### ISSUE TITLE
Ερώτηση για εμφάνιση επιλογής πληρωμής E-Banking

### ISSUE THREAD

**Issue by AinSynagoga** [VivaPayments/API#100]
Χρησιμοποιώντας το api με Redirect Checkout πώς μπορούμε να εμφανίσουμε την επιλογή για πληρωμή μέσω E-Banking? Πρέπει να περάσω κάποιον λογαριασμό τράπεζας στο demo λογαριασμό μου για να βγαίνει ως επιλογή;  Προς το παρόν βλέπω μόνο τις επιλογές 'Κάρτα' και 'Viva Wallet'.

Επίσης πώς μπορώ να απενεργοποιήσω μεν την επιλογή Cash (πληρωμή στα εξουσιοδοτημένα καταστήματα) αλλά να κρατήσω την εμφάνιση του E Banking ως τρόπο πληρωμής; Θέτοντας DisableCash false διαβάζω στο documentation ότι απενεργοποιούνται και τα δύο.

**Comment by dmihos** [comment]
Καλησπέρα
Οι τρόποι πληρωμής Cash/Ebanking ενεργοποιούνται/απενεργοποιούνται με κοινό flag και, για να εμφανιστούν, χρειάζεται επιπλέον να υπάρχει τουλάχιστον 1 ώρα περιθώριο μέχρι τη λήξη του Order (παράμετρος PaymentTimeout)

**Comment by themis1970** [comment]
ΞΕΡΕΤΕ ΠΟΥ ΣΤΕΛΝΕΤΕ ΑΥΤΑ ΤΑ ΜΗΝΗΜΑΤΑ ΓΙΑ ΤΗΝ VIVA...........


www.koronis.com.gr
www.χονδρικη.gr
<http://www.%CF%87%CE%BF%CE%BD%CE%B4%CF%81%CE%B9%CE%BA%CE%B7.gr>
www.xondriki.eu
www.tzamia-tapetsaries.gr

email: koronis1970@gmail.com

ΕΜΠΟΡΙΟ ΕΙΣΑΓΩΓΗ ΚΑΤΑΣΚΕΥΗ
ΞΥΛΟΥ-ΑΛΟΥΜΙΝΙΟΥ.

ΘΕΜΙΣΤΟΚΛΗΣ ΚΟΡΩΝΗΣ
ΤΗΛ.-FAX 22210 22243
MOBILE: 6972699533
TK.34100
ΒΑΛΣΑΜΑ 4
ΧΑΛΚΙΔΑ

****************************************************************
Προσοχή ! Σύμφωνα με το άρθρο 14 του Νόμου 2672/1998 (ΦΕΚ 290 τ.Α)
τα μηνύματα e-mail, για να είναι έγκυρα θα πρέπει να περιέχουν απαραίτητα :
Ονοματεπώνυμο ή επωνυμία (για Νομικό πρόσωπο), ταχυδρομική διεύθυνση
κατοικίας, αριθμό τηλεφώνου ή fax, ιδιότητα του χειριστή.
Αν τα μηνύματα προέρχονται απο υπηρεσία ή Δημόσιο φορέα να περιέχουν
επιπλέον θέμα, ημερομηνία, αριθμό πρωτοκόλλου.
Το μήνυμα ηλεκτρονικού ταχυδρομείου τεκμαίρεται οτι έχει περιέλθει κανονικά
στον λήπτη αν υπάρξει ηλεκτρονική επιβεβαίωση.
 Οι πληροφορίες ή και τυχόν αρχεία που υπάρχουν σε αυτό το ηλεκτρονικό
μήνυμα είναι προσωπικά και απόρρητα
****************************************************************

2016-08-29 15:51 GMT+03:00 Konstantinos Athanasoglou <
notifications@github.com>:
