### ISSUE TITLE
Text not coming through

### ISSUE THREAD

**Issue by john-antunes** [VivaPayments/API#1000]
I'm trying to transfer money from my Viva Wallet Account to my bank account. Normally when I do this, I get sent an SMS code that I need to enter in order to transfer the funds. However, over the last day the SMS code is not coming through despite the system saying it's sent the code. I'm receiving all other text messages so the issue is not on my side.

**Comment by VaiaPatta** [comment]
I have been trying to set up a Viva account and I have run into the same problem. I have tried resending the message, I have tried 3 different phone numbers, I have even tried an address and phone number from a different country. Still nothing.

**Comment by matthewrgourd** [comment]
Hi @john-antunes, @VaiaPatta have you tried [contacting customer service](https://www.vivawallet.com/en-eu/contact-us/).

**Comment by matthewrgourd** [comment]
@john-antunes @VaiaPatta Could you let me know if this is definitely a problem you're experiencing with your live production accounts rather than demo instances?

**Comment by john-antunes** [comment]
Definitely live environment.

Sent from my iPhone

On 12 Nov 2019, at 08:53, matthewrgourd <notifications@github.com> wrote:

﻿

@john-antunes<https://github.com/john-antunes> @VaiaPatta<https://github.com/VaiaPatta> Could you let me know if this is definitely a problem you're experiencing with your live production accounts rather than demo instances?

**Comment by matthewrgourd** [comment]
Please call the [customer service number](https://www.vivawallet.com/en-eu/contact-us/) for your country and ask for a check on your account(s).
