### ISSUE TITLE
Payments Looping

### ISSUE THREAD

**Issue by CBDNutra** [VivaPayments/API#1001]
We've been using Vivawallet for some time and everything has worked fine, however over the last 2 weeks, we've been experiencing problems with people not being able to checkout.

Payment works fine up until you click pay, it directs you to the Vivawallet payment page, you enter in your card details etc, then it just redirects back to the sites cart and you have to start the process all over again. No money is ever debited even though it looks like the payment has gone through - Wordpress simply displays "An error occurred, please try again."

All settings appear to be fine & I've gone through the setup process twice with new codes but the issue still persists.

I've tried contacting support but it has been 3 days and I've had no response, so I am trying here instead.

Any help would be appreciated.

**Comment by VivaWalletSupport** [comment]
Hello, please confirm that the plugin and its instructions are used from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

If so, please provided the following screenshots and we will look into the issue:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by matthewrgourd** [comment]
Hi @CBDNutra, as you've not replied, I'm assuming this is no longer a problem. However, if not, please reopen the issue. Thanks!
