### ISSUE TITLE
Store not found

### ISSUE THREAD

**Issue by Bwerpophile** [VivaPayments/API#1002]
Hi, 

I know the question has been ask many times.  I follow the tutorial for shopify but still don't undestrand where I make a mistake. 

I ask your support team for a store token, I put my Merchant Id at the right position and when I try to do a paiment VivaWallet send me a "Store Not found" I don't get where I'm wrong. 

Any help will be a pleasure.

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear that. Could you confirm the first 10 characters of your [merchantId](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/)? (not ApiKey, not StoreToken)

**Comment by Bwerpophile** [comment]
Hi, 
So this is the 12 first characters of my MerchantId : 15b892e6-0fa

I also want to share that the account is not fully verify yet, I don't know if it change something ?

**Comment by dmihos** [comment]
Do you maybe have the 'Use test mode' checked? You'll have to uncheck this

**Comment by Bwerpophile** [comment]
@dmihos Nope, it is not checked

**Comment by dmihos** [comment]
Then you're not inserting it correctly in the field (maybe leading/trailing spaces or a missing character?)

**Comment by Bwerpophile** [comment]
I did it many times and I'm not copy pasting. I verify many time before I validate I don't get it.

Is it normal that the token desappear when I press validate ?

**Comment by Bwerpophile** [comment]
@matthewrgourd 

The account is now fully verified and I still have the same issue. Is it possible to have an other store token ?

**Comment by dmihos** [comment]
The account verification or the new store token won't help.

The logs show attempts on August 15 in the DEMO store. Did you have the 'Use Test Mode' checked at the time, which you now have unchecked?
Can you try an attempt now?

**Comment by dmihos** [comment]
On further investigation, you are now hitting the production server, so you've now unchecked the Test mode. The error you now get is 'Signature not verified', which means you mistype the store token.
Please use a different browser and try to store the correct store token. This is a problem related to Shopify, not VivaWallet.

**Comment by Bwerpophile** [comment]
All right ! Cool ! Thanks for the helps !

**Comment by Bwerpophile** [comment]
Hi 
I reopen this issu since Shopify told me they don't see them having a problem and cannot answer. 

Where can I ask for a new Store Token I saw that it works on an other issue. 

Thanks

**Comment by matthewrgourd** [comment]
What is the business name, please, and I will see if I can get another Shopify token sent out?

**Comment by Bwerpophile** [comment]
SAS laniakea - Satyva.fr

**Comment by Bwerpophile** [comment]
Thanks

**Comment by matthewrgourd** [comment]
Hi @Bwerpophile we've look into this and the token you were sent initially hasn't been copied and pasted correctly. Please try again with the same token. The upper case L's need to be duplicated verbatim. Hope this helps!

**Comment by Bwerpophile** [comment]
Hi, 

@matthewrgourd  Any update from your side ? 

thanks for you time, 

Joris

**Comment by Bwerpophile** [comment]
There is no upper case L on my store token, I don't get it.

**Comment by matthewrgourd** [comment]
It appears the store token was mistyped. Please try again with the same store token. I've checked and unfortunately we can't create new ones for the same merchant ID. My colleague has checked his logs and we can see that the merchant ID you entered doesn't quite match the one we sent you.

**Comment by Bwerpophile** [comment]
I took the merchant ID from my account on Vivawallet I just copy past it. 

The store token you send me is the one I entered. What are the logs saying, that the store token is wrong or that the merchant ID is wrong ?

**Comment by matthewrgourd** [comment]
Sorry, I meant to say that the logs showed that the **store token** was entered incorrectly. Merchant ID is fine.

**Comment by Bwerpophile** [comment]
Ok and what about the L's that I have to duplicate ?
