### ISSUE TITLE
API v2 Credentials

### ISSUE THREAD

**Issue by Florent420** [VivaPayments/API#1003]
Hello,

I would like to get an access for production.
Waiting for your reply.

Thanks
Florent

**Comment by matthewrgourd** [comment]
Hi @Florent420, 

Thanks for your enquiry. Please can you send answers to the following questions to my email address, mgourd@vivawallet.com:

* API required? E.g. Native Checkout v2 or card tokenization
* Business name?
* Merchant ID?
* Contact email address?

I will then put in the request for the client credentials.

**Comment by Florent420** [comment]
Hello I sent the email on monday Will I got something by this week ?
Thank you

**Comment by matthewrgourd** [comment]
Hi there, on their way in the next 30 minutes! Sorry for the delay...
