### ISSUE TITLE
Recurring Payments

### ISSUE THREAD

**Issue by bertdigital** [VivaPayments/API#1004]
Is there anyway to manually setup recurring payments once we have captured the payment information? My site has a recurring option but currently we have to send out a notification every time so we can recapture payment.

**Comment by matthewrgourd** [comment]
Hi there, apologies, but at the moment, the only Viva Wallet payment product / service that supports recurring payments is [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) but this is for Greek credit cards only.
