### ISSUE TITLE
408 request time out server trying to pay on woocommerce live

### ISSUE THREAD

**Issue by Florent420** [VivaPayments/API#1005]
Hello I have no more way to accept payment on my website.
Could you help me on this ?
The demo mode works smoothly same configuration, same website, but as soon as I pass on live mode I uncheck the test mode box and I change the API credits for live, I got time out request.
Each time I try to pay, I got scrennshots here to let you see the config is right.

https://ibb.co/nCzGYFQ
https://ibb.co/1vwZ1PZ
https://ibb.co/56J117M
https://ibb.co/N3YBFdQ
https://ibb.co/7Kn04d2
https://ibb.co/sbk99fr

Thanks

**Comment by VivaWalletSupport** [comment]
Hello, please check if the live payment source has been activated and is enabled.

**Comment by Florent420** [comment]
Yes it have been activated yesterday I had your support on phone. And I just tried again today without changing anything in the sources, it still not work.

Thank you

**Comment by Florent420** [comment]
You can check here https://ibb.co/LQVVd5J

**Comment by VivaWalletSupport** [comment]
Any errors logged?

**Comment by Florent420** [comment]
Since the demo is working in the current situation and not the live, my question is how it could be possible, I can give you access to everything in mp.
I a not developer and at this moment I do not see any error on my wp backend, apart the 408 time out request on live. I face no issue with all my other plugins and my website is up.

**Comment by Florent420** [comment]
What I see is that the viva wallet plugin is not tested with last version of woocommerce from my side, I downloaded the one from your official support page https://ibb.co/n8mbyDw

**Comment by Florent420** [comment]
Could it be the php version of my server ?

Thanks

**Comment by VivaWalletSupport** [comment]
Please send admin login credentials + FTP credentials to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com to investigate the problem.

**Comment by Florent420** [comment]
Hello,

I just sent the email.

Thank you for your support.

**Comment by VivaWalletSupport** [comment]
Thank you,  you would have to contact your hosting provider to solve the issue, they might have implemented some security that prevents connecting to the live environment from Viva. This issue is identical with issue https://github.com/VivaPayments/API/issues/986 (same hosting provider). 

From my server I do not have any problem connecting with the live environment using your Viva credentials and your payment source.

**Comment by Florent420** [comment]
Hi, great support from you on sunday :)
I will contact them, but please let this ticket open until I got the answer from them.

**Comment by Florent420** [comment]
Hello, Ovh just answered saying That I must turn off firewall. I did it, but after trying again to pay I got again blank page. Can you prove That everything works from your side as you claim ?

Thanks

**Comment by Florent420** [comment]
Also I asked for API V2 creditentials on another issue, but no answer, anyway if my server cannot communicate with yours even native integration may be complicated.

Thanks

**Comment by VivaWalletSupport** [comment]
Using your credentials with live mode (unchecked Test mode in plugin settings): http://prntscr.com/oujxav

**Comment by Florent420** [comment]
Ok I understand but if you banned the ip address of the cluster of my Hosting provider it won't work from my side.
Your own server is certainly not Blacklist from your system. https://ibb.co/RyrNxFf
Check on That link if you translate they said this kind of issue is due to ip Blacklist, I got no firewall nor Blacklist ip from my side..

**Comment by Florent420** [comment]
Also could you give me in mp or email the ip address from where the requests are made then I double check with OVH if your ip can be Whitelisted, I Will give you my ip if you need.
Thank you

**Comment by Florent420** [comment]
Ticket close I changed the Hosting provider and now it works Thank you !
