### ISSUE TITLE
Viva Wallet Server Error in '/web' Application

### ISSUE THREAD

**Issue by Cristinawork** [VivaPayments/API#1006]
In the last week trying to make payment from website with the Viva Wallet simple checkout (not demo, live mode, which worked until few days ago), it gives error:
Server Error in '/web' Application
Runtime Error
Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine. 

Details: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".
....

**Comment by matthewrgourd** [comment]
Hi there, this sounds like a problem with your server configuration rather than something at our end. If possible, can you provide screenshots of the errors as and when they occur, blurring out any security information. Thanks!

**Comment by Cristinawork** [comment]
Hello, thank you.
It worked fine, nothing has changed. Error page should not be required since there are no errors.
I try to attach screenshot.
![viva](https://user-images.githubusercontent.com/40292151/63508154-09592180-c4e2-11e9-81bd-c6ac4dcc8d22.jpg)

**Comment by Cristinawork** [comment]
I found out what it was, it should have written in error message not to use special characters in the payment text, I removed it and it works now. So wrong message Server error it should be Watch out special chars in payment text!

**Comment by matthewrgourd** [comment]
Hi @Cristinawork good to hear you've managed to resolve this, sorry not to be of more help. We'll make a note of this in the documentation.
