### ISSUE TITLE
Pending Payment WooCommerce orders

### ISSUE THREAD

**Issue by pixelpudding** [VivaPayments/API#1007]
We're using the official WooCommerce plugin and seem to have a large number of orders that are stuck in the 'Pending Payment' status.

Viva Wallet is the only payment option available on the store. medahuman.com

This isn't the case with all orders, but we seem to have about 20-25% of orders staying in Pending Payment status. Is there any way of seeing what happens with these customers? We've had emails from a couple of these customers claiming that they completed the payment but didn't ever receive a confirmation email. Looking on Viva Wallet, the money hasn't come in for these orders, so I'm not sure if their reports are incorrect, if there is a visible error or something else going on. 

Could you recommend how we could potentially look into this issue? 

Here are our settings.

![62063181-52d78900-b222-11e9-8827-bee3ca7fe3c1](https://user-images.githubusercontent.com/34652948/63276453-50090a80-c29b-11e9-96c1-c95aaa686c18.png)
![62063183-52d78900-b222-11e9-9b5c-a3d6a2d99bc2](https://user-images.githubusercontent.com/34652948/63276456-50090a80-c29b-11e9-8cbd-ae3bcffbdcd5.png)
![62063184-52d78900-b222-11e9-8ebb-b10afa60e968](https://user-images.githubusercontent.com/34652948/63276457-50090a80-c29b-11e9-9ab9-18b819d94594.png)
![Screenshot 2019-08-19 16 02 10](https://user-images.githubusercontent.com/34652948/63276458-50a1a100-c29b-11e9-8767-f9bcdd9335ae.png)

**Comment by VivaWalletSupport** [comment]
Hello, in case the transactions for these orders failed, it is logic that no money is received in your account and that these orders statusses have not been updated. You might search in your Viva account for the specific (failed) transaction attempts.

**Comment by pixelpudding** [comment]
We're not receiving money for these order and I can only see 1 failed transactions in Viva Wallet.

**Comment by VivaWalletSupport** [comment]
I cannot see why a transaction was abanodonned or why it failed, plugin wise the working is correct. You might contact you Viva account manager if he can see anything else.

**Comment by matthewrgourd** [comment]
@pixelpudding Please call us on (+44) 20 3734 7770
