### ISSUE TITLE
API viva wallet new payment source

### ISSUE THREAD

**Issue by candabulous** [VivaPayments/API#1008]
![303DB8DB-B377-4D72-8929-0FC7E2F5E937](https://user-images.githubusercontent.com/54313552/63341868-15a67880-c342-11e9-862b-7984e1f97b20.jpeg)
I want all the processed transaction funds from this Shopify shop and thus domain to be routed to a particular wallet. I’m told this can be done. Only there is an issue with the path as Shopify tell me that the url is dynamic I.e 
The standard URL checkout for the Thank you page of Shopify: [Domain].com/shop_id/checkouts/**checkout_token**/thank_you

**Comment by dmihos** [comment]
Integration with Shopify is not handled via Payment Sources you can edit.
I'm afraid what you ask for is not currently possible, but you can always email support team and ask.
