### ISSUE TITLE
Direct Shopify Viva Wallet Payment to different account

### ISSUE THREAD

**Issue by ORHADMIN** [VivaPayments/API#1009]
I have two accounts in our Viva Wallet,

We have multiple shopify accounts poitning to our Primary account, but we have another business account in our Viva wallet.

In this second account we have a WooCommerce site pointing payments correctly to our secondary account, but we have a Shopify site that we want to point into our secondary account but these Shopify payments seem to be directed to our primary account.

How do I direct these payments to our secondary wallet rather than our primary wallet?

**Comment by matthewrgourd** [comment]
Hi there, I believe you need to [request a new store token](https://viva.microsoftcrmportals.com/shopify/) using the Merchant ID for the secondary account, then set up Shopify as instructed in our [Shopify guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/).
