### ISSUE TITLE
Viva Generic Urls

### ISSUE THREAD

**Issue by ddrosatos** [VivaPayments/API#101]
Καλησπέρα.

Θα ήθελα να ρωτήσω αν υπάρχει τρόπος στα redirect url απο την Viva να βάλω κάποια παράμετρο που να την στέλνω σαν tags απο το Optional Parameters.

**Comment by dmihos** [comment]
Καλημέρα ddrosatos
Μπορείτε να κάνετε χρήση των OrderTags κατά τη δημιουργία του Order.
Έπειτα, στη success/fail σελίδα σας, μπορείτε να δείτε τα tags.
https://github.com/VivaPayments/API/wiki/Optional-Parameters

**Comment by ddrosatos** [comment]
Σας ευχαριστώ πολύ.
