### ISSUE TITLE
API v2 Credentials

### ISSUE THREAD

**Issue by theremon** [VivaPayments/API#1010]
Hello

please provide API v2 credentials for the following accounts (production and demo):

business name: CHOES LIMITED
environment requested: DEMO

business name: CHOES LIMITED
environment requested: PRODUCTION

**Comment by matthewrgourd** [comment]
Hi there, please can you send exactly the same information to mgourd@vivawallet.com and remove the above post except for your company name? I would advise this for the sake of security as this is a public forum.

**Comment by theremon** [comment]
Thank you, email sent
