### ISSUE TITLE
Viva Wallet for WooCommerce – at checkout "this site is experiencing technical issues" (error message)

### ISSUE THREAD

**Issue by matthewrgourd** [VivaPayments/API#1013]
https://github.com/neonvaperz/abbiesmith/issues/1#issue-484473656

This is a copy of an issue which should have been raised here.

"I have set up Viva Wallet with WooCommerce going through the steps I was given correctly. It lets me type name and address but when I go to checkout with Viva Wallet it sends to this page. Can anyone help me please?

I downloaded it from the Viva Wallet website. I had the [instructions](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) for set up with WooCommerce sent to me. The link was in there.

Thanks
Abbie
Neon Vaperz"

**Comment by VivaWalletSupport** [comment]
Hello, please provided the following screenshots and we will look into the issue:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by neonvaperz** [comment]
Hi, where can i find the other information please. 


<img width="1131" alt="Screenshot 2019-08-28 at 13 46 37" src="https://user-images.githubusercontent.com/54439222/63856752-474ebd80-c99a-11e9-84b8-9514d51739a0.png">


<img width="1280" alt="Screenshot 2019-08-28 at 13 41 57" src="https://user-images.githubusercontent.com/54439222/63856650-0ce52080-c99a-11e9-87e1-e2325ec4e0fa.png">
<img width="1280" alt="Screenshot 2019-08-28 at 13 42 30" src="https://user-images.githubusercontent.com/54439222/63856652-0d7db700-c99a-11e9-9cdf-1b05ca692e32.png">

Thanks
Abbie

**Comment by VivaWalletSupport** [comment]
See for example https://github.com/VivaPayments/API/issues/1007

**Comment by neonvaperz** [comment]
thankyou

<img width="1280" alt="Screenshot 2019-08-28 at 14 53 03" src="https://user-images.githubusercontent.com/54439222/63862138-0065c580-c9a4-11e9-85ce-1ed5ed951d77.png">
<img width="1280" alt="Screenshot 2019-08-28 at 14 52 59" src="https://user-images.githubusercontent.com/54439222/63862139-0065c580-c9a4-11e9-87fb-7784065aead0.png">
<img width="1277" alt="Screenshot 2019-08-28 at 14 54 07" src="https://user-images.githubusercontent.com/54439222/63862140-0065c580-c9a4-11e9-8647-107a1c9b38f7.png">

**Comment by VivaWalletSupport** [comment]
1. In the payment source remove the www. part from the Domain Name (it is not used by your store).
2. In the plugin setting specify the correct Source Code: 6289

**Comment by neonvaperz** [comment]
I have just done that thankyou

**Comment by neonvaperz** [comment]
back to pending so just got to wait for it to activate again :)
