### ISSUE TITLE
Show me page not found(404) after successful payment(Redirection Issue) 

### ISSUE THREAD

**Issue by nimspatel** [VivaPayments/API#1014]
I am having an issue with the viva wallet plugin in wordpress.

After making a payment - customers are not **redirected properly** to our order-success page or order-not-successful page.

I have set **URL** and **parameter** like this 

![Image1](https://user-images.githubusercontent.com/16508401/63856848-39139800-c9c0-11e9-8ec5-d07ef72ba507.png)

but still after success shows me URL like this

![Image2](https://user-images.githubusercontent.com/16508401/63856873-49c40e00-c9c0-11e9-9f80-233acbef94ec.png)

**Comment by VivaWalletSupport** [comment]
Hello, use the plugin and follow the instructions to the letter from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by nimspatel** [comment]
Hello @VivaWalletSupport 

I have facing an issue when I create a webhook.
Please check :
![Issue](https://user-images.githubusercontent.com/16508401/63942055-91af6780-ca8a-11e9-92f7-27c3f332a718.png)

I have set Payment Source like this :
![Settings](https://user-images.githubusercontent.com/16508401/63942233-ebb02d00-ca8a-11e9-8d99-db9fa6e2d1f5.png)

Thanks

**Comment by VivaWalletSupport** [comment]
Did you follow the instructions and did you manage to setup correctly the order payments before proceeding to the webhook feature?

**Comment by nimspatel** [comment]
Yes, I have followed the instructions and I did manage to setup correctly. But still, I have facing an issue.
@matthewrgourd @VivaWalletSupport

**Comment by VivaWalletSupport** [comment]
Please confirm that the basic integrations is working correctly now when placing an order, transaction ok, order status is updates as set in the plugin settings (processing/complete).

**Comment by nimspatel** [comment]
Hello,

I have set setting like this Please check and let me know it is correct or not.

Plugin Setting :
![screencapture-elixicureeurope-wp-admin-admin-php-2019-08-30-12_30_56](https://user-images.githubusercontent.com/16508401/64000331-1cdc3c00-cb23-11e9-9e71-844772c6d362.png)

Vivawallet Settings :
![download](https://user-images.githubusercontent.com/16508401/64000381-409f8200-cb23-11e9-9504-d7f1db8faab2.png)

When Creating a webhook then show me this error:
![Screenshot_4](https://user-images.githubusercontent.com/16508401/64000434-5d3bba00-cb23-11e9-8b31-506b11a03e0e.png)

Thanks

**Comment by VivaWalletSupport** [comment]
Please forget about the webhook for the moment and try to answer my previous question in order to be able to provide assistance.

**Comment by nimspatel** [comment]
Yes, it is working properly.

Can you confirm again settings is correct or not
https://user-images.githubusercontent.com/16508401/64000331-1cdc3c00-cb23-11e9-9e71-844772c6d362.png

https://user-images.githubusercontent.com/16508401/64000381-409f8200-cb23-11e9-9504-d7f1db8faab2.png

Thanks
@VivaWalletSupport @matthewrgourd

**Comment by VivaWalletSupport** [comment]
Please provide the following screenshots and we will look into the issue:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by nimspatel** [comment]
Hello @VivaWalletSupport @matthewrgourd 

Payment plugin settings (mask the API Key).
![payment](https://user-images.githubusercontent.com/16508401/64014942-0d6beb80-cb41-11e9-8342-946d2521634e.png)

Viva Wallet payment source settings (include the browser's URL in the screenshot).
![vivawallet2](https://user-images.githubusercontent.com/16508401/64015304-d944fa80-cb41-11e9-87ca-e81cf70f13f7.png)

Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
![website_app](https://user-images.githubusercontent.com/16508401/64015347-faa5e680-cb41-11e9-984d-732c92432083.png)

API Access page (mask API Key, include the browser's URL in the screenshot).
![api](https://user-images.githubusercontent.com/16508401/64015381-072a3f00-cb42-11e9-9540-b01b300bdd35.png)

Thanks

**Comment by VivaWalletSupport** [comment]
I cannot verify the screenshots as you did not included the browser URLs in the last 2 and not all required screenshots are provided also you covered the full Merchant ID. See for example issue https://github.com/VivaPayments/API/issues/1007 on what to provide exactly. Also see that you are using source code 1309 in your plugin, in your source listing screenhot this source does not exits, you would not even be able to make a normal transaction like that.

**Comment by nimspatel** [comment]
![1](https://user-images.githubusercontent.com/16508401/64102195-1224df80-cd8d-11e9-9b74-701e6b390c02.png)
![2](https://user-images.githubusercontent.com/16508401/64102196-1224df80-cd8d-11e9-8850-ec8a4db805ac.png)

**Comment by VivaWalletSupport** [comment]
Please provide the following 4 screenshots and we will look into the issue:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

PS, do not cover the complete Merchant ID.
See for example issue #1007 on what to provide exactly.

**Comment by nimspatel** [comment]
I have attached all screenshots as you said. When I checkout my order it gives me error that screenshot attached too.

![plugin_settings](https://user-images.githubusercontent.com/16508401/64114661-3099d380-cdab-11e9-9623-9236339d4c98.png)
![GL](https://user-images.githubusercontent.com/16508401/64114666-35f71e00-cdab-11e9-9cb6-d61506ca904e.png)
![apps](https://user-images.githubusercontent.com/16508401/64114679-3a233b80-cdab-11e9-8284-bc3aede2f58d.png)
![api-acces](https://user-images.githubusercontent.com/16508401/64114680-3a233b80-cdab-11e9-9b3f-214a916ec539.png)

This one is checkout Error screenshot:

![checkout_error](https://user-images.githubusercontent.com/16508401/64114692-40191c80-cdab-11e9-98e1-ca7bcac8c817.png)

**Comment by VivaWalletSupport** [comment]
Did you use a live credit card with sufficient funds? Did you try another card?
To verfy the working I would recommend to setup first using the demo account and using the special test card.

**Comment by mittunsupport** [comment]
Hello @VivaWalletSupport 

How can I  setup the demo account and using the special test card?

Thanks

**Comment by nimspatel** [comment]
Hello @VivaWalletSupport

How can I setup the demo account and using the special test card?

Thanks

**Comment by VivaWalletSupport** [comment]
https://demo.vivapayments.com/en/signup enable Test mode in the plugin settings and configure the plugin with the values from the demo environment.

To simulate a successful payment on the demo environment, use the card number 4111111111111111 with any valid date and 111 for the CVV2.

**Comment by nimspatel** [comment]
Thanks @VivaWalletSupport 

It is fixed now on my hand.

**Comment by agrippaold** [comment]
Hello @nimspatel how you solve this issue i have the same

Thank you so much 

Riccardo
