### ISSUE TITLE
Sometimes my MerchantTrns on 'Transaction Payment Created' webhook is "PE"

### ISSUE THREAD

**Issue by shahzaibmuneeb** [VivaPayments/API#1015]
Hi,

Sometimes for my MerchantTrns on the 'Transaction Payment Created'  webhook I get "PE" - what could be causing this? The payments do always go through.

`{
...
MerchantTrns: 'PE',
...
}`

Why is this happening? 

EDIT: Also sometimes the webhook isn't even called? Everything was working flawlessly until very recently.

**Comment by matthewrgourd** [comment]
Which or our e-commerce plugins, online checkouts, or APIs are you using. Please can we have a few more details. Thanks!

**Comment by matthewrgourd** [comment]
Hi @shahzaibmuneeb , as you've not replied, I'm assuming this is no longer a problem. However, if not, please reopen the issue. Thanks!
