### ISSUE TITLE
@Urgent - Ακυρωμένες παραγγελείες χωρίς κάποιο τεχνικό πρόβλημα.

### ISSUE THREAD

**Issue by ntourziotis** [VivaPayments/API#1017]
Αγαπητή ομάδα καλησπέρα,

Εδώ και κάποιες ημέρες παρουσιάζεται πρόβλημα με τις ηλεκτρονικές συναλλαγές στο eshop μας
https://petpanic.gr

Το πρόβλημα παρουσιάζεται συγκεκριμένα στη πληρωμή με κάρτα. Χρησιμοποιούμε το plugin σας (viva payment) εδώ και αρκετά χρόνια με επιτυχία. Ωστόσο το τελευταίο καιρό μας δημιουργούνται θέματα με τις πληρωμές, **αλλά όχι συνέχεια** στην ολοκλήρωση της παραγγελίας. 

Συγκεκριμένα στην περίπτωση που όλα πηγαίνουν μια χαρά

1) Η παραγγελία φεύγει από το site, πηγαίνει στη Viva, https://prnt.sc/oy4zp0
2) Γίνεται η πληρωμή, επιστρέφουμε στο site, https://prnt.sc/oy56ww 
3) Έρχεται email με το invoice https://prnt.sc/oy57bz
4) Γίνεται confirmed στο σύστημα: https://prnt.sc/oy5958 

Στην περίπτωση που δεν πάει καλά δεν ολοκληρώνεται η παραγγελία στην πλευρά σας με αποτέλεσμα να εμφανίζεται ακυρωμένη στο σύστημα μας.
ενδεικτικά παράδειγματα αποτυχημένων προσπάθειων 

Order Number       Name
579e017895           Θεανω Παπαναγιώτου
565f017887            Ελένη Δρακοπούλου
89ce017883           ΜΑΡΙΑ ΤΕΝΤΖΕΡΑΚΗ
719c017876           Ίννα Ταράσκα
9c49017868           Αργέττα Βαρρηά
3ecb017860           Nikolaos Mastorakis

Μπορείτε σας παρακαλώ να με βοηθήσετε να κατανοήσουμε το πρόβλημα και να το διορθώσουμε άμεσα, γιατί δημιουργεί θέμα στην επιχείρηση μας? 

Για οποιαδήποτε απορία παραμένω στη διάθεση σας.

Με εκτίμηση 

Ντουρζιώτης Γιάννης

**Comment by VivaWalletSupport** [comment]
Hello, please download the latest plugin and use the instructions from https://developer.vivawallet.com/e-commerce-plugins/

**Comment by ntourziotis** [comment]
Thanks a lot for your support!

I Just installed the new plugin and everything looks fine.Just a small issue to check,At the Viva payment page, https://prnt.sc/oz6331 Could you please redirect back to the site?

I think it stucks there.

Best regards

Ioannis

**Comment by VivaWalletSupport** [comment]
Looks you are not using a payment source that you should have setup in your Viva account (source code should be set in the plugin settings).

**Comment by ntourziotis** [comment]
thanks for your advice but plugin has the same settings (working) with the previous plugin version and still not working properly. 

Order Status for Pending transactions : pending
Order Status for Successful transactions : confirmed
Order Status for Failed or Cancelled transactions : cancel

My main issues are:

1) Not redirect to the site after success order.
2) As a result the order still stay pending and the client never receipt the invoice. Need admin to manual change it to confirmed.

Could you please check and let me know?

Best regards

Ioannis

**Comment by VivaWalletSupport** [comment]
Please provide the following screenshots and we will look into the issue:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by ntourziotis** [comment]
Thank you very much

Payment plugin settings (mask the API Key). --> https://prnt.sc/p0n7hq
Viva Wallet payment source settings (include the browser's URL in the screenshot). --> https://prnt.sc/p0nd0b
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot). --> https://prnt.sc/p0nf67
API Access page (mask API Key, include the browser's URL in the screenshot). --> Dont know where to find exactly.  Please provide some help here.

Best regards

Ioannis

**Comment by VivaWalletSupport** [comment]
See issue https://github.com/VivaPayments/API/issues/1007 for an example regarding the screenshots.

**Comment by ntourziotis** [comment]
Please check this : https://prnt.sc/p0o9y8

**Comment by VivaWalletSupport** [comment]
Please post the 4 requested screenshots as done at issue https://github.com/VivaPayments/API/issues/1007

**Comment by ntourziotis** [comment]
Greetings team, 

I have the 3/4 screenshots (please check attached). Could you please let me know where should I find the pending one?

Best regards

Ioannis 

![1](https://user-images.githubusercontent.com/54627473/64163654-59bd7100-ce4a-11e9-978c-0aa8f83ce31c.jpg)
![2](https://user-images.githubusercontent.com/54627473/64163655-59bd7100-ce4a-11e9-8fae-908cab9f0db5.jpg)
![3](https://user-images.githubusercontent.com/54627473/64163658-5a560780-ce4a-11e9-9e6c-9fa26ea7b55b.jpg)

**Comment by VivaWalletSupport** [comment]
See point 5 on how to correcly configure the payment source https://developer.vivawallet.com/e-commerce-plugins/virtuemart2/
The return URLs you are using are not valid for this plugin, also protocol should be https as your site does not use http and domain name should be petpanic.gr as your site does not use the www. part.

**Comment by ntourziotis** [comment]
Good morning team, 

We are still facing the issue!  I tried to change the configuration and the system and we are waiting an aggrement from Viva Payment (still) . Please check the attached screenshot. Also i am trying to add the link below and the system denied . Please check attached screenshot.

Best regards

Ioannis 

![1](https://user-images.githubusercontent.com/54627473/64320292-e0975880-cfc6-11e9-97fb-1690e5e50d63.jpg)
![2](https://user-images.githubusercontent.com/54627473/64320293-e0975880-cfc6-11e9-92bb-a9ed499dbab6.jpg)
![3](https://user-images.githubusercontent.com/54627473/64320310-ea20c080-cfc6-11e9-9871-822b069b6e35.jpg)

**Comment by VivaWalletSupport** [comment]
Hello, still see you have not the correct return URLs in your payment source as mentioned before (See point 5 on how to correcly configure the payment source https://developer.vivawallet.com/e-commerce-plugins/virtuemart2/). Also you would have to wait after making the modifications until yhe source has been activated.
