### ISSUE TITLE
SimpleCheckout null data on demo response

### ISSUE THREAD

**Issue by JulioIbro** [VivaPayments/API#1019]
I have implemented a button that creates a token and then send's it at the demo environment. 

My implementation is in PHP:

```
function Charge($viva_token)
{
	
	$data = 'PaymentToken='.$viva_token;
	
	$url = 'https://demo.vivapayments.com/api/transactions';
	$m_id = 'XXXXXXXXXXXXXXX';
	$api_key = 'XXXXXX';
	$curl = curl_init($url);

	curl_setopt($curl, CURLOPT_POST, true);
	curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
	curl_setopt($curl, CURLOPT_USERPWD, $m_id.':'.$api_key);
	curl_setopt($curl, CURLOPT_HEADER, true);
	curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
	curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
	
	curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
	
	$response = curl_exec($curl);
	
	curl_close($curl);
	
	return $response;
}

```

My problem is that i got the below response after the submit, 200 OK but returns null data:

`200 OK Server: nginx Date: Thu, 29 Aug 2019 17:17:15 GMT Content-Type: application/json; charset=utf-8 Content-Length: 318 Connection: keep-alive X-Viva-CorrelationId: 19-241-F69C88D X-Powered-By: ASP.NET {"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":400,"ErrorText":null,"TimeStamp":"2019-08-29T20:17:15.3547909+03:00","CorrelationId":null,"EventId":0,"Success":false}`

**Comment by JulioIbro** [comment]
has anyone a working code for simple checkout? php or js preffered. I can't make it work, i am following the documentation but i can't have a completed test transaction. Any help will be appreciated

**Comment by matthewrgourd** [comment]
Hi @JulioIbro sorry to hear this. Can you send your Merchant ID to mgourd@vivawallet.com and I'll check your account. Thanks!

**Comment by matthewrgourd** [comment]
Hi @JulioIbro please send your Merchant ID to my email address (mgourd@vivawallet.com) referencing this issue and I'll hopefully be able to fix for you.

**Comment by matthewrgourd** [comment]
Closing as no response.
