### ISSUE TITLE
Transaction related queries related to orders management

### ISSUE THREAD

**Issue by christianago** [VivaPayments/API#102]
Hello.
I have some queries regarding the Viva API.
I need to implement the API on web and mobile apps that currently are in development.
So my queries are:
1. Can I authorize and/or tokenize the card's details for later use, e.g. for charging/clearing after a couple of days or weeks? I cannot save the card details on the database, so is it possible to have a token or a reference of the client's card?
2. Can I void or a refund a transaction that has taken place (cleared) in the past? Consider I have the the transaction id or any other related data to the transactions' response.
3. Does the API support commission to another cardholder or Viva Wallet account except the main cardholder?

Thank you for consider my ticket.

**Comment by dmihos** [comment]
Hi christianago
Regarding your questions:
1. The only way for you to do this is with [Recurring Payments](https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction). You will need a successful transaction and a user consent for this
2. Yes, you can void a transaction the same day it was created on and refund it (even fully) from there on. More at [Cancel Transaction](https://github.com/VivaPayments/API/wiki/CancelTransaction)
3. No, this is not currently supported

Regards

**Comment by christianago** [comment]
Thank you for answering my ticket.
The info you provided was very helpful in regards with the selection of the right payment API for my needs.
