### ISSUE TITLE
API V2 Client Credentials

### ISSUE THREAD

**Issue by monogios** [VivaPayments/API#1020]
@matthewrgourd  I've sent you an email regarding API V2 Client Credentials 3 days ago with all required information. Do I need to contact another person or I should wait for your reply?

**Comment by matthewrgourd** [comment]
Hi @monogios Thanks for sending that. I chased with the developer handling these types of request yesterday. Will do so again today. Sorry for any inconvenience caused.

**Comment by matthewrgourd** [comment]
Hi @monogios please check your email in the next hour!

**Comment by monogios** [comment]
Thank you @matthewrgourd !
