### ISSUE TITLE
Viva Wallet plugin for Magento issue

### ISSUE THREAD

**Issue by matthewrgourd** [VivaPayments/API#1021]
Hi there,

This is on behalf of a customer but please can you look into when you have a spare moment?

Thanks!

> We are still having problems if a customer accidentally puts makes an error when putting in his card details they get the following message
>  
> Fatal error: Call to a member function getId() on a non-object in /domains/nationwidepharmacies.co.uk/http/app/code/local/Mage/Vivawallet/Helper/Checkout.php on line 64  
>  
> Can you get this sorted please. Many thanks.
> 
> Kind regards
> 
> David K Harrison
> 
> C.E.O.
> Nationwide Pharmacies Ltd

**Comment by VivaWalletSupport** [comment]
In case this happens on a Magento 1.9.4.x installation using the latest version of the plugin with a failed transaction attempt, I am not able to replicate the problem.

**Comment by matthewrgourd** [comment]
We're checking this but I'm fairly certain the merchant is using one of our plugins for Magento.

**Comment by matthewrgourd** [comment]
@VivaWalletSupport Merchant has replied back by email saying they're using Magento 1.702 and Viva Wallet 100. Can I have your response here, please, and I'll get back to them?

**Comment by VivaWalletSupport** [comment]
I am not able to replicate the issue on the latest Magento 1.9 version. I would recommed that the client updates his Magento installation to the latest 1.9 version to see if that resolves the problem.
