### ISSUE TITLE
Prestashop 1.6 Πρόβλημα με μετάφραση όταν έχουμε δόσεις

### ISSUE THREAD

**Issue by CW737** [VivaPayments/API#1022]
Έχω μεταφράσει όλα τα πεδία και όταν έχουμε εφάπαξ πληρωμή όλα κάλα. Όταν ενεργοποιείται η επιλογή των δόσεων ορισμένα πεδία δεν μεταφράζονται, οπώς στην φωτογραφία:
![viva](https://user-images.githubusercontent.com/54856514/64190016-1ed53080-ce7e-11e9-824c-055360df9fd7.jpg)
Πως θα μεταφράσω και αυτά; Έβαλα την μετάφραση στα αντίστοιχα πεδία που βρήκα στο back office:
![viva-2](https://user-images.githubusercontent.com/54856514/64190190-77a4c900-ce7e-11e9-9d1b-bde010d8e151.jpg)
αλλά η μετάφραση δεν εμφανίζεται. Επίσης δεν βρήκα κάποιο αρχείο php για να την άλλαζα κατευθείαν από εκεί.

**Comment by VivaWalletSupport** [comment]
Hello, this is due to a compatiblity issue between old and newer versions of PrestaShop. Edit the translation files and rename all vivawalletold and vivawalletlatest wording to vivawallet.
