### ISSUE TITLE
Payments Cancelled on WooCommerce

### ISSUE THREAD

**Issue by VapeCargo** [VivaPayments/API#1024]
When a customer places an order on WooCommerce and clicks "check out" after selecting Vivawallet as the payment method the following message appears 

404 - File or directory not found

The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.**

https://www.vivapayments.com/web/newtransaction.aspx?Ref=

Please oculd you advis ehow this can be resolved so that we can start recievenig payments as payments are being cancelled via woocommerce

Thanks

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following screenshots and we will look into the issue:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

See for an example issue #1007

**Comment by VapeCargo** [comment]
Hello,

Please find attached requested screenshots

![image](https://user-images.githubusercontent.com/54898875/64369010-53c6bc00-d013-11e9-93be-020beebe7412.png)

![image](https://user-images.githubusercontent.com/54898875/64369239-cdf74080-d013-11e9-9881-e9cb94aa94bd.png)

![image](https://user-images.githubusercontent.com/54898875/64369294-ee26ff80-d013-11e9-8062-dd6fbc1389d7.png)

![image](https://user-images.githubusercontent.com/54898875/64369411-39411280-d014-11e9-9e46-89ca46e768ec.png)

Many Thanks in advance

**Comment by VapeCargo** [comment]
Hi there, 

You have asked us for screenshots of what the issues are and no one decided to GET BACK TO US!!! Its been 7 days and the issue still has not been fixed i find it ridiculous, why ask for something if no one is going to help us resolve the situation!! 
We have received no support whatsoever in regards to this, and the gateway has not been working since we signed up! find it rather awful

Can someone get back to us and resolve this issue? Otherwise i will be looking for a different company.

**Comment by VivaWalletSupport** [comment]
Hello and sorry for the delay. Please try to post accurately the requested information, including the browsers URL. See issue https://github.com/VivaPayments/API/issues/1007 for an example.

**Comment by VapeCargo** [comment]
![64369010-53c6bc00-d013-11e9-93be-020beebe7412](https://user-images.githubusercontent.com/54898875/64729089-55412a00-d4d4-11e9-8f97-1a1583f488fe.png)

**Comment by VapeCargo** [comment]
<img width="605" alt="Capture" src="https://user-images.githubusercontent.com/54898875/64729326-def0f780-d4d4-11e9-8fbe-73cf8267e5b1.PNG">

**Comment by VapeCargo** [comment]
<img width="942" alt="Capture" src="https://user-images.githubusercontent.com/54898875/64729390-f7611200-d4d4-11e9-92b3-41ee783758f3.PNG">

**Comment by VapeCargo** [comment]
<img width="738" alt="Capture" src="https://user-images.githubusercontent.com/54898875/64729496-2d9e9180-d4d5-11e9-996d-5a8582e5e5b3.PNG">

**Comment by VapeCargo** [comment]
Hi Please find attached images wih Page URL's

Many Thanks

**Comment by VivaWalletSupport** [comment]
Thank you, please try following:
Change the API Key in your Viva account and adjust it accordingly in the plugin settings.
