### ISSUE TITLE
Viva Wallet for Drupal Commerce

### ISSUE THREAD

**Issue by orangutangle** [VivaPayments/API#1025]
I have an issue with Viva Wallet for Drupal Commerce. I have installed as per [the instructions](https://developer.vivawallet.com/e-commerce-plugins/drupal-commerce/). However, the payment process is failing silently on the payment page of the checkout. I think the redirection to Viva Wallet is failing.

I am debugging variable values throughout the module code in watchdog. commerce_vivawallet_build_redirect_form is completing, as is commerce_vivawallet_form_commerce_checkout_form_payment_alter. However, commerce_vivawallet_create_transaction never fires.

Any ideas as to why the redirect is failing?

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following screenshots and we will look into the issue:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by orangutangle** [comment]
![Screen Shot 2019-09-04 at 17 23 23](https://user-images.githubusercontent.com/20044823/64273582-8308fa80-cf39-11e9-94d7-7e26fd18433d.png)
![Screen Shot 2019-09-04 at 17 26 17](https://user-images.githubusercontent.com/20044823/64273595-88664500-cf39-11e9-9f50-a59c59bf9251.png)
![Screen Shot 2019-09-04 at 17 25 13](https://user-images.githubusercontent.com/20044823/64273601-8c926280-cf39-11e9-9246-5ea41805e47c.png)
![Screen Shot 2019-09-04 at 17 24 32](https://user-images.githubusercontent.com/20044823/64273606-8f8d5300-cf39-11e9-9643-879308349fdb.png)

**Comment by VivaWalletSupport** [comment]
Could you add the missing Websites/Apps image (see 3rd image at issue https://github.com/VivaPayments/API/issues/1007).

**Comment by orangutangle** [comment]
![Screen Shot 2019-09-05 at 09 13 55](https://user-images.githubusercontent.com/20044823/64324100-9e1d4e00-cfbd-11e9-9b94-58b8aeb95dc5.png)

**Comment by orangutangle** [comment]
Sorry, closed in error.

**Comment by VivaWalletSupport** [comment]
What version of Drupal and Commerce are used, are there any errors logged?

**Comment by orangutangle** [comment]
drupal 7.67
commerce 7.x-1.14+20-dev

No errors logged to Recent log messages.

**Comment by VivaWalletSupport** [comment]
Just tested, but cannot find any problem. Try changing the lines $response = curl_exec($curl); to $response = curl_exec($curl) or die("cURL Error" . curl_error($curl)); in the commerce_vivawallet.module file, or do a die on the response like die(print_r($response)); before the try sequence to see if any error comes up.
