### ISSUE TITLE
Issue with Magento 2.3 plugin

### ISSUE THREAD

**Issue by onnetgr** [VivaPayments/API#1026]
Hello.
I am running Magento 2.3.2 and I installed the plugin for Magento 2.3
When I enter payment method "Viva Payments" with redirect, it comes an error

1 exception(s):
Exception #0 (Exception): Notice: Trying to get property 'ErrorCode' of non-object in /home/onnetgr/public_html/app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 202

Exception #0 (Exception): Notice: Trying to get property 'ErrorCode' of non-object in /home/onnetgr/public_html/app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 202
<pre>#1 Ced\VivaPayments\Model\PaymentMethod->getPostHTML() called at [generated/code/Ced/VivaPayments/Model/PaymentMethod/Interceptor.php:63]
#2 Ced\VivaPayments\Model\PaymentMethod\Interceptor->getPostHTML() called at [app/code/Ced/VivaPayments/Controller/Checkout/Start.php:40]
#3 Ced\VivaPayments\Controller\Checkout\Start->execute() called at [generated/code/Ced/VivaPayments/Controller/Checkout/Start/Interceptor.php:24]
#4 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#5 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#6 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#7 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callPlugins() called at [generated/code/Ced/VivaPayments/Controller/Checkout/Start/Interceptor.php:39]
#9 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#10 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#11 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#12 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#13 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#14 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#15 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#16 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#17 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#18 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#19 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:137]
#20 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#21 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#22 Magento\Framework\App\Bootstrap->run() called at [index.php:39]
</pre>

**Comment by VivaWalletSupport** [comment]
Hello, most likely you have made a mistake with your setup. I would advise to setup first with the demo environment to verify the correct working before proceeding to the live environment. Follow the instructions given at https://developer.vivawallet.com/e-commerce-plugins/magento2.3/ to the letter.

**Comment by onnetgr** [comment]
Hello.
I have done this and the problem still exists

**Comment by VivaWalletSupport** [comment]
Please provide the following screenshots for your connection with the demo environment and we will look into the issue:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by onnetgr** [comment]
![2](https://user-images.githubusercontent.com/54945354/64408602-d4c39900-d08f-11e9-998a-9150533d084a.jpg)
![3](https://user-images.githubusercontent.com/54945354/64408603-d4c39900-d08f-11e9-8a79-897744bf0ac8.jpg)
![4](https://user-images.githubusercontent.com/54945354/64408606-d55c2f80-d08f-11e9-9de4-eda259c607d8.jpg)
![viva](https://user-images.githubusercontent.com/54945354/64408607-d55c2f80-d08f-11e9-847e-93e39acdde82.jpg)

**Comment by alexbk31** [comment]
try replacing demo. with www.
for gateway and transaction url
