### ISSUE TITLE
Viva Wallet Plugin set up issue with WooCommerce – when placing order "Wrong Merchant credentials or API unavailable"

### ISSUE THREAD

**Issue by Bauwer** [VivaPayments/API#1027]
Hello,

I have set up Viva Wallet with WooCommerce going through the steps I was given correctly, but when I place an order with Viva Wallet it is showing the following message "Wrong Merchant credentials or API unavailable"

Can anyone help me please?

Thank you,

Regards,
Alexander

**Comment by VivaWalletSupport** [comment]
Please use the plugin and the instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

In case the problem persists provide the following screenshots and we will look into the issue:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by Bauwer** [comment]
Could you please see the screenshots
![44](https://user-images.githubusercontent.com/38963838/64365690-96d16100-d00c-11e9-8f7b-ebc22b122ad4.jpg)
![Uploading 33.jpg…]()
![Uploading 22.jpg…]()
![Uploading 11.jpg…]()



 attached:

**Comment by Bauwer** [comment]
![33](https://user-images.githubusercontent.com/38963838/64371395-57a90d00-d018-11e9-8716-2544066b146f.jpg)

**Comment by Bauwer** [comment]
![22](https://user-images.githubusercontent.com/38963838/64371408-61cb0b80-d018-11e9-9279-ccc7bcda3124.jpg)

**Comment by Bauwer** [comment]
![11](https://user-images.githubusercontent.com/38963838/64371430-6f809100-d018-11e9-8a7a-e19f09bbc1eb.jpg)

**Comment by Bauwer** [comment]
> Please use the plugin and the instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
> 
> In case the problem persists provide the following screenshots and we will look into the issue:
> 
> Payment module settings (mask the API Key).
> Viva Wallet payment source settings (include the browser's URL in the screenshot).
> Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
> API Access page (mask API Key, include the browser's URL in the screenshot).

Thanks for your help, looking forward to your reply, thank you

**Comment by VivaWalletSupport** [comment]
The screenshot from the plugin settings indicate that a 3rd party plugin is used and not the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by Bauwer** [comment]
> The screenshot from the plugin settings indicate that a 3rd party plugin is used and not the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

Thanks Matthew, what could be a reason for using 3rd party plugin instead of supported plugin?

**Comment by Bauwer** [comment]
Thanks Matthew, our developer has found now the original plugin and it's working perfectly. The merchant id and the api is working fine.
But when it redirect to the next page it shows an error. Which is server error. I have attached the screenshot. 

Could you please help!

Thanks a lot

Best regards,
Alexander
![Screenshot_6](https://user-images.githubusercontent.com/38963838/64439357-afe81980-d0c1-11e9-99c7-f692771c73af.png)

**Comment by Bauwer** [comment]
![InkedScreenshot_5_LI](https://user-images.githubusercontent.com/38963838/64439395-c1c9bc80-d0c1-11e9-9319-83e29c4509d3.jpg)
