### ISSUE TITLE
Google autofill card details

### ISSUE THREAD

**Issue by CBDStar** [VivaPayments/API#1028]
Hi there, we are having an issue where customers are using tools like autofill card details into Viva Wallet and there is a problem where Viva Wallet wants short date ie MM/YY and Google fills MM/YYYY which is creating customer frustration as they think it is broken. If card details are entered manually it's not a problem but this is still unintuitive as customers do not expect to have to have their card on them to make a payment online. Is there a fix for this? I am using Viva Wallets simple checkout on Woocommerce. 

Thank you

**Comment by matthewrgourd** [comment]
We recommend using our official Viva Wallet plugin for WooCommerce. Instructions and a download link are given in our developer portal: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ Thanks!
