### ISSUE TITLE
Viva Wallet Plugin set up issue with WooCommerce - Server Error 404 File or directory not found

### ISSUE THREAD

**Issue by Bauwer** [VivaPayments/API#1029]
When we redirected to the next page it shows an error. Which is server error. I have attached the screenshot.

Could you please help!

Thanks a lot
![Screenshot_6](https://user-images.githubusercontent.com/38963838/64446237-34da2f80-d0d0-11e9-8161-5ef6a03ff6ab.png)

Best regards,
Alexander

**Comment by Bauwer** [comment]
![InkedScreenshot_5_LI](https://user-images.githubusercontent.com/38963838/64446256-415e8800-d0d0-11e9-8b75-993cf253dd11.jpg)

**Comment by Bauwer** [comment]
Thanks for your help

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following screenshots and we will look into the issue:

Payment plugin settings (mask only the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask only the API Key, include the browser's URL in the screenshot).

See for an example issue #1007

**Comment by Bauwer** [comment]
![33](https://user-images.githubusercontent.com/38963838/64472653-d2c60c80-d159-11e9-88af-e633e00576bc.jpg)
![44](https://user-images.githubusercontent.com/38963838/64472654-d2c60c80-d159-11e9-8a98-106dffa3383b.jpg)
![55](https://user-images.githubusercontent.com/38963838/64472656-d35ea300-d159-11e9-97ed-7094c1578ab8.jpg)
![66](https://user-images.githubusercontent.com/38963838/64472657-d35ea300-d159-11e9-8875-7cb444d4bed2.png)
![11](https://user-images.githubusercontent.com/38963838/64472658-d35ea300-d159-11e9-9e25-90f933dddc2b.jpg)
![22](https://user-images.githubusercontent.com/38963838/64472659-d35ea300-d159-11e9-8f9a-36ec3d1dedf5.jpg)

**Comment by Bauwer** [comment]
Thank you, what do you think is an issue?

**Comment by VivaWalletSupport** [comment]
Remove the papaki_vivapayments_gateway plugin completely, uncheck the Test mode in the Vivawallet plugin as you seem to use the credentials from your live account.

**Comment by Bauwer** [comment]
Done, but it is still the same problem?
![66](https://user-images.githubusercontent.com/38963838/64488329-843e6e00-d23e-11e9-9185-6e98c1c76856.jpg)

**Comment by Bauwer** [comment]
also were you can see "papaki_viva_gateway plugin"?

**Comment by VivaWalletSupport** [comment]
https://user-images.githubusercontent.com/38963838/64472658-d35ea300-d159-11e9-9e25-90f933dddc2b.jpg

**Comment by Bauwer** [comment]
it was already changed before, but it did not resolve the problem:
![66](https://user-images.githubusercontent.com/38963838/64529020-c977a400-d301-11e9-92a3-3177b542de74.jpg)

**Comment by VivaWalletSupport** [comment]
Please send admin login credentials + FTP credentials to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com to investigate the problem.

**Comment by Bauwer** [comment]
> Please send admin login credentials + FTP credentials to [vivawalletgithubsupport@hellasboost.gr](mailto:vivawalletgithubsupport@hellasboost.gr) with a cc to [ecommerce-support@vivawallet.com](mailto:ecommerce-support@vivawallet.com) to investigate the problem.

I just sent the email, thanks for your support

**Comment by VivaWalletSupport** [comment]
The issue was that you made a mistake with the API Key, you specified as first character a capital I (India) while it should be a lowercase l (Lima).
