### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by webace-studio** [VivaPayments/API#103]
Καλημέρα.
Εχω ένα eshop σε wordpress(woocommerce),και σαν επιλογή πληρωμής χρησιμοποιώ το viva (Integration method: Redirection).Οταν κάποιος κανει την πληρωμή πηγαίνει κανονικα στο περιβάλλον της VIVA,βάζει τα στοιχεία, και όταν πατάει την πληρωμή τον βγάζει σε σελίδα SERVER ERROR 403 Forbidden.(Δείτε εικόνα)
Η πληρωμή γίνετε όμως κανονικά.Αποστέλετε email στον πελάτη απο τη VIVA,όχι όμως και απο το woocommerce στον ιδιοκτήτη του eshop,;ότι έχει νέα παραγγελία.
Ενώ έχει γίνει η πληρωμή και έχουν περάσει τα χρήματα κανονικά στον λογαριασμό,η πληρωμή στο woocommerce φαινετε σε εκρεμότητα .
![error](https://cloud.githubusercontent.com/assets/19302933/15176023/db7baf10-1771-11e6-9c7e-2aad87e3f7b2.png)

Απο την άλλη σε test mode της viva,όλα λειτουργούν κανονικά.
ΥΓ
Tα urls της επιτυχημένης και αποτυχημένης συναλλαγής είναι σωστά
Ευχαριστώ προκαταβολικά
Γιάννης

**Comment by dmihos** [comment]
Καλησπέρα σας
Στο account σας έχουν καταχωρηθεί 2 επιπλέον πηγές, ωστόσο στη συγκεκριμένη πληρωμή δεν κάνατε χρήση αυτών, αλλά χρησιμοποιήσατε την Default (η οποία επιπροσθέτως πρέπει να διορθωθεί σε http**s**, είναι ο λόγος του παραπάνω σφάλματος).
Κατά το CreateOrder, λοιπόν, θα πρέπει να περνάτε το σχετικό SourceCode που αφορά στην πηγή που θέλετε να χρησιμοποιήσετε.
