### ISSUE TITLE
declined payments

### ISSUE THREAD

**Issue by zionchakraborty** [VivaPayments/API#1031]
all cards are being declined by viva why is this?

**Comment by matthewrgourd** [comment]
Are you attempting to use our Shopify plugin? Please provide more details of your Viva Wallet setup so we can help further.

**Comment by zionchakraborty** [comment]
yes with shopify

**Comment by zionchakraborty** [comment]
I have had all my customers cards declined. I have been onto shopify already and they have done test payments already and they said there end is fine. I have even got to the last page on viva wallet, where they contact my bank, the bank texts me a code for 3d secure. i pass, it says ok. then viva says decline so im 100% sure the error is on viva wallet side

**Comment by zionchakraborty** [comment]
![Screenshot 2019-09-09 09 40 44](https://user-images.githubusercontent.com/55083923/64713304-8ad61b00-d4b4-11e9-80ac-07859196558a.png)
this first screenshot shows the error in viva test mode


![Screenshot 2019-09-09 10 09 50](https://user-images.githubusercontent.com/55083923/64713319-90336580-d4b4-11e9-89fc-caf98f9f5153.png)
this second is the decline when it goes back to shopify from viva

**Comment by matthewrgourd** [comment]
Hi @zionchakraborty please send your Merchant ID to myself at mgourd@vivawallet referencing this GitHub issue and I'll check your account.

**Comment by matthewrgourd** [comment]
No reply since September so I'm closing this issue. Please reopen if it's still a problem.
