### ISSUE TITLE
Credentials request for Native Checkout v2.0

### ISSUE THREAD

**Issue by Sotiris-k** [VivaPayments/API#1032]
API Access: **Native Checkout v2.0**
Environment: **Demo and Production.**
Business Name: **KOS4ALL TOURS TRAVEL SERVICES PC**
Merchant ID for Demo: **62c15cdd-bb78-4d50-a472-666a544f8ab6**
Merchant ID for Production: **5e158994-817c-4fd5-97f1-5aca41a16b98**

**Comment by matthewrgourd** [comment]
Hi @Sotiris-k , thanks for this! Can you also please send me the same info. by email? Email address is mgourd@vivawallet.com

**Comment by Sotiris-k** [comment]
Done
