### ISSUE TITLE
OAuth2 Credentials Request

### ISSUE THREAD

**Issue by ncarchia** [VivaPayments/API#1033]
API Access: Native Checkout v2.0
Environment: Demo
Business Name: Codat
Merchant ID: f595019e-0211-4f1c-8fe7-900e5299d2ed

**Comment by matthewrgourd** [comment]
Hi @ncarchia, thanks for this! Please can you send me the same info. by email also? Email address is mgourd@vivawallet.com

**Comment by drakakisgeo** [comment]
Hey @matthewrgourd 

API Access: Native Checkout v2.0
Environment: Demo
Business Name: Billit.io
Merchant ID: 6a64a6db-fb03-4ea7-9201-ef0427db16d5

I'll send them by email as well.
