### ISSUE TITLE
VIVAWALLET  PLUG IN   & VIRTUEMART 3

### ISSUE THREAD

**Issue by twistedpig** [VivaPayments/API#1034]
Seems to be a problem with the Viva Wallet plugin   for virtuemart  I have recently ujpdated my  virtuemart store to latest joomla and virtuemart fiels -  and I get an error 1504   after the custmer has paid the final page reverts to 1504
  seems to be issue  //     Unknown column "type" in "where clause "   

Please advise  - this plug now seems to be NOT compatable with latest Virtuemart3.6.0 .10113   & Joomla 3.9.11  php 7.2.22

**Comment by VivaWalletSupport** [comment]
Thank you for your patience, just tested on a fresh installation using the VirtueMart3.6.0_Joomla_3.9.11-Stable-Full_Package.zip package. Transaction passes without any error and I am not able to replicate the reported database (1504) problem. I would suggest to debug your setup or use a fresh installation.

**Comment by matthewrgourd** [comment]
Hi @twistedpig if you're still experiencing issues, please try our updated plugin here: 
[vm3_plugin_vivawallet.zip](https://github.com/VivaPayments/API/files/3641753/vm3_plugin_vivawallet.zip)

**Comment by twistedpig** [comment]
Hi is there any special Plug in for WIX WEB SITES ?

**Comment by twistedpig** [comment]
HI I am stil having issues with teh error
ERROR 1054 (42S22): Unknown column '' in 'where clause'
this comes after the user pays. ??
