### ISSUE TITLE
Native Checkout v2.0 3DS

### ISSUE THREAD

**Issue by Aviatoryona** [VivaPayments/API#1035]
I am kindly requesting a working PHP demo of checkout  using Native v2.0 3DS, have tried following the documentation but nothing is working. Thank you

**Comment by matthewrgourd** [comment]
Hi @Aviatoryona, here you go!
```
<?php

$authurl =  'https://demo-accounts.vivapayments.com/connect/token'; 
$client_id = '9dd8b7b2-f65d-4eff-b715-6dee12eaf4ac.apps.vivapayments.com';
$client_secret = '9dd8b7b2-f65d-4eff-b715-6dee12eaf4ac';
$postdata = [
    "grant_type"=>"client_credentials"
];		

$curl = curl_init($authurl);
curl_setopt($curl, CURLOPT_USERPWD, $client_id . ":" . $client_secret); 
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, $postdata);
$jsonResponse = curl_exec($curl);
if(curl_errno($curl)){
    throw new Exception(curl_error($curl));
}

$response = json_decode($jsonResponse, true);
$access_token = $response['access_token'];
$access_token_type = $response['token_type'];

echo $access_token_type . ' : ' . $access_token;die("eeee");

?>
```

**Comment by Aviatoryona** [comment]
Hi @matthewrgourd , Thank you for posting your code and helping me solve my problem. Let me check, i will get back to you if i run into problems.
 
Collaborator
matthewrgourd

**Comment by Aviatoryona** [comment]
Hello, how do I get client id and secret since what I have from my sandbox
account is merchant id Apikey and public key.

Thanks in advance.

**Comment by matthewrgourd** [comment]
Hi @Aviatoryona please email mgourd@vivawallet.com stating your merchant ID and we will send the credentials to you. If you also need credentials for the test environment, send us your demo merchant ID as well.
