### ISSUE TITLE
Request credentials for Native Checkout 2.0

### ISSUE THREAD

**Issue by sebdesign** [VivaPayments/API#1036]
API access required: **Native Checkout v2.0**
Environment: **demo**
Business name: **Σεμπαστιάν Νικολάου**
Merchant ID: **0998e4de-3574-451b-9521-8e4f2a06c39d**

I've sent an email to mgourd@vivawallet.com as well.

Thanks!

**Comment by matthewrgourd** [comment]
Sent through by email
