### ISSUE TITLE
OAuth2 Credentials Request for Native Checkout 2.0

### ISSUE THREAD

**Issue by ggamvetas87** [VivaPayments/API#1037]
API Access: Native Checkout v2.0
Environment: Demo
Business Name: Ioannis Gamvetas
Merchant ID: 7a908687-15c8-4767-8613-d467cc49a307

I've also sent an email to mgourd@vivawallet.com.

Thank you in advance.

**Comment by matthewrgourd** [comment]
Sent through by email.

**Comment by ggamvetas87** [comment]
Thank you again!
