### ISSUE TITLE
Payments timing out on WooCommerce Purchases

### ISSUE THREAD

**Issue by CBDOILLAB** [VivaPayments/API#1038]
Hi,

Around half our customers orders face a timing out issue of around 12 hours then the order cancels. This has been persistent for on our account forever. Please find attached a screen shot of our WooCommerce orders. As you can see roughly half cancel. I can't show the names publicly for data protection. 

I have been told to included the following screenshots:

- Plugin settings (mask the API Key). -- I do not have a option on the plugin for settings/docs etc. Maybe this could be part of the issue?
- Viva Wallet payment source settings (include the browsers URL in the screenshot). -- Not sure how to get please advise. 
- Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.  -- Not sure how to get please advise. 
- API Access page (mask API Key, include the browsers URL in the screenshot). -- Not sure how to get please advise. 

Please advice what you need next to investigate the issue. 

Each order fills in their full name, full address, email, phone number so it is unlikely all of these backed out the order. On one of the order notes it shows the order cancelled due to time limit reached - See attached. 
![Details of a Time Limit Reached Order](https://user-images.githubusercontent.com/52702083/64647210-81937280-d410-11e9-8c0b-047658c74345.PNG)
![Plugin Settings - No option to click settings](https://user-images.githubusercontent.com/52702083/64647211-81937280-d410-11e9-99ad-cb296537175f.PNG)
![WooCommerce Orders Page](https://user-images.githubusercontent.com/52702083/64647212-822c0900-d410-11e9-9078-21c06deb83b9.PNG)

Regards

Jordan Cowsill

**Comment by VivaWalletSupport** [comment]
Hello, are there any success transactions for these timed out orders?

**Comment by CBDOILLAB** [comment]
Hi Tom,

No the successful sales did not time out. I emailed a time out customer lastnight to ask them to confirm, please see attached screenshot.

Is there anything you would like me to ask him IE card used or any other details which may assist you?

[image1.png]


Jordan Cowsill

Sent from my iPhone

On 11 Sep 2019, at 04:18, Tom van der Veer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, are there any success transactions for these timed out orders?

**Comment by VivaWalletSupport** [comment]
In case you want to post an image, do it at github, do not attached it to an email as it will not show. As the answer was not 100% understood, please confirm that the transaction of this specific customer was executed correctly in Viva or if no transaction was registered.

**Comment by CBDOILLAB** [comment]
No this customer had the timing out issue.

I emailed the client to check if he backed out the order but as suspected he said his payment timed out and order was cancelled.

The picture was just a screen shot of his email so no need to upload.

Regards Jordan.

Sent from my iPhone

On 11 Sep 2019, at 14:34, Tom van der Veer <notifications@github.com<mailto:notifications@github.com>> wrote:


In case you want to post an image, do it at github, do not attached it to an email as it will not show. As the answer was not 100% understood, please confirm that the transaction of this specific customer was executed correctly in Viva or if no transaction was registered.

**Comment by VivaWalletSupport** [comment]
The payment timeout in the plugin is set to 300 seconds (5 minutes), that in most cases is more then enought to complete the transaction. You can adjust this value by editing the wc-vivawallet.php file that is located in the plugin folder, change PaymentTimeOut=300 to the desired amount of seconds.

**Comment by CBDOILLAB** [comment]
Hi,

Thanks for finding the issue.

I’m not very IT literate. Please can you provide some instructions on how to get into the Viva Plugin.

As per my original upload on Viva wallet the plugin doesn’t have a setting link, it only shows a deactivate link.

Regards

Jordan Cowsill

Sent from my iPhone

On 12 Sep 2019, at 04:16, Tom van der Veer <notifications@github.com<mailto:notifications@github.com>> wrote:


The payment timeout in the plugin is set to 300 seconds (5 minutes), that in most cases is more then enought to complete the transaction. You can adjust this value by editing the wc-vivawallet.php file that is located in the plugin folder, change PaymentTimeOut=300 to the desired amount of seconds.

**Comment by CBDOILLAB** [comment]
Hi Tom,

Surly if 5 minutes is usually enough then the time out issue is due to a deeper problem.

It must be running past 5 mins for a reason.... I don't know maybe connection issues etc? Please can you have a further look into this as it is still happening and cost me a £65 sale the other day (attached).

Also, where can I find the file wp-content\plugins\vivawallet-for-woocommerce\wc-vivawallet.php.


Regards,
Jordan

Jordan Cowsill
Director

Email: hello@cbdoillab.co.uk

 [1518543506527_Webp.net-resizeimage]

This email is sent for and on behalf cbdoillab.co.uk.

CONFIDENTIALITY
This email is intended only for the use of the addressee named above and may be confidential or legally privileged. If you are not the addressee you must not read it and must not use any information contained in nor copy it nor inform any person other than CBD Oil Lab or the addressee of its existence or contents. If you have received this email in error please delete it and notify our IT Department on hello@cbdoillab.co.uk

For more information visit www.cbdoillab.co.uk



________________________________

**Comment by VivaWalletSupport** [comment]
Hello, the wp-content is a WordPress directory located on your server.
