### ISSUE TITLE
Viva Payment Problem

### ISSUE THREAD

**Issue by ckarikas** [VivaPayments/API#104]
Καλησπέρα σας,

Έχω ένα θέμα με το invoice που πρέπει να αποστέλλετε από τη Viva μόλις ολοκληρωθεί η παραγγελία. Ενώ ο χρήστης μπαίνει κανονικά, κάνει την αγορά, μεταφέρετε στον ιστότοπο της Viva για να πληρώσει και αφού πληρώσει ανακατευθύνεται στη σελίδα που έχω ορίσει χωρίς κανένα πρόβλημα. Μέσα στο WordPress η καταγραφή της παραγγελίας γίνεται κανονικά, αλλά δε λαμβάνω email για την ολοκλήρωση της παραγγελίας, ούτε εγώ, ούτε ο πελάτης. Επίσης μέσα στο back end της viva δε φαίνεται να έχει γίνει το transaction.

Για πιο λόγο μπορεί να γίνεται αυτό; και τι μπορώ να κάνω για να το λύσω;

Να σας αναφέρω πως το transaction έγινε με ένα ποσό της τάξεως των 0.50€. Μήπως το ποσό αυτό είναι αρκετά μικρό; Υπάρχει κάποιο όριο;

ΥΓ: Όλα τα παραπάνω λειτουργούν άψογα στο demo site της Viva.

Ευχαριστώ εκ των προτέρων!

**Comment by dmihos** [comment]
Καλημέρα ckarikas

Καταρχήν, το πρόβλημα που βλέπω, στην υλοποίησή σας, είναι ότι δεν αντιλαμβάνεστε την επιτυχή ή όχι εκτέλεση μιας συναλλαγής. 
Απ'ότι καταλαβαίνω, πιθανά έχετε ορίσει ίδια urls για success/failure και δεν κάνετε κάποια κλήση στο API για επιβεβαίωση της συναλλαγής.

Οι λόγοι απόρριψης ποικίλουν, θα χρειαστεί διερεύνηση.
Αν πρόκειται για demo περιβάλλον, δώστε μας εδώ το OrderCode.
Αν όχι, θα πρέπει να στείλετε σχετικά στοιχεία στο merchants@vivawallet.com
