### ISSUE TITLE
Mixed Content Error at demo.vivapayments.com

### ISSUE THREAD

**Issue by ggamvetas87** [VivaPayments/API#1040]
Hello, 

I have installed WooCommerce Vivawallet Gateway plugin at a test wordpress site, and while I am trying to complete a transaction, via redirect, using the the test data (credit card: 4111111111111111 and CVV: 111), I get the following error:

`Mixed Content: The page at 'https://demo.vivapayments.com/web/newtransaction.aspx?Ref=8132048874272608' was loaded over HTTPS, but requested an insecure form action 'http://demo.vivapayments.com/web/checkout/threedsecurevalidation'. This request has been blocked; the content must be served over HTTPS.`

![mixed_content](https://user-images.githubusercontent.com/40852174/64679189-dfad6d80-d483-11e9-8c04-88815a5a58e5.png)

Please find below the gateway info for my demo account:

- MerchantID: **7a908687-15c8-4767-8613-d467cc49a307**

Is it possible that a setting is misconfigured?

P.S: My website http://wptimber.warriorpanda.com/ does not have an SSL certificate installed.

Thank you in advance.

**Comment by matthewrgourd** [comment]
Hi @ggamvetas87 it sounds like you inadvertently may still have the unofficial plugin selected. Can you try to completely remove this so you're only left with ours?

**Comment by matthewrgourd** [comment]
@ggamvetas87 @ngoun looks like this could be part of a wider issue, I'm raising with our senior developer. Apologies for any inconvenience, we'll get this looked at as soon as possible.

**Comment by matthewrgourd** [comment]
Hi @ggamvetas87 @ngoun, we think the issue may be due to some of our code samples being out of date and still using including http. I will adjust these as soon as possible but in the meantime if you could replace any instances of *http*://demo.vivapayments.com with **https**://demo.vivapayments.com ? Thank you!

**Comment by matthewrgourd** [comment]
Hi @ggamvetas87 in the example that you gave, I believe *http*://demo.vivapayments.com/web/checkout/threedsecurevalidation needs to be replaced with **http**://demo.vivapayments.com/web/checkout/threedsecurevalidation in the code
