### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 

### ISSUE THREAD

**Issue by ChrisLennonLondon** [VivaPayments/API#1041]
Hi there,

I have an issue with vivawallet. Have followed the online setup. The plugin was downloaded via their own support portal and I configured the api settings as per instructions. I have no webhooks as these are optional

When I click subscribe now to (launch the viva wallet interface) I get SyntaxError: Unexpected token < in JSON at position 

The website I am using is cbdspringwater.co.uk

I can provide login details if required as long as the thread is private

Many thanks

Chris Lennon

**Comment by ChrisLennonLondon** [comment]
Hi Matthew, just to update you, Im getting the same issue. I tried with Internet explorer and the error shows SyntaxError: Invalid character

**Comment by VivaWalletSupport** [comment]
Hello, are you using WooCommerce Subscriptions?

**Comment by ChrisLennonLondon** [comment]
Hi Tom

Yes I am using woocommerce subscriptions

**Comment by VivaWalletSupport** [comment]
Thank you, at the moment the payment plugin does not support subscriptions.

**Comment by ChrisLennonLondon** [comment]
Thanks Tom. Is there a rough time line or roadmap to support this?

**Comment by VivaWalletSupport** [comment]
Not for the moment.

**Comment by ChrisLennonLondon** [comment]
Ok thanks for help all
