### ISSUE TITLE
Πρόβλημε με redirect Integration

### ISSUE THREAD

**Issue by AresC** [VivaPayments/API#105]
Καλησπέρα σας, έχουμε ένα account στην viva και έχουμε χρησιμοποιήσει το default κομμάτι κώδικα που έχετε στο github για την δημιουργία παραγγελίας.

Ενώ με τα default στοιχεία σύνδεσης δουλεύει κανονικά, όταν αλλάζει το κλειδί, το id ο κωδικός της πηγής, δε μπορεί γίνει σωστά η κλήση και το σφάλμα που παίρνουμε είναι το "API Call failed! The error was: NULL "

το url που καλούμε είναι το  $request =  'https://www.vivapayments.com/api/orders';	// production environment URL
και ο κωδικός πηγής: 8010

Υπάρχει κάτι που πρέπει να γίνει παραπάνω πέρα από το default script?

Να επαναλάβω ότι στο demo παίζει κανονικά, τα μόνα που αλλάζουν είναι:
$request
$MerchantId
$APIKey
$Source

**Comment by AresC** [comment]
Έχουμε κάποια ενημέρωση? Χρειάζεστε κάποιο παραπάνω στοιχείο από εμάς?

**Comment by dmihos** [comment]
Καλημέρα AresC
Στείλτε, αν θέλετε, στο merchants@vivawallet.com, τα στοιχεία του εμπορικού σας προφίλ, για διερεύνηση. Μην ξεχάσετε να αναφέρετε το παρόν issue για reference.

**Comment by AresC** [comment]
Καλησπέρα σας και πάλι, 
η καρτέλα που διατηρούμε είναι στο όνομα
ΔΗΜΗΤΡΙΑΝΑ ΟΕ 
Ε ΦΙΩΤΟΔΗΜΗΤΡΑΚΗΣ ΚΑΙ ΣΙΑ ΟΕ 
με κωδικό πηγής 8010

Στο http://isologis.gr/test.php

έχει στηθεί το default php script - create order
με αλλαγμένα τα στοιχεία του ΑΡΙ.

Το σφάλμα όπως μπορείτε να δείτε στο παραπάνω url είναι το 
"API Call failed! The error was:"
 Σε ένα demo account η σύνδεση δουλεύει κανονικά. 

Επικοινωνήσαμε με το merchants και μας ζήτησαν να ξαναεπικοινωνήσουμε με σας.

Μπορούμε να δούμε το παραπάνω πρόβλημα?

**Comment by dmihos** [comment]
Δε βλέπουμε κάποιο πρόβλημα στο λογαριασμό σας.
Ποιο είναι το ακριβές url το οποίο χρησιμοποιείτε για τη δημιουργία Order στο παραγωγικό περιβάλλον;

**Comment by AresC** [comment]
![isologis](https://cloud.githubusercontent.com/assets/6428882/15323179/0f824002-1c41-11e6-9366-d87c829c5c86.PNG)

**Comment by dmihos** [comment]
Αυτό που ρωτάω είναι, πιο είναι το ακριβές url που χρησιμοποιείτε στο php αρχείο για τη δημιουργία του Order.
Έχετε αλλάξει το http://demo.vivapayments.com/api/orders σε https://www.vivapayments.com/api/orders;

**Comment by AresC** [comment]
Αυτό είναι το url που χρησιμοποιούμε:
$request =  'https://www.vivapayments.com/api/orders';

**Comment by dmihos** [comment]
Τότε πιθανά το πρόβλημα οφείλεται στην έκδοση OpenSSL του server σας. Περισσότερες πληροφορίες αναφέρονται εδώ
https://support.vivawallet.com/hc/en-us/community/posts/200568401-Site-not-responding-when-called-from-PHP-code

**Comment by AresC** [comment]
Αυτό είναι το πρόβλημα. Ευχαριστώ πολύ.
