### ISSUE TITLE
Demo Enviroment Redirect checkout 3D Secure

### ISSUE THREAD

**Issue by ngoun** [VivaPayments/API#1056]
On Demo environment redirect checkout using 4111 1111 1111 1111  Card Pops up 3D Secure and cannot proceed 
Example
https://demo.vivapayments.com/web/checkout?ref=8601582655172600&lang=el-GR

**Comment by matthewrgourd** [comment]
Hi @ngoun many thanks for this, I've raised with our dev team and will get back to you with an update shortly.

**Comment by stevestavropoulos** [comment]
When the 3DS modal is shown, there is a form inside, with action="http://demo.vivapayments.com/web/checkout/threedsecurevalidation", which is never submitted and produces the following error in the console:

Mixed Content: The page at 'https://demo.vivapayments.com/web/checkout?ref=<myrefcode>' was loaded over HTTPS, but requested an insecure form action 'http://demo.vivapayments.com/web/checkout/threedsecurevalidation'. This request has been blocked; the content must be served over HTTPS.

The obvious solution seems to be a change of the action protocol from http to https.

As it is, demo environment is unusable, as no payment can be completed.

**Comment by matthewrgourd** [comment]
Hi @ngoun @stevestavropoulos one of our developers has responded to a number of queries in one post. Please see https://github.com/VivaPayments/API/issues/1073#issuecomment-532243393 . Hope this clarifies things!

**Comment by stevestavropoulos** [comment]
@matthewrgourd the issue you reference is for the Native Checkout method and is not applicable here. There seems to be no solution or workaround for completing a payment in the demo environment with redirect checkout.

Issue should be opened again.

**Comment by matthewrgourd** [comment]
@stevestavropoulos Ok, looks like there could be a problem here, I'm raising with our senior developer.

**Comment by matthewrgourd** [comment]
Hi @stevestavropoulos, we think the issue may be due to some of our code samples being out of date and still using including http. I will adjust these as soon as possible but in the meantime if you could replace any instances of http://demo.vivapayments.com with https://demo.vivapayments.com ? Thank you!

**Comment by stevestavropoulos** [comment]
@matthewrgourd We use the https version and that's how the "mixed content" error occurs. Plain http wouldn't have any such problems.

As I understand it, there are at least two issues here which prevent a successful payment from being made in the demo environment:

1) In demo's payment interface, when 3DS auth tries to start, it fails as it tries to submit a form to a plain http url. This should change to https and we (the outside developers) don't have any kind of access there.

2) Even if the form url is changed to https, payment will still fail, as 3ds auth will not be able to succeed with any test card! You need a 3DS emulator, or a way to disable 3ds in the demo altogether.

Please reopen the issue.

**Comment by matthewrgourd** [comment]
Hi @stevestavropoulos  in the example that you gave, I believe *http*://demo.vivapayments.com/web/checkout/threedsecurevalidation needs to be replaced with **http**://demo.vivapayments.com/web/checkout/threedsecurevalidation in the code

**Comment by stevestavropoulos** [comment]
Sorry @matthewrgourd, but this dialog doesn't seem to work, so I will have to stop responding. Please fix it as soon as you can.

**Comment by xiaoyao929** [comment]
I have the same problem with Redirect Checkout

**Comment by devnullsolutions** [comment]
The problem may be reproduced in [JSBin example](https://jsbin.com/figaxul/edit?html,output) (link provided in docs).

Step 1. Open JSBin example
Step 2. Click "Pay" button
Step 3. Open "Pay with card" block
Step 4. Paste `4111111111111111` into card number field
Step 5. Paste `01/22` into expiration date field
Step 6. Paste `111` into CVV field
Step 7. Paste `Jon` into First name field
Step 8. Paste `Snow` into Last name field
Step 9. Paste `some@email.com` into email field`
Step 10. Click "Pay €10.00" button
Step 11. 3DS emulator will be visible for a second and then will be hidden (because of http blocked on https website). Safari will also ask confirmation of sending data to unsecure form.

**Comment by Talagozis** [comment]
The same problem here too, the Redirect procedure does not work on demo. Any other way to test it except going on Live ?

**Comment by matthewrgourd** [comment]
Hi all, our development team has come back with this response:

> We've finished the implementation for the fix and expect it to reach demo environment within the next week. Thank you for your patience

**Comment by dpnevmatikos** [comment]
Hello everyone,
Issue with mixed content is fixed. Can you please try again ?
Apologies for any inconvenience caused.

**Comment by devnullsolutions** [comment]
I'm always getting "This order has been cancelled. Payment order has been canceled by the merchant" message right after I click "Charge €100.00". No 3d secure check. You can try it here https://demo.vivapayments.com/web/checkout?ref=5312807187873711.

API response for order with code `5312807187873711`:
```js
{
  OrderCode: 5312807187873711,
  SourceCode: '9989',
  Tags: [ 'test' ],
  TipAmount: 0,
  RequestLang: 'en-GB',
  MerchantTrns: 'ORDER',
  CustomerTrns: 'Payment',
  MaxInstallments: 0,
  RequestAmount: 100,
  ExpirationDate: null,
  StateId: 0
}
```
StateId is `0` that means `pending`.

**Comment by ngoun** [comment]
@devnullsolutions  I think that this message is shown when multiple attempts have been made for that order code. Do the developers confirm this behaviour?

I think the initial Issue is now fixed.. @matthewrgourd @dpnevmatikos 
If not any more requests can now be closed?

**Comment by dpnevmatikos** [comment]
Hello everyone, 
As of yesterday we've released a dummy 3DSecure window which behaves exactly like those found into production environment, yet allows you to decide the cardholder's authentication outcome :) 

We hope that you'll find it useful and more helpful when integrating with our payments platform.
Make sure that you let us know if you encounter any issues!

**Comment by EuroStreet** [comment]
So, are the codes updated now?, Do we need to install again the plugin or what's the solution on this?, Thank you. @matthewrgourd

**Comment by HumayunE** [comment]
Hi @dpnevmatikos I tried it yesterday but it does not redirect back to website and shows message:
"This card does not support electronic transactions. In order to complete this payment please use a different card, or add funds to your Viva Wallet."

I updated it yesterday on #1135 .

> Hi @matthewrgourd I have just tried it and it seems the old problem of redirecting is back.
> Now it is not redirecting back to the website again.
> 
> See screenshots:
> ![Screenshot 2019-11-08 at 7 19 01 PM](https://user-images.githubusercontent.com/10536341/68483184-e4f91f80-025c-11ea-94c7-1f4723a9d4b4.png)
> 
> ![Screenshot 2019-11-08 at 7 19 16 PM](https://user-images.githubusercontent.com/10536341/68483203-ecb8c400-025c-11ea-83d3-abeb1627cc29.png)
> 
> After clicking on confirm payment it shows the old message again..
> ![Screenshot 2019-11-08 at 7 13 33 PM](https://user-images.githubusercontent.com/10536341/68483215-f0e4e180-025c-11ea-9699-9033c56367af.png)
