### ISSUE TITLE
Διαγραφή κουμπιού πληρωμών

### ISSUE THREAD

**Issue by AthensPride** [VivaPayments/API#106]
Γεια σας, 

Προσπαθώ να διαγράψω ένα κουμπί πληρωμών αλλά δεν είναι δυνατή η διαγραφή του. 
Πρέπει οπωσδήποτε να γίνει σήμερα καθώς ο αριθμός των διαθέσιμων εισιτηρίων που θα πωλούνταν μέσω του συγκεκριμένου κουμπιού έχει καλυφθεί. 

Σας ευχαριστώ πολύ.

**Comment by dmihos** [comment]
Καλησπέρα σας
Δυστυχώς δεν υπάρχει αυτή η δυνατότητα. 
Ωστόσο, μπορείτε απλά να αφαιρέσετε το κουμπί από τη σελίδα σας, ώστε να μην μπορεί κάποιος να το χρησιμοποιήσει για πληρωμή.

**Comment by AthensPride** [comment]
Τότε γιατί υπάρχει σαν επιλογή η διαγραφή του κουμπιού?

**Comment by dmihos** [comment]
Σωστή ερώτηση, δεν το διευκρίνησα προηγουμένως.
Η διαγραφή λειτουργεί εφόσον δεν έχουν γίνει συναλλαγές με το συγκεκριμένο κουμπί. Χρησιμεύει για τις περιπτώσεις που έγινε κάποια λάθος εισαγωγή κατά τη δημιουργία κλπ.
Πιθανά να προστεθεί "Απενεργοποίηση" στο μέλλον, αλλά προς το παρόν κάτι τέτοιο δεν είναι διαθέσιμο.
