### ISSUE TITLE
OAuth 2 Client Credentials Application

### ISSUE THREAD

**Issue by quoMC** [VivaPayments/API#1060]
API Access: Native Checkout v2.0
Environment: Demo + Production

**Comment by matthewrgourd** [comment]
Hi @quoMC , sorry for the delay getting back to you. Our Dev Team has just informed me that a new feature for generating your own demo credentials is now available at the following location:

https://demo.vivapayments.com/selfcare/en/security/apiaccess 

Please check in the 'Native Checkout v2 Credentials’ section. Any queries, please let me know. I will be updating the documentation around this next week. Your production credentials request is still in progress. Thanks!
