### ISSUE TITLE
OAUTH Credentials

### ISSUE THREAD

**Issue by odysseas12** [VivaPayments/API#1062]
API access required (Native Checkout v2)
    Environment demo
    Business name: ODYSSEAS ODYSSEOS 
    Merchant ID* ee8c7898-639b-4319-a6a9-6880add32ecd

Hi Matt,
I also need a dozen production credentials for clients.
Should I open a request for each one here and then send an email for each one to mgourd@vivawallet.com ?

Thanks

**Comment by matthewrgourd** [comment]
Hi there, sorry, I only just saw this. Please send through multiple requests in an Excel spreadsheet or similar to mgourd@vivawallet.com. Thanks!

**Comment by odysseas12** [comment]
Thank Matt will do.
