### ISSUE TITLE
Native checkout OAuth2 client credentials

### ISSUE THREAD

**Issue by abaoubas** [VivaPayments/API#1065]
API access required: Native Checkout v2
Environment: production
Business name: Αλέξανδρος Πιπέρογλου & ΣΙΑ ΟΕ | IroKids.gr
Merchant ID: XXXXXXXXXXXXXXXXXXXXX

API access required: Native Checkout v2
Environment: demo
Business name: Θανάσης Αγγελογεώργος ( a demo account)
Merchant ID: XXXXXXXXXXXXXXXXXXXXX

**Comment by matthewrgourd** [comment]
Hi there, please send through to mgourd@vivawallet.com along with the full merchant IDs. Thanks!

**Comment by abaoubas** [comment]
Hi Matthew, I sent you the details via email. Thanks!
