### ISSUE TITLE
Unable to do VivaPayments.cards.requestToken

### ISSUE THREAD

**Issue by beisnikosspi** [VivaPayments/API#1067]
Hi there, it seems that there something wrong with this link:

In the demo environment, when I'm trying to do:

`VivaPayments.cards.requestToken({
                amount: 3600
            }).done((response) => {
                alert(response.chargeToken);
            });`

after a while I get a 401 response from: 

`https://api.vivapayments.com/nativecheckout/v2/chargetokens`

Even though it's not written in the documentation I've tried switching from `https://www.vivapayments.com/web/checkout/v2/js` to `https://demo.vivapayments.com/web/checkout/v2/js`, however I get the same error.

In postman I've tried replicating this call but using this url: `https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens` and it worked fine.

Can you please correct the documentation as long the js here? `https://demo.vivapayments.com/web/checkout/v2/js`

Thanks.

**Comment by matthewrgourd** [comment]
Hi there, @beisnikosspi I've sent this by email but thought it might be worth sharing here as well for others to be able to see. This is a reply back from one of our developers:

> There are 2 different urls that we're talking about: 
> The url that contains the JS file which implements the Native Checkout v2 functionality, and can be found here
> DEMO: https://demo.vivapayments.com/web/checkout/v2/js
> PRODUCTION: https://www.vivapayments.com/web/checkout/v2/js
> 
> The endpoint which must be set as a base url on Native's initialization when one needs to use the demo env only and is https://demo-api.vivapayments.com/
> ​
> the second url is actually the API url that Native checkout uses behind the scenes
