### ISSUE TITLE
Exchanging cardtokens for chargetokens not working

### ISSUE THREAD

**Issue by EleniDnD** [VivaPayments/API#1068]
This url https://www.vivapayments.com/acquiring/v1/cards/chargetokens?token=XXXXXXXXX is not working. I keep getting an error with StatusCode "NotAcceptable".

We are implementing card tokenization using 3DS (v2)

Please advise

**Comment by matthewrgourd** [comment]
Do you have access credentials? You need to request these via myself at mgourd@vivawallet.com before you can be authenticated.

**Comment by djsolid** [comment]
Hi, yes client credentials have been requested and obtained. We don't get NotAuthorized but NotAcceptable

**Comment by matthewrgourd** [comment]
Hi @jkatsiotis I believe the correct base URL for production is https://api.vivapayments.com so you should replace with https://api.vivapayments.com/acquiring/v1/cards/chargetokens?token=XXXXXXXXX

**Comment by jkatsiotis** [comment]
That is correct. For future reference this API needs AuthToken to work (type of Authorization: Bearer). 

Feel free to close this issue
