### ISSUE TITLE
Unable to create order using API with production api details .

### ISSUE THREAD

**Issue by digu087** [VivaPayments/API#1069]
Hello @matthewrgourd 
I have successfully tested the Viva Checkout v2 3ds . When I moved to production details order API is giving 404 error . 
I have tried both the urls 
https://api.vivapayments.com and https://vivapayments.com but it just returns the error 
Client error: `POST https://vivapayments.com/api/orders` resulted in a `404 Not Found` response:
Or Client error: `POST https://api.vivapayments.com/api/orders` resulted in a `404 Not Found` response:
Please help asap .
Thanks

**Comment by matthewrgourd** [comment]
Hi there, the correct base URL for production is https://www.vivapayments.com. I've checked and I think there's a misprint in the documentation. We will rectify this as soon as possible. Apologies for any inconvenience caused.
