### ISSUE TITLE
Συνδεση για δωρεές

### ISSUE THREAD

**Issue by plegma2014** [VivaPayments/API#107]
Καλησπέρα

Χρειαζόμαστε αυτά τα στοιχεία για να συνδέσουμε το λογαριασμό μας με μια πλατφόρμα  - σελίδα δωρεών προς εμάς.  Πώς τα βρίσκω; 

viva merchant id
viva payments API key
Viva Payments CodeID

**Comment by dmihos** [comment]
Καλησπέρα
Στο μενού Ρυθμίσεις>Πρόσβαση API θα βρείτε το MerchantId και το API key.
Ως CodeID μάλλον αναφέρεστε στο SourceCode, οπότε θα το βρείτε στο μενού Οι Πωλήσεις μου>Πηγές Πληρωμών
