### ISSUE TITLE
Native Checkout V2 Error

### ISSUE THREAD

**Issue by odysseas12** [VivaPayments/API#1070]
The following request fails.
`{
  "creditCard": {
      "token": "ctok_U8OCfj73etqZ-L-JhCotSIITo7M"
    },
    "orderCode": "2002756994032273",
    "SourceCode": 2232,
    "Installments":1,
	"AllowsRecurring":false,
	"Amount":22700
}`

Response
`{
    "Emv": null,
    "Amount": null,
    "StatusId": "E",
    "CurrencyCode": null,
    "TransactionId": null,
    "ReferenceNumber": null,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ThreeDSecureStatusId": null,
    "ErrorCode": 403,
    "ErrorText": "Source 2232 of merchant ee8c7898-639b-4319-a6a9-6880add32ecd supports only native checkout",
    "TimeStamp": "2019-09-14T03:12:55.7998504+03:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": false
}`

The same request using a token from Native V1 works fine.

**Comment by matthewrgourd** [comment]
Hi @odysseas12 , I'm not sure what's happening here. I think there may be a flag our development team has to switch on for your account. I will check this a.s.a.p. on Monday.

**Comment by Sotiris-k** [comment]
I may be able to help here, if this is a demo transaction I can safely say that the source type inside the demo account needs to actually be checked as "Redirect" instead of "Native".

![image](https://user-images.githubusercontent.com/4454324/64911856-a26d0800-d72f-11e9-9bb0-3e32f63a5672.png)

**Comment by odysseas12** [comment]
Thanks Sotiris, that was the issue, I was up till 3 bunging my head on the wall trying to figure out what was wrong.

@matthewrgourd  
I dont have the production credentials yet but I assume the payment source should stay as Native there.

Also any way to emulate a 3DS secured card and get cardHolderAuthInitiated and cardHolderAuthFinished triggered ?

**Comment by matthewrgourd** [comment]
@odysseas12 At present you have to select to select **Redirect** not **Native** in the source for both demo and production account types. We intend to change the wording as soon as possible. In answer to your question about emulating a 3DS-secured card, please see https://github.com/VivaPayments/API/issues/1073#issuecomment-532243393
