### ISSUE TITLE
Viva payments/ simple checkout: Problem with multiple buttons

### ISSUE THREAD

**Issue by Tinakicious** [VivaPayments/API#1071]
Hello!

I seem to getting a problem with Viva payments simple checkout.
I follow the instructions here: https://developer.vivawallet.com/online-checkouts/simple-checkout/
1 single button works fine, but when Im trying to add more than 1 button, they turn into small grey buttons, without text in them and they are also not functional.

My code is the fillowing:
`<form id="myform" action="/checkout" method="post">
        <button type="button"
          data-vp-publickey="LZmm8E8FLUJmRMPQFAssIV3mkzsrgQ3wbDIp7XcsZno="
          data-vp-baseurl="https://demo.vivapayments.com"
          data-vp-amount= "<?php echo $params->get('data-vp-amount'); ?>"
          data-vp-description= "<?php echo  $params->get('data-vp-description'); ?>"
          data-vp-lang= "<?php echo  $params->get('data-vp-lang'); ?>"
          data-vp-background-color= "<?php echo  $params->get('data-vp-background-color'); ?>"
          data-vp-color= "<?php echo  $params->get('data-vp-color'); ?>"
          data-vp-hover-background-color= "<?php echo  $params->get('data-vp-hover-background-color'); ?>"
          data-vp-hover-color= "<?php echo  $params->get('data-vp-hover-color'); ?>"
          data-vp-border-radius= "<?php echo  $params->get('data-vp-border-radius'); ?>"
          data-vp-text= "<?php echo  $params->get('data-vp-text'); ?>">
        </button>
      </form>`

as you can see I am using joomla module to create the button.
I've included those:

`      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://demo.vivapayments.com/web/checkout/js"></script>`

inside index.php folder.

Thanks in advance

**Comment by matthewrgourd** [comment]
Hi @Tinakicious the problem (I think) is that you're attempting to use multiple buttons on one page. I'm not sure why you would want to do this. Perhaps you can send through a bit more info. @sdstef If you're experiencing an issue yourself please raise it separately with full details including screenshots.
