### ISSUE TITLE
Redirection after succesfull payment not working

### ISSUE THREAD

**Issue by bairamispanagiotis** [VivaPayments/API#1072]
Hello!

I have a problem with viva payment module for prestashop.

After succesful payment im redirecting correct to payment url, but i have two issues.

-Script redirect me to cart without data (empty cart)
-Got from script 500 error

Why that happening? has to do something with database tables?

Shop is a multistore version 1.7.5.2

Thanks!

**Comment by VivaWalletSupport** [comment]
Hello, are you using the latest version and instructions from https://developer.vivawallet.com/e-commerce-plugins/prestashop/ ?

**Comment by bairamispanagiotis** [comment]
Yes, and viva charge correct the amount on checkout. The problem begins on success redirect.

**Comment by VivaWalletSupport** [comment]
What URLs are used for success / fail in the payment source?

**Comment by bairamispanagiotis** [comment]
On the web hook settings i add module/vivawallet/success and module/vivawallet/fail.

You want me to send you the full url?

**Comment by VivaWalletSupport** [comment]
Please provide following screesnhots and we will look into the issue:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by bairamispanagiotis** [comment]
![image (4)](https://user-images.githubusercontent.com/3509439/64948350-8b3d3000-d87f-11e9-986b-4e6666d5c088.png)
![image (5)](https://user-images.githubusercontent.com/3509439/64948396-a5770e00-d87f-11e9-827c-870bf788681d.png)
![image](https://user-images.githubusercontent.com/3509439/64948536-fab31f80-d87f-11e9-8b94-e2775513e5d6.png)
![image (1)](https://user-images.githubusercontent.com/3509439/64948554-030b5a80-d880-11e9-8376-75ea5ba27d15.png)


Are those images ok?

**Comment by VivaWalletSupport** [comment]
The setup looks correct, anything reported in your Prestashop logfile about the 500 error?

**Comment by bairamispanagiotis** [comment]
Nothing, just some old errors.

Can this be a webhook error?

For example, if  I add modules/vivawallet/webhook.php instead of module/vivawallet/webhook

can this cause an error?

**Comment by bairamispanagiotis** [comment]
PHP Fatal error:  Uncaught Error: Using $this when not in object context in /modules/vivawallet/webhook.php:62\nStack trace:\n#0 {main}\n  thrown in /modules/vivawallet/webhook.php on line 62

**Comment by VivaWalletSupport** [comment]
I would suggest to leave the webhook until the default functioning is working correctly, please try attached. 
[vivawallet.zip](https://github.com/VivaPayments/API/files/3616429/vivawallet.zip)

**Comment by bairamispanagiotis** [comment]
Guys thank you very much, its working.

I leave the webhook as it is?

**Comment by VivaWalletSupport** [comment]
You can leave the webhook, but use attached updated package that has also a fix for the webhook / multistore. 
[vivawallet.zip](https://github.com/VivaPayments/API/files/3616642/vivawallet.zip)

**Comment by bairamispanagiotis** [comment]
Hello again,

tha last zipped module did the same as before, after succefull payment the redirection is on an empty cart.

I m  waiting for another zip?

**Comment by VivaWalletSupport** [comment]
Try after removing the webhook.

**Comment by bairamispanagiotis** [comment]
we deleted the webhook form the api settings but the same thing happened.

**Comment by bairamispanagiotis** [comment]
is it safe to upload the first zipped module? or we have to wait for another one? or a settings change?

**Comment by VivaWalletSupport** [comment]
There is no harm to try again the first zipped package.

**Comment by bairamispanagiotis** [comment]
In order to use the first zip, i have to disable or enable webhook?

**Comment by VivaWalletSupport** [comment]
It should not matter..

**Comment by bairamispanagiotis** [comment]
The same think happen, after a succefull payment redirect me to success with 500 error

 PHP Fatal error:  Uncaught Error: Using $this when not in object context in /modules/vivawallet/webhook.php:62\nStack trace:\n#0 {main}\n  thrown in /modules/vivawallet/webhook.php on line 62

**Comment by bairamispanagiotis** [comment]
I add three different sources for multistore and its working.
