### ISSUE TITLE
Native Checkout V2 - redirectToACSForm always null

### ISSUE THREAD

**Issue by odysseas12** [VivaPayments/API#1074]
This is the request I send
{
"Cvc": "111",
"Amount": 1000,
"Number": "4111111111111111",
"Holdername": "John Doe",
"ExpirationYear": 2030,
"ExpirationMonth": 10,
"AuthenticateCardholder": true,
"SessionRedirectUrl": ""
}

I get back

{
"chargeToken": "ctok_kGPRS6X-n3a0MRmijP0Bgi7yf18",
"redirectToACSForm": null
}

**Comment by matthewrgourd** [comment]
Hi @odysseas12 please can you send through your request / response logs so we can investigate further. Ensure any confidential information is blanked out. Thanks!

**Comment by matthewrgourd** [comment]
Hi @odysseas12, as you've not replied, I'm assuming this is no longer a problem. However, if not, please reopen the issue. Thanks!
