### ISSUE TITLE
Viva Payments API

### ISSUE THREAD

**Issue by boscaned** [VivaPayments/API#1075]
I need my Client ID and Client Secret.

**Comment by boscaned** [comment]
I need both demo and production access.

**Comment by matthewrgourd** [comment]
No problem, please send your demo and production merchant IDs to mgourd@vivawallet.com along with your business name and email address.

**Comment by boscaned** [comment]
Where can I find the demo and production merchant ID?

**Comment by matthewrgourd** [comment]
Hi @boscaned the merchant ID is under **Settings / API** access. Log in first either to [demo](https://demo.vivapayments.com/en-us/signin) or [production](https://www.vivapayments.com/en-us/signin).
