### ISSUE TITLE
Card Charge status

### ISSUE THREAD

**Issue by ezekiel1977** [VivaPayments/API#1079]
Hello,
Two customers today tried placing an order from the website. When they entered the OTP in the 3D  secure portal they received a message there stating that the purchase was successful however the page then got redirected to the checkout showing an error message. There is no record of any charge in my Viva wallet account. Is this a problem from my end or the customer's bank?
Please look into it and let me know.
Regards,
Ezekiel Dcosta
Nyvana Limited

**Comment by matthewrgourd** [comment]
Hi @ezekiel1977 , apologies for the delayed reply. Please can you let me know which of our online checkouts, e-commerce plugins or APIs you're using. If possible include some screenshots obscuring any confidential data.

**Comment by ezekiel1977** [comment]
Hello Matthew,
Thank you for your email.
The issue has been resolved now. The problem was with the customer's 
bank and not from our side.

Regards,
Ezekiel Dcosta
