### ISSUE TITLE
Problem changing website

### ISSUE THREAD

**Issue by chgiak** [VivaPayments/API#108]
We have built a new web site and ty tried to transfer viva wallet payment.
During the tests everything was working fine.
When we shift in poduction we set the proper merchant_id and api ketys.

On create order we are getting the following error
{"OrderCode":null,"ErrorCode":403,"ErrorText":"The merchant with id xxxxxxxx does not have a source with code 'xxxx' assigned or the source is disabled","TimeStamp":"2016-05-17T17:52:19.761055+03:00"}

instead of getting OK and the redirection url.

We tried also to create additional payment sources but the problem is the same.
Although we created an additional payment source from account control panel, we couldn't delete the default one.

I look forward for support.

Thank you

**Comment by dmihos** [comment]
Hi chgiak
Is the source enabled and in "Active" status?

**Comment by chgiak** [comment]
Hi dmihos

We use the default payment sources on each wallet. There is no any option for enabling or disabling.
Moreover there is no option to delete default sources.

Please have in mind that viva wallet was working fine on the old website. We just changed the success and failed urls on each wallet. No other change.

Please have in mind that demo account is working fine on the new website too. There is no any technical issue with the new website. The request of order creation is taking place and the aforementioned reply with error number 403 is taken back.

**Comment by dmihos** [comment]
If all sources are active, then you are probably an invalid SourceCode during CreateOrder.
Are you using 'Default' as sourcecode (or empty, as it fallbacks to Default)?
