### ISSUE TITLE
Refund Issue

### ISSUE THREAD

**Issue by ayushpandey15** [VivaPayments/API#1080]
Hello 
After placing the order using viva simple checkout. We can't able to refund the amount as its always getting Transaction Failed. We have already enabled refund and OCT in the account and 
the transaction_id  is 195aaa03-1943-43c0-8681-4687730e6730

This is the request "https://demo.vivapayments.com/api/transactions/195aaa03-1943-43c0-8681-4687730e6730?amount=400&ServiceId=6"

This is the response {
    "Emv": null,
    "Amount": -4.00,
    "StatusId": "E",
    "CurrencyCode": "826",
    "TransactionId": "1999eb1a-50c7-425d-9692-bada71a14161",
    "ReferenceNumber": 103908,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ThreeDSecureStatusId": 2,
    "ErrorCode": 502,
    "ErrorText": "Transaction failed",
    "TimeStamp": "2019-09-18T09:53:27.2130308+03:00",
    "CorrelationId": null,
    "EventId": 311,
    "Success": false
}

**Comment by Delivertoo** [comment]
@VivaWalletSupport  Can you help us ?

**Comment by matthewrgourd** [comment]
Hi there, I've checked your account and all seems fine. I will need to escalate to a developer. Bear with me and I'll get back to you. Thanks! Matt

**Comment by Shubham3454** [comment]
@viva-payments  @VivaWalletSupport

**Comment by Delivertoo** [comment]
@matthewrgourd @VivaWalletSupport  Μπορείτε να μας βοηθήσετε ή πρέπει να επιλέξουμε άλλη λύση ?

**Comment by dpnevmatikos** [comment]
Hello @Delivertoo 
OCT transactions are only allowed to merchants with gambling activities. 
You should omit the `serviceId=6` when making the `delete` transaction request.

**Comment by Shubham3454** [comment]
@dpnevmatikos  I have tried that also I have removed  serviceId =6 also  I was still facing the same issue

**Comment by dpnevmatikos** [comment]
Hi @Shubham3454  could you please try to create a new transaction and then cancel it ?

502 http status codes usually relate to systemic errors and since it's the demo env we're talking about, it is quite possible that you happen to stumble upon an env's upgrade or a network error within our cluster.

If you still hit a wall again then please post both your request options, as well as our response.
