### ISSUE TITLE
Disable Payment Confirmation Email

### ISSUE THREAD

**Issue by digu087** [VivaPayments/API#1081]
Hello @matthewrgourd 
Is there a way to disable payment confirmation email that clients receive . I  am sending the confirmation email on my end so would like to disable the default email that the gateway sends .

Thanks

**Comment by matthewrgourd** [comment]
Hi @digu087 I think you can do this but you need to ring our customer service desk to have it switched off. Thanks! + 44 (20) 37347770

**Comment by digu087** [comment]
@matthewrgourd  Thanks
