### ISSUE TITLE
Plugin για το Openshop του ELXIS 5.0 CMS

### ISSUE THREAD

**Issue by ewdewd** [VivaPayments/API#1082]
Καλησπέρα σας,
Υπάρχει το ενδεχόμενο να  δημιουργήσετε plugin για το Openshop του ELXIS 5.0 CMS ;
http://www.elxis.org/el/ (Ελληνικό  Open Source CMS ).
Ευχαριστώ .

**Comment by matthewrgourd** [comment]
Hi there, I'm afraid our payment gateway doesn't support Openshop. For our full list of plugins please see [E-commerce plugins](https://developer.vivawallet.com/e-commerce-plugins) on the Viva Wallet Developer Portal.
