### ISSUE TITLE
Apply for client credentials

### ISSUE THREAD

**Issue by terracom** [VivaPayments/API#1083]
Hi, could you please provide client credentials for DEMO environment?
Despite the fact you provided us credentials for our prod environment, unfortunately we had some issues and we shall need to make some further tests.
thanks in advance

**Comment by matthewrgourd** [comment]
Hi @terracom please email mgourd@vivawallet.com with the relevant merchant ID for your [demo account](https://developer.vivawallet.com/account-types/#demo). Thanks!

**Comment by matthewrgourd** [comment]
Sent by email. Thanks!
