### ISSUE TITLE
Προβλημα στο prestashop 1.7

### ISSUE THREAD

**Issue by texnikoss** [VivaPayments/API#1084]
Φτιαχνω τα παντα αλλα δεν  δουλευει
δειτε το προβλημα που εχω

![image](https://user-images.githubusercontent.com/55501223/65164519-bd988a00-da45-11e9-9903-dcaadecb6038.png)

εχω ακολουθησει ολα τα βηματα και τα εχω κανει σωστα. 
Μηπως βαζω λαθος Link  σε αυτο το κουτι? τι ακριβως βαζω.

**Comment by Sotiris-k** [comment]
Το https://selida.com το άλλαξες για χάρη του screenshot; Γιατι προφανώς εκεί πρέπει να βάλεις ένα ενεργό URL.

**Comment by texnikoss** [comment]
Καλησπερα ναι. Το ξερω. 

Τελικα πως θα το κανω να δουλεψει ξερει καποιος εχω βασανιστει 10 μερες τωρα

**Comment by VivaWalletSupport** [comment]
Please update the vivawallet\controllers\front\webhook.php code with using the revised version from https://github.com/VivaPayments/API/blob/master/Plugins/prestashop/vivawallet/controllers/front/webhook.php

**Comment by texnikoss** [comment]
You say me to change the code from the file  with this? And  after I will setup again?

**Comment by VivaWalletSupport** [comment]
Use the new webhook.php code and try setting up the webhook functionality afterwards from your Viva account.

**Comment by texnikoss** [comment]
Το ιδιο βγαζει. Αλλαξα αυτό που ειπες αλλα δεν εκανε τιποτα απλα μετα από αυτό δεν  εμφανιζεται καθολου μεσα στις πληρωμες μου η Viva.  Εκανα ζημια  δηλαδη αντι να το φτιαξω

**Comment by VivaWalletSupport** [comment]
Try removing the current plugin and install from the beginning, download the packages from https://developer.vivawallet.com/e-commerce-plugins/prestashop/

**Comment by texnikoss** [comment]
You tell me  to unistall and install again  with the same  program? Or someone is  fix and change the program I am download?

**Comment by VivaWalletSupport** [comment]
The package has been updated and contains all fixes.

**Comment by texnikoss** [comment]
NOT WORKING NOW

**Comment by texnikoss** [comment]
And now why don’t see on my page? :/

**Comment by texnikoss** [comment]
I AM READYYYYYYYYYYYYYYYYYYYYYYYYY 😊
