### ISSUE TITLE
Handling Wrong Card Input

### ISSUE THREAD

**Issue by beisnikosspi** [VivaPayments/API#1085]
Hello all,

When we were using the v1 native checkout, during the VivaPayments.cards.setup, we had an event called cardTokenHandler. This event received a response object that contained an ErrorText which described what went wrong.

Now we are trying ti integrate the v2 native checkout, but I don't see anything like this. I've searched the documentation as well. So, how can we catch the following error scenarios?

1. Cardholder name is empty
2. Cardnumber or cvv is empty
3. The customers enters an invalid date (eg month 13)
4. The customer enters an expired card
5. The customer enters an invalid card number

Thanks in advance!

**Comment by odysseas12** [comment]
You get an error response if the promise fails, see below

 VivaPayments.cards.requestToken({
  amount: 1321, // amount is in currency's minor unit of measurement
  installments: 10,
  authenticateCardholder: true
}).done(function (responseData) {
  console.log(`Here is the charge token: ${responseData.chargeToken}`);
}).fail(function(error){
  console.log(error) // error object here
});

**Comment by beisnikosspi** [comment]
I have tested with an expired card but it doesn't work:
TEST NAME, 4111111111111111, 111, 01/2019

I have tested also with another expired card:
TEST NAME, 4111111111111111, 111, 01/2000 and the error response does not say anything about expiration date: {"Error":{"ErrorCode":400,"ErrorText":"VivaPayments: Bad Request"}}

I have also tested with empty CVV and no error appears. Should't an error regarding empty cvv appear?

Thanks,

**Comment by odysseas12** [comment]
You can easily validate user input and display the appropriate notifications like you would on any form.
If user passes validation then call requestToken.

**Comment by beisnikosspi** [comment]
Yes I know that I can do a custom validation. The purpose of this post is to mention that your implementation is a little bit problematic in this case. In v1 it used to work but now it doesn't work.

Cheers.

**Comment by matthewrgourd** [comment]
Hi @beisnikosspi I think @odysseas12 has answered your queries so I'm closing this now. Regarding the removal of `cardTokenHandler`, yes, that's correct, because `requestToken` uses a Promise to return the chargeToken’s value.
