### ISSUE TITLE
window.on("message") error in VivaWallet JS

### ISSUE THREAD

**Issue by jkatsiotis** [VivaPayments/API#1086]
This code 

`t(window).on("message",function(t){var i=JSON.parse(t.originalEvent.data);i.MessageType===n.MessageType.THREEDSECURE&&u.state() {snip}`

throws the following error:

Unexpected token o in JSON at position 1 in in JSON.parse.

Can you look into it?

**Comment by matthewrgourd** [comment]
Hi @jkatsiotis, I will get one of our developers to look into it. Looks like we may need to update the code. Apologies for any inconvenience caused.

**Comment by matthewrgourd** [comment]
Hi there, is this still an issue or was it solved by the result update to the JS?

**Comment by jkatsiotis** [comment]
No this isn't fixed. I can confirm the issue appeared 10mins ago. This line " JSON.parse(e.originalEvent.data)" is causing the error. Just put a try/catch.

window.on("message") is pretty generic and there are many libraries (for example Facebook Pixel) that use that event to handle data. So this fires many times within the lifecycle of the page

**Comment by matthewrgourd** [comment]
Hi @jkatsiotis our development team has got back to me and apparently the issue should be fixed now. Thanks!
