### ISSUE TITLE
webhook for virtuemart 3 error 502

### ISSUE THREAD

**Issue by panmo21** [VivaPayments/API#1088]
Κατά την εισαγωγή του url για την δημιουργία webhook για το virtuemart3 εμφανίζεται error 502. 
Έχω 2 domain στα οποία είναι εγκατεστημένο το plugin της vivapayments για το virtuemart 3, και στα 2 url που εισαγώγω δεν μπορώ να δημιουργήσω webhookg. Το redirection και οι πληρωμές λειτουργούν κανονικά.

**Comment by VivaWalletSupport** [comment]
Please try attached latest version.
[vm3_plugin_vivawallet.zip](https://github.com/VivaPayments/API/files/3638480/vm3_plugin_vivawallet.zip)

**Comment by panmo21** [comment]
Hi, thank you.
I have update the vm plugin and I have succesfully add the webhook for
domain name meletise.gr/apps.

I have also update the plugin for the domain apps.ergasiatora.gr and I try
to create a  new webhook for this domain. The new url added
successfully/verify but when I cilck on save button I am getting an error
Error! A Webhook for this Event Type already exists (Error code 409)

Στις Σάβ, 21 Σεπ 2019 στις 11:35 π.μ., ο/η Tom van der Veer <
notifications@github.com> έγραψε:

**Comment by VivaWalletSupport** [comment]
Apparently you can only use one webhook per account.
