### ISSUE TITLE
Invalid source account for native checkout v2

### ISSUE THREAD

**Issue by asamaras11** [VivaPayments/API#1089]
Hello all,

I've completed the transition to native checkout v2.
I've used the demo account and I've managed to get an access token and create a charge token successfully. So far so good. The problem is that when the server tries to create the order, I'm getting the following error:
`Source 1350 of merchant 1d8712a7-c9cf-4b5e-b930-1a630adae194 supports only native checkout`

I've checked the source at the demo environment and indeed has the "Native checkout" radio button enabled. As it should do with v1.
Am I missing something?

Let me know if you need me to provide more info for the account.

Thanks

**Comment by matthewrgourd** [comment]
Hi @asamaras11 we've got to apply a fix but in the meantime when you set up your source in the web app choose "Redirection" instead of "Native/Pay with Viva Wallet Checkout: https://github.com/VivaPayments/API/issues/1070#issuecomment-531498753 Thanks!
