### ISSUE TITLE
CancelTransaction: 403

### ISSUE THREAD

**Issue by christianago** [VivaPayments/API#109]
Hello. I am experiencing issue with the request: CancelTransaction. 
Below is the response I get.
I cannot cancel a transaction that is made on the same day.
I understand that I am not allowed to do that (error code: 403)
but I do not understand what error text means and how I can fix it
(Source Default of merchant e1082881-7c55-4a4e-96d6-1642963134dd does not support native checkout).

Can you help please?

```
{
  "Emv": null,
  "Amount": null,
  "StatusId": "E",
  "TransactionId": null,
  "ReferenceNumber": null,
  "RemainingRefunds": null,
  "AuthorizationId": null,
  "ErrorCode": 403,
  "ErrorText": "Source Default of merchant e1082881-7c55-4a4e-96d6-1642963134dd does not support native checkout",
  "TimeStamp": "2016-05-18T15:20:54.5541923+03:00"
}
```

**Comment by dmihos** [comment]
Hi Cristianago
Are you using verb DELETE for this API call?
https://github.com/VivaPayments/API/wiki/CancelTransaction

**Comment by christianago** [comment]
Hi dmihos,
yes I make the DELETE request

**Comment by dmihos** [comment]
What is the transactionId you're trying to reverse?
Can you post a sample of your code?

**Comment by Tejas-narola** [comment]
@dmihos . I am chirps colleagues. 

Actually when we are calling “Payment Execution” API and we are getting following error.

{
  "Emv": null,
  "Amount": null,
  "StatusId": "E",
  "TransactionId": null,
  "ReferenceNumber": null,
  "RemainingRefunds": null,
  "AuthorizationId": null,
  "ErrorCode": 403,
  "ErrorText": "Source Default of merchant e1082881-7c55-4a4e-96d6-1642963134dd does not support native checkout",
  "TimeStamp": "2016-05-18T15:20:54.5541923+03:00"
}

Also we have checked to our account on demo.vivapayment and native checkout is enabled. 

![screen shot 2016-05-19 at 4 19 29 pm](https://cloud.githubusercontent.com/assets/5028455/15391260/d1c4d2e0-1ddd-11e6-9d09-8804e436dc0c.png)


Would you please guide us what could be the issue ?

**Comment by dmihos** [comment]
You will also need to change the integration type of source Default to Native Checkout (Menu > My Sales > Payment Sources)

**Comment by christianago** [comment]
Yes, it worked!
The process got approved very quickly.
Thank you so much for your time. ;)
