### ISSUE TITLE
Πρόβλημα με χρέωση κάρτας

### ISSUE THREAD

**Issue by giannis2019** [VivaPayments/API#1090]
Καλησπέρα,
προσπαθώ να συνδέσω στο site μου manual τη μέθοδο redirection αλλά ενώ με πάει στη σελίδα της viva κανονικά και μου περνάει και σωστά όλα τα στοιχεία μου βγάζει συνέχεια transaction failed.Έχω το τελευταίο orderid το οποίο είναι 6484420625291731.Μπορείτε να μου πείτε που οφείλεται το σφάλμα?

**Comment by matthewrgourd** [comment]
Hi there, please can you let me have the request / response logs and I will investigate further. It sounds like you're passing the parameter `PaymentTimeOut` or `ExpirationDate` with a value that is less than 300 seconds (5 minutes) therefore causing a timeout. Thanks!

**Comment by matthewrgourd** [comment]
Hi @giannis2019,

We cannot identify what’s wrong.

Suggest you try removing PaymentTimeOut completely just to check if it then works.
 
If it does and you still need to diversify from the default 5 min expiration you could try with the ExpirationDate [parameter](https://developer.vivawallet.com/api-reference-guide/payment-api/#optional-parameters), expressed in absolute datetime in ISO 8601 format. Please note that there is currently incorrect info in our Developer Portal about it being expressed in seconds. This will be updated as soon as possible. 

Thanks!

**Comment by giannis2019** [comment]
Το πρόβλημα ήτα ότι έλειπε η παράμετρος Sourcecode από τα πεδία της post.
Ευχαριστώ για το χρόνο σας.
