### ISSUE TITLE
Recurring Payment

### ISSUE THREAD

**Issue by deliverymanager** [VivaPayments/API#1092]
How do we make a recurring payment in 3DS v2 native?
I cannot find any documentation for version 2.

**Comment by armaan123sharma** [comment]
Can you please help me with refund of transaction

**Comment by matthewrgourd** [comment]
Hi @deliverymanager please see https://developer.vivawallet.com/api-reference-guide/payment-api/#create-recurring-transaction
@armaan123sharma see https://developer.vivawallet.com/api-reference-guide/payment-api/#cancel-transaction Hope this helps!

**Comment by deliverymanager** [comment]
This ia the old classic way to make a recurring transaction.
What about the 3DS way?
What if the credit card ia 3DS enabled and we need to show the iframe in order for the user is able to add the code he code via SMS for his saved credit card.

**Comment by matthewrgourd** [comment]
@deliverymanager I'll check with our dev team and get back to you shortly.

**Comment by deliverymanager** [comment]
Any news on that?
Thank you

**Comment by matthewrgourd** [comment]
Hi @deliverymanager I've spoken to our dev team and apparently we're working on an alternative but at the moment you need to use the old classic method.

**Comment by deliverymanager** [comment]
Any news on the alternative method?
Or an estimate of the release date?

**Comment by matthewrgourd** [comment]
No news as yet. @dpnevmatikos Can you provide any updates? Thanks!

**Comment by viclec** [comment]
Is it possible to create recurring transactions with simple checkout?

**Comment by matthewrgourd** [comment]
@viclec No, you would need to use Redirect Checkout. Please see the following answer: https://www.nopservices.com/contactus
