### ISSUE TITLE
refund transaction issue

### ISSUE THREAD

**Issue by armaan123sharma** [VivaPayments/API#1093]
Hi . I am armaan. 

I am integrating viva wallet. but i am stuck with the integration. In refund case, I am not able to get success from refund API . i have enable refund from viva accound and using ServiceId = 6 as well. 

this is my URL-> 
https://demo.vivapayments.com/api/transactions/d3e01acf-52b5-47eb-b8df-10497c46340e?amount=900&ServiceId=6

and response i get from viva is 

{
    "Emv": null,
    "Amount": -9,
    "StatusId": "E",
    "CurrencyCode": "826",
    "TransactionId": "18b41a41-d179-4643-9428-6a6d211d2744",
    "ReferenceNumber": 104809,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ThreeDSecureStatusId": 2,
    "ErrorCode": 502,
    "ErrorText": "Transaction failed",
    "TimeStamp": "2019-09-24T10:39:19.3303768+03:00",
    "CorrelationId": null,
    "EventId": 311,
    "Success": false
}

kindly please look into it on priority. 

Thanks

**Comment by deliverymanager** [comment]
Check the Amount.
It looks wrong to me

**Comment by armaan123sharma** [comment]
I have make transaction of 10 and i am refunding 9 ..the amount seems to be correct. becasue viva get amount in cents so 9 becomes 900
