### ISSUE TITLE
request for premission on refund API

### ISSUE THREAD

**Issue by armaan123sharma** [VivaPayments/API#1094]
I have read the documentation of viva wallet. 

and I am facing issue in refund API. i have enabled refund option in dashboard account. and i received error every time when i hit API of refund. while reading documentation I have found this line.
what does that line means
"You need to specifically be granted access to this API call. Please request permission by raising an issue via our public GitHub account.".

Kindly please resolve this.

**Comment by matthewrgourd** [comment]
Hi @armaan123sharma I think you need to look at this section of the Developer Portal: https://developer.vivawallet.com/api-reference-guide/payment-api/#cancel-transaction . However, I will ask the dev team more about OCT which you initially mentioned as I'm not sure what the process is now for accessing that endpoint.

**Comment by matthewrgourd** [comment]
Hi @armaan123sharma I've checked with our developers and the OCT endpoint is reserved for merchants with a business category of 'gambling'. Please use [Cancel transaction](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1transactions~1{Id}/delete) instead. Thanks!
