### ISSUE TITLE
Request for Demo API Access

### ISSUE THREAD

**Issue by dpantazis94** [VivaPayments/API#1095]
Hello everyone,

I am trying to complete the steps described here https://developer.vivawallet.com/online-checkouts/migrating-from-native-checkout-v1/ . From what I ' ve read in your documentation i need to apply for client credentials. For the time being i need demo credentials ( sandbox ). 

Environment: Demo
API Access: Native Checkout v2.0

Please contact with me when available.

Thank you in advance,

Dimitris

**Comment by matthewrgourd** [comment]
Please email mgourd@vivawallet.com with the business name and merchant ID. Thanks!

**Comment by matthewrgourd** [comment]
Hi @dpantazis94 , our Dev Team has just informed me that a new feature for generating your own demo credentials is now available at the following location:

https://demo.vivapayments.com/selfcare/en/security/apiaccess

Please check in the 'Native Checkout v2 Credentials’ section. Any queries, please let me know. I'll be updating the documentation around this next week. Thanks!

**Comment by dpantazis94** [comment]
Thanks a lot @matthewrgourd !
