### ISSUE TITLE
VM3, error 500 μετά από επιτυχημένη πληρωμή

### ISSUE THREAD

**Issue by panmo21** [VivaPayments/API#1096]
Γεια σας,
έχω εγκατεστημένο virtumart 3, μετά την επιτυχημένη πληρωμή στην προσπάθεια επιστροφής στο eshop για να εμφανιστεί η success page εμφανίζεται error page 500, το url που εμφανίζει το error είναι το 

mydomain.gr/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&bnkact=success&t=02c96985-a2b1-441a-aadb-0fae7b301948&s=8882324090572602&lang=el-GR&eventId=0&eci=2

**Comment by VivaWalletSupport** [comment]
Hello, did you recently download the updated plugin?

**Comment by panmo21** [comment]
Yes

Στις Τρί, 24 Σεπ 2019, 17:33 ο χρήστης Tom van der Veer <
notifications@github.com> έγραψε:

**Comment by VivaWalletSupport** [comment]
Please provide following screenshots and we will look into the issue:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by panmo21** [comment]
![Screenshot 2019-09-24 20 46 31](https://user-images.githubusercontent.com/55593375/65538130-59773980-df0f-11e9-8069-9b049f3203d5.png)
![Screenshot 2019-09-24 20 48 06](https://user-images.githubusercontent.com/55593375/65538131-59773980-df0f-11e9-8721-d130d12bae91.png)
![Screenshot 2019-09-24 20 48 46](https://user-images.githubusercontent.com/55593375/65538132-5a0fd000-df0f-11e9-8eb1-223919246121.png)
![Screenshot 2019-09-24 21 02 25](https://user-images.githubusercontent.com/55593375/65538134-5a0fd000-df0f-11e9-9949-95b137fd629d.png)
![Screenshot 2019-09-24 21 02 33](https://user-images.githubusercontent.com/55593375/65538135-5a0fd000-df0f-11e9-999d-752e0ff57d9c.png)

**Comment by VivaWalletSupport** [comment]
Try after correcting the protocal in the payment source to https.

**Comment by panmo21** [comment]
I have try it also. Same problem.

Στις Τετ, 25 Σεπ 2019, 07:28 ο χρήστης Tom van der Veer <
notifications@github.com> έγραψε:

**Comment by VivaWalletSupport** [comment]
Could you check what is causing the 500 error and/or maybe to setup a clean version of VirtueMart and test?

**Comment by panmo21** [comment]
Το πρόβλημα δημιουργούταν επειδή έλειπε η βιβλιοθήκη που είναι υπεύθυνη για την δημιουργία των pdf για τις αποδείξεις πληρωμών στο virtuemart.
