### ISSUE TITLE
Test card failures

### ISSUE THREAD

**Issue by adrianblynch** [VivaPayments/API#1097]
Is it possible to trigger failures from Native Checkout v1 via test cards?

Much like [Checkout has a way to trigger various error messages](https://docs.checkout.com/docs/testing), I'd like to do the same in Viva.

I use 41111... for successful test payments, I'd like to trigger failures on demand.

Thanks.

**Comment by matthewrgourd** [comment]
Hi there, we advise using [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) as v1 has been deprecated. As regards triggering different error messages, we've not quite reached the same point as Checkout.com but I'm sure we will in the future. Thanks!
