### ISSUE TITLE
Oauth Credentials

### ISSUE THREAD

**Issue by korgoth** [VivaPayments/API#1098]
Hi there:
I require OAuth credentails as follows:

Environment: Demo
API Access: Native Checkout v2.0

Thanks in advance!

**Comment by matthewrgourd** [comment]
Please email mgourd@vivawallet.com with the business name and demo merchant ID. Thanks!

**Comment by matthewrgourd** [comment]
Hi @korgoth , our Dev Team has just informed me that a new feature for generating your own demo credentials is now available at the following location:

https://demo.vivapayments.com/selfcare/en/security/apiaccess

Please check in the 'Native Checkout v2 Credentials’ section. Any queries, please let me know. I'll be updating the documentation around this next week. Thanks!
