### ISSUE TITLE
Issue while processing VIVA refund through API 

### ISSUE THREAD

**Issue by Shubham3454** [VivaPayments/API#1099]
Hi,
I am using viva payment API for payment and now I want to do a partial refund, but I am facing some issue, I am using this request - https://demo.vivapayments.com/api/transactions/()merchant_id?amount=90&ServiceId=6
and I am getting this response
{
    "Emv": null,
    "Amount": null,
    "StatusId": "E",
    "CurrencyCode": null,
    "TransactionId": null,
    "ReferenceNumber": null,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ThreeDSecureStatusId": null,
    "ErrorCode": 403,
    "ErrorText": "OCT is disabled for the merchant (merchant_id)",
    "TimeStamp": "2019-09-24T16:45:08.6235347+03:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": false
}

@viva-payments  @VivaWalletSupport

**Comment by matthewrgourd** [comment]
Hi @Shubham3454 I believe you need to use [Cancel transaction](https://developer.vivawallet.com/api-reference-guide/payment-api/#cancel-transaction) rather than OCT which is by request only.

**Comment by Shubham3454** [comment]
hi @matthewrgourd  as I have tried that also and in that case i am receiving this response  :- 
{
    "Emv": null,
    "Amount": null,
    "StatusId": "E",
    "CurrencyCode": null,
    "TransactionId": null,
    "ReferenceNumber": null,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ThreeDSecureStatusId": null,
    "ErrorCode": 403,
    "ErrorText": "Refund is disabled for the merchant 00e7a1c9-60fb-4eb1-8f08-798b7014875a",
    "TimeStamp": "2019-10-01T08:31:51.5070144+03:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": false
}
 the error message shows :- Refund is disabled for the merchant 00e7a1c9-60fb-4eb1-8f08-798b7014875a although my refund is enabled (in API Security features tab the check box is enabled ) for this merchant id I am not able to share the screan shot here it would be helpfull if you can provide an alternative to contact viva or you Like email or a video call

**Comment by matthewrgourd** [comment]
Hi @Shubham3454 I'm not sure why the refund feature won't work if it is enabled in the banking app. Let me ask a developer and get back to you. Thanks!

**Comment by Delivertoo** [comment]
@matthewrgourd  @VivaWalletSupport   είναι το τρίτο στην σειρά ερώτημα από την ομάδα που κάνει την ενσωμάτωση  και αυτό όπως και τα υπόλοιπα είναι σε εκκρεμότητα, θα μπορούσατε να μας βοηθήσετε.

**Comment by dpnevmatikos** [comment]
duplicate https://github.com/VivaPayments/API/issues/1080

**Comment by Shubham3454** [comment]
@matthewrgourd  any update on this ?
