### ISSUE TITLE
Πρόβλημα μετά την ολοκλήρωση πληρωμής

### ISSUE THREAD

**Issue by homeviv** [VivaPayments/API#110]
Ενώ έχει ολοκληρωθεί η διασύνδεση και ο πελάτης ανακατευθύνεται στη σελίδα της viva μόλις ολοκληρώσει την πληρωμή παραμένει εκεί και δεν επιστρέφει στην ιστοσελίδα μας. Βλεπει το παρακάτω.
https://drive.google.com/a/pixelone.gr/file/d/0B20d2vIA8DBiUlpLMVd3SGY5UEk/view

Τα urls επιτυχημένης συναλλαγής έχουν οριστεί κανονικά.

**Comment by dmihos** [comment]
Καλησπέρα homeviv
Υποθέτω έχετε φτιάξει μια νέα πηγή με τα urls σας, αλλά στο CreateOrder δεν περνάτε καθόλου OrderCode (ή περνάτε Default)
https://github.com/VivaPayments/API/wiki/CreateOrder

**Comment by homeviv** [comment]
Υπάρχει περίπτωση να φταίει κάτι άλλο; Το OrderCode περνάει απ ότι βλέπω.

**Comment by homeviv** [comment]
To πρόβλημα επιλύθηκε.

Ευχαριστώ
