### ISSUE TITLE
Woocommerce - Transaction Failed Message

### ISSUE THREAD

**Issue by craigb88** [VivaPayments/API#1100]
I've installed the Vivawallet WooCommerce plugin and set up all the details for online payment but transactions won't go through. 

When I checkout I get redirected to the Vivawallet checkout page. I then put in my card credentials I get the verified card message, then I get redirected back to my website with the error message "An error occured, please try again."

I check Viva and there no sales have gone through, in my WordPress orders it says there is an order awaiting payment.

**Comment by VivaWalletSupport** [comment]
Hello, did you setup for the demo environment?

**Comment by craigb88** [comment]
It’s on a production environment.

**Comment by craigb88** [comment]
I can give you access to the site / Wordpress if you need to view it.

Thanks

**Comment by VivaWalletSupport** [comment]
Please setup on the demo environment, test and move to production when everything is confirmed working correctly.

**Comment by craigb88** [comment]
Everything was working correctly. As you can see there is money in the account that came via the website. 
Do you have dummy card credentials I can use while in demo mode then?

**Comment by craigb88** [comment]
I’ve tried this in demo mode and still no luck. 
Any suggestions? 

Thanks

**Comment by VivaWalletSupport** [comment]
Could you define what went wrong exactly and what card data was used?

**Comment by matthewrgourd** [comment]
Hi @craigb88 as you've not replied, I'm assuming this is no longer a problem. However, if not, please reopen the issue. Thanks!
