### ISSUE TITLE
testing native checkout to sandbox always fails

### ISSUE THREAD

**Issue by dasimakis** [VivaPayments/API#1105]
Dears, the problem I am facing is that I can not test transactions anymore using demo card and sandbox cause always return the message viva payments error. This has start happening about a year ago but I never actually needed so I left it ….but now I needed to check my page. Can you help me ?

**Comment by matthewrgourd** [comment]
Hi @dasimakis could you send us some further details including request / response logs so we can look into further? Thanks!

**Comment by matthewrgourd** [comment]
Hi @dasimakis in case you're using Native Checkout v1 you actually need to implement [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) now as the former is deprecated. I hope this helps!
