### ISSUE TITLE
Issue with Simple Checkout process

### ISSUE THREAD

**Issue by Tinakicious** [VivaPayments/API#1107]
Hello!

I'm having an issue with Simple Checkout process.
I'm on Joomla CMS (not eshop - without Virtuemart)
I've connected the button as writen on your tutorial here: https://developer.vivawallet.com/online-checkouts/simple-checkout/

My code is the following:

1) a **module** for the button with the following code:
```

  <form id="myform" action="/index.php/en/checkout" method="post">
        <button type="button"
          data-vp-publickey="{{ public key here - cannot show that }}"
          data-vp-baseurl="https://www.vivapayments.com"
          data-vp-amount= "<?php echo $params->get('data-vp-amount'); ?>"
          data-vp-description= "<?php echo  $params->get('data-vp-description'); ?>"
          data-vp-lang= "<?php echo  $params->get('data-vp-lang'); ?>"
          data-vp-background-color= "<?php echo  $params->get('data-vp-background-color'); ?>"
          data-vp-color= "<?php echo  $params->get('data-vp-color'); ?>"
          data-vp-hover-background-color= "<?php echo  $params->get('data-vp-hover-background-color'); ?>"
          data-vp-hover-color= "<?php echo  $params->get('data-vp-hover-color'); ?>"
          data-vp-border-radius= "<?php echo  $params->get('data-vp-border-radius'); ?>"
          data-vp-text= "<?php echo  $params->get('data-vp-text'); ?>">	  
        </button>
      </form>
```
	  
	  <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://www.vivapayments.com/web/checkout/js"></script>
 
	  <script>
		public class TransactionResult
		{
			public int ErrorCode { get; set; }
			public decimal Amount { get; set; }
			public string ErrorText { get; set; }
			public Guid TransactionId { get; set; }
		}

		public async Task<TransactionResult> ChargeAsync(string vivaWalletToken)
		{
			var cl = new RestClient("https://www.vivapayments.com/api/") {
				Authenticator = new HttpBasicAuthenticator("{{ merchard id - cannot show that }}", "{{ api key here - cannot show that }}")
			};
			var request = new RestRequest("transactions", Method.POST) {
				RequestFormat = DataFormat.Json
			};

			request.AddParameter("PaymentToken", vivaWalletToken);

			var response = await cl.ExecuteTaskAsync<TransactionResult>(request);

			return response.ResponseStatus == ResponseStatus.Completed &&
				response.StatusCode == System.Net.HttpStatusCode.OK ? response.Data : ErrorCode;
		}
	  </script>

2) I'm assigning the module inside my page. I fill my credit card info, and until I click the button everything gets fine. After that I'm redirected to the checkout page (see forms action), which I created customly. After that nothing happens, no payment no anything. I tried to get $_POST on the checkout page and it returns an array with vivaWalletToken and vivaWalletPaymentMethod. 

How can I make the button to work and the payment to be completed?? Thank you

**Comment by matthewrgourd** [comment]
Hi @Tinakicious, I'll need to raise the issue with one of our developers. Let me do that and get back to you. Thanks!

**Comment by JulioIbro** [comment]
has anyone a working code for simple checkout? php or js preferred. I can't make it work, i am following the documentation but i can't have a completed test transaction. Any help will be appreciated

**Comment by matthewrgourd** [comment]
Hi @Tinakicious we've checked the provided code sample and the .net bit should be in your back end and not included as JavaScript in the front-end:
```
public class TransactionResult
	{
		public int ErrorCode { get; set; }
		public decimal Amount { get; set; }
		public string ErrorText { get; set; }
		public Guid TransactionId { get; set; }
	}

	public async Task<TransactionResult> ChargeAsync(string vivaWalletToken)
	{
		var cl = new RestClient("https://www.vivapayments.com/api/") {
			Authenticator = new HttpBasicAuthenticator("{{ merchard id - cannot show that }}", "{{ api key here - cannot show that }}")
		};
		var request = new RestRequest("transactions", Method.POST) {
			RequestFormat = DataFormat.Json
		};

		request.AddParameter("PaymentToken", vivaWalletToken);

		var response = await cl.ExecuteTaskAsync<TransactionResult>(request);

		return response.ResponseStatus == ResponseStatus.Completed &&
			response.StatusCode == System.Net.HttpStatusCode.OK ? response.Data : ErrorCode;
	}
```

**Comment by Tinakicious** [comment]
@matthewrgourd I already know that. 
Were should I put this in order to make the transaction completed successfully? Can you give me some instructions? (Go there do that and that etc).

Thanks in advance!

**Comment by matthewrgourd** [comment]
Hi @Tinakicious I'm sorry for the delayed reply but we're unable to give you help with specific platforms. If you're having issues with Simple Checkout I suggest you try implementing Native Checkout v2 instead. Alternatively, for a Viva Wallet plugin solution that works with Joomla you have a  choice of the following two options:

- [https://developer.vivawallet.com/e-commerce-plugins/joomdonation-eshop/](https://developer.vivawallet.com/e-commerce-plugins/joomdonation-eshop/)
- [https://developer.vivawallet.com/e-commerce-plugins/joomdonation-eshop/](https://developer.vivawallet.com/e-commerce-plugins/joomshopping/)

We don't a service whereby you can speak to one of our developers on the phone, I'm afraid. However, @dpnevmatikos has access to this channel so may be able to give a bit more input.

Hope that helps!

**Comment by ckefalianou** [comment]
Hello! I'm @Tinakicious I just opened a different account.

Look, there are plenty of github posts with php curl code but none of that makes the payment to be completed. As far as I can see, there are many developers that face the same problem. I don't know what is the point of providing a dotnet code for a button that is mostly used on websites... Native checkout uses dotnet as well, what is the difference? I've already read your tutorials I just need you to provide me more info on how I can run the simple checkout, I don't want checkout alternatives, this is supposed to work. 

So, please can you tell me with exact steps how can I get this button to work? Where should I run the dotnet code? Where on the server?

thank you

**Comment by matthewrgourd** [comment]
@ckefalianou @Tinakicious I've spoken to one of our developers and there's no further help we can provide. We don't provider training for developers as such, only support for our products which are well documented, although of course we're always striving to make improvements. We've taken on board your comments but can't assist you any more than we already have. Closing this ticket now. Have a good day!

**Comment by ckefalianou** [comment]
@matthewrgound of course you are.Giving some more info on how to run this code when so many developers ask is not "training" is "support, in case you don't know. Copying and pasting your own tutorial code, is not really helpful, but thank you anyway. Have a nice day.
