### ISSUE TITLE
URGENT - Issue History

### ISSUE THREAD

**Issue by Tinakicious** [VivaPayments/API#1108]
Hello! I've created an issue here  https://github.com/VivaPayments/API/issues/1107

Could you please delete the edited story cause I've published id's by mistake? Thank you!

**Comment by matthewrgourd** [comment]
Hi @Tinakicious, I can't see any of your IDs as only the [latest version](https://github.com/VivaPayments/API/issues/1107) of your post is showing? Let me know if you want me to delete that (but I don't think you do) . Alternatively, please send me a link to the page you want me to delete in case I've missed it. Thanks!

**Comment by ckefalianou** [comment]
@matthewrgourd Thank you for your fast response.
As I can see post history isn't visible now, so I think we are good! :)
Thank you!
