### ISSUE TITLE
Recieving Card Payments - Viva Wallet

### ISSUE THREAD

**Issue by Simonfbarrett** [VivaPayments/API#1109]
Good Morning a little help please, I am using Viva Wallet with generally no problems. However there have been a few times where customers have tried to purchase on my ecommerce store which is operated via WooCommerce and cards have not been accepted - various cards are tried MasterCard and visa and nothing works. This has happened with atleast 3 customers over the past few months. Any idea please?

**Comment by matthewrgourd** [comment]
Hi @Simonfbarrett unfortunately this will happen from time-to-time in the same way that customers in face-to-face transactions also have infrequent issues with the cards they attempt to use. However, if there is a pattern you can see (card issuer, card type etc.) please let me know and we will investigate further.
