### ISSUE TITLE
Viva Payment

### ISSUE THREAD

**Issue by beesmart1** [VivaPayments/API#111]
Καλημέρα

Έχω ένα eshop στο οποίο δέχομαι πληρωμές μέσω Viva.
O Developer αγόρασε τo extention εκ μέρους μου (τον πλήρωσα).
Μετά από προβλήματα που προέκυψαν, απο τον Developer, επικοινωνίας μετέφερα το site σε άλλο host και προσπαθώ να κάνω upgrade απο 1.5.5.1 στην τελευταία έκδοση.
Η ερώτηση μου είναι α. εάν χρειάζεται να προβώ σε νέα αγορά του extention?
                              & β. Θέλω για να χρησημοποιήσω το extention της Viva ακόμα σε ένα site της ίδιας εταιρείας άλλου Domain. Χρειάζεται επιπλέον αγορά άδειας?

Με εκτίμηση 
Γιιάννης

**Comment by dpnevmatikos** [comment]
Καλημέρα σας,
Το plugin στο οποίο αναφέρεστε δεν είναι της Viva Payments και έχει δημιουργηθεί από άλλη εταιρεία.
Θα πρέπει να επικοινωνήσετε μαζί τους για να σας δώσουν τις απαντήσεις που χρειάζεστε.

Ευχαριστούμε.
