### ISSUE TITLE
EUPHORIA DIRECT LIMITED - VivaWallet Integration Issues

### ISSUE THREAD

**Issue by EuphoriaDirect** [VivaPayments/API#1110]
[Viva Wallet Payment Gateway Integration Issues.docx](https://github.com/VivaPayments/API/files/3671705/Viva.Wallet.Payment.Gateway.Integration.Issues.docx)

**Comment by VivaWalletSupport** [comment]
Hello, I have no clue from where the message "_This order’s status is “Processing”—it cannot be paid for. Please contact us if you need assistance._" comes from, it does not come from the supported plugin and I have not received any other reports like this.
