### ISSUE TITLE
Viva Wallet Partial Billing (Τμηματικές Χρεώσεις)

### ISSUE THREAD

**Issue by Bambinaros** [VivaPayments/API#1111]
Good day,

We have an online shop allowing the purchase of products with customized logos on them and are currently intergrating VivaWallet as a payment method. We need to be able to offer our clients the option to buy an e-printing proof, which is a sample of how their logo will look on the product they are about to buy. We also use Composite Products (if you are familiar with them), so we can add the e-printing proof option as an extra component in each different product. (If you have a different suggestion on how to add this option in each product that also works better with VivaWallet, please let me know.)

What we need from VivaWallet is to allow for partial payments for all products that include the above mentioned e-printing proof. 
If a client chooses to acquire an e-printing proof, then they will only be billed for a flat amount - same for every product (ex. €10). 
If they decide to go forward with buying that specific product, then they must be able to go into their order and choose to accept the charge for the full product price minus the e-printing proof they already paid for. If they decide not to go forward with the purchase, then the e-printing proof is not refundable.
Alternatively, they could pay for the e-printing proof while the rest of that product's bill could be withheld in their account until they choose to pay the full amount, in which case the rest of the bill is also paid. If they decide not to go forward with the purchase, then the withheld amount is released and, as above, the e-printing proof is not refundable.
Can the above functionality be achieved with VivaWallet and how?

For any further information you may need, please contact me. Thank you for your time.

**Comment by matthewrgourd** [comment]
Hi @Bambinaros, apologies, I'm afraid we cannot provide specific advice on bespoke e-commerce solutions. Our [Online Checkout](https://developer.vivawallet.com/online-checkouts/) and [e-commerce plugins](https://developer.vivawallet.com/e-commerce-plugins/) work out of the box and you can use our [payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/) for any custom solution, but as far as I'm aware there is no partial payment option available within any of these.
