### ISSUE TITLE
Incorporating Vivawallet to OpenCart 1.5

### ISSUE THREAD

**Issue by ftcms** [VivaPayments/API#1112]
I have already installed viva wallet ( registered a demo version ) and enabled it on the Opencart payment system but I need to know how to change the current PayPal button to the vivawallet button

e.g. current button is

<a href="https://www.paypal.com/uk/webapps/mpp/paypal-popup" onclick="javascript:window.open('https://www.paypal.com/uk/webapps/mpp/paypal-popup','WIPaypal'); return false;">.... etc...</a>

cheers

**Comment by VivaWalletSupport** [comment]
Hello, the supported plugin does not have a payment button.
