### ISSUE TITLE
error message after 3DS page on woocommerce

### ISSUE THREAD

**Issue by davidsensiness** [VivaPayments/API#1114]
Hello,
We seem to have multiple problems with the gateway plugins.
1. We have Redirection/Native Checkout v2 checked on our VivaWaller account, and sometimes, clients reports that there is an error message when they try to pay ("An error has occured") on the page just after 3D Secure. I have done the test myself and indeed, from time to time (approximately 1 in 2 times, but it isn't completely regular) There is this message. Most of the times if the client retry the payment process it works afterwards but obviously some of them will not do this again and I would just have lost these clients.
I have noticed that if I go into my Viva account, in websites / apps, click on the website and then just click on the Update button, it seems to make the problem disappear for a couple of hours.
2. I don't know if this is linked to these errors, but when I go into my Orders dashboard in WooCommerce, there are a lot of gaps between the order numbers (see attached screenshot). I manage another WooCommerce store running without Viva (same version of everything otherwise) and all the numbers are incremented normally so that probably comes from the Viva gateway.
We need help in solving out these problems because we can't afford to lose any customer to this kind of errors.

- wordpress version: 5.2.3
- woocommerce version: 3.7.0
- php version 7.2.19
- vivawallet gateway version: 3.5.7

![Order numbers](https://user-images.githubusercontent.com/56072639/66041227-af546e80-e519-11e9-89e0-8dc5b4c81e75.PNG)

**Comment by davidsensiness** [comment]
And I forgot another problem: 
3. The order confirmation email is sent bBEFORE the customer completes the payment.

**Comment by davidsensiness** [comment]
And I forgot another problem:
3. The order confirmation email is sent BEFORE the customer completes the payment.

**Comment by VivaWalletSupport** [comment]
Hello, could you post a screenshot of the error (including the browsers URL)?

**Comment by davidsensiness** [comment]
Yes , I will send it next time / if it happens again. I don't have one at the moment. In the mean time could you check what could be the problem.

Also, what about the confirmation email sent before the customer completes the payment ?

**Comment by VivaWalletSupport** [comment]
The supported plugin does not send an order email, on the moment of redirection to the payment gateway the order should be pending (no order email sent by default WooCommerce). The order email would be generated by WooCommerce when the gateway redirects the customer back to the store and when the order status is updated from pending to processing or complete by the plugin.
