### ISSUE TITLE
Opencart URL? No order details in admin

### ISSUE THREAD

**Issue by barry1001** [VivaPayments/API#1115]
Hi - how to i set up vivawallet with opencart? Orders are in the database but they are not showing in the admin of the site unless I manually change the status in the database.

**Comment by VivaWalletSupport** [comment]
Hello, please provide following screenshots in case you are using the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by matthewrgourd** [comment]
Hi @barry1001, as you've not replied, I'm assuming this is no longer a problem. However, if not, please reopen the issue. Thanks!
