### ISSUE TITLE
Viva wallet declined payment on Shopify

### ISSUE THREAD

**Issue by andbuzz** [VivaPayments/API#1117]
I'm trying to make this plugin to work for 2 days. I've followed every step from viva wallet tutorial, got the merchant id, store token, verified twenty time, added shop in online transactions, waited to become active and still doesn't work, tried with 3 different credit cards, from 3 different PC, payment rejected, try again.

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Could you send me a few screenshots to illustrate the issue. Blank out any personal data before you do so. Thanks!
