### ISSUE TITLE
Redirect Checkout Get Transaction not working

### ISSUE THREAD

**Issue by kikloo** [VivaPayments/API#1119]
Hi,

I am trying to add redirect checkout into my client's website. I am in demo mode and though create order and redirect is working fine, the get transaction is not working and keeps on giving the following message:

---
Checking status for: 1104392415112391
No transactions found. Make sure the order code exists and is created by your account.
---

Why its not returning the data properly ?

Thanks.

**Comment by matthewrgourd** [comment]
Could you let me know the business name and the first 8 digits of the merchant ID. I need to make some checks. Thanks!

**Comment by kikloo** [comment]
Hi,

The details are following:

Business Name: FYL Direct Ltd.
Merchant ID: 16beb1c5

Thanks.

**Comment by matthewrgourd** [comment]
Hi, do you definitely have a demo account set up? If so I can't find it. Perhaps you used a name other than FYL Direct?

**Comment by kikloo** [comment]
Hi,

I am using the demo merchant ID and it is working to generate order code but the same is not working for get transaction. Any idea why ??

Thanks.

**Comment by kikloo** [comment]
Hi,

This is not working with redirect checkout - create order at all:

Business Name: FYL Direct Ltd.
Merchant ID: a27471bd

Error:

---
API Call failed! The error was: Invalid or inactive reseller with id a27471bd
---

Thanks.

**Comment by kikloo** [comment]
Hi,

Please ignore all above and these are the correct details:

Business Name: Tapan Bhanot
Demo Merchant ID: 16beb1c5

Now after entering and configuring all, it gets stuck on 3d secure as attached in screenshot.

![ss](https://user-images.githubusercontent.com/33521529/66549389-cf5ee000-eb60-11e9-9f92-05e43accbf79.jpg)

Please let me know what I have done wrong.

Thanks.

**Comment by afitiskin** [comment]
3d secure error issue reported here #1056

**Comment by matthewrgourd** [comment]
Hi all, our development team has come back with this response:

> We've finished the implementation for the fix and expect it to reach demo environment within the next week. Thank you for your patience

**Comment by matthewrgourd** [comment]
Hi @kikloo our dev team has made some changes behind the scenes meaning that an emulation of 3DS is now available in the demo environment. Please see #1056 (comment) for further info. Hope that solves the issue!

**Comment by kikloo** [comment]
Hi,

The 3dsecure page is now showing but when I am trying to get the transaction to verify I get transaction not found etc.

---
Checking status for: 4975809731200464
No transactions found. Make sure the order code exists and is created by your account.
---

Can you please check why this is not working ?

Thanks.

**Comment by matthewrgourd** [comment]
Hi @kikloo can you send through screenshots of the request / response logs, please?

**Comment by matthewrgourd** [comment]
Hi @kikloo feedback from development team is that you have to create a transaction with the order code in order to retrieve the transaction. The relevant section of the documentation is:

https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-5-make-the-actual-charge



Thanks!
