### ISSUE TITLE
Opencart reward Points

### ISSUE THREAD

**Issue by beesmart1** [VivaPayments/API#112]
Hi

I have a problem with reward points, they not substracted when i place the order   http://prntscr.com/b7rjb5

Could you help?

Regards

**Comment by dpnevmatikos** [comment]
Hi there @beesmart1 
Unfortunately the plugin you're mentioning was not created nor is maintained by Viva Payments, therefore we can't offer any support.
Please try contacting the people that created the discussed plugin.

Regards.
