### ISSUE TITLE
new payment source is pending

### ISSUE THREAD

**Issue by xiaoyao929** [VivaPayments/API#1121]
when I create a new payment source , why it's status is  pending ? 
![image](https://user-images.githubusercontent.com/8858971/66376302-e88d5280-e9e1-11e9-85b5-cd996f7fd5dc.png)

**Comment by matthewrgourd** [comment]
Creating or modifying a payment source will change its status to pending, requiring approval from our team. This is to ensure the payment source meets our security and compliance standards.

**Comment by xiaoyao929** [comment]
How long it would be approved by your team?

**Comment by matthewrgourd** [comment]
A few hours at the most. If there is any delay, please [contact customer services](https://www.vivawallet.com/en-eu/contact-us/).
