### ISSUE TITLE
Viva Wallet Simple Checkout Product Price Added via text field (Is it possible)?

### ISSUE THREAD

**Issue by sdstef** [VivaPayments/API#1122]
Good day!

I am using the Simple Checkout Method (where you set up a custom form with price etc.)
Found here: https://developer.vivawallet.com/online-checkouts/simple-checkout/

My question is: 
Can I have a **text field where someone can add his price** and when they click on the button the price will be the one that the user inputted?

Thank you!

**Comment by matthewrgourd** [comment]
Hi @sdstef as far as I'm aware the option to add custom fields isn't available with Simple Checkout. Apologies for any inconvenience caused.
