### ISSUE TITLE
Payment Processing error

### ISSUE THREAD

**Issue by MrandMsWonder** [VivaPayments/API#1124]
hi, When I am trying to test my Viva Wallet process in my website, it is showing me 404 error with the message '
Oops! That page can’t be found.
It looks like nothing was found at this location. Maybe try one of the links below or a search?

Can you help me? The website is www.mrandmswonder.com

**Comment by VivaWalletSupport** [comment]
Hello, in case you are using the supported plugin, please follow the instructions to the letter:
https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
