### ISSUE TITLE
Redirect payment: how to check if order paid in success callback

### ISSUE THREAD

**Issue by devnullsolutions** [VivaPayments/API#1125]
Hi there! 
I'm working on integration of redirect payment into my application. 
I need to schedule the delivery after successful payment, so I have to be sure that I will not lost my money (e.g. if client dispute the transaction).

So, my main question is: **What is the best and secure way to check if payment order is paid (and transaction is finally cleared and may not be cancelled)?** 

After payment user is redirected to my app, and my success callback is called. I have 2 parameters there: `OrderCode` and `TransactionId`.  So I'm able to get order and transaction, but I'm not sure what exactly I have to check...

SubQuestion 1: Order has parameter `StateId` (Enum: `"0 (Pending)"`, `"1 (Expired)"`, `"2 (Canceled)"`, `"3 (Paid)"`). How and when order statuses change?

SubQuestion 2: Is it safe just to check if order's `StateId` equals to `"3 (Paid)"` to decide that payment was successful and proceed with other stages, e.g. schedule goods delivery to client?

SubQuestion 3: Transaction has parameter `StatusId`(Enum: `"E"`, `"A"`, `"M"`, `"U"`, `"X"`, `"R"`, `"F"`). How and when transaction statuses change? 

SubQuestion 4: Is status `"F (The transaction has been successfully completed)"` final? May user dispute the transaction (and get money back) if transaction reached `"F"` status?

**Comment by devnullsolutions** [comment]
SubQuestion 5: Is transaction guaranteed cleared at the moment when user is redirected to success redirect URL? If not I have to schedule transaction status recheck with some timeout, how much time should I wait?

**Comment by kikloo** [comment]
You have to do a call back to the server using the order code number and it will tell you the status, the following link might shed some light:

https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1transactions~1{Id}/get

**Comment by devnullsolutions** [comment]
@kikloo thanks for the answer! So, in your opinion the answer for my SubQuestion 2 is "Yes", am I right?
One more thing, that I'm trying to figure our: As I know, payment transactions are not instantaneous. Is it possible that user is redirected back to my website (with order code and transaction id) and transaction is not finished yet and order status is not changed yet from pending to paid?

**Comment by xiaoyao929** [comment]
I also has this doubt, which status I can trust to change my order to be paid? order StatusId = '3 (Paid)' or  transaction StatusId = 'F' ?

**Comment by devnullsolutions** [comment]
@matthewrgourd any news here?

**Comment by matthewrgourd** [comment]
@devnullsolutions I'm afraid not but our dev team has advised there will be an update soon.

**Comment by matthewrgourd** [comment]
Hi @devnullsolutions @xiaoyao929, developer feedback is that relevant documentation is here: https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/get . If this doesn't answer your queries please raise individually – with further info if possible!
