### ISSUE TITLE
invalid reseller id

### ISSUE THREAD

**Issue by gabole** [VivaPayments/API#1127]
hellon trying to test the create order using this sample code: https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php

have the following error: API Call failed! The error was: Invalid or inactive reseller with id e256e4dexxxxxxxxxxxxxxxxxxxxxxx

if i base64_encode the credential, i dont have this error any more but dump of resultObj is:
object(stdClass)#1 (1) { ["Message"]=> string(47) "Authorization has been denied for this request." }

any idea ? i've tripled checked my credentials, they are correct

**Comment by matthewrgourd** [comment]
Hi there, could I have your business or account name please? Thanks!

**Comment by matthewrgourd** [comment]
@gabole Are you attempting this in demo or production mode?

**Comment by matthewrgourd** [comment]
Hi @gabole it appears the sample PHP code is incorrect. We will get it updated but in the meantime here's a request example in cURL:

`curl -X POST https://demo.vivapayments.com/api/orders -H 'Authorization: Bearer ZmJmMWUwOTAtNjVkZS00Yzc1LWI1ODAtZDlkOWJjNDk0YWQyOldEdi1WKw==' -H 'Content-Type: application/json' -d '{
    "Tags": [
        "tag 1",
        "tag 2",
        "tag 3"
    ],
    "Email": "customer@domain.com",
    "Phone": "2117604000",
    "FullName": "Customer Name",
    "PaymentTimeOut": 86400,
    "RequestLang": "en-US",
    "MaxInstallments": 12,
    "AllowRecurring": true,
    "IsPreAuth": true,
    "Amount": 1000,
    "MerchantTrns": "Your reference",
    "CustomerTrns": "Description that the customer sees"
}'`

In case it's helpful, here is a link to the Postman collection we've created for the Viva Wallet Payment API where you will find 'Create payment order' in the 'Orders' folder.

<a href="https://app.getpostman.com/run-collection/98329e9b4d990fd46ff8" target="_blank"><img src="https://run.pstmn.io/button.svg"/>
