### ISSUE TITLE
Pending online payment settings (with redirect)

### ISSUE THREAD

**Issue by eranfl** [VivaPayments/API#1128]
Hi,

I modified and created a new website/app on the "online payment" page. Now the status of the 2 settings I created is "pending" for a long period of time. How can I set it to "active"?

Thanks

![image](https://user-images.githubusercontent.com/16452344/66559873-d84eb200-eb5e-11e9-8649-489a9182a596.png)

**Comment by matthewrgourd** [comment]
Hi @eranfl there is normally a wait of a few hours while we verify your payment sources. If this has answered your question, please close the issue.

**Comment by eranfl** [comment]
Hi @matthewrgourd, its been over a day and its still pending.. It holds back my development... Is there any way to speed it up? Thanks

**Comment by eranfl** [comment]
@matthewrgourd It's been over a week now there the sources are still in pending state... What should I do?

**Comment by matthewrgourd** [comment]
Hi @eranfl, not sure what's going on there. Please email mgourd@vivawallet.com with your business name and Merchant ID and I'll look into it. Thanks!

**Comment by devtst** [comment]
I have the same problem. After 5 days the payment sources its still pending.

**Comment by matthewrgourd** [comment]
@eranfl and @devtst Can you try again following the below instructions?

https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/

We're not sure why the payment sources haven't shown in our backend but if you start the process again, they will be made active in less than 2 hours. 

If this doesn't happen for any reason, please call [customer services](https://www.vivawallet.com/en-eu/contact-us/) and they will investigate further.
