### ISSUE TITLE
Disable payment methods on Viva payment page

### ISSUE THREAD

**Issue by kkaravolas** [VivaPayments/API#1129]
Hello,

we are administering a magento 2.2 site which has the viva payment module.
We would like to disable all methods of payment except "Card" when the customer goes to the viva payment page.
How can we do this? 

![image002](https://user-images.githubusercontent.com/850646/66565647-a55eeb00-eb6b-11e9-8cf2-d59949123e77.png)

**Comment by VivaWalletSupport** [comment]
Hello, you would have to edit the code (model) and add any needed optional parameters:
https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Orders

**Comment by kkaravolas** [comment]
Hello,

I have tried adding the parameters in $poststring variable as well as $postargs but the methods still appear.

![image](https://user-images.githubusercontent.com/850646/66634205-42299300-ec15-11e9-85cf-c7f6c0cc0040.png)

**Comment by VivaWalletSupport** [comment]
Use the $postargs string to set optional parameters, set PaymentTimeOut to 300 seconds and use true or false values.

**Comment by kkaravolas** [comment]
Thank you very much it works.
