### ISSUE TITLE
Πηγές Πληρωμών

### ISSUE THREAD

**Issue by icop** [VivaPayments/API#113]
Καλημέρα ,έχω δημιουργήσει περίπου εδώ και ένα μήνα καινούριο source code αλλά ακόμη μου λέει σε εκρεμότητα ενώ σύμφωνα με το σύστημα χρειάζονται δύο με τρεις ημέρες ..

Παρακαλώ πείτε μου τι στοιχεία χρειάζεστε ούτως ώστε να γίνει η επαλήθευση ..

**Comment by dpnevmatikos** [comment]
Καλημέρα @icop ,
Παρακαλούμε στείλτε μας τα στοιχεία του λογαριασμού σας (Α.Φ.Μ ή MerchantId) καθώς επίσης και τον αριθμό του παρόντος github issue στο merchants@vivawallet.com ώστε να προβούμε στις απαραίτητες ενέργειες.

Ευχαριστώ.
