### ISSUE TITLE
Payment Processing Error

### ISSUE THREAD

**Issue by EuphoriaDirect** [VivaPayments/API#1130]
Hi 

Im getting this error page, after the Billing Details page is completed and "Place Order" is clicked.

Server Error

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by VivaWalletSupport** [comment]
Hello, please provide some more details like what ecommerce program / plugin are used.

**Comment by matthewrgourd** [comment]
Hi @EuphoriaDirect, as you've not replied, I'm assuming this is no longer a problem. However, if not, please reopen the issue. Thanks!
