### ISSUE TITLE
Problem with Vivawallet plugin

### ISSUE THREAD

**Issue by geo1985** [VivaPayments/API#1131]
Pop up plugin Vivawallet doesn't working on my Eshop. www.missopera.gr this is the eshop domain name. Can u help? I called the Viva technical support team and they told me to contact u. Can u help?

**Comment by VivaWalletSupport** [comment]
Hello, please provide following screenshots:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by geo1985** [comment]
If u need any more informations contact me asap, i will be online all day.
Thanx.

Στις Παρ, 11 Οκτ 2019 στις 9:49 π.μ., ο/η Tom van der Veer <
notifications@github.com> έγραψε:

**Comment by VivaWalletSupport** [comment]
Hello, please provide following screenshots (post them at Github):

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by geo1985** [comment]
Hi there,
I have sent u 2 days before, what u asked me to. What happened with my
problem, can someone's tell me? Am still waiting.
Thnx.

Στις Παρ, 11 Οκτ 2019, 13:16 ο χρήστης Pantazis George <
geopantazis26@gmail.com> έγραψε:

**Comment by VivaWalletSupport** [comment]
Please check your issue at Github to see the problem.

**Comment by geo1985** [comment]
![Σχόλιο 2019-10-11 130641](https://user-images.githubusercontent.com/56397845/66738669-b06d9000-ee77-11e9-9786-f4c08493d2da.png)
![Σχόλιο 2019-10-11 130641](https://user-images.githubusercontent.com/56397845/66738678-b3688080-ee77-11e9-928f-63807f8f5f34.png)
![Σχόλιο 2019-10-11 130937](https://user-images.githubusercontent.com/56397845/66738704-bcf1e880-ee77-11e9-8262-fdc11ea80de2.png)
![Σχόλιο 2019-10-11 131215](https://user-images.githubusercontent.com/56397845/66738706-be231580-ee77-11e9-918e-20b03f194591.png)
I have sent u again those informations 2 days ago from my gmail, u haven't got them yet?

**Comment by geo1985** [comment]
![Σχόλιο 2019-10-11 130839](https://user-images.githubusercontent.com/56397845/66739243-fbd46e00-ee78-11e9-8eb6-2a07f39c3309.png)

**Comment by VivaWalletSupport** [comment]
Uncheck in the plugin settings the Test mode option (as you seem to use live credentials), correct the return URLs in the payment source (see https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ step 1 - point 5).
