### ISSUE TITLE
Problem translatation on Prestashop

### ISSUE THREAD

**Issue by MichelP74** [VivaPayments/API#1132]
Hello I can't translate module on prestashop 1.7.6.1. I have module vivawallet v1.7.6.
I go to internationnal / translation / module / vivawallet. I go to lign "Pay by Viva" but after le translation not work.
What can i do?

Thank you

Michel

<img width="726" alt="Capture d’écran 2019-10-10 à 16 56 23" src="https://user-images.githubusercontent.com/56402267/66581113-d0ebd080-eb7f-11e9-822f-d4342e9e25f1.png">
<img width="989" alt="Capture d’écran 2019-10-10 à 16 57 36" src="https://user-images.githubusercontent.com/56402267/66581115-d0ebd080-eb7f-11e9-90c4-57096027f304.png">

**Comment by VivaWalletSupport** [comment]
Hello, edit the langauge files that are located in the modules folder and rename every vivawalletlatest wording to vivawallet.

**Comment by MichelP74** [comment]
It's OK for me. Thank you very much !!!!!!
