### ISSUE TITLE
Prestashop 1.7

### ISSUE THREAD

**Issue by drlove39** [VivaPayments/API#1133]
Hello,

What is "source code" in prestashop Module ?

Thanks

**Comment by drlove39** [comment]
I supposed it is 4 digit number.

But i have an error. see attached
![Capture](https://user-images.githubusercontent.com/56402337/66586714-6049b180-eb89-11e9-9a9e-c4e7ac6f17af.JPG)

**Comment by VivaWalletSupport** [comment]
Hello, please provide following screenshots:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by drlove39** [comment]
Thanks for answer.

![Capture03](https://user-images.githubusercontent.com/56402337/66739495-1d315c00-ee71-11e9-90c8-390a9756ac3a.JPG)
![Capture04](https://user-images.githubusercontent.com/56402337/66739496-1d315c00-ee71-11e9-9ded-d6fde5c04743.JPG)
![Capture01](https://user-images.githubusercontent.com/56402337/66739498-1d315c00-ee71-11e9-95c2-ded5db3c3ab6.JPG)
![Capture02](https://user-images.githubusercontent.com/56402337/66739499-1d315c00-ee71-11e9-9c94-88cc217e8869.JPG)

**Comment by VivaWalletSupport** [comment]
Please post again the screenshots, mask only the API Key.

**Comment by drlove39** [comment]
Sorry...
![Capture02](https://user-images.githubusercontent.com/56402337/66748922-c172cd00-ee88-11e9-92a5-9897313a27c6.JPG)
![Capture03](https://user-images.githubusercontent.com/56402337/66748925-c20b6380-ee88-11e9-8a39-65b71987b739.JPG)
![Capture01](https://user-images.githubusercontent.com/56402337/66748926-c20b6380-ee88-11e9-858b-0bab0faaa504.JPG)

**Comment by VivaWalletSupport** [comment]
Thank you, could you try changing your API Key in your Viva account and in the modules settings? Everything else looks correct.

**Comment by drlove39** [comment]
perfect. thanks
