### ISSUE TITLE
wocommerce 3.7

### ISSUE THREAD

**Issue by bonzinho-feup** [VivaPayments/API#1134]
Hello, i have wocommerce 3.7 but after config the plugin, payment option not show in checkout. can u provide old versions or have any aideia how can solve?

**Comment by VivaWalletSupport** [comment]
Hello, please provide following screenshots in case you are using the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by bonzinho-feup** [comment]
Hello thank u 

https://ibb.co/QDnNfXD
https://ibb.co/LxSKNbV
https://ibb.co/RYDPJFY
https://ibb.co/XZtt8fq

**Comment by VivaWalletSupport** [comment]
Configuration looks ok, most likely your currency configuration causes a problem (in case you have no problem with other payment options). 

`function is_valid_for_use()
	{
		if (!in_array( get_woocommerce_currency(), array('GBP', 'BGN', 'RON', 'EUR'))) return false;
		
		return true;
	}`
