### ISSUE TITLE
Redirect issue.

### ISSUE THREAD

**Issue by TIWD** [VivaPayments/API#1135]
Hi

We are using the "Redirect Checkout" method but after successful payment, it's not redirecting to our website success page.

We have setup our website profile and its approved by viva wallet but still its not redirecting to our website page.

We are using asp.net, c# tehcnology. please help.

Thanks
Manoj

**Comment by TIWD** [comment]
Hi 

We are looking forward to your response.

Thanks
Manoj

**Comment by TIWD** [comment]
But I am getting redirection issue in a LIVE version. it's not redirecting once payment successful.

**Comment by dpnevmatikos** [comment]
@Talagozis  can you please try again ? Issue's fixed.

**Comment by TIWD** [comment]
Please reply to our query about redirection.

Thanks

**Comment by HumayunE** [comment]
Hello!
I am also having issue with redirect.
Here is the screenshot for my settings in demo account:
![Screenshot 2019-10-19 at 1 41 28 PM](https://user-images.githubusercontent.com/10536341/67140730-e6938100-f276-11e9-9db6-019ae547fd4f.png)

and this is the response I get after redirection:
![Screenshot 2019-10-19 at 1 44 42 PM](https://user-images.githubusercontent.com/10536341/67140736-fe6b0500-f276-11e9-84e9-278279be295f.png)

So it redirects perfectly on the Failure URL which means it gets all settings right but what makes it fail?
I am using:
£25 amount
Card number: 4111 1111 1111 1111
CVV: 111
Date: 10/2021

Please help!!
Thanks

**Comment by HumayunE** [comment]
Hello!
Please is there any update regarding redirect issue?
I really need to fix it for my client.
Thanks

**Comment by matthewrgourd** [comment]
Hi @HumayunE our dev team has made some changes behind the scenes meaning that an emulation of 3DS is now available in the demo environment. Please see #1056 (comment) for further info. Hope that solves the issue!

**Comment by matthewrgourd** [comment]
Hi @TIWD our dev team has made some changes behind the scenes meaning that an emulation of 3DS is now available in the demo environment. Please see #1056 (comment) for further info. Hope that solves the issue!

**Comment by HumayunE** [comment]
Hi @matthewrgourd I have just tried it and it seems the old problem of redirecting is back.
Now it is not redirecting back to the website again.

See screenshots:
![Screenshot 2019-11-08 at 7 19 01 PM](https://user-images.githubusercontent.com/10536341/68483184-e4f91f80-025c-11ea-94c7-1f4723a9d4b4.png)

![Screenshot 2019-11-08 at 7 19 16 PM](https://user-images.githubusercontent.com/10536341/68483203-ecb8c400-025c-11ea-83d3-abeb1627cc29.png)

After clicking on confirm payment it shows the old message again..
![Screenshot 2019-11-08 at 7 13 33 PM](https://user-images.githubusercontent.com/10536341/68483215-f0e4e180-025c-11ea-9699-9033c56367af.png)

**Comment by HumayunE** [comment]
I also tried with these card details but no luck..

Visa Card : 4860530113481433
Expiry : 12/19
CVV : 123

**Comment by TIWD** [comment]
Hello 

We are facing redirection issue on LIVE.  Its not redirecting to our website.

![image_2019_11_15T09_51_28_390Z](https://user-images.githubusercontent.com/56542179/68934039-f346be80-07bb-11ea-9a93-047d02d16006.png)
Thanks
![image_2019_11_15T09_51_28_390Z](https://user-images.githubusercontent.com/56542179/68934063-fe99ea00-07bb-11ea-8cf8-d20d6d2374a7.png)

**Comment by MadMikeyB** [comment]
Seeing the same issue here.

**Comment by MadMikeyB** [comment]
Sorry to bump - is this a common issue or am I doing something wrong? All URL's set correctly as per docs - just get the same as @TIWD

**Comment by MadMikeyB** [comment]
Any update ???

**Comment by matthewrgourd** [comment]
@MadMikeyB Could you raise a new issue with screenshots? Blur out any confidential information. We need to be able to log each problem separately, even if they're related. Thanks!

**Comment by matthewrgourd** [comment]
Hi @TIWD, sorry for the delayed reply. Could you let me know where you got the success failure URLs from when [setting up the payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/)? I don't recognise them...

**Comment by TIWD** [comment]
We have setup success and failed url as per https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/

But its not redirecting after success. We have setup in LIVE mode.

**Comment by dpnevmatikos** [comment]
Hi @TIWD  
Could you please provide us your merchant Id (the one found in your profile and NOT the api key) as well as the sources' configuration that you've made in the production environment?

**Comment by TIWD** [comment]
Merchant Id : 6fe691f8-41de-47c2-922c-edfff93943da

**Comment by matthewrgourd** [comment]
Hi @TIWD I've checked and you have two sources set up. The one for 'Holidaymasters' has a code of '2771' so I would suspect that his needs to be referred to during setup.

**Comment by TIWD** [comment]
Hi
We had already setup in '2771' code. but still it's not redirecting.

Pleadse advise.

Thanks
Manoj

**Comment by matthewrgourd** [comment]
@TIWD Ok, I will raise with our dev team.

**Comment by matthewrgourd** [comment]
Hi @TIWD, apologies for the delay, our offices were closed over the Christmas / NY period. Can you send me a screenshot of the relevant payment source settings window from your Viva Wallet account? Available at https://members.vivawallet.com/selfcare/en/sources/paymentsources Should look something like the below:

![Screenshot 2020-01-07 at 10 26 17](https://user-images.githubusercontent.com/44943019/71888499-2fe9c300-3138-11ea-9057-da35dac99f3e.png)

**Comment by matthewrgourd** [comment]
Closing as no reply.
