### ISSUE TITLE
Delay to be online payment method in demo account

### ISSUE THREAD

**Issue by knikolou** [VivaPayments/API#1137]
Dear all
I have change urls  to my  website/apps in my demo viva account but there is not have been approved and online since a week now .Is it possible to check why is this delay?
the ids of payment apps are 1074,4812,8435 
Thanks

**Comment by matthewrgourd** [comment]
Please [contact us](https://www.vivawallet.com/en-eu/contact-us/) via customer service and we will look into this for you. Thanks!
