### ISSUE TITLE
Native Checkout Public key issue

### ISSUE THREAD

**Issue by Alexookah** [VivaPayments/API#1138]
Δεν υπάρχει πλεον το public key (δοκιμασμένο με ανώνυμη περιήγηση)

<img width="1427" alt="Screenshot 2019-10-15 at 3 03 35 PM" src="https://user-images.githubusercontent.com/9624843/66830670-b4c0a880-ef5e-11e9-9759-7dc4ede537b6.png">

Δείτε το παραπάνω screenshot. Το Viva Support μου είπαν να φτιάξω github issue  για να το δείτε.

**Comment by matthewrgourd** [comment]
Hi there, you don't need your public API key for [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/). However, if you're talking about [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/), please send me your merchant ID, stating whether it is the demo or production environment you're working in, and I'll enable the correct flag. My email is mgourd@vivawallet.com Thanks!

**Comment by matthewrgourd** [comment]
Should be available now. Let me know if not, otherwise feel free to close the issue!

**Comment by Alexookah** [comment]
yes finally it works.

you should also update the https://developer.vivawallet.com/online-checkouts/generate-your-public-key/
it has old screenshots

**Comment by matthewrgourd** [comment]
@Alexookah Will do – thanks for the feedback!
