### ISSUE TITLE
VivaPayments.cards.requestToken errors

### ISSUE THREAD

**Issue by korgoth** [VivaPayments/API#1139]
Hello, i am trying to integrate this payment system into our platform (not using any of the pre-made plugins). But when i try to execute  VivaPayments.cards.requestToken i can see the browser making a POST request to https://api.vivapayments.com/nativecheckout/v2/chargetokens:skipauth and it gets a 403 Forbidden error (this is with authenticateCardholder set to false - which i need).  
When i try the same request with authenticateCardholder set to true, the browser again initates a POST request this time to https://api.vivapayments.com/nativecheckout/v2/chargetoken, but this time it gets a 400 Bad request error. 

Thats the current code im trying to execute (taken from the documentation):

$(function(){
 VivaPayments.cards.setup({
   authToken:'ACCESS_TOKEN_HERE',
   cardHolderAuthOptions: {
   cardHolderAuthPlaceholderId: 'threed-secure-pane',
   cardHolderAuthInitiated: function() {
   alert('Cardholder authentication started!');
   },
   cardHolderAuthFinished: function() {
   alert('Cardholder authentication has finished');
   }
   }
   });
    
   $('input#submit').click(function(e){
   e.preventDefault();
   VivaPayments.cards.requestToken({
   amount: 100, // amount is in currency's minor unit of measurement
   installments: 1,
   authenticateCardholder: false
   }).done(function (responseData) {
   console.log('eeee');
   console.log(ResponseData);
   console.log(`Here is the charge token: ${responseData.chargeToken}`);
   });
   console.log(VivaPayments.cards);
   });
   });

Any ideas what might be the problem?

**Comment by matthewrgourd** [comment]
I'm going to leave this open as I may be able to get back to you with more info. Please bear with me.

**Comment by matthewrgourd** [comment]
Hi there, I think you may have received an email from you as well, but just in case:

> Apparently the http status code (415) that you're receiving is most probably related to the fact that you're not submitting the request in the proper format (JSON format). Card tokenization works as it should. So we can look into your issue further, please provide us with an export from Postman showing the exact details of the http request.

**Comment by matthewrgourd** [comment]
Closing now as answered via email.

**Comment by haramjan** [comment]
why you don put the answer here as I have facing similar issue. could please provide help in this regard.

**Comment by haramjan** [comment]
Aslo please provide some better sample code so to have better idea

**Comment by matthewrgourd** [comment]
@haramjan please raise a new request with full details of the issue and I'll look into it for you.
