### ISSUE TITLE
Redirect checkout page - Cancel

### ISSUE THREAD

**Issue by nomdev** [VivaPayments/API#114]
Καλησπέρα σας,

στη Redirect checkout page, υπάρχει δυνατότητα "cancel and return to site"? Διότι μόνο "Charge the amount" είναι ορατή.

Ευχαριστώ.

**Comment by defilerc** [comment]
Καλησπέρα @nomdev,

Δεν υπάρχει η επιλογή για cancel στη redirect checkout σελίδα.

Ευχαριστούμε πολύ.
