### ISSUE TITLE
Magento extensión 1.x doubts

### ISSUE THREAD

**Issue by ptazta** [VivaPayments/API#1141]
Hi,

I have installed the extension for Magento 1.x and I have some doubts:

1- when making a purchase never redirects to the specific url I added in sales/online payments/website-apps 

2- I've added our store logo but it still shows the viva wallet logo.

3- When you land on the viva wallet page where you fill in the credit card information is not possible to cancel the purchase and return to the store, is there any option for this?

Thanks

**Comment by VivaWalletSupport** [comment]
Hello, please provide following screenshots:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by ptazta** [comment]
<img width="1271" alt="Captura de pantalla 2019-10-16 a las 10 37 58" src="https://user-images.githubusercontent.com/23451298/66902602-39fc9980-f001-11e9-80f5-e8a925712eb6.png">
<img width="1678" alt="Captura de pantalla 2019-10-16 a las 10 35 25" src="https://user-images.githubusercontent.com/23451298/66902603-39fc9980-f001-11e9-99de-20a324ffab69.png">
<img width="1675" alt="Captura de pantalla 2019-10-16 a las 10 35 58" src="https://user-images.githubusercontent.com/23451298/66902604-39fc9980-f001-11e9-8a76-7444ae5afd1f.png">
<img width="1666" alt="Captura de pantalla 2019-10-16 a las 10 36 30" src="https://user-images.githubusercontent.com/23451298/66902605-39fc9980-f001-11e9-8859-30e374d9bde5.png">

**Comment by VivaWalletSupport** [comment]
Your settings are not correct, please see the setup instructions at https://developer.vivawallet.com/e-commerce-plugins/magento1.x/

**Comment by ptazta** [comment]
Please, can you tell me exactly what's not ok?
Thank you

**Comment by VivaWalletSupport** [comment]
No source code(s) have been specified in the extension settings, in the payment source wrong return URLs are specified, all of this is explained at https://developer.vivawallet.com/e-commerce-plugins/magento1.x/
