### ISSUE TITLE
Demo Account is not activated

### ISSUE THREAD

**Issue by gtsoukasgr** [VivaPayments/API#1142]
Hello , i have make new account in demo.vivawallet.com , i create new on-line payment but is stuck in pending.

Whats is going wrong ?.
my mail account is admin@northcom.gr

**Comment by gtsoukasgr** [comment]
Hello is any body there ? , is been 15 days no answer ?.........

**Comment by ngoun** [comment]
I have the same problem. A couple months ago (before the 3DS) on the demo accounts New Apps/Websites for the DEMO Enviroment were instantly changed status to ACTIVE. Something changed and now seems that no-one attends the demo so new website/apps stay stuck on **Pending** state.
@matthewrgourd  @dpnevmatikos  Can you do something about it?

**Comment by matthewrgourd** [comment]
Hi @gtsoukasgr, @ngoun, please [contact customer service](https://www.vivawallet.com/en-nl/contact-us/) and they should be able to check your acccounts. Thanks.
