### ISSUE TITLE
Module installed on PrestaShop 1.7.5.2 : no come back to webstite, no order in back-office

### ISSUE THREAD

**Issue by PierreB13** [VivaPayments/API#1143]
Hi,
We are web agency. Customer asked install your module Vivawallet v1.7.6.

Payment received on VivaPayment accout, but 2 problems: 

1) Module no come back to webstite after payment
2) no order in back-office and on customer account, no orders/no invoice generated

What must input here : 
- Instalment logic : .... ? (I input nothing)
- Source Code : .... ? (I input nothing)

Maybe problem come from this empty field ?

Thanks you by advance for you help.
Pierre

**Comment by VivaWalletSupport** [comment]
Hello, please follow the setup instructions given at https://developer.vivawallet.com/e-commerce-plugins/prestashop/

**Comment by PierreB13** [comment]
Ok, thanks you.

**Comment by PierreB13** [comment]
Hi,

I done all what I see on https://developer.vivawallet.com/e-commerce-plugins/prestashop/
(hook, etc).
- 2 tests payment with VISA CB : no come back on website and order missed on back-office / customer account.

Please, can you help me ?
Thanks you by advance.
Best regards,
Pierre

**Comment by stennnn** [comment]
Hello Pierre, 

What are the configurations you setup in your prestashop module?
Try copying my details:

Instalment logic
300:3,600:6

Base URL
https://www.vivapayments.com

Merchant ID 
YOUR MERCHANT ID. GET IN API SETTINGS IN VIVAWALLET

API Key
YOUR API KEY

Source Code
The code besides the Website/App name you have created in Online Payments -> Website/Apps

Cheers,
Best regards,
Hugo

**Comment by PierreB13** [comment]
Hi,

Thanks you for yours advices. 

I complete the form of you module, delete cache, recompile force yes/no...

Same ploblem : the money come in vivawallet account BUT in prestashop back-office and in customer account no order no invoice. Nothing.

If you want, I can give you by MP/email the access of back-office and filezilla account. It's became urgent we need to sell.

Thank you y advance.
Best regards,
Pierre

**Comment by VivaWalletSupport** [comment]
Please provide following screenshots:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by stennnn** [comment]
Hello Pierre,

That is strange, mine is working perfectly now. 
If you want, email me at hugofscosta6@gmail.com and I can try to help you out.

Cheers,
Hugo

**Comment by matthewrgourd** [comment]
Hi @PierreB13, please provide screenshots as requested by @vivawalletsupport and we'll be able to look into this further.

**Comment by nicolas8000** [comment]
> Bonjour pierre
> 
> Quelles sont les configurations que vous avez configurées dans votre module prestashop?
> Essayez de copier mes coordonnées:
> 
> Logique des versements
> 300: 3 600: 6
> 
> URL de base
> https://www.vivapayments.com
> 
> Identification du commerçant
> VOTRE ID DE MARCHAND. OBTENIR LES PARAMÈTRES D'API DANS VIVAWALLET
> 
> Clé API
> VOTRE CLÉ API
> 
> Code source
> Le code en plus du nom du site Web / de l'application que vous avez créé dans Paiements en ligne -> Site Web / Applications
> 
> Cheers,
> Cordialement,
> Hugo

Bonjour Hugo

Pouvez vous préciser ce que l'on doit renseigner dans le code source ?
ex : 1111amazon

c'est comme ça ?
