### ISSUE TITLE
3d Secure Issues

### ISSUE THREAD

**Issue by raman3593** [VivaPayments/API#1144]
I am using viva wallet payment module with prestashop 1.7 with demo account (https://demo.vivapayments.com). Previousaly its working good, but now I am getting "3d Secure" message on payment page after inserting card number, CVV and Expiration date. Please suggest me how can we resolve this issue.

**Comment by matthewrgourd** [comment]
Hi there, we've made some changes behind the scenes. Please see https://github.com/VivaPayments/API/issues/1056#issuecomment-548695466 for more info. and let me know if this resolves the issue.
