### ISSUE TITLE
Public Key missing

### ISSUE THREAD

**Issue by Luigital** [VivaPayments/API#1145]
I'm trying to set a Simple Checkout form on my website but on the API Access page there is no Public Key as described on the Developer Portal (https://developer.vivawallet.com/online-checkouts/generate-your-public-key/)

![image](https://user-images.githubusercontent.com/151773/66906110-bb5b2880-f00f-11e9-89ec-a88b751efd50.png)

**Comment by matthewrgourd** [comment]
Hi there, please may I check your settings? If you could send your merchant ID to mgourd@vivawallet.com. Thanks!

**Comment by matthewrgourd** [comment]
Hi there, can you try again? I've changed a setting.

**Comment by kostas1986** [comment]
Hello, same thing to me as well. Any solutions on this?
