### ISSUE TITLE
Προβλημα χρησης καρτας στο demo account 

### ISSUE THREAD

**Issue by acharonitakis** [VivaPayments/API#1146]
Σχετικα με το demo account της lervante ferries και του demo app στο κινητο .

Χρησιμοποιώντας τα παρακάτω settings όταν μπαίνουμε με το demo account στο κινητο έχουμε πρόβλημα μετα την εισαγωγή των στοιχείων της δοκιμαστικής κάρτας …
`<add key="VivaPayments.Live" value="false" />
<add key="VivaPayments.MerchantId" value="da73c68d-83f6-4b58-8678-ddb6fe537fb2" />
<add key="VivaPayments.ApiKey" value="yH.kZk" />
<add key="VivaPayments.PublicKey"  value="NbMyY4D3U7azMEqDlRlyS5Yoz7Cd38UE+chJxi93mCQ=" />
    <add key="VivaPayments.SourceCode" value="4642" />`

**Comment by matthewrgourd** [comment]
Please can I have a bit more information. Are you attempting to test [Native Checkout v2 3DS](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/)?

**Comment by acharonitakis** [comment]
No  , we are not attempting to test the  Native Checkout v2 3DS 
We tried to do some normal tests from the mobile application. 
and when we try to insert the test credit card "No 4111111111111111 CVV 111 Date 02/21" 
and Name "Test T. " 
we get the message "Παρακαλω ελεγξτε ότι τα στοιχεία της κάρτας σας είναι σωστά"

**Comment by acharonitakis** [comment]
kind reminder

**Comment by nikosfa** [comment]
Reminder

**Comment by matthewrgourd** [comment]
Hi there, I believe our mobile API is no longer supported. @dpnevmatikos can you confirm?
