### ISSUE TITLE
Πρόβλημα διασύνδεσης με Shopify

### ISSUE THREAD

**Issue by starkthes** [VivaPayments/API#1147]
Καλησπέρα σας,

Έχω το εξής πρόβλημα με τη διασύνδεση Viva Wallet με το Shopify.

Πατώντας το παρακάτω link
http://www.shopify.com/admin/authorize_gateway/1041324

Προχωράω κανονικά και πατάω "Install payment provider"

![1](https://user-images.githubusercontent.com/56636557/66916366-bacc8d00-f023-11e9-8954-bf04a6d4a3cd.png)

Στη συνέχεια εμφανίζεται το popup 

![2](https://user-images.githubusercontent.com/56636557/66916430-d9cb1f00-f023-11e9-880a-6df57a93035b.png)

Αλλά δεν εμφανίζεται ποτέ το παρακάτω παράθυρο

![3](https://user-images.githubusercontent.com/56636557/66916484-f6ffed80-f023-11e9-8e67-170bb30f63ea.png)

**Comment by matthewrgourd** [comment]
Ok, I believe the *Payment providers* page may have come up instead:

![payment-providers](https://user-images.githubusercontent.com/44943019/66918745-ed708880-f017-11e9-9db2-5a313cc2351c.png)

In which case:

a. Click on the **Add a provider** button to display the *Change provider* dialog box.<br />
b. Select the **Third party credit card provider** radio button then choose **Viva Wallet** from the 'Provider' dropdown.
c. Click on the **Continue** button to display the Viva Wallet payment provider settings.

9. In the **Merchant ID** and **Store Token** fields, enter the relevant details from Viva Wallet (described under [Prerequisites](https://developer.vivawallet.com/e-commerce-plugins/shopify/#prerequisites)) and ensure **Use test mode** is disabled.

10. Click on the **Activate** button and an activation message will be displayed.<br />On the *Payment providers* page, Viva  Wallet is now listed in place of Shopify Payments<br /><br />You should also receive an email from Shopify confirming the change.

11. Go to **Settings > General > Currency** and set the currency of your Shopify store to one of the currencies supported by Viva Wallet:
  - **Euro (EUR)**
  - **British pound (GBP)**
  - **Romanian leu (RON)**

12. Click on the **Save** button.<br />The Shopify integration is now complete.

**Comment by starkthes** [comment]
There is not Add a provider button

![4](https://user-images.githubusercontent.com/56636557/66919940-00d91f00-f02b-11e9-9ce9-0c9814d777a3.png)

**Comment by starkthes** [comment]
There is not "Add a provider" button

![4](https://user-images.githubusercontent.com/56636557/66920068-3ed64300-f02b-11e9-9a36-67bb9402c89d.png)

**Comment by starkthes** [comment]
I found a solution.

I changed the country in settings from Greece to US and finally Viva Wallet appeared. I revert back to Greece and everything is OK. Now i will make tests.

Thank you

**Comment by matthewrgourd** [comment]
Glad to hear it. Closing this ticket now but please do revert back if you need anything :-)
