### ISSUE TITLE
 3d secure issue in Redirect Checkout 

### ISSUE THREAD

**Issue by Shubham3454** [VivaPayments/API#1149]
I am using Redirect Checkout for making payment for that I am using this -
url - https://demo.vivapayments.com/api/orders 
method -post 
request body - {
  "Amount": 1000,
  "SourceCode":2011
}
response- {
    "OrderCode": 4191160495272605,
    "ErrorCode": 0,
    "ErrorText": null,
    "TimeStamp": "2019-10-16T16:21:31.1604952+03:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": true
}
I have already defined "SourceCode":2011 in my profile with redirect pages defined in that 
after that when I enter card details - 4111111111111111 and cvv-111 with valid expire date and email  after that a  pop up comes for 3d secure and after that nothing happens and also no transections are created in that order I used this URL to check it -
url -https://demo.vivapayments.com/api/transactions/?ordercode=4191160495272605
method - get 
 also when I fill up card number it is taking an extra space at the end for , I manually remove that extra space to make it a valid card number
the first 4 digits for my merchant id are - 00e7a1c9 
@viva-payments  @VivaWalletSupport @matthewrgourd

**Comment by Shubham3454** [comment]
I need a quick help as I have already raised an issue in simple checkout in that @matthewrgourd  replied and asked me to use  Redirect Checkout
 here is that issue - https://github.com/VivaPayments/API/issues/1102

**Comment by devnullsolutions** [comment]
You are not alone, your issue duplicates #1056, it describes exactly the same problem

**Comment by Shubham3454** [comment]
@matthewrgourd  @viva-payments  @VivaWalletSupport  @devnullsolutions  any update on this,
 I have just run it again and I am still facing the same issue

**Comment by Shubham3454** [comment]
<img width="526" alt="Screenshot 2019-10-29 at 4 09 13 PM" src="https://user-images.githubusercontent.com/33493304/67760009-836bd080-fa66-11e9-8e59-1b6da6bb5312.png">

I am receiving this screen @matthewrgourd  @viva-payments @VivaWalletSupport @devnullsolutions

**Comment by Shubham3454** [comment]
It would be helpful if you people can schedule a demo with us

**Comment by matthewrgourd** [comment]
Hi @Shubham3454 our dev team has made some changes behind the scenes meaning that an emulation of 3DS is now available in the demo environment. Please see https://github.com/VivaPayments/API/issues/1056#issuecomment-548695466 for further info. Hope that solves the issue!
