### ISSUE TITLE
CreateRecurringTransaction - CancelTransaction 

### ISSUE THREAD

**Issue by aristotelis79** [VivaPayments/API#115]
Καλησπέρα,

Θα μπορούσα να έχω κάποια διευκρίνηση σχετικά με τις παραμέτρους που πρέπει να περάσω στα παρακάτω API.

Για την CancelTransaction στέλνω το παρακάτω uri όπου η πρώτη παράμετρος είναι ο κωδικός συναλλαγής (TransactionId) και η απάντηση είναι "The transaction was not completed because of an error"
http://demo.vivapayments.com/api/transactions/27370284-4fda-421c-905f-437053e6dab7?amount=5960  (DEL)

Ομοίως και για την CreateRecurringTransaction παίρνω την ίδια απάντηση
http://demo.vivapayments.com/api/transactions/27370284-4fda-421c-905f-437053e6dab7  (POST)

Ευχαριστώ

**Comment by defilerc** [comment]
Καλησπέρα @aristotelis79,

Ο συγκεκριμένος merchant που προσπαθεί να κάνει cancel το transaction δεν έχει δικαίωμα για refund συναλλαγών.

Θα πρέπει να μπεις στο profile του εμπόρου (Ρυθμίσεις -> Πρόσβαση ΑPI) και να ενεργοποιήσεις την επιλογή "Επιτρέπονται refunds" κάτω από την κατηγορία "Ρυθμίσεις ασφαλείας API".

Ευχαριστούμε!

**Comment by aristotelis79** [comment]
Ευχαριστώ @defilerc, 

θα το δοκιμάσω και θα σου πω

**Comment by aristotelis79** [comment]
Καλησπέρα @defilerc,

Μετά την ρύθμιση η CancelTransaction έπαιξε αλλά με την CreateRecurringTransaction συνεχίζω να παίρνω το ίδιο json
{
  "Emv": null,
  "Amount": null,
  "StatusId": "E",
  "TransactionId": null,
  "ReferenceNumber": null,
  "RemainingRefunds": null,
  "AuthorizationId": null,
  "ErrorCode": 400,
  "ErrorText": null,
  "TimeStamp": "2016-06-01T12:32:01.7485291+03:00"
}

**Comment by defilerc** [comment]
Καλησπέρα @aristotelis79

Η κλήση για τη δημιουργία transaction χρειάζεται υποχρεωτικά και το πεδίο Amount, το οποίο καθορίζει το ποσό της πληρωμής. Απ' ότι βλέπω στην κλήση που γίνεται, απουσιάζει από τις παραμέτρους.

Μπορείς να ξαναδοκιμάζεις, ορίζοντας κάποιο συγκεκριμένο amount;

Αν αποτύχει και πάλι, μπορείς να μας στείλεις το ακριβές request που κάνεις, καθώς και το error το οποίο λαμβάνεις, ώστε να το διερευνήσουμε περαιτέρω.

Σ' ευχαριστούμε πολύ!

**Comment by aristotelis79** [comment]
Καλησπέρα @defilerc,

Δυστυχώς το είχα το δοκιμάσει και εγώ με το amount αλλά δεν έπαιξε. Τα request που του κάνω είναι 

http://demo.vivapayments.com/api/transactions/03a85cce-b83b-4f3a-86ec-322298190946
και
http://demo.vivapayments.com/api/transactions/03a85cce-b83b-4f3a-86ec-322298190946?amount=5960
με POST.
Tο αποτέλεσμα και των δυο είναι  
{
  "Emv": null,
  "Amount": null,
  "StatusId": "E",
  "TransactionId": null,
  "ReferenceNumber": null,
  "RemainingRefunds": null,
  "AuthorizationId": null,
  "ErrorCode": 400,
  "ErrorText": null,
  "TimeStamp": "2016-06-02T18:48:37.5535878+03:00"
}

Υ.Γ. H πρώτη παράμετρος είναι η TransactionId.

**Comment by defilerc** [comment]
Καλησπέρα @aristotelis79 

Τα parameters όπως το Amount, θα πρέπει να περαστούν στο body του HTTP Request και όχι σαν url parameters. Μπορείς να δεις τα code examples που υπάρχουν στο:

https://github.com/VivaPayments/API/tree/master/CreateOrder

για παραδείγματα σε διάφορες γλώσσες.

Στη διάθεσή σου για οποιαδήποτε διευκρίνηση.

**Comment by aristotelis79** [comment]
Καλησπέρα @defilerc,

Όλα οκ. αυτό ήταν έπαιξε. 

Ευχαριστώ.
