### ISSUE TITLE
Woocommerce vivawallet plugin, demo payment returns fail

### ISSUE THREAD

**Issue by dimitriadisg** [VivaPayments/API#1150]
I have integrated the vivawallet payment gateway into my client's woocommerce eshop, by following the instructions found [here](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/).

I am using the demo subdomain and the test mode in the site. The Source is marked as Active and the connection seems to be established. However, when I proceed to checkout and fill in the data bellow into the [vivapayments gateway](demo.vivapayments.com/web/newtransaction.aspx?Ref=9953348628172607), I'm getting a failed response:

Name: Bob White
Card: 1111111111111111
CVV: 2222
Expiry: 09/2031
Payment code: 9953348628172607
Charge: 0.10 Euro

The redirect response is: https://www.myclientsitedomain.gr/index.php?wc-api=wc_vivawallet&vivawallet=fail&s=9953348628172607&lang=el-GR&eventId=0

I have tried to fill in real data too, but the response is still the same. I need your assistance to solve this issue. Why is the payment gateway redirecting with fail response, even with real card data ?

**Comment by dimitriadisg** [comment]
Updating my issue: The payment gateway returns a success when the price is higher. For a price of 0.10 Euro I am getting the above error.

Could you inform me on the minimum valid amount required for this payment method to work ?

**Comment by matthewrgourd** [comment]
Hi @dimitriadisg the minimum is 0.30 Euro.
