### ISSUE TITLE
Multiple buttons on Simple Checkout

### ISSUE THREAD

**Issue by Luigital** [VivaPayments/API#1152]
Is it possible to add several buttons on page using Simple Checkout?
I already tried adding two buttons on the same form and separate forms for each button but neither approach worked.

Thanks!

**Comment by Luigital** [comment]
Would it be possible to have an answer on that because it's extremely urgent?

Thanks.

**Comment by dpnevmatikos** [comment]
Hi @Luigital  
Sorry but there can't be multiple Simple Checkout buttons on the same page.

Sorry :(
