### ISSUE TITLE
Redirection to success page on magento 1.9

### ISSUE THREAD

**Issue by ptazta** [VivaPayments/API#1154]
Hello, I have installed the extension for magento 1.9, I have two languages. When you make a payment via Viva Wallet, the payment is done correctly, I have added the url of redirection so that it returns to the web once made the payment, but I would like that it could return to the page of confirmation of order instead of to the home page.

It happens that some parameters are needed to get to that page.

Is this possible? 

Thank you

**Comment by VivaWalletSupport** [comment]
Hello, in case you use the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/magento1.x/ and follow the setup instructions given on that page, it should work exactly as you need it.

**Comment by ptazta** [comment]
Hello, 
![Captura de pantalla 2019-10-18 a las 10 36 00](https://user-images.githubusercontent.com/23451298/67079948-701e5280-f194-11e9-9993-35634d654313.png)
<img width="1663" alt="Captura de pantalla 2019-10-18 a las 10 43 50" src="https://user-images.githubusercontent.com/23451298/67079950-701e5280-f194-11e9-9679-d07f241e1db0.png">

I have reviewed everything and have it as indicated in the extension documentation.

Attached is a snapshot of the configuration in: Online payments/Websites-apps and another one of the error when returning to the page once the payment has been made correctly.

Please tell me what's wrong.

Thank you.

**Comment by VivaWalletSupport** [comment]
For your English store you should use the language parameter in the return URLs like en/vivawallet/hpay/hpok/ and en/vivawallet/hpay/hpnok/

**Comment by ptazta** [comment]
Ok, but what happens then if a purchase is made in the Spanish version?

What urls do I have to put in the configuration?

**Comment by VivaWalletSupport** [comment]
You would create another payment source for Spanish using the return URLs es/vivawallet/hpay/hpok/ and es/vivawallet/hpay/hpnok/

**Comment by ptazta** [comment]
yeah!! now its ok!! thanks.
