### ISSUE TITLE
New Webhook

### ISSUE THREAD

**Issue by Caledonianhemp** [VivaPayments/API#1156]
I'm trying to create a New Webhook as I believe that is the final thing I'm needing to do to make my Woocommerce checkout work.

Each time I enter the URL 'https://www.caledonianhemp.com/index.php?wc-api=wc_vivawallet&vivawallet=webhook' and set Event Type to Transaction Payment Created as shown in the installation guide I get the error 'Error! The url could not be verified. Please make sure you have entered a valid, publicly available, url that conforms to these guidelines (Error code 502)'

Any idea how to fix this?

**Comment by VivaWalletSupport** [comment]
Hello, the rest of the integration is working correctly (success / fail transactions / correct order status update)?

**Comment by Caledonianhemp** [comment]
No, the order is left at Pending Payment, even though the Wallet is showing the payment has been succesful.

After payment it then redirects to https://www.caledonianhemp.com/index.php?wc-api=wc_vivawallet&vivawallet=fail&t=87b12e57-c3c5-45ec-9652-05fcfe80b6a9&s=3525424754048547&lang=en-US&eventId=10005&eci=2 and shows a blank screen showing -1

**Comment by Caledonianhemp** [comment]
![API Access](https://user-images.githubusercontent.com/56803773/67192327-4ca11500-f3eb-11e9-8668-ff38dcb863fd.png)
![Payment Source](https://user-images.githubusercontent.com/56803773/67192328-4ca11500-f3eb-11e9-81bf-803a64e44d82.png)
![Settings](https://user-images.githubusercontent.com/56803773/67192329-4d39ab80-f3eb-11e9-8e08-70cfc073f03b.png)
![WebsiteApps](https://user-images.githubusercontent.com/56803773/67192330-4d39ab80-f3eb-11e9-9306-45fce063412d.png)

**Comment by Caledonianhemp** [comment]
I went ahead and installed that plugin and can confirm successful payment, woo!

Thank you for your help.

**Comment by VivaWalletSupport** [comment]
See you are using a 3rd party payment plugin and the instructions for the supported plugin, that will not work. Remove that plugin and use the one from https://developer.vivawallet.com/e-commerce-plugins/woocommerce or follow the instructions from the 3rd party plugin.
