### ISSUE TITLE
Accept credit card on my second website

### ISSUE THREAD

**Issue by Jules3434** [VivaPayments/API#1158]
Hello,

I'm using Vivawallet since few month for my main website on wordpress.

Now I created a new website on BigCommerce.
I would like to know if I can start to accept credit card by Viva on this new website using my same Viva account. (with other words can i have 2 websites who works with the same viva account)

If yes, implement the viva checkout seems to be more complicated with BigCommerce. Could you help me with that?

Best regards,

**Comment by matthewrgourd** [comment]
Hi there, unfortunately we don't currently have available a Viva Wallet plugin for use with BigCommerce so you'd need to do a custom integration via our API. The gateways available for use with BigCommerce are listed on this page: https://support.bigcommerce.com/s/article/Available-Payment-Gateways
