### ISSUE TITLE
Migrating to Native Checkout v2 CORS Error

### ISSUE THREAD

**Issue by aiosifelis** [VivaPayments/API#1159]
Καλησπέρα. Ακολουθώντας τις [οδηγίες](https://developer.vivawallet.com/online-checkouts/migrating-from-native-checkout-v1/) για το migration απο native checkout v1 σε v2 , προσπαθώ να στήσω/δοκιμάσω τοπικά το native checkout v2, στον τοπικό μου Η/Υ και η μέθοδος requestToken γυρίζει με ένα σφάλμα για το CORS.

![image](https://user-images.githubusercontent.com/36890905/67254602-dbde1500-f44b-11e9-8537-4557c3ed70d0.png)

![image](https://user-images.githubusercontent.com/36890905/67254489-4f335700-f44b-11e9-801a-a71644fa2634.png)

Έχω υλοποιήσει το v1 εδώ και ένα χρόνο περίπου χωρίς κάποιο παρόμοιο error.

**Comment by matthewrgourd** [comment]
Does this article on CORS help at all? https://medium.com/@xinganwang/a-practical-guide-to-cors-51e8fd329a1f

**Comment by aiosifelis** [comment]
Thank you, this is very useful.
Have you added the appropriate headers in your API as the article suggests?
![image](https://user-images.githubusercontent.com/36890905/67999540-283b0900-fc33-11e9-91a3-c67fec498e15.png)

**Comment by aiosifelis** [comment]
I don't understand why you closed the issue.

**Comment by matthewrgourd** [comment]
Ah, sorry, thought you were able to continue now but obviously not. No, we do not have those headers but the article was intended as a general guide to CORS. If you're still having issue please check previous issues raised on the same subject in this forum: https://github.com/VivaPayments/API/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+cors+

**Comment by aiosifelis** [comment]
Thanks for your reply. I'm going to have to test it again since it has been a couple of weeks and if I get to the same conclusion I will post again to this issue.

**Comment by aiosifelis** [comment]
I have tested it again by implementing from the beginning the native checkout v2 as it is described in the developers section. So far no CORS error has occurred. Probably my mistake was that I followed the migration instructions which muddied the waters a little bit. I'm going to open a separate issue if something comes along. 
Thank you.
