### ISSUE TITLE
Redirect payment

### ISSUE THREAD

**Issue by eranfl** [VivaPayments/API#1161]
Hi,

I implemented the redirect payment method according to https://developer.vivawallet.com/online-checkouts/redirect-checkout/
(using the demo environment).

I created order and after redirected to the checkout page, I used the following credit card info:
* Card number: 4111111111111111
* CVV: 111

But the payment always redirects to the "failed" page and no transaction created.

Note:
I set the "AuthenticateCardholder" attribute to "false" to prevent the card authentication as suggested in another issue.

There is a reason why the payment always fails? How can I test the entire flow using the demo environment?

Thanks

**Comment by matthewrgourd** [comment]
Hi @eranfl our dev team has made some changes behind the scenes meaning that an emulation of 3DS is now available in the demo environment. Please see https://github.com/VivaPayments/API/issues/1056#issuecomment-548695466 for further info. Hope that solves the issue!
