### ISSUE TITLE
προβλημα login στο demo account

### ISSUE THREAD

**Issue by evandoulas** [VivaPayments/API#1162]
sto demo account μας με στοιχεία 
demo account : http://demo.vivapayments.com/ 
u:6934611628

Μετά το Login λαμβάνουμε error
![image](https://user-images.githubusercontent.com/43986375/67288914-6a9f7000-f4e6-11e9-9cd3-4326b5681c15.png)

Μπορείτε παρακαλώ να το δείτε και να μας βοηθήσετε?

**Comment by dpnevmatikos** [comment]
Ηι @evandoulas  
Could you try resetting your password and try again?

**Comment by evandoulas** [comment]
We cannot
(the email on this account is no longer valid in our company)
Could you replace it with mine (evandoulas@newsphone.gr<mailto:evandoulas@newsphone.gr>) ?

Or do you have another way to help us retrieve this account?

**Comment by evandoulas** [comment]
παρακαλώ μπορείτε να μας βοηθήσετε με αυτό.
δεν μπορούμε επίσης να δημιουργήσουμε νέο demo account δεν βλέπουμε τρόπο να βρούμε
public key  και source code, που χρησιμοποιεί η εφαρμογή μας

**Comment by matthewrgourd** [comment]
Hi there, I can't recreate the issue you mention about not being able to create a demo account. Is this still a problem? If not, please close this ticket. Thanks!

**Comment by evandoulas** [comment]
Please let me re-explain the situation.
1. We have an old demo account where we cannot change password as  the email that created is no longer active.
2. If we go ahead and create a NEW demo account from scratch, we can achieve that. But in this case, we cannot find "public key και source code" which are 2 parameters, that our application is still using in the production mode and so we need to have the same implementation in the staging/demo environment.

Could you please advice on those?

**Comment by matthewrgourd** [comment]
Hi @evandoulas please create a new demo account, send me the associated Merchant ID (referencing this issue) and I'll make sure those parameters are enabled for you.

**Comment by evandoulas** [comment]
Merchant ID : 337988205142

**Comment by matthewrgourd** [comment]
Hi @evandoulas I'm afraid that isn't your Merchant ID. Please check [this page](https://developer.vivawallet.com/e-commerce-plugins/merchant-id/) on our developer portal for info on how to find it.

**Comment by evandoulas** [comment]
Apologize, and I am resending :
02d4db03-c4d8-48f3-b6b3-b151843cf932

[cid:image001.png@01D59FC3.F4F89AB0]

**Comment by matthewrgourd** [comment]
Hi @evandoulas can you try again? I've changed some of your settings.

**Comment by evandoulas** [comment]
Source Code ?
