### ISSUE TITLE
Redirection mode shows credit card fields in website as well

### ISSUE THREAD

**Issue by billmis** [VivaPayments/API#1163]
Hi guys. I have an urgent problem. I use viva redirection on Magento 1 for a couple of months without any problem. Suddenly we realize (after many succesful redirections etc) that when a customer selects to pay with viva redirection a new box appears to enter the card details (as native checkout) inside the onepage checkout page (see screenshot - we are using Magento1). I try with my own card to check, and the functionality of importing those details on my website was useless as after i press complete order i re-directed normally to viva checkout and i need to re-enter the card details. But the most important, is when my bank informed me that my card has been stolen and someone try to make transactions from the usa and uk. I use this card for years, and i cannot connect with anything else my stolen data. Meanwhile i delete all the files from magento 1 extension and re-upload them just to ensure that all the files are correct and unattached. Still this drop-down appears every time i select this method. Could you please help? 
![Untitled-6](https://user-images.githubusercontent.com/47184297/67308470-d42d7780-f502-11e9-9ae4-476020a9ecb5.jpg)

**Comment by VivaWalletSupport** [comment]
Hello, it is a popular way of hacking to obtain credit card information. The fields are not part of the payment extension. Clean your site, take appropriate measures to secure your website and inform you customers. https://www.getastra.com/blog/911/fake-payment-method-added-in-magento/
