### ISSUE TITLE
Αφαιρεση δυνατότητας δόσεων απο plugin magento 1.X

### ISSUE THREAD

**Issue by kelekis** [VivaPayments/API#1164]
Πώς μπορώ να αφαιρέσω τη δυνατότητα αφοράς με δόσεις απο το Plugin για Magento 1.x για το viva wallet?

**Comment by VivaWalletSupport** [comment]
Hello, you would have to leave the configuration field for instalments empty to disable the feature.

**Comment by kelekis** [comment]
yes for fast answer . Where is the configuration field for instalments ?

**Comment by kelekis** [comment]
ok i find it . thanks 
something else how could put the payment pending and if confirm from me to be process after?

**Comment by kelekis** [comment]
and also if we can put more than one eshop in the viva account and how this is separate ?

**Comment by VivaWalletSupport** [comment]
Pending should be no problem, for multiple stores create multiple payment sources in our Viva account.
