### ISSUE TITLE
bodyandmindbotanicals.com unable to take payments

### ISSUE THREAD

**Issue by 07447908555** [VivaPayments/API#1165]
Hi, 
Our website is currently unable to take payment for orders.  When clicking to complete the order, it bounces back to the checkout page.
Please confirm what the issue is?
Thanks
Martin

**Comment by VivaWalletSupport** [comment]
Hello, in case you are using the plugi and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ please provide following screenshots:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by 07447908555** [comment]
Hello,

Hopefully, all of the screenshots are correct as per below:

Thanks
Martin

**Comment by VivaWalletSupport** [comment]
Hello, please post your screenshots at Github to be visible.

**Comment by 07447908555** [comment]
Hello,

The issue is resolved.

Thanks

Martin Kaprockyj
Chief Operations Officer
Cannovation Group


On 24 Oct 2019, at 06:53, Tom van der Veer <notifications@github.com> wrote:

﻿

Hello, please post your screenshots at Github to be visible.

**Comment by VivaWalletSupport** [comment]
@foshdafosh I do not see this problem in your store, it redirects normally to the payment page from Viva. Please open a new ticket with detailed information about the problem you are experiencing.
