### ISSUE TITLE
Issue about online payment platform

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1166]
Hi team,

Can you help me about this problem for the customer, I transcribe words: 

As a comment by phone I have a question regarding the payment gateway in form redirection mode.
The request is good and valid, but the answer (my confirmation that a payment was made OK) I do not see it so well given that I have no way of knowing if the answer to my server really from you ... I put myself in a situation :
Upon receiving the following call: https://www.micomercio.com/pay/checkout/result?t=71477d3c-70ef-4ac4-ba9d-4e5f71e8a055&s=7733673280991548&lang=en-US&eventId=0&eci=2 I understand that the order 7733673280991548 resulted , because it responds to me with eventid = 0 and returns the analysis code t = 71477d3c-70ef-4ac4-ba9d-4e5f71e8a055. So far perfect.
The problem comes because imagine that someone a little shaky "out there" captures the calls and observes these answers. The "user" may initiate a payment, but instead of paying, if you paste that same request in your browser, I will get something that seems valid, therefore, what will be valid and what the product will deliver to the customer In a few hours.
One of the possibilities that I observed is obtaining the IP of origin of the request, but I observed that the IP that reaches me to the server is that of the user, not that of your server.
Please help me by looking to see if there is any method to guarantee this particular

**Comment by matthewrgourd** [comment]
Are you using one of our [e-commerce plugins](https://developer.vivawallet.com/e-commerce-plugins/)? Please send through a little more information.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada please assure your customers that all payments through the Viva Wallet platform are safe and secure. We are a licenced e-money institution authorised by the Financial Conduct Authority. Thanks!
