### ISSUE TITLE
WooCommerce Shop unable to take payments

### ISSUE THREAD

**Issue by foshdafosh** [VivaPayments/API#1167]
We're currently unable to take payments on our WooCommerce store (cannadoxshop.com).
As per the Error screenshot below, customers simply see "An error occured, please try again." after entering card details etc, and are returned to the Checkout screen.

Error:
![Error](https://user-images.githubusercontent.com/7311481/67475582-60988100-f64e-11e9-9d4a-4e85a9684734.png)

Payment Module Settings:
![Payment Module Settings](https://user-images.githubusercontent.com/7311481/67475599-68582580-f64e-11e9-90eb-4e02b459066f.png)

Viva Wallet Websites Apps page:
![Viva Wallet Websites Apps page](https://user-images.githubusercontent.com/7311481/67475600-68582580-f64e-11e9-9cea-aca0512614a8.png)

API Access page:
![API Access page](https://user-images.githubusercontent.com/7311481/67475601-68582580-f64e-11e9-90d3-9024af48843a.png)

**Comment by VivaWalletSupport** [comment]
Please try another card or setup the plugin with the demo environment and use the test card to verify the correct working.

**Comment by foshdafosh** [comment]
We tested this with purchases using three cards belonging to different staff members, prior to raising this issue.
There's also the customers who haven't been able to purchase anything either.

One change from earlier that might be interesting, is that the Webhook was verifying perfectly earlier today, but is failing verification while creating a demo account. I've just tested the production verification, and that's failing too (see screenshot at the bottom).

I've created a demo account, but without a webhook. I've changed the details in WooCommerce to match the demo account details.
This doesn't work either with or without the test mode box ticked.

![Failed Verification](https://user-images.githubusercontent.com/7311481/67498160-e7615400-f676-11e9-8d56-28b20dae4640.png)

**Comment by VivaWalletSupport** [comment]
Please configure the setup for the demo mode and check the test mode option in the plugin settings.

**Comment by foshdafosh** [comment]
As I mentioned in my previous message, this doesn't work either with or without the test mode box ticked.

So I have tried with Test Mode checked, and I get the exact same message as the live error.
If Test Mode is unchecked, I get the 404 error caused by incorrect details.

**Comment by VivaWalletSupport** [comment]
In case you want me to have a look at the problem, please do as instructed. Make sure any 3rd party Viva plugins are removed from your installation.

**Comment by foshdafosh** [comment]
Understood, I've set the payments to Demo mode, so you can test it out and see the problem yourself if you like.
I can confirm that there are no 3rd party VivaWallet plugins in the installation.

**Comment by VivaWalletSupport** [comment]
Please correct the success / fail URLs (to include shop) in your payment source like:

shop/index.php?wc-api=wc_vivawallet&vivawallet=success
shop/index.php?wc-api=wc_vivawallet&vivawallet=fail

Let me know if that fixed the problem.

**Comment by foshdafosh** [comment]
I've copied those lines into my demo account, but my test purchase produced the same error as before I'm afraid.

**Comment by VivaWalletSupport** [comment]
Try card 4016000000040000012 cvc 111 exp 01/20
http://prntscr.com/pnvqp1

**Comment by foshdafosh** [comment]
That worked!

Shall I change the Live payments to use these URLs and make a real test purchase?
shop/index.php?wc-api=wc_vivawallet&vivawallet=success
shop/index.php?wc-api=wc_vivawallet&vivawallet=fail

Or am I skipping a step?

**Comment by VivaWalletSupport** [comment]
Yes, please do so and use the correct URLs. To test a payment in live mode, make sure the order value is above 30 p/cents.

**Comment by VivaWalletSupport** [comment]
No clue here, but  as your store uses "shop" in the path, it also should be added to the return URLs in the payment source.

**Comment by foshdafosh** [comment]
Good to know, thanks again for your help.
