### ISSUE TITLE
Simple check out demo κάρτα δεν λειτουργεί

### ISSUE THREAD

**Issue by nikosfa** [VivaPayments/API#1168]
Καλησπέρα σας, 

Το simple check out δεν λειτουργεί με τις demo κάρτες εδώ και πολλές εβδομάδες τώρα.

Μήπως υπάρχει κάποιο προτεινόμενο workaround από την Viva Wallet προκειμένου να μπορούμε να εξυπηρετήσουμε τους πελάτες μας ή κάποια ημερομηνία bug fix ;

**Comment by matthewrgourd** [comment]
Hi there, which demo card(s) have you tried and what errors are you receiving?

**Comment by matthewrgourd** [comment]
Closing as no reply. Please reopen if you are still experiencing issues.
