### ISSUE TITLE
Viva Wallet (Payment Failed)

### ISSUE THREAD

**Issue by EuroStreet** [VivaPayments/API#1169]
Perasa  to  Vivawallet sto Opencard website mou, exw vali ola ta credentials,
Alla otan paw na plirosw apo to website, afou v alw thn karta  mou vgazei (Payment Failed)
Dokimasa me 2 diafwretikes kartes,  to shop mou sta sales> einai Active. 
Exw to plugin  open card 2.3

**Comment by EuroStreet** [comment]
![image](https://user-images.githubusercontent.com/56961296/67480056-eecd3100-f667-11e9-828b-1e4227067c60.png)
Vgazei, kai auto edw prin pah sto page me  to payment failed.

**Comment by matthewrgourd** [comment]
Hi @EuroStreet our dev team has made some changes behind the scenes meaning that an emulation of 3DS is now available in the demo environment. Please see https://github.com/VivaPayments/API/issues/1056#issuecomment-548695466 for further info. Hope that solves the issue!

**Comment by EuroStreet** [comment]
My problem's not in Demo, i haven't try the Demo version, also I don't want
to try it.
My problem appears in the LIVE version.
I've installed the 2.3.2 plugin for the Viva Wallet as instructed and added
all my details, but when i go to pay the 3D images are broken, and payment
just keeps saying failed.
