### ISSUE TITLE
Integration with OpenCart 3.0 Error - cannot get payments

### ISSUE THREAD

**Issue by DekosportsUKLtd** [VivaPayments/API#1170]
We cannot integrate OpenCart 3.0 with Viva Wallet. We followed all adviced steps but, still receiving an error:

![image](https://user-images.githubusercontent.com/56964637/67486616-48336100-f664-11e9-9764-e9d6ada66982.png)

Please advice asap.

Regards
Deko Sports UK Ltd

**Comment by VivaWalletSupport** [comment]
Hello, in case you use the plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/opencart3/ please provide following screenshots:

Payment extension settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by nickthesail0r** [comment]
i have found an error in vivawallet plugin on opencart 3.0 you should change #payment to payment_method on /catalog/view/theme/default/template/extension/payment/vivawallet.twig on line 1 and on line 7

**Comment by VivaWalletSupport** [comment]
@Nickthesail0r as the id of the form is `payment`, using `payment_method` to trigger the form submission seems not logic.

**Comment by nickthesail0r** [comment]
with that id #payment it did not trigger the submission for me because opencart recalls the payment_method id

**Comment by VivaWalletSupport** [comment]
I cannot replicate the issue your mention. In case there is a conflict with another payment method, you might rename the form id to `vivapayment` and the trigger to `#vivapayment`.

**Comment by nickthesail0r** [comment]
check the response and the request. opencart is calling payment_method by default in complete order button.Many sites have the Cash on delivery plugin or pick from store even other payment methods so maybe this makes the conflict.
