### ISSUE TITLE
I don't see Simple Checkout API Key

### ISSUE THREAD

**Issue by fabiosicilia86** [VivaPayments/API#1171]
Hi,
i have created two accounts in viva wallet: one is in demo and the other is in live.
The problem is that there is not Simple Checkout API key and so i can't receive payments...
what is the reason? thanks for help!

**Comment by matthewrgourd** [comment]
Hi there if you could send your Merchant IDs (demo and production) to mgourd@vivawallet.com, I'll check your account(s).

**Comment by matthewrgourd** [comment]
Hi @fabiosicilia86 I'm closing this now. I believe you may have emailed me. If not, please email mgourd@vivawallet.com and I'll enable your API key. Thanks!

**Comment by fabiosicilia86** [comment]
ok

Il giorno lun 11 nov 2019 alle ore 14:49 matthewrgourd <
notifications@github.com> ha scritto:
