### ISSUE TITLE
Error API

### ISSUE THREAD

**Issue by fabiosicilia86** [VivaPayments/API#1172]
Hi,
i create a button for payment using the follow code:

```
<html>
    <head>
        <title>Simple Checkout</title>
    </head>
    <body>
      <form id="myform" action="/viva-wallet/checkout.php" method="post">
        <button type="button"
          data-vp-publickey="ShGehyZBNMrqNS0QWdBu9wYfGwWc1ICwwZOD2AXtQFA="
          data-vp-baseurl="https://www.vivapayments.com"
          data-vp-lang="en"
          data-vp-amount="3000"
          data-vp-description="My product">
        </button>
      </form>

      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
 <script src="https://www.vivapayments.com/web/checkout/js"></script>
</html>
```

The payment form appear correctly but i am not able to do the payment:
when i use the card the payment seem going correctly but in dashboard i don't see payments...
when i use the vivawallet payment at the end the button becomes red and i am not able to do the payment.
What should i do? What is the reason?
Thanks for help

**Comment by matthewrgourd** [comment]
Hi @fabiosicilia86 sorry to hear you're experiencing issues. Can I just check, did you copy the public key from your account area? https://developer.vivawallet.com/online-checkouts/find-your-public-api-key/

**Comment by matthewrgourd** [comment]
Closing as no reply. If you're still experiencing an issue, please reopen and send through further details. Thanks!
