### ISSUE TITLE
Woo Commerce Checkout "Wrong Merchant crendentials or API unavailable"

### ISSUE THREAD

**Issue by human-cbd** [VivaPayments/API#1174]
Hello,
During the final payment phase, after clicking pay with vivawallet and an infinite load time, an error message appears: Wrong Merchant crendentials or API unavailable.

I recovered the API directly to my account by following the tutorial about it.

**Comment by human-cbd** [comment]
I looked at the other posts about my problem and I noticed that I did not have the right plugin .. I downloaded the good but now in LIVE mode the loading time never ends and in TEST mode I fall on a 404 error ...

**Comment by human-cbd** [comment]
![image](https://user-images.githubusercontent.com/56971117/67577277-71292400-f740-11e9-94ba-9cd6ecf0b8c0.png)
![image](https://user-images.githubusercontent.com/56971117/67577342-95850080-f740-11e9-81a5-345a188402ed.png)
![image](https://user-images.githubusercontent.com/56971117/67577378-a6ce0d00-f740-11e9-9cd9-5e2f5f3b2257.png)

**Comment by human-cbd** [comment]
Hello I replied on Github

________________________________

**Comment by VivaWalletSupport** [comment]
See you are using the credentials from your live account. Please do as instructed, setup a demo account to connect at https://demo.vivapayments.com/ and post the relevant screenshots in case the problem persists.

**Comment by human-cbd** [comment]
![image](https://user-images.githubusercontent.com/56971117/67668493-54733300-f970-11e9-9368-33e6f11e3c17.png)

"Registration cannot be completed".....

**Comment by human-cbd** [comment]
I can't create demo account, there is an error.

**Comment by VivaWalletSupport** [comment]
Could you please create a new issue for the problem with creating an account in the demo environment so that the right department can pick it up?

**Comment by human-cbd** [comment]
It is done. Would not you have a demo account to be ready to move faster?

**Comment by matthewrgourd** [comment]
Hi @human-cbd I'm afraid we don't have any shared demo accounts you can use. However, I've replied to the other issue you raised about password reset not working.

**Comment by human-cbd** [comment]
Nothing works....

**Comment by matthewrgourd** [comment]
Hi @human-cbd I have tried and retried but I'm able to create demo accounts without any problems. Hence I have closed https://github.com/VivaPayments/API/issues/1182. Please let me know what the outstanding issue is and @VivaWalletSupport or myself will try to resolve.

**Comment by human-cbd** [comment]
I managed to create a demo account, there is an error with the french numbers because I managed to choose Germany.

I replaced Marchant ID with the one from the demo account, I tried to place an order but I have a 404 error.

![image](https://user-images.githubusercontent.com/56971117/68688046-6529c880-056e-11ea-9338-6574ce859f87.png)

**Comment by VivaWalletSupport** [comment]
Hello, what version of PHP is used and could you please provide following screenshots?

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by human-cbd** [comment]
My PHP version : 7.2

Screenshot ( demo mode )
![image](https://user-images.githubusercontent.com/56971117/68696525-6ca49e00-057d-11ea-9bea-bb2927842a61.png)
![image](https://user-images.githubusercontent.com/56971117/68696271-ed16cf00-057c-11ea-90e8-6f2d9a8adede.png)
![image](https://user-images.githubusercontent.com/56971117/68696558-7b8b5080-057d-11ea-9987-02e99bab7005.png)
![image](https://user-images.githubusercontent.com/56971117/68696590-87771280-057d-11ea-870c-f780858fae3b.png)

**Comment by VivaWalletSupport** [comment]
The posted plugin settings indicate that a 3rd party plugin is used. Please use the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by human-cbd** [comment]
Hello I have to reinstall the plugin but I always have the same error, the loading is infinite during the checkout ( live mode ) 
![image](https://user-images.githubusercontent.com/56971117/68772250-c8c4fc00-0629-11ea-8402-15da4d3a1039.png)
![image](https://user-images.githubusercontent.com/56971117/68772266-cd89b000-0629-11ea-8633-a774fb1c35fa.png)
![image](https://user-images.githubusercontent.com/56971117/68772327-e72af780-0629-11ea-98fc-25ab802ce1b5.png)
![image](https://user-images.githubusercontent.com/56971117/68772357-f6aa4080-0629-11ea-93cb-e7456c994295.png)

**Comment by VivaWalletSupport** [comment]
Hello, please configure for the demo mode and provide following screenshots:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by human-cbd** [comment]
(demo mode ) It's working, i come on your page : 

![image](https://user-images.githubusercontent.com/56971117/68780607-d8970d00-0636-11ea-896e-584ab383ee51.png)
![image](https://user-images.githubusercontent.com/56971117/68780630-ddf45780-0636-11ea-9eff-5d74358c3fdc.png)


After there is an error :

**Comment by human-cbd** [comment]
![image](https://user-images.githubusercontent.com/56971117/68780681-ed73a080-0636-11ea-92a9-6b8d2f276661.png)

![image](https://user-images.githubusercontent.com/56971117/68780710-f6647200-0636-11ea-9475-5488c1a8147f.png)

![image](https://user-images.githubusercontent.com/56971117/68780748-03816100-0637-11ea-9f10-b42132763d73.png)

![image](https://user-images.githubusercontent.com/56971117/68780800-13994080-0637-11ea-9a3f-798de455b965.png)

**Comment by VivaWalletSupport** [comment]
Did the transaction succeed in Viva, what was used to make the test transactions (amount, what card)?

**Comment by human-cbd** [comment]
Trying again the transaction was successful, I did not think it was necessary to use a real card for demo mode ..
![image](https://user-images.githubusercontent.com/56971117/68805669-91c00c00-0664-11ea-8eba-7b6ea8122f53.png)
![image](https://user-images.githubusercontent.com/56971117/68805679-971d5680-0664-11ea-8272-db8ce17f5fa5.png)

**Comment by human-cbd** [comment]
Hello, the transaction only works in demo mode.

**Comment by human-cbd** [comment]
?

**Comment by VivaWalletSupport** [comment]
As there is no problem in de demo mode, I can exclude that there is a problem with the plugin. Please check your configuration for the live mode, use the avaiable documentation.

**Comment by human-cbd** [comment]
Hello, same problem , impossible to finish the transaction and access to your payment !
![image](https://user-images.githubusercontent.com/56971117/69862032-e1741980-1299-11ea-8dca-a3d81222f6c2.png)
![image](https://user-images.githubusercontent.com/56971117/69862147-1d0ee380-129a-11ea-9a46-c47b1740d995.png)
![image](https://user-images.githubusercontent.com/56971117/69862192-2d26c300-129a-11ea-9b99-cc7cd9ca8e79.png)
![image](https://user-images.githubusercontent.com/56971117/69862233-3fa0fc80-129a-11ea-938b-599677387781.png)

**Comment by matthewrgourd** [comment]
Hi @human-cbd sorry to hear you're still experiencing issues. I've sent your update to our plugin developer in case he can help further.

**Comment by matthewrgourd** [comment]
Hi there, please send your Merchant ID (production) through to myself: mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
Hi @human-cbd, please send your Merchant ID (production) through to me (mgourd@vivawallet.com) referencing this issue. I will investigate further but at the moment I cannot find your account.

**Comment by matthewrgourd** [comment]
Hi @human-cbd, if this is still a problem, we advise following the [setup procedure](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) again in production after uninstalling the module completely.

**Comment by human-cbd** [comment]
always not working...

**Comment by matthewrgourd** [comment]
Hi @human-cbd please provide further details of the issue as it stands now. Error messages etc. I understand that you feel frustrated but there is no issue with our plugin so there must be something else that's wrong.

**Comment by human-cbd** [comment]
![image](https://user-images.githubusercontent.com/56971117/70794915-09d23c80-1d9f-11ea-9704-9889015fb500.png)

Hello, as you can see it again on this screenshot nothing happens when you click on validate the payment. I invite you to try an order by selecting your payment module during the checkout to better understand the problem. I tried other plugins of your competitors and only with yours that blocks. Can be an error with my vivawallet account my merchant id or my API?

https://www.human-cbd.fr/produit/bhanga-kush/

(Tell me when you have tested an order because I have to remove the plugin if it does not work because there is activity on my site)

**Comment by matthewrgourd** [comment]
@human-cbd I have tested just now and see what you mean about nothing happening at checkout. We know that our official plugin works so I'm not sure how to help other than mentioning again the suggestions we already gave you. One thing of note is that you previously installed an unofficial plugin. Are you sure that this is now completely removed?

**Comment by human-cbd** [comment]
Hello, I think the problem comes from the database.

At the beginning of December I emptied all the tables corresponding to the plugin to uninstall it correctly, by reinstalling it I managed to access your payment module and place an order (victory).
I left the payment module that I used for the holidays because I did not have time to take care of vivawallet. Today I want to stop my old payment module to switch to yours and ... it does not work anymore ... I tried to empty the database to delete all the tables corresponding to viva but it does not work .
When I reinstall the module I see that my information like my API is already entered, so it is stored somewhere? what are the different tables that the module vivawallet created in the database that I can empty everything ..

I am very frustrated to have declared victory too soon ...

**Comment by matthewrgourd** [comment]
Hi @human-cbd I'm sorry, I've read your reply but can't offer you any further help so am closing this issue. As already stated, our plugin definitely works. You need to completely remove any previous installations before reinstalling. Thanks and have a nice day!
