### ISSUE TITLE
Payment failures on WooCommerce again

### ISSUE THREAD

**Issue by foshdafosh** [VivaPayments/API#1175]
Hi there, I'm sorry to say that the shop isn't taking payments again.
Is there anything else I can try to get this up and running as soon as possible?

**Comment by VivaWalletSupport** [comment]
Hello, as we tested with success before using the demo account, there seem to be no problem with the plugin. I would suggest to contact your account manager to find out why transaction attempts fail.

**Comment by foshdafosh** [comment]
Thanks, shall do.
