### ISSUE TITLE
WooCommerce Plugin - Payment Pending & 3D Secure missing images

### ISSUE THREAD

**Issue by OrsomeWells** [VivaPayments/API#1176]
To the best of my knowledge I have configured the plugin correctly, however when a purchase is made it will show "Payment Pending" in the WooCommerce orders list.

The payment itself goes through and the customer receives an email from VivaWallet to this effect confirming the purchase. The funds also show in VivaWallet.

Additionally, the 3D Secure verification pop-up has all images missing as per another ticket in this forum.

Any ideas on what I'm doing wrong?

**Comment by VivaWalletSupport** [comment]
Hello, did you try testing with the a demo account?

**Comment by OrsomeWells** [comment]
Hi Tom,
No, this was connected to a live account.
Are you suggesting I should try with a demo account?
Cheers,
Ben

**Comment by VivaWalletSupport** [comment]
Hello Ben, yes that was my suggestion.
