### ISSUE TITLE
How can I get charge token using PHP?

### ISSUE THREAD

**Issue by maab16** [VivaPayments/API#1177]
Hi,

I want to get charge token using "Bearer" access token. I followed this url https://developer.vivawallet.com/authentication/ and get access token.

Now I want to get chargeToken that I want to store in database for future payment. Anyone there can help me to get chargetoken using  "Bearer" token.

https://developer.vivawallet.com/api-reference-guide/payment-api/card-tokenization/

I'm following above URL but It's not working in my case. Is there any resource or doc or tutorial or source code to solve my issue?

Thanks

**Comment by matthewrgourd** [comment]
Hi @maab16 Sorry for the delayed reply. I'm afraid that's all the documentation we have at present but I will take on board your comments for future iterations. I've checked with our development team and the functionality you mention is definitely working at this end. I will keep this issue open in case I can give you another update. Thanks!

**Comment by maab16** [comment]
Hello @matthewrgourd ,

Thanks for your reply. Can you send me some example where receive chargeToken using php (No JavaScript)?

**Comment by matthewrgourd** [comment]
Hi @maab16 unfortunately we're not in a position to provide php code samples right now but here's a link to a Postman collection I created earlier: https://app.getpostman.com/run-collection/abcf52c40e501ff233f0 . Or you can import the JSON (attached) into Postman. I hope this is a help to you!

**Comment by maab16** [comment]
Hello @matthewrgourd, It looks good in postman. I'm trying to apply in my project. I'll inform if I need further help. Thanks for your help.
