### ISSUE TITLE
vivawallet.zip module Prestashop

### ISSUE THREAD

**Issue by maragos91** [VivaPayments/API#1178]
I can't install vivawallet.zip module on my Prestashop. It fails and report than this module can not be disabled. My Prestashop version is 1.7.5.1

**Comment by VivaWalletSupport** [comment]
Hello, please check what error happens when installing the module.

**Comment by maragos91** [comment]
![SmartSelect_20191029-154604_Chrome](https://user-images.githubusercontent.com/57088202/67772753-494cff80-fa63-11e9-96ce-3df698f84676.jpg)

**Comment by VivaWalletSupport** [comment]
Unfortunately I am not ale to replicate the problem, I would suggest to check PrestaShop's forum for similar problems or to perform a Google on it.

**Comment by bekway** [comment]
Hi Maragos91
Did you resolve this problem? I have exactly the same issue and our website has now been offline for 12 days.
