### ISSUE TITLE
Connect VIVA WALLET with e-shop

### ISSUE THREAD

**Issue by magicom-gr** [VivaPayments/API#1179]
Καλημέρα,

Χρησιμοποιώ την πλατφόρμα ARCADIER Marketplace για το ηλεκτρονικό μου κατάστημα.
Η πλατφόρμα σου δίνει την δυνατότητα να συνδέσεις τρόπους πληρωμής πέραν των PayPal, Stripe και Omise που υποστηρίζει.
Θα ήθελα να έχω σαν τρόπο πληρωμής και το VIVA WALLET (αυτό που με ενδιαφέρει είναι να μπορεί να πληρώσει κάποιος με την πιστωτική του κάρτα χωρίς να χρειάζεται να το κάνει μέσω PayPal αν δεν θέλει)
Επισυνάπτω τις οδηγίες από την πλατφόρμα για την σύνδεση τρόπου πληρωμής.

Μπορεί να βοηθήσει κάποιος;

Ευχαριστώ εκ των προτέρων.

Σωτήρης Μέγγουλης
s.megoulis@gmail.com

[Connect payment method.docx](https://github.com/VivaPayments/API/files/3778111/Connect.payment.method.docx)

**Comment by matthewrgourd** [comment]
Unfortunately an offical plugin for the Viva Wallet payment gateway is not currently available for Arcadier Marketplace.
