### ISSUE TITLE
How to wake up terminal(Mini Reader)

### ISSUE THREAD

**Issue by ilseopHwang** [VivaPayments/API#1180]
Hello.

I am a Bluetooth engineer of Bluebird in Korea. My company provide Android device to many countries.
One of my customer is using your Mini Reader.
Recently they report a issue. Vivawallet app failed if your product is in sleep mode(No LED is on). 
But I found that Bluetooth connection made actually and my android device could read information from Mini Reader even though Mini Reader’s LED is off.
You can see mov file. https://drive.google.com/open?id=1fYiwr5BfkPzFVJcHsZor9SXkteBOdMtt
Of course Vivawallet app works well if Terminal wake up and led is on.

I cannot find any document in your dev site. So please let me any guide how to turn on your product that is in sleep mode from remotes.

This is information of Mini Reader.
Manufacturer Name String: NordicSemiconductor
Model Number String: 4.2 LESC eval
HW Rev: 0.8
Frimware Rev: 8.11D
SW Rev: 2.01

Android OS 7.1.2

BR
Tim.

**Comment by matthewrgourd** [comment]
Hi there, thanks for raising this. Apparently there are known issues which will be addressed by a firmware update to the Mini Reader. This should happen by the end of next week (w/e 10 Nov). If after this you're still experiencing difficulties, please send through further details.
