### ISSUE TITLE
VivaPayments JS is not working on IE 11 or Edge

### ISSUE THREAD

**Issue by jkatsiotis** [VivaPayments/API#1181]
The JS file has syntax errors and it's not working on IE or Edge. Kindly look into is asap as it's easy to fix and urgent

**Comment by theremon** [comment]
Hello,

same thing happens with older versions of Safari that are still however in use.
ES6 features and coding is not supported on IE11 of older Safari versions and the Viva scripts crash.

**Comment by jkatsiotis** [comment]
Is this fixed?

**Comment by dpnevmatikos** [comment]
Hello @jkatsiotis @theremon 
Issue's fixed and it will be released into production within the next week.
