### ISSUE TITLE
I cant create demo acount to resolve issue #1174

### ISSUE THREAD

**Issue by human-cbd** [VivaPayments/API#1182]
![image](https://user-images.githubusercontent.com/56971117/67752659-a3ce6780-fa33-11e9-9dd4-3350830ab989.png)

Hello, to solve the issue # 1174, I need to set up a demo account. Unfortunately I can not create an account, an error appears.

**Comment by matthewrgourd** [comment]
Hi @human-cbd I believe this may be because you're already registered. Have you tried logging in here with your usual mobile phone number? https://demo.vivapayments.com/en-fr/signin

**Comment by human-cbd** [comment]
![image](https://user-images.githubusercontent.com/56971117/67780894-03923600-fa67-11e9-8d00-0973eaa37efd.png)

Hello it does not work with my normal account and when I do "forgotten password" there is an error

**Comment by matthewrgourd** [comment]
Hi there, I think you need to drop the zero at the beginning of your phone number. Please do this and try again.

**Comment by human-cbd** [comment]
![image](https://user-images.githubusercontent.com/56971117/67854447-a3f06500-fb10-11e9-8a76-60a3648b3034.png)

Hello, It does not work .. I tried with and without the 0, I tried several numbers and several passwords.
I tried to remove my Adblock but it still does not work.

**Comment by human-cbd** [comment]
I tried with another browser so nothing works ...

**Comment by matthewrgourd** [comment]
I'm sorry but I'm unable to recreate your issue. Can you maybe try clearing your autofill form settings and retyping the input fields manually.

**Comment by human-cbd** [comment]
I already did it does not work

**Comment by matthewrgourd** [comment]
Hi @human-cbd I'm sorry I cannot recreate the issue. Is it still a problem?

**Comment by matthewrgourd** [comment]
Hi @human-cbd you can create as many demo accounts as you like, just vary the mobile number at registration (doesn't have to be real as we don't need to send any verification texts unless you are registering for production). The error you're receiving is because you attempted to set up a new account with a previously registered mobile number. I've checked more than once and there's definitely no issue at the Viva Wallet end. Hope this helps! Am closing the issue now.

**Comment by human-cbd** [comment]
NO it's not working, my problem are not resolve... I can't use your system payment, read my message, i have already try it, my problem is a API problem. 2 weeks to tell me how to create a demo acount... Not serious...

**Comment by matthewrgourd** [comment]
Hi there, please provide a link to the API issue if you’ve already raised one and I will look at it a.s.a.p.

**Comment by human-cbd** [comment]
https://github.com/VivaPayments/API/issues/1174
