### ISSUE TITLE
Native Checkout error 1012

### ISSUE THREAD

**Issue by cstsortan** [VivaPayments/API#1188]
Hello there,
We have an issue with Native Checkout transactions on a client

We’re getting an error code 1012, and transactions fail. Please note that apiKey on this client has a structure way different from others, and also publicKey was not displaying until last week. However.
I am not sure if this is relative to the issue in any way, but looks similar to https://github.com/VivaPayments/API/issues/1171

**Comment by matthewrgourd** [comment]
Hi there, sounds as though you may still be using Native Checkout v1 which has been deprecated. In this instance you need to follow these instructions to migrate to v2: https://developer.vivawallet.com/online-checkouts/migrating-from-native-checkout-v1/

**Comment by cstsortan** [comment]
So what happens to clients still hitting v1 in production? Are we excepting this to stop receiving requests any time in the future?

**Comment by matthewrgourd** [comment]
Hi @cstsortan I understand that v1 won't suddenly stop working tomorrow but you'd be wise to upgrade to v2 when you can.
