### ISSUE TITLE
VIVA WALLET PAYMENT FAILED.(Reopen)

### ISSUE THREAD

**Issue by EuroStreet** [VivaPayments/API#1189]
My previous topic was closed without any solution so far.
ISSUE:
Hello, I set up the viva wallet on our website, I followed all the instructions, and it looks perfectly fine.
However, when I go to make the Payment, it keeps getting ''Failed''.
I also contacted the Viva Wallet support, and they send me here.
My shop is also Activated on the Viva Wallet account.
I'm using open cart 2.3.2, and installed the plugin of the Viva Wallet that you had in instructions.
And 3d  secure looks broken, I'am using LIVE version not demo.
Pictures:
![67480056-eecd3100-f667-11e9-828b-1e4227067c60](https://user-images.githubusercontent.com/56961296/68068437-6c2a2d00-fd5d-11e9-89b2-ca75ff5ceb6f.png)
![67558828-69598780-f720-11e9-9f58-7f2721fcdd24](https://user-images.githubusercontent.com/56961296/68068438-6cc2c380-fd5d-11e9-9ffa-9492fb7e4a6a.png)

**Comment by matthewrgourd** [comment]
Hi @EuroStreet I'm checking with our dev team today. I'll update you when I can. Thanks!

**Comment by dpnevmatikos** [comment]
Hello @EuroStreet  
Does this error appear consistently every time checkout page is rendered, and with 
different card numbers ? If possible, please provide us your merchant id for further investigation.

**Comment by EuroStreet** [comment]
Hello, @dpnevmatikos 
My merchant id: 6360
Every time, we try to pay in the website, it says FAILED, in both ways Redirection/Native Checkout v2 or Native/Pay with Viva Wallet Checkout
We tried about 5 different working credit cards(our personal cc).

**Comment by EuroStreet** [comment]
Hello, @dpnevmatikos <https://github.com/dpnevmatikos>
My merchant id: 6360
Every time, we try to pay in the website, it says FAILED, in both ways
Redirection/Native Checkout v2 or Native/Pay with Viva Wallet Checkout
We tried about 5 different working credit cards(our personal cc).

**Comment by EuroStreet** [comment]
Sorry, the merchant ID is :  a3ed4c90-7420-42e9-9b84-39b84db0e0ec

**Comment by dpnevmatikos** [comment]
>Every time, we try to pay in the website, it says FAILED, in both ways
Redirection/Native Checkout v2 or Native/Pay with Viva Wallet Checkout

what's the error you're getting from the API when using Native checkout v2 ? You should be receiving an HTTP status code along with an error text.

**Comment by EuroStreet** [comment]
Not sure I received any error, is there an error log for viva wallet? so i
can check it ?

**Comment by EuroStreet** [comment]
Now for some reason, one of the credit cards that was keep saying failed
before, it just worked, and it made the payment, did u made any changes?,
should i try with more credit cards?

**Comment by EuroStreet** [comment]
So basically, it's declining a lot of cards for some reasons?, I'll have a
test with 3-4 more credit cards today and let u know

Στις Δευ, 4 Νοε 2019, 13:54 ο χρήστης Adonis Priftis <
eurostreet101@gmail.com> έγραψε:

> Now for some reason, one of the credit cards that was keep saying failed
> before, it just worked, and it made the payment, did u made any changes?,
> should i try with more credit cards?
>
> On Mon, Nov 4, 2019 at 1:49 PM Adonis Priftis <eurostreet101@gmail.com>
> wrote:
>
>> Not sure I received any error, is there an error log for viva wallet? so
>> i can check it ?
>>
>> On Mon, Nov 4, 2019 at 1:47 PM Dimitris Pnevmatikos <

**Comment by matthewrgourd** [comment]
Hi @EuroStreet can you close this issue if no more card problems. Thanks!
