### ISSUE TITLE
Checkout παραγγελιών VivaPayments Payment Gateway και στα Αγγλικά

### ISSUE THREAD

**Issue by musicmegastoregr** [VivaPayments/API#119]
Καλησπέρα σας,

Σας στέλνω εκ μέρους του music-megastore.gr, 

Πελάτης μας προσπάθησε να χρησιμοποιήσει την VivaPayments Payment Gateway δυνατότητα που παρέχουμε στο site μας, όμως η εν λόγω σελίδα ολοκληρώσεως του checkout εμφανίζεται μόνον στα Ελληνικά και ο πελάτης είναι Άγγλος,

Θα θέλαμε να μπορεί να εμφανιστεί η εν λόγω σελίδα και στα αγγλικά για να μπορεί να χρησιμοποιηθεί και από πελάτες εκτός Ελλάδος,

Περιμένω νέα σας σχετικά,

Φιλικά,

Κόκκινος Λάμπρος

**Comment by dpnevmatikos** [comment]
Καλησπέρα @musicmegastoregr 
Για να αλλάξετε τη γλώσσα της checkout θα πρέπει κατά τη δημιουργία του κωδικού πληρωμής στην ```CreateOrder``` να περάσετε και την παράμετρο ```RequestLang="en-US"``` όπως φαίνεται και σε αυτό το [sample](https://github.com/VivaPayments/API/wiki/CreateOrder#sample-request).

Ευχαριστούμε.

**Comment by musicmegastoregr** [comment]
ευχαριστώ για την άμεση απάντηση
