### ISSUE TITLE
Woocommerce not picking up the completed payment

### ISSUE THREAD

**Issue by kybalion2** [VivaPayments/API#1191]
Hi Matthew,
I'm new to Viva, I hope you can help get this running. The account ID status is active and entered in the ID of the plugin along with API and the Merchant ID.
I'm using the official Version 3.5.7 | By Viva Wallet 

There are a few problems:
1. The payment goes through to Visa wallet but woocommerce shows as still pending payment.
2. The items stay in the cart after checkout, but this doesn't happen with paypal checkout.
3. Upon posting payment, the result is 'page not found' even tho I have made a payment completed page:  https://werone.co/eng/payment-complete .

I suspect this may be a webhook issue, but I haven't found how to set them correctly yet. 

Thanks in Advance

Ky
![image](https://user-images.githubusercontent.com/47025070/68093894-aa753880-fe92-11e9-88a0-3d0fa2855f38.png)

![image](https://user-images.githubusercontent.com/47025070/68093898-b234dd00-fe92-11e9-9e38-eec20a08bf28.png)

**Comment by VivaWalletSupport** [comment]
Hello, please follow the setup instructions given at https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by kybalion2** [comment]
Hi Matthew,
Thanks so much, adding in the webhooks seems to have resolved the issue.

One thing which is a little disconcerting in the process is when on the Checkout page and you click Proceed to Payment , our CART page briefly flashes up with a Viva dialogue box which is so fast you can't read the redirection notice, is there a way to tidy this experience up? Some customers may feel they have been intercepted by something?

Also, the logo I uploaded fresh in the API screen logo and it seems to revert back when it feels like it to the first logo I uploaded, is that a caching issue?

Best Regards

Ky

**Comment by matthewrgourd** [comment]
Hi @kybalion2 thank you for the feedback. I will pass on to our development team for analysis and potential action. Best regards.
