### ISSUE TITLE
@Petpanic.gr - VivaPayments issue again

### ISSUE THREAD

**Issue by ntourziotis** [VivaPayments/API#1192]
Αγαπητή ομάδα καλησπέρα,

Εδώ και κάποιες ημέρες παρουσιάζεται πρόβλημα με τις ηλεκτρονικές συναλλαγές στο eshop μας
https://petpanic.gr

Το πρόβλημα παρουσιάζεται συγκεκριμένα στη πληρωμή με κάρτα. Χρησιμοποιούμε το plugin σας (viva payment) εδώ και αρκετά χρόνια με επιτυχία. Πρόσφατα περάσαμε το τελευταίο update για joomla που μας στείλατε και τα προβλήματα λύθηκαν. Ωστόσο το τελευταίο καιρό μας δημιουργούνται πάλι θέματα με τις πληρωμές, αλλά όχι συνέχεια στην ολοκλήρωση της παραγγελίας. 
Joomla Site με
MerchantID: a64460bc-0c01-41a2-9cf3-d026117389be

Μπορείτε σας παρακαλώ να με βοηθήσετε να κατανοήσουμε το πρόβλημα και να το διορθώσουμε άμεσα, γιατί δημιουργεί θέμα στην επιχείρηση μας? 

Για οποιαδήποτε απορία παραμένω στη διάθεση σας.

Με εκτίμηση 

Ντουρζιώτης Γιάννης

**Comment by VivaWalletSupport** [comment]
Hello, please provide detailed information about the problem you currently have with Viva. Use some examples or screenshots to make the problem clear.

**Comment by ntourziotis** [comment]
Hello team,

The last few days all the card payments are canceled . https://prnt.sc/psnjyl 
Could you please let me know what extra details you need? 

Best regards

ioannis

**Comment by VivaWalletSupport** [comment]
In fact I would need more details like was the transaction successful (registered in you Viva backoffice), did the tranesaction fail, has the transaction been registered in your Viva backoffice. Did you test placing an order yourself, if so, what is the outcome?

**Comment by ntourziotis** [comment]
Hi again 

I just did a live test payment and at the time i chose to pay with credit card appears the 404 error
https://prnt.sc/psp5jc

Does it make sense?

Best regards

Ioannis

**Comment by VivaWalletSupport** [comment]
Please provide following screenshots:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by ntourziotis** [comment]
Here you are. please check attached
![joomla](https://user-images.githubusercontent.com/54627473/68210501-57100100-ffde-11e9-99bf-49d160711621.jpg)
![70924564_2356243934625039_5257320414488559616_n](https://user-images.githubusercontent.com/54627473/68210518-5ecfa580-ffde-11e9-8687-3bea4c6c03ba.jpg)
![74175742_464745234387416_951577294650998784_n](https://user-images.githubusercontent.com/54627473/68210520-5ecfa580-ffde-11e9-94e2-271149485fbb.jpg)
![75446534_399455344334730_5261568064129859584_n](https://user-images.githubusercontent.com/54627473/68210521-5f683c00-ffde-11e9-92a9-cae79bb4d2c7.jpg)

**Comment by VivaWalletSupport** [comment]
What changes have been made before the connection stopped working? Did you try changing your API Key in your Viva account and in the plugin settings?

**Comment by ntourziotis** [comment]
As much as I Know we haven't done any changes either plugin settings neither Viva Account.

**Comment by VivaWalletSupport** [comment]
Please try changing your API Key in your Viva account and in the plugin settings.

**Comment by ntourziotis** [comment]
Good morning

Should i add whatever I want or you send me a new one?

**Comment by VivaWalletSupport** [comment]
You can use your own preference here.

**Comment by ntourziotis** [comment]
Greetings again,

We changed the API Key finally! 

Unfortunatelly we are facing the same issue. Could you please check and let us know, what we have to do ? Our company has very big issue and very big economical impact with this error.

Please let us know.

Regards
Ioannis

**Comment by VivaWalletSupport** [comment]
Please send admin login credentials + FTP credentials to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com to investigate the problem.

**Comment by VivaWalletSupport** [comment]
The problem is the Vivawallet Merchant ID that you specified in the plugin settings. The 6th character should be a 0 (zero) and not an O (capital O as in Oscar). Please make the correction.

**Comment by ntourziotis** [comment]
Good morning

Thanks a lot for your help,very
much appreciated.

It looks very weird to me, the fact I have never changed that before. So
the capital O was there from the beginning of the configuration!

Do you believe now we are fine ?

Best regards

Ioannis
