### ISSUE TITLE
@cbddiffusion - Payment by credit card failed

### ISSUE THREAD

**Issue by cafeine404** [VivaPayments/API#1193]
Hello,

We have put viva wallet on a prestashop 1.6.1.18 with the module u offer.
I think i made all the parameters good.
I made test with success.

But now, some customers told me they got errors, and i made test with the same result : the usual sentence of the module if there is trouble with paiement : We noticed a problem with your transaction. If you think this is an error, please contact us. 

I made the order, i got the page with credit card info, i put it. I have the 3D secure verification. I made it and then the page is loading and no success. I got email indicate error in paiement.

I dont know if it is an error with parameters or else.
Thx for ur help.

![image](https://user-images.githubusercontent.com/19798184/68223436-12d82d00-ffed-11e9-983a-d22b7b2d4b9a.png)

![image](https://user-images.githubusercontent.com/19798184/68223464-208db280-ffed-11e9-83a4-dee5bef97075.png)
![Screenshot_2019-11-05 https members vivawallet com](https://user-images.githubusercontent.com/19798184/68223619-68acd500-ffed-11e9-80ee-fb61278e15f0.jpg)

**Comment by cafeine404** [comment]
![Screenshot_2019-11-05 https members vivawallet com](https://user-images.githubusercontent.com/19798184/68223770-ae699d80-ffed-11e9-9bd7-e51e0213afdc.jpg)

on prestashop

**Comment by VivaWalletSupport** [comment]
Hello, could you please calrify if the transaction also failed (in your Viva backoffice)?

**Comment by cafeine404** [comment]
Thx for ur answer.

I got nothing in the back this week, or days before my test were ok.
![Screenshot_2019-11-05 https members vivawallet com](https://user-images.githubusercontent.com/19798184/68289151-ef14f580-0085-11ea-9255-8c79d6c218e2.jpg)

**Comment by VivaWalletSupport** [comment]
So I might conclude it is not an issue with the plugin and it is a matter of transactions failing in the Viva environment. You might try to contact your Viva account manager for this matter or wait and see if someone from Viva can see why this is happening.

**Comment by cafeine404** [comment]
they told me it is the plugin trouble ^^, is there anything else i can test or check to see if my parameters are all good before seeing back with them ?

**Comment by VivaWalletSupport** [comment]
You can setup the module using the demo environment (https://demo.vivapayments.com/) and the test cards.

**Comment by cafeine404** [comment]
For info, right now, i made a new test on my website, the 3D secure system looks like he changes (not the same that yesterday, the code is send automatically). Then i got the message for the validation of the authentification (that i didnt have before) but still... error. i will contact the other support.

**Comment by cafeine404** [comment]
they ask for this issue ref, i guess some return will come
