### ISSUE TITLE
Simple Checkout implementation problem

### ISSUE THREAD

**Issue by FLIPNEWMEDIA** [VivaPayments/API#1194]
Hello,
We are trying to implement the Simple Checkout method to enable online viva payments on our website. On the last step (Make the charge) where we are sending an HTTP post request to **https://www.vivapayments.com/api/transactions**  along with the **vivaWalletToken** parameter, the transaction fails with text error: The specified api action is disabled for the merchant 72f989bc-5218-4d12-8911-92ad23c41107, please consult the documentation.  The returned json is this: {"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"The specified api action is disabled for the merchant 72f989bc-5218-4d12-8911-92ad23c41107, please consult the documentation","TimeStamp":"2019-11-05T17:53:01.3580551+02:00","CorrelationId":null,"EventId":0,"Success":false}.

On my viva wallet account all api security features are enabled.
![Screenshot 2019-11-05 at 18 05 53](https://user-images.githubusercontent.com/57406369/68224335-11abfd80-fff7-11e9-80a3-f2ba1e490058.png)

**Comment by matthewrgourd** [comment]
Hi @FLIPNEWMEDIA I've enabled your public API key now. For some reason it previously wasn't displaying under your profile. Can you try the process again from the beginning with this value for `data-vp-publickey`? Let me know how you get on!

**Comment by FLIPNEWMEDIA** [comment]
The problem is fixed. Everything works as expected! Thank you!
