### ISSUE TITLE
Native Checkout v2 3DS Problem

### ISSUE THREAD

**Issue by Afrodith** [VivaPayments/API#1195]
Hello,
I am trying to implement the Native Checkout v2 method in my website so it can handle viva payments. I have followed the Online Checkout guide for the Native Checkout v2 3DS and i am sussesfully generating and storing an OAuth 2 token on my transactions. 
The problem is that when i am trying to POST my data from my form (i followed the template for my form as it is described in the guide) and click the Submit button it doesnt seem to ever call the VivaPayments.cards.requestToken()  and VivaPayments.cards.setup() function even though i have confirmed it reaches the functions. I have confirmed by debbuging with console log that i am indeed making a call to these functions on POST. It just seems not to excecute any code inside the functions. 

The structrure of my button on click call and the fuinctions are :
` <input type="button"  class="btn green"  id="submit" value="<%=myAmmount %>"  onclick ="getRequest();" />`

`$(document).ready(function () {

          console.log("testt");
          if ($('#payment-form').length)  
              VivaPayments.cards.setup({
              authToken: '<%=Stored.authToken %>', //use the current valid stored token
              baseURL: 'https://demo-api.vivapayments.com', //get viva base url from the merchant model
              cardHolderAuthOptions: {
                  cardHolderAuthPlaceholderId: 'threed-secure-pane',
                  cardHolderAuthInitiated: function () {
                      alert('Cardholder authentication started!');
                  },
                  cardHolderAuthFinished: function () {
                      alert('Cardholder authentication has finished');
                  }
              }
          });`

`function getRequest() {
          console.log("Test here");
          VivaPayments.cards.requestToken({
              amount: '<%=myAmount %>',  //get the amount to pay dynamically.
              installments: 1,
              authenticateCardholder: true
          }).done(function (responseData) {
              console.log(`Here is the charge token: ${responseData.chargeToken}`);
          });
      }`

Can you give me some feedback or guide me towards what the problem could be?

Thank you very much in advance!

**Comment by Sotiris-k** [comment]
You should try adding a fail callback to that requestToken Promise. For example.
```
VivaPayments.cards.requestToken({
  amount: 1321, // amount is in currency's minor unit of measurement
  installments: 1,
  authenticateCardholder: true
}).done(function (responseData) {
  console.log('Here is the charge token: ${responseData.chargeToken}');
}).fail(function (responseData) {
  console.log('Here is the reason it failed: '  + responseData.Error.toString());
});
```

**Comment by Sotiris-k** [comment]
Also @matthewrgourd I think it would actually be best if you added that fail callback in your dev documentation [here](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-4-request-a-charge-token)

**Comment by matthewrgourd** [comment]
@Sotiris-k thank you!

**Comment by Afrodith** [comment]
Ok, Thank you for your answer and information! i'm going to try to resolve my issue this way.
