### ISSUE TITLE
Shopify Preferences - VivaWallet

### ISSUE THREAD

**Issue by smartfits** [VivaPayments/API#1196]
I have connected VivaWallet with Shopify but I have 2 issues
1) I want to change the "Credit or Debit Card" text to translate it to Greek
2) After the redirection to VivaPayments page the Viva Page is in english while my whole website is in greek. (vivapayments.com/web/checkout?lang=en is the default)
Below I have images with the issues
http://prntscr.com/ptofew
http://prntscr.com/ptofne

**Comment by matthewrgourd** [comment]
Hi @smartfits 

Apologies for the delayed reply.

I've spoken with our Shopfy plugin developer and apparently the button cannot be translated.

The checkout page matches the settings of your Shopify store. You will have to change the country of the shop to Greece. Then the checkout will open in Greek.

Hope this helps!

**Comment by smartfits** [comment]
1) The language of my shopify store & shopify checkout is in greek but the vivawaller redirection is still in english
2) I have searched the whole shopify language text to translate the "Credit Card" text but I cannot find it. This text is controlled by the the viva app on top of shopify. They can definitely change it/
