### ISSUE TITLE
ΠΩΣ ΑΛΛΑΖΩ ΤΟ API KEY ΣΤΟ VIVA BACKOFFICE

### ISSUE THREAD

**Issue by mariaalex93** [VivaPayments/API#1199]
Καλησπέρα σας,

Θα ήθελα να μου εξηγήσετε τον τρόπο για το πως θα αλλάξω το API KEY στο VIVA BACKOFFICE.

**Comment by matthewrgourd** [comment]
Hi @mariaalex93 you simply go to the [API access screen](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) and amend your API key with your preferred characters.
