### ISSUE TITLE
ip or sitename

### ISSUE THREAD

**Issue by nikosnik** [VivaPayments/API#120]
Hi, 

We have a eshop that uses vivapayments. we are about to change the IP of the server. Will this affect the gateway? 
Is vivapayment using the ip or the sitename to verify the incomiming connection ?

Kind Regards

**Comment by defilerc** [comment]
Hi @nikosnik,

There is no IP restriction, when calling the Viva Payments API. As long as you call the API with the correct credentials assigned to your merchant, you will be fine.

Best regards
