### ISSUE TITLE
404 - File or directory not found.

### ISSUE THREAD

**Issue by Zouari11** [VivaPayments/API#1200]
Hello,
I installed viva payments, only
- I have a 404 error
- I can not put Webhook:
https://www.rapide-achat.com/index.php?wc-api=wc_vivawallet&vivawallet=webhook

https://www.rapide-achat.com
<img width="641" alt="Capture d’écran 2019-11-08 à 15 27 22" src="https://user-images.githubusercontent.com/57533754/68484128-00543280-023d-11ea-865b-9e76fd1c6f06.png">
<img width="1280" alt="Capture d’écran 2019-11-08 à 15 27 28" src="https://user-images.githubusercontent.com/57533754/68484129-00543280-023d-11ea-8b47-7c49ba7a1584.png">

Thank you for your help

**Comment by VivaWalletSupport** [comment]
Please provide following screenshots:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by matthewrgourd** [comment]
Closing issue as no reply from user.
