### ISSUE TITLE
stuck at viva 3d secure payment page in demo 

### ISSUE THREAD

**Issue by Shubham3454** [VivaPayments/API#1201]
hi,
I am using viva redirect checkout in demo environment  i am using 4111111111111 and 111 as card number and cvv with valid date of card date here is the req body  and url -
https://demo.vivapayments.com/api/orders
{
  "Tags": [
    "sample string 1",
    "sample string 2",
    "sample string 3"
  ],
  "Email": "customer123@yopmail.com",
  "Phone": "2117604000",
  "FullName": "Customer Name",
  "PaymentTimeOut": 86400,
  "RequestLang": "en-US",
  "MaxInstallments": 12,
  "AllowRecurring": true,
  "IsPreAuth": true,
  "Amount": 1000,
  "MerchantTrns": "Your reference",
  "CustomerTrns": "Description that the customer sees"
}

id - b0afc089-5868-42fd-a5c1-b5bf9641146b
API key - jQoNx4

the page get stuck here after entring the details 
 
[
<img width="1114" alt="Screenshot 2019-11-08 at viva issue PM" src="https://user-images.githubusercontent.com/33493304/68563589-054ef700-0474-11ea-9206-177b66ac1c7e.png">
](url)

**Comment by matthewrgourd** [comment]
Hi there, it appears you added a duplicate URL component to the redirect address:

https://demo.vivapayments.com/web/web/checkout?ref=[order code]

E.g.

https://demo.vivapayments.com/web/web/checkout?ref=3808346171052841

when it should be

https://demo.vivapayments.com/web/checkout?ref=[order code]

E.g. 

https://demo.vivapayments.com/web/checkout?ref=3808346171052841

**Comment by Shubham3454** [comment]
@matthewrgourd  I haven't added web/web I think it  is added two times own its own, because  in case I have added this then the URL on which I am adding card details should be - https://demo.vivapayments.com/web/web/checkout?ref=6508413876722094 which will not open so after going to https://demo.vivapayments.com/web/checkout?ref=6508413876722094 and adding card details it is redirecting to https://demo.vivapayments.com/web/web/checkout?ref=6508413876722094 own its own , I don't know how but it is not happening now as I have just checked although thanks for your help, I think it is working now
