### ISSUE TITLE
Simple Checkout integration (novice)

### ISSUE THREAD

**Issue by ranger-a** [VivaPayments/API#1202]
Is it possible for a complete novice to integrate the simple checkout into a website ? I have zero experience, I employed the theme developer to do this for me but they have let me down, now I'm stuck. Don't know where to start despite looking at the guidelines, it makes no sense to me !! tia

**Comment by ranger-a** [comment]
Can someone do this for me ?

**Comment by matthewrgourd** [comment]
Hi @ranger-a I'm afraid you do need to have some front-end development experience as we don't offer any training or consultancy at this end. Sorry for that and good luck!
