### ISSUE TITLE
Viva Wallet | Plugin Opencart

### ISSUE THREAD

**Issue by BoostYourDigital** [VivaPayments/API#1204]
Hello,
I've one bug in my installation. Every purchase made in the shop is going to missing orders. Check ss below:
http://prntscr.com/pvzoik

Everything is working fine on frontend, the money goes to the wallet but the orders gets this "filter".
any idea why?
This is the shop: https://mariadomarshop.com/loja/
This is the client number: Paper Boat Import & Export Lda 

Thanks.
Please reach on email: david.rodrigues@byd.pt

Thanks.

**Comment by VivaWalletSupport** [comment]
Hello, in case the plugin and instructions are used from https://developer.vivawallet.com/e-commerce-plugins/ please provide following screenshots:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by BoostYourDigital** [comment]
Hello,
http://prntscr.com/pwip2v
http://prntscr.com/pwipm2

Is this all that you need?
Thanks.

**Comment by VivaWalletSupport** [comment]
You posted 2 from the 4 requested screenshots. So far I see you did not specify the source code (5061) in the plugin settings like mentioned in the instructions.

**Comment by BoostYourDigital** [comment]
Hello,
Sorry for the delay. SS below:
http://prntscr.com/pziwa6
http://prntscr.com/pziyx2
http://prntscr.com/pzizbd
http://prntscr.com/pzizix
http://prntscr.com/pzizyq
https://www.vivapayments.com/web/newtransaction.aspx?Ref=8485263216748347
I've already specified the source code.
Thanks.

**Comment by VivaWalletSupport** [comment]
Could you confirm the problem still exists after specifying the souce code and a successful transaction? If so, please setup the gateway with the demo mode from Viva in order to test.

**Comment by BoostYourDigital** [comment]
Yes, almost everything ok!

There is one thing left. If, for some reason, the data is incorrect the clients is redirected to the website checkout again. How can I keep him in vivawallet checkout? (here: http://prntscr.com/pzordy)

Thanks!

**Comment by VivaWalletSupport** [comment]
This is how the plugin works, so that the customer might try another payment method.
