### ISSUE TITLE
PaymentsPolicyCreditRestriction | Native Checkout v2 3DS

### ISSUE THREAD

**Issue by Varekto** [VivaPayments/API#1205]
Hey,
I'm working on integration Native Checkout v2 3DS.

But I every time get the response:
```
[
  "status" => 403
  "message" => "PaymentsPolicyCreditRestriction"
  "eventId" => "2105"
]
```

Could you please tell me the reason?

**Comment by matthewrgourd** [comment]
Hi @Varekto please send your Merchant ID to mgourd@vivawallet.com referencing this issue and I'll check your account. Thanks!

**Comment by morv96** [comment]
hi, the marcant ID was sent to the email you post above.

**Comment by marketima** [comment]
hi, the marcant ID was sent to the email you post above.

**Comment by matthewrgourd** [comment]
Hi @Varekto I've checked your account and setup isn't fully completed yet I'm afraid. You should have received emails regarding this. Please try again once you receive confirmation.

**Comment by marketima** [comment]
hi, i have checked my email and i didn't recieve any. emailregarding setup or what you wrote
what setup? i worked before with native checkout v1 and when i immigrate to v2 i saw this error again.

so what do i need to do? (i didn't got you from your response)

**Comment by matthewrgourd** [comment]
Have you checked for any messages on your account after [logging in](https://members.vivawallet.com/en-eu/signin)? If you're still unsure about your account status please call customer services: https://www.vivawallet.com/en-eu/contact-us/

**Comment by marketima** [comment]
hi, i face again this issue:

2019-12-17 12:52:25
Response: {"status":403,"message":"PaymentsPolicyCreditRestriction","eventId":"2105"}

can you check it please, as it cause big trouble and in support nobody reply my email almost 20 days as well i call to support by phone.

**Comment by matthewrgourd** [comment]
Hi @marketima, sorry to hear this, I'm checking with our development team.
