### ISSUE TITLE
API Call failed! 

### ISSUE THREAD

**Issue by codnext** [VivaPayments/API#1206]
Καλησπέρα σας,

Τρέχω τον κώδικα .php που βρήκα στον ακόλουθο σύνδεσμο έχοντας αλλάξει τα merchant id και api key με αυτά του λογαριασμού μου:
https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php

**Αλλά λαμβάνω το ακόλουθο μήνυμα:**
"API Call failed! The error was: Your Order Code is:
To simulate a successful payment, use the credit card 4111 1111 1111 1111, with a valid expiration date and 111 as CVV2.
Make Payment"

**Δεν θα έπρεπε να μου εμφανίζει order_code?**

**Comment by matthewrgourd** [comment]
Hi @codnext can you see if the following card details work instead and let me know how you get on? Thanks!

"cvc": 111,
"expirationMonth": 1,
"expirationYear": 2020,
"holderName": "Nikos Saravanos",
"number": "4016000000000000028"

**Comment by codnext** [comment]
Εκτελώ τον κώδικα που επιστρέφει το order code πριν κανω redirect για το checkout και παίρνω το παραπάνω μήνυμα. Δεν λαμβάνω order code..

**Comment by codnext** [comment]
Try to run this code to check it:
https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php

**Comment by matthewrgourd** [comment]
Hi @codnext we need to update that code. I will remove reference to it in the documentation for the time being.

**Comment by codnext** [comment]
Will you update it soon? If not I should create the php code for it.. Thank you!

**Comment by matthewrgourd** [comment]
Hi @codnext, it won't be immediately so I should come up with your own version. Thanks!
