### ISSUE TITLE
magneto 2.2.9 viva wallet redirect error 

### ISSUE THREAD

**Issue by alexbk31** [VivaPayments/API#1207]
Hi when a customer places order on website it dosnt seem to redirect to viva it just gose to order complete 
please see attached

**Comment by alexbk31** [comment]
![viva payment check out 2](https://user-images.githubusercontent.com/51369531/68798298-10f61580-064e-11ea-977d-c4db913bd471.jpg)
![viva payment check out](https://user-images.githubusercontent.com/51369531/68798299-10f61580-064e-11ea-8a67-85aa831b05ec.jpg)
![viva payment check out 3](https://user-images.githubusercontent.com/51369531/68798531-7c3fe780-064e-11ea-88ca-24c7a34ba827.jpg)
![viva payment check out 4](https://user-images.githubusercontent.com/51369531/68798532-7c3fe780-064e-11ea-9943-e6995d764d14.jpg)

**Comment by alexbk31** [comment]
were having same issue with a magento 2.3.3 on a separate website

**Comment by alexbk31** [comment]
@matthewrgourd  any one eles having this issue its happening on 2 of my clients website m2.2.6 & m2.3.3

**Comment by VivaWalletSupport** [comment]
Hello, please check if the problem occurs when using a vanilla Magento installation (with checkout customizations).
