### ISSUE TITLE
401 submiting /nativecheckout/v2/transactions

### ISSUE THREAD

**Issue by Earthnat** [VivaPayments/API#1209]
We're getting 401 when submiting the transaction confirmation with chargeToken from our server side as showed on https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-5-make-the-actual-charge

It seems all is working up to this last step. 

We tried by adding the "Authorization Basic auth" header we used to obtain the OAuth token but without success.

What kind of authorization process is executing /nativecheckout/v2/transactions to return 401?

Thanks for advance

**Comment by matthewrgourd** [comment]
Hi @Earthnat you need to user the time-limited bearer token generated in [Step 2](https://developer.vivawallet.com/authentication/#step-2-request-access-token) of the OAuth 2 token generation procedure. Set the auth to type to 'bearer'. Hope this helps! If not I'll investigate further.

**Comment by aiosifelis** [comment]
Thanks @matthewrgourd  this solution worked for me. I was getting a 401 Unauthorized.
Is changed my PHP code into this
`curl_setopt($session, CURLOPT_HTTPHEADER, array('Authorization: Bearer '.$access_token));`
However after I passed he 401 error, I'm getting a `415 Unsupported Media Type` http error.

HTTP\/1.1 415 Unsupported Media Type\r\nServer: nginx\r\nDate: Fri, 15 Nov 2019 04:55:30 GMT\r\nContent-Length: 0\r\nConnection: keep-alive\r\nX-Viva-CorrelationId: 19-319-9C22FF88\r\n\r\n","exception":"Unsupported Media Type

Any thoughts?

**Comment by matthewrgourd** [comment]
Hi @aiosifelis Have you tried passing "Content-Type: application/json" in the header?

**Comment by aiosifelis** [comment]
Yes the content-type header is present in the request. Please let me know if we should continue here or open a new issue. 
Thanks for your reply.

**Comment by aiosifelis** [comment]
@matthewrgourd my issue with the `415` HTTP error was resolved. For some reason I had the configuration for http headers twice in my code and the `Content-Type: application/json` was not being sent.(as you suggested). 
Thank you.
