### ISSUE TITLE
Βοήθεια σχετικά με την ενσωμάτωση του viva wallet

### ISSUE THREAD

**Issue by crisxz** [VivaPayments/API#121]
Καλησπέρα,

Έχω ένα website shop το οποίο είναι γραμμένο με html και javascript και θέλω να ενσωματώσω το viva wallet. Αυτό που δεν καταλαβαίνω είναι πως υλοποιώ το 2 βήμα. 

Δηλαδή έχω βάλει το κουμπί και έχω ορίσει public key και τις παραμέτρους, αλλά δεν καταλαβαίνω που πρέπει να μπει ο κώδικας από το 2ο βήμα και αν πρέπει να αλλάξω κάτι.

Η γνώσεις μου πάνω στο προγραμματισμό είναι μηδαμινές :P οπότε αν υπάρχει η περίπτωση να με καθοδηγήσετε βήμα βήμα θα με βοηθούσατε πάρα πολύ.

Ευχαριστώ

**Comment by defilerc** [comment]
Καλησπέρα @crisxz,

Για την υποστήριξη πληρωμών από το site σας, θα πρέπει εκτός από html/javascript να χρησιμοποιηθεί και server-side κώδικας, ο οποίος θα κάνει την διεκπεραίωση της πληρωμής σε συνεργασία με τη Viva.

Για παραδείγματα σε διάφορες γλώσσες στις οποίες μπορεί να γίνει η υλοποίηση, μπορείτε να δείτε στη σελίδα: https://github.com/VivaPayments/API/tree/master/CreateOrder

Ευχαριστούμε για την επικοινωνία

**Comment by crisxz** [comment]
Καλησπέρα,

Εχω προσαρμόσει το create order (από τα δείγματα), με βάση τα δικά μου στοιχεία και δουλεύει τέλεια στο demo. 

και έχω 3 ερωτήσεις να σας κάνω.
1) επείδη το checkout στο website που θέλω να φτιάξω είναι single page (το website σας υπενθυμίζω είναι html/javascript) έχω δηλώσει στο create order αρχείο να κάνει απευθείας redirect αν δεν βρει λάθος (αντί να ζητάει να ξαναπατήσει το κουμπί για να κάνει την πληρωμή). Υπάρχει περίπτωση να υπάρξει κάποιο πρόβλημα αργότερα;
και 2) όταν γίνεται redirect στην σελίδα για να πληρώσεις με κάρτα δεν υπάρχει κάποιο link/επιλογή στο πελάτη για να ακυρώσει την παραγγελία, πρέπει να κάνω κάτι εγώ για να εμφανιστεί;

τέλος, 3) υπάρχει κάποια σελίδα παράδειγμα για το πως είναι το "DELETE /api/orders/{id} - Cancel an existing Payment Order." που πρέπει να βάλω, όπως αναφέρεται στο 1ο βήμα της σελίδας "Redirect Checkout" και με τί πρέπει να συνδεθεί;

**Comment by defilerc** [comment]
Καλησπέρα @crisxz ,

1. Θα πρέπει να διευκρινήσουμε σε ποιά μέθοδο αναφέρεστε. Redirect μετά την πληρωμή, γίνεται μόνο στην περίπτωση που προσπαθείτε να κάνετε integrate με τη μέθοδο "Redirect Checkout". Μπορείτε να μας επιβεβαιώσετε ότι αναφέρεστε σε αυτή τη μέθοδο (οι μέθοδοι αναφέρονται στη σελίδα https://github.com/VivaPayments/API/wiki στην ενότητα "Website Checkout") ; 

Αν όντως χρησιμοποιείτε αυτή την περίπτωση, τότε η διαδικασία είναι ως εξής: κάνετε πρώτα create order, στέλνετε το χρήστη στη σελίδα της Viva Payments για την πληρωμή και στη συνέχεια ο χρήστης ανακατευθύνεται από τη σελίδα της Viva πίσω στο site σας, ανάλογα με το status της πληρωμής (sucess/fail). Τα URLs μπορείτε να τα ορίσετε από το εντός login περιβάλλον του εμπόρου. 

Σε αυτή την περίπτωση και αν ο χρήστης έχει κάνει την πληρωμή επιτυχώς, δεν μπορεί να υπάρξει κάποιο πρόβλημα αργότερα όπως αναφέρετε.

2. Όταν ο χρήστης γίνεται redirect στη Viva για την πληρωμή, δεν υπάρχει κάποιο κουμπί για ακύρωση της πληρωμής, καθώς η συμπεριφορά αυτού του κουμπιού δε θα είχε κάποιο νοήμα στο συγκεκριμένο βήμα. Σε αυτή την περίπτωση ο χρήστης θα πρέπει απλά να κλείσει τη σελίδα που του έχει εμφανιστεί.

3. Παράδειγμα για την ακύρωση κάποιας πληρωμής, μπορείτε να βρείτε εδώ: https://github.com/VivaPayments/API/wiki/CancelOrder . Αυτό αφορά την ακύρωση κάποιας πληρωμής σε εκκρεμότητα, καθώς μόνο αυτές μπορούν να ακυρωθούν.

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by crisxz** [comment]
Γεια σου και πάλι @defilerc ,

Όντως κάνω χρήση του redirect checkout για την πληρωμή.

Νομίζω με κάλυψες μέχρι ένα σημείο, οπότε για να δω αν κατάλαβα καλά δεν χρειάζεται να κάνω χρήση του "DELETE /api/orders/{id} - Cancel an existing Payment Order. " που αναφέρεται στη σελίδα σελίδα "Redirect Checkout" στο πρώτο βήμα, σωστά; Σε περίπτωση που κάνει κάποιος πληρωμή με viva και δεν την ολοκληρώσει, τότε ο κωδικός πληρωμής δεν ισχύει διαγράφεται από μόνος του.

Την ακύρωση πληρωμής μπορώ να την κάνω και μέσω της διαχείρης του viva wallet ή πρέπει να δημιουργήσω ένα CancelOrder αρχείο;

Ευχαριστώ πολύ για τον χρόνο σου, νομίζω δεν θα έχω άλλες ερωτήσεις προς το παρόν :P

**Comment by defilerc** [comment]
Καλησπέρα @crisxz ,

Σωστά, δε θα χρειαστεί να γίνει cancel κάποιο order, αν ο πελάτης μεταφερθεί στη redirect checkout και αποφασίσει πως δε θέλει να πληρώσει (π.χ. κλείσει τη σελίδα). Το order δε θα γίνει cancel, αλλά expire από μόνο του.

Cancel order μπορεί να γίνει μόνο με κλήση μέσω του Viva Payments API κα θα πρέπει να γίνετε μόνο στις περιπτώσεις που κρίνεται από τον έμπορο ότι δε θέλει να πληρωθεί για ένα order (π.χ. ο πελάτης ακυρώνει μια υπάρχουσα παραγγελία).

Μέσα από το site μπορεί να γίνει μόνο ο αντιλογισμός ενός επιτυχούς transaction (void/refund ώστε να μη χρεωθεί ο πελάτης ή να του επιστραφούν τα λεφτά, αντίστοιχα).

Ελπίζω να βοήθησαν τα παραπάνω,
