### ISSUE TITLE
Incorrect order total is passed to Viva payments from Magento 2 store with multiple currencies

### ISSUE THREAD

**Issue by Ddcdom** [VivaPayments/API#1212]
The order total passed to Viva for authorisation from the Magento 2.3 plugin is GrandTotal, not BaseGrandTotal. GrandTotal is the value in the store's display currency, not the store's base currency.

I've created pull request #1211 to fix this issue. Please note these changes are untested.

**Comment by VivaWalletSupport** [comment]
Thank you for bringing this up. For your situation this modification might work (to always use the stores default currency). In a preferred setup, using various currencies with various Viva accounts, this mod will be a problem.
