### ISSUE TITLE
How to translate Native/Pay avec Viva Wallet Checkout

### ISSUE THREAD

**Issue by yummyweed** [VivaPayments/API#1213]
Hi,

The default language of my website is french.
When customers arrive on the payment page, they arrive on a page in English.
How can my clients automatically arrive on the French payment form?
My integration method is : Redirection/Native Checkout v2
Thank you in advance for your help.

Olivier

**Comment by matthewrgourd** [comment]
Hi @yummyweed, sorry, can I just confirm that you've used the instructions from our [Native Checkout v2 guide](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) to complete this implementation?

**Comment by matthewrgourd** [comment]
Closing issue as no recent updates...
