### ISSUE TITLE
Integration with other payment gateways

### ISSUE THREAD

**Issue by ijonts** [VivaPayments/API#1214]
Can I integrate Viva with any of these gateways?

![image](https://user-images.githubusercontent.com/55828844/69008043-9d565000-094e-11ea-9045-c30b93be47ef.png)
![Screenshot_4](https://user-images.githubusercontent.com/55828844/69008058-bc54e200-094e-11ea-863f-efa178e18b51.png)

**Comment by matthewrgourd** [comment]
Hi @ijonts not all of these are payment gateways. In general, the way our proposition works is if you integrate with an e-commerce platform using one of our pre-written [plugins](https://developer.vivawallet.com/e-commerce-plugins/). Alternatively, you may wish to create a custom solution using our [Native Checkout](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) or [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/). Most of the above are payment gateways in their own right and you wouldn't be able to use Viva Wallet in tandem with them.
