### ISSUE TITLE
If transaction is error, how can i get error message

### ISSUE THREAD

**Issue by xiaoyao929** [VivaPayments/API#1215]
I have a trade, it's payment order stateId = 0, means "pending" ,  it's transaction status is "E", means "The transaction was not completed because of an error",   two questions
1. why transaction is error but payment order is pending?
2. how can i know the exactly reason or message about this error? i can't find some flag about this error, such as error code or error msg from the response about retrieve this transactions

**Comment by matthewrgourd** [comment]
Hi @xiaoyao929 there is a page on the developer portal with some of the info you require: https://developer.vivawallet.com/api-reference-guide/payment-api/transaction-parameters/ . However, I see that you need more detail. I will flag that as something we should look at.

**Comment by xiaoyao929** [comment]
> Hi @xiaoyao929 there is a page on the developer portal with some of the info you require: https://developer.vivawallet.com/api-reference-guide/payment-api/transaction-parameters/ . However, I see that you need more detail. I will flag that as something we should look at.

you didn't solved my question,  when customer has a failed transaction,  we can't know the exactly reason for this failed transaction, such as his card bank hold his transaction etc.
