### ISSUE TITLE
In your doc, default expired time is 300 seconds, but the order we created , ExpirationDate is 125 minutes, why?

### ISSUE THREAD

**Issue by freeskyala** [VivaPayments/API#1216]
we get order from your getOrder interface (https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1orders~1{OrderCode}/get)
the response is :
	"ExpirationDate": "2019-11-16 17:33:15.573",
	"StateId": 1,
we have some question:  
1. In your doc, default expired time is 300 seconds, but the order we created , ExpirationDate is 125 minutes, why?

**Comment by matthewrgourd** [comment]
Hi @freeskyala sorry to hear you've been experiencing issues. In order to investigate further, our ev team needs a bit more info. If possible, would you be able to send through the `CorrelationId`? Thanks!

**Comment by matthewrgourd** [comment]
@freeskyala as I've not heard from you I'm closing this issue. Please feel free to reopen if it's still a problem.
