### ISSUE TITLE
Submerchant id for VivaPayment for Marketplace

### ISSUE THREAD

**Issue by rigasp** [VivaPayments/API#1217]
I would like to understand the fit for Viva Wallet for the **marketplace** solution I have in mind. 

We want to enable a marketplace where every submerchant can have his own account and be able to sell some items and then receive payments. We would like the submerchant to be able to input some parameter in our marketplace e.g. a wallet id and then we will enable him to receive payments. 

For example with paypal we want him to be able to enter his paypal email or paypal id and our checkout process will allow redirect to the paypal site and the payment will be transferred straight from the end customer to the merchant account without us being involved in the transaction - we act as a marketplace that facilitates the transaction. 

Would it be possible that a merchant in our platform puts a viva wallet id and potentially some other parameters and we can enable payments to him? In this case what parameters do we need to know for each merchant so that we can support him? Ideally we would like something very simple (like the paypal email) that the customer can find easily in his Viva Wallet account and copy paste it. 

It's a bit more complex this market place example than the standard payment use cases that there are on your website that's why it is difficult for me to see if it works. Thank you for your support.

**Comment by matthewrgourd** [comment]
Hi @rigasp what you describe sounds like a highly customised solution which I'm afraid we wouldn't be able to advise on. Our supported solutions for e-commerce are documented in our [developer portal](https://developer.vivawallet.com/). Anything beyond that is necessarily out of scope.
