### ISSUE TITLE
3DS Demo simulate failed response always returns a success

### ISSUE THREAD

**Issue by pmatsinopoulos** [VivaPayments/API#1218]
I am trying develop the unhappy path of authentication failure. While working with my demo account, on the following screen:

<img width="1141" alt="simulate-failied-payments" src="https://user-images.githubusercontent.com/898286/69123137-45802c00-0aa9-11ea-8981-6ebc668d7d52.png">

I select "Fail" and then "Confirm Payment" but what I get back in the `done()` of the `requestToken()` is a `response` that does not have an `Error`. It has a charge token, like if I had selected `Success` in the authentication.

What am I doing wrong?

**Comment by matthewrgourd** [comment]
Hi @pmatsinopoulos I'm not sure what's going on here. @dpnevmatikos would you be able to help?

**Comment by pmatsinopoulos** [comment]
I have continue working on that, and it seems that the error is taken into account AFTER we try to use the charge token returned in the `Fail` case. Otherwise, both `Success` and `Fail` return a charge token, normally. But the `Fail` case will not allow to later on use it create a transaction. So, I am ok for now. Maybe it is good to be added to the documentation.

**Comment by matthewrgourd** [comment]
Hi @pmatsinopoulos thanks for the update. I will make a note about the documentation update.
