### ISSUE TITLE
problem with wordpress at the time of payment.

### ISSUE THREAD

**Issue by cerbere83** [VivaPayments/API#1219]
Hello,
I would like some help to install the vivawallet payment method on Wordpress.
When one arrives at the time of paying I am redirected to a message "404 - File or directory not found. "

can you help me solve the problem if you like?

cordially Loïc.

**Comment by matthewrgourd** [comment]
Hi @cerbere83 which e-commerce platform are you using with Wordpress, WooCommerce, WP e-Commerce or Jigoshop? If it's a custom installation, please send through screenshots of any request / response logs you may have.

**Comment by cerbere83** [comment]
![61FF685F-FAA5-40D8-9645-843E7D7EAE0C](https://user-images.githubusercontent.com/57753733/69171706-c1f02a80-0afc-11ea-9817-57bae8458cdd.jpeg)
![8068410C-6062-467F-BCCD-15FF6928C796](https://user-images.githubusercontent.com/57753733/69171707-c1f02a80-0afc-11ea-8a2d-8acdc0179e87.png)
![04460A37-F0DD-4856-91F8-6F9AF461A661](https://user-images.githubusercontent.com/57753733/69171708-c1f02a80-0afc-11ea-9978-face6bb0fdbf.png)
![805247D6-4DA6-446F-A297-5B50211B8BEB](https://user-images.githubusercontent.com/57753733/69171709-c1f02a80-0afc-11ea-8550-9cc4fa6fb144.jpeg)
![17F0F329-8A8A-4D9C-930F-DD001264966D](https://user-images.githubusercontent.com/57753733/69171711-c288c100-0afc-11ea-976e-1b3c6ca5d20a.png)
![1A9EA74B-F4EE-419E-A394-E7D515EABB56](https://user-images.githubusercontent.com/57753733/69171712-c288c100-0afc-11ea-9027-5adf39f9f7a2.jpeg)

I use WooCommerce .

**Comment by matthewrgourd** [comment]
Hi @cerbere83, thanks for confirming that. Could you also let me know if you're using our official plugin, i.e. you downloaded it from our developer portal [WooCommerce page](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/)?

**Comment by cerbere83** [comment]
Yes and yes .

**Comment by matthewrgourd** [comment]
Hi @VivaWalletSupport can you shed any light? Thanks.

**Comment by cerbere83** [comment]
@VivaWalletSupport Thanks .

**Comment by VivaWalletSupport** [comment]
@cerbere83 according the screenshots you are not using the supported plugin, please contact the plugin developer for any support or follow the leads from @matthewrgourd

**Comment by cerbere83** [comment]
@VivaWalletSupport I use the plugin supported.
VivaPayment woocommerce payment gateway

**Comment by cerbere83** [comment]
![image](https://user-images.githubusercontent.com/57753733/69322657-9167d800-0c45-11ea-9fad-e94b85c25499.jpg)

**Comment by cerbere83** [comment]
![image](https://user-images.githubusercontent.com/57753733/69323003-2a96ee80-0c46-11ea-9f46-57c8f6d1232b.jpg)

**Comment by cerbere83** [comment]
@VivaWalletSupport @matthewrgourd 
I use the first of two because if I activate the other an error message arrives.

**Comment by cerbere83** [comment]
![image](https://user-images.githubusercontent.com/57753733/69323163-7b0e4c00-0c46-11ea-9d1f-c5509222b153.jpg)

**Comment by matthewrgourd** [comment]
Hi @cerbere83 our plugin developer has confirmed that you're not using our official plugin so unfortunately we can't offer any support. Feel free to remove the one you're using and download the [Viva Wallet ZIP file](https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip), following [these instructions](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) to install. Thanks!

**Comment by cerbere83** [comment]
That work . Thanks so much
