### ISSUE TITLE
Customer Login to Viva Wallet with Redirect Checkout

### ISSUE THREAD

**Issue by paulfeakins** [VivaPayments/API#1220]
If we have used the Redirect Checkout method, is it possible for a customer to pay with a stored card in their account rather than re-enter card details? Or must we use the Simple Checkout method for that?

**Comment by matthewrgourd** [comment]
Hi there, I'm finding out for you. Thanks!

**Comment by matthewrgourd** [comment]
Hi @paulfeakins do you mean accept a payment from a stored account on Viva Wallet or a card payment on your (customer's) platform? If you wish to implement recurring card payments (save card at checkout), simply set optional `AllowRecurring` parameter during [Create payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1orders/post) call. This will make a consent checkbox appear on the checkout page. The purchaser checks the box if they agree to let the merchant save their card for future payments. If a transaction was completed with consent provided by the purchaser, then merchant can use [Create transaction](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1transactions~1{Id}/post) to make subsequent charges to the same card. Hope that helps!

**Comment by paulfeakins** [comment]
Thanks for the reply @matthewrgourd. But not quite what I mean. Imagine a customer already has a Viva Wallet account with a stored card or credit. When they use the integration we have developed they get to the Viva screen where they can enter a card ... but there is nowhere for them to login to Viva and use a card they may have stored previously. Does that make more sense?

**Comment by matthewrgourd** [comment]
Hi Paul, I'm afraid for this method to work you'd need to use [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/) if your account is not Greek. This is because we have disabled it on Redirect checkout for customers based outside Greece where our company originates.

**Comment by paulfeakins** [comment]
Thanks that does answer the question.
