### ISSUE TITLE
Need to change company name in redirect payment page

### ISSUE THREAD

**Issue by adamianos** [VivaPayments/API#1221]
Hi
We need to replace the legal company name shown on the redirect method payment page, with the brand name, because we get a lot of questions and abandoned payments.

Can you please tell us how to proceed?

**Comment by matthewrgourd** [comment]
Hi @adamianos please email your Merchant ID to mgourd@vivawallet.com together with the brand name which should be shown instead of the legal company name. Thanks!

**Comment by matthewrgourd** [comment]
Hi @adamianos as I've not heard from you I'm closing this issue.
