### ISSUE TITLE
only ACCEPTING EURO CURRENCY

### ISSUE THREAD

**Issue by josepaoun** [VivaPayments/API#1222]
We are a new merchant online store we have implement VIVA PAYMENTS API on Prestashop. all work well when user pay with Euro based card but if the user has payment card other than EURO (any local currency) it fails on the payment process.

**Comment by VivaWalletSupport** [comment]
At the moment you can only accept payments in the same currency as set in your Viva account.

**Comment by josepaoun** [comment]
if what you are saying is true then why the same cardholder of a NON EURO
Mastercard can pay no problem directly on my Viva account when i send him a
payment notification via email?
