### ISSUE TITLE
Besoin d'aide pour intégration Viva Wallet sur mon e-shop

### ISSUE THREAD

**Issue by WeedStock** [VivaPayments/API#1223]
Bonjour à tous,

J'ai besoin de votre aide ! Je dois intégrer Viva Wallet (module de paiement en carte bancaire) à mon e-shop mais je ne sais absolument pas comment faire. Mon site est hébergé chez Wix. Je n'ai aucune notion de codage. Pouvez-vous m'aider ?

J'ai déjà enregistré mon site sur Viva Wallet. Il est approuvé et actif. Je dois maintenant intervenir depuis mon site Wix et c'est là que j'ignore comment faire. J'ai un accès "développeur" (Corvid) mais je ne sais pas m'en servir. Pouvez-vous m'aider ??

**Comment by matthewrgourd** [comment]
Hi there, I'm afraid we don't currently have available an off-the-shelf plugin for Wix. As regards a custom solution, we can't advise on that apart from directing you to our [developer portal](https://developer.vivawallet.com/) for use as a technical reference. Thanks!
