### ISSUE TITLE
Webhook not working on the account for our new woocommerce website

### ISSUE THREAD

**Issue by Joshualtbaker** [VivaPayments/API#1224]
We are trying to add a new Payment app to our account, doing so it's saying we are required to set up a Webhook, this isn't working as it's coming up with invalid domain/dns

**Comment by matthewrgourd** [comment]
Hi there, are you using the [official plugin for WooCommerce](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/)? The instructions and download are available here:   Please check this first and get back to me if you're still experiencing issues.
