### ISSUE TITLE
backend payment 

### ISSUE THREAD

**Issue by LeoTravel** [VivaPayments/API#1225]
i have to try find a solution for integrate vivawallet with an existing system.

i've all my customers credit card stored, we want to create a really clean payment flow, like amazon.

when the customer want to check out, in our backend we have to take the selected cc and pay with that, is it possible?

**Comment by LeoTravel** [comment]
any news about?

**Comment by matthewrgourd** [comment]
@LeoTravel sounds like you want to store customer credit card information, is that correct?

**Comment by LeoTravel** [comment]
yes, we have already stored that info, could we use that info for pay? we don't wanna have the customer that write his cc everytime

**Comment by matthewrgourd** [comment]
Hi @LeoTravel I'm afraid it wouldn't be possible to re-use previously stored credit card information unless it has been entered into Viva Wallet systems already by customers via our payment gateway.

**Comment by matthewrgourd** [comment]
Hi @LeoTravel correct: I'm told by one of our technical team that you can in fact do this although it requires some manual processes at this end. What you'd need to do in the first instance is contact your existing provider mentioning that you want to move to us and that we are PCI compliant. An example would be if you currently use Stripe and wish to move to Viva Wallet, you first need to approach them to migrate your data: https://support.stripe.com/questions/export-customer-card-data-from-stripe  Once you've looked at how this is done (with your actual provider not Stripe) please let us know and we'll let you know an email address where you can speak to one of our development team to proceed to the next step of the process. Hope that helps! Thanks.

**Comment by LeoTravel** [comment]
Ok that could be really awesome for us, could you provide the api calls about?
We have the credit card number in clear, but in secure api with our flight provider. So is possible in backend create the token card and pay with it? Could you provide the api calls about? sorry but I haven’t understand if we could do that without the customer have to write the number, with just backend code

Anyway could we talk about in email?

**Comment by matthewrgourd** [comment]
Hi @LeoTravel I'm not sure what you mean exactly. I have already given quite a full answer. Let me know if I've made any incorrect assumptions and I'll reply again. To start, perhaps you could confirm the name of your existing payment provider? Thanks.

**Comment by LeoTravel** [comment]
Could we talk via email?

**Comment by matthewrgourd** [comment]
Hi @LeoTravel feel free to myself on mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
Closing as in discussion by email.
