### ISSUE TITLE
nativecheckout/v2/transactions

### ISSUE THREAD

**Issue by johnpaizis** [VivaPayments/API#1226]
In demo all ok, but in real account I get the
{"status":405,"message":"Action blocked due to security policy","eventId":"0"}

What is the problem?

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear that. Please email mgourd@vivawallet.com with your Merchant ID referencing this issue and I'll look into it.

**Comment by matthewrgourd** [comment]
Hi there, I've changed one of your settings, can you try again?

**Comment by johnpaizis** [comment]
Nothing changed, exactly the same message!

Παραθέτοντας από matthewrgourd <notifications@github.com>:

**Comment by johnpaizis** [comment]
Still have a problem, can you help?

**Comment by matthewrgourd** [comment]
Hi @johnpaizis I've changed another of your settings, can you try again?

**Comment by johnpaizis** [comment]
ok, fixed. what was the problem?

**Comment by matthewrgourd** [comment]
I had to enable Native Checkout for you!
