### ISSUE TITLE
Viva Payments "No order placed after payment"

### ISSUE THREAD

**Issue by OptimalFurion** [VivaPayments/API#1227]
Hello Can Someone Please Help

Open Cart Version 2.1.0.2

I have an issue on my website with the vivapayments module. Attached you will find the .jpg file which is completed with the proper parameteres. When the client chooses to pay with credit/debit card and it redirects to the native checkout of Vivawallet the charge is done but the order is not placed. As a result we see the payments but we can't see the order.

I have Followed the https://developer.vivawallet.com/e-commerce-plugins/ and everything works apart from not posting an order on our website.
![CBD UK Payment](https://user-images.githubusercontent.com/58035097/69349147-31862700-0c6f-11ea-93e1-bd2b7ac48f21.PNG)

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear that. I don't see a jpg. Can you reattach?

**Comment by OptimalFurion** [comment]
Thank you i have re attached.

**Comment by VivaWalletSupport** [comment]
Hello, you did not specify the source code in the extension settings, please follow the instructions to the letter https://developer.vivawallet.com/e-commerce-plugins/opencart2-2.2/
