### ISSUE TITLE
Incorrect order total is passed to Viva payments from Magento 2 store with multiple currencies

### ISSUE THREAD

**Issue by Ddcdom** [VivaPayments/API#1228]
I opened issue https://github.com/VivaPayments/API/issues/1212 and provided a fix in pull request https://github.com/VivaPayments/API/pull/1211, but the issue has been closed, incorrectly in my opinion.

The problem is in file Plugins/magento/magento23_vivawallet/Ced/VivaPayments/Model/PaymentMethods.php

On lines 91 and 92 the order total is obtained using the` $order->getGrandTotal()` method. This method will return the order total in the _display currency_. Then on line 102, the currency code is obtained using `$order->getBaseCurrencyCode()`, which returns the stores _base currency_ code.

If the store's base currency is set to EUR, but a customer has checked out with the display currency of USD, then the order value in USD will be sent to Viva for processing along with the EUR currency code, resulting in the customer being charged the incorrect amount.

The update to issue https://github.com/VivaPayments/API/issues/1212 from @VivaWalletSupport suggests that the preferred set up would use various currencies with various Viva accounts. This answer misunderstands the purpose of Magento's display currency and it also would not work with Viva's current plugin code.

Magento 2 has a display currency to allow customers to browse the store and be shown an invoice in their preferred currency, but at check out they will be charged the correctly converted value in the base currency.

Currently, getting the currency code from the base and the total from display will mean that your Magento plugin code can only work when there is one display currency and that currency is the same as the base, otherwise you code will always charge the incorrect amount.

When I last asked, Viva wallet wouldn't allow an account to have multiple currencies. If as you're last update suggested you'd need multiple viva accounts, each with a different currency, then your code would not support this. The magento 2 plugin can only accept a single merchant ID and password, so you could not use different Viva accounts based on the currency selected.

The fix in my pull request doesn't break anything, as you're code wouldn't work in the way you've suggest and it fixes the problem I've raised. Please can you review it again and let me know.

**Comment by matthewrgourd** [comment]
Hi @Ddcdom, sorry for closing your previous issue but our plugin developer has replied implying that the code changes wouldn't necessarily be appropriate. @VivaWalletSupport can you confirm that you do not wish to proceed with the merge?

**Comment by Ddcdom** [comment]
@matthewrgourd I think your plugin developer is mistaken in their understanding of M2's display currency.

Please can you ask your developer to read through the issue above. If there are any questions, then please can you ask them to raise them here and let me respond before closing the ticket.

**Comment by matthewrgourd** [comment]
Hi @VivaWalletSupport, when you have a spare moment, please provide further feedback regarding the suggested merge.

**Comment by Ddcdom** [comment]
Hi @matthewrgourd just wondering if you had an update on this issue?

**Comment by matthewrgourd** [comment]
Hi @Ddcdom we're currently in a transition period between plugin developers but I'll make a note to add this to the roadmap for early 2020. Thanks!
