### ISSUE TITLE
Issue Switching from Demo Environment to Production Environment

### ISSUE THREAD

**Issue by adamstacey** [VivaPayments/API#1229]
Hello,

We’re in the middle of switching from the demo environment to production and we’re bumping into an issue we haven’t had on any previous Viva integrations.

We’re using Simple Checkout and our call to https://www.vivapayments.com/api/cards?key=OUR_PUBLIC_KEY fails with:

> 401 The specified api action is disabled, please consult the documentation

We’re posting the following as we have with others in the past:

```
Number: 4xxxxxxxxxxxxxxx
CVC: 123
ExpirationDate: 2020-01-01
CardHolderName: Card Holder
```
We’ve spoken to our account manager and they’ve said our account has been verified.

We see:

> The verification of your account has been completed. You are ready to use all our services.

and:

> Source OUR_SOURCE has been approved for use

Could we get help on figuring out the issue?

Many thanks

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this, please send your Merchant ID to mgourd@vivawallet.com referencing this issue. I'll then investigate for you.

**Comment by matthewrgourd** [comment]
Hi @adamstacey thanks for sending through your Merchant ID. I've adjusted one of your settings. Can you try again for me?

**Comment by adamstacey** [comment]
Hi @matthewrgourd, that is now working. Thanks for sorting that so quickly for us.
