### ISSUE TITLE
Πρόβλημα με την επικοινωνία του Vivapeyments με το magento

### ISSUE THREAD

**Issue by nleont** [VivaPayments/API#123]
Καλησπέρα, 

Εχω κατεβάσει την εφαρμογή από το magento έχει φτιάξει της ρυθμίσεις αλλά δεν παίζει βγάζει not response και ότι δεν υπάρχουν προιοντα, ενώ αν φτιάξω ένα demo λογαριασμό  από το demo.vivapayments και βάλω εκείνες τις ρυθμίσεις (τις ίδιες δηλ) δουλεύει κανονικά και περιμένει να πληρώσω κάνει δηλ redirect μπορείτε να μου πείτε πως μπορώ να κάνω το magento να δουλευει με την εφαρμογή του VivaPayments ή αν δεν υπάρχει τρόπος να συνδεθεί απλά ενημερώστε με να το συνδέσω με άλλους τρόπους πληρωμής 

Ευχαριστώ πολύ για τον χρόνο σας

**Comment by defilerc** [comment]
Καλησπέρα @nleont ,

Αν χρησιμοποιείται κάποιο εξωτερικό plugin για τη διασύνδεσή σας με τη Viva Payments, όπως αυτό του magento που μας αναφέρετε, θα πρέπει να επικοινωνήσετε με το δημιουργό του για περαιτέρω οδηγίες, καθώς δεν έχει δημιουργήθει από τη Viva και δεν παρέχεται κάποια υποστήριξη γι' αυτό.

Από αυτά που μας αναφέρετε, το μόνο που μπορούμε να σας προτείνουμε είναι να έχετε ελέγξει πως για τη διασύνδεση με το παραγωγικό (live) περιβάλλον και όχι το demo, θα πρέπει να έχετε αλλάξει το URL σε https://www.vivapayments.com

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by nleont** [comment]
Καλησπέρα,

Υπάρχει κάποιο πρόγραμμα δικό σας που μπορώ να το χρησιμοποιησω στο
magento? Υπάρχει κάποια ευκολη λύση που να μπορώ να την ενσωματωσω στο
eshop?

Ευχαριστώ πολύ για την απάντηση

Στις 14 Ιουνίου 2016 - 3:54 μ.μ., ο χρήστης Kostas Athanasoglou <
notifications@github.com> έγραψε:

**Comment by defilerc** [comment]
Καλημέρα @nleont ,

Για να μπορέσετε να παίξετε στο live περιβάλλον, θα πρέπει να έχετε δημιουργήσει λογαριασμό στο https://www.vivapayments.com και να έχετε πάρει "live" merchantid, καθώς και api key. Επομένως, δε θα μπορέσετε να συνδεθείτε, χρησιμοποιώντας τις ίδιες ρυθμίσεις του demo.

Παρακαλώ πολύ ελέγξτε ότι έχετε κάνει τις απαραίτητες αλλαγές στις ρυθμίσεις και ότι το URL που χρησιμοποιείτε είναι το https://www.vivapayments.com . Αν συνεχίζετε να αντιμετωπίζεται πρόβλημα, θα χρειαστούμε κάποιο response error message, το οποίο λαμβάνετε, ώστε να μπορέσουμε να διερευνήσουμε περαιτέρω.

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by nleont** [comment]
καλημέρα,

Τα έχω κάνει όλα αυτά που λέτε και δεν δουλεύει. Γενικά πιστευώ ότι θα
πρέπει να είχατε κάποια εφαρμογή όπως έχει το paypal και να μπορούμε να το
συνδεσουμε.

Αν έχετε κάποια λύση για το magento να βοηθήσετε ευχαριστώς αλλιώς λυπάμαι
αλλά θα ακυρώσουμε το λογαριασμό και θα πάμε σε κάποια άλλη λύση

Ευχαριστώ πολύ για το χρόνο σας

Στις 16 Ιουνίου 2016 - 11:39 π.μ., ο χρήστης Kostas Athanasoglou <
notifications@github.com> έγραψε:

**Comment by defilerc** [comment]
Καλησπέρα @nleont ,

Για να μπορέσουμε να σας βοηθήσουμε, θα πρέπει να μας στείλετε ακριβώς τα responses που παίρνετε, καθώς και τα requests που στέλνονται προς το API της Viva Payments, ώστε να μπορέσουμε να βρούμε κάποια λύση.

Αν αυτό γίνεται μέσω κάποιου εξωτερικού plugin, όπως στην περίπτωσή σας, θα πρέπει ίσως να αναζητήσετε τη βοήθεια του δημιουργού για να μπορέσετε να εντοπίσετε που καταγράφονται.

Ευχαριστούμε πολύ για την επικοινωνία.
