### ISSUE TITLE
Error : unsupported_grant_type

### ISSUE THREAD

**Issue by safwen1** [VivaPayments/API#1231]
When requesting an access token on the production API, we get an error:

![Screenshot from 2019-11-22 09-38-43](https://user-images.githubusercontent.com/13918596/69410996-6bf1d180-0d0c-11ea-8839-da58193deae8.png)

And I know that the Authorization header is correct because if I change client secret to a wrong one, the error changes to "invalid_client"

**Comment by matthewrgourd** [comment]
Hi there @safwen1 sorry to hear you're experiencing problems. In Postman the easiest (and recommended) way to do this is follow the offical [OAuth2 instructions](https://learning.getpostman.com/docs/postman/sending-api-requests/authorization/#oauth-20). After following these myself, here are some screenshots to give you an idea of the expected result.

![Get new access token](https://user-images.githubusercontent.com/44943019/69424586-e9bfd800-0d20-11ea-8a7c-617744c10158.png)

![Result](https://user-images.githubusercontent.com/44943019/69424595-f04e4f80-0d20-11ea-8685-a098de7842e7.png)

Hope this helps!

**Comment by safwen1** [comment]
@matthewrgourd thank you for responding. We have successfully retrieved the access token.

Now we are trying to create a transaction using a VivaWalletToken.

So we created a call like this : 
![Screenshot from 2019-11-22 16-09-14](https://user-images.githubusercontent.com/13918596/69436880-86df3880-0d42-11ea-8351-2695502450e8.png)

and a body like this : 
![Screenshot from 2019-11-22 16-09-30](https://user-images.githubusercontent.com/13918596/69436947-a8d8bb00-0d42-11ea-9ca0-03cff5705a2c.png)

Response is 401 {
    "Message": "Authorization has been denied for this request."
}

My question is , is this the expected behaviour since we used a test virtual MasterCard (5555555555554444) ? Or are we still have problems with the HTTP request formating?

Thanks a lot

**Comment by safwen1** [comment]
@matthewrgourd Hello again, we have tested a real credit card and received the same response. What's wrong with our request?

Request info:
Headers : Authorization : Bearer [the access token received in the previous request]
JSON Data : {'PaymentToken': [the token received from the simple checkout form]}

**Comment by matthewrgourd** [comment]
Hi @safwen1 once you have generated the charge token, subsequent API calls use basic authentication based on your [Merchant ID and API Key](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/). So when you attempt to create the transaction do not use the earlier generated bearer token.

I.e.
Output from Postman (1)
![Screenshot 2019-11-25 at 10 18 42](https://user-images.githubusercontent.com/44943019/69532145-1cf6a700-0f6d-11ea-990a-12db98255594.png)

Output from Postman (2)
![Screenshot 2019-11-25 at 10 19 07](https://user-images.githubusercontent.com/44943019/69532182-326bd100-0f6d-11ea-9728-5d3cd3e60a4c.png)

**Comment by safwen1** [comment]
Hello @matthewrgourd , If I understand you correctly, we don't need to generate an access token if we are using the simple checkout.

We have changed the charge request to use Basic Auth with Merchant ID and API private key.

Request is 200 Ok but response contains this message :
'The specified api action is disabled for the merchant 5fafcd59-4060-4764-bb47-0bf3b15b02b9, please consult the documentation'

**Comment by matthewrgourd** [comment]
Hi @safwen1 yes, that's right.

I've changed one of your account settings in an attempt to prevent the error. Can you try again?

**Comment by safwen1** [comment]
Thank you @matthewrgourd you have solved the problem.
We will now wait for the demo account problem to be resolved.
