### ISSUE TITLE
merchant error or API is not working

### ISSUE THREAD

**Issue by petvar** [VivaPayments/API#1233]
After placing order in woocommerce store with viva plugin appears the message merchant error or API is not working and customer is not redirecting to fill out the card details and complete the order

**Comment by VivaWalletSupport** [comment]
Hello, in case the plugin and instructions are used from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ please provide following screenshots:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by petvar** [comment]
No, the plugin that i used is Viva Payments - Viva Wallet WooCommerce Payment Gateway.
I will follow your instructions and i will reply again.

Thank you

**Comment by matthewrgourd** [comment]
Assuming you no longer have a problem, I'm closing this issue. Feel free to reopen if not the case.
