### ISSUE TITLE
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.vivapayments.com/api/cards?key=PykZU8**********************D

### ISSUE THREAD

**Issue by Reaper1994** [VivaPayments/API#1235]
Hi im using native checkout v2 version  (everything seems to be working fine but when I'm using the live credentials) I'm getting the following error 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.vivapayments.com/api/cards?key=Pyk************Cg%3D

I have added the correct domain in the dashboard still getting this error while using the live account

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear you've been experiencing difficulties. If possible, could you send through requests / responses for you working demo instance? That way I can hopefully see where you're going wrong in the live environment.

**Comment by Reaper1994** [comment]
> Hi there, sorry to hear you've been experiencing difficulties. If possible, could you send through requests / responses for you working demo instance? That way I can hopefully see where you're going wrong in the live environment.

yes but why is cors failing when i use the live URL 
im getting the below error in the console  on chrome

Access to XMLHttpRequest at 'https://api.vivapayments.com/api/cards?key=PykZU8D3***********3D' from origin 'https://*****' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.



I have tried setting all the headers still this issue while accessing the live url

**Comment by matthewrgourd** [comment]
Hi there, you could try in Firefox instead. Alternatively, have a look at this Medium post: https://medium.com/@siddhartha.ng/disable-cross-origin-on-chrome-for-localhost-c644b131db19

**Comment by Reaper1994** [comment]
> Hi there, you could try in Firefox instead. Alternatively, have a look at this Medium post: https://medium.com/@siddhartha.ng/disable-cross-origin-on-chrome-for-localhost-c644b131db19

yes tried it in Firefox as well this is what I get 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.vivapayments.com/api/cards?key=PykZU8D3rN5f2GiOuPqCPJSn7YgFX5ahOdRd%2BWsCdCg%3D. (Reason: CORS request did not succeed)

**Comment by matthewrgourd** [comment]
Hi there can you send through some screenshots of the request / response logs if possible? How are you making the calls?

**Comment by Reaper1994** [comment]
> Hi there can you send through some screenshots of the request / response logs if possible? How are you making the calls?

hi I'm using javascript to make the calls 
attached below is the error screenshot

![cors error](https://user-images.githubusercontent.com/23649642/69600467-b8a01a00-1036-11ea-980e-5ce3da04ff55.png)

**Comment by matthewrgourd** [comment]
Hi @Reaper1994 this is a coding issue. I'm seeing if one of our developers can help, but as far as I can tell there's no problem at the Viva Wallet end.

**Comment by Reaper1994** [comment]
> Hi @Reaper1994 this is a coding issue. I'm seeing if one of our developers can help, but as far as I can tell there's no problem at the Viva Wallet end.

Hi @matthewrgourd   that seems a bit strange, it works when I use the demo credentials but when I use the live credentials I get the above message. 

do I need to whitelist my IP or something while using the production account?

Thanks

**Comment by matthewrgourd** [comment]
Hi there, one of our developers has got back to me and mentioned that you need to consult the documentation for [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/). At the moment it looks as though you've been using the Native Checkout v1 instructions. Hope this helps.

**Comment by matthewrgourd** [comment]
Hi @Reaper1994 Hope my email reply has helped. Please close this issue when you can.

**Comment by matthewrgourd** [comment]
Hi @Reaper1994 I believe you've still got problems. You mention in your latest email reply:

>I tried on several computers / browsers / phones / tablets and the error remains the same: an infinite loading time after clicking on command. 

Could you elaborate on this? What exactly do you mean? Thanks. Matt

**Comment by Reaper1994** [comment]
> Hi @Reaper1994 I believe you've still got problems. You mention in your latest email reply:
> 
> > I tried on several computers / browsers / phones / tablets and the error remains the same: an infinite loading time after clicking on command.
> 
> Could you elaborate on this? What exactly do you mean? Thanks. Matt

hi, @matthewrgourd  I guess there is some confusion with some other email thread.

actually I'm using the instructions mentioned in native checkout v2 documentation ie when I switch to the live account I get the above-mentione error

error
The Same Origin Policy disallows reading the remote resource at https://api.vivapayments.com/api/cards?key=PykZU8D3rN5f2GiOuPqCPJSn7YgFX5ahOdRd%2BWsCdCg%3D.

**Comment by matthewrgourd** [comment]
Hi @Reaper1994 reply back from our development team is that the endpoint `https://api.vivapayments.com/api/cards?key=[yourkey]` is not referred in our Native Checkout v2 documentation. If you don't want to use the [VivaPayments.js](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-2-add-a-reference-to-vivapayments-js), the steps for integrating with our platform are described here [Native Checkout v2 API](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#native-checkout-v2-api).
