### ISSUE TITLE
Magento 1.9.3 order status not updating

### ISSUE THREAD

**Issue by NTRXIT** [VivaPayments/API#1237]
Hello, I'm using the plugin from the repository on a Magento 1.9.3 setup. Everything works pretty well except for the order status update. Initially, when an order is created I have set it to have a status pending, this is fine. But when the transaction is successful the order status does not update to Processing as it is supposed to. This is quite a big issue. Can you help, please?

Thank you in advance.

@VivaWalletSupport

**Comment by VivaWalletSupport** [comment]
Hello, please send a screenshot of the extensions settings, mask the API Key.

**Comment by NTRXIT** [comment]
![image](https://user-images.githubusercontent.com/58218003/69635677-9ec5fd80-105d-11ea-8dd3-1270aa0c65ae.png)

here you are. thank you

**Comment by VivaWalletSupport** [comment]
Could you also include a screenshot of the payment source settings?

**Comment by NTRXIT** [comment]
Sure

![image](https://user-images.githubusercontent.com/58218003/69636552-85be4c00-105f-11ea-8776-f19875ad6978.png)

**Comment by VivaWalletSupport** [comment]
Please correct the success / fail URLs as instructed at https://developer.vivawallet.com/e-commerce-plugins/magento1.x/

**Comment by NTRXIT** [comment]
Is this the issue? I was wondering how I can track the goals in analytics if I have the guide URLs.

**Comment by VivaWalletSupport** [comment]
This seems to be the solution for the posted issue.

**Comment by NTRXIT** [comment]
OK thank you. It works for a canceled order. Any way I could test a successful transaction without using an actual card? Thanks a lot for your support.

**Comment by VivaWalletSupport** [comment]
You could setup the extension to work with the demo environment and use the test card.
