### ISSUE TITLE
Custom logo in demo 3DS form

### ISSUE THREAD

**Issue by adrianblynch** [VivaPayments/API#1238]
We're updating from native v1 to v2 and during development we're seeing the Viva logo on the 3DS form:
<img width="504" alt="viva-logo-3ds" src="https://user-images.githubusercontent.com/4160967/69639149-f1022100-1053-11ea-8297-2d1721f09fda.png">

We have changed the logo for the source we're using, here:
<img width="581" alt="source-logo-clear" src="https://user-images.githubusercontent.com/4160967/69639051-c617cd00-1053-11ea-99f0-bc7688aee1d5.png">

Should our logo appear on the form here?

**Comment by matthewrgourd** [comment]
Hi there, this is just to emulate 3DS during testing. It is different in production.
