### ISSUE TITLE
Merchant missing from 3DS form on demo

### ISSUE THREAD

**Issue by adrianblynch** [VivaPayments/API#1239]
Is there a way to supply data for the Merchant field on this form:
<img width="504" alt="viva-logo-3ds" src="https://user-images.githubusercontent.com/4160967/69639507-8998a100-1054-11ea-9453-d8699e35a1da.png">

This is on the test form but I guess the question applied to production when we get there too.

**Comment by matthewrgourd** [comment]
Hi there, this is just to emulate 3DS during testing. It is different in production.

**Comment by adrianblynch** [comment]
Thanks @matthewrgourd 

What value appears in _Merchant:_ field or is there no such field on the card acquirer's 3DS form?
