### ISSUE TITLE
Πρόβλημα στην Μετάβαση από το Demo στο Παραγωγικό

### ISSUE THREAD

**Issue by geomcp** [VivaPayments/API#124]
Καλημέρα σας,
Αλλάζοντας τα links για να μεταβώ από τους λογαριασμούς demo στους παραγωγικούς λογαριασμούς το object που επιστρέφεται για το Order είναι κενό. 

Τι μπορεί να συμβαίνει? 
Είμαι σίγουρος ότι τα MerchantId, Api key , url είναι  σωστά.

**Comment by defilerc** [comment]
Καλησπέρα @geomcp ,

Θα πρέπει να μας στείλετε αναλυτικά τα requests που κάνετε όπου θα φαίνεται τα εξής:

1. το Url που χρησιμοποιείται
2. το Http verb (πχ: GET, POST, DELETE)
3. οι παράμετροι που περνάτε στο request

όπως αντίστοιχα και τα requests για να μπορέσουμε να σας βοηθήσουμε περαιτέρω.

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by geomcp** [comment]
Το Request γίνεται με τον παρακάτω τρόπο

Dim cl = New RestClient(URL)     
        Dim req = New RestRequest("api/orders", Method.POST)
        ' amount is in cents
        req.AddObject(New OrderOptions() With { _
         .Amount = Ctype(transfer.TotalPrice*100, int32),  _
		 .FullName = transfer.FullName, _
		 .Email = transfer.Email, _
		 .Phone = transfer.Mobile, _
		 .MerchantTrns =transfer.PNR, _
		 .CustomerTrns="CANDIA TAXI - Ref: "+transfer.PNR, _
		 .SourceCode=sourceCode _
        })
        cl.Authenticator = New HttpBasicAuthenticator(MerchantId.ToString, Password)

Για το demo περιβάλλον που δουλεύει χρησιμοποιώ τις παρακάτω μεταβλητές
http://demo.vivapayments.com/
ενώ για το παραγωγικό το 
https://www.vivapayments.com/

**Comment by geomcp** [comment]
Το Request γίνεται με τον παρακάτω τρόπο

Dim cl = New RestClient(URL)

Dim req = New RestRequest("api/orders", Method.POST)
' amount is in cents
req.AddObject(New OrderOptions() With { _
.Amount = Ctype(transfer.TotalPrice*100, int32), _
.FullName = transfer.FullName, _
.Email = transfer.Email, _
.Phone = transfer.Mobile, _
.MerchantTrns =transfer.PNR, _
.CustomerTrns="CANDIA TAXI - Ref: "+transfer.PNR, _
.SourceCode=sourceCode _
})
cl.Authenticator = New HttpBasicAuthenticator(MerchantId.ToString, Password)

Για το demo περιβάλλον που δουλεύει χρησιμοποιώ τaURL
http://demo.vivapayments.com/
ενώ για το παραγωγικό το 
https://www.vivapayments.com/

Η εταιρεία είναι η Candia Taxi A.E

  ----- Original Message -----

**Comment by defilerc** [comment]
Καλησπέρα @geomcp ,

Θα χρειαστούμε κάποιο request με actual δεδομένα, αντί για μεταβλητές, όπως επίσης και την απάντηση που παίρνετε απο το Viva Payments API για να μπορέσουμε να σας βοηθήσουμε.

Ευχαριστούμε για την επικοινωνία

**Comment by geomcp** [comment]
Καλησπέρα 
Το πρόβλημα έχει λυθεί, χωρίς να κάνουμε τίποτα, άρα όλα είναι ΟΚ.
Μία άλλη ερώτηση τώρα:

Βάζοντας στην γλώσσα en-US η ημερομηνία στο περιβάλλον σας δίνεται στην μορφή MM/DD/YYYY. 
Μπορούμε με κάποιο τρόπο να την αλλάξουμε σε DD/MM/YYYY έχοντας Αγγλικά?

Ευχαριστώ εκ των προτέρων 
  ----- Original Message -----

**Comment by defilerc** [comment]
Καλησπέρα @geomcp ,

Η μορφή της ημερομηνίας καθορίζεται από την τιμή που έχετε ορίσει στο `RequestLang`. Αυτό γίνεται, έτσι ώστε να μην υπάρχει σύγχυση στον τρόπο που καταλαβαίνουν οι χρήστες τη μορφή της ημερομηνίας, ανάλογα με τη γλώσσα που βλέπουν.

Ευχαριστούμε πολύ για την επικοινωνία.
