### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by Barnaby-Clifton** [VivaPayments/API#1242]
Hi, I am having trouble integrating vivawallet into my website. please assist. 

greendragonstores.co.uk

**Comment by matthewrgourd** [comment]
Hi @Barnaby-Clifton have you checked our [developer portal](https://developer.vivawallet.com/)? If so, which section are you looking at. What exactly is the problem? If possible, can you send through any request / response logs? (with confidential information blurred out).

**Comment by Barnaby-Clifton** [comment]
I found the simple error! I put the URL suffix incorrectly. How long until
the changes will be approved? I'd like to run a sale tomorrow.

**Comment by Barnaby-Clifton** [comment]
can you respond to my last?

**Comment by matthewrgourd** [comment]
Can you send me your Merchant ID and I'll look into it. Email address is mgourd@vivawallet.com.

**Comment by matthewrgourd** [comment]
Thanks for that. I'm just checking with my colleague if we can expedite the process for you.

**Comment by matthewrgourd** [comment]
Hi there, I'm told by our Risk team that you should have been sent an email advising what to do next. Basically you need to have a website up and running before we can evaluate. Hope this helps!

**Comment by Barnaby-Clifton** [comment]
My website is all up and running,

**Comment by Barnaby-Clifton** [comment]
greendragonstores.co.uk

**Comment by Barnaby-Clifton** [comment]
The problem was because I put .com not .co.uk, that's probably why you
think I don't have a website.

**Comment by matthewrgourd** [comment]
Should be active in the next couple of hours if not sooner. Thanks!

**Comment by Barnaby-Clifton** [comment]
BRILLIANT
