### ISSUE TITLE
Virtual payment

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1243]
Hi team! this morning, customer "Latin Travel" asking me about these questions, can you help me?:

1 - When a payment is made it is completely necessary that these are preauthorized, ("Capture" in the image) because the core of the business so requires, however much I try to send the parameter "IsPreAuth = true or IsPreAuth = false" is not it obtains no different result in practice. The problem at the business level would be that an employee could enter the control panel to "Capture" those payments, this situation would be ineffective a service that must be "minutes".

2 - Obtain the payment information to know in which state it is processed, we would obtain the payment status, it can be "Captured", "Uncaptured" or "Canceled", however when we get the detail of the same state any indicator of the Payment is always the same (please see attached image).
That said what we would need is a reliable way of knowing that the payment has been made effective.
![captura pantalla problema latin travel](https://user-images.githubusercontent.com/56823712/69722095-8e258e00-1116-11ea-8c43-b4b2b3bc3703.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada I'm raising with one of our developers. I'll let you know when I've an outcome. Thanks!

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd, thanks mate, I keep waiting!

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, our development team has got back to me about question 1. Please see below:

>`Regarding Q1, it's not clear whether you want to continue to do preauthorizations due to the "core of the business" you mention.

>There is a difference between an authorization and a preauthorization. During the authorization card charges occur instantly while a 
preauthorization is a promise for a later charge and need to be captured (immediately or at a later time). 

>You can filter sale transactions grid by clicking the *Advanced search* panel and modifying the **Remarks** multi select with the desired statuses.

>If you wish to continue to do preauthorizations, then the 'Capture action' cannot be avoided. In order to do a successful preauthorization you need to pass `IsPreAuth=True` and `PaymentMethod=1` in the create transaction endpoint.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd, my client still has two questions about the above:

Q1: Is there any possibility that as soon as the transaction is made the card will be charged and that it is not necessary to enter the control panel to "Capture" the payment?
Q2: Please give me an answer or I will have no choice but to recommend suspending operations again because we do not know if the payment is really valid or not.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd Do you know something about I told you the last time?

Thanks mate.

**Comment by konsP** [comment]
Hello @Alvaroalconada, 

Regarding your first question, as @matthewrgourd  has already mentioned "During the authorization card charges occur instantly". So you basically charge the cards instantly and there is no need to do a "Capture" from within your merchant environment. 
You can do this by setting `IsPreAuth=False` option.

Hope this helps ;)

**Comment by Alvaroalconada** [comment]
@konsP Thanks for the answer. What about the second question?

**Comment by konsP** [comment]
Hi @Alvaroalconada, 
I am not entirely sure what Q2 regards. "we do not know if the payment is really valid or not."  Care to clarify? 

The payment (using the above method) will appear in the merchant's transaction grid as "Card charge".

**Comment by Alvaroalconada** [comment]
Hi @konsP I mean this description about Q2:
Obtain the payment information to know in which state it is processed, we would obtain the payment status, it can be "Captured", "Uncaptured" or "Canceled", however when we get the detail of the same state any indicator of the Payment is always the same (please see attached image).
That said what we would need is a reliable way of knowing that the payment has been made effective.

**Comment by Alvaroalconada** [comment]
Hi @konsP I mean this description about Q2:
Obtain the payment information to know in which state it is processed, we would obtain the payment status, it can be "Captured", "Uncaptured" or "Canceled", however when we get the detail of the same state any indicator of the Payment is always the same (please see attached image).
That said what we would need is a reliable way of knowing that the payment has been made effective.
![captura pantalla problema latin travel](https://user-images.githubusercontent.com/56823712/70132298-37730380-1684-11ea-8a3e-c0ce18fad822.png)

**Comment by konsP** [comment]
@Alvaroalconada  
the arrows in your figure point to **the state of the order not the payment**. In this case 3 = Paid.

Now,  the payment's status (either a preauth [marked as "Authorization"] or a charge [marked as "Card charge"in the transactions grid] is **colour-coded** as in this picture and in the attached pic for the case of a card charge. We do not provide any other info on the status of the payment other than that. 
 
![charge-cancelled](https://user-images.githubusercontent.com/12849628/70134751-575cf400-1691-11ea-8c59-0b25a4709f4e.jpg)

I hope this clarifies everything.
