### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by MadMikeyB** [VivaPayments/API#1244]
As per #1135 

I've set up the Redirect Checkout, I get sent to Viva Wallet, the payment processes, and then bam, no redirect.

![live](https://user-images.githubusercontent.com/831828/69766209-cbb60580-116e-11ea-9a08-6a3197bbf43a.png)

I've been asked to add a new issue even though #1135 explains it adequately, and surely the redirect link doesn't matter if I'm never redirected to Viva Wallet. 🤷‍♂️

**Comment by MadMikeyB** [comment]
I am not using WooCommerce. I am using Laravel and [this](https://github.com/sebdesign/laravel-viva-payments)

**Comment by matthewrgourd** [comment]
Hi @MadMikeyB I'm afraid we don't support the package you mention (it's unofficial) so I won't be able to help any further. However, you could try raising an issue here: https://github.com/sebdesign/laravel-viva-payments/issues

**Comment by MadMikeyB** [comment]
@matthewrgourd 

But it's not the package? I get sent to Viva Wallet and I am not redirected back to my website. *how* is that an issue with the package?

**Comment by matthewrgourd** [comment]
@MadMikeyB I imagine that the instructions to accompany the package may reference our-of-date documentation.

**Comment by matthewrgourd** [comment]
Hi @MadMikeyB can you send me your merchant ID so I can check if there's any issue with your account? Apologies if you've already done this but I need to look again.

**Comment by MadMikeyB** [comment]
Thanks @matthewrgourd - I was not sending the correct SourceCode - though I did not see this anywhere in the dev docs - maybe it could be updated that SourceCode is an INT and not "Default" like it is in the docs?


Thanks anyway
