### ISSUE TITLE
Server Error at demo.vivapayments.com/selfcare/en/sales/mysales

### ISSUE THREAD

**Issue by Stratubas** [VivaPayments/API#1245]
Hello again.

I'm working on native checkout v2 with pre-auth.

My steps are the following:

1) Get an access token by posting at
https://demo-accounts.vivapayments.com/connect/token

2) Get a charge token (and some html+js) by posting at
https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens

3) Render the html+js from step 2, which redirects me to
https://demo.vivapayments.com/web/checkout/fakethreedsecurecardholderauthentication,
where I click "Confirm payment".

4) Make a transaction (which responds with a `"transactionId"`) by posting at
https://demo-api.vivapayments.com/nativecheckout/v2/transactions,
putting `"preauth":true` in the payload.

Then, at https://demo.vivapayments.com/selfcare/en/sales/mysales, I get the following error:
[viva-server-error.pdf](https://github.com/VivaPayments/API/files/3904684/viva-server-error.pdf)

Are these steps OK? What's wrong?

**Comment by matthewrgourd** [comment]
Should normally be fine but the demo server can sometimes misbehave. Are you still experiencing the same issue or is it ok now?

**Comment by Stratubas** [comment]
Yes, the issue remains.

The page worked once now, because I didn't have any orders today. Searching for older orders popped up an "Error" message, and console logged "Failed to load resource: the server responded with a status of 500 ()".

After creating a new order (with the same steps), the original "Server Error" is shown in https://demo.vivapayments.com/selfcare/en/sales/mysales

**Comment by matthewrgourd** [comment]
@Stratubas Step 4 should be made through a back-end channel, not a browser. Is this what you're doing?

**Comment by Stratubas** [comment]
I'm doing step 4 through a locally hosted node server.

**Comment by matthewrgourd** [comment]
Hi @Stratubas you said "the original "Server Error" is shown in https://demo.vivapayments.com/selfcare/en/sales/mysales". Can you attach a screenshot of this?

**Comment by Stratubas** [comment]
Hey @matthewrgourd . Here's your screenshot 
![Screen Shot 2019-12-18 at 15 32 50](https://user-images.githubusercontent.com/9803561/71090489-cd8e4a00-21ab-11ea-8103-8f68e1e63dc7.png)

**Comment by matthewrgourd** [comment]
Hi there, this error occurs from time to time on the demo server. I believe you can simply refresh the page to remove the error. Please rest assured the production environment is a completely different story.

**Comment by Stratubas** [comment]
@matthewrgourd Refreshing the page does not remove the error. Even changing computer and OS does not remove the error. The error has been there for almost 20 days. Not exactly "from time to time" :) So how are we supposed to develop a new application? With our real credit cards in the production server?

**Comment by matthewrgourd** [comment]
Hi @Stratubas, sorry, I didn't realise that. I'll get them to reboot the demo server.

**Comment by matthewrgourd** [comment]
Any change?

**Comment by matthewrgourd** [comment]
Hi @Stratubas, sorry for the delay, the demo server has been fixed now. Obviously any further issues don't hesitate to get back to us!

**Comment by Stratubas** [comment]
@matthewrgourd Ahh, nice. Finally I can see how "capture" works. Thanks.
