### ISSUE TITLE
woocommerce redirect after successful payment

### ISSUE THREAD

**Issue by anupg** [VivaPayments/API#1246]
Hello
This is my domain name https://www.cbdeaze.co.uk and I am using the plugin from developer account https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip . I have setup everything also user can make the payment but user not redirecting to sucess page after sucessfull payment .. so I need urgent help on this and below is the configuration I am using in vivawallet setting and plugin setting.

![image](https://user-images.githubusercontent.com/5044873/69865818-52322a80-12c8-11ea-8884-a747f5a3fa89.png)

![image](https://user-images.githubusercontent.com/5044873/69865860-7130bc80-12c8-11ea-9fa9-a58b1b1ea68e.png)

![image](https://user-images.githubusercontent.com/5044873/69865929-ae954a00-12c8-11ea-8297-51b2da2e1b1f.png)

![image](https://user-images.githubusercontent.com/5044873/69866205-7b9f8600-12c9-11ea-93c0-ebe4f1b3b835.png)

Thanks
Anup

**Comment by VivaWalletSupport** [comment]
Hello, please follow the instructions to the letter: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
You seemed to have left empty the Source Code field in the plugin settings.
