### ISSUE TITLE
Virtuemart 1054 error

### ISSUE THREAD

**Issue by twistedpig** [VivaPayments/API#1248]
HI I am stil having issues with teh error
ERROR 1054 (42S22): Unknown column '' in 'where clause'
this comes after the user pays. ?? PLease help

Using the latest virtuemart vivawallet plug in

**Comment by VivaWalletSupport** [comment]
Hello, please try what had been recommended in your original post https://github.com/VivaPayments/API/issues/1034

**Comment by matthewrgourd** [comment]
Hi @twistedpig, @VivaWalletSupport installed as a test and found no problems. Suggestion was to  to debug your setup or use a fresh installation. Please try this. Thanks.
