### ISSUE TITLE
Magento 2.3 Integration

### ISSUE THREAD

**Issue by benjamin-dot** [VivaPayments/API#1249]
Hi, 

We've got Viva Payments installed and configured on a dev Magento 2.3 store however the payment methods is not showing up on the frontend, can anybody assist with this?

I've got no errors in any log files anywhere.

**Comment by VivaWalletSupport** [comment]
Hello, please follow he instructions from https://developer.vivawallet.com/e-commerce-plugins/magento2.3/ (Step 2).

**Comment by benjamin-dot** [comment]
I have done that and it doesn't show up.

The only issue I can potentially see is that the dev website has a different URL to that on the Viva Wallet website, would this cause the payment method to not show?

**Comment by VivaWalletSupport** [comment]
It wouldn't, only in case the extension has been excluded for specific countries or if the store currency differs from the configured currency the payment method would not be available. I would suggest to test on a vanilla version of Magento to exclude any problem with other 3rd party extensions / themes.

**Comment by benjamin-dot** [comment]
Thanks, it was the currency selection.

I hadn't selected the active currencies on the VivaPayments module, once i had updated this the module started showing up.
