### ISSUE TITLE
Integration method "Redirection"

### ISSUE THREAD

**Issue by meatpro** [VivaPayments/API#125]
Μπορώ να έχω Redirection method αλλά να στέλνω στο URL το ποσό χρέωσης?

**Comment by defilerc** [comment]
Καλησπέρα @meatpro ,

Για λόγους ασφαλείας, δεν είναι δυνατό να περνάει το ποσό της χρέωσης στο URL.

Η διαδικασία που ακολουθείται είναι η δημιουργία ενός Order από τη μεριά του site σας και στη συνέχεια redirect στη Viva Checkout με το order code σαν reference στο Url.

Ευχαριστούμε πολύ για την επικοινωνία,
