### ISSUE TITLE
Please enable API transactions endpoints for the following

### ISSUE THREAD

**Issue by davecarlson** [VivaPayments/API#1250]
Please enable API transactions endpoints for the following

demo:
`82d8cf98-baa4-47ae-b4d0-50dad0c8331a`

live:
`ca45e17e-01d8-43d5-a2e5-9dc3bdb93b50`

Thanks

**Comment by matthewrgourd** [comment]
Hi @davecarlson are you requesting this as the result of an error message? If so, what does it say?

**Comment by davecarlson** [comment]
Yes, it says that the api is disable for this merchant I’d.

Trying to post the token returned from simple checkout to /api/transactions

**Comment by matthewrgourd** [comment]
@davecarlson I've changed your settings. Please try again. Thanks!

**Comment by davecarlson** [comment]
The specified api action is disabled for the merchant ca45e17e-01d8-43d5-a2e5-9dc3bdb93b50, please consult the documentation

**Comment by davecarlson** [comment]
@matthewrgourd  - all working on test now. 

However - live is still down:

The specified api action is disabled for the merchant ca45e17e-01d8-43d5-a2e5-9dc3bdb93b50, please consult the documentation.

Can you please enable the API on this one too ?

```ca45e17e-01d8-43d5-a2e5-9dc3bdb93b50```

**Comment by matthewrgourd** [comment]
@davecarlson done! I'm closing this issue now. Feel free to reopen if any further problems.

**Comment by davecarlson** [comment]
Thanks Matthew - all working now.

**Comment by davecarlson** [comment]
Please can you enable the same APIs on the following LIVE account: 

Merchant ID | c949a92d-42ed-4bb5-a4d3-68b1ec007088
