### ISSUE TITLE
Getting Access Denied issue for demo testing

### ISSUE THREAD

**Issue by rajdeeporbsys** [VivaPayments/API#1251]
Hello,

Am getting access denied error while going for viva wallet checkout page. 

"You dont have permission to access..."

please check loom video for better understanding

https://www.loom.com/share/eba37bcc466f4550b9fb43d343599615

**Comment by matthewrgourd** [comment]
Hi @rajdeeporbsys it looks like you need to replace any instances of `http` with `https`. Thanks!

**Comment by rajdeeporbsys** [comment]
If you check my code its already https and as i mentioned it sometimes works
