### ISSUE TITLE
Getting Access Denied issue for demo testing and instances are already of https

### ISSUE THREAD

**Issue by rajdeeporbsys** [VivaPayments/API#1252]
Hello,

Am getting access denied error while going for viva wallet checkout page.

"You dont have permission to access..."

please check loom video for better understanding

https://www.loom.com/share/eba37bcc466f4550b9fb43d343599615

For this matthewrgourd already reverted but am using https instance already.

Also If you check my code its already https and as i mentioned it sometimes works too.

**Comment by matthewrgourd** [comment]
Ok I will raise again with one of our developers and get back to you when I have any further info.

**Comment by matthewrgourd** [comment]
Hi @rajdeeporbsys you said you were using Ecwid as your e-commerce platform. Are you sure the error message isn't from Ecwid? We can't find any issues at the Viva Wallet end?

**Comment by rajdeeporbsys** [comment]
Hello,

this is not related to ecwid as its normal post which going to your demo server and sometimes behaves like this.

So please take this under consideration

**Comment by matthewrgourd** [comment]
Ah, ok, you're referring to our demo server. Unfortunately this isn't 100% reliable but rest assured that in the live environment everything will be fine.

**Comment by rajdeeporbsys** [comment]
Hello,

As from your guidance i make it live but still facing access denied issue.

Access Denied
You don't have permission to access "http://www.vivapayments.com/web/checkout?" on this server.
Reference #18.51c2017.1577963421.b8b518f9 

Please resolve

**Comment by robksawyer** [comment]
I'm also getting this issue anytime I navigate to https://www.vivapayments.com/ from South Korea.
