### ISSUE TITLE
How to translate Credit/Debit Card text at checkout page into Greek

### ISSUE THREAD

**Issue by theomandgr** [VivaPayments/API#1253]
Hello,

I am having an issue with the checkout page concerning the credit/debit card payment provider. The text of the Credit Card option is written in English as you can see in the image below.

Is there any way this can be translated into Greek? Can this be done via the platform of Shopify? 
The only thing I haven't tried is to switch the whole Shopify account in Greek.
![Screenshot 2019-12-04 at 17 25 36](https://user-images.githubusercontent.com/58560054/70244047-65d40a00-177c-11ea-9c8c-92742c0e94a0.png)

**Comment by GJFox1972** [comment]
I also have a similar language issue our return invoice emails are in greek and i need them in English

**Comment by theomandgr** [comment]
Anyone?

**Comment by matthewrgourd** [comment]
@GJFox1972 Regarding the receipts being in Greek, you need to confirm that your Preferred language setting is set to English as in the image below:

![50774099-4fd37600-129b-11e9-8956-7c889a42c0de](https://user-images.githubusercontent.com/44943019/70916009-d3045c80-2012-11ea-9174-983ca8cea866.jpg)

**Comment by matthewrgourd** [comment]
@theomandgr sorry for the delayed reply. Is your Viva Wallet Account Greek?
