### ISSUE TITLE
Emails language 

### ISSUE THREAD

**Issue by GJFox1972** [VivaPayments/API#1254]
How do we change the language of the emails to English?

**Comment by matthewrgourd** [comment]
Hi @GJFox1972, sorry, which emails? What language are they being sent in? Sorry, please provide further details of the issue. Can I have your company name, please?

**Comment by GJFox1972** [comment]
this is in regards to the other issue to when that API is active the email invoice to the customer is being sent in greek I am currently using your plugin and it's fine but I paid Mohit for the API so I could have tokenization.

**Comment by matthewrgourd** [comment]
If this relates to the API parameters, please send through the request / response logs (or get your developer to).

**Comment by matthewrgourd** [comment]
For instance there is a parameter `RequestLang` for setting the language within the Payment API. This is when you create the Payment order. It needs to be set to 'EN-US' for English: https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post

**Comment by matthewrgourd** [comment]
@GJFox1972 Which plugin is it you're referring to which needs its language changing? Need more info please.

**Comment by GJFox1972** [comment]
@matthewrgourd  cheers it was with the API that is being temporarily disabled so once It's sorted i will take it back up with you

**Comment by matthewrgourd** [comment]
@GJFox1972 ok, I'm going to close this ticket for the time being but you can always reopen it.
