### ISSUE TITLE
Error - PaymentsCardHolderAuthenticationInvalidStatus

### ISSUE THREAD

**Issue by odysseas12** [VivaPayments/API#1258]
Im getting this error on some transactions. 

{"error":1,"data":{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":400,"ErrorText":"PaymentsCardHolderAuthenticationInvalidStatus","TimeStamp":"2019-12-07T10:34:58.6234796+02:00","CorrelationId":null,"EventId":2061,"Success":false}}

Can you please let me know what is the issue and what can be done about it.

Thanks.

**Comment by matthewrgourd** [comment]
Please email me with your Merchant ID so I can check your account. Reference this issue in the message. mgourd@vivawallet.com

**Comment by odysseas12** [comment]
@matthewrgourd 
I send you an email a few days ago did you get it ?

**Comment by matthewrgourd** [comment]
Hi @odysseas12 got that now – thanks. I can't see any issues with the account. Suggest you try a different card.

**Comment by odysseas12** [comment]
Matt this is a live account for a real client and real credit cards.

**Comment by matthewrgourd** [comment]
@odysseas12 I will get one of our developers to look into it.

**Comment by matthewrgourd** [comment]
Hi @odysseas12 our dev team is requesting full request / response logs. Can you please send these to mgourd@vivawallet.com. Thanks.

**Comment by odysseas12** [comment]
Hi Matt, 
Unfortunately I dont have request logs, its on a live site and on certain failed transactions that is the response I get back. 
Its not an issue I can reproduce, it randomly happens maybe 1 or 2 times every 100 transactions.

**Comment by odysseas12** [comment]
If you could just let me know what the error suggests.
Is it a problem on my end ? a problem on your end ? or is it an issue of the credit card ?

**Comment by matthewrgourd** [comment]
Hi @odysseas12, if it's an intermittent issue I'm not sure what it means. Can you remind me how you've implemented our payment platform? Is it using Native Checkout v2?

**Comment by matthewrgourd** [comment]
Hi @odysseas12, I've just spoken with our dev team who say that 'Error - PaymentsCardHolderAuthenticationInvalidStatus' means that the 3DS authentication failed (I assume at the cardholder end). Hope this helps!
