### ISSUE TITLE
UNABLE TO LINK VIVA WALLET ACCOUNT TO SHOPIFY PLEASE HELP!!!

### ISSUE THREAD

**Issue by lilkitty22** [VivaPayments/API#1259]
I am unable to link my Viva wallet account to my Shopify store. When a customer tries to pay instead of viva wallet loading the payment page it just comes up with the words, 'input is invalid' on a white screen?
I'd be so grateful if anyone could help? xx

**Comment by matthewrgourd** [comment]
Hi @lilkitty22 is this a recent switch you've made to using Viva Wallet within Shopify? Have you followed our [guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/)? Please follow this verbatim in order to install correctly. Thanks!

**Comment by matthewrgourd** [comment]
Hi @lilkitty22 can you send me your Merchant ID and I may be able to investigate further. Email is mgourd@vivawallet.com. Please reference this issue in the message.

**Comment by matthewrgourd** [comment]
Hi @lilkitty22 please follow our [Shopify guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/) to make sure you've added the plugin correctly.
