### ISSUE TITLE
Viva  Επιστροφή

### ISSUE THREAD

**Issue by beesmart1** [VivaPayments/API#126]
Γεια σας

Έχω δημιουργήσει δύο πηγές πληρωμών για δυο site ξεχωριστά ώστε να δέχομαι πληρωμές μέσω της Vivapayments  (http://prntscr.com/bgj8bg & http://prntscr.com/bgj8bg). 
Στο ένα site, www.bee-smart.gr μετά την πληρωμή η επιστροφή γίνεται κανονικά στο site.
Στο άλλο site, www.beekeeping-equipment.com μετά την πληρωμή η επιστροφή βγάζει ένα σφάλμα http://prntscr.com/bgj9i6 (επιστρέφει στο πρώτο).
Επιπλέον στο περιβάλλον πληρωμής δεν εμφανίζετε το logo της εταιρείας.

Περιμένω την απάντηση - βοήθειά σας για την επίλυση του προβλήματος.

Με εκτίμηση 
Γιάννης

**Comment by beesmart1** [comment]
Απάντηση  καμιά  ρε παιδιά

**Comment by dmihos** [comment]
Καλημέρα σας και συγγνώμη για την καθυστερημένη απάντηση

Βλέπουμε ότι η πλειοψηφία των συναλλαγών σας κάνουν χρήση της πηγής 'Default', στην οποία μάλιστα δεν υπάρχει καταχωρημένο logo (γι'αυτό δεν εμφανίζεται στην checkout)
Για το κάθε site, θα πρέπει να κάνετε χρήση της αντίστοιχης πηγής, ώστε ο χρήστης να ανακατευθείνεται αντίστοιχα ([link](https://github.com/VivaPayments/API/wiki/Optional-Parameters))
Το error που μας δείχνετε, δυστυχώς, προέρχεται από το δικό σας σύστημα, οπότε δε μπορούμε να βοηθήσουμε παραπάνω. Ίσως θα πρέπει να εντοπίσετε τις διαφορές στον κώδικα των 2 sites.
