### ISSUE TITLE
Issue with SimpleCheckout 

### ISSUE THREAD

**Issue by alexnuzh** [VivaPayments/API#1261]
I use this instruction
https://developer.vivawallet.com/online-checkouts/simple-checkout/
Step 1 is ok
Step 2 when I send request to Make the charge to https://demo.vivapayments.com/api/transactions
I receive error
https://prnt.sc/q727kb
May be in some place need activate this simple checkout ?

**Comment by matthewrgourd** [comment]
Hi @alexnuzh please email mgourd@vivawallet.com with your demo and live Merchant IDs. I will then be able to enable the correct settings. Thanks!

**Comment by matthewrgourd** [comment]
Hi @alexnuzh I have enabled 'Allow recurring transactions through the API' in your settings. Please try again. You should do this also in your [production account](https://members.vivawallet.com/en/signin) once you've set one up (Settings / API Access / 'Allow recurring payments').
