### ISSUE TITLE
WooCommerce Viva Wallet Plugin Integration into Wordpress 

### ISSUE THREAD

**Issue by olesiastudenets** [VivaPayments/API#1262]
Dear Team,

I have downloaded the version of plugin from here https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ but failed to install it to my new last update version of Wordpress WooComnmerce dashboard. The only error was - failed, no other specific details.
I have competetd the settlement of account with API on my online Viva bank account but stuck at installation of plugin for WooCommerce.
I have checked the available plugins for Viva Wallet in official Wordpress site and there are 3 others plugins for Viva Wallet:
https://wordpress.org/plugins/woo-payment-gateway-viva-wallet/
and
https://wordpress.org/plugins/woo-payment-gateway-for-vivapayments/
Which one should I install for Viva Payments?
Or how to install the plugin which is on your site and not existing on Wordpress site,
Thank you for your help,
Best Regards,
Olesia Studenets Christodoulou
+35797617427

**Comment by VivaWalletSupport** [comment]
Hello, you would download the zip package from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ to your desktop and use the plugin installer from WordPress.

**Comment by olesiastudenets** [comment]
I did it exactly as you say. Downloaded to my desktop and tried to install in dashboard WordPress as it is described in the instruction but it failed, can't be installed.

**Comment by olesiastudenets** [comment]
I have new Worpress version-the latest one.
Is there any potential issue with compatibility with your plugin which is here https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ ?

**Comment by VivaWalletSupport** [comment]
Just tested the specific plugin on the latest version of WP / WooCommerce and I cannot replicate the issue you mention. Try a vanilla WP/WC installation / find out what exact error occurs.

**Comment by olesiastudenets** [comment]
Can you explain what does it mean? I just received the new reinstalled WP with WooCommerce plugin form Alidropship support team, i am not developer so can't catch you.
 Can you explain please what can be done exactly?

And comment on the plugins already existing on official Wordpress site i mentioned.
Are they not working?

**Comment by olesiastudenets** [comment]
I have seen the problem, it was conflict with default currency (for some reason it was USD), when i have changed it to EUR it became active.
The problem resolved. 
Thank you for your time.
