### ISSUE TITLE
Vivawallet and Shopify order syncing 

### ISSUE THREAD

**Issue by Laura345** [VivaPayments/API#1263]
A customer has tried to place an order using Shopify and payment was taken for the order from vivawallet however the order didn't pull through as completed on Shopify and sits in abandoned checkout. Please assist in fixing this and converting this to a placed order. What would cause this?
--

**Comment by matthewrgourd** [comment]
Hi @Laura345, sorry to hear this. How long have you been using Viva Wallet with Shopify? Any issues before?

**Comment by matthewrgourd** [comment]
Hi @Laura345, on what date was the payment taken? Please email me your Merchant ID and company name so I can check your account. My email is mgourd@vivawallet.com.

**Comment by matthewrgourd** [comment]
Hi @Laura345 I can't find any issues with your account. The transaction you mentioned by email went through fine so suggest you get in touch with Shopify.
