### ISSUE TITLE
Simple checkout and Installments

### ISSUE THREAD

**Issue by zissop** [VivaPayments/API#1264]
Hello

Do you support installments on the simple checkout method?

Thanks in advance

**Comment by matthewrgourd** [comment]
Hi @zissop , I'm afraid installments are not supported using the Simple Checkout method. You would need to use [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/).

**Comment by zissop** [comment]
Do you plan to support it? It's a must have feature.
