### ISSUE TITLE
"Simple Checkout" integration in Prestashop module?

### ISSUE THREAD

**Issue by IlPizza79** [VivaPayments/API#1265]
Hi, I'm using Viva wallet module for Prestashop.
It seems that only "Redirect Checkout" integration can be used with Prestashop module, is it true?
Is there a way to activate "Simple checkout" integration when using Prestashop module?
Thanks :-)

**Comment by VivaWalletSupport** [comment]
Hello, currently the simple checkout is not available in the supported module.
