### ISSUE TITLE
 Checkout token decryption failed

### ISSUE THREAD

**Issue by alexnuzh** [VivaPayments/API#1266]
Hi 
I am using simple checkout https://developer.vivawallet.com/online-checkouts/simple-checkout/
but on step 2 I receive error 
 Checkout token decryption failed see please attached below 
http://prntscr.com/qah6mv  

I am use demo account 
My Merchant ID: e12b1507-b333-4bd5-94d2-d299288d58e0
publickey : 1IK3aOYpmaZaW28icrI8fzq1ocI64u9N6eLL/JehJZA=

thank  

token from screen below: 
9WxXQ1MJ71BdtPDTJjuarWcESod1jdtfAj4Anc5pDq0h2XREmdvALAFbyXaNbQW2oSdBo7re8OtZRx94WRESQdegYqUqTCvowpvQmdS94HpWpFTmeKhpun3yMpNGfy7wBtXntaUEkD6e83C2IBzJ0vcPWDec3uRv12qn1j8Ds7dzDWkBqC0SjrhyI2dIJb0whpQl9fvpRT5H9WOKP2Q3NRJRXaoryqKCkTuX5nhO9Euerw+xl80EC0d7TzCTeDRHnnafNds7EiCbyt+SJPHcAjTf0Ec1U5p9cpMCcpLoR32JpLRtD3E74L+0EJfLMd6WU7+MSS9wpMOcnP6USha+FrrIikpdifPzajJL6s477FY/2t9BySMXeui6IYMREW9urjEoN3WZsKsEbYYmlIuypJx83uTMGOh6XyQyscCTyHcUkzrFuEJBj5gi7NPQOyqR37M3HZkfUDiilZt7x5UZldu2JBM3ePgnzxOkLpmXgJJZPZzPP+/Pa49UQdDyQbezeNtweKnNbBflNSSQ3LvY+cvIN5CczFznbpf9KrjIvWeiCttKPkoZoKXMGMM2ry+H1iTCfeZnPzvHd3SSnfCukvq86ABA5SWRuaCcNeh7gcLjEpcZ+K3RZgiSNoAVePdO2yWRoZ2BUSHlG0dK2RUrbjJ1LHdMNsmFLEetzXDga8bIRBdHjhwiA+ifSQRmmdmGmAzUiAnAEvprLjDXdzyRU5sj1C9jlGYVkaZ+0VSzuAxmgEH7fHT9xEqWld4tLtzBxY7DGCLWNTV0sHZF1Ak+sjHgunSKoye24tqfS7Jde4AeyihJyrfrvEoOfvmWy6xbPBAw5qAzFtYmiK5hfWotQg/t82aVvVSshgf0u2O1IOF8NXMZvnsCDd2IWyZDkLtGe+qT2GzbwU/VnRrMizu4EsrUb3smO7PNkAPovDItV7cp3Oe2DdYeGWnZmq5/Jlf56nnuU9pAjx/TYcjaeS/FqbkIClnqR5ikIdWVGK5sobLHDy9J59RWIWpBJoqFN1NMslwy/gkxtqKqgiPfMcib1gZEi8JZEyVXQN+KuIjj77+ZLsMNG8zWJQ==

**Comment by matthewrgourd** [comment]
@alexnuzh Please try again. I've adjusted one of your settings.

**Comment by alexnuzh** [comment]
thanks but I still receiving error 

https://prnt.sc/qbkh9p

PaymentToken=9WxXQ1MJ71BdtPDTJjuarWcESod1jdtfAj4Anc5pDq0h2XREmdvALAFbyXaNbQW2oSdBo7re8OtZRx94WRESQdegYqUqTCvowpvQmdS94HpWpFTmeKhpun3yMpNGfy7wBtXntaUEkD6e83C2IBzJ0vcPWDec3uRv12qn1j8Ds7dzDWkBqC0SjrhyI2dIJb0whpQl9fvpRT5H9WOKP2Q3NRJRXaoryqKCkTuX5nhO9EsQDQ1hi4m8c9OSVeInCf3OD+Z/yrk6DkSfptGpq5nJj/5YwlY2T5Bn+gDiJOtbxrUw2agKofFjHhgMVz/qxPBgR58MrBiRqXmaC2vwM/U0o3bwjqFlvViJB7rSnyEZMFzVZeXT0PMYFGEtPcXiplJjzjjZsGY3JUrIgQnfcJlRzr1eVCr1WSWiyHbiaPEK3i0z9QBPhAm83hW4MpxLfjcYAlUMB3QQgAe+c0maeZByPNqk6ZRfrRaGU+VyamerRJMRdlG78Gimjl9KKY31ztBNlPYNO/kIoEIEboPWe1n5umPMkR9DNnIdNiT0019+qtal2k4nIF/LS/wF3KxIanWKwOna+k4kdWiLUUeBhlO8qaLrTfnsjEhWNmfbuTshbrK0YAQiCbiHzJLXAGuDxzVJUMPNHn2ogYwPRRnGgivV+Ot93vue00pSVIHIcGxPaCmTckO3b7UbcM5nvsLSVkGsRTMM95jK+d3ovWkZ6ZQdrwo91zhWUC63pSJkCRmBNTiy5Q297tDiAIFK8SBc2RFe8y4aCvW7GQU/Ea1Jnu+hlWYMgrx5j9zRaG3w/7S3IGKxB73LkyRwkPu3KDzPAKkyYtAtqtWbsNjOPCadgwi13IFzKhaSvSLnC4kfZLPoCU/VKW9hP+/iEgGIjSJLVvMPWP6q9HlLR3osnSkI/yDRYNjZ5IpNN7Vu3/ch0OZ1+r9YQXpTNMlMtu7udUN7QueoMh8hV7gXi6UwI8vt+TeqYVbJfF5Os36ICNMsZFHHmNhswT6qRZZyPzOzHy4qYTaf/vn4WiFVCCk2J4dKALav8MK7pFCadfYxzGabP5+ngCA=

$response=Array
(
    [Emv] => 
    [Amount] => 
    [StatusId] => E
    [CurrencyCode] => 
    [TransactionId] => 
    [ReferenceNumber] => 
    [AuthorizationId] => 
    [RetrievalReferenceNumber] => 
    [ThreeDSecureStatusId] => 
    [ErrorCode] => 500
    [ErrorText] => Checkout token decryption failed
    [TimeStamp] => 2019-12-16T16:25:52.5000504+02:00
    [CorrelationId] => 
    [EventId] => 0
    [Success] => 
)

**Comment by alexnuzh** [comment]
Hi 

Any news here? Still getting error and cannot put this on live site :(

**Comment by matthewrgourd** [comment]
Hi @alexnuzh sorry to hear this. Please send through full request / response logs. What tool are you using to create the output shown in your screenshot?

**Comment by alexnuzh** [comment]
Hi see please below 👍  
http://hobbymounts.arthur.antropy.co.uk/viva.php   
then I enter https://prnt.sc/qcghi8
then https://prnt.sc/qcghp2 
then second script https://hobbymounts.arthur.antropy.co.uk/index.php?route=competition/vivawallet/callback2 do STEP 2  
I send by POST 1 variable 
https://prnt.sc/qcgibf  

thats all

**Comment by matthewrgourd** [comment]
Hi @alexnuzh, after further investigation this issue relates to your server implementation when posting to api/transactions. We've checked and everything is ok at the Viva Wallet end. Sorry not to be able to help any further. Thanks! Matt

**Comment by alexnuzh** [comment]
Thanks but may be you have some PHP example of server part because I am sure I all did in correct way
