### ISSUE TITLE
Simple checkout problem

### ISSUE THREAD

**Issue by zissop** [VivaPayments/API#1267]
When we try to make a payment using the demo credit card with Simple checkout, the popup turns into a 3D secure dialog (Image1) where we have to choose the authentication outcome.

Whatever we choose we get Image2 and the form is never posted. The X button cant be pressed.

What is the problem?

Image1: https://ibb.co/3RJ9FvW

Image2:  https://ibb.co/Cwdyzpn

**Comment by zissop** [comment]
Now i see that when we choose the authentication outcome, a javascript error occured in your side:

simplecheckoutjs?v=PR_YzcgeWp89Jcf7LTy4GlU9K4a9SpGE3dZyoXpYHWs1:1 POST https://demo.vivapayments.com/web/checkout/getpaymenttoken 500 (Internal Server Error)

**Comment by matthewrgourd** [comment]
Hi @zissop I've just tried this myself and the only way I've been able to recreate your issue is if I attempt to use the demo card details against a production account. The demo card details against a demo account are fine: the red X button never appears.

**Comment by zissop** [comment]
No, we use the demo URLs.

<button id="viva_button" type="button"
                            data-vp-publickey="xxxx"
                            data-vp-baseurl="https://demo.vivapayments.com"
                            data-vp-lang="el"
                            data-vp-amount="<%=sAmount%>"
                            data-vp-merchantref="<%=OrderId%>"
                            data-vp-description="Order <%=OrderId%>"
                            data-vp-expandcard="true"
                            data-vp-text="Πληρωμή μέσω Viva Payments"
                        </button>
                    </form>
                     <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
                    <script src="https://demo.vivapayments.com/web/checkout/js"></script>

**Comment by matthewrgourd** [comment]
Very strange, I just tried the above with my own (demo) key and an amount of 100 and still the green tick symbol is displayed rather than a red cross. I chose 'Success' as the 3DS option.

**Comment by matthewrgourd** [comment]
Closing issue as unable to recreate.

**Comment by zissop** [comment]
Actually this problems still exists when i try to make payments from my computer. I tried from another computer - no problem.
Do i have to clear anything? I cleared cache and local storage - still no success.
