### ISSUE TITLE
Redirect back to my site URL failed after Success Payment

### ISSUE THREAD

**Issue by nimaris** [VivaPayments/API#1268]
Some times (not all times) the redirection from vivawallet to my site success url not working. As a result, I cannot input successfully the transaction. I use Redirection/Native Checkout v2 method.

**Comment by matthewrgourd** [comment]
HI @nimaris, sorry to hear this. Can you let me know a bit more about your setup? Are you using an e-commerce platform with one of our [plugins](https://developer.vivawallet.com/e-commerce-plugins/) or is it a custom implementation. What's your web address? Thanks!

**Comment by nimaris** [comment]
I'm using custom setup and my web address is mobis.gr. Thanks.

**Comment by matthewrgourd** [comment]
Is the redirect not working sometimes in production or is it demo you're referring to?

**Comment by matthewrgourd** [comment]
Can I just confirm you've followed our instructions for [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) for the custom integration?

**Comment by nimaris** [comment]
Not working sometimes in production mode. Yes, i have followed your instructions. I use the service for a long time in most cases with no problems.

**Comment by matthewrgourd** [comment]
Hi @nimaris can you email mgourd@vivawallet.com with your merchant id referencing this issue? I will then check your account.

**Comment by matthewrgourd** [comment]
Hi @nimaris thanks for sending through your merchant ID. I see that you have several payment sources set up. Could you provide the 4-digit number for the one you're having problems with? Thanks!

**Comment by matthewrgourd** [comment]
Hi @nimaris thanks for sending through the payment source ID. I can't see any issues there either so will have to think about it a bit more before getting back to you.

**Comment by matthewrgourd** [comment]
Hi @nimaris is this still an issue?

**Comment by matthewrgourd** [comment]
Closing issue as not heard back.
