### ISSUE TITLE
Validate online payment gateway

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1269]
Hi @matthewrgourd  I need quickly your help about this customer GONZALEZ SA
Please solve for me ASAP. This customer is very important
Is there anybody of your team that speaks French and call her? because I sent the proccedure that appears in CC-1227488 and she can´t continue with the process to validate pending account. Is so difficult for me communicate with her because just speaks french and almost nothing English or Spanish.

If you want I can provide you her Telephone number

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada I gather the merchant has now been informed by telephone about the pending elements for approving the source. I'm therefore closing this issue.
