### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by avogiatzakis** [VivaPayments/API#127]
καλημέρα σας

Έχουμε εγκαταστήσει το module σε πλατφόρμα prestashop της viva..έχουν γίνει όλες οι ρυθμίσεις κανονικά.
Οταν κάποιος πελάτης μας κανει αγορα, μεταφέρετε στο περιβάλλον σας,βάζει τα στοιχεία του και ολοκληρώνετε επιτυχώς η παραγγελία.

Στο διαχειριστηκο σας φαίνεται κανονικά η αγορά του πελάτη μας.

Το πρόβλημα ειναι οτι μετα την ολοκληρωση της παραγγελιας,δεν στέλνει τον πελάτη πίσω στην σελίδα που έχουμε ορίσει σαν success ,με αποτέλεσμα δεν ολοκληρωνεται σε εμας η παραγγελία..

Έχουν οριστεί σωστά και οι δυο παράμετροί για την επιστροφή σε εμας, σωστή και αποτυχημένη συναλλαγή.

Το κατάστημα είναι το shoecloset.gr

**Comment by dmihos** [comment]
Καλημέρα σας, ευχαριστούμε για το μήνυμά σας.
Κατά τη δημιουργία του Order, θα πρέπει να χρησιμοποιείτε το SourceCode στο οποίο έχετε δηλώσει τα urls σας, διαφορετικά χρησιμοποιείται η πηγή Default.
https://github.com/VivaPayments/API/wiki/CreateOrder
https://github.com/VivaPayments/API/wiki/Optional-Parameters

**Comment by avogiatzakis** [comment]
καλήμερα σας

το module χρησιμοποιεί το source code,εσεις βλεπετε στης αγορες που εχουν γινει,οτι δεν εχει ερθει σε εσας?

**Comment by dmihos** [comment]
Οι περισσότερες συναλλαγές (όχι όλες) έχουν sourceCode 'Default'.
Στείλτε μας, στο merchants@vivawallet.com, αν θέλετε, κάποιο συγκεκριμένο transactionId για διερεύνηση.

**Comment by avogiatzakis** [comment]
Μετα απο καποιες δοκιμες μας βγαζει αυτο

![untitled](https://cloud.githubusercontent.com/assets/19935834/16879284/9dac83ec-4ab8-11e6-997e-62ffc795abdf.jpg)

**Comment by themis1970** [comment]
ΜΑΛΟΝ ΚΑΝΕΤΕ ΚΑΠΟΙΟ ΛΑΘΟΣ, ΚΑΙ ΜΟΥ ΣΤΡΕΝΕΤΕ ΔΙΑΦΟΡΑ ΜΗΝΥΜΑΤΑ,

ΘΑ ΣΑΣ ΠΑΡΑΚΑΛΕΣΩ, ΝΑ ΜΗΝ ΜΟΥ ΞΑΝΑΣΤΕΙΛΕΤΕ ΜΗΝΥΜΑΤΑ

www.koronis.com.gr
www.χονδρικη.gr
<http://www.%CF%87%CE%BF%CE%BD%CE%B4%CF%81%CE%B9%CE%BA%CE%B7.gr>
www.xondriki.eu
www.tzamia-tapetsaries.gr

email: koronis1970@gmail.com

ΕΜΠΟΡΙΟ ΕΙΣΑΓΩΓΗ ΚΑΤΑΣΚΕΥΗ
ΞΥΛΟΥ-ΑΛΟΥΜΙΝΙΟΥ.

ΘΕΜΙΣΤΟΚΛΗΣ ΚΟΡΩΝΗΣ
ΤΗΛ.-FAX 22210 22243
MOBILE: 6972699533
TK.34100
ΒΑΛΣΑΜΑ 4
ΧΑΛΚΙΔΑ

****************************************************************
Προσοχή ! Σύμφωνα με το άρθρο 14 του Νόμου 2672/1998 (ΦΕΚ 290 τ.Α)
τα μηνύματα e-mail, για να είναι έγκυρα θα πρέπει να περιέχουν απαραίτητα :
Ονοματεπώνυμο ή επωνυμία (για Νομικό πρόσωπο), ταχυδρομική διεύθυνση
κατοικίας, αριθμό τηλεφώνου ή fax, ιδιότητα του χειριστή.
Αν τα μηνύματα προέρχονται απο υπηρεσία ή Δημόσιο φορέα να περιέχουν
επιπλέον θέμα, ημερομηνία, αριθμό πρωτοκόλλου.
Το μήνυμα ηλεκτρονικού ταχυδρομείου τεκμαίρεται οτι έχει περιέλθει κανονικά
στον λήπτη αν υπάρξει ηλεκτρονική επιβεβαίωση.
 Οι πληροφορίες ή και τυχόν αρχεία που υπάρχουν σε αυτό το ηλεκτρονικό
μήνυμα είναι προσωπικά και απόρρητα
****************************************************************

2016-07-15 18:19 GMT+03:00 avogiatzakis <notifications@github.com>:
