### ISSUE TITLE
Forbidden 403

### ISSUE THREAD

**Issue by pvflessa** [VivaPayments/API#1270]
When I try to pay during checkout, I get the following error message at chrome console:
POST https://api.vivapayments.com/acquiring/v1/cards/chargetokens 403 (Forbidden). 
I can't figure out if this is an issue with my code or if my client should modify his account settings.

**Comment by matthewrgourd** [comment]
Hi @pvflessa unfortunately this call is no longer available due to updates as a result of PSD2. Can you try https://api.vivapayments.com/nativecheckout/v2/chargetokens which we have made available instead?

**Comment by pvflessa** [comment]
That was it. Thank you
