### ISSUE TITLE
VivaWallet Fee

### ISSUE THREAD

**Issue by pRieStaKos** [VivaPayments/API#1271]
Καλησπέρα,

Μπορεί κάποιος να μου πει το fee της Viva για πληρωμές με Redirect Checkout ?
Έχω μείνει στο `2.9%` + `0.20€` / συναλλαγή

Ευχαριστώ.

**Comment by matthewrgourd** [comment]
Hi @pRieStaKos the acquiring fee is set by Viva Wallet according to your sales volumes. Please check with our customer service team, contact details below:

<table><tr><th>Country</th><th>Phone number</th>
  <tr><td>Belgium</td><td>(+32) 2342 0790</td></tr>
    <tr><td>Cyprus</td><td>(+357) 2403 0211</td></tr>
    <tr><td>France</td><td>(+33) 1876 50765</td></tr>
    <tr><td>Greece</td><td>(+30) 21 1760 4000</td></tr>
    <tr><td>Netherland</td><td>(+31) 2089 05503</td></tr>
    <tr><td>Romania</td><td>(+40) 3122 96150</td></tr>
    <tr><td>UK</td><td>(+44) 20 3734 7770</td></tr>
    <tr><td>Portugal</td><td>(+351) 3 0050 9059</td></tr>
</table>
