### ISSUE TITLE
status":403,"message":"PaymentsPolicyCreditRestriction

### ISSUE THREAD

**Issue by marketima** [VivaPayments/API#1272]
hi,

i am use native checkout v2 (3ds) and i fae this issue:

2019-12-17 12:52:25
Response: {"status":403,"message":"PaymentsPolicyCreditRestriction","eventId":"2105"}
-------------
can you check it please, as it cause big trouble and in support nobody reply my email almost 20 days as well i call to support by phone.

**Comment by matthewrgourd** [comment]
Hi @marketima, sorry to hear this, I'm checking with our development team.

**Comment by matthewrgourd** [comment]
Hi @marketima I've checked and there's a restriction on your account. Please speak to your nearest Viva Wallet customer services team. There's nothing I can do from here I'm afraid.

<table><tr><th>Country</th><th>Phone number</th>
  <tr><td>Belgium</td><td>(+32) 2342 0790</td></tr>
    <tr><td>Cyprus</td><td>(+357) 2403 0211</td></tr>
    <tr><td>France</td><td>(+33) 1876 50765</td></tr>
    <tr><td>Greece</td><td>(+30) 21 1760 4000</td></tr>
    <tr><td>Netherland</td><td>(+31) 2089 05503</td></tr>
    <tr><td>Romania</td><td>(+40) 3122 96150</td></tr>
    <tr><td>UK</td><td>(+44) 20 3734 7770</td></tr>
    <tr><td>Portugal</td><td>(+351) 3 0050 9059</td></tr>
</table>

**Comment by marketima** [comment]
are you sure? as i see in my vivawallet console- no any restriction, i call (and still with support in greece)- and they know nothing about it... so i really don't know what to do.
what is the reason? how to solve it?

**Comment by matthewrgourd** [comment]
Hi @marketima, yes, I'm sure, it's an account restriction on your business "MSA UG". If customer service are unable to lift it for whatever reason then you can't use are API.
