### ISSUE TITLE
The specified api action is disabled for the merchant

### ISSUE THREAD

**Issue by SBO-FRTN** [VivaPayments/API#1274]
Hello @matthewrgourd, can you please do the same as you did for us [here](https://github.com/VivaPayments/API/issues/1231#issuecomment-558177121)

New Merchant ID : 0eaaf41b-704d-41e5-84da-0e9b835c0318

Thank you in advance!

**Comment by matthewrgourd** [comment]
Hi @SBO-FRTN that's done now (and I've obscured your Merchant ID from the forum.)

**Comment by safwen1** [comment]
Hello @matthewrgourd we need the same thing for another client : ed105491-5fda-4ca2-9938-debe1fb3c615

PS: Sorry for posting the merchant ID as there was no other way to send it to you. Please obscur it from the forum.

**Comment by matthewrgourd** [comment]
Hi @safwen1, done! Thanks.
