### ISSUE TITLE
J2store - Joomla Extension

### ISSUE THREAD

**Issue by ntourziotis** [VivaPayments/API#1275]
Greetings dear support team,

I would like to install on my joomla site your viva wallet plugin. I am using the J2store plugin.

Could you please let me know which one of your extension should i have to install in my site?

Best regards

Ioannis

**Comment by matthewrgourd** [comment]
Hi @ntourziotis  I'm sorry, we do not have a plugin available for J2Store. Are you based in Greece? Here is a list of the supported payment gateways: https://www.j2store.org/j2store-payment-gateways/united-kingdom.html
