### ISSUE TITLE
Trouble with some payments : payments failed

### ISSUE THREAD

**Issue by WoodyLine** [VivaPayments/API#1276]
We suscribe to vivawallet 2 weeks ago, and we use the method with token on Shopify (which was adviced by VivaWallet on them website). Their is a problem because many payments failed, and many customers contact us to say that they have money, but the payment failed every time. 
How can we resolve this problem ? 
Is there any other method to install VivaWallet on Shopify ? 
Thank you

**Comment by matthewrgourd** [comment]
Hi @WoodyLine Sorry to hear this. Did you receive any error messages while you followed our [installation guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/)? If not, and most of your customers are managing to make payments successfully, then I suggest they try a different payment method. If any errors have occurred, please send through screenshots if possible?

**Comment by WoodyLine** [comment]
the integration of viva wallet is successfully done. but we still refused our payment when there is money on the account and 3dsecure validation done. here is the screenshot just after validation of 3dsecure with a full bank [account.
![IMG_2333](https://user-images.githubusercontent.com/59024488/71193147-ea994a80-2289-11ea-8985-9e594df87495.jpg)

**Comment by WoodyLine** [comment]
![yyy](https://user-images.githubusercontent.com/59024488/71310336-52c76800-2413-11ea-8018-7aa86023e9e2.PNG)

**Comment by WoodyLine** [comment]
I have a lot of payment like this one which is in check.

**Comment by matthewrgourd** [comment]
Hi @WoodyLine is this still happening? I will need to raise with a member of our dev team in case it's an issue at our end. However, it could be something today with customers failing their 3DS. Is that a possibility? I can't tell much from the error message I'm afraid.

**Comment by WoodyLine** [comment]
We saw with the customers and it is not 3D Sécur they accept 3D Sécur, they
have the money on their account but are unable to pay the payment is still
refused. I tried my card myself and sometimes we are refused


Le mer. 8 janv. 2020 à 17:57, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @WoodyLine, ok, thanks for the additional info. Could I have the web address of your e-commerce site so I can have a look myself?

**Comment by WoodyLine** [comment]
Hello , link : woodyline.fr

Le jeu. 9 janv. 2020 à 11:29, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @WoodyLine, ok, could I do some checks on your account? Please send me an email with your website address and Merchant ID (mgourd@vivawallet.com) referencing this issue.

**Comment by matthewrgourd** [comment]
Hi @WoodyLine I can't find any issues on your account. However, I will raise with our Shopify plugin developer in case he can shed any light.

**Comment by matthewrgourd** [comment]
Hi @WoodyLine, I'm advised that if the amount is not approved, there's nothing wrong with the integration or the plugin. You will need to contact [customer support](https://www.vivawallet.com/en-gb/contact-us) for your country to query those transactions. I'm therefore closing this issue.

**Comment by WoodyLine** [comment]
Bonjour, j’aimerais faire un virement sur un compte au Luxembourg mais
quand je rentre le Rib cela ne fonctionne pas, comment faire ? Merci de me
répondre rapidement c’est assez urgent. Bonne soirée à vous.
