### ISSUE TITLE
3D Secure 

### ISSUE THREAD

**Issue by farawayland** [VivaPayments/API#1277]
The 3D secure solution is required at checkout as our site does not keep a list of cards used at checkout by the clients

**Comment by matthewrgourd** [comment]
Hi @farawayland, I'm sorry, could you elaborate on what it is you need from us? How may we help exactly?

**Comment by farawayland** [comment]
also that the transactions are With a big delay to be process and that you have complaines because we do not store customer card information and those who do not have 3D secure set up with the card providers are unable to complete checkout regardless of number of attempts. Is it possible to get a popup for onsite 3D SMS to client phones?

**Comment by farawayland** [comment]
![image](https://user-images.githubusercontent.com/59052523/71179859-e7da2d80-2268-11ea-986e-f2b354a4618c.png)
on occasion i will pay an old debt by posting a company bond from my computer using a discarded purchase but there is no card required to flip the order to processing from pending. However, numerous clients who have no 3D secure setup are failing to complete orders since we have no method to detect the missing 3D setup with client services. A link allowing the client to get a sms is required to complete purchase.

**Comment by matthewrgourd** [comment]
Hi @farawayland I notice you're using WooCommerce on WordPress. First I need to ask you if you've installed our [official plugin](https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip) by following the instructions here: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/. There are several unsupported Viva Wallet plugins out there hence why I have to check.

**Comment by farawayland** [comment]
the developer got the plugin directly from vivawallet and it was authenticated by Marco Nobre the rep in Portugal

**Comment by farawayland** [comment]
the plugin works well and have made numerous purchases and payments to my bank  account. The vivawallet team has detected no problems with their database this morning. 
"As far as your account is concerned, we do not spot any problem regarding its functionality, so we kindly ask you to let us know about the problems your customers face as well as forwarding us a screenshot showing such issues."

**Comment by matthewrgourd** [comment]
@farawayland I'm raising this with our development team. I'll let you know when I have an answer.

**Comment by matthewrgourd** [comment]
Added to roadmap

**Comment by matthewrgourd** [comment]
Hi @farawayland, one of our developers just got back to me with the following: 

> if the card isn't 3DS enabled then the transaction will go through with liability to the issuer of the card.

I don't know if that helps at all.
