### ISSUE TITLE
Refund option not available

### ISSUE THREAD

**Issue by pdx169** [VivaPayments/API#1278]
I am trying to refund a couple of transactions that were made a few months ago from with the dashboard.

I cannot see any options to make a refund. Can you please let me know how a refund is done?

Thank you

**Comment by matthewrgourd** [comment]
Hi there, if you could send through your Merchant ID and business name to mgourd@vivawallet.com, referencing this issue, I'll have a look for you.

**Comment by pdx169** [comment]
Hi Matthew,

Thank you for the reply.

I have now worked out how to do the refunds. I was just looking through the list of transactions in the dashboard. When I search using the Sales Transactions from the menu on the left I can see the option to refund from the list of returned transactions.

Best regards,
Bart

[cid:image001.png@01D5B978.750EDCA0]

Paradox Limited
169 Old Christchurch Road
Bournemouth
BH1 1JU
United Kingdom

Tel: +44 (0)1202 314214

The information contained in or attached to this email is intended only for the use of the individual or entity to which it is addressed. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are not authorized to and must not disclose, copy, distribute, or retain this message or any part of it. It may contain information which is confidential and/or covered by legal professional or other privilege (or other rules or laws with similar effect in jurisdictions outside England and Wales). The views expressed in this email are not necessarily the views of Paradox Limited, and the company, its directors, officers or employees make no representation or accept any liability for its accuracy or completeness unless expressly stated to the contrary.
