### ISSUE TITLE
I am reissuing this problem because you didnt address nothing and you clearly can

### ISSUE THREAD

**Issue by smartfits** [VivaPayments/API#1279]
I have connected VivaWallet with Shopify but I have 2 issues
I want to change the "Credit or Debit Card" text to translate it to Greek
After the redirection to VivaPayments page the Viva Page is in english while my whole website is in greek. (vivapayments.com/web/checkout?lang=en is the default)
Below I have images with the issues
http://prntscr.com/ptofew
http://prntscr.com/ptofne

Your Reply
"Hi @smartfits
Apologies for the delayed reply.
I've spoken with our Shopfy plugin developer and apparently the button cannot be translated.
The checkout page matches the settings of your Shopify store. You will have to change the country of the shop to Greece. Then the checkout will open in Greek."

My Reply
"The language of my shopify store & shopify checkout is in greek but the vivawaller redirection is still in english
I have searched the whole shopify language text to translate the "Credit Card" text but I cannot find it. This text is controlled by the the viva app on top of shopify. They can definitely change it/"

Is is simply unacceptable for a greek company like viva to not offer a native checkout experience in greek. If the issues above are not resolved I am switching to stripe (which for some reason have on site checkout and fully translated to greek)

**Comment by matthewrgourd** [comment]
Hi @smartfits, apologies for the inconvenience. I'm not sure why this is the case so I'm checking with one of our developers. I'll get back to you as soon as I've an update.

**Comment by matthewrgourd** [comment]
Hi @smartfits, our Shopify plugin developer just got back to me. He advises that he has found the problem and it's now fixed. Please ensure that your Store Country (**Settings > General > Store Address**) is set to Greece. Thanks!
