### ISSUE TITLE
Bad Request χωρίς Error και με Ref

### ISSUE THREAD

**Issue by botonakis** [VivaPayments/API#128]
![2016-06-15_18-23-41](https://cloud.githubusercontent.com/assets/481918/16090205/61ec9558-3326-11e6-91ea-c79fce47dc5b.jpg)

Όλα μας τα αιτήματα δείχνουν το συγκεκριμένο response με errorcode=0 και κενό errortext.

Το ref υπάρχει οπότε δε μπορούμε να βρούμε που είναι το πρόβλημα.

**Comment by defilerc** [comment]
Καλησπέρα @botonakis ,

Το συγκεκριμένο order code που φαίνεται στο screenshot που μας έχετε στείλει, δεν είναι valid order code παραγωγής, γι' αυτό και το bad request που λαμβάνετε.

Θα πρέπει να έχετε δημιουργήσει αρχικά επιτυχώς ένα order code στο περιβάλλον που επιθυμείτε (demo ή live) και στη συνεχεία να κάνετε redirect στη σελίδα της viva payments χρησιμοποιώντας στην παράμετρο ?ref= το order code που δημιουργήσατε. 

Περισσότερες πληροφορίες μπορείτε να βρείτε εδώ: https://github.com/VivaPayments/API/wiki/Redirect-Checkout

Ευχαριστούμε πολύ για την επικοινωνία.
