### ISSUE TITLE
Προβλημα με Native Checkout v2

### ISSUE THREAD

**Issue by greekuser987** [VivaPayments/API#1280]
Καλησπέρα

Προσπαθώ να μεταβώ στην καινούργια σας πλατφόρμα  Native Checkout v2
κάνοντας δοκιμές με ένα demo Viva Account 

Χρησιμοποίω ASP.NET

Έκανα επιτυχώς τα 4 steps όπως τα γράφετε στην σελίδα https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

**στο 5ο step παίρνω πάντα response (401)  unauthorized**

Αφου έχω πάρει το charge token.

Κάνω π.χ. HTTP request στο Url (με το Authorization Header):
https://demo-api.vivapayments.com/nativecheckout/v2/transactions

και PostData:
{"ammount":1321,"preauth":false,"sourceCode":"5916","chargeToken":"ctok_40luDk1Hn82hphj-aBi39P-PqBs","Installments":1,"merchantTrns":"asdf adsfadsf","customerTrns":"234234343","currencyCode":978,"customer":{"email":"greekuser987@gmail.com","phone":"3453453453454","fullname":"John Doe","requestLang":"en","countryCode":"GR"}}

**Comment by matthewrgourd** [comment]
Hi @greekuser987 do you use the bearer token in the authorization header as described [here](https://developer.vivawallet.com/authentication/#demo-environment)? 401 implies that there is an issue in this area.

**Comment by matthewrgourd** [comment]
Closing as no reply.
