### ISSUE TITLE
Viva checkout issues-clarifications for use of the platform in other languages

### ISSUE THREAD

**Issue by pvflessa** [VivaPayments/API#1281]
We recently used viva payment on behalf of a client for his website. He has submitted certain questions and raised issues he requires assistance with. 

- what happens if a buyer does not use a cellphone? Is there an alternative method of receiving the OTP code or is he disqualified from using the platform?
- OTP FORM: Depending on the website's language, I send the corresponding "requestLang" but still the OTP form remains in Greek.
- OTP FORM: Can the word 'Submit" appear in Greek? The "cancel" choice is in Greek but the "Submit" choice remains in English.
- The confirmation email the buyer receives from Viva is in Greek. How can he receive it in English?
- In the confirmation email the buyer receives, is there a way to include an SKU for the purchased product?

If the above are viva platform issues, can you pleasse advise how we can resolve them? If not, please indicate which of the above issues have to do with our platform (that has incorporated the viva payment checkout platform).

**Comment by matthewrgourd** [comment]
Hi there, please can I have the web address of your client (where you added our payment gateway) and could you confirm which method was used to integrate with our platform ([online checkout](https://developer.vivawallet.com/online-checkouts), e-commerce [plugin](https://developer.vivawallet.com/e-commerce-plugins) or [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/)).

**Comment by pvflessa** [comment]
Hi there, Can I send you a private message with the link and the credentials? The website is under construction and it is password-protected. So can you provide an e-mail address? Also I have used the Payment API method.

**Comment by matthewrgourd** [comment]
Hi @pvflessa thanks, you can email me directly at mgourd@vivawallet.com. Thanks for confirming the integration route.

**Comment by pvflessa** [comment]
Hello, last Tuesday I sent you an email with the credentials. I haven't had any news from you since and I wonder If you  received it.

**Comment by matthewrgourd** [comment]
Hi @pvflessa, yes, thanks! Can I ask you if by "OTP form" you mean 3DS popup?

**Comment by pvflessa** [comment]
Hello, by "OTP form" I mean this form https://cl.ly/22bad3f30e3e

**Comment by matthewrgourd** [comment]
Hi @pvflessa anything to do with the OTP form is generated by the card issuer, not by us. There is no way of making any adjustments here. If your client's Viva Wallet was set up in Greece, all confirmation emails will be in Greek. An SKU cannot be included, I'm afraid.
