### ISSUE TITLE
I need to access the wallets and their transactions.

### ISSUE THREAD

**Issue by gkourtis** [VivaPayments/API#1284]
I follow the directions of the account api, I am able to get the token, but at the end when I do the get to I get a "403 Forbidden
nginx/1.4.6 (Ubuntu)"

I am doing the get from "https://uat-api.vivapayments.com/api/Wallets';

Does the account api works correctly ?

**Comment by matthewrgourd** [comment]
Hi @gkourtis apologies, although it's mentioned in the documentation, our Account API has yet to be launched. I don't know when it will be live.
