### ISSUE TITLE
Migrating from Native Checkout v1 (wordpress-site)

### ISSUE THREAD

**Issue by atr0x23** [VivaPayments/API#1286]
Hello,

Our programmer isn't available this period and I need your help to migrate online vivapayments to V2.

My company's e-shop is: coffeebrandsdelivery.gr and is a wordpress. Now it is using a plugin which is: VivaPayments WooCommerce Payment Gateway by emspace.gr. Is there a new plugin that I have to download an replace this one, or what is the procedure I have to follow to fix it? Do I need to add some code? if yes, on which specific file on my site? Please tell me what steps I have to follow to begin the migration. I already had a look on this link (https://developer.vivawallet.com/authentication/) on step 2 didn't understand much.  

Thanks in advance
I am waiting for your response.

**Comment by matthewrgourd** [comment]
Hi there, if you're using our official plugin for WooCommerce you don't need to make any changes as it is already 3DS enabled. However, it sounds like you've installed something else in which case please follow the instructions below to download and install Viva Wallet for WooCommerce after removing any previous versions.

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
