### ISSUE TITLE
OpenCart 3 "Trying to get property 'ErrorCode' of non-object"

### ISSUE THREAD

**Issue by KAILone** [VivaPayments/API#1288]
When I'm trying to checkout on the demo profile I get this error: 
![Screenshot](https://user-images.githubusercontent.com/11787805/71558954-55543e00-2a61-11ea-8962-490b3c5eafe9.png)

And the code is:
<img width="798" alt="Screenshot" src="https://user-images.githubusercontent.com/11787805/71558796-8cc1eb00-2a5f-11ea-9255-64a0e049b2df.png">

Why doesn't it see the objects?

**Comment by VivaWalletSupport** [comment]
Hello, you get a notice, not an error. Disable notices on a production environment.

**Comment by KAILone** [comment]
> Hello, you get a notice, not an error. Disable notices on a production environment.

Ok. But when I click on “confirm checkout” I get 404 error on https://www.vivapayments.com/web/newtransaction.aspx

![B0A500B2-5D7D-4E18-9D6D-20614E378171](https://user-images.githubusercontent.com/11787805/71572569-714ef280-2ae8-11ea-8177-70733cac0454.jpeg)

**Comment by VivaWalletSupport** [comment]
Please provide following screenshots:

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by KAILone** [comment]
@VivaWalletSupport 
1) Plugin setting:
![E219D4E1-5DCF-42F2-B50F-FDD7DB6369ED](https://user-images.githubusercontent.com/11787805/71577004-2e4a4a80-2afb-11ea-9729-ad90e7c371bb.jpeg)
2) Not quite sure what is that. 
3) Website page:
![33C09D55-CCEE-4B17-A04E-1E1532DADA3F](https://user-images.githubusercontent.com/11787805/71577011-386c4900-2afb-11ea-9a31-93d28d2524a9.png)
4) API page:
![35116E02-FD07-48A6-8CEB-62AC752B15F4](https://user-images.githubusercontent.com/11787805/71577019-41f5b100-2afb-11ea-8da5-76be1c3d5773.jpeg)

**Comment by VivaWalletSupport** [comment]
You are using the live URLs in the plugin settings mixed with the credentials from your Viva demo account.

**Comment by KAILone** [comment]
Oh. My bad. I tried to use the wrong demo site before. www.demo.vivapayments.com instead of just demo.vivapayments.com. 
Thank you.
