### ISSUE TITLE
Need to download transactions as CVS file

### ISSUE THREAD

**Issue by Planthaya** [VivaPayments/API#1289]
I need to download a CVS file of transactions to upload onto accounting software but don't seem to be able to find an option to do so

**Comment by gkourtis** [comment]
I need the same but programmatically in order to update our accounting software

**Comment by matthewrgourd** [comment]
@Planthaya there should be an 'Export to Excel' button on the following page in the banking app: https://members.vivawallet.com/selfcare/en/sales/mysales

@gkourtis Apologies, we don't currently have a function available to do this via our API.
