### ISSUE TITLE
OsCommerce - Viva Payment

### ISSUE THREAD

**Issue by icop** [VivaPayments/API#129]
Καλημέρα ,θα ήθελα να σας ρωτήσω τι διαδικασία πρέπει να ακολουθήσω έτσι ώστε να εγκαταστήσω το vivapayment στο website μου το οποίο είναι OsCommerce. Έχω περάσει ένα module το οποίο κατά την ολοκλήρωση της παραγγελίας μου λέει ότι η παραγγελία ολοκληρώθηκε χωρίς να γίνεται πληρωμή στο λογαριασμό στη Viva .. Αν έχετε να μου προτείνετε κάτι διαφορετικό θα βοηθούσε πολύ.

Ευχαριστώ εκ των προτέρων

**Comment by defilerc** [comment]
Καλησπέρα @icop ,

Θα πρέπει να μας στείλετε περισσότερες πληροφορίες για να μπορέσουμε να σας βοηθήσουμε, όπως το order code που δημιουργήθηκε, καθώς και το συγκεκριμένο error το οποίο λαμβάνετε.

Ευχαριστούμε πολύ για την επικοινωνία.
