### ISSUE TITLE
NativeCheckout v2 ERROR 502 

### ISSUE THREAD

**Issue by vasilevich** [VivaPayments/API#1291]
Hello, I've tried to implement /nativecheckout/v2/transactions in PHP 

Getting TOKEN with 0AUTH2:  OK
Getting Charge Token 3DS system : OK
Getting Order Code : OK
**Performing the actual transaction with the charge token : FAIL** 
I send:
```
array(8) {
  ["amount"]=>
  int(24994)
  ["preauth"]=>
  bool(false)
  ["sourceCode"]=>
  int(5711)
  ["OrderCode"]=>
  int(1441150996218910)
  ["chargeToken"]=>
  string(32) "ctok_RhO_Sc3TzY-5l8OKDeD4QtoHeu8"
  ["Installments"]=>
  int(1)
  ["currencyCode"]=>
  int(826)
  ["customer"]=>
  array(4) {
    ["email"]=>
    string(20) "testtest@hotmail.com"
    ["phone"]=>
    string(19) "+444324324234235323"
    ["fullname"]=>
    string(10) "eliav laav"
    ["requestLang"]=>
    string(2) "en"
  }
}
```

I recieve:

```
array(3) {
  ["status"]=>
  int(502)
  ["message"]=>
  string(18) "Transaction failed"
  ["eventId"]=>
  string(5) "10005"
}
```

According to your documentation: Error 502 is on your(vivawallet.com) side

Please resolve the issue, or atleast give the appropiate error message.
### Please note! in Demo this code worked fine, however in LIVE it returns the error 502 code.
Thanks!

**Comment by matthewrgourd** [comment]
Hi there, there appears to be an x-viva-eventId returned of 10005 meaning the issuing bank declined the transaction without an explanation. Have you tried using a different card?

https://developer.vivawallet.com/api-reference-guide/error-codes/

**Comment by vasilevich** [comment]
yes, since then different cards worked, please add more detailed errors next time in the response,  because your documentation says 502 is on YOUR side.

thanks

**Comment by matthewrgourd** [comment]
The error code of '10005' that I mentioned is documented and clearly states that the problem is at the card issuer end. Best wishes.
