### ISSUE TITLE
Getting Access Denied issue for Live environment and instances are already of https

### ISSUE THREAD

**Issue by rajdeeporbsys** [VivaPayments/API#1292]
Hello,

Am getting access denied error while going for viva wallet checkout page.

Access Denied
You don't have permission to access "http://www.vivapayments.com/web/checkout?" on this server.
Reference #18.51c2017.1577963421.b8b518f9

Please resolve

**Comment by matthewrgourd** [comment]
Sorry to hear this. Can you send me a link to the page before the Viva Wallet checkout page?

**Comment by matthewrgourd** [comment]
Hi @rajdeeporbsys please send through some more information so we can investigate, otherwise I'll need to close this issue.
