### ISSUE TITLE
Redirection/Native Checkout v2 Problem

### ISSUE THREAD

**Issue by Harshp13** [VivaPayments/API#1293]
Hi, ever since i have had viva wallet merchant i have some orders that do not go through after customers try to place orders they get cancelled.

Can i have some assistance please ?

Regards

**Comment by matthewrgourd** [comment]
Hi @Harshp13 sorry to hear this. Please can you tell me which of our products / services you're using. Is it an e-commerce [plugin](https://developer.vivawallet.com/e-commerce-plugins) (e.g. Viva Wallet for WooCommerce or Shopify), [online checkout](https://developer.vivawallet.com/online-checkouts) or are you integrating using our [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/)? Can you also let me know the web address of the site with the problems. Thanks!

**Comment by Harshp13** [comment]
Viva Wallet for WooCommerce
https://cbdhempking.co.uk/

**Comment by matthewrgourd** [comment]
Looks like you're using an unofficial Viva Wallet plugin for WooCommerce. Please remove the current version then download and install the correct plugin using the below installation instructions.

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by Harshp13** [comment]
![Screenshot (136)](https://user-images.githubusercontent.com/59532354/71838458-c2df1a80-30b0-11ea-98e3-e9e6aed9e7cb.png)

ok i have done that what does installments mean what do i set it to ?

**Comment by matthewrgourd** [comment]
Hi @Harshp13, I'm sorry, but that's not our official Viva Wallet for WooCommerce plugin. You can download the correct one, along with detailed installation instructions, from here: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

The plugin you currently have installed was developed by a Greek hosting company called 'Papaki' and more specifically by its parent company 'Enartia'.

Hope this helps!

**Comment by Harshp13** [comment]
Ok i followed instructions and downloaded the zip and uploaded and it looks like i already had that one in the first place ?

So this is still not resolved ?

**Comment by matthewrgourd** [comment]
Hi there, the screenshot you sent about one day ago showed a URL containing the word 'papaki' meaning you definitely weren't using our plugin. If you now have the correct plugin installed your settings page shouldn't contain any reference to the other product. Can you send a screenshot through again so I can confirm?

**Comment by Harshp13** [comment]
![Screenshot (137)](https://user-images.githubusercontent.com/59532354/71930980-a87e6d00-3194-11ea-9d8d-075a55f82879.png)

I am still getting cancelled orders

**Comment by Harshp13** [comment]
![Screenshot (139)](https://user-images.githubusercontent.com/59532354/71931063-debbec80-3194-11ea-95cc-f6961ca02fc2.png)

I am still getting orders cancelled

**Comment by matthewrgourd** [comment]
I'd advise you to [contact the support team](https://wordpress.org/support/plugin/woo-payment-gateway-for-vivapayments/) for the plugin you've installed (which is not ours). Alternatively, remove your current plugin and [install the official Viva Wallet extension](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/). Hopefully after that you should not receive any errors. If you still get orders cancelled after that maybe you can try changing the default timeout as described [here](https://github.com/VivaPayments/API/issues/1294#issuecomment-571177161).

**Comment by Harshp13** [comment]
What do you mean install the official viva wallet ? i have already followed that instruction and that plugin installed in the first place version 3.57.7 i already had this can you explain how to change the default timeout ?

**Comment by Harshp13** [comment]
Ok the payment timeout is set to 300 default what do i change it to ?

**Comment by matthewrgourd** [comment]
Hi @Harshp13 I suggest 600 seconds which is 10 minutes.

**Comment by Harshp13** [comment]
Still getting same problem ?

**Comment by matthewrgourd** [comment]
Hi @Harshp13, apologies, I replied to you previously without checking the second screenshot you sent through. That is indeed our official plugin now. If you've increased the default timeout then we can rule that out as the issue. What I found just now was that there's definitely something weird going on with your checkout when I attempt to pay using Viva Wallet. Do you have any error logs that you can share with me?

**Comment by Harshp13** [comment]
![Screenshot (140)](https://user-images.githubusercontent.com/59532354/72066166-ca343d00-32d7-11ea-8db2-aac8ee4c782a.png)

**Comment by Harshp13** [comment]
![Screenshot (141)](https://user-images.githubusercontent.com/59532354/72066472-960d4c00-32d8-11ea-8b9b-c95c88e41101.png)
![Screenshot (140)](https://user-images.githubusercontent.com/59532354/72066476-960d4c00-32d8-11ea-8548-fb08de36d7b9.png)

I have never had this before on my vivawallet account after checking today

**Comment by Harshp13** [comment]
What is the issue ?

**Comment by matthewrgourd** [comment]
Hi @Harshp13 I've checked with our Customer Service team and the problem is your monthly transaction limits need to be increased. Apparently the only way to do this is to send a message to support@vivawallet.com from your registered email address. You'll need to include your Merchant ID, business name and the purpose of the email. For the latter, mention that Matt Gourd from GitHub support has investigated your account and your limits need increasing in order to avoid failed transactions. We should be able to sort this out very quickly once you've sent the email. Thanks!

**Comment by Harshp13** [comment]
Will they get back to me by today or tomorrow ?

**Comment by Harshp13** [comment]
These are the limits  Acquiring (CP & CnP)
Per Transaction
£250
Daily
£500
Monthly
£3,000
Yearly
£15,000

I am pretty sure i have not done £3000 monthly ?

**Comment by Harshp13** [comment]
I have just had one payment go through so i don't think it's to with limits

**Comment by matthewrgourd** [comment]
@Harshp13 There was another limit I saw on your account of 100 transactions per month. I'll check with support and get back to you once I've confirmed if it needs removing. I'm not 100% clear on what needs to happen as it's a different department. Apologies again for any inconvenience caused.

**Comment by Harshp13** [comment]
I am still getting some orders completed and some cancelled

**Comment by Harshp13** [comment]
This is urgent please i am losing customers

**Comment by matthewrgourd** [comment]
Hi @Harshp13 I'm chasing for you. The issue is we need to raise your limit profile. It is in progress and I'll keep checking!

**Comment by Harshp13** [comment]
Are you 100% this is the problem ?

**Comment by matthewrgourd** [comment]
Hi @Harshp13 yes, but I gather you may not be eligible for a limit increase for another 6 months so not a lot else I can do, unfortunately. May I ask when you were registered as a company or are you a sole trader? Apparently you need to have been operating for at least a year.

**Comment by Harshp13** [comment]
16/04/2019 Then why i am still getting some payments ? and when does the limit rest ?

**Comment by Harshp13** [comment]
I am sole trader

**Comment by matthewrgourd** [comment]
You should have received an email from our customer service now saying you're not currently eligible for an upgrade to your limits. You need to be set up with us for at least a year. Previously you said you weren't exceeding £3000 a month in incoming transactions. However, I checked December just now and you were just over. However, I wouldn't have thought this would affect January. Can you tell me when you set up WooCommerce initially, as in, on what date?

**Comment by Harshp13** [comment]
I have received a email and yes i have not done £3000 in a month i can't have i set that up in February  2019 and January is a new month so how is it possible i done £3000 this month ?

You were talking about another 100 transactions limit ?

**Comment by matthewrgourd** [comment]
Hi @Harshp13, I just checked your payment source settings and there was an error in the success / failure URLs. Hopefully should be fine now!

**Comment by Harshp13** [comment]
so that was the problem ? i have not reach no limits ?

**Comment by matthewrgourd** [comment]
I believe so, yes

**Comment by Harshp13** [comment]
Hey can you change it back to what it was this is not problem still getting cancelled order i am getting really unhappy with this service nothing is working ????

**Comment by Harshp13** [comment]
Hold on i just changed https to http

**Comment by Harshp13** [comment]
still problem

**Comment by matthewrgourd** [comment]
Please provided the following screenshots and we will look into the issue further:

* Payment module settings from [WooCommerce / Payments tab](https://developer.vivawallet.com/images/WooCommercePaymentsTab.png?classes=border&width=900) (mask the API Key).
* Viva Wallet [payment source settings](https://developer.vivawallet.com/images/NewPaymentSource.png) (include the browser's URL in the screenshot).
* Viva Wallet [Websites/Apps page](https://developer.vivawallet.com/images/WebsitesSubmenu.png?classes=border&width=900) (include the browser's URL in the screenshot).
* [API Access page](https://developer.vivawallet.com/images/API%20Access.png?classes=border&width=900) (mask API Key (include the browser's URL in the screenshot).

Thanks!

**Comment by Harshp13** [comment]
![Screenshot (143)](https://user-images.githubusercontent.com/59532354/72254925-55297600-35fd-11ea-9b3a-623e803e19a1.png)
![Screenshot (144)](https://user-images.githubusercontent.com/59532354/72254926-55297600-35fd-11ea-838f-ab996f432d2c.png)
![Screenshot (146)](https://user-images.githubusercontent.com/59532354/72254927-55c20c80-35fd-11ea-9508-d3c991f75cce.png)
![Screenshot (142)](https://user-images.githubusercontent.com/59532354/72254929-55c20c80-35fd-11ea-8c8d-46f9c10b3f0c.png)

**Comment by Harshp13** [comment]
I have a made a call to vivawallet there were also saying about the limits they will call me back at the end of the day

**Comment by Harshp13** [comment]
You can closed this now the issue has been sorted
