### ISSUE TITLE
Redirect Checkout - cancelled transactions

### ISSUE THREAD

**Issue by Oanicica** [VivaPayments/API#1294]
hello!

Merchant Abundant hamza s.r.l is using redirect checkout for his website hamza.ro, built on WordPress.
Issue no.1: They have a lot of cancelled transactions (photos attached). 
Let me know what details do you need in order to get it from them and resolve this issue. 

Issue no.2: they want to accept payments in EUR (from cards issues in EUR). what do they need to do?
<img width="287" alt="Hamza 2" src="https://user-images.githubusercontent.com/53224411/71811143-a4f7c280-307c-11ea-8eaa-76bf31bcc17d.png">
<img width="287" alt="hamza" src="https://user-images.githubusercontent.com/53224411/71811144-a5905900-307c-11ea-8dde-0a133c8a1b22.png">

**Comment by matthewrgourd** [comment]
Hi @Oanicica, sorry to hear you're experiencing difficulties. Looks like you're using the default timeout for payments which is only 300 seconds (5 minutes). You need to set the parameter to your own preference or `65535` if you want a payment order to never expire. Please see `PaymentTimeOut` under [Create payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments) in our API reference guide for full details.

**Comment by Oanicica** [comment]
@matthewrgourd The modification is ok to be done in our module? they found the problem but they say it's set this way and the modification will affect other users and future releases as well. I hope I'm making sense :)

**Comment by matthewrgourd** [comment]
Hi @Oanicica which module are you using, can you tell me where you downloaded it from? Sounds like it might not be our official package.

**Comment by Oanicica** [comment]
Hi @matthewrgourd . They took it from here: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/. 
Version 3.5.7.
![WhatsApp Image 2020-01-07 at 10 37 30 Hamza](https://user-images.githubusercontent.com/53224411/71881042-38db9400-313a-11ea-9f6f-36d13e526679.jpeg)

**Comment by matthewrgourd** [comment]
Hi @Oanicica, ok, so you're using our official WooCommerce plugin, great! So all you have to do is adjust the timeout value by editing the wc-vivawallet.php file that is located in the plugin folder. change PaymentTimeOut=300 to the desired amount of seconds. The plugin folder is located here in your WordPress folder hierarchy: `wp-content\plugins\vivawallet-for-woocommerce`. Please get back to me if any further issues or, if not, close this issue.

**Comment by Oanicica** [comment]
@matthewrgourd  Everything is ok! Thank you very much for your help!
