### ISSUE TITLE
Getting Viva wallet website app to be active and redirect issue

### ISSUE THREAD

**Issue by championcbd** [VivaPayments/API#1295]
We have 2 issues. 
1. 
The first is we have created a website/app for the WordPress woocommerce website as denoted here https://developer.vivawallet.com/e-commerce-plugins/woocommerce/.  After creating this, we have waited for over a week only for this message to appear:
"Changes to existing electronic sources might need to be approved first by Viva Payments. Please keep in mind that this action can temporarily turn this source inactive."

2. After resorting to using the Default website app, which was the only one that was active, we were able to run the payment through successfully but it does not redirect the customer to the order received page nor does it trigger order processing on woocommerce and therefore does not send customer order emails.

Please respond ASAP.

**Comment by matthewrgourd** [comment]
Hi there, you definitely need to create a new source that's separate from the default one. It shouldn't take more than a couple of days to move to active status. However, I think we email you. Please try again, checking we have the right email address registered against you. If you experience any further problems please email me at mgourd@vivawallet.com with your Merchant ID referencing this issue.

**Comment by Harshp13** [comment]
Ok i have done that but i was getting this issue before i hit the limits ?

**Comment by matthewrgourd** [comment]
@Harshp13 ok, but it still could be connected. All I can suggest now is you wait to see what happens once the limits have been raised. If you experience any further issues do please get back to me!
