### ISSUE TITLE
Urgent 

### ISSUE THREAD

**Issue by indicabeauty** [VivaPayments/API#1296]
I’ve submitted all ID etc. It’s ok taking payments fine but can’t make payments from account it’s saying contact support for more. Could you please fix this issue ASAP.
As we would like to launch today Thanks

**Comment by matthewrgourd** [comment]
Hi @indicabeauty, sorry to hear you're experiencing problems. Can I just check if you're attempting to make payments using your Viva Wallet business debit card? Or is it transfers to another account you can't action? I'll need to check your account in the first instance. Please send me an email containing your Merchant ID and business name and referencing the GitHub issue number (#1296): mgourd@vivawallet.com.

**Comment by indicabeauty** [comment]
Hi,

The merchant id is 34389344 the business name is Indica Beauty Ltd

It wont let us make transfers as its saying the feature is disabled contact support.
We want to launch our business this evening and wouldl ike this resolved before hand.

Thanks
Tomas William-Grimwood

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by matthewrgourd** [comment]
That's not your Merchant ID unfortunately. Ok, sounds like transfers are disabled so you'll need to contact support anyway. Please dial the appropriate number from our [Contact us](https://www.vivawallet.com/en-eu/contact-us/) page.
