### ISSUE TITLE
Prestasho ERROR 502

### ISSUE THREAD

**Issue by itskold** [VivaPayments/API#1297]
Bonjour,

J'ai une site d'une cliente qui est client chez Vivawallet malgré la configuration et la revérification de la document tout est correctement respecté. A chaque fois, qu'un client désire aller dans le Checkout de son panier, le site plante et charge indéfiniment. J'ai essayer plusieurs variable pour voir d'où vient le problème et il s'avére etre du au module de Vivawallet. Voici tout les captures d'écran que j'ai juger utile. Bien à vous, j'aurai besoin d'une réponse assez rapidement ma cliente s'impatiente.
<img width="1111" alt="Capture d’écran 2020-01-07 à 23 13 15" src="https://user-images.githubusercontent.com/46155667/71933826-5264f600-31a3-11ea-8a1c-2409abb673ef.png">
<img width="888" alt="Capture d’écran 2020-01-07 à 23 11 09" src="https://user-images.githubusercontent.com/46155667/71933827-5264f600-31a3-11ea-84ea-5acb01f74821.png">
<img width="601" alt="Capture d’écran 2020-01-07 à 23 06 05" src="https://user-images.githubusercontent.com/46155667/71933829-5264f600-31a3-11ea-8679-f49d53dc28b5.png">
<img width="631" alt="Capture d’écran 2020-01-07 à 23 14 43" src="https://user-images.githubusercontent.com/46155667/71933913-82ac9480-31a3-11ea-9185-80be76d8d737.png">

**Comment by itskold** [comment]
l'API Key a été caché volontairement

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear your client has been experiencing issues. I believe the problem may be that payment source 6084 is still pending. I'm not sure why this is. I'll get one of my colleagues to activate it as soon as possible.

**Comment by itskold** [comment]
> Hi there, sorry to hear your client has been experiencing issues. I believe the problem may be that payment source 6084 is still pending. I'm not sure why this is. I'll get one of my colleagues to activate it as soon as possible.


Thank you. If you can do it as soon as possible please. thank you so much

**Comment by matthewrgourd** [comment]
Hi @itskold an email with some instructions has been sent to info@parisis.be by our customer service team. This has to be responded to and action taken by your client before the payment source can be activated. Hope this helps!

**Comment by itskold** [comment]
> Hi @itskold, an email with some instructions has been sent to [info@parisis.be](mailto:info@parisis.be) by our customer service team. This has to be responded to and action taken by your client before the payment source can be activated. Hope this helps!

It isn’t the good mail address. The correct mail is info@par-isis.be

**Comment by matthewrgourd** [comment]
I'm requesting a resend to the good email :-)

**Comment by itskold** [comment]
> I'm requesting a resend to the good email :-)

Hi,
I haven't received anything yet .. is this normal?

**Comment by matthewrgourd** [comment]
Apparently it was sent 25 minutes ago, all good now?

**Comment by matthewrgourd** [comment]
Hi @itskold I'm told your payment source is active now so I'm closing this issue.

**Comment by itskold** [comment]
> Hi @itskold I'm told your payment source is active now so I'm closing this issue.

The account is activated, but the problem is still there! The module always puts an ERROR 502 during CHECKOUT!!
