### ISSUE TITLE
Refund Issue (Live Payments)

### ISSUE THREAD

**Issue by alkatsaros** [VivaPayments/API#1298]
Καλησπέρα σας,

προσπαθώντας να κάνω ένα refund για μια συναλλαγή για την οποία έχει περάσει μια ημερολογιακή ημέρα έχω το παρακάτω response. Στο demo.vivapayments δεν είχα κάποιο θέμα. Μπορεί να παίζει ρόλο που ακόμα δεν έχει ολοκληρωθεί η ταυτοποιηση του λογαριασμού;

{
    "Emv": null,
    "Amount": null,
    "StatusId": "E",
    "CurrencyCode": null,
    "TransactionId": null,
    "ReferenceNumber": null,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ThreeDSecureStatusId": null,
    "ErrorCode": 403,
    "ErrorText": "Refund is disabled for the merchant 4c5075b5-0277-4a6d-ba55-525042727bd5",
    "TimeStamp": "2020-01-09T11:29:15.4900119+02:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": false
}

Ευχαριστω

**Comment by matthewrgourd** [comment]
Hi @alkatsaros, debits appear to be disabled on your account. Please call customer service to see what can be done: (+30) 211 7604 000. Thanks!

**Comment by alkatsaros** [comment]
Hi @matthewrgourd  and thanks for the quick response. 

I had a call with customer service and they asked me to ask you some more details about the the issue.

Thanks

**Comment by matthewrgourd** [comment]
The issue that credits are disabled on your account for some reason so they (customer service) need to re-enable once they've made some checks.

**Comment by alkatsaros** [comment]
@matthewrgourd thanks! It seems it has to do with account account verification.
Thanks for your help!
