### ISSUE TITLE
Payment issue with digital products

### ISSUE THREAD

**Issue by xrusap** [VivaPayments/API#1299]
Hello,
 I have a problem with the pluggin viviawallet for woocomerce. I try to create a e-shop with digital products where my costumers when they pay with credit cards, they can downlaod the product. But by testing the pluggin vivawallet for woocomerce  while a successful payment message is displayed, the product is not displayed for the user to download. What can I do about this, please help me.

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. First, can you confirm that you installed our official plugin by following [these installation instructions](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) on the Viva Wallet Developer Portal? Thanks!

**Comment by matthewrgourd** [comment]
Hi @xrusap are you still having issues with the setup of your plugin?

**Comment by matthewrgourd** [comment]
Closing as no reply...
