### ISSUE TITLE
λάθος Bad Request

### ISSUE THREAD

**Issue by stonekgraff** [VivaPayments/API#130]
καλησπέρα σας
εχω πρόβλημα με την συναλλαγή μεσω viva
ενώ στην αρχή λειτουργούσε κανονικά πλέων δεν μπορούμε να κάνουμε συναλλαγές.
με το που πατάει κάποιος ολοκλήρωσης της παραγγελίας μας πετάει σε ενα παράθυρο της viva 

https://www.vivapayments.com/web/newtransaction.aspx?ref=
με το λάθος Bad Request

εχουμε ξανα στείλει για το θέμα μας με κωδ.βλάβης:4409877
αλλα αυτο που μας είπαν ειναι οτι ειναι τα url και τα δύο ίδια 

URL Επιτυχημένης συναλλαγής: index.php?route=payment/viva_payments/callback 
URL Αποτυχημένης συναλλαγής: index.php?route=payment/viva_payments/callback

το θέμα ειναι οτι για να σε γυρίσει σε επιτυχία η αποτυχία συναλλαγής πρέπει πρώτα να την κάνεις την συναλλαγή
τώρα εχουμε αυτο το λαθος...

να σημειωθεί  οτι το extension που εχουμε για το opencart για viva το χρησιμοποιουμε κατα κόρον χωρίς κανενα πρόβλημα 

το site ειναι
babytunes.gr

**Comment by defilerc** [comment]
Καλησπέρα @stonekgraff ,

Ενδεχομένως να υπάρχει θέμα με την έκδοση OpenSSL που έχει ο server σας.

Δείτε περισσότερα σε [αυτό το άρθρο](https://support.vivawallet.com/hc/en-us/community/posts/200568401-Site-not-responding-when-called-from-PHP-code)

**Comment by stonekgraff** [comment]
Ο κώδικας που μου λέτε να βάλω υπάρχει ήδη, δεν ειναι θεμα του σέρβερ γιατι
στον ιδιο σέρβερ τρέχω με το ιδιο σκρίπτ αλλα 20+ eshop και μόνο σε αυτο
εχω πρόβλημα.
Σας παρακαλώ δείτε το γιατι ο πελάτης μου εχει θεμα με της πωλήσεις του

Στις Παρασκευή, 17 Ιουνίου 2016, ο χρήστης Kostas Athanasoglou <
notifications@github.com> έγραψε:

> Καλησπέρα @stonekgraff <https://github.com/stonekgraff> ,
>
> Ενδεχομένως να υπάρχει θέμα με την έκδοση OpenSSL που έχει ο server σας.
>
> Δείτε περισσότερα σε αυτό το άρθρο
> <https://support.vivawallet.com/hc/en-us/community/posts/200568401-Site-not-responding-when-called-from-PHP-code>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/VivaPayments/API/issues/130#issuecomment-226754360>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATDMc9S0Kp9M24-rY557PqNl5ihQ2iBGks5qMpBlgaJpZM4I3V64>
> .
>


-- 
Εστάλη από iPhone

**Comment by defilerc** [comment]
Καλημέρα @stonekgraff,

Μπορείτε να μας στείλετε το request που κάνετε για τη δημιουργία του order (CreateOrder), καθώς και το response που παίρνετε για να μπορέσουμε να δούμε τι γίνεται;

Ευχαριστούμε πολύ.

**Comment by stonekgraff** [comment]
Συγνώμη δεν εχετε λάβει τι μήνυμα λαμβάνουμε τοσο καιρό?

μετα απο επιλογή συναλλαγής με viva μας πετάει στο site
https://www.vivapayments.com/web/newtransaction.aspx?ref=
με blank page με error BAD Request και τπτ αλλο

εμεις δεν εχουμε Επιτυχημένη/Αποτυχημένης url διαφορετικά

URL Επιτυχημένης συναλλαγής: index.php?route=payment/viva_payments/callback
URL Αποτυχημένης συναλλαγής: index.php?route=payment/viva_payments/callback

αλλα δεν φτάνουμε ποτέ σε κάτι τέτοιο



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

------------------------------------
*Dimitris Botakis*

*Graphic - webdesigner**tel.* .: +302396112070
*mob*.:+306943987559
*e-mail*:thess.webdesigner@gmail.com
*web*: www.stonekgraph.com

Στις 22 Ιουνίου 2016 - 11:09 π.μ., ο χρήστης Kostas Athanasoglou <
notifications@github.com> έγραψε:

**Comment by dpnevmatikos** [comment]
Καλησπέρα @stonekgraff 
Το πρόβλημα που έχετε ξεκινάει από το γεγονός οτι η δημιουργία παραγγελίας αποτυγχάνει, και εξαιτίας αυτού δεν έχετε κωδικό παραγγελίας όταν κάνετε redirect στην checkout:
https://www.vivapayments.com/web/newtransaction.aspx?ref=  (η παράμετρος ref δεν εχει τιμή)

Δεδομένου οτι ο λογαριασμός σας έχει ελεγχθεί και δεν φαίνεται να υπάρχει κάποιο πρόβλημα,
δεν υπάρχει άλλος τρόπος να εντοπίσουμε το πρόβλημα σας για αυτό και σας ζητάμε συγκεκριμένα το error που παίρνετε κατά την διαδικασία της δημιουργίας κωδικού πληρωμής.

Ευχαριστούμε

**Comment by stonekgraff** [comment]
αυτο που σας εστειλα ειναι το error που παίρνω , αυτο μπορειτε να το δείτε
και εσεις.

θελα να σας πω πως το συγκεκριμένο σκριπτ το χρησιμοποιώ και σε αλλα σαιτ
και δουλεύουν κανονικα , στον ιδιο σερβερ.
επίσης στην αρχη της εγκατάστασης καναμε κανονικά συναλλαγές , τωρα τι
έγινε?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

------------------------------------
*Dimitris Botakis*

*Graphic - webdesigner**tel.* .: +302396112070
*mob*.:+306943987559
*e-mail*:thess.webdesigner@gmail.com
*web*: www.stonekgraph.com

Στις 22 Ιουνίου 2016 - 12:31 μ.μ., ο χρήστης Dimitris Pnevmatikos <
notifications@github.com> έγραψε:

**Comment by defilerc** [comment]
Καλημέρα @stonekgraff ,

Το error που παίρνετε στη σελίδα της checkout, προέρχεται από το γεγονός ότι δεν έχει επιτύχει η δημιουργία της παραγγελίας σωστά (CreateOrder).

Η διαδικασία είναι ως εξής:

1. Δημιουργία της παραγγελίας με κλήση στην CreateOrder
2. Redirect στην checkout σελίδα με την παράμετρο ref να περιέχει τον κωδικό πληρωμής που πραγματοποιήθηκε στο προηγούμενο βήμα.

Θα πρέπει να ανατρέξετε στα logs του opencart plugin που χρησιμοποιείτε, ώστε να δείτε το error που παίρνετε από το βήμα 1, για να επιβεβαιώσετε ότι οι παράμετροι που χρησιμοποιείτε είναι σωστές. Μπορείτε να μας στείλετε επίσης το request που στέλνετε για την CreateOrder, όπως επίσης και την απάντηση που παίρνετε, ώστε να βρούμε τι ακριβώς έχει συμβεί.

Ευχαριστούμε πολύ.

**Comment by stonekgraff** [comment]
στα Logs πέρνω αυτα τα notice
2016-06-23 11:32:14 - PHP Notice:  Undefined property: stdClass::$OrderCode
in /home/babytunes/public_html/catalog/controller/payment/viva_payments.php
on line 148
2016-06-23 11:32:14 - PHP Notice:  Undefined property: stdClass::$ErrorCode
in /home/babytunes/public_html/catalog/controller/payment/viva_payments.php
on line 149
2016-06-23 11:32:14 - PHP Notice:  Undefined property: stdClass::$ErrorText
in /home/babytunes/public_html/catalog/controller/payment/viva_payments.php
on line 150
2016-06-23 11:32:14 - PHP Notice:  Undefined property: stdClass::$TimeStamp
in /home/babytunes/public_html/catalog/controller/payment/viva_payments.php
on line 151

τα request για την CreateOrder απο που τα λαμβάνω.. ???

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Απαλλαγμένο
από ιούς. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_-8863268625982575731_DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

------------------------------------
*Dimitris Botakis*

*Graphic - webdesigner**tel.* .: +302396112070
*mob*.:+306943987559
*e-mail*:thess.webdesigner@gmail.com
*web*: www.stonekgraph.com

Στις 23 Ιουνίου 2016 - 11:21 π.μ., ο χρήστης Kostas Athanasoglou <
notifications@github.com> έγραψε:

**Comment by stonekgraff** [comment]
εχω δοκιμάσει να κάνω μια νεα εκδοση του site εδω babytunes.gr/new και εχω
αλλάξει απο το viva τα url
URL Επιτυχημένης συναλλαγής: index.php?route=payment/viva_payments/callback
URL Αποτυχημένης συναλλαγής: index.php?route=payment/viva_payments/callback

σε
URL Επιτυχημένης συναλλαγής:
new/index.php?route=payment/viva_payments/callback
URL Αποτυχημένης συναλλαγής:
new/index.php?route=payment/viva_payments/callback

για να κάνω μερικά τεστ να δοκιμάσω τι μπορει να φταίει.
μπορείτε να το δειτε κ εσεις απο εδω. γιατι τωρα οταν πατάω ολοκλήρωση δεν
με πάει πουθενα λογικα λογο url


------------------------------------
*Dimitris Botakis*

*Graphic - webdesigner**tel.* .: +302396112070
*mob*.:+306943987559
*e-mail*:thess.webdesigner@gmail.com
*web*: www.stonekgraph.com

Στις 23 Ιουνίου 2016 - 11:34 π.μ., ο χρήστης Δημητρης Μποτάκης_Webdesigner <
thess.webdesigner@gmail.com> έγραψε:

**Comment by defilerc** [comment]
Καλημέρα @stonekgraff ,

Τα logs τα οποία ζητάμε να μας στείλετε έχουν τη μορφή που φαίνεται και στη σελίδα https://github.com/VivaPayments/API/wiki/CreateOrder στις ενότητες Sample Request, Sample Response.

Αν δε χρησιμοποιείτε απευθείας κλήσεις προς το Viva Payments API, αλλά κάποιο plugin, θα πρέπει ενδεχομένως να μιλήσετε με τους δημιουργούς του plugin, για να μπορέσουν να σας βοηθήσουν στον τρόπο που θα τα ανακτήσετε τα logs.

Ευχαριστούμε πολύ
