### ISSUE TITLE
Viva Wallet Payment API / Wrong source and wallet

### ISSUE THREAD

**Issue by simplesoftwaregr** [VivaPayments/API#1302]
I am using Viva Wallet Payment API
My flow is 
Create payment order(IsPreAuth=true) -> Cancel payment order OR  Create recurring transaction

My problem is that even if the create payment and cancel works just fine, when i capture the payment (recurring) the transaction in my viva wallet account appear in the Primary account and the source is Default (even if i configured it to "e-shop"). 

I also noted that the recurring api has no "source" parameter

**Comment by matthewrgourd** [comment]
Please provide any request / response logs so we can look into further...

**Comment by simplesoftwaregr** [comment]
There is no problem with the response. The problem is that when i capture the preauth transaction the money goes to the wrong wallet and the transactions is marked with the wrong source. I beleave that is because there is no source parameter in the cecurring API.


RES:
{"Emv":null,"Amount":0.15,"StatusId":"F","CurrencyCode":"978","TransactionId":"13857867-4ed9-4d31-adf4-9fa810c82cb8","ReferenceNumber":67387,"AuthorizationId":"597365","RetrievalReferenceNumber":"001313067387","ThreeDSecureStatusId":2,"ErrorCode":0,"ErrorText":null,"TimeStamp":"2020-01-13T15:30:46.9058834+02:00","CorrelationId":null,"EventId":0,"Success":true}

**Comment by simplesoftwaregr** [comment]
I think i fixed that, i send the source in the body and it worked (you have to fix your documentation)

**Comment by matthewrgourd** [comment]
Hi @simplesoftwaregr, glad you've been able to solve this and thanks for the suggestion. I will look at the documentation again.
