### ISSUE TITLE
Worpress - infinite loading

### ISSUE THREAD

**Issue by matt88120** [VivaPayments/API#1303]
I have some trouble with Worpdress plugin :
when click on "Place order" on the command page,  i have a infinite loading. I can wait 10 minutes, nothing happens. Any idea ?

No warning. No error in the console and the debug.log.
v3.5.7

![Capture d’écran 2020-01-11 à 16 21 43](https://user-images.githubusercontent.com/1491751/72206467-7fa8f100-348e-11ea-81fe-d694977df179.png)

**Comment by matthewrgourd** [comment]
Hi @matt88120, sorry to hear this. When you say 'Wordpress plugin', do you mean the Viva Wallet plugin for WooCommerce or something else?

**Comment by matt88120** [comment]
yes, i Mean Viva Wallet Plugin for Woocommerce, version 3.5.7. Every other plugins like Stripe works fine. Theme use : StoreFront.

**Comment by matthewrgourd** [comment]
Ok. Please provide the following screenshots and we'll look into the issue:

* Payment module settings from [WooCommerce / Payments tab](https://developer.vivawallet.com/images/WooCommercePaymentsTab.png?classes=border&width=900) (mask the API Key).
* Viva Wallet [payment source settings](https://developer.vivawallet.com/images/NewPaymentSource.png) (include the browser's URL in the screenshot).
* Viva Wallet [Websites/Apps page](https://developer.vivawallet.com/images/WebsitesSubmenu.png?classes=border&width=900) (include the browser's URL in the screenshot).
* [API Access page](https://developer.vivawallet.com/images/API%20Access.png?classes=border&width=900) (mask API Key (include the browser's URL in the screenshot).

Thanks!

**Comment by matt88120** [comment]
![01- woocommerce](https://user-images.githubusercontent.com/1491751/72250116-290cf580-35fb-11ea-811d-726a9c9d9b75.jpg)
![02 - payment source](https://user-images.githubusercontent.com/1491751/72250121-2ca07c80-35fb-11ea-831b-2d901a511333.jpg)
![03 - website](https://user-images.githubusercontent.com/1491751/72250130-30340380-35fb-11ea-962d-2441dc0e28d9.jpg)
![04 - API](https://user-images.githubusercontent.com/1491751/72250134-32965d80-35fb-11ea-98a6-d3da66ffe5cd.jpg)

**Comment by matthewrgourd** [comment]
Everything looks fine in the screenshots. I suggest a check to see if you've followed the steps in our setup guide verbatim: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by matt88120** [comment]
I follow every step, twice.

**Comment by matt88120** [comment]
Juste the step 3 doesn't seems to work : first, it takes a very long time to save webhook (like 2 min then, i have an error). 
![capture-ecran](https://user-images.githubusercontent.com/1491751/72253201-4f359400-3601-11ea-9da3-85dd3fc55444.jpg)

**Comment by matthewrgourd** [comment]
Can you try without the webhook?

**Comment by matt88120** [comment]
I don’t try With the webhook ! Still not working

**Comment by matthewrgourd** [comment]
Sounds like a WooCommerce problem rather than one relating to our plugin, but I may be wrong. Can you email me your Merchant ID to mgourd@vivawallet.com and I'll check your account?

**Comment by matthewrgourd** [comment]
Hi @matt88120 I can't see any issues with the account. One query, in the below screenshot, I assume you're enabling Viva Wallet using **Enable/Disable** checkbox?

https://user-images.githubusercontent.com/1491751/72250116-290cf580-35fb-11ea-811d-726a9c9d9b75.jpg

**Comment by matthewrgourd** [comment]
One other question, are you attempting to switch from Stripe to Viva Wallet?

**Comment by matthewrgourd** [comment]
Finally, how come when I initially visit widl.lu, it's not using HTTPs? Only when I click on a product does it switch over to encrypted. Looks like the certificate isn't set up correctly?

**Comment by matthewrgourd** [comment]
Hi @matt88120 are you still experiencing issue attempting to use our plugin for WooCommerce for payments?

**Comment by matt88120** [comment]
Yes. Also i tried a new fresh install with Worpress latest version, and **i have only two plugins** : WooCommerce & ViVaWallet. I have the same infinite loading. This cannot be plugins. 

Theme is default Twenty Twenty with 0 transformation. This cannot be theme.

I also tried with unofficial plugin developped by Enartia. I have a long time loading, but then i have a response : "Wrong API or credentials". In my thought, there is a problem with configuration on VIVAWALLET dashboard.

**Comment by matt88120** [comment]
Found !
The plugin is not compatible with PHP 7.3 !! 
Rollback to 7.1, and it works.

**Comment by matt88120** [comment]
Thanks

**Comment by matthewrgourd** [comment]
@matt88120 thanks for the heads-up about the php version :-)
