### ISSUE TITLE
Stop invoice email to customer upon purchase

### ISSUE THREAD

**Issue by charlotteux** [VivaPayments/API#1308]
Hi

I am using Woocommerce Wordpress plugin, when a purchase has been made an email comes out to customer from Woocommerce, we don't want another one coming from vivawallet - can we stop this email coming out?

Thanks

**Comment by matthewrgourd** [comment]
Hi there, first, can you let me know if you're using our official WooCommerce plugin downloadable from here:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by charlotteux** [comment]
If the email must come out ( for legal reasons ) thats fine as Paypal does the same but there are a few things on it that from my user research may create a lack of trust in the user -

The missing description (this is prob my end - can you advise where this pulls in from in my product set-up )

The app store link says app no longer available apart from in Greece

Hope that makes sense

Charlotte

**Comment by matthewrgourd** [comment]
Hi @charlotteux thanks for confirming. I believe we can switch the email off. Please send your business name and Merchant ID to myself at mgourd@vivawallet.com referencing this issue and I'll check your account. The description comes from the settings screen in WooCommerce. Please see step 9 onwards of [Integrate with your e-commerce store](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#step-2-integrate-with-your-e-commerce-store] within our [integration guide](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/).

**Comment by charlotteux** [comment]
Thanks have sent that.  Re the description it is the product description i believe is missing, I have set up the payment description settings correctly (Cards accepted….)

I raised the issues with checkout screen on a separate card but as the description is part of that, see attached.  I also wanted the order code thing removed and the button text to be BUY NOW and bigger if poss

(Realise this is a bit of work but from a UX perspective will be a good move for future business I think :-)

Thanks

**Comment by matthewrgourd** [comment]
Hi there, the product description is at the WooCommerce end. I can't help with that, I'm afraid, as it's a third-party platform. Same goes for your other UX query. I've switched off merchant payment notifications from Viva Wallet.

**Comment by charlotteux** [comment]
Ok thanks

Just to clarify,  can you tell me what the code is that pulls in the description? I have tried putting test text in all the meta fields in Woocommerce product settings and still nothing shows.

Also is the 'order code expires on….’ text coming from Woocommerce?

Thanks

**Comment by matthewrgourd** [comment]
Hi @charlotteux I believe all your queries are on the WooCommerce side so I'm closing this issue. You can get help via the following web page: https://docs.woocommerce.com/document/how-to-get-help/
