### ISSUE TITLE
Αλλαγή Server και Nameserver

### ISSUE THREAD

**Issue by nsitsanis** [VivaPayments/API#131]
Προσφατα αλλάξαμε servers και δεν λειτουγεί ο τροπος πληρωμη΄ς της vivapayment απο woocomerce δεν προχωράει στο περιβαλλον της viva. Μπορει να μας βοηθησει καποιος?

**Comment by ChristosMylonas** [comment]
Οι ρυθμίσεις στο νέο server θα πρέπει να είναι ίδιες με τον παλαιό. Αν ο τρόπος πληρωμής που χρησιμοποιείς στο woocommerce είναι Redirect Checkout τοτε θα πρεπει να  εμφανίζεται η Viva checkout page.
Περισσότερα μπορείς να βρεις εδω:

- https://github.com/VivaPayments/API/wiki/Redirect-Checkout
- https://github.com/VivaPayments/API/wiki/API-Authentication

Chris
