### ISSUE TITLE
Native Checkout v2 VivaPayments.cards.requestToken ERROR

### ISSUE THREAD

**Issue by nkapetanopoulos** [VivaPayments/API#1310]
Hello,

i am trying to implement the new Native Checkout v2 method in the DEMO environment but i am getting ERROR when executing the **VivaPayments.cards.requestToken** method

**_Request URL: https://demo.vivapayments.com/nativecheckout/v2/chargetokens:skipauth
Request Method: OPTIONS
Status Code: 400 Bad Request
Remote Address: 10.11.21.132:8080
Referrer Policy: no-referrer-when-downgrade**

The steps i am following are
1. I successfully get the access_token from "https://demo-accounts.vivapayments.com", using the client_id and client_secret appropriately

2. I set up the card
VivaPayments.cards.setup({
                authToken: access_token, // created in step 1
                baseURL: 'https://demo.vivapayments.com/'           
            });

3. I call the method and get the ERROR i stated at the top
    VivaPayments.cards.requestToken({
        amount: 1321
        ,installments: 1
        ,authenticateCardholder: false
    }).done(function (responseData) {
        console.log('Here is the charge token: ' + responseData.chargeToken);
    }).fail(function (responseData) {
        console.log('Here is the reason it failed: '  + responseData.Error.toString());
    });

Can you help me with this issue ?

Also, in your documentation you state that, after obtaining the charge_token "Creating a payment order and Completing the charge requires no modifications, so any existing implementations will continue to work as expected."
Is it correct ?

Thank you in advance

**Comment by nkapetanopoulos** [comment]
Hello again,

i implemented the chargeToken method on the server (see code below) and i get a "**Forbidden**" response status code

var client = new RestClient("https://demo-api.vivapayments.com");
RestRequest request = new RestRequest("/acquiring/v1/cards/chargetokens", Method.POST);
request.AddHeader("Authorization", "Bearer " + access_token);
request.AddJsonBody(pObj);
IRestResponse response = client.Execute(request);

---> response.StatusCode = "Forbidden"

**Comment by matthewrgourd** [comment]
Hi @nkapetanopoulos sorry for the delayed response. I don't have an immediate answer but will raise with our dev team and get back to you when I've a response. Thanks!

**Comment by matthewrgourd** [comment]
Hi @nkapetanopoulos, our development team has looked at your query and apparently you need to make this call from a backend channel not your browser. Hope this helps!

**Comment by matthewrgourd** [comment]
Hi @nkapetanopoulos, our development team has looked at your query and you should follow this guide https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

In your first post in step 2: the baseUrl must be "https://demo-api.vivapayments.com" and in step 3 you have to remove `authenticateCardholder: false`
