### ISSUE TITLE
Viva Wallet client - Error Message checkout page - SHOPIFY

### ISSUE THREAD

**Issue by YannMeyrades** [VivaPayments/API#1312]
Hi there,

I have just installed successfully VIVAWALLET on my SHOPIFY online store following this page: https://developer.vivawallet.com/e-commerce-plugins/shopify/.

However, there is an issue in the checkout page which leads to an ERROR message when I try to buy a product. Please see the error below:

https://www.loom.com/share/4533251f03864ffe824523ab6a661634

You can also look at the way I have configured VivaWallet on my shopify account:

https://www.loom.com/share/4c94f9a450f244e8821a22a2375d5671

Please HELP and GIVE me a solution to make the payment page work.

My credentials:
Name: Pierre LeGrand
VAT: FR77825164213
Company: GroupC

Thanks,
++

**Comment by YannMeyrades** [comment]
Hi there,

Could you please reply to me ?

THanks

**Comment by matthewrgourd** [comment]
Hi @YannMeyrades, sorry to hear you've been experiencing difficulties setting up Shopify. If you untick the 'test mode' option your store should be found at the point of redirect. Please let me know how you get on. Thanks!

**Comment by YannMeyrades** [comment]
Hi Matthew,

Thank you, it seems to be working now. I can see the page.

Now, I would like to make a test order. Please can you tell me how to make
a test order using a fake credit card ?

thanks

Le jeu. 16 janv. 2020 à 11:21, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @YannMeyrades, about your last query, I'm checking for you!

**Comment by matthewrgourd** [comment]
Hi @YannMeyrades, the advice from our Shopify plugin developer is that you should proceed with a normal order, with a real credit card, then cancel the transaction. We don't have a test payment option in the live environment.
