### ISSUE TITLE
Please enable API transactions endpoints for the following #1250

### ISSUE THREAD

**Issue by davecarlson** [VivaPayments/API#1313]
Please enable the APIs for the following: 
Merchant ID | c949a92d-42ed-4bb5-a4d3-68b1ec007088

```
{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"The specified api action is disabled for the merchant c949a92d-42ed-4bb5-a4d3-68b1ec007088, please consult the documentation","TimeStamp":"2020-01-15T21:25:03.7102539+02:00","CorrelationId":null,"EventId":0,"Success":false}
```

We are passing a payment token to the $request = 'https://www.vivapayments.com/api/transactions/'

**Comment by matthewrgourd** [comment]
Hi @davecarlson, sorry to hear this. Everything's switched on at the account end. Could you be more specific about what it is you're attempting to do, i.e send through the full request details if possible? (sensitive information blurred out) Thanks!

**Comment by matthewrgourd** [comment]
Closing as no reply
