### ISSUE TITLE
Opencart - Keep getting Transaction failed

### ISSUE THREAD

**Issue by ossovik** [VivaPayments/API#1314]
I have lost many sales this month because the checkout does not work. Can anyone help me fix this?
Been using Native/Pay with Viva Wallet Checkout

**Comment by matthewrgourd** [comment]
Hi @ossovik sorry to hear this. Is it Viva Wallet for OpenCart you're attempting to use? Which version of OpenCart do you have installed?

**Comment by ossovik** [comment]
Yea that is correct. I am using Version 3.0.3.2

**Comment by matthewrgourd** [comment]
Closing as no reply.
