### ISSUE TITLE
Cancelled Transactions - orders dont go thru.

### ISSUE THREAD

**Issue by admindarkside** [VivaPayments/API#1315]
We are contacting from EMA LEGENDARY COLLECTIRBLES GROUP LTD.  We have customers thats try to purchase our products and when they go to checkout payment via viva the transaction is cancelled and we receive the message "The payment for order xxxx has failed or has been canceled.7974245219462099 Payment failed or cancelled". The customers have contacted us saying that they have talked with their bank and they credit card is working fine, Can you please check what may be the problem. 
Another customer has placed an order that went thru fine and after 20 minutes he tried to place another order and his order was automatically cancelled by the viva system stating the exact above message. Customer contacted us about the issue and states that his card is fine and the card limit is much higher than the purchased value. Can you please check why the payments are not getting thru. 
Thank you

**Comment by matthewrgourd** [comment]
Hi @admindarkside sorry to hear this, I've looked at your account and indeed some cards are being rejected but not by Viva Wallet. Those customers should contact their card issuers for further information.

**Comment by admindarkside** [comment]
Hi Matt we spoke with the customers and both told us that their cards are fine and there is only specific orders that dont go thru. For example if you check flores he has 2 or 3 succesful orders and 2 cancelled so thats definately not his card that has issue as its has already been used succesfully.  Plus those who have contacted stated that their card works fine and they have plenty of limit for further purschases.

**Comment by matthewrgourd** [comment]
If you could raise these particular transactions with [customer service](https://www.vivawallet.com/en-eu/contact-us/), they may be able to help. It's definitely not due to a technical issue at the Viva Wallet end.
