### ISSUE TITLE
Customize VivaWallet Checkout Page with my LOGO

### ISSUE THREAD

**Issue by YannMeyrades** [VivaPayments/API#1316]
Hi Matthew,

I would like to know if it's possible to customize the Viva Wallet checkout page so my Logo can show up on the page. I'm talkin about this page at the end of this video:

https://www.loom.com/share/fba5b3685624405c8400f892f054c11b

If it is, please guide me through the steps of adding a logo.

Thanks
Yann

**Comment by matthewrgourd** [comment]
Hi @YannMeyrades, I'm afraid this is not possible at the moment. Best regards...
