### ISSUE TITLE
nativecheckout/v2/transactions - 403 Forbidden

### ISSUE THREAD

**Issue by 5361796f6e617261** [VivaPayments/API#1319]
- I used this guide https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

- Steps 1 - 4 works fine. 

- But on step 5 I'm getting 403 from https://api.vivapayments.com/nativecheckout/v2/transactions

I think what I'm sending correct `Bearer token` because I'm getting `chargeToken`  on step 4 (
I can make a purchase with a V1 api (`/api/order` -> `/api/transactions`) and that `chargeToken`)

I used this code
```
$client = new \GuzzleHttp\Client([
    'baseUrl' => 'https://api.vivapayments.com'
  ]);

  $headers = [
    'Authorization' => ['Bearer <my_access_token_here form https://accounts.vivapayments.com/connect/token>'],
    'Accept' => 'application/json',
    'Content-Type' => 'application/json',
  ];


  $response = $client->post('https://api.vivapayments.com/nativecheckout/v2/transactions', [
    'headers' => $headers,
    'json' => [...],
  ]);
```

**Comment by matthewrgourd** [comment]
@5361796f6e617261, I've just tested in Postman and I can't recreate the issue. You need to use the  bearer token generated here: http://developer.vivawallet.com/authentication/#production-environment-1 for authentication when making the call to https://api.vivapayments.com/nativecheckout/v2/transactions

**Comment by 5361796f6e617261** [comment]
Well, to get access token:
```
    $client = new \GuzzleHttp\Client();
    $credentials = base64_encode($this->getClientId() . ':' . $this->getClientSecret());
    // $this->getAccountsTokenUrl() => https://accounts.vivapayments.com/connect/token
    $responce = $client->post($this->getAccountsTokenUrl(), [
      'headers' => [
        'Authorization' => ['Basic ' . $credentials],
        'Content-Type'  => 'application/x-www-form-urlencoded',
        'Accept'        => 'application/json',
      ],
      'body' => 'grant_type=client_credentials',
    ]);
    
    $contents = $responce->json();
    
    return [$contents['token_type'] ?? '', $contents['access_token'] ?? ''];
```
`$contents['access_token']` send to `VivaPayments.cards.setup({'authToken':<access_token>})` 

After that I get `chargeToken` from js and make request to `/nativecheckout/v2/transactions` like i sent before (but for a new request, I request a new Bearer token) and I am getting 403 Forbidden. 

And for example request to `/nativecheckout/v2/chargetokens` is woking fine

**Comment by psot** [comment]
Just for future reference in case someone else gets the same error. The "403 forbidden" is a business logic error despite being described as a client access error in documentation, so it should better raise a 400 error to avoid confusion.

If you get the 403 error just parse the response body and it will describe the reason, usually it's forbidden because of a difference in the amount being charged or of an invalid currency code.
