### ISSUE TITLE
Custom Payment Source (other than the Default): Unable to process transaction

### ISSUE THREAD

**Issue by christianago** [VivaPayments/API#132]
Hello dmihos,

So setting Default Payment source on native checkout is working great! I am able to create all types of transactions.
However, I recently received an email from merchants@vivawallet.com stating that Default source won't be activated for the next merchant accounts that will be created in the future (I expect at least 20 new merchants to join Viva API). The only payment source that will get activated is the custom ones.

The issue is that when setting a custom payment source (native checkout and active) I am not able/authorized to create transactions (error code: 403). All other Viva settings are double-checked and working good with the Default payment source.

How to deal with this issue?

Thank you for your time, dmihos

Here is the email body from support:

> Καλημέρα σας,
> 
> Θα θέλαμε να σας ενημερώσουμε πως η αναφορά που σας γίνεται στην αλλαγή της Default πηγής δεν είναι περιοριστική. Ο developer μας σας καθοδηγεί στην ορθή διαδικασία διασύνδεσης, χωρίς αυτό να σημαίνει ότι το app θα λειτουργεί μόνο εάν γίνει η διασύνδεση πάνω στην Default πηγή. Ως συμπέρασμα, θα πρέπει να δηλώσετε μια νέα πηγή με το όνομα Summerize App και να αλλάξετε τις ήδη default από native σε redirection, ώστε και να προχωρήσουμε στην έγκρισή τους.
> 
> Με εκτίμηση,

**Comment by dmihos** [comment]
Hi @christianago 

Merchants perform card transactions through Greek acquiring institutes.
As part of the audit procedure, we are obliged to check every merchant's major business field and make sure it complies with legal directives (legal business for allowed activities).

One of those checks is a brief domain check on sources. 

Even though a source may be used for a mobile app, where a domain url does not apply, you are required to fill this info and wait for the approval procedure. 
In case a domain is not available, the Support center will most probably handle it as exception and ask for alternative audit material.

I understand this may cause some small delays, but I don't believe it's unreasonable for us to ask you for this info.

Thanks for contacting us.

**Comment by christianago** [comment]
Thank you for the instant response.

The merchants accounts I am referring contain all the required documents which are already approved by Viva.
All of our merchant accounts include a single domain URL, meaning that the merchants are able to receive payments from a single app, that we have developed.
A custom source is already filled and created within our merchant accounts and they are already active and approved.
So what is the delay period you refer to? 
Custom source is set to Native Checkout and approved.
Default source is set to Redirect and approved.
All approvals are being done as well as the delay periods.
Given the situation, what are the next steps in order to proceed to create transactions by using the native custom source?

**Comment by dmihos** [comment]
Then all you need to do is use the sourcecodes you create.
For example, in line 
https://github.com/VivaPayments/API/blob/master/MobileAPI/iOS/PaymentDemo/ViewController.m#L106
you need to replace 'Default' with the appropriate codes

**Comment by christianago** [comment]
I tried the solution you suggested and I got the following response (403):
{
  "OrderCode": null,
  "ErrorCode": 403,
  "ErrorText": "The merchant with id XXXX-XXXX-XXXX does not have a source with code 'Summerize App' assigned or the source is disabled",
  "TimeStamp": "2016-06-23T09:23:34.9998724+03:00"
}

**Comment by dmihos** [comment]
You should use the Code (Κωδικός) of the source and not the name.

**Comment by dmihos** [comment]
You need to use SourceCode for this call.
However, please note, that when creating a source you can define the SourceCode (you can change the random auto assigned numeric value).

**Comment by christianago** [comment]
I tried the suggested solution and now I got error: **502**

{
  "Emv": null,
  "Amount": 5,
  "StatusId": "E",
  "TransactionId": "d3982f8f-a857-4679-a256-bae73271c90f",
  "ReferenceNumber": 343838,
  "RemainingRefunds": null,
  "AuthorizationId": "",
  "ErrorCode": 502,
  "ErrorText": "Transaction failed",
  "TimeStamp": "2016-06-23T13:24:22.6685758+03:00"
}

**Comment by christianago** [comment]
I made a new request on a verified account and the order succeeded.
Conclusion is that a merchant should upload all required documents and then wait ~2 weeks for verification.
So thank you again for your help.

**Comment by dmihos** [comment]
The 502 error you got means that the card charge, for the specific card, has been denied.
Account verification has nothing to do with transaction approval.

**Comment by Tejas-narola** [comment]
@dmihos Would you please tell me where can I find ErrorCode Documentation on github or on viva ?

**Comment by defilerc** [comment]
Hi @Tejas-narola ,

Viva Payments API sends along with the HTTP error code a descriptive error text, which provides additional information regarding the cause of the error.

Error texts cannot contain sensitive information for security reasons. In case you receive an HTTP error and the error text response is too generic for you, you can always open an issue on the github page, so you can receive support regarding your issue.

Best regards
