### ISSUE TITLE
ecommerce vivawallet setup issue

### ISSUE THREAD

**Issue by cannamad** [VivaPayments/API#1322]
Hi all,

There appears to be an issue with either my merchant credentials or the plugin
for my ecommerce website. I have filled my vivawallet merchant credentials as per my profile but after testing it when clicked on PLACE ORDER i get an error message "Thank you - your order is now pending payment. You should be automatically redirected to Vivapayments to make payment.

Wrong Merchant crendentials or API unavailable"

Any ideas why would I get such error?

**Comment by matthewrgourd** [comment]
Hi @cannamad sorry to hear this. Can you let me know which of our plugins you're using? Thanks!

**Comment by cannamad** [comment]
Hi Matthew
I realised it was a plugin by somebody else and not vivawallet, I deleted it and intsalled the one vivawallet website and now I get a different message. 

**Thank you for your order, please click the button below to pay.

There has been a critical error on your website.

Learn more about debugging in WordPress.**

Also the "button below" does not appear

**Comment by cannamad** [comment]
Matthew I think I solved it

After debugging I realised that it was the currency setting in Woocommerce

Thank you

**Comment by matthewrgourd** [comment]
Hi @cannamad, ok, thanks for letting me know!
