### ISSUE TITLE
Issue with Issuing Money to My Bank Account

### ISSUE THREAD

**Issue by YannMeyrades** [VivaPayments/API#1323]
Hi There,

I have added my bank account and IBAN on my Viva Wallet account (GroupC) weeks ago.

Problem is that in the "Deposit Money>Bank Transfer" tab, the IBAN that shows up is wrong and definitely not mine. And there is no way to scroll-down and search for the right IBAN.

Please see this video: https://www.loom.com/share/a96a82afdffc48ccadac4215bd3bb1ff

Please reply to my VivaWallet email , Group C.

Thanks

**Comment by matthewrgourd** [comment]
Hi @YannMeyrades sorry to hear you've experiencing difficulties. Can you click on the drop-down on the Bank Transfer page and see if there are any other accounts (including the correct one) to choose from?

**Comment by YannMeyrades** [comment]
Hi Matthew,

Unfortunately not. The drop-down button doesn't show anything. Nothing you
can choose from.

Yann

Le mar. 21 janv. 2020 à 10:43, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @YannMeyrades we're not quite sure why the new beneficiary is inactive. I would ring [customer service](https://www.vivawallet.com/en-eu/contact-us/) and ask them what is the problem with that account. Thanks!

**Comment by YannMeyrades** [comment]
Hi Matthew, why did you close the ticket ? The problem hasn't been fixed.
I still can't use my IBAN number

please advise
Yann

**Comment by matthewrgourd** [comment]
Hi @YannMeyrades sorry about that but you really need to contact customer service as I advised. There's nothing I can do from here. It looks like the beneficiary you set up hasn't been verified but I don't know the reason. Maybe try to delete and set up again? But speak with customer service for your country first:

<table><tr><th>Country</th><th>Phone number</th>
  <tr><td>Belgium</td><td>(+32) 2342 0790</td></tr>
    <tr><td>Cyprus</td><td>(+357) 2403 0211</td></tr>
    <tr><td>France</td><td>(+33) 1876 50765</td></tr>
    <tr><td>Greece</td><td>(+30) 21 1760 4000</td></tr>
    <tr><td>Netherland</td><td>(+31) 2089 05503</td></tr>
    <tr><td>Romania</td><td>(+40) 3122 96150</td></tr>
    <tr><td>UK</td><td>(+44) 20 3734 7770</td></tr>
    <tr><td>Portugal</td><td>(+351) 3 0050 9059</td></tr>
</table>
