### ISSUE TITLE
payment API problem (401 error)

### ISSUE THREAD

**Issue by irakfouk** [VivaPayments/API#1324]
Hi,
i want to implement payment API and i follow the steps.
1. make a demo acount (ok)
2. make a request token (ok)
3. make genaration acces token (ok)

and now in step 4, when i call an API with access token authorization header with bearer it returns me a 401 error.(why?)

Please help me!
with regards

**Comment by matthewrgourd** [comment]
Please send me the full request / response logs if you can. Thanks!

**Comment by irakfouk** [comment]
this is my code:
I get a token from authentication (this part works) and then i call this functio public static string token;


```
            public static string token;
            public static VivaCreatPayment VivaCreatPayment;
            public static void Main(string[] Tags, string Email, string Phone, string Fullname, int PaymentTimeOut, string RequestLang, int MaxInstallments, bool AllowRecurring, bool IsPreAuth, int Amount, string MerchantTrns, string CustomerTrns )
            {
                token = Auth.VivaAuth();

                string strUrl = String.Format("https://demo.vivapayments.com/api/orders");
                WebRequest request = WebRequest.Create(strUrl);
                request.Method = "POST";
                request.Headers.Add("Authorization: Bearer " + token);
                request.ContentType = "application/json";
                request.ContentType = "application/x-www-form-urlencoded";
                string postData = @"{
                                    'Tags': [
                                        |tags|
                                    ],
                                    'Email':  '" + Email + @"',
                                    'Phone': '" + Phone+ @"',
                                    'FullName': '" +Fullname+ @"',
                                    'PaymentTimeOut': " +PaymentTimeOut.ToString()+ @",
                                    'RequestLang': '" + RequestLang + @"',
                                    'MaxInstallments': " + MaxInstallments.ToString() + @",
                                    'AllowRecurring': " + AllowRecurring.ToString() + @",
                                    'IsPreAuth': " + IsPreAuth.ToString() + @",
                                    'Amount': " + Amount.ToString() + @",
                                    'MerchantTrns': '" + MerchantTrns + @"',
                                    'CustomerTrns': '" + CustomerTrns + @"'
                                    }";
                string tags = "";
                string comma = "";
                for (int i = 0; i < Tags.Length; i++) {
                    tags = tags + comma + "'"+Tags[i]+"'";
                    comma = ",";
                }
                postData = postData.Replace("|tags|", tags);
                   
                
                using (var streamWriter = new StreamWriter(request.GetRequestStream()))
                {
                    streamWriter.Write(postData);
                    streamWriter.Flush();
                    streamWriter.Close();
                }
                HttpWebResponse response = (HttpWebResponse)request.GetResponse();
                Console.WriteLine(response.StatusDescription);
                Stream dataStream = response.GetResponseStream();
                StreamReader reader = new StreamReader(dataStream);
                string responseFromServer = reader.ReadToEnd();
                VivaCreatPayment = JsonConvert.DeserializeObject<VivaCreatPayment>(responseFromServer);
                Console.WriteLine(responseFromServer);
                reader.Close();
                dataStream.Close();
                response.Close();

                
            }

```

**Comment by matthewrgourd** [comment]
Hi @irakfouk, sorry to hear this. Our Payment API usesBasic Auth for authentication rather than Identity Server. Please see https://developer.vivawallet.com/authentication/#basic-authentication for further details.

**Comment by irakfouk** [comment]
the line " token = Auth.VivaAuth(); " retrieves a token using  basicAuth just as you described in the authentication.
Using this token i get 401 error.

**Comment by matthewrgourd** [comment]
Hi @irakfouk please see this updated explanation of basic authentication as implemented by Viva Wallet:

With basic authentication, you pass your credentials ([Merchant ID and API Key](/e-commerce-plugins/find-your-merchant-id-and-api-key/)) in each request to our APIs.

You can pass your credentials as a Base64-encoded header or as parameters in an HTTP client.

When you pass your credentials in the header, you must Base64-encode them. The following is an example of an encoded HTTP basic authentication header:

`Authorization: Basic ZmJmMWUwOTAtNjVkZS00Yzc1LWI1ODAtZDlkOWJjNDk0YWQyOldEdi1WKw==`

With a client such as cURL, you pass your encoded credentials in the header with the -H option, as the following example shows:

```json
curl -X POST \
  https://demo.vivapayments.com/api/orders \
  -H 'Authorization: Basic ZmJmMWUwOTAtNjVkZS00Yzc1LWI1ODAtZDlkOWJjNDk0YWQyOldEdi1WKw==' \
  -H 'Content-Type: application/json' \
  -d '{
  "Tags": [
    "sample string 1",
    "sample string 2",
    "sample string 3"
  ],
  "Email": "customer@domain.com",
  "Phone": "2117604000",
  "FullName": "Customer name",
  "PaymentTimeOut": 86400,
  "RequestLang": "en-US",
  "MaxInstallments": 12,
  "AllowRecurring": true,
  "IsPreAuth": true,
  "Amount": 1000,
  "MerchantTrns": "Your reference",
  "CustomerTrns": "Description that the customer sees"
}'
```
Running the above from the command line should result in a response containing an order code generated by the [Create payment order](/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post) call from our Payment API.

**Comment by irakfouk** [comment]
hi again.. 
i tried everything above again and again but i have the same problem! it send me  401 error!

**Comment by irakfouk** [comment]
@matthewrgourd 

update status: now i am getting 400 error.

**Comment by matthewrgourd** [comment]
@irakfouk Does the cURL example I gave you work? It should return an order code.

**Comment by irakfouk** [comment]
@matthewrgourd i will do again the process with the updated explanation of basic authentication , and i will inform you the next days!
with regards

**Comment by irakfouk** [comment]
@matthewrgourd  hi again!

I make the process as you said, but in the answer i get is an error 411('The remote server returned an error: (411) Length Required.').
I checked it and i saw that gives a result with the Amount returns zero or negative.
my JSON is this
`{
                                    'Tags': [
                                        
                                    ],
                                    'Email':  'customer@domain.com',
                                    'Phone': '2117604000',
                                    'FullName': 'Customer Name',
                                    'PaymentTimeOut': 86400,
                                    'RequestLang': 'en-US',
                                    'MaxInstallments': 12,
                                    'AllowRecurring': true,
                                    'IsPreAuth': true,
                                    'Amount': 1000,`


and returns me this

`{"OrderCode":null,"ErrorCode":400,"ErrorText":"Negative or zero amount, merchant b0770dac-c8ea-4c71-a90d-09081dd07911)","TimeStamp":"2020-01-29T15:59:27.3384989+02:00","CorrelationId":null,"EventId":0,"Success":false}`

**Comment by matthewrgourd** [comment]
@irakfouk, you've got an errant apostrophe in the amount field? Try `'Amount': 1000`

**Comment by irakfouk** [comment]
it worked! @matthewrgourd 

Used basic authentication,  pass my credentials (Merchant ID and API Key) in each request for the APIs.
