### ISSUE TITLE
Are we already Native Checkout v2 compliant?

### ISSUE THREAD

**Issue by LoggiaNG** [VivaPayments/API#1325]
Hello, 
on our delivery applications, we have a common checkout method for web and mobile using a token, so our method does not include javascript calls, everything is managed on the backend.

We have the procedure where we first create a charge token, and only when the store accepts the order, we continue with a call to "/api/transactions".

Our source is already selected as "Redirection/Native Checkout v2", and everything is working as expected.

How can we tell if we are already compliant with v2?
If we are not, what changes should we make (since we are not using the method that the migration guide expects) ?

Thank you!

**Comment by matthewrgourd** [comment]
Hi @LoggiaNG all our payment solutions are compliant with the latest PSD2 update (SCA) except [Native Checkout v1](http://developer.vivawallet.com/online-checkouts/migrating-from-native-checkout-v1/). I hope this helps.

**Comment by LoggiaNG** [comment]
I believe we have left Native Checkout v1 behind long ago, so we should be ok.
Thanks! :)
