### ISSUE TITLE
Connect two separate Shopify stores with same MerchantID on different WalletIDs

### ISSUE THREAD

**Issue by pvoulg** [VivaPayments/API#1326]
Hi there, 

We've got a client who has two separate Shopify stores. Up until now they were using the same MerchantID and StoreToken for both stores, but have decided to create an additional Wallet Id, in order to track revenue separately.

They have a new Wallet Id and have requested an additional StoreToken, which they have already received. The question is—without providing the Wallet Id anywhere on Shopify's side—on which wallet would the sales revenue land, in Viva's dashboard. Is it possible to have two completely separate entities and Shopify Stores under one account, or should they create another one (and is that even possible, since they're both under the same company)?

Thanks!

**Comment by matthewrgourd** [comment]
Hi there, I believe the wallet connected to Shopify when you set it up through Viva Wallet by default is the one known as "Primary". Unfortunately as a merchant you can't change the [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings designated by us for Shopify but our [customer service](https://www.vivawallet.com/en-gb/contact-us) department may be able to help. Alternatively, just make sure that no other payments other than those from Shopify are received by the primary wallet. Hope this helps!
