### ISSUE TITLE
Query about 3DS for recurring transactions, that came from non 3DS customer initiated transactions

### ISSUE THREAD

**Issue by jspanom** [VivaPayments/API#1327]
Hello, we are an existing client (manual.co), and a subscription business.

We have customer initiated transactions (new subscriptions) since October 2019 that did not pass through 3DS. We are going to implement the V2 of the API and enable 3DS going forward, but we would like to understand what will happen to that segment of customer initiated new subscriptions after 14th September 2019, without 3DS verification.

Our concern is that if those automatically recurring transactions require passing through 3DS, it will be a huge business setback, as churn is likely to be very high.

We asked the same query to another large PSP platform, and they said that:

"In that case, for those transactions, you would still fall under the exemption for those existing subscribers, so no need to re-authorise them as 3DS".

Can you please confirm that the same applies to your platform?

**Comment by matthewrgourd** [comment]
Hi @jspanom apparently right now there is no 3DS requirement for e-commerce. It's currently up to the issuer (or in some cases the card scheme) to require 3DS for e-commerce transactions. When the 3DS mandate comes into force around March 2021, the rule that Mastercard and Visa are looking to implement is that in such cases that the parent transaction occurred before 14 Sep 2019 then all following transactions are excluded from SCA. I assume a similar thing would apply if you switched over soon after October 2019.

**Comment by matthewrgourd** [comment]
Hi @jspanom, so, yes, in short, the same applies on our platform!

**Comment by jspanom** [comment]
Thanks Matt, just to clarify, when we implement V2 of your API next week, can we still technically do that without enabling 3DS for new subscriptions?

**Comment by matthewrgourd** [comment]
@jspanom I believe you can, yes.
