### ISSUE TITLE
WooCommerce Pending Payment

### ISSUE THREAD

**Issue by Kanalife** [VivaPayments/API#1328]
Can we have it set the order status to "Processing" after payment has been taken instead of "Payment Pending"? 

The order automatically goes to cancelled if I don;t manually set the order status to processing.

It's also confusing for customers that have paid to see payment pending in their dashboard area.

Many thanks

**Comment by matthewrgourd** [comment]
Hi there, I believe the status is set by WooCommerce, rather than at the Viva Wallet end: https://support.primaryimage.uk/help-topics/order-status-woocommerce/

**Comment by Kanalife** [comment]
Pending payment is what it says on the tin. No payment made. Or abandoned cart. WooCommerce gives you 24hrs to pay or it cancels the order and adds the stock back.

If the payment is taken using viva wallet the order should set to processing if the payment is successful or failed if they didn't have funds etc. If it's pending payment then there is a pay button in the dashboard for the user to make payment.

All other payment gateways I've used work this way and it even says in the link you sent about the processing when payment is made.

On 23 Jan 2020 13:36, matthewrgourd <notifications@github.com> wrote:

Hi there, I believe the status is set by WooCommerce, rather than at the Viva Wallet end: https://support.primaryimage.uk/help-topics/order-status-woocommerce/

**Comment by Kanalife** [comment]
There is a setting in Viva to do the order status and I have it set to processing but it keeps going to pending payment by default after taking payment
[cid:7a576377-b819-47e0-9275-5272b8248714]
________________________________

**Comment by Kanalife** [comment]
I had it set to native pay. Maybe that was the issue? I've set it to the redirect to test now.

[cid:2e62ac7d-b944-4263-bf03-0b7259854eac]
________________________________

**Comment by matthewrgourd** [comment]
Hi @Kanalife, let me know how you get on and when it's ok to close this issue.

**Comment by Kanalife** [comment]
Still having the same problem where it take the payment but still says payment pending.

On 27 Jan 2020 11:23, matthewrgourd <notifications@github.com> wrote:

Hi @Kanalife<https://github.com/Kanalife>, let me know how you get on and when it's ok to close this issue.

**Comment by matthewrgourd** [comment]
Hi @Kanalife has the payments you mention gone through successfully when you check under your sales transactions in the Viva Wallet banking app?

**Comment by Kanalife** [comment]
Hi @matthewrgourd 

Still showing payment pending once the payment is made. The payments are going through and show up in the app as well. Just doesn't set to processing unfortunately

**Comment by matthewrgourd** [comment]
Hi @Kanalife understood. Can I check two things:

1. What version of WooCommerce are you using?
2. Did you download the Viva Wallet plugin from our official page here: 
https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
Just checking as there are a few unofficial extensions out there!

**Comment by Kanalife** [comment]
I'm using WooCommerce version 3.8.1 and the official viva wallet plugin version 3.5.7

On 5 Feb 2020 12:58, matthewrgourd <notifications@github.com> wrote:

Hi @Kanalife<https://github.com/Kanalife> understood. Can I check two things:

  1.  What version of WooCommerce are you using?
  2.  Did you download the Viva Wallet plugin from our official page here:
https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
Just checking as there are a few unofficial extensions out there!

**Comment by matthewrgourd** [comment]
Can you reply with a screenshot showing your Viva Wallet payment settings within WooCommerce with any confidential info. blurred out? This page:

![WooCommercePaymentsTab](https://user-images.githubusercontent.com/44943019/73920483-617fb680-48bd-11ea-897b-22ee50254fec.png)

**Comment by matthewrgourd** [comment]
Hi @Kanalife I'm closing this issue as I think the behaviour you describe may be correct and is more to do with the design of our plugin than any particular error.
