### ISSUE TITLE
Production Keys for Native Checkout v2

### ISSUE THREAD

**Issue by dpantazis94** [VivaPayments/API#1329]
Hello Everyone,

We have been using the Native checkout v1 for a client. We got notified that we need to migrate to v2, in order for the client to continue to accept payments after the 31/01/2020 . We have completed the development needed for the migration on a staging enviroment using demo keys.

What i would like to know are the following : 

If i create a new event via the `Add Website/App` button from a similar URL like the one below
https://members.vivawallet.com/selfcare/en/sources/paymentsources?sourceTypeId=XXXXXXX,
whats the process of Viva's approval and how long would it take ?

If i edit my already existing and working production key ( which implements v1 Checkouts ), to  Redirection/Native Checkout v2 as  the Integration method, would i still follow a similar approval process ? Again are you able to estimate how long would that take ?

Thank you in Advance!

**Comment by matthewrgourd** [comment]
Hi there, the process of approving a new payment source and making it active shouldn't take longer than 24 hours. Please see [What happens during payment source activation?](https://help.vivawallet.com/hc/en-us/articles/360002562577-What-happens-during-payment-source-activation-) for further details. Hope this helps. Thanks!

**Comment by dpantazis94** [comment]
Hey @matthewrgourd ,

Thanks for the quick response. I read the article and understood its contents. Just one more question please.

I created a new Payment source with the `Add Website/App` button i mentioned earlier and its status was `Active` immediately. Does that meens i can already use it on a production environment ?

Thanks again !

**Comment by matthewrgourd** [comment]
Hi @dpantazis94, as far as I'm aware it is only in the demo environment where a new source becomes active immediately. Is this what you're referring to or is it actually production you're talking about?

**Comment by dpantazis94** [comment]
Hello @matthewrgourd ,

Yes in the production the new key became immediately actrive. It still is active actually and we were planning the migration from the staging enviroment to the production one today using this new active key.

Thanks!

**Comment by matthewrgourd** [comment]
@dpantazis94 it's unusual for a payment source to be made active so quickly but I don't think it indicates an issue.

**Comment by dpantazis94** [comment]
Οκ @matthewrgourd , thanks a lot for the quick response!
