### ISSUE TITLE
Προσθήκη πηγής πληρωμής για Mobile App

### ISSUE THREAD

**Issue by deliverymanager** [VivaPayments/API#133]
Μέσα από το Πάνελ της Viva, δεν υπάρχει η δυνατότητα αυτή τη στιγμή να προσθέσει κάποιος μία νέα πηγή πληρωμής η οποία να αφορά mobile εφαρμογή, καθώς πάντα ζητά domain.
Προφανώς οι εφαρμογές δεν έχουν domain, άρα πώς μπορώ να προσθέσω μία πηγή πληρωμής μόνο για εφαρμογή Android και iOS, κάνοντας χρήση του Mobile API (Native Πληρωμή);

**Comment by defilerc** [comment]
Καλημέρα @deliverymanager ,

Στο domain, θα πρέπει να βάλετε το domain της επιχείρησής σας, ώστε να γίνεται ο απαραίτητος έλεγχος από το Audit Team της εταιρείας. 

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by deliverymanager** [comment]
Απλώς όπως πιστεύω αντιλαμβάνεστε δεν μπορεί να καλυφθεί η περίπτωση μία επιχείρησης που είναι απολειστικά με mobile app, χωρίς ιστοσελίδα.

**Comment by defilerc** [comment]
Στις εξαιρετικά σπάνιες περιπτώσεις, όπου κάποιος έμπορος επιθυμεί να κάνει ηλεκτρονικές πληρωμές, χωρίς να διαθέτει κανένα σημείο ηλεκτρονικής παρουσίας, ενδέχεται να ζητηθεί από το Audit Team της εταιρείας, επιπλέον δικαιολογητικά για την ταυτοποίηση των δραστηριοτήτων του εμπόρου.

Ευχαριστούμε πολύ.
