### ISSUE TITLE
Sajid

### ISSUE THREAD

**Issue by Sajidh1** [VivaPayments/API#1331]
I just set up shopify store while processing payment it gives error.... that only currencies r accepable r EU, GBP and RON... /but I need to sell in USA in USD.....

**Comment by Sajidh1** [comment]
Please someone help....

**Comment by Sajidh1** [comment]
Error
Invalid currency used. You can currently only use EUR, GBP & RON

I get above text when try to buy on my shopify store.........     Please help.. ASAP

**Comment by matthewrgourd** [comment]
Hi there, I'm afraid what you see is correct, when using Viva Wallet as the payment gateway, you can only select EUR, GBP and RON for your Shopify store at this present time.

**Comment by Sajidh1** [comment]
Thanks Matt
