### ISSUE TITLE
Native Checkout V2 - PaymentsCardHolderAuthenticationInvalidStatus

### ISSUE THREAD

**Issue by nkapetanopoulos** [VivaPayments/API#1332]
Hello,

until yesterday the native checkout v2 was working flawlessly, in both demo and production environment.
This morning, in the **demo** environment, i get
 { 
   "status": 400, 
   "message": "PaymentsCardHolderAuthenticationInvalidStatus", 
   "eventId": "2061" 
 } 
error when i try to generate card token.

This is the request
https://demo-api.vivapayments.com/acquiring/v1/cards/tokens?chargeToken=myToken

Please help, it is very urgent !

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. The error message means that 3DS has failed on the card. If possible, please send through the full request / response logs so I can investigate further.

**Comment by staran001** [comment]
The response is this 
{
    "status": 400,
    "message": "PaymentsCardHolderAuthenticationInvalidStatus",
    "eventId": "2061"
}

**Comment by nkapetanopoulos** [comment]
I send you the requests and the responses
I first run the "Generate charge token using card details" and i get the chargeToken
Then i run the "Generate card token using charge token" and i get the error mentioned

**Please keep in mind that that until yesterday this was working in both demo and production**


[Generate card token using charge token.txt](https://github.com/VivaPayments/API/files/4109106/Generate.card.token.using.charge.token.txt)
[Generate charge token using card details.txt](https://github.com/VivaPayments/API/files/4109107/Generate.charge.token.using.card.details.txt)

**Comment by matthewrgourd** [comment]
Hi @nkapetanopoulos I'm getting the same. Will need to get feedback from our development team. I'll update you as soon as I can...

**Comment by nkapetanopoulos** [comment]
Continuing the issue with some info which may help you to address it

I try the test card 4111111111111111 with the **LIVE** API (https://api.vivapayments.com/acquiring/v1/cards/tokens?chargeToken=myTKN)
and i can generate the card token
The response is:
{
    "chargeToken": "ctok_xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "redirectToACSForm": null
}
Then i proceed with the generation of the card token and of the final charge token which i will use in my payment

When i try the same with a normal/valid card i get
The response is:
{
"chargeToken": "ctok_ukYY2imSQza7f8EgcMjHQBiYos4",
"redirectToACSForm": "html code rendering page for 3DS processing"
}

1. **With the same card my code was working fine until Thursday afternoon, i was able to create the appropriate tokens an execute payments!**
2. **I do not want to redirect the user to any other page, i need the payment to be executed in my page with the user just giving the credit number, cvv and card expiration date, as it has always have been in our site!**

Please advise

**Comment by matthewrgourd** [comment]
@nkapetanopoulos I've spoken with our dev team and I'm not sure why you're suddenly experiencing this issue. However, just to confirm the way Native Checkout v2 should work and give you a way of testing on demo:

1. Create one-time charge token and wait until the 3DS session closed. There is a parameter in the chargetoken endpoint called `SessionRedirectUrl` that can be filled with the desired endpoint. After the session is closed the iframe within which the 3DS window is rendered will redirect to the given endpoint. Finishing the session doesn't mean that the 3DS authentication is successful it means that it has its final status (approved / declined)

2. Exchange charge token with card token (if card storage required for future payments. Card tokens can be exchanged for charge tokens as many times as necessary).

3. Complete transaction using charge token.

Here is a one-time charge token you can use once to see how the response should look with a simulated 3DS-authenticated transaction: `ctok_VUSo1PjkrBfxFIVSTVPUxBiHFIU`

E.g. 
```
curl -X POST \
  https://demo-api.vivapayments.com/nativecheckout/v2/transactions \
  -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6IkpXVCIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCJ9.eyJuYmYiOjE1ODAxMzkzNDEsImV4cCI6MTU4MDE0Mjk0MSwiaXNzIjoiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJhdWQiOlsiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIiwiY29yZV9hcGkiXSwiY2xpZW50X2lkIjoiODl1bzFiZHR4dWI2OGRjbDkwYm5mZGJyMDFjOWZndW11cWF4NTAxbTlpODM1LmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiJGQkYxRTA5MC02NURFLTRDNzUtQjU4MC1EOUQ5QkM0OTRBRDIiLCJzY29wZSI6WyJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmciLCJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmc6Y2FyZHM6dG9rZW5zIiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6bmF0aXZlY2hlY2tvdXR2MiJdfQ.Se_X8uinm-i3n6JBwazwFW7ISQ9tXsKw-N24XkhTvTh9hZfeRUgnGgGiegznI7U8b-koF9HI6FZ-3SaHpl3PFD0zDgb8V2CSSF3SfZ0J5-EXtEBl4_cUxp7XuuFfg8am2g4UzFeZIE-VbUxx56JgoJRug9fMgDceqPBLkcsspv1RLVGHrq_Y_DO62n3gRVRJpZCWcK4j0KnjGXmzvSwWJXdROShbh0IWr3NBoUDGajj7C5FDecwwRsrXFCA-PoBzjtVEva6NwnUiqyuj50Pzl7nzj4-W7xf-iwQ_NW1lm7FPAAlGcSZJHM3D0dIfwdEZmYg-Dh9evV3jEnCZbnkXkQ' \
  -H 'Content-Type: application/json' \
  -d '{
  "amount": 100,
  "preauth": false,
  "sourceCode": "9158",
  "chargeToken": "ctok_VUSo1PjkrBfxFIVSTVPUxBiHFIU",
  "Installments": 1,
  "merchantTrns": "Merchant transaction reference",
  "customerTrns": "Description that the customer sees",
  "currencyCode": 826,
  "customer": {
	  "email": "native@vivawallet.com",
	  "phone": "442037347770",
	  "fullname": "John Smith",
	  "requestLang": "en",
	  "countryCode": "GB"
   }
}'
```

**Comment by matthewrgourd** [comment]
Native Checkout v1, which I think you're currently using, will be unavailable from the end of this month so you need to migrate to v2, above, as soon as possible. This is in order to comply with the latest PSD2 updates, specifically Strong Customer Authentication.

**Comment by nkapetanopoulos** [comment]
I understand what you are suggesting but what about the method WITHOUT 3ds that we have implemented and tested and it was working until Thursday in both demo and live ?

Our company's needs demand native checkout v2 WITHOUT 3DS

Thank you in advance for your answer

**Comment by matthewrgourd** [comment]
Hi @nkapetanopoulos, sorry if I misunderstood your query. Again, I need to check with our dev team. I'll get back to you as soon as I've an answer.

**Comment by staran001** [comment]
I would like also to mention here that the endpoint for card tokenization is "acquiring/v1/cards/".
Does this mean that it is also going to be unavailable, since it is under the v1 ??

**Comment by matthewrgourd** [comment]
@staran001 no, the v1 in `acquiring/v1/cards` is in a different context unrelated to Native Checkout v1.

**Comment by nkapetanopoulos** [comment]
Hi @matthewrgourd
If acquiring/v1/cards is in a different context unrelated to Native Checkout v1, then i should be allowed to use 

1. https://demo-api.vivapayments.com/acquiring/v1/cards/tokens?chargeToken=chargeToken
2. https://demo-api.vivapayments.com/acquiring/v1/cards/chargetokens?token=cardToken

to create the charge token for my payment transaction as i did until few days ago !!!

**Comment by matthewrgourd** [comment]
@nkapetanopoulos please check the [Card Tokenization](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/) page within our developer portal as I believe this covers what you're referring to.

**Comment by nkapetanopoulos** [comment]
@matthewrgourd these are the exact steps i have implemented and tested

But since Friday, "Step 2: Generate card token using the charge token" returns
{
    "status": 400,
    "message": "PaymentsCardHolderAuthenticationInvalidStatus",
    "eventId": "2061"
}

I guess this is because of 3DS, a feature that we DO NOT WANT TO USE
I hope it is clear enough

**Comment by matthewrgourd** [comment]
Hi @nkapetanopoulos this is the correct behaviour if 3DS authentication hasn't been passed. You need to update to the method I've described in detail both in the documentation and further up the chain of replies in this issue.

**Comment by nkapetanopoulos** [comment]
Hi @matthewrgourd 
so, there is no way to bypass 3DS user authentication ?

**Comment by matthewrgourd** [comment]
@nkapetanopoulos I'm checking for you...

**Comment by matthewrgourd** [comment]
Hi @nkapetanopoulos, no, unfortunately there isn't, due to security reasons. However, you can simulate a 3DS-authenticated response using the  code in the below comment:

https://github.com/VivaPayments/API/issues/1311#issuecomment-579708540
