### ISSUE TITLE
Recurring payments possible in native v2

### ISSUE THREAD

**Issue by indevsa** [VivaPayments/API#1333]
Hello,

We have multiple clients using native checkout v1 to receive recurring payments. We are migrating them to native checkout v2, but [the documentation](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) doesn't mention anything about recurring payments.

Is it possible to receive new recurring payments using native checkout v2?

Thanks!

**Comment by matthewrgourd** [comment]
Hi there, I believe our development team is working on this. I will check if we've got an updated timeline for release but at present only the old method is possible: https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/post

**Comment by indevsa** [comment]
Hello and thanks for your response.

Our clients are receiving notifications that the old method is going to stop working on Friday 31/01. Is this accurate?

Thanks!

**Comment by matthewrgourd** [comment]
Hi @indevsa this sounds about right but I will check with our development team and get back to you...

**Comment by matthewrgourd** [comment]
Hi @indevsa our dev team has advised that you do need to migrate to Native Checkout v2 by 31st January. However, our Payment API, including recurring transactions, will remain unchanged: 

- [Create recurring transaction](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1%7BId%7D/post)

**Recurring payments set up using Native Checkout v1** 
Will continue to work in Native Checkout v2.

**Recurring payments set up using Native Checkout v2**
The initial charge will pass through 3DS and every recurring charge after the Initial transaction will not pass through 3DS validation.

**Comment by indevsa** [comment]
> **Recurring payments set up using Native Checkout v2**
> The initial charge will pass through 3DS and every recurring charge after the Initial transaction will not pass through 3DS validation.

On the previous version of the API, there was a parameter you needed to pass (`AllowRecurring`) during the order creation in order to enable recurring payments, which doesn't seem to exist anymore.

Indeed, when we create a payment using native v2 and then try to create a recurring transaction we get the following error:

`{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"Invalid transaction. The transaction e6254f00-737d-43f2-938a-8f505bef7c33 does not allow recurring charge","TimeStamp":"2020-01-27T14:44:21.9949689+02:00","CorrelationId":null,"EventId":0,"Success":false}`

**Comment by matthewrgourd** [comment]
Hi @indevsa , order creation is through our Payment API, as before. Please see [Create payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post) in our API reference guide. The parameter you mention is still available.

**Comment by indevsa** [comment]
Hey @matthewrgourd, how do we reference the created order from the v2 API? There used to be a way in v1, but it doesn't seem to exist in v2.

**Comment by matthewrgourd** [comment]
@indevsa , apologies, I need to check with our dev team. I'll get back to you as soon as I've an answer.

**Comment by matthewrgourd** [comment]
Hi @indevsa, the dev team have got back to me and apparently a v2 way of doing recurring transactions isn't available yet. They suggest tokenizing cards in order to charge a card multiple times.

**Comment by 5361796f6e617261** [comment]
Hi @matthewrgourd can we reuse exists `recurring transaction` to get card tokens?

**Comment by matthewrgourd** [comment]
Hi @5361796f6e617261, I'm nt sure what you mean by that. Can you give me a little more information?
