### ISSUE TITLE
Confirming integration method change

### ISSUE THREAD

**Issue by safwen1** [VivaPayments/API#1334]
Our client has some types of cards not working when they require an SMS token step, so we would like to test the second integration method **Native/Pay avec Viva Wallet Checkout**

Please confirm this change for us.
Merchant ID : 0eaaf41b

**Comment by safwen1** [comment]
PS: One of the payments that did not succeed was done at 2020-01-23 16:23

retry at 2020-01-23 17:57:15

**Comment by matthewrgourd** [comment]
Hi @safwen1 I'm not sure what you mean. I've checked the account and I see that Redirect Checkout is currently in place. All other settings seem correct. By the way, you shouldn't really be posting the Merchant ID publicly so I've erased part of it.

**Comment by safwen1** [comment]
Hello @matthewrgourd 
Our problem is that some customers are not able to pay with their credit card in some cases. And we cannot know why therefore I sent you the date and time of one of these failed transactions to check if you can tell us what the cause is. (The customer tried several times, she sees no error or anything just a blank screen then she is redirected to our website without any error)
2020-01-23 16:23

**Comment by matthewrgourd** [comment]
Hi there, sounds like an issue with her 3DS authentication which will be handled by her issuing bank. There should be a popup asking for certain details, but unfortunately this part is not handled by ourselves. It's possible if she tries a different browser, (e.g. Chrome or Firefox) the problem will be resolved.

**Comment by safwen1** [comment]
Hello again @matthewrgourd , the customer retried today at 12:34 with Chrome, problem persists. 
She can pay on other websites so it is not a problem with her bank.
Is there any way to debug this? It is an urgent matter.
