### ISSUE TITLE
Payment Notification

### ISSUE THREAD

**Issue by beckermirko2000** [VivaPayments/API#1335]
Hello, i send a payment notification to a buyer that want to pay via debit card and when he press the link, on the link he don't see the payment options.. i think is a problem... Thank you !

**Comment by matthewrgourd** [comment]
Hi @beckermirko2000 as far as I'm aware, payment notifications are working fine. I just tried myself via iPhone and desktop and I can't recreate the issue. Do you know what device your customer is using?

**Comment by beckermirko2000** [comment]
The buyer tried via desktop, can you check this link : https://www.vivapayments.com/web/checkout?ref=4480368814730329&lang=ro-RO

If you see the payment methods there ? Thank you !
________________________________

**Comment by matthewrgourd** [comment]
Hi @beckermirko2000 same thing happens when I view the above link. Did you set the below date / time fields (see below) for a realistic time in the future?

![Screenshot 2020-02-06 at 11 36 11](https://user-images.githubusercontent.com/44943019/73933849-3acd7a00-48d5-11ea-9b06-731a986c37ed.png)

**Comment by matthewrgourd** [comment]
Closing as no reply for a while...
