### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by haramjan** [VivaPayments/API#1336]
Access to XMLHttpRequest at 'https://demo.vivapayments.com/nativecheckout/v2/chargetokens' from origin 'https://www.mailboxpharmacy.co.uk' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I am trying to set header  this way
`headers: {"Access-Control-Allow-Origin": "https://www.mailboxpharmacy.co.uk", "Access-Control-Allow-Headers":"Origin, X-Requested-With, Content-Type, Accept"}` in the  VivaPayments.cards.setup but no success at all

**Comment by matthewrgourd** [comment]
Hi @haramjan I believe any calls to `https://demo.vivapayments.com/nativecheckout/v2/chargetokens` need to be made from a back-end channel not your browser.

**Comment by matthewrgourd** [comment]
Hi @haramjan please reply or close this issue if you've solved the problem. Thanks!
