### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by thewebscripts** [VivaPayments/API#1337]
Hello we have downloaded and installed plugin. All credentials are fed properly. But while testing after entering 16 digits of credit card number and other details the page is redirecting and we are getting an error. attaching the error screenshot. 
Kindly help
![1](https://user-images.githubusercontent.com/60387447/73258719-4f7e8380-41ec-11ea-9954-6bb76053099a.png)

**Comment by matthewrgourd** [comment]
@thewebscripts if you're referring to a Viva Wallet [plugin](http://localhost:1313/e-commerce-plugins/) for an e-commerce platform, please let me know which one it is. There are currently 28 options available.

**Comment by thewebscripts** [comment]
Hello,

Downloaded from this link https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ <https://developer.vivawallet.com/e-commerce-plugins/woocommerce/>

**Comment by matthewrgourd** [comment]
Hi @thewebscripts thanks for confirming. Can you let me know whether you're testing on your live account or on demo?

**Comment by thewebscripts** [comment]
live account

**Comment by thewebscripts** [comment]
Hello 

Tried testing again and everything looks good.

Thanks

**Comment by matthewrgourd** [comment]
Ok, cool. The payment source can't always be set up immediately which is probably why you had to wait. I'm closing the ticket now.
