### ISSUE TITLE
Native Checkout v2 Forbidden

### ISSUE THREAD

**Issue by djdimimc** [VivaPayments/API#1338]
Hello,

I am calling VivaPayments.cards.requestToken as mentioned in the documentation but i get the error message "Forbidden".

That's the code:
`    <script type="text/javascript">
        $(document).ready(function () {
            if ($('#paymentform').length)
            var accessToken = document.getElementById('hdToken').value;
            VivaPayments.cards.setup({
                baseURL: 'https://api.vivapayments.com',
                authToken: accessToken,
                cardHolderAuthOptions: {
                    cardHolderAuthPlaceholderId: 'mdlthreedpane',
                    cardHolderAuthInitiated: function () {
                        $('#mdlthreedpane').show();
                    },
                    cardHolderAuthFinished: function () {
                        $('#mdlthreedpane').hide();
                    }
                }
            });
        });
        function GetChargeToken() {
            var amount = document.getElementById('hdAmount').value;
            VivaPayments.cards.requestToken({
                amount: amount,
                installments: 1,
                authenticateCardholder: false
            }).done(function (responseData) {
                document.getElementById('hdCToken').value = responseData.chargeToken;
            }).fail(function (responseData) {
                document.getElementById('hdCToken').value = 0;
                console.log('Here is the reason it failed: ' + responseData.Error.toString());
            });
        }
    </script>`

The accesstoken is ok.

If Date, Card number, name is not entered, the error message i get, is refereeing to the missing info.
if the above data is entered, i get the Forbidden message, regardless of filling the cvv field or not.

Thanks

**Comment by nkapetanopoulos** [comment]
Why "authenticateCardholder: false" ?

**Comment by djdimimc** [comment]
If setting to true, it throws Bad Request

**Comment by matthewrgourd** [comment]
Hi @djdimimc can you try removing `authenticateCardholder: false` altogether?

**Comment by djdimimc** [comment]
Hi Matthew,

Still the same. Bad Request.

**Comment by matthewrgourd** [comment]
Have you followed our guide closely? https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

**Comment by djdimimc** [comment]
Yes, authToken and amount is being passed from the code behind (.NET) and on step 4, it throws Bad Request.

**Comment by djdimimc** [comment]
Is there a way to check what exactly throws the error?

**Comment by matthewrgourd** [comment]
Hi @djdimimc I think the issue relates to the charge token not representing a 3DS-authenticated request. Please check this code example I posted in response to another query in case this may help: https://github.com/VivaPayments/API/issues/1287#issuecomment-579200937

**Comment by djdimimc** [comment]
Well, the code i posted above works.
it threw an error because i passed by mistake an amount with decimals.
