### ISSUE TITLE
Demo /orders/api redirect doesn't work

### ISSUE THREAD

**Issue by seldimi** [VivaPayments/API#1339]
I'm trying to make a demo payment, as we normally do. Used the php code example.
After payment, demo.vivapayments.com doesn't redirect me back to my website and it seems that some JS are missing.

Can you fix please?

**Comment by matthewrgourd** [comment]
VivaPayments.cards.setup({
	authToken: 'your_access_token',
	baseURL: 'https://demo-api.vivapayments.com',
	cardHolderAuthOptions: {
		cardHolderAuthPlaceholderId: 'threed-secure-pane',
		cardHolderAuthInitiated: function() {
			alert('Cardholder authentication started!');
		},
		cardHolderAuthFinished: function() {
			alert('Cardholder authentication has finished');
		}
	}
});

**Comment by matthewrgourd** [comment]
Hi @seldimi, sorry to hear this. Are you referring to the PHP code sample available here:

https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php

I've not tested the above recently but here's a working example in cURL which should help:
```
curl -X POST \
  https://demo.vivapayments.com/api/orders \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Authorization: Basic ZmJmMWUwOTAtNjVkZS00Yzc1LWI1ODAtZDlkOWJjNDk0YWQyOldEdi1WKw==' \
  -H 'Content-Type: application/json' \
  -d '{
  "Tags": [
    "sample string 1",
    "sample string 2",
    "sample string 3"
  ],
  "Email": "customer@domain.com",
  "Phone": "2117604000",
  "FullName": "Customer Name",
  "PaymentTimeOut": 86400,
  "RequestLang": "en-US",
  "MaxInstallments": 12,
  "AllowRecurring": true,
  "IsPreAuth": true,
  "Amount": 1000,
  "MerchantTrns": "Your reference",
  "CustomerTrns": "Description that the customer sees"
}'
```

**Comment by seldimi** [comment]
Yes, I'm redirecting to the demo viva tab, where I use 4111 card etc, and on success, it says that i can print receipt but no redirect back to success page (and JS broken)

**Comment by seldimi** [comment]
Any news?

**Comment by matthewrgourd** [comment]
Hi @seldimi sorry to hear this, I believe you may have missed out some steps if you're attempting to implement our Redirect Checkout. Please start with 'Prerequisites' on the following page:

https://developer.vivawallet.com/online-checkouts/redirect-checkout

Thanks!

**Comment by seldimi** [comment]
I have added the wallet, its not the first time I'm doing the process..
Also how is the process related to broken Javascript on your page ?!

**Comment by seldimi** [comment]
https://imgur.com/a/vKEKIxZ

**Comment by matthewrgourd** [comment]
Hi @seldimi can you let me have the path to the JS that you say is broken?

**Comment by seldimi** [comment]
https://demo.vivapayments.com/web/Scripts/Globalize/cultures/globalize.culture.en.js

**Comment by seldimi** [comment]
Any news?

**Comment by matthewrgourd** [comment]
Hi @seldimi, I'm afraid I don't know what's going on here. Can I have the URL of your website in order to test a payment myself? If there's anything that needs to be kept confidential, please email me directly at mgourd@vivawallet.com. Thanks!

**Comment by matthewrgourd** [comment]
Hi @seldimi can I have your demo Merchant ID so I can check some things?

**Comment by seldimi** [comment]
$MerchantId = 'ccc814eb-0ece-404d-a31b-8e53c0420abf'; 
$APIKey = '36rfUC'; 
$Source = '1228';

Με εκτίμηση,
Δημήτριος Σελημίδης
------------------------------------------
Web Expert
Ολοκληρωμένες Λύσεις Πληροφορικής
(+30) 2461041995 | (+30) 6982503223
www.webexpert.gr  | info@webexpert.gr

**Comment by seldimi** [comment]
Same thing.. stacks on the page 
Transaction details
Your payment was successful.
Click here to print the transaction's receipt.

**Comment by matthewrgourd** [comment]
Hi @seldimi our dev has replied that you're pointing to the wrong payment source:

>You have to create an order with SourceCode: 1228. Right now you're pointing orders to sourceCode: Default with configuration
UrlSuccess: http://demo.vivapayments.com/web/checkout/result
UrlFail: http://demo.vivapayments.com/web/checkout/result

Hope this helps!

**Comment by seldimi** [comment]
I do have this already initialized on demo.vivapayments.com and on my code
                            
$MerchantId = 'ccc814eb-0ece-404d-a31b-8e53c0420abf';
$APIKey = '36rfUC';
$Source = '1228';

https://imgur.com/a/gLdr9Gx

**Comment by matthewrgourd** [comment]
We're referring to the order creation process.

`https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post`

Field: `sourceCode`

**Comment by seldimi** [comment]
I do.. let me know you
`// Your merchant ID and API Key can be found in the 'Security' settings on your profile.
                            $MerchantId = 'ccc814eb-0ece-404d-a31b-8e53c0420abf';
                            $APIKey = '36rfUC';
                            $Source = '1228';
                            $Amount = $total_advance*100;	// Amount in cents

                            //Set the Payment Amount
                            $query = array();
                            $query['Amount']=$Amount;
                            $query['AllowRecurring']=false;
                            $query['AllowRecurring']=false;
                            $query['RequestLang']='en-US';
                            $query['customerTrns']="Transfer from ".$_POST['location_from_name']." to ".$_POST['location_to_name']." at ".date("d/m/Y H:i", strtotime($date_starts));
                            $query['Source']=$Source;
                            $query['disableCash']=true;
                            $query['disableIVR']=true;
                            $query['disablePayAtHome']=true;
                            $query['email'] = sanitize_text_field($_POST['email']);
                            $query['fullName'] = sanitize_text_field($_POST['name'])." ". $query['last_name'] = sanitize_text_field($_POST['surname']);
                            $query['phone']=sanitize_text_field($_POST['phone_mobile']);

                            $postargs = http_build_query($query);
                            $session = curl_init($request);

                            curl_setopt($session, CURLOPT_POST, true);
                            curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
                            curl_setopt($session, CURLOPT_HEADER, true);
                            curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
                            curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
                            curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

                            $response = curl_exec($session);
                            $header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
                            $resHeader = substr($response, 0, $header_len);
                            $resBody =  substr($response, $header_len);

                            curl_close($session);

                            try {
                                if(is_object(json_decode($resBody))){
                                    $resultObj=json_decode($resBody);
                                }else{
                                    preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader, $match);
                                    throw new Exception("API Call failed! The error was: ".trim($match[1]));
                                }
                            } catch( Exception $e ) {
                                echo $e->getMessage();
                            }

                            if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
                                $orderId = $resultObj->OrderCode;
                                header("Location: https://demo.vivapayments.com/web/checkout?ref=$orderId");
                                exit;
                            }
                            else{
                                echo 'The following error occured: ' . $resultObj->ErrorText;
                            }`

**Comment by matthewrgourd** [comment]
Hi @seldimi , we have tested and our Redirect Checkout works fine in the demo environment. You're posting your source code in a field called `Source` which doesn't exist. Hope this helps!

**Comment by seldimi** [comment]
Oh... I say Source and the new one is sourceCode... Sorry for that .. 
You can close (or delete) now thanks :)
