### ISSUE TITLE
Σχετικά με ποσό πληρωμής μεσω τις φόρμας

### ISSUE THREAD

**Issue by lkounadis** [VivaPayments/API#134]
Γεια σας, θέλω να χρησιμοποιήσω την φόρμα σας σε ενα site ωστε ο χρήστης να μπορεί να καταθέτει το ποσό που θέλει χωρίς προεπιλεγμένη τιμή. Δεν έχω βρεί κατι μεχρι τώρα που να το κάνει αυτό. Μου διαφεύγει κάτι ή όντως δεν γίνεται?

**Comment by defilerc** [comment]
Καλησπέρα @lkounadis ,

Αν ενδιαφέρεστε να χρησιμοποιήσετε την Redirect Checkout (https://github.com/VivaPayments/API/wiki/Redirect-Checkout), μπορείτε να δημιουργήσετε ένα Order με το optional parameter "DisableExactAmount = true", όπως αναφέρεται και στη σελίδα εδώ: https://github.com/VivaPayments/API/wiki/Optional-Parameters

Με αυτό τον τρόπο, ο χρήστης μπορεί να επιλέξει το ποσό όταν μεταφερθεί στην checkout σελίδα, στο περιβάλλον της Viva Payments.

Ευχαριστούμε για την επικοινωνία.
