### ISSUE TITLE
WooCommerce problem with 3DS screen

### ISSUE THREAD

**Issue by NikiKot** [VivaPayments/API#1341]
Hello,
we use your vivawallet plugin for our WooCommerce and our clients complain that the 3DS screen is never shown in a transaction and the payment is never completed! Could you please provide some assistance because we have deactivated the plugin for the time being.

**Comment by matthewrgourd** [comment]
Hi @NikiKot , sorry to hear this. Can you firstly confirm you downloaded our official plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/? It should show a version number of "3.5.7" in the php file. What is the web address of your e-commerce site?

**Comment by NikiKot** [comment]
We have this exact plugin with that exact version. Our web address is https://lisbon.escapegameover.pt/ and we are using your plugin so that customers can pay their bookings! We have deactivated it now because of that error.

**Comment by NikiKot** [comment]
Hello again! Any news about the problem?

**Comment by matthewrgourd** [comment]
Hi @NikiKot are your clients (the ones with the issue) 100% certain their cards are 3DS enrolled. Are other card payments going through successfully with the 3DS?

**Comment by matthewrgourd** [comment]
Hi @NikiKot have you tested on demo using the [sandbox](https://developer.vivawallet.com/getting-started/#sandbox-account)? I'd advise this before switching to production again.

**Comment by matthewrgourd** [comment]
Hi @NikiKot, I'm raising with our development team. I'll get back to you once they've investigated the issue.

**Comment by NikiKot** [comment]
Hello we had test the demo using sandbox but on sandbox by using the default demo account and the default demo card the 3ds doesn't show but the transaction is successful while on the live version the 3ds screen doesn't always show up. After checking the settings of our client and reactivating the plugin the issue was somehow resolved...so I don't know where the problem was. It may needed and activation and deactivation? The transactions are successfully performed now so I think it is resolved for now.
