### ISSUE TITLE
Getting 404 access denied issues

### ISSUE THREAD

**Issue by rajdeeporbsys** [VivaPayments/API#1344]
Hello,

Please check below loom video

https://www.loom.com/share/eba37bcc466f4550b9fb43d343599615

Am getting this access denied error some times

https://www.cbdshopfrance.fr/

**Comment by matthewrgourd** [comment]
Hi @rajdeeporbsys, sorry to hear this. Is that your live e-shop shown in the Loom video? The 404 error includes some info about the API call which seems to be going to your demo account.

**Comment by matthewrgourd** [comment]
Hi @rajdeeporbsys if you could let me know a bit more information about your set-up. Are you attempting to use our plugin for WooCommerce? If so, did you download it from [here](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) and follow the surrounding installation instructions?

**Comment by matthewrgourd** [comment]
Closing as no reply...
