### ISSUE TITLE
I can not get the oath2 token

### ISSUE THREAD

**Issue by dasimakis** [VivaPayments/API#1347]
Dears I tried to implement migration from nativecheckout v1 to 2 and I can not manage to get the oath2 token. I execute the request but it fails with error 411 (length error). My request has no body only headers (according to your example). Can you provide a simple example of getting the access code from .NET httpwebrequest or something similar ? 

Thanks in advance Dimitris

**Comment by dasimakis** [comment]
I finally manage to complete a transaction by myself....However I want to comment that documentation for the nativecheckout 2 is poor and is missing at least one example per network (php, .NET etc).
This forum is not as helpful as I was expected to be. Generally I can not understand why don't you behave as professionals creating the required material for developers. (After all, this is primarily for your own profit. Isn't it ?)

**Comment by matthewrgourd** [comment]
HI @dasimakis , thanks for the feedback. I will take on board your comments. FYI, we plan to expand the documentation in the next couple of months. I'm sorry to only be replying now but our offices are closed at the weekend.
