### ISSUE TITLE
How to get completed order by transactionid

### ISSUE THREAD

**Issue by dasimakis** [VivaPayments/API#1348]
Dears, can you provide a sample request on how to get order details calling transaction API ?
I tried to complete the request to the "https://demo.vivapayments.com/api/transactions/{Id}" using my credentials (_merchantid, pass) but it returns 401 error (unauthorized - "Authorization has been denied for this request.").
Do I have to create an authorization token or something similar to complete the request  and get back order details ?

Please provide a sample web request...

Thanks in advance

**Comment by matthewrgourd** [comment]
Hi @dasimakis here you go:

cURL example:
```
curl -X GET \
  https://demo.vivapayments.com/api/transactions/520a123f-53c2-4152-be27-8bcb54a9d967 \
  -H 'Authorization: Basic ZmJmMWUwOTAtNjVkZS00Yzc1LWI1ODAtZDlkOWJjNDk0YWQyOldEdi1WKw=='
```

**Comment by matthewrgourd** [comment]
@dasimakis let me know if that helps at all...

**Comment by dasimakis** [comment]
Hi #matthewgourd thank you very much for your help. Your solution worked! Before your GET example  I was trying to do it with a POST request but the API (even if it returned OK message the content was empty). Can you image why ? Maybe there is a POST curl example ?
