### ISSUE TITLE
URGENT - VivaWallet Reimbursment Process

### ISSUE THREAD

**Issue by YannMeyrades** [VivaPayments/API#1349]
Hi Matthew,
I hope you're well.

Please, I need an urgent answer from you. I need to reimburse a client from a purchase that the client wishes to return.

Please can you explain to me how to reimburse the client on VivaWallet ?

Thank you

**Comment by matthewrgourd** [comment]
Hi there @YannMeyrades please see https://support.vivawallet.com/hc/en-us/articles/360001355169-How-do-refunds-work- or [contact our customer support team](https://www.vivawallet.com/en-eu/contact-us/). Thanks.
