### ISSUE TITLE
Viva σε Prestashop - Λευκή σελίδα fail μετά την εκτέλεση πληρωμής

### ISSUE THREAD

**Issue by nikpony** [VivaPayments/API#135]
Καλημέρα σας,
έχω εγκαταστήσει σε Prestashop το Viva Payment και όταν επιλέγω να πληρώσω με αυτό με πηγαίνει κανονικά στη σελίδα της viva, συμπληρώνω τα στοιχεία της κάρτας και μετά πάει να με κάνει redirect στο site αλλά μου φορτώνει μια λευκή σελίδα με το fail url.
Τι πρέπει να κοιτάξω;
Ευχαριστώ εκ των προτέρων.

**Comment by defilerc** [comment]
Καλημέρα @nikpony ,

Στη σελίδα που γίνεστε redirect, θα πρέπει στο url να υπάρχει η παράμετρος ?ref= με την τιμή του ordercode που δημιουργήθηκε. 

Ενδεχομένως, το πρόβλημα να προέρχεται κατά τη δημιουργία του Order Code στο προηγούμενο βήμα.

Ευχαριστούμε πολύ.

**Comment by nikpony** [comment]
Καλησπέρα @defilerc ,
σου παραθέτω παρακάτω τα url που παράγει το viva και μετά αυτό που επιστρέφει στη σελίδα.
Το πρώτο είναι χωρίς να έχω συμπληρώσει το Source Code μέσα στο plugin και το δεύτερο (που είναι η κενή λευκή σελίδα) είναι αφού το συμπλήρωσα.

**Χωρίς Source Code συμπληρωμένο (φορτώνει τη σελίδα της Viva μετά την εκτέλεση)**
https://www.vivapayments.com/web/newtransaction.aspx?Ref=8693675132672601
https://www.vivapayments.com/web/checkout/result?s=8693675132672601&lang=el-GR

**Με Source Code συμπληρωμένο (φορτώνει τη σελίδα μας κενή λευκή μετά την εκτέλεση)**
https://www.vivapayments.com/web/newtransaction.aspx?Ref=6239589808072603
https://woodengarden.gr/modules/hellaspay/fail.php?s=6239589808072603&lang=el-GR

**Comment by defilerc** [comment]
Καλησπέρα @nikpony ,

Απ' όσο βλέπουμε, υπάρχει κανονικά η παράμετρος ref= στο url, κάτι που σημαίνει ότι η δημιουργία της παραγγελίας γίνεται κανονικά. Από εκεί και πέρα, αυτό που κάνει η Viva είναι να κάνει redirect σε σελίδα του site σας στο URL που έχετε ορίσει εσείς (ανάλογα αν είναι success/fail η συναλλαγή).

Εφ' όσον λοιπόν ο χρήστης γίνεται redirect στο fail url που έχετε ορίσει εσείς, θα πρέπει να δείτε τη σελίδα του site σας και γιατί αυτή είναι λευκή.

Όσον αφορά την υπόλοιπη διαδικασία, τα πράγματα φαίνεται να λειτουργούν κανονικά.

Ευχαριστούμε για την επικοινωνία.

**Comment by nikpony** [comment]
Καλημέρα σας,
συνήθως αυτό τι πρόβλημα είναι; Θέμα δικαιωμάτων στο φάκελο και στα αρχεία; Τι πρέπει να κοιτάξω γιατί σφάλμα στο log file δεν εμφανίζεται ούτε το Prestashop δείχνει σφάλμα.

**Comment by defilerc** [comment]
Καλημέρα @nikpony ,

Θα πρέπει να επικοινωνήσετε με τους δημιουργούς του Prestashop, για να σας βοηθήσουν στην ερώτησή σας, καθώς τα πιθανά προβλήματα μπορεί να ποικίλουν, ανάλογα με το περιβάλλον που χρησιμοποιείται για την ανάπτυξη του site σας.

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by nikpony** [comment]
Καλησπέρα @defilerc ,
βρήκαμε το παρακάτω error:

2016-06-29 19:08:03.388 [NOTICE] [2.86.209.5:52536-1#APVH_woodengarden.gr] [STDERR] PHP Fatal error:  <br>The encoded file <b>/var/www/vhosts/woodengarden.gr/httpdocs/modules/hellaspay/fail.php</b> is not permissioned for 185.29.24.132 in Unknown on line 0

Τι πρέπει να κάνουμε;

**Comment by defilerc** [comment]
Καλησπέρα @nikpony ,

Φαίνεται να υπάρχει κάποιο πρόβλημα με τα permissions του αρχείου fail.php που έχετε στο server σας. Θα σας προτείναμε να βεβαιωθείτε για αρχή ότι ο χρήστης μπορεί να κάνει navigate στη σελίδα fail.php. 

Υπό κανονικές συνθήκες, οι χρήστες θα πρέπει να μπορούν να δουν τη σελίδα αυτή, βάζοντας το URL της σελίδας στο browser, καθώς αυτή είναι η σελίδα που χρησιμοποιεί η Viva Payments για να κάνει redirect τον πελάτη πίσω στο site σας, μετά από μια αποτυχημένη συναλλαγή.

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by nikpony** [comment]
Καλημέρα @defilerc ,
λοιπόν καταφέραμε να προχωρήσουμε ένα βήμα και να φτάνουμε κανονικά στη σελίδα αλλά ότι πληρωμή και να έκανα ήταν αποτυχημένη. Καμία κάρτα δεν γίνεται δεκτή ακόμα και η demo της viva (41111111111111).
Υπάρχει μήπως πρόβλημα την πηγή πληρωμών μας;
Είναι η 8524 αν θέλετε να δείτε.
Ευχαριστώ.

**Comment by defilerc** [comment]
Καλησπέρα @nikpony ,

Θα πρέπει να μας στείλετε περισσότερα στοιχεία για το λάθος, όπως τον κωδικό πληρωμής (order code) που δημιουργήθηκε, το περιβάλλον που χρησιμοποιήσατε (live/dev), καθώς και το μήνυμα λάθους που λαμβάνετε για να σας βοηθήσουμε περαιτέρω

Ευχαριστούμε πολύ.

**Comment by nikpony** [comment]
Καλησπέρα @defilerc ,
ο κωδικός πληρωμής είναι ο 7655297854972607 και είμαστε σε live mode.
Μήνυμα λάθους δεν το έχω εγώ δεν έχω πρόσβαση στο Vivapayments του πελάτη.
Ευχαριστώ.

**Comment by defilerc** [comment]
Καλημέρα @nikpony ,

Ο συγκεκριμένος κωδικός πληρωμής έχει δημιουργηθεί επιτυχία στο live environment. Φυσικά, η demo κάρτα (4111 1111 1111 1111) δε γίνεται να περάσει στο live environment και γι' αυτό θα έχετε αποτυχημένη συναλλαγή.

Απ' ότι βλέπουμε, υπάρχουν και επιτυχημένες συναλλαγές, επομένως δε φαίνεται να υπάρχει κάποιο γενικότερο πρόβλημα με το λογαριασμό σας.

Αν συνεχίζετε και έχετε πρόβλημα, παρακαλώ στείλτε μας στοιχεία μιας συγκεκριμένης πληρωμής (το order code, καθώς και το μήνυμα λάθους που παίρνετε) για να μπορέσουμε να δούμε τη συγκεκριμένη συναλλαγή.

Ευχαριστούμε πολύ.

**Comment by nikpony** [comment]
Καλησπέρα @defilerc ,
οι επιτυχημένες συναλλαγές που φαίνονται μέσα στην πραγματικότητα δεν δημιούργησαν ποτέ παραγγελία μέσα στο eshop, παρά μόνο την χρέωση μέσω viva.
Ένα παράδειγμα αυτής ήταν αυτή με τον κωδικό 7211811902472607.
Παρακαλώ δείτε το.
Ευχαριστώ.

**Comment by defilerc** [comment]
Καλησπέρα @nikpony ,

Θα θέλαμε να μας πείτε αν:

1. Έγινε redirect ο χρήστης επιτυχώς στην checkout σελίδα της Viva Payments και
2. Αν μετά τη συμπλήρωση των στοιχείων στη σελίδα Viva Payments Checkout, έγινε redirect ο χρήστης στο site σας και σε ποιό url (success/fail) από τα δύο που έχετε ορίσει στην πηγή πληρωμής.

Ευχαριστούμε πολύ

**Comment by nikpony** [comment]
Καλησπέρα @defilerc ,
το 1 έγινε επιτυχώς αλλά το 2 ο χρήστης έγινε redirect στο ακόλουθο url αλλά σε μια λευκή σελίδα. Όπως είπα και πριν όταν ο χρήστης γίνεται redirect στην fail σελίδα (πάλι λευκή κενή) η παραγγελία πέφτει κανονικά στο σύστημα, ενώ στην success όχι.

https://woodengarden.gr/modules/hellaspay/success.php?t=2c0cf5eb-ac48-4742-a31a-a180f2231a7f&s=7211811902472607&lang=el-GR

**Comment by nikpony** [comment]
Επίσης ένας ακόμα κωδικός που τώρα προσπάθησα είναι ο 2979841776772607 κατά την οποία με γύρισε στη σελίδα κανονικά αλλά έλεγε ότι προέκυψε πρόβλημα κατά την πληρωμή σας.
Στο error log της σελίδας μου βγάζει ότι Undefined variable: wbsubmitbutton in modules/hellaspay/hellaspay.php on line 337.

**Comment by themis1970** [comment]
ΤΙ ΜΑΛΑΚΙΕΣ ΜΟΥ ΣΤΕΛΝΕΤΕ ΣΥΝΕΧΕΙΑ ΑΠΟ ΤΗΝ
VIVA???????????????????????????????????

www.koronis.com.gr
www.χονδρικη.gr
<http://www.%CF%87%CE%BF%CE%BD%CE%B4%CF%81%CE%B9%CE%BA%CE%B7.gr>
www.xondriki.eu
www.tzamia-tapetsaries.gr

email: koronis1970@gmail.com

ΕΜΠΟΡΙΟ ΕΙΣΑΓΩΓΗ ΚΑΤΑΣΚΕΥΗ
ΞΥΛΟΥ-ΑΛΟΥΜΙΝΙΟΥ.

ΘΕΜΙΣΤΟΚΛΗΣ ΚΟΡΩΝΗΣ
ΤΗΛ.-FAX 22210 22243
MOBILE: 6972699533
TK.34100
ΒΑΛΣΑΜΑ 4
ΧΑΛΚΙΔΑ

****************************************************************
Προσοχή ! Σύμφωνα με το άρθρο 14 του Νόμου 2672/1998 (ΦΕΚ 290 τ.Α)
τα μηνύματα e-mail, για να είναι έγκυρα θα πρέπει να περιέχουν απαραίτητα :
Ονοματεπώνυμο ή επωνυμία (για Νομικό πρόσωπο), ταχυδρομική διεύθυνση
κατοικίας, αριθμό τηλεφώνου ή fax, ιδιότητα του χειριστή.
Αν τα μηνύματα προέρχονται απο υπηρεσία ή Δημόσιο φορέα να περιέχουν
επιπλέον θέμα, ημερομηνία, αριθμό πρωτοκόλλου.
Το μήνυμα ηλεκτρονικού ταχυδρομείου τεκμαίρεται οτι έχει περιέλθει κανονικά
στον λήπτη αν υπάρξει ηλεκτρονική επιβεβαίωση.
 Οι πληροφορίες ή και τυχόν αρχεία που υπάρχουν σε αυτό το ηλεκτρονικό
μήνυμα είναι προσωπικά και απόρρητα
****************************************************************

Στις 5 Ιουλίου 2016 - 1:54 μ.μ., ο χρήστης nikpony <notifications@github.com

**Comment by defilerc** [comment]
Καλησπέρα @nikpony ,

Το συγκεκριμένο order δημιουργήθηκε με Amount 0.09. Το ελάχιστο επιτρεπόμενο amount είναι τα 30 cents, όπως αναφέρεται και στη σελίδα της CreateOrder: https://github.com/VivaPayments/API/wiki/CreateOrder

Η σελίδα που θα γίνει redirect ο χρήστης μετά την επιτυχία/αποτυχία της πληρωμής, καθορίζεται από εσάς. Δεν είναι κάτι το οποίο είναι στον έλεγχο της Viva Payments για να μπορέσουμε να σας βοηθήσουμε.

Ευχαριστούμε για την επικοινωνία.
