### ISSUE TITLE
No payment added

### ISSUE THREAD

**Issue by nimaris** [VivaPayments/API#1350]
TransactionId returned but the payment was not added to my VivaWallet account.

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Please email me the business name, Merchant ID and transaction ID so I can check: mgourd@vivawallet.com. If you can reference issue #1350 when you do this, I'd be very grateful.

**Comment by matthewrgourd** [comment]
Please also describe a bit more what it is you are attempting to do.

**Comment by nimaris** [comment]
I sent you the information you requested.

**Comment by matthewrgourd** [comment]
Thanks. For ID purposes, what name is on the email?

**Comment by matthewrgourd** [comment]
Ah, sorry, I see the email now.

**Comment by nimaris** [comment]
Dο you have any progress with my request? It is very important!

**Comment by matthewrgourd** [comment]
Hi @nimaris you mentioned about your customer wishing to set up a subscription. Do you have other customers that have successfully done this as it could be a problem with their card?

**Comment by nimaris** [comment]
Yes, many customers have paid successfully. Can you see if his card was
debited?

**Comment by matthewrgourd** [comment]
HI @nimaris I've checked the transaction and no payment was taken. This is due to the issuer not allowing use of the card. Your customer should contact the card issuer.

**Comment by nimaris** [comment]
Ok, thank you.
But why return transaction ID if card not allowed?

Στις Τρί, 4 Φεβ 2020, 15:54 ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @nimaris not sure as I don't know in what context you're getting a transaction ID. Are you attempting to use our [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/)? Please provide more info (i.e. full request / response logs blurring out any confidential info) or close this issue if you feel it is solved.

**Comment by nimaris** [comment]
I sent you some information at mgourd@vivawallet.com.

**Comment by matthewrgourd** [comment]
Hi @nimaris having looked at this further I'm not sure I can solve your issue except to say no payment was taken due to the card issuer failing to honour the payment. I'm afraid I can't comment specifically on the code you sent through.
