### ISSUE TITLE
Payment Example NodeJS

### ISSUE THREAD

**Issue by zacpeires** [VivaPayments/API#1351]
Can I get an example for the simple code in javascript, and/or the authorisation for native checkout. A JS/Node example would be greatly appreciated

**Comment by matthewrgourd** [comment]
Hi @zacpeires are you asking for something in addition to our documentation below?

https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

The JS is here:
https://www.vivapayments.com/web/checkout/v2/js

**Comment by zacpeires** [comment]
@matthewrgourd, can I get a JS example for either the simple checkout, or for setting the auth header and making a payment on the redirect. I would like an example of how to implement it. I.e, on the simple checkout there is an example at the bottom in c#. Are there any examples in express or javascript

**Comment by zacpeires** [comment]
I am looking for additional documentation, preferably for the simple checkout. An express equivalent of the c# code would be ideal

**Comment by ChristianMEC** [comment]
Please I need help integrating the viva-payment trough redirect using Node / Javascript.

Documentation from developer pages is bad, not complete and not working ... please check that too.

I want to implement viva-payments for a shopping platform where will be tens of businesses with hundreds of transactions monthly.

**Comment by matthewrgourd** [comment]
Hi @ChristianMEC, what aspects of our API documentation do you need help with? What is it you're attempting to achieve. Please let me know specifics in a new issue which you can raise from our [GitHub](https://github.com/VivaPayments/API/issues) issues landing page.
