### ISSUE TITLE
Payment pending WordPress issue

### ISSUE THREAD

**Issue by NattyT** [VivaPayments/API#1353]
Hello,

I am experiencing an issue where my Wordpress/Woocommerce orders page does not update from 'Payment Pending' status when a payment has been made through VivaWallet.

I have to check into the Vivawallet dashboard to check that each order has been paid for, but it should just update the status automatically each time a payment has been received.

We recently changed our domain from info@cannabatree.com to info@cannabatree.co.uk and we have updated all areas that we can see to do this on Vivawallet, but it may still be causing a problem somewhere in your system? Please help, thanks

Natalie

**Comment by NattyT** [comment]
Hello,
Please can you tell me if I'm still waiting for an answer, or if the e-commerce label is supposed to help me? Sorry, I have not posted here before?

**Comment by matthewrgourd** [comment]
Hi @NattyT I'm not 100% sure on the answer to this one. It could be that our system doesn't automatically update WooCommerce, but it sounds unlikely. Have all the payments come through to your Viva Wallet sales page correctly?

**Comment by NattyT** [comment]
Hi Matthew,

Thanks for your reply.

All payments show as normal when I check them on the Vivawallet page, it seems like Vivawallet is not sending the confirmation that the payment has been made, and leaves the woocommerce payment page looking like the payment has not been made, when in fact it has. I have to check each order has been paid on Vivawallet, then manually go into each order on Woocommerce and change the 'payment pending' to 'processing' or 'completed.

We have recently changed domains from cannabatree.com to cannabatree.co.uk, not sure if this has any relevance to the problem, but would really like to get this issue sorted please as it's time-consuming and not as it should be.

Many thanks

Natalie


Cannaba Tree

________________________________

**Comment by matthewrgourd** [comment]
Hi @NattyT do you have any further information about the issue so I can attempt to troubleshoot further? Specifically, is there anything recorded in the order notes?

**Comment by matthewrgourd** [comment]
Hi @NattyT I'm going to raise this with our development team who should be able to advise further. Thanks.

**Comment by matthewrgourd** [comment]
HI @NattyT I've checked with our dev team and the Viva Wallet for WooCommerce plugin is definitely working as expected. In order for me to investigate further your settings, please send through the following screenshots if possible:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!
