### ISSUE TITLE
Magento 2.2 - Viva Wallet Plugin is not working and order not placed

### ISSUE THREAD

**Issue by selisc** [VivaPayments/API#1355]
Hi,

I have successfully installed and configured the Viva wallet Ecommerce plugin for my Magento(v2.2.6) store.

Followed & configured the Demo setup with reference to this link : https://developer.vivawallet.com/e-commerce-plugins/magento2.1-2.2/

When I proceed to checkout the its redirecting to Viva wallet page, after completing the Test transaction, the order is not placed and giving the error

I think its due to the Viva wallet plugin which causing the issues.

Can you please assist on this?

**Site's Product URL** : http://ve-staging.aptania.com/2-post-kennedy-rda-24-25-black-w-stainless-steel-24mm.html

**Steps to Reproduce the Issue**
1. Open the Product URL and add it to Cart.
2. Proceed with the Checkout and select Viva wallet as Payment Method.
3. Complete the transaction and will get the transaction failed issue & order not created.

Thanks.

**Comment by selisc** [comment]
Hi,

Any solution on this? Awaiting for the reply. 

Thanks.

**Comment by matthewrgourd** [comment]
Hi @selisc, after entering my payment details and clicking on the charge button I get the following popup which is our 3DS simulation:

![73448818-a3f34180-4359-11ea-8d00-3e7c411d3386](https://user-images.githubusercontent.com/44943019/73839600-4e61dd80-480e-11ea-8995-750a9f279507.png)

I choose 'Success' and the payment proceeds without any issues. What exactly is happening at your end at checkout?

**Comment by selisc** [comment]
Hi,

When I choose "Success" and proceed with the payment, then its showing Transaction Failure Message. Because of this Order is not Placed.

Kindly follow the above mentioned steps on my site's product page, then you will get the same error.

Thanks.

**Comment by matthewrgourd** [comment]
Hi @selisc, I followed your steps, but I'm getting a different result with the transaction going through successfully and a confirmation email sent. Strange.

**Comment by selisc** [comment]
Hi,

Please send the order confirmation screenshot here.

In your previous screenshot, its showing the date as 30th of Jan 2020.

Thanks.

**Comment by matthewrgourd** [comment]
@selisc sorry, I didn't take a capture but included a screenshot from our documentation instead.

**Comment by selisc** [comment]
@matthewrgourd Please check my site and place an order. So that only you will get the issue with viva wallet payment. Because you didn't checked the site & placed order. 

Please check the error which we are facing in our site using Viva Wallet.

![viva-error](https://user-images.githubusercontent.com/42018729/73841319-5d618380-4840-11ea-9cf8-71bc468457d1.png)

**Comment by selisc** [comment]
> Hi @selisc, I followed your steps, but I'm getting a different result with the transaction going through successfully and a confirmation email sent. Strange.

Very strange because you didn't tested that yet. When you received confirmation message with order success.

**Comment by matthewrgourd** [comment]
Here are the steps I took as screenshots (all of which were successful):
1.
![1](https://user-images.githubusercontent.com/44943019/73843461-9b49b200-4816-11ea-8cc8-3f13c401e019.png)
2.
![2](https://user-images.githubusercontent.com/44943019/73843427-8a993c00-4816-11ea-85c1-2695e50ef338.png)
3.
![3](https://user-images.githubusercontent.com/44943019/73843437-908f1d00-4816-11ea-8e8b-3bb13a362674.png)
4.
![4](https://user-images.githubusercontent.com/44943019/73843446-94bb3a80-4816-11ea-9733-7380fc57ea60.png)

**Comment by selisc** [comment]
@matthewrgourd Can you please share the Card Details which you tried to place an order?

I have tried below Card Details :

Card number: 4111111111111111
Expiration date: Any in the future
CVV: 111

**Comment by matthewrgourd** [comment]
Hi @selisc I think the test card details need to be updated in our documentation. The number that works for me is 4016000000040000012 (all other details the same).
