### ISSUE TITLE
Redirect Checkout does not open an actual checkout page

### ISSUE THREAD

**Issue by zacpeires** [VivaPayments/API#1357]
<img width="1262" alt="Screenshot 2020-02-03 at 20 57 35" src="https://user-images.githubusercontent.com/29861914/73690270-e4d7b700-46c7-11ea-850f-157e007b0ff2.png">

**Comment by matthewrgourd** [comment]
Hi @zacpeires can you try https://www.vivapayments.com/web/checkout?ref={orderCode} as mentioned in [Step 2](https://developer.vivawallet.com/online-checkouts/redirect-checkout/#step-2-complete-payment-details-redirect) of the Redirect Checkout guide?

**Comment by matthewrgourd** [comment]
@zacpeires did this work?
