### ISSUE TITLE
Loyalty discounts are not getting applied to cart

### ISSUE THREAD

**Issue by magmaorganicfoodslimited** [VivaPayments/API#1358]
Hi, We have a wordpress website www.britishcbd.net and offer loyalty point which can be redeemed to get a discount. When customers are redeeming them it is not applying it on the viva wallet cart and they are being charged the full amount. 
Our viva account is: Magma organic foods limited

Kind regards
Mazhar Mir
07563432965

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear you're experiencing issues. Are you using Viva Wallet for WooCommerce? Did you download from our official installation page here: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by magmaorganicfoodslimited** [comment]
Hi Mathew,
Yes we did download it from your official download link.
Everything is working fine but when customers are trying to redeem their
discounts from the points they have accumulated. It deducts the points but
does not add the discount to the cart.
Our web developer thought it was the loyalty plugin but has now confirmed
it is viva wallet the has the issue.
Kind regards
Saifi

**Comment by magmaorganicfoodslimited** [comment]
Hi Matthew,
Did you manage to get to the root of the issue?
Kind regards
Saifi

**Comment by matthewrgourd** [comment]
Hi Saifi, I'm checking for you.

**Comment by magmaorganicfoodslimited** [comment]
Thank you for your response

**Comment by matthewrgourd** [comment]
Hi @magmaorganicfoodslimited I don't think you can apply discounts using our payment gateway but I'm double-checking this for you!

**Comment by magmaorganicfoodslimited** [comment]
Hi Matthew,
When we give discount codes they have been working but the loyalty points
are not. It just does not deduct the discount but takes the points off.
Thanks

**Comment by magmaorganicfoodslimited** [comment]
Hi Matthew,
Do you have any update on this?
Can you give me a call please.

Kind regards
Saifi Mir
07563432965

**Comment by matthewrgourd** [comment]
Hi @magmaorganicfoodslimited this is still with our dev team. I'll update you as soon as I can.

**Comment by magmaorganicfoodslimited** [comment]
Hi Matthew,
Please could you get someone to call me as we are losing customers because
of this issue.
Kind regards
Saifi Mir

**Comment by matthewrgourd** [comment]
@magmaorganicfoodslimited I'm chasing for you...

**Comment by magmaorganicfoodslimited** [comment]
Thank you for your response

**Comment by matthewrgourd** [comment]
Hi @magmaorganicfoodslimited so I gather that you're attempting to use a third-party loyalty extension for WooCommerce with our payment plugin. I've checked with our dev team and I'm afraid it is not possible to use this type of extension with our plugin. Apologies for any inconvenience caused.

**Comment by magmaorganicfoodslimited** [comment]
Hi Matthew,
So do you offer a discount plugin? What is the solution to this issue?
Kind regards
Saifi Mir

**Comment by matthewrgourd** [comment]
This issue is not one that can be solved as the plugin you're attempting to use (I'm guessing) is not compatible with our payment gateway. Unfortunately we do not offer our own equivalent product so unfortunately you'll need to either stop attempting to use the discount plugin or switch to another payment provider that supports the plugin. What is the name of the discount plugin out of interest?
