### ISSUE TITLE
transaction failed, 

### ISSUE THREAD

**Issue by 99697997** [VivaPayments/API#1359]
Hi,
After putting all my card details in check out the next step is one page saying that the transaction failed, without any other reason. What can i do? The websit is ilovewater.com.cy

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear you're experiencing issues. A few questions if you don't mind. Are you using Viva Wallet for WooCommerce? Did you download from our official installation page here: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ Are you attempting to pay in Euros and your Viva Wallet account was set up in a country with a different currency?

**Comment by 99697997** [comment]
Hello...

Are you using Viva Wallet for WooCommerce? YES

Did you download from our official installation page here: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.vivawallet.com%2Fe-commerce-plugins%2Fwoocommerce%2F&data=02%7C01%7C%7Cf49807a5f3294c565e6808d7aaddfb06%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637165742679398247&sdata=oAHfR262BwSOrn0VV64TorN8fehdgAuDHdNJFmrZ3Rg%3D&reserved=0>   YES

We first download something else. After you sent me this , we disable the first one and we download the new one (viva wallet) but still the same note (transaction failed)

Are you attempting to pay in Euros YES

and your Viva Wallet account was set up in a country with a different currency? NO

Regards
Marios Kaplanis

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by matthewrgourd** [comment]
Hi @99697997 I'm managed to recreate the issue so will raise with a developer as soon as possible.

**Comment by matthewrgourd** [comment]
Hi there, one of our devs has requested some further information about the failed transaction:

- Correlation ID of the failed request
– your Merchant ID and the enviroment you're using

Please send the info. to mgourd@vivawallet.com referencing this issue (#1359)

Thanks!

**Comment by 99697997** [comment]
Hello,

Regarding the issue (#1359<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVivaPayments%2FAPI%2Fissues%2F1359&data=02%7C01%7C%7Cda233cd01e944522097808d7abd66d4d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637166809746674231&sdata=b8DO355leUe3f739%2FGCAsrB9W9QFPUF1V4Jh15uHkZM%3D&reserved=0>)

Please find below the requested info

Merchant ID = 7efb397b-5fd9-4039-aba3-c2fbb73e98fb

Environment = wordpress/woocomerce - php/mysql

What exactly is the  Correlation ID ?

Please feel free to contact me for any further information

Regards
Marios
Username @99697997

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by matthewrgourd** [comment]
Hi @99697997 I've got the Merchant ID now and will pass on to our dev team. I need to erase it from your post now for security reasons (I meant for you to send it by email only).

**Comment by matthewrgourd** [comment]
In order for us to investigate further could you send through the following screenshots:

- Payment module settings (mask the API Key).
- Viva Wallet payment source settings (include the browser's URL in the screenshot).
- Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
- API Access page (mask API Key, include the browser's URL in the screenshot).

Thanks

**Comment by 99697997** [comment]
Please find attached some screenshots that may be useful[Image]

[Image]

Please feel free to contact me for any further information


Regaeds
Marios Kaplanis


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by matthewrgourd** [comment]
Hi @99697997 sorry, I can't see the screenshots!

**Comment by 99697997** [comment]
[Image]



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by 99697997** [comment]
[Image]

[Image]



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by matthewrgourd** [comment]
Hi @99697997, thanks for emailing those screenshots. One thing I noticed in screenshot 4 is that under **Integration method**, you have "Native/Pay with Viva Wallet Checkout" selected. In fact you need to choose "Redirection/Native Checkout v2".

**Comment by matthewrgourd** [comment]
Hi @99697997 is this still an issue or did you manage to resolve it? Please close if no longer a problem.

**Comment by 99697997** [comment]
Hello there
We are trying to sort it out.  Is still an issue

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 99697997** [comment]
Everything was changed per your suggestion. Still not working. Will it work for you if we pass you some administration access to our website's backend to check this problem yourselves? We have done everything you have suggested.

[Image]

Regards
Marios 99697997

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by 99697997** [comment]
Guys this is really important, we need a solution.

This whole delay is giving my business huge problems.

We tried everything you asked.

Please let me know if you want an administrator account for my website in order to check things out.


Thank you and looking forward to your reply


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by radito123** [comment]
We have the same problem. since 19.Jan. 2020 late afternoon (United Kingdom time) all of our customers are experiencing transaction failed. We have been with the vivawallet for over 14 months and never had such a bad issue with the payment gateway. 
the website is: https://imuscle.co.uk/

**Comment by matthewrgourd** [comment]
HI @99697997, we're still looking into this. Apologies for the delay. By the way in answer to your question, CorrelationID is shown in Chrome if you 'inspect' the transaction failed page, e.g. as below:

![Screenshot 2020-02-24 at 11 36 12](https://user-images.githubusercontent.com/44943019/75149650-77350e80-56fa-11ea-8db4-358c2310f2c3.png)

**Comment by matthewrgourd** [comment]
@radito123 please bear with us.

**Comment by matthewrgourd** [comment]
Hi @99697997 I just tried to pay for one of your products using a Viva Wallet credit card. I reached checkout but am getting a '404 not found' error. Have you disabled the Viva Wallet payment gateway?

**Comment by 99697997** [comment]
Hi,
No we have not. This is the problem we are facing now
Thanks

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by matthewrgourd** [comment]
@99697997 looks like you need to completely remove and re-install, making sure you download from https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip before installing again. One thing I noticed in screenshot 3 you sent through, and duplicated below, is that under Integration method, you had "Native/Pay with Viva Wallet Checkout" selected. In fact you need to choose "Redirection/Native Checkout v2". Can you try that option instead?

![3](https://user-images.githubusercontent.com/44943019/75151988-e95c2200-56ff-11ea-8de9-06ddbc24011e.PNG)

**Comment by radito123** [comment]
no we have not disabled the vivawallet payment.
After all these days on the phone with the support , they couldn't tell me
the problem beside to be putting the blame at me. However when i rang today
they told me that it was the limit on my account has been reached. I had to
request to up my limit. I have done this now, and the limit has been
increased, however i still do get customers with failed transactions.

Thank you
Radi Hristov

**Comment by radito123** [comment]
The information from the above screenshot is not my account.

**Comment by matthewrgourd** [comment]
@radito123 you are replying to the wrong thread. Please delete from this issue (which is @99697997 's) and repost to https://github.com/VivaPayments/API/issues/1402 Thank you.

**Comment by matthewrgourd** [comment]
Hi @99697997 did you manage to make any progress? Just wondering in case I can close the issue...

**Comment by 99697997** [comment]
Yes. Thank you. We have re-install and everything is working normaly

Thanks for your help!!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
