### ISSUE TITLE
Viva Native - Πρόβλημα με πηγές

### ISSUE THREAD

**Issue by vasilisf** [VivaPayments/API#136]
Καλησπέρα σας, 

Έχουμε υλοποιήσει το viva native για λογαριασμό πελάτη μας. Στο test περιβάλλον όλα δουλευάνε όπως έπρεπε χωρίς κανένα πρόβλημα. 

Στην παραγωγή όμως, και κατόπιν των υποδείξεων σας σε ότι αφορά την ρύθμιση των πηγών πληρωμών εξακολουθεί να επιστρέφεται το παρακάτω λάθος:

Error Text: Source Default of merchant 92f473bc-557d-417c-a17f-ec6b31f56175 does not support native checkout Error Code: 403 StatusId: E TimeStamp: 30/6/2016 7:48:31 μμ Transaction Id: 00000000-0000-0000-0000-000000000000

Αναμένουμε την απάντηση σας

Ευχαριστώ πολύ

**Comment by defilerc** [comment]
Καλησπέρα @vasilisf ,

Θα πρέπει να βεβαιωθείτε ότι η πηγή με την οποία γίνεται το CreateOrder είναι ρυθμισμένη να έχει σαν Integration Method την επιλογή "Native/Πληρωμή με Viva Wallet Checkout". Αυτό γίνεται από το διαχειριστικό του εμπόρου και πηγαίνοντας από το μενού στις Πωλήσεις -> Πηγές Πληρωμών και πατώντας πάνω στην πηγή που σας ενδιαφέρει.

Στη συνέχεια, θα πρέπει να βεβαιωθείτε πως κατά τη δημιουργία του CreateOrder, θα πρέπει στην παράμετρο SourceCode να έχετε χρησιμοποιήσει τον *κωδικό* της πηγής (και όχι το όνομα).

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by vasilisf** [comment]
Σας ευχαριστώ πολύ. Αλλάξα το sourceCode και δούλεψε σωστά.
