### ISSUE TITLE
On Line Payment capture

### ISSUE THREAD

**Issue by FarzadMoshfeghi** [VivaPayments/API#1360]
We have integrated VivaWallet to our online Shopify Store
The payments are being captured automatically by VivaWallet - even though we have set the Shopify payment capture to Manual. This means that  when a customer has placed an order the same day and wants it called before it has been fulfilled, we are still having to process a refund. 
Please advise how this is mean to work.

**Comment by matthewrgourd** [comment]
Hi @FarzadMoshfeghi, apologies, I'm not immediately sure of the answer. I will ask our Shopify plugin developer and get back to you.

**Comment by matthewrgourd** [comment]
Hi @FarzadMoshfeghi our dev advises that we do not have a preauth / capture mode available.
Our Shopify integration uses only direct charges. Hope this helps!

**Comment by FarzadMoshfeghi** [comment]
Thank you Matthew. I assume then that all payments are automatically captured in VivaWallet?

 

 




 

 

Faz Moshfeghi CEO 

WINCHESTER MD 
+44 7970 227204
+44 207 486 6183
 <http://www.winchestermd.com/> www.winchestermd.com

 

 

 



 

 

 

 

NOTICE OF CONFIDENTIALITY: This material is not intended for public consumption, distribution or reproduction.  The information contained herein is intended only for the confidential use of the recipient.  If the reader of this message is not the intended recipient, or person responsible for delivering it to the intended recipient, you are hereby notified that you have received this communication in error, and that any review, dissemination, distribution, or copying of this communication is strictly prohibited.  If you receive this in error, please notify the sender immediately. WARNING: Computer viruses can be transmitted by Email. The recipient should check this Email and any attachments to it for the presence of viruses. We accept no liability for any damage caused by any virus transmitted by this Email.

Please consider the environment before printing this e-mail.

**Comment by matthewrgourd** [comment]
Hi @FarzadMoshfeghi that's right, yes. Please close this issue if you believe it has been solved. Thanks!

**Comment by FarzadMoshfeghi** [comment]
Not an ideal situation - most merchant banks expect you to fulfil the order before collecting funds.
This leaves the vendor to abuse - customers who buy something online, then email and want to cancel their purchase.
