### ISSUE TITLE
problem on checkout -- URGENT

### ISSUE THREAD

**Issue by evandoulas** [VivaPayments/API#1361]
![image](https://user-images.githubusercontent.com/43986375/73936410-76733e80-48eb-11ea-8a2f-7c6253754bdf.png)
we are getting this error on specific cards. (others are working)
We have uploaded in the production our new native payment checkout v2 method with 3D secure.

Our site is levanteferries and we are talking about ioniagroup account

Could you please advice asap

**Comment by matthewrgourd** [comment]
Hi @evandoulas, sorry to hear this. Please send me the Merchant ID referencing issue number 1361 and I will investigate. My email address is mgourd@vivawallet.com. Thanks!

**Comment by evandoulas** [comment]
Now it is working.
You can close the issue.

**Comment by matthewrgourd** [comment]
Thanks for letting me know, @evandoulas!
