### ISSUE TITLE
Integration question

### ISSUE THREAD

**Issue by fb4business** [VivaPayments/API#1362]
Hello, is it ok if i re direct my costume the the following link?

https://www.vivapayments.com/web/checkout/simplecheckout?publickey=aW5ggxNmlN2kRg32iUMabOgMbX6konNKQA1cq63e0xM%3D&amount=5000&lang=en&expandcard=true&description=Consultation&disablewallet=true

It’s the link that is the same actually when we click on the pay button that we put on the site , but the payment button on the site we put is from the help page you offer where you give 3 steps to complete the simple checkout, the problem is that we didn’t do step 2 , so we don’t know if the payment button on the site actually works , you can see it in blossom365.com/order

So if you can help us by telling us if the payment button can work without step 2 , or is link above is good instead?

**Comment by matthewrgourd** [comment]
Hi @fb4business looks fine to me!

**Comment by fb4business** [comment]
Thank you 🙏🏻
