### ISSUE TITLE
Website Connection "Pending"

### ISSUE THREAD

**Issue by seancowley** [VivaPayments/API#1363]
Hi all,
I believe we set up a connection between VivaWallet and WooCommerce around a week ago and it's still being listed as pending with a note saying it's awaiting approval, is it possible to have this looked at soon? It's the only thing we are waiting for prior to launch
The website is https://ultra-hemp.com
Thanks
Sean

**Comment by matthewrgourd** [comment]
Hi @seancowley, please email the Merchant ID to mgourd@vivawallet.com and I'll investigate for you. Thanks!

**Comment by matthewrgourd** [comment]
Hi @seancowley I've checked with out accounts team and apparently there's some more info we're asking for before the payment source can be made active. We sent an email on 1st Feb.

**Comment by matthewrgourd** [comment]
Closing as replied via email.
