### ISSUE TITLE
Vivawallet Source Pending

### ISSUE THREAD

**Issue by adssolutions** [VivaPayments/API#1364]
Hello support team,

I have my Website/App source code already set up, but it remains in pending status till now. 
As a result viva wallet cannot redirect payment to success / error page, and so the website (wordpress) keeps order as PENDING. 

Can you assist me on that?

**Comment by matthewrgourd** [comment]
Hi @adssolutions , please email the Merchant ID and trading name to mgourd@vivawallet.com and I'll investigate for you. Thanks!

**Comment by matthewrgourd** [comment]
Hi @adssolutions I've checked with our accounts team and apparently an email was sent on 1st February detailing some actions that are required before the payment source can be activated. Did you receive anything? Please check the registered email address.

**Comment by matthewrgourd** [comment]
Hi @adssolutions if I could have the account name, please?

**Comment by matthewrgourd** [comment]
Hi @adssolutions unfortunately I can't check anything until you send me the name of your business!
