### ISSUE TITLE
Prestashop 1.7 Cannot get module to show on front end

### ISSUE THREAD

**Issue by bekway** [VivaPayments/API#1365]
We installed latest version of Vivawallet module on Prestashop 1.7.5.2
- modules/vivawallet//webhook.php verified and active
- in BO module manager v1.7.6 on top of "other" section list
- both webhooks set to "paymentOptions" (invisible) and "displayPaymentReturn (Payment Return)()" (visible) do not resolve issue
- Vivawallet does NOT appear in payment method (but this is probably normal)
- Vivawallet correctly set up in Groups and Countries and Currencies settings
We tried resetting, same. We tried complete re-install, same. We tried changing API key, same.
Only "bank transfer" option appears on checkout page.

Any other solutions are welcome

**Comment by matthewrgourd** [comment]
Hi @bekway, sorry to hear this. Please send through the trading name and Merchant ID to mgourd@vivawallet.com and I'll investigate.

**Comment by bekway** [comment]
Hi Matthew,
Trading name SARL NATURAL SHOP 65 merchant ID f94e0408-91dd-4151-9891-da52cd7c84e8

I previously write in French I hope you understood the issue. First there was a problem with web hooks, I couldn't get Vivashop to appear on front office so I tried a complete uninstall, and re-install. Automtic install impossible and after manual install via FTP module does not show in Backoffice. I tried two Vivawallet modules, first the one from Github and then the one linked from https://developer.vivawallet.com/e-commerce-plugins/prestashop/
Many thanks
NC

**Comment by bekway** [comment]
copy of previous message and follow up:

From: nick@collinson.fr <mailto:nick@collinson.fr> <nick@collinson.fr <mailto:nick@collinson.fr>> 
Sent: Tuesday, February 11, 2020 10:34 AM
To: frsupport <frsupport@vivawallet.com <mailto:frsupport@vivawallet.com>>
Cc: Philippe Masson <masson.phil@gmail.com <mailto:masson.phil@gmail.com>>
Subject: Problèmes Prestashop
 
Bonjour,
J'ai posté une demande de l'aide sur Github il y a quelques jours, sans réponse pour l'instant, alors je vous contact directement.
Depuis ce post et sous pression du client qui souhaite son magasin activé très vite, j'ai désactivé le module et je l'ai désinstallé. Mais impossible de le re-installé.
Cache désactivé, j'ai même nettoyé tout mention de vivawallet dans la base de données par phpMyadmin.
Installation par Module manager retourne "Vous n'êtes pas autorisé à désactiver le module vivawallet" puisat src/Core/Addon/Module/ModuleManager.php:415
  at PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->disable('vivawallet')
     (src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php:594)
  at PrestaShopBundle\Controller\Admin\Improve\ModuleController->importModuleAction(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (Backoffice/index.php:88)
 
Installation manuel par FTP est possible mais le module ne parait pas dans la liste des modules, alors impossible de le configurer. J'ai essayé un connexion sur modules/vivawallet/webhook.php qui retourne
 
Notice: Undefined variable: postargs in /var/www/vhosts/eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php <http://eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php> on line 38

Notice: Undefined variable: resultObj in /var/www/vhosts/eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php <http://eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php> on line 59

Notice: Trying to get property 'EventData' of non-object in /var/www/vhosts/eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php <http://eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php> on line 59

Warning: sizeof(): Parameter must be an array or an object that implements Countable in/var/www/vhosts/eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php <http://eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php> on line 59
 
Le client est SARL NATURAL SHOP 65 à Hèches dans le 65 (Numéro d'enregistrement 879455426)
 
Le problème avant était au niveau des hooks, c'était impossible de faire paraitre le mode de paiement par vivawallet sur le front end, pour cela j'ai tenté le re-installation complet et maintenant (en fait c'est un troisième re-installation) c'est pire.
 
Merci pour votre aide et bien cordialement
Nicholas C
 
 
Demande de l'aide sur forum Github le 8/01
We installed latest version of Vivawallet module on Prestashop 1.7.5.2
modules/vivawallet//webhook.php verified and active
in BO module manager v1.7.6 on top of "other" section list
both webhooks set to "paymentOptions" (invisible) and "displayPaymentReturn (Payment Return)()" (visible) do not resolve issue
Vivawallet does NOT appear in payment method (but this is probably normal)
Vivawallet correctly set up in Groups and Countries and Currencies settings
We tried resetting, same. We tried changing API key, same.
Only "bank transfer" option appears on checkout page.
Any other solutions are welcome
Nicholas Collinson
Conception et hébergement de sites internet depuis 1994
Collinson Consultant Sarl
Jouandassou
12 Chemin de Labarthe
65220 Fontrailles, France
tél: +33562356443
mobile: +33607912587
E-mail: nick@collinson.fr <mailto:nick@collinson.fr>
https://collinson.fr/web <https://collinson.fr/web>

**Comment by matthewrgourd** [comment]
Hi there, 

Thanks for sending through those details. I'll need to remove your Merchant ID from the post for security reasons. I meant for you to send to my email address! I've checked your account and payment source is active. However, you need to adjust success URL to `modules/vivawallet/success.php` rather than `modules/vivawallet/succes.php`. But in order for me to investigate further I need you to send me the following screenshots:

- Payment module settings (mask the API Key).
- Viva Wallet payment source settings (include the browser's URL in the screenshot).
- Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
- API Access page (mask API Key, include the browser's URL in the screenshot).

Thanks,

Matt

**Comment by bekway** [comment]
Hi again Matt,
I cannot send you these because since I tried a complete re-install this morning I can no longer see Vivawallet in the back office. I put the module folder there manually by FTP but it does not show up at all in the back office, so the pages you request are simply not available as I cannot install it

This is what I previous wrote in French, quickly translated for you:

I deactivated and then re-installed the module but re-installation was impossible.

Cache déactivated, I even cleaned out all mention of viva wallet in the DB via phpMyadmin.
Module manager installation returns "Vous n'êtes pas autorisé à désactiver le module vivawallet" - you are not authorised to deactivate the module and at src/Core/Addon/Module/ModuleManager.php:415
  at PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->disable('vivawallet')
     (src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php:594)
  at PrestaShopBundle\Controller\Admin\Improve\ModuleController->importModuleAction(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (Backoffice/index.php:88)
 
Manual installation via FTP is possible but the module does not appear in the list of modules so it's impossible to configure. I did try connecting to modules/vivawallet/webhook.php which returns:
 
Notice: Undefined variable: postargs in /var/www/vhosts/eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php <http://eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php> on line 38

Notice: Undefined variable: resultObj in /var/www/vhosts/eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php <http://eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php> on line 59

Notice: Trying to get property 'EventData' of non-object in /var/www/vhosts/eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php <http://eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php> on line 59

Warning: sizeof(): Parameter must be an array or an object that implements Countable in/var/www/vhosts/eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php <http://eauetgaz.com/naturalshop65.com/modules/vivawallet/webhook.php> on line 59
 
before the problem was the hooks and it was impossible to get viva wallet to appear on the front end and now I tried the re-installation  the situation is even worse
 
many thanks for your thoughts on this
Nicholas C

**Comment by matthewrgourd** [comment]
Hi @bekway the most up-to-date version of our plugin is available at https://developer.vivawallet.com/e-commerce-plugins/prestashop/ Is this the one with which you're still having issues?

**Comment by bekway** [comment]
Yes, the problem started using this version, I also tried an older version downloaded from Github, same thing. Now I'm back trying the latest version and I get this on Install Module:
Uncaught PHP Exception Exception: "You are not authorised to deactivate the module vivawallet." at ..........[my path]/src/Core/Addon/Module/ModuleManager.php line 415
When the first installation would not appear on the front end I deactivated it, then uninstalled it, then tried to reinstall and got this problem.
N

**Comment by matthewrgourd** [comment]
Hi @bekway if you're sure you've fully removed the previous version and that the error message originates from the later installation one of our developers will need to investigate further. It sounds like a bug.

**Comment by bekway** [comment]
Yes I fully agree, I think it's a bug, especially as I can install other payment modules, like Paypal, without any problem.
To fully remove the previous "almost working except not on Front end"  version of Vivawallet, I first deactivated it in Module Manager, then I deinstalled it, also in Module Manager.
When the module re-install (latest version) did not work the first time, I checked every Vivawallet item was deleted vis FTP, then  I went into phpMyadmin and deleted all references to "vivawallet" (there was just one in ps_prefs called vivawallet_currencies). This did not resolve the issue and reinstall both automatic and manual still do not work.
You should note that this is a fresh latest version of Prestashop and other prestashop websites are operating on the same server without any problem.
NC

**Comment by matthewrgourd** [comment]
Hi @bekway ok I'm going to raise with our dev team and get back to you with an update hopefully soon. Thanks!

**Comment by bekway** [comment]
and thank you Matthew, 
I have been designing and hosting websites since 1994 and I have been using prestashop many many times over the last 5 or 7 years. This is the first time I have encountered something I really do not understand and, in my humble opinion, the explanation must be somewhere in the Vivawallet module code and not in the prestashop or server installation.

**Comment by bekway** [comment]
Hi Matthew, sorry to pester, is there any response on this issue from the dev team? The website has now been offline for 10 days because of this problem.

**Comment by bekway** [comment]
We have the same problem as maragos91 posted here two weeks ago. Does anyone have a solution. Vivawallet module will not install, alert says "you are not authorised to disable this module".

**Comment by matthewrgourd** [comment]
Sorry, @bekway, I can't see a GitHub ticket from @maragos91? Anyway, just to let you know I'm in talks with our new plugin developer but it's difficult to know whether this is a Prestashop configuration problem or on our side. We can't recreate the issue so difficult to troubleshoot. Any updates I'll let you know.

**Comment by bekway** [comment]
Hi Matthew, maragos91 issue is here: https://github.com/VivaPayments/API/issues/1178
It dates from 2019, exactly same problem as us.
To resume: 
- we installed Vivawallet module and configured it and verified with vivawallet website
- could not get module to show on front end
- tried everything (reset, etc.): no success
- deactivated vivawallet module in PS admin
- deinstalled vivawallet module in PS admin
- tried to reinstall latest version of module with .zip from vivawallet website
- no success ("not authorised to deactivate" alert)
- delete led manually all traces on "vivawallet" from DB via php Myadmin
- same: no success ("not authorised to deactivate" alert)

Nearly 2 weeks offline, client is looking for another solution, I don't think it's a PS config issue as we can install other payment modules with no problem.

many thanks for your support
@bekway

**Comment by matthewrgourd** [comment]
Hi @bekway I'm raising with our development team. I'll get back to you once they've recreated the issue.

**Comment by bekway** [comment]
Many thanks Matthew,
Someone else here (from Poland I think) had the same problem and suggested replacing the ps_access table with a fresh version. I tried this and ALL modules disappeared so I reverted back to a backup table.
Now over 2 weeks offline, the client is discussing opening accounts with GreenPay and some other gateways, I fear Vivawallet are losing a customer unless we resolve the issue quickly.
NC

**Comment by matthewrgourd** [comment]
HI @bekway, ok, sorry to hear this. FYI, I've flagged with one of our developers to fully test out the Viva Wallet plugin for PrestaShop plugin but I'm not sure when that will be. As I've only received one other query alluding to the same problem it may well be a problem with your PrestaShop setup. Anyway, sorry not to be of more immediate help.

**Comment by matthewrgourd** [comment]
Hi @bekway , our development team has come back to me. They're investigating the issue and need some further info. When you have a spare moment, would you mind answering the following if at all possible?

1. What version of PHP / MySQL are you using?
2. What kind of webserver do you use for hosting (is it Apache? Linux-based?) 

We see you've raised an [issue](https://www.prestashop.com/forums/topic/960231-exception-you-are-not-allowed-to-disable-the-module/) on the PrestaShop forum. Thanks for that, although I think the problem may well be at our end so please bear with us!

**Comment by matthewrgourd** [comment]
Hi @bekway one other thing, you mentioned you're using PrestaShop 1.7.5. Our plugin was slightly amended to work with 1.7.6 onwards. So you may need to use the previous plugin version, below, or install the latest version of PrestaShop.

[vivawallet.zip](https://github.com/VivaPayments/API/files/4292517/vivawallet.zip)

**Comment by bekway** [comment]
Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz (8 core(s))
Plesk Onyx v17.8.11_build1708180301.19 os_CentOS 6
CentOS 6.10 (Final)
PHP 7.3.15
MSql 5.1.73-8.el6_8

Thanks Matthew

**Comment by matthewrgourd** [comment]
Hi @bekway, just to let you know that our development team has now completed their tests. The conclusion is that our plugin for PrestaShop is working correctly. The problem must be within the PrestaShop e-commerce settings which can often be quite complicated to get one's head around. I wish you luck with this but I'm afraid I can't help any further. Thanks...
