### ISSUE TITLE
Αλλαγή του λεκτικού 'Pay by Vivawallet' στο Prestashop

### ISSUE THREAD

**Issue by limitcracker** [VivaPayments/API#1367]
Χαίρετε,

έχουμε εγκαταστήσει το Vivawallet module για το Prestashop το οποίο μέχρι στιγμής δουλεύει μια χαρά αλλά θα θέλαμε να αλλάξουμε το translation παρακάτω:

**Pay by Viva**
[https://share.getcloudapp.com/E0uEDpkm](https://share.getcloudapp.com/E0uEDpkm)

ώστε να το κάνουμε στα ελληνικά.

Οπότε πήγαμε στο backend του Prestashop και έχουμε αλλάξει το λεκτικό "Pay by Viva".
Παραταύτα παραμένει στα αγγλικά.
όπως μπορείτε να δείτε παρακάτω:
[https://share.getcloudapp.com/yAuLpNdg](https://share.getcloudapp.com/yAuLpNdg)

έχετε κάποια ιδέα γιατί συμβαίνει αυτό ή πως να το επιλύσουμε;
το cache και τα cookies τα έχω κάνει reset μήπως και έφταιγε αυτό.

Με εκτίμηση,
Γιάννης

**Comment by matthewrgourd** [comment]
Hi @limitcracker sorry to hear you're experiencing issues. I've found a response to a similar problem from a while back. Can you check and see if it helps? https://github.com/VivaPayments/API/issues/1132

**Comment by matthewrgourd** [comment]
Hi @limitcracker please let me know if you need further help...
