### ISSUE TITLE
Signature not verified

### ISSUE THREAD

**Issue by mrnice23** [VivaPayments/API#1369]
Hi, 

I entered our viva wallet token and merchant ID and am receiving the error message signature not verified when trying to process a payment on both our websites. can you please advise. 

thanks

**Comment by matthewrgourd** [comment]
Hi @mrnice23 could you let me know what you're attempting to achieve. I need to bit more information as I don't know which of our products / services you need help with.

**Comment by mrnice23** [comment]
Hi, 

We are using viva wallet as our payment provider, since yesterday I am not able to transact anymore, so therefore it will be the online checkout I guess

**Comment by mrnice23** [comment]
Apologies, I think it must be the e commerce plugin to shopify that doesnt work

**Comment by matthewrgourd** [comment]
Hi @mrnice23 thanks for the info. So did you attempt to install our Shopify plugin recently or have you been using it for a while? If the former, have you taken care to follow the step-by-step instructions in our [guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/) verbatim.

**Comment by mrnice23** [comment]
We have been using it for a while with no problem. When trying to activate a second e-commerce site, I accidentally copied the token into the mrnicelondon.com shopify page, and since then it has not been working. I am not quite sure why, as the token didn't change.

**Comment by mrnice23** [comment]
i have also requested a new token to try to rectify the issue over 48 hours ago but have not received one yet.

**Comment by matthewrgourd** [comment]
Hi @mrnice23 sorry for the delay, I can chase if you email the business name and Merchant ID to mgourd@vivawallet.com.

**Comment by matthewrgourd** [comment]
Hi @mrnice23 is your issue resolved now? Did you receive the second token?

**Comment by mrnice23** [comment]
Hi, yes it has been resolved. 
Thank you
