### ISSUE TITLE
(Redirect Checkout) Τέστ πληρωμή E-Banking

### ISSUE THREAD

**Issue by dimlev** [VivaPayments/API#137]
Αφού έχουμε ενεργοποιήσει τα E-Banking/Phone banking ως τρόπους πληρωμής, πώς μπορούμε να τα ελέγξουμε; 

Πχ για την πιστωτική: "To simulate a successful payment on the demo environment, use the card number 4111111111111111 with any valid date and 111 for the CVV2"

Τα υπόλοιπα;

**Comment by dmihos** [comment]
Καλημέρα
Ο τρόπος πληρωμής IVR δε διαφέρει σε τίποτε από την πληρωμή με κάρτα, οπότε μπορείτε να το κάνετε simulate με τον ίδιο τρόπο.
Για cash/ebanking, μπορείτε να δημιουργήσετε κάποια demo OrderCodes με μεγάλο Expiration (PaymentTimeout) και να κάνουμε εμείς simulate τις πληρωμές.
Αποστείλετε τα σχετικά στοιχεία, μαζί με reference για το παρόν issue, στο merchants@vivawallet.com.

**Comment by dimlev** [comment]
Ευχαριστώ για την απάντηση, απλά η διαδικασία αυτή είναι αρκετά χρονοβόρα, σε σημείο που την καθιστά σχεδόν μη πραγματοποιήσιμη.

Υπάρχει μήπως κάποιο βραχυπρόθεσμο σχέδιο για υλοποίηση simulation μέσω του demo.vivapayments.com χωρίς δική σας παρέμβαση;

**Comment by dmihos** [comment]
Δυστυχώς όχι, δεν προβλέπεται στο άμεσο μέλλον.
