### ISSUE TITLE
Issue with Simple checkout

### ISSUE THREAD

**Issue by ammon123** [VivaPayments/API#1370]
I have issue with simple checkout I done everything perfectly like in guide, but it's shows {"FriendlyMessage":"Invalid merchant public key"}, the key is correct, my website test button, www.yourtourlink.com/pay.html how to fix this ?

**Comment by matthewrgourd** [comment]
Hi @ammon123 are you definitely using the key from your demo account?

**Comment by ammon123** [comment]
Yes, I copied from my live account the Public Key, Also I changed to live, everything perfect but still shows up invalid, please could someone give me support email to check my account maybe some issue

**Comment by matthewrgourd** [comment]
Hi @ammon123 I can check your account if you email the Merchant ID and account name to mgourd@vivawallet.com referencing this issue. Thanks!

**Comment by matthewrgourd** [comment]
Hi @ammon123 thanks for emailing that info. through. I notice your html file includes a base URL of https://demo.vivapayments.com when in fact the key being used is from your live account. If you wish to test on live, replace "demo" with "www". Alternatively simply replace the public key from your live account with the public key from your demo account. Thanks!
