### ISSUE TITLE
Simple Checkout problem - payment not finalized

### ISSUE THREAD

**Issue by Oanicica** [VivaPayments/API#1371]
Hello!

I am currently working on implementing Simple Checkout and my problem is that the payment amount isn't substracted from the card.

Here you can see some technical details:

I use this api URL: https://www.vivapayments.com/api/orders?PaymentToken=xxxxxxxxx
I provide Authorization header.
And here is the example of body of my request:

{
"email": "111@1111",
"phone": "11111",
"fullName": "111",
"paymentTimeOut": 86400,
"requestLang": "en-US",
"amount": 1000,
"customerTrns": "Payment for smartfood menu order"
}

I get this response:
{
"OrderCode": 9602053430249752,
"ErrorCode": 0,
"ErrorText": null,
"TimeStamp": "2020-02-11T12:22:14.3024975+02:00",
"CorrelationId": null,
"EventId": 0,
"Success": true
}

So everything seems OK though the money are not substructed from the account.

I would appreciate you help!
Thanks in advance.
Best regards, 
Olha Liashenko.

**Comment by matthewrgourd** [comment]
Hi @Oanicica sorry to hear you're experiencing issues! Can you let me know from where in our [documentation](https://developer.vivawallet.com/) you got https://www.vivapayments.com/api/orders?PaymentToken=xxxxxxxxx?

**Comment by Oanicica** [comment]
Hello @matthewrgourd ! In the meantime we talked to the merchant and his source is still pending. Could this be the reason?

**Comment by matthewrgourd** [comment]
Hi @Oanicica aha, yes, the payment source needs to be active so that will be the problem. The merchant should have received an email telling them what they need to do before we can proceed. Let me know if not!

**Comment by Oanicica** [comment]
Yes, he did. If they will still have problems I will revert to you. Thanks!

**Comment by matthewrgourd** [comment]
@Oanicica Ok, no problem!
