### ISSUE TITLE
Depuis quelques heures les transactions ne passe plus plus appel a l'API ou LURL erreur Prestashop 1.7.6.1

### ISSUE THREAD

**Issue by support-cids** [VivaPayments/API#1373]
Bonjour on a une erreur lord de l’appel de l’url de paiement ca vient de se déclencher a l’instant 

Hello we have an error lord of the call of the payment url ca has just started at the moment

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by support-cids** [comment]
tout marché bien encore ce matin pas de MAJ de modules on a rien bougé de la journée et plus rien ne marche . Comme je vous disais par mail tant que nous ne pouvons plus prendre de transactions avec vous on passe d'ailleurs. 

everything worked well again this morning no update of modules we did not move anything during the day and nothing works. As I told you by email as long as we can no longer take transactions with you we go elsewhere
.

**Comment by support-cids** [comment]
Piste de l'hébergeur rien a signaler coté Vivawallet pour le moment

**Comment by matthewrgourd** [comment]
Hi @support-cids sorry to hear you were having issues earlier. Is everything ok now and that's why you closed the ticket?
