### ISSUE TITLE
ΔΟΣΕΙΣ ΜΕ WEBSITE/APP

### ISSUE THREAD

**Issue by asmartgr** [VivaPayments/API#1374]
Καλησπέρα,

έχουμε εγκαταστήσει το plugin της Vivawallet στο site μας και θα θέλαμε να ξέρουμε εάν υπάρχει τρόπος να ορίζουμε σε ποια προϊόντα μπαίνουν οι δόσεις, γιατί προς το παρόν μπαίνουν σε όλα τα προϊόντα.

Υπάρχει κάποιος κώδικας για να ενσωματώσουμε στο php του plugin και μετά να δημιουργήσουμε φίλτρο (attribute) σε κάθε προϊόν που θέλουμε να έχει δόσεις, π.χ.

1) Εάν το προϊόν έχει το attribute (pa-doseis) με επιλεγμένο Yes, το προιόν υποστηρίζει δόσεις. 

2) Εάν το προϊόν έχει το attribute (pa-doseis) με επιλεγμένο No, το προιόν δεν υποστηρίζει δόσεις. 

Επίσης θα θέλαμε να μάθουμε με πιο τρόπο μπαίνουν οι δόσεις στη ρύθμιση π.χ.

εμείς θέλουμε όλα τα προϊόντα μας άνω των 100 ευρώ να έχουν έως 12 άτοκες δόσεις

**Comment by matthewrgourd** [comment]
Hi there, could I first ask which of our [e-commerce plugins](https://developer.vivawallet.com/e-commerce-plugins/) have you installed?

**Comment by asmartgr** [comment]
Hi,

we have download the zip file from your official site (*WooCommerce
Vivawallet Gateway*) and it works. But we have another problem now. We use
the native version but when we put the credit card info there is not an
option to choose the installments.

I attach screenshot.



*Με εκτίμηση,*
*Η ομάδα του a-smart*






Τηλ: 2311261683
Κιν: 6908243506
E-mail: info@a-smart.gr
Web: a-smart.gr


Στις Παρ, 14 Φεβ 2020 στις 12:30 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Closing issue as duplicate of #1376 which I will respond to in a bit!
