### ISSUE TITLE
404 - File or directory not found.

### ISSUE THREAD

**Issue by asmartgr** [VivaPayments/API#1376]
Hello,

we have installed the plugin and when we tried to test the payment method the above error occurs:

The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

![VIVAWALLET ERROR](https://user-images.githubusercontent.com/61015027/74515910-25310380-4f18-11ea-97ca-4873dd0aff39.jpg)

**Comment by matthewrgourd** [comment]
Hi @asmartgr sorry to hear this. Can I just check, are you attempting to install our official plugin downloadable from the top of our [installation guide](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/)?

**Comment by asmartgr** [comment]
Hi,

yes we have download the zip file from your official site and it works now.
But we have another problem now. We use the native version but when we put
the credit card info there is not an option to choose the installments.

I attach screenshot.



*Με εκτίμηση,*
*Η ομάδα του a-smart*






Τηλ: 2311261683
Κιν: 6908243506
E-mail: info@a-smart.gr
Web: a-smart.gr


Στις Παρ, 14 Φεβ 2020 στις 12:28 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @asmartgr do you mean on the payment screen here?

![image](https://user-images.githubusercontent.com/44943019/74530820-ef454c80-4f22-11ea-9c16-f66a47efa9fe.png)

**Comment by asmartgr** [comment]
Yes,

on the payment screen there is not an option to choose up to 12
installments.



*Με εκτίμηση,*
*Η ομάδα του a-smart*






Τηλ: 2311261683
Κιν: 6908243506
E-mail: info@a-smart.gr
Web: a-smart.gr


Στις Παρ, 14 Φεβ 2020 στις 2:10 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
@asmartgr I'm checking for you.

**Comment by asmartgr** [comment]
Good morning,

have you checked our problem? Cause we need to setup our installments and
the problem keeps occurring.



*Με εκτίμηση,*
*Η ομάδα του a-smart*






Τηλ: 2311261683
Κιν: 6908243506
E-mail: info@a-smart.gr
Web: a-smart.gr


Στις Παρ, 14 Φεβ 2020 στις 3:28 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by asmartgr** [comment]
Hello,

i have not received any answer for our issue. Have you checked our problem?

**Comment by andreatosi89** [comment]
Hello, I got the same issue.
The test environment doesn't work and I get 404 error.
[
![demo vivapayments_404-IIS](https://user-images.githubusercontent.com/43884956/75025191-047a2800-549b-11ea-8526-6d78b6c8ee63.png)
](url)

**Comment by matthewrgourd** [comment]
Hi @andreatosi89 they resolved this. Now their issue is related to instalments. Please raise the 404 error via a new ticket so I can deal with separately. Provide as much info as possible as to what it is you're trying to do in the demo environment.

**Comment by matthewrgourd** [comment]
Hi @asmartgr I'm told the instalments option is available only in Greece. Where are you based?

**Comment by asmartgr** [comment]
Hello,

we have solved our issue. Thank you for your concerne.



*Με εκτίμηση,*
*Η ομάδα του a-smart*






Τηλ: 2311261683
Κιν: 6908243506
E-mail: info@a-smart.gr
Web: a-smart.gr


Στις Παρ, 21 Φεβ 2020 στις 12:16 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @andreatosi89 you've put in the URL without an order code at the end. So the 404 error is correct. Try https://demo.vivapayments.com/web/newtransaction.aspx/?Ref=9588935208827383 and as an example and you'll get the correct payment page. If you're still experiencing issues, please raise a new ticket on GitHub.

**Comment by andreatosi89** [comment]
Hi @matthewrgourd,
as you suggested I've opened a new ticket:
https://github.com/VivaPayments/API/issues/1398
Yes, I've noticed that the URL has not the ref code, but this should be an automatic request, shouldn't be?
When I click the button the URL should have the ref code, it's not something I have to put manually. Am I wrong?
Anyway let's discuss under the ticked I've opened.
Thank you.
