### ISSUE TITLE
Technical Help Needed Urgently Please. 

### ISSUE THREAD

**Issue by ellebee80** [VivaPayments/API#1378]
Hi, I need some tech help please? I have several issues,   The payment processor has been working fine on my wordpress website until today, I integrated the system myself months ago, its been working fine and nothing has been changed on the site however. 

1, The landing page for successful payments has been working fine, today the landing page has changed to an Error 404 page and I have no idea why. 

2, Due to the issue above a customer has attempted to place an order 3 times and 3 payments have been taken however only 2 orders have been generated on my order system and the 3 payments show only 2 order numbers.  One order number is on 2 payments and the other order number on 1 payment.  I have no idea how this has happened as the order number is generated when the payment is made.  The payments with the same order number where made 6 minutes apart.  I have raised this issue with Viva Wallet who are looking into this one. 

3, I have placed a test order and the payment receipt email I have received does not have my order number attached,  The invoice also doesn't show the order number when downloaded.  This has not happened before and the order number has always been attached.  I also have no idea why this is happening. 

Please can someone assist as this is really bad for business.

**Comment by matthewrgourd** [comment]
Hi @ellebee80 I'm sorry to hear this. First I just need to ask, is the plugin you mention our official Wordpress plugin? You will need to have downloaded it from the page below:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by ellebee80** [comment]
Hi yes it is this one below

WooCommerce Vivawallet Gateway Version 3.5.7

Just to mention I did update woocommerce 2 weeks ago but didn't get any notification that I needed to update/change Viva.

Thank

**Comment by matthewrgourd** [comment]
Hi @ellebee80 if you've already raised with Viva Wallet Customer Service let's wait to see the outcome. It could be an account rather than a technical issue. Thanks!

**Comment by ellebee80** [comment]
Hi

Only point 2 has been raised, the others haven’t as they told me to discuss them with you 

Thanks

**Comment by matthewrgourd** [comment]
Hi @ellebee80 please can you update me on whether your issue has now been solved. Thanks!

**Comment by ellebee80** [comment]
Hi yes it has because I deleted and reinstalled however no one has bothered to reply to me or give me any support from Viva,  and the issue with the payment being taken twice for the same order has not been advised on either! I am pretty shocked at the technical support from Viva,

**Comment by matthewrgourd** [comment]
Hi @ellebee80 I'm sorry you feel that way. Just to point out that I've replied to you three times since you raised the issue 7 days ago. I was waiting for you to clear with customer service the account problems so I could narrow it down to being a technical problem. Also, unfortunately we don't have anyone else to check this GitHub page and I was on annual leave this week!

**Comment by ellebee80** [comment]
I’m sorry but that’s not really acceptable, the last comment on here was mine advising you that customer service were only dealing with issue 2 and I needed help with the other issues, I didn’t get it, I understand you were on annual leave which you are entitled to however this is the only technical support we can get to for a service that we pay for through our % deduction so there really should be more than one person helping and certainly not left with zero support when someone is on leave

**Comment by matthewrgourd** [comment]
Thanks for the feedback @ellebee80 . I will pass on your concerns. Apologies for any inconvenience caused.
