### ISSUE TITLE
Δυνατότητα διατήρησης token κάρτας για επαναλαμβανόμενες χρεώσεις

### ISSUE THREAD

**Issue by nikosmouroutis** [VivaPayments/API#138]
Καλησπέρα, αναπτύσσω μια εφαρμογή στην οποία θέλω:

1. Ο χρήστης να εισάγει τα στοιχεία της κάρτας του μέσα από το δικό μου περιβάλλον (native)
2. Να αποθηκεύω μόνο ένα token (το οποίο να μην λήγει).
3. Να μπορώ να χρεώσω την κάρτα του σε δεύτερο χρόνο.

Κάτι σαν την λογική που έχει το taxibeat που ο χρήστης εισάγει την κάρτα του και αυτή χρεώνεται σε δεύτερο χρόνο χωρις να μεσολαβεί ο χρήστης.

Αυτή την στιγμή χρησιμοποιώ την εξής λογική:

1. Δημιουργώ ένα token στέλνοντας τα στοιχεία της κάρτας στο endpoint: http://demo.vivapayments.com/api/cards?key=XXXXXXX
2. Αποθηκεύω το token στον χρήστη (Στην βάση μου)
3. Δημιουργώ μια παραγγελία στο http://demo.vivapayments.com/api/orders
4. Εκτελώ την παραγγελία με το token από το βήμα 1

Το πρόβλημα εδώ είναι ότι το token λήγει αρκετά σύντομα.

Δοκίμασα στο βήμα 3 να βάλω στην παραγγελία το {"AllowRecurring": true} με την λογική να χρεώσω 0.5€ τον χρήστη και να τα κάνω refund αμέσως έχοντας ταυτόχρονα το δικαίωμα να εκτελέσω RECURRING TRANSACTION χρησιμοποιώντας το TransactionId. Αλλά από ότι κατάλαβα πρέπει να μεσολαβήσει το ui της viva και ο χρήστης να πατήσει το αντίστοιχο checkbox κάτι το οποίο δεν με καλύπτει.

Στην ενότητα [CreateRecurringTransaction](https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction) αναγράφεται το εξής: 

> The cardholder has agreed on allowing recurring payments on their card.

Πώς μπορώ στην διαδικασία του tokenization να δηλώσω ότι ο χρήστης έχει συμφωνήσει να χρεώνεται η κάρτα του και άρα το token να μην λήγει (εννοείται πως ο χρήστης θα το αποδέχεται στο δικό μου UI)

**Comment by defilerc** [comment]
Καλησπέρα @nikosmouroutis ,

Για να υλοποιήσετε την επιθυμητή λειτουργικότητα που θέλετε, θα πρέπει καταρχάς στη φόρμα που θα εμφανίζεται στον πελάτη, να έχετε ένα checkbox, με το οποίο ο χρήστης θα συμφωνεί ότι αποδέχεται recurring πληρωμές στην κάρτα του.

Στη συνέχεια, θα πρέπει να δημιουργήσετε ένα Order, το οποίο θα έχει το flag AllowRecurring == true, ώστε να μπορείτε να πραγματοποιήσετε recurring πληρωμές στο ίδιο Order.

Για την αρχική χρέωση του πελάτη, θα πρέπει να ακολουθήσετε τα βήματα που περιγράφονται στη [native checkout](https://github.com/VivaPayments/API/wiki/Native-Checkout), ώστε να πάρετε τα στοιχεία της κάρτας από τον πελάτη, να δημιουργήσετε ένα tokenId με κλήση στο Viva Payments API και να κάνετε την αρχική χρέωση με βάση αυτό το tokenId. Αν η συναλλαγή είναι επιτυχής, στο response θα πάρετε ένα transactionId, που είναι μοναδικός κωδικός της συναλλαγής.

Οι μετέπειτα χρεώσεις, θα πρέπει να γίνουν με post στο URL /api/transaction/{transactionId} χρησιμοποιώντας το transactionId της αρχικής πληρωμής, όπως περιγράφεται στη σελίδα [εδώ](https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction)

Αν παρ' όλα τα παραπάνω, συνεχίζετε να αντιμετωπίζετε κάποιο πρόβλημα, παρακαλώ στείλτε μας περισσότερες πληροφορίες, όπως για παράδειγμα, ένα συγκεκριμένο order code που δημιουργήσατε, καθώς και ένα συγκεκριμένο error response που λαμβάνετε σε κάποιο από τα παραπάνω βήματα, για να μπορέσουμε να σας βοηθήσουμε περαιτέρω.

Σας ευχαριστούμε πολύ για την επικοινωνία.

**Comment by nikosmouroutis** [comment]
Το demo merchantID μου είναι: 87c2019d-2584-4dd1-b3d5-a9b0e708ff18

1. Έκανα tokenize την κάρτα στέλνοντας
`{"Number": '4111111111111111',"CVC": 111,"ExpirationDate": '2017-06-15',"CardHolderName": 'Customer Name'}`
στο http://demo.vivapayments.com/api/cards?key=ΧΧΧΧΧ
και έλαβα
`{
  "Token": "aIhwc3yNL9TUWnw7Hc+axUB8FxELS0R+gBTtINf9ajO5ZIgZjct5zaVun0OBED7vdw2XihfTbdfY8GS1AAxavdXo5M4RENkZq8TGgROTiwNq5BOf5LCHaTrdfoNJrsY8Ae8DwLz3XNBhHyD3lDbxBWJriSOVyrBmSjKk4wO3dXWZ7jtj9LpFHr7+3s6MLn83lhQOa9Pxof5Owp4DtMKAUPB3LqwTa2UxvEs9GLaGX65r+tx8yDCBGRpeaVAHSfyvsE8HGKa6ugUfPFMXN5TKIqrXDwo5sYYRRF3opMBMyKcAih86z4znGHnGiuKRqHbwHNC/QMrcqrXn9/Nm7KLeb0wQVvoIGwjxeA29JsL7tQ0=",
  "TransactionId": null
}`

2. έφτιαξα order στέλνοντας
`{
  "Amount": 50,
  "SourceCode": 1414,
  "AllowRecurring": "true",
  "IsPreAuth": "false"
}`
στο http://demo.vivapayments.com/api/orders
και έλαβα:
`{
  "OrderCode": 5507758366572609,
  "ErrorCode": 0,
  "ErrorText": null,
  "TimeStamp": "2016-07-04T18:55:07.7583665+03:00"
}`

3. Εκτέλεσα την παραγγελία στέλνοντας
`{
  "OrderCode" : 5507758366572609,
  "SourceCode": 1414,
  "CreditCard" : {
     "Token": "aIhwc3yNL9TUWnw7Hc+axUB8FxELS0R+gBTtINf9ajO5ZIgZjct5zaVun0OBED7vdw2XihfTbdfY8GS1AAxavdXo5M4RENkZq8TGgROTiwNq5BOf5LCHaTrdfoNJrsY8Ae8DwLz3XNBhHyD3lDbxBWJriSOVyrBmSjKk4wO3dXWZ7jtj9LpFHr7+3s6MLn83lhQOa9Pxof5Owp4DtMKAUPB3LqwTa2UxvEs9GLaGX65r+tx8yDCBGRpeaVAHSfyvsE8HGKa6ugUfPFMXN5TKIqrXDwo5sYYRRF3opMBMyKcAih86z4znGHnGiuKRqHbwHNC/QMrcqrXn9/Nm7KLeb0wQVvoIGwjxeA29JsL7tQ0="
  }  
}`
στο http://demo.vivapayments.com/api/Transactions
και έλαβα:
`{
  "Emv": null,
  "Amount": 0.5,
  "StatusId": "F",
  "TransactionId": "7dd3c028-a503-435a-853e-e9e7d5c71a9a",
  "ReferenceNumber": 89349,
  "RemainingRefunds": 5,
  "AuthorizationId": "612132",
  "ErrorCode": 0,
  "ErrorText": null,
  "TimeStamp": "2016-07-04T18:55:34.6974211+03:00"
}`

Παρόλο που στο order είχα ορίσει `"AllowRecurring": "true"` στο TransactionId "7dd3c028-a503-435a-853e-e9e7d5c71a9a" δεν μπορώ να κάνω CreateRecurringTransaction. Αυτό φαίνεται και από το panel της viva που δεν δίνει το αντίστοιχο κουμπί.

Ερώτημα: Θα μπορούσε αυτή η πρώτη χρέωση να είναι τύπου pre-authorization, γιατί σε καμία περίπτωση δεν θέλω να χρεωθεί ο χρήστης νωρίτερα από ότι πρέπει.

**Comment by defilerc** [comment]
Καλημέρα @nikosmouroutis ,

Οι παραπάνω κλήσεις φαίνονται όλες σωστές. Για να μπορέσετε να κάνετε recurring πληρωμές, θα πρέπει απλά στο αρχικό transaction που γίνεται η χρέωση (βήμα 3 που αναφέρετε), να περάσετε επιπλέον και την παράμετρο **AllowsRecurring** == true (προσοχή: το όνομα της παραμέτρου είναι διαφορετικό από το **AllowRecurring** που περνάτε κατά τη δημιουργία του Order).

Αν μετά την παραπάνω αλλαγή, συνεχίζετε και έχετε πρόβλημα, παρακαλώ πολύ ενημερώστε μας για να μπορέσουμε να σας βοηθήσουμε περαιτέρω.

Ευχαριστούμε πολύ.

**Comment by themis1970** [comment]
τι ειναι ολα αυτα τα μηνηματα που μου στελνετε συνεχεια???????

www.koronis.com.gr
www.χονδρικη.gr
<http://www.%CF%87%CE%BF%CE%BD%CE%B4%CF%81%CE%B9%CE%BA%CE%B7.gr>
www.xondriki.eu
www.tzamia-tapetsaries.gr

email: koronis1970@gmail.com

ΕΜΠΟΡΙΟ ΕΙΣΑΓΩΓΗ ΚΑΤΑΣΚΕΥΗ
ΞΥΛΟΥ-ΑΛΟΥΜΙΝΙΟΥ.

ΘΕΜΙΣΤΟΚΛΗΣ ΚΟΡΩΝΗΣ
ΤΗΛ.-FAX 22210 22243
MOBILE: 6972699533
TK.34100
ΒΑΛΣΑΜΑ 4
ΧΑΛΚΙΔΑ

****************************************************************
Προσοχή ! Σύμφωνα με το άρθρο 14 του Νόμου 2672/1998 (ΦΕΚ 290 τ.Α)
τα μηνύματα e-mail, για να είναι έγκυρα θα πρέπει να περιέχουν απαραίτητα :
Ονοματεπώνυμο ή επωνυμία (για Νομικό πρόσωπο), ταχυδρομική διεύθυνση
κατοικίας, αριθμό τηλεφώνου ή fax, ιδιότητα του χειριστή.
Αν τα μηνύματα προέρχονται απο υπηρεσία ή Δημόσιο φορέα να περιέχουν
επιπλέον θέμα, ημερομηνία, αριθμό πρωτοκόλλου.
Το μήνυμα ηλεκτρονικού ταχυδρομείου τεκμαίρεται οτι έχει περιέλθει κανονικά
στον λήπτη αν υπάρξει ηλεκτρονική επιβεβαίωση.
 Οι πληροφορίες ή και τυχόν αρχεία που υπάρχουν σε αυτό το ηλεκτρονικό
μήνυμα είναι προσωπικά και απόρρητα
****************************************************************

Στις 5 Ιουλίου 2016 - 11:08 π.μ., ο χρήστης Kostas Athanasoglou <
notifications@github.com> έγραψε:

**Comment by nikosmouroutis** [comment]
Καλημέρα @defilerc,

Μόλις το τέσταρα και πράγματι δημιουργήθηκε transaction που επιτρέπει Recurring. Όταν όμως πάω να εκτελέσω Recurring μέσω του endpoint _/api/transactions/0e6c0733-6455-440c-8ef8-e4999a8e1fbb_ μου απαντά το εξής:

```
"ErrorCode": 403,
  "ErrorText": "The specified api action is disabled for the merchant 87c2019d-2584-4dd1-b3d5-a9b0e708ff18, please consult the documentation"
```

Όταν όμως δοκιμάζω να επαναχρεώσω μέσα από το UI της viva το κάνει με επιτυχία


@themis1970 μάλλον έχετε κάνει subscribe στο issue, μπορείτε να κάνετε unsubscribe [εδώ](https://github.com/VivaPayments/API/issues/138)

**Comment by defilerc** [comment]
Καλησπέρα @nikosmouroutis ,

Βεβαιωθείτε ότι από το διαχειριστικό του εμπόρου στο μενού "Ρυθμίσεις -> Πρόσβαση API" είναι enabled η επιλογή _Επιτρέπονται οι επαναλαμβανόμενες πληρωμές_ στην ενότητα **Ρυθμίσεις ασφαλείας API**.

Ευχαριστούμε

**Comment by nikosmouroutis** [comment]
@defilerc  Όντως δεν ήταν ενεργοποιημένο, το ενεργοποίησα και δουλεύει σωστά όλη η διαδικασία πλέον.

Ευχαριστώ πολύ για την εξυπηρέτηση.
