### ISSUE TITLE
After completing the checkout form in vivapayments.com, the customer is not redirected back to our e-shop

### ISSUE THREAD

**Issue by kanenas** [VivaPayments/API#1380]
**Opencart**: 1.5.6.4
**Integration method**: Redirection/Native Checkout v2

The issue is that the customer, after completing the checkout form in https://www.vivapayments.com/web/newtransaction.aspx?ref=xxxxxx, is not redirected back to our e-shop.

We have 2 Websites/Apps:
- Default (created by Viva and we have no control over it)
- e-Shop (created by us, we have set it up based on this https://developer.vivawallet.com/e-commerce-plugins/opencart1.5/)

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear you've been experiencing issues. I've raised this with our development team who should get back to you soon.

**Comment by kanenas** [comment]
I don't know what Viva has changed recently, but this worked for me.

**Solution**:
1. Disable the old **VivaPayments** extension. 
2. Download, install & configure https://github.com/VivaPayments/API/tree/master/Plugins/opencart/OpenCart%201.5
