### ISSUE TITLE
Orders Not Reaching Viva Wallet

### ISSUE THREAD

**Issue by PontyPrince** [VivaPayments/API#1381]
Hi,

We have had reports of customers not being redirected to the Viva Wallet even though we can see the orders as pending on our side. Would you be able to investigate an order if I provide details?

Thanks

**Comment by matthewrgourd** [comment]
Hi @PontyPrince sorry to hear this. Sure, please provide the details to me via email referencing this issue number (#1381). My email address is mgourd@vivawallet.com. If I could have your Merchant ID, business name and any other info you might be able to provide...

**Comment by matthewrgourd** [comment]
Hi @PontyPrince thanks for your email reply. You mentioned that you wanted to change the business logic of our Magento plugin. I'm afraid the current behaviour isn't about to change in the near future. Apologies for any inconvenience caused.
