### ISSUE TITLE
Viva Wallet and Pending Payments

### ISSUE THREAD

**Issue by p4resh** [VivaPayments/API#1383]
Hi about 4 weeks ago we integarted Viva Wallet Native Check out V2. We have set this up in such a way that customers are informed if there is an issue with there payment, either wrong card number entered, CV2 not match or declined payments. This reduced the number of pending payments we were receiving.

Yesturday suddenly we have a spike in pending payments, where noramlly we would receive 3 or 4 we had about 15 payments that stayed in pending.

We are looking to find out why this would happen and what else can be done to reduce this.

When a payment stays pending no notes are crreated in the customer profile. From what we are told by our customers, they are redirected to the Viva Wallet payment page it seems this does not load properly and stay grey, after a while customers abandon the sale and move to other sitesa, we not only loose the sale but the customer as well.

Please can any one help with this issue, is this something any one else is facing or faced and resolved

**Comment by matthewrgourd** [comment]
Hi @p4resh I'm sorry to hear about the problem you've faced with a sudden spike in pending payments. So that I can investigate, would you be able to send the following details to my email address (mgourd@vivawallet.com) referencing the issue number (#1383):

- business name
- Merchant ID
- web address of e-commerce site using Viva Wallet for payments

Thanks!

**Comment by p4resh** [comment]
HI Matthew
Sorry for the delay, is it possible to reopen the case. Here are the details you require


Merchant ID     d072de3c-819c-42a1-b968-47967614fa5f
Business Name: Havana House Ltd

www.havanahouse.co.uk<http://www.havanahouse.co.uk>


Please let me know if you require any further information


Paresh

________________________________

**Comment by matthewrgourd** [comment]
Hi @p4resh I've checked your account and although you do have quite a few failed transactions round that date there looks to be nothing out of the ordinary happening.

**Comment by p4resh** [comment]
Matthew

So can I assume that these pending transactions are due to customer input errors and there bank not authorising the transactions?

Thanks

Paresh

________________________________

**Comment by matthewrgourd** [comment]
Hi Paresh, you can, yet.
