### ISSUE TITLE
How initialize order code in any page refresh (Joomla -php)

### ISSUE THREAD

**Issue by christos99gr** [VivaPayments/API#1384]
Dears,

Could you please help me with an issue that I have? 
I use redirect checkout for selling some tickets for an event. Order can be completed without any problem, BUT after the first payment the order code did not change so nobody else can pay, unless I refresh the page in the administrator panel of the website.

Do you have any idea how the order's code can be refreshed using php?

Thanks a lot!

**Comment by matthewrgourd** [comment]
HI @christos99gr sorry to hear you're experiencing an issue with your ticketing website. So I can investigate further, please email me (mgourd@vivawallet.com) the below info. referencing this ticket number (#1384):

- business name
- website address
- merchant ID

**Comment by matthewrgourd** [comment]
No reply for almost a month so closing issue.
