### ISSUE TITLE
After completing the checkout form in vivapayments.com, the customer is not redirected back to our e-shop

### ISSUE THREAD

**Issue by kapamarou** [VivaPayments/API#1385]
The issue is that the customer, after completing the checkout form in  is not redirected back to our e-shop after successfull payment.  Ι have enable website apps and i have select Redirection/Native Checkout v2 i have complete the URL Επιτυχημένης συναλλαγής and URL Αποτυχημένης συναλλαγής. The app is enabled by you side what is going wrong ?

**Comment by kanenas** [comment]
Which version of Opencart are you using? See #1380

**Comment by matthewrgourd** [comment]
Hi @kapamarou sorry you're experiencing issues. Can I first of all ask which of our e-commerce plugins you're using or is it a custom integration?
