### ISSUE TITLE
Activate merchant id

### ISSUE THREAD

**Issue by Talagozis** [VivaPayments/API#1386]
I m trying to use the demo gateway of your service but I get the follow error:

The specified api action is disabled for the merchant  71afa****-****-****-****-********02d9 , please consult the documentation.

Could you activate my demo account?

**Comment by matthewrgourd** [comment]
Hi @Talagozis please let me have your full demo Merchant ID so I can check? The only one you shouldn't let us have publicly is the production Merchant ID.

**Comment by Talagozis** [comment]
Here it is the full demo one:
**71afa7ea-c845-40cf-8fb4-16f8734802d9**

**Comment by matthewrgourd** [comment]
Hi @Talagozis, thanks, can you try again now?
