### ISSUE TITLE
Installation - Wordpress plugin -Webhook issue

### ISSUE THREAD

**Issue by ntourziotis** [VivaPayments/API#1387]
Greetings team, 

I just installed Viva plugin for my wordpress site https://www.lifeup.gr

As i tried to add a new webhook into Viva wallet environemt an error appeared and dont let me finalize the procedure https://prnt.sc/r3ygj5 

Plugin configuration settings --> https://prnt.sc/r3ykip 
Payment source settings --> https://prnt.sc/r3yl6w , https://prnt.sc/r3ylro
Payment sources listing : https://www.lifeup.gr/index.php?wc-api=wc_vivawallet&vivawallet=webhook 

Could you please let me know where is the issue?

Best regards
Ioannis

**Comment by ntourziotis** [comment]
Friendly kind reminder

**Comment by matthewrgourd** [comment]
Hi @ntourziotis can you confirm you downloaded and installed using our [official guide](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/)? Some of the settings look unfamiliar.

**Comment by ntourziotis** [comment]
Hi Matthewgourd, 

I had downloaded wrong version of the plugin! I think now we are fine! 
How could i test it ? Is it something you can check first from your side? Or from my side to try "buy" something?

Best regards
Ioannis

**Comment by matthewrgourd** [comment]
Hi @ntourziotis you can test buying something on your live site then immediately make a refund from our banking app. Please close this issue if you feel it has been solved. Thanks!
