### ISSUE TITLE
Problem with VivaWallet connexion

### ISSUE THREAD

**Issue by julienbonnal** [VivaPayments/API#1389]
Bonjour.
Je suis le webmaster du site internet Le Temple de la Vape, qui est client chez vous.

J’ai installé tout précisément comme prévu sur votre site internet, j’ai également installé le module Prestashop avec les éléments (capture en pièce-jointe) API.

Seul problème : parfois les paiements ne passent pas, ou quand ils passent ils sont seulement pris en compte par Viva Wallet, mais rien dans le Prestashop comme le ferait un Stripe ou autre.

Pourriez-vous voir cela ?

Merci à vous.
Le capture en PJ.

Cordialement.
Julien.

**Comment by matthewrgourd** [comment]
Hi @julienbonnal, sorry to hear you've been experiencing issues with our Prestashop plugin. There could be a general problem but at the moment I'm not sure. Am in talks with our development team. I'll get back to you as soon as I've any updates.

**Comment by julienbonnal** [comment]
Hi
Ok thank you I wait to you for a feedback when the issue is fixe

Julien

—


Julien RICCIARELLI-BONNAL
BR Médias
www.brmedias.com

Tel.: (+33) 06.95.34.86.21
Fixe: (+33) 09.72.64.12.54
Suisse: +41 (0)225 192 944

**Comment by matthewrgourd** [comment]
in order for us to investigate further, could you send through the following screenshots:

- CS Cart payment module settings (mask the API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include the browser's URL bar in the screenshot).
- Viva Wallet Websites / Apps page (include the browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include the browser's URL bar in the screenshot).

Thanks.

**Comment by matthewrgourd** [comment]
Hi there, our development team has come back to me. They're still investigating the issue and need some further info. When you have a spare moment, could you answer the following, please?

1. What version of PrestaShop are you using?
2. PHP/ MySQL versions?
3. What kind of webserver do you have for hosting (is it Apache? is it Linux-based?)

**Comment by matthewrgourd** [comment]
Hi @julienbonnal, just to let you know that our development team has now completed a test installation of the plugin. The conclusion is that it is working correctly. Can you elaborate on the exact nature of the problem you're having or close this issue if solved? Thanks!

**Comment by matthewrgourd** [comment]
Closing issue as no reply for almost a week.
