### ISSUE TITLE
Native Checkout PreAuthorization

### ISSUE THREAD

**Issue by nikosmouroutis** [VivaPayments/API#139]
Καλησπέρα @defilerc ,

1. Δημιουργώ ένα Order στο endpoint /api/orders με `"IsPreAuth": "true"`
2. Το εκτελώ (αφού έχω δημιουργίσει και το ανάλογο token της κάρτας) στο endpoint /api/Transactions

Το πρόβλημα είναι ότι δεν γινεται preAuthorization αλλά κανονική χρέωση.
Είναι κάτι το οποίο παραλείπω;

(Τα calls που κάνω στο συγγεκριμένο project περιγράφονται αναλυτικότερα και στο issue [Δυνατότητα διατήρησης token κάρτας για επαναλαμβανόμενες χρεώσεις](https://github.com/VivaPayments/API/issues/138))

**Comment by defilerc** [comment]
Καλημέρα @nikosmouroutis ,

Όπως σωστά αναφέρετε, το μόνο που χρειάζεται για να γίνει capture και όχι actual χρέωση, είναι να δημιουργήσετε το order με `IsPreAuth: true`.

Αυτό θα μειώσει το λογιστικό (και όχι το διαθέσιμο) υπόλοιπο του πελάτη για όσο διάστημα διαρκεί το capture (η δέσμευση του ποσού).

Ευχαριστούμε πολύ.

**Comment by nikosmouroutis** [comment]
Καλημέρα @defilerc 

Παρόλο που όταν δημιουργώ το order ορίζω  `"IsPreAuth": "true"` γίνεται κανονική χρέωση.

**Comment by defilerc** [comment]
Καλησπέρα @nikosmouroutis ,

Αν συνεχίζετε και έχετε πρόβλημα, παρακαλώ πολύ στείλτε ένα email στο merchants@vivawallet.com μαζί με τα εξής στοιχεία:

- Merchant ID του λογαριασμού σας
- Transaction ID, για το οποίο έχετε πρόβλημα
- GitHub Reference Issue

ώστε να μπορέσουμε να δούμε πιο διεξοδικά τι έχει συμβεί.

Ευχαριστούμε πολύ.
