### ISSUE TITLE
How to set static dhcp address

### ISSUE THREAD

**Issue by SIKLAIT** [VivaPayments/API#1390]
Hello, we have a Viva Wallet POS A80.
I have a static network on my business and i have to set through the POS static dhcp address like e.g. 192.168.1.2.

The problem is I cannot find any option to set it. Any help would be much appreciated. Thank you.

**Comment by matthewrgourd** [comment]
Hi @SIKLAIT our POS A80 definitely supports the use of static IPs. However, the required parameters need to be pushed out at network level rather than via the terminal hardware.
