### ISSUE TITLE
Sumo Reward Points Plugin not working with Vivawallet 

### ISSUE THREAD

**Issue by magmaorganicfoodslimited** [VivaPayments/API#1391]
Hi,
We have vivawallet installed for our website www.britishcbd.net Everything has been working fine for over a year but recently we added Sumo Rewards Points and that is not working with vivawallet. 
So when customers try to redeem their points it does not deduct it from the total and charges them full amount. 
If this plugin is not compatible please can you recommend one that is or give us a solution for this issue.
Kind regards
Saifi Mir
.

**Comment by matthewrgourd** [comment]
Hi there I think you need to update the plugin as it's still showing our old logo which means it's either an old version or one provided by an unofficial supplier. Please visit our Viva Wallet for WooCommerce [guide](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) to download and install the latest plugin. As regards your query regarding deducting reward points, I'm not sure if our plugin is compatible but I'll check and get back to you.

**Comment by magmaorganicfoodslimited** [comment]
Hi Matthew,
I will update the new viva wallet plugin and if you can let me know any
reward points plugin that are compatible with your viva wallet plugin.
Kind regards
Saifi Mir

**Comment by magmaorganicfoodslimited** [comment]
Hi Matthew,
Before you close can you let me know any reward plugins that are compatible
with vivawalet.
Kind regards
Saifi Mir

**Comment by matthewrgourd** [comment]
Hi @magmaorganicfoodslimited there are no off-the-shelf plugins directly compatible but you can deduct it programmatically through a custom solution using our [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api) to set the appropriate [Create payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post) amount.

**Comment by magmaorganicfoodslimited** [comment]
Hi Matthew,
We still have not been able to create a loyalty scheme with the Payment API
you sent.
Can we pay you to do this for us?
Kind regards
Taqi Mir

**Comment by magmaorganicfoodslimited** [comment]
Hi Matthew,
Can you confirm if we can setup a subscription system on viva wallet?
Kind regards
Saifi Mir
