### ISSUE TITLE
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by dolaptsispanos** [VivaPayments/API#1392]
Καλησπέρα,

Εδώ και λίγες ημέρες το παράδειγμα σας https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php
έχει σταματήσει να λειτουργεί και δεν δίνει orderid. Εμείς που δεν δουλεύουμε σε περιβάλλον όπως joomla, wordpress κλπ. και ζητάμε ένα λειτουργικό παράδειγμα με PHP για το Create Order ζητάμε να απαντήσει κάποιος υπεύθυνα ποια είναι η λύση και να δώσει ένα παράδειγμα κατανοητό. 

το curl_error($session); μου δίνει το παρακάτω error

error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Μπορείτε να μου πείτε τι πρέπει να κάνω και γιατί ενώ όλα λειτουργούσαν κανονικά ξαφνικά έχω αυτό το error;

Περιμένω μια υπεύθυνη απάντηση ευχαριστώ.

**Comment by dolaptsispanos** [comment]
Χάνουμε πωλήσεις καθημερινά... υπάρχει κάποιο νέο σχετικά με το πρόβλημα αυτό;

**Comment by matthewrgourd** [comment]
Hi @dolaptsispanos sorry for the issue you've been having. At the moment our GitHub code samples are in need of updating so we can't guarantee whether they'll work or not. We are taking on new staff in our dev team so this should change soon. In the meantime, please refer to the [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/) section of our developer portal. I've included a fully tested cURL sample there to create a payment order:
```
curl -X POST https://demo.vivapayments.com/api/orders -H 'Authorization: Basic ZmJmMWUwOTAtNjVkZS00Yzc1LWI1ODAtZDlkOWJjNDk0YWQyOldEdi1WKw==' -H 'Content-Type: application/json' -d '{
      "Tags": [
          "tag 1",
          "tag 2",
          "tag 3"
      ],
      "Email": "customer@domain.com",
      "Phone": "2117604000",
      "FullName": "Customer Name",
      "PaymentTimeOut": 86400,
      "RequestLang": "en-US",
      "MaxInstallments": 12,
      "AllowRecurring": true,
      "IsPreAuth": true,
      "Amount": 1000,
      "MerchantTrns": "Your reference",
      "CustomerTrns": "Description that the customer sees"
  }'
```
If you want to test making a payment by opening the below URL and replacing {orderCode} with the result of the above, the card number to use is 4016000000040000012.

`https://demo.vivapayments.com/web/checkout?ref={OrderCode}`

Hope this helps!
