### ISSUE TITLE
Default language wordpress payment

### ISSUE THREAD

**Issue by safwen1** [VivaPayments/API#1393]
Our client is asking how to make the default language in the checkout payment page by default French instead of English:
![WhatsApp Image 2020-02-19 at 14 05 04](https://user-images.githubusercontent.com/13918596/74840362-25217100-5327-11ea-93dc-2768d9fb6b39.jpeg)

**Comment by matthewrgourd** [comment]
Hi @safwen1 I think it's simply the country of origin of your account. So if you registered in the UK by default it will automatically be set to EN. However, I will double-check and get back to you!

**Comment by matthewrgourd** [comment]
Hi @safwen1 you can set this via a parameter within our [Create payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post) API call. The parameter is called `requestLang`.

**Comment by safwen1** [comment]
@matthewrgourd thank you for responding, but we are using the wordpress plugin not a manual integration.

**Comment by matthewrgourd** [comment]
@safwen1 you can make the changes to the WooCommerce plugin yourself by editing the code (wc-vivawallet.php). Specifically this section:

ORIGINAL
`$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300';`

NEW (add **`&RequestLang=fr`**)
`$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang=fr'.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300';`

**Comment by WeedyTech** [comment]
I have the same problem and I have tried your solution, but with your code, the default langage is GREEK.. And we want French langage too for the viva wallet confirmation email too if possible
