### ISSUE TITLE
Viva Wallet causing ALL options to disapear from checkout

### ISSUE THREAD

**Issue by Allthejam** [VivaPayments/API#1395]
Help 

We are a customer of Viva wallet and we have been building a website using Prestashop up until a few days ago it was all working perfectly with Viva as the 1st choice and main payment option.

This is no longer the case as your Module is no longer working, basically, after 2 days of back and forth with Prestashop support we have got all the other payment options working but when we enable Viva all out options disappear from our checkout area so NO payment can be made, the only option is to disable or uninstall Viva and then all other options come back on, we need s developer or some technical support for this module to find out what’s gone wrong, in the interim we are having to look at other options but this is not desirable to us either.

**Comment by matthewrgourd** [comment]
Hi @Allthejam, sorry to hear you've been experiencing issues with our Prestashop plugin. There could be a general problem but at the moment I'm not 100% sure. Am in talks with our development team. I'll get back to you as soon as I've any updates.

**Comment by Allthejam** [comment]
Ok, Thank you for letting me know,

**Comment by matthewrgourd** [comment]
Hi @Allthejam, in order for us to investigate further, could you send through the following screenshots:

- PrestaShop payment module settings (mask the API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include the browser's URL bar in the screenshot).
- Viva Wallet Websites / Apps page (include the browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include the browser's URL bar in the screenshot).

Thanks.

**Comment by Allthejam** [comment]
I'm sorry but you'll have to elaborate a little I think this is what your after, see attached.

I'm not 100% sure or happy sending this type of info over this network.

Allthejam
[New Rich Text Document.docx](https://github.com/VivaPayments/API/files/4245863/New.Rich.Text.Document.docx)

**Comment by matthewrgourd** [comment]
Hi @Allthejam thank you for those screenshots. I've checked your account and the problem is the payment source you wish to use for Prestashop isn't active yet. gary@blu-pharma.com should have received an email with instructions about what is needed to get it out of pending status. Let me know if not...

**Comment by Allthejam** [comment]
That's not the problem, 

The issue is in the Module itself, when the module is enabled all the payment options on the website disappear leaving no way to pay, and when I disable the Viva Module I get all the other payment options back, like Bank transfer, Bitcoin & pay by check.

So you see its a module issue that's causing the entire site to not be ably to take any card payments and all I can do it disable the module or uninstall it and use another banking option.

Allthejam

**Comment by matthewrgourd** [comment]
Ah, I see. Well I've flagged with one of our developers to fully test out the Viva Wallet plugin for PrestaShop plugin but I'm not sure when that will be. As I've only received one other query alluding to the same problem it may well be a problem with your PrestaShop setup. Anyway, sorry not to be of more immediate help.

**Comment by Allthejam** [comment]
Thank you, just to let you know then, I have had the Prestashop people look into this from there end and everything is working properly right up to the point this module is enabled, they have said that this is a Viva issue and they can do nothing more to assist, I have installed this into some other test sites and used the same details for banking and the result is the same, All other till disappear.

It was all working a few weeks ago and we have had this installed now for a few months without any issues until now.

Just thought you should know.

Allthejam

**Comment by matthewrgourd** [comment]
Hi @Allthejam , our development team has come back to me. They're investigating the issue and need some further info. When you have a spare moment, would you mind answering the following if at all possible?

1. PrestaShop version?
1. What version of PHP / MySQL are you using?
2. What kind of webserver do you use for hosting (is it Apache? Linux-based?) 

You may also be interested to see the following [issue](https://www.prestashop.com/forums/topic/960231-exception-you-are-not-allowed-to-disable-the-module/) that was raised on the PrestaShop forum. This is just FYI as I think the problem may well be at our end. Please bear with us!

**Comment by Allthejam** [comment]
See below, for the info you required, as for the additional issue you mentioned, I don't have any problems in installing any modules, this module was installed months ago and had worked perfectly up until about 2 weeks ago when it started to cause everything to go off. I have got to get another temporary checkout installed now asap as this is taking far too long to resolve.

Presta version 1.7.5.2
PHP version 7.2
Web server
nginx/1.14.0
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 7.2.24-0ubuntu0.18.04.3

Allthejam

**Comment by matthewrgourd** [comment]
Hi @Allthejam thank you. I've passed on to our development team who are looking into the problem.

**Comment by matthewrgourd** [comment]
Hi @Allthejam , just to let you know that our development team has now completed a test installation of the plugin. The conclusion is that it is working correctly. The problem therefore must be within your PrestaShop e-commerce settings which do tend to be quite tricky to sort out. If you cannot find the Viva Wallet module the modules collection page, it's displayed under 'Other' not under 'Payments'. I wish you luck finding a solution but I'm afraid I can't help any further. Thanks!

**Comment by Allthejam** [comment]
Hi, I'm a little confused, not with the module I know exactly where that is but more the development teams findings, Like I said it worked perfectly right up until it threw a fit and decided that it didn't and not only that but it took out all the other payment options as well. When I remove viva everything else comes back on and works as they should, even the team from Presta themselves have had a go and concluded that its the Viva module that's the problem, so, I'm not exactly sure what to do, I'm not a developer nor do I work for Presta, so, I have to put it back to you guys to have another look and I suggest see what it's clashing with although in saying that even when everything else was uninstalled it still did not work. If you cant help any further then we will have no choice but to move our banking elsewhere for the launch and remaining business ventures, I hope you understand this. Please ask again if they have any real suggestions or solutions,  there's definitely something wrong.

Thank you

**Comment by matthewrgourd** [comment]
Hi @Allthejam sorry about that, I will feed back to my colleagues what you've said in case they can help further.

**Comment by Allthejam** [comment]
Thank you.

Allthejam

**Comment by Allthejam** [comment]
Can I reopen this conversation with a new issue?

My issue is this, I have since got Vive wallet to work however it does NOT sync with my back office, after customers making payments and yes money went into my Viva wallet, the transactions did not show up in my back office making it very difficult to get the appropriate address and details not to mention the customer did not get any emails sent out or any recent purchases in his customer login area. Any ideas or is this as good as the module gets?

Thank you

Allthejam...
