### ISSUE TITLE
Apple/Google Pay

### ISSUE THREAD

**Issue by alextovey** [VivaPayments/API#1396]
Hi, All.

How can we implement apple and google play with the plugin for woocommerce please? it states on the website that you allow it however I cannot find any option in out backend of on the settings for woocommerce to allow these.

**Comment by matthewrgourd** [comment]
Hi there, we accept Apple/Google Pay through some of our [card terminals](https://help.vivawallet.com/hc/en-us/articles/360001362538-Can-%CE%99-accept-contactless-transactions-with-Viva-Wallet-POS-terminals-) but not e-commerce currently. Thanks!

**Comment by alextovey** [comment]
Is it possible to to manually add this in ourselves using the apple pay/google pay php coding?

**Comment by iMonZ** [comment]
Is it possible to add Apple Pay?

**Comment by matthewrgourd** [comment]
Hi @alextovey @iMonZ, I would advise against this as it's quite complicated. Anyway, we are working on implementing Apple Pay in the next release of the WooCommerce plugin. Watch this space!
