### ISSUE TITLE
Critical error in the payment page

### ISSUE THREAD

**Issue by andreatosi89** [VivaPayments/API#1397]
Hello, I've just followed the steps to install and configure the plugin in wp-woocommerce.
The procedure seems to be done successfully but If I try to complete the order I get the following error:

![image](https://user-images.githubusercontent.com/43884956/75025513-a13cc580-549b-11ea-95d3-3486a46ee278.png)

Is that happening because the website still has status "pending"?
I can't try in the test environment beacuse of another issue (I have written in another thread for that).

P.S. The css doesn't seem to work correctly. Can you confirm it?

**Comment by matthewrgourd** [comment]
Hi @andreatosi89 this looks like an issue more at the WooCommerce end. P'raps wait until we get to the bottom of your other issue before looking at this one.

**Comment by andreatosi89** [comment]
Hey @matthewrgourd, I really don't know what happened but now it works.
This morning I tried a lot of times, I even tried waiting for a while thinking that some procedures were still running.
So I can say that one can be closed. I'm sorry for wasting your time.

**Comment by matthewrgourd** [comment]
@andreatosi89 good to hear! Thanks, am closing the issue now.
