### ISSUE TITLE
Test environment: 404 - File or directory not found. 

### ISSUE THREAD

**Issue by andreatosi89** [VivaPayments/API#1398]
Hello, I've just followed the steps to install and configure the plugin in wp-woocommerce.
The procedure seems to be done successfully but, If I enable the test environment and try to complete the order, I get the following error:

![demo vivapayments_404-IIS](https://user-images.githubusercontent.com/43884956/75026283-004f0a00-549d-11ea-9c07-159e8d96f5b1.png)

Thank you.

**Comment by matthewrgourd** [comment]
Hi @andreatosi89 that's strange, could you let me know exactly what steps you took to test completion of an order, with more screenshots if possible?

**Comment by andreatosi89** [comment]
Of course, I've downloaded and installed your official plugin found in the below link:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

I followed your installation and configuration guide.
I don't know if this can help you, but this is my configuration page in WP

![image](https://user-images.githubusercontent.com/43884956/75053590-d95efb00-54d1-11ea-999d-672e1e110c5c.png)

Now I'm not in test mode as you can see, but I tried 5 minutes ago to enabled it and it didn't work. Maybe I missed a parameter.
I've noticed that before the plugin redirects me in the 404 page, it has the following URL:

<my_domain>/checkout/?key=wc_order_0FvwQQdFewAi2&order-pay=1203

Thank you

**Comment by matthewrgourd** [comment]
Hi @andreatosi89 please try without 'Enable test mode' selected.

**Comment by andreatosi89** [comment]
Hi @matthewrgourd, just tried but it doesn't work yet. I got the same error.

**Comment by matthewrgourd** [comment]
Hi @andreatosi89, in order for us to investigate further, could you send through the following additional screenshots:

- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet Websites / Apps page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Also, please may I have your demo merchant ID?

Thanks!

**Comment by unclemuzy** [comment]
Experiencing this same issue just now.

**Comment by andreatosi89** [comment]
@matthewrgourd before giving you the screenshots I have a quick question: 
In order to use the demo environment is the registration at https://demo.vivapayments.com/it/signup required?
Because I've noticed I can't access using my "real" credentials.
Could this cause the issue?

**Comment by matthewrgourd** [comment]
Hi @andreatosi89, yes, you need to register at the demo site if you wish to test within the demo environment with a 'pretend' Merchant ID and API key.

**Comment by andreatosi89** [comment]
Ok @matthewrgourd , I think we found the problem.
Let me try in the next hours and I'll let you know. It's my fault, I didn't read any guide to test the environment and I thought it was enough to check the flag in the configurations of WordPress.
So, basically I'm try to access to the demo env using my real IDs... That's good! :-)
