### ISSUE TITLE
E-shop payment by installments

### ISSUE THREAD

**Issue by savlos** [VivaPayments/API#1399]
Hello,

We have an eshop (cozykids.gr), which is using VivaWallet for receiving card payments.

We would like to add interest-free installments option at our check-out process.

Last time I've checked this was not feasible yet.

Do you know whether this will change and when?

Regards,
Pavlos Papadimitriou

**Comment by matthewrgourd** [comment]
Hi @savlos, if you're referring to our Shopify plugin, no, I'm afraid installments aren't available yet as an option. Not sure if / when in the future this will change.
