### ISSUE TITLE
Woocommerce - Issue -1 after checkout page

### ISSUE THREAD

**Issue by thanosmil** [VivaPayments/API#1401]
Hello,

I am having an issue with the payment solution via woocommerce and your plugin.

Uploaded the plugin, configured it and it seems to work (i've made a small purchase on my website, chosen viva wallet as payment method, redirected me to viva dashboard, entered card details and i can see the payment received on my vivawallet dashboard)

Issue 👎 
After filling card details on the secured by visa page and clicking pay, it directed me to a page in our domain  index.php?wc-api=wc_vivawallet&vivawallet=succes&t=beeb29b5-2fd8-4cbc-a926-b113ae0e1562&s=3774025323872602&lang=en-US&eventId=0&eci=3

The page rendered was a blank one with a -1 on top left corner. 

Is it a problem of a webhook? Redirection or similar ?

Wordpress Woocommerce dashboard states the payment is is pending mode (but viva wallet has mark it as completed).

Thanks

**Comment by thanosmil** [comment]
I am using the official viva wallet plugin, downloaded from the link you provided in the support section

**Comment by matthewrgourd** [comment]
Hi @thanosmil sorry to hear you're experiencing an issue. I can see an immediate issue with 

index.php?wc-api=wc_vivawallet&vivawallet=**succes**&t=beeb29b5-2fd8-4cbc-a926-b113ae0e1562&s=3774025323872602&lang=en-US&eventId=0&eci=3

should be (there was a typo)

index.php?wc-api=wc_vivawallet&vivawallet=**success**&t=beeb29b5-2fd8-4cbc-a926-b113ae0e1562&s=3774025323872602&lang=en-US&eventId=0&eci=3

If that hasn't fixed anything, please email me at mgourd@vivawallet.com with the below details:

- business name
- Merchant ID
- reference to this issue #1401

**Comment by matthewrgourd** [comment]
HI @thanosmil, I've spoken with our dev team and apparently the WooCommerce plugin is 100% working correctly. In order for me to investigate further what your issue might be, please send through the following screenshots:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Closing issue as no reply for almost a month...
