### ISSUE TITLE
Merchant declining customer payments/failed transactions

### ISSUE THREAD

**Issue by radito123** [VivaPayments/API#1402]
I spoke to viva wallet "tech support" who advised that the issue would be with customer bank and not them. This is not the case. I have two customers who have called their different banks and it shows on the bank system that the transaction was approved and the merchant has declined to process the payment. 

I have been with yourselves now for almost a year and have not had any issue like this which has been regularly cancelling payments. I have been advised to open a ticket or my issue will not get dealt with. I am not doing this. 

I have about 8 transactions now over the last 36 hours that have declined and customers cannot make payment via viva wallet. Their banks have approved the transaction and viva are not processing. There is an issue here as it is obviously costing me business. I need it sorted ASAP. 
I have updated all wordpress, themes and woocommerce which is what we use. This has not rectified the issue. I see from this forum that I am not the only one having an issue. 
imuscle.co.uk is my website. Please let me know if you need any other info in order to resolve.

**Comment by benjumanji** [comment]
Hi, I work with @radito123 on his ecommerce site. We use the redirection checkout. We redirect with no problems at all, orders are being created without issues and customers land on the checkout page without difficulty. When being redirected back to our site after a failed transactions I note that we are being redirected back with `eventId=0` which as far as I can tell from [your rejection reasons](https://developer.vivawallet.com/api-reference-guide/error-codes/#rejection-reasons) means that the transaction was approved, yet somehow we are not getting paid. We can provided some order numbers in private if you need those for trouble shooting.

**Comment by matthewrgourd** [comment]
Hi @radito123 @benjumanji thanks for raising and sorry for the problems you've been facing. We will certainly investigate further for you. Please can you email me the Merchant ID and a couple of failed transaction IDs (or date when you had some of these) and I will forward to our dev team. My email address is mgourd@vivawallet.com Thanks!

**Comment by matthewrgourd** [comment]
Hi @radito123 I gather that some changes have been made to your account so that perhaps this issue has been fixed?

**Comment by matthewrgourd** [comment]
@radito123 @benjumanji I just tried a new purchase and am still getting transaction failed. We will investigate further...

**Comment by radito123** [comment]
Yes.  The limit had to be increased but they told me only this morning this
after I was chasing more.
I start receiving people's money, however I got some unpaid orders and I
have emailed the customers to find out if they have just abounded the
payment page or they had transaction fail. When I receive there reply I
will then update you.
Either close the case or let you know that they have had failed transaction.

Thank you
Radi

**Comment by matthewrgourd** [comment]
I believe that should have fixed things. I've looked at your account and can see a number of successful transactions. Closing this issue now but you can always reopen if you believe there to be still a problem. Thanks!
