### ISSUE TITLE
Cannot create order after authentication

### ISSUE THREAD

**Issue by alfasoftpt** [VivaPayments/API#1403]
Good morning.

We are trying to create a few orders to integrate with our billing platform, and we are getting an error which we are not able to decypher. I guess we are doing something wrong, but since the response from the API is not totally clear, we haven't spotted what we are missing.

We have a sandbox account, and we are using Oauth2 and requesting a token. So far so good, we can get a token (screenshots below):

![5a962f9e](https://user-images.githubusercontent.com/38887326/75139092-b441d680-56e3-11ea-8a18-2869739970bd.png)

This was done based on your documentation, and as you can see from the screenshot, we get an access token.

Next step was to try and create an order. Once again, we got a sample from the API documentation, added the bearer token as a header and submitted the request. This time, instead of a 200 response, we get a 401 unauthorized response.

What are we missing here?

![ff938f54](https://user-images.githubusercontent.com/38887326/75139114-c1f75c00-56e3-11ea-8b42-327e6c9194f5.png)

Here is the Authorization tab from Postman:

![7585156a](https://user-images.githubusercontent.com/38887326/75139231-03880700-56e4-11ea-8684-d660e5402a3e.png)

What are we missing or doing wrong here?

**Comment by matthewrgourd** [comment]
Hi @alfasoftpt apologies for any confusion but our Payment API uses basic auth. So creating a payment order involves putting your [MerchantID and API key](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) in place as the username and password under 'Authorization' (with Basic Auth seleted from the drop-down):

![Screenshot 2020-02-24 at 12 26 36](https://user-images.githubusercontent.com/44943019/75152452-f3caeb80-5700-11ea-9193-cfcdd1ab146c.png)
