### ISSUE TITLE
Have a Wix Website and need to get Viva Wallet Pay button on the site

### ISSUE THREAD

**Issue by DynamiteTom** [VivaPayments/API#1404]
I'm using JavaScript and not C# and need a way to integrate the Viva Wallet onto my Website 
An example would be appreciated - 
Email is dynaphoneimages@hotmail.com

**Comment by matthewrgourd** [comment]
Hi @DynamiteTom for custom integrations, the documentation we've made available at https://developer.vivawallet.com/online-checkouts/redirect-checkout/, https://developer.vivawallet.com/online-checkouts/native-checkout-v2/ and https://developer.vivawallet.com/api-reference-guide/payment-api/ is the extent of what's on offer at present. Unfortunately, I also need to point out that we don't currently have a Viva Wallet plugin available for Wix. Thanks, and sorry not to be of more help!

**Comment by matthewrgourd** [comment]
Hi @DynamiteTom you may also wish to look at our [Simple Checkout information](https://developer.vivawallet.com/online-checkouts/simple-checkout/) as this relates to adding a button to your website.

**Comment by DynamiteTom** [comment]
Hi I know how to add a button to website
thats easy but I want to incorporate the Viva Wallet with its https etc. onto website using javascript

Gordon

________________________________
