### ISSUE TITLE
New Website / App status still "Pending" after 4 days

### ISSUE THREAD

**Issue by unclemuzy** [VivaPayments/API#1405]
First time trying to integrate the VivaWallet payment gateway / wordpress plugin for a new ecommerce site and having some problems.

I am following the documentation found at https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ however the newly created Website/App is still marked as Status "Pending" after 4 days 

Any sugegstions as to what I am overlooking / doing wrong?

**Comment by matthewrgourd** [comment]
Hi @sab1709, thanks for raising this. Regarding your new payment source still being in pending, you should have received an email from us with some instructions. Have you checked your spam? If you can't find this please email me at mgourd@vivawallet.com with your Merchants ID / business name and I'll check your account.

**Comment by sab1709** [comment]
Hi @matthewrgourd, thanks for the reply, I'd emailed you.

**Comment by matthewrgourd** [comment]
Hi @unclemuzy I gather you've received the email now. Our accounts team will get back to you today, hopefully. If not, please email support@vivawallet.com. Thanks! I'm closing this issue now...

**Comment by unclemuzy** [comment]
I'm a little lost here, am I to take it that an email has been sent / one
of my colleagues has replied to it??

Kind Regards,


*E:* stefan@emither.me
*T:* +44 (0)7798 685 903
*In:* /in/stefanbailey <https://www.linkedin.com/in/stefanbailey/>

**Comment by matthewrgourd** [comment]
@unclemuzy as far as I'm aware, whoever set up the account has received and replied to an email from us sent to the registered email address. Is it yourself that set up the account or someone else?

**Comment by matthewrgourd** [comment]
@unclemuzy by way of assistance, the message mentioned that before we can make the payment source active, you need to add [to your website] contact details of the company and other relevant information, such as VAT Identification Number, Email Address, Contact Number and Address of the Head Office.

**Comment by unclemuzy** [comment]
Thanks Matt,

Nathan, who set the account up, says that he hasn't received any such email
this morning. So I am very confused as to where the email may have gone,
and who might have replied.

Kind Regards,


*E:* stefan@emither.me
*T:* +44 (0)7798 685 903
*In:* /in/stefanbailey <https://www.linkedin.com/in/stefanbailey/>

**Comment by matthewrgourd** [comment]
@unclemuzy, it would have been sent to bowmanliquids@hotmail.com. Do you know who has access to that email address?

**Comment by unclemuzy** [comment]
Yep that would be the same Nathan that's telling me that he's not had any
emails apart from one that he missed in Jan.

Kind Regards,


*E:* stefan@emither.me
*T:* +44 (0)7798 685 903
*In:* /in/stefanbailey <https://www.linkedin.com/in/stefanbailey/>

**Comment by matthewrgourd** [comment]
Ok, I will get them to resend. Or could it have gone in spam? Can you check this also?

**Comment by unclemuzy** [comment]
Thanks, I've shared the conversation with him and asked him to double
check.

Kind Regards,


*E:* stefan@emither.me
*T:* +44 (0)7798 685 903
*In:* /in/stefanbailey <https://www.linkedin.com/in/stefanbailey/>

**Comment by matthewrgourd** [comment]
Hi @unclemuzy I'm told the payment source is now live. Thanks.

**Comment by unclemuzy** [comment]
thank you

**Comment by unclemuzy** [comment]
Hi Matt,

I've just placed a test transaction through and it's taken me to the
following URL https://demo.vivapayments.com/web/newtransaction.aspx?Ref= and
presented a 404

Any ideas?

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. So I can investigate further, please send through the following screenshots if you can:

- WooCommerce payment module settings (mask your API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by unclemuzy** [comment]
As requested
[image: image.png]
[image: image.png]
[image: image.png]

**Comment by matthewrgourd** [comment]
Hi @unclemuzy those screenshots aren't coming through. Can you try again?

**Comment by unclemuzy** [comment]
![image](https://user-images.githubusercontent.com/39371225/75253088-cac85a80-57d5-11ea-9735-a7b0c8cba817.png)
![image2](https://user-images.githubusercontent.com/39371225/75253118-d87de000-57d5-11ea-8bbb-72312bcfefc7.png)
![image3](https://user-images.githubusercontent.com/39371225/75253125-db78d080-57d5-11ea-990e-231c2b1a230d.png)

**Comment by matthewrgourd** [comment]
Hi @unclemuzy can you try again, but with test mode deselected?

**Comment by unclemuzy** [comment]
it works ourtside of test-mode, however I am looking to be able to test the
payment gateway, make example transactions and test things like order and
transaction emails / refunds and so on, and I do not want to have to use a
live credit / debit card and incur charges / costs during this process.

**Comment by matthewrgourd** [comment]
Hello again, I believe when using test mode you need to use the demo credentials (Merchant ID and API Key) available from here: https://demo.vivapayments.com/selfcare/en/security/apiaccess rather than the production credentials available from the equivalent page on live. If you've not set up your demo account yet, please sign up here: https://demo.vivapayments.com/

**Comment by unclemuzy** [comment]
Good morning Matthew,

Sorry to reopen this ticket but I noticed that the Website/Api has gone
back to being "Pending" after I migrated the website to the live domain and
updated the settings in your control panel. I appreciate this will need a
review, but I would be grateful if you could keep an eye on it /
expedite this for me as I am dreading it taking 4+ days again to resolve..

Thanks in advance,

Kind Regards,


*E:* stefan@emither.me
*T:* +44 (0)7798 685 903
*In:* /in/stefanbailey <https://www.linkedin.com/in/stefanbailey/>

**Comment by matthewrgourd** [comment]
Hi Stefan, sorry to hear – not sure why that is. Am checking now...

**Comment by unclemuzy** [comment]
Hi Matthew,

Can we please get an update or ETA on this issue as this is a live /
customer facing domain and I need to plan accordingly.

Thanks

**Comment by matthewrgourd** [comment]
Hi @unclemuzy, sorry for the delay. I received a reply back from my colleague as below:

> the website is inaccessible for the moment. We have send an email with all the required elements to be integrated in the URL.

Did you receive the email?

**Comment by unclemuzy** [comment]
I've just called my colleague Nathan and asked him to check the registered email account, in the mean time is there any chance you will be able to forward it to me directly in case he's unable to access his work computer remotely?

**Comment by unclemuzy** [comment]
The only email received by my colleague today has been one that says the domain is approved and you're now able to send transactions through this source. 

![image](https://user-images.githubusercontent.com/39371225/77185682-b40dde80-6ac9-11ea-9f48-9f4123763e35.png)

**Comment by unclemuzy** [comment]
Obviously this isnt requesting any additional information, and contradicts the current status of "Pending" ?

**Comment by matthewrgourd** [comment]
Hi @unclemuzy, sorry for any confusion. Will update you in a minute.

**Comment by matthewrgourd** [comment]
Hi @unclemuzy, another email has been sent just now requesting that Viva Wallet is added (to the website) as a payment solution. After that we can make the payment source active.

**Comment by unclemuzy** [comment]
Can you please copy that to me directly as I'm not sure if I will be able to get that from my colleague now (given the time) and obviously I want to resolve this matter as quickly as possible.

**Comment by matthewrgourd** [comment]
Hi @unclemuzy I'm sorry it generally has to be the account holder that receives the emails. But if you can make the necessary changes and email support@vivawallet.com quoting the Merchant ID and other details specific to the company I'm sure it can be done. Thanks!

**Comment by unclemuzy** [comment]
> Hi @unclemuzy I'm sorry it generally has to be the account holder that receives the emails. But if you can make the necessary changes and email [support@vivawallet.com](mailto:support@vivawallet.com) quoting the Merchant ID and other details specific to the company I'm sure it can be done. Thanks!

I managed to obtain the email from Nathan and I have updated the footer logos to include the VivaWallet logo as requested.

**Comment by unclemuzy** [comment]
Please can someone action this and respond? This is a customer facing
domain now, and I am very disappointed that the reason it's being held up
is over a logo that wasnt requested or advised as being required when the
site was hosted on a staging domain when this would not have been an issue.

I understand it is now the weekend, but I would appreciate a response
please.

Kind Regards,


*T:* +44 (0)7798 685 903

**Comment by matthewrgourd** [comment]
Hi @unclemuzy I'm sorry there still seems to be some outstanding information our accounts team needs from the person at the registered email address:

> Before we can process the approval of the site, you will need to integrate the following:
>  
> 1) The Terms of Use that need be accepted by the consumer during the distant transaction. You should consult your legal services dept. regarding this.
> 2) The contact details of the company and other relevant information, such as VAT Identification Number, Email Address, Contact Number and Address of the Head Office.
>  
> Once you have actioned the above, please respond to this email via support@vivawallet.com to inform us you have done so. We will then be able to proceed to all necessary further steps.

**Comment by unclemuzy** [comment]
Hi Matthew,

The information is already displayed on the website clearly and
unambiguously

The Company Reg and VAT Number are displayed on the Contact page here:
http://crystalclearvapestore.co.uk/contact/

and the full T&C are found via the link in the footer, and during the
customer checkout procedure, which can be found here:
http://crystalclearvapestore.co.uk/terms-and-conditions/

- Regards

**Comment by unclemuzy** [comment]
Also the SSL has now been issued and installed, and I have updated the
settings in the Website/API configuration also.

Please can you review and advise if this is now sufficient for you to place
the integration Live

**Comment by matthewrgourd** [comment]
Hi @unclemuzy, I've chased again. I'm so sorry for the continued delay.

**Comment by unclemuzy** [comment]
Thank you. I was actually just about to email again as I have had no
response to the emails I have sent to support@
In fact, I was on the verge of looking up the phone number to see if I
could get through to someone directly.

I simply cannot fathom why these problems were not raised when the website
was on my staging domain and have only been mentioned since the site has
been made live / customer facing?

**Comment by matthewrgourd** [comment]
@unclemuzy, I'm told the payment source is now active. Once again, apologies for the delay.
