### ISSUE TITLE
404 error on cs cart 4

### ISSUE THREAD

**Issue by gtempelis** [VivaPayments/API#1406]
Hello. 

After following the exact steps on https://developer.vivawallet.com/e-commerce-plugins/cscart4/ we get the 404 restricted error.

In order to debug, I have added a curl logger, and the output was (API pass and authentication toked deleted):

`data submitted: "Amount=59850&RequestLang=el-GR&Email=tempelis%40allaboutbusiness.gr&MaxInstallments=1&MerchantTrns=120_REFb5cfd954e&SourceCode=2321&CurrencyCode=978&PaymentTimeOut=300"
 
credentials used: e4bc7a70-825d-4c07-8dd2-20e695a51b0:APIDELETED
 
*   Trying 2.22.50.184:443...
* TCP_NODELAY set
* Connected to www.vivapayments.com (2.22.50.184) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: TLSv1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=GR; L=Marousi; O=VIVA PAYMENT SERVICES S.A.; CN=*.vivapayments.com
*  start date: Oct 30 00:00:00 2019 GMT
*  expire date: Nov  3 12:00:00 2021 GMT
*  subjectAltName: host "www.vivapayments.com" matched cert's "*.vivapayments.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=Thawte RSA CA 2018
*  SSL certificate verify ok.
* Server auth using Basic with user 'e4bc7a70-825d-4c07-8dd2-20e695a51b0'
> POST /api/orders HTTP/1.1
 
Host: www.vivapayments.com
Authorization: Basic TOKEN DELETED
Accept: */*
Content-Length: 167
Content-Type: application/x-www-form-urlencoded
 
 
* upload completely sent off: 167 out of 167 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
 
< Server: Microsoft-IIS/10.0
< Strict-Transport-Security: max-age=15768000
< Content-Type: application/json; charset=utf-8
< X-Viva-CorrelationId: 20-050-5346750D
< Content-Length: 61
< Date: Wed, 19 Feb 2020 14:53:00 GMT
< Connection: close
< SSL_CLIENT_S_DN: 
< 
* Closing connection 0
 
response: {"Message":"Authorization has been denied for this request."}
`

Any ideas?

**Comment by matthewrgourd** [comment]
I appreciate you sending all that information through. However, in order for us to investigate further, could you send through the following screenshots:

- Payment module settings (mask the API Key).
- Viva Wallet payment source settings (include the browser's URL in the screenshot).
- Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
- API Access page (mask API Key, include the browser's URL in the screenshot).

Thanks.

**Comment by gtempelis** [comment]
Thank you Matthew for you response.

Find them as follows:

![1](https://user-images.githubusercontent.com/19335316/75167721-7c13b580-572e-11ea-90ed-4b16d4204688.jpg)

![εικόνα](https://user-images.githubusercontent.com/19335316/75167887-baa97000-572e-11ea-9647-0d2b735192f4.png)

![εικόνα](https://user-images.githubusercontent.com/19335316/75167921-c432d800-572e-11ea-9c3f-3652e77f8226.png)

![εικόνα](https://user-images.githubusercontent.com/19335316/75167990-dca2f280-572e-11ea-8d3b-029f3781a388.png)

Thanks!

**Comment by matthewrgourd** [comment]
Hi @gtempelis thanks for the screenshots. I think the problem is the last letter of your merchant ID was missed out in one of the settings. Instead of e4bc7a70-825d-4c07-8dd2-20e695a51b0 use **e4bc7a70-825d-4c07-8dd2-20e695a51b0e**. If it's not that, please let me know.

**Comment by gtempelis** [comment]
... this is the part @matthewrgourd that I feel awkward... 

Sorry for troubling you. You are right.

Thank you for everything.
