### ISSUE TITLE
Transaction seemingly goes through, but no payment is received and I'm redirected to the error page

### ISSUE THREAD

**Issue by lexam79** [VivaPayments/API#1407]
Hello,
I have a problem with a specific - as far as I know - client from Germany. When they try to pay through my website (I'm using the redirection method) and after confirming the payment they want to send, using some mobile app of their bank, they get redirected to my failure page (based on the configuration of the payment sources within vivawallet.com), without any error message. Although they have - theoretically - approved the payment and received no error within the vivawallet page or their bank's app, there is actually no payment made (they don't see any transaction in their bank, nor do I see any trace in vivawallet.com).

This happened again yesterday, at 2020-02-24T21:39:40.3777706+02:00. I have the transaction ID and order code, if you need it.

Can you please assist me?

Thank you

**Comment by matthewrgourd** [comment]
Hi @lexam79 sorry to hear this. If it's an isolated incident it could well be the client's card issuer that's preventing the transaction. However, I can investigate to see if your account is ok. Please send your merchant ID and business name to me by email: mgourd@vivawallet.com. May I ask which of our products / services it is you're using? ([online checkout](https://developer.vivawallet.com/online-checkouts/), [e-commerce plugin](https://developer.vivawallet.com/e-commerce-plugins/) or [payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/))

**Comment by lexam79** [comment]
Hello,

I'm using the online checkout and more specifically, the redirection method. I'll send the details you asked for straight away, via email.

Thanks

**Comment by matthewrgourd** [comment]
Hi there, I've replied to you by email but essentially all the payment failures I can see relate to an invalid CVV being provided by your client. Hope this helps!
