### ISSUE TITLE
problem registration number 

### ISSUE THREAD

**Issue by Mickael1531** [VivaPayments/API#1408]
Hello,
I have got a problem when i want to add and configure my account on vivawallet.
The account configuration is blocked because the Rgistration number is already existed.

I think the problem became that i created two accounts for the company ROADFLOWERS.

Can you help me to find a solution to finish my account configuration.
Thanks

**Comment by matthewrgourd** [comment]
Hi @Mickael1531, sorry to hear this. Can you reply with a screenshot of the error message, blurring out any personal details?

**Comment by Mickael1531** [comment]
Hello matthewrgourd,

In attachement the screenshot of the error message.
![Screenshot_2020-02-25 Create Business Account - Viva Wallet](https://user-images.githubusercontent.com/61472655/75338431-fc512c80-588e-11ea-9b47-21cb8bea519a.png)

**Comment by matthewrgourd** [comment]
If you're already registered, don't you need to [log in](http://developer.vivawallet.com/getting-started/#log-in-to-sandbox) rather than open a new account, or am I missing something?

**Comment by Mickael1531** [comment]
Yes, i think you don't have all the details of the problem. I explain.

Yesterday, i create a 1st account and i enter all the informations of my company. But, i want to connect to my account later. I don't access to the account. And i had the message : "your account don't exist".

So, i created a second account. But when i want to enter the informations, i can't because the registration number already exist.

Is it possible to clean all the informations of my company in order to put again the informations on the account will run ?

**Comment by matthewrgourd** [comment]
Hi @Mickael1531 is it simply that you've forgotten your password from the initial registration? If so, please click on the **I forgot my password** link on the [signin page](https://www.vivapayments.com/en/signin). Or is it something more than that?

**Comment by Mickael1531** [comment]
Is more than that.

When i click sur forgot my password. The message says that my account don't exist. And i can't access to create a new password.

**Comment by Mickael1531** [comment]
I've received a message to reset my password. I create a new one and can access to my account.

But again, i can't complete the informations because your says to me that the registration number already exist.
Can you delete the two accounts open with contact@roadflowers.fr and RFpaiement@roadflowers.fr ?
After, i will try to create my account.

**Comment by matthewrgourd** [comment]
Hi @Mickael1531 I'm afraid I can't do anything from here but if you call our Customer Service team I'm sure they can help :-) If you're based in France, the number to call is (+33) 1876 50765. Thanks!
