### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by MichailChomatas** [VivaPayments/API#141]
Καλησπέρα σας,

Με την ολοκλήρωση της παραγγελίες εμφανίζει το παρακάτω:
![image](https://cloud.githubusercontent.com/assets/20337087/16650923/699d7df6-4449-11e6-8d30-a238c72712f9.png)

Τι μπορεί να φταίει?

Ευχαριστώ.

**Comment by MichailChomatas** [comment]
καλησπέρα σας,

Παρακαλώ μήπως έχετε κάποια απάντηση σχετικά με το παραπάνω αίτημα?

**Comment by krakenrules** [comment]
Καλησπέρα MichailChomatas,

Το πρόβλημα που έχετε ξεκινάει από το γεγονός οτι η δημιουργία παραγγελίας αποτυγχάνει, και εξαιτίας αυτού δεν έχετε κωδικό παραγγελίας όταν κάνετε redirect στην checkout:
https://www.vivapayments.com/web/newtransaction.aspx?ref= (η παράμετρος ref δεν εχει τιμή)

Για περισσότερες λεπτομέρειες δείτε στην σελίδα https://github.com/VivaPayments/API/wiki/CreateOrder

Ευχαριστούμε πολύ για την επικοινωνία.
