### ISSUE TITLE
how to get transaction id for simple checkout process

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1411]
Hi,

I am trying simple checkout process, Step 1: Display the button is done, 
Step 2: Make the charge - to complete this we need transaction id, where to get this transaction id.

Thanks,
Pavithra

**Comment by matthewrgourd** [comment]
Hi there, I'm getting a developer to look into it. It appears there's a gap in the documentation. I'll reply once I have an update.

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, sorry for the delay, we needed to update our Simple Checkout implementation guide. Please have a look and get back to me whenever you need a hand. Thanks!
