### ISSUE TITLE
Not able to create the transaction for simple checkout

### ISSUE THREAD

**Issue by Bharat0538** [VivaPayments/API#1412]
Hi, 
I am trying to create the transactions for simple checkout.
I am not getting what id to put in URI ("https://demo.vivapayments.com/api/transactions/{Id}") for posting the JSON.
How to get the id .

**Comment by matthewrgourd** [comment]
Hi there, I'm getting a developer to look into it. It appears there's a gap in the documentation. I'll reply once I have an update.

**Comment by ArisTseka** [comment]
Hello, I have the same problem too.

**Comment by matthewrgourd** [comment]
Hi @Bharat0538, @ArisTseka, sorry for the delay, we needed to update our [Simple Checkout implementation guide](https://developer.vivawallet.com/online-checkouts/simple-checkout/). Please have a look and get back to me whenever you need further help. Thanks!

**Comment by matthewrgourd** [comment]
[Simple Checkout guide](https://developer.vivawallet.com/online-checkouts/simple-checkout/) checked and updated. I'm closing this issue.
