### ISSUE TITLE
Translation Issue - Prestashop 1.7.5.1

### ISSUE THREAD

**Issue by Paolobigga** [VivaPayments/API#1413]
Hi everyone,

I have trouble translating in the checkout on the front-end (attached you'll find an image)

I've tried to translate it from the admin area but it doesn't work. How can I proceed?

Thank you!

Paolo

![Schermata-2020-02-26-alle-18 37 02](https://user-images.githubusercontent.com/61514653/75371609-5cfc5b80-58c7-11ea-8d23-da9ab597c18c.jpg)

**Comment by matthewrgourd** [comment]
Hi @Paolobigga, edit the language files that are located in the modules folder and rename every instance of 'vivawalletlatest' with `vivawallet'.

**Comment by Paolobigga** [comment]
Hi @matthewrgourd, thank you for your reply!

I'm not familiar with PrestaShop yet, where can I find these modules folder?

Thank you!

**Comment by matthewrgourd** [comment]
Hi @Paolobigga, me neither, apologies! All I know is that it's located in the admin area in PrestaShop.
