### ISSUE TITLE
Shopify checkout language

### ISSUE THREAD

**Issue by pvoulg** [VivaPayments/API#1414]
We've noticed that the redirect Checkout on our English website (Shopify) is set in Greek, even though the language preferences are all set in English. The default language used to be in English, but for some reason it has now reverted to Greek and I can't seem to find a way to change that.

The majority of this store's customers are non-Greek speakers, so this is rather confusing. Since this is a Shopify integration that I have no control over, how would we be able to switch that back to English?

**Comment by matthewrgourd** [comment]
Hi @pvoulg strange, can you let me know the Viva Wallet Merchant ID and business name so I can check a few things? Please send to my email address mgourd@vivawallet.com. Thanks!

**Comment by pvoulg** [comment]
Hi @matthewrgourd, thanks for the quick reply. I've sent you an email with the info requested.

**Comment by matthewrgourd** [comment]
Hi @pvoulg I've received that info now. Thank you. So your account was set up in Athens meaning the default language is Greek. I think you change this for Shopify as below but I'm not 100% certain. Please try this and let me know the result!

![50766594-851f9a00-1282-11e9-82cc-5093b9adfcf2](https://user-images.githubusercontent.com/44943019/75445332-22450280-595d-11ea-80f6-6e6eb150ac80.jpg)

**Comment by pvoulg** [comment]
The language is already set to English, as you can see below. 

![Screen-Shot-2020-02-27-at-15 43 39](https://user-images.githubusercontent.com/7416221/75451175-ba041a00-5978-11ea-8559-f2749e9e127e.jpg)

**Comment by matthewrgourd** [comment]
Hi @pvoulg I've spoken with our Shopify plugin developer who says that the default language is set by the Shopify property 'Store Country'. So I believe it's on the Shopify side of things you need to be checking. Hope this helps. Let me know if not!

**Comment by pvoulg** [comment]
Hi @matthewrgourd, yes this seems to be the case. If I change the Shopify country it reverts to the English interface. 

Is there any way that this setting is defined elsewhere though? Because we've got several clients based off Greece who are selling mainly worldwide and as you can imagine, they can't go changing their Store Country, just so their users can pay in an English UI. The Store Country setting affects Shopify's invoicing as well (it's tied to your VAT code), so it can't just be changed at will.

**Comment by matthewrgourd** [comment]
Hi @pvoulg I'm checking for you...

**Comment by matthewrgourd** [comment]
Unfortunately, I'm told default language is currently based on Store Country only. There are no other settings. Apologies for any inconvenience caused.

**Comment by pvoulg** [comment]
That's probably a proper feature request, if you can relay that to the Shopify developers.

**Comment by matthewrgourd** [comment]
@pvoulg will do that, certainly...
