### ISSUE TITLE
Redirect checkout,saying transaction failed, unable to getting  merchant account specified redirect url 

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1415]
1. created the  payment order.(https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post)
2.with order code, we redirect to vivawallet page(https://demo.vivapayments.com/web/checkout?ref={OrderCode})
3.after entering customer(sandbox ) details, after that i am getting the  url , its not going back to merchant account specified Redirect url. 
4.Saying transaction failed.
![redirectcheckout_transactionfailed](https://user-images.githubusercontent.com/61449311/75439750-68f82400-5980-11ea-8075-110167084274.png)

   attached full details in following screen shots.

**Comment by matthewrgourd** [comment]
Hi @chennurubharath although the error message states that the transaction failed, if you check the [sales transactions](https://demo.vivapayments.com/selfcare/en/sales/mysales) in the Viva Wallet banking app, you will see corresponding entries if you chose success in the 3DS simulator as an outcome. I'm not sure why there isn't a simulated 'success message' after you've made the transaction.
