### ISSUE TITLE
Viva payment plugin for j2store

### ISSUE THREAD

**Issue by vasite** [VivaPayments/API#1416]
Καλησπέρα σας
Βλέπω πως υπήρχε ήδη η ζήτηση από το 2017 αλλά την επαναφέρω επειδή δεν έχει επιλυθεί. 
Το k2store έχει καταργηθεί ήδη εδώ και χρόνια και αντικαταστάθηκε από το J2Store.
Θα ήταν καλό να ενημερώσετε το Plugin σας k2store ώστε να λειτουργεί στο τελευταίο Joomla και στο J2Store.

_Originally posted by @vasite in https://github.com/VivaPayments/API/issues/335#issuecomment-592025025_

**Comment by matthewrgourd** [comment]
Hi @vasite, many thanks for your feedback. I'll be sure to tell our plugin developer to add to the roadmap as a priority. Apologies for the delay, this is due to a resourcing issue which has now been resolved.

**Comment by vasite** [comment]
That's perfect! Thanks a lot for you quick response! 
p.s. please change the subject to lets say: Viva payment plugin for j2store
I dont have permissions to change it.

**Comment by matthewrgourd** [comment]
I'm closing the case now but I've added to our priority list...
