### ISSUE TITLE
WooCommerce payment issue

### ISSUE THREAD

**Issue by Mystersoo** [VivaPayments/API#1417]
Hello, overnight impossible to make payments on the 3 Internet sites, an inifinite loading this products just after choosing VivaWallet as payment, then loading as in the image provides, to finish with this errors "Request Timeout

Server timeout waiting for the HTTP request from the client.

Additionally, a 408 Request Timeout error was encountered while trying to use an ErrorDocument to handle the request."
![Chargement Infinie](https://user-images.githubusercontent.com/61589443/75556748-116cbd80-5a3f-11ea-9c18-6ae17edec6c4.png)
![Erreur](https://user-images.githubusercontent.com/61589443/75556776-1f224300-5a3f-11ea-9be1-7fb6f76844a9.png)

Thank you in advance

**Comment by matthewrgourd** [comment]
Hi @Mystersoo sorry to hear this, can I first of all check if you work for Royal CBD? If you do, please let me know if the Viva Wallet plugin for WooCommerce has been downloaded and installed from the below page:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

Thanks!
