### ISSUE TITLE
Shopify- Issue- Multiples Payment failure

### ISSUE THREAD

**Issue by Mamakana** [VivaPayments/API#1418]
Hello, 

I am using vivawallet for my shopify shop www.mamakana.com. 
There are multiples payment failure on the shop every day.
Here an exemple of one of them yesterday.
![Capture d’écran 2020-02-28 à 10 40 42](https://user-images.githubusercontent.com/61584569/75558739-8d1c3980-5a42-11ea-94da-2970c699311f.png)

Even when payment is accepted, there is a payment failure before 
![Capture d’écran 2020-02-28 à 15 55 07](https://user-images.githubusercontent.com/61584569/75559029-0a47ae80-5a43-11ea-893a-a2918d56d296.png)

Kind regards, 
Joffrey

**Comment by matthewrgourd** [comment]
I can see from your account that all the failures are due to insufficient funds on the cards being used. The card owners should contact their card issuers.
