### ISSUE TITLE
PrestaShop module success page error

### ISSUE THREAD

**Issue by Daaaaad** [VivaPayments/API#1420]
Hello,

I have installed and configured your solution following the doc : https://developer.vivawallet.com/e-commerce-plugins/prestashop/

Payment is working fine and card is charged... but order is not validated in PrestaShop. After some research I found that the success page is called but the redirection (line 88 of controllers/front/success.php) is missing the $this->module->currentOrder (param is empty, don't know if it should be).

Here is my configuration : 

https://www.dropbox.com/s/h2ld0m4xp1x4mu4/Capture%20d%27%C3%A9cran%202020-02-28%2020.57.05.png?dl=0

https://www.dropbox.com/s/7tr34dew2rr7zfg/Capture%20d%27%C3%A9cran%202020-02-28%2020.58.25.png?dl=0

Can you help?

**Comment by Daaaaad** [comment]
Can someone help?

**Comment by matthewrgourd** [comment]
Hi @Daaaaad is the Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/prestashop/#step-1-create-a-payment-source) you set up active? Beyond that, if you've followed our setup instructions verbatim, it's most likely a problem at the PrestaShop end. However, saying that, if have reason to believe it's a bug with our plugin, I can raise with one of our developers.

**Comment by Daaaaad** [comment]
Yes, the payment source is active 👍

I have double checked the configuration and still cannot find the reason... can you transfer this ticket to a developer please?

**Comment by matthewrgourd** [comment]
Hi @Daaaaad will do!

**Comment by Daaaaad** [comment]
Can you help?

We need to accept credit cards payment ASAP 🙄

**Comment by matthewrgourd** [comment]
Hi there, our development team has come back to me. They're still investigating the issue and need some further info. When you have a spare moment, could you answer the following, please?

1. What version of PrestaShop are you using?
2. PHP/ MySQL versions?
3. What kind of webserver do you have for hosting (is it Apache? is it Linux-based?) 

You may also be interested checking this post on the PrestaShop forum, although I think the problem may be at our end so bear with us! Thanks.

**Comment by Daaaaad** [comment]
Hi @matthewrgourd, here is: 

1. PrestaShop 1.7.6.2
2. PHP 7.3.15, MySQL 5.5.64-MariaDB
3. Apache on Linux #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64

Regards,

David.

**Comment by matthewrgourd** [comment]
Hi @Daaaaad thanks for those answers. I'll pass on that info. In the meantime, can you try installing this zip file which has some slight amendments to the PrestShop plugin for version 1.7.6 onwards... https://github.com/VivaPayments/API/files/3512057/vivawallet.zip

**Comment by matthewrgourd** [comment]
@Daaaaad apologies, I double-checked and you're using the correct version of our plugin. The above link is actually to the previous version.

**Comment by matthewrgourd** [comment]
Hi @Daaaaad , just to let you know that our development team has now completed a test installation of the plugin. The conclusion is that it is working correctly. The problem therefore must be within your PrestaShop e-commerce settings which do tend to be quite tricky to sort out. I wish you luck finding a solution but I'm afraid I can't help any further. Thanks!

**Comment by Daaaaad** [comment]
The problem certainly comes from the configuration as we are testing on a (almost) fresh installation of PrestaShop. But ok if you can't help we will not use your payment solution. Bye.
