### ISSUE TITLE
Woocommerce Langage issue

### ISSUE THREAD

**Issue by WeedyTech** [VivaPayments/API#1421]
Hello,

We would like the default language on the vivawallet payment page to be French for our customers and same for the payment confirmation email. How can we do this?

thank you in advance

**Comment by WeedyTech** [comment]
We have try this solution below but the langage change to GREEK by default... Someone has the solution please ? It could us lost customers who are afraid of arriving on a payment page in a foreign language

> @safwen1 you can make the changes to the WooCommerce plugin yourself by editing the code (wc-vivawallet.php). Specifically this section:
> 
> ORIGINAL
> 
> `$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300';`
> 
> NEW (with **`&RequestLang=fr`** added)
> 
> `$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang=fr'.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300';`

**Comment by safwen1** [comment]
@WeedyTech The solution is not accurate, it needs to be like this : 

$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang=fr&Email='.urlencode($poststring['Email']) etc

meaning that the part '.urlencode($poststring['RequestLang']).' should be deleted.

**Comment by WeedyTech** [comment]
Thank you for your help. Could you please paste the complete code that I need to update in my wc-vivawallet.php please ?

**Comment by WeedyTech** [comment]
Ok i have success thanks to you !

**Comment by WeedyTech** [comment]
Could you please tell me how can I change the lang for the confirmation email of viva wallet please ?

**Comment by matthewrgourd** [comment]
@WeedyTech for the second problem, have you tried changing your default language in the Viva Wallet banking app? See screenshot below:

![75451175-ba041a00-5978-11ea-8559-f2749e9e127e](https://user-images.githubusercontent.com/44943019/75771289-96a6e980-5d41-11ea-9804-84fc5fa5ca17.jpg)

**Comment by matthewrgourd** [comment]
@safwen1 thanks for the correction!

**Comment by WeedyTech** [comment]
Yes unfortunately I only have Greek or English

**Comment by matthewrgourd** [comment]
@WeedyTech in that case I'm not sure and will have to check with a developer.

**Comment by WeedyTech** [comment]
> @WeedyTech in that case I'm not sure and will have to check with a developer.

Ok thank you

**Comment by matthewrgourd** [comment]
@WeedyTech in which country did you [register](https://app.vivawallet.com/) for your Viva Wallet account?

**Comment by matthewrgourd** [comment]
@WeedyTech reply back from our dev team:

>Confirmation email will respect the value of the `requestLang` parameter of the [Payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post)
(French is supported)

Hope this helps!

**Comment by safwen1** [comment]
> @WeedyTech reply back from our dev team:
> 
> > Confirmation email will respect the value of the `requestLang` parameter of the [Payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post)
> > (French is supported)
> 
> Hope this helps!

We have a case where the payment is done in French, but the confirmation email is in English. Can you please check again.

**Comment by WeedyTech** [comment]
can you tell me in the 3.6.0 plugin how can I do please ?

**Comment by WeedyTech** [comment]
@matthewrgourd

**Comment by matthewrgourd** [comment]
Hi @WeedyTech can you try replacing:
```
             $trlang = get_locale();

            if (preg_match("/gr/i", $trlang) || preg_match("/el/i", $trlang)) {
                $formlang = 'el-GR';
            } else {
                $formlang = 'en-US';
            }
```
with
```
           $trlang = get_locale();

            if (preg_match("/gr/i", $trlang) || preg_match("/el/i", $trlang)) {
                $formlang = 'el-GR';
            } else {
                $formlang = 'en-FR';
            }
```
in wc-vivawallet.php ?

**Comment by WeedyTech** [comment]
Ok i have try but it doesn't change anything @matthewrgourd

**Comment by WeedyTech** [comment]
Do you have another solution please ?

**Comment by matthewrgourd** [comment]
Did you refresh your browser after making the change? You need to clear your cache and cookies. No other solution I can think of – sorry! We're in the process of updating / improving our plugins so please watch this space...

**Comment by WeedyTech** [comment]
Yes I have clean.. You can't have any solution like the previous version of the plugin ?

**Comment by WeedyTech** [comment]
The good solution is :

         $formlang = 'fr-FR';
            } else {
                $formlang = 'fr-FR';

**Comment by matthewrgourd** [comment]
@WeedyTech, great, thanks for informing me!
