### ISSUE TITLE
Shopify Payment without redirect

### ISSUE THREAD

**Issue by scalef** [VivaPayments/API#1422]
Hi, I have a Shopify store and I followed the instruction [here](https://developer.vivawallet.com/e-commerce-plugins/shopify/) to install the Viva payment gateway. 
My question is: is it possible to have the input fields of card detail, directly in the Shopify checkout, avoiding the message below?
![image](https://user-images.githubusercontent.com/23737624/75696920-a0324200-5cac-11ea-95d8-4933ec85a091.png)

I saw the issue #537 but since it's 2 years old, I try to ask if there is some news. 

I think that the solution explained [here](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) could not be implemented in Shopify.

Thank you in advance,
Stefano

**Comment by matthewrgourd** [comment]
Hi @scalef this is still the way our plugin works out of the box. Unfortunately Shopify is making it very difficult for us to upgrade from the redirect functionality. However, this may change in the future.
