### ISSUE TITLE
Problème installation shopify

### ISSUE THREAD

**Issue by gui7925** [VivaPayments/API#1423]
Bonjour, 

J'ai essayé d'installer le système de paiement vie votre lien. J'ai bien eu le token nécessaire mais quand je l'installe, rien ne se passe sur Shopify, je n'ai pas l'écran qui montre que l'option est ajouté.

Que dois-je faire ?

**Comment by matthewrgourd** [comment]
Please follow our Viva Wallet for Shopify [instructions](https://developer.vivawallet.com/e-commerce-plugins/shopify/) closely, taking special care at the start to:

1. Identify your [Merchant ID](https://www.vivawallet.com/wp-content/uploads/2019/03/how-to-find-merchant-id-2.png) correctly.
2. Successfully [request a Shopify Store Token](https://viva.microsoftcrmportals.com/shopify) from us.

**Comment by gui7925** [comment]
Hello,

I'm sorry, i follow the step but at the step 7, there is no popup, and
vivawallet is not on proposition on my shopify ?
---
Guillaume PONTON



Le mar. 3 mars 2020 à 12:07, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi there, can you let me have a screenshot of what you're seeing at step 7? Thanks.

**Comment by gui7925** [comment]
Hello,

it's ok it's working now.

but is it possible to put your system in French for my website for my
french customers ?

thanks

---
Guillaume PONTON



Le ven. 6 mars 2020 à 16:04, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @gui7925 the default language is set by the Shopify property 'Store Country'. Hope this helps!

**Comment by gui7925** [comment]
Hello,

Everything is in french but not your form when the client have to pay
---
Guillaume PONTON



Le lun. 9 mars 2020 à 14:12, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @gui7925 it should be in French if you [registered](https://app.vivawallet.com/register/) your Viva Wallet account in France? Otherwise customers will have to switch using the dropdown indicated below:

![web-checkout](https://user-images.githubusercontent.com/44943019/76229495-379e1480-621a-11ea-81fd-9453ccbbae58.png)
