### ISSUE TITLE
Simpe checkout , response as   "ErrorText": "The specified api action is disabled for the merchant XXXXXXX, please consult the documentation

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1424]
Hi, in simple checkout while trying step (2) make the charge, the response "Error text " saying like bellow
{
  "Emv": null,
  "Amount": null,
  "StatusId": "E",
  "CurrencyCode": null,
  "TransactionId": null,
  "ReferenceNumber": null,
  "AuthorizationId": null,
  "RetrievalReferenceNumber": null,
  "ThreeDSecureStatusId": null,
  "ErrorCode": 403,
  "ErrorText": "The specified api action is disabled for the merchant 5e8d6a84-d20c-485e-a085-354b2a54473e, please consult the documentation",
  "TimeStamp": "2020-03-03T11:43:20.4335139+02:00",
  "CorrelationId": null,
  "EventId": 0,
  "Success": false
}

**Comment by matthewrgourd** [comment]
HI @chennurubharath I've changed one of your settings. Can you try again and see if you get the same result?

**Comment by chennurubharath** [comment]
its working, thank u @matthewrgourd
