### ISSUE TITLE
Opencart Version 2.3.0.2 Module Error

### ISSUE THREAD

**Issue by yawar786** [VivaPayments/API#1426]
Hi, Module Installed.

When customer paid website redirect to account page but customer can't see order in his under the account and admin side order can be seen but under missing order even payment is paid.

Until you update order payment received or any other status change then customer can see order in his under the front-end side.

Please advise how can I fix this issue.

Thanks.

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. I don't fully understand the issue. If you can, please send through screenshots with customer information (and anything else confidencial) blurred out.

**Comment by yawar786** [comment]
Hi @matthewrgourd.

Problem which i am facing. When customer doing checkout, page take to customer vivawallet page for payment after complete payment customer can't see order under his account. 

2nd Admin side I can see customer order but under missing order as i am using module which shows me if any customer left any item in cart doing the checkout if they not paid so OpenCart system not show by default. 

If you give me email add where i can send you all screenshot plus login details then you can see what actually happening.

**Comment by matthewrgourd** [comment]
Hi @yawar786 please send me screenshots (mgourd@vivawallet.com) referencing this issue (#1426) and I'll investigate further.

**Comment by yawar786** [comment]
Emailed please check. Thanks.

**Comment by matthewrgourd** [comment]
HI @yawar786 I've replied by email with what I hope is the solution!
