### ISSUE TITLE
hikashop

### ISSUE THREAD

**Issue by michalis82** [VivaPayments/API#1427]
UNABLE TO CREATE ORDER CODE (THE MERCHANT WITH ID 045B8B72-6EFB-467A-A940-69CFA3C81189 DOES NOT HAVE A SOURCE WITH CODE 'SIRIOCENTER' ASSIGNED OR THE SOURCE IS DISABLED)

**Comment by matthewrgourd** [comment]
Hi @michalis82, in your HikaShop module settings, can you try specifying a source code of '7994' (siriocenter2) instead of '1180' (siriocenter) as the latter is inactive..
