### ISSUE TITLE
Oauth 2 token generation

### ISSUE THREAD

**Issue by antoniohalexo** [VivaPayments/API#1428]
Hi, 

I've just created a demo account and - as part of the Native Checkout v2 3DS - I'm trying to get the Request access token by submitting my Client ID and Secret (econded) via Postman.

But, the answer I'm receiving is:

invalid_client

Do you have a example/instruction to how use Postman to get the access token?

Thank you

**Comment by matthewrgourd** [comment]
Example in cURL:
```
curl -X POST \
  https://demo-accounts.vivapayments.com/connect/token \
  -F client_id=ht4x6zatylyt0qu5py9turjqj61158y25nzbxueg32v56.apps.vivapayments.com \
  -F client_secret=XEP256vR6jXRzD455Vrv3Eew4AYw2L \
  -F grant_type=client_credentials
```

**Comment by chennurubharath** [comment]
hi @matthewrgourd  , i  also faced same problem like @antoniohalexo ,  i tried you mentioned cURL, even though its showing same  "invalid client "( i tried with my demo account id, secret)

thank you
