### ISSUE TITLE
Το success οδηγεί στο Viva Payments result page αντί της custom πηγής πληρωμών

### ISSUE THREAD

**Issue by Cadmos** [VivaPayments/API#143]
Γεια σας,

σχετικά με το Viva Wallet με ΑΦΜ ****68339.

Ενώ στο demo environment μετά την επιτυχή συναλλαγή οδηγούσε στο http://www.**********.gr/book/ok.php?... και όλα λειτουργούσαν **άψογα**, στο live περιβάλλον αντί να οδηγεί επίσης στο http://www.******.gr/book/ok.php , οδηγεί τον πελάτη στο success page του https://www.vivapayments.com/web/checkout/result?.. μετά την πληρωμή του.

Το success url έχει οριστεί στο live account ακριβώς όπως στο demo. Όπως φαίνεται εκτός της πηγής πληρωμής για το website που δημιουργήσαμε και είναι ενεργή στο status, **έχει παραμείνει και η Default** που υπήρχε κατά το άνοιγμα του account και φαίνεται να χρησιμοποιείται αυτή αντί της ενεργής ενώ **δε μπορεί να διαγραφεί**.

Μπορείτε να το κοιτάξετε ;

*** Δυστυχώς δε μπορώ να δημοσιοποιήσω τα στοιχεία του ΑΦΜ και του website online, μέσω e-mail στο merchants@vivawallet.com με παραπέμψατε εδώ. Ενημερώστε με τι στοιχείο χρειάζεστε.

**Comment by krakenrules** [comment]
Γεια σας, 

Αν στο live περιβάλλον έχει οριστεί νέα πηγή πληρωμών θα πρέπει να δηλώσετε τον κωδικό (όχι το όνομα) της νέας αυτής πηγής στην παράμετρο ‘SourceCode’ όταν καλείτε την CreateOrder. 

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by Cadmos** [comment]
Δούλεψε όπως υποδείξατε, δηλαδή αλλάζοντας στο CreateOrder file το 

`$Source = 'Default';` σε  `$Source = 'κωδικός-πηγής-πληρωμών';`

Ευχαριστώ.
