### ISSUE TITLE
shopify install 

### ISSUE THREAD

**Issue by dablabuk** [VivaPayments/API#1430]
Hi, 

I am trying to connect my viva to shopify payments. 

However when i sign in as an admin, and access "payment providers" viva does not appear. Also I'm unsure how to add the token, to my profile section as there is no options to do so on my account. 

if you can share some advise, it would be much appreciated. 

thank

**Comment by matthewrgourd** [comment]
Hi @dablabuk, sorry to hear this. Please ensure you've followed our [Shopify plugin guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/) closely. Pay particular attention to covering the below:

1. Identify your [Merchant ID](https://www.vivawallet.com/wp-content/uploads/2019/03/how-to-find-merchant-id-2.png) correctly.
2. Successfully request a [Shopify Store Token](https://viva.microsoftcrmportals.com/shopify) from us.
3. Submit result of 1. and 2. accurately as in screenshot below.
![viva-wallet-payment-provider-settings](https://user-images.githubusercontent.com/44943019/75980493-76f6f900-5eda-11ea-83a8-a82878d23b74.png)
4. ('Test mode' disabled).

Hope this helps! Thanks...
