### ISSUE TITLE
POST to /nativecheckout/v2/transactions Fails to answer

### ISSUE THREAD

**Issue by dpantazis94** [VivaPayments/API#1431]
Hello !

We have just find out, that some POST Requests to  https://api.vivapayments.com/nativecheckout/v2/transactions fail to give a response. While, it did fail to give a response to us, the charge was succesfull. Please let me know, if this is an issue or if we should take a better look onm our code. I can share the code used to retrieve the charge token, and then the one that makes the Charge post request.

How much is the maximum time, the api could take to answer a transaction request ?

Thanks!

**Comment by dpantazis94** [comment]
More specific we have an example on these :

**date                  | viva data                                                      | transaction ID**
3/3/2020 22:47 |  04/03/2020  00:47:06 4124955864772604 | f2010990-864d-449e-b72f-e0d5e7734db9
3/3/2020  22:49 |                                                                     | 
3/3/2020  23:00 | 04/03/2020  01:00:21 9321178534972605 | 34fec623-6427-4a13-9887-2db37d123ea4

The client made  tries. Date is the when he made those tries on our system, viva data is the viva's date and order code and the transaction Id is the again the one created from viva.

On the first 2 requets viva failed to answer us, while on the first one the client was charged. Our client, told us that on the 1 request he did not receive an email as well. On the 3rd Request, everything worked fine and the client received an email as well.

Please let me know, for anything !

Thanks!

**Comment by matthewrgourd** [comment]
Hi @dpantazis94, I'm afraid I can't check anything without you providing your Merchant ID and business name. Please send these details through to my email address (mgourd@vivawallet.com). In the meantime, apologies, but I've obscured some of the transaction information you posted on GitHub for security reasons.

**Comment by matthewrgourd** [comment]
Hi @dpantazis94 thanks for sending through those details. I've checked your account and all looks fine. If there are any error codes returned by our API at any point, please let me know, otherwise I have to assume the issues are from those clients you mention failing their 3DS one or more times.

**Comment by dpantazis94** [comment]
Ok @matthewrgourd , thanks a lot for the quick resposne and your support.
