### ISSUE TITLE
Woocommerce authorize payment (credit, or bank transfer) but keep capture payment on hold until admin accepts the order

### ISSUE THREAD

**Issue by opykeweb** [VivaPayments/API#1432]
Hi, on a woocommerce site we would like the client to able to authorize  the payment on the checkout of the store an give the credit card /bank account details and authorize us but not charge the client and make the actual transfer of funds from client to our account until  the admin changes the order status ex. ‘’processing order’’ or via the viva panel by accepting the order and change it from oh hold to accept. If some days pass then the order and authorization are cancelled automatically. 

This is a function similar to stripe which can authorize and keep the payment onhold for 7 days and paypal for 29 days.

Is this possible?

**Comment by matthewrgourd** [comment]
This is not the way our WooCommerce plugin works our of the box but you can certainly modify the code if you have the necessary technical skills. To get you started, the relevant call in our Payment API is [Create payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post) using the parameter `isPreAuth`.
