### ISSUE TITLE
Blank page after 3D secure

### ISSUE THREAD

**Issue by WeedyTech** [VivaPayments/API#1434]
Hello, 15% of our customers have an issue : after validate their 3D secure code, they are redirect to a simple blank page without anything. And their order are in "pending payment".

15% is a very high fail rate, these customers have already do few orders on our website before implementing the viva wallet plugin. We was working with quickpay before. 

We use the official plugin.

Thank you for your help

**Comment by matthewrgourd** [comment]
Hi @WeedyTech I think I've spoken to you before via GitHub. Are you still referring to our  WooCommerce website plugin? Please email me your business name and Merchant ID so I can check your account: mgourd@vivawallet.com. Thanks!

**Comment by WeedyTech** [comment]
I have sent all information at your email address, thank you

**Comment by matthewrgourd** [comment]
Hi @WeedyTech I've checked your account and everything seems to be in order. Over the past week, there were multiple successful transactions through your WooCommerce plugin with the odd one here or there coming through as failed due to the customer's issuer preventing payment. In these instances, customers should contact their card issuer to find out why their payments are not successful. If you want to find out more about specific transactions, please contact the Viva Wallet customer service team for your country, details below. Best regards.

<table><tr><th>Country</th><th>Phone number</th>
  <tr><td>Belgium</td><td>(+32) 2342 0790</td></tr>
    <tr><td>Cyprus</td><td>(+357) 2403 0211</td></tr>
    <tr><td>France</td><td>(+33) 1876 50765</td></tr>
    <tr><td>Greece</td><td>(+30) 21 1760 4000</td></tr>
    <tr><td>Netherland</td><td>(+31) 2089 05503</td></tr>
    <tr><td>Romania</td><td>(+40) 3122 96150</td></tr>
    <tr><td>UK</td><td>(+44) 20 3734 7770</td></tr>
    <tr><td>Portugal</td><td>(+351) 3 0050 9059</td></tr>
</table>

**Comment by matthewrgourd** [comment]
Hi @WeedyTech, reopening as I gather you're still experiencing the issue. We've looked into this further and it seems you're not enrolled to Mastercard or something is going wrong with Mastercard. There is no obvious reason for this. We're continuing to investigate.

**Comment by WeedyTech** [comment]
Hello,

Thank you very much for your investigations, it seems that the problem could come from a problem of compatibility of the bank of the customer concerned by the error, or even from a problem with their computer configuration.

**Comment by matthewrgourd** [comment]
Hi @WeedyTech I've just had an update from our development team. Apparently a manual process which involves ourselves, Mastercard and our third-party 3DS provider, Modirum, failed and we had to repeat it on Friday. I'm told that everything should be working by end of tomorrow at the latest. This is not a common problem; usually everything goes smoothly. We will keep monitoring the service. Apologies for any inconvenience caused.

**Comment by WeedyTech** [comment]
Hello, thank you very much for this information !

---
Nous vous remercions pour votre confiance et restons à votre disposition 
pour toute information complémentaire,

Votre Service Clientèle Weedy.

Le 2020-03-16 10:09, matthewrgourd a écrit :

**Comment by WeedyTech** [comment]
Hello,


We now know that the error occurs when customers are on Google Chrome 
and it occurs for absolutely all customers who wish to pay via Google 
Chrome, not only with us but also with one of our competitors who uses 
your payment solution via Woocommerce.

---
Nous vous remercions pour votre confiance et restons à votre disposition 
pour toute information complémentaire,

Votre Service Clientèle Weedy.

Le 2020-03-16 10:09, matthewrgourd a écrit :

**Comment by WeedyTech** [comment]
Can you do something ?
