### ISSUE TITLE
maffeihoh20

### ISSUE THREAD

**Issue by maffeihoh** [VivaPayments/API#1435]
Having trouble working out how to set up and what to put for successful URL & Failure URL. 
I don’t know what to put in or how to set up .any advice would be appreciated

**Comment by matthewrgourd** [comment]
Hi @maffeihoh, sorry, before I can help, I need to know a bit more about your setup. Are you using an e-commerce platform (e.g. Shopify or WooCommerce)? If already live, what is your web address? Thanks!

**Comment by maffeihoh** [comment]
Thank you for getting back to me. I am using Shopify..web address is .
www.maffeihomeofhavana.co.uk
Thank you

**Comment by maffeihoh** [comment]
My merchant company is viva wallet . If you needed to know. Thanks.

**Comment by matthewrgourd** [comment]
Hi @maffeihoh if you follow the instructions in our [Shopify plugin installation guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/), the success and failure URLs should be set up for you automatically. I believe on the Viva Wallet side you just need to [request a store token](https://viva.microsoftcrmportals.com/shopify) and all the rest is done for you.

**Comment by maffeihoh** [comment]
Thank you so much
I will give it a go.
Marco
