### ISSUE TITLE
Websites / Apps : status pending for more than 56H

### ISSUE THREAD

**Issue by thebestofnature** [VivaPayments/API#1436]
Hi , i created a Websites / Apps account and i'm waiting for approval for more than 56H now. 
What can i do ?

**Comment by matthewrgourd** [comment]
Hi @thebestofnature have you received any emails from us? (check your spam) We may have sent out some instructions on what you need to add to your website before we can make your payment source active. If not, please email me at mgourd@vivawallet.com with your business name and Merchant ID quoting this issue (#1436).

**Comment by thebestofnature** [comment]
Hi Matthewrgourd  i didn't receved any mail with instructions . Nothing in spams . Thanks 
The best of nature

**Comment by matthewrgourd** [comment]
In that case, @thebestofnature, please email me at mgourd@vivawallet.com with your business name and Merchant ID quoting this issue (#1436) and I will check your account.

**Comment by matthewrgourd** [comment]
Hi @thebestofnature thanks for sending that info through. I've checked with our accounts team and apparently we sent an email 3 days ago outlining a couple of things you need to do to your website before your payment source can be activated. If you're unable to find this message, please email support@vivawallet.com letting them know your full details and asking them to send again. Thanks!
