### ISSUE TITLE
ERP/ECR support - How to perform a SaleRequest with Installments

### ISSUE THREAD

**Issue by d3sync** [VivaPayments/API#1439]
I have created an app that connects using TCP/IP with our countertop (S900 prolin) to handle the transactions. I can send SaleRequests w/o issues although i can't find how to Initialize transactions with installments. 
Is it even supported in the ERP/ECR api?

thanks in advance

**Comment by matthewrgourd** [comment]
Hi @d3sync, I'm not sure if installments are supported in this instance. I'll check for you.

**Comment by matthewrgourd** [comment]
Hi @d3sync, I've had some info. back. Regarding instalments, these are supported only via our inter-app API, i.e. [POS terminal app](https://developer.vivawallet.com/pos-api-integration/pos-terminal-app/) API. In other words, you can have your own app running alongside ours and trigger a sale with installments. However, unfortunately you can't do this (at present) by connecting an external cash register via the cardlink API.

**Comment by d3sync** [comment]
@matthewrgourd So there is a hope to fully integrate countertop POS like s800 and s900 for all transactions or should I consider upgrading to newer hardware :P 

thank you for your time

**Comment by Darniss** [comment]
@matthewrgourd Hi sir!... I am having device A920. Is it possible to send request from my webpage to the device terminal app?..If possible please guide me..
