### ISSUE TITLE
Prestashop 1.7

### ISSUE THREAD

**Issue by Dany2411** [VivaPayments/API#1440]
Hello,

End of transaction problem with pretashop e-commerce

It indicates a technical error has occurred, but the order is validated and the payment arrives well on Vivawallet, can you help us.
 
Have a good day

**Comment by matthewrgourd** [comment]
Hi @Dany2411 sorry to hear this. Can you send full details of any error messages (and your Merchant ID) to my email address (mgourd@vivawallet.com)? If you could reference this issue (#1440), that would be great.

**Comment by matthewrgourd** [comment]
Hi @Dany2411 , just to let you know that our development team has now completed extensive testing of the plugin. The conclusion is that it is working correctly. The problem therefore must be within your PrestaShop e-commerce settings. I wish you luck finding a solution but I'm afraid I can't help any further. Thanks...

**Comment by Dany2411** [comment]
Ok thanks, so I'm going to have to use another system.

I have the problem on 2 different eshops, neither you nor the vivawallet services have solutions.

So I have to go to another payment system.

thank you good luck




[cid:6814F0AC-DDC4-4910-B731-14599164741C]<http://www.citykart.com/>
Dany Michel
Administrateur délégué
City Kart SA
Phone : +32 2 219 17 47
Site : www.citykart.com
Mail : dmichel@citykart.com
Adress : 13, Rue Xavier De Bue - 1180 Uccle - Belgium
[cid:image002.png@01D5CE15.3D4477B0]<https://www.facebook.com/citykartforest/>

[signature_1363572525]<https://www.instagram.com/city_kart/>











De : matthewrgourd <notifications@github.com>
Répondre à : VivaPayments/API <reply@reply.github.com>
Date : mercredi 11 mars 2020 à 13:02
À : VivaPayments/API <API@noreply.github.com>
Cc : Dany Michel <dmichel@citykart.com>, Mention <mention@noreply.github.com>
Objet : Re: [VivaPayments/API] Prestashop 1.7 (#1440)


Hi @Dany2411<https://github.com/Dany2411> , just to let you know that our development team has now completed extensive testing of the plugin. The conclusion is that it is working correctly. The problem therefore must be within your PrestaShop e-commerce settings. I wish you luck finding a solution but I'm afraid I can't help any further. Thanks...

**Comment by matthewrgourd** [comment]
HI @Dany2411 sorry to hear this. I will reopen this case and raise with our developers again.

**Comment by Dany2411** [comment]
Hello,

It's been almost 10 months since we had a problem with the API for Prestahsop, you still haven't provided us with a solution for our 2 web shops.

We can no longer continue without an issue, each customer who orders on one of our 2 sites ends with a call because there is a bug at the end of each transaction.

In parts the screenshots, we have all filled in as written in your FAQ, but when the transaction is completed the customer receives an error page.

If no solution is found, we will have to interrupt your service, which is a shame because we also wanted to use it for our retail store.

Hoping to have an issuer soon.

Thank you
[cid:image002.png@01D6F036.05A79FA0]<http://www.citykart.com/>
Dany Michel
Administrateur délégué
City Kart SA
Phone : +32 2 219 17 47
Site : www.citykart.com<http://www.citykart.com>
Mail : dmichel@citykart.com<mailto:dmichel@citykart.com>
Adress : 13, Rue Xavier De Bue - 1180 Uccle - Belgium
[cid:image003.png@01D6F036.05A79FA0]<https://www.facebook.com/citykartforest/>

[signature_1363572525]<https://www.instagram.com/city_kart/>




De : Dany <dmichel@citykart.com>
Envoyé : mercredi 11 mars 2020 17:23
À : VivaPayments/API <reply@reply.github.com>; VivaPayments/API <API@noreply.github.com>
Cc : Mention <mention@noreply.github.com>
Objet : Re: [VivaPayments/API] Prestashop 1.7 (#1440)


Ok thanks, so I'm going to have to use another system.

I have the problem on 2 different eshops, neither you nor the vivawallet services have solutions.

So I have to go to another payment system.

thank you good luck




[cid:image013.png@01D6F036.05A79FA0]<http://www.citykart.com/>
Dany Michel
Administrateur délégué
City Kart SA
Phone : +32 2 219 17 47
Site : www.citykart.com<http://www.citykart.com>
Mail : dmichel@citykart.com<mailto:dmichel@citykart.com>
Adress : 13, Rue Xavier De Bue - 1180 Uccle - Belgium
[cid:image014.png@01D6F036.05A79FA0]<https://www.facebook.com/citykartforest/>

[signature_1363572525]<https://www.instagram.com/city_kart/>











De : matthewrgourd <notifications@github.com<mailto:notifications@github.com>>
Répondre à : VivaPayments/API <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : mercredi 11 mars 2020 à 13:02
À : VivaPayments/API <API@noreply.github.com<mailto:API@noreply.github.com>>
Cc : Dany Michel <dmichel@citykart.com<mailto:dmichel@citykart.com>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Objet : Re: [VivaPayments/API] Prestashop 1.7 (#1440)


Hi @Dany2411<https://github.com/Dany2411> , just to let you know that our development team has now completed extensive testing of the plugin. The conclusion is that it is working correctly. The problem therefore must be within your PrestaShop e-commerce settings. I wish you luck finding a solution but I'm afraid I can't help any further. Thanks...
