### ISSUE TITLE
x-viva-eventId 10096 with succesfully payment

### ISSUE THREAD

**Issue by kyrkonpmi** [VivaPayments/API#1441]
Hi there,

I have checked the online payment procedure by myself and i got back  x-viva-eventId 10096 but the payment completed succesfully. 

Regards,
Kyriakos Kontos
Prodromou & Makriyiannis Insurance

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear that you received back that [error code](https://developer.vivawallet.com/api-reference-guide/error-codes/) which means system malfunction. Can you let me have a bit more information? Are you testing on demo or in a live situation?

**Comment by kyrkonpmi** [comment]
Hi,
It was in live situation. All my details...


Order Code | 1849672022803306
-- | --
Timestamp | 28/02/2020 2:30:05 PM
Merchant Reference |  
Description for customer | Please fill the below form   with your credit card details to complete the payment.
Amount | 85.00 EUR
Tip Amount | 0.00 EUR
Paid to your wallet | 84.39 EUR
Channel / Source | Web Redirect / New pmi
Wallet | Primary [904689810038]
Tags |  
Transaction Id | b8aeec95-f31c-4f71-b526-c7c50411f0d1

Regards,

**Comment by matthewrgourd** [comment]
Hi @kyrkonpmi thanks for sending through those details. I'm removing some of the info. as this is a public forum. I checked your account and I can't give you any explanation as to why that happened except maybe it was a temporary blip?

**Comment by kyrkonpmi** [comment]
Thanks again for your answer. 
Can you please check all other similar succesfully transactions which x-viva-eventId our customers get?
What i want to check is if this was really a temporary blip or is something else.
Regards

**Comment by matthewrgourd** [comment]
Hi there, not sure how to track that. Will need to check with a developer and get back to you.

**Comment by matthewrgourd** [comment]
Hi @kyrkonpmi all other transactions received an event ID of "1000" which means "Transaction approved successfully". Hope this helps.
