### ISSUE TITLE
API Order details returns null data on Failed Transactions

### ISSUE THREAD

**Issue by maflo13** [VivaPayments/API#1442]
Hello, 

i have a redirect payment flow, and i am trying to record and verify the transaction details reason on  failing transactions

On some cases when i set a non valid (eg. expired credit card) the api call returns the full transaction details 
On other cases and on other non valid credit cards (eg. expired or different reasons) the transaction API details call looks null

For instance see the following ordercode 
https://www.vivapayments.com/api/transactions/?ordercode=3240326880272601

returns
{
    "Transactions": [],
    "ErrorCode": 0,
    "ErrorText": null,
    "TimeStamp": "2020-03-09T16:51:58.1261357+02:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": true
}

I should assume that i would get a full transaction entity and not a null one
On other failing transactions i get it fully, it looks like the null is returned only on some certain cases (and some certain invalid credit cards)

Is that normal on some non valid credit cards?
Please advise

thx

MF.

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Please send me your Merchant ID and business name quoting this issue (#1442). I will then be able to check your account. My email address is mgourd@vivawallet.com. Thanks!

**Comment by matthewrgourd** [comment]
Hi @maflo13 , thanks for sending through the requested details and sorry for my delayed reply. I've looked at a couple of your failed transactions and I see that at least one of them relates to the test card 4111 1111 1111 1111 in which case I believe it's expected behaviour to receive null data in the response.

**Comment by maflo13** [comment]
@matthewrgourd  thank you for your reply.
I would expect some kind of fail status and explanation at this reply, it would be possible that on certain cases we will not be able to properly guide and inform our clients on what happened to a transaction and what is the problem with the credit card.

Perhaps you should add a more thorough status on your API in the future

Anyway thanks , you can close the ticket
