### ISSUE TITLE
Second Shopify store in a different Currency

### ISSUE THREAD

**Issue by Salesoft01** [VivaPayments/API#1443]
Hello,

We have recently created a second Shopify store in a different Currency (Euro). Our original store is in GBP£.

I have followed the integration guide and successfully setup the payment gateway but when Shopify redirects to the VivaWallet payment screen it is displaying the price in GBP not Euros.

Here is an example:

1, Customer adds a product to the cart which is €29.99 (Euros).
2, They go through the checkout with the product displaying in Euros.
3, They click to Make Payment which opens up VivaWallet but it is showing £29.99 (GBP).

I have checked all the settings inside Shopify and all looks correct.

We still need our VivaWallet account to accept payments in GBP, but for the second store it needs to accept Euros.

Can someone please advise?

Thanks,

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Please send me your Merchant ID and business name quoting this issue (#1446) and I will investigate. My email address is mgourd@vivawallet.com. Thanks!

**Comment by Salesoft01** [comment]
> Hi there, sorry to hear this. Please send me your Merchant ID and business name quoting this issue (#1443) and I will investigate. My email address is [mgourd@vivawallet.com](mailto:mgourd@vivawallet.com). Thanks!

Thanks. I have just sent you an email

**Comment by matthewrgourd** [comment]
Hi @Salesoft01 I've checked your account and everything looks in order. The currency for your store is set on the Shopify side: https://developer.vivawallet.com/e-commerce-plugins/shopify/#store-currency. Viva Wallet supports EUR, GBP and RON. Hope this helps.

**Comment by Salesoft01** [comment]
Hi Matthew,

We have our store set to EUR but when redirecting to VivaWallet it is showing GBP.

![euro](https://user-images.githubusercontent.com/61982661/76402135-df325880-637a-11ea-8980-3de6347aa185.png)

We are a UK company who currently have a website taking payments in GBP. I have read on here that you can only accept payments in the same currency as set in your Viva account.

**Comment by matthewrgourd** [comment]
Hi @Salesoft01 I'm checking with our plugin developer. I'll get back to you soon.

**Comment by matthewrgourd** [comment]
The reply I've received is that the currency of the Shopify store must match the currency of the account (GBP in this case), and that it cannot work any other way.

**Comment by Salesoft01** [comment]
Thank you Matthew.
