### ISSUE TITLE
Utilizzo plugin woocommerce Wivavollet

### ISSUE THREAD

**Issue by KINGSGARDE** [VivaPayments/API#1444]
Ho inserito nella configurazione del plugin i parametri ID venditore, Chiave API e Chiave pubblica ma non
si attiva nessun bottone di collegamento.

**Comment by matthewrgourd** [comment]
Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Still waiting for your reply. Please close this issue if no longer a problem. Thanks...
