### ISSUE TITLE
WooCommerce - payment button missing

### ISSUE THREAD

**Issue by Mamarelis** [VivaPayments/API#1446]
Dear Sir / Madam

I am resposible for an eshop (WooCommerce) and I have installed (and activated) Viva Wallet Plugin (version 3.5.7)

- I use LIVE Merchant ID and API Key. 
- There is no input field for Public Key (So I do not use it)
- I have no Source Code so I use 8559
- Test Mode is not checked

I have one product in my cart (with price 0.10) and I choose Viva payment in checkout.

Sadly, payment button does not displayed and customers are not able to proceed on payment through viva wallet website.
![vivaButton missing](https://user-images.githubusercontent.com/44189264/76305458-d8014100-62cd-11ea-963b-a9b58449debb.JPG)

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Please send me your Merchant ID and business name quoting this issue (#1446) and I will investigate. My email address is mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
Hi @Mamarelis I've checked your account and you have no payment source set up for e-commerce. Please following the instructions below. "Step 1: Create a payment source" is particularly important.

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by Mamarelis** [comment]
We have followed your instructions and we have also changed linked account to primary.

 

 

 

cid:image001.png@01D6076B.C0D814D0

 

Unfortunately payment button still missing in checkout page

 

 

We have submit these changes almost 1 week before and we have not received any reply. 

 

We are looking forward to hearing from you.

**Comment by matthewrgourd** [comment]
@Mamarelis you need to follow the instructions given at https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ precisely.

**Comment by Mamarelis** [comment]
For one more time, I followed all steps and checked all submitted data. 

Also, I created the optional webhook (which I really dont know its purpose). 

 

Status is still pending. 

 

There are two things that I am not sure about: 

The 1st one is If I have to set Linked Wallet to Primary and

The 2nd is If I have to set status to active in webhook

**Comment by matthewrgourd** [comment]
Hi @Mamarelis sorry to hear you're still experiencing issues. In order for me to investigate further what your issue might be, please send through the following screenshots so I can investigate further:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
@Mamarelis one other thing that might help. I think you have to test with a bigger transaction than 0.10. I believe the plugin will only work with greater than 0.30.

**Comment by Mamarelis** [comment]
I will set the price to 0.50 but I am still wondering: 

 

Why status is pending all these days???

**Comment by matthewrgourd** [comment]
Hi @Mamarelis I believe you've missed out an installation step. You need to set up a separate [payment source](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#step-1-create-a-payment-source) in order to create a source code for use in the plugin. At the moment there is no connectivity between your website and our payment gateway. Hope this helps!
