### ISSUE TITLE
Getting error on Magento 2 while redirecting on viva wallet payment page

### ISSUE THREAD

**Issue by linnaeushealth** [VivaPayments/API#1448]
We have installed and configured Viva wallet on website but got following error on testing.

I have attached the screenshot of the plugin setting and also with error image.
![viva wallet error](https://user-images.githubusercontent.com/62015483/76307745-50add080-62c1-11ea-933a-0213dc1a61f8.png)
![viva wallet setting](https://user-images.githubusercontent.com/62015483/76307750-53102a80-62c1-11ea-8fa1-026212343287.png)

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Please send me your Merchant ID and business name quoting this issue (#1448) and I will investigate. My email address is mgourd@vivawallet.com. Thanks!

**Comment by linnaeushealth** [comment]
@matthewrgourd thank you for reply. 
I have just replied you on email provided.

Business name : Linnaeus Healthcare Ltd.

I am not sure to provide merchant ID on open platform so, I have just sent you all details over email.

Could you please confirm if you have received that or not?

Adam

**Comment by linnaeushealth** [comment]
> 
> 
> Hi there, sorry to hear this. Please send me your Merchant ID and business name quoting this issue (#1448) and I will investigate. My email address is [mgourd@vivawallet.com](mailto:mgourd@vivawallet.com). Thanks!

@matthewrgourd thank you for reply.
I have just replied you on email provided.

Business name : Linnaeus Healthcare Ltd.

I am not sure to provide merchant ID on open platform so, I have just sent you all details over email.

Could you please confirm if you have received that or not?

Adam

**Comment by matthewrgourd** [comment]
Hi Adam, thanks for sending those details through. I can't see any issues with your account. Looking at those settings you sent through it may be worth checking you entered the correct value for API key (see number 2 in screenshot below). 

![API_Access_annotated](https://user-images.githubusercontent.com/44943019/76526688-d66a8100-6465-11ea-83af-7b12c638e43e.png)

Beyond this, I suggest checking that you're looking at the correct instructions within our developer portal ([Magento 2.1-2.2](https://developer.vivawallet.com/e-commerce-plugins/magento2.1-2.2/) or [Magento 2.3](https://developer.vivawallet.com/e-commerce-plugins/magento2.3/).) Thanks!

**Comment by linnaeushealth** [comment]
@matthewrgourd I have compared all settings and all looks fine on my side but still getting following error on this page https://linnaeushealth.com/vivapayments/checkout/start

Please try to complete order on following link with credit card payment method and you can see this error.
https://linnaeushealth.com


1 exception(s):
Exception #0 (Exception): Notice: Trying to get property of non-object in /home2/linnaeushealth/public_html/app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 202

Exception #0 (Exception): Notice: Trying to get property of non-object in /home2/linnaeushealth/public_html/app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 202
<pre>#1 Ced\VivaPayments\Model\PaymentMethod->getPostHTML(&Magento\Sales\Model\Order\Interceptor#0000000029f100320000000030fba26a#) called at [app/code/Ced/VivaPayments/Controller/Checkout/Start.php:40]
#2 Ced\VivaPayments\Controller\Checkout\Start->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#3 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#4 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#5 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#6 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Ced/VivaPayments/Controller/Checkout/Start/Interceptor.php:26]
#7 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#) called at [vendor/magento/framework/App/FrontController.php:159]
#8 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#, &Ced\VivaPayments\Controller\Checkout\Start\Interceptor#0000000029f106ec0000000030fba26a#) called at [vendor/magento/framework/App/FrontController.php:99]
#9 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#10 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#11 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#12 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000029f105280000000030fba26a#, &Closure#0000000029f1050e0000000030fba26a#, &Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#13 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#14 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000029f105280000000030fba26a#, &Closure#0000000029f1050e0000000030fba26a#, &Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#15 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#16 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#17 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000029f104790000000030fba26a#) called at [vendor/magento/framework/App/Http.php:137]
#18 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#19 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#20 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000029f1049c0000000030fba26a#) called at [index.php:39]
</pre>

**Comment by linnaeushealth** [comment]
Hi @matthewrgourd I have compared all settings and all looks fine on my side but still getting error.

Could you please review and confirm our setting we have made some changes and update which one is correct.

Our new setting is now pending for approval. Please update us ASAP.
![image](https://user-images.githubusercontent.com/62015483/76735210-55103880-675c-11ea-9a5b-72c1e51f670b.png)

**Comment by matthewrgourd** [comment]
Hi @linnaeushealth, your payment source '1716' is active so no problem there. In the above settings you should have "Redirection/Native Checkout v2" selected (first radio button on the left). Second part of Success / Failure URLs should be "vivapayments/viva/callback" rather than "/vivapayments/viva/callback" (lost the leading forward slash). I hope that helps!

**Comment by linnaeushealth** [comment]
Hi @matthewrgourd  made required changes but still getting same error.

You need to go on website add product in basket>> complete checkout with credit card and you can see this error.
https://linnaeushealth.com
![image](https://user-images.githubusercontent.com/62015483/76756866-75e98580-677e-11ea-9928-2ae6b27886a0.png)

**Comment by linnaeushealth** [comment]
@matthewrgourd 
![image](https://user-images.githubusercontent.com/62015483/76757056-d24ca500-677e-11ea-8f22-15df6178ce34.png)

**Comment by matthewrgourd** [comment]
![Screenshot 2020-03-16 at 12 12 46](https://user-images.githubusercontent.com/44943019/76757435-7b939b00-677f-11ea-9379-a8d790c4ed69.png)

**Comment by linnaeushealth** [comment]
@matthewrgourd looking forward to hearing from you soon.

**Comment by linnaeushealth** [comment]
@matthewrgourd still waiting for your reply.

**Comment by matthewrgourd** [comment]
Hi @linnaeushealth sorry for the delay. In your settings can you try replacing all instances of `vivapayments.com` with `www.vivapayments.com`?

**Comment by linnaeushealth** [comment]
Hi @matthewrgourd  tried but same error.

it seems like php error could you please ask your developers to have a look on it please?

1 exception(s):
Exception #0 (Exception): Notice: Trying to get property of non-object in /home2/linnaeushealth/public_html/app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 202

Exception #0 (Exception): Notice: Trying to get property of non-object in /home2/linnaeushealth/public_html/app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 202
<pre>#1 Ced\VivaPayments\Model\PaymentMethod->getPostHTML(&Magento\Sales\Model\Order\Interceptor#000000000b2086120000000066499096#) called at [app/code/Ced/VivaPayments/Controller/Checkout/Start.php:40]
#2 Ced\VivaPayments\Controller\Checkout\Start->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#3 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#4 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#5 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#6 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/Ced/VivaPayments/Controller/Checkout/Start/Interceptor.php:26]
#7 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#) called at [vendor/magento/framework/App/FrontController.php:159]
#8 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#, &Ced\VivaPayments\Controller\Checkout\Start\Interceptor#000000000b20873b0000000066499096#) called at [vendor/magento/framework/App/FrontController.php:99]
#9 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#10 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#11 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:94]
#12 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#000000000b2084ff0000000066499096#, &Closure#000000000b2084d90000000066499096#, &Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#13 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#14 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#000000000b2084ff0000000066499096#, &Closure#000000000b2084d90000000066499096#, &Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#15 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#16 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#17 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000000b2085ae0000000066499096#) called at [vendor/magento/framework/App/Http.php:137]
#18 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#19 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#20 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000000b20854b0000000066499096#) called at [index.php:39]
</pre>

**Comment by linnaeushealth** [comment]
![image](https://user-images.githubusercontent.com/62015483/77060949-5a29ed80-69d1-11ea-928b-d99f6bdd2764.png)

**Comment by matthewrgourd** [comment]
@linnaeushealth check "OrderCode URL" field. It's still wrong. You need to put the `www` in there.

**Comment by linnaeushealth** [comment]
@matthewrgourd  done and returned with new error.

![image](https://user-images.githubusercontent.com/62015483/77068417-7ed89200-69de-11ea-8bd8-6ac6c1421806.png)

**Comment by linnaeushealth** [comment]
![image](https://user-images.githubusercontent.com/62015483/77068468-96177f80-69de-11ea-84d1-e3414591c900.png)

**Comment by linnaeushealth** [comment]
@matthewrgourd just want to share I noticed same error came up if hit this link in browser.
Gateway URL: https://www.vivapayments.com/newtransaction.aspx

**Comment by linnaeushealth** [comment]
@matthewrgourd  if we hit call back URL it also shows us error.
https://linnaeushealth.com/vivapayments/viva/callback

It seems something to do with magento 2 extension could you please have a look on this in detail please? As above errors also shows error in extension php file 
1 exception(s):
Exception #0 (Exception): Notice: Trying to get property of non-object in /home2/linnaeushealth/public_html/app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 202

**Comment by matthewrgourd** [comment]
Hi @linnaeushealth, I've just spotted that 'Gateway URL' should be `https://www.vivapayments.com/web/newtransaction.aspx` rather than `https://www.vivapayments.com/newtransaction.aspx` This may do the trick.

**Comment by linnaeushealth** [comment]
@matthewrgourd thank you so much for your help. It looks fine now and went on payment page.

Let us try to do some test transaction and will get back to you if we face any problem.
