### ISSUE TITLE
Integrating on to shopify isn't working

### ISSUE THREAD

**Issue by deezer123** [VivaPayments/API#1449]
when asked to add payment provider two options should pop up to allow me to add viva wallet to my shopify but neither are popping up.

**Comment by deezer123** [comment]
I get to step seven on the lists provided and nothing else happens, it doesn't redirect me to either page

**Comment by matthewrgourd** [comment]
Hi @deezer123 sorry to hear this. Bear with me and I'll come back to you...

**Comment by deezer123** [comment]
okay great

**Comment by deezer123** [comment]
I don't know if there is anyway to access the next page without the link

**Comment by matthewrgourd** [comment]
Hi @deezer123, I've looked into this and it appears the procedure for this has changed slightly. I will need to update the documentation. In the meantime, after step 7, please do the following:

1. On the 'Payment providers' page, scroll down to the 'Third-party providers' section and click on the **Choose third-party provider** button.
A list of supported payment providers is displayed.
2. Filter on Viva and select **Viva Wallet**.
The Viva Wallet settings page is displayed.
3. Under 'Account Information' enter your Merchant ID and Store Token in the fields provided.
4. Click on the **Activate Viva Wallet** button at the bottom of the page.

Hope this helps! Let me know if not...

**Comment by matthewrgourd** [comment]
Hi @deezer123 I've updated the documentation now. Please check https://developer.vivawallet.com/e-commerce-plugins/shopify/ in case any different from the above.
