### ISSUE TITLE
Πληρωμή με Μετρητά 

### ISSUE THREAD

**Issue by integrators** [VivaPayments/API#145]
Θέλουμε να χρησιμοποιήσουμε την υπηρεσία Πληρωμή με μετρητά στο website μας. 

- Που μπορούμε να βρούμε πληροφορίες για το API (ποια calls είναι για τη συγκεκριμένη υπηρεσία) και πως δουλεύει σε τεχνικό επίπεδο (δηλαδή πως ενημερωνόμαστε ότι έγινε η πληρωμή κ.λπ)? 
- Υπάρχουν κάποια παραδείγματα για τη χρήση του?

**Comment by dmihos** [comment]
Καλησπέρα σας

Για τις πληρωμές μετρητών, απαιτείται η δημιουργία ενός OrderCode (με την [CreateOrder](https://github.com/VivaPayments/API/wiki/CreateOrder)).
Φροντίστε, μόνο, να δίνετε αρκετό περιθώριο ([PaymentTimeout](https://github.com/VivaPayments/API/wiki/Optional-Parameters)), ώστε να προλαβαίνει ο πελάτης την εξόφληση.
Το μόνο που χρειάζεται να γνωρίζει ο πελάτης είναι το OrderCode για να μπορεί να το εξοφλήσει σε κάποιο σημείο.
Μπορείτε να ενημερώνεστε την ώρα της πληρωμής χρησιμοποιώντας τα [webhooks](https://github.com/VivaPayments/API/wiki/Webhooks).

Τα [samples](https://github.com/VivaPayments/API) περιλαμβάνουν παραδείγματα για CreateOrder και Webhooks.

Ευχαριστούμε,

**Comment by geolits** [comment]
Hello,

if we have a module that creates the gateway for vivapayment, so someone can pay with credit card through vivapayments.

We can use the same module so someone to can use the cash payment; Or it is needed to create a different module for this functionality;

The website will be informed somehow,that the cash pament took place;

Is there any full instructions how to implement the cash payment; 

Thank you

**Comment by dmihos** [comment]
Hi geolits

The usage of a 'module', and what it can do, depends on the module itself.

As described above, cash payments consist of the [Creation of an Order](https://github.com/VivaPayments/API/wiki/CreateOrder) and informing the client with the OrderCode. 
He can then use this code to pay in any [Viva Spot](https://members.vivawallet.com/el-gr/network).
You can use [webhooks](https://github.com/VivaPayments/API/wiki/Webhooks) to get informed about the payments, the second they are created.

Regards
