### ISSUE TITLE
Unable to complete payments on my Shopify e-commerce

### ISSUE THREAD

**Issue by Weedzardit** [VivaPayments/API#1450]
Hello, I'm using Viva Wallet since a few months with the same account on two Shopify e-commerces. I've no problem with one of the e-commerce but the system is not able to process the most of the payments on the other one. The website is www.theweedzard.com - I've personally tried to place two orders: one worked with American Express, another one did not work with master card.

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Please send me your Merchant ID and business name quoting this issue (#1450) and I will investigate. My email address is mgourd@vivawallet.com. Thanks!

**Comment by matthewrgourd** [comment]
Hi @Weedzardit I've checked your account and I see no issues at the Viva Wallet end. Suggest these are card problems (are they 3DS enrolled?) rather than anything related to your account or our plugin. Thanks.
