### ISSUE TITLE
Payment Being Declined

### ISSUE THREAD

**Issue by belsley** [VivaPayments/API#1452]
Hi there

The Shopify installation has all worked and the payment gateway is set up and live. However when i have tried to make a few payments online each time it says its been declined - I've tried a number of times with different debit and credit cards.

Any ideas?

Thanks

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Please send me your Merchant ID and business name quoting this issue (#1452) and I will investigate. My email address is mgourd@vivawallet.com. Thanks!

**Comment by Nanny1234** [comment]
Hi There, I have the same problem here, can you help?

**Comment by matthewrgourd** [comment]
Hi @Nanny1234 please raise as a separate issue to avoid any confusion with this one. You need to click on the **New Issue** button on our [GitHub issues home page](https://github.com/VivaPayments/API/issues).

**Comment by matthewrgourd** [comment]
Hi @belsley are you still experiencing issues? Did you send your details through as requested?
