### ISSUE TITLE
API failing 33% of the time via Wordpress. 

### ISSUE THREAD

**Issue by Plantandhemp1234** [VivaPayments/API#1453]
Users are entering all the card and information correctly and the first time it's failing.

When they try again it normally works but this isn't due to incorrect details it's an API problem returning a failure. 

Please help.

![working](https://user-images.githubusercontent.com/62068743/76435719-45d16980-63af-11ea-8a88-b22cef9c2f0b.png)
![not working](https://user-images.githubusercontent.com/62068743/76435731-4964f080-63af-11ea-877a-06063aa960f4.png)

**Comment by matthewrgourd** [comment]
Hi @Plantandhemp1234 what's your business name, please? I need to do some checks. Thanks.

**Comment by matthewrgourd** [comment]
Hi @Plantandhemp1234 I've advised you (via email) to change the expiration date field to four digits. Please try this. Thanks...

**Comment by matthewrgourd** [comment]
@Plantandhemp1234 if you continue experiencing issues I recommend you use our [Viva Wallet for WooCommerce plugin](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) rather than attempting to implement our payment gateway natively.
