### ISSUE TITLE
Woocommerce Live Payment Error [404 - File or directory not found.]

### ISSUE THREAD

**Issue by Lyngas** [VivaPayments/API#1454]
Hi there, 
What title says. All settings are correct in my side.  

![Screenshot_4](https://user-images.githubusercontent.com/5469648/76458104-b2199080-63e2-11ea-935e-ed03b9eb98b7.png)

here is the result page.

![Screenshot_5](https://user-images.githubusercontent.com/5469648/76458194-d6756d00-63e2-11ea-952f-05df13f6af3e.png)

**Comment by Lyngas** [comment]
Hi there, it was a typo from me that i resolve it. 
The Payment works perfect ! 

But .. after the succes payment the return page shows me that

![Screenshot_7](https://user-images.githubusercontent.com/5469648/76459530-09b8fb80-63e5-11ea-82c7-0329058e71a9.png)

How i can redirect customers in the right page ..? 

Thanks !
DEmetris

**Comment by Lyngas** [comment]
Well, i attach you also this screen with the return url that maybe help you. :)

![Screenshot_8](https://user-images.githubusercontent.com/5469648/76460035-ff4b3180-63e5-11ea-932f-29f426ca00ba.png)

**Comment by Lyngas** [comment]
Also, in my Woo backend I see **Pending payment** as status  and not **Completed** BUT the transaction works normal because i do the 3D Secure accept from my mobile app and i charged the cost. ! Weird  .. :/

![Screenshot_9](https://user-images.githubusercontent.com/5469648/76460924-9664b900-63e7-11ea-87d4-b7c052e39c74.png)

![Screenshot_10](https://user-images.githubusercontent.com/5469648/76461433-8f8a7600-63e8-11ea-85d8-6e191e88d5c9.png)

**Comment by matthewrgourd** [comment]
Hi @Lyngas I believe you've followed the incorrect instructions on our developer portal. You need to check the [WooCommerce page](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) rather than page for [WP eCommerce](https://developer.vivawallet.com/e-commerce-plugins/wpecommerce/). Correct Success / Failure URLs for WooCommerce plugin are below:

- index.php?wc-api=wc_vivawallet&vivawallet=success
- index.php?wc-api=wc_vivawallet&vivawallet=fail

Hope that helps!

**Comment by Lyngas** [comment]
Hi there, thank you for your reply Matthew .. 
Well, ok, i will check it again, but the other issue about , is that i pay , bank did the payment, vivawallet get the money, but the woocommerce cancel somehow the order !! 
![Screenshot_3](https://user-images.githubusercontent.com/5469648/76628206-0c326700-6545-11ea-8a57-ea7eed67ec76.png)
![Screenshot_2](https://user-images.githubusercontent.com/5469648/76628210-0d639400-6545-11ea-9abd-0caa0aa88f90.png)

**Comment by matthewrgourd** [comment]
Hi @Lyngas I can't advise you on the WooCommerce side of things I'm afraid. Best regards,
