### ISSUE TITLE
Need to add an chinese bank account but they dont have IBAN

### ISSUE THREAD

**Issue by thebestofnature** [VivaPayments/API#1455]
Dear team Viva Wallet. 
I would like to pays one of my provider in china, but the bank account does not have IBAN.
Just bank account and SWIFT.
How can i do it ?
Thanks
Kind regards Livio

**Comment by matthewrgourd** [comment]
Hi @thebestofnature, Viva Wallet supports transfers to IBAN accounts only. Apologies for any inconvenience caused.
