### ISSUE TITLE
Popup σε Viva payments demo account και Virtuemart

### ISSUE THREAD

**Issue by cvrak** [VivaPayments/API#1457]
Καλησπέρα,
Έχω στήσει ένα e-shop σε Joomla 3.9.15 & Virtuemart 3.6.10
Εχω φτιάξει μια μέθοδο πληρωμής test και έχω βάλει τα API από demo λογαριασμό Viva payments.
Όταν βάζω τα στοιχεία της demo καρτας και πριν την ολοκλήρωση της δοκιμαστικής παραγγελίας μου βγάζει το επισυναπτόμενο popup, με 2 επιλογές sucess & failure.
όταν επιλέξω sucess, γίνεται η δοκιμαστική πληρωμή.
Τί είναι αυτό το popup? Θα βγαίενι και στην κανονική λειτουργία?
Αν ναι, πώς γίνεται να μην εμφαν'ιζεται?

Ευχαριστώ
![vm_wallet_screen_01](https://user-images.githubusercontent.com/62111630/76620893-e1411680-6536-11ea-8791-b141269a301b.jpg)

**Comment by matthewrgourd** [comment]
Hi @cvrak the popup simulates 3DS during testing within the [sandbox](https://developer.vivawallet.com/getting-started/#sandbox-account). In the live situation, the real 3DS issuer popup is displayed. Hope this helps!

**Comment by cvrak** [comment]
Ok, I'll check the live and let you know

**Comment by matthewrgourd** [comment]
Hi @cvrak any particular reason why you've reopened this issue? Are you experiencing another problem now?

**Comment by cvrak** [comment]
Hi, 
Sorry, maybe clicked by mistake.

**Comment by matthewrgourd** [comment]
@cvrak no worries!
