### ISSUE TITLE
payment issu 

### ISSUE THREAD

**Issue by CBDBICYCLETTE** [VivaPayments/API#1458]
Good afternoon, 

Several customer told me that they were not able to finalise their order. they put their code of credit card and then nothing follow. Some of them get until the 3D secure but then white page appear and nothing else. 
Could you check what is wrong please ? 

here is my URL : https://cbdbicyclette.fr

I hope to hear from you soon. 
Best regards

morgan Ben Haim - CBD BICYCLETTE - morganbenhaim@gmail.com

![capture ecran pb paiement erwan](https://user-images.githubusercontent.com/60919906/76625613-ec487680-6537-11ea-9e70-2fb108c0809f.JPG)

**Comment by matthewrgourd** [comment]
HI @CBDBICYCLETTE sorry to hear that. I will need to test with a card with no funds. In the meantime, can you let me know the date and approximate time when the above blank 3DS window was produced. I can then check your account to see if it matches up with a failed transaction.

**Comment by CBDBICYCLETTE** [comment]
Hi, 

The last failed was yesterday at 11H19 am (that was is written on the screen shot). i have only one failed transaction, it was 13 of february. But several customers complain about this trouble. They all tried to order from a smartphone. 
Thank’s for your help. 
bye 
Morgan

**Comment by CBDBICYCLETTE** [comment]
Hello Matthew,

Any news about the issu payment ? I would like to set up an advertising campaign, but i have to be sure about the payment process reliability. 
thanks you. 
Best regard’s
Morgan

**Comment by matthewrgourd** [comment]
Hi @CBDBICYCLETTE as a test, I just tried to buy something with a card with no funds from my mobile. 3DS works fine and failed transaction shows up correctly on your account. If you used the card 4111 1111 1111 on 13th that's why it didn't work. Unfortunately the test cards don't work on production. If that answers your query, please close this issue.
