### ISSUE TITLE
Communication between VivaWallet & Virtuemart plugin

### ISSUE THREAD

**Issue by cvrak** [VivaPayments/API#1459]
Hi,
I've installed the VivaWallet plugin for Virtuemart (Joomla).
For every transcation, the order in Virtuemart is "pending", therefore no email is sent to vendor.
Can Vivawallet communicate with Virtuemart after the transaction, so the order is "Confirmed by client"?
Its important for the vendor to be informed for every order.

Thans

**Comment by matthewrgourd** [comment]
Hi @cvrak, is the Viva Wallet plugin for Virtuemart working in all other respects other than the transaction status message?

**Comment by cvrak** [comment]
Hi @matthewrgourd, Yes the plugin is working. Let me tell you its is sandbox mode.

**Comment by cvrak** [comment]
@matthewrgourd  probably the problem occured because of the demo version of the plugin. The live plugin works just fine!
Thanks!
