### ISSUE TITLE
payments failure

### ISSUE THREAD

**Issue by theolivetree123** [VivaPayments/API#146]
ΠΑΡΑΚΑΛΩ ΟΠΩΣ ΕΛΕΞΕΤΕ ΤΟ ΚΟΜΜΑΤΙ ΤΩΝ ΠΛΗΡΩΜΩΝ .
ΜΟΛΙΣ ΔΟΚΙΜΑΣΑ ΜΕ ΤΗΝ ΚΑΡΤΑ ΜΟΥ ΚΑΙ Η ΠΛΗΡΩΜΗ ΑΠΕΤΥΧΕ

**Comment by krakenrules** [comment]
Γεια σας,

Θα θέλαμε να μας δώσετε περισσότερες πληροφορίες για το θέμα που έχετε όπως σε ποιο περιβάλλον (παραγωγής ή demo) έχετε πρόβλημα με την κάρτα σας καθώς και το λάθος που εμφανίζεται.

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by theolivetree123** [comment]
Έχω το κοματι τις πληρωμής σε εσάς .The Olive Tree.com         δεν   περνάνε οι πληρωμές
