### ISSUE TITLE
on line payments

### ISSUE THREAD

**Issue by chgl48** [VivaPayments/API#1460]
Let me know the necessary code to include it in my site in order to create a payment llink with my account with vivawallet*. I am also interested the "installments choice" to be included. 
*(To use this facility we need to give you access to our Simple Checkout API. Simply raise an issue on our public GitHub to this effect. We will ask you for a bit more information about your company before granting you the necessary privileges.https://developer.vivawallet.com/online-checkouts/simple-checkout/ )

**Comment by matthewrgourd** [comment]
Hi @chgl48, no problem, please email me with your business name and Merchant ID, quoting this issue (#1460). I will then switch on the API for you.

**Comment by chgl48** [comment]
Hi,My: Business name: ΧΑΡΑΛΑΜΠΟΣ ΛΥΡΙΤΖΗΣ with Merchant ID: 6f63cf67-1341-4bd6-a430-aa13851c3074Can you adviseto me  the completion correctly of the attached file code?Regards@chgl48

 
 
-----Original Message-----

**Comment by matthewrgourd** [comment]
Hi @chgl48 your production account is already enabled. If you wish to test first using the demo environment, please send me that Merchant ID also. By the way, for security reasons, I'm obscuring some of the characters of the above Merchant ID as it is your live account and I meant for you to email it. Sorry for any confusion!

**Comment by chgl48** [comment]
where can I test the demo, in my site pragmatognomon.com?


-----Original Message-----

**Comment by matthewrgourd** [comment]
Hi @chgl48 your site is already live so probably easier to use production for any testing.

**Comment by chgl48** [comment]
6f63cf67-1341-4bd6-a430-aa13851c3070
To check demo
Thx
Χ.Λυριτζής
On Τρίτη, Μαρτίου 17, 2020 matthewrgourd <reply@reply.github.com> wrote:



Hi @chgl48 your production account is already enabled. If you wish to test first using the demo environment, please send me that Merchant ID also. By the way, for security reasons, I'm obscuring some of the characters of the above Merchant ID as it is your live account and I meant for you to email it. Sorry for any confusion!
