### ISSUE TITLE
Unable to capture payments - live account issue

### ISSUE THREAD

**Issue by alekseykuleshov** [VivaPayments/API#1461]
Hello,

The issue started to happen to our production account. Capture payment requests are failing now with "Preauth has expired or already captured" error. They were captured successfully before with no problem. 

Also, we miss the ability to capture the payments in wallet account, see the screenshot:
<img width="1301" alt="Screenshot2" src="https://user-images.githubusercontent.com/6037974/76734981-15097f80-6775-11ea-8b67-5abf034bade9.png">

We have the ability to capture payments in demo account, see screenshot:
<img width="1298" alt="Screenshot1" src="https://user-images.githubusercontent.com/6037974/76735074-3a968900-6775-11ea-92bc-638286ecf84a.png">
So we expect to have it in live account as well. We are sure it was there before. 

The transactions on demo account are captured successfully via API too, using the 100% same code.

Could you please identify what's happened to live account? We can not capture payments and it's a big issue. Live API Merchant ID is a0dff9f5-d976-44be-bbe2-d09b2469439e and Source Code is 8664. 

Please let me know if you need anything else from me. We really need to have this resolved.

Thank you,
Alex

**Comment by alekseykuleshov** [comment]
No response in 3 days? It's issue on production and real money to be received for real service.

@matthewrgourd Could you please check this? @kostGX you helped me a year ago while integrating this, could you please have a look to issue?

**Comment by matthewrgourd** [comment]
@alekseykuleshov sorry for the lack of reply. We're looking into this now.

**Comment by matthewrgourd** [comment]
Hi @alekseykuleshov apparently you're attempting to use v1 of our Native Checkout which has been superseded by v2. Please follow the guide below:

https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

**Comment by alekseykuleshov** [comment]
@matthewrgourd Does that means V1 does not work any longer?

**Comment by matthewrgourd** [comment]
@alekseykuleshov that's correct, yes.
