### ISSUE TITLE
Can't accept payments with Shopify

### ISSUE THREAD

**Issue by TimJohnson83** [VivaPayments/API#1462]
Hi

So I have viva installed on my Shopify store, I have put my merchant Id in and store token which I believe is the api key? However when I tried to my buy my product as a test run it  redirected me to viva and said input invalid?

Ay help please?

**Comment by matthewrgourd** [comment]
Hi @TimJohnson83 you need to request the store token via [this online form](https://viva.microsoftcrmportals.com/shopify) as outlined in our [plugin installation instructions](https://developer.vivawallet.com/e-commerce-plugins/shopify/) (under 'Prerequisites'). Thanks.

**Comment by TimJohnson83** [comment]
Hi, Do you know how long this takes please? I filled in the form yesterday and heard nothing back?

**Comment by matthewrgourd** [comment]
Hi @TimJohnson83 have you received your token yet?

**Comment by TimJohnson83** [comment]
not yet

**Comment by matthewrgourd** [comment]
Hi @TimJohnson83, sorry for the delay. We're having an issue with our automated processes. Please can you send through the below details manually to my email: mgourd@vivawallet.com and I'll get this done for you as soon as possible. Thanks!

- Full name
- Email address
- Phone number
- Viva Wallet Merchant ID
- Shopify store name
- Shopify store URL

**Comment by matthewrgourd** [comment]
Hi @TimJohnson83 I checked and apparently our online form for requesting the token isn't currently working so you need to send through those details I requested above, again. I can then immediately issue you with a token. Apologies for any inconvenience caused!

**Comment by TimJohnson83** [comment]
Hi

Thank you.

Timothy Johnson

hello@loveaftermidnight.co.uk

07949 469367

106410a3-6537-408a-977c-98fc69ca5cb7

https://the-kandy-pot.myshopify.com/

thekandypot.co.uk


Thank you

**Comment by matthewrgourd** [comment]
Hi @TimJohnson83 I've put that request in for you. Please let me know if you don't receive a token by the end of the day. By the way, for security reasons, I'm going to remove the company details you sent me from GitHub. Thanks!

**Comment by TimJohnson83** [comment]
Hi,

Still heard nothing.

**Comment by matthewrgourd** [comment]
@TimJohnson83 let me check for you. Apologies for the delay.

**Comment by matthewrgourd** [comment]
@TimJohnson83 you should have it now. Please let me know if not...

**Comment by TimJohnson83** [comment]
Nope still nothing Matthew.

**Comment by TimJohnson83** [comment]
Hi Matthew,

Thank you received the code, however is it normal that when I tried doing a payment myself to test its takes you to a viva payments page,
![Screenshot 2020-03-31 at 12 08 13](https://user-images.githubusercontent.com/62242858/78020030-969e0780-7348-11ea-8b38-00bb5d2fa9af.png)
 or is it possible to do a payment without leaving Shopify if that makes sense?

**Comment by matthewrgourd** [comment]
Hi @TimJohnson83, this is how our integration works, through a redirect. At present there is no 'native' option available between Shopify and Viva Wallet.
