### ISSUE TITLE
erreur store not found

### ISSUE THREAD

**Issue by XavDelta** [VivaPayments/API#1463]
Bonjour,
error store not found pour paiement VivaWallet sur store shopify, après avoir suivi l'ensemble des instructions.
Problème après validation des informations client vers page paiement. 
Merci pour vos réponses.

**Comment by matthewrgourd** [comment]
Hi there, please check out these responses in case they may help you:

https://github.com/VivaPayments/API/issues?q=is%3Aissue+is%3Aclosed+store+not+found+label%3Ashopify

If you're still having problems after that, please let me know. Thanks!

**Comment by XavDelta** [comment]
Hello,
The different answers could not help me, the problem persists.
I followed the directions, fill in the merchant ID, the Store token, deactivated the test mode, and choose a currency compatible with vivawallet (€).
It still doesn't work, store not found ...
Do you see where the problem may come from?
Thanks for your feedback.
Bonjour,Les differentes réponses n'ont pas pu m'aider, le problème persiste.J'ai bien suivi les indications, remplir le merchant ID, le Store token, désactivé le mode test, et choisir une devise compatible avec vivawallet (€).Cela ne fonctionne toujours pas, store not found...Voyez vous d'ou peut venir le problème?Merci pour votre retour.
Xavier TEYSSIER
Tel : +33 (0)7 82 12 20 36
xtnice@yahoo.fr 

    Le mardi 17 mars 2020 à 09:38:38 UTC+1, matthewrgourd <notifications@github.com> a écrit :  
 
 


Hi there, please check out these responses in case they may help you:

https://github.com/VivaPayments/API/issues?q=is%3Aissue+is%3Aclosed+store+not+found+label%3Ashopify

If you're still having problems after that, please let me know. Thanks!

**Comment by matthewrgourd** [comment]
Hi @XavDelta sorry to hear you're still experiencing difficulties. This problem is usually to do with incorrect identification of merchant ID / store token. To help you out, here are examples of what these should look like:

- Merchant ID: fbf1e090-65de-4c75-b580-d9d9bc494ad2
- Store token: eV!GeBYyx7x^WK3mfi8m!0glbkooxIWJ

I assume you've received a store token from us already?

**Comment by XavDelta** [comment]
I have entered the right information for the Merchand ID and the Store Token, but it still does not work, store not found ...I don't understand why it doesn't work, see where the problem may come from. 
My API key is only 30 characters long and not 32, is this normal?
Thanks in advance.
Xavier TEYSSIER
Tel : +33 (0)7 82 12 20 36
xtnice@yahoo.fr 

    Le mardi 17 mars 2020 à 11:58:58 UTC+1, matthewrgourd <notifications@github.com> a écrit :  
 
 


Hi @XavDelta sorry to hear you're still experiencing difficulties. This problem is usually to do with incorrect identification of merchant ID / store token. To help you out, here are examples of what these should look like:
   
   - Merchant ID: fbf1e090-65de-4c75-b580-d9d9bc494ad2
   - Store token: eV!GeBYyx7x^WK3mfi8m!0glbkooxIWJ

I assume you've received a store token from us already?

**Comment by matthewrgourd** [comment]
@XavDelta in order to request your store token, please complete [this online form](https://viva.microsoftcrmportals.com/shopify) as mentioned in our [installation instructions](https://developer.vivawallet.com/e-commerce-plugins/shopify/). Your API key is not of relevance here.

**Comment by XavDelta** [comment]
I made the request for API key via the form that you joined me, I await the return of vivawallet.

Xavier TEYSSIER
Tel : +33 (0)7 82 12 20 36
xtnice@yahoo.fr 

    Le mardi 17 mars 2020 à 13:56:40 UTC+1, matthewrgourd <notifications@github.com> a écrit :  
 
 


@XavDelta in order to request your store token, please complete this online form as mentioned in our installation instructions. Your API key is not of relevance here.

**Comment by matthewrgourd** [comment]
Hi @XavDelta, apparently there's currently an issue with store token requests and we're looking into it. I'll let you know once I've an update. Thanks!

**Comment by leogravelin** [comment]
Hi @matthewrgourd Any news about store token ?

**Comment by XavDelta** [comment]
Hello,
No I still haven't heard from the store token, I haven't received anything
 

    Le mercredi 18 mars 2020 à 11:00:08 UTC+1, leogravelin <notifications@github.com> a écrit :  
 
 


Hi @matthewrgourd Any news about store token ?

**Comment by matthewrgourd** [comment]
Hi @XavDelta apologies, we're still looking into the issue. In the meantime, I believe I may be able to manually request one for you. Please send the following details through to me at mgourd@vivawallet.com. Thanks! 

- Full name
- Email
- Phone
- Merchant ID
- Shopify store name
- Shopify store URL

**Comment by matthewrgourd** [comment]
Hi @XavDelta did you receive your store token in the end? Thanks.

**Comment by XavDelta** [comment]
Yes is good thanks.

Xavier TEYSSIER 
Envoyé de mon iPhone
