### ISSUE TITLE
in Redirect chekout ,allow recurring =true, after some transaction customer want to disable the allow recuring , how to do that?

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1464]
hi,
 in redirect checkout, i tried allow recurring =true,
after that i made tick mark, payment order created & transaction id came, made  some recuring payments .customer wants to use another card, so he wants to cancel the allow recurring.

how to do disable the allow recurring after some successfull transactions?

**Comment by matthewrgourd** [comment]
Hi @chennurubharath I can't quite visualise the steps your customer(s) must have taken so far to get to this point. Can you show me an example, e.g. the website you're using to take payments? Please send through as much information as possible including request / response logs if relevant. Obviously blur out any confidential information. Thanks!

**Comment by matthewrgourd** [comment]
Closing as no reply...
