### ISSUE TITLE
Store token never sent

### ISSUE THREAD

**Issue by leogravelin** [VivaPayments/API#1469]
Hi 

I have a problem to link shopify account. I have a permanent error of "Store not Found" after the basket validation on my shopify cms.

I have the Merchant ID but never received the store token. Could you please help me ?

name of account HEMP SAS
website : https://thehemp.today/fr

**Comment by matthewrgourd** [comment]
Hi @leogravelin sorry to hear this. I've put in a request with the details you sent. Let me know if you don't receive the token by the end of today...
