### ISSUE TITLE
Πρόβλημα λειτουργίας δόσεων στο allaboutprint.gr 

### ISSUE THREAD

**Issue by ftsakonitis** [VivaPayments/API#147]
Magento website με module σύνδεσης με εσάς,  αντιμετωπίζω υμένας πρόβλημα με τις δόσεις. Φαίνεται σαν να μην έχουν ενεργοποιηθεί δόσεις στο συγκεκριμένο account. Εμείς σαν site δεν βλέπουμε κάποιο θέμα.

**Comment by defilerc** [comment]
Καλησπέρα @ftsakonitis ,

Για να μπορέσει ο χρήστης να επιλέξει τον αριθμό των δόσεων, θα πρέπει πρώτα να βάλει τον αριθμό της κάρτας του και στη συνέχεια θα του εμφανιστεί η επιλογή για τον αριθμό των δόσεων.

Ευχαριστούμε πολύ.

**Comment by ftsakonitis** [comment]
Καλησπέρα @defilerc ,

Ευχαριστώ πολύ για την ανταπόκριση. Δυστυχώς όμως, παρότι προσθέτω τον αριθμό της κάρτας μου, δεν ανοίγει το πεδίο των δόσεων. Καταφέρατε με κάποιο τρόπο να δείτε εσείς την επιλογή των δόσεων;

Ευχαριστώ εκ των προτέρων.

**Comment by defilerc** [comment]
Καλησπέρα @ftsakonitis ,

Θα πρέπει επίσης, κατά τη δημιουργία του Order, να περάσετε την παράμετρο MaxInstallments. Δείτε τη σελίδα [εδώ](https://github.com/VivaPayments/API/wiki/CreateOrder) για περισσότερες πληροφορίες.

Ευχαριστούμε πολύ.

**Comment by ftsakonitis** [comment]
Καλησπέρα @defilerc ,

αυτό είναι κάτι που έτσι κι αλλιώς κάνουμε μέσα από το module.

Ευχαριστώ πολύ

**Comment by defilerc** [comment]
Καλησπέρα @ftsakonitis ,

Απ' ότι βλέπουμε, τα orders που έχετε δημιουργήσει μέσα στο 2016, είναι με την επιλογή MaxInstallments = 0. Επομένως, εκεί είναι το πρόβλημα.

Ευχαριστούμε πολύ.
