### ISSUE TITLE
Simple Checkout API

### ISSUE THREAD

**Issue by Cannatheque** [VivaPayments/API#1470]
Hello, 

I'm installing Viva Wallet into a customer woocommerce website. 
I've installed the plugin for woocommerce and setup the website in the Websites/Apps at the Wallet.

When ordering something, I'm having this Server Error: 
> https://www.vivapayments.com/web/checkout?ref=3.1067712514813E+15
> 404 - File or directory not found.
> The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

I guess I need to use the Simple Checkout API. 
Could you please help me?

<img width="500" alt="Screenshot 2020-03-17 at 18 14 48" src="https://user-images.githubusercontent.com/62302211/76882709-584e1600-687b-11ea-9d4e-05891568be96.png">
<img width="969" alt="Screenshot 2020-03-17 at 18 13 56" src="https://user-images.githubusercontent.com/62302211/76882719-5ab07000-687b-11ea-84e6-23e9709a05a2.png">

**Comment by matthewrgourd** [comment]
Hi @Cannatheque sorry to hear you're having problems. Can you first of all let me know if you downloaded our plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ ? Download link is https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip Thanks

**Comment by matthewrgourd** [comment]
Hi @Cannatheque I'm sorry, the module fields for the plugin don't match our official extension. You need to uninstall what you have under WooCommerce plugins and follow the [guide](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) provided on our developer portal.
