### ISSUE TITLE
ECR Support_ How to perform TCP communication with device/PC and A920 ?

### ISSUE THREAD

**Issue by Darniss** [VivaPayments/API#1471]
Hi !.. I am having device A920. Is it possible to send request from my webpage to the device terminal app?..If possible please guide me..

**Comment by matthewrgourd** [comment]
Hi @Darniss, please see https://developer.vivawallet.com/pos-api-integration/. Let me know if that helps at all.

**Comment by Darniss** [comment]
Hi @matthewrgourd , I have already read that documentation there they have mention about the migration.It didn't help me.Please confirm me  Is it possible to send request from my webpage to the device terminal app?.  If not I have to find other alternative solution.

**Comment by matthewrgourd** [comment]
Hi @Darniss that specific scenario within the Viva Wallet environment is not supported, I'm afraid.
