### ISSUE TITLE
issues with checkout of imanager 

### ISSUE THREAD

**Issue by enzodipalma** [VivaPayments/API#1472]
Hi Matt Gourd, the CEO of imanager just wrote me that they have a lot of problems with our checkout. It register the transaction but not the order. Consumers pay but then the order is not closed on shopify, so there is the payment but not the order. moreover the checkout is very very slow, he asked me to accelerate the server and the system. could you pls check it asap, very very urgent pls? tks

**Comment by matthewrgourd** [comment]
Hi @enzodipalma sorry to hear that. Could I have the Shopify store name, please, and dates / times for some of the transactions referred to? (when the problem was experienced.)

**Comment by enzodipalma** [comment]
Hi Matt
Here you are:

[cid:image004.jpg@01D5FD3F.595C8420]

Enzo Di Palma
Country  Manager

Viva Wallet Italian Branch
Mobile 340 2169162
Phone 02 87369240
Mail edipalma@vivawallet.com<mailto:edipalma@vivawallet.com>
Web Site www.vivawallet.com

[cid:image003.png@01D5FD3F.57CFA290]

By Viva Payments SA, EEA-31 Region licensed e-money Institution

Disclaimer: This email contains confidential and privileged material for the sole use of the intended recipient. Any review or distribution by others is strictly prohibited. If you are not the intended recipient please contact the sender and delete all copies

**Comment by matthewrgourd** [comment]
Hi @enzodipalma image didn't come through. Please just let me have his store url asap, thanks.

**Comment by enzodipalma** [comment]
Done by teams:
6017
Justmary Shopify
Web
Public
True
Active
0
True


Enzo Di Palma
Country  Manager

Viva Wallet Italian Branch
Mobile 340 2169162
Phone 02 87369240
Mail edipalma@vivawallet.com<mailto:edipalma@vivawallet.com>
Web Site www.vivawallet.com

[cid:image001.png@01D5FD40.7A9ECF20]

By Viva Payments SA, EEA-31 Region licensed e-money Institution

Disclaimer: This email contains confidential and privileged material for the sole use of the intended recipient. Any review or distribution by others is strictly prohibited. If you are not the intended recipient please contact the sender and delete all copies

**Comment by matthewrgourd** [comment]
Hi @enzodipalma, thanks. Please get him to check his store status using the following link: https://shopifystatus.com/

**Comment by matthewrgourd** [comment]
Then, for each additional store he wants to set up, he should follow our guide from [Setup instructions](https://developer.vivawallet.com/e-commerce-plugins/shopify/#setup-instructions) onwards but using the same key each time. He should not manually add any new payment sources (the one I already mentioned via Teams has to be removed).

**Comment by matthewrgourd** [comment]
If all else fails, he can also check with Shopify in case there's an issue at their end!

**Comment by matthewrgourd** [comment]
Regarding notifications, as our payment gateway's integration with Shopify is non-native, they will never be fully in sync.
