### ISSUE TITLE
The primary account is showing pending

### ISSUE THREAD

**Issue by DavidNatures** [VivaPayments/API#1473]
Hi the primary account is showing pending and has been for 5 days the default account is showing active although on the dashboard the note is showing account verified. When I try to test my WooCommerce cart it states there is a critical error.
<img width="1440" alt="Screenshot 2020-03-17 at 23 04 03" src="https://user-images.githubusercontent.com/62347972/76983616-9f004680-6935-11ea-8a6e-ef3a33b2a64f.png">

<img width="1440" alt="Screenshot 2020-03-18 at 16 29 48" src="https://user-images.githubusercontent.com/62347972/76983722-c9520400-6935-11ea-9a6f-51b1f36c363c.png">

**Comment by matthewrgourd** [comment]
Hi @DavidNatures sorry to hear this. Have you received any emails from us? Maybe in your spam. We probably need you to make some changes before we can make the payment source active. If not please email me (mgourd@vivawallet.com) with your business name and Merchant ID and I will chase. Thanks!

**Comment by DavidNatures** [comment]
Hi thank you for your reply, it has now been sorted.

Regards
