### ISSUE TITLE
Woocommerce: Redirect page after payment "Nothing found" 

### ISSUE THREAD

**Issue by Lyngas** [VivaPayments/API#1474]
Hi there, after the payment , the plugin redirect me to woocommerce page with this message:  "Nothing found" 
But the payment created successful , the money goes to vivawallet account , email sent both in to customer, and merchant.

![Screenshot_2](https://user-images.githubusercontent.com/5469648/77061367-cb25d100-69e2-11ea-8f24-5fbd37c9471f.jpg)

Here is The backend screenshots:

![Screenshot_](https://user-images.githubusercontent.com/5469648/77062434-8a2ebc00-69e4-11ea-8bfd-848e14469fff.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/5469648/77062562-c7934980-69e4-11ea-97f4-3188f7b98d15.jpg)

**Comment by matthewrgourd** [comment]
Hi @Lyngas sorry to hear this. What is the business name, please? I need to check the transactions. Thanks!

**Comment by Lyngas** [comment]
I must to post it here ? public ? or you have any email or something.

**Comment by Lyngas** [comment]
Here is the VAT number 
` 106481272 ` 
Is that ok, or you need the name ..? the business name is the same as the real name. if you need it please tell me to send it you in some e mail. or what you prefer.

**Comment by matthewrgourd** [comment]
Hi @Lyngas, please email me your Viva Wallet Merchant ID: mgourd@vivawallet.com Thanks!

**Comment by matthewrgourd** [comment]
Hi @Lyngas thanks for sending through the requested info. Everything looks like it’s set up correctly as long as the source code you’re specifying in the WooCommerce settings is “4529”. The only thing that might be worth trying is removing the “www.” from the domain name field in the payment source so you have “amazareti.gr” instead of “www.amazareti.gr” but I’m not sure why this should make any difference. I assume you’ve downloaded the latest version of our plugin from the Viva Wallet for WooCommerce [installation guide](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/)? Failing any of these suggestions, the issue must be on the WooCommerce side. Thanks.

**Comment by Lyngas** [comment]
Hi   @matthewrgourd ,  Thank you for the reply.. yes i use the latest version "Vivawallet v3.5.7"
well, let me try with the www option..  and then i will back.

**Comment by Lyngas** [comment]
Yes, is 4529 the source code  ..

**Comment by Lyngas** [comment]
Hi Matthew,
Here is the Debug log:
`Fatal error: Uncaught Exception: Unable to create order code (The merchant with id 11765f33-6bd7-4255-accb-bdb95c126d69 does not have a source with code '4529' assigned or the source is disabled) in /home/amazareti/public_html/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php:343 Stack trace: #0 /home/amazareti/public_html/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php(453): WC_VIVAWALLET->generate_form(2820) #1 /home/amazareti/public_html/wp-includes/class-wp-hook.php(288): WC_VIVAWALLET->receipt_page(2820) #2 /home/amazareti/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array) #3 /home/amazareti/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #4 /home/amazareti/public_html/wp-content/plugins/woocommerce/templates/checkout/order-receipt.php(44): do_action('woocommerce_rec...', 2820) #5 /home/amazareti/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(249): include('/home/amazareti...') #6 /home/amazareti/public_html/wp- in /home/amazareti/public_html/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php on line 343`

**Comment by Lyngas** [comment]
Hi Matthew, update. The payment somehow was "pending" in vivavallet backend, and today back to active again.

So try it again and i get the same error :
`Search Results - 6799783309772608
HOME
SEARCH - 6799783309772608
Nothing Found
Sorry, but nothing matched your search terms. Please try again with different keywords.`
here is the redirect page url:
`https://www.amazareti.gr/index.php?wc_api=wc_vivawallet&vivawallet=success&t=2e847262-c276-4511-8953-d22ad1408fb0&s=6799783309772608&lang=el-GR&eventId=0&eci=1`

here is a screenshot of the page 
![Screenshot_1](https://user-images.githubusercontent.com/5469648/77227147-b2eeb700-6b86-11ea-9400-5f44bc094aad.jpg)

**Comment by polcbd** [comment]
Hello,
I'm having exactly the same issue. I'm guessing that it has to be with the permalinks or webhooks. 
I'm using the official plugin but I've seen that in the alternative plugin available in the wordpress repositories they offer two alternatives for Success/Failure URL depending on if you are using permalinks or not. I don't see that option in the plugin from Viva. 
Thanks in advance.
