### ISSUE TITLE
Shopify : Problem with 3D secure

### ISSUE THREAD

**Issue by Daex75** [VivaPayments/API#1476]
Hello
I am contacting you because I have a small problem with vivawallet, my customers who pay with 3D secure receive an SMS to enter their security codes, but my real name appears in the SMS instead of my company name.
How can I fix this? 
Thank you in advance

**Comment by matthewrgourd** [comment]
Hi @Daex75 not sure why that is – maybe something to do with your account settings? If you can send through your Viva Wallet Merchant ID to mgourd@vivawallet.com I'll take a look.

**Comment by matthewrgourd** [comment]
I've not received a reply back from you – did you email with your Merchant ID? P'raps if you could just share your company web address? Thanks!

**Comment by matthewrgourd** [comment]
Closing as no reply from customer
