### ISSUE TITLE
Need simpleCheckout API acces.

### ISSUE THREAD

**Issue by peorthyr** [VivaPayments/API#1477]
Good morning, I need the simplecheckout demo environment access to develop a simplecheckout flow on a website.
Thanks in advance.

**Comment by matthewrgourd** [comment]
Sure, please let me have the Viva Wallet Merchant ID for your demo account. Thanks!

**Comment by peorthyr** [comment]
4dc21ea8-fd02-4332-b455-a7db06476049

Sorry the delay. thanks in advance!

**Comment by matthewrgourd** [comment]
Hi @peorthyr I've enabled that now! Thanks.

**Comment by peorthyr** [comment]
thanks a lo guys! good job! 🍡
