### ISSUE TITLE
woocommerce subscriptions

### ISSUE THREAD

**Issue by despsym** [VivaPayments/API#1478]
Hello. I would like to create an e-learning platform where I can receive automatic monthly payments from my clients. The plugin I want to use is the **woocomerce subcriptions**. So I'd like to know if viva is compatible with this plugin or not. Ιf not can you suggest some way for me to have subscribers who automatically renew their subscription without having to enter their details over and over again?

**Comment by matthewrgourd** [comment]
Hi @despsym, you can develop a plugin or modify an existing plugin to fit your needs: https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/post

**Comment by despsym** [comment]
Hello. Is there anything new about the integration of vivawallet and woocommerce subscriptions? I was informed by mail (several months ago) about the integration but since then I don't have any news.

**Comment by matthewrgourd** [comment]
Hi @despsym it will be available in Oct/Nov is my best estimate. There are a number of improvements planned for our WooCommerce plugin. We're just about to release a native version for phase 2, but subscriptions won't be until phase 6 unfortunately.
