### ISSUE TITLE
αγγλικα στο checkout

### ISSUE THREAD

**Issue by vovosm7** [VivaPayments/API#148]
Καλησπέρα σας. Το eshop rdpharmacy.gr   είναι δίγλωσσο.  Όταν κάποιος κάνει παραγγελία με αγγλικά και επιλέγει να κάνει pay με **Credit Card / Debit Card (Viva Payments)** τότε η φόρμα που εμφανίζεται από τη viva είναι στα ελληνικά.  Πως θα μπορούσα να το κάνω να εμφανίζεται η φόρμα στα αγγλικά
επισυνάπτω και εικόνες
![rdpha](https://cloud.githubusercontent.com/assets/20646805/17110587/64c6b138-52a6-11e6-8242-7c715cb9a071.PNG)
![1](https://cloud.githubusercontent.com/assets/20646805/17110588/64d13acc-52a6-11e6-920b-26416bd953de.PNG)

**Comment by krakenrules** [comment]
Γεια σας,

Για να αλλάξετε τη γλώσσα θα πρέπει κατά τη δημιουργία του κωδικού πληρωμής στην CreateOrder να περάσετε και την παράμετρο RequestLang με τιμή "en-US" (https://github.com/VivaPayments/API/issues/119)
Περισσότερα για τις παραμέτρους θα βρείτε στο https://github.com/VivaPayments/API/wiki/Optional-Parameters

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by Vge0rge** [comment]
Καλησπέρα, 

Αντιμετωπίζουμε το ίδιο πρόβλημα εάν και περνάμε την παράμετρο αυτή με τιμή 'en-US' ή 'en-GB'. Μπορούμε να σας στείλουμε με κάποιο τρόπο πληροφορίες ώστε να δείτε ακριβώς τι συμβαίνει; Μήπως κάτι δεν λαμβανετε καλά για κάποιο λόγο;

**Comment by krakenrules** [comment]
Καλησπέρα,

Θα θέλαμε να μας στείλετε το order code για το οποίο αναφέρεστε καθώς και το περιβάλλον (demo/production) για να το διερευνήσουμε; 

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by Vge0rge** [comment]
Καλησπέρα και πάλι, 

Να σας το στείλω εδώ ή υπάρχει κάποιος άλλος τρόπος;

**Comment by krakenrules** [comment]
Μπορείτε να το στείλετε εδώ.

**Comment by Vge0rge** [comment]
Τα στοιχεία είναι:
 
 Κωδικός Πληρωμής: 7975645185872600 
Περιβάλλον: Production

**Comment by krakenrules** [comment]
Γεια σας,

Θα πρεπει να περάσετε την παραμετρο **lang=en-US** μαζι με το order code κατά την διαδικασια του redirection. 
πχ. "/web/checkout?ref=7975645185872600&lang=en-US"
Περισσότερα για τις παραμέτρους θα βρείτε στο https://github.com/VivaPayments/API/wiki/Redirect-Checkout


Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by Vge0rge** [comment]
Ευχαριστώ για την απάντηση!  Ωστόσο χρησιμοποιούμε το web/newtransaction.aspx?ref= και όχι το web/checkout?ref= . Είναι από παλιά έκδοση του api αυτό γιατί δεν το βρίσκω στο wiki;  Είναι ασφαλές να το αλλάξουμε ή χρειάζεται και κάποια άλλη αλλαγή;

**Comment by krakenrules** [comment]
Γεια σας,

Μπορείτε να το αλλάξετε σε web/checkout?ref=. Για την αλλαγή σε Αγγλικά προσθέστε και το "lang=en-US".

Ευχαριστούμε πολύ για την επικοινωνία.
