### ISSUE TITLE
Cannot register card reader

### ISSUE THREAD

**Issue by Gazatron3000** [VivaPayments/API#1480]
When i follow the instructions to register a device as per https://help.vivawallet.com/hc/en-us/articles/360004586638-How-can-I-activate-my-Viva-Wallet-card-terminal-
The option to select device is not given
s/n is not recognised
Is there an alternative method of adding device to my account in order to begin using it?

**Comment by Gazatron3000** [comment]
![Screenshot_2020-03-20 https members vivawallet com](https://user-images.githubusercontent.com/62450774/77212965-13d3ac00-6b01-11ea-8cdf-895843e9396a.png)

**Comment by matthewrgourd** [comment]
Hi @Gazatron3000 sorry to hear this. Did you buy the card reader from Viva Wallet?

**Comment by matthewrgourd** [comment]
Hi @Gazatron3000 apologies, it looks like the process has changed. Thanks for pointing out! We need to update our support page. No, that's the only way to register a device. If the [card terminal ID](https://help.vivawallet.com/hc/en-us/articles/360004421437-Where-can-I-find-the-card-terminal-ID-of-my-Viva-Wallet-POS-device-) wasn't recognised, it probably isn't a Viva Wallet device.
