### ISSUE TITLE
Android x86 support

### ISSUE THREAD

**Issue by adydeac** [VivaPayments/API#1481]
My name is Adrian (from Romania) and I am developing an POS terminal software for HORECA (ie. bar, restaurants, shops, hotels, etc) called Negotio (https://negot.io/). It is based on PHP and is Linux-centric.

I am trying to reuse some terminals available on the locations I am installing my POS system. Most of them have x86 systems with touchscreens, therefore it is an pity to simply dump them and buy new hardware. Linux is running perfectly on them. Plus, decent tablets to use as an POS terminal (ie >10" display, octa core, >2GB RAM) are quite expensive.

However, I am trying to interface with the Mini Card Reader, but the only way to do that is via the Android app (or is there another way?).

I have installed Android x86 in an virtual machine, I can install the app from the Play store, but I get an message that reads "Ambigous activity is detected, for security reasons the app cannot operate and will be terminate. Check that the device is not rooted. Please contact support if the issue persists."
I've removed the su binaries from the Android x86 stock image, I've also disabled the root access from developer options, but it still fails.
Is there an way to find out on which check point it fails? I am happy to do any debugging and modify the Android stock image to comply with your apps conditions/restrictions, but I'm blind on how to do that.

Thanks,
Adrian

**Comment by matthewrgourd** [comment]
Hi @adydeac, on the subject of interacting with the Mini Card Reader, currently the only available interface is our [POS terminal app](https://developer.vivawallet.com/pos-api-integration/pos-terminal-app/). Regarding contacting support, you should use our email address support@vivawallet.com. About the Android x86 stock image, our app supports Android non-rooted devices with OS >= 6.0 and BLE 4.2, so please use a physical device.

**Comment by adydeac** [comment]
Hi @matthewrgourd,

Thanks for getting back to me!
As I've said, I've cleaned the x86 stock image as much as I could, but I could not get over the message. Is there a list of files to check? Maybe (most likely) I've missed some files.
I have the same issue with android TV boxes (that have bluetooth). Chinese stock firmwares already come rooted. :(
Kindly provide me an list of checks so I could clean the images so I can get these devices to wotk with the POS terminal app.

Thank you,
Adrian

**Comment by matthewrgourd** [comment]
Hi @adydeac, apologies, I can't provide anything more than general guidance in this area. Have a good day!
