### ISSUE TITLE
PAX S800 Ethernet POS limitations

### ISSUE THREAD

**Issue by adydeac** [VivaPayments/API#1482]
My name is Adrian (from Romania) and I am developing an POS terminal software for HORECA (ie. bar, restaurants, shops, hotels, etc) called Negotio (https://negot.io/). It is based on PHP and is Linux-centric.

I have also the PAX S800 Ethernet POS - which I've managed to control over network. I've hit some use case limitations that would be great to fix.
The first issue/limitation (and quite the most annoying one) is that once you set it up to accept network payments, you cannot use it as standalone anymore. There are various situations when you need to do it the standard way (ie pay for an invoice, not simply sell something from the POS software), but you have to disable the network payments to do that. Would be great to support this situation straight from the software of the terminal by either temporary disabling the network payments while you do the manual transaction, or to postpone (or reject with an HTTP code?) the new network payments while the manual transaction is running.

The second issue/limitation would be related to the batch reporting from the network. Would need an way of either starting the batch from the network or allow generating the batch report by specifying the start and end time from the network. Or maybe implement both? We need these reports to be attached along with the ECR report to the daily papers.
I could not find any documentation for doing the batch start/report actions from the network. 

Thank you,
Adrian

**Comment by matthewrgourd** [comment]
Hi @adydeac I will need to forward your suggestions to our head of product for consideration. I'll let you know when I receive any feedback.
