### ISSUE TITLE
Error store not found

### ISSUE THREAD

**Issue by ideificio** [VivaPayments/API#1483]
i have a problem with wallet payment system for my ecommerce cannyou.it

I connected the app to my shopify cms

in the configuration I used the Merchant ID code of my account wallet and token that I received by email.

but when I do a test I get an error "Error store not found".
<img width="1318" alt="Schermata 2020-03-23 alle 13 00 14" src="https://user-images.githubusercontent.com/62553726/77324985-d72dcd80-6d17-11ea-9438-b4f47cb34ebd.png">
why? what steps I skipped to activate the store?

Thanks!

**Comment by matthewrgourd** [comment]
Hi @ideificio sorry to hear this. I assume you've followed all the steps in our [installation guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/)? Ensure test mode is deselected. If you're still having problems, please email me (mgourd@vivawallet) your Merchant ID referencing this issue (#1483).

**Comment by matthewrgourd** [comment]
Hi @ideificio did you manage to get it working? Please close this issue if that's the case

**Comment by ideificio** [comment]
thanks we solved it
