### ISSUE TITLE
Vivawallet API configuration with Gloriafood.com

### ISSUE THREAD

**Issue by rjdrundle** [VivaPayments/API#1485]
Hi guys, I am trying to implement the Vivawallet API on a platform called Gloriafood.com - It is a platform that is used for restaurants and eateries for ordering and paying online. The platform offers the option to add your own payment API details.  I would like to add the Viva payment system to my page. Unfortunately I have gone through the API and cannot really understand what I need to add exactly. Attached are the fields that are asked from the platform to be added. Any help or advise on the matter would be of course truly appreciated. Thanks in advance.

Requested Information by Gloriafoods:
Endpoint URL
Restaurant Token
![viva-api](https://user-images.githubusercontent.com/4725834/77341401-58488d00-6d37-11ea-80e9-e7bcda532e8b.png)

**Comment by matthewrgourd** [comment]
Hi @rjdrundle I don't believe we're one of the payment gateways supported by Gloria Foods but I'm checking for you. Please bear with me!

**Comment by rjdrundle** [comment]
Hi! @matthewrgourd ! Gloriafood has 4 specific gateways (braintree, authorize, ayden, worldpay & PP) however it allows you via API to integrate your own payment tab.  The fields above are what they ask for to create it for the customer checkout. Should you need any log in details to see more let me know. Looking forward  to having some good news :)

**Comment by matthewrgourd** [comment]
Hi @rjdrundle there are no obvious values (at the Viva Wallet end) for Endpoint URL / Restaurant Token but I'll run past a developer and see if they can shed any light.

**Comment by rjdrundle** [comment]
Should you wish a the login credentials to take a closer look at the credential panel please let me know.

**Comment by matthewrgourd** [comment]
Hi @rjdrundle, we've not come across this one before but are looking into it. Can you tell me what web page you're sent to if you click on the API docs link next to the second field?

**Comment by rjdrundle** [comment]
Sure, whatever I can do to help. I have been trying with a combination of techniques that you have on your API wiki to try and make this work however it is somewhat impossible form my side. 
Regarding the link,.. once pressed you are taken here: https://github.com/GlobalFood/integration_docs

**Comment by matthewrgourd** [comment]
Hi @rjdrundle can you click on / mouse over the 'information' symbol next to the Endpoint URL field and tell me what's displayed? Can you do the same for the Restaurant Token field? Thanks!

**Comment by rjdrundle** [comment]
Sure, find attached.
![restaurant-token](https://user-images.githubusercontent.com/4725834/78268917-9735ca00-7511-11ea-9f2c-e3c5c5780bd1.jpg)
![email](https://user-images.githubusercontent.com/4725834/78268923-9866f700-7511-11ea-8f2e-0278e5794304.jpg)
![server-key](https://user-images.githubusercontent.com/4725834/78268924-9866f700-7511-11ea-96f2-b66f5b940427.jpg)
![enviornment-key](https://user-images.githubusercontent.com/4725834/78268926-98ff8d80-7511-11ea-8254-31866064dc90.jpg)
![keys-generated](https://user-images.githubusercontent.com/4725834/78268929-98ff8d80-7511-11ea-83f3-15d4d7902bb1.jpg)
![enpoint](https://user-images.githubusercontent.com/4725834/78268931-99982400-7511-11ea-94f1-48c9d88367e2.jpg)

**Comment by matthewrgourd** [comment]
Hi @rjdrundle I've looked into this with our dev team and unfortunately we won't be able to support an integration between Viva Wallet and Gloria Food. Apologies for any inconvenience caused.
