### ISSUE TITLE
Email order issue

### ISSUE THREAD

**Issue by MOM-TRK** [VivaPayments/API#1486]
Hello,

I have your plugin on my website and there is an issue with the order emails that customer and admin user gets. I am using an extra plugin to customize my woo order emails and it worked great untill I installed your plugin. I have the option of "proccessing order" that "your" orders are going to get and that option uses the default woo emails template for proccessing orders.

So, when I try a test order with your plugin as a payment method, I am getting the woo's default email template. But when I try different payment method and I get the "proccessing order" email, I am getting the custom email that I have created with that extra plugin.

I've tried all the possible combinations for order testing, and anything that has to do with vivapayments plugins, it is not working like I want it to work. 

How can I "deactivate" your plugin's option that sends the default woo order email tempaltes?

Thank you!

**Comment by matthewrgourd** [comment]
Hi @MOM-TRK I believe our WooCommerce plugin is intended for use with a vanilla version of WooCommerce installed with no additional plugins. Thanks!

**Comment by MOM-TRK** [comment]
Hello there

My issue is i think clearly with your plugin. I am not expert at coding but in my mind this is like:
1. A customer makes an order
2. Woo wants to send him the order email
3. And that additional plugin is sending a Custom email instead of woo's default

with your plugin
1. A customer makes an order
2. Woo wants to send him the order email
3. your plugins re-activates the default order email and just sends it to customer

So I want your plugin to stop sending the default emails after an order is placed
or somehow to "follow the instructions" that my additional plugin is giving


Thank you!

**Comment by matthewrgourd** [comment]
Hi @MOM-TRK unfortunately I can't see any notification settings to change within our plugin so I assume that's how it works out of the box. Sorry I can't help any further.
