### ISSUE TITLE
Success URL Error Message

### ISSUE THREAD

**Issue by atalosweb** [VivaPayments/API#1488]
Please check the following image: https://ibb.co/bz1jrcs
It's being displayed after the payment has been proceeded by Viva 
Source URL in Viva dashboard is this: index.php?wc-api=wc_vivawallet&vivawallet=success
Can you figure out where is the mistake?

**Comment by matthewrgourd** [comment]
Hi @atalosweb sorry to hear this. Can you let me have (in text rather than a screenshot) the URL of your e-commerce website so I can check further? Thanks!

**Comment by matthewrgourd** [comment]
Closing issue as no reply...
