### ISSUE TITLE
Στοιχεία Πελάτη στην χρέωση

### ISSUE THREAD

**Issue by andyz1974** [VivaPayments/API#149]
Καλησπέρα. 
Έχω ενσωματώσει το Native Payments σε ένα website το οποίο είναι σε τεστ και χρησιμοποιώ το demo.vivapayments.com για δοκιμές. Θα ήθελα να ρωτήσω τι χρειάζεται να κάνω για να εμφανίζονται το όνομα, το email και το τηλέφωνο του πελάτη, στις Πληροφορίες Χρέωσης της κάρτας.

Ευχαριστώ.

**Comment by krakenrules** [comment]
Γεια σας,

Μπορείτε να ορίσετε το ονοματεπώνυμο, email και τηλέφωνο στα optional parameters της CreateOrder. Περισσότερα για τις παραμέτρους θα βρείτε στο https://github.com/VivaPayments/API/wiki/Optional-Parameters

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by andyz1974** [comment]
Γεια σας και σας ευχαριστώ για την απάντηση. Χρειάζομαι λίγη περισσότερη βοήθεια.
Χρησιμοποιώ το παράδειγμα που έχετε στο API/NativeCheckout/PHP

Στην φόρμα με τα στοιχεία, ζητάω το email με το πεδίο
`<div class="form-row"><span>Email</span> <input name="Email" size="20" type="text" /></div>`
και το όνομα με τον τρόπο που είναι και στο παράδειγμα, δλδ
`<div class="form-row"><span>Cardholder Name</span> <input autocomplete="off" name="txtCardHolder" size="20" type="text" data-vp="cardholder" /></div>`

Ορίζω τις μεταβλητές
$Email=$_POST['Email']; 
$Fullname=$_POST['txtCardHolder'];

Χρησιμοποιώ το αρχείο NativeCheckoutClass.php. Σε ποιο σημείο θα πρέπει να προσθέσω τις παραμέτρους;

**Comment by andyz1974** [comment]
Γεια σας και σας ευχαριστώ με την απάντηση. Τα κατάφερα με το email και το τηλέφωνο, αλλά φαίνεται ότι κάτι κάνω λάθος με το όνομα. 
Στην φόρμα των στοιχείων χρησιμοποιώ το πεδίο όπως στο παράδειγμα που δίνετε:
`<div class="form-row"><span>Cardholder Name</span> <input autocomplete="off" name="txtCardHolder" size="20" type="text" data-vp="cardholder" /></div>`

Δημιουργώ την μεταβλητή `$name=$_POST['txtCardHolder'];`, την εισάγω στην MakePayment() και στις παραμέτρους του NativeCheckoutClass.php, ακριβώς όπως και με το τηλέφωνο και το email.

Οποιαδήποτε βοήθεια θα την εκτιμούσα απεριόριστα, καθώς είναι το μόνο που λείπει για να πάει το site live.

Και πάλι ευχαριστώ

**Comment by dmihos** [comment]
Καλησπέρα σας
Το σχετικό property για το Ονοματεπώνυμο, είναι το **FullName**, όπως φαίνεται και στα [Optional Parameters](https://github.com/VivaPayments/API/wiki/Optional-Parameters).

**Comment by andyz1974** [comment]
Καλησπέρα σας.
Πράγματι, όπως και για το τηλέφωνο είναι "Phone" και για το email, "Email". Ωστόσο, το μόνο που δεν μεταφέρεται είναι το όνομα. 
Ακόμα και αλλάζοντας το `name="txtCardHolder"` σε `name="FullName"` και το `$name=$_POST['txtCardHolder'];` σε `$name=$_POST['FullName'];`, το αποτέλεσμα παραμένει το ίδιο: το όνομα δεν μεταφέρεται.
Στο NativeCheckoutClass.php  φυσικά προσθέτω `$obj->FullName=$name;`, όπως ακριβώς και για το τηλέφωνο και το email.

Μήπως μου ξεφεύγει κάτι;

**Comment by defilerc** [comment]
Καλησπέρα @andyz1974 ,

Θα πρέπει να βεβαιωθείτε πως στο `input` element με `name="FullName"` έχετε αφαιρέσει το attribute `data-vp`.

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by andyz1974** [comment]
Καλησπέρα @defilerc 
Δοκίμασα να αφαρέσω το Attribute data-vp και δεν προχωράει καν η διαδικασία. Εξάλλου και στο documentation αναφέρεται ότι αυτό είναι απαραίτητο για να γίνει το tokenization.

Ευχαριστώ.

**Comment by defilerc** [comment]
Καλησπέρα @andyz1974 ,

Για να γίνει επιτυχώς το tokenization, χρειάζονται οι εξής πληροφορίες: 

- Card holder name
- Card number & CVV
- Expiration Month & Year

Τα συγκεκριμένα input elements πρέπει να έχουν το attribute `data-vp`, ώστε να αποσταλλούν στο Viva Payments API και να πάρετε πίσω το token.

Εκτός από τα συγκεκριμένα πεδία, μπορείτε στη φόρμα σας να ζητήσετε οποιαδήποτε πληροφορία παραπάνω. Στα συγκεκριμένα πεδία, **δεν** θα πρέπει να βάλετε το attribute `data-vp`, επειδή αυτό θα τα αποτρέψει από το να αποσταλλούν στη σελίδα που θα γίνει post η φόρμα.

Επομένως, για να μπορέσετε να επιτύχετε αυτό που θέλετε, θα πρέπει να έχετε ένα επιπλέον πεδίο, το οποίο θα ζητάτε το ονοματεπώνυμο του χρήστη και το οποίο δε θα έχει το attribute `data-vp`, ώστε να αποσταλεί στη σελίδα που θα γίνει post η φόρμα.

Στη συνέχεια θα πρέπει να δημιουργήσετε ένα order, χρησιμοποιώντας την `CreateOrder`, στην οποία θα περάσετε σαν παράμετρο `FullName`, την τιμή που σας πέρασε ο χρήστης στο επιπλέον πεδίο που ορίσατε. Έτσι θα εμφανιστεί στη χρέωση της κάρτας το ονοματεπώνυμο του χρήστη.

Με εκτίμηση
