### ISSUE TITLE
Pre-install 

### ISSUE THREAD

**Issue by dablabuk** [VivaPayments/API#1490]
Hi, 

my viva wallet account has been verified and domain accepted. However when signing in to shopify and trying to integrate - the option for viva wallet (pre-install) within payment providers is not showing in my account? is there something else i need to connect, or should this appear automatically - as showed in the step by step guide to shopify integration? 

thanks

**Comment by matthewrgourd** [comment]
Hi @dablabuk, sorry to hear this. Do you have a live Shopify site? What is the URL please?

**Comment by dablabuk** [comment]
Hi,

yes our url is: https://dablab.co.uk

thanks

**Comment by dablabuk** [comment]
Hi matthew,

is this now resolved?

thanks

**Comment by matthewrgourd** [comment]
Hi @dablabuk can you send your Viva Wallet Merchant ID to me at mgourd@vivawallet.com as I need to check a few things? Thanks!

**Comment by matthewrgourd** [comment]
HI @dablabuk thanks for sending your Merchant ID through. I've checked your account now and can see everything looks fine. Can I just ask, did you successfully receive a store token by email from us?

**Comment by dablabuk** [comment]
hi,

yes i received a token. Im looking in my payment providers section now, and
there is still no viva wallet. do i have to go in to third party suppliers??

thanks

**Comment by matthewrgourd** [comment]
Hi @dablabuk I'm not sure what to suggest. Maybe log out of your Shopify account and try the installation steps again, or try in a different browser?

**Comment by dablabuk** [comment]
I have done all that, on a number of occasions. So you suggest finding  a
new supplier?

to confirm - it should just appear in my payment providers section yes??
there is nothing else i can do, apart from what you recommended

**Comment by dablabuk** [comment]
can you send me over the links to sign in and sign out and ill try one more
time

**Comment by matthewrgourd** [comment]
@dablabuk I mean just log out of your Shopify shop then log back in again.

**Comment by dablabuk** [comment]
yes i have just tried it again there, and there is still no viva wallet pre
install showing. Any other suggestions? I would like to try and get this
resolved asap, and begin to connect it - as im unable to take any payments.

thanks

**Comment by dablabuk** [comment]
?

**Comment by dablabuk** [comment]
???

**Comment by matthewrgourd** [comment]
Hi @dablabuk, I'm sorry, I don't know what to suggest beyond what I've already mentioned.

**Comment by dablabuk** [comment]
can you not go in to our shopify and viva store if i give you the logins
and solve it that way?

**Comment by dablabuk** [comment]
can you give me a call??

**Comment by matthewrgourd** [comment]
Hi @dablabuk, the support we offer is via GitHub only. I will need to escalate this as I don't have an immediate solution. Please bear with me.

**Comment by matthewrgourd** [comment]
Solved by email...
