### ISSUE TITLE
Problem with Shopify API

### ISSUE THREAD

**Issue by rounsmith** [VivaPayments/API#1491]
We didn't had any problem past weeks but Greece global lockdown it seems some errors are getting to some of our users during checkout.

Can you check it out?

User send me error saying ERROR GENERIC ERROR with url checkout.vivawallet.com/shopifyplugin

Is this valid or?

It was working until 2 days ago lol.

I did the integration on forum of viva wallet.

**Comment by matthewrgourd** [comment]
Can I have the URL of your Shopify website so I can test, please? Thanks!

**Comment by rounsmith** [comment]
Shop is www.afasia.gr

**Comment by matthewrgourd** [comment]
Hi @rounsmith I believe there may have been a temporary issue but I'm not sure why. Please can you let me know if it's working ok now?

**Comment by rounsmith** [comment]
Well seems to be fixed from that error but we have the issue of people can't pay with viva wallet and same card via paypal pays. I don't know if this issue of the plugin or not.

We had 1 payment go through from 12-13 attempts(all cards had money in them).

**Comment by matthewrgourd** [comment]
Hi @rounsmith please email me your Merchant ID so I can check your account transactions. My email address is mgourd@vivawallet.com Thanks!

**Comment by rounsmith** [comment]
Ok i will sent them to you now!

**Comment by matthewrgourd** [comment]
Hi @rounsmith thanks for the email. I've checked your account over the past six weeks and can't see anything unusual. You have very few payment failures and these are all due to the usual issuer rejection reasons. Please keep monitoring and let us know if any further issues but in the meantime I'm going to close this issue.

**Comment by rounsmith** [comment]
Thank you !
