### ISSUE TITLE
Problem with Shopify API 

### ISSUE THREAD

**Issue by WJMalcom** [VivaPayments/API#1492]
Hi, 

on our website cbdqueen.fr , our customer cannot pay anymore without having a " Error : Generic Error " ,  with url checkout.vivawallet.com/shopifypluginwe didn"t change anything to shopify code or configuration. 

It use to work fine before. 
![90994952_230263694839874_2760311619270475776_n](https://user-images.githubusercontent.com/62606569/77435842-137a3000-6de3-11ea-8d41-2f7c1e2edcf6.jpg)

**Comment by WJMalcom** [comment]
We now have problem with 3D secure. There is a white screen in the 3D secure's pop up.

**Comment by WJMalcom** [comment]
![91187592_206792653878321_5181442962436915200_n](https://user-images.githubusercontent.com/62606569/77440680-ddd84580-6de8-11ea-9597-c0cf8dbb6947.jpg)

**Comment by matthewrgourd** [comment]
Hi @WJMalcom I just tested this myself by making a purchase via your website with a card with zero balance and everything seems to be working fine? https://cbdqueen.fr/ I'm using Google Chrome and the card is a Mastercard. Obviously the card transaction was declined due to insufficient funds but the 3DS worked. I'm not sure why you would want to visit the URL vivawallet.com/shopifyplugin.

**Comment by matthewrgourd** [comment]
Hi @WJMalcom, I see a couple of other people have had this issue. I checked with our development team and I'm told there's definitely no generic error with our Shopify plugin. So it must be your settings, but I don't know an immediate answer, I'm afraid. I'll speak to the devs again! One thing to check, have your transaction volumes increased a lot recently?

**Comment by matthewrgourd** [comment]
Hi @WJMalcom, our development team just got back to me after some tests over the weekend. Apparently there were a few performance issues with our platform and some fixes have been applied. Hope things are fine now. Please let me know if you experience any further issues. Thanks.

**Comment by WJMalcom** [comment]
Hi @matthewrgourd thanks for checking. We had a lot of issues previous week ( 28/03 and 29/03) but yesterday and today no problem seem to occur, lets hope it continue that way. the phone support told us that it was a problem on our side, thanks for admitting a possible bug on you server side. i let you know if there is any new issue , thank you really much :)

**Comment by matthewrgourd** [comment]
Hi @WJMalcom, no worries and thanks :-) I'm closing this issue now but feel free to reopen if any further problems...
