### ISSUE TITLE
δεν ολοκληρωνει την πληρωμη ο μηχανισμος της vivawallet  στο eshop μας

### ISSUE THREAD

**Issue by 6986621622** [VivaPayments/API#1493]
Δυστυχως δεν λειτουργει ο μηχανισμος πληρωμης μεσω viva  στο e-shop μας τις τελευταιες 3 μερες

Σας στελνωουμε και σε φωτογραφια το μηνυμα που βγαζει

ενω ολοκληρωνεται σωστα η παραγγελια κανει και redirect  στην σελιδα της vivawallet εχει φερει το ποσο της παραγγελιας και ζηταει τα στοιχεια της καρτας τα συμπληρωνουμε ολα και μολις παμε στο επομενο βημα μας βγαζει μηνυμα την φωτο που στειλαμε οτι δηλαδη εγινε ακυτωση (ενω ειμαστε ακομα σε περιβαλλον vivawallet)

αναβαθμησαμε και στην τελευταια εκδοση το plugin της vivawallet .

**Comment by matthewrgourd** [comment]
Sorry to hear this, which plugin are you using, is it for WooCommerce by any chance? Please let me have the web address of your e-commerce site so I can test. Thanks!

**Comment by 6986621622** [comment]
Our website is http://www.craftbox.gr 



Στάλθηκε από το Ταχυδρομείο Yahoo για iPad


Στις Τετάρτη, Μαρτίου 25, 2020, 12:38 μμ, ο χρήστης matthewrgourd <notifications@github.com> έγραψε:




Sorry to hear this, which plugin are you using, is it for WooCommerce by any chance? Please let me have the web address of your e-commerce site so I can test. Thanks!

**Comment by 6986621622** [comment]
Do you have any news??
Can you please fix the problem??

**Comment by matthewrgourd** [comment]
Can you let me know your registered business name if possible, please? Thanks!

**Comment by 6986621622** [comment]
Our Website is http://www.craftbox.grCompany name  Manolis K. - Georgouti E. O.E.Vat No EL099961402
    Στις Πέμπτη, 26 Μαρτίου 2020, 02:19:10 μ.μ. EET, ο χρήστης matthewrgourd <notifications@github.com> έγραψε:  
 
 


Can you let me know your registered business name if possible, please? Thanks!

**Comment by matthewrgourd** [comment]
Hi @6986621622, I checked your account and it looks like you're using an unofficial Viva Wallet plugin for WooCommerce. The plugin you currently have installed was developed by a Greek hosting company called 'Papaki' and more specifically by its parent company 'Enartia'. Please remove the current version then download and install the correct plugin using the below installation instructions.

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
