### ISSUE TITLE
Demo Site not redirecting on success/fail

### ISSUE THREAD

**Issue by jlazos** [VivaPayments/API#1495]

**Comment by matthewrgourd** [comment]
Hi @jlazos I'm sorry I'm going to need a bit more info than that in order to investigate. A start would be your demo Viva Wallet Merchant ID so I can investigate your account!

**Comment by jlazos** [comment]
Hi! 
My demo Merchant ID is 982cde4c-f9ee-46ea-82a7-026d2be19839

**Comment by matthewrgourd** [comment]
I see you're using our WooCommerce plugin. Is that correct? If so, please send through the following screenshots if you can:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by jlazos** [comment]
Hi, I have attached the screenshots

![3](https://user-images.githubusercontent.com/2114937/77659007-2f670880-6f80-11ea-94d7-adff9fff1414.png)
![4](https://user-images.githubusercontent.com/2114937/77659021-3261f900-6f80-11ea-81ba-d6aa6ca58ac3.png)
![1](https://user-images.githubusercontent.com/2114937/77659024-32fa8f80-6f80-11ea-88a0-6b27c9a0c70a.png)
![2](https://user-images.githubusercontent.com/2114937/77659025-32fa8f80-6f80-11ea-8b0f-aae0df0a5302.png)

**Comment by jlazos** [comment]
Hi! I have attached the screenshots

![1](https://user-images.githubusercontent.com/2114937/77659314-9684bd00-6f80-11ea-88a2-3dcd4e4a2431.png)
![2](https://user-images.githubusercontent.com/2114937/77659318-98e71700-6f80-11ea-8fa6-61a75cfb50c0.png)
![3](https://user-images.githubusercontent.com/2114937/77659320-9a184400-6f80-11ea-847b-58de27457d40.png)
![4](https://user-images.githubusercontent.com/2114937/77659323-9ab0da80-6f80-11ea-92b0-9876588b3544.png)

**Comment by matthewrgourd** [comment]
Thanks for sending those through. For testing in the demo environment, please use the fake card details below:

- Card number: 4111111111111111
- Expiration date: Any in the future
- CVV: 111

This should trigger a 3DS simulation where you can choose the authentication status.

**Comment by jlazos** [comment]
Yes, I'm using the above card!
On the 3DS Simulation I choose a success status.
Then, a page from the demo viva payments site appears confirming the success of the payments. No redirect occurs.

**Comment by manosk1** [comment]
I have the same problem....
Yes, I'm using the above card!
On the 3DS Simulation I choose a success status.
Then, a page from the demo viva payments site appears confirming the success of the payments. No redirect occurs.

**Comment by matthewrgourd** [comment]
Hi @jlazos, @manosk1, as far as I'm aware, this is the correct behaviour for the demo environment. For full testing of the 3DS you have to use production.
