### ISSUE TITLE
Simple Checkout API Access needed

### ISSUE THREAD

**Issue by iromarkaki** [VivaPayments/API#1496]
Hello,
We need to enable production environment access for the Simple Checkout Method.
Our merchant ID is: ****6936-****-413c-****-d9412a02**** 

Thank you in advance

**Comment by matthewrgourd** [comment]
Hi @iromarkaki that's done now! However, I've obscured part of your Merchant ID from your message for security reasons.

**Comment by iromarkaki** [comment]
Thank you.
