### ISSUE TITLE
Native Checkout v2 3DS problems

### ISSUE THREAD

**Issue by mariasoromenho** [VivaPayments/API#1498]
Hi,

I would like to know if you have any full working example of Native Checkout v2 3DS in PHP.
Having implemented lots of payment methods before, I'm having lots of problems with VivaWallet.

This is what i was able to do :
- Generated the token with connect/token
- Created the form with the given token. When I click to submit the form, the chargeToken is generated correctly.
- When trying to communicate perform the transaction through https://demo-api.vivapayments.com/nativecheckout/v2/transactions I get "NULL" as curl response.
- If I simulate the transaction directly  on postman i get a 403 error - Person 873d805f-fff6-4df2-9c75-fc6ffd20e484 does not support currency '826'

Can you please provide a working example?

thank you

* This issue was edited to reflect new steps

**Comment by matthewrgourd** [comment]
Hi @mariasoromenho unfortunately we're a bit short on PHP samples at the moment but are working hard on changing this in the future. However, saying that, I'll see what I can do. Regarding the currency error message this is because at the moment we only support payments into the currency of the country of incorporation of the merchant. So if you set up a Viva Wallet account in Spain, for instance, you would need to set the `currencyCode` parameter to 978 (EUR). Thanks!

**Comment by mariasoromenho** [comment]
Hi @matthewrgourd, here's my transaction code, maybe you can see where the problem is.

`$url = "https://demo-api.vivapayments.com/nativecheckout/v2/transactions";

      $data = array(
        'amount' => 3600,
        'preauth' => false,
        'chargeToken' => $charge_token,
        'installments' => 1,
        'merchantTrns' => "Merchant transaction reference",
        'customerTrns' => "Description",
        'currencyCode' => 978,
        'customer' =>  array('email' => 'mail@example.com', 'phone' => '442037347770', 'fullname' => 'John Smith', 'requestLang' => 'en', 'countryCode' => 'PT')
      );

       $request_headers = array();
       $request_headers[] = 'Authorization: Bearer ' . $token;
       $request_headers[] = 'Content-Type:application/json';

        $ch = curl_init($url);
                              
        curl_setopt($ch, CURLOPT_HTTPHEADER, $request_headers);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 60);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);

      $jsonResponse = curl_exec($ch);
     
      if(curl_errno($ch)){
        throw new Exception(curl_error($ch));
      } 

      curl_close($ch);

      $response = json_decode($jsonResponse, true);
      var_dump($response);`

I don't get an error, or a response.

Thank you.

**Comment by mariasoromenho** [comment]
Hi @matthewrgourd, I think I was able to fix it, after many hours due to lack of good documentation.

Anyway, I'm facing another problem now.

In JS we have

VivaPayments.cards.requestToken({
	    amount:  3600
}).done(function (data) {
	 $('#vivatoken').val(data.chargeToken);
	 processorder();
});

The moment the form is loaded, we still don't have the final amount - the user is still choosing delivery methods. So, if the user makes a change, the amount needs to change too.
I tried calling an ajax when the user clicks the submit button that will return final amount.
The amount returns correctly but when I pass it into your code I get **status: 400
message: "Null options" eventId: "0"**

I tried with a var, like
 amount:  total_amount
and as a function
amount: get_total()

Either way, I guess the values is not being passed.
	          
Any idea? Thanks.

**Comment by matthewrgourd** [comment]
Hi @mariasoromenho, apologies for the delay. I've spoken with our dev team and we will have something for you soon.

**Comment by matthewrgourd** [comment]
Hi @mariasoromenho here is the code sample from our dev team. Hope this helps! Please let me know how you get on.

```
<?php 
    
	$url = 'https://demo-api.vivapayments.com/nativecheckout/v2/transactions';

	$headerArgs = array(
        "Authorization: Bearer ".ACCESS_TOKEN,
        "Content-Type: application/json",
        "Content-Type: text/plain"
	);
	
	$postArgs = array(
		'amount' => AMOUNT,
		'chargeToken' => CHARGE_TOKEN,
		'installments' => 1,
		'preauth' => false,
		'merchantTrns' => "Merchant transaction reference",
		'customerTrns' => "Description that the customer sees",
		'currencyCode' => CURRENCY_CODE,
		'customer' => array(
			'email' => CUSTOMER_EMAIL,
			'phone' => CUSTOMER_PHONE,
			'fullname' => CUSTOMER_NAME,
			'requestLang' => 'en',
			'countryCode' => 'GB'
		)
	);
	
	$curl = curl_init();
	curl_setopt($curl, CURLOPT_URL, $url);
	curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
	curl_setopt($curl, CURLOPT_ENCODING, "");
	curl_setopt($curl, CURLOPT_MAXREDIRS, 10);
	curl_setopt($curl, CURLOPT_TIMEOUT, 0);
	curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);
	curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
	curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
    curl_setopt($curl, CURLOPT_POSTFIELDS, $postArgs);
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headerArgs);

    $result = curl_exec($curl);
    curl_close($curl);

    
    // to debug the call you can uncomment the following lines to check response from the API
    // and get transactionId if success
    // $result = json_decode($result);
    // print_r($result);
```
