### ISSUE TITLE
Issue with Payment 

### ISSUE THREAD

**Issue by khushinar** [VivaPayments/API#1499]
We are struggling with Viva Payment API
When customers use native payment option,  they are receiving error message while making payments
VivaPayments : Expiration Date could not be parsed. 
Even if all details entered are correct. As well same card are working fine on other sites with other payment gateways.

Plugins we are using are 
1. donfn-viva-payments-native-checkout
2. vivawallet-for-woocommerce

Please help solving the issue.

**Comment by 6986621622** [comment]
Good morning? Will you find a way to solve the problem with the payment soon?

**Comment by matthewrgourd** [comment]
Hi @khushinar https://wordpress.org/plugins/donfn-viva-payments-native-checkout/ is not a plugin we support so I won't be able to help, I'm afraid. Thanks.

**Comment by matthewrgourd** [comment]
HI @khushinar I gather you just contacted our customer service team. I will say this again we don't support unofficial plugins I'm afraid. Nothing I can do. You should go here for support: https://wordpress.org/support/plugin/donfn-viva-payments-native-checkout/
