### ISSUE TITLE
Datetime conversion in python wrapper

### ISSUE THREAD

**Issue by ppetrid** [VivaPayments/API#15]
The current python implementation fails to convert the returned ISO-formatted timestamp to a datetime object if the characters representing seconds are less than 10.

For example, I have seen both 
```2014-08-15T15:39:55.461264+03:00``` and
```2014-08-15T15:39:55.5706103+03:00``` returned by the REST API as ```TimeStamp``` in actual calls.
In the former case the parser fails since it tries to convert ```55.461264+``` to float.

The obvious solution is to replace
*L83*: ```time_tokens = timestamp[11:27].split(':')``` with
*L83*: ```time_tokens = timestamp[11:26].split(':')``` so that only the first 9 digits of seconds are parsed (or maybe even less).

However, I strongly recommend using a library such as [dateutil] (https://pypi.python.org/pypi/python-dateutil) to do this kind of work. It will add a dependency, but a pretty common one. Dateutil will also add timezone information, which is currently missing.

As a side note, I'd like to see other datetime objects returned by the REST API (such as ```InsDate``` returned by get_transaction) converted too, currently the wrapper only deals with ```TimeStamp```.

If needed, I could create a pull request for this issue.

**Comment by defilerc** [comment]
Hi @ppetrid ,

Thank you very much for your contribution.

Best regards
