### ISSUE TITLE
Native checkout transaction id

### ISSUE THREAD

**Issue by yperaksia** [VivaPayments/API#150]
Καλησπέρα,

έχω ενσωματώσει τους κώδικες σε php ιστοσελίδα και έχω ακολουθήσει τα βήματα που περιγράφονται και όλες τις οδηγίες πιστεύω πιστά και σωστά. 
Το πρώτο πρόβλημα το οποίο αντιμετώπισα ήταν ότι δεν γινόταν ασφαλής μετάβαση των δεδομένων στο js και για αυτό μετέτρεψα όλα τα redirection σε https. Μετά από αυτό ολοκληρώνεται η διαδικασία χωρίς error response σε κανένα επίπεδο.

Το πρόβλημα τώρα είναι ότι δεν παίρνω πίσω transaction id, σαν να μην δουλεύει δηλαδή το NativeCheckoutClass.php
δεν δίνει πίσω ούτε transaction id ούτε error και είναι null
σε συνδυασμό, δεν γίνεται καμία χρέωση ούτε σε demo περιβάλλον ούτε σε πραγματικό ούτε με δική μου κάρτα ούτε με την 41111....

Σημείωση: Το $cardToken, το $installments και το $amount μεταφέρονται μέχρι το τέλος της διαδικασίας άριστα.

Σας επισυνάπτω παρακάτω το NativeCheckoutClass όπως έχει ολοκληρωθεί και παρακαλώ θερμά για όποια βοήθεια στο σχετικό θέμα επειδή είναι πολύ σοβαρή η επίλυσή του.

<?php
 
 class OrderRequest {}
 class PaymentRequest {}
 
 class NativeCheckout {
 
	private $merchantId = '123456789-1234-1234-1234-123456789012';
	private $apiKey = '123456'; 
 	private $baseApiUrl = "https://demo.vivapayments.com";
     private $paymentsUrl = "/api/transactions";
     private $paymentsCreateOrderUrl = "/api/orders";
  
 	private $nativeCheckoutSourceCode = "Native";
	private $resultObj = "";
 	
 	public function MakePayment($amount,$cardToken,$installments){
 		
 		$orderCode=$this->CreateOrder($amount,$installments);
 		
 		$obj=new PaymentRequest();
 		
 		$obj->Amount=$amount;
 		$obj->OrderCode=$orderCode;
 		$obj->SourceCode=$this->nativeCheckoutSourceCode;
		$obj->CreditCard["Token"]=$cardToken;
 		$obj->Installments=$installments;
 		
 		$resultObj = $this->ExecuteCall($this->baseApiUrl.$this->paymentsUrl,$obj);
 				
 		if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
 			return $resultObj->TransactionId;
 		}
 		else{
 			echo 'The following error occured: ' . $resultObj->ErrorText;
 			return '0';
 		}	
 	}
 	
 	private function CreateOrder($amount,$installments){
 	
 		$obj=new OrderRequest();
 		
 		$obj->Amount=$amount;
 		$obj->SourceCode=$this->nativeCheckoutSourceCode;
 		$obj->MaxInstallments=$installments;
 				
 		$resultObj = $this->ExecuteCall($this->baseApiUrl.$this->paymentsCreateOrderUrl,$obj);
 		
 		if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
 			return $resultObj->OrderCode;
 		}
 		else{
 			echo 'The following error occured: ' . $resultObj->ErrorText;
 			return 0;
 		}	
 	}	
 	
 	private function ExecuteCall($postUrl,$postobject){
 	
 		$postargs=json_encode($postobject);
 	
 		// Get the curl session object
 		$session = curl_init($postUrl);
 		
 		// Set the POST options.
 		curl_setopt($session, CURLOPT_POST, true);
 		curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
 		curl_setopt($session, CURLOPT_HTTPHEADER, array(                                                                          
 			'Content-Type: application/json',                                                                                
 			'Content-Length: ' . strlen($postargs))                                                                       
 		);   
 		curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
 		curl_setopt($session, CURLOPT_USERPWD, $this->merchantId.':'.$this->apiKey);
 		curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
 		
 		curl_setopt($session, CURLOPT_HEADER, true);
 		
 		// Do the POST and then close the session
 		$response = curl_exec($session);
 		
 		// Separate Header from Body
 		$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
 		$resHeader = substr($response, 0, $header_len);
 		$resBody =  substr($response, $header_len);
 		
 		// Parse the JSON response
 		try {
 			if(is_object(json_decode($resBody))){
 				$resultObj=json_decode($resBody);
 			}else{
 				preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader, $match);
 				throw new Exception(trim($match[1]));
 			}
 		} catch( Exception $e ) {
 			echo $e->getMessage();
 		}
 		
 		curl_close($session);
 		return $resultObj;
 	}
 	
 }
?>

**Comment by yperaksia** [comment]
Συμπληρώνω ότι στη σελίδα προορισμού όπου καλείται το NativeCheckoutClass.php με POST έχω τα εξής: 

<?php
require_once("NativeCheckoutClass.php");
					 if (count($_POST)>0){
			 	$page=new NativeCheckout();
			 	$amount=$_POST['sum3']; // in cents
			 	$cardToken=$_POST["hidToken"];
			 	$installments=$_POST["drpInstallments"];
				$transactionId=$page->MakePayment($amount,$cardToken,$installments);};
?>

**Comment by defilerc** [comment]
Καλησπέρα @yperaksia ,

Θα πρέπει να χρησιμοποιήσετε τα credentials (merchant id και api key) τα οποία σας έχουν αποδοθεί κατά την εγγραφή σας στο demo περιβάλλον της viva payments. Απ' ότι βλέπουμε στους κώδικες που έχετε επισυνάψει, χρησιμοποιείται κάποια dummy στοιχεία και επειδή δεν αναφέρετε κάπου ότι τα έχετε αντικαταστήσει, θα πρέπει πρώτα να σιγουρέψουμε ότι συνδέεστε σωστά με το Viva Payments API.

Αν χρησιμοποιείται τα σωστά credentials και συνεχίζετε και αντιμετωπίζετε κάποιο πρόβλημα, θα σας παρακαλούσαμε να μας στείλετε το Request καθώς και το Response που παίρνετε κατά την επικοινωνία σας με το API.

Σας ευχαριστούμε πολύ για την επικοινωνία.

**Comment by yperaksia** [comment]
Ναι εννοείται ότι βάζω τα σωστά credentials στις σειρές 5 και 6 και τα άλλαξα εδώ για να μην τις χρησιμοποιήσει κάποιος άλλος.

Η ολοκλήρωση γίνεται μέσα από php σελίδα με κώδικα php/html
κατά τον έλεγχο δεν εμφανίζεται κανένα Request από το NativeCheckoutClass.php οπότε και κανένα Response. H σελίδα NativeCheckoutClass.php εδώ πέραν των credentials είναι όπως προβλέπεται?


Για να βοηθήσω να κατανοήσετε το πρόβλημα:
Η πρώτη σελίδα basket.php έχει αυτό το κώδικα με τον οποίο δημιουργείται το TOKEN επιτυχημένα:

<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="https://demo.vivapayments.com/web/checkout/js">/script>
<script type="text/javascript">											 		$(document).ready(function (){
															 			   VivaPayments.cards.setup({
																				publicKey: "luqxozhR8k03M8ZFRcSNulnBQJy1ytFwVPK4kA7d1Rs=",
															 					baseURL: "https://demo.vivapayments.com",
															 					cardTokenHandler: function (response) {
															 							if (!response.Error) {
															 								$("#hidToken").val(response.Token);
															 								$("#basket").submit();
															 								return false;
															 							}
															 							else{
															 								console.log(response);
															 								alert(response.Error);
															 								return false;
															 							}
															 					},
															 					installmentsHandler: function (response) {
															 							if (!response.Error) {
															 									if (response.MaxInstallments == 0)
															 										return;
															 									$("#drpInstallments").show();
															 									for(i=1; i<=response.MaxInstallments; i++){
															 										$("#drpInstallments").append($("<option>").val(i).text(i));
															 									}
															 							}
															 							else
															 								alert(response.Error);
															 					}
															 			   });
															 		});
		</script>

 και στη συνέχει το στέλνει με POSΤ σε δεύτερη σελίδα ok.php εφόσον δεν υπάρχει error μαζί με το $cardToken, το $installments και το $amount. Σε αυτή τη δεύτερη σελίδα ok.php καλείται το NativeCheckoutClass.php  του οποίου τον κώδικα σας έστειλα παραπάνω,

Το NativeCheckoutClass.php όμως δεν επιστρέφει $transactionId

**Comment by defilerc** [comment]
Καλημέρα @yperaksia ,

Η πρώτη κλήση στο Viva Payments API αφορά τη δημιουργία του Order. Θα πρέπει πρώτα να διαπιστώσουμε ότι δημιουργείται με επιτυχία το order και λαμβάνετε κάποιο order code. Απ' ότι βλέπω χρησιμοποιείται το SourceCode = "Native". Θα πρέπει σαν SourceCode να ορίσετε τον κωδικό που έχει αποδοθεί στην πηγή πληρωμής Native που έχετε δημιουργήσει. Συνδεθείτε στο εμπορικό σας account και πηγαίνετε από το μενού στις Πωλήσεις -> Πηγές Πληρωμών και δείτε τον Κωδικό (αντί για την περιγραφή της Πηγής Πληρωμών που έχετε δημιοιυργήσει).

Επιπλέον από τις ρυθμίσεις της Πηγής Πληρωμών (κάνοντας κλικ πάνω στο όνομα της Πηγής στην περιγραφή), θα πρέπει να βεβαιωθείτε ότι η συγκεκριμένη πηγή πληρωμών είναι ορισμένη ως "Native/Πληρωμή με Viva Wallet Checkout" στο Integration Method.

Αν παρ' όλα αυτά συνεχίζετε και έχετε πρόβλημα, παρακαλώ πολύ στείλτε μας το merchant id σας, ώστε να δούμε τι έχει συμβεί.

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by yperaksia** [comment]
Ναι οι ρυθμίσει και οι δύο που αναφέρετε έχουν γίνει.

To merchant id : 91cb9a7f-3ef0-4de5-937b-b41bd2fbec47

**Comment by defilerc** [comment]
Καλησπέρα @yperaksia ,

Απ' ότι φαίνεται δεν έχει δημιουργηθεί κανένα Order στο demo περιβάλλον κάτω από το merchant id που μας αναφέρετε. Επομένως, το πρόβλημα σας προέρχεται από το ότι η CreateOrder αποτυγχάνει. Για να πάρετε transaction id, θα πρέπει πρώτα να έχετε ένα valid order code από την CreateOrder.

Θα πρέπει να μας στείλετε το ακριβές request που κάνετε για την CreateOrder (που να φαίνονται όλες οι παράμετροι που περνάτε), καθώς και το response που λαμβάνετε από το Viva Payments API (error code και error message) για να μπορέσουμε να σας βοηθήσουμε περαιτέρω. 

Το request και το response έχουν τη μορφή που φαίνεται στη σελίδα: https://github.com/VivaPayments/API/wiki/CreateOrder στις ενότητες "Sample Request" και "Sample Response".

Σας ευχαριστούμε πολύ.

**Comment by yperaksia** [comment]
To merchant id για το demo είναι: 8b8c69fe-2c0a-4b8b-85e7-cb1a9a0c1c1d
ενώ
Το merchant id για το www είναι: 91cb9a7f-3ef0-4de5-937b-b41bd2fbec47

δηλαδή το Create Order δεν ολοκληρώνεται μέσα από το NativeCheckoutClass.php με session?

Όταν λέτε να σας στείλω το Request εννοείται τον κώδικα της σελίδας ? Αν όχι από που θέλετε να τα συλλέξω, πχ με echo των $response  και $postargs?

**Comment by defilerc** [comment]
Καλησπέρα @yperaksia ,

Στο παρακάτω URL, μπορείτε να βρείτε sample κώδικα php για το πως να πάρετε την απάντηση από το Viva Payments API, σε περίπτωση λάθους:

https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php

Ευχαριστούμε πολύ.

**Comment by yperaksia** [comment]
Ok
έκανα create order σε demo περιβάλλον και αυτό ολοκληρώθηκε με επιτυχία, μάλιστα έγινε και πληρωμή με επιτυχία.
Όταν όμως έβαλα τα credentials για το πραγματικό περιβάλλον πήρα αυτό το μήνυμα:
API Call failed! The error was: Invalid or inactive reseller with id 91cb9a7f-3ef0-4de5-937b-b41bd2fbec47Your Order Code is: 

τι σημαίνει το invalid or inactive reseller?

**Comment by yperaksia** [comment]
Σε συνέχεια του προηγούμενου διόρθωσα το demo. σε www. και πλέον παίρνω το μήνυμα:

API Call failed! The error was: Your Order Code is:

**Comment by dmihos** [comment]
Θα χρειαστεί να μας δώσετε την ακριβή απάντηση του API (Status Code / Text) για να καταλάβουμε το πρόβλημα. Μπορείτε να προσαρμόσετε τον κώδικά σας όπως υποδείχθηκε παραπάνω.

Θεωρώντας ότι url/credentials είναι σωστά, ελέγξτε, αν θέλετε και την πηγή (βλέπω χρησιμοποιείτε μια πηγή 'Native'. Υπάρχει στην παραγωγή με το ίδιο όνομα;)

Ευχαριστούμε,

**Comment by yperaksia** [comment]
Ναι αυτό μου δίνει, κενό μήνυμα.

Δίνω κώδικα (κρύβοντας τον κωδικό για το API):

<?php 
$request =  'https://www.vivapayments.com/api/orders';	
$MerchantId = '91cb9a7f-3ef0-4de5-937b-b41bd2fbec47';
$APIKey = 'XXXXXXXX'; 	
//Set the Payment Amount
$Amount = 40;	// Amount in cents
//Set some optional parameters (Full list available here: https://github.com/VivaPayments/API/wiki/Optional-Parameters)
$AllowRecurring = 'true'; // This flag will prompt the customer to accept recurring payments in tbe future.
$RequestLang = 'en-US'; //This will display the payment page in English (default language is Greek)
$Source = 'Default'; // This will assign the transaction to the Source with Code = "Default". If left empty, the default source will be used.
$postargs = 'Amount='.urlencode($Amount).'&AllowRecurring='.$AllowRecurring.'&RequestLang='.$RequestLang.'&SourceCode='.$Source;
// Get the curl session object
$session = curl_init($request);
// Set the POST options.
curl_setopt($session, CURLOPT_POST, true);
curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
curl_setopt($session, CURLOPT_HEADER, true);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
// Do the POST and then close the session
$response = curl_exec($session);
// Separate Header from Body
$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
$resHeader = substr($response, 0, $header_len);
$resBody =  substr($response, $header_len);
curl_close($session);
// Parse the JSON response
try {
	if(is_object(json_decode($resBody))){
	  	$resultObj=json_decode($resBody);
	}else{
		preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader, $match);
				throw new Exception("API Call failed! The error was: ".trim($match[1]));
	}
} catch( Exception $e ) {
	echo $e->getMessage();
}
if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
	$orderId = $resultObj->OrderCode;
	echo 'Your Order Code is: <b>'. $orderId.'</b>';
	echo '<br/><br/>';
	echo 'To simulate a successfull payment, use the credit card 4111 1111 1111 1111, with a valid expiration date and 111 as CVV2.';
	echo '</br/><a href="https://demo.vivapayments.com/web/newtransaction.aspx?ref='.$orderId.'" >Make Payment</a>';
}
	
else{
	echo 'The following error occured: ' . $resultObj->ErrorText;
}
?>

και παίρνω:

API Call failed! The error was: Your Order Code is: 

To simulate a successfull payment, use the credit card 4111 1111 1111 1111, with a valid expiration date and 111 as CVV2.
Make Payment

Στην πηγή όπου έχω εδώ Default έχω δοκιμάσει και τους κωδικούς από τις πηγές πληρωμών στο λογαριασμό μου και τα ονόματα αλλά πάντα μου βγάζει αυτό το κενό error.

Σημειωτέον ότι στο demo ολοκληρώνονται όλα τέλεια!

Ευχαριστώ εκ των προτέρων.

**Comment by yperaksia** [comment]
Κάποιο νέο σχετικά με τα παραπάνω?

Ακόμη παίρνω:

API Call failed! The error was: Your Order Code is:

**Comment by defilerc** [comment]
Καλημέρα @yperaksia ,

Μπορείτε να δοκιμάσετε τη λύση που περιγράφεται στο παρακάτω thread:
https://github.com/VivaPayments/API/issues/144

και να μας πείτε αν αυτό έλυσε το πρόβλημά σας;

Ευχαριστούμε πολύ.

**Comment by yperaksia** [comment]
Ναι το πρόβλημα λύθηκε! Θα το δοκιμάσω και στο native και επανέρχομαι.

Σημείωση: αυτό συμβαίνει μόνο σε TLSv1 ;

**Comment by defilerc** [comment]
Καλησπέρα @yperaksia ,

Στη συγκριμένη έκδοση μας έχουν αναφέρει προβλήματα. Αν παρ' όλ' αυτά, αντιμετωπίζετε κάποιο θέμα και με διαφορετική έκδοση, παρακαλώ πολύ ενημερώστε μας, ώστε να προβούμε σε νέα διερεύνηση.

Ελπίζω να σας βοηθήσαμε,

Ευχαριστούμε πολύ για την επικοινωνία.
