### ISSUE TITLE
not same price basket and checkout vivawallet

### ISSUE THREAD

**Issue by nakasgroup** [VivaPayments/API#1500]
καλησπέρα εχω ενα asp site ... hartinipoli.gr
εχω ενα πρόβλημα και θελω τη βοηθεια σας
εχω λογαριασμο στο στη viva. ανοιξα κωδικο πληρωμης και εκανα τη συνδεση στο με το site στη πλατφορμα του viva wallet... αλλαξα και το κωδικα στο site.. μου εμφανιζει το παραθυρο να βαλω τα στοιχεια της καρτας μου αλλα δε συγχρονίζετε η τιμη των προιοντων με την πληρωμη που πρεπει να γινει... τι εχω κανει λαθος ?
ευχαριστω πολυ

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Are you using our [Native Checkout](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) for integration with Viva Wallet for payments or is it something else? Please let me have a bit more info. about your setup. Thanks!

**Comment by nakasgroup** [comment]
I don't use the native checkout v2 3dsI am using sample checkout...NAKAS GROUP | Christos Papathodoris
-------- Αρχικό μήνυμα --------Από: matthewrgourd <notifications@github.com> Ημερομηνία: 26/3/20  15:13  (GMT+02:00) Προς: VivaPayments/API <API@noreply.github.com> Κοιν.: nakasgroup <dtp@nakasgroup.gr>, Author <author@noreply.github.com> Θέμα: Re: [VivaPayments/API] not same price basket and checkout vivawallet
  (#1500) 
Hi there, sorry to hear this. Are you using our Native Checkout for integration with Viva Wallet for payments or is it something else? Please let me have a bit more info. about your setup. Thanks!

**Comment by matthewrgourd** [comment]
Hi @nakasgroup for Simple Checkout, please follow our guide here https://developer.vivawallet.com/online-checkouts/simple-checkout/ which we updated recently.
