### ISSUE TITLE
Problem with checkout

### ISSUE THREAD

**Issue by CristinaCollins** [VivaPayments/API#1501]
Hello,
I have a problem with your plugin, the same that other users have reported at checkout.
I took a look at the backoffice and found these errors:

2020-03-25T17: 01: 19 + 00: 00 CRITICAL Uncaught Exception: Unable to create order code (The merchant with id (...) does not have a source with code '3120' assigned or the source is disabled) in (...)/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php:343
Stack trace:
# 0 (...) / wp-content / plugins / vivawallet-for-woocommerce / wc-vivawallet.php (453): WC_VIVAWALLET-> generate_form (1459)
# 1 (...) / wp-includes / class-wp-hook.php (288): WC_VIVAWALLET-> receipt_page (1459)
# 2 (...) / wp-includes / class-wp-hook.php (312): WP_Hook-> apply_filters ('', Array)
# 3 (...) / wp-includes / plugin.php (478): WP_Hook-> do_action (Array)
# 4 (...) / wp-content / plugins / woocommerce / templates / checkout / order-receipt.php (44): do_action ('woocommerce_rec ...', 1459)
# 5 (...) / wp-content / plugins / woocommerce / includes / wc-core-functions.php (251): include ('/ home / in (...) / wp-content / plugins / vivawallet- for-woocommerce / wc-vivawallet.php on line 343

and in the system state of woocommerce instead it tells me that the plugin has not been tested with the new version of woocommerce.

![Schermata 2020-03-26 alle 10 51 46](https://user-images.githubusercontent.com/62695655/77633881-63c2d080-6f50-11ea-8569-92f5221cf692.png)

How can I resolve?

**Comment by matthewrgourd** [comment]
Hi @CristinaCollins, sorry to hear this. Can you let me have your website address or business name and I'll investigate? Thanks!

**Comment by CristinaCollins** [comment]
This is my brand name: eliteweed

**Comment by matthewrgourd** [comment]
Hi @CristinaCollins thanks for that. I can see that you have the wrong payment source specified in your WooCommerce settings. Please try "3182" instead of "3120". You can disregard the version error.

**Comment by CristinaCollins** [comment]
Yes, I just wanted to hide the source code by putting a dummy one..

**Comment by matthewrgourd** [comment]
Ok. Well we don't currently have any reported issues with our plugin. This looks like a problem very much relating to the source code. Please confirm the actual source code used in your WooCommerce settings in order to avoid confusion. It is ok to publish this as long as you don't provide any other details about your account.

**Comment by CristinaCollins** [comment]
The source code you mentioned earlier is the correct one and has already been included in the backoffice.

**Comment by CristinaCollins** [comment]
These are the plugin errors reported:

2020-03-25T17: 01: 19 + 00: 00 CRITICAL Uncaught Exception: Unable to create order code (The merchant with id (...) does not have a source with code '3182' assigned or the source is disabled) in (...)/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php:343
Stack trace:

0 (...) / wp-content / plugins / vivawallet-for-woocommerce / wc-vivawallet.php (453): WC_VIVAWALLET-> generate_form (1459)
1 (...) / wp-includes / class-wp-hook.php (288): WC_VIVAWALLET-> receipt_page (1459)
2 (...) / wp-includes / class-wp-hook.php (312): WP_Hook-> apply_filters ('', Array)
3 (...) / wp-includes / plugin.php (478): WP_Hook-> do_action (Array)
4 (...) / wp-content / plugins / woocommerce / templates / checkout / order-receipt.php (44): do_action ('woocommerce_rec ...', 1459)
5 (...) / wp-content / plugins / woocommerce / includes / wc-core-functions.php (251): include ('/ home / in (...) / wp-content / plugins / vivawallet- for-woocommerce / wc-vivawallet.php on line 343

**Comment by CristinaCollins** [comment]
And in the system state of woocommerce this error is shown: 
"Not tested with the active version of woocommerce" (last one)

**Comment by matthewrgourd** [comment]
In that case, I'm raising with our dev team. It does sound like a problem with our plugin...I take it you recently installed WooCommerce so are using the latest version of this?

**Comment by matthewrgourd** [comment]
However, @CristinaCollins, how come the first error " does not have a source with code '****' assigned or the source is disabled)" I don't understand how your Viva Wallet settings can be correct if you're receiving this error. Have you tried all the different source codes you seem to have created within your account?

**Comment by CristinaCollins** [comment]
Yes, I have already tested several source codes on a tip from your Italian team

**Comment by matthewrgourd** [comment]
@CristinaCollins, sorry you're still experiencing setup issues. I'm going to raise with our development team and get back to you. Thanks!

**Comment by matthewrgourd** [comment]
Hi @CristinaCollins I've spoken with our developer who advises me our plugin definitely works with the newest version of WooCommerce. I've never seen this issue before so maybe uninstall and start again with a fresh [download](https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip) of our plugin while referring to our [installation instructions](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/)?
