### ISSUE TITLE
WooCommerce Vivawallet - Integration | New Website / App Inactive

### ISSUE THREAD

**Issue by gullivergreece** [VivaPayments/API#1503]
Hello.
I just received an email from Viva Wallet that the domain athinarose.gr was not approved (Website / Mobile App).
I am the developer of this e-shop and I have already completed the test on the demo site.
I act on behalf of the owner of the account Miss Eirini Gourdi.
Merchant ID: ****2e**-2281-4670-****-b02ceb1e***
What is the problem?
Please advise asap.

**Comment by gullivergreece** [comment]
I want to add here (maybe what causes the problem) that my web site is under development still and it need password login to access it...

**Comment by matthewrgourd** [comment]
Hi @gullivergreece sorry to hear you're frustrated but I believe what you've been advised is 100% correct. We do need to have a completely accessible site showing terms and conditions and various other things before we can make a payment source active. So please follow the exact advice given to the account owner. Thanks! By the way, I'm obscuring part of your Merchant ID from the above for security reasons

**Comment by gullivergreece** [comment]
OK. Thanks a lot.
I will retry when the site will be live and available to the public.
