### ISSUE TITLE
Not redirecting back to site afterpayment

### ISSUE THREAD

**Issue by zabbetas** [VivaPayments/API#1505]
Hello
i have implemented my site www.cardou.com with wordpress.
My issue is that after a sale i get a screen with a -1(image1) regardless of success or fail,
please advise
thank you
![1](https://user-images.githubusercontent.com/62714414/77675275-672c7b00-6f95-11ea-8750-799158b4d10e.jpg)
![2](https://user-images.githubusercontent.com/62714414/77675287-698ed500-6f95-11ea-8ddf-fdd3c355abdb.jpg)
![3](https://user-images.githubusercontent.com/62714414/77675290-6b589880-6f95-11ea-9517-e52935ec769c.jpg)
![4](https://user-images.githubusercontent.com/62714414/77675293-6c89c580-6f95-11ea-8ecc-c775c48d53df.jpg)
![5](https://user-images.githubusercontent.com/62714414/77675300-6e538900-6f95-11ea-8c34-4d7d42cd2d1a.jpg)

**Comment by matthewrgourd** [comment]
Hi @zabbetas unfortunately you've installed an unofficial Viva Wallet plugin. Please uninstall and visit https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ for the installation instructions. A download link for our official plugin is given under [Prerequites](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#prerequisites) at the top of the page. Thanks!

**Comment by zabbetas** [comment]
Thanks!

 

Now everything seems to be working fine, I just installed the correct app!
