### ISSUE TITLE
Multiple failed payments without any obvious Errors? 

### ISSUE THREAD

**Issue by unclemuzy** [VivaPayments/API#1506]
Hi Matthew, 

Sorry to trouble you again but I've noticed a chain of incomplete order transactions and messages from customers this afternoon who have tried and failed to process payments after reaching the VivaWallet pages. 

They are all reporting that they are entering their payment details, clicking to confirm, and then being redirected back to the website with an error message that simply states "an error occurred, please try again later"

I've looked through the control panel, the back end of the website, and the SQL database and I cannot find any indication as to why this is happening. We've had successful transactions as well, so I know the site has been working and processing orders, but we've lost about £300 in sales in the last few hours and cannot afford to let this go unchecked. 

Please can you be of some assistance, as the telephone support staff just direct me to make a new ticket here. 

Thanks in advance & #StaySafe!

- Stefan

**Comment by Alex444555** [comment]
We've had the exact same issue, started 25th March

**Comment by matthewrgourd** [comment]
Hi @unclemuzy very sorry to hear this. Can you just remind me, is it our WooCommerce plugin you're using?

**Comment by unclemuzy** [comment]
Hi @matthewrgourd yes that's right. And the failed transactions now stand at a total of £1,025 which is almost the same as the total amount of successful transactions (granted some are repeated attempts) but as I am sure you can appreciate this is extremely concerning!

**Comment by Alex444555** [comment]
Hi, yes, your official one. And yesterday I downloaded it AGAIN and reinstalled it in an attempt to fix the issue but it didn’t

 

Regards,

 

Alexander Bullivant

 

 <https://www.roxbourne.com/> ROXBOURNE.COM | MOB: 07795-622551

 

High-impact E-commerce, Web Design and Digital Marketing Services

 



 

This e-mail and the information it contains may be privileged and/or confidential. It is for the intended addressee(s) only. If you are not the intended recipient, disclosure, copying, distribution or any action taken or omitted to be taken or reliance upon it, is prohibited and may be unlawful. The contents may be legally binding. If you are not the intended recipient, please notify the sender immediately and delete the message from your system.

**Comment by unclemuzy** [comment]
The problem continues... :( 

![image](https://user-images.githubusercontent.com/39371225/77759466-abb72580-702c-11ea-8f85-13608c80f038.png)

**Comment by unclemuzy** [comment]
Still happening - haven't had a successful transaction now for about 4 hours

**Comment by Alex444555** [comment]
We rang Viva and they have now fixed the issue their end.

**Comment by unclemuzy** [comment]
@Alex444555 
> We rang Viva and they have now fixed the issue their end.

Lucky! The only response I ever get when I call them is "open a ticket on GitHub"

Out of interest did they provide any details / explanation or insight into what is (or was?) causing the problem?

**Comment by unclemuzy** [comment]
@matthewrgourd We are still receiving complaints from customers saying they are unable to process payments. Please can you advise what we need to do to get a response on this matter?

**Comment by unclemuzy** [comment]
@Alex444555 are you sure the issue is resolved for your site? I am still seeing more failures than successful transactions here, and unfortunately I do not seem to be getting any kind of meaningful response from VivaWallet themselves.

**Comment by unclemuzy** [comment]
Still no response on this issue?

**Comment by Alex444555** [comment]
![Screenshot-(81)](https://user-images.githubusercontent.com/62745229/77824649-2ac75f00-70fc-11ea-897f-cd715531e9b5.jpg)

**Comment by Alex444555** [comment]
I updated all Wordpress plugins and theme to latest versions. I am using WooCommerce, WP Rocket, Wordfence Security and iThemes security. Have deleted, redownloaded and reinstalled the official WooCommerce Viva Wallet Gateway plugin. None of that fixed the payments issue. I read all the threads here on GitHub, found nothing that helped. The boss rang Viva and they said they were working on a fix of a known issue, then suddenly orders started coming through on Thursday with payments complete. The new industry-wide 3D Secure end step does cause some payment failures, but that may be just customer-only issues. You may have multiple issues, which obviously makes it hard to fix. Particularly check all the settings in your Viva Wallet account and in WooCommerce/Payments and in your caching plugin.

**Comment by matthewrgourd** [comment]
Hi @unclemuzy, @Alex444555 we've checked for you and there is definitely no problem at the Viva Wallet end. If the the 3DS is activated that means our plugin is working fine. Any errors after that are 100% related to 3DS authentication failures. Customers with declined cards should contact their card issuers. Hope that helps! Best regards.

**Comment by Dragonvapour123** [comment]
Hi, 

Has this issue been resolved? It is driving me mad because all my payments are getting declined. 

Thanks, 

Amun

**Comment by unclemuzy** [comment]
Hi Amun ( @Dragonvapour123 )

I'm afraid not. In our case we ended ultimately up integrating paypal to the website and using them instead as almost 50% of the attempted payments were failing over the period in question and we were unable to get through to anyone who could help via the telephone and never received the promised call backs. 

It might have been a different situation if we were able to look through logs or see some kind of reasoning as to why transactions were failing, but the only message posted back to the website was "Sorry there has been an Error" so we werent able to do any real form of troubleshooting or investigation even. 

I hope you have a better experience.

- Muzy

**Comment by Dragonvapour123** [comment]
@unclemuzy Thats is terrible. I've been trying to contact them all weekend and they are impossible to get hold of in the UK. I spoke to people in Greece and it's like they can't process that we are losing sales. Ridiculous. I see above they tried to blame the banks, well that is impossible really because not every bank would reject transactions all of a sudden.

**Comment by matthewrgourd** [comment]
Hi @unclemuzy, I did a bit more investigating. 

I've spoken with someone from our development team who advises the following:

> Chrome 80 is gradually deploying a new cookie policy in their browser, problems will occur with payment systems that use the redirection method. Most e-commerce platforms are not prepared to set the cookie in the new format, so in most cases the customer will lose his session when getting returned to the store. Payment plugins that are not adjusted will see problems with lost sessions (customer has to login again and with some plugins lost orders). 

I'm not 100% sure but it's possible this could be happening. Until we have a fix if you could maybe get your customers to try a different browser if they're having problems. Apologies, but this only just came through today after a long bank holiday weekend.

**Comment by matthewrgourd** [comment]
Hi all, just to let you know we've done a thorough check through our plugins and there are currently no coding errors. There is a fix being applied for the Chrome cookie mechanism I mentioned but this is actually in advance of it being released on Chrome so won't affect anything. I'm closing this issue now. Thank you!
