### ISSUE TITLE
Access to Simple Checkout API

### ISSUE THREAD

**Issue by iromarkaki** [VivaPayments/API#1507]
Hello,

We would like access to the Simple Checkout API for our demo Tenant. 
The tenant ID is: 238fa41c-2c8a-4835-8c74-93db06b8beb0

Thank you.

**Comment by matthewrgourd** [comment]
Hi @iromarkaki I can't seem to enable for that account. Can you try [registering](https://demo.vivapayments.com/) another demo account this time entering fuller details? Thanks!
