### ISSUE TITLE
Partial refund in Native Checkout v2 3DS

### ISSUE THREAD

**Issue by vaskou** [VivaPayments/API#1508]
Hello,

I'm trying to do a partial refund 24 hours after the payment with the Native Checkout v2 3DS but 
I'm getting the message:
`Refund is disabled for the merchant 1ef183eb-94de-44dd-b682-3c404f74a267`

I'm getting the same message when I do a full refund 24 hours after the payment, but when I do a full refund 1-2 minutes after the payment it works fine.

The full response is:
`{"status":403,"message":"Refund is disabled for the merchant 1ef183eb-94de-44dd-b682-3c404f74a267","eventId":"0"}`

**Comment by matthewrgourd** [comment]
Hi @vaskou that's your demo account Merchant ID, right? I've checked and refunds are definitely enabled. Did you find that setting in the banking app? If this is solved now, please close the issue.

**Comment by vaskou** [comment]
Yes it's my demo account. 
Yes that setting is in the banking app and it was enabled before.

My problem is that I can do a **full** refund 1-2 minutes after the payment, but not a **partial**. 
If I try a partial refund 1-2 minutes after the payment, I get the response `PaymentsInvalidAmountForVoid`.

If I do a **full** or a **partial** refund 24 hours (a day) after the payment I get the response `Refund is disabled for the merchant 1ef183eb-94de-44dd-b682-3c404f74a267`.

![screenshot](https://user-images.githubusercontent.com/2781587/77746524-b3bf9700-7025-11ea-9363-4181c579a600.png)

As you can see in the image I've done a **full** refund via Native Checkout v2 3DS about a minute after the payment.

I've tried to do a refund **(partial and full)** via Native Checkout v2 3DS, for the payment that was done at 26/03/2020 12:55:33, today but I get the response with the disabled merchant message. As you can see there is also no cancel button for that order, so I can cancel it manually.

**Comment by matthewrgourd** [comment]
Hi @vaskou, sorry for the delayed response. I will need to raise with our development team and get back to you. Thanks!

**Comment by matthewrgourd** [comment]
Hi @vaskou my understanding is that you can only do a partial refund once the payment has cleared (24 hours). Before that you're limited to a full refund only. Hope this helps.
