### ISSUE TITLE
Shopify Plugin Generic Error.

### ISSUE THREAD

**Issue by rounsmith** [VivaPayments/API#1509]
Hello again. Same problem still exists. 

Is there any generic problem with viva wallet here in Greece? At the past few days we have so many transactions and most of clients want to pay through credit or debit card for contactless delivery. Only payments through paypal going through.

And generic error is back. 

Was working fine until 24/3/2020. Do we need to call viva wallet support here in Greece or?

(We have so many decline payments through cards that go through paypal after from same card).

P.s. I wrote two days ago with same issue on another issue that we closed.

![image](https://user-images.githubusercontent.com/61347180/77743976-938dd900-7021-11ea-8d80-b32764327f0b.png)

**Comment by matthewrgourd** [comment]
Hi @rounsmith, I've checked with our development team and I'm told there's definitely no generic error with our Shopify plugin. So it must be your settings, but I don't know an immediate answer, I'm afraid. I'll have to speak to the devs again!

**Comment by rounsmith** [comment]
We haven't changed anything in our settings(neither inside viva or on plugin on shopify).

Btw it was never on test mode.

It's general increase in volume because of COVID-19. After 24/3 from like 30-40 transactions 1 went through (people with same card are paying through SAME CARD with paypal can't with viva).

Before 24/3 we had no problem.

**Comment by matthewrgourd** [comment]
@rounsmith one of our senior developers is checking the logs for you. I'll get back to you once I've an update.

**Comment by rounsmith** [comment]
Thank you very much for the assistance!

**Comment by rounsmith** [comment]
Update: 

Customer contacted us and said "I was going through the payment and my bank asked for confirmation to pay (via sms) he did that correctly and viva rejected the payment,did that twice".

I write this considering the too many declined payments from Viva.

**Comment by rounsmith** [comment]
Any update? I saw on #1506 that someone rang Viva and they fixed it for them but when my boss rang them they said to address you here on github. We have lost too many sales past 5 days :/

**Comment by matthewrgourd** [comment]
Hi @rounsmith, sorry for the delay. Apparently if your customers get to the 3DS authentication popup, that means our plugin is working correctly. Can you confirm that's what is happening?

**Comment by rounsmith** [comment]
Well pop is working and says to press continue (i don't press anything since it does redirect me anyway to the site of the merchant). Thing is it has a progress bar when the pop up goes off goes to 50% and redirects me to our site with decline payment error.

P.s. I tested it with my working card that i payed for groceries this morning online (so it works).(mastercard)

If it's not problem from your plugin, even if i call here in Greece Viva Wallet they will redirect me again here in GitHub. How can i actually speak to someone to see our merchant account in Greece or someone from your part look at our account?

**Comment by matthewrgourd** [comment]
Hi @rounsmith, as I say, if you see the 3DS popup during a payment attempt, that means our plugin is working fine. Anything beyond that, e.g. declined payment, is handled by the card issuer. Best regards.

**Comment by rounsmith** [comment]
Ok then. 

Can you raise an issue in your company since the Viva Wallet representatives here in Greece don't pickup phones or answer to email's regarding this issue?

We have email them again 2 days ago and they don't pickup the phone (it's ringing not occupied). 

We need to fix this issue since we had no problem until 25th of March and after that our customers can't pay with viva wallet. It's viva wallet issue not from our part afaik.

**Comment by Dragonvapour123** [comment]
Has this been resolved? I'm having the same issue and the support at Viva Wallet is atrocious. I'm loosing sales every minute at the moment
