### ISSUE TITLE
Global Error

### ISSUE THREAD

**Issue by mikaghp** [VivaPayments/API#1510]
Dear,

All our websites which works with VivaWallet doesn't works.
Please find error as soon as possible.
Find attached all error log. there is issue in CURL request.
Please solve the probleme.

![WhatsApp Image 2020-03-27 at 10 37 12](https://user-images.githubusercontent.com/62746066/77745411-7fdf7400-701b-11ea-97dd-56c2488c7116.jpeg)
![WhatsApp Image 2020-03-27 at 10 51 16](https://user-images.githubusercontent.com/62746066/77745416-82da6480-701b-11ea-9ff2-59aec2d9e29c.jpeg)

**Comment by matthewrgourd** [comment]
Hi @mikaghp, sorry for the issue. This is due to a general problem with our acquiring service which we're working on.

**Comment by matthewrgourd** [comment]
Hi @mikaghp I've just been told service is back up! Please keep me informed if any future failure but you should be fine now. Best regards, Matt
