### ISSUE TITLE
27/3/2020 Money Transfer Cancelled 3 times

### ISSUE THREAD

**Issue by Shipwright61** [VivaPayments/API#1512]
Hello,
I am having a problem transfering Money to a Bank account. I have tried 3 times and each time it has been cancelled. I cannot understand why. All the details are correct.

My Name: ANTHONY TUCK OF EDWARD
Account: Commercial Account.
IBAN: GR8670100000000726389991162

I am trying to pay this account:

Account Name: Istiorafio o.e.
IBAN: GR6701103990000039900167568
Bank Name: National Bank of Greece
Amount To Pay: 1612.00 euro

Please can you assist me.

Anthony Tuck
email: tonyetuck@hotmail.com

**Comment by Shipwright61** [comment]
Hello,
I am having a problem transfering Money to a Bank account. I have tried 3 times and each time it has been cancelled. I cannot understand why. All the details are correct.

My Name: ANTHONY TUCK OF EDWARD
Account: Commercial Account.
IBAN: GR8670100000000726389991162

I am trying to pay this account:

Account Name: Istiorafio o.e.
IBAN: GR6701103990000039900167568
Bank Name: National Bank of Greece
Amount To Pay: 1612.00 euro

Please can you assist me.

Anthony Tuck
email: tonyetuck@hotmail.com

**Comment by matthewrgourd** [comment]
Hi there, please contact your local support number for any account queries. I'm going to remove the bank account info. you posted as it's a security risk. Sorry I can't help any further!

<table><tr><th>Country</th><th>Phone number</th>
  <tr><td>Belgium</td><td>(+32) 2342 0790</td></tr>
    <tr><td>Cyprus</td><td>(+357) 2403 0211</td></tr>
    <tr><td>France</td><td>(+33) 1876 50765</td></tr>
    <tr><td>Greece</td><td>(+30) 21 1760 4000</td></tr>
    <tr><td>Netherland</td><td>(+31) 2089 05503</td></tr>
    <tr><td>Romania</td><td>(+40) 3122 96150</td></tr>
    <tr><td>UK</td><td>(+44) 20 3734 7770</td></tr>
    <tr><td>Portugal</td><td>(+351) 3 0050 9059</td></tr>
</table>

**Comment by matthewrgourd** [comment]
By the way, I did just quickly check your account although I'm not trained in this area and I could see what looks to be a successful transfer for that amount to that person but I could be wrong.
