### ISSUE TITLE
Issu payment

### ISSUE THREAD

**Issue by CBDBICYCLETTE** [VivaPayments/API#1513]
Good afternoon, 

I open a new issu because my customers still have some trouble with the payment system.
The last one is florentin Louail, he tried 3 times to buy an item but it doesn't work. 

Benjamin Queyrel alose tried this morning with a 34€ order. His bank (society général) said the payment was ok but actually it failed. 

Please could you check it quicky ? I

It s a real problem for me, i would like to spend a lot of money in an advertising campaign with google ads and FB ads but i have to be sure that the customers will be able to buy my product. 

If the problem can not be solved, i will have to check other payment platform for my website. 

Thanks for your answer. 
Best regards

Morgan Ben Haim
CBD Bicyclette

https://cbdbicyclette.fr
morganbenhaim@gmail.com

**Comment by matthewrgourd** [comment]
Hi @CBDBICYCLETTE, sorry to hear this. You mentioned before it could be a smartphone problem. I'm testing that now.

**Comment by CBDBICYCLETTE** [comment]
Yes but this time it was a computer order

**Comment by matthewrgourd** [comment]
Hi @CBDBICYCLETTE the last time I checked via my desktop and this time I tested via a mobile. Both are routes work fine with a card I use for this purpose. This is going to be a problem that comes up from time to time with individual customers. I'm afraid you need to get them to speak to their issuers. The 3DS popup is meant to prevent fraud and was introduced as an additional layer of security by the recent PSD2 SCA legislation. I've fully tested and our plugin is working fine.

**Comment by CBDBICYCLETTE** [comment]
Ok thanks you for the check. 

I will close the issu. I hope it will be fine. 
Thanks you
