### ISSUE TITLE
No mastercard payments 

### ISSUE THREAD

**Issue by kostasmultimedia** [VivaPayments/API#1516]
Goodevening
I use Eshop Joomdonation in my Joomla eshop site. I use Vivawallet payment plugin for the last 10 months. Everything works fine until Yesterday. 
My customers said me that only VISA card payments can be used... NOT Mastercard!!
I always use redirection to vivawallet payment  and when my customers try fill the Mastercard data , after transition ... a Error appears.. and no payment exists!! 
It s bizzare that because everything worked fine in last months and other my customers tried with VISA and everything was OK.
What can i do now? Unfortenatully Mastercard card payment is very important for my eshop !
Did you ever heard similar problem?
Yours
Kostas

**Comment by matthewrgourd** [comment]
Hi @kostasmultimedia sorry to hear this. Could I have your business name / website address and I'll check for you?

**Comment by kostasmultimedia** [comment]
Goodevening
My website is 
https://www.corc.gr/

Thank you in advance for your support

**Comment by matthewrgourd** [comment]
Hi @kostasmultimedia can you confirm your Merchant ID by sending to my email (mgourd@vivawallet.com)

**Comment by matthewrgourd** [comment]
Hi @kostasmultimedia, after checking your account, my colleague found that you weren't 3DS enrolled with Mastercard. This should be fixed now. Please close this issue if you believe this to be the case. Thanks!
