### ISSUE TITLE
error 500 viva payment hikashop

### ISSUE THREAD

**Issue by kotheor** [VivaPayments/API#1517]
Unfortunately no. You can go to https://www.dpaper.gr/proionta/product/1-xartotainia5740.html now and try to pay with Viva Wallet. You'll see that it gets stuck on the redirection page.

**Comment by matthewrgourd** [comment]
Hi @kotheor, sorry to hear this. How long have you been using this integration? Did it work before?

**Comment by matthewrgourd** [comment]
Hi @kotheor,

Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- [Hikashop] payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
@kotheor please provide more info about your setup otherwise I won't be able to solve your issue. The screenshots are particularly important!

**Comment by kotheor** [comment]
[
![dpaper_pay_viva](https://user-images.githubusercontent.com/61879955/78030657-1ccb4580-736b-11ea-9feb-0394666c9383.jpg)
](url)

**Comment by matthewrgourd** [comment]
Hi @kotheor thanks for that. I've checked your Viva Wallet account and the payment source settings for your website are shown as below:

![Screenshot 2020-04-02 at 10 35 37](https://user-images.githubusercontent.com/44943019/78233548-d8a48600-74cd-11ea-97c8-7885325035a7.png)

I've checked out [Hikashop plugin guide](https://developer.vivawallet.com/e-commerce-plugins/hikashop/) and in fact the failure / success URLs are missing from step 5. May I ask where you got these from?

They're more than likely causing the issue, but I'll need to speak to a developer in order to reach a solution. Please bear with me and apologies for any delay!

**Comment by kotheor** [comment]
app download ( https://developer.vivawallet.com/e-commerce-plugins/hikashop/ )

**Comment by matthewrgourd** [comment]
Thanks. Can you try removing the forward slash (/) from the beginning of the success / failure URLs?

**Comment by kotheor** [comment]
I've done it. The problem was not solved.

**Comment by matthewrgourd** [comment]
Hi @kotheor sorry to hear this. I'm not sure what the problem is. I'll need to raise with a developer and get back to you.

**Comment by kotheor** [comment]
have not received an answer yet. I want to complete payments on my website via viva.

**Comment by matthewrgourd** [comment]
Hi @kotheor sorry for the delay, can you confirm your company VAT number so I can find your account quickly again?

**Comment by matthewrgourd** [comment]
@kotheor I need you to confirm that your company name is ΘΕΟΔΩΡΑΚΟΠΟΥΛΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ ΦΩΤΙΟΣ with a VAT number of EL079053181. If that is the case, I don't see a payment source set up for dpaper.gr with a source code of 4600. You need to set one up in your account back-end as described in steps 1 to 6 of our guide: https://developer.vivawallet.com/e-commerce-plugins/hikashop/
