### ISSUE TITLE
Implementare/Implementation Viva Wallet Online payment on Wix Restaurants Website

### ISSUE THREAD

**Issue by sebi75** [VivaPayments/API#1518]
Hello,

I have an issue imlementing Viva Wallet online payment on Wix, as I have a Wix Restaurants Web Site
with the link wegrill.ro. I have the ID client, API key, I just need help to make it work with the website.

**Comment by matthewrgourd** [comment]
Hi @sebi75 we don't currently provide a plugin for Wix, how are you attempting the integration?

**Comment by sebi75** [comment]
This is the reason for this ticket, exactly I don't know how to install and implement Viva Wallet on the site, and I was told this is possible with some API I think and as well I was told to open a ticket here, that is possible to implement.

**Comment by matthewrgourd** [comment]
Hi @sebi75 I'm afraid we don't have an out-of-the box plugin available for Wix. Its supported payment provider list is here: https://support.wix.com/en/article/available-payment-providers-3848246

**Comment by sebi75** [comment]
I understand, but I heard it is possible without an e-commerce plugin, but with the API key and ID, and it is more complicated.

**Comment by sebi75** [comment]
Can someone help?

**Comment by matthewrgourd** [comment]
@sebi75, if you come from a development background, you can attempt an implementation of our [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/). Alternatively, our [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) is another option.

**Comment by sebi75** [comment]
https://prnt.sc/rq1nyr
https://prnt.sc/rq1pnp
So we already have 2 payment options, but it is not online, and I don't know how to add it as I'm am not really a developer, and display it like the others on the checkout page, and make an action of confirmation after payment...

**Comment by matthewrgourd** [comment]
Hi @sebi75 given what you've told me I advise you to use a different payment option as I won't be able to guide you through this except to point you to our documentation as I already have done. It sounds to me like you need an off-the-shelf payment plugin which unfortunately at this moment in time Viva Wallet doesn't specifically provide for Wix.
