### ISSUE TITLE
Native Checkout v2 3DS - PaymentsCardHolderAuthenticationInvalidStatus

### ISSUE THREAD

**Issue by kalgik** [VivaPayments/API#1519]
Hello everyone.

I would like to use the whole flow of Card Tokenization API (https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/) in Postman.I followed the steps as they described. The authentication took place successfully,I generated card token successfully [https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/#step-1-generate-one-time-charge-token-using-card-details](url) , and when I am going to do the actual [payment()](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/#step-4-make-the-actual-charge), I received  the following `{
    "status": 400,
    "message": "PaymentsCardHolderAuthenticationInvalidStatus",
    "eventId": "2061"
}`

I am using a demo account. Is it possible to do a test transaction with a demo account or not (pass from 3DS successfully)?

Regards,

**Comment by matthewrgourd** [comment]
Hi @kalgik unfortunately it is not possible to test the 3DS properly apart from in the live environment. Thanks.

**Comment by kalgik** [comment]
Hi @matthewrgourd.

So, shall I try with a real valid card or is any way to simulate a real card (e.g. 19 digits as I read somewhere, 4016000000040000012)  in the live environment?

Regards,

**Comment by matthewrgourd** [comment]
HI @kalgik, in live environment, a real card is the only option currently, I'm afraid.
