### ISSUE TITLE
ΑΝΑΒΑΘΜΙΣΗ

### ISSUE THREAD

**Issue by diatrofologiki** [VivaPayments/API#152]
Καλησπέρα,

Θα γίνει αναβάθμιση της πλατφόρμας (αλλά όχι αλλαγή domains)!

Θα υπάρξει αλλαγή στους κωδικούς μου ή όχι?

**Comment by krakenrules** [comment]
Γεια σας,
Οι κωδικοί που σχετίζονται με τον λογαριασμό αλλάζουν από την ενότητα Ρυθμίσεις | Πρόσβαση API (API Key) από εσάς.  (πχ για το demo περιβάλλον http://demo.vivapayments.com/selfcare/el-gr/security/apiaccess)
To API Key θα πρέπει να παραμείνει το ίδιο και στην νέα πλατφόρμα.

Ευχαριστούμε πολύ για την επικοινωνία.
