### ISSUE TITLE
Struggling to move website/app online payment source from Pending to Active.

### ISSUE THREAD

**Issue by 5PENC3** [VivaPayments/API#1520]
Hello.

I have received the following automated email about what needs to be done before these payment sources are approved and set to active. To my knowledge everything has been provided but it has been over 7 days and it is still pending. 

The website in question in Supremecbd.uk

Any help on what is missing from the website integration would be helpful. This is the automated email;

**Dear Sir or Madam, We are emailing you today regarding the approval of the URL: https://supremecbd.uk/Before we can process the approval of the site, you will need to integrate the following:
 1) The Terms of Use that need be accepted by the consumer during the distant transaction. You should consult your legal services dept. regarding this.
2) The contact details of the company and other relevant information, such as VAT Identification Number, Email Address, Contact Number and Address of the Head Office.
3) The ability to select/purchase products. 

In addition to the above, it is necessary to include Viva Payments as an online payment solution using the HTTPS protocol (at least at the payment stage). 

Please see the link to our Viva Wallet logo here:https://support.vivawallet.com/hc/en-us/articles/201897841-Can-I-use-the-Viva-Wallet-logo-on-my-website- Once you have actioned the above, please respond to this email to inform us you have done so. We will then be able to proceed to all necessary further steps. Please note, that if more than 15 calendar days have elapsed and we have not received a response, our company may reject the URL.**  

Thank you
Chris

**Comment by matthewrgourd** [comment]
Hi @5PENC3 Sorry for the delay. You need to make sure all those things are done before we can activate the payment source. As far as I'm aware, these should all be applied to your website at https://supremecbd.uk/ Please reply to the email once completed...

**Comment by 5PENC3** [comment]
Hi Mathew

As far as I am aware we have done all of the things required. Are you able
to provide me with more detail as to which criteria has not been met?

Chris

**Comment by matthewrgourd** [comment]
@5PENC3 I'm afraid all you can do is reply to the email we sent and ask the same question. I have no input into this area.
