### ISSUE TITLE
Orders Getting Canceled 

### ISSUE THREAD

**Issue by PontyPrince** [VivaPayments/API#1521]
Hi,

We have noticed that orders in Magento 2 appear to be getting cancelled randonly after the Viva Wallet payment has completed and wanted to know if the API may be causing this for some reason.

Thanks

**Comment by matthewrgourd** [comment]
@PontyPrince let me check your account. Please email me your Merchant ID, business name and website address. My email address is mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
Hi @PontyPrince our developers tell me that when a payment doesn't get through for any reason (e.g. customer failing 3DS or insufficient funds) the request in the back-end remains 'pending' for a period of one day after which it gets cancelled automatically. A message is then sent via the Viva Wallet banking app notifying you of the cancellation.

**Comment by PontyPrince** [comment]
Hi Matthew,

Thankyou for confirming!!

Regards

________________________________
