### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by onetourismo** [VivaPayments/API#1522]
Hi,

We was trying to call the endpoint https://www.vivapayments.com/api/cards for a customer of ours with merchantID : *******b2e0d426

The specific call was the following one:

curl --location --request POST 'https://www.vivapayments.com/api/cards?key=wolqcPaU6di67*****2uuERTV%2BgaVcJFv0%3D' \
--header 'x-viva-native-version: 100' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'Number=4111111111111111' \
--data-urlencode 'CVC=123' \
--data-urlencode 'ExpirationDate=2022-11-15' \
--data-urlencode 'CardHolderName=test'

But we got 401 http code as response.(same thing happens using real card details)
Same endpoint, works when we use public keys from accounts of other customers.

Thank you.

**Comment by matthewrgourd** [comment]
Hi @onetourismo apologies, I'm not quite sure where you got the above from. Our [Card Tokenization API](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/) documentation gives the most up-to-date information about how to do what I think you're attempting. Hope this helps. Btw, for security reasons, I've erased part of the Merchant ID you mentioned in the issue.
