### ISSUE TITLE
Payment not credited properly

### ISSUE THREAD

**Issue by gordhaval** [VivaPayments/API#1523]
Hi there,

I am using vivawallet as payment gateway in my two Shopify stores.  One I receive payment in GBP and another as Euro.

Payment work fine for GBP store, but in Euro store, it's showing customers to paying 45.90 Euro but actual in Viva account its show 45.90 GBP. 

Payment amount should not be same but it should auto convert from Euro to GBP. And that actual amount should credit in my viva account.

Here are screen shot for your reference.

Shopify Store - https://prnt.sc/rntcn8
Viva Wallet -- https://prnt.sc/rnv10m

Look forward to hearing from you ASAP. 

Thanks,
Dhaval

**Comment by matthewrgourd** [comment]
Hi @gordhaval the currency of both your stores has to be set to GBP to match your account currency. Our plugin doesn't work any other way I'm afraid.

**Comment by gordhaval** [comment]
Hi @matthewrgourd , If I set separate Viva account for both stores than It could work properly for GBP and Euro ? As store currency I could not change as we set stores currency accordingly to give currency choice to our customers. Kindly advise if any other way to fix this. Thank you

**Comment by matthewrgourd** [comment]
If you had a separate Viva Wallet account set up in a EUR country, yes, you could do that. But it depends on you having a separate company incorporated in another country other than the UK and there's no workaround, as far as I'm aware.
