### ISSUE TITLE
Access to Simple Checkout API

### ISSUE THREAD

**Issue by Tzimiscegr** [VivaPayments/API#1524]
Καλημέρα σας.
Θα χρειαστώ access στο Simple Checkout API για το merchant id 7a2c****-b70e-****-81df-ecad8f4d***** 

Ευχαριστώ

**Comment by Tzimiscegr** [comment]
Sorry, if you need this in English,
I will need access to simple checkout API for the merchant ID 7a2cf351-b70e-43da-81df-ecad8f4d27bf 
Thank you

**Comment by matthewrgourd** [comment]
Hi @Tzimiscegr that's done now! I'm obscuring part of your Merchant ID in your post for security.
