### ISSUE TITLE
I need access to simple checkout production env.

### ISSUE THREAD

**Issue by peorthyr** [VivaPayments/API#1525]
Good morning, I'd like to switch from test to production, does you have to grant me some kind of access?
what kind of informations do you need?

**Comment by matthewrgourd** [comment]
@peorthyr you need to [register an account](https://app.vivawallet.com/) with us which will involve [verification](https://help.vivawallet.com/hc/en-us/articles/360001352757-What-documents-are-acceptable-for-verification-) by our accounts team.

**Comment by peorthyr** [comment]
we already have an account, I need to access the production environment.
the merchantID is: "10c4c084-e819-4358-9f9b-fc42f15bbfd1"

**Comment by matthewrgourd** [comment]
Ok, that's done now!
