### ISSUE TITLE
Signature Not verified 

### ISSUE THREAD

**Issue by annoyedbeyond** [VivaPayments/API#1526]
No matter what I do, no matter who I request to help. I am being forced to sign up to github with no development skills. 

Vivawallet, your customer service is crap. You should be ashamed. 

These are my settings 
<img width="483" alt="Screenshot 2020-03-31 15 55 10" src="https://user-images.githubusercontent.com/62949313/78040995-1ab3b780-7368-11ea-80eb-0177a2192af9.png">

I have installed the plugin for Shopify and inserted the merchant ID and also the token that was generated for me. 

My account is fully approved and the payment source is approved but no matter what I do, when I try to check out the following screen appears 
<img width="788" alt="Screenshot 2020-03-27 14 39 09" src="https://user-images.githubusercontent.com/62949313/78041226-58184500-7368-11ea-9591-df3bb787a7e1.png">

Why doesn't this work, why can't someone just tell me what I'm doing wrong and tell me if my settings are correct. 

I'm no coder but I have a hunch this is sweet FA to do with code and simply just a lack of documentation on how to implement this gateway using the settings. 

Thanks in advance - Frustrated person

**Comment by matthewrgourd** [comment]
Hi there, you need to request a Shopify token using the form mentioned in our [installation guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/). We will then email it to you. Can I first of all check if you've done this as it's possible our online form is playing up? The form link is https://viva.microsoftcrmportals.com/shopify_request

**Comment by matthewrgourd** [comment]
Ok, apologies, my colleague says you've already received a token. However, from your account settings I can see the Shopify payment source hasn't been set up yet. I'll need to look into this with our development team and get back to you when I've found out a bit more! I can understand your frustration but I promise we're looking into this for you...

**Comment by matthewrgourd** [comment]
Hi @annoyedbeyond I can there are two Viva Wallet Merchant IDs registered with your company name. Can you confirm the last four digits of the correct Merchant ID?

**Comment by matthewrgourd** [comment]
Hi @annoyedbeyond I've worked out which Merchant ID is the correct one and I'm raising with our development team. I'll get back to you as soon as I've a solution to your problem. Thanks for your patience.

**Comment by matthewrgourd** [comment]
Hi @annoyedbeyond we've looked into this and you entered your token incorrectly into the Shopify settings. You added an extra asterisk (*) at the end. Please remove this and you should be fine! Thanks.

**Comment by annoyedbeyond** [comment]
I have done this, still nothing.

Can you please look into other issues that may be causing this?

Kind regards
Paul Moore
Director | GreenMachine CBD Ltd
site:  www.greenmachinecbd.co.uk
email:  paul@greenmachinecbd.co.uk
<https://facebook.com/greenmachineCBD>
<https://instragram.com/greenmachinecbd>
IMPORTANT: The contents of this email and any attachments are confidential.
It is strictly forbidden to share any part of this message with any third
party, without a written consent of the sender. If you received this
message by mistake, please reply to this message and follow with its
deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by annoyedbeyond** [comment]
Hi, 

I have done all of this, tried both with asterix and without, now the asterix is removed and is still doing the same thing. 

Kind regards

**Comment by annoyedbeyond** [comment]
I have tried everything in the shopify plugin guide too.

**Comment by matthewrgourd** [comment]
@annoyedbeyond sorry you're continuing to experience difficulties. I've checked with our Shopify plugin developer and he's given me the correct token. You've correctly dropped the asterisk from the end but I notice there should be an asterisk in the first few digits of the token. So instead of fjVYI^ you should have fjVYI*^ (first seven digits). I can't print the whole thing for security reasons but if you're still having problems please email me directly at mgourd@vivawallet.com and I'll resend the token in its entirety!

**Comment by annoyedbeyond** [comment]
Added the asterix that was missed and now it is working and capturing / processing payments. 

As I said before, I just needed a new store token, or at least the right one. This could have been checked at the very start and saved us all the hassle of raising a github ticket for a typo. Appreciate the help but as I said, massively avoidable errors and over the top to have to go through all of this time wastage for a missed keystroke. 

Kind regards,
