### ISSUE TITLE
Pagamenti negati al 30% dei clienti

### ISSUE THREAD

**Issue by AndreaVacca** [VivaPayments/API#1527]
Da giorni parte dei miei clienti che paga con carta di credito attraverso sistema vivawallet, circa il 30%,   dopo aver compilato tutto il form e cliccato sulla conferma, si vede rifiutato pagamento.

Si prega di eseguire un analisi tecnica per comprendere la natura del problema il più presto possibile.

Questi sono i dati:

Profilo viva wallet intestato a Weweed di Andrea Vacca, 
Sito E-commerce: www.Prodotti-cannabis.it (usiamo woocommerce)
Mail account viva wallet: Andrea.weweed@gmail.com
Attendiamo riscontro,
Cordiali saluti

**Comment by matthewrgourd** [comment]
Duplicate of #1528
