### ISSUE TITLE
ΘΕΛΟΥΜΕ ΝΑ ΒΓΑΛΟΥΜΕ ΤΟ ΤΗΛΕΦΩΝΟ ΑΠΟ ΤΟ SITE

### ISSUE THREAD

**Issue by dresscode24** [VivaPayments/API#153]
Καλησπερα σας,
Θα ηθελα να ρωτήσω πως μπορούμε να βγάλουμε το τηλεφωνο απο το site μας.Με εχουν ενημερώσει οτι μπορούμε να το κανουμε αυτο.

**Comment by defilerc** [comment]
Καλησπέρα @dresscode24 ,

Σε ποιό σημείο ακριβώς αναφέρεστε, όπου εμφανίζεται το τηλέφωνο και θέλετε να το αφαιρέσετε; Μπορείτε να μας στείλετε κάποιο screenshot;

Ευχαριστούμε πολύ.

**Comment by defilerc** [comment]
Καλησπέρα @dresscode24 ,

Ίσως αναφέρεστε στην εμφάνιση της επιλογής για πληρωμή μέσω IVR στην checkout σελίδα. Η επιλογή αυτή μπορεί να αφαιρεθεί, αν κατά τη δημιουργία του create order βάλετε το optional parameter `DisableIVR` ίσο με `true`.

Περισσότερες πληροφορίες, μπορείτε να βρείτε εδώ: https://github.com/VivaPayments/API/wiki/Optional-Parameters

Ευχαριστούμε πολύ
