### ISSUE TITLE
Prestashop Module Installation Probleme

### ISSUE THREAD

**Issue by Franejre** [VivaPayments/API#1530]
Hello everyone i have a big trouble with the vivapayment module 1.7.6  , on prestashop 1.7.6.4.

Iam in native V2 settings 

the probleme is : the order process work perfect, then click finalize payement then get redirected to the vivawallet payment page , make the payment , confirm 3DS , then get redirect to prestashop and the probleme start here:

Error 500 page (link is "fail.php?........")
then if you stay on page and refresh it you get "this shopping card id have already been used"

i have look at the vivawallet error logs in modules folders and get this error

[01-Apr-2020 13:20:02 Europe/Paris] PHP Fatal error:  Uncaught Exception: Kernel Container is not available in /home/cbdptlvp/public_html/src/Adapter/ContainerFinder.php:77
Stack trace:
#0 /home/cbdptlvp/public_html/classes/Tools.php(796): PrestaShop\PrestaShop\Adapter\ContainerFinder->getContainer()
#1 /home/cbdptlvp/public_html/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context))
#2 /home/cbdptlvp/public_html/classes/PaymentModule.php(429): ToolsCore::displayPrice(9, Object(Currency), false)
#3 /home/cbdptlvp/public_html/modules/vivawallet/fail.php(37): PaymentModuleCore->validateOrder(6, '8', 0, 'Vivawallet', 'Transaction fai...', Array, NULL, false, 'b54a0872623c411...')
#4 {main}
  thrown in /home/cbdptlvp/public_html/src/Adapter/ContainerFinder.php on line 77

anyone can help me ? thanks a lot every one

**Comment by matthewrgourd** [comment]
Hi @Franejre sorry to hear this. Are you using any specific transaction amount for testing? What transaction amount was used and is there any info about the transaction in your Viva account? Anything logged in your PrestaShop error log and/or in your PHP error log?

**Comment by Franejre** [comment]
hi , no transaction info in viva account , prestashop error logs only when i refresh the error 500 "modules/vivawallet/fail.php?" i get in prestashop error log: id card already used , its normal because the order is already created.
i think as you can see the vivawallet erorr logs its a problem with the module and prestashop

if you can help me to solve this as soon as possible because it make me loose many sales

**Comment by barmatt75** [comment]
Hi,

I had the same problem on Prestashop 1.7.6.3. I solved it by modifying the fail.php and success.php file. See attached files.
The code below has been added to the files

```
global $kernel;
if(!$kernel){
    require_once _PS_ROOT_DIR_.'/app/AppKernel.php';
    $kernel = new \AppKernel('prod', false);
     $kernel->boot();
}
```
I hope this will help you


[Archive.zip](https://github.com/VivaPayments/API/files/4421344/Archive.zip)

**Comment by Franejre** [comment]
thanks my friend i test this right now , where i add it in the file ?

**Comment by Franejre** [comment]
oh thanks you give me the files thanks a lot i try right now

**Comment by barmatt75** [comment]
In my previous message there is an archive with the files.
You also have to fill in the success and error urls like my screenshot
<img width="583" alt="Capture d’écran 2020-04-02 à 15 37 00" src="https://user-images.githubusercontent.com/7480021/78255958-3d74d600-74f8-11ea-872a-b40caaaf90d4.png">

**Comment by Franejre** [comment]
Francais ? j'ai pas modifier sa dans le compte vivawallet car je suis en native et il te demande pas de preciser les redirect en native ;)

**Comment by barmatt75** [comment]
oui français, ok test ça devrait fonctionner.

**Comment by Franejre** [comment]
je reste sur mon error 500 et si jactualise la page j'obtien
Le panier ne peut être chargé ou une commande a déjà été réalisée avec ce panier

**Comment by Franejre** [comment]
par contre l'error log a changé  / but the error log have changed
[02-Apr-2020 15:51:10 Europe/Paris] PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "idn_to_ascii" from the global namespace. in /home/cbdptlvp/public_html/classes/Mail.php:901
Stack trace:
#0 /home/cbdptlvp/public_html/classes/Mail.php(323): MailCore::toPunycode('djfhdjfdjh@djfd...')
#1 /home/cbdptlvp/public_html/classes/order/OrderHistory.php(552): MailCore::send(2, 'payment_error', 'Erreur de paiem...', Array, 'djfhdjfdjh@djfd...', 'fdfdf ddfjdjfh', 'admin@xxxxx...', 'shop name - L...', NULL, NULL, '/home/cbdptlvp/...', false, 1)
#2 /home/cbdptlvp/public_html/classes/order/OrderHistory.php(468): OrderHistoryCore->sendEmail(Object(Order), Array)
#3 /home/cbdptlvp/public_html/classes/PaymentModule.php(557): OrderHistoryCore->addWithemail(true, Array)
#4 /home/cbdptlvp/public_html/modules/vivawallet/fail.php(48): PaymentModuleCore->validateOrder(13, '8', 0, 'Vivawallet', 'Transaction fai...', Array, NULL, false, '3a6a895c141a405...')
#5 {main}
  thrown in /home/cbdptlvp/public_html/classes/Mail.php on line 901

**Comment by barmatt75** [comment]
Capture de ma config côté Vivawallet au cas ou.
Ton panier actuel est lié à une commande, qu'elle soit valide ou non. Fais un nouveau panier. 

<img width="590" alt="Capture d’écran 2020-04-02 à 15 44 06" src="https://user-images.githubusercontent.com/7480021/78257376-0d2e3700-74fa-11ea-8f58-9eda12bda015.png">

**Comment by barmatt75** [comment]
> par contre l'error log a changé / but the error log have changed
> [02-Apr-2020 15:51:10 Europe/Paris] PHP Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "idn_to_ascii" from the global namespace. in /home/cbdptlvp/public_html/classes/Mail.php:901
> Stack trace:
> #0 /home/cbdptlvp/public_html/classes/Mail.php(323): MailCore::toPunycode('djfhdjfdjh@djfd...')
> #1 /home/cbdptlvp/public_html/classes/order/OrderHistory.php(552): MailCore::send(2, 'payment_error', 'Erreur de paiem...', Array, 'djfhdjfdjh@djfd...', 'fdfdf ddfjdjfh', 'admin@xxxxx...', 'shop name - L...', NULL, NULL, '/home/cbdptlvp/...', false, 1)
> #2 /home/cbdptlvp/public_html/classes/order/OrderHistory.php(468): OrderHistoryCore->sendEmail(Object(Order), Array)
> #3 /home/cbdptlvp/public_html/classes/PaymentModule.php(557): OrderHistoryCore->addWithemail(true, Array)
> #4 /home/cbdptlvp/public_html/modules/vivawallet/fail.php(48): PaymentModuleCore->validateOrder(13, '8', 0, 'Vivawallet', 'Transaction fai...', Array, NULL, false, '3a6a895c141a405...')
> #5 {main}
> thrown in /home/cbdptlvp/public_html/classes/Mail.php on line 901

Pour cette erreur je pense que tu dois installer l'extension php-intl

**Comment by Franejre** [comment]
yes niquel c'est ce que je vien de faire maintenant j'obtien bien la confirmation de commande mais erreur de paiement de la part de vivawallet 
yes thanks its what i did , now i get the confirmation prestashop page but payement error with vivawallet

**Comment by barmatt75** [comment]
Parfait je te laisse voir les reste avec leur support. Bonne vente

**Comment by Franejre** [comment]
vraiement tres gentil de ta part je n'aurai jamais trouver autrement , si je peu aider en quoi que ce soit n'hesite pas

thanks a lot without you i coudnt solve this problem , if need anything let me know

**Comment by Franejre** [comment]
il faut que je configure le webhook ? 
have to configure webhook ? 
iam under native settings

**Comment by barmatt75** [comment]
Not necessary with Prestashop

**Comment by Franejre** [comment]
no more error in error logs , payement and redirection works good thanks to barmatt75 and his files and active php intl in php version

now all card are payement error and not show in vivawallet account ,i try to contact the team to the problem

**Comment by matthewrgourd** [comment]
Hi @Franejre so you got a bit further but you're still receiving an error when attempting to do a test transaction? Could I have your web address and business name, please? I will then investigate further for you.

**Comment by Franejre** [comment]
yes sure , in private please ? or have a mail?

**Comment by matthewrgourd** [comment]
Hi @Franejre please send further details through to myself at mgourd@vivawallet.com quoting this issue number (#1530).

**Comment by matthewrgourd** [comment]
Hi @Franejre thanks for sending through your Merchant ID. I've performed a test transaction with a card with no funds and I see what you mean about nothing showing up on your account. I don't know what you've been advised about modifying files but our plugin should work as it is with no modifications. The success / failure URLs in your payment source settings for source code 8524 are wrong:

![Screenshot 2020-04-03 at 10 40 44](https://user-images.githubusercontent.com/44943019/78347272-2259a300-7598-11ea-825b-10ad6aac9dac.png)

According to our [PrestaShop plugin installation guide](https://developer.vivawallet.com/e-commerce-plugins/prestashop/) (Step 5), if you're using PrestShop 1.7 or greater they should be as below:

Success URL – `module/vivawallet/success`
Failure URL – `module/vivawallet/fail`

You should not need to modify any PHP files.

Hope this helps!

**Comment by Franejre** [comment]
@matthewrgourd , in ftp with prestashop 1.7.6.4 the module folder is called moduleS with an S , the folder module without an S doesnt exist

its original prestashop module folder name i have change nothing on it, it comes as it

for the modded ftp files i have add these line in success and fail php

global $kernel;
if(!$kernel){
    require_once _PS_ROOT_DIR_.'/app/AppKernel.php';
    $kernel = new \AppKernel('prod', false);
     $kernel->boot();
}

else you get these error code and module dont work

PHP Fatal error: Uncaught Exception: Kernel Container is not available in /home/cbdptlvp/public_html/src/Adapter/ContainerFinder.php:77

**Comment by Franejre** [comment]
![Capture d’écran 2020-04-03 à 14 29 42](https://user-images.githubusercontent.com/63005755/78360967-e6ced100-75b7-11ea-852f-bfd3903898c0.png)

**Comment by matthewrgourd** [comment]
Hi @Franejre I'm not sure I can help you further. I was under the impression our plugin was working out of the box. If not, I'll need to pass on to a developer.

**Comment by Franejre** [comment]
just to inform you that everything works fine after changing from native to redirection chekout v2

to inform other people who have same problem :

the information provided on vivawallet merchant page config for prestashop is not good

the path of module have a S at the end for all version 1.7 and you need to name the redirect link with .php at the end  

have a nice day
