### ISSUE TITLE
In french

### ISSUE THREAD

**Issue by dikkydog** [VivaPayments/API#1531]
hello,

Hello,

I have installed the plugin for woocommerce. I would like to know how to put the payment page in French.

Thank you

![vivawallet](https://user-images.githubusercontent.com/21257980/78155026-3e94fd00-743d-11ea-9d47-f3aa0462be03.jpg)

**Comment by matthewrgourd** [comment]
Hi @dikkydog you can make the changes to the WooCommerce plugin yourself by editing the code (wc-vivawallet.php). Specifically this section:

ORIGINAL

`
$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300';
`

NEW 

`
$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang=fr&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300';
`

**Comment by dikkydog** [comment]
great, it works.

thank you so much
