### ISSUE TITLE
implement online payment gateway

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1534]
Hi @matthewrgourd This customer 02649662Q has an issue relation to implement online payment gateway. Client send me the next mail:

 First of all, I want to have the option to change that message, which appears in English in the middle of the payment process. Could be possible?

 Second, system tells me wrong credentials or unavailable API, which I imagine it will be, that even though I got into the vivawallet woocommerce plugin, the API key and user key, which I got in the VivaWallet profile, are still not approved or related. He followed the steps mentioned in official WooCommerce plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
![Kayamagu com](https://user-images.githubusercontent.com/56823712/78265353-9b0f1f80-7504-11ea-9dab-ae02efe9cfaf.JPG)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada can I have the web address and business name for the merchant, please? What is "02649662Q" a VAT number or Wallet ID? I can't find it!

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd sorry, Rodrigo Christian Marzan Diaz and his web is kayamagu.com

**Comment by matthewrgourd** [comment]
@Alvaroalconada no problem, I realise now you were referring to the company registration number! I've changed his settings which were wrong. It should work fine now. Regarding your first question, I'm not sure, it might be a WooCommerce setting where he needs to change the language. Thank you...

**Comment by Alvaroalconada** [comment]
@matthewrgourd Thank very much! let me check with customer if is everything fine, we will close this issue
