### ISSUE TITLE
Implement online payment gateway

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1535]
Hi @matthewrgourd 
This customer, 20813850T, doesn´t know what he has to fill up in each one of the screenshots provided. 
![Captura outletdezapatos](https://user-images.githubusercontent.com/56823712/78268147-145c4180-7508-11ea-89f7-edb5622318d3.png)
![captura restos de zapatos](https://user-images.githubusercontent.com/56823712/78268163-1a522280-7508-11ea-8b03-33dba9a9a0d4.png)

Another issue is that when he has configured the new Webhook he got it this error that I attach in the scrrenshot. I don´t know if it is because he put it wrong or because the module is not yet configured.
![1](https://user-images.githubusercontent.com/56823712/78268198-24742100-7508-11ea-85f1-50a9489465aa.png)

Can you tell me for informing him?

Thanks in advance.

**Comment by matthewrgourd** [comment]
@Alvaroalconada what is this number "20813850T" I'm sorry, is this a VAT number or Wallet ID as I can't find their account? By the way, you shouldn't be posting wallet IDs on the public GitHub. Please, if at all possible can you get customers to post their problems here directly rather than doing so on their behalf? Thank you.

**Comment by matthewrgourd** [comment]
@Alvaroalconada please advise the customer to view our [PrestaShop guide](https://developer.vivawallet.com/e-commerce-plugins/prestashop/) where all of these field values are mentioned explicitly.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada looks like the merchant has two websites. Which one is he attempting to configure for PrestaShop? restosdezapatos.com or outletdezapatos.es ?? Thanks

**Comment by Alvaroalconada** [comment]
Good morning @matthewrgourd He is trying to configure both websites

What about the second question?

**Comment by matthewrgourd** [comment]
@Alvaroalconada regarding the second question, he should delete any webhooks unless they are specifically needed.

**Comment by Alvaroalconada** [comment]
@matthewrgourd customer ask me if data is correct in the next screenshot:
![captura prestashop](https://user-images.githubusercontent.com/56823712/78358784-11b72600-75b4-11ea-8c87-458c27eee0d5.png)

**Comment by matthewrgourd** [comment]
@Alvaroalconada all correct except base URL should be https://www.vivapayments.com

**Comment by Alvaroalconada** [comment]
@matthewrgourd Thx! Customer also comment me that in web restosdezapatos.com is different because the systme gives several options to choose...I send you a screenshot:
![restodezapatos](https://user-images.githubusercontent.com/56823712/78361560-e4b94200-75b8-11ea-9538-167beb827fbf.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada he just needs to make sure the instalments field is blank in the settings page.
