### ISSUE TITLE
Payment confirmation (Magento 2)

### ISSUE THREAD

**Issue by pakagyla** [VivaPayments/API#1536]
Hello ,

We would like to be able to receive a payment confirmation from the api, so we can incorporate it as a reference to our cms to post in order.
Many times we don't know if a payment has been made by the customer, as many of them are never displayed on your vivawallet system. (It takes up to 2 or 3 weeks for payments to appear sometimes)

Awaiting your reply

Best Regards, 
Panos K.

**Comment by matthewrgourd** [comment]
Hi @pakagyla I'm sorry, could you give me a bit more info. Is this regarding a live e-commerce website? If so, please may I have the web address? What is the business name so I can look at your account? Please also send through company registration number.

**Comment by matthewrgourd** [comment]
Hi @pakagyla are you using our plugin for Magento? You're welcome to modify the code if you have PHP experience. Our API documentation is available here:

https://developer.vivawallet.com/api-reference-guide/payment-api/

Beyond that, I'm not sure what you mean by payments not appearing immediately in the Viva Wallet backend. This shouldn't be happening if you're using one of our official plugins for Magento (see below the 3 versions available). Thanks!

https://developer.vivawallet.com/e-commerce-plugins/magento1.x/
https://developer.vivawallet.com/e-commerce-plugins/magento2.1-2.2/
https://developer.vivawallet.com/e-commerce-plugins/magento2.3/
