### ISSUE TITLE
make the charge

### ISSUE THREAD

**Issue by nakasgroup** [VivaPayments/API#1537]
hi 
i am using siple checkout to my eshop and i am in step 2 to make the charge
i want to ask you where i put this code

where i put this code?
curl -X POST \
  https://demo.vivapayments.com/api/transactions \
  -H 'Authorization: Basic ZmJmMWUwOTAtNjVkZS00Yzc1LWI1ODAtZDlkOWJjNDk0YWQyOldEdi1WKw==' \
  -H 'Content-Type: application/json' \
  -d '{
  "PaymentToken": "[payment token]"
}'

down of the code to step 1?

**Comment by matthewrgourd** [comment]
Hi @nakasgroup this is an illustration in cURL to show the API call. In practice you would incorporate into code (see the [code samples](https://developer.vivawallet.com/online-checkouts/simple-checkout/#code-samples) in PHP and C#).
