### ISSUE TITLE
How to add missing languages in simple checkout?

### ISSUE THREAD

**Issue by IlPizza79** [VivaPayments/API#1539]
Hi, I've noticed that right now simple checkout supports only English, French, 'Dutch, Romanian and Greek. Are you planning to add more languages in the future, like German or Italian?
Is there a way to add more languages or translate popup manually?
Thanks!

**Comment by matthewrgourd** [comment]
Hi @IlPizza79 I'm afraid there are no immediate plans but I'll update you once I have access to the timeline.
