### ISSUE TITLE
Δεν μπορώ να δημιουργήσω νέο κουμπί πληρωμής.

### ISSUE THREAD

**Issue by jlinard** [VivaPayments/API#154]
Χαιρετώ την κοινότητα του VivaPayments!

Όταν πάω να δημιουργήσω ένα καινούργιο κουμπί πληρωμής μου βγάζει το παρακάτω error:

![vivapayments-problem](https://cloud.githubusercontent.com/assets/20900596/17473161/a5996b2c-5d57-11e6-8cec-bf88e0cfa560.png)

Μιλώντας με την τηλεφωνική υποστήριξη μου παρέπεμψαν σε εσάς.

Ευχαριστώ,
jinard

**Comment by defilerc** [comment]
Καλησπέρα @jlinard ,

Ευχαριστούμε πολύ για την πληροφορία. Θα θέλαμε να μας δώσετε επιπλέον κάποιες πληροφορίες, για να μπορέσουμε να σας βοηθήσουμε:

1. Τις ακριβείς τιμές που βάζετε στο παράθυρο για τη δημιουργία του κουμπιού. Αν είναι εύκολο επισυνάψτε πάλι ένα screenshot, αλλά αυτή τη φορά από το παράθυρο "Δημιουργία κουμπιού αγοράς" με τις τιμές συμπληρωμένες, πριν πατήσετε το κουμπί "Δημιουργία".

2. Την ακριβή έκδοση του browser που χρησιμοποείται (π.χ. Chrome Version 52.0.2743.116 m)

3. Το merchant id σας.

Ευχαριστούμε πολύ.

**Comment by defilerc** [comment]
Καλημέρα @jlinard ,

Το πρόβλημα εντοπίστηκε τελικά και έχει ήδη διορθωθεί, επομένως δε χρειάζεται να μας στείλετε επιπλέον στοιχεία από τη μεριά σας. Ευχαριστούμε πολύ και πάλι για την πληροφορία που μας δώσατε!

Σε περίπτωση που αντιμετωπίζετε οποιοδήποτε άλλο πρόβλημα, είμαστε στη διάθεσή σας για να σας βοηθήσουμε.

Ευχαριστούμε πολύ.

**Comment by jlinard** [comment]
Ευχαριστώ πολύ για την άμεση ανταπόκριση. 
Μπορώ να επιβεβαιώσω ότι δημιουργώ πλέον νέα κουμπιά πληρωμής.

Ευχαριστώ και πάλι.
