### ISSUE TITLE
Simple Checkout returns server error

### ISSUE THREAD

**Issue by Dr1ps** [VivaPayments/API#1540]
I have tried both live and development, and after completing the form that is generated, I get the following 500 error:
![image](https://user-images.githubusercontent.com/5947079/78355519-7d01f780-75b6-11ea-849a-45d4a393f4ae.png)

**Comment by matthewrgourd** [comment]
Hi @Dr1ps sorry to hear this, can you share the code you're using, together with any response logs, please? Blur out any confidential info.

**Comment by Dr1ps** [comment]
![image](https://user-images.githubusercontent.com/5947079/78366194-d1ae6e00-75c8-11ea-83f7-157666e40e62.png)

And the response is the server error I have posted above.

**Comment by matthewrgourd** [comment]
Hi @Dr1ps are you using JSBin for testing or something else? I just ran the below, filled in the resultant payment form, and the 3DS simulation was generated successfully. However, after that, an error occurred. I believe this is correct as the transaction will never complete in the demo environment. On live, it will be fine.

```
<!DOCTYPE html>
<html>
    <head>
        <title>Simple Checkout</title>
    </head>
    <body>
      <form id="myform" action="/checkout" method="post">
        <button type="button"
          data-vp-publickey="F3nrgfiPzz/nTH/O/LFu7q8iaBAf9VStbVfypQde9d4="
          data-vp-baseurl="https://demo.vivapayments.com"
          data-vp-lang="el"
          data-vp-amount="30"
          data-vp-description="My product">
        </button>
      </form>

      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://demo.vivapayments.com/web/checkout/js"></script>
    </body>
</html>
```

**Comment by Dr1ps** [comment]
I have created a fiddle https://jsfiddle.net/ubpg2aLd
What kind of error are you getting? Are you also getting an error 500 and you're saying that is normal in the demo environment?

**Comment by matthewrgourd** [comment]
Hi @Dr1ps apparently this has come up before with the demo environment which unfortunately isn't 100% perfect compared to production. In the instance you describe, clicking refresh on your browser should remove the error: https://github.com/VivaPayments/API/issues/1245#issuecomment-567033059.

**Comment by Dr1ps** [comment]
Refreshing didn't solve the issue. Also want to point out the screenshot of the response I provided is the POST request sent to https://demo.vivapayments.com/web/checkout/getpaymenttoken after completing the Simple Checkout pop-up form.

**Comment by Dr1ps** [comment]
I have found what the issue was. Apparently, the demo environment only accepts the credit card number provided by the documentation, so I probably should have read it more carefully.

> Base URL: https://demo.vivapayments.com/ The sandbox can be used for all your development / demo requirements. No actual payments can be made within this environment (you cannot use a real card).
A successful transaction can be simulated with the test card number 4111111111111111. Use any future expiration date and 111 for the CVV2. The minimum transaction amount is 30p.

**Comment by matthewrgourd** [comment]
@Dr1ps ok, thanks for the update. I'm closing the issue now if you don't mind.
