### ISSUE TITLE
Payment page in English by default, need it in French

### ISSUE THREAD

**Issue by Antho-Shopify** [VivaPayments/API#1541]
Hi there, 
My VivaWallet payment page is for all my customers in English by default however my whole Shopify shop is in French, there is only one language in my e-shop, etc.. 
I've tried to find the answer on Github without any success. 
Could you get bak to me and let me know how the payment page can be in French by default please ? 

Thanks in advance. 
Anthony

**Comment by Antho-Shopify** [comment]
Also, I just saw the email confirmation VivaWallet is sending to clients, it's also in Englsih and on the invoice there is no VAT... 
Any help on that one as well please ? 
Thanks

**Comment by matthewrgourd** [comment]
Hi @Antho-Shopify is your 'Store Language' set to French in the settings within Shopify?

**Comment by Antho-Shopify** [comment]
Hi @matthewrgourd , thanks for your feedback. 
Yes, my store language is set to French in Shopify (I've double checked it, unless this is hidden somewhere else in the settings..)

**Comment by matthewrgourd** [comment]
@Antho-Shopify what is the registered business name / company registration number if possible, please? I'll need to check the account.

**Comment by Antho-Shopify** [comment]
@matthewrgourd  here you go : 841474398 
Thanks

**Comment by matthewrgourd** [comment]
Hi @Antho-Shopify sorry for this. I see what you're saying but at the moment I can't see a fix. Will need to raise with a developer and get back to you!

**Comment by Antho-Shopify** [comment]
@matthewrgourd 
Thanks for your honest feedback. Will wait from a developer then. 

=> What about my other point ? 
I've seen the email confirmation VivaWallet is sending to clients after a purchase, it's also in English and on the invoice there is no VAT...
Any help on that one as well please ? i.e. somewhere to customize those automatic emails for example or a way to delete them (as I'm sending emails via Shopify by default) ? 
Thanks

**Comment by matthewrgourd** [comment]
Hi @Antho-Shopify regarding your other point, I can switch off the client notification we send. Would you like me to do that?

**Comment by Antho-Shopify** [comment]
@matthewrgourd : yes please, switch off this notification. Let me know when it'll be done, I'll do an order test to double check
Thanks!

**Comment by matthewrgourd** [comment]
@Antho-Shopify ok, that's switched off now. I'll let you know about the other query asap!

**Comment by matthewrgourd** [comment]
Hi @Antho-Shopify, I've checked with our Shopify plugin developer, and in response to your second question, there's not, I'm afraid. We offer a fairly basic integration with Shopify with hardly any settings you can change. Thanks!
