### ISSUE TITLE
Viva payment error Error occured while processing your payment via VivaPayments.

### ISSUE THREAD

**Issue by Antrosp** [VivaPayments/API#1542]
Hello clients can not pay through Viva what is the problem? 
Does that mean that we have problem with the limits?
The problem appears when they put their card, they click the button to pay and it returns them back to our site with the following message **Viva payment error Error occured while processing your payment via VivaPayments**
Please help

**Comment by Antrosp** [comment]
![problemviva](https://user-images.githubusercontent.com/63106298/78363674-d8d37d00-75c4-11ea-99cd-7b7d8c438d64.jpg)

**Comment by matthewrgourd** [comment]
Hi @Antrosp sorry to hear this, could I have your registered business name / company number, please? I will then be able to check your account. You're using our WooCommerce plugin, is that correct?

**Comment by Antrosp** [comment]
Hello this is our info.
My mobile number of registration is +30 6945633637
VAT 00938064L
The problem appears when they put their card, they click the button to pay
and it returns them back to our site with the following message Viva
payment error Error occured while processing your payment via VivaPayments

[image: image.png][image: Pink and Blue Galaxy Gaming Youtube Channel
Art.png]

Please help us since the majority now they pay using cards due to COVID 19
they do not want to pay in cash or in banks

**Comment by Antrosp** [comment]
I think that the problem is with the limits. We have big increase due to
this pandemic people pay using cards more than ever before.
Please help

**Comment by matthewrgourd** [comment]
Hi @Antrosp sorry, I can't find you with the details provided. Please can you email me with your Merchant ID quoting this issue? (#1542) My email is mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
Hi @Antrosp apparently your acquiring limits have been reached. My colleague is looking into this for you now. She should be in contact if any further info is needed. For future reference our customer service team is available at the below phone number / email address:

- (+30) 211 7604 000
- support@vivawallet.com

**Comment by Allomobil971** [comment]
Bonjour, 
Nous avons le même problème sauf que nous n'avons jamais utilisé le paiement pour notre site sur Magento 2 
Au moment de payer. Une erreur disant que le paiement à échoué ou est refusé.

**Comment by Allomobil971** [comment]
Pouvez vous vérifier l'installation ?

**Comment by matthewrgourd** [comment]
@Allomobil971 please can you raise a separate issue using the [New Issue button](https://github.com/VivaPayments/API/issues) so I can look at it independently from this one from @Antrosp which I'm closing now as solution has been provided.
