### ISSUE TITLE
payment issues on website

### ISSUE THREAD

**Issue by greenvape** [VivaPayments/API#1543]
Hello,

We are The Green Vape Company, 36a Coleshill Road, Nuneaton, CV10 0NY.

We are having issues taking payment on our website through viva wallet.

The payment section does not seem to be working on our website, when our customers are going thru to the payment option its directing them back to the checkout.

We think there may be an issue with the plugin on wordpress as it seems to have stopped working.

If you could get back to me asap on this that would be much appreciated on either mobile  07708714211 or by email at admin@thegreenvape.co.uk

Regards

Robert Brindley

**Comment by matthewrgourd** [comment]
Hi @greenvape sorry to hear this. I've just tested and am experiencing the same issue. Have you changed anything in WordPress or WooCommerce recently?

**Comment by matthewrgourd** [comment]
In order for me to investigate further what your issue might be, please send through the following screenshots:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Closing issue as no reply. If this is still a problem, please reopen and reply back with screenshots. Thanks!
