### ISSUE TITLE
payment issue Shopify plugin 

### ISSUE THREAD

**Issue by git842732** [VivaPayments/API#1544]
Currently absolutly every payment are rejected on our website. We didn't change anything to the site. 

it's on the website cbdqueen.fr, a ticket have been previously open, we had issues previous week, then everything work this week , and today nothing. Do we need to change something to our site ?

**Comment by matthewrgourd** [comment]
Hi @git842732 very sorry to hear this! Will raise with our dev team immediately and get back to you asap.

**Comment by matthewrgourd** [comment]
Hi @git842732 are you still experiencing issues. Can I have you company registration number so we can check further?

**Comment by git842732** [comment]
Hi @matthewrgourd , yes we still experience an issue. We have costumer having a blank page at the 3D secure step. I saw an other ticket on github with the same issue , is there something i can do on the shopify side of the plugin ? My merchant id is  3d8523d5-1f40-4b38-a8f5-f8ef8f63ac1c

**Comment by matthewrgourd** [comment]
Hi @git842732 I've checked your account and everything looks fine. You have plenty of sales transactions coming through. This will be a problem that customers face from time to time which is related to their 3DS and nothing to do with Viva Wallet. If they've got through to 3DS (even if they see a blank page) it means our redirect has worked. Everything from this point onwards is down to the card issuer's 3DS setup. Hope that helps. I'm closing this issue now.
