### ISSUE TITLE
problem with vivapayment/vivawallet

### ISSUE THREAD

**Issue by vic19888** [VivaPayments/API#1545]
Hi, i have problem with the service.
on two sites that i use to buy things online (sites use vivawallet for credit card payments),i can't finishing the payment,when i click on "charge" a popup window come up with the name of my bank and nothing else but withe. Usually when i do that come up with name of my bank and the space to write a code that the bank send me on my phone. I already check my bank account and the problem is not there, and also the code arrive to me aniway but there isn't the space to write in.

**Comment by matthewrgourd** [comment]
If you get through to the 3DS popup, it means our checkout is working. Anything beyond that is determined by the card issuer. You could try a different browser in case this helps. Which of our plugins are you using?

**Comment by matthewrgourd** [comment]
Closing as no reply.
