### ISSUE TITLE
problems with check out imanager srl

### ISSUE THREAD

**Issue by enzodipalma** [VivaPayments/API#1549]
Matt Gourd hi, still problems with the check out of imanager srl 
F48D3F1E-B36F-47A4-8831-9114B1A4F577, our check out don't process orders at the end. The CEO checked if the problems are with mastercard and 3D secure, yes it is, but all customers that have issues solved the 3d issue with their respective banks, could you pls and solve it asap? because during week end they have always problems. tks

**Comment by enzodipalma** [comment]
Hello, anyone there to support our customer, pls find below, 30 customers in the last 30 minutes had problems like this, can we solve our check out: 
![IMG-20200404-WA0002](https://user-images.githubusercontent.com/62343589/78450324-16481100-767e-11ea-9794-98baeb0c52a6.jpg)

**Comment by justmary123** [comment]
hello, we are having many problems with the mastercard management. our customers complain about redirection problems after authorizing 3dsecure through their bank. vivawallet pages give error message.
Here are some erroneous transactions:
gateway reference
3460833593302291
gateway reference
9360848202897798
gateway reference
9360859879335583
gateway reference
2260847396089395
gateway reference
3660862663530281
gateway reference
8960843384796818
gateway reference
4460932460289963
gateway reference
8260929659747570

I hope it will be useful to solve the problem, blocking payments is a real problem. Please really sort it out

**Comment by matthewrgourd** [comment]
Hi @justmary123 we're looking into this. Sorry for the delay.

**Comment by justmary123** [comment]
any news?

**Comment by justmary123** [comment]
https://www.vivapayments.com/web/Checkout?lang=en-GB&ref=2086283933726057

**Comment by matthewrgourd** [comment]
Hi @justmary123 cc @enzodipalma my colleague replied to me and I'm passing on what he responded back with. Unfortunately the payment notification cancellations can only be investigated by us if the URL is included in the screenshot and that's because it contains the failure reason or the order code number. We also need the date and the exact time the failure took place. The screenshot provided  doesn't include the URL and cannot help us. Can you please try from a browser and send us the URL in case of a failure?

**Comment by justmary123** [comment]
Chiave di autorizzazione
5686788353252267
Messaggio
Failed
Importo
€38,80
Gateway
Viva Wallet
Stato
failure
Tipo
sale
Creata
7 apr 2020, 13:52
Informazioni dal gateway
X timestamp
2020-04-07T11:56Z
X test
false
X result
failed
X reference
12965719670881
X gateway reference
5686788353252267
X currency
EUR
X amount
38.80
X account
f48d3f1e-b36f-47a4-8831-9114b1a4f577
X signature
1743a9e331ca9152cc493f2b833e70186aa9f524dcc14948a4ae6a83d912f84b

**Comment by matthewrgourd** [comment]
Hi @justmary123 thanks for that info which I've passed on to my colleague. He's also askng for a screenshot similar to the one below if at all possible. This is the failure screen with a specific URL. 

![MicrosoftTeams-image__6___1_](https://user-images.githubusercontent.com/44943019/78672847-1f80ea00-78d9-11ea-9938-9c8095f2c645.png)

**Comment by matthewrgourd** [comment]
Hi @justmary123 my colleague investigated this for you and his last reply was as below:

> there is no issue with 3DS
>can an image of the transaction failure screen (including the URL) be provided in order to investigate?

**Comment by justmary123** [comment]
unfortunately it is the customers who make the transactions and I am not able to send screenshots. Can you do analysis?

**Comment by matthewrgourd** [comment]
@justmary123 on the order code you sent through we had an 'expired' error. Still investigating, but ideally we need more examples, but I appreciate what you said in your previous reply!

**Comment by matthewrgourd** [comment]
Closing as no further response from merchant...
