### ISSUE TITLE
Bad Request - Order Code is not integer!

### ISSUE THREAD

**Issue by zstergios** [VivaPayments/API#155]
Έχω κάνει αρκετές διασυνδέσεις....αυτή  την φορά δεν μπορώ να ΛΥΣΩ το πρόβλημα...
Το orderCode είναι ένας τεράστιος αριθμός με +
https://www.vivapayments.com//web/checkout?ref=4.9476462815726E+15

Parameters:
(
    [Amount] => 1372
    [AllowRecurring] => false
    [RequestLang] => el-GR
    [MerchantTrns] => OrderNum:WN3Z010,Paymethod:1
    [CustomerTrns] => Order Number: WN3Z010 via xx
    [PaymentTimeOut] => 3600
    [FullName] => asdasdas adasdas
    [Email] => asdasdas@asdasd.gr
    [AllowTaxCard] => false
    [SourceCode] => 6246
    [Phone] => 
    [ActionUser] => asdasdas adasdas
)
stdClass Object
(
    [OrderCode] => 4.9476462815726E+15
    [ErrorCode] => 0
    [ErrorText] => 
    [TimeStamp] => 2016-08-08T11:57:27.6462815+03:00
)

Response....
stdClass Object
(
    [OrderCode] => 4.9476462815726E+15
    [ErrorCode] => 0
    [ErrorText] => 
    [TimeStamp] => 2016-08-08T11:57:27.6462815+03:00
)

**Comment by defilerc** [comment]
Καλησπέρα @zstergios ,

Το πρόβλημα μάλλον οφείλεται στο πως γίνεται parse από τη μεριά σας το order code που σας επιστρέφει το Viva Payments API κατά τη δημιουργία του order.

Στο παρακάτω URL, μπορείτε να βρείτε παραδείγματα σε διάφορες γλώσσες για το βήμα της δημιουργίας του order: https://github.com/VivaPayments/API/tree/master/CreateOrder

Αν συνεχίζετε και έχετε πρόβλημα, παραμένουμε εδώ για να σας βοηθήσουμε.

Ευχαριστούμε πολύ,

**Comment by zstergios** [comment]
Το πρόβλημα οφείλεται στο json_decode στην PHP 5.4 ενώ με άλλες εκδόσεις παίζει χωρίς πρόβλημα. Ένα quick fix	

```
// Parse the JSON response
		try {
			$resultObj=json_decode($resBody);
			if($resultObj!==NULL){
				//php 5.4 fix
				if(JString::strpos($resultObj->OrderCode,'E+')!==false){
					preg_match('/"OrderCode":([0-9]*+)/', $resBody, $matches);
					$resultObj->OrderCode=JString::trim($matches[1]);
				}
				$dbValues['vivapayments_response']=json_encode($resultObj);
			}else{
				preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader, $match);
				throw new Exception("API Call failed! The error was: ".trim($match[1]));
			}
		} catch( Exception $e ) {
			$dbValues['vivapayments_response_error']=$e->getMessage();
		}
```
