### ISSUE TITLE
Invalid merchant public key

### ISSUE THREAD

**Issue by platongr** [VivaPayments/API#1550]
I receive the following message on my development page. 
"Invalid merchant public key"

i'm using the https://demo.vivapayments.com.

Can you please advice what to do ?

Thanks

**Comment by matthewrgourd** [comment]
@platongr can you attach a copy of your code for context? With any confidential info. blurred out.

**Comment by platongr** [comment]
This is what i use 


  |  
-- | --
  | <html>
  | <head>
  | <title>Simple Checkout</title>
  | </head>
  | <body>
  | <br><br><br>
  | <form id="myform" action="viva_results2.php" method="post">
  | <button type="button"
  | data-vp-publickey="xxxxxxxxxxxxxxxx"
  | data-vp-baseurl="https://demo.vivapayments.com"
  | data-vp-lang="el"
  | data-vp-amount="1000"
  | data-vp-text="Πληρωμή με Viva"
  | data-vp-customersurname="xxx"
  | data-vp-customerfirstname="xxx"
  | data-vp-customeremail="xxx@xxx.gr"
  | data-vp-expandcard="true"
  | data-vp-description="Event">
  | </button>
  | </form>
  |  
  | <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
  | <script src="https://demo.vivapayments.com/web/checkout/js"></script>
  | </body>
  | </html>
  |  
  |  
  |

**Comment by matthewrgourd** [comment]
Hi @platongr I think we need to switch something on in your demo account. Do you have the demo merchant ID and business name you used during setup?

**Comment by platongr** [comment]
I don't have demo merchant ID. I was trying with the merchant id it appears
in the General Tab of my API account.
Should I apply somewhere for a demo ?
The email account i'm using is  i n f o [at] hosthouse.gr
Could you please check ?


Στις Τετ, 15 Απρ 2020 στις 2:39 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi there, please register a demo account at https://demo.vivapayments.com then go into API access and grab the key from there. Thanks.
