### ISSUE TITLE
 viva default payment solution online payment refused.

### ISSUE THREAD

**Issue by Allomobil971** [VivaPayments/API#1551]
after installation of viva wallet. It does not work with Magento2. We need advice to solve the problem. Urgent

**Comment by matthewrgourd** [comment]
Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- Magento payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Hi @Allomobil971 I replied to your email but I'm duplicating here to keep a record!

Would you be able to check these important module settings are set as below in the Magento backend:

**Order code URL:** https://www.vivapayments.com/api/orders
**Gateway URL:** https://www.vivapayments.com/web/newtransaction.aspx
**Transaction URL:** https://www.vivapayments.com/api/transactions

Also, please try to switch your websites to HTTPs. And send me your company name / registration number so I can check your account.

**Comment by matthewrgourd** [comment]
Hi @Allomobil971 I've sent you an email but am duplicating my answer here:
please check again our plugin installation guide as we updated it recently:

https://developer.vivawallet.com/e-commerce-plugins/magento2.1-2.2/

Please see in particular step 8:

In the Magento store settings:

MerchantID – your Viva Wallet Merchant ID
API Key – your Viva Wallet API Key
Source Code – 4-digit code for the payment source you set up in the Viva Wallet banking app
OrderCode URL – https://www.vivapayments.com/api/orders
Gateway URL – https://www.vivapayments.com/web/newtransaction.aspx
Transaction URL – https://www.vivapayments.com/api/transactions

**Comment by matthewrgourd** [comment]
Hi @Allomobil971 are you up and running now? If you are, please close this issue. Thanks!

**Comment by matthewrgourd** [comment]
Closing issue as no reply and full answer provided...
