### ISSUE TITLE
error payment 

### ISSUE THREAD

**Issue by noe852** [VivaPayments/API#1552]
I cannot complete your transaction, I am sending 2 of my own photos and 1 more from another website where your service is operating normally.
Today the website is planned to be made public for the whole world but with the problem of payment I can't do it.
Δεν μπορεί να ολοκληρωθεί η συναλλαγή σας στέλνω 2 δικές μου φωτογραφίες και ακόμα 1 από άλλο website που λειτουργεί κανονικά η υπηρεσία σας.
Σήμερα είναι προγραμματισμένο το website να γίνει δημόσιο για όλο τον κόσμο αλλά με το πρόβλημα της πληρωμής δεν μπορώ να το κάνω.
![91616377_707109056761596_3120432562476941312_n](https://user-images.githubusercontent.com/63224153/78532559-241da380-77f0-11ea-999e-d357410dc6a8.jpg)
![91851295_2546984985543720_7037633914013220864_n](https://user-images.githubusercontent.com/63224153/78532564-24b63a00-77f0-11ea-9cab-787365e0e380.jpg)
![viva wallet -problem](https://user-images.githubusercontent.com/63224153/78532672-50392480-77f0-11ea-83a0-9b70b2c3b935.jpg)

**Comment by noe852** [comment]
![viva wallet -problem-test](https://user-images.githubusercontent.com/63224153/78533596-e3bf2500-77f1-11ea-8489-2c336f565e1a.jpg)

**Comment by matthewrgourd** [comment]
@noe852 you need to follow the instructions in our guide: https://developer.vivawallet.com/e-commerce-plugins/shopify/
