### ISSUE TITLE
Order is not complete

### ISSUE THREAD

**Issue by Alexklb** [VivaPayments/API#1554]
Hello, I just installed the plugin on woocommerce.

Everything looks ok but when I pass an order after wrting my card information and validate I am back on main page, cart is still full. On my backoffice order appears as waiting for payment, then canceled.

If I check on vivawallet dashboard payment is received and card is charged

**Comment by matthewrgourd** [comment]
Hi @Alexklb 

Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Hi @Alexklb sounds like our plugin for WooCommerce is working correctly. Unfortunately due to the nature of redirect checkouts, there may not be full real-time synchronicity between your Viva Wallet account and your WooCommerce dashboard.
