### ISSUE TITLE
PROBLEM WORSENED: Payments denied for 50% of my customers - URGENT HELP!!! (#1528)

### ISSUE THREAD

**Issue by AndreaVacca** [VivaPayments/API#1555]
Hello,
help us urgently!
In the last 24 hours ten payment went wrong or was refused by your
platform because
of your mistake!

This is the list of failed transactions in the last 23h, we are loosing a
lot of money. You absolutely must thoroughly check our account and remedy
the problem!

#2194 Salvatore Rindone 2 ore fa
#2193 Alessandro Mirabile 6 ore fa

#2192 Alessandro Mirabile 6 ore fa
#2183 Paola Chiaramonte 13 ore fa

#2176 ludovico dallai 15 ore fa

#2174 Salvatore Rindone 17 ore fa

#2173 STEFANO SCOMA 19 ore fa

#2171 STEFANO SCOMA 19 ore fa

#2170 Stefano Martinucci 20 ore fa
#2167 Salvatore Rindone 21 ore fa

Stefano Scoma, for example, he saw his payment denied twice. He says that
after entering the credit card details and confirming them, your page does
not load.
The screen stays as it is, and nothing else happens. It is no possible for
the customer to go ahead and he doesn't receive confirmation of payment.
And the payment is not processed by your platform. We lose the order and
are forced to cancel it.

We've lost more than 100 orders in less than a month since we started using
your platform. We need a fast solution!

Other customers complain that the message to enter the OTP code in the 3d
secure procedure arrives after hours.This is ridiculous and outrageous!
If it's your responsibility you must also check this aspect.

We trust in your will to resolve the problem as soon as possible.  Do a
thorough check please!
I thank you and whish you all the best in your work.

My data:
Viva wallet profile intestate to Weweed di Andrea Vacca,
Website E-commerce: www.Prodotti-cannabis.it (we use woocommerce)
Mail account viva wallet: Andrea.weweed@gmail.com

Weweed - Prodotti-cannabis.it

**Comment by dikkydog** [comment]
Hello,
I have the same problem. many orders are not validated.
Website E-commerce: https://la-verte-feuille.fr (we use woocommerce)
Mail account viva wallet: contact@la-verte-feuille.fr

**Comment by matthewrgourd** [comment]
Hi @AndreaVacca I've looked at a couple of the examples you gave above and can advise you that the card issuer message was either insufficent funds or 'do not honour'. You need to speak to those customers as they're trying to buy goods on your e-commerce store wthout having any money available on their credit cards or some other reason relating to their card issuers.

**Comment by Dragonvapour123** [comment]
@matthewrgourd Can you stop blaming the card issuers. We're having the same problem and so are others. This is an issue on your side. Viva Wallet support is virtually impossible to get hold of. Can you advise a proper solution further please.

**Comment by matthewrgourd** [comment]
@AndreaVacca @Dragonvapour123 I've spoken with someone from our development team who advises the following:

> Chrome 80 is gradually deploying a new cookie policy in their browser, problems will occur with payment systems that use the redirection method. Most e-commerce platforms are not prepared to set the cookie in the new format, so in most cases the customer will lose his session when getting returned to the store. Payment plugins that are not adjusted will see problems with lost sessions (customer has to login again and with some plugins lost orders). 

I'm not 100% sure but it's possible this could be happening. Until we have a fix if you could maybe get your customers to try a different browser if they're having problems. Apologies, but this only just came through today and we've had a long bank holiday weekend.

**Comment by matthewrgourd** [comment]
Hi @AndreaVacca @Dragonvapour123 just to update you. I've spoken to our development team and we don't think our plugin had any issues. However, just to be sure, you can remove your existing plugin and use the below (updated) plugin instead:

[vivawallet-for-woocommerce-3.6.0.zip](https://github.com/VivaPayments/API/files/4502739/vivawallet-for-woocommerce-3.6.0.zip)

**Comment by matthewrgourd** [comment]
Please check https://en-gb.wordpress.org/plugins/vivawallet-woocommerce-gateway for future updates. Closing this issue now...
