### ISSUE TITLE
Issue in Simple Checkout with google chrome autocomplete

### ISSUE THREAD

**Issue by IlPizza79** [VivaPayments/API#1556]
Hi, I'm using Simple Checkout on my website and some of my customers notify me about an issue with Google Chrome input autocomplete: "year" field sometimes is autofilled with 4 digits instead of 2 digits, and they cannot proceed until they edit manually the year field.

Do you think you could disable autocomplete in form?
I guess it can be also a security improvement...
Thanks in advance!

**Comment by matthewrgourd** [comment]
Hi @IlPizza79 thanks for raising this. I will ask a developer to get back to me about whether this may be possible.

**Comment by matthewrgourd** [comment]
This is now on the roadmap but I'm not sure exactly when we'll be able to make the update. I'm closing this issue now...
