### ISSUE TITLE
Paiement problem

### ISSUE THREAD

**Issue by dikkydog** [VivaPayments/API#1557]
Hello,

We have orders that are not validated. The last order on the site is still pending after 20 minutes when the customer has paid with his card. In the history of VivaWallet, I do not see the customer's payment. Can you check if everything is ok on my site?

Site : https://la-verte-feuille.fr (we use woocommerce)
Mail account viva wallet: contact@la-verte-feuille.fr

**Comment by dikkydog** [comment]
the payment is passed 1h30 after the customer has made his cb. Please Can you check if everything is ok on my site?

**Comment by matthewrgourd** [comment]
Hi @dikkydog as far as I'm aware pending status usually means the customer has failed 3DS. It should change automatically to cancelled status after 1-2 days. I've checked your account and can see 7 successful transactions since the beginning of April and zero failed transactions.
