### ISSUE TITLE
Δεν περνάνε οι πιστωτικές κάρτες master card

### ISSUE THREAD

**Issue by 6986621622** [VivaPayments/API#1558]
Οι πιστωτικές κάρτες τύπου master card δεν περνάνε και δεν εγκρίνονται στο σύστημα σας που έχουμε στο σιτε μας.
Επιβεβαιώσαμε και εντοπίσαμε το πρόβλημα, έχουμε ζητήσει να το διορθώσετε από το Σάββατο το πρωί και φτάνει Δευτέρα βράδυ για να πάρουνε απάντηση ότι πρέπει να πούμε το αίτημα μας έτσι!!!!
Είναι γ δεύτερη φορ:α που αντιμετωπίζουμε τεραστιο πρόβλημα με το σύστημα μας και χάνουμε σε κρίσιμη περίοδο παραγγελίες κι δουλειές και είμαστε τρέλα δυσαρεστημένοι!!!
Ενημερώστε μας για την διάθεση και την ικανότητα να μας υποστηρίξετε σαν σύστημα και σαν εταιρεία αλλιώς να δούμε τις επόμενες κινήσεις μας

**Comment by matthewrgourd** [comment]
Hi @6986621622 sorry to hear this. We've had a few businesses that needed enrolling to Mastercard. Could I have your company name and registration number, please, and I'll check.

**Comment by 6986621622** [comment]
Manolis - Georgouti O.E.
EL099961402
www.craftbox.gr

**Comment by matthewrgourd** [comment]
Hi @6986621622 I've checked your account it it looks like you're using an unofficial Viva Wallet plugin for WooCommerce. You need to download from the page below and follow the instructions:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

However, we looked into whether you're currently 3DS enrolled with Mastercard and you're not. So we will put that through for you. Please note, it can take up to two working days.
