### ISSUE TITLE
Confirmed payment displays an error page (woocommerce)

### ISSUE THREAD

**Issue by filipecardigos** [VivaPayments/API#1559]
Every time someone uses the app to make a payment, after the 3D secure verification it redirects back to WP but shows a error message "There has been a critical error on your website. / Learn more about debugging in WordPress."
With other payment methods such as PayPal it doesn't happen.
It was working properly before the last major WooCommerce update.
Can you please follow into this issue? If there's anything else I can provide let me know.
This is the string after www."mydomain".com/index.php?wc-api=wc_vivawallet&vivawallet=success&t=d5e0a800-90d6-448b-9276-6d13f2d9a40b&s=8279784045961288&lang=en-US&eventId=0&eci=1

**Comment by filipecardigos** [comment]
I reverted the latest update (now running on WooCommerce 3.9.3 and the error won't show up.
Before updating WC alerts that some plugins may not be compatible with the newest version, VivaWallet Gateway included.
Can someone please advise if it's been tested and updated according to WC?
Thanks.

**Comment by matthewrgourd** [comment]
Hi @filipecardigos looks like I need to look at this with a developer. Thanks for raising and let me get back to you soon. Can you just confirm the version number of our plugin from the php code if possible, please? Thanks!

**Comment by filipecardigos** [comment]
Thank you @matthewrgourd 
As requested I'm using version 3.5.7
Let me know as soon as have any updates.

**Comment by filipecardigos** [comment]
Hi Matthew, any updates on this? Thanks!

•
*wetheknot.com <http://wetheknot.com/>*

(+351) 965 459 096 / 914 567 656
wetheknot@gmail.com
Instagram <http://www.instagram.com/wetheknot> —  Facebook
<http://www.facebook.com/wetheknot>

**Comment by filipecardigos** [comment]
Hi @matthewrgourd, any updates on this?
Thanks!

**Comment by matthewrgourd** [comment]
Hi @filipecardigos sorry for the delayed reply. Our developers have confirmed our plugin works with the latest version of WooCommerce. 

In order for me to investigate further what your issue might be, please send through the following screenshots:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by filipecardigos** [comment]
@matthewrgourd, hello!
I've made another test purchase and it went all good on the newest WooCommerce update.
Thanks for your time to look into this.
Have a great day, Filipe :)
