### ISSUE TITLE
Χρεώσεις που δεν ολοκληρώνονται

### ISSUE THREAD

**Issue by StellaGiovani** [VivaPayments/API#1560]
Καλησπέρα σας,

σας γράφω από το θέατρο Πορεία και την εταιρεία Δόλιχος.
Διατηρούμε στο site μας σύστημα χρεώσεων στο vivawallet: https://poreiatheatre.com/content/members/ για συνδρομές και δωρεές, το οποίο έχει υλοποιήσει η εταιρία Indev software. Παρατηρήσαμε πως κάποιες χρεώσεις με κάρτα δεν ολοκληρώνονται. Θα μπορούσατε να το ελέγξετε και να μας πείτε εάν υπάρχει κάποιο θέμα στο σύστημα των χρεώσεων από μέρους σας;
Μία κυρία που μας έστειλε mail πως δεν μπορούσε να προχωρήσει σε χρέωση της κάρτας της, μας είπε πως είναι στην Αμερική, μπορεί αυτό να έχει κάποια σχέση;

Σας ευχαριστώ πολύ.

Με εκτίμηση,

Στέλλα Γιοβάνη

Διευθύντρια Παραγωγής θεάτρου Πορεία / Production Manager at Poreia Theatre
Τρικόρφων 3-5 / Trikorfon 3-5
Αθήνα, 10433 / Athens, 10433
τηλ: 6977405359, 2108210991
www.poreiatheatre.com

**Comment by matthewrgourd** [comment]
Hi @StellaGiovani what is your company registration number, please, so I can check your account?

**Comment by matthewrgourd** [comment]
Hi @StellaGiovani would you mind also providing a version of your question in English as I don't understand Greek? Thanks!

**Comment by StellaGiovani** [comment]
Good evening,

I am writing to you from the Poreia theater and the Dolichos company. 
We maintain in our site a system of charges on vivawallet: https://poreiatheatre.com/content/members/ for subscriptions and donations, which has been implemented by the company Indev software. We noticed that some card charges are not completed. Could you check it out and tell us if there is an issue with your billing system?
A lady who emailed us that she couldn't charge her card, told us she's in America, could that have anything to do with it?

Thank you very much.

Yours sincerely,

Stella Giovani

Production Manager at Poreia Theater
Trikorfon 3-5 / Trikorfon 3-5
Athens, 10433 / Athens, 10433
Tel: 6977405359, 2108210991
www.poreiatheatre.com

**Comment by StellaGiovani** [comment]
Hello @matthewrgourd do you mean registration number in vivawallet? How can I find my company registration number?

**Comment by matthewrgourd** [comment]
Hi @StellaGiovani sorry for the delay. I've found your account details. Your VAT number (EL090325128) is helpful for tracking. On what day was the transaction you mention?

**Comment by matthewrgourd** [comment]
Hi @StellaGiovani I couldn't see any unusual transactions. Everything looks fine to me at the account end.

**Comment by matthewrgourd** [comment]
Closing issue as no errors found at Viva Wallet end. It's most probably a 3DS or card issuer problem.
