### ISSUE TITLE
Δεν περνάει άτοκες δόσεις

### ISSUE THREAD

**Issue by xakou** [VivaPayments/API#1561]
Χρησιμοποιώ το Opencart 2.3.0.2 και το offical module της Viva από την ιστοσελίδα τους, αλλά δεν κάνει δόσεις, ενώ θεωρητικά έπρεπε να δουλεύει...

**Comment by matthewrgourd** [comment]
Hi @xakou is it possible to have the question in English by any chance? Unfortunately, we don't have a Greek-speaking technical support person. Thanks!

**Comment by xakou** [comment]
Hello, im using OC 2.3.0.2 and official Viva module.
At the module i have enable installments, but actually doesn't work

**Comment by matthewrgourd** [comment]
Sorry to hear this. Is the module currently enabled on your site? Can I have your website address?

**Comment by xakou** [comment]
@matthewrgourd yes it is. Have a look at https://behappyonline.gr

**Comment by matthewrgourd** [comment]
Hi @xakou I believe you need to define your installments in the payment module settings in WooCommerce. Can you send me a screenshot of the OpenCart settings that relate to Viva Wallet, obscuring your Merchant ID / API key? Thanks!

**Comment by xakou** [comment]
I don't have WooCommerce!!!!!!!
I have Opencart. No i can't send it. It is private. Does vivawallet have support or only github?

**Comment by matthewrgourd** [comment]
Sorry, I meant OpenCart. It's fine to share your settings here but you need to blur out anything confidential. This IS the official Viva Wallet technical support. If anything needs escalate I will do so to the dev team but they will definitely need screenshots. An alternative is to send anything you'd prefer to keep private direct to my email address: mgourd@vivawallet.com

**Comment by xakou** [comment]
You have mail....

**Comment by matthewrgourd** [comment]
Hi @xakou thanks for sending the screenshots through. I've checked your settings and everything looks fine. Does the plugin work with the installments field left blank? I know you're attempting to use the installments functionality but I need to know if the plugin works with single payments.

**Comment by xakou** [comment]
Yes the plugin works with single payment.


Στις Τετ, 22 Απρ 2020, 18:36 ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Ok, in that case I need to raise as a bug. After a test myself, I can confirm that your installments functionality isn't working. I'll get back to you as soon as I've any updates.

**Comment by xakou** [comment]
Thank you. I'm waiting for your reply.


Στις Τετ, 22 Απρ 2020, 18:47 ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @xakou reply from developer:

>The OpenCart modules do not show an option in the checkout to select the amount of installments before redirection to Viva Wallet, but they populate the MaxInstallments field when the ordercode is generated. So if a customer visits the mentioned https://behappyonline.gr,, has an order total of 60 Euro or above, he will have an option to pay with a maximum of 3 installments if his card is enabled to make payments with installments (this option will be shown in that case on the payment page from Viva).
