### ISSUE TITLE
Transaction failed or has been cancelled!

### ISSUE THREAD

**Issue by tase09** [VivaPayments/API#1562]
Hi! I'm running a website on opencart 2.3 and installed the extension... First of all the module received an error when trying to confirm the order on website... i noticed that in your code the was case RON for our currency but whe had LEI so i replaced RON with LEI in your cases and it worked it would transfer me from website to gateway for payment... the issue now it's that only paymanets with ING Bank cards work... other banks doesn't work it gives error "Transaction failed or has been cancelled!". www.gym-stack.ro

**Comment by matthewrgourd** [comment]
Hi @tase09 sorry to hear this. 
Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- OpenCart payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by tase09** [comment]
![apikey](https://user-images.githubusercontent.com/58305947/78657645-bf3a7a00-78d1-11ea-8a69-b63a7173e33a.png)
![opencartextension](https://user-images.githubusercontent.com/58305947/78657651-c06ba700-78d1-11ea-8770-b577da01e847.png)
![paymentsource](https://user-images.githubusercontent.com/58305947/78657653-c06ba700-78d1-11ea-880e-b20521aee7c5.png)
![site](https://user-images.githubusercontent.com/58305947/78657654-c06ba700-78d1-11ea-9785-f016ff351587.png)

**Comment by tase09** [comment]
Hi! So I've reinstalled the module but still the error with currency ... i modified again in cases LEI instead of RON and it worked this time with every bank. I tried 3 different bank cards and it seems to work properly. I leave you the code here for related problems. Thanks!

![image](https://user-images.githubusercontent.com/58305947/78771955-a85f5a80-7999-11ea-9fa4-57f0a413b393.png)

**Comment by matthewrgourd** [comment]
Hi @tase09 that's good to know and thanks for sharing your solution!
