### ISSUE TITLE
Πληρωμή με πιστωτική Κάρτα/ Αύξηση δόσεων (WooCommerce)

### ISSUE THREAD

**Issue by NllySn** [VivaPayments/API#1563]
Καλησπέρα!έχουμε ακολουθήσει όλες τις οδηγίες για εγκατάσταση της Viva σε WooCommerce και με τις χρεωστικές δεν υπάρχει θέμα. Οι πελάτες μπορούν κανονικά να πληρώσουν με πιστωτική και θα πρέπει να κάνουμε κάτι άλλο γι'αυτό? επίσης πως θα ρυθμίσουμε τις δόσεις και πως μπορούμε να βάλουμε άτοκες δόσεις?

**Comment by matthewrgourd** [comment]
Hi @NllySn is it possible to have the question in English by any chance as we don't have a Greek-speaking technical support. Thanks!

**Comment by NllySn** [comment]
Hello,

 

We have installed the viva wallet for our eshop (WooCommerce). The customers do buy with their debit card successfully and I was wondering if we have to do something else in order our customers to be able to use their credit card instead their debit. And sth more, how can we adjust the installments for instance for a payment with 6 installments or 12 installments? And how are we going to have interest-free installments?

 

I mean for all these do we have to do something to the settings of the woocommerce or viva wallet?

 

Looking forward to hearing from you

 

Thank you

 

Νelly Sianna

eCommerce Administrator



Nexion Hellas Ltd

p: (+30) 216 900 66 58 

e: nelly.sianna@nexion.gr <mailto:nelly.sianna@nexion.gr>  | w: nexion.gr 

a: 6 Messinias Str.| Kifisia 145 64 Athens | Greece

 

 



 

 

 

 

Εάν δεν είστε ο παραλήπτης για τον οποίον προορίζεται το συγκεκριμένο μήνυμα (ή το λάβατε εσφαλμένα), παρακαλείσθε 

να ενημερώσετε άμεσα τον αποστολέα και να το καταστρέψετε. Απαγορεύεται αυστηρά οποιαδήποτε μη εξουσιοδοτημένη 

αντιγραφή, διάδοση ή διανομή του περιεχομένου του παρόντος μηνύματος.

If you are not the intended recipient of this email (or have received this e-mail in error) please notify the sender immediately 

and destroy this e-mail. 

Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden

 

P Please consider the environment before printing.

**Comment by matthewrgourd** [comment]
Hi @NllySn sorry for the delayed reply. My understanding is that your query is about paying by installments through the Viva Wallet for WooCommerce plugin with a credit card. As far as I'm aware, it doesn't make any difference if you're using a credit or a debit card. However, as a merchant, you do have to be based in Greece. Hope this helps!

**Comment by matthewrgourd** [comment]
Hi @NllySn I've checked further and the card would need to support installments, whether it's a debit or a credit card. Hope this helps!
