### ISSUE TITLE
Recommended Woocommerce Currency converter plug in

### ISSUE THREAD

**Issue by ijonts** [VivaPayments/API#1565]
Hi,
We use Viva's Woocommerce plug in for accepting credit cards. Our website is UK based, and currently shows prices in GBP.
We would like to display prices and checkout in different currencies to different users, based on their geo location.
What is a known currency converter woocommerce plug in, that works well with Viva's plug in? (when we tried installing a random one, users from different geo locations received a message at checkout from Viva's plug in that their state in not supported)
Thank you

**Comment by matthewrgourd** [comment]
No, unfortunately we don't have a specific one we can recommend. Sorry not to be of more help.

**Comment by ijonts** [comment]
We tried using one plug in and when a user tries to check out from the US they see a message that they cannot complete the transaction from the state they are in

**Comment by ijonts** [comment]
I need some assistance please. According to your customer service we can receive payments from the US in USD

**Comment by ijonts** [comment]
Just tell me one that works please

**Comment by matthewrgourd** [comment]
Hi @ijonts I'm sorry I can't provide any help with third-party plugins so I'm closing this issue.
