### ISSUE TITLE
Problème d'activation de mon canal de paiement 

### ISSUE THREAD

**Issue by Grosjo773** [VivaPayments/API#1566]
Bonjour, 

Pour un site internet utilisant le moyen de paiement Vivawallet, j'ai créée une première fois un canal de paiement pour pouvoir configurer mon module sur Prestashop 1.7. Ce canal a été validé, mais depuis je me suis rendu compte que je devais le changer. J'ai donc effectué la mise à jour, mais je suis toujours en attente de validation de la mise à jour de mon canal de paiement. Pouvez-vous m'aider ?

**Comment by matthewrgourd** [comment]
Hi @Grosjo773 what's your company name / registration number and I'll check for you?

**Comment by Grosjo773** [comment]
L'entreprise est enregistrée sous le nom CBDELICE. N°841380157 pour l'enregistrement. 
Merci pour votre aide

**Comment by matthewrgourd** [comment]
Hi @Grosjo773 that payment source should be active now. However, I amended your Success / Failure URLs slightly. Depending on which version of PrestaShop you're using they should either be:

`module/vivawallet/success` (without the opening forward-slash)
`module/vivawallet/fail`

Or: (older versions of PrestaShop)

`modules/vivawallet/success.php`
`modules/vivawallet/fail.php`

**Comment by Grosjo773** [comment]
Bonjour, 

Merci pour l'aide.
On utilise la version 1.7.1.2 de prestashop et la dernière vers du module Vivawallet. 

J'ai cependant des question sur la procédure à suivre. 
Ma source de paiement est basée sur "Native/Pay", est-ce que je dois me baser sur la procédure : https://developer.vivawallet.com/online-checkouts/simple-checkout/ ? 

Merci

**Comment by matthewrgourd** [comment]
@Grosjo773 no, it's not Simple Checkout, it's a version of our Redirect Checkout. You need to follow the instructions on our plugin page:

https://developer.vivawallet.com/e-commerce-plugins/prestashop/

and "Redirect / Native Checkout v2" should be chosen in the below settings:

![NewPaymentSource](https://user-images.githubusercontent.com/44943019/78776426-c031e100-798f-11ea-9f5e-7a1c0058ca80.png)

**Comment by Grosjo773** [comment]
Merci, je vais donc mettre à jour ma source de paiement. 
Une fois ma source de paiement mise à jour il faut configurer le module dans prestashop : 
![image](https://user-images.githubusercontent.com/63296647/78785922-393d3280-79a8-11ea-883a-a6d474a3a519.png)
Quelle URL je dois rentrer dans "Base URL" ?

Est-ce qu'il est nécessaire de toucher au code source du site internet ? 

Merci d'avance pour votre retour
