### ISSUE TITLE
Simple checkout

### ISSUE THREAD

**Issue by chgl48** [VivaPayments/API#1567]
1. Do you have a complete code example for simple chechout? Also tell me how many pages do I have to create for the whole successful execution of any payment?
2. Send me also all demo codes, because system does not leave me to open demo account but this not critical as above 1.

**Comment by matthewrgourd** [comment]
Hi @chgl48 please see the PHP or C# tab under [Request example](https://developer.vivawallet.com/online-checkouts/simple-checkout/#request-example) on our developer portal. Unfortunately we don't have any other code examples at the moment. Regarding demo accounts, I was under the impression you could have as many as you want.

**Comment by matthewrgourd** [comment]
To sign up for a demo account, visit the below URL:

https://demo.vivapayments.com/

I'm closing this issue now, but please feel free to respond back if you have any further queries.

**Comment by chgl48** [comment]
For demo is needed other password than for the product case?
 
 
-----Original Message-----

**Comment by chgl48** [comment]
The 3 steps in https://developer.vivawallet.com/online-checkouts/simple-checkout/#request-exampleare to be included in the code of a single page e.g. with a name like checkout.html ? Or is to be included in more pages?

RegardsC. Lyritzis
 
 
-----Original Message-----

**Comment by matthewrgourd** [comment]
Hi @chgl48, Step 1 refers to a single page of HTML. Step 2 is a call that's made (via program code, e.g. php) through a backend channel. Step 3 relates back to Steps 1 and 2. Hope that helps!
