### ISSUE TITLE
Πρόβλημα με φόρμα στοιχείων

### ISSUE THREAD

**Issue by andyz1974** [VivaPayments/API#157]
Καλησπέρα σας,
Χρησιμοποιώ το Native Payments και έχω δημιοργήσει μερικά επιπλέον πεδία, τα οποία είναι: 
Όνομα, Επώνυμο (ξεχωριστά από το όνομα κατόχου κάρτας), Διεύθυνση, ΤΚ, Πόλη, Χώρα.
Όταν συμπληρώνονται όλα τα στοιχεία, εμφανίζεται ένα μήνυμα σφάλματος "VivaPayments: Error" (βλ. Screenshot). Αντίθετα, όταν ένα από τα πεδία μένει κενό, η συναλλαγή ολοκληρώνεται κανονικά.
Πού μπορεί να οφείλεται αυτό;
Όλα τα παραπάνω είναι σε demo.

![error](https://cloud.githubusercontent.com/assets/8945918/17558219/8a068b7a-5f22-11e6-9b73-54223ccc5c3a.jpg)

**Comment by defilerc** [comment]
Καλησπέρα @andyz1974 ,

Σιγουρευτείτε για αρχή, ότι τα επιπλέον πεδία που έχετε ορίσει, **δεν** περιέχουν το attribute `data-vp`.

Αν αυτό δεν είναι η αιτία του προβλήματος, τότε παρακαλώ στείλτε μας το merchant id σας, ώστε να μπορέσουμε να διερευνήσουμε περαιτέρω τι έχει συμβεί.

Ευχαριστούμε πολύ.

**Comment by andyz1974** [comment]
@defilerc Κανένα από τα πεδία δεν περιέχει το Attribute data-vp.
Το Merchant id είναι: a61a9e19-cca4-4ed3-9eb0-51aa7e2d390a, αλλά αυτό είναι το προσωρινό για το demo.

Παρακάτω είναι και ο κώδικας της φόρμας, ώστε να δείτε αν υπάρχει κάτι που δεν θα έπρεπε.

Ευχαριστώ πολύ

`<form action="" method="POST" id="payment-form">
			<div class="g-grid payment-form"><input name="sendmail" type="hidden" value="1" />
				<div class="g-block size-100">
					<h2>Στοιχεία Εγγραφής <small>(* Όλα τα πεδία είναι υποχρεωτικά)</small></h2>
				</div>				
				<div class="g-block size-30"><span>Επώνυμο: </span></div>
				<div class="g-block size-70"><input name="lastname" size="20" type="text" required/></div>
				<div class="g-block size-30"><span>Όνομα: </span></div>
				<div class="g-block size-70"><input name="firstname" size="20" type="text" required/></div>
				<div class="g-block size-30"><span>Διεύθυνση: </span></div>
				<div class="g-block size-70"><input name="address" size="20" type="text" required /></div>
				<div class="g-block size-30"><span>ΤΚ </span></div>
				<div class="g-block size-70"><input name="postal" size="5" type="text"  /></div>
				<div class="g-block size-30"><span>Πόλη: </span></div>
				<div class="g-block size-70"><input name="city" size="20" type="text" required/></div>
				<div class="g-block size-30"><span>Χώρα: </span></div>
				<div class="g-block size-70"><select name="country"><option value="Greece">Greece</option><option value="Afganistan">Afghanistan</option><option value="Albania">Albania</option><option value="Algeria">Algeria</option><option value="American Samoa">American Samoa</option><option value="Andorra">Andorra</option><option value="Angola">Angola</option><option value="Anguilla">Anguilla</option><option value="Antigua &amp; Barbuda">Antigua &amp; Barbuda</option><option value="Argentina">Argentina</option><option value="Armenia">Armenia</option><option value="Aruba">Aruba</option><option value="Australia">Australia</option><option value="Austria">Austria</option><option value="Azerbaijan">Azerbaijan</option><option value="Bahamas">Bahamas</option><option value="Bahrain">Bahrain</option><option value="Bangladesh">Bangladesh</option><option value="Barbados">Barbados</option><option value="Belarus">Belarus</option><option value="Belgium">Belgium</option><option value="Belize">Belize</option><option value="Benin">Benin</option><option value="Bermuda">Bermuda</option><option value="Bhutan">Bhutan</option><option value="Bolivia">Bolivia</option><option value="Bonaire">Bonaire</option><option value="Bosnia &amp; Herzegovina">Bosnia &amp; Herzegovina</option><option value="Botswana">Botswana</option><option value="Brazil">Brazil</option><option value="British Indian Ocean Ter">British Indian Ocean Ter</option><option value="Brunei">Brunei</option><option value="Bulgaria">Bulgaria</option><option value="Burkina Faso">Burkina Faso</option><option value="Burundi">Burundi</option><option value="Cambodia">Cambodia</option><option value="Cameroon">Cameroon</option><option value="Canada">Canada</option><option value="Canary Islands">Canary Islands</option><option value="Cape Verde">Cape Verde</option><option value="Cayman Islands">Cayman Islands</option><option value="Central African Republic">Central African Republic</option><option value="Chad">Chad</option><option value="Channel Islands">Channel Islands</option><option value="Chile">Chile</option><option value="China">China</option><option value="Christmas Island">Christmas Island</option><option value="Cocos Island">Cocos Island</option><option value="Colombia">Colombia</option><option value="Comoros">Comoros</option><option value="Congo">Congo</option><option value="Cook Islands">Cook Islands</option><option value="Costa Rica">Costa Rica</option><option value="Cote DIvoire">Cote D'Ivoire</option><option value="Croatia">Croatia</option><option value="Cuba">Cuba</option><option value="Curaco">Curacao</option><option value="Cyprus">Cyprus</option><option value="Czech Republic">Czech Republic</option><option value="Denmark">Denmark</option><option value="Djibouti">Djibouti</option><option value="Dominica">Dominica</option><option value="Dominican Republic">Dominican Republic</option><option value="East Timor">East Timor</option><option value="Ecuador">Ecuador</option><option value="Egypt">Egypt</option><option value="El Salvador">El Salvador</option><option value="Equatorial Guinea">Equatorial Guinea</option><option value="Eritrea">Eritrea</option><option value="Estonia">Estonia</option><option value="Ethiopia">Ethiopia</option><option value="Falkland Islands">Falkland Islands</option><option value="Faroe Islands">Faroe Islands</option><option value="Fiji">Fiji</option><option value="Finland">Finland</option><option value="France">France</option><option value="French Guiana">French Guiana</option><option value="French Polynesia">French Polynesia</option><option value="French Southern Ter">French Southern Ter</option><option value="Gabon">Gabon</option><option value="Gambia">Gambia</option><option value="Georgia">Georgia</option><option value="Germany">Germany</option><option value="Ghana">Ghana</option><option value="Gibraltar">Gibraltar</option><option value="Great Britain">Great Britain</option><option value="Greece">Greece</option><option value="Greenland">Greenland</option><option value="Grenada">Grenada</option><option value="Guadeloupe">Guadeloupe</option><option value="Guam">Guam</option><option value="Guatemala">Guatemala</option><option value="Guinea">Guinea</option><option value="Guyana">Guyana</option><option value="Haiti">Haiti</option><option value="Hawaii">Hawaii</option><option value="Honduras">Honduras</option><option value="Hong Kong">Hong Kong</option><option value="Hungary">Hungary</option><option value="Iceland">Iceland</option><option value="India">India</option><option value="Indonesia">Indonesia</option><option value="Iran">Iran</option><option value="Iraq">Iraq</option><option value="Ireland">Ireland</option><option value="Isle of Man">Isle of Man</option><option value="Israel">Israel</option><option value="Italy">Italy</option><option value="Jamaica">Jamaica</option><option value="Japan">Japan</option><option value="Jordan">Jordan</option><option value="Kazakhstan">Kazakhstan</option><option value="Kenya">Kenya</option><option value="Kiribati">Kiribati</option><option value="Korea North">Korea North</option><option value="Korea Sout">Korea South</option><option value="Kuwait">Kuwait</option><option value="Kyrgyzstan">Kyrgyzstan</option><option value="Laos">Laos</option><option value="Latvia">Latvia</option><option value="Lebanon">Lebanon</option><option value="Lesotho">Lesotho</option><option value="Liberia">Liberia</option><option value="Libya">Libya</option><option value="Liechtenstein">Liechtenstein</option><option value="Lithuania">Lithuania</option><option value="Luxembourg">Luxembourg</option><option value="Macau">Macau</option><option value="Macedonia">Macedonia</option><option value="Madagascar">Madagascar</option><option value="Malaysia">Malaysia</option><option value="Malawi">Malawi</option><option value="Maldives">Maldives</option><option value="Mali">Mali</option><option value="Malta">Malta</option><option value="Marshall Islands">Marshall Islands</option><option value="Martinique">Martinique</option><option value="Mauritania">Mauritania</option><option value="Mauritius">Mauritius</option><option value="Mayotte">Mayotte</option><option value="Mexico">Mexico</option><option value="Midway Islands">Midway Islands</option><option value="Moldova">Moldova</option><option value="Monaco">Monaco</option><option value="Mongolia">Mongolia</option><option value="Montserrat">Montserrat</option><option value="Morocco">Morocco</option><option value="Mozambique">Mozambique</option><option value="Myanmar">Myanmar</option><option value="Nambia">Nambia</option><option value="Nauru">Nauru</option><option value="Nepal">Nepal</option><option value="Netherland Antilles">Netherland Antilles</option><option value="Netherlands">Netherlands (Holland, Europe)</option><option value="Nevis">Nevis</option><option value="New Caledonia">New Caledonia</option><option value="New Zealand">New Zealand</option><option value="Nicaragua">Nicaragua</option><option value="Niger">Niger</option><option value="Nigeria">Nigeria</option><option value="Niue">Niue</option><option value="Norfolk Island">Norfolk Island</option><option value="Norway">Norway</option><option value="Oman">Oman</option><option value="Pakistan">Pakistan</option><option value="Palau Island">Palau Island</option><option value="Palestine">Palestine</option><option value="Panama">Panama</option><option value="Papua New Guinea">Papua New Guinea</option><option value="Paraguay">Paraguay</option><option value="Peru">Peru</option><option value="Phillipines">Philippines</option><option value="Pitcairn Island">Pitcairn Island</option><option value="Poland">Poland</option><option value="Portugal">Portugal</option><option value="Puerto Rico">Puerto Rico</option><option value="Qatar">Qatar</option><option value="Republic of Montenegro">Republic of Montenegro</option><option value="Republic of Serbia">Republic of Serbia</option><option value="Reunion">Reunion</option><option value="Romania">Romania</option><option value="Russia">Russia</option><option value="Rwanda">Rwanda</option><option value="St Barthelemy">St Barthelemy</option><option value="St Eustatius">St Eustatius</option><option value="St Helena">St Helena</option><option value="St Kitts-Nevis">St Kitts-Nevis</option><option value="St Lucia">St Lucia</option><option value="St Maarten">St Maarten</option><option value="St Pierre &amp; Miquelon">St Pierre &amp; Miquelon</option><option value="St Vincent &amp; Grenadines">St Vincent &amp; Grenadines</option><option value="Saipan">Saipan</option><option value="Samoa">Samoa</option><option value="Samoa American">Samoa American</option><option value="San Marino">San Marino</option><option value="Sao Tome &amp; Principe">Sao Tome &amp; Principe</option><option value="Saudi Arabia">Saudi Arabia</option><option value="Senegal">Senegal</option><option value="Serbia">Serbia</option><option value="Seychelles">Seychelles</option><option value="Sierra Leone">Sierra Leone</option><option value="Singapore">Singapore</option><option value="Slovakia">Slovakia</option><option value="Slovenia">Slovenia</option><option value="Solomon Islands">Solomon Islands</option><option value="Somalia">Somalia</option><option value="South Africa">South Africa</option><option value="Spain">Spain</option><option value="Sri Lanka">Sri Lanka</option><option value="Sudan">Sudan</option><option value="Suriname">Suriname</option><option value="Swaziland">Swaziland</option><option value="Sweden">Sweden</option><option value="Switzerland">Switzerland</option><option value="Syria">Syria</option><option value="Tahiti">Tahiti</option><option value="Taiwan">Taiwan</option><option value="Tajikistan">Tajikistan</option><option value="Tanzania">Tanzania</option><option value="Thailand">Thailand</option><option value="Togo">Togo</option><option value="Tokelau">Tokelau</option><option value="Tonga">Tonga</option><option value="Trinidad &amp; Tobago">Trinidad &amp; Tobago</option><option value="Tunisia">Tunisia</option><option value="Turkey">Turkey</option><option value="Turkmenistan">Turkmenistan</option><option value="Turks &amp; Caicos Is">Turks &amp; Caicos Is</option><option value="Tuvalu">Tuvalu</option><option value="Uganda">Uganda</option><option value="Ukraine">Ukraine</option><option value="United Arab Erimates">United Arab Emirates</option><option value="United Kingdom">United Kingdom</option><option value="United States of America">United States of America</option><option value="Uraguay">Uruguay</option><option value="Uzbekistan">Uzbekistan</option><option value="Vanuatu">Vanuatu</option><option value="Vatican City State">Vatican City State</option><option value="Venezuela">Venezuela</option><option value="Vietnam">Vietnam</option><option value="Virgin Islands (Brit)">Virgin Islands (Brit)</option><option value="Virgin Islands (USA)">Virgin Islands (USA)</option><option value="Wake Island">Wake Island</option><option value="Wallis &amp; Futana Is">Wallis &amp; Futana Is</option><option value="Yemen">Yemen</option><option value="Zaire">Zaire</option><option value="Zambia">Zambia</option><option value="Zimbabwe">Zimbabwe</option></select></div>
				<div class="g-block size-30"><span>Email: </span></div>
				<div class="g-block size-70"><input autocomplete="off" name="mail" size="10" type="text" required/></div>
				<div class="g-block size-30"><span>Τηλέφωνο: </span></div>
				<div class="g-block size-70"><input autocomplete="off" name="phone" size="10" type="text" required/></div>
				<div class="g-block size-100">
					<h2>Στοιχεία Χρέωσης</h2>
				</div>
				<div class="g-block size-30"><label>Συμπληρώστε ποσό: </label></div>
				<div class="g-block size-70"><input autocomplete="off" name="amount" size="10" type="text" required/></div>
				<div class="g-block size-30"><span>Όνομα Κατόχου: </span></div>
				<div class="g-block size-70"><input autocomplete="off" name="FullName" size="20" type="text" data-vp="cardholder" required/> <i class="fa fa-question-circle" title="Το όνομα όπως αναγράφεται στην κάρτα" data-uk-tooltip="{pos:'right'}"></i></div>
				<div class="g-block size-30"><label> <span>Αριθμός Κάρτας: </span></label></div>
				<div class="g-block size-70"><input autocomplete="off" maxlength="16" name="txtCardNumber" size="20" type="text" data-vp="cardnumber" required/><i class="fa fa-question-circle" title="16 ψηφία, χωρίς κενά" data-uk-tooltip="{pos:'right'}"></i></div>
				<div class="g-block size-30"><label> <span>CVV: </span></label></div>
				<div class="g-block size-70"><input autocomplete="off" name="txtCVV" size="4" type="text" class="cvv" data-vp="cvv" required/> <i class="fa fa-question-circle" title="Ο 3ψήφιος αριθμός στο πίσω μέρος της κάρτας" data-uk-tooltip="{pos:'right'}"></i></div>
				<div class="g-block size-30"><label> <span>Ημερομηνία Λήξης :</span></label></div>
				<div class="g-block size-70"><input autocomplete="off" name="txtMonth" size="2" type="text" class="month" placeholder="MM" data-vp="month" required/> <span> / </span> <input autocomplete="off" name="txtYear" size="4" type="text" class="year" placeholder="YYYY" data-vp="year" /></div>
				<div class="g-block size-17" title="" data-uk-tooltip="">
					
					<a href="#terms" data-uk-modal=""><label>Αποδέχομαι τους όρους</label></a>
					
					<div id="terms" class="uk-modal">
						<div class="uk-modal-dialog">
							<a class="uk-modal-close uk-close"></a>						
						</div>
					</div>
				</div>
				<div class="g-block size-10"><input name="terms" type="checkbox" class="tickbox" value="1" required/></div>
			</div>
			
			<input name="OrderId" type="hidden" value="146228" />
			<input name="hidToken" type="hidden" id="hidToken" />
			<input type="submit" value="Υποβολή" class="submit" onclick="return VivaPayments.cards.requestToken();" /></form>`

**Comment by andyz1974** [comment]
Επίσης, να προσθέσω ότι τα στοιχεία αυτά αποστέλλονται με email στη διαχείριση του site και η αποστολή ολοκληρώεται κανονικά. Το σφάλμα και το μήνυμα αφορά μόνο την πληρωμή.

**Comment by defilerc** [comment]
Καλησπέρα @andyz1974 ,

Η φόρμα που έχετε στείλει, φαίνεται να είναι σωστή. Μια πιθανή αιτία για το συγκεκριμένο μήνυμα λάθους που λαμβάνετε είναι ότι το Public Key, το οποίο χρησιμοποιείται για να κάνετε την κλήση στο viva payments api, δεν είναι σωστό.

Παρακαλώ βεβαιωθείτε ότι το έχετε αντιγράψει σωστά από τη σελίδα του εμπόρου σας, πηγαίνοντας στη σελίδα Ρυθμίσεις -> Πρόσβαση API και αντιγράφοντας με copy/paste το key που βρίσκεται δίπλα στο πεδίο **Public Key** και όχι το API Key που βρίσκεται παραπάνω. Βεβαιωθείτε ότι έχετε αντιγράψει όλο το key και δεν έχετε κατά λάθος βάλει κάποιο επιπλέον κενό.

Αν εξακολουθείτε και αντιμετωπίζετε πρόβλημα, ξαναδοκιμάστε να αναπαράγετε το λάθος, έχοντας ανοιχτό το development console (π.χ. πατώντας F12 στον google chrome) και πείτε μας, αν σας εμφανίζει κάποιο λάθος στον browser στο tab Console, όταν πατάτε το κουμπί _Υποβολή_ της φόρμας σας.

Ευχαριστούμε πολύ.

**Comment by andyz1974** [comment]
Επιβεβαίωσα το Public Key και είναι σωστό (εξάλλου, η συναλλαγή σε περίπτωση που ένα από τα πεδία μείνει κενό, πραγματοποιείται).
Στο console εμφανίζεται το σφάλμα "uncaught exception: unknown (can't convert to string)" και το μήνυμα στο browser είναι: 
"The following error occured: Source 3751 of merchant a61a9e19-cca4-4ed3-9eb0-51aa7e2d390a supports only native checkoutTransaction Failure "
Σε περίπτωση που θέλετε να επιβεβαιώσετε το πρόβλημα, μπορείτε να το δείτε εδώ: http://www.kokonut.gr/kefim/el/dwrees.

Σας ευχαριστώ και πάλι.

**Comment by defilerc** [comment]
Καλημέρα @andyz1974 ,

Μπορείτε να μας στείλετε τα ακριβή στοιχεία που συμπληρώνετε στη φόρμα και αναπαράγουν το συγκεκριμένο error, ώστε να δούμε τι ακριβώς συμβαίνει; 

Αν μπορείτε, στείλτε κάποιο screenshot που να φαίνονται όλα τα στοιχεία της φόρμας συμπληρωμένα και τα οποία δημιουργούν το error, όταν ο χρήστης πατήσει submit.

Σε δοκιμή που έγινε από τη μεριά μας στο site σας, το tokenization της κάρτας φαίνεται να ολοκληρώνεται σωστά, καθώς γυρνάει response code 200 (SUCCESS).

![image](https://cloud.githubusercontent.com/assets/1667459/17582751/03819790-5fb6-11e6-8789-468c8c554459.png)

Ευχαριστώ πολύ.

**Comment by andyz1974** [comment]
Καλημέρα @defilerc 
Επισυνάπτω τα screenshots
![error](https://cloud.githubusercontent.com/assets/8945918/17583167/33d40dc2-5fb8-11e6-9e94-e9b601b76bfc.png)
![screenshot-kokonut gr 2016-08-11 11-35-12](https://cloud.githubusercontent.com/assets/8945918/17583168/33d92c9e-5fb8-11e6-9f6a-72884778ca24.png)

**Comment by defilerc** [comment]
Καλησπέρα @andyz1974 ,

Δοκιμάζοντας με τα στοιχεία που μας δώσατε στο site σας, βλέπουμε πως ολοκληρώνεται κανονικά και το tokenization της κάρτας, καθώς και το post στο server σας (στη σελίδα dwrees) με επιτυχία.

![image](https://cloud.githubusercontent.com/assets/1667459/17583870/ef435498-5fbb-11e6-8daf-31ffb880f091.png)

Υπάρχει περίπτωση να έχετε εγκατεστήμενο κάποιο plugin στον browser σας, το οποίο να επηρεάζει τη συμπεριφορά της σελίδας (π.χ. κάποιο form auto-fill) και να αλλάζει τα πεδία που γίνονται submit;

Μπορείτε να αναπαράγετε το error και από άλλον browser;

Ευχαριστούμε πολύ.

**Comment by andyz1974** [comment]
@defilerc συμβαίνει το εξής: με Google Chrome και με Microsofr Edge, η διαδικασία ολοκληρώνεται κανονικά. 
Στον Mozilla απενεργοποίησα όλα τα πρόσθετα, καθώς και το antivirus (για κάθε ενδεχόμενο), αλλά το πρόβλημα παραμένει. Το περίεργο είναι ότι αν παρελείψω να συμπληρώσω ένα πεδίο, π.χ. την πόλη, τότε η διδαδικασία ολοκληρώνεται και στον Mozilla κανονικά...

Και πάλι ευχαριστώ.

**Comment by defilerc** [comment]
Καλησπέρα @andyz1974 ,

Ύστερα από δοκιμές και με Firefox, το tokenization της κάρτας φαίνεται να ολοκληρώνεται σωστά και εκεί. Το πρόβλημα εμφανίζεται κατά τη μετέπειτα επεξεργασία των δεδομένων που έχουν γίνει post στο server.

Μπορείτε να μας στείλετε το server-side κομμάτι του κώδικα που κάνει process την παραγγελία, ώστε να δούμε τί γίνεται εκεί;

Ευχαριστούμε πολύ.

**Comment by andyz1974** [comment]
Βεβαίως. Είναι το παρακάτω:
`<?php
require_once("libraries/NativeCheckoutClass.php");
if (count($_POST)>0 AND isset($_POST['sendmail'])){
	if ($_POST['terms']== 1) {
	// Remember to change the API Credentials in the NativeCheckoutClass file
	$page=new NativeCheckout();
	$amount=$_POST['amount']*100; // in cents
	$name=$_POST['FullName'];
	$email=$_POST['mail'];
	$tel=$_POST['phone'];
	$l_name=$_POST['lastname'];
	$f_name=$_POST['firstname'];	
	$address=$_POST['address'];
	$city=$_POST['city'];
	$postal=$_POST['postal'];
	$country=$_POST['country'];
	$transactionId=$page->MakePayment($amount,$_POST["hidToken"],$_POST["drpInstallments"],$name,$email,$tel);
	if ($transactionId!='0')
		echo "Transaction Succesful for ". $name ." with Id :".$transactionId;
	else
		echo "Transaction Failure";
	}
	else echo "You must accept the terms";
}
?>
<?php
if (isset($_POST['sendmail'])){	
	$subject="Νέα εγγραφή";
	$headers .= "Content-type: text/html; charset=utf-8; \r\n";
	$headers .= "From: Ειδοποίηση Πληρωμής \r\n";
	$message= '<h1>New subscription</h1>
	<div>'.$f_name.'</div>
	<div>'.$l_name.'</div>
	<div>'.$address.'</div>
	<div>'.$postal.'</div>
	<div>'.$city.'</div>
	<div>'.$country.'</div>
	<div>'.$tel.'</div>
	<div>'.$email.'</div>';
	mail('xzervas@gmail.com', $subject, $message, $headers );
}
?>`

**Comment by defilerc** [comment]
@andyz1974 Η πληρωμή φαίνεται να γίνεται στην `$page->MakePayment`, επομένως θα χρειαστούμε και αυτό τον κώδικα.

**Comment by andyz1974** [comment]
@defilerc είναι σχεδόν αντιγραφή από το παράδειγμα που δίνετε, το NativeCheckoutClass.php

`<?php
class OrderRequest {}
class PaymentRequest {}
class NativeCheckout {
	private $merchantId = 'a61a9e19-cca4-4ed3-9eb0-51aa7e2d390a';
	private $apiKey = 'p092431'; 
	private $baseApiUrl = "http://demo.vivapayments.com";
    private $paymentsUrl = "/api/transactions";
    private $paymentsCreateOrderUrl = "/api/orders";
    // A Source for which its Integration method is 
    // set to "Native/Pay with Viva Wallet" option.
    // See http://demo.vivapayments.com/selfcare/en-US/sources/paymentsources
	private $nativeCheckoutSourceCode = 3751;
	private $resultObj = "";
	
	public function MakePayment($amount,$cardToken,$installments,$name,$email,$tel,$AllowRecurring='true'){
		
		$orderCode=$this->CreateOrder($amount,$installments,$name,$email,$tel);
		
		$obj=new PaymentRequest();
		
		$obj->Amount=$amount;
		$obj->OrderCode=$orderCode;
		$obj->SourceCode=$this->nativeCheckoutSourceCode;
		$obj->CreditCard["Token"]=$cardToken;
		$obj->Installments=$installments;		
		$obj->FullName=$name;
		$obj->Phone=$tel;
		$obj->Email=$email;
				
		$resultObj = $this->ExecuteCall($this->baseApiUrl.$this->paymentsUrl,$obj);
				
		if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
			return $resultObj->TransactionId;
		}
		else{
			echo 'The following error occured: ' . $resultObj->ErrorText;
			return '0';
		}	
	}
	
	private function CreateOrder($amount,$installments,$name,$email,$tel){
	
		$obj=new OrderRequest();
		
		$obj->Amount=$amount;
		$obj->SourceCode=$this->nativeCheckoutSourceCode;
		$obj->MaxInstallments=$installments;
		$obj->FullName=$name;
		$obj->Phone=$tel;
		$obj->Email=$email;
				
		$resultObj = $this->ExecuteCall($this->baseApiUrl.$this->paymentsCreateOrderUrl,$obj);
		
		if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
			return $resultObj->OrderCode;
		}
		else{
			echo 'The following error occured: ' . $resultObj->ErrorText;
			return 0;
		}	
	}	
	
	private function ExecuteCall($postUrl,$postobject){
	
		$postargs=json_encode($postobject);
	
		// Get the curl session object
		$session = curl_init($postUrl);
		
		// Set the POST options.
		curl_setopt($session, CURLOPT_POST, true);
		curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
		curl_setopt($session, CURLOPT_HTTPHEADER, array(                                                                          
			'Content-Type: application/json',                                                                                
			'Content-Length: ' . strlen($postargs))                                                                       
		);   
		curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($session, CURLOPT_USERPWD, $this->merchantId.':'.$this->apiKey);
		curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
		
		curl_setopt($session, CURLOPT_HEADER, true);
		
		// Do the POST and then close the session
		$response = curl_exec($session);
		
		// Separate Header from Body
		$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
		$resHeader = substr($response, 0, $header_len);
		$resBody =  substr($response, $header_len);
		
		// Parse the JSON response
		try {
			if(is_object(json_decode($resBody))){
				$resultObj=json_decode($resBody);
			}else{
				preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader, $match);
				throw new Exception(trim($match[1]));
			}
		} catch( Exception $e ) {
			echo $e->getMessage();
		}
		
		curl_close($session);
		return $resultObj;
	}
	
}
?>`

**Comment by defilerc** [comment]
Καλησπέρα @andyz1974 ,

Θα θέλαμε να κάνετε την εξής αλλαγή και να δοκιμάσετε να δείτε αν συνεχίζετε και παίρνετε το ίδιο error:

Στην html σελίδα, αλλάξτε τον τύπο του κουμπιού Υποβολή από `submit `σε `button`. Δηλαδή, από:

`<input type="submit" value="Υποβολή" class="submit" onclick="return VivaPayments.cards.requestToken();" />`

σε

`<input type="button" value="Υποβολή" class="submit" onclick="return VivaPayments.cards.requestToken();" />`

Ευχαριστούμε πολύ.

**Comment by andyz1974** [comment]
Καλησπέρα @defilerc 
Πράγματι, το πρόβλημα λύθηκε.
Ευχαριστώ πολύ για την εξαιρετική υποστήριξη!
