### ISSUE TITLE
page blanche 3D Secure

### ISSUE THREAD

**Issue by simondoap** [VivaPayments/API#1571]
après le redirection du paiement vers la plateforme Vivawallet, le client ayant renseigné le paiement se retrouve avec une page blanche juste marquée 3D Secure. Et donc le paiement n'aboutit pas

**Comment by highabove** [comment]
I am having the same issue. When customer pays using their card via Vivawallet it redirects to a blank page with -1 on it?

**Comment by matthewrgourd** [comment]
@simondoap how many of your customers are ok and have made payments? Can you send through your e-commerce website address and the company registration number if possible, please?

**Comment by matthewrgourd** [comment]
@highabove that sounds very much like a separate issue from this one. Please raise using the **New Issue** button at https://github.com/VivaPayments/API/issues

**Comment by highabove** [comment]
I solved the issue by changing the success/fail urls to (see image)

[Craig Douglas](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=gt46s)	[gt46s]
Craig Douglas
High Above Health
CBD Oils UK
www.highabovehealth.co.uk

On April 15, 2020 at 10:53 GMT, matthewrgourd <notifications@github.com> wrote:

[@highabove](https://github.com/highabove) that sounds very much like a separate issue from this one. Please raise using the New Issue button at https://github.com/VivaPayments/API/issues

**Comment by highabove** [comment]
And I’m not gonna start a new issue for you to take days to answer. Your support is terrible.

[Craig Douglas](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=gt51k)	[gt51k]
Craig Douglas
High Above Health
CBD Oils UK
www.highabovehealth.co.uk

On April 15, 2020 at 10:53 GMT, matthewrgourd <notifications@github.com> wrote:

[@highabove](https://github.com/highabove) that sounds very much like a separate issue from this one. Please raise using the New Issue button at https://github.com/VivaPayments/API/issues

**Comment by matthewrgourd** [comment]
@highabove you raised your issue within another customer's issue. That's the only reason I asked you to create your own which I would have dealt with today but it sounds like you fixed the problem yourself. There has been a bank holiday weekend and I'm trying to catch up. Unfortunately there's only one of me! Best wishes.
