### ISSUE TITLE
πληρωμή μεσω viva

### ISSUE THREAD

**Issue by epiplakokkinos** [VivaPayments/API#1572]
Καλησπέρα σας. 
Το eshop μας ειναι WooCommerce και όταν ένας πελάτης κάνει παραγγελία και θέλει να πληρώση μέσω viva όταν το κάνει αργεί περίπου μισή μέρα να μας έρθει email η παραγγελία του.
Όταν όμως το τσεκάρεις μέσα από την πλατφόρμα του WooCommerce σου γράφει>  Πληρωμή μέσω Πληρωμή μέσω VivaWallet αλλά το έχει σαν Εκκρεμεί Πληρωμή.

**Comment by matthewrgourd** [comment]
Hi @epiplakokkinos This is normal for our WooCommerce plugin. There are always some payments in pending as they are automatically generated when a card is declined for a reason given by the issuer. My understanding is that in these instances they later get changed to cancelled automatically after a couple of days.
