### ISSUE TITLE
vivawallet plugin prestashop

### ISSUE THREAD

**Issue by George-Sexyworld** [VivaPayments/API#1573]
Το plugin που έχετε διαθέσιμο για κατέβασμα στο σύνδεσμο: (https://developer.vivawallet.com/e-commerce-plugins/prestashop/), αφορά Prestashop 1.7.
Το δικό μου Prestashop είναι 1.6.0, πως θα κάνω εγκατάσταση?

**Comment by matthewrgourd** [comment]
@George-Sexyworld our plugin is backwards compatible with version 1.5 onwards. So you can follow the [same instructions](https://developer.vivawallet.com/e-commerce-plugins/prestashop/). Hope this helps!
