### ISSUE TITLE
NO MASTERCARD PAYMENTS

### ISSUE THREAD

**Issue by egiochiamo** [VivaPayments/API#1574]
I have 2 websites, Woocommerce and Magento 1.9.6

My customers said me that only VISA card payments can be used, the payments with mastercard instead go in error.
Please help me

in both my websites it happens
My websites are: e-giochiamo.it and erbalegaleonline.com

Mastercard card payment is very important for my websites
Regards

**Comment by egiochiamo** [comment]
Any help please?

**Comment by egiochiamo** [comment]
I SENT AN EMAIL WITH MY MERCHANT ID TO mgourd@vivawallet.com
PLEASE HELP ME

**Comment by matthewrgourd** [comment]
@egiochiamo thanks for sending through the details of your account. I'm checking with one of our developers to see if you're enrolled with Mastercard. If not, we need to request it.

**Comment by matthewrgourd** [comment]
@egiochiamo we have checked your account and you are now enrolled with Mastercard. There are plenty of recent Mastercard payments. Best wishes.

**Comment by matthewrgourd** [comment]
@egiochiamo is everything ok now?

**Comment by matthewrgourd** [comment]
@egiochiamo I can confirm that, yes. Best wishes.
