### ISSUE TITLE
Translation issues Prestashop 1.7

### ISSUE THREAD

**Issue by Petroskall-tech** [VivaPayments/API#1575]
Hello,
I was trying to translate the Vivapayments module for prestashop 1.7.6.2 version (specifically I wanted to translate the payment option inside the Checkout Page) and while I did manage to translate in the BO the module,unfortunately nothing changed in the Front office.

I also cleared my cache,the websites cache and even disabled cache of the website,no changes.

Last but not least I tried to translate another Payment option (paypal) and it did translate with no issues so it seems that it is not a general issue but a module issue

**Comment by matthewrgourd** [comment]
Hi @Petroskall-tech thanks for raising and letting us know the results of your research. I will pass on to a developer to look into.
