### ISSUE TITLE
WooCommerce - Payment Issue -WooCommerce Plugin

### ISSUE THREAD

**Issue by arissk** [VivaPayments/API#1577]
Hello,

We have an issue with the payment. The issue is when the payment is completed and after the 3D secure message it doesn't redirect to the correct page and shows a blank page with the number -1 instead.

This also happens while using the sandbox. 

I have followed the documentation step by step. 

One more thing. You should replace the old pictures of the plugin in WooCommerce with the ones that you now have. Cause some options have changed.

See attached image.
![Screenshot 2020-04-10 at 11 58 44](https://user-images.githubusercontent.com/16369047/78983387-c9a48000-7b2c-11ea-9b74-1de06ada0690.png)

**Comment by highabove** [comment]
I am having the exact same issue. Have you have any luck on a resolution yet?

**Comment by highabove** [comment]
Does anyone even read these? Where’s the support team?

**Comment by arissk** [comment]
Unfortunately no. I am still waiting and my client decided to keep it this way while we wait for the fix, cause the payments are being received despite the issue... I hope that we will have a solution soon. 

I suppose it has something to do with the new version of WooCommerce...

**Comment by barmatt75** [comment]
Hi,

I use Woocommerce 4.0.1

I had the same problem and I modified the success and failure urls in the Vivawallet dashboard by this "wc-api / WC_Papaki_Vivapayments_Gateway".

See screen below
<img width="587" alt="dashboard" src="https://user-images.githubusercontent.com/7480021/79212884-932a7600-7e48-11ea-9cef-ec377022c145.png">

**Comment by highabove** [comment]
Thank you!! I chnaged the URL's and everything working perfect now :)

**Comment by arissk** [comment]
You are a life saver mate! Thanks a lot!
