### ISSUE TITLE
Demo success payment sending to cancel url

### ISSUE THREAD

**Issue by IndiAsh** [VivaPayments/API#1579]
H have a demo account on https://demo.vivapayments.com/
I have created a source code (6351) that has different Success URL and Failure URL.

When i make the payment with card number 4111111111111111 i get 2 option one for success and one for failure. When i select the failure the system send me to the failure url. When i select success the system send me to failure url again. 

There is a custom build and the url is https://wonder.netplanet.gr

**Comment by matthewrgourd** [comment]
Hi @IndiAsh can you share your actual code so I can see what you're seeing. If there's anything confidential, email me at mgourd@vivawallet.com. Thanks!

**Comment by matthewrgourd** [comment]
Closing issue as no reply...
