### ISSUE TITLE
Null In res.Data Response Object From /api/Transactions

### ISSUE THREAD

**Issue by ppsichopedas** [VivaPayments/API#158]
Καλησπέρα σας,
Έχουμε υλοποιήσει εδώ και πολύ καιρό την σύνδεση με το API και πριν από δύο μέρες παρατηρήθηκε το εξής φαινόμενο:

Στην προσπάθεια ενός πελάτη μας να κάνει αγορά (πρώτη φορά) η κλήση στο api/Transactions απάντησε με null στο property data!

Στο σημείο αυτό θα ήθελα να σας επισημάνω ένα σφάλμα που έχετε στον κώδικα σας στην σελίδα: 
[https://github.com/VivaPayments/API/wiki/Native-Checkout](https://github.com/VivaPayments/API/wiki/Native-Checkout)
το οποίο είναι άμεσα συνεδεμένο με το πρόβλημα που σας περιγράφω.

Συγκεκριμένα στην ενότητα Full Sample στο τέλος της σελίδα έχετε τον παρακάτω κώδικα:

> protected void Page_Load(object sender, EventArgs e)
>     {
>         if (Request.HttpMethod == "POST") {
> 
>             var _orderCode = CreateOrder(10000);    //CALL TO CREATE AN ORDER. IF AN ORDER CODE ALREADY EXISTS FROM A PREVIOUS STEP, USE THAT ONE INSTEAD
> 
>             var cl = new RestClient(_BaseApiUrl);
>             cl.Authenticator = new HttpBasicAuthenticator(
>                                     _MerchantId.ToString(),
>                                     _ApiKey);
> 
>             var req = new RestRequest(_PaymentsUrl, Method.POST);
>             req.RequestFormat = DataFormat.Json;
>             req.AddBody(new {
>                 OrderCode = _orderCode,
>                 SourceCode = "Default",             //MAKE SURE THIS IS A SOURCE OF TYPE NATIVE/SIMPLE 
>                 CreditCard = new {
>                     Token = hidToken.Value.ToString()
>                 }
>             });
> 
>             paymentform.Visible = false;
> 
>             var res = cl.Execute<TransactionResult>(req);
>             if (res.Data != null && res.Data.ErrorCode == 0 && res.Data.StatusId == "F") {
>                 Response.Write(String.Format(
>                     "Transaction was successful. TransactionId is {0}",
>                     res.Data.TransactionId));
>             }
>             else{
>                 Response.Write(String.Format(
>                     "Transaction failed. Error code was {0}",
>                     res.Data.ErrorCode));
>             }
> 
>         }
>     }

Στο If μετά την απάντηση από την υπηρεσία σας κάνετε έλεγχο εάν το **res.Data != null** και στην περίπτωση που είναι, (else) προσπαθείτε να διαβάσετε το **res.Data.ErrorCode**

Αυτό ακριβώς συνέβη στην δική μας περίπτωση:
Ο πελάτης στην πρώτη του απόπειρα πήρε πίσω null στο res.Data με αποτέλεσμα εμείς με την σειρά μας να θεωρήσουμε ότι η απόπειρα απέτυχε και να  τον αφήσουμε να προσπαθήσει ξανά.
Στο σύστημά σας όμως η χρέωση είχε γίνει κανονικά.

Θα ήθελα να μου δώσετε οδηγίες για το πώς να χειριστούμε την περίπτωση του res.Data == null που σας περιγράφω, διότι όταν έρθει τέτοιου είδους απάντηση δεν είναι εφικτό να συνεχίσουμε την διαδικασία πληρωμής αλλά ούτε να ξέρουμε τι έχει συμβεί στο σύστημά σας.

**Comment by dpnevmatikos** [comment]
Καλησπέρα @ppsichopedas ,

> Στην προσπάθεια ενός πελάτη μας να κάνει αγορά (πρώτη φορά) η κλήση στο api/Transactions απάντησε με null στο property data!

Μπορείτε να δείτε σε αυτή την περίπτωση το ```res.StatusCode``` τι τιμή έχει? Συνήθως αυτό συμβαίνει όταν έχετε βάλει λάθος [MerchantId](https://github.com/VivaPayments/API/blob/master/NativeCheckout/ASP.NET/NativeCheckoutWebforms/Default.aspx.cs#L6).

>Στο If μετά την απάντηση από την υπηρεσία σας κάνετε έλεγχο εάν το res.Data != null και στην περίπτωση που είναι, (else) προσπαθείτε να διαβάσετε το res.Data.ErrorCode

Όντως όπως αναφέρατε το sample χρειαζοταν διόρθωση σε εκείνο το σημείο. Δείτε το ανανεωμένο sample [εδώ](https://github.com/VivaPayments/API/blob/master/NativeCheckout/ASP.NET/NativeCheckoutWebforms/Default.aspx.cs)

**Comment by ppsichopedas** [comment]
Καλησπέρα @dpnevmatikos,

Δυστηχώς δεν μπορώ να δω το `res.StatusCode` της συγκεκριμένής κλήσης γιατί δεν κρατάμε logs για το αντικείμενο res και την εάν η κλήση ήταν επιτυχής αλλά μόνο για το `res.Data` και τα data που γύρισε το σύστημά σας πίσω (ακόμη και αυτά τα data όμως τα δεν τα αποθυκέυουμε ώς έχουν λόγο pci compliance ).

Λάθος MerchantId δεν είναι δυνατό να έχει γιατί το έχουμε σαν static στον κώδικά μας. Επίσης η χρέωση πέρασε από την μερία σας στον MerchantId που εμείς στείλαμε ( έχουμε 2 MerchantId ).

Από την μερία σας δεν έχετε κάποιο τρόπο (logs ίσως) να το διασταυρώσουμε?

Σχετικά με τον ανανεωμένο κώδικά:
Yπάρχει περίπτωση να πάρουμε απάντηση `System.Net.HttpStatusCode.OK` και παρόλα αυτά το `res.Data` να είναι null?

**Comment by dpnevmatikos** [comment]
Καλησπέρα και πάλι,
> Από την μερία σας δεν έχετε κάποιο τρόπο (logs ίσως) να το διασταυρώσουμε?

Απο τη στιγμή που λέτε οτι η συναλλαγή ολοκληρώθηκε με επιτυχία τότε δε θα υπάρχει κάποιο log για να δούμε.
Αυτό που αναφέρετε (να είναι null δηλαδή το res.data) σας έχει ξανασυμβεί?

> Yπάρχει περίπτωση να πάρουμε απάντηση System.Net.HttpStatusCode.OK και παρόλα αυτά το res.Data να είναι null?

Από τη στιγμή που το status code είναι ΟΚ τότε θα έχετε πάντα τιμή στο res.data.

**Comment by ppsichopedas** [comment]
Καλησπέρα,

> Απο τη στιγμή που λέτε οτι η συναλλαγή ολοκληρώθηκε με επιτυχία τότε δε θα υπάρχει κάποιο log για να δούμε.

Δεν σας είπα ότι η συναλλαγή ολοκληρώθηκε με επιτυχία. Από την μερία σας χρεώθηκε αλλά δεν πήραμε απάντηση εμείς πίσω (res.Data == null). Και σύμφωνα με αυτό που λέτε:

> Από τη στιγμή που το status code είναι ΟΚ τότε θα έχετε πάντα τιμή στο res.data.

τότε το σύστημά σας χρέωσε τον πελάτη και δεν μας απάντησε με επιτυχία.

> Αυτό που αναφέρετε (να είναι null δηλαδή το res.data) σας έχει ξανασυμβεί?

Όχι δεν έχουμε κάποια άλλη περίπτωση, μόνο αυτή που σας αναφέρω στις 2016-07-28 16:48:53.527


Από την μερία μας αλλάξαμε τον κώδικα μας να ελέγχει το StatusCode και να _υποθέτει_ ότι η χρέωση δεν πέρασε στην περίπτωση που δεν πάρουμε OK.
Tο ίδιο συνέβαινε και πρίν βέβαια με τον ελεγχο `res.Data != null` και γι αυτό σας ζήτησα να ερευνήσετε τυχον logs από την συγκεκριμένη περίοδο.

**Comment by dpnevmatikos** [comment]
Καλησπέρα και πάλι @ppsichopedas 
Ελέγξαμε τα logs σε εκείνο το διάστημα (+- 5 λεπτά) αλλά δεν είδαμε κάποιο σφάλμα.
Μήπως έχετε το ordercode από την εν λόγω συναλλαγή?

Ευχαριστώ.

**Comment by defilerc** [comment]
Κλείνουμε το issue, λόγω απουσίας κάποιας δραστηριότητας για πάνω από ένα μήνα. 

Σε περίπτωση που ακόμα ενδιαφέρεστε για υποστήριξη και δεν έχετε επιλύσει το πρόβλημά σας, μπορείτε να ξανά ανοίξετε το συγκεκριμένο issue ή να δημιουργήσετε κάποιο νέο.

Με εκτίμηση
