### ISSUE TITLE
Woocomerce - webhook url invalid

### ISSUE THREAD

**Issue by Bahwaimongars** [VivaPayments/API#1580]
Good morning, sir,

I'm taking the liberty of contacting you because I have a problem with the activation of the webhook.

- I'm using the right version of the plugin (the one in the official documentation)

Below are some screenshots.

Sincerely!

**Comment by Bahwaimongars** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/62238066/78997297-9a027180-7b46-11ea-910e-095677819366.jpg)

**Comment by Bahwaimongars** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/62238066/78997306-9f5fbc00-7b46-11ea-99ab-e6be982c8bc3.jpg)

**Comment by Bahwaimongars** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/62238066/78997368-bc948a80-7b46-11ea-91fd-d651ae7644e1.jpg)

**Comment by matthewrgourd** [comment]
Hi @Bahwaimongars sorry to hear you're having a problem setting up a webhook. More info about URI verification is available here: 

https://developer.vivawallet.com/api-reference-guide/payment-api/webhooks/#webhook-url-verification

But webhooks are optional and used for specific purposes outlined here:

https://developer.vivawallet.com/api-reference-guide/payment-api/webhooks/

Please note these are optional: you don't need to set one up for our payments gateway to successfully receive payments from your customers.

Hope this helps!

**Comment by Bahwaimongars** [comment]
Good morning, sir,
Thank you for your return.

Indeed the payment is going well, however I have no update on the wordpress side: 
The order remains pending even though the payment has been made.

**Comment by matthewrgourd** [comment]
Hi @Bahwaimongars, I have an update for you. Unfortunately, one of our developers tested recently and discovered that the webhook functionality isn't currently working. I'm not yet sure when a fix will be applied. I'll update this ticket once I know more. Apologies for any inconvenience caused. Have a good day!

**Comment by matthewrgourd** [comment]
Hi @Bahwaimongars, I've looked into this and can confirm that unfortunately the webhooks functionality for our WooCommerce plugin isn't working correctly. We expect to have a fix but not immediately, I'm afraid

**Comment by matthewrgourd** [comment]
Hi @Bahwaimongars apparently the fix should be in the next week or so along with a general overhaul of our plugin. Please keep checking our new Wordpress plugin page for the latest info: https://en-gb.wordpress.org/plugins/vivawallet-woocommerce-gateway  Thanks!

**Comment by weecl** [comment]
> Hi @Bahwaimongars apparently the fix should be in the next week or so along with a general overhaul of our plugin. Please keep checking our new Wordpress plugin page for the latest info: https://en-gb.wordpress.org/plugins/vivawallet-woocommerce-gateway Thanks!

Just translated the whole plugin in french :)
