### ISSUE TITLE
Vivawallet payment platform

### ISSUE THREAD

**Issue by estebanascione** [VivaPayments/API#1581]
Hi, I would like to be able to accept payments on my shopify account https://winis-deal.myshopify.com/ via my payment platform vivawallet Esteban Ascione. Can you give me permission? Please

**Comment by matthewrgourd** [comment]
Hi @estebanascione please view the instructions in our Shopify plugin guide: https://developer.vivawallet.com/e-commerce-plugins/shopify/ One of the first and most important steps is to email our support team on support@vivawallet.com with the below details:
- Company name
- Merchant ID
- Shopify Store name
- Shopify Store URL
Have you done this yet? I know there is a bank holiday in some cases as our team is spread across different countries in the EU. So, apologies, there make be a slight delay in receiving your token which is needed for setup of our plugin.

**Comment by estebanascione** [comment]
I just sent the email to the email address indicated with all the information. What must I do now?


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : matthewrgourd <notifications@github.com>
Envoyé : Friday, April 17, 2020 10:38:38 AM
À : VivaPayments/API <API@noreply.github.com>
Cc : estebanascione <esteban.ascione@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [VivaPayments/API] Vivawallet payment platform (#1581)


Hi @estebanascione<https://github.com/estebanascione> please view the instructions in our Shopify plugin guide: https://developer.vivawallet.com/e-commerce-plugins/shopify/ One of the first and most important steps is to email our support team on support@vivawallet.com<mailto:support@vivawallet.com> with the below details:

  *   Company name
  *   Merchant ID
  *   Shopify Store name
  *   Shopify Store URL

Have you done this yet? I know there is a bank holiday in some cases as our team is spread across different countries in the EU. So, apologies, there make be a slight delay in receiving your token which is needed for setup of our plugin.

**Comment by matthewrgourd** [comment]
Wait until you receive a token from us. Nothing more can be done until then, I’m afraid!

**Comment by matthewrgourd** [comment]
Hi @estebanascione, did you receive the token? Are you up and running now?

**Comment by estebanascione** [comment]
Vivawallet don’t give me the Token

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : matthewrgourd<mailto:notifications@github.com>
Envoyé le :lundi 20 avril 2020 11:55
À : VivaPayments/API<mailto:API@noreply.github.com>
Cc : estebanascione<mailto:esteban.ascione@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [VivaPayments/API] Vivawallet payment platform (#1581)


Hi @estebanascione<https://github.com/estebanascione>, did you receive the token? Are you up and running now?

**Comment by matthewrgourd** [comment]
@estebanascione please email support@vivawallet.com asking where your Shopify token has got to. Also, check your spam folder in case an email has been missed. Thanks!
