### ISSUE TITLE
Activate website account - Foxseedseurope.fr

### ISSUE THREAD

**Issue by Nilsfox** [VivaPayments/API#1586]
Hello,

I configured the module with prestashop, and your commercial told me that you need to activate my account to use the paiement solution.

I have 2 websites :

https://www.foxseedseurope.fr/ (main website) 
https://dtcpdirect.com/

Best Regards,
Nils

**Comment by matthewrgourd** [comment]
Hi @Nilsfox, I've checked and you need to set up new payment sources for both e-commerce websites. You do this via the Viva Wallet banking app (see step 1 of our guide below).

https://developer.vivawallet.com/e-commerce-plugins/prestashop/

Hope this helps!
