### ISSUE TITLE
Transactions stay on pending and are not updating

### ISSUE THREAD

**Issue by adriansome** [VivaPayments/API#1588]
Hi Our Viva Wallet / Woocommerce transactions stay on pending and are not updating. Consequently we are not receiving any email notifications of product purchases or payments.

We have made a few changes to the url information and added a webhook, as a result our online payment account has been given a status of 'pending', see atached image.

Viva Wallet has given us a link to this GitHub to get our account status off pending

**Comment by adriansome** [comment]
OK, I think I have managed to sort the 'pending' issue out. However, I can't understand how your success url works. Please see the attached screen grab of our admin setup, which sends us to a 'page not found' url. This is where a recent test transaction took us. https://hemptyonline.co.uk/thank-you-for-your-order/?t=c24ef333-57f7-4bb6-806e-daeace6d3e07&s=3546232884115824&lang=en-US&eventId=0&eci=1

**Comment by matthewrgourd** [comment]
Hi @adriansome, sorry for the delayed reply. I'm glad the pending payment status makes sense to you now. About the success URL, there's an explanation of the constituent parts on our developer portal, 'Redirect Checkout' page here: https://developer.vivawallet.com/online-checkouts/redirect-checkout/#step-3-confirm-the-transaction The Viva Wallet WooCommerce e-commerce plugin you're using is based on the aforementioned Redirect Checkout. Hope this helps!
