### ISSUE TITLE
προβλημα επικοινωνιας viva με shopify

### ISSUE THREAD

**Issue by djgogos** [VivaPayments/API#1589]
καλησπερα
σημερα ενημερωθηκα απο πελατη που ειχε πραγματοποιησει αγορα στο ηλεκτρονικο μου καταστημα οτι δεν εχει παρει καποια ειδοποιηση σχετικα με την παραγγελια του.
ψαχνωντας στις παραγγελιες δεν βρηκα παραγγελια στο ονομα του.
Μου εστειλε το εμαιλ απο την βιβα που εδειχνε οτι οντως ειχε πληρωσει 15 ευρω.
Εμεις ομως δεν ειχαμε  παρει καποια παραγγελια στο shopify.
Δεν μου εχει ξανασυμβει αυτο ειναι η αληθεια αλλα με προβληματισε λιγο.
τι μπορει να συνεβει ?

ευχαριστω

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. Would you be able to send me some further info. especially your business name / VAT number and Shopify store URL? Then if you could also provide the date of the transaction I will check further? Thanks!

**Comment by matthewrgourd** [comment]
Closing as no reply...
