### ISSUE TITLE
Αφαίρεση τηλεφώνου - checkout page

### ISSUE THREAD

**Issue by ebnb** [VivaPayments/API#159]
Καλησπέρα σας,
θα θέλαμε να αφαιρέσουμε την επιλογή: "Πληρώστε με κάρτα μέσω τηλεφώνου (IVR)" 
![03c10416-55a2-11e6-89d9-7d9f67ade81f](https://cloud.githubusercontent.com/assets/20724509/17855289/a1e19a34-6880-11e6-8673-b3eff9e1176d.png)

για ένα συγκεκριμένο traffic με παράμετρο 
?utm_source=Linkwise&utm_medium=Affiliates

Είναι εφικτό;

**Comment by defilerc** [comment]
Καλημέρα @ebnb ,

Όπως θα δείτε στα optional parameters της CreateOrder (https://github.com/VivaPayments/API/wiki/Optional-Parameters) υπάρχει το option `DisableIVR `το οποίο αν το θέσετε `false`, θα σταματήσει να εμφανίζεται η επιλογή της πληρωμής μέσω τηλεφώνου (IVR).

Μπορείτε να θέτετε τη συγκεκριμένη μεταβλητή, ανάλογα με το αν εμφανίζονται τα συγκεκριμένα url parameters, ώστε να μην εμφανίζεται στις συγκεκριμένες περιπτώσεις η επιλογή αυτή.

Ευχαριστούμε πολύ.

**Comment by ebnb** [comment]
Ευχαριστούμε για τις πληροφορίες :+1:
