### ISSUE TITLE
Backend API response Success: "false"

### ISSUE THREAD

**Issue by dimipak** [VivaPayments/API#1590]
Hello,

We use the api in our backend custom php app. 

I dont know when but surely is a lot of time that we have this problem but i dont know when exactly.

We use php curl and in order for a client to make a payment we use 3 curl calls.

1. https://www.vivapayments.com/api/orders
2. https://www.vivapayments.com/api/cards?key=
3. https://www.vivapayments.com/api/Transactions

The third and final step is the problem where we receive false Success.

A response example is this:

{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"Source 2119 of merchant aaa-bbb-ccc-ddd-123456789 does not support native checkout","TimeStamp":"2020-04-13T15:40:08.6457954+03:00","CorrelationId":null,"EventId":0,"Success":false}

**Comment by matthewrgourd** [comment]
Hi @dimipak sorry to hear about the intermittent issue you are experiencing with our API. Would you mind sharing the business name and web address? I will then be able to investigate further! Thanks!

**Comment by dimipak** [comment]
Hello thanks for the answer. 
Business name: "Elin Aderfoi Christoula"
Do you want also the merchant number?
Web Address: "https://www.roadcube.com"

**Comment by matthewrgourd** [comment]
@dimipak thanks for that. Unfortunately I can't find you with that info. Looks like I need company registration / VAT number, please?! Alternatively you can send merchant ID to me at mgourd@vivawallet.com citing this issue (#1590).

**Comment by dimipak** [comment]
Thanks again.

I just sent you the merchant ID from my company email: dev@roadcube.com

**Comment by matthewrgourd** [comment]
Hi @dimipak, thanks for sending through your Merchant ID. I've found the account now. I checked, and Native Checkout is definitely enabled so I'm not sure why you received that error message. I will need to investigate further, maybe with a developer. I'll let you know once I've an update!

**Comment by dimipak** [comment]
Just to give you all the information. 

Before you answered here in the first place i contact with the business and told them to change from "Redirection/Native Checkout v2" to "Native/Pay with Viva Wallet Checkout". And after that they told me to wait until viva approval.

I thought that change maybe will fix the problem but now i am receiving a slightly different error:
{"OrderCode":null,"ErrorCode":403,"ErrorText":"The merchant with id 111-222-333-444 does not have a source with code '2119' assigned or the source is disabled","TimeStamp":"2020-04-21T12:50:27.7903124+03:00","CorrelationId":null,"EventId":0,"Success":false}

**Comment by matthewrgourd** [comment]
@dimipak ok, in that case the problem is that the payment source '2119' is still in pending status. The account owner should have received an email to the registered email address advising them what to do. If not, they should send an email to support@vivawallet.com requesting that the source be made active or contact customer service for the same. Hope this helps!

**Comment by dimipak** [comment]
Hello again

After speaking with support team in Viva they accepted the url and they told us we are ready for payments.

The thing is that now i am having an other problem. Card tokenization doesnt work. I dont receive anything as a response. No success no error no nothing. Response is blank. The url i used to use is this:
https://www.vivapayments.com/api/cards?key=

I need your help! Thank you

**Comment by matthewrgourd** [comment]
Hi @dimipak, apologies, that call isn't available any more. I believe it has been replaced by `https://api.vivapayments.com/acquiring/v1/cards/tokens?chargetoken=` using the later Native Checkout v2 we built in order to be compliant with the latest PSD2 security definitions. For full details see [Generate card token](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/#step-2-generate-card-token-using-the-charge-token-optional) in the Viva Wallet [Card tokenization](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/) documentation.

**Comment by dimipak** [comment]
Hello,

I played around a little and i understand that with the new system is mandatory to use 3D Secure. Is it any other way to skip it for the moment? I just want to create the system with simple payments like i used to have before. 

1. https://www.vivapayments.com/api/orders
2. https://www.vivapayments.com/api/Transactions

These two urls above seem to still working for me. I am missing the token of the card (the middle one) which now the v2 needs to be authenticated with 3d secure if i am not mistaken. 

Thank you

**Comment by matthewrgourd** [comment]
Hi @dimipak apologies, I will need to check this with a developer and get back to you.

**Comment by matthewrgourd** [comment]
Hi @dimipak unfortunately not. In order to comply with the latest PSD2 advice, we support only 3DS payments now.
