### ISSUE TITLE
WooCommerce - payment button missing

### ISSUE THREAD

**Issue by mdh18** [VivaPayments/API#1591]
Dear Sir / Madam

I am creating an online shop on woocommerce.

I have installed and followed all the steps to use viva wallet but it is impossible to validate the order.

At the time of validating the order, no button is displayed.

<img width="694" alt="viva-wallet" src="https://user-images.githubusercontent.com/63476829/79129759-1050df00-7da6-11ea-8609-a25c871d3ab3.png">

**Comment by matthewrgourd** [comment]
Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by mdh18** [comment]
Please find enclosed the requested screenshots.

Thanks.
________________________________
De : matthewrgourd <notifications@github.com>
Envoyé : lundi 20 avril 2020 15:39
À : VivaPayments/API <API@noreply.github.com>
Cc : mdh18 <mouhcine@msn.com>; Author <author@noreply.github.com>
Objet : Re: [VivaPayments/API] WooCommerce - payment button missing (#1591)


Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

  *   WooCommerce payment module settings (mask your Merchant ID and API Key).
  *   Viva Wallet payment source<https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/> settings (include your browser's URL bar in the screenshot).
  *   Viva Wallet Websites / Apps page (include your browser's URL bar in the screenshot).
  *   API Access<https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/> page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Hi @mdh18, sorry, I can't see the screenshots. Can you try again?

**Comment by matthewrgourd** [comment]
Hi @mdh18 please send screenshots to my email address: mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
Hi @mdh18 thanks for sending those through. In the below payment module settings, in the **Source Code* field you need to replace `Likyn` with `3336`. Thanks!

![payment-module](https://user-images.githubusercontent.com/44943019/80576868-d6b2e180-89fd-11ea-9397-15e478f24f0f.jpg)
