### ISSUE TITLE
Magento URL after payment confirmation

### ISSUE THREAD

**Issue by psaldanha** [VivaPayments/API#1592]
What is your URL that asked after payment confirmation on Magento Plug-in? 
we need to test for a merchant (PT514470410) which is delivering some errors which I am not able to tell as I am not the developer. Developer email is suporte@wheelt.com but apparently did not put any question here although I asked a week ago to insert the question here (and they keep asking me this) and our merchant is complaining...

**Comment by matthewrgourd** [comment]
@psaldanha what's the company name, please? I need to check the account first. Thanks.

**Comment by psaldanha** [comment]
Ferreira e Herrero Lda and trade name is noMenu

**Comment by psaldanha** [comment]
Hi Team, they are having problems with the URL from Magento plugin that confirms the payment. They are saying that when payment is confirmed the payment confirmation page should be  www.nomenu.pt/vivawallet/hpay/hpokNevertheless, they say that no confirmations are being received on that URL. They tested with logs. They request to which URL are being sent the payment confirmations.

**Comment by matthewrgourd** [comment]
@psaldanha Can you confirm which version of Magento they're using? Are they referring to the merchant notifications? These are being sent through to their unconfirmed email address geral@nomenu.pt. If something else, please get them to send an example of the confirmation page after a successful transaction with the screenshot including their browser's current URL. They have plenty of sales transactions coming through in the CRM so I can see that the redirect seems to be working fine. Thanks.

**Comment by matthewrgourd** [comment]
Hi @psaldanha please check again our plugin installation guide as we updated it recently:

https://developer.vivawallet.com/e-commerce-plugins/magento2.1-2.2/

Please see in particular step 8:
In the Magento store settings:

MerchantID – your Viva Wallet Merchant ID
API Key – your Viva Wallet API Key
Source Code – 4-digit code for the payment source you set up in the Viva Wallet banking app
OrderCode URL – https://www.vivapayments.com/api/orders
Gateway URL – https://www.vivapayments.com/web/newtransaction.aspx
Transaction URL – https://www.vivapayments.com/api/transactions

**Comment by matthewrgourd** [comment]
Hi @psaldanha are you up and running now?

**Comment by psaldanha** [comment]
Not yet, but I think we can close this issue.
