### ISSUE TITLE
access to simple checkout

### ISSUE THREAD

**Issue by TimurMalyshev** [VivaPayments/API#1594]
I am  web-site developer. I develop a new site for my customer. My current task is to integrate vivawallet. current website is https://babyboomcyprus.com
So, i need access (demo) for simple checkou process.
Thanx/

**Comment by TimurMalyshev** [comment]
$merchantId = 'b505703d-7a91-44d2-86d4-38d17b8d44ce';

**Comment by matthewrgourd** [comment]
Hi @TimurMalyshev no problem, that's done for you now.
