### ISSUE TITLE
issue for get a orderCode in my flutter application

### ISSUE THREAD

**Issue by abdel7517** [VivaPayments/API#1596]
Map<String, String> headers = {
    "Content-Type": "application/json",
    "cache-control": "no-cache",
    "authorization":
        "Basic $$$$$$$$$$$$$$$$"
  };

  Future<VivaWallet> getVivawallet(
      String fullName, String email, int amount, String produit) {
    final msg = jsonEncode({
      "Email": email,
      "FullName": fullName,
      "PaymentTimeOut": 300,
      "RequestLang": "fr",
      "MaxInstallments": 2,
      "AllowRecurring": true,
      "IsPreAuth": true,
      "Amount": amount,
      "MerchantTrns": "Paiement pour Rapide Réparation",
      "CustomerTrns": produit
    });

    return http
        .post("https://www.vivapayments.com/api/orders",
            headers: headers, body: msg)
        .then((http.Response response) {
      final String res = response.body;
      if (response.statusCode == 200) {
        return new VivaWallet.fromJson(json.decode(res));
      } else {
        throw new Exception("Error while fetching data");
      }
    });
  }

i want to get the order code with this code but i have already exception Error while fetching data
in my real code ***** it`s my id marchand and my api key encoding with base64.
i have add my domain name in vivawallet and my bundle id  use my reverse-domain name 
sorry for my english.

**Comment by matthewrgourd** [comment]
Hi @abdel7517 sorry to hear this. Do you know what response code was returned by our API in the event of the error? This would be helpful to know. Thanks!

**Comment by matthewrgourd** [comment]
Closing as no reply...
