### ISSUE TITLE
Activate website account - Foxseedseurope.fr

### ISSUE THREAD

**Issue by Nilsfox** [VivaPayments/API#1597]
Hello,

I configured (again) the module with prestashop, and your commercial told me that you need to activate my account to use the paiement solution.

I have 2 websites :

https://www.foxseedseurope.fr/ (main website)
https://dtcpdirect.com (coming soon)

Best Regards,
Nils

**Comment by matthewrgourd** [comment]
Hi @Nilsfox this is technical support but I can try to help? If you're asking about activating a payment source, this is done by another team but I can try to chase for you. What is your registered business name, please?

**Comment by matthewrgourd** [comment]
Replied at https://github.com/VivaPayments/API/issues/1586 and this issue is a duplicate so I'm closing
