### ISSUE TITLE
Payments not processed, either URL returns (-1) or redirects to search page

### ISSUE THREAD

**Issue by mihaijbv** [VivaPayments/API#1598]
Hello,

We are unable to make the plugin work with out current Woocommerce setup. We have followed the step-by-step guide, but the users either return to a blank page with a (-1) declaration or to a 404 page. Merchant ID, API Key, Source Code are fine and we've tested all of the Order status options available. No setup seems to do the trick. 

Is there a way to debug this, please? 

These are the URLs I have used on the VivaWalltet website for the property:
Success: index.php?wc-api=wc_vivawallet&vivawallet=success
Failure: index.php?wc-api=wc_vivawallet&vivawallet=fail

URL seems to be registered properly (https://www). Not sure what to look at next. 

Thank you

**Comment by highabove** [comment]
I had the same issue and changed the success and fail URL's to -

Success: wc-api/WC_Papaki_Vivapayments_Gateway
Fail: wc-api/WC_Papaki_Vivapayments_Gateway

**Comment by matthewrgourd** [comment]
@mihaijbv sorry to hear this. Did you definitely download from our page here: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/. 

@highabove that's incorrect as it refers to an unofficial Viva Wallet plugin.

**Comment by highabove** [comment]
Can you tell me the correct urls then please as yours don’t seem to work.

[Craig Douglas](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=gtacz)	[gtacz]
Craig Douglas
High Above Health
CBD Oils UK
www.highabovehealth.co.uk

On April 15, 2020 at 13:09 GMT, matthewrgourd <notifications@github.com> wrote:

[@mihaijbv](https://github.com/mihaijbv) sorry to hear this. Did you definitely download from our page here: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/.

[@highabove](https://github.com/highabove) that's incorrect as it refers to an unofficial Viva Wallet plugin.

**Comment by matthewrgourd** [comment]
@highabove as stated by @mihaijbv. 

Success URL – index.php?wc-api=wc_vivawallet&vivawallet=success
Failure URL – index.php?wc-api=wc_vivawallet&vivawallet=fail

But you have to have downloaded our official plugin from https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip otherwise these won't work

**Comment by highabove** [comment]
Perfect that solution worked for me. Was the plugin updated?

**Comment by matthewrgourd** [comment]
@highabove no, the plugin wasn't updated, think it was just a typo.

**Comment by mihaijbv** [comment]
@matthewrgourd yes, the plugin was downloaded from the official website. I think the issue was solved, in the end, after enforcing the SSL version across domain. We will be testing this in the next couple of days and I will get back with an update if need be. Thank you
