### ISSUE TITLE
Native / CreateOrder, κανένα δε λειτουργεί

### ISSUE THREAD

**Issue by Sandbird** [VivaPayments/API#160]
Προσπαθώ να φτιάξω μία checkout σελίδα σε PHP και κανένα από τα παραδείγματα δε δουλεύει σωστά. 
Η createOrder τύπου σελίδα μου φτιάχνει τεράστια orderIds με αποτέλεσμα να βγάζει Bad Request στην επόμενη σελίδα:
`Your Order Code is: 3.4677266057726E+15`

ενώ η Native δείχνει:
```
The following error occured: Invalid order with code 5560481765072600
Transaction Failure 
```

Έχω βάλει σωστά όλα τα κλειδιά και στην NativeCheckoutClass.class και στην createOrder, και φυσικά έφτιαξα πηγές πληρωμών και έβαλα το code τους αντί το default που είχε.

Υποψιάζομαι ότι το πρόβλημα είναι αλλού....Στην εγγραφή μου στο demo site δεν έστειλα τα credentials μου (όπως ταυτότητες κτλ)....Μήπως φταίει αυτό ? 
Το ότι το demo account μου δεν έχει γίνει verified ?

Ευχαριστώ.

**Comment by defilerc** [comment]
Καλημέρα @Sandbird ,

Όσον αφορά το parsing του order code, μπορείτε να δείτε και το ακόλουθο issue και να μας πείτε αν αυτό έλυσε το πρόβλημά σας:

https://github.com/VivaPayments/API/issues/155

Ευχαριστούμε πολύ

**Comment by Sandbird** [comment]
Καλησπέρα,
Ναι έχετε δίκιο, αυτό ήταν.
Το παραπάνω 'fix' θα πιάνει και για άλλες εκδόσεις php ή θα πρέπει να κάνω έλεγχο τι έκδοση έχει ο server και αναλόγως να τρέχω το ένα case ή το άλλο? 
Ευχαριστώ

**Comment by defilerc** [comment]
Καλησπέρα,

Καλό θα ήταν να έχετε εγκατεστημένη την ίδια έκδοση php σε κάθε server που θα είναι hosted το site σας, έτσι ώστε να δείτε αν θα πρέπει να χρησιμοποιήσετε το συγκεκριμένο τρόπο ή όχι.

Αν η έκδοση της php δεν καθορίζεται από εσάς, αλλά από κάποιον provider, τότε θα πρέπει αναγκαστικά να κάνετε έλεγχο για την έκδοση της php που τρέχει κάθε φορά.

Ευχαριστούμε πολύ

**Comment by Sandbird** [comment]
Ναι δε ξέρω που θα καταλήξει ο κώδικας η αλήθεια είναι.
Αυτό το fix είναι μόνο για την 5.4 ? 'η < 5.4 ? Από 5.4 και πάνω ο κανονικός τρόπος ?
(Τα ifs να φτιάξω γι'αυτό) :)

**Comment by defilerc** [comment]
Καλό θα ήταν να συμβουλευτείτε το επίσημο site της php, γι' αυτά τα θέματα, για να δείτε ποιές εκδόσεις επηρεάζονται και τι λύσεις μπορεί να προτείνουν εκεί.

Με εκτίμηση

**Comment by Sandbird** [comment]
Ευχαριστώ πολύ!
