### ISSUE TITLE
API is available for uk

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1600]
Hi,

1) Please let us know can we use Simple Checkout API and Redirect Checkout API for UK country.
 2) Pay using Viva Wallet (Greece only) :- Here customers can create their own viva wallet account (sign up) and enter their card details, it will get saved in Viva Wallet. Next time onwards just they need to enter a mobile number and password to pay. Is this option available for the UK.

Thanks,
Pavithra

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, yes you can use Redirect / Simple Checkout if based in the UK. Regarding the 'pay using Viva Wallet' part, that isn't possible from the UK. Customers have to select the second option at checkout which is pay by card. Thanks!
