### ISSUE TITLE
Compatibility issue with Google Chrome

### ISSUE THREAD

**Issue by WeedyTech** [VivaPayments/API#1601]
Hello, 15% of our customers have an issue : after validate their 3D secure code, they are redirect to a simple blank page without anything or to a message saying "an error has occurred".

This happens with customers using Google Chrome, whether on phone or computer, and we got information from a customer that the problem also occurred on one of our competitors, who also uses the plugin. viva wallet. This customer had attempted all payments under Google Chrome.. And their order are in "pending payment".

15% is a very high fail rate in e commerce, these customers have already do few orders on our website before implementing the viva wallet plugin. 

We use the official plugin.

Thank you for your help

**Comment by WeedyTech** [comment]
I just tried it out and there is indeed an error 
<img width="1288" alt="Capture d’écran 2020-04-15 à 18 35 47" src="https://user-images.githubusercontent.com/61606686/79363358-18488480-7f48-11ea-854b-c027a824c2e0.png">

**Comment by WeedyTech** [comment]
<img width="1288" alt="Capture d’écran 2020-04-15 à 18 35 47" src="https://user-images.githubusercontent.com/61606686/79363402-226a8300-7f48-11ea-9c36-03590bc91f1c.png">

**Comment by WeedyTech** [comment]
I am sorry, it represent a potential lost of 50% of our customers...

<img width="1143" alt="Capture d’écran 2020-04-15 à 19 02 10" src="https://user-images.githubusercontent.com/61606686/79366009-bdb12780-7f4b-11ea-91a8-e74d9f57f71e.png">

**Comment by WeedyTech** [comment]
Issue solves by developers team !

**Comment by WeedyTech** [comment]
I open again because finally this issue isnt fixed. Someone can help?

**Comment by matthewrgourd** [comment]
Hi @WeedyTech, we have looked into this in detail and, although there may be a potential cookie handling problem in Chrome in the future, we can confirm that our plugin for WooCommerce functions correctly. Once a customer has been redirected from the payment screen, they're taken through to a 3DS popup which is handled by their issuer not by us. However, there is an updated plugin we've been working on in case you'd like to try. Please see link below. You'll obviously need to uninstall the previous one first. Thanks!

[vivawallet-for-woocommerce-3.6.0.zip](https://github.com/VivaPayments/API/files/4503169/vivawallet-for-woocommerce-3.6.0.zip)

**Comment by WeedyTech** [comment]
Thank you, I will install this updated plugin tonight and come to you

**Comment by matthewrgourd** [comment]
Closing issue as I assume it's now solved...

**Comment by lobtx** [comment]
That issue reminds me of https://github.com/VivaPayments/API/issues/1372 which has been closed saying plugin was tested and worked fine.
