### ISSUE TITLE
viva wallet is available to customers in  United Kingdom or not?

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1603]
hi ,
 1. viva wallet is available to customers in  United kingdom or not(bot simple checkout & redirect checkout)?
2. In Api doc , payment through viva wallet to is applicable for greece only.,  in england payment through viva option is available ?

**Comment by matthewrgourd** [comment]
Hi @chennurubharath if I understand your query correctly, the answer is 'yes' in both cases. Our checkouts and API are available in the UK as well as in Greece.
