### ISSUE TITLE
simple checkout

### ISSUE THREAD

**Issue by TimurMalyshev** [VivaPayments/API#1604]
Sorry for my questions again.
I am working in localhost environment.
I try to receive some response from https://demo.vivapayments.com/api/transactions.
I make a html form and  prepare method in backend.
But response is empty string.
What i am doing wrong?

(i read and try some code from issues: #1567,743,723,519)

Thanx, and sorry to trouble you. 
(b505703d-7a91-44d2-86d4-38d17b8d44ce)

**Comment by TimurMalyshev** [comment]
Firstly i am use code from this page: https://developer.vivawallet.com/online-checkouts/simple-checkout/

And then try to use this:

$MerchantId = xxxxxxxxxxxxxxx;
   $APIKey = xxxxxxxxxxxxxxxxxx;
					
   $session = curl_init('https://www.vivapayments.com/api/transactions');
   curl_setopt( $session, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
   curl_setopt($session, CURLOPT_POSTFIELDS, json_encode(array("PaymentToken" => $_POST['vivaWalletToken']))); //Replace $_POST['vivaWalletToken'] in case you have already set it as a variable
   curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
   curl_setopt($session, CURLOPT_USERPWD, htmlspecialchars_decode($MerchantId) . ':' . htmlspecialchars_decode($APIKey));
   $response = curl_exec($session);
   curl_close($session);



but response still empty

please help

**Comment by matthewrgourd** [comment]
Hi @TimurMalyshev I'm not immediately able to help but will check with a developer and get back to you. Speak soon!

**Comment by matthewrgourd** [comment]
Hi @TimurMalyshev, we don't recognise the code from our [Simple Checkout documentation page](https://developer.vivawallet.com/online-checkouts/simple-checkout/). Please try to use the examples there. Thanks!
