### ISSUE TITLE
BUG paiement par carte bancaire

### ISSUE THREAD

**Issue by Neyonis** [VivaPayments/API#1605]
Bonjour, depuis quelques jours voici les soucis rencontrés : 

- soit le processus de paiement fonctionne très bien jusqu’à entrer les coordonnées de la carte et la réception du code de confirmation 3d secure qu’ils rentrent mais ensuite plus rien, aucune confirmation de paiement ou de commande.
- soit sur certains clients qui paient sur mobile l’option paiement par carte n’apparait même pas, il y a seulement virement ou chèque.

On dit aux clients qui sont sur mobile de réessayer sur ordinateur et en général ça marche mais certains sont déjà sur leur ordinateur et dans ce cas en changeant de navigateur parfois ça refonctionne mais pour certains ça plante avec Chrome et fonctionne avec Firefox pour d’autres c’est l’inverse. Du coup on a beaucoup de paniers abandonnés à cause de ça.

Merci de nous aider

**Comment by git842732** [comment]
Même problème sur notre site web, je traduit pour les devs qui sont anglophones: 

" Since a couple of days we have those issues : 

- either the processus of payment work but after 3D secure no confirmation of the payment/order
- either for certain clients the option for paying don't even display, only transfer or check" 

We have the same kind of issue since today on our french website cbdqueen.fr

**Comment by Neyonis** [comment]
Merci

**Comment by WeedyTech** [comment]
Meme soucis chez Weedy.fr 

Majoritairement des paniers abandonnés quand les clients sont sur Chrome

**Comment by Neyonis** [comment]
Toujours rien ?

**Comment by matthewrgourd** [comment]
@Neyonis sorry to hear this. Generally once a customer has been successfully redirected to the 3DS popup from the payment page, this means the Viva Wallet platform is working correctly. However, I can certainly investigate further. What's the business name / web address? Are you using the Viva Wallet plugin for WooCommerce?

**Comment by Neyonis** [comment]
Hello we are on Shopify, the business name is Green Heaven the website is : https://greenheaven.fr/
We don't have to use WooCommerce on Shopify
Help us please

**Comment by matthewrgourd** [comment]
Hi @Neyonis all looks fine on your account. I can confirm that our Shopify plugin is working correctly. Any issues will be to do with customer cards / 3DS which is outside our control, I'm afraid. Thanks!
