### ISSUE TITLE
Ordine transato su vivawallet non va in lavorazione su woocommerce

### ISSUE THREAD

**Issue by DarioGalluzzo** [VivaPayments/API#1606]
Ciao a tutti, premetto che sono un neofita, ho un problema con le transazioni da viva wallet a woocommerce, mi spiego meglio, la transazione del cliente avviene regolarmente sul conto corrente di viva wallet, ma nel mio gestionale degli ordini di woocommerce l'ordine rimane in "attesa di pagamento" (in grigio) e non va in "lavorazione" (in verde), di conseguenza non parte la mail automatica di woocommerce dell'avvenuto pagamento.

Non so se sia una configurazione sbagliata del plug in di viva wallet

**Comment by DarioGalluzzo** [comment]
Ciao a tutti, premetto che sono una neofita, ho un problema con le transazioni da vivawallet a woocommerce, mi spiego meglio, la transazione del cliente avviene tramite conto corrente corrente vivawallet, ma nel mio gestionale degli ordini di woocommerce ordinato rimane in "attesa di pagamento" (in grigio) e non va in "lavorazione" (in verde), di conseguenza non parte la posta automatica di woocommerce dell'avvenuto pagamento.

Non così sia una configurazione sbagliata del plug in di vivawallet

**Comment by matthewrgourd** [comment]
I think this is the correct behaviour for failed transactions (you will always have some of these due to customers failing their 3DS or experiencing card issues). However, please provide your registered business name / web address so I can check for you?
