### ISSUE TITLE
URL address can't be verified during New Webhook creation and users see 404 page after selecting Vivawallet as payment method

### ISSUE THREAD

**Issue by breakofficial** [VivaPayments/API#1607]
Hi,
I already made all the steps required in your guide: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
In Step 3, during the creation of Webhook I enter the url following the guide, but if I save the progress a icon shows up eith these words: "Error! Urls address can't be verified etc"
My web site is already online and users can access but when they selected Viva Wallet as payment method an 404 page show up.
Please let me know how I can fix it.
Regards

**Comment by matthewrgourd** [comment]
Hi @breakofficial, unfortunately, one of our developers tested recently and discovered that the webhook functionality isn't currently working. I'm not yet sure when a fix will be applied. I'll update this ticket once I know more. Apologies for any inconvenience caused. Have a good day!

**Comment by breakofficial** [comment]
Hi Matthew,
thank for the time you dedicate.
At the moment we are in a bad position because we have started a web promo
and users can only buy with payment at delivery.
Waiting for updates and thanks again.
Giuseppe

Il giorno lun 20 apr 2020 alle ore 10:46 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment]
Hi @breakofficial , I've looked into this and unfortunately the webhooks functionality for our WooCommerce plugin isn't working correctly. We expect to have a fix but not immediately, I'm afraid. Regarding the 404 error, please may I have business name and web address of your e-commerce site?

**Comment by breakofficial** [comment]
Hi,
the e-commerce is located on https://breakofficial.it and our business name
is: BREAK ITALIA di Guglielmo Troian.
Please let me be notified

Il giorno mar 21 apr 2020 alle ore 16:16 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment]
Hi @breakofficial I've checked your settings and at the Viva Wallet everything looks fine. But I notice your website is showing as insecure even though it uses https. Please check that you have the right certificate as this may be causing a problem. Also, if you send through a screenshot of your WooCommerce payment module settings, that would be a help so I can troubleshoot. Obscure your Merchant ID / API key. Thanks!

**Comment by breakofficial** [comment]
Hi Mattew,
have you got any news? Please contact me, because we have some big problem
with our customers.
Giuseppe

Il giorno mar 21 apr 2020 alle ore 16:16 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by breakofficial** [comment]
Hi,
these are the screenshots you ask for, I'll try to resolve the problem with
unsecure site.


Il giorno mer 22 apr 2020 alle ore 16:01 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment]
Hi @breakofficial unfortunately screenshots didn't come through. If you could try again, or email to my email address mgourd@vivawallet.com? Thanks!

**Comment by breakofficial** [comment]
Hi,
I've already send you an email with the screenshots mgourd@vivawallet.com.


Il giorno mer 22 apr 2020 alle ore 16:37 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment]
Hi @breakofficial thanks for emailing the screenshots. From what I can see, some of the field names indicate that you're not using our official plugin. Please uninstall and download / install the following ZIP folder instead:

https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip

**Comment by breakofficial** [comment]
Hi,
now seems to work thank you!!! last question: how can I change the
languages of the page where users have to insert their credit
card credentials?

Il giorno mer 22 apr 2020 alle ore 17:24 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by breakofficial** [comment]
don't pay attention to the previous mail, I see users can change their self.
Thank you again
Giuseppe

Il giorno mer 22 apr 2020 alle ore 18:09 Giuseppe Troian <
giuse0697@gmail.com> ha scritto:

**Comment by matthewrgourd** [comment]
Hi @breakofficial, you can make the changes to the WooCommerce plugin yourself by editing the code (wc-vivawallet.php). Specifically this section:

ORIGINAL

$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300';

NEW

$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang=it&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300';

Hope this helps!

**Comment by matthewrgourd** [comment]
Hi @breakofficial, regarding the webhooks functionality, apparently a fix should be available in the next week or so along with a general overhaul of our plugin. Please keep checking our new Wordpress plugin page for the latest info: https://en-gb.wordpress.org/plugins/vivawallet-woocommerce-gateway  Thanks!
