### ISSUE TITLE
Payment error vivawallet

### ISSUE THREAD

**Issue by ecommerce25** [VivaPayments/API#1609]
Hi everyone,
This 10 days, we got a recurent problem of payment on two differents e-shop.
We don't understand why....
Any idea ? 
The strange thing is the Vivawallet support can see only one 'error'...
Thanks for your help

![2020-04-18 15_26_50-Window](https://user-images.githubusercontent.com/63912267/79639003-16b9cf00-8189-11ea-923c-8ba19c7d22ee.png)

![2020-04-18 15_24_24-Window](https://user-images.githubusercontent.com/63912267/79639020-2df8bc80-8189-11ea-9bcb-f7f1b808ab15.png)

**Comment by matthewrgourd** [comment]
Hi @ecommerce25 can you let me know the URLs of your two e-commerce sites and the registered business name. Ideally VAT / registration number, too! I can then investigate.

**Comment by ecommerce25** [comment]
hi,
Thanks for your quick answer.
Find bellow the URLs concerned
https://lacasadepapel-store.com/ <https://lacasadepapel-store.com/index.php>
http://lelabducbd.fr/
Registration Number : *879112712 *
Cordialement,
Le service client


Le lun. 20 avr. 2020 à 12:49, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @ecommerce25, I'm not sure if there's an issue. I can see payments coming through on your Viva Wallet transactions screen. If you have a specific account query, please contact one of our customer service numbers below:

<table><tr><th>Country</th><th>Phone number</th>
  <tr><td>Belgium</td><td>(+32) 2342 0790</td></tr>
    <tr><td>Cyprus</td><td>(+357) 2403 0211</td></tr>
    <tr><td>France</td><td>(+33) 1876 50765</td></tr>
    <tr><td>Greece</td><td>(+30) 21 1760 4000</td></tr>
    <tr><td>Netherland</td><td>(+31) 2089 05503</td></tr>
    <tr><td>Romania</td><td>(+40) 3122 96150</td></tr>
    <tr><td>UK</td><td>(+44) 20 3734 7770</td></tr>
    <tr><td>Portugal</td><td>(+351) 3 0050 9059</td></tr>
</table>

Thanks!
