### ISSUE TITLE
Τα webhooks δεν λειτουργούν!

### ISSUE THREAD

**Issue by deliverymanager** [VivaPayments/API#161]
Για κάποιο λόγο από σήμερα το μεσημέρι δεν λειτουργούν τα webhooks!

**Comment by defilerc** [comment]
Καλησπέρα @deliverymanager ,

Θα θέλαμε να σας ενημερώσουμε πως τη Δευτέρα 29 Αυγούστου και για το διάστημα 18:30-21:00 υπήρξαν κάποιες καθυστερήσεις στην παράδοση των webhooks, τα οποία στη συνέχεια παραδόθηκαν όλα κανονικά.

Ζητούμε συγνώμη για την οποιαδήποτε ταλαιπωρία.

Ευχαριστούμε πολύ για την επικοινωνία
