### ISSUE TITLE
viva wallet charges for card payment charges details

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1612]
hi , pls let me know,

1)viva wallet charges for card payment , it includes in the payment amount we raised to customer or after successful payment u deduct that charge before transferring to our bank acccount.

2) any vat charges  is there for viva wallet

Regards,
bharath

**Comment by matthewrgourd** [comment]
@chennurubharath The answer is "after successful payment we deduct that charge before transferring to your bank account." However, if you pay for your business expenses using the Viva Wallet card attached to your bank account, you won't pay any charges.
