### ISSUE TITLE
viva wallet charges

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1615]
Hi,

1) viva wallet charges for card payment , it includes in the payment amount we raised to the customer or after successful payment u deduct that charge before transferring to our bank account
2) Does it include any VAT charges??

Thanks,
itcs

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs as far as I'm aware, no VAT is charged at any point within our platform: https://www.vivawallet.com/wp-content/uploads/2018/09/VIVA_WALLET_UK_PRICING.new-pdf.pdf Best regards
