### ISSUE TITLE
Not redirecting back to site after successful payment

### ISSUE THREAD

**Issue by jannis-t69** [VivaPayments/API#1616]
Hello,
we have implemented the official woocommerce plugin as described in the developers manual https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ on our site with wordpress.
The issue is that after a successful payment the customer doesn't get redirected to the "Thank you" page of the site, but remains on the Vivapayments Transaction details page.

![image](https://user-images.githubusercontent.com/55201611/79830472-bf447a80-83a5-11ea-876c-194f3160cf14.png)

On our staging site we've tested the same configuration with the Vivapayments demo-site with exact the same results. The staging site configuration:

![image](https://user-images.githubusercontent.com/55201611/79830626-1b0f0380-83a6-11ea-92df-4925cb8011cf.png)
![image](https://user-images.githubusercontent.com/55201611/79830708-48f44800-83a6-11ea-8d36-688af0aba3f3.png)

![image](https://user-images.githubusercontent.com/55201611/79830899-ab4d4880-83a6-11ea-8dfd-6d3547e6753b.png)
![image](https://user-images.githubusercontent.com/55201611/79831030-ea7b9980-83a6-11ea-9194-c29a54aa112f.png)

please advise
thank you

**Comment by matthewrgourd** [comment]
@jannis-t69 I've had a look and I think it's because you're using the demo environment which doesn't include the last step of the process (3DS). It should work fine on live. Thanks!

**Comment by jannis-t69** [comment]
Hello,

i just replicated the production enviroment [https://slalomshop.gr](https://slalomshop.gr) so i can troubleshoot the issue. We have on the live shop the same issue as described above

**Comment by jannis-t69** [comment]
On the live site we have following settings
![image](https://user-images.githubusercontent.com/55201611/79858429-b1a3ea80-83cf-11ea-8a28-78c5b007bce4.png)
![image](https://user-images.githubusercontent.com/55201611/79858505-d1d3a980-83cf-11ea-9e97-1bbe08cf1150.png)
![image](https://user-images.githubusercontent.com/55201611/79858667-0e9fa080-83d0-11ea-9077-d130143cff63.png)
![image](https://user-images.githubusercontent.com/55201611/79858694-195a3580-83d0-11ea-81b2-b4103aa76569.png)

**Comment by matthewrgourd** [comment]
Hi @jannis-t69 in your WooCommerce payment module settings you just need to add the appropriate payment source code from your Viva Wallet account ('1573' or '2526', both look identical in terms of settings).

**Comment by jannis-t69** [comment]
Hi & thank you very much, it works now on the staging site. We'll test it on the production site.
