### ISSUE TITLE
Card Tokenization API

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1618]
Hi,

    Can we use this API for card payment, Using that customer's card details gets saved in Viva Wallet. Next time onwards just they need to enter a mobile number and password to pay,it acts like PayPal.

Thanks,
itcs

**Comment by matthewrgourd** [comment]
Depends how you implement. Suggest to read the [documentation](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/) in detail and see if it suits your requirements.
