### ISSUE TITLE
Viva Wallet Pay Features

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1619]
Hi Sir/Madam,

We got to know Simple Checkout API having Pay using Viva Wallet option and available for Greece only.
Using that customers can create their own viva wallet account (sign up) and enter their card details,
it gets saved in Viva Wallet. Next time onwards just they need to enter a mobile number and password to pay,
it acts like PayPal.

Will this service be available for the UK also.  If Not possible to provide means is there any equivalent other API is there could you please let us know??

This will save customers from type the card details each time when they need to pay us.

Thanks,
itcs

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs no plans for any changes at present. Apologies for any inconvenience caused. In any non-ideal scenario, we're encouraging people to use our [Native Checkout](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/), instead, as this is our most up-to-date checkout / API. Hope this helps!
