### ISSUE TITLE
Τύπος συναλλαγής Δέσμευση (PreΑuth) με δόσεις

### ISSUE THREAD

**Issue by speed-chase** [VivaPayments/API#162]
Καλημέρα,

Σε demo πληρωμές με τη μέθοδο redirect και τύπο συναλλαγής Δέσμευση (PreΑuth), ενώ το σύστημα υποστηρίζει την εμφάνιση επιλογής δόσεων στη σελίδα πληρωμής, όταν επιλέγονται δόσεις, δεν καταχωρούνται στην συναλλαγή ακόμα και όταν πραγματοποιείται η δέσμευση. Ενώ με μέθοδο Χρέωση κάρτας (ChargeCard) καταχωρούνται κανονικά οι δόσεις, υπάρχει κάποια εξήγηση γι αυτό;

**Comment by dpnevmatikos** [comment]
Καλημέρα @speed-chase ,
Σε τύπο συναλλαγής PreAuth δεν επιτρέπεται η καταχώρηση δόσεων.
Όπως σωστά παρατηρήσατε, επιτρέπεται μόνο στην χρέωση κάρτας.

Ευχαριστούμε.
