### ISSUE TITLE
IS it possible to get the "data-vp-merchantref" in output JSON of simple checkout?

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1620]
Hi,

IS it possible to get the "data-vp-merchantref"  in output JSON of simple checkout?
 It will help us to track the customer.

here : *{"Emv":null,"Amount":6.00,"StatusId":"F","CurrencyCode":"826","TransactionId":"eaf3b4c3-2f5d-4b1b-9845-7b2a2947bb34","ReferenceNumber":134297,"AuthorizationId":"134297","RetrievalReferenceNumber":"011206134297","ThreeDSecureStatusId":1,"ErrorCode":0,"ErrorText":null,"TimeStamp":"2020-04-21T09:02:06.6805359+03:00","CorrelationId":null,"EventId":0,"Success":true}

Is it possible to send along with this , it help us to find the customer.

Thanks,
itcs

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, looks like you're requesting a modification to our Simple Checkout offering. I'll raise with our development team and get back to you once I have a response.

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, yes, that's fine as it's a documented parameter: https://developer.vivawallet.com/online-checkouts/simple-checkout/#configuration-options
