### ISSUE TITLE
What is the maximum amount we  can collect from customer in one shot?

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1621]
hi, pls let me know what is What is the maximum amount we  can collect from customer in one  shot.
i tried data-vp-amount="5000000000000000000"   payment is not successfull

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @chennurubharath, this is dependent on the merchant's account status which depends on their transaction history. A common maximum for a single transaction is £6,0000. I don't know why you would want to test with such a high value. Hope this helps! I'm closing this ticket now.
