### ISSUE TITLE
not able to load live js

### ISSUE THREAD

**Issue by navdeepsinghapporio** [VivaPayments/API#1623]
I am integrating VivaWallet and facing some issue as follow
1. In Demo, I am not able to done success payment
2. In Live, I am not to load js File Getting some error while I am loading the page
screenshot attached please check.
please provide me any solution ASAP.
Thanks

![Screenshot from 2020-04-17 11-26-45](https://user-images.githubusercontent.com/44015258/80077602-5a3a8180-856b-11ea-9c65-02308954a54d.png)

**Comment by matthewrgourd** [comment]
HI @navdeepsinghapporio, are you attempting to integrate using our [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/) solution? If you have any further problems after checking the below, please try our [Native Checkout](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) instead.

1. Regarding the demo site, there is currently no way to mimic a successful payment, unfortunately. Ultimately you will have to test on live.
2. On live, the correct URL for the JS is https://www.vivapayments.com/web/checkout/js.

Hope this helps!

**Comment by navdeepsinghapporio** [comment]
Live Url of JS is working now but after that, I am getting this response 

using this url for payment 
https://www.vivapayments.com/api/transactions

Response
{
"Emv": null,
"Amount": null,
"StatusId": "E",
"CurrencyCode": null,
"TransactionId": null,
"ReferenceNumber": null,
"AuthorizationId": null,
"RetrievalReferenceNumber": null,
"ThreeDSecureStatusId": null,
"ErrorCode": 403,
"ErrorText": "The specified api action is disabled for the merchant 50c2cdbf-0c37-4b76-97c4-851e18a2bfb3, please consult the documentation",
"TimeStamp": "2020-04-27T12:30:07.8949452+03:00",
"CorrelationId": null,
"EventId": 0,
"Success": false
}

**Comment by matthewrgourd** [comment]
Hi @navdeepsinghapporio, I've changed one of your settings. Can you try now? Thanks!

**Comment by navdeepsinghapporio** [comment]
yes now it is working 
I am able to do success payment but I have one question also 
is there any provision to save cards?

**Comment by matthewrgourd** [comment]
Not with Simple Checkout out of the box. However, we do have a card tokenization API. See https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/

**Comment by navdeepsinghapporio** [comment]
we can use that token for multiple payments or it is for one time payment only ?

**Comment by navdeepsinghapporio** [comment]
what should I need to pass in header Authorization in these APIs?

**Comment by matthewrgourd** [comment]
Hi @navdeepsinghapporio please see https://developer.vivawallet.com/authentication/#oauth-2-token-generation Thanks

**Comment by navdeepsinghapporio** [comment]
as I have check all the API and getting the flow but I am not able to **Generate a pair of credentials**  
on vivawallet dashboard as mention in API
nothing happens when I click on **Generate a pair of credentials**


![Screenshot from 2020-05-06 13-47-18](https://user-images.githubusercontent.com/44015258/81153505-9e347a00-8fa0-11ea-9f48-bb310bb512a4.png)
