### ISSUE TITLE
inserimento vivawallet su jimdo

### ISSUE THREAD

**Issue by Whitelephantweed** [VivaPayments/API#1625]
salve vorrei sapere come inserire vivawallet sul mio sito creato con la piattaforma jimdo

**Comment by matthewrgourd** [comment]
Hi @Whitelephantweed unfortunately we don't have a plugin for Jimdo. However, if you come from a development background you can create your own using our [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) and [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/) documentation as a reference. Hope this helps!
