### ISSUE TITLE
Card Tokenization API, step(2) response  problem

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1626]
hi,  
 I am trying card Tokenization API, i was tried following things 
Step 1: Generate one-time charge token using card details (got charge token)
 at Step (2): Generate card token using the charge token 
  i am geting the respose as following

{"status":400,"message":"PaymentsCardHolderAuthenticationInvalidStatus","eventId":"2061"}

**Comment by matthewrgourd** [comment]
Hi @chennurubharath this means a 3DS failure. Unfortunately you can't test on demo, you have to use production otherwise you'll keep getting this error.
