### ISSUE TITLE
viva payments

### ISSUE THREAD

**Issue by istoselida** [VivaPayments/API#1627]
Hello,
My website is https://sapon.gr/
I installed the plugin viva payments with version 3.6.0 and I had a problem with the attachment.
Please for your help. Give it a try to buy something with viva option to see the problem.

![Annotation 2020-04-21 112904](https://user-images.githubusercontent.com/48787978/80203875-8966f680-8630-11ea-8156-49c7d979bacf.jpg)

**Comment by matthewrgourd** [comment]
Hi @istoselida, I've checked your website and there's a fundamental issue with the settings. It's nothing to do with our plugin. Please contact [Wordpress](https://wordpress.org/support/) or [WooCommerce support](https://woocommerce.com/).
