### ISSUE TITLE
Unable to call the production live env

### ISSUE THREAD

**Issue by Kakktuss** [VivaPayments/API#1628]
Hi, i'm sorry to borow you today but i have a problem.

I've created an integration for the ecwid plateform. My integration works great in the demo env but when i try to put my app in production, and change the env to https://www.vivapayments.com/api, i get an 404 error.

To make REST calls, i use RestSharp (such as my app is wrote in c#), everything works fine in the dev mode but not in live. So, i tried to make this call using postman but i get exactly the error, a 404 error.

Does i have the good live url or i made a mistake ?

Thank you

**Comment by matthewrgourd** [comment]
Hi @Kakktuss, could you show me the call you're attempting to make on demo and I'll see what the base url should be?

**Comment by matthewrgourd** [comment]
Closing as no reply...
