### ISSUE TITLE
merchant wallet money will possible to  tansfer bank account automatically?

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1629]
hi,
  in merchant account  "deposit money" option we can transer money to bank, is there any option is available to  transfer  money  to bank automaticaly, without manually efforts.

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @chennurubharath unfortunately we don't currently offer this as an option, it's manual transfer only. Best regards.
