### ISSUE TITLE
Magento 2.3 Payment method is not available 

### ISSUE THREAD

**Issue by jimkar** [VivaPayments/API#1630]
On magento 2.3 we have enable the extension but the payment method is not available on front.

**Comment by matthewrgourd** [comment]
Hi @jimkar, sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- Magento payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Hi @jimkar are you using Magento 2.3.5 as we have an updated plugin for this? (see below)

[magento23_vivawallet.zip](https://github.com/VivaPayments/API/files/4573428/magento23_vivawallet.zip)

**Comment by matthewrgourd** [comment]
Hi @jimkar is this issue solved now? If so, please close using the button below...Thanks!
