### ISSUE TITLE
Magento 2 - payment failure issue on certian cards

### ISSUE THREAD

**Issue by nathmeister** [VivaPayments/API#1631]
Hi, 
I have successfully integrated viva wallet with my magento 2.2.9 store and can process transactions fine using most of my debit/credit cards I use to test, but 2 of my cards are with a smaller bank called Metro Bank and they keep saying payment failed and not even registering on the vivawallet transactions page. 

I noticed that my other cards that work fine have a popup for a security check (I think the pop up is the verified by visa and mastercard secure one) when on the vivawallet checkout page where my Metro Bank cards don't get that pop up. 

On other sites when I pay with my Metro Bank card I usually get this security pop-up which just disappears after a few seconds, I have never had this issue before with my Metro Bank cards.

My Metro Bank cards are both mastercard debit cards (one personal card, one business card)

Is this a known issue? Is it Metro Bank not doing their security checks properly? Are there other bank that are likely to do this? Is there a way around it?

Thanks
Nathan

![viva-error-1](https://user-images.githubusercontent.com/64208749/80310355-0c738280-87d2-11ea-86b7-cc2da023ed79.png)

**Comment by matthewrgourd** [comment]
Hi @nathmeister, in order to be in line with the latest requirements from the PSD2 directive, our payment solutions work only with 3DS enabled cards. Please check with your card issuer if you are unsure whether your Metro Bank card is fully compliant. Thanks!
