### ISSUE TITLE
PCI DSS  full card data API 

### ISSUE THREAD

**Issue by christos-kapa** [VivaPayments/API#1632]
We have PCI DSS through a company ( WSA ) 
We want to ask if you have API for full card data in order to make the integration. We want to make our own paywall ( mainly for better UI/UX in mobile ) and then VIva to make the transaction. 

**Is this possible?**

**Comment by matthewrgourd** [comment]
Hi @christos-kapa, let me find out for you. In the meantime, can I have a bit more info about your business? Maybe website address to start off with?

**Comment by christos-kapa** [comment]
> Hi @christos-kapa, let me find out for you. In the meantime, can I have a bit more info about your business? Maybe website address to start off with?

Hello, 

We have already viva. We have already viva payments checkout. We are bazaraki.com the biggest marketplace in Cyprus. 


Regards, 
Christos

**Comment by christos-kapa** [comment]
Hi Matthew, 

We tried many times to speak to the technical support by phone or email and said this is not possible. So the only way is asking here Github. 

Regards, 
Christos

**Comment by matthewrgourd** [comment]
@christos-kapa, that's fine, this is technical support. I will pass your details on to our development team and get back to you when I have a reply. Thanks!

**Comment by matthewrgourd** [comment]
Hi @christos-kapa we've had a discussion about this and think the best solution is going to be our Card Tokenization API. Please check our [documentation](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/) and let us know how you get on.
