### ISSUE TITLE
The specified api action is disabled for the merchant

### ISSUE THREAD

**Issue by bfeio** [VivaPayments/API#1634]
hi, we are testing the payment api but getting the following error:
{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"The specified api action is disabled for the merchant xxxx8247-9330-4xxx-96e5-4b8014caxxx, please consult the documentation","TimeStamp":"2020-04-27T14:24:48.8619106+03:00","CorrelationId":null,"EventId":0,"Success":false}
Can you help me?
Regards.

**Comment by matthewrgourd** [comment]
Hi @bfeio, I've enabled the API for you. Can you try again? Thanks!

**Comment by cgtheodorou** [comment]
Hi I'm also facing the same issue, can you please enable it for my account too?

last 12 chars of merchant account
5fb834c1e221

**Comment by matthewrgourd** [comment]
Hi @cgtheodorou, no problem, can I have your website address and trading name, too? Thanks!

**Comment by bfeio** [comment]
> Hi @bfeio, I've enabled the API for you. Can you try again? Thanks!

It's solved thank you

**Comment by cgtheodorou** [comment]
> Hi @cgtheodorou, no problem, can I have your website address and trading name, too? Thanks!

Do you have an email address I could send it to you?

**Comment by matthewrgourd** [comment]
@cgtheodorou mgourd@vivawallet.com but I'm closing this issue now which was raised by @bfeio originally who says his issue is now solved. Feel free to email me though.
