### ISSUE TITLE
URGENT PROBLEM WITH VIVA PAYMENTS

### ISSUE THREAD

**Issue by NikVlachos** [VivaPayments/API#1636]
My website is https://sapon.gr/
I installed the plugin viva payments with version 3.6.0 and I had a problem with the attachment.
Please for your help. Give it a try to buy something with viva option to see the problem.

![pic4](https://user-images.githubusercontent.com/64415163/80372442-342f1d00-889c-11ea-98d5-dc3c2e21434f.jpg)
![pic5](https://user-images.githubusercontent.com/64415163/80372446-372a0d80-889c-11ea-90f3-75def77cad03.jpg)

**Comment by matthewrgourd** [comment]
Hi @NikVlachos, sorry to hear this. Can you first of all try removing the forward-slash from the Success / Failure URLs in your payment source settings?

![Screenshot_2020-04-27_at_14_53_06](https://user-images.githubusercontent.com/44943019/80380186-1e6b2900-8897-11ea-8a89-3e1392568661.png)

**Comment by NikVlachos** [comment]
Nothing has changed

**Comment by matthewrgourd** [comment]
Hi @NikVlachos, ok, so I can investigate further, please send through a screenshot of the payment module settings in WooCommerce with your Merchant ID / API key blurred out. The requested web page looks like this:

![WooCommercePaymentsTab](https://user-images.githubusercontent.com/44943019/80397270-ca1f7380-88ad-11ea-958c-7a7306378185.png)

Thanks!

**Comment by NikVlachos** [comment]
![pic18](https://user-images.githubusercontent.com/64415163/80397649-1fb04c00-88bf-11ea-8e6f-9c2836498916.jpg)
![pic19](https://user-images.githubusercontent.com/64415163/80397662-25a62d00-88bf-11ea-8edf-128b70fbddde.jpg)

**Comment by matthewrgourd** [comment]
Hi @NikVlachos, I've checked all your settings and the Viva Wallet plugin is set up correctly. If your Merchant ID ending in (8fa1) and API key (ending in kw) have been entered correctly, the problem must be related to the general setup of your Wordpress / WooCommerce website.

**Comment by NikVlachos** [comment]
Hello matthewrgourd and thank you for your time to solve my problem.
I contacted the creator of the issue and mentioned it but he told me that there is no problem on his part and to look at the plugin.

**Comment by matthewrgourd** [comment]
Hi @NikVlachos there's nothing more I can do I'm afraid. Your settings for our plugin are correct. as long as you have double-checked the Merchant ID / API key have been entered accurately. The error message given in the screenshot you provided is "There has been a critical error on your website". This suggests a fundamental problem at the Wordpress / WooCommerce end. This is not an error message from our plugin. Beyond that, I can't help, I'm afraid.

**Comment by NikVlachos** [comment]
the Merchant ID / API key is wright.
OK thank you very much

**Comment by matthewrgourd** [comment]
Hi @NikVlachos can you try our updated plugin, 3.6.1 below:

[vivawallet-woocommerce-gateway-3.6.1.zip](https://github.com/VivaPayments/API/files/4552629/vivawallet-woocommerce-gateway-3.6.1.zip)

If that still doesn't work, revert back to 3.5.7, below, and we'll check the plugin code of the updated plugins. Let me know how you get on!

[vivawallet-for-woocommerce.zip](https://github.com/VivaPayments/API/files/4552632/vivawallet-for-woocommerce.zip)

**Comment by NikVlachos** [comment]
Μας ειχατε απαντησει οτι δεν ηταν δικο σας προβλημα και τωρα μας στελνεται
αυτη την απαντηση.
Μας δουλευεται ?Εγω πληρωσα προγραμματιστη και αγορασα plugin.
Ειστε απαρεδεκτοι και ασχετοι μαλλον.


Στις Τετ, 29 Απρ 2020, 18:33 ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @NikVlachos, sorry, but I'm trying to help you. We're having a few problems with our updated plugin. Please remove 3.6.0 and reinstall 3.5.7 from here: [vivawallet-for-woocommerce.zip](vivawallet-for-woocommerce.zip) Let me know how you get on.

**Comment by matthewrgourd** [comment]
Hi @NikVlachos is this issue solved now? If so, please close using the button below. Thanks!
