### ISSUE TITLE
how can i create a payment page directly with viva wallet without redirection on shopify ?

### ISSUE THREAD

**Issue by elmehdies** [VivaPayments/API#1637]
how can i create a payment page directly with viva wallet without redirection on shopify
?

**Comment by matthewrgourd** [comment]
Hi @elmehdies I'm afraid we're only offering the [redirect plugin](https://developer.vivawallet.com/e-commerce-plugins/shopify/) at present. We may have a native integration with Shopify in the future, but I'm not sure when.
