### ISSUE TITLE
Shopify - Payment failure

### ISSUE THREAD

**Issue by Mamakana** [VivaPayments/API#1638]
Hello, 

I am writing to you because some clients have a problem with payment process. 
They actually received by phone a security code from the bank, they write it on the screen but it is keep loading and does not work . 
I have attached a payment failure of a client which tried 5 times to make a payment. 

Kind regards and have a nice day

**Comment by matthewrgourd** [comment]
Hi @Mamakana , sorry to hear this. I've checked and the error code we received relating to this transaction (and the other failed one) is "57" meaning "The card issuer has declined the transaction as the credit card cannot be used for this type of transaction." So no problem at our end. The customer would need to check with their bank / card issuer to find out if their card is 3DS enabled or why they are prevented from using it for e-commerce transactions. Hope this helps!

**Comment by matthewrgourd** [comment]
Hi @Mamakana, by the way, thanks very much for the screenshot but I need to remove it now as it contains confidential information about your account.
