### ISSUE TITLE
Problema integrazione con web site x5

### ISSUE THREAD

**Issue by LoveCanapa** [VivaPayments/API#1639]
buongiorno , 

non riesco ad integrare il pagamento con website x5. 
il programma per la creazione del sito mi da solo la possibilità di aggiungere un bottone di pagamento con codice HTML ad esempio come lavora Paypal . 

avete un codice HTML finito che reinderizza il pagamento sul vostro sito? 

grazie 
Andrea 
3275869887

**Comment by matthewrgourd** [comment]
Hi Andrea, so I know which of our integration solutions you're referring to, can you let me know which page(s) you're looking at on our [developer portal](https://developer.vivawallet.com/)? Thanks!

**Comment by LoveCanapa** [comment]
secondo me quello più efficace per il mio sito è https://developer.vivawallet.com/online-checkouts/redirect-checkout/

**Comment by LoveCanapa** [comment]
Si , puoi aiutarmi ad inserirlo nel mio sistema di pagamento ?
Mi da opportunità di inserire un codice html e basta

**Comment by matthewrgourd** [comment]
Hi @LoveCanapa I'm afraid the only other documentation we have is this: https://developer.vivawallet.com/api-reference-guide/payment-api/. Our Redirect Checkout is based around this. What platform are your websites on? Are you an e-commerce solution like Shopify or WooCommerce or are they your own design? Please provide details of your website including URL if possible.

**Comment by LoveCanapa** [comment]
Il mio e commerce è creato con web site x5 incomesia https://www.lovecanapa.it .

**Comment by matthewrgourd** [comment]
Hi @LoveCanapa you can try adding a button for payment using our [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/) solution, which has some sample HTML code (see Step 1). Beyond that, unfortunately I cannot help you with the use of custom code within WebSite X5. Best regards, Matt

**Comment by LoveCanapa** [comment]
ho provuto ad aggiungere il codice HTML , come nel passaggio 1 , ma poi la risposta del passaggio 2 e il passaggio 3 dove devo inserirli?

**Comment by matthewrgourd** [comment]
I'm sorry, I don't know anything about the WebSite X5 platform so won't be able to help any further. Thanks!
