### ISSUE TITLE
bad request σε demo

### ISSUE THREAD

**Issue by nsama** [VivaPayments/API#164]
καλησπέρα έχω κάνει ενα demo λογαριασμό και όταν πάω να κάνει ανακατεύθυνση στο viva (http://demo.vivapayments.com/web/checkout?ref=4.0495967365726E+15) μου γράφει bad request

**Comment by krakenrules** [comment]
Καλησπέρα,

Το πρόβλημα που έχετε προκύπτει από την μορφή του ref parameter. Θα πρεπει να οριστεί σαν αριθμός χωρις scientific notation, πχ ref=12345.
Για περισσότερα σχετικά με τις παραμέτρους της checkout δείτε https://github.com/VivaPayments/API/wiki/Redirect-Checkout

Ευχαριστούμε

**Comment by krakenrules** [comment]
Καλησπέρα, 
Για PHP μπορείτε να δείτε και μια υλοποίηση στο issues 155.
https://github.com/VivaPayments/API/issues/155

Ευχαριστούμε

**Comment by nsama** [comment]
ok thanks

**Comment by condor0s** [comment]
Αυτό h αλλαγή μπορεί να βοηθήσει:

// $transId = $resultObj->OrderCode; σε 
$transId = number_format($resultObj->OrderCode,0,'','');

Δείτε και εδώ: http://stackoverflow.com/questions/4964059/convert-exponential-to-a-whole-number-in-php
