### ISSUE TITLE
URGENT : problem with expiration dates

### ISSUE THREAD

**Issue by WeedyTech** [VivaPayments/API#1640]
Hello,

Part of our customers can no longer place an order because when they select the expiration date for the month of October, what appears in the selection is "ten" instead of the number "10", a message of error then prevents to validate the payment ...

I am enclosing a photo for proof of this urgent error. Thank you in advance !

![WhatsApp Image 2020-04-28 at 16 34 58](https://user-images.githubusercontent.com/61606686/80503364-0a482a00-8972-11ea-9e0c-c6f238fc0193.jpeg)

**Comment by matthewrgourd** [comment]
@WeedyTech there's no quick fix. I will need to raise with a developer and get back to you tomorrow. Is this related to the amendment you made recently to change EN into FR in our WooCommerce plugin? Maybe it's that hack that's causing the issue. Please remind me of your website URL / trading name.

**Comment by WeedyTech** [comment]
@matthewrgourd Here is the url: https://weedy.fr

No it is not related to our modification, this problem has been presented to us by some customers since the plugin update.

What is strange is that it only concerns a few customers and who do not necessarily have the same configurations (device, browser ...)

**Comment by matthewrgourd** [comment]
@WeedyTech I don't recognise that screenshot as belonging to our payment plugin. I just tested on your website and there is no issue. Best regards, Matt

![Screenshot_2020-04-29_at_09_23_51](https://user-images.githubusercontent.com/44943019/80575450-85a1ee00-89fb-11ea-84cc-131ec0b43d63.png)
