### ISSUE TITLE
[Woocommerce] 3DS forms fails at loading (duplicate of https://github.com/VivaPayments/API/issues/1372)

### ISSUE THREAD

**Issue by lobtx** [VivaPayments/API#1642]
Hi,

Please refer to https://github.com/VivaPayments/API/issues/1372

Here after a screenshot of the issue:
![image](https://user-images.githubusercontent.com/38595388/80587120-4d5bd900-8a16-11ea-8b7b-bd5e3afc90d0.png)

I used my own credit card, which is fully compatible with 3DS.
Version of the plugin: 3.5.7

Thanks

**Comment by matthewrgourd** [comment]
Fixed in 3.6.1. Please install from https://wordpress.org/plugins/vivawallet-woocommerce-gateway/

**Comment by lobtx** [comment]
Thank you, sorry for the mistake.
