### ISSUE TITLE
Default language shopify

### ISSUE THREAD

**Issue by elmehdies** [VivaPayments/API#1644]
Our client is asking how to make the default language in the checkout payment page by default French instead of English: I didn t find any solution

**Comment by matthewrgourd** [comment]
I'm told this is based on the Shopify store country you configure in the Shopify settings.

**Comment by elmehdies** [comment]
hi 
<img width="1440" alt="Capture d’écran 2020-04-30 à 16 17 31" src="https://user-images.githubusercontent.com/28805269/80721617-b880da80-8afe-11ea-9ebe-b41a4dc48b19.png">
<img width="1440" alt="Capture d’écran 2020-04-30 à 16 17 09" src="https://user-images.githubusercontent.com/28805269/80721642-c2a2d900-8afe-11ea-829c-46fa3bcc7deb.png">


yes is. what I did but isn't working like the screen shot

**Comment by matthewrgourd** [comment]
@elmehdies should be working if your Shop language is French. Can I have your trading name / company registration so I can investigate further?

**Comment by elmehdies** [comment]
@matthewrgourd  hi my trade name is dress-on my Registration Number is 832382774 and my webside is https://la-fabrique-a-deal.com/ thanks for your help ! :)

**Comment by elmehdies** [comment]
@matthewrgourd hi what did you find ?

**Comment by matthewrgourd** [comment]
Hi @elmehdies that evverything is set up correctly. As far as I'm aware, our plugin should follow your store language / country settings in the Shopify settings. If this isn't happening, I need to raise with the plugin developer.

**Comment by elmehdies** [comment]
ok so it will take how long time ?

**Comment by matthewrgourd** [comment]
@elmehdies so you can confirm that it isn't working with your Shopify settings correctly configured?

**Comment by elmehdies** [comment]
yes I sent you the screen shot of the configuration

**Comment by matthewrgourd** [comment]
Ok, I will need to raise with a developer. I'll get back to you in the next day or two. Thanks!

**Comment by elmehdies** [comment]
Ok, thank s having a good day best regard

**Comment by matthewrgourd** [comment]
Hi @elmehdies sorry for the delay. I'm told that French will be supported soon. For the moment, we only handle GR/EN languages as default and the user has to manually change the language on checkout.
