### ISSUE TITLE
Affiliate merchants

### ISSUE THREAD

**Issue by lovetoast** [VivaPayments/API#1645]
I am a viva wallet affiliate, will all my merchants need to ask on here to have simple checkout enabled? IS there a quicker and more private way?

**Comment by matthewrgourd** [comment]
Hi @lovetoast yes, sure, please email myself on mgourd@vivawallet.com with all the relevant Merchant IDs and trading names.

**Comment by lovetoast** [comment]
Thanks, emailed.

On the simple checkout itself, is the page posted to the action form only if successful? For example, if it's a decline, I presume it stays on the payment iframe so the user can enter payment details again?

**Comment by lovetoast** [comment]
Any news on this? I would have thought that this was quite a quick process?

**Comment by matthewrgourd** [comment]
Hi @lovetoast sorry for the delayed reply. All payments go through a 3DS step after the customer has entered their card details and gone ahead with the payment. This is in the form of a popup which is provided by the card issuer not by ourselves. If there's a card failure, the customer has to speak to their issuer to determine why their card has been rejected, then start the process again once they have funds (or by using a different card).

**Comment by lovetoast** [comment]
Thanks, have you been able to enable my account?

**Comment by matthewrgourd** [comment]
Hi @lovetoast, yes, this is done now.

**Comment by lovetoast** [comment]
Thanks, but quick question, when you say start the process again, does it go to the page that the form is posted to or does it just display the main payment iframe again?

**Comment by lovetoast** [comment]
Also, I tried it, but it's not working, it is the exact same code as the demo code but with my key and I've changed the URL to production

`

  | <!DOCTYPE html>
-- | --
  | <html>
  | <head>
  | <title>Simple Checkout</title>
  | </head>
  | <body>
  | <form id="myform" action="/checkout" method="post">
  | <button type="button"
  | data-vp-publickey="GWVj3QrRn53c/ZlTaC2Qdgp2QN9W/JOPFjxHMEVBbzo="
  | data-vp-baseurl="https://www.vivapayments.com"
  | data-vp-lang="en"
  | data-vp-amount="1000"
  | data-vp-description="My product">
  | </button>
  | </form>
  |  
  | <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
  | <script type="text/javascript" src="https://www.vivapayments.com/web/checkout/v2/js"></script>
  | </body>
  | </html>

`

**Comment by lovetoast** [comment]
> Hi @lovetoast, yes, this is done now.

Hi Matt,

Working now, the other JS didn't work so I tried this but working now.

Final question is regarding my point above, if 3D secure fails does the form revert back to the lightbox or does it to go the form action URL?

**Comment by matthewrgourd** [comment]
Hi @lovetoast, as far as I'm aware, it goes to the form action URL.
