### ISSUE TITLE
Problem with Woo commerce plug in

### ISSUE THREAD

**Issue by flowerspowercbd** [VivaPayments/API#1647]
Hello,
Since yesterday, we have a problem, when we want to pay on our website, there is an error 404.
We don't change anything.
Can you tell me where is the problem.
Thanks you
![Capture d’écran (38)](https://user-images.githubusercontent.com/61199180/80676199-8b103e80-8ab6-11ea-86c6-2ed2c419b61a.png)

**Comment by matthewrgourd** [comment]
Hi @flowerspowercbd, sorry to hear this. There was a small issue with our updated plugin 3.6.1. Please [download](https://downloads.wordpress.org/plugin/vivawallet-woocommerce-gateway.zip) version 3.6.2 of our plugin, disable and remove the previous version, add 3.6.2 as a new plugin and enable it. You may need to use our [installation guide](http://localhost:1313/e-commerce-plugins/woocommerce/) again in case any of your settings need refreshing. Thanks!
