### ISSUE TITLE
WooCommerce Plugin Updates removes vivawallet.png

### ISSUE THREAD

**Issue by jannis-t69** [VivaPayments/API#1648]
Hi,

with update 3.6.1 the plugin updates from inside Wordpress admin plugin dashboards removes the file vivawallet.png. We have to reupload the image after every update i.e 3.6.1->3.6.2

Thank you.

**Comment by matthewrgourd** [comment]
Hi @jannis-t69 thanks for letting me know. I've updated the source code so this shouldn't happen in the future.

**Comment by jannis-t69** [comment]
Thanks a bunch,
Regards,
Jannis
