### ISSUE TITLE
Codice html pagamento semplice 

### ISSUE THREAD

**Issue by LoveCanapa** [VivaPayments/API#1649]
Praticamente io copio il codice html sostituisco la chiave pubblica elimino lla dicitura demo dalla descizione sito.

E in fase di pagamento LIVE non mi esce più il bottone PAY .

allego le immagini di tutto, oltre che della mia chiave pubblica, riesci a farmi fare un codice html finito che io debba fare solo copia e incolla.

![199ECF62-97B9-4763-BEC2-50B2BA91FCD6](https://user-images.githubusercontent.com/63829908/80758323-c736b400-8b35-11ea-9c89-45a366b49ad4.jpeg)

![AB052CAD-7D0E-4F72-85C3-1E436CA09AE4](https://user-images.githubusercontent.com/63829908/80758297-c00fa600-8b35-11ea-8407-5840499d2e0a.jpeg)
![636B9FD5-0E32-4721-8C4D-DBBC4321A815](https://user-images.githubusercontent.com/63829908/80758318-c6058700-8b35-11ea-8fbf-7dad26e7af48.jpeg)

**Comment by matthewrgourd** [comment]
Hi @LoveCanapa, sorry you're having difficulties. Looks like there is an error in the documentation which I will rectify immediately. Where it says to replace demo.vivapayments.com you should use `www.vivapayment.com` rather than `vivapayments.com`. Hope this helps!

**Comment by LoveCanapa** [comment]
Ho sostituito come da tua indicazioni il link del sito in 
Data vp e script src 

Ma non esce il bottone del pagamento 

![49074418-2546-49C4-B66D-99A5786CDC78](https://user-images.githubusercontent.com/63829908/80790077-2c1df880-8b8e-11ea-8176-90319a951e4b.jpeg)

**Comment by LoveCanapa** [comment]
![211968DD-6A31-437B-A1DB-0D0FF456F5F2](https://user-images.githubusercontent.com/63829908/80790165-66879580-8b8e-11ea-9956-0cb32ad73094.jpeg)
![9C26BAC4-24AE-4841-BC2F-28552733E051](https://user-images.githubusercontent.com/63829908/80790172-6be4e000-8b8e-11ea-83f6-f2f61af904d4.jpeg)


Ti allego quanto scritto all’interno del mio pannello.

**Comment by LoveCanapa** [comment]
ho sostituito con www.vivapayments.com e ora il bottone mi appare quando faccio un acquisto inserisco la carta e tutto ma quando si avvia il controllo otp / 3d secure delle carte , mi dice non found url

**Comment by LoveCanapa** [comment]
Dove devo inserire questo testo ? 
Riesci a fornirmi un html finito ? Cosi da fare copia e incolla ? 

![10200029-9849-41AF-9C5A-20E7F8EF7390](https://user-images.githubusercontent.com/63829908/80791019-abacc700-8b90-11ea-942b-914a6962244a.jpeg)

**Comment by LoveCanapa** [comment]
Lo devo inserire nel database mysql di aruba ?

**Comment by matthewrgourd** [comment]
@LoveCanapa sorry for that typo. As you rightly say, should be `www.vivapayments.com` for the base URL. Let me investigate your other issue further and get back to you.

**Comment by LoveCanapa** [comment]
Ok ora il bottone funziona fa eseguire il pagamento ma non da la risposta di pagamento non sapendo dove devo scrivere il codice di risposta del passaggio 2

**Comment by matthewrgourd** [comment]
Hi @LoveCanapa Step 2 gives examples in cURL, PHP and C# of how you would connect to our API within program code through a backend channel (not your browser). You need knowledge of programming in order to implement this.

**Comment by LoveCanapa** [comment]
so do I have to put it in the aruba back up my sql?

**Comment by matthewrgourd** [comment]
I'm sorry, I don't understand the question.

**Comment by LoveCanapa** [comment]
Il codice devo inserirlo nel beck end principale o c’è una pagina esatta dove inserirlo 

![03D7D915-3423-4B90-BE8C-FEAE206A2E76](https://user-images.githubusercontent.com/63829908/80799223-8aef6c00-8ba6-11ea-9f0c-2d22e4e49ddb.jpeg)

**Comment by LoveCanapa** [comment]
Allora io ho fatto le prove , con il codice html fornito , il bottone non prende la cifra spesa presente in carrello , ed il codice php presente sulla fase 2 non comunica con la pagina di pagamento. 

Secondo me dovete rivedere il tutto

**Comment by matthewrgourd** [comment]
Hi @LoveCanapa thanks for the feedback. As you have demonstrated, it's possible our Simple Checkout solution isn't working. In the event of problems, we normally recommend to try [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) instead. However, I'll get our development team to review the Simple Checkout solution as you have recommended. However, I'm not sure how quickly that will happen as developers are assigned to other tasks currently. Thanks!

**Comment by matthewrgourd** [comment]
Hi @LoveCanapa, I gather you have been in contact with one of my colleagues. If you are attempting to integrate our Native Checkout solution, you first need to [set up a payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) as outlined in the [installation guide](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) under "Prerequisites". In order to do this, you need a live website. However, I note that http://fm.aruba.it doesn't seem to be online at the moment.
