### ISSUE TITLE
Source xxx of merchant xxxx supports only native checkout

### ISSUE THREAD

**Issue by KimiGeo** [VivaPayments/API#165]
Καλημέρα.
Προσπαθώ να ενσωματώσω σε ένα custom e-shop την native checkout.
Ενώ στην Default.aspx του API Master το νέο SourceCode δουλεύει μία χαρά , ο ίδιος
κώδικας στο custom e-shop δείχνει το παραπάνω error.
Εννοείται ότι έχει γίνει η ενεργοποίηση υπηρεσίας Native/Simple Checkout στις ρυθμίσεις του
API και στις πηγές πληρωμών έχει γίνει η επιλογή Native/Πληρωμή με Viva Wallet Checkout

**Comment by defilerc** [comment]
Καλημέρα @KimiGeo ,

Σε αντίστοιχο πρόβλημα στο παρελθόν (https://github.com/VivaPayments/API/issues/157) το πρόβλημα οφειλόταν στο ότι υπήρχε κώδικας παρόμοιος με αυτόν στην checkout σελίδα του εμπόρου:

`<input type="submit" value="Υποβολή" class="submit" onclick="return VivaPayments.cards.requestToken();" />`

ο οποίος έπρεπε να αλλάξει σε:

`<input type="button" value="Υποβολή" class="submit" onclick="return VivaPayments.cards.requestToken();" />`

Δηλαδή, ο τύπος του κουμπιού για την Υποβολή της φόρμας να αλλάξει από `type="submit"` σε `type="button"`.

Παρακαλώ επιβεβαιώστε ότι το πρόβλημα σας δεν οφείλεται σε αυτό, αλλιώς είμαστε στη διάθεσή σας για περαιτέρω διερεύνηση.

Ευχαριστούμε πολύ

**Comment by KimiGeo** [comment]
Καλησπέρα @defilerc ,
Έκανα την αλλαγή στο button. Δυστυχώς συνεχίζω να έχω το ίδιο θέμα.  Επιπλέον παρατήρησα ότι το Token είναι κενό.

**Comment by defilerc** [comment]
Καλησπέρα @KimiGeo ,

Παρακαλώ βεβαιωθείτε ότι περνάτε τα απαραίτητα πεδία για να γίνει το tokenization της κάρτας: `cardholder, cardnumber, cvv, month, year`, όπως αυτά περιγράφονται εδώ: https://github.com/VivaPayments/API/wiki/Native-Checkout

Τα πεδία θα πρέπει να περιέχουν επιπλέον το `data-vp` attribute, ώστε να μπορούν να αποσταλλούν επιτυχώς στο Viva Payments API για να γίνει το tokenization.

Επίσης βεβαιωθείτε ότι το public api key που χρησιμοποιείται έχει αντιγραφεί σωστά και πως το url που χρησιμοποιείται είναι αυτό που αντιστοιχεί στο περιβάλλον που κάνετε τις δοκιμές. Τέλος, ελέγξτε πως δεν υπάρχουν javascript errors στη σελίδα σας που μπορεί να επηρεάσουν το script που κάνει το tokenization.

Αν παρολαυτά εξακολουθείτε και έχετε πρόβλημα, παρακαλώ πολύ στείλτε μας το HTTP response code + message που παίρνετε κατά το βήμα του tokenization, μαζί με το merchant id σας για να το διερευνήσουμε περαιτέρω.

Με εκτίμηση

**Comment by KimiGeo** [comment]
Καλησπέρα @defilerc 
Τελικά ήταν κάτι πολύ απλό το
<asp:HiddenField ID="hidToken" runat="server" />
ήθελε άλλο ένα attribute
<asp:HiddenField ID="hidToken" ClientIDMode="Static" runat="server" />

Ευχαριστώ πάντως για την βοήθεια και για την εξαιρετική υποστήριξη!

**Comment by defilerc** [comment]
Ευχαριστούμε πολύ!
