### ISSUE TITLE
Issue with Simple Checkout and WordPress integration

### ISSUE THREAD

**Issue by Term2G** [VivaPayments/API#1650]
Hi!
I'm trying to integrate simple checkout on my custom WordPress page, the only issue i have right now is when loading your demoJS (<script src="https://demo.vivapayments.com/web/checkout/js"></script>) it fails with "Uncaught VivaPayments.js requires jQuery", because WordPress has its own JQuery library that uses JQuery instead of $.

If i copy your JS to my own file and remove "if(typeof $=="undefined")throw"VivaPayments.js requires jQuery";" from it, then it loads just fine.

So question, can you provide a WP friendly JS version of your simple checkout (both demo and live), or can i copy/paste your JS into my own .js and remove the check for JQuery that fails ?

**Comment by Term2G** [comment]
Also please enable Demo API for Simple Checkout:
"POST to https://demo.vivapayments.com/api/transactions"
Reply:
 "ErrorText": "The specified api action is disabled for the merchant 9e042e4b-d553-426a-a448-d8c63050b329, please consult the documentation",

**Comment by Term2G** [comment]
Any feedback?

**Comment by matthewrgourd** [comment]
Hi @Term2G that's done now. Let me know how you get on. Thanks!

**Comment by matthewrgourd** [comment]
@Term2G regarding your other question, I'm afraid we are unable to make any changes to Simple Checkout this time. Apologies for any inconvenience caused. If you want a more up-to-date native solution please look at our [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) information instead. Thanks!

**Comment by Term2G** [comment]
> @Term2G regarding your other question, I'm afraid we are unable to make any changes to Simple Checkout this time. Apologies for any inconvenience caused. If you want a more up-to-date native solution please look at our [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) information instead. Thanks!

Hi! Demo API works now thanks. 

A quick look at Native Checkout v2, Step 2: <script type="text/javascript" src="https://www.vivapayments.com/web/checkout/v2/js"></script>

Quick look at that: if(typeof t=="undefined")throw"VivaPayments.js requires jQuery";

Will it no cause the same issue of not finding WordPress version of JQuery ?

**Comment by Term2G** [comment]
Why is this closed? I haven't had a chance to confirm if it works or ask any questions.

**Comment by matthewrgourd** [comment]
Hi @Term2G sorry for closing – it was by accident! In answer to your other question, please feel free to copy/paste your JS into your own .js and remove the check for JQuery that fails.

**Comment by Term2G** [comment]
> Hi @Term2G sorry for closing – it was by accident! In answer to your other question, please feel free to copy/paste your JS into your own .js and remove the check for JQuery that fails.

Thank you for reply! I will test native checkout v2 and let you know!

**Comment by Term2G** [comment]
Didn't go with native checkout v2 yet, Still proceeded with Simple Checkout because it working for me.
but i have an issue with testing "Failed" transactions:
When selecting "fail" on 3DS auth page of vivawallet, the form's button just turns red with and X and you cant do ANYTHING after this. Only closing the form works, but in my case payment was already started for processing. Why can't the form do a POST to my specified url just like with success transactions ?

![image](https://user-images.githubusercontent.com/30794520/81501871-4325be80-92e3-11ea-91d9-3f3fe31fdfa0.png)

Any chance you can send me a source code of the form js? maybe i can tinker it to help send me proper events/feedback....

**Comment by Term2G** [comment]
Forgot to mention the "fail" simulation is simply emulated by this request ?
![image](https://user-images.githubusercontent.com/30794520/81501942-a4e62880-92e3-11ea-83ec-70437c5d46cc.png)

**Comment by matthewrgourd** [comment]
Hi @Term2G I'm not sure I can help you any further myself, but I'll raise with a devloper and get back to you! Thanks...

**Comment by matthewrgourd** [comment]
Hi @Term2G unfortunately no-one is around to help with Simple Checkout. The general advice is, if you can't get it working try our [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) instead. Thanks!
