### ISSUE TITLE
Simple or Redirect Checkout with custom amount

### ISSUE THREAD

**Issue by vasdrou** [VivaPayments/API#1652]
Hello,
My issue is if I am able to add some code to Simple & Redirect Checkout so that a client to be able to pay custom amount of money.
Can you additionally give a hint for better results?
I have attached a jpg image so that it would be better understood. 
Thanks in advance and honestly for your time.

![viva](https://user-images.githubusercontent.com/64687538/80862854-dece8380-8c80-11ea-9848-162d9b7ff32c.jpg)

**Comment by matthewrgourd** [comment]
Hi @vasdrou, I'm afraid we are unable to make any changes to Simple Checkout at this time. Apologies for any inconvenience caused. If you want a more up-to-date native solution please look at our [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) information instead. Thanks!
