### ISSUE TITLE
Simple Checkout Customer Telephone Number

### ISSUE THREAD

**Issue by cgtheodorou** [VivaPayments/API#1653]
Hi

I noticed in the invoice that is sent to the customer after paying, that there is a field called customer's telephone number but there is no such option when configuring the simple checkout, is there any way to enable that field on the form so that it can also be shown on the receipt?

**Comment by matthewrgourd** [comment]
Hi @cgtheodorou, I'm afraid we are unable to make any changes to Simple Checkout at this time. Apologies for any inconvenience caused. If you want a more up-to-date native solution please look at our [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) information instead. Thanks!
