### ISSUE TITLE
Magento 2.3.3 payment method

### ISSUE THREAD

**Issue by ioannisgz** [VivaPayments/API#1654]
Hi. It is not exactly an issue. Let me describe.
When customer goes to magento checkout and proceed with vivapayments magento send them to viva portal. 
There except the known credit cart payment, viva has additional ways to pay like with payment code in bank.
I had a customer today who paid with this way through its bank.
But magento didn't recognised as a success payment. In admin we saw the order as pending payment.
Do you know anything about this please?

**Comment by matthewrgourd** [comment]
Hi @ioannisgz which version of Magento are you using? Initially when redirecting to Viva Wallet the order status is "Pending" and when a success transaction is received it will be updated to "Processing". If the customer abandons the transaction process, the order status remains "Pending" until the merchant cancels the order.

**Comment by ioannisgz** [comment]
Hello @matthewrgourd . Thank you for your answer. Probably you didn't understand. The scenario is this:
When you redirect to VIVA you have except the credit card payment, another way to pay through wire transfer with payment code. This is VIVA procedure.
So my client chose to pay with that way. He took the payment code and paid directly from his ebanking. Order completed in magento but status was to pending.

I don't know if you understood now. Magento version 2.3.5

**Comment by matthewrgourd** [comment]
Hi @ioannisgz, not sure I do understand, sounds like he failed 3DS or his card wasn't accepted. That is the only reason a status of Pending would be produced. 

I don't know if this will help but we updated our plugin for Magento 2.3.5. You could try removing the previous version and installing this one instead. 

[magento23_vivawallet.zip](https://github.com/VivaPayments/API/files/4573796/magento23_vivawallet.zip)

**Comment by ioannisgz** [comment]
Look. When you first go to viva you get this:
<img width="1294" alt="Screenshot 2020-05-04 at 12 34 41 PM" src="https://user-images.githubusercontent.com/44767880/80953625-9049f200-8e04-11ea-9fa9-2ae9baddd663.png">
If you choose the 3rd option(Pay with bank) you get this:
<img width="1294" alt="Screenshot 2020-05-04 at 12 35 01 PM" src="https://user-images.githubusercontent.com/44767880/80953667-a9eb3980-8e04-11ea-86c5-8dc6174a286d.png">
Then you go to your bank and you pay like you pay your bills. With a payment number.
But in this step you don't have an option to VIVA to close the order. So Magento see that as order waiting payment.

Do you follow me?

**Comment by matthewrgourd** [comment]
I've never seen that before. Looks like a modified version of our plugin. What is the web address of your e-commerce site, please? I need to test.

**Comment by ioannisgz** [comment]
We can't test it on my production site. I am sorry. This is VIVA native checkout page....I think to solve this and magento get reply from VIVA we need to create web hooks. Like stripe does. Viva has the option for web hook but your module don't have it. Also we need to observe with cron the orders so that magento can get the right replies from VIVA. I think that this should be fixed in your module because it confuse customers. We need to talk with VIVA also.
If you want to test I have a dev server but we need to talk in private please so I can give you access and do whatever you need...It is already working with VIVA test there

**Comment by matthewrgourd** [comment]
Hi @ioannisgz I'm raising with our plugin developer. I'll get back to you when I've a reply.

**Comment by matthewrgourd** [comment]
Hi @ioannisgz, the plugin developer has come back with the following:

> If needed you can decrease the `PaymentTimeOut` value or use the `disableCash` parameter. See 
> the [Create payment order](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Payments/paths/~1api~1orders/post) section in our API Reference Guide for more info.
> 

Hope this helps!

**Comment by ioannisgz** [comment]
@matthewrgourd Thank you for answer. This you mentioned we already know. But again you didn't understand. We use your plugin for magento 2.3. We don't use a custom version. We redirect the customer to VIVAWALLET gateway. There we can't involve. I have already talked with VIVA for this. In my opinion and probably other customers will have same issue is that you should observe in your magento module all the payments are accepted from VIVA in addition to credit card. This can be done with web hooks and js functions which will monitor the answers from VIVA. Please pass these to the developer and if he wants we can talk directly. Because if this won't solve it creates mess with the online customers which make the orders.

**Comment by matthewrgourd** [comment]
Hi @ioannisgz I take on board what you're saying. I will feed back to the plugin developer. Thanks for your suggestion which I agree would improve things a great deal. We are currently reviewing all our plugins so now is a good time to be looking at this.
