### ISSUE TITLE
Woocommerce Subscriptions Integration

### ISSUE THREAD

**Issue by georgedes** [VivaPayments/API#1656]
Are you going to release a plugin for the integration with woocommerce subscriptions? If yes, when? We need it urgently. If not, how easy would it be to customize the existing plugin you have for woocommerce subscriptions or make the integration myself, considering I'm not at an expert level?

**Comment by matthewrgourd** [comment]
Hi @georgedes unfortunately not immediately but it's on the road map for the next few weeks.

**Comment by georgedes** [comment]
Okay. What about my other question?

**Comment by matthewrgourd** [comment]
@georgedes in the first instance, you would need to sign up to [WooCommerce subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/) which comes in at $199 a year. After that, it's a question of how experienced you are with PHP.
