### ISSUE TITLE
VIVA Payments 504 error

### ISSUE THREAD

**Issue by watersidecreative** [VivaPayments/API#1658]
Hi, we have the Wordpress platform plugin installed and enabled but we seem to be receiving a 504 error after the card payment has been entered and charged.

**Comment by matthewrgourd** [comment]
Hi @watersidecreative, are you referring to our WooCommerce plugin for Wordpress? Please clarify. If the answer is yes, in order for me to investigate further, can you send through the following screenshots?

- Viva Wallet for WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Closing as no reply...

**Comment by watersidecreative** [comment]
Hi, 

Due to unforeseen circumstance i've not been in touch. I’ll get the details over to you shortly.

Thanks
Ash

**Comment by watersidecreative** [comment]
Hi

Please find attached requested screenshots.

Many thanks
Ash

**Comment by matthewrgourd** [comment]
Hi @watersidecreative, I'm not able to view the screenshots. If you're having problems attaching, please send directly to my email (mgourd@vivawallet.com). Thanks!

**Comment by matthewrgourd** [comment]
Hi @watersidecreative thanks for sending through the screenshots. Your settings look fine and the redirect worked. I just tried a test purchase with a card with no funds and got the expected error message 'There was a problem with your payment, please try again with another card.' If I were to use a card with funds I would expect the payment to go through correctly. Have you got anything different at your end? Please send me a screenshot of any errors....thank you.

**Comment by watersidecreative** [comment]
The issue happens after a payment has been processed, see screenshots. The payment is made an email has been received by the purchaser from VIVA but then hangs and times out after a while. Upon refreshing browser after the time-out screen then we’re sent back to website to order confirmation page

**Comment by watersidecreative** [comment]
Hi, did you manage to look into the error?

Thanks
Ash

**Comment by matthewrgourd** [comment]
Hi @watersidecreative have you got a test product you can make live briefly while I test with a card with funds? Put a price of £1 or something then refund me if the payment goes through correctly. Thanks!

**Comment by watersidecreative** [comment]
Hi, please use the product below, also use coupon code WATERSIDE-TST to activate free delivery.

https://cbdocs.co.uk/product/test/ <https://cbdocs.co.uk/product/test/>

Thanks
Ash

**Comment by matthewrgourd** [comment]
Hi @watersidecreative all working fine. The payment went through (can you refund when you get a spare moment?), the correct success page was displayed (see below screenshot) and I received an order notification. So the conclusion is that any issues experienced previously are card problems and nothing to do with the payment gateway. Please close the ticket if you feel your query has been answered.

![Screenshot 2020-05-13 at 11 14 03](https://user-images.githubusercontent.com/44943019/81800909-7d71a480-950b-11ea-8114-c7dea3394b5e.png)

**Comment by watersidecreative** [comment]
Strange as all seems fine now, we did quite a few transaction before getting in touch and had the same issue.  Sorry for the trouble.
Thanks
Ash
