### ISSUE TITLE
API Call failed! The error was: Invalid or inactive reseller with id XXXXXXXXXXXXXX

### ISSUE THREAD

**Issue by nikosfa** [VivaPayments/API#166]
Το σύστημα βγάζει το ακόλουθο μήνυμα: 
API Call failed! The error was: Invalid or inactive reseller with id XXXXXXXXXXXXXX

όπου XXXXXXXXXXXXXX είναι merchant id από τα στοιχεία λογαριασμού. Τα credentials είναι double checked ότι έχουν καταχωρηθεί σωστά.

Όταν δοκιμάζω με άλλα credentials το σύστημα λειτουργεί καλά.

Χρησιμοποιώ Redirection
Είναι σε demo mode

Χρειάζομαι τα φώτα σας !

**Comment by defilerc** [comment]
Καλησπέρα @nikosfa ,

Μπορείτε να δοκιμάσετε τη λύση που περιγράφεται στο thread https://github.com/VivaPayments/API/issues/144

και να μας πείτε αν αυτό έλυσε το πρόβλημά σας;

Ευχαριστούμε πολύ.

**Comment by nikosfa** [comment]
Καλησπέρα @defilerc,

Ευχαριστώ για την απάντηση σας, αλλά δυστυχώς δεν λειτούργησε. 

Το σύστημα επέστρεψε: API Call failed! The error was: Invalid or inactive reseller with id XXXXXXXXXXXXXX

Παρακάτω είναι μέρος του κώδικα από την αρχικοποίηση, έως τον τερματισμό του αντικειμένου curl session.
 
// Get the curl session object
$session = curl_init($request);

// Set the POST options.
curl_setopt($session, CURLOPT_POST, true);
curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
curl_setopt($session, CURLOPT_HEADER, true);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
//curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
curl_setopt($session, CURLOPT_SSL_VERIFYHOST, false); 
curl_setopt($session, CURLOPT_SSL_VERIFYPEER, false);


// Do the POST and then close the session
$response = curl_exec($session);

// Separate Header from Body
$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
$resHeader = substr($response, 0, $header_len);
$resBody =  substr($response, $header_len);

curl_close($session);

**Comment by nikosfa** [comment]
Επειδή έχουν περάσει πολλές μέρες από τότε που έχουμε ανοίξει την συνομιλία θα μπορουσε κάποιος από την εταιρία να μας δώσει μια απάντηση ή να έρθει σε επικοινωνία μαζί μας για να λυθεί το πρόβλημα του πελάτη μας ?

**Comment by defilerc** [comment]
Καλησπέρα @nikosfa ,

Μπορείτε να μας στείλετε το merchant id σας, ώστε προχωρήσουμε τη διερεύνηση του ζητήματος;

Επίσης, το συγκεκριμένο error σε πιο ακριβώς σημείο το λαμβάνετε; Κατά τη δημιουργία ενός καινούριου Order? Αν ναι, παρακαλώ πολύ στείλτε μας ακριβώς τα options που περνάτε για τη δημιουργία του συγκεκριμένου Order.

Ευχαριστούμε πολύ,

**Comment by nikosfa** [comment]
Σας ευχαριστώ για την άμεση ανταπόκριση.
Σας στέλνω τα απαραίτητα στοιχεία στο email.

**Comment by nikosfa** [comment]
Καλησπέρα σας,

Το merchant id είναι 7c7df5ad-137b-4fdc-b9fa-10e8ee4c4730

Το πρόβλημα εμφανίζεται κατά την δημιουργία καινούριας παραγγελίας.
Η παραγγελία γίνεται από την ακόλουθη σελίδα: 
http://agiolisefarad.gr/en/shabbat-meals-en

Παρακάτω είναι ο κώδικας που χρησιμοποιώ:

Σας παρακαλώ μην διστάζετε να επικοινωνήσετε μαζί μου για ότι χρειαστείτε.

Σας ευχαριστώ @defilerc <https://github.com/defilerc>


<?php

// The POST URL and parameters
$request =  'http://demo.vivapayments.com/api/orders';    // demo 
environment URL
//$request =  'https://www.vivapayments.com/api/orders';    // 
production environment URL

// Your merchant ID and API Key can be found in the 'Security' settings 
on your profile.

$MerchantId = '7c7df5ad-137b-4fdc-b9fa-10e8ee4c4730';
$APIKey = 'ΧΧΧΧΧΧ - αν το χρειαστείτε μπορώ να σας το στείλω σε PM'

//Set the Payment Amount
$Amount = $_GET['clientordertotal'] * 100;    // Amount in cents

//Set some optional parameters (Full list available here: 
https://github.com/VivaPayments/API/wiki/Optional-Parameters)
$AllowRecurring = 'true'; // This flag will prompt the customer to 
accept recurring payments in tbe future.
$RequestLang = 'en-US'; //This will display the payment page in English 
(default language is Greek)
$Source = 'Default'; // This will assign the transaction to the Source 
with Code = "Default". If left empty, the default source will be used.

$postargs = 'Amount='.urlencode($Amount).'&AllowRecurring='.$AllowRecurring.
'&RequestLang='.$RequestLang.'&SourceCode='.$Source.
             '&FullName='.$_GET['clientordername'].
             '&Email='.$_GET['clientorderemail'].
             '&Phone='.$_GET['clientorderphone'];

// Get the curl session object
$session = curl_init($request);

// Set the POST options.
curl_setopt($session, CURLOPT_POST, true);
curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
curl_setopt($session, CURLOPT_HEADER, true);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
//curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

curl_setopt($session, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($session, CURLOPT_SSL_VERIFYPEER, false);


// Do the POST and then close the session
$response = curl_exec($session);

// Separate Header from Body
$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
$resHeader = substr($response, 0, $header_len);
$resBody =  substr($response, $header_len);

curl_close($session);

// Parse the JSON response
try {
     if(is_object(json_decode($resBody))){
           $resultObj=json_decode($resBody);
     }else{
         preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader, $match);
                 throw new Exception("API Call failed! The error was: 
".trim($match[1]));
     }
} catch( Exception $e ) {
     echo $e->getMessage();
}

if ($resultObj->ErrorCode==0){    //success when ErrorCode = 0
     $orderId = $resultObj->OrderCode;

        setlocale(LC_MONETARY, 'el_GR.utf8');

     $order_message = ' <b>Order Code:</b>'. $orderId .
                      '<br/><br/>' .
                      '<b>Name: </b>' . $_GET['clientordername'] . '<br/>' .
                      '<b>Phone: </b>' . $_GET['clientorderphone'] . 
'<br/>' .
                      '<b>Email: </b>' . $_GET['clientorderemail'] . 
'<br/>' .
                      '<b>Adults No.: </b>' . 
$_GET['clientorderadultsno'] . '<br/>' .
                      '<b>Children No.: </b>' . 
$_GET['clientchildrenno'] . '<br/>' .
                      '<b>Order Date: </b>' . 
$_GET['clientorderdate'].'<br/>' .
                      '<b>Your Message: </b>' . 
$_GET['clientordermessage'].'<br/><br/>' .
                      '<b>Order Total: '. money_format('%.2n', 
$_GET['clientordertotal']) .' </b><br/>' .
                      '<br/><br/>' .
                      '<div class="uk-width-1-2"><a class="uk-button 
uk-button-large uk-button-danger" href="javascript:history.back()">Go 
Back</a>' .
                      '<a  class="uk-align-right uk-button 
uk-button-large uk-button-success" 
href="http://demo.vivapayments.com/web/checkout?ref='.$orderId.'" >Make 
Payment</a></div>';

     /*echo 'To simulate a successful payment, use the credit card 
4111111111111111, with a valid expiration date and 111 as CVV2.';
     echo '</br/><a 
href="http://demo.vivapayments.com/web/newtransaction.aspx?ref='.$orderId.'" 
 >Make Payment</a>';
         */
         echo $order_message;
         // send_order_email($order_message, $orderId);
}

else{
     echo 'The following error occured: ' . $resultObj->ErrorText;
}

function send_order_email($p_order_message, $p_order_id){

}

?>
<script>
//alert('test');
</script>



Με εκτίμηση*

Νίκος Φάτσης**

OpenWare*
Κατασκευή - Φιλοξενία Ιστοσελίδων - SEO
*

Tel./Fax:+30 231 231 51 56 **

Email:* nikos@openware.gr*
Web: *http://www.openware.gr

logo OpenWare

**Comment by defilerc** [comment]
Καλησπέρα @nikosfa ,

Το merchant id (7c7df5ad-137b-4fdc-b9fa-10e8ee4c4730) που προσπαθείτε να χρησιμοποιήσετε στο demo περιβάλλον είναι παραγωγής (live environment). 

Θα πρέπει να κάνετε εγγραφή σαν merchant στο http://demo.vivapayments.com/ και να χρησιμοποιήσετε το merchant id που θα σας αποδωθεί εκεί, προκειμένου να κάνετε δοκιμές στο demo περιβάλλον.

Με εκτίμηση

**Comment by nikosfa** [comment]
Επειδή οι δοκιμές έχουν ήδη γίνει με άλλο merchant id σε demo περιβάλλον, υπάρχει τρόπος να γίνει τεστ με το συγκεκριμένο merchant id ?

**Comment by defilerc** [comment]
Καλησπέρα @nikosfa ,

Το merchant id σχετίζεται με το περιβάλλον που θέλετε να γίνουν δοκιμές. Εσείς σε ποιό περιβάλλον αντιμετωπίσατε το πρόβλημα: demo ή live;

Ευχαριστούμε

**Comment by nikosfa** [comment]
Έχουμε κάνειι δοκιμές σε demo περιβάλλον με άλλο merchant id.
Θα ήθελα να κάνω δοκιμές με το συγκεκριμένο merchant id (7c7df5ad-137b-4fdc-b9fa-10e8ee4c4730), το οποίο αργότερα θα λειτουργήσει, εφόσον οι δοκιμές πετύχουν, και σε live περιβάλλον . 
Είναι εφικτό να κάνω δοκιμές με το συγκεκριμένο merchant id ?

**Comment by defilerc** [comment]
Καλησπέρα @nikosfa ,

Δυστυχώς, δεν είναι δυνατή η χρήση merchant id παραγωγής (live environment) σε δοκιμαστικό περιβάλλον (demo environment).

Με εκτίμηση,

**Comment by nikosfa** [comment]
Καλησπέρα @defilerc,

Σας ευχαριστώ πολύ για την βοήθειά σας.

Με εκτίμηση

**Comment by nikosfa** [comment]
This e-mail contains graphics, if you don't see them » view it online. (
http://www.nautilia-yachting.com/index.php?option=com_acymailing&ctrl=archive&task=view&mailid=91&key=bpvOfCJp&subid=3609-pZLJJFHMyaxIVI&tmpl=component&acm=3609_91
)

Newsletter 19 May 2017

Greetings from NAUTILIA YACHTING !
 
Please check our new special offers in Greece

Special Offers ( http://www.nautilia-yachting.com/yacht-charter/special-offers?acm=3609_91 ) 

Best Regards

Nautilia Yachting
Greek Yacht Charter Company

Address: Skiathou 2 str., Thessaloniki, Greece
tel/fax: +30.2310558192, +302312315154
email: info@nautilia-yachting.com

If you're not interested any more » unsubscribe (
http://www.nautilia-yachting.com/index.php?subid=3609&option=com_acymailing&ctrl=user&task=out&mailid=91&key=pZLJJFHMyaxIVI )

**Comment by nikosfa** [comment]
This e-mail contains graphics, if you don't see them » view it online. (
http://www.nautilia-yachting.com/index.php?option=com_acymailing&ctrl=archive&task=view&mailid=92&key=0swu9a7q&subid=3609-pZLJJFHMyaxIVI&tmpl=component&acm=3609_92
)

Newsletter 24 May 2017

Greetings from NAUTILIA YACHTING !
 
Please check our new special offers in Greece

Special Offers ( http://www.nautilia-yachting.com/yacht-charter/special-offers?acm=3609_92 ) 

Best Regards

Nautilia Yachting
Greek Yacht Charter Company

Address: Skiathou 2 str., Thessaloniki, Greece
tel/fax: +30.2310558192, +302312315154
email: info@nautilia-yachting.com

If you're not interested any more » unsubscribe (
http://www.nautilia-yachting.com/index.php?subid=3609&option=com_acymailing&ctrl=user&task=out&mailid=92&key=pZLJJFHMyaxIVI )

**Comment by nikosfa** [comment]
This e-mail contains graphics, if you don't see them » view it online. (
http://www.nautilia-yachting.com/index.php?option=com_acymailing&ctrl=archive&task=view&mailid=96&key=yoeWb4yY&subid=3609-pZLJJFHMyaxIVI&tmpl=component&acm=3609_96
)

Newsletter 03 June 2017

Greetings from NAUTILIA YACHTING
 
Please check our new special offers in Greece

Best Regards

Nautilia Yachting
Greek Yacht Charter Company

Address: Skiathou 2 str., Thessaloniki, Greece
tel/fax: +30.2310558192, +302312315154
email: info@nautilia-yachting.com

If you're not interested any more » unsubscribe (
http://www.nautilia-yachting.com/index.php?subid=3609&option=com_acymailing&ctrl=user&task=out&mailid=96&key=pZLJJFHMyaxIVI )

**Comment by nikosfa** [comment]
This e-mail contains graphics, if you don't see them » view it online. (
http://www.nautilia-yachting.com/index.php?option=com_acymailing&ctrl=archive&task=view&mailid=97&key=amuJDONK&subid=3609-pZLJJFHMyaxIVI&tmpl=component&acm=3609_97
)

Newsletter 06 June 2017

Greetings from NAUTILIA YACHTING
 
Please check our new special offers in Greece

Best Regards

Nautilia Yachting
Greek Yacht Charter Company

Address: Skiathou 2 str., Thessaloniki, Greece
tel/fax: +30.2310558192, +302312315154
email: info@nautilia-yachting.com

If you're not interested any more » unsubscribe (
http://www.nautilia-yachting.com/index.php?subid=3609&option=com_acymailing&ctrl=user&task=out&mailid=97&key=pZLJJFHMyaxIVI )

**Comment by nikosfa** [comment]
This e-mail contains graphics, if you don't see them » view it online. (
http://www.nautilia-yachting.com/index.php?option=com_acymailing&ctrl=archive&task=view&mailid=98&key=OuI1iDub&subid=3609-pZLJJFHMyaxIVI&tmpl=component&acm=3609_98
)

Newsletter 08 June 2017

Greetings from NAUTILIA YACHTING
 
Please check our new special offers in Greece

Best Regards

Nautilia Yachting
Greek Yacht Charter Company

Address: Skiathou 2 str., Thessaloniki, Greece
tel/fax: +30.2310558192, +302312315154
email: info@nautilia-yachting.com

If you're not interested any more » unsubscribe (
http://www.nautilia-yachting.com/index.php?subid=3609&option=com_acymailing&ctrl=user&task=out&mailid=98&key=pZLJJFHMyaxIVI )
