### ISSUE TITLE
WooCommerce Orders are canceled. 

### ISSUE THREAD

**Issue by Superbumas** [VivaPayments/API#1660]
When the order comes in and the payment is made, for some reason order status becomes Cancelled.

What could be the issue please?

Thank you 
Andrius

**Comment by matthewrgourd** [comment]
Hi @Superbumas, the status of 'Cancelled' occurs if a customer has failed their 3DS authentication or has insufficient funds. There are a few other reasons, too. If in doubt, the customer should contact their card issuer. If you want me to check your account to see if there's anything unusual happening, please provide your trading name and website address. Thanks!

**Comment by Superbumas** [comment]
Hi Matthew, sorry missed your reply. So I would understand that status cancelled would be if they fail the payment, but the money is showing in the Vivapayments dashboard, so as I understand the payment does go through, but on Woo is shows as cancelled.

**Comment by matthewrgourd** [comment]
Hi @Superbumas I believe what you describe is the correct behaviour with our current plugin. However, we're about to release a new version which will address the synchronisation issue between WooCommerce and our payment gateway. Watch this space!
