### ISSUE TITLE
Woocommerce Pending Payments

### ISSUE THREAD

**Issue by nicolascolocci** [VivaPayments/API#1661]
Hello, many customers are reporting that once they pay on vivawallet the funds are correctly withdrawn from their bank accounts or cards, but sometimes they show up on our vivawallet account, sometimes they do not. 

In case they do show up in our account sometimes the order status takes days (or weeks) to change from Pending Payment to Processing, causing quite some issues both for Customer Care and for our Inventory dept.

**I would like to note that this isnt always the case, it only happens with some orders, others pay and the order goes straight to processing with no problems at all.**

Any ideas on what could be the cause of this? 
Thanks

**Comment by matthewrgourd** [comment]
Hi @nicolascolocci sorry to hear this. One possible explanation is that the current download of our payment plugin for WooCommerce doesn't feature real-time syncing. We are about to release a new version where this happens automatically. I'll update the ticket once this is available.

**Comment by WeedyTech** [comment]
Hello, we have the same problem and we need a solution to fix this very quick. We can't continue to collaborate in these conditions.

**Comment by nicolascolocci** [comment]
Hello, any updates on this? we are loosing about 20 orders per day because of this!!

**Comment by matthewrgourd** [comment]
Hi @nicolascolocci apologies for the extended delay. We've got a big project on right now but I should be able to update you tomorrow!

**Comment by matthewrgourd** [comment]
Hi @nicolascolocci the latest update is we're due to release an updated version next Monday or Tuesday. I'll update you again once this is available.

**Comment by matthewrgourd** [comment]
Hi @nicolascolocci, we now have this version ([v4.0.0](https://github.com/VivaPayments/API/files/4656365/viva-wallet-plugin-for-woocommerce.zip)) you can try which is currently in beta. The syncing works but you need to set up a webhook in your Viva Wallet API settings. The documentation will be slightly different when released as the payment source is now set up automatically rather than manually. Let me know how you get on!
