### ISSUE TITLE
version compatibility with woocommerce

### ISSUE THREAD

**Issue by aristosv** [VivaPayments/API#1662]
Are there any plans of populating the unknown value (woocommerce) shown below?

It will provide ease of mind for online shop owners, when upgrading woocommerce.

![1](https://user-images.githubusercontent.com/528302/81136240-ae7a3400-8f63-11ea-90ad-ae14546e6e81.png)

Thanks

**Comment by matthewrgourd** [comment]
Hi @aristosv this is a very good point which I spotted myself. I will raise with one of our devs.

**Comment by matthewrgourd** [comment]
Hi @aristosv I've made a note to update this in the next release. Thanks again.
