### ISSUE TITLE
HTTP ERROR 500 with  module Vivawallet v1.6.8 for  prestashop 1.6.1.24

### ISSUE THREAD

**Issue by SharkBaitweb** [VivaPayments/API#1663]
Good afternoon,
i have an issue with the module, when i proceed to checkout at step 4 it throws an HTTP ERROR 500 
<img width="1273" alt="Schermata 2020-05-06 alle 15 04 18" src="https://user-images.githubusercontent.com/64905623/81180118-dfca2280-8faa-11ea-8f5d-58a780646abd.png">

**Comment by SharkBaitweb** [comment]
i have tried on a fresh install of prestashop 1.6.1.24

**Comment by matthewrgourd** [comment]
Hi @SharkBaitweb, sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- PrestaShop payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by SharkBaitweb** [comment]
Hi matthewrgourd,
the settings are correct but even though they where wrong it is some misconfiguration from the plugin with prestashop 1.6.1.24 i have made a test installation on a freshly installed prestashop. 
it returns a http error 500 whethever it has a configuration or not. 
problably is the plugin itself that has a misconfiguration.

**Comment by SharkBaitweb** [comment]
i made a transaction but in BO payment is not registered ...

**Comment by matthewrgourd** [comment]
Hi @SharkBaitweb I note that the source code field in your settings is blank. Please complete this with your four-digit Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) ID. This will be what is causing the problem. Thanks!

**Comment by SharkBaitweb** [comment]
Hi @matthewrgourd  i have to leave the field blank otherwise il will give the error as for picture n 1 in the issue. 

**I have created Parmasapori app links are correck and webhook is created and active
but if i put in the plugin the source code 4 digits it wont work..**



<img width="944" alt="Schermata 2020-05-07 alle 19 19 51" src="https://user-images.githubusercontent.com/64905623/81325317-758fab80-9098-11ea-87c4-d805d0e6e8cb.png">



**i have changed instead the default app with che correct url's from parmasapori and leaving the source code blank and it will process correctly the transactions**



<img width="582" alt="Schermata 2020-05-07 alle 19 20 12" src="https://user-images.githubusercontent.com/64905623/81325511-c1425500-9098-11ea-8615-4e4b04566028.png">



**It is working perfectly now !!!!! only issue is the payment page as for picture i have english language... how to change it?**



<img width="1014" alt="Schermata 2020-05-07 alle 19 32 29" src="https://user-images.githubusercontent.com/64905623/81326166-b89e4e80-9099-11ea-8828-ad62955c49e9.png">



**i have changed in the settings as for image but still language in English**



<img width="585" alt="Schermata 2020-05-07 alle 19 20 20" src="https://user-images.githubusercontent.com/64905623/81326313-ef746480-9099-11ea-892f-68217c165574.png">


it must be somewhere in the plugin php code  that is configured and not retrieve the source code but gives a HTTP 500 error

**Comment by matthewrgourd** [comment]
Can you try removing the entry from the 'Instalment logic' field? Apparently instalments are available in Greece only.

**Comment by matthewrgourd** [comment]
If that doesn't work, in the 'Lingua' field in the payment source settings, try leaving the default 'lang' instead of adding it-IT.

**Comment by SharkBaitweb** [comment]
ok i did and seems its working now, but still i have the redirected page in English, i'll need to have it in italian

**Comment by matthewrgourd** [comment]
Hi @SharkBaitweb unfortunately we only handle GR/EN languages as default so customers have to manually change the language on checkout if they want Italian.

**Comment by SharkBaitweb** [comment]
it will be possible in future to add IT language?

**Comment by SharkBaitweb** [comment]
i have managed to accomplish the request i have made before , just changed in vivawallet.php @line 218 the language code.
<br>
<br>
<img width="718" alt="Schermata 2020-05-09 alle 09 50 17" src="https://user-images.githubusercontent.com/64905623/81467685-b2fc5200-91da-11ea-9fc5-7ecc05ed57b7.png">


now i have another question:

in the processing page should not be there in the description something about the articles purchased? Please help me out with this
<br>
<br>

<img width="1186" alt="Schermata 2020-05-09 alle 09 53 46" src="https://user-images.githubusercontent.com/64905623/81467823-9876a880-91db-11ea-92cc-0ccb682b1ad0.png">

**Comment by matthewrgourd** [comment]
Hi @SharkBaitweb, nice one, I will bear that code change in mind for future reference if anyone else asks the same question!

Regarding the product description, I'm not sure if there's anything more you can add but I will check for you. Thanks...
