### ISSUE TITLE
Creating new Webhook at final step verification error

### ISSUE THREAD

**Issue by Developer587** [VivaPayments/API#1665]
I can't create new web hook at the last step here:
https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

I'm using this url: https://www.shopistic.gr/index.php?wc-api=wc_vivawallet&vivawallet=webhook
but returns me this error all the time. I cannot verify it

![error](https://user-images.githubusercontent.com/62015895/81324349-8132a080-909f-11ea-92a4-48d5cdd2d9f3.JPG)

here is the payment source screenshot:
![1](https://user-images.githubusercontent.com/62015895/81324747-16359980-90a0-11ea-8e7c-cf0f25377f6c.png)

**Comment by matthewrgourd** [comment]
Hi @Developer587 sorry to hear this, we're looking into the issue now. I'll get back to you once I've an update.

**Comment by matthewrgourd** [comment]
Hi @Developer587 we've checked the webhook functionality and it's working as expected. Can you let me know if you downloaded our latest plugin for WooCommerce from the below location?

https://downloads.wordpress.org/plugin/vivawallet-woocommerce-gateway.zip

If you did, I'll need to investigate further. Please send through the following screenshots:

- WooCommerce payment module settings (hide your Merchant ID and API Key).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (hide API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Closing issue as no reply...
