### ISSUE TITLE
 refund   customer money any time information

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1666]
hi, pls let me know 
                  in simple checkout , after successfull payment, after  2 months we want to  refund 
 there money back.

pls let me know any API is there to implement this requirement

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @chennurubharath please see https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/delete in our [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/) documentation.
