### ISSUE TITLE
viva wallet enable for live merhcant  account 

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1667]
Hi, 

we are getting below response for live merchant, 

find below  live account response,

{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,
"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,
"ErrorText":"The specified api action is disabled for the merchant XXXXXX-d9a6-4cfe-a992-3ae583caXXXX,
please consult the documentation","TimeStamp":"2020-05-08T14:46:54.7370739+03:00","CorrelationId":null,"EventId":0,"Success":false}

Please reply as soon as possible

Thanks &Regards,
itcs

**Comment by matthewrgourd** [comment]
Hi @chennurubharath can I have the merchant name and website address, please, and I will investigate further. Thanks!

**Comment by chennurubharath** [comment]
hi @matthewrgourd ,

kindly note that,  you are given label native checkout v2, but  we are trying  simple checkout.

in simple checkout, after getting   vivawallettoken, we are calling transaction api (  second step simple checkout) we are facing   above error. pls find below details.
 Trade name
EFILE READY LIMITED
  Registration date
19/02/2020 
 
Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @chennurubharath the Simple Checkout API is now enabled on the live account. Thanks!

**Comment by chennurubharath** [comment]
thanks @matthewrgourd
