### ISSUE TITLE
Wrong Email 

### ISSUE THREAD

**Issue by gpantelidis** [VivaPayments/API#1668]
Hello, I use the plugin for woocommerce and when an order is completed sent the stock email template to customers.

I use Woocommerce email Customizer for edit templates.

**Comment by matthewrgourd** [comment]
Hi @gpantelidis, sorry, I don't understand the query. Please provide full details including your business name and website address, and what it is you're attempting to do. Thanks!

**Comment by gpantelidis** [comment]
Hello again, 
The name company is PiGi Shoes. I edit email templates that send to customers when an order is completed. For some reason plugin sends the stock template that has woocommerce. It is like skip the plugin.

**Comment by matthewrgourd** [comment]
Hi @gpantelidis there is an-autogenerated notification we send to customers. Would you like me to turn that off? Unfortunately there are no other settings I can change...

**Comment by matthewrgourd** [comment]
Closing as no reply...
