### ISSUE TITLE
Shopify payment platform error

### ISSUE THREAD

**Issue by cbdhouse** [VivaPayments/API#1669]
The payment method is not working properly. It doesn't allows customer make payments since yesterday so I'm having many left items, its urgent to fix it.

**Comment by matthewrgourd** [comment]
Hi @cbdhouse sorry to hear this, could I have your registered business name and website address so I can check? Thanks!

**Comment by cbdhouse** [comment]
hi. registered name: Strategos Commerce consulting SL
web: www.cbdhousemadrid.com

**Comment by matthewrgourd** [comment]
HI @cbdhouse I can see successful payments on the following dates:

* 17/05
* 14/05 (x2)
* 13/05
* 12/05

How many 'failures' have you had? Are you sure these aren't abandoned carts?

**Comment by cbdhouse** [comment]
Morning, 
<img width="1440" alt="Captura de pantalla 2020-05-08 a las 17 16 28" src="https://user-images.githubusercontent.com/65082316/82193279-7a085f80-98f5-11ea-9554-c748801d8d6f.png">
<img width="1440" alt="Captura de pantalla 2020-05-08 a las 17 28 17" src="https://user-images.githubusercontent.com/65082316/82193282-7b398c80-98f5-11ea-9e06-52ac1a2386d7.png">
<img width="1440" alt="Captura de pantalla 2020-05-15 a las 22 49 20" src="https://user-images.githubusercontent.com/65082316/82193285-7b398c80-98f5-11ea-8c1e-9b1059df560b.png">
<img width="1440" alt="Captura de pantalla 2020-05-17 a las 22 39 11" src="https://user-images.githubusercontent.com/65082316/82193288-7bd22300-98f5-11ea-9bb5-455807236ccb.png">
<img width="1440" alt="Captura de pantalla 2020-05-17 a las 22 39 19" src="https://user-images.githubusercontent.com/65082316/82193289-7bd22300-98f5-11ea-8d24-0b97096ae39a.png">

**Comment by cbdhouse** [comment]
It's true that at a few orders were paid, but there are 3/4 after 20? 30? of them lost... Last night I tried again by myself, and there's the same result. I complete sure there are not abandoned carts, some of failed trials you can see that customers tried at least 4 times.

**Comment by matthewrgourd** [comment]
Hi @cbdhouse sorry to hear this. Can you let me know what the error message states in the third screenshot you sent through? Unfortunately I'm not an Italian speaker!

**Comment by cbdhouse** [comment]
sure, It says: 
"Your payment have been refused.  Please try again or use different payment way" 
But is the same, there a re customers that have tried with 2 different cards, me too, I have tried 4 cards and none is accepted.

**Comment by matthewrgourd** [comment]
Hi @cbdhouse, this does sound like a problem we may need to look into further. Can you confirm your cards are [3DS enabled](https://help.mobiletopup.com/knowledge-base/what-is-3ds-and-why-do-i-need-to-use-it/)?

**Comment by matthewrgourd** [comment]
@cbdhouse are the cards you attempted to use Visa or Mastercard? If they're Mastercard it's possible you may not be enrolled with them. In this instance, we will be able to do something for you...

**Comment by matthewrgourd** [comment]
Closing issue as no reply for 12 days...
