### ISSUE TITLE
Native Recurring Payments

### ISSUE THREAD

**Issue by andyz1974** [VivaPayments/API#167]
Καλησπέρα σας.
Έχω ενσωματώσει Native Payments σε ένα test site, χρησιμoποιώντας ως βάση το παράδειγμα που έχετε για php και θελω να ενεργοποιήσω τις επαναλαμβανόμενες πληρωμές (Recurring). 
Στην φόρμα όπου ο πελάτης συμπληρώνει τα στοιχεία χρέωσης, έχω και ένα πεδίο για να αποδεχτεί τις επαναλαμβανόμενες πληρωμές, οπότε, εφόσον επιλέξει "Ναι", δίνεται στο $AllowRecurring η τιμή True.
Στο NativeCheckoutClass.php έχω προσθέσει στις παραμέτρους της createOrder και το $AllowRecurring.
Η συναλλαγή εκτελείται κανονικά και στο demo.vivapayments.com φαίνεται το ποσό, αλλά όταν τρέχω το /recurring_payments.php (επίσης από το παράδειγμα), με το αντίστοιχο transactionID, εμφανίζεται το μήνυμα "Invalid transaction. The transaction xxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxx does not allow recurring charge.
Προφανώς κάπου κάνω λάθος. Θα ήθελα την βοήθειά σας για να το εντοπίσω.

Παρακάτω το σχετικό κομμάτι από το index.php
`<?php
require_once("libraries/NativeCheckoutClass.php");
if (count($_POST)>0){
	// Remember to change the API Credentials in the NativeCheckoutClass file
	$page=new NativeCheckout();
	$amount=$_POST['amount']; // in cents
	$name=$_POST['txtCardHolder'];
	$email=$_POST['email'];
	$AllowRecurring=$_POST['recurring'];
	$transactionId=$page->MakePayment($amount,$_POST["hidToken"],$_POST["drpInstallments"],$AllowRecurring,$email);
	if ($transactionId!='0'){
		echo "Transaction Succesful with Id :".$transactionId;
		echo $AllowRecurring; 
	}
	else {
		echo "Transaction Failure";
	};	
}
?>`

Σας ευχαριστώ πολύ.

**Comment by andyz1974** [comment]
Καλησπέρα @krakenrules και ευχαριστώ για την απάντηση.
Στις ρυθμίσεις του demo είναι ενεργοποιημένες οι επαναλαμβανόμενες πληρωμές.
To $AllowRecurring=$_POST['recurring']; παίρνει την τιμή του από το σχετικό πεδίο στην φόρμα, και το αποτέλεσμα είναι TRUE.
Στο NativeCheckoutClasss.php η δημιουργία order είναι ως εξής:

`	private function CreateOrder($amount,$installments,$AllowRecurring){
	
		$obj=new OrderRequest();
		
		$obj->Amount=$amount;
		$obj->SourceCode=$this->nativeCheckoutSourceCode;
		$obj->MaxInstallments=$installments;
		$obj->AllowRecurring=$AllowRecurring;
				
		$resultObj = $this->ExecuteCall($this->baseApiUrl.$this->paymentsCreateOrderUrl,$obj);
		
		if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
			return $resultObj->OrderCode;
		}
		else{
			echo 'The following error occured: ' . $resultObj->ErrorText;
			return 0;
		}	
	}	
	`
Είναι κάτι από αυτά λάθος;

Διάβασα ξανά και ξανά τις ενότητες στα παραπάνω link, αλλά προφανώς κάτι χάνω.
Μπορείτε να δείτε live το παράδειγμα (σε υποτυπώδη μορφή, εδώ: http://www.kokonut.gr/viva/)

Και πάλι ευχαριστώ.

**Comment by krakenrules** [comment]
Καλημέρα andyz1974,

Θα πρέπει να προστεθεί και η παράμετρος "AllowsRecurring" = true κατά την δημιουργία του αρχικού payment, πχ:

**`http://demo.vivapayments.com/api/Transactions`**
```
{
  "OrderCode" : 4196994049072607,
  "SourceCode": 'NATIVE',
  "Installments": 1,
"AllowsRecurring": true,
  "CreditCard" : {
     "Token": "Ihwc3yNL9Rjw/Y6oD7rCSGWjwBBK="
  }  
}
```


Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by andyz1974** [comment]
Καλησπέρα @krakenrules  
Θα ήταν δύσκολο ένα παράδειγμα του πώς θα πρέπει να είναι το NativeCheckoutClass.php ME ενεργοποιημένο το recurring payments; 
Έχω κάνει όσα γράφετε παραπάνω και όταν "τρέχω" το recurring_payment.php εμφανίζεται το μήνυμα "Invalid transaction. The transaction bc845329-e54e-4bc3-b466-bac32ab895e0 does not allow recurring charge".
Προφανώς αυτό σημαίνει ότι κάπου υπάρχει λάθος, το οποίο προφανώς επίσης είναι δικό μου, αλλά δεν είναι προς όφελος όλων να έχουμε ένα έτοιμο παράδειγμα και ένα step by step tutorial για το πώς μπορούμε να έχουμε native recurring payments;

**Comment by andyz1974** [comment]
Καλησπέρα @krakenrules 
Η παράμετρος είναι AllowsRecurring ή AllowRecurring; Έχω δοκιμάσει και τα δύο, αλλά δεν μπορώ να εντοπίσω το λάθος.
Υπάρχει κάποιο παράδειγμα για το πώς πρέπει να είναι το recurring payments σε php;

**Comment by krakenrules** [comment]
Καλημέρα,

Συνοπτικά για recurring payment πρέπει:
- Στο Profile  να είναι **ενεργοποιημενα τα recurring payments**.
- Στο CreateOrder να έχει δηλωθεί η παραμετρος **AllowRecurring** = true
- Στο αρχικό CreateTransaction να έχει δηλωθεί η παραμετρος **AllowsRecurring** = true

Παρόμοιο θέμα με το δικό σας είναι [εδώ](https://github.com/VivaPayments/API/issues/138)

Ευχαριστούμε πολύ για την επικοινωνία.

**Comment by andyz1974** [comment]
Καλησπέρα σας. 
Πράγματι αυτό το "s" στην μέση ήταν το θέμα.
Ευχαριστώ πολύ.
