### ISSUE TITLE
Orders "waiting for payment" - then "cancel" (woocommerce)

### ISSUE THREAD

**Issue by Alexklb** [VivaPayments/API#1670]
Hello, I have some issues on couple of orders.

The issue appears for some of my customers. They told me they cannot go through payment process.

On my woocommerce account I can see order "waiting for payment" then changing to "cancel".

On my vivawallet dashboard nothing appears.

I can say about 20% of my orders every day are having that issue. This is much more than the "normal" failed payments I use to have. I know this is not just an abandonned checkout because I know most of my customers, they write me about it, and they are able to pay with the other gateway I have on my site.

When I try personnaly to pay everything is working. Is there a known issue on some browser or with some kind of credit card? One of my customers having issue was using a revolut card, but not sure this is the case for all of them.

Is there anyone who could help ? The install is new (about 2 weeks), and works fine for all the rest of my customers. But still I'd like this to work 100% fine

**Comment by matthewrgourd** [comment]
Hi @Alexklb this sounds normal as there will always be some failed transactions due to genuine card issuer reasons (insufficient funds, 3DS failures etc.). However, I will check your account. Please provide your registered business name and website address. Thanks!

**Comment by Alexklb** [comment]
Hello Matthew thanks for reply.
Business name is Flora CBD and website is https://floracbd.fr/

I asked customers about it when payment failed. They told me about a freezing page right after they validate 3Ds secure on their banking app, no validation, then back to home page. If they use the other payment gateway I have on my website they can pay. It really looks like there is an issue on some card, browser , device on anything.

**Comment by matthewrgourd** [comment]
Hi @Alexklb I can see one payment failure on 8 May, three on 9 May and one on 10 May. These were all due to genuine card issuer reasons. You have approximately 52 successful payments in the time since setup. I can confirm that everything is working correctly at the Viva Wallet end. Best regards, Matt

**Comment by Alexklb** [comment]
Hello, I actually have on 
8/05 : 5 cancel payment
9/05 : 8 cancel payment
10/05 : 5 cancel payment
Its much more than what you can see because those transaction doen't even appears on vivawallet.

As I tols you it shows on my website "waiting for payment", then it appears as cancelled.

My customers told me it's nothing about card issuers reason because they can pay with the other gateway mercanet.

Is there any way you could trust and help ?

Thanks

**Comment by Alexklb** [comment]
Hello again. On a single day yesterday I had 8 cancel orders on woocommerce from vivawallet. Still no-one can help me with it?

**Comment by matthewrgourd** [comment]
Hi @Alexklb you had 13 successful payments coming in to your Viva Wallet account yesterday. If there was an issue with our plugin, there wouldn't be any successful transactions. However, at the moment our plugin doesn't sync with WooCommerce so you may see differences in output from the two platforms. We aim to address this with a release happening soon. I'll let you know when this becomes available.
