### ISSUE TITLE
domain name, subdomain

### ISSUE THREAD

**Issue by Wolfus7833** [VivaPayments/API#1671]
Bonjour
Here is the website I built for a friend: https://commander.mikwabo-paris.fr
I asked him to fulfill the file on members.vivawallet.com, but he got an error with the domain name   "commander.mikwabo-paris.fr"
Then I asked him to try with "mikwabo-paris.fr", and it seems to work.
Must I change url "https://commander.mikwabo-paris.fr" to https://mikwabo-paris.fr, or is there any possibility to keep "https://commander.mikwabo-paris.fr"
for the moment, I still have "The merchant with id 7fbb797c-04a6-48fb-afee-148b84e177d8 does not have a source with code 'xxxx' assigned or the source is disabled"

**Comment by matthewrgourd** [comment]
Hi @Wolfus7833 this is something you need to take up with our customer service team on support@vivawallet.com. Unfortunately I can't make your payment source active from here. You should have received an email with instructions on what to do. If not, please call one of the below numbers for help:

<table><tr><th>Country</th><th>Phone number</th>
  <tr><td>Belgium</td><td>(+32) 2342 0790</td></tr>
    <tr><td>Cyprus</td><td>(+357) 2403 0211</td></tr>
    <tr><td>France</td><td>(+33) 1876 50765</td></tr>
    <tr><td>Greece</td><td>(+30) 21 1760 4000</td></tr>
    <tr><td>Netherland</td><td>(+31) 2089 05503</td></tr>
    <tr><td>Romania</td><td>(+40) 3122 96150</td></tr>
    <tr><td>UK</td><td>(+44) 20 3734 7770</td></tr>
    <tr><td>Portugal</td><td>(+351) 3 0050 9059</td></tr>
</table>

**Comment by Wolfus7833** [comment]
Merci, Have a good day.
