### ISSUE TITLE
Website inactive

### ISSUE THREAD

**Issue by dansmithvl** [VivaPayments/API#1672]
Good morning,

I have set up viva wallet with woocommerce on Friday on a sub domain.

Still inactive and test mode is enabled on woo plugin.

What now please?

Thanks Danny

**Comment by matthewrgourd** [comment]
Hi @dansmithvl I don't think the plugin will work on a subdomain. However, please send through the following screenshots and I will investigate further:

- WooCommerce payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by dansmithvl** [comment]
Thanks Mathew a bit later. Cheers

**Comment by dansmithvl** [comment]
Hi Mathew,

Please find attached.

Thanks Danny

![payment source](https://user-images.githubusercontent.com/65151058/81639114-ec1f0700-9412-11ea-89d1-fab91a61c130.PNG)

![api](https://user-images.githubusercontent.com/65151058/81639088-d7427380-9412-11ea-8c5b-f4cb228d7c56.PNG)

![websites apps](https://user-images.githubusercontent.com/65151058/81639131-f7723280-9412-11ea-961e-491641176aef.PNG)

![WP payment settings](https://user-images.githubusercontent.com/65151058/81639138-fd681380-9412-11ea-8340-6c00d7ac291f.PNG)

**Comment by matthewrgourd** [comment]
Hi @dansmithvl you should have received an email from us explaining what to do to get the payment source active. This would have gone to your registered email address. If not, please send details of your query to support@vivawallet.com or call one of the below customer service numbers. Thanks!

<table><tr><th>Country</th><th>Phone number</th>
  <tr><td>Belgium</td><td>(+32) 2342 0790</td></tr>
    <tr><td>Cyprus</td><td>(+357) 2403 0211</td></tr>
    <tr><td>France</td><td>(+33) 1876 50765</td></tr>
    <tr><td>Greece</td><td>(+30) 21 1760 4000</td></tr>
    <tr><td>Netherland</td><td>(+31) 2089 05503</td></tr>
    <tr><td>Romania</td><td>(+40) 3122 96150</td></tr>
    <tr><td>UK</td><td>(+44) 20 3734 7770</td></tr>
    <tr><td>Portugal</td><td>(+351) 3 0050 9059</td></tr>
</table>

**Comment by dansmithvl** [comment]
Hi Mathew,  Yes below and was set up as per.

Thanks Danny

Please find attached the API documentation below.

This should be given to your developer in order to complete the integration.

https://developer.vivapayments.com/

Use the picture attached in order to find your unique merchant ID & API key.

Let me know if you have questions.

Kind regards,
