### ISSUE TITLE
Error "red button with cross" with simple checkout in Prestashop

### ISSUE THREAD

**Issue by IlPizza79** [VivaPayments/API#1673]
Hi, I'm using simple checkout in Prestashop. This morning one of my customer sent me this picture:
![viva-error](https://user-images.githubusercontent.com/48421419/81549331-db24b600-937e-11ea-8f4b-1e9fd47b6081.jpg)

He said he fills in his card details like he always does, but then the button turns red with a cross and he can't go further with his payment. Since he got no alert or warning, can you please tell me what's the problem with his payment?
Thanks :-)

**Comment by matthewrgourd** [comment]
Hi @IlPizza79 sounds like his card is being declined. In order for me to check further, can you let me have your live website address and trading name?

**Comment by IlPizza79** [comment]
Hi, thank you for your answer.
My website is a bit "unusual", is there a way to send you those details privately?
Thanks :-)

**Comment by matthewrgourd** [comment]
Hi @IlPizza79, sure, please use my email address: mgourd@vivawallet.com. Thanks!

**Comment by IlPizza79** [comment]
Thank you, I've just sent details by mail.

**Comment by matthewrgourd** [comment]
Hi @IlPizza79 I just tried a payment with a card with no funds and everything seems to be working fine. I also checked your account and can't see any problems. The one thing I noticed is that the card end date has to be entered mm/yy and some autocomplete mechanisms seem to be filling it with mm/yyyy. If a customer of yours has an issue, please get them to replace the 'valid to' date in the format mm/yy. Thanks!

**Comment by IlPizza79** [comment]
> Hi @IlPizza79 sounds like his card is being declined.
Is there somewhere a transaction log where I can check for error in transactions?
Thanks!
