### ISSUE TITLE
Making a transaction and a Pre-authorization

### ISSUE THREAD

**Issue by bonucci** [VivaPayments/API#1674]
Hello, i have a question, i need to issue a payment and also a pre-authorization for a insurance for rental products, my question is regarding the amountToken, im using the Online Checkout (Native Checkout v2 3DS),  for example to process the first payment i need to issue a tokenAmount when the user needs to click in the form to accept, than i need to create another tokenAmount for the insurance where the user needs to click in the form to accepts again, is there a way in doing this task in only one step or one time? Making the Pre-authorization (rental assurance) and the payment  (sale products) ?

**Comment by matthewrgourd** [comment]
Hi @bonucci this is currently under discussion. I'll get back to you once I have an answer...

**Comment by matthewrgourd** [comment]
Hi @bonucci I don't believe we have a solution available for you at this time. Please update this issue if you've heard any different and I'll talk to the dev team again.
