### ISSUE TITLE
Magento 2.3.5 frontend session messages not working with plugin enable

### ISSUE THREAD

**Issue by rjgc** [VivaPayments/API#1675]
Hi. I'm having a weird bug, when i enable the Viva Payments Plugin on Magento 2.3.5 the session success/error messages on the fontend forms(e.g. contact form, login page) aren't working, I'm using Porto template and also tried the Plugin on Magento 2.3.4 with the same effect.

![viva_wallet](https://user-images.githubusercontent.com/5764679/81558547-ca2b7300-9385-11ea-9601-d6f6a1658ff9.PNG)

Can you guys check it? Thanks

**Comment by matthewrgourd** [comment]
Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- Magento payment module settings (mask your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by rjgc** [comment]
Hi Matthew, thanks for the quick reply

I didn't touch the default settings of the plugin yet, i'm waiting for the credentials but i'll report back when i have them set. Just a note, i have the plugin disabled in the settings but the problem persits, the only way to solve it is by disabling the plugin using the command line.

**Comment by matthewrgourd** [comment]
Hi @rjgc I'll await a further update from you. I've not heard of that problem before, but thanks for letting me know!

**Comment by matthewrgourd** [comment]
Hi @rjgc, this is now noted. Thanks again!
