### ISSUE TITLE
Change the name on SMS notification

### ISSUE THREAD

**Issue by andreas-digitalminds** [VivaPayments/API#1676]
On the OTP notification is the Merchant name and on the payment the Trade name. How to control what is going to be written? 
![2020-05-12_15-32-26](https://user-images.githubusercontent.com/22727682/81691750-fb7b7000-9465-11ea-8a0d-b0889e779506.jpg)

**Comment by matthewrgourd** [comment]
Hi @andreas-digitalminds you've explained the current behaviour. What would you prefer to happen in the scenario you mention?

**Comment by andreas-digitalminds** [comment]
We 'd like to control what is going to appear.

**Comment by matthewrgourd** [comment]
@andreas-digitalminds can I have your trading name and merchant, here, so I can copy and paste into our system and look up your account? I don't believe your legal name can be changed but the trading name can be amended by calling one of our customer service team numbers:

<table><tr><th>Country</th><th>Phone number</th>
  <tr><td>Belgium</td><td>(+32) 2342 0790</td></tr>
    <tr><td>Cyprus</td><td>(+357) 2403 0211</td></tr>
    <tr><td>France</td><td>(+33) 1876 50765</td></tr>
    <tr><td>Greece</td><td>(+30) 21 1760 4000</td></tr>
    <tr><td>Netherland</td><td>(+31) 2089 05503</td></tr>
    <tr><td>Romania</td><td>(+40) 3122 96150</td></tr>
    <tr><td>UK</td><td>(+44) 20 3734 7770</td></tr>
    <tr><td>Portugal</td><td>(+351) 3 0050 9059</td></tr>
</table>

**Comment by andreas-digitalminds** [comment]
Is it safe to give these information here?

Because we are running several eshops from the same merchant account we d like to have control which name appeared from each eshop.

**Comment by matthewrgourd** [comment]
It's ok I've found you!

**Comment by matthewrgourd** [comment]
Unfortunately you cannot control this except to change the trading name to the same as your merchant name (at account level). To do that you would need to speak to our customer service team. I'm sorry there is not an easier answer...

**Comment by andreas-digitalminds** [comment]
Thank you Matthew, really appreciate your effort.
