### ISSUE TITLE
Woocommerce issue "couldn't obtain access token please validate your API V.2 credentials!"

### ISSUE THREAD

**Issue by GJFox1972** [VivaPayments/API#1677]
any ideas on how I can resolve this, please

**Comment by matthewrgourd** [comment]
Hi @GJFox1972 , are you using our [plugin for WooCommerce](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) or a custom solution through our API? I don't recognize that error message.

**Comment by GJFox1972** [comment]
I am using your plugin 

I also have sage too 

A few weeks ago the plugin disabled it self from memory stating a php was no longer valid so it was deleted 

i switched to a plugin of my own and it still gave the same error and this afternoon i switched back to your plugin and i received messages from customer who are still getting this pop up 


could it be a conflict between both gateways ?

**Comment by matthewrgourd** [comment]
Hi @GJFox1972 you should make sure all other payment plugins are completely removed if you wish to use our official one.

**Comment by GJFox1972** [comment]
Thank you matthew 

I had another free plugin that offered the ViVa wallet gateway and their plugin has been deleted hopefully this will have been the issue 


Regards 
Grant Fox
📞 07789882255
Vulpes Media limited T/A Dreambikecompetition™
reg 11794512
