### ISSUE TITLE
PHP Version and JSON_BIGINT_AS_STRING

### ISSUE THREAD

**Issue by nmichalakis** [VivaPayments/API#1678]
[This is an issue for commece_vivawallet module for Drupal (7.x) + Commerce 1.x ]
Hi, i had an issue with JSON_BIGINT_AS_STRING and PHP Version 5.5.9-1ubuntu4.21.
I found this https://stackoverflow.com/questions/19520487/json-bigint-as-string-removed-in-php-5-5 and changed commerce_vivawallet.module file from line 182 - 200 (try - catch block) with this code
```
try {
    if (version_compare(PHP_VERSION, '5.4.0', '>=') && !(defined('JSON_C_VERSION') && PHP_INT_SIZE > 4)) {
      	$resultObj=json_decode($response, false, 512, JSON_BIGINT_AS_STRING);
    } 
      else {
    $max_int_length = strlen((string) PHP_INT_MAX) - 1;
    $json_without_bigints = preg_replace('/:\s*(-?\d{'.$max_int_length.',})/', ': "$1"', $response);
    $resultObj = json_decode($json_without_bigints);
		}
	} catch( Exception $e ) {
		throw new Exception("Result is not a json object (" . $e->getMessage() . ")");
	}
```

![Screenshot 2020-05-13 at 09 39 47](https://user-images.githubusercontent.com/25632631/81779860-34ffba00-94fe-11ea-9d9f-c4f97a0ffa8e.jpg)

**Comment by matthewrgourd** [comment]
@nmichalakis Thanks for this!
