### ISSUE TITLE
viva wallet partial refund is not working

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1679]
Hi, 
i tried full refund , its working fine,
but for partial refund(i gave the amount which is less than the succesful payment) it not working.

https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/delete

Regards,
ITCs

**Comment by matthewrgourd** [comment]
Hi @chennurubharath I believe partial refund is only possible after the funds have cleared into the account (approx 24 hours)...

**Comment by chennurubharath** [comment]
thanks @matthewrgourd
