### ISSUE TITLE
payment platform doesn't work

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1680]
Hi @matthewrgourd, I have a problem with this customer: 02649662Q Rodrigo Christian Marzan Díaz. He tells me the next:
  
We've had orders in the past that have had problems to be completed, and as I'm finding out where the problem was, I found that the payment platform doesn't work! Everything is correct until, when I send the bank code to check your identity, I introduce it and it gives me failure and doesn´t allow me to conclude the operation. I attach you a screenshot.

Thanks in advance.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/56823712/81812328-4361cc00-9526-11ea-8e91-f2801cae67e9.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada this is a card problem as indicated by the error message. Our platform is working correctly. The customer should contact their card issuer to see why their card has been declined.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd The problem keep on persisting, several clients tryied to pay with different card servers and continues the problem...

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada please let me know all the affected merchants by giving me their IDs on MS Teams and I will check for you.
