### ISSUE TITLE
virtual payments not working

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1681]
Hi again @matthewrgourd , I have another customer with similar problems. Client is Strategos commerce consuting S.L, B88328042. I submitt you the next link for looking the whole issue:

https://jira.viva.gr/jira/browse/CC-1284651

Thanks in advance

**Comment by matthewrgourd** [comment]
@Alvaroalconada this is already being handled by the customer care team. If they need my input, they will ask me. Please do not raise internal issues on our public GiHub site as it causes unnecessary duplication of effort. If you need to prompt me, use MS Teams instead!
