### ISSUE TITLE
viva wallet customer  wants refund, when merchant account dont have the enough balance  

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1682]
hi @matthewrgourd,

suppose customer paid 1000 pounds,After merchant transfered  1000 pounds to his bank, Now customer wants refund...how the customer get refund?

Regards,
Bharathkumar.c

**Comment by matthewrgourd** [comment]
Enough money has to be available in the Viva Wallet account in order to process the refund.
