### ISSUE TITLE
Card Errors

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1683]
Hi @matthewrgourd! I have a problem with this customer, Latin travel money Transfer SAU.

I attach you screenshot about the issue.

Thanks in advance
![latin travel problem](https://user-images.githubusercontent.com/56823712/81917801-f2a9ac00-95d5-11ea-9f08-7602df6c0135.jpeg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada the merchant has a payment source set up for the website pasarela.latintravelmt.com but the website is currently unavailable. The payment source settings in the merchant's Viva Wallet account are unrecognizable to me. Which of our online checkouts or e-commerce plugins is the merchant attempting to use? It doesn't look like anything official. Please find out more. Thanks!

**Comment by Pedrohernandezoss** [comment]
The website is currently available for you to help , thank you

**Comment by Pedrohernandezoss** [comment]
Costumer response of : direct turn

**Comment by matthewrgourd** [comment]
@Pedrohernandezoss http://pasarela.latintravelmt.com still isn't working. Please provide the right web address if that isn't the one...

**Comment by Pedrohernandezoss** [comment]
https://girodirecto.latintravelmt.com/

**Comment by matthewrgourd** [comment]
Hi @Pedrohernandezoss which of our plugins or checkouts have they attempted to install or have they gone for a custom solution using our API? I need them to provide a lot more information before I can investigate...

**Comment by Pedrohernandezoss** [comment]
Technical: As request i inform you :

What we use for integration with Viva Wallet is a propietary tool developed with as.net , it is an own development 

We make use of your APIS to invoke the service after obtaining the request to the site :  

https://www.vivapayments.com/web/newtransaction.aspx?ref=????

Once the client completes the operation you will redirect us to our answer page , then we invoke the method https://www.vivapayments.com/api/orders/{pedidoid} to get the order status.

It is then where we see the order status comes "Stateld: 0" when expect to receive "Stateld": 3.

Below i send the responses receibed 

Best regards

**Comment by matthewrgourd** [comment]
Hi @Pedrohernandezoss please advise client that the latest information about implementing a native checkout solution incorporating our payment gateway is providing on the following page:

https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

This is fully PSD2 compliant and should be used in place of any previous approaches.

Thanks!

**Comment by Pedrohernandezoss** [comment]
Thank you Matt, have a nice day
