### ISSUE TITLE
Achieving SCA through Native/Simple Checkout

### ISSUE THREAD

**Issue by solatali** [VivaPayments/API#1687]
Sir, 

About closing Issue # 1685, I actually just got your message so that's why I created new issue to be able to briefly talk with you. 

I forwarded your response to tech. team and here's what they said. Please see attached screenshot. 
![image](https://user-images.githubusercontent.com/30649120/82207402-33315e80-9923-11ea-8dcd-247e44aa9250.png)

**They said there is no info on how to achieve "SCA" compliance when using Native/Simple checkout. They told me that they must handle SCA themselves. Can you guide about that specifically please ?

Sorry if this question is redundant but I'm just very confused about this whole thing. Also, please don't close this thread because I have to relay your response back to tech. team for their response.** 

Thank you

**Comment by matthewrgourd** [comment]
Hi @solatali, I closed the other issue because you were referring to a custom checkout which we can't give you direct help with only general advice.

Regarding Native Checkout v2, our most up-to-date checkout solution, this is fully SCA compliant, and native too, so I would recommend using that rather than Simple Checkout. Hope this helps!

**Comment by solatali** [comment]
Thank you for replying. Now, my tech. team is saying that they'll be developing the custom integration, but they need to implement SCA authentication themselves using API. 
Can you point me to a direction where in API it states how to authenticate using SCA ? Here's a response from the team, for which I'm attaching screenshot of conversation


![image](https://user-images.githubusercontent.com/30649120/82301374-95e13380-99d1-11ea-920d-cf2ff213c59d.png)

**Comment by matthewrgourd** [comment]
Hi @solatali, I'm not sure I understand fully the queries. However, I've trawled through some previous conversations with developers here at Viva Wallet. I can advise that we have to enrol each merchant to Modirum, our primary third-party 3DS vendor, who handle the SCA capability. There is a handover at some point which doesn't involve our platform. Beyond that, I'd need to get further details from my colleagues which may take a few days.

**Comment by wasi007gh** [comment]
Hey @matthewrgourd, we just want one simple thing that is recurring payments.
Once a card is authorized on viva wallet side then how can we charge again without redirecting again to viva wallet.

We use the WooCommerce Vivawallet Gateway by Viva Wallet plugin but there is not such handling in this plugin.

We also see there is Allow recurring payments settings in Viva API Access settings.

So how to achieve this ?

**Comment by matthewrgourd** [comment]
Hi @wasi007gh our plugin for WooCommerce is currently redirect only and doesn't handle recurring payments. We'll be working on a native one soon that supports subscriptions, but I'm afraid I don't have a launch date for you yet. Please feel free to check again in a few weeks. Sorry not to be of more help...

**Comment by wasi007gh** [comment]
Thankyou for the reply @matthewrgourd.

This leaves us with the option to build our own custom integration. So please share with us any documentation that contains information regarding SCA for Viva Wallet.

Thanks.

**Comment by matthewrgourd** [comment]
Hi @wasi007gh I'm afraid we don't have any further documentation beyond what is already shared on our [Developer Portal](https://developer.vivawallet.com/) and what I've advised in my previous responses. Have a good day.
