### ISSUE TITLE
Shopify payments does not save Store Token

### ISSUE THREAD

**Issue by loca2020** [VivaPayments/API#1688]
Hi,
I tried several times to inster and save the store token in the shopify viva wallet dashbord.
I delete the cache, did it from incognito mode and from different device, the results is the same, once saved it loads but it never updates and the store token remains empty, as shown in the screenshot.

Hope you can help.

Best,

![Screenshot (128)](https://user-images.githubusercontent.com/65592098/82300524-442baf80-99b7-11ea-9395-d9c61bb73ee2.png)

**Comment by matthewrgourd** [comment]
Hi @loca2020 sorry to hear this, looks like you may have entered the wrong value for Store Token. Please complete a [request form](https://forms.office.com/FormsPro/Pages/ResponsePage.aspx?id=11xgZwUpeU2CVq4fVCDCd_r-QSHD_PtMuAvap6OPapdUNkVITTFMNzMyWFdYSUJWNUw4MkxGSlhXRi4u) and we'll send you the correct token. Thanks!

**Comment by loca2020** [comment]
Thanks Matt for your answer, I just submitted the application.

**Comment by loca2020** [comment]
Hi Matt, 
we received the token, it is identical to the previous you sent us.
Therefore, the results could not be different.

**Comment by matthewrgourd** [comment]
@loca2020 but in the screenshot your store token (represented by the asterisks) is only 6 digits in length. That is not the store token as this is more like 30 digits long.

**Comment by loca2020** [comment]
The dots you see are there by default, the field is actually empty.
When I insert there I insert the 30 digits token you sent us, however it never saved.

We just spoke with the VivaWallet italian representative, he says that the token is blocked and that's why it does not work. 
Could you please check it and possibly solve the issue?

**Comment by matthewrgourd** [comment]
@loca2020 your Shopify payment source was inactive. Can you try now?

**Comment by loca2020** [comment]
Just tried but no luck, the field remain empty

**Comment by matthewrgourd** [comment]
So just to confirm, you're completing the field but it's clearing itself of the entry once you try to save the page? Is there an error message at all? Have you deactivated Shopify Payments? Is test mode deselected?

**Comment by loca2020** [comment]
Exactly, that is what happens.
No message at all, it seems to work but then you see the empty field.
I tried from different devices, activating and deactivating, from incognito mode, I deleted the caches, al l the available options in my knowledge

**Comment by matthewrgourd** [comment]
@loca2020 very strange. And I take it you've tried in more than one browser, e.g. Firefox if you were using Chrome and vice versa?

**Comment by loca2020** [comment]
Right, I tried from Chrome and Edge

**Comment by matthewrgourd** [comment]
So still no luck or are you ok now? Please provide an update or close the issue. Thanks!

**Comment by loca2020** [comment]
It's working now.
When we tried again it does not work immediately, then it started after a few hours.
