### ISSUE TITLE
API Transactions

### ISSUE THREAD

**Issue by fabiosicilia86** [VivaPayments/API#1689]
Hi,
I have implemented a web system where I download the POS transactions at the link "https://www.vivapayments.com/api/transactions".
I noticed that it only returns POS transactions to me.
I would also need outgoing transactions and therefore those with credit cards and bank transfers.
I'd like to know if it's possible.
Thanks and goodbye

**Comment by matthewrgourd** [comment]
Hi @fabiosicilia86 I think this depends on the payment sources set up in your Viva Wallet account. If there's one specifically for e-commerce transactions you would need to specify in the API call. An example is given in the [Transactions](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions) section of our Payment API documentation: 

>List of all transactions for a given Source Code for a specific date.
Example: GET `/api/transactions/?sourcecode=Default&date=2018-08-27`

**Comment by fabiosicilia86** [comment]
Hi,
I tried to insert the sourcecode (4 digits) but it continues to give me only POS transactions.
No negative transactions ... why?

**Comment by matthewrgourd** [comment]
Hi @fabiosicilia86 what's your trading name / website address so I can check your account?

**Comment by fabiosicilia86** [comment]
Here the account informations:
Nome depositato: SERVIZI IMPRESE SERGI
Indirizzo: VIA GIOVANNI EV DI BLASI 3A, 90135
Telefono
Partita IVA: IT05625560825
Numero di registrazione: PA414333
INFORMAZIONI DI CONTATTO DEL CONTO BUSINESS
Email di contatto: principalesergiorosciglione1943@gmail.com
Email per le notifiche: sistemasergiorosciglione1943@gmail.com

**Comment by matthewrgourd** [comment]
Hi @fabiosicilia86 I can only see POS transactions on your account. Do you have any dates for when a web transaction was made?

**Comment by fabiosicilia86** [comment]
we are interested in being able to download the data of all purchases made with active cards on the Viva Wallet account. Not just POS transactions.
For example on 2020/05/20 there is a transaction with the card 537489XXXXXX4007 of -300 € but this is not found in the API

**Comment by matthewrgourd** [comment]
Hi @fabiosicilia86 I've checked your account and all the transactions for 2020/05/20 were POS so the info you're getting back from the API is correct, as far as I can tell...

**Comment by fabiosicilia86** [comment]
In the Viva Wallet platform I see a debit card transaction to this date ... I don't find it in the API

**Comment by fabiosicilia86** [comment]
There are debit card transactions also on 2020/05/19 with card number (*** 8667) but I can't find them in the API

**Comment by matthewrgourd** [comment]
@fabiosicilia86 I'm sorry, I can't see the transactions you're referring to in our CRM which means they definitely won't be findable via the API. When you say "There are debit card transactions also on 2020/05/19 with card number (*** 8667)" where are you viewing this info as there's nothing on the Viva Wallet platform that correlates to this. Likewise, there's nothing for 2020/05/20!
