### ISSUE TITLE
Αφαίρεση τρόπου πληρωμής μέσω τηλεφώνου

### ISSUE THREAD

**Issue by Natasamini** [VivaPayments/API#169]
Καλησπέρα,

Σε eshop site που υπάρχει τρόπος πληρωμής με vivapayment, κατά το checkout εκεί που γίνεται το redict σε link της vivapayment θα θέλαμε να απενεργοποιηθεί το πλαίσιο με το μήνυμα της επιλογή της πληρωμής με κάρτας μέσω τηλεφώνου (IVR). Πως γίνεται να το απενεργοποιήσουμε;

**Comment by defilerc** [comment]
Καλησπέρα @Natasamini ,

Η επιλογή αυτή μπορεί να αφαιρεθεί, αν κατά τη δημιουργία του create order βάλετε το optional parameter DisableIVR ίσο με true.

Περισσότερες πληροφορίες, μπορείτε να βρείτε εδώ: https://github.com/VivaPayments/API/wiki/Optional-Parameters

Ευχαριστούμε πολύ

**Comment by Natasamini** [comment]
To ίδιο ισχύει και για site με χρήση Woocommerce? Αν ναι, υπάρχει κάποιο παράδειγμα; Προσπαθησα να το περάσω σαν όρισμα, όπως το id της παραγγελίας, αλλά δεν λειτούργησε.

**Comment by defilerc** [comment]
Καλημέρα @Natasamini ,

Για περισσότερα παραδείγματα κώδικα σε διάφορες γλώσσες, όσον αφορά τη δημιουργία πληρωμής, μπορείτε να δείτε τη σελίδα: https://github.com/VivaPayments/API/tree/master/CreateOrder

Για τη χρήση εξωτερικών plugins, όπως για παράδειγμα για το Woocommerce που αναφέρετε, θα πρέπει να μιλήσετε με τους developers που έχουν αναπτύξει το συγκεκριμένο plugin διασύνδεσης με τη Viva Payments, καθώς αυτά δεν έχουν αναπτυχθεί από εμάς και δε μπορούμε να σας προσφέρουμε κάποια επίσημη υποστήριξη.

Ευχαριστούμε πολύ για την επικοινωνία

**Comment by Natasamini** [comment]
Καλημέρα σας, 

Εντάξει βρέθηκε η λύση. Τελικά στο plugin υπήρχε ένα array όπου προσθέτεις το όρισμα. Ευχαριστώ πολύ.
