### ISSUE TITLE
prestashop vivawallet

### ISSUE THREAD

**Issue by VickyFrag** [VivaPayments/API#1690]
hello

after the customer has placed the order

it does not send confirmation email to the customer

it does not return to aou website
it just stuck with a blank page

shouldn't been sent a email to the customer?
Processing in progress ?

thank you in advance

**Comment by matthewrgourd** [comment]
Sorry to hear this. Which version of PrestaShop are you using? In order for me to investigate further what your issue might be, please send through the following screenshots if you can:

- PrestaShop payment module settings (hide your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (hide API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by VickyFrag** [comment]
1) we are using prestashop  1.7.6.4
2) PrestaShop payment is the default
3) 
![98453757_2559297234337309_7](https://user-images.githubusercontent.com/52821240/82348157-297e2880-9a01-11ea-995c-dbed82da57a4.jpg)
![98034794_2015327635278438_9](https://user-images.githubusercontent.com/52821240/82348185-300ca000-9a01-11ea-8fd0-ff22e7e53412.jpg)

hope i understood right

i have no probelm sending you my admin backoffice settings of prestashop to login
(but not public..)

**Comment by matthewrgourd** [comment]
Hi @VickyFrag, I've checked the Payment Source 7421 in your Viva Wallet account and for PrestaShop 1.7 and above you should be using the following settings as outlined in the [relevant page](https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/) on our developer portal:

- **Success URL** – module/vivawallet/success
- **Failure URL** – module/vivawallet/fail

Please check and try again.

**Comment by VickyFrag** [comment]
UPDATE:
Ι have made the changes and things got even worst
now the customer's order  doesn't appear at all.

i had an order, pad with viva and  the customer callled me fuuk of anger

please check
waiting for your reply
thanx 
vicky

**Comment by matthewrgourd** [comment]
Hi @VickyFrag so our plugin worked for this customer? Or not. I'm unclear. I notice you have plenty of successful payments made on both your websites. Could it be that this customer had a card failure? That's more than likely the case.

**Comment by VickyFrag** [comment]
hi again

there is no problem with their card
their payment can been seen from the viva website
But from pretsashop's backoffice 
there is nothing

there is no order !
customers call me and inform me about the payment.
 i changed the 

    Success URL – module/vivawallet/success
    Failure URL – module/vivawallet/fail


to 
   Success URL – module/vivawallet/success.php
    Failure URL – module/vivawallet/fail.php



at least the order is placed
but as you understand this is no solution 
the initial problem   remains

**Comment by matthewrgourd** [comment]
Please let me have a time and date of a payment that has received at the Viva Wallet account end but not in PrestaShop. Or more than one if possible. I'll need to investigate further...

**Comment by VickyFrag** [comment]
![100376857_179448193391611_3632302379652612096_n](https://user-images.githubusercontent.com/52821240/82917027-83d83580-9f7b-11ea-8070-17d8833d6ab6.png)
![100555256_706665193432738_3026601709041352704_n](https://user-images.githubusercontent.com/52821240/82917036-863a8f80-9f7b-11ea-8908-aee951e78a2e.png)
![100768891_368661687426437_8187211820939870208_n](https://user-images.githubusercontent.com/52821240/82917040-876bbc80-9f7b-11ea-98b6-e2804cf3a825.png)

**Comment by matthewrgourd** [comment]
Hi @VickyFrag I see what you're saying. If you've not already done so, can you try setting up a webhook as this may provide better integration with PrestaShop: https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/#step-3-set-an-optional-webhook

**Comment by VickyFrag** [comment]
got an error
![100662716_976769279421717_5442711002783154176_n](https://user-images.githubusercontent.com/52821240/82920532-0fec5c00-9f80-11ea-9881-f6bb60a0f230.png)

**Comment by matthewrgourd** [comment]
Hi @VickyFrag, can you translate the error message into English? Sorry, my Greek is non-existent!

**Comment by VickyFrag** [comment]
![100710909_2954717851302473_5714138556339847168_n](https://user-images.githubusercontent.com/52821240/83116953-27892900-a0d5-11ea-841c-379dcb7d50a2.png)
![100662716_976769279421717_5442711002783154176_n](https://user-images.githubusercontent.com/52821240/83117014-38d23580-a0d5-11ea-9d2e-b1286471650e.png)

**Comment by matthewrgourd** [comment]
Hi @VickyFrag, I think some of your settings are wrong in the PrestaShop back office and this is affecting the ability to add a webhook. Can you send me a screenshot of the Viva Wallet module settings in PrestaShop, blanking out your Merchant ID and API Key? Thanks!

**Comment by VickyFrag** [comment]
![Uploading 2020-05-28_1736.png…]()

**Comment by VickyFrag** [comment]
![2020-05-28_1736](https://user-images.githubusercontent.com/52821240/83155702-2e7e5e80-a10a-11ea-95fa-c2fb3b7a6cb1.png)

**Comment by matthewrgourd** [comment]
Hi @VickyFrag can I just check that you want to give customers the option for instalments? Otherwise you should leave that field blank, I believe.

**Comment by VickyFrag** [comment]
ok
i left it blank
is saw you tried you made a purchase..
can you try again? 
just to make sure...

**Comment by matthewrgourd** [comment]
Hi @VickyFrag I just tried again. The redirect is working and I'm able to submit my payment details. However, I'm not being forwarded back to your site. Are you sure there aren't any more settings in PrestaShop for the Viva Wallet plugin other than what you sent through in your last screenshot? Regarding webhooks, are there any already set up in your account because you can only have one per account?

**Comment by VickyFrag** [comment]
i have access only to kaftania.gr
but as i can see form the viva backoffice there is no other  webhook

if you like i can give you access to my eshop to check  anything you want

please  have in mind that i have changed  the 

Success URL – module/vivawallet/success
Failure URL – module/vivawallet/fail

to
Success URL – module/vivawallet/success.php
Failure URL – module/vivawallet/fail.php

if i do it 

Success URL – module/vivawallet/success
Failure URL – module/vivawallet/fail

your order wont be placed in my eshop
but you will be charged

**Comment by matthewrgourd** [comment]
Hi @VickyFrag thanks for that info. Unfortunately I can't log in to your account on your behalf for security reasons and as a result of company policy. Can I trouble you for one more screenshot? I need the payment source settings from your Viva Wallet account (with payment source ID of 7421). Here is a screenshot of the dialog box with blank fields:
![NewPaymentSource](https://user-images.githubusercontent.com/44943019/83163667-325ab280-a103-11ea-951f-2d381527d2d2.png)
I'm sorry not to be able to solve things very quickly for you!

**Comment by VickyFrag** [comment]
![101393172_176830467058481_4787425110833233920_n](https://user-images.githubusercontent.com/52821240/83164469-ee70a900-a114-11ea-9345-a51cda90916a.png)

**Comment by VickyFrag** [comment]
i have made the other domain inactive  (i cannot delete it)
can you try again to make a purchase?

**Comment by matthewrgourd** [comment]
Hi @VickyFrag I don't think that has made any difference. Please see screenshot of what happens after I complete the payment screen:

![Screenshot 2020-05-28 at 17 19 26](https://user-images.githubusercontent.com/44943019/83166913-7bad0100-a107-11ea-8289-2d0c83f7964b.png)

I'm using a card with no funds but I should get forwarded to the failure message on your e-commerce site. So no point in trying to set up the webhook as the plugin isn't installed correctly. It's usually the Success / Failure URLs that are the problem. You said you tried 

- Success URL – module/vivawallet/success
- Failure URL – module/vivawallet/fail

Which is correct according to the documentation and I checked this recently. What exactly happened? If possible, can you switch back to the above settings and I'll try again?

**Comment by VickyFrag** [comment]
i made the changes

    Success URL – module/vivawallet/success
    Failure URL – module/vivawallet/fail
![viva](https://user-images.githubusercontent.com/52821240/83167750-2c6fcc00-a119-11ea-8391-0b1499b22098.png)

**Comment by matthewrgourd** [comment]
Now I'm getting the error message below:

![Screenshot 2020-05-28 at 17 39 47](https://user-images.githubusercontent.com/44943019/83169285-b6fcff00-a10a-11ea-89b5-e70a6fb55f22.png)

I will need to raise with the original plugin developer and get back to you.

**Comment by VickyFrag** [comment]
ok, 
waiting for your reply
thank you

**Comment by matthewrgourd** [comment]
Hi @VickyFrag, reply from the dev:

>If the merchant is using Prestashop 1.7 and has installed the correct module for that version, I would not be able to access the https://www.kaftania.gr/modules/vivawallet/webhook.php URL without getting a 404 error (as in the latest module correct link is https://www.kaftania.gr/module/vivawallet/webhook.php). So I would advise the merchant to check again what PrestaShop version is used, to remove any installed old Viva Wallet modules and to use the correct [latest version](https://developer.vivawallet.com/downloads/vivawallet1.7.zip) of the module.

**Comment by matthewrgourd** [comment]
Hi @VickyFrag please close this issue if solved. Thanks!

**Comment by VickyFrag** [comment]
well it is not solved
i installed the latest version of the viva module
my prestashop version is the latest

after many tryouts
it is still not working...

**Comment by matthewrgourd** [comment]
Hi @VickyFrag sorry to hear this. I'm feeding back your reply to a developer.

**Comment by matthewrgourd** [comment]
Hi @VickyFrag sorry about this but can you provide the following screenshots again if possible? We need to see what your current settings are:

- PrestaShop payment module settings (partially hide your Merchant ID and API Key).
- Viva Wallet payment source settings (include your browser's URL bar in the screenshot).
- Viva Wallet Websites / Apps_ page (include your browser's URL bar in the screenshot).
- API Access page (partially hide API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by VickyFrag** [comment]
![101663001_776576629542327_1889231568048750592_n](https://user-images.githubusercontent.com/52821240/83860432-ed98d200-a727-11ea-8f54-325fc191fafa.jpg)
![101687732_1206813682983211_7727232948230946816_n](https://user-images.githubusercontent.com/52821240/83860448-f1c4ef80-a727-11ea-8f38-6537e7f062d1.jpg)
![Uploading 102557341_1097781297287895_944305339493253120_n.jpg…]()

**Comment by VickyFrag** [comment]
![102794719_3018753431541417_853956785411719168_n](https://user-images.githubusercontent.com/52821240/83860523-073a1980-a728-11ea-917d-15738a135bc9.jpg)

**Comment by VickyFrag** [comment]
![102557341_1097781297287895_944305339493253120_n](https://user-images.githubusercontent.com/52821240/83860658-38b2e500-a728-11ea-8303-e53a4caf0e75.jpg)

**Comment by matthewrgourd** [comment]
Hi @VickyFrag thanks for sending those through. Please try the following:

**Payment source ->** 

Success URL – module/vivawallet/success
Failure URL – module/vivawallet/fail

**Payment source ->** 

domain name should include www.

Let me know how you get on. Thank you.

**Comment by VickyFrag** [comment]
no, unfortunately...

![103374862_590606661572010_2959781763196387328_n](https://user-images.githubusercontent.com/52821240/83886124-a7576900-a74f-11ea-828a-d98b06ab36a9.jpg)

**Comment by matthewrgourd** [comment]
Hi @VickyFrag sorry to hear this. I've checked the payment source settings for 3671 and unfortunately you've still got the wrong values for the Success/Failure URLs:

INCORRECT
modules/vivawallet/success
modules/vivawallet/fail

CORRECT
module/vivawallet/success
module/vivawallet/fail

Thanks!

**Comment by VickyFrag** [comment]
i did it 
even though the default folder for the modules in prestashop
is modules  not module

![2020-06-05_2109](https://user-images.githubusercontent.com/52821240/83909342-48a2e700-a771-11ea-8701-76c922ac3fb6.png)

still not working!

do you want my prestashop back office login accounts?
i will be happy to send them ( privately )

**Comment by matthewrgourd** [comment]
@VickyFrag from the latest screenshot sent through, I can see a typo in the Success URL (missing 'S'):

INCORRECT
module/vivawallet/succes

CORRECT
module/vivawallet/success

**Comment by matthewrgourd** [comment]
Hi @VickyFrag, please close issue if now solved. Thanks!

**Comment by julie-paris75** [comment]
Hello everyone, I am a little lost concerning the configuration of vivawallet on prestashop.1.7.6.9 ... In fact when I order on our site and place an order and that I choose as a means of payment vivawallet it displays me not the description of the product I bought I don't understand ... Can someone help me please it's been a week since I can solve the problem .... you can try to place an order you will see a lot of information missing on the payment page ... thank you very much
![Screenshot_20210105-104900](https://user-images.githubusercontent.com/77002117/103641833-a3443180-4f52-11eb-8338-295d7b8364b5.png)

**Comment by matthewrgourd** [comment]
HI @julie-paris75, what's your website address please? I think it is correct as the product description is not normally repeated on the Viva Wallet payment page. There is a unique reference instead.

**Comment by julie-paris75** [comment]
Oh thank you matthewrgourd

https://www.maplantation.com

**Comment by julie-paris75** [comment]
thank you for your help, I saw on a competitor's site that there was the description

**Comment by matthewrgourd** [comment]
I tried just now with a card with no funds. Our payment page is working as expected. There was a unique reference beginning 784**** – did that appear anywhere in your PrestaShop backoffice?

**Comment by julie-paris75** [comment]
No order in my admin
![Screenshot_20210105-133943](https://user-images.githubusercontent.com/77002117/103647437-9b3cbf80-4f5b-11eb-8991-bf177b593fa0.png)

😕

**Comment by julie-paris75** [comment]
the real problem is that the payment is made but in the.back office no.order

**Comment by matthewrgourd** [comment]
Hi @julie-paris75, ok, that's an issue. I just tried with a card with no funds so no payment is correct. Can you try with a card with funds? You can then refund immediately from within your [Viva Wallet back office](https://members.vivawallet.com/en-gb/signin). Let me know what happens in terms of orders.

**Comment by julie-paris75** [comment]
yes great, I will try

**Comment by julie-paris75** [comment]
Thank you very much for your help matthewrgourd, it works (:-)
