### ISSUE TITLE
Woocommerce stack on successful

### ISSUE THREAD

**Issue by AELCharis** [VivaPayments/API#1691]
Woocommerce: After successful payment, the customer cant sees the order number and the details. Its stacks on Your payment was successful.

**Comment by matthewrgourd** [comment]
Hi @AELCharis, I take it you're referring to our plugin for WooCommerce. Have you recently installed it and this is the exhibited behaviour, or have you been using it for a while. Could I have your trading name and website address, please?

**Comment by matthewrgourd** [comment]
No reply in 1 week so closing issue...
