### ISSUE TITLE
Problems with plunning in prestashop store.

### ISSUE THREAD

**Issue by joseout** [VivaPayments/API#1692]
Hello good Morning.
There are problems with the plunning in the store, the client when making the payment directs him to the page to put the data, once he enters them up to there everything correct, but when he gives the ok, the payment is not finalized or leaves in the store .
You can tell me how we can solve it.
Thank you.

**Comment by matthewrgourd** [comment]
Hi @joseout, sorry to hear this. Can you tell me if there's an error message the customer sees when unable to continue with payment?

**Comment by joseout** [comment]
Hi, thanks for the quick reply.
The truth is that I can not tell you the error that appears specifically since it is made by the client, I know that it does not complete, which does not indicate what error may come out.
The client can continue with the payment, once he gives the ok and it is not completed. At the moment I can not give you more information, I hope to be able to give you something more shortly.
Regards.

**Comment by matthewrgourd** [comment]
Closing as no reply. Please feel free to reopen but I will need a lot more information before I can investigate, starting with your e-commerce website address...
