### ISSUE TITLE
Mocule Not working properly with the back office

### ISSUE THREAD

**Issue by Allthejam** [VivaPayments/API#1693]
My issue is this, I have since got Vive wallet to work however it does NOT sync with my back office after customers make payments and yes money does go into my Viva wallet, the transactions do not show up in my back office making it very difficult to get the appropriate address and details not to mention the customer did not get any emails sent out or any recent purchases in his customer login area. I have to wait 24 hours for the transactions to show in the Vivawallet accounts and then get the Po numbers and cross-reference them in my back office with the recent activity and then create the order manually so the clients don't get and confirmation until at least 24 hours later and I am spending a lot of additional time doing it this way and I know I'm going to start missing things, this can't possibly be right. Any ideas or is this as good as the module gets?

Thank you

Allthejam...

**Comment by matthewrgourd** [comment]
Hi @Allthejam, can you remind me which e-commerce platform you're using? Thanks!

**Comment by Allthejam** [comment]
PrestaShop Version 1.7.6.3

**Comment by Allthejam** [comment]
My other question is this. Just something we're thinking about...
Can I have my own bespoke terminal made using the merchant ID to link to Vivawallet?

We have found some very good ones that work seamless with PrestaShop but we can't use because of a product we sell or terms and conditions that are not met, so can we get something made by a developer just for us and have Viva as our banking outlet? ? ?

Allthejam

**Comment by matthewrgourd** [comment]
Hi @Allthejam I believe better synching can be achieved between your Viva Wallet account and PrestaShop if you [employ a webhook](https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/#step-3-set-an-optional-webhook). Have you done that? 

On your second question, I'm afraid we don't provide bespoke solutions at this point in time. 

Thanks!

**Comment by Allthejam** [comment]
Yes, I have a webhook, the system would not go live until it was done, see the image attached. Any other ideas? ? ?

![webhook](https://user-images.githubusercontent.com/52738920/82656679-11cebc00-9c1c-11ea-83f7-675307bb2d4c.jpg)

**Comment by Allthejam** [comment]
As for the bespoke solution, If I had it made by a developer can we use the merch ID ? I'm not asking anyone there to make the bespoke module, just can we link it to Vivawallet if we make our own bespoke module.?

**Comment by matthewrgourd** [comment]
Feel free, our API is publicly available. The most up-to-date way of integrating is through our [Native Checkout](http://localhost:1313/online-checkouts/native-checkout-v2/). Regarding better synching with PrestaShop, it sounds as though our plugin needs improving which we will be looking at in due course.
