### ISSUE TITLE
Changing the success and failure url is not working

### ISSUE THREAD

**Issue by YannisPittakidis** [VivaPayments/API#1695]
Hi there

I am trying to change the success and failure URLs but it's not working.

The account is EL094163083

When I change the main url and the 2 URLs below it says pending.
Later it goes on active but the main url is the default by vivapayment.com

Check attachment
![Screen Shot 2020-05-22 at 12 38 53](https://user-images.githubusercontent.com/63146519/82654528-8d833580-9c29-11ea-9ef4-1d3864254ac3.png)

**Comment by matthewrgourd** [comment]
Hi @YannisPittakidis one initial observation is that your website address https://payments.hotelperrakis.com/ is currently unresolvable. Also, could you give me a bit more information about what it is you're attempting to do. Are you using our API and attempting a custom implementation of the Viva Wallet payment gateway?

**Comment by YannisPittakidis** [comment]
Hi there

I am trying to change the domain and the url’s (success and failure)
at the Websites/Apps - check screen shot.

I need them to be:

payments.hotelperrakis.com/return?success
payments.hotelperrakis.com/return?fail

When I click update the Default says pending so it’s ok.

When it turns to active the main domain turns back to “Vivapayments.com" default domain.

I' ve done this 6-7 times and it does the same thing.

What can we do?


PS. We are just running a script at https://payments.hotelperrakis.com/ <https://payments.hotelperrakis.com/> so it’s ok we tested and it’s working in test mode

**Comment by YannisPittakidis** [comment]
![Screen Shot 2020-05-22 at 16 33 31](https://user-images.githubusercontent.com/63146519/82673861-1fe80100-9c4b-11ea-9a7c-3a1e67cf0fdf.png)

**Comment by matthewrgourd** [comment]
I'm sorry @YannisPittakidis, i don't know what it is you're attempting to do. Are you referring to our [Developer Portal](https://developer.vivawallet.com/) for guidance on performing a custom implementation of our payment gateway? If so, please let me know which page(s) you're looking at. Thanks!

**Comment by matthewrgourd** [comment]
Hi @YannisPittakidis thinking about this you need to [add a new payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) rather than using the default one. If you do this, the problem you describe won't occur.
