### ISSUE TITLE
payment clearance in live  account

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1697]
hi @matthewrgourd ,

pls let me know ,

1) after login to vivawallet account  where we can see transaction failed list 
2)  in response data :-   StatusId:"E"  and  "ErrorCode":502,"    but after login to  vivawallet account  its showing  payment clearance
3) what mean by  payment clearance

The response 
{"Emv":null,"Amount":2.04,"StatusId":"E","CurrencyCode":"826","TransactionId":"972600c4-0b1c-4e1c-b712-8e42cbac9009","ReferenceNumber":655812,"AuthorizationId":null,"RetrievalReferenceNumber":"014405655812","ThreeDSecureStatusId":1,"ErrorCode":502,"ErrorText":"Transaction failed","TimeStamp":"2020-05-23T08:22:56.5458934+03:00","CorrelationId":null,"EventId":10200,"Success":false}

4)what is mean by eventId value  =  10200  in above response.

live account payment clearnace screen shot attachemt below, 

Regards,
ITCS

![vivawallet1](https://user-images.githubusercontent.com/61449311/82726374-4ff1db80-9d01-11ea-9f5c-004855fb79cc.png)

**Comment by matthewrgourd** [comment]
Before I go any further, which of our checkouts are you attempting to implement? Is it [Native](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) or [Simple](https://developer.vivawallet.com/online-checkouts/simple-checkout/)?

**Comment by chennurubharath** [comment]
we are implemented Simple checkout.

**Comment by matthewrgourd** [comment]
Can you remind me of the Merchant ID if you're testing on demo, or company name / registration number if using production?

**Comment by chennurubharath** [comment]
hi, 
Trade name
EFILE READY LIMITED
Registration date
19/02/2020

**Comment by matthewrgourd** [comment]
Hi @chennurubharath, please see my responses below:

1. I believe our banking app doesn't currently show payment failures but I'm checking with a developer for you.
2. I can see only a failed transaction on 2020-05-23. However, this shouldn't be possible if you're getting a 502. Can you share with me a copy of the corresponding request blanking out any secure info?
3. Payment clearance is when the funds are available as opposed to being in the process of being cleared.

**Comment by chennurubharath** [comment]
Hi, @matthewrgourd ,

following transaction merchant account showing payment clearance

27/05/2020
1) amount £12.00
2) amount £12.00

26/05/2020
1) amount £48.96
2) amount £121.20

23/05/2020
1) amount £2.04

13/05/2020
1) amount £2.40
Please find the below Response for date :23/05/2020 1) amount £2.04

{"Emv":null,"Amount":2.04,"StatusId":"E","CurrencyCode":"826","TransactionId":"972600c4-0b1c-4e1c-b712-8e42cbac9009",
"ReferenceNumber":655812,"AuthorizationId":null,"RetrievalReferenceNumber":"014405655812","ThreeDSecureStatusId":1,"ErrorCode":502,
"ErrorText":"Transaction failed","TimeStamp":"2020-05-23T08:22:56.5458934+03:00","CorrelationId":null,"EventId":10200,"Success":false}


Please find the below  attatchments,

![](https://lh3.googleusercontent.com/-CiXR_Iy6O5I/Xs5i_XsqNTI/AAAAAAAAAR0/vPwDjsv4GXAMfwp6l0HcN44km84iF_7hQCK8BGAsYHg/s0/26-05-2020.png)

![](https://lh3.googleusercontent.com/-GYlSwQCKO3s/Xs5jCilS8yI/AAAAAAAAASA/YymTCPwNetoH02VKfWaXv9yeFFLQM5ITACK8BGAsYHg/s0/23-05-2020.png)
![aa](https://user-images.githubusercontent.com/61449311/83021927-5f965a80-a048-11ea-9716-5acac6295b19.png)

**Comment by chennurubharath** [comment]
Hi @matthewrgourd , we had been waiting for your  response, Kindly reply as soon as possible....

**Comment by matthewrgourd** [comment]
Hi @chennurubharath I previously asked for a log of the request you're making to return the response with the error. Can you do that for me, please? I can't investigate further without this.

**Comment by pavithra-itcs** [comment]
Please find the below Response for date :23/05/2020 1) amount £2.04
{"Emv":null,"Amount":2.04,"StatusId":"E","CurrencyCode":"826","TransactionId":"972600c4-0b1c-4e1c-b712-8e42cbac9009",
"ReferenceNumber":655812,"AuthorizationId":null,"RetrievalReferenceNumber":"014405655812","ThreeDSecureStatusId":1,"ErrorCode":502,
"ErrorText":"Transaction failed","TimeStamp":"2020-05-23T08:22:56.5458934+03:00","CorrelationId":null,"EventId":10200,"Success":false}

for remaining records we don't have a log... but after login into a live account, we could able to see payment clearance.

**Comment by matthewrgourd** [comment]
@pavithra-itcs please send me the code you're using that gives this result otherwise I can't help...you can email me directly at mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs I've sent the code through to our dev team for checking...

**Comment by matthewrgourd** [comment]
HI @pavithra-itcs one of our developers has had a look at the response and points out that amount should always be returned in the currency's smallest unit of measurement. It must always be greater than 30 (which is the minimum amount you can charge with Viva Wallet).

>For example, if you want to create a payment for €100.37, you need to pass the value "10037".

I don't know if this helps at all? I'm getting another dev to check the Java code...

**Comment by pavithra-itcs** [comment]
Thanks. We are taking care of that currency conversion part.

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs I've also been advised by our development team that a failed transaction normally happens if the customer gives a wrong CVV or expiry date, for example.

**Comment by pavithra-itcs** [comment]
ok Thanks

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, if your questions are now answered adequately, please close the issue. Thanks!
