### ISSUE TITLE
What is Payments Clearance and Sales Clearance Cards?

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1698]
Hi,

What is Payments Clearance ? When this situation will occur. Please let us know the details regarding this.

And also let us know what is Sales Clearance Cards?

Regards,
itcs

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs Viva Wallet accounts offer a free daily sales clearance which means customer payments to merchants for products and services are cleared the next day.
