### ISSUE TITLE
EventId -  10200

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1699]
Hi,

We are not able to find any information for this EventId(10200) . Please let us know more details regarding this.

**Comment by matthewrgourd** [comment]
In what context? Sorry, I need more info. Could I have the full request / response logs, please?

**Comment by pavithra-itcs** [comment]
Hi Matthewrgourd,

I tried Simple checkout API and I got the response given below.
The response
{"Emv":null,"Amount":2.04,"StatusId":"E","CurrencyCode":"826","TransactionId":"972600c4-0b1c-4e1c-b712-8e42cbac9009","ReferenceNumber":655812,"AuthorizationId":null,"RetrievalReferenceNumber":"014405655812","ThreeDSecureStatusId":1,"ErrorCode":502,"ErrorText":"Transaction failed","TimeStamp":"2020-05-23T08:22:56.5458934+03:00","CorrelationId":null,"EventId":10200,"Success":false}

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs the transaction failure reason is "Invalid CVV". Hope this helps!

**Comment by pavithra-itcs** [comment]
okok. Thanks
