### ISSUE TITLE
αλλαγή IP (κάπως άμεσο ζήτημα) 

### ISSUE THREAD

**Issue by stonekgraff** [VivaPayments/API#170]
γεια σας
εχω ενα θεματάκι , έχω κανει μεταφορά ενός πελάτη το σαιτ του σε νέο σερβερ και τώρα η εφαρμογή της hellaspay προκαλεί γενικό σφάλμα (λευκή σελίδα) καθώς εντοπίζει ότι η IP του διακομιστή δεν αντιστοιχεί στην επιτρεπόμενη για το e-shop:
-------------------------------------------------------------------------------------------------------------------------------------------
[22-Sep-2016 12:04:26 UTC] PHP Fatal error: <br>The encoded file <b>/home/digitop/public_html/wp-content/plugins/hellaspay-for-woocommerce2/wc-hellaspay.php</b> is not permissioned for 185.25.21.31 in Unknown on line 0

τι κάνουμε σε αυτην την περίπτωση ?
μπορούμε να δηλώσουμε την νεα ip του νεου σερβερ κάπου?

**Comment by defilerc** [comment]
Καλησπέρα @stonekgraff ,

Το Viva Payments API δε χρησιμοποιεί IP restriction για να μπλοκάρει requests από συγκεκριμένες IPs. Εφ' όσον περνάτε τα merchant credentials σωστά, μπορείτε να επικοινωνήσετε επιτυχώς.

Παρακαλούμε βεβαιωθείτε πως δεν υπάρχει κάποιο δικτυακό θέμα από τη μεριά μας και πως ο νέος server που είναι hosted το site σας, μπορεί να δει επιτυχώς τα urls: http://demo.vivapayments.com για το demo περιβάλλον και https://www.vivapayments.com για το live, αντίστοιχα.

Ευχαριστούμε πολύ
