### ISSUE TITLE
css

### ISSUE THREAD

**Issue by renatoDragan** [VivaPayments/API#1700]
a want to make some changes in css. is posible? i can't change .container-header in simple checkout
thanks

**Comment by matthewrgourd** [comment]
Are you referring to Simple Checkout? You can't change the CSS directly as such. However, there are some styling settings within the [Configuration options](https://developer.vivawallet.com/online-checkouts/simple-checkout/#configuration-options):

data-vp-background-color | Sets button’s background colour. Default value: #030408. | Recommended
-- | -- | --
data-vp-color | Sets button’s text colour. Default value: #fff. | Recommended
data-vp-hover-background-color | Sets button’s background colour on mouse over. Default value: #1a2242. | Recommended
data-vp-hover-color | Sets button’s text colour on mouse over. Default value: #fff. | Recommended
data-vp-border-radius | Sets button’s roundness. Default value: 10px. | Recommended
data-vp-text | Sets button’s text. Default value: Pay (when data-vp-lang="en"). | Recommended
