### ISSUE TITLE
Update Magento Order Status Once Payment Has Cleared

### ISSUE THREAD

**Issue by Daniel-Rafique** [VivaPayments/API#1704]
I am currently using the VivaWallet Magento Extension.

I am looking for functionality that will update the order status in my store once payment has been cleared in VivaWallet from "pending_payment" to "processing".

I am using Magento 2.3.4

The steps to reproduce: 

1. Configure module to set order status to "pending_payment" for new orders
2. Once payment is cleared in VivaWallet at 12 midnight update Magento order and set the status to "processing".

The reason for this is simple, setting ALL new orders to "processing" will lead to external ERP systems importing orders BEFORE payment has been cleared and can lead to duplicate orders if a customer decides to change billing or shipping details. 

Due to the redirect that happens all orders are placed even if a customer has not entered credit card information so setting a order status of "processing" is impractical and will lead to orders being imported into an ERP that do not have a payment.

**Comment by matthewrgourd** [comment]
Hi @Daniel-Rafique I'm going to need to check with a developer and get back to you. Thanks!

**Comment by Daniel-Rafique** [comment]
Hi @matthewrgourd 
I checked my order this morning that was set to "pending_payment" and noticed that it had changed to "cancelled" This is not good because the payment has cleared in VivaWallet.

I had to set the status myself using the Magento API which is not ideal.

If you need additional dev resource I am available and can get to work on this ASAP.

**Comment by Daniel-Rafique** [comment]
Hi @matthewrgourd Any update on this??

**Comment by matthewrgourd** [comment]
Hi @Daniel-Rafique our Magento plugin for Magento 2.3.4 may be limited in the way that you mentioned as unfortunately it hasn't been updated for a long time. Please feel free to edit the code for your own custom installation if you wish. I'm afraid as a next step I'd have to point you in the direction of our [developer portal](https://developer.vivawallet.com/), in particular the [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api/) section.

**Comment by Daniel-Rafique** [comment]
@matthewrgourd Thanks, I'll look into it.

**Comment by matthewrgourd** [comment]
Hi @Daniel-Rafique, I've got feedback from the plugin author regarding your suggestion:

> in the event of all of the following being true:
> 
> - Extension / payment source set up correctly
> - "New Order Status" set to **Processing** in the extension settings
> - Successful transaction
> - Customer did not close his browser after the transaction / before getting returned to the store
> 
> ...the order status would not remain in **Pending** status and the order would not be cancelled.

Hope this makes sense. Please close the issue if you feel it has been answered adequately. Thanks!
