### ISSUE TITLE
simple  checkout 'Commission' is not updating in live

### ISSUE THREAD

**Issue by chennurubharath** [VivaPayments/API#1705]
Hi @matthewrgourd ,

in Live account, when customer paying through card, 'Commission' field in get transaction API call is not working, its given  "Commission":0.00 
But when we call through Curl  its showing  commission ammount.(https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/get)

is their time gape for calculating the commission?

Regards,
ITCs

**Comment by matthewrgourd** [comment]
Hi @chennurubharath I'm slightly confused as I don't see a `commission` field mentioned in the API documentation. Where did you find this?

**Comment by chennurubharath** [comment]
Hi @matthewrgourd,
When we call, get transaction(https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/get) with transaction id, "commission" field 
 available, Please find below respose JSON.


 
Following Customer  Detail response will come,    
{"Transactions":[{"Fee":0.00,"BankId":"NET_VISA","ParentId":null,"Switching":false,"Amount":XXX,"StatusId":"F","ChannelId":"2b56f2a2-2d26-4493-bfcXXXXXXX","MerchantId":"b85b1ede-d9a6-4cfe-a992-XXXX","ResellerId":null,"InsDate":"2020-05-26T19:53:14.807+03:00","CreatedBy":"","TipAmount":0.00,"SourceCode":"Default","TransactionId":"07a277fe-1b14-4040-acd-XXXX","**Commission":0.07**,"PanEntryMode":"01","MerchantTrns":"XXXXXXX","CustomerTrns":"The period of Month","IsManualRefund":false,"TargetPersonId":null,"AcquirerApproved":false,"SourceTerminalId":90000000,"AuthorizationId":"0973X","TotalInstallments":0,"CurrentInstallment":0,"ClearanceDate":"2020-05-27T02:39:13.493+03:00","ResellerSourceCode":null,"RetrievalReferenceNumber":"01471XXX","Order":{"OrderCode":2811959282568546,"ChannelId":"2b5XXXX2-2d26-4493-bfc4-9fb9fb612f48","ResellerId":null,"SourceCode":"Default","Tags":["Simple Checkout"],"RequestLang":"en-GB","ResellerSourceCode":null},"Payment":{"Email":"XXXX@* Connection #0 to host www.vivapayments.com left intact
gmail.com","Phone":null,"ChannelId":"2b56f2a2-2d26-4493-bfc4-9fb9fb612XX","FullName":"XXXXX XX","Installments":0,"RecurringSupport":false},"TransactionType":{"Name":"CardCharge","TransactionTypeId":5},"CreditCard":{"Token":"XXXXCD35904A6501EA422DB0E652B1A676C","Number":"465860XXXXXX3010","CountryCode":"GB","IssuingBank":"BAXXXXXXX","CardHolderName":"XXXXXX XXX","ExpirationDate":"2022-03-31T00:00:00","CardType":{"Name":"VISA","CardTypeId":0}}}]

**Comment by matthewrgourd** [comment]
Hi @chennurubharath can you share with me a copy of the exact request that gives you this response, blurring out any secure info?

**Comment by chennurubharath** [comment]
Hi @matthewrgourd ,

After loging to merchant account , we are able  see the commission value 

but Response json we are getting commission value as 0.00

please find the below response 
Transaction Response Data**{"Transactions":[{"Fee":0.00,"BankId":"NET","ParentId":null,"Switching":false,"Amount":12.00,"StatusId":"F","ChannelId":"2b56f2a2-2d26-4493-bfc4-9fb9fb612f48","MerchantId":"b85b1ede-d9a6-4cfe-a992-3ae583cab24f","ResellerId":null,"InsDate":"2020-05-25T20:08:54.03+03:00","CreatedBy":"","TipAmount":0.00,"SourceCode":"Default","TransactionId":"a589e1ec-7993-48e8-XXXX-d1678fe06124","**Commission":0.00**,"PanEntryMode":"81","MerchantTrns":"PS-XXXX01707","CustomerTrns":"The period of Month(12/05/2020)","IsManualRefund":false,"TargetPersonId":null,"AcquirerApproved":false,"SourceTerminalId":80000000,"AuthorizationId":"T77665","TotalInstallments":0,"CurrentInstallment":0,"ClearanceDate":null,"ResellerSourceCode":null,"RetrievalReferenceNumber":"014617797339","Order":{"OrderCode":960341XXXX304241,"ChannelId":"2b56f2a2-2d26-4493-bfc4-9fb9fb612f48","ResellerId":null,"SourceCode":"Default","Tags":["Simple Checkout"],"RequestLang":"en-GB","ResellerSourceCode":null},"Payment":{"Email":"chXXX@gmail.com","Phone":null,"ChannelId":"2b5XXX2a2-2d26-4493-bfc4-9fb9fb612f48","FullName":"Anita Riseborough","Installments":0,"RecurringSupport":false},"TransactionType":{"Name":"CardCharge","TransactionTypeId":5},"CreditCard":{"Token":"8773EDCFFXX62188782C5F3B4AFCE8B83E39A9DF0","Number":"518791XXXXXX0615","CountryCode":"GB","IssuingBank":"XXX Bank Plc","CardHolderName":"XXXX","ExpirationDate":"2022-10-31T00:00:00","CardType":{"Name":"MasterCard","CardTypeId":1}}}],"ErrorCode":0,"ErrorText":null,"TimeStamp":"2020-05-25T20:08:54.6660","CorrelationId":null,"EventId":0,"Success":true}


 





**the following request json:**

curl -v -X GET "https://www.vivapayments.com/api/transactions/XXXXX-4040-acd3-4c565aee840a" \
-H "Accept: application/json" \
-H "Authorization: Basic Yjg1YjFlZGUtZDlhNi00Y2ZlLWE5OTItM2FlNTgzY2FiMjRmOkR6ZXXXXXXXX"

**Comment by matthewrgourd** [comment]
Hi @chennurubharath, I'm not sure of the answer, I'l need to ask a developer and get back to you!

**Comment by matthewrgourd** [comment]
Hi @chennurubharath, apologies for the extended delay. Reply back from our developer is that commission is calculated from another system asynchronously. So you correctly identified that there is a gap time for the calculation.
