### ISSUE TITLE
Native Payment v1 - 405 Not Allowed

### ISSUE THREAD

**Issue by minamoto19** [VivaPayments/API#1706]
Hello.

Is the first version of the native payment still active?

I'm getting a 405 Not Allowed response after VivaPayments.cards.requestToken();

Thank you.

**Comment by matthewrgourd** [comment]
Hi @minamoto19, no, unfortunately not, but we have this page you can follow for updating to v2: https://developer.vivawallet.com/online-checkouts/migrating-from-native-checkout-v1/

**Comment by matthewrgourd** [comment]
Hi @minamoto19 [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) is supported, yes, but not v1.

**Comment by minamoto19** [comment]
This guide does not seem right
https://developer.vivawallet.com/online-checkouts/migrating-from-native-checkout-v1/

EG: What does this mean?
`cardHolderAuthPlaceholderId should contain the element ID which will hold the cardholder’s authentication window. cardHolderAuthInitiated signifies the start of a new authentication session and cardHolderAuthFinished its conclusion.`

I followed the guide above.

1. I created a new app with v2 native option in vivawallet backpanel
1b. Complete our OAuth 2 token generation procedure.
1c. Now I have a Bearer access token that last 60 mins.
1d. I kept the same payment form as mentioned in docs

2. Added reference to VivaPayments-2.0.js

3. I modified VivaPayments.cards.setup() as mentioned in docs 

4. Call requestToken

I get an error at this point:

`Uncaught TypeError: Cannot read property 'amount' of undefined
`

Why is that?

Is this migrate guide complete?

Best regards

**Comment by minamoto19** [comment]
Update 

> This guide does not seem right
> https://developer.vivawallet.com/online-checkouts/migrating-from-native-checkout-v1/
> 
> EG: What does this mean?
> `cardHolderAuthPlaceholderId should contain the element ID which will hold the cardholder’s authentication window. cardHolderAuthInitiated signifies the start of a new authentication session and cardHolderAuthFinished its conclusion.`
> 
> I followed the guide above.
> 
> 1. I created a new app with v2 native option in vivawallet backpanel
>    1b. Complete our OAuth 2 token generation procedure.
>    1c. Now I have a Bearer access token that last 60 mins.
>    1d. I kept the same payment form as mentioned in docs
> 2. Added reference to VivaPayments-2.0.js
> 3. I modified VivaPayments.cards.setup() as mentioned in docs
> 4. Call requestToken
> 
> I get an error at this point:
> 
> `VivaPayments: cardHolderAuthPlaceholderId is not defined`
> 
> `Uncaught TypeError: Cannot read property 'amount' of undefined `
> Why is that?
> 
> Is this migrate guide complete?
> 
> Best regards

OK figured that out.

I shouldn't just call VivaPayments.cards.requestToken() but migrate it in my actual event.

But now I get a 400 Bad request after calling VivaPayments.cards.requestToken.

Keep in mind that Im still in demo.

**Comment by matthewrgourd** [comment]
Hi @minamoto19, sorry to hear this. Reopening issue. I'll need to check with a dev and get back to you.

**Comment by minamoto19** [comment]
The issue was a wrong IP in vivawallet app settings.
I updated the domain with an IP and now I get the response expected.

Consider this closed.
