### ISSUE TITLE
Simple checkout pay button - auto click

### ISSUE THREAD

**Issue by lovetoast** [VivaPayments/API#1707]
is there any way to auto click the pay button for the simpel checkout so the pay form loads on page load?

**Comment by matthewrgourd** [comment]
Hi @lovetoast not as far as I'm aware out of the box – sorry!

**Comment by lovetoast** [comment]
OK thanks, no problem, 1 more question, is simple checkout restricted to a particular domain name?

> Hi @lovetoast not as far as I'm aware out of the box – sorry!

**Comment by matthewrgourd** [comment]
Hi @lovetoast no, it shouldn't be, but if you wish to use it, you need it enabled on your account. Have you requested this? If not, I need your merchant name and web address.

**Comment by lovetoast** [comment]
THanks, do you mean simple checkout itself or the domains? Simple checkout is already enabled so all good right?

**Comment by matthewrgourd** [comment]
All good in that case!
