### ISSUE TITLE
native checkout -  cannot generate access token

### ISSUE THREAD

**Issue by lovetoast** [VivaPayments/API#1709]
curl -X POST https://demo-accounts.vivapayments.com/connect/token -H 'Authorization: Bearer base64(clientid:secret)' -H 'Content-Type: application/json' -d '{"grant_type"="client_credentials"}'

Hi, using the above as per documentation to generate access token for native checkout v2, but doesn't work, says invalid token?

thanks

**Comment by matthewrgourd** [comment]
Hi @lovetoast you need to take `client:secret` and [encode](https://www.base64encode.net/) into a Base64 number. The cURL will then look something like the below. You actually opt for basic authorisation once you have encoded the client credentials:
```
curl -X POST 'https://demo-accounts.vivapayments.com/connect/token' \
-H 'Authorization: Basic ODl1bzFiZHR4dWI2OGRjbDkwYm5mZGJyMDFjOWZndW11cWF4NTAxbTlpODM1LmFwcHMudml2YXBheW1lbnRzLmNvbTptZDJuQ1I5elkzSEZBMmdQVTlaNVdSNDc2OGVhclM=' \
-F 'grant_type=client_credentials'
```
Hope this helps! Let me know how you get on...

**Comment by lovetoast** [comment]
Thanks, I did that but where I went wrong was the grant type, needed the -F, sorry!

I can now generate the native form BUT when I do I get a 401 when I submit the form, on the chargetokens endpoint?

**Comment by matthewrgourd** [comment]
Hi @lovetoast so that means you're doing something wrong with the authorisation process. In the previous step you should have received a response with the bearer token, e.g. 
```
{
    "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6IkpXVCIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCJ9.eyJuYmYiOjE1OTA2NDcwODUsImV4cCI6MTU5MDY1MDY4NSwiaXNzIjoiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJhdWQiOlsiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIiwiY29yZV9hcGkiXSwiY2xpZW50X2lkIjoiODl1bzFiZHR4dWI2OGRjbDkwYm5mZGJyMDFjOWZndW11cWF4NTAxbTlpODM1LmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiJGQkYxRTA5MC02NURFLTRDNzUtQjU4MC1EOUQ5QkM0OTRBRDIiLCJzY29wZSI6WyJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmciLCJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmc6Y2FyZHM6dG9rZW5zIiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6bmF0aXZlY2hlY2tvdXR2MiJdfQ.AzWAsQfNjGOBCmur8FdSM1lz4mzyYocFfpoednjquON5gpvgRqPU6u5ZIvkiktPGFmf2bDPBejjEuhnorU1602ed5ulWNvExp8K-CC9aHaG9Twjlfzl9MwGkSOXnUs5ARivtVVXhS_ArkhUfvbf7Ntr5jsL72XHywjHtGl1s0m5T_wNiqvdP2sgiWlgUaSy8_qOrA3HfajeSK3RSv-dIyNmGTKyI1Wfu07tOJLxThOpjgzqP658T8juQKq4mNqfa2NZ4aL4uTKSS_DRKXUI5zo5sPs8JSSBt0dUHWoOxu3ZZ91l6S0GQOkfZ_N-Y2Tr6cxGHcqReUsqt40AcBslIGQ",
    "expires_in": 3600,
    "token_type": "Bearer",
    "scope": "urn:viva:payments:core:api:acquiring urn:viva:payments:core:api:acquiring:cards:tokens urn:viva:payments:core:api:nativecheckoutv2"
}
```
So now you take the bearer token generated and add it to the second request. So using the above as an example the next piece of cURL would be as follows:
```
curl -L -X POST 'https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6IkpXVCIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCJ9.eyJuYmYiOjE1OTA2NDcwODUsImV4cCI6MTU5MDY1MDY4NSwiaXNzIjoiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJhdWQiOlsiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIiwiY29yZV9hcGkiXSwiY2xpZW50X2lkIjoiODl1bzFiZHR4dWI2OGRjbDkwYm5mZGJyMDFjOWZndW11cWF4NTAxbTlpODM1LmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiJGQkYxRTA5MC02NURFLTRDNzUtQjU4MC1EOUQ5QkM0OTRBRDIiLCJzY29wZSI6WyJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmciLCJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmc6Y2FyZHM6dG9rZW5zIiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6bmF0aXZlY2hlY2tvdXR2MiJdfQ.AzWAsQfNjGOBCmur8FdSM1lz4mzyYocFfpoednjquON5gpvgRqPU6u5ZIvkiktPGFmf2bDPBejjEuhnorU1602ed5ulWNvExp8K-CC9aHaG9Twjlfzl9MwGkSOXnUs5ARivtVVXhS_ArkhUfvbf7Ntr5jsL72XHywjHtGl1s0m5T_wNiqvdP2sgiWlgUaSy8_qOrA3HfajeSK3RSv-dIyNmGTKyI1Wfu07tOJLxThOpjgzqP658T8juQKq4mNqfa2NZ4aL4uTKSS_DRKXUI5zo5sPs8JSSBt0dUHWoOxu3ZZ91l6S0GQOkfZ_N-Y2Tr6cxGHcqReUsqt40AcBslIGQ' \
-H 'Content-Type: text/plain' \
--data-raw '{
    "authenticateCardholder": false,
    "Amount": 1000,
    "Cvc": "111",
    "Number": "4016000000040000012",
    "Holdername": "John Doe",
    "ExpirationYear": 2030,
    "ExpirationMonth": 10,
    "SessionRedirectUrl": "https://www.example.com"
}'
```
and the response would include a unique one-time only charge token:
```
{
    "chargeToken": "ctok_naMAZMrngUFRb7XvL46p642p-jc",
    "redirectToACSForm": "\r\n                <form id=\"acsForm\" method=\"POST\" action=\"https://demo.vivapayments.com/web/checkout/fakethreedsecurecardholderauthentication\">\r\n                    <input type=\"hidden\" name=\"pareq\" value=\"eyJMYW5nIjoiZW4iLCJBbW91bnQiOjEwMDAsIk1lcmNoYW50SWQiOiJmYmYxZTA5MC02NWRlLTRjNzUtYjU4MC1kOWQ5YmM0OTRhZDIiLCJTZXNzaW9uSWQiOiJlZTQ5MTAyYy0zMGQ1LTQwZjUtYWQxNy0zZDRmMjI0ODY3ZGMiLCJJbnN0YWxsbWVudHMiOjAsIkNhcmROdW1iZXIiOiI0MDE2MDBYWFhYWFgwMDEyIiwiQ3VzdG9tZXJUcm5zIjpudWxsLCJDdXJyZW5jeUNvZGUiOiI4MjYiLCJDYXJkRXhwaXJ5IjoiMjAzMC0xMC0zMVQxMjowMDowMCJ9\"/>\r\n                    <input type=\"hidden\" name=\"md\" value=\"ee49102c-30d5-40f5-ad17-3d4f224867dc\"/>\r\n                    <input type=\"hidden\" name=\"termUrl\" value=\"https://demo.vivapayments.com/web/checkout/threedsecurevalidation\"/>\r\n                </form> \r\n                <script>document.getElementById('acsForm').submit()</script>"
}
```

**Comment by lovetoast** [comment]
Yes, I probably was, I started a fresh template and all good now :)

Last question, promise, in the 3d secure, there is a select box and on iPhones when you click it it zooms in on the element but then doens't zoom out again, can we prevent the zooming in?

**Comment by lovetoast** [comment]
OK Matt, promise, last one, can I just native v2 3ds on http://localhost (or another protocol like ionic://localhost), it appears to be working? anything I need to be aware of?

**Comment by matthewrgourd** [comment]
@lovetoast can you provide a screenshot of the 3DS 'zooming in' problem? I think that's outside the Viva Wallet platform but I can check for you.

Local host may not work due to [CORS](https://www.codecademy.com/articles/what-is-cors) but you may be able to get round this by installing a plugin for your browser.

**Comment by lovetoast** [comment]
Hi Matt, I've resolved issue1, FYI there are a couple of things you can try but the easiest is user-scalable=0

I think it's fine (localhost), I've given it a few tests, do you need to manually approve native v2 on production, like the simple integration, or can I just switch it on?

**Comment by matthewrgourd** [comment]
Hi @lovetoast, cool, good to here.

Native Checkout v2 should be enabled on production by default for everyone. Obviously let me know if you have any problems. Thanks!

**Comment by lovetoast** [comment]
Thanks, I will of course :)

**Comment by lovetoast** [comment]
> Hi @lovetoast, cool, good to here.
> 
> Native Checkout v2 should be enabled on production by default for everyone. Obviously let me know if you have any problems. Thanks!

Hi Matt,

Quick one here, when you make an error on the card form for native (wrong expiry, card number etc). you can get 400 bad request with some data in the chargetoken request but there is no handler for this? At least, not that I can see in the sample code?

**Comment by matthewrgourd** [comment]
Hi @lovetoast, not sure I understand the question. I'll ask a dev and get back to you!

**Comment by lovetoast** [comment]
So essentially, when you make a transaction with the wrong expiry, it doesn't return a response? the customer doesnt know

**Comment by lovetoast** [comment]
> Hi @lovetoast, not sure I understand the question. I'll ask a dev and get back to you!

Think I solved this, the demo code does not have the failure code.

But I'm having another issue. Let's say you submit the wrong card details and then the right ones. When the right card details are processed, it then gives 2 charge tokens? and runs the success request twice?

**Comment by lovetoast** [comment]
Hi, just to confirm I've been able to replicate this about ten times now. There does seem to be a bug with the viva code, the "done" function is called multiple times with different charge tokens as the charge, only 1 is correct though.

I've confirmed that there is only one instance of the viva code on the page (i.e. I've not copied the code to initiate viva twice)

![image](https://user-images.githubusercontent.com/18267975/83941991-cf92a680-a7e7-11ea-8253-6842cf669c36.png)

**Comment by matthewrgourd** [comment]
Hi @lovetoast, sorry to hear about this error you've kindly pointed out. I will pass on to the development team and get back to you shortly.

**Comment by matthewrgourd** [comment]
Hi @lovetoast, reply from developer:

> Initial query: I think that [the developer] is calling to get the charge token when the form is submitted. This is incorrect. The charge token should instead be retrieved in the page load.

> Regarding the question on the card failure (a user tries a card. the card is inputted incorrectly and gets rejected, then tries again), the system should receive the same charge token..the charge token is not related to the card of the user and it is valid for some time until it gets expired.

Hope that makes sense! Let me know if not...

**Comment by lovetoast** [comment]
Hi Matthew,

Thanks for your reply, but with the native checkout, everything is done via ajax, so there is no page load? There is an e.preventdefault and so the page does not reload?


In addition to that, the same token is not sent, two are actually sent (or more than 2) (in regards to the card failure issue).

**Comment by matthewrgourd** [comment]
Hi @lovetoast I will feed back your reply to our dev team and see if I can get more info from them.

**Comment by matthewrgourd** [comment]
Hi @lovetoast, apologies if I asked for this info before, but please could I have your business name / company registration number so we can find you on our CRM.

**Comment by matthewrgourd** [comment]
Hi @lovetoast, our dev team is asking for your code / a full request log to check. Is that something you can provide? Obviously blur out any confidential info.

**Comment by lovetoast** [comment]
Hi Matt, easy peasy, it's actually the demo code on your website for native checkout!

**Comment by matthewrgourd** [comment]
Hi developer wants to know if you definitely completed step 2 under Prerequisites successfully:

>Complete our [OAuth 2 token generation](https://developer.vivawallet.com/authentication/#oauth-2-token-generation) procedure.

**Comment by matthewrgourd** [comment]
Hi @lovetoast, thanks for emailing me your Viva Wallet account details just now. 

Just to be clear, can you let me know if the below issue you've raised relates to the PHP code sample on our [Native Checkout documentation page](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/)? 

>Hi, just to confirm I've been able to replicate this about ten times now. There does seem to be a bug with the viva code, the "done" function is called multiple times with different charge tokens as the charge, only 1 is correct though.

**Comment by lovetoast** [comment]
The code below, the HTML/JS code, it makes multiple token requests, I could login remotely and show you?

`<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Native 3DS test</title>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://demo.vivapayments.com/web/checkout/v2/js"></script>
</head>

<body>

    <form action="" method="POST" id="payment-form">
        <div class="form-row">
            <label>
                <span>Cardholder Name</span>
                <input type="text" size="20" name="txtCardHolder" autocomplete="off" data-vp="cardholder"
                    value="Joe Blogs" />
            </label>
        </div>

        <div class="form-row">
            <label>
                <span>Card Number</span>
                <input type="text" size="20" name="txtCardNumber" autocomplete="off" data-vp="cardnumber"
                    value="4111111111111111" />
            </label>
        </div>
        <div class="form-row">
            <label>
                <span>CVV</span>
                <input type="text" name="txtCVV" size="4" autocomplete="off" data-vp="cvv" value="111" />
            </label>
        </div>
        <div class="form-row">
            <label>
                <span>Expiration (MM/YYYY)</span>
                <input type="text" size="2" name="txtMonth" autocomplete="off" data-vp="month" value="1" />
            </label>
            <span> / </span>
            <input type="text" size="04" name="txtYear" autocomplete="off" data-vp="year" value="2025" />
        </div>
        <button type="button" id="submit" (click)="submit($event)">Submit Payment</button>
    </form>
    <div id="threed-pane" style="height: 450px;width:500px">
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            const baseUrl = 'https://demo-api.vivapayments.com';
            VivaPayments.cards.setup({
                baseURL: baseUrl,
                authToken: '[access token]',
                cardHolderAuthOptions: {
                    cardHolderAuthPlaceholderId: 'threed-pane',
                    cardHolderAuthInitiated: function () {
                        $('#threed-pane').show();
                    },
                    cardHolderAuthFinished: function () {
                        $('#threed-pane').hide();
                    }
                },
                installmentsHandler: function (response) {
                    if (!response.Error) {
                        if (response.MaxInstallments == 0)
                            return;
                        $('#drpInstallments').show();
                        for (i = 1; i <= response.MaxInstallments; i++) {
                            $('#drpInstallments').append($("<option>").val(i).text(i));
                        }
                    }
                    else {
                        alert(response.Error);
                    }
                }
            });

            $('#submit').on('click', function (evt) {
                evt.preventDefault();
                VivaPayments.cards.requestToken({
                    amount: 3600
                }).done(function (data) {
                    console.log(data);
                    alert(data.chargeToken);
                });
            });

        });
    </script>
</body>
</html>`

**Comment by matthewrgourd** [comment]
Hi @lovetoast, I need to ask an important question. Did you replace the [access token] placeholder with a recently generated token? For instance, here's the same example but with a token generated against my demo account:
```
<title>Native 3DS test</title> <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script> <script type="text/javascript" src="https://demo.vivapayments.com/web/checkout/v2/js"></script>
<form action="" method="POST" id="payment-form">
    <div class="form-row">
        <label>
            <span>Cardholder Name</span>
            <input type="text" size="20" name="txtCardHolder" autocomplete="off" data-vp="cardholder"
                value="Joe Blogs" />
        </label>
    </div>

    <div class="form-row">
        <label>
            <span>Card Number</span>
            <input type="text" size="20" name="txtCardNumber" autocomplete="off" data-vp="cardnumber"
                value="4111111111111111" />
        </label>
    </div>
    <div class="form-row">
        <label>
            <span>CVV</span>
            <input type="text" name="txtCVV" size="4" autocomplete="off" data-vp="cvv" value="111" />
        </label>
    </div>
    <div class="form-row">
        <label>
            <span>Expiration (MM/YYYY)</span>
            <input type="text" size="2" name="txtMonth" autocomplete="off" data-vp="month" value="1" />
        </label>
        <span> / </span>
        <input type="text" size="04" name="txtYear" autocomplete="off" data-vp="year" value="2025" />
    </div>
    <button type="button" id="submit" (click)="submit($event)">Submit Payment</button>
</form>
<div id="threed-pane" style="height: 450px;width:500px">
</div>

<script type="text/javascript">
    $(document).ready(function () {
        const baseUrl = 'https://demo-api.vivapayments.com';
        VivaPayments.cards.setup({
            baseURL: baseUrl,
            authToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6IkpXVCIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCJ9.eyJuYmYiOjE1OTE3MTI5NzYsImV4cCI6MTU5MTcxNjU3NiwiaXNzIjoiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJhdWQiOlsiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIiwiY29yZV9hcGkiXSwiY2xpZW50X2lkIjoic2Zrc3U2OWRwMTYxMXA0OWpnMzBrYjM1N2lsZjEwMW5tcHFlcThrNDE1a2szLmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiJBMDYwOEVBRS1EODg1LTRFN0MtODIxNy1FOUE3QkFBMzM5NUIiLCJzY29wZSI6WyJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmciLCJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmc6Y2FyZHM6dG9rZW5zIiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6bmF0aXZlY2hlY2tvdXR2MiJdfQ.bq363Gb9MUYra543d2SFxgHFaX4pjbvDkg_UDsEA1ZjzRXHoJGFQ8vFo2CH4M0y0OUBMBAuAboYLDkS171dGkozbvnefO9CzUTeju2ruzuyMX2T2uNYmBBaEDCL1aW1K0gxwIi511F9NH0dQWTkAn12K6-F6ZzVMakzGHprBoPzlvQYebQYYRUwhO7WDZjRl173JU-BT8ABkeB1FYF0_3XVu-TxuLqZMDFDWLXQgRDWEGMaznDnfZe2rrgI-v57tDFv7F0G75JJwlVxznZzVm_QjV3EqAtlyvqwUVvLdObp1RxuiAwmNVvI_YxJWXo60CY1d4ou5YfRzZyjwQefePA',
            cardHolderAuthOptions: {
                cardHolderAuthPlaceholderId: 'threed-pane',
                cardHolderAuthInitiated: function () {
                    $('#threed-pane').show();
                },
                cardHolderAuthFinished: function () {
                    $('#threed-pane').hide();
                }
            },
            installmentsHandler: function (response) {
                if (!response.Error) {
                    if (response.MaxInstallments == 0)
                        return;
                    $('#drpInstallments').show();
                    for (i = 1; i <= response.MaxInstallments; i++) {
                        $('#drpInstallments').append($("<option>").val(i).text(i));
                    }
                }
                else {
                    alert(response.Error);
                }
            }
        });

        $('#submit').on('click', function (evt) {
            evt.preventDefault();
            VivaPayments.cards.requestToken({
                amount: 3600
            }).done(function (data) {
                console.log(data);
                alert(data.chargeToken);
            });
        });

    });
</script>
```
This appears to work fine.

**Comment by lovetoast** [comment]
Yes, now, if you try this:

add the fail callback

fail(function (data) {
                console.log(data);
                alert(data.chargeToken);
            });

Enter wrong details and click submit
Enter right details and click submit and you get 3d auth, but fail

and then process with correct details and correct 3d auth

(so that's 2 fails and 1 success without a page load)

you will find that you get 3 popups for a charge token

**Comment by matthewrgourd** [comment]
Ok, maybe this is because you're testing on demo. Unfortunately we only have a simulation of 3DS in the sandbox. For the real thing you'd need to switch to testing on live.

**Comment by lovetoast** [comment]
I have. I have simulated testing on both. Using a real card!

**Comment by matthewrgourd** [comment]
I see. Apologies, let me take away this query and come back to you.

**Comment by matthewrgourd** [comment]
Hi @lovetoast, the dev team would like details of the backend code you used to retrieve the access token used in the above HTML / JS snippets.

**Comment by lovetoast** [comment]
easy peasy again, the one that you helped me with:

```
curl -X POST 'https://demo-accounts.vivapayments.com/connect/token' \
-H 'Authorization: Basic ODl1bzFiZHR4dWI2OGRjbDkwYm5mZGJyMDFjOWZndW11cWF4NTAxbTlpODM1LmFwcHMudml2YXBheW1lbnRzLmNvbTptZDJuQ1I5elkzSEZBMmdQVTlaNVdSNDc2OGVhclM=' \
-F 'grant_type=client_credentials'
```

**Comment by matthewrgourd** [comment]
Hi @lovetoast, thanks for confirming. From our dev team:

>In this function that is being called three times in the alert. is the token different? Or it is the same?

**Comment by lovetoast** [comment]
Thanks, it is different

**Comment by matthewrgourd** [comment]
Hi @lovetoast, latest question from the dev team is, for us to investigate further, can you provide a correlation ID from the data object you're console logging?

**Comment by lovetoast** [comment]
> Hi @lovetoast, latest question from the dev team is, for us to investigate further, can you provide a correlation ID from the data object you're console logging?

Hi Matt, sorry for the delay:

1) What is a correlation ID?
2) Also, if I wish to do a native full integration on a Pax device (android app on pax that communicates with the viva payment app so we have an all in one device), what is the process?

**Comment by matthewrgourd** [comment]
Hi @lovetoast,

Please see below:

1. X-Viva-CorrelationId is found in the headers in your browser. Make the transaction, then to view the request or response HTTP headers in Google Chrome, take the following steps:

a. In Chrome, visit a URL, right-click, select **Inspect** to open the developer tools.
b. Select **Network** tab.
c. Reload the page, select any HTTP request on the left panel, and the HTTP headers will be displayed on the right panel.
E.g. 
![Screenshot 2020-06-15 at 11 06 07](https://user-images.githubusercontent.com/44943019/84645314-44589580-aef8-11ea-8764-a26d03a45359.png)

2. We have documentation here: https://developer.vivawallet.com/pos-api-integration/

Hope this helps!

**Comment by lovetoast** [comment]
1) Thanks, I'll try and get this over the next day
2) Thanks, I saw this but there is no info on how to actually load an APK for testing onto the PAX?
3) Is there an SDK for android/ios payments for ecommerce?
4) By native v2 sdk, can I take addresses for AVS verification?

**Comment by lovetoast** [comment]
> Hi @lovetoast,
> 
> Please see below:
> 
> 1. X-Viva-CorrelationId is found in the headers in your browser. Make the transaction, then to view the request or response HTTP headers in Google Chrome, take the following steps:
> 
> a. In Chrome, visit a URL, right-click, select **Inspect** to open the developer tools.
> b. Select **Network** tab.
> c. Reload the page, select any HTTP request on the left panel, and the HTTP headers will be displayed on the right panel.
> E.g.
> ![Screenshot 2020-06-15 at 11 06 07](https://user-images.githubusercontent.com/44943019/84645314-44589580-aef8-11ea-8764-a26d03a45359.png)
> 
> 1. We have documentation here: https://developer.vivawallet.com/pos-api-integration/
> 
> Hope this `helps!

Hi, any update on my last message?

**Comment by matthewrgourd** [comment]
You were going to send me a Correlation ID to help our developers solve the last problem?Regarding the hardware side of things, I'm afraid the documentation is what you see at https://developer.vivawallet.com/pos-api-integration/ and nothing more currently.

**Comment by matthewrgourd** [comment]
Hi @lovetoast if you can clarify your account name I should be able to ask those outstanding questions to the development team:

- How to load an APK for testing onto the PAX?
- Is there an SDK for android/ios payments for ecommerce?
- By native v2 sdk, can I take addresses for AVS verification?

**Comment by matthewrgourd** [comment]
Hi @lovetoast, I had a prompt response back about the above:

>- About loading the APK, in the first instance, you need to discuss with your Viva Wallet contact about the business case and get them to send it for business value evaluation with our Sales Director.
>- Unfortunately we don't have an SDK at present, only the API documentation.
>- Regarding the AVS query, the answer is not yet.

It would be helpful if I could have your account details so I can identify you on the CRM. If you don't wish to publish your business name here, please send to my email at mgourd@vivawallet.com referencing this issue (#1709). Thanks!
