### ISSUE TITLE
Αίτηση βοήθειας

### ISSUE THREAD

**Issue by tsoniotimaria** [VivaPayments/API#171]
Καλησπέρα ,
εχω πρόβλημα με το API. Το έβαλα στο plugin και λέει οτι είναι λάθος.

παρακαλώ βοηθήστε.

**Comment by defilerc** [comment]
Καλησπέρα @tsoniotimaria ,

Εφ' όσον χρησιμοποιείται κάποιο εξωτερικό plugin, θα πρέπει να επικοινωνήσετε με το δημιουργό του, καθώς δεν έχει αναπτυχθεί από τη Viva Payments και δεν παρέχεται κάποια επίσημη υποστήριξη γι' αυτό.

Αν πάλι, επιθυμείτε να κάνετε integration μόνοι σας, μπορείτε να βρείτε παραδείγματα κώδικα στη σελίδα https://github.com/VivaPayments/API καθώς και περισσότερες πληροφορίες για το API στη σελίδα https://github.com/VivaPayments/API/wiki 

Ευχαριστούμε πολύ
