### ISSUE TITLE
Amex acceptance issues

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1710]
Hi,

1) Our live customers try to pay using AMEX card but the transaction ended with an error.
In our viva wallet account its showing "AMEX not supported for your account".
Could you please enable our account to accept AMEX cards, what is the fee applicable for that??

2) Please let us know what all credit and debit cards accept by the Viva wallet.

Please find below the live account details
Trade name : EFILE READY LIMITED
Registration date : 19/02/2020
Merchant id: b85b1ede-xxxx-xxxx-xxxx-3ae583cab24f

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, you just need to enable it in your account settings ([Profile page](https://members.vivawallet.com/selfcare/en/profile)):

![Screenshot_2020-05-28_at_12_01_15](https://user-images.githubusercontent.com/44943019/83133740-35da4380-a0db-11ea-95cf-2eae69f5a59c.png)

**Comment by pavithra-itcs** [comment]
![profile-page](https://user-images.githubusercontent.com/61500322/83135853-1acff980-a104-11ea-97c0-6bb08e31ebf5.png)

**Comment by pavithra-itcs** [comment]
Checkbox we don't have. Please see the above image. Let us know what needs to be done.

**Comment by pavithra-itcs** [comment]
![profile-page](https://user-images.githubusercontent.com/61500322/83136297-dabd4680-a104-11ea-949e-880566bce954.png)

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs apparently you chose a category that is subject to [Amex restrictions](https://help.vivawallet.com/hc/en-us/articles/360001359837-I-m-experiencing-Amex-acceptance-issues-what-should-I-do-). We have changed that now. Please log out and log back in and check your Profile screen again.

**Comment by pavithra-itcs** [comment]
It's showing now. Thanks a lot.
