### ISSUE TITLE
Probleme Webhook

### ISSUE THREAD

**Issue by KeyTenDzn** [VivaPayments/API#1711]
Bonjour,

J'ai un gros problème je n'arrive pas a créer de WEBHOOK sur le site de vivawallet on me refuse systématiquement la demande en me disant " L'URL n'a pas pu être vérifié. Assurez-vous d'avoir entré une URL valide, accessible au public et conforme à ces instructions." 

Aidez moi s'il vous plait !!

<img width="609" alt="Capture d’écran 2020-05-28 à 12 28 00" src="https://user-images.githubusercontent.com/56676514/83130499-ad5da200-a0de-11ea-99aa-a42937da9e5f.png">

**Comment by matthewrgourd** [comment]
Hi @KeyTenDzn, sorry to hear this. In order to investigate further, please let me know which of our [e-commerce plugins](https://developer.vivawallet.com/e-commerce-plugins/) you've installed. Thanks!

**Comment by KeyTenDzn** [comment]
Hello @matthewrgourd  ! I use VivaWallet WooCommerce Gateway.

**Comment by KeyTenDzn** [comment]
on wordpress

**Comment by matthewrgourd** [comment]
Hi @KeyTenDzn thanks for letting me know that info. Can you also tell me your website address?

**Comment by matthewrgourd** [comment]
Hi @KeyTenDzn I've found your account now. It seems you've not completed installation of our plugin for WooCommerce correctly. You need to do this before the webhook can be set up. In the payment source settings for terpenesbrothers.com you have blank fields for the Success / Failure URLs: 

![Screenshot 2020-06-01 at 08 54 09](https://user-images.githubusercontent.com/44943019/83388146-d97e6900-a3e5-11ea-99cd-02751566f1f1.png)

These should be completed as follows: 

`index.php?wc-api=wc_vivawallet&vivawallet=success`
`index.php?wc-api=wc_vivawallet&vivawallet=fail`

Hope this helps!

**Comment by KeyTenDzn** [comment]
Yes ! Now it's good, thank for your help @matthewrgourd !
