### ISSUE TITLE
What is Payments Clearance

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1713]
Hi,

We are using Simple checkout API when the customer tries to pay. Payments Clearance is happening. Please let us know what it is. when this situation occurs. In our log file, no data is there to find out the customer details also but after login to our live viva wallet account, we are able to see payment clearance records. I have attached an image please have a look.

Everyday 2 to 3 payments are happening like this, we have no idea how to proceed.
They are our live users please kindly do the needful ASAP.

Please find below the live account details
Trade name : EFILE READY LIMITED
Registration date : 19/02/2020
Merchant id: b85b1ede-xxxx-xxxx-xxxx-3ae583cab24f

![Payment-Clearance](https://user-images.githubusercontent.com/61500322/83149071-50caa900-a117-11ea-95b4-0de600fead84.png)

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs I'm sorry, I don't understand. In the example above, I can't see the transaction listed in our CRM. Where is that screenshot from? Is it your Viva Wallet dashboard?

**Comment by pavithra-itcs** [comment]
Yes , it's our live Viva Wallet account dashboard Screenshot.

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs I've checked with our accounts team and using the example you gave with the figure of 22.08, you'll find it's the sum of all your transactions from the previous day, in this case 27/05. Hope this helps!

**Comment by pavithra-itcs** [comment]
Thanks
