### ISSUE TITLE
WooCoommerce & Δόσεις

### ISSUE THREAD

**Issue by dimmisel** [VivaPayments/API#1715]
Αντιμετωπίζω πρόβλημα με τις δόσεις. Ενώ εμφανίζονταν πιο παλιά, τώρα δε μας τις δείχνει καθόλου στο WooCommerce e-shop μας. Τις δόσεις μάλιστα τις έχουμε σετάρει όπως ακριβώς στο παράδειγμά σας.
![αρχείο λήψης](https://user-images.githubusercontent.com/22232266/83229269-53b5b000-a190-11ea-8368-aa5985030874.png)

Ακόμη, ένα άλλο πρόβλημα που αντιμετωπίζουμε είναι ότι στην ολοκλήρωση πληρωμής στο πάνελ σας, δεν εμφανίζεται λινκ ανακατεύθυνσης στο e-shop καθώς επίσης δε ανακατευθύνει αυτόματα τους πελάτες στο e-shop. Πριν από λίγο άλλαξα το integration method σε Redirection/Native Checkout v2 αλλά αυτό δεν άλλαξε την συμπεριφορά στο e-shop.

**Comment by matthewrgourd** [comment]
Hi @dimmisel, sorry to hear that the instalments functionality isn't working for you. In order to investigate further, please may I have your registered business name and website address. Thanks!

**Comment by dyrer** [comment]
Same problem here, installment are not working for me neither

**Comment by matthewrgourd** [comment]
Hi @dyrer could I have your business name and website address also? Thanks!

**Comment by dyrer** [comment]
Azalea Boutique at https://azaleaboutique.gr/

**Comment by matthewrgourd** [comment]
Hi @dyrer your payment source settings indicate you're using an unofficial Viva Wallet plugin. Please use the info on in our [WooCommerce plugin guide](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) to install and configure the correct extension. You'll need to de-activate and delete the current one first. Thanks!

**Comment by matthewrgourd** [comment]
@dimmisel when you're ready, can I have your business name and website address? I won't be able to continue investigating without these. Thanks!

**Comment by dimmisel** [comment]
youbath.gr & Υιοί Γ. Νικολαΐδη Ο.Ε.

**Comment by matthewrgourd** [comment]
Hi @dimmisel thanks for sending through those details. I've tested a transaction with a card with no funds. Although the redirect works fine, I can see there's no installments option shown and I'm not taken back to your website correctly after submitting the payment. 

In the Viva Wallet payment source settings, ensure 'HTTPS' is selected and 'Redirect' as integration method. Your Success / Failure URLs are fine. So I can investigate further, please send through a screenshot of the Viva Wallet module settings within WooCommerce under WooCommerce > Settings > Payments. For security purposes, blur out part of your Merchant ID and API key. Thanks!

**Comment by dimmisel** [comment]
You can look here the screenshot:
http://prntscr.com/srnz0x

I cannot check now the method, I will inform you later. Please look at the settings and tell me if problem exists

**Comment by dimmisel** [comment]
Where to fill this number? I will do it tommorow with my client.
Thanks

**Comment by matthewrgourd** [comment]
Please see annotated screenshot below:

![download](https://user-images.githubusercontent.com/44943019/83421401-ef108480-a41f-11ea-921f-059968a3f47a.png)

**Comment by dimmisel** [comment]
Again I cannot see any instalments. Any other solution?

**Comment by matthewrgourd** [comment]
Hi @dimmisel in that case I will need to raise with a developer. I'll do that and get back to you as soon as I can.

**Comment by matthewrgourd** [comment]
Hi @dimmisel, one of our devs has got back to me. He's asking which version of the plugin you're using. Can you check? You need to go to your list of plugins in WordPress. The version number should be shown against the Viva Wallet entry.

**Comment by dimmisel** [comment]
We have version Version 3.6.2

**Comment by matthewrgourd** [comment]
Hi @dimmisel, apologies for the delayed reply. Apparently the installments dropdown displays on the Viva Wallet payment page only if the customer's card supports installments. The other requirement is that the value of the purchase is the same as or more than the first number defined in the installments field So in your case, that would be the same as or more than 90 euros. Otherwise the option will be unavailable. Hope that helps! Please close the issue if you feel it has been addressed adequately. Thanks.
