### ISSUE TITLE
Integrate in my own site

### ISSUE THREAD

**Issue by QuintaDaTor** [VivaPayments/API#1716]
I am developing a website in PHP. I am using the demo version for integration in my platform.
I am not using any plug in.
I am using the Simple Checkout and the code that you have in your manual. I simple change the data-vp-publickey, $merchantId and $apiKey. https://developer.vivawallet.com/online-checkouts/simple-checkout/
I disable the comments to see the result, I have the following mensage:

stdClass Object ( [Emv] => [Amount] => [StatusId] => E [CurrencyCode] => [TransactionId] => [ReferenceNumber] => [AuthorizationId] => [RetrievalReferenceNumber] => [ThreeDSecureStatusId] => [ErrorCode] => 403 [ErrorText] => The specified api action is disabled for the merchant XXXXXXXXXXXXXXXX, please consult the documentation [TimeStamp] => 2020-05-29T11:44:12.0737103+03:00 [CorrelationId] => [EventId] => 0 [Success] => )

For now I am using localhost for developing. The testing url is locahost.
When I go to production I only change the URL to my domain, the code will be the same except the demo for production vivawallet.

I need to have success in order to continue to test the processing of the order.

More information or questions please contact geral@quintadator.com

**Comment by matthewrgourd** [comment]
Hi @QuintaDaTor you need to have the API enabled for your account. Please can I have your demo Merchant ID and I'll do this for you? Thanks!

**Comment by matthewrgourd** [comment]
It's ok, I've found your account by the email address provided. The Simple Checkout API is now available. When you're ready to go to production, you'll need to go through the same process. Thanks!
