### ISSUE TITLE
Reccuring payments

### ISSUE THREAD

**Issue by johnpetr** [VivaPayments/API#1718]
Hi. I am interested in creating a platform with monthly payments. I saw in older issues that you are going to expand your plugin to be compatible with woocomerce subscriptions. Is there any information on when this feature will be implemented?

**Comment by matthewrgourd** [comment]
Hi @johnpetr I don't have a definitive answer for you, I'm afraid. Will need to check and get back to you!

**Comment by matthewrgourd** [comment]
Hi @johnpetr I've checked and development of the requested feature is in progress. Unfortunately I can't give you a more concrete answer currently.
