### ISSUE TITLE
Issue after Updating wordpress and php

### ISSUE THREAD

**Issue by p4resh** [VivaPayments/API#1719]
Hi
We seem to be facing an issue after we updated our worpress to the latest version and php to 7.4
All other apps seems to be working fine, we are using native check out 2

Whilst still on our site when customers click on pay to be taken to the viva wallet payment page, A fate error message appears on our page.

Is there an issue with viva wallet native check out 2 with the lastest edition of wordpress and php 7.4

Paresh
![6FAF3FBE29414F5586C10B06454CA1AA](https://user-images.githubusercontent.com/61083605/83353953-efd8e600-a34d-11ea-8314-2e9573c49210.png)

**Comment by matthewrgourd** [comment]
Hi @p4resh I believe the merchant has three websites, all of which have our plugin for WooCommerce installed (not Native Checkout v2):

- https://www.havanahouse.co.uk
- https://regalcigars.com/
- https://www.thevaping-lounge.co.uk/

Can you confirm?

Are the other two e-commerce sites still working correctly? Have you done the same updates to those? Please let me know more so I can investigate further.

I've done a test transaction on https://www.havanahouse.co.uk and I'm redirecting to the payment page correctly. However, after 3DS, I'm not getting any kind of confirmation page.

**Comment by matthewrgourd** [comment]
Closing as no reply...
