### ISSUE TITLE
Βοήθεια

### ISSUE THREAD

**Issue by tsoniotimaria** [VivaPayments/API#172]
Δεν ξέρω πως κάνεις redirection. Έχω χρησιμοποιήσει το Woocommerce
το οποίο φτάνει μέχρι ολοκλήρωση παραγγελίας, τι πρέπει να κάνω για
να πάει στο viva...; Έχω δημιουργήσει πηγή πληρωμών

Ευχαριστώ

**Comment by defilerc** [comment]
Καλησπέρα @tsoniotimaria ,

Θα πρέπει να συμβουλευτείτε τις οδηγίες υλοποίησης του εξωτερικού plugin που χρησιμοποιείται. Καθώς η υλοποίηση δεν έχει γίνει από τη Viva Payments, δε μπορούμε να προσφέρουμε υποστήριξη για κάποιο εξωτερικό plugin που δεν έχει υλοποιηθεί από εμάς.

Ευχαριστούμε για την επικοινωνία
