### ISSUE TITLE
Intergrating with Pos from Pc

### ISSUE THREAD

**Issue by Diochris** [VivaPayments/API#1720]
Is there any solution to intergrate with mini card reader with pc via bluetooth ? on a windows enviroment platform? i mostly use visual studio c#.

**Comment by matthewrgourd** [comment]
Hi @Diochris please check the [POS API integration](https://developer.vivawallet.com/pos-api-integration/) section of our developer portal. Thanks!

**Comment by gmg-sante-jonction** [comment]
HI,
We are trying to integrate Vivawallet with a PAX A80.
Do you have any example of the code that give us some hint how to start.
thanks,
Alain

**Comment by matthewrgourd** [comment]
I'll check with a developer and get back to you. Thanks!

**Comment by matthewrgourd** [comment]
Hi @gmg-sante-jonction, we're not sure exactly how you want to integrate but here are two options:

- using InterApp 
https://developer.vivawallet.com/pos-api-integration/pos-terminal-apps/
you may check our [GitHub repo](https://github.com/VivaPayments/mobile-android-cardterminal-interapp-sample)
 
- over socket
https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/

**Comment by gmg-sante-jonction** [comment]
Hi,
We are trying to integrate the following API
https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/?utm_source=vivawallet_api_cl&utm_medium=referral&utm_campaign=pos_terminals

It does work with regular socket.
Our application is running with Web server. 
I have a question. Do you support Websocket or socket.io.
Is there any possible way to connect the terminal with through web application?

best regards,
Alain
a.alahi@gmg-sante.fr

On 1 Jun 2020, at 17:14, matthewrgourd <notifications@github.com> wrote:


Hi @gmg-sante-jonction <https://github.com/gmg-sante-jonction>, we're not sure exactly how you want to integrate but here are two options:

using InterApp
https://developer.vivawallet.com/pos-api-integration/pos-terminal-apps/ <https://developer.vivawallet.com/pos-api-integration/pos-terminal-apps/>
you may check our GitHub repo <https://github.com/VivaPayments/mobile-android-cardterminal-interapp-sample>
over socket
https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/ <https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/>

**Comment by gmg-sante-jonction** [comment]
Hi,

We have integrated the POS API over socket and we will connecte it to our Kiosk.
https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/?utm_source=vivawallet_api_cl&utm_medium=referral&utm_campaign=pos_terminals <https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/?utm_source=vivawallet_api_cl&utm_medium=referral&utm_campaign=pos_terminals>

In this regards I have some questions?

1- Always running:
The payment application must run all the times and it should never goes to Home screen or Card Terminal screen. 
This is very important that user should never be able to change the application or terminal setup.
How can we achieve this?
How can we luck the application to be always in ECR mode and never go to Card terminal screen pic #2.
Today when we are in ECR screen and we push Red button (X) it goes to Card Termina pic #1l.


2- Is there any way to know whether the customer has put its credit card in?

3- Is there is anyway to change waiting time to put the credit card reader in and do transaction (timeout)?

4- Is there anyway to customise the home screen?

Best regards,

Alain Alahi
Directeur de projet

GMG Santé
7 Rue Jean Goujon
75008 Paris
M: +33 6 266 266 86

**Comment by matthewrgourd** [comment]
Hi @gmg-sante-jonction, I've spoken with our POS developer and his response was as follows:

>These questions refer to kiosk mode. Unfortunately, this is not supported currently. We need to develop the mentioned features and at the moment I'm not sure of the timeline.

Apologies for any inconvenience caused. If I find out any further info, I'll be sure to update you!
