### ISSUE TITLE
Payment received on Vivawallet but no order on Shopify

### ISSUE THREAD

**Issue by Mamakana** [VivaPayments/API#1721]
Hello, 

I am using Vivawallet for my Shopify store mamakana.com. 

It is not the first time that i received a payment on Vivawallet but that there is not the order on Shopify but in Abandoned Cart.

This issus happens 1 hour ago, i have attached screenshot of the Vivawallet transaction and the Abandoned Cart.

It is not the first time that i raised this issue to Github. 

Please find a solution because this is a big problem for us as we have to check every time our Vivawallet payment and Abandoned Cart.

Kind regards, 
Joffrey
![Capture d’écran 2020-06-01 à 10 26 09](https://user-images.githubusercontent.com/61584569/83391277-88757180-a3f3-11ea-9d12-da1b54d0d14d.png)
![Capture d’écran 2020-06-01 à 10 26 09](https://user-images.githubusercontent.com/61584569/83391291-8ca18f00-a3f3-11ea-8d30-f77312d136c5.png)

**Comment by matthewrgourd** [comment]
Hi @Mamakana sorry to hear this. I've just checked your website and attempted a transaction with my company card. I was returned to mamakana.com after completing the payment page and the right message was displayed about payment failure (card has no funds). The step after finalising the cart is payment so it is impossible to abandon a cart having already made a payment. I can see the £75 successful transaction you mentioned in today's transactions against your account. There's no possibility of this relating to an abandoned cart so there must be an issue at the Shopify end. Hope this helps!
