### ISSUE TITLE
Can i keep $ currency while i using Viva wallet with my store? 

### ISSUE THREAD

**Issue by TheGold-Eagle** [VivaPayments/API#1722]
Hi, I hope everyone doing well, I'm new with viva wallet, I wanna know if can viva wallet with $ store we don't wanna change it because we target usa market, thanks.

**Comment by matthewrgourd** [comment]
Hi @TheGold-Eagle, are you referring to your Shopify store? Please let me have more details so I can try and help you. Are you US based? Have you used Viva Wallet before?

**Comment by TheGold-Eagle** [comment]
Hi, @matthewrgourd thanks for the reply, yes I'm using Shopify store, no I'm not living in the USA, but our store targeting USA market so the currency should be with $ so people can know how much they will pay, if we change it to GBP or EURO, our conversation create will down, also i don't use viva wallet before this is the first time, so I want to know if we can using viva wallet without change the store currency, thanks.

**Comment by matthewrgourd** [comment]
Hi @TheGold-Eagle thanks for the update. You need to set your Shopify store currency to the same currency as your Viva Wallet account. So (for instance) if you set up your Viva Wallet account in the UK, you'd need to specify GBP as the store currency. There's no other way of doing it I'm afraid.
