### ISSUE TITLE
odoo connector with VIVA

### ISSUE THREAD

**Issue by stavri672** [VivaPayments/API#1723]
Hello

I connect my odoo Community with VIVA wallet,  My account in viva is aproved and ready but we get the error 403?  Anyone can help?

**Comment by matthewrgourd** [comment]
Have you implemented a custom solution using our API or used some other integration? I'm afraid we don't have an e-commerce plugin for Odoo at the moment.

**Comment by stavri672** [comment]
Mathew,

 

We are using a odoo-viva connector from Devstriker

 

They are on the email too. How can we solve the issue?

 

Sincerely

 

Stavros Mylonas

Sincerely

 

Telli Enterprises

Direct Tel: 357-22-026255

Switch:  357-22-485690

Mob: 357-99-379290

 

Email: smylonas@tellienterprises.com <mailto:smylonas@tellienterprises.com> 

Web: www.tellienterprises.com <http://www.tellienterprises.com>

**Comment by matthewrgourd** [comment]
Hi @stavri672, I've found the plugin now: https://apps.odoo.com/apps/modules/12.0/viva_payments_integration/

This was not developed by us so we can't provide you with any support. According to the info on the above page, if you encounter any problem with the module you should email direction@devstriker.com.

**Comment by stavri672** [comment]
Hello Mathiew,

Our client needs you to activate API access for them as you did for us 
in this issue <https://github.com/VivaPayments/API/issues/1274> .

Thanks & Regards,
Safwen

**Comment by matthewrgourd** [comment]
Ok, I can do that but not sure why it would help as that is for our Simple Checkout API and I don't think the unofficial plugin uses that. If you still wish me to go ahead, please provide the business name / company registration number of the client registered with Viva Wallet. Thanks!

**Comment by stavri672** [comment]
Hello All

 

Company TC NUOVO Enterprises Ltd

Registration: HE265319

 

Sincerely

 

Stavros Mylonas

Sincerely

 

Telli Enterprises

Direct Tel: 357-22-026255

Switch:  357-22-485690

Mob: 357-99-379290

 

Email: smylonas@tellienterprises.com <mailto:smylonas@tellienterprises.com> 

Web: www.tellienterprises.com <http://www.tellienterprises.com>

**Comment by matthewrgourd** [comment]
@stavri672 enabled as requested. Thanks.

**Comment by stavri672** [comment]
Thanks

 

Works great

 

Sincerely

 

Stavros Mylonas

Sincerely

 

Telli Enterprises

Direct Tel: 357-22-026255

Switch:  357-22-485690

Mob: 357-99-379290

 

Email: smylonas@tellienterprises.com <mailto:smylonas@tellienterprises.com> 

Web: www.tellienterprises.com <http://www.tellienterprises.com>
