### ISSUE TITLE
changing language

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1724]
Hi @matthewrgourd , this customer ´´ Sub-ohm Technologies SL´´ needs to change the language in payment platform, like I show in the screenshot, by defect way in Spanish NOT change manually.

Thanks in advance!

![image](https://user-images.githubusercontent.com/56823712/83498700-888d7400-a4bc-11ea-9130-d713ddbab1e7.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada this is not supported for Spanish currently. Except for Greek / English accounts, customers have to change the language manually.
