### ISSUE TITLE
Vivawallet is not redirected to website after paying.

### ISSUE THREAD

**Issue by InHeDEV** [VivaPayments/API#1725]
I followed the guide doc. and then redirect is not working with woocommerce plugin.
https://github.com/somewherewarm/woocommerce-gateway-viva
after paying it to stay the viva wallet success page. and Order not completed.
*payment was completed. I got an email from the viva wallet.
Could anyone help me?

**Comment by matthewrgourd** [comment]
Hi @InHeDEV that URL you've given is a link to an unofficial plugin not supported by Viva Wallet. Please deactivate and delete any existing plugins, then visit our official [installation page](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) where you will find all the correct details. Thanks!

**Comment by InHeDEV** [comment]
thank you for your help, I will do
