### ISSUE TITLE
Simple Checkout Access Request

### ISSUE THREAD

**Issue by appartment** [VivaPayments/API#1726]
Please grant me access for the simple checkout sandbox

**Public Key** : 4LYyIR0t+O5XG+NzDFWh72V7FGrr2TUSFYDUyF848vk=

**Comment by matthewrgourd** [comment]
Hi there please provide your demo Merchant ID rather than public key so I can deal with your request. Thanks.

**Comment by appartment** [comment]
There you go: 1788ee76-e6d0-4172-b05e-94edffa85296

**Comment by matthewrgourd** [comment]
Hi @appartment that's enabled for you. Thanks!
