### ISSUE TITLE
Termination of agreement with immediate effect

### ISSUE THREAD

**Issue by TheGold-Eagle** [VivaPayments/API#1727]
Hi, I have created viva wallet account, I'm located in the UK and I have LTD, I have vivificated my viva wallet account, but after a day I get an email that says: 

However, we regret to inform you that for reasons pertaining to the continuous compliance of our firm with both the framework applicable in the context of our operation as a payment service provider and the terms and conditions set by intermediaries and other entities in the financial system, we are obliged to proceed to the termination of our agreement with an immediate effect, according to clause no. 10 of our terms and conditions published on www.vivawallet.com.  

what I'm doing wrong? what the reason? I get this email even I still didn't link my store with viva wallet

**Comment by matthewrgourd** [comment]
Hi @TheGold-Eagle sorry to hear this. Please email support@vivawallet.com for further info or call one of the below numbers:

<table><tr><th>Country</th><th>Phone number</th>
  <tr><td>Belgium</td><td>(+32) 2342 0790</td></tr>
    <tr><td>Cyprus</td><td>(+357) 2403 0211</td></tr>
    <tr><td>France</td><td>(+33) 1876 50765</td></tr>
    <tr><td>Greece</td><td>(+30) 21 1760 4000</td></tr>
    <tr><td>Netherland</td><td>(+31) 2089 05503</td></tr>
    <tr><td>Romania</td><td>(+40) 3122 96150</td></tr>
    <tr><td>UK</td><td>(+44) 20 3734 7770</td></tr>
    <tr><td>Portugal</td><td>(+351) 3 0050 9059</td></tr>
</table>

**Comment by TheGold-Eagle** [comment]
bad support bad service, you close my account without any reason
