### ISSUE TITLE
"There was a problem with your payment"

### ISSUE THREAD

**Issue by nicolascolocci** [VivaPayments/API#1729]
Hello, a customer that  has bought numerous times through vivawallet and with the same card is now getting a "There was a problem with your payment, please try with another card" error every time she tries to pay. 
Is this an issue deriving from the recent update in your systems?
Hoping in a swift response

**Comment by matthewrgourd** [comment]
Hi @nicolascolocci, sorry to hear this. Can you let me have the web address of the e-commerce site and your registered business name? Thanks.

**Comment by matthewrgourd** [comment]
No reply so closing issue...
