### ISSUE TITLE
Βοήθεια

### ISSUE THREAD

**Issue by tsoniotimaria** [VivaPayments/API#173]
Καλησπέρα,

όταν κάνω redirection στη σελίδα σας μου δείχνει μόνο δύο τρόπου πληρωμής.
γιατί ?.   Κάρτα και wallet

Ευχαριστώ

**Comment by defilerc** [comment]
Καλησπέρα @tsoniotimaria ,

Κατά τη δημιουργία ενός Order, μπορείτε να ορίσετε τις μεθόδους πληρωμής που θα σας εμφανίζονται στη Redirect σελίδα μέσω των optional parameters. 

Για περισσότερες πληροφορίες, μπορείτε να δείτε εδώ: https://github.com/VivaPayments/API/wiki/Optional-Parameters

Σας ευχαριστούμε πολύ.
