### ISSUE TITLE
pos-api-integration with web

### ISSUE THREAD

**Issue by gmg-sante-jonction** [VivaPayments/API#1730]
Hi,
We are trying to integrate the following API
https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/?utm_source=vivawallet_api_cl&utm_medium=referral&utm_campaign=pos_terminals

It does work with regular socket.
Our application is running with Web server. 
I have a question. Do you support Websocket or socket.io.
Is there any possible way to connect the terminal with through web application?

best regards,
Alain
a.alahi@gmg-sante.fr

**Comment by matthewrgourd** [comment]
Hi @gmg-sante-jonction, thanks for your question. I'm raising with a developer. I'll get back to you as soon as I have an answer.

**Comment by matthewrgourd** [comment]
Hi @gmg-sante-jonction, reply from our dev team: 

> Currently we support only the communication over TCP/IP socket. We've not implemented or tested a web app integration. If you are able by any means to connect and communicate with a TCP/IP socket through your web app, then I cannot see any issue to implement a solution.

Hope this helps!

**Comment by ChrysalisSolution** [comment]
Hi, i wish to implement a same project. 
My system run on PHP and I wish just send the amount to my physical terminal. 
Have you a example code to run this ?
Thank you

**Comment by matthewrgourd** [comment]
Hi @ChrysalisSolution there are two integration options:

- using InterApp 
https://developer.vivawallet.com/pos-api-integration/pos-terminal-apps/
you may check our [GitHub repo](https://github.com/VivaPayments/mobile-android-cardterminal-interapp-sample)
 
- over socket
https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/

Hope this helps!
