### ISSUE TITLE
Error after Magento installation

### ISSUE THREAD

**Issue by evapespain** [VivaPayments/API#1732]
Hello,

I have just installed the Vivapay module for magento 2.3.
At the checkout we get the following error:
{"0":"Notice: Trying to get property 'ErrorCode' of non-object in \/chroot\/home\/ac46cd57\/evape.com\/html\/app\/code\/Ced\/VivaPayments\/Model\/PaymentMethod.php on line 202","1":"#1 Ced\\VivaPayments\\Model\\PaymentMethod->getPostHTML() called at [app\/code\/Ced\/VivaPayments\/Controller\/Checkout\/Start.php:40]\n#2 Ced\\VivaPayments\\Controller\\Checkout\\Start->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#3 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#4 Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#5 Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#6 Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->___callPlugins() called at [generated\/code\/Ced\/VivaPayments\/Controller\/Checkout\/Start\/Interceptor.php:26]\n#7 Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#8 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:98]\n#9 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#10 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#11 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php:99]\n#12 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#13 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:73]\n#14 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#15 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#16 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#17 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#18 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:24]\n#19 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#20 Magento\\Framework\\App\\Bootstrap->run() called at [index.php:39]\n","url":"\/vivapayments\/checkout\/start","script_name":"\/index.php","report_id":"8271b9c77fd7afc5cd1065a33ec0ad434cbd80407035a6d47de6ba87a57788b8"}

This error only occurs using vivapay module. 

Are you able to help with a solution to this.

Kind regards

**Comment by matthewrgourd** [comment]
Hello, most likely you have made a mistake with your setup. I would advise to setup first with the demo environment to verify the correct working before proceeding to the live environment. Follow the instructions given at https://developer.vivawallet.com/e-commerce-plugins/magento2.3/ to the letter.
