### ISSUE TITLE
"Error! The url could not be verified." on Webhook creation

### ISSUE THREAD

**Issue by burningmax** [VivaPayments/API#1733]
Hi there I'm having some trouble in the final configuration of the VivaWallet plugin for WooCommerce on a client's website. I have been following all the steps from the dev portal https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ but still i get an error message when I try to create a Transaction Payment Created webhook from the VivaWallet API dashboard. Please help?????????

![vivawallet-error](https://user-images.githubusercontent.com/66515309/83942758-dbd23000-a7f6-11ea-8265-ce59a1d308e0.png)

**Comment by burningmax** [comment]
Hi Matthew, thanks for your reply. 

I'm using two VivaWallet plugins. The first, i guess the main one is the "WooCommerce Viva Wallet Gateway" v. 4.1.1 whose claim is "Connects WooCommerce to Viva Wallet payment gateway to process and sync your payments and help you sell more." - The other one is still a "WooCommerce Viva Wallet Gateway" v. 3.6.2 whose claim is "Extends WooCommerce with the Vivawallet gateway." - Both plugins are produced by VivaWallet.

The full webhook URL is https://www.canapa-co.com/index.php?wc-api=wc_vivawallet&vivawallet=webhook   ---  as suggested in the GitHub documentation. I have tried to get it verified in any form, with http and https, including with or without the www - non of them worked, I still get the error message "The url could not be verified, etc...". This is the only webhook i have tried to create for this merchant account, and also the first time i ever work with VivaWallet.

I appreciate your support and suggestions on this. Thanks.

**Comment by matthewrgourd** [comment]
Hi @burningmax please disregard 4.1.1 for the moment as we had to roll back to 3.6.2. The documentation at https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ refers to the latter. So I suggest deactivating and deleting 4.1.1 then trying again. But make sure you the plugin is set up correctly on your Wordpress instance before trying again to verify the same webhook which is correct for 3.6.2.

**Comment by burningmax** [comment]
Hi Matthew, thank you very much for your input. I have followed your suggestions, got rid of 4.4.1, reset the WC configuration, and the webhook has been validated. More to it, we already tested the payment and in fact everything works fine! Thanks again!!!

**Comment by burningmax** [comment]
Actually, Matthew - hope you are still following this. First of all, thanks a lot for your previous helr, everything is working fine and stuff.

But I have hit another error - thing is that the website is a biliingual site italian / english, bullt with two different wordpress/woocommerce installation, the italian one on the /it/ subdomain. 

Now I have just set up the vivawallet plugin for the italian site, but when I try to create the webhook same procedure as before, i hit an ERROR message as the systems "doesn't like" the /it/ domain name, showing a message that goes: Please enter a valid domain (without protocol (http:// or https://), or "/")

How can I get around this to make the gateway work also on the italian website? A y suggestion? Thanks!

**Comment by burningmax** [comment]
And I forget to say, sorry....

Also the fields that I cannot modify for the Success/Failure URLs since they see above www.namedomain.com/it automatically show as namedomain.comit/ before appending the second part of the URL....

**Comment by matthewrgourd** [comment]
Hi @burningmax, as far as I'm aware, the webhook should work at domain level (the bit before the /it) so no need to change the existing webhook for different localisations.

**Comment by burningmax** [comment]
Hi Matthew, the problem is that the website is not ONE website with different localization (i.e. polylang or such). They are actually two different websites, on with a wordpress + woocommerce + vivawallet installation at root level, another complete website installed in the /it/ subdirectory - with its own wordpress è woocommerce + vivawallet. 

So OK the webhook should work at domain level, but the validation for the "domain.com/index.php?wc-api=wc_vivawallet&vivawallet=webhook" for am event type "transaction payment created" - on the Italian website - should happen on "domain.com/it/index.php?wc-api=wc_vivawallet&vivawallet=webhook", otherwise also the success and fail pages will go straight to the main platform/website in english (root) --- but we need them to be on the /it/ installation. 

I have just tried to create a new webhook on the "domain.com/it/index.php?wc-api=wc_vivawallet&vivawallet=webhook" URL and at first the validation went OK, even with the /it/ ---- but when I set it as "transaction payment created" and clicked "save" I got an error saying "Error! A Webhook for this Event Type already exists (Error code 409)" ---- so we are back to square one.

How can I go around this? Any help? Thanks again in advance....

**Comment by matthewrgourd** [comment]
Hi @burningmax, I'm afraid that, due to technical considerations, there's a limitation with the webhooks. You can only have one set up per Viva Wallet account. That's probably why you're having problems.

**Comment by burningmax** [comment]
OK I see - but let me ask another question - if we drop the idea of having the italian website in a subdirectory /it and install the website at root level on a new domain .it, will i be able to create a new webhook for a new website? Does my client will have to create a new account/IBAN within the same VivaWallet merchant account, alongside the primary account? Or does my client have to create a totally different new account on the VivaWallet platform?

**Comment by EvaBjornsdottir** [comment]
Hi, I have the same problem, have tried all types of different approaches, with or without https, with or without www. and still not working. I have version 3.6.2 installed on plugin WooCommerce Viva Wallet Gateway. Version 4.1.1 on plugin Viva Wallet for WooCommerce and version 4.2.0 on plugin WooCommerce. 
Any help would be appriciated. 
Thanks in advance

**Comment by matthewrgourd** [comment]
Hi @EvaBjornsdottir, sorry to hear this. Please remove all other versions of the plugin except 3.6.2 which is the current one. We had an issue with 4.1.1 and had to roll back, Webhook should be  

`http(s)://(www.)your_domain.com/index.php?wc-api=wc_vivawallet&vivawallet=webhook`
exchanging the placeholder for your actual domain name.

as you rightly stated. Thanks.

**Comment by EvaBjornsdottir** [comment]
Hi @matthewrgourd, unfortunately I am still having problems.
I deleted all vivawallet plugins and reinstalled version 3.6.2 but the url can still not be verified.
Do you have any other suggestions for me to try fix this?

Thanks in advance

**Comment by matthewrgourd** [comment]
Hi @EvaBjornsdottir you need to follow our guide word for word. I've checked your website and our plugin isn't working properly. This needs to be fixed before the webhook can be verified. Please change the payment source settings in your Viva Wallet account as below:
INCORRECT
![image003_01D6463CEBA6FD60](https://user-images.githubusercontent.com/44943019/85259657-52ab3200-b461-11ea-80fa-d7a31df139a2.png)

**CORRECT**
![image003_01D6463CEBA6FD61](https://user-images.githubusercontent.com/44943019/85260441-98b4c580-b462-11ea-8025-e58eeb2e3628.png)

Also, the webhook is wrong. You're including a `www` when the web address is https://lighterleaf.com (without `www`). 
INCORRECT
https://www.lighterleaf.com/index.php?wc-api=wc_vivawallet&vivawallet=webhook
**CORRECT**
https://lighterleaf.com/index.php?wc-api=wc_vivawallet&vivawallet=webhook

**Comment by EvaBjornsdottir** [comment]
Hi @matthewrgourd, 
Everything is up&running now.
Thank you so much for your help!

**Comment by matthewrgourd** [comment]
@EvaBjornsdottir no problem!

@burningmax, in answer to your last question, I believe they need to create a completely new account. Thanks.
