### ISSUE TITLE
Refund error - 

### ISSUE THREAD

**Issue by lovetoast** [VivaPayments/API#1734]
Hi,

Using code:

`<?php 
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://www.vivapayments.com/api/transactions/{REDACTED TRANSACTION ID}');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"amount\": 100,\n}");
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");

$headers = array();
$headers[] = 'Authorization: Basic {REDACTED TOKEN}';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
print_r ($result);`

I receive 

"ErrorText":"Negative or zero amount in reversal"

I understand that on the day of the transaction only a full refund is possible and so I entered 100 for a £1 transaction, but that's not working. Any idea how to rectify this? The transaction ID and token are valid because I'm getting a  response but it's the error above.

**Comment by matthewrgourd** [comment]
Hi @lovetoast sorry to hear this. Not immediately sure why that is. Let me check with a developer for you!

**Comment by matthewrgourd** [comment]
Hi @lovetoast, developer has come back with the following:

>I believe the merchant should include the source code in the request:
```
$body = array( 
'amount' => $refund_amount_cents,
'SourceCode' => $credentials ['source_code']
);
$args = array( 
'headers' => array( 
'Authorization' => 'Basic ' . base64_encode ( $credentials ['merchant_id'] . ':' . $credentials ['api_key'] ),
'Content-Type' => 'application/json'
),
'method' => 'DELETE'
);
$url    = WC_Vivawallet_Helper::get_url_endpoint ( $credentials ['test_mode'], WC_Vivawallet_Helper::ENDPOINT_TRANSACTIONS );
$url    = $url . $payment_transaction_id;
$params = http_build_query ( $body );
$url    = $url . '?' . $params;
$response = wp_remote_request ( $url, $args );
```
>`amount` and `SourceCode` must be included in the URL as params. Method should be DELETE, I think [the developer] sets that properly, but the URL should be something like `https://www.vivapayments.com/api/transactions/TXN-ID?amount=100&SourceCode=1234`
