### ISSUE TITLE
 Redirect Checkout  - Recurring payment info

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1736]
Hi,

In Redirect checkout API How we can get the information regarding, customer clicked "I allow future or recurring payments for this card" checkbox or not.
Does any API response include this information?

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs I'm not sure I'll need to check with a developer.

**Comment by pavithra-itcs** [comment]
Hi,

Please check and let us know ASAP.

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, apologies for the extended delay. Our dev team has been busy prioritising other tasks. The reply is:

>In the response of [Retrieve transactions](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1%7BId%7D/get) there is a field called `recurringSupport` inside payment object:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/44943019/84767574-9c5fcc80-afca-11ea-9f89-acfefe51251f.png)

**Comment by pavithra-itcs** [comment]
Thank you.
