### ISSUE TITLE
Redirect Checkout - how to cancel Recurring payment option

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1738]
Hi,

In redirect checkout customer selected "I allow future or recurring payments for this card"  checkbox and do the payment. Later he wants to disable this recurring payment option. Could you please tell us how to achieve this.

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, this is not something I'm hugely familiar with so will need to check with a developer.

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, apparently it's currently not possible to disable the recurring payments flag. Best regards.
