### ISSUE TITLE
viva payments emails missing

### ISSUE THREAD

**Issue by evandoulas** [VivaPayments/API#1739]
from yesterday we have stopped receiving the email that comes along with every ticket payment, from our site "levanteferries.com"
Could you please check it and inform us asap
It is critical because it affects our production.

thanks in advance

**Comment by matthewrgourd** [comment]
Hi @evandoulas, sorry to hear this. Can you let me know whether this is a custom installation using our API or if you're using one of our e-commerce plugins?

**Comment by evandoulas** [comment]
It is solved.
We have been informed by your colleagues

**Comment by matthewrgourd** [comment]
Ok, thanks for letting me know @evandoulas. I'll close the issue in that case.
