### ISSUE TITLE
Fatal Error Unknown cipher in list: TLSv1

### ISSUE THREAD

**Issue by polyskasinides** [VivaPayments/API#1740]
Hi there,

We are using Viva Payments for our online store for a long time and now we are building a new store, under a different domain name. For the purpose of testing our new store with Viva payments API, we created a new Viva account for demo purposes.
When we implement the code as indicated here we get the following error.
Unknown cipher in list: TLSv1

Can you please assist?

Thanks

**Comment by matthewrgourd** [comment]
Hi @polyskasinides, sorry to hear this. Can you let me know whether you're referring to a custom installation using our API, online checkout or e-commerce plugin? I need a bit more info, if possible, please...

**Comment by polyskasinides** [comment]
Thanks for the reply. The solution was to remove the following line.

curl_setopt($c, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

**Comment by polyskasinides** [comment]
Thanks for the reply. The solution was to remove the following line.

curl_setopt($c, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

**Comment by matthewrgourd** [comment]
Hi @polyskasinides thanks for the solution.
