### ISSUE TITLE
connect vivawallet POS terminal to Ecr electronic cash register

### ISSUE THREAD

**Issue by srcevo** [VivaPayments/API#1741]
How to connect the ECR (electronic cash register) to the POS terminal to automatically send the payment amount?
What settings should be made? 
Which terminals are compatible with ECR?

**Comment by matthewrgourd** [comment]
Hi @srcevo have you checked our [POS API integration page](https://developer.vivawallet.com/pos-api-integration/) on the Viva Wallet Developer Portal?

**Comment by srcevo** [comment]
Hi, i read  POS API integration page, i always integrate our ordering application with Viva Wallet POS and it works ok, but now i want to connect directly a ECR to Viva POS terminal using serial port.

**Comment by matthewrgourd** [comment]
HI @srcevo let me check with a developer and get back to you.

**Comment by matthewrgourd** [comment]
Hi @srcevo, our tech team is asking in what country you're based? Apparently each country's cash registers are implementing different connection protocols to integrate with the card terminals of the local market. Please note that the Cardlink API currently does not support communication over serial. We support ECR integration over TCP/IP only, for specs see
https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/

**Comment by srcevo** [comment]
Hi @matthewrgourd , I'm from Romania. Most of the ECRs communicate on the serial port. Do you know if there is any local ECR model that communicates with Viva POS terminal? I can talk to the ECR's manufacturers to implement a serial communication protocol if you have one. ECR local models: Datecs, Incotex, Adpos, Tremol.

**Comment by matthewrgourd** [comment]
Hi @srcevo, apparently not currently supported but in our long term plans. However, if you do develop support for it, we can accommodate your software on our terminals. Hope this helps.
