### ISSUE TITLE
International Transfer

### ISSUE THREAD

**Issue by Robert-A-Taily** [VivaPayments/API#1742]
Hi Viva Team, 

I am trying to process a payment for an invoice to a German-based company and my company is based in the UK. Your platform won't allow me to add their IBAN and save them as a beneficiary. 

If you can please advise the best way to move forward with this that would be greatly appreciated. I have also sent an email to support@ with more details the ticket i.d is CC-1299580.

Thanks, 
R

**Comment by matthewrgourd** [comment]
Hi @Robert-A-Taily, believe your query has been answered by our Customer Care Team so I'm closing this issue now. Thanks!
