### ISSUE TITLE
Native Checkout v2 3DS in Android

### ISSUE THREAD

**Issue by kalgik** [VivaPayments/API#1743]
Dear all,

I was wondering if I can use the Native v2 3DS (https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) in an Android application.

Regards,

**Comment by matthewrgourd** [comment]
Hi @kalgik you can build a custom solution for Android, but you would need to be able to open a popup or iframe for the 3DS authentication. Unfortunately we don't have any code samples.
