### ISSUE TITLE
Transaction failed with Native checkout V2 with 3DS

### ISSUE THREAD

**Issue by TwinkleMali** [VivaPayments/API#1744]
Hi Team Viva,

Regarding query for transaction failed issue.

We are facing issues for making payment using Card some times.
We have integrated Viva for platforms : Android, iOS and PHP

The flow for payment is as below :

Step 1:  Platform used : Android/iOS
Make call to API for getAccessToken URL : “https://accounts.vivapayments.com/connect/token”

Step 2: Platform used : Android/iOS
After response from getAccessToken and receive proper access token data 
Make call to Api for getChargeToken URL : “https://api.vivapayments.com/nativecheckout/v2/chargetokens”

Step 3: Platform used : PHP
After we get proper response from getChargeToken api , ie if 3DS is enabled for card after completing that step.
We call API to make transaction URL : “https://api.vivapayments.com/nativecheckout/v2/transactions”
And we are getting issue at this step 3.

Issue faced is as follows:
-We are facing issue for making payment using particular card some time when we perform step 1 and step 2 from android app.
-The particular card works some times and same card do not work some time from android app.
-ie. Out of 10 tries from android app it works 3 time and 7 times fails for particular card.
-It always works for other card from android and iOS.
-If the same card is used to make payment from iOS app it always works.

The error which we receive while making payment is as follows :
{
      "status": 502,
      "eventId": "10030",
      "message": "Transaction failed",
      "Amount": 100,
      "ErrorText": "Payment Error: "
}

Error code and event id we are receiving in transaction api response , is indicating issue from viva side as per the error description given on viva site.

Would you please check the same and provide us more detail regrind the issue we are facing according to the error we face?

We would like to have reply for this as soon as possible as our live users are affecting in making online payment. 

Looking forward to your reply soon.

Thanks,
Twinkle

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali, sorry to hear this. What is the website address or is it an app you're referring to?

**Comment by TwinkleMali** [comment]
Hi @matthewrgourd ,
We have developed application in iOS , Android and Cake PHP. In all we have followed same steps. 
but in Android app we are getting transaction failed error . And when we try same card in iOS and Web, its worked.  The error we are receiving on transaction failed is status: 502 and EventId: 10030.

Not sure what is wrong is happening. But those error code description pointing issue at Viva side. 
Can you please check that and guide us is there is something wrong happening at our end ?

Looking forward to your reply soon.

Thanks,
Twinkle

**Comment by matthewrgourd** [comment]
From Viva Wallet developer Portal [error codes page](https://developer.vivawallet.com/api-reference-guide/error-codes/):

<table>
  <tr>
    <th>Code number</th>
    <th>Reason</th>
    <th>Explanation</th>
    <th>Type</th>
    <th>x-viva-eventId</th>
  </tr>
  <tr>
    <td>30</td>
    <td>Format error</td>
    <td>The card issuer does not recognise the transaction details being entered. This is due to a format error.</td>
    <td>System</td>
    <td>10030</td>
  </tr>
</table>

...but I will speak to a developer as well.

**Comment by TwinkleMali** [comment]
Sure, Please check with developer and do let us know if there is something missed to be managed from our side. As same card is working fine as expected all time form iOS app and Web app. 
So not sure from which side issue is. And the thing is that same steps we follow for all applications. 

Also we faced that issue with some card only and some cards are always works. 

Looking forward to your reply soon. 

Thanks,
Twinkle

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali, developer has replied that more info is needed so we can investigate further.

> If the same card is used to make payment from iOS app it always works.

It doesn't matter the type of programming language or device that is being used.

Did you pass exactly the same details from all the platforms?

**Comment by TwinkleMali** [comment]
Hi @matthewrgourd ,
We had shared all details in very first message. can you please do let me know specific what information you need so i can check from my side ?

**Comment by TwinkleMali** [comment]
Hi @matthewrgourd  ,
Any update on this reported issue? 

We are stuck very badly as live user facing issue in payment. 

Looking forward to your reply soon.

**Comment by matthewrgourd** [comment]
Sorry for the delay, I will ask again.

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali, I've checked with the dev team and there are currently no problems on our side. We're not sure why this is happening but as you're attempting a custom integration, we're unable to help further. Good luck!

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali, I need to look at this issue again. Before I go any further, can you confirm the Viva Wallet account name and / or company registration number, please?

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali , regarding the below response:
```
The error which we receive while making payment is as follows :
{
"status": 502,
"eventId": "10030",
"message": "Transaction failed",
"Amount": 100,
"ErrorText": "Payment Error: "
}
```

Please can you let use have a copy of the call made that elicited this response. Blur out any confidential information. Thanks!

**Comment by TwinkleMali** [comment]
Hi Matt,

Below I have attached doc file in that you will get all details about viva wallet account. If you need any thing else from our end then please do let us know.



Thanks,
Twinkle

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali, sorry, I can't see an attachment. Can you try again?

**Comment by matthewrgourd** [comment]
@TwinkleMali, if you have any issues with the attachment again, please email to myself at mgourd@vivawallet.com. Thank!

**Comment by TwinkleMali** [comment]
@matthewrgourd ,  i just new email to mgourd@vivawallet.com .
Can you please check now ? 

Thanks,
Twinkle

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali I need you to send me a copy of the request details. You sent me the below response previously but I need the request to accompany it, otherwise we can't investigate:
```
{
"status": 502,
"eventId": "10030",
"message": "Transaction failed",
"Amount": 100,
"ErrorText": "Payment Error: "
}
```

**Comment by matthewrgourd** [comment]
By the way, thanks for the Word doc containing the general info about how many payments have been affected.

**Comment by TwinkleMali** [comment]
@matthewrgourd , Do you want details of cancelled transactions ?

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali, no, if possible, I need the code you used that produced the response with the error.

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali, I cannot proceed any further with you sharing your code, especially the bit that produced the error response. You can email me at mgourd@vivawallet.com if you like. Thanks!

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali I just replied to your email. I believe all your questions are answered now. If you agree, please close this issue.

**Comment by TwinkleMali** [comment]
@matthewrgourd , i sent you email in personal about the this issue along with logs. 
Can you please check the same and help us in same?

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali my last email to you sent over the weekend included an extensive set of examples from one of our developers. I assumed as you'd not got back to me, you were ok. I'm afraid I've offered you all the assistance I can. I hope the multiple emails I have sent helped, but I'm afraid I can't give you any further guidance beyond what I've sent you already. Good luck!

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali let me reply to your email about the logs.
