### ISSUE TITLE
Error 404 /api/orders/<orderId>

### ISSUE THREAD

**Issue by johnnyneverwalked** [VivaPayments/API#1746]
Right after creating an order and retrieving an `orderId` from the API, on the next request to 
`GET  /api/orders/<orderId>` the API responds with `404 not found` for this `orderId` that was just created. This happens once every ~100 orders. 

Has anyone else encountered this issue?

I am using the **Viva Wallet Payment API** through HTTP.

**Comment by matthewrgourd** [comment]
Hi @johnnyneverwalked, sorry to hear this. Are you making this call on demo or live?

**Comment by johnnyneverwalked** [comment]
Hi @matthewrgourd! I have encountered this problem on production. The call is being made on live.

**Comment by matthewrgourd** [comment]
Ok @johnnyneverwalked, thanks. Our dev team is checking the logs for errors. I'll get back to you shortly.

**Comment by matthewrgourd** [comment]
Hi @johnnyneverwalked we've checked the logs and no recent issues with the API that we can see. We suggest if this happens again you make a note of the date / time of the problem so we can investigate further. Hope this helps!

**Comment by johnnyneverwalked** [comment]
Hello @matthewrgourd! This particular issue surfaced again on 29/06/2020 11:24 AM (GMT+3). The returned `orderId` from the API is `9225999865372604` and the API response on subsequent retrieval requests is again `404 not found`. Hope this narrows it down!

**Comment by matthewrgourd** [comment]
Hi @johnnyneverwalked, sorry to hear this. So that I can check our CRM, please provide your account name.

**Comment by johnnyneverwalked** [comment]
Could you provide me with an email so I can send it to you? Thank you

**Comment by matthewrgourd** [comment]
mgourd@vivawallet.com. Thanks!

**Comment by matthewrgourd** [comment]
Hi @johnnyneverwalked, I can confirm that the transaction didn't go through. There is no record of it in our CRM. So you wish me to raise as an instability in our API? Because it obviously failed for this one transaction. Just want to be clear on what it is you're requesting. Thanks!

**Comment by johnnyneverwalked** [comment]
@matthewrgourd since it is not the first instance of this issue surfacing I think it would be correct to be raised as an instability. The instability being that even if the transaction doesn't go through, a successful response with an `orderId` is still being returned by the API in some cases. Thank you!

**Comment by matthewrgourd** [comment]
Ok @johnnyneverwalked, I will raise with our development team. Best wishes.
