### ISSUE TITLE
Error 500 - opencart 3

### ISSUE THREAD

**Issue by geochrisgr** [VivaPayments/API#1747]
Hi i have add the ocmod in my store, the final customer go to the viva and pay, in success url the final customer is take 500 ERROR and the order is goin in "mised order".
How we can resolve the issue!?

**Comment by matthewrgourd** [comment]
Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- OpenCart 3 payment module settings (partially hide your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps  page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (partially hide API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by geochrisgr** [comment]
Thnx for you fast support! :)
1.
![freesnippingtool com_capture_20200617181452](https://user-images.githubusercontent.com/8250482/84916541-e0d09280-b0c6-11ea-8848-f9b284e6af93.jpg)
2.
![freesnippingtool com_capture_20200617181743](https://user-images.githubusercontent.com/8250482/84916575-e928cd80-b0c6-11ea-82d1-cac13af2b5f0.jpg)
3.
![freesnippingtool com_capture_20200617181640](https://user-images.githubusercontent.com/8250482/84916587-ecbc5480-b0c6-11ea-8d95-764f1b564bbc.jpg)
4.
![freesnippingtool com_capture_20200617181936](https://user-images.githubusercontent.com/8250482/84916743-1ecdb680-b0c7-11ea-8966-1f476e9deac6.jpg)

**Comment by matthewrgourd** [comment]
Hi @geochrisgr, thanks for those. Could I also have your trading name and web address if you're ok posting on here? I need to check your details on our CRM.

**Comment by geochrisgr** [comment]
Do you have email to send it?

**Comment by matthewrgourd** [comment]
Please email mgourd@vivawallet.com quoting this issue (#1747). Thanks!

**Comment by matthewrgourd** [comment]
Hi @geochrisgr, thanks for sending through to my email. The settings all look fine and you're receiving successful payments. So I imagine this is an issue with one customer and related to their card issuer. Can you give me the date and approximate time when they attempted the purchase and got the error? Thanks!

**Comment by geochrisgr** [comment]
Hi the issue come with all viva order! the 500 error !

**Comment by matthewrgourd** [comment]
Hi @geochrisgr, regarding the order you mention, I've checked, and it definitely came in as a successful transaction on your Viva Wallet account so not sure what the problem is. However, I just attempted to buy something with a card with no funds and after payment I was incorrectly returned to the shopping cart page instead of the success page. To fix this, please try amending your payment source settings as below:

![Screenshot_2020-06-19_at_09_46_54](https://user-images.githubusercontent.com/44943019/85114696-41201b00-b212-11ea-8422-ce19441233a5.png)

**Comment by geochrisgr** [comment]
ok i have remove the / lets see if is ok ! :)

**Comment by geochrisgr** [comment]
OK.... i have custom success page.... i have desable the mod. and the order come with no issue!i want now to find a way that viva mod. is going to work with custom success page !
