### ISSUE TITLE
Redirect Checkout - recurring payment option

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1750]
Hi,

1) One of our customer paid using the Redirect flow checkout with recurring option. Now he wants to change the credit card details because it going to expire soon. Could you please tell us how to achieve this in recurring payment.
2) We need to cancel the recurring option, If the customer not will to proceed. please guide us to achieve this. If the " recurring support" flag not able to disable means chances are there to misuse. 

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, I thought I'd already answered your query in a previous issue, but I'll check again with the dev team. Thanks for providing further info.

**Comment by pavithra-itcs** [comment]
Is it possible to provide the API related to disable the recurring payments flag in Redirect Checkout?

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs i've had a reply from our dev team that it's not possible, unfortunately. The existing recurring payment will fail, so a new payment is required.
