### ISSUE TITLE
Installments 

### ISSUE THREAD

**Issue by marinavlr** [VivaPayments/API#1751]
It doesn’t show anything in the checkout for installments, although I have written the appropriate things at the settings, for example, 60:3,100:6.

**Comment by matthewrgourd** [comment]
The total amount per purchase has to be over 60 EUROS for 3 instalments to be offered and over 100 EUROS for 6 instalments to be offered. Is this the case?

**Comment by marinavlr** [comment]
Yes, but the problem is that at the checkout it doesn’t give the opportunity for instalments.

**Comment by matthewrgourd** [comment]
Have you tested with amounts higher than 60 or 100 EUROS?

**Comment by marinavlr** [comment]
Yes I have

**Comment by matthewrgourd** [comment]
Can I have your website address and trading name, please?

**Comment by marinavlr** [comment]
I am using the wordpress with the plugin “ Viva Payments - Viva Wallet WooCommerce Payment Gateway “ 
Website address www.xd-design.com.gr 
Trading name : Pandossou 10 shopping Center Ε.Ε

**Comment by matthewrgourd** [comment]
Hi @marinavlr thanks for providing those details. You seem to have two payment sources set up. Can you check that you added the instalments information to the currently active source which has an ID of 9318?

**Comment by marinavlr** [comment]
Yes this is correct. I have it on that.

Στις Δευ, 22 Ιουν 2020, 15:17 ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @marinavlr, ok, thanks. Can you send me a screenshot of your Viva Wallet payment module settings in WooCommerce, blurring out your Merchant ID and API key? This page:

![WooCommercePaymentsTab](https://user-images.githubusercontent.com/44943019/85295781-527a5900-b498-11ea-94d4-d9dc0b1d1292.png)

**Comment by marinavlr** [comment]
Yes, thank you for your help!


Στις Δευ, 22 Ιουν 2020 στις 4:55 μμ ο χρήστης matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @marinavlr, I've asked our dev team if there's anything we're missing. Apparently for instalments to work, all of the following must be true:

- Viva Wallet account set up in Greece
- amount must be 90 Euros or more
- card must be enabled for instalments.

Can you check these items and get back to me? Thanks!

**Comment by matthewrgourd** [comment]
Closing as no reply...
