### ISSUE TITLE
unsuccessful payments for orders received

### ISSUE THREAD

**Issue by AndreaVacca** [VivaPayments/API#1752]
Hi, in the last two days there have been orders received on the site for which payment has not been received on vivawallet. We ask you to check for what reasons it happened and if there were problems in the transactions as in the past. If there have been problems in the transactions we ask you to solve them. These are the order numbers for which the payments have not been successful:

#6824 | Giu 19, 2020

#6828 | Giu 19, 2020

#6838 | Giu 20, 2020

#6841 | Giu 20, 2020

#6844 | Giu 20, 2020

The website is: www.prodotti-cannabis.it

We await response, thank you, good job

**Comment by matthewrgourd** [comment]
Hi @AndreaVacca sorry to hear this. I can confirm no payments were received against those order numbers. No sign of anything, in which case, where did you get those order numbers from?

**Comment by AndreaVacca** [comment]
HI,
I get those order numbers from the database of order in my
website dashboard. In the dashboard the orders were present but the payment
on vivawallet no, for this reason I ask if the non-payment could derive
from your problems or perhaps from a abandonment of the payment screen by
the client. thank you

Il giorno lun 22 giu 2020 alle ore 12:09 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment]
@AndreaVacca I will need to ask a developer as I don't understand how a Viva Wallet order number could be present on another system if it isn't registered on our platform. Please bear with me.

**Comment by matthewrgourd** [comment]
Hi @AndreaVacca, the dev team got back to me and any order that isn't registered in your Viva Wallet account but has generated an order number in WooCommerce would be an abandoned payment page. Meaning a customer has got to the Viva Wallet payment page and decided against making a payment, entered incorrect details or failed 3DS. Hope this helps!

**Comment by AndreaVacca** [comment]
Today another 5 orders without payments:


Anteprima
<https://prodotti-cannabis.it/wp-admin/edit.php?post_type=shop_order&paged=1#>#6898
Yuri Buccino
<https://prodotti-cannabis.it/wp-admin/post.php?post=6898&action=edit> 4
ore fa
#6899 Esther Sananes
<https://prodotti-cannabis.it/wp-admin/post.php?post=6899&action=edit> 3
ore fa In attesa di pagamento
#6901 Silvia Adamo
<https://prodotti-cannabis.it/wp-admin/post.php?post=6901&action=edit> 1
ora fa In attesa di pagamento - 62,22€
#6902 Ilaria Pierangeli
<https://prodotti-cannabis.it/wp-admin/post.php?post=6902&action=edit> 1
ora fa In attesa di pagamento - 44,95€

Il giorno lun 22 giu 2020 alle ore 12:50 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment]
Hi @AndreaVacca what status do these orders show in WooCommerce?

**Comment by AndreaVacca** [comment]
Hi, "Pending Payment"


Il giorno mar 23 giu 2020 alle ore 12:17 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment]
Ok, so as I stated before, for whatever reason, these are orders that have been created in WooCommerce but customer has done one of the following for whatever reason:

- decided against making a payment
- entered incorrect payment details
- failed 3DS.

Please close this issue as there is no problem at the Viva Wallet end. We have already checked this for you.

**Comment by AndreaVacca** [comment]
Ok, thank you!

Il giorno mar 23 giu 2020 alle ore 14:00 matthewrgourd <
notifications@github.com> ha scritto:
