### ISSUE TITLE
wrong page after successful payment

### ISSUE THREAD

**Issue by purelywellness** [VivaPayments/API#1753]
When a customer successfully makes a payment, they are automatically directed to a search page which has the order number in the search window and a message saying the item was not found. This is resulting in confusion for the customer and uncertainty if their order has been processed correctly. They should be redirected back to the website shop page. I need to know if this is an issue that is on the viva wallet side or woocommerce and if viva wallet then i need to know how to rectify this please

**Comment by matthewrgourd** [comment]
Hi @purelywellness please may I have your website address to check? Also, the trading name you registered with Viva Wallet. Thank you!

**Comment by purelywellness** [comment]
Hi,
The website address is
Purelycbd.co.uk
The company name is Purely wellness.
Thank you
Regards John


Sent from Yahoo Mail for iPhone


On Monday, June 22, 2020, 1:18 pm, matthewrgourd <notifications@github.com> wrote:




Hi @purelywellness please may I have your website address to check? Also, the trading name you registered with Viva Wallet. Thank you!

**Comment by purelywellness** [comment]
Hi,
I think maybe the trading name was purely CBD.
Regards John


Sent from Yahoo Mail for iPhone


On Monday, June 22, 2020, 2:02 pm, john cartwright <jcartwrightuk@yahoo.co.uk> wrote:

Hi,
The website address is
Purelycbd.co.uk
The company name is Purely wellness.
Thank you
Regards John


Sent from Yahoo Mail for iPhone


On Monday, June 22, 2020, 1:18 pm, matthewrgourd <notifications@github.com> wrote:




Hi @purelywellness please may I have your website address to check? Also, the trading name you registered with Viva Wallet. Thank you!

**Comment by matthewrgourd** [comment]
Hi @purelywellness I just carried out two tests and I could see what the problem is. It was an error with your Success / Failure URLs in the payment source settings. I've fixed it for you now!

**Comment by purelywellness** [comment]
That’s great. Thank you very much.


Sent from Yahoo Mail for iPhone


On Monday, June 22, 2020, 3:04 pm, matthewrgourd <notifications@github.com> wrote:




Hi @purelywellness I just carried out two tests and I could see what the problem is. It was an error with your Success / Failure URLs in the payment source settings. I've fixed it for you now!
