### ISSUE TITLE
Error 403 https://uat-api.vivapayments.com/walletaccounts/v1/wallets

### ISSUE THREAD

**Issue by houssame17** [VivaPayments/API#1754]
Hello, 

I get access_token using https://demo-accounts.vivapayments.com/connect/token

and then I send request to https://uat-api.vivapayments.com/walletaccounts/v1/wallets, but it's always end with 403 error 

It seems like https://uat-api.vivapayments.com/walletaccounts/v1/wallets is not working.

PS : I m using a Sandbox account. 

thanks in advance for your help

**Comment by matthewrgourd** [comment]
Hi @houssame17, although documented within the Developer Portal, our Account API is currently unavailable to the outside world. Apologies for any inconvenience caused.
