### ISSUE TITLE
Incomplete transaction

### ISSUE THREAD

**Issue by TheHappyVaper** [VivaPayments/API#1755]
At the checkout, after selecting the Viva payment option, the site is re-directed. However, the page is taking too long to load and an error message is appearing and the transaction is not completing. 

I am running this on test mode. Please advise. Thanks

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this. May I ask which of our e-commerce plugins are you using?

**Comment by TheHappyVaper** [comment]
We are using shopify

**Comment by matthewrgourd** [comment]
Hi there, please try without test mode enabled and it should be fine. Let me know how you get on.

**Comment by TheHappyVaper** [comment]
Just to clarify, should I process a real transaction to test if it is working properly?

**Comment by matthewrgourd** [comment]
Yes, as I'm afraid test mode isn't working currently.

**Comment by TheHappyVaper** [comment]
ok. lastly, there is an option on Shopify to deactivate the viva payment provider and activate the bogus gateway to perform a test. Can you confirm that after testing I will be able to then reactivate the viva payment method easily? thanks.

**Comment by matthewrgourd** [comment]
Sorry, I'm not sure I fully understand. To test our payment gateway you need to have the Viva Wallet payment method enabled.

**Comment by TheHappyVaper** [comment]
As you stated the test mode for viva isn't working. I wanted to test through a bogus gateway but in order to do this I will have to deactivate the viva payment option temporarily. I just wanted to confirm after testing, that I can easily reactivate the viva payment option. Thanks.

**Comment by matthewrgourd** [comment]
That's correct, yes. Thanks.

**Comment by TheHappyVaper** [comment]
Matthew, thanks for your help. have a good day.
