### ISSUE TITLE
Πρόβλημα με την ενημέρωση του eshop με το IPN

### ISSUE THREAD

**Issue by terracom** [VivaPayments/API#176]
Χαίρετε,
παρατηρούμε ότι κάποιες φορές τις τελευταίες μέρες, μερικές συναλλαγές που ολοκληρώνονται επιτυχώς στο vivawallet (με redirection) δεν ενημερώνουν το sites μας, με αποτέλεσμα η παραγγελία στο eshop μας να μην ολοκληρώνεται.
Το web-site μας είναι πάντα On και επίσης, λαμβάνουμε κανονικά IPNs από άλλες υπηρεσίες (paypal).

Βέβαια, εμείς δε μπορούμε να ξέρουμε τι συνέβη και λάβαμε την ειδοποίηση από το vivawallet, καθώς δεν υπάρχει κάποιο ιστορικό που να φαίνεται κάτι τέτοιο. Το πιο πρόσφατο παράδειγμα αποτυχίας είναι η συναλλαγή με κωδικό συναλλαγής: 971eae8f-b904-4bfa-8e4a-23c618dfa7c4 (εάν θέλετε περισσότερα δεδομένα, παρακαλώ επικοινωνήστε μαζί μου, γιατί δε μπορώ να δώσω άλλες λεπτομέρειες εδώ).

Επίσης 2 είναι οι ερωτήσεις μας:
- Στην περίπτωση αποτυχίας ενημέρωσης του eshop με το IPN, επαναλαμβάνεται η προσπάθεια;
- Δεν έχω βρει κάπου στη διαχείριση του account μας. Υπάρχει κάποιο Log που να φαίνονται οι προσπάθειες ενημέρωσης του eshop με την εξόφληση;

Ευχαριστώ και αναμένω τις απαντήσεις σας.

**Comment by defilerc** [comment]
Καλησπέρα @terracom ,

Απ' ότι βλέπουμε η συγκεκριμένη συναλλαγή (971eae8f-b904-4bfa-8e4a-23c618dfa7c4) έχει γίνει processed με επιτυχία από τη Viva Payments.

Να σας ενημέρωσουμε πως σε πολύ σπάνιες περιπτώσεις (π.χ. λόγω απώλειας δικτύου από τη μεριά του χρήστη ή κάποιου server που είναι hosted το website του εμπόρου) το redirect να αποτύχει και ο χρήστης να μην φτάσει στη σελίδα του site σας.

Παρακαλώ βεβαιωθείτε ότι οι servers σας, δεν αντιμετωπίζουν κάποιο δικτυακό θέμα, καθώς η συγκεκριμένη περίπτωση θα έπρεπε να συμβαίνει πολύ σπάνια.

Σε κάθε περίπτωση μπορείτε να χρησιμοποίησετε και τη λειτουργικότητα των webhooks, ώστε να λαμβάνετε ενημέρωση για κάθε συναλλαγή που πραγματοποιείται και το αποτέλεσμά της (https://github.com/VivaPayments/API/wiki/Webhooks).

Αν παρόλαυτά, έχετε και άλλες συναλλαγές που πέφτουν σε αυτή την περίπτωση παρακαλώ πολύ στείλτε μας τα στοιχεία, ώστε να προχωρήσουμε σε διερεύνηση.

Με εκτίμηση,

**Comment by terracom** [comment]
Χαίρετε και πάλι,
τελικά, το πρόβλημα δεν ήταν ότι ο server μας ήταν μη διαθέσιμος και δεν ενημερώθηκε με την πληρωμή, αλλά ότι με πληρωμές όχι από card αλλά από το vivawallet του πελάτη, δεν στέλνεται το IPN στο eshop.
Αυτό είναι τσεκαρισμένο, γιατί μετά από έλεγχο στο eshop μας, διαπίστωσα ότι, όποιες πληρωμές είναι στο ιστορικό χαρακτηρισμένες σαν [Χρέωση VivaWallet] με αυτές έχουμε πρόβλημα.

Επίσης, είμαι σίγουρος ότι τίποτα δεν εστάλη (τουλάχιστον για μία συναλλαγή που έγινε χτες), επειδή όταν έρχεται κάποιο web-request στο url ενημέρωσης επιτυχούς συναλλαγής, το πρώτο πράγμα που κάνουμε είναι να γράφουμε στο log, όλη την πληροφορία που μας στέλνεται.

Μπορείτε παρακαλώ να εξετάσετε το πρόβλημα;
Ευχαριστώ

**Comment by terracom** [comment]
Χαίρετε και πάλι,
Για να γίνω πιο ξεκάθαρος, η ερώτησή μου από το προηγούμενο post είναι:
Είναι γνωστό θέμα το ότι, οι πληρωμές που κάνουν οι πελάτες μας από vivawallet και όχι από κάρτα, δεν ενημερώνουν το eshop (άρα πρέπει να χρησιμοποιήσουμε τα web-hooks), ή κάποιο άλλο θέμα υπάρχει και δεν ενημερωνόταν το eshop μας με IPN;
Ευχαριστώ

**Comment by defilerc** [comment]
Καλησπέρα @terracom ,

Δε χρειάζεται να δημιουγήσετε κάποιο webhook για να λάβετε ειδοποίηση για το αν έγινε επιτυχής ή αποτυχής πληρωμή με viva wallet.

Όταν ο χρήστης επιλέξει να πληρώσει με viva wallet, η διαδικασία που ακολουθείται είναι η ίδια με την πληρωμή με κάρτα. Δηλαδή, θα κατευθυνθεί είτε στο success url, είτε στο fail url με κάποιες επιπλέον παραμέτρους στο URL.

Θα θέλαμε να μας πείτε περισσότερες πληροφορίες για το πρόβλημα:

- Η συναλλαγή που δοκιμάσατε ήταν επιτυχής ή ανεπιτυχής;
- Σε ποιό URL έγινε η ανακατεύθυνση και με ποιές παραμέτρους;

Ευχαριστούμε πολύ,


Εσάς ποιό από τα δύο συμβαίνει; Ποιό είναι το URL που ανακατευθύνεται ο χρήστης;

**Comment by terracom** [comment]
Καλημέρα σας,

όπως σας είπα και στο προηγούμενο post, μιλάμε πάντα για επιτυχείς συναλλαγές, πληρωμής όχι από κάρτα, αλλά από vivawallet . Στο ιστορικό, στο vivawallet.com φαίνονται κανονικά χρεωμένες στον πελάτη.
Το url για την πηγή πληρωμής 4622 (για να μη βάλω και το domain εδώ που είναι public) είναι το payments/vivawallet/success

Σε αυτό, ότι GET κλήση γίνεται, πρώτα γράφεται στο log και μετά κάνουμε οτιδήποτε άλλο. Δεν λαμβάνουμε όμως κάποια κλήση, στην περίπτωση πληρωμής με vivawallet.

Εμείς έχουμε υλοποιήσει ήδη πληρωμή με Native checkout. Θα προσθέσουμε και την επιλογή πληρωμής με vivawallet και δε θα αντιμετωπίζουμε αυτό το πρόβλημα. Αυτό το θέμα απλώς σας το αναφέρω, μήπως υπάρχει κάποιο γενικότερο θέμα και θα βοηθηθεί κάποιος άλλος χρήστης του vivapayments.

Ευχαριστώ

**Comment by defilerc** [comment]
Καλησπέρα @terracom ,

Μπορείτε να αναπαράξετε το πρόβλημα; Θα θέλαμε να μας πείτε σαν χρήστης που πάει να κάνει πληρωμή, ποιά είναι η συμπεριφορά που αντιμετωπίζετε όταν κάνετε μια επιτυχής - όπως είπατε, πληρωμή με Viva Wallet.

Εμείς από τη μεριά μας δε βλέπουμε κάποιο λάθος στις συναλλαγές σας και γι' αυτό θα θέλαμε να μας βοηθήσετε στην αναπαραγωγή του προβλήματος.

Με εκτίμηση,

**Comment by terracom** [comment]
Χαίρετε και πάλι,
δεν ξέρω τι έγινε τις προηγούμενες φορές, αλλά αυτή τη φορά πήραμε IPN για μια χρέωση από vivwallet και είχαμε και καταχώρηση στο log.
Τελικά, το πρόβλημα ήταν όντως από εμάς, γιατί το TransactionTypeId ήταν 9 αντί για 5 (Credit card charge) και δεν είχαμε πρόβλεψη τι θα συμβαίνει σε αυτή τη περίπτωση.
Το διορθώσαμε. 

Ευχαριστούμε πολύ και συγνώμη για την ταλαιπωρία. Μπορείτε να κλείσετε το ticket! :-)

**Comment by defilerc** [comment]
Ευχαριστούμε πολύ για την ενημέρωση!
