### ISSUE TITLE
Successful or Unsuccessful payment returns with an error page not found

### ISSUE THREAD

**Issue by costascy** [VivaPayments/API#1761]
The transaction is completed successful but returns with an error page not found, and in Woo eCommerce orders status is **Pending payment**.

I added the return Successful to website app as shown bellow but still have an issue.
 
![Screenshot](https://user-images.githubusercontent.com/67457434/85833240-13028400-b79a-11ea-8a76-3a68f5e606ee.jpg)

**Comment by matthewrgourd** [comment]
Hi @costascy, sorry to hear this. I see that you're using WooCommerce. Does this mean you've installed our WooCommerce plugin? If so, please check the [documentation](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) as I notice you've got the Success / Failure URLs wrong when setting up the payment source in the Viva Wallet banking app:

INCORRECT
Success URL – `/successful-payment/`
Failure URL – `/unsuccessful-payments/`

**CORRECT**
Success URL – `index.php?wc-api=wc_vivawallet&vivawallet=success`
Failure URL – `index.php?wc-api=wc_vivawallet&vivawallet=fail`

Hope this helps!
