### ISSUE TITLE
3DS Secure transaction no RedirectToACSForm returned

### ISSUE THREAD

**Issue by SchrisAylon** [VivaPayments/API#1762]
We recently noticed that while trying to make a payment, when calling the 
https://api.vivapayments.com/nativecheckout/v2/chargetokens
 With body: {"amount":1050.0,"cvc":"Right_CVV","expirationMonth":10,"expirationYear":2022,"holdername":"THE_HOLDER_NAME","number":"4567XXXXXXXXXXXX","sessionRedirectUrl":"https://www.example.com/"}
we get the following response:
ChargeToken: ctok_zdgE3OOlkKNqWakYnX0Mi0shhlQ
RedirectToACSForm: null

As you can see the RedirectToACSForm is returned as null and we can proceed to the payment. This affects our already working application which in turn affects our sales.

**Comment by SchrisAylon** [comment]
MerchantId = "bfe10622-3b64-486a-bf18-a7d98fa31977"

**Comment by matthewrgourd** [comment]
Hi @SchrisAylon please give me an alternative way of finding you on our CRM? Account name, VAT number or website address will do? Otherwise I will need to close this issue...

**Comment by SchrisAylon** [comment]
Dear @matthewrgourd the problem has been solved. It seems that for a reason the app has changed status to "Under Review". Now everything works fine. Thanks

**Comment by matthewrgourd** [comment]
Hi @SchrisAylon thanks for letting me know! Closing issue now...

**Comment by Alexookah** [comment]
@matthewrgourd I have the same issue in the following merchant ID: 

e6443905-30a6-4428-a320-64f232116ad1

The redirectToACSForm from the response is null.

Can you check it out please?

**Comment by matthewrgourd** [comment]
Hi @Alexookah, this normally only happens if the card isn't 3DS enabled. I've just tested the below request using a 3DS enabled card and it works:

POST `https://api.vivapayments.com/nativecheckout/v2/chargetokens`
**Request body**
```
{
    "Amount": 100,
    "Cvc": "[xxx]",
    "Number": "[xxxxxxxxxxxxxxxx]",
    "Holdername": "[name]",
    "ExpirationYear": [year],
    "ExpirationMonth": [month],
    "SessionRedirectUrl": "https://www.example.com"
}
```
**Response**
```
{
    "chargeToken": "[charge_token]",
    "redirectToACSForm": "<!DOCTYPE html SYSTEM \"about:legacy-compat\">\n<html class=\"no-js\" lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n<meta charset=\"utf-8\"/>\n<title>3D Secure Processing</title>\n<link href=\"https://mpi.viva.modirum.com/mdpaympi/static/mpi.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>\n<body>\n<div id=\"main\">\n<div id=\"content\">\n<div id=\"order\">\n<h2>3D Secure Processing</h2>\n<img src=\"https://mpi.viva.modirum.com/mdpaympi/static/preloader.gif\" alt=\"Please wait..\"/>\n<img src=\"https://mpi.viva.modirum.com/mdpaympi/static/verifiedbyvisa.png\" alt=\"Verified by VISA\"/>\n<div id=\"formdiv\">\n<script type=\"text/javascript\">\nfunction hideAndSubmitTimed(formid)\n{\nvar timer=setTimeout(\"hideAndSubmit('\"+formid+\"');\",100);\n}\n\nfunction hideAndSubmit(formid)\n{\nvar formx=document.getElementById(formid);\n\tif (formx!=null)\n\t{\n\tformx.style.visibility=\"hidden\";\n\tformx.submit();\n\t}\n}\n</script>\n<div>\n<form id=\"webform0\" name=\"red2ACSv1\" method=\"POST\" action=\"https://www.securesuite.co.uk/hbos/tdsecure/opt_in_dispatcher.jsp?partner=hx_vdc&amp;VAA=B\" accept_charset=\"UTF-8\">\n<input type=\"hidden\" name=\"_charset_\" value=\"UTF-8\"/>\n<input type=\"hidden\" name=\"PaReq\" value=\"[value]"/>\n<input type=\"hidden\" name=\"MD\" value=\"[value]"/>\n<input type=\"hidden\" name=\"TermUrl\" value=\"https://www.vivapayments.com/web/checkout/threedsecurevalidation\"/>\n<input type=\"submit\" name=\"submitBtn\" value=\"Please click here to continue\"/>\n</form>\n</div>\n</div>\n<script type=\"text/javascript\">\n\t\t\thideAndSubmitTimed('webform0');\n\t\t</script>\n<noscript>\n<div align=\"center\">\n<b>Javascript is turned off or not supported!</b>\n<br/>\n</div>\n</noscript>\n</div>\n<div id=\"content-footer\">\n<br/>\n<img height=\"20\" src=\"https://mpi.viva.modirum.com/mdpaympi/static/powered-by-modirum.svg\" alt=\"Powered by Modirum\"/>\n</div>\n</div>\n</div>\n</body>\n</html>\n"
}
```

**Comment by Alexookah** [comment]
OK. 
So there is a case where some cards do not have 3DS enabled and the SessionRedirectUrl is null.
I just tested with only using the chargeToken and i get a 403 error.

@matthewrgourd

**Comment by matthewrgourd** [comment]
403 error means authentication failure. Please check the below for information on generating a bearer token which is needed for the example call above to work:

https://developer.vivawallet.com/authentication/#oauth-2-token-generation

**Comment by matthewrgourd** [comment]
@Alexookah, sorry, I meant to say also that our payment platform supports only 3DS-enabled cards. This meets the [PSD2 SCA](https://en.wikipedia.org/wiki/Strong_customer_authentication) requirement.

**Comment by Alexookah** [comment]
@matthewrgourd I am getting error 500. any idea why?
