### ISSUE TITLE
API  unavailable?

### ISSUE THREAD

**Issue by northernDee** [VivaPayments/API#1765]
Customers trying to pay are getting this message:

Thank you - your order is now pending payment. You should be automatically redirected to Vivapayments to make payment.
Wrong Merchant crendentials or API unavailable 

I have obviously checked all my details are correct. Website should be linked to my account as of yesterday.

**Comment by matthewrgourd** [comment]
Hi @northernDee, sorry to hear this. Can I have the website address and your Viva Wallet account name, please?

**Comment by northernDee** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  HiI've got it sorted now thanks though! I just had the wrong plugin.                                                                                                                                        Cheers for getting back to me so quickly.       Kate SharkeyNorthern Delights CBDww.northerndelightscbd.co.uk                                                                                                                                                                           From: notifications@github.comSent: 30 June 2020 2:20 p.m.To: API@noreply.github.comReply to: reply@reply.github.comCc: kate@northerndelightscbd.co.uk; mention@noreply.github.comSubject: Re: [VivaPayments/API] API  unavailable? (#1765)  
Hi @northernDee, sorry to hear this. Can I have the website address and your Viva Wallet account name, please?

**Comment by matthewrgourd** [comment]
Hi @northernDee no problem, in that case I'll close the issue now...
