### ISSUE TITLE
Recurring payments option(check box) - Redirect checkout

### ISSUE THREAD

**Issue by HarishankarIT** [VivaPayments/API#1766]
Hi,

One of my client while doing payments using your redirect checkout, client selected checkBox("I allow future or recurring payments for this card") for future recurring payment.
After some days clients wants to Disable(Cancel) that recurring payment option.
how to do that please let us know.

Regards,
hariIT

**Comment by matthewrgourd** [comment]
Once the flag has been set, it's not possible to disable it, I'm afraid. Customer would need to cancel Direct Debit via their bank.
