### ISSUE TITLE
Cannot GET /api/transactions in Callback Magento 2.1.0

### ISSUE THREAD

**Issue by arpanabbacus** [VivaPayments/API#1767]
I have tried to place an order and after callback Url executed I got 400 Page and I had debug the code and I got the response from curl Which is "Cannot GET /api/transactions".

What's the issue in it?

Can you please look into this ASAP?

Thanks

**Comment by matthewrgourd** [comment]
Sorry to hear this. First of all, please can I confirm that you're attempting to install our plugin for Magento 2.1 documented here? https://developer.vivawallet.com/e-commerce-plugins/magento2.1-2.2/

**Comment by arpanabbacus** [comment]
yes @matthewrgourd, I have followed the steps which are described in the above link.

**Comment by matthewrgourd** [comment]
Do you have a live website I can check? Also, if I could have your Viva Wallet account name or VAT number? Ideally, if you could also send through a screenshot of the payment module settings in Magento, obscuring any confidential information. Thanks...

**Comment by arpanabbacus** [comment]
Yes, we have a live website and we have to integrate the viva wallet on the site. the site URL is: https://www.crimsonbuddha.com/

Viva Wallet Account Name is: GINGE DULAI LIMITED

**Comment by matthewrgourd** [comment]
Hi, I've checked your settings. Everything looks fine except can you try leaving "Installments" blank? I've had to delete the screenshot now as it's showing confidential information. Another thing I noticed is that some of the checkboxes during the checkout process are difficult to enable. The last one "Accept the terms and conditions" won't work at all in Google Chrome. Your theme doesn't seem to work with all browsers. Can you maybe try another one?

**Comment by arpanabbacus** [comment]
Hi, I have tried to check out and I have successfully placed the order but when it comes back from Viva Wallet payment and the callback executed at that time it gives me this error "Cannot GET /api/transactions in Callback Magento 2.1.0"

**Comment by matthewrgourd** [comment]
Hi @arpanabbacus having looked again at your installation, it looks like there is a theme issue. Please try again with another theme. Our plugin is working fine.

**Comment by arpanabbacus** [comment]
Hi @matthewrgourd 

We have other payment methods like Paypal and it is working very well. I got this response from the cUrl method which is located at callback URL then how it's possible that there is an issue with the theme?

**Comment by matthewrgourd** [comment]
Hi @arpanabbacus, actually, I see what you're saying, it does seem that way. Let me check further and get back to you.

**Comment by matthewrgourd** [comment]
Hi @arpanabbacus, the original developer of the plugin has tested it and is unable to recreate the issue. We are therefore unable to help any further. It must be a local issue with your instance of Magento. Please contact their [support team](https://magento.com/contact-us).

**Comment by arpanabbacus** [comment]
Hi @matthewrgourd 

I have checked with the default luma theme but I got the same error response. So Here I have sent you the Curl Request Info. You can see I have pasted the array of the request and we have call this URL 'https://www.vivawallet.com/api/transactions?ordercode=9871257578746011' via cUrl and we got this error "**Cannot GET /api/transactions**". I have also attached the screenshot in which the same error I have face and this error comes from the VivaWallet API server.

Array
(
    [url] => https://www.vivawallet.com/api/transactions?ordercode=9871257578746011
    [content_type] => text/html; charset=utf-8
    [http_code] => 404
    [header_size] => 422
    [request_size] => 215
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.19988
    [namelookup_time] => 0.012301
    [connect_time] => 0.019165
    [pretransfer_time] => 0.173076
    [size_upload] => 0
    [size_download] => 155
    [speed_download] => 775
    [speed_upload] => 0
    [download_content_length] => 155
    [upload_content_length] => 0
    [starttransfer_time] => 0.199836
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 23.10.252.71
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 141.0.164.244
    [local_port] => 49806
)

![viva_wallet](https://user-images.githubusercontent.com/41432910/86733554-ec243780-c04e-11ea-8db3-4ad448e20ef3.png)

**Comment by arpanabbacus** [comment]
Hi @matthewrgourd 

It's working now. Thanks for your help.
