### ISSUE TITLE
PAX App

### ISSUE THREAD

**Issue by makelarisjr** [VivaPayments/API#1769]
Is it possible to get the latest aip file for the pax s800?

**Comment by matthewrgourd** [comment]
Sorry, @makelarisjr, please can you give me a bit more background on what it is you're attempting to do.

**Comment by makelarisjr** [comment]
I'm trying to install the latest version using TermAssist

**Comment by matthewrgourd** [comment]
I'm sorry, I don't understand what issue it is you're attempting to solve and how it involves Viva Wallet. Please elaborate if you can...

**Comment by makelarisjr** [comment]
I'm trying to install the latest version of the viva wallet application on my pax s800 but i can't find anywhere the AIP(Application Installation Package) file.

**Comment by matthewrgourd** [comment]
I'm sorry, we don't understand what you're attempting to do exactly. Please provide some more background information.

**Comment by makelarisjr** [comment]
Is it possible to talk directly with the POS developer?

**Comment by matthewrgourd** [comment]
Hi @makelarisjr I'm afraid not, but I can pass on any additional information directly. He has seen what you posted but doesn't understand exactly what it is you're attempting to do or the context. So please elaborate if you can!

**Comment by matthewrgourd** [comment]
Closing as no reply
