### ISSUE TITLE
Ερώτηση σχετικά με έλεγχο χρημάτων

### ISSUE THREAD

**Issue by bolanakis** [VivaPayments/API#177]
Καλή σας ημέρα, 
έχω επιχείρηση κατασκευής ιστοσελίδων και παροχής υποστήριξης και θα ήθελα να βάλω σύστημα πληρωμών μέσω viva. Αυτό που θέλω να ρωτήσω είναι το εξής: "**Μπορώ μέσα από το σύστημα της viva να ελέγξω αν ο πελάτης έχει χρήματα μέσα στη κάρτα του ώστε στη συνέχεια να επιτρέψει το σύστημά μου να προχωρήσω στη υποστήριξη ή αν δε τα έχει να μη προχωρήσει η διαδιακασία**?"

**Comment by defilerc** [comment]
Καλημέρα @bolanakis ,

Υπάρχει η επιλογή μέσω του VivaPayments API για δέσμευση χρημάτων, αντί για κανονική χρέωση. Σε αυτή την περίπτωση το ποσό δεσμεύεται από το διαθέσιμο υπόλοιπο του πελάτη, επομένως θα πρέπει να εξετάσετε σοβαρά αν θέλετε να χρησιμοποιήσετε το συγκεκριμένο τρόπο, καθώς και να ενημερώνετε τον πελάτη σχετικά.

Ευχαριστούμε πολύ για την επικοινωνία,
