### ISSUE TITLE
Native Checkout v2 3DS show errors on wrong Card Number, CVV, Date

### ISSUE THREAD

**Issue by ddrosatos** [VivaPayments/API#1770]
Hello. We have implemented the Native Checkout v2 3DS as described in the documentation, and everything is working as expected. The issue i am facing is when i use wrong credit card number, cvv or date that is in the past.

Wrong CVV and old date continues to 3ds with no error and the transaction is completed without any issues. Is this due to the test environment? What is the response of https://demo-api.vivapayments.com/nativecheckout/v2/transactions in these situations?

Wrong card number gives a 400 Bad request on VivaPayments.cards.requestToken using the fail function. The request returns in network XHR response {"status":400,"message":"CardsCreateValidationFailedInvalidCardNumber","eventId":"6000"}. I want to show the user that he entered wrong card number. How can i do this?

**Comment by matthewrgourd** [comment]
Hi @ddrosatos, the short answer is that there is no way of testing 3DS without doing it on production with a real card. Our demo option delivers a pseudo 3DS popup but is not intended to fully mimic the real world. I will need to check further before I can give you a longer answer.

**Comment by matthewrgourd** [comment]
Hi @ddrosatos, sorry for the extended delay. Please check the source code of our plugin for WooCommerce which is an implementation of our Native Checkout v2 solution and contains various error handling options. 
[viva-wallet-for-woocommerce.zip](https://github.com/VivaPayments/API/files/5006198/viva-wallet-for-woocommerce.zip) Hope this helps.
