### ISSUE TITLE
Problème après paiement Woocommerce/Vivawallet

### ISSUE THREAD

**Issue by Motionis** [VivaPayments/API#1772]
Bonjour,
Je n'arrive absolument pas a faire fonctionner le paiement. En fait, après avoir payé, le site revient à la page de checkout. A priori le paiement a fonctionné mais le site n'as pas redirigé sur la bonne page. Nous avons essayé tous les parametres possibles de pages de paiement dans vivawallet et woocommerce mais rien n'y fait.

Bien à vous,
Nathan.

**Comment by matthewrgourd** [comment]
Hi there, are you attempting to set up our WooCommerce plugin that we've made available as a download on this page? https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ Can I have the URL of your website and the merchant name registered with Viva Wallet? Thanks, Matt

**Comment by Motionis** [comment]
Hi,
Yes i'ts the good plugin. The payments work (and arrive on VivaWallet) but
the buyer, after paying, is not redirected to a payment success page (he
automatically returns to the chekout page, where he must put his delivery
information then click on "order" when he has already done so).
The links to success payment and payment failure are the ones given in your
doc. But no matter which links I put, after the payment the customer always
returns to the same page.

The URL of the website is ogspace.fr
The merchant name registered with Viva Wallet is Nathan Valeyre.

Thanks,
Nathan.

Le jeu. 9 juil. 2020 à 18:07, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @Motionis I amended the domain name specified in the payment source which you had as  `www.ogspace.fr` instead of `ogspace.fr`. Please test your payment page and close this issue if no further problems. Thanks!

**Comment by Motionis** [comment]
Hi Matthew !
I don't know how to thank you, it finally works! Thank you very much, it
was silly but we would not have found it without you.

Good day to you !

Le lun. 13 juil. 2020 à 10:32, matthewrgourd <notifications@github.com> a
écrit :

**Comment by lagregs** [comment]
Hi Everyone, 

I have the same problem as Motionis. Do you think you can help me to ? @matthewrgourd 
The URL : acbd-shop.fr
Viva wallet : ACBD 

Thank you so much

**Comment by matthewrgourd** [comment]
Hi @lagregs this issue is now closed. Please open a new issue with full details of your problem via our [GitHub issues home page](https://github.com/VivaPayments/API/issues) (New Issue button).
