### ISSUE TITLE
Simile check out activation

### ISSUE THREAD

**Issue by isaajoint** [VivaPayments/API#1773]
Dear support i need to activate simple check out for my account. Development is already done. Please can you tell me how to proceed? Thanks

**Comment by matthewrgourd** [comment]
Hi @isaajoint, please email me on mgourd@vivawallet.com with your Merchant ID and I will enable the Simple Checkout API for you. If you're trying out on demo, please send your demo Merchant ID. If you're launching on production, it should be the Merchant ID for your live account.

**Comment by matthewrgourd** [comment]
Hi @isaajoint thanks for your email. This is enabled now.
