### ISSUE TITLE
Why Native Checkout v2 3DS asks for bank credentials

### ISSUE THREAD

**Issue by alkatsaros** [VivaPayments/API#1774]
We have a client that complaint that our checkout asks for bank credentials. I couldn't replicate it.
![image](https://user-images.githubusercontent.com/26555214/87138999-f3924d80-c2a7-11ea-89ea-b69c080193a1.png)

You can see the issue in above image. How can this happen?

Thanks in advance!

**Comment by alkatsaros** [comment]
Is this screen part of the authentications method? I mean instead of SMS or push notifications to mobile app.
I have never seen it gain and I am afraid possible fraudulent.

**Comment by matthewrgourd** [comment]
Hi @alkatsaros I'm not sure as each card issuer has a different way of doing 3DS (it isn't handled by Viva). If in doubt, get your customer to try a different card.

**Comment by alkatsaros** [comment]
Thanks @matthewrgourd . I called bank and they activated stronger authentication since last Monday. So you can close this issue.

**Comment by matthewrgourd** [comment]
Thanks!
