### ISSUE TITLE
TPV Webservice

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1776]
Good morning @matthewrgourd! This merchant Inconel Administration Limited is interested in testing webservice with his tpv (S./N: 90205144) I would need the following data regarding his tpv credentials, could you provide it me for informing the merchant?:

commerce_id=                
servicio=                           
passwd:         

Thx in advance

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I have no idea what that means, I'm afraid! Please provide further info. if possible. Thank you.

**Comment by Alvaroalconada** [comment]
I mean, is a software that is installed on a computer to manage the ways of payment of your business
have this modality our devices?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada I'm sorry, I still don't understand what the requirement is. Please speak to me on MS Teams as GitHub is for communicating with customers directly. Thanks!
