### ISSUE TITLE
OrderCode

### ISSUE THREAD

**Issue by kyrkonpmi** [VivaPayments/API#1778]
Hi, is ti possible to Create payment order but the client to not receive email from Viva but only my email.

As Viva api for how to Create payment order
serviceId | integer <int32>If you wish to create a Payment Order without redirecting the customer to the payment page, use the value "4" **and the system will automatically send your customer an e-mail notification**. This is equivalent to the Payment Notification option from the merchant environment.

Probably if i use other serviceId?

Regards,

Kyriakos Kontos

**Comment by matthewrgourd** [comment]
Hi @kyrkonpmi yes, I believe it can be switched off at account level. If you wanted to test I would need your Viva Wallet account name. Thanks.

**Comment by kyrkonpmi** [comment]
Hi @matthewrgourd thank you for your reply but what i am looking is to dissable the email from Vivawallet to customers into API level because sometimes i need the email but sometimes not. Regards

**Comment by matthewrgourd** [comment]
As far as I'm aware, this cannot be controlled via our API. Best regards..
