### ISSUE TITLE
OC 2.3.0.2 - Problem with products 

### ISSUE THREAD

**Issue by charalambos88** [VivaPayments/API#1779]
For Opencart 2.3.0.2 we are having a strange problem. The customer add 5 products to the cart, paid for 5 products (redirect to viva site), after the return we see only 3 products at this cart (admin). The customer paid for 5 products.

**Comment by matthewrgourd** [comment]
Sorry to hear this. Could be an isolated issue, but I can look into it for you. What is your website address?

**Comment by charalambos88** [comment]
Hi, it's https://thegamerules.com/

**Comment by matthewrgourd** [comment]
Hi @charalambos88 I just tested with 10 items using a card with no funds. Can you see if you get a similar result in terms of the order quantity?

**Comment by charalambos88** [comment]
Tried the order quantity is correct. Maybe the problem happened for the first time.

**Comment by matthewrgourd** [comment]
Closing as unable to recreate issue
