### ISSUE TITLE
Invalid Card Number

### ISSUE THREAD

**Issue by dskalidis** [VivaPayments/API#178]
Καλησπέρα, 

Ενώ έχω κάνει όλη την διαδικασία για την viva πληρωμή στο τέλος μου βγάζει error 412 Invalid Card Number. Η κάρτα που χρησιμοποιώ είναι 4111111111111111 με CVV 111. Το τοκεν φτιάχνεται κανονικά και ποστάρεται μαζί με την φόρμα. Έχετε καμιά ιδέα τι μπορεί να φταίει?

MerchantID: 5e69b107-ced3-462b-81cb-8006c08b5d93

**Comment by dskalidis** [comment]
Το token είναι:

aIhwc3yNL9TniTqMqvpoyspTIOtDK3TaJS/8Tn9CfK2+4Y727OgLQWCtAE76nMHSU5JUzpKTkihBTF2lQkSwtqVXyPAMCef1zZI6/XHyoAVx95ucUKot7wE9HMWPlIT3cd308wY+s/+76nEm9VQB2wxyBrcu5e5beZNzuUE/yVg9tR8TjczoaDiJGMwOXkmbKa91VRAGk06lCvfF1VNyW0vISYs7o0tgcl9gMRryrKOBUbH7m43uTL+983HTxzgKG0U7wbQ2VHTiOUFCbjh5fgMENfm/NZ0CeHP5ZxrE1SpRxk/ksKWaACrDNQVGjx9vbOFfW4UaLKvJzSnEutERVtSdGkCH268z

**Comment by defilerc** [comment]
Καλησπέρα @dskalidis ,

Καταρχάς θα θέλαμε να μας επιβεβαιώσετε ότι σαν integration method χρησιμοποιείται την Native Checkout (https://github.com/VivaPayments/API/wiki/Native-Checkout).

Η διαδικασία γενικά είναι ότι στο πρώτο βήμα θα πρέπει να πάρετε το token και στη συνέχεια όταν πάτε να κάνετε κλήση στην `/api/transactions` θα πρέπει να περάσετε στα `CreditCardOptions` το token της κάρτας που πήρατε από το 1ο βήμα και όχι το νούμερο και το CVC.

Αν συνεχίζετε και αντιμετωπίζετε πρόβλημα, παρακαλώ πολύ στείλτε μας sample κώδικα που να φαίνονται οι κλήσεις για: 1. το tokenization, 2. της CreateOrder και 3. για την προσπάθεια χρέωσης του Order, ώστε να δούμε λεπτομερώς τι έχει συμβεί.

Με εκτίμηση

**Comment by dskalidis** [comment]
public static OrderResult CreateOrder(IApiAuthenticationSettings settings, VivaNativeTransactionDetails transactionDetails)
    {
      RestClient client = ApiClient.GetClient(settings);
      RestRequest restRequest1 = new RestRequest("/api/orders", Method.POST);
      restRequest1.AddObject((object) new
      {
        Amount = (int) Math.Truncate(transactionDetails.TotalAmount * new Decimal(100)),
        SourceCode = transactionDetails.SourceCode,
        MerchantTrns = transactionDetails.TransactionID
      });
      RestRequest restRequest2 = restRequest1;
      IRestResponse<OrderResult> restResponse = client.Execute<OrderResult>((IRestRequest) restRequest2);
      if (restResponse == null)
        return (OrderResult) null;
      return restResponse.Data;
    }

**Comment by dskalidis** [comment]
public static TransactionResult CreateTransaction(IApiAuthenticationSettings settings, OrderResult order, VivaNativeTransactionDetails transactionDetails)
    {
      RestClient client = ApiClient.GetClient(settings);
      RestRequest restRequest1 = new RestRequest("/api/transactions", Method.POST);
      restRequest1.AddObject((object) new
      {
        OrderCode = order.OrderCode,
        SourceCode = transactionDetails.SourceCode,
        CreditCard = new
        {
          Token = transactionDetails.CreditCardToken
        }
      });
      RestRequest restRequest2 = restRequest1;
      IRestResponse<TransactionResult> restResponse = client.Execute<TransactionResult>((IRestRequest) restRequest2);
      if (restResponse == null)
        return (TransactionResult) null;
      return restResponse.Data;
    }

**Comment by dskalidis** [comment]
public static OrderResult CreateOrder(IApiAuthenticationSettings settings, VivaNativeTransactionDetails transactionDetails)
{
RestClient client = ApiClient.GetClient(settings);
RestRequest restRequest1 = new RestRequest("/api/orders", Method.POST);
restRequest1.AddObject((object) new
{
Amount = (int) Math.Truncate(transactionDetails.TotalAmount * new Decimal(100)),
SourceCode = transactionDetails.SourceCode,
MerchantTrns = transactionDetails.TransactionID
});
RestRequest restRequest2 = restRequest1;
IRestResponse restResponse = client.Execute((IRestRequest) restRequest2);
if (restResponse == null)
return (OrderResult) null;
return restResponse.Data;
}

**Comment by dskalidis** [comment]
protected override void Process(Transaction transaction, VivaNativeConfiguration configuration)
    {
      VivaNativeTransactionDetails transactionDetails = transaction.GetItem<VivaNativeTransactionDetails>();
      PaymentState paymentState = transaction.GetOrCreateItem<PaymentState>();
      OrderResult order = ApiClient.CreateOrder((IApiAuthenticationSettings) configuration, transactionDetails);
      Assert.IsNotNull((object) order, "Viva payments failed unexpectedly (could not create order)");
      if (order.ErrorCode > 0)
      {
        paymentState.ErrorCode = order.ErrorCode.ToString();
        paymentState.ErrorDescription = order.ErrorText;
        paymentState.Status = PaymentStatus.Failed;
      }
      else
      {
        TransactionResult transaction1 = ApiClient.CreateTransaction((IApiAuthenticationSettings) configuration, order, transactionDetails);
        Assert.IsNotNull((object) order, "Viva payments failed unexpectedly (could not create transaction)");
        if (transaction1.ErrorCode > 0)
        {
          paymentState.ErrorCode = transaction1.ErrorCode.ToString();
          paymentState.ErrorDescription = transaction1.ErrorText;
          paymentState.Status = PaymentStatus.Failed;
        }
        else if (transaction1.StatusId != "F")
        {
          paymentState.ErrorCode = transaction1.ErrorCode.ToString();
          paymentState.ErrorDescription = transaction1.ErrorText;
          paymentState.Status = PaymentStatus.Failed;
        }
        else
        {
          paymentState.Status = PaymentStatus.CompletedSuccesfully;
          transaction.SetItem<VivaNativePaymentProviderState>(new VivaNativePaymentProviderState()
          {
            Transaction = transaction1,
            Order = order
          });
        }
      }
    }

**Comment by dskalidis** [comment]
Δυστυχός το πρόβλημα συνεχίζει και υπάρχει.

**Comment by defilerc** [comment]
Καλημέρα @dskalidis ,

Από τα logs βλέπουμε δύο θέματα:

- Το πρώτο είναι ότι αποτυγχάνει το tokenization της κάρτας με την ένδειξη Invalid Card Number, όπως είχατε αναφέρει κι εσείς αρχικά. Αυτό όμως έρχεται σε αντίφαση με το γεγονός ότι έχετε πάρει ήδη κάποιο token, το οποίο και ποστάρατε στην ερώτησή σας.

Για την επίλυση του πρώτου θέματος, παρακαλώ πολύ βεβαιωθείτε ότι στη javascript και συγκεκριμένα στην `VivaPayments.cards.setup()` έχετε ορίσει σωστά το publicKey, πως στην html υπάρχουν τα πεδία για τον όνομα κατόχου της κάρτας, τον αριθμό της κάρτας, την ημερομηνία λήξης και το cvv με τα αντίστοιχα `data-vp` attributes:

```
data-vp="cardholder"
data-vp="cardnumber"
data-vp="cvv"
data-vp="month"
data-vp="year"
```

Είναι σημαντικό τα `data-vp` attributes να υπάρχουν έτσι ακριβώς, ώστε να μπορέσει η κλήση στην `VivaPayments.cards.requestToken()` να τα πάρει από τη φόρμα. Αν είναι εύκολο, στείλτε μας τι ακριβώς φαίνεται ότι στέλνετε στο συγκεκριμένο ajax call και τι λαμβάνετε σαν απάντηση.

- Το δεύτερο είναι ότι χρησιμοποιείται το source code 'Mastihashop', το οποίο δε μπορεί να βρεθεί. Αυτό οφείλεται στο γεγονός ότι θα πρέπει να περάσετε το code της πηγής και όχι το όνομα. Μπορείτε να δείτε τον κωδικό συνδεόμενοι στο προφίλ του εμπόρου και πηγαίνοντας στο μενού "Οι Πωλήσεις μου -> Πηγές Πληρωμών" στη στήλη Κωδικός για την πηγή που επιθυμείτε να χρησιμοποιήσετε.

Με εκτίμηση

**Comment by dskalidis** [comment]
![viva](https://cloud.githubusercontent.com/assets/22683096/19263764/9c923fe6-8fa6-11e6-98c9-cb0945adf825.png)

**Comment by defilerc** [comment]
Καλησπέρα @dskalidis ,

Ύστερα από δοκιμή στη σελίδα του site σας, βλέπουμε πως το πρόβλημα δεν οφείλεται στη λήψη token, καθώς αυτό ολοκληρώνεται κανονικά. Παρακαλώ δείτε τα συνημμένα αρχεία `token_request.png` και `token_response.png`, όπου φαίνονται τα στοιχεία που έχουν σταλθεί στην `requestToken()` και η απάντηση που έχετε λάβει:

![token_request](https://cloud.githubusercontent.com/assets/1667459/19264292/c9550f48-8fa8-11e6-9d18-0643d0018d43.png)
![token_response](https://cloud.githubusercontent.com/assets/1667459/19264291/c9528b60-8fa8-11e6-88ef-e43728206f59.png)

Το πρόβλημα ενδεχομένως να είναι στη χρήση λανθασμένου source code που βάζεται για τη δημιουργία του Order. Δοκιμάστε να αλλάξετε την τιμή Mastihashop (source name) με τον **κωδικό** της πηγής (source code).

Με εκτίμηση,

**Comment by dskalidis** [comment]
Αυτό που παρατηρώ είναι όταν στο Integration method βάλω native/πληρωμή μου βγάζει σφάλμα Source 7293 of merchant 5e69b107-ced3-462b-81cb-8006c08b5d93 supports only native checkout.

Όταν βάζω redirect τότε έχω σφάλμα invalid card number.

**Comment by defilerc** [comment]
Καλησπέρα @dskalidis ,

Καταρχάς, θα πρέπει να έχετε ρυθμίσει τη συγκεκριμένη πηγή σαν **Native**, από το μενού των Πηγών Πληρωμών.

Το πρόβλημά σας, φαίνεται να είναι πως κατά την κλήση της `/api/transactions`, στα `CreditCardOptions`, δεν τίθεται σωστά το Token της κάρτας που έχετε πάρει από το προηγούμενο βήμα (card tokenization).

Παρακαλώ πολύ δείτε και το issue https://github.com/VivaPayments/API/issues/165 που αναφέρεται μια ενδεχόμενη λύση στο πρόβλημά σας.

Εναλλακτικά, αν αυτό δε βοήθησε, θα πρέπει να μας στείλετε ακριβώς τις τιμές που χρησιμοποιείται κατά την κλήση της `/api/transactions`, ώστε να δούμε τι ακριβώς συμβαίνει.

Με εκτίμηση,

**Comment by dskalidis** [comment]
Καλησπέρα και καλή βδομάδα,
Το πρόβλημα συνεχίζει να υπάρχει. To μνμ σφάλματος που λαμβάνω είναι "Source 3859 of merchant 5e69b107-ced3-462b-81cb-8006c08b5d93 supports only native checkout".

Έχει γίνει ρυθμίσει στη συγκεκριμένη πηγή σαν Native.

**Comment by defilerc** [comment]
Καλησπέρα,

Κατά την κλήση της `CreateTransaction()` στον κώδικά σας, η τιμή `transactionDetails.CreditCardToken` φαίνεται να μην περνάει σωστά. Κανονικά θα έπρεπε να έχει την τιμή του πεδίου `hidToken` της html φόρμας σας, που πήρε τιμή μετά την κλήση για το tokenization.

Με εκτίμηση,

**Comment by dskalidis** [comment]
Καλημέρα,

Το τοκεν που περνάει στην createTransaction είναι ίδιο με αυτό που δημιουργείται κατα την κλήση της requestToken. Σας επισυνάπτω μια εικόνα με τα δεδομένα που περνάω.
![viva](https://cloud.githubusercontent.com/assets/22683096/19470589/c247f316-9528-11e6-9d4a-1bd4037dfd6e.jpg)

**Comment by defilerc** [comment]
Καλησπέρα @dskalidis ,

Απ' ότι βλέπουμε, η πηγή `Default` που χρησιμοποιείται στο demo περιβάλλον, **δεν** είναι ρυθμισμένη ως Native Checkout. Παρακαλούμε πολύ ρυθμίστε την πηγή, όπως φαίνεται και από το παρακάτω screenshot:

![defaultsourcesettings](https://cloud.githubusercontent.com/assets/1667459/19477307/2b6ecd98-9546-11e6-973f-dc5518f42f02.png)

Δηλαδή, θα πρέπει να είναι ρυθμισμένη ως `Native/Πληρωμή με Viva Wallet Checkout` και το πρωτόκολλο επικοινωνίας να είναι `HTTPS`.

Στη συνέχεια, δημιουργήστε ένα `Order` με τη συγκεκριμένη πηγή και επαναλάβετε τη διαδικασία πληρωμής.

Με εκτίμηση,

**Comment by dskalidis** [comment]
Καλημέρα,

Το πρόβλημα λύθηκε με την χρήση του 127.0.0.1 στο όνομα domain και την αλλαγή του createTransaction() που δεν έκανα σε json τα αποτελέσματα. 

Ευχαριστώ πολύ για την βοήθεια.
