### ISSUE TITLE
if i charge quickpay payment faild message pls resolve my problem

### ISSUE THREAD

**Issue by tassadaq1956** [VivaPayments/API#1781]
if i charge quickpay payment faild message pls resolve my problem

**Comment by matthewrgourd** [comment]
Hi @tassadaq1956 sorry, I need a bit more info about the error. Can you attach a screenshot? Thanks!

**Comment by tassadaq1956** [comment]
﻿

**Comment by tassadaq1956** [comment]
![F1A9CBF1-4791-4719-9B0F-3432D34A19EA](https://user-images.githubusercontent.com/68305306/87534862-84916c00-c68e-11ea-86f7-ba852b37c499.png)
![20BD0331-6A66-43B9-84A0-5E2DFE1A4E8F](https://user-images.githubusercontent.com/68305306/87534867-86f3c600-c68e-11ea-9fa7-779f34dd64ef.jpeg)

**Comment by matthewrgourd** [comment]
Hi @tassadaq1956 please try again with a different card. The error message is very clear that it's a card problem.

**Comment by tassadaq1956** [comment]
My all costumers same problem

**Comment by matthewrgourd** [comment]
Hi @tassadaq1956 very strange, could I have your registration or VAT number to check your account?

**Comment by tassadaq1956** [comment]
what kind of registration

**Comment by tassadaq1956** [comment]
my mobile number this account 004407448031885     and email info@mirwahinternational.co.uk

**Comment by matthewrgourd** [comment]
Hi @tassadaq1956, I've been able to check your account details now. Looks like all the failures are card related. Please ask those customers to contact their card issuers. I can confirm that there is no issue with our Quick Pay service. Thanks!

**Comment by tassadaq1956** [comment]
Brother I Chack my all costumer, didn’t gone throw,
Also I charge my all costumer another Company merchant Payment good to go.
My request pls Chack my Acount and resolved my services.
Thanks

**Comment by matthewrgourd** [comment]
Hi @tassadaq1956, for account queries, please contact our [customer service](https://www.vivawallet.com/contact) team. There is also a live chat facility available on our [home page](https://www.vivawallet.com/) for you to talk to someone online.

I have checked your Quick Pay service and it is working fine. The customers who attempted payments and got failures have an issue on their side which I'm afraid I can't help with.
