### ISSUE TITLE
lots of errors on payments over the last hours on www.levanteferries.com site

### ISSUE THREAD

**Issue by evandoulas** [VivaPayments/API#1782]
MerchantId = "bfe10622-3b64-486a-bf18-a7d98fa31977"

we are facing a lot of errors during lasta hours on the payment process.

**Comment by matthewrgourd** [comment]
Hi @evandoulas, sorry to hear this. Can you get me any more information such as error messages, logs and screenshots? My email address is mgourd@vivawallet.com if you prefer to share privately. I've had a quick check of your sales transactions and no problems that I can see, but I can ask my colleague who has access to more detailed info.

**Comment by nikapetano** [comment]
Hi, 
i send you a file with yesterday's and today's (so far) failed transactions
You can see the exact time and the viva response
[fail_transactions.xlsx](https://github.com/VivaPayments/API/files/4930536/fail_transactions.xlsx)

**Comment by matthewrgourd** [comment]
Hi @nikapetano thanks for sending this through. Please see below explanation of Event ID listed for each payment failure:

> 10051 – **Insufficient funds**. The card has insufficient funds to cover the cost of the transaction.
> 2062 – **3DS failure**. Card holder has failed their 3DS.

These are customer-related and have nothing to do with our platform. In both cases customer should speak to their card issuer. Hope this helps!

**Comment by nikapetano** [comment]
Hi again @matthewrgourd ,

can you check please the following merchant transaction codes ?
Have you any usefull information in your system ?
The customer was not able to pay, he says the application "frozen" before the 3DS form was displayed

0212612610, 0212612313, 0212603328

**Comment by matthewrgourd** [comment]
Hi @nikapetano if there's any problem with the 3DS window not displaying, please let me know the full details of their setup. Are they attempting a payment by mobile. If so, iOS or Android. If the issue happens from within a desktop browser, get them to try Chrome or Firefox or whatever is an alternative to what they're previously used.

**Comment by matthewrgourd** [comment]
@nikapetano if you need me to search for particular transactions, please provide the transaction IDs. Thank you.

**Comment by nikapetano** [comment]
Hi @matthewrgourd,

these are orders that have NOT reached the payment transaction
The error (if there is an error) occured at the 3DSecure step
But i am not absolutely sure, that's why i asked you if you can see anything helpful on your side

**Comment by evandoulas** [comment]
Οne more question Mathew.
Did you make any change in the 3Dsecure backend at the previous days?
We have noticed that the past 2-3 days we are getting more complains from our customers than the previous week.

**Comment by matthewrgourd** [comment]
Hi @evandoulas, @nikapetano having checked in some depth, we can see nothing unusual on our side.
