### ISSUE TITLE
Brother I Chack my all costumer, didn’t gone throw,

### ISSUE THREAD

**Issue by tassadaq1956** [VivaPayments/API#1784]
Brother I Chack my all costumer, didn’t gone throw,
Also I charge my all costumer another Company merchant Payment good to go.
My request pls Chack my Acount and resolved my services.
Thanks

_Originally posted by @tassadaq1956 in https://github.com/VivaPayments/API/issues/1781#issuecomment-659784138_

**Comment by matthewrgourd** [comment]
Duplicate of #1781
