### ISSUE TITLE
The Native Redirect on Checkout takes too long and customers are not converting

### ISSUE THREAD

**Issue by WNascimento77** [VivaPayments/API#1785]
Hi,

I was wondering if anyone can help me. My Vivawallet is working, but the problem is the redirect to the card details form takes too long and customers see that it is not working. How can this be improved or is their a simpler entering card details form on the checkout page itself?

**Comment by matthewrgourd** [comment]
Hi @WNascimento77, there's not normally a problem. Can I have your website address, for checking, please?

**Comment by WNascimento77** [comment]
Sure www.pureconnectcbd.co.uk
    	
    	

    	Get Outlook for iOS
    
  




On Mon, Jul 20, 2020 at 10:12 AM +0100, "matthewrgourd" <notifications@github.com> wrote:















Hi @WNascimento77, there's not normally a problem. Can I have your website address, for checking, please?

**Comment by matthewrgourd** [comment]
Hi @WNascimento77 I just tested attempting to buy something from your website with a card with no funds. I can confirm that there is no issue with the speed of the redirect. It maybe happens with particular customers, but this would not be anything to do with our payment gateway.

**Comment by WNascimento77** [comment]
Okay Matthew, thanks for testing. It maybe that customers are not aware and will try to incorporate them to wait for the vivapayment to load.
 
IS vivawallet maybe looking into maybe have card details entered like a button on checkout page in the future?
 
Kind Regards
 


 

 
Sales Support
 <https://www.pureconnectcbd.co.uk/> PureConnectCBD.co.uk
 

-- Follow us on social media --

 <https://www.facebook.com/pureconnectoil/>  <https://www.instagram.com/pureconnecthemp/> 

Confidentiality Notice: This email contains confidential and privileged information intended only for the use of the individual or entity to which it is sent. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivery to the intended recipient, or if this message has been addressed to you in error, you are hereby notified that the dissemination, distribution or copying of this communication is strictly prohibited. If you have received this email in error, please immediately notify the sender by reply email. Delivery of this message and any attachments to any person other than the intended recipient(s) is not intended in any way to waive confidentiality or a privilege.

**Comment by matthewrgourd** [comment]
Hi @WNascimento77, actually there is a newer, fully native version of our plugin for WooCommerce available from the below page. You will need to deactivate and delete the existing plugin first.

https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/

**Comment by WNascimento77** [comment]
Thanks Mat, I will give this a try and see if it improves.
Thanks for your assistance.
    	
    	

    	Get Outlook for iOS
    
  




On Mon, Jul 20, 2020 at 10:34 AM +0100, "matthewrgourd" <notifications@github.com> wrote:















Hi @WNascimento77, actually there is a newer, fully native version of our plugin for WooCommerce available from the below page. You will need to deactivate and delete the existing plugin first.


https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/
