### ISSUE TITLE
The merchant with id xxxxxxx does not have a source with code \'XXXX\' assigned or the source is disabled.

### ISSUE THREAD

**Issue by plinio1983** [VivaPayments/API#1786]
Hello,
I am receiving this error while testing checkout in demo environment:

The merchant with id xxxxxxx-xxxx-xxxx-xxxx-xxxxxx does not have a source with code \'3093\' assigned or the source is disabled.

After clicking the checkout button the url changes to:
https://demo.vivapayments.com/web/newtransaction.aspx?Ref=

where "Ref" is empty.
Am I missing something?

Thanks,
Plinio

**Comment by matthewrgourd** [comment]
Hi @plinio1983 can I have you demo Merchant ID, please? This will be different from the one associated with your verified account.

**Comment by plinio1983** [comment]
Hi matthewrgourd, 
Merchant ID: b1c6c25d-3c8d-4e27-a500-b211637dd8a6

**Comment by matthewrgourd** [comment]
Hi @plinio1983 that's your Production Merchant ID. I'm going to obscure some of the digits now for security reasons. If you're testing on demo you need to [sign up for a sandbox account](https://demo.vivapayments.com/) and use the credentials from there, that's why you're getting the error.
