### ISSUE TITLE
CARD ACCEPTANCE

### ISSUE THREAD

**Issue by palmeriaclothing** [VivaPayments/API#1787]
Hello,

We would like for the website **palmeria.clothing** **not accept payments by card type American Express** through the company VivaPayments.

The details of the business are:
Business Account: ΚΕΣΊΔΗΣ ΙΩΆΝΝΗΣ (KESIDIS IOANNIS)
Trade name: Palmeria Clothing
Address: Ίωνος Δραγούμη 65, Θεσσαλονίκη, 54630 (Ionos Dragoumi 65, Thessaloniki, 54630)
VAT NumberEL150989359

Thank you.

**Comment by matthewrgourd** [comment]
Hi @palmeriaclothing, status is now inactive for Amex as requested. Best regards.
