### ISSUE TITLE
Locked Out

### ISSUE THREAD

**Issue by saxtouri** [VivaPayments/API#179]
Μου ζήτησαν να σας αναφέρω το πρόβλημά μου εδώ. Δε μου φαίνεται λογικό, διότι είναι θέμα υπηρεσίας ότι repo, αλλά αφού μου το ζήτησαν από το support σας, θα το κάνω...

Χρησιμοποιώντας το demo site σας, κάποια στιγμή ξέχασα τον κωδικό μου. Το email που είχα δώσει στα settings είναι ανύπαρκτο. Έτσι, αυτή τη στιγμή δε μπορώ να κάνω recover τον κωδικό μου αφού τα στοιχεία για το reset στέλνονται στο ανύπαρκτο email, αλλά ούτε και να φτιάξω νέο account, αφού το τηλεφωνικό μου νούμερο είναι δεσμευμένο στον κλειδωμένο λογαριασμό.

Πως μπορεί να λυθεί το πρόβλημα; Π.χ. μπορείτε να σβήσετε εντελώς το λογαριασμό μου στο demo;

**Comment by dpnevmatikos** [comment]
Καλησπέρα @saxtouri 
Ο λογαριασμός σου διεγράφη. Δοκίμασε πάλι να γραφτείς.

**Comment by saxtouri** [comment]
Το πρόβλημα διορθώθηκε, ευχαριστώ
