### ISSUE TITLE
issue payment gateway

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1790]
@matthewrgourd I have an issue from another merchant ´´Serpent Vape Sl´´

Hello!
we have the configuration of the woocommerce plugin done as follows.
 
We have doubts about the Source Code field since we haven't found that field.
 
Could you check if everything is correct?
Thanks

<img width="399" alt="Captura 1" src="https://user-images.githubusercontent.com/56823712/88203658-72916980-cc4a-11ea-82bd-14cb5f556ad1.PNG">
<img width="414" alt="Captura" src="https://user-images.githubusercontent.com/56823712/88203763-98b70980-cc4a-11ea-8d05-0828263098d5.PNG">

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada source code is generated automatically if they've downloaded the correct plugin from here:

https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/
