### ISSUE TITLE
Lack of information

### ISSUE THREAD

**Issue by callumb** [VivaPayments/API#1791]
Looking through your API docs and I am in love! You have made is so simple to integrate! However the way we do things is we pre auth a customers card then when the order is accepted do we capture it. The API docs show how to pre auth but don't show how to capture or cancel the pre auth! Can you point me in the right direction?

**Comment by matthewrgourd** [comment]
Hi @callumb, thank you! Once you've done the pre auth, log in to the Viva Wallet banking app, click on **Sales Transactions**. Search for today's sales, find the transaction, then you will see a **Capture** link you can click on:

![Screenshot_2020-07-28_at_14_46_04](https://user-images.githubusercontent.com/44943019/88674260-81ac6780-d0e1-11ea-8c13-ed00440c8ebd.png)

**Comment by callumb** [comment]
Hi, what I mean is how can I do this via API?

**Comment by matthewrgourd** [comment]
Hi @callumb there is some information here about capturing a pre-auth but I don't know if it's exactly what you want to do:

https://developer.vivawallet.com/api-reference-guide/native-checkout-v2-api/#capture-a-pre-auth

**Comment by callumb** [comment]
Hi @matthewrgourd Thats perfect thanks! I own an online ordering system for local businesses and the way we work is a customer orders, we pre auth, then when the order is accepted we capture the payment else release the pre auth if its declined. Basically avoids the faff of refunds.
