### ISSUE TITLE
Error 400  in native checkout v2

### ISSUE THREAD

**Issue by ricardotech88** [VivaPayments/API#1793]
Hi, thanks in advance to take your time.
I'm trying implement this:
https://developer.vivawallet.com/online-checkouts/native-checkout-v2/ 
is everyting going good until step 5, when i try call the api to conclude transaction i receive 
- 400 bad request
{
    "status": 400,
    "message": "Null options",
    "eventId": "0"
}
![image](https://user-images.githubusercontent.com/21170225/88605627-5e969f00-d072-11ea-927a-20df5bd4e049.png)

i tried:
1) using quotes in array customer, for example, customer["email"] etc
2) i tried use bearer created to use in form (step 1), generate a new bearer code, before submit this request, same error

When i try use https://developer.vivawallet.com/api-reference-guide/native-checkout-v2-api/ i can generate acess_token, but when try create [this](https://developer.vivawallet.com/api-reference-guide/native-checkout-v2-api/#create-a-one-time-charge-token) i receive same error
![image](https://user-images.githubusercontent.com/21170225/88606746-66a40e00-d075-11ea-8473-c5a6b2cfd7c8.png)

im using a demo account (291eba67-2f50-4e91-8347-7522f46d2366) 
kindly Ricardo Amaral

**Comment by matthewrgourd** [comment]
Hi there, as an initial query, can I just check if it's Postman you're using for testing?

**Comment by ricardotech88** [comment]
it's okey, no problem.
I use browser in first moment i receive chargeToken from [form submit](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-4-request-a-one-time-charge-token)  works okey.
Then i copy chargeToken and bearer used in first request to try complete transaction ,manually in other php file, but i receive error 400
Then i copy chargeToken and try create a new bearer authentication to complete transaction, same error.

Now i'm using postman to test, yes.

**Comment by matthewrgourd** [comment]
Hi @ricardotech88 the reason you're getting the error is that step 5 cannot be done using a browser. You have to do it from a backend channel. Testing in Postman is fine. You should not get this error.

**Comment by ricardotech88** [comment]
My first image is a print from postman, trying step 5.
Probably i set customer array wrongly, can you say that?

**Comment by matthewrgourd** [comment]
The array then, is the problem. Remove everything from the **Params** tab and try passing your version of the below in JSON under the **Body** tab instead:
```
{
  "amount": 1000,
  "preauth": false,
  "sourceCode": "Default",
  "chargeToken": "ctok_BIb-u_x7ga4ABsKVVqa6mHI7B4I",
  "Installments": 1,
  "merchantTrns": "Merchant transaction reference",
  "customerTrns": "Description that the customer sees",
  "currencyCode": 826,
  "customer": {
	  "email": "native@vivawallet.com",
	  "phone": "442037347770",
	  "fullname": "John Smith",
	  "requestLang": "en",
	  "countryCode": "GB"
   }
}
```

**Comment by ricardotech88** [comment]
Done XD 

God bless you!!

![image](https://user-images.githubusercontent.com/21170225/88678473-6859ea00-d0e6-11ea-9cc9-52a941b1f7c2.png)

**Comment by matthewrgourd** [comment]
@ricardotech88 no worries, please close this issue if you feel it's been solved. Thanks!
