### ISSUE TITLE
Bug in opencart 3 extension

### ISSUE THREAD

**Issue by pamgeo** [VivaPayments/API#1794]
On \catalog\controller\extension\payment\vivawallet.php line 229 the query execution 

`$email_query = $this->db->query("SELECT email FROM " . DB_PREFIX . "order WHERE order_id = '" . (int)$order_id . "'");`

will fail if no DB_PREFIX is defined, as order is reserved by mysql.

**Comment by matthewrgourd** [comment]
Hi @pamgeo, thanks for letting us know, I'll raise with the plugin developer!

**Comment by matthewrgourd** [comment]
Hi @pamgeo, we've applied the fix to all OpenCart versions. Thanks again.
