### ISSUE TITLE
Помогите мне! Подтверждение Учетной записи!

### ISSUE THREAD

**Issue by denys19941** [VivaPayments/API#1795]
Добрый день как мне подтвердить Учетную запись мои убытки уже 1200$ за 2 дня потому что мне никто не отвечает! Сколько можно уже? Мне на вас в суд подавать? Для возмещения убытков

**Comment by matthewrgourd** [comment]
Hi @denys19941, sorry to hear this. The fastest way to get in contact direct with our customer service team is via the live chat function on our home page here: https://www.vivawallet.com

**Comment by denys19941** [comment]
У меня. Убытки со всех сторон! 3  день я не могу связаться с вами!! Это не
нормально!

ср, 29 июл. 2020 г., 11:28 matthewrgourd <notifications@github.com>:

**Comment by matthewrgourd** [comment]
@denys19941 what is your trading name, please?

**Comment by denys19941** [comment]
На сайте нету live chat   нету такой функции я уже 3 день ищу! Нет такого

ср, 29 июл. 2020 г., 11:28 matthewrgourd <notifications@github.com>:

**Comment by matthewrgourd** [comment]
Hi @denys19941 I just tested the live chat and it is working. You need to click on **Support** feature on the home page:

![Screenshot_2020-07-29_at_11_14_50](https://user-images.githubusercontent.com/44943019/88788701-9f370b00-d18d-11ea-9e1e-67fa0a6376df.png)

However, please let me have your trading name so I can progress things for you.

**Comment by denys19941** [comment]
DJA
Регистрационный номер
47473829637

ср, 29 июл. 2020 г. в 11:32, matthewrgourd <notifications@github.com>:

**Comment by denys19941** [comment]
ForexDJA

ср, 29 июл. 2020 г. в 11:32, matthewrgourd <notifications@github.com>:

**Comment by denys19941** [comment]
дайте ссылку на живой чат я не могу найти его вообще

**Comment by denys19941** [comment]
![Безымянный](https://user-images.githubusercontent.com/68920344/88798737-0b296b80-d1ae-11ea-9f3a-ea22a31c4237.png)
Подскажите где она я не могу розобраться Заранее вам спасибо!

**Comment by denys19941** [comment]
![Безымянный](https://user-images.githubusercontent.com/68920344/88799294-ec77a480-d1ae-11ea-99ff-062c4667564f.png)
Я писал им сюда но это же не Живой Чат

**Comment by denys19941** [comment]
Спасибо Вам !! у мемя Куки выключаные были(

**Comment by matthewrgourd** [comment]
Hi @denys19941 I've been advised that your account has been blocked due to fraud. I can't help you any further unfortunately. If you've used our contact form, someone will get back to you soon.
