### ISSUE TITLE
Order is generate if customer don't pay on viva portal

### ISSUE THREAD

**Issue by amitphpdeveloper** [VivaPayments/API#1796]
Hi,

We are using Viva Payment module on Magento 2.3.4 version. We face issue that if customer won't pay on viva portal then order is created which should not happen. 

Order can only be generated if  customer pay and do successfull transcation on viva porta.

Kindly help we faced so many issues that customer see orders with no payment process.

Thanks
Amit

**Comment by matthewrgourd** [comment]
Hi @amitphpdeveloper, sorry to hear this. Can I have the URL of your e-commerce store? What status are these orders you mention with payment failures. Does the customer get confused because they receive an order notification despite not being able to make the payment?

**Comment by matthewrgourd** [comment]
Hi @amitphpdeveloper have you tried updating to the latest version of the plugin? See attached (below). Please let me know if this makes any difference to the exhibited behaviour.

[magento23_vivawallet.zip](https://github.com/VivaPayments/API/files/5057507/magento23_vivawallet.zip)

**Comment by matthewrgourd** [comment]
Closing as no reply...
