### ISSUE TITLE
WooCommerce to Viva Wallet payment gateway (native checkout)

### ISSUE THREAD

**Issue by WeedyTech** [VivaPayments/API#1797]
Hello,

We have installed the new vivawallet plugin for woocommerce, which integrates the payment form directly on the same page of the customer's cart, with the new possibility of accepting new payment methods such as Bancontact, it's really excellent.

However, something bothers us, when the customer validates his payment, he must wait 5 to 10 seconds before being redirected to the payment acceptance page. During this loading time, there is nothing indicating to him that his payment is in progress (a small loading animation would be really good ....) and therefore during this time the customer may unfortunately be tempted to manually refresh the page or leave it ..

**Comment by matthewrgourd** [comment]
Hi @WeedyTech, I'm glad you're please with the new plugin. I will forward your suggestion to our development team. Thank you for raising.

**Comment by matthewrgourd** [comment]
Hi @WeedyTech this has been looked at and there should be a release in mid September with the suggested improvement.
