### ISSUE TITLE
Mastercard in my Shopify store is not working 

### ISSUE THREAD

**Issue by Mjennifer** [VivaPayments/API#1798]
Hi!

I am trying out the check out with VivaPayments but the Mastercard seem not to work. 
Any idea why?

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this, can you let me know your Shopify store name and / or Viva Wallet account name so I can investigate?

**Comment by Mjennifer** [comment]
Hi Matthew
Thank you for getting back to me so fast 
My store name is thehempishoil.com and my account ID is 2041810785

All the best
Jennifer

**Comment by matthewrgourd** [comment]
Hi @Mjennifer I checked with our accounts team and you're in the process of being enrolled to Mastercard. You should be ok by the end of today. Let me know if not. Thanks!

**Comment by Mjennifer** [comment]
Thank you Matthew, will you email me when its done or do I check myself?
All the best
Jennifer

**Comment by Mjennifer** [comment]
Amex is working at the moment, do you know if the other cards are working?

**Comment by matthewrgourd** [comment]
The other cards should be working it's just Mastercard that sometimes takes a while. We don't email you automatically. I would try again first thing tomorrow and get back in contact here if still any issues which are unlikely.

**Comment by Mjennifer** [comment]
Ok great thank you Matthew,  you have been great! Which you a lovely weekend!

**Comment by matthewrgourd** [comment]
No problem – you too!
