### ISSUE TITLE
Payment page in english lang (magento 1.9)

### ISSUE THREAD

**Issue by alienato** [VivaPayments/API#1799]
Hello, how do I set italian language in payment page (vivawallet)?

![2020-07-31_10h43_54](https://user-images.githubusercontent.com/6955418/89017908-5319d100-d31b-11ea-99b3-e0ddd8a7fba8.png)
![2020-07-31_10h48_44](https://user-images.githubusercontent.com/6955418/89019925-5febf400-d31e-11ea-8e98-262387970bbc.png)
![2020-07-30_12h35_09](https://user-images.githubusercontent.com/6955418/89019931-61b5b780-d31e-11ea-9797-c17130b48779.png)

**Comment by matthewrgourd** [comment]
Hi @alienato I'm afraid the options are fairly limited for the default languages. These are EN if based in the UK or GR if based in Greece. All other languages have to be selected manually by the customer via the payment page at checkout.
