### ISSUE TITLE
Συνδεση virtuemart με viva payments

### ISSUE THREAD

**Issue by LinoZipper** [VivaPayments/API#180]
Καλησπέρα σε όλο το forum.
Θα ήθελα αν είναι δυνατόν βοήθεια στο τι χρειάζεται να κάνει κανείς για να συνδέσει το virtuemart με viva payments ώστε να δέχεται κάρτες (visa, master, prepaid κ.λ.π.)
Παρατήρησα πως δεν υπάρχει στην πραγματικότητα κάποιος «μπουσουλας» με αποτέλεσμα πολλές φορές οι φίλοι του virtuemart να κάνουν setup αντίστοιχα plugin από άλλες εταιρίες.

**Comment by defilerc** [comment]
Καλημέρα @LinoZipper ,

Από τη μεριά μας, να σας ενημερώσουμε πως το Viva Payments API, είναι ένα RESTful API και μπορεί να επιτευχθεί η επικοινωνία μαζί του μέσω HTTP, όπως θα δείτε και από τα διάφορα code samples που παρέχονται: https://github.com/VivaPayments/API

Από εκεί και πέρα, για τη χρήση εξωτερικών plugins για διάφορα e-commerce συστήματα, δεν παρέχεται κάποια επίσημη υποστήριξη από εμάς, καθώς αυτά έχουν αναπτυχθεί από εξωτερικούς developers. Θα πρέπει επομένως να αναζητήσετε υποστήριξη εκεί, για να έχετε κάποια επίσημη απάντηση.

Σας ευχαριστούμε πολύ,

**Comment by LinoZipper** [comment]
Καλημέρα @defilerc δεν σας κρύβω και εγώ από την μεριά μου πως αυτή είναι η απάντηση που περίμενα (όπως είπα και εχτές στο τηλέφωνο)
Το θέμα παρόλα αυτά είναι πολύ σοβαρό μιας και το vivawallet ασχολείται με χρήματα και δεν μπορεί να βασίζεται κάποιος σε «εξωτερικούς developers» μιας και δεν γνωρίζουμε την ποιότητα του εκάστοτε «εξωτερικού developer». Πολλοί από τους ιδιοκτήτες ιστοσελίδων έχουν μπλέξει με «εξωτερικούς developers» οι οποίοι τους παραμυθιάζουν για την ποιότητα των υπηρεσιών τους και όταν χρειαστεί να μεταφέρουν την ιστοσελίδα τους σε κάποιοα άλλη εταιρία βλέπουν πως ακόμα και το domain name το οποίο ο πελάτης έχει πληρώσει δεν του ανήκει γιατί ο κομπιναδόρος «εξωτερικός developer» το έχει καταχωρήσει στο όνομά του (για να τον έχει κλειδωμένο).
Επομένως μιας και το vivawallet μου είπε να απευθυνθώ σε αυτό το forum για βοήθεια, να φανταστώ πως και η επίσημη απάντηση του vivawallet στο ερώτημά μου είναι πως δεν παρέχεται κάποια επίσημη υποστήριξη από εμάς για το api που παρέχει;

**Comment by defilerc** [comment]
Καλημέρα @LinoZipper ,

Επίσημη υποστήριξη υπάρχει για όλο το functionality του Viva Payments API που είναι documented στο wiki μας (https://github.com/VivaPayments/API/wiki).

Μπορείτε σε κάθε περίπτωση να κατεβάσετε τα code samples και να επικοινωνήσετε με το API, όπως και να μας ζητήσετε βοήθεια σε οποιοδήποτε πρόβλημα αντιμετωπίσετε.

Αυτός είναι και ο συνιστώμενος τρόπος, αν θέλετε να είστε σίγουρος ότι δεν εξαρτάστε από κάποιο third-party tool ή developer και ότι η επικοινωνία σας μέσω του Viva Payments API είναι ασφαλής και άμεση.

Από εκεί και έπειτα, δε μπορούμε να εμποδίσουμε οποιονδήποτε third-party developer στο να αναπτύξει κάποια δικιά του λύση ή plugin, καθώς το API μας είναι ανοιχτό σε οποιονδήποτε θέλει να το χρησιμοποιήσει. Όπως καταλαβαίνετε όμως, δεν μπορούμε να παρέχουμε κάποια επίσημη υποστήριξη σε τέτοιες περιπτώσεις, καθώς ο κώδικας που έχει αναπτυχθεί δεν είναι υπό την επίβλεψή μας.

Με εκτίμηση,

**Comment by LinoZipper** [comment]
Αγαπητέ @defilerc τα εχω κατεβάσει τα code samples και δεν είπα σε καμία περίπτωση πως εσείς πρέπει να εμποδίσετε κανέναν developer να κάνει την δουλειά του ! 
Ρώτησα αν υπάρχει υποστήριξη για να ενσωματώσουμε το api στο virtuemart.
Η απάντησή σας «για τη χρήση εξωτερικών plugins για διάφορα e-commerce συστήματα, δεν παρέχεται κάποια επίσημη υποστήριξη από εμάς, καθώς αυτά έχουν αναπτυχθεί από εξωτερικούς developers» είναι ξεκάθαρη και σας ευχαριστώ πολύ.
Παρόλα αυτά βλέπω πως και εσείς με την δεύτερη απάντησή σας « Όπως καταλαβαίνετε όμως, δεν μπορούμε να παρέχουμε κάποια επίσημη υποστήριξη σε τέτοιες περιπτώσεις, καθώς ο κώδικας που έχει αναπτυχθεί δεν είναι υπό την επίβλεψή μας » αποδέχεστε αυτό που σας είπα παραπάνω  «δεν μπορεί να βασίζεται κάποιος σε εξωτερικούς developers »  ιδιαίτερα όταν δεν γνωρίζει κάποιος τον developer και ακόμα περισσότερο όταν μιλάμε για μεταφορά χρημάτων, πιστωτικές κάρτες κ.λ.π.

Με εκτίμηση,
