### ISSUE TITLE
Can Vivawallet incorporate applepay solution?

### ISSUE THREAD

**Issue by WNascimento77** [VivaPayments/API#1800]
Quite a few merchant providers offer applepay. I was wondering if vivawallet will allow applypay integration as quite majority of consumers pay via this method due to use of mobile iPhone and feel as a business we lose out.

Is there anyway to use this method?

**Comment by mavr1982** [comment]
Hello @WNascimento77,
At this moment we are working on ApplePay integration for our new Woocommerce plugin. We'll have new version including it shortly.

I hope this will be helpful for you.
