### ISSUE TITLE
invalid merchant ID

### ISSUE THREAD

**Issue by inaus** [VivaPayments/API#1801]
when using the Simple Checkout feature, a message appears on the top left corner of the preview page stating that the merchant public key is invalid

**Comment by matthewrgourd** [comment]
Hi @inaus sorry to hear this. Can you let me know if you're testing on demo or using the live version? If you're on production, please send me a screenshot of the error. My email is mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
no reply so I'm closing
