### ISSUE TITLE
Woocommerce Error message on payment - Please check your card details!

### ISSUE THREAD

**Issue by cathallen14** [VivaPayments/API#1802]
Hi,

I keep getting the "Please check your card details!" error message when trying to checkout on my woocommerce site and orders aren't being placed.

The card details being entered are correct so I'm unsure as to why this error message is appearing.

Any thoughts?

Thanks
Catherine

**Comment by liviujs** [comment]
Hi,
Same issue: "Please check your card details!"

Integration: Viva Wallet for WooCommerce v.1.0.1

What is not clear is that we have 3 ID-s and Key-s in here: http://prntscr.com/tu9ah3 which one should we use depending on integration?
The costumer support told me that we need to use the first one, but it returns "Please check your card details!" with a valid card.

Thanks.
Liviu

**Comment by mavr1982** [comment]
Hi @cathallen14,

Can you please share your domain with us so our team could check your site and verify if there is any problem with JS?

Thanks in advance.

**Comment by mavr1982** [comment]
Hi @liviujs , Hi @cathallen14 

Please check out our documentation at https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/ to ensure everything is set up properly within our new plugin.

Thanks.

**Comment by mavr1982** [comment]
Hi again @liviujs @cathallen14 

We also checked some fields must be set as REQUIRED on billing address. The fields are: First name, Last name, email address, street, city and phone number.

**Comment by liviujs** [comment]
Hi @mavr1982 
From my point of view the error came from incorrect set up of the Plugin.
One have to use the ID and Key from the Woo commerce Credentials inside Viva Wallet dashboard and not the general ones that the Sales persons suggests as default.

Regarding REQUIRED fields, here I disagree, normally the Plugin has nothing to do with the CITY field or Last Name field. It has to capture the payment, delivery issues have to be on Courier companies and Web shops. That's my opinion.
By the way, we checked some fields as Not Required with the purpose of returning as little as possible errors to the user on the Checkout page, and if we receive some incomplete data about delivery, we can always contact the user by phone or mail.

**Comment by cathallen14** [comment]
Hi @mavr1982 ,

The url is https://uniquehealthsupplements.co.uk/

I've made sure all of the fields are set to required but this still doesn't seem to make a difference. However, I have just switched off the Stripe payment and now VivaWallet is processing payments. 

Am I unable to have both Stripe and Viva Wallet running on the same site?

Thanks
Catherine

**Comment by glagonikas** [comment]
We are trialling the Viva Wallet integration on a store with Stripe and came across the same issue. 

We think the current version of Viva doesn't work when Stripe is enabled because it has the same field name ‘accessToken’ as the stripe plugin.

**Comment by matthewrgourd** [comment]
Hi @cathallen14, @liviujs and @glagonikas, we've completed some updates for a release planned for approximately mid September. We took on board your feedback so I'm closing this issue now...
