### ISSUE TITLE
VivaWallet for Woocommerce v.1.0.1 integration

### ISSUE THREAD

**Issue by liviujs** [VivaPayments/API#1805]
Hi,
Managed to integrate Vivawallet for Woocommerce.

Issue 1: the window for entering the 3d secure Code opens in a framework that needs to be scrolled on Desktop: http://prntscr.com/tu9nfz
Same problem on mobile: http://prntscr.com/tu9q7u
Also on Mobile the Iframe opens above the Payment Botton (above the checkout form) and it's not clear for the user that he/she has to scroll up in order to find where to enter 3D Secure Code.

Issue 2: Need an option to translate Error Messages. Now all error messages show up in EN: http://prntscr.com/tu9rx6
Also here, Error message shows up at the top of the page, I know it's a woocommerce problem, but since last 4.3 version they solved this issue. But error messages from Viva Wallet still show up on top of Page only even on WC 4.3

Hope to hear from you soon.

**Comment by mavr1982** [comment]
Hi @liviujs ,

Thanks so much for using our plugin.

Regarding issue no.1: Can you please share your domain with us so our team could check your site and verify if there is any problem with JS?

Concerning issue #no.2: There is a .pot in a folder called languages in our plugin files (wp-content/plugins/viva-wallet-for-woocommerce/languages/viva-wallet-for-woocommerce.pot). That file contains all the strings used on the plugin. You can get more info about localizations on Wordpress in https://developer.wordpress.org/plugins/internationalization/localization/

**Comment by liviujs** [comment]
Hi @mavr1982 
Thank you for answer.
The domain name where we are using Viva Payments is https://lambre.ro
Please let me know if you need more info in order to help us solve the issues.

p.s. regarding .pot files, yes I somehow missed this option, I will make the necessary translations, in case I won't find any strings gone let you know.

**Comment by mavr1982** [comment]
Hi @liviujs 

We have been checking out your issue with the 3ds window and it seems it can bee problematic with some themes.

We will try to include a patch for this issue on following versions of our plugin.

**Comment by liviujs** [comment]
Hi @mavr1982 
Thanks for your reply.
Waiting for the patch.

Also as a note: Maybe it's a better idea to open the 3D Secure window in a pop up, this way it would be more intuitive to the user to understand where to look. Thanks.

**Comment by matthewrgourd** [comment]
Hi @liviujs we are working on some updates for a release planned for approximately mid September. We took on board your comments so I'm closing this issue now...
