### ISSUE TITLE
ordre pas passer dans appel paiement prestashop1.7

### ISSUE THREAD

**Issue by affidev** [VivaPayments/API#1806]
Suite installation module viva wallet sur prestashop 1.7, lorsque je fais un test de commande au moment du paiement, la requette ne contient pas le numéro d'ordre ?
Où j'ai fait une erreur ?
Si quelqu'un peut m'orienter.
Merci d'avance

![demoerror](https://user-images.githubusercontent.com/25718465/89707249-b5eb1800-d96c-11ea-9cbf-99c59c22ddf0.JPG)

**Comment by matthewrgourd** [comment]
Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- PrestaShop payment module settings (blur out part of your Merchant ID and API Key).
- Viva Wallet [payment source](https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/) settings (include your browser's URL bar in the screenshot).
- Viva Wallet _Websites / Apps_ page (include your browser's URL bar in the screenshot).
- [API Access](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by affidev** [comment]
merci pour votre aide, voici les captures d'écran :

![accesapi](https://user-images.githubusercontent.com/25718465/90022870-5a45c500-dcb3-11ea-910a-f518d42b75ed.JPG)
![module1](https://user-images.githubusercontent.com/25718465/90022873-5ade5b80-dcb3-11ea-9f3f-5e973860dcda.JPG)
![siteapp-vivawallet](https://user-images.githubusercontent.com/25718465/90022875-5ade5b80-dcb3-11ea-934d-79d160e5c471.JPG)
![sourcepaiement](https://user-images.githubusercontent.com/25718465/90022877-5b76f200-dcb3-11ea-9248-dc4fb7f1e413.JPG)

**Comment by matthewrgourd** [comment]
Hi @affidev thanks for those. I've had a look and if you're using PrestaShop 1.7, with our plugin downloaded from here: https://developer.vivawallet.com/downloads/vivawallet1.7.zip the only setting you need to change is in the second screenshot, showing the plugin module fields:

WRONG
Base URL: https://demo.vivapayments.com

> **CORRECT!**
> Base URL: https://www.vivapayments.com

Hope this helps. Let me know how you get on...

**Comment by affidev** [comment]
Merci,
j'ai réinstaller le plugin plus correctif que vous m'avez indiqué et tout fonctionne maintenant.
merci encore pour votre aide.
Cordialement
