### ISSUE TITLE
Viva Wallet error, says 'transaction declined' everytime

### ISSUE THREAD

**Issue by abesapples** [VivaPayments/API#1807]
Hi, My viva wallet card machine has stopped working mid service. An error message saying 'transaction declined' appears on every transaction, but there seems to be no reason for the problem, everything else is working fine! Please help!

**Comment by abesapples** [comment]
i hate you vivawallet

**Comment by abesapples** [comment]
who doesnt have there tech line open on a saturday, when you might actually need it?

**Comment by matthewrgourd** [comment]
Hi @abesapples please let me know a bit more about the problem. Apologies, it is August so many staff are on leave. Firstly, could I have your Viva Wallet account name?

**Comment by matthewrgourd** [comment]
Closing as no answer...
