### ISSUE TITLE
Vaping in Madrid

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1809]
Hi @matthewrgourd this merchant VAPING IN MADRID S.L. has some problems with the implementation of the payment gateway: the operations are charged but he doesn´t get the notifications to his website. I attach you the settings´ screenshot of prestashop
![f6f7f50d-5cc0-48ef-b1a5-53a19e1b1ab1](https://user-images.githubusercontent.com/56823712/89992086-0e7c2700-dc85-11ea-83de-6808619be2e7.jpg)
![eee5d554-b0ee-4da7-8945-2a8dc774c52d](https://user-images.githubusercontent.com/56823712/89992096-120fae00-dc85-11ea-86cb-27f87b260fc3.jpg)

**Comment by matthewrgourd** [comment]
Please get them to check their settings for payment source 5002 in the Viva Wallet banking app:

WRONG
Success URL: https://www.vivapayments.com
Failure URL: https://www.vivapayments.com

**CORRECT IF USING PRESTASHOP 1.5-1.6!**
Success URL – `modules/vivawallet/success.php`
Failure URL – `modules/vivawallet/fail.php` 

**CORRECT IF USING PRESTASHOP 1.7!**
Success URL – `module/vivawallet/success`
Failure URL – `module/vivawallet/fail`

**Comment by Alvaroalconada** [comment]
@matt merchant has several fails payments, can you check it pls?
![MicrosoftTeams-image (10) jpg](https://user-images.githubusercontent.com/56823712/90248396-e7feed00-de38-11ea-805f-1a35c767475b.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada these are all card issuer rejections:

Card ending 3014: "Mastercard Do not honor (05)" and "Mastercard Expired card (54)"
Card ending 6206: "Mastercard Do not honor (05)"

I can confirm that there is no problem with our plugin.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada please close this case if no further issues. Thanks!
