### ISSUE TITLE
OpenCart - Viva Wallet

### ISSUE THREAD

**Issue by icop** [VivaPayments/API#181]
Καλησπέρα , έχω εγκαταστήσει ένα module για Viva Payment στο website και κατά το checkout και ενώ έχω επιλέξει σαν τρόπο πληρωμής το VivaPayment μου βγάζει το μήνυμα "API Call failed! The error was: Forbidden" και όταν προσπαθώ να κάνω επιβεβαίωση παραγγελίας μου βγάζει "Bad Request" και το ref είναι κενό.

**Comment by defilerc** [comment]
Καλησπέρα @icop ,

Το συγκεκριμένο πρόβλημα οφείλεται στο γεγονός ότι η δημιουργία του Order έχει αποτύχει (η κλήση στην CreateOrder είναι ανεπιτυχής) και γι' αυτό η παράμετρος ref είναι κενή.

Μπορείτε αρχικά να δείτε παρόμοια issues με το συγκεκριμένο πρόβλημα, καθώς οι λύσεις ποικίλουν: https://github.com/VivaPayments/API/search?q=bad+request&type=Issues

Ευχαριστούμε πολύ

**Comment by icop** [comment]
$viva_firstname = $order_info['payment_firstname'];
		$viva_lastname = $order_info['payment_lastname'];
		$viva_customeremail = $order_info['email'];
		$viva_customerphone = $order_info['telephone'];

		$request =  $this->data['action'].'/api/orders';
		$trans =  $this->data['action'].'/api/newtransaction.aspx';
		$MerchantId = $this->config->get('viva_merchantid');
		$APIKey = $this->config->get('viva_merchantpass');
		$Amount = $viva_total_cents;	// Amount in cents
		$AllowRecurring = 'true'; // This flag will prompt the customer to accept recurring payments in tbe future.
		$RequestLang = 'en-US';
		$Source = $this->config->get('viva_sourcecode'); // This will assign the transaction to the Source with Code = "Default". If left empty, the default source will be used.

		$postargs = 'Amount='.urlencode($Amount).'&AllowRecurring='.$AllowRecurring.'&RequestLang='.$RequestLang.'&Source='.$Source;
		// Get the curl session object
		$session = curl_init($request);
		// Set the POST options.
		curl_setopt($session, CURLOPT_POST, true);
		curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
		curl_setopt($session, CURLOPT_HEADER, true);
		curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
		curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
		// Do the POST and then close the session
		$response = curl_exec($session);
		// echo '<pre>';
		// print_r($response);
		// echo '</pre>';
		// Separate Header from Body
		$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
		$resHeader = substr($response, 0, $header_len);
		$resBody =  substr($response, $header_len);
		curl_close($session);


![1](https://cloud.githubusercontent.com/assets/19566592/19312356/ad3ee12e-909a-11e6-82e0-f5fce5482714.png)

το $respone μου γυρνάει αυτό.

**Comment by defilerc** [comment]
Καλησπέρα @icop ,

Θα πρέπει να μας στείλετε τις ακριβείς τιμές που περνάτε στην CreateOrder (π.χ. Amount=xxs), το MerchantId σας, καθώς και το API response (HTTP error code + message) για να δούμε τι έχει συμβεί.

Ευχαριστούμε,

**Comment by icop** [comment]
$viva_firstname = $order_info['payment_firstname'];
		$viva_lastname = $order_info['payment_lastname'];
		$viva_customeremail = $order_info['email'];
		$viva_customerphone = $order_info['telephone'];

		$request =  $this->data['action'].'/api/orders';
		$trans =  $this->data['action'].'/api/newtransaction.aspx';
		$MerchantId = $this->config->get('viva_merchantid');
		$APIKey = $this->config->get('viva_merchantpass');
		$Amount = $viva_total_cents;	// Amount in cents
		$AllowRecurring = 'true'; // This flag will prompt the customer to accept recurring payments in tbe future.
		$RequestLang = 'en-US';
		$Source = $this->config->get('viva_sourcecode'); // This will assign the transaction to the Source with Code = "Default". If left empty, the default source will be used.

		$postargs = 'Amount='.urlencode($Amount).'&AllowRecurring='.$AllowRecurring.'&RequestLang='.$RequestLang.'&Source='.$Source;

		// Get the curl session object
		$session = curl_init($request);

**Comment by icop** [comment]
Καλημέρα , δώστε μου ένα email να σας στείλω τα στοιχεία που ζητάτε.

**Comment by defilerc** [comment]
Καλησπέρα @icop ,

Μπορείτε να στείλετε email με τα στοιχεία στο merchants@vivawallet.com μαζί με τον αριθμό του παρόντος github issue για να γίνει η διασταύρωση.

Με εκτίμηση

**Comment by defilerc** [comment]
Καλησπέρα @icop ,

Στο email που στείλατε δεν περιέχονται οι ακριβείς τιμές για ένα παράδειγμα που αποτυγχάνει. Το πρόβλημα σας οφείλεται στο ότι αποτυγχάνει η δημιουργία ενός Order, με την κλήση στην CreateOrder.

Παρακαλώ πολύ δείτε τη σελίδα https://github.com/VivaPayments/API/wiki/CreateOrder που περιέχει ένα παράδειγμα CreateOrder. Θα θέλαμε να μας στείλετε ακριβείς τιμές για καθένα από τα πεδία που περιγράφεται στο section Sample Request, καθώς και τις τιμές που λαμβάνεται για καθένα από τα πεδία στο section Sample Response, για να μπορέσουμε να σας βοηθήσουμε.

Μπορείτε να ποστάρετε την απάντησή σας εδώ, καθώς δεν περιέχεται κάποια ευαίσθητη πληροφορία στη συγκεκριμένη κλήση, ώστε να πάρετε ταχύτερα απάντηση.

Ευχαριστούμε πολύ

**Comment by icop** [comment]
Email: test
First Name:test
Last Name:testtest@example.gr
Phone:2101234567
request :http://vivapayments.com/api/orders
trans:http://vivapayments.com/api/newtransaction.aspx
Merchant id:984d1f47-b211-4979-a569-87b857629f61
Api Key:*W.jTs
Amount:4290
Allow Recuiring:true
Request Lang:en-US
Source:6033
Postargs:Amount=4290&AllowRecurring=true&RequestLang=en-US&Source=6033

Αυτά τα στοιχεία παίρνω...

Από κάτω το κομμάτι κώδικα που πήρα από το github

                // Get the curl session object
$session = curl_init($request);
// Set the POST options.
curl_setopt($session, CURLOPT_POST, true);
curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
curl_setopt($session, CURLOPT_HEADER, true);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
// Do the POST and then close the session
$response = curl_exec($session);
// Separate Header from Body
$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
$resHeader = substr($response, 0, $header_len);
$resBody =  substr($response, $header_len);
curl_close($session);

 try {
            $resultObj=json_decode($resBody);
            if($resultObj!==NULL){
                //php 5.4 fix
                if(strpos($resultObj->OrderCode,'E+')!==false){
                    preg_match('/"OrderCode":([0-9]*+)/', $resBody,
$matches);
                    $resultObj->OrderCode=trim($matches[1]);
                }
            }else{
                preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader,
$match);
                throw new Exception("API Call failed! The error was:
".trim($match[1]));
            }
        } catch( Exception $e ) {
            $error=$e->getMessage();
        }
if ($resultObj->ErrorCode==0){ //success when ErrorCode = 0
$orderId = $resultObj->OrderCode;
$this->data['link'] = '<a style="float:right;" id="button-confirm"
class="button" href="
https://www.vivapayments.com/web/newtransaction.aspx?ref='.$orderId.'"
>'.$button_confirm.'</a>';
}else{
// $this->data['link'] = 'The following error occured: ' .
$resultObj->ErrorText;
$this->data['link'] = '';
}

2016-10-14 15:32 GMT+03:00 Konstantinos Athanasoglou <
notifications@github.com>:

**Comment by defilerc** [comment]
Καλησπέρα @icop ,

Θα πρέπει να αλλάξετε όλα τα URLs που σχετίζονται με το domain `vivapayments.com` από `http` σε `https`. 

Για παράδειγμα: `http://vivapayments.com/api/orders` -> `https://vivapayments.com/api/orders`

Η επικοινωνία γίνεται σε secure περιβάλλον και επιβάλλεται η χρήση πρωτοκόλου `https`.

Παρακαλώ πολύ κάντε τη συγκεκριμένη αλλαγή και ξαναδοκιμάστε.

Με εκτίμηση,

**Comment by icop** [comment]
Όλα οκ ..αυτό ήταν το πρόβλημα ..μπορείτε να το κλείσετε.
Ευχαριστώ για το χρόνο σας.

2016-10-18 11:14 GMT+03:00 Konstantinos Athanasoglou <
notifications@github.com>:
