### ISSUE TITLE
Gomariz store Iberica Sl

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1811]
Hi @matthewrgourd this merchant appears the next error message when he tries to set up webhook 
![51798505-905c-425c-bcf7-165d98be7cc2](https://user-images.githubusercontent.com/56823712/89994034-db876280-dc87-11ea-928a-f445c3ea3de7.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada this is because he needs to set up his payment source correctly in the Viva Wallet banking app. I've checked and payment source 4014 currently has the below settings:
WRONG
Success URL – `https://gomarizstore.com/`
Failure URL – `https://gomarizstore.com/`
**CORRECT!**
I think he's using PrestaShop 1.7 in which case he should amend to:
Success URL – `module/vivawallet/success`
Failure URL – `module/vivawallet/fail`
Once the payment source has been amended successfully, he can try setting up the webhook again and it should work this time.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd this merchant keep on having problems about implement, I attach the screenshot
![WhatsApp Image 2020-08-13 at 10 05 22 jpg](https://user-images.githubusercontent.com/56823712/90110483-975e9580-dd4d-11ea-8d9c-c17d24990472.jpeg)

**Comment by matthewrgourd** [comment]
Hi payment source settings are still wrong. He needs to fix these before attempting to set up the webhook:

WRONG
Success URL – módulo/viva cartera/éxito
Failure URL – módulo/viva billetera/fracaso

**CORRECT!!**
Success URL – module/vivawallet/success
Failure URL – module/vivawallet/fail

Also, when he sets up the webhook, it should be as follows:

`https://gomarizstore.com/module/vivawallet/webhook`

**Comment by Alvaroalconada** [comment]
@matthewrgourd now appears the next message
![WhatsApp Image 2020-08-13 at 11 03 53 jpg](https://user-images.githubusercontent.com/56823712/90117491-4bb0e980-dd57-11ea-838d-f808616af930.jpeg)

**Comment by matthewrgourd** [comment]
Can you translate the error message for me, please? Also, can you answer my question about which version of PrestaShop?

**Comment by matthewrgourd** [comment]
HI @Alvaroalconada, please let me know what the error message in the screenshot states as I don't speak Spanish, I'm afraid. I can't investigate further without this info. Also, need confirmation of the PrestaShop version if you can...

**Comment by Alvaroalconada** [comment]
first of all, he is using prestashop 1.7
Message says ´´viva payments may have to approve changes to existing electronic sources first. Please note that this action may temporarily disable this source´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada thank you. That's fine, I checked and the payment source is still active after the changes so setting up the webhook `https://gomarizstore.com/module/vivawallet/webhook` should work now. Let me know if not!

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant ensures me that the system doesn´t let him implement webhook
![IMG-20200814-WA0000](https://user-images.githubusercontent.com/56823712/90227822-79f4fe80-de15-11ea-984d-85a431f010bf.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada the plugin needs to be fully up and running on his store before he can set the webhook. At the moment it doesn't seem to be enabled? I just tested checking out (see screenshot below.)

![Screenshot 2020-08-14 at 09 23 14](https://user-images.githubusercontent.com/44943019/90229528-f553b180-de0f-11ea-994c-fe11d85085ec.png)

Please get him to enable the Viva Wallet plugin and test checking out via our payment page works correctly. Once this has been done, the webhook can be set up.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd this merchant remits me the next issues:
He mades a purchase of 1€ but in his web´s dashboard doesn´t appear. It stays in the cart but doesn´t end the sale on his website
![adc7ef96-9e3c-4915-b79e-0054263d86f0-1-17-8](https://user-images.githubusercontent.com/56823712/90382797-87152600-e07f-11ea-9544-5548e5c01c8b.jpg)
![f4262379-8143-44da-9152-326cbdc8344f 2-17-8](https://user-images.githubusercontent.com/56823712/90382813-8bd9da00-e07f-11ea-807c-bd0161f38aa8.jpg)
![f8a3df81-ebc9-4cdf-8c79-f8e9c1ec18b9 4-17-8](https://user-images.githubusercontent.com/56823712/90383192-191d2e80-e080-11ea-97c4-e26c879f55b0.jpg)

On the other hand he asks me about what he has to fill up in these fields
![90f2e303-7167-4790-88d2-eee3a49c60aa 3-17-8](https://user-images.githubusercontent.com/56823712/90382982-d2c7cf80-e07f-11ea-93e4-1f0726e54a07.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada testing won't work as the plugin is still not set up correctly. Instalment logic field should be blank. Source code is extremely important. I see he has two sources set up. For his website https://gomarizstore.com, the source code is 4014 as stated previously. If you're referring to his second website https://gomarizstorecanarias.com, source code is 7978. Hope this helps.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada please close this issue if merchant is ok now.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd! merchant tells me the next:
´´in the palms of gran canaria don´t enter the orders to prestashop, can you tell me what to put in that weekhob?´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada sorry, I don't understand what that question means.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd here I provide you a screenshot
![gomariz 28 agosto](https://user-images.githubusercontent.com/56823712/91549267-f82dc680-e926-11ea-9ac6-e6394f2be664.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, sorry, why are you sending me this screenshot? Is the -commerce plugin not working for https://gomarizstorecanarias.com/? Please confirm which version of PrestaShop is being used? You have still not answered this question and I've asked more than once. I notice that https://gomarizstorecanarias.com/ shows an unsecure site. You need to get the merchant to check he has a valid SSL certificate installed as this could be causing issues. Please do not expect me to be able to solve technical problems if you don't provide all the information I'm asking for. Thanks.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada please can you respond to my queries so I can help this merchant.

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant is checking again, if he has problems I´ll let you know with more details.
