### ISSUE TITLE
Carlos Miguel Hernández Gil

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1812]
Hi @matthewrgourd this merchant appears the next error message. I attach you the setting´s woocommerce
![c866ee25-094b-45b6-abaa-483365948593](https://user-images.githubusercontent.com/56823712/89995063-4ab18680-dc89-11ea-8908-db671db86231.jpg)
 and the error message
![faab345c-5112-440d-9842-06d4ecc715b6](https://user-images.githubusercontent.com/56823712/89995081-52712b00-dc89-11ea-9254-8564bdc430a0.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, in the first screenshot, there is no source code specified. I've checked his account and this should be set to 6718. Again, I need to point out that this merchant is currently using the redirect version of our WooCommerce plugin. There is a new, native version available for download from here:
https://woocommerce.com/products/viva-wallet-for-woocommerce/
If he chooses to go down this path, the merchant will need to disable and delete the old plugin, then follow our [installation instructions](https://developer.vivawallet.com/e-commerce-plugins/viva-wallet-for-woocommerce/) for the new plugin (they are a lot easier and installation is almost automatic).

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd Could you tell me the currently status of this merchant about his several websites that are working with us?
![MicrosoftTeams-image (24)](https://user-images.githubusercontent.com/56823712/96609053-62952e80-12fa-11eb-8ef4-ec4d4576a539.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada please resend this query to me on Microsoft Teams. This is for internal discussion as opposed to a public forum!

**Comment by Alvaroalconada** [comment]
@matthewrgourd I´ll do it! sorry
