### ISSUE TITLE
La Vapotienda SL

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1813]
Hi @matthewrgourd this merchant ensure me that has problems when he tries to make a payment by request money. I attach the last movements 
![MicrosoftTeams-image (5) (1)](https://user-images.githubusercontent.com/56823712/89996595-45edd200-dc8b-11ea-9543-d7f12805daf6.png)
and the error´s screenshot
![la vapotienda issue](https://user-images.githubusercontent.com/56823712/89996611-4be3b300-dc8b-11ea-824b-1000dc3b9e3f.jpg)

**Comment by matthewrgourd** [comment]
These are card issuer rejections and have nothing to do with our plugin. The person attempting to pay in each case should contact their card issuer or try a different card.

Please can you keep internal discussions on MS Teams where possible as GitHub is intended as a public forum? Thanks in advance.

**Comment by Alvaroalconada** [comment]
@matthewrgourd Sorry for the inconvenience. Thank you very much and very kindly for the arrangements :)
