### ISSUE TITLE
David Cobano Pareja

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1814]
Hi @matthewrgourd  this merchant asked me if is there any way set up his business´ logo in his payment gateway?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I'm not sure if this can be done with our Shopify plugin. The payment source is created automatically but it's possible he could amend it once it's been created and upload the logo as below:

To edit the Shopify payment source in the Viva Wallet banking app:

1. [Log in](https://app.vivawallet.com/register/) to the Viva Wallet banking app.

2. Click on **Sales** in the left navigation:

![Sales menu](https://developer.vivawallet.com/images/SalesSubMenu.png?classes=border)

3. Click on **Online payments** in the *Sales* menu.

4. Click on **Websites / apps** in the *Online payments* menu:

![Online payments menu](https://developer.vivawallet.com/images/WebsitesSubmenu.png?classes=border)

5. Click on the Shopify source to display the *Edit Payment Source* dialog box:

![Screenshot_2020-08-12_at_12_30_30](https://user-images.githubusercontent.com/44943019/90010598-0083d180-dc98-11ea-8e0a-041cc33b9513.png)

Logo should be uploaded as indicated in the screenshot.

> I'd like to stress that I can't guarantee this will work, but it's worth trying.

**The reason I know the extension he's using is I checked the CRM under his name. For the sake of efficiency, please provide more info. next time.**
