### ISSUE TITLE
Redirect checkout Request Lang

### ISSUE THREAD

**Issue by HarishankarIT** [VivaPayments/API#1815]
Hi,

 Redirect checkout payment page is showing different language  after redirect to your payment page.
 we are passing "RequestLang": "en-US" still showing different lang.
 please let us know asap.

please check below attachement (screenshot).

![Screenshot from 2020-08-12 15-24-23](https://user-images.githubusercontent.com/67691169/90002579-74ca6f00-dcb0-11ea-9bf7-e91ad83f35fb.png)

Regards,
HariIT

**Comment by matthewrgourd** [comment]
Hi @HarishankarIT could I have the demo merchant ID, please and your trading name?

**Comment by matthewrgourd** [comment]
Hi @HarishankarIT, we've looked into this and it looks like there is a problem on demo. Whichever language you choose for the `requestLang` parameter value, it reverts to EL (Greek) on the payment form. However, we've just tested on live and there's no issue. The correct language is chosen automatically depending on the value of the parameter. I'm going to pass this on to the development team to investigate further. In the meantime, apologies for any inconvenience caused. If it suits your needs, you can still test on production.

**Comment by HarishankarIT** [comment]
Hi,

sorry for late reply 
Registration date : 21/02/2020
Merchant ID : 5e8d6a84-d20c-485e-a085-354b2a54473e



Regards,
HariIT

**Comment by matthewrgourd** [comment]
Hi @HarishankarIT you've given me the Merchant ID for your demo account? My last answer still stands: the API isn't fully functioning on demo currently. You would need to test the `requestLang` parameter on live to get the correct results. Sorry about that!
