### ISSUE TITLE
Server Error in '/web' Application.

### ISSUE THREAD

**Issue by renatoDragan** [VivaPayments/API#1816]
Server Error in '/web' Application.
Runtime Error
Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.

Details: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off".

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear this, but could you provide a little context, please? What Viva Wallet product / service / API are you attempting to use?

Could you provide a simple summary of what you're trying to achieve? If possible, please include a brief piece of code (or ideally, a link to an example project) demonstrating the problem you're having.

**Comment by matthewrgourd** [comment]
@renatoDragan, please see my questions above. We need further info in order to help you.

**Comment by matthewrgourd** [comment]
Closing as replied on email...
