### ISSUE TITLE
flirting app

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1817]
Hi @matthewrgourd , I've been contacted by a merchant that his business is a flirting app. I wanted to ask you if there are any plugins that we have that specifically only ask for card data and not personal data to preserve customer confidentiality. thx

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, no, I'm afraid not. Card data always always has to be associated with some personal data (name, billing address etc.)
