### ISSUE TITLE
3DS test card not working

### ISSUE THREAD

**Issue by jkatsiotis** [VivaPayments/API#1818]
Hi, we are trying to use the test card 4111 1111 1111 1111 with cvv 111 and 01/21 as exp date and after the 3DS popup shows and we select "Success" as the outcome we get the following error:
"Η συναλλαγή σας απέτυχε."

See more in this vid:

https://www.loom.com/share/40eddbf3fd934a3eaeb28186fb5f877b

**Comment by matthewrgourd** [comment]
Hi @jkatsiotis I see you've raised this as a separate issue so I'll close the other one (which I had reopened). My last reply:

> Very strange, I just got it to work and I used exactly the same details for each field. Will get someone in the development team to look into this.

**Comment by jkatsiotis** [comment]
It's not an issue after all. If you look at the video the card number is invalid (has an extra "111" at the end). Test card works fine.
