### ISSUE TITLE
Redirect issue after payment -eCommerce 

### ISSUE THREAD

**Issue by MosheAssulien** [VivaPayments/API#1819]
After trying to get your customer service for almost two weeks now with no response in the the near future I'm trying my luck here.

So whenever I submit a payment on the website it redirect to vivawallet payment to complete the payment and then it should redirect back to my thank you page as defines on your website, none if that happens and it throws the customer back to our 404 page.

I have reinstalled the new plugin from your website and follow all instructions and still nothing

What else can I do?

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear that. Could you let me know your website address and the e-commerce platform you're attempting to install the plugin for? Also, your Viva Wallet account name if possible? Thanks.

**Comment by matthewrgourd** [comment]
Closing as no reply...
