### ISSUE TITLE
Is their a step by step guide I can see to integrate your payment gateway to my online business

### ISSUE THREAD

**Issue by modernman00** [VivaPayments/API#1823]
I already have a VIVA account
am struggling to integrate the account API access to my online business. 
Is their a step by step guide I can see (preferably, video)  to integrate your payment gateway to my online business. 
 what do I need?
customers will enter their card details for me to make an agreed monthly charge for an agreed period (continuous payment authority)
I have perused through the developer page, but did struggle to implement it.

**Comment by matthewrgourd** [comment]
@modernman00 please provide further info as I can't help you otherwise. The steps are different depending on how you want to integrate with us. If you can check our [developer portal](https://developer.vivawallet.com/) and find the page most relevant to you, sending me the link, I'll try to guide you further.

**Comment by modernman00** [comment]
@matthewrgourd  - thanks for coming back to me. I want to integrate payments through Viva Wallet. I have looked through the developer porta but was confused about how to integrate the API to create the payment order.

**Comment by matthewrgourd** [comment]
Hi @modernman00 do you have a website already. If so, please can I have the web address? What platform is it on? How much technical experience do you have? The answers you provide will enable me to offer you the best solution for integration.

**Comment by modernman00** [comment]
@matthewrgourd Am hoping to implement this week so any help will be appreciated.

**Comment by matthewrgourd** [comment]
@modernman00, cool, please answer my queries below so I can help you further:

>Do you have a website already? If so, please can I have the web address? What e-commerce platform is it on, if any? How much technical experience do you have?

**Comment by modernman00** [comment]
website -> www.loaneasyfinance.com. 
e-commerce platform - none
technical experience - (full stack) PHP, javascript  (over 5 years) 
Thanks.

**Comment by matthewrgourd** [comment]
Hi @modernman00, thanks for your reply. I would advise a custom integration via our [Native](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) solution. This uses our most up-to-date API to embed a payment form seamlessly within your checkout flow.

**Comment by modernman00** [comment]
Thanks @matthewrgourd . I will give that a shot
