### ISSUE TITLE
Viva terminals - semi unattended mode

### ISSUE THREAD

**Issue by lovetoast** [VivaPayments/API#1825]
Hi, if I wish to use a viva card terminal in a semi-attended environment, like a self service kiosk, if there a special mode/setting for this so a customer can't mess around with the terminal? Can I disable refunds from the card terminal?

**Comment by matthewrgourd** [comment]
Hi @lovetoast, which model of card terminal are you referring to? I will ask one of our POS experts...

**Comment by lovetoast** [comment]
Hi, a920
    On Monday, 24 August 2020, 09:43:51 BST, matthewrgourd <notifications@github.com> wrote:  
 
 


Hi @lovetoast, which model of card terminal are you referring to? I will ask one of our POS experts...

**Comment by lovetoast** [comment]
Or the A80?

**Comment by matthewrgourd** [comment]
Hi @lovetoast reply back from the team is that the only terminals we support this in currently are the Prolin terminals (not the Paydroid ones). So not the A920 or A80 but the Q30, S900 and IM20 (purpose-made unattended device).
