### ISSUE TITLE
Woocommerce v2 gateway 

### ISSUE THREAD

**Issue by Gfox1972** [VivaPayments/API#1826]
Morning I am having a few customers receiving 

"please check your card details"  

when the card has been put in correct 

anyone know what this could be please

**Comment by matthewrgourd** [comment]
@Gfox1972, sorry to hear this. Could I have the web address of the store where our plugin is enabled? I need to check a few things.

**Comment by Gfox1972** [comment]
Thanks 

@matthewrgourd  

www.thedreambikecompetition.co.uk 

I think it's down to them not entering all of there address!    as some fields are marked optional 

But please do let me know

**Comment by matthewrgourd** [comment]
Hi @Gfox1972 thanks for that. You're right, at the moment, some fields must be set as required on the billing address. The fields are: "First name", "Last name", "Email address", "Street", "City" and "Phone number". Phone number must be entered without any spaces. We're working on a fix due to be released soon. Apologies for any inconvenience caused.

**Comment by matthewrgourd** [comment]
Hi @tristanadlington the installation and setup of the source is automatic so you shouldn't edit any of those settings. The solution is as below:

>At the moment, some fields must be set as required on the billing address. The fields are: "First name", "Last name", "Email address", "Street", "City" and "Phone number". Phone number must be entered without any spaces. We're working on a fix due to be released soon. Apologies for any inconvenience caused.

Please let me know how you get on.

**Comment by tristanadlington** [comment]
@matthewrgourd Thank you that has fixed it for me. My issue was a missing mobile field. I think that is worth adding to the documentation. 

Also - is it on your roadmap to add support for recurring payments to this plugin? Specifically to work with WooCommerce Subscriptions.

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, thanks for the feedback. Regarding recurring payments, this is on the roadmap for later in the year.
