### ISSUE TITLE
Cannot make a charge using card token due to CardsGetByTokenFailedNotFound

### ISSUE THREAD

**Issue by bulivlad** [VivaPayments/API#1828]
Hi,

I am not able to make a charge using a charge token retrieved by card token due to following error
```java
{"status":404,"message":"CardsGetByTokenFailedNotFound","eventId":"6001"}
```
Currently the flow i'm trying to follow is
- create native transaction using card details
- get transaction by transactionId and save card token
- use card token to get chargeToken
```java
curl -X GET \ 
  'https://demo-api.vivapayments.com/acquiring/v1/cards/chargetokens?token=B6D3CC438671F16B211D83BBC077FEBD843CBC28' \
  -H 'Authorization: Bearer <bearerTokenHere>' \
  -H 'Content-Type: application/json'  
```
- use charge token to make an actual charge
```java
curl -X POST \
  https://demo-api.vivapayments.com/nativecheckout/v2/transactions \
  -H 'Authorization: Bearer <bearerTokenHere>' \
  -H 'Content-Type: application/json' \
  -d '{
  "amount": 1599,
  "preauth": true,
  "chargeToken": "ctok_ChXpzHjA6QCoshcN_n5vwdT68aI",
  "installments": 0,
  "merchantTrns": "Merchant transaction reference",
  "customerTrns": "Description that the customer sees",
  "currencyCode": 946,
  "customer": {
    "email": "native@vivawallet.com",
   }
}'
```

The first three steps above are working fine but on the last one I get CardsGetByTokenFailedNotFound error.

Am I doing anything wrong in the flow?

Also another thing I just noticed is that the card token generated based on a charge token is different that the card token saved on the transaction
The card token generated based on a charge token was `05FB1A1EBF41440FDF88A359C46645B6D1EE3EF5` while the card token saved on the transaction payed with that card token was `B6D3CC438671F16B211D83BBC077FEBD843CBC28`

The flow I was following:
- generate charge token
- generate card token with charge token -> `05FB1A1EBF41440FDF88A359C46645B6D1EE3EF5`
- generate charge token with card token
- create transaction with charge token
- retrieve card token from transaction -> `B6D3CC438671F16B211D83BBC077FEBD843CBC28`

Thanks

**Comment by matthewrgourd** [comment]
Hi @bulivlad, dealing with the first half of your issue, you need to generate the charge token using html / javascript similar to the below. Open in a browser and choose "Success" when the 3DS popup is displayed. Obviously you will need to replace the `authToken` value with your own bearer token. 
```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Native 3DS test</title>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://demo.vivapayments.com/web/checkout/v2/js"></script>
</head>

<body>

    <form action="" method="POST" id="payment-form">
        <div class="form-row">
            <label>
                <span>Cardholder Name</span>
                <input type="text" size="20" name="txtCardHolder" autocomplete="off" data-vp="cardholder"
                    value="Joe Blogs" />
            </label>
        </div>

        <div class="form-row">
            <label>
                <span>Card Number</span>
                <input type="text" size="20" name="txtCardNumber" autocomplete="off" data-vp="cardnumber"
                    value="4111111111111111" />
            </label>
        </div>
        <div class="form-row">
            <label>
                <span>CVV</span>
                <input type="text" name="txtCVV" size="4" autocomplete="off" data-vp="cvv" value="111" />
            </label>
        </div>
        <div class="form-row">
            <label>
                <span>Expiration (MM/YYYY)</span>
                <input type="text" size="2" name="txtMonth" autocomplete="off" data-vp="month" value="1" />
            </label>
            <span> / </span>
            <input type="text" size="04" name="txtYear" autocomplete="off" data-vp="year" value="2025" />
        </div>
        <button type="button" id="submit" (click)="submit($event)">Submit Payment</button>
    </form>
    <div id="threed-pane" style="height: 450px;width:500px">
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            const baseUrl = 'https://demo-api.vivapayments.com';
            VivaPayments.cards.setup({
                baseURL: baseUrl,
                authToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6IkpXVCIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCJ9.eyJuYmYiOjE1OTgyNjMzMjgsImV4cCI6MTU5ODI2NjkyOCwiaXNzIjoiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJhdWQiOlsiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIiwiY29yZV9hcGkiXSwiY2xpZW50X2lkIjoiZzI0N2NmbnlwYzV3cmszaHAwZnU2cTk3N2YzZzYxY2hnODV1NzJzZmJkb3c3LmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiI5NkNCNUEwNy00OENFLTREODEtODc2RC1BNkMzREY4REJEMTYiLCJzY29wZSI6WyJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmciLCJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmc6Y2FyZHM6dG9rZW5zIiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6bmF0aXZlY2hlY2tvdXR2MiJdfQ.adDbOTcuG3x8J_pNZLyZoHaU1HuL4RnKe85mfwIZez0nsZapPupo8TpYeLwBzLWQg8p6STu-QTpbxxLgsAcdVm24urwn-QbMtLmRIJiStMMEXoKHuUqZV5VDmOyObMnxZqK3nKS_x56G9z4K3qyb2CYNHIyk5Oo9Jfe4A8RqSzdVTIri2Ff6zQGG1ySybFbIsg6czbLdRExidnCPmB8vIw2mEv_fSP3qemme8wrx8M_frlpYXAWy6nV1xD2Tw1eHdvBhRtwTHYjqPJVYP4nOAC4EZlypmF8QdMPeYMudhCRaoXnh8wJB0kx2TBSwMb0GWIlf4WrL4tmDwxGcvcMa0g',
                cardHolderAuthOptions: {
                    cardHolderAuthPlaceholderId: 'threed-pane',
                    cardHolderAuthInitiated: function () {
                        $('#threed-pane').show();
                    },
                    cardHolderAuthFinished: function () {
                        $('#threed-pane').hide();
                    }
                },
                installmentsHandler: function (response) {
                    if (!response.Error) {
                        if (response.MaxInstallments == 0)
                            return;
                        $('#drpInstallments').show();
                        for (i = 1; i <= response.MaxInstallments; i++) {
                            $('#drpInstallments').append($("<option>").val(i).text(i));
                        }
                    }
                    else {
                        alert(response.Error);
                    }
                }
            });

            $('#submit').on('click', function (evt) {
                evt.preventDefault();
                VivaPayments.cards.requestToken({
                    amount: 3600
                }).done(function (data) {
                    console.log(data);
                    alert(data.chargeToken);
                });
            });

        });
    </script>
</body>
</html>
```
If you then take the resulting charge token and continue with the steps using a backend channel, you should be fine.

Regarding the second half of the issue, I'm afraid I don't really understand the question. To help me further, please include the exact contents of the following call as I don't recognise it:

>Retrieve card token from transaction

**Comment by bulivlad** [comment]
Hi, 

First half of the issue:
I'm using a similar html form to generate a charge token and charge the card which gets me a transaction id. Then i'm retrieving the transaction using api endpoint https://demo.vivapayments.com/api/transactions/{Id} and try to use the card token from the transaction

Second half of the issue:
i'm using the steps listed here https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/ to charge the customer card which generates a transaction id.
However the card token generated at Step 2 https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/#step-2-generate-card-token-using-the-charge-token-optional is different than the card token stored on the transaction - i'm using this api endpoint https://demo.vivapayments.com/api/transactions/{Id} to retrieve the transaction

**Comment by matthewrgourd** [comment]
Hi @bulivlad regarding the API call POST https://demo.vivapayments.com/api/transactions/{id}, this is from our payment API, using https://demo.vivapayments.com for the base URL, whereas card tokenization uses https://demo-api.vivapayments.com. As far as I'm aware, you cannot mix the two APIs. There is currently no call documented to check transaction information for transactions created within card tokenization.

I've tested in Postman and I can see no issue with the steps for card tokenization. I'm receiving the correct response each time. Perhaps if I show you my exact steps below this will help.

**BROWSER**

**1 Generate one-time charge token using card details in example HTML page**
https://jsbin.com/qiqehufeha/edit?html,output). 
Charge code is generated. E.g. ctok_AqD9wXipxkYk0C2v7ecp02x9q6M

**POSTMAN / BACKEND CHANNEL**

**2 Generate card token using the charge token**

**Request**
**GET** https://demo-api.vivapayments.com/acquiring/v1/cards/tokens?chargetoken=ctok_AqD9wXipxkYk0C2v7ecp02x9q6M

**Response**
```
{
    "token": "05FB1A1EBF41440FDF88A359C46645B6D1EE3EF5"
}
```
**3 Generate one-time charge token using card token**

**Request**
**GET** https://demo-api.vivapayments.com/acquiring/v1/cards/chargetokens?token=05FB1A1EBF41440FDF88A359C46645B6D1EE3EF5

**Response**
```
{
    "chargeToken": "ctok_M49efrGXPFBS2kjpFusxQQqRl10"
}
```
**4 Make the actual charge**

**Request**
**POST** https://demo-api.vivapayments.com/nativecheckout/v2/transactions
*Body*
```
{
  "amount": 100,
  "preauth": false,
  "sourceCode": "default",
  "chargeToken": "ctok_M49efrGXPFBS2kjpFusxQQqRl10",
  "Installments": 1,
  "merchantTrns": "Merchant transaction reference",
  "customerTrns": "Description that the customer sees",
  "currencyCode": 826,
  "customer": {
	  "email": "native@vivawallet.com",
	  "phone": "442037347770",
	  "fullname": "John Smith",
	  "requestLang": "en",
	  "countryCode": "GB"
   }
}
```

**Response**
```
{
    "transactionId": "2551357b-d15a-48e6-b5b5-6d442842b54f"
}
```

Does that help at all?

**Comment by bulivlad** [comment]
Hi @matthewrgourd,

Here are the steps I'm trying

**1. Generate one-time charge token using card details in example HTML page
https://jsbin.com/qiqehufeha/edit?html,output).**
Charge code is generated. E.g. ctok_CfEt-IkKu8WtNjFhYAtFFJ9QVaA

**POSTMAN / BACKEND CHANNEL**

**2. Generate card token using the charge token**

**Request**
GET https://demo-api.vivapayments.com/acquiring/v1/cards/tokens?chargetoken=ctok_CfEt-IkKu8WtNjFhYAtFFJ9QVaA

**Response**
```java
{"token":"05FB1A1EBF41440FDF88A359C46645B6D1EE3EF5"}
```

**3. Generate one-time charge token using card token**

**Request**
GET https://demo-api.vivapayments.com/acquiring/v1/cards/chargetokens?token=05FB1A1EBF41440FDF88A359C46645B6D1EE3EF5'

**Response**
```java
{"chargeToken":"ctok_wSZCOs45TlJJdW90JfRqS-nht78"}
```

**4. Make the actual charge**

**Request**
POST https://demo-api.vivapayments.com/nativecheckout/v2/transactions
_Body_
```java
{
  "amount": 1599,
  "preauth": true,
  "sourceCode": "3620",
  "chargeToken": "ctok_wSZCOs45TlJJdW90JfRqS-nht78",
  "installments": 0,
  "merchantTrns": "Merchant transaction reference",
  "customerTrns": "Description that the customer sees",
  "currencyCode": 946,
  "customer": {
    "email": "native@vivawallet.com",
   }
}
```

**Response**
```java
{"transactionId":"520d594f-e7d4-4c1d-a6fb-70adf19327ee"}
```

**5. Retrieve transaction `520d594f-e7d4-4c1d-a6fb-70adf19327ee`**

**Request**
GET https://demo.vivapayments.com/api/transactions/520d594f-e7d4-4c1d-a6fb-70adf19327ee

**Response**
```java
{
   "Transactions":[
      {
         "Fee":0.00,
         "BankId":"NET_VISA",
         "ParentId":null,
         "Switching":false,
         "Amount":15.99,
         "StatusId":"F",
         "ChannelId":"f66dce6a-95ec-404d-a2c8-ba5a6a7fae8f",
         "MerchantId":"85f35cea-b32f-4156-90d0-97e16c271c6e",
         "ResellerId":null,
         "InsDate":"2020-08-24T17:27:42.513+03:00",
         "CreatedBy":"qfvhdi7ekfqm23ugi90kthiz00rto8fte1ifs00ubekt4.apps.vivapayments.com",
         "TipAmount":0.00,
         "SourceCode":"3620",
         "TransactionId":"520d594f-e7d4-4c1d-a6fb-70adf19327ee",
         "Commission":0.00,
         "PanEntryMode":"01",
         "MerchantTrns":"Merchant transaction reference",
         "CustomerTrns":"Description that the customer sees",
         "IsManualRefund":false,
         "TargetPersonId":null,
         "AcquirerApproved":false,
         "SourceTerminalId":90000000,
         "AuthorizationId":"781446",
         "TotalInstallments":0,
         "CurrentInstallment":0,
         "ClearanceDate":null,
         "ResellerSourceCode":null,
         "RetrievalReferenceNumber":"023714781446",
         "Order":{
            "OrderCode":6888686245114791,
            "ChannelId":"f66dce6a-95ec-404d-a2c8-ba5a6a7fae8f",
            "ResellerId":null,
            "SourceCode":"3620",
            "Tags":[
               
            ],
            "RequestLang":"en-GB",
            "ResellerSourceCode":null
         },
         "Payment":{
            "Email":"native@vivawallet.com",
            "Phone":null,
            "ChannelId":"f66dce6a-95ec-404d-a2c8-ba5a6a7fae8f",
            "FullName":null,
            "Installments":0,
            "RecurringSupport":false
         },
         "TransactionType":{
            "Name":"CardPreauth",
            "TransactionTypeId":1
         },
         "CreditCard":{
            "Token":"B6D3CC438671F16B211D83BBC077FEBD843CBC28",
            "Number":"411111XXXXXX1111",
            "CountryCode":"US",
            "IssuingBank":"Demo Bank",
            "CardHolderName":"Joe Blogs",
            "ExpirationDate":"2025-01-31T00:00:00",
            "CardType":{
               "Name":"VISA",
               "CardTypeId":0
            }
         }
      }
   ],
   "ErrorCode":0,
   "ErrorText":null,
   "TimeStamp":"2020-08-24T17:29:11.4381625+03:00",
   "CorrelationId":null,
   "EventId":0,
   "Success":true
}
```

**6. Generate one-time charge token using credit card token got from transaction**

**Request**
GET https://demo-api.vivapayments.com/acquiring/v1/cards/chargetokens?token=B6D3CC438671F16B211D83BBC077FEBD843CBC28

**Response**
```java
{"chargeToken":"ctok_iBUyOXEF1d_Ix4VV27F2gt-FOjg"}
```

**7. Make the actual charge**

**Request**
POST https://demo-api.vivapayments.com/nativecheckout/v2/transactions
_Body_
```java
{
 "amount": 1599,
 "tipAmount": 0,
 "preauth": true,
 "chargeToken": "ctok_iBUyOXEF1d_Ix4VV27F2gt-FOjg",
 "installments": 1,
 "merchantTrns": "Merchant transaction reference",
 "customerTrns": "Description that the customer sees",
 "currencyCode": 946,
 "customer": {
      "email": "native@vivawallet.com"
   }
}
```

**Response**
```java
{"status":404,"message":"CardsGetByTokenFailedNotFound","eventId":"6001"}
```

**Comment by matthewrgourd** [comment]
Hi @bulivlad if you wish to create another transaction with the same card you simply repeat step 3 (in this instance using card token "05FB1A1EBF41440FDF88A359C46645B6D1EE3EF5") to generate a new one-time charge token. The token shown in the transaction details is a different one and should not be used for this purpose. Hope this helps.

**Comment by bulivlad** [comment]
Hi @matthewrgourd 

I was trying a way to retrieve the card token from transaction to perfectly fit our current payment flow. But it seems that we have to slightly change our flow.

Thanks for helping out.

**Comment by matthewrgourd** [comment]
Hi @bulivlad, ok, no problem.
