### ISSUE TITLE
Woocomerce checkout error: The site is experiencing technical difficulties.

### ISSUE THREAD

**Issue by TravelAmbassadorGroup** [VivaPayments/API#1829]
Hello there.

We set up the plugin according to the instructions https://github.com/somewherewarm/woocommerce-gateway-viva
However, in the checkout screen the following message appears: "Thank you for your order, please click the button below to pay. The site is experiencing technical difficulties."
Moreover, when we try to create webhooks in viva wallet environment, the following error message appears.
![Capture](https://user-images.githubusercontent.com/70104743/90983076-28b2e080-e574-11ea-82e4-cad6b63bff05.PNG)

Please, provide us your help.
Looking forward to your reply asap.

**Comment by matthewrgourd** [comment]
Hi @TravelAmbassadorGroup, this is not our official plugin and the developer has no affiliation with us. Please remove and download our latest plugin from  your [WooCommerce dashboard](https://woocommerce.com/my-account/downloads/) using our [documentation](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) as a guide to installation. Thanks.
