### ISSUE TITLE
Native checkout - Empty responses

### ISSUE THREAD

**Issue by orestis-s** [VivaPayments/API#183]
Προ κάποιων ημερών έγινε η μετάβαση σε παραγωγικό περιβάλλον για μία εφαρμογή (https://costo.menu) και αντιμετωπίζουμε το παρακάτω πρόβλημα.
Χρησιμοποιούμε το native checkout, και ενώ λαμβάνουμε κανονικά το cardToken, το payment request (createOrder) που αποστέλλεται από μέρους μας δεν μας επιστρέφει καμία απολύτως απάντηση, με αποτέλεσμα να μην ολοκληρώνεται η πληρωμή. Όσο ήμασταν σε δοκιμαστικό περιβάλλον οι πληρωμές ολοκληρώνονταν επιτυχώς.
Η υλοποίηση έχει γίνει βάσει των samples που παρέχονται στο github, έχουμε ήδη προβεί σε εκτενές debugging και φαίνεται πως το request που αποστέλλεται από μέρους μας, είναι πλήρες και με σωστά στοιχεία (merchant id, api key, checkout source code, amount, installments κ.λπ.)

Το output από την κλήση cURL είναι το ακόλουθο

'url' => 'https://www.vivapayments.com/api/orders',
'content_type' => NULL,
'http_code' => 0,
'header_size' => 0,
'request_size' => 0,
'filetime' => -1,
'ssl_verify_result' => 0,
'redirect_count' => 0,
'total_time' => 0.0043420000000000004,
'namelookup_time' => 0.0042360000000000002,
'connect_time' => 0.042569999999999997,
'pretransfer_time' => 0,
'size_upload' => 0,
'size_download' => 0,
'speed_download' => 0,
'speed_upload' => 0,
'download_content_length' => -1,
'upload_content_length' => -1,
'starttransfer_time' => 0,
'redirect_time' => 0,
'redirect_url' => '',
'primary_ip' => 'XX.XX.XX.XXX',
'certinfo' =>  array (),
'primary_port' => 443,
'local_ip' => 'XXX.XXX.XXX.XXX',
'local_port' => XXXX

To merchant id είναι το a5296b05-90d3-41fa-8cf2-06d0c5da6c2b
Ευχαριστώ εκ των προτέρων

**Comment by defilerc** [comment]
Καλησπέρα @orestis-s ,

Μπορείτε να δοκιμάσετε τη λύση που προτείνεται στο https://github.com/VivaPayments/API/issues/144 και να μας πείτε αν έλυσε το πρόβλημά σας;

Ευχαριστούμε πολύ,

**Comment by orestis-s** [comment]
Όντως επιλύθηκε. Ευχαριστώ
