### ISSUE TITLE
No mastercard test details in api documentation

### ISSUE THREAD

**Issue by bulivlad** [VivaPayments/API#1831]
Hi,

I'm not able to find any mastercard card details in api documentation. I can only find a visa card details reference.
However i found it working with following mastercard details:
Name: anystring
Card number: 5454 5454 5454 5454
Expiry: any date
CVV: 111

Can you please advise/update the documentation with any mastercard card test details we should use?

Thanks

**Comment by matthewrgourd** [comment]
Hi @bulivlad we are working on providing more card examples. At present we don't have one for Mastercard but thanks for the heads-up. A review will be carried out shortly. Apologies for any inconvenience caused.

**Comment by matthewrgourd** [comment]
Hi @bulivlad I've updated the dev portal with the following (new) info.:

>Mastercard 
Card number: 5900000000000000022
Expiration date: Any in the future
CVV: 111
