### ISSUE TITLE
David Cobano Pareja 

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1832]
Hi @matthewrgourd! this merchant tell me that in his payment gateway appears the next screenshot, so people think that only they can pay with paypal and this causes a lot of rejections and abandoned carts. Is there any option to solve it?
![769f5cb9-95e2-4154-877e-db6003a03156](https://user-images.githubusercontent.com/56823712/91166050-0505ac80-e6d2-11ea-9074-bf35cd170144.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada I believe this is a Shopify store (please let me know more info next time). If our plugin isn't showing up it means he hasn't set it up correctly. Please get him to check each stage of the installation process documented here:

https://developer.vivawallet.com/e-commerce-plugins/shopify/

In particular, step 11 which is the most common cause of an error.

**Comment by Alvaroalconada** [comment]
thank you like always @matthewrgourd , I´ll inform the merchant about it and If I have more questions I´ll ask you.
On the other hand, in future issues I´ll provide you the merchant´s plugin

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I'm closing this issue now, but please feel free to reopen if you have any subsequent queries.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant followed up all the steps that you wrote down above, step 11 as well. The matter is when customer wants to pay in the screenshot that I provided above he is confused between paypal and the data to fill in so that it takes you to the payment gateway to make the payment. So, merchant wants to remove field Paypal.

**Comment by Alvaroalconada** [comment]
@matthewrgourd I need an answer for the last comment pls

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada I believe this has to do with the Shopify theme settings. I found this answer in the Shopify community forum: 

- https://community.shopify.com/c/Shopify-Design/Remove-the-Express-Checkout-buttons-from-first-Checkout-Page/m-p/810310

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd this merchant is trying to set up shopify for another web https://onlye111.com/ in the same account 

Could you check it the currently status of the implementation? merchant asks me about what option he has to choice relation to payment providers in one of the shopify´s steps: manual payment, alternative or automatic?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada current status of the implementation is that he has not made his website onlye111.com live yet with products so the plugin is obviously not available for testing. The answer to your second question is "Automatic".
