### ISSUE TITLE
Error - ShopifyPlug: Signature not verified

### ISSUE THREAD

**Issue by daminufe** [VivaPayments/API#1834]
Hello.

I just followed the manual to have vivawallet on my Shopify shop, but while testing I am getting a Signature not verified error.
![image](https://user-images.githubusercontent.com/4832774/91319942-44f58e00-e7bd-11ea-992b-ef34ccdbdc8a.png)

I already requested the Store token, which I've received already, but still no luck.
Could you please help?

My Merchant ID last 4 digits are **23a9**

Thank you

**Comment by matthewrgourd** [comment]
Sorry to hear this. Please double-check the [setup procedure](https://developer.vivawallet.com/e-commerce-plugins/shopify/), paying careful attention to step 11. You have to carefully copy and paste your Merchant ID into the first field and your Store token in the second field. Any typos in either of these fields will result in the error you mention.

**Comment by daminufe** [comment]
@matthewrgourd I've triple checked it. All the same.

**Comment by matthewrgourd** [comment]
Hi @daminufe I'm checking the token you sent through by email. I'll get back to you shortly...

**Comment by matthewrgourd** [comment]
Hi @daminufe I replied by email with the correct token. Please close this issue if this has fixed the problem.

**Comment by daminufe** [comment]
Works now. Thanks. I only miss the customization.
