### ISSUE TITLE
Visa debit payments being randomly rejected by Viva 

### ISSUE THREAD

**Issue by RecVapeS** [VivaPayments/API#1836]
Have customers with functional visa debit cards, with money in the account who have used their cards the same day. Yet when they try to place an order on my store the payment is rejected by Viva. Please help, issues like this have the ability to kill my business. 
message: failed
Status failure
x test false
x result failed

**Comment by matthewrgourd** [comment]
Hi @RecVapeS , sorry to hear this. Please may I have the web address of your store? What e-commerce platform is it running on, if any? Thanks.

**Comment by RecVapeS** [comment]
Hi thanks for getting back to me,

I've spoken with tech support this morning and looked into it. Seems to be
an issue with a specific card provider in the US. Trying to find out from
customer which one.
Thanks

Matt

(+44)07397221820
https://recommendedvapesupplies.co.uk
