### ISSUE TITLE
Πρόβλημα μεταφοράς από demo σε παραγωγικό περιβάλλον

### ISSUE THREAD

**Issue by netwerkgr** [VivaPayments/API#184]
Μετά την δήλωση των μεταβλητών σε παραγωγικό περιβάλλον το object  /api/orders επιστρέφει κενό  . (https://www.vivapayments.com)

**Comment by orestis-s** [comment]
Φαίνεται να είναι το ίδιο με το #183

**Comment by defilerc** [comment]
Καλησπέρα @netwerkgr ,

Μπορείτε να δοκιμάσετε τη λύση που προτείνεται στο https://github.com/VivaPayments/API/issues/144 και να μας πείτε αν έλυσε το πρόβλημά σας;

Ευχαριστούμε πολύ,
