### ISSUE TITLE
Simple checkout activation

### ISSUE THREAD

**Issue by PyB1l** [VivaPayments/API#1840]
Hi there, I need to activate simple check out for my account. If I understood correctly, you need to activate Simple checkout access from here, both for dev and production, right?
Thanks

**Comment by matthewrgourd** [comment]
Hi @PyB1l, that's right. You can post your demo merchant ID here, to be enabled with Simple Checkout. However, for security reasons, your production merchant ID should be sent to my email address: mgourd@vivawallet.com

**Comment by PyB1l** [comment]
Hi @matthewrgourd, i can find my production merchant ID from my viva account, but where can i find my demo merchant ID?

**Comment by matthewrgourd** [comment]
Hi @PyB1l you first need to [set up a sandbox account](https://demo.vivapayments.com/), then you will find it under **Settings > API access**.

**Comment by PyB1l** [comment]
Thanks @matthewrgourd my deme merchant is 

79d707f4-488b-4485-9fe4-c357360fce88
--

**Comment by matthewrgourd** [comment]
Hi @PyB1l that's enabled for your demo account now. Thanks.
