### ISSUE TITLE
Simple Check Out

### ISSUE THREAD

**Issue by QuintaDaTor** [VivaPayments/API#1842]
I am in the finish process of testing my website.
I use the simple check out. I already had develop access. I ask using this channel to have permitting to develop part.
I were in vacation so I don´t use the test payment for a while. When I came back from holidays I try to make a demo payment and the result is the following:

![Capturar](https://user-images.githubusercontent.com/66118257/92094681-a1176e00-edcc-11ea-8396-0b320e14f7a4.PNG)

I don´t change any code for the payment. I need to continue to test the website.

**Comment by matthewrgourd** [comment]
Hi @QuintaDaTor apologies for this. There is currently an issue in the demo version of Simple Checkout meaning failures are occurring when you attempt a test transaction. This has been fixed and a release is due today. So if you're getting errors it may be worth holding off any tests again until later today / tomorrow.

**Comment by matthewrgourd** [comment]
Hi @QuintaDaTor, I'm advised by our dev team that the fix for production is now live. Regarding the demo environment, this should be available in the next hour. Thanks.

**Comment by moid1** [comment]
Hi, I got some error in testing my payment gateway.
"specified api action is disabled for the merchant 39e0b63a-1d78-4bda-88f6-5abb9f3a4334"
Can you please help me out.

**Comment by matthewrgourd** [comment]
Hi @moid, I've enabled the Simple Checkout API for you on demo.

**Comment by moid1** [comment]
Hi, Thank you for this but I got another error.


"Checkout token does not belong to merchant fbf1e090-65de-4c75-b580-d9d9bc494ad2"

Can you please guide me to resolve this error.
Thanks in advance    On Friday, September 4, 2020, 04:20:42 PM GMT+5, matthewrgourd <notifications@github.com> wrote:  
 
 


Hi @Moid, I've enabled the Simple Checkout API for you on demo.

**Comment by matthewrgourd** [comment]
Hi @moid1, sorry, it's not very clear in the documentation which I'm updating now. Replace the public key shown in the code sample with your own public key. To find this, log in to your [demo Viva Wallet account](https://demo.vivapayments.com/) and go to **Settings > API Access > Simple Checkout**. Copy and paste over the current value of `data-vp-publickey` below.

```html
<html>
    <head>
        <title>Simple Checkout</title>
    </head>
    <body>
      <form id="myform" action="/checkout" method="post">
        <button type="button"
          data-vp-publickey="F3nrgfiPzz/nTH/O/LFu7q8iaBAf9VStbVfypQde9d4="
          data-vp-baseurl="https://demo.vivapayments.com"
          data-vp-lang="en"
          data-vp-amount="1000"
          data-vp-description="My product">
        </button>
      </form>

      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://demo.vivapayments.com/web/checkout/js"></script>
    </body>
</html>
```

**Comment by moid1** [comment]
Hi, I hope you doing well. I just want to know that why Viva wallet simple checkout method (Not Demo ) not working in google chrome. Can you please help me out to sort this.Thanks
    On Friday, September 4, 2020, 04:47:08 PM GMT+5, matthewrgourd <notifications@github.com> wrote:  
 
 


Hi @moid1, sorry, it's not very clear in the documentation which I'm updating now. Replace the public key shown in the code sample with your own public key. To find this, log in to your demo Viva Wallet account and go to Settings > API Access > Simple Checkout. Copy and paste over the current value of data-vp-publickey below.
<html>
    <head>
        <title>Simple Checkout</title>
    </head>
    <body>
      <form id="myform" action="/checkout" method="post">
        <button type="button"
          data-vp-publickey="F3nrgfiPzz/nTH/O/LFu7q8iaBAf9VStbVfypQde9d4="
          data-vp-baseurl="https://demo.vivapayments.com"
          data-vp-lang="en"
          data-vp-amount="1000"
          data-vp-description="My product">
        </button>
      </form>

      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://demo.vivapayments.com/web/checkout/js"></script>
    </body>
</html>

**Comment by matthewrgourd** [comment]
Hi @moid1, sorry to hear this. Please can you share with me the exact HTML code you're using obscuring your API key and I will investigate further. Thanks.

**Comment by moid1** [comment]
Sorry for late reply, Can you please enable specific api for this merchant id 'EG6Qgt9k4XwKsIrF+EYKqTMQoKNMCFYZ/9FjirDCCHE=' (Not Demo).Thanks


    On Tuesday, September 8, 2020, 01:08:51 PM GMT+5, matthewrgourd <notifications@github.com> wrote:  
 
 


Hi @moid1, sorry to hear this. Please can you share with me the exact HTML code you're using obscuring your API key and I will investigate further. Thanks.

**Comment by matthewrgourd** [comment]
Hi @moid1, no problem. Please provide the Merchant ID for enablement. Unfortunately I can't find this via the token you sent through. For security reasons, please email me the Merchant ID: mgourd@vivawallet.com referencing this issue (#1842).

**Comment by moid1** [comment]
Sure.
    On Tuesday, September 8, 2020, 04:37:00 PM GMT+5, matthewrgourd <notifications@github.com> wrote:  
 
 


Hi @moid1, no problem. Please provide the Merchant ID for enablement. Unfortunately I can't find this via the token you sent through. For security reasons, please email me the Merchant ID: mgourd@vivawallet.com referencing this issue (#1842).

**Comment by matthewrgourd** [comment]
Hi @moid1 thanks for sending through the Merchant ID. The Simple Checkout API is now enabled in this instance.

**Comment by moid1** [comment]
Thank you
    On Tuesday, September 8, 2020, 04:40:16 PM GMT+5, matthewrgourd <notifications@github.com> wrote:  
 
 


Hi @moid1 thanks for sending through the Merchant ID. The Simple Checkout API is now enabled in this instance.

**Comment by matthewrgourd** [comment]
Hi @moid1, I've had an update from our development team which is that the production version of Simple Checkout is fine in Chrome now but we're waiting for an update in the sandbox environment. Can you confirm you're having no further issues using Chrome on production?

**Comment by moid1** [comment]
No. Its working now. Thank you.
    On Friday, September 11, 2020, 06:17:37 PM GMT+5, matthewrgourd <notifications@github.com> wrote:  
 
 


Hi @moid1, I've had an update from our development team which is that the production version of Simple Checkout is fine in Chrome now but we're waiting for an update in the sandbox environment. Can you confirm you're having no further issues using Chrome on production?
