### ISSUE TITLE
[WC] Feature request: Card number should limit input depending on card type

### ISSUE THREAD

**Issue by glagonikas** [VivaPayments/API#1843]
On the WooCommerce plugin, the "Card number" input allows up to 19 characters, regardless of the card type used.

The input is clever enough to realise what card brand is used (Visa/Mastercard/Amex) and displays the icon accordingly, so it wouldn't take more than a few lines of code to limit the character input to 16 characters for Visa and Mastercard, just like WooCommerce Stripe does.

![viva](https://user-images.githubusercontent.com/10516403/92211623-a76b2000-ee88-11ea-94e6-955a1a600354.png)

**Comment by matthewrgourd** [comment]
Hi @glagonikas, I'm discussing this with our plugin developer. I'll get back to you when I have a reply. Thanks.

**Comment by matthewrgourd** [comment]
Hi @glagonikas, I've spoken with our dev team and the solution is not quite as simple as it looks. We've added to our roadmap but I can't confirm a release date at this time. Thanks.

**Comment by matthewrgourd** [comment]
Hi @glagonikas, we've looked into this in detail and in fact the current card number validation settings for Visa are correct. 

Visa cards can have card number lengths of 13, 16, or 19.

We're looking at changing the maximum length allowed for Amex and Mastercard, neither of which can be 19 digits in length. Will keep you updated.

Please see links below for further info.

https://www.bincodes.com/bin-list/
https://www.nccgroup.com/uk/about-us/newsroom-and-events/blogs/2016/november/prepare-for-19-digit-credit-cards/
https://baymard.com/checkout-usability/credit-card-patterns

**Comment by glagonikas** [comment]
I don't think 19 digit cards are a thing yet and all references are referring to "prepare for" but none is showing a release date.

Braintree already allows 19 digit Visa after they saw the NCC link, but Stripe doesn't and they don't have a ticket in their backlog, which probably means they don't exist yet.

I believe they are not due until 2022 and Mastercard might follow suit? https://globalrisk.mastercard.com/wp-content/uploads/2018/12/8-Digit-BIN-Expansion-Mandate-and-PCI-DSS-Impact.pdf

In any case, I see no harm in having a longer number in preparation, as long as the UI allows customers to validate their card easily without scrolling. The card used below is 4242 4242 4242 4242 222
**Viva**
![viva](https://user-images.githubusercontent.com/10516403/94275449-e13abe00-ff3e-11ea-8281-63fcaf270608.png)
**Stripe**
![stripe](https://user-images.githubusercontent.com/10516403/94275764-48f10900-ff3f-11ea-8959-13826e7f0097.png)
