### ISSUE TITLE
granted access tp use API for simplecheckout

### ISSUE THREAD

**Issue by gesasav** [VivaPayments/API#1844]
my email is gesasav@gmail.com

**Comment by matthewrgourd** [comment]
Hi @gesasav if you'd like access to the production version of Simple Checkout, please email me at mgourd@vivawallet.com with your Viva Wallet Merchant ID and trading name. If it's demo access you need, just let me have your demo Merchant ID here. Thanks.

**Comment by matthewrgourd** [comment]
Hi @gesasav the Simple Checkout API is enabled for you now. Thanks.
