### ISSUE TITLE
Transaction Failed

### ISSUE THREAD

**Issue by etienneevrard** [VivaPayments/API#1845]
We having some trouble with some of our customers who try to order. 
At the end of the paiement process, and after they get the confirmation from their bank that the transaction is all good, their get a last message from our website saying there is a problem with their card. 

It happen to often the last days and we loosing a lot of business. 

Here is our website URL : www.lignevertecbd.com

Please let me know what's the problem 

Here are the details of the last three failed orders : 

**First :** 
Transaction failed with Viva-CorrelationId: 20-249-D7F6FA85

5 septembre 2020 à 15 h 49 min Supprimer la note

Transaction failed with Viva-CorrelationId: 20-249-66BC64A0

5 septembre 2020 à 15 h 46 min Supprimer la note

Transaction failed with Viva-CorrelationId: 20-249-658504AC

5 septembre 2020 à 15 h 43 min Supprimer la note

Transaction failed with Viva-CorrelationId: 20-249-983DCD80

**Second :** 
Transaction failed with Viva-CorrelationId: 20-249-3719FB88

5 septembre 2020 à 10 h 55 min Supprimer la note

Transaction failed with Viva-CorrelationId: 20-249-CBA87087

**Third one :** 
Transaction failed with Viva-CorrelationId: 20-249-CA152F5B

5 septembre 2020 à 14 h 09 min Supprimer la note

Transaction failed with Viva-CorrelationId: 20-249-E5DA131D

5 septembre 2020 à 13 h 54 min Supprimer la note

Transaction failed with Viva-CorrelationId: 20-249-B08FBA18

Also, we realised nearly every order from the french caribean , Martinique or Guadeloupe, failed most of the time. Please consider we have a lot of customers over there.

**Comment by etienneevrard** [comment]
Anyone ??? 
Too many paiement end up with an error. Please check and reply. Regards.

**Comment by etienneevrard** [comment]
Hi Matthew 
You mean they should put their phone number without any area code ? 
For example a phone number from martinique should be +59643072555. So they should put something like 0643072555 instead ? 
Do you think you will arrange this problem quick ??? Cause we loosing a lot of business actually !!



    Le lundi 7 septembre 2020 à 10:36:30 UTC+2, matthewrgourd <notifications@github.com> a écrit :  
 
 


Hi @etienneevrard, sorry to hear you're experiencing issues with customers from certain countries attempting to pay by card. We're aware there's an issue and are looking into a solution. Please not that the problem seems to be related to the phone number field when checking out. A possible workaround may be to ask customers to leave out the country code when entering their contact number.

**Comment by matthewrgourd** [comment]
Hi @etienneevrard, yes, that's right. In the meantime, can I have your company registration number / trading name, please, so I can check your account? I believe some of those transaction failures may be valid.

**Comment by etienneevrard** [comment]
Company name : HPME INVESTtrading name : Ligne Verte CBD Products Register (SIRET) : 88149294600010 www.lignevertecbd.com 
Let me know if u need more infos 

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., sept. 7, 2020 à 10:57, matthewrgourd<notifications@github.com> a écrit :   


Hi @etienneevrard, yes, that's right. In the meantime, can I have your company registration number / trading name, please, so I can check your account? I believe some of those transaction failures may be valid.

**Comment by matthewrgourd** [comment]
Hi @etienneevrard, apologies, I'm having difficulty finding you on our CRM platform. Please send me your Viva Wallet Merchant ID. My email is mgourd@vivawallet.com

**Comment by etienneevrard** [comment]
Matthew 
Here are our information again : 

HPME INVEST trade name : 
Ligne Verte CBD produc

 Registration Number: 881492946







ETIENNE EVRARD

**Comment by matthewrgourd** [comment]
@etienneevrard, please send through your Viva Wallet Merchant ID to mgourd@vivawallet.com. I can't find your details using the information you've provided (twice now – thanks). Are you definitely a Viva Wallet account holder?

**Comment by etienneevrard** [comment]
Come on Matthew, of course i am !! Why would i waste my time writing about those problems if i wasn t ... 
Anyway, here are my information again attached to this email. I did copy the screen. 
Please keep me post. Regards

**Comment by etienneevrard** [comment]
Come on Matthew, of course i am !! Why would i waste my time writing about those problems if i wasn t ... 
Anyway, here are my information again attached to this email. I did copy the screen. 
Please keep me post. Regards

    Le lundi 7 septembre 2020 à 12:24:21 UTC+2, matthewrgourd <notifications@github.com> a écrit :  
 
 


@etienneevrard, please send through your Viva Wallet Merchant ID to mgourd@vivawallet.com. I can't find your details using the information you've provided (twice now – thanks). Are you definitely a Viva Wallet account holder?

**Comment by matthewrgourd** [comment]
Hi @etienneevrard found you at last! The CRM wasn't playing ball with the registration number.

**Comment by etienneevrard** [comment]
Ok no problem 
Please fix those problems asap , we losing too much business at the moment.



    Le lundi 7 septembre 2020 à 12:48:27 UTC+2, matthewrgourd <notifications@github.com> a écrit :  
 
 


Hi @etienneevrard found you at last! The CRM wasn't playing ball with the registration number.

**Comment by matthewrgourd** [comment]
Hi @etienneevrard, please see below failure reasons I've been able to find against each date / time:

5 septembre 2020 à 15 h 49 min 
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 15 h 46 min 
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 15 h 43 min 
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 10 h 55 min 
Mastercard Do not honor (05) – LEGITIMATE 3DS FAILURE FLAGGED BY ISSUER

5 septembre 2020 à 14 h 09 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 13 h 54 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

**Comment by etienneevrard** [comment]
Imagine how much business we losing untill you fix this Please keep me post cause this is more than important for us!!! 
So waiting for this to be fix, u advise us to ask our customer not to put any area code when it comes to phone number that's it?? 
Everyday we losing money and I hate to lose money 
Regards 

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., sept. 7, 2020 à 13:05, matthewrgourd<notifications@github.com> a écrit :   


Hi @etienneevrard, please see below failure reasons I've been able to find against each date / time:

5 septembre 2020 à 15 h 49 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 15 h 46 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 15 h 43 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 10 h 55 min
Mastercard Do not honor (05) – LEGITIMATE 3DS FAILURE FLAGGED BY ISSUER

5 septembre 2020 à 14 h 09 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 13 h 54 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

**Comment by etienneevrard** [comment]
Matthew, 
Since our last email, there s a few new order that didn t reach till the end because an error again 

Can you tell me when this will be fix ??? 
That is too much business gone and there s no reason we can explain to our customers .... 


    Le lundi 7 septembre 2020 à 13:05:28 UTC+2, matthewrgourd <notifications@github.com> a écrit :  
 
 


Hi @etienneevrard, please see below failure reasons I've been able to find against each date / time:

5 septembre 2020 à 15 h 49 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 15 h 46 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 15 h 43 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 10 h 55 min
Mastercard Do not honor (05) – LEGITIMATE 3DS FAILURE FLAGGED BY ISSUER

5 septembre 2020 à 14 h 09 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

5 septembre 2020 à 13 h 54 min
Problem with API based on telephone country code – KNOWN BUG. WE ARE INVESTIGATING AND WILL APPLY A FIX ASAP

**Comment by matthewrgourd** [comment]
Hi @etienneevrard, apologies for the inconvenience. We are working on a fix and will update you as soon as a release date has been agreed.

**Comment by etienneevrard** [comment]
I don't know if it's because you guys are working on it now , but it seems like none of our customers is able to order now ... Please check the 2 latest attempt by FRED GRUSELLE ... he s one of our regular customer now and he s unable to order... 

Regards 


    Le lundi 7 septembre 2020 à 14:43:24 UTC+2, matthewrgourd <notifications@github.com> a écrit :  
 
 


Hi @etienneevrard, apologies for the inconvenience. We are working on a fix and will update you as soon as a release date has been agreed.

**Comment by matthewrgourd** [comment]
I can't see any issuer failures on the account. Have you got any correlation IDs I can check? FYI, the plugin shouldn't be affected while we're working on it behind the scenes.

**Comment by etienneevrard** [comment]
No I don't have any correlation number I can give you. The customer end up the paiement process but nothing appear neither on his screen, neither on our dashboard... Name of the customer is FRED GRUSELLE

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., sept. 7, 2020 à 16:16, matthewrgourd<notifications@github.com> a écrit :   


I can't see any issuer failures on the account. Have you got any correlation IDs I can check? FYI, the plugin shouldn't be affected while we're working on it behind the scenes.

**Comment by matthewrgourd** [comment]
Ok, no problem. As I say, no payment failures have been registered at the Viva Wallet end for a customer with that name.  If there's nothing under WooCommerce orders then the customer didn't complete the checkout process. I've just tested buying something from your website with a card with no funds and our plugin appears to be working fine. Maybe if he tries from a different browser or from a laptop (if he was previously attempting via a mobile device). This looks like a local problem unrelated to the other thing. 

I will update you once I know about the next release.

**Comment by etienneevrard** [comment]
Ok , i asked the customer to try it in a different oomputer and browser. 
But it is indeniable that there is a problem with the plugin. As u saw, there was a lot of failed yesterday and today also. I know you guys doing you maximum but yes there are a lot of problems and i hope you find where it comes from. 
Hopefully you release a new one TODAY ;) 
Regards 

    Le lundi 7 septembre 2020 à 16:37:42 UTC+2, matthewrgourd <notifications@github.com> a écrit :  
 
 


Ok, no problem. As I say, no payment failures have been registered at the Viva Wallet end for a customer with that name. If there's nothing under WooCommerce orders then the customer didn't complete the checkout process. I've just tested buying something from your website with a card with no funds and our plugin appears to be working fine. Maybe if he tries from a different browser or from a laptop (if he was previously attempting via a mobile device). This looks like a local problem unrelated to the other thing.

I will update you once I know about the scheduling of the next release.

**Comment by matthewrgourd** [comment]
Hi @etienneevrard rest assured there is not a general problem with our plugin. I just tested it. There is a specific issue with customers from certain countries which we aim to resolve hopefully this week. If you don't have a correlation id (or order in WooCommerce) for a customer, the customer has not reached the checkout page for whatever reason but it is not a problem at our end. However, if you find any more examples (specific correlation ids relating to customers) feel free to let us know, and we will investigate. Thank you for your time.

**Comment by etienneevrard** [comment]
Yes Matthew So if there s a problem with customers from certain countries it means that there s a general problem ;) And from it is a lot of our customers, you can imagine how stressfull it can beThanks for your time and thanks for letting me know when the solution will be find. Regards 

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., sept. 7, 2020 à 16:55, matthewrgourd<notifications@github.com> a écrit :   


Hi @etienneevrard rest assured there is not a general problem with our plugin. I just tested it. There is a specific issue with customers from certain countries which we aim to resolve hopefully this week. If you don't have a correlation id (or order in WooCommerce) for a customer, the customer has not reached the checkout page for whatever reason but it is not a problem at our end. However, if you find any more examples (specific correlation ids relating to customers) feel free to let us know, and we will investigate. Thank you for your time.

**Comment by matthewrgourd** [comment]
Replied by email with the new version (1.0.3 released today...attaching a copy here for convenience.
[viva-wallet-for-woocommerce_v1.0.3.zip](https://github.com/VivaPayments/API/files/5194006/viva-wallet-for-woocommerce_v1.0.3.zip)
