### ISSUE TITLE
Get credentials

### ISSUE THREAD

**Issue by annysmolyan** [VivaPayments/API#1846]
Hi! I'm trying to write my module with the VivaPayment.
Tried to get access token as described here: https://developer.vivawallet.com/authentication/#oauth-2-token-generation

but always get response like "invalid_client".

can you help here?  I read that i should create a new issue here - https://gitmemory.com/issue/VivaPayments/API/832/493079121

I need access to the demo

**Comment by matthewrgourd** [comment]
Hi @annysmolyan, please check you're copying and pasting the correct credentials from your Viva Wallet account (**Settings > API Access**):
![Screenshot_2020-09-08_at_09_15_50](https://user-images.githubusercontent.com/44943019/92451061-25466880-f1b4-11ea-81ac-122e1b39f08c.png)

**Comment by annysmolyan** [comment]
Hi @matthewrgourd . My code example on php:

$service_url = 'https://demo-accounts.vivapayments.com/connect/token';
$curl = curl_init($service_url);
curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($curl, CURLOPT_USERPWD, "here_my_decoded_user_data");
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, urlencode ('grant_type=client_credentials'));
curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
curl_setopt($curl, CURLOPT_HTTPHEADER, ["Content-Type: application/x-www-form-urlencoded"]);
$curl_response = curl_exec($curl);
$status_code = curl_getinfo($curl, CURLINFO_HTTP_CODE);   --> get 400 error

**Comment by matthewrgourd** [comment]
Hi @annysmolyan, I don't know if this will help at all, but here's a link to my working Postman request:

https://www.getpostman.com/collections/98329e9b4d990fd46ff8

**Comment by annysmolyan** [comment]
@matthewrgourd it doesn't work for me. maybe your server blocks request from locallhost?
does anybody from support know how to create curl request on php?
many thanks!

**Comment by matthewrgourd** [comment]
Hi @annysmolyan, sorry, you need to save the contents of the link as a JSON then import into Postman:
```
{"info":{"_postman_id":"ba0de6f8-2820-49b4-ac10-f5447fb294b8","name":"Share","schema":"https:\/\/schema.getpostman.com\/json\/collection\/v2.0.0\/collection.json"},"item":[{"name":"Generate bearer token","_postman_id":"2cd2a33c-d2ed-4836-bb02-7b8ce8cefd55","request":{"auth":{"type":"basic","basic":{"username":"g247cfnypc5wrk3hp0fu6q977f3g61chg85u72sfbdow7.apps.vivapayments.com","password":"m5R7n2ZJk6Fs4xyRwHjH2nh844R63E","showPassword":false}},"method":"POST","header":[{"key":"Content-Type","name":"Content-Type","type":"text","value":"application\/x-www-form-urlencoded"}],"body":{"mode":"formdata","formdata":[{"key":"grant_type","value":"client_credentials","type":"text"}]},"url":"https:\/\/demo-accounts.vivapayments.com\/connect\/token"},"response":[]}],"auth":{"type":"basic","basic":{"password":"generic_acquiring_client","username":"generic_acquiring_client.apps.vivapayments.com"}},"event":[{"listen":"prerequest","script":{"id":"181ec4a9-e3de-405c-a3ff-2a02eb6e89b5","type":"text\/javascript","exec":[""]}},{"listen":"test","script":{"id":"47c13d38-d3ec-4dd3-95c9-fdb2f4e016c3","type":"text\/javascript","exec":[""]}}],"protocolProfileBehavior":{}}
```

**Comment by annysmolyan** [comment]
@matthewrgourd many thanks! it helped!

**Comment by annysmolyan** [comment]
@matthewrgourd hi again! i have a question
When I send request for getting one time token, in response i get redirection form, after user redirection i can simulate error or success. I picked "error", but anyway was redirected to the success page which i sent in request params. How to determine, that it's error or success?
https://developer.vivawallet.com/api-reference-guide/native-checkout-v2-api/#create-a-one-time-charge-token
.

**Comment by matthewrgourd** [comment]
Hi @annysmolyan, please share with me the full request log so I can investigate further. Thanks!

**Comment by annysmolyan** [comment]
@matthewrgourd 
i use the same params as mentioned in you documentation

1) before getting ChargeToken i build this

**Comment by matthewrgourd** [comment]
@annysmolyan the field `redirectToACSForm` is nullable and will have value only if the card is enrolled to 3DS. In demo we have simulated the functionality of 3DS so that every card is "enrolled".

**Comment by annysmolyan** [comment]
@matthewrgourd i got it, but what if we will have a fail on prod env? user will be redirected back on sessionRedirectUrl? will i have some parameters that mark request failed?
how i can test error scenario on dev env? because in your form i can pick "success" or "fail" result but actually as i see it is always "success"

**Comment by matthewrgourd** [comment]
On production, when the `redirectToACSForm` HTML code is rendered, an authentication session is initiated: the user is redirected to their issuer’s page to authenticate before continuing with the transaction.

After completing the authentication session, the user is redirected to the URL defined in the `sessionRedirectUrl` parameter. The redirection signals the end of the authentication session. The final charge to the user’s card is applied when the charge token is submitted.

**Comment by matthewrgourd** [comment]
Note that 'completing the authentication session' doesn't mean that the 3DS authentication is successful it means that it has a final status (approved / declined) given by card issuer.

**Comment by matthewrgourd** [comment]
If you think there is a genuine issue with the process, I'm happy to get someone from the development team involved. Just let me know...

**Comment by matthewrgourd** [comment]
Closing as no further response from customer.

**Comment by annysmolyan** [comment]
@matthewrgourd sorry for the long response, wasn't available here.
Many thanks for your explanation about the final status (approved / declined) given by card issuer. Seems my transaction works!

**Comment by susaree** [comment]
> {"info":{"_postman_id":"ba0de6f8-2820-49b4-ac10-f5447fb294b8","name":"Share","schema":"https:\/\/schema.getpostman.com\/json\/collection\/v2.0.0\/collection.json"},"item":[{"name":"Generate bearer token","_postman_id":"2cd2a33c-d2ed-4836-bb02-7b8ce8cefd55","request":{"auth":{"type":"basic","basic":{"username":"g247cfnypc5wrk3hp0fu6q977f3g61chg85u72sfbdow7.apps.vivapayments.com","password":"m5R7n2ZJk6Fs4xyRwHjH2nh844R63E","showPassword":false}},"method":"POST","header":[{"key":"Content-Type","name":"Content-Type","type":"text","value":"application\/x-www-form-urlencoded"}],"body":{"mode":"formdata","formdata":[{"key":"grant_type","value":"client_credentials","type":"text"}]},"url":"https:\/\/demo-accounts.vivapayments.com\/connect\/token"},"response":[]}],"auth":{"type":"basic","basic":{"password":"generic_acquiring_client","username":"generic_acquiring_client.apps.vivapayments.com"}},"event":[{"listen":"prerequest","script":{"id":"181ec4a9-e3de-405c-a3ff-2a02eb6e89b5","type":"text\/javascript","exec":[""]}},{"listen":"test","script":{"id":"47c13d38-d3ec-4dd3-95c9-fdb2f4e016c3","type":"text\/javascript","exec":[""]}}],"protocolProfileBehavior":{}}

why does it only work if you import it as JSON?
so what are people supposed to do that want to connect their c# web application
