### ISSUE TITLE
Request Access to Simple Checkout API

### ISSUE THREAD

**Issue by Dropitlikehemp** [VivaPayments/API#1847]
Hi there - am new to github  / viva wallet.

Would like to install the simple checkout on my site and according to the guide i need to request access to the Simple Checkout API  - if you could ship the necessary it would be much appreciated.

V much hoping I can just copy and paste the code in to my site and all will be well in the world.

Thanks in advance for your help.

L

**Comment by Dropitlikehemp** [comment]
Thanks Matthew - will send you an email just now
_________________

Lee Brett
Co-Founder | Director

twobeards.co

**Comment by matthewrgourd** [comment]
Replied by email
