### ISSUE TITLE
Sandbox Access

### ISSUE THREAD

**Issue by SuperiaCommerce** [VivaPayments/API#1848]
Hi,

Can you please allow me access to use the Sandbox.

e2baf015-2bed-484e-88ed-5c62f896b069

Cheers

**Comment by matthewrgourd** [comment]
Hi @SuperiaCommerce, is that for Simple Checkout? Done now. Thanks.

**Comment by SuperiaCommerce** [comment]
Yes it was, thanks for that, however it doesn't appear to be working, here is my code that I am using

<form id="myform" action="/viva/return.asp" method="post">
	<button type="button" 
	data-vp-publickey="e3Iqg2OV/newavi6g6XHwm2ycHg6JP1eXvvNRMW++es=" 
	data-vp-merchantref="20200908-12" 
	data-vp-customerfirstname="David" 
	data-vp-customersurname="Coles" 
	data-vp-customeremail="david.coles@superiacommerce.co.uk" 
	data-vp-baseurl="https://demo.vivapayments.com/" 
	data-vp-lang="en" 
	data-vp-amount="59" 
	data-vp-sourcecode="2283" 
	data-vp-description="Superia Commerce Ltd DEV">Pay Now</button>
</form>
<script src="https://demo.vivapayments.com/web/checkout/js"></script>

However when I click the button nothing happens.

**Comment by SuperiaCommerce** [comment]
Sorry here is the code
```
<form id="myform" action="/viva/return.asp" method="post">
	<button type="button" 
	data-vp-publickey="e3Iqg2OV/newavi6g6XHwm2ycHg6JP1eXvvNRMW++es=" 
	data-vp-merchantref="20200908-12" 
	data-vp-customerfirstname="David" 
	data-vp-customersurname="Coles" 
	data-vp-customeremail="david.coles@superiacommerce.co.uk" 
	data-vp-baseurl="https://demo.vivapayments.com/" 
	data-vp-lang="en" 
	data-vp-amount="59" 
	data-vp-sourcecode="2283" 
	data-vp-description="Superia Commerce Ltd DEV">Pay Now</button>
</form>
<script src="https://demo.vivapayments.com/web/checkout/js"></script>
```

**Comment by SuperiaCommerce** [comment]
I already have JQuery added to the site in the header

**Comment by matthewrgourd** [comment]
Hi @SuperiaCommerce it works for me. Are you opening HTML similar to the below in your browser or JSBin?
```
<html>
    <head>
        <title>Simple Checkout</title>
    </head>
    <body>
      <form id="myform" action="/viva/return.asp" method="post">
	<button type="button" 
	data-vp-publickey="e3Iqg2OV/newavi6g6XHwm2ycHg6JP1eXvvNRMW++es=" 
	data-vp-merchantref="20200908-12" 
	data-vp-customerfirstname="David" 
	data-vp-customersurname="Coles" 
	data-vp-customeremail="david.coles@superiacommerce.co.uk" 
	data-vp-baseurl="https://demo.vivapayments.com/" 
	data-vp-lang="en" 
	data-vp-amount="59" 
	data-vp-sourcecode="2283" 
	data-vp-description="Superia Commerce Ltd DEV">Pay Now</button>
</form>

      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://demo.vivapayments.com/web/checkout/js"></script>
    </body>
</html>
```
Thanks.

**Comment by SuperiaCommerce** [comment]
Yes, that's what I'm doing, I sent you the code that I am using, it's all within the normal <html><body> tags and JQuery is already in the header of the site so I am omitting that bit as I don't want to duplicate it.
However when I click the button, nothing happens.
I can see this works when I run it in a JSBin, but why will it not work on my site? I don't get any error message or anything.

**Comment by matthewrgourd** [comment]
Hi @SuperiaCommerce, if you like, I can check your page code. Can you share the whole page omitting any confidential info? Having had a look at your code, I can confirm that everything is working fine on the Viva side.

**Comment by SuperiaCommerce** [comment]
my code repeats the form twice, could this be the issue? it repeats it for a mobile view which switches between mobile and desktop dependent on screen resolution.

**Comment by SuperiaCommerce** [comment]
Yeah I confirmed that this is the case as this also breaks the JSBin
Thanks
