### ISSUE TITLE
Payment page language

### ISSUE THREAD

**Issue by SimoneDondi** [VivaPayments/API#1849]
Hi I have an e-commerce on shopify. When someone completes the checkout he is redirected to the vivawallet payment page. By default this page is in english, is it possible to set up italian language by default? My store and checkout are in italian.

![Schermata 2020-09-08 alle 15 38 54](https://user-images.githubusercontent.com/70958989/92485753-a10fd780-f1eb-11ea-81b1-06d7b756d6a7.jpg)

**Comment by matthewrgourd** [comment]
Hi @SimoneDondi unfortunately at this moment in time, we have no way of switching automatically to Italian if store and checkout are in Italian. The customer has to manually choose **IT** from the dropdown. Apologies for any inconvenience caused, I know this is far from ideal.
