### ISSUE TITLE
Viva Wallet Payment - URL μεταφοράς όταν κάποιος θέλει να κλείσει το παράθυρο.

### ISSUE THREAD

**Issue by snatchgr** [VivaPayments/API#185]
Κατά την υλοποίηση του Payment με Viva Wallet υπάρχει τρόπος να ορίσουμε URL στο οποίο θα μεταφέρεται ο χρήστης όταν πατάει το x στο box που εμφανίζεται και του ζητάει να συμπληρώσει τα στοιχεία του?
Αυτή την στιγμή όταν κάποιος πατήσει το (χ) εμφανίζεται μια κενή σελίδα.
Δείτε attached file.
![attachedfile](https://cloud.githubusercontent.com/assets/22978617/19594034/fe9dabd4-978b-11e6-8dbf-a0e1b9f9f07b.JPG)

**Comment by defilerc** [comment]
Καλησπέρα @snatchgr ,

Δυστυχώς, δεν υποστηρίζεται η συγκεκριμένη λειτουργικότητα αυτή τη στιγμή.

Ευχαριστούμε πολύ για την επικοινωνία

**Comment by snatchgr** [comment]
Άρα ο χρήστης θα πρέπει να κάνει Back και να μεταφερθεί πίσω στο Checkοut σωστά?
Ευχαριστούμε για την άμεση ανταπόκριση.

**Comment by xargr** [comment]
@snatchgr μπορείς βέβαια να το κάνεις ένα έλεγχο με is και όταν κλείνει το παράθυρο να γίνετε redirect στην σελίδα checkout ;)
