### ISSUE TITLE
Issue with Simple Checkout Sandbox

### ISSUE THREAD

**Issue by SuperiaCommerce** [VivaPayments/API#1850]
Hi,

I am having an issue with the Simple Checkout Sandbox, everything appears to be fine, I enter the payment details, it asks me if I want the 3DSecure to be successful or not and then I just get presented with the following.

![viva-error](https://user-images.githubusercontent.com/3793433/92496892-a1f73800-f1f0-11ea-83f1-9cbeffbe0651.png)

Is there some reason why this is happening, it does nothing after this, no error message and doesn't call my callback page.

Here is my code

```
<form id="myform" action="https://dev.superiacommerce.co.uk/viva/return.asp" method="post">
	<button data-vp-publickey="e3Iqg2OV/newavi6g6XHwm2ycHg6JP1eXvvNRMW++es=" 
	data-vp-merchantref="20200908-19" 
	data-vp-customerfirstname="David" 
	data-vp-customersurname="Coles" 
	data-vp-customeremail="david.coles@superiacommerce.co.uk" 
	data-vp-baseurl="https://demo.vivapayments.com/" 
	data-vp-lang="en" 
	data-vp-amount="5900" 
	data-vp-sourcecode="2283" 
	data-vp-description="Superia Commerce Ltd DEV">Pay</button>
</form>
```

Cheers

**Comment by matthewrgourd** [comment]
Hi @SuperiaCommerce, sorry to hear this. Unfortunately there is a known issue with our sandbox at the moment. I have raised it and our development team are going to provide a fix in the next release (soon). However, should be working on live.

**Comment by matthewrgourd** [comment]
Hi @SuperiaCommerce, demo is now fixed. Thanks.
