### ISSUE TITLE
INTERMEDIA 2002 SL

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1851]
Hi @matthewrgourd I have several issues relation to this merchant , he is using currently prestashop 1.6.8:

- Last 29/8 at 18.43 we received two accepted orders, the customer only paid one... 
 
****transaction info to be emailed to mgourd@vivawallet.com
		
- On the other hand, the payment gateway continues to appear in English, although you can switch to Spanish with the top button, many customers or do not speak English, or because they have uploaded the scams on the network by covid, they think it is a fraudulent page, abandoning this method of payment, a programmer could easily change this, thus avoiding mistrust and be more professional. In case can't change it, when will be available?

- Last, I show you an email from a customer of this merchant that complaints about payment gateway: I have tried many times to process the order by bank card payment between yesterday and today, and I always receive an error message from the payment gateway saying that the operation has not been processed because "I don't have the cookies activated". I have made other card purchases on the internet between yesterday and today and have had no problems, I have deleted all the histories, cookies from my browser on several occasions, restarted my computer, etc. but the problem still occurs. I am informing you in case there is any action you should take on your part.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, please confirm the merchant's website address and trading name so I can investigate further. FYI, I'm removing the Merchant ID references from your post as they should not be shared on a public forum.

**Comment by matthewrgourd** [comment]
Closing issue as everything is working correctly from a technical perspective. I've also replied by email.
