### ISSUE TITLE
Ramón Bravo Moreno

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1852]
Hi @matthewrgourd this merchant is trying to set up the implementation of his payment gateway (woocommerce) and wants to know if the way is correct, could you check it?
![Captura1 (002)](https://user-images.githubusercontent.com/56823712/92621849-a68d2080-f2c4-11ea-8853-58ecaa92f2be.JPG)
![Captura2 (002)](https://user-images.githubusercontent.com/56823712/92621863-aa20a780-f2c4-11ea-8302-1e432f304d27.JPG)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, no it's not. With our new plugin for WooCommerce, the payment source is created automatically. Please get him to remove any existing Viva Wallet plugins, download the latest native version (1.0.3) from his WooCommerce dashboard and use our [step-by-step instructions](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) as a guide to setup. Thanks.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I see that the merchant has never downloaded our native plugin for WooCommerce. This means he will need to follow the instructions for downloading the plugin as a new customer:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#downloading-the-plugin

**Comment by matthewrgourd** [comment]
Advice given...
