### ISSUE TITLE
Change the name in the SMS of payment validation

### ISSUE THREAD

**Issue by Motionis** [VivaPayments/API#1853]
Hello !
When a customer pays on the site, he receives an SMS (3d Secure) with a code to verify the payment. However my personal name appears because it is the name of my VivaWallet account, I would like to be able to put my company name on this SMS.

How can I do this? 
Thanks a lot!

**Comment by matthewrgourd** [comment]
Hi @Motionis, can you let me have your trading name and website address so I can check something first? Thanks.

**Comment by Motionis** [comment]
Hi!
If my trading name is my merchant /company name it’s OG SPACE.
My website is www.ogspace.fr

Le ven. 11 sept. 2020 à 08:13, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @Motionis, thanks for providing that info. Having checked your account, I can see that your company name is currently set to your personal name. Please use our online chat to be found on our home page at www.vivawallet.com and ask our customer service team if this can be amended.

**Comment by matthewrgourd** [comment]
Hi @Motionis, apparently your website runs WooCommerce and is using the previous redirect version of our plugin. Perhaps you would like to upgrade to our new native version? The payment form is embedded within the checkout process rather than customers having to be redirected to another page. If you would like to install this, please deactivate and remove the existing plugin and follow the below instructions to get the new one working:

https://docs.woocommerce.com/document/viva-wallet-for-woocommerce

Thanks!

**Comment by Motionis** [comment]
Hi,

This seems to make payment easier indeed. However, I don't think it will
solve my problem.
My problem is that on the payment validation SMS when I have to put the
code to validate the payment, my name appears, and I would like to be able
to change it.




Le ven. 11 sept. 2020 à 14:41, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @Motionis, ok, no problem. You need to speak to customer services about that (see my previous reply). Unfortunately I can't do anything from here.

**Comment by Motionis** [comment]
Hello,
My VivaWallet account name has been changed but it is still my legal name
displayed on 3D secure, so it is not resolved. Can you help me?

Le mar. 15 sept. 2020 à 14:43, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @Motionis, sorry about that. I've updated another system that handles the 3DS part of things and it looks like you're ok now. I just tested with a card with no funds (Matt Gourd) and your company name is correctly displayed now.

**Comment by Motionis** [comment]
The problem has been solved thank you very much!
I wish you an excellent day.
Nathan.

Le mar. 15 sept. 2020 à 15:11, matthewrgourd <notifications@github.com> a
écrit :
