### ISSUE TITLE
Vapin Cartagena

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1854]
Hi @matthewrgourd, this merchant a79fee6b-c38c-4f20-aed7-1c2dd08c7a30 has the next question, he is trying to set up prestashop 1.6

![issue 1](https://user-images.githubusercontent.com/56823712/92902938-fa614c00-f421-11ea-931b-b2841f07e39f.png)

**Comment by matthewrgourd** [comment]
Hi, @Alvaroalconada, I'm blurring out part of the Merchant ID for security reasons. You should email me these requests not post them on GitHub which is for customers only. My email is mgourd@vivawallet.com. Thanks for your understanding in this matter.

To answer your query, the source code I can see for this merchant should be set to 3247. Looking at the entry for the installment logic field, it has a missing comma. However, please get them to leave blank, as, anyway, this facility is available in Greece only.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd! this merchant asks me the next:

´´we have already installed the payment module

we are testing to make it operational...

I have a query

Once the card number and date have been dialed

when you are asked for the payment confirmation code

the payment appears in my name, as a natural person and my ID

It would be possible to change it and have the payment appear in the name

of the website or trade name ?????

 Please tell me how I can change it...´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, they need to speak to our support team and get their trading name changed. This is what shows against the transaction. It is an account request so needs to be submitted via our online chat available on the [Viva Wallet homepage](https://www.vivawallet.com).
