### ISSUE TITLE
Help! My Sandbox Vivawallet Simple Checkout has error

### ISSUE THREAD

**Issue by Marvin261** [VivaPayments/API#1855]
Hello. I am Marvin. I am a web developer. I have a sandbox viva wallet account and I am testing payment using vivawallet simple checkout. But when I am about to charge the payment after getting the "vivaWalletToken" I got an unsuccessful payment result saying the error:  "The specified api action is disabled for the merchant 91d9caaa-6c47-4d8b-8f36-3ab47266dacb,  please consult the documentation. 

Here is the code for charging the payment with vivawallet token:
`<?php
    // retrieve vivaWalletToken from POST vars
    $vivaWalletToken = $_POST["vivaWalletToken"];

    // check if the token is defined
    if(!isset($vivaWalletToken)){
        echo ("viva wallet token is not defined");
        //and catch errors if it is not...
        return;
    }

    // define vars
    $merchantId = 'YOUR_MERCHANT_ID';
    $apiKey = 'YOUR_API_KEY';

    $url = 'https://demo.vivapayments.com/api/transactions';
    $postArgs = 'PaymentToken='.urlencode($vivaWalletToken);

    $curl = curl_init();
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $postArgs);
    curl_setopt($curl, CURLOPT_USERPWD, $merchantId . ":" . $apiKey);
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    $result = curl_exec($curl);
    curl_close($curl);
?>`

Here is the full error result returned response in JSON format
{"Emv":null,"Amount":null,"StatusId":"E","RedirectUrl":null,"CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"The specified api action is disabled for the merchant 91d9caaa-6c47-4d8b-8f36-3ab47266dacb, please consult the documentation","TimeStamp":"2020-09-14T10:13:09.3572084+03:00","CorrelationId":null,"EventId":0,"Success":false}

Please help me fix. Thank you.

**Comment by Marvin261** [comment]
<?php
    // retrieve vivaWalletToken from POST vars
    $vivaWalletToken = $_POST["vivaWalletToken"];

    // check if the token is defined
    if(!isset($vivaWalletToken)){
        echo ("viva wallet token is not defined");
        //and catch errors if it is not...
        return;
    }

    // define vars
    $merchantId = 'YOUR_MERCHANT_ID';
    $apiKey = 'YOUR_API_KEY';

    $url = 'https://demo.vivapayments.com/api/transactions';
    $postArgs = 'PaymentToken='.urlencode($vivaWalletToken);

    $curl = curl_init();
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $postArgs);
    curl_setopt($curl, CURLOPT_USERPWD, $merchantId . ":" . $apiKey);
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    $result = curl_exec($curl);
    curl_close($curl);

?>

**Comment by matthewrgourd** [comment]
Hi @Marvin261, the Simple Checkout API needed to be enabled on demo which I've done for you now. When you want to do the same on live, send me an email (mgourd@vivawallet.com) with your production Merchant ID and reference this issue (#1855).

**Comment by Marvin261** [comment]
Ok. Thank you.

**Comment by Marvin261** [comment]
I will test that now and see if that's really working.

**Comment by Marvin261** [comment]
Hello. Can we still reply here even this thread is  close? I have a problem to report on my simple checkout

**Comment by Marvin261** [comment]
When is I use Vivawallet wallet simple checkout with preauth = true and charge the transaction I got this error again. 

{"Emv":null,"Amount":null,"StatusId":"E","RedirectUrl":null,"CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"The specified api action is disabled for the merchant 91d9caaa-6c47-4d8b-8f36-3ab47266dacb, please consult the documentation","TimeStamp":"2020-09-18T10:37:14.9924834+03:00","CorrelationId":null,"EventId":0,"Success":false}

Here is the simple checkout code I use with preauthorization set to true;
`<form action="https://' . $_SERVER['HTTP_HOST'] . '/wp-content/plugins/HHootteeLLAppPlugin/VivawalletPayChargePayment.php" method="post" style="margin:5px;">
                     <button type="button" 
                        id="VivawalletPayBtn"
                        data-vp-publickey="IcxqTfWPuWndyveHX9ZCNApTTkyF48pg909rRdsIY2s="
                        data-vp-baseurl="https://demo.vivapayments.com"                        
                        data-vp-lang="en"
                        data-vp-disablewallet=true
                        data-vp-expandcard=true                      
                        data-vp-amount="' . (Int)$AmountInGBP . '"
                        data-vp-description="' . $Desc . '"
                        data-vp-merchantref="' . $Fetch['RefId'] . '"
                        data-vp-preauth=true
                        data-vp-text="Pay With Vivawallet"                                                                      
                        data-vp-sourcecode="4430"
                        data-vp-background-color="#030408"
                        data-vp-color="white"
                        data-vp-hover-background-color="#1a2242"
                        data-vp-hover-color="white"
                        data-vp-border-radius="5px"                        
                     </button>
                  </form>`

When I charge the preauthorize transaction using this code:
`$MerchantId = '91d9caaa-6c47-4d8b-8f36-3ab47266dacb';
   $ApiKey = '';
   $Amount = round($AuthPaymentData['Transactions'][0]['Amount'], 2) * 100;
   $Data = array();
   $Data['amount'] = (Int)$Amount;
   $Data['customerTrns'] = $AuthPaymentData['Transactions'][0]['CustomerTrns'];
   $Data['merchantTrns'] = $AuthPaymentData['Transactions'][0]['MerchantTrns'];
   $Data = json_encode($Data);
   
   //$Url = 'https://www.vivapayments.com/api/transactions/' . $AuthPaymentData['Transactions'][0]['TransactionId']; // live version
   $Url = 'https://demo.vivapayments.com/api/transactions/' . $AuthPaymentData['Transactions'][0]['TransactionId']; // sandbox version
   $AuthorizationHeader = 'Basic ' . base64_encode($MerchantId . ':' . $ApiKey);
   $Header = (array("Accept: application/json","Content-Type: application/json", "Authorization: " . $AuthorizationHeader, "GoCardless-Version: 2015-07-06"));
   $Options = array('http' => array('header' => $Header, 'method' => 'POST', 'content' => $Data, 'ignore_errors' => true ));
   $Context  = stream_context_create($Options);
   $Result = file_get_contents($Url, false, $Context);

echo $Result;
`
Response  error json format
'{"Emv":null,"Amount":null,"StatusId":"E","RedirectUrl":null,"CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"The specified api action is disabled for the merchant 91d9caaa-6c47-4d8b-8f36-3ab47266dacb, please consult the documentation","TimeStamp":"2020-09-18T10:37:14.9924834+03:00","CorrelationId":null,"EventId":0,"Success":false}'

**Comment by matthewrgourd** [comment]
I've checked again your demo merchant ID "91d9caaa-6c47-4d8b-8f36-3ab47266dacb" and it is definitely enabled for Simple Checkout so I don't know why you're getting the "api action is disabled" error.

From the below I can see you're missing a "**>**" from the last parameter. Last parameter should be closed as follows `data-vp-border-radius="5px">`
```
<button type="button" 
                    id="VivawalletPayBtn"
                    data-vp-publickey="IcxqTfWPuWndyveHX9ZCNApTTkyF48pg909rRdsIY2s="
                    data-vp-baseurl="https://demo.vivapayments.com"                        
                    data-vp-lang="en"
                    data-vp-disablewallet=true
                    data-vp-expandcard=true                      
                    data-vp-amount="' . (Int)$AmountInGBP . '"
                    data-vp-description="' . $Desc . '"
                    data-vp-merchantref="' . $Fetch['RefId'] . '"
                    data-vp-preauth=true
                    data-vp-text="Pay With Vivawallet"                                                                      
                    data-vp-sourcecode="4430"
                    data-vp-background-color="#030408"
                    data-vp-color="white"
                    data-vp-hover-background-color="#1a2242"
                    data-vp-hover-color="white"
                    data-vp-border-radius="5px"                        
                 </button>
              </form>
```
Beyond that, I see that you're customising our Simple Checkout code and I'm afraid we don't offer technical support on that. Best of luck!
