### ISSUE TITLE
French Language

### ISSUE THREAD

**Issue by Ghos1ware** [VivaPayments/API#1856]
Hey guys,
I'm implementing your solution for a customer. The store is in French.

I've added the following to the button: data-vp-lang="fr", and the modal is entirely translated in French. Great ! However, when using this attribute value, the button is in Greek. If I set it back to data-vp-lang="en", the button is in English and the modal as well.

**Comment by Ghos1ware** [comment]
(This can be fixed by using the data-vp-text="Your button text"), but yeah, still, a little thing to fix for you guys ;)

**Comment by matthewrgourd** [comment]
Hi @Ghos1ware thanks for letting us know, I will raise with our dev team.
