### ISSUE TITLE
Sandbox Charge Attempts fails due to permissions ?

### ISSUE THREAD

**Issue by Ghos1ware** [VivaPayments/API#1857]
Hey,
Having troubles trying to implement your solution on a customer website.

When attempting to charge a test card, the API returns an error. (The specified api action is disabled for the merchant 73a7d1fa-0a7d-48ee-9d1a-2b28089f0da0, please consult the documentation)

Can you please enable that on my account ?

Thank you !

**Comment by matthewrgourd** [comment]
Hi @Ghos1ware the Simple Checkout API needed to be enabled on demo which I've done for you now. When you want to do the same on live, send me an email (mgourd@vivawallet.com) with your production Merchant ID and reference this issue (#1857).
