### ISSUE TITLE
Δεν παίζει το vivapayments.com (resolve issue)

### ISSUE THREAD

**Issue by aboukouris** [VivaPayments/API#186]
Καλησπέρα,

Από τις 20:00 σήμερα δεν παίζει η χρέωση με κάρτα από το website μας. Πήρα τηλέφωνο και ρώτησα αν έχετε κάποιο πρόβλημα. Μου είπαν κανένα, ότι όλα παίζουν μια χαρά (!!). 

Εψαξα λοιπόν μήπως έχουμε πρόβλημα εμείς... αλλά δεν έχουμε. Το πρόβλημα είναι ότι το vivapayments.com σταμάτησε να εξυπηρετείται από DNS. Πήρα πάλι τηλέφωνο και τους το είπα... και μου είπαν "να μπω στο github". Ζήτησα να ενημερώσουν κάποιον τεχνικό άμεσα διότι έχετε σοβαρό πρόβλημα και μου λένε "εμείς δεν έχουμε πρόβλημα".

Ορίστε αν έχετε ή όχι:

![2016-10-21](https://cloud.githubusercontent.com/assets/22987086/19608987/339b457a-97dd-11e6-969d-c8d06c0c3e4a.png)

Δεν παίζει τίποτα, και το vivapayments.com δεν γίνεται resolve γιατί οι DNS έχουν πέσει.

**Comment by defilerc** [comment]
Καλησπέρα @aboukouris ,

Θα θέλαμε να σας ενημερώσουμε πως το πρόβλημα που αναφέρετε, δεν οφειλόταν σε κάποια δυσλειτουργία των συστημάτων της VivaPayments, αλλά σε πρόβλημα εξυπηρέτησης των DNS servers σε παγκόσμιο επίπεδο, ύστερα από DDoS attack, όπως μπορείτε να δείτε και στα παρακάτω links:

1. http://www.businessinsider.com/amazon-spotify-twitter-github-and-etsy-down-in-apparent-dns-attack-2016-10
1. http://www.slate.com/blogs/future_tense/2016/10/21/a_lot_of_the_internet_went_down_this_morning_this_is_probably_why.html

Με βάση την ημερομηνία, στην οποία έγινε αναφορά του προβλήματος από μεριά σας, η πιο πιθανή αιτία για το πρόβλημα που αντιμετωπίσατε ήταν αυτή.

Ευχαριστούμε πολυ για την επικοινωνία,
