### ISSUE TITLE
Feature request: Display link to transaction ID

### ISSUE THREAD

**Issue by glagonikas** [VivaPayments/API#1860]
On the order details page on admin, there should be a link to the transaction so we can easily open up the transaction details on https://members.vivawallet.com/

I do understand this might require some changes on the vivawallet.com dashboard as well so you can open the transaction details directly, but the amount of effort required is minimal.

The plugin adds a note showing the transaction ID, but the search bar on "Sales Transactions" does not search for the transaction ID. The only way is to use the "Advanced Search" and place the transaction ID in the relevant field.

In contrast, both the PayPal and Stripe plugins have direct links to that transaction, so there's 100% no chance of staff error when searching for a transaction

![paypal](https://user-images.githubusercontent.com/10516403/93464479-20cf2d80-f8e1-11ea-9460-db22aefb6d0f.png)
![stripe](https://user-images.githubusercontent.com/10516403/93464482-2167c400-f8e1-11ea-987e-1ec9e87ab98d.png)

**Comment by matthewrgourd** [comment]
Hi @glagonikas, many thanks for your suggestion. We're currently looking into whether this is straightforward to do. Will let you know an update soon.

**Comment by matthewrgourd** [comment]
Hi @glagonikas, many thanks for this. We've had an initial look but it isn't as straightforward as it might sound. However, it's on the roadmap for a future release....
