### ISSUE TITLE
Need Some Help Please ! Issue with Payment & Redirection

### ISSUE THREAD

**Issue by ACB13** [VivaPayments/API#1861]
Hello, 

Using VivaWallet since a few month for my web-store. 
I contact  you because I have some problems with VivaWallet.

The bigger one happen when a client make a purchase using is credit card. The payment works fine in VivaWallet Payment Page and the client is charge but nothing return to the woocomerce interface and the command stay in pending mode and after few hours become canceled. The connection between woocomerce and VivaWallet seem to be broke. Do you know how to solve this problem please ? 

The other one is about the redirection page after a purchase from client using VivaWallet. The page redirection is not reach and an error page appears. It's very annoying cause it confuse the client and we don't really know if the command is done or not. 

My website is : https://www.greenstorecbd.net/
My VivaWallet Marchand ID is : 5d5d1a16-63e7-41c5-b4cb-cd12476fc517

Thanks in advance fore your help.

Adrien

**Comment by matthewrgourd** [comment]
Hi @ACB13, if you see a status "Pending payment" in WooCommerce after a customer attempted to buy something from your store it means they didn't complete their payment details correctly. The status should later change to cancelled. This is normal behaviour. I've had a look at your account and I notice you're currently using the previous version of our plugin. The latest version has improved functionality and embeds natively into your website. Please deactivate and delete the current version, then download the new one from the below page: 

https://woocommerce.com/products/viva-wallet-for-woocommerce/

Instructions are provided on the following page:

https://docs.woocommerce.com/document/viva-wallet-for-woocommerce

I just tried a test purchase on your website (with a card with no funds) and I can see that your settings for our plugin are incorrect. However, purchases should still be able to get through. But I would advise disabling and deleting the previous version of our plugin as soon as possible. The new one is a lot better.

Thanks!

**Comment by ACB13** [comment]
Thank you very much for your assistance. And sorry the late answer. 
I have installed the new plugin and all seem to be working fine again. 
I let you know if I see some new issue. 

Thanks

**Comment by matthewrgourd** [comment]
No problem, closing the issue but please feel free to reopen if you experience any further issues...
