### ISSUE TITLE
Help Me! My Sandbox Vivawallet Simple Checkout PreAuthorization Has Error

### ISSUE THREAD

**Issue by Marvin261** [VivaPayments/API#1863]
When is I use Vivawallet wallet simple checkout with preauthorization(data-vp-preauth=true) and charge the preauthorize transaction I got this error again. 

{"Emv":null,"Amount":null,"StatusId":"E","RedirectUrl":null,"CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"The specified api action is disabled for the merchant 91d9caaa-6c47-4d8b-8f36-3ab47266dacb, please consult the documentation","TimeStamp":"2020-09-18T10:37:14.9924834+03:00","CorrelationId":null,"EventId":0,"Success":false}

Here is the simple checkout code I use with preauthorization set to true;

> <form action="https://' . $_SERVER['HTTP_HOST'] . '/wp-content/plugins/HHootteeLLAppPlugin/VivawalletPayChargePayment.php" method="post" style="margin:5px;">
                     <button type="button" 
                        id="VivawalletPayBtn"
                        data-vp-publickey="IcxqTfWPuWndyveHX9ZCNApTTkyF48pg909rRdsIY2s="
                        data-vp-baseurl="https://demo.vivapayments.com"                        
                        data-vp-lang="en"
                        data-vp-disablewallet=true
                        data-vp-expandcard=true                      
                        data-vp-amount="' . (Int)$AmountInGBP . '"
                        data-vp-description="' . $Desc . '"
                        data-vp-merchantref="' . $Fetch['RefId'] . '"
                        data-vp-preauth=true
                        data-vp-text="Pay With Vivawallet"                                                                      
                        data-vp-sourcecode="4430"
                        data-vp-background-color="#030408"
                        data-vp-color="white"
                        data-vp-hover-background-color="#1a2242"
                        data-vp-hover-color="white"
                        data-vp-border-radius="5px"                        
                     </button>
                  </form>

When I charge the preauthorize transaction using this code:

```
$MerchantId = '91d9caaa-6c47-4d8b-8f36-3ab47266dacb';
   $ApiKey = '';
   $Amount = round($AuthPaymentData['Transactions'][0]['Amount'], 2) * 100;
   $Data = array();
   $Data['amount'] = (Int)$Amount;
   $Data['customerTrns'] = $AuthPaymentData['Transactions'][0]['CustomerTrns'];
   $Data['merchantTrns'] = $AuthPaymentData['Transactions'][0]['MerchantTrns'];
   $Data = json_encode($Data);
   
   //$Url = 'https://www.vivapayments.com/api/transactions/' . $AuthPaymentData['Transactions'][0]['TransactionId']; // live version
   $Url = 'https://demo.vivapayments.com/api/transactions/' . $AuthPaymentData['Transactions'][0]['TransactionId']; // sandbox version
   $AuthorizationHeader = 'Basic ' . base64_encode($MerchantId . ':' . $ApiKey);
   $Header = (array("Accept: application/json","Content-Type: application/json", "Authorization: " . $AuthorizationHeader, "GoCardless-Version: 2015-07-06"));
   $Options = array('http' => array('header' => $Header, 'method' => 'POST', 'content' => $Data, 'ignore_errors' => true ));
   $Context  = stream_context_create($Options);
   $Result = file_get_contents($Url, false, $Context);

echo $Result;
```
Response  error json format

`{"Emv":null,"Amount":null,"StatusId":"E","RedirectUrl":null,"CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"The specified api action is disabled for the merchant 91d9caaa-6c47-4d8b-8f36-3ab47266dacb, please consult the documentation","TimeStamp":"2020-09-18T10:37:14.9924834+03:00","CorrelationId":null,"EventId":0,"Success":false}`

Please enable my simple checkout preauthorization with my merchant id.
Please help me fix this as soon as possible so that I can finish this work.

**Comment by matthewrgourd** [comment]
I've checked again your demo merchant ID "91d9caaa-6c47-4d8b-8f36-3ab47266dacb" and it is definitely enabled for Simple Checkout so I don't know why you're getting the "api action is disabled" error.

From the below I can see you're missing a "**>**" from the last parameter. Last parameter should be closed as follows `data-vp-border-radius="5px">`
```
<button type="button" 
                    id="VivawalletPayBtn"
                    data-vp-publickey="IcxqTfWPuWndyveHX9ZCNApTTkyF48pg909rRdsIY2s="
                    data-vp-baseurl="https://demo.vivapayments.com"                        
                    data-vp-lang="en"
                    data-vp-disablewallet=true
                    data-vp-expandcard=true                      
                    data-vp-amount="' . (Int)$AmountInGBP . '"
                    data-vp-description="' . $Desc . '"
                    data-vp-merchantref="' . $Fetch['RefId'] . '"
                    data-vp-preauth=true
                    data-vp-text="Pay With Vivawallet"                                                                      
                    data-vp-sourcecode="4430"
                    data-vp-background-color="#030408"
                    data-vp-color="white"
                    data-vp-hover-background-color="#1a2242"
                    data-vp-hover-color="white"
                    data-vp-border-radius="5px"                        
                 </button>
              </form>
```
Beyond that, I see that you're customising our Simple Checkout code and I'm afraid we don't offer technical support on that. Best of luck!

**Comment by Marvin261** [comment]
I already remodify the html form and did what you said but I still got error. "The specified api action is disabled for the merchant 91d9caaa-6c47-4d8b-8f36-3ab47266dacb".

I tested a non preauthorized test simple checkout and its working and automatically charge payment. But I am looking for preauthorize simple checkout. Please enable preauthorize simple checkout "data-vp-preauth=true" on my merchant id.

**Comment by Marvin261** [comment]
Right now I already found a solution without enabling any preauthorize checkout or payment in vivawallet.  I do not need to enable my redirect checkout. If preauthorize simple checkout and  preauthorize redirect checkout is not yet available  in sandbox account account, its fine with me. I will close this thread/post. Thank you.
