### ISSUE TITLE
Request access to Simple Checkout API

### ISSUE THREAD

**Issue by Diavlos** [VivaPayments/API#1864]
Hello, could you give me an access to the Simple Checkout API.
Thank you.

**Comment by matthewrgourd** [comment]
Hi there, in order to facilitate this I need your Viva Wallet Merchant ID. Thanks.

**Comment by Diavlos** [comment]
768306e6-71ca-4657-b3f5-12c344394541

**Comment by matthewrgourd** [comment]
Enabled as requested. I'm blurring out your Merchant ID now for security.

**Comment by Diavlos** [comment]
Thank you very much. Regards.
