### ISSUE TITLE
Problem with confirmation on smartphone

### ISSUE THREAD

**Issue by Diavlos** [VivaPayments/API#1865]
Hello, submit button on 3d secure confirmation screen is not clickable. Also other links (cancel and request for new OTP) are also not clickable. This happens on smartphones. Any idea?
![119753994_359744372058025_4752061243819399868_n](https://user-images.githubusercontent.com/71500008/93606234-70d8ed80-f9d0-11ea-80ff-05f39c50cf5e.png)

**Comment by matthewrgourd** [comment]
Not sure, I just tried my Viva Wallet card with an iPhone and the 3DS process seems to work fine. Can you give me more info. about your device / browser / OS version please? Also, which website are you experiencing this issue on?

**Comment by Diavlos** [comment]
Hi, my device is a Samsung galaxy s6 and I'm trying to pay over the app I'm working on. It uses the webkit. Everything is ok with a payment, until I have to confirm it by the code. The window you can see on the above screenshoot is scrollable horizontally, so I can move it left and right, but the button and the text links are not clickable. So because it is not a website, at the moment I can not give you a chance to try, sorry.

**Comment by Diavlos** [comment]
Finally I made a payment, but after pushing the SUBMIT button many many times. May be this happens because of the small size of the button? As I had seen, the 3D secure runs as an IFRAME into the IFRAME of the Viva, Do you have any access to that. Because I think this form really was not made for mobile devices. There is no responsive CSS at all. Any idea?

**Comment by Diavlos** [comment]
Any help?

**Comment by matthewrgourd** [comment]
Hi @Diavlos your suggestion as to what the problem could be sounds valid. I need to run this past the technical team to see if they have any advice. I'll get back to you soon...

**Comment by Diavlos** [comment]
OK, thank you. Hope it will not take a lot of time to resolve the problem.

**Comment by matthewrgourd** [comment]
Hi @Diavlos, I've checked with our dev team and the 3DS bit of the payment process is handled by a third-party not by Viva Wallet. However, if it isn't working as expected it may be something to do with your app.

**Comment by Diavlos** [comment]
Hi @matthewrgourd, there are no other mobile friendly 3DS?
