### ISSUE TITLE
Creating new transactions for native checkout

### ISSUE THREAD

**Issue by Sotiris-k** [VivaPayments/API#1866]
Hello,

In the developers portal there are two ways to create a transaction.

The [first one](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-5-make-the-actual-charge) and the [second one](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/post) also the second one includes the order entity which isn't mentioned at all in the first one.

Which one should we follow?

**Comment by matthewrgourd** [comment]
Hi @Sotiris-k, if you wish to implement our Native Checkout, it will always be the first one you mention.

**Comment by Sotiris-k** [comment]
I have implemented the second one a long time since and I don't know if there's any correlation with it being the wrong implementation but I'm getting a lot of seemingly random 502 errors among a lot of successful transactions.

Should I take it as a sign to switch to the first one?

**Comment by matthewrgourd** [comment]
This is what I would advise, yes.

**Comment by Sotiris-k** [comment]
Thank you very much @matthewrgourd.
