### ISSUE TITLE
Payments not working for Wholesale Customers - VivaWallet for WooCommerce 

### ISSUE THREAD

**Issue by tristanadlington** [VivaPayments/API#1867]
Payments are working fine for regular customers but not for my wholesale customers. 

"There was a connection problem. Please try again later"

It has not worked for several wholesale customers (Wholesale customers defined by plugin Wholesale for WooCommerce) 

I have double checked they have phone numbers assigned to their account and they have.

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, sorry to hear this. Could you let me know which version of our plugin for WooCommerce you are using? Can I also have your trading name and website address so I can check your account?

**Comment by tristanadlington** [comment]
I have updated to latest version of plugin, and this appears to have fixed it when I test it on myself. 

However, I have now noticed a new issue. 

When logged in as a wholesale customer, I see and checkout with discounted prices. However, when I go to pay via VivaWallet it is trying to charge me the full retail price so it isn't picking up on the discounted pricing. 

Trading name: Pot Head Coffee
www.pothead.coffee

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, there's no reason why our plugin shouldn't be able to handle that as it always takes the total from whatever the WooCommerce cart total is. One question, how does someone register and get access to wholesale prices. I tried registering just now (mgourd@vivawallet.com) but can't see any options.

**Comment by tristanadlington** [comment]
They apply via this page: http://pothead.coffee/wholesale-registration

It is a different user role. 

I can change your user role from customer to wholesale if you wish. I have screenshots that prove it tried to charge me more than the total. 
![Screenshot 2020-09-23 at 12 43 00](https://user-images.githubusercontent.com/28437173/94029496-c63c4280-fdb4-11ea-91f9-6a89871f1dbf.png)
![Screenshot 2020-09-23 at 12 42 41](https://user-images.githubusercontent.com/28437173/94029502-c76d6f80-fdb4-11ea-90a7-be6b502d008a.png)

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, please apply 'wholesale' to my user profile so I can see for myself what is happening. Thanks!

**Comment by tristanadlington** [comment]
@matthewrgourd - This has been done. Thank you.

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, I've just done a test and I couldn't see any change when logged into the website. However, I received an invoice with a payment link including the Viva Wallet symbol. Not sure how you've done that but it doesn't seem to work. I attempted to make a payment with a card with no funds and should have got a card error but it looked like the payment went through which is impossible. Apologies, but we don't support whatever custom invoice it is you have built there.

**Comment by tristanadlington** [comment]
Hi Matt, we have not built any custom invoices. They are styled to match our brand, but not customised. 

Not sure which email features the VivaWallet symbol. I created you a custom wholesale order, then emailed you the invoice through WooCommerce here.
![image](https://user-images.githubusercontent.com/28437173/94121527-54620880-fe49-11ea-83fe-dfaecc9d1e75.png)

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, ok, well as far as I'm aware, our plugin can't be used in this scenario, only within the checkout process on a WooCommerce store.

**Comment by tristanadlington** [comment]
This is the checkout process on a WooCommerce store though? The only difference is I am adding the products to their cart and then sending them a link to the checkout. It's no different to an abandoned cart really. I think the plugin should support it properly.

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, let me double-check with our plugin developer and get back to you with a definitive answer.

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, out plugin developer has confirmed we don't support manual invoicing at this moment in time. Although it is a Woo feature, it won't currently work with our plugin. However, it's on the roadmap for a future release. Apologies for any inconvenience caused. At the moment, if you want to send manual payment links to specific customers, we can offer you our [Quick Pay](https://developer.vivawallet.com/payment-tools/quick-pay/) service.
