### ISSUE TITLE
payment interrupted and automatic return to the compilation screen - purchase registered on the site but payment does not arrive

### ISSUE THREAD

**Issue by AndreaVacca** [VivaPayments/API#1869]
Hello, we ask you if you can check purchases # 8530 and # 8531 on our website. We have recently installed the vivawallet payment plugin. These two customers say that when they finish filling in all the card details and click send, instead of processing the payment and completing the purchase, they are again shown in the order compilation field and the purchase is not completed. Can you see if the vivawallet payment plugin has had any problems? We have some bug notes released by the plug in. I copy them below if it helps. Thank you.

**This for order 8530**
Transaction failed with Viva-CorrelationId: 20-266-48C87E20

22 Settembre 2020 alle 02:09 Elimina nota

Transaction failed with Viva-CorrelationId: 20-266-105C4A4C

22 Settembre 2020 alle 02:07 Elimina nota

Transaction failed with Viva-CorrelationId: 20-266-12B7A1E6

22 Settembre 2020 alle 02:07 Elimina nota

Transaction failed with Viva-CorrelationId: 20-266-3B8D93F7

22 Settembre 2020 alle 02:06

for the order 8531 we haven't any note, only what the customer say. 

 Thanks, we await your reply.

**Comment by matthewrgourd** [comment]
Hi @AndreaVacca , please confirm your trading name, company registration number and website address so I can investigate for you. Thanks.

**Comment by AndreaVacca** [comment]
trading name is: Weweed di andrea Vacca

Registration number is:  01223520956

website: https://prodotti-cannabis.it/

Il giorno mar 22 set 2020 alle ore 11:36 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment]
Hi @AndreaVacca, also, please confirm the version of our plugin you're using. Have you installed the latest, v.1.0.3?

**Comment by AndreaVacca** [comment]
Version 1.0.3  yes

Il giorno mar 22 set 2020 alle ore 11:41 matthewrgourd <
notifications@github.com> ha scritto:

**Comment by matthewrgourd** [comment]
Hi @AndreaVacca we've checked and all the payment failures were due to customers failing their 3DS authentication. Hope this helps!

**Comment by matthewrgourd** [comment]
Please close this issue if you are happy with the response.
