### ISSUE TITLE
Σφάλμα μετά από αλλαγές

### ISSUE THREAD

**Issue by andyz1974** [VivaPayments/API#187]
Καλησπέρα σας. 
Στην σελίδα native payments έκανα κάποιες αλλαγές στην φόρμα και στα πεδία, ώστε να  γίνει πιο λειτουργική. Στο demo λειτουργεί κανονικά, αλλά όταν το βάζω στο live site, με το που βάζω τον αριθμό της κάρτας, εμφανίζεται το εξής μήνυμα:
JS frame :: https://code.jquery.com/jquery-1.11.2.min.js :: .send :: line 4"  data: no] 
σε popup.

Τι σημαίνει αυτό και πώς μπορώ να το διορθώσω;

**Comment by defilerc** [comment]
Καλησπέρα @andyz1974 ,

Τι ακριβώς αλλαγές κάνατε στα πεδία; 

Το πρώτο βήμα στη Native Checkout είναι το card tokenization, το οποίο λειτουργεί παίρνοντας τα html πεδία που έχουν το `data-vp` attribute και στέλνοντάς τα στο server, ώστε να πάρει η σελίδα το token.

Μπορείτε να επιβεβαιώσετε ότι το tokenization σαν πρώτο βήμα λειτουργεί σωστά;

Με εκτίμηση,

**Comment by andyz1974** [comment]
Τελικά το παραπάνω σφάλμα ήταν λόγω των διαφορών από http:// σε https://. 
Ωστόσο ενώ τα πεδία της κάρτας έχουν όλα τα αντίστοιχα data-vp μετά το Submit λαμβάνω το μήνυμα uncaught "exception: VivaPayments: Required data-vp attribute "cardnumber" was not found"
Μέχρι το submit, η διαδικασία φαίνεται να προχωράει κανονικά

**Comment by andyz1974** [comment]
Τελικά, κάποια από τις ρυθμίσεις μου ξέφευγε. Το έφτιαξα. Σας ευχαριστώ πολύ.
