### ISSUE TITLE
Payments shown as successful in Woocommerce, but not showing up in VivaWallet

### ISSUE THREAD

**Issue by gtlsgamr** [VivaPayments/API#1870]
Hey, So I have set up the live credentials and they are accepted. Now Whenever an order is placed, the payment is shown as successful but no money/transaction is being shown in my vivawallet account.

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, sorry to hear this. Can you let me have your website address and I will check your account? If you give me a date / time for 2 or 3 of the orders where payment hasn't been received?

**Comment by gtlsgamr** [comment]
Hey the site is https://simplyhooked.be. Only the first order payment wasn't received and I didn;t make any orders after that. I cant even refund the order, it says transaction Id could not be recieved. 
Payment via Payment card (Viva Wallet). Paid on September 21, 2020 @ 10:24 am. Customer IP: 109.136.43.198

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr I've checked your settings and it looks like our plugin is installed incorrectly. Please deactivate and delete the existing plugin, then [download the latest version](https://woocommerce.com/products/viva-wallet-for-woocommerce/) (v1.0.3) following the [installation instructions](https://docs.woocommerce.com/document/viva-wallet-for-woocommerce) closely. The Viva Wallet payment source is created automatically and should not have any additional Success / Failure URL information added afterwards. The native version of our plugin works on a different principal from the redirect version which I notice you may have used before. Thanks.

**Comment by gtlsgamr** [comment]
Hey, I followed all these instructions and still, the same issue.
Payment via Payment card (Viva Wallet). Paid on September 23, 2020 @ 12:46 pm. Customer IP: 109.136.43.198

This time I am sure I used the native and not redirect method. I used the credentials perfectly as well.

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr can you confirm the payment source ID currently being used by the plugin? (**Plugins > Installed Plugins > Payments > Viva Wallet for WooCommerce > Advanced Settings > Source Code List** dropdown.)

**Comment by gtlsgamr** [comment]
WC-0005 its this.

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, thanks. For some reason you had some out-of-date settings in WC-0005 which I've now removed. Can you try checkout again now as it should be working?

**Comment by gtlsgamr** [comment]
Tried again. Same issue. Money is deducted but doesn't go in my vivawallet.
Both orders for 1 EUR: 
Payment via Payment card (Viva Wallet). Paid on September 28, 2020 @ 1:28 pm. Customer IP: 109.136.43.198

Payment via Payment card (Viva Wallet). Paid on September 28, 2020 @ 1:40 pm. Customer IP: 109.136.43.198

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, we've released a new version of our plugin, v1.1.0. Please remove the existing one and try this:

viva-wallet-for-woocommerce-v1.1.0.zip

Thanks,

Matt

**Comment by gtlsgamr** [comment]
Just did that. Now, it is not accepting my live credentials and showing an apple pay error. 

![image](https://user-images.githubusercontent.com/47787284/94555225-e5d1e000-0278-11eb-8148-e38642a5e82c.png)

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, ignoring the Apple Pay error for the moment, I believe you may need to copy and paste your [WooCommerce credentials](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#viva-wallet-for-woocommerce-credentials) from Viva Wallet selfcare again:

![woocommerce-credentials](https://user-images.githubusercontent.com/44943019/94565322-f70ef280-0260-11eb-9b66-211a6d910720.png)

**Comment by gtlsgamr** [comment]
Hello, yes. I'm sorry I'm bothering you repeatedly but I already tried this, twice. Then I generated a new secret, that didn't work either. Then I tried through a demo account, which didn't work as well.

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, please bear in mind every time you click **Generate** for a new key you then you need to copy it across to the plugin settings. Obviously only use the demo credentials from your [demo Viva Wallet account](https://demo.vivapayments.com/) if you have 'demo' selected in the plugin. Otherwise use the credentials from your [live Viva Wallet account](https://app.vivawallet.com/).

Could you also send us the log file relating to our plugin? Go to **WooCommerce > Status** and click on the **Logs** tab. Select today's date from the drop-down and click on the **View** button. Copy and paste into a text file and attach to your reply to this GitHub issue. Thanks!

**Comment by gtlsgamr** [comment]
Here, sorry for the late reply. And yes, I know I need to paste the new secret. 
[logs.txt](https://github.com/VivaPayments/API/files/5311019/logs.txt)

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, thanks for providing the log file. I'm checking with our plugin developer. I'll get back to you shortly.

**Comment by gtlsgamr** [comment]
Hey matt, any updates?

**Comment by matthewrgourd** [comment]
Hi there, we've just released a new version of the plugin which should fix the issue. I suggest you deactivate and delete all current versions of the plugin and replace with this one:
https://developer.vivawallet.com/downloads/viva-wallet-for-woocommerce_v1.1.1.zip

**Comment by gtlsgamr** [comment]
Hello, I installed the new plugin after removing the previous version, and thankfully, the credentials are being accepted now. What's happening is that i am getting this message, unable to process your order, both in LIVE and DEMO credentials.
![image](https://user-images.githubusercontent.com/47787284/95473187-78712e00-09a1-11eb-8e67-b5009c97ea4a.png)

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr that looks like a WooCommerce error message. Not sure what the issue is. I just tried testing Viva Wallet via https://www.simplyhooked.be/ but I don't think the plugin is enabled. Can you enable it for 20 minutes or so?

**Comment by gtlsgamr** [comment]
Just did. please check

**Comment by matthewrgourd** [comment]
@gtlsgamr thanks. Testing now...

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr looks the plugin is in demo mode. You need to add the WooCommerce credentials from your **demo** Viva Wallet account. Alternatively, switch to live mode and add the WooCommerce credentials from your **live** Viva Wallet account. The page to visit in the banking app to [grab your credentials](https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/#section-6) is **Settings > API Access** and looks like this:

![woocommerce-credentials](https://user-images.githubusercontent.com/44943019/95572380-c62d7b00-0a21-11eb-9b8d-8677ed6d0bcd.png)

**Comment by gtlsgamr** [comment]
Hello Matt, I knew that and was already using demo credentials. Technically it should work with demo credentials in demo mode, no?

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr I got an error at checkout related to the demo credentials being wrong. Have you updated them now?

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, I've tested again and I'm getting a different error this time. Will run it past our dev team and get back to you!

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr we've noted that you have the URL `cafedeparis/checkout` where one call is going to `https://www.simplyhooked.be/cafedeparis/?wc-ajax=checkout` and the other to `https://www.simplyhooked.be/?wc-ajax=checkout`. Are the moment our plugin requires the second option rather than the first. Is it possible for you to change?

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, alternatively if you're unable to make that change, we've got a patch for you. Please remove the current version of the plugin and install the below:

[viva-wallet-for-woocommerce_v1.1.1_simplyhooked.zip](https://github.com/VivaPayments/API/files/5355422/viva-wallet-for-woocommerce_v1.1.1_simplyhooked.zip)

Let us know how you get on. Thanks!

**Comment by gtlsgamr** [comment]
Oh my god, sorry I wasn't able to reply due to the weekend.
But I am installing the patch right now and will get back to you ASAP.

**Comment by gtlsgamr** [comment]
Nope, still the same issue.

![image](https://user-images.githubusercontent.com/47787284/95739876-208c3d00-0ca9-11eb-870f-98fcc54c393f.png)

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, sorry to hear that. Can you try something for me? In the plugin [required settings](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#step-2-specify-required-settings), can you deliberately leave out the live client secret and click on save. This will force an error. Next, enter the correct client secret, and click on save again. Enable the Viva Wallet plugin on live. Let me know when you've done that. Thanks!

**Comment by gtlsgamr** [comment]
Hey, Let me clarify, I got the screenshotted error on demo mode with demo credentials. Do you want me to follow your instructions with demo credentials, or is live mode necessary for that?

**Comment by gtlsgamr** [comment]
Hello, I tried the above with DEMO credentials and it worked! But only halfway. I got till this screen >>> 
![image](https://user-images.githubusercontent.com/47787284/95742695-043ecf00-0cae-11eb-926a-05b986fa7944.png)
and then when I click on the confirm payment option, I got this error >>>
![image](https://user-images.githubusercontent.com/47787284/95742749-1a4c8f80-0cae-11eb-9024-0e3c4577f469.png)
Keep in my this was all in DEMO mode.

**Comment by matthewrgourd** [comment]
Hi did you try making the pretend payment with a [test card](https://developer.vivawallet.com/getting-started/#test-cards)?

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, I notice some key details are missing from your demo account (company name etc.) I believe our API may need these so please also test (using the same steps) with the live merchant account.

**Comment by gtlsgamr** [comment]
I made them using a test card. I will try with live credentials and get back to you. It might take a little while, but Ill get back!

**Comment by gtlsgamr** [comment]
Hello Matt, I had it tried and now it shows the unable to process error again.

**Comment by matthewrgourd** [comment]
HI @gtlsgamr, please note that "We were unable to process your order, please try again." is an error from WooCommerce rather than our plugin. I've just tested the checkout process and noted the following:

- you still have an Ajax call going to `https://www.simplyhooked.be/cafedeparis/?wc-ajax=checkout` when I believe it needs to be `https://www.simplyhooked.be/?wc-ajax=checkout` for our plugin to work
- there' seems to be an error (see below screenshot) relating to the WooODT plugin you're got installed. Maybe try testing our plugin after disabling this one? 

![Screenshot 2020-10-13 at 08 29 27](https://user-images.githubusercontent.com/44943019/95830512-afdc3380-0d2f-11eb-802d-d82b84059682.png)

If none of the above suggestions work, one more thing you could try is delete the credentials from the admin page of the plugin and save. The plugin will produce an error that "Your credentials are not valid. Please check your credentials". At that point re-enter your credentials and save again.

**Comment by gtlsgamr** [comment]
> you still have an Ajax call going to https://www.simplyhooked.be/cafedeparis/?wc-ajax=checkout when I believe it needs to be https://www.simplyhooked.be/?wc-ajax=checkout for our plugin to work
I thought your patched plugin was supposed to fix this? See, the thing is, this is a wordpress multisite setup, and like cafedeparis, there are going to be multiple sites stored in subdirectories, so changing the url is out of question. 

> there' seems to be an error (see below screenshot) relating to the WooODT plugin you're got installed. Maybe try testing our plugin after disabling this one?

I will have a look at this. Meanwhile, I hope you can solve the issue with ajax call.

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, I'm checking with our plugin developer for you.

**Comment by gtlsgamr** [comment]
Thank you!

**Comment by matthewrgourd** [comment]
Hi @gtlsgamr, our developer has confirmed that he can see the Ajax calls are working now after the patch. He thinks it could be a caching issue. No new customers will have the problem. I just tested with a card with no funds (in incognito mode) and the correct response was given. It is working fine now.

**Comment by gtlsgamr** [comment]
Thank you so much! It is working now, you've been a great help!
