### ISSUE TITLE
CSS broken on some resolutions on 3DS

### ISSUE THREAD

**Issue by Diavlos** [VivaPayments/API#1871]
Hello @matthewrgourd , I describe the problem in the previous issue, but you close it without resolving the problem. Check the image below:
![VivaIssue](https://user-images.githubusercontent.com/71500008/94005740-625f4d00-fda7-11ea-8729-2822836d409d.JPG)

1) On the first icon you can see how the form of 3DS shows inside my mobile APP using webkit. 
The problem that I could not click the button is that the string marked with red arrow falls over the links and the button.

2) On the second icon you can see how it shows inside chrome browser on my phone. The same string also on the wrong place, before the input field. Also values on the info table are below titles (name, amount, title etc.)

3) On the third icon is how it shows inside chrome browser on PC. Everything is OK with a width of 368px.

4) On the forth icon the same thing, but under the width of 365px values on the info table are below titles and the problem with the string "call for any problem to the....." also exist.

So the problem with the 3DS form is everywhere, in any devices with the screen width smaller than 365px.

The second thing I found is that you use Modirum solution for the 3ds confirmation. If so, I found that you could use your own css when loading it in IFRAME. Check the image below.
![image](https://user-images.githubusercontent.com/71500008/94006949-507ea980-fda9-11ea-8b49-08194df140a2.png)

I found it on third paragraph here:
https://www.modirum.com/products/vposgw/

What do you think? Is there any way to fix it for smaller resolutions by you?

**Comment by matthewrgourd** [comment]
Hi @Diavlos I will take your suggestion to the development team and see what their response is. Thanks.

**Comment by Diavlos** [comment]
Hello @matthewrgourd , do you have any news about this issue?

**Comment by matthewrgourd** [comment]
Hi @Diavlos, not yet, I will chase today...

**Comment by Diavlos** [comment]
Thank you.

**Comment by matthewrgourd** [comment]
Hi @Diavlos I've spoken to our technical team and apparently we're changing our 3DS provider soon so all of this will be looked at afresh. Our Modirum setup is not going to be updated before that, but thanks again for your suggestion.

**Comment by matthewrgourd** [comment]
Hi @Diavlos, I've raised within our front-end team and will let you know an update soon!

**Comment by matthewrgourd** [comment]
Hi @Diavlos, we've looked into this further but I have been informed that we've changed our 3DS provider so the issue should no longer occur. Thanks.

**Comment by Diavlos** [comment]
Hi @matthewrgourd . Yes the problem is gone now. The new provider works very well as it was chacked on some small devices. Thank you.
