### ISSUE TITLE
The specified api action is disabled

### ISSUE THREAD

**Issue by VirtualColossus** [VivaPayments/API#1872]
I'm getting the following error on a demo account, when trying to call the api/transactions url for a completed payment please can you activate it so I can complete testing.

"The specified api action is disabled for the merchant 5d21ce40-a47e-4642-b3c4-3caa719c0e76, please consult the documentation"

**Comment by matthewrgourd** [comment]
Hi @VirtualColossus, sorry to hear that. I've enabled the API for you now.

**Comment by VirtualColossus** [comment]
Thank you - it's working now.
