### ISSUE TITLE
Problem to back to download after a payment

### ISSUE THREAD

**Issue by Taig7** [VivaPayments/API#1873]
Hello,
I don't know how to configure VivaWallet so that after a payment of a virtual product, VivaWallet redirects to the download of the product.
Can anyone help me?
Thank you in advance.

**Comment by matthewrgourd** [comment]
Hi @Taig7, this is handled by WooCommerce. Please check the following article for info. on how to do that:

https://docs.woocommerce.com/document/digital-downloadable-product-handling/

**Comment by Taig7** [comment]
My plugin WooCommerce was already configurated for downloading of virtual product with "Force downloads". It worked with PayPal before and the window to download appeared. But with VivaWallet, the windows does'nt appear after the payment.
![Download](https://user-images.githubusercontent.com/21078462/94125097-364ed500-fe56-11ea-8127-27daec012f75.jpg)

**Comment by matthewrgourd** [comment]
Hi @Taig7, can I have your website address and trading name so I can look into this further?

**Comment by Taig7** [comment]
Hi @matthewrgourd,
I have a website for adult sexe-elite .com/en/
After the payment, there is no screen to download my formation.

**Comment by matthewrgourd** [comment]
Hi @Taig7, I've checked your account and you're not using our latest WooCommerce plugin. Please deactivate and delete the one that exists already, and download the following ZIP file to your desktop:

[viva-wallet-for-woocommerce-v1.1.0.zip](https://github.com/VivaPayments/API/files/5297642/viva-wallet-for-woocommerce-v1.1.0.zip)

Then follow our guide from [Installation](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#installation) onwards.

**Comment by Taig7** [comment]
Hi @matthewrgourd,
Do you have a solution for the mention "There was a problem with your card. Please check the card details and try again"?

**Comment by matthewrgourd** [comment]
Hi @Taig7, usually it means the card issuer has declined the transaction. However, I can't see any activity against your Viva Wallet account so I'm not sure what's happening. How are you attempting to integrate with our platform? Do you have Wordpress with WooCommerce or is it just Wordpress?

**Comment by matthewrgourd** [comment]
Closing as no reply...
