### ISSUE TITLE
Page freezing after checkout By customer

### ISSUE THREAD

**Issue by WNascimento77** [VivaPayments/API#1875]
Hi,

Numerous customers placed an order after entering card details and their screen freezes. The order comes through on woo commerce as pending payment. If i do not manually change the order status on woocommerce to processing then the pending payment status becomes cancelled and the payment does not go through. If i do change it manually then the payment goes through.

This is obviously quite an issue as i cannot be logged in dashboard 24/7 to manually change the order status. I do not have the most up to date word press, but do have the most up to date vivawallet plugin. Do you think i will need to update the wordpress to most recent version?

**Comment by WNascimento77** [comment]
I seem to get an order confirmation and then a order recovery email confirmation straight away. If you could test it your side that would be great.

**Comment by matthewrgourd** [comment]
Hi @WNascimento77, after entering card details, and clicking to confirm, a 3DS popup will be displayed. The customer has to complete this otherwise no payment will go through. If you see an order in WooCommerce with "Pending Payment" it means no payment has been received. You have to take the payment in another way (e.g. via Viva Wallet Quick Pay) then change the status to "Completed". However, I'm happy to check your account. Could I have your website address and trading name? Thanks.

**Comment by WNascimento77** [comment]
PureConnect CBD
    	
    	

    	Get Outlook for iOS
    
  




On Thu, Sep 24, 2020 at 3:58 PM +0100, "matthewrgourd" <notifications@github.com> wrote:















Hi @WNascimento77, after entering card details, and clicking to confirm, a 3DS popup will be displayed. The customer has to complete this otherwise no payment will go through. If you see an order in WooCommerce with "Pending Payment" it means no payment has been received. You have to take the payment in another way (e.g. via Viva Wallet Quick Pay) then change the status to "Completed". However, I'm happy to check your account. Could I have your website address and trading name? Thanks.

**Comment by WNascimento77** [comment]
Hi Matthew,
I thought I have vivawallet quick pay installed. Please could you check as this was not happening before.
My website https://www.pureconnectcbd.co.uk
    	
    	

    	Get Outlook for iOS
    
  




On Thu, Sep 24, 2020 at 3:58 PM +0100, "matthewrgourd" <notifications@github.com> wrote:















Hi @WNascimento77, after entering card details, and clicking to confirm, a 3DS popup will be displayed. The customer has to complete this otherwise no payment will go through. If you see an order in WooCommerce with "Pending Payment" it means no payment has been received. You have to take the payment in another way (e.g. via Viva Wallet Quick Pay) then change the status to "Completed". However, I'm happy to check your account. Could I have your website address and trading name? Thanks.

**Comment by matthewrgourd** [comment]
Hi @WNascimento77, I just tested buying something (with a card with no funds) from your website and the plugin seems to be working fine. If you have any queries regarding transaction failures, please send me the date and approximate time of the attempted payment and I'll let you know the failure reason. Thanks.

**Comment by WNascimento77** [comment]
Thanks Matthew. 
A payment that failed was made on 19th September 2020 time 08:22 in the morning value £42
    	
    	

    	Get Outlook for iOS
    
  




On Thu, Sep 24, 2020 at 5:19 PM +0100, "matthewrgourd" <notifications@github.com> wrote:















Hi @WNascimento77, I just tested buying something (with a card with no funds) from your website and the plugin seems to be working fine. If you have any queries regarding transaction failures, please send me the date and approximate time of the attempted payment and I'll let you know the failure reason. Thanks.

**Comment by matthewrgourd** [comment]
Hi @WNascimento77, I can see one failure on 19th but it's at 22:22. The amount is €42.03 The reason for the failure is "Mastercard Exceeds withdrawal amount limit (61)". The card holder should contact their issuer if they want to know further details. If you're referring to a different order, no payment details were provided, so you need to get the customer to place the order again.

**Comment by WNascimento77** [comment]
Thanks Matthew. If I have same issue I will contact you again.
Thanks for checking and your assistance 🙏
    	
    	

    	Get Outlook for iOS
    
  




On Thu, Sep 24, 2020 at 5:31 PM +0100, "matthewrgourd" <notifications@github.com> wrote:
















Hi @WNascimento77, I can see one failure on 19th but it's at 22:22. The amount is €42.03 The reason for the failure is "Mastercard Exceeds withdrawal amount limit (61)". The card holder should contact their issuer if they want to know further details. If you're referring to a different order, no payment details were provided, so you need to get the customer to place the order again.
