### ISSUE TITLE
How can i disable IVR in woocommerce plugin?

### ISSUE THREAD

**Issue by gfuchris** [VivaPayments/API#1876]

**Comment by gfuchris** [comment]
Is there any workaround for this ?

**Comment by matthewrgourd** [comment]
Hi @gfuchris, I'm sorry, can you elaborate? Not sure exactly what you mean by that.

**Comment by gfuchris** [comment]
> 
> 
> Hi @gfuchris, I'm sorry, can you elaborate? Not sure exactly what you mean by that.

**Comment by gfuchris** [comment]
> 
> 
> > Hi @gfuchris, I'm sorry, can you elaborate? Not sure exactly what you mean by that.

Hi, i use the viva payments plugin with woocommerce for a client of mine,  and he needs to disable the IVR (phone orders) option, and i can not diasable it as there is no option for that (in woocommerce plugin or in viva admin page of my client).
I know this is done by code, can you help?

**Comment by gfuchris** [comment]
> 
> 
> > Hi @gfuchris, I'm sorry, can you elaborate? Not sure exactly what you mean by that.
Sorry, closed by mistake...
I use the viva payments plugin with woocommerce for a client of mine, and he needs to disable the IVR (phone orders) option, and i can not diasable it as there is no option for that (in woocommerce plugin or in viva admin page of my client).
I know this is done by code, can you help?

**Comment by matthewrgourd** [comment]
Hi @gfuchris, not sure, sounds like a WooCommerce thing. Check their support? https://woocommerce.com/contact-us/

**Comment by gfuchris** [comment]
> 
> 
> Hi @gfuchris, not sure, sounds like a WooCommerce thing. Check their support? https://woocommerce.com/contact-us/

no, i didn't but as the IVR option is by viva i thought it wouldn't be a woo thing.It'w something like this but for woocommerce (this is for magento): [https://github.com/VivaPayments/API/issues/270?fbclid=IwAR0fTVTJKBX4Nagpzv1qlVog7I2WYyz4NskL9LusNctFy0t1wctxeVUiuG4#issuecomment-383157039](url)

**Comment by webitbz** [comment]
In V3.6.2 wc-vivawallet.php change:
`$body = [
                'Amount'            => $poststring['Amount'],
                'RequestLang'       => $poststring['RequestLang'],
                'Email'             => $poststring['Email'],
                'MaxInstallments'   => $maxperiod,
                'MerchantTrns'      => $order_id,
                'SourceCode'        => $this->vivawallet_source,
                'CurrencyCode'      => $currency_symbol,
                'PaymentTimeOut'    => 300
            ];`

To:
`$body = [
                'Amount'               => $poststring['Amount'],
                'RequestLang'       => $poststring['RequestLang'],
                'Email'                    => $poststring['Email'],
                'MaxInstallments'   => $maxperiod,
                'MerchantTrns'        => $order_id,
                'SourceCode'          => $this->vivawallet_source,
                'CurrencyCode'       => $currency_symbol,
                'DisableIVR'             => true,
                'PaymentTimeOut'   => 300
            ];`

**Comment by matthewrgourd** [comment]
@webitbz, looks correct – thanks very much! @gfuchris please check the above. Thanks.

**Comment by gfuchris** [comment]
It didn't work until i used double quote: 'DisableIVR' => "true"
Thank you very much for your time and efforts
