### ISSUE TITLE
Native checkout v2 - Step 5: Make the actual charge 

### ISSUE THREAD

**Issue by lovetoast** [VivaPayments/API#1878]
Hi, on native checkout V2:

Step 5: Make the actual charge 

If you do not proceed with the step (i.e. the customer has entered the card details and generated a charge token, but you do not call the API in step 5), I presume, nothing will be charged to the customer's card?

**Comment by matthewrgourd** [comment]
Hi @lovetoast, that is correct, until you use the card token in a transaction, no money is taken.

**Comment by lovetoast** [comment]
@matthewrgourd Hi Matt, thanks, I presume you mean card OR charge token, right?

**Comment by matthewrgourd** [comment]
@lovetoast sorry, I meant **charge** token! If you have a card token you have to convert it into a charge token before you can take a payment.

**Comment by lovetoast** [comment]
Thanks @matthewrgourd - hope you have a good weekend.
