### ISSUE TITLE
simple checkout request for streaming site - www.thetisTV.gr

### ISSUE THREAD

**Issue by tassoskouts** [VivaPayments/API#1879]
greetings.

I would like to embed viva payment plugin for site www.thetistv.gr (redirecting to www.pay-tv.gr), in order to provide paying mechanism for our fans. We sell live streaming material and memberships cards to our fans.
I am in charge for the streaming  platform and I am developing paying module.

Please guide me for the next steps. What do I have to provide as information?

Thanks 
Tassos Koutsomboris

**Comment by matthewrgourd** [comment]
Hi @tassoskouts, no problem. Most people try out Simple Checkout using a Viva Wallet demo account first. Do you have one of these? If so, what is the Merchant ID so I can enable the API?

**Comment by matthewrgourd** [comment]
Hi @tassoskouts I believe this has already been addressed in a duplicate issue.
