### ISSUE TITLE
Η συναλλαγή απέτυχε σε κάθε δοκιμή που κάνω

### ISSUE THREAD

**Issue by nikpony** [VivaPayments/API#188]
Καλησπέρα σας,
στο καινούργιο eshop που φτιάχνουμε (yourstore.gr) έχουμε εγκαταστήσει ένα plugin του prestashop από την επίσημη σελίδα του Prestashop, αποκλειστικά για Viva Payments.
Έχω συμπληρώσει στα στοιχεία της Πηγής Πληρωμών όπως ακριβώς τα έχει περιγράψει ο developer του plugin και βρίσκομαι στο σημείο της πληρωμής της παραγγελίας μου και συνέχεια μου λέει ότι η συναλλαγή αποτυγχάνει.
Μπορείτε να με βοηθήσετε σας παρακαλώ;
Ένας κωδικός συναλλαγής που τώρα προσπάθησα είναι ο  8655746579172609
Ευχαριστώ εκ των προτέρων

**Comment by defilerc** [comment]
Καλησπέρα @nikpony ,

Θα θέλαμε να σας ενημερώσουμε πως το ελάχιστο ποσό για το οποίο μπορείτε να δημιουργήσετε order code είναι τα 0.30€. 

Παρακαλώ πολύ, ξανά δοκιμάστε, με κάποιο μεγαλύτερο ποσό.

Ευχαριστούμε πολύ

**Comment by nikpony** [comment]
Σωστά, αυτό ήτανε.
Ευχαριστώ πολύ.
Δεν θα έπρεπε όπως να υπάρχει στη σελίδα της πληρωμής ένα κουμπί επιστροφής στην δική μας σελίδα;

**Comment by defilerc** [comment]
Καλησπέρα @nikpony ,

Αυτή τη στιγμή κάτι τέτοιο δεν υποστηρίζεται. Αν ο χρήστης κλείσει τη σελίδα της Viva, τότε η παραγγελία (Order) θα γίνει κάποια στιγμή expired (ανάλογα το timeout που ορίστηκε κατά τη δημιουργία του).

Με εκτίμηση,
