### ISSUE TITLE
receiving error on Simple Checkout (demo enviroment)

### ISSUE THREAD

**Issue by tassoskouts** [VivaPayments/API#1880]
Greetings.

I am receiving an error during simple checkout , I am posting json printing for debug (I am following instructions from https://developer.vivawallet.com/online-checkouts/simple-checkout/)  :
/**************************************************************************************/
stdClass Object ( [Emv] => [Amount] => [StatusId] => E [RedirectUrl] => [CurrencyCode] => [TransactionId] => [ReferenceNumber] => [AuthorizationId] => [RetrievalReferenceNumber] => [ThreeDSecureStatusId] => [ErrorCode] => 403 [ErrorText] => The specified api action is disabled for the merchant e7f53b52-d0cf-4102-a6a2-5093f1dda4d7, please consult the documentation [TimeStamp] => 2020-09-26T11:23:12.4572836+03:00 [CorrelationId] => [EventId] => 0 [Success] => )

/**************************************************************************************/
May you have to enable my demo merchant?

Thanks

Tassos Koutsomboris

**Comment by matthewrgourd** [comment]
Hi @tassoskouts, I've enabled the Simple Checkout API for you on your demo account. Thanks.

**Comment by tassoskouts** [comment]
Greetings.

my merchant id is : 

I have the same issue for my customer, with merchant id 680924138691for production (dev:310922594420).

May you enable Simple Checkout API also for him? or he may follow the same process, by placing a request on hiw own?

T.

**Comment by ThetisTV** [comment]
I represent ASPE ThetisTV ( merchant id in prod: 680924138691 and in dev:310922594420 ).

I confirm request, please give us access to demo enviroment.

Thanks in advance, An. Triantafyllou, President of ASPE THETIS Voulas Volleyball Club.

**Comment by matthewrgourd** [comment]
Hi @tassoskouts @ThetisTV, now enabled (on both production and demo). Thanks!
