### ISSUE TITLE
Mandeep Kooner

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1881]
Hi @matthewrgourd this merchant 95910A9F-8122-47A5-9695-C16342DF109F has the next issue:

At the beginning she was using woocommerce but was wrong implemented and now the plugin has been deleted, desactivated and reinstalled again. After that two different customers (one Sabadell credit card and one a Spanish debit card) are both displaying this message that I attach you. What should she has to do for fixing it?

![IMG-20200927-WA0000](https://user-images.githubusercontent.com/56823712/94362595-d443d900-00bc-11eb-96a3-05627cbf47ba.jpg)

**Comment by lovetoast** [comment]
Was this Visa or Mastercard?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada can you please translate the error message into English for me? Our plugin is working correctly but the customer needs to change their browser cookie settings. It is not a Viva Wallet issue but an issue to do with the customer's local settings.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd message says ´´operation not performed, your browser has cookies disabled. To ensure proper operation, you must activate them first. ´´ Could you show me how the merchant change her browser cookie settings?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, ok, the translation confirms my advice. As I say, this is not a Viva Wallet issue. If the merchant needs to know how to change their cookie settings for a particular device / browser, they should be able to find out by doing a search on Google. Alternatively, it may be there's a reset button for their privacy settings available, in which case they should click on that.
