### ISSUE TITLE
Tudor

### ISSUE THREAD

**Issue by Tudor301** [VivaPayments/API#1882]
The Mastercard payments are getting declined . 3D Secure is not working for Mastercard and the paymets are getting declined.
I'm using Shopify Plug In

**Comment by lovetoast** [comment]
Was your account recently setup? If so, mastercard 3D secure takes up to 72 hours.

**Comment by Tudor301** [comment]
Yes today.

Visa is working perfectly with no issue on processing the payment.
Only on Mastercard i got declined payments.

Kind regards,
Tudor.

**Comment by lovetoast** [comment]
@Tudor301 OK, mastercard 3D  will take a couple of days for setup

**Comment by matthewrgourd** [comment]
Hi @Tudor301, sorry to hear this. @lovetoast is right, registration with Mastercard 3DS is not always instantaneous. Could I have your website address then I can check for you?

**Comment by Tudor301** [comment]
Www.touchsale.co.uk

**Comment by matthewrgourd** [comment]
Hi @Tudor301, we've checked and your merchant registration went through yesterday. For Mastercard 3DS enrolment it takes 2 further working days, usually, so I believe that tomorrow it will be fine. Sorry for the delay!

**Comment by Tudor301** [comment]
That's great. Thank you for your help.

**Comment by Tudor301** [comment]
Hi,

Still not working the Mastercard. The card getting declined.

**Comment by matthewrgourd** [comment]
@Tudor301, really? Ok, let me check again...

**Comment by matthewrgourd** [comment]
Hi @Tudor301 we're looking into this and will get back to you as soon as possible.

**Comment by Tudor301** [comment]
Hi,

All working now.

Kind regards,
Tudor.
