### ISSUE TITLE
Card Tokenization: get masked details of card in response

### ISSUE THREAD

**Issue by pantelispanayiotou** [VivaPayments/API#1883]
I need to tokenize my user's credit cards and i went through the api documentation. I would like to add a save card option so that i i can generate a token and make transactions without having user to re enter their credit card details. However i would like to give the ability to the users to save multiple cards. Is there an option to get the masked credit card number after the card token is generated? It seems that i can get these details only using the Transaction API but this does not get the job done.

**Comment by matthewrgourd** [comment]
Hi @pantelispanayiotou I'm afraid there's no option to do this for card tokens, only transactions that have already taken place. Thanks.

**Comment by lovetoast** [comment]
@pantelispanayiotou @matthewrgourd The alternative would be to send the last 4 digits of the card field to your API (which I don't think breaks PCI compliance) and then save it. Essentially, take the form input and the last 4 characters. Alternatively, you could simply just add a nickname for the card.

**Comment by pantelispanayiotou** [comment]
@lovetoast @matthewrgourd thank you for the answers. Saving the last 4 digits is a more robust solution. However i would like to know for sure that i can save those 4 digitis including the cardholder name so that i dont break the pci compliance

**Comment by lovetoast** [comment]
@pantelispanayiotou  My understanding is no, this is fine for PCI but @matthewrgourd  will need to confirm.
