### ISSUE TITLE
HOTELIAS HOSPITALITY SERVICES SL

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1884]
Hi @matthewrgourd this merchant asks me about the next:
I have installed in woocommerce your API in the domain www.promoly.com I have made a test of 0.01 and it works well, the only thing is that in the card it comes out as a commerce name (hotelias...) and I ask you if there is any way to configure it so that the domain name comes out as a commerce name

Would be possible to change it?

**Comment by lovetoast** [comment]
@Alvaroalconada My understanding is this name is configured from the trading name in the Viva Wallet account and to change this you can contact viva wallet like chat support.

**Comment by matthewrgourd** [comment]
Hi @lovetoast, that's correct (thanks). @Alvaroalconada will need to speak to someone on our live chat at www.vivawallet.com to change the trading / business name
