### ISSUE TITLE
Enabling simple checkout in demo environment

### ISSUE THREAD

**Issue by MichaelMGit** [VivaPayments/API#1885]
I get the following error trying to use the simple checkout:

["Emv"]=> NULL ["Amount"]=> NULL ["StatusId"]=> string(1) "E" ["RedirectUrl"]=> NULL ["CurrencyCode"]=> NULL ["TransactionId"]=> NULL ["ReferenceNumber"]=> NULL ["AuthorizationId"]=> NULL ["RetrievalReferenceNumber"]=> NULL ["ThreeDSecureStatusId"]=> NULL ["ErrorCode"]=> int(403) ["ErrorText"]=> string(124) "The specified api action is disabled for the merchant 3cd15eea-52aa-4124-89e1-d5edc85629e4, please consult the documentation" ["TimeStamp"]=> string(33) "2020-09-28T10:41:39.5500996+03:00" ["CorrelationId"]=> NULL ["EventId"]=> int(0) ["Success"]=> bool(false)

I assume that I need to be enabled for my demo account, could you please provide it to me? Thank you

**Comment by matthewrgourd** [comment]
Hi @MichaelMGit, that's enabled for you now.
