### ISSUE TITLE
WooCommerce Plugin - Not working with discount codes

### ISSUE THREAD

**Issue by tristanadlington** [VivaPayments/API#1886]
Found another issue with the WooCommerce plugin which is losing me orders. 

The plugin is not recognising discounts from coupons. Please see the different amounts in my Checkout and the amount being charged to my card... 

![image](https://user-images.githubusercontent.com/28437173/94418986-0404e680-017a-11eb-93cc-e75e353e71c7.png)
![image](https://user-images.githubusercontent.com/28437173/94419168-43cbce00-017a-11eb-9b89-3852eb1f84be.png)

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, sorry to hear this. Have you installed the latest version, v1.1, we released yesterday? If not, please either click on 'update' or upload the below, disabling any previous versions.

[viva-wallet-for-woocommerce-v1.1.0.zip](https://github.com/VivaPayments/API/files/5298759/viva-wallet-for-woocommerce-v1.1.0.zip)

Could you remind me of the website address and / or trading name?

**Comment by matthewrgourd** [comment]
We have another version available for download, released today, in case this helps: 

https://developer.vivawallet.com/downloads/viva-wallet-for-woocommerce_v1.1.1.zip

**Comment by tristanadlington** [comment]
It isn't working at all now: www.pothead.coffee

When you click to confirm and pay, the page just refreshes.

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, I've just tested and I see what you mean. I switched on the console in Chrome and there seem to be a couple of JS errors related to the theme. Did you get any errors after saving the [required settings](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#step-2-specify-required-settings)? Please note that I removed the below from your WC-0002 payment source as these are not used in our new plugin. Payment source setup is automatic and you should leave these blank.

NOT REQUIRED
Success URL: index.php?wc-api=wc_vivawallet&vivawallet=success
Failure URL: index.php?wc-api=wc_vivawallet&vivawallet=fail

Can you let me have a copy of the WC status report: **WP Admin > WooCommerce > System status**?

And lastly, can you let me know if the following tab exists? **WP Admin > WooCommerce > Logs**. If so, please select today's date from the drop-down and click on the **View** button. Send me the contents of the log file. Thanks!

**Comment by tristanadlington** [comment]
Vivawallets has been working for us a while, so I did not change any settings when we updated the plugin late last week. 

Just emailed those requested bits to you.

**Comment by matthewrgourd** [comment]
Hi @tristanadlington, thanks for sending through that information. I'll get back to you as soon as possible.

**Comment by tristanadlington** [comment]
Hi Matthew - I have managed to get it working again but installing an older version of the theme - there must have been an issue there.

**Comment by matthewrgourd** [comment]
Aha, great! Thanks for the update...
