### ISSUE TITLE
Enabling simple checkout in demo environment 

### ISSUE THREAD

**Issue by utpalruparel** [VivaPayments/API#1889]
[Emv] => 
    [Amount] => 
    [StatusId] => E
    [RedirectUrl] => 
    [CurrencyCode] => 
    [TransactionId] => 
    [ReferenceNumber] => 
    [AuthorizationId] => 
    [RetrievalReferenceNumber] => 
    [ThreeDSecureStatusId] => 
    [ErrorCode] => 403
    [ErrorText] => The specified api action is disabled for the merchant 6c34ad7a-862c-45da-8209-1a06ba18ce2b, please consult the documentation
    [TimeStamp] => 2020-09-28T12:47:59.2929111+03:00
    [CorrelationId] => 
    [EventId] => 0
    [Success] => 
)

This is for my client in greece. please let me know if any more information needed.

**Comment by matthewrgourd** [comment]
Hi @utpalruparel, enabled as requested.
