### ISSUE TITLE
ΠΡΟΒΛΗΜΑ ΣΤΗΝ ΔΙΑΣΥΝΔΕΣΗ ΤΟΥ ESHOP ΜΕ ΤΟ VIVA WALLET

### ISSUE THREAD

**Issue by crystalpepper** [VivaPayments/API#189]
ΓΕΙΑ ΣΑΣ 
ΕΝΩ ΕΧΩ ΒΑΛΕΙ ΟΛΟΥΣ ΤΟΥΣ ΚΩΔΙΚΟΥΣ ΠΟΥ ΑΠΑΙΤΟΥΝΤΑΙ ΣΤΟ ESHOP ΑΠΟ ΤΟ VIVA WALLET ΟΤΑΝ ΠΑΜΕ ΝΑ ΟΛΟΚΛΗΡΩΣΟΥΜΕ ΜΙΑ ΣΥΝΑΛΛΑΓΗ ΔΕΝ ΜΕ ΠΑΕΙ ΣΤΗΝ ΣΕΛΙΔΑ ΓΙΑ ΝΑ ΚΑΤΑΧΩΡΗΣΟΥΜΕ ΤΑ ΣΤΟΙΧΕΙΑ ΤΗΣ ΚΑΡΤΑΣ ΑΛΛΑ ΛΕΕΙ ΟΤΙ ΥΠΑΡΧΕΙ ΣΦΑΛΜΑ. ΜΠΟΡΕΙΤΕ ΝΑ ΜΕ ΒΟΗΘΗΣΕΤΕ?

**Comment by defilerc** [comment]
Καλησπέρα @crystalpepper ,

Το αρχικό βήμα της διαδικασίας που ακολουθείτε (Redirect), για να ολοκληρώσετε μια παραγγελία μέσω της Viva Payments, είναι η δημιουργία ενός καινούριου Order με την κλήση στην CreateOrder (https://github.com/VivaPayments/API/wiki/CreateOrder).

1. Θα θέλαμε αρχικά να μας στείλετε το merchant id σας.
2. Αν η κλήση στην CreateOrder επιτυγχάνει και έχετε έναν κωδικό πληρωμής, στείλτε μας τον κωδικό πληρωμής για να δούμε τι έχει συμβεί. Εναλλακτικά, αν έχετε κάποιο κωδικό σφάλματος και κάποιο error message, παρακαλώ πολύ στείλτε το μας, για να μπορέσουμε να σας βοηθήσουμε περαιτέρω.

Ευχαριστούμε πολύ,

**Comment by crystalpepper** [comment]
Καλησπέρα σας, 
αυτο που μας βγαζει στο eshop ειναι το εξης:
Ευχαριστούμε - η παραγγελία αναμένει πληρωμή. Θα μεταφερθείτε αυτόματα στη Vivapayments για να πραγματοποιήσετε πληρωμή.
Λάθος στοιχεία εμπόρου ή το API δεν λειτουργεί.

**Comment by defilerc** [comment]
Μπορείτε να μας στείλετε το merchant id σας, καθώς και αν δοκιμάζετε στο demo περιβάλλον ή στο live?

Ευχαριστούμε,

**Comment by crystalpepper** [comment]
δοκιμαζω στο live νομιζω και το merchant id μας ειναι το : 6cd7ce60-2294-404b-b751-d071d83b6e16

**Comment by crystalpepper** [comment]
στις ρυθμισεις του eshop εχει ενεργοποιημενο το test mode. να το απενεργοποιησω αυτο το κουμπι?

**Comment by defilerc** [comment]
Καλησπέρα,

Απ' ότι βλέπουμε, τα στοιχεία που χρησιμοποιείται είναι παραγωγής (live). Επομένως, θα πρέπει να ρυθμίσετε το plugin που χρησιμοποιείται, ώστε να χρησιμοποιεί το live περιβάλλον. Οι ρυθμίσεις ποικίλουν ανάλογα με το plugin που χρησιμοποιείτε.

Ευχαριστούμε πολύ,

**Comment by crystalpepper** [comment]
Καλησπερα,
Χρησιμοποιω το plugin της viva wallet για το wordpress και εχω βαλει ολα τα στοιχεια που μου ζηταει αλλα παλι δεν δουλευει δυστυχως

**Comment by crystalpepper** [comment]
Τελικα το καταφερα και δουλευει αφου απενεργοποιησα το test mode . 
Σας Ευχαριστω πολυ
