### ISSUE TITLE
Payments shown as successful in Woocommerce, but not showing up in VivaWallet

### ISSUE THREAD

**Issue by kapamarou** [VivaPayments/API#1890]
Hey, So I have set up the live credentials and they are accepted. Now Whenever an order is placed, the payment is shown as successful but no money/transaction is being shown in my vivawallet account. I also have select the website that has been created "WC-0002 | Viva Wallet For WC - thatfeeling.gr"

**Comment by kapamarou** [comment]
the website url is https://thatfeeling.gr/

**Comment by matthewrgourd** [comment]
Hi @kapamarou, I'm checking your website but can't find any products to buy?

**Comment by kapamarou** [comment]
Hi i am sending you a product where you can buy https://thatfeeling.gr/empeiria/proion/

**Comment by matthewrgourd** [comment]
Hi @kapamarou, i believe checkout needs to be located here in relation to your domain otherwise our plugin won't work:

`https://thatfeeling.gr/[checkout]`

I don't understand how this URL relates to your live website: https://thatfeeling.gr/empeiria/proion/

**Comment by kapamarou** [comment]
the link above is a product in order to put it in the basket and after to check the checkout page which is https://thatfeeling.gr/checkout/

**Comment by matthewrgourd** [comment]
The link you sent for testing seems to be using a different theme from the one at https://thatfeeling.gr. I believe you need to test with only one theme installed.

**Comment by kapamarou** [comment]
what do you mean ?  its the same theme its "crowdfunding" make an inspect element  . what has to do with the theme ?

**Comment by kapamarou** [comment]
i dont get any issues. I get these 
Viva Wallet: Your LIVE credentials are valid.
Viva Wallet: Your LIVE source code: WC-0002 is verified and you are ready to accept payments.
Viva Wallet: Your domain is verified with Apple Pay and you are ready to accept LIVE payments!

Everything it seems to work fine but it doesnt charge the money to viva account

**Comment by matthewrgourd** [comment]
Hi @kapamarou, we're still looking into this. Can you confirm the plugin version is 1.1?

**Comment by kapamarou** [comment]
yes its the latest version . I ve updated a few days ago .

**Comment by matthewrgourd** [comment]
We think it's because your form is asking for the customer's name in a single field whereas our plugin is looking for first name / surname.

**Comment by matthewrgourd** [comment]
@kapamarou, CORRECTION we can send you a patched version tomorrow so the plugin will work with your form. Best regards.

**Comment by kapamarou** [comment]
i fixed it no need to worry . We were declaring wrong name with the name i changed them to the default name and everything worked fine :D thank you very much for your help

**Comment by matthewrgourd** [comment]
No worries. Glad you got it sorted!
