### ISSUE TITLE
Vivawallet payment is not working

### ISSUE THREAD

**Issue by cvrak** [VivaPayments/API#1894]
Hi @matthewrgourd,

I face the same hard situation as mentioned at #1859 with another customer of mine. I've installed the latest version of the plugin, Joomla and php is up to date, but the same problem occurs.
My customer's data is
Merchant ID *************
API Key L31***********
Code ****

Pls advise
Chris

**Comment by matthewrgourd** [comment]
Hi @cvrak, sorry to hear this, I was under the impression that was fixed. Please let me have the website address where you are testing with the demo card number. I need to see what's going on...

**Comment by cvrak** [comment]
Hi @matthewrgourd,

The URL is www.emeli.gr
My tests are with real credit card, with a test product 0,03 €, at https://bit.ly/3cKDxC2
If you want to make tests, pls let me know in order to activate the vivawallet payment. Now its not available due to this problem
If you need to have access to admin UI, pls send me an email to give you credentials

Thanks

**Comment by matthewrgourd** [comment]
Hi @cvrak what was it that fixed the problem #1859 in the end? Have you tried to replicate the settings from the previous merchant? Test mode should be off I believe... 

If you're still having difficulty, please send me a screenshot of the plugin settings from the e-commerce platform but blur out the Merchant ID and API key.

**Comment by cvrak** [comment]
Hi @matthewrgourd,
The issue #1859 fixed when i switched from demo to real environment.
The settings of the new merchant are the same, tets mode is off
Pls check the attached image for plugins settings

Thanks
![Screenshot_01](https://user-images.githubusercontent.com/62111630/94797560-fa34ea80-03e8-11eb-9810-cece6b1d7cc1.jpg)

**Comment by cvrak** [comment]
Hi @matthewrgourd,
I've checked once more the merchant of #1859 , its working.
I use my Vivawallet card for the tests.
Merchant from #1859: a popup asking for OTP, and then the successful message
Merchant from this issue: no OTP popup, just the failure message
I hope this helps

Thanks

**Comment by matthewrgourd** [comment]
Hi @cvrak I'm not clear on what the problem is in this instance. Please explain. Also, if you could enable Viva Wallet briefly now I will test. Please bear in mind when testing, the minimum amount you can use for the payment is 30 cents. Maybe the problem is you tried with 3 cents (0,03 €)?

**Comment by cvrak** [comment]
Hi @matthewrgourd,
I activated the Vivawallet payment.
I've just checked with 0.30 € test product, same problem.
You can find the test product at https://bit.ly/3cKDxC2

**Comment by matthewrgourd** [comment]
Hi @cvrak, I'm getting issues as well. You can disable again now. Can you remind me which version of VirtueMart it is you're using?

**Comment by cvrak** [comment]
Hi @matthewrgourd,

VM 3.8.4
Joomla 3.9.21
php 7.3.22

**Comment by matthewrgourd** [comment]
Hi @cvrak, I've checked with our plugin developer and he doesn't know of any issues with our plugin. Do you have any other plugins installed that you can temporarily disable or can you try using a different theme?

**Comment by cvrak** [comment]
Hi @matthewrgourd,
Is it possible that something wrong with the version of the plugin I use?
Can you send me the most updated plugin at info@cvart.eu ?
I'll uninstall everything and re-install it again

Thanks

**Comment by matthewrgourd** [comment]
Hi @cvrak, it's a possibility, yes. Can you try the below? Thanks!

[vm3_plugin_vivawallet.zip](https://github.com/VivaPayments/API/files/5313628/vm3_plugin_vivawallet.zip)

**Comment by cvrak** [comment]
Hi @matthewrgourd,

I un-installed and re-installed vm plugin.

1. with my vivawallet card the problem remains
2. with another card  (Piraeus bank) the order is successful

Any ideas? The customer starts to complain for the delay.
Pls advice

Thanks

**Comment by matthewrgourd** [comment]
Hi @cvrak, I'm afraid I don't fully understand. I can see 2 successful test payments for €0.30 made today with a card ending in 5007. These were later cancelled. What's the outstanding issue?

**Comment by cvrak** [comment]
Hi @matthewrgourd,

These payments are made with credit card from Piraeus bank. Everything is ok, then, I cancelled them because is for test purposes. 

The problem occurs when I try to use another card, my Vivawallet card, issued by Vivawallet.

**Comment by matthewrgourd** [comment]
Hi @cvrak please speak to our customer service team to see if there are any limitations with your Viva Wallet card. You can do this via our live chat feature on the [Viva Wallet home page](https://www.vivawallet.com/).
