### ISSUE TITLE
Woocommerce Successful Order but no deposit into our account

### ISSUE THREAD

**Issue by icon32** [VivaPayments/API#1895]
Hello.

We have received our first order with viva wallet payment and although the site get order completed the payment hasn't been transferred to our viva wallet account.

We are using Woocommerce with your official plugin and the website url is https://www.vervejuices.gr/.

**Comment by matthewrgourd** [comment]
Hi @icon32, sorry to hear this. I've tested your website and it looks like the plugin isn't successfully integrated or it isn't the most up-to-date version. Please deactivate and delete any existing Viva plugins and use the below instead.

[viva-wallet-for-woocommerce.zip](https://github.com/VivaPayments/API/files/5326300/viva-wallet-for-woocommerce.zip) 

Installation instructions are here:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce

**Comment by Gfox1972** [comment]
I am also having this issue but I am using your latest version! apple pay works fine and is showing credited to my VW account but if the customers pays via card its not successful and is not showing in my account but states completed in Woocomm

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, we've just released a new version of the plugin which should fix the issue. I suggest you deactivate and delete all current versions of the plugin and replace with this one:
https://developer.vivawallet.com/downloads/viva-wallet-for-woocommerce_v1.1.1.zip

**Comment by matthewrgourd** [comment]
No reply so assume all is ok?

**Comment by Gfox1972** [comment]
Hi matt 

yes the gateway is working fine thank you 

I have noticed that the Apple button is only displayed on my basket page ! and it offers card input on the checkout page only no apple button! 


I wasn’t sure if this a setting within WooCommerce or the fact i use 2 other gateways too   


best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, that's good to know! FYI, our Apple Pay button is meant to be displayed only on the page prior to the checkout page.

**Comment by icon32** [comment]
Actually i am sorry but it seams it is not over since your company have informed us that the payment was canceled that's why it hasn't shown on our account, but that's not true since woocommerce has marked the orders completed which means that your system received the money and then replied to our woocommerce that the transaction is complete.

**Comment by matthewrgourd** [comment]
Hi @icon32, sorry, but that's technically impossible. We can't receive a payment on your behalf without it also appearing in your account. Please can you provide the Viva Wallet correlation ID for the order you have an issue with (go into the order and look under notes). If there is no correlation ID or transaction ID it is an abandoned cart (the customer tried to place the order without paying).

**Comment by icon32** [comment]
Well I do not have this  correlation ID on the order page but that's interesting because in the photo i have posted you below you  will clearly see that at the plugin settings page says that after the successful payment the order status changes to completed.

![22221](https://user-images.githubusercontent.com/43208879/96230713-326b2a00-0fa0-11eb-96bb-38f4b3edcea7.jpg)

**Comment by matthewrgourd** [comment]
@icon32 , that's correct. In the case of a successful payment, you can choose whether to have Processing or Completed as the order status. Additionally, if payment **not** successful, order status in Woo will be set to 'Pending payment' as outlined in the information provided by Woo here: https://docs.woocommerce.com/document/managing-orders/
