### ISSUE TITLE
Error 2055 after refund

### ISSUE THREAD

**Issue by lovetoast** [VivaPayments/API#1896]
Full error text:

PaymentsNonReversibleTransaction: Request to reverse transaction aborted\

Anyone able to shed some light?

**Comment by matthewrgourd** [comment]
Hi @lovetoast, can I have the full request / response logs so I can see the full context? Blur out any confidential info. Thanks!

**Comment by matthewrgourd** [comment]
Hi @lovetoast, what exactly are you attempting to do here? Please provide full details of the request / response. If you're not happy sharing here, please email me at mgourd@vivawallet.com quoting this issue (#1896). Thanks!

**Comment by lovetoast** [comment]
Hi Matt, 

It was an attempted refund, but we don't log the request, so I will do so and let you know if the problem reoccurs, thanks.
