### ISSUE TITLE
Problem succes/fail prestashop 1.7.6

### ISSUE THREAD

**Issue by Taylorsghs** [VivaPayments/API#1897]
Bonjour,
Je rencontre un problème avec les pages de succès et d'échec de paiement. Une fois le paiement validé la redirection vers la page /modules/vivawallet/succes et fail me retourne l'erreur "HTTP ERROR 500"

Comment résoudre cette erreur ?
Merci a vous.

**Comment by matthewrgourd** [comment]
Hi @Taylorsghs, the correct Success / Failure URLs for our plugin for PrestaShop 1.7 are as below:

- Success URL – module/vivawallet/success
- Failure URL – module/vivawallet/fail

Can you try amending the payment source accordingly?

**Comment by Taylorsghs** [comment]
Bonjour

J'ai ajouté correctement les URLs d'accès

![Capture](https://user-images.githubusercontent.com/72338343/95076662-7fced800-0712-11eb-8f58-69a74f6a05e6.PNG)
![Captureerror](https://user-images.githubusercontent.com/72338343/95076665-80676e80-0712-11eb-94c5-82c6124f885b.PNG)

Comme ci-dessus j'ai toujours une error 500

**Comment by matthewrgourd** [comment]
Hi @Taylorsghs, please amend the payment source settings as follows:

**WRONG** ❌
Domain name: https://www.greenhouse-shop.eu
Success URL: modules/vivawallet/success
Failure URL: modules/vivawallet/fail

**CORRECT** ✔️
Domain name: https://greenhouse-shop.eu
Success URL: module/vivawallet/success
Failure URL: module/vivawallet/fail

**Comment by Taylorsghs** [comment]
Ah good, thank u so much !
