### ISSUE TITLE
Shopify - Clients paid 2 times for one order

### ISSUE THREAD

**Issue by Mamakana** [VivaPayments/API#1898]
Hello, 

Recently , 2 clients complain that they has been charged by credit card 2 times for one order. 

After checking our vivawallet account, we received the payment one time but not 2 times as they said. 

The orders are MAMA5606 and MAMA5893.

Kind regards, 

Joffrey

**Comment by matthewrgourd** [comment]
Hi @Mamakana, sorry to hear that. Can you let me have your Viva Wallet Merchant ID so I can check your account? For security reasons, you'll need to send it to my email address: mgourd@vivawallet.com. Please quote this issue (#1898).

**Comment by matthewrgourd** [comment]
Closing as no reply...
