### ISSUE TITLE
Viva Redirect Checkout, return orderId 

### ISSUE THREAD

**Issue by pantelispanayiotou** [VivaPayments/API#1899]
I am trying to implement redirect checkout. The structure of the url is something like: /checkout/2/payment. Number 2 is my orderId. I would like to return to the same page with the same id after successful payment, but i can't find a way to return a variable in success or fail urls provided by viva. What is the correct way to do it so that i will be able to know which orderId was paid? Is there an option to make the return urls dynamic or provide them on my own?

**Comment by matthewrgourd** [comment]
Hi @pantelispanayiotou, all of our plugins (with the exception of [Viva Wallet for WooCommerce](https://woocommerce.com/products/viva-wallet-for-woocommerce/)) have implemented our redirect checkout solution. So probably the best thing to do is check the code of some of them to get an idea of how it's done:

https://github.com/VivaPayments/API/tree/master/Plugins

Hope this helps.

**Comment by pantelispanayiotou** [comment]
Can i have a more specific answer please? I am trying to implement it in Drupal 8 and there is support of only Drupal 7 which is quite different.

**Comment by matthewrgourd** [comment]
@pantelispanayiotou I'll speak to our dev team and get back to you.

**Comment by matthewrgourd** [comment]
Hi @pantelispanayiotou I'm sorry, our dev team has replied that we're unable to help with custom integrations...
