### ISSUE TITLE
Απορίες σχετικά με το ΑΡΙ

### ISSUE THREAD

**Issue by psychiko21** [VivaPayments/API#190]
Πρόκειται να χρησιμοποιήσω το viva payments μέσω του woocommerce plugin για wordpress και θα ήθελα να ρωτήσω 2 πράγματα:

1. Είδα ότι υπάρχει η δυνατότητα πληρωμής με μετρητά είτε σε φυσικό σημείο είτε με αντικαταβολή σε κούριερ. Ωστόσο, δεν βλέπω τις επιλογές αυτές στο διαχειριστικό του vivapayments.com ή στο αρχείο με τον κώδικα που υπάρχει για το wordpress.
Πώς μπορεί να γίνει αυτό;

2. Θα ήταν επιθυμητό να επιλεγόταν η recurring συναλλαγή μέσα από το σάιτ πριν το redirect checkout με το σχετικό checkbox. Διαφορετικά, να επιστρέφεται από το περιβάλλον του viva αν ο χρήστης το επέλεξε ή όχι ώστε να αποθηκεύεται σε τοπική βάση.
Πώς μπορεί να γίνει κάτι τέτοιο;

Ευχαριστώ

**Comment by defilerc** [comment]
Καλησπέρα @psychiko21 ,

- Για να υποστηρίξετε πληρωμή με μετρητά σε φυσικό σημείο ή με αντικαταβολή στο σπίτι του πελάτη, αρκεί να δημιουργήσετε ένα Order (με την [CreateOrder](https://github.com/VivaPayments/API/wiki/CreateOrder)) με αρκετά μεγάλο περιθώριο λήξης (τροποποιώντας την παράμετρο [PaymentTimeout](https://github.com/VivaPayments/API/wiki/Optional-Parameters)), ώστε να προλάβει ο πελάτης να την πληρώσει προτού να λήξει. 

Ο πελάτης το μόνο που χρειάζεται να γνωρίζει είναι το OrderCode, ώστε να μπορέσει να την εξοφλήσει σε κάποιο συνεργαζόμενο κατάστημα.

Για την πληρωμή της παραγγελίας, μπορείτε να ενημερώνεστε χρησιμοποιώντας Webhooks.

Τα [samples](https://github.com/VivaPayments/API) περιλαμβάνουν παραδείγματα για CreateOrder και Webhooks.

- Για recurring συναλλαγές θα πρέπει να δημιουργήσετε ένα Order με την επιλογή AllowRecurring = true. Αυτό έχει σαν αποτέλεσμα κατά το redirect να εμφανιστεί το checkbox στο χρήστη για αποδοχή των recurring χρεώσεων. Αν θέλετε να έχετε γνώση, αν ο πελάτης το αποδέχτηκε ή όχι, μπορείτε να καλέσετε την [GetTransaction](https://github.com/VivaPayments/API/wiki/GetTransactions) παιρνόντας το id της συναλλαγής που δημιουργήθηκε από την πληρωμή του χρήστη και να δείτε το flag `RecurringSupport` στο object `Payment` της απάντησης.

Ευχαριστούμε πολύ,
