### ISSUE TITLE
The specified api action is disabled for the merchant

### ISSUE THREAD

**Issue by veteranslayer** [VivaPayments/API#1901]
Hello, i am getting the same error for the demo account "The specified api action is disabled for the merchant 77e73c25-4ebc-46f2-bd5f-d36ba63c26b7, please consult the documentation". 

Is there something i can do to open this function or is it only available from your side of configuration? 

@VivaWalletSupport

**Comment by matthewrgourd** [comment]
Hi @veteranslayer, I've enabled the API for you.

**Comment by veteranslayer** [comment]
Hello again @matthewrgourd and thanks for enabling the demo account. I finished the tests of the intergration and i would like to switch to live mode. Should i only change the merchant keys or is this something activatable from your side first? The merchant is the  0ed80e95-1861-4b64-9d4f-821eb88c8572

**Comment by matthewrgourd** [comment]
Hi @veteranslayer done!
