### ISSUE TITLE
Viva Wallet X REcharge ?

### ISSUE THREAD

**Issue by Alphabox1** [VivaPayments/API#1902]
Hello,

I'm having a problem because I'm using the Recharge app with my Shopify hosted site.

And here I am wondering how to link Viva Wallet and the REcharge application and even if it is possible?

thank you.

**Comment by matthewrgourd** [comment]
Hi @Alphabox1, unfortunately at this point in time, our Shopify plugin doesn't support recurring payments, subscriptions, or the Recharge app.
