### ISSUE TITLE
Account API - Extrait report - 404 issue

### ISSUE THREAD

**Issue by Ghos1ware** [VivaPayments/API#1903]
Hey, I'm trying to retrieve the wallet extrait report through the account API, as explained in @ https://developer.vivawallet.com/api-reference-guide/account-api/#retrieve-the-extrait-report

But I'm getting a 404 error ?

I'm calling the following URL: https://www.vivapayments.com/walletaccounts/v1/wallets/MYWALLETID/extrait/2020/09

PHP Code:

```
$url = sprintf('https://www.vivapayments.com/walletaccounts/v1/wallets/%s/extrait/%s/%s', $walletId, $year, $month);
$curl = curl_init($url);
curl_setopt($curl, CURLOPT_HTTPGET, true);
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_USERPWD, $merchantId . ":" . $apiKey);
curl_setopt($curl, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

$result = curl_exec($curl);
curl_close($curl);
```

Any idea what's the issue ?

Thank you.

**Comment by matthewrgourd** [comment]
Hi @Ghos1ware, apologies, this functionality isn't available currently. You have to download individual reports manually from the Viva Wallet banking app:

1. Visit app.vivawallet.com and click on the **Sign in** link.
2. If you have more than one account, click on the required account.
2. Click on **Accounts** in the left nav.
3. Click on the **Details** button against the required wallet.
4. Choose the time period you wish to look at and click on the **Search** button.
5. Click on the **Export to Excel** button.
