### ISSUE TITLE
Antonio Navarro Alvarez

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1904]
Hi @matthewrgourd this merchant **** doesn´t know if the next fields are filling up corretly. He is using Woocommerce. Could you check it?
![Issue Antonio Navarro](https://user-images.githubusercontent.com/56823712/95313617-9dc24700-0890-11eb-979b-964aee6de5d4.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, "Instalment logic" field should be blank as I believe this feature is available for Greek merchants only. Source code should be **5436**.
