### ISSUE TITLE
Using Viva Payments in my mobile application

### ISSUE THREAD

**Issue by pantelispanayiotou** [VivaPayments/API#1906]
I am building a react native application and i would like to use viva payments with native checkout with using the marketplace api in mind. Can you tell me what is the correct way to implement it since html and jquery are not supported in react native?

**Comment by matthewrgourd** [comment]
Hi @pantelispanayiotou, that's a very good question. Let me check with our dev team and get back to you.

**Comment by pantelispanayiotou** [comment]
@matthewrgourd any updates?

**Comment by matthewrgourd** [comment]
Hi @pantelispanayiotou unfortunately our Native v2 solution requires JQuery.
