### ISSUE TITLE
Probleme Module

### ISSUE THREAD

**Issue by OBSTELECOM** [VivaPayments/API#1907]
Bonjour,

Je n'arrive pas à installer le Module sur Prestashop 1.7.6 : 

×
error
Aïe... le chargement a échoué.

Que s'est-il passé ?
 Symfony Exception
 Symfony Docs
 Symfony Support
Exception
HTTP 500 Internal Server Error
Vous n'êtes pas autorisé à désactiver le module vivawallet.
Exception
Exception
in src/Core/Addon/Module/ModuleManager.php (line 415)
     * @return bool True for success     */    public function disable($name)    {        if (!$this->adminModuleProvider->isAllowedAccess(__FUNCTION__, $name)) {            throw new Exception(                $this->translator->trans(                    'You are not allowed to disable the module %module%.',                    array(                        '%module%' => $name,                    ),
ModuleManager->disable('vivawallet')
in src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php (line 614)
                    ]                ),            ];        } catch (Exception $e) {            if (isset($moduleName)) {                $moduleManager->disable($moduleName);            }            $installationResponse = [                'status' => false,                'msg' => $e->getMessage(),
ModuleController->importModuleAction(object(Request))
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 151)
        $this->dispatcher->dispatch(KernelEvents::CONTROLLER_ARGUMENTS, $event);        $controller = $event->getController();        $arguments = $event->getArguments();        // call controller        $response = \call_user_func_array($controller, $arguments);        // view        if (!$response instanceof Response) {            $event = new GetResponseForControllerResultEvent($this, $request, $type, $response);            $this->dispatcher->dispatch(KernelEvents::VIEW, $event);
HttpKernel->handleRaw(object(Request), 1)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php (line 68)
    public function handle(Request $request, $type = HttpKernelInterface::MASTER_REQUEST, $catch = true)    {        $request->headers->set('X-Php-Ob-Level', ob_get_level());        try {            return $this->handleRaw($request, $type);        } catch (\Exception $e) {            if ($e instanceof RequestExceptionInterface) {                $e = new BadRequestHttpException($e->getMessage(), $e);            }            if (false === $catch) {
HttpKernel->handle(object(Request), 1, false)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php (line 200)
        $this->boot();        ++$this->requestStackSize;        $this->resetServices = true;        try {            return $this->getHttpKernel()->handle($request, $type, $catch);        } finally {            --$this->requestStackSize;        }    }
Kernel->handle(object(Request), 1, false)
in admin903aifift/index.php (line 86)
$request = Request::createFromGlobals();Request::setTrustedProxies([], Request::HEADER_X_FORWARDED_ALL);try {    require_once __DIR__.'/../autoload.php';    $response = $kernel->handle($request, HttpKernelInterface::MASTER_REQUEST, false);    $response->send();    $kernel->terminate($request, $response);} catch (NotFoundHttpException $exception) {    define('ADMIN_LEGACY_CONTEXT', true);    // correct Apache charset (except if it's too late)
Logs 2
Level	Channel	Message
DEBUG
16:18:09
doctrine	SELECT name FROM ps_module WHERE active = 1
INFO
16:18:09
request	Matched route "admin_module_import".
DEBUG
16:18:09
security	Read existing security token from the session.
DEBUG
16:18:09
security	User was reloaded from a user provider.
WARNING
16:18:09
translation	Translation not found.
INFO
16:18:09
php	User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector".
CRITICAL
16:18:09
php	Uncaught Exception: Vous n'êtes pas autorisé à désactiver le module vivawallet.
CRITICAL
16:18:09
request	Uncaught PHP Exception Exception: "Vous n'êtes pas autorisé à désactiver le module vivawallet." at /var/www/your-cbd.fr/htdocs/src/Core/Addon/Module/ModuleManager.php line 415
Stack Trace
Exception
Exception:
Vous n'êtes pas autorisé à désactiver le module vivawallet.

  at src/Core/Addon/Module/ModuleManager.php:415
  at PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->disable('vivawallet')
     (src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php:614)
  at PrestaShopBundle\Controller\Admin\Improve\ModuleController->importModuleAction(object(Request))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, false)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, false)
     (admin903aifift/index.php:86)

**Comment by matthewrgourd** [comment]
Sorry to hear this. In order for me to investigate further what your issue might be, please send through the following screenshots:

- PrestaShop 1.7.6 payment module settings (mask your Merchant ID and API Key).
- Viva Wallet <a href="https://developer.vivawallet.com/images/redirect-checkout-payment-source.png?classes=border" target="_blank">payment source settings</a> (include your browser's URL bar in the screenshot).
- Viva Wallet  **Sales > Online Payments > Websites / Apps** page (include your browser's URL bar in the screenshot).
- <a href="https://developer.vivawallet.com/images/api-access-page.png?classes=border" target="_blank">API Access</a> page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Closing as no reply
