### ISSUE TITLE
Successful payment / redirection 

### ISSUE THREAD

**Issue by cbdeee** [VivaPayments/API#1910]
Hello,

I have a problem with the redirection page after a successful/failure payment.
It does redirect to a page but there's nothing on the page, juste blank and its write "-1" at the top left of the page.

Success url : index.php?wc-api=wc_vivawallet&vivawallet=success
Failure url : index.php?vivawallet_callback=true&fail=true

Had this one at first for the successful one and change after seeing some post here : index.php?vivawallet_callback=true&success=true

Which one is the right one ? WHy is it still not working ?

The website is www.cbde.fr (coming soon page actually, will be online on saturday)
It's vivawallet plugin for woocommerce

Thanks,

Justin

**Comment by matthewrgourd** [comment]
Hi @cbdeee, in your payment source, please change the current setting for **Domain Name** from `cbde.fr` to `www.cbde.fr`. By the way, it looks like you're using the previous redirect version of our plugin for WooCommerce. We now have a native extension. Please feel free to install that one instead if you want an improved user experience for your customers. Instructions and download link: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/. If you choose this option, payment source is created automatically so you don't have to worry about what goes in the settings.

**Comment by cbdeee** [comment]
Hello,

I just change it and it's still not working.
So with this version it will work ? Or still have to manage the successful/failure URL etc ?

Thanks for your answer,

Justin
________________________________
De : matthewrgourd <notifications@github.com>
Envoyé : mardi 13 octobre 2020 07:57
À : VivaPayments/API <API@noreply.github.com>
Cc : cbdeee <dumas.justin@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [VivaPayments/API] Successful payment / redirection (#1910)


Hi @cbdeee<https://github.com/cbdeee>, in your payment source, please change the current setting for Domain Name from cbde.fr to www.cbde.fr. By the way, it looks like you're using the previous redirect version of our plugin for WooCommerce. We now have a native extension. Please feel free to install that one instead if you want an improved user experience for your customers. Instructions and download link: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/. If you choose this option, payment source is created automatically so you don't have to worry about what goes in the settings.

**Comment by cbdeee** [comment]
And do I need to desinstall all the plugin or I can update it like it's says on the page ? But is it gonna change the success/failure url etc if I just update it ?

Thanks a lot !

Justin
________________________________
De : Justin Dumas <dumas.justin@hotmail.com>
Envoyé : mardi 13 octobre 2020 08:01
À : VivaPayments/API <reply@reply.github.com>
Objet : RE: [VivaPayments/API] Successful payment / redirection (#1910)

Hello,

I just change it and it's still not working.
So with this version it will work ? Or still have to manage the successful/failure URL etc ?

Thanks for your answer,

Justin
________________________________
De : matthewrgourd <notifications@github.com>
Envoyé : mardi 13 octobre 2020 07:57
À : VivaPayments/API <API@noreply.github.com>
Cc : cbdeee <dumas.justin@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [VivaPayments/API] Successful payment / redirection (#1910)


Hi @cbdeee<https://github.com/cbdeee>, in your payment source, please change the current setting for Domain Name from cbde.fr to www.cbde.fr. By the way, it looks like you're using the previous redirect version of our plugin for WooCommerce. We now have a native extension. Please feel free to install that one instead if you want an improved user experience for your customers. Instructions and download link: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/. If you choose this option, payment source is created automatically so you don't have to worry about what goes in the settings.

**Comment by matthewrgourd** [comment]
Hi @cbdeee, can you first let me know the version number shown against the current Viva Wallet plugin on your **Installed Plugins** page.

**Comment by cbdeee** [comment]
Yes, it's the 3.6.2 version!
________________________________
De : matthewrgourd <notifications@github.com>
Envoyé : mardi 13 octobre 2020 08:11
À : VivaPayments/API <API@noreply.github.com>
Cc : cbdeee <dumas.justin@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [VivaPayments/API] Successful payment / redirection (#1910)


Hi @cbdeee<https://github.com/cbdeee>, can you first let me know the version number shown against the current Viva Wallet plugin on your Installed Plugins page.

**Comment by matthewrgourd** [comment]
Hi @cbdeee, this is a much older version which offered a redirect rather than a native checkout experience. Please deactivate, delete, and install the latest plugin: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ Thanks!

**Comment by cbdeee** [comment]
This is amazing,

Thanks a lot man! Everything's working well, it's perfect !!
Thanks you so much!


Justin
________________________________
De : matthewrgourd <notifications@github.com>
Envoyé : mardi 13 octobre 2020 08:38
À : VivaPayments/API <API@noreply.github.com>
Cc : cbdeee <dumas.justin@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [VivaPayments/API] Successful payment / redirection (#1910)


Hi @cbdeee<https://github.com/cbdeee>, this is a much older version which offered a redirect rather than a native checkout experience. Please deactivate, delete, and install the latest plugin: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ Thanks!

**Comment by matthewrgourd** [comment]
@cbdeee no problem 👍
