### ISSUE TITLE
The specified api action is disabled

### ISSUE THREAD

**Issue by FuseMetrix** [VivaPayments/API#1912]
I'm getting the following error on a Simple Checkout account for our client, when trying to call the api/transactions url for a completed payment please can you activate it so I can complete the system.

"The specified api action is disabled for the merchant *****, please consult the documentation"

**Comment by matthewrgourd** [comment]
Hi @FuseMetrix, I've enabled our Simple Checkout API for the merchant.

**Comment by VirtualColossus** [comment]
Thank you

**Comment by FuseMetrix** [comment]
Thank you
