### ISSUE TITLE
Demo and Live enviroment

### ISSUE THREAD

**Issue by AmazonesTV** [VivaPayments/API#1913]
Hello.

Please enable demo/live environment for simple checkout in live and DEMO environment

Merchant ID is 56d463aa-18d1-43d6-adb4-b0e5663a513c (for demo)
and **** (for Live)

thanks,

AmazonesTV

**Comment by AmazonesTV** [comment]
We have relative previous experience fromThetis TV, which has been developeld in two separate steps, so Demo and Production in Amazones TV will be developed almost immediately. 
We really appreciate your direct response, in order to publish our site as soon as possible

T.

**Comment by matthewrgourd** [comment]
Hi @AmazonesTV, this is done for you now.
