### ISSUE TITLE
Getting error in recurring payment: Negative or zero amount, order xxx, parent yyy

### ISSUE THREAD

**Issue by yairpe** [VivaPayments/API#1915]
Hi, in doing the integration, I'm facing a problem with the recurring payment in the demo environment.

I'm calling 
`https://demo.vivapayments.com/api/transactions/<transaction-id>`

The amount is 2900
I'm also using the optional actionUser, customerTrns, installments (=1) and merchantTrns
The transaction id is correct and belong to a valid successful transaction with original amount of 30 GBP (3000 pennies)

Yet I'm getting StatusId of 'E' and ErrorText of
`'ErrorText' => 'Negative or zero amount, order 7723336944627581, parent 86d943d0-29bb-47e0-a666-332e8b35501b'`

Any idea how to solve it?

**Comment by matthewrgourd** [comment]
Hi @yairpe, are you including the `amount` parameter? The error message you mentioned normally occurs if this has been left out, e.g.
**WITHOUT AMOUNT**
**Request**
```
curl -L -X POST 'https://demo.vivapayments.com/api/transactions/91bc8b8e-b2ce-413e-a22a-a47af695da46' \
-H 'Authorization: Basic ZTc1ZmZmNDMtNWM5Zi00YWE2LTljZjEtODZhZmRkZWE4MjA0OmV0UzdrMw==' \
-H 'Content-Type: application/json' \
-H 'Cookie: __RequestVerificationToken_L3dlYg2=gkThAllpUCIO18o0NFzEvG1jH563MpAranj7EsWYeK7KV6hMuLlxuR5CMNAGXFmAlG001fd6MDZaDbW13LpcXgtpVXyazlqYGyZchcqfuk81' \
--data-raw '{
  "actionUser": "name",
  "CustomerTrns": "Description that the customer sees",
  "maxInstallments": 1,
  "AllowRecurring": true,
  "MerchantTrns": "123"
}'
```
**Response**
```
{"Emv":null,"Amount":null,"StatusId":"E","RedirectUrl":null,"CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":400,"ErrorText":"Negative or zero amount, order 2328965920848997, parent 91bc8b8e-b2ce-413e-a22a-a47af695da46","TimeStamp":"2020-10-14T16:32:16.7104299+03:00","CorrelationId":null,"EventId":0,"Success":false}
```
**WITH AMOUNT:**
**Request**
```
curl -L -X POST 'https://demo.vivapayments.com/api/transactions/91bc8b8e-b2ce-413e-a22a-a47af695da46' \
-H 'Authorization: Basic ZTc1ZmZmNDMtNWM5Zi00YWE2LTljZjEtODZhZmRkZWE4MjA0OmV0UzdrMw==' \
-H 'Content-Type: application/json' \
-H 'Cookie: __RequestVerificationToken_L3dlYg2=gkThAllpUCIO18o0NFzEvG1jH563MpAranj7EsWYeK7KV6hMuLlxuR5CMNAGXFmAlG001fd6MDZaDbW13LpcXgtpVXyazlqYGyZchcqfuk81' \
--data-raw '{
  "actionUser": "name",
  "CustomerTrns": "Description that the customer sees",
  "maxInstallments": 1,
  "AllowRecurring": true,
  "MerchantTrns": "123",
  "Amount": 2900
}'
```
**Response**
```
{"Emv":null,"Amount":29.00,"StatusId":"F","RedirectUrl":null,"CurrencyCode":"978","TransactionId":"04309d84-779a-4370-8498-b593d2ed87c5","ReferenceNumber":793137,"AuthorizationId":"793137","RetrievalReferenceNumber":"028813793137","ThreeDSecureStatusId":2,"ErrorCode":0,"ErrorText":null,"TimeStamp":"2020-10-14T16:34:09.7577343+03:00","CorrelationId":null,"EventId":0,"Success":true}

**Comment by yairpe** [comment]
Yes. Here are the POST parameters

`{"actionUser":"301248","amount":2900,"customerTrns":"Topishare","installments":1,"merchantTrns":"30-days-29-GBP-viva-301248"}`

**Comment by yairpe** [comment]
I also noticed that you used:
`
"maxInstallments" => 1,
"AllowRecurring"  => true,`

where the [documentaion ](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/post) has only `installments` (not maxInstallments) and does not have  `AllowRecurring`

**Comment by matthewrgourd** [comment]
Hi @yairpe, I can't seem to recreate the error. Would you be able to send through each step you took in detail? My steps are:

STEP 1: Create payment order: 

**Request**

POST `https://demo.vivapayments.com/api/orders`

Body parameters
```
{
  "actionUser": "name",
  "Tags": [
    "sample string 1",
    "sample string 2",
    "sample string 3"
  ],
  "Email": "customer@example.com",
  "Phone": "07967813180",
  "FullName": "Customer Name",
  "PaymentTimeOut": 86400,
  "RequestLang": "en-GB",
  "Source": "Default",
  "maxInstallments": 1,
  "AllowRecurring": true,
  "Amount": 100,
  "MerchantTrns": "123",
  "CustomerTrns": "Description that the customer sees"
}
```
**Response**
```
{
    "OrderCode": 6929129404006375,
    "ErrorCode": 0,
    "ErrorText": null,
    "TimeStamp": "2020-10-14T16:54:54.0400637+03:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": true
}
```
STEP 2: Open payment page in browser https://demo.vivapayments.com/web/checkout?ref=6929129404006375. Complete payment details with test card number 4111 1111 1111 1111 and click on **Charge** button.

STEP 3: Click on Success at the 3DS prompt and grab transaction ID from URL in browser address bar.

STEP 4: Create child transaction:

**Request**

POST `https://demo.vivapayments.com/api/transactions/09e5f9ee-31c3-4f07-a4f3-28dffbf30c64`

Body parameters
```
{"actionUser":"301248",
"amount":2900,
"customerTrns":"Topishare",
"installments": 0,
"merchantTrns":"30-days-29-GBP-viva-301248"}
```
**Response**
```
{
    "Emv": null,
    "Amount": 29.00,
    "StatusId": "F",
    "RedirectUrl": null,
    "CurrencyCode": "978",
    "TransactionId": "39ff5599-ca2a-4ef5-8819-ffc86740fe70",
    "ReferenceNumber": 793157,
    "AuthorizationId": "793157",
    "RetrievalReferenceNumber": "028814793157",
    "ThreeDSecureStatusId": 2,
    "ErrorCode": 0,
    "ErrorText": null,
    "TimeStamp": "2020-10-14T17:08:11.1881564+03:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": true
}
```

**Comment by yairpe** [comment]
As I've noted, I'm using the nativecheckout v2 to create the initial transaction.

**Step 1:** 
As described in the [docs](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/)
User fills in the HTML form (name, 4111111111111111, 11/22, 111), click 'Confirm Payment' in the 3D iframe and we get the charge token.

**Step 2:**
on the server: 
doing a POST to `https://demo-api.vivapayments.com/nativecheckout/v2/transactions` with 

`Array (
    [amount] => 100
    [tipAmount] => 0
    [chargeToken] => ctok_zdISxmYkAJn4R_ZjeoVfDuFjLac
    [installments] => 1
    [preauth] => 
    [AllowRecurring] => 1
    [merchantTrns] => 301248.SP1D.1.2020-10-14-15-29-10
    [customerTrns] => SP1D
    [currencyCode] => 826
    [customer] => Array  (
            [email] => mymailhidden@gmail.com
            [phone] => 7440965007
            [fullname] => John Smith
            [requestLang] => en
            [countryCode] => GB
        )
)`

We get a `{"transactionId":"06898b60-ca78-4276-ba7d-f551274becf0"}`

**Step 3:**
On the server:
doing a POST to `https://demo.vivapayments.com/api/transactions/` with 
`Array (
    [actionUser] => 301248
    [amount] => 2900
    [customerTrns] => Topishare
    [maxInstallments] => 1
    [AllowRecurring] => 1
    [merchantTrns] => 30-days-29-GBP-viva-301248
)`

and getting the error:
`'ErrorText' => 'Negative or zero amount, order 9529372059549902, parent 06898b60-ca78-4276-ba7d-f551274becf0',`

**Comment by matthewrgourd** [comment]
Hi @yairpe, thanks for sending through that detailed info. We're still looking into this for you.

**Comment by matthewrgourd** [comment]
Hi @yairpe, I believe the problem may be that you're mixing two APIs. If you want to use the Native Checkout v2 approach, please follow our [Card Tokenization](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/) guide.

**Comment by yairpe** [comment]
Thank you @matthewrgourd 

I will certainly try using card tokenization.

Please look as the documentation is misleading in the [Card Tokenization guide](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/). I read it and went on to implement recurring using the link provided there but as you already saw, it does not work for Native Checkout v2.

`"Before choosing this option you might want to look also at how to create a recurring transaction. This takes less effort to implement than card tokenization."`

**Comment by yairpe** [comment]
So basically you're saying that for recurring payment:

I cannot create a new charge using the original transaction id like POST /api/transactions/<original-transaction-id>
[documented here](https://developer.vivawallet.com/api-reference-guide/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/post)

but I have to use the card token from the original payment and get a charge token 
like /acquiring/v1/cards/chargetokens?token={cardtoken}
and make the charge
like /nativecheckout/v2/transactions
[documented here step 4](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/)

I've tried it and it works. Thanks.

You may think of updating your docs to state that you must use Card Tokenization API for recurring payments if you used Native Checkout v2 for the original payment.

**Comment by matthewrgourd** [comment]
Hi @yairpe, yes, that's right. Thanks for the feedback, I will remove that bit from the documentation as it is a bit misleading!

**Comment by matthewrgourd** [comment]
Hi @yairpe, please close the issue if you feel it has been solved. Thanks!
