### ISSUE TITLE
Wowcomponents

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1916]
Hi Matt! this merchant which their website is https://learnafo.com/ has the next issue (is using woocommerce):

He receives an error when trying to accept recurring payments.
When he puts a recurring product in cart, he’s told that the payment method does not support recurring transactions.  
As he mentioned he’s configured the plugin with live keys, and activated the recurring option in his viva wallet backend.
When a non-recurring product is added to the cart, the transaction is processed successfully. 
The source is active and he has completed the integration with his website.
Source code WC-0002.
<img width="832" alt="Screenshot 2020-10-14 at 13 25 33" src="https://user-images.githubusercontent.com/56823712/96008589-020c7a00-0e40-11eb-8632-8a66fc34df31.png">
<img width="1336" alt="Screenshot 2020-10-14 at 13 42 13" src="https://user-images.githubusercontent.com/56823712/96008638-0f296900-0e40-11eb-859e-48a1272914b6.png">

<img width="1154" alt="Screenshot 2020-10-14 at 13 21 54" src="https://user-images.githubusercontent.com/56823712/96008876-4dbf2380-0e40-11eb-9108-05b3d7cb115c.png">

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, this means that the payment card does not support recurring payments. He needs to contact his issuer or use a different card.

**Comment by Alvaroalconada** [comment]
merchant just contact me for telling me that they have set up your plugin for woo-commerce and marked the "subscription" setting in your API settings. But it seems like we cannot accept subscriptions. Other transactions seem to be able to go through.
