### ISSUE TITLE
Native Checkout v2 Error 404 during Step 5: Make the actual charge

### ISSUE THREAD

**Issue by VaggelisAvdelas** [VivaPayments/API#1917]
Hello,

We are following directions from this documentation [https://developer.vivawallet.com/online-checkouts/native-checkout-v2/](url)

Although a lot of payments have been fulfilled without a problem, there are others where we're getting a 404 error during step 5 and we're trying to understand what's been going on with those.

From the logs I can see the following error:
Client error: `POST https://api.vivapayments.com/nativecheckout/v2/transactions` resulted in a `404 Not Found` response:
{"status":404,"message":"Could not get 'token:charge:ctok_xxxxxxxxxxxxxx', key does not exist"

Our js setup code looks like this: 

```
VivaPayments.cards.setup({
            authToken: <the access token>,
            baseURL: https://api.vivapayments.com,
            cardHolderAuthOptions: {
              cardHolderAuthPlaceholderId: 'threed-secure-popup',
              cardHolderAuthInitiated: function() {
                $('body').removeClass('viva-loading');
                $('.threed-secure-popup-wrapper').css('display', 'flex');
              },
              cardHolderAuthFinished: function() {
                $('.threed-secure-popup-wrapper').css('display', 'none');
                $('body').addClass('viva-loading');
              }
            }
          });
```

and our js requestToken code looks like this:

```
VivaPayments.cards.requestToken({
  amount: amount.val(),
}).done(function (responseData) {
      token = responseData.chargeToken;
       chargetoken.val(responseData.chargeToken);
       $('#submit').submit();
}).fail(function(responseData) {
       error.html('Invalid credit card. Please check your card details or use another card.')
});

```
Afterwards we're getting this chargetoken and using it on the backend with PHP to make a call to this url https://api.vivapayments.com/nativecheckout/v2/transactions along with the other data. Data looks like this:

```
$data = [
      'chargeToken' => <the charge token>,
      'currencyCode' => 978,
      'amount' => <the amount>,
      'isPreAuth' => TRUE,
      'preauth' => TRUE,
      'PaymentMethodId' => 1,
      'merchantTrns' => 'Merchant transaction reference'
      'customer' => [
        'email' => <customer email>
      ]
];

```
Are we missing something? How come some of the payments are fulfilled correctly while others get rejected?

**Comment by matthewrgourd** [comment]
Hi @VaggelisAvdelas, the error you're getting suggests a payment has already been made using the charge token. A new one needs to be generated for each subsequent payment. However, if you need to store an individual card for multiple charges, see [Generate card token using the charge token (optional)](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api/#step-2-generate-card-token-using-the-charge-token-optional) on our [Card Tokenization](https://developer.vivawallet.com/api-reference-guide/card-tokenization-api) page. Hope this helps!

**Comment by VaggelisAvdelas** [comment]
Thanks for clarifying what that error means. 
But it doesn't make sense to me that a payment has already been made with the charge token, as the token is generated on submitting the 3DS form. 
I've never stumbled on this error on the demo environment, that's what makes it hard to debug this.

Do you have any suggestions on why this might be happening or how we can fix it? Card tokenization isn't really an option right now, but if you believe it might solve the problem I will discuss it further.

**Comment by matthewrgourd** [comment]
Hi @VaggelisAvdelas, ah, I see, so when you receive that error, you've not yet used the charge token for a payment. I was testing on demo and it's fine. Let me test on live to see if I can recreate the error.

**Comment by matthewrgourd** [comment]
```
$data = [
      'chargeToken' => <the charge token>,
      'currencyCode' => 978,
      'amount' => <the amount>,
      'isPreAuth' => TRUE,
      'preauth' => TRUE,
      'PaymentMethodId' => 1,
      'merchantTrns' => 'Merchant transaction reference'
      'customer' => [
        'email' => <customer email>
      ]
];
```

In the above, I notice that you have 'isPreAuth' => TRUE. This is an incorrect parameter and looks like it's been taken from our Payment API which is different from our Native Checkout v2. Please remove and use only  'preauth' => TRUE.

Looking at your question in a bit more detail, are you saying the call mostly works but you're getting inconsistent performance? If so, I'll need to check with our core dev team to see if anyone else has been experiencing issues.

**Comment by VaggelisAvdelas** [comment]
My bad, I will have to remove that parameter, thanks for that.

Yes, that's exactly the case. We're getting some payments registered correctly, but others have trouble progressing because of this error.

**Comment by VaggelisAvdelas** [comment]
Hey, sorry for re-opening this, but I didn't get any response regarding the issue.

Did you check with the core dev team if anyone else is experiencing something like this?

**Comment by matthewrgourd** [comment]
Hi @VaggelisAvdelas there's no problem with our API, so it's probably your custom php code which I can't advise on I'm afraid.
