### ISSUE TITLE
προβλημα

### ISSUE THREAD

**Issue by tsilis** [VivaPayments/API#192]
Ευχαριστούμε - η παραγγελία αναμένει πληρωμή. Θα μεταφερθείτε αυτόματα στη Vivapayments για να πραγματοποιήσετε πληρωμή.
Λάθος στοιχεία εμπόρου ή το API δεν λειτουργεί.

**Comment by defilerc** [comment]
Καλησπέρα @tsilis ,

Μπορείτε να μας στείλετε το merchant id σας, καθώς και το περιβάλλον στο οποίο πραγματοποιείτε δοκιμές (demo ή live), για να δούμε τι έχει συμβεί;

Ευχαριστούμε,

**Comment by tsilis** [comment]
Wordpress με woocommerce, merchant id: 28eef60b-cfed-4352-b327-87634e8ab8ab, VivaPayments API key: oI!E;Qjkh, VivaPayments CodeId: 4073
thanks

**Comment by tsilis** [comment]
παρακαλω ενημερωστε με

**Comment by defilerc** [comment]
Καλημέρα @tsilis ,

Τα στοιχεία που χρησιμοποιείται είναι σωστά και αφορούν το παραγωγικό (live) περιβάλλον. Παρακαλώ πολύ βεβαιωθείτε ότι χρησιμοποιείτε το σωστό URL για να συνδεθείτε: `https://www.vivapayments.com`. Επίσης, για λόγους ασφαλείας δεν πρέπει **ποτέ** να ποστάρετε το API Key σας και καλό θα ήταν να το κάνετε remove από το προηγούμενο post σας.

Ευχαριστούμε πολύ,

**Comment by tsilis** [comment]
ευχαριστω το εσβησα, μετα την ολοκληρωση της παραγγελειας εχω αυτο το μυνημα, Ευχαριστούμε - η παραγγελία αναμένει πληρωμή. Θα μεταφερθείτε αυτόματα στη Vivapayments για να πραγματοποιήσετε πληρωμή.
αλλα δεν με παει στην σελιδα του viva, δεν βλεπω καπου στα settings τετοια εντολη

**Comment by defilerc** [comment]
Καλησπέρα @tsilis ,

Θα πρέπει να βεβαιωθείτε ότι χρησιμοποιείτε το σωστό περιβάλλον για να συνδεθείτε (live). 

Απ' ότι καταλαβαίνω, χρησιμοποιείτε κάποιο εξωτερικό plugin, καθώς αυτό το μήνυμα που παίρνετε δεν προέρχεται από το Viva Payments API.

**Comment by tsilis** [comment]
είναι σίγουρο ότι δεν έχω κάποιο εξωτερικό plugin

**Comment by defilerc** [comment]
Καλησπέρα @tsilis ,

Για να μπορέσουμε να σας βοηθήσουμε, θα θέλαμε να μας πείτε:

1. Αν χρησιμοποιείτε το live environment ή το demo.
2. Ποιά μέθοδο integration χρησιμοποιείτε (π.χ. Native Checkout, Redirect Checkout). Για τις διάφορες μεθόδους, παρακαλώ δείτε στη σελίδα https://github.com/VivaPayments/API/wiki , στην παράγραφο "Website Checkout".
3. Τις κλήσεις που κάνετε στο API, καθώς και τις παραμέτρους που χρησιμοποιείτε

Με εκτίμηση,

**Comment by tsilis** [comment]
χρησιμοποιω το live environment τωρα, Redirect Checkout,

**Comment by tsilis** [comment]
σας έστειλα screenshot χωρίς να μου απαντήσετε

**Comment by tsilis** [comment]
πρέπει παρακαλώ  να κλείσει αυτό το θέμα

**Comment by defilerc** [comment]
Καλησπέρα @tsilis ,

Δεν έχει γίνει κάποιο file attach στο συγκεκριμένο issue. Το redirect URL καθορίζεται από την πηγή που χρησιμοποιείται για να γίνει το transaction. Θα πρέπει να βεβαιωθείτε ότι η πηγή έχει οριστεί σωστά από το προφίλ σας (success/fail URLs) και ότι κατά τη δημιουργία του Order, χρησιμοποιείται το σωστό SourceCode.

Για να μπορέσουμε να σας βοηθήσουμε περαιτέρω και να επιβεβαιώσουμε ότι τα βήματα που έχετε κάνει είναι σωστά, θα πρέπει να μας στείλετε αναλυτικά τα requests που κάνετε για τη δημιουργία του Order, για την πληρωμή του, καθώς και τυχόν μηνύματα λάθους που παίρνετε από το API.

Με εκτίμηση,

**Comment by tsilis** [comment]
http://prntscr.com/deeo4q
http://prntscr.com/deeq9a

**Comment by defilerc** [comment]
Καλησπέρα @tsilis ,

Απ' ότι φαίνεται στο 1ο screenshot, η πηγή πληρωμών με κωδικό 4073 αναμένει έγκριση. Αυτό γίνεται κάθε φορά που αλλάζετε το domain της πηγής, για λόγους ασφαλείας.

Όταν η πηγή πληρωμών εγκριθεί, θα μπορείτε να προχωρήσετε σε συναλλαγές με τη συγκεκριμένη πηγή.

Με εκτίμηση,

**Comment by tsilis** [comment]
Την Πέμπτη μίλησα τηλεφωνικός με την viva και με διαβεβαίωσαν ότι δεν υπάρχει τίποτα για έγκριση, όλα είναι εγκεκριμένα και η ιστοσελίδα βγάζει ακόμα το ίδιο πρόβλημα, παρακαλώ ενημερώστε με να ξέρω τι να κάνω, αν είναι να προχωρήσω με κάποια τράπεζα και να μην έχω τέτοια προβλήματα που διαρκούν περίπου 1 μήνα για την λύση τους. Με εκτίμηση

**Comment by tsilis** [comment]
Ευχαριστούμε - η παραγγελία αναμένει πληρωμή. Θα μεταφερθείτε αυτόματα στη Vivapayments για να πραγματοποιήσετε πληρωμή.

**Comment by tsilis** [comment]
και δεν γίνετε τιποτα

**Comment by defilerc** [comment]
Καλησπέρα @tsilis ,

Μετά την επιτυχή δημιουγία παραγγελίας, θα πρέπει να κάνετε redirect το χρήστη στη σελίδα της VivaPayments, έτσι όπως περιγράφεται στη σελίδα: https://github.com/VivaPayments/API/wiki/Redirect-Checkout

Η διαδικασία είναι η εξής:

- Δημιουργείτε έναν κωδικό παραγγελίας
- Κάνετε redirect το χρήστη στη σελίδα https://vivapayments.com/web/checkout?ref={OrderCode} , όπου `OrderCode` ο κωδικός παραγγελίας που λάβατε από το πρώτο βήμα.

1. Χρησιμοποείται κάποιο εξωτερικό plugin?
1. Παρακαλώ πολύ, δώστε μας και το merchant id, για να ερευνήσουμε αν υπάρχει κάποιο άλλο πρόβλημα.

Με εκτίμηση,

**Comment by tsilis** [comment]
στην επεξεργασια πηγης εβαλα, /web/checkout?ref={OrderCode} δεν εγινε τιποτα, μετα wc-api/WC_em_Vivapayments_Gateway ουτε παλι,

**Comment by tsilis** [comment]
Ευχαριστούμε - η παραγγελία αναμένει πληρωμή. Θα μεταφερθείτε αυτόματα στη Vivapayments για να πραγματοποιήσετε πληρωμή.

**Comment by tsilis** [comment]
στατικα

**Comment by defilerc** [comment]
Καλημέρα @tsilis ,

Φαίνεται να υπάρχει κάποιο πρόβλημα με το εξωτερικό plugin που χρησιμοποιείται. Θα πρέπει να απευθυνθείτε στο δημιουργό του για περαιτέρω καθοδήγηση.

Με εκτίμηση,

**Comment by markosweb** [comment]
Καλησπέρα σας,
Αντιμετωπίζω και εγώ το ίδιο πρόβλημα (Λάθος στοιχεία εμπόρου ή το API δεν λειτουργεί.)
Στο demo περιβάλλον όμως, λειτουργούν όλα άψογα,
Έχει αλλάξει κάτι στο τρόπο διασύνδεσης ώστε να κάνω κάποια αλλαγή στο plugin?
Ευχαριστώ.

**Comment by kostGX** [comment]
Closing as issue is very old.
