### ISSUE TITLE
VivaPayments v2 error 502

### ISSUE THREAD

**Issue by Alexookah** [VivaPayments/API#1920]
We have 502 error in the following merchant: 

e6443905-30a6-4428-a320-64f232116ad1

Is there something wrong with this merchant account?

`
{ Error: Request failed with status code 502
   { url:
      'https://api.vivapayments.com/nativecheckout/v2/transactions',
     method: 'post',
     data:
      '{"amount":416,"preauth":false,"sourceCode":"Default","chargeToken":"*******************","installments":1,"merchantTrns":"-","customerTrns":"Smart Delivery Order Payment","currencyCode":978,"customer":{"fullname":"Test Test","phone":"**********","requestLang":"el","email":"*********@gmail.com","countryCode":"GR"}}',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization:
         'Bearer ********',
        'User-Agent': 'axios/0.19.0',
        'Content-Length': 330 },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus] },
  request:
   ClientRequest {
     _header:
      'POST /nativecheckout/v2/transactions HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nAuthorization: Bearer 
  response:
   { status: 502,
     statusText: 'Bad Gateway',
     headers:
      { server: 'Kestrel',
        'strict-transport-security': 'max-age=15768000',
        'content-type': 'application/json; charset=utf-8',
        'x-viva-eventid': '10005',
        'x-viva-correlationid': '20-290-3015E29',
        'x-powered-by': 'ASP.NET',
        'content-length': '63',
        date: 'Fri, 16 Oct 2020 14:55:40 GMT',
        connection: 'close' },
     config:
      { url:
         'https://api.vivapayments.com/nativecheckout/v2/transactions',
        method: 'post',
        data:
         '{"amount":416,"preauth":false,"sourceCode":"Default","chargeToken":"*************","installments":1,"merchantTrns":"-","customerTrns":"Smart Delivery Order Payment","currencyCode":978,"customer":{"fullname":"Test Test","phone":"***********","requestLang":"el","email":"******@gmail.com","countryCode":"GR"}}',
        headers: [Object],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        adapter: [Function: httpAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus] },
     request:
      
        _header:
         'POST /nativecheckout/v2/transactions HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nAuthorization: Bearer ******r\nUser-Agent: axios/0.19.0\r\nContent-Length: 330\r\nHost: api.vivapayments.com\r\nConnection: close\r\n\r\n',
       
     data:
      { status: 502, message: 'Transaction failed', eventId: '10005' } },
  isAxiosError: true,
  toJSON: [Function] } 
`

**Comment by matthewrgourd** [comment]
Hi @Alexookah, I've checked and you're getting repeated payment failures on the Visa card ending 9008 with the Do Not Honour reason from the issuer. The only thing I can see at this end that might make a difference is if you set up a payment source other than the default one (as described here: https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/#native-checkout-v2-3ds) or try another card.

**Comment by Alexookah** [comment]
first i tried again using the default source code and it worked correctly in this merchant.

closing this issue

thanks for your tips @matthewrgourd. ( will keep them in mind for future similar issues)
