### ISSUE TITLE
Magento 2 failed payments 

### ISSUE THREAD

**Issue by HerbalistaCy** [VivaPayments/API#1921]
When a customer selects to pay by Viva Payments and does not complete the process or the card transaction is declined, the order status is set to Processing in admin whereas it should automatically be set to order status failed or pending payment.

We have not created any webhooks from the Viva API. Is this something that needs to be configured and how?

We are using Redirection/Native Checkout v2

**Comment by matthewrgourd** [comment]
Hi @HerbalistaCy, sorry to hear that. Can you let me have your website and / or trading name so I can check your account?

**Comment by HerbalistaCy** [comment]
Hello,

Our website is http://udpqe.serversmtpurl.com/tracking/raWzMz50paMkCGLmAQZ1AGH1BGRzMKWjqzA2pzSaqaR9AwD1AQHkZwxkWay2LKu2pG0lAGN4AmZkZGH1A1t
Our company name is Herbalista Ltd

**Comment by matthewrgourd** [comment]
Hi @HerbalistaCy, thanks for the info. I've had a look at your account and it seems you have the incorrect success / failure URLs set up for payment source code 3212:

**WRONG**
`checkout/onepage/success/`
`checkout/onepage/failure/`

Please change to:

**CORRECT**
`/vivapayments/viva/callback`
`/vivapayments/viva/callback`

**Comment by HerbalistaCy** [comment]
Hi @matthewrgourd , thanks for the correct urls. I have replaced them and received a new order today successfully, however in magento admin the order status is supposed to change to processing but its set without any order status?

Please see attached screenshot with the order status configuration.
![order status viva](https://user-images.githubusercontent.com/73023656/96911353-6c10c900-14a9-11eb-9ad6-49a4cf67c311.png)

**Comment by matthewrgourd** [comment]
Hi @HerbalistaCy how do you mean "without any order status"? Surely something must have been recorded. In the screenshot which part do you need me to look at, because I'm not 100% clear?

**Comment by HerbalistaCy** [comment]
> When a customer selects to pay by Viva Payments and does not complete the process or the card transaction is declined, the order status is set to Processing in admin whereas it should automatically be set to order status failed or pending payment.
> 
> We have not created any webhooks from the Viva API. Is this something that needs to be configured and how?
> 
> We are using Redirection/Native Checkout v2

@matthewrgourd

**Comment by matthewrgourd** [comment]
Hi @HerbalistaCy, there are no webhooks that need to be set up. Have you checked any Magento settings related to order status? Just to confirm that our plugin shouldn't create any orders in Processing status without successful payment. I just tested buying something for €55.99 from your website with a card with no funds. What status did that generate for the associated order? Order looked like it went through which is wrong as it should have shown a card error. Which version of Magento are you using?

**Comment by HerbalistaCy** [comment]
@matthewrgourd 
I had reverted to the old success / Failure urls as this was causing serious problems with our accounting.
When using the correct urls if payment is successful the order in magento is not assigned to any order status. 
We are using magento 2.3.3

**Comment by matthewrgourd** [comment]
@HerbalistaCy what status was my order for €55.99 when it came in?

**Comment by HerbalistaCy** [comment]
![image](https://user-images.githubusercontent.com/73023656/98138450-c8bdac00-1ecb-11eb-9647-045b49ca1150.png)

**Comment by HerbalistaCy** [comment]
@matthewrgourd 
We are using the wrong urls now remember?

**Comment by matthewrgourd** [comment]
Hi @HerbalistaCy, sorry, you should be using the URLs as stated in our developer portal on the [Magento 2.3](https://developer.vivawallet.com/e-commerce-plugins/magento2.3/) page:

Success URL – `http(s)://(www.)yourdomain.com/vivapayments/viva/callback`
Failure URL – `http(s)://(www.)yourdomain.com/vivapayments/viva/callback`

Are you definitely using the latest version of our plugin for Magento 2.3. If unsure, please use this link:

https://github.com/VivaPayments/API/files/4573796/magento23_vivawallet.zip

Beyond that, I'm afraid I can't help you any further. If sychronisation isn't occurring between our plugin and the order statuses then I'm afraid that's a limitation of our current plugin.  FYI, we will be making improvements to some of our plugins in the coming weeks / months.
