### ISSUE TITLE
Payment method do not display in cart

### ISSUE THREAD

**Issue by mughen6ki** [VivaPayments/API#1923]
Hi evryone, 
I'm developing an e-commerce for a client and want to use vivawallet as payment method.

We opened a business account with vivapayment and now i'm tryng to add the plugin on wordpress + woocommerce site.

i follow this guide: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
I download the plugin at this link: https://woocommerce.com/products/viva-wallet-for-woocommerce/#

I think to setup correctly all the forms on woocommerce payment method, but when i try to complete order on site, any payment method is displayed.

i attach you some screenshot of settings.

Help us please, if you need other info ask and i update.
site is: www.sbhemp.it

![screeengit](https://user-images.githubusercontent.com/73112815/96449478-305dd100-1215-11eb-90c4-9a33e851f1ed.png)
![screeengit2](https://user-images.githubusercontent.com/73112815/96450413-75cece00-1216-11eb-8674-8235743513be.png)
![screeengit3](https://user-images.githubusercontent.com/73112815/96449946-dc072100-1215-11eb-8a1e-27f3c9a8a809.png)
![screeengit4](https://user-images.githubusercontent.com/73112815/96450500-95fe8d00-1216-11eb-81b8-d90055fc2388.png)
![screeengit5](https://user-images.githubusercontent.com/73112815/96450627-bfb7b400-1216-11eb-80f6-d6ba153ef3de.png)

Thank you very much, your help will be really appreciate :)

**Comment by matthewrgourd** [comment]
Hi @mughen6ki, our plugin for WooCommerce creates its own payment source automatically. You should not modify any of the settings. Can you tell me exactly what happened when you enabled the plugin and went to checkout. Did the payment form not display?

**Comment by mughen6ki** [comment]
hi Mattew thank you very much for your reply.

The payment source was automatically created, and after some minutes of try the payment method is displayed in the checkout section. this is great !
Just do not remember if i change something, for example "redirection/native checkout v2" or "native chckout".
which is the correct one ?

now there is another problem: after i put the credit card datas and try to pay, i encounter an error message:
"There was a problem with your card. Please check the card details and try again."
I try 2 different cards, but the result is the same..

has you an idea of why this happend ?

![screeengit7](https://user-images.githubusercontent.com/73112815/96457227-c8f94e80-121f-11eb-9667-1e175e642c79.png)
![screeengit6](https://user-images.githubusercontent.com/73112815/96457246-cd256c00-121f-11eb-9fbd-ea876bbf81a8.png)
![screeengit8](https://user-images.githubusercontent.com/73112815/96457253-d1ea2000-121f-11eb-8656-2262328d2adc.png)

thank you again !!

**Comment by matthewrgourd** [comment]
Hi @mughen6ki for the integration method, please select the **Redirection/Native Checkout v2** radio button in the payment source. Try again with the test card payment and let me know the result.

**Comment by mughen6ki** [comment]
i try to change the radio button, but the error still the same
"there was a problem with your card. Please check the card details and try again"

Waiting for your kind reply :)

**Comment by matthewrgourd** [comment]
Hi @mughen6ki, can you check you're using the latest version of our plugin, as shown below?

![installed-plugins](https://user-images.githubusercontent.com/44943019/96557701-87fe4a00-12b2-11eb-8b3e-ffb7869d4a95.png)

**Comment by matthewrgourd** [comment]
Closing as no reply
