### ISSUE TITLE
Viva Wallet Stuck on Payment Pending

### ISSUE THREAD

**Issue by FlyingFoxCreative** [VivaPayments/API#1924]
I have installed Viva Wallet payment gateway on a client's woocommerce shop.

Everything is configured correctly, but the orders are showing up as "payment pending" instead of processing. 

The payments are being taken out of the bank account of the card being used and the money is going into the "today's revenue" in my viva wallet account. 

I have a feeling these orders will cancel on their own if they aren't set as "processing" manually. I don't want to do that, because there is a number of reasons it will display as "payment pending"

Please help me resolve this issue as viva wallet isn't being very helpful.

**Comment by matthewrgourd** [comment]
Hi @FlyingFoxCreative, sorry to hear this. Please can I have the website address where you have installed the plugin. Also, the trading name of the merchant so I can check their account. Thanks.

**Comment by FlyingFoxCreative** [comment]
https://theessenceofwellbeing.co.uk

The Essence Of Wellbeing

**Comment by FlyingFoxCreative** [comment]
Everything is configured as per the instructions provided and the online payment I have created is active. 

The other issue I am having is that viva wallet is adding numbers after the selected successful and unsuccessful payment URLS and the redirect is creating a 404 error.

**Comment by matthewrgourd** [comment]
Hi @FlyingFoxCreative, I notice you're using the previous redirect version of our plugin for WooCommerce. We strongly advise you to download and install our new native plugin which supports Apple Pay and improved syncing with WooCommerce orders. Payment source setup is automatic so it's also a lot easier to install. Please visit https://docs.woocommerce.com/document/viva-wallet-for-woocommerce for further info.

**Comment by FlyingFoxCreative** [comment]
yes! this worked! Order now showing as completed! Thank you!

**Comment by FlyingFoxCreative** [comment]
HOWEVER... It is showing up as completed, but not showing up as a new order or sending the email to the address provided in the email section

**Comment by matthewrgourd** [comment]
Hi @FlyingFoxCreative, sorry, I don't understand what you mean. Just to let you know, I can see two successful transactions made via the "WooCommerceNativeCheckoutV2" channel this afternoon, both for £1.

**Comment by matthewrgourd** [comment]
Closing as no reply
