### ISSUE TITLE
APPLE PAY 

### ISSUE THREAD

**Issue by Gfox1972** [VivaPayments/API#1926]
Morning, I have had a few of these now being sent through to me I have checked my logs no errors the gateway 100% works but apple pay seems to be unavailable

www.thedreambikecompetition.co.uk 

<img width="257" alt="Screenshot 2020-10-21 at 09 00 06" src="https://user-images.githubusercontent.com/69973030/96690620-d3305f80-137b-11eb-90d9-acadbd6a9b1b.png">

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, we're looking into this. I'll let you know as soon as I've got an update.

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, can you let me know something? When you configured the plugin, enabled and clicked on save on the settings page (**Plugins > Installed Plugins > Viva Wallet for WooCommerce > Settings**), you should have received some messages at the top including one about Apple Pay. Can you send me a screenshot of these? (with any confidential info blurred out, of course) Thanks!

**Comment by Gfox1972** [comment]
I have just noticed there was an update 

I am now running version 112

lets hope that sorts it 

as for the apple message it states 

Viva Wallet: Your LIVE credentials are valid.
Viva Wallet: Your LIVE source code: ******* is verified and you are ready to accept payments.
Viva Wallet: Your domain is verified with Apple Pay and you are ready to accept LIVE payments!

best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, thanks for sending through that info and letting us know you've gone ahead with the upgrade. Can you do one more thing for me and let me know what source is currently selected under **Advanced settings** here:

![advanced-settings](https://user-images.githubusercontent.com/44943019/96710450-00890780-1394-11eb-85f4-a1104d4b6f24.png)

**Comment by Gfox1972** [comment]
i have WC-0001 selected 

But I am sure it use to be WC-0005 !



best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, WC-0001 is correct because it is associated with your current domain: thedreambikecompetition.co.uk

May I ask one more thing, when you log in to WP Admin, which of the following URLs do you use?

- https://thedreambikecompetition.co.uk/wp-admin
- https://www.thedreambikecompetition.co.uk/wp-admin

**Comment by Gfox1972** [comment]
I use //thedreambike


I know i had some dev work done recently and they set it to //www. and it was then changed back! to “//the” 


best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, ok, that's fine.

We've investigated further and although you correctly have WC-0001 selected in the plugin settings, the source code on your basket page is showing WC-0005 (see below). Please amend as soon as possible otherwise your customers will continue to experience problems with Apple Pay. Thanks!

![Screenshot 2020-10-21 at 12 43 36](https://user-images.githubusercontent.com/44943019/96715174-164dfb00-139b-11eb-8dd8-b9d5667bf9b8.png)

**Comment by Gfox1972** [comment]
ok should just delete WC-0005 from my viva account ?

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, unfortunately it isn't possible to delete payment sources which have transactions recorded against them as that one does. Let me check what you need to do and get back to you.

**Comment by matthewrgourd** [comment]
Hi @Gfox1972, the best thing for you to do is deactivate and delete the existing plugin from **Plugins > Installed Plugins**.  Upload the below plugin file which is the latest version. Then reinstall and reconfigure with your WooCommerce credentials from the Viva Wallet banking app. This will reset the Apple flag and the call to register the domain will execute again. Let me know how you get on!

[viva-wallet-for-woocommerce_V1.1.2.zip](https://github.com/VivaPayments/API/files/5421244/viva-wallet-for-woocommerce_V1.1.2.zip)

**Comment by Gfox1972** [comment]
that worked many thanks for you help matthew 


best regards 
Grant Fox
07789882255
www.southcoastsuspension.co.uk <http://www.southcoastsuspension.co.uk/>
www.dreambikecompetition.co.uk <http://www.dreambikecompetition.co.uk/> 
www.facebook.com/southcoastsuspension <http://www.facebook.com/southcoastsuspension>
 
MTB Suspension Specialists, Fox trained and Approved
VULPES MEDIA LIMITED 1179452

**Comment by matthewrgourd** [comment]
@Gfox1972 no problem!
