### ISSUE TITLE
Shopify Test Transactions

### ISSUE THREAD

**Issue by estazz** [VivaPayments/API#1927]
Hi guys,

I am having an issue with testing your Shopify solution  for one of my clients. I strictly followed your Shopify [Guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/) but do not know how to test the integration. 

The vivawallet account within Shopify is still set in test mode and when trying to buy an item I get redirected to this page: https://feed.viva.gr/shopify with ends in a timeout.

Any ideas on how I can fix this and test the integration before going live?

Thanks in advance!

**Comment by matthewrgourd** [comment]
Hi @estazz, sorry to hear you're having issues. Unfortunately our plugin doesn't have a test option so you should always leave test mode deselected. The solution is to try making a real payment then immediately refund the money from the Viva Wallet banking app. Minimum payment amount is €0.30 or £0.30. Hope this helps!
