### ISSUE TITLE
Refund: Non reversible transaction

### ISSUE THREAD

**Issue by dskalidis** [VivaPayments/API#193]
Καλησπέρα σας,

Προσπαθώ να κάνω refund και ενώ βλέπω στο demo site ότι έχει γίνει η ακύρωση της παραγγελίας και και επιστροφή χρημάτων σε εμένα έρχεται απάντηση 403 Non reversible transaction.

MerchantID: 5e69b107-ced3-462b-81cb-8006c08b5d93

**Comment by defilerc** [comment]
Καλησπέρα @dskalidis ,

Μπορείτε να μας στείλετε τη διαδικασία που ακολουθείτε και παίρνετε το παραπάνω error;

1. Με ποιές παραμέτρους κάνετε τη δημιουργία πληρωμής (CreateOrder).
1. Με ποιές παραμέτρους κάνετε την αρχική χρέωση.
1. Με ποιές παραμέτρους κάνετε το Cancel της συναλλαγής.

Με εκτίμηση,
