### ISSUE TITLE
When making a payment on Shopify, it redirects but doesn't go any where. Then times out? Merchant ID and Token in place.

### ISSUE THREAD

**Issue by TheCBDPeople** [VivaPayments/API#1930]

**Comment by matthewrgourd** [comment]
Hi @TheCBDPeople, sorry to hear that. So that I can investigate further, please provide your Viva Wallet Merchant ID. Thanks!

**Comment by TheCBDPeople** [comment]
Hi Matt.

Thanks for the message. My Merchant ID is below:

5d7aaad9-6ae9-459f-b137-8ea987dd2fb2

Let me know if you need anything else.

Regards

Rob

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by matthewrgourd** [comment]
Hi @TheCBDPeople, thanks for that, and can I confirm that you entered the above Merchant ID in the correct field in the Shopify settings, together with the Store Token we provided you, again in the correct field as shown below? I'm sorry, I have to ask this, as a lot of people get it wrong!

![viva-wallet-settings](https://user-images.githubusercontent.com/44943019/97000034-116d8080-152e-11eb-951e-f12412d318f3.png)

**Comment by TheCBDPeople** [comment]
Hi.

I entered the Merchant ID into the top box then the token you supplied in the box below it. When i entered the Token, i clicked the button so I couls check it was correct. When i then saved it, the turned to those 6 dots. Is that correct?


Regards

Rob

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by matthewrgourd** [comment]
Hi @TheCBDPeople, yes, that's correct. Can you email me your token so I can check you've been given the right one? For security reasons can you send it to my email address quoting this issue (#1930): mgourd@vivawallet.com

**Comment by TheCBDPeople** [comment]
Thanks Matt. Ive emailed that over to you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by matthewrgourd** [comment]
Hi @TheCBDPeople, the Shopify token you emailed is correct, so I'm checking further for you what the problem might be.

**Comment by TheCBDPeople** [comment]
Ive just tried purchasing amd item again and it did the same thing. When it times out,
it shows -

"feed.viva.gr" took to long to respond


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by matthewrgourd** [comment]
Hi @TheCBDPeople sorry to hear that. We can't see a problem with your settings. Can you enable once again so I can test? Just for 15 minutes or so. Thanks!

**Comment by matthewrgourd** [comment]
Hi @TheCBDPeople, I've worked out what the issue is. You need to deselect test mode in your Shopify settings. Please try that and see what happens. Thanks!

**Comment by TheCBDPeople** [comment]
Thanks Matt.

I'll try that now 🙂.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TheCBDPeople** [comment]
Thats done the trick. For some reason I thought with the test mode selected itbwould still go through to the payment.

Many thanks for your help Matt.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
