### ISSUE TITLE
Could not create order. Generic Error - Message order Viva wallet x SHopify

### ISSUE THREAD

**Issue by Steevo0206** [VivaPayments/API#1931]
Hi guys,

I have this error message when I checkout with viva wallet on my shopify website "Could not create order. Generic Error."
Does anyone know how to fix this? I have tried A LOT of things.
Thank you

**Comment by matthewrgourd** [comment]
Hi @Steevo0206, let me look into this for you. Could I start by taking your Viva Wallet Merchant ID?

**Comment by Steevo0206** [comment]
Thanks Matthew here is my merchant ID 3b8264cd-d5fe-40d6-86f8-a73e97610d85.

**Comment by matthewrgourd** [comment]
Hi @Steevo0206, this is already solved, please see my response to your colleague here: https://github.com/VivaPayments/API/issues/1929#issuecomment-715198592
