### ISSUE TITLE
viva payment in french by default

### ISSUE THREAD

**Issue by Steevo0206** [VivaPayments/API#1934]
Hi @matthewrgourd I hope you are fine.
I have an issue with the language of the checkout.
As you can see it's english by default. Is it possible to have it in french?
![Screenshot 2020-10-25 at 22 29 37](https://user-images.githubusercontent.com/72416056/97120803-c4e29a80-1711-11eb-92d4-30530b5b2ee2.png)
Another request is to change the email address steeveelgui@gmail.com to contact@joiiacbd.com.
Please tell me if it's possible.
Thank you

**Comment by matthewrgourd** [comment]
Hi @Steevo0206, French will be supported soon. For the moment, we only handle GR/EN languages as default. For countries other than Greece and the UK, the user has to manually change the language during checkout. Apologies for any inconvenience caused.
