### ISSUE TITLE
Wrong order

### ISSUE THREAD

**Issue by Mjennifer** [VivaPayments/API#1935]
Dear Viva Payment, I am working together with The Hempish Group BV. Account ID: 2041810785
We recieved 1 payment yesterday with Viva Payment, however in our e-com platform there is a differnt name
Just wanted for you to confirm order #3546

**Comment by matthewrgourd** [comment]
Hi @Mjennifer, I see that the merchant is using our Shopify plugin. For yesterday I can see one successful payment and that is for €155,00 and registered against order number #3546.

**Comment by Mjennifer** [comment]
Can you see the email adress that was used?

**Comment by matthewrgourd** [comment]
Hi @Mjennifer, I'm sorry, I can't disclose any contact info. as this is a public GitHub. Please speak to our customer service team via the online chat at www.vivawallet.com for further details.

**Comment by Mjennifer** [comment]
Dear Matthew, thank you for getting back to me. 
This is strange since the customer converted at or woocommerce site 
Can you see any conversions at the woo commerce plugin?

**Comment by matthewrgourd** [comment]
HI @Mjennifer, ah, sorry, yes, that transaction of €155,00 with the reference 3546 came in from the WooCommerce site and was approved. However, there are no other transactions.

**Comment by Mjennifer** [comment]
Thank you

Vänligen,
Jennifer Moonan
________________________________
Från: matthewrgourd <notifications@github.com>
Skickat: Monday, October 26, 2020 3:17:33 PM
Till: VivaPayments/API <API@noreply.github.com>
Kopia: Mjennifer <jennifer.moonan@live.se>; Mention <mention@noreply.github.com>
Ämne: Re: [VivaPayments/API] Wrong order (#1935)


HI @Mjennifer<https://github.com/Mjennifer>, ah, sorry, yes, that transaction of €155,00 with the reference 3546 came in from the WooCommerce site and was approved. However, there are no other transactions.
