### ISSUE TITLE
Cloud Distro S.L

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1937]
Hi @matt! I have some problems with this merchant ´´Cloud Distro S.L´´ because he is trying to set up his own developement in our payment gateway but doesn´t get it. Could you take a look?

Good morning, I'm Alin the developer in charge of Cloud Distro to implement the Vivawallet API to perform Online Checkout with the NATIVE mode. Currently there are problems with the generation of the transaction with the endpoint "nativecheckout/v2/transasctions" as it is being blocked in the OPTIONS of the request.
The configuration of the application on the Vivawallet website is as follows:
![imagen](https://user-images.githubusercontent.com/56823712/97290765-4d178b80-1849-11eb-9b9f-593e1b6f77d3.png)
![unnamed](https://user-images.githubusercontent.com/56823712/97290785-54d73000-1849-11eb-8f99-3e6638f281dd.png)

The process we are carrying out is as follows:

**1º We generate the OAtuh Token 2 as indicated in the documentation:**

$url = 'https://accounts.vivapayments.com/connect/token';

$headerArgs = array(
    "Accept: application/json",
    "Authorization: Basic YW83Y3dndjU1YjczNDJ2MXZjY245M3d....."
);

$postArgs = array(
    "grant_type" => "client_credentials",
);

$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, $url);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($curl, CURLOPT_ENCODING, "");
curl_setopt($curl, CURLOPT_MAXREDIRS, 10);
curl_setopt($curl, CURLOPT_TIMEOUT, 0);
curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);
curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($curl, CURLOPT_POSTFIELDS, $postArgs);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headerArgs);

$res = curl_exec($curl);
curl_close($curl);

**2º With the access_token, we go on to generate the "chargetoken":**

const baseUrl = 'https://api.vivapayments.com';

VivaPayments.cards.setup({
    baseURL: baseUrl,
    authToken: '<?php echo $token->access_token?>',
    cardHolderAuthOptions: {
        cardHolderAuthPlaceholderId: 'threed-pane',
        cardHolderAuthInitiated: function () {
            $('#threed-pane').show();
        },
        cardHolderAuthFinished: function () {
            $('#threed-pane').hide();
        }
    },
    installmentsHandler: function (response) {
        if (!response.Error) {
            if (response.MaxInstallments == 0)
                return;
            $('#drpInstallments').show();
            for (i = 1; i <= response.MaxInstallments; i++) {
                $('#drpInstallments').append($("<option>").val(i).text(i));
            }
        }
        else {
            alert(response.Error);
        }
    }
});

**3º With the "chargetoken" we generate the transaction and that is when the error 404 occurs in the OPTIONS:**

evt.preventDefault();
VivaPayments.cards.requestToken({
    amount: 10
}).done(function (data) {

    console.log(data);
    $.ajax({
        type: "POST",
        headers: {
            'Authorization': 'Bearer <?php echo $token->access_token?>',
            'Content-Type': 'application/json',

        },
        url: 'https://api.vivapayments.com/nativecheckout/v2/transactions',
        data:{
            "amount": '10',
            "chargeToken": data,
            "sourceCode": "2038",
            "installments": 1,
            "preauth": true,
            "merchantTrns": "Merchant transaction reference",
            "customerTrns": "Description that the customer sees",
            "currencyCode": 978,
            "customer": {
                "email": "prueba@gmail.com",
                "phone": "6161611",
                "fullname": "Jhon",
                "requestLang": "es",
                "countryCode": "ES"
            }
        },
        dataType: 'json',
        success: function(data) {
            console.log(data);
        }
    });
});

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I've tested our Native Checkout v2 solution and it seems to be working fine. Can you ask the developer if they performed step 3 in a browser or via a back-end channel? The second option will work whereas the first option won't.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant asked me the next:

option 3 refers to this:

Step 3: Initialize Native Checkout 
Initialize Native Checkout v2 by calling the setup() method.
Example in JavaScript:
VivaPayments.cards.setup({
	authToken: 'your_access_token',
	baseURL: 'https://demo-api.vivapayments.com',
	cardHolderAuthOptions: {
		cardHolderAuthPlaceholderId: 'threed-pane',
		cardHolderAuthInitiated: function() {
			alert('Cardholder authentication started!');
		},
		cardHolderAuthFinished: function() {
			alert('Cardholder authentication has finished');
		}
	}
});

He does this when he load the page with the form and the "access_token" he get before the page loads in PHP.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, no, I'm asking if he made the last step:

POST to `https://api.vivapayments.com/nativecheckout/v2/transactions`

through a back-end channel as it should not be done through a browser.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant ensure me that he has done through a back-end channel

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, in that case, it's a problem with his code which unfortunately I won't be able to help with as it's a custom integration. In case this may help, what worked for me is the below code pointing at production. The merchant should replace `[access token]` with his unique token (see [Request access token](https://developer.vivawallet.com/web-api-integration/authentication/#step-2-request-access-token) under [OAuth 2 Authentication](https://developer.vivawallet.com/web-api-integration/authentication/#identityserver-oauth-2-authentication) for more info).
```
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Native 3DS test</title>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://www.vivapayments.com/web/checkout/v2/js"></script>
</head>

<body>

    <form action="" method="POST" id="payment-form">
        <div class="form-row">
            <label>
                <span>Cardholder Name</span>
                <input type="text" size="20" name="txtCardHolder" autocomplete="off" data-vp="cardholder"
                    value="" />
            </label>
        </div>

        <div class="form-row">
            <label>
                <span>Card Number</span>
                <input type="text" size="20" name="txtCardNumber" autocomplete="off" data-vp="cardnumber"
                    value="" />
            </label>
        </div>
        <div class="form-row">
            <label>
                <span>CVV</span>
                <input type="text" name="txtCVV" size="4" autocomplete="off" data-vp="cvv" value="" />
            </label>
        </div>
        <div class="form-row">
            <label>
                <span>Expiration (MM/YYYY)</span>
                <input type="text" size="2" name="txtMonth" autocomplete="off" data-vp="month" value="" />
            </label>
            <span> / </span>
            <input type="text" size="04" name="txtYear" autocomplete="off" data-vp="year" value="" />
        </div>
        <button type="button" id="submit" (click)="submit($event)">Submit Payment</button>
    </form>
    <div id="threed-pane" style="height: 450px;width:500px">
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            const baseUrl = 'https://api.vivapayments.com';
            VivaPayments.cards.setup({
                baseURL: baseUrl,
                authToken: '[access token]',
                cardHolderAuthOptions: {
                    cardHolderAuthPlaceholderId: 'threed-pane',
                    cardHolderAuthInitiated: function () {
                        $('#threed-pane').show();
                    },
                    cardHolderAuthFinished: function () {
                        $('#threed-pane').hide();
                    }
                },
                installmentsHandler: function (response) {
                    if (!response.Error) {
                        if (response.MaxInstallments == 0)
                            return;
                        $('#drpInstallments').show();
                        for (i = 1; i <= response.MaxInstallments; i++) {
                            $('#drpInstallments').append($("<option>").val(i).text(i));
                        }
                    }
                    else {
                        alert(response.Error);
                    }
                }
            });

            $('#submit').on('click', function (evt) {
                evt.preventDefault();
                VivaPayments.cards.requestToken({
                    amount: 3600
                }).done(function (data) {
                    console.log(data);
                    alert(data.chargeToken);
                });
            });

        });
    </script>
</body>
</html>
```
This will enable him to enter card details (real card) after which he should authenticate via 3DS. Once this is done, a one-time charge token is generated. This can then be used in the following call or similar. Example using cURL:
```
curl -L -X POST 'https://api.vivapayments.com/nativecheckout/v2/transactions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer [access token]' \
--data-raw '{
 "amount": 150,
 "preauth": false,
 "sourceCode": "Default",
 "chargeToken": "ctok_*****",
 "Installments": 1,
 "merchantTrns": "Merchant transaction reference",
 "customerTrns": "Description that the customer sees",
 "currencyCode": 826,
 "customer": {
 "email": "test@example.com",
 "phone": "442037347770",
 "fullname": "John Smith",
 "requestLang": "en",
 "countryCode": "GB"
 }
}'
```
Then a response is returned with a transaction ID:
```
{
    "transactionId": "********-****-***-**-*******"
}
```
Hope this helps!

**Comment by Alvaroalconada** [comment]
fuck! what a programming masterclass you just gave me Matt jaja.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant is trying to make the request for the transaction and it returns the following error all the time:

"stdClass Object ([status] => 400 [message] => Null options [eventId] => 0 )"
These are his fields:

$headerArgs = array(
    "Authorization: Bearer ". $oauth,
    "Content-Type: application/json",
    "Content-Type: text/plain"
);

$postArgs = array(
    'amount' => 10,
    'chargeToken' => $token,
    'sourceCode' => 2038,
    'installments' => 1,
    'preauth' => false,
    'merchantTrns' => "Merchant transaction reference",
    'customerTrns' => "Description that the customer sees",
    'currencyCode' => 978,
    'customer' => array(
        'email' => "cretu@ossian.tech",
        'phone' => "+34617199077",
        'fullname' => "CUSTOMER_NAME",
        'requestLang' => 'es',
        'countryCode' => 'ES'
    )
);

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, error 400 means "Bad request, the server could not understand the request due to invalid syntax." I've provided an example with the correct syntax already. I'm afraid I wont be able to help any further with the merchant's code. He needs to recheck the example I gave and our [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) documentation and work it out from there. Thanks.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant answered me the next: I am doing exactly what you are telling me and following the documentation to the letter. You can look at the image I have sent you to see if you see anything wrong? I just don't understand the message of 400 Mala Mala syntax if it's identical.

Could you contact him through mail and try to solve the implementation pls? I have to make calls and I don´t have more time for it
I send you mails that I Interchange with him before

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I'm sorry, I'm unable to provide any further assistance for this merchant by email or via GitHub.

**Comment by Alvaroalconada** [comment]
@matthewrgourd So which alternative solution could you provide me? telling merchant that choice another plugin of our list and try to implement?

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant just told me the next: this message comes up when I make the request from POSTMAN

{
    "Status: 403,
    "message": "PaymentsCardHolderAuthenticationFailed",
    "eventId": "2062"
}

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, the 403 response code is due to a pending 3DS session ID. He needs to render the response HTML to a web page. The correct flow is:

1. A user types his card details.

2. Maybe a popup will be rendered while the issuer sends a push notification to the client to authorise the transaction.

3. After authorisation, the popup closes and Viva Wallet redirects the session to the redirect URL that he's using as a parameter.

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant tells me the next:

I can understand why I was doing that from a program, but from the back-end it comes out now:

"HTTP/1.0 401 Unauthorized Server: Kestrel Strict-Transport-Security: max-age=15768000 WWW-Authenticate: Bearer X-Viva-CorrelationId: 20-302-AC36616D X-Powered-By: ASP.NET Content-Length: 0 Date: Wed, 28 Oct 2020 13:20:54 GMT Connection: close

I'm following all the steps as it says in the documentation.

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant asks me if this screenshot is well configured?
![unnamed (1)](https://user-images.githubusercontent.com/56823712/97456725-6992f100-1939-11eb-931b-15fb25b48bfd.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, no, there's nothing wrong with his payment source settings. Please note that when making the POST to `https://api.vivapayments.com/nativecheckout/v2/transactions` he should then replace `"sourceCode": "Default"` with `"sourceCode": "2038"` in the body parameters.

**Comment by Alvaroalconada** [comment]
@matthewrgourd Hi machine, it seems that everything goes well, He is doing some test transactions, perfect

Like always thanks a lot for your support Sir

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant tells me that they are having several issues when their customers are making trx, not executed. System gives a payment error. They are using an own development. I let you the error message that came out them:

HTTP/1.1 405 Method Not Allowed
Server: Kestrel
Strict-Transport-Security: max-age=15768000
Content-Type: application/json; charset=utf-8
X-Viva-EventId: 0
X-Viva-CorrelationId: 20-317-F0D5D56B
X-Powered-By: ASP.NET
Content-Length: 78
Date: Thu, 12 Nov 2020 07:59:13 GMT
Connection: close

{"status":405,"message":"Action blocked due to security policy","eventId":"0"}

**Comment by matthewrgourd** [comment]
Do they have our payment gateway enabled currently at www.vapeo24.com for me to test?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, it seems that the merchant's account has plenty of successful transactions so it looks like the integration is working correctly. The above message means "Acquiring anti-fraud rule violation" and probably relates to a card problem rather than an issue on the Viva Wallet side.
