### ISSUE TITLE
2mhellas.gr issue

### ISSUE THREAD

**Issue by 2mhellas** [VivaPayments/API#1938]

**Comment by matthewrgourd** [comment]
Hi @2mhellas please provide some more info. if you have a genuine issue that needs resolving. Thanks.

**Comment by matthewrgourd** [comment]
Hi @2mhellas, I see you're using WooCommerce with the Viva Wallet plugin for card payments. Looking at your account, there was one successful payment on 21 October, and two payment failures as below:

- **27 October** – Visa Insufficient funds (51)
- **26 October** – Mastercard Insufficient funds (51)

From this information I can confirm that our plugin for WooCommerce is functioning currently. Please let me know if you have any further queries. Alternatively you can close the issue if you feel it has been addressed adequately.
