### ISSUE TITLE
configure Simply Quick with Joomla Gridbox

### ISSUE THREAD

**Issue by Botteghe** [VivaPayments/API#1939]
Hi, i need help to install simply quick on my ecommerce made with joomla gridbox. I put my publikey on html code and it give me an error. Can I have help?

**Comment by matthewrgourd** [comment]
Hi @Botteghe, unfortunately we don't have a Viva Wallet payment plugin for Joomla Gridbox.

**Comment by Botteghe** [comment]
Hello Gridbox has recently launched ecommerce, are you planning to
release the plugin?


That you

Isabella


Il mer 28 ott 2020, 16:46 matthewrgourd <notifications@github.com> ha
scritto:

**Comment by matthewrgourd** [comment]
Hi there, sorry, we have no plans to do so as yet.

**Comment by Botteghe** [comment]
Ok, I need help to configure this method on my ecommerce. Can you help me?

Il mer 28 ott 2020, 16:52 matthewrgourd <notifications@github.com> ha
scritto:

**Comment by matthewrgourd** [comment]
Can you attach a screenshot of what you're seeing?

**Comment by matthewrgourd** [comment]
Closing as no reply
