### ISSUE TITLE
Αδυναμία Πληρωμής

### ISSUE THREAD

**Issue by quadrawebteam** [VivaPayments/API#194]
Καλησπέρα,

εχω κάνει την διασύνδεση του viva payments με Wordpress E-shop με ένα wordpress plugin της εταιρείας Webit. 

Έχει ολοκληρωθεί η ταυτοποίηση του επαγγελματικού λογαριασμού viva και έχει εγκριθεί και η ιστοσελίδα. 

Κάνω δοκιμαστική πληρωμή 0,01€ για ενα αντικείμενο με κάνει redirect στην σελίδα της viva και μόλις βάλω τα στοιχεία της κάρτας και πατάω το κουμπί "χρέωση" με πετάει σε μία σελίδα του Eshop μου με 404 error. 

Αν υπήρχε πρόβλημα στην διασύνδεση με το plugin δεν θα έκανε καν redirect στο viva. Από την στιγμή που κάνει το redirect και πληρώνω σημαίνει ότι δεν δέχεται την πληρωμή? 

Το πρόβλημα αφορά το site audiction.gr

Ευχαριστώ, Δημήτρης

**Comment by dmihos** [comment]
Καλημέρα
Θα πρέπει να δοκιμάσετε με κάποιο μεγαλύτερο ποσό, καθώς το 0.01€ είναι πολύ μικρό για να γίνει δεκτό.

Ευχαριστούμε για την επικοινωνία
