### ISSUE TITLE
plugin for prestashop

### ISSUE THREAD

**Issue by mondialshop** [VivaPayments/API#1940]
Where i can find the plugin for prestashop 1.7.6.1?

**Comment by matthewrgourd** [comment]
Hi @mondialshop, have you tried our plugin available from here? https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/

**Comment by mondialshop** [comment]
I can’t find the link of download






[cid:image002.jpg@01D6AD4A.D9D6DA90]
Andrea Banfi // Support
Tel. +39 0331 <tel:0039+055+0351508> 490301
www.mondialshop.it<http://www.mondialshop.it/> // www.mondialshop.it/it/blog<http://www.mondialshop.it/it/blog>
Be Easy srl – Via Einaudi 33 – Parabiago Mi 20015 P.iva 07056420966
Lunedì Venerdì Orari 9>13  14>18 - Sabato Orari 9>13 Codice SDI per Fatturazione Elettronica : SUBM70N

Da: matthewrgourd <notifications@github.com>
Inviato: mercoledì 28 ottobre 2020 16:49
A: VivaPayments/API <API@noreply.github.com>
Cc: Andrea Mondialshop.it <andrea@mondialshop.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [VivaPayments/API] plugin for prestashop (#1940)


Hi @mondialshop<https://github.com/mondialshop>, have you tried our plugin available from here? https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/

**Comment by matthewrgourd** [comment]
It's on the page I mentioned? But in case you missed it:

[vivawallet1.7.zip](https://github.com/VivaPayments/API/files/5453215/vivawallet1.7.zip)

**Comment by mondialshop** [comment]
Please how to set Italian language in check-out?







[cid:image003.jpg@01D6AD5C.AE2DEC50]
Andrea Banfi // Support
Tel. +39 0331 <tel:0039+055+0351508> 490301
www.mondialshop.it<http://www.mondialshop.it/> // www.mondialshop.it/it/blog<http://www.mondialshop.it/it/blog>
Be Easy srl – Via Einaudi 33 – Parabiago Mi 20015 P.iva 07056420966
Lunedì Venerdì Orari 9>13  14>18 - Sabato Orari 9>13 Codice SDI per Fatturazione Elettronica : SUBM70N

Da: Andrea Mondialshop.it
Inviato: mercoledì 28 ottobre 2020 16:53
A: VivaPayments/API <reply@reply.github.com>
Oggetto: R: [VivaPayments/API] plugin for prestashop (#1940)

I can’t find the link of download





[cid:image002.jpg@01D6AD5C.AE29A690]
Andrea Banfi // Support
Tel. +39 0331 <tel:0039+055+0351508> 490301
www.mondialshop.it<http://www.mondialshop.it/> // www.mondialshop.it/it/blog<http://www.mondialshop.it/it/blog>
Be Easy srl – Via Einaudi 33 – Parabiago Mi 20015 P.iva 07056420966
Lunedì Venerdì Orari 9>13  14>18 - Sabato Orari 9>13 Codice SDI per Fatturazione Elettronica : SUBM70N

Da: matthewrgourd <notifications@github.com<mailto:notifications@github.com>>
Inviato: mercoledì 28 ottobre 2020 16:49
A: VivaPayments/API <API@noreply.github.com<mailto:API@noreply.github.com>>
Cc: Andrea Mondialshop.it <andrea@mondialshop.it<mailto:andrea@mondialshop.it>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Oggetto: Re: [VivaPayments/API] plugin for prestashop (#1940)


Hi @mondialshop<https://github.com/mondialshop>, have you tried our plugin available from here? https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/

**Comment by mondialshop** [comment]
hello,

A) we want set current language
we want to set the default language based on the origin of the country of origin
http://prntscr.com/v8v65b
default http://prntscr.com/v8v8p7

B) there is no button to return to our site or to cancel the transaction

**Comment by matthewrgourd** [comment]
Hi @mondialshop, by default, our plugin for PrestaShop is displayed in EN-US for customers based in Italy. They need to manually select "Italiana" from the language switcher displayed on the payment page in order to change language.

**Comment by mondialshop** [comment]
Hello, This is very bad for me….
               My customer can’t do this any time….


I don't think customers can do this / or trust a situation not in Italian.

[cid:image001.jpg@01D6ADD5.A9A8A750]
Andrea Banfi // Support
Tel. +39 0331 <tel:0039+055+0351508> 490301
www.mondialshop.it<http://www.mondialshop.it/> // www.mondialshop.it/it/blog<http://www.mondialshop.it/it/blog>
Be Easy srl – Via Einaudi 33 – Parabiago Mi 20015 P.iva 07056420966
Lunedì Venerdì Orari 9>13  14>18 - Sabato Orari 9>13 Codice SDI per Fatturazione Elettronica : SUBM70N

Da: matthewrgourd <notifications@github.com>
Inviato: giovedì 29 ottobre 2020 09:22
A: VivaPayments/API <API@noreply.github.com>
Cc: Andrea Mondialshop.it <andrea@mondialshop.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [VivaPayments/API] plugin for prestashop (#1940)


Hi @mondialshop<https://github.com/mondialshop>, by default, our plugin for PrestaShop is displayed in EN-US for customers based in Italy. They need to manually select "Italiana" from the language switcher displayed on the payment page in order to change language.

**Comment by mondialshop** [comment]
Hello, we've set http://prntscr.com/v9k1s7
But in our check out don't work - the check out is ever with redirect...
How to fix ?


is very very urgent

**Comment by matthewrgourd** [comment]
Hi @mondialshop, I'm sorry, but our PrestaShop plugin is redirect only at the moment. You should leave the radio button on the left selected.
