### ISSUE TITLE
Programmatically set the timeout for an abandoned checkout 

### ISSUE THREAD

**Issue by ozizo41** [VivaPayments/API#1941]
Hello,

I want to set a timer for an abandoned checkout in my application that calls VW POS to complete a transaction.

I checked this issue: #716, and I find that the timeout has been hard coded to 300 seconds. By any chance, can I change this timeout or set a timer in my Main Activity? (The link provided didn't exist anymore)

Thank you,
Ziad Hanna

**Comment by matthewrgourd** [comment]
Hi @ozizo41, before I can answer your query, I need to know which of our checkout solutions you've implemented as a custom integration: [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/), [Redirect](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) or [Native](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/)?

**Comment by ozizo41** [comment]
Hello again,
It's not an online checkout it's an Android POS terminal app.

**Comment by matthewrgourd** [comment]
Hi @ozizo41, sorry about that, I see the parameter you're referring to now. The documentation about `paymentTimeOut` has been transferred to our developer portal. Please check under https://developer.vivawallet.com/web-api-integration/payment-api/#tag/Payments

**Comment by ozizo41** [comment]
Thank you!
