### ISSUE TITLE
postman to connect to /connect/token is throwing errors

### ISSUE THREAD

**Issue by susaree** [VivaPayments/API#1942]
I'm trying to connect to  https://demo-accounts.vivapayments.com/connect/token
following, word for word, the guides on this forum for people who have faced similar issues. I can't get it to connect but can connect to every other company's apis.

Please can you help.

### **_Status 400:_**
curl -X POST \
  https://demo-accounts.vivapayments.com/connect/token \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic W2gzY3prOTN4OWh4Z3ZtOGduanp1Y2twNWQ1ZDd3Y3VyYWlkbzE1anN2ZHJ5Ml06W1d6M2J2Zm80cVNSSDE0aVhjNDQxeGFkOUYxMjJZQV0=' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: 8faf64b7-3f52-4a5a-b14a-da025b5cc36c,217d82f4-f5a0-405b-97fb-d29cfb98cbf7,1c1711e8-f8d4-4b86-8b09-7af4b4094fc0' \
  -H 'cache-control: no-cache,no-cache,no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F client_id=h3czk93x9hxgvm8gnjzuckp5d5d7wcuraido15jsvdry2 \
  -F client_secret=Wz3bvfo4qSRH14iXc441xad9F122YA \
  -F grant_type=client_credentials

### _**Status 400:**_
curl -X POST \
  https://demo-accounts.vivapayments.com/connect/token \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic ZjQwZTE5YTYtNTE2MC00OTdmLThkZGYtMGQxZDY3Mzg3ZTE0OjhGajkzPw==' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: 04c21635-da65-4c9d-938e-520ae634a38a' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F client_id=h3czk93x9hxgvm8gnjzuckp5d5d7wcuraido15jsvdry2 \
  -F client_secret=Wz3bvfo4qSRH14iXc441xad9F122YA \
  -F grant_type=client_credentials

**Comment by matthewrgourd** [comment]
Hi @susaree, client id looks wrong (it should end in `.apps.vivapayments.com`. You can find this in **Settings > API access** in the Viva Wallet banking app at the below location:

![native-checkout-credentials](https://user-images.githubusercontent.com/44943019/97561083-854cd480-19d7-11eb-9f43-a44e811f9977.png)

**Comment by susaree** [comment]
Hi Matthew, thanks for your quick response.

I've changed to the correct client id and it's still throwing the same status, do you have a working curl I can use to test this api?

curl -X POST \
  https://demo-accounts.vivapayments.com/connect/token \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic W2gzY3prOTN4OWh4Z3ZtOGduanp1Y2twNWQ1ZDd3Y3VyYWlkbzE1anN2ZHJ5Mi5hcHBzLnZpdmFwYXltZW50cy5jb21dOltXejNidmZvNHFTUkgxNGlYYzQ0MXhhZDlGMTIyWUFd' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Postman-Token: 8faf64b7-3f52-4a5a-b14a-da025b5cc36c,217d82f4-f5a0-405b-97fb-d29cfb98cbf7,1c1711e8-f8d4-4b86-8b09-7af4b4094fc0,0908ce9d-ab21-4178-a812-855e9495e14d' \
  -H 'cache-control: no-cache,no-cache,no-cache,no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F client_id=h3czk93x9hxgvm8gnjzuckp5d5d7wcuraido15jsvdry2.apps.vivapayments.com \
  -F client_secret=Wz3bvfo4qSRH14iXc441xad9F122YA \
  -F grant_type=client_credentials

**Comment by susaree** [comment]
I took off the 'Authorization' header in Postman and it works now
