### ISSUE TITLE
How can I Send a Request about Get Viva Wallet TransactionDetailInfo?

### ISSUE THREAD

**Issue by went94** [VivaPayments/API#1943]
As title, I have got TransactionId right now, but I Send a Request about **https://demo.vivapayments.com/api/transactions/{Id}**, and I Received a Response about ErrorCode is 400, ErrorMessage is Bad Request.  I copied it according to the example in the document.
What parameters are required？

**Comment by matthewrgourd** [comment]
Hi @went94, sorry to hear this. Can you send me the transaction ID together with Merchant ID / API key for your demo account so I can test?

**Comment by went94** [comment]
> 
> 
> Hi @went94, sorry to hear this. Can you send me the transaction ID together with Merchant ID / API key for your demo account so I can test?

Hi @matthewrgourd, First of all， you replied to my Message.
Of course,  the Transaction ID is 52ffdd12-2807-494e-a09b-cb373562d8ee and the OrderCode is 2557872583807462, the Merchant ID is c8baa4e0-00e0-41d4-b8ac-5cc4236ca27c, API key is hI4q2b.

**Comment by went94** [comment]
Hi @matthewrgourd. First of all, I'm very Happly that you replied to my Message.
At the now time,I had following these problems：

1. Send a Request that Get the Viva Wallet Transaction Detail Information.
the parameters include the Transaction ID:52ffdd12-2807-494e-a09b-cb373562d8ee,  the OrderCode:2557872583807462, the Merchant ID:c8baa4e0-00e0-41d4-b8ac-5cc4236ca27c, the API key:hI4q2b;

2. I need to create Webhook. And I have received the error Information is "The url could't be verified."
url: **https://zoutvivawalletdev.utools.club/api/VivaWalletWebhook/Webhook_0A67B29D0CD2**
Or **http://zoutvivawalletdev.utools.club/api/VivaWalletWebhook/Webhook_0A67B29D0CD2**
(As the Document say that replaced Http with Https demo environment).

**Comment by matthewrgourd** [comment]
Hi @went94, regarding 1, you need to use basic auth to retrieve transaction details (see below screenshot).

![Screenshot 2020-11-02 at 08 38 02](https://user-images.githubusercontent.com/44943019/97847057-e7168280-1ce6-11eb-8d72-fd90774d0944.png)

Relevant pages in Viva Wallet Developer Portal:

https://developer.vivawallet.com/web-api-integration/payment-api/#section/Authentication
https://developer.vivawallet.com/web-api-integration/payment-api/#tag/Transactions

Regarding 2, please check https://developer.vivawallet.com/web-api-integration/webhooks/#webhook-url-verification. Does your website domain exist yet?

**Comment by went94** [comment]
> 
> 
> Hi @went94, regarding 1, you need to use basic auth to retrieve transaction details (see below screenshot).
> 
> ![Screenshot 2020-11-02 at 08 38 02](https://user-images.githubusercontent.com/44943019/97847057-e7168280-1ce6-11eb-8d72-fd90774d0944.png)
> 
> Relevant pages in Viva Wallet Developer Portal:
> 
> https://developer.vivawallet.com/web-api-integration/payment-api/#section/Authentication
> https://developer.vivawallet.com/web-api-integration/payment-api/#tag/Transactions
> 
> Regarding 2, please check https://developer.vivawallet.com/web-api-integration/webhooks/#webhook-url-verification. Does your website domain exist yet?

Hi@matthewrgourd.
Thanks for your Help,I had resolved these progroms.

**Comment by matthewrgourd** [comment]
Hi @went94 , good to hear. I'm closing this issue now but you can reopen if any further problems.

**Comment by went94** [comment]
Hi @matthewrgourd  Of curse. See you again.
