### ISSUE TITLE
Native payments with Viva Wallet problem on prestashop

### ISSUE THREAD

**Issue by maofree** [VivaPayments/API#1944]
Hi
Native payments with Viva Wallet option
the redirect works well on https://www.mondialshop.it but the other option no
"Native payments with Viva Wallet" should be the iframe that shop the payment form?
like paypal or payplug?

thanks

![1](https://user-images.githubusercontent.com/653230/97699307-31f78680-1aaa-11eb-8dd2-568e2ea186be.png)

**Comment by maofree** [comment]
hi
Have you done some tests on prestashop 1.7 with active that option?

**Comment by matthewrgourd** [comment]
Hi @maofree, if you're attempting to use our plugin for PrestaShop 1.7, please follow the installation instructions accurately:

https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/

- **Integration method** should be radio button on the left selected
- Success URL: `module/vivawallet/success`
- Failure URL: `module/vivawallet/fail`

**Comment by maofree** [comment]
hi

it is necessary to set
module/vivawallet/success
or
/module/vivawallet/success
?
![1](https://user-images.githubusercontent.com/653230/97853529-8001c980-1cf8-11eb-9d76-4026cbec3138.png)

**Comment by matthewrgourd** [comment]
Hi @maofree I believe it is the first option. Thanks.

**Comment by maofree** [comment]
hi
I've other two question:
1) can you explain me this option "native payment"?
![1](https://user-images.githubusercontent.com/653230/97854965-6792ae80-1cfa-11eb-8c62-fbfa61e90e45.png)


2) is it possible to integrate a popup with iframe payment? to avoid the redirect to your website and then a new redirect to return on our website? like for paypal and payplug?

thanks

**Comment by matthewrgourd** [comment]
Hi @maofree, the above option is for use with our [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/) solution only. This includes a button and iframe but if you want to use it with PrestaShop you'll need to integrate it yourself with that platform. At the moment our PrestaShop plugin supports only the [Redirect](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) option.

**Comment by maofree** [comment]
ok thanks
