### ISSUE TITLE
Simple Check out issues

### ISSUE THREAD

**Issue by PanosMusicMan** [VivaPayments/API#1945]
I raise an as requested ...
You are kindly requested to grand me the required privileges in order to proceed further.
Thank you in advance for your awareness looking forward to hearing from you soon.

**Comment by matthewrgourd** [comment]
Hi @PanosMusicMan, no problem. Please let me know your merchant ID if for demo, or website address if for live. Thanks.

**Comment by PanosMusicMan** [comment]
Good morning,

Site address: https://teemwiz.eu <https://teemwiz.eu/>
Merchant ID: 85980289-eddd-4827-88e0-75f3e45101f1

Thank you in advance for your awareness.

Have a nice day.

Regards,
Panos.

**Comment by matthewrgourd** [comment]
Hi @PanosMusicMan, that's done for you now.
