### ISSUE TITLE
Paiement Annulé à la dernière étape 

### ISSUE THREAD

**Issue by MJR-Julie** [VivaPayments/API#1946]
Bonsoir,
Des clients m'ont rapporté que à l'étape finale leurs paiements étaient refusés. 
J'ai fais un test et effectivement tout se déroule normalement jusqu'à la toute fin où un message vient pour dire que le paiement est refusé.
Peut-être un mauvais réglage de ma part ? 
ou une validation de votre côté que je n'ai pas eu ?
Je reste disponible à tout moment,
Merci par avance pour votre aide.
Bien cordialement,
Julie.

**Comment by matthewrgourd** [comment]
Hi @MJR-Julie, sorry to hear this. May I have your website address so I can investigate the issue?

**Comment by MJR-Julie** [comment]
Bonjour,
Peut-être était-ce mes réglages qui n'étaient pas bon car le problème à
l'air de s'être résolu... Je veux bien que vous vérifiez tout de même pour
être sûre que tout est correct. Merci par avance. Bien cordialement,, julie.

https://lebaronducbd.com/

Le lun. 2 nov. 2020 à 10:06, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @MJR-Julie, I just tested the redirect with a card with no funds and I can confirm that your checkout is working fine. Best regards.

**Comment by MJR-Julie** [comment]
Merci à vous.

Le lun. 2 nov. 2020 à 10:29, matthewrgourd <notifications@github.com> a
écrit :
