### ISSUE TITLE
The specified api action is disabled for the merchant ...

### ISSUE THREAD

**Issue by mrusciel** [VivaPayments/API#1947]
Hola, necesito habilitar el pago simple en mi cuenta demo, me pueden ayudar?

Este es la respuesta que recibo: The specified api action is disabled for the merchant bdd31447-03d9-4a0d-894f-fd7604ea9ddc

**Comment by matthewrgourd** [comment]
Hi @mrusciel, I've enabled Simple Checkout for you in the demo environment.

**Comment by mrusciel** [comment]
Thank you, very much.
