### ISSUE TITLE
Create Order > PHP > ERROR: Order Not Found

### ISSUE THREAD

**Issue by PanagiotisChKollas** [VivaPayments/API#1948]
Yπάρχει πρόβλημα στην αποδοχή πληρωμών μέσω redirection : Order not found
![kodikas](https://user-images.githubusercontent.com/49236730/97810596-a8001700-1c7d-11eb-95f0-0b846e4dc059.png)
![pigi](https://user-images.githubusercontent.com/49236730/97810598-ab939e00-1c7d-11eb-9bc2-c5516d8c6126.png)
![error](https://user-images.githubusercontent.com/49236730/97810599-adf5f800-1c7d-11eb-822d-f17faa285b55.png)

**Comment by matthewrgourd** [comment]
Hi @PanagiotisChKollas, sorry to hear you're experiencing issues in what looks to be an attempted implementation of our [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/). Is that correct? I'm not sure about your custom code in the first screenshot. However, here is a working example in PHP cURL:
```
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://demo.vivapayments.com/api/orders",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS =>"{\n  \"actionUser\": \"name\",\n  \"Tags\": [\n    \"sample string 1\",\n    \"sample string 2\",\n    \"sample string 3\"\n  ],\n  \"Email\": \"customer@example.com\",\n  \"Phone\": \"07967813180\",\n  \"FullName\": \"Customer Name\",\n  \"PaymentTimeOut\": 86400,\n  \"RequestLang\": \"en-GB\",\n  \"Source\": \"Default\",\n  \"maxInstallments\": 1,\n  \"AllowRecurring\": true,\n  \"Amount\": 100,\n  \"MerchantTrns\": \"123\",\n  \"CustomerTrns\": \"Description that the customer sees\"\n}",
  CURLOPT_HTTPHEADER => array(
    "Content-Type: application/json",
    "Authorization: Basic ZTc1ZmZmNDMtNWM5Zi00YWE2LTljZjEtODZhZmRkZWE4MjA0OmV0UzdrMw=="
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
```
Regarding the payment source settings, you're using an IP address rather than a domain name. I'm afraid that won't work. It has to be a domain name. Please see https://developer.vivawallet.com/e-commerce-plugins/create-a-payment-source/#redirect-checkout for further info.

**Comment by PanagiotisChKollas** [comment]
Thanks for your reply !
So your sample code here --> https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php dosn't works !!

**Comment by matthewrgourd** [comment]
Hi @PanagiotisChKollas, apologies if that's the case. I'll get one of our developers to check it.

**Comment by PanagiotisChKollas** [comment]
Just a simple pay via redirection method

**Comment by matthewrgourd** [comment]
Ok, so relevant page is https://developer.vivawallet.com/online-checkouts/redirect-checkout/

**Comment by PanagiotisChKollas** [comment]
With the above code , when i am trying to get the order code ( $response->OrderCode; )  i receive the code with wrong format -> 8.97948831257E+15 .

**Comment by PanagiotisChKollas** [comment]
The bellow code works fine 

if(is_object(json_decode($response))){
  **$resultObj =json_decode($response, false, 512, JSON_BIGINT_AS_STRING);
  $ErrorCode = $resultObj->{'ErrorCode'};
  $OrderCode = $resultObj->{'OrderCode'};**
  
  if ($ErrorCode == 0) {
    $viva_url = "https://demo.vivapayments.com/web/checkout/?ref=$OrderCode";
    echo "<script>window.location = '$viva_url'</script>";
  } else {
    echo "oups";
  }
} else {
  echo "oups";
}

**Comment by matthewrgourd** [comment]
Hi @PanagiotisChKollas, that's great news. Thanks for letting us know your solution!
