### ISSUE TITLE
Add the "back to site" on the payment page

### ISSUE THREAD

**Issue by maofree** [VivaPayments/API#1949]
Hi
I'm using your module on prestashop 1.7
can you add the "back to site" on the payment page of your website?
because at this moment it is not present a button to return to the website in the case the customer is not interested to pay with the virtual pos of viva wallet.

thanks

**Comment by matthewrgourd** [comment]
Hi @maofree, ok, I will add as a feature request, but I don't know when this will be rolled out to our plugin.

**Comment by maofree** [comment]
hi
I don't think there are major changes to be made
I imagine it is enough to pass the language iso code in the redirect url from prestashop to the page of the checkout, and then set it as the base language also in the checkout

**Comment by matthewrgourd** [comment]
Hi there, our plugin is open source so please feel free to make any modifications if you have the technical knowledge. However, as I say, I've added as a feature request so it will be looked at, I just can't tell you a date right now. Apologies for any inconvenience caused.

**Comment by maofree** [comment]
hi
I think it is not possible to add a button under the payment form on your website directly from the module
