### ISSUE TITLE
italian language for prestashop 1.7 module

### ISSUE THREAD

**Issue by maofree** [VivaPayments/API#1951]
Hi
I've translated the texts of the module for prestashop 1.7

[it.zip](https://github.com/VivaPayments/API/files/5475110/it.zip)

**Comment by matthewrgourd** [comment]
Hi @maofree, that's very good of you. Let me see if one of our developers can incorporate this into the source files and send you a patch.

**Comment by maofree** [comment]
it is only necessary to put the txt file inside the language folder
bye

**Comment by matthewrgourd** [comment]
Ok, thanks very much, we've done that for you, please install the ZIP file below (and the checkout will default to Italian as requested in #1950 which I'm closing now).

[prestashop1.7.zip](https://github.com/VivaPayments/API/files/5475527/prestashop1.7.zip)

**Comment by maofree** [comment]
Hi
I've fixed the problem about the switch between the languages, now it takes the same language selected from the website automatically, if the language is among those managed by you.

`	$allowed_languages = array('de', 'nl', 'en', 'fr', 'it', 'el', 'pl', 'pt', 'ro', 'es');
	$language_by_iso_code = strtolower(Language::getIsoById($cookie->id_lang));
			
	if(in_array($language_by_iso_code, $allowed_languages)){
	    $languagecode = Language::getLocaleByIso($language_by_iso_code);
	} else {
	    $languagecode ='en-US';
	}`

[vivawallet.zip](https://github.com/VivaPayments/API/files/5479939/vivawallet.zip)

I've already tested it on mondialshop.it
bye

**Comment by matthewrgourd** [comment]
Hi @maofree, that's great! Thanks for letting us know your solution.

**Comment by trischitti** [comment]
Salve,


> Hi
> I've fixed the problem about the switch between the languages, now it takes the same language selected from the website automatically, if the language is among those managed by you.
> 
> ` $allowed_languages = array('de', 'nl', 'en', 'fr', 'it', 'el', 'pl', 'pt', 'ro', 'es');
> $language_by_iso_code = strtolower(Language::getIsoById($cookie->id_lang));
> 
> ```
> if(in_array($language_by_iso_code, $allowed_languages)){
>     $languagecode = Language::getLocaleByIso($language_by_iso_code);
> } else {
>     $languagecode ='en-US';
> }`
> ```
> 
> [vivawallet.zip](https://github.com/VivaPayments/API/files/5479939/vivawallet.zip)
> 
> I've already tested it on mondialshop.it
> bye

Hi,
I have the same problem as you so I tried to install the zip file you attached, but prestashop (version 1.7) does not install it!
system error says: Ooops ... Failed to load - This file does not appear to be a valid zip module

can you help me? Thanks

**Comment by maofree** [comment]
Hi
that zip as only the main php file of the module so you need to install prestashop1.7.zip before and than upload the vivawallet.php in the module folder using filezilla
modules/vivawallet/

bye
