### ISSUE TITLE
Enable instalments

### ISSUE THREAD

**Issue by kapamarou** [VivaPayments/API#1952]
Hi do i enable instalments on the new plugin ?

**Comment by matthewrgourd** [comment]
Hi @kapamarou, which plugin are you referring to? We have plugins for all the major e-commerce [platforms](http://localhost:1313/e-commerce-plugins/#all-platforms).

**Comment by kapamarou** [comment]
i am sorry woocommerce

**Comment by matthewrgourd** [comment]
Hi @kapamarou, I'm afraid instalments aren't currently available for our WooCommerce plugin. However, support for [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions) is coming soon if that's any use to you?

**Comment by kapamarou** [comment]
Ιs there any guide i can follow in order to enable them ? You use any specific variable ?

**Comment by matthewrgourd** [comment]
There is no such functionality at present, but it should be available in the next few weeks.

**Comment by matthewrgourd** [comment]
Hi @kapamarou, my apologies, I think I misunderstood you. Instalments are available but you need to have a Viva Wallet account set up in Greece and using the Euro currency. Does this apply to you? If it does, you will see an additional field in your payment module settings:

![Screenshot_2020-11-02_at_6_31_48_PM](https://user-images.githubusercontent.com/44943019/97894037-ed7a1e00-1d29-11eb-979f-90d5b8182e85.png)

If configured, customers will be given the option at checkout:

![Screenshot 2020-11-02 at 6 37 22 PM](https://user-images.githubusercontent.com/44943019/97894170-1bf7f900-1d2a-11eb-918b-3d779f70ba62.png)
