### ISSUE TITLE
interface module

### ISSUE THREAD

**Issue by Areatoner** [VivaPayments/API#1953]
Hello
I would like to know if it is possible to interface your API with the Ready Pro management system
(https://www.readypro.it/software-gestionale)
thanks

**Comment by matthewrgourd** [comment]
Hi @Areatoner, I assume you mean specifically the [e-commerce](https://www.readypro.it/gestionale-integrato-ecommerce) component of that platform? No, we don't have an off-the-shelf payment plugin available, I'm afraid. Under "Credit card payment management" I see the following options are supported:

- Sella Bank
- Paysite-cash from NORDPAY
- Bankpass Web
- Triveneto Consortium
- Keyclient / CIM Italy
- Paypal
- Skrill / Moneybookers
- e-GIPSy
- IPG
- e-POSitivity
- IWSmile
- Pagonline
- SOAR
- Raiffeisen
- X-pay
- @POS
- Agos
- Rate-in-Net

You could ask them if they have an API for integrating with a custom payment solution, but beyond that I'm not sure what to suggest. Do you have development skills?
