### ISSUE TITLE
Simple checkout: question on the button style

### ISSUE THREAD

**Issue by IleaBrussels** [VivaPayments/API#1954]
Hello,

How can I change the height, width and the font of the "Pay" button to match the design of my online shop? I can't find relevant parameters on the Simple checkout page.

If it's not possible to change the font, then please provide the name of the font used for the "Pay" button in order I could align the font of another button located on the same page.

**Comment by matthewrgourd** [comment]
Hi @IleaBrussels, the styling settings are limited to the following within the [Configuration options](https://developer.vivawallet.com/online-checkouts/simple-checkout/#configuration-options):

data-vp-background-color | Sets button’s background colour. Default value: #030408. | Recommended
-- | -- | --
data-vp-color | Sets button’s text colour. Default value: #fff. | Recommended
data-vp-hover-background-color | Sets button’s background colour on mouse over. Default value: #1a2242. | Recommended
data-vp-hover-color | Sets button’s text colour on mouse over. Default value: #fff. | Recommended
data-vp-border-radius | Sets button’s roundness. Default value: 10px. | Recommended
data-vp-text | Sets button’s text. Default value: Pay (when data-vp-lang="en"). | Recommended

Font is Arial, 14px.

If you're confident about editing JS files there are some further settings in https://www.vivapayments.com/web/checkout/js but you'd need to host your own copy of the file before making any changes (and update its reference in the HTML of your payment page).

**Comment by IleaBrussels** [comment]
Hi, 

Thank you. Could you please also send me the width and the height of the button?
Best regards

    On Tuesday, November 3, 2020, 10:54:05 AM GMT+1, matthewrgourd <notifications@github.com> wrote:  
 
 


Hi @IleaBrussels, the styling settings are limited to the following within the Configuration options:

| data-vp-background-color | Sets button’s background colour. Default value: #030408. | Recommended |
| data-vp-color | Sets button’s text colour. Default value: #fff. | Recommended |
| data-vp-hover-background-color | Sets button’s background colour on mouse over. Default value: #1a2242. | Recommended |
| data-vp-hover-color | Sets button’s text colour on mouse over. Default value: #fff. | Recommended |
| data-vp-border-radius | Sets button’s roundness. Default value: 10px. | Recommended |
| data-vp-text | Sets button’s text. Default value: Pay (when data-vp-lang="en"). | Recommended |


Font is Arial, 14px.

If you're confident about editing JS files there are some further settings in https://www.vivapayments.com/web/checkout/js but you'd need to host your own copy of the file before making any changes (and update its reference in the HTML of your payment page).

**Comment by matthewrgourd** [comment]
Hi @IleaBrussels, I believe it's 65px x 37px.
