### ISSUE TITLE
ARCOINX

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1955]
Good morning @matthewrgourd! this merchants seems to have some problems with his payment gateway, he is using prestashop, Could you check it?

![MicrosoftTeams-image (26)](https://user-images.githubusercontent.com/56823712/97959421-a2a2e980-1daf-11eb-9124-0faab254d3a3.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, his settings are wrong. Please get him to check step 5 of the installation guide for whichever version of PrestaShop he's using:

- [PrestaShop 1.5-1.6](https://developer.vivawallet.com/e-commerce-plugins/prestashop1.5-1.6/)

- [PrestaShop 1.7](https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/)

Radio button selected for "Integration method" for both versions of the plugin should be the first one (on the left) as below:

![NewPaymentSource](https://user-images.githubusercontent.com/44943019/97969383-e3066580-1db7-11eb-8bae-ff42be8a2eda.png)

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant asks me about this:

´´I need to make automatic refunds from my website, *which is made in PHP and does not use any CMS.* 
The payment method we are trying is *Simple Checkout.* 
What I need is that yes, you can help me with a sample code to make the refund request to the API´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada please get the developer to consult our documentation, specifically the [Cancel transaction](https://developer.vivawallet.com/web-api-integration/payment-api/#tag/Transactions/paths/~1api~1transactions~1{Id}/delete) page. An example is shown in the screenshot below:

![Screenshot 2020-11-07 at 09 02 27](https://user-images.githubusercontent.com/44943019/98653581-1bb4ba80-2335-11eb-8fbe-c3218fb5ec02.png)
