### ISSUE TITLE
Code informatica

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1956]
Hi @matthewrgourd Could you indicate me what merchant has to write down in the below fields, he is using prestashop 1.765

![image001](https://user-images.githubusercontent.com/56823712/97968732-5790d280-1dbf-11eb-87c0-98d99460b8af.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I've checked their Merchant ID and it looks like this is the one used in production so they need to change Base URL from `https://demo.vivapayments.com` to `https://www.vivapayments.com`.

**Comment by Alvaroalconada** [comment]
Thx Matt, great and what about of source code?

**Comment by matthewrgourd** [comment]
From the documentation: 

> Code – the four-digit number in the top-left of the dialog box is the ‘Source Code’. Make a note of it for use in your plugin.

**Comment by Alvaroalconada** [comment]
@matt Could you indicate me which four digit number, sorry

**Comment by matthewrgourd** [comment]
The merchant first needs to set up a new payment source as outlined in the [documentation](http://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/#step-1-create-a-payment-source). This will give them a four-digit number to add to their payment module settings. I've checked and they've not done that part yet.
