### ISSUE TITLE
About The Cancel Transaction question

### ISSUE THREAD

**Issue by went94** [VivaPayments/API#1957]
Hi @matthewrgourd.
As Title,I Send a Request that use Basic Authorization. 
**https://demo.vivapayments.com/api/transactions/2d79b549-85f4-4a65-9e36-7e648d509b0e**

Method of DELETE.
As the example in the document,Get 400 Respone Code.
I tried to pass values in two ways. As the Image:
![图片](https://user-images.githubusercontent.com/45383633/97984313-90f22e00-1e11-11eb-96d8-f63678681438.png)
function 2:
![图片](https://user-images.githubusercontent.com/45383633/97984403-b3844700-1e11-11eb-9f02-87785b4a2ae8.png)

**Comment by matthewrgourd** [comment]
Hi @went94, have you [enabled refunds](https://developer.vivawallet.com/e-commerce-plugins/ensure-refunds-are-enabled/) in the Viva Wallet banking app?

**Comment by went94** [comment]
Hi @matthewrgourd. 
Yes. I set.  And the deal was created Today.
![图片](https://user-images.githubusercontent.com/45383633/97995284-47114400-1e21-11eb-96f5-1c8ed7d8ff30.png)

**Comment by matthewrgourd** [comment]
Hi @went94, I see that the original transaction amount was for £60. Before funds have cleared, only a cancellation of the full amount is allowed. Partial refunds are enabled once funds have cleared (after midnight, on the same day, approximately...)

**Comment by went94** [comment]
Ah, I've got it that the Viva Wallet arrived the next day in Beijing Time.

**Comment by matthewrgourd** [comment]
Hi @went94 did you try to refund exact amount (£60). I can't see that in the examples you gave?

**Comment by went94** [comment]
> 
> 
> Hi @went94 did you try to refund exact amount (£60). I can't see that in the examples you gave?

**Comment by went94** [comment]
> 
> 
> Hi @went94 did you try to refund exact amount (£60). I can't see that in the examples you gave?

Yeah,
![图片](https://user-images.githubusercontent.com/45383633/98000249-454a7f00-1e27-11eb-90c0-686f9b9880bd.png)
I use the Content-Type of application/json pass values.
Can I use the wrong way to pass values?
Could I

**Comment by went94** [comment]
> 
> 
> Hi @went94 did you try to refund exact amount (£60). I can't see that in the examples you gave?

Yeah,
![图片](https://user-images.githubusercontent.com/45383633/98000249-454a7f00-1e27-11eb-90c0-686f9b9880bd.png)
I use the Content-Type of application/json pass values.
Can I use the wrong way to pass values?

**Comment by LoggiaNG** [comment]
We have the same issue.
We have tried the same ways to pass the "amount" parameter but we always get "Negative or zero amount in reversal" with "Amount": null in the response.

Please advise, thank you

**Comment by matthewrgourd** [comment]
Hi @LoggiaNG the amount is in body which is not supported in http delete. It should instead be included as a query string after the transaction ID in the URL (see below):

![Screenshot 2020-11-07 at 09 02 27](https://user-images.githubusercontent.com/44943019/98535948-d9c93d00-227e-11eb-85c5-43dc2fd19358.png)

Hope this helps!

**Comment by LoggiaNG** [comment]
Thanks, this works now.
It should be clearer in the documentation, not everyone is well-versed in http methods/parameters...
