### ISSUE TITLE
Error 500 on test environment with 3D page (threedsecurevalidation)

### ISSUE THREAD

**Issue by yairpe** [VivaPayments/API#1958]
I'm using native checkout v2

It used to work fine with the 3D simulation and success/failure option.

Now there's an issue on viva page - https://demo.vivapayments.com/web/checkout/threedsecurevalidation

When I try to test my payment page in test mode, after typing the card details (4111111111111111 11/22 111), the 3D iframe opens with an error message 
`Server Error in '/web' Application.
Runtime Error`

See screenshot
![3d_test_issue](https://user-images.githubusercontent.com/8095933/97997938-6ab49a00-1de1-11eb-9dd5-ca246011ee87.png)

**Comment by matthewrgourd** [comment]
Hi @yairpe, I'm checking for you, will send an update soon.

**Comment by mediamorphoseBe** [comment]
Same problem here

**Comment by matthewrgourd** [comment]
Hi @yairpe, we have temporarily disabled the 3DS simulation. Can you let me know what happens if you try again now?

**Comment by matthewrgourd** [comment]
@mediamorphoseBe, sorry to hear that. Please share with me any response logs or screenshots that will show me the error(s) you're receiving.

**Comment by mediamorphoseBe** [comment]
The problem has been fixed. Thx!
