### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by orestis-s** [VivaPayments/API#196]
Καλησπέρα

Υπάρχει δυνατότητα στη διασύνδεση native checkout, να παίρνουμε περισσότερες λεπτομέρειες σχετικά με το σφάλμα transaction failed (π.χ. μη επαρκές υπόλοιπο);

Ευχαριστώ εκ των προτέρων

**Comment by defilerc** [comment]
Καλημέρα @orestis-s ,

Στις περιπτώσεις που ο χρήστης πληρώνει με viva wallet, υπάρχει ειδικό error code το οποίο έρχεται από το API και υποδηλώνει insufficient funds (Error Code: 452).

Στις περιπτώσεις που ο χρήστης πληρώνει με credit card, τότε το response έρχεται από την εκάστοτε τράπεζα και έτσι δεν υπάρχει δυνατότητα για κάποιο συγκεκριμένο error code, καθώς η κάθε τράπεζα δεν επιστρέφει πάντα πληροφορία για το λόγο που απορρίφθηκε η συναλλαγή.

Με εκτίμηση,

**Comment by orestis-s** [comment]
Καλώς

Ευχαριστώ
