### ISSUE TITLE
Bad Request Refund Transaction

### ISSUE THREAD

**Issue by went94** [VivaPayments/API#1960]
Hi @matthewrgourd .
Yeah,
![图片](https://user-images.githubusercontent.com/45383633/98000249-454a7f00-1e27-11eb-90c0-686f9b9880bd.png)
I use the Content-Type of application/json pass values.
Can I use the wrong way to pass values?

**Comment by matthewrgourd** [comment]
Hi @went94, not sure, let me check something first. Can you send me the Merchant ID for your demo account?

**Comment by went94** [comment]
> 
> 
> Hi @went94, not sure, let me check something first. Can you send me the Merchant ID for your demo account?

Hi @matthewrgourd.
Of curse.
The Demo Account's Merchant ID:5287ffd9-7361-4ffd-a63a-8b5312d2916f
APIKey: 9Vr%9;
AccountID:34801199
I‘m’ waitting for your good news!

**Comment by matthewrgourd** [comment]
Hi @went94, I'm getting the same issue. I will need to speak to our dev team and get back to you. Sorry for the delay!

**Comment by went94** [comment]
> 
> 
> Hi @went94, thanks for providing that info. I'm getting the same issue. I will need to speak to our dev team and get back to you. Sorry for the delay!

Hi @matthewrgourd ,
At the  now time,I Met a New Problem.
I use Card Payment to create a transaction,And I received a Bad Request.
As the Image:
![图片](https://user-images.githubusercontent.com/45383633/98239440-ee69b480-1fa2-11eb-9373-a1591e56a29f.png)

My Steps is:
First,I get AccessToken;
Next,I get ChargeToken pass CardToken;
Finally,I received the Bad Request.
I wish to your reply!
Thanks

**Comment by matthewrgourd** [comment]
Hi @went94, for your first issue, I'm still checking for you. Regarding your second issue, can you replace [access-token] in the below HTML code sample with the one you generated then open in a browser. Click on **Generate charge token** to create the charge token which you then pass as a body parameter when you do your POST `https://api.vivapayments.com/nativecheckout/v2/transactions` call.

[generate-charge-token.txt](https://github.com/VivaPayments/API/files/5495185/generate-charge-token.txt) (rename as "generate-charge-token.html" once downloaded, edited and saved)

**Comment by went94** [comment]
Hi @matthewrgourd ,
As you say,I need to get charge token  by access token,Then, use to generate ChargeToken to create the ChargeToken？

**Comment by matthewrgourd** [comment]
Hi @went94 to generate a card token from a charge token see [Step 2: Generate card token using the charge token](https://developer.vivawallet.com/web-api-integration/card-tokenization-api/#step-2-generate-card-token-using-the-charge-token-optional) on our Card Tokenization page. You can then generate as many charge tokens as you want from the card token (see [Step 3: Generate one-time charge token using card token](https://developer.vivawallet.com/web-api-integration/card-tokenization-api/#step-3-generate-one-time-charge-token-using-card-token-optional)). Hope his helps!

**Comment by went94** [comment]
Hi @matthewrgourd ,
If Escrow Account's Viva Wallet don't have enough money,
What can I receive message that transfer money to other Account?
Response Code 403 Unkonwn?

**Comment by matthewrgourd** [comment]
Hi @went94, I believe we have a technical representative from Viva Wallet dealing with you directly. Can you confirm that? If so, please speak to them about the specifics of your case as they will know the answers better.

**Comment by went94** [comment]
Hi @matthewrgourd ,
![图片](https://user-images.githubusercontent.com/45383633/98359308-fbe67380-2062-11eb-9ce1-87dc6f856c9b.png)
![图片](https://user-images.githubusercontent.com/45383633/98359449-38b26a80-2063-11eb-9115-5982a19f3405.png)

**Comment by matthewrgourd** [comment]
Hi @went94, I'm not sure, please send this last query directly to your technical contact at Viva Wallet. Regarding the cancel transaction functionality, I have this reply:

CASE 1

![CASE1](https://user-images.githubusercontent.com/44943019/98378912-92546e00-203e-11eb-8ad6-8878b5b59e53.jpg)

The amount is in body which is not supported in http delete.

CASE 2

![CASE2](https://user-images.githubusercontent.com/44943019/98378932-984a4f00-203e-11eb-90b8-c33df89cc562.jpg)

Amount is correctly included as query string but you have spaces ...... ?amount=100

**Comment by matthewrgourd** [comment]
Hi @went94, an example of a cancellation of a transaction for the amount of £1 would be as follows:

DELETE `https://demo.vivapayments.com/api/transactions/8bd78517-d0d0-4c90-8144-7e5279f5e1e8/?amount=100`

Hope this helps..
