### ISSUE TITLE
Simple checkout: question on Step 2 Make the charge

### ISSUE THREAD

**Issue by IleaBrussels** [VivaPayments/API#1961]
Hello,

On the Simple checkout page https://developer.vivawallet.com/online-checkouts/simple-checkout/ 
there is Step 2 Make the charge. It is stated there:

"Response example
If the cardholder’s authentication was successful and all other requirements met (e.g. account has enough balance etc.) then you should receive a response containing the charge’s transactionId:..."

It is not explained however what happens if a payment failed (e.g. 3DS check failed or the bank refused the payment due to  insuffucient account balance). From testing it looks like in case of failure Viva Wallet does not provide any response, hence it is not possible to display a page on my website that tells to a cutomer that his order could not be paid.

Is my understanding correct or there is a possibility to get a negative response in case of payment failure?

**Comment by matthewrgourd** [comment]
HI @IleaBrussels, I'm checking with our dev team. I'll update you soon.

**Comment by matthewrgourd** [comment]
Hi @IleaBrussels, I'm told by our development team that our Simple Checkout is fairly limited in terms of the responses available from the API. For a newer solution, please integrate with [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) instead. Thanks.

**Comment by IleaBrussels** [comment]
Hi,It looks like only the demo version is limited. The live version works well. It is inconvenient to have different behavior of live and demo versions, as while developing with demo we don't know what to expect in live. The demo must be the same as live. With the demo version we couldn't test the insufficient funds scenario, that turned to work with the live version. The demo version, nor documentation provide a clear view on how simple checkout works. But testing in live is a bad solution too.The difference between live and demo caused wasting time on testing scenarios that didn't work in demo.Hope this will be fixed.

Отправлено из Yahoo Почты для Android 
 
  вт, 24 нояб. 2020 в 9:40 matthewrgourd<notifications@github.com> написал(-а):   


Hi @IleaBrussels, I'm told by our development team that our Simple Checkout is fairly limited in terms of the responses available from the API. For a newer solution, please integrate with Native Checkout v2 instead. Thanks.

**Comment by matthewrgourd** [comment]
Hi @IleaBrussels, thank you for the feedback. I will pass on to our dev team. Apologies for any inconvenience caused.
