### ISSUE TITLE
Woocommerce Plugin error

### ISSUE THREAD

**Issue by jayvicson** [VivaPayments/API#1962]
The Woocommerce plugin documentation is out of date and not relevant to the user interface.
2.
I am getting errors 
Fatal error: Uncaught Exception: Unable to reach Viva Payments (Unauthorized) in /srv/users/fog/apps/4og/public/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php:310 Stack trace: #0 /srv/users/fog/apps/4og/public/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php(428): WC_VIVAWALLET->generate_form(396) #1 /srv/users/fog/apps/4og/public/wp-includes/class-wp-hook.php(287): WC_VIVAWALLET->receipt_page(396) #2 /srv/users/fog/apps/4og/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #3 /srv/users/fog/apps/4og/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #4 /srv/users/fog/apps/4og/public/wp-content/plugins/woocommerce/templates/checkout/order-receipt.php(44): do_action('woocommerce_rec...', 396) #5 /srv/users/fog/apps/4og/public/wp-content/plugins/woocommerce/includes/wc-core-functions.php(344): include('/srv/users/fog/...') #6 /srv/users/fog/apps/4og/public/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(208): wc_ in /srv/users/fog/apps/4og/public/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php on line 310

There has been a critical error on your website.

**Comment by matthewrgourd** [comment]
Hi @jayvicson the [Viva Wallet WooCommerce gateway](https://wordpress.org/plugins/vivawallet-woocommerce-gateway/) has been superseded by [Viva Wallet for WooCommerce](https://woocommerce.com/products/viva-wallet-for-woocommerce/), an enhanced native plugin for Woo hosted directly on the Woo platform. Please remove the previous extension (which is no longer maintained) and install the new one by following the installation instructions here:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
