### ISSUE TITLE
Nordicsweet

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1963]
Hi @matthewrgourd! I have the next problem with the merchant: 

Waiting for your answer to see if I could have the shopify checkout without an external checkout I installed the external checkout to see if everything was working correctly. 
I have placed a test order (the shop I have now is in Polish) and I am selling with the currency from there. I have placed an order for 1 Euro which is 4.57 ZL in Polish currency. And I have been charged 4.57 Euro as I do to be charged in the currency of each country?

![MicrosoftTeams-image (28)](https://user-images.githubusercontent.com/56823712/98013652-ebcc5b00-1dfa-11eb-8e07-b6fd799db6b4.png)
![MicrosoftTeams-image (29)](https://user-images.githubusercontent.com/56823712/98013681-f4249600-1dfa-11eb-813b-dd674ee00442.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, the redirect checkout option is what we have available for our Shopify plugin. We don't currently have a native version but there may be one in the future. Regarding currency selected for payment, this always has to be the currency of the merchant's Viva Wallet account. Then the [currency](https://developer.vivawallet.com/e-commerce-plugins/shopify/#store-currency) in the Shopify settings also has to be set to this. Does that answer your questions? If so, please close this issue. Thanks!
