### ISSUE TITLE
The issue with 3DS on mobile devices not solved yet!!!

### ISSUE THREAD

**Issue by Diavlos** [VivaPayments/API#1964]
Hello @matthewrgourd,

A month ago I wrote to you about the issue we have on 3DS confirmation form. [Issue #1871](https://github.com/VivaPayments/API/issues/1871). The problem still exists. You told me that you will change 3DS provider soon, but it is still the same and the problem not gone. Many customers trying to pay and they cannot finish the payment because of that problem. 

I started a new project which will have hundreds of payments  per day, and I really don't know what to do with payments on mobile devices. Only desktop and tablet screens are acceptable. Could you help to solve the problem fast or I need to start looking for new online payment provider.

Before you answer to my question, please read the old issue first. [Issue #1871](https://github.com/VivaPayments/API/issues/1871). I'm explaining that the problem is not coming from us, but from bad css (not responsive) of Modirum.

Regards

**Comment by matthewrgourd** [comment]
Hi @Diavlos, ok, sorry I should have kept the other issue open. I will reopen and update you once I've spoken to our dev team. We're still using Modirum, but I will re-iterate the problems you've been facing and see what they have to say.

**Comment by matthewrgourd** [comment]
Can you just confirm for me which Viva checkout solution you're using. Is it [Native](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) Checkout?

**Comment by Diavlos** [comment]
No, it's a Redirect method. Please, I need a solution ASAP.

**Comment by matthewrgourd** [comment]
Hi @Diavlos, I've tested on mobile using the redirect method and can replicate the issue. I'm afraid I didn't fully understand the problem before as I'd assumed you were using our latest Native Checkout v2 solution. I've tested with the latter and the problem doesn't seem to occur. Please see documentation below if you want to try that route:

https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

**Comment by Diavlos** [comment]
I need to use it with the Redirect. This is a simple solution for me and I can better implement it on our mobile app easy. The code is ready. Don't know  how long will take for me to develop the payment with a native checkout 2. Even I don't know if it will work, because there is no URL to redirect after the payment. As I wrote in the previous issue, there is a way to implement custom CSS to the Modirum 3ds form so the problem will be fixed.  Check it please. I could help you if needed.
Regards.

**Comment by matthewrgourd** [comment]
Hi @Diavlos, I understand what you're saying and I'm sorry for any inconvenience caused. Obviously you want to stick with the checkout solution you've already adopted. FYI, I've replied on the other ticket. I should have an update soon from our front-end team. If you don't mind I'll close this issue as I've re-opened the other one. Rest assured I've communicated your concerns in full to our dev team. Thank you!

**Comment by Diavlos** [comment]
Hello @matthewrgourd.  Look, the problem is that the redirect method was implemented on our website, but also in our apps (Android and iOS). So do you understand how much work I have to do to change to the native checkout v2 method? And it is not only me using this method, and the method has a problem as you saw too. Also I'm not 100% sure that if I implement this method, it will work well. The problem can be solved by doing some small custom CSS changes to the 3ds, and it is possible as  described in Modirum page. Why your developers don't do this changes? It will solve the problem globally. Regards.

**Comment by matthewrgourd** [comment]
Hi @Diavlos, I've chased our dev team today and this is still in progress. I'll update you soon.

**Comment by matthewrgourd** [comment]
Hi @Diavlos, our 3DS provider for issuing has now been updated from Modirum. Hope this helps.

**Comment by Diavlos** [comment]
Yes, there is no problem at the moment, as I've tested on some devices. Thanks.
