### ISSUE TITLE
Creating QuickPay link Error

### ISSUE THREAD

**Issue by HarishankarIT** [VivaPayments/API#1966]
Hi,

while creating a quick pay link I am getting an error called "An error occurred. Please try again later".And please inform me about API related to quick pay.
Please let us know asap. 
Merchant ID : 5e8d6a84-d20c-485e-a085-354b2a54473e

Regards,
HariIT

**Comment by matthewrgourd** [comment]
Hi @HarishankarIT, you've given me your demo merchant ID. Have you tried Quick Pay from your live account? It could be that the issue occurs only on demo as you can't receive real payments from there.

**Comment by HarishankarIT** [comment]
hi, @matthewrgourd In my live account never tried. for testing, I tried in the Demo account. I want to know API related to quick pay.
please let us know.

**Comment by matthewrgourd** [comment]
Hi @HarishankarIT, unfortunately there is no API for Quick Pay currently. You should try on live.
