### ISSUE TITLE
Antonio Cano Morales

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1967]
Hi @matthewrgourd could you tell me the currently status of this merchant, he is using IONOS, he sent me several screenshots for guiding him to implement payment gateway. Could you help me?

![MicrosoftTeams-image (30)](https://user-images.githubusercontent.com/56823712/98226437-50e89380-1f56-11eb-82ee-a3ad31358aa4.png)
![MicrosoftTeams-image (31)](https://user-images.githubusercontent.com/56823712/98226454-5514b100-1f56-11eb-9d62-e87ad54426d1.png)
![MicrosoftTeams-image (32)](https://user-images.githubusercontent.com/56823712/98226458-57770b00-1f56-11eb-84a0-cc356ee3cf55.png)
![MicrosoftTeams-image (33)](https://user-images.githubusercontent.com/56823712/98226461-59d96500-1f56-11eb-8b04-471d7a4227af.png)
![MicrosoftTeams-image (34)](https://user-images.githubusercontent.com/56823712/98226469-5cd45580-1f56-11eb-93fd-ab99d9c8ab35.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, if "Viva Wallet" is not listed in the dropdown you're showing me there from IONOS, unfortunately it means that the merchant won't be able to integrate with us.
