### ISSUE TITLE
vapeNorte

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1968]
Hi @matthewrgourd! this merchant complains me that doesn´t redirect the payment to the web, he is using woocommerce, Could you check it the currently status and if it´s well configurated? thx
![MicrosoftTeams-image (35)](https://user-images.githubusercontent.com/56823712/98238323-8301f180-1f66-11eb-98f2-e876c21798ff.png)
![MicrosoftTeams-image (36)](https://user-images.githubusercontent.com/56823712/98238659-058ab100-1f67-11eb-8444-1722a595c3ba.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I've checked and they seem to be using the old redirect version of our plugin. They should install the latest version by following our guide. Please note that the payment source settings will be generated automatically. 

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

During my tests, I noticed that they made "NIF number: a mandatory field at checkout. I think it should be optional because not everyone will want to provide that level of personal information.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd this merchant tells me the next:

As we mentioned on the phone, here are some screenshots of the configuration:

![foto 1](https://user-images.githubusercontent.com/56823712/99073342-07cbbb80-25b6-11eb-880a-37c8c48c719f.png)

These are the messages that appear when I enter the configuration of the Plugin, the Source Code I added directly from the database.
But if I tell you to save it and let it work normally, this comes out:

![foto 2](https://user-images.githubusercontent.com/56823712/99073417-26ca4d80-25b6-11eb-9696-fb9f3a414cc7.png)

As you can see the credentials are fine but the Source List is not receiving any information.

![foto 3](https://user-images.githubusercontent.com/56823712/99073522-5711ec00-25b6-11eb-9b7f-6cc39720a7b8.png)

As you can see in the image the Live Source Code List does not receive the information even if the credentials are correct.
The credentials that are currently configured are as follows:
![foto 4](https://user-images.githubusercontent.com/56823712/99073580-76a91480-25b6-11eb-8649-036bae0b573d.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, can you get the merchant to force creation of a new payment source? They should temporarily remove the client secret and click on the Save Changes button. An error will occur. This is fine. After that, they should replace the client secret and save again. This should create a new payment source without any errors.

If the above solution does not work, can you ask them to grab the contents of a log file for us? Instructions below:

1. Go to **WooCommerce > Status > Logs** tab:

![log1](https://user-images.githubusercontent.com/44943019/99075879-2039d700-25b2-11eb-806d-f45cc6441d68.png)

2. Select today's date from the dropdown:

![log2](https://user-images.githubusercontent.com/44943019/99075893-262fb800-25b2-11eb-844d-bbf073524f3f.png)

3. Click on the **View** button.

4. Copy the contents into a text file and save it with an appropriate name. 

5. Attach to this issue in .txt format.

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant tells me the next:

The truth remains the same and the LOG you are asking for is very short:

2020-11-13T10:35:03+00:00 DEBUG 
Viva Wallet Version: 1.2.0

--- LOG STARTS HERE: Viva Wallet - Apple Pay: Unable to load domain association file from Viva Wallet API \API result: \headers":{}, "body":", "response":{"code":401, "message": "Unauthorized", "cookies":[], "filename":null, "http_response":{"data":null, "headers":null, "status":null

--- LOG ENDS HERE

This is all there is.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, thanks for the additional info. It's a bit of a strange one, so I'll need to run past our plugin developer. Can you confirm that the version of our plugin that the merchant installed is definitely 1.2.0? They can find this in **Plugins > Installed Plugins**. Thanks!

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I've got some more info for you. The merchant mentions about adding the source code directly from the database. I'm afraid our plugin doesn't support that. Please get them to deactivate and delete the current plugin file and reinstall from the original downloaded ZIP. Setup is automatic. All the merchant needs to do is add their credentials from their live Viva Wallet account (or demo if they wish to test with the card number 4111 1111 1111 1111). They should not make any manipulations to the DB after that. All being well, if they install it and pass the correct credentials everything should work correctly. Thanks.

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant tells me the next:

´´This has been done about twice and we continue with the failure, the database was a test made by us.

Even though we installed the plugging, it still failed. "It does not load the source code".

All done with your Plugin.

Still not valid.

Please look for a solution´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada I will check again with our plugin developer and get back to you when I have any updates.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, please could you find out from the merchant if there's anything new in the logs from 13 November (Friday) and send through if there is. Thanks!

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd what do you mean?

**Comment by matthewrgourd** [comment]
Please ask him to send us another log as described in the comment here: https://github.com/VivaPayments/API/issues/1968#issuecomment-726758220 in case any other information is now shown for Friday.

**Comment by Alvaroalconada** [comment]
@matthewrgourd Reply of merchant:

As you can see, everything is going on at same, without changes

--- LOG STARTS HERE: Viva Wallet - Apple Pay: Unable to load domain association file from Viva Wallet API. \n API result: \n{"headers":{},"body":"","response":{"code":401,"message":"Unauthorized"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}

--- LOG ENDS HERE

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, is there any possibility the merchant could give us temporary admin access to his Wordpress account. If so, please send the login details to mgourd@vivawallet.com rather than posting here. Thanks!
