### ISSUE TITLE
Quick Pay API info

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1970]
Hi,

   Please let us know any API integration is provided for the QuickPay link.

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, no API integration as far as I'm aware.

**Comment by pavithra-itcs** [comment]
Hi,

1. Can we pass document reference along with the Quick pay link - the document reference should be displayed as read-only field
2. If possible the amount which has to be paid (editable)
document reference - can be invoice number or party id.

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, before we go any further, can you let me know the name of the Viva Wallet account holder or their trading name?

**Comment by pavithra-itcs** [comment]
Hi,

Please find the below information 
Trade name : EFILE READY LIMITED
Registration date : 19/02/2020

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Ok, thanks @pavithra-itcs, sorry, could I have the website address as well?

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs as far as I'm aware those parameters you're requesting aren't available. As I say, we don't have an API for Quick Pay.
