### ISSUE TITLE
Payment notifications API information

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#1971]
Hi,

Please let us know any API integration is provided for the Payment notifications tool.

Regards,
ITCS

**Comment by matthewrgourd** [comment]
Hi @pavithra-itcs, yes, please see `serviceId` parameter under [Create payment order](https://developer.vivawallet.com/web-api-integration/payment-api/#tag/Payments/paths/~1api~1orders/post) on our developer portal.
