### ISSUE TITLE
comari factory sl

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1972]
Hi @matthewrgourd this merchant just contact me for telling me the next: 

 ´´We are installing, for test purposes, the payment gateway module in prestashop 1.7.6.5.
I have followed everything that is indicated in the Viva Wallet developer site, so we have Merchant ID, API Key and Source Code. After installing vivawallet1.7.zip on the sales site, www.quevap.es, when activating the payment method with Viva Wallet an error appears saying that there are no active payment methods and the order cannot be placed; when deactivating the Viva Wallet module the payment methods return to normal so we are experiencing problems directly with the app and we see no way to solve this. We have also made a test installing any other payment gateway and everything works correctly to place an order, so I think the problem may be in the Viva Wallet module.
I hope you have the solution and give course to the web, the version of Prestashop is 1.7.6.5´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada can we have screenshots of the error please? Also, screenshots of the payment module settings (in PrestaShop) and Payment Source settings in Viva Wallet. Thanks!

**Comment by Alvaroalconada** [comment]
@matthewrgourd of course mate, I´m waiting it

**Comment by Alvaroalconada** [comment]
@matthewrgourd I send you the screenshots of the problems and settings that you requested me:
<img width="1440" alt="Screen Shot 2020-11-06 at 16 42 31" src="https://user-images.githubusercontent.com/56823712/98389890-f2560f00-2054-11eb-96c4-46fd1a2d2f67.png">
<img width="1440" alt="Screen Shot 2020-11-06 at 16 27 48" src="https://user-images.githubusercontent.com/56823712/98389914-fbdf7700-2054-11eb-9967-6fadc866807e.png">
<img width="1440" alt="Screen Shot 2020-11-06 at 16 58 31" src="https://user-images.githubusercontent.com/56823712/98389931-01d55800-2055-11eb-8b7d-1010916805e8.png">

Merchant ID: 8333b4c0-c018-4e5f-922a-de933aeceeca
API Key: +b7A(P   
SOURCE CODE: 5304

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, thanks for providing those screenshots. The merchant has not followed [installation instructions](https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/) correctly. After checking their **payment source** settings I have found two mistakes:

1. "Domain name" field
WRONG
`www.quevap.es`
**CORRECT**
`quevap.es`
2. "Success / Failure URL" fields
WRONG - 
`https://www.quevap.es/historial-compra`
`https://www.quevap.es/carrito?action=show`
**CORRECT**
`module/vivawallet/success`
`module/vivawallet/fail`

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant tells me the next:

´´we have made the correction but what happens is that if we put the demo URL it doesn't work,
if we put the live URL the gateway is active in Prestashop, I send you the photo,
let me know thanks´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, their payment source settings are still wrong according to the info I have about their demo account with Merchant ID **8333b4c0-c018-4e5f-922a-de933aeceeca**. Correct payment source is **8532** not 5304 as previously stated. Success / Failure URLs should be as below:
**CORRECT**
module/vivawallet/success
module/vivawallet/fail
However, if it's working on live they could try a real-life transaction which they can immediately refund and bypass the demo option where the 3DS is currently disabled (don't know when a fix will be).
