### ISSUE TITLE
3DS on DEMO native v2 redirectToACSForm returns null

### ISSUE THREAD

**Issue by PyB1l** [VivaPayments/API#1973]
My integration was working until recently (4, 5, days ago), but suddenly the 
https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens started responding with 

{"chargeToken":"<token>","redirectToACSForm":null}.

For the demo purposes I am trying a checkout with
4111 1111 1111 1111 
Visa cart

**Comment by matthewrgourd** [comment]
Hi @PyB1l, sorry for this. I believe it is because our dev team are currently working on a fix to the 3DS redirect on demo. In the meantime, it has been deactivated. I'll be able to give you an update soon.

**Comment by PyB1l** [comment]
Hi there,
Just a quick update on the issue, currently the endpoint https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens hangs for ever and it does not returning anything.

**Comment by matthewrgourd** [comment]
Hi @PyB1l, 

I'm sorry, not sure what you mean. I just did the below call and got a charge token back?
```
curl -L -X POST 'https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer 5a9efb2253b196a0b002534542be2b05535da7110443154a13650052bde09ea4' \
--data-raw '{
    "Cvc": "111",
    "Amount": 1000,
    "Number": "5900000000000018",
    "Holdername": "Joe Blogs",
    "ExpirationYear": 2030,
    "ExpirationMonth": 1,
    "SessionRedirectUrl": "https://www.example.com"
}'
```

**Comment by PyB1l** [comment]
I am trying the API with 
4111 1111 1111 1111
Visa cart

Shouldn't this work for 3DS as well?

**Comment by PyB1l** [comment]
I just checked the API returns the JSON response, but still **redirectToACSForm** is null for some reason

**Comment by matthewrgourd** [comment]
Hi @PyB1l we had to disable 3DS on demo while we build a new simulator for authentication / non authentication. So that will be why. At the moment it only works on production. I should have an update from our development team soon.

**Comment by PyB1l** [comment]
Thanks @matthewrgourd

**Comment by PyB1l** [comment]
Αny news?

**Comment by matthewrgourd** [comment]
@PyB1l, I'm told there's a good chance the fix will be this week. Sorry for the delay.

**Comment by matthewrgourd** [comment]
Hi @PyB1l, our demo environment now has a 3DS simulator you can use with our [test card](https://developer.vivawallet.com/getting-started/#test-card). Please close this issue if you feel it has been resolved now.

**Comment by PyB1l** [comment]
I just tested it and it works!

**Comment by PyB1l** [comment]
After some days that worked perfectly, today I suddenly get 
`{"chargeToken":"","redirectToACSForm":null}` again for 

5511070000000020

**Comment by matthewrgourd** [comment]
Hi @PyB1l, maybe the demo environment is being a bit temperamental. I just did a POST to https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens with the below body parameters:

REQUEST
```
{
    "Amount": 100,
    "Cvc": "111",
    "Number": "5511070000000020",
    "Holdername": "John Doe",
    "ExpirationYear": 2030,
    "ExpirationMonth": 10,
    "SessionRedirectUrl": "https://www.example.com"
}
```
and got the below in the response body:

RESPONSE
```
{
    "chargeToken": "ctok_ajUwLw5sfRwAPgmPqh9mT5wzZa4",
    "redirectToACSForm": "<iframe id=\"tdsMmethodTgtFrame\" name=\"tdsMmethodTgtFrame\" style=\"width: 1px; height: 1px; visibility: hidden;\" src=\"javascript:false;\" xmlns=\"http://www.w3.org/1999/xhtml\">\n<!--.-->\n</iframe><form id=\"tdsMmethodForm\" name=\"tdsMmethodForm\" action=\"https://dsx.modirum.com/dstests/ACSEmu2?handshake=1\" method=\"post\"  xmlns=\"http://www.w3.org/1999/xhtml\">\n<input type=\"hidden\" name=\"3DSMethodData\" value=\"eyAidGhyZWVEU1NlcnZlclRyYW5zSUQiIDogImZhODgyMzBhLTI1ZjctNTgyZC04MDAwLTAwMmVhNmNhZWI0ZCIsICJ0aHJlZURTTWV0aG9kTm90aWZpY2F0aW9uVVJMIiA6ICJodHRwczovL2RlbW8udml2YXBheW1lbnRzLmNvbS93ZWIvY2hlY2tvdXQvdGhyZWVkc2VjdXJlYXV0aGVudGljYXRpb24vZmEwODMyNDctZDE4NC00OWVmLThmOWYtOTkyNTI2ZDI2MDYzIiB9\"/>\n<input type=\"hidden\" name=\"threeDSMethodData\" value=\"eyAidGhyZWVEU1NlcnZlclRyYW5zSUQiIDogImZhODgyMzBhLTI1ZjctNTgyZC04MDAwLTAwMmVhNmNhZWI0ZCIsICJ0aHJlZURTTWV0aG9kTm90aWZpY2F0aW9uVVJMIiA6ICJodHRwczovL2RlbW8udml2YXBheW1lbnRzLmNvbS93ZWIvY2hlY2tvdXQvdGhyZWVkc2VjdXJlYXV0aGVudGljYXRpb24vZmEwODMyNDctZDE4NC00OWVmLThmOWYtOTkyNTI2ZDI2MDYzIiB9\"/>\n</form><script type=\"text/javascript\" xmlns=\"http://www.w3.org/1999/xhtml\">\ndocument.getElementById(\"tdsMmethodForm\").submit();\n</script>"
}
```

**Comment by PyB1l** [comment]
Seems that it some times it returns `redirectToACSForm: null` instead of the iframe strin

**Comment by PyB1l** [comment]
For instance right now for

```
{
	"amount": 1000,
	"cvc": "111",
	"number": "5511070000000020",
	"holderName": "John Doe",
	"expirationYear": 2030,
	"expirationMonth": 9,
	"sessionRedirectUrl": "http://localhost:8000/payments/vivapayments_native/auth_redirect/"
}
```

i get 

```
{
	"chargeToken": "ctok_rei4i37XYr5Tk2mzV-g2bNJR8NI",
	"redirectToACSForm": null
}
```

But It worked two hours ago

**Comment by matthewrgourd** [comment]
Hi @PyB1l, I understand the problem. As I say, the demo environment can sometimes behave a bit unpredictably. This of course will not happen on production.
