### ISSUE TITLE
como hacer reembolso automatico desde mi comercio con llamada a la api

### ISSUE THREAD

**Issue by mrusciel** [VivaPayments/API#1976]
Necesito que mi sistema reembolso automáticamente cuando se cancela una venta, como hago la llamada a la api en PHP.... cual es la URL para el curl y los parametros que debo enviar, ademas de como seria la autenticacion. Disculpe mi ignorancia.

**Comment by matthewrgourd** [comment]
Hi @mrusciel, sorry, I'm going to need more information than that. Are you using one of our e-commerce plugins or have you implemented a custom solution using one of our checkouts? If so, which one? Please provide as much information as possible. Thanks!

**Comment by mrusciel** [comment]
No uso ningun cms, por tanto no uso plugin, Yo estoy implementando una
solución a la medida con php. El checkout q utilizo es simple checkout.
Estoy en el ambiente demo aun, haciendo pruebas,  pero necesito probar
hacer reembolsos automaticos desde el sitio web.  Encontre algo en la
documentacion pero no se como aplicarlo. Con paypal yo hago una llamada a
la api de autenticacion obtengo un token y con este hago una llamada a la
api refund le indico el monto y el id de transaccion y funciona perfecto.
Me gustaria saber si vivawallet tiene algo asi. Y si me pueden ayudar con
un codigo de ejemplo en php. Disculpen pero no tengo mucha experiencia con
php.
 Saludos y gracias.

**Comment by matthewrgourd** [comment]
Hi @mrusciel, please consult our documentation, specifically the [Cancel transaction](https://developer.vivawallet.com/web-api-integration/payment-api/#tag/Transactions/paths/~1api~1transactions~1%7BId%7D/delete) page. An example of a refund is shown in the screenshot below:
![Screenshot 2020-11-07 at 09 02 27](https://user-images.githubusercontent.com/44943019/98653917-85cd5f80-2335-11eb-9e4a-c194a13086a8.png)
Hope this helps!

**Comment by mrusciel** [comment]
Hi,

Disculpe, no se si fue que interprete mal sus indicaciones, pero el codigo
que estoy probando para hacer un reembolso me da el siguiente error:
{"Message":"Authorization
has been denied for this request."}

Le envio el codigo para ver si me puede ayudar.

Codigo:

<?php

$Client_ID = "bdd31447-03d9-4a0d-894f-fd7604ea9ddc";
$Secret = "Xj;76[";
$codigoBase64 =
'YmRkMzE0NDctMDNkOS00YTBkLTg5NGYtZmQ3NjA0ZWE5ZGRjOlhqOzc2Ww==';

$Login = curl_init("https://accounts.vivapayments.com/connect/token");
curl_setopt($Login, CURLOPT_RETURNTRANSFER,TRUE);
curl_setopt($Login, CURLOPT_HTTPHEADER, array("Authorization: Basic
 ".$codigoBase64,"Accept: application/json","Content-Type:
application/x-www-form-urlencoded"));
curl_setopt($Login, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
$res_login = curl_exec($Login);
$objRes_login = json_decode($res_login);
$Access_Token = $objRes_login->access_token;
print_r($Access_Token);
curl_close($Login);



$Trans_ID = '9c4ada9e-6992-4b28-bf81-88d35799db4c';
$amount = 100;

$url = "https://demo.vivapayments.com/api/transactions/$Trans_ID";

$headerArgs = array(
        "Authorization: Bearer ".$Access_Token,
        "Content-Type: application/json",
        "Content-Type: text/plain"
    );

    $postArgs = array(
        'amount' => $amount,

        );

$curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($curl, CURLOPT_ENCODING, "");
    curl_setopt($curl, CURLOPT_MAXREDIRS, 10);
    curl_setopt($curl, CURLOPT_TIMEOUT, 0);
    curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);
    curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "DELETE");
    curl_setopt($curl, CURLOPT_POSTFIELDS, $postArgs);
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headerArgs);

    $result = curl_exec($curl);




if (curl_errno($curl) != 0) {
error_log(date('[Y-m-d H:i e] '). "Can't connect to VIVA WALLET to refund,
IPN message: " . curl_error($ch) . PHP_EOL, 3, 'refundVW.log');
print_r('error');
curl_close($curl);
exit;
} else {
curl_close($curl);
}

print_r( $result);
?>

Saludos,
Maite

**Comment by matthewrgourd** [comment]
Hi @mrusciel, my understanding is that to perform a refund using our API you need to make the following call using [basic authentication](https://developer.vivawallet.com/web-api-integration/authentication/#basic-authentication):

DELETE `https://demo.vivapayments.com/api/transactions/{transactionID}/?amount={amount of original transaction}`

I'm afraid we don't have a PHP code sample as such, but please find below the PHP output from Postman:
```php
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://demo.vivapayments.com/api/transactions/36cb831b-25ad-4731-a868-8947ee921182/?amount=1000",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "DELETE",
  CURLOPT_HTTPHEADER => array(
    "Authorization: Basic ZTc1ZmZmNDMtNWM5Zi00YWE2LTljZjEtODZhZmRkZWE4MjA0OmV0UzdrMw=="
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
```
Hope this helps!

**Comment by mrusciel** [comment]
Thank you very much, I´ll try it.

**Comment by mrusciel** [comment]
Hi...

Sus indicaciones fueron muy útiles, y efectivamente me funciona muy bien
siempre y cuando vaya a devolver la totalidad de la compra, pero si hay dos
productos en una compra y se cancela uno, necesito un reembolso parcial, y
este método entonces no funciona me da error en el *amount*.

Alguna sugerencia para reembolso parcial??

Saludos
Maite

**Comment by mrusciel** [comment]
Estuve revisando y el problema es que el mismo método es para cancelar
pagos de antes de 24h y para reembolsos, pero estos no funcionan si se
hacen antes de las 24 horas, no sería mejor que separasen esto, que añadan
un atributo o algo que yo diga que lo que quiero hacer es un reembolso
parcial?? Sino tendria q preguntar cada vez q vaya a reembolsar si tiene o
no mas de 24 h y si no dejar pendiente el reembolso hasta el otro dia.

Saludos,

**Comment by matthewrgourd** [comment]
Hi @mrusciel, I'm sorry if the approach currently being taken by our API isn't ideal for you. I will report back to our dev team as a possible future improvement to look at. I see that you answered your own query about partial refunds. These cannot be done until overnight clearance has taken place. Please feel free to close the issue unless you need further help. Thanks!

**Comment by mrusciel** [comment]
Thanks for you answer. I solved the problem with a program task in the
server that try the refund later. Thank you very much for everything. Now
you can close the issue. Sorry about my english.
