### ISSUE TITLE
INTERMEDIA SL

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1977]
Good morning @matthewrgourd This merchant tells me the next respecte to plugin for modifying language in checkout to set up ES
Uploading/installing the "new" module vivawallet gives me:

2 errors
1. vivawallet (syntax error in /modules/vivawallet/vivawallet.php)
2. vivawallet (missing class in /modules/vivawallet/vivawallet.php)

On the website I had:
PrestaShop] Fatal error in module file :/var/www/vhosts/elcigarroelectronico.com/httpdocs/modules/vivawallet/vivawallet.php:
syntax error, unexpected ')'. 

Nor does it work by exchanging the old chips for the new ones you sent me 

Translated with www.DeepL.com/Translator (free version)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, firstly, please confirm the version of PrestaShop being used by the merchant.

**Comment by Alvaroalconada** [comment]
@matthewrgourd you have reason, sorry I forgot. Is: prestashop 1.6.8

**Comment by matthewrgourd** [comment]
What is the merchant's website address? Is this one we have been dealing with already? If so, is there any related info relevant to this case? Did the download the latest version of our plugin for PrestaShop 1.5-1.6 from the below page?

https://developer.vivawallet.com/e-commerce-plugins/prestashop1.5-1.6/

With this version, the correct language is selected automatically unless unsupported in their PrestaShop instance. 

If possible, please provide screenshots of the errors. Also, a screenshot of the payment module settings. Thanks!

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant´s website address is https://www.elcigarroelectronico.com/. Yeah We have been dealing before.
I let you the reply of him:

´´The problem persists.
Attached 14 and 16, PS backoffice error after installation of the new module What you sent me last week and what I downloaded today from your site have the same result. Syntax error.
Attachment 15: after installing your new module, the whole shop (frontoffice) doesn't work either and leaves everything blank.
Your new zip has 2 folders, I think this is not good for installing a module and there is one or more bugs in vivaweallet.php

I have installed the "old module" again (attached 17 module setting) and it works without problems, except for the English part´´
![viva14](https://user-images.githubusercontent.com/56823712/98574341-19604b00-22b8-11eb-9b63-86632e3c7f4f.jpg)
![viva15](https://user-images.githubusercontent.com/56823712/98574354-1c5b3b80-22b8-11eb-9460-1548142a4740.jpg)
![viva16](https://user-images.githubusercontent.com/56823712/98574362-1e24ff00-22b8-11eb-94ae-cbbe820f1262.jpg)
![viva17](https://user-images.githubusercontent.com/56823712/98574368-20875900-22b8-11eb-8ad7-d9ab89fe3886.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada ok then, get them to use the previous version which I gather is still working. We'll look into why the new one is having issues...
