### ISSUE TITLE
CORS issue on card tokenization (Viva V2 Native)

### ISSUE THREAD

**Issue by viclec** [VivaPayments/API#1979]
We have integrated the Viva V2 Native and we are facing an issue during card tokenization. 

You can see on the following images the error messages:
![image](https://user-images.githubusercontent.com/19333791/98511454-5d7a2e00-226d-11eb-8d23-0233dbeef0eb.png)
![image](https://user-images.githubusercontent.com/19333791/98511473-63700f00-226d-11eb-9ceb-ff50e2b2d323.png)

The process we follow:
1. Get a charge token
![image](https://user-images.githubusercontent.com/19333791/98511698-c95c9680-226d-11eb-8056-ff38c6d619bf.png)
2. Generate a card token (the error message appears in this step)
![image](https://user-images.githubusercontent.com/19333791/98511743-e09b8400-226d-11eb-99ef-3d858b62aca2.png)
3. Store card token along with cardPrefix
4. User can pay with the stored card token for future payments (the error message appears in this step, too)
![image](https://user-images.githubusercontent.com/19333791/98511866-13de1300-226e-11eb-8d81-c899493840dd.png)

Can you give us some directions if we are doing something wrong, or even if we could achieve the same result by following a different process?

**Comment by matthewrgourd** [comment]
Hi @viclec, sorry to hear this. As part of our investigation (which I may need to involve our dev team with) can you let me know if you get the same problem in Firefox?

**Comment by viclec** [comment]
Yes same issue on Firefox as well

**Comment by matthewrgourd** [comment]
Hi @viclec, ok, I'm going to take this to the dev team. Apologies for not giving you a solution to this previously. I don't think the answer we gave was in the right context. I'll get back to you as soon as I can...

**Comment by matthewrgourd** [comment]
Hi @viclec, we have checked and re-checked and the Viva Wallet Card Tokenization API is working fine. It must be a problem with your custom code. In case this helps, please find attached our Card Tokenization Postman collection.

[Card Tokenization API (demo).postman_collection.json.zip](https://github.com/VivaPayments/API/files/5588582/Card.Tokenization.API.demo.postman_collection.json.zip)
