### ISSUE TITLE
getTransactions by DateRange

### ISSUE THREAD

**Issue by pefremidis** [VivaPayments/API#198]
Καλησπέρα,
θέλουμε σε δική μας εφαρμογή να υλοποιήσουμε το κομμάτι εμφάνισης και αναζήτησης των πληρωμών όπως αυτό παρουσιάζεται μέσα στο ίδιο το vivapayments.

Χρειαζόμαστε δηλαδή για παράδειγμα τις πληρωμές του τελευταίου μήνα.

Υπάρχει άλλος τρόπος από το να καλείται συνέχεια το ίδιο πράγμα 30 φορές απλά με διαφορετική ημερομηνία γτ καθυστερεί αρκετά και μέσα στο documentation δεν βρίσκουμε κάτι.

Ευχαριστώ

**Comment by defilerc** [comment]
Καλησπέρα @pefremidis ,

Αυτή η λειτουργικότητα δεν παρέχεται από το API για λόγους ασφαλείας. Αν θέλετε να κάνετε κάποια τέτοια υλοποίηση, θα πρέπει να κρατάτε τις συναλλαγές σε δικό σας σύστημα, ώστε να μπορείτε να κάνετε query με όποιο τρόπο θέλετε τα δεδομένα.

Με εκτίμηση,
