### ISSUE TITLE
Joomshopping problem

### ISSUE THREAD

**Issue by kazanakius** [VivaPayments/API#1980]
Hello,
There seens to be a problem with Viva's Joomshopping plugin. The installation seems to complete successfully but there is no viva payment option.
I checked in the Joomla installation files in my server and the files are not uploaded, neither are the database tables created.

Joomla 3.9.22 - Joomshopping 4.18.4

**Comment by matthewrgourd** [comment]
Sorry to hear this. Did you download the ZIP for the plugin from our Developer Portal? Location below.

https://developer.vivawallet.com/downloads/joomshopping_viva.zip

In order for me to investigate further what your issue might be, please send through the following screenshots:

- JoomShopping payment module settings (mask your Merchant ID and API Key).
- Viva Wallet <a href="https://developer.vivawallet.com/images/redirect-checkout-payment-source.png?classes=border" target="_blank">payment source settings</a> (include your browser's URL bar in the screenshot).
- Viva Wallet  **Sales > Online Payments > Websites / Apps** page (include your browser's URL bar in the screenshot).
- <a href="https://developer.vivawallet.com/images/api-access-page.png?classes=border" target="_blank">API Access</a> page (mask API Key, include your browser's URL bar in the screenshot).

Thanks!

**Comment by kazanakius** [comment]
Hello,
Thank you for your answer,
Yes, I download it from the link that you posted.
I dont have any module settings to send you, because the module does not install correctly.

I havent setup any of the above yet, as I started by trying to install the plugin first.

**Comment by matthewrgourd** [comment]
Hi @kazanakius, did you receive any error messages when you tried to install the plugin? Please send any screenshots so we can investigate. Is your Joomla site live? What is your website address?

**Comment by kazanakius** [comment]
Thank you for the answer, no, Ι see no error, it installs and says "installation complete" but I there is no viva plugin afterwards, and I see no  viva files uploaded on the server.
The domain is : https://www.popshop.com.gr

**Comment by matthewrgourd** [comment]
Hi @kazanakius, so you followed the below route in order to attempt the upload and nothing happened?

![install_update](https://user-images.githubusercontent.com/44943019/98564607-74884280-22a4-11eb-98a6-d39a31ad02c9.png)

When you go to the menu **Components -> JoomShopping -> Options -> Payment method**, is anything listed?

**Comment by kazanakius** [comment]
yesm this is the route a followed, and there is no Viva wallet in Components -> JoomShopping -> Options -> Payment method

**Comment by matthewrgourd** [comment]
Hi @kazanakius, in that case I don't know what to suggest. I note that [JoomShopping](https://extensions.joomla.org/extension/joomshopping/) hasn't been updated since May 2019 so maybe you should try another e-commerce product for Joomla, e.g. [VirtueMart](https://virtuemart.net/downloads).

**Comment by kazanakius** [comment]
[image: Screenshot_2020-11-09 Install Update - PopShop - Πάτρα Αθήνα
Λεμεσός - Administration.png]
[image: Screenshot_2020-11-09 Payment list - PopShop - Πάτρα Αθήνα Λεμεσός
- Administration.png]

Στις Δευ, 9 Νοε 2020 στις 6:00 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by kazanakius** [comment]
is there a way to install it through FTP?


Στις Δευ, 9 Νοε 2020 στις 6:14 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
@kazanakius not that I know of, unfortunately.
