### ISSUE TITLE
 Prestashop 1.7 module not working

### ISSUE THREAD

**Issue by tkardaridis** [VivaPayments/API#1981]
Hi,

Installed the prestashop module for 1.7.

All payment attemps end up with the browser displaying a 404 Page not found error from the vivapayments website.

This is the URL the module is attempting to access :
https://vapemart.atmomixani.gr/web/newtransaction.aspx?Ref=
I don't know why is trying to find an ASPX page on my site which is php. I don't know if i have to fill in the BASE URL in the module configuration and what URL to add. Unfortunately in the developers documentation it does not have any comments for the BASE URL.

Needles to say, we cannot process any payments.

I would like to mention also that i tried both 1309 and 5100 viva settings.
Also to answer your questions, no this is not the first time, but before installing the latest version from the https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7 i had uninstall the previous version and delete all the files from the control panel file mamager. After that i install the latest version. And yes i follow the installation instructions from here
https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/. As you will see in the 5100 settings i had set the success and fail urls as it is mentioned in the developers guide and not like the 1309 which was the configuration for previous versions of prestashop and module.

Finally i would like to mention that webhook validation is not working also.

This is the screenshot just right before the user press the complete button 
![Viva1](https://user-images.githubusercontent.com/40442450/98538853-12bfdc80-2294-11eb-9710-f51cb0cc2928.png)

This is the screenshot after the user press the complete button 
![Viva2](https://user-images.githubusercontent.com/40442450/98538870-16536380-2294-11eb-8a08-7ed111ce79fe.png)

And finally this is the screenshot with the 404 error
![Viva3](https://user-images.githubusercontent.com/40442450/98538886-1b181780-2294-11eb-83c4-a5bf1192fff0.png)

Following are the screenshots as you asked for
![Viva4](https://user-images.githubusercontent.com/40442450/98538899-21a68f00-2294-11eb-8606-3e204cc69466.png)
![Viva5](https://user-images.githubusercontent.com/40442450/98538915-266b4300-2294-11eb-809f-a1c677eb841e.png)
![Viva6](https://user-images.githubusercontent.com/40442450/98538930-29feca00-2294-11eb-8a4b-33708a4c626c.png)
![Viva7](https://user-images.githubusercontent.com/40442450/98538933-2cf9ba80-2294-11eb-8816-70a59655b0a5.png)
![Viva8](https://user-images.githubusercontent.com/40442450/98538937-2f5c1480-2294-11eb-8e7f-141920ee62b5.png)

As for the webhooks if i use the following url (https://vapemart.atmomixani.gr/module/vivawallet/webhook) on verify i am getting the following error
![Viva9](https://user-images.githubusercontent.com/40442450/98540140-22d8bb80-2296-11eb-88f6-e4719999f00a.png)

if i use the following url (https://vapemart.atmomixani.gr/modules/vivawallet/webhook.php) which is previous version format
on verify i am not getting any response but when i press save i am getting the following error
![Viva10](https://user-images.githubusercontent.com/40442450/98540334-73501900-2296-11eb-9687-8de0934effae.png)

Best regards

**Comment by tkardaridis** [comment]
As for the 404 error  i think i fixed the issue. I had to add the https://www.vivapayments.com in the Base Url of the module. After that it redirects the user to yours secure payment page. Also it returns the user correctly in the eshop after the payment and an order has been created.

Now the webhooks... is the problem

**Comment by matthewrgourd** [comment]
Hi @tkardaridis, thanks for providing such detailed information. From your payment module settings, I can see that you have a blank field for "Base URL". Please populate this with `https://www.vivapayments.com`. Source code entry should be `5100` as your PrestaShop version is 1.7.6.8 and I see that payment source `5100` is correctly set up for that. 

Regarding the webhook, please use `https://vapemart.atmomixani.gr/module/vivawallet/webhook` (for PrestaShop v1.7). This will verify correctly, but only when you have the above settings in place.

Let me know how you get on.

**Comment by tkardaridis** [comment]
I have configure the module as you mention, i had correctly place and pay an order. Unfortunately the webhook still not working. It does not verify the url

**Comment by matthewrgourd** [comment]
Hi @tkardaridis did you use the URL for the webhook exactly as shown here:

 `https://vapemart.atmomixani.gr/module/vivawallet/webhook` 

and with **Transaction Payment Created** selected from the dropdown?

**Comment by tkardaridis** [comment]
Yes, copied and paste the url from your comment. And yes with  Transaction Payment Created selected in the dropdown

**Comment by matthewrgourd** [comment]
HI @tkardaridis, ok, I will pass on to our developers that there is a problem with webhook setup for our PrestaShop 1.7 plugin. However, please note that you will still be able to use our plugin without any problems as the webhook is optional.

**Comment by tkardaridis** [comment]
Yes i know that, i will continue to use it. Thanks a lot for the support.
