### ISSUE TITLE
Armand Lopes Rosell

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1982]
Hi @matthewrgourd this merchant tells me the next:

´´I have migrated my shop from Woocommerce to Shopify, I have installed the payment gateway and I am waiting for the token to configure it, I understand that nothing more needs to be done, right?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, please do not post this on GitHub. If it's an internal question you need to ask me, please use Microsoft Teams. Thanks! 

In answer to the merchant's question, they need to wait for the token, yes.

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant already received the mail for finishing integrate shopify but he has a question:

Is there a way to customize this? More than anything, the text in English and with a different typography from the rest of the page does not fit very well and those details end up in lost sales due to lack of trust from the customers.

![elvaporvapeshop](https://user-images.githubusercontent.com/56823712/98941539-06828c00-24ed-11eb-8ca0-18cd2c8a936a.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, unfortunately if the customer is visiting from any country other than Greece, language auto-selects as English. However, the customer can use the language drop-down at checkout to change manually to their language:

![Screenshot 2020-11-12 at 13 26 48](https://user-images.githubusercontent.com/44943019/98945679-be626a00-24ea-11eb-8c04-c32cd2592272.png)

There are no other adjustments that can be made to the look and feel of the plugin, I'm afraid.
