### ISSUE TITLE
【Comfirm】On the currency of credit card payment

### ISSUE THREAD

**Issue by went94** [VivaPayments/API#1983]
Hi @matthewrgourd ,
I meet a question for your help.
Follow Image:
![图片](https://user-images.githubusercontent.com/45383633/98654194-f649a000-2378-11eb-9120-f21fbcf6e817.png)
Could you mind tell me that test card can't use  currency type of EUR?
I tried to close deal  in the currency type of GBP.

I wish your reply, Thank you!

**Comment by matthewrgourd** [comment]
Hi @went94, sorry to hear you're having problems with what looks like authentication. If you could let me know the exact request you're attempting to make with any secure information blurred out?

**Comment by matthewrgourd** [comment]
Also, if you're using the demo environment, is the Merchant ID still 5287ffd9-7361-4ffd-a63a-8b5312d2916f?

**Comment by went94** [comment]
Hi @matthewrgourd ,
I have had complete transfer that use the currency type of GBP.
When I switch to the currency type of EUR that I get Bad Request.

**Comment by matthewrgourd** [comment]
Hi @went94, I believe all transfers have to be in the same currency. So if the first account is in GBP, account for transfer also has to be in GBP.

**Comment by matthewrgourd** [comment]
Hi @went94, are your details as below still?
```
The Demo Account's Merchant ID:5287ffd9-7361-4ffd-a63a-8b5312d2916f
APIKey: 9Vr%9;
AccountID:34801199

And the Demo Account(EscrowAccount):
07410583379
jinze#8060456

OrderyAccount:
7534013186
Ferrari360!

VendorAccount:
07410487326
Nox18115!
(OrderyAccount And VendorAccount Revecied money from EscrowAccount.)
```

**Comment by went94** [comment]
Hi @matthewrgourd ,
Yeah, I think so.
The first transfer that  my Shop set the currency type of GBP.
The second transfer that I set the currency type of the shop to EUR,And received 403.
Use Test Card Following these: 

4111 1111 1111 1111
5900000000000000022
378282246310005

**Comment by went94** [comment]
> 
> 
> Hi @went94, are your details as below still?
> 
> ```
> The Demo Account's Merchant ID:5287ffd9-7361-4ffd-a63a-8b5312d2916f
> APIKey: 9Vr%9;
> AccountID:34801199
> 
> And the Demo Account(EscrowAccount):
> 07410583379
> jinze#8060456
> 
> OrderyAccount:
> 7534013186
> Ferrari360!
> 
> VendorAccount:
> 07410487326
> Nox18115!
> (OrderyAccount And VendorAccount Revecied money from EscrowAccount.)
> ```

Yes.

**Comment by matthewrgourd** [comment]
If you're using a Viva Wallet account set up in the UK, currency always has to be GBP. Likewise, for accounts set up in a country where the currency is EUR, currency has to be set to EUR in all cases. From Native Checkout v2 [documentation page](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/):
<blockquote>
currencyCode is an ISO 4217 code. It should be set to the same currency as your Viva Wallet account. In the example above, the currency is GBP. If registered your account in a Eurozone country, it would be EUR with a code of 978.
</blockquote>

**Comment by went94** [comment]
> 
> 
> If you're using a Viva Wallet account set up in the UK, currency always has to be GBP. Likewise, for accounts set up in a country where the currency is EUR, currency has to be set to EUR in all cases. From Native Checkout v2 [documentation page](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/):
> 
> > currencyCode is an ISO 4217 code. It should be set to the same currency as your Viva Wallet account. In the example above, the currency is GBP. If registered your account in a Eurozone country, it would be EUR with a code of 978.

Hi @matthewrgourd ,
Thank you for help to me. I got it.

**Comment by went94** [comment]
Hi @matthewrgourd ,
I want to know where I can see refund balance to Viva Wallet Account.
I can see the transfer accounts in the Tab of Reports follow Monthly Account Statement.

**Comment by matthewrgourd** [comment]
Hi @went94, I'm not sure which screen you're referring to, can you attach a screenshot?

**Comment by went94** [comment]
> 
> 
> Hi @went94, I'm not sure which screen you're referring to, can you attach a screenshot?

Hi @matthewrgourd , Of curse.
![图片](https://user-images.githubusercontent.com/45383633/98665519-c0131d00-2386-11eb-9a79-e007c59a7dcc.png)
![图片](https://user-images.githubusercontent.com/45383633/98665667-f18be880-2386-11eb-8549-f164d3b603cd.png)
I don't see the refund record here.

**Comment by matthewrgourd** [comment]
Hi @went94, thanks for sending those through. I'm not sure how often the monthly account statement is updated. I think maybe it's 1 day behind the Sales transactions page. Please see below, **Screen 1**, after a successful payment, and **Screen 2**, after a successful refund. Both of these transactions were actioned via our Native Checkout API. 
**Screen 1**
![payment](https://user-images.githubusercontent.com/44943019/98667655-9cc87d80-2346-11eb-966d-c59acdd5f324.png)
**Screen 2**
![refund](https://user-images.githubusercontent.com/44943019/98667670-a225c800-2346-11eb-9e33-e8eb3b221dba.png)

**Comment by went94** [comment]
Hi @matthewrgourd ,
Yes,I do.
After successful refund, how to deal with the amount?
For example，I complete a transfer,I need to transfer balance to Account 1 and Account 2.
At this time, I apply refund.How to deal with the transaction money?

**Comment by matthewrgourd** [comment]
Hi @went94, are you asking about how to perform a balance transfer through the API? Documentation is [here](https://developer.vivawallet.com/web-api-integration/account-api/#balance-transfer) or I can provide an example if you like?

**Comment by went94** [comment]
> 
> 
> Hi @went94, are you asking about how to perform a balance transfer through the API? Documentation is [here](https://developer.vivawallet.com/web-api-integration/account-api/#balance-transfer) or I can provide an example if you like?

Hi @matthewrgourd ,
I mean, how is the money returned after a successful refund

**Comment by matthewrgourd** [comment]
Hi @went94, in the case of a full refund on the same day as the payment, this will simply be a payment cancellation. No funds will be returned as the funds won't have been cleared yet. In the case of full or partial refunds after funds have cleared (overnight), the money is returned to the customer via the card used for the original payment.

**Comment by went94** [comment]
> 
> 
> Hi @went94, in the case of a full refund on the same day as the payment, this will simply be a payment cancellation. No funds will be returned as the funds won't have been cleared yet. In the case of full or partial refunds after funds have cleared (overnight), the money is returned to the customer via the card used for the original payment. I hope I've understood your question correctly. Please let me know if not.

Hi @matthewrgourd ,
In other words, after the transaction of the previous day has been applied for refund, the amount will be returned to the card initiating the transfer in the form of transfer?

**Comment by matthewrgourd** [comment]
Hi @went94, before I respond, can you let me know if you're talking about refunds from the marketplace to the customer via the seller? (Viva Wallet [online marketplace solution](https://developer.vivawallet.com/online-marketplace/)). If yes, I'd need to check with a member of our development team to confirm the answer.

**Comment by went94** [comment]
> 
> 
> Hi @went94, before I respond again, can you let me know if you're talking about refunds from the marketplace to the customer via the seller? (Viva Wallet [online marketplace solution](https://developer.vivawallet.com/online-marketplace/)). If yes, I'd need to check with a member of our development team to confirm the answer.

Hi @matthewrgourd , Yes.I just want to know about these.

**Comment by went94** [comment]
> 
> 
> Hi @went94, before I respond again, can you let me know if you're talking about refunds from the marketplace to the customer via the seller? (Viva Wallet [online marketplace solution](https://developer.vivawallet.com/online-marketplace/)). If yes, I'd need to check with a member of our development team to confirm the answer.

Hi @matthewrgourd , Yes.I just want to know about these.

**Comment by matthewrgourd** [comment]
Hi @went94, I gather my colleague, Michael Vachos, handling the account with Ordery has already answered this. Please check your email. Thanks!

**Comment by matthewrgourd** [comment]
Closing as replying via email on this subject
