### ISSUE TITLE
Zayin Trade Sl

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#1984]
@matthewrgourd this merchant tells me the next: (he is using shopify)

We are trying to do the integration of Viva Wallet with Shopify. I have found this link (https://developer.vivawallet.com/e-commerce-plugins/shopify/) where it explains how to do it. I have followed the steps, and the platform seems to be integrated, but when I try it, it gives an error and does not allow payment by bank card. I don't know if it's an error in the codes I'm entering in Shopify, today there's something else. I appreciate you giving us a hand with this.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I will need a screenshot of the error and also of his Viva Wallet settings page in Shopify. Thanks.

**Comment by Alvaroalconada** [comment]
@matthewrgourd From what I see, I think it's a mistake with the code. I understand that the Merchant ID has been set correctly, but I think that the Store Token has not been set correctly as I do not have access to this code. I found a link on the Viva Wallet help page requesting the code via a Google form and I have done so.

It is possible that the error came from that code, right?
![viva-wallet-shopify (002)](https://user-images.githubusercontent.com/56823712/98707036-e1bcd600-237f-11eb-9d73-cf976af145fd.png)
![error-viva-wallet (002)](https://user-images.githubusercontent.com/56823712/98707060-e5e8f380-237f-11eb-9f62-d9e9259d1e6c.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, has he received an email with the store token and entered that in the settings? He needs to wait for that before he can integrate.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, if the store token has been provided already, and he's using that in the settings along with his merchant ID, and the error message still occurs, let me know via Teams and I will double-check his token for you.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd he just replied me and tell me that everything is all right. Thx very much like always machine, very kind

pd: I close the ticket :)

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant asks me the next:

´´We would like the Viva Wallet payment gateway to appear right after you finish your shopping cart as card payment is the most used on our website, and we believe that there are too many clicks to reach the card payment of the website.
The aim of this is to reduce clicks and thus increase conversion. I do not know if it is possible to do this we want, if possible tell us how or if you need access to the web to do it yourself.´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada this is not configurable I'm afraid. Please do not reopen ticket unless it is a technical issue. Thanks!
