### ISSUE TITLE
configuring wubook.net with vivapayments

### ISSUE THREAD

**Issue by VladMaier** [VivaPayments/API#1985]
Hello

I am trying to configure the connection of my Channel Manager with VivaPayments API.
My channel manager asks for an ACK URL (see https://tdocs.wubook.net/ord/gateway.html ). How can I get this one?

Thank you!

**Comment by matthewrgourd** [comment]
Hi @VladMaier , I gather you wish to use Viva Wallet as a payment gateway with Wubook. Is that correct? I'm afraid at this moment in time we don't support Wubook. You can view a list of the current list of gateways supported by Wubook here:

https://wubook.net/s-pgs/partners-ota/Payment-gateway-5.html
