### ISSUE TITLE
Simple checkout access

### ISSUE THREAD

**Issue by IleaBrussels** [VivaPayments/API#1986]
Hello,

Could you please provide access to the live Simple Checkout API?

**Comment by matthewrgourd** [comment]
Hi @IleaBrussels, sure, could I have the live website URL for the integration, please?

**Comment by IleaBrussels** [comment]
Hi,
I have a live account at Viva Wallet for my offline shop, do you need my merchant id or something else to connect it to my website?
Website URL is shop.ilea.be

Отправлено из Yahoo Почты для Android 
 
  пт, 13 нояб. 2020 в 9:56 matthewrgourd<notifications@github.com> написал(-а):   


Hi @IleaBrussels, sure, could I have the live website URL for the integration, please?

**Comment by matthewrgourd** [comment]
Hi @IleaBrussels, I've enabled the Simple Checkout API for the live Viva Wallet account associated with shop.ilea.be.
