### ISSUE TITLE
Simple Checkout API access

### ISSUE THREAD

**Issue by pitsilkas** [VivaPayments/API#1987]
Hi,

I would like to access the Simple Checkout API of pitsilkas.edu.gr 

Thanks in advance!

**Comment by matthewrgourd** [comment]
Hi @pitsilkas, I've enabled that for you now. Have a good day!

**Comment by pitsilkas** [comment]
I have a problem. I made a payment with credit card but in my account there is no any transaction. I complete the whole process without any error (I set the 3D secure code succesfully). Could you please help me?

**Comment by matthewrgourd** [comment]
Hi @pitsilkas, you have integrated our Simple Checkout solution with your website already? I don't understand. You cannot do that without the API being switched on first. To clarify, please send me the URL of where you just made a payment.

**Comment by pitsilkas** [comment]
Hello @matthewrgourd,  the URL is https://www.pitsilkas.edu.gr/images/vivawallet/payment.html?amount=1

Would you like to send you also the script?

**Comment by matthewrgourd** [comment]
Hi @pitsilkas, do not worry, no funds will have been taken as I can see there is an error with your setup. I believe you're using payment source 1449 for Simple Checkout in your Viva Wallet account. Can you set it to **Native/Pay with Viva Wallet Checkout** (second radio button in below screenshot):

![simple-checkout-payment-source](https://user-images.githubusercontent.com/44943019/99109054-247ce900-25e0-11eb-8451-2ec11ae05b02.png)

**Comment by pitsilkas** [comment]
Hi @matthewrgourd, I had already set Integration method as "Native/Pay with Viva Wallet Checkout". I have to fill in the field Domai Name or I have to left it empty?

**Comment by matthewrgourd** [comment]
Hi @pitsilkas, the payment source settings are correct. Can you share your code, removing any confidential info with placeholders?

**Comment by pitsilkas** [comment]
Hi @matthewrgourd the code (of the URL https://www.pitsilkas.edu.gr/images/vivawallet/payment.html?amount=1) is

`<html>
  <head>
    <title>Πληρωμή με κάρτα</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      #btnContainer {
        text-align: center;
      }
      #btnContainer button {
        width: 75% !important;
        font-size: 18px !important;
        margin: 1.5rem auto !important;
      }
    </style>
  </head>
  <body>
    <table
      style="width: 50%; height: 80%; margin-left: auto; margin-right: auto;"
      border="0"
    >
      <tbody>
        <tr>
          <td>
            <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
            <script type="text/javascript">
              $(document).ready(function () {
                var getUrlParameter = function getUrlParameter(sParam) {
                  var sPageURL = window.location.search.substring(1),
                    sURLVariables = sPageURL.split("&"),
                    sParameterName,
                    i;

                  for (i = 0; i < sURLVariables.length; i++) {
                    sParameterName = sURLVariables[i].split("=");

                    if (sParameterName[0] === sParam) {
                      return sParameterName[1] === undefined
                        ? true
                        : decodeURIComponent(sParameterName[1]);
                    }
                  }
                };
                $("span#amount-value").html(getUrlParameter("amount"));
                LoadButton(getUrlParameter("amount"));
              });
            </script>

            <p style="text-align: center; margin: 0px;">
              <span style="font-size: 14pt;"
                >Επιλέξατε να πληρώσετε
                <b><span id="amount-value"></span> ευρώ</b> με τη χρήση
                πιστωτικής ή χρεωστικής κάρτας. <br />Παρακαλώ πατήστε το
                πλήκτρο "Πληρωμή" για να προχωρήσετε με την εισαγωγή των
                στοιχείων της κάρτας σας.</span
              >
            </p>

            <form id="myform" action="/checkout" method="POST">
              <div id="btnContainer"></div>
            </form>

            <script type="text/javascript">
              function LoadButton(val) {
                $("#btnContainer").empty();
                $("#btnContainer").append(
                  '<button type="button" class="simple" data-vp-publickey="T/MlrH/AXpH0kmle3bKANpNDYmH08qAySvt2Iz2gMZA=" data-vp-lang="el" data-vp-sourcecode="1449" data-vp-description="Πληρωμή σεμιναρίου" data-vp-amount="' +
                    val * 100 +
                    '" data-vp-baseurl="https://www.vivapayments.com" data-vp-expandcard="true"></button>'
                );
                $.getScript("https://www.vivapayments.com/web/checkout/js");
              }
            </script>

            <p style="text-align: center;">
              <img
                src="https://www.pitsilkas.edu.gr/images/vivawallet/viva-logos.png"
                alt="viva logos"
                style="max-width: 100%;"
              />
            </p>
          </td>
        </tr>
      </tbody>
    </table>
  </body>
</html>
`

**Comment by pitsilkas** [comment]
Hello @matthewrgourd. Have you find anything wrong in the code?

**Comment by matthewrgourd** [comment]
Hi @pitsilkas `https://www.pitsilkas.edu.gr/images/vivawallet/payment.html?amount=1` the only thing that looks a bit strange is the `amount=1` query parameter. This way of passing amount isn't documented on our [Simple Checkout page](https://developer.vivawallet.com/online-checkouts/simple-checkout/)? Please follow the instructions exactly as provided.

**Comment by pitsilkas** [comment]
Hi again @matthewrgourd. I just tried the default code but after the transaction no money showed in my vivawallet account.

`<html>
    <head>
        <title>Simple Checkout</title>
    </head>
    <body>
      <form id="myform" action="/checkout" method="post">
        <button type="button"
          data-vp-publickey="T/MlrH/AXpH0kmle3bKANpNDYmH08qAySvt2Iz2gMZA="
          data-vp-baseurl="https://www.vivapayments.com"
          data-vp-lang="en"
          data-vp-amount="100"
          data-vp-sourcecode="1449"
          data-vp-description="My product"
          data-vp-disablewallet="true"
          data-vp-expandcard="true">
        </button>
      </form>

      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://demo.vivapayments.com/web/checkout/js"></script>
    </body>
</html>`

**Comment by matthewrgourd** [comment]
Hi @pitsilkas, can you send me that as plain text rather than a screenshot? I need to test something.

**Comment by pitsilkas** [comment]
[pitsi.html.txt](https://github.com/VivaPayments/API/files/5546470/pitsi.html.txt)
Hi @matthewrgourd. Please rename the file.

**Comment by matthewrgourd** [comment]
Hi @pitsilkas, thanks for that. Your code seems to be fine. I did a test and the expected token `vivaWalletToken` was returned as shown in the below screenshot:

![vivaWalletToken](https://user-images.githubusercontent.com/44943019/99260481-55912f80-2813-11eb-8241-fd95d6f96c05.png)

However, the actual payment won't be made until you make a POST to  `/api/transactions` with the payment token in the body parameters.

See [Step 2: Make the charge](https://developer.vivawallet.com/online-checkouts/simple-checkout/#step-2-make-the-charge).

**Comment by matthewrgourd** [comment]
Hi @pitsilkas, is your issue resolved? If so, please close this ticket.
