### ISSUE TITLE
Simple Checkout API access

### ISSUE THREAD

**Issue by 3294134664** [VivaPayments/API#1988]
I would like to access the Simple Checkout API of webviaggi.eu

**Comment by matthewrgourd** [comment]
Hi @3294134664, that's done for you. Thanks!

**Comment by 3294134664** [comment]
Please can you help me .

In data-vp-amount="??"  

Which is the value i can insert?

**Comment by matthewrgourd** [comment]
Hi, I believe you have to replace with a variable from your source code which automatically picks up the amount due in your customer's checkout. FYI, you need programming experience in order to integrate with our Simple Checkout.
