### ISSUE TITLE
Διασυνδεση Digitech4all.eu με viva payments

### ISSUE THREAD

**Issue by digitech4all** [VivaPayments/API#199]
Αγαπητοι κυριοι 
Προσπαθω να συνδεσω το ηλεκτρονικο μας καταστημα με το συστημα πληρωμων σας
Καταχωρισα μεσα στην εφαμογη μου (πλατφορμα opencart) το merchant id , το merchand password (εβαλα το API KEY) και το source code (εβαλα το τετραψηφιο κωδικο απο Οι πωλήσεις μου/Πηγές πληρωμών (4383)
Παρακαλω επιβεβαιωστε μου οτι εχω φτιαξει σωστα τα παραπανω και ενημερωστε με ποτε θα ειμαι ετοιμος να ξεκινησω να δεχομαι πληρωμες
Για οτι αλλο χρειαστειτε παρακαλω επικοινωνηστε μαζι μας στο 6955113589 η στο sales.digitech4all@gmail.com
ευχαριστω εκ των προτερων 
Νικος Γεωργιου

**Comment by krakenrules** [comment]
Καλημέρα κ Γεωργίου,

Θα θέλαμε να μας στείλετε τα στοιχεία που έχετε ορίσει (merchantid, ApiKey, SourcCode) όπως και το integration method στο merchants@vivawallet.com για να επιβεβαιώσουμε ότι είναι σωστά. 

Ευχαριστούμε πολύ

**Comment by digitech4all** [comment]
Merchant ID:	bddb0174-b8bd-4a4b-83e5-417945e7111d
Merchant Password:	3roDeE
Source Code:   4383
If empty, "Default" source will be used instead	

Σας τα στελνω και ενημερωστε με
Ευχαριστω εκ των προτερων 
Φιλικα
Νικος Γεωργιου

**Comment by digitech4all** [comment]
Η συναλαγη θελω να γινεται σε εσας αρα φανταζομαι ότι εννοειται redirect σαν integration method

**Comment by krakenrules** [comment]
Κύριε Γεωργίου, 

Τα στοιχεία που έχετε ορίσει για το API είναι σωστά όπως και το source code "4383" το οποίο λειτουργεί με integration method=redirection. 

Για δοκιμαστικές πληρωμές θα μπορούσατε να συνδέσεται την εφαρμογή σας με το demo.vivapayments.com.

Επίσης για λόγους ασφαλείας θα παρακαλουσαμε να διαγράψετε τα στοιχεία MerchantId & Password απο το προηγούμενο post.

Ευχαριστούμε πολύ

**Comment by digitech4all** [comment]
Μολις δοκιμασα και ειδα οτι η πηγη πληρωμης digitech4all.eu ειναι ακομα σε εκρεμοτητα και στην ανακατευθυνση μου γραφει 
The merchant with id bddb0174-b8bd-4a4b-83e5-417945e7111d does not have a source with code '4383' assigned or the source is disabled
μπορω να κανω κατι εγω η ειναι θεμα δικο σας ???

**Comment by krakenrules** [comment]
Κύριε Γεωργίου,

Είναι θέμα δικό μας. Πριν απο την ενεργοποιήση ενός source γίνεται έλεγχος από εμάς. Αν προκύψει κάποιο θέμα θα σας ενημερώσει το support μας.

Ευχαριστούμε πολύ
