### ISSUE TITLE
Simple Checkout API access

### ISSUE THREAD

**Issue by Dydy88** [VivaPayments/API#1990]
Hello,

I would like to access the Simple Checkout API of saiyengin-cbd.com

Thanks in advance!

**Comment by matthewrgourd** [comment]
Hi @Dydy88, completed as requested. Thanks.

**Comment by Dydy88** [comment]
Hello 

I have a problem with the integration of the VivaWallet payment form, once the customer's bank details and double authentication have been carried out, an error is returned and I do not understand the why


Here is the example of the payment form used for the test, as well as a screenshot of the error returned by the console

Thanks for your help

`<form id="myform" action="index.php?p=checkout" method="post">
                                <button style="width: 100%;" type="button" name="paymentVivaWallet"
                                        data-vp-publickey="Txk1YfQuHb3ZCShUIeozJrcrs33d11WkUtKIWPuXuV0="
                                        data-vp-baseurl="https://www.vivapayments.com/"
                                        data-vp-lang="fr"
                                        data-vp-text="ProcÃ¨der au Paiement"
                                        data-vp-amount="100"
                                        data-vp-sourcecode="Default"
                                        data-vp-description="RÃ©glement de vos Produits"
                                        data-vp-border-radius="0"
                                        data-vp-customersurname="<?= $_SESSION['client']->name ?>"
                                        data-vp-customerfirstname="<?= $_SESSION['client']->client_firstname ?>"
                                        data-vp-customeremail="<?= $_SESSION['client']->email ?>"
                                        data-vp-disablewallet="true"
                                        data-vp-expandcard="true">
                                </button>
                            </form>
`
![error paiement](https://user-images.githubusercontent.com/18478869/99303633-8a23dc00-2851-11eb-92d7-d1a3f33e9d41.PNG)

**Comment by matthewrgourd** [comment]
Hi @Dydy88, I've just tested our Simple Checkout solution on live and it's working fine. It must be an issue with your custom code which I'm afraid I won't be able to help with.

**Comment by matthewrgourd** [comment]
@Dydy88 after testing this scenario myself it appears a 500 error is returned if a payment card has been rejected by the issuer or 3DS has failed. My advice would be to implement our [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) solution which is more up-to-date than Simple Checkout and has a better API.
