### ISSUE TITLE
j2store and VivaPayment plugin

### ISSUE THREAD

**Issue by stvlahos** [VivaPayments/API#1994]
Hello, 

I think that is a top priority to have a j2store plugin.. I believe that there is big demand!  

I am watching the page but there is no plugin for j2store, also there is no third company that have this plugin. (I have 2 eshops and I need it asap) 

thank you

**Comment by matthewrgourd** [comment]
Hi @stvlahos, the following Viva Wallet plugins are available for Joomla:

- [HikaShop](https://developer.vivawallet.com/e-commerce-plugins/hikashop)
- [Joomdonation EShop](https://developer.vivawallet.com/e-commerce-plugins/joomdonation-eshop)
- [JoomShopping](https://developer.vivawallet.com/e-commerce-plugins/joomshopping)
- [VirtueMart 1](https://developer.vivawallet.com/e-commerce-plugins/virtuemart1)
- [VirtueMart 2](https://developer.vivawallet.com/e-commerce-plugins/virtuemart2)
- [VirtueMart 3](https://developer.vivawallet.com/e-commerce-plugins/virtuemart3)

There are currently no plans to add one for J2Store but I will certainly let our developers know there is interest. Thank you.
