### ISSUE TITLE
access to your Simple Checkout API

### ISSUE THREAD

**Issue by Antho-Shopify** [VivaPayments/API#1995]
Hi there,

I'm following the steps to integrate your payment page to a wix site and to do so, I need to raise an issue, which is what I'm doing :) 
Could you get back to me about it ? 

Thanks in advance. 
Best, 
Anthony

**Comment by matthewrgourd** [comment]
Hi there, in order to enable Simple Checkout for you, I need your Merchant ID which can be found in your Viva Wallet account under **Settings > API access**. Thanks!

**Comment by Antho-Shopify** [comment]
Hi Matthew,

THanks for your quick feedback. Here is my merchant id :
1cf49477-cb24-44c0-837f-2973f72238da

Best,
Anthony
--
Saveurs-CBD
Suivez-nous sur Facebook <https://www.facebook.com/saveurscbd/> et sur
Instagram <https://www.instagram.com/saveurs_cbd_hemeka/> !
www.saveurs-cbd.fr


Le mer. 18 nov. 2020 à 10:23, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
@Antho-Shopify that's done for you now.

**Comment by Antho-Shopify** [comment]
Thanks !
--
Saveurs-CBD
Suivez-nous sur Facebook <https://www.facebook.com/saveurscbd/> et sur
Instagram <https://www.instagram.com/saveurs_cbd_hemeka/> !
www.saveurs-cbd.fr


Le mer. 18 nov. 2020 à 10:33, matthewrgourd <notifications@github.com> a
écrit :

**Comment by Antho-Shopify** [comment]
Another question : I need to add VivaWallet to a Wix site. Would you have
any documentation about how to do it by any chance ?

Thanks in advance.
best,
Anthony
--
Saveurs-CBD
Suivez-nous sur Facebook <https://www.facebook.com/saveurscbd/> et sur
Instagram <https://www.instagram.com/saveurs_cbd_hemeka/> !
www.saveurs-cbd.fr

**Comment by matthewrgourd** [comment]
Hi @Antho-Shopify, I checked on Google and Wix has a page with a list of payment providers with setup instructions provided:

https://support.wix.com/en/article/available-payment-providers-6803928

If you wish to use us, I believe you can, but I'm afraid there are no specific instructions.

We have three options for implementing a custom integration with Viva Wallet, but please note, you need developer experience to tackle these:

- [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/)
- [Redirect](https://developer.vivawallet.com/online-checkouts/redirect-checkout/)
- [Native](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/)

**Comment by Antho-Shopify** [comment]
THanks Matthew !
--
Saveurs-CBD
Suivez-nous sur Facebook <https://www.facebook.com/saveurscbd/> et sur
Instagram <https://www.instagram.com/saveurs_cbd_hemeka/> !
www.saveurs-cbd.fr


Le mer. 18 nov. 2020 à 10:56, matthewrgourd <notifications@github.com> a
écrit :
