### ISSUE TITLE
Integrate Viva Payment Ionic

### ISSUE THREAD

**Issue by adamsony06** [VivaPayments/API#1997]
Hello,

I have a project and i need to integrate your api on an ionic projet. In your website, I did not see how we can integrate it for Android and iOS. 

I saw that we can do a POST with the following url https://demo.vivapayments.com/api, but i did'nt see the body to provide card information. Please I need an answer as soon as possible.

Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06 please let me know what it is you're attempting to do. Is it create an app for Android / iOS with Viva Wallet as a payment option? For information on natively integrating with a website or app, please see https://developer.vivawallet.com/online-checkouts/native-checkout-v2/ on our developer portal.

**Comment by adamsony06** [comment]
Hello, yes it's the case but the problem is that i can't integrate your html that use VivaPayment.js and jQuery. So i can't use data-vp as a tag.

Best regards.

**Comment by matthewrgourd** [comment]
We have a [Native Checkout v2 API](https://developer.vivawallet.com/web-api-integration/native-checkout-v2-api/) (without a JS). I don't know if that helps at all.

**Comment by adamsony06** [comment]
Ah fine I will try it and give you updates, Thank you !

Best regards.

**Comment by adamsony06** [comment]
Could you give me access to the OAuth2 for the Native Checkout v2 Credential  please ? I need it so I can test it. I have the following error : {
    "error": "invalid_client"
}
Thank you in advance !

Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06 your Native Checkout v2 credentials are available via the Viva Wallet banking app (**Settings > API access**). See https://developer.vivawallet.com/web-api-integration/authentication/#oauth-2-token-generation for more info. I don;t think we need to enable anything, but p'raps if I could have your [Viva Wallet merchant ID](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) to check?

**Comment by adamsony06** [comment]
It's a test one, and i followed the steps in your website with the base64 encryption of the following [clientid]:[secretid] and it don't work.
My viva wallet merchant ID is the following : 

a939f97f-c8ec-4ecb-90a6-546aeccc8f6f
--

**Comment by matthewrgourd** [comment]
Hi @adamsony06 there is nothing that needs to be enabled. Please check that you're using the demo Client ID / Client Secret from your demo Viva Wallet account **Settings > API access** here:

![api-access-page](https://user-images.githubusercontent.com/44943019/99640382-b6517f80-2a40-11eb-89a2-5c7a7322fe9c.png)

A call such as the below should then be made to return the bearer token:

REQUEST
 ```
curl -L -X POST 'https://demo-accounts.vivapayments.com/connect/token' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-H 'Authorization: Basic ZzI0N2NmbnlwYzV3cmszaHAwZnU2cTk3N2YzZzYxY2hnODV1NzJzZmJkb3c3LmFwcHMudml2YXBheW1lbnRzLmNvbTo3NjZOTGsyN2oyOGJLZlBCWVI2RDQ4NVVTV2twQ1k=' \
-F 'grant_type=client_credentials'
```
RESPONSE
```
{
    "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6IkpXVCIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCJ9.eyJuYmYiOjE2MDU3NzQ0NjIsImV4cCI6MTYwNTc3ODA2MiwiaXNzIjoiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJhdWQiOlsiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIiwiY29yZV9hcGkiXSwiY2xpZW50X2lkIjoiZzI0N2NmbnlwYzV3cmszaHAwZnU2cTk3N2YzZzYxY2hnODV1NzJzZmJkb3c3LmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiI5NkNCNUEwNy00OENFLTREODEtODc2RC1BNkMzREY4REJEMTYiLCJzY29wZSI6WyJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmciLCJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmc6Y2FyZHM6dG9rZW5zIiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6bmF0aXZlY2hlY2tvdXR2MiJdfQ.Ykqj-GlXyN8ObSpcc7RHebFaLpiOl167-huubmOYz2vQGs58Y5VA20-HTnn89l7hiDQ3uhtt0zkcXu6y66rk5NTpp-VHQPa5O4faSRKOfCodKqB7B4er3oCXKbxPWz4ulwuOq9s_tvYlQ4NHAh24HSCLNX2dt4eZS0v5SQ_FJEVz85haxGcAp8NTIkxSN9r7qrDUtdwf0F9wb-uzUhAnjhHFbPVWACCj3DFCLjJFcRdkJ3Fdcl73HUA1nwQHbKFQV-R4jhLgXIV-mqdA177ULXhj9qDLKHa2XlwBNlkhBwWwpIKcdpvHct6eqdebqzdV-s3ogLL17-drCS4z57m_0g",
    "expires_in": 3600,
    "token_type": "Bearer",
    "scope": "urn:viva:payments:core:api:acquiring urn:viva:payments:core:api:acquiring:cards:tokens urn:viva:payments:core:api:nativecheckoutv2"
}
```

**Comment by adamsony06** [comment]
I tried with postman with your token and i get the same error : 
<img width="1345" alt="Capture d’écran 2020-11-19 à 10 03 57" src="https://user-images.githubusercontent.com/58440550/99644748-9a54da80-2a4e-11eb-8928-fe4c38d60155.png">
<img width="1347" alt="Capture d’écran 2020-11-19 à 10 04 10" src="https://user-images.githubusercontent.com/58440550/99644761-9c1e9e00-2a4e-11eb-892a-f031512bf5a6.png">

**Comment by matthewrgourd** [comment]
Hi @adamsony06, to replicate the cURL example in Postman, add your Native Checkout v2 credentials as username as password:

![Screenshot 2020-11-19 at 09 42 59](https://user-images.githubusercontent.com/44943019/99649119-b73bde80-2a4b-11eb-831a-edeb5a9913b8.png)

Grant type should be "client_credentials" in the body parameters:

![Screenshot 2020-11-19 at 09 44 51](https://user-images.githubusercontent.com/44943019/99649282-ed795e00-2a4b-11eb-989d-bd566d319218.png)

Here is a Postman collection for you to import:

[generate bearer token.postman_collection.json.zip](https://github.com/VivaPayments/API/files/5565885/generate.bearer.token.postman_collection.json.zip)

Obviously replace the demo credentials included with your own.

**Comment by adamsony06** [comment]
Thank you so much for your help that works for me with mobile and postmant ! But just one question, for the https://demo-api.vivapayments.com/nativecheckout/v2/transactions endpoint, i need to add the sourceCode in the body, what is this ?

Best regards.

**Comment by matthewrgourd** [comment]
Source code is what you should have set up in your Viva Wallet account here:

![Screenshot_2020-11-19_at_12_44_37](https://user-images.githubusercontent.com/44943019/99668083-2d007400-2a65-11eb-8a13-37e349a8a8ca.png)

You need to include the 4-digit code as a parameter.

**Comment by adamsony06** [comment]
Thank you ! Right now i have this error : {
    "status": 403,
    "message": "Person a939f97f-c8ec-4ecb-90a6-546aeccc8f6f does not support currency '826'",
    "eventId": "0"
}

Could you help me please.

Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06, your Viva Wallet account is in Euros so `"currencyCode": 826` in the body parameters of your POST to   `/nativecheckout/v2/transactions` needs to be set to 978.

**Comment by adamsony06** [comment]
Thank you for all of your response ! But I have a big problem with 3DS Authentification, could we disable it ? Because I can't render the html response with ionic, js is not supported.

**Comment by adamsony06** [comment]
Hello, so i manage to make it work by any means... But i have a problem from your server side, see the above image : 
![F80D85A4-B022-4911-B98A-54D3891FD49D](https://user-images.githubusercontent.com/58440550/99777858-321bfc80-2b13-11eb-9b57-e0079c46bceb.png)

**Comment by matthewrgourd** [comment]
We can't disable 3DS I'm afraid. Looks like maybe you won't be able to use ionic?

**Comment by adamsony06** [comment]
I made it worked but i have the following error, did you see the above message ?

**Comment by matthewrgourd** [comment]
Hi @adamsony06 you're testing on demo right? We have an issue which means the 3DS functionality is currently disabled on demo. I don't know when it will be fixed but will chase today. Apologies for any inconvenience caused.

**Comment by adamsony06** [comment]
Ah okay so in live it will work ? Also i have cors problem on the two endpoints : https://demo-accounts.vivapayments.com/connect/token and https://demo-api.vivapayments.com/nativecheckout/v2/transactions with http angular post.

Best regards.

**Comment by matthewrgourd** [comment]
@adamsony06 in production it will be fine. The reason for the CORS issue is you should be making those calls through a back-end channel not the browser.

**Comment by adamsony06** [comment]
Thank you ! So what I should do ? Can I keep it like that or add a backend bridge ?

Best regards.

**Comment by adamsony06** [comment]
I tried from back end and i get empty result, is the backend must be https ?

Best regards.

**Comment by adamsony06** [comment]
Sorry It worked, i will update you asap

Best regards.

**Comment by adamsony06** [comment]
It worked as expected ! Now with demo when I try to test the 3D Authentification, there is a blank screen not the server error problem, is it still not working ?

Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06, in answer to your question, apparently the demo 3DS is still being worked on so not switched on currently. Please close this issue if you feel it has been resolved.

**Comment by adamsony06** [comment]
Dear,

How are you ? We have a problem with viva wallet, we have an account with customer ID but we don't have the secret code, we can generate another but the problem is, it's already implemented in a website and we don't have access with the server. 

Could we generate another secret code without affect the website ?

Thank you Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06 I'm afraid what you request isn't possible. You have to update the remote server if there has been a change on the Viva Wallet side.
