### ISSUE TITLE
Can't enter card details

### ISSUE THREAD

**Issue by meganburns17** [VivaPayments/API#1998]
Hi there, have hooked up Viva Wallet for Woocommerce and all verified API's however when I reach the checkout page on my website I cannot enter the card details. No input fields are available. Everything is verified correctly inside Woocommerce and also Viva Wallet. Thanks, Megan

<img width="558" alt="Screen Shot 2020-11-18 at 14 11 59" src="https://user-images.githubusercontent.com/74665524/99540934-17794480-29a8-11eb-87dd-6c8df20d3db3.png">

**Comment by matthewrgourd** [comment]
Hi @meganburns17, sorry to hear that. Could I have your merchant ID and the web address please?

**Comment by matthewrgourd** [comment]
Hi @meganburns17, is the problem still occurring? I'm sorry, but I need further information in order to help you. Could I have you web address and / or Viva Wallet Merchant ID?

**Comment by meganburns17** [comment]
Hello, I got this sorted as it was a piece of ccs missing from the theme!

Thanks for following up - much appreciated

Megan

On 23 Nov 2020, at 09:32, matthewrgourd <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi @meganburns17<https://github.com/meganburns17>, is the problem still occurring? I'm sorry, but I need further information in order to help you. Could I have you web address and / or Viva Wallet Merchant ID?
