### ISSUE TITLE
Simple check out access

### ISSUE THREAD

**Issue by giannischAC** [VivaPayments/API#1999]
Hello, I would like to have access to your Simple Checkout API.
Demo account
Merchant ID: 6d4252f0-2088-484f-8c0e-5cfc2024ff77
Domain: marketplace.ampointdigital.gr

I already created a payment source, don't know if you need that information. (Code 9237)

Thank you in advance

**Comment by matthewrgourd** [comment]
Hi @giannischAC, that's done for you now. Thanks.
