### ISSUE TITLE
Hotel online reservation software payment gateway

### ISSUE THREAD

**Issue by orestisvla** [VivaPayments/API#200]
![clocl_pms](https://cloud.githubusercontent.com/assets/23481691/20571997/51e3d0c6-b1b2-11e6-8337-8f1f87129f92.png)
Hi 
I am using an online hotel PMS and i want to use viva wallet as a payment gateway on the image above they request for a Payment Service URL so the guest can be Redirected to viva wallet.
Were can i find that URL?
Thank You
Orestis Vlachos
orestisvlachos@gmail.com

**Comment by defilerc** [comment]
Hi @orestisvla ,

The solution you're trying to implement is the "Redirect Checkout" method. Please check the documentation page at https://github.com/VivaPayments/API/wiki/Redirect-Checkout .

We are happy to help, in case you need any further assistance.

Regards,
