### ISSUE TITLE
Still payment problems!

### ISSUE THREAD

**Issue by Giacomo120** [VivaPayments/API#2000]
Good morning,
A customer tells us that he has tried several times to pay for an order but the payment system refuses it by saying "payment canceled" when he has entered the data correctly (the card is a Nexi Mastercard circuit).
I don't know what to do anymore, every day a new problem arises with your gateway, it's scandalous!

**Comment by Giacomo120** [comment]
Before you ask, yes, he says he has enough funds on the card.

**Comment by Giacomo120** [comment]
On the Vivawallet transactions there are two rejected by the customer

**Comment by matthewrgourd** [comment]
Hi @Giacomo120 please could I have your website address and date of the transaction so I can check further. Thanks!

**Comment by Giacomo120** [comment]
www.hemport.it

**Comment by Giacomo120** [comment]
The transaction was made yesterday, two times or three, at 14 pm more less

**Comment by Giacomo120** [comment]
![Screenshot_20201119_094819_com android gallery3d](https://user-images.githubusercontent.com/74073970/99643022-7c867600-2a4c-11eb-83e0-6bec9d7d096e.jpg)

**Comment by Giacomo120** [comment]
This is the problem that the customer is having

**Comment by Giacomo120** [comment]
He has just retry

**Comment by matthewrgourd** [comment]
Hi @Giacomo120, I've checked and there were 2 card failures recorded for €65 yesterday against your account:

- 18/11/2020 15:16:43 - Mastercard Exceeds withdrawal count limit (65)
- 18/11/2020 15:21:06 – Mastercard Exceeds withdrawal count limit (65)

I can confirm that there is no issue at the Viva Wallet end. The customer needs to contact their card issuer(s). Thanks!

**Comment by matthewrgourd** [comment]
Hi @Giacomo120, regarding the retry, I can also see the below attempt to make a €65 payment today:

- 19/11/2020 10:30:51 – Mastercard Exceeds withdrawal count limit (65)

Again, I would advise the customer to contact their card issuer.

**Comment by Giacomo120** [comment]
Ok, thanks, i am happy that this time the problem is not due to vivawallet!

**Comment by matthewrgourd** [comment]
Please feel free to close the issue if you feel it has been resolved. Thanks.
