### ISSUE TITLE
Payment problem still present

### ISSUE THREAD

**Issue by Giacomo120** [VivaPayments/API#2001]
Hi, with reference to the problem closed an hour ago I would like to point out that the customer has contacted their bank which reported that the withdrawal limit is only physical and not online, and that it appears to them that the type of card used is not is authorized by your system. (Nexi debit card of the Mastercard circuit)
What can we do?

**Comment by Giacomo120** [comment]
Please reply me, I'm losing customers for all these problems..

**Comment by matthewrgourd** [comment]
Hi @Giacomo120, ok, so that's correct then, we don't support that particular card. Ask your customer to use a different card.

**Comment by Giacomo120** [comment]
So you don't accept nexi cards? That are still from the Mastercard circuit?
But above all, did you not know so far?

**Comment by matthewrgourd** [comment]
Hi @Giacomo120, I'm not sure why there's a problem as we definitely accept Mastercard. Let me double-check if Nexi is special.

**Comment by Giacomo120** [comment]
Ok, let me know thanks

**Comment by Giacomo120** [comment]
Hi, is there news?

**Comment by matthewrgourd** [comment]
Hi @Giacomo120, this is with our operations team. I should be able to update you tomorrow.

**Comment by Giacomo120** [comment]
Ok, thanks

**Comment by matthewrgourd** [comment]
Hi @Giacomo120 we've looked into the Nexi transactions on your account and it is seems to be a problem with that particular customer. We definitely accept Nexi Mastercards, indeed, we can see that there are successful payments into your account from other clients of yours using Nexi. Please close this issue if you feel it has been answered fully.
