### ISSUE TITLE
Will you make a fix for this? 

### ISSUE THREAD

**Issue by Giacomo120** [VivaPayments/API#2003]
Will you make a fix for this?
Hi, I want to clarify that for us it is a considerable problem that even failed orders are counted.
In this way the order of the orders is unpacked, because even the failed ones are numbered.

**Comment by Giacomo120** [comment]
![Screenshot_20201119_132435](https://user-images.githubusercontent.com/74073970/99665937-959e1f80-2a6a-11eb-8bec-ac9484b0809e.jpg)

**Comment by Giacomo120** [comment]
??

**Comment by matthewrgourd** [comment]
Hi @Giacomo120 are you talking about unpaid orders in WooCommerce? Yes, you will see these as "Pending payment" and later "Cancelled". Successful payments normally show as "Completed". This is not something that can be altered. It's just the way WooCommerce works and is not linked to Viva Wallet.

**Comment by Giacomo120** [comment]
We are on Magento 2

**Comment by Giacomo120** [comment]
And we never had this problem until we start to use your gateway

**Comment by matthewrgourd** [comment]
Ah, sorry, I thought you were WooCommerce. Well a similar concept applies with our Magento plugin.

**Comment by Giacomo120** [comment]
Yes but as you just said it's a problem with your plug in .. Are you planning to find a solution about it?

**Comment by matthewrgourd** [comment]
Hi @Giacomo120 we are in the process of reviewing all our plugins and the Magento one is on the list. However, there isn't a 'problem' with it you can be assured of that.

**Comment by Giacomo120** [comment]
Sorry, I'm a customer who uses your service, I'll explain that this is a problem and I'll also explain the reasons why it is (change the number of orders, count the use of coupons, change the quantities) and you answer that for you it is not?
But what way of working is this?

**Comment by matthewrgourd** [comment]
Hi @Giacomo120, as far as I can tell you're referring to the orders as displayed in Magento, is that correct? Let me try to understand the issue a bit more. What status is shown for the unpaid orders. Can I have a couple of examples (dates / amounts so I can check against your Viva Wallet account?

**Comment by matthewrgourd** [comment]
Hi @Giacomo120, please provide the requested info. as soon as possible so I can help you further.

**Comment by Giacomo120** [comment]
Sorry, I thought I answered.
For an example just look at yesterday's failed transactions.
Only one customer has failed the transaction at least 5 times, for all these 5 times the system has created an order, assigning a progressive number, and counting the use of any coupons.
That is the question! It doesn't matter if they can be canceled afterwards, that is only for us to avoid shipping an unpaid order.
It shouldn't happen. It also happens if a customer arrives at the final purchase stage and then exits without entering the data! And I also begin to have the suspicion that customers can see among the "past orders" those not successful with the relative progressive number.
This only happens with you, it is convenient that a purchase attempt is notified but it is not if it then causes the problems I mentioned above.
To say, if now a customer buys me on the site it will turn out to be order 202, when in reality it would have been 170 maybe! But having been given a number also to failed orders (which in my opinion should not really be created, again for the previous reasons) then 202 is assigned.

**Comment by Giacomo120** [comment]
If that's not a problem for you, I don't know what else to say. At a management level it is a big problem and if it is not for you I will try to find another service.

**Comment by matthewrgourd** [comment]
Hi @Giacomo120, for the orders that are unpaid, what is the initial status shown in Magento?

**Comment by Giacomo120** [comment]
Pending Payment

**Comment by Giacomo120** [comment]
It just happened again. A customer even don't insert his card data but in the back end there are three orders in pending payment.

**Comment by Giacomo120** [comment]
It is happening again. It's ridiculous. Thanks to you i have at least 30 orders canceled that are counted like normal orders. Do something!

**Comment by Giacomo120** [comment]
It is happening again. Thanks to your service i have the back end order list full of failed orders! It's ridiculous.

**Comment by matthewrgourd** [comment]
Hi @Giacomo120 as far as I'm aware this is the correct functionality from Magento. When you see an order in "Pending payment" it either means no card payment was received or an abandoned cart.

**Comment by Giacomo120** [comment]
No! For days, not to say weeks since I have been reporting this problem for a long time, I am telling you that this happens ONLY USING YOUR GATEWAY.

**Comment by Giacomo120** [comment]
If you don't understand my English tell me, because now I'm starting to lose patience.
This is not the correct functionality of magento. It is if YOU have provided this functionality on your plug in.
Paypal, Stripe etc did not cause these problems if an order was abandoned!

**Comment by Giacomo120** [comment]
If you don't understand my English tell me, because now I'm starting to lose patience.
This is not the correct functionality of magento. YOU have provided this functionality on your plug in.
Paypal, Stripe etc did not cause these problems if an order was abandoned!

**Comment by Giacomo120** [comment]
I have the orders page flooded with orders that are actually abandoned carts, failed payments, etc. which is also given the progressive number.
I don't give a fuck if I can delete them later! They really shouldn't be there!

**Comment by Giacomo120** [comment]
If you don't understand my English tell me, because now I'm starting to lose patience.
This is not the correct functionality of magento. YOU have provided this functionality on your plug in.
Paypal, Stripe etc did not cause these problems if an order was abandoned!

**Comment by Giacomo120** [comment]
I have the orders page flooded with orders that are actually abandoned carts, failed payments, etc. which is also given the progressive number.
I don't give a fuck if I can delete them later! They really shouldn't be there!

**Comment by matthewrgourd** [comment]
HI @Giacomo120, unfortunately our plugin is not very sophisticated so you will see abandoned carts and payment failures as 'Pending orders' in Magento. The successful orders should be displayed as "Completed" or similar. Let me know if that is not the case otherwise our plugin is working as expected. We intend to refresh many of our plugins soon with enhanced functionality but until that time I'm afraid there is only limited syncing between Viva Wallet and Magento from an order perspective. However, to be clear, that doesn't mean we're losing any of your orders. If an order has been paid, it will show as a "Processing" or "Complete" order in Magento.

**Comment by Giacomo120** [comment]
I appreciate the sincerity, I highly recommend that you fix this.
Now I have also accidentally canceled a completed order, because I had been canceling the unsuccessful ones for hours.
We can't have failed orders counted in total orders, that's ridiculous.
Furthermore, if an order left in "Pending Payment" is not promptly canceled manually, the quantities of the products are also changed as if the order had been placed correctly.

**Comment by Giacomo120** [comment]
![Screenshot_20201120_134714](https://user-images.githubusercontent.com/74073970/99808805-b38a8380-2b41-11eb-9caa-04bde6708b17.jpg)

**Comment by Giacomo120** [comment]
This is just an example of what happen.

**Comment by matthewrgourd** [comment]
Hi @Giacomo120, I see what you mean. I'm testing your checkout now.

**Comment by matthewrgourd** [comment]
Hi there, I added an item to the cart and clicked on **Proceed to checkout**. I was then asked to log in (I previously created an account) but I'm getting this and nothing happens for at least 60 seconds:

![Screenshot 2020-11-20 at 14 28 06](https://user-images.githubusercontent.com/44943019/99811274-d9615980-2b3c-11eb-9566-ff0874aabfca.png)

I think there's something wrong with your checkout / theme. Some customers may lose patience and try to refresh their browser. Now I've gone to my cart but there's no obvious button to click on to proceed to payment?

![Screenshot 2020-11-20 at 14 32 13](https://user-images.githubusercontent.com/44943019/99811574-4117a480-2b3d-11eb-84eb-47f6ea01a964.png)
 
I imagine this is why you're getting so many abandoned carts. This has nothing to do with our plugin. Please try using another Magento theme or checkout as there's something wrong with this one!

**Comment by Giacomo120** [comment]
Yes, we need to make some corrections at check out which are already planned.
But that's not what I mean. For the umpteenth time, if my English isn't clear tell me because it seems you don't want to understand what I'm complaining about.
The problem is not the abandoned carts, those are reported after the customer logs in but does not continue the purchase, they have their own section where we can see them.
I repeat for the umpteenth time, the ones I am reporting to you, of which I sent the screenshot, are ORDERS.
It means that the customer clicked on "place order" and entered the payment screen of your gateway, but then decided not to complete the order, or simply was refused the transaction: in both cases, it is created the order in "Pending Payment".

**Comment by Giacomo120** [comment]
You did not click on "place order" and in fact I see your cart in the abandoned section.
"Abandoned carts" in Italian means "abandoned carts". In fact, in this case no pending orders have been created, nor is a number assigned or quantities changed.
I don't really know how to explain it anymore. You are really putting my patience to the test.

**Comment by Giacomo120** [comment]
![Uploading Screenshot_20201120_154942.jpg…]()

**Comment by Giacomo120** [comment]
![Screenshot_20201120_154942](https://user-images.githubusercontent.com/74073970/99813911-8d1c1680-2b48-11eb-9dfa-459500bc0f70.jpg)

**Comment by Giacomo120** [comment]
You did not click on "place order" and in fact I see your cart in the abandoned section.
"Carrelli abbandonati" in Italian means "abandoned carts". In fact, in this case no pending orders have been created, nor is a number assigned or quantities changed.
I don't really know how to explain it anymore. You are really putting my patience to the test.

**Comment by matthewrgourd** [comment]
Hi @Giacomo120, I have gone to the trouble of testing your checkout and given you my feedback. Your checkout / theme needs to be changed as it is not fit for purpose. As to why many of your customers, after being taken to our payment page (which I couldn't get to because there didn't seem to be a payment button as I indicated in the screenshot), then left without paying, I have no idea. FYI, if a customer is redirected to our payment page, an order is created in Magento, **whether or not they pay**. However, the ones who have paid are indicated in Magento with the "Complete" status. The ones where payment has not been collected are indicated by "Pending" status. I'm afraid we cannot prevent Magento from creating an order even if payment has not been taken because our solution is a redirect checkout rather than native. We hope to introduce the latter soon, but until then, as I say, there is no direct synchronisation between our plugin and Magento. Hope that clears things up for you and I'm sorry for the issues you've been experiencing. My advice is to sort out your theme / checkout problems and see if that improves matters with more customers following through with payment.

**Comment by matthewrgourd** [comment]
Extensive testing of checkout shows problem is with theme not Viva Wallet plugin. Closing issue as detailed advice given.
