### ISSUE TITLE
Creating payment from token + 3DS ?

### ISSUE THREAD

**Issue by deliverymanager** [VivaPayments/API#2004]
Is there a plan for charging a saved card (Tokenization) via the Web API but also being able to show a frontend dialog for the OTP process of the card?

**Comment by matthewrgourd** [comment]
Hi @deliverymanager, I'm sorry, I'm not sure I understand the question. When you say "OTP process" are you referring to the 3DS popup related to a payment?

**Comment by deliverymanager** [comment]
Let me explain.
In the standard process with the redirection frame the user that uses his card he is asked from his bank's card to enter an OTP.
Then the transaction is completed

If we already have a card token which ia the tranaaction id from a previous payment that had allowrecurring true, the we make the card charge using the WEB Api not the redirection process.

The question is if it is possible to show the OTP dialog for the saved card if needed by the bank during the payment process when using a tokenized card.

**Comment by matthewrgourd** [comment]
Hi @deliverymanager, no, because, according to the current PSD2 regulations, for recurring payments, you only need 3DS authentication to take place once (during card capture). Hope this helps.

**Comment by deliverymanager** [comment]
So the 3DS process for a card is only necessary during the normal payment process via the iFrame.
It is not needed based on the latest PSD2 regulations for the tokenized / saved cards that we charge using the WEB API with the transaction_id.
I hope you are sure and right about that.

And what about the new payment fields like Billing Address, Billing City, Billing etc, that most of the other banks are requiring right now to have these kind of information when they make charge card via their payment iFrame?

**Comment by matthewrgourd** [comment]
Hi @deliverymanager, so I can be sure, please let me know which of our online checkouts you're attempting to integrate, is it [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/), [Redirect](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) or [Native](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/)?

**Comment by deliverymanager** [comment]
I have integrated the Redirect method and it is working fine right now.
But other banks (Eurobank and Piraeus) have contacted us in order to update the payment gateway so that we include billing info like city, country, address etc.
This claim was made based on the "strong customer authentication and common and secure open standards of communication".

So my question is based on the (ΕΕ) 2015/2366 (PSD 2).

**Comment by matthewrgourd** [comment]
Hi @deliverymanager, from what you're saying I believe the best solution for you to implement would be our Native Checkout v2 checkout. This is more up-to-date and has more configurable parameters than Redirect Checkout. Please see below pages for more info. We have two options available, the first is API + JS; the second is API only:

- [Native Checkout v2 + Viva Payments JS](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/)
- [Native Checkout v2 API](https://developer.vivawallet.com/web-api-integration/native-checkout-v2-api/)
