### ISSUE TITLE
Only vapers S.L

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#2006]
Hi @matthewrgourd! this merchant tells me the next: (she is using prestashop 1.7.5.2)

we have a doubt because when you arrive at the page to leave the data of the card (checkout) the default language is English, can you put as default language Spanish? 

Would be possible change it?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, please get the merchant to install our latest plugin version, created today, using the below ZIP archive. It now has language auto-select included as a feature. Thanks.

[vivawallet1.7.zip](https://github.com/VivaPayments/API/files/5568267/vivawallet1.7.zip)
