### ISSUE TITLE
How to change the name of the payment method in Shopify

### ISSUE THREAD

**Issue by cextrahh** [VivaPayments/API#2008]
Hi, is there a way to change the name of the viva wallet credit card payment method in Shopify? "Credit or Debit Card" shows up as a payment method during the shopify checkout process. That dosen't makes sense for the german market when the whole website is in german. In the shopify backend we are not able to make any changes to the payment method names. Please let us know if you can change the name or tell us how to do. Otherwise the payment method dosen't makes sense for local markets.
![Bildschirmfoto 2020-11-20 um 14 23 42](https://user-images.githubusercontent.com/74776214/99804937-0d884a80-2b3c-11eb-8240-5113c1bfe48d.png)

**Comment by matthewrgourd** [comment]
Hi @cextrahh, unfortunately there are no settings available currently that enable this to be changed.
