### ISSUE TITLE
which API should I use?

### ISSUE THREAD

**Issue by ccastiglioni** [VivaPayments/API#2009]
Hello I am new to this API, I would like to implement a service in which my website will deposit money both in a bank account and in another card .. which of the three I start:

Native Checkout v2 3DS, Redirect checkout or Web API integration?

The bigger question is that I need to receive payments of various types of currencies and in the [fifth step](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) it is written "If you registered your account in a Eurozone country, it would be EUR with a code of 978."
so, can I use this Api? 

Note: I'm programming sistem a money transfer system. .  . please help me with any tips

**Comment by matthewrgourd** [comment]
Hi @ccastiglioni, if you're referring to an API that transfers money from a Viva Wallet account to another account that isn't Viva Wallet, I'm afraid this service isn't available. However, you can do transfers between Viva Wallet accounts / wallets no problem:

https://developer.vivawallet.com/web-api-integration/account-api/#balance-transfer
