### ISSUE TITLE
ΦΠΑ / TAX

### ISSUE THREAD

**Issue by spiritinlife** [VivaPayments/API#201]
Καλησπέρα,
Όταν χρησιμοποιώ το createOrder endpoint το price που θέτω είναι χωρίς φπα και περίμενα στην "απόδειξη" που εμφανίζεται μετά να εχει αυτόματα προστεθεί το φπα, αλλά αυτό δεν συμβαίνει.
Κάνω κάτι λάθος?
Πρέπει να υπολογίζω εγώ την τελική τιμή μαζί με το φπα?

**Comment by defilerc** [comment]
Καλησπέρα @spiritinlife ,

Το ποσό που χρησιμοποιείτε στην CreateOrder είναι το τελικό ποσό που θα χρεωθεί ο πελάτης. Επομένως, θα πρέπει να συνυπολογίζετε το ΦΠΑ στην τιμή του Amount στο CreateOrder.

Με εκτίμηση,
