### ISSUE TITLE
Viva payments failure

### ISSUE THREAD

**Issue by jimkarai** [VivaPayments/API#2010]
Hi there, have hooked up Viva Wallet for Woocommerce and all verified API's however when I reach the checkout page on my website I cannot enter the card details. No input fields are available. Everything is verified correctly inside Woocommerce and also Viva Wallet. Thanks, JIm

**Comment by matthewrgourd** [comment]
Hi @jimkarai, sorry to hear that, can I confirm that you followed the below instructions in order to download and install our latest plugin?

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

alternatively, the same instructions are provided directly on the WooCommerce platform here:

https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/

If you can also let me have your WooCommerce store URL and enable Viva Wallet so I can test in the next 30 minutes or so?

**Comment by jimkarai** [comment]
The url of the store is https://siennan.gr and i have it enabled in with
demo.vivawallet

Στις Δευ, 23 Νοε 2020 στις 10:52 π.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @jimkarai, please confirm whether you installed our latest plugin available from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ or are you using a different one?

**Comment by jimkarai** [comment]
Yes i use the plugin you describe as you can see on screenshot

Στις Δευ, 23 Νοε 2020 στις 1:32 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by jimkarai** [comment]
Στις Δευ, 23 Νοε 2020 στις 2:12 μ.μ., ο/η Dimitris Karaiskos <
dkaraiskos@gmail.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @jimkarai, the screenshot didn't come through? Can you try again?

**Comment by jimkarai** [comment]
Στις Δευ, 23 Νοε 2020 στις 2:50 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @jimkarai, I still can't see the screenshot but never mind, I've tested buying something from your website. I can confirm what you're saying. For some reason there is a problem viewing the fields from our payment gateway at checkout. We're not sure what this is yet, it could be an incompatibility with the theme or plugin you're using. We'd like to check if any other software could be interfering with ours. You can find out all the plugins installed from **WooCommerce > Status** in your Wordpress admin. In there you'll see lots of info but there are 2 relevant sections called **Active plugins** and **Theme**. Can you copy and paste their contents into this issue? Thanks!

**Comment by jimkarai** [comment]
Active plugins (28)
Product Size Charts Plugin for WooCommerce by theDotstore – 2.0.6 –
Installed version not tested with active version of WooCommerce 4.7.0
Arrowpress Core by AHT – 1.0.0
ArrowPress Importer by ArrowPress – 1.2.0
Classic Editor by WordPress Contributors – 1.6
Contact Form 7 by Takayuki Miyoshi – 5.3
Cookie Notice by dFactory – 1.3.2
Custom Content Shortcode by Eliot Akira – 3.8.6
Elementor by Elementor.com – 3.0.13
Enable Gzip Compression by Moki-Moki Ios – 1.0.3
JetSticky For Elementor by Crocoblock – 1.0.1
Kirki Customizer Framework by David Vongries – 3.1.5
Loco Translate by Tim Whitlock – 2.4.4
Regenerate Thumbnails Advanced by ShortPixel – 2.3.2
Shortcode Elementor by rs-theme – 1.0.1
Social Media Follow Buttons Bar by Space X-Chimp – 4.62
OpenHook by Rick Beckman – 4.3.0
Viva Wallet for WooCommerce by Viva Wallet – 1.2.0 – Installed version not
tested with active version of WooCommerce 4.7.0
WebP Express by Bjørn Rosell – 0.19.0
WooSwatches - Woocommerce Color or Image Variation Swatches by woomatrix –
3.0.0 – Installed version not tested with active version of WooCommerce
4.7.0
WooCommerce by Automattic – 4.7.0
WordPress Importer by wordpressdotorg – 0.7
WP All Import Pro by Soflyy – 4.6.3
WP Fastest Cache by Emre Vona – 0.9.1.2
WP Mail SMTP by WPForms – 2.5.1
WP All Import - WooCommerce Add-On Pro by Soflyy – 3.2.4 – Installed
version not tested with active version of WooCommerce 4.7.0
YITH WooCommerce Compare by YITH – 2.4.2 – Installed version not tested
with active version of WooCommerce 4.7.0
YITH WooCommerce Quick View by YITH – 1.4.6 – Installed version not tested
with active version of WooCommerce 4.7.0
YITH WooCommerce Wishlist by YITH – 3.0.16 – Installed version not tested
with active version of WooCommerce 4.7.0



Theme
Name: Lusion
Version: 1.2.5
Author URL: http://arrowhitech.com/
Child theme: – If you are modifying WooCommerce on a parent theme that you
did not build personally we recommend using a child theme. See: How to
create a child theme




Στις Δευ, 23 Νοε 2020 στις 6:07 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @jimkarai, thanks for sending that info. through. I can't immediately see why there should be a problem except maybe our plugin isn't compatible with Elementor or your Lusion theme, but I don't see why not. I will check with our plugin developer and get back to you as soon as I can...

**Comment by jimkarai** [comment]
Great, thanks!

Στις Τρί, 24 Νοε 2020 στις 10:28 π.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by jimkarai** [comment]
Good morning!Its the theme Lusion.I changed it instantly with  the default
wordpress theme and it worked.I will try again with a child theme of
lusion.If it doesnt work i will change theme.I will let you know


Στις Τρί, 24 Νοε 2020 στις 10:31 π.μ., ο/η Dimitris Karaiskos <
dkaraiskos@gmail.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi @jimkarai, did it work with the Lusion child theme?

**Comment by jimkarai** [comment]
Hi!No unfortunatelly it didnt work.I changed theme with oceanwp and it worked right away
