### ISSUE TITLE
shopify- direct payment installation guide help

### ISSUE THREAD

**Issue by Carshopcy** [VivaPayments/API#2011]
I need someone to guide me how to install the direct payment process on our shopify shop

**Comment by matthewrgourd** [comment]
Hi @Carshopcy, I'm sorry, I don't understand what you mean by "direct payment process". Please explain further, or, if you're referring to our payment plugin for Shopify, see installation instructions below:

https://developer.vivawallet.com/e-commerce-plugins/shopify/

Thanks.

**Comment by Carshopcy** [comment]
i want to install the viva wallet native payment v2 on my shopify shop

**Comment by matthewrgourd** [comment]
Hi @Carshopcy, we have available a solution called [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) but I believe the following conditions would need to be satisfied before you can do that:

1. Contractual agreement with Shopify to offer a native checkout through a third-party.
2. Development experience as you would need to integrate using our API together with Shopify's.

Just so you know, we requested to do this ourselves and are still waiting for Shopify's response. My recommendation is to use our existing [redirect plugin](https://developer.vivawallet.com/e-commerce-plugins/shopify/) for Shopify.
