### ISSUE TITLE
Woocommerce Missing Tab and Checkout Form

### ISSUE THREAD

**Issue by iamwobby** [VivaPayments/API#2012]
Hello

So I've installed the Woocommerce Vivawallet plugin on my shop. I have 2 issues as I followed the steps that were send to me from Vivawallet. So when I activate the plugin from the Payment settings on WooCommerce I don't get the extra tab to make the necessary adjustments and also I want to have the actual form on the checkout process and not just the vivawallet logo that will redirect me to make the payment. Ideally I would like to have the actual form on the checkout. How is this possible?

![viva-screen-2](https://user-images.githubusercontent.com/74908615/99959253-54bc4880-2d93-11eb-9091-805a8fda5669.jpg)

![vivawallet](https://user-images.githubusercontent.com/74908615/99958497-238f4880-2d92-11eb-850a-48b8b6f95b08.jpg)

**Comment by matthewrgourd** [comment]
Hi @iamwobby, before I can answer the first issue, what actually happens when you select the radio button for Viva Wallet? Does it not show the payment form on the same page once you click on it? It should do. I dont' understand the second question. Please let me know what you mean. There is no 'extra tab' for our plugin settings, only the **Payments** tab.

**Comment by iamwobby** [comment]
Hello @matthewrgourd when I select the radio button for Viva Wallet the form doesn't load...only the checkout button becomes Place order to redirects me to Viva wallet to make the payment....Regarding the second questions you answered it thanks!

**Comment by matthewrgourd** [comment]
Hi @iamwobby, to help me investigate further I'd like to find out all the plugins installed from **WooCommerce > Status** in your Wordpress admin. In there you'll see lots of info but there are 2 relevant sections called **Active plugins** and **Theme**. Can you copy and paste their contents into this issue? Thanks!

**Comment by iamwobby** [comment]
Hello @matthewrgourd 

Thank you for you prompt reply.

So here are the **active plugins** currently on the site.

Redux | by Redux.io + Dovy Paukstys – 4.1.23
Akismet Anti-Spam |   | by Automattic – 4.1.7
All-in-One WP Migration Unlimited Extension |   | by ServMask – 2.37
All-in-One WP Migration |   | by ServMask – 7.30
Back In Stock Notifier for WooCommerce \| WooCommerce Waitlist Pro | by codewoogeek – 1.9.9 
Better Search Replace |   | by Delicious Brains – 1.3.3
Classic Editor |   | by WordPress Contributors – 1.6
Contact Form 7 |   | by Takayuki Miyoshi – 5.3
Simple Custom CSS and JS |   | by SilkyPress.com – 3.34
Disable Comments |   | by WPDeveloper – 1.11.0
Envato Market |   | by Envato – 2.0.6
Facebook for WooCommerce |   | by Facebook – 2.1.4 
Google XML Sitemaps |   | by Auctollo – 4.1.1
Social Feed Gallery |   | by QuadLayers – 3.0.6
WPBakery Page Builder |   | by Michael M - WPBakery.com – 6.2.0
MC4WP: Mailchimp for WordPress |   | by ibericode – 4.8.1
Perfect Brands for WooCommerce |   | by QuadLayers – 1.8.5 
Product Input Fields for WooCommerce |   | by Tyche Softwares – 1.2.7
PW WooCommerce Gift Cards Pro |   | by Pimwick, LLC – 1.271
Retainful - Abandoned Cart Recovery Emails and Next Order Coupons |   | by Retainful – 2.5.0
SG Optimizer |   | by SiteGround – 5.7.5
Ship to Different Address Unchecked for WooCommerce |   | by eCreations – 1.2 
Shopkeeper Extender |   | by GetBowtied – 1.6.6
Shortcodes Ultimate |   | by Vladimir Anokhin – 5.9.4
Smart Slider 3 |   | by Nextend – 3.4.1.13
Stock Exporter for WooCommerce |   | by Webdados – 0.8.1 
Advanced Editor Tools (previously TinyMCE Advanced) |   | by Automattic – 5.5.1
Trustpilot-reviews |   | by Trustpilot – 2.5.811 
GDPR Cookie Consent Banner |   | by termly – 2.3.15
WooCommerce Viva Wallet Gateway |   | by Viva Wallet – 3.6.2 
WC Custom Thank You |   | by Nicola Mustone – 1.2.1 
WC Hide Shipping Methods |   | by Rynaldo Stoltz – 1.4
WooCommerce Weight Based Shipping |   | by weightbasedshipping.com – 5.3.7
Open Graph and Twitter Card Tags |   | by Webdados – 3.0.0
Braintree For WooCommerce |   | by Payment Plugins, support@paymentplugins.com – 3.2.11
WooCommerce Admin |   | by WooCommerce – 1.6.3 
WooCommerce Checkout Field Editor |   | by WooCommerce – 1.5.12 
WooCommerce PayPal Checkout Gateway |   | by WooCommerce – 2.1.0 
WooCommerce Sequential Order Numbers Pro |   | by SkyVerge – 1.12.0 
WooCommerce |   | by Automattic – 4.7.0
YITH Pre-Order for WooCommerce |   | by YITH – 1.2.12
YITH WooCommerce PDF Invoice and Shipping List Premium |   | by YITHEMES – 1.7.1 
YITH WooCommerce Wishlist |   | by YITH – 3.0.16

And Here is the **Theme** content

**Shopkeeper**
--
Version: | 2.9.34
Author URL: | https://www.getbowtied.com/
WooCommerce support: Yes

**Comment by matthewrgourd** [comment]
Hi @iamwobby, ok, I can see that you've installed the previous redirect version of our plugin (3.6.2). Please remove and replace with the Native version (v1.2.0). Installation instructions are here:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

Thanks!

**Comment by iamwobby** [comment]
@matthewrgourd Thank you so much for your support. That worked!
