### ISSUE TITLE
New account opend, activated but payments are not succesfull. Please help.

### ISSUE THREAD

**Issue by alxalbu** [VivaPayments/API#2013]
For the account ATDS SYSTEMS INTERNATIONAL SRL
I did an implementation and some tests. On the demo platform I can pay with the test card and a valid card, but on production they don't let me pay.
On the demo it tells me that the payment was made but I do not receive a callback on the url set www.vintu.net/viva/success nor fail at www.vintu.net/viva/fail in case of error.
So I tried on production, where any card I use for payment gives me a failed transaction and I also don't receive any callback on the urls set in this account.
https://www.vivapayments.com/web/checkout/result?s=6073062149519109&lang=en-US&eventId=0

**Comment by alxalbu** [comment]
I have used the simplest implementation: redirect v2

**Comment by alxalbu** [comment]
I do the post request with the account credentials and then generate the link for payment. When follow the link the production platform displayes correct data with our logo and data but after entering the cc data the payment fails and do not receive any callback.

**Comment by matthewrgourd** [comment]
Hi @alxalbu, before I go any further, please confirm which of our checkout solutions you're attempting to implement, [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) or [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/)?

**Comment by alxalbu** [comment]
I use Redirect Checkout.

You can test it's functionality on https://www.vintu.net/home/test

I have a button  wich launches a function on backend which makes a   post
request to Url from bellow with amount and credentials:
url = URI("https://www.vivapayments.com/api/orders") #prod

If post is successful It receives a parameter OrderCode
@payment_order=@body['OrderCode']

Then and I redirect the page to the link:
viva_payment_url="
https://www.vivapayments.com/web/checkout?ref=#{@body['OrderCode']}" #prod

After any  payment the result is Transaction rejected and I do not receive
any callback on the success or fail pages I set up on
https://www.vintu.net/viva/success or https://www.vintu.net/viva/fail
where I am waiting the parameters for transactionId.

Please check account validity. Till there everything works ok.

On Demo platform the payment is done properly, transaction success but I
also do not receive callbacks (redirection of pages with proper response of
transaction)

Thanks,
Alexandru Albu

Mobile/Whatsapp: +40764 111 211
Skype/YM: alx_albu

**Comment by matthewrgourd** [comment]
Hi @alxalbu, I believe you need to edit your Viva Wallet payment source (6173) which was originally set up for the domain `vintu.net`. Please try changing that to `www.vintu.net to` match your website's actual live domain name. Let me know how you get on.

**Comment by alxalbu** [comment]
Hi,
I did it with www.vintu.net
Same error.

Alexandru Albu

Mobile/Whatsapp: +40764 111 211
Skype/YM: alx_albu

**Comment by alxalbu** [comment]
Should we delete and recreate it with www.vintu.net?
Alexandru Albu

Mobile/Whatsapp: +40764 111 211
Skype/YM: alx_albu

**Comment by matthewrgourd** [comment]
Hi @alxalbu, it's ok, I managed to change it for you at this end. Can you try again?

**Comment by alxalbu** [comment]
Thank You,
It worked but I didn.t redirect the page to the destination page in order
to get the transactionId.
Alexandru Albu

Mobile/Whatsapp: +40764 111 211
Skype/YM: alx_albu

**Comment by alxalbu** [comment]
[image: image.png]
Alexandru Albu

Mobile/Whatsapp: +40764 111 211
Skype/YM: alx_albu

**Comment by alxalbu** [comment]
Can you find out why redirection is not working? Should we do something
else? The pages are ok and works properly.
We need to see the transactionID! to make the automatization further
Alexandru Albu

Mobile/Whatsapp: +40764 111 211
Skype/YM: alx_albu

**Comment by matthewrgourd** [comment]
Hi @alxalbu, the screenshot didn't come through? When you're doing the POST to `api/orders` have you replaced the body parameter `"SourceCode": "Default"` with `"SourceCode": "6173"` where you set up the redirect URLs?

**Comment by alxalbu** [comment]
No, I have set it www.vintu.net.
I will try now with: "6173".
Alexandru Albu

Mobile/Whatsapp: +40764 111 211
Skype/YM: alx_albu

**Comment by alxalbu** [comment]
Ok, thanks very much Matthew!
Works now with this modification.
May I suggest to send an email to Quality Manager to request modification
of the documentation for customers? Just instead of domain field should be
the url address of the web page and that in the post request should be
places Source: source_id as in interface.
In rest it was flowless!!
Thank you very much again  for help for saving me to start again an
implementation on other operator.
I will continue with payment verification for transactionId  received on
callback.


Alexandru Albu

Mobile/Whatsapp: +40764 111 211
Skype/YM: alx_albu
