### ISSUE TITLE
Live Error transaction never send transactionId

### ISSUE THREAD

**Issue by adamsony06** [VivaPayments/API#2014]
Dear,

So I retrieve all the data about customer Id and secret code, everything works fine except for the transaction part, after we enter the code received by phone and validated by the 3DS Authentification, I try to make an api call to transaction, but the problem is, we never received the transactionId, just a 200 response with nothing. Is it normal ?

Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06, sorry to hear that. May I ask, first, which of our checkouts are you attempting to implement, [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/), [Redirect](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) or [Native](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/)?

**Comment by adamsony06** [comment]
Hello,
I use the Native Checkout v2 Credentials api, everything works fine except the call to the transaction API which fails everytime like described.

Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06, please have a look at our [Native Checkout v2 documentation](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) and let me know which step you're referring to. Is it [Step 5: Make the actual charge](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-5-make-the-actual-charge)?

**Comment by adamsony06** [comment]
Yes it's this step ! In demo mode it's working but in live, it's not working, no transactionId sent despise of 3DS Authentification succeed.

Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06, ok, thanks for confirming. So you have sent the request in Postman with the charge token in the body parameters as follows?

**REQUEST**

POST /nativecheckout/v2/transactions

Body parameters
```
{
 "amount": 1000,
 "preauth": false,
 "chargeToken": "<charge token>",
 "installments": 1,
 "merchantTrns": "Merchant transaction reference",
 "customerTrns": "Description that the customer sees",
 "currencyCode": 826,
 "customer": {
      "email": "native@vivawallet.com",
      "phone": "442037347770",
      "fullname": "John Smith",
      "requestLang": "en",
      "countryCode": "GB"
   }
```
**RESPONSE**

In the response, you should get a transaction ID. If you don't get a transaction ID, you should receive an error code instead. Can you tell me what that is?

**Comment by adamsony06** [comment]
Yes i can confirm that I used a back-end channel, actually a php file. And I don't get any error, just a response 200 like it worked. I can share with you the php code.

Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06, sure, please share your php code, replacing any confidential info. with placeholders.

**Comment by adamsony06** [comment]
Okay, i'll share you.
```php

<?php

    $url = 'https://api.vivapayments.com/nativecheckout/v2/transactions';
    $amount = $_POST["amount"];
    $charge = $_POST["ctoken"];
    $mail = $_POST["mail"];
    $phone = $_POST["phone"];
    $nom = $_POST["nom"];
    $token = $_POST["token"];

    $headerArgs = array(
        "Authorization: Bearer ".$token,
        "Content-Type: application/json",
        "Content-Type: text/plain"
    );

    $postArgs = array(
        'amount' => $amount,
        'chargeToken' => $charge,
        'sourceCode' => "mysourcecode",
        'installments' => 1,
        'preauth' => false,
        'merchantTrns' => "Merchant transaction reference",
        'customerTrns' => "Description that the customer sees",
        'currencyCode' => 978,
        'customer' => array(
            'email' => $mail,
            'phone' => $phone,
            'fullname' => $nom,
            'requestLang' => 'fr',
            'countryCode' => 'FR'
        )
    );


    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($curl, CURLOPT_ENCODING, "");
    curl_setopt($curl, CURLOPT_MAXREDIRS, 10);
    curl_setopt($curl, CURLOPT_TIMEOUT, 0);
    curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);
    curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
    curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($postArgs));
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headerArgs);

    $result = curl_exec($curl);
    curl_close($curl);


    // to debug the call you can uncomment the following lines to check response from the API
    // and get transactionId if success
    $result = json_encode($result);
    print_r($result);
    



?>```

**Comment by matthewrgourd** [comment]
Hi @adamsony06, I've had a quick look and can't see any glaring errors. Unfortunately we cannot advise on custom code beyond the API calls. I've followed the steps in our [Native Checkout v2 guide](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) and cannot recreate the issue. The steps are working fine. My advice is to use our [working example in HTML](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#working-example-in-html) (and Postman for the subsequent POST to `/nativecheckout/v2/transactions`) to attempt to visualise the flow before revisiting your code.

**Comment by adamsony06** [comment]
Hello,
So i tried to make a post call in my transaction.php API via Postman and it returns an empty result, is it normal ? I have checked multiple time, how can i debug this ?

<img width="1344" alt="Capture d’écran 2020-11-24 à 14 00 21" src="https://user-images.githubusercontent.com/58440550/100098003-acbf8180-2e5d-11eb-8941-3ab434c56f0d.png">

**Comment by adamsony06** [comment]
I am reposting it because i let critical information, so it sends an empty result
<img width="1343" alt="Capture d’écran 2020-11-24 à 14 13 18" src="https://user-images.githubusercontent.com/58440550/100099158-53585200-2e5f-11eb-9b50-edaa2f3352a1.png">

**Comment by matthewrgourd** [comment]
Hi @adamsony06, I'm sorry, but I don't know what you're doing there. Correct call to generate a transaction ID from your charge token is as I already posted in https://github.com/VivaPayments/API/issues/2014#issuecomment-732798189. You should try that in Postman.

**Comment by adamsony06** [comment]
Do you have to activate something on your side ?

Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06, no. The only thing you need to make sure you do is to generate a bearer token for authentication, but I think you did that because you got a 200 ok? If unsure about this please re-read the section in our developer portal on OAuth 2 authentication:

https://developer.vivawallet.com/web-api-integration/authentication/#identityserver-oauth-2-authentication

After looking at your screenshot (which is completely wrong in terms of the call, I'm afraid. You should not be doing a POST to `oneip/transaction.php`).  I advised you to try the following in Postman. What was the result?

**REQUEST**

POST /nativecheckout/v2/transactions

Body parameters
```
{
 "amount": 1000,
 "preauth": false,
 "chargeToken": "<charge token>",
 "installments": 1,
 "merchantTrns": "Merchant transaction reference",
 "customerTrns": "Description that the customer sees",
 "currencyCode": 826,
 "customer": {
      "email": "native@vivawallet.com",
      "phone": "442037347770",
      "fullname": "John Smith",
      "requestLang": "en",
      "countryCode": "GB"
   }
```
**RESPONSE**

In the response, you should get a transaction ID. If you don't get a transaction ID, you should receive an error code instead. Let me know the outcome either way, please, otherwise I won't be able to help you.

**Comment by adamsony06** [comment]
Dear,

It work from my computer, i don't know what's wrong, because i use my iOS to test everything to show token and charge_token also, i have to debug...

Best regards.

**Comment by adamsony06** [comment]
You can close the issue it seems that there is an error on the tutorial in the header part :  "Content-Type: application/json",
        "Content-Type: text/plain", two Content-Type, I have to delete the second one and it worked.
Please remove it from your tutorial, it will avoid such problems in the future : [https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#working-example-in-html](url)

Best regards.

**Comment by matthewrgourd** [comment]
Hi @adamsony06, thanks for spotting that. I will update asap. I didn't realise you were using our php code snippet.
