### ISSUE TITLE
The specified api action is disabled for the merchant 51476232-3856-489d-8cf8-ae8dff8b1eb4, please consult the documentation

### ISSUE THREAD

**Issue by mrusciel** [VivaPayments/API#2015]
Necesito ahora que he hecho las pruebas en el demo, me autoricen la cuenta de producción, para el simple checkout
el id de comerciante es: ****

Saludos,
Maite.

**Comment by matthewrgourd** [comment]
Hi @mrusciel that's done for you now.

**Comment by mrusciel** [comment]
Thanks!
