### ISSUE TITLE
Redirect checkout

### ISSUE THREAD

**Issue by ManTnd** [VivaPayments/API#2016]
There are parameters returned after successful transaction that are not included in your the docs (https://developer.vivawallet.com/online-checkouts/redirect-checkout/) What is the "eci" param? What are the possible return values?

I also got eventId = 2046 in a failed transaction, which is not included in the errors list (https://developer.vivawallet.com/web-api-integration/error-codes/). I suppose that more codes could exist. Are there any updated docs? What is the description of 2046?

**Comment by matthewrgourd** [comment]
Hi @ManTnd, so that I can help you further, please can you share with me the following:

- details of the exact API call you're making
- the request body (if applicable)
- the response body

**Comment by matthewrgourd** [comment]
Closing as no reply
