### ISSUE TITLE
Payment button on Native Checkout v2 page redirects to viva demo login page

### ISSUE THREAD

**Issue by skapator** [VivaPayments/API#2017]
On a new Native checkout (redirect) new transaction page (demo environment), clicking the charge button redirects to https://demo.vivapayments.com/en/signup instead off the web success or failure redirect.
Also clicking the change language button has the same effect.

![demo-signin](https://user-images.githubusercontent.com/1220837/100071716-09ae3e00-2e44-11eb-998f-1c2f60fa5f53.png)
![newtrns](https://user-images.githubusercontent.com/1220837/100071728-0c109800-2e44-11eb-97c5-4815af081e24.png)

**Comment by matthewrgourd** [comment]
Hi @skapator, sorry to hear that. Are you attempting to implement a custom integration with our website using our Redirect Checkout solution? I need a bit more context / background information and your live website address / Viva Wallet merchant ID (demo) if possible.

**Comment by skapator** [comment]
Hi @matthewrgourd ,
I am using the php create_order example as is.
It is a local environment  (laravel/homestead), no live setup yet.

![image](https://user-images.githubusercontent.com/1220837/100097482-3a529f80-2e65-11eb-87da-7fbfa6dae72b.png)

**Comment by matthewrgourd** [comment]
Hi @skapator, I believe for your demo to work correctly, even though you're only testing, the domain name needs to be publicly available on the internet. A workaround is to use something like [ngrok](https://ngrok.com/product) to tunnel through to your localhost but give you a public URI which you can then use to configure the payment source (screenshot above).

**Comment by skapator** [comment]
Thanks @matthewrgourd,
Will try that.
Just post it because it seemed to work fine couple weeks ago with the local domain.

**Comment by skapator** [comment]
Hi @matthewrgourd,
Unfortunately the issue persists with a public domain (not ngrok, live server).
Payments on this app are not public, users have to register in order to purchase an appointment so I can not provide a public url.

Here is the code used to redirect to viva payments checkout page:

```php
    $request_url            = env('MIX_VIVAP_API_URL');
    $merchant_id          = env('MIX_VIVAP_MERCH_ID');
    $api_key                 = env('MIX_VIVAP_API_KEY');
    $amount                 = get_setting('appointment_price'); // Amount in cents
    $allow_recurring     = 'false';
    $request_lang         = 'el-GR';
    $source                   = env('MIX_VIVAP_CALLBACK_CODE'); 

    $postargs = 'Amount='.urlencode($amount).'&AllowRecurring='.$allow_recurring.'&RequestLang='.$request_lang.'&SourceCode='.$source;

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $request_url);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $postargs);
    curl_setopt($ch, CURLOPT_HEADER, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_USERPWD, $merchant_id.':'.$api_key);
    curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'TLSv1.2');

    $response = curl_exec($ch);

    $header_len  = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    $res_header  = substr($response, 0, $header_len);
    $res_body     =  substr($response, $header_len);

    curl_close($ch);

    // Parse the JSON response
    // return response([0, $request_url], 422);
    try {
        if(is_object(json_decode($res_body))) {
            $res_obj = json_decode($res_body);
        } else {
            preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $res_header, $match);
            return response(trim($match[1]), 422);
        }
    } catch( Exception $e ) {
        return response($e->getMessage(), 422);
    }

    if ($res_obj->ErrorCode==0) {	//success when ErrorCode = 0
        $appointment->update([
            'user_id' => $request->user_id,
            'order_code' => $res_obj->OrderCode,
            'status' => 'pending',
        ]);

        return response(json_encode($res_obj), 200);
    }
    else{
        return response($res_obj->ErrorText, 422);
    }
```

**Comment by matthewrgourd** [comment]
Hi @skapator, apologies, I'm not 100% sure our [Create order](https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php) code sample is working properly. One thing to check is are you passing the `sourceCode` parameter with a value of **5711** to denote the payment source you set up for your domain?

**Comment by skapator** [comment]
Thanks for your time @matthewrgourd 
The sourceCode val is from the env file. Checked that it is set to 4511 which is the public domain Payment Source.
I tried hordcoding it, no change.
The Create order sample code does return an order_code and the it does take the user to the newtransaction page for that order_code.
There seams that every button just goes to viva demo login page.
Are you suggesting that the order_code returned from Create order code is somehow "invalid" ?

**Comment by matthewrgourd** [comment]
Hi @skapator `sourceCode` value should be **5711** according to your screenshot (not 4511). I think that may be the crucial bit for everything to work. Also, I'll say it again, I believe that thcv2.test needs to be resolvable on the public internet, although I know you mentioned you had a workaround. One other suggestion, if you generated an order code successfully, have you tried appending it to the following URL as stated in [step 2](http://developer.vivawallet.com/online-checkouts/redirect-checkout/#step-2-complete-payment-details) of our Redirect Checkout guide? 

`https://demo.vivapayments.com/web/checkout?ref=`

**Comment by skapator** [comment]
Hi @matthewrgourd  the screenshots on my first post are from my local setup with the thcv2.test domain which had the 5711 payment source code.
I have moved the project since then to a live server with a public domain and anew payment source of 4511 for that public domain.

**Comment by matthewrgourd** [comment]
Hi @skapator, aha, ok, makes sense now! In that case, have you made sure to replace the base URL `https://demo.vivapayments.com` with `https://www.vivapayments.com` in all the API calls?

**Comment by skapator** [comment]
@matthewrgourd NO but I don;t want to use viva production now, I need to work with viva demo env

**Comment by matthewrgourd** [comment]
Hi @skapator, please close this issue if you feel your problem was addressed adequately.
