### ISSUE TITLE
Redirect πισω στο site

### ISSUE THREAD

**Issue by sots13** [VivaPayments/API#202]
Γειά σας,

Υπάρχει ένα πρόβλημα σε ένα prestashop site που φτιάχνουμε. Χρησιμοποιώ ένα module της ActionWeb για την συνδεση με Viva. Όταν βαζω τα demo credentials (API, Merchant ID, Payment Source) όλα λειτουργουν σωστά και επιστρέφω στο site μετα την πληρωμή. Όταν χρησιμοποιώ όμως τα κανονικά credentials (η source είναι ενεργή) η πληρωμή εκτελείται κανονικά αλλά δεν επιστρέφω ποτε στο site για να μπορέσει το συστημα μας να περάσει την παραγγελια. Στις πληρωμές, στην πηγή εξακολουθεί να φαινεται η Default ως πηγη ενω ειναι ενεργή αυτη που εχουμε φτιαξει εμεις.

Περιμένω την απάντηση σας,

Ευχαριστώ πολύ

**Comment by defilerc** [comment]
Καλησπέρα @sots13 ,

Θα πρέπει κατά το CreateOrder να χρησιμοποιήσετε το SourceCode της καινούριας πηγής που έχετε φτιάξει, όπως περιγράφεται εδώ: https://github.com/VivaPayments/API/wiki/Optional-Parameters

Αν δεν χρησιμοποιήσετε κάποια παράμετρο, το SourceCode που χρησιμοποιείται είναι η "Default" πηγή. Θα πρέπει να χρησιμοποιήσετε την καινούρια πηγή που έχετε δημιουργήσει.

Με εκτίμηση,
