### ISSUE TITLE
3DS issue - Redirect

### ISSUE THREAD

**Issue by NTRXIT** [VivaPayments/API#2022]
Hello, many of our clients experience a 3DS Secure window when trying to checkout. The window doesn't show anything as it's just a broken image or no content. We are using the redirect method on Magento2 and this is greatly affecting our conversion rates, especially now at Black Friday.

**Comment by matthewrgourd** [comment]
Hi @NTRXIT, so that I can investigate further, please may I have you website address?

**Comment by NTRXIT** [comment]
Yes, sure but I'm not willing to share in public. Our conversion rate was greatly hurt by this issue.

**Comment by matthewrgourd** [comment]
Hi @NTRXIT, no problem, can you send me and email instead in that case: mgourd@vivawallet.com. If you can include your website address and merchant ID and quote this issue (#2022) I will investigate.

**Comment by matthewrgourd** [comment]
Hi @NTRXIT, thanks for emailing me that info. do you have a specific date you want me to check? I have access to your account details now. Over the past month I can see 240 transactions, 73 of which were rejected by the card issuer.

**Comment by NTRXIT** [comment]
Hi Matthew,

You can check the dates between 26-30 of November. We had a lot of
complaints from customers.

Thank you.

On Mon, Nov 30, 2020 at 6:44 PM matthewrgourd <notifications@github.com>
wrote:

> Hi @NTRXIT <http://email.anthraxpaintball.com/c/eJxFTs2KgzAYfJp4LO4XTdZDDonVZikbWrE_einGJCprqXQtpW_ftJfCMMwwzDCGWYAEm2BgKZd4W586bqYCvmi_vjeJw4ZOu_QulFpuK4SXl8fmb6cTvvLa1Y6sOYrCczOMi-7N7eUc9CxqtXXO0ojYsMVUh9A2hBptvolPgAQj6-d5-keYI8g9umHub_rV9kaVxfGnDK7saqfxgUBwFeW_WUxSmUFcHotKAd2QPIZMSJHthZIyrfcHiCt_5l1afAafolBFTw>, thanks for emailing me that info.
> do you have a specific date you want me to check? I have access to your
> account details now. Over the past month I can see 240 transactions, 73 of
> which were rejected by the card issuer.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <http://email.anthraxpaintball.com/c/eJxFj81ugzAQhJ_G3Bo5a2zwgYMhEKqoFokaWrhEJpgfFRoUSCPevoZLpNVoPmlGu1t6GoCT0mq9QMTkmF9qUQ4n2DrN4al4RUpnOAdPX8rdMUNkd5uTn3PBxd74Kq_YQSAb96rtNvWq11tvNR4mzKWFywk3DvC1VNuKaUfZ3C4YJtrqvGaahhERgSAyU7dT8yiWtoG0_VOJmnv9O40GRfJutB3Hh14QMAACsrLJL6k3h1CzCWPXunt3PXQzAl9IO_oIKQviEOjn9ymT4CQsohD6sR-mvozjIE-_gGbmg7W0eV3xDwB7VIg>,
> or unsubscribe
> <http://email.anthraxpaintball.com/c/eJxFj8tugzAURL8Gdo3A5uUFCwMmVlIsEkoKbCpeBqsEEA9F-fu66aLS6GpmpCPdadwWAAQbVbg-pvBSfHW4ma9At_vzo0QcNvac-g-PseCSKzCYnvF3WiF8lJ4X3DpjxdDupRgO3evW013tXQSBVqPW0XSkOzXiDgeOaYNGt2XfNlwd3H7b5lWBWAGhVCe2fq9-aRnGaRNc1OUmpnGVeR_XvVrrRVTtW7lvvawwM8KIwJMZH8kpiyO7IDSk70kSB5mHmc_CJDJSYkUsvKiLu7Tz8FSA94eZlk8JMD-ya86AHVuhCYhHPXLzGKV-cfsEZi5XvaDD_2c_oRxbzw>
> .
>


-- 

Kind regards,


Stergios Kontogiannis


Technology Specialist

Anthrax Sportswear
1i odos Tagaradon, 57001, Thessaloniki, Greece
Τ: +30 23920 72063

**Comment by NTRXIT** [comment]
In addition to my previous email, I am attaching a screenshot from a client.
[image: 128137168_469772410667905_900156060341256897_n (1).jpg]

On Tue, Dec 1, 2020 at 11:14 AM Stergios Kontogiannis <
stergios@anthraxpaintball.com> wrote:

> Hi Matthew,
>
> You can check the dates between 26-30 of November. We had a lot of
> complaints from customers.
>
> Thank you.
>
> On Mon, Nov 30, 2020 at 6:44 PM matthewrgourd <notifications@github.com>
> wrote:
>
>> Hi @NTRXIT <http://email.anthraxpaintball.com/c/eJxFjsFqhDAYhJ8m3ir6J1E85BCtNj3U1t3UqpeiMaioVGyU2qdfu5fCMDAM3zAt0wABbq2BRVzgrPocuvV35P74w3NA-HGZo_1BHBupxmyT2y7BdKZqzka8vz45V46IM9fDZHd3V1-z1TOHuNBArVvtEaW06zo-UU1AAkz9VinPmlhvzPKNMEeQnOoG02_NH32GVF6KZ2mtbNXLdCAIeUqSl5h6kYiByuJSpuC_eQmFOBRhnIepEFGVfwAtzzN3yP4fvAENvEWg>, thanks for emailing me that
>> info. do you have a specific date you want me to check? I have access to
>> your account details now. Over the past month I can see 240 transactions,
>> 73 of which were rejected by the card issuer.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <http://email.anthraxpaintball.com/c/eJxFj0FPhDAUhH9Nue2meaVUDhwKgvUgsorocjFlaaABlEAh4q-3cDGZTPLlzSTz6kAB-KR2dBBxQS7lp26m346z7ocXgMj9OETrSWyLW3aXJV_WHExjyspexNvzA37lyMWD1P25Ofz2PThtIAlVjNYVxVUlpUddBcxTityYr1TNpNMHrTHjjAhHkFg12rRLtbctFHqVmdwG9WVmizx7tK7neVE7AgZAQA62-T11YoT6mGB850zBpMZ-QxDy1E2eYupFIgaaf7xcU2CZl1CIQxHGRZgKEZXFO9Cr_eAonf9X_AH6KVb1>,
>> or unsubscribe
>> <http://email.anthraxpaintball.com/c/eJxFj8tugzAQRb8GdomMjUFdsDDExIoKJYVQwqbCQMDiKbCjpl9fmi4qjUY69-pIM5VTQ_iCKl04HmHonH-KZvnuiN19kRRq6DAP3n3HHsrMu7NK1D2BspE53xp2eTuCmGgmGArR75vnLqdBbx0T8IqDW4k4qGxklBYABYZmZWBUl7gw9N5ppZxXDREN-ts0QraK_9objJMUN1EWUkzjurEaV8XXchG83hVKtltEQtMPKDrh6EhPWRTYOWU-e43j6JC5JPRCPw7MC7WC0D_ri7PUc__QoPunYctjFOIke7-G0I4sH0PqMpembsiYl6cfEF-3r57S_v-yHxK0XUM>
>> .
>>
>
>
> --
>
> Kind regards,
>
>
> Stergios Kontogiannis
>
>
> Technology Specialist
>
> Anthrax Sportswear
> 1i odos Tagaradon, 57001, Thessaloniki, Greece
> Τ: +30 23920 72063
>
>

-- 

Kind regards,


Stergios Kontogiannis


Technology Specialist

Anthrax Sportswear
1i odos Tagaradon, 57001, Thessaloniki, Greece
Τ: +30 23920 72063

**Comment by matthewrgourd** [comment]
Hi @NTRXIT, I've checked your transactions for 26-30 of November and can see that you had 46 failed transactions versus 106 successful payments. I'm seeing a lot of "Do Not Honour" from both Visa and Mastercard. That can mean a number of things but usually it means the card issuer suspects a card has been used fraudulently.

**Comment by NTRXIT** [comment]
Hello,

I understand. But the error message is broken and the client doesn't have a
clue why this is happening or what is wrong. This is not acceptable when
making a payment where everything must be clear and feel safe. Also, I
personally tried a card that never ever gave me issues anywhere in the
world and got blocked until it suddenly didn't. Same cards that have no
issue using another card payment gateway from a Greek bank. This doesn't
make sense and having this in mind kills all benefits of using Viva
payments in the first place. Looking at the GitHub issues I found many
other similar tickets about the specific issue and saw they were mostly
dismissed with the same reasoning as I'm given now. I strongly believe
there is some backend issue on your side.

On Tue, Dec 1, 2020 at 1:57 PM matthewrgourd <notifications@github.com>
wrote:

> Hi @NTRXIT <http://email.anthraxpaintball.com/c/eJxFjl0LgjAYhX_NvCvqnSu82MX8Ygszi1DrRuZmzXAUZZT_PusmODxwLp7D0bQB8LB2WhowjrfHyhj2SpJLESTLFRniytrMs9XcrMJFEuangmWbN5u8EA6hUAy5Myvbbnr-UV2tY-hSL04EpASp9Vw2Cmuoa6WI8mrdKKWdjpq-vz0QZgjiMee2N8_6a48l3e9KsXfu9N7cugGBz1I3XkfAXZG66yiIdiVnpcgJCCFwlPsp58ExL4AcxjM_afof_ACqzUX9>, I've checked your transactions
> for 26-30 of November and can see that you had 46 failed transactions
> versus 106 successful payments. I'm seeing a lot of "Do Not Honour" from
> both Visa and Mastercard. That can mean a number of things but usually it
> means the card issuer suspects a card has been used fraudulently.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <http://email.anthraxpaintball.com/c/eJxFjz1vgzAYhH-N2RKZ1zaUgcHhQzgilHaANAtysBNTQRsF0pR_X8NS6XTSI91JdyrUAAFRThdGPCNvp8YY_szzzzrK_T2b02YYymBoXLOPvTyuLjUvX3_55olIDHXLEcWD7PrtdfX2e3BMSAhp2eWMQSoitesqX2HWKvkCKtDU9Zw-NNN0GxHhCFKrazeZx3lpW6i6H1nKedBf02iRl8J6N44PvSBgAARkZZtfUhufeAx7QLFzD-_61s8Idryg6SGBjIqCHpIoeT9m_CgqBkIIklS7IsuiU1UD-7AP1tL2f8UfL4lVMg>,
> or unsubscribe
> <http://email.anthraxpaintball.com/c/eJxFj9FugjAUhp8G7jSzLRIuuKgFBAadDAbiDaEFbRcBAyXOt5e5iyUn5-T7ky85f2O3AFiw0aVNsA-TUyUEvkfRd0EiMzQeXtV1B6urNiJ0tpGTnwt8-PjBq7sGHVBwrKG3rpbX9eW1-dDpwmYcNVsDWIwBxOvlWDVv2Blxs7XYxtzoV1sodZs0iDXgLXORSszs116gH5Q8S14rOfTTwnM_zWzio2Ttqp6VWCJMkRe70KTZfu-QMszCAJIkS9PsvYSYEuqlMfpytzH1En20x_Z2fWhg96cBHwUUxS5xP48-Pga5AYIggG6-o75PTnkBjHJp9ZLW_589ASXzXNo>
> .
>


-- 

Kind regards,


Stergios Kontogiannis


Technology Specialist

Anthrax Sportswear
1i odos Tagaradon, 57001, Thessaloniki, Greece
Τ: +30 23920 72063

**Comment by NTRXIT** [comment]
Also, how is it possible for a card "Do Not Honour" from the Magento redirect and it does not when I charge the card from the backend of Viva Wallet?

**Comment by matthewrgourd** [comment]
Hi @NTRXIT, when you say from the "back-end of Viva Wallet", do you mean using Quick Pay?

**Comment by NTRXIT** [comment]
It must be virtual POS.

**Comment by matthewrgourd** [comment]
Hi @NTRXIT, ah you mean Virtual Terminal? This is because Virtual Terminal does not include [3DS](https://en.wikipedia.org/wiki/3-D_Secure) which is more secure and protects you from potential customer fraud.

**Comment by NTRXIT** [comment]
OK I see. How about the broken error popup? The multiple denials until it suddenly work with the same card? I literally have clients that tried 3+ times and finally went through eventually. How about cards having issues only with Viva?

**Comment by matthewrgourd** [comment]
Hi @NTRXIT, I gather that you're still having problems. Please enable the Viva Wallet plugin for the next 30 minutes so that I test again.

**Comment by NTRXIT** [comment]
Hi @matthewrgourd, it's enabled constantly at this point.

**Comment by matthewrgourd** [comment]
@NTRXIT, I can't see it at the moment?

![Screenshot 2020-12-04 at 11 08 04](https://user-images.githubusercontent.com/44943019/101156809-0fb0d580-3621-11eb-8c5f-b6e1c9ba4bab.png)

**Comment by NTRXIT** [comment]
It's the credit/ cash card method.

**Comment by matthewrgourd** [comment]
Hi @NTRXIT, I tested again and your checkout through Viva Wallet is working fine. I just tested with a card with no funds so you will have received an order that will later be cancelled automatically. There is no technical issue. However, I appreciate what you're saying about the multiple payment rejections. It is somewhat unusual so I will escalate one of my colleagues in our Operations Team.

**Comment by NTRXIT** [comment]
OK thank you. From what I noticed it seems that the service is not responding for periods of time. I would get all attempts rejected from different clients in a specific period and then suddenly every order goes through with no issues. Also please note the broken 3DS image that clients were getting. This left customers puzzled and also when they returned to the site their cart was also gone.

**Comment by matthewrgourd** [comment]
Hi @NTRXIT, our Ops Team has confirmed that there is no technical issue. They do not see anything strange as this would affect all of your transactions so far. Most of the rejections refer to issuer's response (do not honor). Most of these attempts relate to non-European cards. That could be an issue, but has nothing to do with your setup. Regarding the 3DS popup not displaying correctly, again, this is not a Viva Wallet thing. Different issuers have different implementations. Thank you.
