### ISSUE TITLE
Viva wallet simple checkout

### ISSUE THREAD

**Issue by panospepper** [VivaPayments/API#2024]
hello, i would like to get access to the Simple Checkout API

**Comment by matthewrgourd** [comment]
Hi @panospepper, ok, please send me your Viva Wallet Merchant ID and I will do that right away.

**Comment by matthewrgourd** [comment]
Hi @panospepper do you still want us to enable the Simple Checkout API? If you prefer to send your merchant ID by email confidentially, my address is mgourd@vivawallet.com. Please quote this issue (#2024) if you do. Thanks!
