### ISSUE TITLE
Native Checkout v2 API issue

### ISSUE THREAD

**Issue by aasghar551** [VivaPayments/API#2026]
I have integrated Viva Wallet Native Checkout v2 sandbox API. Some times it processed the transaction successfully and some time giving this error. Most of time its throwing below error

[status] => 400
[message] => PaymentsCardHolderAuthenticationInvalidStatus
[eventId] => 2061

You can run the script here
http://trueraffles.co.uk/vivawallet/index.php

I have attached the successful transaction screenshots

<img width="960" alt="success" src="https://user-images.githubusercontent.com/23654213/100475496-12816700-3105-11eb-8a48-177ea8105916.png">
<img width="957" alt="transaction" src="https://user-images.githubusercontent.com/23654213/100475499-13b29400-3105-11eb-84a7-9e91a8aca4ce.png">

Can anybody help me with the issue?

**Comment by matthewrgourd** [comment]
Hi @aasghar551, the "2061" Event ID means 3DS flow incomplete (Browser closed before authentication finished) as stated under [Rejection reasons](https://developer.vivawallet.com/web-api-integration/error-codes/#rejection-reasons) on our [Error codes](https://developer.vivawallet.com/web-api-integration/error-codes/) page on the Viva Wallet Developer Portal.

**Comment by ccastiglioni** [comment]
@matthewrgourd and @aasghar551,   I got the same problem, when I recive the request "chargeToken" the redirectToACSForm returns a empty string.. like :

```
array(2) {
  ["chargeToken"]=>
  string(32) "ctok_RtcIhoihQZ_9aCzd-LtH6qeFxz0"
  ["redirectToACSForm"]=>
  string(1160) "



"
}
```
This redirectToACSForm is must be used for may implementation?

**Comment by matthewrgourd** [comment]
Hi @aasghar551, you may want to try again and let me know the result as we recently made some changes to our demo environment meaning you shouldn't experience the same problem again.

**Comment by matthewrgourd** [comment]
Hi @ccastiglioni, you should test this on demo first as we have a 3DS simulator that will populate that parameter if you use the 5511070000000020 test card number.

**Comment by aasghar551** [comment]
Sorry for the late response. My client was so hurry and I had integrated another viva wallet API and its working fine. If anyone need that API I can provide. Thanks
