### ISSUE TITLE
error pay ??

### ISSUE THREAD

**Issue by renatoDragan** [VivaPayments/API#2027]
<configuration>     <system.web>         <customErrors mode="Off"/>     </system.web> </configuration>
--

**Comment by matthewrgourd** [comment]
Sorry, @renatoDragan, I cannot help without a description of the problem. More info please!

**Comment by renatoDragan** [comment]
Web.Config Configuration File
configuration>
system.web>
customErrors mode="Off"
system.web
configuration

**Comment by matthewrgourd** [comment]
Sorry, that doesn't help. You're attempting to implement our Simple Checkout, is that correct? (I'm having to guess here). The API key suggests Simple Checkout but beyond that I'm still going to need more info.

**Comment by renatoDragan** [comment]
https://www.vivapayments.com/web/checkout/getpaymenttoken
POST
500
SIMPLE CHECKOUT
MAIL AT MGOURD WITH IMAGE

**Comment by matthewrgourd** [comment]
Hi @renatoDragan, thanks for the info. Looks like you may not have the Simple Checkout API enabled for your Viva Wallet account. May I have the Merchant ID or website address so that I can check, please?

**Comment by matthewrgourd** [comment]
Thanks for the screenshot you sent. I checked your Viva Wallet account and you have had successful transactions up until 28 November. When did you start experiencing the issue? Was it just now or at the weekend? I tried purchasing an item from https://www.cobi.ro/ as a test but the payment popup never showed?

**Comment by renatoDragan** [comment]
Because of this issue i close card payment. It works up until 26 November and 1 hour in 28 November. Merchant ID:bd80da5e-a39d-41bb-bd8b-0848c4713e71

**Comment by matthewrgourd** [comment]
Hi @renatoDragan, thanks for that info. Could you also share with me your code so I can check it?

**Comment by renatoDragan** [comment]
<form id="vivaPay" action="https://www.cobi.ro/market/payVivaCard" method="post">
                                <button 
                                    id 							=	"vivaPayCheck"
                                    data-vp-customersurname     =   "<?php echo $user['user_firstname'];?>"
                                    data-vp-customerfirstname   =   "<?php echo $user['user_lastname'];?>"
                                    data-vp-customeremail       =   "<?php echo $user['user_email'];?>"
                                    style 						=	"width:50%;margin-top:25px;"
                                    type						=	"button"
                                    data-vp-publickey			=	"4JL2dvQPSqb06k43hITjE9hW70zA/rnPljapy9KtSb0="
                                    data-vp-baseurl				=	"https://www.vivapayments.com"
                                    data-vp-background-color	=	"#2879fe"
                                    data-vp-lang				=	"ro"
                                    data-vp-merchantref         =   "COBI 2330"
                                    data-vp-amount				=	"<?php echo ($total*100);?>"
                                    data-vp-description         =   "SET DE CONSTRUIT COBI"
                                    data-vp-border-radius		=	"5px"
                                    data-vp-disablewallet		=	"true"
                                    data-vp-sourcecode          =   ""
                                    data-vp-expandcard			=	"true"
                                    data-vp-text 				= 	"PLATESTE">
                                </button>
                            </form>

  public function payVivaCard()
                {

                    // retrieve vivaWalletToken from POST vars
                    $vivaWalletToken = $_POST["vivaWalletToken"];

                    // check if the token is defined
                    if(!isset($vivaWalletToken)){
                        echo ("viva wallet token is not defined");
                        //and catch errors if it is not...
                        return;
                    }
                    // define vars
                    $merchantId = 'bd80da5e-a39d-41bb-bd8b-0848c4713e71';
                    $apiKey = 'mT55x2ke7945WJx6pcR4q684Da3iJZ';

                    $url = 'https://www.vivapayments.com/api/transactions';
                    $postArgs = 'PaymentToken='.urlencode($vivaWalletToken);

                    $curl = curl_init();
                    curl_setopt($curl, CURLOPT_POST, true);
                    curl_setopt($curl, CURLOPT_POSTFIELDS, $postArgs);
                    curl_setopt($curl, CURLOPT_USERPWD, $merchantId . ":" . $apiKey);
                    curl_setopt($curl, CURLOPT_URL, $url);
                    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
                    $result = curl_exec($curl);
                    curl_close($curl);
                    // to debug the call you can uncomment the following lines to check response from the API
                    $result = json_decode($result, true);
                    
                    if($result['EventId'] == 0)
                        {
                            redirect('paySuccess/');
                        }
                    else
                        {
                            redirect('payFailed/'.$result['EventId']);
                        }
                }

**Comment by matthewrgourd** [comment]
Hi @renatoDragan, as far as I can see, there are no issues with your code. The one small thing I noticed is that the payment source you’re using is the “Default” one. In the documentation we advise to create a [new payment source for Simple Checkout](https://developer.vivawallet.com/online-checkouts/create-a-payment-source-simple-checkout/) and add to your custom HTML as follows:
 
`data-vp-sourcecode="[4-digit code of your payment source]"`

I will continue to investigate and get back to you if I discover an answer as to why you're receiving the 500 error. Can I just check with you if it's possible you can enable the checkout briefly while I test it? Any time in the next hour would be fine. For just 15 minutes would be fine.

**Comment by renatoDragan** [comment]
In Romania is a holidays now. I do this on 02 December. Tks.

**Comment by matthewrgourd** [comment]
Hi @renatoDragan, thanks for your email. I've tested with the details given and it seems the public key you're using is invalid. Please can you send me your Viva Wallet Merchant ID so I can check further.

**Comment by renatoDragan** [comment]
merchantId = bd80da5e-a39d-41bb-bd8b-0848c4713e71

**Comment by matthewrgourd** [comment]
Hi @renatoDragan, thanks for that. I can see that your code and Viva Wallet settings are correct. Please note that the 500 error is correct if your card has been declined for whatever reason. Unfortunately the feedback given is not very user-friendly. Looking back over your transactions since you started using Simple Checkout in June, I can see that you have had 77 successful transactions since you started using our integration. Unfortunately you also had 154 card rejections, each of which would have led to the 500 error. The card rejections can be broken down as follows:

- 180 x Visa Insufficient funds (51) (most of those seem to be from your own card ending in 666). This is very unusual behaviour
– 20 x other reasons

I suggest you can switch back to our Simple Checkout but I may need to let our KYC department know.
