### ISSUE TITLE
connection to woocommerce checkout failed

### ISSUE THREAD

**Issue by Easyherbs** [VivaPayments/API#2030]
Hi teams

It seems that I have the same problem as (some) others.
On my website, when customers are paying (numbers then 3Dsecure), the payment doesn't validated anything:
1/ payment is not done as money is not arriving on the viva wallet
2/ on the website, you are coming back to the checkout page with a message on the top "connection to Woocommerce checkout failed. Please check your connectio or try again later"
-> impossible for the customer to know if payment has been done from their bank account (it is not taken from their account, but they didn't know that)
-> I receive the order on the woocommerce / orders page but the status is "waiting for payment"

I have downloaded from the vivawallet site the right extension ans set up it (Viva Wallet for WooCommerce 1.2)

Payment / order are sometimes accepted but it is maybe 1 order for 5 attempts..
I have tried severals times, it seems that when you first try to pay with a card, it is failing with this message. If you cancel your cart, then try again, payment and order is a success...

PLEASE HELPPPPPP !!!   ;)

My website is   https://easyherbs.fr

**Comment by matthewrgourd** [comment]
Hi @Easyherbs, sorry to hear that. Looking at your account, It seems that everything was fine until today. Is that correct? 
So we can investigate further, please can you send me a log file for today's date, Instructions below:

1. Go to **WooCommerce > Status > Logs** tab:

![log1](https://user-images.githubusercontent.com/44943019/99075879-2039d700-25b2-11eb-806d-f45cc6441d68.png)

2. Select relevant date from the dropdown:

![log2](https://user-images.githubusercontent.com/44943019/99075893-262fb800-25b2-11eb-844d-bbf073524f3f.png)

3. Click on the **View** button.

4. Copy the contents into a text file and save it with an appropriate name. 

5. Attach to this issue in .txt format.

Thanks!

**Comment by matthewrgourd** [comment]
Hi @Easyherbs, we think we have isolated the problem. We believe you may have auto-generation of user password switched on in your WooCommerce settings. This is causing a security issue. In your wp-admin, please go to **WooCommerce > Settings > Accounts & Privacy**. Make sure that the **When creating an account, automatically generate an account password** checkbox indicated in the screenshot below is **not selected**:

![Screenshot_2020-12-01_at_11_32_27](https://user-images.githubusercontent.com/44943019/100735692-8f446780-33c9-11eb-98ba-f7cc3338d79a.png)

**Comment by Easyherbs** [comment]
Hi  
  
  
Thank you for your email  
  
  
Just read it and please find attached the file as requested  
  
  
I the same time, again, a customer has tried to pay an order, and same problem ..  
  
:(  
  
Thank you for your help

**Comment by Easyherbs** [comment]
Hi  
  
  
I just answered to your previous email  
  
You're right this option was activated: "Lors de la création d'un compte, générer automatiquement un mot de passe.."  
  
![Capture d’écran 2020-12-01 à 21.20.11.png](cid:3001a38b9b019c5cac420f8a81233412a652a249@infomaniak "Capture d’écran 2020-12-01 à 21.20.11.png")  
  
  
> I just un-selected this option..   
  
I will wait new order to know if it ok now..  
  
  
Great job, thank you  
  
Fabrice
