### ISSUE TITLE
probleme avec viva wallet et shopify "Impossible de créer la commande. Erreur générique"

### ISSUE THREAD

**Issue by cbdriveparis** [VivaPayments/API#2033]
bonjour,

lorsque j 'essaye de générer une commande ( sur shopify)  avec une cb afin de verifier que la passerelle de paiement ( viva wallet) fonctionne je recoit ce message d 'erreur : "Impossible de créer la commande. Erreur générique" .
pourtant j ai suivi le processus d installation a la lettre, j ai bien mis mon ID marchand et j ai egalement bien demander la clef API par mail que j ai egalement mis au moment de la configuration.
bref je suis un peu perdu pourriez vous me filer un coup de main svp.
Cordialement
.

**Comment by matthewrgourd** [comment]
Hi @cbdriveparis, sorry to hear that. So that I can check what the problem is, please send your Merchant ID and the Shopify Token to my email address (mgourd@vivawallet.com) quoting this issue (#2033).

**Comment by cbdriveparis** [comment]
merci beaucoup je vous ai envoyé un mail a l'instant avec toutes les infos

**Comment by matthewrgourd** [comment]
Hi @cbdriveparis, thanks for sending that info through. I'm checking and will get back to you shortly.

**Comment by matthewrgourd** [comment]
Hi @cbdriveparis, the problem should be resolved now. I believe you may have updated your API key in the Viva Wallet banking app which causes problems with the integration.

**Comment by cbdriveparis** [comment]
merci pour votre reactivite je n 'ai plus de message d 'erreur .

cordialement

**Comment by cbdriveparis** [comment]
E
