### ISSUE TITLE
Monica bartolome

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#2034]
Hi @matthewrgourd this merchant has already installed Woocommerce in her website but appears the next:

![MicrosoftTeams-image (37)](https://user-images.githubusercontent.com/56823712/100720451-4d61f400-33be-11eb-8d79-b80cdf3e2db4.png)

Also, ask me For e-commerce web integration we need to know the payment processor you use

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I'm not immediately sure what the issue is. I've worked out website address is monteroleather.com Is that correct? Can you try to get hold of a (full-size) screenshot of the plugin settings which should be similar to the below?

![Screenshot_2020-12-01_at_12_11_57](https://user-images.githubusercontent.com/44943019/100739234-afc2f080-33ce-11eb-9f60-b5e90aa3f92e.png)

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant tells me the next:

That if, currently I have disconnected because in the computer works perfectly the payment environment is well integrated and everything works ok, but in the mobile devices leaves a few lines of error that according to manuel told me is because the account is not yet verified. Although I find it strange that it does that for that reason.

I already have my account verified and I keep getting a plugin error...
![Monica Bartolome](https://user-images.githubusercontent.com/56823712/100775391-81133d00-3403-11eb-99f2-98af24098c68.png)
For your reference, I have removed the apple payment and the error lines are no longer displayed. But now we go with another problem...
![Monica Bartolome 2](https://user-images.githubusercontent.com/56823712/100775488-a43dec80-3403-11eb-91e6-c9b51fe7ee28.png)
 I try to make a purchase and it tells me that there is an error with my credit card. I put my wife's card in and it says the same thing...

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, please ask for the screenshot as I requested in my last reply. I cannot do any troubleshooting on their checkout as they currently have Stripe enabled not Viva Wallet. Alternatively, please ask them to enable ours for 30 minutes today so I can test. As far as I'm aware, the above error message relates to a card issue not anything to do with our plugin, but I need to investigate further before I can give you a definitive answer. Thank you.

**Comment by Alvaroalconada** [comment]
Good morning @matthewrgourd merchant told me the next:

´´I just did a test right now and was able to make a payment with a master card. So in theory it's set up.
But I do want to ask you two things.
One of them is that when the order comes in it changes the status to "completed" instead of "processing" which is normal. I have seen that it gives the option in advanced options but it does not work. I have marked it in processing but it doesn't do it and it marks me as completed and that's a problem´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, that's strange. Can you ask the merchant if they are in live mode when they switch to **Processing** in the Advanced settings? Can you confirm the version of our plugin that the merchant is using? (Plugins > Installed Plugins > Viva Wallet for WooCommerce). This is really important. I just tested on my Wordpress instance with the latest version (v1.2.0) and it's working fine.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant tells me the next:

  I don't have the live one enabled because it gives errors and I can't afford to lose customers these days. But now I'll enable it from 8 to 10, don't you think? I'll put it on the web as "on trial".

can you keep an eye on it?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, sure, I will keep an eye on monteroleather.com between 8 and 10.

**Comment by Alvaroalconada** [comment]
hi @matthewrgourd any news? merchant told me the next:

If I have it configured correctly but it appears as completed in the order, version 1.2.0

**Comment by Alvaroalconada** [comment]
![Uploading montero leather.jpg…]()

**Comment by matthewrgourd** [comment]
@Alvaroalconada they have it set to "Processing" but order is being displayed as "Completed" on live? Are you sure the setting was saved correctly?

**Comment by Alvaroalconada** [comment]
fuck system don´t let me charge the screenshot, I send you by mail

**Comment by matthewrgourd** [comment]
I checked their account and I can't see any test payments for today? Did they perform a test with a real card. Please advise them to do so now. They can make an immediate refund.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I got the screenshot. As long as the merchant clicked on Save after changing the setting to **Processing**, it should work fine. I cannot recreate the issue myself on my own instance or WP with the same version of the plugin. One thing I noticed is that they don't seem to have performed a test with a real card today, only yesterday. Please could you ask them to do that and see if the same behaviour is shown (Order status of "Completed" rather than "Processing").
