### ISSUE TITLE
Grant access to Simple Checkout API

### ISSUE THREAD

**Issue by ckaklamanos** [VivaPayments/API#2037]
Hello.

According to the setup instructions here,

https://developer.vivawallet.com/online-checkouts/simple-checkout/

 I would like you to give us access to Simple Checkout API.

We have set up 3 payment buttons on our website, which do not work at the moment.

Please let me know what information is necessary to give us this access.

Thanks

Haris.

**Comment by matthewrgourd** [comment]
Hi @ckaklamanos, please provide the Merchant ID for the account you wish to enable. Thanks.

**Comment by ckaklamanos** [comment]
Hello and thank you for getting back.

Before posting the Merchant ID here, just to double-check, is it ok to post it here on this public issue post?

**Comment by matthewrgourd** [comment]
Hi @ckaklamanos, I will immediately obscure it once I've captured it. However, if you prefer, you can email me at mgourd@vivawallet.com quoting this issue (#2037)

**Comment by ckaklamanos** [comment]
Thanks.

I just emailed it to you.
