### ISSUE TITLE
Vap Fit Aromas

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#2038]
Hi @matthewrgourd this merchant is trying to set up prestashop 1.5 1.6 but appears him the next error:
![IMG-20201202-WA0005](https://user-images.githubusercontent.com/56823712/100884336-a5c5ee00-34b1-11eb-9769-7030cc716826.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, his settings at the Viva Wallet end look fine. Please can I have a screenshot of his module settings from PrestaShop? Thanks.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, ok, sounds like a PrestaShop error in that case. Unfortunately I won't be able to help with that. The only thing to check now from our end is if he's attempting to install the correct ZIP. See below:

 https://developer.vivawallet.com/downloads/vivawallet1.5_1.6.zip

**Comment by Alvaroalconada** [comment]
Good morning @matthewrgourd merchant just tells me the next:

I was able to uninstall the module and reinstall the one you told me to download. The result is the same, I have taken a screenshot.
![carga_del_modulo_fallida_vivawallet](https://user-images.githubusercontent.com/56823712/100973311-9f2f8900-353a-11eb-931d-17926045dd09.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, can you get the merchant to confirm exactly which version of PrestaShop they're using?

**Comment by Alvaroalconada** [comment]
is 1.6.1.24

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, ok, they've chosen to the correct version of our plugin to upload. Looks like a PrestaShop issue. However, apparently PrestaShop 1.6 is [no longer maintained](https://www.prestashop.com/en/blog/maintenance-extension-prestashop-1-6). In that case, I advise them to [upgrade](https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/) to PrestaShop 1.7 and install our later plugin, ZIP file below.

https://developer.vivawallet.com/downloads/vivawallet1.7.zip

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant tells me that can´t update web to prestashop 1.7 until final of january...

Could you give an another alternative?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada sorry, I can be of no further assistance I'm afraid. The problem is not with our plugin and we can't offer PrestaShop technical support. Sorry!

**Comment by Alvaroalconada** [comment]
@matthewrgourd Could you help me to fill up the module configuration?
![configuración viva wallet](https://user-images.githubusercontent.com/56823712/101021478-411d9880-3570-11eb-9ce3-3bcb58b0a133.jpg)

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant tells me the next:

![MicrosoftTeams-image (39)](https://user-images.githubusercontent.com/56823712/101132320-1c283480-3607-11eb-86b2-e599a38027ba.png)
![MicrosoftTeams-image (40)](https://user-images.githubusercontent.com/56823712/101132405-41b53e00-3607-11eb-95af-d38c0cef8404.png)

- Can you provide me with a tool to make the language in the checkout default to Spanish?--It sounds that you provided me a file. Could be the one that I attach you? 

- The client does not know if the account is properly linked to the website

- You have tried to make a purchase and it gives you an error: when you have made the operation and the system has told you that there is an error it has remained there and has not redirected you to the vap fip home page, is there any way to correct this?

- When you have made the purchase, you have not executed the order but the shopping cart has disappeared, would there be a way to go back and leave the cart intact so that the customer can go back to purchase?

[prestashop1.5-1.6.zip](https://github.com/VivaPayments/API/files/5641049/prestashop1.5-1.6.zip)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, 

- Unfortunately the default language available is English only. However, customers can change the language manually from the payment page.
- The settings are correct at the Viva Wallet end. I would need a screenshot of the PrestaShop settings to confirm 100% the integration. Alternatively, the merchant should enable their Viva Wallet payment plugin on their website so I can test (I notice it's not currently enabled).
- this sounds like the pament source has not been defined correctly in the module settings. "Source code" should be set to 1678 as defined in your Viva Wallet account.
- unfortunately not

**Comment by Alvaroalconada** [comment]
@matthewrgourd what do you mean when you say ´´I would need a screenshot of the PrestaShop settings´´?

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd 

Here I send you the corresponding image that you have requested. Please note that it is not in demo mode, it is directly in the form of payment.
The module is already active and working. Since it does not work well and the trolleys are not recovered, I would be grateful if you could tell me, in case it does not work, to deactivate it after the tests.
If you need to enter physically inside the application or you want to connect remotely with my computer, please tell me.
![configuración viva wallet llena](https://user-images.githubusercontent.com/56823712/101143413-23efd500-3617-11eb-91d6-d548b9df3785.jpg)

**I'm in a hurry because the website has to be ready before 2 p.m.**

**Comment by matthewrgourd** [comment]
@Alvaroalconada, everything looks fine in the screenshot. The merchant should now enable our plugin.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd! merchant tells me the next:

We tried to make two purchases, one on a mobile phone and the other in order from two different cards, and both of them failed. Attached are photos of the error messages.
The mobile was a visa card and the computer was a Sabadell mastercard.
In both cases, the operation has been carried out correctly until the end. When the operation is accepted by the bank, the operation starts to think and the error comes out. This time it has been redirected to the web page, I comment it because the first time yesterday afternoon it didn't do it and before that I asked if it could be programmed
![Uploading 20201204_193503.jpg…]()

**Comment by Alvaroalconada** [comment]
hi @matthewrgourd merchant tells me the next:
We tried to make two purchases, one on a mobile phone and the other in order from two different cards, and both of them failed. Attached are photos of the error messages.
The mobile was a visa card and the computer was a Sabadell mastercard.
In both cases, the operation has been carried out correctly until the end. When the operation is accepted by the bank, the operation starts to think and the error comes out. This time it has been redirected to the web page, I comment it because the first time yesterday afternoon it didn't do it 
![WhatsApp Image 2020-12-04 at 19 16 39](https://user-images.githubusercontent.com/56823712/101217782-35ba9200-3682-11eb-8a1a-5ec0cb29c327.jpeg)
![20201204_193503](https://user-images.githubusercontent.com/56823712/101217794-3bb07300-3682-11eb-8b37-32e9832e6817.jpg)

and before that I asked if it could be programmed

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I can't see any errors relating to our plugin in the screenshots. More than likely the issue was local to the customer (mobile device or card being used). I can also see (in the CRM) that you made a successful purchase yourself that the merchant later cancelled for you. So I think it is fine. Please, if you can, get them to enable our payment gateway. If they're still unsure I can test it on Monday if they enable it for just 30 minutes or so during a timeframe of their choosing. Thanks!

**Comment by Alvaroalconada** [comment]
Hi boss! Everything seems to be going well, let's pray that there are no more unexpected events

Thanks in advance like always, Great weekend :)

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd this merchant is trying to set up prestahop 1.7 for another web chdermacosmetics.com
![MicrosoftTeams-image (42)](https://user-images.githubusercontent.com/56823712/101758357-87c34380-3ad8-11eb-96fc-489c72f8c118.png)
 in the same account Vap Fip Aroma S.L

Could you check it?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, yes, it is working fine.

**Comment by Alvaroalconada** [comment]
@matthewrgourd the merchant ensures me that the payment is made correctly but when he is redirected back to the website he gets this error
![MicrosoftTeams-image (43)](https://user-images.githubusercontent.com/56823712/101765643-e04b0e80-3ae1-11eb-981b-cf537a3ab9db.png)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada works fine for me! Get him to try again. If he gets the same issue, let me know, but I don't think he will.

**Comment by Alvaroalconada** [comment]
@matthewrgourd nothing, keep on giving the same error...

**Comment by matthewrgourd** [comment]
@Alvaroalconada this is after attempting a purchase on https://chdermacosmetics.com? Correct? What is the amount of the transaction so I can check the CRM?

**Comment by Alvaroalconada** [comment]
@matthewrgourd He has tried 4 attemps: 
1ª this morning at 9:19 of 5,44€
2ª, 3ª and 4ª each one of 8,44€ at 12:09, 12:34 and 12: 43 respectively

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I got the same error after making a payment with a real card. However, payment has gone through so please get him to cancel immediately from within his Viva Wallet account, transaction details below:

- 10/12/2020 13:57:36 - Matthew Gourd - Visa - Amount: 8.92

Please can you confirm two things:

1. Which version of PrestaShop is he using for chdermacosmetics.com?
2. Screenshot of Viva Wallet module settings for the above.

Thanks.

**Comment by Alvaroalconada** [comment]
@matthewrgourd I write down the things over your last message:

Hi @Alvaroalconada, I got the same error after making a payment with a real card. However, payment has gone through so please get him to cancel immediately from within his Viva Wallet account, transaction details below: **Relation to this: cancel means refund the money?**

10/12/2020 13:57:36 - Matthew Gourd - Visa - Amount: 8.92
Please can you confirm two things:

Which version of PrestaShop is he using for chdermacosmetics.com? **PrestaShop 1.7.7.0**
Screenshot of Viva Wallet module settings for the above. (I attach)
I believe it is a problem with his success / failure URL, but I need more info. to be sure: **I think that the problem was that he doesn´t write in the URL of success and failure a final PHP, right?**
![chdermacosmetics](https://user-images.githubusercontent.com/56823712/101774771-d8459b80-3aee-11eb-9bf1-4a8fe4466d48.jpg)

Also, he tells me that make the operations because appears the movement in issued bank but doesn´t reflects the purchase because keep on appearing in the cart. On the other hand, is there any possibility to change by defect appears ES instead of Greek?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, yes, "cancel" means "refund". Please get him to cancel the below amount from within his Viva Wallet banking app as soon as possible:

- 10/12/2020 13:57:36 - Matthew Gourd - Visa - Amount: 8.92 

Regarding the version of PrestaShop, if he's using 1.7, the redirect URLs need to be set as follows in payment source 9628 in his Viva Wallet account settings:

- Success: `module/vivawallet/success`
- Failure: `module/vivawallet/fail`

Please get him to amend accordingly and we're good to go.

**Comment by Alvaroalconada** [comment]
@matthewrgourd could you check it if you receive a notice for making setting changes because merchant ensure me that appears a notice that tells him first of all these changes has to been approval by vivapayments service

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, it's ok, I've made the changes myself at this end. Please get him to try again.

**Comment by Alvaroalconada** [comment]
@matthewrgourd merchant tells me that everything keep on same...gives the same error that I attached above and tell me the next:

Payment and order have been made but you are not being redirected

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, the only other possible thing it could be is they're actually using PrestaShop 1.6 rather than 1.7. In which case the below redirect URLs need to be set as follows in payment source 9628 in their Viva Wallet account settings:

- Success URL – `modules/vivawallet/success.php`
- Failure URL – `modules/vivawallet/fail.php`

But to be honest, I'm running out of ideas. If the above still doesn't work, please get me a screenshot of the Viva Wallet payment module settings from his PrestaShop. Thanks.

**Comment by Alvaroalconada** [comment]
Good morning @matthewrgourd sorry but I think that was a mistake myself because I provided this folder of plugin prestahop 1.7 to the merchant for setting up it and I think that a file with the codification of the failure-success url is missing...I attach you. I provided this because I thought that furthemore included all data for a correct instalation of the plugin included checkout by defect in ES instead of english or Greek...shit!

In case that this will be a mistake what solution will give me? he should download again plugin by developers or Could you make some modifications for reaching the correct work?
[prestashop1.7.zip](https://github.com/VivaPayments/API/files/5677986/prestashop1.7.zip)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, sorry, we are going round in circles. The above is of no use to me I'm afraid. You need to provide me with two things, otherwise we can't go any further:

1. Confirm **version** of PrestaShop.
2. Attach screenshot of merchant's payment module settings from his PrestaShop.

Thanks!

**Comment by Alvaroalconada** [comment]
@matthewrgourd  I write down over your sentences that mention above:

Confirm version of PrestaShop.--- PrestaShop 1.7.7.0
Attach screenshot of merchant's current payment module settings from his PrestaShop.
![MicrosoftTeams-image (44)](https://user-images.githubusercontent.com/56823712/101900751-4dc57080-3bb0-11eb-840a-21b0cc1926f3.png)

Thanks!

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I can confirm that all the settings are fine. I just tested their checkout at chdermacosmetics.com (again) and can confirm that everything is working fine. Please advise the merchant of the same.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant has sent me this files. Could you check it and informing about it?
![error 500sobre 7_24h](https://user-images.githubusercontent.com/56823712/102201092-eec06e00-3ec5-11eb-8697-3c0846374cc3.jpg)


[Tue Dec 15 04:01:48.957497 2020] [ssl:warn] [pid 18257] AH01909: RSA certificate configured for chdermacosmetics.com:8143 does NOT include an ID which matches the server name
[Tue Dec 15 04:01:48.957764 2020] [ssl:warn] [pid 18257] AH01909: RSA certificate configured for chdermacosmetics.com:8143 does NOT include an ID which matches the server name
[Tue Dec 15 04:03:18.757487 2020] [ssl:warn] [pid 18257] AH01909: RSA certificate configured for chdermacosmetics.com:8143 does NOT include an ID which matches the server name
[Tue Dec 15 04:03:18.757666 2020] [ssl:warn] [pid 18257] AH01909: RSA certificate configured for chdermacosmetics.com:8143 does NOT include an ID which matches the server name
[Tue Dec 15 07:22:30.407658 2020] [proxy_fcgi:error] [pid 24622] [client 2.136.247.25:59616] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- \n  thrown in /var/www/vhosts/vapfip.com/chdermacosmetics.com/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 177\n', referer: https://chdermacosmetics.com/pedido
[Tue Dec 15 07:24:36.343415 2020] [proxy_fcgi:error] [pid 24622] [client 2.136.247.25:33150] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Unexpected input at line111:  ' in /var/www/vhosts/vapfip.com/chdermacosmetics.com/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatelexer.php:912\nStack trace:\n#0 /var/www/vhosts/vapfip.com/chdermacosmetics.com/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatelexer.php(279): Smarty_Internal_Templatelexer->yylex4()\n#1 /var/www/vhosts/vapfip.com/chdermacosmetics.com/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php(123): Smarty_Internal_Templatelexer->yylex()\n#2 /var/www/vhosts/vapfip.com/chdermacosmetics.com/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(481): Smarty_Internal_SmartyTemplateCompiler->doCompile('{extends file='...', true)\n#3 /var/www/vhosts/vapfip.com/chdermacosmetics.com/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(405): Smarty_Internal_TemplateCompilerBase->compileTemplateSource(Object(Smarty_Interna...\n', referer: https://www.vivapayments.com/

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, the Viva Wallet payment plugin was working fine and all the settings were correct last time I spoke to you about this. I think they have disabled it now so we cannot test currently. However, from the screenshot and the error message you just sent it looks like there is a general problem with the merchant's PrestaShop installation. We **do not** provide PrestaShop technical support, only technical support for the Viva Wallet plugin for PrestaShop. Therefore I believe the only option for the merchant is to contact PrestaShop support: https://www.prestashop.com/en/support Sorry I can't help any further.

**Comment by Alvaroalconada** [comment]
Good morning @matthewrgourd this merchant tells me the next:

I have been in contact with the server to try and see where the problem came from and if they could fix it. 
They have put the prestashop debug mode, so that when the error occurs, a wider explanation of what was happening will come out. They have investigated the solution from within prestashop and what they say below is the result. 
The problem is in the payment gateway from the lines they point out. I pass you the jpg file that has left the debug mode (error 500 debug 11_45h.jpg).
I hope you look at the result and try to get a resolution from this data.

![error 500 debug 11_45h](https://user-images.githubusercontent.com/56823712/102327910-ae74f480-3f86-11eb-8c92-84a8b848f400.jpg)


They have been reviewing the error logs and the error seems to be produced by the gateway you are using, vivapayments.com, returns to the server an obsolete function and gives an error, you will have to contact the module support to see if they have any updates to it

[2020-12-15 15:14:21] php.INFO: User Deprecated: AdminMarketing is a deprecated tab since version 1.7.0 and "Default" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/. {"exception":"[object] (ErrorException(code: 0): User Deprecated: AdminMarketing is a deprecated tab since version 1.7.0 and \"Default\" will be removed in 1.7.1.. Upgrade module using the docs: http://build.prestashop.com/news/how-we-reorganized-main-menu-prestashop-1.7/. at /var/www/vhosts/vapfip.com/chdermacosmetics.com/classes/Tab.php:346)"} []
[2020-12-15 15:14:21] php.DEBUG: Warning: filemtime(): stat failed for /var/www/vhosts/vapfip.com/chdermacosmetics.com/Backoffice/themes/default/css/theme.css {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"/var/www/vhosts/vapfip.com/chdermacosmetics.com/classes/Media.php\",\"line\":269,\"trace\":[{\"file\":\"/var/www/vhosts/vapfip.com/chdermacosmetics.com/classes/Media.php\",\"line\":240,\"function\":\"getMediaPath\",\"class\":\"MediaCore\",\"type\":\"::\"}],\"count\":1})"} []

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, thanks for this very useful info. All I can suggest is you need to make sure that the client has installed our plugin for PrestaShop v1.7, ZIP archive below. If that still doesn't work, then I'll need to speak to a developer and see if they can troubleshoot but unfortunately we're a bit short on resources at the moment so not sure exactly when that will be...

[vivawallet1.7.zip](https://developer.vivawallet.com/downloads/vivawallet1.7.zip)

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant tells me the next:

 After installing the plugin I made a purchase and the attached jpg file came out. I'll pass it on to the server guys. The purchase has been done well and the order has been placed but the final page is this error.
![error al finalizar la compra 16_12_2020___11_45h](https://user-images.githubusercontent.com/56823712/102340210-8db49b00-3f96-11eb-844a-0003a0abc525.jpg)

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, as before, I tested buying something from https://chdermacosmetics.com/ and it works fine. I'm unable to recreate that issue. Please get them to try from a different computer or browser. You should test yourself to see the same as what I'm seeing. You can use the [test card number](https://developer.vivawallet.com/getting-started/#test-card) with any future expiry date and any CVV (which will fail) but this is fine and proves the plugin works:

**Payment form displays correctly:**

![Screenshot 2020-12-16 at 11 16 45](https://user-images.githubusercontent.com/44943019/102341884-65c23900-3f90-11eb-83b4-92c12d0ffec3.png)

**Failure URL works correctly:**

![Screenshot 2020-12-16 at 11 15 28](https://user-images.githubusercontent.com/44943019/102341701-1c71e980-3f90-11eb-93b1-02717a6537e4.png)

You can try with a real card if you like, but they will need to refund you any money. I **100% guarantee** the checkout will work with a real card too.

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd I just did it a test payment and when you make the payment the system provide me the next screenshot:

![fallo CD dermacosmetics](https://user-images.githubusercontent.com/56823712/102347388-a32ec280-3fa0-11eb-8a3f-af8868d42c57.PNG)

Please mate!! contact with plugin´s developer because this is starting a terrible nightmare...

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada did you use a real card?

**Comment by Alvaroalconada** [comment]
@matthewrgourd yes of course my own card!

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, if you got to the payment form, then it means our plugin is working fine. Anything else is a PrestaShop error.
