### ISSUE TITLE
 how to render the string: redirectToACSForm

### ISSUE THREAD

**Issue by ccastiglioni** [VivaPayments/API#2040]
Hello, I'd like some help about implementation.. this is not exactly a problem about the API but a help, because I have no one to turn to :( 
I got this returns:
```
{
    "chargeToken": "ctok_bcGN8H87tGi1qtxtEoYkliYgMrc",
    "redirectToACSForm": "<html><head></head><body>Hey there! Don't
      forget to render me!</body></html>"
}
```
eventId =2061, Browser closed before authentication finished.. I'm using Ajax and I dont know to render the string: redirectToACSForm, wait for your return and then get the chargeToken variable?
pls help

**Comment by matthewrgourd** [comment]
Hi @ccastiglioni, it's a bit difficult to explain. Probably the best thing to do is test on demo with card number [5511070000000020](https://developer.vivawallet.com/getting-started/#test-card) which will simulate the 3DS step and lead to a populated `redirectToACSForm`. Please check example below:

REQUEST
```
POST /nativecheckout/v2/chargetokens HTTP/1.1
Host: demo-api.vivapayments.com
Content-Type: application/json
Authorization: Bearer 4c9c0e303b824deae38938705b9a19888a641b5b3ed14311d27bbcd7619db2f5
Content-Length: 204

{
    "Cvc": "111",
    "Amount": 1000,
    "Number": "5511070000000020",
    "Holdername": "Joe Blogs",
    "ExpirationYear": 2030,
    "ExpirationMonth": 1,
    "SessionRedirectUrl": "www.example.com"
}
```
RESPONSE
```
{
    "chargeToken": "ctok_VKwiS1HCUt_DRE0fcb7u_gijMUA",
    "redirectToACSForm": "<iframe id=\"tdsMmethodTgtFrame\" name=\"tdsMmethodTgtFrame\" style=\"width: 1px; height: 1px; visibility: hidden;\" src=\"javascript:false;\" xmlns=\"http://www.w3.org/1999/xhtml\">\n<!--.-->\n</iframe><form id=\"tdsMmethodForm\" name=\"tdsMmethodForm\" action=\"https://dsx.modirum.com/dstests/ACSEmu2?handshake=1\" method=\"post\"  xmlns=\"http://www.w3.org/1999/xhtml\">\n<input type=\"hidden\" name=\"3DSMethodData\" value=\"eyAidGhyZWVEU1NlcnZlclRyYW5zSUQiIDogIjFjNmVhY2EzLWFmYTYtNWMzMy04MDAwLTAwMmVhNmM5ZjZmNyIsICJ0aHJlZURTTWV0aG9kTm90aWZpY2F0aW9uVVJMIiA6ICJodHRwczovL2RlbW8udml2YXBheW1lbnRzLmNvbS93ZWIvY2hlY2tvdXQvdGhyZWVkc2VjdXJlYXV0aGVudGljYXRpb24vOWUxNjA2MTgtZWRlZi00ZjAzLTk5MjgtYTA0MjYxMTllMGNiIiB9\"/>\n<input type=\"hidden\" name=\"threeDSMethodData\" value=\"eyAidGhyZWVEU1NlcnZlclRyYW5zSUQiIDogIjFjNmVhY2EzLWFmYTYtNWMzMy04MDAwLTAwMmVhNmM5ZjZmNyIsICJ0aHJlZURTTWV0aG9kTm90aWZpY2F0aW9uVVJMIiA6ICJodHRwczovL2RlbW8udml2YXBheW1lbnRzLmNvbS93ZWIvY2hlY2tvdXQvdGhyZWVkc2VjdXJlYXV0aGVudGljYXRpb24vOWUxNjA2MTgtZWRlZi00ZjAzLTk5MjgtYTA0MjYxMTllMGNiIiB9\"/>\n</form><script type=\"text/javascript\" xmlns=\"http://www.w3.org/1999/xhtml\">\ndocument.getElementById(\"tdsMmethodForm\").submit();\n</script>"
}
```
Hope this helps!

**Comment by Sotiris-k** [comment]
Sorry if it is already said in other issues but the 4111 1111 1111 1111 test card isn't suitable for 3DS anymore. I wonder when was this changed and if it was intentional.

**Comment by matthewrgourd** [comment]
Hi @Sotiris-k, yes, that one is no longer recommended for testing, but unfortunately I can't go back over all the GitHub issues and correct it!

**Comment by Sotiris-k** [comment]
That's a pity since it was such a memorable number. Anyway, thanks for the confirmation @matthewrgourd .

**Comment by ccastiglioni** [comment]
ok ,returned a form for a choice (correct|delayed|attempt|wrong/cancel/error/unable/reject).
 But whenever I change SessionRedirectUrl from www.example.com to my application link it returns a
```
array(3) {
  ["status"]=> int(400)
  ["message"]=>string(12) "Null options"
  ["eventId"]=> string(1) "0"
}
```
and when I set with "www.example.com" works but return [404 ](https://dochub.com/clebercastiglioni/7vA0q9lw2jGlAAEwPDNOxd/captura-de-telade2020-12-03-11-30-56-png) when I submit..that way I can't test all behavior

**Comment by ccastiglioni** [comment]
sorry thats my mistake! I forgot to count the Content-Length:

```
   $postfields = json_encode(array(
      "Cvc" =>  $cvc,
      "Amount" => $amount,
      "Number"=>$dsCardNumber,
      "Holdername" =>$holdername, 
      "ExpirationYear" => $expirationyear, //"2023",
      "ExpirationMonth" => $expirationmonth, //"1",
      "SessionRedirectUrl" => $sessionredirecturl 
     ));

   CURLOPT_HTTPHEADER => array(
      "Content-Type: application/json",
      "Authorization: Bearer {$accesstoken}",
      "Content-Length: ". strlen($postfields)),
  ));

```
