### ISSUE TITLE
Problem accepting payments

### ISSUE THREAD

**Issue by Jacks-Eliquid** [VivaPayments/API#2041]
HI
I am having a problem I have followed the guide for installing and configuring the plugin when I have it live I get an error.
I have tried 3 different cards and I know that there is nothing wrong with the cards

I am using your woocomerce plugin Version 1.2.0

Any help / advice appreciated.

![viva Settings](https://user-images.githubusercontent.com/75417993/100985553-0a318d80-3544-11eb-82e2-2089a69cba69.png)
![payment_page_error](https://user-images.githubusercontent.com/75417993/100985597-161d4f80-3544-11eb-82d0-d0526df8cfd7.png)

**Comment by matthewrgourd** [comment]
Hi @Jacks-Eliquid, that usually means a card problem rather than an issue with our plugin. So that I can investigate further, could you re-enable our plugin on your [website](https://jackseliquid.com/) for about 20 minutes or so? Thank you!

**Comment by Jacks-Eliquid** [comment]
Hi yes I will set it live now please let me know when I can turn it off as the site is live.
I have tried 3 different cards if that makes a difference.

I have also tried a one of the cards on a friends site and it works fine.

thanks
Nick

**Comment by Jacks-Eliquid** [comment]
I'm using MasterCard debit cards.

**Comment by matthewrgourd** [comment]
Hi @Jacks-Eliquid, I tested just now and I can see there's a problem but I don't know what it is yet. It could be to do with your theme or other installed plugins. I'm getting my colleague to investigate further. I'll get back to you soon!

**Comment by Jacks-Eliquid** [comment]
HI don't know if this helps but this is what comes up when I look at your orders.

Transaction failed with Viva-CorrelationId: 20-338-2BB53F6A
Transaction failed with Viva-CorrelationId: 20-338-56699297

**Comment by matthewrgourd** [comment]
Ok, @Jacks-Eliquid, yes, that does help. Let me look those up.

**Comment by matthewrgourd** [comment]
hi @Jacks-Eliquid, those correlation IDs show (correctly) that the cards failed. This is correct because we deliberately used a fake card number for the tests. If the correlation IDs are there, it means there is a proper connection being made with our platform. We think it is working correctly and advise you to re-enable it. If you can then monitor it over the next few days and report any further issues, I'd be very grateful. Thank you.

**Comment by Jacks-Eliquid** [comment]
OK I can do that and see what happens, but that won't explain why my cards work on other Viva sites but not on my own.

**Comment by Jacks-Eliquid** [comment]
Just for your info using a real card I get this.

Transaction failed with Viva-CorrelationId: 20-338-947AA38B

**Comment by matthewrgourd** [comment]
Hi @Jacks-Eliquid, sorry to hear that. Let me check that correlation ID. Also, would you mind doing me a favour? Can you send the latest log file from our plugin if possible, instructions below?

1. Go to **WooCommerce > Status > Logs** tab:

![log1](https://user-images.githubusercontent.com/44943019/99075879-2039d700-25b2-11eb-806d-f45cc6441d68.png)

2. Select today's date from the dropdown:

![log2](https://user-images.githubusercontent.com/44943019/99075893-262fb800-25b2-11eb-844d-bbf073524f3f.png)

3. Click on the **View** button.

4. Copy the contents into a text file and save it with an appropriate name. 

5. Attach to this issue in .txt format.

**Comment by Jacks-Eliquid** [comment]
There you go hope this helps.

[jacks error log.txt](https://github.com/VivaPayments/API/files/5635793/jacks.error.log.txt)

**Comment by matthewrgourd** [comment]
Hi @Jacks-Eliquid, there definitely seems to be an issue, but we're not sure why. Still investigating. Will update you when I can.

**Comment by Jacks-Eliquid** [comment]
Ok great thanks. If it helps happy to give you access to the website.

**Comment by Jacks-Eliquid** [comment]
HI
Not sure if you have done anything but it seems to be working now, I have just been talking to a friend who uses it and he told me he had the same problem and was informed that the boarding process from Mastercard takes a minimum of 48hrs. I was using mastercard to pay so just tried it again and it went through.

**Comment by matthewrgourd** [comment]
Hi @Jacks-Eliquid, aha, makes sense. I should have thought of that! Thank you so much for passing on the feedback...please close this issue once you're happy.

**Comment by Jacks-Eliquid** [comment]
Would like to thank you for all the work you have done, I will leave this open if it's ok just for a day or so to make sure there are no issues then I will close it. Thanks again for all you time and help.
