### ISSUE TITLE
Transaction Failed. Prestashop 1.7.7

### ISSUE THREAD

**Issue by Taylorsghs** [VivaPayments/API#2042]
Hello, 
After clicking on "pay" I return to my previous page with the message "Transaction Failed."
I specify that it worked before.

Thank you

**Comment by matthewrgourd** [comment]
Hi @Taylorsghs, sorry to hear that, can I have your store URL, please, and I will investigate.

**Comment by Taylorsghs** [comment]
hi @matthewrgourd , my URL : https://greenhouse-shop.eu/

**Comment by matthewrgourd** [comment]
Hi @Taylorsghs, are you experiencing an issue with the 3DS popup too? I just tried and it seemed to get 'stuck'. When did you install our plugin? A while ago or recently?

**Comment by matthewrgourd** [comment]
Hi @Taylorsghs, please ignore what I said about the 3DS popup. I see that you are in demo mode. Is that what you intended or do you actually want to take payments? If the latter, in your settings, please replace the base URL `https://demo.vivapayments.com` with `https://www.vivapayments.com` Thanks!

**Comment by Taylorsghs** [comment]
@matthewrgourd 
I installed the plugins a short time ago because a prestashop bug. I was on version 1.7.6 prestashop, the vivawallet plugin was functional, and I switched to version 1.7.7 and now it no longer works

I wish to accept payment.
I want to test the webhook

**Comment by matthewrgourd** [comment]
Hi @Taylorsghs, please can you install the below ZIP while following our PrestaShop 1.7 plugin installation instructions and let me know if it makes a difference. Thanks!

https://developer.vivawallet.com/downloads/vivawallet1.7.zip

**Comment by matthewrgourd** [comment]
Closing as no reply
