### ISSUE TITLE
Viva payment and woocommerce not completing

### ISSUE THREAD

**Issue by davidbanfield** [VivaPayments/API#2043]
Firstly, I am not a developer so could all answers be in simple language please. I have been trying to set up viva payments in my woocommerce store for about four days now. This SHOULD have been a simple case of entering API key etc but it has not been a smooth ride. It now works right up to the point of sales notifications both from viva and the website but no money is taken from the payment source and consequently no money is deposited into viva account. To all intents and purposes a sale is complete but no money changes hands.
Could someone explain what is wrong and how to fix it please, I am at my wit's end and support just keep directing me to pages that I followed in the first place. Thank you.

**Comment by matthewrgourd** [comment]
Hi @davidbanfield, sorry to hear you're experiencing difficulties. If you could let me know which Viva Wallet plugin you've installed, and the website address, I can investigate for you. Thanks.

**Comment by davidbanfield** [comment]
Hi Matthew, thanks for the response. The plugin is vivawallet for woocommerce version 1.2.0 but I think that part is now working. Here is the current problem. I am the second user of the viva account and tried logging in but got the password wrong so I was locked out. I decided to simply change the password and used my phone number. This brought me back into our dashboard but no sales stats were showing so I thought the system wasn't working. It turned out it WAS working because the other account user had the viva app on his phone which showed funds had been received. What I would like to know now is how to reset or get me back into the account dashboard. Can you help with that?

**Comment by matthewrgourd** [comment]
Hi @davidbanfield, when you say "account dashboard", do you mean in the Viva Wallet banking app? From the below, which URL are you attempting to access, is it for demo or live?

- Demo: https://demo.vivapayments.com/en-us/signin
- Live: https://members.vivawallet.com/en-gb/signin

**Comment by davidbanfield** [comment]
The Live one. When I sign in with the initial sign up credentials all is well but using my second user credentials I see just an account dashboard with no real information. I am going to also try the live chat but I find they just direct me to pages rather than sort out issues. Thanks again for your response

**Comment by matthewrgourd** [comment]
Hi @davidbanfield, at a guess, it sounds as though the second set of credentials are limited by the parent user accessed via the first set of credentials. Can you log in with the first set of credentials and visit **Settings > Users** to see if you have a 'child' user listed for whom you can change the access privileges?

**Comment by davidbanfield** [comment]
That was my first thought but inside the user area the original user does not show up. It's almost as though my resetting of the password overwrote the original

**Comment by matthewrgourd** [comment]
Hi @davidbanfield, I take it you're using the same phone number to log in, just a different password. Is that correct?

**Comment by davidbanfield** [comment]
No, when I reset the password I also had the sms code sent to my phone number so I confirmed it on my phone. I didn't realise it would create this problem. I can still log in using the original credentials but the original user's actual name and email address is gone from the list and replaced with mine. Does that make sense?

**Comment by matthewrgourd** [comment]
Hi @davidbanfield, I'm not sure I can help you directly with this issue as it seems to be account related. Sorry! Let me check with one of my colleagues and get back to you. Could I have your name and Viva Wallet Merchant ID, please?

**Comment by davidbanfield** [comment]
On here?

**Comment by matthewrgourd** [comment]
@davidbanfield email me at mgourd@vivawallet.com quoting this issue (#2043). Thanks.

**Comment by matthewrgourd** [comment]
Replied by email.
