### ISSUE TITLE
Viva Wallet for WooCommerce - Customer Account Payment Methods

### ISSUE THREAD

**Issue by puffinclouds** [VivaPayments/API#2044]
Customers receive an error message when trying to store a preferred payment method in their accounts.
In WooCommerce their is a "Payment Method" option under "My Account"
When customers take this option they are presented with the Viva Wallet screen for entering their preferred payment card. Having entered their card details and selecting the "Add Payment Method" button they receive the error message "Connection to WooCommerce checkout failed. Please check your connection or try again later."
![viva-wallet-payment-method](https://user-images.githubusercontent.com/34268274/101244602-6260bf00-36ff-11eb-9cc7-b654496a000b.JPG)

**Comment by matthewrgourd** [comment]
Hi @puffinclouds, I'm afraid the ability to store payment methods is unavailable with v1.2 of our plugin. This will be enabled in a future release. Please advise your customers accordingly. Apologies for any inconvenience caused. Thanks.

**Comment by puffinclouds** [comment]
No problem - thanks Matthew for the quick answer :)
