### ISSUE TITLE
Shopify Integration - all failed payments

### ISSUE THREAD

**Issue by Frank8833** [VivaPayments/API#2046]
I have integrated viva wallet with shopify but since this morning I am testing (not in test mode) and all payments fail, that is, after entering the card data and processing the payment, it returns to the shopify checkout page with payment failure error.
I entered the merchant id and the token correctly and set a new website / webapp code, in the Integration method option
between Redirection / Native Checkout v2 and Native payments with Viva Wallet I selected the second one because being the dynamic checkout url I cannot enter failed payment url or the correct payment url, the customer would be disoriented. I raised the issue this morning to support and they told me they are trying to fix it but I have not received more responses and in the meantime customers are unable to make payments. Thanks in advance for the support
![viva wallet](https://user-images.githubusercontent.com/75544789/101262570-2568ec80-3740-11eb-95d4-3532e59ad01f.PNG)

**Comment by matthewrgourd** [comment]
Hi @Frank8833, sorry to hear that. FYI, the Shopify payment source is set up automatically and  you shouldn't change any of its settings. The payment error could relate to a card issue rather than our plugin failing. Please let me have your Shopify store address so I can investigate further. Thanks!

**Comment by Frank8833** [comment]
Hi @matthewrgourd, 

www.marigrace.it

Actually the chat support told me to add the source code as there was only the default one, in fact after, from the email support instead they told me that it is generated automatically and I was confused, so they replied again delete the source code but from the wallett it goes into error and cannot be deleted, I tried to deactivate it but it remains on Active. So I tried again to disconnect Viva Wallett from Shopify and reactivate it, but nothing is wrong. However I have tried with all types of paper, and have had the same feedback from some customers. This morning they replied that the competent department is trying to solve it, however if you can take a look too you would do me a great favor.
Thanks a lot.

**Comment by matthewrgourd** [comment]
Hi @Frank8833, I just tested your checkout with a card with no funds and it appears to be working fine now. Please monitor and let me know if any further issues. FYI, the payment failure error you mention denotes a card rejection from the issuer rather than a problem with our checkout.

**Comment by Frank8833** [comment]
Hi @matthewrgourd,
I also tried again with other cards of all circuits (VISA e MASTERCARD) including Maestro, among which there was also a credit card, and I made some customers try again but everyone is refused the transaction, so it is not a problem of cards used.
I don't know how to solve it anymore, what do you think?

**Comment by matthewrgourd** [comment]
Hi @Frank8833, ok, thanks for letting me now. I'm not immediately sure what the problem is and will need to investigate further.

**Comment by matthewrgourd** [comment]
Hi @Frank8833, it's possible there's an incompatibility with PayPal Express Checkout that you currently have enabled. Can you see if it's possible to [remove / disable](https://community.shopify.com/c/Shopify-Design/Remove-the-Express-Checkout-buttons-from-first-Checkout-Page/td-p/810310)?

**Comment by Frank8833** [comment]
Hi @matthewrgourd,
the change to code is now not possible, because as you read from the documentation it is very impactful and I cannot afford to smash the shopify checkout now. But I did better, I deactivated Paypal as a payment, so the Paypal Express Checkout was no longer there (, I tried to pay with the various cards through Viva Wallett but it always gave me the transaction rejected.
Other ideas ?

**Comment by matthewrgourd** [comment]
Hi @Frank8833, it's a long-shot, but can you send me a screenshot of the current Shopify payment source from your Viva Wallet account?

**Comment by Frank8833** [comment]
Hi @matthewrgourd,
the e-mail support a little while ago told me that they have deactivated the source code created by hand, and actually as per the attached image it is so, but I tried again with various cards but it always denies the transactions, so I tried again to deactivate viva wallet from shopify and reactivate it but nothing the transactions always fail.
![sourcecode](https://user-images.githubusercontent.com/75544789/101358696-81945380-389b-11eb-8351-3cd49990db1e.PNG)

**Comment by matthewrgourd** [comment]
Aha, no worries, looks like the Shopify payment source is hidden (to you). So I think that must be fine as I can see it in your account from our end. Let me investigate a bit further and get back to you. Sorry for the delay.

**Comment by Frank8833** [comment]
Hi @matthewrgourd do you have any news to give me?

**Comment by matthewrgourd** [comment]
Hi @Frank8833, still checking. Sorry for the delay. I will need to speak to a developer and get back to you tomorrow.

**Comment by Frank8833** [comment]
Hi @matthewrgourd ,
I have not received any more feedback regarding the bug and photos of failed payments are arriving from customers, I have seen from my wallet that among the failed payments I am only showing yours, why?
Please these are important days for sales

**Comment by matthewrgourd** [comment]
Hi @Frank8833, I've not forgotten about you. Still investigating. Sorry for the delay...

**Comment by matthewrgourd** [comment]
Hi @Frank8833, I just test with a valid card with no funds and got an error. This is correct as the payment won't go through if the card has no funds. I then tested with my own personal card and payment went through successfully. I can therefore confirm that your Viva Wallet for Shopify plugin is working fine. Please can you refund me the payment just made for 30 Euros under the name Matthew Gourd. Thank you!

**Comment by Frank8833** [comment]
Hi @matthewrgourd ,
great thanks, I'll refund you and I'll do some tests, I'll update you very soon

**Comment by Frank8833** [comment]
Hi @matthewrgourd i,
then I made the refund in your favor, we have carried out some tests with Amex it is ok, we are looking for someone with Visa card to do a test but I have seen from your transaction that it is Visa it is ok but I want to deepen, all the tests with mastercard is of credit and debt (with funds of course) have gone KO. What could be the problem ?

**Comment by matthewrgourd** [comment]
Hi @Frank8833, regarding Mastercard enrolment, unfortunately this is still a manual process that we have to perform. I checked with one of my colleagues and apparently we uploaded your details yesterday so by the end of this day you should be ok for Mastercard e-commerce. Apologies for not checking this before, I initially thought it was a technical issue.

**Comment by Frank8833** [comment]
Hi @matthewrgourd 
thanks a lot don't worry, I hope it will be activated as soon as possible, one last question no less important why I don't see the successful transactions in the available balance of the viva wallet account?
you can leave the issue open until mastecard goes well, thanks.

**Comment by matthewrgourd** [comment]
Hi @Frank8833, regarding your last question, we have next day clearance so available balance should reflect the new transactions tomorrow.

**Comment by Frank8833** [comment]
Hi @matthewrgourd first of all thanks for the precious assistance you were really helpful and efficient. We carried out other tests yesterday in the evening and they were ok and today the orders are coming. You can close the problem. Thanks again and good job.
