### ISSUE TITLE
Access for simple-checkout for a demo account

### ISSUE THREAD

**Issue by Fishlex0** [VivaPayments/API#2047]
According to the documentation _(To use this facility we need to give you access to our Simple Checkout API. Simply raise an issue on our public GitHub to this effect. We will ask you for a bit more information about your company before granting you the necessary privileges.,_ I need to raise a question to access the simple-checkout, so here it is.

Right now I have a demo that returns `The specified api action is disabled for the merchant dd118d48-34b5-4bab-8b9b-0770f3d0c7c5, please consult the documentation`.

What is the next step?

**Comment by matthewrgourd** [comment]
Hi @Fishlex0, that's enabled for you now. Best regards.
