### ISSUE TITLE
PHP website - Mini Card Reader plugin integration

### ISSUE THREAD

**Issue by valentinrot** [VivaPayments/API#2048]
Hello!

We are interested to integrate the Viva Wallet Mini Card Reader into our website (PHP Codeigniter).

The website is used in physical stores, on Android tablets which are part of self-service/unattended info kiosks/touchstands. 

The customers are not allowed to use anything else than our website.

The Mini Card Reader is connected to the tablet via bluetooth.

When a customer sends an order and reaches the checkout, the order amount should be transferred automatically to the POS terminal and the POS terminal should send back the status of the order.

Also, the PIN card should be entered on the tablet, on our website. 

Can you please tell us how we could integrate it?

Thanks

**Comment by matthewrgourd** [comment]
Hi @valentinrot, please see https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/.
You will need to use TCP/IP sockets and communicate with a Paydroid terminal over WiFi or LAN. Hope this helps!

**Comment by valentinrot** [comment]
Hello Matthew, you are sure that we can make this kind of setup using that documentation or it is just an assumption?
 Thanks

**Comment by matthewrgourd** [comment]
My reply above is after conferring with our POS specialist, in which case, yes, I believe so!

**Comment by valentinrot** [comment]
You wrote about WiFi or LAN but the Mini Card Reader from Viva Wallet connects only via bluetooth.

**Comment by valentinrot** [comment]
> My reply above is after conferring with our POS specialist, in which case, yes, I believe so!

Matthew, can you please tell me how I can identify the IP of the POS terminal?

**Comment by matthewrgourd** [comment]
Hi @valentinrot, I'm afraid I'm not an expert in this area. However, the [documentation](https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl/) states that "When the ERP/ECR support gets enabled, the terminal displays on screen the IP address and the listening port. "
