### ISSUE TITLE
Return to home page after a timeout

### ISSUE THREAD

**Issue by ozizo41** [VivaPayments/API#2049]
Hello,

I'm developing an Android application that integrate POS API.

I want after a certain time of inactivity, after calling the transaction, to return to the home page.
I set a timer, using `CountDownTimer` class in `MainActivity`, that starts when the user click on the button to starts the transaction, and returns to the home page (`MainActivity`) after the timeout occurs. But if the transaction starts in the last seconds of the timer, it will return to the home page before the transaction ends, so the user will not get any report of the transaction.

Here is the description of the scenario:

- The user click on a certain amount button and the timer starts, then the application will open VW POS app and ask the user to perform the payment.
- If the user abandons the transaction after a certain time the application will return to the home page (`MainActivity`), but also if the user performs the payment in the last seconds of the timer the application will return to the home page without any report of the transaction.

My `CountDownTimer`:
```
CountDownTimer countDownTimer = new CountDownTimer(Long.parseLong(timeout) * 1000, 1000) {
    @Override
    public void onTick(long l) {

    }

    @Override
    public void onFinish() {
        Intent intent = new Intent(MainActivity.this, MainActivity.class);
        startActivity(intent);      
    }
};
```
What it should be:
```
CountDownTimer countDownTimer = new CountDownTimer(Long.parseLong(timeout) * 1000, 1000) {
    @Override
    public void onTick(long l) {
        boolean isStarted = checkPayment();
        if (isStarted) {
            cancel();
        }
    }

    @Override
    public void onFinish() {
        Intent intent = new Intent(MainActivity.this, MainActivity.class);
        startActivity(intent);      
    }
};
```
So the question is:
Is there any function `checkPayment()` I can write to check if the payment has started so the timer will stop? Or is there any equivalent method to return to the home page only if nothing happens in the VW POS app (the user didn't start the payment) after a certain amount of time?

**Comment by ozizo41** [comment]
Here is the description of the scenario:

- The user click on a certain amount button and the timer starts, then the application will open VW POS app and ask the user to perform the payment.
- If the user abandons the transaction after a certain time the application will return to the home page (MainActivity), but also if the user performs the payment in the last seconds of the timer the application will return to the home page without any report of the transaction.

My CountDownTimer: 
```
CountDownTimer countDownTimer = new CountDownTimer(Long.parseLong(timeout) * 1000, 1000) {
    @Override
    public void onTick(long l) {

    }

    @Override
    public void onFinish() {
        Intent intent = new Intent(MainActivity.this, MainActivity.class);
        startActivity(intent);      
    }
};
```

What it should be:
```
CountDownTimer countDownTimer = new CountDownTimer(Long.parseLong(timeout) * 1000, 1000) {
    @Override
    public void onTick(long l) {
        boolean isStarted = checkPayment();
        if (isStarted) {
            cancel();
        }
    }

    @Override
    public void onFinish() {
        Intent intent = new Intent(MainActivity.this, MainActivity.class);
        startActivity(intent);      
    }
};
```

So the question is: 
Is there any function `checkPayment()`  I can write to check if the payment has started so the timer will stop? Or is there any equivalent method to return to the home page only if nothing happens in the VW POS app (the user didn't start the payment) after a certain amount of time?

**Comment by matthewrgourd** [comment]
Hi @ozizo41, assuming you're integrating using intents (Android app to app communication), no, there is no status call. Hope this helps.
