### ISSUE TITLE
access to Simple Checkout API

### ISSUE THREAD

**Issue by tsartsaris** [VivaPayments/API#2050]
Acces to Simple Checkout API needed.

**Comment by matthewrgourd** [comment]
Hi @tsartsaris, sure, if I could have your Viva Wallet Merchant ID, please? If this is for your live account, please email me at mgourd@vivawallet.com quoting this issue (#2050). Thanks.

**Comment by tsartsaris** [comment]
@matthewrgourd 

b3e3203b-117a-4514-b2d2-7a0467b72eb6
--


Thank you.

**Comment by matthewrgourd** [comment]
Hi @tsartsaris, enabled as requested. Thanks.

**Comment by tsartsaris** [comment]
@matthewrgourd thank you, Matthew. It's working.
