### ISSUE TITLE
Calling Transaction Details API Error

### ISSUE THREAD

**Issue by HarishankarIT** [VivaPayments/API#2052]
Hi,

One of our live customers paid us using viva wallet - Simple checkout.
Payment is done successfully and the record is there in the merchant account.
But the next moment we are calling transaction API call for transaction details. that time we have faced an error called HTTP Error 503. The service is unavailable.

Please kindly let us know the reason.

Customer Details:
Transaction Id: f54a36ea-e94b-45d8-b145-fe96c4189d32 
Order Code: 3047856591895758
Date: 20/11/2020 

Trade name: EFILE READY LIMITED
Registration date : 19/02/2020
live Merchant id: b85b1ede-d9a6-4cfe-a992-3ae583cab24f

Thanks & Regards,
HariIT

**Comment by matthewrgourd** [comment]
Hi @HarishankarIT, I just tried myself using your credentials and got a 200 ok + expected response body. Maybe it was a very short period of unavailability of our API?
