### ISSUE TITLE
Transaction Failed.

### ISSUE THREAD

**Issue by tmsio** [VivaPayments/API#2053]
Hello, i follow this guide for prestashop:
https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/

Code – ****
Source Name – Raskal Shop
Linked Wallet – Primary
Protocol – https
Domain Name – raskal.shop
Integration method – Redirection/Navite Checkout V2
Company Logo - My logo
Success URL – module/vivawallet/success
Failure URL – module/vivawallet/fail
Checkboxes – all checked

When i try to pay an order, after  insert my card and clicche oreder, i  get redirect to my store (Transaction Failed.)

Can You Help Me

Regards

My Site:
https://raskal.shop

**Comment by matthewrgourd** [comment]
Hi @tmsio, sorry to hear that. For some reason, the success / failure urls were set to something different. I've changed them now. Please re-enable the plugin and try again. Thanks.

**Comment by tmsio** [comment]
Hello, same errore : Transaction Failed
I attached my
conf

Regards

Emiliano

Il 10.12.2020 15:54 matthewrgourd ha scritto:


> Hi @tmsio [1], sorry to hear that. For some reason, the success /
failure urls were set to something different. I've changed them now.
Please re-enable the plugin and try again. Thanks. 
> 
> --
> You are
receiving this because you were mentioned.
> Reply to this email
directly, view it on GitHub [2], or unsubscribe [3].
 



Con Tiscali Mobile Smart 30 4G hai minuti illimitati, 100 SMS e 30 Giga in 4G a soli 8,99€ al mese. http://tisca.li/smart30

**Comment by matthewrgourd** [comment]
Hi @tmsio, sorry to hear, please send me a screenshot of your current PrestaShop settings for the Viva Wallet payment module, blurring out any private information.

**Comment by tmsio** [comment]
Hello, atteched.

Regards

Emiliano

Il 10.12.2020 17:08
matthewrgourd ha scritto: 

> Hi @tmsio [1], sorry to hear, please send
me a screenshot of your current PrestaShop settings for the Viva Wallet
payment module, blurring out any private information. 
> 
> --
> You are
receiving this because you were mentioned.
> Reply to this email
directly, view it on GitHub [2], or unsubscribe [3].
 



Con Tiscali Mobile Smart 30 4G hai minuti illimitati, 100 SMS e 30 Giga in 4G a soli 8,99€ al mese. http://tisca.li/smart30

**Comment by matthewrgourd** [comment]
Hi @tmsio, unfortunately I can't see the screenshot. Can you try attaching again?

**Comment by matthewrgourd** [comment]
I can see it now. Thanks! To test on demo you need to change the base URL to `https://demo.vivapayments.com`, and use the Merchant ID, API key and source code values from your Viva Wallet [demo account](https://demo.vivapayments.com/).

**Comment by tmsio** [comment]
Do you need test on demo account?
Regrads.


Il 11.12.2020 16:43 matthewrgourd ha scritto:

**Comment by matthewrgourd** [comment]
Hi @tmsio, sorry, I thought you wanted to try on demo first. Not necessary as I can test directly on live? Are you happy to enable now? I can test during the next 30 minutes or so...

**Comment by tmsio** [comment]
Hello, the problem appear fixed now.
I have not make any change.
I have to text better.
Thank You.
Regards
Emiliano
