### ISSUE TITLE
Payment taken but no order created

### ISSUE THREAD

**Issue by oofta-web** [VivaPayments/API#2056]
Hello. Having integrated Viva Wallet on my client's website we noticed that approximately 1 in every 30 orders or so was experiencing this issue; the payment is taken successfully and deposited into my client's account but no order is created on his website. He asked me to investigate and I found the following problem using a demo account: it appears that if a customer attempts a payment which fails for whatever reason, they are returned to the payment option page on my client's website to either select a different payment option or try again - as you would expect. When they return to the Viva Wallet payment page to try to pay again, they are returned to my client's session timed out page where they have been logged out of their account completely, whether the second attempt is a success or failure. However, the really worrying part is that if the second attempt is a success, the customer's payment is taken but no order is created. I am happy to supply screenshots or better still, provide access to my test website where you can see this for yourself. I am using the Zen Cart plugin.

**Comment by oofta-web** [comment]
Here are screenshots showing the process:
<img width="1253" alt="Screen Shot 1st attempt" src="https://user-images.githubusercontent.com/75837234/101910452-d8a96980-3bb6-11eb-801f-f7544e672002.png">
1st attempt - set to reject (this can be any other setting to simulate a failure).

<img width="1247" alt="Screen Shot 1st attempt fails" src="https://user-images.githubusercontent.com/75837234/101910448-d6dfa600-3bb6-11eb-814c-fb4fc39e6082.png">
1st attempt fails - sends us back to the payment page on our website.

<img width="1253" alt="Screen Shot 2nd attempt" src="https://user-images.githubusercontent.com/75837234/101910446-d6470f80-3bb6-11eb-8ae3-940def99cfaa.png">
2nd attempt - set to success.

<img width="1252" alt="Screen Shot 2nd attempt succes" src="https://user-images.githubusercontent.com/75837234/101910440-d3e4b580-3bb6-11eb-9caf-720faebbd93d.png">2nd attempt success - we are booted out of our account on our website and end up on the timed out page.

<img width="942" alt="Screen Shot 2020-12-11 at 13 41 35" src="https://user-images.githubusercontent.com/75837234/101910429-d0e9c500-3bb6-11eb-9ca3-3f08aaa763a4.png">
No order is created but we can see in our account that the payment has been taken.

**Comment by matthewrgourd** [comment]
Hi @oofta-web, sorry to hear that this is not working for you as expected. It's been a while since I tested on an OpenCart website. I'll need to look into this and get back to you. Thanks.

**Comment by oofta-web** [comment]
Hi @matthewrgourd, thanks, I look forward to hearing from you.

**Comment by matthewrgourd** [comment]
Hi @oofta-web, do you have a web address for me to test the implementation?

**Comment by oofta-web** [comment]
www.fastfoodtakeaway.website

Just create an account using the postcode AA1 1AA (should already be pre-filled in the Create Account form).

Viva Wallet is installed and linked to my demo account.

Let me know if you need more.

**Comment by matthewrgourd** [comment]
Hi @oofta-web, I've tested on demo and it's working fine. Can you enable on live for the next 30 minutes or so (or whenever convenient) as I need to test there as well. Obviously you will need to change your Open Cart settings to point to the live base URL (https://www.vivapayments.com) and using your Merchant ID and API key from production. Thanks.

**Comment by oofta-web** [comment]
Hi @matthewrgourd, did you only make one order?

**Comment by oofta-web** [comment]
I'm sorry, but the testing environment is really flaky. I have just tried myself and for some reason I cannot enter the outcome I want to simulate because the pop-up window containing the Authenticate button is bypassed. Why is that? I can assure you that it is not working fine.

**Comment by matthewrgourd** [comment]
Hi @oofta-web, the testing environment is not as good as it could be, I agree. However, I was able to view the 3DS simulator earlier, and choose a positive and a negative outcome in two different scenarios. My advice would be to now test on live for the complete picture. As I say, I can do this for you and confirm within 30 minutes as long as you can enable our plugin during this time.

**Comment by oofta-web** [comment]
Can you please try again and simulate "reject" (or any other simulation that takes you back to the payment page), then try again and simulate "correct", then see what happens.

**Comment by oofta-web** [comment]
Note - you must try to complete the transaction on the same order. What we are finding is that when a customer tries to pay with a card that is rejected, and then goes to pay for the same order again with another card that is accepted, he is returned to our timed-out page and logged out of his account, no order is created, but his payment is taken. This exact same thing happens in the simulator (when it is working that is).

**Comment by oofta-web** [comment]
Hi @matthewrgourd, the simulator has now just worked for me and I tested the above scenario - payment taken but no order created and booted out of my account. Please check it yourself.

**Comment by matthewrgourd** [comment]
@oofta-web, the negative scenario is the one that seems to be unreliable on demo. We will need to test on live to get an accurate outcome.

**Comment by oofta-web** [comment]
Hi @matthewrgourd, as I say, my customer's website where this is happening is a live environment! That is why I have created a test environment of my own to make tests. To be able to test live, you first need a live card which will be rejected - I do not have one! I can assure you that what happens in my test environment is happening on my customer's live site, and, to be honest, he is getting pretty miffed with it!

**Comment by oofta-web** [comment]
Hi @matthewrgourd, so how would you test this in a live environment. Do you have a card that would be rejected?

**Comment by matthewrgourd** [comment]
@oofta-web, your demo website would need to point to a live Viva Wallet account (you will need to change your Open Cart settings to point to the live base URL (https://www.vivapayments.com) and using the Merchant ID and API key from production for authentication.) I simply test with a real card without any funds.

**Comment by oofta-web** [comment]
OK - I'll set that up now, but please, when you are rejected back to my website payment page, please try again immediately with a good card and see what happens. I'll comment back when the Wallet is live and set up.

**Comment by oofta-web** [comment]
Hi @matthewrgourd, the live Wallet is now installed and working. Please let me know your findings.

**Comment by matthewrgourd** [comment]
Hi @oofta-web, I tested with a card with no funds twice:

1ST ATTEMPT RESULT (there has been an error)
![there-has-been-an-error](https://user-images.githubusercontent.com/44943019/102079986-945fd880-3e05-11eb-8afc-a32f4b0c80be.png)

2ND ATTEMPT RESULT (timeout and session closed)
![time-out](https://user-images.githubusercontent.com/44943019/102080006-9cb81380-3e05-11eb-983f-2234ee5db6ee.png)

I don't know if this helps at all.

**Comment by oofta-web** [comment]
I already knew this. This is what I have been saying all the time! I thought this was the place to come to get these issues sorted out? This is the place where Viva Wallet directed me when I reported this issue. Is that not correct? I'm not sure you have understood what I have been saying? If the second attempt is made with a good card we get the same result but payment is taken and no order created. Why is that? Do you actually work for Viva Wallet? I was under the impression that you would help to get this fixed, or have I got that wrong? There looks like there is a fault somewhere when Viva Wallet processes a second payment attempt within the same session and I was under the impression that this is where I should come to to talk to the VivaPayments technical team about it.

**Comment by matthewrgourd** [comment]
Hi @oofta-web, sorry, I do work for Viva Wallet, and am trying to help you as best I can. So I can investigate further, please could you let me know the below:

- version of Open Cart you're using
- Viva Wallet account info (demo and live). This could be the company registration or VAT number.
- screenshot of OpenCart settings page with Viva Wallet configuration info.

Thank you.

**Comment by oofta-web** [comment]
Hi @mathewgourd,

Thanks for the email and sorry for the misunderstanding.

I am using Zen Cart version 1.3.9 but heavily updated.

Viva Wallet Accounts:

Live =
Business Account
EAST LANCASHIRE FOODS LIMITED
Verified
Registration date
20/10/2020
Trade name
Godfather pizza house
Address
Whalley New Road 455, BB1 9SP
Telephone
VAT Number
Registration Number
11315711



Test =
(I’m afraid there is little or no information in my test account)



Hope this helps, let me know if you need anything else.

Kind regards,
Malcolm Shannon

@oofta-web

**Comment by matthewrgourd** [comment]
Hi @oofta-web, no problem. Thanks for providing that info. I've checked the settings at this end and there is one problem related to the payment source. The domain name value has been entered as "fastfoodtakeaway.website" instead of "www.fastfoodtakeaway.website". I've updated that now. I just did another test and this time got a different result, but not the expected one. My card with no funds has resulted in the order success page being displayed instead of an error message. However, of course, no payment has been taken as the card has no funds. What I really need from you now is a screenshot of the settings you're currently using within OpenCart for the Viva Wallet payment plugin. Would you be able to provide that? Thanks...

**Comment by oofta-web** [comment]
Hi @matthewrgourd, trying to juggle a few jobs at once here so apologies if there are any delays. I can confirm that an order for £12.78 has been created. Please see screenshot for the Cart plugin settings for the test account. 

<img width="1273" alt="Screen Shot 2020-12-14 at 13 56 31" src="https://user-images.githubusercontent.com/75837234/102099772-908d7f80-3e20-11eb-9199-2e800058cd33.png">

**Comment by matthewrgourd** [comment]
Hi @oofta-web, ok, thanks. Your settings look fine. Not sure what else to suggest except it's possible our plugin is not compatible with the specific theme or plugins you're using. Is there any way of changing the theme and disabling the plugins temporarily and testing our payment plugin again after that?

**Comment by oofta-web** [comment]
Hi @matthewrgourd, I have found the issue. Zen Cart has a built in Credit Card slam prevention where a php session stores card payment attempts. If the number of payment attempts is over a set number, the customer is booted out and his session is destroyed along with his shopping cart. I have found that, for some mysterious reason, a failed payment attempt using VivaWallet is recorded as 2 attempts (no idea why). Zen Cart has its default value set to 3. Therefore, if a customer fails with his first card and tries again, the number of attempts is 4 no matter what the second outcome is, resulting in an automatic boot out.
The solution is to up the Zen Cart credit card slam value - I changed this to 4 and now the second attempt creates the order as expected. Simple as that.
Surely there have been other Zen Cart users who have experienced the same issue? In any case, this does pose the question as to why Viva Wallet counts a single payment attempt as 2 attempts?

**Comment by oofta-web** [comment]
Hi @matthewrgourd, furher update - apparently 2 attempts is correct when using 3d secure. Therefore the fix is simply to up the slam attempt number within the Zen Cart checkout_process.php file. I have set mine to 6 which will allow 3 attempts which I will monitor. 
Many thanks for your help with this.
