### ISSUE TITLE
Language of the payment page in Greek redirect checkout

### ISSUE THREAD

**Issue by NicoBBS** [VivaPayments/API#2057]
hello, I am using the official module for a prestashop 1.7 site.
Everything works correctly but my client does not want to keep your solution because when we select payment by credit card and we are redirected to your page: "https://www.vivapayments.com/web/newtransaction.aspx? Ref = xxxxxxx "the default language is Greek. Our clients are French and they leave the page.

Would you have a solution for me please?

I thank you in advance,
Nico
![vivagr](https://user-images.githubusercontent.com/75841627/101903862-39d03d80-3bb5-11eb-9ae8-5d7677e38281.png)

**Comment by NicoBBS** [comment]
[vivawallet1.7.zip](https://github.com/VivaPayments/API/files/5679112/vivawallet1.7.zip)

**Comment by matthewrgourd** [comment]
Hi @NicoBBS, a number of merchants have raised the same issue and we're currently looking at a fix. I'll update you when I have a spare moment.

**Comment by NicoBBS** [comment]
Hello,
very good thank you ! I await your news.

**Comment by matthewrgourd** [comment]
Hi @NicoBBS, I've been told this has been fixed. Apparently it was an issue on our production server. Thanks.

**Comment by NicoBBS** [comment]
It's perfect, I can confirm that it works. Thank-you for your prompt response !
I close the ticket.

Have a nice day!
