### ISSUE TITLE
Native Checkout v2 JS error message

### ISSUE THREAD

**Issue by pedrolopes10** [VivaPayments/API#2058]
Hi there, first of all thanks for this package.

When error handling the requests made by your JS it's not possible to get real error message.

VivaPayments.cards.requestToken({
  amount: 100, 
  installments: 1,
}).done(function (responseData) {
  console.log(`Here is the charge token: ${responseData.chargeToken}`);
}).fail(function (responseData) {
  console.log('Here is the reason it failed: '  + responseData.Error.toString());
});

Inserting a bad expire date the fail function will return "VivaPayments: Bad Request" instead of response body: 
{eventId: "6002"
message: "CardsParseExpiryFailedInvalidExpirationMonth"
status: 400}

Thanks

**Comment by matthewrgourd** [comment]
Hi @pedrolopes10, this is something I need to check with our dev team. I'll get back to you when I have a reply.

**Comment by matthewrgourd** [comment]
Hi @pedrolopes10, our development team is working on some improvements but I'm not sure of the timeline yet.

**Comment by matthewrgourd** [comment]
HI @pedrolopes10, an update from our development team: the changes will be released next week.

**Comment by matthewrgourd** [comment]
Hi @pedrolopes10, some improvements have now been released so you should find better error handling.

**Comment by pedrolopes10** [comment]
Hi @matthewrgourd ! Many thanks, I will test it this weekend. Thanks again
