### ISSUE TITLE
native checkout v2 / 3DS

### ISSUE THREAD

**Issue by PyB1l** [VivaPayments/API#2059]
Hi, I would like to ask the restrictions for the client phone in /nativecheckout/v2/transactions/ . We had some incidents in production where 3DS verification failed due to phone values.

**Comment by matthewrgourd** [comment]
Hi @PyB1l, sorry, I'm not sure I understand exactly the nature of the query. Can you clarify?

**Comment by PyB1l** [comment]
We have a registration form in our app and where we collect user info and if the registration is for for paid subscription, we use native checkout v2. In this process we provide customers phone in /nativecheckout/v2/transactions/  and sometimes it fails to complete due to phone validation issues.

Since phone is mandatory in VivaPayments 3DSv2 but optional in our registration process, is it safe to provide a "fake" phone in
 /nativecheckout/v2/transactions/ ? If yes, will it have 3DS implications?

**Comment by matthewrgourd** [comment]
Hi @PyB1l, in answer to your query about phone number capture, yes it is fine to use that work-around. Thanks.

**Comment by PyB1l** [comment]
And it won't have any implication on 3DS verification of any kind? I am asking mostly for banks that use sms verification code, and in that case if a different (fake) phone in VivaPayments  /nativecheckout/v2/transactions/  could cancel  the transaction.

If I understand your reply correctly, phone capture is VivaPayment specification and has no impact of any kind in 3DS v2, correct?

**Comment by matthewrgourd** [comment]
Hi @PyB1l 3DS authentication is handled by the card issuer with a phone number that will have already been set up by the customer with their bank. I believe the only info. they need to be captured on the form is billing name, billing address, card number, expiry date and CVV.

**Comment by PyB1l** [comment]
Thanks again, other than a working solution I was warring for implementing some kind of anti-pattern.
I shall close this issue.
