### ISSUE TITLE
Offline πληρωμές

### ISSUE THREAD

**Issue by spiritinlife** [VivaPayments/API#206]
Καλησπέρα

Θα ήθελα να μάθω πώς μπορώ να διαχειριστώ τις offline πληρωμές.
**Περίπτωση 1**
Ο χρήστης μέσα απο το site πατάει να πληρώσει και τον κάνω redirect στη viva απόδειξη αφού πρώτα εχω καλέσει το createOrder και έχω πάρει πίσω ενα transaction. Σε αυτο το transaction εχω βάλει expiration time σε 3 μέρες, οπότε στον πελάτη εμφανίζονται οι επιλογές πληρωμής σε φυσικό κατάστημα
Ερωτήσεις
1. Υπάρχουν κάπου στο διαχειριστικό της viva τα transactions ετσι ώστε να μπορώ να βλέπω ποια δεν εχουν ολοκληρωθεί?
2. Μπορεί ο πελάτης να κάνει κατάθεση στην τράπεζα και να πάω εγω μεσα απο κάποιο διαχειριστικό και να κλείσω το transaction , ετσι ώστε να μου έρθει ειδοποίηση μέσου webhooks για την επιτυχής συναλλαγή? 

**Περίπτωση 2**
Ο χρήστης μπορεί να κάνει κατάθεση στην τράπεζα χωρίς να ξεκινήσει την διαδικασία απο το site μας.
Τότε ποιες είναι οι επιλογές μου? 
Πώς μπορώ να δημιουργήσω ισως transaction απο το διαχειριστικό της viva και να το κλείσω, ετσι ώστε να μου έρθει ειδοποίηση μέσου webhooks για την επιτυχής συναλλαγή?

**Comment by dmihos** [comment]
Καλημέρα 
Για την 1η περίπτωση, webhook θα λάβετε, σε κάθε περίπτωση, για τις καταθέσεις μέσω τράπεζας, όταν αυτές επεξεργαστούν (συνήθως την επόμενη μέρα).
Αυτό, νομίζω σας καλύπτει (προφανώς, για όσα OrderCodes δε λάβετε webhook, σημαίνει ότι δεν πληρώθηκαν ακόμα)

Για τη 2η περίπτωση, θέλετε να μας εξηγήσετε το σενάριο; Που θα βρει ο πελάτης τον κωδικό πληρωμής, αν δεν ξεκινήσει τη διαδικασία από το site σας;

**Comment by spiritinlife** [comment]
Καλημέρα,
Για την περίπτωση 1 υπάρχουν κάπου οδηγίες για κατάθεση σε τράπεζα με το orderCode και ποια ειναι η διαδικασία που πρέπει να ακολουθήσει ο πελάτης? 
Για την περίπτωση 2 σκεφτόμουν χωρίς κωδικό πληρωμής αλλά μάλλον είναι αδύνατο γιατι δεν θα υπάρχει τρόπος να αναγνωριστεί η πληρωμή απο το σύστημα.

Ευχαριστώ

**Comment by dmihos** [comment]
Στη σελίδα checkout, αναφέρονται σχετικές οδηγίες, όταν ο χρήστης επιλέξει "Τράπεζα"

**Comment by spiritinlife** [comment]
Ευχαριστώ.
