### ISSUE TITLE
Nouesmalt

### ISSUE THREAD

**Issue by Alvaroalconada** [VivaPayments/API#2060]
Hi @matthewrgourd I have this merchant that wants to implement our payment gateway in his website and I receive the next notice. Could you check it?

´´Hello, we want to use your platform to receive payments from our
clients.
To do this we are following the steps described in the developer portal.
The first step is to perform the oauth identification:

https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.vivawallet.com%2Fweb-api-integration%2Fauthentication%2F&data=04%7C01%7Ccustomercare%40vivawallet.com%7Cda746917894c4e44655508d89d360083%7C67605cd729054d798256ae1f5420c277%7C0%7C1%7C637432203337303588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=l5IOScDE6eV4wnXrikoEFTL6MclRCs%2BCMLnc4J01oNg%3D&reserved=0

Well, we are getting NULL as a response to this first call.

We believe that we are doing everything well, because in the
documentation it is quite well explained and we have followed the steps.

I give you the source code in PHP that we have used so that you can
analyze the error we make

$url_vivawallet="https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdemo.vivapayments.com%2F&data=04%7C01%7Ccustomercare%40vivawallet.com%7Cda746917894c4e44655508d89d360083%7C67605cd729054d798256ae1f5420c277%7C0%7C1%7C637432203337303588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=t44rdVBC8ueGztmE2Ks%2BK9wDwckp%2FHYRenO77JcwBQA%3D&reserved=0";
$merchant_id_vivawallet="vwyuun2l21myi9to3huiwn2cij7jqg5hr3rss3318qis6.apps.vivapayments.com";
$api_vivawallet="Au3av3BLb5bk0Sih2jyg9OuPZY4qGH";
$login=base64_encode($merchant_id_vivawallet.":".$api_vivawallet);
$header=[
"Authorization: Basic ".$login,
"Accept: application/json",
"Content-Type: application/x-www-form-urlencoded"
];
$endpoint="/connect/token";
$theurl=$url_vivawallet.$endpoint;
$postdata=["grant_type"=>"client_credentials"];

$ch = curl_init($url);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($postdata));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$result = curl_exec($ch);

echo $result;

Result is empty or NULL.

Could you tell us what we are doing wrong?´´

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, please firstly ask them which of our checkouts they're attempting to implement. Is it Simple Checkout, Redirect Checkout or Native Checkout v2? I can then respond to the rest of the query.

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada , do you have any further info. on which checkout the client is attempting to implement?

**Comment by Alvaroalconada** [comment]
@matthewrgourd Still not, I´m waiting an answer about it...

**Comment by Alvaroalconada** [comment]
@matthewrgourd native checkout v2 is the answer

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, great, thanks! So I can't troubleshoot their code, but I can reiterate the steps that need to be taken for correct Native Checkout v2 implementation.

1. [Generate OAuth 2 token](https://developer.vivawallet.com/web-api-integration/authentication/#oauth-2-token-generation).
2. [Create a payment source](https://developer.vivawallet.com/online-checkouts/create-a-payment-source-native-checkout-v2) selecting Redirection/Native Checkout v2  as the integration method.
3. [Follow setup instructions](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#setup-instructions) as outlined in our developer portal.

Hope this helps!

**Comment by Alvaroalconada** [comment]
Hi @matthewrgourd merchant tells me the next: ( Is an own development)

we are trying to implement the Native checkout v2.
In demo mode, using the card numbering you provide, everything works ok.
In real mode, by pressing the pay button on the form, using the chrome developer console, we can see that it launches the following
error:
Uncaught ReferenceError: VivaPayments is not defined and does nothing else.

We understand that to go from demo mode to real mode, you would only have to change these 3 urls:

(To obtain the OAuth token)
Demo:
https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdemo-accounts.vivapayments.com%2Fconnect%2Ftoken&amp;data=04%7C01%7Caalconada%40vivawallet com%7C81b595eb20d448912a8d08d8a1bb282a%7C67605cd729054d798256ae1f5420c277%7C0%7C0%7C637437173213875681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp; sdata=JVu29k9ukT3k%2Ff3Bf8rLgWaDtIcUxB4Xowb4bpR7x9U%3D&amp;reserved=0
Real:
https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Faccounts.vivapayments.com%2Fconnect%2Ftoken&amp;data=04%7C01%7Caalconada%40vivawallet. com%7C81b595eb20d448912a8d08d8a1bb282a%7C67605cd729054d798256ae1f5420c277%7C0%7C0%7C637437173213875681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp; sdata=LJOE6Y4qimMmHSYWGUAKwIeppv5gI2d5sj7WPnC%2B5ZM%3D&amp;reserved=0
(So far so good, we get the token well in both cases)

Demo:
<script type="text/javascript" 
src="https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdemo.vivapayments.com%2Fweb%2Fcheckout%2Fv2%2Fjs&amp;data=04%7C01%7Caalconada%40vivawallet. com%7C81b595eb20d448912a8d08d8a1bb282a%7C67605cd729054d798256ae1f5420c277%7C0%7C0%7C637437173213875681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp; sdata=zg4qjnoaHtGgRaJge3P7q0DA2urGoLU5JRs2dFfvl6o%3D&amp;reserved=0"></script>
Real:
<script type="text/javascript" 
src="https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvivapayments.com%2Fweb%2Fcheckout%2Fv2%2Fjs&amp;data=04%7C01%7Caalconada%40vivawallet. com%7C81b595eb20d448912a8d08d8a1bb282a%7C67605cd729054d798256ae1f5420c277%7C0%7C0%7C637437173213875681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp; sdata=3T8GUnyvqHoTnukAW6ovoyXMSjsibEPVp3VqI9bFvhs%3D&amp;reserved=0"></script>

Demo:
const baseUrl = 'https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdemo-api.vivapayments.com%2F&amp;data=04%7C01%7Caalconada%40vivawallet com%7C81b595eb20d448912a8d08d8a1bb282a%7C67605cd729054d798256ae1f5420c277%7C0%7C0%7C637437173213875681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp; sdata=MSv%2FlruLISbkhlbpuf9378%2B8UP1cW1VJ7LKCDd3m7ms%3D&amp;reserved=0';
Real:
const baseUrl = 'https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.vivapayments.com%2F&amp;data=04%7C01%7Caalconada%40vivawallet. com%7C81b595eb20d448912a8d08d8a1bb282a%7C67605cd729054d798256ae1f5420c277%7C0%7C0%7C637437173213875681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp; sdata=6M03Q%2FFYnXgwrbRkCdQikTvjP5ejDjtQTjNErxIXII%3D&amp;reserved=0';

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I'm sorry, I can't comment any further except to point them back to the documentation...

**Comment by Alvaroalconada** [comment]
@matthewrgourd Really can´t you help me what happen with the above data?

**Comment by matthewrgourd** [comment]
Hi @Alvaroalconada, I'm afraid not.
