### ISSUE TITLE
Simple checkout access

### ISSUE THREAD

**Issue by MikaCheloudtchenko** [VivaPayments/API#2061]
Hi, is it possible to open simple checkout access for the merchant 59fbf24a-ab95-4951-956c-af20d36f1c5c ?

**Comment by matthewrgourd** [comment]
Hi @MikaCheloudtchenko, Simple Checkout API enabled for you in demo environment. Thanks.

**Comment by MikaCheloudtchenko** [comment]
Thank you, can you open now acces for live environment for merchant id d62f0874-2b7b-4514-afbd-2fb53da7267c

**Comment by matthewrgourd** [comment]
Hi @MikaCheloudtchenko, that's done for you now. Best regards.

**Comment by MikaCheloudtchenko** [comment]
Thank you
