### ISSUE TITLE
Shopify x Viva Wallet : Error. Could not create order. Generic Error.

### ISSUE THREAD

**Issue by Nilsouchi** [VivaPayments/API#2062]
Hello,

I am having an issue with Shopify checkout with Viva Wallet.
I am sure that I have used the right Merchant ID and Store Token, but when I try to checkout using Viva Wallet, I get this error message : 

Error.
Could not create order. Generic Error.

I see that this issue has already been discussed here in the past. Can someone help me please ?

Thank you

Nils

**Comment by matthewrgourd** [comment]
Hi @Nilsouchi, sorry to hear this. Strangely, this can happen if you change your Viva Wallet API key in your account settings during the process of Shopify integration. Have you by any chance done that in the past week or so?

**Comment by Nilsouchi** [comment]
Hello,

Thank you for your answer. To be honest I don't remember changing the API
key but it's possible yes.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 15 déc. 2020 à 08:20, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @Nilsouchi, ok, I will check this out for you. Please send your Viva Wallet Merchant ID and Shopify token to my email address at mgourd@vivawallet.com quoting this issue (#2062).

**Comment by matthewrgourd** [comment]
Hi @Nilsouchi, thanks for sending through the requested info. We're still looking into a fix.

**Comment by matthewrgourd** [comment]
Hi @Nilsouchi it should be working now. Please check and get back to me if any further issues.

**Comment by Nilsouchi** [comment]
Hello, it seems to work fine thank you ! I made a test order and received
the funds. Do you know the time between the transaction and the transfer to
my "available balance" ?

Thank you again

Nils



Le mer. 16 déc. 2020 à 14:35, matthewrgourd <notifications@github.com> a
écrit :

**Comment by matthewrgourd** [comment]
Hi @Nilsouchi, good to hear. Clearance is overnight so you should receive the money within 24 hours.
