### ISSUE TITLE
Your transaction failed or has been cancelled in magento2

### ISSUE THREAD

**Issue by Gopalvegans** [VivaPayments/API#2065]
Hello 

We have create live viva wallet account (account verification is in process) and configure from admin.

While we are testing into our live server , **we are getting Your transaction failed or has been cancelled.**

![photo_2020-12-16_20-39-36 (1)](https://user-images.githubusercontent.com/76115640/102367147-6f26c200-3fdf-11eb-8258-771941615e6b.jpg)

Could you please guide me asap?

Thanks

**Comment by matthewrgourd** [comment]
Hi @Gopalvegans, sounds like a card issue rather than problem with our plugin. Could you let me have your website address so I can have a look?

**Comment by matthewrgourd** [comment]
Closing as no reply
