### ISSUE TITLE
Redirection/Native Checkout v2 

### ISSUE THREAD

**Issue by naturways** [VivaPayments/API#2066]
Hello, 

I have an issue with payment redirection from native checkout as it always takes me to an error page instead of the page I have set up.

Not sure why the url it redirects is a long url. 

Thank you.

![viva wallet redirection error](https://user-images.githubusercontent.com/76122539/102384863-14806c80-3fc5-11eb-9a3a-f440c38de596.JPG)

**Comment by matthewrgourd** [comment]
Hi @naturways, do you have a website or code I can check?

**Comment by naturways** [comment]
Hi, Yes the website is naturways.shop

**Comment by matthewrgourd** [comment]
Hi @naturways, your payment source settings were wrong. I've corrected them now and it works fine. FYI, we've got a newer plugin for WooCommerce now that embeds into your checkout. For an improved customer experience you should install that. Payment source creation is automatic so you should find it easier to install. Please see below if you're interested in doing that:

https://docs.woocommerce.com/document/viva-wallet-for-woocommerce

**Comment by naturways** [comment]
Problem solved! Thank you Matthew I appreciate your help.
