### ISSUE TITLE
Error with module for Prestashop 1.6

### ISSUE THREAD

**Issue by mirkocoppola80** [VivaPayments/API#2067]
Hello,
i have an account business vivawallet, and a prestashop 1.6.
When i install the module as in your guide for developer it returns an error Fatal error in module file :/home/ryogivtf/domains/diakosmo.gr/public_html/modules/vivawallet/vivawallet.php:
and doesn't let me enter in modules at all. 
I had to rename the module from ftp in order to have again modules tab function.

Can you help ?

**Comment by matthewrgourd** [comment]
Hi @mirkocoppola80, sorry to hear that? Can you let me know your website address please so I can investigate?

**Comment by iliasiovis** [comment]
Hi, same issue here. any progress?

**Comment by matthewrgourd** [comment]
Closing as no reply from issue reporter...

**Comment by Jajcjusz** [comment]
where I can find version of module for Vivawallet for Prestashop 1.6?

**Comment by gemitsio** [comment]
Hi there, 

Many thanks for your request. You may update your prestashop version to the latest. Also, please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
