### ISSUE TITLE
Multiple Transactions fail with simple checkout

### ISSUE THREAD

**Issue by vassilismon85** [VivaPayments/API#2070]
I had opened several days ago an issue (#2045), with a problem that seemed that was solved by you.
The past days, I am getting again server error code 502 in many transactions.
Just today I had these transactions failed, with the same error code:
72e1883b-94ee-46b5-bdef-5157a3eeaf47
7e113353-9a30-47de-9019-9423e7321672
3ae7bb76-0366-4f2b-9650-bfddd21daa44
7aa777ab-d0b2-4e72-8e4d-5b01a26bf8dd
471c71ee-6d4a-4f6b-a4df-afed456bf5a6
ff78eea6-20a9-4a9a-9595-2e4f3547d7c3
9c5ac43a-ded0-4117-9236-c6c0adc6d8de

Could it be the same problem as in issue (#2045)?

**Comment by mavr1982** [comment]
Hi @vassilismon85,

We have been checking those transactions and all of them were rejected by the card issuer.

I hope that helps.
