### ISSUE TITLE
Erro in Transactions (PaymentsCardHolderAuthenticationInvalidStatus)

### ISSUE THREAD

**Issue by ccastiglioni** [VivaPayments/API#2073]
hello I'm trying to finalize a transaction (https://demo-api.viva payments.com/nativecheckout/v2/transactions) but the following error is appearing:
```
array(3) {
  ["status"]=>int(403)
  ["message"]=> string(38) "PaymentsCardHolderAuthenticationFailed"
  ["eventId"]=> tring(4) "2062"
}
```

I don’t know where I’m wrong because I’m sending all the data you ask for:
My CURLOPT_HTTPHEADER:
```
array(2) {
  [0]=>  string(86) "Authorization: Bearer 10aec59a02e13efe619d9d28b7e1cf4fcb762d1e380f342040cf53989e76a1a0"
  [1]=> string(30) "Content-Type: application/json"
}
```
My CURLOPT_POSTFIELDS:
```
 {"amount":"10000",
 "chargeToken":"ctok_NfrFHcqVtzMfm2LwYUCyTSsg4GQ",
 "installments":1,
 "preauth":false,
 "sourceCode":"6505",
 "merchantTrns":"The user CLEBER RODRIGUES CASTIGLIONI recived 10000",
 "customerTrns":"Contact user recipient: +5551997559868",
 "currencyCode":"978",
 "customer":{"email":"altar@gmail.com",
 "phone":"44998787987",
 "fullname":"altar",
 "requestLang":"en",
 "countryCode":"GB"}
}
```
I'm using 5511070000000020 , 01/2023 , cvv 111
 pls help me!

**Comment by mavr1982** [comment]
Hi @ccastiglioni,

Sorry to hear you are facing issues.

Please check the error list provided in https://developer.vivawallet.com/web-api-integration/error-codes/

This is the info about the error what you get.
2062 | 3DS validation failed | Wrong password or two-factor auth code entered.

I hope this helps you.

Merry Christmas.

**Comment by jonian** [comment]
Hi @mavr1982, I'm having the same issue. Data sent are correct.

Sometimes this issue does not happen. Any more help than checking the error codes?

**Comment by mavr1982** [comment]
Hi @jonian 

Please check the issue [#2040](https://github.com/VivaPayments/API/issues/2040)

**Comment by jonian** [comment]
@mavr1982 That issue did not help because I'm using Native Checkout v2 with JS in an SPA application.

I used the card number suggested in #2040 (5511070000000020) and the first payment, with correct data, was successful.  
After trying a payment with incorrect data (CVV and Exp. Date), any payment, even with correct data, fails with event_id 2061.

In production, some users can't complete their payment. They have tried with multiple cards.

**Comment by mavr1982** [comment]
@jonian I would need to research further but I would suggest you try to get a new charge token after a failed payment.

**Comment by jonian** [comment]
@mavr1982 I already generate new `access_token` and `charge_token` after a failed payment.

**Comment by mavr1982** [comment]
Please @jonian open a new issue and I personally will check tomorrow morning.

**Comment by ccastiglioni** [comment]
tnks for the anwser @mavr1982 .So the password is correct.. I got it in **Settings->Api Access-> ID Secret** .
So whats do you meaning "two-factor auth code entered" ? Because I got a _charge token_ and  _access token_ and I put in curl when I call (https://demo-api.vivapayments.com/nativecheckout/v2/transactions)

**Comment by ccastiglioni** [comment]
@mavr1982 .. why do you closed my issue? you didn't even answer my question!
