### ISSUE TITLE
Access to Simple Checkout API for demo

### ISSUE THREAD

**Issue by ReneRousso** [VivaPayments/API#2074]
I have to use the Simple Checkout API for demo(software development), so  I need you give me access to this API.
Tell me, please, what information you want from me.

**Comment by ReneRousso** [comment]
Also, I try to connect Payment Checkout and the message 'demo.vivapayments.com refused to connect'  is displayed in Browser.
The same happens when select he sample  'https://jsbin.com/zomuqogawu/1/edit?html,output'.
Please, what's the wrong about it?

**Comment by mavr1982** [comment]
Hi @ReneRousso 

Please follow the instructions provided in https://developer.vivawallet.com/online-checkouts/simple-checkout/ to use our Simple Checkout API. If you want to use our Demo environment you must create an account in https://demo.vivapayments.com/en/signup.

Merry Christmas.

**Comment by matthewrgourd** [comment]
Hi @ReneRousso, for access to our Simple Checkout please send me your merchant ID and I will enable the API for you: mgourd@vivawallet.com

**Comment by ReneRousso** [comment]
Merchant Id:  20764269-fed0-43a6-b6eb-b2ed06bf724d

**Comment by ReneRousso** [comment]
Hello,
I’m working on https://demo.vivapayments.com.

[cid:image002.png@01D6E355.8F5EAC40]

[cid:image006.png@01D6E355.8F5EAC40]


Merchant Id:  20764269-fed0-43a6-b6eb-b2ed06bf724d
I’ve got the Public Key (from  bottom of page ) but
When I ask for pay (via Simple Checkout ), the error ‘Invalid merchant public key’ is returned.

**Comment by matthewrgourd** [comment]
Hi @ReneRousso, that's enabled for you now in the demo environment. Thanks.
