### ISSUE TITLE
Issue in Simple Checkout Method

### ISSUE THREAD

**Issue by khurrameycon** [VivaPayments/API#2076]
Hi i am setting checkout with Simple Checkout procedure of Vivawallet and i am getting this error 
{"FriendlyMessage":"Source not found"}
I am right now setting a demo and then will switch to Live production. 

Kindly guide me so that i can work on demo and live after. 

Regards

**Comment by khurrameycon** [comment]
After adding the live production Public key its now giving me error : 

{"FriendlyMessage":"Invalid merchant public key"}

**Comment by mavr1982** [comment]
Hi @khurrameycon,

It seems you are using wrong credentials on the environment you are calling to. If you are using Demo env then you must use credentials from your demo account.

Merry Christmas

**Comment by khurrameycon** [comment]
I made account on Demo.vivapayments.com and got the public key from that account. But still its displaying error "{"FriendlyMessage":"Source not found"}"

**Comment by mavr1982** [comment]
Hi @khurrameycon 

Seems you are using a wrong source code for that environment. data-vp-sourcecode is an optional parameter so you can remove it from your calls and test if that helps.

**Comment by matthewrgourd** [comment]
Hi @khurrameycon, please close this issue if you are experiencing no further problems after our advice.

**Comment by khurrameycon** [comment]
Hi 
Thanks alot @mavr1982 for your support. The issue has been resolved by removing the optional parameter
