### ISSUE TITLE
Viva Wallet for Woocommerce Credential error

### ISSUE THREAD

**Issue by Microstudio258** [VivaPayments/API#2077]
Hello! Installed the Viva Wallet for Woocommerce plugin, inserted  the Native Checkout v2 Credentials 
(ID client and a secret key) but there are the following errors:

Viva Wallet: Your LIVE credentials are NOT valid. Please check your credentials!

And on the check-out page (as a customer that tries to buy a product) : Thank you for your order — please click the button below to pay. 

And then — no button but this message: 

"there has been a critical error on this website." 

This is rather urgent, my customers are already asking when they can order, I really wish you can help me.

**Comment by mavr1982** [comment]
Hi @Microstudio258 

That message means you are using some kind of wrong data when setting up the plugin.

Please follow the instructions provided for our WooCommerce plugin https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/

Merry Christmas

**Comment by Microstudio258** [comment]
Hello Miguel, thank you!

So I changed the credentials and it worked. 4 messages in green in the settings page of woocommerce — payments. 


But: 

As I tested, after I entered the card details, a message appeared saying " There was a problem with your card. Please check the card details and try again." 

Tried it with two cards, both valid. 

Any further help is highly appreciated!

**Comment by mavr1982** [comment]
Hi again @Microstudio258

It seems some kind of problem with the cards.

In your WooCommerce dashboard you should be able to see the orders with a status pending payment. Please go inside them and look for the correlation ids of the errors. You can find them in order comments. Send us the correlation ids what you get.

Moreover, please provide us with your merchant Id so we can trace your transactions in our CRM.

Thanks.

**Comment by Microstudio258** [comment]
Hei there!

Here is one order: 
Transaction failed with Viva-CorrelationId: 20-358-5A310A32

and the other one: 
Transaction failed with Viva-CorrelationId: 20-358-A5739E43

My merchant ID is 44901db1-a4c2-4705-ad48-bf529c298b0a

Thanks!

**Comment by Microstudio258** [comment]
Oh, i disabled card payments for the moment, there are customers already who want to order and I didnt want to confuse them with the option that doesnt work yet. But if it's necesary I can turn it on again.

**Comment by mavr1982** [comment]
Hi @Microstudio258 

We have been checking the logs and it seems those transactions were posted with currency EUR but your account is set in Romania so you can only accept payments in RON.

It also seems you are using an old version of our WooCommerce plugin, I would encourage you to install the latest version which includes many improvements and new features. You can find the plugin in: https://woocommerce.com/products/viva-wallet-for-woocommerce/

Merry Christmas.

**Comment by Microstudio258** [comment]
Thank you Miguel!

I suspected there might be a problem with not having an euro account
connected to the plugin.

Thanks for informing me about the plugin, i downloaded it following  the
documentation i got from viva.

Will go through that again and hope it works after i have that account
open.

Merry Christmas to you too!
