### ISSUE TITLE
Αδυναμία δημιουργίας παραγγελίας και μετάβασης στο viva

### ISSUE THREAD

**Issue by marinaofpiraeus** [VivaPayments/API#208]
Καλησπέρα. 

Έχω δημιουργήσει μια ιστοσελίδα την οποία έχετε εγκρίνει, έχω δηλαδή κωδικούς api κλπ. Έχω βάλει ένα plugin για virtuemart στο website μου, με όλα τα στοιχεία σωστά, αλλά δεν μπορεί να συνδεθεί. Οι κατασκευαστές του plugin λένε πως κολλάει στη σύνδεση με το api, προφανώς λόγω firewall. Ακόμη και με κλειστό το firewall του server μου δεν μπορώ να συνδεθώ. Υπάρχει περίπτωση να μπλοκάρει το δικό σας site την σύνδεση, ή τι άλλο μπορεί να συμβαίνει;

Εΰχαριστώ.

**Comment by krakenrules** [comment]
Μπορείτε να μας στείλετε το merchant id σας, καθώς και το περιβάλλον στο οποίο πραγματοποιείτε δοκιμές (demo ή live), για να δούμε τι έχει συμβεί;

Ευχαριστούμε,

**Comment by marinaofpiraeus** [comment]
Το site είναι το http://christinachristijewels.com/ . Μπορείτε να χρησιμοποιήσετε όνομα χρήστη Marina και κωδικό 123456 για τις δοκιμές σας. Το merchant id είναι το 	9e7c79e2-3a61-4fbd-ba63-7f6a9b461aeb.

Ευχαριστώ.

**Comment by krakenrules** [comment]
Καλημέρα,

Τα παρακάτω url απο τις ρυθμίσεις που έχετε είναι σωστά, και το site σας επιστρέφει σωστή σελίδα. 
http://christinachristijewels.com//index.php?option=com_virtuemart&b=vivapayments&task=ok
http://christinachristijewels.com//index.php?option=com_virtuemart&b=vivapayments&task=cancel	

Δοκιμασαμε να κανουμε login με τα στοιχεια που μας δώσατε ανεπιτυχώς.

Ευχαριστούμε

**Comment by marinaofpiraeus** [comment]
Καλημέρα. Το μήνυμα που λαμβάνω μετά την παραγγελία είναι αυτό.

![capture](https://cloud.githubusercontent.com/assets/24418282/21012265/e18bc164-bd5d-11e6-871c-a1b7a7d6a605.PNG)

**Comment by krakenrules** [comment]
Γεια σας, 

Με βάση το μήνυμα φαίνεται ότι υπάρχει ανοικτό firewall στην δική σας υποδομή. 

Ευχαριστούμε

**Comment by marinaofpiraeus** [comment]
Το μήνυμα το άλλαξε αυτός που έφτιαξε το plugin. Έχω κλείσει το firewall του server και πάλι παίρνω αυτό το μήνυμα. Υπάρχει περίπτωση να μπλοκάρετε το ip μου με κάποιο τρόπο;

**Comment by krakenrules** [comment]
Γεια σας,

Για να επιβεβαιώσετε ότι δεν υπάρχει θεμα με το firewall δοκιμάστε να συνδεθείτε από τον webserver σας στο https://www.vivapayments.com.

Ευχαριστούμε
