### ISSUE TITLE
Viva wallet/Shopify error code

### ISSUE THREAD

**Issue by Hotboxin** [VivaPayments/API#2083]
Hi,

when customers are trying to pay through my website they fill there details in and once done an error shows up not allowing them to confirm the payment/order. My merchant ID has been correctly entered and the token also but it still isn’t working, how can I sort this?

thanks

callum
![D83E31C7-FEDA-4FBD-BE7D-FDC80C45DA0B](https://user-images.githubusercontent.com/76788222/103371449-62b66500-4ac7-11eb-9d20-1f8c6121d6af.jpeg)

**Comment by matthewrgourd** [comment]
Hi @Hotboxin, please email me your merchant ID and Shopify token so I can check that they look correct. I take it the latter we emailed to you separately? If you could quote this issue (#2083) when you do so, that would be great. Thanks.

**Comment by matthewrgourd** [comment]
Closing as no reply...
