### ISSUE TITLE
/api/Wallets - Authorization has been denied

### ISSUE THREAD

**Issue by pRieStaKos** [VivaPayments/API#2085]
Hello,

We updated WHMCS to 8.1 and our Vivawallet widget stopped working. 

With the same code and same API key, API call returns the following error: 

'_Authorization has been denied for this request._'

The api URL is the same to get the wallets info: '_vivapayments.com/api/Wallets_'

We change the response variables to lowercase as in your developers documentation, but we get the same error about authorization.

Any suggestions ? 

**Merchant ID:** _8998c675-3218-426e-be17-0972e62da918_

**Comment by matthewrgourd** [comment]
Hi @pRieStaKos, sorry to hear this. what is the exact API call you're trying to make? Can you also let me know what section of our developer portal you're referring to?

**Comment by pRieStaKos** [comment]
Hello,

Thank you for your reply.

As I already mentioned, I call /api/Wallets to get wallet info.

https://developer.vivawallet.com/web-api-integration/account-api/#retrieve-wallet-info

It was working since I update my WHMCS. Nothing else is changed.

**Comment by matthewrgourd** [comment]
Hi @pRieStaKos ok, thanks. So that API call is for partners of Viva Wallet and not open to the general public. Can you confirm that you have a special agreement with us to use that API call?

**Comment by pRieStaKos** [comment]
The merchant id is from a business account ? Is this different from a partner ? 
If yes, when did this changed without any notice ?

**Comment by matthewrgourd** [comment]
Hi @pRieStaKos, all I'm saying is that you would normally need a special agreement with us to access that specific API call. I assume you do since it was working for you before. Let me speak to our development team and try to find out what the problem might be.

**Comment by matthewrgourd** [comment]
Hi @pRieStaKos, sorry for any confusion. I think I've worked out the issue now. We don't offer an official plugin for WHMCS but perhaps you've installed this one here: https://whmcs.community/topic/233025-viva-payments-gateway-for-whmcs/. This is not an official extension from Viva Wallet I'm afraid, so I'm unable to support you. Probably best to try contacting the plugin developer directly. Sorry I can't help any further.

**Comment by pRieStaKos** [comment]
Hi @matthewrgourd,

I'm not using this WHMCS module, but I mentioned that this was a widget issue, that I developed using cURL and Account API, to get the wallet info.

On WHMCS 7.10, this was working well and we didn't have any issues, connecting to the API with our Merchant ID and API key. Same as our [third-party VivaPayments payment gateway](https://web-expert.gr/en/whmcs-addons-modules/item/47-whmcs-vivapayments-gateway), which is still working on WHMCS 8.1 (we asked the developert before updating).

Below is a part of our widget code:

```
$request = 'https://www.vivapayments.com/api/Wallets'; // production environment URL

// Get the curl session object
$session = curl_init($request);

// Set the GET options.
curl_setopt($session, CURLOPT_URL, $request);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, "$MerchantId:$APIKey");
curl_setopt($session, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($session, CURLOPT_SSL_VERIFYPEER, false);

// Do the GET and then close the session
$response = curl_exec($session);

curl_close($session);

$results = json_decode($response, true);
```

And the response we get after the WHMCS update is `Authorization has been denied for this request.`

**Comment by matthewrgourd** [comment]
Hi @pRieStaKos, ok, apologies for the misunderstanding. Are you sure you've not changed your API key? I just tried the following and I'm getting a 200 ok using your current credentials in base 64 format:
```
curl -L -X GET 'https://www.vivapayments.com/api/Wallets' \
-H 'Authorization: Basic [your merchant ID and API in Base 64]
```

**Comment by pRieStaKos** [comment]
This was not base64 before. Issue has been resolved.

Thank you @matthewrgourd
