### ISSUE TITLE
Webhook 502 error

### ISSUE THREAD

**Issue by sumanth05** [VivaPayments/API#2087]
I am adding a webhook for my Jenkins but it not delivered giving 502 error
![IMG_20210105_173045__01](https://user-images.githubusercontent.com/55985114/103644334-3b0a4580-4f7c-11eb-89e0-8d9d35373dd2.jpg)
![IMG_20210105_173453__01](https://user-images.githubusercontent.com/55985114/103644444-6725c680-4f7c-11eb-9d97-20afe19d905d.jpg)

**Comment by matthewrgourd** [comment]
Hi @sumanth05, FYI, you're raising this issue on the Viva Wallet public GitHub issues page. Please provide more context as at the moment I can't see how it relates to any of our payment products.

**Comment by matthewrgourd** [comment]
@sumanth05 does this relate to a Viva Wallet webhook at all? If not, please close the issue as this board is for Viva Wallet-related queries only. Thanks.

**Comment by sumanth05** [comment]
Sure will close the issue

**Comment by sumanth05** [comment]
As it not regards about viva payments
