### ISSUE TITLE
Access to simple checkout API

### ISSUE THREAD

**Issue by Add1ctiv3** [VivaPayments/API#2089]
Hello I am trying to implement the simple checkout API in an app I am developping. 

My merchant account is 

57e8a105-7f70-4f7c-b59e-cf2f3e681247

**Comment by matthewrgourd** [comment]
Hi @Add1ctiv3, that's enabled for you now. Best wishes.

**Comment by Add1ctiv3** [comment]
Followed the instructions here https://developer.vivawallet.com/online-checkouts/simple-checkout/ by the letter. Included the script, copy pasted the button/form code and copy pasted the public_key and the source code.

Refreshed the page and got this --> Failed to load resource: the server responded with a status of 404 (Not Found)

Been trying to work with native v2 last couple of days. That didnt go so well. Now followed the instructions for the simple checkout and still having trouble. Is there something wrong with the instructions pages??

**Comment by matthewrgourd** [comment]
Hi @Add1ctiv3, sorry to hear this. Can you share with me your code as it's working fine for me?

**Comment by Add1ctiv3** [comment]
<button type="button" 
data-vp-publickey="/hzAX+NFP1b/yOAlAF6fTUTTqfbqnBJEp306BOBPtl+w=" 
data-vp-baseurl="https://demo-api.vivapayments.com" 
data-vp-lang="el" 
data-vp-amount="370.76" 
data-vp-sourcecode="1139" 
data-vp-description="My product" 
data-vp-disablewallet="true" 
data-vp-expandcard="true" 
style="font-weight: bold; cursor: pointer; border: none; padding: 10px 20px; font-family: Arial; font-size: 14px; outline: none; background-color: rgb(3, 4, 8); color: rgb(255, 255, 255); border-radius: 10px;">

Πληρωμή

</button>

<script src="https://demo.vivapayments.com/web/checkout/js"></script>

I changed the public key here so that the original one isnt displayed (despite it being public) but I surely have the correct one typed in.
