### ISSUE TITLE
Redirection on 404

### ISSUE THREAD

**Issue by panosgtx** [VivaPayments/API#209]
Καλημέρα,

   Αντιμετωπίζω ξαφνικά πρόβλημα με το redirection μετά την πληρωμή στο viva waller. Η πληρωμή περνάει αλλά με γυρνάει σε 404 Error στην σελίδα μου. Το πρόβλημα δημιουργήθηκε μετά από αλλαγή hosting provider χωρίς να έχει γίνει άλλη αλλαγή στο configuration. Μπορεί κάποιος να με βοηθήσει?

**Comment by defilerc** [comment]
Καλησπέρα @panosgtx ,

Θα πρέπει να αλλάξετε τα URLs της πηγής πληρωμών που χρησιμοποιείτε, ώστε να δείχνουν στο καινούριο domain σας.

Με εκτίμηση,

**Comment by panosgtx** [comment]
Καλησπέρα,
Δεν έχει αλλάξει το URL της πηγής των πληρωμών. Αλλάχτηκε μόνο ο hosting provider, δηλαδή μόνο η ip του domain.

**Comment by defilerc** [comment]
Καλησπέρα @panosgtx ,

Αν το domain παραμένει το ίδιο, τότε αν καταλαβαίνω καλά, σας κάνει redirect στα success/fail URLs που έχετε ορίσει εσείς στο configuration της πηγής.

Επομένως γίνεστε redirect σε κάποιο URL που εσείς έχετε ορίσει. Θα πρέπει να είναι υπαρκτό URL του site σας, ώστε να μην παίρνετε 404 (not found) error.

Με εκτίμηση,

**Comment by panosgtx** [comment]
Μάλιστα κατάλαβα. Μία ερώτηση ακόμα. Έχω παραλάβει το e-shop από άλλο developer. Το e-shop είναι φτιαγμένο με woocommerce. Στις ρυθμίσεις του viva φαίνεται να είχε τοποθετήσει ο προηγούμενος developer και στα δύο link το ίδιο page το οποίο όμως δεν υπάρχει πλέον. Είναι δυνατόν κάτι τέτοιο να είχε υλοποιηθεί? Η συνναλαγή δεν επιστρέφει κάποιο μήνυμα που να εμφανίζεται στην σελίδα? Και τέλος, τα δύο link που αναφέρει ο οδηγός της viva ως επιστροφή, σε τι αποσκοπούν? Όταν τα δήλωσα η επιστροφή στο site ήταν μία σελίδα με ένα "-1" εκτυπωμένο μόνο. 
Ευχαριστώ πολύ για την βοήθεια,

**Comment by defilerc** [comment]
Καλησπέρα @panosgtx ,

Μπορείτε να το χειριστείτε είτε με δύο διαφορετικά URLs, είτε χρησιμοποιώντας ένα κοινό και κάνοντας διαχωρισμό στον κώδικα του controller που δέχεται το request από τη Viva.

Περισσότερες πληροφορίες μπορείτε να δείτε εδώ: https://github.com/VivaPayments/API/wiki/Redirect-Checkout

Με εκτίμηση,

**Comment by panosgtx** [comment]
Θα το κοιτάξω. Σας ευχαριστώ πολύ.

**Comment by panosgtx** [comment]
Έφτιαξα μία και μία σελίδα στο site μου για την επιτυχημένη και αποτυχημένη πλρωμή στην viva. Η κατάληξη ήταν η ίδια. Για επιβεβαίωση, έχω τοποθετήσει:

URL Επιτυχημένης συναλλαγής:
mydomain/orders-received/

URL Αποτυχημενης συναλλαγής:
mydomain/orders-failed/

Πρέπει να προσθέσω κάτι ακόμα στα URL? Γιατί δεν μου εμφανίζει την σελίδα που έχω φτιάξει αλλά 404 error?

**Comment by defilerc** [comment]
Μπορείτε να μας στείλετε ένα παράδειγμα με ένα URL που σας κάνει redirect η viva checkout?

Θα πρέπει αυτή τη σελίδα να μπορείτε να τη δείτε από το browser σας αν τη βάλετε στο address bar.

Επίσης, στείλτε μας το merchant id σας, ώστε να μπορούμε να δούμε τι ακριβώς συμβαίνει.

Με εκτίμηση,

**Comment by panosgtx** [comment]
Ένα URL είναι: http://mydomain/order-failed/?t=d38370ca-cb3a-4782-9fd6-b2d1b10f7ce5&s=5940758574772604&lang=el-GR

Ο κωδικός για την πηγή πώλησης είναι: 9890
Το merchantid: f6e6df53-6368-4adc-827c-9d7670389799

**Comment by defilerc** [comment]
Θα πρέπει μετά το `order-failed` να μην υπάρχει slash (/). Επίσης, το `mydomain` υποθέτω είναι το πραγματικό URL του site σας.

Επομένως, ρυθμίστε τα success/fail URLs σας, να μην έχουν slash στο τέλος. Ένα παράδειγμα σωστού URL είναι το εξής:

`http://sitedomain/order-failed?t=d38370ca-cb3a-4782-9fd6-b2d1b10f7ce5&s=5940758574772604&lang=el-GR`

Με εκτίμηση,

**Comment by panosgtx** [comment]
Έχω ρυθμίσει τα URLs χωρίς το / Το αποτέλεσμα είναι πάλι το ίδιο. Σας γράφω ολόκληρο το URL: 
http://audiction.gr/orderf?t=b919f289-51de-47ab-9271-7f626d58f424&s=4743039199472601&lang=el-GR

Η σελίδα orderf υπάρχει και έχει ένα μικρό κείμενο μέσα. Πάλι δέχομαι 404 error

**Comment by defilerc** [comment]
Καλησπέρα @panosgtx ,

Θα πρέπει να το δείτε με κάποιον από τους διαχειριστές του site σας, καθώς δεν είναι θέμα API. Όταν κάποιος πάει να κάνει navigate στη σελίδα:

http://audiction.gr/orderf?t=b919f289-51de-47ab-9271-7f626d58f424&s=4743039199472601&lang=el-GR

παίρνει error από το server σας: 301 Moved Permanently και γίνεται redirect. Κανονικά, δε θα έπρεπε να συμβαίνει αυτό.

![error_301](https://cloud.githubusercontent.com/assets/1667459/20973030/b2cffb2e-bc9f-11e6-899a-abf353c1e62a.png)

Με εκτίμηση,

**Comment by panosgtx** [comment]
Διαχειριστείς της σελίδας είμαι εγώ ο ίδιος. Καταλαβαίνω ότι το API κάνει html redirection πίσω στο site μου. Το θέμα είναι ότι δεν βρίσκει όλο αυτό το path που του στέλνει πίσω. Μήπως χρειάζεται κάτι παραπάνω από αυτά που αναφέρονται στα instructions? 

Επίσης στο instruction αναφέρεται ότι πρέπει να βάλω τα:
 wc-api/WC_em_Vivapayments_Gateway ή αν τα friendly urls(permalinks) είναι ενεργοποιημένα σε διαφορετική περίπτωση ?wc-api=WC_em_Vivapayments_Gateway

Αν βάλω αυτά δεν γυρνάει καθόλου στην σελίδα. 

Ψάχνω λοιπόν ποιά είναι τα βήματα που πρέπει να ακολουθήσω. Σας γράφω τι βήματα ακολουθώ και τα κάνω παράλληλα αυτή τη στιγμή:
1. Φτιάχνω μία σελίδα ordersaccepted και μία ordersdenied
Οι σελίδες υπάρχουν και είναι εδώ: http://audiction.gr/ordersaccepted/ και http://audiction.gr/ordersdenied/
2.Τοποθετώ τις σελίδες στο vivawallet χωρίς να έχουν / στο τέλος
3. Πραγκατοποιώ αγορά και δέχομαι το 404 error. Το URL που γυρνάει είναι: http://audiction.gr/ordersdenied/?t=bcdaec9e-c5f5-4c9c-a47e-9fa075ea601a&s=8798858152172601&lang=el-GR και τοποθετεί αυτόματα το σύστημα το / στο τέλος της σελίδας, το οποίο δεν θα έπρεπε να το ενοχλεί λόγω τον permalinks που χρησιμοποιεί το site. 

Θα μπορούσατε να με βοηθήσετε περαιτέρω?

**Comment by defilerc** [comment]
Καλησπέρα @panosgtx ,

Το API όπως είπατε, κάνει ένα HTTP GET request στο site σας για να σας ενημερώσει για την κατάληξη της παραγγελίας. Αυτό το URL θα έπρεπε κανονικά να μπορείτε να το χτυπάτε και από το browser σας, αλλά αυτό απ' ότι φαίνεται δεν είναι δυνατό.

Υποθέτουμε πως είναι κάποιο configuration στο server σας, που πρέπει να επιλύσετε. Όσον αφορά τις ρυθμίσεις για το integration με τη Viva, φαίνεται να είναι σωστές.

Τώρα αν απαιτείται κάποια επιπλέον ρύθμιση στο εξωτερικό plugin που χρησιμοποιείται, δυστυχώς δε μπορούμε να το γνωρίζουμε.

Με εκτίμηση,

**Comment by panosgtx** [comment]
Καταλαβαινω. Ξερετε ομως που μπορω. Α απευθυνθω; Δεν μπορω να κανω καποιο configuration χωρις να ξερω ακριβως τι ζηταει το ΑΡΙ.

**Comment by panosgtx** [comment]
Υπάρχει περίπτωση να χρειάζεται χρόνος για να ενεργοποιηθούν τα urls ή το όλο plugin μέχρι αν δουλέψει το plugin σωστά?

**Comment by defilerc** [comment]
Καλησπέρα @panosgtx ,

Δεν υπάρχει κάτι που θα πρέπει να ενεργοποιηθεί από τη μεριά του API. Η Viva κάνει ανακατεύθυνση τον πελάτη σε σελίδα του site σας και η σελίδα αυτή παίρνει status 301 Moved Permanently και γίνεται ανακατεύθυνση από τη μεριά του server σας σε άλλη σελίδα που δεν υπάρχει.

Θα πρέπει να επιλύσετε το θέμα με τα redirections από τη μεριά του server σας. Δεν είναι θέμα του API, καθώς και από τον browser αν χτυπήσετε κάποιο από τα URLs (π.χ. το http://audiction.gr/orderf?t=b919f289-51de-47ab-9271-7f626d58f424&s=4743039199472601&lang=el-GR ) θα πρέπει να εμφανίζεται μια σελίδα του site σας που να ενημερώνει το χρήστη για την επιτυχία ή την αποτυχία της συναλλαγής.

Με εκτίμηση,

**Comment by panosgtx** [comment]
​Καλημέρα σας,

   Για να εμφανίζει η σελίδα μου κάτι στο link που μου δίνεται, θα πρέπει
να υπάρχει σελίδα με το ίδιο link. Προφανώς και αυτό δεν γίνεται γιατί το
link το παράγετε εσεις και όχι η σελίδα μου. Η σελίδα μου έχει link όπως
αναφέρετε εσείς στο pdf Instruction και αυτή είναι η ​
http://audiction.gr/orderf/ και αντίστοιχα η orderc. Εδώ θα έπρεπε να
γίνεται η ανακατεύθυνση μετά την φόρμα σας. Ο Server μου δεν κόβει κάποια
κίνηση ούτε το site μου απαγορεύει κάποιο link. Δεν έχετε αντιμετωπίσει
ξανά τέτοιο πρόβλημα σε άλλον πελάτη σας? Τι λύση δόθηκε?

   Εφόσον κρίνετε ότι έχουμε εμείς κάπου το πρόβλημα, δώστε μου ένα
documentation για τις βέλτιστες ρυθμίσεις που πρέπει να έχει ο hosting
server μου και το wordpress site μου ώστε να δουλεύει η υπηρεσία σας.

   Περιμένω νέα σας,

Με εκτίμηση,

---
Panagiotis Georgakopoulos
M: +30 694 7782381
E: panos.g.tx@gmail.com

*P* *Please consider the environment. Do you really need to print this
email?*


Στις 13 Δεκεμβρίου 2016 - 5:24 μ.μ., ο χρήστης Konstantinos Athanasoglou <
notifications@github.com> έγραψε:

**Comment by defilerc** [comment]
Καλημέρα @panosgtx ,

Η σελίδα `http://audiction.gr/orderf/` θα πρέπει να υπάρχει από τη μεριά σας, αλλά να δέχεται και σαν παραμέτρους τις μεταβλητές `t`, `s` και `lang` που σας περνάμε.

Για αρχή, δοκιμάστε να αναπροσαρμόσετε τη σελίδα `http://audiction.gr/orderf` έτσι ώστε να δέχεται σαν όρισμα το `t` (transaction id) και να το εκτυπώνει στη σελίδα.

Δηλαδή, θα πρέπει κάποιος, αν κάνει navigate στη σελίδα `http://audiction.gr/orderf?t=b919f289-51de-47ab-9271-7f626d58f424` να μπορεί να βλέπει το transactionId που έχει περαστεί σαν παράμετρος στο URL.

Με εκτίμηση,

**Comment by panosgtx** [comment]
Στην ουσία θέλετε η σελίδα να περιέχει κώδικα. Έχουμε κάποιο κάποιο sample για αυτό τον κώδικα που πρέπει να υπάρχει στην σελίδα?

**Comment by defilerc** [comment]
Μπορείτε να βρείτε διαθέσιμα code samples εδώ: https://github.com/VivaPayments/API

Συγκεκριμένα, μπορείτε να ξεκινήσετε με το φάκελο CreateOrder: https://github.com/VivaPayments/API/tree/master/CreateOrder που περιέχει examples, ανάλογα με τη γλώσσα που χρησιμοποιείτε.

Με εκτίμηση,

**Comment by panosgtx** [comment]
Θα ήθελα να ρωτήσω μερικά πράγματα ακόμα.
1. Ποιά θα ήταν η βέλτιστη κατά τη γνώμη σας υλοποίηση για wordpress σελίδα? 
2. Βλέπω τα samples αλλά δεν βλέπω κάτι έτοιμο για wordpress. Υπάρχει κάτι τέτοιο? Δεδομένου ότι έχετε φτιάξει το plugin θα έπρεπε να έχετε έτοιμη την υλοποίηση. 
3. Βλέπω στα πεδία τα πεδία merchant id και api key. Τα έχω αυτά. Αυτό που δεν έχω είναι το initial transaction id. Αυτό που θα το βρω? Είναι ένα από τα δύο ορίσματα t και s?

**Comment by defilerc** [comment]
Καλησπέρα @panosgtx ,

Αν θέλετε να χρησιμοποιήσετε κάποιο εξωτερικό plugin για wordpress, θα πρέπει να απευθυνθείτε στους developers του plugin, καθώς αυτή τη στιγμή δεν παρέχεται κάποιο επίσημο plugin από τη Viva.

Το transaction id στην περίπτωση της Redirect Checkout, προκύπτει αφού δημιουργήσετε έναν κωδικό πληρωμής σύμφωνα με όσα περιγράφονται εδώ: https://github.com/VivaPayments/API/wiki/CreateOrder και στη συνέχεια ανακατευθύνετε το χρήστη στη Viva, θα πραγματοποιηθεί η χρέωση και θα δημιουργηθεί ένα μοναδικό transaction id από τη Viva. 

Στη συνέχεια, στο URL που θα ανακατευθύνει η Viva τον πελάτη στο site σας, θα παρέχεται στην παράμετρο `t` το μοναδικό αυτό transaction id και στην παράμετρο `s` το OrderCode που δημιουργήσατε κατά το προηγούμενο βήμα.

Με εκτίμηση,
