### ISSUE TITLE
Simple checkout additional fields?

### ISSUE THREAD

**Issue by Add1ctiv3** [VivaPayments/API#2090]
Hello, I was wondering whether you can add additional fields you wish to be posted to the backed as a parameter to the simple checkout button. 

I need to include a csrf token and 2 more fields. I tried using data-vp-testAttr="testAttribute" in case i get lucky but it didnt work.

Thanks in advance

**Comment by matthewrgourd** [comment]
Hi @Add1ctiv3, I'm afraid the fields are restricted to what you see on the [documentation page](https://developer.vivawallet.com/online-checkouts/simple-checkout/). Hope this helps.
