### ISSUE TITLE
vivawallet no longer accepts payments

### ISSUE THREAD

**Issue by Gianluca93m** [VivaPayments/API#2091]
Hello as already described in the title vivawallet has stopped working, after talking with against vivawallet I was invited to download and install the new vivawallet for woocommerce plugin, but even so it continues not to accept payments, the technical support explained to me that to them the plugin is not installed otherwise from their management system they saw the link which does not happen, after several attempts they told me to contact here because the problem lies in the plugin.

the domain of the site is https://www.primeroroma.it/cbd-online before the site was on primeroroma.it I made a new site on a sub-folder with a new wordpress installation

**Comment by matthewrgourd** [comment]
Hi @Gianluca93m, I've checked your recent transactions and you have had a card rejected a number of times for the payment of €16 but there's nothing wrong with our plugin. I just checked and it is working fine. Please try with another card. Thanks.
