### ISSUE TITLE
cannot post /checkout - Angular & simple checkout using viva wallet

### ISSUE THREAD

**Issue by georgeat** [VivaPayments/API#2094]
-  I am using angular and simple checkout using the instructions found here https://developer.vivawallet.com/online-checkouts/simple-checkout/

- my button works and the payment is processed. however when is time to post and return the vivaWalletToken  it says cannot post /checkout

- is there something i am missing? 

- has anyone managed to implement vivapayments using angular?

**Comment by georgeat** [comment]
and trying to get the second method (redirect checkout to work),
 i get the following errors:

Access to XMLHttpRequest at 'https://demo.vivapayments.com/api/orders' from origin 'http://www.iqbookingcy.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

zone-evergreen.js:2845 POST https://demo.vivapayments.com/api/orders net::ERR_FAILED

**Comment by matthewrgourd** [comment]
Hi @georgeat, I've checked your demo account, and the Simple Checkout API wasn't enabled. I've done that for you now. Also, I notice you've set up a source (9954) for www.iqbookingcy.com but it has the wrong integration type selected. Please go into the payment source and change to _Integration method_ **Native/Pay with Viva Wallet Checkout** as shown below. Let me know how you get on. Thanks!
![simple-checkout-payment-source](https://user-images.githubusercontent.com/44943019/104426878-73141880-557a-11eb-9dc6-179c8bed7623.png)

**Comment by georgeat** [comment]
Thank you but now it gives me the following error when validating through 3d secure

[cid:221aa755-6e2f-46c8-8386-3112475fbb75]
________________________________

**Comment by georgeat** [comment]
you  can discard the previous email.

I have un it from the actual website (iqbookingcy.com) and not the localhost and  it works now.

Thank you very much
________________________________

**Comment by georgeat** [comment]
I am really sorry to spam  with all these questions...
This is the first time I'm implementing  payments online as a programmer and I'm both excited and overwhelmed.

Is there a way to remove the 3D secure  because it does not seem to work and freezes when I enter the value correct and then press enter.
________________________________

**Comment by matthewrgourd** [comment]
Hi @georgeat, in the demo environment, if you use card number 5188340000000011 it will mimic a frictionless transaction (without 3DS popup). Hope this helps!

**Comment by georgeat** [comment]
it did help.
excellent thank you very much.
hopefully on the live version we won't have that issue.
________________________________

**Comment by matthewrgourd** [comment]
Hi @georgeat, good to hear. Regarding the live version, the individual card issuers provide the 3DS rather than our test 3DS provider. It is 100% operational and has no issues.
