### ISSUE TITLE
Access to Simple Checkout API for demo / dev purposes

### ISSUE THREAD

**Issue by andyhot** [VivaPayments/API#2095]
Hi there,
we've integrated the Simple Checkout process (https://developer.vivawallet.com/online-checkouts/simple-checkout/) in our product and we're now at the point where we call the transactions API `https://demo.vivapayments.com/api/transactions` and receive
```The specified api action is disabled for the merchant f76a063a-2423-4bcb-a856-9040439e2e42, please consult the documentation```

Would it be possible to enable the API for Merchant Id: `f76a063a-2423-4bcb-a856-9040439e2e42`

**Comment by matthewrgourd** [comment]
Hi @andyhot, I've enabled Simple Checkout for you in the demo environment. Best wishes.
