### ISSUE TITLE
nativecheckout/v2/transactions 403 encoding 

### ISSUE THREAD

**Issue by braesident** [VivaPayments/API#2097]
If we get a 403 response is the data of these wrong encoded. It's non-readable. Only with try/catch we can see in the trace message, it is 403 .
At the moment we are observed it on demo-api.vivapayments.com

Problem: this breaks our Httpful Request because of an 'Unable to parse response as JSON: Control character error, possibly incorrectly encoded'

And secondly, why is 90% of responses 403 ?

tested card: Mastercard | 5511070000000020 | cvc: 123 | month 12 | year 2022

**Payload:**
```json
{"amount":4369,"tipAmount":0,"preauth":false,"chargeToken":"ctok_4MgYN6hQJcxpTnyQaKoO9UA9Jnk","sourceCode":"5398","installments":1,"merchantTrns":"Bestellung von Kurt Shopper","customerTrns":"Ihre Bestellung bei ","currencyCode":"978","customer":{"email":"kurt.shopper@fake.mail","phone":"0123456789","fullname":"Kurt Shopper","requestLang":"de","countryCode":"DE"}}
```
**Header:**
```php
[
    'Authorization' => 'Bearer ' . $accessToken,
    'Accept' => 'application/json',
    'ContentType' => 'application/json'
]
```

**Comment by matthewrgourd** [comment]
Hi @braesident, sorry to hear this, we have had some issues with our test card. Please try with 5188340000000011 or any of the other recently updated [test cards](https://developer.vivawallet.com/getting-started/#test-cards) instead. Let me know if this makes a difference.

**Comment by braesident** [comment]
Hey @matthewrgourd, unfortunately these cards give out a 2061 error. I'll solve that first with this [comment](https://github.com/VivaPayments/API/issues/2078#issuecomment-757325564)

a 403 can still happen, but then the body must not consist of binary data. this kills every json encode

**Comment by matthewrgourd** [comment]
Hi @braesident, thanks. Apologies, there is a general issue with our test cards at the moment that's being looked into by our third party 3DS provider, Modirum. I checked card number 4006090000000007 posted via that [comment](https://github.com/VivaPayments/API/issues/2078#issuecomment-757325564) you mentioned and it seems to give a success outcome correctly. Can you let me know if you experience the same? Thanks

**Comment by matthewrgourd** [comment]
Hi @braesident, the test card 5188340000000011 should be correctly triggering a simulated 3DS popup now. There were issues with our third party provider, Modirum, which have now been fixed. Please close this issue if resolved.
