### ISSUE TITLE
Enabling simple checkout in demo environment 

### ISSUE THREAD

**Issue by kleido** [VivaPayments/API#2098]
^ {#2338 ▼
  +"Emv": null
  +"Amount": null
  +"StatusId": "E"
  +"RedirectUrl": null
  +"CurrencyCode": null
  +"TransactionId": null
  +"ReferenceNumber": null
  +"AuthorizationId": null
  +"RetrievalReferenceNumber": null
  +"Loyalty": null
  +"ThreeDSecureStatusId": null
  +"ErrorCode": 403
  +"ErrorText": "The specified api action is disabled for the merchant b654f213-1d32-4f94-80c1-b98dfecadeea, please consult the documentation"
  +"TimeStamp": "2021-01-14T16:19:25.8771943+02:00"
  +"CorrelationId": null
  +"EventId": 0
  +"Success": false
}

Hello, 
could you please enable simple checkout for this merchant  id: b654f213-1d32-4f94-80c1-b98dfecadeea
thanks in advance

**Comment by matthewrgourd** [comment]
Hi @kleido, that's enabled for you now. Best wishes.

**Comment by kleido** [comment]
Hello @matthewrgourd, 
Sorry to bother you again.

It worked in the case where the an order is created with preauth = false. If i set preauth = true. I can create
a transaction for the authorization of the payment, but when i try to capture i get the same error message

The merchant id is the same: b654f213-1d32-4f94-80c1-b98dfecadeea

Can you please enable this action also?

Also Is there a way to enable these actions from the demo account or do they have to be enabled manually by you?

Thanks for your time

**Comment by matthewrgourd** [comment]
Hi @kleido, can I see a log of the exact request you're making that gives the error message relating to the capture? There shouldn't to be anything else needing to be enabled at this end.

**Comment by kleido** [comment]
The request is a POST to https://demo.vivapayments.com/api/transactions/317c1226-1740-4540-b0e3-c3f64cd22d20
with params amount `amount : 750`

response 
^ {#2332 ▼
  +"Emv": null
  +"Amount": null
  +"StatusId": "E"
  +"RedirectUrl": null
  +"CurrencyCode": null
  +"TransactionId": null
  +"ReferenceNumber": null
  +"AuthorizationId": null
  +"RetrievalReferenceNumber": null
  +"Loyalty": null
  +"ThreeDSecureStatusId": null
  +"ErrorCode": 403
  +"ErrorText": "The specified api action is disabled for the merchant b654f213-1d32-4f94-80c1-b98dfecadeea, please consult the documentation"
  +"TimeStamp": "2021-01-14T18:15:48.163432+02:00"
  +"CorrelationId": null
  +"EventId": 0
  +"Success": false
}

**Comment by matthewrgourd** [comment]
Hi @kleido I'm not sure why you're still receiving that error. It makes no sense as I just enabled the Simple Checkout API on demo for you. Have you looked at our [Simple Checkout instructions](https://developer.vivawallet.com/online-checkouts/simple-checkout/) in detail? FYI, nothing else needs to be 'switched on' at this end.
