### ISSUE TITLE
Access To Simple Checkout API

### ISSUE THREAD

**Issue by ddroggitis** [VivaPayments/API#2099]
Hello!   I'd like to test your simple checkout API.
Thank you,
Dionysis Droggitis

**Comment by matthewrgourd** [comment]
Hi @ddroggitis, cool, can I have your demo Merchant ID so I can enable for you?

**Comment by ddroggitis** [comment]
Helo again! The demo id is 425101332328 . 
Thank You!

**Comment by matthewrgourd** [comment]
Hi @ddroggitis, our Simple Checkout API is now enabled for your demo account. Thanks!
