### ISSUE TITLE
Reccuring + MaxInstallments

### ISSUE THREAD

**Issue by zstergios** [VivaPayments/API#210]
Καλησπέρα,
 βλέπω οτι γινεται να υπάρχουν ταυτόχρονα και τα 2
https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction

Άπλα δεν ξέρω πως λειτουργεί πρακτικά. 
Ο έμπορος λαμβάνει στην αρχική πληρωμή την 1η δόση από 3 μέχρι να εξοφληθεί τελείως 3μηνες
Όταν είναι recurring, θα γινεται η χρέωση ξανά πχ 2ο μηνά και θα εξοφληθεί σε 4μήνες

Σωστά;

Επίσης θεωρώ θα ήταν πολύ χρήσιμο η αυτόματη χρέωση στο recurring μια παράμετρος με N Days, με δυνατότητα να γίνει cancel η να τροποποιηθεί.

Φυσικά να υπάρχει και notify URL παράμετρος να στέλνει εκεί το callback για ειδοποίηση στο website

Amount=100&Installments=3&charge_every_days=15&callback=URLENCODE(https://my-URL.php)

**Comment by dmihos** [comment]
Καλημέρα

Η recurring πληρωμή είναι η εκτέλεση μιας one-off συναλλαγής, που δεν απαιτεί στοιχεία κάρτας (αλλά βασίζεται στα στοιχεία μιας προηγούμενης). 
Ως εκ τούτου, μια συναλλαγή με δόσεις δε διαφέρει σε τίποτα από μια recurrent συναλλαγή με δόσεις.
Το ποσό, και στις 2 περιπτώσεις, δεσμεύεται στο ακέραιο από την κάρτα του πελάτη και αποδίδεται μηνιαίως στον έμπορο.

Για τη συστημική ενημέρωσή σας σχετικά με την εκτέλεση συναλλαγών, μπορείτε να δείτε πληροφορίες στο section σχετικά με τα [webhooks](https://github.com/VivaPayments/API/wiki/Webhooks)

Ευχαριστούμε για την επικοινωνία
