### ISSUE TITLE
WP WC Plugin Payment refused

### ISSUE THREAD

**Issue by ponc83** [VivaPayments/API#2100]
Hi, with my sales manager i configured the plugin following instructions here
https://docs.woocommerce.com/document/viva-wallet-for-woocommerce/#

All went good and it said

Viva Wallet: Your LIVE credentials are valid.
Viva Wallet: Your LIVE source code: XXXX is verified and you are ready to accept payments.

But when i go to try to close an order i always get

There was a problem with your card. Please check the card details and try again.

This happens both with test cards (Visa/Mastercard) and with real CC. 
To be clear, in WC all seems to be good, it creates the selling channel in VivaWallet and recognize it in the plugin advanced settings, so i don't understand what could be the problem.

Thanks in advice

![WhatsApp Image 2021-01-15 at 13 45 24](https://user-images.githubusercontent.com/29686284/104728991-0d6d8b00-5738-11eb-897b-335a807cfe37.jpeg)
![WhatsApp Image 2021-01-15 at 12 47 18](https://user-images.githubusercontent.com/29686284/104729017-16f6f300-5738-11eb-8111-d1655cbfc940.jpeg)

**Comment by matthewrgourd** [comment]
Hi @ponc83, we've had a quick check and can't immediately see any issue. All your settings look fine and your checkout is calling the API correctly. Could we have a bit more info. in the form of logs? These are available as follows:

Instructions below:

1. Go to **WooCommerce > Status > Logs** tab:

![log1](https://user-images.githubusercontent.com/44943019/99075879-2039d700-25b2-11eb-806d-f45cc6441d68.png)

2. Select relevant date from the dropdown. We suggest you send through the one with today's date (note that the below is just an example).

![log2](https://user-images.githubusercontent.com/44943019/99075893-262fb800-25b2-11eb-844d-bbf073524f3f.png)

3. Click on the **View** button.

4. Copy the contents into a text file and save it with an appropriate name. 

5. Attach to this issue in .txt format.

Thanks!

**Comment by ponc83** [comment]
[log.txt](https://github.com/VivaPayments/API/files/5820874/log.txt)

Here you are

**Comment by ponc83** [comment]
Hi, we solved the issue with the help of our vivawallet sales manager Alberto. Thanks also to you for your precious support.

**Comment by matthewrgourd** [comment]
Hi @ponc83, ok, that's great. Any idea what the problem was? We were a bit confused at this end!

**Comment by athigb** [comment]
Hi 
I have exactly the same problem. Can i attach my logfile to this issue?

**Comment by matthewrgourd** [comment]
Hi @athigb, please explain in detail the issue you're experiencing in case there are any differences. I will then decide whether we need you to provide a log file. Thanks!

**Comment by matthewrgourd** [comment]
Hi @athigb, if you're still experiencing issues, please create a new issue with full details via our [GitHub issues home page](https://github.com/VivaPayments/API/issues).
