### ISSUE TITLE
Shopify for vivawallet: error. Could not create ordre. Generic Error

### ISSUE THREAD

**Issue by Cbdate** [VivaPayments/API#2102]
Hello,

I am having an issue with Shopify checkout with Viva Wallet.
I am sure that I have used the right Merchant ID and Store Token, but when I try to checkout using Viva Wallet, I get this error message :

Error.
Could not create order. Generic Error.

I see that this issue has already been discussed here in the past. Can someone help me please ?

Thank you

Antonio
![WhatsApp Image 2021-01-16 at 15 30 47](https://user-images.githubusercontent.com/77614022/104899239-e4890800-597a-11eb-8876-3285eec2ff4a.jpeg)

**Comment by matthewrgourd** [comment]
Hi @Cbdate, sorry to hear that. Please may I have your Shopify store URL and Viva Wallet merchant ID so I can check your account. Thanks.

**Comment by Cbdate** [comment]
Hi @matthewrgourd , thanks for the support, this is my website: www.cbdate.it and this is my ID. 544127527647

**Comment by matthewrgourd** [comment]
Hi @cbdate, we recently changed our processes so you can generate your own Shopify token from within the Viva Wallet banking app. Can you try to replace the current token in your Shopify settings for the Viva Wallet payment plugin with one created as follows:

1. Log in to the [Viva Wallet banking app](https://app.vivawallet.com/).

2. Click on **Settings > API Access** and scroll down to the **Shopify Credentials** section:<br /><br />
![Shopify credentials](https://developer.vivawallet.com/images/shopify-credentials.png?classes=border)
3. Click on the **Get client secret** button.<br />A popup is displayed:<br /><br />
![Shopify credentials popup](https://developer.vivawallet.com/images/shopify-credentials-popup.png?classes=border)
4. Complete the two fields. Note that **Store URL** should end `.myshopify.com`.
5. Click on the **Create** button.<br />Your unique Shopify token is now displayed in the **Client secret** field below **Client ID**:<br /><br />
![Shopify token created](https://developer.vivawallet.com/images/shopify-token-created.png?classes=border)

**Comment by Cbdate** [comment]
@matthewrgourd I have successfully connected the token and reset the checkout several times, I have tried even now but the problem continues

**Comment by matthewrgourd** [comment]
Hi @Cbdate, sorry to hear this. A couple of things to note. Test mode should be **switched off** in your Shopify settings. Merchant ID, below, should be the same as Client ID:

![image](https://user-images.githubusercontent.com/44943019/104914287-d345f880-5986-11eb-8f70-8a609d4b8748.png)

Can you confirm all of that?

**Comment by Cbdate** [comment]
@matthewrgourd yes sure

**Comment by matthewrgourd** [comment]
Ok, I will need to check with our plugin developer and get back to you. Apologies for any inconvenience caused.

**Comment by Cbdate** [comment]
@matthewrgourd How quickly can you solve the problem?

**Comment by matthewrgourd** [comment]
@Cbdate, not sure yet. One other thing to check, have you got your Shopify currency set to Euros to match your Viva Wallet account currency?

**Comment by Cbdate** [comment]
@matthewrgourd yes I confirm the euro corrency

**Comment by matthewrgourd** [comment]
Hi @Cbdate, our dev team discovered that you had changed your API key and unfortunately this affects any Shopify integrations taking place. This is fixed now. Please retest. Thanks.

**Comment by Cbdate** [comment]
@matthewrgourd Yes it's ok i have checked thank you very much for the support
