### ISSUE TITLE
API to read incoming deposits made using Payment Codes

### ISSUE THREAD

**Issue by stefpantmc** [VivaPayments/API#2103]
Hello, 

I'm searching for an API to read my account's deposits, the ones shown on dashboard on my account as "Your account was credited via Payment Code <payment_code>" and showing the amount next to this(like it shows in the attached image). 

I have tried using the payment API to read all transactions(https://www.vivapayments.com/api/transactions/) using date/clearancedate/ordercode parameters but I didn't get back any transfer or deposit transaction! Also I tried to get any order from (https://www.vivapayments.com/api/orders/<order_code>) using as order code my payment code just in case that could return any deposit information but as expected it , I got an answer that nothing found with that code!

So my question is if there exists another API that I can read all incoming deposits of my account, or if it doesn't yet exists if you could create an API like the one reading all transactions of a specific date?
Furthermore, I would like to know if exists an API to create a Payment Code giving the <amount> to send to customers to make a deposit.

Thanks in advance,
Stefanos
![vivacapt](https://user-images.githubusercontent.com/62287117/104908164-b9a8af00-598e-11eb-804c-b8c33df42fbf.JPG)

**Comment by matthewrgourd** [comment]
Hi @stefpantmc, so I can check, could you email me your Viva Wallet Merchant ID and company name, quoting this issue? (#2103)

**Comment by stefpantmc** [comment]
Hello @matthewrgourd  could you share me your email to send you the requested informations, even if I believe my question(how to get account deposits from API) is more generic and my account's details won't help to answer that question!

**Comment by matthewrgourd** [comment]
mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
Hi @stefpantmc, thanks for sending through your account details. I can see that Viva Spot deposits are displayed in your wallet only. This has a separate API. You should try the [Retrieve wallet info](https://developer.vivawallet.com/web-api-integration/account-api/#retrieve-wallet-info) API call, example in cURL below:
```
curl -L -X GET 'https://demo.vivapayments.com/api/wallets' \
-H 'Content-Type: application/json' \
-H 'Authorization: Basic OTZjYjVhMDctNDhjZS00ZDgxLTg3NmQtYTZjM2RmOGRiZDE2OkFEMmUqKA=='
```
Please note that the authorization code should be your [Merchant ID and API Key](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) in Base64.

**Comment by stefpantmc** [comment]
Hello @matthewrgourd, thanks for your reply, I just called that API and saw it's returning only the basic information about my wallet. Also I checked more the Account API and find the next of the one you sent me must be the API I wanted, more specifically the POST request  '/walletaccounts/v1/wallets/{walletId}/transactions:search' but I couldn't get an answer from that API using my walletId as it says in documentation that "This API call is not intended for general merchant use. Access is given only if you’re working as a partner of Viva Wallet." 

So do you know how I can use that API, because it must have a different authorization without explaining it in the documentation(it only says for authorization "Role: Client merchant reseller."), or if I can't how to become a partner of Viva Wallet?

**Comment by matthewrgourd** [comment]
Hi @stefpantmc, I'm currently checking the `POST request '/walletaccounts/v1/wallets/{walletId}/transactions:search` and speaking to our Core team about how it can be accessed. I'll update you when I have the answer. Thanks.

**Comment by stefpantmc** [comment]
Hello @matthewrgourd , thanks for your reply. I'll be waiting for your update! Also, I believe that information should be accessible from all viva wallet accounts, because everyone needs himself to manage his wallet transactions!
