### ISSUE TITLE
Improve documentation on ThreeDSecureStatusId

### ISSUE THREAD

**Issue by andyhot** [VivaPayments/API#2104]
Is it possible to add some documentation regarding the `ThreeDSecureStatusId` key that we get in the response of ```POST /api/transactions``` ( we post there the PaymentToken we get from a simple checkout) ?

It'd be great if we could have a list of values and their meaning, something like the eci values described at https://support.midtrans.com/hc/en-us/articles/204161150-What-is-ECI-on-3DS-protocol-

**Comment by matthewrgourd** [comment]
Hi @andyhot, thanks for the tip, will look into that.

**Comment by andyhot** [comment]
So, from what i've seen, a value of 1 most probably means `Fully authenticated` and a value of 2 probably `Not authenticated`.

Other systems (modirum) provide some more values (`Not enrolled` and `Attempt`) but i'm not sure if those somehow map to `ThreeDSecureStatusId`

**Comment by matthewrgourd** [comment]
Hi @andyhot, looking at this again, in fact we do have two possible x-viva-eventId values relating to 3DS failures as described under [Rejection reasons](https://developer.vivawallet.com/web-api-integration/error-codes/#rejection-reasons) on our developer portal:

x-viva-eventId | Reason | Explanation | Type
-- | -- | -- | --
2061 | 3DS flow incomplete | Browser closed before authentication finished. | User
2062 | 3DS validation failed | Wrong password or two-factor auth code entered. | User

However, I have raised with our development team in case they have any further comments.
