### ISSUE TITLE
Access to simple checkout API

### ISSUE THREAD

**Issue by D1ceS5** [VivaPayments/API#2105]
Access needed please

**Comment by matthewrgourd** [comment]
Hi @D1ceS5, no problem, could I have your Merchant ID, please? If it's for the production environment, please send this to me by email quoting this issue (#2105).

**Comment by D1ceS5** [comment]
Sorry, but which email do you mean, I'm a little confused

**Comment by matthewrgourd** [comment]
@D1ceS5, sorry, here you go: mgourd@vivawallet.com

**Comment by matthewrgourd** [comment]
Replied by email
