### ISSUE TITLE
Viva Payments via NFC

### ISSUE THREAD

**Issue by ozizo41** [VivaPayments/API#2106]
Hello,
Is there any documentation on how to implements Viva Payments via NFC in an Android app or anything similar?

**Comment by matthewrgourd** [comment]
@ozizo41, what exactly are you trying to do? We have a card terminal app for Android and it is documented here: https://developer.vivawallet.com/pos-api-integration/pos-terminal-apps/android/. Whatever is mentioned there is the extent of what is possible currently. Hope this helps...

**Comment by ozizo41** [comment]
Okay it works for NFC payment too. Thank you!
