### ISSUE TITLE
VivaPayments - WooCommerce - Delivery Options

### ISSUE THREAD

**Issue by latinario** [VivaPayments/API#2107]
Good day,

I have a question regarding the VivaPayments plugin for WooCommerce. I am currently using the plugin in order to sell tickets for my event, however it is asking for delivery options (including shipping address etc.). The e-tickets should be sent on an email and it is not needed to be sent to a physical address.

I will also like to sell some merchandise for my event (like t-shirts etc.) and physical address might be needed.

Is there any setting that I could use in order to choose where Delivery on Physical Address is mandatory or not?

Kind regards,
Pantelis K.
Latinario Events

**Comment by matthewrgourd** [comment]
Hi @latinario, these options are set in WooCommerce. Please refer to their [setup products](https://docs.woocommerce.com/documentation/plugins/woocommerce/getting-started/setup-products/) page or support team for help. Regarding our plugin, for non-physical stock, ensure that our
