### ISSUE TITLE
paymentTimeOut doesn't work in Android integration

### ISSUE THREAD

**Issue by ozizo41** [VivaPayments/API#2108]
I'm developing an Android app that integrate Viva Payments.
In the past I asked a question related to this topic ( #1941 ) and read the documentation in https://developer.vivawallet.com/web-api-integration/payment-api/#tag/Payments and the request is sent in JSON format (not my case).
I tried to add a timeout after 10 seconds on my Android app using the following code:
```
String deeplinkPath = "vivapayclient://pay/v1"
                    + "?merchantKey=" + myMerchantKey
                    + "&appId=com.example.myapp"
                    + "&action=sale"
                    + "&clientTransactionId=1234567801234"
                    + "&amount=" + amountL
                    + "&tipAmount=" + tipL
                    + "&withInstallments=" + installments
                    + "&preferredInstallments=" + prefInstallments
                    + "&callback=" + callback
                    + "&paymentTimeOut=" + 10;

final Intent payIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(deeplinkPath));
payIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
payIntent.addFlags(Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS);
payIntent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
startActivity(payIntent);
```
But unfortunately, the timeout happens after 1 minute like nothing was added.
Is the syntax wrong, or anything else should be added? What can I do?

Thank you for your help.

**Comment by matthewrgourd** [comment]
Hi @ozizo41, our Interapp API is a totally different API from VivaPayments API (e-commerce). Please see the relevant documentation page below. You will see that currently we do not support a timeout parameter in sale action:
https://developer.vivawallet.com/pos-api-integration/pos-terminal-apps/android/ Hope this helps!

**Comment by ozizo41** [comment]
So there's no way to set programmatically the timeout to be less than 1 minute by using any other method for example? I really need it!

**Comment by matthewrgourd** [comment]
I'm afraid not. Sorry.
