### ISSUE TITLE
Πρόβλημα με πληρωμές

### ISSUE THREAD

**Issue by pRieStaKos** [VivaPayments/API#211]
Καλησπέρα,

Έχω ένα WHMCS module για πληρωμές μέσω Viva (VivaPayments Pro - https://www.arip.net/cart.php?gid=3). Όλα έπαιζαν καλώς μέχρι εδώ και 1 μήνα.

- Οι ρυθμίσεις είναι όπως έχουν από την πρώτη μέσα εγκατάστασης του module. 
- Το module δεν εμφανίζει error logs.
- Στο test account όλα παίζουν κανονικά, αλλά με το merchant account, ο πελάτης κάνει την πληρωμή, το wallet βλέπει κανονικά την πώληση και την πληρωμή, αλλά δεν μου επιστρέφει το transaction id για να χαρακτηριστεί το invoice ως πληρωμένο.

Επικοινώνησα με την εταιρεία του module και μου είπε "_Πραγματοποιήσαμε ελέγχους τόσο στην κανονική όσο και στην πειραματική κονσόλα της Viva Payments χωρίς πρόβλημα._".

Μπορείτε να το δείτε ή να προτείνετε κάτι για την επίλυση ?

**Comment by dmihos** [comment]
Καλημέρα

Εφόσον CreateOrder και συναλλαγή εκτελούνται επιτυχώς, το πρόβλημα φαίνεται να βρίσκεται στις δηλωμένες πηγές του εμπορικού λογαριασμού.
Θα χρειαστούμε το merchantId (όχι το api key) του εμπόρου για διερεύνηση.

**Comment by skkostas** [comment]
Καλημέρα σας, 

Merchant ID: 8998c675-3218-426e-be17-0972e62da918

πρόβλημα από πλευρά Viva εννοείται η στο setup του module μας

**Comment by dmihos** [comment]
Οι συναλλαγές εκτελούνται με την πηγή Default, ενώ τα urls του site είναι δηλωμένα σε άλλη πηγή. 
Το module, λογικά, κάπου δίνει τη δυνατότητα να δηλώσετε την πηγή που θα χρησιμοποιεί. 
Οπότε. εκεί θα πρέπει να δηλωθεί η σωστή πηγή

Ευχαριστούμε για την επικοινωνία

**Comment by skkostas** [comment]
:O είναι το μόνο που δεν είχα προσέξει και εμείς ευχαριστούμε για την άμεση απάντηση..

**Comment by themis1970** [comment]
?????????????????????????????????????????????????????????????

www.koronis.com.gr
www.χονδρικη.gr
<http://www.%CF%87%CE%BF%CE%BD%CE%B4%CF%81%CE%B9%CE%BA%CE%B7.gr>
www.xondriki.eu
www.tzamia-tapetsaries.gr

email: koronis1970@gmail.com

ΕΜΠΟΡΙΟ ΕΙΣΑΓΩΓΗ ΚΑΤΑΣΚΕΥΗ
ΞΥΛΟΥ-ΑΛΟΥΜΙΝΙΟΥ.

ΘΕΜΙΣΤΟΚΛΗΣ ΚΟΡΩΝΗΣ
ΤΗΛ.-FAX 22210 22243
MOBILE: 6972699533
TK.34100
ΒΑΛΣΑΜΑ 4
ΧΑΛΚΙΔΑ

****************************************************************
Προσοχή ! Σύμφωνα με το άρθρο 14 του Νόμου 2672/1998 (ΦΕΚ 290 τ.Α)
τα μηνύματα e-mail, για να είναι έγκυρα θα πρέπει να περιέχουν απαραίτητα :
Ονοματεπώνυμο ή επωνυμία (για Νομικό πρόσωπο), ταχυδρομική διεύθυνση
κατοικίας, αριθμό τηλεφώνου ή fax, ιδιότητα του χειριστή.
Αν τα μηνύματα προέρχονται απο υπηρεσία ή Δημόσιο φορέα να περιέχουν
επιπλέον θέμα, ημερομηνία, αριθμό πρωτοκόλλου.
Το μήνυμα ηλεκτρονικού ταχυδρομείου τεκμαίρεται οτι έχει περιέλθει κανονικά
στον λήπτη αν υπάρξει ηλεκτρονική επιβεβαίωση.
 Οι πληροφορίες ή και τυχόν αρχεία που υπάρχουν σε αυτό το ηλεκτρονικό
μήνυμα είναι προσωπικά και απόρρητα
****************************************************************

2016-12-09 14:14 GMT+02:00 skkostas <notifications@github.com>:
