### ISSUE TITLE
Native checkout V2 Status 400, message null options

### ISSUE THREAD

**Issue by tmblog** [VivaPayments/API#2110]
Hi, I have been trying to integrate native v2 checkout using all the steps described here:
https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

I create the access token then create a charge token but when it comes to making the actual charge no matter which card I use from a few from your site (5188340000000011) including one mentioned in https://github.com/VivaPayments/API/issues/1311

I get this response:
`stdClass Object ( [status] => 400 [message] => Null options [eventId] => 0 ) `

I have tried your code from the docs but to no avail.
Any help would be appreciated.

**Comment by matthewrgourd** [comment]
Hi @tmblog, sorry to hear that. Can you let me know if you're using the correct base URL for demo (https://demo-api.vivapayments.com)? Please also share the exact request body parameters you're using for the POST to `/nativecheckout/v2/transactions`. Thanks.

**Comment by tmblog** [comment]
Hi @matthewrgourd, thank you for the reply.
The endpoint is:
`https://demo-api.vivapayments.com/nativecheckout/v2/transactions`
And demo-api for all client side calls.
And here's the POST parameters (all variables are set):

```
$postArgs = array(
        'amount' => 100,
        'chargeToken' => $token,
        'installments' => 1,
        'preauth' => false,
        'sourceCode' => "9733",
        'merchantTrns' => "MERC TRNS",
        'customerTrns' => "CX TRNS",
        'currencyCode' => 826,
        'customer' => array(
            'email' => $cxEmail,
            'phone' => $cxPhone,
            'fullname' => $cxName,
            'requestLang' => 'en',
            'countryCode' => 'GB'
        )
```
Thanks

**Comment by matthewrgourd** [comment]
Hi @tmblog, I believe `chargeToken` value should be in quotes (" "). In Postman, if I remove the quotes, I get the same error as you.

**Comment by tmblog** [comment]
Hi @matthewrgourd, thanks for the reply I put quotes around the charge token variable like `'chargeToken' => "$token",` but I still get 
```
stdClass Object
(
    [status] => 400
    [message] => Null options
    [eventId] => 0
)
```
This was the token `"ctok_TlsOIHGZzHP5xt9Q16GKTj2A230"`
Any other ways to try?

**Comment by matthewrgourd** [comment]
Hi @tmblog, I'm sorry, but I don't immediately know the answer. Will speak to our development team and get back to you.

**Comment by matthewrgourd** [comment]
@tmblog, in the meantime, I suggest you test in Postman, which will prove that our API works. The question you're asking is a coding question not a technical support question.

**Comment by matthewrgourd** [comment]
Hi @tmblog, I've spoken with a member of our dev team who advises of the following:

>Can you var_dump the headers args and body args when you're making the call (log it somehow) and send the values to us in order to check them. Your body parameters seem ok (the part of the code that you're sharing) so it might be something else. Are you using the bearer token correctly in your headers? Finally, can you check it in Postman? If you're getting an error there, we can check the correlation id, and get logs.

Hope this helps!

**Comment by tmblog** [comment]
Hi @matthewrgourd, thank you for your perseverance, I will send the requested info from my scripts, meanwhile here's a response from a postman request:
```
{
    "status": 400,
    "message": "PaymentsCardHolderAuthenticationInvalidStatus",
    "eventId": "2061"
}
```
Just in addition, my payment source is from a subdomain, and I did specify the subdomain, would that make a difference? e.g:
`demo.example.com` and I specified `demo.example.com` in domain name for the source.

**Comment by tmblog** [comment]
Hi here's the entire code I used from a server:

```
$url = 'https://demo-api.vivapayments.com/nativecheckout/v2/transactions';

    $headerArgs = array(
        "Authorization: Bearer 568fca17cd9732ff7a457f8b65848e7e166a368f2c8fc6123a707064802585ab",
        "Content-Type: application/json"
    );

    $postArgs = array(
        'amount' => 100,
        'chargeToken' => "ctok_3U8lsPaB-IFKLRQRbyGsD8KR6DI",
        'installments' => 1,
        'preauth' => false,
        'sourceCode' => "9733",
        'merchantTrns' => "MERC TRNS",
        'customerTrns' => "CX TRNS",
        'currencyCode' => 826,
        'customer' => array(
			  "email"=> "native@vivawallet.com",
			  "phone"=> "442037347770",
			  "fullname"=> "John Smith",
			  "requestLang"=> "en",
			  "countryCode"=> "GB"
        )
    );

    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($curl, CURLOPT_ENCODING, "");
    curl_setopt($curl, CURLOPT_MAXREDIRS, 10);
    curl_setopt($curl, CURLOPT_TIMEOUT, 0);
    curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);
    curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
    curl_setopt($curl, CURLOPT_POSTFIELDS, $postArgs);
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headerArgs);

    $result = curl_exec($curl);
    curl_close($curl);

    $result = json_decode($result);
    print_r($result);
```
Results in:
`stdClass Object ( [status] => 400 [message] => Null options [eventId] => 0 ) `
Not sure what it is I can see the response is different in postman, I have no doubt your system works as you mentioned before, just not sure what I am doing wrong.
Cheers!

**Comment by matthewrgourd** [comment]
Hi @tmblog, thanks for sharing the above. One of my colleagues has taken a look and come back with the following. Your header arguments should be like this:
```
$headerArgs = array(
    'Authorization' => 'Bearer ' . $access_token,
    'Accept' => 'application/json',
    'Content-Type'  => 'application/json',
);
```
The access token is dynamic. Unfortunately you have it set to static:
```
"Authorization: Bearer 568fca17cd9732ff7a457f8b65848e7e166a368f2c8fc6123a707064802585ab",
```
We think it is not valid php code because of the the 'Authorization' => 'Bearer ' format. This is a string opens when " and finishes at the end at the last ". It is not a value pair. If the structure of data is not as expected, the API call will fail. Hope this helps!

**Comment by tmblog** [comment]
Hi @matthewrgourd, thank you for taking the time to do this. 
I've updated the code to the above and when using the same access token and charge I get `The requested URL returned error: 401 Unauthorized` via php backend, but get a transaction ID with postman. Leads me to think somehow my server is blocked maybe or something similar, can you check? The app ID is 9733.

Also regarding the code which your colleague has said is incorrect it was copied exactly bar the dynamic values from:
`https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-5-make-the-actual-charge`
Click on the php tab of the code. Perhaps someone should update that.
Cheers, hopefully get this sorted soon :-) Thanks for your perseverance.

**Comment by matthewrgourd** [comment]
Hi @tmblog, I'm sorry, we can't really get involved any further with your custom code. The code sample on our developer portal you mention is in fact correct. Everything in caps there is a variable. In your code you also have
```
$url = 'https://demo-api.vivapayments.com/nativecheckout/v2/transactions';
$access_token = "c4a7238738388ec15a300f7e14f853c30fe193aa7c710a7a658752eb38229205";
  
$headerArgs = array(
```
a static value, when in fact the access token needs to be changed every time it expires (you have to push a new value in each call). And charge token the same:
```
'chargeToken' => "ctok_5g8TWO4hOicnk3J7BzUBRAr2fG0",
```
Good luck!

**Comment by tmblog** [comment]
OK fair enough, can check if my server is blocked at your end or if my app is ok to make calls? Because I have a feeling there's something blocking it.

Just a couple of points Matthew, I'm not having a rant just that devs need to be more proactive and I know you are just the messenger in this instance:

> Static value

Well of course they are! If I pasted variables they would have said what's the value of those variables and they asked me to var_dump the body and header (that was the way to do it), it's daft to think that I am using the same static auth token everytime! Quite condescending actually or silly from their part.

> The code sample on our developer portal you mention is in fact correct.

Well they contradict themselves! This what you said earlier from the dev:

>Your header arguments should be like this: 
$headerArgs = array(
    'Authorization' => 'Bearer ' . $access_token,
    'Accept' => 'application/json',
    'Content-Type'  => 'application/json',
);

When in fact the code in your DOCS is this:

```
$headerArgs = array(
    'Authorization' => 'Bearer ' . $access_token,
    'Accept' => 'application/json',
    'Content-Type'  => 'application/json',
);
```
See the difference yourself.
Would appreciate the check of my server if it's blocked or if my source is set up correctly.
I will continue to test knowing the dev support is non-existent for "custom scripts" unlike competitors.
None of this is directed your way @matthewrgourd. Thank you for your help.

**Comment by matthewrgourd** [comment]
Hi @tmblog, I'm sorry if you feel the answers given have not been as helpful as you would like. 

Our devs have asked again if there's a way you can var_dump the body and header?

FYI:

- there shouldn't be any blocking from our end
- you can use a sub-domain no problem.

Could I have your demo Merchant ID so I can check our logs in case that may help us to understand the issue?

**Comment by tmblog** [comment]
Hi Matthew, no need to apologise but thank you.
I will somehow dump those you asked. 
Here's my demo account id: 39011331

Hope fully get to the bottom of it soon.
Thank you for your assistance on this.

**Comment by matthewrgourd** [comment]
Hi @tmblog, looking at your account, I can see that you have had a successful transaction through Native Checkout v2 on 27 Jan for €1. The source name is DemoSuper V2 and the source code is 9733. Can you maybe try to replicate what you did then?

**Comment by tmblog** [comment]
Hi Matthez, thanks for checking that. It was actually from Postman, I will continue to test and see if I can achieve anything.
Thanks

**Comment by tmblog** [comment]
Can you tell me what this means?
`PaymentsCardHolderAuthenticationInvalidStatus`
I was able to get that this time, is it a 3DS challenge fail?

**Comment by matthewrgourd** [comment]
Hi @tmblog, yes, it's a 3DS challenge failure.

**Comment by tmblog** [comment]
Just letting you know @matthewrgourd that using this [wrapper](https://github.com/alekseykuleshov/viva-php) I am now able to successfully create transactions.
I am running into some trouble with 3DS some test cards are not requiring it, whilst one does. The element briefly shows without any prompt, feel free to close this.
Thank you for all your help and support.
