### ISSUE TITLE
Simple Checkout access

### ISSUE THREAD

**Issue by Alex360T-web** [VivaPayments/API#2112]
Hi would like to test simple checkout please.
id account : 1010165128741

Thanks

**Comment by matthewrgourd** [comment]
Hi @Alex360T-web, enabled as requested. Best regards.

**Comment by Alex360T-web** [comment]
Thanks

my test its correct can activate on production with the account 9662878781830

**Comment by matthewrgourd** [comment]
Hi @Alex360T-web, enabled as requested. Have a good day!
