### ISSUE TITLE
Viva Wallet oAuth 2 token request error - PHP

### ISSUE THREAD

**Issue by geesmo** [VivaPayments/API#2115]
Hi, we have created a demo account and we are calling https://demo-accounts.vivapayments.com/connect/token via php curl
to get an access token.

We have generated correctly a client secret for Native Checkout v2 Credentials.

The response we get is {"error":"unsupported_grant_type"}

the grant type we send is as follows:

$arr = array(
'grant_type' => 'client_credentials'
);
$query = json_encode($arr); 

curl_setopt($ch, CURLOPT_POSTFIELDS, $query);

Can you assist us please?

Thank you

**Comment by mavr1982** [comment]
Hi @geesmo 

An example of valid PHP curl call would be:

```
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://demo-accounts.vivapayments.com/connect/token',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS => 'grant_type=client_credentials',
  CURLOPT_HTTPHEADER => array(
    'Authorization: Basic NDI4ZnZ5ZjJkZXRjYjlrN3AxZHhyZWk0Z3I0NGFmMWt2aWNkYXRlanE0ajQ3LmFwcHMudml2YXBheW1lbnRzLmNvbTo5OExVVlNRNTJjWlc3cFpXM25zOEg3dTMyUXE0T1A=',
    'Content-Type: application/x-www-form-urlencoded'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
```
I hope that helps.

**Comment by geesmo** [comment]
Thanks, we have changed the CURLOPT_POSTFIELDS from json το form string parameters as you described and everything works perfect.
