### ISSUE TITLE
Simple Checkout Access

### ISSUE THREAD

**Issue by exefron** [VivaPayments/API#2116]
- Could you provide access to merchant ID 09460cec-5b97-46ef-baa5-b5430a7b3079 for production environment (live).
- Also, mercant ID dee7ae76-96d8-45de-9712-d45cc5563b3c, for testing purposes on other e-commerce platforms, without the supported plugins.

Thanks in advance

**Comment by matthewrgourd** [comment]
Hi @exefron, enabled as requested. Have a good day!
