### ISSUE TITLE
VivaWallet not assigning order status in Prestashop

### ISSUE THREAD

**Issue by DrFostersCBD** [VivaPayments/API#2117]
Hello,

I have an issue with VivaWallet in Prestashop. The customer goes onto the website, adds items to their cart, goes to checkout and upon completion of the payment and returning back to the website, the customer is shown a white screen, no info. In the back office, the order is created but it's not assigned an order status so the customer doesn't see if their order has gone through nor by email until I manually check VivaWallet to see if the payment has been made then manually update the status to Payment Accepted in VivaWallet. I don't experience this with Bank Transfers payment option so wondering if my VivaWallet settings are incorrect or if there is a bug. When I setup VivaWallet module I followed the guide to the letter.

**Comment by matthewrgourd** [comment]
Hi @DrFostersCBD, sorry to hear. We advise [setting up a webhook](https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/#step-3-set-an-optional-webhook) for improved order syncing. Did you do that?

**Comment by DrFostersCBD** [comment]
Hello @matthewrgourd, I setup the API as asked and waited for a new order. The order has done the same again, created itself but hasn't assigned an order status. Every time an order is placed, the following information from the log appears on every VivaWallet transaction.

'16-Jan-2021 12:53:52 Europe/London] PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- 
  thrown in /home/*********/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 177'

'28-Jan-2021 13:19:21 Europe/London] PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- 
  thrown in /home/*********/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 177'

Reading a few other posts it appears to say its coming from the Payment Module and others saying its coming from the theme but doing a bank transfer payment doesn't cause the issue so I assume it's not the themes fault. Any suggestions?

**Comment by matthewrgourd** [comment]
Hi @DrFostersCBD, sorry to hear that, could I have your Viva Wallet Merchant ID so I can check your settings at this end? If you're unhappy to share it here, please send me an email (mgourd@vivawallet.com) quoting this issue number (#2117).

**Comment by DrFostersCBD** [comment]
Hi @matthewrgourd My Merchant ID: c7fbe8d8-94ea-429c-aaf3-ec6f18d500c1

**Comment by matthewrgourd** [comment]
Hi @DrFostersCBD, thanks for that. I'm going to replace with asterisks now for security purposes.

**Comment by matthewrgourd** [comment]
Hi @DrFostersCBD, can I also check which version or PrestaShop you have installed?

**Comment by DrFostersCBD** [comment]
Hi @matthewrgourd, I have Version 1.7.6.9 running PHP Version 7.2 if thats any use.

**Comment by matthewrgourd** [comment]
Hi @DrFostersCBD, I've corrected your payment source settings. Please test again when you get a spare moment.
