### ISSUE TITLE
3DS on  native v2 redirectToACSForm returns null in Production

### ISSUE THREAD

**Issue by PyB1l** [VivaPayments/API#2118]
It was a known issue in DEMO environment but suddenly 
https://api.vivapayments.com/nativecheckout/v2/chargetokens started responding with

`{"chargeToken":"whatever","redirectToACSForm":null}.`

**Comment by PyB1l** [comment]
I just tried it myself in production with 3 different valid cards and I consistently get
{"chargeToken":"whatever","redirectToACSForm":null} 

This totallly blocks our production payment process at least for 2 days

**Comment by matthewrgourd** [comment]
Hi @PyB1l, sorry to hear that. Did you get any Viva Wallet correlation IDs returned for us to check the logs. Can you also remind me of your merchant ID and tell me what date to check for the failures? If you prefer to share your merchant ID privately, you can email me at mgourd@vivawallet.com. Thanks.

**Comment by PyB1l** [comment]
We just tried a new payment and failed with 
```
X-Viva-CorrelationId: 21-029-FE199313
X-Viva-EventId: 0
```
I will send you the merchant_id  shortly

**Comment by PyB1l** [comment]
I just sent you the merchant_id by email

**Comment by matthewrgourd** [comment]
Hi @PyB1l, thanks for sending through your merchant ID. I've spoke to our dev team and apparently it's ok to have `null` as a value for `redirectToACSForm`. For payments below a certain level (threshold decided by card issuer), 3DS is frictionless and doesn't involve a challenge. In these cases you will see `null` returned in the response. I will update our documentation to make that clear. Looking at your account, I can see that you made 6 test payments today via the Native Checkout v2 channel. All of these were successful. Please close this issue if you feel it has been addressed adequately. Thanks, and have a good day!
