### ISSUE TITLE
 access to our Simple Checkout API

### ISSUE THREAD

**Issue by iChristosK** [VivaPayments/API#2119]
Hello! I'd like to test your simple checkout API.
Thank you,
Christos Katomoniatis 

Account ID  - 414741660351
Merchant ID - a3bcd06f-b8bb-4d47-a3ea-bae0dcb81369

**Comment by matthewrgourd** [comment]
Hi @iChristosK, demo access to Simple Checkout API enabled as requested. Have a good day!
