### ISSUE TITLE
Native chekout μήνυμα: VivaPayments: Expiration Date information could not be parsed

### ISSUE THREAD

**Issue by ignatios** [VivaPayments/API#212]
Καλησπέρα,

Θέλω να ενσωματώσω την Native checkout Μέθοδο αλλα δεν καλέιται ποτέ η installmentsHandler όπως έχετε στο παράδειγμα.

Επίσης όταν καλώ την VivaPayments.cards.requestToken() επιστρέφει μήνυμα: "VivaPayments: Expiration Date information could not be parsed"
Το url  tou site είναι https://shop2day.gr 

To viva account είναι demo και το merchantid είναι : f338efec-2b05-4de2-bdcc-78eccdb0eef9

**Comment by krakenrules** [comment]
Καλησπέρα Ignatios,

Μπορείτε να δοκιμάσετε την native checkout πληρωμή με βάση το παράδειγμα και τα δικά σας στοιχεία (Merchant ID, API Key).

**Comment by ignatios** [comment]
Εχω δοκιμάσει ήδη στο παράδειγμα με τo κώδικα που έχετε στο παράδειγμα και επιστρέφει μήνυμα:The following error occured: Invalid order with code 4164193826172600NULL Transaction Failure.
Ευχαριστώ

**Comment by krakenrules** [comment]
Καλησπέρα,
Στο σύστημα μας βλέπουμε ότι έχετε δημιουργήσει επιτυχώς orders τα οποιά εκτελέστηκαν (πχ με order code: 3298312283472609, 3789307993272602) καθώς και πολλά άλλα τα οποία έχουν γίνει expire.(πχ order code: 4164193826172608) Η διαδικασία CreateOrder δημιουργεί orders τα οποια γίνονται expire μετά από 5 λεπτα. Για να αλλάξετε αυτη την τιμή χρησιμοποιήστε την παράμετρο PaymentTimeOut στα options του CreateOrder.

Περισσότερα θα βρείτε στα παρακάτω links:
https://github.com/VivaPayments/API/wiki/Optional-Parameters 
https://github.com/VivaPayments/API/wiki/CreateOrder


Το order code 4164193826172600 που μας δώσατε δεν έχει δημιουργηθεί.

Ευχαριστούμε
