### ISSUE TITLE
UPDATE FROM VIVA WALLET: OUR ISSUES PAGE HAS MOVED TO LIVE CHAT!

### ISSUE THREAD

**Issue by matthewrgourd** [VivaPayments/API#2120]
### As of 29 Jan 2021

For technical support, please visit [developer.vivawallet.com](https://developer.vivawallet.com/) and click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. You do not need to have an account with Viva Wallet in order to use this service.

Thank you –

_Viva Wallet Development Team_

**Comment by vila3** [comment]
Hi there,

I have some questions, but I'm unable to use the live chat. Above it's saying
> You do not need to have an account with Viva Wallet in order to use this service.

I only have a demo account and I can't use the live chat because it's always asking me to sign in on my account. And with the demo account, I can't either use the live chat.

Am I missing something? Do you have any alternatives?

**Comment by bulivlad** [comment]
This is outrageous how I've been moving around to maybe 6 chat agents in the course of 2 days and no one is able to answer me why the documentation bit of Apple Pay is not working. the GitHub way of resolving issues was waaaay better 🤦

**Comment by Sotiris-k** [comment]
The people manning your Viva Wallet Chat have no idea about development issues.

I asked if I could use the API to send a Payment Notification and the person that answered me just copied and pasted some generic description of a Payment Notification. Then I asked if they knew what API means and they responded by telling me where to find my API Keys.

At least with the issues here we could help each other. The Live Chat is completely unhelpful.

**Comment by genesispro** [comment]
The live chat there is a bot asking you to login to your production account and chat... the chat agents there do not provide any developer feedback
