### ISSUE TITLE
problem with cards at mobile application 

### ISSUE THREAD

**Issue by evandoulas** [VivaPayments/API#2121]
for vivawallet account
 key="VivaPayments.PublicKey" value="Kgzu67pq+TVqooBDvG/k8RohIPf9bkHHyp0h/5hFvWE="
 key="VivaPayments.ClientId" value="26p1blspv05ec6p77fu91b0w4vymbgu67rwlakvl1b3e4.apps.vivapayments.com
 at source 4021

we are facing problem, after submitiing payment data.
we are getting blank page with no other response

It is an urgent problem as we are working in production mode!!!
please give us your feedback asap

**Comment by evandoulas** [comment]
kind reminder.
 we are still facing the problem

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [www.vivawallet.com](http://www.vivawallet.com) and [help.vivawallet.com](https://help.vivawallet.com/hc). We will reply to you as soon as we can. 

Best regards,

_Viva Wallet Development team_

**Comment by evandoulas** [comment]
Thanks for the info.
Next time I will use the proposed channel to reach your support.

Till now and for the problem #2121 that you closed the issue, where am I expecting your answer ?
This email ?

Regards
