### ISSUE TITLE
Installazione plugin su prestashop v. 1.6.1.2

### ISSUE THREAD

**Issue by KINGSGARDE** [VivaPayments/API#2122]
Buongiorno,

non riesco ad installare il plugin scaricato dal vs. sito development, mi segnala questo errore:

×2 errori
vivawallet (errore di analisi in /modules/vivawallet/vivawallet.php)
vivawallet (classe mancante in /modules/vivawallet/vivawallet.php)

come posso procedere?

Grazie

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). We will reply to you as soon as we can. 

_Viva Wallet Development team_
