### ISSUE TITLE
Quinta da Tôr - Turinox LDA

### ISSUE THREAD

**Issue by QuintaDaTor** [VivaPayments/API#2123]
Hi Team,

I ask permission to use demo version here. Now I have the code ready to deploy. I simple change the demo settings to realize. I made a simple test with a real card and viva wallet refuse the pay.
Could you please help to unlock the realize version?

I use simple checkout. In demo it works perfect. In realize mode in realize website I get the following mensagem, screen:

![image_2020_11_30T17_44_03_696Z](https://user-images.githubusercontent.com/66118257/107202253-e5e5a780-69f1-11eb-983a-9ec5f869b604.png)

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
