### ISSUE TITLE
Confirmed payment sets Processing status, but does not create invoice

### ISSUE THREAD

**Issue by flouris** [VivaPayments/API#2124]
I've installed this extension on our Magento 2.4 store, configured it and it works with test orders and payments I've made.
There are 2 issues that I currently found in testing:
1. After successful payment the order is set to "Processing" status (in the configuration I've set new orders to "Pending payment"), however the invoice of the order is not created automatically. This works differently from other payment methods I have (Paypal and other bank payments). The invoice should be created automatically, or at least there should be a configuration option to create it automatically or not.
2. After a refund or a cancelling of a successful payment in Viva payments (via the web dashboard), the order in magento remains in Processing status with the full invoice (manually created currently). The correct behavior after a refund would be to create a credit memo, depending on the amount of a partial or full refund that was inserted in Viva payments.
Please let me know how to resolve these issues.

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
