### ISSUE TITLE
Vivapayments Redirect Checkout

### ISSUE THREAD

**Issue by aiosifelis** [VivaPayments/API#2125]
Hi all. We recently converted our checkout page to use the redirect method. Everything works perfectly and the payments go through. We have a little issue with the payment methods on the Viva checkout page. Despite the fact that our customers choose to pay with a card when they're redirected to the Viva checkout page they have other options. The result is that the success url of our website is never called when they choose an option other than card. That way the order is never placed in our end.
![image](https://user-images.githubusercontent.com/36890905/107883692-598a2780-6ebe-11eb-9f66-9debaa01e434.png)

Is there a way to configure the checkout page not to accept other payment method other than card? 

In your documentation https://developer.vivawallet.com/online-checkouts/redirect-checkout/ you present the checkout page only with the card options but in the picture attached I can see that other methods are available. We would like to only give the card option to our customers.

Thank you in advance!

**Comment by aiosifelis** [comment]
Hey again. I went through the documentation here
https://developer.vivawallet.com/web-api-integration/payment-api/#tag/Payments/paths/~1api~1orders/post
And I figured how to disable the other options by settings the `disable*` kind of options to true. 
Is there a way to disable the `Vivawallet` option?

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
