### ISSUE TITLE
Vivawallet won’t redirect to create order in prestashop 1.7

### ISSUE THREAD

**Issue by win83max** [VivaPayments/API#2126]
Hi there!

We are experiencing the same issue of #900 , after payment there’s no redirection to our website so the order is not created on prestashop.

Customers do receive the option to print the receipt on screen but no link or redirection to our website.

Tried to remove www of our domain on vivawallet configuration but still is not working. Payment is accepted but order in prestashop is not created.

![Sans-titre-2](https://user-images.githubusercontent.com/79768704/109400272-19a85300-7948-11eb-99b5-fbc3d61e7ef7.jpg)
![Sans-titre-1](https://user-images.githubusercontent.com/79768704/109400339-7b68bd00-7948-11eb-92e2-b4da209b861f.jpg)
![Sans-titre-4](https://user-images.githubusercontent.com/79768704/109400341-7c015380-7948-11eb-90c0-af7a0b977efb.jpg)

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
