### ISSUE TITLE
Card tokenization - access_token incorrect?

### ISSUE THREAD

**Issue by LoggiaNG** [VivaPayments/API#2127]
Hello,
we're having problems making card tokenization work on Production. In demo everything works fine.

We think that the problem is that getting the bearer token doesn't work correctly for some reason.

We first make a POST request at https://accounts.vivapayments.com/connect/token with the correct credentials (else we would get "invalid client" error), to get the "access_token".

Then, when using the access_token as Token authorization in POST https://api.vivapayments.com/acquiring/v1/cards/chargetokens and the card details in the body, we get 403 Forbidden.

I think it's because the access_token is too short, but why does it return like this and not in the correct format or some error code? 

<img width="586" alt="Screenshot 2021-02-28 at 6 59 17 PM" src="https://user-images.githubusercontent.com/53644001/109426579-18822f00-79f7-11eb-8253-1176c999451f.png">

Are we missing something? Thank you

Also we've seen that the issues have been transferred to Live Chat, but there is no option for developers there.

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
