### ISSUE TITLE
Get Account Card Operations

### ISSUE THREAD

**Issue by fabiosicilia86** [VivaPayments/API#2128]
Hi,
i have a viva wallet account.
From API i see i can download POS Operations associate to my account.
I would know how i can download the operations that i do with the card associate to my account...
thanks in advance for response!

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
