### ISSUE TITLE
Native Checkout v2 Cancel payment

### ISSUE THREAD

**Issue by dbSoft-SoftwareSolutions** [VivaPayments/API#2129]
Hello and hope doing well. Is there any way to cancel transaction, which has been made with Native Checkout v2?

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_

**Comment by dbSoft-SoftwareSolutions** [comment]
Thank you!!
