### ISSUE TITLE
BIOTEK

### ISSUE THREAD

**Issue by BIOTEKMONEPE** [VivaPayments/API#213]
Καλησπέρα σας έχουμε ένα λογαριασμό σε εσάς και δημιουργήσαμε ακόμα ένα. Το www.sexylips.gr.
Θα θέλαμε να έχει την ίδια ασφάλεια όπως ο αλλός λογαριασμός. 
Νομίζω λέγεται htpps;

**Comment by krakenrules** [comment]
Καλησπέρα,

Μπορείτε να διαγράψετε την πηγη http ετσι ωστε να έχετε μόνο την https ενεργή.
Επισης θα πρέπει να ορίσετε το wallet στην πηγη πληρωμής. Απο τις ρυθμίσεις που έχετε κάνει προκύπτει ότι η πηγή 3701 (http) δεν έχει συνδεδεμένο wallet. Η άλλη πηγη που έιναι https ειναι συνδεδεμένη κανονικά. 

Ευχαριστούμε
