### ISSUE TITLE
wrong name

### ISSUE THREAD

**Issue by VickyFrag** [VivaPayments/API#2130]
i have installed vivawallet module for prestashop
but although i re-installed many times 
the name of the module is Test

see [attachment[]
![Opera Snapshot_2021-03-22_155422_www kaftania gr](https://user-images.githubusercontent.com/52821240/112000896-13605d80-8b27-11eb-9cd3-44bcfee4b945.png)
)

the same name test is 
![Opera Snapshot_2021-03-22_155638_mail google com](https://user-images.githubusercontent.com/52821240/112001085-47d41980-8b27-11eb-9b9d-749b91beba0d.png)
in the checkout page 

do you have any suggestions?
vfrag

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
