### ISSUE TITLE
Support Issues

### ISSUE THREAD

**Issue by vittsof** [VivaPayments/API#2132]
The vivawallet payments for magento 2 not working as it should. no cancel and return to order button and no native enviroment available. so customers who want to return and add products to cart lose their cart cause viva has placed the order before paying and no back button available. So customers do not buy anything and leave website.

Support through chat system is unacceptable and no solution for this issue yet.

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_

**Comment by vittsof** [comment]
Your live chat facility support team sucks... and your services too... No support at all!
