### ISSUE TITLE
VivaWallet API cannot load due to access controls checks

### ISSUE THREAD

**Issue by iChristosK** [VivaPayments/API#2133]
I am trying to hit the viva wallet api https://demo.vivapayments.com/api/orders but I get the following error.

![Screenshot 2021-03-26 at 15 40 46](https://user-images.githubusercontent.com/16455384/112792228-be16d580-906b-11eb-821e-4b233f65749d.png)

In order to verify that the request is indeed correct, I've used postman and I get

```
{
    "OrderCode": 8660470483575978,
    "ErrorCode": 0,
    "ErrorText": null,
    "TimeStamp": "2021-03-29T08:51:44.830731+03:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": true
}
```
So I know the request is valid. There is something wrong with my HTTP Headers? I am using Ionic Framework (typescript). 
I make sure I encode to based 64 the following MerchantID:APIkey and I add to the authorization of my headers. I also add the body like below. I've hidden the private information.

  ```
  const body = {
      amount: 200,
      email: "xxx@xxxcom",
      fullName: "xxx xxxxxxx",
      customerTrns:
        "Short description of items/services purchased to display to your customer",
      requestLang: "en",
      sourceCode: "xxxx",
    };
```

The request is a post request. So if anyone can help me figure out why I get the error, I'd really appreciate it

**Comment by iChristosK** [comment]
P.S I've tried to talking to the live support chat, but the people there didn't even remotely help me, and they didn't even know what postman is. So I don't know where else to put it.

**Comment by iChristosK** [comment]
```
 curl --location --request POST 'https://demo-accounts.vivapayments.com/connect/token' \
 --header 'Content-Type: application/x-www-form-urlencoded' \
 --header 'Authorization: Basic ZzI0N2NmbnlwYzV3cmszaHAwZnU2cTk3N2YzZzYxY2hnODV1NzJzZmJkb3c3LmFwcHMudml2YXBheW1lbnRzLmNvbTpTODUySjE4RDkzTDJzZDJKbU8xWG1iOU02eWg2NlU=' \
 --data-urlencode 'grant_type=client_credentials'
```

Using this I get the same error. So I can't even connect to get the access token
![Screenshot 2021-03-29 at 09 06 15](https://user-images.githubusercontent.com/16455384/112793502-1a7af480-906e-11eb-8390-595dea2e3df6.png)

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_

**Comment by vittsof** [comment]
> 
> 
> P.S I've tried to talking to the live support chat, but the people there didn't even remotely help me, and they didn't even know what postman is. So I don't know where else to put it.

ΑΠΑΡΑΔΕΚΤΟ support και χάλια υπηρεσίες
