### ISSUE TITLE
⚠️ No transaction received / demo mode 

### ISSUE THREAD

**Issue by LaBoem** [VivaPayments/API#2134]
Hello,
We recently started using your platform.
We use Wordpress / WooCommerce for our online store.

We have installed the Viva Wallet plugin, followed the installation and adjustment instructions. Also, we have installed the WooCommerce Credentials API on the online store and checked the demo boxes.

Once these parameters have been saved in the front office, Viva Wallet does not have any problems and all the notifications are very green.

When I do an online payment simulation on the store, with the fake bank card etc. everything seems to be working fine. (I received my order confirmation email a few seconds later)
But when I look in my dashboard at https://demo.vivapayments.com/, no transaction was fetched ...

Is this normal?
Please can you help us?
BOHEME Jean

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
