### ISSUE TITLE
Vivawallet checkout problem

### ISSUE THREAD

**Issue by Iron1977** [VivaPayments/API#2135]
Hi guys, 

i have a vivawallet acount for my company that is in uk, my accoubnt is in pounds but my shop is for the french market. 

My store is under shopify

the problem is when customers are in the checkout on my store for exemple, they have 99 euro , they continue the checkout and go to the vivawallet payment page and they get 99 pounds ! there is no conversion 

my shop is 4alphas.fr 

I try to install currency selector but the problem stays the same, i think there is something to do , changing some code i dont know , i think its a bug

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
