### ISSUE TITLE
Declined transaction problem

### ISSUE THREAD

**Issue by wojciechbrzostek** [VivaPayments/API#2137]
hello

a lot of transaction in my shop were declined

from random countries

some of them have this corelation id:

Transaction failed with Viva-CorrelationId: 21-120-904B0798
Transaction failed with Viva-CorrelationId: 21-120-893C5E24
CorrelationId: 21-119-94E14F36

could you help me with this?

I cant even see the two first transaction in my viva wallet panel

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
