### ISSUE TITLE
The merchant with id xxxx does not have a source with code '123' assigned or the source is disabled

### ISSUE THREAD

**Issue by tusharshah1692** [VivaPayments/API#2138]
hi @matthewrgourd we are trying to make payment using credit card we receive the error merchant with id xxxx does not have a source with code '123' assigned or the source is disabled . some cards were able to make transactions and some failed. 
We also found that few credit cards does not ask for otp and the transaction failes.

https://user-images.githubusercontent.com/82366772/117563314-a7c85480-b0c2-11eb-9480-1615c0ed2dfb.mp4

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
