### ISSUE TITLE
Success url not working in demo

### ISSUE THREAD

**Issue by IvanSammut** [VivaPayments/API#2139]
Hi,

I've set up my account to send the success as shown below in the development area. But once the payment is successfull I never get redirected to the success url but I just get a page with transaction successfull and it stops there. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/84788396/119514402-47e5d500-bd75-11eb-9bc0-ca6c4833a092.png)

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
