### ISSUE TITLE
Connect Vivapayments with website made on WIX platform

### ISSUE THREAD

**Issue by efidolcini** [VivaPayments/API#214]
Hi, I am trying to connect my ecommerce made on wix.com, is that possible?
thanks

**Comment by defilerc** [comment]
Καλησπέρα,

Όπως μπορείτε να δείτε και εδώ: https://github.com/VivaPayments/API/issues/174 δεν υπάρχει κάποιο wix plugin για integration με το viva payments api. Μπορείτε ωστόσο, να προβείτε σε custom υλοποίηση, χρησιμοποιώντας μία από τις μεθόδους που περιγράφονται εδώ: https://github.com/VivaPayments/API/wiki

Επίσης εδώ: https://github.com/VivaPayments/API μπορείτε να βρείτε διάφορα code samples που θα σας βοηθήσουν.

Με εκτίμηση,

**Comment by Daubthi** [comment]
Hi, efidolcini, Did you find a solution to implement vivawallet on wix ?
Thank you
