### ISSUE TITLE
htaccedd

### ISSUE THREAD

**Issue by federicoprimomo** [VivaPayments/API#2141]
I can't implement for prestashop.
First I installed from prestashop modules, the demo version was perfect,
then the real keys failed, then, I read about installing from this link https://developer.vivawallet.com/downloads/vivawallet1.7.zip
but still doesnt work. When I click pay button, redirects to https://www.vivapayments.com/web/newtransaction.aspx?Ref=
and shows OrdersOrderCodeNotFound: Order with code 0 was not found
Configuration is OK, I followed this instructions https://developer.vivawallet.com/plugins/prestashop-1.7/
except for "Step 3: Set an optional webhook" , I got an error "URL not verified." 
PLEASE HELP, chat with vivashop didn't solve nothing.

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
