### ISSUE TITLE
Problem with payments Vivawallet/Woocommerce

### ISSUE THREAD

**Issue by cbdeee** [VivaPayments/API#2143]
Hello,

I'm using vivawallet on my woocommerce website and have problems with payments, 95% of the payments are not working.
I'm using the latest version of the plugin (1.4.4), credentials are good, API key too.

When customers try to pay, the payment page just become grey/white and nothing happened, see :

![image](https://user-images.githubusercontent.com/72744136/125192054-071f1e00-e246-11eb-8a83-3bcf5911f63e.png)

I've been using vivawallet for more than a year and have tons of problems with it, but I just change my website and now it's just dramatic, almost all my orders are unpayed and I have to call my customers to send them a payment link to solve the issue. I'm gonna loose my customers if this problem is not solve quickly, i've been sending a lot of tickets to the support, trying a lot of solutions, install, desinstall plugins, credentials... Nothing work.

Thanks

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
