### ISSUE TITLE
Error - Connection to WooCommerce checkout failed. Please check your connection or try again later.

### ISSUE THREAD

**Issue by NunoSilva1979** [VivaPayments/API#2144]
Good night,

I write here because I need help, I have a site ready to work but this error has been happening for 15 days and I can't solve it.

When placing an order on the website gives an error when the customer makes the payment / Checkout ( Connection to WooCommerce checkout failed. Please check your connection or try again later.), this error appears only for credit cards payments. The purchase is made and the amount is sent to Viva Wallet's account, however this error induces customers that something went wrong with the purchase and they leave the site or else pay again.

Can you help us in this situation?

Best Regards

Nuno Silva

**Comment by matthewrgourd** [comment]
Hi there, 

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via [developer.vivawallet.com](http://developer.vivawallet.com). Click on the live chat icon in the bottom right-hand corner of the page:

[![Live chat](https://user-images.githubusercontent.com/44943019/106276885-2134e900-6230-11eb-8c1a-ade0e95a3fc2.png)](https://developer.vivawallet.com)

Our support team will help you directly and escalate to our technical team if necessary. 

_Viva Wallet Development Team_
