### ISSUE TITLE
Payment order with 3 customer emails

### ISSUE THREAD

**Issue by kyrkonpmi** [VivaPayments/API#2146]
Hi, when i create a payment and the customer email include 3 different emails then i get errorcode 500 but if my customer email include 2 emails it works fine. 

Sample customer email with 2 address is: xyz123@gmail.com,xyz456@gmail.com
Sample customer email with 3 address is: xyz123@gmail.com,xyz456@gmail.com,xyz789@gmail.com

Regards,

Kyriakos

**Comment by gemitsio** [comment]
Hi there,

Many thanks for your request. I would like to inform you that there is a limitation of 50 characters in email parameter (it is a string parameter). 

Also, please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via developer.vivawallet.com. Click on the live chat icon in the bottom right-hand corner of the page:

![image](https://user-images.githubusercontent.com/91877364/142834591-bca334b6-dd26-470a-ad6c-208b154c9963.png)

Our support team will help you directly and escalate to our technical team if necessary.

Viva Wallet Development Team
