### ISSUE TITLE
SmartCheckout -- after redirecting transaction id is missing in the Response URL

### ISSUE THREAD

**Issue by mrpavithra228** [VivaPayments/API#2147]
We are trying Smart checkout API using Java, while redirecting to our website its not showing transaction id. 

https://122.166.49.42:9020/ais/control/returnVivaRedirectUrldata?OrderCode=4487601523599771&language=en-US&eventId=2062
https://122.166.49.42:9020/ais/control/returnVivaRedirectUrldata?OrderCode=5536380685155681&language=en-GB&eventId=2061
https://122.166.49.42:9020/ais/control/returnVivaRedirectUrldata?OrderCode=5938148974244862&language=en-US&eventId=2061
https://122.166.49.42:9020/ais/control/returnVivaRedirectUrldata?OrderCode=2538330130579758&language=en-US&eventId=2061
https://122.166.49.42:9020/ais/control/returnVivaRedirectUrldata?OrderCode=2038541317268508&language=en-US&eventId=2061

Trade name :  EFILE READY LIMITED
Registration date :  19/02/2020

**Comment by mrpavithra228** [comment]
Please let me know any API call is there to get transaction id using OrderCode

**Comment by gemitsio** [comment]
Hi there,

Many thanks for your request. I would like to inform you that you will receive transaction id only if the payments will be successful. The provided URLs includes [eventid ](https://developer.vivawallet.com/integration-reference/response-codes/)which are linked for failed transactions.

Also, please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via developer.vivawallet.com. Click on the live chat icon in the bottom right-hand corner of the page:

![image](https://user-images.githubusercontent.com/91877364/142834591-bca334b6-dd26-470a-ad6c-208b154c9963.png)

Our support team will help you directly and escalate to our technical team if necessary.

Viva Wallet Development Team
