### ISSUE TITLE
Cokie Manager doesnt exist

### ISSUE THREAD

**Issue by gokhanakdag** [VivaPayments/API#2148]
Hello,

I had an error after installed Vivapayments for Magento 2.4;

Cokie Manager doesnt exist;

sh-4.2$ php -f bin/magento module:enable --clear-static-content Ced_VivaPayments
The following modules have been enabled:
- Ced_VivaPayments

To make sure that the enabled modules are properly registered, run 'setup:upgrade'.
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Generated static view files cleared successfully.
sh-4.2$ php -f bin/magento setup:upgrade
Cache types config flushed successfully
Class Ced\VivaPayments\Stdlib\Cookie\CookieManager does not exist

In ClassReader.php line 24:

  Class Ced\VivaPayments\Stdlib\Cookie\CookieManager does not exist

sh-4.2$ php -f bin/magento cache:flush

  There are no commands defined in the "cache" namespace.

sh-4.2$ php -f bin/magento module:disable --clear-static-content Ced_VivaPayments
The following modules have been disabled:
- Ced_VivaPayments

Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Generated static view files cleared successfully.

In ClassReader.php line 24:

  Class Ced\VivaPayments\Stdlib\Cookie\CookieManager does not exist

**Comment by gokhanakdag** [comment]
Magento 2.4.2 Version;

 Error code:

main.CRITICAL: Class Ced\VivaPayments\Stdlib\Cookie\CookieManager does not exist {"exception":"[object] (ReflectionException(code: -1): Class Ced\\VivaPayments\\Stdlib\\Cookie\\CookieManager does not exist at /var/www/vhosts/xxx.com/abc.xxx.com/vendor/magento/framework/Code/Reader/ClassReader.php:24)"} []

**Comment by gemitsio** [comment]
Hi there,

Many thanks for your request. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via developer.vivawallet.com. Click on the live chat icon in the bottom right-hand corner of the page:

![image](https://user-images.githubusercontent.com/91877364/142834591-bca334b6-dd26-470a-ad6c-208b154c9963.png)

Our support team will help you directly and escalate to our technical team if necessary.

Viva Wallet Development Team
