### ISSUE TITLE
Smart Checkout: empty response

### ISSUE THREAD

**Issue by IleaBrussels** [VivaPayments/API#2149]
Hello,

I receive an empty response when sending the request for Smart Checkout https://demo-api.vivapayments.com/checkout/v2/orders

You can see the data sent in the request here:
https://smartcheckout.ilea.be/test/t.php

Also, attached the request code. 

Could you please check what's wrong?

[t.txt](https://github.com/VivaPayments/API/files/7807087/t.txt)

**Comment by gemitsio** [comment]
Hi there,

Many thanks for your request. You should check the Authentication type and to remove the decimal from amount parameter. Please be aware that we are no longer monitoring this issues page. You can raise any technical issues via our live chat facility available via developer.vivawallet.com. Click on the live chat icon in the bottom right-hand corner of the page:

![image](https://user-images.githubusercontent.com/91877364/142834591-bca334b6-dd26-470a-ad6c-208b154c9963.png)

Our support team will help you directly and escalate to our technical team if necessary.

Viva Wallet Development Team
