### ISSUE TITLE
Invalid password for the merchant

### ISSUE THREAD

**Issue by powerpcgr** [VivaPayments/API#215]
Βγάζει αυτό το σφάλμα κατά την πληρωμή. Έχω ελέγξει τους κωδικούς αλλά δεν είναι λάθος και επίσης έχουν ταυτοποιηθεί όλα τα στοιχεία μου και έχει εγκριθεί το payment source και μου επιβεβαίωσαν από την viva ότι μπορώ να κάνω συναλλαγές.

**Comment by krakenrules** [comment]
Θα θέλαμε να μας στείλετε το merchant id σας, καθώς και το περιβάλλον στο οποίο πραγματοποιείτε δοκιμές (demo ή live),;

Ευχαριστούμε,

**Comment by powerpcgr** [comment]
Σε live περιβάλλον είναι. Να γράψω το merchant id δημόσια εδώ ή να στείλω σε κάποια διεύθυνση;
Ευχαριστώ.

**Comment by krakenrules** [comment]
Θα θέλαμε να μας στείλετε τα στοιχεία στο merchants@vivawallet.com.

Ευχαριστούμε πολύ

**Comment by krakenrules** [comment]
Καλημέρα,

Παρακαλούμε επιβεβαιώστε ότι ορίζετε σαν password το API Key της σελίδας Ρυθμίσεις  | Πρόσβαση API.

Ευχαριστούμε πολύ

**Comment by powerpcgr** [comment]
Απ' ότι συμπέρανα έχει πρόβλημα το extension για το opencart, καθώς δεν με αφήνει να έχω συγκεκριμένα σύμβολα στο API Key. Οι κωδικοί συμφωνούσαν μεταξύ τους παρ' όλα αυτά έβγαζε το σφάλμα. Μόλις αφαίρεσα κάποια σύμβολα το δέχτηκε. Ευχαριστώ.
