### ISSUE TITLE
www.vivawallet.com - Access denied error message 

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#2150]
We are one of your live customers.
Trade name :  EFIXE RXADY XXXXX
Registration date :  19/02/2020

We are getting an Access Denied error message when accessing  'https://www.vivawallet.com/'.

The similar message appeared for a couple of our clients while making payment using Viva Wallet.
One of the client uses - Isle of Man IP addresses - should these IP addresses be added to the approved list?

Please suggest what can be done to resolve this issue.

**Comment by gemitsio** [comment]
Hello @pavithra-itcs, thank you for your message. 

Please provide your IP to investigate further.

Sincerely,
Viva Wallet Development Team

**Comment by pavithra-itcs** [comment]
Hi George Mitsiou,

Please find the below IP address which is used to access 'https://www.vivawallet.com/'.
103.56.252.130
122.166.49.41
122.166.49.42
115.246.209.82
these are the four ip being used...could you please let us know what is the issue.
It could be any one of the IP

Please Clarify why is end-user getting this 'Access Denied' error message while making payments making API call.

Thanks,
Pavithra

**Comment by gemitsio** [comment]
Hello @pavithra-itcs,

we would like to inform you that we investigate the reported issue with our network team and there is not any restriction for the provided IPs.

We suggest to check with the network team internally.

Sincerely,
Viva Wallet Development Team

**Comment by gemitsio** [comment]
Hello @pavithra-itcs,

we investigate the reported issue and the transaction b3fc9559-6c62-48cd-af75-8d96eb54d0c8 had failed. No money transferred to your bank account.

Sincerely,
Viva Wallet Development Team
