### ISSUE TITLE
how many days takes to activate redirect URL

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#2151]
Hi Team,

After adding  redirect URL how many days it takes to activate that source code related to that redirect URL.

**Comment by gpliakis** [comment]
Hi @pavithra-itcs,

I am sorry but I do not understand your query. Could you please clarify what exactly are you trying to do?

**Comment by pavithra-itcs** [comment]
To Use smart checkout API, we should add redirect URL in viva wallet account. How many days it will take to activate that.

https://help.vivawallet.com/en/articles/5119253-where-can-i-find-the-source-code

**Comment by gpliakis** [comment]
This happens instantly, once you set up the source code.

Sincerely,
Viva Wallet Development Team
