### ISSUE TITLE
IN LIVE - Transaction is success but returns "StatusId":"E"

### ISSUE THREAD

**Issue by pavithra-itcs** [VivaPayments/API#2152]
Hi Team,

We are using the Smart checkout, we got the money but in response showing the transaction failed "StatusId":"E", Please let us know the reason.

Please find the response below :

Transaction Response Data**{"Transactions":[{"Fee":0.00,"BankId":"NET_VISA","ParentId":null,"Switching":false,"Amount":12.00,"StatusId":"E","ChannelId":"245a790d-c98d-4d80-ad97-a9b1efb5771e","MerchantId":"3d9285cf-808a-ec11-93b0-000d3ab7b565","ResellerId":null,"InsDate":"2022-02-23T21:49:46.903+02:00","CreatedBy":null,"TipAmount":0.00,"SourceCode":"6343","TransactionId":"b3fc9559-6c62-48cd-af75-8d96eb54d0c8","Commission":0.00,"PanEntryMode":"01","MerchantTrns":"PS-P20-08529","CustomerTrns":"The period of Month(12/08/2019)","IsManualRefund":false,"TargetPersonId":null,"AcquirerApproved":false,"SourceTerminalId":90000000,"RedeemedAmount":0.00,"AuthorizationId":null,"TotalInstallments":0,"CurrentInstallment":0,"ClearanceDate":null,"ResellerSourceCode":null,"RetrievalReferenceNumber":"205419407633","Order":{"OrderCode":2424976561467251,"ChannelId":"95d02b56-bace-4608-ad1b-c1a8da705e52","ResellerId":null,"SourceCode":"6343","Tags":["18641","PS-42627","PS-P20-08529"],"RequestLang":"en-US","ResellerSourceCode":null},"Payment":{"Email":"[nutautaiteruta@gmail.com](mailto:nutautaiteruta@gmail.com)","Phone":null,"ChannelId":"245a790d-c98d-4d80-ad97-a9b1efb5771e","FullName":"R NUTAUTAITE","Installments":0,"RecurringSupport":false},"TransactionType":{"Name":"CardCharge","TransactionTypeId":5},"CreditCard":{"Token":"2E11F9068F689C78F9CC5D71889F15CE1E5DBB2A","Number":"475747XXXXXX8352","CountryCode":"GB","IssuingBank":"National Westminster Bank PLC","CardHolderName":"R NUTAUTAITE","ExpirationDate":"2024-04-30T00:00:00","CardType":{"Name":"VISA","CardTypeId":0}}}],"ErrorCode":0,"ErrorText":null,"TimeStamp":"2022-02-23T21:49:47.4588747+02:00","CorrelationId":null,"EventId":0,"Success":true}

**Comment by gemitsio** [comment]
Hello @pavithra-itcs,

we investigate the reported issue and we found out that the transaction failed due to issuer declined with response code - 59 (The customer's card issuer has declined this transaction as the credit card appears to be fraudulent).

So, the StatusId":"E" is correct.

Sincerely,
Viva Wallet Development Team
