### ISSUE TITLE
access to simple checkout stopped?

### ISSUE THREAD

**Issue by ThetisTV** [VivaPayments/API#2157]
Greetings to all!

Does anyone know if VivaWallet has stopped to support Simple Checkout Method?

Suddenly functionality has stopped working few days ago for merchant 5ba2aa58-5bad-49ba-ac83-dbc0e2b5ca0d .

Thanks, 
Tassos

**Comment by jonian** [comment]
Hi @can3ry, apologies for commenting on a closed issue. If we don't want/can't use the smart checkout, are there any other alternatives, except advising our clients to move to another platform?

**Comment by jonian** [comment]
@can3ry I just realized that we are using native checkout v2 and not simple checkout. Should I open a new issue or native checkout is still available and will remain available?

**Comment by can3ry** [comment]
Hi @jonian 
We would like to inform you that we will be retiring our "Native Checkout v2" solution as of June 30th.  
This means that any integration you may have with us using your Native Checkout v2 credentials will cease to function from June 30th onwards. 
Therefore, we’d advise you to integrate with Smart Checkout, our hosted payments page for online stores that gets smarter over time. Smart Checkout is fast and easy to integrate, offers increased conversion and is continually self-updated, making your life a lot easier.  
Integration guidelines for Smart Checkout can be found here: https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/ 
I am closing this ticket but please feel free to create a new one.
Thanks
Best Regards
Viva Wallet Development Team
