### ISSUE TITLE
OAuth2 authentication / OAuth 2 token generation

### ISSUE THREAD

**Issue by karbivskij** [VivaPayments/API#2159]
Howdy!

I'm use instruction from this link and set up curl to get access token, my code PHP in bellow:

I'm used a few methods to get token, but it's not working. I want to know, why?

The error code - {"error":"invalid_client"}
```
<?PHP
function post($url, $data, $headers)
{
    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => $url,
        CURLOPT_RETURNTRANSFER => true, // return the transfer as a string of the return value
        CURLOPT_TIMEOUT => 0,   // The maximum number of seconds to allow cURL functions to execute.
        CURLOPT_POST => true,   // This line must place before CURLOPT_POSTFIELDS
        CURLOPT_POSTFIELDS => $data // Data that will send
    ));
    // Set Header
    if (!empty($headers)) {
        curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
    }
    $response = curl_exec($curl);
    $errno = curl_errno($curl);
    if ($errno) {
        return false;
    }
    curl_close($curl);
    return $response;
}
$str = 'grant_type=client_credentials';
$data = $str;
$headers = ['Authorization: Basic (mycredentials)','Content-Type: application/x-www-form-urlencoded'];
 echo post("https://demo-accounts.vivapayments.com/connect/token", $data, $headers);
?>
```

**Comment by can3ry** [comment]
Thanks for your query.
Could you let me know what you're trying to do, e.g., which APIs you're attempting to access?
This error is commonly associated with invalid authentication credentials.
If you are implementing our [Smart Checkout](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/) solution, could you ensure you use the smart checkout credentials as mentioned in step 5 [on this page](https://developer.vivawallet.com/getting-started/find-your-client-credentials/)? 
Thanks
Viva Wallet Development Team

**Comment by karbivskij** [comment]
Client ID and Client Secret ?

**Comment by can3ry** [comment]
Yes, please use the Client ID and Client Secret and let me know the result.
![Screenshot 2022-04-02 at 21 46 44](https://user-images.githubusercontent.com/51880555/161400712-869620f8-496f-44b7-a888-ddb74083aac3.png)
Thanks

**Comment by karbivskij** [comment]
Thanks for help
