### ISSUE TITLE
Checkout Problem

### ISSUE THREAD

**Issue by musicmegastoregr** [VivaPayments/API#216]
Καλησπέρα σας,

Πελάτης μας προσπάθησε να κάνει checkout χρησιμοποιώντας την πιστωτική του κάρτα όμως το μήνυμα που έλαβε ήταν Η συναλλαγή σας απέτυχε.

Προσπάθησα να κάνω και εγώ ο ίδιος δοκιμαστική αγορά με πιστωτική κάρτα και έλαβα το ίδιο μήνυμα κατά το checkout,

Παρακαλώ ενημερώστε με σχετικά στο email: info@music-megastore.eu

Φιλικά,

Κόκκινος Λάμπρος
www.music-megastore.gr

**Comment by krakenrules** [comment]
Καλησπέρα σας, 
Θα θέλαμε να μας στείλετε το merchant id σας στο merchants@vivawallet.com.

Ευχαριστούμε πολύ

**Comment by musicmegastoregr** [comment]
Καλησπέρα σας,

Ευχαριστώ για την ενημέρωση, μπορείτε σας παρακαλώ να μου εξηγήσετε τι ακριβώς σημαίνει το integration με redirection ή native τρόπο;

Επιθυμούμε δυνατότητα πληρωμής και με viva wallet πελατών αλλά και με χρήση της πιστωτικής τους κάρτας,

Ευχαριστώ,

Φιλικά,

**Comment by xargr** [comment]
@musicmegastoregr rediration είναι ο τρόπος πληρωμής με redirect. Δηλαδή ο χρήστης πατάει πληρωμή και μεταφέρεται σε ασφαλές περιβάλλον της vivapayment, στην συνέχεια αφού ολοκληρώσει την πληρωμή επιστρέφει στην ιστοσελίδα σας. Ο μηχανισμός επιτρέπει να ενημερώνεται ο κάτοχος της σελίδας δυναμικά για το αν η πληρωμή είναι επιτυχημένη ή όχι. Στην native μέθοδο ο χρήστης ολοκληρώνει την πληρωμή μέσα στην σελίδα της ιστοσελίδας, απαιτείται όμως η χρήση ssl

**Comment by musicmegastoregr** [comment]
@xargr @krakenrules Καλημέρα σας, νομίζω κατάλαβα, η επιλογή που ήδη είχαμε ήταν redirect, ο χρήστης μεταφέρονταν σε περιβάλλον vivapayment και ολοκλήρωνε την πληρωμή του, το πρόβλημα είναι όμως ότι καθώς προσπαθεί να ολοκληρώσει πληρωμή με credit card, λαμβάνει μήνυμα σφάλματος και δεν ολοκληρώνεται η πληρωμή, αυτό ήταν και το πρόβλημα μας εξ αρχής αυτού του topic. παρακαλώ, ενημερώστε με πως μπορούμε να το διορθώσουμε.

Φιλικά,

**Comment by xargr** [comment]
@musicmegastoregr μέσα στην viva σου έχει στοιχεία για το integration. Σιγουρέψου ότι έχει βάλει στον κώδικα σου τα σωστά και επίσης κοίταξε αν έχεις τα σωστά URL . Στο τέλος το μόνο που υπάρχει είναι να μην βάζεις τα βάτα στοιχεία της δοκιμαστικής κάρτας..
Γιατί αφού σου δείχνει την σελίδα της viva για την πληρωμή με το πόσο πληρωμής κανονικά άρα ο κώδικας σου είναι σωστός

**Comment by kostGX** [comment]
Closing because issue is more than 6 months inactive and assuming it's solved.

Please let us know if you want to reopen it.
