### ISSUE TITLE
Viva Wallet Standard Checkout - Missing alternative text

### ISSUE THREAD

**Issue by Karagiannidis** [VivaPayments/API#2163]
At file includes/class-wc-vivawallet.php inside function payment_fields(), line 558

please change
```php
$res .= '<img src="' . WC_Vivawallet_Helper::VW_CC_LOGOS_URL . '" style="max-width:100%;"  />';
```
 to
```php
$res .= '<img alt="Vivawallet CC Logos" src="' . WC_Vivawallet_Helper::VW_CC_LOGOS_URL . '" style="max-width:100%;"  />';
```

(An other alternative is to make function payment_fields pluggable).

It's a small but important change in order to be compatible with Web Content Accessibility Guidelines.

Thanks

**Comment by can3ry** [comment]
Hello @Karagiannidis 
Thanks too much for your feedback.
I've informed the product team accordingly.
Best regards
Viva Wallet Development Team
