### ISSUE TITLE
Magento 2.4 Problem

### ISSUE THREAD

**Issue by pakagyla** [VivaPayments/API#2164]
Υπάρχει ενα λάθος , το οποίο είναι λάθος λογικής στην δημιουργια του Module σας., 

Οι παραγγελιες επιστρεφουν στο magento το Transaction Id, ολα καλά. 
To προβλημα ειναι πως κατα τη διαδικασία της συναλλαγης ολοκληρωνονται και προσπαθειες παραγγελιας που δεν ολοκληρωνονται , ειτε οταν κανει ο πελατης ενα βημα πίσω απο το περιβαλλον πληρωμής, παλι ερχεται σε εμας η παραγγελια

Θα πρεπει να διορθωθει το module σας ώστε να μην ερχονται σε εμάς οι μη ολοκληρωμένες παραγγελιες.

Αναμένοντας τη βοήθειά σας.

**Comment by gemitsio** [comment]
Hello @pakagyla,

thank you very much for the reported case.

I would like to inform you that transactions generated when a payment is completed and not when the payment remains pending. Magento works with [cron jobs] (https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cron.html) and update the status of the orders based on the conditions that you have set.

I appreciate to clarify which cron jobs you have set in your admin panel.

Best regards,
Viva Wallet Development Team

**Comment by gemitsio** [comment]
Hello @pakagyla,

this is a gentle reminder 😊.

Best regards,
Viva Wallet Development Team
