### ISSUE TITLE
Cannot capture pre-auth transaction on demo account

### ISSUE THREAD

**Issue by svolkomorov** [VivaPayments/API#2165]
Hello!

I'm doing a POST /api/transactions/3fdcbe81-7ada-4c55-b894-1526b54e46bb  and it returns the following error:

"The specified api action is disabled for the merchant 0be707ba-54d4-41c3-8750-f3c7a53aca62, please consult the documentation"

I've searched through the issues here and apparently something needs to be enabled on my demo account for this endpoint to work. Can I do it myself? If not could someone please help me out? Thank you!

**Comment by can3ry** [comment]
Hello,
Thank you for your query.
Please refer to [this link](https://developer.vivawallet.com/tutorials-for-payments/create-a-recurring-payment/#before-you-start) to allow recurring payments for your account. You should also set allowRecurring parameter as true while [creating the initial payment order](https://developer.vivawallet.com/tutorials-for-payments/create-a-recurring-payment/).
Please let us know if this helps.
Thanks
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hello,

Could you send the request body for the payment order you created? 

Please remember to set **preauth** to true for the [initial payment order](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post). 

Please also ensure that you do not set installment or recurring payment features(allowRecurring and maxInstallments) when creating a payment order.

Thanks
Viva Wallet Development Team

**Comment by svolkomorov** [comment]
Hello,

1. `/checkout/v2/orders`

`{
      "amount": 2600,
      "sourceCode": "5142",
      "preauth": true,
      "customer": {
        "email": "913d6e8f-6fdb-4e10-90b7-f7473149ae61@fake.local",
        "phone": null,
        "fullName": "913d6e8f-6fdb-4e10-90b7-f7473149ae61",
        "requestLang": null,
        "countryCode": null
      },
      "merchantTrns": "demo #605/6256aece37d81101c10cadec",
      "customerTrns": "demo #605"
    }`

At this point I'm able to see the transaction in the "sales" table with the type "authorization".

2. `/api/transactions/b16d61c2-0c95-4030-82b2-6a981036cd97`

`{
      "amount": 2000
    }`

This request used to give me the "specified api action is disabled" error but it turns out checking the "Allow recurring payments" checkbox in "API Security features" helps and I can capture the preauthed transaction now, even though I'm not actually doing a recurring payment. It stops working as soon as I uncheck the checkbox. Is this expected behavior?

**Comment by can3ry** [comment]
Hello @svolkomorov 
Thanks so much for all the details you shared.
By default, pre-auth functionality is available on Viva Wallet self-care. You can capture the payment from the Viva Wallet interface; however, the "Allow recurring payments" option should be activated **for using API calls**. This is the current flow, so please proceed as per your needs. 
I am going to raise this internally for further investigation and keep you updated. 
Thanks again
Viva Wallet Development Team
