### ISSUE TITLE
RFC: OpenAPI Definitions

### ISSUE THREAD

**Issue by hivanov** [VivaPayments/API#2166]
Hello,

Is it possible to create OpenAPI definition of your APIs? It would be very helpful for automatic client generation.

**Comment by gemitsio** [comment]
Hello @hivanov,

thank you for your message. I would like to inform you that our end points are public published, and everyone can target them.

To can be identified as merchant, you should use your account credentials.

Let me know if you need further clarifications.

Best regards,
Viva Wallet Development Team
