### ISSUE TITLE
WooCommerce pending payment after client successfully paid to VivaWallet.

### ISSUE THREAD

**Issue by ipAlexx** [VivaPayments/API#2168]
The payment status SOME TIMES stays at pending and don't change to processing.
I'm using the default viva wallet plugin "WooCommerce Viva Wallet Gateway v.3.6.3"
And the latest version of Woldpress.

When I say some times I mean that some times works correct and some times the order status stays in at pending.
These are the settings of the plugin https://imgur.com/n3aw0oA
And this is the plugin https://imgur.com/R34gJ0w

Thank you in advance!

**Comment by gemitsio** [comment]
Hello @ipAlexx,

thank you for your message.

You refer that sometimes there is delay when the user is in Smart Checkout or in your website checkout form?

Best regards,
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hello @ipAlexx 
Thanks for the details.
As you mentioned, when the customer completes a purchase, they are redirected to your return URL. This is a browser to browser redirection. If any communication issue happens during or before this redirection, your website cannot get the payment status and update the order.  There can be several reasons for this. For example, the user can leave/close the page, or the server has a degradation and cannot process the request, a lack of internet connection, a plugin that prevents redirection, etc. This is not entirely avoidable, but setting up a **webhook** can be a solution. When you activate the webhooks, we start sending server-to-server notifications to your site, and our plugin updates the payment's status accordingly.  Webhooks can be defined from Viva Wallet self-care. Please check [this page ](https://developer.vivawallet.com/plugins/woocommerce-smart-checkout/#step-2-set-webhook) to learn how to create a webhook for the smart checkout plugin. 
Please let us know if you need further assistance.
Thanks
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hi @ipAlexx 
I am closing this issue, but please feel free to add comments if you have any questions. 
Thanks
Viva Wallet Development Team

**Comment by stocki8810** [comment]
Hello,

i have the same issue with 99% of all Payconiq Paiement.

Control has been done for Webhooks also all credi card paiement work no problem.

Is it possible to active log on webhooks ? Because i see any logs for Webhooks on the WooCommerce Viva Wallet Gateway

I have already take a Ticket on Viva Wallet but always same information check Webhooks.

Thank You
