### ISSUE TITLE
Payment successful order status canceled 

### ISSUE THREAD

**Issue by jkmagic1** [VivaPayments/API#2169]
Hi i use opencart 3.0.3.2 .
When a customer makes a payment the status of order is canceled and i find the order  in "Missing Orders" 
I receive mail from viva that a payment has been made.
Am i doing something wrong?

I use those links in VIvawallet dashboard:

https://mysite.com/index.php?route=checkout/success
https://mysite.com/index.php?route=checkout/failure

my site runs on a vps server with litespeed enabled
Thanks

**Comment by krinis11** [comment]
i have the same problem. any solution???

**Comment by jkmagic1** [comment]
Έλληνας?
Οχι φιλε μου σημερα το ανεβασα και περιμενω απαντηση

**Comment by krinis11** [comment]
Έλληνας ναι!!! Το έκανα εγκατάσταση και ενώ λειτουργεί κομπλέ όσο αφορά την μεταφορά χρημάτων από την κάρτα στο vivawallet, η παραγγελία στο site φαίνεται ακυρωμένη ενώ από τις επιλογές έχω βάλει να γίνετε "Σε επεξεργασία".

**Comment by jkmagic1** [comment]
Το ιδιο ακριβως και σε μένα

**Comment by krinis11** [comment]
για να δουμε θα απαντησουν??? διαβασα τον κώδικα και ενω πρεπει να δημιουργήσει πίνακα στην βάση δεν τον βλέπω μεσα και μονο εκει βρήκα την επιλογη για το statu order το οποιο ειναι default για να το αλλαζα μονιμα να ειναι σε επεξεργασια. εαν δεν απαντησουν θα πρεπει να κανω δοκιμε σε xampp μπας και βρω λύση.

**Comment by krinis11** [comment]
εχω 3 ωρες που ψάχνω μήπως εχουν γραψει και πουθενα αλλου καμια λύση αλλα δεν βρήκα τιποτα.

**Comment by jkmagic1** [comment]
Εγω το ψαχνω μερες και σημερα εφαγα φλασιά να το ανεβασω μηπως και βρεθει λύση

**Comment by can3ry** [comment]
Hello @krinis11 @jkmagic1 
Let us check this and get back to you. 
In the meantime, could you give more details about the problem? When did this started to happen? 
Could you also share your merchant id? 
@krinis11 What is your OpenCart version?
Best regards,
Viva Wallet Development Team

**Comment by krinis11** [comment]
my opencart version is 2.2.0.0

**Comment by jkmagic1** [comment]
merchant id:
4044a04f-63bb-4d5f-9292-66c4a0fe1a6c
The problem strarted from the first day in Vivawallet some months ago.

**Comment by can3ry** [comment]
Thanks for the details.

@krinis11  Could you inform me about the plugin source you use? Did you download it from [this link](https://github.com/VivaPayments/API/tree/master/Plugins/opencart/OpenCart%202.0%20-%202.1%20-%202.2)? 

Could you shortly describe the flow so we can try to reproduce it?

From the comments, I understand that some transactions are being directly marked as canceled on the admin panel of OpenCart. Does the customer get a fail message?

Best regards,
Viva Wallet Development Team

**Comment by krinis11** [comment]
merchant id:
92fb984e-0769-4309-b795-50725af77e8c

yes i download it from the link where you sent me.
customer doesnt get fail message.

i have select "Processed Status: in processing" to the vivawallet payments options.
when the payment process is completed, I can see the money in my vivawallet account but in the opencart control center on orders the order seems canceled while it should appear in "in process" status

**Comment by jkmagic1** [comment]
the same for me too

**Comment by can3ry** [comment]
Hi @jkmagic1 
I've passed this to engineers. 
Please give us some time to investigate, and we'll respond as soon as possible.
Best regards,
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hello @jkmagic1 
We've made a test on OpenCart v3.0.3.2, and the payment status is correctly shown. 
Our plugin uses OpenCart statuses, and if the payment is successful, it updates the order status as per the value you set on the Viva Wallet extension configuration page. The configurations are stored in the settings table, and you may check the current value and compare it with OpenCart statuses. 

**Viva Wallet Processed Status Id**  {TABLE_PREFIX}.setting
<img width="542" alt="Viva-Status" src="https://user-images.githubusercontent.com/51880555/166225997-39f9842a-07b4-42c7-a2b2-d2ce52cef4ac.png">

**OpenCart Order Status Ids**  {TABLE_PREFIX}.order_status
<img width="674" alt="OpenCart-status" src="https://user-images.githubusercontent.com/51880555/166226217-e9bb8d2e-3e81-4ac8-95fb-2c1b1fd60bd6.png">

Kindly check your database to see if there is a mismatch with the statuses. Please note it is possible our plugin is not compatible with the specific theme or plugins you're using. So I would recommend you to check with a developer for further updates.

**Please do not share any confidential information here.**

Hello @krinis11 
I've checked your source code(redirect URLs), and it seems they are not valid. 
Could you create [a new source code](https://developer.vivawallet.com/getting-started/create-a-payment-source/payment-source-for-online-payments/) and set the redirect URLs below? Kindly make the changes to your demo environment first and make all necessary tests before going live. 
**Note: The below URLs are for [our old plugin](https://github.com/VivaPayments/API/tree/master/Plugins/opencart/OpenCart%202.0%20-%202.1%20-%202.2) only** 

**Success url:**  index.php?route=payment/vivawallet/callback&success
**Fail url:**  index.php?route=payment/vivawallet/callback&fail

Best regards,
Viva Wallet Development Team

**Comment by jkmagic1** [comment]
I have checked the data base and its the same with your images.
So it must be the theme or the server
I use Journal3 and the server is litespeed

**Comment by krinis11** [comment]
i changed the urls 
i used Success url: https://mysite/index.php?route=checkout/success
Fail url: https://mysite/index.php?route=checkout/failure

but i still have the same problem

**Comment by krinis11** [comment]
I fixed the problem.

Viva defaults urls was:
Success path: index.php?route=payment/vivawallet/callback&success
Fail path: index.php?route=payment/vivawallet/callback&fail
 
Mine was:
Success url: https://mysite/index.php?route=checkout/success
Fail url: https://mysite/index.php?route=checkout/failure

I change the urls:
Success path: index.php?route=extension/payment/vivawallet/callback&success
Fail path: index.php?route=extension/payment/vivawallet/callback&fail

it works perfectly

**Comment by can3ry** [comment]
Hi @krinis11  I am glad to hear that you have sorted it out. So I understand that you use our newest plugin. Please let us know if you need further assistance.

Hi @jkmagic1 could you also set the Success/Fail URLs as mentioned below and let us know the result?

Success path: index.php?route=extension/payment/vivawallet/callback&success
Fail path: index.php?route=extension/payment/vivawallet/callback&fail

Changing a value from DB can cause other problems, so I recommend you work with a developer and make all changes to your sandbox first to ensure that your system is set up correctly. 

Best regards,
Viva Wallet Development Team

**Comment by krinis11** [comment]
I'm okay!!!  thank you for your help!!!

**Comment by can3ry** [comment]
Hi @jkmagic1 
I am closing the ticket for now. Please feel free to add a comment when you have an update. So we can re-open it.
Best regards,
Viva Wallet Development Team
