### ISSUE TITLE
Αυτόματη επιστροφή μετά την πληρωμή

### ISSUE THREAD

**Issue by malexandrakis** [VivaPayments/API#217]
Γεια χαρά,

Θα ήθελα μετά την πληρωμή να γίνεται αυτόματα επιστροφή στο ηλεκτρονικό κατάστημα. Υπάρχει κάποια παράμετρος για να γίνει αυτό;

Ευχαριστώ

**Comment by dmihos** [comment]
Καλημέρα σας
Μπορείτε να ορίσετε το url του site σας στην πηγή πληρωμής που χρησιμοποιείτε (menu>Οι πωλήσεις μου>Πηγές πληρωμών)

**Comment by xargr** [comment]
Με από το διαχειριστικό της vivapayment ορίζεις success URL και false URL
