### ISSUE TITLE
Cancel unpaid payment

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2170]
Hi,

Same question as https://github.com/VivaPayments/API/issues/2129.

How can I cancel a payment started with `/checkout/v2/orders` if it hasn't been paid yet?

The provided answer is to chat with the support but chat doesn't let me ask **technical** questions.

I want to make sure the customer doesn't pay the payment after changing his mind and canceling or updating the order on our side.

**Comment by fmarchalemisys** [comment]
Hi can3ry,

Thank you for your answer.

The deprecated v1 api provides all the features lacking in v2!

Regarding v2, there is another reason preventing me from using it. Maybe you can enlighten me.

`/checkout/v2/orders` returns an `OrderCode` but it can't be used to query the payment status as `/checkout/v2/transactions/{transactionId}` expects a `TransactionId`.

The `TransactionId` is only available after the customer returns to our website or the webhook is correctly configured and working. This is far too unreliable. It looks like a design flaw.

Am I missing something?

**Comment by can3ry** [comment]
Hi @fmarchalemisys 
Thanks for your query.
An order code can have multiple transactions, so we use transaction id to get the details of å specific payment.
However, you can also check the status of the order code. Please see [this link ](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments-(Deprecated)/paths/~1api~1orders~1{orderCode}/get)for getting order code details.

Please also note that the MerchantTrns parameter can be used for flagging a payment on your side. So whenever you get details of a transaction/order, you can match them on your side.  This parameter is set with [create payment](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post) order request and available on both in the responses of [retrieve transaction](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions/paths/~1checkout~1v2~1transactions~1{transactionId}/get) and  [retrieve order ](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments-(Deprecated)/paths/~1api~1orders~1{orderCode}/get) calls.
Please let us know if you need further clarifications.

Best regards,
Viva Wallet Development Team

**Comment by fmarchalemisys** [comment]
Hi can3ry,

You fully answered my questions. I now have all the information I need.

Thank you.
