### ISSUE TITLE
Error: input is invalid - VivaWallet Shopify Integration 

### ISSUE THREAD

**Issue by aasghar551** [VivaPayments/API#2171]
I am trying to connect vivawallet into Shopify store but getting invalid input error on checkout page.

I have set correct vivawallet Client ID and Client Secret keys into Shopify. I followed the vivawallet integration documentation and all settings are correct but always getting the invalid input error.

Please help me to fix this issue ASAP. We have to run campaign and a lot of stress on us.

Website URL is: https://annonpet.it/

![vivawallet](https://user-images.githubusercontent.com/23654213/167177538-3ce3ff6e-8ade-4687-96d9-1371a0f279eb.png)

**Comment by can3ry** [comment]
Hi @aasghar551,
We are checking this with high priority and will release a fix soon.
I am keeping this ticket open and will update you shortly.
Sorry for the inconvenience.
Best regards,
Viva Wallet Development Team

**Comment by aasghar551** [comment]
I will be waiting to hear from you.

**Comment by aasghar551** [comment]
Is there any update please? Our customers are waiting and we are unable to open campaign due to vivawallet issue.

**Comment by can3ry** [comment]
Hello @aasghar551
We've released a new version of Shopify.
Could you remove the old plugin and install the new one as per the instructions on [this page](https://developer.vivawallet.com/plugins/shopify/)?
Best regards,
Viva Wallet Development Team

**Comment by aasghar551** [comment]
I have installed the updated Shopify plugin and it seems to working well, will make some transactions and then confirm.

Thank you for helping me out there.

Regards,
Ahmed Asghar
