### ISSUE TITLE
[452 Status] - (Marketplace) Transferring fees & payouts between Demo accounts.

### ISSUE THREAD

**Issue by ColudioS** [VivaPayments/API#2174]
Hello,

I'm creating a Woocommerce custom Viva Wallet payment gateway plugin for marketplaces, and I'm currently testing everything under the demo environment. The transaction is being created successfully (both on demo viva wallet and the woocommerce order update), but when it comes to transferring the fees from the marketplace (platform) account to the marketplace owner account, I get a status = 452 Unknown. I've already enabled the transfers between accounts through Viva Settings as stated [here](https://developer.vivawallet.com/apis-for-payments/wallet-api/#1-balance-transfer). With a quick search through the Closed Issues, I found that 452 status possibly means "Insufficient Funds". When I'm checking the demo platform account, the transaction is visible under the "Online Transactions" tab, but the balance of the account is still 0. Is this the cause of the problem? If it is, how can I add the money received through the transaction into the balance so the transfer can actually happen? 

Thank you a lot for your time.

**Comment by can3ry** [comment]
Hi  @ColudioS 

Thank you for your query.

Yes, the 452 error code means that the wallet has insufficient funds. Could you provide the merchant id of your platform account? 

We'll add balance.

Best regards
Viva Wallet Development Team

**Comment by ColudioS** [comment]
Hello @can3ry 

Thank you for your reply! This is the Merchant ID of the platform account: 91d048de-6079-481e-ad5a-62f80a644eb2

Best regards.

**Comment by can3ry** [comment]
Hi @ColudioS 

We have added funds to your account.

Please do not hesitate to raise a new ticket if you need further assistance.

Best regards
Viva Wallet Development Team

**Comment by ColudioS** [comment]
Hello again! 

Now that the balance exists, I'm not getting that response code anymore. However, when I'm trying to make a balance transfer, I'm getting the response code 403 Forbidden. Searching for it in the [documentation of the API](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Balance-Transfer) it says that this error means "The amount is zero or is null or is missing.". However on my request, the amount **isn't** zero, null or missing. 

![image](https://user-images.githubusercontent.com/45774211/169506729-e57bfe24-66d7-4f05-87ce-0dfb59bad20f.png)
