### ISSUE TITLE
Viva Wallet simple checkout

### ISSUE THREAD

**Issue by Cristinawork** [VivaPayments/API#2175]
Is Viva Wallet simple checkout still alive?
Or only the new Smart checkout?

**Comment by can3ry** [comment]
Hi @Cristinawork 

Simple checkout is retired. Instead, we provide the Smart Checkout solution, which offers the widest variety of payment options and overall features.

For more information about Smart Checkout, please visit our [developer portal](https://developer.vivawallet.com/smart-checkout/).

Thanks
Viva Wallet Development Team
