### ISSUE TITLE
403 Forbidden - Balance Transfer API

### ISSUE THREAD

**Issue by ColudioS** [VivaPayments/API#2178]
Hello again! 

This thread is a follow-up to [this closed thread](https://github.com/VivaPayments/API/issues/2174).

Now that the balance exists, I'm not getting that response code anymore. However, when I'm trying to make a balance transfer on the demo environment, I'm getting the response code 403 Forbidden. Searching for it in the [documentation of the API](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Balance-Transfer) it says that this error means "The amount is zero or is null or is missing.". However on my request, the amount **isn't** zero, null or missing. 

![image](https://user-images.githubusercontent.com/45774211/169506729-e57bfe24-66d7-4f05-87ce-0dfb59bad20f.png)

Thank you a lot for your time once again,
Best regards.

**Comment by can3ry** [comment]
Hello @ColudioS 

Possible reasons for this error,

- There is no role for the merchant (your account has the necessary roles✅ )
- There is a currency mismatch between the wallets (Please make sure that the wallets are in the same currency❓)
- The Wallet does not belong to the merchant (Please make sure that the wallet belongs to the merchant ❓)
- Amount <= 0  (You set it correctly ✅ )

Could you also provide the X-Viva-CorrelationId information from the response headers?

Thanks

**Comment by ColudioS** [comment]
Hello again @can3ry,

First of all, thank you for your fast reply. 
- The two wallets have the same currency indicated in each wallet's balance (€). 
- The transaction I'm trying to make is from the Platform Account to the Marketplace Owner Personal Account (so from the blue account to the orange in the Demo Environment)
![image](https://user-images.githubusercontent.com/45774211/169516646-f833b350-a358-4993-91ae-bcb5f8c701d5.png)

Also the X-Viva-CorrelationId is this: 22-140-9C33BA14

Best regards.

**Comment by can3ry** [comment]
Hi @ColudioS 
Kindly note that the targeted account should not be a personal account. This is valid for the marketplace scheme. So, please create a new business account and use it as a marketplace account.

Please also share the merchant id when you create it.

Best regards
Viva Wallet Development Team

**Comment by ColudioS** [comment]
Hello again @can3ry ,

I just retried the request -without changing anything at all-, and it worked on the personal account. I'll test it out with a new business account as you told me to see if it works to that one as well. 

Best regards.

**Comment by can3ry** [comment]
Hi @ColudioS 
Yes, all the vendors(the sellers) should have a business account. 
If you require any further information please feel free to let us know.
Best regards
Viva Wallet Development Team
