### ISSUE TITLE
Problema ricezione status pagamento

### ISSUE THREAD

**Issue by MarcoEndesa** [VivaPayments/API#2179]
Gentilissimi,
stiamo implementando VivaWallet sulla nostra piattaforma custom utilizzando le istruzione SmartCheckout e ci siamo interfacciati con le procedure di generazione oAuth2, generazione orderCode e successiva chiamata alla URL della vostra pagina di pagamento.
Abbiamo attivato un conto DEMO e con quelle credenziali stiamo operando tutti i test.
Abbiamo effettuato stamattina una prova utilizzando una delle card di test (esattamente la 2' VISA con numero 4147 4630 1111 0141) e ci aspettavamo di ricevere un KO come esito.
Il webhook che abbiamo ricevuto, invece, ha il campo "StatusId" valorizzato a "F" nonostante abbiamo utilizzato una carta che avrebbe dovuto produrre un FAILED.
Alleghiamo:
- identificativo del numero di carta utilizzato:

![Schermata 2022-05-25 alle 12 28 12](https://user-images.githubusercontent.com/106250044/170265864-eb919daf-6c18-4db1-8254-1399ea19b9b7.png)

- webhook ricevuto con StatusId = F:

[webhook.txt](https://github.com/VivaPayments/API/files/8771245/webhook.txt)

Potete aiutarci a capire come intercettare correttamente l'esito della transazione?
Grazie
Marco

**Comment by can3ry** [comment]
Hi @MarcoEndesa 

Thanks for raising this issue.

We've noticed an issue with some of the test cards. The payment attempt you made was unexpectedly successful. That's why you got a payment-created notification with status id F. We are investigating possible reasons and will fix it as soon as possible.

In the meantime, the below card should work for you. Could you try it and let us know the result?

Bancontact card number: 6060 0500 0000 00148
Expire date: 11/22

Thanks
Viva Wallet Development Team

**Comment by MarcoEndesa** [comment]
Buongiorno,
abbiamo fatto una prova con la carta di test che ci avete comunicato:
- Bancontact card number: 6060 0500 0000 00148
- Expire date: 11/22
e questa volta non abbiamo ricevuto alcuno webhook. Non so se questo è normale perché ci saremmo aspettati di ricevere un webhook con StatusId = E o qualsiasi altro status tranne la F.
Attendiamo riscontro
Grazie per il supporto

**Comment by can3ry** [comment]
Hello  @MarcoEndesa 

Was the payment successful?

If you set a [transaction-fail webhook](https://developer.vivawallet.com/webhooks-for-payments/transaction-failed), you get a notification with a statusId=E for failed payments.

Could you provide your demo merchant Id, please?

Thanks
Viva Wallet Development Team

**Comment by MarcoEndesa** [comment]
Avete ragione, avevo inserito la chiamata al webhook solo per TRANSAZIONE OK.
Sto provando ad aggiungere un nuovo webhook per TRANSAZIONE KO ma la verifica della URL fallisce (nonostante sia lo stesso identico indirizzo del webhook ok).
Il marchandId demo è il seguente: 3b0376c6-ecf8-4a0b-bb0e-be4ea786afc0
Grazie

**Comment by can3ry** [comment]
Hi @MarcoEndesa 

It seems your webhook URL does not print the verification key. Before verifying the webhook on [self-care](https://demo.vivapayments.com/en/signin), please make sure that your web URL is showing the JSON structure as mentioned on [this page](https://developer.vivawallet.com/webhooks-for-payments/setting-up-webhooks/#response-example). The content type should be application/JSON. 

```
{
  "Key":"YOUR-ACCOUNT-KEY"
}
```

We are also checking the test cards and will give you an update soon.

Thanks
Viva Wallet Development Team

**Comment by MarcoEndesa** [comment]
Gentilissimi,
abbiamo impostato il webhook per l'esito KO e con la carta Bancontact card number: 6060 0500 0000 00148 (Expire date: 11/22) funziona tutto correttamente (StatusId = E).
Se invece utilizziamo le carte FAILED della seguente pagina (https://developer.vivawallet.com/integration-reference/test-cards-and-environments/) otteniamo in risposta StatusId = F.
L'instabilità del sistema ci preoccupa molto.
Attendiamo un vostro riscontro per essere sicuri che attivando il sistema, la vostra piattaforma non ci risponda con dei falsi positivi e vendiamo servizi in realtà non pagati.
Buon lavoro
Marco

**Comment by cforrestvivawallet** [comment]
Hi @MarcoEndesa,

My apologies for the issues you have faced. Please try the following two cards which - in my testing - provided the correct 'failed' response:

- 3670 010200 0000
- 3528 1111 1111 11119

However, please note that our test cards are provided by a partner and occasionally face issues due to upgrades and maintenance, etc., and so we cannot guarantee they will work correctly all of the time.

Regardless of our test cards, I can confirm these issues are _not_ related to Viva Wallet's platform or services, and so you will _not_ face these same issues in your production environment with real cards.

Please let us know if you need any further help.

Kind regards,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
HI @MarcoEndesa,

Please try (or retry) the VISA Failed card listed on our Developer portal:
- 4147 4630 1111 0141

Alternatively, please try this card - **with a specific order value of €99.05** - which should simulate an issuer decline:
- 4147 4630 1111 0133

I have just tested these cards and both took me to the failure URL as expected (within the Demo environment of course).

Please let me know if you get the same result.

Kind regards,
Viva Wallet Development Team

**Comment by MarcoEndesa** [comment]
Grazie per l'assistenza.
Una ultima domanda (forse ...): non siamo riusciti a trovare una API per avere una lista delle transazioni OK in un determinato periodo. Esiste questa funzione?
Grazie
Marco

**Comment by cforrestvivawallet** [comment]
Hi @MarcoEndesa,

You can use the 'deprecated' Retrieve Transaction API ([found here](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)/paths/~1api~1transactions~1{id}/get)) to find a list of transactions for a given date - although this is deprecated, it is still fully functional and you are free to use it.

Simply append the date query parameter - e.g: ?date=2018-08-27

Please let me know if there is anything else I can help with.

Kind regards,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
Hi,

We are closing this issue now, but please don't hesitate to get in touch if there is anything else we can help with.

Kind regards,
Viva Wallet Development Team
