### ISSUE TITLE
woocommerce

### ISSUE THREAD

**Issue by gatenet** [VivaPayments/API#218]
χρησιμοποιώ το woocommerce για eshop και έχω βρει ένα plugin για να εγκαταστήσω. είναι σωστο?

**Comment by krakenrules** [comment]
Καλημέρα,

Τα plugins τα οποία έχουν αναπτυχθεί για το woocommerce, είναι από ανεξάρτητους developers και δεν παρέχεται κάποια επίσημη υποστήριξη από τη Viva.

Για τυχόν πληροφορίες/απορίες, θα πρέπει να επικοινωνήσετε με τον εκάστοτε developer του plugin.

Ευχαριστούμε πολύ για την επικοινωνία
