### ISSUE TITLE
Συνυπολογισμός χρεώσεων στο ποσό πληρωμής

### ISSUE THREAD

**Issue by appartment** [VivaPayments/API#2181]
Καλησπέρα, υπάρχει τρόπος στο smart checkout να χρεώνεται ο πελάτης για τα fees της συναλλαγής?

Ευχαριστώ

**Comment by cforrestvivawallet** [comment]
Thanks for your query.

I can confirm there is _not_ a way to pass on transaction fees to the customer within Smart Checkout.

Please let us know if there is anything else we can help with.

Kind regards,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
Hi,

We are closing this issue now, but please don't hesitate to get in touch if there is anything else we can help with.

Kind regards,
Viva Wallet Development Team
