### ISSUE TITLE
Demo environment balance transfer Returns 403

### ISSUE THREAD

**Issue by ngoun** [VivaPayments/API#2184]
Demo environment balance transfer Returns 403
POST TO 
https://demo.vivapayments.com/api/wallets/{FROM_A}/balancetransfer/{TO_B}

Balance transfer between accounts is ENABLED

**Comment by can3ry** [comment]
Hi @ngoun 

Thank you for your query.

As stated [here](https://github.com/VivaPayments/API/issues/2178#issuecomment-1132753205), could you provide the X-Viva-CorrelationId value you get in the response header? 

Best regards
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
Hi @ngoun,

As mentioned previously, if this issue is still occurring, please provide the X-Viva-CorrelationId.

If this issue is no longer occurring, please let me know.

Kind regards,
Viva Wallet Development Team

**Comment by ngoun** [comment]
Problem still occurs:
X-Viva-CorrelationId : 22-151-B1CCCEF0
MercID: aed2230d-6897-43d1-b884-a82094f9a95c

**Comment by ngoun** [comment]
```
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://demo.vivapayments.com/api/wallets/819293881279/balancetransfer/985409664941',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
 "amount": 1000
 }',
  CURLOPT_HTTPHEADER => array(
    'Authorization: Basic ###########REMOVED############',
    'Content-Type: application/json'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;

```

**X-Viva-CorrelationId: 22-151-379EEC8A**

**Comment by cforrestvivawallet** [comment]
Hi @ngoun - thanks very much for providing that information.

I have made a small change to the permissions on your demo account.

Could you please retry this balance transfer and let me know if the issue is resolved?

Kind regards,
Viva Wallet Development Team

**Comment by ngoun** [comment]
Hi @cforrestvivawallet 
Now seems to work !
Was it something I could have done? (for future reference)

**Comment by cforrestvivawallet** [comment]
Hi @ngoun,

I'm glad to hear it is now working!

No, this was something on the back-end to which you do not have access - my apologies for the inconvenience.

Is there anything else I can help you with or are you happy for me to close this GitHub issue now?

Kind regards,
Viva Wallet Development Team
