### ISSUE TITLE
Samsung Pay is not working in test enviroment

### ISSUE THREAD

**Issue by tetianaDotcom** [VivaPayments/API#2189]
We are integrating viva wallet payment method to our eccomerce website (https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/). In particular we are interested in Samsung Pay payment method. Currently we are testing our integration (we are using demo/sandbox account), everything works correctly, apart the Samsung Pay payment method. Unfortunately, while we press the button 'Pay with Samsung Pay' we receive an error 'The Transaction Failed'. We use your test enviroment and Nexi card that is enabled for test of Samsung Pay.

**Comment by gemitsio** [comment]
Hello @tetianaDotcom,

Thank you for your post.

Please provide your merchant id.

Sincerely,
Viva Wallet Development Team

**Comment by tetianaDotcom** [comment]
Hello @gemitsio,
this is our merchant Id = fa3085ac-ad7e-4ada-a7b5-e0fa106f822d

**Comment by gemitsio** [comment]
Hello @tetianaDotcom,

can you retry executing the case please? 

Just for your info, we reproduce the issue on demo and seems that works successfully.

https://user-images.githubusercontent.com/91877364/174773160-b195e09d-d553-4d14-883c-c8c7e5c7179b.MP4

 Sincerely,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
Hi @tetianaDotcom,

We are closing this issue now, but please do not hesitate to let us know if you have any further problems with this, or with any other topics.

Kind regards,
Viva Wallet Development Team
