### ISSUE TITLE
Mobile API payment Android

### ISSUE THREAD

**Issue by methadoni** [VivaPayments/API#219]
Καλησπέρα, 

Προσπαθώ να χρησιμοποιήσω το mobile api για πληρωμή από android app αλλά δεν καταλαβαίνω πως ακριβώς μπαίνει το authentication στο header. 
Χρησιμοποιώ Volley library για τα Request.
Υπάρχει κάποιο παράδειγμα για Android; Έχω δει μόνο για ios.  
Ευχαριστώ.

**Comment by defilerc** [comment]
Καλησπέρα @methadoni ,

Θα πρέπει να ψάξετε πως γίνεται Basic Authentication με τη βιβλιοθήκη Volley Library που χρησιμοποιείτε.

Δείτε μήπως σας βοηθάει η συγκεκριμένη σελίδα: http://stackoverflow.com/questions/16817980/how-does-one-use-basic-authentication-with-volley-on-android

Τα username/password που θα χρησιμοποιήσετε είναι τα merchant id και το api key σας αντίστοιχα.

Με εκτίμηση,

**Comment by methadoni** [comment]
Ευχαριστώ για την απάντηση αλλά το παράδειγμα είναι παλιό ελλιπές και έχει κάποια προβλήματα. 
Το έχω δει αυτό και έχω δοκιμάσει διάφορα άλλα για basic authentication αλλά δε μου λειτουργούν γι αυτό και ζήτησα παράδειγμα. Αν υπάρχει κάτι έτοιμο εκτός από volley θα ήταν πολύ χρήσιμο.
