### ISSUE TITLE
Can't login to my account

### ISSUE THREAD

**Issue by antonisfot** [VivaPayments/API#2192]
When trying to connect to my account i receive an error message saying to try again but nothing happened. This is going for a month now.

**Comment by cforrestvivawallet** [comment]
Hi @antonisfot, 

In order for us to investigate further, could you please confirm:

1. What account are you referring to (Demo, Production, etc.)?
2. What process are you using to connect/login to your account?
3. What is your Merchant ID or the phone number linked to your account?

Kind regards,
Viva Wallet Development Team

**Comment by vaskou** [comment]
I have a similar problem.
I want to login in my demo account, I fill my mobile phone and password and then I never get the SMS to my phone.

**Comment by cforrestvivawallet** [comment]
We will be closing out this issue now, but please do not hesitate to let us know if there is anything else we can assist with.

Kind regards,
Viva Wallet Development Team
