### ISSUE TITLE
Payment order returned but does not exist on redirect

### ISSUE THREAD

**Issue by appartment** [VivaPayments/API#2197]
Hello, I was trying to test some payment failures on the demo env but I stumbled upon an issue where I was getting the orderCode but when redirecting there was a message saying that the orderCode does not exist

```
OrderCodes: [9948100551072600, 9590609433472608]
Env: demo
MerchantId: 1788ee76-e6d0-4172-b05e-94edffa85296
```

These orders do not exist on the demo.vivapayments.com portal and the response I get when calling the API endpoint is 
```
https://demo.vivapayments.com/api/transactions/?ordercode=9948100551072600
{
    "Transactions": [],
    "ErrorCode": 0,
    "ErrorText": null,
    "TimeStamp": "2022-06-20T17:06:31.9015316+03:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": true
}
```

**Comment by cforrestvivawallet** [comment]
Hi @appartment,

I have taken a look in the system and I can't see those order codes either.

1. Are you able to confirm if this issue exists **every** time you create an orderCode, or just in certain instances?
2. Additionally, please could you outline the process you are using to create these orderCodes?

Kind regards,
Viva Wallet Development Team

**Comment by appartment** [comment]
Hello @cforrestvivawallet 

1. It randomly happens. When I retry with the same data (same amount same customer) it goes through
2. I follow the steps below
- I generate an auth token
- I post the data to /checkout/v2/orders
- I get the orderCode
- I persist the orderCode in my DB
- I redirect to https://demo.vivapayments.com/web/checkout?ref={ORDER_CODE}&color=313896

**Comment by cforrestvivawallet** [comment]
Hi @appartment,

I wanted to provide an update on this particular issue.

After further internal discussion, it seems that the order codes you have mentioned above (9948100551072600 & 9590609433472608) may be running into a limitation of JavaScript, which occurs across all browsers.

These orderCode values are both above JavaScript's **[MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)** value of 9,007,199,254,740,991.

If these values are stored as numbers and then passed to the redirect URL, the values essentially become 'changed', leading to the incorrect orderCode being called. To rectify this, we would recommend ensuring these values are stored as **strings**, which should preserve the correct values when passed to the redirect.

Please let us know if you have any further questions or issues.

Kind regards,
Viva Wallet Development Team

**Comment by appartment** [comment]
Hello @cforrestvivawallet thanks for the response. It is stored as string but I use whatever it is returned from the response and from what I remember the create payment order returns it as a number
```
{
  "orderCode": 7568594363572609
}
```

Is it possible that the error happens before I receive the orderCode?

**Comment by appartment** [comment]
Ok this didn't take long :) 

I was trying again and I created an order with code `{ orderCode: 9855227595272608 }`. This is exactly what I got from the endpoint in my logs and I was redirected properly on https://demo.vivapayments.com/web2?ref=9855227595272608&color=313896 and I stored the correct value in my DB.

Any ideas?

**Comment by cforrestvivawallet** [comment]
Hi @appartment, 

Correct me if I am wrong, but it looks as though everything worked correctly in this instance. If you were to store this orderCode as a String within your database and then pass this String when redirecting to Smart Checkout, the orderCode should remain unchanged.

My apologies, but can you confirm what issue you are still facing with the above?

Kind regards,
Viva Wallet Development Team

**Comment by appartment** [comment]
I haven't changed anything I handled the orderCode in the exact same manner (Since I am not doing anything with the orderCode apart from just propagating it) it seems that the order codes that I wasn't able to retrieve before are indeed not present and it's not some kind of int handling issue.
