### ISSUE TITLE
Using test cards - 3DS challenge flow - unpredictable

### ISSUE THREAD

**Issue by NikosTsesmelis** [VivaPayments/API#2198]
We are using the 3DS challenge flow to test the 3ds functionality of our app but it is not very reliable. Most of the time it works as intended but sometimes it simply returns as success and doesn't return the html with the choices. It usually starts working again after some time but makes testing difficult. Is this some expected behaviour (happening during deployment for example) that we can document so that we know what to expect?

**Comment by appartment** [comment]
I can also verify this behavior and it happens with most test cards every now and then.

```
OrderCode: 3528851377372601
TransactionId: 224d41f5-7fb1-4b70-aad4-b29b56ac96b9
Amount: 90,05 EUR
Card: 414746XXXXXX0133
```
As per the documentation should fail with issuer decline https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#trigger-an-issuer-decline

However I got
```
Issuer authorization code (AID): 074982
```

Also when it actually fails the errorCode is different and instead of 10005 I get 2062

**Comment by cforrestvivawallet** [comment]
Hi both,

@NikosTsesmelis, we do sometimes have instability within the Demo environment, which can indeed be related to deployments. However, in the case of 3DS issues, we actually utilise test cards configured by a third-party, meaning we could face intermittent issues when they are carrying out updates or maintenance on their side. As such, we unfortunately cannot predict when these intermittent issues might occur.

@appartment, regarding your specific example, I can see you have made a payment for 90,05 EUR. Instead, to trigger an issuer decline you will need to use the amount of 99,05 EUR.

Please let us know if you face any further specific issues and we would be happy to help.

Kind regards,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
We will be closing out this issue now, but please do not hesitate to let us know if there is anything else we can assist with.

Kind regards,
Viva Wallet Development Team
