### ISSUE TITLE
Αποτυχία συναλλαγής

### ISSUE THREAD

**Issue by ETltd** [VivaPayments/API#220]
Καλησπέρα. Εχουμε πάρει εγγριση για το website (domain) / viva λογαριασμό.
Φτιάξαμε το button από το viva payment panel, copy τον κωδικό, και αν δείτε το κουμπί "χτυπάει" (εικαστικά). Οταν το πατάς λαμβάνεις το error αποτυχίας.
Επισυνάπτω links με printscreens

https://gyazo.com/dec36ee0a829c20c90df139f41ff94b3
https://gyazo.com/e61120c2815490cbd1104020e2865c04

**Comment by ETltd** [comment]
Καλησπέρα και χρόνια πολλά. Το βλέπει κάποιος το support;

**Comment by defilerc** [comment]
Καλημέρα @ETltd ,

Μπορείτε να μας στείλετε το merchant id σας, για να δούμε τι έχει συμβεί;

Με εκτίμηση,

**Comment by ETltd** [comment]
Καλημέρα σας.
| e5aa9f2c-cd80-4562-bc3e-339134b24ea5 |
|



 

    On Tuesday, December 27, 2016 10:05 AM, Konstantinos Athanasoglou <notifications@github.com> wrote:
 

 Καλημέρα @ETltd ,Μπορείτε να μας στείλετε το merchant id σας, για να δούμε τι έχει συμβεί;Με εκτίμηση,—

**Comment by defilerc** [comment]
Μπορείτε να μας στείλετε το URL που παράγεται όταν πατάτε πάνω στο κουμπί "Επισκόπηση" στο κουμπί πληρωμών που έχετε φτιάξει; (μενού Οι Πωλήσεις μου -> Κουμπιά Πληρωμών)

**Comment by ETltd** [comment]
Η προεπισκόπηση λειτουργεί πάντως κανονικά
https://www.vivapayments.com/web/buybutton/default.aspx?lang=el-GR&productid=98436316-d669-41ca-99dc-343824fda9f2&key=xao516ExlyMXrQ4MEHV6AFev1gEgBEWWGhKcVr2C9TQ%3d

**Comment by defilerc** [comment]
Θα πρέπει να βεβαιωθείτε ότι τρέχει σωστά ο κώδικας javascript που υπάρχει στη σελίδα σας, καθώς θα πρέπει να γίνεται ανακατεύθυνση σε URL της μορφής:

`https://www.vivapayments.com/web/buybutton/default.aspx?lang=el-GR&productid=ΧΧΧ&key=ΧΧΧ`

οπού μετά το URL `https://www.vivapayments.com/web/buybutton/default.aspx` ακολουθούν οι παράμετροι `productid` και `key`. Το URL στο screenshot που μας έχετε στείλει δεν περιέχει αυτές τις παραμέτρους, γι' αυτό και παίρνετε το συγκεκριμένο μήνυμα λάθους.

Παρακαλώ πολύ δείτε αν εμφανίζονται μηνύματα λάθους στο browser console και βεβαιωθείτε ότι ο κώδικας javascript για το κουμπί πληρωμής τρέχει από τη σελίδα σας.

Με εκτίμηση,

**Comment by ETltd** [comment]
Να το δω

**Comment by ETltd** [comment]
Δεν βρίσκω κάποιο πρόβλημα. Μπορείτε να το δείτε εσείς στην σελίδα μας; Ο κώδικάς γίνεται paste όπως είναι.

**Comment by defilerc** [comment]
Ποιό είναι το URL?

**Comment by ETltd** [comment]
http://www.yellowpin.gr/buy-now/

**Comment by defilerc** [comment]
Καλησπέρα,

Η σελίδα σας βγάζει errors: 

![image](https://cloud.githubusercontent.com/assets/1667459/21497643/257485e8-cc2f-11e6-8cc3-5c324e4554ff.png)

κάποιοι χαρακτήρες δεν έχουν γίνει paste σωστά και έχουν γίνει url encoded. το: `vivapayments.widgets = vivapayments.widgets || [];` έχει γίνει σε σας:
`vivapayments.widgets = vivapayments.widgets || &#091;&#093;;`

Θα σας προτείναμε να τοποθετήσετε το συγκεκριμένο `<script>` της vivapayments, μαζί με τα υπόλοιπα `<script>` tags που έχετε στο τέλος της σελίδας και να επιβεβαιώσετε ότι είναι ίδιο με αυτό που σας δίνουμε.

Με εκτίμηση,

**Comment by ETltd** [comment]
Μάλιστα. Τελικά θέλει Entry από script editor και οχι text editor. Με τον script editor Το δεχεται κανονικα.
Ευχαριστώ πολύ
