### ISSUE TITLE
Viva Wallet Deprecated API methods

### ISSUE THREAD

**Issue by viderspan** [VivaPayments/API#2200]
Dear Support,

I would like to ask what does mean exactly that some API method is Deprecated?

https://developer.vivawallet.com/apis-for-payments/payment-api/

I haven't found alternative solutions to many deprecated functions but I should have to use them.
How will the deprecated API methods be handled?
How long can they be used?
What will happen if I use them?
May I use the deprecated Retrieve methods to the Smart Checkout?

https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments-(Deprecated)/paths/~1api~1orders~1{orderCode}/get
https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)/paths/~1api~1transactions~1{id}/get

Thank you.

Best regards.

**Comment by cforrestvivawallet** [comment]
Hi @viderspan,

Our 'Deprecated' API endpoints are still fully-functional. As you say, in some cases these provide functionality which is not yet available via our 'new' API calls.

We will continue to build out our newer endpoints, but we do not currently have any plans to disable or remove our 'Deprecated' endpoints, so please feel free to use these.

Please let us know if there is anything else we can assist with.

Kind regards,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
We will be closing out this issue now, but please do not hesitate to let us know if there is anything else we can assist with.

Kind regards,
Viva Wallet Development Team
