### ISSUE TITLE
Transaction failed page

### ISSUE THREAD

**Issue by viderspan** [VivaPayments/API#2207]
Dear Support,

I tried to test the timeout case.
If the cardholder doesn't enter the card details within the timeout period, a Viva Wallet error page will be displayed after pressing the pay button. I attach this screen.
In this case neither the merchant's failed URL nor his webhook will be called.
How can the merchant be notified of the status of this transaction?
Is it possible for redirection to work in this case as well?

Thank you and Best regards.
![Screenshot from 2022-06-24 10-41-24](https://user-images.githubusercontent.com/5574455/175503474-3077dec5-ecf8-4ea6-acad-5b1a7cb3c823.png)

**Comment by cforrestvivawallet** [comment]
Hi @viderspan,

Thanks for getting in touch. This is a known issue and something we are looking to resolve in the future. For the time being, there is no way of being notified in such cases.

If you know the orderCode, you can query the [Retrieve Order API](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments-(Deprecated)/paths/~1api~1orders~1{orderCode}/get) to see the status of the payment order. Within the response, a value of  **"StateId": 1** indicates that the payment order has **Expired**. You could also navigate to https://demo.vivapayments.com/web2?ref=[orderCode] to determine whether a payment order has indeed expired.

If you need to amend the timeout time of the payment order, you can use the paymentTimeOut parameter within the [Create Payment order API.](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post).

Please don't hesitate to let us know if you have any further questions.

Kind regards,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
We will be closing out this issue now, but please do not hesitate to let us know if there is anything else we can assist with.

Kind regards,
Viva Wallet Development Team
