### ISSUE TITLE
3DS challenge flow not working

### ISSUE THREAD

**Issue by NikosTsesmelis** [VivaPayments/API#2208]
WebView shows blanc page. The html that is returned the following:
Was working fine some days ago.

demo-api.vivapayments.com/nativecheckout/v2/chargetokens:

`redirectToACSForm : <html class=\"no-js\" lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n<meta charset=\"utf-8\"/>\n<title/>\n<link href=\"static/mpi.css\" rel=\"stylesheet\" type=\"text/css\"/>\n</head>\n<body>\n<div id=\"main\">\n<div id=\"content\">\n<div id=\"order\">\n<h2>3D Secure processing</h2>\n</div>\n<div id=\"content-footer\"/>\n</div>\n</div>\n</body>\n</html>`

**Comment by egaou** [comment]
Hi @NikosTsesmelis,

Thank you for reporting this behavior to us.
We inform you that we are intermittently encountering some instabilities in the demo environment regarding the 3DS challenge flow.
When payments are successful, the transactions use to go through frictionless with no 3DS dialog box appearing.
We'll investigate further and get back to you as soon as possible.

Kind regards,
Viva Wallet Development Team

**Comment by NikosTsesmelis** [comment]
Yes thank you now it is working correctly.
