### ISSUE TITLE
php8.0 warnings

### ISSUE THREAD

**Issue by knofte** [VivaPayments/API#2209]
Hello champs,
Plugin version 1.2.0, wordpress, php8.0.

Causes the warning:
PHP message: PHP Warning:  The magic method PGWC_Vivawallet::__wakeup() must have public visibility in /path/wp-content/plugins/viva-wallet-for-woocommerce/woocommerce-vivawallet-gateway.php on line 90

Seems ok in php7.4 and earlier. Though warns in php8.0 and php8.1.

Cheers.

**Comment by can3ry** [comment]
Hello @knofte 

Thank you for the notice.

We’ve addressed this issue with our engineering team. They’ll be making necessary improvements soon.

We will be closing out this issue now, but please let us know if we can help you with anything else in the meantime.

Best Regards
Viva Wallet Development Team
