### ISSUE TITLE
While integrating with magento 2.3 getting error

### ISSUE THREAD

**Issue by munishdogra** [VivaPayments/API#2210]
While integrating VIVA Wallet with Magento 2.3 we are getting following error:
Class Magento\Framework\Session\SessionStartChecker does not exist                                                                                                           
  Class Ced\VivaPayments\Session\SessionManager\Interceptor generation error: The requested class did not generate properly, because the 'generated' directory permission is   
  read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not ge  
  nerate properly, then you must add the generated class object to the signature of the related construct method, only.

**Comment by munishdogra** [comment]
![Screenshot at 2022-06-29 12-10-31](https://user-images.githubusercontent.com/108390361/176371492-2c5b6504-99e8-4f0f-b8e7-795d40965833.png)

**Comment by gemitsio** [comment]
Hello @munishdogra,

please clarify if the issue faced during the Viva Wallet plugin installation. If not, please provide the actions that you take with the additional sequence. 

Kind regards,
Viva Wallet Development Team

**Comment by phplead4** [comment]
Hello @gemitsio, yes we are facing the issues while installation Viva Wallet plugin. And getting error mentioned above. 

Thanks

**Comment by phplead4** [comment]
> yes we are facing the issues while installation Viva Wallet plugin. And getting error mentioned above.
> 
> Thanks

Hello @gemitsio, yes we are facing the issues while installation Viva Wallet plugin. And getting error mentioned above.

Thanks

**Comment by munishdogra** [comment]
Hello Viva Support Team,
While installing the Viva wallet plugin in Magento 2.3, below are the steps which I followed and got the errors after hitting the compile command.
Step 1: 
1: I have downloaded the extension and added files to the app/code/Ced/VivaPayments folder.
Step 2:
1: Run the following commands within Magento
	Enable module: bin/magento module:enable --clear-static-content Ced_VivaPayments
	Upgrade database: bin/magento setup:upgrade
	Re-run flush command: bin/magento cache:flush
	Re-run compile command: bin/magento setup:di:compile

2: The compile command was not properly executed and hit the error mentioned in the screenshot: https://prnt.sc/RErmGWOLwDca

Step 3:
1: I have given permission to the entire Magento folder, including the generated folder, and then hit the above commands again, but I am still getting the same error.
Step 4:
1: I have also added the additional information which is mentioned in the documentation, please see the screenshot: https://prnt.sc/JG7UnKtc8Thv
2: After that, I hit the below commands:
	find . -type d -exec chmod 755 {} \; && find . -type f -exec chmod 644 {} \; && chmod u+x bin/magento
	chmod -R 0777 var/ pub/ generated/
	rm -rf var/cache/* var/view_preprocessed/* generated/* pub/static/*
	php bin/magento setup:upgrade
	php bin/magento setup:di:compile
	php bin/magento setup:static-content:deploy -f
	php bin/magento cache:flush  

	Then we got the same error. Then we ran composer update and after that I ran the above commands again in sequence. But still, the issue was not resolved.

Step: 5 
1: I have installed the fresh Magento 2.3 setup and added files to the app/code/Ced/VivaPayments folder and ran the above commands again, but in the fresh Magento 2.3 setup it's giving the same error.

Note: After hitting all the above commands, Magento admin is working fine, and on the frontpage we are getting the errors. Please see the screenshot: https://prnt.sc/y-7_oO-Vw7Cc 
Can you please check that after doing all the above steps and following the documentation steps, we are still getting the error while installing the Viva Wallet plugin?

Thanks

**Comment by munishdogra** [comment]
@gemitsio, kindly check the above steps we followed with screenshots

**Comment by can3ry** [comment]
Hello @phplead4 

We appreciate your patience and will be happy to identify this issue for you.

Kindly note that I've forwarded the details to the engineering department. They should have an answer within a few days, but I’ll be sure to update you as soon as I hear back.  

Best regards,
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hello @phplead4 

Just to let you know, we have not yet received an update on this issue, but we are liaising with the engineering and will keep you informed of any information.

Thank you for your understanding.

Best regards,
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hello @phplead4 @munishdogra 

It looks like this is a server configuration issue on your end. A possibility is that the file system owner is not the web server. Setting the proper ownership before you install the Magento can be a solution. Correspondingly, we confirm that the error you get is not related to Viva Wallet's smart checkout plugin.

[This link](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/file-system-perms.html) provides more information on how to set ownership and permissions for Magento 2.3.

If there’s anything else we can help you with in the meantime, please let us know.

Kind regards,
Viva Wallet Development Team

**Comment by agams** [comment]
Hello @can3ry,

Here is the response from your technical support team over the chat:
https://prnt.sc/V66ifSW1Ei9D
Your domain on your source doesn't match the default domain of your website. The website's domain should be stage.aloegarve.com to complete the integration. Now the website is located in an inner folder of the server. Can you please make the necessary changes and try it again?


And we have matched the domain  with Viva settings and also moved the website's  from inner folder to root folder and still getting the same issue. 

Thanks

**Comment by agams** [comment]
> Hello @phplead4 @munishdogra
> 
> It looks like this is a server configuration issue on your end. A possibility is that the file system owner is not the web server. Setting the proper ownership before you install the Magento can be a solution. Correspondingly, we confirm that the error you get is not related to Viva Wallet's smart checkout plugin.
> 
> [This link](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/file-system-perms.html) provides more information on how to set ownership and permissions for Magento 2.3.
> 
> If there’s anything else we can help you with in the meantime, please let us know.
> 
> Kind regards, Viva Wallet Development Team

Here is the response from your technical support team over the chat:
https://prnt.sc/V66ifSW1Ei9D
Your domain on your source doesn't match the default domain of your website. The website's domain should be stage.aloegarve.com to complete the integration. Now the website is located in an inner folder of the server. Can you please make the necessary changes and try it again?

And we have matched the domain with Viva settings and also moved the website's from inner folder to root folder and still getting the same issue.

Thanks

**Comment by agams** [comment]
> Hello @phplead4 @munishdogra
> 
> It looks like this is a server configuration issue on your end. A possibility is that the file system owner is not the web server. Setting the proper ownership before you install the Magento can be a solution. Correspondingly, we confirm that the error you get is not related to Viva Wallet's smart checkout plugin.
> 
> [This link](https://devdocs.magento.com/guides/v2.3/install-gde/prereq/file-system-perms.html) provides more information on how to set ownership and permissions for Magento 2.3.
> 
> If there’s anything else we can help you with in the meantime, please let us know.
> 
> Kind regards, Viva Wallet Development Team

Hello @can3rty,

Here is the response from your technical support team over the chat:
https://prnt.sc/V66ifSW1Ei9D
Your domain on your source doesn't match the default domain of your website. The website's domain should be stage.aloegarve.com to complete the integration. Now the website is located in an inner folder of the server. Can you please make the necessary changes and try it again?

And we have matched the domain with Viva settings and also moved the website's from inner folder to root folder and still getting the same issue.

Thanks

**Comment by can3ry** [comment]
Hi @agams 

Thanks for the additional information.

As mentioned, it seems there is an issue with your server/file system configuration. So there is nothing to do with the Viva Wallet plugin. 

Were you able to check the ownership of the file system?  

We recommend checking this link for more details about setting ownership. 

https://devdocs.magento.com/guides/v2.3/install-gde/prereq/file-system-perms.html
![set-ownership](https://user-images.githubusercontent.com/51880555/178263160-6d0449c1-2dc1-4428-b5b9-13a2dfb50eda.png)

Let us know if you need any further help with the Viva Wallet smart checkout plugin.

Kind regards,
Viva Wallet Development Team
