### ISSUE TITLE
Test credit cards not working in demo

### ISSUE THREAD

**Issue by RobertoDex** [VivaPayments/API#2212]
When i try to use a test credit cards in Smart Checkout in order to test a failed payment, the payment does not fail. It always gets successfull.

**Comment by egaou** [comment]
Hi @RobertoDex ,

Could you please confirm how do you test a failed transaction?

Do you use the cards mentioned [here in developer portal](https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#test-cards)?

Kind regards,
Viva Wallet Development Team

**Comment by RobertoDex** [comment]
Hi, i try with the "fail" cards in list that you linked

**Comment by egaou** [comment]
Could you please provide any transactionId and the test card details that you used?

**Comment by RobertoDex** [comment]
afcc7f9a-86cb-4008-8e52-dad732d53f48 and card 5239 2907 0000 0119

**Comment by egaou** [comment]
Hi @RobertoDex ,
Could you try again and let us know if the transactions fail?

**Comment by egaou** [comment]
Please only test with 5239 2907 0000 0119 and 4147 4630 1111 0141. It should be working.
 4147 4630 1111 0133 is for successful transactions.

**Comment by egaou** [comment]
Our test cards are configured by a third-party and we are getting intermittent issue with the cards.
We'll investigate further and advise you.

Regards

**Comment by RobertoDex** [comment]
ok, i'm here.

**Comment by egaou** [comment]
Hi @RobertoDex,

Please could you test again and confirm that it works as expected?

Regards

**Comment by RobertoDex** [comment]
Ok, now the payment fails, but my "transaction payment created" or "transaction failed" webhook is not called

**Comment by egaou** [comment]
Please, note that webhook notifications will be not triggered for expired, cancelled payments, or payments that failed 3DS user authentication (see the [Event ID codes](https://developer.vivawallet.com/integration-reference/response-codes/#event-id-codes)). If you wish to test a [Transaction Failed](https://developer.vivawallet.com/webhooks-for-payments/transaction-failed/) webhook, please use our [Trigger an issuer decline](https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#trigger-an-issuer-decline) functionality.

We have updated [our documentation](https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#test-cards) with this information.

Kind regards,
Viva Wallet Development Team

**Comment by egaou** [comment]
We will be closing out this issue now, but please do not hesitate to let us know if there is anything else we can assist with.

Kind regards,
Viva Wallet Development Team
