### ISSUE TITLE
Can't connect my sanbox paypal account in vivawallet demo api dashboard

### ISSUE THREAD

**Issue by RobertoDex** [VivaPayments/API#2213]
I can't connect my sandbox paypal account in the viva wallet demo portal (https://demo.vivapayments.com/selfcare/it/security/apiaccess). The connect process finalizes well, but when the paypal pop up is closed and page is refreshed, nothig happen.

**Comment by gpliakis** [comment]
Hi, I see that you are trying to set it up on your sandbox environment. Did you follow this guide?
https://developer.vivawallet.com/payment-methods/digital-wallets/paypal/#optional-setup-steps-to-enable-paypal-as-a-payment-method-sandbox-mode

**Comment by RobertoDex** [comment]
Yes i've followed all the steps (we already had a sandbox business account), but nothing. When the page refresh nothig happen. I have tried In Production environment with paypal production account and all works well. I think this is a demo environment problem

**Comment by gpliakis** [comment]
Correct.
As I mentioned, you won't be able to test PayPal in sandbox. Please go on and enable it in production and you can test it there!

**Comment by RobertoDex** [comment]
How can i test in production? i have to pay with real money! or not?

**Comment by gpliakis** [comment]
Yes.
You can try with small amounts of money and since it is your account and you can cancel it at anytime, there is no risk there :)
