### ISSUE TITLE
Transaction Payment Created webhook fired more than once for a transaction in demo environment

### ISSUE THREAD

**Issue by RobertoDex** [VivaPayments/API#2214]
I had set a webhook endpoint for "Transaction Payment Created" event. The verification went well. The end point is called correctly, but the problem is that it is called many times for one transaction with same StatusId and same TransactionTypeId. I don't know why.
My endpoint response is correctly 200.
This is my MVC C# code

```
public ActionResult NotifyPayment(NotifyPaymentModel model)
{
        /// other code

        return new HttpStatusCodeResult(HttpStatusCode.OK);
}

```

**Comment by gemitsio** [comment]
Hello @RobertoDex,

Please confirm that you reply with HTTP 200 to our POST webhook notification request.

Kind regards,
Viva Wallet Development Team

**Comment by gemitsio** [comment]
Hello @RobertoDex,

the webhook triggered more than one time because we don't receive HTTP 200 from your end point, as described [here](https://developer.vivawallet.com/webhooks-for-payments/#retry-policy). 

Just for your info, we reproduce all the webhook scenarios and the mechanism works successfully. 

Kind regards,
Viva Wallet Development Team

**Comment by RobertoDex** [comment]
ok, i'll review again my code

**Comment by RobertoDex** [comment]
I've checked again and i correctly return 200.

**Comment by can3ry** [comment]
Hi @RobertoDex 

We will surely help you with this problem.

However, before we dive in, we will need more details from you. 

When did you start facing this issue? Is the problem occurring consistently, or does it happen from time to time? 

Do you keep the payloads you received twice?  If so, would it be possible to send us one of the duplicated payloads?

The answer to these questions will help us dig deeper and find an answer to this issue.

Kind regards,
Viva Wallet Development Team
