### ISSUE TITLE
Viva Wallet Standard Checkout for WooCommerce - Can't change subscription status from the backend

### ISSUE THREAD

**Issue by vaskou** [VivaPayments/API#2215]
I have the Viva Wallet Standard Checkout plugin for WooCommerce and I have the WooCommerce Subscriptions plugin enabled in my site.

When I try to change the status of a subscription, that was purchased with Viva Wallet payment method, from the backend I get the error "Error updating some information: You are not allowed to change the Card Token." and the status of the subscription does not change.

Can you please help?

**Comment by cforrestvivawallet** [comment]
Hi @vaskou,

1. Please could you provide the exact steps you have taken, from the initial payment through to the error message?
2. Are you able to confirm if this is also happening for other/all such subscriptions?
3. Lastly, please could you provide me with your Merchant ID so I can take a look at your account?

Kind regards,
Viva Wallet Development Team

**Comment by vaskou** [comment]
Hi @cforrestvivawallet,

1. The exact steps are:
  a. The payment is complete in the frontend
  b. In the backend I go to WooCommerce -> Subscriptions and I open the subscription I want to edit
  c. In the subscription edit page I change the subscription status from "Active" to "Pending Cancellation" and I click the "Update" button.
  d. The error "Error updating some information: You are not allowed to change the Card Token." is shown and the status of the subscription have not been changed. It is still to "Active".

2. Yes it is happening to all subscriptions

3. I'm testing this with a demo Viva Wallet account.

I have done some code digging and the problem occures in file of the plugin "viva-wallet-for-woocommerce/includes/class-wc-vivawallet-subscriptions.php" in the function "validate_subscription_payment_meta".

`if ( ! empty( $payment_meta['post_meta'] ) ) { `
`throw new Exception( __( 'You are not allowed to change the Card Token.', 'viva-wallet-for-woocommerce' ) );`
`}`

There is an if statement that I think that it must be more specific because `$payment_meta['post_meta']` contains various data that it will always be not empty. Check this out if you can.

Thanks

**Comment by cforrestvivawallet** [comment]
Thanks for your response @vaskou, this is very helpful.

Please could you also provide the Merchant ID of this demo account? You can find this **[here](https://developer.vivawallet.com/getting-started/find-your-merchant-id-and-api-key/)** (your API key is not required).

Kind regards,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
Hi @vaskou,

Thanks for providing that information.

We will look into this issue internally, but in the mean time you may be able to amend the status of a subscription from the Subscriptions List / 'All Subscriptions'. Here you should be able to use the checkboxes on the left-hand side to select the relevant subscription and then use the 'Bulk Actions' dropdown to make the necessary change.

Please let me know if this alternative method works for you.

Kind regards,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
Hi @vaskou,

Please note, our developers are still investigating the reported issue and we will provide feedback soon.

In the meantime, if the workaround I mentioned previously does not work, or if you have any other queries, please let us know.

Kind regards,
Viva Wallet Development Team

**Comment by cforrestvivawallet** [comment]
Hi @vaskou,

Our developers have fixed this issue internally and this fix will go live with the next release of our plugin. Unfortunately, I don't have an exact timeframe on this.

I will close out this issue now, but please let us know if you have any problems with the workaround provided previously, or if you have any other queries.

Thanks again for bringing this to our attention.

Kind regards,
Viva Wallet Development Team

**Comment by vaskou** [comment]
Hi @cforrestvivawallet 

Thanks you for fixing the problem. I will wait for the plugin update.
