### ISSUE TITLE
PROBLEM WHIT AMEX

### ISSUE THREAD

**Issue by 01odierno** [VivaPayments/API#2216]
GOOD MORNING
I EXPERIENCED SEVERAL FAILED TRANSACTIONS ON THIS SCHEME
PLEASE WE NEED TO SET UP A CALL WHIT YOU DEVELOPERS
BEST REGARDS

**Comment by can3ry** [comment]
Hi @01odierno 

Could you please provide your merchant id so we can investigate further?

You can follow [this link](https://developer.vivawallet.com/getting-started/find-your-merchant-id-and-api-key/
) to find the merchant id information 

Best Regards
Viva Wallet Development Team

**Comment by 01odierno** [comment]
WELCOME TRAVEL SUD SRL

**Comment by can3ry** [comment]
hI @01odierno 
Thank you for the information.
We'll contact you via email.
As this is not an issue related to integration, I am closing this ticket for now.
Let me know if you have any questions, I’d be happy to answer them.
Best regards
Viva Wallet Development Team
