### ISSUE TITLE
Recurring payment not working

### ISSUE THREAD

**Issue by RobertoDex** [VivaPayments/API#2217]
I try to create a recurring payment by set "AllowRecurring" to true during the create payment request. When i insert credit card numbers in smart checkout page and submit, i'm redirect to my page but with eventcode = 1 but without the transaction id. Furthermore my Transaction Payment Created webhook is never fired (also my Transaction Failed webhook never fired).

**Comment by RobertoDex** [comment]
Hi, now it works, but if i try with failed test credit card, my "Transaction payment created" or "Transaction failed" webhook is not called.

**Comment by cforrestvivawallet** [comment]
We will be closing out this issue now, but please do not hesitate to let us know if there is anything else we can assist with.

Kind regards,
Viva Wallet Development Team
