### ISSUE TITLE
Requests and clarifications on payment transaction management

### ISSUE THREAD

**Issue by aldexxx86** [VivaPayments/API#2219]
Hi,
as already exposed to your Italian commercial contacts, I also expose to you our technical problem in the integration of your payment API in our systems.
Below I put the diagram on your documentation page: https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/
<a href="https://imgbb.com/"><img src="https://i.ibb.co/KN4d2c1/vivawallet-diag.png" alt="vivawallet-diag" border="0"></a>
Our problem is to understand if we can manage the payment flow in a transactional way, that is, that our backend is immediately aligned with your payment system on the status of each payment, if the payment was successful or failed.

In the diagram above and in your documentation it seems that this is not possible, this is because the passage (redirect) circled in red from the backend of VivaWallet (Viva Wallet API) to our frontend (Merchant Frontend) is not guaranteed, several events could happen, examples :

- loss of internet connection by the user

- frontend page error

- closing of the page / App earlier than expected by the user

Furthermore, in turn, our frontend could have the same chain problem in the call to our backend, so in practice it could happen that a successful payment on VivaWallet does not result in a status executed on the database of our systems, this is because from what I saw a lack of direct communication and verification from your systems to our backend in real time.

For example, Nexi which is your competitor (also PayPal gives it but in a different way) implements this concept of transactionality through the "Cancel Transaction in case of Failed Notification" function, practically the Nexi system, before redirecting the user to the page of our frontend, during the payment process calls "server to server" (Nexi backend -> Merchant backend) our backend sending us all the information on the payment transaction, if this call is correctly processed by our Merchant Backend to the backend of Nexi the successful Http 200 code is returned and the payment proceeds successfully, otherwise if our system returns an error http code for some problem the payment transaction is canceled.
This mechanism allows us to be sure not to lose any information on payments made by users in real time and to always have the situation aligned.

But from what I have seen the webhook setup allows you to receive a call from your systems when the payment ends in success or failure but it is not binding and does not cancel the transaction if we do not process the information correctly, and the call of the your webhook is done later in a way unrelated to the payment transaction as you can also understand from here:
<a href="https://ibb.co/bNqB7xb"><img src="https://i.ibb.co/frBpQbD/vivawallet-retrypolicy.png" alt="vivawallet-retrypolicy" border="0"></a>

I look forward to receiving your technical feedback.
Thank you

**Comment by aldexxx86** [comment]
> Dear @aldexxx86
> 
> Thank you so much for your feedback and for bringing this to our attention.
> 
> We're sorry to say that we do not have such functionality right now. I've forwarded your request to the product team to be analyzed and considered for the future.
> 
> You mentioned that the payments are canceled if a server-to-server call is not correctly processed by your Merchant Backend. In this case, can I understand that you do not dynamically show the result of the payment to your customers? Do you show a temporary payment status like "processing" and if everything goes well, you make it successful.
> 
> If you show the result dynamically, may I ask what happens if a delay occurs on a notification and the customer is redirected back to your system before the server-to-server notification reaches out to you?
> 
> If you do not show the result dynamically, the same logic can be applied to our API calls as well. The only difference is we do not cancel the transaction on behalf of you. If somehow you cannot handle the redirection or webhook notifications, you need to fetch the payment result with an API call. So you can decide to cancel it or not.
> 
> In Viva Wallet Payment APIs, you are allowed to set **a lifespan for an order code**(please see the paymentTimeOut parameter in [this call](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post)). You can check the status of an order code anytime. However, checking it **after its lifespan** would give you a final result about the payment. So you can validate the order in your system and decide how to proceed. You can make this **programmatically** as per the lifespan of your order codes.
> 
> Please see the retrieve transaction details [API call](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)/paths/~1api~1transactions~1%7Bid%7D/get) for more details. You can use this API call with OrderCode filtering. Example: /api/transactions/?ordercode=XXXXXXXX If you have a successful payment for the mentioned order code you get its details.
> 
> Retrieve order code details [API call](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments-(Deprecated)/paths/~1api~1orders~1%7BorderCode%7D/get) helps you to fetch the state of an order code. The StateId parameter gives you a clear view of the payment status.
> 
> StateId=0 (Pending) StateId=1 (Expired) StateId=2 (Canceled) StateId=3 (Paid)
> 
> If any of those steps are unclear, let me know, and I’m happy to explain further.
> 
> Let us know if you have any more questions, comments, or concerns.
> 
> Kind regards, Viva Wallet Development Team

Hi,
we handle payments dynamically if I understand what you mean.
However, your competitor systems, such as PayPal and Nexi, ensure that the backend is updated with the status of the payment once the payment is finished and displayed on the user's frontend.
For example Nexi, with a certain option activated as already described, calls our backend (server to server, Nexi -> our backend) to communicate the payment status with all the details, if our backend returns http 200 that is everything ok , Nexi finishes processing the payment successfully and redirects the user to the frontend.
The call to our backend and the redirection to the frontend of the user are not asynchronous and in parallel but they are synchronous and consecutive, what you described cannot happen that the user is redirected to our frontend before the call to the backend.
How Nexi manages it I don't know, in the sense I don't know if it finalizes the payment after the response of our backend or finalizes the payment first and then in case the call to our backend fails it cancels it.
PayPal instead uses this other method, when PayPal redirects the user to our frontend PayPal has not yet finalized the payment, but our frontend must display a payment confirmation button and only when the user presses the button through this action will managed the server to server confirmation call (our frontend --> our backend --> PayPal) the payment will be confirmed and the result will be displayed to the user.

I hope I was clear, but in your payment process the certainty of the communication on the status of the payment towards our backend is lacking.

Thanks
Matteo Alderighi

**Comment by can3ry** [comment]
Thanks for further explanations @makisantypas 

If any problem happens with the connection/applications, we advise you to follow the below steps and take action according to your requirements.

1-[Set up webhooks](https://developer.vivawallet.com/webhooks-for-payments/) for failed and successful transactions. You will be notified about the status of payments. So you can [cancel](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)/paths/~1api~1transactions~1{id}/delete) it when necessary.

2-[Retrieve transaction details](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)/paths/~1api~1transactions~1%7Bid%7D/get), check its status and [cancel](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)/paths/~1api~1transactions~1{id}/delete) if necessary.

I have also shared your valuable feedback with the rest of my team.

I am closing this ticket for now. If you need further information, please let us know.

Kind regards,
Viva Wallet Development Team
