### ISSUE TITLE
Payment Failed when i tried to purchase 1000 credits

### ISSUE THREAD

**Issue by sarroula** [VivaPayments/API#222]
I 've tried to charge my credit card and my debit card to buy credits (1000) from the greek company P. Melissaropoulos and i received the following error. A client received the same error too when he tried to purchase credits. I didn't face that error when i tried to purchase a monthly plan, and i received the correct invoice.

![step1](https://cloud.githubusercontent.com/assets/24875968/21589825/8cdbb458-d0fe-11e6-841d-55834ab2f34a.jpg)
![step2](https://cloud.githubusercontent.com/assets/24875968/21589826/8cdc409e-d0fe-11e6-8001-1efca471d38e.jpg)
![step3](https://cloud.githubusercontent.com/assets/24875968/21589827/8cdcc3c0-d0fe-11e6-9ab6-67ae2240d8c3.jpg)

These is our website www.moosend.com
and you can find more if you check that order code 3484639911472601

**Comment by krakenrules** [comment]
Καλημέρα
Το πρόβλημα είναι στο ποσό της χρέωσης (0.04) αφού δε μπορεί να γίνει χρέωση τόσο μικρού ποσού.  Δοκιμάστε ένα μεγαλύτερο ποσό, αν θέλετε (πάνω από 0.30€-0.40€)

Ευχαριστούμε
