### ISSUE TITLE
Vivawallet magento 2.4

### ISSUE THREAD

**Issue by panoskwst** [VivaPayments/API#2222]
Hallo, I have installed your pluggin in magento 2.4 and I see that, when redirected to the payament gateway, if i go back and don't enter card details , the order is created in Magento as processing even when payment has not completed. Can we atleast get a callback for this case?

**Comment by can3ry** [comment]
Hi @panoskwst 

Thank you for your feedback. 

Currently, development for this is not in our pipeline however we've noted your request for future improvements.

For the Magento plugin, every order code(checkout form) expires 30 minutes later. So if an order's status does not change 30 minutes later, it will be permanent and will not change in the future. So, a quick solution would be to create a cron job that checks such orders and update their status according to their creation time.

Please let us know if there is anything further we can assist with.

Kind regards,
Viva Wallet Development Team
