### ISSUE TITLE
Marketplace - Manage transfer fees and payouts (demo)

### ISSUE THREAD

**Issue by galyfantis** [VivaPayments/API#2223]
Hello,

We are implementing a custom module for markeplaces, and we are trying to test the related [Manage transfer fees and payouts](https://developer.vivawallet.com/tutorials/marketplace/manage-transfer-fees-and-payouts/) scenario in the demo environment.

With a quick search we have found #2174, which exactly describes our current situation:
* Calling the [balance tranfer endpoint](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Balance-Transfer/paths/~1api~1wallets~1{walletId}~1balancetransfer~1{targetWalletId}/post), we receive a response with status 452 
* Although we are seeing the successful transactions under 'Online Payments', the balance of the linked account is still 0

So, based on the resolution of #2174, could you please add balance to our account?

The merchant id is **7cd48fd4-a59c-4101-a6cc-fb93788ae880**

**Comment by egaou** [comment]
Hi @galyfantis,

We have added funds to your account.

Could you please check and let us know if everything works fine? 

Best regards
Viva Wallet Development Team

**Comment by galyfantis** [comment]
Hello @egaou 

Thanks for adding the funds. Everything works fine now.
