### ISSUE TITLE
Magento 2.4.2 order canceled when payment is successfull

### ISSUE THREAD

**Issue by panoskwst** [VivaPayments/API#2224]
Hallo,
In some orders we have noticed that while the customer has made a successfull transaction the order is canceled and it displays the message "Transactions completed Successfully". This is not happening in all the orders and we don't know exactly how to recreate this problem. We think that for some reason in the callback.php file after it enterd the if ($resultObj->ErrorCode==0) in line 136 then for some reason it is entered in the else in line 193 and it displays the message from the previusly if and it cancels the order.

**Comment by can3ry** [comment]
Hello @panoskwst ,

We are looking into this and will get back to you soon.

Best regards
Viva Wallet Development Team

**Comment by NedelkosM** [comment]
Hello, we are experiencing exactly the same issue, please let us know if there is an update to this!

**Comment by can3ry** [comment]
Hello @panoskwst @NedelkosM 

Could you please share the order history of a transaction you issued this problem?

It can be found on the order details page under the _Comments History_ tab. Please see below,

<img width="1324" alt="history" src="https://user-images.githubusercontent.com/51880555/180732528-bd3e4b8d-649b-4281-8746-1b048de603ac.png">

Best regards
Viva Wallet Development Team

**Comment by panoskwst** [comment]
![example1](https://user-images.githubusercontent.com/45177097/180749876-aa04f4a6-d5ee-4854-ab95-d2b287744ad9.png)

**Comment by can3ry** [comment]
@panoskwst  thanks for this. Could you also share the Viva Wallet transaction id?

Kind regards
Viva Wallet Development Team

**Comment by can3ry** [comment]
@panoskwst  is it also possible to share the plugin you use?

Kind regards
Viva Wallet Development Team

**Comment by can3ry** [comment]
hi @NedelkosM 

Thanks for the additional information. You can find the order code in the order details. Please see the below,

<img width="1429" alt="Screenshot 2022-07-25 at 15 50 52" src="https://user-images.githubusercontent.com/51880555/180806621-4f2ed70d-1963-4777-bbd9-baacac178b78.png">

Kind regards
Viva Wallet Development Team

**Comment by NedelkosM** [comment]
Hi @can3ry , thank you for the reply.

Sorry this is not in english but I believe you can understand. Unfortunately the order ID is not listed. Maybe this is part of the issue.
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/4204263/180938403-e29d1286-1ea5-4093-bb99-647a02c7286e.png">

**Comment by panoskwst** [comment]
our 

> @panoskwst thanks for this. Could you also share the Viva Wallet transaction id and the plugin details?
> 
> Kind regards Viva Wallet Development Team

The plugin we use is one for magento 2.3 i can't find the exact version in the code. Unfortunatly i don't have access to the transaction id.

**Comment by can3ry** [comment]
Hello @NedelkosM 

WooCommerce's Hold Stock functionality cancels a transaction if the order is unpaid for X minute. For our current plugin(version 3.6.4), we recommend setting this parameter as 30 or more.  Please see the screenshot below. 

Our plugin does not have a cancellation function except for the redirection page. At the time of redirection, we show a cancel button in a form but the form submits itself automatically and opens a smart checkout. If -somehow- the user's javascript does not work, they can see this button and click it to cancel the order. This is a very unusual scenario and should not be an issue.

In both cases, the transaction can be canceled if there is no payment at all. 

<img width="1433" alt="woo" src="https://user-images.githubusercontent.com/51880555/180965512-4aa97a92-3ca1-4f44-bb3e-a34ceda0cd66.png">

As a result, we have two statuses in the plugin. The first one is pending payment for unpaid orders. And the second one is the status you selected for paid orders at the time of plugin installation.

Please let us know if you need further information.

Kind regards
Viva Wallet Development Team

**Comment by NedelkosM** [comment]
Hello @can3ry 

The setting you have showed me it already at 60 minutes, that doesn't seem to be related to the issue.

Please keep in mind that the transactions are charged normally. The client is charged, we receive the money through Viva, but the plugin reports a cancelled order.

**Comment by can3ry** [comment]
Hi @panoskwst 

We discovered a minor issue within the scope of Magento order history. We pass the "Transactions completed Successfully" message for some declines that are not covered in decline recovery. Please note we believe that the transaction you mentioned actually failed. And the order history has a wrong record. For this type of transaction, the end user should see  "Your transaction failed or has been cancelled" message on the result page. For now, we recommend ignoring that message for canceled transactions. We're going to fix this in the future release. 

In addition, you may add the below **$message** into the else clause in line 157 (Controller/Viva/Callback.php) to have a quick solution.

`$message = 'The following error occured: <strong>' . $resultObj->ErrorCode . '</strong>, ' . $resultObj->ErrorText;
`

<img width="601" alt="mag" src="https://user-images.githubusercontent.com/51880555/181015157-4c897585-10d4-4d51-af0c-15b1d15419b3.png">

If you need further information please let us know.

Kind regards
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hello @NedelkosM 

Thanks for the additional info.

The message in your screenshot is directly coming from wordpress/woocommerce. So, I can confidently say that the transaction was not canceled by our plugin.

I've also checked your account and confirm that **there is no payment** for the mentioned timestamps. 

The money you receive from the Viva Wallet may belong to another transaction. But from the screenshot you shared, I can say that the payment was not paid at all. 

If you need further information, please let us know.

Kind regards
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hello,

I presume that the issues have been identified. This is why I am closing this ticket for now.

If you have further questions, please do not hesitate to raise a new ticket.

Kind regards
Viva Wallet Development Team
