### ISSUE TITLE
Order Auth

### ISSUE THREAD

**Issue by Emytica** [VivaPayments/API#2227]
Hi,
in the order message you can use the Basic Auth?

regards,
Emilia

**Comment by can3ry** [comment]
Hello @Emytica,

Could you clarify your question, please?

Best regards
Viva Wallet Development Team

**Comment by Emytica** [comment]
Does the "Create payment order" (checkout/v2/orders)  use the "Basic Auth" ?

**Comment by can3ry** [comment]
Hi @Emytica 

This API resource is OAuth 2.0 protected and needs to be accessed by a Bearer token(access token). To generate payment orders, you should make authenticated requests with a bearer token using the "Authorization" request header field. You may find a detailed tutorial here: [Use OAuth 2.0 authentication](https://developer.vivawallet.com/tutorials/api-configuration/use-oauth-2-authentication/). Please do not hesitate to use our postman collection to test it out.

You can also check [API Docs](https://developer.vivawallet.com/apis-for-payments/payment-api/) page to see the authentication type of API calls. Please see the red-mentioned area in the below screenshot below.

<img width="1432" alt="oauth" src="https://user-images.githubusercontent.com/51880555/180471276-49702488-a9a3-4fbf-99ae-f54ef70b9fb6.png">

Please let us know if there is anything further we can assist with.

Kind regards,
Viva Wallet Development Team
