### ISSUE TITLE
/api/fees documentation

### ISSUE THREAD

**Issue by galyfantis** [VivaPayments/API#2228]
Hello,

I am trying to understand what `/api/fees` endpoint is about, but I find it a bit hard just looking at the [api documentation](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Fees/paths/~1api~1fees/get).

E.g., what do the fields (Fee, BillFee, ServiceFee, etc) of the response mean? Is there another page with more information about this endpoint?

Also, please note that the api documentation needs a small fix: 
![image](https://user-images.githubusercontent.com/11825259/180406335-0e92e49d-1c63-4fa9-89c2-91f7af746289.png)

**Comment by can3ry** [comment]
Hello @galyfantis 

Thanks for the heads up.

We are going to add details to our documentation shortly. 

I'll inform you as soon as it is ready.

Kind regards,
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hello @galyfantis 

We've decided to remove this API call from documentation. It was containing some fees for our old APIs and now, it is deprecated.

I am closing this ticket for now. 

Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet Development Team
