### ISSUE TITLE
SSL και Redirect Checkout

### ISSUE THREAD

**Issue by fydbill** [VivaPayments/API#223]
Έχω κάνει όλα τα βήματα για το Redirect Checkout όπως περιγράφεται,ωστόσο συμβαίνει το εξής... παράδοξο: Με το που ενεργοποιήσω την σύνδεση SSL στην εφαρμογή (VB.NET) αδυνατεί να συνδεθεί με το API,βγάζοντας μου μήνυμα σφάλματος πως "το νήμα ματαιώθηκε". Υπάρχει περίπτωση το Redirect Checkout να μην μπορεί να χρησιμοποιηθεί σε σύνδεση SSL?

**Comment by defilerc** [comment]
Καλησπέρα @fydbill ,

Η μέθοδος Redirect Checkout όχι μόνο υποστηρίζει SSL, αλλά είναι και ο μόνος συνιστώμενος τρόπος για να το υλοποιήσετε καθώς αφορά την πραγματοποίηση πληρωμών και πρέπει να γίνεται μέσα από ασφαλές περιβάλλον. 

Επομένως σίγουρα δεν είναι αυτό το πρόβλημα. Έχετε μήπως κάποια επιπλέον πληροφορία από το exception, ώστε να μπορέσουμε να βοηθήσουμε;

Με εκτίμηση,

**Comment by fydbill** [comment]
Βασικά έχω το εξής πρόβλημα: Στην ιστοσελίδα μου,αφού ο χρήστης δώσει το ποσό που θέλει να πληρώσει,τον ανακατευθύνω σε ένα πλαίσιο το οποίο περιέχει μια σελίδα που φορτώνει το API. Με το που ενεργοποιώ το SSL το πλαίσιο δε φορτώνει καθόλου τη σελίδα,αλλά αν πληκτρολογήσω το όνομα του αρχείου στον browser με ανακατευθύνει κανονικά στο demo.vivapayments.com κτλ.

**Comment by defilerc** [comment]
Καλησπέρα @fydbill ,

Παρακαλώ πολύ, δείτε την περιγραφή της μεθόδου στη σελίδα: https://github.com/VivaPayments/API/wiki/Redirect-Checkout

Η διαδικασία είναι η εξής: Στη σελίδα που θα γίνει πληρωμή, ο χρήστης με το που πατήσει το κουμπί "Πληρωμή", εσείς δημιουργείται ένα Order με το ποσό που είναι να πληρώσει, κάνοντας μια κλήση στην CreateOrder στο API της Viva και στη συνέχεια τον ανακατευθύνεται στη σελίδα της Viva περνώντας στο URL σαν παράμετρο το ordercode από το order που δημιουργήσατε στο προηγούμενο βήμα.

Με εκτίμηση,

**Comment by fydbill** [comment]
Μια ερώτηση: Μπορώ έπειτα να αποθηκεύσω τις λεπτομέρειες της πληρωμής κάπου (προτιμότερο σε πίνακα μιας βάσης δεδομένων) αφού αυτή γίνει ώστε να ξέρω αν ο χρήστης πραγματοποίησε επιτυχώς την πληρωμή και με ποιο ποσό? Μοιάζει με το "verify transaction" που γράφετε αλλά επειδή είμαι αρχάριος στο θέμα θα ήθελα να μου το επιβεβαιώσετε. 

Αυτό που περιγράφετε το κάνω ακριβώς και δουλεύει,μέχρι να αλλάξω το "Project URL" από http://tourltousitemou σε https://tourltousitemou. Μόλις κάνω αυτό δεν με ανακατευθύνει στη σελίδα της Viva (την οποία καλώ από μια κενή σελίδα όπως δείχνετε άλλωστε και στα samples σας)

Ευχαριστώ και αναμένω απάντηση

**Comment by kostGX** [comment]
Closing because issue is more than 6 months inactive and assuming it's solved.

Please let us know if you want to reopen it.
