### ISSUE TITLE
Marketplace - Add funds to demo account

### ISSUE THREAD

**Issue by ntsagkas** [VivaPayments/API#2230]
We have a similar request to https://github.com/VivaPayments/API/issues/2223

Can you add balance to this merchant id is f726db45-af35-4175-b93b-54ecad79cb53
or provide instruction so we can do this ourselves?

**Comment by can3ry** [comment]
Hello @ntsagkas 

The balance has been added to your wallets.  In the meantime, we will discuss a solution for the insufficient balance issue. I'll keep you updated if there is any progress.

I've also noticed that you created a wallet for the seller account. If this is just for testing then it is fine, but if you are trying to test obligation API, you should create a separate account for the seller. So you can pass the seller's merchant ID and wallet ID to the obligation API.

Let us know if you need further information.

Kind regards,
Viva Wallet Development Team
