### ISSUE TITLE
WooCommerce - Pending status when order completed

### ISSUE THREAD

**Issue by netinfoplc** [VivaPayments/API#2232]
Hi,

For some reason, when orders are completed, the order that is being created in WooCommerce has status "Pending". In the settings of viva wallet i have the order status to be set as "completed" though. The funds are being received perfectly fine by the merchant.

Please advice

Thank you

**Comment by can3ry** [comment]
Hello @netinfoplc 

Thanks for your question.

I assume you are using [smart checkout](https://developer.vivawallet.com/plugins/woocommerce-smart-checkout/).  Please let me know if you use our [standard checkout](https://developer.vivawallet.com/plugins/woocommerce-standard-checkout/).

Here are some points to check for smart checkout,

1- Please make sure that you've set the success and fail URLs correctly. They can be set on the [source code](https://developer.vivawallet.com/getting-started/create-a-payment-source/payment-source-for-online-payments/) page.  

Plugin name | Success URL | Failure URL
-- | -- | --
WooCommerce Smart Checkout | index.php?wc-api=wc_vivawallet&vivawallet=success | index.php?wc-api=wc_vivawallet&vivawallet=fail

2- Please set a webhook if you get payments from [alternative payment methods](https://developer.vivawallet.com/payment-methods/local-payment-methods/). More information is available [here](https://developer.vivawallet.com/plugins/woocommerce-smart-checkout/#step-2-set-webhook).

3- Please let us know the version of your plugin. Also, confirm that you did not make a manual implementation.

Best regards
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hello @netinfoplc 

We will be closing out this issue now, but please do not hesitate to let us know if there is anything else we can assist with.

Kind regards,
Viva Wallet Development Team
