### ISSUE TITLE
PSD2 Account Information

### ISSUE THREAD

**Issue by frcake** [VivaPayments/API#2235]
Hello,

Do you offer an Account Information (accounts, account details, account balances, account transactions) API?

I don't seem to be able to find the equivalent to AISP PSD2 on your API Gateway.

Thanks :)

**Comment by can3ry** [comment]
Hi @frcake 

We are in the process of releasing new APIs to replace the existing ones, and we will let you know soon.

Best regards
Viva Wallet Development Team
