### ISSUE TITLE
403 Forbidden: Obligation API

### ISSUE THREAD

**Issue by galyfantis** [VivaPayments/API#2236]
Hello,

In order to test the obligation API in demo, we have followed the instructions given in https://github.com/VivaPayments/API/issues/2230#issuecomment-1195779428 , i.e., we have created a separate account for the seller.

However when we invoke the obligations endpoint we are receiving a response with status 403.

The call is made on behalf of merchant **7cd48fd4-a59c-4101-a6cc-fb93788ae880** with client id **9v5mvwjd295ph2u30j087b5t0yux9c3bf9h5d1qu5ema5.apps.vivapayments.com** and targets wallet **337858852512** of merchant **9ba2e790-58f0-4bd6-b4f9-e5b4ee672b3a** (seller)

This is the call we make 
```
curl --location --request POST 'https://demo-api.vivapayments.com/obligations/v1/obligations' \
--header 'Authorization: Bearer eyJhb..........................................Ll48w' \
--header 'Content-Type: application/json' \
--data-raw '{
    "amount": "45.00",
    "personId": "9ba2e790-58f0-4bd6-b4f9-e5b4ee672b3a",
    "walletId": "337858852512",
    "description": "You need to refund this amount",
    "currencyCode": "978"
}'
```
Any idea what might be wrong?

**Comment by can3ry** [comment]
Hello @galyfantis 

Could you please provide the below details?

*Merchant ID of the marketplace account

*Merchant ID of the platform account

*List the relevant Merchant IDs of the sellers(If you have any other than 9ba2e790-58f0-4bd6-b4f9-e5b4ee672b3a)

Best regards
Viva Wallet Development Team

**Comment by galyfantis** [comment]
Hello @can3ry , 

Both marketplace and platform account share the same mechantId: **7cd48fd4-a59c-4101-a6cc-fb93788ae880**

There is no other seller other than the one with merchantId **9ba2e790-58f0-4bd6-b4f9-e5b4ee672b3a**

**Comment by can3ry** [comment]
Hi @galyfantis 

Could you please create an account separately, and share the merchant ids? Please also inform us which one will be the marketplace owner account.

We also wonder, did you or a relevant person from your company talk to one of our sales representatives about the marketplace solution? If you share an email, we can contact you accordingly. That way we can be sure that there aren’t any mistakes or misinterpretations and it will allow us to answer you appropriately.

Best regards
Viva Wallet Development Team

**Comment by galyfantis** [comment]
Hello @can3ry ,

I don't think anyone from my company has talked to your sales representatives so far.

As for the technical part, I have made a separate account as you requested, so now we have the following demo setup:
* Platform Merchant ID: 7cd48fd4-a59c-4101-a6cc-fb93788ae880
* Markplace Owner Merchant ID: 737a7c47-fafa-40ab-adf9-ba9324cb297c
* Seller Merchant ID: 9ba2e790-58f0-4bd6-b4f9-e5b4ee672b3a

Please let me know when I could check again.

**Comment by can3ry** [comment]
Hello @galyfantis 

Thanks for the additional information.

I'll let you know as soon as the setup is ready.

Best regards
Viva Wallet Development Team

**Comment by galyfantis** [comment]
Hello @can3ry ,

Please get my email from the account with merchant id 7cd48fd4-a59c-4101-a6cc-fb93788ae880. I have set it as primary email.

**Comment by can3ry** [comment]
Hi @galyfantis 

We've sent the account details to your email.

I am closing this ticket for now but please do not hesitate to contact us if you need further information.

Thanks
Best regards
Viva Wallet Development Team

**Comment by galyfantis** [comment]
Hello @can3ry ,

As explained in our email discussion, it is important to us to that you mark our accounts as marketplace, so that we have a stable test environment.

Can you please re-open the current issue, so that you do what's required to our accounts as soon as your freeze period ends?

**Comment by gemitsio** [comment]
Hello @galyfantis,

I would like to inform you that the setup of your requested marketplace schema based to the provided MIDs, is In Progress and I will keep you informed when it is ready.

Thanks & Regards
Viva Wallet Development Team

**Comment by can3ry** [comment]
Hi @galyfantis 

We've completed the necessary actions for the accounts.

Could you please try again and let us know the result?

Thanks & Regards
Viva Wallet Development Team

**Comment by galyfantis** [comment]
Hello @can3ry ,

Thanks for taking necessary actions from your side.

I managed to call the obligations api successfuly this time.

For your reference, I repeated the same call shown in https://github.com/VivaPayments/API/issues/2236#issue-1326682502 and received the following response:

```json
{
    "captureId": null,
    "statusId": "A",
    "obligationId": "819c9e86-6e9f-464f-a966-a0c05f4e55a2",
    "cancellationId": null,
    "created": "2022-08-31T10:52:41.5244168+03:00",
    "completed": null,
    "walletTransactionSubTypeId": 159
}
```

**Comment by can3ry** [comment]
Hi @galyfantis 

Thanks for the confirmation. 

As you may already know, statusId: A means pending status. So the [obligation](https://developer.vivawallet.com/apis-for-payments/marketplace-api/#create-payment-obligation) needs to be captured. This will be done automatically if the account has enough funds. 

Please also do not forget to set up [webhooks for obligation API](https://developer.vivawallet.com/webhooks-for-payments/obligation-captured/).

If you need further assistance, please do not hesitate to raise a new ticket.

Thanks & Regards
Viva Wallet Development Team
