### ISSUE TITLE
Webhook event authentication

### ISSUE THREAD

**Issue by wgrabis** [VivaPayments/API#2237]
Hello,

I'm trying to integrate webhooks for transaction created and failed and I have a question about authentication of those endpoints. 
In the documentation it is mentioned that events are send in a Post request with basic authentication, however my solution is receiving no auth header in the request from the demo environment. 

Is it something configurable for webhooks or is there another way to authenticate that a request is coming from Viva Wallet? 

Thanks

**Comment by can3ry** [comment]
Hello @wgrabis 

Thanks for your query.

We've fixed the typo on our documentation.

Currently, the headers do not have authorization except for the ["sales transaction"](https://developer.vivawallet.com/webhooks-for-payments/sale-transactions/) webhook. So for all other webhooks, we recommend whitelisting [our IP addresses](https://developer.vivawallet.com/webhooks-for-payments/setting-up-webhooks/#whitelist-the-viva-wallet-addresses) for the defined URLs. 

In addition, when you get a webhook notification, please always [retrieve the transaction detail](https://developer.vivawallet.com/code-samples-for-payments/retrieve-transaction/) with our API and process it according to our response.

Best regards
Viva Wallet Development Team
