### ISSUE TITLE
Viva Wallet Smart Checkout Opencart Plugin Database Overloading

### ISSUE THREAD

**Issue by faisalmoon2** [VivaPayments/API#2239]
hi there, i was backing up my mysql database and have seen in the mysqlprefix_vivawallet_data is huge like 1gb+ what should i do should i truncate or it will interfere with transactions which have already been made. Please Help ASAP thanks.

**Comment by can3ry** [comment]
Hi @faisalmoon2 

The prefiix_vivawallet_data table in the **WooCommerce Smart Checkout plugin** manages the orders' status during and after a purchase. Truncating it does not affect the functionality of the plugin, but when doing this, If there are ongoing payments or if there are asynchronous pending payments, you may lose them.  To avoid such issues, you may keep the data for the last 3 days and delete the rest. 

We highly recommend making sure that you've made necessary backups before making any change on any table. 

Best regards
Viva Wallet Development Team
