### ISSUE TITLE
Cannot create webhooks

### ISSUE THREAD

**Issue by mm-kitchenswaps** [VivaPayments/API#2240]
I am trying to setup vivawallet and all supporting functionalities and I am now working on webhooks, but i am failing to see what i am doing wrong.

I am creating a webhook on viva but i get the message "URL not verified. Please enter a valid, publicly available, URL that conforms to [these guidelines](https://developer.vivawallet.com/web-api-integration/webhooks)"

But I am not sure what those guidelines really are. I have this endpoint https://kitchenswaps-api.herokuapp.com/api/payments/obligationCreated as a POST that's currently doing nothing. But it should be valid right? It's really not clear what the issue is...

**Comment by mm-kitchenswaps** [comment]
I even tried with pipedream and got this url but cannot verify it --> https://eo25g8d6qo88ssx.m.pipedream.net

It seems a bit cumbersome to setup and understand why it fails.

**Comment by can3ry** [comment]
Hi @mm-kitchenswaps 

Thanks for solving this issue.

We would appreciate it if you could also share your solution.

We see the Pipedream URL does not show a verification key. So it is normal to get an error for that URL. But the response in herokuapp domain seems correct. So was it about using the wrong verification key?

Best regards
Viva Wallet Development Team
