### ISSUE TITLE
Activating Android POS on demo account

### ISSUE THREAD

**Issue by drigler** [VivaPayments/API#2241]
Hi,
i'm trying to connect Andoid VW POS to demo merchant account with the activation code from the VW POS app, but it's failing without explanation or error code.

My demo Merchant ID is 280adb07-3c3e-40c8-9bac-a7d7f30c3e81

Also, I tried to activate it via intent deeplinks and the response error is:

mycallbackscheme://result?status=fail&message=UNEXPECTED&action=activatePos&virtualId=dEyCNtd-RQuaMjBVfVN_aQ&sourceTerminalId=0

What could be the problem? UNEXPECTED?

Tnx,
Denis

**Comment by cforrestvivawallet** [comment]
Hi @drigler,

Can you please confirm if you are using the Production or Demo VW POS app? The Demo app will have red '**DR**' text on the icon.

If you are using the the Production app (without the '**DR**' text), could you please send the email address associated with your Android / Google Play account to cforrest@vivawallet.com so I can get this email address whitelisted for you to be able to download the Demo application?

Kind regards,
Viva Wallet Development Team

**Comment by drigler** [comment]
Hi Chris,

 

I'm using the Production VW POS app, I did not know there is a Demo one (could not find it). So this is probably the reason why it is failing.

 

This is my email registered with Google play: ***@***.*** ***@***.***> 

 

Thanks.

 

Best regards,

 

Denis Rigler

**Comment by cforrestvivawallet** [comment]
Hi @drigler,

As discussed via email, your email address has now been whitelisted to download our Demo POS app.

I will close this ticket now, but please do not hesitate to get in touch if you need further assistance.

Kind regards,
Viva Wallet Development Team
