### ISSUE TITLE
WooCommerce: Items Meta Appearing When They Shouldn't Be

### ISSUE THREAD

**Issue by websitehelperuk** [VivaPayments/API#2254]
When paying with Viva Wallet additional Items Meta are appearing.

This only seems to be happening when paying with Viva.

![d25ecb601d9f8e39b1283f8777b104f7](https://user-images.githubusercontent.com/4172447/189092224-80160e15-ab42-4b5b-9513-afaaa1457bc3.png)

Something similar occurred with Paypal Checkout so wondering if this may be a similar problem:
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/535

**Comment by VivaWalletCustomerSupport** [comment]
Hello @websitehelperuk,

Thank you for contacting us. Could you please share with us your website address as well as the plugin version to investigate this issue? Thanks in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by websitehelperuk** [comment]
HI, 

It's version 1.4.7. https://tinyurl.com/3z6s3s48

**Comment by VivaWalletCustomerSupport** [comment]
Thank you for your prompt response. Where this information is being displayed?
- Thank you page.
- WordPress admin dashboard.
- Receipt.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by websitehelperuk** [comment]
Admin dashboard, thank you page and order details under customer account.

**Comment by VivaWalletCustomerSupport** [comment]
It appears that is not related to our plugin. To confirm it, try enabling a different method (cash on delivery) and check if the issue persists by executing a test transaction.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by websitehelperuk** [comment]
Yes, this was already done. We tested with cash on delivery and the problem does not appear.

I just tried again, once with cash on delivery and once with Viva, Viva returns the meta items. https://gyazo.com/9bbf56d56d19d2a9f58673f2019df34f

**Comment by websitehelperuk** [comment]
I will continue testing to see if I can find something with substance.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @websitehelperuk, did you find the time to investigate if it was a plugin or a  theme conflict? 

In any case this ticket will remain active for at least 24 hours, to come back if you wish. Thank you very much for contacting us.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @websitehelperuk,

I will close this ticket now, but please do not hesitate to get in touch if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
