### ISSUE TITLE
Question about installments - Woocommerce Smart Checkout 

### ISSUE THREAD

**Issue by ioweb-gr** [VivaPayments/API#2255]
Hello, 
I have an issue with installments. While I enable it on the plugin and set my preferences as described
![image](https://user-images.githubusercontent.com/20220341/189603137-34306a75-fd36-4dda-be1b-a0b4a58311b8.png)

I don't see the option on checkout
![image](https://user-images.githubusercontent.com/20220341/189603345-470ac081-240c-47ea-b8e8-d415b4cee8ad.png)

And it doesn't appear on the Vivawallet environment either. There is no php error in the logs, no javascript error on the browser and nothing is accidentally hidden with css. Recurring payments have been enabled in the viva backend. 

Do you have any idea what might be going on?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

The installments on our Woocommerce Smart Checkout plugin are showing on the Smart Checkout and not in the checkout of the website.

 In order the installments to be available the user should redirect to Smart Checkout, and fill his credit card details. Our system identifies that the card is a credit card and the installments become available. 

![image](https://user-images.githubusercontent.com/112542999/189609623-094cca55-ff5e-4f93-ac35-0493fe6683e5.png)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

Have you found the time to review our answer?

Therefore, this ticket will remain active for at least 24 hours, so that you can come back if you wish. Thank you very much for contacting us.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by ioweb-gr** [comment]
Hello issue was solved.
