### ISSUE TITLE
Random HTTP-502 errors around smart-checkout functionality

### ISSUE THREAD

**Issue by serafeimk** [VivaPayments/API#2256]
Dear experts,

for a long running customer of ours, which migrated since June 2022 to smart checkout functionality, we are experiencing occasional HTTP-502 errors (connection timed-out) that are hard to reproduce or to tackle.

The errors mentioned above are encountered either during the create order phase (checkout/v2/orders API call) or during the verification of transaction callback (checkout/v2/transactions/<tid> API call)

Some evidence around these cases, for our customer with merchant id ending in 06d0c5da6c2b, given in Europe/Athens timezone:

- 2022-09-11 15:38:35,764 - connection timed out error when verifying the status of transaction: da083079-777f-4ffb-a25d-f2578b2e93ba
- 2022-09-11 12:44:24,886 - timed out error during creation of order

Please note that our setup is based on Microsoft Azure, running Spring Boot v2.4 stack.

Any assistance is highly welcome,
Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @serafeimk,

Thank you very much for contacting us. I would like to inform you that we are investigating the information you provided and we will update you as soon as possible.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @serafeimk,

After reviewing the information, all your API calls on 11.09.2022 received an HTTP response 200 meaning that they were processed successfully. We didn't notice any timeout or latency on our server. 

We would like to suggest to check your server logs for random timeouts or latency. Also please review your API development.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @serafeimk,

Did you find the time to review our answer?

In any case this ticket will remain active for at least 24 hours, to come back if you wish. Thank you very much for contacting us.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by serafeimk** [comment]
Dear experts,

thanks for the assistance. We will further investigate this issue to our end, and come back to you, if anything relates to the API comes up.

Thanks again
