### ISSUE TITLE
We are not getting redirected back to our website after a succesfull payment with Redirection/Native Checkout v2

### ISSUE THREAD

**Issue by Octapius** [VivaPayments/API#2257]
Good Day,
We are implementing a demo version of Redirection/Native Checkout v2 and we are filling the form provided in https://demo.vivapayments.com/web/checkout?ref=5990882829972603. Nevertheless, after paying with a Successful or even Failed card, we are being redirected to https://demo.vivapayments.com/web/checkout/result?... instead of being redirected back to our provided url. 
We would like to resolve it and every possible assistance would matter to us.
Thank you for your help in advance.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Octapius,

Thank you for reaching out to us. Would you mind sharing with us the payment source used as well as the [configuration](https://developer.vivawallet.com/getting-started/create-a-payment-source/payment-source-for-online-payments/) of success & failure URLs? Thanks in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Octapius** [comment]
Thank you for your timely response.
I attach the full configuration card for convenience.
Also, the payment method is the following demo cards:

visa - 4147 4630 1111 0133 (success)
mastercard -  5239 2907 0000 0101  (success)
visa - 4147 4630 1111 0141 (failure)
mastercard - 5239 2907 0000 0119 (failure)

![vlpc](https://user-images.githubusercontent.com/54030839/190979615-ac7552c7-399f-4c1d-8c52-6f912776939e.PNG)

Looking forward to hearing back from you.

Your Best

**Comment by VivaWalletCustomerSupport** [comment]
Thank you for your prompt response.
Could you please forward us your API call/request (full code) for these transactions?

Looking forward for your reply.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Octapius** [comment]
**The model is** 
            ExternalPaymentRequestModel vm = new ExternalPaymentRequestModel();
            vm.allowRecurring = true;
            vm.amount = 200;
            vm.customerTrns = "Short description of items/services purchased to display to your customer";
            vm.email = "customer@domain.com";
            vm.fullName = "Customer name";
            vm.isPreAuth = true;
            vm.maxInstallments = 12;
            vm.merchantTrns= "Your reference";
            vm.paymentTimeOut = 86400;
            vm.phone = "2117604000";
            vm.requestLang ="el-GR";
            vm.tags = new string[] { "first", "second"};

**which i turn  into json**

**httpclient call is**

                using (HttpClient client = new HttpClient())
                {
                    client.BaseAddress = new Uri(ConfigurationManager.AppSettings["TokenRequestBaseAddress"]);
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    client.DefaultRequestHeaders.ConnectionClose = true; //(και χωρις αυτό, επιστρέφει το ίδιο αποτέλεσμα)
                    //
                    var authenticationString = $"{ConfigurationManager.AppSettings["MerchantId"]}:{ConfigurationManager.AppSettings["ApiKey"]}";
                    var base64EncodedAuthenticationString = Convert.ToBase64String(System.Text.ASCIIEncoding.ASCII.GetBytes(authenticationString));
                    //
                    HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, "api/orders");
                    request.Headers.Authorization = new AuthenticationHeaderValue("Basic", base64EncodedAuthenticationString);
                    request.Content = new StringContent(JsonConvert.SerializeObject(vm), Encoding.UTF8, "application/json");
                    //
                    var response = await client.SendAsync(request);
                    response.EnsureSuccessStatusCode();
                    rvm = JsonConvert.DeserializeObject<ExternalPaymentResponseModel>(response.Content.ReadAsStringAsync().Result);
                }

where TokenRequestBaseAddress = https://demo.vivapayments.com

Ευχαριστώ

**Comment by Octapius** [comment]
Very well It indeed worked.
Nevertheless, both visa and mastercard failure cards redirected to success url, BUT JCB(failure card) correctly redirected correctly to failure url.
Perhaps this has nothing to do with my app? Any feedback on the matter would be nice

Yours best

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Octapius,

I just wanted to follow up on the reply I sent yesterday. I was simply wondering if you read my response. Are there any other questions, I may help you with? 

In any case this conversation will remain active for at least 24 hours, so that you can come back if you wish. 

I hope this information helps, however, should you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Octapius ,

I will close this ticket now, but please do not hesitate to get in touch if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
