### ISSUE TITLE
redirect issue after successful payment

### ISSUE THREAD

**Issue by dihxo** [VivaPayments/API#226]
Hi,
in our site, which is now rebuilt, after viva successful payment the redirect goes to a unknown page.
![dihxo_viva](https://cloud.githubusercontent.com/assets/24971846/21761286/97c19d18-d65a-11e6-827d-abfb962222d6.png)
is this something configured at your end? or we have to do something in our site?

thanks in advance
eshop.dihxo.gr

**Comment by dmihos** [comment]
Hi
All you need to do is reconfigure the successs/fail urls for the sources you use (menu My Sales>Payment Sources)

**Comment by dihxo** [comment]
thanks a lot , will check that
