### ISSUE TITLE
Redirect issue about the Smart Checkout plugin with Woocommerce

### ISSUE THREAD

**Issue by klevezt** [VivaPayments/API#2260]
Good evening,

I have a problem with the redirection of the Smart Checkout plugin. Everything works fine until I successfully complete my payment at the Viva Wallet enviroment. When I am redirected back to my site, i get a **page not found** result , while at the meantime my cart isn't empty , meaning the transaction wasn't fully completed. 

My thinking is that it has something to do with the 's' parameter at the url. When i am redirected from the viva wallet enviroment to my site , the url has some parameters ( s , t , lang ) that are returned by Viva Wallet containing information about the transaction. I guess that this 's' parameter at the url is the same as wordpress's  's' parameter for searching, so that's the reason this 'Page not found' comes up.

I attach an image with the redirection result.

![309482108_5679875072073243_6373972498325820525_n](https://user-images.githubusercontent.com/36492558/193589312-cd82aec1-5587-40ee-99a6-3e20c1d731e7.jpg)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @klevezt,

Thank you for contacting us. In order we can review your ticket can you please provide your Viva Wallet Merchant ID? Also, it will be helpful to share with us a screenshot of your plugin's configuration. 

Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by klevezt** [comment]
Yes sure. 

My merchant ID is : 381bfcc3-20a2-4fa1-ab27-14bf17da928a.

### **Note that this is a demo account.**

![WooCommerce-settings](https://user-images.githubusercontent.com/36492558/193771939-3b925ef1-a889-4f46-8ad7-d49a4e26d844.png)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @klevezt,

Thank you for the information provided. Kindly note that the source with code 2828 in your Viva Wallet account should contain the following Success and Failure URLs : 

Success: index.php?wc-api=wc_vivawallet&vivawallet=success
Failure: index.php?wc-api=wc_vivawallet&vivawallet=fail

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by klevezt** [comment]
Ok , now it works. Thank you!
