### ISSUE TITLE
Issue with WooCommerce Standard Checkout Redirect link after sucesful payment

### ISSUE THREAD

**Issue by agorakis** [VivaPayments/API#2261]
Hi guys,

I installed your plugin and i wanted to use WooCommerce Standard Checkout in my site.  I works ok but i receive error 404 after succesfull payment.

In the final url is missing the the "checkout" path   **it is** https://www.gorakis.gr/order-received/78912/?key=wc_order_WlhT8pckfbvk

**instead to be**

https://www.gorakis.gr/**ταμείο/**order-received/78912/?key=wc_order_WlhT8pckfbvk

![printscreen](https://user-images.githubusercontent.com/108495758/193898606-1c1f62ee-69cb-4140-9e44-9ef537e7c6c0.jpg)

Please send me also the Sources for Online payments Success URL & Failure URL 

Thanks

**Comment by agorakis** [comment]
![image](https://user-images.githubusercontent.com/108495758/193899445-aa95e1f0-43d3-4177-affe-db0074c97023.png)

I set it up like this but it doesn work

**Comment by VivaWalletCustomerSupport** [comment]
Hello @agorakis,

Thank you very much for contacting us. Can you please send us a screenshot of your plugin's configuration? Feel free to blur out any confidential information on the settings. Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by agorakis** [comment]
![image](https://user-images.githubusercontent.com/108495758/194032508-bbc9ae0d-f16d-47f3-8b66-761a15201dae.png)

![image](https://user-images.githubusercontent.com/108495758/194032676-080cd5e5-545e-4c33-8e2f-84a4308b1286.png)

![image](https://user-images.githubusercontent.com/108495758/194032754-63265a09-7413-4d33-90c0-3fbf67c3057f.png)

![image](https://user-images.githubusercontent.com/108495758/194032905-a1718f7e-9984-4d52-9815-ebb262be98af.png)

**Comment by agorakis** [comment]
Hello Guys,

If you need more info's about my configuration please let me know

Best regards,
Antonis Gorakis

**Comment by VivaWalletCustomerSupport** [comment]
Hello @agorakis,

Thank you for the provided information. The correct success and failure URL for the source that our Woocommerce Standard Checkout  is using are the following:

Success URL: wc-api/wc_vivawallet_native_success
Failure URL: wc-api/wc_vivawallet_native_fail

Keep in mind that thank you page URL should not contain Greek and special characters.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by agorakis** [comment]
Thank you guys all fixed. The issue was "greek" permalinks
