### ISSUE TITLE
Please help me out

### ISSUE THREAD

**Issue by fazilfazil1** [VivaPayments/API#2267]
https://github.com/VivaPayments/API/issues/2266#issue-1414330797

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fazilfazil1,

Thank you for contacting us. We have noticed that you have raised a duplicate request regarding the same issue. With this in mind we will reply in #266.

Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team
