### ISSUE TITLE
crear orden de pago

### ISSUE THREAD

**Issue by mrusciel** [VivaPayments/API#2268]
Hola,

Estoy tratando de integrar el smart checkout pero al intentar crear la orden de pago me devuelve: "status":500,"message":"Update order 6116621340062089 failed","eventId":"0", en lugar de devolver el ordercode

No se como solucionarlo, dice que es un error del servidor, no entiendo.

Saludos,
Maite.

**Comment by mrusciel** [comment]
Hola,
La autenticación no tiene problemas, devuelve bien el token, aquí le envío
el código y la respuesta, quizás sea solo un detalle en la sintaxis,
utilizo variables para algunos parámetros:

$Login = curl_init("https://accounts.vivapayments.com/connect/token");
curl_setopt($Login, CURLOPT_RETURNTRANSFER,TRUE);
curl_setopt($Login, CURLOPT_HTTPHEADER, array("Authorization: Basic
 ".$codigoBase64,"Accept: application/json","Content-Type:
application/x-www-form-urlencoded"));
curl_setopt($Login, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
$res_login = curl_exec($Login);
$objRes_login = json_decode($res_login);
$Access_Token = $objRes_login->access_token;
curl_close($Login);
echo "Access token: ".$Access_Token;

//CREAR LA ORDEN DE COMPRA
$postFields  = [
    'amount'              => $total,
    'customerTrns'        => 'Pago de jugadas',
    'customer'            => [
        'email'       => $email,
        'fullName'    => $name,
        'phone'       => $phone,
        'countryCode' => $pais

    ]

];

$curl = curl_init();
curl_setopt_array($curl, array(
CURLOPT_URL => 'https://api.vivapayments.com/checkout/v2/orders',
CURLOPT_RETURNTRANSFER => true,
CURLOPT_ENCODING => '',
CURLOPT_MAXREDIRS => 10,
CURLOPT_TIMEOUT => 0,
CURLOPT_FOLLOWLOCATION => true,
CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
CURLOPT_CUSTOMREQUEST => 'POST',
CURLOPT_POSTFIELDS =>json_encode($postFields),
CURLOPT_HTTPHEADER => array(
"Authorization: Bearer $Access_Token",
"Content-Type: application/json"
),
));
$response = curl_exec($curl);
$objRes_RESP = json_decode($response);
$order = $objRes_RESP->orderCode;
curl_close($curl);
echo "Orden: ".$response;

Respuesta:
Access token:
eyJhbGciOiJSUzI1NiIsImtpZCI6IjYyODk4N0E3MDQ2QTUyQzkzMDY2NDJFMkJGQjBBNUY5OUJFQkFCQkVSUzI1NiIsIng1dCI6IllvbUhwd1JxVXNrd1prTGl2N0NsLVp2cnE3NCIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJodHRwczovL2FjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJuYmYiOjE2NjY2MzIwMzIsImlhdCI6MTY2NjYzMjAzMiwiZXhwIjoxNjY2NjM1NjMyLCJhdWQiOlsiY29yZV9hcGkiLCJodHRwczovL2FjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIl0sInNjb3BlIjpbInVybjp2aXZhOnBheW1lbnRzOmNvcmU6YXBpOmFjcXVpcmluZyIsInVybjp2aXZhOnBheW1lbnRzOmNvcmU6YXBpOmFjcXVpcmluZzpjYXJkdG9rZW5pemF0aW9uIiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6cmVkaXJlY3RjaGVja291dCJdLCJjbGllbnRfaWQiOiJ6ZmNzaDhrMTgzeGJkNWs2c3E2dWd5enZxMDg5Z3oycnQ1NGo2Z2R3d2d3azAuYXBwcy52aXZhcGF5bWVudHMuY29tIiwidXJuOnZpdmE6cGF5bWVudHM6Y2xpZW50X3BlcnNvbl9pZCI6IjUxNDc2MjMyLTM4NTYtNDg5RC04Q0Y4LUFFOERGRjhCMUVCNCJ9.gnyDTBa6GtxtDhc-E4l7KD5er9N4R9wniAnvGAvwoZ5Ma77DjJh2vdRhLMf6TwLoRH7fbsw2xiPqxhy5AeHTQbBaVcaQWJQVEFq-7YI8ktCQJwh6OL2JItb5_Y5v0b6dOwe3nCelBel10oLeY1HnNbW_FjnsC7Evf-w0P1IYPXT-stUf9Fg2VxO4lTxo6EV4SZDWNClKsTZ2lb-4cL1bOrByOamv1FICAh9UE29Bj3jKQ1rE_uZ9WfGLPUn98mk5DkguU9FvG8QopMANdhOGiXuurnMfd0rugmx-xQwt9tNOeN4US1Zg-QVKolz8VBEs42BPIREehkeFrsgdr4nBr7YVjGvqoD8V0Rfa_CAKuM38l-uaF6t9vTGJ35Ftwes2N2eIJfbp8JpUG7O0R4gdfMx9abdP1hQq9QClNdiKzsU86dYc7LEbyXAJOBA8Mhhpti5kYCI0-Kir2pZo8DM1z3Gv3cAYou3iJv6jb9p3atjILwrcTttGo89xvOdhwm21KTYLBlEoM4zcmvDH-zvXfe7mNzRtolzGcV6xZmht5T4DI58DRf_WJ05FoBHSf1DwaFQP4RlztEI0Vu0-53PoHH2IXumdFTrxfriSEqgKKf5Vb-Xf0a98ouaNIhtA_6xIa4Xz48j1k1LDiCiCwsRsa2xD2RPY5NuttyXyM_TpvfQOrden:
{"status":500,"message":"Update order 7023963290036633
failed","eventId":"0"}

Saludos cordiales,
Ing. Maite Rusciel

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mrusciel,

Thank you for your detailed response. Could you please forward us what you got on ''scope'' response? Under normal circumstances we should return the following response:

**"scope": "urn:viva:payments:core:api:acquiring urn:viva:payments:core:api:acquiring:cardtokenization urn:viva:payments:core:api:redirectcheckout"**

Looking forward for your reply.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by mrusciel** [comment]
Hello,

Thank you for your response, how can I get it? The scope response I mean.

 Sorry,
Maite Rusciel

**Comment by mrusciel** [comment]
I found it:
"scope":"urn:viva:payments:core:api:acquiring
urn:viva:payments:core:api:acquiring:cardtokenization
urn:viva:payments:core:api:redirectcheckout"

Kind Regards,
Maite Rusciel

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mrusciel,

Thank you for providing us the requested data. We need clarifications regarding '**Update order 7023963290036633**'. According to our systems this order code has not been created neither on live nor on demo account. 

What is the purpose of the update order? We do not provide a related parameter on our documentation. In any case try to run our example without adding extra information. Does that fix it?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by mrusciel** [comment]
Thank you for your response.

No se porqué devuelve esa respuesta lo que trato es de crear la orden y me
devuelve eso.... intentaré con el ejemplo a ver. Le comentaré el resultado.
Saludos cordiales,
Maite.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mrusciel,

Kindly keep us posted. In any case this conversation will remain active for at least 24 hours, so that you can come back if you wish. Thank you very much for contacting us.
I look forward to hearing from you!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mrusciel,

Since it's been a while since we last heard from you, we will close this ticket.
We hope this information helps, however, should you have any questions, please don't hesitate to reply back here and we would be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team
