### ISSUE TITLE
Checkout fails in Demo Environment

### ISSUE THREAD

**Issue by galyfantis** [VivaPayments/API#2272]
Hello,
There seems to be a problem with Checkout in the demo enviroment.

After I enter a test card and proceed to payment, processing takes a lot of time, and fails in the end.

After further investigation, I saw that the call to `https://demo.vivapayments.com/web2/checkout/v2/chargetokens` fails with a "Gateway Timeout" error (504) as you can see in the screenshot below:
![image](https://user-images.githubusercontent.com/11825259/198246614-c29f8ab8-9991-487f-ab48-952159299122.png)

Could you please take a look at it as it blocks our testing?

Thanks in advance.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @galyfantis,

Thank you for contacting us. Could you please forward us the following information to further investigate the issue?

- Your demo/live [merchant id](https://developer.vivawallet.com/getting-started/find-your-account-credentials/merchant-id-and-api-key/).
- The full Request information (including URL, Headers and Body & Endpoint).

Thanks in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by galyfantis** [comment]
The problem seems to have been resolved on your side. Now checkout works as it used to.

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Thank you for letting us know.

Should you have any other inquiries we are always here for you.

Kind regards,
Viva Wallet E-commerce Support Team
