### ISSUE TITLE
verificacion de pago

### ISSUE THREAD

**Issue by mrusciel** [VivaPayments/API#2273]
Hola,

He resuelto el problema anterior, muchas gracias, ya crea correctamente la orden de pago, ahora tengo un nuevo problema, cuando se realiza el pago en smart checkout, que funciona bien, no me lleva a la success url (aqui es donde capturo los datos de la transacción para guardarlos en la BD), si no regresa a mi comercio no consta que realizó el pago.

Saludos cordiales,
Ing. Maite Rusciel Garcia.

Nota: estamos en entorno vivo.

Está configurado en la cuenta de vivawallet:
![IMG-20221029-WA0060](https://user-images.githubusercontent.com/39914377/198839355-51aab5bb-c290-4915-a95a-0e9bd8439c30.jpg)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mrusciel,

Thank you very much for contacting us. Transactions will need to be completed from the correct source. In your code, please check the "sourceCode" parameter, which should use the 4-digit number of the source from which you want the purchases to be completed. You can find more information about the create payment order parameters [here](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/#step-1-create-the-payment-order).

**Comment by mrusciel** [comment]
Muchas gracias, resuelto, era el sourceCode que había q especificar. Puede
cerrar

Saludos cordiales,
ING. Maite Rusciel

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mrusciel,

Thank you very for informing us that your issue is resolved. If you do not have any further questions, feel free to close the ticket.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mrusciel,

We will close this ticket now, but please do not hesitate to get in touch if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
