### ISSUE TITLE
Print batch summary from Viva Wallet POS Cardlink API

### ISSUE THREAD

**Issue by devel-andro** [VivaPayments/API#2274]
Hello,

I am trying to integrate our ECR with the VivaWallet A920 POS using the Cardlink API. The sale request works as expected, but we need a possibility at the end of the day, when printing the Z report (the daily fiscal report) to also print the batch summary on the A920 and to close the current batch.

Currently, as I see on your developer website here https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/vivawallet-api-cl/batchmanagement/#batchmanagementrequest the batchManagementRequest can only open or close a batch. 

Is there a api request for printing first the batch summary and the transactions list before closing the current batch? I see that there is an option on the android app integration here https://developer.vivawallet.com/apis-for-point-of-sale/card-terminal-apps/android-app/batch/#batch-request that has open, close and printSummary options but I tried sending the printSummary command trough the network socket and the result was that the current batch was closed and no report was printed.

Thank,

Iulian

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

Thank you very much for contacting us. At the moment there is not such functionality available. Currently, development for this is not in our pipeline however we've noted your request for future improvements.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

First and foremost allow us to thank you for your detailed response. It is very important for us to receive feedback on the instructions we give as in this way we improve our services.

 Even though we can not promise that it will be resolved within the next period, we can assure you that your suggestion will be evaluated for future implementation.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

We will close this ticket now, but please do not hesitate to get in touch if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
