### ISSUE TITLE
Unable to perform any banktransfer operations

### ISSUE THREAD

**Issue by seka17** [VivaPayments/API#2275]
Hi! i'm stuck with banktransfers api, it requires urn:viva:payments:core:api:banktransfers which I'm unable to obtain via oauth2 auth method. I'm getting 403 errors with empty body.

Env: test
Merchant id:  33452b63-3ec2-4cce-880d-bd4988bf274c

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seka17,

Thank you very much for contacting us. We would like to inform you that our new [Bank Transfer API](https://developer.vivawallet.com/apis-for-payments/bank-transfer-api/) is still under development. We would recommend you to use our[ Bank transfer API (Deprecated)](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Bank-Account-(Deprecated)) which is completely functional.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seka17,

Did you find the time to review our answer?

In any case this ticket will remain active for at least 24 hours, to come back if you wish. Thank you very much for contacting us.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by seka17** [comment]
@VivaWalletCustomerSupport yeah, that helped, thanks. Are there're any possibilities that deprecated functionality will not work? And how to retrieve information about bank transfer? Don't see an API call to provide commandId and get status

**Comment by seka17** [comment]
Also I'm getting 403 error when trying to perform outgoing bank transfer in deprecated api in sandbox mode.

**Comment by seka17** [comment]
Okay, I see that 403 returns when my wallet is insufficient, which is not mentioned in the docs. But now it returns 452 status code which I'm unable to understand. Is it even working in sandbox mode? If not, how I can test it?

**Comment by seka17** [comment]
And is amount in outgoing bank transfer represents euros + cents or just euros? It's not clear from documentation. Fe if I send amount 105, it will be represented as 1.05€ or 105€?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seka17,

Thank you for your reply. Kindly note that we return a 452 error code in the event of **Insufficient Funds**. 

The amount associated with the payment order should be a positive, non-zero number. For example, if you want to create a payment for €105, you need to pass the value **10500**.

I hope this information helps, however, should you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seka17, 

We would like to inform you that you cannot get bank transfer information via API call. However if the response code is 200, rest assured that the bank transfer has been successfully executed.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by seka17** [comment]
@VivaWalletCustomerSupport thx for the quick response. Can you suggest a simple way to add funds on my wallet balance? Can't find anything in docs

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seka17,

We added funds in you demo Viva Wallet account as requested.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seka17,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response. Are there any other questions, we may help you with?

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

We hope this information helps, however, should you have any questions, please don't hesitate to reply back here and we would be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seka17,

We will close this ticket now, but please do not hesitate to get in touch if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by skuppuraj** [comment]
How to get the scope (urn:viva:payments:core:api:banktransfers) for the Link bank account API via the Oauth2 method?

If I choose for old API, The document says I have to validate IBAN
(It is strongly recommended to first make sure that the IBAN is valid by using the [Validate IBAN])(https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Bank-Account/paths/~1api~1bankaccounts~1ibans~1%7Biban%7D~1validate/get) API call.)

But the link for validating API not working. How to validate?
