### ISSUE TITLE
Sale API request always returns error when waking up from sleep

### ISSUE THREAD

**Issue by devel-andro** [VivaPayments/API#2276]
Hello,

I am trying to integrate our ECR with the VivaWallet A920 Pro POS using the Cardlink API.  Using the device as it comes from Vivapayments, when unused for 1 minute it will enter sleep mode, and this will suspend the POS application. If i try to connect to it and send a sale request through a network socket, the TCP connection will fail/suspend until I manually press the power button on the A920 Pro device, and then the sale request will appear on the device's screen.

Going through the power settings and battery optimization options on the A920Pro device, I selected that the POS application should not be suspended when the device goes to sleep. When I do that, the TCP connection will succeed even if the device is in sleep mode and sending the sale request will open the device's screen BUT the sale request will always fail with an undocumented error code:

0095|000036|210|00|KO|An error ocured||||||1.00|1010|00|00|00|00|00|00|    16179208||||||||||||

Sending the sale request again, will correctly be processed by the A920Pro device.

Is this normal behaviour, is there another way of waking up the device before sending the sale request, should we try to resend the sale request when we receive the KO message?

Thanks,

Iulian

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

Thank you very much for your feedback. Can you please provide us a video to investigate your request further. Also it will be helpful if you can send us your Sale API request (full code).

**Comment by devel-andro** [comment]
Hello,

All that is described above in my initial message was done using the recommended tool from your website: Hercules from HW-group.com.

The sequence was the following: 
1. Let the A920Pro go to sleep (the device's screen shuts down)
2. Connect to the A920Pro device using the local ip and port
3. I received the txReady response: 0014|810|00|000036
4. I sent the sale request: 0063|002690|200|00|12345678901234567890123456789012|1.00|0000|||||
5. The screen opens and I received: 0095|000036|210|00|KO|S-a produs o eroare||||||1.00|1010|00|00|00|00|00|00|    16179208||||||||||||

Repeating the process gives me the same result. One thing that I observed, yesterday it was a VW POS update and since then the device in ECR mode doesn't go to sleep anymore.

If there is any other information I can help you with please ask.

Best regards,

Iulian

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

We are currently investigating your issue and trying to reproduce it. We will inform you as soon as we have any update.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

Thank you for your patience. Kindly note that every sale request should have a different uniqueTxnId. The uniqueTxnId should be unique because it is connected to a specific transaction. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

Did you find the time to review our answer?

In any case this ticket will remain active for at least 24 hours, to come back if you wish. Thank you very much for contacting us.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

Thank you for letting us know. Kindly keep us posted on any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by devel-andro** [comment]
Hello,

So I have changed the code to generate unique TxnIds for each request. I don't receive the KO response message, but most of the times I receive a user cancel response (UC) with the data of the previous successful card transaction. Here is the log of the communication between of our ERP and the A920 Pro device (i have replaced the first 6 digits of the cards with *):

Connect response:  0014|810|00|000015
Sell command sent: 0062|221112|200|00|202211120326GestiPOS_2Vanz002690|14.50|0000||||
Response received: 0242|000015|210|00|00|Contactless/None~RRN:231613148006|VISA|************1912|148006|A01597|000001|14.50|00|00|00|00|00|00|00|    16179213|2316153586179213|2316153586||||||||aeedd2c3-b62c-4f3f-a57f-4941bf23e349|2022-11-12T15:26:56.5197989+02:00|1

Connect response:  0014|810|00|000016
Sell command sent: 0063|221112|200|00|202211120330GestiPOS_2Vanz002690|101.40|0000||||
Response received: 0230|000016|210|00|UC|Respins de ECR/ERP|VISA|************1912|148006|A01597|000001|101.40|1010|00|00|00|00|00|00|    16179213|2316153586179213|2316153586||||||||aeedd2c3-b62c-4f3f-a57f-4941bf23e349|2022-11-12T15:26:56.5197989+02:00|1

Connect response:  0014|810|00|000017
Sell command sent: 0063|221112|200|00|202211120330GestiPOS_2Vanz002690|101.40|0000||||
Response received: 0248|000017|210|00|00|Contactless/None~RRN:231613158713|MASTERCARD|************3873|158713|966295|000001|101.40|00|00|00|00|00|00|00|    16179213|2316153587179213|2316153587||||||||4b27e28a-5e11-47e5-a8cb-f63cc2c74499|2022-11-12T15:30:12.946253+02:00|1

So, as you can see above, I have a successful transaction (the first one), everything worked, the card was debited, the receipts were printed. On the second one, when sending the sell request, the device returns immediately a UserCancel response, but with the card data of the previous transaction. Repeating the request, the transaction is processed OK.

This scenario repeats itself on almost all transactions, not all of them.

The problem doesn't seam to be from our integration code, since the erroneous response comes from the A920 Pro device.

Please advise,

With warm regards,

Iulian

**Comment by devel-andro** [comment]
Hello,

No, the problem still remains as described above in my last message, I get immediately a user cancel request after sending the sell command. The only way we can avoid that is if before the sale person, before choosing in the ERP the card sale command, manually wakes up the A920 Pro device by pressing the power button.

So, if the A920 Pro devices has the screen open then everything works as expected. Otherwise for things to work we have to press the power button on the A920 Pro device to wake it up and then send the sale request from the ERP.

Please advise,

With warm regards,

Iulian

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

Sorry for the inconvenience. We are still investigating your issue. We will inform you as soon as possible.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by devel-andro** [comment]
Hello,

Doing further investigations the issue seems to be due to the fact that the screen is not open / or fully open when the sale request is sent. I have placed some sleep time between the steps to see what is happening and the results are the following:

With the screen **recently closed**:

1. I connect from the ERP to the A920 Pro device and I receive the txReady message. **The screen remains closed**
2. I send the sale request, the screen opens and two scenarios happen. We have 2 A920 Pro devices, each one connected to a different Windows machine. One of them is a bit slower than the other one, the interface is a bit laggy, I don't know why because we bought them both at the same time. On the laggy device, 99% of the times after sending the sale request, the device will send us back immediately a User Cancel response (UC code) with the message "Rejected by ECR/ERP", the screen will open and it will show the main screen of the POS application without any sum on it (please mind you that at this point no card or NFC device has been approached to the A920 Pro device). On the other device approximately 80% of the times the screen will open and the sale amount will appear correctly, and on the other 20% of the times it will behave like the laggyer one. 

With the screen **closed for some time**:
1. I try to connect from the ERP to the A920 Pro device and the thread blocks, the screen on the A920 Pro device remains closed. If then I press on the power button of the A920 Pro device, the screen opens and the sale steps/process continues and it works as expected. This happens on both of the devices.

With the **screen opened**:
Everything works as expected.

So as I see it, the error is due to the screen being closed and not "fully opened" when the POS application tries to show the sale amount of the device screen. When this happens I'm guessing that an error is generated in the POS application and it returns to the ERP in the form of the User Canceled | Rejected by ECR/ERP response.

When the screen is closed for some time I am guessing that the POS application is suspended by the Android OS and this is why the ERP cannot connect to it, only then I manually open the screen of the  A920 Pro device.

So, if the above diagnostic is correct, then there should be two fixes:
1. Excluding the POS application from the battery optimisation.
2. Maybe opening the screen at the connect request, not on the sale request, will confirm that when the ERP is receiving the txReady message, the A920 Pro device is **realy** ready to receive the sale request.

Please let me know if there is anything else I should try.

Thank,

Iulian

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

We would like to inform you that we locked the terminal again. If you didn't complete the necessary actions please inform us in this ticket to unlock it anew. 

Also this ticket will close. If you need further assistance, you can reopen this or create a new ticket.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by devel-andro** [comment]
Hello,

Unfortunately this issue is not fixed. To replicate it is as simple as this:

1. Starting with the A920 Pro device's screen opened, the VW POS application opened, all transactions sent from the windows machine ERP working.
2. Shortly press the power button on the A920 Pro device to close the screen.
3. Try to send another transaction from the ERP machine. => Error

The result is that the sale transaction will return immediately with a User Cancel response (UC code) with the message "Rejected by ECR/ERP". Please note that at this moment no card or nfc device has been approached to the A920 Pro device.

Kind regards,
Iulian

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devel-andro,

Thank you for your response. We identified the bug and we are developing the solution. It will be available in the next update.

Kind regards,
Viva Wallet E-commerce Support Team
