### ISSUE TITLE
Smart checkout transactions saved as pending and redirected on failure redirect

### ISSUE THREAD

**Issue by tolisp** [VivaPayments/API#2280]
Hello, i have created a small script for a client on a demo account for a client using the smart checkout. everything works fine except that after payment i am sent to the failure redirect and the transaction is saved in the payment notifications as Pending.
Here is the CURL object sent
 curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://demo-api.vivapayments.com/checkout/v2/orders',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
 "amount": 2000,
 "customerTrns": "Transaction for xxxxxxxxxxxxx test",
 "customer": {"email": "'.$data['email'].'","fullName": "'.$data['name'].'","countryCode": "GR","requestLang": "el-GR"},
 "paymentTimeout": 0,
 "preauth": true,
 "allowRecurring": false,
 "maxInstallments": 0,
 "paymentNotification": true,
 "tipAmount": 1,
 "disableExactAmount": false,
 "disableCash": true,
 "disableWallet": false,
 "sourceCode": "9075",
 "merchantTrns": "test tolis",
 "tags": ["xxxxxxx"]
}',

and here is the info on the pending payments from the backend

Order Code | 3236118739972606
-- | --
Creation date | 11/11/2022 1:27:16 μμ
Customer Name | sfgsdgf
Customer e-mail | xxxxxxxx@gmail.com
Merchant Reference | test tolis
Description for customer | Transaction for xxxxxx test
Payment Source | xxxxxxxx.org
Currency | EUR
Amount | 20,00
Installments Allowed | None
Expiry Date | 11/11/2022 1:57:16 μμ
Status | Pending
Tags | xxxxxxx

Any ideas where  could this be going wrong?
Thanks
Tolis

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tolisp,

Thank you very much for contacting us. Kindly note that the parameter "paymentTimeout" is the parameter that sets the time given to the customer to complete the payment. If the value of this parameter is 0 the order code immediately expires. The default value of this parameter is 1800. (1800s equals to 30 minutes).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by tolisp** [comment]
Hi @VivaWalletCustomerSupport  i did the change but the issue is not fixed, for reference the redirect url is 
?order=8542457229172605&lang=el-GR&eventId=0  (i have manually edited the s keyword for ordercode as the s is a reserved GET variable in wordpress for search)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tolisp,

Thank you for your prompt response. Can you please provide us your demo MID to investigate your issue?
Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by tolisp** [comment]
Hi @VivaWalletCustomerSupport  sorry for this but i just saw that the system sends an email to confirm the payment to the buyer. I was able to click the button, and pay through the browser on my mobile. The transaction is set to paid and i am redirectd to the success page. Just one small question, if i did the payment from the link to the email i received, what is the point in having the issue in the smartcheckout in the script in the first place as i have to re do the payment from the email i receive?

I hope my question is clear
Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tolisp,

Thank you for your provided information. If you want to integrate Smart Checkout on a website and you wish the customers to pay via the website, the parameter "paymentNotification" should be set to false. If you wish to create a payment order, and then send out an email to the customer to request payment, rather than immediately redirect the customer to the payment page to pay now, set the value to true, and the system will automatically send the customer an email notification. This is equivalent to sending a payment notification from the Viva Wallet banking app.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by tolisp** [comment]
OK @VivaWalletCustomerSupport thanks, i will try this
Take care

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tolisp,

Thank you for letting us know. Kindly keep us posted on any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by tolisp** [comment]
Hello @VivaWalletCustomerSupport 
the issue is still not fixed. I have created the simple script at beta.redpad.org/viva and i am stopping before the redirect to viva with the ordercode which is displayed in the page. In the console you can also see the auth token and data passed to get the token and the response i get with the ordercode. The only thing changed after setting notifications to false is that no transactions are recorded in the backend (viva) and no emals are sent. The responce i get is with eventID 0

Thanks again

**Comment by tolisp** [comment]
hello @VivaWalletCustomerSupport 
as i mentioned earlier, the s parameter in wordpress is reserved for search keywords and i had to change it to the parameter order. If you think this is the problem i can change it over again. I also need to mention that the demo account i use never sent me a sms verification and i use 111111 responce to login, not sure if that helps

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tolisp, 

Thank you very much for the provided information. Can you please change the Order Code parameter to the default name and try to complete a transaction again? For Demo accounts, you should always use the code ‘111111’ when prompted with the Two-Factor Authentication pop-up as you already did.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello again @tolisp,

Can you please send us the new script you are trying to implement? Also can we have access to your beta website to run some tests on the checkout? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tolisp,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tolisp,

We will close this ticket now, but please do not hesitate to get in touch if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by tolisp** [comment]
Hello, sorry for the late reply as i was unavailable. The issue still occurs. I have created a small repo with the code (php and js files) so you can see it too.
https://github.com/tolisp/viva

Best
Tolis
