### ISSUE TITLE
Where can I find VW POS Demo app?

### ISSUE THREAD

**Issue by BodulKrk** [VivaPayments/API#2281]
Hello, I saw in previous issues that I need the VW POS Demo app to test my integration with demo.vivapayments.com.
Can you point me in the right direction? Where can I find that app?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BodulKrk,

Thank you very much for contacting us. Could you please send the email address associated with your Android / Google Play account to [support@vivawallet.com](mailto:support@vivawallet.com) so we can get this email address whitelisted for you to be able to download the Demo application?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by BodulKrk** [comment]
Thank you. I have everything I need now.
