### ISSUE TITLE
Issue a refund over API

### ISSUE THREAD

**Issue by pbsis** [VivaPayments/API#2286]
We have recently integrated our site into the Smart Checkout using the "/checkout/v2/orders" and "/checkout/v2/transactions" endpoints.

We would also like to automate the processing of refunds but the operation pointed at by the following article is marked as deprecated:

https://developer.vivawallet.com/tutorials/payments/issue-a-refund/#refunds-via-api

Is there a new method for refunding a transaction in the V2 API?

Thanks!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pbsis,

Thank you very much for contacting us. We would like to inform you that our deprecated API's are still fully functional until the new API's are released. Feel free to use the [Cancel Transaction API](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)/paths/~1api~1transactions~1{id}/delete) until a new one is released.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by pbsis** [comment]
Thanks we'll give it a go!
