### ISSUE TITLE
Available Ballance not update

### ISSUE THREAD

**Issue by IliasStathakopoulos** [VivaPayments/API#2287]
I have implement the smart checkout  way for my transactions and  i work at sandbox demo account. I am making successful transactions but the money i made from sales transactions not showing at my Available  Balance. Is it ok  that?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @IliasStathakopoulos,

Thank you very much for contacting us. Kindly note that transactions on the demo account are not getting cleared. If you need funds in your demo account feel free to inform us and we will add them. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by IliasStathakopoulos** [comment]
Hi @VivaWalletCustomerSupport 
Thank you for your quick response!
