### ISSUE TITLE
About the attachement that the user uploads after the transcaction 

### ISSUE THREAD

**Issue by Zeusakos** [VivaPayments/API#2288]
I am using the account trancaction created webhook and i would like to ask if there is any way to get the attachment that the user uploads after the transaction via Api?

Thank you for your time!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Zeusakos,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Zeusakos** [comment]
sorry for the late respone.
The user uploads his receipt and then in his employee card we can see the receipt uploaded for the transcaction that he has done. Is it possible in the json of acount trancaction created webhook that we utilized to  track our organization trancactions to have this image also? Or in any other way with another webhook.

Thank you for your time

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Zeusakos,

Currently there is no method available to get receipts of payments paid from employee card via webhook URL. However, we have noted your request for future improvements.

Please let us know if there is anything further we can assist with.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Zeusakos,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Zeusakos,

I am closing this ticket for now.

Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
