### ISSUE TITLE
Live urls

### ISSUE THREAD

**Issue by zygos29** [VivaPayments/API#2290]
I am trying to find the live urls for REST api
https://demo-api.vivapayments.com/ecr/v1/devices:search
what would be the live url for this ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @zygos29,

Thank you very much for contacting us. Keep in mind that the Rest API is still under development. Also due to this there are some gaps in our documentation, which will be completed soon.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by zygos29** [comment]
Thanks but since POS APIs Credentials is already available in production i should be able to know the live urls. Am i wrong ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @zygos29,

Thank you for your prompt response. The production URLs will be added in our documentation when the development is finished.

For more up to date information about our REST API please check our [developer's portal](https://developer.vivawallet.com/) regularly.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by zygos29** [comment]
Hello
yes I did

**Comment by VivaWalletCustomerSupport** [comment]
Hello @zygos29, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
