### ISSUE TITLE
Demo  Error 500

### ISSUE THREAD

**Issue by 01generator** [VivaPayments/API#2291]
Hello,

Demo environment in API Access Results in 500 Error!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @01generator,

Thank you very much for contacting us. Can you please provide us the Merchant ID of the demo account and the correlation ID of the error. Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by 01generator** [comment]
Hello,

I can not get mechant ID cause the API Access page results in 500 error. 
Demo viva account ID is 543852147382

**Comment by VivaWalletCustomerSupport** [comment]
Hello @01generator,

Thank you very much for your prompt response. Can you please share a screenshot of the error and the correlation ID of the error?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by 01generator** [comment]
![Στιγμιότυπο οθόνης 2022-11-30, 3 25 02 πμ](https://user-images.githubusercontent.com/17577172/204684848-aaea1372-3526-49a4-8124-3c98654335f0.png)
There is no correlation ID :/

**Comment by VivaWalletCustomerSupport** [comment]
Hello @01generator,

Thank you for the additional information. Kindly note that to investigate your request we will need the correlation ID of the error. In order to find it you can open the inspector on your browser and navigate to Network tab. 

Additionally, we would like to suggest you to create a new demo account because as it seems your demo is quite old and maybe some of its elements are deprecated.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by 01generator** [comment]
Hello,

There is no correlation ID in network tab(headers whatsoever)
I have tried another account, same result.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @01generator, 

Thank you for your prompt response. Can you please provide to us the Demo viva account  ID of the second demo account as well so we can investigate the issue on both accounts? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @01generator,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @01generator,

We would like to inform you that we will close this ticket for now. Please don't hesitate to raise a new ticket or reopen this ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
