### ISSUE TITLE
WooCommerce Smart Checkout plugin - new order email not sent to admin email

### ISSUE THREAD

**Issue by kpanosgr** [VivaPayments/API#2292]
Hello all,

it has been reported that when a new order is created, when payment method is selected "Pay via Viva wallet", the new order email is not sent to the admin email. However, the email to the customer is sent as expected.

Any thoughts?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kpanosgr, 

Thank you very much for contacting us. Can you please provide us the Merchant ID of the Viva Wallet account and a screenshot of your plugin's configuration?

Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by kpanosgr** [comment]
Problem solved. It had to do with the viva wallet account settings, not the plugin. Sorry for any inconvenience.
