### ISSUE TITLE
SmartCheckout wrong preselected payment method

### ISSUE THREAD

**Issue by robman70** [VivaPayments/API#2296]
Hi,
I'm trying to test SmartCheckout payments but I have a problem selecting the default payment method (https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/#optional-specify-pre-selected-payment-method).

The generated link is: https://demo.vivapayments.com/web/checkout?ref={MyOrderCode}&color=bc280a&paymentMethod=23&lang=it-IT but the default method I see is 'Samsung Pay'.

Did I something wrong?

![image](https://user-images.githubusercontent.com/48312792/205873514-25b9badd-d07c-4c03-9a0a-6ab13b643d95.png)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @robman70,

Thank you very much for contacting us. Please note that the pre-selected method that is used, should be active on the Viva Wallet account. Preselected payment method 23 is PayPal. Instructions on how to activate PayPal can be found [here](https://developer.vivawallet.com/payment-methods/digital-wallets/paypal/).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by robman70** [comment]
Thanks for the quick response.
I had already done the test integration following the instructions but what I see is this:

![image](https://user-images.githubusercontent.com/48312792/205903920-a08c7768-2a81-495e-a4dc-02c3e73165ab.png)

Does this mean that the integration was not successful?
I tried again now... I clicked on the 'Enable Paypal as a payment method' button, logged in (successfully) and clicked 'Return to test site' (or something like that).

**Comment by VivaWalletCustomerSupport** [comment]
Hello @robman70, 

Thank you for your prompt response. Are you trying to integrate PayPal with a demo Viva Wallet account? Kindly note that demo Viva Wallet accounts can be integrated only with sandbox PayPal accounts. More information can be found [here](https://developer.vivawallet.com/payment-methods/digital-wallets/paypal/#sandbox-demo-mode-optional).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by robman70** [comment]
Thanks but I had already done everything (with a sandbox developer account).
I redid everything again following the procedure step by step again but nothing changes. :-(

**Comment by VivaWalletCustomerSupport** [comment]
Hello @robman70,

Thank you for your answer. Is your PayPal sandbox account a business account? Can you please provide the MID of your demo Viva Wallet account and the MID of your sandbox PayPal account to investigate it further?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by robman70** [comment]
Hi,
yes, it's a Paypal developer (sandbox) business account.

Viva Wallet Test MID: ef062ce6-5481-4d5d-b5d1-b87676bba2ae
Paypal e-mail ID: sb-hf40p22954154@business.example.com (is it enough?)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @robman70,

Thank you for the prompt response. We are investigating your issue concerning the PayPal integration. About the preselected payment method, Samsung Pay is enabled and visible by default on Smart Checkout. Below Samsung Pay, debit card payment method should appear. Regardless of the payment method selected, Samsung pay will be displayed to the user.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by robman70** [comment]
Really??? Is this also the case in the 'paid' (ie non-test) version and there is no way to remove it or make it appear as a second choice?

**Comment by robman70** [comment]
> You can contact us via e-mail at [support@vivawallet.com](mailto:support@vivawallet.com) or via live chat and we can disable the payment method you desire

Ok, thank you. I will continue this discussion privately via e-mail

> About your PayPal issue, in our logs we cannot see any error or malfunction. Can you please try and re-integrate it from a different browser or an incognito window?

Ok, I'll try

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @robman70,

Thank you very much for your prompt response. In any case this ticket will remain active for another 24 hours to come back if you wish.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @robman70,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by robman70** [comment]
How can I get support?
I wrote to support on December 7th and sent two reminders, what should I do?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @robman70,

Sorry for the inconvenience and the late response. Can you please send us the sender's email address so we can investigate it?

Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by robman70** [comment]
> Hello @robman70,
> 
> Sorry for the inconvenience and the late response. Can you please send us the sender's email address so we can investigate it?
> 
> Thank you in advance.
> 
> Kind regards, Viva Wallet E-commerce Support Team

roberto.mannelli@mm-studio.com

**Comment by VivaWalletCustomerSupport** [comment]
Hello @robman70,

Thank you for the prompt response. We didn't receive any e-mails with sender's email [roberto.mannelli@mm-studio.com](mailto:roberto.mannelli@mm-studio.com). In order to support you in the best and fastest way, we would like to advise you to start a live chat with us and send us your request. 

You can access this by clicking on the chat icon in the bottom-right corner of our [developer portal](https://developer.vivawallet.com/) or [main website](https://www.vivawallet.com/).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @robman70,

Thank you for the feedback. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
