### ISSUE TITLE
Webhook - Smart checkout integration

### ISSUE THREAD

**Issue by MaestrelWP** [VivaPayments/API#2299]
Hi,

I am developing the integration of VivaWallet Smart Checkout as payment gateway for my WordPress online booking system plugin. I could correctly create the payment order and have the redirection to VivaWallet payment page. I am now dealing with the treatment of the payment response and customer redirection.

I usually revert the customer to the page where he started the booking/payment process (be it a case of failure or success) and display a response (do following actions) depending on the response caught in the meantime with the webhook (asynchronous). I have 2 issues with VivaWallet implementation:

- Is there any way with the Payments API (Create Payment Order) to pass as parameter the "Success URL" and "Failure URL" (to override the values in the "Payment source" dashboard)? As I wish to redirect the customer to the URL from which the booking/payment process was initiated, it can have different values (booking form on different pages for example).
Update: I have managed to work around this, saving the URL from which the booking process was done, and redirecting myself to the correct page. However, this is not ideal and it would be great if VivaWallet had some parameters that could be passed and that would override the dashboard settings for Success and Failure URL. It is very common amongst payment gateways.

- I am using the Webhook "Transaction Payment Created" in VivaWallet dashboard. I had to use the Basic Auth to be able to have the webhook url validated. Isn't there a possibility to get the Key from https://demo.vivapayments.com/api/messages/config/token, using the Smart Checkout credentials? For me, it means that I need to have 2 additional fields for our users to enter their Merchant ID and API key, only for the webhook authentication... 

Thank you!

Kind regards,

Celine, Maestrel

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MaestrelWP,

Thank you very much for contacting us. We would like to inform you that we always consider customer's feedback and observations for future improvements. We will consider your request and there is a possibility that this improvement will be available in the future. You can visit the developer's portal regularly to stay updated on future additions.

About the webhook validation, the validation is only available via[ Basic Auth authentication](https://developer.vivawallet.com/integration-reference/basic-auth/).

Kind regards,
Viva Wallet E-commerce Support Team
