### ISSUE TITLE
Viva Payments implementation to woocommerce eshop

### ISSUE THREAD

**Issue by christoschronopoulos** [VivaPayments/API#23]
Hi everyone,
I try to implement Viva Payments as a payment gateway into a new eshop I create for a friend. For testing purposes I also created a demo Viva Payments account but i can't find the proper sample code in order to redirect the potential customers to Viva secure page to checkout when they choose "viva" as payment method and press the "checkout" button. I have read many articles in the knowledge base and the github wiki as well. I would like to receive a more understandable reply in order to make use of the Viva Payments which i believe would enchance the overall buying experience for future customers. Thank you in advance.

**Comment by markware** [comment]
Hi did you check the code in the reps? https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php
or is it something else you want?

**Comment by christoschronopoulos** [comment]
Thank you for the reply. How can I make the create_order code to be trigered when the payment method is checked and the "checkout" button is pressed. Also, where it specifies the redirection URL (Viva secure page)?  Sorry for the huge amount of questions but I am trying to learn..

**Comment by markware** [comment]
First you will go to Sales->Payments sources, by clicking in the Default link it will open a modal window with the intergration method, which is Redirection for you. Then define the callback pages after a success or failure(make sure you have added your domain name). The link is here
<a href="http://demo.vivapayments.com/web/newtransaction.aspx?ref='.$orderId.'" >Make Payment</a>'; (replace the demo.vivapayments.com with https://www.vivapayments.com- only in production). Are you using a custom cms  or something else?

**Comment by christoschronopoulos** [comment]
I created the site / eshop using WordPress and woocommerce plugin. I have already gone to Sales-> Payment sources. However I am not sure where to add the  create_order code.

**Comment by markware** [comment]
you can add a hook in the checkout woocommerce action(http://docs.woothemes.com/wc-apidocs/hook-docs.html)  or buy a plugin to do the job for you

**Comment by christoschronopoulos** [comment]
I would like to avoid buying a commercial plugin. I will dig deeper concerning the hooks.

**Comment by markware** [comment]
thats true! have fun with woocommerce !

**Comment by npasadakis** [comment]
Hi Christos. Did you manage it? I'm thinking of doing the same thing. Any pointers?

**Comment by christoschronopoulos** [comment]
Finally we decided to solve our problem using a commercial plugin by ActionWeb! It is well-built and the support team helped us a lot in terms of installation and configuration!

**Comment by npasadakis** [comment]
I think I'll give it a try myself. Thanks

**Comment by MasterJuan** [comment]
Hey @christoschronopoulos could you please send me an email of ActionWeb in order to test this solution? It uses native checkout functionality or the redirect one?
