### ISSUE TITLE
Σύνδεση με Prestashop

### ISSUE THREAD

**Issue by snikolaidis** [VivaPayments/API#230]
Καλησπέρα! Υπάρχει κάποιο plugin ή κάποια οδηγία για το πώς μπορούμε να συνδέσουμε το VivaPayments με Prestashop? Όχι να το δημιουργήσουμε κατ'ανάγκη από το μηδέν, αλλά εάν υπάρχει κάποιο plugin που να κάνει αυτή την επικοινωνία, θα θέλαμε να το κοιτάξουμε.

Σας ευχαριστώ εκ των προτέρων. Με εκτίμηση,
Στράτος Νικολαΐδης

**Comment by dmihos** [comment]
Καλησπέρα σας

Η Viva Payments δεν προσφέρει κάποιο official plugin προς το παρόν, ωστόσο υπάρχουν στην αγορά διάφορα διαθέσιμα, επί πληρωμή.
Ένα από αυτά, μάλιστα, είναι και officially recommended από το PrestaShop.
Μπορείτε να κοιτάξετε προς αυτή την κατεύθυνση.
Αν υπάρξει κάποιο θέμα στη διασύνδεση του account με το plugin, είμαστε στη διάθεσή σας.

Ευχαριστούμε για την επικοινωνία

**Comment by snikolaidis** [comment]
Καλησπέρα και πάλι και ευχαριστώ για την πληροφορία. Ήδη έχουμε βρει το addon και θα προβούμε στην αγορά του. Εν τω μεταξύ, μας είπαν ότι θα χρειαστούν τα merchantid και api key. Υπάρχει κάποιο documentation για το πώς μπορούμε να τα βρούμε αυτά, για να το στείλω στον ιδιοκτήτη του λογαριασμού;

Σας ευχαριστώ εκ των προτέρων. Με εκτίμηση,
Στράτος Νικολαΐδης

**Comment by dmihos** [comment]
Καλησπέρα σας
Τα στοιχεία διασύνδεσης με το API φαίνονται στο μενού Ρυθμίσεις > Πρόσβαση API, αφού πρώτα γίνει login με τον επαγγελματικό λογαριασμό στο https://www.vivawallet.com.

Στη διάθεσή σας
