### ISSUE TITLE
Fatal error on Magento 2.3.7 and version 1.0.4

### ISSUE THREAD

**Issue by ioweb-gr** [VivaPayments/API#2305]
After a successful payment we receive this fatal error 

when the callback URL is invoked

`"GET /vivapayments/viva/callback HTTP/1.0" 500 1178 "https://www.vivapayments.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"`

The error is

```
Uncaught TypeError: urlencode() expects parameter 1 to be string, null given in /var/www/vhosts/example.com/httpdocs/app/code/Ced/VivaPayments/Controller/Viva/Callback.php:112\nStack trace:\n#0 /var/www/vhosts/example.com/httpdocs/app/code/Ced/VivaPayments/Controller/Viva/Callback.php(112): urlencode()\n#1 /var/www/vhosts/example.com/httpdocs/app/code/Ced/VivaPayments/Controller/Viva/Callback.php(84): Ced\\VivaPayments\\Controller\\Viva\\Callback->paymentAction()\n#2 /var/www/vhosts/example.com/httpdocs/vendor/magento/framework/App/Action/Action.php(108): Ced\\VivaPayments\\Controller\\Viva\\Callback->execute()\n#3 /var/www/vhosts/example.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\App\\Action\\Action->dispatch()\n#4 /var/www/vhosts/example.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Ced\\VivaPayments\\Controller\\Viva\\Callback\\Interceptor->___callParent()\n#5 /var/www/vhosts/example.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153):...', referer: https://www.vivapayments.com/
```

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

Thank you very much for contacting us. Can you please provide us the merchant ID of the Viva Wallet account that your site is integrated into? Also, can you share with us a screenshot of your module settings? Feel free to blur out any confidential information of the settings.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by ioweb-gr** [comment]
Let me provide the settings really quickly 

![image](https://user-images.githubusercontent.com/20220341/210218844-59d9ab32-08cb-42e7-9b66-0955b5a02926.png)


The merchant id is 

9b115bbf-e686-4d88-a638-4a828c869ce5

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

Thank you for the provided information. Can you please share with us the domain of the website? Is this error occurs in every completed transaction or in a specific one?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by ioweb-gr** [comment]
Hi can I share the domain somewhere private? The error constantly occurs

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

Thank you for the prompt response. Feel free to  send the domain to support@vivawallet.com. Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

We observed that in the source the website is using the domain has been declared with the following format, www.domain.gr. When we put the domain on a browser the domain appears without the www. Kindly note that the domain of the source should match the primary domain that has been declared to appear on the browsers.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by ioweb-gr** [comment]
I'll change it and report back

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

Thank you for the fast response. We will await your report. Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if the issue is resolved.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by ioweb-gr** [comment]
Sorry for the late response, it seems it's working fine for now.
