### ISSUE TITLE
Transaction Payment Created - webhook not firing

### ISSUE THREAD

**Issue by Kruki** [VivaPayments/API#2307]
Hi,
i am trying to integrate SmartCheckout in our solution, but i am stuck at validating payments.

I created a webhook and successfully verified the URL. When i then test the webhook by buying something (everything in demo-account), my API does not receive the POST-request.

Our solution is written in .NET and the API-methods look like this:
![image](https://user-images.githubusercontent.com/40911910/212467499-c4d35579-6966-48d8-96ae-3953f11dfe4a.png)

As you can see, i would immediatly log the information when the POST-method gets called. (I do the same thing in the GET-request for URL-validation, there it works)

When i copy the example from the documentation (https://developer.vivawallet.com/webhooks-for-payments/account-transaction-created/#webhook-body) into Postman and try the call local everything works just fine.

So my thoughts are, that for some reason the webhook just isn't triggered by me performing a SmartCheckout using my demo-account.

After checking out i receive an email that i successfully received a payment. 

Am i doing something wrong?

Kind regards,
Tobias

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Kruki,

Thank you very much for contacting us. Can you please provide your webhook URL and the Merchant ID of your demo account? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Kruki** [comment]
Hi,
my demo Merchant ID is: 650c5a0f-725e-4889-a2ab-aeaee72c87aa
The webhook-URL is: https://amused-api.azurewebsites.net/api/order/validatePayment

**Comment by VivaWalletCustomerSupport** [comment]
Hello, @Kruki 

We made GET-request with your URL as an endpoint and got as response the verification key.
Everything appears to be correct from our side. I would suggest checking your implementation for errors on why you don't get the correct response.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Kruki,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Kruki** [comment]
Hi,
i read the response and i am currently trying to figure out the issue!

It seems that out API receives a POST-request but returns 400 instantly. It seems like it is not able to parse the body for some reason.

I think i can safely say, this issue is closable and the error is on our side. 

Thanks for the fast and kind response!

Kind Regards,
Tobias
