### ISSUE TITLE
reference number to the payment link

### ISSUE THREAD

**Issue by Emytica** [VivaPayments/API#2308]
Hi support,
we need our reference number in response to payment, to be able to receive at the end of payment both in case of success or failure how can you do it?
Example: at this link you can enter our reference number, https:///demo.vivapayments.com/web/checkout?ref=5546545399006092 so you can read it back in response?

Regards,
Emilia

Italiano:
Buongiorno,
a noi serve in risposta al pagamento un nostro numero di riferimento, per poterlo ricevere a fine pagamento sia in caso di success o failure come è possibile farlo?
Esempio: a questo link è possibile inserire un nostro numero di riferimento, https://demo.vivapayments.com/web/checkout?ref=5546545399006092 cosi da poi poterlo rileggerlo in risposta?
saluti,
Emilia

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Emytica,

Thank you very much for contacting us. Kindly note that you can use [webhooks](https://developer.vivawallet.com/webhooks-for-payments/) to receive all the information about your transactions.[ Transaction payment created webhook](https://developer.vivawallet.com/webhooks-for-payments/transaction-payment-created/) will notify you about your successful transactions. In the other hand, [transaction failed webhook](https://developer.vivawallet.com/webhooks-for-payments/transaction-failed/) will notify you about all the failed transactions.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Emytica** [comment]
Hi support,
In addition to directing the page, we also need to have an identification number in response.
So is it possible to enter our transaction request and then receive it in response?
Example:  https://demo.vivapayments.com/web/checkout?ref=5546545399006092&transaction="123456"
For example in your answer we find t, s with your references. We would like to have another tag with reference to our transaction that we inform you in request.

Regards,
Emilia


Buonasera,
a noi oltre il direzionamento della pagina serve avere in risposta anche un nostro numero identificativo. 
Quindi è possibile inserire in richiesta un nostro transaction per poi riceverlo in risposta?
Esempio richiesta:  https://demo.vivapayments.com/web/checkout?ref=5546545399006092&transaction="123456"
Ad esempio nella vostra risposta troviamo t, s con i vostri rifermenti. Noi vorremmo avere un'altro tag con il riferimento al nostro transaction che vi comunichiamo in richiesta.
Saluti,
Emilia

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Emytica,

Thank you for the prompt response. We would like to inform you that we cannot add custom parameters in the URL of the order code. We would like to suggest you to use in your order code request the parameter "merchantTrns". 

This can be either an ID or a short description that helps you uniquely identify the transaction in the Viva Wallet banking app. For example, this can be the customer order reference number. After logging in, go to Sales > Sales Transactions and find the transaction. Click on the Info button against the item to display the Transaction Details dialog box. The contents of the merchantTrns field will be displayed on the line below the timestamp information.

This parameter will be visible on the responses of your webhooks as well.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Emytica,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Emytica,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by devMacroweb** [comment]
after payment success it is not navigating into our website. While creating order code which parameters need to send for call back url

**Comment by VivaWalletCustomerSupport** [comment]
Hello @devMacroweb 

Thank you for your message.

To assist you better, please reach out to us via email at [support@viva.com](mailto:support@viva.com) or via the Live Chat option (which can be found at the bottom-right of the main Viva.com site, or in your Production Viva.com self-care account)

Kind regards,
Viva E-commerce Support Team
