### ISSUE TITLE
web service is not reachable

### ISSUE THREAD

**Issue by Emytica** [VivaPayments/API#2309]
Hi support,
we are running tests but your demo portal is not reachable.
https://i.imgur.com/qR3ZcGt.png 

Also your webservice is not responding to calls: "https://demo-api.vivapayments.com/checkout/v2/orders"
Regards,

Emilia

**Comment by Emytica** [comment]
Hi Support,

We’re still not getting an answer this morning.
We have in response to "https///demo-api.vivapayments.com/checkout/v2/orders" an unauthorized 401.
Until yesterday morning everything was working properly.
We generate the token from: https://demo-accounts.vivapayments.com/connect/token 
response received: 
{"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjBEOEZCOEQ2RURFQ0Y1Qzk3RUY1MjdDMDYxNkJCMjMzM0FCNjVGOUZSUzI1NiIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJodHRwczovL2RlbW8tYWNjb3VudHMudml2YXBheW1lbnRzLmNvbSIsIm5iZiI6MTY3Mzk0OTAwNiwiaWF0IjoxNjczOTQ5MDA2LCJleHAiOjE2NzM5NTI2MDYsImF1ZCI6WyJjb3JlX2FwaSIsImh0dHBzOi8vZGVtby1hY2NvdW50cy52aXZhcGF5bWVudHMuY29tL3Jlc291cmNlcyJdLCJzY29wZSI6WyJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmciLCJ1cm46dml2YTpwYXltZW50czpjb3JlOmFwaTphY3F1aXJpbmc6Y2FyZHRva2VuaXphdGlvbiIsInVybjp2aXZhOnBheW1lbnRzOmNvcmU6YXBpOnJlZGlyZWN0Y2hlY2tvdXQiXSwiY2xpZW50X2lkIjoiZXN6eGl6NThxaGhxeHluaDB0cXF3anZrcnE5NXU4bW0xMm1kN241OWM4ajg2LmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiI0QzRERUE3QS02NTcwLTRGOTktOTY4Mi1EQzlENEY2NTI2MkQifQ.ae4K1-fhduakTFP3ip9g0SZaHckyYk4YlD_gWMZ5O8cxH-zuwqjmFbSdQG6dYjfHQJcK7Z4OfzvFLqSmnkjpvo1aAnQlsU6IoAHLWB7RBtGyRuRB4SyIurmMfbKIsM8dq7hukusChzzLriOgiNM3MhhI5utbmwyHG7b2h0krspoa7P5aXiIWRAidHyhvtUUvn1HDdWaAJQ4E3Pc5vICWek-cr32GzVs75sB4HD2GIQnvVEvKlc_opPZclnNAA-bOWOLsFcDsbBW9Q50IIPsHTPu0CKydaqHuY_ugrFYJCB09v1jLhgXbnDop5SDusirB_44bg0hZ23xQk8iAuCMJ5g","expires_in":3600,"token_type":"Bearer","scope":"urn:viva:payments:core:api:acquiring urn:viva:payments:core:api:acquiring:cardtokenization urn:viva:payments:core:api:redirectcheckout"}

Then we send a request  "https://demo-api.vivapayments.com/checkout/v2/orders" {"sourceCode":"6416","amount":1000,"preauth":false,"paymentNotification":false,"customerTrns":"testPagament"}

but since yesterday we are receiving 401 Unauthorized.

Regards,
Emilia

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Emytica,

Thank you very much for contacting us. We encountered a technical issue which affected the operation of the demo environment. We would like to inform you that this issue has been resolved.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Emytica,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply back here and I'd be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Emytica,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
