### ISSUE TITLE
Δοσεις σε opencart

### ISSUE THREAD

**Issue by stefloukis** [VivaPayments/API#231]
Καλησπέρα,
Εχει εγκατασταθει plugin  με δυνατοτητα δοσεων οι πληρωμες γινονται κανοικα  αλλα οταν ο πελατης παει στη σελιδα πληρωμης δεν εμφανιζει δυνατοτητα  δόσεων. 
το website ειναι το apokriatika.com.gr

**Comment by dmihos** [comment]
Καλησπέρα σας
Η επιλογή δόσεων γίνεται εφόσον ο πελάτης εισάγει την κάρτα του, οπότε και εμφανίζεται σχετικό dropdown.
