### ISSUE TITLE
Demo Account - 401 Unauthorized

### ISSUE THREAD

**Issue by galyfantis** [VivaPayments/API#2311]
We have suddently started receiving a `401 Unauthorized` response when trying to create an order using our demo account. 

**Note**: we have changed nothing since yesterday pertaining to our integration with viva, and everything worked just fine.

We can reproduce the issue as follows:
1) We request an oAuth token:
```
curl --location --request POST 'https://demo-accounts.vivapayments.com/connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \
--data-urlencode 'grant_type=client_credentials'
```
2) we receive the access token as a response
3) We invoke the endpoint to create a new order
```
curl --location --request POST 'https://demo-api.vivapayments.com/checkout/v2/orders' \
--header 'Authorization: Bearer XXXX_ACCESS_TOKEN_XXXX' \
--header 'Content-Type: application/json' \
--data-raw '{
    "amount": 1000,
    "customerTrns": "Short description of purchased items/services to display to your customer",
    "customer":
    {
        "email": "johdoe@vivawallet.com",
        "fullName": "John Doe",
        "phone": "+30999999999",
        "countryCode": "GB",
        "requestLang": "en-GB"
    },
    "paymentTimeout": 300,
    "preauth": false,
    "allowRecurring": false,
    "maxInstallments": 12,
    "paymentNotification": true,
    "tipAmount": 100,
    "disableExactAmount": false,
    "disableCash": true,
    "disableWallet": true,
    "sourceCode": "6254",
    "merchantTrns": "Short description of items/services purchased by customer",
    "tags":
    [
        "tags for grouping and filtering the transactions",
        "this tag can be searched on VivaWallet sales dashboard",
        "Sample tag 1",
        "Sample tag 2",
        "Anoteher string"
    ]
}'
```
4) We receive 401 Unauthorized as a response

Our demo merchant id is **7cd48fd4-a59c-4101-a6cc-fb93788ae880**

Can you please have a look and give us an indication when this will be fixed?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @galyfantis,

Thank you very much for contacting us. We encountered a technical issue which affected the operation of the demo environment. We would like to inform you that this issue has been resolved.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by galyfantis** [comment]
Thanks for the prompt reply. Works as expected again.
