### ISSUE TITLE
Unable to register Demo app

### ISSUE THREAD

**Issue by BodulKrk** [VivaPayments/API#2312]
Hi. Since this morning, I have been unable to pair the demo app with the demo account. The code is recognized on the demo.vivapayments.com, VW POS DEMO app starts loading, and just stys there with animated logo W logo and Loading.

Edit: after 10 minutes or so it will display Network Error.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BodulKr,

Thank you very much for contacting us. We encountered a technical issue which affected the operation of the demo environment. We would like to inform you that this issue has been resolved.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by BodulKrk** [comment]
Working like a charm! Thank you!
