### ISSUE TITLE
Every Transaction Failed

### ISSUE THREAD

**Issue by BodulKrk** [VivaPayments/API#2313]
Since this morning, every transaction in the Demo environment has failed.
I am getting this in the callback response.
TRANSACTION_DECLINED_BY_SERVER&orderCode=3017115116001184&shortOrderCode=3017115116&status=fail

Can you please check it? Thank you.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BodulKrk,

Thank you very much for contacting us. Can you please provide us your sale request and your demo account's Merchant ID?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by BodulKrk** [comment]
This is a complete callback response:
LNCcallbackscheme://result?accountNumber=478*********7417&action=sale&amount=50&cardType=Visa Credit&clientTransactionId=3F9D3A44-552E-4CC7-90BF-A1573D9D8BD7&message=(-12) TRANSACTION_DECLINED_BY_SERVER&orderCode=3017115116001184&shortOrderCode=3017115116&status=fail&tid=16001184&transactionDate=2023-01-17T12:46:19.0640821+02:00&verificationMethod=CONTACTLESS - NO CVM"

Merchant ID:c0fcdf56-c606-41c8-aa02-287dcf23c59b

My country entered the eurozone on first of January this year, and I noticed that VW POS DEMO app updated currency this morning so maybe the issue lies there? There is still the old currency listed on demo.vivapayments portal.

**Comment by BodulKrk** [comment]
This is URI that worked untill this morning.

{vivapayclient://pay/v1?appId=com.example.myapp&action=sale&clientTransactionId=C0A17121-F95C-4A36-B75B-3339BCBAD06A&amount=50&show_receipt=true&show_rating=false&show_transaction_result=true&callback=LNCcallbackscheme://result}

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BodulKrk,

Thank you for the additional information. We are currently investigating your issue and trying to reproduce it. We will inform you as soon as we have any update.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by BodulKrk** [comment]
Hello. I just wanted to let you know that everything works now. Thank you!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BodulKrk,

Thank you for the feedback. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
