### ISSUE TITLE
What is "access token"

### ISSUE THREAD

**Issue by seymourog** [VivaPayments/API#2315]
Say, I'm writing a cURL request and the documentation says to specify the access token
Tell me where to get it?
If from my personal account, how do I find it?
Unfortunately, I do not have access to the private office viva walet, as it is at the customer and the customer does not want to give access(

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seymourog,

Thank you very much for contacting us. OAuth 2.0 (IdentityServer) is the updated authentication method used for many of Viva Wallet's APIs. More information about OAuth 2.0 authentication can be found [here](https://developer.vivawallet.com/integration-reference/oauth2-authentication/). 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by seymourog** [comment]
> Hello @seymourog,
> 
> Thank you very much for contacting us. OAuth 2.0 (IdentityServer) is the updated authentication method used for many of Viva Wallet's APIs. More information about OAuth 2.0 authentication can be found [here](https://developer.vivawallet.com/integration-reference/oauth2-authentication/).
> 
> Kind regards, Viva Wallet E-commerce Support Team

I'm trying to send a request via cURL 
And I get an error 

<HTML><HEAD>
<TITLE>Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
Reference&#32;&#35;7&#46;89477b5c&#46;1674211865&#46;ebd1544
</BODY>
</HTML>

Code in php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://accounts.vivapayments.com/connect/token');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
$headers[] = 'Authorization: Basic NHN0ZHZ3djMzejhyMDJhNmpjdjFobndnZzBrYzJ3dXhybjJvYTA2b3g2Zms4LmFwcHMudml2YXBheW1lbnRzLmNvbTo0M3cyZVg3d1puaVBjM2NSUmU4VTQwYThOY2k1ZUg=';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
	echo($result);

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seymourog,

Thank you for the prompt response. Kindly note that in the body section of your request the parameter 'grant_type=client_credentials' should be used. More information can be found [here](https://developer.vivawallet.com/integration-reference/oauth2-authentication/#in-base64-encoded-format).

Kind regards,
Viva Wallet E-commerce Support Team
