### ISSUE TITLE
WooCommerce redirect 404 error after payment

### ISSUE THREAD

**Issue by Artnan7** [VivaPayments/API#2318]
Hello,

I've got an issue with the Viva Wallet plugin, after successful payment it redirects me to a 404 link which looks like this:

https://www.leador.gr/-/order-received/10889/?key=wc_order_duOtoyl3ILNX2

I read some other topics, tried to switch from Standard (wc-api/wc_vivawallet_native_success) to Smart permalinks (index.php?wc-api=wc_vivawallet&vivawallet=successs), but didn't fix anything.

![ss1](https://user-images.githubusercontent.com/55397344/215070691-9a65b5c4-9e5b-45e9-b63b-374419767d3d.png)
![ss2](https://user-images.githubusercontent.com/55397344/215070697-54749ce2-5ea2-477e-b5e9-bfe7a3ff5f00.png)
![ss3](https://user-images.githubusercontent.com/55397344/215070700-89e3e7ad-eedf-4d03-b7ec-2d4958f820f4.png)
.

Thank you!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Artnan7,

Thank you very much for contacting us. Kindly note that permalink on your website's checkout page should not contain greek or special characters.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Artnan7** [comment]
Google Translate was actually translating all words including the link when I checked it, lol. Now I rechecked directly in Greek language and the URL of Checkout Page was actually written by Greek chars. Now it works perfectly.

Thank you very much!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Artnan7,

Thank you for your prompt response. This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
