### ISSUE TITLE
Related transaction information by API

### ISSUE THREAD

**Issue by Pay4it-DK** [VivaPayments/API#2319]
Lets say i create a transaction on 50 DKK and later i partial refund 10 DKK, means the original transaction now only have 40 DKK available to be refunded.

How do i retrieve this information with the API?

When im using your webpage and search the transaction and press the INFO button i get a tab called "Related", which shows me the refunded transactions made. - I want to be able to retrieve the same information using the API, how can i do this?

In the UI it is this i'm referring to (DEMO Site)
![image](https://user-images.githubusercontent.com/123942379/215447033-bfbab0e9-b21f-402e-bbf4-4b6f0f084d00.png)

The transaction ID is ac132ff5-fa41-400d-9882-d6e23755468b (DEMO Site)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @JT-Pay4it,

Thank you very much for contacting us. Kindly note that you can use our [Retrieve transaction API request](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions/paths/~1checkout~1v2~1transactions~1{transactionId}/get) to obtain the details of a transaction. If you use the transaction ID of the payment, the information that you will receive it will correspond to the payment transaction.

When you refund or partially refund a transaction, a new entry is created with different transaction ID. If you use the new transaction ID on the API request, you will receive the information that corresponds to the refunded transaction.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Pay4it-DK** [comment]
Hi,

Yes i do know that a new transaction are created when i do a refund, but here i want to be able to use the old transaction, as shown above on your interface, here its possible to use the old transaction id and retrieve the information that there are some related transactions to it (The refunds)

So how can you do this in the interface? as shown in the picture.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @JT-Pay4it,

Thank you for the feedback. We would like to inform you that it is not possible to obtain the information from the initial payment and the refund with a single API request. Two different requests should be made.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Pay4it-DK** [comment]
Hi again,

How can i then obtain this information when i dont have the refund transaction ID ? - As its possible to refund through the webinterface ?

**Comment by Pay4it-DK** [comment]
If this is not something you have, i kindly suggest that you would look into adding this feature, and expand the functions of the transaction API so more functions are available, so its possible to obtain same information as the userinterface.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @JT-Pay4it,

Thank you for the prompt response. A transaction can be refunded from the Viva Wallet account or via API. More information about how to issue a refund can be found [here](https://developer.vivawallet.com/tutorials/payments/issue-a-refund/). If you refund a transaction via API, in the response of the request you will obtain the transaction ID of the refund. Then you can use the transaction ID of the refund to our Retrieve transaction API request.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Pay4it-DK** [comment]
The problem is, the transaction have been refounded by the UserInterface, so our system do not have the refund transaction ID.
And there for we are not able optain the correct amount that have been refunded on a transaction.

So all the transactions made from the userinterface are "hidden" from your API.

Transaction ID: ac132ff5-fa41-400d-9882-d6e23755468b
Is a transaction on 55 DKK

I have partial refunded the transaction through the API which gave me back a transaction ID: 125638da-380c-44b5-9115-f64f9738c02f which amount is 5.5 DKK

I also refunded the transaction using the Web Interface, which now means in total that transaction have a refund on 11 DKK
But I cant not obtain that information using the API, because our system do not know the transaction ID of the refunded transaction made by the web interface.



So im asking that you can extend the API with this functionality in the future, or at least will consider it.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @JT-Pay4it,

Thank you for your answer. We always consider our customers' feedback for future improvements. Our developers will review your request. If you have more questions, please don't hesitate to reply back here and we would be happy to help out!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @JT-Pay4it,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Pay4it-DK** [comment]
Hi again,

Sorry i forgot to answer last message, i read it, and hope that your developers will rewiew it with positive eyes :)

Thank you for fast response. wish you a great day ahead.

Best regards
Jesper Tarp

**Comment by VivaWalletCustomerSupport** [comment]
Hello @JT-Pay4it,

Thank you for your prompt response. This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
