### ISSUE TITLE
Can't assign bluetooth printer to VW POS demo

### ISSUE THREAD

**Issue by BodulKrk** [VivaPayments/API#2320]
Hi guys. I am trying to assign a Bluetooth SPRT printer to print transaction receipts from the VW POS demo app. The printer is paired with my phone, VW app is scanning for the printer but does not see it.  Is there some additional steps that I still need to include? I tried with other printer models, but with the same result. The printer works with other apps that are on that same phone.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BodulKrk,

Thank you very much for contacting us. Can you please send us the model of the printer? Kindly note that the compatible printers are the Bluetooth Star printers that support the STARPRNT protocol.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by BodulKrk** [comment]
Hello, 
Thank you for quick response. I tried with 3 different printers:

SPRT SP-T12BTDM
SPRT SP-L21BTDM
BIXOLON SPP-R200

Printers are paired with an android phone, printing normally. VW POS demo app does not see them at all, when I enable the option of receipt print it will just keep searching for the printers but not finding any.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BodulKrk,

Thank you for the additional information. If our application cannot identify the printers, your printers are not supporting the STARPRNT protocol.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by BodulKrk** [comment]
Thank you for your quick reply. I will find a model that supports STARPRNT.
Can you recommend a mobile Bluetooth printer that would be compatible?
Do you plan to support other protocols?

Thank you!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BodulKrk,

Thank you for your fast response. Kindly note that we cannot suggest a specific printer model. Nevertheless, if you search for this protocol on the internet, you can find a printer that suits your needs. About the supported protocols, we do not have a timestamp for adding new protocols, but we always consider our customers' feedback for future improvements. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @BodulKrk,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by BodulKrk** [comment]
Yes, I read and thank you for your reply. You are a great support team. Thank you!
