### ISSUE TITLE
Api Integration Questions

### ISSUE THREAD

**Issue by eagcx** [VivaPayments/API#2323]
Hi,

we trying to integrate your api for recurring payments.
1) so far i found out it's not possible to end the contract/remove the flag which allows us from gathering payments, correct?

2) i now would like to test chargebacks issued by the bank - how will they arrive at our end?
in this case, we have to notify customer to update payment or contact bank, right?
and eventually stop the membership.

3) is there a way to see if the credit card expires? in this case, the next payment eventually will not work, and best would be to ask customer to update it before?

4) the testing instance is quite slowly, sometimes it takes 30 to 60 seconds till redirect to our servers start - this will change when we move to live api?

thank you for your replies.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @eagcx,

Thank you very much for contacting us. Regarding your questions:

1.Can you please share with us more information, so we properly provide an answer?
2. Chargebacks cannot be tested. In case you receive a chargeback, you will get notified by e-mail.
3. The expiration date cannot be provided for security reasons. If a card expires, the transaction will fail. The customer should make an initial payment from the beginning with his new card.
4. We have not identified any issue with our servers. We kindly suggest checking your server for the delays.


Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @eagcx,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by eagcx** [comment]
@VivaWalletCustomerSupport 
thanks a lot for the answers! I have gone through our integration so far, took some time to process.

regarding your answers:
1) when we don't have any more contract with the customer, we should not be able anymore to chage money from them. but api does not allow to rewoke this access by ourselfs.

2) ok - chargeback is not testable. For automation, we will have to parse emails? no api available.

3) ok. yes, i can understand - even it would be a nice feature so remind them to renew, before card expires. :)
Do get customers a notification/email from you when their payment fails?


thank you @eagcx

**Comment by VivaWalletCustomerSupport** [comment]
Hello @eagcx,

Thank you for the prompt response. Regarding your enquiries:

1. Kindly note that you can choose when and in which customers the [recurring payments API call](https://developer.vivawallet.com/tutorials/payments/create-a-recurring-payment/#step-3-create-a-new-payment-from-the-initial-payment) will be made. This should be implemented by you in your system.
2. About chargebacks, you should check your e-mails regularly. When a chargeback is made, we will notify you by e-mail.
3. We will note your request for future improvements. The customer does not receive a notification e-mail when a transaction is not completed. If you wish to get notified about failed transactions, you can use our [Transaction failed webhook](https://developer.vivawallet.com/webhooks-for-payments/transaction-failed/).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @eagcx,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @eagcx,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
