### ISSUE TITLE
Error setting certificate verify locations

### ISSUE THREAD

**Issue by seymourog** [VivaPayments/API#2324]
Good afternoon, I have an error after the transfer of the site

I replaced Client_ID:Client_Secret data in the request to get access_token 
And replaced source_code with 4944

When I send the first request, I get a long key something like : eyJhbGciOiJSUzI1NiIsImtpZCI6IjYyODk4N0E3MDQ2QTUyQzkzMDY2NDJFMkJGQjBBNUY5OUJFQkFCkVSUzI1NisIng1dCI6IllvbUhwd1JxVXND1prTl2N0NsLVp2cnE3NCIsInR5cCI6ImF0K2p3dCJ9. eyJpc3MiOiJodHRwczovL2FjY291bnRzLnZpdmFwYXltZW50cy5jb20iLCJuYmYiOjE2NzU5MzI4ODQsImlhdCI6MTY3NTkzMjg4NCwiZXhwIjoxNjc1OTM2NDg0LCJhdWQiOlsiY29yZV9hcGkiLCJodHRwczovL2FjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIl0sInNjb3BlIjpbInVybjp2aXZhOnBheW1lbnRzOmNvcmU6YXBpOmFjcXVpcmluZyIsInVybjp2aXZhOnBheW1lbnRzOmNvcmU6YXBpOmFjcXVpcmluZzpjYXJkdG9rZW5pemF0aW9uIiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6cmVkaXJlY3RjaGVja291dCJdLCJjbGllbnRfaWQiOiI0c3Rkdnd2MzN6OHIwMmE2amN2MWhud2dnMGtjMnd1eHJuMm9hMDZveDZmazguYXBwcy52aXZhcGF5bWVudHMuY29tIiwidXJuOnZpdmE6cGF5bWVudHM6Y2xpZW50X3BlcnNvbl9pZCI6IjQ4MkFFRjE0LTUyNkYtNDIxMC05NzQxLTY3OUMzREI2N0E3NyJ9. hW6iPPU4YoaVb656ay7QAfJVZUvZwyd02hrlE9i3wqhWvwwQIfLez9fcn_HQdk34_6L4TaUsltsY6Im6ImJCgyHc0QczAdY7m3oUd201rQOzEeJKMAzbVjXZBFs32m8SA6vtzC- PCeU8VpbsVjT818DwhswN8tiRnoK5ujDW2Y8fXmB9dPzqf63NQ6f0LIhet7GJC0r5Mp_AOIAvpwJwaKyhfmn_N4zWKwoegVMFwbDAn_F_TIwZlmcDnRYneXz6iqM23UJBFrvC_kjWja4__qCDhlBPXwNTXffS30JlsZHnz3S-Jlkm0- miGo8kca3DpRUgmSBWBhOX1ZI2bNFq1m0jpMi_oz5APLQD4Jf4M7Kjo1nAuVrL3fdXGPj6e_mZqR9GrUu6APyHTwdZywmRDkBVg24UAMYBQBAAwDXVbCaVFQz1KN9e-KikhGEyNJlA_nJnntkBCzm-V3Rvl4-BdD_PV2H8Iw3KJWj9dXpCVR9t11O5BLnCl- o9-QqfvXNeM7K6BPH3h6W6rotQAmWsBr_fXgNqzwrp9sX0i8_bC4lgymNDpmZ8YG2Il6atGhaxmIQoFw_Ir4KYho8zIbREbFykR-Dqp8nkos30MfeTpv_9dvtTqKyJDaJcVMcXGdSvhpDZPUtqE47suZvKmytCWdVjdNFcbsnzecNw

But when I send the second request I get an Error:error setting certificate verify locations: CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs

**Comment by seymourog** [comment]
$ch = curl_init();
	//$total_amount = str_replace(".", ",", $total_amount);
curl_setopt_array($ch, array(
  CURLOPT_URL => "https://accounts.vivapayments.com/connect/token",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_SSL_VERIFYHOST =>false,
  CURLOPT_SSL_VERIFYPEER => false,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "grant_type=client_credentials",
  CURLOPT_HTTPHEADER => array(
	"Authorization: Basic NHN0ZHZ3djMzejhyMDJhNmpjdjFobndnZzBrYzJ3dXhybjJvYTA2b3g2Zms4LmFwcHMudml2YXBheW1lbnRzLmNvbToxOWMxUWdzTFIzcmIxdXpCMFJ0S005NkJqOVo0clk=",
    "content-type: application/x-www-form-urlencoded"
  ),
));
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
$result = json_decode($result, true);
$token = $result["access_token"];
echo('Token:<br>');
print_r($token);
echo('<br><br>Order:');
$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://api.vivapayments.com/checkout/v2/orders',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
 "amount": 200,
 "customerTrns": "Payment for Services",
 "customer": {"email": "Test","fullName": "Test","phone": "89999999999","countryCode": "CY","requestLang": "en-GB"},
 "paymentTimeout": 300,
 "preauth": false,
 "allowRecurring": false,
 "maxInstallments": 12,
 "paymentNotification": true,
 "tipAmount": 1,
 "disableExactAmount": false,
 "disableCash": false,
 "disableWallet": true,
 "sourceCode": "4944",
 "merchantTrns": "",
 "tags": [],
 "cardTokens": []
}',
  CURLOPT_HTTPHEADER => array(
    'Authorization: Bearer '.$token,
    'Content-Type: application/json'
  ),
));
$response = curl_exec($curl);
if (curl_errno($curl)) {
    echo 'Error:' . curl_error($curl);
}
curl_close($curl);
print_r($response);
$response= json_decode($response, true);
$response = $response["orderCode"];
//print_r('https://www.vivapayments.com/web/checkout?ref='.$response);

**Comment by seymourog** [comment]
This is my code for the test page, where I just send two requests https://vkcyprus.com/test/

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seymourog,

Thank you for contacting us. We would like to advise you to check your implementation again. From your website we used a bearer token and successfully generated an order code with [the sample code](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/#step-1-create-the-payment-order).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by seymourog** [comment]
> Hello @seymourog,
> 
> Thank you for contacting us. We would like to advise you to check your implementation again. From your website we used a bearer token and successfully generated an order code with [the sample code](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/#step-1-create-the-payment-order).
> 
> Kind regards, Viva Wallet E-commerce Support Team

So what could be the problem if my code worked for you, but my site code does not work correctly?

I rechecked my code several times already, everything is fine, I can't understand what could be the problem

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seymourog,

Thank you for the prompt response. We did not create an order code via your code. We made an API call using your bearer token, with the sample code that we provide in our developer's portal. With this code, the order has been generated successfully. We cannot identify an issue in our end. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by seymourog** [comment]
> Hello @seymourog,
> 
> Thank you for the prompt response. We did not create an order code via your code. We made an API call using your bearer token, with the sample code that we provide in our developer's portal. With this code, the order has been generated successfully. We cannot identify an issue in our end.
> 
> Kind regards, Viva Wallet E-commerce Support Team

Okay, I get it, but help me understand what my problem is, that's why I wrote you, because I can not understand where I have a bug and I need help

You say you used your code from the documentation on the site, if you look, my cUrl request is not different from what you provide in your documentation

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seymourog,

Thank you very much for the prompt response. Can you please replace the following in your code?

CURLOPT_HTTPHEADER => array(
'Authorization: Bearer '.$token,
'Content-Type: application/json'
)

CURLOPT_HTTPHEADER => array(
"Authorization: Bearer $token",
'Content-Type: application/json'
)

If the error persists, please send us the response code of the error you are getting. Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team
