### ISSUE TITLE
The price is not transferred

### ISSUE THREAD

**Issue by seymourog** [VivaPayments/API#2326]
Good afternoon, I send a request for an orderCode using php and everything goes fine, but for some reason the price is not passed in the request, although the variable with the price is definitely not empty

Please tell me what the problem is

Here is my code:
$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://api.vivapayments.com/checkout/v2/orders',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_SSL_VERIFYHOST =>false,
  CURLOPT_SSL_VERIFYPEER => false,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
 "amount": '. $total_amount .',
 "customerTrns": "Payment for Services",
 "customer": {"email": "'.$email.'","fullName": "'.$first_name.'","phone": "'.$phone.'","countryCode": "CY","requestLang": "en-GB"},
 "paymentTimeout": 0, 
 "preauth": true,
 "allowRecurring": true,
 "maxInstallments": 0,
 "paymentNotification": true,
 "tipAmount": 1,
 "disableExactAmount": true,
 "disableCash": false,
 "disableWallet": false,
 "sourceCode": "4944",
 "merchantTrns": "",
 "tags": [],
 "cardTokens": []
}',
  CURLOPT_HTTPHEADER => array(
    "Authorization: Bearer " . $token,
    'Content-Type: application/json'
  ),
));
$response = curl_exec($curl);
curl_close($curl);
$response= json_decode($response, true);
$response = $response["orderCode"];
wp_send_json_success($response);

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seymourog,

Thank you very much for contacting us. Kindly note that if the parameter "disableExactAmount" is set to true, then any amount specified in the payment order is ignored (although still mandatory), and the customer is asked to indicate the amount they will pay. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seymourog,

We just wanted to follow up on the reply we sent on Friday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @seymourog,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
