### ISSUE TITLE
How to update an order

### ISSUE THREAD

**Issue by ipinak** [VivaPayments/API#2327]
Is there a way to update an existing order with the new API?
I see that the deprecated API supports such a feature.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ipinak,

Thank you very much for contacting us. Kindly note that you can use our [Update Order (OLD)](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments-(Deprecated)/paths/~1api~1orders~1{orderCode}/patch) API request. Our deprecated APIs are still completely functional.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by ipinak** [comment]
Thank you.
