### ISSUE TITLE
Webhook Verify sends GET request instead of POST

### ISSUE THREAD

**Issue by icr4** [VivaPayments/API#2329]
As [documentation](https://developer.vivawallet.com/webhooks-for-payments/#create-a-webhook-endpoint) states:

> You should set up an HTTP endpoint on your server and make be sure that you can accept webhook requests with a POST method.

But i'm receiving a GET request after clicking "Verify" button in Webhooks modal in my backend with empty query params.
`INFO 40.74.20.78 - - [14/Feb/2023 12:07:13] "GET /payment/vivawallet/webhook HTTP/1.0" 200 - 3 0.002 0.007`

This is Vivawallet error message during verification:

> Error! URL not verified. Please enter a valid, publicly available, URL that conforms to [these guidelines](https://developer.vivawallet.com/web-api-integration/webhooks) (Error code 502)

I'm currently on demo environment

**Comment by VivaWalletCustomerSupport** [comment]
Hello @icr4,

Thank you very much for contacting us. Can you please send us the webhook URL you are trying to verify? Also we will need the Merchant ID of your demo account. Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by icr4** [comment]
Webhook URL: https://_CENSORED_/payment/vivawallet/webhook
Demo Merchant ID: 002be56c-08a1-4508-b811-662d67c8cc45

**Comment by VivaWalletCustomerSupport** [comment]
Hello @icr4,

Thank you for the additional information. Before receiving a webhook notification to your website, you need to create a [unique verification code](https://developer.vivawallet.com/webhooks-for-payments/#generate-a-webhook-verification-key) for Viva Wallet to identify you as a merchant. To do this, make a simple GET request to the following API endpoint with [basic authentication headers](https://developer.vivawallet.com/integration-reference/basic-auth/).

	Endpoint: https://demo.vivapayments.com/api/messages/config/token

Each time you enter a new webhook URL via the banking app, you need to verify it (by clicking on the “verify” link next to URL input textbox). This action will start the process of a simple GET http call to your URL. We send this request using TLS 1.2 so your server configuration needs to match that. Your page should print a JSON response such as the one shown below.

{
  "Key":"B3248222FDCD1885AEAFE51CCC1B5607F00903F6"
}

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by icr4** [comment]
Thank you,
i've managed to setup successfully my webhook endpoints.
Perhaps documentation is not very clear about this process?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @icr4,

Thank you for your feedback. All the necessary steps of setting up webhooks can be found [here](https://developer.vivawallet.com/webhooks-for-payments/#setting-up-webhooks). Nevertheless, we always consider our customer's reviews for future imporvements.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @icr4,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team
