### ISSUE TITLE
Native Checkout Blank Response

### ISSUE THREAD

**Issue by tenekes** [VivaPayments/API#233]
Στην υλοποίηση native checkout στο site μας στο place order step (MakePayment()>CreateOrder() > ExecuteCall() method )παίρνουμε blank response. Μπορείτε να μας πείτε για ποιο λόγο έχουμε blank response;

Merchant Id: 47ad3395-0890-4eed-8439-2f831cc77d6b

Ευχαριστώ,
Νίκος

![9c99692c63328d6eccbee382dd4df366e173c5cd195a08aaf6 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/15713434/22417920/4bd0e932-e6df-11e6-8c0a-516ab90d0e1b.png)

**Comment by tenekes** [comment]
![a767d40b24344b3dc0474d7748940ba01b5cd612891c314741 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/15713434/22377915/4afa714c-e4bc-11e6-85f7-d1251c359fad.png)

**Comment by orestis-s** [comment]
Καλησπέρα

Δοκιμάστε την απάντηση που υπάρχει στο issue #196

**Comment by tenekes** [comment]
Ευχαριστώ. Διορθώθηκε το πρόβλημα στο production με το SSL.
