### ISSUE TITLE
Place and order API issue

### ISSUE THREAD

**Issue by radosn85** [VivaPayments/API#2330]
I have created an demo account. 
I am able to make an API call to get access_token (oAuth2). 
After that, I want to make an API call "place an order" by passing access_token in Authorization header. **This API call does not work for me.**
I am using PHP examples from API documentation and response is an empty string, so no error no success message.
I tried to put only amount in a body of the request and also, I tried to put multiple parameters in body of the request, following your documentation. The response is always the same, empty string without a proper error or success message.
At the end, I tried to make a request from POSTMAN and I got same results.

I can send my code if it is needed, but it is literally PHP example from your documentation. The only two parameters I have changed and triple checked them is TOKEN I am passing in the header and demo endpoint URL.

Could you please take a look on this?

Thanks in advance

**Comment by VivaWalletCustomerSupport** [comment]
Hello @radosn85,

Thank you very much for contacting us. Can you please send us the API request and the response for the access token and the API request and response for the create payment order? (Full code). Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by chiotelis** [comment]
Same problem here, it worked yesterday? is it something about your update?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @chiotelis,

Thank you very much for contacting us. Can you please send us the API request and the response for the access token and the API request and response for the create payment order? (Full code). Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @chiotelis, @radosn85,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @chiotelis, @radosn85,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
