### ISSUE TITLE
Redirection/Native Checkout v2

### ISSUE THREAD

**Issue by IperGiove** [VivaPayments/API#2332]
Hi, 
I am trying to redirect the payment successful or failure to a custom url. I am using the demo account, but the redirect doesn't work properly, and the default redirect it is used, so https://demo.vivapayments.com/web/checkout/result?t=xxx&s=...
is the problem due to the use of the demo account?

![Screenshot from 2023-02-01 00-18-54](https://user-images.githubusercontent.com/49456524/219487332-fe9aa2b8-72f7-4753-bd76-2b653dd6b507.png)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @IperGiove,

Thank you very much for contacting us. Kindly note that in your create payment order API request, the parameter "sourceCode" should include the 4digit number of the source from which the transaction will be completed. If this parameter is not included in your request the transaction will be completed via the Default source of the account.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by IperGiove** [comment]
Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @IperGiove,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
