### ISSUE TITLE
WooCommerce Viva Wallet: Your DEMO credentials are NOT valid.

### ISSUE THREAD

**Issue by GeorgeKaragiorgos** [VivaPayments/API#2334]
Hello, I'm trying to set up payments on my WooCommerce store using the **Viva Wallet Standard Checkout** plugin.

While updating the plugin's settings to set my demo Client ID and Client Secret (which I've got from demo.vivapayments.com, settings ->API access -> WooCommerce Credentials ) I get the following error:

![image](https://user-images.githubusercontent.com/17750913/220069060-272a9660-467c-42ab-a93c-c7c49b5e9f58.png)

(Viva Wallet: Your DEMO credentials are NOT valid. Please check your credentials!)

I've checked my credentials more than 10 times and regenerated my client secret but nothing changed so I'm wondering if there's anything else I'm missing.

Here are my other plugin settings showing that payments and test mode are enabled:

![image](https://user-images.githubusercontent.com/17750913/220069467-ad130452-045a-47c9-be95-1bc6a928eaf1.png)

Here are the versions of my plugins and my MerchantID:

WooCommerce Version 7.4.0
Viva Wallet Standard Checkout Version 1.4.10
MerchantID: 3f6b4ce9-6e76-44b0-bc0a-fcc3029b6e79

My server uses HTTPs (which is a requirement of the plugin).

This is the relevant log.

> 2023-02-20T07:45:58+00:00 DEBUG 
> Viva Wallet Version: 1.4.10
> --- LOG STARTS HERE:
> API GET CREDENTIALS FAILED 
> URL: https://demo-accounts.vivapayments.com/connect/token
> Scope: BACK
> RESULT: {"headers":{"server":"AkamaiGHost","mime-version":"1.0","content-type":"text\/html","content-length":"176","expires":"Mon, 20 Feb 2023 07:45:58 GMT","date":"Mon, 20 Feb 2023 07:45:58 GMT","strict-transport-security":"max-age=31536000 ; includeSubDomains"},"body":"<HTML><HEAD><TITLE>Error<\/TITLE><\/HEAD><BODY>\nAn error occurred while processing your request.<p>\nReference #219.97361060.1676879158.c5f3f8c\n<\/BODY><\/HTML>\n","response":{"code":403,"message":"Forbidden"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
> --- LOG ENDS HERE 

Thank you in advance.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @GeorgeKaragiorgos,

Thank you for contacting us. We checked the logs you sent us, and we reject your requests for security reasons. We would like to suggest checking your website settings/plugins. Also, please ensure that in your server is not applied any restriction rule. Finally, you should check the number and the way requests are made from your website.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by GeorgeKaragiorgos** [comment]
@VivaWalletCustomerSupport Thank you for the reply.

When I first added the plugin yesterday my server was behind simple HTTP authentication and didn't use HTTPs.
I removed the authentication requirement and set up HTTPs afterwards.

Is there any chance my issue was caused because your API was failing to access my server due to the authentication requirement?

I don't have any other payment related plugins installed, is there anything else I could check?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @GeorgeKaragiorgos,

Thank you for the prompt response. It is possible that the requests are rejected due to a change in authentication or due to HTTP connection anomalies.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by GeorgeKaragiorgos** [comment]
@VivaWalletCustomerSupport Is there anything I can do to "start from scratch" other than creating a new account (which I assume requires a different phone number)? Or is there maybe a time(e.g. 24h) after my changes when things might start working?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @GeorgeKaragiorgos,

Thank you for your reply. We kindly suggest making the appropriate changes to your server and website and trying to complete the integration again 24 hours after the last attempt. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by GeorgeKaragiorgos** [comment]
@VivaWalletCustomerSupport Thank you, I will try this and get back to you in 1-2 days.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @GeorgeKaragiorgos,

Thank you. We will await your response.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by GeorgeKaragiorgos** [comment]
Hello @VivaWalletCustomerSupport 

I've tried again after waiting for 24 hours but I'm still getting the exact same behaviour. Are there any other steps I can take?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @GeorgeKaragiorgos,

Thank you for the feedback. Can you send us the logs of your last attempt? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by GeorgeKaragiorgos** [comment]
@VivaWalletCustomerSupport 

Here are the logs:

```
2023-02-22T11:57:49+00:00 DEBUG 
Viva Wallet Version: 1.4.10
--- LOG STARTS HERE:
API GET CREDENTIALS FAILED 
URL: https://demo-accounts.vivapayments.com/connect/token
Scope: BACK
RESULT: {"headers":{"server":"AkamaiGHost","mime-version":"1.0","content-type":"text\/html","content-length":"176","expires":"Wed, 22 Feb 2023 11:57:49 GMT","date":"Wed, 22 Feb 2023 11:57:49 GMT","strict-transport-security":"max-age=31536000 ; includeSubDomains"},"body":"<HTML><HEAD><TITLE>Error<\/TITLE><\/HEAD><BODY>\nAn error occurred while processing your request.<p>\nReference #219.3cbd7b5c.1677067069.7de3b93\n<\/BODY><\/HTML>\n","response":{"code":403,"message":"Forbidden"},"cookies":[],"filename":null,"http_response":{"data":null,"headers":null,"status":null}}
--- LOG ENDS HERE 
```

**Comment by VivaWalletCustomerSupport** [comment]
Hello @GeorgeKaragiorgos,

Thank you for the additional information. We would like to suggest to contact your hosting provider and ensure that in your server is not applied any restriction rule. Also, please temporarily deactivate your CDN on your website. If the error persists please temporarily deactivate all the unnecessary plugins except Woocommerce and Woocommerce Standard Checkout and try again.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by GeorgeKaragiorgos** [comment]
Hello again @VivaWalletCustomerSupport .

I've tried disabling all my plugins, and I don't any CDN.

I'm trying to check if there are any restrictions on my server but without knowing what would cause this behavior if blocked I don't know what to look for. Do your servers attempt to contact mine in some way when I set up the credentials on the plugin's settings page?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @GeorgeKaragiorgos,

Thank you for the response. We cannot identify which rule/settings on your website/server is causing the issue. When you try to integrate our plugin, you are sending an API request to our server, which is rejected for security reasons. To identify if it is caused by your server, we recommend creating a new staging clean website and try to integrate the plugin again. If the same error occurs, probably the cause is located on your server/firewall.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by GeorgeKaragiorgos** [comment]
I couldn't figure out what was causing my issue so I ended up making a new server to host my store (using the same template as the previous one so all configs are the same) and I managed to set up my demo account.

Thank you again, you can close this.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @GeorgeKaragiorgos,

Thank you for the feedback. This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
