### ISSUE TITLE
Webhooks API client id and client secret

### ISSUE THREAD

**Issue by SamuelMichelRiad** [VivaPayments/API#2336]
Hello support,

Can you please advise which client id/secret we should use to utilize the Webhooks API? The documentation does not explain this.

Thanks,
Sam

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

The webhook API uses OAuth 2.0 authentication. Additional information can be found at the link below:
https://developer.vivawallet.com/integration-reference/oauth2-authentication/

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by SamuelMichelRiad** [comment]
According to your documentation:

> Depending on your use case, different credentials may be required. You can locate these credentials as below:
> [Client (Smart Checkout) credentials]
> [Merchand ID & API Key]
> [ISV credentials]

Which pair of credentials do we use for the Webhooks API? We have already tried with Merchant ID + API key, but that resultet in "Invalid client" response.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad 

Thank you for your prompt response, please use [ Client (Smart Checkout) credentials](https://developer.vivawallet.com/getting-started/find-your-account-credentials/client-smart-checkout-credentials/).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by SamuelMichelRiad** [comment]
Hello support,

We have tried to generate a bearer token with the smart checkout credentials, however when calling the dataservices/v1/webhooks/subscriptions endpoint in the demo environment, we get 404 - Not found. Postman screenshot below. 

Please advise.

![image](https://user-images.githubusercontent.com/9570587/220432150-b2826e26-3e03-4bc9-bf4e-bde994bf736f.png)

**Comment by SamuelMichelRiad** [comment]
Also, please advise on a timeline for when event types other than SaleTransactionsFileGenerated will be supported, particularly TransactionPaymentCreated.

![image](https://user-images.githubusercontent.com/9570587/220432625-1d065b71-9f95-45c8-b0d2-ef3ed261bb24.png)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad

For Data Services API access can only be granted via Live Chat. Please connect to your viva wallet account and start a new Live Chat session to proceed.

Regarding the timeline, currently Webhook Subscription can be made for SaleTransactionsFileGenerated event only. Unfortunately we don't have an ETA for different types. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by SamuelMichelRiad** [comment]
Hi support,

We want to implement the data services API in order to facilitate **onboarding** of new customers. We are an ISV partner. It is not appropriate to ask new customers to request access to an API through a chat function. For other Viva Wallet APIs (e.g. POS API), we instruct the customer to log in to Viva Wallet, copy/paste the relevant keys into our backend.

Please update your documentation with the observations from this ticket. You may close it.

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

Thanks for the quick reply. Enabling the Data Services API requires unique credentials that can only be sent to the account owner. That's why we asked you to contact us via live chat. This information is listed on our developer portal.

![image](https://user-images.githubusercontent.com/112542999/220605287-90c6b878-8171-499a-b931-2183e24142bf.png)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

We just wanted to follow up on the reply we send yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
