### ISSUE TITLE
Invoice for placed order is not created

### ISSUE THREAD

**Issue by MartynasKasp** [VivaPayments/API#2337]
Hello,

I just started using your payment integration plugin for Magento 2 today and noticed that an invoice for an order is not created after a successful payment, so I wanted to know why. Is this intentional or you just forgot to register an invoice? Or am I missing something with my setup? While looking at the source code I can see that the plugin expects an invoice to be created (`Controller\Viva\Callback->_registerPaymentCapture() at line 237`), but it does not exist.

Currently working on Viva Payments' sandbox mode.

Thanks.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MartynasKasp,

Thank you very much for contacting us. We would like to inform you that our Magento Smart Checkout does not create an invoice automatically yet. However, you can create the invoice manually through your website's dashboard if you wish. Also, we will review your request for future improvements.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MartynasKasp,

Thank you for the feedback. We will always review our customers' comments for future improvements.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MartynasKasp,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
