### ISSUE TITLE
problem with 3D secure - demo account/card - woocommerce

### ISSUE THREAD

**Issue by easyaccess2web** [VivaPayments/API#2339]
Hello,

In Demo environnement, with woocommerce plugin vivawallet, I receive a error when I put the password in the 3D Secure process.
In production with the same installation --> it is ok.

Do you have problem with the 3D Secure in Demo environnement ?

Config :
![capture 1](https://user-images.githubusercontent.com/84955063/220718739-7ec4a34f-1fe0-404f-aa1b-a6eaae461a7a.png)
My config is 👍 
wordpress 6.1
Woocommerce 7.3
php 7.3.33
nginx

1) the plugin is well install and works : 

![screen viva wallet 2](https://user-images.githubusercontent.com/84955063/220719268-38e44f74-910e-49db-994b-3d82fb65ef5a.png)

2) I fill in the form with the data of Test Card and it connect to the 3D Secure system : 

![screen3 viva wallet](https://user-images.githubusercontent.com/84955063/220719654-cc5b82ae-f729-4ff0-be52-7426ca82205e.png)

3) I receive an error (not always 8 times of 10) : 
![screen4 viva wallet](https://user-images.githubusercontent.com/84955063/220719839-e175a53b-d24c-4347-b54d-cc0e6137b98c.png)

Is there problem for demo in the plugin woocommerce ?

Thanks a lot.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @easyaccess2web,

Thank you very much for contacting us. We are currently investigating your issue. We will let you know as soon as we have any update.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @easyaccess2web,

Sorry for the late response. Can you please try again, and inform us if the error is persisting? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @easyaccess2web,

We just wanted to follow up on the reply we sent on Friday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by easyaccess2web** [comment]
It works now. Thanks
