### ISSUE TITLE
Link Πληρωμής για viva wallet

### ISSUE THREAD

**Issue by nagiadep** [VivaPayments/API#234]
Καλησπέρα,
Θα ήθελα να μου δώσετε κάποιες διευκρινίσεις ως προς την υλοποίηση πληρωμής για έναν διαγωνισμό, δηλαδή έχουμε φτιάξει μία google form στην οποία θέλουμε οι συμμετέχοντες να καταχωρούν τα στοιχεία τους, να επιλέγουν τρόπο πληρωμής και να μπορούν να πληρώνουν μπαίνοντας στο link της viva wallet και αφότου πληρώσουν να επιστρέφουν στη φόρμα και μόνο τότε να γίνεται δεκτή η αίτηση συμμετοχής. Αυτό θα ήταν προτιμότερο αν το link έμπαινε σε ιστοσελίδα ή μέσω google form γίνεται να προσθέσουμε link πληρωμής.  Γνωρίζω ότι μπορούμε να προσθέσουμε τον κώδικα που έχει το κουμπί πληρωμής στο site που θέλουμε, αλλά από κει και πέρα χρειάζεται να κάνουμε κάτι άλλο για να λειτουργήσει αν επιλέξουμε αυτόν τον τρόπο;

**Comment by kostGX** [comment]
Closing as issue over 1 year old.
