### ISSUE TITLE
Cannot capture pre authorizations via API (setting enabled)

### ISSUE THREAD

**Issue by TsiantosD** [VivaPayments/API#2341]
I have been trying to capture pre authorizations of transactions made by smart checkout (on a demo account) but I keep getting the same error, without any comments, both on postman and my application, even after I enabled the option to accept pre authorizations via API.

![image](https://user-images.githubusercontent.com/75504452/220749327-959348f6-1a9c-4184-99c1-6c516808b730.png)
![image](https://user-images.githubusercontent.com/75504452/220749570-3c28b26e-7c79-488e-96f0-ca8315f9da18.png)

It should also be noted that the same response gets returned regardless of the state of the "Allow recurring payments and pre-auth captures via API" option.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @TsiantosD,

Thank you very much for contacting us. Can you please share a screenshot of the body section of the API request as well? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by TsiantosD** [comment]
Hello, 

Thank you for the quick response. It turns out that, after checking the body, it wasn't properly passed in both the app and postman. An error message and a more descriptive response from the API would be very helpful in this case, rather than a generic errorCode 400.

Thank you for your time.
