### ISSUE TITLE
paymentTimeOut or paymentTimeout

### ISSUE THREAD

**Issue by jpincas** [VivaPayments/API#2343]
From your docs:

![Screenshot 2023-02-23 at 12 30 51](https://user-images.githubusercontent.com/17711012/220921596-01c8aa1e-313c-435d-91d8-c85a61a45941.png)

Could you clarify which is correct?

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jpincas, 

Thank you very much for contacting us. Kindly note the Default value is 1800. By using "0" the default value will be used instead.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by cforrestvivawallet** [comment]
Hi @jpincas, I can confirm that both paymentTime**O**ut and paymentTime**o**ut will work successfully.

However, for consistency I have updated our documentation to show only paymentTime**o**ut. Apologies for any confusion.

Kind regards,
Viva Wallet Development Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jpincas,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
