### ISSUE TITLE
Smart Checkout - many orders stay as 'pending payment' in WC

### ISSUE THREAD

**Issue by slam-d** [VivaPayments/API#2344]
Since switching from the viva standard checkout to the viva smart checkout, many orders stay as pending payment if the order is abandoned and they are not automatically cancelling themselves if abandoned.

How do I resolve this?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @slam-d,

Thank you very much for contacting us. 
Smart checkout requires a [new source](https://developer.vivawallet.com/getting-started/create-a-payment-source/payment-source-for-online-payments/) to be created and linked to your account.

Afterwards, please navigate to your Viva Wallet account under "Sales-> Online Payments -> Websites/Apps" locate the source you have previously generated with the four-digit source code and add the following successful and failed transaction URLs.

Successful Transaction URL: index.php?wc-api=wc_vivawallet&vivawallet=success
Failed Transaction URL: index.php?wc-api=wc_vivawallet&vivawallet=fail

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by slam-d** [comment]
Hi @VivaWalletCustomerSupport 

I have spoken to your support a lot on this and they keep suggesting the same thing.

I have tried setting up a new source. 

The previously used Viva Wallet Standard Checkout never had this same issue when talking to the WooCommerce order ledger.

Are there any other suggestions you can come up with?

Resolving this is taking so long I will most likely look to escalate the issue further

**Comment by VivaWalletCustomerSupport** [comment]
Hello @slam-d,

Thank you for the prompt response. You can achieve this by going to WordPress Dashboard > WooCommerce > Settings > Products > Inventory > Hold Stock and modify the time (minutes) there so that when that time limit is reached, the pending order will be cancelled. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by slam-d** [comment]
Hi @VivaWalletCustomerSupport @VivaWalletSupport 

Thank you for mentioning this. So why have orders not automatically cancelled now that they are over this timeframe already?

They still show up as pending payment and have exceeded the time in minutes for which the stock is held.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @slam-d,

Thank you for the swift response. Was this option enabled or did you enable it today? Kindly note that this option will affect the orders that are created after the activation.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by slam-d** [comment]
@VivaWalletCustomerSupport 

This was already enabled before this conversation

**Comment by VivaWalletCustomerSupport** [comment]
Hello @slam-d,
 
This particular function is of Woocommerce and not of our plugin. For further information please consider contacting their support team.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @slam-d,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @slam-d,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
