### ISSUE TITLE
Transaction Failed webhook not received

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2345]
I configured two identical webhooks for [_Transaction Payment Created_](https://developer.vivawallet.com/webhooks-for-payments/transaction-payment-created/) and [_Transaction Failed_](https://developer.vivawallet.com/webhooks-for-payments/transaction-failed/).

![image](https://user-images.githubusercontent.com/30406081/221118535-3ce9efbc-8d71-49c8-8ed9-f44dd681d913.png)

The _Transaction Payment Created_ webhook is received just fine by my server.

The _Transaction Failed_ seems to be lost. It never reaches my server. I tried both with a demo account and a pro account.

The failed payment was triggered by paying with the [Visa test card 4147 4630 1111 0141](https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#test-cards) during a smart checkout. The smart checkout completes and the customer is redirected to the failed transaction url.

So, I believe I have ruled out an issue with my server as the _Transaction Payment Created_ webhook is received and processed while _Transaction Failed_ doesn't even show up in the http server log.

As the customer is redirected to the failed url of the webshop, I believe the Visa test card is accepted by both the demo and pro accounts.

Do you confirm a _Transaction Failed_ webhook should be sent in that case?

Is there any difference between the two webhooks that might explain why one is emitted but not the other?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you very much for contacting us. Can you send us the URL of your Transaction failed Webhook? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Thanks for your response.

The webhook url is https://frontoffice.byemisys.com/vivawallet/webhook

Please note the url ignores any ip address not listed in [Whitelist the Viva Wallet addresses](https://developer.vivawallet.com/webhooks-for-payments/#whitelist-the-viva-wallet-addresses).

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for the additional information. Can you please share with us the eventid of the failed transaction? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
The event ID is 2062.

Here is the full query from the failed url: `?eventId=2062&lang=fr-FR&s=3085681878701410 `.

Please note the above test was performed from a development environment. It did not use the above mentioned webhook url.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for the information. Kindly note that we are not sending notifications in the webhook endpoints for transactions that are failing to pass the 3ds authentication (2061,2062). Those transactions don't have transaction ids because they never reach our systems as an attempt. The issuing banks are rejecting these transactions. We kindly suggest trying to issue a decline according to the following instructions:

https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#an-issuer-decline-without-decline-recovery

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Yes! Webhook is received with those simulated errors. Thank you!

It's good to know when payments failed to pass 3DS though. It makes things easier to explain to the customer :slightly_smiling_face:
