### ISSUE TITLE
Customer name not sanitized in payment confirm email

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2346]
I paid an order with the name `Fr<h1>édéric</h1> Marchal`. That name is intended to catch unescaped text on our server. If the user's name is properly escaped, html entities should be displayed as above instead of being interpreted as html.

After a smart checkout payment, Viva Wallet send an email to confirm the payment.

The received email didn't sanitize nor escape my name:
![image](https://user-images.githubusercontent.com/30406081/221122613-5c8b2274-2d23-4a51-a8d5-ed0a8020c856.png)

I don't anticipate any serious issue as most modern mail clients should sanitize the received html.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for your comments. We are investigating the information you sent us. We always take our customers' feedback into consideration for future improvements.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
