### ISSUE TITLE
Issue with the "place an order" endpoint

### ISSUE THREAD

**Issue by jiggsaw85** [VivaPayments/API#2348]
I am using demo account and code example from your documentation (for PHP). When I execute code to get an access token, it works perfect and I got the token. 
Next endpoint, when I want to place and order by passing this token in request header, does not work. The response is nothing (empty string), also, without any error message. I tried from PHP and I also tried to make a request from POSTMAN, the result is always the same.

**This is my code to get an access token:**

`$encodedCredentials = base64_encode("$clientId:$secret");
        $payload = [
            'grant_type' => 'client_credentials'
        ];

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://demo-accounts.vivapayments.com/connect/token');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($payload));

        $headers = array();
        $headers[] = 'Content-Type: application/x-www-form-urlencoded';
        $headers[] = "Authorization: Basic $encodedCredentials";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        $data = json_decode($result);

        return $data->access_token;`

Response from the code above looks like this:
`  +"access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjBEOEZCOEQ2RURFQ0Y1Qzk3RUY1MjdDMDYxNkJCMjMzM0FCNjVGOUZSUzI1NiIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6ImF0K2p3dCJ9 ▶"
  +"expires_in": 3600
  +"token_type": "Bearer"
  +"scope": "urn:viva:payments:core:api:posmanagement urn:viva:payments:core:api:posmanagement:usercodes:verify urn:viva:payments:ecr:api"`
  
  From there, I am taking access_token and passing it to the next function.

**This is my code to place an order by passing previously got token:**

`$postFields  = [
            'amount'              => 100,
            'customerTrns'        => 'This is a description displayed to the customer',
            'customer'            => [
                'email'       => 'someone@vivawallet.com',
                'fullName'    => 'George Seferis',
                'phone'       => '69xxxxxxxxx',
                'countryCode' => 'GR',
                'requestLang' => 'el-GR'
            ],
            'paymentTimeout'      => 1800,
            'preauth'             => true,
            'allowRecurring'      => true,
            'maxInstallments'     => 0,
            'paymentNotification' => true,
            'tipAmount'           => 1,
            'disableExactAmount'  => true,
            'disableCash'         => false,
            'disableWallet'       => false,
            'sourceCode'          => 'Default',
            'merchantTrns'        => 'This is a short description that helps you uniquely identify the transaction',
            'tags'                => ['tag1', 'tag2']
        ];

        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_URL            => 'https://demo-api.vivapayments.com/checkout/v2/orders',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING       => '',
            CURLOPT_MAXREDIRS      => 10,
            CURLOPT_TIMEOUT        => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST  => 'POST',
            CURLOPT_POSTFIELDS     => json_encode($postFields),
            CURLOPT_HTTPHEADER     => array(
                "Authorization: Bearer $token",
                'Content-Type: application/json'
            ),
        ));

        $response = curl_exec($curl);

        curl_close($curl);
        return $response;`

Here, response is always empty string.

Could you please take a look on this?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85,

Thank you very much for contacting us. Create payment order API request requires an access token with [Smart Checkout credentials ](https://developer.vivawallet.com/integration-reference/oauth2-authentication/#in-base64-encoded-format)encoded in base 64 format. As we can observe in your request the scope you are getting "urn:viva:payments:core:api:posmanagement urn:viva:payments:core:api:posmanagement:usercodes:verify urn:viva:payments:ecr:api" indicates that the POS credentials have been used.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by jiggsaw85** [comment]
Hi,

Got it. Thanks for your support, you can close the ticket.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
