### ISSUE TITLE
ISV global webhooks

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2349]
Hi,

Webhooks are an essential part of payment processing to ensure no payment nor payment failure are lost.

Is it possible to define webhooks at the ISV level? I mean webhooks that are called irrespective of the merchant performing the payment and that the merchant can't remove.

My purpose is to be informed of every transaction made by any or our merchant without the need to configure the same webhooks over and over on every merchant's account and then hoping a clueless merchant doesn't remove or alter the webhooks we set up.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you very much for contacting us. Kindly note that our webhooks should be created on each account separately. However, we will review your request for future improvements. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Thanks @VivaWalletCustomerSupport . I'll wait for the improvement to become available.

A merchant has to disable both the webhooks and the return url to render the payment system ineffective. So, we should be safe for the time being.
