### ISSUE TITLE
no redirect from vivapayment

### ISSUE THREAD

**Issue by vasilioualex** [VivaPayments/API#235]
καλησπέρα , αντιμετωπίζω το εξης πρόβλημα. ολοκληρώνω την αγορά γίνεται redirect στην σελίδα της viva με το σωστο ποσο και id πληρώνεις κανονικα με καρτα  και μετα  δεν επιστρέφει καθόλου στην σελίδα στα url που δηλωσα σαν succeed or fail  με αποτέλεσμα να μην καταχωρείται η παραγγελία. μενει δλδ στην σελιδα της viva... 
εχετε διεα τι μπορει αν συμβαίνει?

**Comment by dmihos** [comment]
Καλησπέρα σας
Θα πρέπει να ελέγξετε ότι κατά το CreateOrder περνάτε το SourceCode της πηγής στην οποία έχετε βάλει τα urls σας.
https://github.com/VivaPayments/API/wiki/Optional-Parameters

**Comment by gtsoukasgr** [comment]
Τον κωδικό θέλει ή την ονομασία ?.

**Comment by dmihos** [comment]
Τον κωδικό
