### ISSUE TITLE
Can not access demo API settings page

### ISSUE THREAD

**Issue by vaskou** [VivaPayments/API#2350]
Hello,

I have a demo account for Viva Wallet and I am having a problem accessing the settings page for the API keys.
When I try to access it, I get redirected to an error 500 page.

![screenshot-1](https://user-images.githubusercontent.com/2781587/221807023-9721a42e-dc03-41c4-84d9-7ef1428d7175.jpg)
![screenshot-2](https://user-images.githubusercontent.com/2781587/221807024-7f722f27-1747-4cb5-93de-de66b3e5e742.jpg)

Can you please fix this because I need to have access to the API keys.

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vaskou,

Thank you very much for contacting us. Can you please send us the Merchant ID of your demo account and the correlation ID of the error? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by vaskou** [comment]
I would love to send you my Merchant ID but as I said the "API ACCESS" page where I can find my Merchant ID is not accessible. It shows me the "Error 500".

If there is an other way that I can find my Merchant ID please tell me.

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vaskou,

Thank you for the prompt response. To find your demo account, please send us the mobile number or e-mail registered to the account. Feel free to send the information here or via e-mail to support@vivawallet.com. If you send this information via e-mail, please add in the subject of the e-mail the following:

Github ticket #2350.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vaskou,

Thank you for the additional information. We noticed that your demo account is quite old, and some features may be deprecated. We would like to advise you to create a new demo account so that you can use all the features we provide.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by vaskou** [comment]
I tried to create a new demo account but I can't because the mobile phone number is already registered to the old account and I have only one mobile phone number.

Can you delete the old account so I can create a new one with the same mobile phone number?

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vaskou,

Thank you for prompt response. Kindly note that you can use a dummy mobile phone number. Since for Demo accounts you always use the code ‘111111’ when prompted with the Two-Factor Authentication pop-up.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by vaskou** [comment]
Ok I just created an account with a dummy mobile number.

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vaskou,

Thank you very much for the feedback. If you have any question we are at your disposal.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vaskou,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
