### ISSUE TITLE
Smart checkout always redirect to failure URL

### ISSUE THREAD

**Issue by jiggsaw85** [VivaPayments/API#2351]
I am placing an order with smart checkout API. This is my code:

`
$postFields  = [
            'amount'              => 100,
            'customerTrns'        => 'Buying pLikes',
            'customer'            => [
                'email'       => 'someone@vivawallet.com',
                'fullName'    => 'George Seferis',
                'phone'       => '0605030862',
                'countryCode' => 'GR',
                'requestLang' => 'el-GR'
            ],
            'paymentTimeout'      => 1800,
            'preauth'             => true,
            'allowRecurring'      => true,
            'maxInstallments'     => 0,
            'paymentNotification' => true,
            'tipAmount'           => 1,
            'disableExactAmount'  => false,
            'disableCash'         => false,
            'disableWallet'       => true,
            'sourceCode'          => '4669',
            'merchantTrns'        => 'Buying pLikes',
            'tags'                => ['tag1', 'tag2']
        ];

        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_URL            => 'https://demo-api.vivapayments.com/checkout/v2/orders',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING       => '',
            CURLOPT_MAXREDIRS      => 10,
            CURLOPT_TIMEOUT        => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST  => 'POST',
            CURLOPT_POSTFIELDS     => json_encode($postFields),
            CURLOPT_HTTPHEADER     => array(
                "Authorization: Bearer $token",
                'Content-Type: application/json'
            ),
        ));

        $response = curl_exec($curl);
        $data = json_decode($response);

        curl_close($curl);

        return $data->orderCode;
`

The above code returns "order Code" which I am using to generate checkout URL like this:

**https://demo.vivapayments.com/web/checkout?ref={orderCode}&color=003653**

When I open this URL, I can see checkout page and everything I previously set, so all looks good. 
When I want to perform card payment, payment fails always. I am using test cards and only cards which are marked as "success":
**VISA:** 4147 4630 1111 0133
**MASTER:** 5239 2907 0000 0101

After I put the card, checkout page is loading and always redirects me to failure URL I set. The query params in URL looks like this:
?s=8452433451672608&lang=el-GR&eventId=0

I have checked eventId on your list and 0 means "undefined", which does not give me the clue on what is wrong.

Could you please take a look on this issue?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85,

Thank you very much for contacting us. Kindly note that some parameters are not available for activation in the same request. For example, if the "preauth" parameter is set to true, "allowRecurring" and "maxInstallments" cannot be enabled in the same request. Additionally, when creating a payment order for a pre-authorization (with preauth = true), tipAmount should only be set when capturing the pre-authorization, and not when creating the initial payment order.

More information about the parameters of the create payment order API request can be found [here](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post). 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
