### ISSUE TITLE
cant login to demo account caused by 2fa app requirement.

### ISSUE THREAD

**Issue by eagcx** [VivaPayments/API#2355]
hi,

we would live to develop the integration with you further,
but we cant login to the demo account anymore as another 2fa is required. (via viva wallet app)

the app only opens the normal account page 
where my phone number is bound to our normal account.

so we cant login to the demo account anymore.
this blocks our development :(

can you disable the 2fa for the demo accounts? or guide us to a solution?

**Comment by eagcx** [comment]
hi,
i was able to solve it with the normal viva wallet support.

it takes quite long, but then a button gets added saying 'skip, i'll do it later'

**Comment by VivaWalletCustomerSupport** [comment]
Hello @eagcx, 

Thank you for your message. That is correct, you have to press the skip button to procced.
This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
