### ISSUE TITLE
Unable to get transaction information after a POS session webhook confirmation

### ISSUE THREAD

**Issue by adoyen** [VivaPayments/API#2356]
Hello,

I have done a test using VW POS Demo. The test was a payment successful, as you can see here below using postman:
![image](https://user-images.githubusercontent.com/1709103/225894271-fbaab2bd-07c0-4f24-93e7-5dca6b4e2b56.png)
Created using ISV account through this URL: https://demo-api.vivapayments.com/ecr/isv/v1/transactions:sale

The transactionId is well specified in the success webhook received but I haven't any way to check this transactionId,
I tried this:
![image](https://user-images.githubusercontent.com/1709103/225894509-c50c8015-1e68-4353-b788-a8748a17ca48.png)
With MarchantId is the same as the one in the session retrieved : a580b930-5e41-421b-8914-2c9fa30eec66
It seems that my ISV account cannot access a transactionId from a session created by the same ISV.

As specified in your documentation:
![image](https://user-images.githubusercontent.com/1709103/225894971-fdb17f1d-5502-40a6-aede-189f96c9e1c8.png)
I would like to check the webhook information received using the transactionId.

Strangely, the transaction cannot be found on the ISV transactions but only on the merchant transactions (page https://demo.vivapayments.com/selfcare/fr/sales/mysales and equivalent in ISV side)

Am I doing something wrong ?

Thanks.

**Comment by adoyen** [comment]
Useful information:
MerchantId: a580b930-5e41-421b-8914-2c9fa30eec66
SessionId : SD4X52d3eYrkEGMTR-epNs8nkBASWpiYCKu
TransactionId : 63c0a7c3-db7a-43fa-8813-8a4e27762906

Complete Session message retrieved by sessionId:
```
{
    "sessionId": "SD4X52d3eYrkEGMTR-epNs8nkBASWpiYCKu",
    "terminalId": "16001754",
    "cashRegisterId": "ClubOnline",
    "amount": 200,
    "currencyCode": "978",
    "merchantReference": "SD4X52d3eYrkEGMTR",
    "customerTrns": "ClubOnline transaction Club de basket - SD4X52d3eYrkEGMTR",
    "tipAmount": 0,
    "success": true,
    "eventId": 0,
    "authorizationId": "197941",
    "transactionId": "63c0a7c3-db7a-43fa-8813-8a4e27762906",
    "transactionTypeId": 5,
    "retrievalReferenceNumber": 307515197941,
    "panEntryMode": "81",
    "applicationLabel": "VISA",
    "primaryAccountNumberMasked": "414746XXXXXX0133",
    "transactionDateTime": "2023-03-16T15:49:42.473000+00:00",
    "abortOperation": false,
    "abortAckTime": null,
    "abortSuccess": false,
    "loyaltyInfo": null,
    "verificationMethod": null,
    "tid": "16001754",
    "shortOrderCode": "2458571337",
    "installments": 0,
    "message": "Transaction successful",
    "preauth": false,
    "referenceNumber": 0,
    "orderCode": "2458571337605071",
    "isvDetails": {
        "amount": 2,
        "merchantId": null,
        "sourceCode": null,
        "merchantSourceCode": null
    }
}
```

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you very much for contacting us. Can you please retrieve a transaction that is visible on your ISV account and post the results? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by adoyen** [comment]
Hello @VivaWalletCustomerSupport ,

With TransactionId a2a05706-911f-4bfc-a792-a6ab410a2ecd,
I get the result:
```
{
    "email": "xxx",
    "amount": 10.00,
    "orderCode": 7634658829586566,
    "statusId": "F",
    "fullName": "Arnaud Doyen",
    "insDate": "2023-03-13T23:23:18.303+02:00",
    "cardNumber": "606005XXXXXX0130",
    "currencyCode": "978",
    "customerTrns": "ClubOnline transaction Club de basket",
    "merchantTrns": "MQAt2u6kqw6WWPGqH",
    "transactionTypeId": 5,
    "recurringSupport": false,
    "totalInstallments": 0,
    "cardCountryCode": null,
    "cardIssuingBank": null,
    "currentInstallment": 0,
    "cardUniqueReference": "7A796C6ADA14FB1888A4557145030D0713AF5082",
    "cardTypeId": 6,
    "digitalWalletId": null
}
```

**Comment by adoyen** [comment]
I see in my session retrieval that part at the end:
```
    "isvDetails": {
        "amount": 2,
        "merchantId": null,
        "sourceCode": null,
        "merchantSourceCode": null
    }
```

Should I specify fields merchantId and merchantSourceCode when creating the session (initiate sales request) ?
![image](https://user-images.githubusercontent.com/1709103/225943303-2236696c-1e65-4124-bcfc-5a4825d643d8.png)

I'll check while filling in those 2 fields.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for the additional information. The parameters "amount" and "terminalMerchantID" under "isvDetails" are mandatory when you are creating the initiate sales request.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by adoyen** [comment]
I tried session id Lh3MDHp3yEpPCqQjF-ZGwPmXTvwAyRAFaLy
With transactionId : 8d346ded-744a-4528-9f57-10476ee228af
But still not visible for ISV

**Comment by adoyen** [comment]
Hello @VivaWalletCustomerSupport ,

These 2 fields are well filled in :
![image](https://user-images.githubusercontent.com/1709103/225946310-9b2e80f5-1725-4f56-a789-21e4a00f8958.png)

But is there a typo in terminalMerchantId ?

It's effectively strange that this field is not in the session retrieval.
Nevertheless, I can still see the transaction in merchant site while not in ISV site.

**Comment by adoyen** [comment]
If not filled in, I receive this message (tested on postman):
![image](https://user-images.githubusercontent.com/1709103/225988269-0849c4db-5557-4d08-b5d1-d052db9b8ef1.png)

So I don't see anything missing in my initial post.
Furthermore, I think merchantId and merchantSourceCode shouldn't be filled in my case since I treat only one merchant per transaction.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for the information. Can you please send us the whole request you are making? As we noticed, the transaction with transaction ID 8d346ded-744a-4528-9f57-10476ee228af is not connected to an ISV account. That's the reason is not visible on your ISV account.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by adoyen** [comment]
Hello @VivaWalletCustomerSupport ,

Here is what I did:
Call initiate a Sales Request (using ISV token in Authorization header):
```
Call: {
  "headers": {
    "Authorization": "Bearer xxx"
  },
  "data": {
    "sessionId": "Af9gcJRMydoim5oHS-Cij4jRw3mhGyhxAGr",
    "terminalId": "16001754",
    "cashRegisterId": "ClubOnline",
    "amount": 530,
    "currencyCode": "978",
    "merchantReference": "Af9gcJRMydoim5oHS",
    "customerTrns": "ClubOnline transaction Club de basket - Af9gcJRMydoim5oHS",
    "maxInstalments": 0,
    "tipAmount": 0,
    "isvDetails": {
      "amount": 2,
      "terminalMerchantId": "a580b930-5e41-421b-8914-2c9fa30eec66"
    }
  }
}
Response: {
  statusCode: 200,
  content: '',
  headers: {
    connection: 'close',
    'content-length': '0',
    date: 'Mon, 20 Mar 2023 13:50:25 GMT',
    server: 'uvicorn',
    'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
    'x-process-time': '0.5514936447143555',
    'x-viva-correlationid': '23-079-76E0158B321C'
  },
  ok: true,
  redirected: undefined,
  data: null
}
```

Then, payment received on VW POS Demo.
I scan the QR code and got redirected to payment-demo page.
I pay with test card 4147 4630 1111 0133

Then, I receive following webhook (nothing happens on app VW POS Demo until I click "Ticket") :
```
Body received: {
  Url: 'http://xxx.be/webhook/transaction/vivawallet',
  EventData: {
    Moto: false,
    BinId: 41,
    Ucaf: 'AJkBBpBUGQAAAAISl4B5dQcEZSM=',
    Email: 'xxx@gmail.com',
    Phone: null,
    BankId: 'NET_VISA',
    Systemic: false,
    Switching: false,
    ParentId: null,
    Amount: 5.3,
    ChannelId: '2214f59a-ec1e-4c32-bdbf-90f7a85210a3',
    TerminalId: 90000000,
    MerchantId: 'a580b930-5e41-421b-8914-2c9fa30eec66',
    OrderCode: 4592423883416136,
    ProductId: null,
    StatusId: 'F',
    FullName: 'Test',
    ResellerId: null,
    DualMessage: false,
    InsDate: '2023-03-20T15:52:14.533',
    TotalFee: 0,
    CardToken: '2BFCB1FD4F000DB41CB5BA76CAFB68D76AB87752',
    CardNumber: '414746XXXXXX0133',
    TipAmount: 0,
    SourceCode: '6157',
    SourceName: 'demo',
    Latitude: null,
    Longitude: null,
    CompanyName: 'xxx',
    TransactionId: 'fff56a01-5efd-46e4-816e-fbc66908567e',
    CompanyTitle: 'xxx',
    PanEntryMode: '01',
    ReferenceNumber: 199157,
    ResponseCode: '00',
    CurrencyCode: '978',
    OrderCulture: 'fr-FR',
    MerchantTrns: 'Af9gcJRMydoim5oHS',
    CustomerTrns: 'ClubOnline transaction Club de basket - Af9gcJRMydoim5oHS',
    IsManualRefund: false,
    TargetPersonId: null,
    TargetWalletId: null,
    AcquirerApproved: false,
    LoyaltyTriggered: false,
    TransactionTypeId: 5,
    AuthorizationId: '199157',
    TotalInstallments: 0,
    CardCountryCode: 'SG',
    CardIssuingBank: 'Citibank Singapore Ltd.',
    RedeemedAmount: 0,
    ClearanceDate: null,
    CurrentInstallment: 0,
    Tags: [],
    BillId: null,
    ConnectedAccountId: null,
    ResellerSourceCode: null,
    ResellerSourceName: null,
    ResellerCompanyName: null,
    CardUniqueReference: '2BFCB1FD4F000DB41CB5BA76CAFB68D76AB87752',
    ResellerSourceAddress: null,
    CardExpirationDate: '2027-01-31T00:00:00',
    RetrievalReferenceNumber: '307913199157',
    AssignedMerchantUsers: [ '3c5dd92f-830b-4c32-8942-7c4f8b4479b1' ],
    AssignedResellerUsers: [],
    CardTypeId: 0,
    ResponseEventId: null,
    ElectronicCommerceIndicator: '5',
    OrderServiceId: 0,
    DigitalWalletId: null
  },
  Created: '2023-03-20T13:52:14.5757328Z',
  CorrelationId: '23-079-872E2BA0',
  EventTypeId: 1796,
  Delay: null,
  MessageId: 'e1163c48-8aa9-4dc0-a168-3ccd3b143ada',
  RecipientId: 'a580b930-5e41-421b-8914-2c9fa30eec66',
  MessageTypeId: 512
}
```

Then, when I try to retrieve the transactionId fff56a01-5efd-46e4-816e-fbc66908567e,

Using https://demo-api.vivapayments.com/checkout/v2/isv/transactions/:transactionId?MerchantId=:merchantId
(see https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Retrieve-Transactions/paths/~1checkout~1v2~1isv~1transactions~1{transactionId}?merchantId={merchantId}/get)
which works well with smart checkout.

I receive:

```
response: {
    statusCode: 404,
    content: '{"status":404,"message":null,"eventId":"0"}',
    headers: {
      connection: 'close',
      'content-length': '43',
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 20 Mar 2023 14:51:34 GMT',
      'set-cookie': C372E7411B7ED1~000000000000000000000000000000~YAAQxgHzUU62WuaGAQAAVxGB/4QtggGX1QGO1pnHlcxZM8c3dA6A/u2DNK0xdFCmSeEGvSQkK+JDRWp0klIw9VOB9XtxIQih1S6hprHP/6TjX5ZqHji1+N7abP101UV31IAGtlxiUp1kTKIv+1JS69YAi05GnTYTwWcdLolOCXIY70hJxODPIq2c0fB0/f96q0TvUHZ6E1uJ6VumnUx0eqKCd5y6REubV+A8AgKV1KktovT7slfkJxe41J+WRJ8HBNp7epDOWrjXCb/N6LX2nlA=; Domain=.vivapayments.com; Path=/; Expires=Mon, 20 Mar 2023 16:51:34 GMT; nly',
      'strict-transport-security': 'max-age=31536000 ; includeSubDomains',
      'x-viva-correlationid': '23-079-F3890A6',
      'x-viva-eventid': '0'
    },
    ok: false,
    redirected: undefined,
    data: { status: 404, message: null, eventId: '0' }
  }
```

So, I don't know how to retrieve transaction since not found on ISV account.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for the additional information. We are investigating your issue. We will inform you as soon as we have any updates. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for waiting. Kindly note that the [Initiate sale API request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Make-Transactions/paths/~1ecr~1isv~1v1~1transactions:sale/post) is used for card present transactions. If the transaction is completed via Smart Checkout is identified as a card not present transaction, via a source that is created only to handle card present transactions. We kindly advise you to make a request and complete the transaction via your POS. After that try to retrieve the transaction via the [Retrieve Transaction by ID API request](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Retrieve-Transactions/paths/~1checkout~1v2~1isv~1transactions~1%7BtransactionId%7D?merchantId=%7BmerchantId%7D/get).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by adoyen** [comment]
Hello,
I thought that VW demo was not working using normal card. But in fact, I just have to authorize NFC for the application.
I succeeded to pass a payment using my bank card.
TransactionId : b0866127-99f9-4a98-864f-f3c98eaade57, viewable using Retrieve Transaction.

Nevertheless, does this mean that I cannot use the VivaWallet QR code in the VW Pos ?
This use is giving the issue I had explain in this post.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for your message. The transactions via REST API should be completed via POS and not via an e-commerce payment method (QR code which redirects to Smart Checkout).  Our REST API is designed so the ISV fee is declared and calculated via the [Initiate sale API request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Make-Transactions/paths/~1ecr~1isv~1v1~1transactions:sale/post) for card present transactions.

As you may already know the ISV fee for e-commerce transactions is declared and calculated in [Create Payment Order API request.](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Payments/paths/~1checkout~1v2~1isv~1orders/post)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by adoyen** [comment]
Hello @VivaWalletCustomerSupport ,

The QR code I followed is the one proposed by VW Pos demo, when I choose QR Code in place on Tap on Phone.
VW POS then show me the choice between Vivawallet QR code, Payconiq QR code and Alipay QR code.
<img src="https://user-images.githubusercontent.com/1709103/226664577-bc444b1a-e850-4f3d-a0a8-f12cdda2e233.jpeg" width="30%" height="30%"/>

Do you say that when we switch to QR code, it's considered as an internet payment without card presentation ?

In that case, how should I manage that ? 
Since I cannot block this functionnality on your VW Pos and prevent user to use it, the transaction created behind will be lost for the ISV.

Thanks.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for your answer. The transactions that are paid via QR Code are considered as CnP (card not present) transactions. We are investigating this matter and I will inform you as soon as we have any update.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by adoyen** [comment]
Hello @VivaWalletCustomerSupport ,

Have you any news about this issue ?

Thanks.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Sorry for the inconvenience. We are still investigating this issue. As soon as we have any updates, we will inform you. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

We apologize for the late response. After further investigation we would like to inform you that Viva Wallet QR code is not available yet for ISV accounts. Kindly note that those transactions will be successful, but the ISV amount will not be charged.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
