### ISSUE TITLE
Transmission of client information in VW POS

### ISSUE THREAD

**Issue by adoyen** [VivaPayments/API#2358]
Hello,

Is there any way to transmit client information like name, email, phone number when doing a payment through a terminal (like VW POS).

It could be useful while wanting to send ticket by email from VW POS and in "my sales" transactions client details (https://demo.vivapayments.com/selfcare/fr/sales/mysales).

Best regards

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you very much for contacting us. Can you please provide us with an example of the procedure you wish to execute? By ticket are you referring to receipt?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by adoyen** [comment]
Hello @VivaWalletCustomerSupport 

I would like to create a POS session using [Initiate a sales request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Make-Transactions/paths/~1ecr~1isv~1v1~1transactions:sale/post)

But in this API, it's not asked the name, firstname, email or phone number like it is in [Create payment Order](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Payments/paths/~1checkout~1v2~1isv~1orders/post).

So, in the VW POS, when the payment is successful and we choose to send to ticket by email, the email is asked (while we know it in our application).

Then, in the transactions list on merchant site, we can see the detail of the transaction:
![image](https://user-images.githubusercontent.com/1709103/227254539-27bcf601-4689-44b5-8d12-2073b62519d0.png)

Without any information filled in for the client.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for your prompt response. Please note that the fields from the Client tab were created for online payments. You cannot add these details from the terminal.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by adoyen** [comment]
Ok, it is what I thought.
Consider this issue as an ask for improvement.
You can close the ticket.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @adoyen,

Thank you for your comments. We always take our customers' feedback into consideration for future improvements.

Kind regards,
Viva Wallet E-commerce Support Team
