### ISSUE TITLE
Marketplace API - Cannot create a connected account - 403 - demo environment 

### ISSUE THREAD

**Issue by rafirr** [VivaPayments/API#2359]
Hello,
I'm trying to create a connected account using Marketplace API. I have demo account created on page:
https://demo.vivapayments.com/pl/signup

I'm trying to create a linked account, but I'm getting a 403 error. I think the problem is with the token and scopes, but I can't find information about getting a token to manage the marketplace API.

My steps:
1. OAuth2 Authentication:
![Zrzut ekranu 2023-03-30 o 12 20 55](https://user-images.githubusercontent.com/8736261/228807250-fb471256-67c9-4c8e-bec7-5e570e4107fb.png)

The username and password is from Smart Checkout Credentials section. I see that scopes:
`urn:viva:payments:core:api:acquiring:transactions urn:viva:payments:core:api:platform` are missing.

2. Create a connected Account
I'm using token getting from https://demo-accounts.vivapayments.com/connect/token endpoint, bug got 403 error:
![Zrzut ekranu 2023-03-30 o 12 27 05](https://user-images.githubusercontent.com/8736261/228808389-2946cd66-aee3-4c1f-b818-aac548935b58.png)

Should I use different OAuth2 endpoint or credentials? 

Edit:
Merchant ID: 94a7bb82-665d-42bf-8d7f-9d5c3bec7adb
Smart Checkout Client ID: atmrfhvz4v3yxgfcfe2ck3nj00849oqgpw70m8yeqwon7.apps.vivapayments.com

**Comment by VivaWalletCustomerSupport** [comment]
Hello @rafirr,

Thank you for your message. Kindly note that Marketplace API cannot be used by a simple demo account. Please follow the link below and fill in the form and we will contact you.

[https://www.vivawallet.com/contact](https://www.vivawallet.com/contact)

 After that we will onboard your demo account and Marketplace API will be available.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @rafirr,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by rafirr** [comment]
Hi @VivaWalletCustomerSupport, thanks! I'm waiting for a new demo accounts from support :)
