### ISSUE TITLE
Πρόβλημα Viva Native Checkout

### ISSUE THREAD

**Issue by paschalisp** [VivaPayments/API#236]
Αξιότιμοι κύριοι/ες καλημέρα σας,

Έχουμε υλοποιήσει μια custom web εφαρμογή για λογαριασμό πελάτη μας, την οποία έχουμε κάνει integrate με το Viva Payments Native Checkout.

Το πρόβλημα που έχουμε είναι το εξής:

Η δημιουργία συναλλαγής (CreateOrder) εκτελείται σωστά και επιστρέφει το token της κάρτας. Όμως κατά την χρέωση της κάρτας (MakePayment) το API επιστρέφει Error 400 Card decryption failed.

Ένα συγκεκριμένο call που μας επιστράφηκε σε κάποια από τα test, είναι το εξής:

HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 25 Jan 2017 09:33:01 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 265
Connection: keep-alive
Vary: Accept-Encoding
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
 
{"Emv":null,"Amount":null,"StatusId":"E","TransactionId":null,"ReferenceNumber":null,"RemainingRefunds":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ErrorCode":400,"ErrorText":"Card decryption failed","TimeStamp":"2017-01-25T11:33:00.8890311+02:00"}

Μπορείτε να μας κατατοπίσετε στο που εντοπίζεται το πρόβλημα ώστε να το διορθώσουμε άμεσα;
Υπάρχει κάποια σελίδα με τα πιθανά error codes του API;

Σας ευχαριστώ εκ των προτέρων.

**Comment by dmihos** [comment]
Καλησπέρα σας

Το μήνυμα σημαίνει ότι το token δε φτάνει στο API σωστά, πράγμα που συνήθως οφείλεται στο ότι λείπει κάποια διαδικασία escape, που θα προστατέψει τα special characters που περιέχονται.

Ευχαριστούμε για την επικοινωνία

**Comment by paschalisp** [comment]
Καλημέρα σας και ευχαριστούμε για την απάντηση.

Μπορείτε να μας καθογηγήσετε που χρειάζεται να γίνει το escaping, διότι χρησιμοποιούμε την class  NativeCheckoutClass αυτούσια, χωρίς κάποια αλλαγή.

(από εδώ: https://github.com/VivaPayments/API/blob/master/NativeCheckout/PHP/lib/NativeCheckoutClass.php)

```php
$orderCode=$this->CreateOrder($amount,$installments);
		
$obj=new PaymentRequest();
		
$obj->Amount=$amount;      // τιμή: 10000
$obj->OrderCode=$orderCode;     // τιμή: 16-digit numeric
$obj->SourceCode=$this->nativeCheckoutSourceCode; // τιμή: 4-digit numeric
$obj->CreditCard["Token"]=$cardToken; // τιμή: αλφαριθμητικό με κάποια spaces και slashes
$obj->Installments=$installments; // τιμή: 0 (μηδέν, numeric)
		
$resultObj = $this->ExecuteCall($this->baseApiUrl.$this->paymentsUrl,$obj);
```

Το $orderCode παίρνει σωστή τιμή, αλλά το $resultObj παίρνει τις εξής τιμές:

```php
$resultObj {stdClass} [11]
Amount = null
AuthorizationId = null
Emv = null
ErrorCode = 400
ErrorText = "Card decryption failed"
ReferenceNumber = null
RemainingRefunds = null
RetrievalReferenceNumber = null
StatusId = "E"
TimeStamp = "2017-02-03T11:48:10.359307+02:00"
TransactionId = null
```

Το μόνο που θα μπορούσε να χρειαστεί ίσως escaping είναι το token αλλά δεν έχουμε πειράξει την class, την καλούμε όπως ακριβώς είναι στο repo.

**Comment by paschalisp** [comment]
Hello again, I'd like to ask if you have any solution regarding our above issue?

**Comment by kostGX** [comment]
Closing as issue over 1 year old.
