### ISSUE TITLE
Canceling paid payment from web interface not reflected in api

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2361]
Hi,

I canceled a paid payment from the web interface.

When I call `GET https://demo.vivapayments.com/api/orders/8096464623190719` ([documented here](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1api~1orders~1{orderCode}/get)), the response is:

```json
{
  "OrderCode": 8096464623190719,
  "SourceCode": "7234",
  "Tags": [],
  "TipAmount": 0,
  "RequestLang": "fr-FR",
  "MerchantTrns": "",
  "CustomerTrns": "",
  "MaxInstallments": 0,
  "RequestAmount": 40,
  "ExpirationDate": "2023-04-01T17:20:46.233",
  "StateId": 3
}
```

`StateId` is 3 which means it is paid.

What am I doing wrong?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you very much for contacting us. We are currently investigating your issue. We will perform some technical checks and get back to you. Thank you for your time.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for waiting. I would like to inform you that our [Retrieve Order API call](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1api~1orders~1%7BorderCode%7D/get) retrieves the state of an order code and not the transaction. 

Kindly note that when an order code is paid even if it is cancelled, the status of the parameter "StateId" will be 3 (paid). The transaction ID of the actual payment and the cancellation are different. In a few words after the cancellation a new entry is displayed in your Viva Wallet account with the same order code but with a different transaction ID.

The values of the parameter "StateId" can be changed before the payment is completed.

For example, if the "StateId" of an order code is 2 (Canceled) it means that merchant that initiated the payment has cancelled the payment before his customer proceed to its completion.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Thanks for the detailed explanation.

It's clear and it all makes sense.

Regards,
