### ISSUE TITLE
Payment API question

### ISSUE THREAD

**Issue by jiggsaw85** [VivaPayments/API#2362]
Hi,

I have a demo account and lets say, some money on it. In real-world case, I'll have VivaWallet account connected with my bank account.

This is functionality I need:
1. user log in to my application
2. user earn some money inside my application
3. user has an option to click button "cash out", type amount and get money on his own bank account

On step 3, when user clicks "cash out" button and type amount, money from my VivaWallet should be transferred to his bank account. What we should consider is that user does not have VivaWallet account.
So, I need an API where I can transfer money from my VivaWallet account to someone's else bank account. User should have an option to just type his card number / bank account, and that is it.

Is there such an API and if so, please share documentation link with me.

Thanks in advance,
Rados

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85 

Thank you for your message. You can use the [Pay Out API](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions/paths/~1api~1transactions~1{transaction_Id}/delete). Our Pay out API pays directly an amount to a card. It is a refund transaction which allows you to return money to a card, irrespectively of the original payment amount.

Please note that this option is available only upon request. If you want to request this feature, please contact by emailing support@vivawallet.com

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by jiggsaw85** [comment]
I found merchant ID: d4af135e-9d91-4b71-984b-cc246fe4dd7a

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
