### ISSUE TITLE
Execute bank transfer issue

### ISSUE THREAD

**Issue by jiggsaw85** [VivaPayments/API#2363]
Hi,

I have decided to use "execute bank transfer" API. First, I am linking bank account in order to get "bankAccountId" and this goes well, I got it.

Now, when I try to execute bank transfer, request is good, but I am always getting a response with the message: "_Insufficient funds for command creation, wallet 626389892475 ...._"

This is ok response because I have 0EUR on my demo account from which I am trying to send money. Now the question is, how can I perform bank transfer since I do not see an option to add some funds on my account in demo purposes?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85, 

Thank you for your message. Can you please share your DEMO merchant ID? We will transfer the funds to the demo account.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by jiggsaw85** [comment]
Hi,

Thank you for the fast answer.
I am not sure where to find merchant ID, but I suppose this is my "account id", so I am sending you account id and account IBAN number:

**AccountID:** 626389892475
**IBAN number:** GR8370100000000626389892475

**Comment by jiggsaw85** [comment]
I found merchant ID: d4af135e-9d91-4b71-984b-cc246fe4dd7a

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85,

Thank you for the information. We added funds to your demo account as requested.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jiggsaw85,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
