### ISSUE TITLE
Compatibility with Serverless functions

### ISSUE THREAD

**Issue by tsamantanis** [VivaPayments/API#2364]
Our team uses the latest tech stack building e commerce solutions with headless architecture. Much of our backend functionality runs using **serverless functions**, which means **we cannot provide a specific IP Address from which we will be making requests to the Viva API,** as the system is designed to scale on command. Can we use all the Smart Checkout features in a production environment without providing a specific server IP Address? 

So far I have made some tests with the `/connect/token` and the `/checkout/v2/orders` endpoints and they work normally for our preview deployments. Can you confirm we will not run into any IP Address related issues if we complete the full Smart Checkout integration in our production environment? 

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tsamantanis,

Thank you for your message. We would like to inform you that there is no limitation on the IPs from which we accept API requests. You can use any IP you wish.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tsamantanis,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by tsamantanis** [comment]
Yes I have read it and no longer need assistance. Thank you !Philippos Tsamantanis On Apr 7, 2023, at 17:26, VivaWalletCustomerSupport ***@***.***> wrote:﻿
Hello @tsamantanis,
We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.
In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.
However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!
Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tsamantanis,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
