### ISSUE TITLE
Test Cards are not working in Demo environment with Redirect v2

### ISSUE THREAD

**Issue by Mminas** [VivaPayments/API#2365]
I am setting up a new e-shop and going through the testing phase. 

Whichever test card from https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#test-cards I am using I'm getting an error that says my transaction has failed but the redirect doesn't even return to the failed transaction page.

![Screenshot 2023-04-11 110528](https://user-images.githubusercontent.com/50442326/231096587-4938fbf1-122b-470f-b835-ce0980aeb7a0.png)

The error returned by the system in JSON format is 
{"status":412,"message":"Unable to resolve 3d provider","eventId":"1"}

I cannot find any documentation regarding it. Any help is appreciated.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Mminas, 

Thank you very much for contacting us. Kindly note that test cards are only available in the sandbox/demo environment. Could you please tell us the URL of your website and the Demo Merchant ID? 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Mminas** [comment]
Thank you for your time,

I am using the Demo/Sandbox environment.

My demo Merchant ID is *a97ba0a0-8519-4a23-a1ad-bf828fee1d79* and my
website's URL https://verogelato.gr

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Mminas,

Thank you for the additional information. Please try again, if issue persists send us the full body request to further investigate.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Mminas** [comment]
The full body of which request?

You have to understand that I am properly posting a request to get a
transaction order code, and it returns a proper OrderCode successfully.

I then use this OrderCode to redirect to the transaction URL (
https://demo.vivapayments.com/web/newtransaction.aspx?ref=[MY ORDER CODE]).
I get the proper transaction interface, I insert the test card properties,
and I don't get either a decline or an accept or anything else.
I get the error I've already posted.

So this error occurs during a request from the Vivawallet payment form to
the vivawallet backend.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Mminas,

Thank you for your prompt response. Further to our technical checks, we did not experience any issues with the test cards.
Could you please share the request you used (full code) to investigate the issue?   

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Mminas** [comment]
As I explained before my request to get redirected to the viva interface
processes normally without errors. Here are its contents:

REQUEST HEADERS
Host: demo.vivapayments.com
authorization: Basic
YTk3YmEwYTAtODUxOS00YTIzLWExYWQtYmY4MjhmZWUxZDc5OldtdDJXUw==
accept: */*
content-length: 165
content-type: application/x-www-form-urlencoded

REQUEST VALUES
Amount=4464&disableCash=true&paymentTimeOut=600&AllowRecurring=false&RequestLang=el-GR&SourceCode=3964&merchantTrns=168139274600012&customerTrns=Vero+Gelato+Purchase

RESPONSE HEADERS
HTTP/2 200
content-type: application/json; charset=utf-8
content-length: 157
x-viva-correlationid: 23-103-C29F867D
rp: 03
date: Thu, 13 Apr 2023 13:38:10 GMT
server-timing: cdn-cache; desc=MISS
server-timing: edge; dur=25
server-timing: origin; dur=41
strict-transport-security: max-age=31536000 ; includeSubDomains
strict-transport-security: max-age=31536000;IncludeSubDomains
set-cookie:
ak_bmsc=1997FA7F572D15274018C576E09DD3A1~000000000000000000000000000000~YAAQrWQRAiDmnnGHAQAAnH/WehOElA5iA6Zw3IEPW+jLaPKEPBScDJ1wPTVfleL6kdYLfmI7ccrfBZJc73YT3v9czjtcYAIyWDXpNk4Rb8ELZILUNF9MUBTHeO8nirWmZ4jPlKVN/DI0ayTWM6kR+QbFJYSRUD2YY2hWpEHg7bKfGvahc7KUUvJYUrNmAt/u95QehL+LQcU8W/AASvGe1Ok1o8xG/UGmYQIHXwU4ow0DYIUs9fBUaRr4UY2MA/HL8eQy/VOb3s853J4zCb9CjDb/B2+n36xoz3T8XbPso1+i4NtRmFIo3HUZQTqv7FSQ55bF+5PpSBFsvgCI2VqhyxzDLv8UNDLV0u6Nlft55yI2GL1kHX2IF5NsgI+YpZWIWAw8TGI6DgC8Ghva8w==;
Domain=.vivapayments.com; Path=/; Expires=Thu, 13 Apr 2023 15:38:10 GMT;
Max-Age=7200; Secure; HttpOnly
server-timing: ak_p; desc="467053_34694317_293184842_6605_4452_8_0";dur=1

RESPONSE VALUES
{"OrderCode":5590432806572607,"ErrorCode":0,"ErrorText":null,"TimeStamp":"2023-04-13T16:38:10.4328065+03:00","CorrelationId":null,"EventId":0,"Success":true}

Where the error occurs is inside the vivawallet interface during a request
originating from the viva payment form. Its content is as follows:

REQUEST HEADERS
POST /web2/checkout/v2/chargetokens HTTP/2
Host: demo.vivapayments.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0)
Gecko/20100101 Firefox/113.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,el-GR;q=0.8,el;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/json;charset=utf-8
Content-Length: 327
Origin: https://demo.vivapayments.com
DNT: 1
Connection: keep-alive
Referer: https://demo.vivapayments.com/web2?ref=8544010509772606
Cookie:
_abck=6CABE39E4D2621B9D62D7B8DCAA8CC28~0~YAAQ9hdlX5PluXGHAQAADRDGegkOogG784d+tRGohUDKgN+KwfpEhHdR5aqW2f87C4RLrzeQmA7uVTB0x80UeruH/bmeCX/t/CYjybhsH4L3iaEXQiPIHoNCtTE8oIQQpGhu+cCdYiXVo3c9/o+8Xrhu+8UDLR3oEn1HOZQxM+r4T2GNeheauZlGutFvMPMCMtwM/luaHeQLm8EuPDQmw7EFxSZ4zqAHIx9YLXDPIdU2ZN1KjdTIyEdD3kauwq4h3AZ2whzIj14N3v7o1Psh8sXFW6QCkt4gKW6cYunzx8+5WuDQc5ocozB7R3r1x5mirk8q+7d3USshqhhAt8ddt2Kvl24qSxojFaynUnjvUn8ppFncobFreQNbsXszED2MkpNlC4DBFhG7X++3L7elSigGddks3ALnWZlwZOxx8A==~-1~||-1||~-1;
ak_bmsc=71BA45A5CC151767D8981B223D941493~000000000000000000000000000000~YAAQ9hdlX/3kuXGHAQAAkg7GehOlV3c36ASiHWq3v2BlSoxIIwMxf9Le2tlZ2BWwq9K0eTBzDo8zjRsHBRPxxgd7V6o3QLwn5/IrdQQrAQ0HGNIS3Lmw3ehVMS08OLZLknjslGal93NMhvaXbjhf8yq6rllaQstz3AeMBUmXanh27SnW0QawwLk9Si4GsnWYYer4cnico++bzyWAhBqN9egwyKZyp5oUk4NAA88bHIiw5x/O5KOcmA9i7HMNnqJS9mXAP9E+DjuHpKSw5wxLdffjalwztRiaKzV0c8cc4Fb795aWU6JDqOxmhDbhPEfyitHYfoj66N9pGYTK4RaoOP8I4SYRJxk3FvU/2EhljHuUHV/gS+4MukycKBZv6jQUAjpDHgd6nO3OggBkwyRc+YJxnnV25AFadxxAfXcFwmLSvS55PDk=;
bm_sz=1F0D257A4A9F9C232B505322E1C1B875~YAAQ9hdlX9TiuXGHAQAAKAjGehPHdJJKpdriG5MOlSPXgwnYY2HZ1iAP0bHUeh2LpzirCgz6xNkBpcBZJ+9cLisvb2SeUGOdutv04nAIFH2YyiYP7Lz8n3WaLTDq9RJZION0qakc1cuCkQ1Kb64f9WcnhSgepCz60zEjYFaN5RNRrMrKAy+LlbIWHVRT5UUhWnAhYGHUpxYcQ1SZw20FyE6FCpFLRgEC0OKS82Us3XKrkD8G0X3mLHy3t8PupjBFIl5uYFiX9kSFBg+TqVZhPq/d14ENpKKT/ouJt+Zn+OLJ7mIvciOAR20=~4343353~4273989;
bm_mi=BFEA50B78860200D678301CEFAE1BD2F~YAAQ9hdlX+3iuXGHAQAAkwjGehNsNZb9+7vT+drpx67+tQC1sdKMWwtOanrLZH1lZA6dQL/0SPoUEEomspAliVt5GhQXLPA6fTnHoPBzfON++x/SM/93SVUtEzmi7oa/IqqPrasIG662D0cNMLp7zaS/dFT/coFFDyKQjcu9gOSQ/ji2sB5btT2DvnctBbPXWf8FAwmGFa3tamV9fMa7As60AFwdIrgbupFB2SucMZFx4QkP1aO4xVCPWkfN46089E10fI2NRZ4qrd1+ALitC3beiTrQlwbNGrHKEnFxQnryt+MQkB9AeSbXVylAHiMRtaf+F+dr~1;
bm_sv=72EF199C2D7A438DAF6018C8D9C2F4C9~YAAQ9hdlX8Fev3GHAQAA7mfZehMxxdMs8bWPdSFglqV2pJ6nILTRLVebba+SBsnVls7F2M22hnL/5Zh7kj8RtE2ABQZNAaB5CJHJKwkjS0MrOrePey6/TWZOFvo3kcJgeAqJ7Gn9/vBPZI24A8yYayRBYS3GwUtdBxb3ynrmxYMXDNQjm5Ro0SC/HjNa/71VPoWrr43k+wsPSG/b05ruVzoRr8WKFaypPhM0tMqr4hhq/J70OxlrTz+ETtF4mmQektJrS5XuPg==~1;
_dd_s=rum=1&id=29d92474-ea59-4cf1-8302-592f89ee1889&created=1681393245558&expire=1681394203532
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
TE: trailers

REQUEST VALUES
{"orderCode":"8544010509772606","amount":4464,"currencyCode":"978","cvc":"456","number":"4147463011110133","holderName":"My
Name","expirationMonth":"12","expirationYear":"24","installments":0,"customer":{"email":"
***@***.***","fullName":"My
Name"},"rememberCard":false,"friendlyName":"","maskedNumber":"414746XXXXXX0133"}

RESPONSE HEADERS
HTTP/2 412 Precondition Failed
content-type: application/json; charset=utf-8
x-viva-eventid: 1
x-viva-correlationid: 23-103-13128A0C
content-length: 70
date: Thu, 13 Apr 2023 13:41:43 GMT
server-timing: cdn-cache; desc=MISS
server-timing: edge; dur=17
server-timing: origin; dur=27
strict-transport-security: max-age=31536000 ; includeSubDomains
server-timing: ak_p; desc="467053_1600460790_234641882_4456_3412_69_0";dur=1
X-Firefox-Spdy: h2

RESPONSE VALUES
{"status":412,"message":"Unable to resolve 3d provider","eventId":"1"}

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Mminas, 

Thank you for your answer. We are investigating this matter, I will inform you as soon as we have any update.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Mminas,

Thank you for waiting. Can you please create an order code and share it with us? On the "paymentTimeout" parameter please use the value 65535 so the payment order never expires. Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Mminas** [comment]
I have created an order code without a timeout:

The order code is
7355274556872602

The link to the viva payment form is
https://demo.vivapayments.com/web2?ref=7355274556872602

I tried completing the transaction with the 4147 4630 1111 0133 Visa test
card and I still get the same error.
Thank you for your efforts so far. I am looking forward to your reply.

**Comment by VivaWalletCustomerSupport** [comment]
Helo @Mminas,

Thank you for the additional information. We are currently investigating the issue. We will let you know as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Mminas,

Thank you for waiting. Can you please try to complete a transaction with one of our test cards? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Mminas** [comment]
I tried a new transaction and it was completed successfully.

The issue seems to be resolved.

Thank you for all your trouble.

Is there something I did wrong in my implementation that caused this
trouble? Was something wrong with my test account?

Any input is appreciated.

Thank you again for your help and your immediate responses.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Mminas,

Thank you for the feedback. We identified a technical issue in your demo account which affected the 3DS functionality in your demo account. This issue has already been resolved.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Mminas** [comment]
Thank you again for your assistance in addressing this issue.

Best Regards,
Minas

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Mminas,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
