### ISSUE TITLE
Starting EFT POS payment doesn't work

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2366]
Hi,

Some time ago, I programmed the POS api to start a payment on a VW One on a demo account.

I'm now trying to do the same on a prod account and a prod soft pos.

Calling the [api to initiate a sale request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Transactions/paths/~1ecr~1v1~1transactions:sale/post) returns status code 200 with zero content (empty string and content-length is zero) instead of the documented json response:

```
curl 'https://api.vivapayments.com/ecr/v1/transactions:sale' -H 'Authorization: Bearer token_redacted' -H 'content-type: application/json' -d '{"sessionId":"PP3272741-39bbea4cfc","terminalId":"16217194","cashRegisterId":"M6TABHP269","amount":1010,"tipAmount":0,"currencyCode":"978","merchantReference":"4/11929730/1K Live Emisys","customerTrns":"some-reference","preauth":false,"maxInstalments":0}'
```

No payment is started on the terminal with that tid.

Is there something to configure on my side or yours to make the VW one accept an EFT payment?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you very much for contacting us. Can you please tell us the version of the VW Pos App?
Kindly note that the app must be updated to latest version. Also, terminals screen must be enabled for the sales request to appear on the screen.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

I'm using VW Pos version v4.19.2(7193).

My code works with the demo app and a demo account. It fails as described above when I use the prod app with the prod account.

I tried to regenerate the pos API secret to no avail. I double checked the client Id and secret by decoding the base64 header of the OAuth token request sent over the network.

I tried to start the payment on two VW One and one VW Next. I uninstalled and reinstalled the app on the VW Next. The result is the same. No payment is started on the terminal and the response is a success (http code 200) with an empty body response.

In case it helps, one of the response contains this tracking header: x-viva-correlationid: 23-101-D23D72F05F78.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for the additional information. We are investigating your request. We will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Thank you for investigating this issue.

Here are some more info I gathered with postman.

* Using an unknown or invalid TID returns a 200 http code with an empty body.
* Trying to get an OAuth token with the merchant ID and api key returns an error (as expected).
* Initiating a sale request with an OAuth token obtained with the smart checkout ID and secret returns the json response `{"detail": "Could not validate credentials"}`. This is expected as the OAuth token doesn't cover the `urn:viva:payments:ecr:api` scope.
* Searching for live devices returns my TID `{ "statusId": 1, "sourceCode": "5030", "terminalId": "16217200", "virtualTerminalId": "dDzWu…prvR" }`
* Initiating the same sale request twice returns the json response `{"detail":"Session already exists"}` (as expected).

From all this, I'm confident I'm using the correct credentials for the POS API and the TID is indeed registered as a live device of the right merchant.

I also tried to set a pin code, disable manual payments, disable refunds and enable kiosk mode on the VW pos app.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for the update. Can you please provide the Tids of the other two terminals you also tried? Also, send logs from all terminals from the menu "more" then select "Send Logs".

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Thanks for your prompt answer.

Logs have been sent for TID 16217200.

The other two terminals are not currently with me. I'll send the logs tomorrow when I have access to the terminals.

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

With the help of your VW representative, we identified the issue.

The terminal must be registered by the account owner.

I'm just an account user. I can add the new terminal but it silently ignores sale requests. Disconnecting the terminal I previously registered and asking the account owner to register it again solves the issue.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you again for the update. Since the issue has been resolved, this ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Please note we have found a **workaround**. We are still in need of a real **solution**.

A terminal is unusable if it is registered by an account user. We can't depend on the unique account owner to register all the terminals. This is especially cumbersome with an ISV integration where the account owner is not expecting to do such a menial task.

Fixing the terminal creation is on your side.
