### ISSUE TITLE
Initiating sales request on PAX A920/A920 does not work

### ISSUE THREAD

**Issue by sheldon-hr** [VivaPayments/API#2367]
Hello,

We have horeca cash register/system integrated with the vivawallet through rest API.
For some time it is used by our clients with CS50C ciontek and also with their mobile phones/tablets.
One of our clients got PAX A920/A920 and it seems that we are missing something in the communication with it.

https://api.vivapayments.com/ecr/v1/devices:search
Returns device in statusId: 1

We can initiate sales request
https://api.vivapayments.com/ecr/v1/transactions:sale 
it returns 200 but nothing is visible on the pax device.
Is there something different that needs to be set up?

We have tried various solutions, such as setting the terminalId to S/N displayed on the device, S/N from the selfcare (which differs in the first two numeric digits), and the TID from selfcare, but to no avail.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @sheldon-hr,

Thank you very much for contacting us. Please note that REST API functionality is not available yet for Paydroid (PAX) devices.
Additional information can be found [here](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/#supported-devices).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by sheldon-hr** [comment]
Hey @VivaWalletCustomerSupport do you maybe have approx time when we can expect this functionality?
Just something we can communicate to our customers, end of month, quartal, end of year?

Thank you very much

**Comment by VivaWalletCustomerSupport** [comment]
Hello @sheldon-hr,

Thank you for your prompt response. Unfortunately, we don't have an estimated release date. We kindly recommend you visit our [developer's portal](https://developer.vivawallet.com/releasenotes/) regularly for upcoming releases.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @sheldon-hr, 

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @sheldon-hr,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
