### ISSUE TITLE
Invalid or inactive reseller 

### ISSUE THREAD

**Issue by gtsoukasgr** [VivaPayments/API#237]
Καλησπέρα , προσπαθώ να φτιάξω ένα module για πληρωμή μέσω viva στο NopCommerce σε c#.
Βάση την βιβλιογραφία σας παίρνω το παρακάτω λάθος μετά το authentication

Invalid or inactive reseller with id f62cfb3d-9970-44a9-a715-b8885cbd379d

Μπορείτε να μου πείτε τι συμβάνει?

**Comment by dmihos** [comment]
Καλησπέρα σας
Τα περιβάλλοντα demo/παραγωγή είναι ξεχωριστά, συνεπώς απαιτείται διαφορετικό merchantId για το demo περιβάλλον. Μπορείτε να φτιάξετε ένα account στο http://demo.vivapayments.com/el-gr/signup για τις δοκιμές σας

**Comment by gtsoukasgr** [comment]
Πολύ σωστά .
Σας ευχαριστώ.
