### ISSUE TITLE
Suggestion: Matching webhook with EFT POS payment

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2371]
Hi,

I would like to make a suggestion for future developments.

I'm using the EFT API to [initiate a sale request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Make-Transactions/paths/~1ecr~1isv~1v1~1transactions:sale/post) on a terminal.

The sale request is identified by a `sessionId` but [Transaction payment webhooks](https://developer.vivawallet.com/webhooks-for-payments/transaction-payment-created/) don't contain the `sessionId`.

Matching the webhook with the terminal payment would be easier if [initiating a sale request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Transactions/paths/~1ecr~1v1~1transactions:sale/post) returned the `OrderCode` and/or `TransactionId` in addition to the success message.

Thanks,

**Comment by SamuelMichelRiad** [comment]
+1 - this would be immensely useful and avoid multiple lookups to identify the transaction.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys, @SamuelMichelRiad,

Thank you for your suggestion. We always consider our customers' feedback for future improvements. We will review your request and possibly, it will be available in a future release.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys, @SamuelMichelRiad,

We just wanted to follow up on the reply we sent on Tuesday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Sorry for not answering. I assumed your last message meant you would come back with a more comprehensive answer once the suggestion had been reviewed :confounded: 

Indeed, you may close this ticket if you have no additional information to share with us.

Thank you for taking this suggestion into consideration.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys, @SamuelMichelRiad,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
