### ISSUE TITLE
EFT POS api payment first reported as rejected and then unexpectedly succeed

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2373]
Hi,

One of our point of sale [initiated a sale transaction](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Transactions/paths/~1ecr~1v1~1transactions:sale/post) on terminal with TID 16253898.

Our server received, within 3 seconds, a [transaction failed](https://developer.vivawallet.com/webhooks-for-payments/transaction-failed/) webhook (eventId 1798) with `MessageId` 6f268b13-d916-43f1-ade8-1dc8e2ce27df, `ResponseEventId` 10300 and `TransactionId` 9f08747d-ac34-48d4-bd12-e56c8cf5a1c8.

9 seconds later, we received a [transaction payment created](https://developer.vivawallet.com/webhooks-for-payments/transaction-payment-created/) webhook (eventId 1796) with `MessageId` 49fbeb76-516c-4578-b3ed-ad292fb00acc and `TransactionId` f5a5b34d-52dc-407b-8740-a855964d4054.

I'm sure the point of sale didn't initiate a second payment. So, multiple transactions were created without our knowledge.

The first failure webhook disrupted the process as the pos operator was informed of the failure but not of the success that came later.

Incidentally, I observe the same problem with `transactionID` cd5f5d25-9fa5-4edf-81bf-9f43bc670166 and 1d1db61c-559c-484a-8036-3459ce508678. So, it happened twice on the same day.

Transaction status is always double checked with [retrieve transaction](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions/paths/~1checkout~1v2~1transactions~1{transactionId}/get) when a webhook is received. The first failed webhook was confirmed to have `StatusId` "E" (error).

Can you please advise on how to safely deal with payments that are first reported as failed and then as paid?

Is it possible to determine the failure is temporary?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for your message. The failed attempts and the completed transactions have 2 different order codes generated which means that 2 different requests have been made. In a terminal device there are 2 ways an order code to be generated, by our [initiate a sale transaction API request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Transactions/paths/~1ecr~1v1~1transactions:sale/post) or manually by the owner of the terminal. We would like to advise you to double check if the point sale initiated a second attempt.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

I hadn't spotted the single digit difference between the two order codes 310921476**6**253898 and 310921476**7**253898. Thank you for pointing that out :slightly_smiling_face:  

It appears the offending payments occurred during the api disturbance we observed from April, 18th around 18:00 (Brussels time) until the next morning.

As the eft api was mostly unusable, operators were instructed to manually encode payments.

In this case, the operator started a payment with the api but the payment failed. He may then have started a manual payment for which I see no traces as manual payments don't go through our system.

What puzzles me is that both payments have the same `MerchantTrns`.

Is it expected for a manually encoded payment to reuse the same merchant reference as the previously failed api payment?

**Comment by fmarchalemisys** [comment]
Hi,

First, I'm wrong about the timing. Those errors didn't occur during the api outage as operators were only encoding manual payments at that time. The two cases happened the day after, on April 19th.

Yesterday, 6 more payments got corrupted due to this error.

Here is one failed webhook response:

```json
{
  "Url": "https://…",
  "EventData": {
    "Moto": false,
    "BinId": 50,
    "Ucaf": null,
    "Email": null,
    "Phone": null,
    "BankId": "NET_BNCT",
    "Systemic": false,
    "Switching": false,
    "ParentId": null,
    "Amount": 10,
    "ChannelId": "09913a34-c7d2-4e99-a3a7-550f2063d3b1",
    "TerminalId": 16253898,
    "MerchantId": "1b5a77ac-2017-ed11-b83e-0022489c5155",
    "OrderCode": 3110214838253898,
    "ProductId": null,
    "StatusId": "E",
    "FullName": null,
    "ResellerId": null,
    "DualMessage": false,
    "InsDate": "2023-04-20T22:28:03.473",
    "TotalFee": 0,
    "CardToken": "42A8B70F2E606D8A21B0C45AC23A2AEC2CF889AB",
    "CardNumber": "487104…",
    "TipAmount": 0,
    "SourceCode": "1180",
    "SourceName": "Ticket Sur Place",
    "Latitude": 50,
    "Longitude": 4,
    "CompanyName": "…",
    "TransactionId": "0586c622-54f1-4ad8-8efa-5cda82e74287",
    "CompanyTitle": "…",
    "PanEntryMode": "07",
    "ReferenceNumber": 162800,
    "ResponseCode": "182",
    "CurrencyCode": "978",
    "OrderCulture": "nl-BE",
    "MerchantTrns": "[PP3294521-dcb8905751]614/11987870/WS …",
    "CustomerTrns": "Votre commande #11987870 …",
    "IsManualRefund": false,
    "TargetPersonId": null,
    "TargetWalletId": null,
    "AcquirerApproved": false,
    "LoyaltyTriggered": false,
    "TransactionTypeId": 5,
    "AuthorizationId": "000000",
    "TotalInstallments": 0,
    "CardCountryCode": "BE",
    "CardIssuingBank": "BNP PARIBAS FORTIS NV/SA.",
    "RedeemedAmount": 0,
    "ClearanceDate": null,
    "CurrentInstallment": 0,
    "Tags": [],
    "BillId": null,
    "ConnectedAccountId": null,
    "ResellerSourceCode": null,
    "ResellerSourceName": null,
    "ResellerCompanyName": null,
    "CardUniqueReference": "42A8B70F2E606D8A21B0C45AC23A2AEC2CF889AB",
    "ResellerSourceAddress": null,
    "CardExpirationDate": "2027-09-30T00:00:00",
    "RetrievalReferenceNumber": "311019162800",
    "AssignedMerchantUsers": [
      "015716dd-7420-4c0c-8bc7-167213e60f72"
    ],
    "AssignedResellerUsers": [],
    "CardTypeId": 0,
    "ResponseEventId": 10300,
    "ElectronicCommerceIndicator": null,
    "OrderServiceId": 0,
    "DigitalWalletId": null
  },
  "Created": "2023-04-20T19:28:03.8391361Z",
  "CorrelationId": "23-110-7E033946",
  "EventTypeId": 1798,
  "Delay": null,
  "MessageId": "f97f44b3-ddf9-4078-b1e6-0b52a9cb53e6",
  "RecipientId": "1b5a77ac-2017-ed11-b83e-0022489c5155",
  "MessageTypeId": 512
}
```

So, I have two questions at this point:

1. Why are we receiving this error with `ResponseEventId` 10300? It contains payment card info.
2. Why is the success webhook using the same merchant reference as the failed webhook?

**Comment by fmarchalemisys** [comment]
Hi again,

A person in charge on site confirms that pos operators **can't** start manual payments on the *VW Next* connected to the pos. Keyboards are disabled and protected by a pin code on every one of them. When a payment fails, operators are allowed to use a spare *VW One* to start a manual payment.

So there is no way the second payment can be started by the operator on the same terminal.

Even so, I tried to start an API payment on the demo app and then a manual payment on the same terminal. The manual payment never contains the merchant reference of the previous api payment.

In demo mode, I produced api payments failing with `ResponseEventId` 10200 and 10006. I then started a manual payment. It doesn't behave like what I'm seeing with the webhooks in prod.

I can't reproduce error 10300. It's not in the [list of test codes](https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#an-issuer-decline-with-decline-recovery).

In no way was I able to produce a webhook with a non null `parentId`.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for the additional information. This issue is under investigation. We will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Can you please provide us with logs/responses of those transactions from your ECR system so we can investigate the issue further? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Detailed logs are not enabled on our production server. I don't have the content of the api calls exchanged with the api.

I enabled full logging now. We have to wait for the problem to occur again. I'll let you know once/if I capture the problem.

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

As requested, here is one exchange between our server and yours.

[2023-04-21T20:56:41.348965+02:00]
Request to /ecr/v1/transactions:sale
```
{"sessionId":"PP3296441-f39710992b","terminalId":"16253546","cashRegisterId":"POS005","amount":4200,"tipAmount":0,"currencyCode":978,"merchantReference":"[PP3296441-f39710992b]614/11992349/EE …","customerTrns":"Votre commande #11992349 pour …"}
```

[2023-04-21T20:56:42.033999+02:00]
Response header (body is empty)
```
{"content-length":["0"],"server":["uvicorn"],"x-process-time":["0.6090199947357178"],"x-viva-correlationid":["23-111-FDF0A044A2DC"],"date":["Fri, 21 Apr 2023 18:56:42 GMT"],"connection":["keep-alive"]}
```

[2023-04-21T20:56:49.669380+02:00]
Webhook from 51.138.37.238
```
{"Url":"https://webhook.byemisys.com/vivawallet/webhook?project=614","EventData":{"Moto":false,"BinId":47,"Ucaf":null,"Email":null,"Phone":null,"BankId":"NET_BNCT","Systemic":false,"Switching":false,"ParentId":null,"Amount":42.0,"ChannelId":"09913a34-c7d2-4e99-a3a7-550f2063d3b1","TerminalId":16253546,"MerchantId":"1b5a77ac-2017-ed11-b83e-0022489c5155","OrderCode":3111202833253546,"ProductId":null,"StatusId":"E","FullName":null,"ResellerId":null,"DualMessage":false,"InsDate":"2023-04-21T21:56:49.32","TotalFee":0.0,"CardToken":"FC18FC73924DA99621FEDD34B05A08B86CCB38C7","CardNumber":"670342XXXXXX5014","TipAmount":0.0,"SourceCode":"1180","SourceName":"Ticket Sur Place","Latitude":50.8,"Longitude":4.3,"CompanyName":"…","TransactionId":"b025ef44-b8e9-455f-abcd-a2e6de4727f8","CompanyTitle":"…","PanEntryMode":"07","ReferenceNumber":821996,"ResponseCode":"182","CurrencyCode":"978","OrderCulture":"nl-BE","MerchantTrns":"[PP3296441-f39710992b]614/11992349/EE …","CustomerTrns":"Votre commande #11992349 pour …","IsManualRefund":false,"TargetPersonId":null,"TargetWalletId":null,"AcquirerApproved":false,"LoyaltyTriggered":false,"TransactionTypeId":5,"AuthorizationId":"000000","TotalInstallments":0,"CardCountryCode":"BE","CardIssuingBank":"Kbc Bankverzekeringsholding (k","RedeemedAmount":0.0,"ClearanceDate":null,"CurrentInstallment":0,"Tags":[],"BillId":null,"ConnectedAccountId":null,"ResellerSourceCode":null,"ResellerSourceName":null,"ResellerCompanyName":null,"CardUniqueReference":"FC18FC73924DA99621FEDD34B05A08B86CCB38C7","ResellerSourceAddress":null,"CardExpirationDate":"2027-09-30T00:00:00","RetrievalReferenceNumber":"311118821996","AssignedMerchantUsers":["015716dd-7420-4c0c-8bc7-167213e60f72"],"AssignedResellerUsers":[],"CardTypeId":6,"ResponseEventId":10300,"ElectronicCommerceIndicator":null,"OrderServiceId":0,"DigitalWalletId":null},"Created":"2023-04-21T18:56:49.6307129Z","CorrelationId":"23-111-DE665B85","EventTypeId":1798,"Delay":null,"MessageId":"b2eb8cdd-5c2b-46bc-a0b0-c901b91ebe3e","RecipientId":"1b5a77ac-2017-ed11-b83e-0022489c5155","MessageTypeId":512}
```

[2023-04-21T20:57:00.623841+02:00]
Webhook from 51.138.37.238
```
{"Url":"https://webhook.byemisys.com/vivawallet/webhook?project=614","EventData":{"Moto":false,"BinId":47,"Ucaf":null,"Email":null,"Phone":null,"BankId":"NET_BNCT","Systemic":false,"Switching":false,"ParentId":"b025ef44-b8e9-455f-abcd-a2e6de4727f8","Amount":42.0,"ChannelId":"09913a34-c7d2-4e99-a3a7-550f2063d3b1","TerminalId":16253546,"MerchantId":"1b5a77ac-2017-ed11-b83e-0022489c5155","OrderCode":3111202834253546,"ProductId":null,"StatusId":"F","FullName":null,"ResellerId":null,"DualMessage":false,"InsDate":"2023-04-21T21:56:59.793","TotalFee":0.0,"CardToken":"FC18FC73924DA99621FEDD34B05A08B86CCB38C7","CardNumber":"670342XXXXXX5014","TipAmount":0.0,"SourceCode":"1180","SourceName":"Ticket Sur Place","Latitude":50.8,"Longitude":4.3,"CompanyName":"…","TransactionId":"582fe274-0d89-4c82-968c-73bbecec1f47","CompanyTitle":"…","PanEntryMode":"07","ReferenceNumber":822229,"ResponseCode":"000","CurrencyCode":"978","OrderCulture":"nl-BE","MerchantTrns":"[PP3296441-f39710992b]614/11992349/EE …","CustomerTrns":"Votre commande #11992349 pour …","IsManualRefund":false,"TargetPersonId":null,"TargetWalletId":null,"AcquirerApproved":false,"LoyaltyTriggered":false,"TransactionTypeId":5,"AuthorizationId":"F24306","TotalInstallments":0,"CardCountryCode":"BE","CardIssuingBank":"Kbc Bankverzekeringsholding (k","RedeemedAmount":0.0,"ClearanceDate":null,"CurrentInstallment":0,"Tags":[],"BillId":null,"ConnectedAccountId":null,"ResellerSourceCode":null,"ResellerSourceName":null,"ResellerCompanyName":null,"CardUniqueReference":"FC18FC73924DA99621FEDD34B05A08B86CCB38C7","ResellerSourceAddress":null,"CardExpirationDate":"2027-09-30T00:00:00","RetrievalReferenceNumber":"311118822229","AssignedMerchantUsers":["015716dd-7420-4c0c-8bc7-167213e60f72"],"AssignedResellerUsers":[],"CardTypeId":6,"ResponseEventId":null,"ElectronicCommerceIndicator":null,"OrderServiceId":0,"DigitalWalletId":null},"Created":"2023-04-21T18:57:00.5691132Z","CorrelationId":"23-111-DE665B85","EventTypeId":1796,"Delay":null,"MessageId":"c03f8187-1d95-468a-a9e4-8ebf44cf3841","RecipientId":"1b5a77ac-2017-ed11-b83e-0022489c5155","MessageTypeId":512}
```

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Here is another fresh exchange.

[2023-04-22T21:46:37.282940+02:00]
Request to /ecr/v1/transactions:sale
```json
{"sessionId":"PP3300767-4e4dc74928","terminalId":"16253546","cashRegisterId":"POS005","amount":4200,"tipAmount":0,"currencyCode":978,"merchantReference":"[PP3300767-4e4dc74928]614/12007007/QZ …","customerTrns":"Votre commande #12007007 pour …"}
```

[2023-04-22T21:46:37.968191+02:00]
Response header (body is empty)
```json
{"content-length":["0"],"server":["uvicorn"],"x-process-time":["0.5431687831878662"],"x-viva-correlationid":["23-112-DAE62C014221"],"date":["Sat, 22 Apr 2023 19:46:37 GMT"],"connection":["keep-alive"]}
```

[2023-04-22T21:46:44.208481+02:00]
Webhook received
```json
{"Url":"https://webhook.byemisys.com/vivawallet/webhook?project=614","EventData":{"Moto":false,"BinId":50,"Ucaf":null,"Email":null,"Phone":null,"BankId":"NET_BNCT","Systemic":false,"Switching":false,"ParentId":null,"Amount":42.0,"ChannelId":"09913a34-c7d2-4e99-a3a7-550f2063d3b1","TerminalId":16253546,"MerchantId":"1b5a77ac-2017-ed11-b83e-0022489c5155","OrderCode":3112212881253546,"ProductId":null,"StatusId":"E","FullName":null,"ResellerId":null,"DualMessage":false,"InsDate":"2023-04-22T22:46:43.883","TotalFee":0.0,"CardToken":"BBA390055B6DB8819A0FA178EB815D4587362CFC","CardNumber":"487104XXXXXX3749","TipAmount":0.0,"SourceCode":"1180","SourceName":"Ticket Sur Place","Latitude":50.8,"Longitude":4.3,"CompanyName":"…","TransactionId":"3a6763c7-d2b7-4ad5-b20f-97d946fd0a40","CompanyTitle":"…","PanEntryMode":"07","ReferenceNumber":697096,"ResponseCode":"182","CurrencyCode":"978","OrderCulture":"nl-BE","MerchantTrns":"[PP3300767-4e4dc74928]614/12007007/QZ …","CustomerTrns":"Votre commande #12007007 pour …","IsManualRefund":false,"TargetPersonId":null,"TargetWalletId":null,"AcquirerApproved":false,"LoyaltyTriggered":false,"TransactionTypeId":5,"AuthorizationId":"000000","TotalInstallments":0,"CardCountryCode":"BE","CardIssuingBank":"BNP PARIBAS FORTIS NV/SA.","RedeemedAmount":0.0,"ClearanceDate":null,"CurrentInstallment":0,"Tags":[],"BillId":null,"ConnectedAccountId":null,"ResellerSourceCode":null,"ResellerSourceName":null,"ResellerCompanyName":null,"CardUniqueReference":"BBA390055B6DB8819A0FA178EB815D4587362CFC","ResellerSourceAddress":null,"CardExpirationDate":"2026-07-31T00:00:00","RetrievalReferenceNumber":"311219697096","AssignedMerchantUsers":["015716dd-7420-4c0c-8bc7-167213e60f72"],"AssignedResellerUsers":[],"CardTypeId":0,"ResponseEventId":10300,"ElectronicCommerceIndicator":null,"OrderServiceId":0,"DigitalWalletId":null},"Created":"2023-04-22T19:46:44.1653125Z","CorrelationId":"23-112-779C7159","EventTypeId":1798,"Delay":null,"MessageId":"de9cab2a-5c7a-473c-b24d-76a566fdf155","RecipientId":"1b5a77ac-2017-ed11-b83e-0022489c5155","MessageTypeId":512}
```

[2023-04-22T21:46:53.828642+02:00]
Webhook received
```json
{"Url":"https://webhook.byemisys.com/vivawallet/webhook?project=614","EventData":{"Moto":false,"BinId":50,"Ucaf":null,"Email":null,"Phone":null,"BankId":"NET_BNCT","Systemic":false,"Switching":false,"ParentId":"3a6763c7-d2b7-4ad5-b20f-97d946fd0a40","Amount":42.0,"ChannelId":"09913a34-c7d2-4e99-a3a7-550f2063d3b1","TerminalId":16253546,"MerchantId":"1b5a77ac-2017-ed11-b83e-0022489c5155","OrderCode":3112212882253546,"ProductId":null,"StatusId":"F","FullName":null,"ResellerId":null,"DualMessage":false,"InsDate":"2023-04-22T22:46:53.32","TotalFee":0.0,"CardToken":"BBA390055B6DB8819A0FA178EB815D4587362CFC","CardNumber":"487104XXXXXX3749","TipAmount":0.0,"SourceCode":"1180","SourceName":"Ticket Sur Place","Latitude":50.8,"Longitude":4.3,"CompanyName":"…","TransactionId":"8edb796c-e078-4e7a-a3f4-a321303d69ec","CompanyTitle":"…","PanEntryMode":"07","ReferenceNumber":697269,"ResponseCode":"000","CurrencyCode":"978","OrderCulture":"nl-BE","MerchantTrns":"[PP3300767-4e4dc74928]614/12007007/QZ …","CustomerTrns":"Votre commande #12007007 pour …","IsManualRefund":false,"TargetPersonId":null,"TargetWalletId":null,"AcquirerApproved":false,"LoyaltyTriggered":false,"TransactionTypeId":5,"AuthorizationId":"67E8C5","TotalInstallments":0,"CardCountryCode":"BE","CardIssuingBank":"BNP PARIBAS FORTIS NV/SA.","RedeemedAmount":0.0,"ClearanceDate":null,"CurrentInstallment":0,"Tags":[],"BillId":null,"ConnectedAccountId":null,"ResellerSourceCode":null,"ResellerSourceName":null,"ResellerCompanyName":null,"CardUniqueReference":"BBA390055B6DB8819A0FA178EB815D4587362CFC","ResellerSourceAddress":null,"CardExpirationDate":"2026-07-31T00:00:00","RetrievalReferenceNumber":"311219697269","AssignedMerchantUsers":["015716dd-7420-4c0c-8bc7-167213e60f72"],"AssignedResellerUsers":[],"CardTypeId":0,"ResponseEventId":null,"ElectronicCommerceIndicator":null,"OrderServiceId":0,"DigitalWalletId":null},"Created":"2023-04-22T19:46:53.7895946Z","CorrelationId":"23-112-779C7159","EventTypeId":1796,"Delay":null,"MessageId":"924cd947-2dc6-46b2-8a3c-d3cdefe82480","RecipientId":"1b5a77ac-2017-ed11-b83e-0022489c5155","MessageTypeId":512}
```

Let me know if you need more info.

Starting from Monday, I won't be able to collect fresh logs as the event currently testing terminal payments will be over. But I can provide a few more cases like the two I posted.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for the additional information. We will investigate this issue and we will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for waiting. I would like to inform you that all the cards when they reach the contactless limit, are asking for PIN to complete the transaction. Some card schemes record this attempt in our systems as a failed attempt. After the transaction is correctly verified from the user by entering the PIN, a new order code is generated that is connected to the initial one. 

In those cases, you will receive the failed webhook, and after the PIN is correctly entered you will receive a Transaction Payment Created Webhook, because it concerns the same payment.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Thank you for the highlight.

How do I know the failed webhook is not the last one?

Or how can I figure out the reported status may still evolve in the next 30 seconds or so?

Or how can the ECR know the payment is definitely failed and the status can be shown to the operator without undue delay?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

We will investigate your enquiries and we will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for waiting. Kindly note that all the transactions with this behavior have been made via Bancontact scheme. All transactions via Bancontact that first failed and then succeeded will have the same value (182) on the parameter "ResponseCode" in the failed webhook. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Thank you for looking into this issue.

I won't be able to test your solution for some time. There is no point in leaving this issue open until then. I close it for now.
