### ISSUE TITLE
Success webhook received before /ecr/v1/transactions:sale completes

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2374]
Hi,

Our ECR process got in trouble because the transaction success webhook was received **before** the actual eft api call completed.

Here is the request sent to initiate the terminal payment:

```
[2023-04-21T21:02:14.727592+02:00] 
Initiate transaction request /ecr/v1/transactions:sale
{"sessionId":"PP3296468-57383c3bbb","terminalId":"16253898","cashRegisterId":"POS001","amount":1100,"tipAmount":0,"currencyCode":978,"merchantReference":"[PP3296468-57383c3bbb]614/11992400/F5 …","customerTrns":"Votre commande #11992400 pour …"}
```

Here comes the transaction success webhook:

```
[2023-04-21T21:02:20.025166+02:00]
Webhook received
{"Url":"https://webhook.byemisys.com/vivawallet/webhook?project=614","EventData":{"Moto":false,"BinId":50,"Ucaf":null,"Email":null,"Phone":null,"BankId":"NET_BNCT","Systemic":false,"Switching":false,"ParentId":null,"Amount":11.0,"ChannelId":"09913a34-c7d2-4e99-a3a7-550f2063d3b1","TerminalId":16253898,"MerchantId":"1b5a77ac-2017-ed11-b83e-0022489c5155","OrderCode":3111214909253898,"ProductId":null,"StatusId":"F","FullName":null,"ResellerId":null,"DualMessage":false,"InsDate":"2023-04-21T22:02:19.72","TotalFee":0.0,"CardToken":"ED87E27194F06B8942889686F2E48D2A61A49AB0","CardNumber":"487104XXXXXX4214","TipAmount":0.0,"SourceCode":"1180","SourceName":"Ticket Sur Place","Latitude":50.8,"Longitude":4.3,"CompanyName":"…","TransactionId":"f6dfcb95-8799-4d0e-bc65-8622517c6a6c","CompanyTitle":"…","PanEntryMode":"07","ReferenceNumber":828865,"ResponseCode":"000","CurrencyCode":"978","OrderCulture":"nl-BE","MerchantTrns":"[PP3296468-57383c3bbb]614/11992400/F5 …","CustomerTrns":"Votre commande #11992400 pour …","IsManualRefund":false,"TargetPersonId":null,"TargetWalletId":null,"AcquirerApproved":false,"LoyaltyTriggered":false,"TransactionTypeId":5,"AuthorizationId":"F2818F","TotalInstallments":0,"CardCountryCode":"BE","CardIssuingBank":"BNP PARIBAS FORTIS NV/SA.","RedeemedAmount":0.0,"ClearanceDate":null,"CurrentInstallment":0,"Tags":[],"BillId":null,"ConnectedAccountId":null,"ResellerSourceCode":null,"ResellerSourceName":null,"ResellerCompanyName":null,"CardUniqueReference":"ED87E27194F06B8942889686F2E48D2A61A49AB0","ResellerSourceAddress":null,"CardExpirationDate":"2026-09-30T00:00:00","RetrievalReferenceNumber":"311119828865","AssignedMerchantUsers":["015716dd-7420-4c0c-8bc7-167213e60f72"],"AssignedResellerUsers":[],"CardTypeId":0,"ResponseEventId":null,"ElectronicCommerceIndicator":null,"OrderServiceId":0,"DigitalWalletId":null},"Created":"2023-04-21T19:02:19.9695781Z","CorrelationId":"23-111-CACD026E","EventTypeId":1796,"Delay":null,"MessageId":"5dd7561e-d8c7-4cad-bd10-a212761fe93d","RecipientId":"1b5a77ac-2017-ed11-b83e-0022489c5155","MessageTypeId":512}
```

And, finally, 16s later, the response to the api call:

```
[2023-04-21T21:02:30.917700+02:00]
Initiate terminal payment response (header only as response body is empty)
{"content-length":["0"],"server":["uvicorn"],"x-process-time":["16.113510370254517"],"x-viva-correlationid":["23-111-D59A2F1C8295"],"date":["Fri, 21 Apr 2023 19:02:30 GMT"],"connection":["keep-alive"]}}
```

The reported process time is very long. Hence, I'm pretty sure this is not a case of slow network on our side.

I'm well aware internet doesn't guarantee I'll receive the response in a timely manner but the payment taking place asynchronously while the api call is being processed makes things a lot more difficult to handle.

In this particular instance, you may have a deeper issue you might want to investigate.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you very much for contacting us. Kindly note that the issue is under investigation. We will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for waiting. Can you please clarify, is this issue happened in a specific transaction or is this happening regularly?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

There are two occurrences of long processing time during the last week.

The other one was short enough as to cause no issue (or the customer was slow to pay :slightly_smiling_face: ).

Here is the header:

```
"server":["uvicorn"],"x-process-time":["6.3796916007995605"],"x-viva-correlationid":["23-106-A0B3C36235F8"],"date":["Sun, 16 Apr 2023 16:30:09 GMT"]
```

The point is that it is hard to know what the webhook is about when the payment is not supposed to have been started yet.

Should you go along with suggestion #2371 , returning the order code or transaction id in the hope of matching the webhook would utterly fail. If the order code or transaction id is not yet available due to the long response time, it is impossible to match the payment with the webhook.

If you are unable to responds to the initiate sale request before starting the payment on the terminal there is only one solution left: return the sessionId in the webhook.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for the information. Can you please also share with us the exact time of the sale request and of the success webhook notification?

 Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

My original issue message contains all the times (based on my server's clock) up to the microsecond.

The two webhook payloads sent by your server contain the `Created` field with the time the webhook was generated on your server. The `MessageId` field should uniquely identify the webhooks in your system.

So, I'm afraid I don't understand what you are asking for :thinking:  Can you please clarify the information you need?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for the swift response. We wanted all the transactions with the delay to check if there was an issue with our systems. After our research we can't find anything wrong with our flow. The time that any of the steps appear on the system is not depending on our intervention. Most likely there was a connection delay on the network or between the servers.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Thank you for looking into this issue.

It would help to mitigate this issue if the [sessionId provided when starting the EFT API sale request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Transactions/paths/~1ecr~1v1~1transactions:sale/post) was available directly in the webhook or after querying the transaction status through the api.

Is it currently possible to obtain the `sessionId` of an EFT payment when processing a webhook payload?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys,

Thank you for waiting. At the moment, sessionId is not yet available via webhook. Currently we are reviewing your request of adding this parameter to the webhook's response. Until then, you can check the sessionId status by using [Retrieve Session ID Api request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Sessions/paths/~1ecr~1v1~1sessions~1{sessionId}/get).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport 

Thank you for your suggestion.

Actually, it goes the other way around. I must get the session ID from whatever is available in the webhook in order to match the webhook with a pending EFT transaction.

I can't afford to query the status of every pending EFT payment every time a webhook is received for an unknown payment.

I'll wait for an update of the webhook payload :slightly_smiling_face:
