### ISSUE TITLE
Recommended flow for POS payment

### ISSUE THREAD

**Issue by wbison** [VivaPayments/API#2376]
We want to use polling from a local tablet to check the status of a payment that was started with `POST transactions:sale` with our own unique `sessionId`. We will be using endpoint `GET sessions/{sessionId}`.

I assume we should continue to GET while we receive a `202` response?

Once we get a `200` we should look at the `success` field for the result of the transaction?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

Thank you for your message. Kindly note that the 202 response means that the transaction is not yet completed or failed. The sessions with 202 responses are still in progress. The success parameter in the 200 responses indicates if a transaction is completed (when the value of success parameter is true) or failed (when the value of success parameter is false).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by wbison** [comment]
> Kindly note that the 202 response means that the transaction is not yet completed or failed.

202 can also mean failed? Isn't that weird?

Is this the correct polling pseudocode:

```
do {
    GET session
} while(httpstatus == 202)

if (httpstatus == 200 AND session.success == true) {
    // money transferred!
} else {
    // handle error
}
```

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

Thank you for the prompt response. The 202 response indicates that the request has been processed to the POS but has neither failed nor completed yet. The correct response that should be checked is 200 and not 202. For example, you should repeat the GET until you receive a 200 response. After the successful response, the value of the "success" parameter should be checked. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by wbison** [comment]
> For example, you should repeat the GET until you receive a 200 response. 

Isn't that the same as saying that I should continue to GET while I receive a 202? (ignoring errors).
Oh well.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

Sorry for the late response. 202 response doesn't indicate a processed payment. The transactions with 202 responses are still in progress. The 200 responses can be either failed or completed transactions. The 200 responses indicate that the API requests are correct. The success parameter in the 200 responses indicates if a transaction is completed (when the value of success parameter is true) or failed (when the value of success parameter is false).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by wbison** [comment]
> 202 response doesn't indicate a processed payment.

That's why I assume we need to continue to GET for as long as we get a 202.

I don't think you are actually reading any of my messages. Please just close.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

Sorry for the inconvenience. You should continue to GET if you get 202 as a response. 

Kind regards,
Viva Wallet E-commerce Support Team
