### ISSUE TITLE
Standard Checkout Credentials From Woocommerce aren't recognized

### ISSUE THREAD

**Issue by alexandre-rey** [VivaPayments/API#2379]
Hi everyone,

We have a woocommerce online shop set up with the latest Viva Wallet for WooCommerce plugin. Autoupdate is enabled and the current version is 1.4.1 with Woocommerce 7.6.1.

Everything was working fine until this morning when our customers started to see this message :
Viva Wallet: Your LIVE credentials are NOT valid. Please check your credentials!

We double checked the credentials : they are ok
We reseted several times the secret and tried with the new one : not working
We deleted and downloaded the plugin from the official site : not working 

We can't see where we made a mistake, and nothing changed on our side when the link with the API broke.

I've seen a similar issue on this repo but it was on an old version of the plugin. The customer live chat doesn't helped us as they can not see were a problem could be.

Have you ever seen something similar ?

Edit : We tried to rollback woocommerce to 7.6.0 as autoupadte updated it to 7.6.1 yesterday, its still not working

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alexandre-rey,

Thank you for your message. Can you please send us the MID of your account? You can send it here or via email at support@vivawallet.com mentioning github code: 2379 in the title. Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alexandre-rey,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by alexandre-rey** [comment]
Hello @VivaWalletCustomerSupport,

Thank you for your attention and for your response, we are looking into this issue. You should receive an email from us shortly.

Thank you!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alexandre-rey,

Thank you for your prompt response. As soon as we have any updates, we will inform you.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alexandre-rey,

Thank you for your e-mail. We would like to advise you to navigate to your website dashboard to our plugin's settings and save the settings. Afterwards please follow the instructions of the link below and send us the logs of our plugin with today's date.

https://help.vivawallet.com/en/articles/5126216-where-i-can-find-the-logs-for-the-viva-wallet-for-woocommerce-plugin

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by alexandre-rey** [comment]
Hello,

You'll find the logs in the log file attached to this message. You'll see in this file my attemps to make the auth working, even on the demo accounts, to try to find where the problem is.

[woocommerce-vivawallet-logs.log](https://github.com/VivaPayments/API/files/11395453/woocommerce-vivawallet-logs.log)

Thanks for your help,


Kind regards

Alexandre REY

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alexandre-rey,

Thank you for the swift response. We would like to advise you to download our plugin's latest version from the following link:

https://woocommerce.com/products/viva-wallet-for-woocommerce/

If the issue persists, please inform us.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by alexandre-rey** [comment]
Hello,

Starting from line 622, you can see that we use the 1.4.10 version which is the latest from your website. Requests with the 1.4.1 were one of my attemps to make things work by rollbacking to an older version that we know was working.

Updating to the latest version was one of the first suggestion of the live chat support but it didn't change the result.

Kind regards

Alexandre REY

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alexandre-rey,

Thank you for the information. We are investigating the reference numbers to identify the reasons for the rejection. We will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alexandre-rey,

Thank you for waiting. We would like to advise you to navigate to your website dashboard to our plugin's settings and save the settings. Afterwards please follow the instructions of the link below and send us the logs of our plugin with today's date.

https://help.vivawallet.com/en/articles/5126216-where-i-can-find-the-logs-for-the-viva-wallet-for-woocommerce-plugin

We would like an error with today's date to investigate further the issue. Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alexandre-rey,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alexandre-rey,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
