### ISSUE TITLE
404 σε redirect viva payments απο cs-cart 

### ISSUE THREAD

**Issue by harvesterr** [VivaPayments/API#238]
καλησπερα
εχω ενα θεμα
εγκατεστησα ενα plugin για το viva payments se cs cart
αλλα οταν τελειωνει την παραγγελία ο πελάτης με πεταει σε 404! 
κ η χρεωση στον πελατη γινεται κανονικα
κ επίσης η παραγγελία στο πανελ παει στις ατελης παραγγελίες που ειναι κρυφες κ δε φαινονται!

γιατι γινεται αυτο?
επισης επειδη εκανα νεα εγκατασταση σε ssl μπηκα μεσα στο πανελ της viva payments K αλλαξα το λινκ απο  http σε https
κ παλι τα ιδια
(εκτος αν θελει καποεις ωρες να ενεργοποιηθει)
μπορειτε να με βοηθησετε αμεσα?!!!!!
ευχαριστώ
www.epipla24.gr

**Comment by harvesterr** [comment]
καλησπερα
εχω το ιδιο προβλημα ξανα
οπου με πεταει σε 404 με εγκατάσταση των plugins που εχετε εδω!

αλλα δε βλεπω να απαντατε κ εχω προβλημα
τι πρεπειθ να κανω?
παρα,καλω άμεσα γτ γινονται παραγγελίες!

**Comment by harvesterr** [comment]
ειναι καποιος εδω?

**Comment by dmihos** [comment]
Χρησιμοποιήσατε το plugin για cscart ή cscart4;

**Comment by harvesterr** [comment]
cs cart 4

**Comment by harvesterr** [comment]
κ επισης επειδη χρησιμοποιω ssl εκανα κ μια αλλαγη στο vivawallet.tpl απο http σε https.
αλλα κ παλι τπτ

**Comment by harvesterr** [comment]
ειστε εδω??

**Comment by harvesterr** [comment]
εχω σοβαρο θεμα
μπορει καποιος να βοηθησει?

**Comment by harvesterr** [comment]
τελικα που θα μιλησουμε
εδω η στο αλλο???

**Comment by harvesterr** [comment]
μπορουμε να το λυσουμε τελικα?
παιζει?
η απλα θα μεταφερουμε τα αιτηματα??

**Comment by harvesterr** [comment]
η εξυπηρετηση εδω ειναι σχετικη με τη viva?
επειδη εκει δεν υπαρχει κατι αμεσο σε τετοιοες περιπτωσεις κ με παρεπεμψαν εδω

δλδ να εχει καποιο σοβαρο καταστημα προβλημα κ την πατησε κανονικα ετσι?????
δεν υπαρχει ιδιαιτερη σωτηρια με το συγκεκριμενο plugin υποθετω!!!

οποτε θελουμε κ αν θελουμε απανταμε για να λυσουμε ενα προβλημα καποιας εταιρειας, οπου δεν μας νοιαζει αν αυτη η εταιρεία χανει λεφτα η οχι ετσι;!

**Comment by harvesterr** [comment]
το ελυσα μονος μου

support για κλαματα!!!

καλη συνεχεια!
μακαρι να μην τυχει καποιος πελατης να σας εχει αναγκη!
την πατησε!!

**Comment by dmihos** [comment]
Δε γνωρίζω για ποιο λόγο υποθέτετε ότι δεν ασχολήθηκε κανείς με το θέμα σας, μετά από τόσα follow ups.
Το ότι δεν απαντήθηκε στο χρόνο που θα θέλατε, είναι κατανοητό, αλλά κάνουμε ότι μπορούμε.
Αν θέλετε, μοιραστείτε τη λύση που βρήκατε.

Απολογούμαι μόνο για το αρχικό ερώτημα του Φεβρουαρίου, το οποίο δεν απαντήθηκε ποτέ.
Καλή συνέχεια.

**Comment by VivaWalletSupport** [comment]
When testing a fail payment I get redirected to following wrong URL:
https://epipla24.gr/index.php?dispatch=payment_notification.fail&payment=hellaspay

It means that in the payment source a wrong fail URL is used (index.php?dispatch=payment_notification.fail&payment=hellaspay), no clue from where the idea to specify vivapayments_success.php for success source URL came from (maybe a leftover from when he bought the module from a 3rd party before).

I would advise to remove module and every file he has installed for this payment option, delete every database record that has been inserted for the payment option and to start from the beginning with the latest GIT version following the instructions to the letter.

Source Fail URL: index.php?dispatch=payment_notification.fail&payment=vivawallet
Source Success URL: index.php?dispatch=payment_notification.success&payment=vivawallet

**Comment by kostGX** [comment]
Closing as issue over 1 year old.
