### ISSUE TITLE
Unable to verify webhook - Error 502

### ISSUE THREAD

**Issue by george-dragnea** [VivaPayments/API#2380]
I receive Error 502 when I try to verify an URL webhook, on both the demo account, also in a production environment.

The demo account:
Webhook URL: https://api-staging.boosteat.com/public/integrations/payment-provider/vivawallet/webhook/aWxqikSTIvId7szPExp1JoVGxWQaR82sCfAHA8fwsR2Ez3TDDJc013XsK1C7VsUmUtda8yENj7mXhQJaZfFX8MJM3ok9qz7veVgB5PWi2v3UgXT0e3Lq6kNq3j0RApjI
Merchant ID: 74ad0436-080c-423a-ab9a-dbe96fbe03ed

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @george-dragnea,

Thank you for your message. Can you please send us a screenshot of the error? 

Also, make sure your server is using TLS 1.2 and you have whitelisted the following IP addresses. 
https://developer.vivawallet.com/webhooks-for-payments/#whitelist-the-viva-wallet-addresses

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by george-dragnea** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/1846538/235636277-2908afe5-fb8e-483f-ae07-fdf074831686.png">

I use Cloudflare, so I think it supports TLS 1.2, and even 1.3.

**Comment by george-dragnea** [comment]
If I run:
`curl -I -v --tlsv1.2 --tls-max 1.2 https://api-staging.boosteat.com/`

I get:
```
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS handshake, Server finished (14):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
```
So it supports TLS 1.2

**Comment by VivaWalletCustomerSupport** [comment]
Hello @george-dragnea,

Thank you for your swift response.  Kindly note that we send this request using only TLS 1.2 so your server configuration needs to match that. If your server is using a newer version (1.3), it may not be compatible.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by george-dragnea** [comment]
All the TLS versions are supported.
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/1846538/235653475-26456b10-efdf-444d-b0cb-bba5b06e06d1.png">

I have disabled the TLS version 1.3, but I still can add the webhook. So, I don't think this is a TLS problem if only you have tried my URL and received a TLS error.

Maybe because the server is behind Cloudflare? but I don't see why that should be a problem, many websites use Cloudflare.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @george-dragnea,

Thank you for the additional information. We cannot find any restriction to your account from our side.
We would like to suggest checking your server settings once again. Also, please ensure that in your server is not applied any restriction rule. Finally, to eliminate all possible aspects, we would recommend contacting your provider as well.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by george-dragnea** [comment]
I have managed to fix it, Cloudflare has been blocking your IPs.

You should talk with Cloudflare, maybe they have a program where you as a payment provider can join to have your IPs in their whitelist.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @george-dragnea,

Thank you for your response. It is especially important for us to receive feedback as in this way we improve our services. This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
