### ISSUE TITLE
Webhook reached, no data, customer not redirected to store.

### ISSUE THREAD

**Issue by AdamMiltonBarker** [VivaPayments/API#2381]
Custom PHP intergation. App in test mode. Webhook is verified, success and error return URLs. Webhook is reached but $_POST is empty. After payment customer not redirected back to shop.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AdamMiltonBarker,

Thank you for your message. Can you please send us the domain of your website? Also, please send us the[ Create Payment Order API request](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post) you are making. (full code) Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AdamMiltonBarker** [comment]
Hi it is proprietary code so unfortunately would not be able to no. The code does exactly as your documentation says. We receive the POST from your server but it is empty. Also the redirect is not on our side so nothing we can do to change that, the return URLs are set up in the test account. This is delayed delivery today so can you have a look at your services please.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AdamMiltonBarker,

Thank you for the information. To proceed with our investigation, we will need the domain of your website and the URL of your webhook. Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AdamMiltonBarker** [comment]
@VivaWalletCustomerSupport  please provide an email that I can send it to you privately on.

**Comment by AdamMiltonBarker** [comment]
This is where it stays

![image](https://user-images.githubusercontent.com/6291410/236335814-4aaa48cb-3076-4497-8fad-5c6aefacfd9a.png)

In this test I received one piece of data:

```
Array
(
    [EventTypeId] => 1796
)
```

Usually, it is completely empty. 

This is now the only code in the webhook:

```
    if($_SERVER['REQUEST_METHOD'] === 'POST'){
        $main->writeFile("payment-post.txt", $_POST);
        http_response_code(200);
    } else {
        $verifiy = $VivaPay->verifyWebhook();
        $main->writeFile("payment-get.txt", $_GET);
        print_r(json_encode($verifiy));
    }
```

The demo merchant ID in use:  3023cf15-8e1d-4e6c-b68a-16e7b496e988 
The demo iban GB47VPAY04136019892338

That should be enough for you to identify the test account

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AdamMiltonBarker,

Thank you for the additional information. You can use the support@vivawallet.com email. 
We will investigate your enquiry and we will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AdamMiltonBarker** [comment]
Thanks will do so now.

**Comment by AdamMiltonBarker** [comment]
@VivaWalletCustomerSupport  we are awaiting your reply, email sent yesterday. Would appreciate a resolution to this is has delayed delivery of a product to our client.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AdamMiltonBarker, 

Thank you for your message. We received your email. We will investigate your query further and let you know as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AdamMiltonBarker,

Thank you for waiting. Kindly note that on the [Create Payment order API request](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post) the parameter sourceCode should have as value the 4-digit code of the source that the website is using. Otherwise, the transactions will be completed by the default source. The transactions that are completed via a specific source will use the success & failure URLs of the source as well.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AdamMiltonBarker,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AdamMiltonBarker,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AdamMiltonBarker** [comment]
This still did not solve the issue, post still returns only the following:

Array
(
    [EventTypeId] => 1796
)


The return URL is set and it sends to a completely different page?

**Comment by AdamMiltonBarker** [comment]
I worked out what is happening with the return URL, the parameter for ORDER set in the settings is 'order' the page requires this or cannot retrieve the order so it redirects them to the orders home page. You system is:

- Not sending any post data to the webhook
- Not returning the order ID after payment.

**Comment by AdamMiltonBarker** [comment]
We receive this to the success page (I worked out what was happening with that), Event ID is empty:

Array ( [txid] => 9e9e7373-4648-4ca4-b447-bf27f48d237f [order] => 8264364285048981 [lang] => en-GB [eventId] => 0 [eci] => 1 )

We still receive nothing to the webhook.

**Comment by AdamMiltonBarker** [comment]
Hi, your advice worked to some degree, it now redirects back to the success page, however, eventID is empty, and still do not receive any post data about the transaction to the webhook. 

This is what is received at the success page:

Array ( [txid] => 9e9e7373-4648-4ca4-b447-bf27f48d237f [order] => 8264364285048981 [lang] => en-GB [eventId] => 0 [eci] => 1 )

This is what is received at the webhook:

Array
(
    [EventTypeId] => 1796
)

This is now increasingly frustrating, what is wrong with your API?

**Comment by AdamMiltonBarker** [comment]
@VivaWalletCustomerSupport 

Hi, your advice worked to some degree, it now redirects back to the success page, however, eventID is empty, and still do not receive any post data about the transaction to the webhook.

This is what is received at the success page:

Array ( [txid] => 9e9e7373-4648-4ca4-b447-bf27f48d237f [order] => 8264364285048981 [lang] => en-GB [eventId] => 0 [eci] => 1 )

This is what is received at the webhook:

Array
(
[EventTypeId] => 1796
)

This is now increasingly frustrating, what is wrong with your API? The dummy money is shown in the test account so we are obviously completing the transactions correctly, 

Please can you get the solution to us as this is now holding up 2 websites.

**Comment by AdamMiltonBarker** [comment]
@VivaWalletCustomerSupport  Absolutely insane support, you suggest the problem is how the response is being printed?? The writefile function is a simple function that takes the input and writes it to file. There is no problem with this simple function , the probelm is your API not returning a correct response.

    ```
public function writeFile($file,$data)
    {
        $fps = fopen($file, 'w');
        fwrite($fps, print_r($data, TRUE));
        fclose($fps);
    }
```
The code that trggers write file:

   ```
 if($_SERVER['REQUEST_METHOD'] === 'POST'){
        $main->writeFile("payment-post.txt", $_POST);
        http_response_code(200);
    } else {
        $verifiy = $VivaPay->verifyWebhook();
        $main->writeFile("payment-get.txt", $_GET);
        print_r(json_encode($verifiy));
    }
```


IE
        `$main->writeFile("payment-post.txt", $_POST);`

We are simply writing what we receive from your API to file. Your API is ONLY returning:

```
Array
(
    [EventTypeId] => 1796
)
```

Why will you not understand this? Months this issue has gone and you are just shifting blame rather than fix it.

**Comment by AdamMiltonBarker** [comment]
A word of warning to anyone considering using Viva, these guys are cowboys that do not understand the basics of programming. Rather than review logs and provide an accurate response to the issue, they will blame everyone else but themselves. Avoid this company.
