### ISSUE TITLE
WooCommerce saying "Viva Wallet: Your LIVE credentials are NOT valid. Please check your credentials!"

### ISSUE THREAD

**Issue by SwissPeak** [VivaPayments/API#2382]
I've recently changed the Viva Wallet we use on our WooCommerce site, and I'm getting the following error message - "Viva Wallet: Your LIVE credentials are NOT valid. Please check your credentials!"
I'm 100% certain I've entered the Live Client ID and Live Client Secret exactly as entered in my Viva Wallet account, so I can see where the problem is arising from?
Any help would be appreciated.

**Comment by SwissPeak** [comment]
I'm also getting this error on my e-comm site when trying to checkout - "Viva Wallet: Source Code is not set. Please check documentation and fill in your Viva Wallet gateway settings."

**Comment by SwissPeak** [comment]
I've had Viva Wallet working perfectly fine with our previous Viva Wallet account, so I don't know why this would be happening.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SwissPeak,

Thank you for the information. To proceed with our investigation, we will need the domain of your website and the Merchant ID of your account. You can send them here or at support@vivawallet.com please use github code: 2382 in the title.
Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by SwissPeak** [comment]
www.swisspeakcbd.com

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SwissPeak,

Thank you for your swift response. Make sure you are using the correct [credentials](https://developer.vivawallet.com/plugins/woocommerce-standard-checkout/), you can generate a new Client secret as well.  
We will also need the latest Logs. To export them follow the steps [here](https://help.vivawallet.com/en/articles/5126216-where-i-can-find-the-logs-for-the-viva-wallet-for-woocommerce-plugin). 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by SwissPeak** [comment]
I’m 100% using the correct credentials. And I generated a new secret key.
Logs are attached.

Best,

From: VivaWalletCustomerSupport ***@***.***>
Date: Friday, 5 May 2023 at 15:50
To: VivaPayments/API ***@***.***>
Cc: SwissPeak ***@***.***>, Mention ***@***.***>
Subject: Re: [VivaPayments/API] WooCommerce saying "Viva Wallet: Your LIVE credentials are NOT valid. Please check your credentials!" (Issue #2382)

Hello @SwissPeak<https://github.com/SwissPeak>,

Thank you for your swift response. Make sure you are using the correct credentials<https://developer.vivawallet.com/plugins/woocommerce-standard-checkout/>, you can generate a new Client secret as well.
We will also need the latest Logs. To export them follow the steps here<https://help.vivawallet.com/en/articles/5126216-where-i-can-find-the-logs-for-the-viva-wallet-for-woocommerce-plugin>.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SwissPeak,

Thank you for your message. This is not a technical issue. There is a pending issue on your Source/Account. For your best service I would recommend contacting our Live Chat support to further investigate the issue.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SwissPeak,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SwissPeak,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
