### ISSUE TITLE
ISV: Could not validate credentials on devices:search

### ISSUE THREAD

**Issue by wbison** [VivaPayments/API#2385]
I'm getting `Could not validate credentials` when trying to `devices-search`:

## connect/token
```
curl --location 'https://demo-accounts.vivapayments.com/connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=i8npk9dvlwa6u2jt5t79bc9b4qnq2qfzuikvvhrx8f552.apps.vivapayments.com' \
--data-urlencode 'client_secret=xxxx' \
--data-urlencode 'scope=urn:viva:payments:ecr:api'
```

 this gets me access_token which is then used in:

### devices-search
```
curl --location 'https://demo-api.vivapayments.com/ecr/isv/v1/devices:search' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer [access_token from above]' \
--data '{
    "merchantId": "3e7d240b-de6e-4e1f-aabb-7f5fc170ece4",
    "statusId": 1
}'
```

which results in:

```
401 - "Could not validate credentials"
```

I also tried Basic Auth for `connect/token` like so:
```
curl --location 'https://demo-accounts.vivapayments.com/connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic [encoded client_id client_secret' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=urn:viva:payments:ecr:api'
```

This also results in a token but that one is also considered invalid.

The ISV credentials are from this screen:

<img width="1021" alt="isv credentials" src="https://github.com/VivaPayments/API/assets/309892/49641636-d008-4004-bc94-26fc1912f48b">

The merchantId from this screen:

<img width="892" alt="merchant-id" src="https://github.com/VivaPayments/API/assets/309892/bde057b8-05c7-4fc0-af74-bfdb4488eaf0">

What am I doing wrong? (is it ok to include the demo client_secret so you have all the reproducable info?)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

Thank you for your message. Can you please provide us with an access token from your ISV credentials so we can perform some technical checks? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by wbison** [comment]
credentials with method 1

eyJhbGciOiJSUzI1NiIsImtpZCI6IjBEOEZCOEQ2RURFQ0Y1Qzk3RUY1MjdDMDYxNkJCMjMzM0FCNjVGOUZSUzI1NiIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJodHRwczovL2RlbW8tYWNjb3VudHMudml2YXBheW1lbnRzLmNvbSIsIm5iZiI6MTY4Mzg4MjU4OSwiaWF0IjoxNjgzODgyNTg5LCJleHAiOjE2ODM4ODYxODksImF1ZCI6WyJlY3JfYXBpIiwiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIl0sInNjb3BlIjpbInVybjp2aXZhOnBheW1lbnRzOmVjcjphcGkiXSwiY2xpZW50X2lkIjoiaThucGs5ZHZsd2E2dTJqdDV0NzliYzliNHFucTJxZnp1aWt2dmhyeDhmNTUyLmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiI5NEREODY2MS1GQTM3LTQxRTUtOEE5MC1CMzQyRTYyQjU4NjQifQ.B1ajnpY7vVVeC5VmsJh0wXNWS-ln77KOzEO3sbPyVvSEWE6xG0mkBGdlEMcoCSpi8uYlwMhsAmU7--pUPXs5FXtp0hbyKYfDvHMrqoLBT1jmoqZj2iGAPZwKj7UCNsOjefzGI8lNVmHiaag_8qQU38uDvkVzesKVcRN6XsIQlyiO0ClSEiB9Gku2TxtNbdjE29OfalglEHr6gu9fT6VS8a88I-SIKZWl8OXvvFPXqKvUXC82WLLiZAQS8dwGkZiU3DzB7wF5Y65TsMkLZnokCFImu-sMvHqtK0mqKBs1lQC3CdsnsoGwo4VNi5mrX0Civpz25eihZEvblqx5yTDqGw

```
curl --location 'https://demo-accounts.vivapayments.com/connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=i8npk9dvlwa6u2jt5t79bc9b4qnq2qfzuikvvhrx8f552.apps.vivapayments.com' \
--data-urlencode 'client_secret=xxxx' \
--data-urlencode 'scope=urn:viva:payments:ecr:api'
```

========================

credentials as Basic Auth

eyJhbGciOiJSUzI1NiIsImtpZCI6IjBEOEZCOEQ2RURFQ0Y1Qzk3RUY1MjdDMDYxNkJCMjMzM0FCNjVGOUZSUzI1NiIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJodHRwczovL2RlbW8tYWNjb3VudHMudml2YXBheW1lbnRzLmNvbSIsIm5iZiI6MTY4Mzg4MjYyMSwiaWF0IjoxNjgzODgyNjIxLCJleHAiOjE2ODM4ODYyMjEsImF1ZCI6WyJlY3JfYXBpIiwiaHR0cHM6Ly9kZW1vLWFjY291bnRzLnZpdmFwYXltZW50cy5jb20vcmVzb3VyY2VzIl0sInNjb3BlIjpbInVybjp2aXZhOnBheW1lbnRzOmVjcjphcGkiXSwiY2xpZW50X2lkIjoiaThucGs5ZHZsd2E2dTJqdDV0NzliYzliNHFucTJxZnp1aWt2dmhyeDhmNTUyLmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiI5NEREODY2MS1GQTM3LTQxRTUtOEE5MC1CMzQyRTYyQjU4NjQifQ.KOBJnpmqhYoiym1G5AOJ51t7gYKzy-gPffuPckEpxSkS0Ns4tKnqjLI_g3zdBIH_I0vKRptuJh6HB5XjCKGdFRdskio4_qCfe4PkWwIkUffSM9uGpD5ilpeoRUbkisiJbwLzOlSgBHJe03w589POnGyhimkTtl3AlaOjEG-Iner2G3bvLFC_k1kMZoKwWg10-xDkSAJsCzLinAI5cwrwoYxvXoCXpK5Dk_OvoUuh642t_VG_jlBIwVn9N0bPKhG--vKIYMCydRcedOytLM_sFuZmZWlXmXKh5qLiiKjXBIOXP7Zx72Jhfhx54TJeuNp2hrvfggQVV9FfxfM9hZ1ixA

```
curl --location 'https://demo-accounts.vivapayments.com/connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Authorization: Basic xxxxx' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=urn:viva:payments:ecr:api'
```

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

Thank you for the information. Can you please delete the --data-urlencode 'scope=urn:viva:payments:ecr:api' from your request and try again to generate an access token? If the issue persists, please send us the "scope" parameter the access token contains and the Client Secret you are using. Please send the Client Secret by e-mail to support@vivawallet.com and in subject please add the GitHub case number. After our tests we will inform you so you can generate a new client secret.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by wbison** [comment]
Without  scope i get this:

"access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjBEOEZCOEQ2RURFQ0Y1Qzk3RUY1MjdDMDYxNkJCMjMzM0FCNjVGOUZSUzI1NiIsIng1dCI6IkRZLTQxdTNzOWNsLTlTZkFZV3V5TXpxMlg1OCIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJodHRwczovL2RlbW8tYWNjb3VudHMudml2YXBheW1lbnRzLmNvbSIsIm5iZiI6MTY4Mzg4MzcyNywiaWF0IjoxNjgzODgzNzI3LCJleHAiOjE2ODM4ODczMjcsImF1ZCI6WyJjb3JlX2FwaSIsImVjcl9hcGkiLCJodHRwczovL2RlbW8tYWNjb3VudHMudml2YXBheW1lbnRzLmNvbS9yZXNvdXJjZXMiXSwic2NvcGUiOlsidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6aXN2IiwidXJuOnZpdmE6cGF5bWVudHM6Y29yZTphcGk6cmVkaXJlY3RjaGVja291dCIsInVybjp2aXZhOnBheW1lbnRzOmVjcjphcGkiXSwiY2xpZW50X2lkIjoiaThucGs5ZHZsd2E2dTJqdDV0NzliYzliNHFucTJxZnp1aWt2dmhyeDhmNTUyLmFwcHMudml2YXBheW1lbnRzLmNvbSIsInVybjp2aXZhOnBheW1lbnRzOmNsaWVudF9wZXJzb25faWQiOiI5NEREODY2MS1GQTM3LTQxRTUtOEE5MC1CMzQyRTYyQjU4NjQifQ.gK955o-Itme3jDpMcjEquiN2JbQFQaAv-mps9oav9NpqVg_OXoKefdSNM1OiCNYDepRqCfcb95m6rxPjT9PPIasQoqP1NJJ0Hqib6SS_3U1IDgot_qE8QRw2x_TPPc1hLJbUBkUA-2MBsfNs47HO_cM-AGc6Imv8l0RU3yg79b6por890Ifx81DET_cmLJIxqeuwI9crGSQqNtrc0ctuUQBqyjMubs4d8450eF0NOlJiXfRMq15QnRuW4jwkHuV4klqmn-42jklF_HvbLv638bIFMBXMeOr6SuueZ-g5BTJ1yY0oKS3oINCdjtLOc33tsBTqzwRpkP0OGMWho2SrjA",
    "expires_in": 3600,
    "token_type": "Bearer",
    "scope": "urn:viva:payments:core:api:isv urn:viva:payments:core:api:redirectcheckout urn:viva:payments:ecr:api"
}

and with that token `devices-search` returns `200` and an empty array.

Is this the solution?
How about the `transaction-sale` ? What scope is required for the token for that endpoint?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

Thank you for the swift response. The 200 response indicates that the request is successful. If the merchant's account does not have any POS device attached, it is normal to return an empty array. 

The "scope": "urn:viva:payments:core:api:isv urn:viva:payments:core:api:redirectcheckout urn:viva:payments:ecr:api" is the scope of [Search POS Device API request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Get-Device-Status/paths/~1ecr~1isv~1v1~1devices:search/post) and [Initiate a Sales API Request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Make-Transactions/paths/~1ecr~1isv~1v1~1transactions:sale/post) as well.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by wbison** [comment]
I did read your response, thanks.

What confuses me is that you first ask me to "try" to generate an access token without a scope. 

When this apparently works you tell me that the scope is actually `urn:viva:payments:core:api:isv urn:viva:payments:core:api:redirectcheckout urn:viva:payments:ecr:api`

And all that while the docs specify that the scope should be `urn:viva:payments:ecr:api`.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @wbison,

Thank you for the prompt response. Kindly note that the scope is generated in the access token API request depending on the credentials used in the request. If the POS credentials are used the above scope will be generated. If the Smart Checkout credentials have been used the scope for Smart Checkout will be generated.

The scope is not defined on the body of the request, but it depends on the credentials used for authentication.

Kind regards,
Viva Wallet E-commerce Support Team
