### ISSUE TITLE
EventId 2111

### ISSUE THREAD

**Issue by Rikelek1** [VivaPayments/API#2386]
Hi,

We're using your smart checkout integration and have been investigating some issues reported by our users. 

After a customer makes a payment and is redirected back to our site, the first thing we do is log the fact they've just made a payment, making note of the transaction id (t), order id (s), event id (eventId) and eci code (eci) that are returned in the query parameters.

When checking these logs, I've noticed that we've had some payments that appear to have come back to our site with the following values:
- eventId: 2111
- t: null/empty
- s: {expected value}
- eci: null/empty

I took a look at the list of event id codes you have [here](https://developer.vivawallet.com/integration-reference/response-codes/#event-id-codes) but noticed that 2111 doesn't seem to be on there.

Can you please clarify what event id 2111 means?

EDIT:

I've now noticed some logs with an eventId of 1. Can I also please ask what event id 1 means?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Rikelek1,

Thank you for your message. We are currently investigating your request. We will inform you as soon as we have any update.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Rikelek1,

Thank you for waiting. In terms of official restrictions received by the UK Ministry regarding gambling transactions, we as Viva Wallet must block all gaming authorizations accepted by Viva Wallet merchants that were performed with UK Credit Cards. This restriction is printed with event ID 2111.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Rikelek1** [comment]
I see, that clears things up. Thank you for clarifying!
