### ISSUE TITLE
Status 403 on demo - /nativecheckout/v2/chargetokens

### ISSUE THREAD

**Issue by chameleonxxl** [VivaPayments/API#2387]
Hello,

I have problems with requesting a charge token from my Viva Wallet demo account.

My Merchant Id: 0727efb5-1be6-4dea-b355-a9fbe3029171

I'm using the following setting as paymentsource:
[https://i.ibb.co/MgZRDD1/viva-wallet-setting.png](url)

When I request a access_token via https://demo-accounts.vivapayments.com/connect/token

I get the following scope returned:
`urn:viva:payments:core:api:acquiring urn:viva:payments:core:api:acquiring:cardtokenization urn:viva:payments:core:api:redirectcheckout`

Do I not need `urn:viva:payments:core:api:nativecheckoutv2` ?

When I make a request with Postman to obtain a charge token with the following postparameters:
`{
    "Amount": 1000,
    "Cvc": "111",
    "Number": "4147463011110133",
    "Holdername": "John Doe",
    "ExpirationYear": 2030,
    "ExpirationMonth": 10,
    "SessionRedirectUrl": "[Redirect URL]"
}`

I also getting a HTTP Status Code of 403 returned.

Is there something wrong with my Viva wallet account?
Or does charge token request not work with a demo account?

Any help would be appriciated

**Comment by VivaWalletCustomerSupport** [comment]
Hello @chameleonxxl,

Thank you for your message. We would like to inform you that our native checkout is no longer supported for new integration. We would like to advise you to integrate our [Smart Checkout](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/) instead.

Kind regards,
Viva Wallet E-commerce Support Team
