### ISSUE TITLE
Unable to create webhook in demo environment

### ISSUE THREAD

**Issue by SamuelMichelRiad** [VivaPayments/API#2389]
Hello support,

We are unable to create a webhook from the control panel in the demo environment. See screenshot below. Account is registered to phone number (+45) 25250900. We are able to verify the webhook, see second screenshot.

Thanks

-----

The request (from dev tools) is as follows:
URL: https://demo.vivapayments.com/selfcare/en/security/updatewebhook
Parameters:
IsNew: True
Id: 0
Url: https://test.lovingloyalty.com/api/v1/payments/vivawallet/transaction-created/54292
IsActive: true
IsActive: false
EventTypeId: 1796
X-Requested-With: XMLHttpRequest

![image](https://github.com/VivaPayments/API/assets/9570587/1c95e90d-c790-47b0-8451-3d3c30e9ae73)

![image](https://github.com/VivaPayments/API/assets/9570587/3209cf4c-5049-4ada-8142-88f14a4e366b)

**Comment by eliassantannaramos** [comment]
Support, i'm facing the same issue as well.
My postman request in getting everything right for a Get and a Post.
The veryfication process if going fine but I cannot save it.

![image](https://github.com/VivaPayments/API/assets/86597142/1c7f4689-dc93-4438-b130-ac1a290cf95b)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad, @eliassantannaramos,

Thank you for your messages. At the moment we are investigating the issue. @eliassantannaramos, can you please share with us the endpoint URL from the webhook you are trying to implement? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by eliassantannaramos** [comment]
Hello viva wallet,

There are any email that I can send you my webhook link?

Regards,
Elias Ramos

**Comment by VivaWalletCustomerSupport** [comment]
Hello @eliassantannaramos,

Thank you for the swift response. You can send it to the following e-mail:

support@vivawallet.com

Please add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by eliassantannaramos** [comment]
Just did.

Thanks for your support and looking forward for your answer.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @eliassantannaramos,

Thank you for the e-mail. We are currently investigating the issue. We will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by eliassantannaramos** [comment]
Working!! Thanks guys!

![image](https://github.com/VivaPayments/API/assets/86597142/33275091-c49c-4f5d-bb5a-5c3cec4b6ff8)

**Comment by SamuelMichelRiad** [comment]
Also confirmed from my side

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad, @eliassantannaramos 

Thank you for the feedback. We would like to inform you that we identified the issue, and it has been resolved.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad, @eliassantannaramos

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by eliassantannaramos** [comment]
Thanks @VivaWalletCustomerSupport .. everything is working fine! Sorry for the long delay to reply!
