### ISSUE TITLE
Διασύνδεση του eshop με την Viva Payments

### ISSUE THREAD

**Issue by dimline1** [VivaPayments/API#239]
Οι πελάτες δεν μπορούν να ολοκληρώσουν τις αγορές τους μέσω Viva , ενώ πρίν 2 μήνες περίπου , μπορούσαν . Τι έχει αλλάξει ;

**Comment by dimline1** [comment]
αφορά το www.autotecparts.gr

Στο άλλο eshop www.autotec.gr δεν υπάρχει μέχρι τώρα κανένα θέμα μέσω viva

**Comment by dmihos** [comment]
Καλημέρα

Υπάρχει μια πηγή συναλλαγών με SourceCode **5367** που αντιστοιχεί σε urls με domain **autotec.gr**.
Για το **autotecparts.gr**, όμως, δεν υπάρχει κάποια πηγή. Η πηγή **Default** έχει τα default urls (με domain www.vivapayments.com)

Ευχαριστούμε για την επικοινωνία

**Comment by dimline1** [comment]
Καλημέρα 

Στο site  https://www.autotecparts.gr/   οι πελάτες δεν μπορούν να ολοκληρώσουν πληρωμή μέσω viva .

Που ακριβώς οφείλετε το πρόβλημα γιατί δεν ξέρω τι πρέπει να διορθωθεί.
Εκτός κι αν θα πρέπει να έρθετε σε άμεση επαφή με τον διαχειριστή του eshop .

**Comment by dmihos** [comment]
Το θέμα είναι λίγο τεχνικό, θα πρέπει να το δει η εταιρία/προγραμματιστής που διαχειρίζεται το site σας.

**Comment by dimline1** [comment]
Επομένως να σας φέρω σε επαφή για τα περαιτέρω...

**Comment by dimline1** [comment]
http://www.fastwebltd.com/support/index.php

**Comment by dmihos** [comment]
Θα πρέπει να τους εξηγήσετε το πρόβλημα (πιθανά με αναφορά στο παρόν issue), και εφόσον έχουν απορίες, μπορούν να τις αναρτήσουν εδώ.

**Comment by dimline1** [comment]
Μίλησα με τον διαχειριστή και μου είπε ότι έφτιαξε νέα πληρωμή μέσω Viva και περιμένει να την ενεργοποιήσετε....

**Comment by dmihos** [comment]
Αναφέρεστε μάλλον σε νέα πηγή πληρωμής, η οποία όντως δημιουργήθηκε και έχει πλέον ενεργοποιηθεί.

**Comment by dimline1** [comment]
Ναι , φυσικά . Πράγματι δημιουργήθηκε καινούρια και μου ήρθε μήνυμα ενεργοποίησης.
Μένει τώρα να δούμε λειτουργικά πως θα τρέξει ,  γιατί ακόμα δεν έχει πραγματοποιηθεί καμιά πληρωμή... Ελπίζω να είναι όλα σωστά!

**Comment by dimline1** [comment]
Εξακολουθεί παρά την νέα ενεργοποίηση και ρύθμιση να μην ολοκληρώνονται οι συναλλαγές  και πάλι 
 Κωδικός 4171 σε autotecparts  με redirection

**Comment by dmihos** [comment]
Θα χρειαστεί ο τεχνικός σας να μας πει τί σφάλμα παίρνει ακριβώς από το Api

**Comment by kostGX** [comment]
Closing as issue over 1 year old.
