### ISSUE TITLE
Generating bancontact QR from API

### ISSUE THREAD

**Issue by diklou** [VivaPayments/API#2397]
I would like to get the link to put inside a bancontact QR code (looks something like: `BEP://1BNCT-API.VIVAPAYMENTS.COM/BNCTQR*3803598803957909*855$1AD5CE39D2F684EEB9BC7B3D`) using viva wallet API. How to proceed ? I couldn't find anything on the docs.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,

Thank you for your message. We are currently investigating your request. We will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,

Thank you for waiting. We would like to inform you that this feature is not available. Kinly note that Bancontact QR is integrated in our Smart Checkout and the QR code is generated when you select this payment method.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by diklou** [comment]
But there is no way to generate a Bancontact QR code from the API ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,

Thank you for your message. As mentioned above, this feature is not available since Bancontact QR is integrated in our Smart Checkout and the QR code is generated when you select this payment method.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @diklou,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
