### ISSUE TITLE
Token expiration time

### ISSUE THREAD

**Issue by deliverymanager** [VivaPayments/API#24]
The Token seems to expire quickly after its creation.
Is there a way to extend the token period of expiration?
Otherwise what is the purpose of creating the token? 
If I can't store the token and use it again for new payments, so that the user will not have to enter his card details again?

**Comment by dmihos** [comment]
Hi.
As you have probably already been informed, the token is a one-time, short living, code that allows you to securely charge a card.
For repeating charges, please have a look at [recurring payments](https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction)
