### ISSUE TITLE
Pay with Viva Wallet

### ISSUE THREAD

**Issue by sofiakol** [VivaPayments/API#240]
Στο wiki αναφερετε πως για την υπηρεσια Pay with Viva Wallet  μπορούμε να βρούμε το public key μέσα στο Merchant account. Δυστυχώς μέσα στο λογαριασμό δεν υπάρχει κάποιο Public key, από όσο με ενημέρωσαν και τηλεφωνικά από τη Viva.

Που ακριβώςε υπάρχει το key αυτο;

**Comment by dmihos** [comment]
Κάνοντας login με το εμπορικό σας account στο www.vivawallet.com, επιλέγετε Μενού>Ρυθμίσεις>Πρόσβαση API.
Επιλέγετε το checkbox "Ενεργοποίηση υπηρεσίας Native/Pay with Viva Wallet checkout" και θα εμφανιστεί από κάτω το Public Key που χρειάζεστε.
Ευχαριστούμε για την επικοινωνία
