### ISSUE TITLE
Cannot hide "Send Receipt" button - Android integration

### ISSUE THREAD

**Issue by bilal4k** [VivaPayments/API#2400]
Hi there,

I'm currently integrating the Viva Wallet Android SDK into my application using the documentation provided [here](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminal-apps/android-app/sale/). While performing a transaction with specific options, I noticed that there is no option available to hide the "Send Receipt" button.

I would like to ask if such a feature that allows developers to hide the "Send Receipt" button in the Viva Wallet Android SDK exists. This would be beneficial for scenarios where the sending of receipts is not necessary or handled in a different manner within the application.

Could you please let me know if this feature is planned for development in the future? If so, it would be helpful to have an estimated timeline for when this feature might be implemented.

Thank you very much for your assistance.

Best regards,

**Comment by VivaWalletCustomerSupport** [comment]
Hello @bilal4k,

Thank you for your message. We are currently investigating your request. We will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @bilal4k,

Thank you for waiting. We kindy advise you to use the parameter show_receipt with value "false". More information about the paremeters can be found in the link below:

[Sale request](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminal-apps/android-app/sale/#sale-request)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @bilal4k,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @bilal4k,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
