### ISSUE TITLE
Payment source filling

### ISSUE THREAD

**Issue by yu5056561661** [VivaPayments/API#2401]
Hello, I am integrating smart checkout. How can I fill in the URL in the payment source for testing? I am a local testing environment

**Comment by yu5056561661** [comment]
![image](https://github.com/VivaPayments/API/assets/75231131/c2cb1a54-118e-461c-ba7b-c9de1319c8c1)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

Thank you for your message. Could you please share the domain name URL you are trying to add?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by yu5056561661** [comment]
I am testing in a local environment, which is similar to http://192.168.192.24:8080

**Comment by yu5056561661** [comment]
Alternatively, using 'Webhook' is fine, but now that's the address, how should I add it? Because I'm in a local testing environment and the address is 192.168.192.24:8085

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

Thank you for the update. Kindly note that domain URL must use the following format: 
- If your site uses www: www.yourdomain.com
- If your site doesn’t use www: yourdomain.com

Additional information in the link below:
[https://developer.vivawallet.com/getting-started/create-a-payment-source/payment-source-for-online-payments/](url)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by yu5056561661** [comment]
How can I test locally?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

Thank you for your message.
You will have to set a local domain name to add the source URL and test it locally.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by yu5056561661** [comment]
How can I include my own parameters in the returned URL?

**Comment by yu5056561661** [comment]
Each merchant on our platform can collect their own money, is it necessary for each merchant to open a key for a Viva account? Do each merchant need to set up a separate online payment source?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

Are you referring to an ISV or Marketplace account? Can you please elaborate a bit more?

Regarding the URL parameters you can find additional details at the seventh step of the guide in link below: [https://developer.vivawallet.com/getting-started/create-a-payment-source/payment-source-for-online-payments/](url)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by yu5056561661** [comment]
I am using 'smart checkout' and now I am using a simulated account. What I mean is, in the real environment, do I need to create a separate payment source for each store for online payment

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

Thank you for the update.
Exactly, each webstore must have a separate payment source. You can add multiple sources in one account.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by yu5056561661** [comment]
If I use 'webhook', do I also need to set it up separately for each store?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

That is correct. You should set up webhooks for each store separately. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @yu5056561661,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
