### ISSUE TITLE
Opencart vivawallet plug in

### ISSUE THREAD

**Issue by giancalr** [VivaPayments/API#2402]
Hello, is there an update of the vivawallet plugin for opencart 4? Awaiting a Kind Regards

**Comment by VivaWalletCustomerSupport** [comment]
Hello @giancalr,

Thank you for your message.
OpenCart 4 version is not supported. We would like to recommend checking our Release Notes Page for information about the additions and updates to Viva Wallet's products and services. [https://developer.vivawallet.com/releasenotes/](url)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by giancalr** [comment]
Thanks for the reply, I had already seen that there wasn't for open 4, my question was if it was in development,
As a developer of e-commerce sites, I can advise you that for each plugin, especially payment ones, they should be made for all versions of the CMS, since not everyone uses the same version, and then it would be even more profitable for you. cordial greetings

**Comment by VivaWalletCustomerSupport** [comment]
Hello @giancalr,

Thank you for your message. We will review your comments. We always consider our customers' feedback for future improvements.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @giancalr,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by giancalr** [comment]
Good Afternoon, read it, we await updates regarding the plug-in for both opencart version 4 and version 2 Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @giancalr,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
