### ISSUE TITLE
RESELLER_ORDER_DECLINED

### ISSUE THREAD

**Issue by paulcorke** [VivaPayments/API#2405]
I have the Android integration set up and can send the Uri and get a response back.  I have the Viva Terminal App Demo installed and it works for manually entering payments.

From my demo account, in the Settings / API Access area I have extracted my Merchant ID, Client ID and Client Secret and put them in the vivapayclient:// request.

The device switches to Viva Pay, then immediately switches back to my app and returns status=fail with message="(-62) RESELLER_ORDER_DECLINED".

How can I work out what is going wrong please?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

Thank you for your message. We would like to inform you that the error (-62) RESELLER_ORDER_DECLINED appears when the (ISV) Account Credentials that are used in the request are not correct. Can you please ensure that the credentials used belong to your ISV account? 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by paulcorke** [comment]
Thanks - I followed the docs and set up an account on demo.vivapayments.com so it sounds like I also need a separate ISV account.  I'll take this up with our VivaWallet account manager.
