### ISSUE TITLE
Update Parameters Error

### ISSUE THREAD

**Issue by paulcorke** [VivaPayments/API#2406]
Using the Android integration in the demo environment, contactless test card on a terminal with built in NFC.  All transactions are getting declined with "(-12) TRANSACTION_DECLINED_BY_SERVER".  I can't find anywhere in the portal or app which gives any more detail on why this might be happening.  Is there somewhere I can look?

If I try to make a payment just using the Viva Demo app, I can make ONE successful payment (only) before it starts failing with the same declined error.  It also shows a toast with "Update parameters error".  I found an option in "Settings" to Update but it just gives the same error.  If I use the "Settings Reset" option it looks like I can make one more successful payment before needing to reset again.  A "Full Reset" seems to show the same behaviour.

What can I do to work out why this is happening?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

Thank you for your message. Can you please send us the merchant ID of your demo account? Also, can you please send us the logs of the device? You can find the logs by navigating to your POS device to More->Send logs.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by paulcorke** [comment]
Thanks... I've sent you logs for 501eb127-2340-4b5f-9b16-2968c60670f6.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

Thank you for your swift response. Can you also send us the Sale request you are doing for the app-to-app integration? Lastly, we would like to know the version of your POS application. You can find the version by navigating to your POS device to More-> About.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by paulcorke** [comment]
Hello, the request is:
`
vivapayclient://pay/v1?appId=com.scologic.posimple&action=sale&clientTransactionId=0226315870344&amount=1000&tipAmount=0&show_receipt=true&show_transaction_result=true&show_rating=true&ISV_amount=0&ISV_clientId=7t4047e6d4fn0s42zvu2wlsuooa17f5ivp2wk6scjixp5.apps.vivapayments.com&ISV_clientSecret=redacted&ISV_sourceCode=Default&ISV_currencyCode=826&ISV_customerTrns=POSimple&ISV_clientTransactionId=0-63-0226315870344&ISV_merchantId=501eb127-2340-4b5f-9b16-2968c60670f6&ISV_merchantSourceCode=63&paymentMethod=CardPresent&callback=posimplecb://result`

I have redacted the ISV_clientSecret - I believe the value is correct as it is trying to process the transaction.

The application version is:

```
  v4.24.0(8152)
  06/07/2023, 08:16:31
  Demo Release

```
I have also re-sent logs following the above transaction attempt which was run just now (20230711 around 13:33 BST) and was declined.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

Thank you for your reply. Can you please on the parameter "ISV_merchantSourceCode" Default as value and try again?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by paulcorke** [comment]
That's done it, thank you
