### ISSUE TITLE
Klarna in demo environment

### ISSUE THREAD

**Issue by paulcorke** [VivaPayments/API#2408]
Merchant 501eb127-2340-4b5f-9b16-2968c60670f6.  Clicking on "Enable Klarna as a payment method" in the demo portal gives an empty red error at the top of the screen.  Looking at the network request, there's a call to "enableklarna" which results in a 400 response and a payload of {"FriendlyMessage":"PaymentMethodsRequestFailed: Bad Request"} .  How do we enable Klarna for testing please?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke, 

Thank you for your message. The email field must be filled in your demo Viva Wallet account. Can you please provide an email that you wish to be added to?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by paulcorke** [comment]
I have added an email to both my Merchant and ISV accounts in both the Primary and System contact fields.  I have confirmed by clicking on the emailed links.  However I'm still seeing the same behaviour.  Is there something else I can try, please?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

Thank you for your prompt response. 
We also made some changes. Could you please try again? Let us know if issue persists.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by paulcorke** [comment]
Thank you, that fixed it.
