### ISSUE TITLE
Cannot do partial refund in a Cancel Transaction call in the Demo environment ('PaymentsRefundNotAllowed' error)

### ISSUE THREAD

**Issue by panosmacheras** [VivaPayments/API#2409]
Hi team,

I am trying to do a Cancel Transaction API call in the demo environment and I receive a 'PaymentsRefundNotAllowed' 403 error ('Refund is disabled merchant'). Refunds on the full amount work as expected.

The URI is: https://demo.vivapayments.com/api/transactions/{transactionid}/?amount={partialAmount}

Is there support for partial refunds in the demo environment?

Many thanks.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @panosmacheras,

Thank you for your message. Can you please send us the Merchant ID of the demo account so we can perform some technical checks? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by panosmacheras** [comment]
Thank you for the super-quick follow up. The Merchant ID of the demo account is: 238fa41c-2c8a-4835-8c74-93db06b8beb0

**Comment by VivaWalletCustomerSupport** [comment]
Hello @panosmacheras,

Thank you for your prompt response message. Can you please create a new demo account and try again?
Some features have been added to newer demo accounts that were not available when yours was created.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by panosmacheras** [comment]
Thank you for the follow up. Unfortunately I cannot reuse my personal mobile phone number for the creation of a new demo account. Would it be possible for you to delete my old demo account in order to be able to create a new one (with the same mobile phone number)?

Many thanks.

Panos.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @panosmacheras,

You can use a "dummy" mobile phone number to create a new demo account.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by panosmacheras** [comment]
Will do. Thank you so much.

**Comment by panosmacheras** [comment]
Closing.
