### ISSUE TITLE
Viva Pay Failed

### ISSUE THREAD

**Issue by pgrmr** [VivaPayments/API#241]
Καλησπέρα σας , πρόκειται για ένα site ενός πελάτη μου  στο οποίο ενώ από το checkout φεύγω κανονικά και πηγαίνω στο περιβάλλον του Viva Payment όταν κάνω το charge για να πληρώσω τότε με πηγαίνει στο Transaction Failed . Την πληρωμή την κάνω από έγκυρη κάρτα , κάνω αγορά σε προϊόν με 0,09€ . Φαντάζομαι ότι το πρόβλημα δεν είναι δικό μου διότι το ίδιο Module το χρησιμοποιώ και σε άλλους πελάτες και δεν έχω κάποιο πρόβλημα. Ευχαριστώ εκ των προτέρων .

**Comment by dmihos** [comment]
Καλησπέρα σας
Από τις λίγες πληροφορίες που δίνετε, φαίνεται ότι το πρόβλημα είναι στο ποσό, καθώς δε μπορεί να εγκριθεί συναλλαγή 0.09€. Δοκιμάστε με ένα μεγαλύτερο ποσό (πχ 1€). 
Σε περίπτωση που το πρόβλημα παραμένει, θα χρειαστούμε το merchantId του πελάτη σας για περαιτέρω διερεύνηση. 
Μπορείτε να το στείλετε στο support@vivawallet.com με αναφορά στο παρόν Issue.
Ευχαριστούμε για την επικοινωνία

**Comment by pgrmr** [comment]
Μετά από μεγάλη προσπάθεια κατάφερα να επικοινωνήσω και η απάντηση του support ήταν να μιλήσω μαζί σας στο github . Για το μόνο που με ενημέρωσαν  ήταν ότι η πηγή πληρωμών είναι ενεργή . Παρακαλώ για μια άμεση απάντηση. Ευχαριστώ εκ των προτέρων.

**Comment by dmihos** [comment]
Δοκιμάσατε με κάποιο μεγαλύτερο ποσό από 0.09€;
Ποιο είναι το merchantId; (όχι το ApiKey)

**Comment by pgrmr** [comment]
Merchant ID : a519dd01-b122-42fa-b9ef-f3b2a628c14c

**Comment by pgrmr** [comment]
Και με 1.00€ το ίδιο αποτέλεσμα έχω.

**Comment by dmihos** [comment]
Φαίνεται να χρησιμοποιείτε την πηγή Default στις δοκιμές σας, η οποία είναι για χρήση μόνο σε native checkout.
Δοκιμάστε με κάποια άλλη πηγή που είναι για redirect checkout.
