### ISSUE TITLE
MBWay payment option not appearing after enabled

### ISSUE THREAD

**Issue by Gustavo-Stein** [VivaPayments/API#2410]
Hello, i have enabled MBWay as local payment method, but any charge created appears only credit cards as payment option. See attached.

Sample created payment

https://www.vivapayments.com/web2/?ref=9418494559595422

Not appears even if method is added on URL like:

https://www.vivapayments.com/web2/?ref=9418494559595422&color=ffd700&paymentmethod=31

![Screenshot_3](https://github.com/VivaPayments/API/assets/65373775/6dbd0379-fac0-4f95-b06d-1a5e0559e852)

Thanks in advance!

**Comment by Gustavo-Stein** [comment]
In other hand, generic links like:

https://pay.vivawallet.com/gatogordo 

After amount and description added, offears the mbway and multibanco as payment option.

**Comment by Gustavo-Stein** [comment]
Already solved, please close.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Gustavo-Stein,

Thank you for the feedback. This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
