### ISSUE TITLE
ISV Connected Accounts redirectUrl times out in demo environment

### ISSUE THREAD

**Issue by horvathferenc** [VivaPayments/API#2411]
Hey,

I've ran into an issue with Connected Accounts. I've been following [this](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Connected-Accounts/paths/~1isv~1v1~1accounts/post) to create a Connected Account. I get the correct response with everything included (accountId, invitation object with email, redirectUrl, created) however when I open the redirectUrl (which is essentially an invite link), it loads for like 5-10 minutes and eventually times out. The structure of the URL also looks fine: https://demo-app.vivapayments.com/register/invite/3/{accountId}.

Is this feature disabled on demo? If so, how can I test the whole workflow without running through and checking out the onboarding?

Exact error:

An error occurred while processing your request.
Reference #221.be045368.1689701565.8f5b291

**Comment by VivaWalletCustomerSupport** [comment]
Hello @horvathferenc,

Thank you for your message. We would like to inform you that the invitation link is not functional in the demo environment. As a workaround you can connect a new demo account that you will create by adding the value of "accountId" parameter to the field "Connected account id".

![image](https://github.com/VivaPayments/API/assets/112542999/5c10e5d1-b82d-4a32-b905-f26ab09a8ed0)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @horvathferenc,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @horvathferenc, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
