### ISSUE TITLE
How to get all subscription / payment with API ?

### ISSUE THREAD

**Issue by AmityTek** [VivaPayments/API#2412]
Hi,

i can't find any endpoints to get all subscription, or last payment in given time.
I would like to get all recurrent payment, i just need basic infos.
why you doc isn't providing anything on this topic ? (support in website doesn't know anything)

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AmityTek,

Thank you for your message. If you wish to find all subscriptions of your account, you can use our [Retrieve Transaction by Date API request](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)/paths/~1api~1transactions~1{transaction_id}/get) and check the parameter "recurringSupport". All the transactions that allow recurring payments will have the value "true" on this parameter.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AmityTek** [comment]
Thank you

doing this 
I am calling like that GET : https://demo.vivapayments.com/api/transactions/?sourceCode=Default
with
![image](https://github.com/VivaPayments/API/assets/18656702/03e59737-090b-4b06-bcf7-cddc5d6722bc)

So why i have  : Error 400: Empty options ?

Best regards

**Comment by AmityTek** [comment]
OK i added &date=2018-08-27 for example its working

but what i need is simple, retrieve all transaction in my account, (ALL) 
it is possible ?

could you show me which url i have to use in production mode ?

**Comment by AmityTek** [comment]
_https://demo.vivapayments.com/api/transactions/?sourceCode=Default&date=xxxx WORKING

https://www.vivapayments.com/api/transactions/?sourceCode=Default&date=xxxx  NOT WORKING_

![image](https://github.com/VivaPayments/API/assets/18656702/431dc910-ed0c-4b2e-8ac2-b3b071036e67)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AmityTek,

Thank you for the swift response. Kindly note that via our API you can only retrieve a single transaction or transactions of a specific date. About the 404 response can you please provide the Merchant ID of your account to investigate it further?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AmityTek** [comment]
Sorry,
my fault, i was with the wrong merchantID

thank you for help !!
When you will update this link for the V2? because its deprecated

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AmityTek,

Thank you for your message. Even though they appear as deprecated, they are fully functional.

We would also like to recommend checking our [release notes page](https://developer.vivawallet.com/releasenotes/) for information about the additions and updates to our products and services.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AmityTek,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
