### ISSUE TITLE
Show on Android second screen

### ISSUE THREAD

**Issue by paulcorke** [VivaPayments/API#2413]
With the Android integration, how can we request that the Viva app appears on the second screen please?  I don't see any param to vivapayclient://pay/v1 which allows us to force it to the second - customer facing - screen.

Thanks.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

Thank you for your message. Can you please clarify if this second - customer facing - screen will be on the same device that our POS application has been installed or in a different device?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by paulcorke** [comment]
The same device.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

Thank you for the swift response. Can you also clarify if your application is installed on the same device as well?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by paulcorke** [comment]
Yes, it's one device with two screens which has both our app and the Viva Terminal app installed.  Our app runs mainly on the primary screen (Display.DEFAULT_DISPLAY) which faces and is used by the operator / teller.  We also use the second display - which faces the customer - to tell them about the products they are buying and the cost.

When the teller presses the "Pay by card" button, our app requests an activity with the "vivapayclient://pay/v1" uri as per your integration document.  We would like to force the Viva Terminal app to open on the second display so that the customer can see it.

I hope that makes sense but please send over any other questions you may have.

Thank you.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

There is no such parameter in our implementation. This is out of our scope of support. However, you could try when in your app you select the "Pay by card" your app to start screen mirroring on the second screen.

Kind regards,
Viva Wallet E-commerce Support Team
