### ISSUE TITLE
Zen cart Plug in

### ISSUE THREAD

**Issue by giancalr** [VivaPayments/API#2414]
Hello, until December 2020 the plugin for zen cart was present, of course we have a version that works perfectly, but with the new updated payment methods, such as MobilePay, Samsung Pay etc etc, even by enabling the function in the dashboard, they do not appear, is it possible to make an update if we forward the previous plugin? Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @giancalr,

Thank you for your message. In this [link ](https://developer.vivawallet.com/plugins/)you will find all supported plugins you can accept payments online with Viva Wallet. 

We would also like to recommend checking our [release notes page](https://developer.vivawallet.com/releasenotes/) for information about the additions and updates to our products and services.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by giancalr** [comment]
thanks, we've already seen all the plug-ins, but zen cart was there before and now it's not, greetings

**Comment by VivaWalletCustomerSupport** [comment]
Hello @giancalr,

Thank you for your message. We always consider our customers' feedback for future improvements. Kindly note that zen cart is no longer officially supported.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @giancalr, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
