### ISSUE TITLE
main.CRITICAL: Error: Call to a member function getFirstname() on null

### ISSUE THREAD

**Issue by SkyMerlinHosting** [VivaPayments/API#2415]
API/Plugins/magento_vivawallet/magento23_vivawallet/Ced /VivaPayments/ 

Orders in Magento stay as pending with payment pending status even though payment is captured in viva wallet.

`[2023-07-22T16:21:58.388844+00:00] main.CRITICAL: Error: Call to a member function getFirstname() on null in /var/www/vhosts/juicegods.co.uk/htdocs/app/code/Ced/VivaPayments/Model/PaymentMethod.php:97

Stack trace:
#0 /var/www/vhosts/juicegods.co.uk/htdocs/app/code/Ced/VivaPayments/Controller/Checkout/Start.php(40): Ced\VivaPayments\Model\PaymentMethod->getPostHTML()
#1 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Ced\VivaPayments\Controller\Checkout\Start->execute()
#2 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callParent()
#3 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->Magento\Framework\Interception\{closure}()
#4 /var/www/vhosts/juicegods.co.uk/htdocs/generated/code/Ced/VivaPayments/Controller/Checkout/Start/Interceptor.php(23): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callPlugins()
#5 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/App/Action/Action.php(111): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->execute()
#6 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#7 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callParent()
#8 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->Magento\Framework\Interception\{closure}()
#9 /var/www/vhosts/juicegods.co.uk/htdocs/generated/code/Ced/VivaPayments/Controller/Checkout/Start/Interceptor.php(32): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callPlugins()
#10 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/App/FrontController.php(245): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->dispatch()
#11 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#12 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#13 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#14 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#15 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#16 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#17 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/amasty/aminvisiblecaptcha/Plugin/Framework/App/FrontControllerInterface/ValidateCaptcha.php(124): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#18 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\InvisibleCaptcha\Plugin\Framework\App\FrontControllerInterface\ValidateCaptcha->aroundDispatch()
#19 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#20 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#21 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#22 /var/www/vhosts/juicegods.co.uk/htdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#23 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#24 /var/www/vhosts/juicegods.co.uk/htdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#25 /var/www/vhosts/juicegods.co.uk/htdocs/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#26 /var/www/vhosts/juicegods.co.uk/htdocs/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#27 {main} [] []
`

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SkyMerlinHosting,

Thank you for your message. Could you please send us a screenshot from the plugin settings?

Kind regards,
Viva Wallet E-commerce Support Team
