### ISSUE TITLE
OrdersOrderCodeNotFound: Order with code 0 was not found

### ISSUE THREAD

**Issue by lebe1** [VivaPayments/API#2416]
I feel like this is a common error when getting in touch with your API, since it is also mentioned in your tutorial [here](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/#step-2-redirect-the-customer-to-smart-checkout-to-pay-the-payment-order).  
Therefore, I hope others will be glad finding this post while searching for the error and getting a solution. Right now, I try testing your smart checkout integration via curl with my demo account.
Following the above mentioned tutorial, everything works fine for me until I have to copy my OrderCode from my last response into the checkout-URL.
Everytime I type in or copy the OrderCode from terminal into `https://demo.vivapayments.com/web/checkout?ref={4679889206735290}` like this, I receive the mentioned error above.
Any help is welcome.
P.S. My merchant-ID is: `5779279b-4c1c-4504-aa25-46a13bb4f608`
![Screenshot from 2023-07-24 11-42-58](https://github.com/VivaPayments/API/assets/38591956/617b4483-ff56-4aed-a8ed-42c817f63b42)
![image](https://github.com/VivaPayments/API/assets/38591956/2f32cc74-76a7-4598-9b55-df333bb2153a)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @lebe1,

Thank you for your message. From the screenshot we can observe a Goggle Pay error. Please note that to test Google Pay you must use the specific test card suite provided by Google. Additional information [here](https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#google-pay).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by lebe1** [comment]
Hi @VivaWalletCustomerSupport,
thanks for your reply.  
This is an interesting error since I never wanted to test/use Google Pay and just wanted to have a look into your smart checkout process. Is this a necessary requirement to connect to a Google Pay account for using smart checkout? 
If so, this information is missing in this [tutorial](https://developer.vivawallet.com/smart-checkout/smart-checkout-integration/).
After checking even further your provided link, as far as I understand my redirection to the smart checkout process should work and in the next step I could test paying via Google pay with my own wallet or a test wallet, right?

**Comment by lebe1** [comment]
By the way this is the console log using Chrome. The error looks different first but it is actually the same error throwing line too. 

Line 7230 in its browser javascript file:
`document.getElementById('gpayContainer').appendChild(button);`

![image](https://github.com/VivaPayments/API/assets/38591956/6b418b82-899b-4f04-b034-421ddffe4a20)

![image](https://github.com/VivaPayments/API/assets/38591956/b29f3900-c473-4887-b56f-9d8bab95a037)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @lebe1,

Thank you for your message. 
Can you please follow the instructions of the link below and send us the X-Viva-CorrelationId of the error? 
https://developer.vivawallet.com/integration-reference/debugging-errors/#x-viva-correlationid-and-x-viva-eventid

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by lebe1** [comment]
Hi @VivaWalletCustomerSupport,

I found my error on my own now, which is quite obvious and ridicolous in the retrospective...

My problem was that I only replaced `OrderCode` in the demo link like this ` https://demo.vivapayments.com/web/checkout?ref={4679889206735290}` as shown in my first [post](https://github.com/VivaPayments/API/issues/2416#issue-1818094022).
The solution is **not using curly brackets in an URL**, so the correct URL looks something like `https://demo.vivapayments.com/web/checkout?ref=4679889206735290`  

Do you want me to close the issue now?  
Or maybe someone else falls into this one and this issue helps them out ?
Two other options I see is showing a proper example in your tutorial or you just keep everything as it is and expect the devs to know something like **not using curly brackets in a link** ;)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @lebe1 

Thank you for your prompt response and for your suggestions. We always consider our customers' feedback for future improvements. 
This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
