### ISSUE TITLE
Android Demo app "not available in your country"

### ISSUE THREAD

**Issue by paulcorke** [VivaPayments/API#2417]
![2023-07-24 16 42 54 (Medium)](https://github.com/VivaPayments/API/assets/32541176/debba6ee-ff78-4cd1-99bc-dc496ff58af4)

I have two terminals, both from the same manufacturer, both Android 10, both with the same Google account (which is whitelisted), both on the same WiFi (so same public IP address).  Tapping the link on the Viva Payments developer documentation ("you can find the Demo POS app via this direct link") gives the result in the picture.  One terminal has downloaded and installed the app and the other says it is not available in my country (UK).

Do you have any suggestions on how I can install the demo app on the second device for testing please?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

Thank you for your message. There may be a conflict between the google account. Can you please provide an additional Gmail account we can whitelist as well?
You can share it here or via email at support@vivawallet.com 
Please add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by paulcorke** [comment]
I tried it with a different google user and it worked, thanks.

**Comment by michel-silva** [comment]
Hi @VivaWalletCustomerSupport 
I'm working on an integration with Viva Payments and I need to download the Viva.com Terminal demo. Could you please add my email to the whitelist?

Thank you
