### ISSUE TITLE
Unable to Access viva api wiki page

### ISSUE THREAD

**Issue by d3sync** [VivaPayments/API#2418]
Apologies if this is miss placed but I couldn't find any other more appropriate place to ask.
I am trying to access the following link where the api for countertop pos is.
It appears to asks for a basic authentication now
https://developer.vivawallet.com/pos-api-integration/pos-terminals/vivawallet-api-cl

Apologies and thank you.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @d3sync,

Thank you for your message. Kindly note the above feature is deprecated and the link is no longer available.
Additional information regarding Viva Wallet’s REST API (EFT POS) functionality can be found [here](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/). 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by d3sync** [comment]
Will the same API be available for older CounterTop POS like S800 and S900 or they should be replaced? Currently I have a winforms app that is being used with the ECR mode on such devices and I wanted to check if there were any changes/updates, due to a bug that occurred after a transaction 
(a successful transaction did not register on viva's system)

Thank you 
With regards

**Comment by VivaWalletCustomerSupport** [comment]
Hello @d3sync,

Thank you for your swift response. As per company policy we are moving to Rest API (EFT POS) solution.
The REST API functionality is not currently supported for Paydroid (PAX) devices including S800 and S900.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by d3sync** [comment]
Appreciate the quick responses, I do have one last question. Is there a timeline until the support for such devices is dropped completely, or an estimation when those older models should be replaced and move to the RestAPI ?

Thank you!
With regards
Alex

**Comment by VivaWalletCustomerSupport** [comment]
Hello @d3sync,

Thank you for your message. We cannot provide a specific timeline; we would recommend checking our Release Notes Page for information about the additions and updates to Viva Wallet's products and services. 

https://developer.vivawallet.com/releasenotes/

Kind regards,
Viva Wallet E-commerce Support Team
