### ISSUE TITLE
Testing failed transaction/payment callback

### ISSUE THREAD

**Issue by kristofthys** [VivaPayments/API#2420]
Hello,

Is there a way to test a failed payment using the demo environment?

I don't see an option to generate/simulate a failed payment...

Thanks,
Kristof

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kristofthys,
 
Thank you for your message.
Please note that to trigger a failed payment, [specific test cards](https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#trigger-a-decline) must be used. Also, with a [specific amount](https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#an-issuer-decline-without-decline-recovery) you can trigger a specific Response EventId.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by kristofthys** [comment]
Thanks! Ticket can be closed!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kristofthys,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
