### ISSUE TITLE
Aborting a session has no impact on session status

### ISSUE THREAD

**Issue by OssiPesonen** [VivaPayments/API#2422]
I have a mobile application (ECR) where I am polling the [Retrieve Session by Id](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Sessions/paths/~1ecr~1v1~1sessions~1{sessionId}/get) endpoint in Viva Wallet Cloud REST API after I've initiated a sale transaction. 

I get the payment request visible in Viva Terminal App, but if I perform an [Abort Session](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Session-Details/paths/~1ecr~1isv~1v1~1sessions~1{SessionId}/delete) request from the ECR, I get a 200 OK response (with no message), yet the session is not affected. My device still keeps polling the endpoint as it keeps returning:

> {"detail":"The session is being processed"}

The payment is still visible on the Viva Terminal application and is not affected.

**Due note!** This seems to only happen when the default payment method on the Viva Wallet app is "QR code" and not "Tap on Phone". QR code as a payment method does not seem to be affected by the Abort request.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @OssiPesonen,

Thank you for your message. Can you please send us the call you used and the response you got (full code)?
Also, make sure that you have the latest APP installed on your device.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @OssiPesonen,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @OssiPesonen,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
