### ISSUE TITLE
Hello, I am using your plugin for Woocommerce - Viva Wallet Smart Checkout

### ISSUE THREAD

**Issue by ivangrozni12** [VivaPayments/API#2423]
I add API key, Merchant ID and Source Cod. And when I buy something and choose payment with Viva Wallet, I am receiving this error message: 

Thank you for your order, please click the button below to pay.

Fatal error: Uncaught Exception: Unable to reach Viva Payments (401 -- Unauthorized) in /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php:378 Stack trace: #0 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php(496): WC_VIVAWALLET->generate_form() #1 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/class-wp-hook.php(308): WC_VIVAWALLET->receipt_page() #2 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #3 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/plugin.php(517): WP_Hook->do_action() #4 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/plugins/woocommerce/templates/checkout/order-receipt.php(44): do_action() #5 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/home/vhosts/mm...') #6 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(243): wc_get_template() #7 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(59): WC_Shortcode_Checkout::order_pay() #8 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_Checkout::output() #9 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(95): WC_Shortcodes::shortcode_wrapper() #10 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/shortcodes.php(355): WC_Shortcodes::checkout() #11 [internal function]: do_shortcode_tag() #12 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/shortcodes.php(227): preg_replace_callback() #13 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/class-wp-hook.php(308): do_shortcode() #14 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/plugin.php(205): WP_Hook->apply_filters() #15 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/post-template.php(255): apply_filters() #16 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/themes/splendour/skins/default/templates/content-page.php(35): the_content() #17 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/template.php(785): require('/home/vhosts/mm...') #18 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/template.php(718): load_template() #19 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/general-template.php(204): locate_template() #20 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/themes/splendour/page.php(14): get_template_part() #21 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-includes/template-loader.php(106): include('/home/vhosts/mm...') #22 /home/vhosts/mmijewellers.com/mmijewellers.com/wp-blog-header.php(19): require_once('/home/vhosts/mm...') #23 /home/vhosts/mmijewellers.com/mmijewellers.com/index.php(17): require('/home/vhosts/mm...') #24 {main} thrown in /home/vhosts/mmijewellers.com/mmijewellers.com/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php on line 378
There has been a critical error on this website.

[Learn more about troubleshooting WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ivangrozni12,

Thank you for your message. Can you please send us a screenshot of the plugin's settings? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ivangrozni12,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ivangrozni12,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
