### ISSUE TITLE
API usage by an Open Banking TPP

### ISSUE THREAD

**Issue by botsman** [VivaPayments/API#2424]
Hello,

Sorry, I did not find any direct contacts to ask my question. Please direct me if there is a better place to ask this kind of questions.

I am contacting on behalf of the Open Banking TPP "Enable Banking Oy". 
We would like to integrate with your API and I wanted to ask whether you have some Open Banking specific API or you expect TPPs to use your general purpose API (https://developer.vivawallet.com/apis-for-payments/payment-api/)?

Thanks!
Best regards

**Comment by VivaWalletCustomerSupport** [comment]
Hello @botsman,

Thank you for your message. We would like to inform you that Open Banking API is not yet available. All the available APIs can be found in the link below:

https://developer.vivawallet.com/apis-for-payments/payment-api/

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by botsman** [comment]
Thank you for the answer.
Should we as a TPP wait until Open Banking API is available (do you have any estimates on this?)
Or are we able to use your current API meanwhile?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @botsman,

Thank you for the swift response. Unfortunately, we do not have any estimated date of release to provide. We would like to advise you to use the available APIs until this feature is available. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by botsman** [comment]
Thanks for the answers!

**Comment by fed239** [comment]
Hello! Are there updates regarding availability of PSD2 APIs?

Kindest regards,
Fedor

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fed239,

Thank you for your message. 

We would like to inform you that Open Banking API is not yet available. 

Unfortunately, we do not have any estimated date of release to provide. We would like to advise you to use the available APIs until this feature is available.

All the available APIs can be found in the link below:

https://developer.viva.com/api-docs/

Kind regards,
Viva E-commerce Support Team

**Comment by fed239** [comment]
@VivaWalletCustomerSupport Many thanks for coming back to us. Could you please instruct us how we can the API on behalf of the end-user?
