### ISSUE TITLE
Woocommerce smart checkout error

### ISSUE THREAD

**Issue by alxm2023** [VivaPayments/API#2425]
Hi,
I have installed VivaWallet Smartcheckout for Woocommerce on my client's website. 
I used a direct checkout link (https://mkmendis.gr/?add-to-cart=138&redirect_to_checkout=true) for a digital product.

Using demo settings, the transaction seems to be done appropriately, but the following issue occurs:

The status of the order payment on woocommerce appears always as pending (not completed), although the transaction appears correctly on the viva (demo) account. I have to manually set it to "completed", so that woocommerce sends the downloadable product that was (virtually) purchased. This also happens with a live account and live settings.

Please note:
1. I have checked all woocommerce endpoint settings , as well as the source code settings on viva. In fact, using the Standard Viva for Woocommerce, the problem is resolved. I would still prefer to use the Smartcheckout.

2. A test with Paypal (live) worked perfectly and the order payment status was seen immediately as "completed".

Here is the woocommerce status:

`
### WordPress Environment ###

WordPress address (URL): https://mkmendis.gr
Site address (URL): https://mkmendis.gr
WC Version: 7.9.0
REST API Version: ✔ 7.9.0
WC Blocks Version: ✔ 10.4.6
Action Scheduler Version: ✔ 3.6.1
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: el
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.21
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.87.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 10.3.36-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.9.0
WC Database Prefix: mk_
Συνολικό μέγεθος βάσης δεδομένων: 32.82MB
Μέγεθος βάσης δεδομένων: 31.25MB
Μέγεθος ευρετηρίου βάσης δεδομένων: 1.57MB
mk_woocommerce_sessions: Δεδομένα: 0.03MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_woocommerce_api_keys: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_woocommerce_attribute_taxonomies: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_woocommerce_downloadable_product_permissions: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_woocommerce_order_items: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_woocommerce_order_itemmeta: Δεδομένα: 0.01MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_woocommerce_tax_rates: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_woocommerce_tax_rate_locations: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_woocommerce_shipping_zones: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_woocommerce_shipping_zone_locations: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_woocommerce_shipping_zone_methods: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_woocommerce_payment_tokens: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_woocommerce_payment_tokenmeta: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_woocommerce_log: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_actionscheduler_actions: Δεδομένα: 0.03MB + Ευρετήρια: 0.03MB + Μηχανή MyISAM.
mk_actionscheduler_claims: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_actionscheduler_groups: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_actionscheduler_logs: Δεδομένα: 0.03MB + Ευρετήρια: 0.02MB + Μηχανή MyISAM.
mk_commentmeta: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_comments: Δεδομένα: 0.01MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_cpappbk_forms: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_cpappbk_messages: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_e_events: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_hfcm_scripts: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
mk_layerslider: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_layerslider_drafts: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_layerslider_revisions: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_links: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_ml_data: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
mk_options: Δεδομένα: 5.72MB + Ευρετήρια: 0.14MB + Μηχανή MyISAM.
mk_postmeta: Δεδομένα: 1.11MB + Ευρετήρια: 0.22MB + Μηχανή MyISAM.
mk_posts: Δεδομένα: 23.09MB + Ευρετήρια: 0.15MB + Μηχανή MyISAM.
mk_redirection_404: Δεδομένα: 0.08MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
mk_redirection_groups: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
mk_redirection_items: Δεδομένα: 0.02MB + Ευρετήρια: 0.09MB + Μηχανή InnoDB.
mk_redirection_logs: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
mk_relevanssi: Δεδομένα: 0.29MB + Ευρετήρια: 0.38MB + Μηχανή MyISAM.
mk_relevanssi_log: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_relevanssi_stopwords: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_revslider_css: Δεδομένα: 0.09MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_revslider_css_bkp: Δεδομένα: 0.09MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_revslider_layer_animations: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_revslider_layer_animations_bkp: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_revslider_navigations: Δεδομένα: 0.01MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_revslider_navigations_bkp: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_revslider_sliders: Δεδομένα: 0.05MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_revslider_sliders_bkp: Δεδομένα: 0.04MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_revslider_slides: Δεδομένα: 0.12MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_revslider_slides_bkp: Δεδομένα: 0.06MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_revslider_static_slides: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_revslider_static_slides_bkp: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_statistics_exclusions: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_statistics_historical: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_statistics_pages: Δεδομένα: 0.00MB + Ευρετήρια: 0.02MB + Μηχανή MyISAM.
mk_statistics_search: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_statistics_useronline: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_statistics_visit: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_statistics_visitor: Δεδομένα: 0.00MB + Ευρετήρια: 0.02MB + Μηχανή MyISAM.
mk_termmeta: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_terms: Δεδομένα: 0.01MB + Ευρετήρια: 0.02MB + Μηχανή MyISAM.
mk_term_relationships: Δεδομένα: 0.01MB + Ευρετήρια: 0.03MB + Μηχανή MyISAM.
mk_term_taxonomy: Δεδομένα: 0.01MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_usermeta: Δεδομένα: 0.04MB + Ευρετήρια: 0.02MB + Μηχανή MyISAM.
mk_users: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_vivawallet_data: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_viva_payment_transactions: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_wc_admin_notes: Δεδομένα: 0.06MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_wc_admin_note_actions: Δεδομένα: 0.03MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_wc_category_lookup: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_wc_customer_lookup: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_wc_download_log: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_wc_order_coupon_lookup: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_wc_order_product_lookup: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_wc_order_stats: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_wc_order_tax_lookup: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_wc_product_attributes_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
mk_wc_product_download_directories: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_wc_product_meta_lookup: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_wc_rate_limits: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_wc_reserved_stock: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_wc_tax_rate_classes: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_wc_webhooks: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_yoast_indexable: Δεδομένα: 0.07MB + Ευρετήρια: 0.04MB + Μηχανή MyISAM.
mk_yoast_indexable_hierarchy: Δεδομένα: 0.00MB + Ευρετήρια: 0.02MB + Μηχανή MyISAM.
mk_yoast_migrations: Δεδομένα: 0.00MB + Ευρετήρια: 0.01MB + Μηχανή MyISAM.
mk_yoast_primary_term: Δεδομένα: 0.00MB + Ευρετήρια: 0.00MB + Μηχανή MyISAM.
mk_yoast_seo_links: Δεδομένα: 0.04MB + Ευρετήρια: 0.02MB + Μηχανή MyISAM.

### Post Type Counts ###

attachment: 295
custom_css: 2
elementor_library: 2
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
nav_menu_item: 31
page: 80
polylang_mo: 2
port: 4
post: 35
product: 9
revision: 1210
shop_order: 31
testimonials: 6
tt_font_control: 1
wp_paypal_order: 1
wpcf7_contact_form: 15
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

LayerSlider: από τον/την Kreatura Media – 7.6.7
Akismet Anti-Spam: Προστασία από ανεπιθύμητα: από τον/την Automattic - Ομάδα Anti Spam – 5.2
Appointment Hour Booking: από τον/την CodePeople – 1.4.25
BackWPup: από τον/την Inpsyde GmbH – 4.0.0
Bridge Core: από τον/την Qode – 3.0.6
Contact Form 7: από τον/την Takayuki Miyoshi – 5.8
Custom Post Type Permalinks: από τον/την Toro_Unit – 3.4.5
Easy Google Fonts: από τον/την Titanium Themes – 2.0.4
Elementor: από τον/την Elementor.com – 3.15.1
Envato Market: από τον/την Envato – 2.0.10
Header Footer Code Manager: από τον/την 99robots – 1.1.35
Jetpack: από τον/την Automattic. – 12.4
WPBakery Page Builder: από τον/την Michael M - WPBakery.com – 6.10.0
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: από τον/την HubSpot – 10.1.30
Modern Footnotes: από τον/την Prism Tech Studios – 1.4.16
Meta pixel for WordPress: από τον/την Facebook – 3.0.13
Image optimization service by Optimole: από τον/την Optimole – 3.9.1
Qi Addons For Elementor: από τον/την Qode Interactive – 1.6.2
Qi Blocks: από τον/την Qode Interactive – 1.2.2
Qode Instagram Widget: από τον/την Qode Themes – 2.1.3
Qode Twitter Feed: από τον/την Qode Themes – 2.0.4
Redirection: από τον/την John Godley – 5.3.10
Relevanssi: από τον/την Mikko Saari – 4.20.0
Slider Revolution: από τον/την ThemePunch – 6.6.8
Under Construction: από τον/την WebFactory Ltd – 3.97
Viva Wallet Standard Checkout: από τον/την Viva Wallet – 1.4.10
Viva Wallet Smart Checkout: από τον/την Viva Wallet – 3.6.8
W3 Total Cache: από τον/την BoldGrid – 2.4.0
Viva Payments - Viva Wallet WooCommerce Payment Gateway: από τον/την Papaki – 1.4.0.1
WooCommerce Direct Checkout: από τον/την QuadLayers – 3.2.1
WooCommerce: από τον/την Automattic – 7.9.0
Yoast SEO: από τον/την Ομάδα Yoast – 20.13
WP Add Custom CSS: από τον/την Daniele De Santis – 1.1.6

### Inactive Plugins (7) ###

Classic Editor: από τον/την WordPress Contributors – 1.6.3
Google Analytics Dashboard for WP (GADWP): από τον/την ExactMetrics – 7.18.1
Open Graph and Twitter Card Tags: από τον/την WPExperts – 3.3.0
Polylang: από τον/την WP SYNTEX – 3.4.5
Post/Page specific custom CSS: από τον/την Łukasz Nowicki – 0.2.4
WordPress Importer: από τον/την wordpressdotorg – 0.8.1
WP PayPal: από τον/την naa986 – 1.2.3.23

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: db.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Βάση καταστήματος: #10200 - /shop/
Καλάθι: #10201 - /cart/
Ταμείο: #10202 - /checkout/
Ο λογαριασμός μου: ❌ Η ορατότητα σελίδας θα πρέπει να είναι δημόσια
Όροι και Προϋποθέσεις: #10668 - /data/

### Theme ###

Name: Bridge Child
Version: 1.0.0
Author URL: http://www.qodethemes.com/
Child Theme: ✔
Parent Theme Name: Bridge
Parent Theme Version: 29.3
Parent Theme Author URL: https://qodeinteractive.com/
WooCommerce Support: ✔

### Templates ###

Archive Template: Το θέμα σας έχει ένα αρχείο woocommerce.php
δεν θα μπορείτε να παρακάμψετε το προσαρμοσμένο πρότυπο woocommerce/archive-product.php καθώς το woocommerce.php έχει προτεραιότητα έναντι του archive-product.php. Αυτό αποσκοπεί στην αποφυγή προβλημάτων εμφάνισης.

Overrides: bridge/woocommerce/cart/cart-empty.php
bridge/woocommerce/cart/cart-shipping.php έκδοση 3.6.0 είναι ληγμένο. Η βασική έκδοση είναι η 7.3.0
bridge/woocommerce/cart/cart-totals.php
bridge/woocommerce/cart/cart.php έκδοση 7.0.1 είναι ληγμένο. Η βασική έκδοση είναι η 7.9.0
bridge/woocommerce/cart/shipping-calculator.php
bridge/woocommerce/checkout/form-coupon.php
bridge/woocommerce/checkout/thankyou.php
bridge/woocommerce/content-product.php
bridge/woocommerce/content-single-product.php
bridge/woocommerce/global/form-login.php
bridge/woocommerce/global/quantity-input.php έκδοση 7.2.1 είναι ληγμένο. Η βασική έκδοση είναι η 7.8.0
bridge/woocommerce/loop/add-to-cart.php
bridge/woocommerce/loop/loop-start.php
bridge/woocommerce/loop/pagination.php
bridge/woocommerce/loop/rating.php
bridge/woocommerce/loop/result-count.php
bridge/woocommerce/loop/sale-flash.php
bridge/woocommerce/myaccount/form-login.php
bridge/woocommerce/myaccount/form-lost-password.php
bridge/woocommerce/myaccount/my-address.php
bridge/woocommerce/myaccount/my-orders.php
bridge/woocommerce/single-product/add-to-cart/external.php
bridge/woocommerce/single-product/add-to-cart/grouped.php
bridge/woocommerce/single-product/add-to-cart/simple.php
bridge/woocommerce/single-product/add-to-cart/variable.php
bridge/woocommerce/single-product/related.php
bridge/woocommerce/single-product/sale-flash.php
bridge/woocommerce/single-product/tabs/additional-information.php
bridge/woocommerce/single-product/tabs/description.php
bridge/woocommerce/single-product/tabs/tabs.php
bridge/woocommerce/single-product/up-sells.php

Outdated Templates: ❌
					
					
						Μάθετε πως να κάνετε ενημέρωση

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-08-09 12:26:44 +03:00
Options: ✔
Notes: 138
Onboarding: completed

### Action Scheduler ###

Ολοκληρωμένη: 102
Oldest: 2023-07-09 11:33:39 +0000
Newest: 2023-08-08 16:21:12 +0000

Αποτυχία: 6
Oldest: 2023-04-17 09:03:56 +0000
Newest: 2023-08-07 10:32:37 +0000

Σε αναμονή: 1
Oldest: 2023-08-08 18:31:41 +0000
Newest: 2023-08-08 18:31:41 +0000

### Status report information ###

Generated at: 2023-08-08 19:39:00 +03:00
`

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alxm2023,

Thank you for your message. Kindly note that our Woocommerce Smart Checkout needs a source to be completely functional. Please follow the instructions of the link below and create a source in your demo Viva Wallet account. If a source is already created, please ensure that the correct success and failure URLs have been used. You can find the correct URLs in the link below as well:

https://developer.vivawallet.com/getting-started/create-a-payment-source/payment-source-for-online-payments/

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by alxm2023** [comment]
Thanks, I was using the wrong URLs. It works now. Still, this would've been avoided if this information was included the dedicated guide for your WooCommerce Smart Checkout plugin. (https://developer.vivawallet.com/plugins/woocommerce-smart-checkout/)

Thanks again!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alxm2023,

Thank you for the swift response. Kindly note that our installation guide includes this information on [Step 3: Create a Payment Source.](https://developer.vivawallet.com/plugins/woocommerce-smart-checkout/#step-3-create-payment-source)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alxm2023,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by alxm2023** [comment]
Hello again support team,
Yes, I read your response. It is clear, I have no more questions. Thank you for your help.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alxm2023,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
