### ISSUE TITLE
Question about accessing transactions

### ISSUE THREAD

**Issue by botsman** [VivaPayments/API#2426]
Hello,

I am trying to get a list of transactions using the endpoint /dataservices/v2/accounttransactions/Search.

Docs say that it requires the urn:viva:payments:biservices:datafileapi scope.
However, the access token created with "Account Transactions Credentials" contains only following scopes:
'urn:viva:payments:core:api:banktransfers '
'urn:viva:payments:core:api:merchants'
'urn:viva:payments:core:api:merchants:wallets'

Could you please tell me how can I get the urn:viva:payments:biservices:datafileapi scope? Perhaps I need to use some other credentials?

Thanks!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @botsman,

Thank you for your message. Kindly note that the[ Account Transactions API](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Retrieve-Wallets-and-Transactions/paths/~1dataservices~1v2~1accounttransactions~1Search/post) requires specific access credentials. To request access, please speak to your sales representative.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by botsman** [comment]
Thanks for the answer!

**Comment by botsman** [comment]
Thanks for the answer!
