### ISSUE TITLE
viva wallet payment page 

### ISSUE THREAD

**Issue by AthanasiaPana** [VivaPayments/API#2428]
Hello. I work in wordpress with woocommerce and I would like to change the default color to the Smart Checkout payment page of viva wallet. can you please help me how can I do it?? Thank you very much in advance

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AthanasiaPana,

Thank you for your message. We would like to inform you that this feature is only available on custom Smart Checkout integrations. This feature will soon be available in our plugins. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AthanasiaPana** [comment]
Can you please inform me when this plugin is available?

Στάλθηκε από το Ταχυδρομείο Yahoo σε Android 
 
  Στις Πέμ, 10 Αυγ, 2023 στις 4:01 μ.μ., ο ***@***.***> έγραψε:   


Hello @AthanasiaPana,

Thank you for your message. We would like to inform you that this feature is only available on custom Smart Checkout integrations. This feature will soon be available in our plugins.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AthanasiaPana,

Thank you for your prompt response. Unfortunately, we don't have an estimated release date for this feature. We kindly recommend you visit our [developer's portal](https://developer.vivawallet.com/releasenotes/) regularly for upcoming releases.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AthanasiaPana,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AthanasiaPana,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
