### ISSUE TITLE
abort session if user doesn't pay for a time?

### ISSUE THREAD

**Issue by CioacaRadu** [VivaPayments/API#2429]
Hello,

after I initiate a session I am starting a pooling while loop on the /sessions endpoint. If the user doesn't pay for 30 seconds I want to stop the transaction, it should be me who aborts the session or I can also set a default timeout in the viva Terminal app?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

Thank you for your message. Kindly note that every session expires after 1 minute if it is not paid. If you wish to abort the session before the expiration time, it should be done manually.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by CioacaRadu** [comment]
Thanks you!
