### ISSUE TITLE
Σύνδεση με vivapayments μετά απο αλλαγή server σε opencart

### ISSUE THREAD

**Issue by vhta** [VivaPayments/API#243]
Καλησπέρα σας.
Μετά απο αλλαγή server σε website με opencart η εξωτερική σύνδεση προς vivapayments οδηγεί σε 
Bad Request

https://www.vivapayments.com/web/newtransaction.aspx?ref=

Τι θα μπορούσε να φταίει;
Μήπως κάπου πρέπει να δηλωθεί η νέα ip;

Ευχαριστώ εκ των προτέρων.

**Comment by dmihos** [comment]
Καλησπέρα σας
Κάποιο πρόβλημα επικοινωνίας με το API ή ίσως κάποια λάθος credentials στο plugin, οδηγούν σε μή δημιουργία κωδικού πληρωμής και έτσι το url της payments δεν έχει τιμή στην παράμετρο ref.
Προτείνουμε να δείτε το θέμα με τον κατασκευαστή του plugin για οδηγίες.
Πιθανα, επίσης, να υπάρχει πρόβλημα να επικοινωνήσει ο νέος server με το https://www.vivapayments.com, οπότε αυτό θα πρέπει να το δείτε με τους υπεύθυνους της υπηρεσίας hosting.

**Comment by kostGX** [comment]
Closing as issue over 1 year old.
