### ISSUE TITLE
Where do I get or set the sourceCode in REST API?

### ISSUE THREAD

**Issue by CioacaRadu** [VivaPayments/API#2430]
I registered to viva wallet with my company directly (the demo was not allowing me to register a device, when I was entering the code it was saying Internal Error).

I am directly on the production version where I was able to register my phone that has the viva terminal card. 

How do I get the sourceCode parameter of the terminal, that I need in order to get the device status before starting a transaction ? It says it is set by merchant but where I can actually set it?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

Thank you for your message. After activating a POS device to your account, a source should be created on your Viva Wallet account and the device should be attached to it. We kindly suggest following the instructions of the link below and creating a source.

https://developer.vivawallet.com/getting-started/create-a-payment-source/payment-source-for-stores/

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by CioacaRadu** [comment]
Thanks for the reply. The kiosk mode is the option of the viva app?
