### ISSUE TITLE
Unattended payments with Cloud Rest API

### ISSUE THREAD

**Issue by CioacaRadu** [VivaPayments/API#2433]
Hello is the Cloud REST API a good option for unattended payments (vending machine)? We didn't finish testing because our account is still pending documents approval

Can we have an android device / android POS terminal attached to the machine with viva | terminal installed on idle? And that will get triggered for payments by the Cloud REST API and after payment will go back in idle?

We are confused as your sales team suggested Cloud REST API for unattended but some article on your website shows that for unattended payments we should use IM30 PAX, that does not support Cloud REST API.

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

Thank you for your message. Our android POS terminals can be attached in a vending machine. We kindly suggest enabling kiosk mode on the devices that will be attached to the vending machines. 

If you use IM30 PAX on the vending machines the Cloud REST API will not be supported.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by CioacaRadu** [comment]
Hi @VivaWalletCustomerSupport 

The kiosk mode is a feature of the viva | terminal app? Or some third-party is required.

Also, how can we enable the usage of the demo environment. The android app viva terminal demo shows "not available in your country". Is whitelisting required? Could you whitelist: cioacaradu@gmail.com as google account. 

We are in a hurry to test your solution as we want to use it in our machine

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

Thank you for the swift response. We would like to inform you that we are currently investigating your request and we will update you about the whitelist of your e-mail. About the kiosk mode, it is an option in our POS devices. You can find all the necessary steps to enable it in the link below:

https://developer.vivawallet.com/tutorials/pos-terminals/tap-on-phone/kiosk-mode/

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

We would like to inform you that your e-mail has been whitelisted. You can now download our demo POS application.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by CioacaRadu** [comment]
Everything is good so far.

Thanks a lot for your help!
