### ISSUE TITLE
Aborting a session, allows pooling to continue 

### ISSUE THREAD

**Issue by CioacaRadu** [VivaPayments/API#2434]
Scenario:

I start a session
I start pooling that session continuously
I abort the session using the API
The session endpoint still returns code 202
I end the pooling due to timeout but not due to abort

Problem: is it normal that after the session is aborted and the POS shows transaction rejected that the session endpoint still returns code 202 (session is still processing) ?

Should it be up to the developers to implement the abort session mechanism on their app? What will happen if the user have insufficient funds or the bank rejects the transaction, will I still get 202, or the case abort case is the only one behaving like this. Let me know.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

Thank you for your message. We would like to inform you that the sessions that for any reason (e.g. timeout) never appeared on the POS device, if you retrieve them, you will constantly get a response "The session is being processed". Each session has a period of around a minute to be processed and complete the transaction. We would like to advise you except of the retrieve session by id to verify your payments via webhooks. More information can be found in the links below:

[Webhooks for payments | Viva Wallet Developer Portal](https://developer.vivawallet.com/webhooks-for-payments/)

[Transaction Payment Created | Viva Wallet Developer Portal](https://developer.vivawallet.com/webhooks-for-payments/transaction-payment-created/)

[Transaction Failed | Viva Wallet Developer Portal](https://developer.vivawallet.com/webhooks-for-payments/transaction-failed/)

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
