### ISSUE TITLE
Unable to get Bank transfer API scope (urn:viva:payments:core:api:banktransfers) via OAuth2

### ISSUE THREAD

**Issue by skuppuraj** [VivaPayments/API#2435]
How to get the scope (urn:viva:payments:core:api:banktransfers) for the Link bank account API via the Oauth2 method?

Already this issue was reported 
https://github.com/VivaPayments/API/issues/2275
The user got the suggestion to use the old API

If I choose for old API, The document says I have to validate IBAN
(It is strongly recommended to first make sure that the IBAN is valid by using the [Validate IBAN])(https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Bank-Account/paths/~1api~1bankaccounts~1ibans~1%7Biban%7D~1validate/get) API call.)

But the link for validating API not working. How to validate?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @skuppuraj,

Thank you for your message. Bank transfer API requires a new set of credentials. Please send us your account Merchant ID to provide them. 
For security reasons we would recommend contacting us via Live Chat or email.

You can send it to the following e-mail: support@vivawallet.com
Please add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by skuppuraj** [comment]
I conducted the support as you requested.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @skuppuraj,

We have received and replied to your email. 
However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by skuppuraj** [comment]
I am facing 401 error

**Comment by VivaWalletCustomerSupport** [comment]
Hello @skuppuraj,

As long as we continue our conversation via email, this ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by skuppuraj** [comment]
https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Bank-Account/paths/~1banktransfers~1v1~1bankaccounts~1{bankAccountId}~1fees/post
I was trying to execute bank transfer API. It asked for the walletID. How do I get that walletID?

I can see there is an API to retrieve Merchant wallet
https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Retrieve-Wallets-and-Transactions/paths/~1merchants~1v1~1wallets/get

But it is in a different scope.

Or can I get a Wallet ID on the account page?

By,
Kuppuraj S




Sent from Outlook<http://aka.ms/weboutlook>

________________________________
