### ISSUE TITLE
Delete webhook registered through ISV webhook endpoint

### ISSUE THREAD

**Issue by pyr0hu** [VivaPayments/API#2436]
Hello!

If we added a few webhooks through the [ISV create webhook endpoint](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Webhooks/paths/~1isv~1v1~1webhooks/post), how can we edit/delete them?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pyr0hu,

Thank you for your message. We would like to inform you that these features will be available soon. We kindly advise you until the release of those features, if you wish to change an existing webhook, please create a new endpoint by using our [create webhook API request](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Webhooks/paths/~1isv~1v1~1webhooks/post).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pyr0hu,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by pyr0hu** [comment]
@VivaWalletCustomerSupport Thanks for the response!

I could create new ones, that's true, but the main issue is that I'd like to disable the existing ones. For example, we have a production and a pre-production environment, but using production viva keys so all purchases go through them. After we've validated the everything works on pre-prod, we have to deploy to prod and enable webhooks on that deployment (which is using different URLs, so new webhooks). But if we enable both webhooks, both environment will handle the notification. We will disable pre-prod until then. Is there any ETA on those API endpoitns?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pyr0hu,

Thank you for your swift response. Unfortunately, we cannot provide a specific timeline of a future release.
We would recommend checking our Release Notes Page for information about the additions and updates to Viva Wallet's products and services. 
https://developer.vivawallet.com/releasenotes/

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by pyr0hu** [comment]
@VivaWalletCustomerSupport

also it is possible to add a webhook twice so a server will receive the webhook twice for example, therefore we couldn't delete/disable one of them

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pyr0hu,

Thank you for the swift response. We would like to advise you to disable the first webhook in your server (if this option exists in your server) until the delete feature is released.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by pyr0hu** [comment]
@VivaWalletCustomerSupport is this feature on the roadmap?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pyr0hu,

Thank you for your message.

To assist you better, please reach out to us via email at [support@viva.com] or via the Live Chat option (which can be found at the bottom-right of the main Viva.com site, or in your Production Viva.com self-care account)

Kind regards,

Viva E-commerce Support Team
