### ISSUE TITLE
Authentication issue on ISV Basic Auth endpoints

### ISSUE THREAD

**Issue by pyr0hu** [VivaPayments/API#2437]
Hello!

We have an issue when we want to use the [Create Transaction](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Recurring-Payments/paths/~1api~1transactions~1{id}/post) or [Retrieve Transaction by Order Code](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Retrieve-Transactions/paths/~1api~1transactions~1?ordercode={ordercode}/get) endpoints.

Both endpoints uses Basic Auth with Reseller Ids. But it's not really straightforward as on the Create Transaction page the documentation says that we have to use Reseller ID and Secret, but under that it says ISV ID and not Reseller ID. The issue is that neither of them works and we cannot authenticate that endpoint.

We've ensured that the transaction is existing (using the retrieve transaction by transaction id endpoint) but that uses OAuth2 and not Basic Auth and that's even using a different API path (`/checkout/v2/isv/transactions` versus `/api/transactions/?orderCode=....`)

How can we make this work?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pyr0hu,

Thank you for your message. Kindly note that the Reseller ID & API Key can only be generated upon request.

To generate the credentials, we need you to tell us the phone number of the Demo ISV account. For security reasons, please send it via email at support@vivawallet.com and add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by pyr0hu** [comment]
@VivaWalletCustomerSupport What is the difference from the Reseller API Credentials which are present on the web interface under API Access?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pyr0hu,

Thank you for your prompt response. We have received and replied to your email as requested.
Can you please clarify if the credentials we sent are the same as the ones from the web interface?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by pyr0hu** [comment]
@VivaWalletCustomerSupport

no, they are different.

web interface:
![image](https://github.com/VivaPayments/API/assets/4921742/1601544b-6490-46e0-bd7c-3b80a20e6cc0)

and the one I got from the support: `0139bdaf-1a...`

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pyr0hu,

Thank you for the confirmation. Please let us know if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
