### ISSUE TITLE
Ηλεκτρονική πληρωμή στο eshop

### ISSUE THREAD

**Issue by foterisn** [VivaPayments/API#244]
Καλησπέρα σας! Είμαι πελάτης σας και διατηρώ eshop όπου γίνονται πληρωμές με vivapayments. Επειδή προχωράμε σε αναβάθμιση σε joomla 3.0, ήθελα να γνωρίζω εάν υποστηρίζετε κανονικά και θα μεταφερθεί ή θα πρέπει εκ νεου να γίνει απο την αρχή εγκατάσταση. www.hellastore.gr

Φωτερής Νικόλαος

**Comment by dmihos** [comment]
Καλησπέρα σας
Αν χρησιμοποιείτε κάποιο έτοιμο plugin για τη διασύνδεση με Viva Payments, θα πρέπει να ρωτήσετε τον κατασκευαστή του plugin.
Αν όχι, και εφόσον ο κώδικας που έχετε γράψει λειτουργεί σωστά, δε θα έχετε κάποιο πρόβλημα με τη διασύνδεση.

**Comment by kostGX** [comment]
Closing as issue over 1 year old.
