### ISSUE TITLE
Error 403 on https://api.vivapayments.com/checkout/v2/orders

### ISSUE THREAD

**Issue by kristofthys** [VivaPayments/API#2441]
In the demo environment, the project is working fine.

In production, Merchant ID 8bca4c0c-03bb-4ff8-9a8b-5bdaed3e90da we get an error 403.

Can this be solved?

Thanks,
Kristof

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kristofthys,

Thank you for your message. 
Kindly note that the [Create payment order API](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post) uses [OAuth2 authentication](https://developer.vivawallet.com/integration-reference/oauth2-authentication/#how-to-authenticate-using-oauth-2-0).
Can you please provide the scope of the access token to further investigate?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by kristofthys** [comment]
The scope received from the token is:
[scope] => urn:viva:payments:core:api:posmanagement urn:viva:payments:core:api:posmanagement:usercodes:verify urn:viva:payments:ecr:api

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kristofthys,

Thank you for your prompt response. As we can observe from the scope, the POS REST API credentials have been used.
We would recommend using the[ Smart Checkout credentials](https://developer.vivawallet.com/getting-started/find-your-account-credentials/client-smart-checkout-credentials/) for the Create payment order API. 

[scope] => urn:viva:payments:core:api:acquiring urn:viva:payments:core:api:acquiring:cardtokenization urn:viva:payments:core:api:acquiring:transactions urn:viva:payments:core:api:redirectcheckout 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by kristofthys** [comment]
Thanks, I'll ask my client to recreate the keys...

**Comment by VivaWalletCustomerSupport** [comment]
Thank you for the update @kristofthys,

In any case, this thread will remain active for at least 24 hours, so that you can come back if you wish.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kristofthys, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
