### ISSUE TITLE
Status Live even if device is powered off

### ISSUE THREAD

**Issue by CioacaRadu** [VivaPayments/API#2443]
Hello, we are integrating the REST API. We noticed that even though the device is powered off ( we are using an android phone ), the REST API on the endpoint: **/ecr/v1/devices:search** still returns the value 1 (Live). .

In the same time, on the viva account I see the device as Online. We can request payments but they fail only due to the 1 minute timeout because obviously no one is paying.

Is this normal? We really need a way to detect when the device is offline and unavailable such that we stop the operations.

Thank you!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

Thank you for your message. Kindly note that our status 1 (Live) on our Devices Search API request means that this POS device has been activated and connected to a Viva Wallet account. The same meaning has the Online field on your Viva Wallet account.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by CioacaRadu** [comment]
Hello @VivaWalletCustomerSupport ,

Thanks for the reply.  We are using REST API for an unattended solution. At the moment do you provide any way to determine if the device is online and ready to do payments ? We want to stop operations if the device is not working or not connected to the internet and switch to cash only.

Regards

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

Thank you for the additional information. We will investigate your query further and let you know as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by CioacaRadu** [comment]
Hello @VivaWalletCustomerSupport , any news on the matter? Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

Thank you for the reply. Your request is still under investigation. We will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

Thank you for waiting. We would like to inform you that our terminals that are supporting REST API are android devices which can be handled like a mobile device. You can search for a Mobile Device Management application which will give you the capability to check if the terminal or our application is turned off/on. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu.

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by CioacaRadu** [comment]
Thanks for the reply. 

This is unfortunate because MDMs require extra costs.

Also I think having a functionality to check if the device is connected to the internet and alive is relevant...

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

Thank you for your reply.  We always consider our customers' feedback for future improvements. We will review your suggestions and possibly it will be available in a future release.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @CioacaRadu,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
