### ISSUE TITLE
Failure Webhook not triggered in demo version

### ISSUE THREAD

**Issue by lebe1** [VivaPayments/API#2444]
Dear VivaWallet team,

I'm sorry to bother you again. This time I try to implement your [Transaction Failed Webhook](https://developer.vivawallet.com/webhooks-for-payments/transaction-failed/) but when I try to trigger it with your [sample failing test cards](https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#test-cards) all I receive is this screenshot below:

![Screenshot from 2023-09-15 15-53-13](https://github.com/VivaPayments/API/assets/38591956/adb753d3-9bb4-46d6-aa9a-d48431f420bc)

So my question is, if it is necessary at all to implement this failure webhook and if it might be triggered at all at some point?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @lebe1,

Thank you for your message. Kindly note that in soft declines the transaction failed webhook is not triggered. We would like to suggest you issue a decline without a decline recovery by following the instructions of the link below:

https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#an-issuer-decline-without-decline-recovery

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by lebe1** [comment]
Hello @VivaWalletCustomerSupport,
thanks for your quick response and your provided link. Next time I'll be reading your docs fully to the end, I promise ;)

**Comment by lebe1** [comment]
Hello @VivaWalletCustomerSupport,
thanks for your quick response and your provided link. Next time I'll be reading your docs fully to the end, I promise ;)
