### ISSUE TITLE
How can we provide port information for success and failure callbacks?

### ISSUE THREAD

**Issue by fasetto** [VivaPayments/API#2446]
How can we provide port information for success and failure callbacks? 
I would like to use the :3000 port for my local environment. Can you help?

![image](https://github.com/VivaPayments/API/assets/20834021/cf005fcf-896e-45c8-ba9d-156fd9f2832a)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fasetto,

Thank you for your message.
Kindly note that the domain URL must use the following format:
If your site uses www: www.yourdomain.com
If your site doesn’t use www: yourdomain.com

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fasetto** [comment]
This is sandbox env. I was wondering, does VivaWallet supports setting port for urls? For my local env. 
Or, do I have to use my dev env for redirects?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fasetto,

Thank you for your reply.
Setting up ports from the domain name is not supported.
Our sources can only use the format mentioned above.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fasetto** [comment]
Okay, I am closing this one. But as feedback, VivaWallet should support this to allow testing on local development environments.
