### ISSUE TITLE
Orders without transactionId

### ISSUE THREAD

**Issue by kristofthys** [VivaPayments/API#2448]
Merchant ID 8bca4c0c-03bb-4ff8-9a8b-5bdaed3e90da
I've received a couple of orders where I get a success redirect without a transactionId.

In the VIVA backend, I can see the client has paid, but using the API, is it possible to retrieve the transactionId using the orderCode?

Is there a way to retrieve transactions by orderCode?
The deprecated GET: GET /api/transactions/?ordercode=... would be convenient.

Is there an alternative?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kristofthys,

Thank you for your message.
Even though the [Retrieve transactions](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)/paths/~1api~1transactions~1{transaction_id}/get) API is deprecated, it is still operational. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by kristofthys** [comment]
I get an authorization denied on this call.

Is the URL correct: eg https://www.vivapayments.com/api/transactions/?ordercode=8964251573819447

I'm using basic auth with VIVAMERCHANTID','8bca4c0c-03bb-4ff8-9a8b-5bdaed3e90da
And the API-KEY from the backend.

Feedback:
Array ( [url] => https://www.vivapayments.com/api/transactions/?ordercode=8964251573819447 [content_type] => application/json; charset=utf-8 [http_code] => 401 [header_size] => 790 [request_size] => 1702 [filetime] => -1 [ssl_verify_result] => 0 [redirect_count] => 0 [total_time] => 0.499066 [namelookup_time] => 0.099885 [connect_time] => 0.105798 [pretransfer_time] => 0.399023 [size_upload] => 0 [size_download] => 61 [speed_download] => 122 [speed_upload] => 0 [download_content_length] => 61 [upload_content_length] => -1 [starttransfer_time] => 0.499047 [redirect_time] => 0 [redirect_url] => [primary_ip] => 104.110.240.26 [certinfo] => Array ( ) [primary_port] => 443 [local_ip] => 185.75.159.88 [local_port] => 51544 [http_version] => 2 [protocol] => 2 [ssl_verifyresult] => 0 [scheme] => HTTPS [appconnect_time_us] => 398951 [connect_time_us] => 105798 [namelookup_time_us] => 99885 [pretransfer_time_us] => 399023 [redirect_time_us] => 0 [starttransfer_time_us] => 499047 [total_time_us] => 499066 ) 
{"Message":"Authorization has been denied for this request."}

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kristofthys,

Thank you for your prompt response.
The URL is correct. The [credentials ](https://developer.vivawallet.com/getting-started/find-your-account-credentials/merchant-id-and-api-key/)can be found from your Viva Wallet account to Settings > API Access in the left navigation menu. We would recommend checking your code once again for errors.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by kristofthys** [comment]
Thanks for confirmation, It works now, ticket can be closed
