### ISSUE TITLE
No confirmation webhooks are sent to me

### ISSUE THREAD

**Issue by edoardodeangelis** [VivaPayments/API#2449]
Hello,

I'm new on VivaWallet.
I try to integrate Smart Checkout into my apps. So far so good but I'm not receiving any webhooks. My configuration is okay and verified by VivaWallet. When I try to pay, the end-user is redirected to my success URL correctly but no webhook is sent to me.

Here are the information: t=73bf4759-c426-498a-a3a1-046ffc24d22e&s=7351471160926008&lang=en-GB&eventId=0&eci=1

Can you help me?

Thank you,

Edoardo De Angelis

**Comment by VivaWalletCustomerSupport** [comment]
Hello @edoardodeangelis,

Thank you for your message.
Did you deploy the desired webhooks? We would recommend following the guide below on how to configure webhooks in your Viva Wallet account.
https://developer.vivawallet.com/webhooks-for-payments/transaction-payment-created/#webhook-configuration

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by edoardodeangelis** [comment]
Hello! Yes, I deployed my webhook, following the guide you gave me. If I try my services, it works. In my demo account, can I see if the webhook was sent to me?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @edoardodeangelis,

Thank you for your prompt response.
Can you please clarify if you are using your Live or your Demo account?
We will also need the Merchant ID of the account and a screenshot from the webhooks tab on Settings - API access menu.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by edoardodeangelis** [comment]
I'm using Demo account. My merchant id is: 4dbee785-55d3-4d60-bdb9-b86fe0c7e388.
This is the service in POST: https://probee.dev.easy4cloud.com/api/pratiche/pagamento-accettato

Thank you,

Edoardo



![Senza titolo](https://github.com/VivaPayments/API/assets/76429238/fe31a445-7e94-415b-bcfc-a88d62ee8b8a)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @edoardodeangelis,

Thank you for your screenshot. Kindly note that the Event Type of the webhook should be Transaction Payment Created. More information can be found [here](https://developer.vivawallet.com/webhooks-for-payments/transaction-payment-created/).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @edoardodeangelis,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @edoardodeangelis,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
