### ISSUE TITLE
Επιτυχή - Αποτυχία ολοκλήρωσης

### ISSUE THREAD

**Issue by helenkat** [VivaPayments/API#245]
Σας χαιρετώ.
Χρησιμοποιώ redirect checkout από την ιστοσελίδα μου (wordpress + woocommerce) στο domain lenagamos.gr.
Οταν ο πελάτης ολοκληρώσει μια επιτυχημένη συναλλαγή, κατευθύνεται στην αρχική μου σελίδα.
Tο ερώτημα είναι:
Οταν γίνει επιτυχημένη ή αποτυχημένη παραγγελία, πως θα μπορούσα να κατευθύνω τον πελάτη και πάλι στην ιστοσελίδα μου σε σελίδα που να λέει οτι έχει κάνει επιτυχή ή αποτυχημένη παραγγελία?

Απο τις πηγές πληρωμών, στα url Επιτυχημένης συναλλαγής και Αποτυχημένης συναλλαγής, έχει και στα 2 πεδία: wc-api=WC_em_Vivapayments_Gateway

Χρειάζεται να αλλάξω κάτι εκεί?

Ευχαριστώ

**Comment by dmihos** [comment]
Καλησπέρα σας
Η σελίδα σας θα πρέπει να κάνει χρήση του νέου SourceCode που έχετε φτιάξει. Πιθανότατα τώρα χρησιμοποιεί sourcecode Default και γι'αυτό ο χρήστης παραμένει σε περιβάλλον Viva Wallet.

**Comment by helenkat** [comment]
Δεν σας είπα οτι παραμένει στο περιβάλλον του viva! 
Εαν θέλετε διαβάστε το αρχικό μηνυμα να δείτε τι σας ρωτάω....
Χρησιμοποιώ το νεο SourceCode που έχω φτιάξει αλλά οτι ρύθμιση και να βάλω, συνεχίζει να πηγαίνει στην αρχική μου σελίδα, ενω θα έπρεπε να πηγαίνει σε συγκεκριμένη σελίδα του site μου και να τον ενημερώνει οτι έχει κάνει επιτυχή ή αποτυχημένη αγορά.

**Comment by dmihos** [comment]
Τότε θα πρέπει να δείτε το θέμα από την πλευρά του site.
Δοκιμάζοντας το url που προκύπτει από το domain σας μαζί με το url επιτυχίας ή αποτυχίας, βλέπουμε ότι μας κατευθύνει σε σελίδα εγγραφής/σύνδεσης (shop/my-account/?msg).

**Comment by kostGX** [comment]
Closing as issue over 1 year old.
