### ISSUE TITLE
Step 7 of viva wallet HTTP ERROR 500

### ISSUE THREAD

**Issue by gsc1ugs** [VivaPayments/API#2450]
At step 7 on this page

https://developer.vivawallet.com/plugins/opencart/#step-1-add-viva-wallet-smart-checkout-plugin-to-your-opencart-store

I get this error... 

Can anyone shed any light why?

![Untitled](https://github.com/VivaPayments/API/assets/11752019/aa73e20c-93b2-48c7-84ce-1e272ef213cf)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

Thank you for your message. Can you please clarify which OpenCart version you are using on the website? Also, can you please send us the name of the zip file you are trying to upload? Thank you in advance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by gsc1ugs** [comment]
OPENCART Version 2.0.2.0

vivawallet.ocmod

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

Thank you for the information. Kindly note that our OpenCart Smart Checkout is available for OpenCart version 3.x.x and above. More information can be found [here](https://developer.vivawallet.com/plugins/opencart/#overview).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by gsc1ugs** [comment]
I see so i need to upgrade?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

Thank you for the reply. We are supporting OpenCart versions 3.x.x and newer. We kindly suggest using an OpenCart version that is compatible with our module.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
