### ISSUE TITLE
Unable to reach Viva Payments

### ISSUE THREAD

**Issue by StefEpic** [VivaPayments/API#2451]
Hello 
I have installed Viva wallet Smart checkout plugin to a WooCommerce site but I am heaving a redirection problem after the checkout page.

I will regenerate the steps .
STEP 1:  Add a product to Cart.
![test 1- KONSTANTINOS TSIGAROS — Mozilla Firefox 1_10_2023 4_58_34 μμ](https://github.com/VivaPayments/API/assets/88728596/482b8f28-6cf1-485e-a1df-b6189515d748)

STEP 2: Product added -> go to checkout
![test 2- KONSTANTINOS TSIGAROS — Mozilla Firefox 1_10_2023 4_59_08 μμ](https://github.com/VivaPayments/API/assets/88728596/04047ef8-242d-40f6-9e0d-19434a27a78d)

STEP 3: Checkout -> Place order
![test 3 - KONSTANTINOS TSIGAROS — Mozilla Firefox 1_10_2023 5_01_31 μμ](https://github.com/VivaPayments/API/assets/88728596/e9f63632-b7a4-409e-bb03-4afa2eadda2b)

STEP 4: ERROR ->SHOULD REDIRECT TO VIVA WALLET FOR PAYMENT
![test 4- KONSTANTINOS TSIGAROS — Mozilla Firefox 1_10_2023 5_01_48 μμ](https://github.com/VivaPayments/API/assets/88728596/8b5b4a9a-89bf-4c55-8333-606a7eb7fca6)

All the plugin setting are correct and have been checked by Viva wallet personnel.
After contacting my hosting provider  (for IP firewall restrictions) I can provide you with the following error log:

AH01071: Got error 'PHP message: WC_VIVAWALLET::generate_form\nCode:401\n Error:UnauthorizedPHP message: PHP Fatal error: Uncaught Exception: Unable to reach Viva Payments (401 -- Unauthorized) in /var/www/vhosts/konstantinostsigaros.gr/httpdocs/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php:378\nStack trace:\n#0 /var/www/vhosts/konstantinostsigaros.gr/httpdocs/wp-content/plugins/vivawallet-woocommerce-gateway/wc-vivawallet.php(496): WC_VIVAWALLET->generate_form(2131)\n#1 /var/www/vhosts/konstantinostsigaros.gr/httpdocs/wp-includes/class-wp-hook.php(310): WC_VIVAWALLET->receipt_page(2131)\n#2 /var/www/vhosts/konstantinostsigaros.gr/httpdocs/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array)\n#3 /var/www/vhosts/konstantinostsigaros.gr/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#4 /var/www/vhosts/konstantinostsigaros.gr/httpdocs/wp-content/plugins/woocommerce/templates/checkout/order-receipt.php(44): do_action('woocommerce_rec...', 2131)\n#5 /var/www/vhosts/konstantinostsigaros.gr/httpdocs/wp-content/plugins/woocommerce/includes/wc-core-funct...', referer: https://www.konstantinostsigaros.gr/checkout/

Any suggestion will be helpful.
I can provide you more information's and access to backend if needed.
Thanks In advance.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @StefEpic,

Thank you for your message. I would like to inform you that your requests have been rejected for security reasons. This is can happen if our system identifies your requests as suspicious. We kindly recommend checking for any restriction rules for server-to-server requests. We kindly recommend contacting your hosting provider. Also, you should check your CDN/website settings. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @StefEpic,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @StefEpic,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
