### ISSUE TITLE
getBearerAuthentication forbiden

### ISSUE THREAD

**Issue by 12mantis12** [VivaPayments/API#2452]
Hi i recently installed vivawallet smart checkout 1.0.4 for prestashop.

I complete all the steps for installation and account creation and when i enter the prestashop client id and client secret i get an error that  it could not connect check the credentials. 

The log says: Domain=.vivapayments.com; Path=\\/; Expires=Tue, 03 Oct 2023 09:35:26 GMT; Max-Age=7200; Secure; HttpOnly\"]},\"errorMessage\":\"403-Client error response [url] https:\\/\\/accounts.vivapayments.com\\/connect\\/token [status code] 403 [reason phrase] Forbidden\"},\"category\":\"vivaPayments\"}

I have prestashop 1.7.8.8
Module 1.0.4
PHP 7.4.3.3

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @12mantis12, 

Thank you for your message. Please make sure you used the correct [PrestaShop Credentials
](https://developer.vivawallet.com/plugins/prestashop-smart-checkout/#step-2-generate-prestashop-credentials)and try again. Also, send us a screenshot of the newly generated Logs.

If issue persists, could you please share with us your domain URL and the Merchant ID of your Viva Wallet account?
You can share it here or at support@vivawallet.com 
Please add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @12mantis12,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @12mantis12,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
