### ISSUE TITLE
How to test Transaction Failed webhook

### ISSUE THREAD

**Issue by edoardodeangelis** [VivaPayments/API#2455]
Hello, I tried to test the Transaction Failed webhook using https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#trigger-a-decline: but all cards give me a Transaction Payment Created. What am I doing wrong?

Thank you,

Edoardo De Angelis

![Image](https://github.com/VivaPayments/API/assets/76429238/7b2c0e8f-d636-4b3f-9997-9b6f6bd46d8d)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @edoardodeangelis,

Thank you for your message.
Kindly note that to trigger the Transaction Failed webhook you must simulate declines by creating payment orders with a [specific amount.](https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#an-issuer-decline-without-decline-recovery) 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by edoardodeangelis** [comment]
Ok, thank you!
