### ISSUE TITLE
VIVA WALLET - NO CALLBACKS OR DESCRIPTION

### ISSUE THREAD

**Issue by gsc1ugs** [VivaPayments/API#2459]
I also need help with callback please, i notice my sales list was empty after the transaction, i have set my account to redirect now will that fix it? description doesnt give product and OPENCART sales is empty, this use to work with PAYPAL

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

Thank you for your message. Can you please send us a screenshot from the plugin settings and the source settings?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by gsc1ugs** [comment]
See attached 
![pluginopencart](https://github.com/VivaPayments/API/assets/11752019/f5c19240-b721-46af-8ac9-c097a128d1ae)
![sourcesettings](https://github.com/VivaPayments/API/assets/11752019/1f59be21-3cfa-4148-b783-8330709108d1)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

Thank you for your prompt response. Please use the following successful and failed transaction URL's:

Successful Transaction URL: index.php?route=extension/payment/vivawallet/callback&success	
Failed Transaction URL: index.php?route=extension/payment/vivawallet/callback&fail

Also, add the source's 4-digit code to the plugin settings.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by gsc1ugs** [comment]
Yes it works thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
