### ISSUE TITLE
ERROR DOING REFUND

### ISSUE THREAD

**Issue by gsc1ugs** [VivaPayments/API#2460]
Error! Your available wallet balance is not sufficient in order to perform the specific refund. Available wallet balance: 3.36 euro. (Error code 452)

If total was £3.68

1. Why do i get that error 
2. It says euros?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

As we can observe the requested refund amount exceeds the available amount in your account. Please consider adding funds to your account to continue with your refund.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by gsc1ugs** [comment]
What if the total transaction was £3.68? see pic
![refunderr](https://github.com/VivaPayments/API/assets/11752019/9cb2a903-eb22-43fc-933d-5ad780d5c84b)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

Thank you for your message. In that case you will need at least 3.68 GBP into your account to procced with the refund. The fee will be returned but you need sufficient funds to authorize the refund.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by gsc1ugs** [comment]
If the transaction needs cancelling what as happened the to charge on that £3.68 if it requires cancelling?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

Thank you for your prompt response. You need sufficient funds into your account to authorize refunds. You will not be charged with the fee, it will be refunded.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by gsc1ugs** [comment]
"You need sufficient funds into your account"

What im saying is, that transaction was the first made, the account is brand new with VIVA thats why im puzzled it couldn't be cancelled

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

Thank you for your message. 
In every settled transaction a fee is included. In your case the 3.68 GBP amount includes a 0.32 GPB fee.
The new balance after the settlement is now 3,36 GBP which is lower than the 3.68 GBP you requested to be refunded.
Once your account receives funds over the amount of 3.68 GBP the refund request will be able to procced.
Note that you will not be charged with the fee of the refunded transaction; it will be refunded to your account balance. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @gsc1ugs,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
