### ISSUE TITLE
Response from payment and other Cloud REST API questions.

### ISSUE THREAD

**Issue by AntonKankkunen** [VivaPayments/API#2462]
Is it possible to get a response for a processed payment when I first initiate a payment request to my terminal, and then customer pays?
I know I can retrieve the sessions info and see if it was successful, but I would like to be able to get that info in almost real-time. Is it possible somehow, maybe with webhooks?
Then if it’s not possible, is there a limit how many request can I send and how fast, to check if the payment has been made? Let’s say I send a status check in every 5 seconds around the clock for 100 different terminals, is that possible?
The product I am trying to produce would work something like this:
1. I initiate a payment request for x amount.
2. User pays -> automatically request new payment for x amount.
3. No one pays = timeout -> automatically request new payment for x amount.

Also is it possible to modify the time before it times out, maybe even disable the timeout entirely?

Thank you for the response in advance!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AntonKankkunen,

Thank you for your message. We would like to suggest you using our [Transaction payment created](https://developer.vivawallet.com/webhooks-for-payments/transaction-payment-created/) and [Transaction Failed ](https://developer.vivawallet.com/webhooks-for-payments/transaction-failed/) webhooks to verify your payments. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AntonKankkunen** [comment]
Thank you!
Is there anyway to get rid of the timeout on the terminal? Or perhaps add more time to how long it requests the payment?
Our idea is to have it pending for x amount payment basically 24/7. 
Perhaps you have some ideas to how to approach this.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AntonKankkunen,

Thank you for your prompt response. We would like to inform you that the timeout of the terminal is predefined and cannot be modified.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AntonKankkunen,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AntonKankkunen, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
