### ISSUE TITLE
Demo Payments not Working properly

### ISSUE THREAD

**Issue by IliasStathakopoulos** [VivaPayments/API#2463]
I am trying to make a transaction with demo account , and after i fill the test card details , i am redirecting  to https://demo.vivapayments.com/web2/fail

**Comment by VivaWalletCustomerSupport** [comment]
Hello @IliasStathakopoulos,

Thank you for your message. Can you please share with us an order code so we can investigate your issue further?

Kind regards,
Viva Wallet E-commerce Support Team
