### ISSUE TITLE
Test fail scenarios for reccuring payments

### ISSUE THREAD

**Issue by ThetripGr** [VivaPayments/API#2466]
Hello , 

I created a demo recurring payment using the sandbox account card. But i can't seem to be able to test this payment for failed scenarios such as , not having enough balance available. The transaction seems to always be a success . I even tried changing the amount charged to something a lot bigger from 10 to 100 and it still goes throught as a succesfull transaction. 

How do i test these scenarios on a recurred payment from a sandbox account?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ThetripGr,

Thank you for your message. Kindly note that if you wish to issue a decline in the demo environment you should use an amount from 99.01 € to 99.98 €. More information can be found in the link below:

https://developer.vivawallet.com/integration-reference/test-cards-and-environments/#an-issuer-decline-without-decline-recovery

Kind regards,
Viva Wallet E-commerce Support Team
