### ISSUE TITLE
Front office payment options / auto language change not working

### ISSUE THREAD

**Issue by DPStudioGR** [VivaPayments/API#2469]
Hi there...
I have installed viva wallet standard checkout to 3 different prestashop installations all 1.7.8.10
And in the modules admin enviroment i have added the description for customers in Greek "Pay with card, visa mastercard"
The module is working but when a customer 's browser is in english the description in payment option page stays in Greek ...
Shouldn't there be an option when setting up the module to add all active descriptions ...
Also a logo?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Stampa-Stampa,

Thank you for your message. We would like to advise you that you can translate the description of the module by using a translation module. About the logo, this feature is not yet available. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by DPStudioGR** [comment]
Hi there...  I am anot a pro developer but i know that Prestahop offers the option to translate all frontoffice and backoffice text through its internal translation ... For this to happen the develoepr has to have translation sheet ..
Your translation sheet although exist are missing the cart expressions..

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Stampa-Stampa,

Thank you for your response. We would like to inform you that at the moment there is only a description field in the module's settings which applies to all languages. We always consider your comments for future improvements. We will review your request about adding a different field for each language.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Stampa-Stampa,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Stampa-Stampa,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
