### ISSUE TITLE
Χρέωση πιστωτικών καρτών ξένου νομίσματος

### ISSUE THREAD

**Issue by melcon77** [VivaPayments/API#247]
Αφορά www.boatscan.com (για API Native Checkout)

Καλησπέρα σας,
Ας υποθέσουμε π.χ. ότι ένας πελάτης μας έχει πιστωτική κάρτα που έχει εκδοθεί από ίδρυμα στις ΗΠΑ και χρεώνει σε Δολάριο, αγοράζει κάποιες υπηρεσίες από το website μας αξίας π.χ. € 100 και πάει να πληρώσει  μέσα από το site μας σε ΕΥΡΩ (API Native Checkout). Αυτό που τελικά θεωρούμε ότι θα συμβεί είναι να ζητηθεί από την ViVa η χρέωση της πιστωτικής κάρτας για € 100, η εκδότρια Τράπεζα της πιστωτικής κάρτας θα χρεώσει το παραπάνω ποσό στην κάρτα σε Δολάριο με κάποια ισοτιμία €/$ (π.χ. 1,06  --> $ 106) καθώς επίσης και ίσως να χρεωθούν από την χειρίστρια τράπεζα της πιστωτικής κάρτας έξοδα μετατροπής νομίσματος. Τελικά θα πιστωθούν στον δικό μας λογαριασμό € 100 (μείον την προμήθεια της Viva).
Το ερώτημα εδώ είναι αν μπορούμε να έχουμε από εσάς (μέσω API) την ακριβή ισοτιμία που θα χρησιμοποιηθεί για την χρέωση της κάρτας, ένα βήμα πριν ο πελάτης πατήσει την οριστική χρέωση της. Το θέλουμε για να γνωρίζει από πριν ο μη Ευρωπαίος πελάτης το ακριβές ποσό που θα χρεωθεί η πιστωτική του κάρτα.
Σας ευχαριστούμε εκ των προτέρων.
Μ.Κώνστας

**Comment by dmihos** [comment]
Καλησπέρα σας
Δυστυχώς δεν υπάρχει διαθέσιμη τέτοια υπηρεσία.
Ευχαριστούμε για την επικοινωνία

**Comment by melcon77** [comment]
Ευχαριστούμε πολύ για την απάντηση.
Η διαδικασία της πληρωμής από πιστωτική κάρτα σε δολλάριο που περιγράφω παραπάνω είναι σωστή?

**Comment by dmihos** [comment]
Το currency conversion είναι αρκετά περίπλοκο θέμα κατά την εκτέλεση μιας συναλλαγής.
Στο θέμα που σας αφορά, σαν έμπορο πάντως, ισχύει ότι οι εκκαθαρίσεις γίνονται σήμερα σε Ευρώ, οπότε θα παίρνετε πάντα το ποσό που ζητήσατε (100€) μείον τις προμήθειες της Viva.
Τα conversion fees δε σας επηρεάζουν.
