### ISSUE TITLE
Error on WooCommerce checkout 

### ISSUE THREAD

**Issue by crontos** [VivaPayments/API#2470]
Hello, At checkout it shows the following error:
![checkout](https://github.com/VivaPayments/API/assets/150293153/36186e64-5c0f-47a5-b889-34f23074bc1d)

**Viva Wallet: The source code is not set. Review the documentation and complete the Viva Wallet gateway settings.**

Until recently we were accepting payments normally

What exactly do we need to fill in and where? Thanks.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @crontos, 

Thank you for your message. 
Could you please share the [latest Logs](https://help.vivawallet.com/en/articles/5126216-where-i-can-find-the-logs-for-the-viva-wallet-for-woocommerce-plugin) from the plugin and the URL of the website?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by crontos** [comment]
Καλημέρα σας,
Στα logs δεν μας εμφανίζει κάτι που να αφορά το plugin της VIVA,
![Κατάσταση-WooCommerce-‹-Bizouvio-—-WordPress](https://github.com/VivaPayments/API/assets/150293153/fd122f77-4683-4a55-994e-0ec97730898e)

Το plugin δούλευε κανονικά μέχρι προχθές, μήπως παίζει ρόλο το update που έγινε στο WordPress στην 6.4;

Το site είναι το https://bizouvio.gr/

**Comment by VivaWalletCustomerSupport** [comment]
Hello @crontos,

Thank you for your prompt message.
What is the version of your plugin? Please make sure you have the[ latest](https://woo.com/document/viva-wallet-standard-checkout/) one installed.
If issue persists after updating, new logs should be generated.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by crontos** [comment]
The version is 1.4.10

What should we do exactly?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @crontos,

Thank you for your swift response.
After clicking on save changes on the plugin settings new logs will be generated. 
The logs should look like this: wc-vivawallet-native followed by the date.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by crontos** [comment]
Seems to work,
Did you take any action?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @crontos,

Thank you for your message. No further action was taken on our part. it might be a problem with your website or hosting provider.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @crontos,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @crontos,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
