### ISSUE TITLE
support for magento 2.4.6 php 8.2

### ISSUE THREAD

**Issue by agelospanagiotakis** [VivaPayments/API#2472]
does the current plugin support  magento 2.4.6 with php 8.2 ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @agelospanagiotakis,

Thank you for your message. 
Our plugin for Magento supports versions 2.3.X & 2.4.X and a minimum of PHP 8.1 version.
Additional information can be found [here](https://help.vivawallet.com/en/articles/4911024-integrating-viva-com-with-magento-smart-checkout-plugin).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by agelospanagiotakis** [comment]
No it does no seem to be compatible with php 8.2
also in the link you provided link to the download page(Download [magento_vivawallet.zip](https://developer.vivawallet.com/downloads/magento23_vivawallet.zip?_gl=1*1m85ucb*_ga*MjA0NjA5NTkzNi4xNzAwMjEwOTk1*_ga_MV5MJ2V3SZ*MTcwMDIxMDk5NC4xLjEuMTcwMDIxNTMzNi42MC4wLjA.) to your desktop.)  that gives 404 error.
 
1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Ced\VivaPayments\Controller\Checkout\Start\Interceptor::$_paymentMethod is deprecated in /home/stagekois/domains/stage.kois-optics.gr/public_html/app/code/Ced/VivaPayments/Controller/Checkout/Start.php on line 29

Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Ced\VivaPayments\Controller\Checkout\Start\Interceptor::$_paymentMethod is deprecated in /home/stagekois/domains/stage.kois-optics.gr/public_html/app/code/Ced/VivaPayments/Controller/Checkout/Start.php on line 29
<pre>#1 Ced\VivaPayments\Controller\Checkout\Start->__construct() called at [generated/code/Ced/VivaPayments/Controller/Checkout/Start/Interceptor.php:14]
#2 Ced\VivaPayments\Controller\Checkout\Start\Interceptor->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#3 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#4 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#5 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/App/ActionFactory.php:44]
#6 Magento\Framework\App\ActionFactory->create() called at [vendor/magento/framework/App/Router/Base.php:306]
#7 Magento\Framework\App\Router\Base->matchAction() called at [vendor/magento/framework/App/Router/Base.php:167]
#8 Magento\Framework\App\Router\Base->match() called at [vendor/magento/framework/App/FrontController.php:144]
#9 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#10 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#11 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#12 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#13 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:75]
#14 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#15 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#16 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#17 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#18 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#19 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]

**Comment by VivaWalletCustomerSupport** [comment]
Hello @agelospanagiotakis,

Thank you for your prompt response.
You can use the following [steps to download](https://developer.vivawallet.com/plugins/magento/#step-1-add-viva-wallet-smart-checkout-plugin-to-your-magento-store) the plugin. 
Kindly note that an updated version of the plugin will be released soon. Unfortunately, we cannot provide a specific date of the release, but you can check the [release note page](https://developer.vivawallet.com/releasenotes/). 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @agelospanagiotakis,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @agelospanagiotakis,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by heisenbol** [comment]
For anyone reaching this issue:
as @agelospanagiotakis already explained, the plugin does not work with PHP 8.2. It produces exceptions like
`main.CRITICAL: Exception: Deprecated Functionality: Creation of dynamic property Ced\VivaPayments\Controller\Checkout\Start\Interceptor::$_paymentMethod is deprecated in /xxxxxx/app/code/Ced/VivaPayments/Controller/Checkout/Start.php on line 29 in `

This started with PHP 8.2 

To mitigate (till this "new viva plugin version" is out), you have to add AllowDynamicProperties to all classes under Ced/VivaPayments . Something like this

```
#[\AllowDynamicProperties]
class Start
{........
```

Or get back to PHP 8.1
