### ISSUE TITLE
AP Concert ECR Integration Protocol.

### ISSUE THREAD

**Issue by RembarZer** [VivaPayments/API#2473]
Hello, I am working on Android app integration, that's ok.
Now I would like to know how to connect with "AP Concert ECR Integration Protocol" to use the Concert 3 protocol that I already got on our Windows software version.

From your developer portal, I See that the "AP Concert ECR Integration Protocol" is linked in "Card Terminal Devices".
Does Concert 3 protocol will only work with Pax devices and/or a different app ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @RembarZer ,

Thank you for your message. We would like to inform you that [AP Concert ECR Integration Protocol](https://developer.vivawallet.com/apis-for-point-of-sale/card-terminals-devices/-ap-concert-ecr-integration-protocol/) is available for Android PAX POS devices.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by RembarZer** [comment]
OK thanks for that quick response.
Are PAX POS devices working with viva.com | Terminal app ? Allowing them to pay by intent from app to app AND also with Concert 3.1 (IP and custom Port) linked to a Windows app ?

Have a good day.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @RembarZer ,

Thank you for your response.
PAX devices can be used for APP to APP integrations. Additional information in the link below:
https://developer.vivawallet.com/apis-for-point-of-sale/card-terminal-apps/android-app/sale/#overview

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @RembarZer, 

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @RembarZer,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
