### ISSUE TITLE
OAuth 2.0 Authorization Code Flow

### ISSUE THREAD

**Issue by Naaikho** [VivaPayments/API#2474]
Hello,

I wanted to know if your **OAuth 2.0** authorization system also has an **Authorization Code Flow**?
I took a long look at your API documentation but couldn't find anything about it, maybe I wasn't looking in the right place?
I would like to make it possible to connect a user without them having to enter their `ClientID` and `ClientSecret` themselves.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Naaikho,

Thank you for your message. Kindly note that Authorization Code Flow is not supported, the ClientID and ClientSecret must be used to OAuth 2.0 authentication.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Naaikho** [comment]
And do you plan to implement it at some point?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Naaikho,

Thank you for your suggestion. We always consider our customers' feedback for future improvements. We will review your request and possibly, it will be available in a future release.

Kind regards,
Viva Wallet E-commerce Support Team
