### ISSUE TITLE
Testing Android integration using developer account

### ISSUE THREAD

**Issue by vzv111** [VivaPayments/API#2478]
Could you tell me if it is possible to test the Android integration on the developer account?

I am using the Sunmi V2s to test the integration from my Android application via intents to the Viva Terminal Payment app. I have downloaded the Viva Terminal Payment from the Sunmi store.

However the application will only let me log in using my real account. Is there a way to use the Viva app with a developer account?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vzv111, 

Thank you for your message. You can create a demo Viva account and download the demo APP to run your tests. We will have to whitelist your email to access the demo app. Please a share a gmail account address to proceed. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by vzv111** [comment]
Thank you for your response. I have requested my Gmail account to be added via chat.

I believe the instructions for the demo account is at the following URL:

https://developer.vivawallet.com/getting-started/download-demo-pos-app/#overview-and-pre-requisites

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vzv111, that is correct.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @vzv111,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
