### ISSUE TITLE
PHP Webhook Example ?

### ISSUE THREAD

**Issue by nsiatras** [VivaPayments/API#2479]
Hello,

I am trying to create a webook for the "Transaction Payment Created" event.

Do you have any example code written in PHP ?

**Comment by nsiatras** [comment]
I used the ASP .NET code you have available and I wrote a PHP code in order to read the WebHook incoming data.

You can now close this issue.

```
if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
    $strData = file_get_contents('php://input');
    //file_put_contents('log.txt', "$strData", FILE_APPEND | LOCK_EX);
    
    // This array holds the incoming data
    $json = json_decode($strData);

    $eventTypeID = $json->EventTypeId;
    $amount = $json->EventData->Amount)
    $orderCode = $json->EventData->OrderCode;

    // Payment Received Event
    if ($eventTypeID == 1796)
    {
        // Order is now paid !
        // Mark your order as paid to your database and send email to your client
    }
}
```

**Comment by VivaWalletCustomerSupport** [comment]
Hello @nsiatras, 

Thank you for your message. This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
