### ISSUE TITLE
ΠΡΟΒΛΗΜΑ ΜΕ ΣΥΝΑΛΛΑΓΗ

### ISSUE THREAD

**Issue by sampanis** [VivaPayments/API#248]
Καλησπέρα, έχω συνδεμένο το vivawallet στο ηλεκτρονικό μου, κατάστημα inktoner.gr, κάποιος πελάτης προσπαθεί να περάσει μια συναλλαγή, αλλά ενώ περνάει τα στοιχεία της κάρτας κανονικά, χωρίς να του βγάλει κάποιο σφάλμα, η συναλλαγή δεν ολοκληρώνεται. Του έστειλα και ειδοποίηση πληρωμής και πάλι δεν ολοκληρώνεται.  Κωδικός Πληρωμής 	1615711334872606. Για δείτε λίγο τι γίνεται.

**Comment by dpnevmatikos** [comment]
Καλημέρα @sampanis ,
Δυστυχώς δεν υπάρχει καμιά καταγραφή αποτυχημένης συναλλαγής στο σύστημα μας για τον κωδικό παραγγελίας που μας στείλατε.

Μπορείτε να μας δώσετε περισσότερες πληροφορίες σχετικά με την αποτυχία ολοκλήρωσης της συναλλαγής ? Αν κρίνετε χρήσιμο, μπορείτε να μας στείλετε και κάποιο screenshot στο merchants@vivawallet.com τη στιγμή της πληρωμής.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
