### ISSUE TITLE
Device activation

### ISSUE THREAD

**Issue by j-agathos** [VivaPayments/API#2480]
We cant login after OTP the application is not responding after submit, check the attachment.
When we try to activate the device with device code we get a suceess message at https://demo.vivapayments.com/selfcare/el/sales/devices but no terminal actualy saved and at the device all steps finish and all privillages are granded at the last tap (open terminal app) we get an error message that the activation is failed and we logged out.
![Screenshot_20240109_131218_Chrome](https://github.com/VivaPayments/API/assets/20618703/a8d58c7b-01ea-4f2d-9d5f-970ae077fd36)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @j-agathos,

Thank you for your message. Kindly note that in DEMO environment the 6-digit OTP is always the same: 111111.
Additional info on how to activate devices [here](https://developer.vivawallet.com/tutorials/pos-terminals/activate-pos-devices/#android-ios). 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by j-agathos** [comment]
Yes i know that, when i enter the OTP the app does nothing.
Please check the two videos

https://github.com/VivaPayments/API/assets/20618703/c17be988-3b8b-4eb4-8289-eb02af5801ca

https://github.com/VivaPayments/API/assets/20618703/8acf662f-d035-4b8b-9c5f-3425be966e54

**Comment by VivaWalletCustomerSupport** [comment]
Hello @j-agathos,

Thank you for the videos. 
Can you please click on the info button on the top right corner and provide the terminal ID?
We will also need the Merchant ID of your demo account. 
We would recommend uninstalling and reinstalling the app then try again. Also make sure the terminal is not already activated. 

Kindly note that the activation method by logging in as shown in the second video is not working on demo accounts. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by j-agathos** [comment]
Terminal ID: fwnPpDc9TdO0etldLSyjl78
Merchant ID: 1037aa7b-ea60-41cf-88ff-d3a6c5728e38
Source Terminal ID: 

at terminal id i dont know if it is the lowercase letter L or uppercase letter i after t and j
we already uninstall and re install the app many times.
we never accomplish to activate a demo terminal and at the [Card Terminals](https://demo.vivapayments.com/selfcare/en/sales/devices) we have zero records

**Comment by VivaWalletCustomerSupport** [comment]
Hello @j-agathos,

Thank you for your swift reply. We are currently investigating your issue. We will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @j-agathos,

Make sure you are using the latest DEMO APP version and you are trying the Activation method via Activation Code.
The device will then display a 9-digit activation code. 
To proceed log into your DEMO Viva self-care account and navigate to Sales > Physical Payments > Card Terminals:
you will then need to enter the code within your self-care account.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by j-agathos** [comment]
We unistall it and install it again right now from https://play.google.com/store/apps/details?id=com.vivawallet.spoc.payapp.demo
We did again all steps and gave all privillages and again the same thing
You can check at the fourth second of IMG_0003_1.mp4 video that we do the Activation Code method correctly.
At DEMO Viva self-care account on Sales > Physical Payments > Card Terminals page we have zero records despite our tries, is this normal?

**Comment by VivaWalletCustomerSupport** [comment]
Thank you for the additional info.

Between the third and fourth second the 9-digit code briefly appeared. Did you manage to add it successfully into your DEMO Viva self-care account by navigating to Sales > Physical Payments > Card Terminals and clicking on the green button "New Card Terminal" to enter the code?

If so, and issue persist could you please share another video showing the process followed to the terminal and demo viva account? 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by j-agathos** [comment]
From our DEMO Viva self-care account (Sales > Physical Payments > Card Terminals) the activation process run but does not store the terminal.

https://github.com/VivaPayments/API/assets/20618703/9c6a40a3-f0dd-4583-9aa1-c2a660dea3e7

**Comment by VivaWalletCustomerSupport** [comment]
Hello @j-agathos,

Thank you for the video. We will further investigate the issue. We will inform you as soon as we have any update.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @j-agathos,

We would recommend testing it with another device. In case the issue persists please create a new Demo account and try again. 
Kindly note that you can also use a "dummy" mobile number to create a Demo account.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by j-agathos** [comment]
With another device we had the same issues. we create a new demo account and it works, please check our account to solve this issue because at the old account we have all the credentials and also have a purple account

**Comment by VivaWalletCustomerSupport** [comment]
Hello @j-agathos,

Thank you for the update. Kindly note that your demo account was created back in 2018. New additions and updates were not included to old accounts. We would like to recommend using your newly created demo account for a seamless experience. 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @j-agathos,

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @j-agathos,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
