### ISSUE TITLE
Trigger "Transaction Payment Created" webhook for e-banking/DIAS payment?

### ISSUE THREAD

**Issue by jfeid** [VivaPayments/API#2481]
Hi,

Is there a way to trigger a "Transaction Payment Created" webhook for e-banking/DIAS payment in demo environment?

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @jfeid 

Thank you for your message. Kindly note that there isn't, DEMO environment  for  e-banking/DIAS .
Additional info can be found [here](https://developer.vivawallet.com/payment-methods/direct-debit-other/ebanking/#how-to-activate-e-banking-διασ-dias).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by jfeid** [comment]
Thanks for the prompt answer
