### ISSUE TITLE
No payment methods available.

### ISSUE THREAD

**Issue by onuproy** [VivaPayments/API#2482]
Hey,

Enable Viva Wallet Smart Checkout and connect:

https://prnt.sc/iJ6BV9MQplGO

But, There are no payment methods available. This may be an error on our side. Please contact us if you need any help placing your order.
See here: https://prnt.sc/Pbqg-0t1dcJz

How can solve this?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @onuproy, 

Thank you for your message. 
As we can observe from the screenshot, the checkout page uses a block-based layout. The specific way of building the checkout page may create a conflict with our plugin, that is, the form sections 1, 2, 3, 4 that have been created. Please try to structure the checkout page in a different way and our payment method should appear.
We would recommend switching to classic checkout or use a default theme that is not block-based.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by onuproy** [comment]
Hey,
Thanks for reply.

I didn't use block-based theme,
This is the default checkout layout of eCommerce.

Can you suggest a classic checkout,

Thanks!
