### ISSUE TITLE
Marketplace - multiple items in a single order possible?

### ISSUE THREAD

**Issue by AnastasiosHJW** [VivaPayments/API#2488]
Hello

When using the Marketplace API, and creating a new order, is there a way to have multiple separate items in a single order? As a very rough example, in the Smart Checkout something like this would appear:

![viva1](https://github.com/VivaPayments/API/assets/5028948/c41a2755-0f00-4cac-a6b9-517042dcb0e8)

So instead of treating the entire order as one item, the customer can see each individual item priced out.
In addition to that, when using the Marketplace, how will the sellers issue the receipts for these items to the customer? Since there is no POS involved and every transaction is made online. Is this something that Viva offers a way to, or will each seller have to create and send the receipt outside of the Marketplace platform?

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AnastasiosHJW,

Thank you for your message. 
Kindly note that this feature is not available, apologies for the inconvenience.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AnastasiosHJW** [comment]
Thank you for the reply. Regarding the receipts, i assume it is also not a feature that is present for Marketplace? So the individual sellers would be responsible for issuing the receipts outside the platform, or at least without the use of the Viva API?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AnastasiosHJW,

Thank you for your message.
Exactly, its seller is responsible for issuing the receipts.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by AnastasiosHJW** [comment]
Thank you for the clarifications.
