### ISSUE TITLE
There was a problem creating hooks for your website. Make sure that your site is public accessible. (PRESTASHOP)

### ISSUE THREAD

**Issue by kanikbeatweb** [VivaPayments/API#2489]
When i click the save button on Viva.com | Smart Checkout Module. I get an error in a red box : 

There was a problem creating hooks for your website. Make sure that your site is public accessible.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kanikbeatweb,

Thank you for your message. Could you please share a screenshot of the error and the URL of the website?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by kanikbeatweb** [comment]
The URL of the website is : https://grafiki-books.gr/eshop/
![Screenshot 2024-02-08 195355](https://github.com/VivaPayments/API/assets/159443216/7caee704-75d9-45a7-a195-a4603317de8b)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kanikbeatweb,

Thank you for your prompt response. Make sure you are using the[ latest version](https://addons.prestashop.com/en/payment-card-wallet/89363-viva-wallet-smart-checkout.html) of the plugin. 

Also, make sure you are using the correct credentials.  Go to Settings > API Access and scroll down to the PrestaShop Credentials section and generate new if needed.

If issue persists, please share the latest error logs under Advanced Parameters - Logs tab.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by kanikbeatweb** [comment]
Hello, I use the latest version of the plugin. I also generated new credentials. 

When i hit the save button i get the following errors.
![Screenshot 2024-02-09 143114](https://github.com/VivaPayments/API/assets/159443216/9ac5c166-6415-438e-b12d-c28fed57e304)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kanikbeatweb,

Thank you for the Logs. As we can observe you are getting 400 and 502 errors. 
That means the something in your website or server settings is triggering our server to block you. We would recommend checking your server settings for errors and contact your hosting provider and ask them to check if there is any restriction rule or a misconfiguration for server-to-server requests. The use of VPN/PROXY or a debugging mode being ON may also trigger this error.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kanikbeatweb, 

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kanikbeatweb, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
