### ISSUE TITLE
How to verify a webhook notification

### ISSUE THREAD

**Issue by sksksksk** [VivaPayments/API#249]
This is similar to issue #242 but I want to be sure that I am not missing something.

Using a webhook, I get a bunch of information about a transaction. How can I verify that this is a legitimate request from viva, and not a malicious one? There are no checksums in the posted information, so I can't really be sure that the request is legitimate.

Do I have (again) to make an API call to make the verification?

**Comment by dmihos** [comment]
There is no checksum/signature, you are right. We intend to address the issue in the future.
Meanwhile, you'll have to call the API for verification.

**Comment by kostGX** [comment]
Closing as issue over 1 year old.
