### ISSUE TITLE
Oauth authentification

### ISSUE THREAD

**Issue by mikaelcarlavan** [VivaPayments/API#2490]
Hi guys,

I'm trying to use the API to create payment but I am stuck with the Oauth authenfication.
I downloaded the request from Postman, used my Smart Checkout Credentials but it is not working, I always get "invalid_client".

Here is the request :
curl -L -X POST 'https://demo-accounts.vivapayments.com/connect/token' \
 -H 'Content-Type: application/x-www-form-urlencoded' \
 -H 'Authorization: Basic XXX' \
 --data-urlencode 'grant_type=client_credentials'

Any ideas ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mikaelcarlavan, 

Thank you for your message. You can follow this [guide](https://developer.vivawallet.com/integration-reference/oauth2-authentication/#how-to-authenticate-using-oauth-2-0) to create an access token. Make sure you used the correct credentials.

After the creation of the access token, the last step is to generate an order code. For the order code creation you will make another[ API request](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post).

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by mikaelcarlavan** [comment]
Hello,

I followed your guide but it is still not working. 
I also tried all the possible credentials without success.
Seems like severals issues are related to the same problem : for ex #2404 #2159 #1428

**Comment by mikaelcarlavan** [comment]
Ok, seems like the demo endpoint only works with the sandbox account.
Problem solved.
