### ISSUE TITLE
merchantReceiptText/cardholderReceiptText in Sale request (Viva Terminal app integrations)

### ISSUE THREAD

**Issue by SamuelMichelRiad** [VivaPayments/API#2491]
Dear team,

Our POS application produces and prints receipts independently of the payment provider. We use the Viva Terminal app.

We have noticed that the merchantReceiptText and cardholderReceiptText fields are empty. We are aware that these fields are flagged as being available in Android Payment Terminal integrations only, but would request that you can make these fields available to Viva Terminal integrations as well, as they are required to be printed on customer receipts (at least in Denmark).

Thanks,
Sam

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad ,

Thank you for your suggestion. We always consider our customers' feedback for future improvements. We will review your request and possibly, it will be available in a future release.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
