### ISSUE TITLE
Account Verification Status Changed webhook not listed in interface

### ISSUE THREAD

**Issue by fmarchalemisys** [VivaPayments/API#2494]
Hi,

I need to setup a [Account Verification Status Changed](https://developer.vivawallet.com/webhooks-for-payments/account-verification-status-changed/) webhook on my demo marketplace account.

That webhook does not exist (or not with that name) in the drop down selection list.

![image](https://github.com/VivaPayments/API/assets/30406081/505d1ba9-f141-4e24-a987-65cf77a051db)

How do I create that webhook?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @fmarchalemisys, 

Thank you for your message. Kindly note that this [webhook ](https://developer.vivawallet.com/webhooks-for-payments/account-verification-status-changed/#webhook-configuration)is only available in the Production environment, not in the Demo environment.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by fmarchalemisys** [comment]
Hi @VivaWalletCustomerSupport ,

Thank you for your answer.

I understand why it isn't available. I'll find another way to validate my programming before it reaches the production stage.
