### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by Eolia** [VivaPayments/API#2495]
Hi, in the Prestashop module (v.1.2.0 line 389) this control is not good:
`        if (!\Vivawalletsmartcheckout\Helpers\Config::get('app.module.ssl_protected')
            || (Tools::usingSecureMode() && Configuration::get('PS_SSL_ENABLED'))
        ) {`
he should be:
`        if (\Vivawalletsmartcheckout\Helpers\Config::get('app.module.ssl_protected')
            || (Tools::usingSecureMode() && Configuration::get('PS_SSL_ENABLED'))
        ) {`
Because in the config this parameter is always defined at true:
`    'module' => [
        'attributes' => [
            'name' => 'vivawalletsmartcheckout',
            'bootstrap' => true,
            'ps_versions_range_support' => ['min' => '1.6.1', 'max' => _PS_VERSION_],
        ],
        'enabled' => 'VIVAWALLET_SMART_CHECKOUT_ENABLED',
        'ssl_protected' => true,
        'auto_create_webhook' => true,
    ],`

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Eolia, 

Thank you for your message. We are currently investigating your report. We will inform you as soon as we have any updates.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Eolia,

Thank you for your feedback. This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva Wallet E-commerce Support Team
