### ISSUE TITLE
Creating "Pay with Viva Wallet" button dynamically

### ISSUE THREAD

**Issue by dnna** [VivaPayments/API#25]
Hello,
We have a single-page application where the order process happens in a dynamically generated order modal. We would like to use the "Pay with Viva Wallet" button, but we cannot find how to initialize the button *after* the page load and with dynamically created attributes (for example the order amount is not known in the page load, its known only after the user clicks the order button and opens the modal).

I have looked into the documentation but I cannot find any methods or callbacks to do what I'm looking for. Any ideas?

**Comment by labarg** [comment]
In the sample below you may check an implementation where .js is loaded afterwards and button element is appended. You must replace the pyblickey with yours.

'''html
<html>
<body>
<script src="https://www.vivawallet.com/CMSScripts/jquery/jquery-1.11.3.min.js"></script>
<script>
function LoadButton() {
       $('#btnContainer').empty();
       $('#btnContainer').append('<button type="button" class="simple" data-vp-publickey="s5gR7Occme4i/d6kPzj4hg5R/KEFXnavmpAGMR+dtK0=" data-vp-lang="el" data-vp-description="Friendly description for you customer" data-vp-amount="4500"></button>');
       $.getScript( "https://www.vivapayments.com/web/checkout/js");
};
</script>

<form action=/charge" method="POST"> 
<input type="button" onclick="LoadButton()" value="Load 'Pay with VivaWallet'"></input>
<div id="btnContainer"></div>
</form>
</body>
</html>
'''

**Comment by dnna** [comment]
Thanks! That implementation is a little hacky, but it works great.
