### ISSUE TITLE
Πρόβλημα με ηλεκτρονική πληρωμή

### ISSUE THREAD

**Issue by Marilz** [VivaPayments/API#250]
Καλησπέρα, ένας πελάτης μου έκανε μία πληρωμή με κάρτα στις 11/2 και έλαβε τον αριθμό συναλλαγής  9380777722872603, ενώ στο δικό μας λογαριασμό δεν φαίνεται να έχει γίνει πληρωμή. Παρακαλώ ενημερώστε με τι ακριβώς έχει συμβεί.

**Comment by dmihos** [comment]
Καλησπέρα σας
Πράγματι, δεν υπάρχει επιτυχημένη συναλλαγή με αυτό τον κωδικό (Order Code).
Ο πελάτης σας, λανθασμένα, υπέθεσε ότι η συναλλαγή ολοκληρώθηκε επιτυχώς.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
