### ISSUE TITLE
Cannot Reset module vivawalletsmartcheckout

### ISSUE THREAD

**Issue by Benoit1980** [VivaPayments/API#2501]
Hello,

We're encountering an issue with your module on PrestaShop 8.1.3.

After uninstalling your plugin(Version 1.3.0), we attempted to upload a new version(Version 1.3.1) but encountered the following error:

"Cannot Reset module vivawalletsmartcheckout. SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '150-1-98' for key 'PRIMARY'".

Due to this bug, we're unable to install the latest version of your module.

Any assistance you could provide would be greatly appreciated.

Thank you,

Best regards,

Ben

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Benoit1980,

Thank you for your message and apologies for the late response. Since you opened a new request, is the issue with above error ongoing; did you manage to install the plugin? 

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Benoit1980,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team

**Comment by Benoit1980** [comment]
Hello,

I wanted to inform you that we successfully reset the module and resolved the issue with the keys.

I have a quick question: is it normal for all payments in Prestashop to be set to "Viva Wallet payment on hold"? Do they need manual verification, or is there a way to automatically update Prestashop to "Paid" upon receiving payment callbacks?

Thank you.
