### ISSUE TITLE
Prestashop 8.1.3 bug when landing on the module page(it resets all the data)

### ISSUE THREAD

**Issue by Benoit1980** [VivaPayments/API#2502]
Hello,

I've previously discussed this issue with your team over the phone, but I believe it's important to document it here for clarity.

In PrestaShop 8.1.3, while your module was active and functioning correctly, we encountered difficulties revisiting the PrestaShop module page, as it would invalidate the keys.

Upon attempting to access the page after setting the keys using the following URL:

index.php?controller=AdminModules&configure=vivawalletsmartcheckout&token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

We encountered the following problem:

![image](https://github.com/VivaPayments/API/assets/6231274/05a8163b-cdcd-4ecf-9d66-e743a9d5ed9a)

Despite our expectation that this issue had been resolved in version 1.3.1, we uninstalled version 1.3.0. However, we are now unable to proceed further, as we cannot install the new version.

I've opened another request on GitHub to address this matter comprehensively.

Thank you for your attention to this issue.

Best regards,

Ben

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Benoit1980,

Thank you for your message. Could you please share the Merchant ID of your account? We will also need the latest error Logs generated from the plugin. To locate them go from your Prestashop dashboard to Advanced Parameters - Logs.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by Benoit1980** [comment]
Hello,

Sure, please provide us with your email address so we can communicate securely the ids and log.

Thank you,

Regards,

Ben

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Benoit1980,

You can contact us via Live Chat or share them to the following e-mail:

support@viva.com

Please add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Benoit1980,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response since we did not get any emails.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Benoit1980, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
