### ISSUE TITLE
Checkout page in testing mode not working ?

### ISSUE THREAD

**Issue by mikaelcarlavan** [VivaPayments/API#2505]
HI,

The Smartckeckout payment page https://demo.vivapayments.com/web/checkout?ref={orderCode} doesn't seem to work in test mode. I keep getting an internal error. Any help ?

For example, here's the data I send to create my order.  This part is working fine and returned me an orderCode. But the redirection, with this orderCode, fails. Strangely this works well in production mode.

{
    "amount": 2500,
    "sourceCode": "7846",
    "customerTrns": "This is a description displayed to the customer",
    "customer": {
        "email": "test@abc.com",
        "fullName": "M. Test",
        "phone": "06XXXXXXXX",
        "countryCode": "FR",
        "requestLang": "fr-FR"
    }
}

Thanks !

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mikaelcarlavan, 

Thank you for your message. Can you please share a screenshot of the error?

Kind regards,
Viva E-commerce Support Team

**Comment by mikaelcarlavan** [comment]
Nevermind, it is working now. I guess you were having server problems during my tests.
Thanks anyway.

**Comment by mikaelcarlavan** [comment]
Well, unfortunately, the error is back. Here is a screenshot of the error 
<img width="1424" alt="Capture d’écran 2024-04-09 à 16 25 46" src="https://github.com/VivaPayments/API/assets/10746841/a2b11f0c-aebe-4337-8553-0d70c9b0bd3b">

For information, URL is [https://demo.vivapayments.com/web2?ref=2628032408291452](https://demo.vivapayments.com/web2?ref=2628032408291452)
Original URL is [https://demo.vivapayments.com/web/checkout?ref=2628032408291452](https://demo.vivapayments.com/web/checkout?ref=2628032408291452)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mikaelcarlavan ,

Please create a new order code and use this URL when redirecting customers. If the problem persists, please create an order code with a longer "paymentTimeout" timeframe, as the order codes you've sent us have expired. 
<html>
<body>

https://demo.vivapayments.com/web/checkout?ref={OrderCode}


</body>
</html>


Kind regards,
Viva E-commerce Support Team

**Comment by mikaelcarlavan** [comment]
Hello,

I used your URL but your system redirects to the second
Here is a new order : https://demo.vivapayments.com/web/checkout?ref=8634514315068120

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mikaelcarlavan ,

It seems that the URL that you sent us works correctly. Could please send us the Mobile number that you registered your account with? (We need the country code too)

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mikaelcarlavan, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @mikaelcarlavan 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
