### ISSUE TITLE
Authentication issue for ISV Basic Auth

### ISSUE THREAD

**Issue by PaulosPatilas** [VivaPayments/API#2506]
Hello, 

i have an issue, wherever i try to make a call at [Retrieve Transaction by Order Code](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Retrieve-Transactions/paths/~1api~1transactions~1?ordercode=%7Bordercode%7D/get) or [Cancel Payment Order](https://developer.vivawallet.com/isv-partner-program/payment-isv-api/#tag/Payments/paths/~1api~1orders~1{orderCode}/delete) using our Reseller Id and Reseller  Secret with the Merchant Id, exactly as documentation says (ResellerId:MerchantId:ResellerSecret), which i copied from our ISV Demo Account (Settings -> Api Access -> Reseller API Credentials), i get a 401 Unauthorized status. i cross checked every possible credential combination but still nothing.I searched and found someone having a similar issue (#2437) for who you generated different credentials from those displayed on his account. Im wondering if i missed something or i also need different credentials from what i already used.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @PaulosPatilas,

Thank you for your message. Kindly note that the Reseller ID & API Key can only be generated upon request.

To generate the credentials, we need you to tell us the phone number of the Demo ISV account. For security reasons, please send it via email at [support@viva.com](mailto:support@vivawallet.com) and add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @PaulosPatilas 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by PaulosPatilas** [comment]
Hello,
i send an email at [support@viva.com](mailto:support@vivawallet.com) with the GitHub ticked number on the subject.
I still wait for a response.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @PaulosPatilas

We have received your email. We will reply as soon as we have an update.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @PaulosPatilas, 

We replied to your email. This ticket will close for now. Please don't hesitate to raise a new ticket or reply to the email if you need further assistance.

Kind regards,
Viva E-commerce Support Team
