### ISSUE TITLE
handle-payments-with-card-installments with extra amount

### ISSUE THREAD

**Issue by Epameinondas-Theodoropoulos** [VivaPayments/API#2507]
3 Questions:

**Question 1**
I want the customer to pay installements for a period of 12 months. 

But before start the installment i want to charge an extra fee. 

So for example: The user must pay 1200euros + 100 euros to use my service. 

Can i charge somehow the 100 euros at the same time with the installment endpoint ? 

So the user redirect in the viva page. It shows to him that will pay 12euros per month PLUS 100 euros for one time. 

Can i do somehow that ? 

**Question 2**
Does exist any endpoint that returns informations for the card included if it is a debit or credit card ?

**Question 3**
What is the difference between installments and recurring payments in viva ? I mean i know the difference but in viva I can't find any text that explains that the card will be charged until the amount is cleared. 
If the user deactivate his credit card what's going on ? Is this possible when the installments have not be paid yet ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Epameinondas-Theodoropoulos 

Thank you for your message. 
Question 1 - Answer
No, this functionality is not available in our API. 

Question 2 - Answer 
We don't provide a tool for that, but there are many tools online that you can use to see the type of the card by using the 6 first digits. 

Question 3 - Answer
You can find more information about installments and recurring transactions in the following guides.
[guide 1](https://developer.vivawallet.com/tutorials/payments/handle-payments-with-card-installments/)
[guide 2](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post)
[guide 3](https://developer.vivawallet.com/code-samples-for-payments/create-recurring-payment/)
[guide 4](https://help.vivawallet.com/el/?q=%CE%B4%CF%8C%CF%83%CE%B5%CE%B9%CF%82)
 



Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Epameinondas-Theodoropoulos,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by Epameinondas-Theodoropoulos** [comment]
> Hello @Epameinondas-Theodoropoulos
> 
> Thank you for your message. Question 1 - Answer No, this functionality is not available in our API.
> 
> Question 2 - Answer We don't provide a tool for that, but there are many tools online that you can use to see the type of the card by using the 6 first digits.
> 
> Question 3 - Answer You can find more information about installments and recurring transactions in the following guides. [guide 1](https://developer.vivawallet.com/tutorials/payments/handle-payments-with-card-installments/) [guide 2](https://developer.vivawallet.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post) [guide 3](https://developer.vivawallet.com/code-samples-for-payments/create-recurring-payment/) [guide 4](https://help.vivawallet.com/el/?q=%CE%B4%CF%8C%CF%83%CE%B5%CE%B9%CF%82)
> 
> Kind regards, Viva Wallet E-commerce Support Team

**Question1**
This wil be a very good functionality to add it. 

**Question2**
I am aware the online tools, but the security (Even though you give ony 6 digits) is again a problem to consider. Maybe you can add a tool for that . It will be helpfull ( And i did not found it in other providers either).

**Question3**
These 2 articles: 
1) https://help.vivawallet.com/el/articles/4899797-%CF%80%CF%8E%CF%82-%CE%BB%CE%B5%CE%B9%CF%84%CE%BF%CF%85%CF%81%CE%B3%CE%BF%CF%8D%CE%BD-%CE%BF%CE%B9-%CE%AC%CF%84%CE%BF%CE%BA%CE%B5%CF%82-%CE%B4%CF%8C%CF%83%CE%B5%CE%B9%CF%82

2) https://help.vivawallet.com/el/articles/4899830-%CE%BC%CF%80%CE%BF%CF%81%CF%8E-%CE%BD%CE%B1-%CF%87%CF%81%CE%B5%CF%8E%CF%83%CF%89-%CE%AC%CF%84%CE%BF%CE%BA%CE%B5%CF%82-%CE%B4%CF%8C%CF%83%CE%B5%CE%B9%CF%82-%CF%83%CE%B5-%CF%8C%CE%BB%CE%B5%CF%82-%CF%84%CE%B9%CF%82-%CE%BA%CE%AC%CF%81%CF%84%CE%B5%CF%82

answered some of my questions.

But I have a few more questions: 

**Question 4**
In the first article the following is mentioned: 
"In the case of interest-free instalments, the total amount of the purchase is bound from the beginning to your customer's card, thus not allowing him/her to proceed with subsequent purchases in case there is not enough available balance.".

The question I have to ask will be done through 2 examples: 

_Example 1_
a) My client has a limit on his credit card of 500euros. 
b) The interest-free instalments will be 12 months and will be worth 450 euros. So 12 months times 450 euros = 5400 euros. 
c) Can this scenario be done or will the credit card be declined because it does not have the 5400 euro limit ?

_Example 2_
a) My client has a credit card limit of 500 euros. 
b) The interest-free instalments will be 12 months and will be worth 50 euros. So 12 months times 50 euros = 600 euros. 
c) Is this scenario feasible?

------------------------------------------------------

**Question 5**
In case we have a scenario that works. 
The customer pays the interest-free instalments normally every month. For example out of 12 instalments he has paid 6. 
Suddenly on the 7th month he tries to deactivate his credit card to avoid paying the remaining instalments.

Will he be allowed to do this if the amount has been bound as stated in the article or will he be refused by the bank from which he took out the card?

This is an important question for the web application I am trying to implement.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Epameinondas-Theodoropoulos 

Thank you for your feedback about your first questions. As for the rest of your questions: 

Question 4:

Example 1:
a) If your client's credit card has a limit of 500 euros and the total value of the interest-free instalments is 5400 euros, it is likely that the transaction will be declined due to insufficient credit limit. The card issuer typically checks the available credit limit against the total amount to be bound before authorizing the transaction.

Example 2:
a) In this scenario, where the total value of the interest-free instalments is 600 euros, it is feasible as it falls within the credit card's limit of 500 euros. The transaction should be processed successfully.

Question 5:
If the customer attempts to deactivate their credit card to avoid paying the remaining instalments after having made partial payments, the bank will still hold them liable for the outstanding balance and they will take necessary actions to collect the outstanding debt, which could include legal recourse if deemed necessary.

Kind regards,
Viva E-commerce Support Team

**Comment by Epameinondas-Theodoropoulos** [comment]
@VivaWalletCustomerSupport 
Thank you for the answers. They were very helpful and detailed .

I have a follow up question from your answer in **Question 5**

**Question 6**
Does the same occurs when we use the recurring transactions ? 
We have the scenario that someone buys my service and it pays 350 euros per month with his **_debit card_**. 

For example again out of 12 instalments he has paid 6.
Then:
**a)** he tries to deactivate the card or
**b)** the account that has been connected with the card has not enough money (maybe is zero). 

What happens in this case ?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Epameinondas-Theodoropoulos 

You can think of recurring transactions as a subscription. If your customer doesn't have enough funds in their account or if the card gets deactivated, the transaction won't go through.

Kind regards,
Viva E-commerce Support Team

**Comment by Epameinondas-Theodoropoulos** [comment]
@VivaWalletCustomerSupport 
So it's like our responsibility then to warn them "Hey, add funds because after this period of time, we will have to cancel it.. etc etc. "

Ok thank you for the answers :)
