### ISSUE TITLE
[Feature Request] Add Microsoft Kiota API Search support and upgrade to OpenAPI 3

### ISSUE THREAD

**Issue by ThaDaVos** [VivaPayments/API#2509]
I am currently working on a integration between ECR software and Viva - for this I am using [Microsoft Kiota](https://learn.microsoft.com/en-us/openapi/kiota/) to generate a client for DotNet (other languages are supported too) - the thing is, before I could generate it, I needed to upgrade the Swagger 2.0 to OpenAPI 3.0 spec (I got the spec files by using the netwerk tab of my browsers developer tool when looking at the given documentation) - I also had to fix a few inconsistencies to get it to work - so maybe this should be looked after too.

Secondly, I would like to request the addition of the API to Microsoft Kiota Search index, this can be easily done by following the instructions here: https://learn.microsoft.com/en-us/openapi/kiota/add-api

As to why? **To make it easier for people to build integrations!**

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ThaDaVos,

Thank you for your suggestion. We always consider our customers' feedback for future improvements. We will review your request and possibly, it will be available in a future release.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ThaDaVos, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team

**Comment by ThaDaVos** [comment]
Why close it if there is no real answer to if it's accepted or not? Would love to hear about the result of the review so I know if I can expect it or not - willing to do a PR for Microsoft Kiota Support if needed when the OpenAPI 3 get's implemented
