### ISSUE TITLE
Πρόβλημα με πληρωμές (περνάνε ενώ δεν θα έπρεπε)

### ISSUE THREAD

**Issue by makisweb** [VivaPayments/API#251]
Καλησπέρα σε όλους. 
Στην ιστοσελίδα https://www.music-megastore.gr προχωράω σε πληρωμή μέσω vivapayments. 
Δίνω επίτηδες μια λάθος κάρτα και με οδηγεί στη συνέχεια σε σωστό (success page). 
Πράγματι η συναλλαγή γίνεται απλά δεν περνάν τα χρήματα (Έρχεται e-mail με τα στοιχεία της παραγγελίας στο email μου). 

Εάν μια συναλλαγή δεν εγκριθεί δεν θα έπρεπε να μου βγάζει η viva επί τόπου μήνυμα λάθους ; Από το να με οδηγεί στην success page του site ?

**Comment by dmihos** [comment]
Καλησπέρα σας
Παρατηρούμε ότι η πηγή που έχετε για το music-megastore.gr έχει το ίδιο url για success και fail.
Αν όντως η ίδια σελίδα χειρίζεται τις επιτυχίες και τις αποτυχίες, θα πρέπει να δείτε ότι λειτουργεί σωστά.
Αν όχι, τότε μάλλον πρέπει να δηλώσετε διαφορετικά urls.

**Comment by makisweb** [comment]
Ναι σύμφωνα με τις οδηγίες :+1: 
6) Συμπληρώνουμε το όνομα της πηγής, το domain Name, επιλέγουμε http ή https και για integration
method επιλέγουμε Redirection συμπληρώνουμε στα Url συναλλαγής
wc-api/WC_em_Vivapayments_Gateway αν τα friendly urls(permalinks) είναι ενεργοποιημένα σε
διαφορετική περίπτωση ?wc-api=WC_em_Vivapayments_Gateway

Για αυτό έβαλα τα ίδια. Που έκανα το λάθος ;

**Comment by makisweb** [comment]
Κάτι έχω βρει ναι, πείτε μου ακριβώς το πρόβλημα

Στις 17 Αυγούστου 2017 - 7:13 μ.μ., ο χρήστης SonataAmanes <
notifications@github.com> έγραψε:

**Comment by SonataAmanes** [comment]
Σ ευχαριστώ πολύ για την άμεση απάντηση. 
Το πρόβλημα είναι ότι όταν κάνω δοκιμή βάζοντας επίτηδες λάθος κάρτα, με πάει σε success page.
Χρησιμοποιούμε μάλλον το ίδιο plugin, γιατί κι εγώ στην πηγή πλγρωμών χρησιμοποιώ το url wc-api/WC_em_Vivapayments_Gateway.
Θα πρέπει να βάλω διαφορετικό για τις αποτυχημένες συναλλαγές;

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
