### ISSUE TITLE
[Feature Request|Idea] Unify the Cloud and Local Peer-to-Peer API

### ISSUE THREAD

**Issue by ThaDaVos** [VivaPayments/API#2510]
I was just thinking after my conversation with @Oussama Tahour yesterday about the support of ISV for Peer-to-Peer - why not Unify the REST API between both? Like have the same endpoints used in Cloud, available on Peer-to-Peer - this makes easier to develop a client to communicate with Viva - as the same API for Cloud would also works when calling a terminal (as both use HTTPS) by Peer-to-Peer with only the change of the BaseUrl/Host being called.

You could also use Authentication in the same way, except now you send the `/connect/token` to the terminal, perhaps with the following information:
```YAML
ClientKey: {device_id}.viva.com
ClientSecret: {a_value_from_peer_to_peer_settings or mac-address}
```
Why? Cause now anyone can send a payment to the terminal even though they shouldn't!

Why Unify the API? It simply eases development, eases documentation and makes sure that both platforms stay in sync more - also makes it less complex to develop and integrate with Viva

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ThaDaVos,

Thank you for your suggestion. We always consider our customers' feedback for future improvements. We will review your request and possibly, it will be available in a future release.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ThaDaVos,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
