### ISSUE TITLE
Demo Account IARP (AADE) integration

### ISSUE THREAD

**Issue by AlexandrosWrapp** [VivaPayments/API#2515]
Hi, I'm trying to configure an IARP configuration for the [Cloud Terminal Setup ](https://developer.viva.com/apis-for-point-of-sale/card-terminals-devices/rest-api/).

Is there way to setup my soft pos for IARP integration in Demo environment?
From my android device I'm trying to set it up with the enable data configuration and then it asks for cash register id which fails with the message "An error has occured while generating master key" when trying any (mock) value in there.

If I understand this correctly the process as described [here](https://www.aade.gr/sites/default/files/2024-03/Viva_Ciontek_Terminal_App_v2.pdf), is that in production environment AADE will provide us with a valid Cash register id.
But I need to first run my setup in demo environment, so is there any value I could use for it?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AlexandrosWrapp,

Thank you for your message and apologies for the late response.
Kindly note that this feature is not available in demo environment.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AlexandrosWrapp,

We just wanted to follow up on the reply we sent. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by AlexandrosWrapp** [comment]
Hi again,

Yes I saw your response thank you for clarifying.
Just wondering though how I could validate the integration before moving on to production.

[Here](https://developer.viva.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Transactions/paths/~1ecr~1v1~1transactions:sale/post) lists the attributes required for AADE (aadeProviderSignatureData, aadeProviderSignature, etc).

It seems that whatever value passed there works anyway. Is this correct?
Is there a way to get error codes regarding these fields from the request?

Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AlexandrosWrapp,

Thank you for your message and apologies for the late response.
To provide additional support regarding this issue please contact us via the Live Chat option (which can be found at the bottom-right of the Developer Portal and main Viva.com site, or in your Production Viva.com self-care account)

Kind regards,
Viva E-commerce Support Team
