### ISSUE TITLE
Viva Terminal Device support

### ISSUE THREAD

**Issue by chiotelis** [VivaPayments/API#2516]
Hello, 
we purchased an android Kiosk, to use viva Terminal app for our customers but we get the message "Ambiguous activity is detected ..." and the app shuts down. 
 My device is not rooted as shown by screenshot. 
Does viva terminal app need GSM Certificate? 

![432260908_1184551592907786_1607493465549165859_n](https://github.com/VivaPayments/API/assets/81966329/a1902141-dd5e-4244-a634-984ecb66fe35)
![432341952_1484494388803661_3270785183599325975_n](https://github.com/VivaPayments/API/assets/81966329/2db38430-7d23-4140-b5c3-eb227116a312)
![432211846_2397897487066599_3394407426373876860_n](https://github.com/VivaPayments/API/assets/81966329/0d709115-c216-4ae1-b3ea-48ff40223f58)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @chiotelis,

Thank you for your message. We would recommend contacting us via Live Chat (which can be found at the bottom-right of the Developers Portal and main Viva site, or in your Production Viva Wallet self-care account) to better support you on this issue. 

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @chiotelis, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
