### ISSUE TITLE
Unexpected action="mmSale" in response (Android Intent)

### ISSUE THREAD

**Issue by paulcorke** [VivaPayments/API#2517]
We are using the Android app on a Ciontek CS50 and running transactions via Intents.  We are using the ISV_clientId (etc.) parameters and setting "action" to be "sale" in the request.

In the sandbox environment, the response coming back has "action" set to "sale" which is expected and as per the documentation.  However, in production the response has "action" set to "mmSale".

Looking at the documentation, there is a "Multimerchant Sale" call - marked as deprecated - which uses "mmSale".  The documentation is not clear on whether the response would be "sale" or "mmSale", but in any case we are not using that request.

Does the "mmSale" response indicate that we are doing something wrong?  For now we are treating responses with "mmSale" and "sale" as equivalent.  Is that ok?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

Thank you for your message and apologies for the late response.
To provide additional support regarding this issue please contact us via the Live Chat option (which can be found at the bottom-right of the Developer Portal and main Viva.com site, or in your Production Viva.com self-care account)

Kind regards,
Viva E-commerce Support Team
