### ISSUE TITLE
Magento 2.3 Module

### ISSUE THREAD

**Issue by dvakerlis** [VivaPayments/API#2518]
I have a problem with the module for magento 2.3. We use the magento version 2.3.0 and when we make the payment in viva it's redirect to our website.

So in the Callback.php we get error 400. We have made some test and we see that it can't save the order.

$this->_order->save();   returns error 400.

Can anyone help to figure out this problem. 

Ps: We have try to get order with objectManager and save it but still we get the same error.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @dvakerlis 

Thank you for reaching out to us.

Please be informed that, although the Magento Smart Checkout plugin remains functional, it is no longer supported by our team. We are currently working on a new and improved plugin, which will be released soon. Therefore, we are unable to provide support for the existing plugin at this time.

We appreciate your understanding and patience. Should you have any further questions or require additional assistance, please do not hesitate to contact us.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @dvakerlis,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
