### ISSUE TITLE
API Documentation missing responses

### ISSUE THREAD

**Issue by ThaDaVos** [VivaPayments/API#2519]
As noted earlier through a call (few weeks ago) - the responses are missing in the API documentation - this prevents libraries like Kiota to generate valid clients...

For example, see: https://developer.viva.com/apis-for-point-of-sale/card-terminals-devices/rest-api/eft-pos-api-documentation/#tag/Transactions

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ThaDaVos, 

Thank you for the info and apologies for the late response.
Please don't hesitate to raise a new ticket if you need further assistance, regarding this issue, via the Live Chat option (which can be found at the bottom-right of the Developer Portal and main Viva.com site, or in your Production Viva.com self-care account)

Kind regards,
Viva E-commerce Support Team

**Comment by ThaDaVos** [comment]
Any update?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ThaDaVos ,

Thank you for your message.

To assist you better, please reach out to us via email at [support@viva.com](mailto:support@viva.com) or via the Live Chat option (which can be found at the bottom-right of the main Viva.com site, or in your Production Viva.com self-care account)

Kind regards,
Viva E-commerce Support Team
