### ISSUE TITLE
REFUND_SERVER_ERROR (-23) when refunding a payment through Android

### ISSUE THREAD

**Issue by SamuelMichelRiad** [VivaPayments/API#2520]
Hello team,

When attempting to refund a payment through Android, we're getting the REFUND_SERVER_ERROR (-23) message. We cannot find any reference to this error message anywhere. 

Can you please advise on what it means and how we can resolve?

Thanks,
Sam

**Comment by SamuelMichelRiad** [comment]
In addition to REFUND_SERVER_ERROR (-23), we are also seeing error UNEXPECTED (-999). On rare occasions the refund goes through.

Can you please advise?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @SamuelMichelRiad,

Thank you for your message and apologies for the late response.
To provide additional support regarding this issue please contact us via the Live Chat option (which can be found at the bottom-right of the Developer Portal and main Viva.com site, or in your Production Viva.com self-care account)

Kind regards,
Viva E-commerce Support Team
