### ISSUE TITLE
Pass Unlock PIN through Android Intent for Refund

### ISSUE THREAD

**Issue by paulcorke** [VivaPayments/API#2521]
We are using the Android Intent integration with a Ciontek CS50 (customer-facing) controlled by a separate POS terminal (operator-facing).  The operator has enabled PIN protection for refunds but would like to be able to enter the PIN into the POS rather than the Viva app.

I can't see any way in the documentation[0] for us to pass the unlock PIN through the request - we would like to add something like "&unlockPin=1234".  Is there anything I have missed, or a hidden option we could use?  

[0] https://developer.viva.com/apis-for-point-of-sale/card-terminal-apps/android-app/cancel/

**Comment by VivaWalletCustomerSupport** [comment]
Hello @paulcorke,

Thank you for your message and apologies for the late response.
There is no request available for this feature, it can only be done manually from the POS terminal. 

Kind regards,
Viva E-commerce Support Team
