### ISSUE TITLE
No Multiple Source Code

### ISSUE THREAD

**Issue by rederijker** [VivaPayments/API#2522]
It is impossible to insert more source codes into the plugin. This is a problem when dealing with multilingual sites that use WPML.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @rederijker ,

Thank you for your message and apologies for the late response.
Unfortunately, we do not currently support WPML. 

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @rederijker,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
