### ISSUE TITLE
No webhook delivery!

### ISSUE THREAD

**Issue by Papitoulini** [VivaPayments/API#2523]
I 've exposed my project via ngrok! But while i can verify the webhook! I got no deliveries.

The webhook i set up is:
Transaction Payment Created

And am redirecting the user to 
https://demo.vivapayments.com/web2
to confirm his payment

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Papitoulini 

Please provide us more info regarding your issue. 

Kind regards,
Viva E-commerce Support Team

**Comment by Papitoulini** [comment]
What else should i provide?
I just verified my webhook as the documentation mentioned.
Then i make a payment but i don't se any webhook delivery.

One thing i found in the documentation it says that you have to pass the 3ds to trigger the webhook
But in develop mode i dont see a way to pass the 3ds

**Comment by Papitoulini** [comment]
I couldn't understand why, but I randomly tested another webhook, "Account Transaction Created," which somehow triggered my first webhook related to payments. After deleting the second webhook, the first one continued working correctly.
