### ISSUE TITLE
Retrive list of transactions

### ISSUE THREAD

**Issue by hpeykov** [VivaPayments/API#2524]
Hello,

For my program I need a way to retrieve a list of sale transactions done for certain period.
I found this API: https://developer.viva.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)
Actually it works fine, but documentation says it is deprecated.
Is it safe to use it in new project ?
Is there alternative that is going to stay ?

Thank you in advance.
Hristo Peykov

**Comment by VivaWalletCustomerSupport** [comment]
Hello @hpeykov 

Even though the API at this link is marked as deprecated, it currently works fine for retrieving a list of sale transactions for a certain period. There is nothing to worry about as it functions correctly for your needs.

Kind regards,
Viva E-commerce Support Team

**Comment by hpeykov** [comment]
Thank you for clarification.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @hpeykov, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
