### ISSUE TITLE
Whitelist the Viva addresses (not updated)

### ISSUE THREAD

**Issue by pnaa** [VivaPayments/API#2525]
Is your server's IP whitelist updated?
Getting a response from (demo account)  94.62.1.236 that is not listed on the documentation page:
https://developer.viva.com/webhooks-for-payments/#whitelist-the-viva-addresses

can you please update the documentation with the current active servers, either Demo and Production

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pnaa, 

Thank you for your suggestion. We always consider our customers' feedback for future improvements. We will review your request and possibly, it will be implemented in a future update.

Kind regards,
Viva E-commerce Support Team
