### ISSUE TITLE
Vivawallet smart checkout plugin hasn't been tested with the last 3 major wordpress versions

### ISSUE THREAD

**Issue by ioweb-gr** [VivaPayments/API#2526]
When trying to install the plugin I get this message. Is the plugin abandoned? 

![image](https://github.com/VivaPayments/API/assets/20220341/60e233a4-4864-48ea-9377-6b1d2a893cc7)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

Thank you for your message. Rest assured the current plugin is operational. Please note that a new upgraded version will be released soon. We don't have the exact ETA yet, it will be announced [here](https://developer.viva.com/releasenotes/). 

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ioweb-gr ,

Our new WooCommerce plugin is now available!  

Download it [here.](https://wordpress.org/plugins/viva-com-smart-for-woocommerce/)

Please note that the new plugin requires your WooCommerce credentials for seamless integration.

Kind regards,
Viva E-commerce Support Team
