### ISSUE TITLE
Payment gateway not working on Woocommerce Version 9.0.1

### ISSUE THREAD

**Issue by alin-hub** [VivaPayments/API#2527]
<img width="1083" alt="Capture d’écran 2024-06-22 à 09 44 35" src="https://github.com/VivaPayments/API/assets/62423253/ddc8f4de-622d-4163-a2b9-46856536c6bd">
Hello,

With the new version of WooCommerce, I had to regenerate my default pages to enable the pickup option for my clients. Since then, the standard plugin is no longer working. I tried the Smart Checkout option, but it isn’t working either. However, if I activate other payment gateways like PayPal or bank transfer, those payment methods appear on the checkout page.

<img width="348" alt="Capture d’écran 2024-06-22 à 10 09 57" src="https://github.com/VivaPayments/API/assets/62423253/cf506c11-eb19-4d8f-bd5c-346213a57b24">

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alin-hub,

Thank you for your message. Could you please contact us via our live chat option so we can further investigate the issue with more information?

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by alin-hub** [comment]
Hello, thank you but the live chat only send me to the AI bot, unable to have someone

Edit: I figure out to speak to someone but by now no solution

**Comment by alin-hub** [comment]
![Capture d'écran 2024-06-26 193206](https://github.com/VivaPayments/API/assets/62423253/8d6ce00e-0c53-4267-854c-d09a33f98035)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alin-hub,

Thank you for your message. Please ask them to connect you with the ecommerce department. In order for us to investigate and guide you with your issue we need to have more info related to your account.

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by customlab** [comment]
Hello,

I also face the same problem with woocommerce 9.0.2 and wordpress 6.5.5.
I have tried both plugins (Viva smart checkout & standard checkout ).

Standard checkout shows a message like the above screenshot that is incompatible with woocommerce. 

Both plugins do not work on test mode and at live mode they redirect to viva payment environment, completes the tansaction but when they redirect back to wordpress they get a 404 despite the url seems right ( /success/?t=5be9005a-a120-4554-9580-e74dc6dd4f5b&s=7395980851272601&lang=en-US&eventId=0&eci=1 )

what should we do ?

![image](https://github.com/VivaPayments/API/assets/35843267/fe630f5d-6cce-4708-922b-f7254091d4f0)

**Comment by alin-hub** [comment]
> Hello,
> 
> I also face the same problem with woocommerce 9.0.2 and wordpress 6.5.5. I have tried both plugins (Viva smart checkout & standard checkout ).
> 
> Standard checkout shows a message like the above screenshot that is incompatible with woocommerce.
> 
> Both plugins do not work on test mode and at live mode they redirect to viva payment environment, completes the tansaction but when they redirect back to wordpress they get a 404 despite the url seems right ( /success/?t=5be9005a-a120-4554-9580-e74dc6dd4f5b&s=7395980851272601&lang=en-US&eventId=0&eci=1 )
> 
> what should we do ?

Hello, the support team by chat they proposed me to get back to the validation system (the old one) instead off the new block system. I didn't do that beacause i'll loose the pickup possibility of the customer to retrive the order.

**Comment by customlab** [comment]
> > Hello,
> > I also face the same problem with woocommerce 9.0.2 and wordpress 6.5.5. I have tried both plugins (Viva smart checkout & standard checkout ).
> > Standard checkout shows a message like the above screenshot that is incompatible with woocommerce.
> > Both plugins do not work on test mode and at live mode they redirect to viva payment environment, completes the tansaction but when they redirect back to wordpress they get a 404 despite the url seems right ( /success/?t=5be9005a-a120-4554-9580-e74dc6dd4f5b&s=7395980851272601&lang=en-US&eventId=0&eci=1 )
> > what should we do ?
> 
> Hello, the support team by chat they proposed me to get back to the validation system (the old one) instead off the new block system. I didn't do that beacause i'll loose the pickup possibility of the customer to retrive the order.

Hello,
You mean the checkout page with shortcode and not the blocks ? I have already done this because when I use blocks the viva payment option does not show at all.  When I put the checkout page with the [woocommerce_checkout] it showing

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alin-hub,

Our current plugin doesn't support Blocks. But our team is working in an updated version of our plugin that will support it. We don't have a ETA yet but you can check [our release page](https://developer.viva.com/releasenotes/2024/) for the latest updates.  

Kind regards,
Viva Wallet E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team

**Comment by customlab** [comment]
Hello,

There another problem beside the blocks incompatibility.
If we use a checkout page with the shortcode [woocommerce_checkout] , it redirects to vivawaller payment processor, it does the transaction fine BUT when it redirects to wordpress again, wordpress replies with 404 error page

**Comment by VivaWalletCustomerSupport** [comment]
Hello @alin-hub ,

Our new WooCommerce plugin is now available!  

Download it [here.](https://wordpress.org/plugins/viva-com-smart-for-woocommerce/)

Please note that the new plugin requires your WooCommerce credentials for seamless integration.

Kind regards,
Viva E-commerce Support Team
