### ISSUE TITLE
Viva Wallet public key

### ISSUE THREAD

**Issue by MihailChert** [VivaPayments/API#2529]
Where can I find Viva wallet public key for online payments?
What I have from viva account is Merchant ID and API Key.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MihailChert,

Thank you for your message. A public key is not required for our payment gateway. Can you please clarify if you are using one of our plugins?

Kind regards,
Viva E-commerce Support Team

**Comment by MihailChert** [comment]
a form with a payment button using a js script is used https://www.vivapayments.com/web/checkout/js

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MihailChert,

Thank you for your prompt response. In the link below you will find our documentation guide regarding custom smart checkout integrations. https://developer.viva.com/smart-checkout/smart-checkout-integration/

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MihailChert, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
