### ISSUE TITLE
Πρόβλημα με το API Key

### ISSUE THREAD

**Issue by tonythess** [VivaPayments/API#253]
Καλημέρα σας, χρησιμοποιούμε woocommerce, εγκαταστήσαμε σχετικό plugin, συμπληρώσαμε τα απαραίτητα πεδία (Merchant ID, API key και στο Codeld "default". 
Πραγματοποιώ αγορά και πληρωμή με Viva Wallet και το μήνυμα που λαμβάνω είναι: "Λάθος στοιχεία εμπόρου ή το API δεν λειτουργεί." 
Τι κάνουμε λάθος ;;;;

Αντώνης

**Comment by tonythess** [comment]
Άκυρο !!! το πρόβλημα λύθηκε !!!

Αντώνης

**Comment by zabos** [comment]
μπορεις να μου πεις επειδη εχω το ιδιο προβλημα τι εκανες??ευχαριστω

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
