### ISSUE TITLE
Ροή διασύνδεσης cloud erp με viva.com terminal

### ISSUE THREAD

**Issue by kostas27** [VivaPayments/API#2530]
Καλημέρα σας,
Προσπαθούμε να διασυνδέσουμε το viva.com Terminal με cloud erp σύστημα τιμολόγησης της εταιρείας μας, για να προσφέρουμε στους πελάτες μας αναδρομολόγηση στο softpos viva.com terminal σε περίπτωση πληρωμής μέσω κάρτας.
Έχουμε κάνει demo account και έχουμε δηλώσει το demo pos με sourceCode, terminalId και virtualTerminalId. Επίσης έχουμε το demo pos ως εφαρμογή σε συσκευή android με ενεργοποιημένο το πρωτόκολλο ΑΑΔΕ.
Τρέχουμε με επιτυχία μέσω postman αλλά και με κώδικα μέσα από το erp τα services:

Obtain a Bearer Token
Search POS Devices
Initiate a Sales Request

Σύμφωνα με το flow εδώ: https://developer.viva.com/apis-for-point-of-sale/card-terminals-devices/rest-api/
δεν θα έπρεπε να εμφανιστεί στο softpos το ποσό της συναλλαγής και να ζητηθεί η παρουσία της κάρτας; Δε φαίνεται να προχωράει κάτι στην εφαρμογή, παραμένει στο 0.

Παρακαλούμε για τη βοήθειά σας εφόσον χρειάζεται και κάποια επιπλέον ρύθμιση στην εφαρμογή του pos ή υπάρχει κάποιο άλλο σφάλμα, έτσι ώστε να μπορέσουμε να συνεχίσουμε.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @kostas27,

Thank you for your message.
To provide additional support regarding this issue please contact us via the Live Chat option which can be found at the bottom-right of the Developer Portal and main Viva.com site, or in your Production Viva.com self-care account.

Kind regards,
Viva E-commerce Support Team

**Comment by kostas27** [comment]
Hello, we have sent 2 emails already, posted at github and at developer portal chat; however there has been no answer for a relatively simple question. We implement the demo services for initiating a sales request but nothing happens at the demo pos application. Please indicate an email address or somewhere we can have a basic support. Thank you.
