### ISSUE TITLE
Woocommerce plugin / Cancel payment shows as Pending payment order

### ISSUE THREAD

**Issue by ChrisEski** [VivaPayments/API#2533]
I use the Viva Wallet Smart Checkout for WooCommerce plugin for my e-commerce store. When redirected to the payment gateway, if the customer presses the Cancel button or just the back button (for some reason wants to cancel the payment at the given moment), in my "Orders" menu in Woocommerce, i receive this specific order as "Pending payment".

- If the customer never comes back to complete the payment, this pending order still remains in my dashboard.
- If the customer makes any changes to his order and continues the checkout, then i get a second order from him, this time as "Processing" (the expected one).

Is this a normal behaviour, or is there an issue?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ChrisEski, 

Thank you for your message.
Can you please provide more details about the transaction? We will need screenshots from your WooCommerce dashboard showing the status of the transaction and a screenshot from the plugin settings. We will also need the MID of your account. 

You can share them here via email at [support@viva.com](mailto:support@viva.com) or via the Live Chat option (which can be found at the bottom-right of the Developer Portal and main Viva.com site, or in your Production Viva.com self-care account)

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @ChrisEski,

This ticket will close for now. We will inform you via email. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
