### ISSUE TITLE
Bad Request (400) - Authentication Authorization Amount Discrepancy

### ISSUE THREAD

**Issue by Troca82** [VivaPayments/API#2534]
As of Friday, we are getting the following error when our discount plugin is enabled. 

Transaction failed with Viva-CorrelationId: XX-XXX-XXXXXXXX
General message: Bad Request (400)
Specific message: PaymentsCardHolderAuthenticationFailedAuthenticationAuthorizationAmountDiscrepancy

To clarify, neither our discount plugin nor the Viva has changed. 

We are getting the same issues on older known working development sites as well. 

After testing on a copy from 1 month ago (not updated for over a month) it has the same issue. 

All of a sudden discounts are causing a Authentication Authorization Amount Discrepancy error. 

This hints that something has changed at the viva API side. 

Can we please have some help and information what has changed.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Troca82, 

Thank you for your message. We received your email as well. We are investigating your case and we will inform you as soon as we have an update.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Troca82,

This ticket will close for now. We will inform you via email. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
