### ISSUE TITLE
Transactions with Counterpart = null and UserDescription = null

### ISSUE THREAD

**Issue by georgiosd** [VivaPayments/API#2536]
Hey all

I am using the `/dataservices/v2/accounttransactions/Search` API to fetch transactions for our bank account, but many types of transactions, like card or IRIS payments have no textual description whatsoever.

How can I get more information about these transactions?

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @georgiosd, 

Thank you for your message. This is a limitation we are facing with some payment methods like IRIS. You can also try the Retrieve transactions [(OLD)](https://developer.viva.com/apis-for-payments/payment-api/#tag/Transactions-(Deprecated)) it is still functional.

Kind regards,
Viva E-commerce Support Team

**Comment by georgiosd** [comment]
Thank you for the response, but I can't seem to be able to authenticate successfully.

I am using my ClientId and Secret, with Basic auth, but I'm always getting 401. I have also tried using a Bearer token like in the new API.

Example URL: `https://www.vivapayments.com/api/transactions/?clearancedate=2024-07-20`

Any ideas?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @georgiosd,

Thank you for your prompt response.
Make sure to use the correct credentials. This API call uses [Basic authentication](https://developer.viva.com/integration-reference/basic-auth/).

Kind regards,
Viva E-commerce Support Team

**Comment by georgiosd** [comment]
Ι have double- and triple-checked my credentials. I still get 401. Can someone from your team help me debug this?

**Comment by georgiosd** [comment]
It looks like it needs the merchant id + API key instead of client id + secret.

However, I am getting a 404 result when trying to use an `accountTransactionId` from the new service, to retrieve the transaction using the old service.

Is that expected?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @georgiosd,


There might be an error on the endpoint URL. Can you please share the code of the request and response you are getting? 

Kind regards,
Viva E-commerce Support Team

**Comment by georgiosd** [comment]
I am using Postman. 

```
GET /api/transactions/ccf60390-4b48-48b2-8194-4cb53e70cddc HTTP/1.1
Host: www.vivapayments.com
Authorization: Basic *****************
Cookie: ak_bmsc=**************
```
Returns:
```
{
    "Transactions": [],
    "ErrorCode": 404,
    "ErrorText": null,
    "TimeStamp": "2024-07-28T09:41:47.3229559+03:00",
    "CorrelationId": null,
    "EventId": 0,
    "Success": false
}
```

**Comment by VivaWalletCustomerSupport** [comment]
Hello @georgiosd,

Can you please use the full URL with and without www. and try again? 
Also try with a different transaction ID. We could not locate a transaction with the ID mentioned above. 

Kind regards,
Viva E-commerce Support Team

**Comment by georgiosd** [comment]
Is this old API for payment transactions or bank transactions? As a reminder, we are interested in *bank* transactions.

The transaction id was taken from the new API, it's a bank transaction, and it does exist.

The old API returns no transactions for any clearance date in June for us, which would make sense if it only returns payments as we are not using Viva for payments, only for the bank account.

PS: Without the www you get HTML, so the website responds.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @georgiosd,

Thank you for your prompt response. This Deprecated API is used for payment transactions only. 
Apologies for the inconvenience. 

Kind regards,
Viva E-commerce Support Team

**Comment by georgiosd** [comment]
So there is no way of accessing the description+counterpart seen in the dashboard as a user for bank transactions?

**Comment by VivaWalletCustomerSupport** [comment]
That is correct @georgiosd, you can only access it from the dashboard.

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
