### ISSUE TITLE
Smarty error in 1.6 versions

### ISSUE THREAD

**Issue by Eolia** [VivaPayments/API#2537]
Hi,
in \vivawalletsmartcheckout\views\templates\front\payment_return.tpl, version 1.3.2, you can't use "module:" because "module" ressource is unknow in 1.6.
"Trapped exception during execution hook displayPaymentReturn in module vivawalletsmartcheckout: Unknown resource type 'module'"
So, it's preferable to write distincts tpl like you did for order_confirmation tpls.

`
{if $status == 'failed'}
    {if $prestashop_version neq '1.6'}
        {include file="module:vivawalletsmartcheckout/views/templates/front/failure.tpl"}
    {else}
        {include file='./failure.tpl'}
    {/if}
{else}
...
`

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Eolia,

Thank you for your suggestion. We always consider our customers' feedback for future improvements. We will review your request and possibly, it will be available in a future release.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Eolia, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
