### ISSUE TITLE
No payment method available

### ISSUE THREAD

**Issue by Laurentsos** [VivaPayments/API#2538]
Hi,
I configured the plugin, but I have this message "No payment method available"
Thanks for your help

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Laurentsos, 

Thank you for your message. Can you name the plugin please? We will also need you to share a screenshot of the issue or the URL of your website to further investigate.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Laurentsos, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by Laurentsos** [comment]
Hi, 
The plugin is "Viva Wallet Smart Checkout" for Wordpress
https://cbd-sud.shop/
![paiement](https://github.com/user-attachments/assets/ff57c1f4-2db8-4f7e-a3a4-8f86c07c241a)

Thanks

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Laurentsos,

As we can observe from the screenshot, the checkout page uses a block-based layout 'WooCommerce Blocks plugin'. 
The specific way of building the checkout page may create a conflict with our plugin, that is, the form sections that have been created. Please try to structure the checkout page in a different way and our payment method should appear.
We would recommend switching to classic checkout or use a default theme that is not block-based.

Try to Log in to your WordPress admin dashboard.
Navigate to Pages -> Checkout.
Change the checkout page to the classic checkout.
By making this adjustment, you should observe the successful display of our payment method.

Kind regards,
Viva E-commerce Support Team

**Comment by Laurentsos** [comment]
I tried with "Twenty Twenty-Two", and the other default themes and it does the same.
I don't understand how to change the payment page to classic payment

**Comment by Laurentsos** [comment]
OK, I found it, thanks for your help

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Laurentsos,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
