### ISSUE TITLE
Viva Wallet Smart Checkout Stops Before Card Issuer Further Verification

### ISSUE THREAD

**Issue by victor-sopot** [VivaPayments/API#2539]
I am using the Viva Wallet Smart Checkout with WooCommerca on a Wordpress installation. 

Everything has been done according the integration setup, within our viva wallet account.

When trying to checkout and pay, the screen remains with the attached screenshot. 

please advise, thanks 

<img width="1440" alt="Screenshot 2024-08-03 at 2 43 29 PM" src="https://github.com/user-attachments/assets/ec944aa7-78bb-4d14-93c5-e08f39588188">

**Comment by victor-sopot** [comment]
@VivaWalletCustomerSupport which credentials do you need?

**Comment by victor-sopot** [comment]
![Screenshot 2024-08-06 at 10 51 37 AM](https://github.com/user-attachments/assets/d5a5467c-0272-41c6-87ce-71e4a75f8242)

I am receiving a console error related to the centinelapi / cardinal commerce??

**Comment by victor-sopot** [comment]
hello, @VivaWalletCustomerSupport @VivaWalletSupport  - still having this issue!

**Comment by VivaWalletCustomerSupport** [comment]
Hello @victor-sopot,

Thank you for your message and apologies for the late response.
Is the issue ongoing? If so, please share the website URL and your Viva account MID.

You can send it here or to the following e-mail: [support@viva.com](mailto:support@viva.com)
Please add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva E-commerce Support Team

**Comment by victor-sopot** [comment]
Someone replied to me over email with case number CAS-02931715.

My MID is `9fe4c319-363c-492c-8698-e8ec1e243cef`
and the website is https://chillmode.shop

**Comment by VivaWalletCustomerSupport** [comment]
Hello @victor-sopot, 

Since the communication is handled via email, this ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
