### ISSUE TITLE
Καμία ολοκληρωμένη χρέωση στο demo account

### ISSUE THREAD

**Issue by melcon77** [VivaPayments/API#254]
Αφορά URL  www.boatscan.com
Στο περιβάλλον demo (http://demo.vivapayments.com) υπάρχει δυνατότητα να δω μια χρέωση ολοκληρωμένη (δηλαδή να φαίνεται στο πίνακα των πωλήσεων του demo account)? Αν NAI, τότε χρειαζόμαστε την βοήθεια σας καθώς αυτή την στιγμή δεν εμφανίζεται καμία χρέωση από αυτές που δημιουργούμε.
Σημείωση: Στο demo account, στις Ρυθμίσεις/προφίλ/γενικά στοιχεία, ο επαγγελματικός λογαριασμός λέει ότι είναι σε status «επεξεργασία» (απλά το αναφέρω μήπως ευθύνεται αυτό).
Ευχαριστώ εκ των προτέρων
Μ.Κώνστας

**Comment by dmihos** [comment]
Καλησπέρα σας
Το demo περιβάλλον είναι εντελώς διαχωρισμένο από το παραγωγικό, οπότε θα πρέπει να εκτελείτε συναλλαγές με το demo merchantId σας. 
Μπορείτε να κάνετε χρήση της test κάρτας για δοκιμές, όπως αναφέρεται και στο [σχετικό οδηγό](https://github.com/VivaPayments/API/wiki/Redirect-Checkout).

**Comment by melcon77** [comment]
Καλησπέρα,
Εννοείτε πως εκτελούμε συναλλαγές στο demo περιβάλλον χρησιμοποιώντας το demo merchant id (**a743c9ad-feaa-4b0f-829e-04ddf86da58b**) και την demo πιστωτική κάρτα (4111111111111111), αλλά δεν περνάει καμία συναλλαγή στο _http://demo.vivapayments.com_ για να την δούμε.
Ευχαριστώ
Μ.Κώνστας

**Comment by dmihos** [comment]
Δεν υπάρχουν καταχωρημένες συναλλαγές με αυτό το merchantId στο demo περιβάλλον.
Υποθέτω θα παίρνετε κάποιο error στις κλήσεις, θέλετε να μας πείτε ποιο ακριβώς είναι αυτό το error;
