### ISSUE TITLE
All attempts to pay with viva card via an eshop purchase that uses viva checkout fail

### ISSUE THREAD

**Issue by channeld** [VivaPayments/API#2541]
Platform woocommerce.
Using viva checkout.
While the viva environment, under a viva url is shown with correct amount and email of client after hitting checkout in the eshop, all transactions fail without even a proper error message.

We tried with Viva cards, Wise card. All these are used daily with charges to purchase different things.
Clients try with their own cards. Same thing.

We get an error URL with a -1 showing AND at the same time at the "client" card we get the following even for a 4 euros charge: 
Personal {the amount} declined 
Contactless limit reached. Pay again using Chip and PIN (Insert card) to reset limit.
That is entirely irrelevant to what the case is... It is an online purchase...

What is the problem?

Also VIVA support is completely disappeared. That is not support for such a sensitive issue.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @channeld, 

Thank you for your message and apologies for the late response. 
Can you please share some screenshots showing the error? We will also need the account MID. 

You can send it here or to the following e-mail: support@viva.com
Please add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva E-commerce Support Team

**Comment by channeld** [comment]
Hi. Seems viva solved that and it works (after 20 days)...

**Comment by VivaWalletCustomerSupport** [comment]
Thank you @channeld.

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
