### ISSUE TITLE
Create the payment order | Postman

### ISSUE THREAD

**Issue by carlascjesus** [VivaPayments/API#2542]
I'm testing the Jumpseller plataform to create my onlne store. As Viva as no plug-in for Jumpseller, I'm trying to understand the smart checkout integration process. I'm using the Sandbox/Demo Account and Postman to do it. First of all I've created a Bearer token, After that I've tried to create a payment order but I always get the error "400 Bad Request". I've tried with sourceCode = "Default" but also with my payment source code.

![400BadRequest](https://github.com/user-attachments/assets/9852623d-9479-4871-8427-33fdc07eef95)

Could you help me with this issue, please?

Thank you.

Carla Jesus

**Comment by VivaWalletCustomerSupport** [comment]
Hello @carlascjesus, 

Thank you for your message and apologies for the late response.
Make sure you are using the correct demo credentials for the [OAuth 2.0](https://developer.vivawallet.com/integration-reference/oauth2-authentication/). You can also check the [Postman ](https://www.postman.com/viva-com/workspace/developer-portal/request/17199201-4a3e09c1-4209-4e90-a1ea-778fb4c3cf63)collection and the [developers porta](https://developer.viva.com/apis-for-payments/payment-api/#tag/Payments/paths/~1checkout~1v2~1orders/post)l page. 

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @carlascjesus, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @carlascjesus, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
