### ISSUE TITLE
Demo environment returns "Your payment could not be processed" on all test cards

### ISSUE THREAD

**Issue by MiSSHeaDShoT** [VivaPayments/API#2544]
Hello,
I am trying to integrate Smart Checkout but all the test cards return  "Your payment could not be processed" , "Failed" or "ACS internal server error (500)" from your backend. When investigating further trying with a Visa test card 4147 4630 1111 0133	I saw the eventId of the response to be 2062	(3DS validation failed).  I assume this verification must be disabled for my demo account somehow but I do not see how. 

Account number: 779936636281
Country : BG

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MiSSHeaDShoT, 

Thank you for your message and apologies for the late response. Some of the test had issues with the 3DS authentication. We would like to inform you that the issue has been resolved, all test cards are now available for testing.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MiSSHeaDShoT, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
