### ISSUE TITLE
Compatibility with new Opencart 3.0.4.0 and PHP 8.1

### ISSUE THREAD

**Issue by xakou** [VivaPayments/API#2546]
Opencart release version 3.0.4.0  which supports PHP 8.x.
I was wondering if the plugin supports the newer PHP versions and the new Opencart version.
Thank you

**Comment by VivaWalletCustomerSupport** [comment]
Hello @xakou, 

Thank you for your message. 
Kindly note that whilst still functional, this[ OpenCart Smart Checkout plugin](https://developer.viva.com/plugins/opencart/#overview) is no longer supported. 
A new plugin will be released soon, we don't have an ETA unfortunately.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @xakou, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
