### ISSUE TITLE
Integration with Prestashop

### ISSUE THREAD

**Issue by Lauragenevais** [VivaPayments/API#2547]
Hello, I installed the smart checkout payment module on Prestashop.
Unfortunately, it does not seem to recognize my accesses. So he doesn't want to connect me.
Do you know in which file or table in the database to modify (or add) the credentials ?

<img width="1788" alt="Capture d’écran 2024-09-01 à 18 26 19" src="https://github.com/user-attachments/assets/7aa52334-724f-4eef-81a5-cbee599e1ba1">

Thank you for your help.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Lauragenevais,

Thank you for your message and apologies for the late response.
Please follow the guide below and try again, we would also recommend generating new prestashop credentials.
https://developer.viva.com/plugins/prestashop-smart-checkout/#step-2-generate-prestashop-credentials

Kind regards,
Viva E-commerce Support Team

**Comment by Lauragenevais** [comment]
Thank you ! It's work :)

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Lauragenevais, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
