### ISSUE TITLE
Add / edit webhook in demo environment does not work

### ISSUE THREAD

**Issue by MiSSHeaDShoT** [VivaPayments/API#2548]
Hello,

From several days I am not able to edit or add webhooks in demo environment. 
There is some error 500 leading to: https://demo.vivapayments.com/error500.html?aspxerrorpath=/selfcare/en/security/updatewebhook while trying both actions and thus Datatables are showing error. 
No data is saved either ways.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MiSSHeaDShoT, 

Thank you for your message and apologies for the late response.
Can you please share the URL here? Also, make sure the webhook is public; not private. 
We would also recommend whitelisting the following IP addresses/ranges for this demo account: https://developer.viva.com/webhooks-for-payments/#whitelist-the-viva-addresses

Kind regards,
Viva E-commerce Support Team

**Comment by MiSSHeaDShoT** [comment]
Hello,

The webhook is public, I have whitelisted all IP's. When I click on "verify" to check the link I see a record in my apache log with HTTP response code 200 , so the URL gets accessed. Despite that this is what happens:
- The demo environment makes a POST call to https://demo.vivapayments.com/selfcare/en/security/updatewebhook
which results in HTTP response code "302 Found"
- Looking at response headers there is clearly a location redirect to /error500.html?aspxerrorpath=/selfcare/en/security/updatewebhook and later I see this on the response:

"viva.com
Error 500!
You have experienced a technical error. We apologize. Please wait a few moments and try again.
Υπήρξε κάποιο σφάλμα. Λυπούμαστε για τη ταλαιπωρία. Παρακαλώ δοκιμάστε ξανά σε λίγα λεπτά.
Homepage / Αρχική "

Regards

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MiSSHeaDShoT,

Thank you for the prompt response. Could you also share a screenshot showing the error?

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @MiSSHeaDShoT,

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
