### ISSUE TITLE
Cancel permanently recurring payments authorizations 

### ISSUE THREAD

**Issue by pnaa** [VivaPayments/API#2549]
If I create a payment using **allowRecurring = true** it all works well.
However, if a customer ends a subscription I want as a security measure do cancel this recurrency permition, but I can't find the proper endpoint to do it so, can you please assist?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pnaa,

Thank you for your message and apologies for the late response.
There is no API call for that unfortunately. You will have to terminate the existing payment from the[ initial payment](https://developer.viva.com/tutorials/payments/create-a-recurring-payment/#step-3-create-a-new-payment-from-the-initial-payment)

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @pnaa, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
