### ISSUE TITLE
CS50 Printer uses font with variable width

### ISSUE THREAD

**Issue by areiter** [VivaPayments/API#2550]
(got redirected here from VivaWallet SDK support page)

I'm having issues with the internal printer of the CS50. We are using it to print our receipts as well as the payment slips.

For the receipt you usually have a structure as the following:

`
     
      #   Product     Price
     ----------------------
      1x Product1     1.50
     10x Product2    10.20 
      ...
`

All nicely lined up. This only works if you use monospace fonts because a 'i' uses the same width as 'w', which results in having space for let's say 30 characters in one line.
The CS50 printer does not use a monospace font (tried it with the demo apk as well as with our own app) - both using the ciontek SDK. I don't see any way of switching the font.
Without monospace font, the device/printer is basically useless for printing receipts!

Attached find a demo printout;
1st Line: 20 chars 3x(1-0)
2nd + 3rd line: 20 chars double size
4th line 30x 'i'

![IMG_20240915_203718](https://github.com/user-attachments/assets/f18972b2-93fb-419c-ae07-fa03245f8e99)

Expectation 4th line should be same width than first line

Any help on that?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @areiter,

Thank you for your suggestion. Please note that the use of the terminal printer is intended for printing receipts. In any case, we will review your request and possibly make it available in a future release.

Kind regards,
Viva E-commerce Support Team
