### ISSUE TITLE
Issues with integrating VivaPayment for NextJS

### ISSUE THREAD

**Issue by tambaTech** [VivaPayments/API#2551]
I can't figure out how to implement VivaPayment on NextJS app.

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tambaTech,

Thank you for your message and apologies for the late response.
We would recommend checking our[ Smart Checkout Integration](https://developer.viva.com/smart-checkout/smart-checkout-integration/) and [AppToApp](https://developer.viva.com/tutorials/smart-checkout-configuration/integrate-with-a-mobile-app/) guide.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tambaTech, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by tambaTech** [comment]
> Hello @tambaTech, 
> 
> 
> 
> We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.
> 
> 
> 
> In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.
> 
> 
> 
> However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!
> 
> 
> 
> Kind regards,
> 
> Viva E-commerce Support Team

I've tried to create a api-key but can't get it to work

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tambaTech,

Thank you for your message. 
Can you please provide more details about the issue? We would recommend checking once again your implementation. 
If this is an issue from our end we will further investigate.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @tambaTech, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
