### ISSUE TITLE
Duplicate Webhook Issue After Successful Payment

### ISSUE THREAD

**Issue by Ajku1** [VivaPayments/API#2553]
Hello,

I have encountered an issue in the past week related to webhook notifications. 

After receiving a webhook indicating a successful payment for a transaction (statusId=F), I receive the exact same webhook again an hour later. This second webhook contains identical details (amount, merchantId, transactionId, eventType, statusId, createdAt).

This issue occurs sporadically and not for every transaction.

Could you help clarify why this might be happening?

Thank you.

**Comment by myke11j** [comment]
Happening for me too today. 
After payment went through and it sent same webhook message again after 1 hour.
I have to handle it on my service layer to make sure we only process webhook for one order once

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Ajku1,

Thank you for your message and apologies for the late response.
Can you please share the webhook URL and the response you received for this duplicate webhook?

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Ajku1, 

We just wanted to follow up on the reply we sent yesterday. We were simply wondering if you read our response.

In any case this ticket will remain active for at least 24 hours, so that you can come back if you wish.

However, if you have any questions, please don't hesitate to reply here and we'd be happy to help!

Kind regards,
Viva E-commerce Support Team

**Comment by Ajku1** [comment]
Hello @VivaWalletCustomerSupport,

Where can I share the details you requested in private? I don't want to expose the webhook URL here.

Thanks,
Nikola

**Comment by VivaWalletCustomerSupport** [comment]
Thank you for your prompt response @Ajku1 

You can send it to the following e-mail:
support@viva.com
Please add the GitHub ticket number on the subject of the e-mail.

Kind regards,
Viva E-commerce Support Team

**Comment by VivaWalletCustomerSupport** [comment]
Hello @Ajku1, 

This ticket will close for now. Please don't hesitate to raise a new ticket if you need further assistance.

Kind regards,
Viva E-commerce Support Team
