### ISSUE TITLE
What is EventID=20212 for in Viva API response?

### ISSUE THREAD

**Issue by myke11j** [VivaPayments/API#2554]
I am getting reject payment on Viva purchase from my API with  EventID=20212 in URL. I tried looking the response code docs, but it's not there https://developer.viva.com/integration-reference/response-codes/

Does any know what's this error code for?

**Comment by VivaWalletCustomerSupport** [comment]
Hello @myke11j,

Thank you for your message. The EventID=20212 is a status error for [Swish](https://developer.viva.com/payment-methods/local-payment-methods/swish/) payment method.

Kind regards,
Viva E-commerce Support Team

**Comment by myke11j** [comment]
Great, thanks for the quick response
