### ISSUE TITLE
Marketplace - 403 Error on Live Environment

### ISSUE THREAD

**Issue by AnastasiosHJW** [VivaPayments/API#2557]
Hello

I recently switched from the demo environment to the live one, using the API for Marketplace. When attempting to create a connected account, i encountered a 403 error, and when attempting a test transaction it generated the order, including the link to the checkout page, but when i tried to actually pay it failed with eventid 2108 (Payments Policy Acquiring Restriction). In the demo environment everything worked without errors. The API access tokens are being generated as normal, i've set up and verified webhooks, it's just that the some of the calls to the API are failing.
I believe that perhaps it happens because some steps for the platform account verification have not been completed, but i wanted to make sure. Is that the case? Will completing the verification fix the problem?

Thank you
Anastasios

**Comment by VivaWalletCustomerSupport** [comment]
Hello @AnastasiosHJW, 

Thank you for your message and apologies for the late response.
That is correct, once the account gets verified the restrictions will be lifted.

Kind regards,
Viva E-commerce Support Team

**Comment by AnastasiosHJW** [comment]
Thank you for the reply.
