### ISSUE TITLE
Σφάλμα σε συναλλαγή - Γυρνάει πίσω με status pending

### ISSUE THREAD

**Issue by wislem** [VivaPayments/API#256]
orderCode: 1493488894872600

Η ίδια κάρτα χρησιμοποιήθηκε επιτυχώς 2 φορές εχθές. Στις 2 επόμενες προσπάθειες, το StatusId παραμένει 'E' χωρίς αιτιολόγηση μέσα στο GetOrder.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
