### ISSUE TITLE
 Πρόβλημα κατά την προσθήκη Νέας Πηγής Πληρωμών

### ISSUE THREAD

**Issue by nikvaf** [VivaPayments/API#257]
Καλησπέρα,

κατόπιν επικοινωνίας με υπεύθυνο της εταιρίας σας, σας επισυνάπτω ένα screenshot από το σύστημα διαχείρισης της Viva Wallet κατά την διάρκεια προσθήκης νέας Πηγής Πληρωμών.

Παρότι συμπληρώνω κανονικά όλα τα πεδία, όταν πατάω το κουμπί Δημιουργία μου κοκκινίζει τα πεδία της φωτογραφίας.

Please advice me.

Σας ευχαριστώ πολύ,
Νικήτας

![screen shot 2017-02-20 at 2 54 04 pm](https://cloud.githubusercontent.com/assets/25957017/23215022/8abaac86-f919-11e6-98dd-aa1788b24d35.png)

**Comment by dmihos** [comment]
Καλησπέρα σας
Το συγκεκριμένο πρόβλημα έχει διορθωθεί, ξαναδοκιμάστε αν θέλετε.
Ευχαριστούμε,
