### ISSUE TITLE
API : Διαθέσιμο Υπόλοιπο Wallet

### ISSUE THREAD

**Issue by pRieStaKos** [VivaPayments/API#258]
Καλημέρα,
Υπάρχει τρόπος να κάνω API call για να πάρω το διαθέσιμο υπόλοιπο ενός wallet ? Θέλω να το εμφανίζω στο Admin Home Page με widget.

**Comment by pRieStaKos** [comment]
@dmihos υπάρχει καμία απάντηση ?

**Comment by dmihos** [comment]
Καλημέρα
Μπορείτε να χρησιμοποιήσετε το σχετικό API method [GetWalletInfo]  (https://github.com/VivaPayments/API/wiki/GetWalletInfo)

**Comment by pRieStaKos** [comment]
Ευχαριστώ πολύ. Το widget είναι έτοιμο. 
Καλό θα ήταν να περάσετε το Response σε array όλων των Wallets, όπως είναι και των Transactions, για πιο εύκολο return (μετά από foreach). Βλ [API/CreateOrder/PHP/gettransactions.php](https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/gettransactions.php#L44)

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
