### ISSUE TITLE
Native Checkout

### ISSUE THREAD

**Issue by kesidaki** [VivaPayments/API#259]
Καλησπέρα, τελειώνω μία web εφαρμογή και άρχισα να περνάω τις πληρωμές των χρηστών με τη χρήση του native viva payments. Ακολούθησα τις οδηγίες και προχωράω κανονικά με τη φόρμα μου αλλά όταν φτάνω στο php script μου επιστρέφει

The merchant with id (my_merchant_id) does not have a source with code 'Native' assigned or the source is disabled

Στη σελίδα http://demo.vivapayments.com/ έχω ήδη εισάγει τη σελίδα μου και φαίνεται ως ενεργή

**Comment by dmihos** [comment]
Καλημέρα σας

Η πηγή που φτιάξατε, έχει SourceCode 'Native'; 
Το SourceCode εμφανίζεται ως 'Κωδικός' στο διαχειριστικό περιβάλλον, και αυτό πρέπει να χρησιμοποιήσετε κατά το CreateOrder.

**Comment by kesidaki** [comment]
Σου είναι εύκολο να μου πείς που μπορώ να το βρώ αυτό; Να ξέρω που βρίσκεται για όταν κάνω το live λογαριασμό.

Και μήπως υπάρχει μία λίστα με τα συνήθη error που επιστρέφονται κατά το authentication της κάρτας για να εμφανίζω τα μηνύματα σφάλματος στο χρήστη σε ποιο καθαρή μορφή;
