### ISSUE TITLE
Αποτυχία ολοκλήρωσης συναλλαγής

### ISSUE THREAD

**Issue by IakovosR** [VivaPayments/API#260]
Καλησπέρα, χρησιμοποιούμε το web API και σε διάφορες τυχαίες στιγμές και ενώ ο πελάτης μας έχει συμπληρώσει τα στοιχεία της κάρτας του όταν πατήσει το κουμπί πληρωμής οδηγείτε (εντός του συστήματος της viva, κρίνωντας απο το URL) σε λευκή σελίδα. Αυτό συνέβει αρκετές φορές τη προηγούμενη βδομάδα σε τυχαία προιόντα και τυχαίες χρονικές στιγμές. Θεωρώ οτι είναι τυχαία η χρονική στιγμή και τα προιόντα καθώς τα ίδια προιόντα την ίδια ημέρα είχαν ολοκληρώσει κανονικά συναλλαγές.

**Comment by dmihos** [comment]
Καλημέρα σας
Για διερεύνηση, θα χρειαστούμε το merchantId σας (όχι το ApiKey), ένα ακριβές timestamp του συμβάντος και ένα screenshot (αν υπάρχει) που να δείχνει τη λευκή σελίδα με το url.
Μπορείτε να στείλετε αυτές τις λεπτομέρειες στο merchants@vivawallet.com με αναφορά στο παρόν issue.
Ευχαριστούμε

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
