### ISSUE TITLE
Cancel Transaction ASP.NET 

### ISSUE THREAD

**Issue by ktzouros** [VivaPayments/API#262]
Καλησπέρα,

προσπαθούμε να κάνουμε μέσα απο το API (Native Checkout) cancel transaction αλλά αντί να γίνεται cancel το σύστημα κάνει recurring. Ψάξαμε μέσα στο github για κάποια λύση αλλά το μόνο που βρήκαμε είναι https://github.com/VivaPayments/API/wiki/CancelTransaction που αναγράφει αυτά ακριβώς που κάνουμε και εμείς, Υπάρχει κάποιο demo ή μπορείτε να μας προτείνεται κάποια μέθοδο άλλη?

**Comment by dmihos** [comment]
Καλησπέρα
Για cancel/refund, η κλήση στο /api/transactions/{transactionId} πρέπει να γίνεται με verb DELETE (και όχι POST)

**Comment by ktzouros** [comment]
Σας ευχαριστώ για την άμεση απάντηση σας.
