### ISSUE TITLE
Αποτυχία επαναφοράς κωδικού στο demo

### ISSUE THREAD

**Issue by akasmak** [VivaPayments/API#263]
Καλησπέρα,

προσπαθώ να κάνω επαναφορά κωδικού στο demo.vivapayments.com αλλά μου εμφανίζει το παρακάτω μηνυμα:

Θα πρέπει να ορίσετε και να ταυτοποιήσετε μια e-mail διεύθυνση στο προφιλ σας, πριν προχωρήσετε σε επαναφορά του κωδικού πρόσβασης σας. 

Πώς μπορώ να ταυτοποιήσω μια e-mail διεύθυνση στο προφιλ μου ενώ δεν έχω πρόσβαση σε αυτό? 

Ευχαριστώ.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
