### ISSUE TITLE
σύνδεση e shop με viva wallet

### ISSUE THREAD

**Issue by pediabooks** [VivaPayments/API#264]
Καλημέρα σας 
Προσπαθώ να συνδέσω το e shop pedia@pediabooks.gr με τη viva wallet. Κόλησα στην πηγή πληρωμών για e shop. Εβαλε ο τεχνικός που στηρίζει τη σελίδα την "εικονική πληρωμή¨αλλα χάλασε τα pos στα φυσικά καταστήματα οπότε αφου επικοινώνησαν οι υπεύθυνοι των βιβλιοπωλείων με τη viva το διαγράψατε ξανά. Μπορείτε σας παρακαλώ να μας βοηθήσετε ωστε να ολοκληρωθεί η διαδικασία. 
Τα στοιχεία της εταιρείας ειναι ΠΑΙΔΕΙΑ ΒΙΒΛΙΟΠΩΛΕΙΑ ΑΕ αφμ 099316818 και το κινητό τηλ 6974031040

**Comment by dmihos** [comment]
Καλησπέρα
Θα πρέπει να φτιάξετε μια νέα πηγή για το site, ώστε στο διάστημα που αυτή θα είναι ανενεργή (λόγω του ελέγχου του site σας), δε θα επηρεάζεται η λειτουργία των POS.

**Comment by pediabooks** [comment]
καλημέρα σας
Εκανα την ΝΕΑ ΠΗΓΗ εδώ και αρκετές μέρες αλλά ειναι ακόμη σε εκκρεμοτητα. Πρέπει να περιμένω ή έκανα κατι λάθος?

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
