### ISSUE TITLE
Αιτολογίες αποτυχημένων πληρωμών (StatusId: "E")

### ISSUE THREAD

**Issue by wislem** [VivaPayments/API#265]
Καλημέρα σας,

Έχω 3 συναλλαγές με orderCodes:
1736245535272603
5026612813872607
9187401340172604

Οι πελάτες έβαλαν τα στοιχεία της κάρτας τους μέσω Redirection method, στην επιστροφή τους στο δικό μας site είχαν status pending αλλά τελικά οι συναλλαγές κατέληξαν με StatusId: "E".

Υπάρχει κάποιος τρόπος να βλέπουμε ΄το πραγματικό σφάλμα που εμφανίστηκε;

Ευχαριστώ εκ των προτέρων.

**Comment by dmihos** [comment]
Καλησπέρα σας
Οι πραγματικοί λόγοι απόρριψης των συναλλαγών από τον issuer, δεν είναι διαθέσιμες για προβολή ή μέσω του API.
Ευχαριστούμε για την επικοινωνία
