### ISSUE TITLE
Συναλλαγή από demo σε κανονικό με Riderect και mobile api.

### ISSUE THREAD

**Issue by methadoni** [VivaPayments/API#266]
Καλησπέρα, 

Χρησιμοποιώ σε μια πλατφόρμα που έχει ιστοσελίδα και εφαρμογή 
redirect για το site και το mobile api(απο Android)  για τις πληρωμές.

Μετά την ενεργοποίηση δούλεψε στο site και πραγματοποιήθηκε μια πληρωμή.
Τώρα εμφανίζει το μήνυμα
"The merchant with id b243ceeb-f076-4084-83e0-5f8029a868f8 does not have a source with code '8117' assigned or the source is disabled" 
Ως μήνυμα στο site και δεν πραγματοποιείται πληρωμή και  στο api ως ErrorText με erroCode 403 και response 400.  Στο app με το demo οι πληρωμές γίνονταν κανονικά.

Υπάρχει κάποια ειδική ρύθμιση που πρέπει να γίνει για να πραγματοποιούνται πληρωμές και από τις δυο μεριές στον ίδιο λογαριασμό; Αυτό το σφάλμα πως διορθώνεται για να δουλέψουν οι πληρωμές;

**Comment by dmihos** [comment]
Καλησπέρα
Προφανώς αλλάξατε το domain της πηγής 8117, οπότε είναι προσωρινά ανενεργή, μέχρι να περάσει από το σχετικό έλεγχο (εμφανίζεται σχετική προειδοποίηση στο παράθυρο επεξεργασίας της πηγής).

**Comment by methadoni** [comment]
Όχι δεν είχαμε αλλάξει το domain. Είχαμε κάνει κάποια αλλαγή από ridirect σε native μήπως δουλέψει το mobile api και απενεργοποιήθηκε. Όποτε αυτό είναι το κανονικό πρόβλημα:

 ErrorCode":403  ,"ErrorText":"Source 8117 of merchant b243ceeb-f076-4084-83e0-5f8029a868f8 does not support native checkout","TimeStamp":"2017-03-22T11:31:09.4033761+02:00","CorrelationId":null,"EventId":0,"Success":false

Όπως είπα και πριν στο site χρησιμοποιούμε ridirect. Θέλουμε να δουλεύει στο site και από native mobile app. Δεν πιστεύω να έχει γίνει κάποιο λάθος στο κώδικα μιας και το Demo δουλεύει κανονικά.
Χρειάζεται κάποια ρύθμιση ή συμβαίνει κάτι λάθος;

**Comment by dmihos** [comment]
Τότε θα χρειαστεί να έχετε 2 πηγές, μια για redirect και μια για native.
Συνεπώς, αφήστε την 8117 για redirect και φτιάξτε μια νέα για redirect

**Comment by methadoni** [comment]
Μια για native εννοείται. Δεν είναι και πολύ βολικό αυτό πάντως.
