### ISSUE TITLE
Αγγλικα στο redirection

### ISSUE THREAD

**Issue by christosal** [VivaPayments/API#267]
Καλησπερα , 
 Εχω τοποθετήσει ενα plugin στο woocommerce site μου απο την emspace.gr το οποιο κανει redirection. Φαινεται οτι δουλευει κανονικα αλλα το θεμα μου ειναι οτι η σελιδα που με παραπεμπτει ειναι μονο στα ελληνικα και εγω το θελω στα αγγλικα κυριως.Ενα θεμα επισης που υπαρχει ειναι οτι δεν γινεται να γινει πληρωμη με δολλαριο. Αν ενα προιον κοστιζει 80$ τοτε στο redirection εμφανιζει 80€ .Το native απο την αλλη,  μπορει να δουλεψει χωρις ssl?
Ευχαριστω

**Comment by dmihos** [comment]
Καλησπέρα
Η checkout σελίδα υποστηρίζει Ελληνικά/Αγγλικά μέσω της παραμέτρου RequestLang.
Το plugin δεν έχει κάποια σχετική επιλογή για τη γλώσσα; Αν όχι, θα πρέπει να απευθυνθείτε στο δημιουργό του plugin για βοήθεια.

**Comment by christosal** [comment]
Οκ θα τον ρωτησω. Οσο για τη πληρωμη με δολλαριο?

**Comment by dmihos** [comment]
Προς το παρόν το μόνο νόμισμα που υποστηρίζεται είναι το ευρώ
