### ISSUE TITLE
Πληρωμές με κάρτα σε shopify

### ISSUE THREAD

**Issue by sprtools** [VivaPayments/API#268]
Καλησπέρα σας, έχω ενεργό λογαριασμό στην ViVA που είναι συνδεδεμένο με το αρχικό μου eshop της opencart. Έχω ακόμα ένα eshop στην shopify και αναρωτιέμαι αν και πως γίνεται να το συνδέσω με της πληρωμές μέσω viva. Αφμ 998268562 Ευχαριστώ!!

**Comment by dmihos** [comment]
Καλησπέρα σας
Υπάρχει διασύνδεση με Shopify. Αποστείλατε, αν θέλετε, ένα αίτημα στο merchants@vivawallet.com, με ένδειξη "Διασύνδεση Shopify", αναφέροντας τα παρακάτω
MerchantId
Shopify Store name
Shopify Store Url

Στη συνέχεια θα σας δωθούν σχετικές οδηγίες ενεργοποίησης.
