### ISSUE TITLE
Αναφορά σφάλματος 

### ISSUE THREAD

**Issue by checkyourcar** [VivaPayments/API#269]
Καλησπέρα σας 
Κατά την προσπάθεια αγοράς απο το ηλ. κατάστημα, παρουσιάζεται αναφορά σφάλματος :  The merchant with id fd845506-8a71-44f2-9f6d-9d579cc8d2ee does not have a source with code '5177' assigned or the source is disabled"

Στην σελίδα του Viva επαγγ. λογαριασμού μου, στις πηγές πληρωμών αναφέρεται οτι δεν έχει εγκριθεί 
 
![image](https://cloud.githubusercontent.com/assets/26571205/24146059/a8320fc4-0e3c-11e7-8447-59b37b60fe51.png) 

![image](https://cloud.githubusercontent.com/assets/26571205/24146083/c862d396-0e3c-11e7-8787-8141edf348f0.png)

Απο οτι καταλαβαινω το προβλημα είναι οτι ακομα είναι σε εκκρεμότητα η πηγή πληρωμής?

Αν είναι αυτο γιατι είναι σε εκκρεμότητα. Αυτο συμβαίνει εδω και 10 μέρες!

Παρακαλώ για την βοήθεια σας .

**Comment by dmihos** [comment]
Έχει εγκριθεί η πηγή
