### ISSUE TITLE
Angular js error

### ISSUE THREAD

**Issue by kozer** [VivaPayments/API#27]
Is there any way to make the library work in angular?
I get the error "VivaPayments: Required data-vp attribute "cardnumber" was not found",
and i added the data-vp attr, i think its because of the templates...
If not, can you tell me where i can find the non uglify version of your script to make it work?
Thanks a lot.

**Comment by dpnevmatikos** [comment]
Hi there @kozer ,
Tested native checkout with angular.js and everything seems to be working fine.
Have a look at [this sample code](https://gist.github.com/dpnevmatikos/741583dae81942b5595b) for more details.
