### ISSUE TITLE
αφαιρεση επιλογης:ΠΛΗΡΩΣΤΕ ΜΕ ΚΑΡΤΑ ΜΕΣΩ ΤΗΛΕΦΩΝΟΥ (IVR) 

### ISSUE THREAD

**Issue by caredirect** [VivaPayments/API#270]
Κύριοι,

Παρακαλώ πολύ να μου πείτε πως μπορώ να αφαιρέσω την  επιλογή:ΠΛΗΡΩΣΤΕ ΜΕ ΚΑΡΤΑ ΜΕΣΩ ΤΗΛΕΦΩΝΟΥ (IVR)

**Comment by dmihos** [comment]
Καλημέρα
Μπορείτε να δείτε εδώ
https://github.com/VivaPayments/API/wiki/Optional-Parameters
την παράγραφο που αφορά το flag **DisableIVR**

**Comment by wedob13** [comment]
@dmihos  Καλησπέρα! Για την αλλαγή του DisableIVR για το extension του magento γνωρίζετε σε ποιο σημείο γίνεται η αλλαγή;

**Comment by dmihos** [comment]
Καλησπέρα
Η ερώτηση αφορά [αυτό το plugin](https://github.com/VivaPayments/API/tree/master/Plugins/magento/maghellaspay) ή κάποιο 3rd party;

**Comment by nikvaf** [comment]
Καλησπέρα, η απενεργοποίηση του IVR (Πληρωμή με κάρτα μέσω τηλεφώνου) γίνεται μέσω κώδικα ή μέσω από το διαχειριστικό του Viva Wallet? Σας ευχαριστώ πολύ

**Comment by nikvaf** [comment]
Κάποιο νεότερο σχετικά με το παραπάνω?

**Comment by dmihos** [comment]
Η απενεργοποίηση του IVR γίνεται με flag κατά το CreateOrder (flag DisableIVR), δεν είναι setting που αλλάζει από το διαχειριστικό

**Comment by digitupgr** [comment]
Καλησπέρα!! Χρησιμοποιούμε το magento plugin που έχετε ανεβάσει στο github και ενώ θέτουμε τη μεταβλητή $poststring['DisableIVR'] = true; και την ενσωματώνουμε στο $postargs  στο αρχείο Hpay.php το IVR εξακολουθεί να είναι ενεργό. Μπορείτε να μας δώσετε περισσότερες πληροφορίες σχετικά με το σημείο του κώδικα που πρέπει να ενσωματωθεί η συγκεκριμένη μεταβλητή? Ευχαριστώ

**Comment by dmihos** [comment]
Δοκιμάστε DisableIVR=1 (αντί του true)

**Comment by nikvaf** [comment]
Καλησπέρα, 

επανέρχομαι στο συγκριμένο θέμα καθώς ούτε με DisableIVR=1 απενεργοποιείτε η τηλεφωνική επιλογή. Υπάρχει κάποιο τεχνικό θέμα?

**Comment by VivaWalletSupport** [comment]
Hello, in Hpay.php you would replace:
$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&PaymentTimeOut=300';

By:
$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&PaymentTimeOut=300&DisableIVR=true';

In case your code is compiled run the compiler again and clear cache if applies..

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
