### ISSUE TITLE
Λάθος redirection μετά απο ολοκλήρωση συναλλαγής

### ISSUE THREAD

**Issue by ktsixit** [VivaPayments/API#271]
Χρησιμοποιούμε το Viva Payments με redirection, σε **Magento**. Αφου ο πελάτης μεταφερθεί στη σελίδα της Viva και κάνει την πληρωμή, το Viva δεν τον επιστρέφει στη σελίδα επιτυχούς συναλλαγής του Magento, αλλα στην **αρχική** σελίδα του site. Αυτό δημιουργεί προβλήματα.

Έχουμε ορίσει συγκεκριμένο **URL Επιτυχημένης συναλλαγής** αλλά για κάποιο λόγο αυτό αγνοείται.

Πως μπορούμε να το διορθωσουμε;

**Comment by dmihos** [comment]
Μετά την checkout, το redirect γίνεται στο success/fail url. Πιθανολογώ ότι ίσως δεν είναι δηλωμένο σωστά στην πηγή, και το redirect στη home γίνεται από το site σας, μόλις εντοπίσει το λάθος url.
Βεβαιωθείτε, αν θέλετε, ότι το url, όπως αυτό ακριβώς είναι δηλωμένο πάνω στην πηγή, είναι valid

**Comment by ktsixit** [comment]
Ειναι σιγουρα σωστο το url. Υπαρχει καποιος τροπος να ελεγξουμε τι συμβαινει;

**Comment by ktsixit** [comment]
Περιμένω κάποια απάντηση σας

**Comment by dmihos** [comment]
Στείλτε μας το merchantId σας (όχι το ApiKey) να δούμε την πηγή

**Comment by ktsixit** [comment]
merchantId  = e069ad79-3daf-404f-b721-b8a91e8db95b

**Comment by dmihos** [comment]
Όπως είχε αναφερθεί ήδη, σε δοκιμή που κάναμε για την πηγή 8711, μετά από τη συναλλαγή, το redirect έγινε στο
/checkout/onepage/failure/?t={ΧΧΧΧ-ΧΧΧΧΧ-ΧΧΧΧΧ}&s={YYYYYYYYY}&lang=el-GR
αλλά το site σας έκανε redirect (302) στην κεντρική σελίδα

**Comment by ktsixit** [comment]
Μπορούν να αφαιρεθούν τα ?t={ΧΧΧΧ-ΧΧΧΧΧ-ΧΧΧΧΧ}&s={YYYYYYYYY}&lang=el-GR
Δεν εξυπηρετούν σε κάτι και ίσως αυτό δημιουργεί το πρόβλημα.

**Comment by dmihos** [comment]
Δε μπορούν να αφαιρεθούν, μπορείτε να τους αλλάξετε όνομα όμως, μέσα από τη διαχείριση πηγών.
