### ISSUE TITLE
Για καποιο λογο το ΑΡΙ επιστρεφει Invalid Reseller

### ISSUE THREAD

**Issue by ctsimpos** [VivaPayments/API#272]
Χρησιμοποιουσα το ΑΡΙ για χρονια χωρις προβλημα, προσφατα μετα απο μια αλλαγη στην σελιδα μου το ΑΡΙ σταματησε να δουλευει ενω χρησιμοποιω τα ιδια δεδομενα (key etc)
υπαρχει καποιος τροπος να επικοινωνησω μαζι σας και να σας δωσω τον κωδικα μου να δουμε τι εχει γινει;

**Comment by ctsimpos** [comment]
υπάρχει κάποιος που μπορει να μας βοηθησει επ αυτου??? Οι συνεργατες σας μας υπεδειξαν να μιλησουμε μαζι σας. Κανουμε μεγαλο τζιρο μεσω της υπηρεσιας σας και θελουμε να την απενεργοποιησουμε.

**Comment by dmihos** [comment]
Καλημέρα
Ποιο είναι το ακριβές σφάλμα που παίρνετε;
Από τον τίτλο φαίνεται ένα "Invalid Reseller". 
Φαίνεται για authentication πρόβλημα, οπότε βεβαιωθείτε ότι καλείτε με τα σωστά credentials το σωστό περιβάλλον (demo/production).

Στείλτε μας και το merchantId (**όχι** το API key), για να δούμε το account.

**Comment by ctsimpos** [comment]
Καλησπέρα

το merchantID 6645 source 2721 (source 5762 works fine)

**Comment by ctsimpos** [comment]
βρέθηκε κάτι επ'αυτού;

**Comment by dmihos** [comment]
To merchantId δε φαίνεται στο screenshot, ωστόσο ο έμπορος βρέθηκε.
Δεν εντοπίστηκε κάποιο πρόβλημα με την πηγή 2721, έγινε δημιουργία OrderCode και redirect.
Θα πρότεινα να δείτε ξανά τα credentials (merchantId, Api key) καθώς το error εκεί παραπέμπει

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
