### ISSUE TITLE
Pay with vivaWallet amount integrity - vivaWalletToken

### ISSUE THREAD

**Issue by apoeco** [VivaPayments/API#273]
Χρησιμοποιώ την υλοποίηση Pay with Viva Wallet (σε demo περιβάλλον προς το παρών).
Δεδομένου ό,τι ένας κακόβουλος χρήστης μπορεί να αλλάξει το ποσό προς χρέωση που έχει ορισθεί, υπάρχει κάποιος τρόπος αφότου λάβω το vivaWalletToken να ελέγξω το ποσό που θα χρεωθεί πριν κάνω post στο `/api/transactions`;
Δηλαδή δοσμένου ενός vivaWalletToken μπορώ να δω το amount χωρίς να κάνω την χρέωση;

**Comment by dmihos** [comment]
Καλησπέρα
Δυστυχώς δεν υπάρχει τρόπος να διαβάσετε το token.
Ωστόσο, το response της κλήσης για χρέωση επιστρέφει το Amount, οπότε στην περίπτωση που αυτό διαφέρει από το αρχικό, μπορείτε να ακυρώσετε τη συναλλαγή και να ενημερώσετε σχετικώς το χρήστη.
https://github.com/VivaPayments/API/wiki/CancelTransaction
