### ISSUE TITLE
Issue with viva wallet

### ISSUE THREAD

**Issue by EfiMesitidou** [VivaPayments/API#274]
![vivawallet](https://cloud.githubusercontent.com/assets/26704292/24343230/0844ec5c-12ce-11e7-8ed0-bf1fed64248d.PNG)

Όταν έδωσα τα στοιχεία της κάρτας μου για να με χρεώσει η Viva Wallet εμφανίστηκε η επιλογή:
"Αποδέχομαι να χρησιμοποιείται η κάρτα μου για μελλοντικές ή επαναλαμβανόμενες χρεώσεις από τον/την ΜΙΚΥ ΜΑΟΥΣ" 
Μπορείτε σας παρακαλώ να μου εξηγήσετε τί σημαίνει αυτό?

Ευχαριστώ,
Έφη Μεσιτίδου

**Comment by dmihos** [comment]
Καλησπέρα σας
Είναι υπηρεσία που έχει ενεργοποιήσει ο συγκεκριμένος έμπορος και συνήθως χρησιμοποιείται για περιπτώσεις συνδρομητικών υπηρεσιών.
Για περισσότερες πληροφορίες, θα πρέπει να επικοινωνήσετε με τον ίδιο τον έμπορο.
