### ISSUE TITLE
kids LOFT - ΔΙΠΛΗ ΧΡΕΩΣΗ ΜΕ ΑΓΟΡΕΣ ΑΠ ΤΟ E-SHOP ΜΑΣ

### ISSUE THREAD

**Issue by KidsLoft** [VivaPayments/API#275]
Καλησπέρα σας,

Σας ενημερώνουμε πως όπως μας ανέφερε πελάτης μας, σε αγορά του απ το e-shop μας, μέσω της πλατφόρμας Viva Wallet, δημιουργήθηκε ένα ένα "κόλλημα" την ώρα της ολοκλήρωση της συναλλαγής-πληρωμής με τη χρεωστική του κάρτα.
Κατά την ολοκλήρωση, έβγαλε στην οθόνη του πελάτη ERROR 404 ΛΑΘΟΣ URL και τον πήγε πάλι στην προηγούμενη σελίδα για να ξανακάνει τις κινήσεις που έκανε ώστε να ολοκληρώσει τη συναλλαγή πληρωμή.
ΟΜΩΣ εμάς μας ήρθε ειδοποίηση στο e-mail μας, ότι η πληρωμή έγινε κανονικά.

Παρακαλώ όπως ελένξετε το έχει συμβεί διότι υπάρχει το ενδεχόμενο στον επόμενο πελάτη, να συμβεί το ίδιο και να κάνει διπλή πληρωμή και να του γίνει διπλή χρέωση... και θα έχει ΠΟΛΥ ΑΣΧΗΜΟ αντίκτυπο για εμάς και την εταιρεία και το e-shop μας.

Περιμένουμε ενημέρωσή σας άμεσα για το εν λόγο πρόβλημα.

Με εκτίμηση,
Ανδρέας Ρουχωτάς

**Comment by KidsLoft** [comment]
# ΚΑΛΗΣΠΈΡΑ ΣΑς,
ΔΥΣΤΥΧΩΣ ΑΚΟΜΗ ΔΕΝ ΕΧΟΥΜΕ ΛΑΒΕΙ ΑΠΑΝΤΗΣΗ ΣΑΣ ΓΙΑ ΤΟ ΦΑΙΝΟΜΕΝΟ ΤΩΝ ΔΙΠΛΩΝ ΧΡΕΩΣΕΩΝ ΜΕΣΩ ΠΛΡΩΜΗΣ [ΠΙΣΤΩΤΙΚΩΝ ΚΑΡΤΩΝ ΜΕΣΩ ΤΟΥ E-SHOP ΜΑΣ.
ΣΗΜΕΡΑ ΕΓΙΝΕ ΔΙΠΛΟΧΡΕΩΣΗ ΚΑΡΤΑΣ ΞΑΝΑ ΜΕ ΠΕΛΑΤΙΣΣΑ Η ΟΠΟΙΑ ΠΗΓΕ ΝΑ ΟΛΟΚΛΗΡΩΣΕΙ ΤΗΝ ΑΓΟΡΑ ΤΗΣ, ΜΕΣΩ ΤΗΣ VIVA ΕΦΑΡΜΟΓΗΣ ΠΟΥ ΕΧΟΥΜΕ ΕΓΚΑΤΑΣΤΗΣΕΙ ΣΤΟ E-SHOP ΜΑΣ ΚΑΙ ΧΡΕΩΘΗΚΕ ΙΔΙΟ ΠΟΣΟ 2 ΦΟΡΕΣ.
ΔΕ ΜΠΟΡΟΥΜΕ ΝΑ ΚΑΤΑΛΑΒΟΥΜΕ ΤΙ ΣΥΜΒΑΙΝΕΙ... ΕΧΟΥΜΕ ΚΑΝΕΙ ΚΑΙ ΤΗΛΕΦΩΝΙΚΑ ΚΑΙ ΜΕΣΩ E-MAIL ΤΗΝ ΕΝΟ ΛΟΓΟ ΕΠΙΣΗΜΑΝΣΗ ΑΛΛΑ ΔΕΝ ΥΠΑΡΧΕΙ ΚΑΜΙΑ ΑΠΑΝΤΗΣΗ ΑΠΟ ΜΕΡΟΥΣ ΣΑΣ.
ΕΧΕΙ ΜΙΛΗΣΕΙ ΚΑΙ Η IT MANAGER ΠΟΥ ΔΙΑΧΕΙΡΙΖΕΤΑΙ ΤΟ E-SHOP ΜΑΣ ΑΛΛΑ ΔΕ ΤΙΣ ΔΟΘΗΚΑΝ ΔΙΕΥΚΡΙΝΗΣΕΙΣ ΚΑΙ ΦΥΣΙΚΑ ΤΟ ΛΑΘΟΣ ΚΑΙ ΤΟ ΠΡΟΒΛΗΜΑ ΔΕΝ ΕΙΝΑΙ ΔΙΚΟ ΜΑΣ.
ΠΑΡΑΚΑΛΟΥΜΕ ΓΙΑ ΜΙΑ ΦΟΡΑ ΑΚΟΜΗ ΣΕΒΑΣΤΕΙΤΕ ΤΟΥΣ ΠΕΛΑΤΕΣ ΜΑΣ, ΣΤΗΡΙΖΟΜΑΣΤΕ ΣΕ ΑΥΤΟΥΣ ΣΤΙΣ ΔΥΣΚΟΛΕΣ ΑΥΤΕΣ ΕΠΟΧΕΣ ΚΑΙ ΔΕ ΜΑΣ ΕΠΙΤΡΕΠΕΤΑΙ ΝΑ ΤΟΥΣ ΧΑΣΟΥΜΕ.

ΠΑΡΑΚΑΛΟΥΜΕ ΠΟΛΥ ΝΑ ΕΛΕΝΞΕΤΕ ΤΟ ΦΛΕΓΟΝ ΑΥΤΟ ΖΗΤΗΜΑ ΚΑΙ ΝΑ ΜΣ ΕΝΗΕΜΡΩΣΕΤΕ ΕΓΓΡΑΦΟΣ ΓΙΑ ΤΗ ΔΙΟΡΘΩΣΗ ΤΟΥ.

ΠΕΡΙΜΕΝΟΥΜΕ ΑΜΕΣΑ ΕΝΗΜΕΡΩΣΗ ΣΑΣ.

ΜΕ ΕΚΤΙΜΗΣΗ,
ΑΝΔΡΕΑΣ ΡΟΥΧΩΤΑΣ

**Comment by dmihos** [comment]
Καλημέρα σας

Δεν υπάρχει κάποιο πρόβλημα από την πλευρά της Viva Payments.

Θα πρέπει να ελέγξετε τα urls που έχετε δηλώσει στις πηγές που χρησιμοποιείτε, καθώς φαίνεται ότι είναι λάθος (μενού "Οι πωλήσεις μου">"Πηγές πληρωμής").
Συμβουλευτείτε τον τεχνικό σας αν δε γνωρίζετε ακριβώς τί πρέπει να κάνετε.

Ο πελάτης, μετά την πληρωμή, δε βλέπει στο site σας σελίδα επιτυχίας και ξαναπληρώνει, νομίζοντας ότι δε χρεώθηκε.

**Comment by KidsLoft** [comment]
ΚΑΛΗΜΕΡΑ ΣΑΣ.
ΑΝ ΙΣΧΥΕΙ ΑΥΤΟ ΠΟΥ ΜΑΣ ΛΕΤΕ, ΠΙΣΤΕΥΩ ΠΩΣ Η ΤΕΧΝΙΚΟΣ ΘΑ ΠΡΕΠΕΙ ΝΑ ΜΕ ΤΟΝ ΤΕΧΝΙΚΟ ΣΑΣ Ή ΜΕ ΕΣΑΣ ΝΑ ΤΗΝ ΚΑΘΟΗΓΗΣΕΤΕ ΣΧΕΤΙΚΑ ΜΕ ΤΟ ΖΗΤΗΜΑ ΓΙΑ ΝΑ ΛΥΘΕΙ.
ΜΕ ΠΟΙΟΝ ΜΠΟΡΕΙ ΝΑ ΜΙΛΗΣΕΙ ΚΑΙ ΣΕ ΠΟΙΟ ΤΗΛ ΠΟΥ ΜΠΟΡΕΙ ΝΑ ΚΑΛΕΣΕΙ ΓΙΑ ΝΑ ΔΙΕΥΘΕΤΗΘΕΙ ΤΟ ΖΗΤΗΜΑ;;

**Comment by dmihos** [comment]
Δε χρειάζεται κάποια καθοδήγηση τηλεφωνική, είναι αρκετά απλό το θέμα.

Έχετε φτιάξει μια πηγή για τις συναλλαγές από το eshop, στην οποία έχει οριστεί το success και fail url. Σε αυτά οδηγείται ο χρήστης μετά από κάθε συναλλαγή.
Θα πρέπει ο τεχνικός να βεβαιωθεί ότι είναι σωστά.
Αν έχει κάποια απορία, μπορεί να στείλει ερώτημα στο παρόν thread.

**Comment by KidsLoft** [comment]
ΚΑΛΗΜΕΡΑ ΣΑΣ!!!

ΒΑΣΗ ΤΗΣ ΑΠΑΝΤΗΣΗΣ ΣΑΣ: "Θα πρέπει να ελέγξετε τα urls που έχετε δηλώσει στις πηγές που χρησιμοποιείτε, καθώς φαίνεται ότι είναι λάθος (μενού "Οι πωλήσεις μου">"Πηγές πληρωμής")." ΚΑΤΑΛΑΒΑΙΝΟΥΜΕ ΟΤΙ ΕΝΝΟΕΙΤΕ ΠΩΣ ΠΡΕΠΕΙ ΝΑ ΕΧΕΙ ΔΙΑΦΟΡΕΤΙΚΟ ΤΟ URL Η ΕΠΙΤΥΧΗΜΕΝΗ ΠΛΗΡΩΜΗ ΑΠ ΤΗΣ ΑΠΟΤΥΧΗΜΕΝΗΣ ΠΛΗΡΩΜΗΣ...ΣΩΣΤΑ;;;

**Comment by dmihos** [comment]
Καλημέρα σας
Δεν είναι απαραίτητο όχι. Αν το site σας μπορεί να χειριστεί τις επιτυχίες και τις αποτυχίες στο ίδιο url, τότε μπορείτε να το ορίσετε κοινό.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
