### ISSUE TITLE
Βήματα ενεργοποίησης Viva wallet σε Shopify

### ISSUE THREAD

**Issue by sprtools** [VivaPayments/API#276]
Καλησπέρα σας, έχω πάρει την σχετική έγκριση για το URL μου και προσπαθώ να αρχίσω να δέχομαι πληρωμές. Έχω ορίσει στο shopify την επιλογή να δέχομαι πληρωμές μέσω VivaPayments ενώ στα πεδία που μου βγάζει, έχω βάλει το Merchant ID που μου εμφανίζει στο Viva και στο Store token το public key που μου εμφανίζει στο Vivapayments αφότου κλίκαρα το πεδίο "Ενεργοποίηση υπηρεσίας Native/Pay with Viva Wallet checkout". Προσπάθησα πρωτύτερα να βάλω αντί για το publickey το Api Key αλλά και στις δύο περιπτώσεις όταν φτάνω στην ολοκλήρωση παραγγελίας μου κάνει redirect και πετάει error site not found. Παρακαλώ καθοδηγήστε με γιατί δεν έχω γνώσεις προγραμματισμού και ταλαιπωρούμαι πάνω από μια εβδομάδα χωρίς αποτέλεσμα. Αποβλέπω στην ταχεία απάντηση σας.Ευχαριστώ.

**Comment by dmihos** [comment]
Καλησπέρα σας
Στον οδηγό για το integration με το shopify (https://github.com/VivaPayments/API/wiki/Shopify-Integration), υπάρχει ένα section με τίτλο Prerequisities. 
Έχετε εκτελέσει αυτά τα βήματα;
