### ISSUE TITLE
Ενεργοποίση άλλης πηγής

### ISSUE THREAD

**Issue by alexanderthedev** [VivaPayments/API#277]
Καλησπέρα σε όλους,

Έχω ενεγοποιήση άλλη μια πηγή για το api και περιμένω 4 μέρες να εγκριθεί/ενεργοποιηθεί. μπορούμε να κάνουμε γι αυτό μιας και είναι σημαντικό εργαλείο δουλειάς; Και γενικά θα θελα να ξερώ πόσες μέρες χρειάζεται για να κάνετε τον έλεγχο και να το ενεργοποιήσετε;

Ευχαρτιστώ.

**Comment by dmihos** [comment]
Καλησπέρα σας
Συνήθως η έγκριση γίνεται σε 1-2 μέρες. 
Πολλές φορές απαιτούνται διευκρινήσεις ή διορθώσεις, οπότε, σε αυτή την περίπτωση, η αρμόδια ομάδα επικοινωνεί μαζί σας με email.
Αν δεν υπάρχει εκκρεμότητα και συνεχίζετε να έχετε πρόβλημα, μπορείτε να στείλετε ένα email στο merchants@vivawallet.com για το θέμα.
