### ISSUE TITLE
demo.vivapayments.com does not accept test card

### ISSUE THREAD

**Issue by konstpan** [VivaPayments/API#278]
Hello,

I'm trying to use demo.vivapayments.com, redirect checkout, with https, but it seems like it does not accept your test card (4111 1111 1111 1111 with any valid date and 111 for the CVV2). 
It returns back to fail url.

**Comment by dmihos** [comment]
Hi, the card works OK in the demo environment.
What is the amount you're trying to charge?

**Comment by konstpan** [comment]
It's 0,01

I just tried and still does not work. 

Do you think it's possible to have a look in your logs t for the reason, the latest transaction id was 2934991286272607

**Comment by dmihos** [comment]
Request amount cannot be lower than calculated commissions, so please try with a larger amount (>0.30euro).

**Comment by konstpan** [comment]
OK. The amount was indeed the cause of the problem.

The transaction went smoothly with test card.

**Comment by big89** [comment]
Hello,

We are having some problem while using test card details on Viva Wallet Demo Environment.
It gives error as : The Transaction failed.
We tried many times but not working.

Recent Txn Id : 2966535932272607

Our Demo Merchant Id : 58132157-baf5-4554-8229-d95d238a64c0

Can anyone please look into this and let us know the issue on priority.

Thanks,
Logicmaker

**Comment by big89** [comment]
Hello,

Yes, as per integration guide provided, we are using redirect approach to
integrate Viva Payments on Website using PHP.

We are able to create order and redirect customer to Viva secured payment
page.

When we are entering test card details, it gives mentioned error.

Can you please check logs for our demo merchant account and let me know
exact issue.

Thanks,
Logicmaker

**Comment by HumayunE** [comment]
Hi All,
I used the first method 'Redirect' When I add test card details and make payment.
'This card does not support electronic transactions' appears on next page.
Can anybody help me?
Thanks,
Heymi

**Comment by plakidas** [comment]
Have that project https://github.com/plakidas/vivapayment-blazor and have issues to get payment using c# blazor. 
Need help
Thank you
