### ISSUE TITLE
Wordpress Integration

### ISSUE THREAD

**Issue by jtoumpis** [VivaPayments/API#279]
Hi,

Do you have any plugin for wordpress integration or an easy way to do it on a wordpress platform? I tried the manual however i do not know how to use these methods..

Thanks

**Comment by dmihos** [comment]
Hi, we don't offer a Wordpress plugin yet, but you will be able to find some 3rd party plugins for woocommerce that are known to work.

**Comment by dmihos** [comment]
Hi, please check the available Wordpress plugins [here](https://github.com/VivaPayments/API/tree/master/Plugins/wordpress)
