### ISSUE TITLE
NativePayment API - CORS problem

### ISSUE THREAD

**Issue by kostas-brainbox** [VivaPayments/API#28]
Hello,
I have a problem when trying to create an order with the demo native payment api.
The problem seems to be CORS(Cross-Origin Requests) 

The error message I get in the console is:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://demo.vivapayments.com/api/cards?key=XXXXX. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

I have checked the headers and it seems that my script is sending the website url as origin e.g.
```
Origin: http://www.example.com
```
But your script doesn't answer with the header needed for CORS to work e.g.
```
Access-Control-Allow-Origin: http://www.example.com
```
instead there is no header for Access-Control-Allow-Origin.

Can you please check that your script works with CORS and add the header if not. 

Thanks

**Comment by dpnevmatikos** [comment]
Hi there Kostas,
Could you please provide more info about this issue? Especially agent details and where are you running native checkout from.
Keep in mind that if you are developing with Chrome locally then CORS will not work.
Check [this issue](https://code.google.com/p/chromium/issues/detail?id=67743) from the Chromium project repository for more details.

**Comment by kostas-brainbox** [comment]
Hey,
thanks for the reply.
I am testing this from Firefox 41.x but also tried it in Chrome 45.x. 
I am running Windows 7 but this also tried Windows 8 and 10. I think all modern browsers have CORS implemented so I suppose this issue affects all modern browsers.

I checked the link you have provided but it is from 2010 and lots have changed. Also this link refers to not accepting localhost which is not the case here. Your server doesn't respond with the "Access-Control-Allow-Origin" header at all. It is not a matter of the domain not being matched.

I think the solution should be that your server responds with the "Access-Control-Allow-Origin" either with the the domain or * for accepting all domains.

As the error from my javascript console suggests
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://demo.vivapayments.com/api/cards?key=xxx. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```


Thanks

**Comment by dpnevmatikos** [comment]
Hi again Kostas,
Well, from what I see Native Checkout works perfectly both in Firefox (v41.0.1) and Chrome (v45.0.24).

I did notice however that when the public key is incorrect, the call to ```/api/cards``` fails with 404 and Chrome (for some unknown reason to me) after the 404 message shows the one you mentioned: 
![chrome-error](https://cloud.githubusercontent.com/assets/1810462/10516301/50f79f30-7360-11e5-9f06-61e54f2f29d5.PNG)

Firefox on the other hand only logs the 404 message: 
![ff-error](https://cloud.githubusercontent.com/assets/1810462/10516337/7f86612e-7360-11e5-9bcd-59bc980e6f93.PNG)

So I strongly recommend that you double check your ```public key``` by visiting the [Merchant's profile page](http://demo.vivapayments.com/selfcare/en-us/security/apiaccess) at ```General``` > ```Native/Pay with Viva Wallet Checkout```

Just for clarity reasons you can find the code that I used [here](https://gist.github.com/dpnevmatikos/c6deaf886b6e36628431)

As for the Chromium issue: it is indeed old but please notice that it was closed relatively recently and it's status is ```WontFix```. So it's actually still valid.

**Comment by MahbbRah** [comment]
The same problem with me. It's creating CORS problem with firefox, Chrome, in local and in server host also. Here is the error message: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://demo.vivapayments.com/api/cards?key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
