### ISSUE TITLE
Νέα πηγή πληρωμών

### ISSUE THREAD

**Issue by kesidaki** [VivaPayments/API#281]
Καλησπέρα, κάναμε μία νέα πηγή πληρωμών για τη σελίδα μας (1151.gr)
Θα ήθελα αν μπορείτε να μου πείτε περίπου πότε θα έχουμε απάντηση και αν λάβατε το email που είχαμε στείλει με τα στοιχεία των 2 σελίδων που χρησιμοποιούνται για πληρωμές και του λογαριασμού (στάλθηκε από διαφορετικό email από αυτό που αντιστοιχεί στο λογαριασμό, επισυνάψαμε τα στοιχεία του λογαριασμού φυσικά).

Το merchant_id του συγκεκριμένου λογαριασμού είναι:
cf3d8c5e-e8c6-423a-869c-8878f7e0e304

**Comment by kesidaki** [comment]
Μήπως υπάρχει κάποια ενημέρωση; Έχει περάσει πάνω από μία εβδομάδα που προσθέσαμε τη νέα πηγή πληρωμών και δεν έχουμε πάρει καμία απάντηση

**Comment by dmihos** [comment]
Παρακαλώ απευθυνθείτε στην αρμόδια ομάδα, με ένα email στο merchants@vivawallet.com
