### ISSUE TITLE
VivaPay Payment Gateway

### ISSUE THREAD

**Issue by IllusionsD** [VivaPayments/API#282]
Καλησπέρα,

Έχουμε αγοράσει ένα eshop από το woocommerce μέσα απο το papaki.gr. Αυτό εχει ήδη μέσα το VivaPay Payment Gateway. Το κατάστημα Illusions D. έχει ήδη συμφωνία με την Viva.
Για ενεργοποίηση στο eshop ζητάει
VivaPayments Merchant ID
VivaPayments API key
VivaPayments CodeId

Που θα βρούμε τα παραπάνω και ποια ειναι η διαδικασία ενεργοποίσης

Ευχαριστω

**Comment by dmihos** [comment]
Καλησπέρα σας
Εφόσον έχετε account παραγωγής, στο μενού "Ρυθμίσεις>Πρόσβαση API" θα βρείτε τα MerchantId και Apikey. Το CodeId υποθέτω είναι το SourceCode, οπότε θα το βρείτε στο μενού "Οι πωλήσεις μου>Πηγές πληρωμών".

**Comment by IllusionsD** [comment]
Merchant ID	68013caf-7e8e-43ef-868d-cd9e45e8940d
API Key	l4Sx#W

to source code υποθέτω ειναι το 4081αλλά εχει επιλογή και για default

Μου βγάζει μύνημα όταν κανω μια αγορα 
Ευχαριστούμε - η παραγγελία αναμένει πληρωμή. Θα μεταφερθείτε αυτόματα στη Vivapayments για να πραγματοποιήσετε πληρωμή.

Λάθος στοιχεία εμπόρου ή το API δεν λειτουργεί.

Μπορείτε να το δείτε εσείς;

Ευχαριστώ

**Comment by IllusionsD** [comment]
l4Sx#W API Key

**Comment by dmihos** [comment]
Δε χρειάζεται το api key στην απάντησή σας.
Θα πρέπει να αλλάξετε το url από demo σε https://www.vivapayments.com

**Comment by IllusionsD** [comment]
ok Ευχαριστώ λειτουργεί
