### ISSUE TITLE
VivaPay Payment Gateway 

### ISSUE THREAD

**Issue by IllusionsD** [VivaPayments/API#284]
Καλησπέρα,

Έχουμε αγοράσει ένα eshop από το woocommerce μέσα απο το papaki.gr. Αυτό εχει ήδη μέσα το VivaPay Payment Gateway. Το κατάστημα Illusions D. έχει ήδη συμφωνία με την Viva.
Για ενεργοποίηση στο eshop ζητάει
VivaPayments Merchant ID
VivaPayments API key
VivaPayments CodeId

Που θα βρούμε τα παραπάνω και ποια ειναι η διαδικασία ενεργοποίσης

Ευχαριστω

**Comment by dmihos** [comment]
Καλησπέρα σας
Τα 2 πρώτα θα τα βρείτε, μετά από login με το εμπορικό σας προφίλ, στο μενού "Ρυθμίσεις > Πρόσβαση API".
To τελευταία, υποθέτωντας ότι εννούν το SourceCode, αυτό θα το βρείτε στο μενού "Οι Πωλήσεις μου > Πηγές πληρωμών"

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
