### ISSUE TITLE
How to save customer payment card details and make the charge later (can be after 6 months) 

### ISSUE THREAD

**Issue by eefth** [VivaPayments/API#285]
Καλησπερα σας, 
Θα ήθελα να ρωτήσω για το ποιες ειναι οι κλήσεις του API και οι παράμετροι που απαιτούνται για να σώσω τα card details του πελάτη, αλλα η χρέωσή του να γίνει με την έναρξη της υπηρεσίας που προσφέρω (δηλαδή μετά απο μια χρονική περίοδο που μπορει να υπερβαίνει το 6μηνο), χωρίς να ξαναζητήσω τα  card details του. Ποια ειναι τα API calls που πρεπει να χρησιμοποιήσω για αυτη την περίπτωση? Πρέπει πρώτα να κανω μια χρέωση του πελάτη, ωστε να σωσω στους server μου το transactionId και να κάνω καποια άλλη κλήση για να κάνω καινούρια χρέωση με άλλο ποσό παιρνώντας αυτο το transactionId?
Εχω χρησιμοποιήσει μέχρι τώρα:
1. POST  /api/Orders με παραμέτρους: Amount, SourceCode, Email, FullName, Phone 
2. POST  /api/cards?key=apiPublicKey με παραμέτρους Number, CVC, ExpirationDate, CardHlderName
3. POST /api/transactions με παραμέτρους OrderCode (απο το βήμα 1), SourceCode, CreditCard{Token (απο το βήμα 2)} με αποτέλεσμα να κάνω την χρέωση επιτυχώς.
4. Μετά όμως για να κάνω καινούρια χρέωση χρησιμοποιώ το TransactionId απο το βήμα 3 και κανω την κληση POST /api/transactions{transactionId} αλλά πάντα λαμβάνω error (The transaction af5c2dba-ba0f-415d-9f7d-69e0af9ead02 does not allow recurring charge)

Να τονίσω οτι δε με ενδιαφέρει recurring χρέωση αλλα χρέωση με αλλο ποσό του ίδιου πελάτη χωρις να ξαναεισαχθούν τα στοιχεία της κάρτας του.

Χρησιμοποιώ native checkout και demo environment.
Ευχαριστώ, 
Θέμης

**Comment by dmihos** [comment]
Καλησπέρα σας

Αν το βήμα (2) το εκτελείτε μόνος σας, τότε φαίνεται πως δεν έχετε κάνει [τη σωστή χρήση της native checkout](https://github.com/VivaPayments/API/wiki/Native-Checkout).
 
Σχετικά με το ερώτημά σας, αυτό που χρειάζεστε είναι τα [Recurring Payments](https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction). 
Αυτά αφορούν χρεώσεις που γίνονται με δική σας κλήση στο API, για οποιοδήποτε ποσό, χρησιμοποιώντας το transactionid. Δε σχετίζονται με αυτόματες επαναλαμβόμενες χρεώσεις, παρότι το όνομα ίσως εκεί παραπέμπει.
Πρέπει όμως:
- Στο βήμα (1) να περάσετε την παράμετρο AllowRecurring = true
- Να εμφανίσετε ένα checkbox στο χρήστη, με το οποίο θα συναινεί στη χρέωση που σκοπεύετε να κάνετε στην κάρτα του αργότερα
- Στο βήμα (3), και εφόσον έχει συναινέσει ο χρήστης, να περάσετε την παράμετρο AllowsRecurring = true (προσοχή στο extra 's' που παίρνει αυτό το property)

Κατόπιν αυτών, το βήμα (4) θα επιτύχει.

**Comment by eefth** [comment]
Ευχαριστώ, παιζει! 
Υπαρχει η δυνατοτητα να κάνω τα βήματα 1, 3 χωρις να χρέωσω τον πελάτη και να χρεώσω τον πελάτη μόνο στο βήμα 4? Π.χ αν μεταξυ των 1,3 παρεμβάλω μια κλήση PATCH /api/orders/{OrderCode} (με το OrderCode απο το βήμα 1) με Amount=0

**Comment by dmihos** [comment]
Όχι δεν υπάρχει τέτοια δυνατότητα.

Σημειώστε, ξανά, ότι αν δε χρησιμοποιείτε την native checkout σύμφωνα με τον ενδεδειγμένο τρόπο, τότε ενδέχετε να μη σας επιτραπεί η χρήστη της υπηρεσίες, η πηγή δλδ να μην εγκριθεί.

**Comment by eefth** [comment]
Μάλιστα.
Εχω αφαιρέσει το βημα το 2 και η χρήση της native checkout γινεται συμφωνα με το  με τον ενδεδειγμένο τρόπο παιρνώνατς τα σοτιχεια της κάρτας του πελάτη κάνοντας χρήση της φορμας και του https://www.vivapayments.com/web/checkout/js, ακολουθώντας δηλαδή τα βήματα που αναφέρονται στο https://github.com/VivaPayments/API/wiki/Native-Checkout.
Ευχαριστώ για την άμεση απάντησή σας

**Comment by eefth** [comment]
Καλησπερα και χρονια πολλα,

Εχω μια μηχανη κρατήσεων για ξενοδοχεία και θελω να κάνω capture τα στοιχεια της καρτας του πελάτη χρεώνοντας τον αναγκαστικά (λόγω της viva)την ελάχιστη χρέωση αλλά να του επιστρέψω άμεσα την ελάχιστη χρέωση και στη συνέχεια η κανονική χρέωση για την υπηρεσία να γίνει μετα απο μια χρονική περίοδο π.χ όταν ο πελάτης έρθει στο ξενοδοχείο. 
Επίσης, στην περίπτωση που ο πελατης κανει ακυρωση κράτησης μετα απο ενα ορισμενο χρονικο διαστημα (που μπορει να υπερβαινει την ιδια ημερα) πως μπορώ να του επιστρέψω την ελάχιστη χρέωση που του έχω κάνει? 
Μπορώ να χρησιμοποιήσω κάποια απο τα CancelTransaction/CancelOrder στις 2 περιπωσεις? 
Υπάρχει καποιο ιστορικο με ανάλογη διαδικασία που χρησιμοποιει την viva?
Κάποια payment gateways κανουνε μια ελάχιστη χρέωση για να πάρουν τα στοιχεία του πελάτη επιστρέφοντας του αυτομάτως άμεσα την ελάχιστη χρέωση.

**Comment by dmihos** [comment]
Καλησπέρα σας
Η λογική που περιγράφετε είναι σωστή.
Μετά τη μικροχρέωση, μπορείτε να κάνετε αμέσως ακύρωση ([CancelTransaction](https://github.com/VivaPayments/API/wiki/CancelTransaction)), ώστε για την κανονική χρέωση να εκτελέσετε [Recurring Transaction](https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction).
Το Recurring Transaction μπορεί να εκτελεστεί ακόμη κι αν ακυρώθηκε το αρχικό charge.

**Comment by eefth** [comment]
Μπορω να κανω CancelTransaction οποιοδηποτε χρονικο διαστημα μετα τη μικροχρέωση π.χ. οχι μονο μεσα στην ιδια μερα, αλλα μετα απο καποιες μερες-μηνες?

**Comment by eefth** [comment]
Καλησπερα σας και παλι, 
Οσον αφορα το CancelTransaction (οχι για τη μικροχρέωση αλλα γενικα ας πουμε στην περιπτση που ο πελάτης θέλει να ακυρώσει μια κρατηση και να του επιστραφουνε τα λεφτα), μπορώ να το κάνω οποιαδηποτε στιγμή μετά απο ενα αρχικο Transaction που εχει γίνει ή μονο την ιδια business day?
Ευχαριστω.

**Comment by dmihos** [comment]
Μπορεί να γίνει οποιαδήποτε στιγμή, εφόσον η κάρτα είναι ενεργή (δεν έχει λήξει / ακυρωθεί).
Αυτό που αφορά το "same business day", είναι ότι την ίδια μέρα μπορείτε να κάνετε <u>μόνο</u> πλήρη επιστροφή (ακύρωση), ενώ μετά μπορείτε να κάνετε και μερικές επιστροφές (partial refunds).

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
