### ISSUE TITLE
Payments with Viva Transaction Failed error 502

### ISSUE THREAD

**Issue by LetsFerry** [VivaPayments/API#286]
Hello,
I would like to know why there are so many transactions failing?
I always get the error 502.
"Data": {
    "StatusId": "E",
    "TransactionId": "b8159916-212a-45e9-a1ea-59ae06fa212a",
    "ErrorCode": 502,
    "ErrorText": "Transaction failed",
    "TimeStamp": "2017-04-11T07:48:10.1919194+03:00"
  },
Does anyone know how to resolve this?

**Comment by dmihos** [comment]
Hi
If the problem does not seem to relate to a technical integration issue, please contact merchants@vivawallet.com
