### ISSUE TITLE
Πηγές πληρωμών σε Εκκρεμότητα

### ISSUE THREAD

**Issue by nikvaf** [VivaPayments/API#288]
Καλησπέρα σας,

έχω ενεργοποιήσει 2 νέες πηγές πληρωμών στον επαγγελματικό μου λογαριασμό και είναι σε εκκρεμότητα (ΑΦΜ 998096689).

Υπάρχει κάποιος τρόπος σας παρακαλώ να επισπεύσουμε την διαδικασία ελέγχου γιατί θα θέλαμε να ανεβάσουμε live το eshop το συντομότερο δυνατόν?

Σας ευχαριστώ πολύ

**Comment by dmihos** [comment]
Καλησπέρα σας
Θα πρέπει να απευθυνθείτε στο merchants@vivawallet.com για αυτό το θέμα.
Ευχαριστούμε
