### ISSUE TITLE
ΠΡΟΒΛΗΜΑ ΠΛΗΡΩΜΗΣ ΜΕΣΩ VIVA

### ISSUE THREAD

**Issue by Panos16** [VivaPayments/API#289]
Καλησπερα σας και χρονια πολλα.

Μετά την έγκριση του domain του site μας απο εσάς και στον έλεγχο που έγινε απο τους developers μας δεν υπήρχε κανένα πρόβλημα.
όμως απο την Παρασκευή 07/04/2017 και μετά απο δοκιμή που κάναμε οι ίδιοι, δεν μπορεί να πραγματοποιηθεί πληρωμή μέσω του συστήματος σας και σας στέλνω και το μήνυμα που παρουσιάζεται στην οθόνη μου σε μορφη φωτογραφίας για να μπορέσετε να εξακριβώσετε το τι συμβαίνει.
Αναμένω την απαντησή σας.
Ευχαριστώ

**Comment by Panos16** [comment]
Παρακαλώ μπορείτε να απαντήσετε?

**Comment by paucov** [comment]
Αρχικά θα συνιστούσα να αφαιρέσεις την φωτογραφία απο την στιγμή που φαίνονται οι κωδικοί σου (merchantId and APIKey).

Εγώ έλυσα το πρόβλημα στα δικά μου site αφαιρώντας από το curl_setopt την σταθερά CURLOPT_SSL_CIPHER_LIST

Ελπίζω να σε βοηθήσει.

**Comment by Panos16** [comment]
Ευχαριστω για την συμβουλη την κατεβασα.
Με βοηθησε, Πλεον το συστημα δουλευει.
Σε ευχαριστω πολυ.
