### ISSUE TITLE
Μετάβαση από DEMO σε LIVE

### ISSUE THREAD

**Issue by melcon77** [VivaPayments/API#290]
Κάναμε τις δοκιμές στο demo περιβάλλον και όλα λειτουργούν OK (οι πληρωμές περνάνε στο demo περιβάλλον και τις βλέπουμε στις πωλήσεις). 
Ποια είναι τα βήματα για να περάσουμε σε live καθώς αλλάξαμε τα παρακάτω, τεσταραμε με κανονική πιστωτική κάρτα αλλά δεν καταφέραμε να δούμε την πληρωμή στο Viva live.
•	baseURL
•	publicKey 
•	MerchantId
•	SourceCode

**Comment by dmihos** [comment]
Καλησπέρα σας
Εφόσον έχετε δημιουργήσει account στην παραγωγή (https://www.vivawallet.com), θα πρέπει να στείλετε στο merchants@vivawallet.com τα στοιχεία του λογαριασμού σας, με αναφορά στο παρόν github issue, για περαιτέρω διερεύνηση.

**Comment by melcon77** [comment]
Στο ----Πρόσβαση API/Γενικά/API Key  --- πρέπει να γράψουμε κάτι εμείς γιατί βλέπω ότι μπορώ να το αλλάξω (βλέπε φώτο)
![1](https://cloud.githubusercontent.com/assets/25766451/25446244/a38ed10c-2ab9-11e7-9326-472e9265c75d.gif)

**Comment by dmihos** [comment]
Το ApiKey χρησιμοποιείται ως password στην επικοινωνία με το Api. Στην περίπτωση της Native Checkout, χρησιμοποιείται στο τελευταίο βήμα, για τη δημιουργία Order και την εκτέλεση της συναλλαγής. Αν το αλλάξετε, θα πρέπει να φροντίσετε, αντίστοιχα, ο κώδικας να ενημερωθεί.

**Comment by melcon77** [comment]
Καλησπέρα  σας

Στείλαμε όπως μας συμβουλέψατε αίτημα στο  merchants@vivawallet.com (CC-502477) από το οποίο μας επιβεβαίωσαν ότι ο λογαριασμός είναι ενεργοποιημένος (Api Native). Μας ρώτησαν επίσης αν επιστρέφει κάποιο error code και η απάντηση μας ήταν πως αρνητική καθώς δεν επιστρέφει κάποιο error όπως και στην περίπτωση του demo (δεν υπάρχει κάποια διαφορά).
Αρχικά φτιάξαμε την σύνδεση με το demo περιβάλλον και όλα λειτουργούσαν OK (οι χρεώσεις πηγαίναν στο demo της Viva). Μετά αλλάξαμε μόνο τις παραμέτρους που αναφέρω και παραπάνω, και ενώ από εμάς φαίνεται ότι όλα είναι ΟΚ (όπως και στο demo), τελικά όμως δεν βλέπουμε την χρέωση στο live περιβάλλον της Viva.

Σύνοψη:
**-στο demo λειτουργούμε κανονικά
-Ο λογαριασμός για api Native είναι ενεργοποιημένος
-Δεν επιστρέφει κάποιο error code
-για να περάσουμε στο live έχουμε αλλάξει μόνο τις παραμέτρους**

Παρακαλούμε πολύ για την όσο το δυνατόν αμεσότερη βοήθεια σας η οποία νομίζουμε ότι μπορεί πλέον να είναι αποτελεσματική μόνο με **απευθείας επικοινωνία με τον μηχανικό μας** του οποίου τα στοιχεία υπάρχουν στον **issue number CC-502477.**

Ευχαριστούμε πολύ εκ των προτέρων

**Comment by melcon77** [comment]
Υπάρχει κάποια εξέλιξη για το ανωτέρω issue?

**Comment by dmihos** [comment]
Καλημέρα σας

Η αποτυχία εκτέλεσης συναλλαγής συνοδεύεται πάντα από σχετικό μήνυμα λάθους (και σχετικό http status code), κάτι που δε φαίνεται να χειρίζεστε σωστά με τη τεχνική υλοποίηση που έχετε κάνει.

Ο λογαριασμός σας έχει ελεγχθεί και δεν παρουσιάζει κάποιο πρόβλημα.
Πήραμε το παράδειγμα κώδικα native checkout που θα βρείτε [εδώ](https://github.com/VivaPayments/API/tree/master/NativeCheckout/ASP.NET), βάλαμε τα στοιχεία του λογαριασμού σας και εκτελέσαμε συναλλαγή χωρίς πρόβλημα (θα δείτε μια αποτυχημένη χρέωση στις σημερινές πωλήσεις σας, βάλαμε επίτηδες λάθος ημ/νία λήξης σε μια κανονική κάρτα).

Σχετικά με τα σημεία που πρέπει να αλλάξουν στον κώδικά σας, προκειμένου να βγείτε live, και σχετικά με τον οδηγό της [Native Checkout](https://github.com/VivaPayments/API/wiki/Native-Checkout), αυτά είναι:

Τα scriptUrl, publicΚey και baseURL στο client part (javascript)
Τα _MerchantId, _ApiKey, _baseApiUrl και OrderCode στη δημιουργία Order και την εκτέλεση της συναλλαγής με το token.

Όταν ο τεχνικός σας έχει κάποιο συγκεκριμένο μήνυμα σφάλματος, μπορεί να το αναφέρει εδώ για να δωθούν διευκρινήσεις, αν χρειάζονται.

Επίσης, κοιτώντας το λογαριασμό σας, βλέπουμε πως δεν έχετε καν δημιουργήσει Order στο παραγωγικό περιβάλλον.  Άρα δείτε αρχικά το βήμα CreateOrder.

Αν ο κώδικάς σας είναι γραμμένος σε php και το περιβάλλον είναι linux/unix based, μπορείτε να δείτε και το παρακάτω, που συχνά λύνει προβλήματα σε τέτοια περιβάλλοντα.
https://github.com/VivaPayments/API/issues/144

Μερικές φορές, επίσης, λόγω ελλιπούς υλοποίησης, κάποιοι έμποροι αντιμετωπίζουν πρόβλημα όταν το ApiKey περιέχει special characters, οπότε αλλάξτε και αυτό, αν θέλετε.

Είμαστε στη διάθεσή σας για κάθε διευκρίνηση.

**Comment by melcon77** [comment]
**Ελέγξαμε τα θέματα που μας αναφέρατε και σχόλια μας βρίσκονται στο συνημμένο pdf:**

[Απάντηση.pdf](https://github.com/VivaPayments/API/files/986520/default.pdf)

Ευχαριστούμε πολύ εκ των προτέρων

**Comment by dmihos** [comment]
Λυπάμαι, θα πρέπει ο τεχνικός σας να δει το θέμα πιο διεξοδικά.

Αν ο κλήσεις σας φτάνουν στο api μας (κάτι που φαίνεται ότι ΔΕ συμβαίνει), τότε θα παίρνετε σωστά error codes, αναλόγως την επιτυχία ή όχι.

Η συναλλαγή που κάναμε εμείς, φαίνεται στο λογαριασμό σας, αν επιλέξετε στο φίλτρο να βλέπετε και τις αποτυχημένες (Οι πωλήσεις μου > Πωλήσεις > Σύνθετη αναζήτηση > Παρατηρήσεις > Προσθήκη "Αποτυχημένη").

Επίσης, δείτε ξανά το issue #144 που αναφέρθηκε παραπάνω.
Υποθέτω εκεί είναι το πρόβλημα.
Το παραγωγικό περιβάλλον υποστηρίζει διαφορετικό cipher list, για λόγους ασφαλείας. Αρκετά (παλαιότερα κυρίως) λειτουργικά έχουν προβλήματα σύνδεσης.
Με λίγα λόγια, δείτε με τους τεχνικούς υποδομής/φιλοξενίας του site σας, αν μπορούν να προσπελάσουν, από το server σας, το https://www.vivapayments.com.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
