### ISSUE TITLE
Πρόβλημα με πληρωμή σε viva από magento στο redirect

### ISSUE THREAD

**Issue by Periclesimb** [VivaPayments/API#291]
Έχουμε εγκαταστήσει το extension magento/maghellaspay στο magento
Έχουν γίνει όλες οι ρυθμίσεις όπως μπορείτε να δείτε και στις φωτογραφίες

http://imgur.com/WpWAfcD
http://imgur.com/c1uLWRW

Όταν πας να κάνεις την πληρωμή κολλάει στο domain.gr/hellaspay/hpay/redirect/
χωρίς να βγάζει κάποιο error.

Η έκδοση του magento είναι 1.9.3.0 και έχει χρησιμοποιηθεί παλαιώτερα το ίδιο extension σε άλλο eshop χωρίς πρόβλημα.

Μπορείτε να βοηθήσετε ;
Ευχαριστώ

**Comment by VivaWalletSupport** [comment]
Hello Pericles, please check if the payment source has been activated in the viva account, if the module is enabled in the store (system/config/advanced), in case the compiler is running to stop it or recompile, clear cache and verify that the design files have also been copied to the used theme.
