### ISSUE TITLE
Redirect URL δεν λειτουργεί

### ISSUE THREAD

**Issue by EunoiaOWS** [VivaPayments/API#294]
Καλησπέρα, 

Έχουμε εγκαταστήσει το vivawallet σε wordpress site και έχουμε πρόβλημα μετά την πληρωμή με το success/ fail URL. Ο πελάτης χρεώνετε διπλά επειδή το success url δεν λειτουργεί και ξανά βάζεις τα στοιχεία του και χρεώνετε 2 φορές.

Απ ότι βλέπω  στο dashboard του Vivawallet  "οι πληρωμές μου" ->"Επεξεργασία πηγής πληρωμών" στο URL Επιτυχημένης συναλλαγής έχουμε todomainmou.gr/ wc-api/WC_em_Vivapayments_Gateway αλλά δεν λειτουργεί αυτό. Είναι σωστό η πρέπει να βάλω κάποιο αλό σύνδεσμο;

**Comment by dmihos** [comment]
Καλησπέρα σας
Έχετε εγκαταστήσει [ένα από αυτά τα plugins](https://github.com/VivaPayments/API/tree/master/Plugins/wordpress) ή κάποιο 3rd party;

**Comment by EunoiaOWS** [comment]
Όχι δεν χρησιμοποιώ τα πρόσθετα που αναφέρεις. Τώρα άλλαξα το success url και έβαλα το σύνδεσμο παραγγελία ελήφθη - Πως μπορώ εγώ τώρα να το τεστάρω το vivapayments gateway σε live site;

**Comment by dmihos** [comment]
Χρειάζεστε ένα live εμπορικό account, δεν υπάρχουν δοκιμαστικά/demo accounts εκεί.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
