### ISSUE TITLE
DisableIVR does not seem to be working

### ISSUE THREAD

**Issue by LefterisL** [VivaPayments/API#295]
Hello,

I'm trying to disable with IVR option when creating an order id but it still seems to be showing up on the payment page.

Below is a preview of the parameters i have, the postfields i'm passing into the curl and the return from the server.

Array
(
    [PaymentTimeOut] => 65535
    [RequestLang] => en-US
    [MaxInstallments] => 1
    [SourceCode] => XXXX
    [DisableIVR] => 1
    [DisableCash] => 1
    [DisablePayAtHome] => 1
    [Amount] => 3350
    [MerchantTrns] => 55
)

PaymentTimeOut=65535&RequestLang=en-US&MaxInstallments=1&SourceCode=XXXX&DisableIVR=1&DisableCash=1&DisablePayAtHome=1&Amount=3350&MerchantTrns=55&

stdClass Object
(
    [OrderCode] => 9903520425172607
    [Success] => 1
)

https://demo.vivapayments.com//web/checkout?ref=9903520425172607

Am i missing something here ?

**Comment by LefterisL** [comment]
Any news on that?

**Comment by dmihos** [comment]
Hi
Although I can't try curl right now, I'm pretty sure the boolean flags need to pass as true/false, rather than 1/0
Please try that and let us know.

**Comment by LefterisL** [comment]
Seems to be working like so.  Appreciate it!
