### ISSUE TITLE
Amex card is not working

### ISSUE THREAD

**Issue by Tejas-narola** [VivaPayments/API#296]
We are getting 502 error for when we are using Amex card. Same APIs are working on VISA/Master card. Would you please let us know what could be the issue?

**Comment by christianago** [comment]
I am also having this issue.
American Express cards are denied.
Can you please also advise on the correct card input data types?

**Comment by dmihos** [comment]
Due [to different commission rates](https://www.vivawallet.com/en-us/business/pricing) that apply on American Express cards, the merchant needs to explicitly enable it via Menu>Settings>Profile

**Comment by christianago** [comment]
The merchant:2be14b87-0ca1-496d-a569-407cf5b9b992
has already activated Amex cards.

**Comment by dmihos** [comment]
Then please contact merchants@vivawallet.com with full merchant details, for further investigation.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
