### ISSUE TITLE
Πρόβλημα με ελληνική πηγή πληρωμών

### ISSUE THREAD

**Issue by nikvaf** [VivaPayments/API#297]
Καλησπέρα,

θα ήθελα να σας αναφέρω ένα πρόβλημα που αντιμετωπίζουμε με την ελληνική πηγή πληρωμών (8346) του πελάτη μου (ΑΦΜ 998096689).

Ενώ η αντίστοιχη αγγλική πηγή (3751) λειτουργεί κανονικά, όταν γίνεται μια ηλεκτρονική παραγγελία από το ελληνικό site, άρα και από την ελληνική πηγή πληρωμών, η παραγγελία γίνεται κανονικά αλλά μου επιστρέφεται error message. 

Σας ευχαριστώ πολύ

**Comment by dmihos** [comment]
Καλησπέρα σας
Θα πρέπει να δείτε την υλοποίηση που έχετε κάνει, δεν υπάρχει κάποιο πρόβλημα με το λογαριασμό ή την πηγή 8346 (κάναμε μόλις μια δοκιμή, OrderCode 7221023084372601)
