### ISSUE TITLE
 Η συναλλαγή σας απέτυχε. VivaPayments

### ISSUE THREAD

**Issue by dgrigoriadis** [VivaPayments/API#298]
Καλησπέρα,

Έχω κάνει όλες τις απαραίτητες ενέργειες για τις συναλλαγές μέσω viva.
Κατά το checkout όταν επιλέγω πληρωμή με VivaPayments με πετάει σε ασφαλές παράθυρο για την καταχώρηση στοιχείων της κάρτας, αφού συμπληρωθούν όλα τα στοιχεία ( δοκιμάστηκε με δύο κάρτες) και πατήσω ολοκλήρωση με βγάζει " Η συναλλαγή σας απέτυχε. VivaPayments ".
Συνημμένη θα βρείτε την φωτογραφία.

Ευχαριστώ
![error](https://cloud.githubusercontent.com/assets/28568734/25857276/3e4d08a4-34e1-11e7-8335-06aedccda407.jpg)

**Comment by dmihos** [comment]
Καλημέρα σας

Η οθόνη αυτή, πράγματι, δηλώνει πως η συναλλαγή απέτυχε.
Η ερώτησή σας ποια είναι;

Δε μας έχετε δώσει απολύτως κανένα στοιχείο για το λογαριασμό σας.
Είναι demo ή παραγωγικό; Το merchantId σας ποιο είναι; Το OrderCode που αποτυγχάνει;

Ευχαριστούμε για την επικοινωνία

**Comment by dmihos** [comment]
Η πηγή 1121 είναι marked ως native, θα πρέπει να χρησιμοποιήσετε μια πηγή τύπου Redirect.

(Στο screenshot φαίνεται το apiKey σας, **αλλάξτε το άμεσα**)

**Comment by dgrigoriadis** [comment]
Δεν μπορώ να χρησιμοποιήσω το native ως προεπιλογή;

**Comment by dmihos** [comment]
Οι πηγές τύπου Native μπορούν να χρησιμοποιηθούν μόνο σε native checkout υλοποιήσεις.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
