### ISSUE TITLE
Πρόβλημα με failed transactions σε success page

### ISSUE THREAD

**Issue by kostas-brainbox** [VivaPayments/API#299]
Καλησπέρα,
έχουμε μία υλοποίηση του viva wallet με redirect για πληρωμές σε ιστοσελίδα πελάτη μας.

Εφόσον όλα πάνε καλά με την με την πληρωμή στην πλευρά της viva γίνεται ένα redirect σε ένα success page και αν όχι σε ένα fail page.
Αν επιστρέψει στο success page δημιουργείται από εμάς ένα τιμολόγιο για την συναλλαγή.
Αν επιστρέψει σε fail page απλά ενημερώνουμε τον χρήστη ότι υπήρξε πρόβλημα χωρίς κάποια άλλη ενέργεια.

Κάποιες συναλλαγές επιστρέφουν σε success page και εμείς δημιουργούμε τιμολόγιο αλλά το περίεργο είναι ότι σε αυτές τις συναλλαγές φαίνεται (απο το api σας) ότι έχουν "StatusId":"E". Δηλαδή ότι εμφανίστηκε κάποιο πρόβλημα. 

Ένα παράδειγμα τέτοιου προβλήματος είναι το: 

OrderCode: 1281015285972609
merchant_id : 48049402-b9c0-4a01-aec4-9eaf9b3f865b
viva_source : 5835

Ευχαριστώ

**Comment by dmihos** [comment]
Καλησπέρα σας

Η συναλλαγή πράγματι απορρίφθηκε από την εκδότρια τράπεζα, οπότε έγινε redirect στη σελίδα failure.
Αν πιστεύετε ότι οι σελίδες σας λειτουργούν σωστά, τότε πιθανά ο χρήστης άλλαξε το url με το χέρι.
Η κλήση του url επιτυχίας δε θα πρέπει να είναι, από μόνη της, ικανή συνθήκη για έκδοση τιμολογίου.
Θα πρέπει να γίνεται πάντα confirm, μέσω του API.

Ευχαριστούμε για την επικοινωνία

**Comment by kostas-brainbox** [comment]
Καλημέρα,
γίνονται κάποιοι έλεγχοι στο success page( όπως αν η συναλλαγή έχει ξαναπεράσει) αλλά μάλλον δεν είναι αρκετοί και ικανοί.
Ο πιο σωστός έλεγχος θα ήταν να ελέγχουμε ότι το πρώτο transaction object το StatusId == F ;
Ευχαριστώ

**Comment by kostas-brainbox** [comment]
Τελικά το πρόβλημα ήταν κάτι διαφορετικό και έχει λυθεί.
Ευχαριστούμε.
