### ISSUE TITLE
Σφάλμα στο "παραγωγικό" περιβάλλον

### ISSUE THREAD

**Issue by nantoniadis** [VivaPayments/API#30]
Καλησπέρα,

Χρησιμοποιώ τον κώδικα όπως ακριβώς είναι, αλλάζοντας απλώς τις πληροφορίες μου. Στο demo περιβάλλον, όλα δουλεύουν κανονικά. Μόλις όμως αλλάξω το URL, το ID και το KEY για να χρησιμοποιήσω το παραγωγικό περιβάλλον, δε δουλεύει. Ο λογαριασμός μου είναι κανονικά ενεργοποιημένος και δέχεται πληρωμές.

Είτε φταίει με το API, είτε φταίει ο συγκεκριμένος κώδικας.

Σας ευχαριστώ εκ των πρωτέρων.

**Comment by dpnevmatikos** [comment]
Καλημέρα,

> Χρησιμοποιώ τον κώδικα όπως ακριβώς είναι,

Σε ποιον κώδικα αναφέρεστε?
Μπορείτε να μας δώσετε περισσότερες πληροφορίες για το τι προσπαθείτε να κάνετε και ποιο είναι το πρόβλημα που συναντάτε?

Ευχαριστώ.

**Comment by nantoniadis** [comment]
Καλημέρα,
Χρησιμοποιώ Redirect Checkout και πήρα το create_order.php

https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php

Ευχαριστώ

**Comment by dpnevmatikos** [comment]
Καλημέρα και πάλι,
Ενδεχομένως να υπάρχει θέμα με την έκδοση OpenSSL που έχει ο server σας.
Δείτε περισσότερα σε [αυτό το άρθρο](https://support.vivawallet.com/hc/communities/public/questions/200568401-Site-not-responding-when-called-from-PHP-code).

Ευχαριστώ.

**Comment by nantoniadis** [comment]
Τελικά ήταν πρόβλημα του SSL. Σας ευχαριστώ πολύ!
