### ISSUE TITLE
Η πληρωμή απέτυχε! 

### ISSUE THREAD

**Issue by NikosEpex** [VivaPayments/API#300]
Καλημέρα. Από την Παρασκευή το μεσημέρι μας βγάζει αποτυχία στις πληρωμές. Το redirect στη viva γίνεται κανονικά με το σωστό ποσό και βλέπουμε και το λογότυπο του καταστήματος. Συμπληρώνουμε τα στοιχεία για την πληρωμή και πατώντας χρέωση μας επιστρέφει στο eshop με σφάλμα. 

![fail](https://cloud.githubusercontent.com/assets/28726218/26098405/4dba30d8-3a30-11e7-94cc-532a056aeeea.jpg)

Κωδικός Πληρωμής: 3799280017572604 σήμερα το πρωί.
Δοκιμάσαμε με κάρτες από Alpha, Πειραιώς και 1 κάρτα εξωτερικού. 

Δεν έχουμε κάνει κάποια αλλαγή στον κώδικα. Χρησιμοποιούμε open cart με εμπορικό extension πάνω από 6 μήνες χωρίς πρόβλημα. Σας παραθέτω screenshot με τις ρυθμίσεις μας. 

![admin](https://cloud.githubusercontent.com/assets/28726218/26098441/6975c4ae-3a30-11e7-93b2-dcf311a440d2.jpg)
και η πηγή είναι ενεργή. 
![viva admin](https://cloud.githubusercontent.com/assets/28726218/26098456/769bb738-3a30-11e7-975a-6a2f29d34e06.jpg)

Βλέπετε κάτι λάθος από τη μεριά σας;

**Comment by dmihos** [comment]
Καλησπέρα σας
Ο κωδικός 3799280017572604 είναι για 0.04€. Δοκιμάστε με κάποιο μεγαλύτερο ποσό (>0.30€), καθώς δε μπορεί να εξοφληθεί τόσο μικρό ποσό.

**Comment by NikosEpex** [comment]
Με μεγαλύτερο ποσό πέρασε, έχετε δίκαιο, αλλά γυρνάει σε λευκή σελίδα με url

/index.php?route=payment/vivapayment/success&t=dc9826b2-6dbf-4285-ab61-c1f55963fd4d&s=4281335283772606&lang=el-GR

**Comment by dmihos** [comment]
Αυτό είναι κάτι που πρέπει να ελέγξετε στο site σας, σε σχέση με τα urls που έχετε δηλώσει στην πηγή
