### ISSUE TITLE
Πρόβλημα με επιτυχημένη συναλλαγή που δεν κάνει redirect στο success page

### ISSUE THREAD

**Issue by kostas-brainbox** [VivaPayments/API#301]
Μετά από διάφορους ελέγχους βρήκαμε ότι υπάρχουν συναλλαγές που ενώ έχουν αρχίσει μέσω web **ολοκληρώνονται μέσω τηλεφωνικής πληρωμής προς τη viva** ή με κάποιο άλλο τρόπο που δεν γνωρίζουμε, οπότε δεν υπάρχει redirect στo success page.

Παρακάτω σας στέλνω 5 ordercodes που βρήκαμε ότι δεν έχουν έρθει στο success page ενώ ήταν επιτυχημένες.

```
7486983277972600
4029955171972607
9620110557672601
9944981267272601
2526194316072604
```

Πως μπορούμε να δούμε αρχικά με ποιο τρόπο έγιναν αυτές οι συναλλαγές; (τηλέφωνο ή κατι άλλο)
Ή αν δεν μπορούμε μπορείτε να μας ενημερώσετε για τις συγκεκριμένες χρεώσεις.

Επίσης υπάρχει κάποιος τρόπος να απενεργοποιήσουμε τις άλλες διαδικασίες πληρωμών και να κρατήσουμε μόνο την διαδικασία μέσω web (που κάνει redirect στο success page) ;

Ευχαριστώ

**Comment by dmihos** [comment]
Τα OrderCodes 1,2,3,5 εξοφλήθηκαν μέσω IVR ή μετρητών.
Το 4ο έγινε με κάρτα στη redirect.

Στη σελίδα με τα [Optional parameters](https://github.com/VivaPayments/API/wiki/Optional-Parameters), αναφέρονται αναλυτικά τα flags που μπορείτε να ορίσετε κατά το Createorder και θα σας επιτρέψουν να κρύψετε στην checkout σελίδα τους τρόπους πληρωμής που δε θέλετε.
πχ DisableIVR, DisableCash κλπ

**Comment by kostas-brainbox** [comment]
Ευχαριστώ πολύ για την γρήγορη απάντηση και για τις πληροφορίες

**Comment by kostas-brainbox** [comment]
Καλησπέρα και πάλι,
χρησιμοποιήσαμε τα flags DisableIVR κλπ και όντως δεν εμφανίζονται στους τρόπους πληρωμής αλλά απ ότι καταλαβαίνω αυτό δεν απενεργοποιεί εντελώς τη δυνατότητα του χρήστη να πληρώσει με αυτούς τους τρόπους.
Υπάρχει κάποια ρύθμιση που μπορούμε να κάνουμε είτε προγραμματιστικά, είτε στο account για να απενεργοποιήσουμε εντελώς αυτές τις διαδικασίες αλλά όχι την πληρωμή POS;

Ευχαριστώ

**Comment by dmihos** [comment]
Όχι δεν υπάρχει τρόπος. 
Η εμπειρία έχει δείξει, όμως, ότι αν ο πελάτης δε δει λεπτομέρειες/κωδικούς κλπ, δε θα επιχειρήσει άλλο τρόπο πληρωμής.

**Comment by avardikos** [comment]
Καλησπέρα και απο εμένα,
Σήμερα ενεργοποιηθηκε η πηγη πληρωμων και σε εμενα και εχω πρόβλημα με το redirect. Στην ουσια την πρωτη φορα εγίνε η πληρωμη κανονικα αλλα μετα δεν γινεται redirt απο το site σας πισω ωστε να γινει success η πληρωμη και καταγραφει σαν παραγελλια στο eshop. 
Μετά έκανα και μια εσφαλμενη πληρωμη με λαθος κωδικο στην καρτα αλλα παραμενει στο site του vivawallet και αναφερει οτι εκει οτι δεν μπορει να προχωρησει χωρις να γυριζει πισω στο eshop
Αλλαξα τα links του url στις πηγες μηπως υπηρχε καποιο λαθος αλλα δεν καταφερα κατι. 
Εαν αλλαξω το url επιτυχημενης ή αποτυχιμενης πληρωμης στις πηγες ενημερωνεται άμεσα?

**Comment by dmihos** [comment]
Αν έχετε πάνω από μια πηγή, βεβαιωθείτε ότι, κατά το CreateOrder, περνάτε το σωστό SourceCode, ώστε να χρησιμοποιηθούν τα σωστά urls μετά το redirect.
Οι αλλαγές των urls στις πηγές είναι άμεσες, εφόσον δε μεταβληθεί το domain τους.
