### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by avelstorm** [VivaPayments/API#302]
Καλησπέρα.

Αντιμετωπίζουμε ένα πρόβλημα στην ιστοσελίδα μας www.mytenta.gr που έχουμε ενσωματώσει την πληρωμή μέσω πιστωτικής κάρτας με vivapayment.

Όταν πάμε να ολοκληρώσουμε μια πληρωμή μέσω πιστωτικής κάρτας, μας πηγαίνει στη σελίδα που έχουμε δηλώσει (http://www.mytenta.gr/app/payments/vivapayments_submit.php ) μας εμφανίζει το μήνυμα “Access Denied” και δεν ολοκληρώνεται η πληρωμή.

Κωδικός 
_vivaordercodeid
4299688002772600

Παρακαλώ όπως μας απαντήσετε άμεσα για το παραπάνω πρόβλημα καθώς δεν μπορούν οι πελάτες μας να ολοκληρώσουν παραγγελίες από την ιστοσελίδα μας.

**Comment by dmihos** [comment]
Καλημέρα σας

Το μήνυμα 'Access denied' εμφανίζεται στο site σας, συνεπώς θα πρέπει να το δει ο τεχνικός σας.

Από την πλευρά του Viva λογαριασμού σας δεν υπάρχει κάποιο πρόβλημα.
Σε δοκιμή που κάναμε, εμφανίστηκε η σελίδα πληρωμής, βάλαμε μια λάθος κάρτα και έγινε redirect στη σελίδα app/payments/vivapayments_failure.php του site σας, η οποία, πράγματι, εμφάνισε μήνυμα 'Access denied'.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
