### ISSUE TITLE
E-commerce ενσωματωση plugin σε woocommerce

### ISSUE THREAD

**Issue by KoukoumisChristos** [VivaPayments/API#307]
Καλησπέρα,

Κατά τη διαδικασία εγκατάστασης του plug-in και στη δημιουργία της πηγής πληρωμής αντιμετωπίστηκε το εξής πρόβλημα:

όταν εισάγουμε τις διευθύνσεις της ιστοσελίδας "www.athenslimotour.com/en/" και
"www.athenslimotour.com/gr/"

τα πεδία URL Επιτυχημένης συναλλαγής και URL Αποτυχημένης συναλλαγής
 γίνονται αυτόματα "www.athenslimotour.comgr/" και  "www.athenslimotour.com/en/" .

Η ιστοσελίδα είναι πολύγλωσση και έχει ηλεκτρονικό κατάστημα σε 3 γλώσσες.

Υπάρχει τρόπος να φτιαχτεί η πηγή πληρωμής με το σωστό τρόπο για όλες τις γλώσσες τις ιστοσελίδας;

παρακαλώ ενημερώστε με άμεσα ακόμα και σε περίπτωση που δεν υπάρχει κάποια λύση

ευχαριστώ.

**Comment by VivaWalletSupport** [comment]
What plugin are you using and how did you configure the URLs in the payment source?

**Comment by KoukoumisChristos** [comment]
I am using Vivapayments woocomerce payment gateway. I did not configure the urls because i have a problem when i enter my url in the viva panel on my viva account to create vivapayments code id, it does not recognize the"/" symbol

**Comment by VivaWalletSupport** [comment]
The domain name should be www.athenslimotour.com and the return URLs for success / fail 
index.php?wc-api=wc_hellaspay&hellaspay=success
index.php?wc-api=wc_hellaspay&hellaspay=fail

After that Woocommerce should redirect the customer back to correct order complete page with the correct language.

**Comment by KoukoumisChristos** [comment]
Yes i understand taht but the website is athenslimotour.com/en for the english one
And athenslimotour.com/gr for the greek one.
They both have woocommerce and i need payments to be able to be completed on both languages.

**Comment by VivaWalletSupport** [comment]
With the source setup I provided you before, you should be able to do so.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
