### ISSUE TITLE
How can i import thi API to android studio?

### ISSUE THREAD

**Issue by zisk11** [VivaPayments/API#31]
I have a project about a shop and i want the payment go through viva payments but in this API folder i didn't find something for android. Is it possible to use it as it is ?

**Comment by dpnevmatikos** [comment]
Hi there @zisk11 ,
Unfortunately there is no development kit for android for the time being,
so your only option is to use the Viva Payments API as described [in this wiki](https://github.com/VivaPayments/API/wiki).
