### ISSUE TITLE
"Pre-Authorization" and "Capture" time periods

### ISSUE THREAD

**Issue by melcon77** [VivaPayments/API#310]
Σύμφωνα με τις οδηγίες που υπάρχουν στο παρακάτω link μπορώ σε μία κάρτα να κάνω Authorization (ή Pre-Authorization) που στην περίπτωση της πιστωτικής κάρτας μπορεί να κρατήσει (πριν λήξει) μέχρι 30 μέρες (ανάλογα την τράπεζα έκδοσης). Όμως επίσης λέει ότι capture δηλαδή την χρέωση μπορώ να την κάνω μόνο μέσα στην ίδια μέρα. Ποια είναι η λογική εδώ ενώ έχω authorized ένα ποσό στην κάρτα που μπορεί να κρατηθεί αρκετές μέρες, εγώ να μπορώ να το πάρω μόνο μέσα στην ίδια μέρα της συναλλαγής και όχι π.χ. μετά από 2-3 μέρες που χρειάζομαι εγώ?

https://support.vivawallet.com/hc/en-us/articles/201018201-Transaction-Types

**Comment by dmihos** [comment]
Καλημέρα σας
Σωστά, αυτή είναι η δυνατότητα που προσφέρεται για τα preauthorizations. Το capture πρέπει να γίνει εντός της ίδιας μέρας. 

Μπορείτε να χρησιμοποιήσετε τα [Recurring Payments](https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction) που προσφέρουν ένα παραπλήσιο functionality.

**Comment by melcon77** [comment]
Καλημέρα και ευχαριστούμε για την άμεση απάντηση,
Δεν μας διευκρινίζετε όμως γιατί ενώ τα τραπεζικά ιδρύματα έκδοσης των καρτών δίνουν δυνατότητα για capture μέχρι και max 30ημερων (για πιστωτικές κάρτες) εσείς δίνετε capture μόνο εντός της ημέρας της συναλλαγής. Είναι αυτή η πολιτική της εταιρείας σας? υπάρχει κάποιο τεχνικό ή άλλο θέμα?
Ο λόγος που σας ρωτάμε είναι γιατί η επιχειρηματική μας ανάγκη (χρησιμοποιούμε Native Checkout) είναι να μπορούμε  να κάνουμε capture 2 μέρες μετά το Pre-Authorization και αυτό είναι τόσο critical για το επιχειρηματικό μας μοντέλο που αν όντως δεν γίνεται θα πρέπει να εξετάσουμε σοβαρά την επιλογή κάποιας άλλης εταιρείας πληρωμών (εξωτερικού) που παρέχει αυτή την δυνατότητα.
ΥΓ Όσον αφορά το Recurring Payments, σύμφωνα με το παρακάτω link θα πρέπει ο πελάτης να έχει ξαναχρεωθεί στο παρελθόν (σε εμάς όλοι οι πελάτες είναι νέοι). Αν ο πελάτης είναι νέος μπορούμε να κάνουμε Recurring.
https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction

Ευχαριστούμε εκ των προτέρων

**Comment by dmihos** [comment]
Λυπάμαι αν δε σας καλύπτει το functionality του PreAuthorization. 
Είναι πολιτική της εταιρίας και, δυστυχώς, δε μπορεί να αλλάξει.

Σχετικά με τα recurring transactions, χρεώνετε την 1η φορά το χρήστη ένα μικρό ποσό (πχ 1€), και του το επιστρέφετε άμεσα.
Εφόσον θέλετε, στη συνέχεια, 2 μέρες μετά, να χρεώσετε για την υπηρεσία, εκτελείτε Recurring Transaction στην αρχική χρέωση του 1€.

**Comment by melcon77** [comment]
Tα recurring transactions κάνουν προδεσμευση ποσού? ή απλά σου δίνουν το δικαίωμα να χρεώσεις σε περίπτωση που βρεις διαθέσιμο όριο στην κάρτα?

**Comment by dmihos** [comment]
Όχι δεν κάνουν κάποια προδέσμευση

**Comment by melcon77** [comment]
Καλημέρα,
Γενικά η ανάγκη της επιχείρησης μας (χρησιμοποιούμε Native Checkout) είναι για προ-δέσμευση του συνολικού ποσού και capture μετά από 2-3 μέρες, εφόσον όμως αυτό δεν γίνεται με τις παραμέτρους pre-authorization και capture θα θέλαμε μια διευκρίνιση σχετικά με την παράμετρο recurring payments:

Είπαμε ότι για να ενεργοποιήσουμε την recurring payments, εκτός της συναίνεσης του πελάτη με το checkbox, χρειάζεται και μια αρχική χρέωση, που μπορούμε να κάνουμε προχωρώντας σε χρέωση € 1 και μετά άμεση ακύρωση αυτής της χρέωσης.

**Η ερώτηση είναι εδώ αν μπορούμε αντί του παραπάνω τρόπου να ενεργοποιήσουμε την recurring payments με εντολή pre-authorization του ποσού που θέλουμε π.χ. € 500, και μετά να μην κάνουμε καθόλου capture μέσα στην ημέρα ώστε να λήξει, και στην συνέχεια να χρεώσουμε τα € 500 με recurring 2-3 μέρες μετά. Με αυτόν τον τρόπο τουλάχιστον ελέγχουμε αν κατά την στιγμή της αγοράς της υπηρεσίας υπήρχε διαθέσιμο το ποσό.**

Στο παράδειγμα create order που υπάρχει στο παρακάτω link φαίνεται οτι γίνεται ταυτόχρονα και η recurring και η pre-authorization είναι true.
https://github.com/VivaPayments/API/wiki/CreateOrder

Ευχαριστώ εκ των προτέρων

**Comment by melcon77** [comment]
Ευγενική υπενθύμιση - Μπορούμε τελικα να κάνουμε ενεργοποιήση του recurring με εντολη που θα έχει το authorization=true?

**Comment by dmihos** [comment]
Όχι, το recurring transaction γίνεται πάνω σε μια επιτυχημένη χρέωση (και όχι preauthorization)

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
