### ISSUE TITLE
Χρέωση κάρτας από συναλλαγή που έχει ακυρωθεί

### ISSUE THREAD

**Issue by melcon77** [VivaPayments/API#313]
Κάναμε μια δοκιμαστική χρέωση (σε περιβάλλον live) με κωδικό συναλλαγής 
39fa7893-212a-4960-9555-d6d4da2c2b8c
Πόσο 366€ στις 22/5/2017 11:54:19 μμ

Και μετά από 3 λεπτά την ακύρωσαμε (22/5/2017 11:57:33 μμ) 

**Παρόλα αυτά στην κάρτα χρεώθηκε το ποσό των 366€ κανονικά στις 24/5/2017 22:37 με αιτιολογία "VIVA PAYMENTS".**
Τι ακριβώς συνέβη?

**Comment by dmihos** [comment]
Καλημέρα
Κάποιες ακυρώσεις δεν ολοκληρώνονται σε πραγματικό χρόνο από τις εκδότριες τράπεζες, και ακολουθείται μια διαφορετική διαδικασία.
Αυτό συνέβη και στην προκειμένη περίπτωση. Η ακύρωση θα ολοκληρωθεί σε λίγες εργάσιμες.

Πάντως, ακόμη κι αν η ακύρωση γίνει online, και πάλι ενδέχεται να εμφανίζεται στις κινήσεις της κάρτας η χρέωση και η πίστωση.
