### ISSUE TITLE
Λίστα με λεκτικά για **Errortext**

### ISSUE THREAD

**Issue by melcon77** [VivaPayments/API#314]
Υπάρχει κάποια ενδεικτική λίστα με τα **ErrorCode** και τα **Errortext** λεκτικά που αντιστοιχούν σε αυτά?

**Comment by dwb17** [comment]
It would be very helpful if such a list was provided by you.

**Comment by kostGX** [comment]
Closing as issue age > 1 year. Please re-open with an update comment if you still need help with this.
