### ISSUE TITLE
Αποθηκευση καρτας

### ISSUE THREAD

**Issue by deliverymanager** [VivaPayments/API#315]
Υπαρχει η δυνατοτητα αποθηκευσης των στοιχειων της καρτας ενος χρηστη στο server σας και στη συνεχεια να γινει κληση της καρτας με ενα token ωστε να γινει νεα χρεωση αλλα για αλλο ποσο;
Φυσικα δε μιλαω για αποθηκευση και το CVC που απαγορευει η Mastercard και η Visa;
Παρομοια λυση προσφερουν αλλες υπηρεσιες πληρωμων οπως Braintree και Stripe;

**Comment by deliverymanager** [comment]
Οποτε ζηταω την αδεια του χρηστη για recurring payments και αποθηκευω εγω μονο το transaction id της αρχικης μικρης χρεωσης με την οποια πηρα την αδεια δημιουργιας recurring payments απο το χρηστη.
Υπαρχει καποιος περιορισμος σχετικα με το ποσό των επομενων recurring payments και με το πληθος των συναλλαγων που μπορουν να γινουν?
Ληγει καποια στιγμη το αρχικο transaction id?
Τελος, υπαρχει προβλημα στο να αποθηκευσω εστω τα τελευταια 4 ψηφια της καρτας ωστε να ξερει ο χρηστης ποια καρτα εχω θεωρητικα και εμμεσως αποθηκευσει;
Ευχαριστω!

**Comment by dmihos** [comment]
Δεν υπάρχει περιορισμός στον αριθμό ή το ποσό των συναλλαγών.
Μπορείτε να χρησιμοποιείτε το transactionId για recurring, όσο η κάρτα του πελάτη είναι ενεργή.
Μπορείτε να αποθηκεύσετε τα 4 ψηφία της κάρτας.

**Comment by deliverymanager** [comment]
Προσπαθώ να δημιουργήσω μία ένα transaction id το οποίο θα έχει ενεργοποιημένο το AllowRecurring και όταν πάω να το κάνω GET να μου επιστρέφει RecurringSupport true.
Ο τρόπος με τον οποίο το προσπαθώ είναι με το Mobile API.
ενώ λοιπόν στέλνω στο API με POST https://www.vivapayments.com/api/orders 
AllowRecurring: true, αυτό το αγνοεί.
Υπάρχει κάποιος ειδικός τρόπος με τον οποίο πρέπει να δημιουργήσω το orderCode?
Εχω βάλει ένα κουμπάκι το οποίο πατάει ο χρήστης για να αποδεχτεί τις επαναλαμβανόμενες πληρωμές, ωστόσο αυτό δε συνδέεται με κάποιον ιδιαίτερο τρόπο με την κλήση του API.
Τι ακριβώς κάνω λάθος;

**Comment by deliverymanager** [comment]
https://github.com/VivaPayments/API/issues/138
