### ISSUE TITLE
Viva payments

### ISSUE THREAD

**Issue by vsouv** [VivaPayments/API#319]
Καλησπέρα,
Υπάρχει η δυνατότητα διασύνδεσης του API με ένα website κανονικό και όχι eshop. Αυτό που θέλω είναι να δώσω την δυνατότητα σε συγκεκριμένους πελάτες να μπορούν  να  πληρώνουν μέσω του website με redirection στην Viva ένα ποσό το οποίο θα το γράφουν και θα επιλέγουν δόσεις. 
Wordpress είναι το site.

Ευχαριστώ

**Comment by dmihos** [comment]
Καλησπέρα

Δεν υπάρχει κάποια έτοιμη λύση γι'αυτό που ζητάτε, θα πρέπει να κάνετε integration για [Redirect Checkout](https://github.com/VivaPayments/API/wiki/Redirect-Checkout).

Ωστόσο, υπάρχει η δυνατότητα να φτιαχτεί ένας κωδικός (ένα url για την checkout δλδ), το οποίο δε θα λήξει ποτέ, και στο οποίο θα μπορεί ο καθένας (όποιος έχει το link δλδ) να βάζει ότι ποσό θέλει με την κάρτα του. Αν σας καλύπτει αυτή η λύση, μπορεί να φτιαχτεί ένας τέτοιος κωδικός, μέσω του API.
[Οι παράμετροι της CreateOrder](https://github.com/VivaPayments/API/wiki/Optional-Parameters), γι'αυτή την περίπτωση είναι
PaymentTimeout:65535
DisableExactAmount:true
RequestAmount:1000 (ενδεικτικό αρχικό ποσό 10€, το αλλάζει ο χρήστης).

(Αν δεν έχετε την τεχνική δυνατότητα να φτιάξετε μέσω του API έναν τέτοιο κωδικό, στείλτε ένα email στο merchants@vivawwallet.com, με αναφορά στο παρόν issue, να σας φτιάξουμε εμείς)

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
