### ISSUE TITLE
Εάν δεν υπάρχει OpenSSL στον server

### ISSUE THREAD

**Issue by botonakis** [VivaPayments/API#32]
Επειδή ο κώδικας και τα παραδείγματα που αναφέρετε δεν είναι για όλα τα configurations παρακαλώ να προστεθεί ότι εάν ο server δεν έχει OpenSSL (όλοι οι servers της TopHost καθώς και άλλων εταιριών στον Ελληνικό χώρο) και έχει NSS,

η γραμμή: 
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST,'TLSv1');

πρέπει να αντικατασταθεί με το:
define('CURL_SSLVERSION_TLSv1', 1);
curl_setopt( $session, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);

Σας ευχαριστώ.

**Comment by dpnevmatikos** [comment]
Καλησπέρα,
Ευχαριστούμε για την επισήμανση.
Ανανεώσαμε το [σχετικό άρθρο μας στο Help Center](https://support.vivawallet.com/hc/communities/public/questions/200568401-Site-not-responding-when-called-from-PHP-code).
