### ISSUE TITLE
404 σε redirect viva payments απο cs-cart (part 2)

### ISSUE THREAD

**Issue by harvesterr** [VivaPayments/API#323]
καλησπερα
εχω ενα θεμα
εγκατεστησα ενα plugin για το viva payments se cs cart
αλλα οταν τελειωνει την παραγγελία ο πελάτης με πεταει σε 404!
κ η χρεωση στον πελατη γινεται κανονικα
κ επίσης η παραγγελία στο πανελ παει στις ατελης παραγγελίες που ειναι κρυφες κ δε φαινονται!

γιατι γινεται αυτο?
επισης επειδη εκανα νεα εγκατασταση σε ssl μπηκα μεσα στο πανελ της viva payments K αλλαξα το λινκ απο http σε https

εκανα τελος, εγκατασταση απο τα plugins που εχετε εδω για το cs cart (cs cart 4) κ παλι τα ιδια
συνεχως με πεταει σε 404

κ επισης επειδη χρησιμοποιω ssl εκανα κ μια αλλαγη στο vivawallet.tpl απο http σε https.
αλλα κ παλι τπτ

**Comment by dmihos** [comment]
Duplicate
https://github.com/VivaPayments/API/issues/238

**Comment by harvesterr** [comment]
οκ
μπορουμε να κανουμε κατι??
