### ISSUE TITLE
"This card does not support electronic transactions" in demo

### ISSUE THREAD

**Issue by VonShtirlitz** [VivaPayments/API#326]
Hello

We try to integrate Redirect API. Created a demo account with Merchant ID 17891032-5d87-404f-9562-9650ce91431d. Tried to use a demo card 4111 1111 1111 1111 in demo env.

We got an error:
"This card does not support electronic transactions. In order to complete this payment please use a different card, or add funds to your Viva Wallet."

Help please solve this problem.

**Comment by dmihos** [comment]
Hello, please try again now.
Regards

**Comment by VonShtirlitz** [comment]
It works. Thank you.
