### ISSUE TITLE
API support for Ruby on Rails...

### ISSUE THREAD

**Issue by stefkas** [VivaPayments/API#327]
ήθελα να σας ρωτήσω αν υποστηρίζετε ή σκοπεύετε να υποστηρίξετε κάποια βιβλιοθήκη για Ruby on Rails κώδικα.

Η πιο γνωστή και ευρέως διαδεδομένη βιβλιοθήκη που χρησιμοποιείται από πολλούς payment gateways είναι η Active Merchant (από την Stripe)
https://github.com/activemerchant/active_merchant

Ευχαριστώ!

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
