### ISSUE TITLE
redirection to cart

### ISSUE THREAD

**Issue by divramis1** [VivaPayments/API#329]
redirection to cart

Καλημέρα, δεν κάνει redirection στην σελίδα επιτυχημένη συνναλαγή αλλά στο καλάθι αγορών. Ξέρετε τι μπορούμε να κάνουμε;

**Comment by dmihos** [comment]
Καλησπέρα σας

Έχετε κάνει integration με το Api; Χρησιμοποιήτε κάποιο plugin (και ποιο);
Έχετε φτιάξει σωστά τα urls στην πηγή που χρησιμοποιείτε;

Μετά την πληρωμή, το σύστημα δε γνωρίζει για σελίδες και καλάθια αγορών. Γνωρίζει μόνο το url (επιτυχίας/αποτυχίας αντίστοιχα) που έχει οριστεί στη σχετική πηγή και σε αυτό κάνει redirect το χρήστη.

**Comment by chiosdj** [comment]
Το ίδιο αντιμετωπίζω και εγώ αλλά σε όλες τις συναλλαγές  πχ σε αποτυχία δεν κάνει redirect αλλά λεύκη σελίδα

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
