### ISSUE TITLE
Αποτυχία Εκτέλεσης Συναλλαγών

### ISSUE THREAD

**Issue by kesidaki** [VivaPayments/API#332]
Γεια σας,
μετά από τη προσθήκη νέας πηγής πληρωμών (www.citydoctors.gr) δεν μπορώ να εκτελέσω καμία συναλλαγή μέσω πιστωτικής κάρτας με χρήση της Viva Wallet.

Το σφάλμα που μου επιστρέφει είναι κατά την εκτέλεση του ExecuteCall από τη NativeCheckoutClass.php.
Πιο συγκεκριμένα, το response της εν λόγω συνάρτησης είναι bool(false). Αυτό άρχισε να συμβαίνει από όταν έγινε προσθήκη νέας πηγής πληρωμών στο λογαριασμό μας, και επηρεάζει και την άλλη σελίδα όπου γινόντουσαν κανονικά συναλλαγές.

Έχω ελέγξει τις υπόλοιπες εισόδους και εξόδους των συναρτήσεων, όλα δίνουν σωστές τιμές. Μόνο εκεί φαίνεται να υπάρχει πρόβλημα

**Comment by kesidaki** [comment]
Μετά από διάφορες δοκιμές βρήκα ότι το να αφαιρέσω τη γραμμή

curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

έκανε τη δουλειά. Αλλά γιατί έγινε αυτό στα ξαφνικά;

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
