### ISSUE TITLE
"This card does not support electronic transactions" in demo

### ISSUE THREAD

**Issue by pashtete** [VivaPayments/API#333]
Hello

We try to integrate Redirect API. Created a demo account with Merchant ID 493daefb-d388-4910-9e6b-8fbe341d44d9. Tried to use a demo card 4111 1111 1111 1111 in demo env.

We got an error:
"This card does not support electronic transactions. In order to complete this payment please use a different card, or add funds to your Viva Wallet."

Help please solve this problem.

Support on the phone can't help us with this...
Thank you.

**Comment by dmihos** [comment]
Hello, please try again, account is configured properly now.
