### ISSUE TITLE
Virtuemart 3 δεν αποθηκευει την μέθοδο

### ISSUE THREAD

**Issue by LinoZipper** [VivaPayments/API#334]
Καλησπέρα προσπαθώ να δημιουργήσω μέθοδο πληρωμής με το virtuemart3 αλλα παρόλο που μου γράφει πως η μέθοδο έχει αποθηκευτει, στην πραγματικότητα ουτε έχει αποθηκευτεί αλλά ούτε και έχει δημοσιευτεί.

**Comment by VivaWalletSupport** [comment]
Hello, on line 8 from the vivawallet.php file change the line:
class plgVmPaymentVivapay extends vmPSPlugin {

To:
class plgVmPaymentVivawallet extends vmPSPlugin {

The correction is pending in the repository.
