### ISSUE TITLE
new plugin j2store

### ISSUE THREAD

**Issue by LinoZipper** [VivaPayments/API#335]
Καλησπέρα σας,
Μετά από αρκετό καιρό είδα πως έχετε δημιουργήσει αρκετά plugin.
Παρόλο που έχετε δημιουργήσει plugin για το k2store είδα πως δεν έχετε δημιουργήσει το αντίστοιχο για το j2store
Υπάρχει το ενδεχόμενο να το δημιουργήσετε και αυτό;

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.

**Comment by vasite** [comment]
Καλησπέρα σας
Βλέπω πως υπήρχε ήδη η ζήτηση από το 2017 αλλά την επαναφέρω επειδή δεν έχει επιλυθεί. 
Το k2store έχει καταργηθεί ήδη εδώ και χρόνια και αντικαταστάθηκε από το J2Store.
Θα ήταν καλό να ενημερώσετε το Plugin σας k2store ώστε να λειτουργεί στο τελευταίο Joomla και στο J2Store.
