### ISSUE TITLE
Πρόβλημα με redirect 

### ISSUE THREAD

**Issue by Enter-GWD** [VivaPayments/API#337]
Η πληρωμή γίνετε κανονικά στη σελίδα της Viva, όταν όμως ολοκληρωθεί η πληρωμή, δε γίνετε η ανακατεύθυνση πίσω στη σελίδα του καταστήματος. Τα Link που δίνει το πρόσθετο τα έχω βάλει στην αντίστοιχη πηγή. Έχει ταυτοποιηθεί ο αντίστοιχος λογαριασμός στη Viva.

Plugin.: https://el.wordpress.org/plugins/woo-payment-gateway-for-vivapayments/
WordPress 4.8 + Woocommerce 3.0.8
https://stickerbox.gr

**Comment by chiosdj** [comment]
Το ίδιο αντιμετωπίζω και εγώ αλλά σε όλες τις συναλλαγές πχ σε αποτυχία δεν κάνει redirect αλλά λεύκη σελίδα  σε whmcs

**Comment by yannisg** [comment]
Και εμείς το ίδιο πρόβλημα.

Έχουμε δοκιμάσει τα παρακάτω urls που αναφέρονται στο documentation:
 
SUCCESS URL: index.php?wc-api=wc_vivawallet&vivawallet=success
FAIL URL: index.php?wc-api=wc_vivawallet&vivawallet=fail

Περνάει η πληρωμή κανονικά, χρεώνεται η κάρτα και μετά βγάζει κενή σελίδα με '-1'

URL μετά την πληρωμή: https://domain.com/index.php?wc-api=wc_vivawallet&vivawallet=success&t=xxxxxx-xxxxxx-
xxxxxx-xxxxxx-xxxxxx-xxxxxx&s=xxxxxx&lang=el-GR

**Comment by dmihos** [comment]
@Enter-GWD 
Χρησιμοποιτείτε κάποιο 3rd party plugin.

Το μόνο που μπορώ να δω για να σας βοηθήσω, είναι ότι οι συναλλαγές σας γίνονται στην πηγή default, ενώ έχετε ορίσει τα urls σε άλλη πηγή.
Θα πρέπει να βάλετε τον κωδικό της σωστής πηγής, σε κάποιο σημείο του configuration του plugin.
Απευθυνθείτε στην εταιρία που το υποστηρίζει, για λεπτομέρειες.

**Comment by Enter-GWD** [comment]
@yannisg 
@chiosdj

Καλησπέρα.
Τελικά με ελάχιστη βοήθεια κατάφερα και έβγαλα άκρη.
Παρακάτω εξηγώ πως δούλεψε σε εμένα.

vivawallet -> οι πωλήσεις μου -> οι πήγες μου -> εκεί θα παρατηρήσετε ότι υπάρχει η πηγή default. Ταυτόχρονα υπάρχει ένα κουμπί το οποίο λέει "Νέα ιστοσελίδα/εφαρμογή" το οποίο λογικό είναι κάποιος να πάει και να σετάρει από εκεί την πηγή του. Έτσι δημιούργησα άλλη μια πηγή (stickerbox).
Στη δική μου περίπτωση έπρεπε να επεξεργαστώ το default και όχι να δημιουργήσω νέα πηγή.

Για μια τέτοια λεπτομέρεια έφαγα 6 με 8 μέρες.
Καλό θα ήταν να δίνατε πιο κατατοπιστικές οδηγίες.

**Comment by smargj** [comment]
Ακριβώς το ίδιο έπαθα και γω. Ταλαιπωρία 10 ημερών περίπου για κάτι τόσο απλό! Τι τηλέφωνα είχα πάρει, τα πάντα έκανα και νόμιζα ότι κάπου έκανα εγώ λάθος! Ήμαρτον ρε παιδιά! Μια σωστή οδηγία χάθηκε να υπάρχει?

**Comment by chiosdj** [comment]
Αυτό το κάνει κι αν η χρέωση είναι κάτω από 0,60 € δοκιμάστε με μεγαλύτερη χρέωση.

**Comment by Enter-GWD** [comment]
@yannisg @chiosdj @smargj @gliaskos 

Καλησπέρα.  Πρέπει να ορίσετε στο plugin το ID της πηγής. 
Στο VivaPayments CodeId βάζεις  τον κωδικό από την πηγή που δημιουργεις και. 
Το ID ειναι ο κωδικός της πηγής.
Spoiler alert - **Μην Σβήσεις η μην χρησιμοποιήσεις την default πηγή.**

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
