### ISSUE TITLE
Basic auth with & in APIkey

### ISSUE THREAD

**Issue by bekatoros** [VivaPayments/API#34]
Hi,
it seems to be a problem when a & is present in the APIKey.
Basic authorization fails for the php code.
Is there a fix?
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);

**Comment by dpnevmatikos** [comment]
Hi there @bekatoros ,
Are you getting an error code?
Please also refer to [this article](https://support.vivawallet.com/hc/communities/public/questions/200568401-Site-not-responding-when-called-from-PHP-code) for more info.

Let us know if that works out for you.

**Comment by bekatoros** [comment]
The authorization error I receive.
HTTP/1.1 401 Invalid password for the merchant with id 45193634-###-###-###-cf6b72e925fb Cache-Control: no-cache Pragma: no-cache Expires: -1 Server: Microsoft-IIS/7.5 Date: Tue, 01 Dec 2015 15:55:36 GMT Content-Length: 0

**Comment by dpnevmatikos** [comment]
You may need to encode your API key first.
I am not a PHP developer, but a quick Google search revealed this [StackOverflow thread](http://stackoverflow.com/questions/10060093/special-characters-like-and-in-curl-post-data) which might be what you need.

**Comment by bekatoros** [comment]
Fixed by using
curl_setopt($session, CURLOPT_USERPWD, rawurldecode($MerchantId).':'.rawurldecode($APIKey));
