### ISSUE TITLE
Αλλαγη από Native/Πληρωμη με Viva σε Redirect

### ISSUE THREAD

**Issue by katsanosmarket** [VivaPayments/API#340]
Καλησπερα σας.
Εχω εναν επαγγελματικό λογαριασμο που ειχε δημιουργηθεί πριν εγκαταστησω το plugin της viva στο Opencart. Μαζί με το plugin ηρθε κι ενα text που μου λεει οτι η πληρωμη πρεπει να ειναι σε redirect, (You can create a new Payment Source from the menu My Sales - Payment Sources - New Website/App.
Code - use this code in your plugin
Source Name - provide a logic name here
Linked Wallet - link the payment source to the wallet you want to use with it
Protocol - in case your e-commerce platform uses SSL on the checkout select https, otherwise use https
Integration method - redirection
Company Logo - your png company logo to display on the Vivawallet payment page
Success URL - as described in the plugin instructions
Failure URL - as described in the plugin instructions
Advanced Configuration - usually no need to make any changes here)
Εκανα αιτημα αλλαγης στη Viva wallet. Χρειαζεται να κκανω κατι αλλο για την αλλαγη;
Ευχαριστω πολυ.

**Comment by katsanosmarket** [comment]
Υ.Γ.  Το προβλημα που αντιμετωπισα ειναι οτι ενω γινοταν η πληρωμη απο την πιστωτικη καρτα του πελατη, τα χρηματα μεταφερονταν στο λογαριασμο μου της Viva, αλλα δεν ειχε εμφανιστει η παραγγελια του στο backoffice του e-shop.

**Comment by VivaWalletSupport** [comment]
Put the payment source code in the extensions settings (Source Code).

**Comment by katsanosmarket** [comment]
Καλημερα σας.
Εχω κανει αιτημα για αλλαγη του Integration Method απο Native/Πληρωμη με Viva Wallet Checkout σε Redirection.
![viva 04](https://user-images.githubusercontent.com/29598495/27677684-3aa4be7a-5cbb-11e7-8caa-fc5a7704bc33.JPG)
Ο λογαριασμος μου βρισκεται σε εκκρεμοτητα.
![viva 01](https://user-images.githubusercontent.com/29598495/27677772-73f5c656-5cbb-11e7-9994-ad22ea1cf481.JPG).
Επισης οταν επιλεγω τροπο πληρωμης με καρτα και κανω ολοκληρωση αγορας, μου βγαζει αυτο το μυνημα
![viva 03](https://user-images.githubusercontent.com/29598495/27677837-ac6d3e6a-5cbb-11e7-8ff0-ff312e23f97f.JPG)
Οι ρυθμισεις που εχω κανει ειναι αυτες που μου υποδειξατε.
![viva 02](https://user-images.githubusercontent.com/29598495/27677893-eeb2e680-5cbb-11e7-9d2d-5e8818271fca.JPG)
Μιλησα με την υποστηριξη της Viva Wallet και μου ειπαν να απευθυνθω σε εσας. 
Παρακαλω καθοδηγηστε με βημα βημα για την εγκατασταση.
Ευχαριστω.

**Comment by VivaWalletSupport** [comment]
Check if you are using the correct merchant id and api key in your extension settings (no trailing spaces), if so check your opencart/php error logs to see what causes the internal 500 error.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.

**Comment by foteinitsouknida** [comment]
![Screenshot_2019-03-16-17-05-52](https://user-images.githubusercontent.com/46266350/54495971-637e0700-48f2-11e9-9c8d-e9092b896707.png)


why is this massage ? i use opencart
