### ISSUE TITLE
Πρόβλημα με πληρωμή

### ISSUE THREAD

**Issue by LetsFerry** [VivaPayments/API#343]
Καλησπέρα σας,
Αντιμετωπίζουμε ένα θέμα με μία συναλλαγή η οποία δεν εμφανίζεται στο διαχειριστικό περιβάλλον της viva αλλά ο πελάτης έχει χρεωθεί.
Στο δικό μας διαχειριστικό εμφανίζεται σαν failed, όταν μία συναλλαγή γίνεται failed υπάρχουν 2 ενδεχόμενα α. δεν πέρασε η πληρωμή β. κάποιο θέμα με τα εισιτήρια. Στη συγκεκριμένη περίπτωση "χτυπάει" η πληρωμή. 
Έχουμε δει/αντιμετωπίσει διάφορα error codes, με πιο κοινό το 502, σε αυτή την περίπτωση όμως λαμβάνουμε error 0 χωρίς κάποια επεξήγηση. 
Ο πελάτης έχει χρεωθεί, και στο viva όπως με έχετε ενημερώσει και τηλεφωνικά δεν εμφανίζεται κάποια χρέωση από το merchants με ενημέρωσαν να ανοίξω νέο Issue και να σας προωθήσω το παρακάτω αρχείο που είναι το payment responce που έχουμε λάβει.
Αναμένω ενημέρωση, ευχαριστώ.

[Payment Responce Villagomez.txt](https://github.com/VivaPayments/API/files/1111622/Payment.Responce.Villagomez.txt)

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
