### ISSUE TITLE
enartia -> Viva Payments - Viva Wallet WooCommerce Payment Gateway

### ISSUE THREAD

**Issue by Nicolas37** [VivaPayments/API#344]
Καλημέρα,
Προσπαθώ να ενεργοποιήσω το enartia wordpress plugin και στη δήλωση URL Επιτυχημένης συναλλαγής και URL Αποτυχημένης συναλλαγής οι οδηγίες του plugin λένε να βάλω το παρακάτω:
"Συμπληρώνετε στα URL συναλλαγής wc api/WC_Papaki_Vivapayments_Gateway αν τα
friendly URLs (permalinks) είναι ενεργοποιημένα. Σε διαφορετική περίπτωση
?wc api=WC_Papaki_Vivapayments_Gateway"
Ο τεχνικός στο VIVA μου είπε ότι δεν είναι τα σωστά και ότι πρέπει να κάνω ένα post εδώ για να το δει κάποιος άλλος τεχνικός και να μου πει ποιά είναι τα σωστά. Το domain μου είναι το https://www.ntsamis.com
Ευχαριστώ,
Νικος Τσάμης

**Comment by VivaWalletSupport** [comment]
Uninstall current plugin, download and install the plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce follow the instructions given in the readme.txt file.

**Comment by Nicolas37** [comment]
Thank you!
