### ISSUE TITLE
Mobile API Authorization Header

### ISSUE THREAD

**Issue by deliverymanager** [VivaPayments/API#345]
Στη σελίδα αυτή γίνεται μία καλή περιγραφή της διαδικασίας για τη χρέωση κάρτας
https://github.com/VivaPayments/API/wiki/Mobile-API

1. Creation of the Payment Order
2. Card Tokenization
3. Installments check
4. Payment Execution

Ωστόσο, αυτό που δεν είναι πολύ ξεκάθαρο είναι ποιές από αυτές τις διαδικασίες (API requests στη VIVA) θα γίνουν στο client-side και ποιές server-side.
Συγκεκριμένα, το card tokenization θα πρέπει σίγουρα να γίνει στο client-side έτσι ώστε τα δεδομένα της κάρτας του χρήστη να μην περάσουν από το δικό μου server αλλά μόνο στο server της Viva. Το πρόβλημα όμως είναι ότι για να κάνω από το client-side κλήση sto card tokenization API, θα πρέπει να κάνω χρήστη το Authorization header (merchant id και api key) και του public key. Αυτό όμως δημιουργεί το πρόβλημα ότι εκθέτω στο client-side ουσιστικά όλα τα κλειδιά και κυρίως το Authorization header token το οποίο αν το έχει κάποιος μπορεί να κάνει σχεδόν τα πάντα με το API της Viva.

Οπότε που κάνω λάθος στο σκεπτικό και ποιός είναι ο σωστός τρόπος στησίματος του Mobile API;

**Comment by deliverymanager** [comment]
Κάνοντας μία μεγάλη έρευνα νομίζω ότι κατέληξα στο ότι μάλλον έχετε ξεχάσει κατά λάθος το  Authorization header στο POST /api/cards?key={YOUR_PUBLIC_KEY}
Διότι όπως το αντιλαμβάνομαι δεν έχει νόημα να χρησιμοποιείς και το Authorization Header και το public key στο client-side και ουσιαστικά να κάνεις expose του Authorization Header, όπου μπορεί κάποιος να το πάρει και να τραβήξει τα πάντα από άλλα API resources της Viva, όπως για παράδειγμα όλες τις πληρωμές της ημέρας, να κάνει επιστροφές πληρωμών κτλ.

Στόχος του MOBILE API θα έπρεπε να είναι προφανως ότι η κλήση για το tokenization ουσιαστικά να γίνεται απευθείας από τον client στο API της Viva χρησιμοποιώντας το public key.
Ετσι, τα στοιχεία της κάρτας δε θα κάνουν ποτέ κλήση στο δικό μας server, ώστε να μην υπάρχει ενδεχόμενο υποκλοπής των στοιχείων της κάρτας.
Η διαδικασία του Creation of the Payment Order όπου χρειάζεται Authorization Header, μπορεί να γίνεται backend όπως επίσης και η Payment Execution χρησιμοποιώντας το token της κάρτας όπου αυτό μπορούμε να στείλουμε στο backend σύστημά μας.

Οπότε δείτε το λίγο σας παρακαλώ διότι μου φαίνεται πολύ περίεργο αυτο που συμβαίνει αυτή τη στιγμή στον τρόπο λειτουργίας.

**Comment by deliverymanager** [comment]
Στο native http://demo.vivapayments.com/web/checkout/js υπάρχει αυτό το header NativeCheckoutVersion.
Το οποίο δε ξέρω τι ακριβώς είναι ...

>             t.ajax({
>                 url: u.urls.cardtoken + "?key=" + encodeURIComponent(s.settings.options.publicKey),
>                 type: "POST",
>                 headers: {
>                     NativeCheckoutVersion: VivaPayments.version
>                 },
>                 data: n
>             }).done(function(n) {
>                 i(n)
>             }).fail(function(n) {
>                 i(e(n.status, n.statusText))
>             })

**Comment by dmihos** [comment]
Καλησπέρα deliverymanager

Η χρήση του MobileApi αφορά αποκλειστικά native ios/android εφαρμογές.
Δεν επιτρέπεται να χρησιμοποιήσετε αυτές τις κλήσεις σε web εφαρμογές, αφού, όπως σωστά αναφέρετε, τίθονται σε κίνδυνο τα authorization details σας.

Το μόνο που μπορείτε να χρησιμοποιήσετε με ασφάλεια, σε client side web applications, είναι αυτό που περιγράφεται στη Native Checkout ([link](https://github.com/VivaPayments/API/wiki/Native-Checkout)), ακριβώς και μόνο με τον τρόπο που εκεί αναφέρεται.

Ευχαριστούμε για την επικοινωνία

**Comment by deliverymanager** [comment]
Καλησπέρα.
Με όλο το σεβασμό αυτό που λέτε δεν ισχύει.
Κάποιος μπορεί πολύ άνετα να διαβάσει όλα τα requests τα οποία γίνονται σε οποιοδήποτε API, απλώς συνδέοντας το κινητό του σε έναν υπολογιστή.
Οπότε συνεχίσω να πιστεύω ότι κατά λάθος έχετε βάλει το Authorization Header στο συγκεκριμένο API, από τη στιγμή που στο ίδιο API χρησιμοποιείτε και το public key.

Εγώ το έχω ήδη υλοποιήσει με το external script 
http://www.vivapayments.com/web/checkout/js
οπότε δεν έχω πρόβλημα αυτή τη στιγμή στην υλοποίησή μου.

Απλώς ήθελα να σας το αναφέρω ότι ουσιαστικά με τον υπάρχον τρόπο, όπου απαιτείται να κάνω κλήση από τις mobile εφαρμογές κάνοντας expose στο client side τον header, δεν έχει κανένα νόημα.
Αναρωτιέμαι γενικά αν το χρησιμοποιεί κάποιος merchant αυτή τη στιγμή, με τον τρόπο που το έχετε, μη γνωρίζοντας τον κίνδυνο του να κάνει expose στην εφαρμογή του τον Authorization Header.

Ευχαριστώ πολύ!

**Comment by dmihos** [comment]
Καλημέρα
Βοηθήστε με λίγο αν θέλετε: σε ποιο σημείο ακριβώς βλέπετε να έχουμε 'ξεχάσει' το authorization header;

**Comment by deliverymanager** [comment]
Στο documentation του συγκεκριμένου API POST **/api/cards**?key={YOUR_PUBLIC_KEY}
https://github.com/VivaPayments/API/wiki/Mobile-API
αν δείτε λέει ότι χρειάζεται μόνο το a. key και b. card options χωρίς το Authorization Header.

Στην πράξη όμως φαίνεται να θέλει και το Authorization Header, κάτι που δε βγάζει και πολύ νόημα καθώς αυτή η κλήση στο API θα πρέπει να γίνει από front end σημείο.

**Comment by dmihos** [comment]
To documentation είναι σωστό.
Το συγκεκριμένο action (POST>/api/cards?key), δεν απαιτεί Authorization Header.

**Comment by deliverymanager** [comment]
Αν το δοκιμάσετε πχ στο post man θα δείτε ότι αν δε βάλετε το Authorization Header πετάει
Status 404 Account token was not found for key ...

**Comment by dmihos** [comment]
Δεν υπάρχει τέτοιο θέμα.
Στείλτε μου, αν θέλετε, το merchantId και το public key σας στο demo για επιβεβαίωση.

**Comment by deliverymanager** [comment]
public key 7dqqrWkO+TSMIJNkygvaSN2yJYVg7sy26k81o6gNMG0=

**Comment by dmihos** [comment]
Ο χαρακτήρας '+' στο url σας δημιουργεί το πρόβλημα.
Δοκιμάστε να τον κάνετε escape, δλδ να χρησιμοποιήσετε το key
7dqqrWkO%2BTSMIJNkygvaSN2yJYVg7sy26k81o6gNMG0=

**Comment by deliverymanager** [comment]
OK. το μήνυμα του error 404 με οδηγούσε να πιστεύω ότι έλειπε το Authorization Header.
Ετσι όταν πρόσθετα το Authorization Header έπαιρνα κανονικά το token της κάρτας.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
