### ISSUE TITLE
Ενεργοποίηση "Πηγές Πληρωμών"

### ISSUE THREAD

**Issue by nikvaf** [VivaPayments/API#346]
Καλημέρα και καλή εβδομάδα,

θα μπορούσατε σας παρακαλώ να κοιτάξετε την πηγή πληρωμών (είναι σε εκκρεμότητα) στον λογαριασμό με ΑΦΜ 104318160? Υπάρχει κάποιος τρόπος να επισπεύσουμε την διαδικασία ενεργοποίησης?

Σας ευχαριστώ πολύ

**Comment by dmihos** [comment]
Καλησπέρα σας
Το παρόν repository αυτό είναι αποκλειστικά για technical support.
Στείλτε, αν θέλετε, ένα email στο merchants@vivawallet.com
Ευχαριστούμε για την επικοινωνία
