### ISSUE TITLE
Επαναλαμβανόμενες πληρωμές με "Pay with viva wallet"

### ISSUE THREAD

**Issue by StavrosMessaris** [VivaPayments/API#347]
Στις προϋποθέσεις για τις επαναλαμβανόμενες πληρωμές υπάρχει η οδηγία "Ο πελάτης σας να έχει τσεκάρει κατά την εξόφληση την επιλογή που επιτρέπει τις επαναλαμβανόμενες πληρωμές"

Γίνεται αυτό να υλοποιηθεί μέσω του "Pay with viva wallet" ή/και του native, ή γίνεται μόνο με το redirect; Ρωτάω γιατί δεν βρίσκω πώς να κάνω την επιλογή να εμφανιστεί στο "Pay with viva wallet".

**Comment by defilerc** [comment]
Καλημέρα @StavrosMessaris ,

Επαναλαμβανόμενες πληρωμές δεν υποστηρίζονται μέσω _Pay with Viva Wallet_. Οι μόνοι τρόποι είναι μέσω _Redirect Checkout_ και _Native Checkout_.

Στην περίπτωση της _Native Checkout_, θα πρέπει να φροντίσετε **εσείς** να εμφανίσετε το checkbox που ενημερώνει το χρήστη ότι δέχεται να υπάρχουν επαναλαμβανόμενες χρεώσεις.

Στη συνέχεια θα πρέπει:

1. Κατά το CreateOrder, η δημιουργία του Order να γίνει με την επιλογή `AllowRecurring = true` (δείτε και [εδώ](https://github.com/VivaPayments/API/wiki/Optional-Parameters)). 

1. Κατά τη δημιουργία της πρώτης χρέωσης (POST στην `/api/transactions`), να περάσετε την επιλογή `AllowsRecurring = true` (προσοχή, είναι διαφορετικό το όνομα της παραμέτρους από αυτό της CreateOrder, καθώς περιέχει και ένα επιπλέον s).

Μπορείτε να βρείτε αντίστοιχα issues και εδώ: https://github.com/VivaPayments/API/issues/167, https://github.com/VivaPayments/API/issues/138

Στη διάθεσή σας για οποιαδήποτε περαιτέρω βοήθεια!

**Comment by StavrosMessaris** [comment]
Ευχαριστώ για την απάντηση!

Υπάρχει πλάνο για προσθήκη της δυνατότητας επαναλαμβανόμενων πληρωμών στο Pay with Viva Wallet στο μέλλον;

**Comment by defilerc** [comment]
Καλησπέρα @StavrosMessaris ,

Προς το παρών, δεν υπάρχει κάποιο πλάνο για κάτι τέτοιο.

Με εκτίμηση,

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
