### ISSUE TITLE
"This card does not support electronic transactions"

### ISSUE THREAD

**Issue by pashtete** [VivaPayments/API#349]
Hello

Merchant ID 197a8eb4-a74b-4998-9f4a-4e506dc03dba. 

We got an error:
"This card does not support electronic transactions. In order to complete this payment please use a different card, or add funds to your Viva Wallet."

Help please solve this problem.

Thank you.

**Comment by dmihos** [comment]
Hello
The account seems to be properly configured.
What is the card you are trying to charge? (first 6 digits only)
Thanks

**Comment by pashtete** [comment]
4344 84** **** ****
Thanks, not working not only this one, with same error.

**Comment by dmihos** [comment]
You should be OK now, please try again and let us know if you still have issues.

**Comment by pashtete** [comment]
its ok now. thank you.
