### ISSUE TITLE
Android basic authorization

### ISSUE THREAD

**Issue by zisk11** [VivaPayments/API#35]
Hi,

I would like to know in which link i have to send my requests so i can achieve a basic auth.
Also,the api have a specific format for the authorization for example i have to use JSON or i can use base 64 encode ?

Thanks in advance

**Comment by dmihos** [comment]
Hi zisk11, sorry for the late response.

Do you still have trouble with authentication?
There is no specific url you should call for authentication. Instead, every api call should include a standard authorization header, as shown in the [samples](https://github.com/VivaPayments/API) section.
Please provide more info if you need any further assistance.
