### ISSUE TITLE
Μετά απο επιτυχημένη πληρωμή, δεν κάνει redirect

### ISSUE THREAD

**Issue by dervisis** [VivaPayments/API#350]
Καλημέρα,
έχουμε υλοποιήσει την σύνδεση με το vivapayments με custom εφαρμογή στο eshop του πελάτη.
Μετά από επιτυχημένη πληρωμή, δεν κάνει redirect. 
Έχουμε δημιουργήσει στο πάνελ του πελάτη, **νέα πηγή πληρωμών** με τα σωστά στοιχεία (successfull url). Πρέπει να επεξεργαστούμε την default μέθοδο? ή με κάποιο τρόπο να ορίσουμε την πηγή αυτή ως προκαθορισμένη;

**Comment by dervisis** [comment]
Μπορεί κάποιος να με ενημερώσει που μπαίνει η παράμετρος linked wallet ? αλλιώς να κάνω edit το default στο πάνελ σας.

**Comment by dmihos** [comment]
Καλημέρα
Σχετικά με το redirect, θα πρέπει να περάσετε το SourceCode (κωδικός) της πηγής, στην παράμετρο SourceCode του [CreateOrder](https://github.com/VivaPayments/API/wiki/CreateOrder).
Σχετικά με το linked wallet, η σύνδεση γίνεται μόνο στην πηγή συναλλαγών.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
