### ISSUE TITLE
Διακοπή της αυτόματης επαναλαμβανόμενης πληρωμής

### ISSUE THREAD

**Issue by dimitrap** [VivaPayments/API#352]
Καλησπέρα,

Έχουμε ενσωματώσει το vivapayments με redirection, στον ιστότοπο μας ώστε να γίνονται οι πληρωμές των μηνιαίων συνδρομών από τους πελάτες μας.  
Όταν ένας πελάτης κατά την πληρωμή του, τσεκάρει την επιλογή
"Aποδέχομαι να χρησιμοποιείται η κάρτα για μελλοντικές ή επαναλαμβανόμενες χρεώσεις στο μέλλον.." (και επομένως ανανεώνεται η συνδρομή του αυτόματα κάθε μήνα),  με ποιον τρόπο μπορεί να διακόψει την αυτόματη ανανέωση? 
Σημείωση: Δεν έχει viva account ο συγκεκριμένος πελάτης.

**Comment by dmihos** [comment]
Καλησπέρα

Η τύπου 'ανανέωση συνδρομής' συναλλαγές εκτελούνται από τον έμπορο με [Recurring Payments](https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction).
Συνεπώς, ο πελάτης δεν έχει κάτι να δηλώσει στη Viva Payments για τη διακοπή.
Η αίτηση διακοπής θα πρέπει να γίνει στο δικό σας σύστημα, το οποίο θα σταματήσει να στέλνει νέες χρεώσεις.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
