### ISSUE TITLE
Πρόβλημα διασύνδεσης του e-shop  μου με viva wallet 

### ISSUE THREAD

**Issue by kostasgkou** [VivaPayments/API#353]
Καλημέρα σας προσπαθώ εδώ και ένα μήνα να συνδέσω το e-shop μου ( είναι σε πλατφόρμα shopify ) με το viva wallet μου . Έχω βάλει τους κωδικούς μου store token και merchant ID αλλά πάλι μου βγάζει μήνυμα στο e-shop όταν μπαίνουν για να βάλουν την κάρτα τους : error signature not verified . Κοίταξα στις πηγές πληρωμών στο πορτοφόλι μου στη viva wallet και είδα ότι έχω τρεις τύπους για ιστοσελίδα το αρχικό που είχα φτιάξει εγώ το οποίο είχε integration method : native πληρωμή και άλλους δυο τύπους όπου είχαν redirection , αυτό που γράφει shopify το άλλαξα σε native πληρωμή και περιμένω έγκριση είναι κάτι άλλο που πρέπει να κάνω ? Ευχαριστώ πολύ

**Comment by dmihos** [comment]
Καλημέρα
Επαναφέραμε την πηγή Shopify στα σωστά settings. Πουθενά δεν αναφέρουμε ότι πρέπει να γυρίσετε το type σε Native.
Βεβαιωθείτε ότι έχετε βάλει, στα settings, σωστά το merchantId και το storetoken που σας δώθηκε με email.
Έγινε έλεγχος και δοκιμαστική πληρωμή, δεν υπάρχει κανένα πρόβλημα configuration.

**Comment by kostasgkou** [comment]
Και το store token αλλά και το merchard id είναι σωστά πάλι μου βγάζει error signature not verified

**Comment by kostasgkou** [comment]
Παρόλο που οι κωδικοί είναι εντάξει το πρόβλημα παραμένει. Μπορεί κάποιος να μου πει τι συμβαίνει και πως να λυθεί το πρόβλημα ?

**Comment by dmihos** [comment]
To στοιχεία σας έχουν δοκιμαστεί σε test store του shopify και λειτουργούν σωστά.

Λόγω autocomplete στους browsers, παρατηρείται συχνά να μην αποθηκεύονται σωστά το merchantId και το storetoken. Δοκιμάστε κάποιον άλλο browser, στείλτε και ένα screenshot που να φαίνονται τα πεδία συμπληρωμένα σωστά στο merchants@vivawallet.com, με αναφορά στο παρόν issue.

**Comment by kostasgkou** [comment]
Έστειλα αυτά που μου είπατε στο merchant, άλλαξα τους κωδικούς στο firefox , google chrome και opera όπως μου είπατε αλλά και πάλι με τα το πάτημα του πελάτη για να βάλει τον αριθμό της κάρτας του βγαίνει το μήνυμα : error signature not verified , περιμένω μια απάντηση για να λυθεί επιτέλους το πρόβλημα

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.

**Comment by BalinisCaprets** [comment]
Αντιμετωπίζω σχετικό πρόβλημα κατά την ολοκλήρωση της αγοράς, έχω συνδέσει το Viva με Shopify και όταν προσπαθώ να κάνω πληρωμή εμφανίζεται μήνυμα "STORE NOT FOUND"
