### ISSUE TITLE
Σύνδεσή Viva Payment Gateaway με WooComerce eShop 

### ISSUE THREAD

**Issue by jimarasss1** [VivaPayments/API#355]
Καλησπέρα μόλις σήμερα έκανα την πρώτη εγγραφή μου στο Viva Wallet και έχω μερικές απορείς ως προς την σύνδεση του με το eShop μου.

Αρχικά βρήκα ένα word press plug in για το Viva Wallet και το πέρασα κανονικά. Απλά σαν μόνη δυνατότητα για πληρωμή μέσω Viva Wallet δίνει : 1) Μέσω κάρτας 2) Μέσω Viva Wallet Funds. Θα ήθελα να ενεργοποιήσω την δυνατότητα πληρωμής μέσω των Viva Spots αλλά και του Pay@Home. Πως μπορώ να το κάνω;

Ευχαριστώ πολύ εκ των προτέρων.

**Comment by VivaWalletSupport** [comment]
Have a look at the available options https://github.com/VivaPayments/API/wiki/Optional-Parameters
At the moment you would have to modify the wc-vivawallet.php file ($poststring['PaymentTimeOut'] = '300';) and set the timeout to at least 2 working days (change 300 to 65535 to never timeout).

**Comment by jimarasss1** [comment]
Hello and thanks for your reply. After the modification I could normaly do transactions with cash options available?

The "DisableCash" and "DisablePayAtHome" is something that I can not find at the .php.

**Comment by VivaWalletSupport** [comment]
You should be able to, as you do not want to disable these methods you do not have to use these parameters. 

⁣Sent from BlueMail ​

**Comment by jimarasss1** [comment]
I changed the PaymentTimeOut but still I got the message Order code expires on : 7/20/2017 15:00 and still not any other payment options available. Any solution?

**Comment by jimarasss1** [comment]
Thats my php file. Still code expires early. 
[wc-vivawallet.zip](https://github.com/VivaPayments/API/files/1162260/wc-vivawallet.zip)

**Comment by VivaWalletSupport** [comment]
Also make the change a little below, in following line:

$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&**PaymentTimeOut=300**';

**Comment by jimarasss1** [comment]
Thank you very much! Issue solved! :)
