### ISSUE TITLE
Απενεργοποίηση email και τηλέφωνο στην redirect φόρμα

### ISSUE THREAD

**Issue by dimkasta** [VivaPayments/API#356]
Είναι δυνατή η απενεργοποίηση των πεδίων email και τηλέφωνο στη φόρμα πληρωμής redirect?

Ευχαριστώ

**Comment by dmihos** [comment]
Καλησπέρα
Αν περάσετε Email/Phone κατά το Create Order, τότε στη σελίδα πληρωμής αυτά εμφανίζονται readonly.

**Comment by dimkasta** [comment]
Οπότε πρέπει να συμπληρωθούν με τον ένα ή τον άλλο τρόπο. 
ΟΚ ευχαριστώ για τη γρήγορη απάντηση

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
