### ISSUE TITLE
Error μετά απο την ολοκλήρωση διαδικασίας συνδεσης με woocommerce

### ISSUE THREAD

**Issue by KoukoumisChristos** [VivaPayments/API#357]
Καλησπέρα,προσπαθούμε να συνδέσουμε το vivapayments plugin με ενα woocommerce e-shop,ολοκληρώσαμε τη διαδικασία εγκρισης του url από το viva wallet και βάλαμε τα σωστά στοιχεία στα settings tou plug in,παρ'όλα αυτα κατα την προσπάθεια πληρωμής, το plug in δεν ανοίγει νέο παράθυρο αλλά βγάζει error "wrong merchant credentials or api unavailable". Τα merchant credentials τα έχουμε πάρει απο το προφίλ μας στο viva.υπάρχει κάποιος τρόπος να εντοπίσουμε το λάθος?

**Comment by VivaWalletSupport** [comment]
Hello, what plugin are you using for Vivawallet?

**Comment by KoukoumisChristos** [comment]
i am using this plugin -> https://el.wordpress.org/plugins/woo-payment-gateway-viva-wallet/

**Comment by VivaWalletSupport** [comment]
Use following plugin: https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
