### ISSUE TITLE
Viva Wallet σε Wordpress και γλώσσες

### ISSUE THREAD

**Issue by statkats** [VivaPayments/API#358]
![viva](https://user-images.githubusercontent.com/30459400/28607802-2a62ade8-71e6-11e7-83a1-8d6fef4cd179.jpg)
Καλημέρα,
Σε site wordpress κατά την διαδικασία checkout στην περιγραφή χρέωσης και στην επιλογή τρόπου πληρωμής. τα στοιχεία όλα εμφανίζονται στα ελληνικά.
Επίσης στο πάνω μέρος εμφανίζονται το αγγλικό και το ελληνικό σημαιάκι.
Επειδή το site είναι μόνο ξενόγλωσσο, υπάρχει τρόπος να κόψω τα ελληνικά σαν γλώσσα κατά την διαδικασία checkout μέσω Viva Wallet?

**Comment by VivaWalletSupport** [comment]
Hello, are you using a specific e-commerce package (like WooCommerce) and in case you are using a specific plugin for the payment could you specify what plugin is used?

**Comment by statkats** [comment]
Hello, I use Woo Commerce and also I use [Viva Payments – Viva Wallet WooCommerce Payment Gateway](https://wordpress.org/plugins/woo-payment-gateway-for-vivapayments/), but I'm sure that the problem is into Viva Payments environment, it's not a plugin's issue.
As you can see at the picture we have 2 languages, english flag and greek flag, it's a problem relative with Viva Payments and not with plugin.

**Comment by VivaWalletSupport** [comment]
It is a problem of the plugin you are using, it has hard-coded the RequestLang parameter to Greek language. Try following plugin: https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
