### ISSUE TITLE
Native CheckOut Error 422

### ISSUE THREAD

**Issue by mmplazz** [VivaPayments/API#359]
Καλησπέρα,

Έχουμε 2 viva accounts σε δυο διαφορετικές χώρες και έχουμε κάνει ακριβώς τις ίδιες ρυθμίσεις και στα δυο για να χρησιμοποιήσουμε το viva native checkout. Ο κώδικας που τρέχει είναι ίδιoς και στα δυο account.

Ενώ στο πρώτο μας account όλα δουλευουν κανονικά, στο δεύτερο παίρνουμε μονίμος error response με Code: 422 και Msg: PaymentsNoBinRouteFound.

Εχουμε μιλήσει με το support το οποίο μας προέτρεψε απλά να γράψουμε το πρόβλημα μας εδώ...

Παρακαλώ να μας ενημερώσετε για τις πιθανές αιτίες αυτου του error λαμβάνοντας υπόψιν οτι χρησιμοποιούμε εγκεκριμένα και ενεργά sources σεταρισμένα για native checkout σε https.

**Comment by aleksanderd** [comment]
+1

But in my case I use demo account with demo card. And can not get success test payment with error: PaymentsNoBinRouteFound.

@mmplazz did you solve or understand the problem?

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.
