### ISSUE TITLE
PaymentsInvalidAmountForVoid error when issuing a refund

### ISSUE THREAD

**Issue by franticpsyx** [VivaPayments/API#361]
Hi,

We are trying to use the [CancelTransaction](https://github.com/VivaPayments/API/wiki/CancelTransaction) method to issue a refund at demo.vivapayments.com but always get the following response back:

```
{
    "Amount": null,
    "AuthorizationId": null,
    "CorrelationId": null,
    "CurrencyCode": null,
    "Emv": null,
    "ErrorCode": 400,
    "ErrorText": "PaymentsInvalidAmountForVoid",
    "EventId": 0,
    "ReferenceNumber": null,
    "RemainingRefunds": null,
    "RetrievalReferenceNumber": null,
    "StatusId": "E",
    "Success": false,
    "TimeStamp": "2017-07-28T16:07:27.2565658+03:00",
    "TransactionId": null
}
```

Here's an example you can try:

`curl -X DELETE -u 9eb9b9a0-8037-4dc1-ae7a-b91cac8c039a:e{izPG "http://demo.vivapayments.com/api/transactions/f2fd7900-3558-477e-8fc2-f57003ffa11a/?Amount=10" -H "Content-Type: application/json" | python -m json.tool`

Maybe we are doing something wrong? Unfortunately `PaymentsInvalidAmountForVoid` doesn't help us figure out what it might be. Any help would be appreciated!

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
