### ISSUE TITLE
On Native Checkout always creating CORS problem

### ISSUE THREAD

**Issue by MahbbRah** [VivaPayments/API#362]
I followed all the steps for setup a Native payment system with vivaPayment. But unfortunately, It's always throwing an error the CORS error. 

**The error in Firefox console:**
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://demo.vivapayments.com/api/cards?key=l0Bf9SBPokj1oGqFhEoD1XgtU0MR1yIH1aUiQy5MHdE%3D. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).  (unknown)
Object { Error: Object }`

**Error in Chrom console:**

`OPTIONS https://demo.vivapayments.com/api/cards?key=xxxxxxxxxxxxx 500 (Internal Server Error)
send @ jquery-1.11.2.min.js:4
ajax @ jquery-1.11.2.min.js:4
s.requestToken @ js:1
onclick @ (index):67
(index):1 XMLHttpRequest cannot load https://demo.vivapayments.com/api/cards?key=xxxxxxxxxxxxx. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://xxxxxxxx.com' is therefore not allowed access. The response had HTTP status code 500.
(index):21 Object {Error: f}`

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
