### ISSUE TITLE
Checkout Token Decryption failed -- Taken the token from vivaWallet pay Button

### ISSUE THREAD

**Issue by MahbbRah** [VivaPayments/API#363]
Hey good evening guy's
I just Took the token from VivaWallet Pay button and using this onto creating the actual charge. But It's says Checkout token decryption failed! It's wired But no clue why? Please Check it out and waiting for help

**Here is full Codes you can have a look on it**

`<?php
	if($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['vivaWalletToken'])) {
		$request =  'http://demo.vivapayments.com/api/transactions';	// demo environment URL
		$MerchantId = 'xxxxxxxxxxxxxxxxxxxx';
		$APIKey = 'dsafsdfdsf'; 	
		
		$postargs = 'PaymentToken='.$_POST['vivaWalletToken'];

		// Get the curl session object
		$session = curl_init($request);

		// Set the POST options.
		curl_setopt($session, CURLOPT_POST, true);
		curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
		curl_setopt($session, CURLOPT_HEADER, true);
		curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
		curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

		// Do the POST and then close the session
		$response = curl_exec($session);

		// Separate Header from Body
		$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
		$resHeader = substr($response, 0, $header_len);
		$resBody =  substr($response, $header_len);

		curl_close($session);

		// Parse the JSON response
		try {
			if(is_object(json_decode($resBody))){
			  	$resultObj = json_decode($resBody, FALSE, 512, JSON_BIGINT_AS_STRING); 
			}else{
				preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader, $match);
						throw new Exception("API Call failed! The error was: ".trim($match[1]));
			}
		} catch( Exception $e ) {
			echo $e->getMessage();
		}

		if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
			$orderId = $resultObj->OrderCode;
			echo 'Your Order Code is: <b>'. $orderId.'</b>';
			echo '<br/><br/>';
			echo 'To simulate a successfull payment, use the credit card 4111 1111 1111 1111, with a valid expiration date and 111 as CVV2.';
			echo '</br/><a href="http://demo.vivapayments.com/web/newtransaction.aspx?ref='.$orderId.'" >Make Payment</a>';
		}
			
		else{
			echo 'The following error occured: ' . $resultObj->ErrorText;
		}
	}
?>
`

`     <!DOCTYPE html>
     <html lang="en">
     <head>
	<meta charset="UTF-8">
	<title>Pay with Pay Button Viva Payments</title>
     </head>
     <body>
	<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
	<script src="https://demo.vivapayments.com/web/checkout/js"></script>
		<form id="myform" action="" method="post">
		<button type="button"
		data-vp-publickey="gdfgdggdfgdfgdfgdfgdfere"
		data-vp-baseurl="https://demo.vivapayments.com"
		data-vp-lang="el"
		data-vp-amount="1000"
		data-vp-description="My product">
		</button>
		</form>
      </body>
      </html>`

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
