### ISSUE TITLE
viva Wallet Buttons returning success false after while try to create the actual charge

### ISSUE THREAD

**Issue by MahbbRah** [VivaPayments/API#364]
I don't know what actually is the reason But the viva wallet returning this json output as response and I'm user didn't charged! 
`T15:31:39.2545591+03:00","CorrelationId":null,"EventId":0,"Success":false}`

Here is my full code I think it's alright 

`<?php
	if($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['vivaWalletToken'])) {

		$request =  'http://demo.vivapayments.com/api/transactions';	// demo environment URL
		$MerchantId = 'xxxxxxxxxxxxxxxxxxxxxxx';
		$APIKey = 'xxxxxxxxxxxxxxxxxxxxx'; 	
		
		$postargs = 'PaymentToken='.$_POST['vivaWalletToken'];
		// Get the curl session object
		$session = curl_init($request);
		// Set the POST options.
		curl_setopt($session, CURLOPT_POST, 443);
		curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
		curl_setopt($session, CURLOPT_HTTPHEADER, array(
        'Content-Type: application/json',
        'Content-Length: ' . strlen($postargs))
		);
		// curl_setopt($session, CURLOPT_HEADER, true);
		curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
		// curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
		curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
		

		// Do the POST and then close the session
		$response = curl_exec($session);

		// Separate Header from Body
		$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
		$resHeader = substr($response, 0, $header_len);
		$resBody =  substr($response, $header_len);

		curl_close($session);

		echo '<pre>';
		echo $resBody;
	}
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Pay with Pay Button Viva Payments</title>
</head>
<body>
	<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
	<script src="https://demo.vivapayments.com/web/checkout/js"></script>
		<form id="myform" action="" method="post">
		<button type="button"
		data-vp-publickey="xxxxxxxxxxxxxxxxxxxxxxxxxxx="
		data-vp-baseurl="https://demo.vivapayments.com"
		data-vp-lang="el"
		data-vp-amount="1000"
		data-vp-description="My product">
		</button>
		</form>
</body>
</html>`

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
