### ISSUE TITLE
Αποστολή email στον πελάτη αν γίνει ακύρωση της πληρωμής

### ISSUE THREAD

**Issue by nikos134** [VivaPayments/API#365]
Καλησπέρα,
Μέτα την επιτυχή πληρωμή από την πλευρά του πελάτη μέσω redirect όταν γίνεται το redirect πίσω στην σελίδα μου κάνω κάποιους ελέγχους αν κάποιος έλεγχος δεν περάσει κάνω ακύρωση της συναλλαγής. Ενώ η viva στέλνει στο email του πελάτη ότι έκανε πληρωμή δεν στέλνεται κάποιο ανάλογο email ότι έχει γίνει ακύρωση για τον ενημερώσει. Γίνεται κάπως να ενεργοποιήσουμε την αποστολή email για να ενημερωθεί ο πελάτης ότι όντως ακυρώθηκε η χρέωση?

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
