### ISSUE TITLE
Node js κλήση στο CreateOrder

### ISSUE THREAD

**Issue by maznick** [VivaPayments/API#366]
Καλημέρα σας,
δοκιμάζω να κάνω την κλήση με node js στο CreateOrder για να χρησιμοποιήσω τη μέθοδο Redirect Checkout. Επειδή δεν έχετε κάποιο sample code για node js μπορείτε να μου στείλετε ένα πρότυπο;
Αυτό που μου επιστρέφει στην κλήση είναι error code 400.

**Comment by maznick** [comment]
To έφτιαξα. Δοκίμαζα να στείλω με json post data αλλά έπρεπε να τα έχω σαν query string

**Comment by miljkovicmisa** [comment]
> To έφτιαξα. Δοκίμαζα να στείλω με json post data αλλά έπρεπε να τα έχω σαν query string

Καλησπέρα, επειδή κι'εγώ αντιμετώπισα το ίδιο πρόβλημα και θα ήθελα ένα sample code για το node, θα μπορούσες να μοιραστείς τον κώδικά σου;
