### ISSUE TITLE
Πρόβλημα κατά την πληρωμή - Πολλά emails μετά από πληρωμή μέσω viva

### ISSUE THREAD

**Issue by tiesgr** [VivaPayments/API#367]
Καλησπέρα σας,

Θα ήθελα να διατυπωσω ένα πρόβλημα που έχω με έναν πελάτη από την δουλειά μου ο οποίος χρησιμοποιεί vivapayments. 
Χρησιμοποιεί το vivapayments μαζί με το woocommerce και το woo appointments όταν λοιπόν κάποιος κάνει την πληρωμή μέσα από το viva payments ο πελάτης δέχεται γύρω στα 11 email επιβεβαίωσης. 

Έχει συμβεί και σε κάποιον άλλο αυτό μήπως; Θα χρειαστώ κάποια αναβάθμιση στο πρόσθετο σχετικά με τις πληρωμές VIVA για να είναι συμβατό με την τελευταία έκδοση woocommerce και wordpress γενικότερα;

Οποιαδήποτε βοήθεια είναι ευπρόσδεκτη.

Σας ευχαριστώ.

**Comment by VivaWalletSupport** [comment]
Hello, are you using the plugin provided by Vivawallet?
https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

**Comment by tiesgr** [comment]
Hello,

My apologies for the late answer. Yes this is the plugin that I am using. I think that maybe the problem occurs from woo appointments because I can't think something else. 
Viva payments is controlling the payment but while it is handling the payment it sends more than 11-15 emails to administrator that a payment has been made.
I don't know if it sends the same amount of email at the customers.
This is a disaster because it really turns the email account into a spammer and we are facing the problem of being blacklisted and we have to clean the email account every 4-5 payments.
Please any help I would be grateful.

Thank you,

Kind regards,

Nikos

**Comment by VivaWalletSupport** [comment]
The plugin just executes once the payment_complete function in case the success url is followed, it does not send additional emails.

**Comment by tiesgr** [comment]
I have communicated with the plugin that actually handles the emails after a payment has proceeded successfully. The plugin is the woo appointments. So I really believe that this is an issue that the plugin is responsible for.

I 'll keep you updated.

Thank you.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
