### ISSUE TITLE
Πρόβλημα στην ολοκλήρωση της πληρωμής

### ISSUE THREAD

**Issue by SonataAmanes** [VivaPayments/API#368]
Καλησπέρα σας,

Πριν από λίγο εγκρίθηκε το domain μου για να λαμβάνει πληρωμές μέσω viva. Προσπάθησα να κάνω μια δοκιμαστική παραγγελία για να δω όλη τη διαδικασία πληρωμής και αντιμετωπίζω το εξής πρόβλημα:

Μετά την εκτέλεση της πληρωμής:
Θα έπρεπε ο χρήστης να οδηγείται στο URL επιτυχημένης συναλλαγής όπως είναι κατασκευασμένη στο website μας και δηλωμένη στις πηγές πληρωμών:
(https:/www.meliory.gr/σας-ευχαριστούμε-για-την-παραγγελία-σ/) 
https://www.meliory.gr/%CF%83%CE%B1%CF%82-%CE%B5%CF%85%CF%87%CE%B1%CF%81%CE%B9%CF%83%CF%84%CE%BF%CF%8D%CE%BC%CE%B5-%CE%B3%CE%B9%CE%B1-%CF%84%CE%B7%CE%BD-%CF%80%CE%B1%CF%81%CE%B1%CE%B3%CE%B3%CE%B5%CE%BB%CE%AF%CE%B1-%CF%83/

Αντί αυτού, το παραπάνω URL ακολουθείται από ?t=ba9d9888-3880-438c-bd9d-d47e2c352a78&s=8127725042472601&lang=el-GR 
με αποτέλεσμα να υπάρχει error 404. Συγκεκριμένα, ο χρήστης οδηγείται εδώ:
https://www.meliory.gr/%cf%83%ce%b1%cf%82-%ce%b5%cf%85%cf%87%ce%b1%cf%81%ce%b9%cf%83%cf%84%ce%bf%cf%8d%ce%bc%ce%b5-%ce%b3%ce%b9%ce%b1-%cf%84%ce%b7%ce%bd-%cf%80%ce%b1%cf%81%ce%b1%ce%b3%ce%b3%ce%b5%ce%bb%ce%af%ce%b1-%cf%83/?t=ba9d9888-3880-438c-bd9d-d47e2c352a78&s=8127725042472601&lang=el-GR

Επιπλέον, ενώ έλαβα κανονικά το email για την λήψη της πληρωμής, στο website μας δεν ελήφθη η παραγγελία, προφανώς λόγω του 404 που ακολούθησε την πληρωμή.

**Comment by SonataAmanes** [comment]
Κατάφερα να λύσω το πρώτο πρόβλημα.
Το θέμα με τα plugins είναι ότι το URL που θα πρέπει να συμπληρωθεί στην πηγή πληρωμής, δεν είναι η σελίδα επιτυχημένης συναλλαγής που έχουμε δημιουργήσει στο website, αλλά αυτό που δίνει ο δημιουργός του plugin. 
Στην περίπτωσή μου χρησιμοποιήθηκε το plugin Viva Payments – Viva Wallet WooCommerce Payment Gateway και το url επιτυχημένης συναλλαγής που πρέπει να συμπληρωθεί στις πηγές πληρωμών της viva είναι yourdomainname.gr/wc-api/WC_Papaki_Vivapayments_Gateway

Προς το παρόν δεν λειτουργεί το url αποτυχημένης συναλλαγής.
Επιπλέον, το βασικότερο είναι ότι μετά από μια επιτυχημένη συναλλαγή, η παραγγελία δεν εμφανίζεται στο dashboard του wordpress.

**Comment by VivaWalletSupport** [comment]
Try the supported plugin located at: https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce
and follow the instructions to the letter.

**Comment by SonataAmanes** [comment]
Thank you very much. It works perfectly.

Regarding the webhooks, I faced an error with the url verification. I just went to viva dashboard and created the webhook. Should I add any code of file before creating the webhook?

**Comment by VivaWalletSupport** [comment]
Made a small correction to the wc-vivawallet.php file, replace it with your current file.

**Comment by SonataAmanes** [comment]
Thank you.
I replaced wc-vivawallet.php with the new file, but I still get the following error with the webhook url:

Σφάλμα! Το url που εισάγατε δε μπορεί να επιβεβαιωθεί. Παρακαλώ βεβαιωθείτε ότι είναι ένα έγκυρο, προσβάσιμο url φτιαγμένο με αυτές τις προδιαγραφές. (Κωδ. Σφάλματος 502)

**Comment by VivaWalletSupport** [comment]
Made another little change to the same file, please try again.

**Comment by SonataAmanes** [comment]
Hello, 
The plugin now works perfectly. Successful and failed payment redirections, webhooks, woocommerce order handling, all tested and work great.

Just one minor issue: When a payment is failed, I still get the order at WC dashboard, with pending payment status, until it gets cancelled after the WC hold stock time. Maybe these orders should not pass through, as they diminish stock, which has to be manually reset afterwards.

**Comment by VivaWalletSupport** [comment]
The order remains pending after a failed transaction so that the customer has the opportunity to checkout again using the same or another payment method. In case the order would be canceled, the customer would have to start from scratch again to make the purchase. Further more, WooCommerce has the option to cancel automatically pending orders after a set amount of time.

**Comment by SonataAmanes** [comment]
Thank you, your support is great and comprehensive.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.

**Comment by pentesgeorge** [comment]
Hello,
can you publish the solution?

Thank you!
