### ISSUE TITLE
Δεν γίνεται redirect μετά την ολοκλήρωση της συναλλαγής

### ISSUE THREAD

**Issue by Sujiyama** [VivaPayments/API#370]
Καλησπέρα σας, 
Θέλουμε να προσθέσουμε ,σε ένα eshop που κατασκευάζουμε, τρόπο πληρωμής με viva wallet. To project είναι γραμμένο σε C# ASP.NET MVC και είναι custom project. 

Καταφέραμε να κάνουμε το redirect με την επιβεβαίωση τις παραγγελίας αλλά δεν μπορούμε να καταφέρουμε τα εξής:
1) Δεν μπορούμε να καταλάβουμε πως να καταχωρήσουμε στα payment sources μέσω API τα return url. Το μόνο που βρήκαμε είναι αυτό https://github.com/VivaPayments/API/wiki/Payment-Sources:-AddSource αλλά δεν καταλαβαίνουμε μήπως είναι εύκολο να έχουμε κάποιο παράδειγμα με C# παρακαλώ?
2) Απο την στιγμή που δεν καταφέραμε το προηγούμενο καταχωρήσαμε τα return urls χειροκίνητα σε λογαριασμό στο http://demo.vivawallet.com για να κάνουμε δοκιμές αλλά δεν κάνει redirect στα αντίστοιχα Action Results που έχουμε κατασκευάσει. Τις οδηγίες τις είδαμε απο εδώ https://github.com/VivaPayments/API/wiki/Redirect-Checkout. 
Ο κώδικας των urls είναι ο παρακάτω: 
`
public ActionResult VivaSuccess(Int64 s, Guid t, string Lang)
		{

			try
			{
				TransactionEntry order = _uw.TransactionEntryRepository.GetByID(new Guid(t.ToString()));
				order.TransactionNotes.Add(new TransactionNote
				{
					ID = Core.Sys.SequentialGuid(),
					Note = "Payment with viva completed",
					DisplayToCustomer = false,
					CreateDate = DateTime.UtcNow
				});

				order.PaymentStatus = 20;
				_uw.TransactionEntryRepository.Update(order);
				_uw.Save();

			return RedirectToAction("OrderComplete", "Checkout", new { TransactionID = t });
		}`

`public ActionResult VivaFail(Int64 s, Guid t, string Lang)
		{

			try
			{
				TransactionEntry order = _uw.TransactionEntryRepository.GetByID(new Guid(t.ToString()));
				order.TransactionNotes.Add(new TransactionNote
				{
					ID = Core.Sys.SequentialGuid(),
					Note = "Payment with viva canceled",
					DisplayToCustomer = false,
					CreateDate = DateTime.UtcNow
				});

				order.OrderStatus = 3;
				order.PaymentStatus = 10;
				_uw.TransactionEntryRepository.Update(order);
				_uw.Save();

			}
			catch { }

			return RedirectToAction("OrderNotComplete", "Checkout", new { TransactionID = t });
		}`

Μπορείτε να μας βοηθήσετε παρακαλώ τι κάνουμε λάθος και δεν μπαίνει μέσα στα actionResults?
Ευχαριστούμε

**Comment by Sujiyama** [comment]
I am sorry i press Ctrl + Enter while writing and the comment posted before finish it.

**Comment by Sujiyama** [comment]
If you want to rewrite it in english the post please tell me and i do it. Thanks

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
