### ISSUE TITLE
Prestashop Plug-in (bad request)

### ISSUE THREAD

**Issue by samator79** [VivaPayments/API#371]
![corel000](https://user-images.githubusercontent.com/31441644/29821327-2f491ab8-8cd0-11e7-9e52-1453fd1a0e25.jpg)
Hi VivaPayments

I have a issue when i tray to pay in prestashop.

You know whats is the problem and whats i can to do to fix this.

Thank you very much for reply.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
