### ISSUE TITLE
Magento Extension - Bad Request

### ISSUE THREAD

**Issue by CarlosUceira** [VivaPayments/API#372]
Hi, I have installed the extension on based on the instructions received.

 https://github.com/VivaPayments/API/wiki/Integration-with-eCommerce-platforms

We have set up a sandbox account to test, we have added the Merchand ID,  API Key and Source Code. When I am going to pay using VivaWallet, instead of redirecting I am receiving a Bad Request answer. 

Is there anything I am missing in the configuration.

Thanks!
Regards

**Comment by VivaWalletSupport** [comment]
Could you post some screenshots from your configuration (hide your API Key)?

**Comment by CarlosUceira** [comment]
Hi, thanks for the quick reply. Please find below my magento setup.

![image](https://user-images.githubusercontent.com/31443259/29825511-f34248be-8cd4-11e7-9c3d-c71d6420c370.png)

Regards!

**Comment by VivaWalletSupport** [comment]
You should use the OrderCode and Gateway URL for the demo environment,now you are using the ones for the live environment.

**Comment by CarlosUceira** [comment]
And how do i find them? Can you help me? I have already created a sandbox account. 

Thanks!

**Comment by VivaWalletSupport** [comment]
http://demo.vivapayments.com/api/orders
http://demo.vivapayments.com/web/newtransaction.aspx

**Comment by CarlosUceira** [comment]
Ok, now work!! Thanks. I just need to set up the confirmation url :)

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
