### ISSUE TITLE
Εμφάνιση μονο του Viva Wallet

### ISSUE THREAD

**Issue by dlgcom** [VivaPayments/API#373]
Καλησπέρα σας.
Θέλω να ρωτήσω πως μπορώ στις επιλογές, που εμφανίζονται στον πελάτη για πληρωμή μεσα απο το e-shop μου (Κάρτα ή Viva Wallet) να εμφανίζεται ΜΟΝΟ η επιλογή Viva Wallet.

![vivawallet](https://user-images.githubusercontent.com/31478541/29875169-b91dbba0-8da1-11e7-87d7-9aaf9393938c.jpg)

**Comment by VivaWalletSupport** [comment]
Hello, have a look at the additional parameters that can be passed (DisableCard) https://github.com/VivaPayments/API/wiki/Optional-Parameters

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
