### ISSUE TITLE
Module Payment Problems

### ISSUE THREAD

**Issue by matinaKal** [VivaPayments/API#374]
Καλησπέρα,
 χρησιμοποιήσαμε το plugin σας για τη χρήση VivaWallet σε ένα Prestashop 1.6 e-shop και ενώ κάναμε όλα τα απαιτούμενα βήματα (δημιουργία Πηγής Πληρωμών η οποία **εγκρίθηκε**) δε γίνεται η πληρωμή.

**Περιγραφή Προβλήματος:**
Στη σελίδα πληρωμών επιλέγουμε Πληρωμή με VIvawallet και ανακατευθυνόμαστε στο περιβάλλον της Vivawallet όπου και συμπληρώνουμε τα στοιχεία της κάρτας. Όταν επιλέγουμε "Χρεώση" ανακατευθυνόμαστε πίσω με μήνυμα : 
![3](https://user-images.githubusercontent.com/31504727/29915309-1f340226-8e44-11e7-9e2b-5397dba7c8a7.png)

Δοκιμάσαμε και "GET /api/transactions/?date=2017-08-30" και τα αποτελέσματα ήταν **μόνο** οι επιτυχημένες πληρωμές στην **άλλη (παλαιότερη) καταχωρημένη πηγή πληρωμών** και κανένα ίχνος απο τις προσπάθειες που κάναμε.

Τι πρέπει να κάνουμε;
Ευχαριστώ,
Ματίνα

**Comment by VivaWalletSupport** [comment]
Please check if the correct payment source code is used in the module and if the correct return URLs are specified in the payment source.

**Comment by matinaKal** [comment]
Ξανακοίταξα τα urls:
![download](https://user-images.githubusercontent.com/31504727/30021315-a3cf721c-916f-11e7-8e04-7cec2a10940d.png)
και είναι **σωστά** και σύμφωνα με τις οδηγίες του plugin. Κοίταξα και το source code και είναι επίσης σωστό.

**Το url που με επιστρέφει όταν πατάω 'Χρέωση' είναι αυτό:** " /order-confirmation?id_cart=45&id_module=104&id_order=24&key=736468f72f3a6ebb9e823504b39313f9".
και με βγάζει στη σελίδα που επισύναψα στο αρχικό μου σχόλιο.

**Comment by VivaWalletSupport** [comment]
Please download and install the latest version from https://github.com/VivaPayments/API/tree/master/Plugins/prestashop/vivawallet

If the problem remains, post some screenshots from your module and pay source settings (hide the API key).

**Comment by matinaKal** [comment]
So, I uninstalled and deleted the previous plugin and I downloaded again the new one. The result is the same. Step by step:

**1. Viva wallet Account Settings** 
The "Payment Source" settings are:
![fireshot capture 200 - - https___members vivawallet com_selfcare_el-gr_sources_paymentsources](https://user-images.githubusercontent.com/31504727/30102729-2d311904-92f9-11e7-8c1f-58dfb46a7620.png)

**2. Prestashop Module Settings**
![download](https://user-images.githubusercontent.com/31504727/30102831-7fac9dd4-92f9-11e7-874a-0a895b104268.png)

**3. Payment Page**
I select a product and I choose to pay via Viva wallet. Then, the site redirects me here:
![2](https://user-images.githubusercontent.com/31504727/30103022-164956ce-92fa-11e7-875b-b0d71a5268c8.png)

**4. Database vivawallet_data (1)**
So, before I hit the "Pay" button I check vivawallet_data table  (order_state=I):
![download 1](https://user-images.githubusercontent.com/31504727/30103123-62763a9e-92fa-11e7-9bdc-642d2b219be0.png)

**5. Something went wrong...**
So I get redirected to this page again:
![29915309-1f340226-8e44-11e7-9e2b-5397dba7c8a7](https://user-images.githubusercontent.com/31504727/30103176-875b8e36-92fa-11e7-91b2-9a22e795860f.png)

**6. Database vivawallet_data (2) (order_state=F)**
The vivawallet_data table now shows this:
![download 2](https://user-images.githubusercontent.com/31504727/30103288-d3690808-92fa-11e7-8295-ae9d747f3f6a.png)

**7.Postman check**
When I check with postman the day's payments the is **no** sign of the failed transaction.

**7. fail.php**
I checked fail.php and I found this line:
 **$update_query = "update vivawallet_data set order_state='F' where OrderCode='".$OrderCode."'";**
which means that after the 'Buy' button is clicked we get into fail.php which changes order_state in DB.
So, the error is in transaction, right?

**Comment by VivaWalletSupport** [comment]
Either test in the demo mode or use a bigger amount in live mode (2-5 euro for example).

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
