### ISSUE TITLE
Success.php "Notice: Undefined variable" on prestashop  plug in

### ISSUE THREAD

**Issue by samator79** [VivaPayments/API#376]
`Notice: Undefined variable: emp_currency in /home/admin/web/tsarouhis.gr/public_html/modules/vivawallet/success.php on line 20

Notice: Undefined variable: cart_id in /home/admin/web/tsarouhis.gr/public_html/modules/vivawallet/success.php on line 26`

This is the error than apear later to make the payment in viva wallet
I research in the variable cart_id, and i think a typing error (this is the real variable cartid)
You correct me if I am not right

But the othe variable, i dont know from where is or have other typing error.

You can help to fix that.

This is the lines on the file:
 
`line 20: $currency_payment = Db::getInstance()->getValue('SELECT id_currency FROM '._DB_PREFIX_.'currency WHERE iso_code="'.$emp_currency.'"');

lin 26: Context::getContext()->cart = new Cart((int)$cartid);`

Thank you for your reply and help

**Comment by VivaWalletSupport** [comment]
Thank you, will fix the code to:

`line 20: $currency_payment = Db::getInstance()->getValue('SELECT id_currency FROM '.DB_PREFIX.'currency WHERE iso_code="EUR"');

lin 26: Context::getContext()->cart = new Cart((int)$cartid);`

**Comment by samator79** [comment]
The right line is: 
`$currency_payment = Db::getInstance()->getValue('SELECT id_currency FROM '._DB_PREFIX_.'currency WHERE iso_code = "EUR"');`

But now i have other problem:

`Array
(
    [0] => Array
        (
            [file] => /home/admin/web/tsarouhis.gr/public_html/classes/PaymentModule.php
            [line] => 202
            [function] => displayError
            [class] => ToolsCore
            [type] => ::
            [args] => Array
                (
                )

        )

    [1] => Array
        (
            [file] => /home/admin/web/tsarouhis.gr/public_html/modules/vivawallet/success.php
            [line] => 38
            [function] => validateOrder
            [class] => PaymentModuleCore
            [object] => vivawallet Object
                (
                    [_html:vivawallet:private] => 
                    [_postErrors:vivawallet:private] => Array
...`
Me da como resultado despues de la pagina de pagos, una pagina completa de codigo, como te muestro con anterioridad, pero no me devulve a mi pagina con un pago exitoso y no aparece la orden en mi prestashop.

Que debo hacer?
Could you explain the next step?

Thank you very much

**Comment by VivaWalletSupport** [comment]
The FrontController checks if an order has already been placed with the cart number as it returns to prestashop. The cart number is still the same because (upon return) no new cart number has been set yet. And therefore, it places a log entry saying the current cart is already related to an order in the database. This will be fixed in a next version, without debug mode the customer should not notice anything until then.

**Comment by samator79** [comment]
this means that the module finally does not work, and I have to get another or what would be the steps that I would have to do to have a successful response to my prestashop, and thus finish an order?

**Comment by VivaWalletSupport** [comment]
No, the module should work just fine when you disable the debug mode.

**Comment by samator79** [comment]
Where i can disable the debug mode?
In the prestashop or in the php.in or where?

Thank you for your reply

**Comment by VivaWalletSupport** [comment]
In the shop advanced/performance and in php.ini display_errors

**Comment by VivaWalletSupport** [comment]
In success.php and fail.php change:
	if(substr(_PS_VERSION_,2,1) >= 5){
	Context::getContext()->cart = new Cart((int)$cartid);
	Context::getContext()->customer = new Customer((int)Context::getContext()->cart->id_customer);
	$address = new Address((int)Context::getContext()->cart->id_address_invoice);
	Context::getContext()->country = new Country((int)$address->id_country);
	$secure_key = $customer->secure_key;
	}
To:
if(substr(_PS_VERSION_,2,1) >= 5){
	Context::getContext()->cart = new Cart((int)$cartid);
	Context::getContext()->customer = new Customer((int)Context::getContext()->cart->id_customer);
	$address = new Address((int)Context::getContext()->cart->id_address_invoice);
	Context::getContext()->country = new Country((int)$address->id_country);
	$secure_key = $customer->secure_key;
		if ((int)Context::getContext()->cookie->id_cart > 0) 
		{
			Context::getContext()->cookie->__unset('id_cart');
		}
	}

And the notice should not be triggered anymore.

**Comment by samator79** [comment]
I have done everything you say but I still receive a screen like this:
`Array
(
[0] => Array
(
[file] => /home/admin/web/tsarouhis.gr/public_html/classes/PaymentModule.php
[line] => 202
[function] => displayError
[class] => ToolsCore
[type] => ::
[args] => Array`

is a very long page with a lot of payment information.

But the response was not received so that the prestashop creates the order and tells me that this one pays.

Sorry but we want to know if this module is operational or not because otherwise we do not have time for this whole situation.

Thanks for your quick response

**Comment by VivaWalletSupport** [comment]
The module is operational and has been tested with the latest version of Prestashop.

**Comment by samator79** [comment]
With debug mode enabled, I get the blank screen with this message "Fatal error"

I would like to know what can be done in this case.

**Comment by VivaWalletSupport** [comment]
Check your prestahop error log for the specifics of the error.

**Comment by samator79** [comment]
This module for me don't work and you like support, don't give me a good answers to fix the problem.

You give free support or we need to pay for the support.

Thank for you reply

**Comment by VivaWalletSupport** [comment]
I asked you before to see what specific error has been logged in your prestashop error log...

**Comment by samator79** [comment]
6659 | -- | 3 | PaymentModule::validateOrder - Secure key does not match | Cart | 93 | 0x	0 | 04/09/2017 14:38:42
This is the error that i can to see in prestashop log.

Thank you for yout help.

**Comment by VivaWalletSupport** [comment]
Is there any secure_key recorded in the vivawallet_data table for the specific transaction?

**Comment by samator79** [comment]
All the transactions we have performed have the same result, but we have not placed any specific security key in the table.
We see that the problem is internal in the module.
That is the error we have, that can help us to correct it
Thank you

**Comment by VivaWalletSupport** [comment]
Could you post a screenshot of the vivawallet_data table?

**Comment by samator79** [comment]
![image001](https://user-images.githubusercontent.com/31441644/30152853-358fc234-93bd-11e7-925d-b704f3cc0a44.jpg)
![image002](https://user-images.githubusercontent.com/31441644/30152854-3595cb8e-93bd-11e7-81ea-95ec4061dafe.jpg)

It is normal that all the other table have the security prefix and only the vivawallet_data table dont have this prefix like the first image.

Thank you for your help

**Comment by VivaWalletSupport** [comment]
The missing secure prefix is normal as it is not a default Prestashop table, I see that the secure key is stored but ordercode, errorcode and errortext are empty. This means that you have a connection problem (wrong credentials, PHP cURL problem).

**Comment by samator79** [comment]
How i can fix this problem?

**Comment by samator79** [comment]
![corel001](https://user-images.githubusercontent.com/31441644/30154736-7d73d134-93c3-11e7-8226-6f93c3ac5202.jpg)

The curl funtion are enebled and work good, it is tested

**Comment by samator79** [comment]
![corel002](https://user-images.githubusercontent.com/31441644/30155707-31e43116-93c6-11e7-9efa-e1c247972d72.jpg)
This the last page in the vivawallet table, the prev menssage are the first page.
I think in the last page are the last test,  the last page have the other code you said.

Thank for your reply

**Comment by VivaWalletSupport** [comment]
Drop me an email at hellasboost.gr to see if I can debug the problem you are having.

**Comment by samator79** [comment]
I sent a email yesterday to vivawallet@hellasboost.gr, but you dont give me the real email, my email is samator79@yahoo.es.

Thank for your reply.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
