### ISSUE TITLE
GetTransactions call

### ISSUE THREAD

**Issue by VagKolokotronis** [VivaPayments/API#38]
Γεια σας
Θα ήθελα να με πληροφορήσετε για τα παρακάτω 
Έχω δημιουργήσει την γέφυρα πληρωμής bankvivaform.asp η οποία στέλνει τα στοιχεία στην σελίδα πληρωμής του συστήματος σας. 
Η μέθοδος είναι Redirect Checkout και o προγραμματισμός σε γλώσσα asp
Η δημιουργία Creation of the Payment Order είναι σωστή χωρίς προβλήματα 

Το πρόβλημα που έχω είναι στην σελίδα επιστροφής επιτυχής συναλλαγής  (http://www.euroalarm.2easy.gr/bp/bankViva_ok.asp )

Τα στοιχεία επιστροφής μιας επιτυχής συναλλαγής είναι 

http://www.euroalarm.2easy.gr/bp/bankViva_ok.asp?t=39a3eea8-d1c4-41e0-b7a5-bb9c617840f5&s=7531882921572608&lang=el-GR

Σύμφωνα με τις οδηγίες σας συνιστάτε να κάνουμε και μια ερώτηση επιβεβαίωσης της συναλλαγής σύμφωνα (You can make a GetTransactions call to verify the status of an Order. )

Παίρνω τα στοιχεία επιστροφής παρακάτω 

                OrderCode = request.querystring("s")
                strTransactionID = request.querystring("t")
                strLang = request.querystring("Lang") 

ordercode=7531882921572608 strTransactionID=39a3eea8-d1c4-41e0-b7a5-bb9c617840f5 

Τα στοιχεία MerchanID APIkey και url είναι 

MerchanID=f9f3f5f4-f222-48c9-be5a-ea6ae727e88a 
APIkey=;d]z7: 
url=http://demo.vivapayments.com/api/transactions/?

GetTransactions call

strVivaUrlGetTransaction = "http://demo.vivapayments.com/api/transactions/?"
strMerchanID = f9f3f5f4-f222-48c9-be5a-ea6ae727e88a
strAPIKey = =;d]z7:

Set http = Server.CreateObject("Msxml2.ServerXMLHTTP.3.0")
http.open "GET", strVivaUrlGetTransaction, False', strMerchanID, strAPIKey ' 
http.setRequestHeader "Content-Type", "application/x-www-form-urlencoded"
http.setRequestHeader "Authorization", "Basic "&Base64Encode(strMerchanID&":"&strAPIKey)

http.send("ordercode=" & OrderCode )

response.write http.responsetext

η απάντηση που παίρνω είναι 
{"Transactions":[],"ErrorCode":400,"ErrorText":"Empty options","TimeStamp":"2016-02-09T09:54:33.0584711+02:00"}

1)Παρακαλώ ενημερώστε μου που είναι το λάθος η το πρόβλημα. 
Είναι λάθος η διεύθυνση strVivaUrlGetTransaction ? η κάτι άλλο. 
Όσο και να έψαξα στα παράδειγματα σας δεν βρήκα πουθενά παραδείγματα χρήσης των εντολών  GetTransactions (https://github.com/VivaPayments/API/wiki/GetTransactions )

2) Πότε ενεργοποιείτε η σελίδα μη επιτυχής συναλλαγής ? Πότε επιστρέφει το σύστημα σας σε αυτή την σελίδα ? 
Στην σελίδα πληρωμής δεν υπάρχει κάποιο κουμπί ακύρωσης της διαδικασίας πληρωμής. Ο μόνος τρόπος είναι να κλείσει κάποιος την σελίδα ή από το κουμπί επιστροφής στην προηγούμενη σελίδας ( πίσω δηλαδή ), αλλά σε καμία από αυτές τις περίπτωσης δεν  ενεργοποιείτε η σελίδα επιστροφής μη επιτυχής συναλλαγής 

Σας ευχαριστώ για τον χρόνο σας 
Περιμένω τις οδηγίες σας 

Με εκτίμηση
Βαγγέλης Κολοκοτρώνης

**Comment by dpnevmatikos** [comment]
Καλησπέρα σας,
Θα μπορούσατε να κάνετε ένα ```reponse.write``` στο τελικό url που δημιουργείτε στον κώδικα σας και να μας το στείλετε ?

Στη σελίδα αποτυχίας οδηγείται ο χρήστης εάν αποτύχει η διαδικασία της πληρωμής. Δεν μπορεί να οδηγηθεί εκεί με άλλο τρόπο.

**Comment by VagKolokotronis** [comment]
Καλησπέρα σας 
Η απάντηση που παίρνω είναι ( σας την έχω στείλει στο προηγούμενο post μου )

{"Transactions":[],"ErrorCode":400,"ErrorText":"Empty options","TimeStamp":"2016-02-09T09:54:33.0584711+02:00"}

Μπορείτε να το δοκιμάσετε live 
http://www.euroalarm.2easy.gr/bp/bankViva_ok.asp?t=39a3eea8-d1c4-41e0-b7a5-bb9c617840f5&s=7531882921572608&lang=el-GR 

Κάνω επίσης response.write τα 
response.write "ordercode=" & ordercode & " strTransactionID=" & strTransactionID & " MerchanID=" & strMerchanID &" APIkey=" & strAPIKey & " url=" & strVivaUrlGetTransaction &"<br>"

2) Τι εννοείται με αποτυχία στην διαδικασία της πληρωμής ? Πότε μπορεί να συμβεί αυτό ? Όταν ο πελάτης βάλει λάθος στοιχεία κάρτας ή εάν βάλει σωστά στοιχεία κάρτας άλλα δεν υπάρχουν χρήματα στην κάρτα. Εάν ο πελάτης θέλει να διακόψει την διαδικασία πληρωμής τι πρέπει να κάνει ? πως θα φύγει από την σελίδα πληρωμής ? Όλα τα συστήματα πληρωμής έχουν επιλογή Ακύρωσης της διαδικασίας πληρωμής. 

Ευχαριστώ

**Comment by dpnevmatikos** [comment]
Καλησπέρα και πάλι,
Παρακαλώ δοκιμάστε να κάνετε ένα HTTP GET στο ```http://demo.vivapayments.com/api/transactions/?ordercode=7531882921572608``` αν θέλετε να πάρετε πληροφορίες για τα transactions που σχετίζονται με αυτό το order code (χρησιμοποιήστε και τα credentials που έχετε). Δοκιμάσαμε να κάνουμε μια κλήση GET με τη χρήση του [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop) και τα δικά σας credentials και πήραμε κανονικά απάντηση. 

Αποτυχία στη διαδικασία της πληρωμής έχουμε όταν για παράδειγμα ο πελάτης βάζει τα στοιχεία της κάρτας του και αυτή απορρίπτεται από το σύστημα μας (είτε γιατί δεν έχει υπόλοιπο είτε για οποιονδήποτε άλλο λόγο).
Ο πελάτης **μπορεί να διακόψει τη διαδικασία της πληρωμής μόνο εάν φύγει από τη σελίδα πληρωμής** (πατώντας για παράδειγμα Back). 

Σε περίπτωση που η πληρωμή με Redirect δε σας βολεύει, θα μπορούσατε να δοκιμάσετε την [πληρωμή με Viva Wallet](http://www.vivawallet.com/en-us/business/pay-with-vivawallet). Στην ουσία πρόκειται για μια **σελίδα πληρωμής μέσα στο δικό σας web site**. O χρήστης βάζει τα στοιχεία της κάρτας του μέσα σε ένα popup που εμφανίζεται εντός του site σας χωρίς να γίνεται redirect σε άλλο url, ενώ αν θέλει να διακόψει τη διαδικασία της πληρωμής απλά κλείνει το popup της πληρωμής.
Περισσότερα σχετικά με το integration δείτε [εδώ](https://github.com/VivaPayments/API/wiki/Pay-with-Viva-Wallet).

**Comment by VagKolokotronis** [comment]
Καλησπέρα και πάλι 
το http://demo.vivapayments.com/api/transactions/?ordercode=7531882921572608 που μου στείλατε να δοκιμάσω βγάζει ακριβώς το ίδιο λάθος 

{"Transactions":[],"ErrorCode":401,"ErrorText":null,"TimeStamp":"2016-02-09T20:34:40.376052+02:00"}

Στην απάντηση σας "Ο πελάτης μπορεί να διακόψει τη διαδικασία της πληρωμής μόνο εάν φύγει από τη σελίδα πληρωμής (πατώντας για παράδειγμα Back). Αυτό σημαίνει ότι γυρίζει πίσω στην εφαρμογή eshop στην τελευταία σελίδα του eshop από όπου ξεκίνησε. Θεωρό ότι αυτό δεν είναι και ιδιαίτερα κομψό. Θα μπορούσατε να βάλετε ένα κουμπί Ακύρωση της πληρωμής και να επιστρέφει στην σελίδα αποτυχίας έτσι ώστε να μπορούμε να διαχειριστούμε σωστά και αυτήν την περίπτωση.  

Δεν είναι το θέμα εάν η πληρωμή Redirect με βολεύει η όχι Αυτή την στιγμή προσπαθούμε να βρούμε που είναι το πρόβλημα στην διαδικασία GetTransactions call και γιατί παίρνω λάθος επιστροφή και με το δικό σας GET http://demo.vivapayments.com/api/transactions/?ordercode=7531882921572608 

Επισυνάπτω πάλι τους κωδικούς για την κλήση Get σε κώδικα asp. Εάν υπάρχει κάποιο λάθος σε αυτό παρακαλώ ενημερώστε με σε αυτό Εάν δεν γνωρίζετε τότε πάλι ενημερώστε με ότι δεν γνωρίζετε. Θεωρώ ότι είστε το τεχνικό τμήμα για να έχετε προτάσεις και λύσεις σε προβλήματα τεχνικά και προγραμματισμού.  

OrderCode = request.querystring("s")
strTransactionID = request.querystring("t")
strLang = request.querystring("Lang") 

strVivaUrlGetTransaction = "http://demo.vivapayments.com/api/transactions/?"
strMerchanID = "f9f3f5f4-f222-48c9-be5a-ea6ae727e88a"
strAPIKey = "=;d]z7:"

Set http = Server.CreateObject("Msxml2.ServerXMLHTTP.3.0")
http.open "GET", strVivaUrlGetTransaction, False', strMerchanID, strAPIKey ' 
http.setRequestHeader "Content-Type", "application/x-www-form-urlencoded"
http.setRequestHeader "Authorization", "Basic "&Base64Encode(strMerchanID&":"&strAPIKey)
http.send("ordercode=" & OrderCode )
response.write http.responsetext

Η επιλογή με πληρωμή με Viva Wallet διάβασα κάπου ότι δεν υποστηρίζει πληρωμές από κάρτες αλλά μόνο την επιλογή πληρωμή με Viva Wallet. Δεν χρειάζεται αυτή η επιλογή την διαδικασία επιβεβαίωσης της αγοράς με την διαδικασία GetTransactions call ?

Σας ευχαριστώ για την απάντηση σας

**Comment by dpnevmatikos** [comment]
Καλησπέρα σας,


> το http://demo.vivapayments.com/api/transactions/?ordercode=7531882921572608 που μου στείλατε να δοκιμάσω βγάζει ακριβώς το ίδιο λάθος
> 
> {"Transactions":[],"ErrorCode":401,"ErrorText":null,"TimeStamp":"2016-02-09T20:34:40.376052+02:00"}

όπως μπορεί να παρατηρήσατε, το error code που γυρνάει το GET δεν είναι το ίδιο (είναι 401 και όχι 400 που ήταν στο αρχικό μήνυμα σας). Το [401](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error) προκύπτει επειδή βάζετε λάθος κωδικό στη μεταβλητή σας ```strApiKey```.
Επισυνάπτω screenshot όπου φαίνεται καθαρά οτι αν τα στοιχεία τεθούν σωστά η κλήση γυρνάει κανονικά αποτέλεσμα:
<img width="922" alt="screen shot 2016-02-09 at 21 35 23" src="https://cloud.githubusercontent.com/assets/1810462/12928423/059a9bc4-cf76-11e5-9678-cea034fd334f.png">

Δυστυχώς περαιτέρω debug στον κώδικα σας, δεν μπορούμε να κάνουμε.
 

> Η επιλογή με πληρωμή με Viva Wallet διάβασα κάπου ότι δεν υποστηρίζει πληρωμές από κάρτες αλλά μόνο την επιλογή πληρωμή με Viva Wallet.

Η πληρωμή με Viva Wallet μπορεί να χρεώσει και κάρτες. O λόγος που σας την ανέφερα σαν διαδικασία πληρωμής είναι κυριώς γιατί ψάχνετε ένα τρόπο για να ακυρώσει ο χρήστης την πληρωμή άμα θέλει, πράγμα το οποίο είναι δυνατό να συμβεί μόνο με τους τρόπους τους οποίους σας περιέγραψα πιο πάνω.

Ευχαριστώ.

**Comment by VagKolokotronis** [comment]
Καλημέρα 
1) Ερώτηση 
Για κάθε μια επιτυχημένη πληρωμή το σύστημα σας επιστρέφει στην σελίδα που έχουμε δηλώσει ( σελίδα επιτυχημένης συναλλαγής ) . Υπάρχει κάποια περίπτωση που το σύστημα σας επιστρέφει στην σελίδα επιτυχημένης συναλλαγής χωρίς η συναλλαγή να είναι επιτυχημένη = έχει γίνει η χρέωση ?

Όσο αφορά την επιλογή Ακύρωσης της πληρωμής είναι μια πρόταση που θα μπορούσε να κάνει το σύστημα σας ποιο φιλικό και σωστό. Θα μπορούσατε να το προωθήσετε σαν ιδέα στο αντίστοιχο τμήμα που ασχολείται με την υλοποίησης του συστήματος σας.
 
2) 
1)	Η απάντηση λάθους ErrorCode":400, μπορείτε να μου πείτε τι σημαίνει ?
2)	Έχετε κάποια παράδειγμα κλήσης GetTransactions call σε κάποια γλώσσα προγραμματισμού ? Θα με βοηθούσατε εάν είχατε ένα παράδειγμα σε γλώσσα classic asp. Στο github δεν υπάρχουν παραδείγματα GetTransactions  η τουλάχιστον εγώ δεν έχω βρει κάτι. 

Σας επισυνάπτω τον κώδικα της σελίδας επιτυχημένης πληρωμής /bp/bankViva_ok.asp

Και όπως έρχεται από το σύστημα σας η επιστροφή στην σελίδα επιτυχημένης πληρωμής 

http://www.euroalarm.2easy.gr/bp/bankViva_ok.asp?t=87b27951-12f5-4253-bdff-4e43ee7b9bf3&s=8243103019172607&lang=el-GR

bankViva_ok.asp




<%if sxNobody then%>
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body></body></html>
<%end if
openConn

function NzInt(int)
	NzInt = int
	if isNull(int) OR isEmpty(int) OR lenb(int) = 0 OR Not isNumeric(int) then
		NzInt = 0
	end if
end function

Dim radioContinue
	radioContinue = True
Dim radioVivaReturn 
	radioVivaReturn = True

	Dim OrderCode, strTransactionID, strLang 
	OrderCode = request.querystring("s")
	strTransactionID = request.querystring("t")
	strLang = request.querystring("Lang")
	
	if OrderCode = "" then radioVivaReturn = False
	
if radioVivaReturn then
	if radioContinue then
		sql = "SELECT * FROM PB_Viva WHERE InUse = True "
		set rs = conn.execute(sql)
			if not rs.eof then
			strMerchanID = rs("MerchanID")
			strAPIKey = rs("APIKey")
			strPublicKey = rs("PublicKey")		
			strVivaUrltTansaction = rs("VivaUrlTransaction")
			strVivaUrlGetTransaction = rs("VivaUrlGetTransaction")
			radioContinue = True
		else
			radioContinue = False
		end if
		rs.close
		set rs = nothing
	end if

	if radioContinue then
		Set http = Server.CreateObject("Msxml2.ServerXMLHTTP.3.0")
		http.open "GET", strVivaUrlGetTransaction, False', strMerchanID, strAPIKey 
		http.setRequestHeader "Content-Type", "application/x-www-form-urlencoded"
		http.setRequestHeader "Authorization", "Basic "&Base64Encode(strMerchanID&":"&strAPIKey)
		response.write "ordercode=" & ordercode & " strTransactionID=" & strTransactionID & " MerchanID=" & strMerchanID &" APIkey=" & strAPIKey & " url=" & strVivaUrlGetTransaction &"<br>"
		http.send("ordercode=" & OrderCode )
		

response.write http.responsetext
Response.End

end if
%>

και η απάντηση που παίρνω είναι 
α) τα στοιχεία που χρησιμοποιώ είναι τα παρακάτω για την κλήση 

response.write "ordercode=" & ordercode & " strTransactionID=" & strTransactionID & " MerchanID=" & strMerchanID &" APIkey=" & strAPIKey & " url=" & strVivaUrlGetTransaction &"<br>"

ordercode=8243103019172607 
strTransactionID=87b27951-12f5-4253-bdff-4e43ee7b9bf3 MerchanID=f9f3f5f4-f222-48c9-be5a-ea6ae727e88a 
APIkey=;d]z7: 
url=http://demo.vivapayments.com/api/transactions/?

response.write http.responsetext

{"Transactions":[],"ErrorCode":400,"ErrorText":"Empty options","TimeStamp":"2016-02-10T10:49:03.228726+02:00"}

Αυτό που υποψιάζομαι ότι είναι το λάθος είναι ότι η τιμή που στέλνετε στο σύστημα σας με την εντολή http.send("ordercode=" & OrderCode ) Το OrderCode έρχεται σαν sting και φυσικά στέλνετε σαν sting ενώ εσείς το εξετάζετε σαν Int64. H μετατροπή του με την εντολή CDbl OrderCode = CDbl(OrderCode) το αλλάζει από 8243103019172607 σε  8.24310301917261E+15 η εντολή OrderCode = Cint(OrderCode) κάνει Overflow: 'cInt'  Δεν έχω βρει τρόπο να μετατρέψω το string σε int64 μήπως ξέρετε εσείς κάποιο τρόπο ? 

Πραγματικά δουλεύει η επιλογή GetTransactions call στο σύστημα σας ? Είναι κάποια εφαρμογή που την χρησιμοποιεί ? 

Εάν δεν μπορείτε να με πληροφορήσετε εσείς ίσως υπάρχει κάποιος άλλος στο τεχνικό τμήμα που ίσως θα μπορούσε ? ή μήπως θα πρέπει να απευθυνθώ στον υπεύθυνο του τεχνικού τμήματος της vivawallet.

Ευχαριστώ
