### ISSUE TITLE
Πληρωμές με american express

### ISSUE THREAD

**Issue by IakovosR** [VivaPayments/API#380]
Καλησπέρα σας,

Τελευταία αντιμετωπίζουμε αρκετά θέματα απο πελάτες που προσπαθούν να πληρώσουν με κάρτες American Express.

Απ' ότι είδα στις ρυθμίσεις του λογαριασμού είναι ενεργοποιημένη η πληρωμή με American Express. Υπάρχει κάτι άλλο που θα πρέπει να κάνουμε έτσι ώστε να δεχόμαστε πληρωμές τέτοιου είδους? Είναι τυχαία τα γεγονότα? Πρέπει να κάνουμε κάτι άλλο?

**Comment by dmihos** [comment]
Καλησπέρα σας
Στείλτε, αν θέλετε, ένα email στο merchants@vivawallet.com με τα στοιχεία του λογαριασμού σας, ώστε να γίνει ο σχετικός έλεγχος.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
