### ISSUE TITLE
ΑΝΑΒΑΘΜΙΣΗ ΠΛΑΤΦΟΡΜΑΣ

### ISSUE THREAD

**Issue by Imagecopy** [VivaPayments/API#381]
Στο eshop που έχω, έκανα αναβάθμιση πλατφόρμας από Opencart 1.5 σε 2X θέλω να ρωτήσω πως θα περάσω τα στοιχεία της viva και έτσι να μπορέσω να απενεργοποιήσω την παλιά πλατφόρμα;

**Comment by VivaWalletSupport** [comment]
You would have to update your payment source in Viva.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
