### ISSUE TITLE
Πρόβλημα διασύνδεσης με shopify e-shop

### ISSUE THREAD

**Issue by kostasgkou** [VivaPayments/API#382]
Μετά από 3 μήνες ακόμα δεν έχετε καταφέρει να φτιάξετε το πρόβλημα που υπάρχει και φταίτε αποκλειστικά. Γιατί έχουμε ελέγξει μέσω της shopify και δεν έχουμε κάποιο πρόβλημα εμείς. Έχουν σηκώσει τα χέρια ψηλά δύο προγραμματιστές . Στον τελευταίο είπατε ότι θα το από την αρχή μέχρι το Σαββατοκύριακο που πέρασε και πάλι τίποτα δεν έγινε . Σήμερα προσπάθησα να το φτιάξω εγώ πάλι από την αρχή. Είναι τόσο δύσκολο να το φτιάξετε? Παρακαλώ για ύστατη φορά να το φτιάξετε χάνω πωλήσεις.

**Comment by kostGX** [comment]
Καλησπέρα @kostasgkou έχετε κοιτάξει αυτό τον οδηγό; 

https://github.com/VivaPayments/API/wiki/Shopify-Integration

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
