### ISSUE TITLE
Intergration with magento - 404 after success payment.

### ISSUE THREAD

**Issue by ethelserth** [VivaPayments/API#383]
Hello,
We are using your extension, for intertgration with our magento store. We switched in your extension after using HellasPay extension for several years. If i understand this correctly, it is the same extension, but the original one had some files, encoded.

Our issue, is that when a customer complete a viva payment and the procedure completes, the system redirects him on a 404 page. The page is ../onepage/success/hellaspay/hpok/hpay instead of ../onepage/success/vivapayments/hpok/hpay. It uses the old's module namespaces and method for some reason, and on this specific occassion only.

Does the return url change from viva wallet admin panel? Or is it some weird case issue? Thoughts?

**Comment by VivaWalletSupport** [comment]
Hello, you would have to change the URLs in your Viva payment source.

**Comment by ethelserth** [comment]
You mean my viva payment admin panel, on viva website?

**Comment by VivaWalletSupport** [comment]
At https://members.vivawallet.com/selfcare/en-us/sources/paymentsources

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.

**Comment by KostasTimpas** [comment]
Hello I have the same Issue,

my links on Viva payment source are:
index.php/hellaspay/hpay/hpok/
index.php/hellaspay/hpay/hpnok/

By what I have to replace to Redirecto to Success or Failure page?

**Comment by VivaWalletSupport** [comment]
Hello Kostas, in case you use following plugin https://github.com/VivaPayments/API/tree/master/Plugins/magento/magvivawallet see the documentations on how the URLs should be constructed.
