### ISSUE TITLE
viva payments to opencart 2.3

### ISSUE THREAD

**Issue by Imagecopy** [VivaPayments/API#384]
I updated my eshop from opencart 1.5 to opencart 2.3 and I don't know how I can apply vivapayments.

**Comment by VivaWalletSupport** [comment]
A plugin is available from here: https://github.com/VivaPayments/API/tree/master/Plugins/opencart/Opencart%202.3

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
