### ISSUE TITLE
Χρήση κουμπιού της VIVA WALLET για πληρωμή

### ISSUE THREAD

**Issue by codnext** [VivaPayments/API#387]
Έχω δημιουργήσει έναν λογαριασμό demo για να δοκιμάσω τις πληρωμές με την viva wallet σε ιστοσελίδα.
Δημιουργώ το κουμπί και κάνω επικόληση τον κώδικα που δημιουργείται μέσα στο site.
Όταν πατάω το κουμπί παίρνω το παρακάτω error:
403 - Forbidden: Access is denied.
You do not have permission to view this directory or page using the credentials that you supplied.

Θα προτιμούσα να χρησιμοποιήσω τη μέθοδο Pay-with-Viva-Wallet όπως αναλύεται στον παρακάτω σύνδεσμο.
https://github.com/VivaPayments/API/wiki/Pay-with-Viva-Wallet

Στο βήμα 1 έχει data-vp-baseurl="https://demo.vivapayments.com" ; 
Με επικόληση του βήματος 1 στην ιστοσελίδα μου και πατώντας το κουμπί παίρνω το ίδιο error με παραπάνω.  

Πρέπει να κάνω verify τον λογαριασμό μου ακόμα και αν είναι demo? Δεν το έχω κάνει...

**Comment by dpnevmatikos** [comment]
Καλησπέρα, 
θα πρέπει να χρησιμοποιήσετε το Public κλειδί του εμπόρου που έχετε στο demo, στην παράμετρο
```data-vp-publickey="{το δικό σας κλειδί}"```.

Το κλειδί αυτό το βρίσκετε στο http://demo.vivapayments.com/selfcare/el-gr/security/apiaccess

<img width="907" alt="screen shot 2017-09-19 at 19 50 58" src="https://user-images.githubusercontent.com/1810462/30604632-3d8d5198-9d74-11e7-9e31-96bde63b7548.png">

**Comment by codnext** [comment]
Καλησπέρα, 
ευχαριστώ για την απάντηση. Για τις πληρωμές σε production πρέπει να αντικαταστήσουμε το data-vp-baseurl="https://demo.vivapayments.com" με url του site που θα καλεί την μέθοδο για την πληρωμή; Δηλαδή πρέπει να υλοποιήσουμε το βήμα 2 του tutorial https://github.com/VivaPayments/API/wiki/Pay-with-Viva-Wallet ;

**Comment by dpnevmatikos** [comment]
Για πληρωμή σε production θα πρέπει να κάνετε τα εξής  : 
1) να αντικαταστήσετε το ```data-vp-baseurl``` σε αυτό της παραγωγής https://www.vivapayments.com
2) Να αντικαταστήσετε το Public Κλεδί σας με αυτό της παραγωγής, κάνοντας login [εδώ](https://www.vivapayments.com/el-gr/signin)
3) να δημιουργήσετε ενα url δικό σας που θα σταλούν τα δεδομένα της φόρμας, μέσα στην οποία έχετε βάλει το κουμπί πληρωμής. Ο κώδικας του βήματος 2, δείχνει τι γίνεται από τη στιγμή που λάβετε τα δεδομένα σας στο url σας.

**Comment by codnext** [comment]
Μήπως έχετε ένα παράδειγμα σε java για το βήμα 2;

**Comment by dpnevmatikos** [comment]
Δυστυχώς όχι.

**Comment by codnext** [comment]
Το authentication το κάνω στο url http://demo.vivapayments.com/api/transactions ? Προσπαθώ να κάνω Authentication αλλά παίρνω error code 401.
Τα merchantId και apiKey τα βρίσκω από τις ρυθμίσεις -> Προσβαση Api ;

**Comment by dpnevmatikos** [comment]
Δείτε περισσότερα για το authentication στο [wiki](https://github.com/VivaPayments/API/wiki/API-Authentication)

**Comment by nakasgroup** [comment]
Καλησπερα σας 
χρειάζομαι τη βοήθεια σας. θέλω να βαλω στο site μου πληρωμή με καρτα μεσω viva . εχω λογαριασμό. εχω κανει τον τον ορο πληρωμής.. εχω αλλαξει τον κωδικα στο site. μου εμφανίζει να βαλω τη καρτα και τα στοιχεια αλλα δεν μου παίρνει την τιμη που πρεπει για να γινει η χρεωση των προϊόντων, μου παιρνει τιμη 10,00€, πως το συγχρονίζω με τη τιμη στο καλαθι.. τι εχω κανει λαθος?
