### ISSUE TITLE
Δε μπορώ να δηλώσω σελίδα μαζί με το domain στις πηγές πληρωμών

### ISSUE THREAD

**Issue by poseidon-software** [VivaPayments/API#388]
Καλησπέρα είμαστε εταιρία ανάπτυξης λογισμικού στον χώρο εστίασης με μεγάλο πελατολόγιο. Το domain μας προσφέρει υπηρεσίες ξεχωριστά για τον κάθε πελάτη μας, σε ξεχωριστές σελίδες για τον κάθε ένα (π.χ. www.eanimamenu.gr/pelatis). Κάθε πελάτης έχει μεμονωμένα στοιχεία στη σελίδα του, και θα πρέπει να κάνει ξεχωριστή εγγραφή σε εσάς δηλώνοντας πέρα από το domain που τον φιλοξενούμε και την σελίδα του για να μπορεί να εγκριθεί από εσάς. Το πρόβλημα είναι ότι στις πηγές πληρωμών δε μπορεί να δηλώσει το URL όπως πρέπει να το δηλώσει, δεν αφήνει ο form validator slashes "/" ή οτιδήποτε πέρα από το domain.
Σε δοκιμαστική φάση και φάση ανάπτυξης υπάρχει και η δικιά μας δοκιμαστική σελίδα που παρουσιάζουμε την υπηρεσίες μας. Για να υλοποιήσουμε αυτό το template με το οποίο αναβαθμίζουμε τις σελίδες των πελατών μας, σε αυτή τη φάση με τις υπηρεσίες της Viva Wallet, κάναμε την εγγραφή και δε μπορούμε να δηλώσουμε το URL (www.eanimamenu.gr/demo) όπως αναφέραμε προηγουμένως.

Δηλώνοντας το domain www.eanimamenu.gr δεν μπορεί να εγκριθεί η δοκιμαστική σελίδα μας και έπειτα οι σελίδες των πελατών μας γιατι σε αυτή την σελίδα δε γίνονται πληρωμές, είναι ένα διαδικτυακό portal.

**Comment by dpnevmatikos** [comment]
Καλησπέρα,
Την πηγή www.eanimamenu.gr/demo θα πρέπει να την καταχωρήσετε με τον τρόπο
που φαίνεται στο παρακάτω screenshot. Υπόψιν οτι το domain name μπαίνει σε διαφορετικό πεδίο
από το υπόλοιπο url.

![image](https://user-images.githubusercontent.com/1810462/30605283-353c7a26-9d76-11e7-8c06-98f1914de99d.png)

**Comment by poseidon-software** [comment]
Έτσι το έχω δηλώσει, όμως τα στοιχεία που ζητάνε οι συνάδελφοι σας μου είπαν πως πρέπει να αναφέρονται στο domain www.eanimamenu.gr, στοιχεία που είναι διαφορετικά κάθε φορά για κάθε πελάτη.

**Comment by dpnevmatikos** [comment]
Eάν για κάθε πελάτη κάνετε ξεχωριστή εγγραφή στο σύστημα της Viva Payments τότε ναι, θα χρειαστεί κάθε πελάτης να καταθέτει τα στοιχεία που μπορεί να ζητηθούν ώστε να ενεργοποιηθεί μια πηγή πληρωμών που είναι ιστοσελίδα.

Από αυτά που αναφέρατε όμως στο αρχικό σας post, κατάλαβα οτι είχατε θέμα με το πως δηλώνετε το url σε μια πηγή πληρωμών.
