### ISSUE TITLE
Shopify Integration

### ISSUE THREAD

**Issue by MarvellousCreations** [VivaPayments/API#389]
We are trying to integrate Viva Payments in to a Shopify store but are running in to some issues. Is there a specific Viva plan we should be using? I noticed there are three options;

1. Pay with Viva Wallet

2. Redirect

3. Native: our preferred method if possible

We are currently using the native option and it gives a checkout error stating "signature not verified". The native option should allow for customers to checkout without leaving the store, though this is likely not setup for Shopify yet, as Viva seems to be an external gateway. Can you confirm if we need to use redirect and when native will be possible on Shopify?

Any reference as to which we should be using for integrating Viva with Shopify is greatly appreciated!
![viva](https://user-images.githubusercontent.com/32102438/30602911-fd34196e-9d33-11e7-9f01-1caddc2ed840.png)

Thanks!

**Comment by dmihos** [comment]
The required steps for Shopify integration are described here
https://github.com/VivaPayments/API/wiki/Shopify-Integration
You don't need to choose any integration method or create sources, you just need to follow the steps described above.

Only Redirect is supported and there is no plan for any other integration method with Shopify, at the moment.

**Comment by MarvellousCreations** [comment]
Thanks for the response. Still have issues after all of the steps were followed.

We have followed the Shopify Integration wiki completely - 
1. Removed our current credit card gateway
2. Account set to Redirect
3. Authorized Viva gateway using link
4. Entered MerchantId and StoreToken given by merchants@vivawallet
5. Activated Viva gateway on Shopify in production mode

Upon selecting Viva as the payment option within checkout, an error stating "signature not verified" is given.

**Comment by MarvellousCreations** [comment]
@dmihos any updates?

**Comment by dmihos** [comment]
Account/sources seem OK, can you check again please, making sure you don't enter any [space] at the end of the storetoken?

**Comment by mvoreadi** [comment]
Hi, I am the onwer of this shop.  The issue has been resolved but I have the following problem: As customers do not know what Viva Wallet is, we would like to put the phrase "Pay by Credit Card" before the Viva Wallet logo. Can we do this?
[Έγγραφο1.docx](https://github.com/VivaPayments/API/files/1332955/1.docx)

Thanks,

**Comment by dmihos** [comment]
Hi, unfortunately we do not control that page, it is owned and maintained by Shopify.

**Comment by mvoreadi** [comment]
Shopify has a different option for Credit Cards gateways. The option you have selected for Viva is for providers like Paypal. So in oder for the customer to select a credit card option, we have to, either put Viva in the position that Shopify provides for Credit Card Gateways or change the logo, coming from Viva, to: "Payments by Credit card Viva Wallet". Can you help us implement either of these options?

**Comment by mvoreadi** [comment]
@dmihos any updates?

**Comment by mvoreadi** [comment]
@dmihos Καλημέρα.  Θα μπορούσατε να το κοιτάξετε παρακαλώ;

**Comment by kostGX** [comment]
Hello @mvoreadi,

Viva Wallet supports many different types of payments, including card payments. So, in a way, it is "a provider like Paypal".  To show the support of card payments' acceptance, there are the Card Schemes logo on the right side (VISA, mastercard, Diners, AMEX, etc) of the Menu item you're describing.

I have added your request on our Backlog to revisit it and better understand how to implement you're asking, but this feature is not currently on our roadmap.

**Comment by mvoreadi** [comment]
Γειά σας @kostGX & @dmihos ,
Στη σελίδα πληρωμής της Viva στο e-shop μου Anthoshop.com θα ήθελα να φύγει το μήνυμα του IVR πληρωμή μέσω τηλεφώνου.  Μπορείτε παρακαλώ να με καθοδηγήσετε;
Ευχαριστώ,
Μαριλένα

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.

**Comment by mvoreadi** [comment]
Hi, I have to come back to this issue as the Viva screen for payment with a credit card is in Greek and I need it to be in English.  Can you please help me change the Language asap?
![a](https://user-images.githubusercontent.com/32038103/76707985-2a8e9300-66fc-11ea-9af8-70288d5036e9.jpg)
