### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by creaturesgr** [VivaPayments/API#39]
Hello , 

When I make a payment to katsiki.gr I get correctly the redirection to viva's website. After I put the card information and complete the payment it doesn't redirect back to my website. It stays at the payment successfull page.

**Comment by dpnevmatikos** [comment]
Hi there,
Can you please check if your redirect url is declared at your [Payment Source's settings](https://www.vivapayments.com/selfcare/en-us/sources/paymentsources)?
Just click on your Payment Source and check the **Success URL** and **Failure URL** at the popup window as shown below:

![capture](https://cloud.githubusercontent.com/assets/1810462/12922852/d6a6f50c-cf5b-11e5-8a41-1161a25dcfca.PNG)

Please let me know if that helped.

**Comment by creaturesgr** [comment]
all this information is filled but still no redirect. I also tried to change the success url to "katsiki.gr/home" witch is my homepage and still no result

**Comment by dmihos** [comment]
Hi creaturesgr
We noticed you created a new source where you set your domain to 'katsiki.gr'.
Your OrderCodes, though, are created on source Default, which still uses the default urls (vivapayments.com)
Please refer to https://github.com/VivaPayments/API/wiki/Optional-Parameters for guidance on how to set the SourceCode during the creation of the Order.

**Comment by creaturesgr** [comment]
Αυτες ειναι οι ρυθμισεις που εχω κανει και συνεχιζεο να κολλαει. Ειναι κάτι λάθος?

**Comment by dmihos** [comment]
Hi
The problem is not on the configuration of the sources but on your code that creates the Order.
You need to pass the sourcecode of your new Source during the creation of the Order.
The above mentioned reference will help you on this.
