### ISSUE TITLE
Can I test the payments from localhost domain?

### ISSUE THREAD

**Issue by codnext** [VivaPayments/API#390]
Καλησπέρα,
Θα ήθελα να ρωτήσω αν μπορούμε από localhost να δοκιμάσουμε την μέθοδο πληρωμής redirection? Μπορώ να φτιάξω πηγή πληρωμής για localhost? 
Το δοκιμάζουμε σύμφωνα με το ακόλουθο tutorial https://github.com/VivaPayments/API/wiki/Redirect-Checkout
αλλά παίρνουμε error 401 Authorization has been denied for this request.

Το url που χρησιμοποιούμε για το post request ειναι το ακόλουθο: http://demo.vivapayments.com/api/orders

Είναι σωστό;

**Comment by stavros959** [comment]
Θα μπορούσες να ανοίξεις την 80 πόρτα στο ρούτερ σου και να δηλώσεις την Public IP σου ως URL.
