### ISSUE TITLE
Pay With Viva Token

### ISSUE THREAD

**Issue by stavros959** [VivaPayments/API#392]
Καλημέρα,
Δεν υπάρχει κάποιος τρόπος να πάρω το token που βγάζει το "pay with vivawallet" χωρίς να ποσταρω την φόρμα σε αρχείο php? Θέλω να πάρω το token και να το στείλω με Ajax στον σέρβερ καθώς, υπάρχουν και άλλα πράγματα τα οποία πρέπει να στείλω στον σέρβερ κατά την πραγματοποίηση της πληρωμής και η φόρμα δεν μου άφηνει κάποια επιλογή.. Ευχαριστώ!

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
