### ISSUE TITLE
ΠΡΟΒΛΗΜΑ ΠΛΗΡΩΜΩΝ με Πιστωτική Κάρτα μέσω της Viva Wallet... (click-tshirt.gr)

### ISSUE THREAD

**Issue by kelkal** [VivaPayments/API#393]
Καλημέρα σας.
Την προηγούμενη εβδομάδα εντοπίσαμε πρόβλημα στις συναλλαγές των πελατών μας με την εφαρμογή της viva wallet. Αποτυγχάνει να ολοκληρωθεί η διαδικασία της πληρωμής έπειτα από την συμπλήρωση των στοιχείων της πιστωτικής κάρτας του πελάτη.
Σας στέλνω screenshots του προβλήματος που ανέφερα παραπάνω.

Καλέσαμε στη viva wallet. Η απάντηση ήταν ότι θα μας καλέσει το τεχνικό τμήμα για να μας ενημερώσει γιατί συμβαίνει αυτό από τη στιγμή που ο λογαριασμός μας έχει πιστοποιηθεί στη viva wallet και η πλατφόρμα μας ( https://click-tshirt.gr/ ) επίσης.
Πράγματι επικοινώνησαν μαζί μας και μας είπαν να κοιτάξουμε το Github. 
Ο τεχνικός μας το κοίταξε. Έκανε όλα τα απαραίτητα βήματα για να ενημερώσει την εφαρμογή, πάλι όμως υπάρχει το ίδιο ακριβώς πρόβλημα...

![eikona1](https://user-images.githubusercontent.com/14614008/30953322-07cfc2cc-a434-11e7-9bf7-f36cbf7e84b4.jpg)
![eikona2](https://user-images.githubusercontent.com/14614008/30953323-07d39b90-a434-11e7-93a8-fe2448c93040.jpg)
![eikona3](https://user-images.githubusercontent.com/14614008/30953324-07d78aac-a434-11e7-8b54-26b33a6c5946.jpg)
![eikona4](https://user-images.githubusercontent.com/14614008/30953325-07dc7f12-a434-11e7-91a7-f1647d3ba001.jpg)
![eikona5](https://user-images.githubusercontent.com/14614008/30953327-07e3c880-a434-11e7-9e03-90ca190b6e7e.jpg)
![eikona6](https://user-images.githubusercontent.com/14614008/30953326-07e37fb0-a434-11e7-80d7-7dd7b7f52a4c.jpg)
![eikona7](https://user-images.githubusercontent.com/14614008/30953328-07f26f16-a434-11e7-90d3-487499348905.jpg)
![eikona8](https://user-images.githubusercontent.com/14614008/30953329-07f646cc-a434-11e7-8603-dae1d95ae4e7.jpg)
![eikona9](https://user-images.githubusercontent.com/14614008/30953330-07fddb44-a434-11e7-803d-c64ea6bbbc31.jpg)

Στην Εικόνα 9 φαίνεται το πρόβλημα να μην είναι του site αφού έχει περάσει ήδη στη Viva Wallet.

Θα θέλαμε να δοθεί μία λύση διότι έχουμε μία πλατφόρμα η οποία αυτή τη στιγμή δε λειτουργεί παρ'όλες τις διαδικασίες που έγιναν τόσο καιρό για την viva wallet...

Παρακαλώ καλέστε μας να μας καθοδηγήσετε για την πληρωμή ή για οποιοδήποτε άλλο στοιχείο στις ρυθμίσεις μας που θεωρείτε πως μπλοκάρει τη διαδικασία.

Ευχαριστούμε προκαταβολικά!

**Comment by stavros959** [comment]
Για να σου εμφανίζει ο chrome την ειδοποίηση αποθήκευση κάρτας, υποθέτω πως η σελίδα σου εμφανίστηκε σωστά, ετσι; Έβαλες τα στοιχεία της κάρτας και μετά απέρριψε την συναλλαγή;

**Comment by stavros959** [comment]
Έκανα μια δοκιμαστική παραγγελία στο site με τα στοιχεία test. Δεν φαίνεται να είναι στο demo περιβάλλον (με έβγαλε στο www.vivapayments.com όχι demo.vivapayments.com) και η σελίδα έβγαζε το ποσό κανονικά που σημαίνει πως έχει δημιουργηθεί κανονικά το token πληρωμής (ελπίζω να μην κάνω λάθος)... οπότε... περίμενε καλύτερα για το support να σου απαντήσει

**Comment by dmihos** [comment]
Την πηγή που χρησιμοποιείτε, την έχετε δηλώσει ως Native στο Integration Method (Viva Wallet account > menu >  Οι Πωλήσεις μου > Πηγές Πληρωμών).
Θα πρέπει να τη δηλώσετε ως Redirect και να δηλώσετε τα σχετικά urls (επιτυχίας/αποτυχίας).

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
