### ISSUE TITLE
αριθμοι καρτων για δοκιμές

### ISSUE THREAD

**Issue by alkis-giamalis** [VivaPayments/API#394]
Καλημερα, τo demo.vivapayments.com για developement ισχύει ;
Τι αρ. κάρτας και CVV πρέπει να βάλω για να κάνω δοκιμές ;

**Comment by stavros959** [comment]
Αρ.Κάρτας: 4111 1111 1111 1111 
CVV : 111

Υπάρχουν στην πρώτη σελίδα του wiki.
