### ISSUE TITLE
Δεν γινεται redirect σε success page υπό συνθηκες

### ISSUE THREAD

**Issue by alkis-giamalis** [VivaPayments/API#395]
Καλησπέρα,

πραγματοποιώντας μία συναλλαγη στο Viva, από το www.helioskiosk.gr,
οταν δίνουμε merchant ID της ΔΟΛ Α.Ε., όλα προχωρούν κανονικά.
και με την ολοκληρωση της συναλλαγης ο πελάτης επιστρέφει στην success page.

Όταν δώσαμε merchant ID της ALTER EGO MME A.E. στην ολοκλήρωση της συναλλαγης, arxik;a αν και οδηγηθήκαμε μετά στο success URL είδαμε πως δεν ειχε ολοκληρωθει η διαδικασία εκ μέρους μας.

Αυτα, την Παρασκευη 29 Σεπτ.

Σημερα βάλαμε debugging information στην success page, βγάλαμε ενα server μας εκτος φάρμας, τον δήλωσα και στα hosts μου με IP και εκάνα άλλη μια παραγγελία (με ALTER EGO merchant ID)

Αυτη τη φορά οδηγηθηκα εδω: 

https://www.vivapayments.com/web/checkout/result?t=05912e30-ea50-4e39-a33a-7f44f2fddd94&s=1094483567572601&lang=el-GR

και όχι στο success Page.
΄Έτσι δεν παραχθηκε το debug logging που περίμενα.

Γιατι συμπεριφερονται διαφορετικα οι πληρωμες με ΔΟΛ / ALTER EGO και πως θα οδηγουμε τον πελάτη στη success page στην δευτερη περιπτωση (ωστε να βλεπουμε και το debug logging μας ;)

**Comment by dmihos** [comment]
Καλησπέρα σας
Στην πηγή που χρησιμοποιεί ο έμπορος ALTER EGO, έχει δηλωθεί το success/fail url του site σας (μένού Οι Πωλήσεις μου> Πηγές Πληρωμών);

**Comment by alkis-giamalis** [comment]
Άλλαξα καποιες ρυθμισεις στο redirection, θα δοκιμασω ξανα.

**Comment by alkis-giamalis** [comment]
ΟΚ, επαιξε
