### ISSUE TITLE
 Η πληρωμή απέτυχε. Αιτία Quote totals must be collected before this operation.

### ISSUE THREAD

**Issue by tdsgr** [VivaPayments/API#398]
Έχουμε πολλές φορές μήνυμα αποτυχίας πληρωμής (έρχεται μέσω mail) με το παρακάτω αίτιο 

Η πληρωμή απέτυχε.
Αιτία: Quote totals must be collected before this operation.

Έχουμε eshop με magento 1.9X. Τι μπορούμε να κάνουμε για να δούμε τι φταίει;

**Comment by VivaWalletSupport** [comment]
Have a look at following article:
https://journalxtra.com/magento/quote-totals-must-be-collected-before-this-operation-blah-blah-blah-what-a-pita-you-are-magento/

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
