### ISSUE TITLE
Η πληρωμή απέτυχε! Μήνυμα λάθους με πηγή πληρωμών και τη μέθοδο Redirect

### ISSUE THREAD

**Issue by codnext** [VivaPayments/API#399]
Χρησιμοποιούμε την vivawallet για τις πληρωμές στην ιστοσελίδα https://www.professionalsmarket.gr Έχουμε δημιουργήσει μία πηγή πληρωμής με το domain, μέθοδο redirect και τους συνδέσμους Επιτυχίας και αποτυχίας. Μας μεταφέρει με επιτυχία στην vivawallet για την πληρωμή και όταν βάζεις τα στοιχεία της κάρτας και πατά το κουμπί χρέωση εμφανίζει το παρακάτω:
![vivapayments1](https://user-images.githubusercontent.com/31348990/31385114-923bb160-adca-11e7-970e-d53e98085b14.png)

Γιατί μπορεί να συμβαίνει αυτό;

**Comment by codnext** [comment]
Το json που μου επιστρέφεται μετά το post request στο https://www.vivapayments.com/api/orders είναι το παρακάτω:
{"OrderCode":7490714........,"ErrorCode":0,"ErrorText":null,"TimeStamp":"2017-10-11T21:46:30.6898872+03:00","CorrelationId":null,"EventId":0,"Success":true}

Μετά καλώ με post request το ακόλουθο: https://www.vivapayments.com/web/checkout?ref="+ordercode
Με μεταφέρει στο παρακάτω:
![avivapayment4](https://user-images.githubusercontent.com/31348990/31460300-9ecccf72-aece-11e7-9aec-f18a97b265d0.png)

Δοκιμάζω να βάλω διάφορες κάρτες από τράπεζες αλλά παίρνω το παρακάτω μήνυμα λάθους:
![avivapayment5](https://user-images.githubusercontent.com/31348990/31460331-bc756c1e-aece-11e7-8dc1-2e80c85d2c32.png)

Θα μπορούσατε σας παρακαλώ να μας βοηθήσετε με αυτό; Παρακαλώ απαντήστε μας άμεσα να το λύσουμε γιατί δεν μπορούμε να δεχτούμε πληρωμές.

**Comment by dmihos** [comment]
Καλησπέρα 
Με το OrderCode που φαίνεται στα screenshots υπήρξε μια προσπάθεια συναλλαγής η οποία απορρίφθηκε από την εκδότρια τράπεζα.
Δεν εντοπίζουμε κάποιο άλλο πρόβλημα. 

Όσο για την πηγή, θα πρέπει να χρησιμοποιήσετε το SourceCode της νέας πηγής στη συναλλαγή, ώστε μετά την πληρωμή να γίνεται επιστροφή στο site σας

**Comment by codnext** [comment]
Έχουμε δοκιμάσει από διάφορες τράπεζες περισσότερες από μία φορές κατά τη διάρκεια 2 ημερών και παίρνουμε το ίδιο σφάλμα. Τι εννοείτε να χρησιμοποιήσω το SourceCode της νέας πηγής? Πρέπει να περάσουμε επιπλέον παράμετρο στο request?
Ευχαριστώ

**Comment by dmihos** [comment]
Δώστε μου μερικά σχετικά OrderCodes να τα διερευνήσουμε.

Το SourceCode είναι παράμετρος του CreateOrder και πρέπει να οριστεί explicitly.
Διαφορετικά, δε μπορούμε να ξέρουμε σε ποιο url θέλετε να επιστρέψει ο πελάτης.

**Comment by codnext** [comment]
Εννοείτε να οριστεί με value explicitly?

**Comment by dmihos** [comment]
Αν η πηγή σας έχει πχ κωδικό 4477, θα πρέπει να περάσετε στο CreateOrder: SourceCode=4477

**Comment by codnext** [comment]
οκ, ευχαριστώ!

**Comment by codnext** [comment]
Πήρα πάλι το ίδιο μήνυμα για το ordercode: 1351473477072605

**Comment by dmihos** [comment]
Χρησιμοποιήστε κάποιο μεγαλύτερο ποσό, πάνω από 0.50/0.60
Αυτό ήταν το πρόβλημα εξαρχής

**Comment by codnext** [comment]
είχα δοκιμάσει και με 50€ και είχα πάρει το ίδιο λάθος... Θα δοκιμάσω ξανά με μεγαλύτερο ποσό.
Υπάρχει δυνατότητα να χρησιμοποιήσουμε μόνο σύνδεσμο για επιτυχή πληρωμή; Σε περίπτωση που είναι ανεπιτυχείς να τον κρατάει στη viva για να ξανα προσπαθήσει. Γίνεται αυτό;

**Comment by codnext** [comment]
Δοκίμασα με 1€ και έγινε η πληρωμή. Επομένως αυτό ήταν το πρόβλημα! Ευχαριστώ
Παρακαλώ απαντήστε μου στο παραπάνω ερώτημα αν είναι εύκολο.

**Comment by dmihos** [comment]
Όχι δε γίνεται αυτό που περιγράφετε
