### ISSUE TITLE
Empty json response

### ISSUE THREAD

**Issue by specialone33** [VivaPayments/API#40]
Καλημέρα σας

προσπαθώ να συνδέσω το site http://agrotikes-eykairies.gr/online-registration

με το vivapayments api

Χρησιμοποιώ την παρακάτω εγκεκριμένη πηγή πληρωμών

Κωδικός	Περιγραφή	Τύπος	Συνδεδεμένο Wallet	Κατάσταση	Λειτουργία	Επιλογές
4871	agrotikes-eykairies	Ιστοσελίδα	Primary	Ενεργή	
Διαγραφή

Οταν χρησιμοποιούσα τα demo στοιχεία όλα λειτουργούσαν κανονικά. Όταν χρησιμοποίησα τα κανονικά στοιχεία της πηγής πληρωμών, δεν κάνει Parse το JSON response

όταν κάνω print_r  το $resBody μου βγάζει λευκή σελίδα, όταν χρησιμοποιώ τα demo στοιχεία μου κάνει κανονικά print_r το json object.

Μπορείτε παρακάλω να με βοηθήσετε ?

Χρησιμοποιώ τον παρακάτω κώδικα
================================
`$request =  'https://www.vivapayments.com/api/orders';

$MerchantId = 'ac850453-3820-4535-81c9-3ec502d1fb84';
$APIKey = 'AGRO1';
$CustomerTrns = $data['seminar'];
$MerchantTrns = $data['name'];
$Email = $data['email'];

//Set the Payment Amount
$Amount = $data['totalamount'] * 100 ;	// Amount in cents
$AllowRecurring = 'false';
$RequestLang = 'el-GR';
$Source = '4871';
$postargs = 'Amount='.urlencode($Amount).'&AllowRecurring='.$AllowRecurring.'&RequestLang='.$RequestLang.
        '&CustomerTrns='.$CustomerTrns.'&MerchantTrns='.$MerchantTrns.'&Email='.$Email.'&SourceCode='.$Source;
// Get the curl session object
$session = curl_init($request);
// Set the POST options.
curl_setopt($session, CURLOPT_POST, true);
curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
curl_setopt($session, CURLOPT_HEADER, true);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
// Do the POST and then close the session
$response = curl_exec($session);
// Separate Header from Body
$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
$resHeader = substr($response, 0, $header_len);
$resBody =  substr($response, $header_len);
curl_close($session);
// Parse the JSON response
try {
	if(is_object(json_decode($resBody))){
	  	$resultObj=json_decode($resBody);
	}else{
		preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader, $match);
				throw new Exception("API Call failed! The error was: ".trim($match[1]));
	}
} catch( Exception $e ) {
	echo $e->getMessage();
}
if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
	$orderId = $resultObj->OrderCode;
	
	
	 $data['url'] = "https://vivapayments.com/web/newtransaction.aspx?ref=$orderId";
}
	
else{
	echo 'The following error occured: ' . $resultObj->ErrorText;
}`

Μπορείτε παρακαλώ να με βοηθήσετε?

**Comment by nickgardos** [comment]
Καλό θα ήταν τις μεταβλητές $MerchantId και $APIKey να τις κρύψετε και να τις αλλάξετε αμέσως γιατί έχετε δώσει δημοσίως αυτή τη στιγμή τα κλειδιά του λογαριασμού σας.

**Comment by dpnevmatikos** [comment]
@specialone33 ενδεχομένως να υπάρχει θέμα με το SSL version που τρέχει ο server σας.
Δοκιμάστε αυτό που προτείνεται στο #32 μήπως διορθωθεί το πρόβλημα.

Επίσης **αλλάξτε άμεσα το api key σας** όπως πολύ σωστά σας προέτρεψε ο @nickgardos 
στη σελίδα :  https://www.vivapayments.com/selfcare/el-gr/security/apiaccess

**Comment by specialone33** [comment]
Θα το δοκιμάσω και θα σας ενημερώσω. Τα άλλαξα τα στοιχεία

**Comment by specialone33** [comment]
Καλησπέρα σας
το πρόβλημα διορθώθηκε.
Θα ήθελα να ρωτήσω αν υπάρχει τρόπος να παρακάμψω το alert που βγάζουν οι browsers από τη μετάβαση http σε httpsχωρίς να εγκαταστήσω κάποιο ssl

**Comment by dpnevmatikos** [comment]
Καλησπέρα και πάλι,
Δυστυχώς από όσο γνωρίζω δεν υπάρχει κάποιος τρόπος για να ξεπεραστεί αυτό το alert.

**Comment by botonakis** [comment]
Καλησπέρα,

για το SSL μπορείς να χρησιμοποιήσεις κάτι σαν το: https://letsencrypt.org/
Παρόλα αυτά προτείνεται η αγορά SSL.
