### ISSUE TITLE
Python integration: HTTP Error 400: Invalid Input Parameters in production

### ISSUE THREAD

**Issue by csylaios** [VivaPayments/API#400]
We just released our services integrated with VIVA payments and everything worked ok in the demo account. however when we switched to prod and call 
```
payment = viva.create_order(amount, 
                                                 RequestLang=lng,
                                                 CustomerTrns=descr,
                                                 SourceCode=config.VIVA_SOURCE,
                                                 Email=data.email,
                                                 Phone=phone)
```

data that we are submitting:  **700, el-GR, Payment to OffersAroundMe, XXXX, admin@offersaroundme.mobi, 2310474100**

we get the following error: HTTP Error 400: Invalid Input Parameters in production. this is kind of urgent since we are in prod and its running at the moment for our users.

thanks Chris

**Comment by dmihos** [comment]
Hi. 
The error indicates a problem with one or more input parameter.
Please make sure you are using the production merchantid/ApiKey, you post to correct production url (https://www.vivapayments.com/api/orders) and all input parameters have appropriate values.
If problem is not resolved, please send an email with a working sample (where actual values, not variables, are passed via POST) that demonstrate the problem.

**Comment by csylaios** [comment]
hi,

we have added extra logs to the call we are doing

starting payment to viva with: 700, el-GR, Payment to OffersAroundME, 9059, admin@offersaroundme.mobi, 2310474100 
 <https://papertrailapp.com/systems/production/events?focus=856943850793648140&selected=856943850793648140>Oct 17 16:55:57 production <https://papertrailapp.com/systems/production/events?centered_on_id=856943850793648140> DOMAIN-client: <https://papertrailapp.com/events?centered_on_id=856943850793648140&q=program%3ADOMAIN-client> calling viva endpoint https://www.vivapayments.com/web/newtransaction.aspx?ref=orders 
 <https://papertrailapp.com/systems/production/events?focus=856943850793656360&selected=856943850793656360>Oct 17 16:55:57 production <https://papertrailapp.com/systems/production/events?centered_on_id=856943850793656360> DOMAIN-client: <https://papertrailapp.com/events?centered_on_id=856943850793656360&q=program%3ADOMAIN-client> calling viva endpoint with data "Phone=2310474100&amount=700&SourceCode=9059&RequestLang=el-GR&CustomerTrns=Payment+to+OffersAroundME&Email=admin%40offersaroundme.mobi"

these are the endpoint and params we are using and still getting the same error. can you have a look and let us know why we are getting this error?

thanks
chris.

**Comment by dmihos** [comment]
I just sent at `https://www.vivapayments.com/api/orders`, using your API credentials, the following, via **POST**

```json
{
	"Amount":700,
	"Phone":"2310474100",
	"SourceCode":"9059",
	"RequestLang":"el-GR",
	"CustomerTrns": "Payment to OffersAroundME",
	"email":"admin@offersaroundme.mobi"
}
```
and response was successful, I was given an OrderCode.
I think you need to check your code.

**Comment by csylaios** [comment]
ok found the issue

the issue is in the sample code that VIVA provides for python

     def __init__(self, merchant_id=None, api_key=None, production=False):
 <https://bitbucket.org/gsylaios/offers-server-client/commits/534a7ab600a2e68092ee56fc52cc672079119f85?at=master#add-comment> <https://bitbucket.org/gsylaios/offers-server-client/commits/534a7ab600a2e68092ee56fc52cc672079119f85?at=master#Loffers/models/payment.pyF26>
-        self.url = VivaPayments.DEMO_URL if production == False else VivaPayments.PRODUCT_REDIRECT_URL
 <https://bitbucket.org/gsylaios/offers-server-client/commits/534a7ab600a2e68092ee56fc52cc672079119f85?at=master#add-comment> <https://bitbucket.org/gsylaios/offers-server-client/commits/534a7ab600a2e68092ee56fc52cc672079119f85?at=master#Loffers/models/payment.pyT26>
+        self.url = VivaPayments.DEMO_URL if production == False else VivaPayments.PRODUCTION_URL


you can see the change that we have done to make it work. it is correct for the demo environment but wrong for the prod env

can you please correct it in github samples because its something that people don't usually think of since they expect this to be correct.

thanks
chris

**Comment by dmihos** [comment]
Right, I fixed that, thanks for reporting

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
