### ISSUE TITLE
Shopify "Could not create order. Generic Error."

### ISSUE THREAD

**Issue by ULALAjewels** [VivaPayments/API#401]
Καλημέρα
Υποθέτω ότι έχω κάνει σωστά την διασύνδεση μεταξύ Viva και Shopify. Όταν η κατάσταση στο Shopify είναι demo και προσπαθώ να κάνω αγορά μου εμφανίζει "store could not found" και "Could not create order. Generic Error." όταν είναι απενεργοποιημένο το demo. Μπορείτε να με καθοδηγήσετε?
Ευχαριστώ 
Γιάννης

**Comment by dmihos** [comment]
Καλησπέρα
Την πηγή Shopify που είχε φτιαχτεί στο λογαριασμό σας δεν έπρεπε να την πειράξετε.
Φτιάχτηκε καινούρια, δεν πρέπει να τη σβήσετε/τροποποιήσετε.
Ξαναδοκιμάστε τώρα μια πληρωμή αν θέλετε.

Το  ' demo' mode του Shopify απαιτεί λογαριασμό στο demo περιβάλλον (https://demo.vivapayments.com).
Οπότε θα πρέπει να επαναλάβετε τη διαδικασία ενεργοποίησης και θα σας δωθεί νέο StoreToken (για demo μόνο).

**Comment by ULALAjewels** [comment]
Διορθώθηκε. Ευχαριστώ πολύ.

**Comment by ULALAjewels** [comment]
Δοκίμασα πληρωμή και μου βγάζει "Error
                                                            Payments generic error"
Τι θα πρέπει να κάνω?
