### ISSUE TITLE
VivaPayments: No form element was found for submission

### ISSUE THREAD

**Issue by dklisiaris** [VivaPayments/API#402]
I am trying to use the _pay with viva wallet_ button in a page where the _amount_ is calculated based on user actions.

I use this code to dynamically load the button, which is called every time the total amount changes:
```javascript
var loadVivaButton = function(amount) {
  if (amount == null) {
    amount = 30;
  }
  $('#vivaBtnContainer').empty();
  $('#vivaBtnContainer').append('<button type="button" data-vp-amount="' + amount + '" data-vp-publickey="my-public-key" data-vp-lang="el" data-vp-description="project-name" data-vp-sourcecode="my-sourcecode" data-vp-merchantref="my-merchant-id" data-vp-baseurl="http://demo.vivapayments.com"></button>');
  $.getScript("http://demo.vivapayments.com/web/checkout/js");
};
```

This first time this function executes it succefully load the button and everything works as expected.

When the amount changes and the functions run for the second time, the amount is correct and the pop up works fine but when the payment is completed and the form should submit then I get a 
`VivaPayments: No form element was found for submission` error.

Is any way to use that payment way in our current situation?

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
