### ISSUE TITLE
οι αποτυχημένες συναλλαγές προωθούνται στον server μου

### ISSUE THREAD

**Issue by atr0x23** [VivaPayments/API#403]
Θα ήθελα την βοήθειά σας γιατί ίσως να μην έχω καταλάβει πλήρως
 την διαδικασία της πληρωμής μέσω viva-wallet.

Έχουν γίνει 2 παραγγελίες στο site μας.
Η μία στις 18/10/2017 στις 10:16am και ποσό:7€
Η άλλη στις 2017-10-19 09:08am και ποσό: 4€

για τις οποίες δεν εμφανίστηκε ποτέ η χρέωση στην σελίδα μας
 στοviva-wallet. Μίλησα με κάποιον από εσάς και μου είπε πως οι
 πληρωμές αυτές δεν ολοκληρώθηκαν ποτέ. Ωραία ως εδώ.
Σαν χρήστης του viva-wallet δεν θα έπρεπε να ενημερωθώ κάπως? Ότι η πληρωμή δεν πραγματοποιήθηκε...

Το παράξενο είναι ότι αφού η πληρωμή δεν έγινε,γιατί η παραγγελία προωθήθηκε στον server μας σαν να πραγματοποιήθηκε κανονικά?
Δεν θα έπρεπε η διαδικασία να διακοπεί εκεί και να μήν φθάσει ποτέ στον server εφόσον
δεν πραγματοποιήθηκε ποτέ πληρωμή?

Θα ήθελα επίσης εάν μπορείτε να μου εξηγήσετε την διαδικασία της πληρωμής όσο πιο αναλυτικά γίνετε για να καταλάβω καλύτερα.

Σας ευχαριστώ.

**Comment by atr0x23** [comment]
to url einai:
https://coffeebrandsdelivery.gr

**Comment by VivaWalletSupport** [comment]
Are you using a specific plugin for the connection to Viva Wallet? If so, what plugin is used?

**Comment by atr0x23** [comment]
yea I am using VivaPayments WooCommerce Payment Gateway Έκδοση 1.0.4 | Από emspace.gr

**Comment by VivaWalletSupport** [comment]
Try the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress
It will update the order status as configured in the plugin in case a success transaction is received.

**Comment by atr0x23** [comment]
the problem it's not in the success transaction!!!  It's in the incomplete transaction. 2 orders have been maded and they never completed their transaction with the bank because of a problem with the user's card But the order returns to the server as completed! this isn't wrong?!!

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
