### ISSUE TITLE
An error occured, please try again. Χωρίς κωδικό σφάλματος

### ISSUE THREAD

**Issue by jampweb** [VivaPayments/API#404]
Καλησπέρα,
εδώ και 2 εβδομάδες αντιμετοπίζω ένα πρόβλημα που δεν μπορώ να το εξηγήσω. Έχω το plugin: WooCommerce Vivawallet Gateway, Version 3.0.1 | By Viva Wallet.
Έχω ακολουθήσει τη διαδικασία όπως ακριβώς περιγράφετε στις οδηγίες. Κι ενώ κάνω την παραγγελία μου μεταφέρομαι στο περιβάλλον της viva εισάγω τα στοιχεία της κάρτας μου και υποβάλλω την χρέωση της κάρτας, μου κάνει redirection στο site μου αλλά στη σελίδα του καλαθιού έχοντας αυτό το μήνυμα στην κορυφή: An error occured, please try again. χωρίς κωδικό σφάλματος ή περιγραφή? Κι ενώ έχει εγκριθεί η πηγή πληρωμών και όλα φαίνονται να λειτουργούν. Τι θα μπορούσα να κάνω για να λυθεί το πρόβλημα ή τουλάχιστον να πάρω ένα αναγωριστικό ώστε να ξέρω που να κινηθώ για την διόρθωσή του. Έκδοση WordPress 4.8.2 Woocommerce 3.2.1
![screenshot from 2017-10-20 16-31-18](https://user-images.githubusercontent.com/32328408/31823375-a8197d22-b5b4-11e7-8045-754d8a1f7737.png)

**Comment by VivaWalletSupport** [comment]
Hello, did you test in the demo mode using the test card number? If not, follow this procedure first.

**Comment by jampweb** [comment]
Yeap... In demo mode everything was great and succeed...

**Comment by VivaWalletSupport** [comment]
In your Viva Wallet the transaction (from your screenshot) was completed successfully?

**Comment by jampweb** [comment]
No, neither in my vivawalet nor in my woocommerce! However in my woocommerce admin panel I can see an order that pending payment...

**Comment by VivaWalletSupport** [comment]
In that case the shown (general) error message is correct if the transaction failed and the order status remains pending.

**Comment by jampweb** [comment]
Ok but my question is why the transaction failed? And where can I find the error log to find out the problem to fix it. This is a general situation with every credit or debit card, not only mine, so the e-shop couldn't work if the transactions failed. Where I could find the reason of failed transaction? However the communication with API seems good and the demo transactions were succeed.

**Comment by VivaWalletSupport** [comment]
The exact reason is not logged, you could contact the card issuer to find out more about the problem. What card and amount did you use?

**Comment by jampweb** [comment]
Ok with your question I found the answer! There was a demo product until to find why transactions failed, but the replay payments in a small amount of a product wasn't properly for the banks...
