### ISSUE TITLE
Πρόβλημα με την ένταξη του VivaWallet POS ως πύλη πληρωμών στο Elorus

### ISSUE THREAD

**Issue by athinaionfos** [VivaPayments/API#405]
Χαιρετώ τους Developers & Troubleshooters!
To πρόβλημα που αντιμετωπίζω είναι το εξής: 
Εάν προσθέσω στο Elorus ως πύλη πληρωμών το VivaWallet POS μου ζητάει Merchant ID * το οποίο το βρίσκω στο "Μπορείτε να βρείτε το merchant ID στο λογαριασμό σας στο VivaWallet, κάτω από την ενότητα "Ρυθμίσεις->Πρόσβαση API"  ..... και όντος το βάζω και όλα ειναι μια χαρά!

Ομως μου ζητάει και Κωδικός πηγής και εκεί λέει το Elorus: Ο κωδικός της πηγής που είναι συνδεδεμένη με τη συσκευή POS. Συνήθως είναι ίδιος με το serial number της συσκευής.
Βάζω το serial number της συσκευής μου που είναι το D200 αλλά κάθομαι στον άξονα των Ζ!!!
Μου βγάζει λάθος ... οπότε δεν μπορώ να συνδέσω το POS μου στο Elorus.

Can you help?
Looking forward to hearing soon from you guys

Mε εκτίμηση

Γιώργος Χριστοδούλου

**Comment by dmihos** [comment]
Καλημέρα
Εφόσον ζητάει Κωδικό Πηγής, επιβεβαιώστε ότι πράγματι ο κωδικός της πηγής είναι το s/n.
Μπορείτε να δείτε τις πηγές στο μενού Οι πωλήσεις μου>Πηγές Πληρωμών (στήλη 'Κωδικός')

**Comment by athinaionfos** [comment]
Ευχαριστώ!!! Την βρήκα εχθές αυτην την πληροφορία από ένα εκπαιδευτικό βίντεο της Elorus και δουλεύει κανονικά.Τώρα έχουμε άλλο ένα πρόβλημα που το ψάχνουν και αυτοί.Εαν χρειαστεί θα επικοινωνήσω μαζί σας.Νά'στε καλά.
 Χριστοδούλου Γεώργιος Jagaro
Κοινωνική Συνεταιριστική ΕπιχείρησηΑθηναίων ΦωςKέντρο Ολιστικής Ανάπτυξης και Θεραπείας
Ιστοσελίδα: www.athinaionfos.grFB:https://www.facebook.com/athinaionfosΤηλ: 210 525 6729, 697 365 4844 

    Στις 9:43 π.μ. Τρίτη, 24 Οκτωβρίου 2017, ο/η dmihos <notifications@github.com> έγραψε:
 

 Καλημέρα
Εφόσον ζητάει Κωδικό Πηγής, επιβεβαιώστε ότι πράγματι ο κωδικός της πηγής είναι το s/n.
Μπορείτε να δείτε τις πηγές στο μενού Οι πωλήσεις μου>Πηγές Πληρωμών (στήλη 'Κωδικός')—

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
