### ISSUE TITLE
Link viva payment with woocommerce e-shop

### ISSUE THREAD

**Issue by pixelgr** [VivaPayments/API#406]
Hi there!

I am new to e-shop development and I would like to know if I followed the right procedure for the incorporation of this payment method to my website. 
I installed Viva Payments - Viva Wallet WooCommerce Payment Gateway plugin, and filled merchant id and ΑPI Key. I added a new website at demo vivapayment page and filled as url success and failure page the following wc-api/WC_Papaki_Vivapayments_Gateway. Then I made a test order with the card number you provide and the transaction seemed successful.  
What I wanted to know is if the same procedure applies in live connection too. No coded is needed? It just seems too easy to be true...

**Comment by VivaWalletSupport** [comment]
Hello, I cannot assist you with the plugin you are using, it would be better to post your questions to the maker of it. Otherwise use the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

**Comment by franticpsyx** [comment]
Also see https://github.com/somewherewarm/woocommerce-gateway-viva

**Comment by kostGX** [comment]
Closing as issue was last updated > 3 months. Please re-open with an update comment if you still need help with this.
