### ISSUE TITLE
προβλημα σε redirect 404 κατα την διαδικασια αγορας

### ISSUE THREAD

**Issue by akoylini** [VivaPayments/API#407]
καλησπερα σας, εχω βαλει στο plugin κανονικα τα url το API κτλπ 
το plugin δουλευει κανονικα μεχρι το σημειο που παταει ο αγοραστης το  κουμπι
για να γινει η χρεωση,τοτε επιστρεφει σε 

http://stromata.gr/?controller=404
 μπορειτε να με βοηθησετε να το φτιαξω?
ευχαριστω θερμα

**Comment by VivaWalletSupport** [comment]
Hello, could you post an URL from the plugin you are using?

**Comment by akoylini** [comment]
Hello Tom this is the plugin 

https://addons.prestashop.com/en/payment-card-wallet/23960-vivapay.html

**Comment by VivaWalletSupport** [comment]
Try following supported plugin: https://github.com/VivaPayments/API/tree/master/Plugins/prestashop/vivawallet

**Comment by akoylini** [comment]
can you tell me where i find download the plugin

**Comment by VivaWalletSupport** [comment]
You can checkout with GIT, or download the complete repository from https://github.com/VivaPayments/API and save the needed files as described in the documentation of the module.

**Comment by akoylini** [comment]
Can you provide me the full link please to download the zip file because i cant see

**Comment by VivaWalletSupport** [comment]
https://github.com/VivaPayments/API/archive/master.zip

**Comment by akoylini** [comment]
ok thank you,so after instalation and setup when i try to proceed the order and accept terms of use i take white page with error 500

**Comment by VivaWalletSupport** [comment]
Can you post a screenshot of the modules settings (hide the api key) and of the source settings? Also verify that the payment source has been activated. Check the Prestashop/PHP error logs for the details of the error.

**Comment by akoylini** [comment]
![viva1](https://user-images.githubusercontent.com/33124346/32160592-10f10254-bd5b-11e7-9725-54accfc90a1f.jpg)
![viva2](https://user-images.githubusercontent.com/33124346/32160593-1118352c-bd5b-11e7-81f2-886bb1a13aad.jpg)

**Comment by akoylini** [comment]
![viva3](https://user-images.githubusercontent.com/33124346/32160643-43406128-bd5b-11e7-8db3-e8efb1f185c7.jpg)

**Comment by VivaWalletSupport** [comment]
Any errors logged and has the payment source been activated?

**Comment by akoylini** [comment]
the payment source is activated.where  i can see errors logged and give you screenshot???

**Comment by akoylini** [comment]
ok i find the error

Fatal error: Uncaught exception 'Exception' with message 'Unable to create order code (The merchant with id 12e3255d-9bb4-41f3-b267-656bbb431297 does not have a source with code '1821' assigned or the source is disabled)' in /home/stromata/public_html/modules/vivawallet/vivawalletold.php:289 Stack trace: #0 /home/stromata/public_html/classes/Hook.php(591): vivawallet->hookPayment(Array) #1 /home/stromata/public_html/classes/Hook.php(548): HookCore::coreCallHook(Object(vivawallet), 'hookpayment', Array) #2 /home/stromata/public_html/controllers/front/ParentOrderController.php(577): HookCore::exec('displayPayment') #3 /home/stromata/public_html/controllers/front/OrderController.php(469): ParentOrderControllerCore->_assignPayment() #4 /home/stromata/public_html/controllers/front/OrderController.php(228): OrderControllerCore->_assignPayment() #5 /home/stromata/public_html/classes/controller/Controller.php(189): OrderControllerCore->initContent() #6 /home/stromata/public_html/classes/Dispatcher.php(367): ControllerCore->run() in /home/stromata/public_html/modules/vivawallet/vivawalletold.php on line 289

**Comment by VivaWalletSupport** [comment]
As the error mentions: The merchant with id 12e3255d-9bb4-41f3-b267-656bbb431297 does not have a source with code '1821' assigned or the source is disabled

**Comment by akoylini** [comment]
![viva3](https://user-images.githubusercontent.com/33124346/32170293-a7cc1242-bd7c-11e7-8623-378d94641775.jpg)
thanks for your reply.as you can see all settings are ok

![1821](https://user-images.githubusercontent.com/33124346/32170271-9cbe1774-bd7c-11e7-8487-2acf0af84a05.jpg)

**Comment by VivaWalletSupport** [comment]
The source is switched off (λειτουργία).

**Comment by akoylini** [comment]
oh my God!!!! thank you.
so after try to make and finish order,in the last step i take this error

http://stromata.gr/modules/vivawallet/success.php?t=404b92b2-1fc6-496e-a5ee-fc0ad1bbe5e6&s=8925775390172604&lang=el-GR
[an error occurred while processing this directive]

but the order is completed

**Comment by VivaWalletSupport** [comment]
What error has been logged?

**Comment by akoylini** [comment]
this is the error

[an error occurred while processing this directive]

**Comment by VivaWalletSupport** [comment]
I meant the error from your Prestashop log, also correct the protocol in your viva source to http, as your site does not use https and see if that solves the problem.

**Comment by akoylini** [comment]
where i can see this log?
and i fix https to http before

**Comment by akoylini** [comment]
ok i find it,so logs prestashop not give me error

**Comment by VivaWalletSupport** [comment]
Check if the directory (755) and the files (644) have the correct file permissions, or mail me access to FTP (tom at hellasboost dot gr).

**Comment by akoylini** [comment]
ok i send you ftp logins

**Comment by VivaWalletSupport** [comment]
Corrected the directory rights on the modules folder from 777 to 755, please try again.

**Comment by akoylini** [comment]
thank you for Best support,all work perfect.
Regards

**Comment by Samcronic** [comment]
i have the same problem but i cannot find any error
