### ISSUE TITLE
Πρόβλημα με το Native Checkout

### ISSUE THREAD

**Issue by sonidelav** [VivaPayments/API#408]
Καλησπέρα σας,

Έχουμε κατεβάσει το κώδικα από το τρέχων repository για την κλάση NativeCheckout την οποία χρησιμοποιούμε σε μία custom πλατφόρμα που δημιουργήσαμε για την εκτέλεση πληρωμής μέσα από την πλατφόρμα με πιστωτική - χρεωστική κάρτα.

Η υλοποίηση έγινε με δοκιμαστικό περιβάλλον στο οποίο δεν αντιμετωπίσαμε πρόβλημα.

Στη συνέχεια κάναμε τις κατάλληλες κινήσεις στον επαγγελματικό λογαριασμό για Πηγές πληρωμών και API key όπου και τα συμπληρώσαμε σωστά.

Στην δοκιμή που κάναμε με πλέον παραγωγικό περιβάλλον στην εκτέλεση της CreateOrder το response στο /api/orders δεν επιστρέφει κανένα αποτέλεσμα, ούτε Headers δεν βλέπουμε.

**Παράδειγμα:**
`Url: https://www.vivapayments.com/api/orders
Post: {"Amount":100,"SourceCode":"4952","MaxInstallments":0,"Email":"----","FullName":"---","MerchantTrns":"\u0391\u03bd\u03b1\u03bd\u03ad\u03c9\u03c3\u03b7 \/ \u0395\u03c0\u03ad\u03ba\u03c4\u03b1\u03c3\u03b7 \u03a3\u03c5\u03bd\u03b4\u03c1\u03bf\u03bc\u03ae\u03c2 CheckThePrice.gr (1 \u039c\u03ae\u03bd\u03b1\u03c2)","CustomerTrns":"\u0391\u03bd\u03b1\u03bd\u03ad\u03c9\u03c3\u03b7 \/ \u0395\u03c0\u03ad\u03ba\u03c4\u03b1\u03c3\u03b7 \u03a3\u03c5\u03bd\u03b4\u03c1\u03bf\u03bc\u03ae\u03c2 CheckThePrice.gr (1 \u039c\u03ae\u03bd\u03b1\u03c2)","Tags":["CheckThePrice Subscription"]}
Response:`

**CURL INFO:**
`Array
(
[url] => https://www.vivapayments.com/api/orders
[content_type] => 
[http_code] => 0
[header_size] => 0
[request_size] => 0
[filetime] => -1
[ssl_verify_result] => 0
[redirect_count] => 0
[total_time] => 0.0043
[namelookup_time] => 0.004208
[connect_time] => 0.052665
[pretransfer_time] => 0
[size_upload] => 0
[size_download] => 0
[speed_download] => 0
[speed_upload] => 0
[download_content_length] => -1
[upload_content_length] => -1
[starttransfer_time] => 0
[redirect_time] => 0
[redirect_url] => 
[primary_ip] => ...
[certinfo] => Array
(
)

[primary_port] => 443
[local_ip] => ....
[local_port] => 50788
)`

Μπορείτε να μας πείτε γιατί συμβαίνει αυτό;

**Σημείωση:**
Η πηγή έχει ενεργοποιηθεί σωστά με πρωτόκολλο HTTPS και domain : checktheprice.gr.

**Comment by kostGX** [comment]
Hello @sonidelav, our technical team is looking into to the issue and we'll get back to you here on Github as soon as we have resolved it.

Thank you for your patience.

**Comment by dmihos** [comment]
Hi @sonidelav 
I just posted below json to https://www.vivapayments.com/api/orders, and got a working OrderCode back.
{code:json}
{
    "Amount": 100,
    "SourceCode":"4952"
}
{code}

Your account is OK.
Provided you authenticate correctly, you should probably check your server's ability to communicate with https://www.vivapayments.com.

**Comment by kostGX** [comment]
@sonidelav Did the above answer your question?
If yes, kindly close the issue.

Thanks!

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
