### ISSUE TITLE
επιστροφη μετα την χρεωση στο site (digitech4all.eu)

### ISSUE THREAD

**Issue by digitech4all** [VivaPayments/API#409]
![viva back](https://user-images.githubusercontent.com/23696118/32178389-3de3c136-bd95-11e7-9d09-09c76c102645.png)
Καλησπερα
Χρησιμοποιω  Viva Payments με ανακατευθυνση σαν payment gateway Eχω δηλώσει στις πηγες πληρωμων της VIVA σαν σελιδα επιτυχημένης και αποτυχημένης συναλλαγης σελιδα επιστροφης digitech4all.eu/index.php?route=payment/viva_payments/callback Εδω και μερικες μερες δεν επιστρεφει στο site μου και κολλαει σε λευκη σελιδα με αποτελεσμα να χρεωνεται ο πελατης απο δευτερες και τριτες προσπαθειες που κανει
παρακαλω για την βοηθεια σας
Φιλικα
Για το digitech4all.eu
Νικος Γεωργιου
email: nick.faser@gmail.com

**Comment by VivaWalletSupport** [comment]
Could you post the URL from the extension you are using?

**Comment by digitech4all** [comment]
https://www.digitech4all.eu/index.php?route=payment/viva_payments/callback&t=dd15ce60-d38c-47f3-803e-3e35ce0babf3&s=7987106808272603&lang=el-GR

**Comment by VivaWalletSupport** [comment]
Please post the URL from where you got the Viva Wallet extension that you are using for OpenCart.

**Comment by digitech4all** [comment]
https://www.vivapayments.com/web/newtransaction.aspx?ref=6497990417072603
or you mean my site www.digitech4all.eu
the extesion is from www.opencartgreece.com  https://eshop.opencartgreece.gr/el/opencart-1-5-x/extensions-yia-pleromes/viva-payments-pleromes-thoseis-yia-to-opencart-1-5-x.html

**Comment by VivaWalletSupport** [comment]
It would be more logic if you would contact the developer (opencartgreece.com). Otherwise use the supported extension from https://github.com/VivaPayments/API/tree/master/Plugins/opencart

**Comment by digitech4all** [comment]
Great, i'll change the extesion
thanks

**Comment by digitech4all** [comment]
did you have a link with zipfilew to download???

**Comment by digitech4all** [comment]
sorry zip files i mean

**Comment by VivaWalletSupport** [comment]
Checkout the file through github and upload them to your store, you can also download th ecomplete repository and save the files you need from here https://github.com/VivaPayments/API/archive/master.zip

**Comment by digitech4all** [comment]
perfect!! 
thanks again!

**Comment by kostGX** [comment]
@digitech4all 
If you don't have any further questions, kindly close the issue. 

Thanks!

![close issue](https://user-images.githubusercontent.com/3908736/32366406-9f02601e-c086-11e7-9f5d-953937cbca69.png)

**Comment by digitech4all** [comment]
Thanks man
everything is ok now!
