### ISSUE TITLE
i got 2 websites under the same vat number

### ISSUE THREAD

**Issue by poulis** [VivaPayments/API#41]
I got 2 different websites that both run cs-cart eshop, that belong to the same company
i want to connect Viva Payments to them. 
should i use the same API Key and how can i understand from which website the payment came?

**Comment by dpnevmatikos** [comment]
Hi there @poulis 
Yes you can use the same API key.
What you need to do to separate the incoming payments is to create two separate Payment Sources, one for each of your websites.
Check [this article](https://support.vivawallet.com/hc/en-us/articles/201251212-What-is-the-definition-of-a-Payment-Source-Do-I-need-to-create-one-) for more info about Payment Sources.

Let me know if that helped.

**Comment by poulis** [comment]
Ευχαριστούμε για την επικοινωνία.

Σύντομα θα έρθουμε σε επαφή μαζί σας.



Thank you for contacting us.

We will reply to your email soon. 



Πουλής Κώστας 

Dixa Audio & Lights

**Comment by poulis** [comment]
Thank you Dimitris
You helped me alot !!

**Comment by dpnevmatikos** [comment]
:+1:
