### ISSUE TITLE
Failed Payments

### ISSUE THREAD

**Issue by meetsos** [VivaPayments/API#410]
Γεια σας, 
η πηγή πληρωμών μου έχει εγκριθεί εδώ και αρκετές ημέρες για την ιστοσελίδα μου (supersmartphones.gr). Προσπαθώ να κάνω δοκιμαστικές παραγγελίες, για να δω οτι όλα λειτουργούν κανονικά, αλλά όλες επιστρέφουν ως αποτυχημένες! Δοκίμασα με τρεις διαφορετικές κάρτες (mastercard, visa, american express) από τρεις διαφορετικές τράπεζες (Eurobank, Alpha Bank, Πειραιώς) με τα ίδια αποτελέσματα κάθε φορά.

Τα μηνύματα που μου ερχονται κατα τις παραγγελίες, είναι αυτής της μορφής:

> Η κατάσταση της παραγγελίας άλλαξε από Εκκρεμεί Πληρωμή σε Αποτυχημένες.

> Ευχαριστούμε για τη προτίμηση.
Η συνναλλαγή σας ήταν ανεπιτυχής και η πληρωμή δεν παραλήφθηκε.
Vivapay Transaction ID: ....

- Χρησιμοποιώ WordPress & WooCommerce στις τελευταίες εκδόσεις (3.2.1 και 4.8.2 αντίστοιχα)
- Χρησιμοποιώ το δικό σας plugin, που παρέχετε εδώ στο github
- Εχω ακολουθήσει κατά γράμμα τα βήματα σας, όπως και άλλες φορές που έχω εγκαταστήσει επιτυχώς το plugin για πελάτες μου, ως προγραμματιστής
- Χρησιμοποιώ redirection και όχι native checkout 
- Η πηγή πληρωμών μου έχει εγκριθεί εδώ και αρκετές ημέρες
- Ο επαγγελματικός μου λογαριασμός είναι ταυτοποιημένος

Τι μπορεί να φταίει; 
Μήπως υπαρχει κάποιο πρόβλημα με το viva account μου;

Ευχαριστώ

**Comment by VivaWalletSupport** [comment]
Could you post a screenshot from your payment source, are you working in the demo environment, was the transaction marked as successful in the Viva wallet account?

**Comment by meetsos** [comment]
Hello,
I am working on a live enviroment and I don't see the transaction in the viva wallet account.

Here is a screenshot of the payment source
https://www.dropbox.com/s/5156wb0eyrq6ufy/Screenshot%202017-11-01%2012.00.37.png?dl=0

By the way, maybe the problem is that in the domain I had "https://supersmartphones.gr" instead of "https://www.supersmartphones.gr"

I update the payment source and I am waiting for approval, to see if there will be any difference.

Thanks

![screenshot 2017-11-01 12 00 37](https://user-images.githubusercontent.com/27548105/32270113-3f6275d4-befd-11e7-873a-06c99f81e7e7.png)

**Comment by meetsos** [comment]
Problem seems to be resolved by checking url from "https://" to "https:/www"

Thanks a lot

**Comment by kostGX** [comment]
Thanks for letting us know @meetsos. Glad you figured it out.
Kindly close the issue.

![close issue](https://user-images.githubusercontent.com/3908736/32366406-9f02601e-c086-11e7-9f5d-953937cbca69.png)
