### ISSUE TITLE
www.kyriazistudios.com

### ISSUE THREAD

**Issue by Vagelis17** [VivaPayments/API#411]
Καλησπέρα σας ήθελα να σας ρωτήσω,
> Εχουμε συνδέσει τα δυο eshops που έχουμε με το ίδιο account της viva με διαφορετικη πηγη. Μετά την αγορά που κάνει ο χρήστης στο kyriazistudios.com του εμφανίζει το ευχαριστηριο μήνυμα απο την άλλη σελίδα που έχουμε συνδεδεμένη σαν πηγή πληρωμών, την seminariaonline.gr
> Με ποιο τροπο μπορούμε μετά την αγορά απο το kyriazistudios.com να τον οδηγεί σε αυτή την σελιδα?
>
> Ευχαριστώ

**Comment by VivaWalletSupport** [comment]
In the plugin settings of both stores check if the correct source code is used and in the viva payment sources check if you have specified the correct return URLs in both sources.

**Comment by kostGX** [comment]
@Vagelis17 Does the above answer your question?
If yes, kindly close the issue. 

Thanks!

![close issue](https://user-images.githubusercontent.com/3908736/32366406-9f02601e-c086-11e7-9f5d-953937cbca69.png)

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
