### ISSUE TITLE
In hikashop module not all available restrictions is available 

### ISSUE THREAD

**Issue by special2k5** [VivaPayments/API#412]
Using the payment of viva in hikashop business the available restrictions is only 
Zone |  Shipping method | Currency |  Prefix | Minimum post code |  Maximum post code and suffix compared for example with paypal payments or other payments like bank deposit where there is also available options like Minimum price |   Maximum price |  Minimum weight  |  Maximum weight |  Minimum volume |  Maximum volume .Will it be any update to hikashop plugin of vivapayment to enable also this restrictions?

**Comment by VivaWalletSupport** [comment]
Basically the focus is on open source e-commerce software, but I cannot rule out that a future update will have these capabilities.

**Comment by kostGX** [comment]
@special2k5 thanks for your question. Does the above answer your question?
If yes, kindly close the issue. 

Thanks!

![close issue](https://user-images.githubusercontent.com/3908736/32366406-9f02601e-c086-11e7-9f5d-953937cbca69.png)

**Comment by special2k5** [comment]
Please add it in your future list for fixing it as it will help a lot.
