### ISSUE TITLE
Download Files

### ISSUE THREAD

**Issue by KostasTimpas** [VivaPayments/API#413]
Καλημέρα,

δεν μπορούμε να κατεβάσουμε τα αρχεία.
Δεν υπάρχει κάπου το download.

Ευχαριστούμε.

**Comment by kostGX** [comment]
@KostasTimpas Goodmorning,
What are you looking to do, exactly?
What do you need to download?

**Comment by KostasTimpas** [comment]
Προσπαθω να κατεβάσω το extension απο εδώ ώστε να το κάνω εγκατάσταση στο magento.

Αυτός είναι ο σύνδεσμος απο τον οποίο προσπαθώ να το κατεβάσω
https://github.com/VivaPayments/API/tree/master/Plugins/magento/magvivawallet

**Comment by kostGX** [comment]
[magento.zip](https://github.com/VivaPayments/API/files/1445803/magento.zip)

Please see attached. I had to download the whole codebase in a ZIP file and then access the Magento plugin.

**Comment by KostasTimpas** [comment]
Thanks a lot!

Have a nice day!
