### ISSUE TITLE
Διασύνδεση με Magento 1.8

### ISSUE THREAD

**Issue by nmihos** [VivaPayments/API#414]
Καλησπέρα,

Υπάρχει κάποιο plugin ή οδηγίες για διασύνδεση με Magento 1.8?

Ευχαριστώ

**Comment by VivaWalletSupport** [comment]
Hello, you can use following:
https://github.com/VivaPayments/API/tree/master/Plugins/magento/magvivawallet

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
