### ISSUE TITLE
Success Order 

### ISSUE THREAD

**Issue by KostasTimpas** [VivaPayments/API#415]
Καλημέρα σας,

σχετικά με το redirect μετά την επιτυχή πληρωμή στο  περιβάλλον της Viva, το url είναι hellaspay/hpay/hpnok/?s=8829191107372609&lang=el-GR
και η σελίδα είναι κενή.

Πως μπορώ στη σελίδα να τοποθετήσω περιεχόμενο επιτυχούς παραγγελίας ή να κάνει το redirect στο success που υπάρχει by default?

Ευχαριστώ

**Comment by VivaWalletSupport** [comment]
Could you post the URL from the plugin you are using and the URL from your website?

**Comment by KostasTimpas** [comment]
You send me the plugin with zip but the url is this
https://github.com/VivaPayments/API/tree/master/Plugins/magento/magvivawallet

eshop
https://sexbijoux.gr

**Comment by VivaWalletSupport** [comment]
Can you post a screenshot of your viva payment source settings?

**Comment by KostasTimpas** [comment]
do you need this?
![viva](https://user-images.githubusercontent.com/13455642/32502016-4997457c-c3e2-11e7-84a4-63dbedc108cb.JPG)

**Comment by VivaWalletSupport** [comment]
You should use the return URLs in the payment source as instructed in the readme file:

Success page: vivawallet/hpay/hpok/
Failure page: vivawallet/hpay/hpnok/
