### ISSUE TITLE
Bad request - WooCommerce & Viva Wallet Plugin

### ISSUE THREAD

**Issue by TDGR** [VivaPayments/API#417]
Καλησπέρα σας,

Merchant ID : 2afc6b93-6708-41a1-a0b6-61aac5cd3bed

Έχουμε δημιουργήσει μια νέα πηγή (4880) που αφορά την ιστοσελίδα nutracan.gr με το όνομα Nutracan η οποία έχει από εσάς ενεργοποιηθεί και είναι σε λειτουργία με τα εξής στοιχεία.

Η ιστοσελίδα μας έχει κατασκευαστεί σε WordPress (v4.8.3) και το WooCommerce (v3.2.3). Επιλέξαμε να χρησιμοποιήσουμε το Viva Wallet ως κύρια και μοναδική πύλη συναλλαγών
και στη συνέχεια κατασκευάσαμε και εγκαταστήσαμε το plugin που εσείς μας προτείνατε https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce.
Ακολουθήσαμε τις οδηγίες που αναφέρονται στο github. 

Το πρόβλημα.

Δοκιμάζοντας στο frontend  να κάνουμε αγορά, είτε έχοντας επιλεγμένο το test mode είτε όχι, αφού ολοκληρώσουμε όλα τα βήματα φτάνοντας στο checkout πατάμε “Ολοκλήρωση Αγοράς”
και γίνεται το εξής:
Δημιουγείται στιγμιαία το λινκ http://nutracan.gr/checkout/?key=wc_order_5a01afc8ab186&order-pay=1030
και στη συνέχεια μας κάνει redirect σε κενό ref (https://www.vivapayments.com/web/newtransaction.aspx?Ref=) με μήνυμα “Bad Request”.

Μπορείτε σας παρακαλούμε να μας καθοδηγήσετε ώστε να διορθώσουμε όποιο τυχόν λάθος έχουμε κάνει κατά την παραμετροποίηση;

Ευχαριστώ

**Comment by TDGR** [comment]
Live environment

**Comment by VivaWalletSupport** [comment]
Can you post 3 screenshots, plugin settings (obfuscate API Key), viva source settings, viva sources listing overview.

**Comment by TDGR** [comment]
Sure,

![plugin_backend](https://user-images.githubusercontent.com/7686974/32571009-b08ac654-c4ce-11e7-8e6d-1a6d2f4a6ce8.jpg)
![screenshot](https://user-images.githubusercontent.com/7686974/32571042-cdb4973c-c4ce-11e7-9618-17a73bc3d8d0.png)
![screenshot nutracan](https://user-images.githubusercontent.com/7686974/32571044-cdd9f3b0-c4ce-11e7-8b69-45c7c346c2af.png)

P.S. I can send you access to our website if needed.

Thank you.

**Comment by VivaWalletSupport** [comment]
Send me ftp and admin credentials to tom at hellasboost dot gr to have a look.

**Comment by VivaWalletSupport** [comment]
Getting following error with cURL:
curl error: Protocol "https" not supported or disabled in libcurl

Check with your hosting provider..

**Comment by TDGR** [comment]
Hello,

Issue has been fixed. I replaced cURL with cURL-SSL and it works perfectly.

Thank you for your great support!
