### ISSUE TITLE
Dummy Enviroment for Tests - VivaWallet Demo

### ISSUE THREAD

**Issue by athinaionfos** [VivaPayments/API#418]
Στο Αγγλικό web site σας υπάρχει και μια Demo μορφή του VivaWallet. Πάρα πολύ χρήσιμο αυτό
και με μια Dummy credit card του στύλ 4111 1111 1111 1111. Ωραιότατη κατάσταση!!!!
Προσπάθησα να φτιάξω ένα account ... και μου ζητάει ταυτοποίηση!!! Ωραίο Demo!!!!! Απίστευτος Dummy account!!!!

Επειτα αγόρασα μια κάρτα VivaWallet προσωπική για να την χρησιμοποιήσω για δοκιμές με το POS και τον επαγγελματικό λογαριασμό.
Και με μεγάλη έκπληξη είδα ότι και σε αυτήν υπάρχουν χρεώσεις!!!! Μου φαίνεται κουφό!!! Πως γίνεται αυτό?
Πως ένας άνθρωπος που θέλει να κάνει διάφορες δοκιμές δεν θα χρεωθεί? Πως θα στήσει κάτι στο Ιντερνετ είτε παροχές υπηρεσιών είτε πώληση προϊόντως εάν πρώτα δεν ξέρει ότι αυτό που έχει φτιάξει είναι φιλικό, ασφαλές και σωστό για τον πελάτη;

Περιμένω απάντήση σας

Με εκτίμηση

**Comment by Sotiris-k** [comment]
Δεν χρειάζεσαι ταυτοποίηση για το demo κι ας το λέει αυτό. Απλά αγνόησέ το

Χρησιμοποιήσε την 4111 1111 1111 1111 και το 111 για CVV και μπορείς να κάνεις δοκιμές.

(Δεν είμαι υπάλληλος της Viva. Απλά έχω κάνει την υλοποίηση και ξέρω)

**Comment by athinaionfos** [comment]
Eυχαριστώ πάρα πολύ κε. Σωτήρη.Εκτιμώ πάρα πολύ την βοήθειά σας.Είναι πολύ σημαντική για εμένα και την ομάδα μου.
Νά'στε πολύ καλά, να έχετε ένα ξεκουραστο ΣΚ
 Χριστοδούλου Γεώργιος Jagaro
Πρόεδρος Κοινωνικής Συνεταιριστικής ΕπιχείρησηςΑθηναίων ΦωςΚέντρο Ολιστικής Ανάπτυξης και Θεραπείας
Δανίλη 3, 11744, Ν. Κόσμος, Αθήναemail: athinaionfos@gmail.com
Ιστοσελίδα: www.athinaionfos.grFB:https://www.facebook.com/athinaionfos

Τηλ: 210 525 6729, 697 365 4844 

    Στις 10:54 π.μ. Παρασκευή, 10 Νοεμβρίου 2017, ο/η Sotiris Katsaniotis <notifications@github.com> έγραψε:
 

 Δεν χρειάζεσαι ταυτοποίηση για το demo κι ας το λέει αυτό. Απλά αγνόησέ τοΧρησιμοποιήσε την 4111 1111 1111 1111 και το 111 για CVV και μπορείς να κάνεις δοκιμές.(Δεν είμαι υπάλληλος της Viva. Απλά έχω κάνει την υλοποίηση και ξέρω)—

**Comment by kostGX** [comment]
Ευχαριστούμε @Sotiris-k για την προσφορά βοήθειας στην κοινότητα των devs. 
@athinaionfos παρακαλώ αν έχετε εξυπηρετηθεί να κάνετε close το issue.

Ευχαριστούμε πολύ.

![close issue](https://user-images.githubusercontent.com/3908736/32366406-9f02601e-c086-11e7-9f5d-953937cbca69.png)

**Comment by athinaionfos** [comment]
Eυχαρίστως να το κάνω!!
Καλό ΣΚ σε όλους σας!
Ευχαριστώ και πάλι!
