### ISSUE TITLE
"Requested by" field in Payment Email

### ISSUE THREAD

**Issue by Sotiris-k** [VivaPayments/API#419]
What is the parameter which should be filled in the transaction that is responsible for this field in the email?

![image 001](https://user-images.githubusercontent.com/4454324/32652817-43e80502-c60e-11e7-9953-47f9ffcf1ca2.png)

Thanks

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
