### ISSUE TITLE
GetTransactions call  more

### ISSUE THREAD

**Issue by VagKolokotronis** [VivaPayments/API#42]
Καλημέρα 
Σε συνέχεια προηγούμενου post που έχει κλείσει 

1) Ερώτηση 
Για κάθε μια επιτυχημένη πληρωμή το σύστημα σας επιστρέφει στην σελίδα που έχουμε δηλώσει ( σελίδα επιτυχημένης συναλλαγής ) . Υπάρχει κάποια περίπτωση που το σύστημα σας επιστρέφει στην σελίδα επιτυχημένης συναλλαγής χωρίς η συναλλαγή να είναι επιτυχημένη = έχει γίνει η χρέωση ?

Όσο αφορά την επιλογή Ακύρωσης της πληρωμής είναι μια πρόταση που θα μπορούσε να κάνει το σύστημα σας ποιο φιλικό και σωστό. Θα μπορούσατε να το προωθήσετε σαν ιδέα στο αντίστοιχο τμήμα που ασχολείται με την υλοποίησης του συστήματος σας.

2) 
1) Η απάντηση λάθους ErrorCode":400, μπορείτε να μου πείτε τι σημαίνει ?
2) Έχετε κάποια παράδειγμα κλήσης GetTransactions call σε κάποια γλώσσα προγραμματισμού ? Θα με βοηθούσατε εάν είχατε ένα παράδειγμα σε γλώσσα classic asp. Στο github δεν υπάρχουν παραδείγματα GetTransactions η τουλάχιστον εγώ δεν έχω βρει κάτι.

Σας επισυνάπτω τον κώδικα της σελίδας επιτυχημένης πληρωμής /bp/bankViva_ok.asp

Και όπως έρχεται από το σύστημα σας η επιστροφή στην σελίδα επιτυχημένης πληρωμής

http://www.euroalarm.2easy.gr/bp/bankViva_ok.asp?t=87b27951-12f5-4253-bdff-4e43ee7b9bf3&s=8243103019172607&lang=el-GR

bankViva_ok.asp

<%if sxNobody then%>

<%end if
openConn

function NzInt(int)
NzInt = int
if isNull(int) OR isEmpty(int) OR lenb(int) = 0 OR Not isNumeric(int) then
NzInt = 0
end if
end function

Dim radioContinue
radioContinue = True
Dim radioVivaReturn 
radioVivaReturn = True

Dim OrderCode, strTransactionID, strLang 
OrderCode = request.querystring("s")
strTransactionID = request.querystring("t")
strLang = request.querystring("Lang")

if OrderCode = "" then radioVivaReturn = False
if radioVivaReturn then
if radioContinue then
sql = "SELECT * FROM PB_Viva WHERE InUse = True "
set rs = conn.execute(sql)
if not rs.eof then
strMerchanID = rs("MerchanID")
strAPIKey = rs("APIKey")
strPublicKey = rs("PublicKey")

strVivaUrltTansaction = rs("VivaUrlTransaction")
strVivaUrlGetTransaction = rs("VivaUrlGetTransaction")
radioContinue = True
else
radioContinue = False
end if
rs.close
set rs = nothing
end if

if radioContinue then
    Set http = Server.CreateObject("Msxml2.ServerXMLHTTP.3.0")
    http.open "GET", strVivaUrlGetTransaction, False', strMerchanID, strAPIKey 
    http.setRequestHeader "Content-Type", "application/x-www-form-urlencoded"
    http.setRequestHeader "Authorization", "Basic "&Base64Encode(strMerchanID&":"&strAPIKey)
    response.write "ordercode=" & ordercode & " strTransactionID=" & strTransactionID & " MerchanID=" & strMerchanID &" APIkey=" & strAPIKey & " url=" & strVivaUrlGetTransaction &"<br>"
    http.send("ordercode=" & OrderCode )
response.write http.responsetext
Response.End

end if
%>

και η απάντηση που παίρνω είναι 
α) τα στοιχεία που χρησιμοποιώ είναι τα παρακάτω για την κλήση

response.write "ordercode=" & ordercode & " strTransactionID=" & strTransactionID & " MerchanID=" & strMerchanID &" APIkey=" & strAPIKey & " url=" & strVivaUrlGetTransaction &"
"

ordercode=8243103019172607 
strTransactionID=87b27951-12f5-4253-bdff-4e43ee7b9bf3 MerchanID=f9f3f5f4-f222-48c9-be5a-ea6ae727e88a 
APIkey=;d]z7: 
url=http://demo.vivapayments.com/api/transactions/?

response.write http.responsetext

{"Transactions":[],"ErrorCode":400,"ErrorText":"Empty options","TimeStamp":"2016-02-10T10:49:03.228726+02:00"}

Αυτό που υποψιάζομαι ότι είναι το λάθος είναι ότι η τιμή που στέλνετε στο σύστημα σας με την εντολή http.send("ordercode=" & OrderCode ) Το OrderCode έρχεται σαν sting και φυσικά στέλνετε σαν sting ενώ εσείς το εξετάζετε σαν Int64. H μετατροπή του με την εντολή CDbl OrderCode = CDbl(OrderCode) το αλλάζει από 8243103019172607 σε 8.24310301917261E+15 η εντολή OrderCode = Cint(OrderCode) κάνει Overflow: 'cInt' Δεν έχω βρει τρόπο να μετατρέψω το string σε int64 μήπως ξέρετε εσείς κάποιο τρόπο ?

Πραγματικά δουλεύει η επιλογή GetTransactions call στο σύστημα σας ? Είναι κάποια εφαρμογή που την χρησιμοποιεί ?

Εάν δεν μπορείτε να με πληροφορήσετε εσείς ίσως υπάρχει κάποιος άλλος στο τεχνικό τμήμα που ίσως θα μπορούσε ? ή μήπως θα πρέπει να απευθυνθώ στον υπεύθυνο του τεχνικού τμήματος της vivawallet.

Ευχαριστώ

**Comment by dmihos** [comment]
Καλησπέρα

Για τα επι μέρους ερωτήματά σας

1. Όχι, το redirect στο success url γίνεται μόνο σε περίπτωση πετυχημένης χρέωσης
2. Error 400 σημαίνει ότι κάποια παράμετρος(παράμετροι) στο request που στέλνετε είναι λάθος. Πχ missing OrderCode, invalid types κλπ
3. Παρότι οι γνώσεις μας σε asp/vb είναι περιορισμένες, νομίζω η function που ψάχνετε για cast σε Long (το OrderCode είναι typed Long) είναι η **CLng**

**Comment by VagKolokotronis** [comment]
Καλησπέρα
Ευχαριστώ για το 1) Αυτό σημαίνει ότι δεν χρειάζεται να κάνουμε επιπλέον έλεγχο GetTransactions call 

3) το CLng παράγει Overflow: 'CLng'  The CLng function converts an expression to type Long
The value must be a number between -2147483648 and 2147483647
Όπως αναφέρω παραπάνω οι μόνες εντολές είναι CDbl(OrderCode) αλλά αλλάζει το 8243103019172607 σε 8.24310301917261E+15

1) Έκανα και δοκιμές σύμφωνα με το 
https://github.com/VivaPayments/API/wiki/GetTransactions

σε date=2012-12-24 ?clearancedate=2012-12-24 κλπ

GET /api/transactions/b1a3067c-321b-4ec6-bc9d-1778aef2a19d
GET /api/transactions/?ordercode=175936509216
GET /api/transactions/?date=2012-12-24
GET /api/transactions/?clearancedate=2012-12-24

με το ίδιο αποτέλεσμα λάθους 
{"Transactions":[],"ErrorCode":400,"ErrorText":"Empty options","TimeStamp":"2016-02-10T10:49:03.228726+02:00"}

2) Μπορείτε να κοιτάξετε και να με ενημερώσετε τι ακριβώς ελέγχει η κλήση σε /api/transactions/?

3) Έχετε κάποιο παράδειγμα χρήσης GetTransactions call σε οποιαδήποτε γλώσσα ?. Δεν υπάρχει τίποτε στο github στα παραδείγματα που έχετε. Μήπως θα ήταν καλό να ανεβάσετε ένα τέτοιο παράδειγμα που να δουλεύει.  

Ευχαριστώ

**Comment by dmihos** [comment]
```vb
baseUrl = "http://demo.vivapayments.com/api/transactions/"

dim MerchantId
MerchantId = "XXXXXXXXXXXXXXXXXXXXXXX"
dim ApiKey
ApiKey = "yyyyy"

Set http = Server.CreateObject("Msxml2.ServerXMLHTTP.3.0")
http.open "GET", baseUrl & "?OrderCode=8243103019172607", False
http.setRequestHeader "Content-Type", "application/x-www-form-urlencoded"
http.setRequestHeader "Authorization", "Basic "&Base64Encode(MerchantId & ":" & ApiKey)

http.send()

response.write http.responsetext

```

Θα πρέπει να βάλετε τα στοιχεία του προφίλ σας.

Η κλήση στη GetTransactions καλό θα είναι να γίνεται **πάντα**, ακόμα και στην περίπτωση του redirect στο success url σας, για λόγους ασφαλείας.

**Comment by VagKolokotronis** [comment]
Καλημέρα 
Σας ευχαριστώ πολύ για την πληροφορία. Τώρα δουλεύει η λειτουργία και σε μένα. Θα μπορούσατε να το ανεβάσετε στα παράδειγμα στο github.com και σίγουρα θα βοηθήσει και σε άλλους που θα έχουν το ίδιο πρόβλημα. 
Ευχαριστώ
