### ISSUE TITLE
Redirection does not work!

### ISSUE THREAD

**Issue by athinaionfos** [VivaPayments/API#420]
Καλησπέρα σας!

(Πρόκειτα για τον Επαγγελματικό Λογαριασμό της Συνεταιριστικής Επιχείρησης - Αθηναίων Φως)

Exω κάνει ένα test button στην Ιστοσελίδα: http://thetahealing.education/synedries
Βγαίνει η σελίδα της VivaWallet Payment Services. Βάζω όλα τα στοιχεία. Περνάει και πληρώνεται/χρεώνεται κανονικά.
Βγαίνει το μήνυμα: !success Η πληρωμή έγινε με επιτυχία.
Μέχρι εδώ μια χαρά. Ομως δεν γυρνάει πίσω στην ιστοσελίδα. Μένει εκεί!

Πηγές πληρωμών: Κωδικός: 4324 - H Ιστοσελίδα του Theta Healing: κατάσταση Ενεργή
(ονομα domain: www.thetahealing.education, Integration method: redirection 
Url επιτυχημένης συναλλαγής: http://thetahealing.education/eyxaristoyme-para-poly-gia-thn-synallagh-sas
Url αποτυχημένης συναλλαγής: http://thetahealing.education/a8hnaiwn-fws

Eυχαριστώ και αναμένω την απάντησή σας

Με εκτίμηση

**Comment by dmihos** [comment]
Καλησπέρα σας
Τα buttons δεν υποστηρίζουν επιστροφή στο url του εμπόρου.
Αυτό είναι functionality του [Redirect checkout](https://github.com/VivaPayments/API/wiki/Redirect-Checkout).
Ευχαριστούμε για την επικοινωνία

**Comment by athinaionfos** [comment]
Eυχαριστώ πάρα πολύ για την διευκρίνηση και απάντηση!Υπάρχει κάποιο tuturial video πάνω σε αυτό (Redirct checkout);

Mε εκτίμηση Χριστοδούλου Γεώργιος Jagaro
Πρόεδρος Κοινωνικής Συνεταιριστικής ΕπιχείρησηςΑθηναίων ΦωςΚέντρο Ολιστικής Ανάπτυξης και Θεραπείας
Δανίλη 3, 11744, Ν. Κόσμος, Αθήναemail: athinaionfos@gmail.com
Ιστοσελίδα: www.athinaionfos.grFB:https://www.facebook.com/athinaionfos

Τηλ: 210 525 6729, 697 365 4844 

    Στις 2:22 μ.μ. Πέμπτη, 16 Νοεμβρίου 2017, ο/η dmihos <notifications@github.com> έγραψε:
 

 Καλησπέρα σας
Τα buttons δεν υποστηρίζουν επιστροφή στο url του εμπόρου.
Αυτό είναι functionality του Redirect checkout.
Ευχαριστούμε για την επικοινωνία—

**Comment by kostGX** [comment]
@athinaionfos παρακαλώ δείτε εδώ: https://github.com/VivaPayments/API/wiki/Redirect-Checkout 

Είναι βήμα-βήμα οδηγός για να υλοποιήσετε την Redirect Checkout λύση.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
