### ISSUE TITLE
Σετάρισμα σε Woocommerce

### ISSUE THREAD

**Issue by alexandramavridou** [VivaPayments/API#422]
Καλησπέρα, έχω το εξής πρόβλημα:

Το site μου είναι σε woocommerce και δεν μπορώ να το κάνω να διαβάσει το viva wallet μου.

Έχω βάλει τα πάντα σωστά από ότι πιστεύω αλλά μου βγάζει την παρακάτω οθόνη όταν κάποιος πάει να κάνει συναλλαγή με viva wallet: 

![001](https://user-images.githubusercontent.com/33688678/32833717-802c31e8-ca08-11e7-911a-1a87dd75dbb7.jpg)

Τι μπορώ να κάνω, έχω ακολουθήσει όλα τα βήματα!!

**Comment by VivaWalletSupport** [comment]
Seems you are not using the plugin from github (https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce), in that case I would suggest to contact the plugin developer.

**Comment by alexandramavridou** [comment]
Greetings, I am using this plugin you have said. I’ve download each file and uploaded to my site. 

I even set up everything according to the readme file.

Στάλθηκε από το iPhone μου

15 Νοε 2017, 15:11, ο χρήστης «Tom van der Veer <notifications@github.com>» έγραψε:

**Comment by VivaWalletSupport** [comment]
Unless you also changed some code/texts in the plugin I do not recognize the shown sentence "wrong merchant credentials or the API is not working".

**Comment by alexandramavridou** [comment]
No I didn't do anyhting but to collect the files in the order I've download
them, put them into a folder with the given name and uploaded to my host.
Then I activated it, I've putted the Merchand ID, API Key and Code ID given
by viva wallet. I can't understand why I get this message.

2017-11-15 17:16 GMT+02:00 Tom van der Veer <notifications@github.com>:

**Comment by VivaWalletSupport** [comment]
Can you email ftp and admin to tom at hellasboost dot gr to have a look?

**Comment by alexandramavridou** [comment]
Greetings, I've just send them.

**Comment by VivaWalletSupport** [comment]
You where using a 3rd party plugin and you did not install the supported plugin correctly.  http://prntscr.com/hcwmhj

**Comment by alexandramavridou** [comment]
i've downloaded the certain folder that you gave me (https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce)
I have to reinstall it?

**Comment by alexandramavridou** [comment]
is there a zip file ready for that so I don't download file by file?

**Comment by VivaWalletSupport** [comment]
Please check your site, I already installed and configured the plugin for you.

**Comment by alexandramavridou** [comment]
There is no viva payment in the woocommerce!?

**Comment by alexandramavridou** [comment]
I can't understand

**Comment by alexandramavridou** [comment]
Can you please help me, I can't find the plugin into woocommerce.

**Comment by VivaWalletSupport** [comment]
I saw that you uploaded again the wrong files, I installed and configured it again, don't make any changes, the plugin should work fine. Please close this ticket after checking.

**Comment by alexandramavridou** [comment]
Thank you thank you. Realy thank you a lot I won't make any changes.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
