### ISSUE TITLE
Viva: Αδυναμία σύνδεσης στο demo περιβάλλον

### ISSUE THREAD

**Issue by vickyfal** [VivaPayments/API#423]
Καλησπέρα,

Είχα δημιουργήσει πριν μερικούς μήνες ένα λογαριασμό στο demo περιβάλλον (https://demo.vivapayments.com), για να κάνω κάποιες δοκιμές με το VivaPayments API.

Προσπαθώ εδώ και λίγες μέρες να συνδεθώ ξανά στο demo, αλλά μάλλον δε θυμάμαι σωστά τον κωδικό μου και δεν μπορώ να συνδεθώ. 
Όταν πατάω στο "Ξέχασα τον κωδικό μου" μου γράφει πως θα λάβω ένα mail με οδηγίες επαναφοράς του κωδικού, αλλά δεν έχω λάβει ακόμα κανένα mail. Έλεγξα και το spam/junk folder μήπως είχε πάει εκεί, αλλά τίποτα.
Δοκίμασα να φτιάξω και ένα νέο λογαριασμό με τον ίδιο αριθμό κινητού τηλεφώνου, αλλά όπως ήταν φυσικό δε με αφήνει να προχωρήσω γιατί υπάρχει ήδη ο προηγούμενος λογαριασμός με αυτόν τον αριθμό. 

Θα μπορούσατε μήπως να με βοηθήσετε με κάποιον τρόπο;

**Comment by dmihos** [comment]
Καλημέρα
Ξαναδοκιμάστε, αν θέλετε.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
