### ISSUE TITLE
Δόσεις μέσω vivapayments στο magento

### ISSUE THREAD

**Issue by dkontod** [VivaPayments/API#424]
Καλημέρα. 
Έχω ένα ηλεκτρονικό κατάστημα στο magento community 1.9 και δέχομαι πληρωμές με πιστωτικές κάρτες μέσω viva redirect.
Πως μπορώ να ορίσω την δυνατότητα για πληρωμή με δόσεις;

Ευχαριστώ

**Comment by dkontod** [comment]
Hello Tom.
My magento version is 1.9.2.4 
I have Infortis 2.3.1 theme installed
I have done everything you suggest, but no dropdown shows to the customer at the front end nor at the viva wallet payent page.
What I am doing wrong?
![image](https://user-images.githubusercontent.com/24634785/33133029-1eb3f3aa-cfa4-11e7-995e-3f221dc19608.png)

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
