### ISSUE TITLE
Προβλημα με Πληρωμή

### ISSUE THREAD

**Issue by forsaken1981** [VivaPayments/API#425]
Καλή σας ημέρα,

Στον λογαριασμό με username: 6978350865 έχει γίνει εχθές μία πληρωμή με VIVA.  Οι ρυθμίσεις στο prestashop είναι κανονικές μίας και έχει ελεχθεί το σύστημα. Μπορείτε να μου πείτε τι φταίει?

Και το Merchant ID είναι το σστό όπως θα δείτε παρακάτω αλλά και το VIVA API key

Inline image 1

**Comment by VivaWalletSupport** [comment]
Could you provide some details on what payment module is used?

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
