### ISSUE TITLE
Maximum characters for fields in new order

### ISSUE THREAD

**Issue by PKDataGreece** [VivaPayments/API#426]
Hello. 

Today one of our customer tried to place an order using two phone numbers during the order creation. This resulted in an order exception. After cutting off the extra phone number the order was processed successfully.

Are there any details about the maximum number allowed for characters in the optional parameters for the Create Order API method? I see the available parameters in [documentation](https://github.com/VivaPayments/API/wiki/Optional-Parameters), however I do not know the maximum characters (for example in the "phone" parameter).

Thank you very much

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
