### ISSUE TITLE
"Pay with Viva Wallet" Closed popup by user

### ISSUE THREAD

**Issue by DimitraPappa** [VivaPayments/API#427]
Καλησπέρα, 
Χρησιμοποιώ το Pay with Viva Wallet Button. Πατώντας το, εμφανίζεται το popup της Πληρωμής. Εκεί δημιουργώ στη βάση ένα OrderID πριν το Transaction. Θέλω να πιάσω την περίπτωση όταν ο χρήστης κλείνει το popup από το "X" (χωρίς να έχει πατήσει το κουμπί "Πληρωμή") ,  και να  σβήνω την παραγγελία από τη βάση μου. Υπάρχει τρόπος να πιάσω αυτό το event?

**Comment by dpnevmatikos** [comment]
@DimitraPappa δυστυχώς το Pay with Viva Wallet button δεν δίνει τέτοιο event. 
Και να υπήρχε όμως τέτοιο event, θα ήταν κάπως "επίφοβο" να χρησιμοποιηθεί με τον τρόπο που σκέφτεστε καθώς πρέπει να λάβετε υπόψιν οτι ο χρήστης έχει τη δυνατότητα να το ανοίξει και πάλι.

Συνεπώς δεν είναι ασφαλής τρόπος για να ξέρετε πότε ο χρήστης αποφάσισε να μην πληρώσει.

Αν παρ'όλα αυτά θέλετε να προχωρήσετε στη συγκεκριμένη υλοποίηση τότε θα μπορούσατε να ανοίγετε παραγγελίες με συγκεκριμένο [PaymentTimeout](https://github.com/VivaPayments/API/wiki/Optional-Parameters) και να τις διαγράφετε-ακυρώνετε και εσείς στο σύστημα σας μόλις παρέλθει το time out αυτό.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
