### ISSUE TITLE
Συνεργάζεται το VivaWallet με το Typeform?

### ISSUE THREAD

**Issue by athinaionfos** [VivaPayments/API#429]
Kαλησπέρα σας,

Θα ήθελα να ρωτήσω εαν το VivaWallet συνεργάζεται με το Typeform και πως.
Aπό το documentation του Typeform βλέπω ότι συνεργάζεται με πολλές εφαρμογές. Συνεργάζεται δε με native τρόπο με το Stripe, το οποίο δεν υποστηρίζεται στην Ελλάδα. 
Yπάρχει κάποιος τρόπος συνεργασίας με το Typeform?

Eυχαριστώ πάρα πολύ

Γιώργος Χριστοδούλου

**Comment by kostGX** [comment]
@athinaionfos διαβάζοντας το documentation το Typeform έχει κάνει integrate μόνο με Stripe. Θα το εξετάσουμε το θέμα και επανέλθουμε.

Θα μπορούσατε να μαζέψετε ενδιαφερόμενους με την Typeform και στη συνέχεια να αποστείλετε στα leads σας μία Viva Wallet Ειδοποίηση Πληρωμής με σκοπό να δεχθείτε την πληρωμή σας και δίνοντας στον πελάτη σας εναλλακτικούς τρόπους πληρωμής.

Διαβάστε σχετικά [εδώ](https://support.vivawallet.com/hc/el/articles/200831662-Πώς-λειτουργούν-οι-ειδοποιήσεις-πληρωμών-) ή [δείτε το σχετικό βίντεο](https://www.youtube.com/watch?v=LNM-VU0HjPA&feature=youtu.be).

**Comment by kostGX** [comment]
@athinaionfos καλησπέρα σας,

Μετά από επικοινωνία με την Typeform μου επιβεβαίωσαν πως υποστηρίζουν μόνο το Stripe ώς Payment Processor.

Συνεπώς κλείνω το issue αφού δώθηκε μια οριστική απάντηση.

**Comment by athinaionfos** [comment]
Σας ευχαριστώ πάρα πολύ!!!!!Νομίζω πιο ξεκάθαρη απάντηση .... δεν γίνεται!!!!
Νά'στε πολύ καλά!!! Εκτιμώ την βοήθειά σας!!!!

 Χριστοδούλου Γεώργιος Jagaro
Πρόεδρος Κοινωνικής Συνεταιριστικής ΕπιχείρησηςΑθηναίων ΦωςΚέντρο Ολιστικής Ανάπτυξης και Θεραπείας
Δανίλη 3, 11744, Ν. Κόσμος, Αθήναemail: athinaionfos@gmail.com
Ιστοσελίδα: www.athinaionfos.grFB:https://www.facebook.com/athinaionfos

Τηλ: 210 525 6729, 697 365 4844 

    Στις 5:40 μ.μ. Τρίτη, 28 Νοεμβρίου 2017, ο/η Kostas Xiradakis <notifications@github.com> έγραψε:
 

 @athinaionfos καλησπέρα σας,Μετά από επικοινωνία με την Typeform μου επιβεβαίωσαν πως υποστηρίζουν μόνο το Stripe ώς Payment Processor.Συνεπώς κλείνω το issue αφού δώθηκε μια οριστική απάντηση.—
