### ISSUE TITLE
Internal Server error API 

### ISSUE THREAD

**Issue by Orestis93** [VivaPayments/API#430]
Hello, i am keep getting these error messages.
API Call failed! The error was: Internal Server Error
Notice: Undefined variable: resultObj in C:\xampp\htdocs\ContactForm\form.php on line 69

Notice: Trying to get property of non-object in C:\xampp\htdocs\ContactForm\form.php on line 69

Notice: Undefined variable: resultObj in C:\xampp\htdocs\ContactForm\form.php on line 70

I have not set the public key anywhere and i have not created new source.

Here is my code which i get it straight from the tutorial:

`<html>
<head>
<style>
td{
	
	border-style:ridge;
	border-color:#ce0202f7;
}
.main{
	background-color:white;
	border-style:double;
	border-color:#d00000;
	max-width:800px;
	margin-left:20%;
}
</style>
<?php 
// Get the values from the $_POST array:
    $persons = $_POST['u_persons'];
    $persons2 = $_POST['u_persons2'];
    $persons3 = $_POST['u_persons3'];
	$persons4 = $_POST['u_persons4'];
    $price = 120;
    $price2 = 50;
    $price3 = 35;
	$price4 = 50;
// Calculate the total:
  $Amount = 15000;//($persons * $price)+($persons2 * $price2)+($persons3 * $price3)+($persons4 * $price4);
// The POST URL and parameters
$request =  'http://demo.vivapayments.com/api/orders';	// demo environment URL
//$request =  'https://www.vivapayments.com/api/orders';	// production environment URL
// Your merchant ID and API Key can be found in the 'Security' settings on your profile.
$MerchantId = 'e6159d9d-d28f-4649-afc3-d24450186129';
$APIKey = '123abc!@'; 	
//Set the Payment Amount
//$Amount = 100;	// Amount in cents
//Set some optional parameters (Full list available here: https://github.com/VivaPayments/API/wiki/Optional-Parameters)
$AllowRecurring = 'false'; // This flag will prompt the customer to accept recurring payments in tbe future.
$RequestLang = 'en'; //This will display the payment page in English (default language is Greek)
$Source = 'Default'; // This will assign the transaction to the Source with Code = "Default". If left empty, the default source will be used.
$postargs = 'Amount='.urlencode($Amount).'&AllowRecurring='.$AllowRecurring.'&RequestLang='.$RequestLang.'&SourceCode='.$Source;
// Get the curl session object
$session = curl_init($request);
// Set the POST options.
curl_setopt($session, CURLOPT_POST, true);
curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
curl_setopt($session, CURLOPT_HEADER, true);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
// Do the POST and then close the session
$response = curl_exec($session);
// Separate Header from Body
$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
$resHeader = substr($response, 0, $header_len);
$resBody =  substr($response, $header_len);
curl_close($session);
// Parse the JSON response
try {
	if(is_object(json_decode($resBody))){
	  	$resultObj=json_decode($resBody);
	}else{
		preg_match('#^HTTP/1.(?:0|1) [\d]{3} (.*)$#m', $resHeader, $match);
				throw new Exception("API Call failed! The error was: ".trim($match[1]));
	}
} catch( Exception $e ) {
	echo $e->getMessage();
}
if ($resultObj->ErrorCode==0){	//success when ErrorCode = 0
	$orderId = $resultObj->OrderCode;
	echo 'Your Order Code is: <b>'. $orderId.'</b>';
	echo '<br/><br/>';
	echo 'To simulate a successfull payment, use the credit card 4111 1111 1111 1111, with a valid expiration date and 111 as CVV2.';
	echo '</br/><a href="http://demo.vivapayments.com/web/newtransaction.aspx?ref='.$orderId.'" >Make Payment</a>';
}
	
else{
	echo 'The following error occured: ' . $resultObj->ErrorText;
}
  // Address error handling, if you want.

  
  
  

  
  
  
  // Print out the results:
 // print "<div>You have selected to
 //   purchase:<br />, the total
 //   cost is
//  $<span class=\"number\">$total
//    </span>.<br />
// </div>";
//require 'connection.php';
//$conn    = Connect();
//$total    = $conn;
//$query   = "INSERT into tb_cform (u_name,u_first,u_city,u_email,u_phone,subj,message) VALUES('" . $name . "','" . $first . "','" . $city . "','" . $email . "','" . $phone . "','" . $subj . "','" . $message . "')";
//$success = $conn->query($query);

  ?>
<title>REGISTER AND PAY FOR YOUR PARTICIPATION IN OUR EVENTS-Amphitrion </title>
</head>
<body style="background-color:#45556b">
<div class="main">
<img src="logo.jpg" style="margin-left:38%">
<h3> REGISTER AND PAY FOR YOUR PARTICIPATION IN OUR EVENTS</h3>
<form action="thankyou.php" method="post">
  Family Name:<br>
  <input require type="text" name="u_name" required><br>
 First Name:
  <input type="text" name="u_first" required><br>
  City/Country:
  <input type="text" name="u_city" required><br>
  Email:
  <input type="email" name="u_email" required><br>
 Telephone:
 <input type="text" name="u_phone" required><br>
Subject:<br>
  <input type="text" name="subj" required><br>
 
Message:<br>
  <input type="text" name="message" required><br>
<input type="submit" value="Submit"><br>

</form>
 <h1>Fill out this form to calculate
    the total cost:</h1>
<form method="post">
<table>
<tr><td style="border-style:ridge;">
  PARTICIPATION FEE COMPANIONS -
120€
<br>
</td><td>
  <p>Number of Persons:<input type="text" name="u_persons" size="5" required/></p><br>
 <p>Price  120: </p>
 
  </td>
  <tr><td>
 <p> FRIDAY MARCH 2ND - TITANIA HOTEL
20:30 - DINNER
LADIES & COMPANIONS - 50€ </p>
<br>
</td><td>
  <p>Number of Persons:<input type="text" name="u_persons2" size="5" required/></p> <p>Price  50: </p>
  </td>
  </tr><tr>
  <td>
 <p> SATURDAY MARCH 3RD - TITANIA HOTEL
13:00 - LUNCH COMPANIONS - </p>
<br>
</td>
  <td>
  <p>Number of Persons:<input type="text" name="u_persons3" size="5" required/></p> <p>Price  35: </p>
  <tr>
  <td>
 <p> SATURDAY MARCH 3RD - LADIES PROGRAM
ATHENS SITE SEEING- GUIDED TOUR- ACROPOLIS MUSEM-LUNCH
10:00 - DEPART. TITANIA HOTEL </p>
<br>
</td>
  <td>
  <p>Number of Persons:<input type="text" name="u_persons4" size="5" required/></p> <p>Price  50: </p>
   <tr>
  <td>
 <p> SATURDAY MARCH 3RD - ATHENS MASONIC HALL
20:30 – OFFICIAL DINNER
LADIES & COMPANIONS - FREE OF CHARGE </p>
<br>
</td>
  <td>
  <p>Number of Persons:<input type="text" name="u_persons5" size="5" required/></p><p>Price:Free of charge </p>
  </td></tr>
  </table>
 <p>Total Amount to pay: 
 
  <?php echo $Amount; ?> <br>
<input type="submit" name="submit" value="Calculate!" /></p><br>
<table>
<tr><td style="border-style:ridge;">

<h1>OR BANK TRANSFER</h1>
<p>
BANK OF CYPRUS<br/>
ADDRESS : 134 LIMASSOL AVENUE,<br/>
CYFIELD 2 BUILDING,2015 STROVOLOS, CYPRUS<br/>
BANK ACCOUNT NR : 357020982581<br/>
IBAN: CY33002001950000357020982581<br/>
SWIFT / BIC: BCYPCY2N<br/>
BENEFICIARY: AMPHITRION PRISMA TRAVEL S.A.</p>
  </td></tr>
  </table>
</form>
</div>
</body>
</html>`

**Comment by kostGX** [comment]
Hello @Orestis93,

In order to get faster support, please let us know what kind of integration are you trying to achieve (Simple/Redirect/Native Checkout), and what is your technology stack? (XAMPP + PHP + MySQL?)

**Comment by Orestis93** [comment]
Dear KostGX,

I would like to achieve Redirect Checkout, where i parse the $Amount integer to Viva.
Yes i am running it on localhost (Xammp + php + msql).
Check my form and if you recommend different kind of integration please let me know.
Thanks a lot in advance :D

**Comment by Orestis93** [comment]
Kosta Hello again,
I have an update,whithout changing anything in my code, it now displays me the order code, but in this format,"Your Order Code is: 8.5908106701726E+15 "  and when i click make a payment it gives me bad request error.
Thank you in advance

**Comment by Orestis93** [comment]
Issue solved Kosta!! :D

**Comment by kostGX** [comment]
Great @Orestis93... Closing the issue.
