### ISSUE TITLE
Δεν κάνει ανακατεύθυνση στο e-shop μετά από επιτυχημένη συναλλαγή

### ISSUE THREAD

**Issue by kodirovshchik** [VivaPayments/API#431]
Γειά σας,

έχω εγκαταστήσει το opencart extension που έχετε ανεβάσει εδώ στο github.
έχω ρυθμίσει την πηγή πληρωμής (έχει εγκριθεί) , έχω βάλει τα κατάλληλα redirect links για επιτυχία και αποτυχία πληρωμής και έχω ρυθμίσει να είναι redirect checkout και όχι native.

Σημείωση: χρησιμοποιούσα παλαιότερα άλλο extension και έκανα κανονικά πληρωμές. Η πηγή πληρωμών δηλαδή δουλεύει κανονικά.

Το πρόβλημα είναι πως μετά από επιτυχημένη πληρωμή, στην σελίδα της viva δεν κάνει ανακατεύθυνση στο e-shop. Μένει στο μήνυμα που γράφει ότι η πληρωμή έχει γίνει επιτυχώς αλλά δεν κάνει ανακατεύθυνση, με αποτέλεσμα η παραγγελία να μένει κρυφή στο e-shop.

Ευχαριστώ

**Comment by VivaWalletSupport** [comment]
Could you post screenshots of the extensions settings (hide API Key) and of the payment source settings?

**Comment by kodirovshchik** [comment]
1. Opencart
![opencart](https://user-images.githubusercontent.com/26555988/33490301-62bb7a2e-d6bf-11e7-8aa2-d09315b6dd21.png)

2. Viva
![viva](https://user-images.githubusercontent.com/26555988/33490306-670bc6d8-d6bf-11e7-8e88-2c47c8604ab6.png)

**Comment by VivaWalletSupport** [comment]
Enter the Source Code (7960) in your extension settings.

**Comment by kodirovshchik** [comment]
Super! I confirm that it's working now. Thank you very much!
