### ISSUE TITLE
Πρόβλημα στο live περιβάλλον API call Failed

### ISSUE THREAD

**Issue by Orestis93** [VivaPayments/API#433]
Καλησπέρα σας,

Δημιούργησα μια φόρμα σε php και πήρα τον κώδικά σας για την προκειμένη περίπτωση του Redirect Checkout.
Ενώ στο demo  περιβάλλον ο κώδικάς μου τρέχει και δημιουργέι κανονικά  orderCode, μόλις άλλαξα σε live δηλαδή σε $request =  'https://www.vivapayments.com/api/orders'; αντι του demo, σκάει με error "API call failed". Έχω σωστά αλλάξει και τα υπόλοιπα path καθώς και το merchantId kai APIkey.
(Εάν ξαναλλάξω τα στοιχεία για demo περιβάλλον όλα δουλεύουν ρολόι )
Τι μπορεί να φταίει? Θα βοηθήσει να παραθέσω τον κώδικά μου?

**Comment by VivaWalletSupport** [comment]
Are you using a specific plugin from github, or just a custom made form?

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
