### ISSUE TITLE
Πρόβλημα με Viva native 

### ISSUE THREAD

**Issue by djdimimc** [VivaPayments/API#434]
Καλησπέρα σας,

Έχω πάρει τον .NET κώδικα για το Native checkout και έχω κάνει τις απαραίτητες αλλαγές.
Όταν όμως προσπαθώ να πραγματοποιήσω μια συναλλαγή, λαμβάνω το μήνυμα:
Source hidden of merchant 54d6ad2c-6294-4483-9d98-f24d6043c4a7 supports only native checkout
hidden = ο τετραψήφιος αριθμός της πηγής

Το μήνυμα το λαμβάνω, παρότι στην πηγή είναι τσεκαρισμένο το Native/Πληρωμή με Viva Wallet Checkout 
![native](https://user-images.githubusercontent.com/34279616/33617835-82eed318-d9e9-11e7-9796-e4307d0a40f4.jpg)

Στις ρθμίσεις ΑΡΙ είναι τσεκαρισμένο το "Ενεργοποίηση υπηρεσίας Native/Pay with Viva Wallet checkout"

Κάποια ιδέα για το τι μπορεί να φταίει;

Ευχαριστώ εκ των προτέρων.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
