### ISSUE TITLE
Προβλημα με παραγγελίες

### ISSUE THREAD

**Issue by stamatelos1234** [VivaPayments/API#435]
Το πρόβλημα είναι το εξής. H πλατφόρμα του eshop μου ειναι opencart 2.3.0.2 σε journal.
Oι πελάτες αγοράζουν πληρώνουν με κάρτα μεσώ viva wallet και μετά  η σελίδα χάνετε δεν γίνεται ολοκλήρωση παραγγελίας με αποτέλεσμα να λαμβάνω μόνο την πληρωμή και όχι την παραγγελία.
Μπορούμε να λύσουμε το πρόβλημα παρακαλώ?
Χρησιμοποιώ αγορασμένο extension από opencart marketplace και ο developer μου είπε να απευθυνθώ στη viva.

**Comment by dmihos** [comment]
Καλησπέρα σας
Αφού φτιάξετε την πηγή στο Viva Wallet account σας (Μενού> Πληρωμές> Πηγές Πληρωμών), ορίζοντας σωστά τα success/fail urls, θα πρέπει στη συνέχεια στο περιβάλλον διαχείρισης του plugin, να ορίσετε το SourceCode αυτής.

**Comment by plakidas** [comment]
Εχω το ιδιο προβλημα. Στο account τις Viva υπαρχει πληρωμή ενω στο site δεν υπάρχει η παραγγελία.
Το ιδιο ισχύει και σε demo-account-mode.

**Comment by plakidas** [comment]
To source code πεδιο ειναι αδειο. Τι να κανω ?

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.
