### ISSUE TITLE
Problem with a payment.

### ISSUE THREAD

**Issue by atr0x23** [VivaPayments/API#436]
Hi,

An order was made to my website using vivapayments (https://coffeebrandsdelivery.gr) its a wordpress_site yesterday (05/12/2017 @ 5:48 μμ.) but I can't see it on my Revenue. However the order it arrived normally on my server.  Can you please explain to me what is going on? If you see something on a log_file? because I am losing money.

Thanks in advance.

**Comment by VivaWalletSupport** [comment]
Are you using a specific plugin for the accepting payments?

**Comment by atr0x23** [comment]
I am using "VivaPayments WooCommerce Payment Gateway" version 1.0.4 
on wordpress 4.9.1

**Comment by VivaWalletSupport** [comment]
I would suggest to either contact the developer of that plugin or to use the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
