### ISSUE TITLE
"Invalid Code" error

### ISSUE THREAD

**Issue by dkladis** [VivaPayments/API#437]
Χαίρετε, έχω στήσει έναν λογαριασμό στο demo περιβάλλον για να ενσωματώσω στην σελίδα μας το Native Checkout που παρέχετε.

Έχω ακολουθήσει τις οδηγίες σας και στο demo διαχειριστικό του συστήματος σας, στην ενότητα "Οι Πωλήσεις Μου" -> "Πηγές Πληρωμών" έχω δοκιμάσει να δημιουργήσω νέες πηγές, αλλά πάντα το api σας μου επιστρέφει error "invalid code". Όταν χρησιμοποιώ την "Default" πηγή πληρωμών που υπάρχει από την δημιουργία του δοκιμαστικού λογαριασμού το api δέχεται τις πληρωμές.

Το πρόβλημα είναι ότι κατά τυχαία χρονικά διαστήματα, το σύστημα σας αρνείται την πληρωμή με το ίδιο error "Invalid code". Δηλαδή, εκεί που λειτουργεί κανονικά, μετά από μερικές δοκιμές σταματάει να δέχεται πληρωμές... Και ξεμπλοκάρει μετά από κάμποση ώρα, μέχρι να κολλήσει πάλι.

Που ακριβώς βρίσκεται το πρόβλημα; Είναι θέμα μόνο του demo περιβάλλοντος ή μπορεί να έχουμε προβλήματα και στο production;

Ευχαριστώ πολύ

**Comment by atr0x23** [comment]
Καλημέρα,

Φιλε μου, πραγματικά δεν εχω αλλάξει τίποτα στο api του server. 
Οπως λειτουργούσε απο την αρχη που στήθηκε έτσι είναι.
Θέλεις να μου πεις το key που χρησιμοποιείς να το συγκρίνω, μήπως είναι 
όντως Invalid?

**Comment by dkladis** [comment]
Καλημέρα, ορίστε το apikey και το source code που χρησιμοποιώ

apiKey = "+3gVSZ"
SourceCode = "Default"

**Comment by atr0x23** [comment]
Αυτη τη στιγμή απο το σύστημά μου βλέπω ότι χρησιμοποιείται αυτο:
DEMO_VIVA_API_KEY = "O2]F?C";
Μήπως γι'αυτό;

**Comment by dkladis** [comment]
Το api key που σου έστειλα το είχα πάρει από το demo διαχειριστικό σας, από τις ρυθμίσεις -> Πρόσβαση API!!

Θα κάνω δοκιμές με το key που μου λες και θα σε ενημερώσω!
Ευχαριστώ πολύ!

**Comment by atr0x23** [comment]
Οκ.
Δες και αυτό γιατί αυτο "zEWCKg" βλέπω τωρα να εχουμε βάλει στο ρυθμίσεις -> Πρόσβαση API!!
Ισώς το είχε βάλει το παλικάρι που δουλευε πρίν απο εμένα στην θέση αυτη. Απλα για να ξέρεις και εγώ είμαι καινούριος εδω, οπότε πολλα πραγματα τα ανακαλύπτω τώρα.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
