### ISSUE TITLE
Paymend provlem

### ISSUE THREAD

**Issue by oksanamagar** [VivaPayments/API#438]
καλησπέρα σας μήπως μπορείτε να μου πείτε πως θα διορθώσω αυτό το πρόβλημα το domain είναι πράσινο στην viva και έχω περάσει τα στοιχεία κανονικά στο panel

http://prntscr.com/hm4jjw

**Comment by VivaWalletSupport** [comment]
Hello, are you using the credentials from the demo or the live environment?

**Comment by oksanamagar** [comment]
demo or live μου βγάζει το ίδιο μήνυμα πως μπορούμε να το διορθώσουμε

**Comment by VivaWalletSupport** [comment]
I would suggest to start with the demo account, use the merchantid/api key/source code from your viva demo account and specify in the extension the proper demo URLs.

**Comment by oksanamagar** [comment]
με το demo που εκάν σε αυτήν την σελίδα δουλεύει κανονικά χωρίς προβλήματα

http://demo.vivapayments.com/

**Comment by VivaWalletSupport** [comment]
Change the URLs, merchantid, api key and source code in the extension settings to the ones from your live account.

**Comment by oksanamagar** [comment]
thank you it works now

**Comment by oksanamagar** [comment]
καλημέρα σας μια ερώτηση τελευταία μετά την επιτυχημένη πληρωμή που κάνει το shop βγάζει αυτό το μήνυμα που μπορώ να διορθώσω το url 
http://prntscr.com/hmtqei

**Comment by oksanamagar** [comment]
καλημέρα σας μια ερώτηση τελευταία μετά την επιτυχημένη πληρωμή που κάνει το shop βγάζει αυτό το μήνυμα που μπορώ να διορθώσω το url 
http://prntscr.com/hmtqei

**Comment by VivaWalletSupport** [comment]
Looks like you made a mistake in your payment source with the domain URL / Fail - Success URLs. Use as instructed in the readme.txt

**Comment by oksanamagar** [comment]
fixed thank you
