### ISSUE TITLE
GetTransactions API Error

### ISSUE THREAD

**Issue by Stordia** [VivaPayments/API#44]
Dear friends,

I have stuck for 2 days with the error on GetTransactions.

Always gives me :
[StatusId] => E 
[ErrorCode] => 400 
[ErrorText] => Null creditcard options on payment, order 9507169750172601.

I am trying to verify the payment for the order but with no luck !

PS: Working with the Demo API and Credit card 4111111111111111
and in the Dashboard i can see the successful payment.

**Comment by dmihos** [comment]
Hi Stordia
Are you sure you're using **GET** method for you call?

**Comment by Stordia** [comment]
Dear dmihos,

Thank you but i have found the problem... Everything is working perfect now!

**Comment by adrianblynch** [comment]
@Stordia - What was the issue in the end?
