### ISSUE TITLE
Συνδεση Viva Wallet με Shopify. ERROR Signature not verified

### ISSUE THREAD

**Issue by Msirakis** [VivaPayments/API#440]
Καλημέρα, 
Ακολούθησα όλα τα βήματα που περιγράφονται στον οδηγό. Ενημέρωσα το αρμοδιο τμημα, ανοιξε λογαριασμός πήρα τους κωδικούς MerchantId και StoreToken και τα εβαλα manual κι όχι copypaste. 

Δοκίμασα τόσο σε Native όσο και σε Redirection. 
Δοκίμασα αγορές σε διαφορετικούς browsers. 
Δοκίμασα μήπως στον κωδικό του MerchantId δεν θέλει τις παύλες

Το αποτέλεσμα είναι το ίδιο: ERROR--- Signature not verified

Μήπως μπορείτε να με βοηθήσετε; 
ΣΗΜ: Στις πηγές πληρομών μου ζήτησαν να σβήσω το αρχείο shopify που δημιουργήθηκε. Τώρα έχω ένα που λέει Default που δηιουργήθηκε απο τη viva και ένα απο το κατάστημα στο shopify (καθώς και ένα που είχα αρχικά για το φυσικό μου κατάστημα). 

Το ulr του καταστήματος είναι https://oxigenshop.myshopify.com

**Comment by dmihos** [comment]
Καλησπέρα σας
Δεν υπήρχε πηγή 'Shopify' στο λογαριασμό σας.
Προφανώς, μαζί με την πηγή που είχατε φτιάξει εσείς, σβήσατε και τη συστεμική πηγή που δημιουργήθηκε γι'αυτό το σκοπό.

Μπορείτε να ξαναδοκιμάσετε τώρα.
Βεβαιωθείτε, πρώτα, ότι έχετε βάλει σωστό MerchantId/StoreToken, ακριβώς όπως σας δόθηκαν από το τμήμα υποστήριξης με email.

**Comment by Msirakis** [comment]
Καλησπέρα και πάλι. 
Μόλις προσπάθησα ξανα. Το ίδιο αποτέλεσμα. 
Εβγαλα την επιλογή για viva wallet και επέλεξα πάλι βάζοντας ξανά manualy τους κωδικούς που πήρα απο το email. Πάλι το ίδιο αποτέλεσμα και σε άλλο browser : ERROR--- Signature not verified
Ειναι να αλλαξω κάτι απο το panel του viva wallet? Να κάνω το shopify φακελο --Συνδεδεμένο Wallet Primary ?

**Comment by Msirakis** [comment]
Μου στείλανε νέο κωδικό StoreToken και λειτουργει μια χαρά. 
Όμως ένα άλλο θέμα αν έχει λύση: Το κατάστημα μου έχει default έξοδο πληρωμών σε δολλάριο. Αν το αφήσω έτσι (έτσι με βολευει καλυτερα λογο πελατών) βγαινει μια error σελιδα που λέει οτι πληρωμές μονο σε ευρώ  και δεν με αφήνει να προχωρήσω. 
Αλλαξα σε Ευρω to default νομισμα για να δοκιμάσω ότι η εφαρμογή δουλευει. 

Υπάρχει κάποια λύση σε αυτό; 

Ευχαριστώ

**Comment by dmihos** [comment]
Καλημέρα
Όχι, δυστυχώς, προς το παρόν δεν υποστηρίζεται άλλο νόμισμα.

**Comment by Msirakis** [comment]
Ευχαριστώ για την βοήθεια. Ελπίζω να λυθεί σύντομα και το θέμα του νομίσματος. 
Καλή σας ημέρα
