### ISSUE TITLE
Μεταφορά ιστοσελίδας σε νέο server και αλλαγή πλατφόρμας eshop.

### ISSUE THREAD

**Issue by pkostopoulos** [VivaPayments/API#441]
Είμαστε στην μετάβαση από ένα υπάρχων eshop (magento) που έχει τρόπο πληρωμής μόνο την viva wallet και δουλεύει κανονικά, σε νεό eshop (wordpress) στο ίδιο domain αλλά σε νέο server όπου και γίνεται η ανάπτυξη της ιστοσελίδας.
Το πρόβλημα που αντιμετωπίζουμε είναι πως δεν μπορούμε να κάνουμε test πληρωμές πριν βγεί το νέο site live γιατί βρίσκεται στο ίδιο domain. Υπάρχει κάποια λύση σε αυτό;
Επίσης θέλουμε να ξέρουμε που ενημερώνουμε το τεχνικό τμήμα της viva wallet για την αλλαγή διεύθυνσης ip που αλλάζουμε και πόσο χρόνο θα διαρκέσει αυτή η αλλαγή;
Υπάρχει κάποια άλλη διαδικασία που πρέπει να λάβουμε υπόψιν ώστε να κυλήσουν όλα ομαλά στην αλλαγή αυτή;

**Comment by VivaWalletSupport** [comment]
You can make a new payment source in your live Viva Wallet account for the new site and make a transaction using a small amount (3 Euro for example).

**Comment by pkostopoulos** [comment]
Περιμένουμε απάντηση και σε άλλα δύο ερωτήματα.
Αν δεν κάνω λάθος είστε το τεχνικό τμήμα και ο μόνος τρόπος επικοινωνίας είναι μέσω github.
Σε περίπτωση που δεν γνωρίζεται τις απαντήσεις πείτε μας που να απευθυνθούμε.

**Comment by VivaWalletSupport** [comment]
In case these issues are related to the payment plugins, please inform me what ticket numbers you're still awaiting an answer on.

**Comment by dmihos** [comment]
Καλησπέρα σας

Δε χρειάζεται κάποιου είδους ενημέρωση για την αλλαγη IP.

Σχετικά με το νέο site στο existing domain, και εφόσον αυτό είναι προσβάσιμο από κάποιο προσωρινό cname (τύπου newsite.mydomain.com), τότε μπορείτε να κάνετε δοκιμές με demo viva wallet ή με μια νέα πηγή που θα φτιάξετε στο παραγωγικό σας account.
Όταν τελικά κάνετε την αλλαγή του domain, θα πρέπει να θυμηθείτε να αλλάξετε τα success/fail urls, σύμφωνα με το νέο site.

**Comment by pkostopoulos** [comment]
Καλημέρα, θα ήθελα να σας ενημερώσω πως χρειάζεται η ενημέρωση αλλαγής IP η οποία πέρνει 1 με 2 εργάσιμες μέρες και αυτό είναι απάντηση από το merchants@vivawallet.com που προώθησε το αίτημα.
Επίσης έχουμε κάνει όλες τις αλλαγές, έχουμε ενημερωθεί πως έχει αλλάξει η IP και όλες οι διαδικασίες από πλευρά σας, το site είναι live, σαν success kai fail url έχουν μπεί τα 
SUCCESS URL: index.php?wc-api=wc_vivawallet&vivawallet=success
FAIL URL: index.php?wc-api=wc_vivawallet&vivawallet=fail
και συνεχίζει να μην κάνει συναλλαγή.
Μετά από redirection στην σελίδα του viva wallet για πληρωμή, βάζουμε τα στοιχεία της κάρτας, και στο επόμενο βήμα εμφανίζει η συναλλαγή ακυρώθηκε και μας πάει πάλι στην σελίδα της viva, χωρίς κάποιο άλλο error message ή κάποιο code.

**Comment by pkostopoulos** [comment]
Μετά από δοκιμή με νέα κάρτα η πληρωμή δούλεψε.
Δεν χρειαζόμαστε κάποια άλλη βοήθεια, ευχαριστούμε.
