### ISSUE TITLE
wordpress woocommerce, πρόβλημα στην προσθήκη τρόπου πληρωμής με Viva

### ISSUE THREAD

**Issue by tasoskonst** [VivaPayments/API#442]
Καλησπέρα σας,

προσπαθώ να προσθέσω στο eshop την Viva σαν τρόπο πληρωμής. Κατέβασα και εγκατέστησα σύμφωνα με τις οδηγίες, το plugin για το woocommerce. Επίσης δημιούργησα την πηγή πληρωμών από την Viva (η οποία εγκρίθηκε) και πέρασα στο plugin το Merchant ID , το API Key και το Source Code. Στην πηγή πληρωμών έβαλα τα παρακάτω url:

SUCCESS URL: index.php?wc-api=wc_vivawallet&vivawallet=success
FAIL URL: index.php?wc-api=wc_vivawallet&vivawallet=fail

Τέλος, προσέθεσα και το optional webhook URL (Settings/API Access/Webhooks), μήπως λύσει το πρόβλημα αλλά δεν βοήθησε.

Όταν κάνω ολοκλήρωση της παραγγελίας, με πηγαίνει κανονικά στην σελίδα της Viva (έρχεται η παραγγελία, σε αναμονή πληρωμής), βάζω τα στοιχεία της κάρτας και μου βγάζει το μήνυμα : 
**Η συναλλαγή απέτυχε ή ακυρώθηκε, παρακαλώ προσπαθήστε ξανά.**. 

Έχετε καμία ιδέα για το τι μπορεί να φταίει?

**Comment by VivaWalletSupport** [comment]
Assuming you are trying to make a transaction in live mode, make sure you have enough funds on your card and that the amount you use is high enough. Try to use a different card and check the failure reason in your Viva Wallet account.

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
