### ISSUE TITLE
Συνδεση shopify με viva 

### ISSUE THREAD

**Issue by Libelloula** [VivaPayments/API#443]
Kαλησπερα, μηπως μπορει καποιος να με βοηθησει στα βηματα για να συνδεσω το shopify eshop μου με το viva..?
Ειμαι ακομη στην αρχη εχω μπει στον λογαριασμο μου Οι πωλήσεις μου ->Πηγές πληρωμών -> Νέα ιστοσελίδα/εφαρμογή εκει στο URL Επιτυχημένης συναλλαγής και URL Επιτυχημένης συναλλαγής τι πρεπει να βαλω??
Ευχαριστω!

**Comment by gdotw** [comment]
Καλημέρα βγάλατε μήπως άκρη γιατί και εγώ τα ίδια ψάχνω και δεν μπορώ να βρώ τι πρεπει να βάλω?

Σας ευχαριστώ

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.

A source named "Shopify" is automatically created on your account, so you don't have to set anything.
