### ISSUE TITLE
Συνεργασία του VivaWallet με Woofoo forms

### ISSUE THREAD

**Issue by athinaionfos** [VivaPayments/API#444]
Καλημέρα σας,

Θα ήθελα να σας ρωτήσω εαν το VivaWallet συνεργάζεται με το Woofoo forms ή εαν υπάρχει τρόπος συνεργασίας. Θέλω να πιστεύω ότι δεν είμαι ο μοναδικός που ρωτάει κάτι τέτοιο διότι το Woofoo ως σύστημα φόρμας υποστηρίζει πλήρως και τα Ελληνικά.

Ευχαριστώ εκ των προτέρων και Χρόνια σας Πολλά
Με εκτίμηση

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
