### ISSUE TITLE
The SSL certificate used to load resources from https://www.vivapayments.com will be distrusted in M70

### ISSUE THREAD

**Issue by Sotiris-k** [VivaPayments/API#445]
Παρατηρώ ότι στην τελευταία έκδοση του Chrome υπάρχει η παρακάτω ειδοποίηση στην κονσόλα για όσους έχουν υλοποιήσει το Native Checkout.

The SSL certificate used to load resources from https://www.vivapayments.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

Παρόλο που το πρόβλημα αυτό ουσιαστικά θα είναι πρόβλημα από τον Οκτώβριο του 2018, καλό θα είναι να του ρίξετε μια ματιά για να μην φτάσουμε ως εκεί.

**Comment by kostGX** [comment]
Closing as issue was last updated > 5 months. Please re-open with an update comment if you still need help with this.

**Comment by Sotiris-k** [comment]
The issue still exists. You closed it without an answer.
