### ISSUE TITLE
Custom Name and Logo in Viva Button pop up window

### ISSUE THREAD

**Issue by mirotis** [VivaPayments/API#446]
Is there an option to add a custom logo as well as a custom Company name in the pop up windows after clicking the PAY NOW button of viva wallet?

**Comment by kostGX** [comment]
Hello @mirotis and thank you for your patience. Unfortunately at this time Pay NOW Button of Viva Wallet does not support custom logos. To preserve your branding and logo while staying PCI-Compliant you can integrate our Native Checkout Solution.

You can learn more about it here https://github.com/VivaPayments/API/wiki/Native-Checkout

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.

**Comment by kostGX** [comment]
@mirotis we would like to inform you that it is now possible to update the logo of the Simple Checkout.

Update the logo in your Viva Wallet Account Payment Source connected to the payment form and it should work.
