### ISSUE TITLE
Πρόβλημα αποδοχής κάρτας

### ISSUE THREAD

**Issue by bill27** [VivaPayments/API#447]
Γεια σας.

Έχει προκύψει ένα πρόβλημα με την αποδοχή της κάρτας Viva Wallet που έχω σαν πελάτης από συγκεκριμένες ιστοσελίδες.

Πιο συγκεκριμένα το πρόβλημα προκύπτει όταν υπάρχει πεδίο στο οποίο θα πρέπει να συμπληρωθεί το όνομα του κατόχου της κάρτας.
Σε ιστοσελίδες όπως της Microsoft που δεν ζητά το όνομα κατόχου δεν υπάρχει πρόβλημα. Σε ιστοσελίδες όπως της Google που το ζητά υπάρχει πρόβλημα.

Δοκιμάζοντας όλους τους δυνατούς συνδυασμούς του ονόματός μου (κεφαλαία, μικρά, ελληνικοί χαρακτήρες, λατινικοί χαρακτήρες, πρώτα το όνομα και μετά το επώνυμο ή το αντίθετο κτλ.) δεν βρήκα κάποια λύση στο πρόβλημα.

Με τη vivawallet που επικοινώνησα και τηλεφωνικά αλλά και με email με το τμήμα υποστήριξης και με στείλανε εδώ για να αναφέρω το πρόβλημα.

Τελικά τι θα πρέπει να συμπληρώσω στο πεδίο "Όνομα Κατόχου";

Σας ευχαριστώ.

**Comment by kostGX** [comment]
Καλησπέρα @bill27, εγώ χρησιμοποιώ το **Viva Wallet** σαν όνομα κατόχου της κάρτας καθώς αυτό είναι γραμμένο πάνω στην κάρτα.

Παρακαλώ δοκιμάστε με αυτό.

**Comment by bill27** [comment]
Θα το δοκιμάσω αυτό που μου λέτε.

Από μία αναζήτηση που έκανα είδα ότι κατά καιρούς υπάρχει πρόβλημα και με κάρτες άλλων εταιρειών στη Google.
Στη Godaddy που είχα πρόβλημα μου έχουν μπλοκάρει το λογαριασμό (ίσως λόγο των πολλών ανεπιτυχών προσπαθειών που έκανα χρησιμοποιώντας πολλούς διαφορετικούς συνδυασμούς του ονόματός μου).

Πάντως με την πρώτη ευκαιρία θα δοκιμάσω με το όνομα κατόχου "Viva Wallet" και θα απαντήσω για το εάν λειτουργεί ή όχι.

Σας ευχαριστώ.

**Comment by kostGX** [comment]
Closing as issue was last updated > 5 months. Please re-open with an update comment if you still need help with this.
