### ISSUE TITLE
Πιθανό πρόβλημα με τη φόρμα κάρτας

### ISSUE THREAD

**Issue by msfgreece** [VivaPayments/API#448]
Από χρήστες του ιστότοπου msf.gr είχαμε την πληροφορία ότι «κολλάει» η φόρμα της πιστωτικής κάρτας στο περιβάλλον VIVA που οδηγούνται όταν επιλέγουν να κάνουν δωρεά με την κάρτα τους στο https://msf.gr/support/donation

**Comment by VivaWalletSupport** [comment]
Hello, are you using a specific plugin to make the connection? When trying the page it shows that not only the credit card option but also the Paypal option does not function (empties the card).

**Comment by msfgreece** [comment]
We use the module https://www.drupal.org/project/commerce_vivapayments  
Please describe the problem you mention.

**Comment by VivaWalletSupport** [comment]
When simulating a donation on the URL you mentioned, checking an amount, specifying client information,  checking the credit card or paypal button, when proceeding nothing happens, only a message pops up that the shopping card has been emptied (Η Δωρεά αφαιρέθηκε από το καλάθι σας. Επιλέξτε δωρεά ή μηνιαία δωρεά για να ολοκληρώσετε την παραγγελία σας.). So it does not look like a specific problem with Viva Payments to me.

**Comment by msfgreece** [comment]
Δεν μπορούμε να το αναπαράξουμε αυτό το σφάλμα, θα το ερευνήσουμε.

**Comment by kostGX** [comment]
Closing as issue was last updated > 5 months. Please re-open with an update comment if you still need help with this.
