### ISSUE TITLE
Oscommerce Δεν κάνει Redirect μετά την επιτυχημένη πληρωμή

### ISSUE THREAD

**Issue by urbancom** [VivaPayments/API#449]
Καλησπέρα σας,

εγκαταστήσαμε τον μηχανισμό και ύστερα από επιτυχημένη πληρωμή, δεν κάνει Redirect στην ιστοσελίδα μας, με αποτέλεσμα να μην καταγράφεται και η παραγγελία, ενώ ο πελάτης έχει χρεωθεί.

![viva](https://user-images.githubusercontent.com/35459862/34949059-a3c13790-fa17-11e7-979a-c8ca142eaf82.png)
![settings](https://user-images.githubusercontent.com/35459862/34949143-efe69ade-fa17-11e7-9d64-c78afc61d2ca.png)

**Comment by VivaWalletSupport** [comment]
Specify the Source Code (8443) in your module settings.

**Comment by kostGX** [comment]
Closing as issue was last updated > 5 months. Please re-open with an update comment if you still need help with this.
