### ISSUE TITLE
Currency Code

### ISSUE THREAD

**Issue by RazaLabs** [VivaPayments/API#45]
WE are having issue with multi currency , we have included in our request parameters args for USD currency but it still display amount in Euros

	$currenctyType = '840'; 
	$postargs = 'Amount='.urlencode($Amount).'&AllowRecurring='.$AllowRecurring.'&RequestLang='.$RequestLang.'&SourceCode='.$Source.'&CurrencyCode='.$currenctyType;

Kindly can you help?
Thanks

**Comment by dpnevmatikos** [comment]
Hi there @RazaLabs,
Unfortunately we do not currently support multiple currencies (only EUR).

**Comment by RazaLabs** [comment]
I can see the currency support documents here?
https://github.com/VivaPayments/API/wiki/Pay-with-Viva-Wallet

**data-vp-currency	Only available to merchants that support multiple currencies The currency of the amount (3 digit ISO code). The default is 978 (for EUR).
**

**Comment by dpnevmatikos** [comment]
Apologies for that. The data attribute discussed, was reserved for future use.
We will update the existing documentation to indicate clearly that this attribute is not yet supported.
