### ISSUE TITLE
Συνδεση Vivawallet με e-shop στο Wix.com

### ISSUE THREAD

**Issue by bzrstickers** [VivaPayments/API#450]
Kαλησπέρα,

Υπάρχει κάποιος τρόπος για να μπορέσω να συνδέσω το e-shop που εχω φτιάξει στο wix με το vivawallet μου? Στο payment methods του wix έχει μονο μεσω braintree και manual payment.

ευχαριστώ πολύ!

**Comment by VivaWalletSupport** [comment]
Hello, I would suggest to submit a ticket as instructed at https://support.wix.com/en/article/requesting-additional-payment-providers

**Comment by bzrstickers** [comment]
To έχω κάνει ήδη αλλα μου ζητανε Τραπεζα. Τ μυνημα που μου στείλανε είναι το εξής:

Thank you for contacting Wix. 

I understand you have questions about your eshop. 

So that I can further assist you, please tell me the error message you are receiving when you try to add the provider. 

 
Add a screenshot to your ticket in order to help Wix Support agents better understand your question. Important:If you are taking a screenshot of a billing page or bank statement, be sure to conceal your full credit card number and CVV number, leaving only the last 4 digits of the credit card visible.

**Comment by VivaWalletSupport** [comment]
Maybe they did not understood your question, try to reformulate it and provide them with an URL to the API.

**Comment by bzrstickers** [comment]
Μπορειτε να μου δωσετε ενα παραδειγμα πως να το κανω αυτο?

**Comment by VivaWalletSupport** [comment]
Example: We would like to use a payment provider (Viva Wallet) that is currently not listed in your options, for more information please have a look at https://github.com/VivaPayments/API

**Comment by kostGX** [comment]
Closing as issue was last updated > 5 months. Please re-open with an update comment if you still need help with this.
