### ISSUE TITLE
Connection of my site eshop with Vivapayments 

### ISSUE THREAD

**Issue by chgl48** [VivaPayments/API#452]
Καλησπέρα σας,
έλαβα από την host εταιρία του site μου το παρακάτω μήνυμα:

"Please provide us with needed requirements for Business - VivaWallet and we will assist you with your questions."

Πείτε μου λοιπόν τι χρειάζεστε για να μπορέσω να συνδέσω το site μου με τη προσφερόμενη υπηρεσία σας

Χ.Λυριτζής

**Comment by VivaWalletSupport** [comment]
Could you provide some more details on what you want to implement, custom coding for Native/Redirection method, ready made plugin for specific e-commerce program? Also, what requirements is your hosting company looking for, server requirements, requirements to build a payment gateway? For more information and examples have a look at the Wiki.

**Comment by chgl48** [comment]
Thank you for the reponse.
go to pragmatognomon.com click on above left: ΤΕΧΝΙΚΗ ΕΚΘΕΣΗ then click on any of the three links and then click on the wordlink ΠΛΗΡΩΜΗ. There, any of my clients shall put his/her card details in order to pay me. The picture you see is under construction and it was created with the code I put to the web page, but this code is incomplete and does not work, so I need the exact code in order this gateway to work properly in conjunction with the vivawallet payment system
Please advise
Regards
C.Liritzis


-----Original Message-----

**Comment by VivaWalletSupport** [comment]
In case you want to use a payment form embedded in your page I would suggest to have a look at the Native Checkout examples at https://github.com/VivaPayments/API/tree/master/NativeCheckout

**Comment by chgl48** [comment]
Native Checkout is already declared in vivawallet as you show, but it does not perform. Advise what code to put in the file: vivapayment.html of my site?



-----Original Message-----

**Comment by VivaWalletSupport** [comment]
You can find PHP examples here: https://github.com/VivaPayments/API/tree/master/NativeCheckout/PHP

**Comment by chgl48** [comment]
The whole of code of it shall I paste to my code of vivapayment.html, completed with my publickey etc?
https://github.com/VivaPayments/API/commit/22d629f4113d96b999eba4744eb54f708fb789ca


-----Original Message-----

**Comment by VivaWalletSupport** [comment]
I would suggest to contact a developer in case you are not familiar with coding.

**Comment by chgl48** [comment]
I would suggest to provide the requested code



-----Original Message-----

**Comment by VivaWalletSupport** [comment]
The code is already provided at https://github.com/VivaPayments/API/tree/master/NativeCheckout and you can either use PHP or ASP (not HTML) to implement it in your website. To sell items over the internet and to comply with EU regulations I would recommend to use a professional shopping cart solution, you can find ready made payment plugins at https://github.com/VivaPayments/API/tree/master/Plugins to connect with Viva Wallet without any coding requirements.

**Comment by chgl48** [comment]
1. For API/NativeCheckout/ , I choose the PHP sample, so this code shall be copied to my file: http://pragmatognomon.com/vivapayment.html 
or to 
the eshop that shall be created with the professional shopping cart? So the shopping cart is a must?
2.The ready made payment plugins at https://github.com/VivaPayments/API/tree/master/Plugins shall connet the professional shopping cart with viva wallet ?
Pls advise
Rgds
CL


-----Original Message-----

**Comment by VivaWalletSupport** [comment]
1. You cannot copy PHP or ASP code to an HTML file, using a ready made shopping cart would be a solution in case you are not familiar with coding and you do not have a budget to hire a developer.
2. That is correct.

**Comment by chgl48** [comment]
1. The file http://pragmatognomon.com/vivapayment.html  was created as a copy of the code of vivawallet, you do not explain how this code shall be completed in order to be workable in conjuntion with vivawallet payment link
2. That is correct



-----Original Message-----

**Comment by kostGX** [comment]
Closing as issue was last updated > 5 months. Please re-open with an update comment if you still need help with this.

**Comment by chgl48** [comment]
Μήπως υπάρχει τελικά ένας κώδικας να συμπεριλάβω στη σελίδα του link:   http://pragmatognomon.com/vivapayment.html
ώστε να είναι δυνατές πληρωμές;


Χ.Λυριτζής


Translation of the above:



Is there finally a code to include on the link page: http://pragmatognomon.com/vivapayment.html
so that payments are possible?


Ch.Lyritzis



-----Original Message-----
