### ISSUE TITLE
Δημιουργια Order με  IsPreAuth

### ISSUE THREAD

**Issue by nikos90** [VivaPayments/API#454]
προσπαθώ να δημιουργήσω ένα νέο order για το οποιο να δεσμευθει το ποσό αλλα να μην γίνει η χρέωση αυτόματα και φαίνεται να μην λειτουργεί.
Ακολουθώ τα εξής βήματα:
Δημιουργώ ένα Order στο endpoint /api/orders με "IsPreAuth": "true"
Το εκτελώ (αφού έχω δημιουργίσει και το ανάλογο token της κάρτας μεσω της διαδικασίας native checkout ) στο endpoint /api/Transactions
Επειτα οταν τραβήξω τις λεπτομερειες της συνναλαγής βλέπω πάντα αυτό:

 [TransactionType] => stdClass Object
                        (
                            [Name] => CardCharge
                            [TransactionTypeId] => 5
                        )

Τι κάνω λάθος;

Merchant id: d859f662-606a-4058-842b-b210aefb9366
Transaction id: 18aab763-4077-46d5-8eb9-2b39a758f594
Order Code: 2116207480672600

Εκτελώ τις κλήσεις στο δοκιμαστικό περιβάλλον.

**Comment by dpnevmatikos** [comment]
Καλησπέρα σας,
Μπορείτε να δοκιμάσετε στην κλήση που κάνετε στο api/transactions να προσθέσετε σαν παράμετρο ```PaymentMethodId: 1``` ?

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.

**Comment by djsolid** [comment]
Hi,

I am facing the same issue. We are sending transactions with IsPreAuth: true however those are being marked as completed even though we don't complete them. I've tried adding PaymentMethodId:1 but I get a "Transaction failed" error.

Did anything change in the API ?

**Comment by alekseykuleshov** [comment]
I've added `$obj->PaymentMethodId = 1;` with transaction creation and it helped
