### ISSUE TITLE
Magento 2 support

### ISSUE THREAD

**Issue by gaitan1** [VivaPayments/API#455]
Hello,

Is there support for eshops based on a magento 2 platform? can I accept through viva payments? 
Thanks..

**Comment by VivaWalletSupport** [comment]
Hello, following plugin works with the redirection method and can be used with Magento 2 and Viva Wallet: https://github.com/VivaPayments/API/tree/master/Plugins/magento/magento2_vivawallet/Ced/VivaPayments

**Comment by NoSGR** [comment]
Hello,

I've used the above link for Magento 2.2.0 but i get this error when i'm about to complete an order with Viva Payments: There has been an error processing your request

URL: {myurl}/vivapayments/checkout/start

Can you please help me?

**Comment by NoSGR** [comment]
I've created a demo account and used those credentials in the configuration and now i'm getting this error:

 PHP Fatal error:  Uncaught Error: Class 'Ced\VivaPayments\Model\Exception' not found in /app/code/Ced/VivaPayments/Model/PaymentMethod.php:171

**Comment by VivaWalletSupport** [comment]
First try the demo environment and use the credentials from you demo account, I made a correction today to the code the properly display the exception and the error text.

**Comment by kostGX** [comment]
Closing as issue was last updated > 5 months. Please re-open with an update comment if you still need help with this.
