### ISSUE TITLE
Cors problem

### ISSUE THREAD

**Issue by kostas1986** [VivaPayments/API#456]
Hello,
I have a small problem with my native integration. Everything on demo version of the payment works just great, but when i try to turn my app live with the none-demo credentials from viva payments i keep receiving a Cors problem. Can you please advise?

Failed to load https://vivapayments.com/api/cards/installments?key=NF1D2Xef5SPiUP605aCCYYkVDdUBLSSg5MlYpwunG%2Fc%3D: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://driveyouaway.com' is therefore not allowed access.

**Comment by kostas1986** [comment]
Για να λυθεί το πρόβλημα με το cors πρεπει το call του js function να γίνετε στο https://www.vivapayments.com και όχι στο https://vivapayments.com
Ας διορθωθεί και στο native php example που έχετε πάνω.

**Comment by kostGX** [comment]
Closing as issue was last updated > 5 months. Please re-open with an update comment if you still need help with this.
