### ISSUE TITLE
Wordpress/Woocommerce-You should be automatically redirected to Vivapayments to make payment.

### ISSUE THREAD

**Issue by ggg125** [VivaPayments/API#457]
Hi,
I have setup everything and when click pay with viva, i get this message and doesn't direct to viva payment environment:

"Thank you - your order is now pending payment. You should be automatically redirected to Vivapayments to make payment."

I have deactivate all plugins except -WooCommerce Weight Based Shipping-.

What can i do to solve this issue?

Thanks

Wordpress 4.9.2
WooCommerce 3.2.6
Viva Payments - Viva Wallet WooCommerce Payment Gateway  1.2 Enartia (downloaded direct from WP plugins).

**Comment by VivaWalletSupport** [comment]
When using a  3rd party plugin I would advise to contact its developer about any problems you might experience with it. You also might want to try the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress

**Comment by ggg125** [comment]
We didn't knew that this is a 3rd party plugin because we never found any official viva plugin in your website or to viva wallet control panel. Also we didn't get any instructions from no one about installing viva payments on our website.

I would suggest you to put your official plugin inside Wordpress's plugin searcher.Every user will search there.

Would you like to guide me where i can find vivawallet-for-woocommerce.zip?

**Comment by VivaWalletSupport** [comment]
Management and keeping up to date the various published plugins can be done in a more efficient way when they are published in a central location like here on Github. As mentioned before you can find your plugin here: https://github.com/VivaPayments/API/tree/master/Plugins/wordpress

**Comment by ggg125** [comment]
link not redirect to a download file. Would you like be more specific?

**Comment by VivaWalletSupport** [comment]
In case you are not using a git tool, download the complete repository from https://github.com/VivaPayments/API and follow the instructions from the readme file located in the Plugins/wordpress/vivawallet-for-woocommerce folder on how to prepare your plugin.

**Comment by ggg125** [comment]
After installing and activate plugin, we fill all plugin's necessary areas like API etc. and when try to pay with viva we get this message in the directed page.. (and of course no button appear)

"Thank you for your order, please click the button below to pay."

What we make wrong?

**Comment by VivaWalletSupport** [comment]
What errors are logged?

**Comment by ggg125** [comment]
Since all those days that we try to install YOUR plugin and figure out how to make it work, we decided to give up. We tired all this and spend time on phone with the very poor and delayed support by Viva,trying to solve problem email by email and github forum. It seems you have some reasons that you don't want to continue this payment method and of course you don't care to share and spread Viva payment plugin gateway nice and easy.
Hope your company knows that the whole support is the worst ever exists and with all this complications you put obstacles to have an easy and clean installation of your plugin that you earn money % from our sales.

We have Co-Op and used plugins from many other different companies wordwide but we didn't faced something like this before.

Good luck with your hidden and mystic plugin and your arrogance programmers.

**Comment by VivaWalletSupport** [comment]
I'm sorry for your negative experiences and that my short trouble shooting questions are interpreted as arrogant. In case it is not possible to provide me with an error log (as requested yesterday), it might be an option to provide me access to your site solve the problem in a faster way. In desired please contact me at vivawalletgithubsupport@hellasboost.gr and send a cc to ecommerce-support@vivawallet.com

**Comment by kostGX** [comment]
Closing as issue was last updated > 5 months. Please re-open with an update comment if you still need help with this.
