### ISSUE TITLE
Ενημέρωση για επιτυχημένη - αποτυχημένη συνναλλαγή μεταξύ συστημάτων

### ISSUE THREAD

**Issue by Ko2ta2** [VivaPayments/API#459]
Χρησιμοποιώ php με redirection.
Έχω δημιουργήσει το order και τα url που επιστρέφουν μετά την επιτυχημένη / αποτυχημένη πληρωμή.
Αναρωτιώμουν σε περίπτωση που για τον οποιοδήποτε λόγο ο πελάτης δεν επιστρέψει στη σελίδα ή απλά κλείσει τη παράθυρο πριν ξεκινήσει να συμπληρώνει τα στοιχεία του πώς μπορώ να ξέρω αν η πληρωμή ολοκληρώθηκε ή όχι; 
Ευχαριστώ

**Comment by VivaWalletSupport** [comment]
You can implement a webhook for this purpose https://github.com/VivaPayments/API/wiki/Webhooks

**Comment by Ko2ta2** [comment]
Do we have any excample in php? Thanks

**Comment by VivaWalletSupport** [comment]
If it helps, you can have a look at an existing PHP plugin https://github.com/VivaPayments/API/blob/master/Plugins/wordpress/vivawallet-for-woocommerce/wc-vivawallet.php

**Comment by Ko2ta2** [comment]
Έχω φτιάξει μέχρι το σημείο που παίρνω το key {"Key":"D82D214D6A42E3D08E7F62536242DD72322C3AFB"}.
Έχω κολλήσει στο τι πρέπει να κάνω ώστε να δημιουργήσω το webhook μέσα από το πίνακα ελέγχου "http://demo.vivapayments.com/selfcare/el-gr/security/apiaccess". Μου βγάζει συνεχώς σφάλμα 502. Τι πρέπει να βάλω στο url;

**Comment by VivaWalletSupport** [comment]
When creating a new webhook URL, it first should generate a proper response (Key), after the webhook URL has been verified correctly you can implement your logic to check the transaction results ad take necessary actions accordingly (like you can see with the PHP plugin). https://github.com/VivaPayments/API/wiki/Webhooks#webhook-url-verification

**Comment by Ko2ta2** [comment]
Για το merchand id 05a1ed4e-d464-46ef-baeb-e1866e256887 ή το 618fe4af-211f-4e62-b334-3271610c0518
υπάρχει κάποιος λόγος που ενω φτάνω στο σημείο της viva για καταχώρηση της κάρτας, η συνναλαγή καταλήγει σε refuse πάντα και δεν υπάρχει αναφορά για τη προσπάθεια συνναλαγής στο σύστημα της viva;
Έφτιαξα τον πρώτο με ID λογαριασμό για να τσεκάρω αν έχει μπλοκάρει κάτι αλλά πάλι έβγαινα στο ίδιο σενάριο.
Έχει μήπως κλειδώσει το site ή η ip που έρχονται τα αιτήματα;

Τα στοιχεία βρίσκονται στο MID 05a1ed4e-d464-46ef-baeb-e1866e256887
Στο άλλο MID έχει τις συνναλαγές που είχαν γίνει παλαιότερα.

Ευχαριστώ

**Comment by VivaWalletSupport** [comment]
Hello, I would suggest to close this ticket and create a new ticket for the problem you mention.
