### ISSUE TITLE
Redirect Payment μέσω Viva

### ISSUE THREAD

**Issue by ckarikas** [VivaPayments/API#46]
Καλησπέρα σας,

θα ήθελα να συνδέσω τον ιστότοπο μου (esolutionpro.gr), μέσω του Viva με τη Redirect Payment method, έτσι ώστε, όταν ένας πελάτης ολοκληρώσει την αγορά του στον ιστότοπο μου να ανακατευθύνεται στον ιστότοπο της Viva προκειμένου να κάνει την πληρωμή. Για να το κάνω αυτό πρέπει να χρησιμοποιήσω τον κώδικα PHP που δίνεται στο github, όσον αφορά το Redirect Checkout (1. Payment Order, 2. Completion of the payment details, 3. Confirmation of the transaction), η μπορεί να γίνει πιο απλά; Κι αν πρέπει να το κάνω με χρήση PHP, υπάρχει κάποιος οδηγός στο github;

Ευχαριστώ εκ των προτέρων!

**Comment by ckarikas** [comment]
Good evening,

I would like my website to be connected  (esolutionpro.gr) with Viva, through Redirect Payment method. When my client has finished his purchase, I want to redirect automatically to viva website for paying. For doing this, I have to use GitHub PHP code for Redirect Checkout (1. Payment Order, 2. Completion of the payment details, 3. Confirmation of the transaction) or is there another way? If there is no other way except for PHP, maybe, is there a guide?

Thank you!

**Comment by dpnevmatikos** [comment]
Καλησπέρα,
Τα βήματα για να ενσωματώσετε την μέθοδο πληρωμής με Redirect περιγράφονται [εδώ](https://github.com/VivaPayments/API/wiki/Redirect-Checkout).
Αν χρησιμοποιήσετε PHP μπορείτε να δείτε sample κώδικα που δημιουργεί κωδικό παραγγελίας (πρώτο step) [εδώ](https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php).

Είμαστε στη διάθεση σας για τυχόν διευκρινήσεις.

**Comment by ckarikas** [comment]
Ευχαριστώ πολύ για την απάντηση σας! Τα έχω ήδη δει αυτά τα βήματα, απλά ήθελα να ρωτήσω για να σιγουρευτώ!

**Comment by dpnevmatikos** [comment]
:+1:
