### ISSUE TITLE
We have one new issue with the prestashop plug in

### ISSUE THREAD

**Issue by samator79** [VivaPayments/API#460]
This is the issue when i pay with card:

`Fatal error: Uncaught Table 'namedatabase.vivawallet_data' doesn't exist<br /><br /><pre>update vivawallet_data set order_state='P' where OrderCode='8684358944672601'</pre> thrown in mydirectory/public_html/classes/db/Db.php on line 791`

Thank for your reply 

Jorge Torres

**Comment by VivaWalletSupport** [comment]
Check if the vivawallet_data table exists, if not create the table manually:

CREATE TABLE IF NOT EXISTS `vivawallet_data` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `secure_key` varchar(150) DEFAULT NULL,
  `OrderCode` varchar(255) DEFAULT NULL,
  `ErrorCode` varchar(50) DEFAULT NULL,
  `ErrorText` varchar(255) DEFAULT NULL,
  `Timestamp` datetime DEFAULT NULL,
  `ref` varchar(150) DEFAULT NULL,
  `total_cost` int(11) DEFAULT NULL,
  `currency` char(3) DEFAULT NULL,
  `order_state` char(1) DEFAULT NULL,
  `sessionid` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

**Comment by kostGX** [comment]
Closing as issue was last updated > 5 months. Please re-open with an update comment if you still need help with this.
