### ISSUE TITLE
demo site for developers does not work

### ISSUE THREAD

**Issue by jimkar** [VivaPayments/API#462]
hi 

I am trying to sign up on demo.vivapayments.com for a developer account but I get an error "Registration cannot be completed".

**Comment by pawebgate** [comment]
The same holds for me!

**Comment by gliaskos** [comment]
Please try again.

Sorry for the inconvenience :/

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.
