### ISSUE TITLE
Error on Magento 2.1 

### ISSUE THREAD

**Issue by jimkar** [VivaPayments/API#463]
I get this error on viva payment method checkout

Exception #0 (Exception): Notice: Trying to get property of non-object in /app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 167

**Comment by VivaWalletSupport** [comment]
Hello, are you in live or demo mode and can you add some screenshots of your extension and Viva wallet payment source settings (mask the API Key).

**Comment by jimkar** [comment]
Hi 

it seems to work fine on live environment after the activation of payment source.
