### ISSUE TITLE
Πληρωμη με american express

### ISSUE THREAD

**Issue by chiosdj** [VivaPayments/API#464]
Ο πελάτης υποστηρίζει ότι έγινε χρέωση στην Amex card αλλά σε εμάς  δεν επέστρεψε επιτυχή πληρωμή για να γίνει ενεργοποίηση της υπηρεσίας που αγόρασε.

Επίσης δεν φαίνεται η συναλλαγή μέσα από στο site https://members.vivawallet.com στις Πωλήσεις
ενώ φαίνονται άλλες μεταγενέστερες συναλλαγές.

  [OrderCode] => 4285983299972605

**Comment by kostGX** [comment]
Closing as issue was last updated > 6 months. Please re-open with an update comment if you still need help with this.
