### ISSUE TITLE
Ένωση Magento με Viva Payments

### ISSUE THREAD

**Issue by xenofon360** [VivaPayments/API#465]
Καλησπέρα,

Έχουμε ένα site σε Magento 2.1.3 CE και επιθυμούμε την σύνδεση της με την υπηρεσία Viva ώστε να μπορούν οι πελάτες να ολοκληρώνουν τις παραγγελίες τους με πληρωμή με κάρτα.

Ενώ η διαδικασία έχει γίνει από εμένα σε site WordPress / Woocommerce & Joomla / VirtueMart, δεν γνωρίζω καθόλου τον τρόπο για να γίνει σε Magento. Από την μεριά της Viva, όλα είναι έτοιμα και ο λογαριασμός έχει εγκριθεί κανονικά.

Αυτό που χρειάζομαι είναι έναν άνθρωπο να με καθοδηγήσει αναλυτικά, από την αρχή μέχρι το τέλος, ώστε να γίνει η ένωση. Λογικά θα χρειαστεί κάποιο Payment Gateway, για να φανούν τα πεδία της Viva στην περιοχή Payment Methods του Magento, δεν γνωρίζω όμως ούτε που θα βρω το ανάλογο extension ούτε πως ακριβώς θα το "ενσωματώσω" στο site.

Με εκτίμηση,
Ξενοφών Καλούδης

**Comment by VivaWalletSupport** [comment]
Hello, the extension and installation instructions are located here: https://github.com/VivaPayments/API/tree/master/Plugins/magento/magento2_vivawallet/Ced/VivaPayments

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.
