### ISSUE TITLE
Πρόβλημα με Παραγγελία

### ISSUE THREAD

**Issue by KostasTimpas** [VivaPayments/API#467]
Το Eshop είναι κατασκευασμένο σε CMS Magento και έχουμε κατεβάσει το extension από το GitHub όπως μας είχατε ενημερώσει παλαιότερα.

Κατά την ολοκλήρωση της παραγγελίας όμως συνεχώς λαμβάνουμε μήνυμα Σφάλματος.

Στο account έχουμε τοποθετήσει τα εξής:

Example with URL rewrite enabled:
Success page: vivawallet/hpay/hpok/
Failure page: vivawallet/hpay/hpnok/

Θα μπορούσατε να μας βοηθήσετε;

**Comment by VivaWalletSupport** [comment]
Please provide some more info on the error you get and the used scenario.

**Comment by KostasTimpas** [comment]
We try to complete a credit card order. When we place the items on Viva,
the order is not successful but redirects us to a page indicating that
something was wrong in our order and the order is canceled ...
The eshop is rgns.gr

If you needed additional information, please let us know.



2018-02-07 6:27 GMT+02:00 Tom van der Veer <notifications@github.com>:

**Comment by VivaWalletSupport** [comment]
Are you testing in the demo environment?

**Comment by KostasTimpas** [comment]
Νο. In Productive

**Comment by VivaWalletSupport** [comment]
Please check first in the demo environment, when everything works ok switch to live.

**Comment by KostasTimpas** [comment]
Its Ok. Its new eshop and customers cant see.
What i should do to work normally?

**Comment by VivaWalletSupport** [comment]
Create a payment source in the demo environment, change the credentials in the extension settings for the ones from the demo environment and test using test card 4111111111111111

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.
