### ISSUE TITLE
Magento 2.2 Error

### ISSUE THREAD

**Issue by NoSGR** [VivaPayments/API#468]
Καλησπέρα σας,

πριν λίγο αλλάξαμε απο demo environment σε live, και μετά απο την εισαγωγή της κάρτας στην παραγγελία, λαμβάνω αυτό το error:

Notice: Undefined variable: resultObj in /html/app/code/Ced/VivaPayments/Controller/Viva/Callback.php on line 113

**Comment by VivaWalletSupport** [comment]
Please verify you are using the credentials an payment source from the live environment and that the payment source is also activated.

**Comment by NoSGR** [comment]
I've double-checked them without any luck.

I've also updated the plugin with the latest files you've got here, and now i'm getting a blank screen. 

The URL of the blank screen is: <site_url>vivapayments/viva/callback/?t=6d124433-f93a-4d68-a77a-c694b6b13133&s=7237529656472603&lang=en-US

Here is a screenshot of my configuration:

![screenshot-2018-2-7-configuration-settings-stores-magento-admin](https://user-images.githubusercontent.com/14458818/35906110-0e473efc-0bf2-11e8-9efa-5b4d6a2096f4.jpg)

**Comment by VivaWalletSupport** [comment]
Please check again in the demo environment if everything works ok (failed / success transactions).

**Comment by NoSGR** [comment]
Hello,

I've just placed demo information and i'm getting this error:

Notice: Trying to get property of non-object in /app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 167

**Comment by NoSGR** [comment]
I've changed http://demo.vivapayments.com to https://demo.vivapayments.com and now it worked but again after the payment with the Demo Credit card details, i get blank page.

**Comment by VivaWalletSupport** [comment]
Please send me a screenshot of your extension settings, payment source setting and your store URL to vivawalletgithubsupport@hellasboost.gr and send a cc to ecommerce-support@vivawallet.com

**Comment by NoSGR** [comment]
Ok you'll have them in next 5 minutes.

**Comment by NoSGR** [comment]
Mail sent.

**Comment by NoSGR** [comment]
Issue solved with the updated controller file. Thank you for your support!

**Comment by kostGX** [comment]
@NoSGR Cool! Can you please share how you updated the controller file, because I'm having a friend dealing with the same problem? 

Thanks in advance.

**Comment by VivaWalletSupport** [comment]
The controller file has been updated on Github https://github.com/VivaPayments/API/blob/master/Plugins/magento/magento2_vivawallet/Ced/VivaPayments/Controller/Viva/Callback.php

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.
