### ISSUE TITLE
Webhook response wrong amount (bigger) on cash payment method

### ISSUE THREAD

**Issue by spyrosdiam** [VivaPayments/API#469]
In my application I have created a webhook to receive and manage the successful payment transactions. The payment methods card charge, DIAS and viva wallet returns the correct  amount of the  payment notification (orderCode). If a client pays with cash on a viva spot, the webhook returns an incorrect amount (always +1 euro).

example transaction id c59a80d9-4c49-4b9c-b630-1b9144bc806c

**Comment by dpnevmatikos** [comment]
@spyrosdiam the transaction amount you are receiving from the webhook is correct.

Please note that Orders paid at Viva Spots are subject to Reseller fees, so if you want to calculate
the amount without fees you will need to subtract the ```TotalFee``` from the ```Amount``` (both included in the webhook's data)

**Comment by spyrosdiam** [comment]
@dpnevmatikos As regards the payments via DIAS, why the `TotalFee` is 0 ?

**Comment by dpnevmatikos** [comment]
Because there is no fee to be paid :)

**Comment by spyrosdiam** [comment]
@dpnevmatikos No, there is a fee for every transaction via Dias (0.30 euro, 0.50 euro) etc

**Comment by dpnevmatikos** [comment]
Well actually this is a different type of "fee" called commission (bank commission in the discussed case). 
Check the ```TotalCommission``` property of the webhook's data.
