### ISSUE TITLE
Διασύνδεση με ecwid

### ISSUE THREAD

**Issue by agirosis** [VivaPayments/API#473]
Καλησπέρα,

Έχω ολοκληρώσει τη δημιουργία ενός e-shop στο  https://www.ecwid.com/ και επιθυμώ τη σύνδεση του με την υπηρεσία Viva ώστε να μπορούν οι πελάτες να ολοκληρώνουν τις παραγγελίες τους με πληρωμή με κάρτα.
Πως μπορώ να ενσωματώσω το Viva Payment Gateway στο site.

Με εκτίμηση,
Δημήτρης

**Comment by dmihos** [comment]
Hi, please have a look at the [wiki pages](/VivaPayments/API/wiki), you will, most probably, find all the info you need.

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.
