### ISSUE TITLE
Διασύνδεση με Shopify

### ISSUE THREAD

**Issue by gdotw** [VivaPayments/API#474]
Καλησπέρα,

Στήνουμε ένα eshop σε Shopify με ένα paid template της Sandbox και επιθυμούμε την σύνδεση του με την υπηρεσία Viva ώστε να μπορούν οι πελάτες να ολοκληρώνουν τις παραγγελίες τους με πληρωμή με κάρτα.

Από την μεριά της Viva, όλα είναι έτοιμα και ο λογαριασμός έχει εγκριθεί κανονικά και έχω λάβει 
MerchantId & StoreToken για Demo Enviroment απο εκεί και περα δεν γνωρίζω καθόλου την διαδικασία.

Αυτό που χρειάζομαι είναι κάποιος να με καθοδηγήσει αναλυτικά, από την αρχή μέχρι το τέλος, ώστε να γίνει η ένωση. Λογικά θα χρειαστεί κάποιο Payment Gateway, για να φανούν τα πεδία της Viva στην περιοχή Payment Methods του Shopify γιατί αυτήν την στιγμή δεν το εμφανίζει σαν επιλογή καθόλου, δεν γνωρίζω όμως καθόλου την διαδικασία, και τον τρόπο για να ενσωματωθεί να τεσταριστεί και να δουλέψει στο shopify eshop μου.

Με εκτίμηση,
Καλοκαίρης Γιώργος

**Comment by kostGX** [comment]
Καλησπέρα Γιώργο,

Διάβασε εδώ https://github.com/VivaPayments/API/wiki/Shopify-Integration#adding-viva-wallet-to-shopify για βήματα για αυτό ακριβώς που ψάχνεις.

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.
