### ISSUE TITLE
Why to remove "name" attributes from the form?

### ISSUE THREAD

**Issue by aleksanderd** [VivaPayments/API#476]
Hi!

We have some pre submit validators for the form and its logic is depend on input's name attribute.
So when we call `VivaPayments.cards.setup`  the form validation do not work anymore :(

Is it possible to disable name removing? Or what logic must be implemented? 

Currently it is like this:
1) Init the form with our custom validators.
2) On submit check validators, and if not valid => cancel submit with validation errors, etc
3) If custom validation is passed ok, send `VivaPayments.cards.requestToken()`
4) if not success, show errors at the form and go to 2.
5) if all ok, submit the form to server side action to process Viva API, etc

Thank you!

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.
