### ISSUE TITLE
Test card doesn't work

### ISSUE THREAD

**Issue by apahomov** [VivaPayments/API#477]
Hello
I'm trying to integrate Viva to our site, but I can't test it: in demo environment test card doesn't work for me - I use 4111111111111111 number with 111 CVV, but get error `This card does not support electronic transactions. In order to complete this payment please use a different card, or add funds to your Viva Wallet.`
![image](https://user-images.githubusercontent.com/721932/36263073-53be46cc-127a-11e8-9069-d3a9638b3caf.png)
What am I doing wrong?

Thanks

**Comment by dpnevmatikos** [comment]
Hi ,
Can you please try again ?

**Comment by apahomov** [comment]
Same response

**Comment by dpnevmatikos** [comment]
What's your demo merchant Id?

**Comment by apahomov** [comment]
it is `41194e23-553b-4a63-b0e9-973a2364d140`

**Comment by dpnevmatikos** [comment]
Your account settings are ok now. Please try again.

**Comment by apahomov** [comment]
Yes, now it's working. Thanks!
