### ISSUE TITLE
Magento 2.1.7 Issue with module

### ISSUE THREAD

**Issue by webjardev** [VivaPayments/API#478]
Hello,

I have created a website in Magento 2.1.7 and I use the module you have in github for payments. In test environment it works great but in live environment I get an error on Callback "Undefined variable resultObj". Could you please help me resolve this issue. Thank you

**Comment by VivaWalletSupport** [comment]
Are you using the latest version (as it was updated 8 days ago)?

**Comment by webjardev** [comment]
No but when i did change all the files you changed in your latest commit I get a blank page with a 400 error.

**Comment by VivaWalletSupport** [comment]
Did you clear cache / recompile after you updated the files from my latest commit?

**Comment by webjardev** [comment]
Yes, I cleared cache and recompiled my code but I still get a blank page on callback.

**Comment by VivaWalletSupport** [comment]
Please contact me at vivawalletgithubsupport@hellasboost.gr and send a cc to ecommerce-support@vivawallet.com to investigate the problem.

**Comment by webjardev** [comment]
Problem solved! I didn't have the right Transaction URL in settings (http instead of https) which was causing the issue. Also I was testing with an amount less than 0,30 euros which are the minimum accepted.
