### ISSUE TITLE
redirection

### ISSUE THREAD

**Issue by newitamea** [VivaPayments/API#48]
Καλημέρα,

Η ανακατεύθυνση στο κουμπί πώλησης δεν λειτουργει, παρόλο που έχει εγκριθεί η ανακατεύθυνση στο site μας. (Υπάρχει ακόμα η ειδοποιηση που λέει οτι χρειάζεται έγκριση) Η δοκιμές που κάναμε ανακατευθύνουν πάλι σε εσάς

Μπορείτε να το δείτε

ΑΦΜ: 997399330

**Comment by dmihos** [comment]
Καλησπέρα newitamea

Λυπάμαι για την καθυστερημένη απάντηση στο ερώτημά σας. 
Βλέπω ότι έχετε κάνει επιτυχημένη συναλλαγή μετά την αποστολή αυτού του issue.
Αντιμετωπίζετε κάποιο πρόβλημα ακόμη με τη διασύνδεση;

**Comment by newitamea** [comment]
Καλιο αργα παρα ποτε. Το redirection δεν δουλευει.  Εχουμε βαλει το url
αλλα δεν ανακατευθηνει
Στις 31 Μαρ 2016 2:35 μ.μ., ο χρήστης "dmihos" <notifications@github.com>
έγραψε:
>
> Καλησπέρα newitamea
>
> Λυπάμαι για την καθυστερημένη απάντηση στο ερώτημά σας.
> Βλέπω ότι έχετε κάνει επιτυχημένη συναλλαγή μετά την αποστολή αυτού του
issue.

**Comment by defilerc** [comment]
Καλησπέρα @newitamea ,

Υπάρχει κάπου deployed η λύση του site σας με το συγκεκριμένο πρόβλημα, ώστε να μπορέσουμε να κάνουμε κάποια δοκιμή;

Ευχαριστούμε πολύ

**Comment by defilerc** [comment]
Κλείνουμε το issue, λόγω απουσίας κάποιας δραστηριότητας για πάνω από ένα μήνα. 

Σε περίπτωση που ακόμα ενδιαφέρεστε για υποστήριξη και δεν έχετε επιλύσει το πρόβλημά σας, μπορείτε να ξανά ανοίξετε το συγκεκριμένο issue ή να δημιουργήσετε κάποιο νέο.

Με εκτίμηση
