### ISSUE TITLE
Error 422: PaymentsNoBinRouteFound

### ISSUE THREAD

**Issue by aleksanderd** [VivaPayments/API#480]
Hi!

After getting the token and creating an order (`api/orders` - ok) I have an error at `api/transactions` request, here the response:  

![default](https://user-images.githubusercontent.com/5766592/36416767-17faa184-163b-11e8-89eb-06f286642e0f.png)

Could you answer some questions to make this clear, plz:
1) What means the 422 error and `PaymentsNoBinRouteFound` message? Is there any docs for this case?
2) Is it ok I using demo(not verified) account?
3) Is there any geo IP restrictions/etc?

Thank you!

**Comment by aleksanderd** [comment]
update.

is it ok if transactionId is null at token response?

![default](https://user-images.githubusercontent.com/5766592/36423347-b191f242-1650-11e8-8212-18da925fd61b.png)

**Comment by odysseas12** [comment]
Any luck with this ? Im having the same issue.

**Comment by aleksanderd** [comment]
@odysseas12 no, in private discuss they said:
> We are facing issues with the demo environment so go live at once.

**Comment by kostGX** [comment]
Στη σελίδα πληρωμής, πλέον, ο πελάτης μπορεί να αλλάξει σε ελληνική γλώσσα.
Η default παραμένει η αγγλική, χωρίς δυνατότητα παραμετροποίησης, προς το παρόν.
Ευχαριστούμε
