### ISSUE TITLE
Viva integration 

### ISSUE THREAD

**Issue by GRANDX1** [VivaPayments/API#482]
Hi!
All questions listed in the file attached.

regards,

Svetla
[Viva Payment Integration_Questions.docx](https://github.com/VivaPayments/API/files/1746952/Viva.Payment.Integration_Questions.docx)
na

**Comment by kostGX** [comment]
Hello and thanks for your questions.

I've answered with green highlighted text below.

[Viva.Payment.Integration_Questions.docx](https://github.com/VivaPayments/API/files/1747304/Viva.Payment.Integration_Questions.docx)

**Comment by GRANDX1** [comment]
Thank you! That was super fast :)
