### ISSUE TITLE
ErrorCode 422

### ISSUE THREAD

**Issue by odysseas12** [VivaPayments/API#486]
I am trying to implement the Native checkout using your sample code.

I created a demo account and using those credentials.

This is the response I get back.

stdClass Object
--
  | (
  | [Emv] =>
  | [Amount] =>
  | [StatusId] => E
  | [CurrencyCode] =>
  | [TransactionId] =>
  | [ReferenceNumber] =>
  | [AuthorizationId] =>
  | [RetrievalReferenceNumber] =>
  | [ErrorCode] => 422
  | [ErrorText] => PaymentsNoBinRouteFound
  | [TimeStamp] => 2018-02-27T01:49:31.2665563+02:00
  | [CorrelationId] =>
  | [EventId] => 2054
  | [Success] =>
  | )

Please advice.

**Comment by dpnevmatikos** [comment]
Hello ,
What's your demo merchant id?

**Comment by odysseas12** [comment]
Hi, 
Merchant id is : ee8c7898-639b-4319-a6a9-6880add32ecd

**Comment by dpnevmatikos** [comment]
Can you please try again ? Try using the test card with number '4111111111111111'.

**Comment by odysseas12** [comment]
Yes its working fine now.

Thanks.
