### ISSUE TITLE
OSCommerce problem with Viva redirection back to checkout page

### ISSUE THREAD

**Issue by Barbutis** [VivaPayments/API#487]
After the checkout process, Viva module redirects to the Viva payment page where the user has to input his/her card credentials. Payment is handled correctly and both the customer and the merchant see the payment. (So far so good). The problem is when the Viva page redirects back to the eshop, The user is redirected to the login page where he is logged out and prompted to login in again. When he logs in the cart products are still there and the order has not been processed. Everything is double/triple checked. Payment source is correct and added to module. MerchantID is added, api key also. Is there anything we can do?

**Comment by VivaWalletSupport** [comment]
Could you post a screenshot of the payment source settings?

**Comment by Barbutis** [comment]
The "Enable Vivawallet Module" is obviously false because we're testing on a live server and we don't want anything to happen.
![viva_screenshot](https://user-images.githubusercontent.com/11193620/36732606-e580d286-1bd6-11e8-9e7d-4a170ee01784.png)

**Comment by VivaWalletSupport** [comment]
I would suggest to test first in the demo mode (rename the title in the language files to something that indicates a demo/test).

**Comment by Barbutis** [comment]
That suggestion is not really helpfull. I am currently testing on that live server, just reenabling/redisabling the module when i'm not using it. Do you have any possible solution for my problem? (i am not trying to be mean, just that that particular answer was not meant to be of help). I have also tried some solutions posted by others such as enabling cookie domain paths and meddling with checkout_success and checkout_process but nothing seems to work.

**Comment by VivaWalletSupport** [comment]
Without being able to make a test transaction I cannot perform any check. Also it is a good practice to test the payment gateway in the demo environment and to go live only after everything is working correctly in that environment.

**Comment by Barbutis** [comment]
I reenabled the module and activated the demo mode. Also i changed the price of this specific product <https://www.germanos.parts/catalog/product_info.php?products_id=4881> to 0,01 euro in case you need to buy anything. Is there anything else i can do to assist you in your testings?

**Comment by VivaWalletSupport** [comment]
I would suggest to increase the price of the demo product as the minimum order amount is 30 cents.

**Comment by VivaWalletSupport** [comment]
Also make sure you use the Merchant ID / API key / Payment Source Code from the demo environment.

**Comment by Barbutis** [comment]
Good morning and sorry for the delayed answer, we just had to contact Viva in order to create the demo account. Well, we created it and we set it up in our site. As instructed by Viva (something you probably already know) the demo credentials are 4111 1111 1111 1111 for card number, and 111 for CVV2; all other fields are of no importance. Is there anything else you need to make your tests?

**Comment by VivaWalletSupport** [comment]
Hello, could you post a screenshot of the demo payment source settings having the endings of the Success / Fail entries visible?

**Comment by Barbutis** [comment]
Ofc. I have the success/failure urls written at the bottom cause i also that the "catalog/" part is also usefull.

![viva_screenshot-2](https://user-images.githubusercontent.com/11193620/36838754-b90f0948-1d48-11e8-8fe3-a4b4010682c7.png)

**Comment by VivaWalletSupport** [comment]
Please contact me at vivawalletgithubsupport@hellasboost.gr and send a cc to ecommerce-support@vivawallet.com to investigate the problem.
