### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by alexandros-iordanidis** [VivaPayments/API#488]
Hi, is there any way to see the errors of the transaction?

After the payment i get redirected to fail.php and got an error code "7593067358672607" an nothing more.

**Comment by VivaWalletSupport** [comment]
Hello, are you using a specific plugin and do you have the problem in the live or demo environment?

**Comment by alexandros-iordanidis** [comment]
Hi, i'm in live mode, i use the prestashop module.

The redirection to viva is successful without any errors and after the submission of the card info i get redirected to failure url that is the fail.php

Is there any way to find out what the error code stands for? Some log maybe?

**Comment by VivaWalletSupport** [comment]
What transaction amount was used and is there any info about the transaction in your Viva account?

**Comment by alexandros-iordanidis** [comment]
The amount was 0.1 EUR.
No there is no transaction info in my account

**Comment by VivaWalletSupport** [comment]
Minimum transaction amount is 30 cents, try a transaction with 1 Euro, you can cancel it afterwards from your Sales.

**Comment by alexandros-iordanidis** [comment]
Ok, thank you.
That was indeed causing the issue.

**Comment by VivaWalletSupport** [comment]
Great to hear so, please close this ticket in case the issue has been solved.
