### ISSUE TITLE
makePayment api request using native resulting into  PaymentsNoBinRouteFoundTransaction error.   

### ISSUE THREAD

**Issue by arjrldev** [VivaPayments/API#489]
After getting the token and creating an order (api/orders - ok) I have an error at api/transactions request, here the response:

URL: https://demo.vivapayments.com/api/transactions
PaymentRequest Object
(
    [Amount] => 100
    [OrderCode] => 3476764346872609
    [SourceCode] => 5924
    [CreditCard] => Array
        (
            [Token] => [generated_token]
        )

    [Installments] => 0
)
Result: PaymentsNoBinRouteFoundTransaction Failure

Please let me know what I am doing wrong. Is it code level issue or account setting issue?

Thanks in advance

**Comment by kostGX** [comment]
Closing as issue was last updated > 4 months. Please re-open with an update comment if you still need help with this.
