### ISSUE TITLE
Πρόβλημα με το Public Key στο www.papnet.gr - Error: Status Code: 404 Account token was not found for key 6ptCfMHVzSv0oz09xZwt0aLUschKTHRvxhHlb6EEqCo=

### ISSUE THREAD

**Issue by compustargr** [VivaPayments/API#49]
Καλησπέρα σας,

Έχουμε φτιάξει ένα ηλεκτρονικό κατάστημα σε OpenCart (ver.2.1.0.1) - (www.papnet.gr) και αγοράσαμε επίσης και ένα plugin το οποίο επιτρέπει την πληρωμή μέσω VIVA (υποστηρίζει redirect & native).

Εγκαταστήσαμε και ρυθμίσαμε με την βοήθεια του Author το συγκεκριμένο plugin και ενώ φαίνεται να λειτουργεί κανονικά (σε redirect σύμφωνα με τον author που το δοκίμασε), όταν το ρυθμίζουμε να λειτουργήσει ως Native, κατά την διαδικασία αγοράς και στο τελευταίο βήμα εισαγωγής στοιχείων της κάρτας, εμφανίζει στο Network Reporter του browser (πχ firefox) το παρακάτω error:

Status Code: 404 Account token was not found for key 6ptCfMHVzSv0oz09xZwt0aLUschKTHRvxhHlb6EEqCo=
*Σας επισυνάπτουμε και το σχετικό printscreen.
![public_key-error](https://cloud.githubusercontent.com/assets/17579351/13442926/3d54b652-e007-11e5-992c-5e56e8df43ca.png)

Όλες οι ρυθμίσεις στο plugin (μέσα στο Open Cart) καθώς και στο account του πελάτη στην VIVA, έχουν πραγματοποιηθεί σωστά (σύμφωνα πάντα με τις οδηγίες του author και της VIVA αντίστοιχα).
*Σας επισυνάπτουμε και τα σχετικά printscreens.
![printscreen-opencart](https://cloud.githubusercontent.com/assets/17579351/13443036/c93f8c46-e007-11e5-8e25-24f7877cb402.png)
![printscreen-viva_account](https://cloud.githubusercontent.com/assets/17579351/13443042/d1a705c6-e007-11e5-91fe-25565d31430a.png)

Στο τελευταίο μήνυμά του ο author του plugin, μας διαβεβαιώνει ότι το plugin του λειτουργεί άψογα και ότι ο server της VIVA απορρίπτει το Public Key ή ότι το Public Key είναι λανθασμένο.

Παρακαλούμε πολύ για την άμεση εξυπηρέτησή σας και επίλυση του συγκεκριμένου ζητήματος, ώστε να εξυπηρετηθεί άμεσα και ουσιαστικά ο πελάτης.

Σας ευχαριστούμε εκ των προτέρων.

**Comment by dpnevmatikos** [comment]
Καλημέρα σας,
Οι δοκιμές που προσπαθείτε να κάνετε είναι στο παραγωγικό ή στο demo περιβάλλον?

**Comment by compustargr** [comment]
Καλημέρα σας,
Όπως φαίνεται και στο printscreen που σας έστειλα (ρυθμίσεις στο plugin του author - εντός του OpenCart), η σχετική ρύθμιση είναι σε "κανονική λειτουργία".
Αυτός είναι ο λόγος που εμφανίζει το error; Υποτίθεται ότι όλα αυτά τα έχει δει και ο author.
Σας ευχαριστώ.

**Comment by dpnevmatikos** [comment]
Αν με τον όρο "κανονική λειτουργία" εννοούμε το παραγωγικό περιβάλλον, τότε το πρόβλημα είναι οτι το plugin κάνει request στο url του demo περιβάλλοντος ```demo.vivapayments.com``` (δείτε το πρώτο σας screenshot).
Επομένως για να δουλέψει σωστά η διαδικασία και να μην παίρνετε αυτό το error θα πρέπει να ρυθμίσετε το plugin ώστε τα requests να πηγαίνουν στο ```www.vivapayments.com```.
Οδηγίες για αυτό θα πρέπει να σας δοθούν από τον author του plugin.

**Comment by compustargr** [comment]
Ωστόσο, ρύθμισα το plugin και σε demo λειτουργία και πάλι έβγαλε το ίδιο error.
Έπειτα δοκίμασα να κάνω και άμεσο request προς τον server σας, τροποποιόντας το link μέσα από την κονσόλα Network του Firefox, αφαιρόντας την λέξη "demo" και πάλι δεν δούλεψε.
Σας στέλνω 3 σχετικά printscreens για την διαδικασία αυτή που ακολούθησα.
![printscreen-1](https://cloud.githubusercontent.com/assets/17579351/13456142/4d2b4baa-e06a-11e5-8e20-110c8da1ac68.png)
![printscreen-2](https://cloud.githubusercontent.com/assets/17579351/13456157/5c10d838-e06a-11e5-9d87-58030ee24976.png)
![printscreen-3](https://cloud.githubusercontent.com/assets/17579351/13456169/66eb4ac2-e06a-11e5-83d9-ea04ef72bc63.png)
Δεν θα έπρεπε με αυτό το request να δουλέψει;

**Comment by dpnevmatikos** [comment]
Μπορείτε να κάνετε μια δοκιμή με τον παρακάτω κώδικα?  
https://gist.github.com/dpnevmatikos/c6deaf886b6e36628431

Αντιγράψτε τον σε ένα html αρχείο, αντικαταστήστε τη μεταβλητή ```publicKey``` με το δικό σας και δοκιμάστε να δείτε αν σας φέρνει token και δόσεις.

**Comment by compustargr** [comment]
Έφτιαξα 1 αρχείο test.html και το έτρεξα και από το pc και online μέσα από το public directory του site του πελάτη μου. Σας στέλνω τα αποτελέσματα με 2 printscreens:...
![test-html_1](https://cloud.githubusercontent.com/assets/17579351/13457084/dc9dc61a-e06e-11e5-805e-ab6d912d9c78.png)
![test-html_2](https://cloud.githubusercontent.com/assets/17579351/13457090/e74e0c64-e06e-11e5-9892-0bdb521712cd.png)
...καθώς επίσης και το (προσωρινά) ενεργό ακόμη link με το αρχείο test.html για να το δείτε και εσείς εφόσον το επιθυμείτε (https://www.papnet.gr/test.html).
Ποιό είναι τελικά το συμπέρασμα από τα παραπάνω;

**Comment by dpnevmatikos** [comment]
Το συμπέρασμα από τον παραπάνω δοκιμαστικό κώδικα είναι οτι το κλειδί που έχετε είναι valid στο παραγωγικό περιβάλλον. 
Όπως βλέπετε απο το 2ο screenshot ο server γυρνάει κανονικά απαντηση στο request που κάνετε.
Ο κώδικας ο οποίος σας ζήτησα να τρέξετε είναι ένα sample για τον τρόπο χρήσης της Native Checkout.
Επομένως αφού το sample δουλεύει όπως προβλέπεται, θα πρέπει να επικοινωνήσετε με τον author του plugin για περισσότερες λεπτομέρεις ως προς το τι φταίει. Το plugin θα έπρεπε 
να λειτουργεί σωστά στο παραγωγικό περιβάλλον εφόσον το sample δουλεύει σωστά.

**Comment by compustargr** [comment]
Και το πινακάκι που εμφανίζεται στο 1ο printscreen γιατί εμφανίζεται;
Αυτό συμβαίνει όταν κάνουμε κλικ στο πεδίο CVV (για 1η φορά) και αφού φυσικά έχουμε συμπληρώσει τα 2 προηγούμενα πεδία "Cardholder" & "Cardnumber".

**Comment by dpnevmatikos** [comment]
Το πινακάκι αυτό είναι μέρος του sample κώδικα και δείχνει τις επιτρεπόμενες δόσεις.
Όπως σωστά παρατηρήσατε εμφανίζεται μόλις έχει συμπληρωθεί o αριθμός της κάρτας.

**Comment by compustargr** [comment]
Ωραία λοιπόν... εφόσον με διαβεβαιώνετε (ως VIVA) ότι το πρόβλημα δεν δημιουργείται από εσάς, θα επικοινωνήσω άμεσα με τον Author του plugin (για ακόμη μία φορά), για να του αναφέρω τα όσα συζητήσαμε.

Σας ευχαριστώ πολύ για τον χρόνο σας.
