### ISSUE TITLE
Shopify IVR

### ISSUE THREAD

**Issue by nestoras** [VivaPayments/API#490]
Καλησπέρα σας,

Υπάρχει δυνατότητα να απενεργοποιηθεί το IVR σε Shopify ;

Ευχαριστώ

**Comment by dmihos** [comment]
Καλησπέρα σας
Ναι είναι στα άμεσα πλάνα να απενεργοποιηθεί.

**Comment by kostGX** [comment]
Καλησπέρα @nestoras, ενημερώνω πως έχει απενεργοποιηθεί το IVR στο Shopify.
