### ISSUE TITLE
ΠΡΟΒΛΗΜΑ ΜΕ OPENCART 2.2

### ISSUE THREAD

**Issue by krokeatis84** [VivaPayments/API#491]
καλημέρα σας
κατά την προσπάθεια συναλλαγής μέσω vivawallet και αφου καταχωρούμε τα στοιχεία της κάρτας εμφανίζεται το συνημμένο σφάλμα.

η πλατφόρμα ειναι opencart 2.2.0.0 και έχει γινει εγκατάσταση κ παραμετροποίηση του plugin που υπάρχει στο github. 

any suggestions ?
ευχαριστώ

![screen shot 2018-03-06 at 10 58 40](https://user-images.githubusercontent.com/22301939/37023027-59fbcc82-212d-11e8-8300-904d5078ec81.png)
![screen shot 2018-03-06 at 10 57 20](https://user-images.githubusercontent.com/22301939/37022967-2d8b6784-212d-11e8-9f70-238846cf6a64.png)

**Comment by VivaWalletSupport** [comment]
Hello, are you in demo or live mode and what transaction amount is used?

**Comment by krokeatis84** [comment]
i am in Live mode and the amount is 0.10€

**Comment by VivaWalletSupport** [comment]
Minimum amount is 30 cents.

**Comment by krokeatis84** [comment]
many thanks :)
