### ISSUE TITLE
Opencart 2.3 vivawallet plugin server error

### ISSUE THREAD

**Issue by costaspetrou** [VivaPayments/API#492]
Good Afternoon, 

We have set up the payment source in our Vivawallet account and installed the latest version of the vivawallet plugin in opencart 2.3.0.2 (plugin downloaded from here: https://github.com/VivaPayments/API/tree/master/Plugins/opencart/Opencart%202.3)

The opencart extention is saved with no issue.

When the customer is about to continue to choose payment methods, it is thrown an Internal Server Error and cannot proceed.
The server log is:

```
Stack trace:
#0 [internal function]: Loader->{closure}(Array, Array)
#1 /system/engine/proxy.php(25): call_user_func_array(Object(Closure), Array)
#2 /catalog/controller/checkout/payment_method.php(53): Proxy->__call('getMethod', Array)
#3 //catalog/controller/checkout/payment_method.php(53): Proxy->getMethod(Array, 3293)
#4 [internal function]: ControllerCheckoutPaymentMethod->index()
#5 /system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array)
#6 /catalog/controller/startup/router.php(25): Action->execute(Object(Registry))
#7 [internal function]: ControllerStartupRouter->index()
#8 /system/storage/modification/system/e in /system/storage/modification/system/engine/loader.php on line 169 
```

Please advise what could be wrong.

Kind regards
avshop.avsys.gr  -- Team

**Comment by VivaWalletSupport** [comment]
Hello, are you in the demo or live environment and can you post a screenshot of the modules settings (hide merchant id and api key)?

**Comment by costaspetrou** [comment]
Hello, The extension has been setup for the live envirnment. 
![vivapayment](https://user-images.githubusercontent.com/36242500/37118048-93ca1408-225b-11e8-999e-2658ec27225d.jpg)

**Comment by VivaWalletSupport** [comment]
Has the payment source been activated or is it still pending?

**Comment by costaspetrou** [comment]
It is active.

**Comment by VivaWalletSupport** [comment]
Please send me ftp / admin access if possible at vivawalletgithubsupport@hellasboost.gr and send a cc to ecommerce-support@vivawallet.com to investigate the problem.

**Comment by kostGX** [comment]
Closing as issue was last updated > 3 months. Please re-open with an update comment if you still need help with this.
