### ISSUE TITLE
Redirection problem

### ISSUE THREAD

**Issue by VasilisMoustakas** [VivaPayments/API#494]
Καλημέρα, έχουμε ολοκληρώσει τη λύση redirect, γίνεται κανονικά η πληρωμή, ελέγχουμε βάση το transaction code και είναι ολα οκ. Το πρόβλημα είναι πως ο πελάτης μόλις ολοκληρώσει την πληρωμή δεν κάνει redirect στη success σελίδα που έχουμε δηλώσει στο payment source και παραμένει στην σελίδα ολοκλήρωσης συναλλαγής της viva

**Comment by VivaWalletSupport** [comment]
Hello, are you using a specific plugin or did you code your own solution?

**Comment by VasilisMoustakas** [comment]
custom code

**Comment by VivaWalletSupport** [comment]
I would suggest to post the code used to generate the order before the customer is redirected, so someone might see what goes wrong.

**Comment by kostGX** [comment]
Closing as issue was last updated > 2 months. Please re-open with an update comment if you still need help with this.
