### ISSUE TITLE
Επαναλαμβανόμενες χρεώσεις - WooCommerce

### ISSUE THREAD

**Issue by asynadak** [VivaPayments/API#495]
Καλησπέρα,

προσφέρουμε κάποιες συνδρομητικές υπηρεσίες μέσα από την ιστοσελίδα μας (μηνιαίες ή ετήσιες), οπότε θα θέλαμε να ενεργοποιήσουμε την δυνατότητα αυτή και στο κομμάτι της πληρωμής. Δηλαδή, ανά ένα μήνα (ή ανά ένα έτος), να χρεώνεται αυτόματα η κάρτα ή ο λογαριασμός του πελάτη.

Πως μπορεί να γίνει αυτό στο WooCommerce;

Σας ευχαριστώ πολύ εκ των προτέρων.

**Comment by VivaWalletSupport** [comment]
Please have a look at https://support.vivawallet.com/hc/en-us/articles/201403771-How-can-I-make-a-recurring-payment-via-the-API-

**Comment by asynadak** [comment]
Great, thanks! I'll take a look at it.

**Comment by asynadak** [comment]
Hello again,

beside using the API, is there a way to enable recurring payments through the woocommerce plugin? I've enabled recurring payment in vivawallet settings, but there isn't an option in woocommerce plugin dashboard to enable there as well.

Am I missing something or I need to developed this feature in the plugin?

Thanks in advance.

**Comment by VivaWalletSupport** [comment]
There is not option in the plugin settings, you would have to add the parameter AllowRecurring=true to the code (wc-vivawallet.php).

`$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&PaymentTimeOut=300';
`
`$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&PaymentTimeOut=300&AllowRecurring=true';
`

**Comment by asynadak** [comment]
Great! That works! Thank you a lot.
