### ISSUE TITLE
Redirection demo to live not working

### ISSUE THREAD

**Issue by Ko2ta2** [VivaPayments/API#497]
I tried to change from demo enviroment to live but I get error code "Bad Request"
The viva walet id=Wallet ID 542971789387

The code I'm using is:
$request =  'https://www.vivapayments.com/api/orders';
$MerchantId = the one I get from live account
$APIKey =  the one I get from live account
$postargs = 'Amount='.urlencode($Amount).'&AllowRecurring='.$AllowRecurring.'&RequestLang='.$RequestLang.'&SourceCode='.$Source.'&MerchantTrns='.$MerchantTrns.'&Email='.$Email.'&Phone='.$Phone;

// Get the curl session object
$session = curl_init($request);
// Set the POST options.
curl_setopt($session, CURLOPT_POST, true);
curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
curl_setopt($session, CURLOPT_HEADER, true);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
// Do the POST and then close the session
$response = curl_exec($session);
// Separate Header from Body
$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
$resHeader = substr($response, 0, $header_len);
$resBody =  substr($response, $header_len);
curl_close($session);

If I print the $response get from the above program, I get nothing, when on the demo account I get.

For moving to viva wallet link I use the following coding:
header("Location:https://www.vivapayments.com/web/newtransaction.aspx?ref=$orderId");

The final result is https://www.vivapayments.com/web/newtransaction.aspx?ref= and bad request message on screen.

Thanks for you help.

**Comment by VivaWalletSupport** [comment]
Try replacing:
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

By:
$curlversion = curl_version();
if(!preg_match("/NSS/" , $curlversion['ssl_version'])){
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, "TLSv1");
};

**Comment by Ko2ta2** [comment]
Thanks, I figured it out yesterday, please update the folder CreateOrder/PHP so others can find it easy.

For the gettransactions curl what should I use (please all the example with the curl) so I can check if there is any mistakes on my coding?

Thanks

**Comment by VivaWalletSupport** [comment]
Have a look at the Magento 2 controller file to get the idea: https://github.com/VivaPayments/API/blob/master/Plugins/magento/magento2_vivawallet/Ced/VivaPayments/Controller/Viva/Callback.php and please close this ticket in case it answered your question.
