### ISSUE TITLE
No greek text on viva wallet checkout with Shopify connection

### ISSUE THREAD

**Issue by Eleftherios72** [VivaPayments/API#498]
hello
We use the viva wallet API using Shopify platform for our Greek site
Until recenlty we were redirected to the https://www.vivapayments.com/web/Checkout etc where there was an english flag and a Greek flag .
Recently the greek flag has been disappeared.... with no change from our side.
We prefered of course be default to have Greek text on viva wallet checkout page

what happened? and how we can resolve the issue

**Comment by kostGX** [comment]
It should be working now. Closing as issue was last updated > 2 months. Please re-open with an update comment if you still need help with this.
