### ISSUE TITLE
Notice: Undefined variable: mode in (enviroment: PHP file with editplus) with FTP server

### ISSUE THREAD

**Issue by SiyoungSong** [VivaPayments/API#499]
Error :  

lineNumber5: if ($mode == "insert")   /  Notice: Undefined variable: mode in /home/2017/ce1733/public_html/htdocs/score_list.php on line 5

lineNumber59 : if ($mode == "big_first")    /Notice: Undefined variable: mode in /home/2017/ce1733/public_html/htdocs/score_list.php on line 59

i don't write typing error. so why  occured execution error?

**Comment by kostGX** [comment]
Closing as issue was last updated > 2 months. Please re-open with an update comment if you still need help with this.
