### ISSUE TITLE
VivaPayments: Required data-vp attribute "cardnumber" was not found

### ISSUE THREAD

**Issue by pefremidis** [VivaPayments/API#502]
I am trying to reproduce one of my client's error but I can't.
Is there anyway you can help me with the reasons that this error might occur?

I found in the js code that this message comes inside this if

if ((e = t('[data-vp="' + u + '"]')).length == 0) {

}

Does this mean that the cardholder input is not inside the DOM?
All other customers don't have any problem.
Is there a place to dig deeper with the errors and why do the happen?

Thank you in advance

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming this problem isn't still occurring, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
