### ISSUE TITLE
Long lifetime token?

### ISSUE THREAD

**Issue by aleksanderd** [VivaPayments/API#504]
Hi!

A question about native checkout token which getting via js at the form: how long it usable? 
Can we save it for future use without re-entering the card data by client?

If not, is there some way to make a payment using some long lifetime token or so, to avoid re-entering the card data which was entered once before?

Thank you!

**Comment by dpnevmatikos** [comment]
Hello @aleksanderd 
Unfortunately the token received by Native Checkout is a one time charge token.
However, there is a way of accepting recurring payments described [here](https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction). 

To make the long story short, here's what you need to do: 
1) Perform an credit card charge transaction with the token received from Native Checkout by making the API call described [here](https://github.com/VivaPayments/API/wiki/Native-Checkout#call-the-api-to-securely-process-the-payment) including the parameter ```AllowsRecurring: true```. Please note that **this parameter indicates that the cardholder has agreed on allowing recurring payments** on their card. This means that **you should be presenting the user with a checkbox** (or a UI element of your choice) which clearly states that the card may be charged more than once.

2) Once the payment is completed, store the ```TransactionId``` received from the API's response

3) Use the aforementioned ```TransactionId``` to create a recurring transaction as described [here](https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction)

Please let me know if that works out for you
