### ISSUE TITLE
Viva Simple Checkout Error 400

### ISSUE THREAD

**Issue by Ntenistromeros** [VivaPayments/API#505]
Hi, and thank you for a grate popup for a Viva payment.

We are trying to complete this plugin for opencart in php. We are using demo mode. Viva responds with Paymenttoken that we should resbmit into https://demo.vivapayments.com/api/transactions if we understood right so far. We tried to submit in json format, but we get 400 error as a response. We used demo credentials: 
Note: To simulate a successful payment on the demo environment, use the card number 4111111111111111 with any valid date and 111 for the CVV2

Part of code is below: 
	$fields_string='';
	$MerchantID = trim($this->config->get('vivawallet_merchantid'));
	$Password =  trim(html_entity_decode($this->config->get('vivawallet_merchantpass')));
	if(isset($_POST['vivaWalletToken']) && $_POST['vivaWalletToken'] !='') {
		$postargs = $_POST['vivaWalletToken'];
	} else {
		$postargs = '';
	}	
	echo "vivaWalletToken: ".$postargs;
	$fields = array ('PaymentToken' => $postargs);
	$content = json_encode($fields);
	$curl = curl_init();
	curl_setopt($curl, CURLOPT_URL,"https://demo.vivapayments.com/api/transactions");
	curl_setopt($curl, CURLOPT_USERPWD, $MerchantID.':'.$Password);
	curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);   // no verify
	curl_setopt($curl, CURLOPT_POST, 1);
	curl_setopt($curl, CURLOPT_POSTFIELDS, $content);

**Comment by kostGX** [comment]
Closing as issue was last updated > 2 months. Please re-open with an update comment if you still need help with this.
