### ISSUE TITLE
Original Credit Transaction OCT - Multiple Wallets

### ISSUE THREAD

**Issue by jkouroup** [VivaPayments/API#506]
OCT transactions (ServiceId 6) seem to always credit the Primary wallet!
That is, even if the user's initial payment (whose transactionId we use for the OCT) was debited to another sub-wallet, the Primary wallet takes the credit!

Is there a way to specify the wallet we want credited in an OCT or does the transactionId used determines the wallet as we thought.?

In case of the latter, is what we face a bug or perhaps a miss-configuration in our sub-wallet (eg. our wallet is not allowed to perform OCTs, any other suggestions...)

In case of the former, we have implemented the API as described here: https://github.com/VivaPayments/API/wiki/Original-Credit-Transaction-(OCT)
Are we missing something? Is it not up to date?

Thanks in advance

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Our latest documentation mentioning OCT is available here: https://developer.vivawallet.com/api-reference-guide/payment-api-details/#original-credit-transaction

If you have any other queries please do please let us know and we'd be happy to help. Thanks!
