### ISSUE TITLE
Viva Payments - ελληνικά αντί για Αγγλικά; (MODX-minishop2)

### ISSUE THREAD

**Issue by tatianagor** [VivaPayments/API#508]
Παρακαλώ μια βοήθεια! το e-shop μας, χτισμένο στο ModX (MODX Revolution 2.5.7-pl - minishop2), λειτουργεί στα Αγγλικά και δέχεται πληρωμές απο εξωτερικό μέσω Viva payments . Προφανώς, δεν κάναμε καποια κίνηση για να λειτουργεί εξ ολοκλήρου στα Αγγλικά, γιατι οι πελάτες μας παραπονιούνατι ότι τους εμφανήζει μηνύματα στα Ελληνικά, απ΄ότι καταλαβα σε φάση όταν δεν περνάει η πληρωμή για κάποιο λόγο... Το support του Viva με έστειλε εδώ - Χίλια ευχαριστώ εκ των προτέρων

**Comment by kostGX** [comment]
Hello @tatianagor, are you using[ a ready-made plugin?](https://github.com/VivaPayments/API/wiki/Integration-with-eCommerce-platforms) or have you made a custom integration?
