### ISSUE TITLE
Payment with Redirection

### ISSUE THREAD

**Issue by nsitsanis** [VivaPayments/API#51]
I use woocommerce with wordpress and i installed the plugin. I tried to make a payment as a test payment but the transaction failed. What can i do? can someone help me?

**Comment by dpnevmatikos** [comment]
Hi @nsitsanis ,
Unfortunately the wordpress plugin discussed is not an official Viva Wallet plugin, therefore we offer no support.
We advise that you contact the plugin's creator to give you further information.
We can only provide assistance if you provide specific details regarding the communication with our systems (error code, error message etc).

**Comment by nsitsanis** [comment]
Και δηλαδή πως μπορώ να ενεργοποιησω την λειτουργία αυτην;

**Comment by defilerc** [comment]
Hi @nsitsanis ,

Please refer to the specific plugin documentation, you're using, so you can get specific information regarding your issue.

Best regards
