### ISSUE TITLE
API transactions returns E

### ISSUE THREAD

**Issue by powersite1** [VivaPayments/API#510]
Μετά την πληρωμή επιστρέφω στο eshop στην success σελίδα, εκεί καλώ το api transactions με transaction id το t που επιστρέφετε, αλλά πάντα το StatusId είναι E, παρόλο που στον DEMO λογαριασμό φαίνεται κανονικά η πληρωμή.
Το transaction id είναι το 1e6a50d1-54fc-4d83-bc5a-cba6bc627225

**Comment by aceneeraj** [comment]
I am also getting same problem The api return a response with json with status ID= E but its okay but i have chhecked in woocommerce plugin it means "The transaction was not completed because of an error".
But what is actual error. Can any tell me what is actual meaning of Status ID = E.
