### ISSUE TITLE
Αδυναμία Πληρωμών απο E-shop / Woocommerce

### ISSUE THREAD

**Issue by zagorianos** [VivaPayments/API#511]
Καλησπέρα σας, θα ήθελα βοήθεια σχετικά με τον τρόπο πληρωμής (viva wallet) που έχω ενσωματώσει στο eshop μου. Έχουμε πολλά παράπονα απο πελάτες που ολοκληρώνουν την πληρωμη και την παραγγελία τους αλλα δεν πραγματοποιείται η πληρωμή όπως θα έπρεπε.

Σας ευχαριστώ πολύ εκ των προτέρων.

**Comment by VivaWalletSupport** [comment]
Hello, are you using a ready made plugin (if so, please provide a link to the plugin that is used) or your own implementation?

**Comment by zagorianos** [comment]
Hello,
we are using the wordpress plug in, it is definitely already made.

My regards
John Zagorianos

Στις Τρί, 17 Απρ 2018 - 12:31 ο χρήστης Tom van der Veer <
notifications@github.com> έγραψε:

**Comment by VivaWalletSupport** [comment]
if so, please provide a link to the plugin that is used..

**Comment by VivaWalletSupport** [comment]
Hello zagorianos, please close this issue in case the problem has been resolved, otherwise let me know how I can help.

**Comment by Samcronic** [comment]
καλησπερα ενω εχω βαλει ολα τα στοιχεια που χρειαζεται στο plug in οταν παω να κανω πληρωμη που εμφανιζει 404 error
τι πρεπει να κανω ευχαριστω

**Comment by VivaWalletSupport** [comment]
@Samcronic I would suggest to open a new issue, provide in detail what is used (platform/plugin) and add some screenshots of you plugin settings / Viva Wallet payment source settings (mask the API Key).
