### ISSUE TITLE
 Πρόβλημα με την αποθήκη και την πληρωμή viva payments σε woocommerce.

### ISSUE THREAD

**Issue by liakatsagoni** [VivaPayments/API#514]
Καλησπέρα!!! Η πληρωμή στο site μου γίνεται κανονικά,λαμβάνω κανονικά τα λεφτά στο λογαριασμό της viva και ο παραλήπτης ειδοποίηση από την τράπεζα του ότι πλήρωσε αλλά το woocommerce μου δείχνει ότι έχει γίνει παραγγελία και η πληρωμή είναι σε εκκρεμότητα συν το ότι εξίσου σοβαρό όταν γυρίζω την πληρωμή σε ολοκληρωμένη το απόθεμα δεν μειώνετε. 

Ευχαριστώ εκ των πρότερο για την βοήθεια!!!!

**Comment by VivaWalletSupport** [comment]
Hello, are you using a specific plugin?

**Comment by liakatsagoni** [comment]
Viva Payments – Viva Wallet WooCommerce Payment Gateway

**Comment by VivaWalletSupport** [comment]
Are you using the plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce or from another plugin provider?

**Comment by liakatsagoni** [comment]
Hey!!!
I am using this plugin
https://el.wordpress.org/plugins/woo-payment-gateway-for-vivapayments/#installation
and
it was already provided by my host service Papaki.gr

2018-04-20 14:37 GMT+03:00 Tom van der Veer <notifications@github.com>:

**Comment by VivaWalletSupport** [comment]
Its states the name of the creator on their plugin page and they offer support from there: http://prntscr.com/j7tasd

**Comment by liakatsagoni** [comment]
So calling Viva helping desk linked me to Git Hub support and you to the
creator of the plugin.
After sales support is your weak point.

2018-04-20 15:38 GMT+03:00 Tom van der Veer <notifications@github.com>:

**Comment by VivaWalletSupport** [comment]
Probably the help desk understood you used our supported plugin but it seems you are using a 3rd party plugin that offers its own support. Contact the plugin provider for any issues you have with their program or install the supported plugin from Github and post here any issues you might have with it.

**Comment by liakatsagoni** [comment]
Hello!!!
After working closely on solving out the problem I mentioned previously with the tech team of the plugin provider and after installing and trying another plugin from a different provider the problem is still there. Therefore I believe that now is the moment that you from your side should check if Viva Payments provides correctly the API and if the problem gets triggered from your information system.

Thanks for your time in advance !!!

**Comment by VivaWalletSupport** [comment]
Hello liakatsagoni, please close this issue in case the problem has been resolved, otherwise let me know how I can help.
