### ISSUE TITLE
Webhook problem

### ISSUE THREAD

**Issue by mihaifaget** [VivaPayments/API#516]
Hello. 
 Having problems adding a webhook with any url, including the magento2 module's site/vivapayments/viva/callback. Also, the magento 2 module callback url has a lot of undefined properties when accessing the callback url directly, fixed them, but still the webhook doesn't accept url.

Error! The url could not be verified. Please make sure you have entered a valid, publicly available, url that conforms to these guidelines (Error code 502)

Therefore we have no success page redirect and order status stays on pending payment.

**Comment by VivaWalletSupport** [comment]
Hello, in case you are using the vanilla VivaPayments Github Magento2 extension, it does not support the webhook functionality.

**Comment by mihaifaget** [comment]
Hello. The issue I'm talking about is not module related, we use Ced VivaPayments. The problem is on 
http://demo.vivapayments.com/ where we can not add any webhook when going to Settings->Api Access->Webhooks

**Comment by kostGX** [comment]
@mihaifaget you need to first get a Webhook verification token like here: https://github.com/VivaPayments/API/wiki/Webhooks#webhook-url-verification

You can see a PostMan screenshot here: 
<img width="899" alt="screen shot 2018-05-16 at 11 36 24" src="https://user-images.githubusercontent.com/3908736/40106235-dee36916-58fd-11e8-8740-ecf3b8d4b37e.png">

After you've done that, you need to 

1. Set your endpoint logic to return the token you received
2. Go to Viva Wallet Settings > API Access > Webhooks
3. Create a Webhook by setting your endpoint you created on step 1.
4. Click verify. Your endpoint will return the token and your webhook will be verified and added.

You're set :)

**Comment by mihaifaget** [comment]
@kostGX thanks for the info. The problem was that I am using magento module Ced_VivaPayments that doesn't have the token logic built in(though documentation mentions vivapayments/viva/callback should work). Added logic to return token and now I managed to create the webhook for Transaction Payment Created. But the webhook is ignored completely, I am stuck to payment success page in http://demo.vivapayments.com/web/checkout/result with message "Your payment was successful.". There is no redirect back to the shop, there is no option to click something to return to your shop, the webhook callback is never accessed(based on server logs and an email that should've been sent with the request parameteres), order stays in pending payment, no email received

**Comment by VivaWalletSupport** [comment]
Please verify you have setup a payment source within your Viva (demo) account and that you are using the source code (usually a four digit code) in your extensions settings.

**Comment by VivaWalletSupport** [comment]
In the payment source you would specify the return URLs (Success/Fail), in case you have not correctly setup this part you will be redirected as you described.

**Comment by mihaifaget** [comment]
I have no idea how to do that, can't find anything in documentation. All I can find is when editing payment source I can set a Success URL with predefined http://demo.vivapayments.com which will not work, I want to go back to the shop, not remain on viva payments

**Comment by VivaWalletSupport** [comment]
For setup see the documentation the extension has (scroll to the bottom): https://github.com/VivaPayments/API/tree/master/Plugins/magento/magento2_vivawallet/Ced/VivaPayments

If still a problem, post a screenshot of your payment source setup and of the extensions settings (mask your  API Key).

**Comment by VivaWalletSupport** [comment]
Hello mihaifaget, please close this issue in case the problem has been resolved, otherwise let me know how I can help.
