### ISSUE TITLE
viva sucks

### ISSUE THREAD

**Issue by oneplusdesign** [VivaPayments/API#517]

**Comment by VivaWalletSupport** [comment]
Hello, could you provide some more details about the transaction (live/demo/order amount/used card data/transaction status in Viva)?

**Comment by oneplusdesign** [comment]
Με εκτίμηση
 *Τάσος Τσικριτέας*



Κατασκευή Ιστοσελίδων
   *www.OnePlusDESIGN.com <http://www.oneplusdesign.com/>*

*Γραφεία*: Σισίνης 33, ( έναντι Hilton Hotel ) Αθήνα
                Π. Σούλου 10, ( 1ός Όροφος )    Αγρίνιο

*Phone   *: (+30 )  210 72 19 574  - 26410 20 141
*Mobile*  : (+30 ) 697 48 62 157

*Skype*   : thetasos

*E**-**mail   *: info@oneplusdesign.com
*Gmail   *: info.oneplusdesign@gmail.com


*Είμαστε σίγουροι πως μπορούμε να σας προσφέρουμε μια εφαρμογή αντάξια της
δυναμικότητά σας αλλά και των υψηλών απαιτήσεων του δικτύου. **Για
οποιαδήποτε απορία, ερώτηση ή αλλαγή  μην διστάσετε να επικοινωνήσετε μαζί
μας!  *

2018-04-20 10:30 GMT+03:00 Tom van der Veer <notifications@github.com>:

**Comment by geoadamo** [comment]
Hello,
I am having the same issue as above.
I am testing on the demo enviroment with a card number (4111 1111 1111 1111 111) and CVV 111.
The demo enviroment always redirects to the fail url (https://thinkpositive.gr/staging/index.php?wc-api=wc_vivawallet&vivawallet=fail).
![viva](https://user-images.githubusercontent.com/33297717/39047408-6d2c0608-44a2-11e8-9235-34b1ec017ed5.JPG)
No transaction is logged in my demo account.
I don't know what is the issue. Any help would be much appreciated.
Thank you
