### ISSUE TITLE
Always redirected to fail response

### ISSUE THREAD

**Issue by geoadamo** [VivaPayments/API#518]
Hello,
I have installed your woocommerce plugin and i am having issues with the payment response.
I am testing on the demo enviroment with a card number (4111 1111 1111 1111 111) and CVV 111.
The demo enviroment always redirects to the fail url (https://thinkpositive.gr/staging/index.php?wc-api=wc_vivawallet&vivawallet=fail).
![viva](https://user-images.githubusercontent.com/33297717/39048490-4b001c14-44a6-11e8-8ae1-284c8e044940.JPG)

No transaction is logged in my demo account.
Wordpress vesrion 4.9.5
Woocomerce 3.3.5
I don't know what is the issue. Any help would be much appreciated.
Thank you

**Comment by VivaWalletSupport** [comment]
Hello, what amount did you use when testing?

**Comment by geoadamo** [comment]
Hello,
The ammount was 36,40 euro. Thank you
![capture](https://user-images.githubusercontent.com/33297717/39049174-05f8215e-44a9-11e8-9f4a-48bec1a4f3ff.JPG)

**Comment by geoadamo** [comment]
Hello and thanks for this but the issue remains.
I made a product with a price of 0.25 and tried again, below is the screenshot
![viva1](https://user-images.githubusercontent.com/33297717/39064469-4bf17182-44d7-11e8-85ae-122acf0c8d52.JPG)

And a screenshot of the fail response
![viva2](https://user-images.githubusercontent.com/33297717/39064485-5972dcc4-44d7-11e8-8f00-fac276cc0c80.JPG)

Also no transaction is logged in my viva demo account.

**Comment by geoadamo** [comment]
Well ok. Rookie mistake. Sorry for waisting your time :-)
