### ISSUE TITLE
API error codes

### ISSUE THREAD

**Issue by GRANDX1** [VivaPayments/API#520]
Hi!
Where I can get API error codes and http response code?

Thank you

**Comment by artetrad** [comment]
Is there a list of the viva API ErrorCodes somewhere in the Wiki?

**Comment by matthewrgourd** [comment]
Hi @artetrad , we now have a new developer portal where these are listed:

[developer.vivawallet.com/api-reference-guide/error-responses-and-codes](https://developer.vivawallet.com/api-reference-guide/error-responses-and-codes)/
