### ISSUE TITLE
Supported types of checkout for Shopify 

### ISSUE THREAD

**Issue by kkastrad** [VivaPayments/API#522]
Hi there

Just wanted to ask what are the available checkout options for vivapayments when integrating with Shopify.  It's not very clear in the guide posted here (https://github.com/VivaPayments/API/wiki/Shopify-Integration).

Also, in the guide you are saying that Shopify through VivaPayments allows you to process " Visa, Mastercard, Maestro and Viva Wallet payments". Does this exclude American Express, Diners and Discovery Payments?

**Comment by kostGX** [comment]
Hello @kkastrad, for our GR merchants we also support American Express and Diners cards.

If your company is based outside of Greece, we currently support Visa, Mastercard and Maestro cards, in which card schemes we're Principal Members.

I've updated our documentation to better reflect that.

**Comment by kkastrad** [comment]
Hi ,

thank you for your prompt response. In the payment selection, however, the icons of American Express and Diners are not visible so it's not clear to the customer if these cards are supported. Any chance to fix this?

**Comment by kostGX** [comment]
Where is the Country of Incorporation of your business? What account country do you have? @kkastrad

**Comment by kkastrad** [comment]
Greece :)
