### ISSUE TITLE
Redirection Problem

### ISSUE THREAD

**Issue by shop365** [VivaPayments/API#523]
Τις τελευταίες μέρες έχουμε κάποιο πρόβλημα με το redirection στο viva payments. Ανοίγουμε σε iframe την σελίδα του Payment px.https://www.vivapayments.com//Web/merchantinterface/shop365/newtransaction.aspx?ref={refCode}και στο post της φόρμας μας εμφανίζει ένα json αντι να συνεχίσει το post.
πχ. 
{
  "ThreeDHtml": null,
  "CardHolderAuthenticationSessionId": "2de71709-defd-4309-bf02-6842e5a3c9f4"
}

Επίσης στην σελίδα βλέπουμε πως υπάρχουν και javascript errors.

δεν ξέρω αν έχει σημασία αλλά έχουμε υλοποιήσει την διασύνδεση με custom κώδικα. Δεν έχουμε κάνει καμία αλλαγή σε τίποτα, και μέχρι προχτές έπαιζαν όλα κανονικά

Ευχαριστώ πολύ εκ των προτέρων

![vivaerror](https://user-images.githubusercontent.com/39118105/39804344-7526cf80-537c-11e8-9264-f31488f7ff15.jpg)

![jserror](https://user-images.githubusercontent.com/39118105/39804366-837aea3a-537c-11e8-8192-4856857cab64.png)

**Comment by kostGX** [comment]
Hello @shop365, ευχαριστούμε για την αναφορά. Επηρεάστηκε η σελίδα σας για λίγη ώρα από κάποιες αναβαθμίσεις επειδή πρόκειται για μία παλαιότερη custom υλοποίηση.

Προτείνουμε αναβάθμιση στην https://github.com/VivaPayments/API/wiki/Simple-Checkout την οποία μπορείτε να κάνετε personalize, ο χρήστης δεν φεύγει από την σελίδα σας και ταυτόχρονα θα έχετε και τη δυνατότητα χρήσης 3D Secure για ακόμα μεγαλύτερη ασφάλεια στις συναλλαγές.

Καλο Σαββατοκύριακο.
