### ISSUE TITLE
Ελληνική έκδοση του viva wallet

### ISSUE THREAD

**Issue by darampatz** [VivaPayments/API#526]
Καλησπέρα,
Έχω κάνει integrate το viva wallet με το shopify. Όταν ο πελάτης φεύγει απο το  κατάστημα και γίνεται redirect στην Viva για να πληρώσει, εμφανίζεται η αγγλική έκδοση χωρίς να υπάρχει η δυνατότητα για αλλαγή στην ελληνική έκδοση.

Αυτό μπορεί να αλλάξει? Δηλαδή μετά το redirect να εμφανίζεαι η ελληνική έκδοση του viva wallet?

Ευχαριστώ εκ των προτέρων,

**Comment by isset1988** [comment]
Θα πρέπει κάπου μέσα στον κώδικα του plugin να υπάρχει μια μεταβλητή `$RequestLang`. Αντικατέστησέ τη με `$RequestLang = 'el-GR';`.

**Comment by darampatz** [comment]
Καλημέρα isset1988. Δεν υπάρχει κώδικας plugin για το shopify :(

**Comment by isset1988** [comment]
Συγγνώμη. Διάβασα λάθος. Θα πρέπει να κανουν την αλλαγή οι τεχνικοί του shopify.

**Comment by dmihos** [comment]
Καλημέρα
Στη σελίδα πληρωμής, πλέον, ο πελάτης μπορεί να αλλάξει σε ελληνική γλώσσα.
Η default παραμένει η αγγλική, χωρίς δυνατότητα παραμετροποίησης, προς το παρόν.
Ευχαριστούμε
