### ISSUE TITLE
custom code eshop php

### ISSUE THREAD

**Issue by isset1988** [VivaPayments/API#527]
Καλησπέρα σας,

Έχουμε custom website και προσπαθούμε να ρυθμίσουμε τις πληρωμές μας.
Χρησιμοποιήσαμε το create_order.php με τα στοιχεία ενός demo account.

Μας κάνει redirect και πληρώνουμε κανονικά, όμως
στο http://demo.vivapayments.com/ δεν μας κάνει redirect πίσω στο website μας.

Σας ευχαριστώ για το χρόνο σας.

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
