### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by Savikos** [VivaPayments/API#528]
Can you please check if we set up correctly the ViVa Payments account? 

The website is automotohistory.com. 

We are getting an error message although we have created a Merchant ID and an API key. 

We are using the latest version of WooCommerce.

**Comment by VivaWalletSupport** [comment]
Hello, what error do you get? Can you post a screenshot of the plugin and the payment source settings (mask the API key)?

**Comment by VivaWalletSupport** [comment]
Hello Savikos, please close this issue in case the problem has been resolved, otherwise let me know how I can help.
