### ISSUE TITLE
ERROR API 

### ISSUE THREAD

**Issue by oksanamagar** [VivaPayments/API#529]
καλησπερα σας έχω βάλει κάποιον προγραμματιστεί να μου κάνει στην ιστοσελίδα μου αυτόματες πληρωμές μέσο api και βγάζει το παρακάτω μήνυμα καμια λύση πάνω σε αυτό σας ευχαριστώ..
σε demo δουλεύει μια χαρά..

δουλεύουμε πάνω σε αυτή την φόρμα php
https://github.com/VivaPayments/API/tree/master/NativeCheckout/PHP

The following error occured: The merchant with id 8eb9f9d6-2d78-4351-b821-0c50e712f979 does not have a source with code 'Native' assigned or the source is disabledThe following error occured: Invalid codeTransaction Failure

**Comment by isset1988** [comment]
Εφόσον δουλεύεις με native checkout θα πρέπει να ενεργοποιήσεις και τις αντίστοιχες επιλογές.
`https://github.com/VivaPayments/API/wiki/Native-Checkout`

**Comment by oksanamagar** [comment]
καλησπέρα όλα τα domain που έχω συνδεμένα βγάζουνε αυτό το μήνυμα τι γίνετε?

http://prntscr.com/jm1u3q
