### ISSUE TITLE
Προβλήματα με το API της VivaPayment

### ISSUE THREAD

**Issue by ckarikas** [VivaPayments/API#53]
Καλησπέρα σας,

θα ήθελα να σας ενημερώσω πως χρησιμοποιώ το εν λόγω plugin - https://el.wordpress.org/plugins/woo-payment-gateway-viva-wallet/ για να συνδέσω το εταιρικό μου site με τη viva.

Έχω στείλει τα απαραίτητα έγγραφα που μου ζητήθηκαν και ο λογαριασμός που έχει ταυτοποιηθεί επιτυχώς σε όλα τα επίπεδα τα οποία ζητάει το site της Viva.

Όμως μου παρουσιάζεται ένα πρόβλημα: Όταν ο χρήστης πάει να ολοκληρώσει την αγορά του, μου πετάγεται ένα μήνυμα το οποίο λέει πως υπάρχει πρόβλημα ή με τα στοιχεία του χρήστη ή με το API. Ξέρετε για πιο λόγο συμβαίνει αυτό; Προσπαθώ εδώ και ένα μήνα να ενεργοποιήσω αυτόν τον λογαριασμό και μία τα προβλήματα του API, μία η καθυστέρηση ταυτοποίησης μας έχουν πάει πολύ πίσω.

Ευχαριστώ εκ των προτέρων!

**Comment by dmihos** [comment]
Καλημέρα ckarikas
Το plugin αυτό δεν έχει αναπτυχθεί από εμάς, και το error message το δίνει το ίδιο το plugin. Δείχνει να είναι κάποιο πρόβλημα στο configuration (πιθανά δεν έχετε δηλώσει σωστά στοιχεία πρόσβασης για το  API του παραγωγικό περιβάλλον).
Αν υπάρχει κάποιο συγκεκριμένο error που δόθηκε από το API της Viva και καταγράφεται, μπορούμε να βοηθήσουμε περαιτέρω.
Διαφορετικά, θα πρότεινα να επικοινωνήσετε με το δημιουργό του plugin.

**Comment by ckarikas** [comment]
Καλημέρα και ευχαριστώ για την απάντηση.

Το γνωρίζω πως το εν λόγω plugin δεν έχει αναπτυχθεί από εσάς, απλά το θέμα μου είναι, ότι τρία στοιχεία παίρνω copy paste από το site της Viva, το merchant id, το API και το CodeId και μου βγάζει error στο API.

Τηλεφώνησα στα κεντρικά και μου είπαν πως τα URL που έχω δηλώσει στη Επιτυχημένη και την Αποτυχημένη συναλλαγή είναι τα ίδια και πρέπει να είναι διαφορετικά. Τα άλλαξα, αλλά κάθε φορά που τα αλλάζω πρέπει να περιμένω 2-3 εργάσιμες για επιβεβαίωση.

Απλά θα ήθελα να γνωρίζω αν το πρόβλημα μπορεί να είναι από αυτό που μου είπα στα κεντρικά και που αναφέρω παραπάνω, ή να είναι κάτι άλλο πιο συγκεκριμένο, ώστε να εστιάσω σε αυτό.

Ευχαριστω και πάλι εκ των προτέρων.

**Comment by dmihos** [comment]
Απ'ότι καταλαβαίνω, δεν εμφανίζεται καθόλου η checkout σελίδα της Viva, οπότε το πρόβλημα είναι στα στοιχεία σύνδεσης με το API κατά τη δημιουργία του Order.
Μοιάζει με authentication πρόβλημα.
Αν μιλάμε για demo περιβάλλον, ποιο είναι το merchantID σας; (Αν πρόκειται για παραγωγή, αποστείλετε τα στοιχεία στο support@vivawallet.com)

**Comment by ckarikas** [comment]
Ναι κι εγώ κάτι τέτοιο φανταζόμουν, ότι  το πρόβλημα θα είναι το authentication, αλλά μέσα στο λογαριασμό μου όλα τα στοιχεία μου έχουν ταυτοποιηθεί, οπότε δε νομίζω να έχει να κάνει με αυτό. Εκτός αν είναι fake αυτό που βλέπω. Όχι δεν αναφέρομαι σε demo, αναφέρομαι σε production περιβάλλον.

**Comment by ckarikas** [comment]
Να σας ενημερώσω ότι στο περιβάλλον του demo, κατά το checkout, μου κάνει το redirect αλλά εμφανίζει ένα bad request, όπως θα δείτε στην επισυναπτόμενη εικόνα.
![viva-connection](https://cloud.githubusercontent.com/assets/17335265/13701409/63398830-e790-11e5-818c-e356a87ea121.jpg)

**Comment by dmihos** [comment]
Το πρόβλημα, όπως φαίνεται και στο url της σελίδας checkout, είναι ότι δεν αποθηκεύετε σωστά στο σύστημά σας το 16ψήφιο OrderCode.
Θα πρέπει να το δείτε με τον δημιουργό του plugin.

**Comment by ckarikas** [comment]
Καλημέρα και πάλι! Όλα όσα φαίνονται παραπάνω είναι σε demo περιβάλλον, τόσο δικό μας όσο και της viva. Σε prod περιβάλλον τα πράγματα αλλάζουν. Όλα μας τα στοιχεία είναι ταυτοποιημένα από τη viva και τα Merchant ID, API key και Code ID, βρίσκονται μέσα στον ιστότοπο της viva και τα πέρνουμε copy paste. Το αποτέλεσμα είναι το παρακάτω.

![viva-payment-order](https://cloud.githubusercontent.com/assets/17335265/13771000/6fcc912c-ea93-11e5-986a-a2536cf0ea80.JPG)

**Comment by vmanthos** [comment]
Εάν δείτε τον κώδικα του plugin (ln 249), το συγκεκριμένο μήνυμα σφάλματος είναι πολύ γενικό κι επιστρέφει όταν το response από την κλήση στο API της Viva, δεν είναι object. Αυτό μπορεί να συμβαίνει για πολλούς λόγους κι όχι μόνο λόγω λανθασμένων στοιχείων authentication.

Από το σφάλμα στο demo περιβάλλον, φαίνεται ότι το payment order που στέλνεται στο API δεν είναι integer. Το plugin το χειρίζεται ως integer. Έχετε αλλάξει κάτι στον κώδικα του plugin;

**Comment by ckarikas** [comment]
1. Δεν έχουμε πειράξει καθόλου τον κώδικα του plugin μέχρι τώρα,
2. Στο status του εργαλείου που χρησιμοποιώ, εμφανίζεται το ακόλουθο μήνυμα:
**✕ Your server does not have the SOAP Client class enabled - some gateway plugins which use SOAP may not work as expected.** 
Υπάρχει περίπτωση να παίζει αυτό κάποιο ρόλο στο πρόβλημα το οποίο έχει δημιουργηθεί ή γενικότερα υπάρχει κάποιο setting το οποίο πρέπει να ορίσουμε στον server;

**Comment by vmanthos** [comment]
Πιθανότατα είναι κάτι στο configuration σας. Είτε στον server (το μήνυμα που παίρνετε) είτε στο wordpress.

Σχετικά με τον server, το plugin χρησιμοποιεί σίγουρα cURL, οπότε ελέγξτε εάν είναι διαθέσιμο. Όσο για το SOAP client class, μπορείτε να τον ενεργοποιήσετε ή να ζητήσετε να σας το ενεργοποιήσουν (system administrator), εάν δεν έχετε πρόσβαση, μήπως κι έτσι λυθεί το θέμα.

Το δεύτερο μπορείτε να το ελέγξετε απενεργοποιώντας τα plugins και αφήνοντας μόνο το woocommerece και το viva gateway plugin. Εάν δουλέψει, κάποιο από τα άλλα plugins που έχετε, κάνει τη ζημιά. Το επόμενο βήμα είναι να ελέγξετε το theme σας. Ενεργοποιήστε κάποιο άλλο, συμβατό με woocommerce και ξαναδοκιμάστε.

**Comment by ckarikas** [comment]
Καλημέρα! Διαβάσαμε χθες στο Viva Payments Instructions ότι στο demo server της viva θα υπάρχει πρόβλημα στο redirect (bad request) αν το site βρίσκεται σε DNS server ή σε host file. Ισχύει το ίδιο και για τον prod server της viva; Υπάρχει κάποια άλλη εναλλακτική;

Ευχαριστώ εκ των προτέρων!

**Comment by defilerc** [comment]
Προχωράω σε κλείσιμο του συγκεκριμένου issue, καθώς η συζήτηση έχει μεταφερθεί από Viva Payments API related σε συζήτηση γύρω από το configuration συγκεκριμένου plugin.

**Comment by mixos** [comment]
Έχω αλλαξει url στο eshop μου (έκανα νέο eshop) όταν γινεται η πληρωμη στο site της viva στο redirect back στο eshop μου με στελνει στο παλιο url και παιρνω 404. Πως δηλώνω την αλλαγή url στη viva?

**Comment by dmihos** [comment]
Menu>Οι Πωλήσεις μου>Πηγές πληρωμών
Και επεξεργάζεστε την πηγή που χρησιμοποιείτε.
