### ISSUE TITLE
αποτυχια συναλλαγης

### ISSUE THREAD

**Issue by oksanamagar** [VivaPayments/API#530]
Καλησπέρα πριν δυο μέρες άλλαξα το domain σε native για να μπορέσουμε να το βάλουμε σε πληρωμές μέσω το web που έχουμε ..επίσης δεν το κάναμε και το γύρισα το domain σε redirect κάτι που δούλευε χρονια με τα button πληρωμών..τώρα με το που το γύρισα με βγάζει σφάλμα συναλλαγής παρακαλώ καμια λύση πάνω σε αυτό?.

Να προσθέσω ότι έχω κάνει με 3 διαφορετικές κάρτες πληρωμή..Και πριν την αλλαγή δούλευε καλά εδώ και δυο χρονια...δεν δουλεύει κανένα button όσα και να ετοιμάσω όλα βγάζουνε σφάλμα

Kαι τα button δεν σβήνουνε μέσα μου βγάζει μήνυμα 
Δεν ήταν δυνατή η διαγραφή του κουμπιού

Σας ευχαριστώ.

https://prnt.sc/jmj11j

**Comment by oksanamagar** [comment]
καλημέρα παιδιά καμια ενημέρωση με το πρόβλημα που υπάρχει?

**Comment by isset1988** [comment]
Δοκίμασε να ενεργοποιησεις το redirection 
στο Πωλήσεις->Πηγές Πληρωμών. 
Και στο Ρυθμίσεις-> Πρόσβαση Api, απενεργοποίησε την επιλογή Ενεργοποίηση υπηρεσίας Native/Pay with Viva Wallet checkout

**Comment by oksanamagar** [comment]
http://prntscr.com/jnndjq
καλησπέρα πάλι το ίδιο σε redirect βγάζει σφάλμα και έχω βγάλει το native ερίσεις δεν κάνει διαγραφή τα κουμπιά ενώ πριν τα έκανε κανονικά μέσα στο panel

**Comment by patisiaeasy** [comment]
Καλησπέρα σας ,

Το τελευταίο διάστημα έγινε αναβάθμιση στο site μας.  Tρόπο πληρωμής και στο παλιό και στο νέο έχουμε viva wallet.
Το πρόβλημα είναι ότι δεν μου φαίνονται οι πληρωμές όπου γίνονται από το site. 
Χάνονται για κάποιο λόγο, ενώ ο πελάτης έχει πληρώσει κανονικά. Σας αναφέρω για την αναβάθμιση του site μήπως οφείλεται σ' αυτό.

**Comment by oksanamagar** [comment]
καλημέρα νομίζω ότι θα έπρεπε να ανοίξεις άλλο ticket με το πρόβλημα που έχεις αλλα πιστεύω και εδώ να μας βολέψουνε τα παιδιά και τους δυο για τα θέματα που έχουμε ..

**Comment by kostGX** [comment]
@oksanamagar καλησπέρα, επιλύθηκε το πρόβλημα με την καθοδήγηση του @isset1988 τον οποίο και ευχαριστούμε πολύ; Αν ναι, παρακαλώ κάντε close issue. Αν όχι, παρακαλώ κάντε το κοπό να μας δώσετε ένα update.

@patisiaeasy παρακαλώ ανοίξτε ένα άλλο issue για το πρόβλημα σας καθώς φαίνεται να είναι διαφορετικό.

Ευχαριστώ πολύ

**Comment by oksanamagar** [comment]
καλησπέρα όχι δεν δούλεψε καθόλου με αυτό συνεχίζει το ίδιο πρόβλημα

**Comment by dpnevmatikos** [comment]
Καλημέρα @oksanamagar ,
Θα μπορούσες να μας στείλεις πληροφορίες για τον λογαριασμό σου στο support@vivawallet.com ώστε να μπορέσουμε να διερευνήσουμε το πρόβλημα με τις συναλλαγές αυτές?

Χρειαζόμαστε το ```MerchantId``` σου (στο διαχειριστικό: profile -> API Access), τον κωδικό
της πηγής που χρησιμοποιείς, και το όνομα του Button.

Ευχαριστώ

**Comment by oksanamagar** [comment]
καλημέρα τα στέλνω τώρα άμεσα

**Comment by oksanamagar** [comment]
παιδιά ευχαριστώ παρα πολύ για το support το θέμα λύθηκε όπως ακριβώς με είπε το παλικάρι  dpnevmatikos  να σε καλά ...

**Comment by dpnevmatikos** [comment]
Thnx @oksanamagar :)

Να αναφέρουμε, για μελλοντική χρήση, οτι το πρόβλημα ήταν οτι η πηγή ```Default``` που χρησιμοποιείται απο το buy button ήταν σεταρισμένη για ```Native/Simple checkout``` integration.
Για αυτό το λόγο αποτύγχαναν οι συναλλαγές.
Σε αυτή την περίπτωση πρέπει η ```Default``` να παραμένει σεταρισμένη για ```Redirect``` integration και να δημιουργείται νέα πηγή για να εξυπηρετηθεί η ```Native/Simple``` checkout.
