### ISSUE TITLE
Maximum characters for fields in new order - Phone Number

### ISSUE THREAD

**Issue by PKDataGreece** [VivaPayments/API#533]
Hello. In reference to my previous issue in #426, I' d like to know if there is any a maximum limit in the field "Phone" when creating a new order. Is there any way to use two phone numbers during this process.

PS. Previous post #426 may have been too general to be answered

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
