### ISSUE TITLE
test with Viva Wallet

### ISSUE THREAD

**Issue by GRANDX1** [VivaPayments/API#534]
Thank you for your reply. However, we can find only test data for testing payments with VIVA CARD but not with VIVA WALLET. We used the test wallet account we registered and managed to enter it during testing but since there is no money on test account we could not finish testing payments with VIVA WALLET.

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
