### ISSUE TITLE
Error: 422, PaymentsNoBinRouteFound

### ISSUE THREAD

**Issue by odysseas12** [VivaPayments/API#535]
Hi I have 2 cases where a client tried to make a payment but it failed with error 422.

This first case the client tried 4 times and the fourth time the transaction was successful.
stdClass Object
(
    [error] => 1
    [data] => stdClass Object
        (
            [Emv] => 
            [Amount] => 
            [StatusId] => E
            [CurrencyCode] => 
            [TransactionId] => 
            [ReferenceNumber] => 
            [AuthorizationId] => 
            [RetrievalReferenceNumber] => 
            [ErrorCode] => 422
            [ErrorText] => PaymentsNoBinRouteFound
            [TimeStamp] => 2018-05-30T22:01:47.0990755+03:00
            [CorrelationId] => 
            [EventId] => 2054
            [Success] => 
        )

)
stdClass Object
(
    [error] => 1
    [data] => stdClass Object
        (
            [Emv] => 
            [Amount] => 
            [StatusId] => E
            [CurrencyCode] => 
            [TransactionId] => 
            [ReferenceNumber] => 
            [AuthorizationId] => 
            [RetrievalReferenceNumber] => 
            [ErrorCode] => 422
            [ErrorText] => PaymentsNoBinRouteFound
            [TimeStamp] => 2018-05-30T22:07:32.0695014+03:00
            [CorrelationId] => 
            [EventId] => 2054
            [Success] => 
        )

)
stdClass Object
(
    [error] => 1
    [data] => stdClass Object
        (
            [Emv] => 
            [Amount] => 
            [StatusId] => E
            [CurrencyCode] => 
            [TransactionId] => 
            [ReferenceNumber] => 
            [AuthorizationId] => 
            [RetrievalReferenceNumber] => 
            [ErrorCode] => 422
            [ErrorText] => PaymentsNoBinRouteFound
            [TimeStamp] => 2018-05-30T22:08:51.5359583+03:00
            [CorrelationId] => 
            [EventId] => 2054
            [Success] => 
        )

)
stdClass Object
(
    [error] => 0
    [data] => stdClass Object
        (
            [Emv] => 
            [Amount] => 160.2
            [StatusId] => F
            [CurrencyCode] => 978
            [TransactionId] => 269b326f-f1e0-4f67-bcb1-ba4b204f754e
            [ReferenceNumber] => 107074
            [AuthorizationId] => 019547
            [RetrievalReferenceNumber] => 815019107074
            [ErrorCode] => 0
            [ErrorText] => 
            [TimeStamp] => 2018-05-30T22:09:54.2840757+03:00
            [CorrelationId] => 
            [EventId] => 0
            [Success] => 1
        )

)

This the client only tried once.

stdClass Object
(
    [error] => 1
    [data] => stdClass Object
        (
            [Emv] => 
            [Amount] => 
            [StatusId] => E
            [CurrencyCode] => 
            [TransactionId] => 
            [ReferenceNumber] => 
            [AuthorizationId] => 
            [RetrievalReferenceNumber] => 
            [ErrorCode] => 422
            [ErrorText] => PaymentsNoBinRouteFound
            [TimeStamp] => 2018-06-01T19:20:36.0404342+03:00
            [CorrelationId] => 
            [EventId] => 2054
            [Success] => 
        )

)

So what went wrong ? What is error 422 and how do you advice to handle it.

Thank you

**Comment by minamoto19** [comment]
Same issue here.
Sometimes there is an error PaymentsNoBinRouteFound 422 exactly as mentioned above.

Additionally is there a list of error codes?

Please advise!

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Apparently this is a configuration issue that one of our developers needs to fix. I'll let you know when it's done. Thanks!

**Comment by matthewrgourd** [comment]
Hi @minamoto19 please could I have the merchant ID so we can look into this further. Thanks!

**Comment by matthewrgourd** [comment]
Hi @odysseas12 , please could I have your demo merchant ID so we can look into this further? Thanks!

**Comment by odysseas12** [comment]
Hi matt this was not on a a demo account this was on a live client.
From what I can see from my logs it still happens every couple of months.
I have this error 55 times in the last year for around 5000 transactions.

**Comment by matthewrgourd** [comment]
Hi @odysseas12 Apologies, my mistake. About the error code, simply put it means transaction failed, but I don't know why this is happening. Can you tell me which of our products you're using to receive payment? Is it [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout), [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout), [Native Checkout 3DS](https://developer.vivawallet.com/online-checkouts/native-checkout-v2) or one of our e-commerce plugins? Alternatively, maybe you're using our [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api-details/).

**Comment by odysseas12** [comment]
Im using the v1 of native checkout, didnt know a v2 was available and v1 was deprecated.
Is v2 out of beta? and recommended now ?

**Comment by matthewrgourd** [comment]
Hi there, yes, v2 is the one to use now. V1 is being phased out, although not immediately.

Thanks,

Matt

Matt Gourd
Technical Writer

Viva Wallet
3 Apple Tree Yard, London, SW1Y 6AE, UK
M: +447498 719486
[cid:image001.png@01D4BFC5.9A26E5D0]

ΕEA-31 region licensed e-money Institution
Disclaimer: This email contains confidential and privileged material for the sole use of the intended recipient. Any review or distribution by others is strictly prohibited. If you are not the intended recipient please contact the sender and delete all copies.

On 22 Jul 2019, at 12:22, odysseas12 <notifications@github.com<mailto:notifications@github.com>> wrote:


Im using the v1 of native checkout, didnt know a v2 was available and v1 was deprecated.
Is v2 out of beta? and recommended now ?

**Comment by matthewrgourd** [comment]
Please see here for more info about Native Checkout v2:

https://developer.vivawallet.com/online-checkouts/native-checkout-v2

Over the next few months we're going to ask all our clients to migrate to it.

Thanks!
