### ISSUE TITLE
Pay button not work. Transaction Failed

### ISSUE THREAD

**Issue by evi-voulgari** [VivaPayments/API#536]
Δημιούργησα το pay button και κάνοντας μια δοκιμαστική συναλλαγή για έλεγχο της λειτουργικότητας αυτή αποτυγχάνει. Νομίζω ότι το πρόβλημα οφείλεται αλλά χωρίς να είμαι σίγουρος στο ότι η default πηγή πληρωμής είναι σε κατάσταση pending (το Integration method είναι σε redirection). Γιατί συμβαίνει αυτό ?
Ευχαριστώ

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
