### ISSUE TITLE
request to 'https://www.vivapayments.com/api/orders' returns NOTHING

### ISSUE THREAD

**Issue by easy2order** [VivaPayments/API#538]
I successfully tested my implementation of api calls with the demo environment, but when I change to the production I got NO RESPONSE  at all !!! The call returns with status code 200 but with no response data ... How I would debug this issue ? Payment Sources seems OK, API credentials double-checked ... Please advise.

Thank you in advance

**Comment by b4g4** [comment]
I have the same issue, during test mode everything worked perfect once it went live it returns 

Wrong Merchant crendentials or API unavailable 

Have checked credentials and everything look fine.

**Comment by Delivertoo** [comment]
we  have the same issue with wordpress plugin,
during test mode everything worked perfect once it went live it returns Wrong Merchant credentials or API unavailable

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. You need to switch over from using your demo merchant ID and API key to using the live versions. If you have any other queries please do please let us know and we'd be happy to help. Thanks!
