### ISSUE TITLE
Ερώτηση για AngularJS

### ISSUE THREAD

**Issue by beisnikosspi** [VivaPayments/API#539]
Καλησπέρα, έχω μια ερώτηση να κάνω. Θέλουμε να ενσωματώσουμε το native checkout στο custom eshop μας αλλά η σελίδα του καλαθιού είναι γραμμένη με Angular JS v1.6.6. Πως θα γίνει η ενσωμάτωση της φόρμας καταχώρησης της κάρτας; Τα attributes data-vp λογικά δεν θα παίξουν. Έχετε κάποια πρόταση;

Ευχαριστώ,

**Comment by dpnevmatikos** [comment]
Καλημέρα @beisnikosspi ,
Η Native Checkout έχει dependency στο jQuery, επομένως ασχέτως με το τι framework χρησιμοποιείς για το eshop σου, αν έχεις ref στο jQuery θα παίξει κανονικά.

**Comment by beisnikosspi** [comment]
Κατανοητό. Τα data-vp attributes θα λειτουργήσουν με AngularJS? Νομίζω πως δεν θα δουλέψουν.

**Comment by dpnevmatikos** [comment]
Αυτά είναι [custom data attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) πάνω σε HTML elements. Δεν έχουν σχέση ουτε με το Angular ούτε με το jQuery.

**Comment by beisnikosspi** [comment]
Μάλιστα. Οπότε δεν υπάρχει κανένα απολύτως πρόβλημα ούτε ασυμβατότητα όταν μπαίνει ενδιάμεσα Angular?
