### ISSUE TITLE
Viva Wallet public key

### ISSUE THREAD

**Issue by Cristinawork** [VivaPayments/API#542]
Where can I find Viva wallet public key for online payments?
What I have from viva account is Merchant ID and API Key.
In the simple checkout form when I use the demo public key it works fine, when I change it with the Merchant ID it displays the error Invalid merchant public key. So public key must be something else.

**Comment by kostGX** [comment]
@Cristinawork correct, you need to navigate to Settings > API, then scroll to the bottom of the page, and enable Native/Simple Checkout Public Key. Once checked, the public key will be generated there.

<img width="1438" alt="enable simple checkout public key" src="https://user-images.githubusercontent.com/3908736/41460518-b9ecf8e8-7095-11e8-9b0a-5e1966b59797.png">

**Comment by Cristinawork** [comment]
For one thing thank you very very much for the quick response.
Of course I will try it and let you know.
best regards,
Cristina

**Comment by Cristinawork** [comment]
It works with the public key. Is there a variable to send to Viva wallet for number of installments maybe?

**Comment by Cristinawork** [comment]
Also how to change button text from simple Pay to Pay with VivaWallet for example, so that the customer knows?

**Comment by kostGX** [comment]
@Cristinawork hello, instalments are not available at Simple Checkout, but it is available in Redirect Checkout.

You can change the text with the following attributes: 
```
data-vp-text
Sets button’s text
Default value: Pay (when data-vp-lang="en"), Πληρωμή (when data-vp-lang=”el”)
```

**Comment by Cristinawork** [comment]
Thank you!

**Comment by chgl48** [comment]
Where the above attributes are being completed?
