### ISSUE TITLE
Not redirect back to my page on success or failure

### ISSUE THREAD

**Issue by isset1988** [VivaPayments/API#544]
Hello,

I have a php website and i setup viva payments. Everything works perfect. Customers pays and i get the money, but the success or failure redirection is not sending the customer back to my page. Its only shows a viva page "Η συναλλαγή πραγματοποιήθηκε επιτυχώς. Πατήστε εδώ για να εκτυπώσετε το αποδεικτικό συναλλαγής."

The url of success transaction is this https://www.mypage.com/ws/success.php and 
The url of failure transaction is this https://www.mypage.com/ws/deny.php

Any help?
![screenshot](https://user-images.githubusercontent.com/28668203/41500176-db51b914-7195-11e8-8109-71bbeef69efd.png)

**Comment by isset1988** [comment]
i found the solution. I create two different websites on payments section and my default is empty.
For the record, if i want to use anybod tge other websites, how can i add the code of website into php?

**Comment by makistank** [comment]
I face also the same problem , in my app settings we have the default (VivaPayment) and my live site, everything works just fine but when i pay in viva page it does not redirect to success (or fail if payment failed) but it stays in Viva's page as you see below . 

Notes:
1. Is the port that i put before webpage a problem ?
2. My MID is -> 2e15b061-f521-4cca-a656-275efe858a3f

 https://www.vivapayments.com/web/checkout/result?t=xxxxxx-xxxxxx-xxxxx-xxxxx-xxxxxx&s=xxxxxxxxxxxxxxxxxxxxxxxxx&lang=en-US

![viva](https://user-images.githubusercontent.com/5020063/50356885-83549780-055c-11e9-854f-6f6db9c062bc.png)
