### ISSUE TITLE
worldbytez.com API access issue

### ISSUE THREAD

**Issue by oksanamagar** [VivaPayments/API#545]
I am the member of viva, we are using API access for accepting payments.
We are facing a problem after moving to a new server. all payments could not get passed. 
Could you please check it for us?

Our Merchant ID: 8eb9f9d6-2d78-4351-b821-0c50e712f979
Payment Source: 8541

Our new server IP: 91.121.108.129

any help would be appreciated.

**Comment by oksanamagar** [comment]
Hello any news for my problem ?

**Comment by dpnevmatikos** [comment]
Hi @oksanamagar ,
Could you please provide us with more info regarding the problem you are facing?
What's your integration method with Viva Payments? Are you receiving an error code?
Have you set up the correct redirect URLs to your payments source?

Our system shows that the last successful payment you received was yesterday (20 June 2018).
When did this issue first appeared?

**Comment by oksanamagar** [comment]
hello i put my card live or demo same provlem no take money from the card and give this message check screen 
http://prntscr.com/jxpo9s
and not give trasaction id  i am use php native

before change server it works fine

**Comment by kostGX** [comment]
Καλησπέρα @oksanamagar,

Στο configuration της πηγής είναι σωστά ορισμένες οι ρυθμίσεις (Native Checkout = Enabled and source Active)

Το πρόβλημα ποιό είναι; 

Μήπως υπάρχει κάποιο θέμα με το URL redirection σε κάποιο σημείο του integration; Οι πηγές μας ορίζονται με URL και όχι με IP.

**Comment by oksanamagar** [comment]
καλησπέρα για κάποιο λόγο δεν δέχεται πληρωμές είναι σαν να μην υπάρχει γιατί και στο demo τα ίδια κάνει όλα είναι σωστά όπως τα είχα και πριν ..για αυτό και σας έστειλα μήπως το πρόβλημα προέρχεται από την viva και όχι από το server ..πριν την αλλαγή του server όλα δούλευαν σωστά έδινε και id μετά την πληρωμή τώρα είναι σαν demo μονο που δεν δουλεύει ούτε στο demo ούτε στο live..

**Comment by oksanamagar** [comment]
https://worldbytez.com/viva/web/index.php

μπορείτε να το δείτε και από εδώ  σε demo απλά να δείτε αν είναι προσβάσιμο από εμενα προς εσάς

**Comment by kostGX** [comment]
@oksanamagar καλημέρα σας, μπορείτε παρακαλώ να ξαναδοκιμάσετε;

**Comment by oksanamagar** [comment]
καλημέρα το ίδιο μήνυμα κανονικά έπρεπε στο demo να δείξει πληρωμή

**Comment by kostGX** [comment]
Η φόρμα ποστάρετε κανονικά. Πρέπει να ολοκληρώσετε την πληρωμή στο backend σας.
Παρακαλώ κάντε το κόπο να ακολουθήσετε το flow που περιγράφεται εδώ: https://github.com/VivaPayments/API/wiki/Native-Checkout 

και σιγουρευτείτε πως όλα τα βήματα είναι σωστά.

**Comment by oksanamagar** [comment]
καλώς θα τα κοιτάξω ακόμα μια φορα καλά και θα σας ενημερώσω σας ευχαριστώ για τον χρόνο σας

**Comment by oksanamagar** [comment]
καλησπέρα μετά από αρκετό ψάξιμο έβαλα το demo στο παλιό το μηχάνημα και είδα ότι εκεί δουλεύει ..το πρόβλημα έρχεται από το ( PLESK ΓΙΑ ΠΕΤΑΜΑ ) ..με cpanel δουλεύει κανονικά ευχαριστώ παιδιά για το support..
