### ISSUE TITLE
Trying to Enable Native/Pay with Viva Wallet checkout error 500

### ISSUE THREAD

**Issue by dimkasta** [VivaPayments/API#546]
I am trying to Enable Native/Pay with Viva Wallet checkout on the demo site to get the demo public key, but I am getting error 500 on the popup.
The XHR response looks completely empty on dev tools

**Comment by isset1988** [comment]
Θα πρέπει να ενεργοποιήσεις την επιλογή native στο ρυθμίσεις->πρόσβαση api.
Επίσης να έχεις επιλέξει native και από το οι πωλήσεις μου->πηγές πληρωμών.

**Comment by dimkasta** [comment]
Καλημέρα και ευχαριστώ για την απάντηση.
Το error 500 το παίρνω όταν πάω να ενεργοποιήσω το Native στην πρόσβαση ΑΡΙ
