### ISSUE TITLE
Trying to verify a redirect payment is always get sent to failure

### ISSUE THREAD

**Issue by dimkasta** [VivaPayments/API#547]
I am doing some tests from localhost to the demo portal, trying to do a redirect payment.
( I am manually switching the url from the dummy domain I have configured to localhost:8000 where my local server runs)

The payment is always sent to failure url

However, if I try to verify the transaction/order, I see that it was a success with error code 0, but no transactions are included in the response.

Can you please check?
Order code: 2209859916472602

**Comment by isset1988** [comment]
Απο όσο ξέρω οι πληρωμές refirect δε δουλέουν σε localhost. Μέσα στο διαχειριστικό πανελ της viva payments προσθέτεις τα domain σου. Μόνο αυτά τα domain έχουν πρόσβαση στο api.

**Comment by dimkasta** [comment]
Μέχρι τώρα δούλευε, γι αυτό άνοιξα και το case. Έχει αλλάξει αυτό? 'η είναι απλά bug στο demo site?

**Comment by isset1988** [comment]
Ισως είναι αναβάθμιση ασφαλείας και όχι bug. Το domain είναι αυτό που καθορίζει τη σύνδεση με το api. Μπορείς να περιμένεις και την επίσημη απάντηση από τη viva σε περίπτωση που δει κάποιος αυτό το ticket. Κατ εμέ δούλεψε σε live server.

**Comment by dimkasta** [comment]
Πάντως το ίδιο κάνει και με τοπικό domain .test
Και πάλι ευχαριστώ
