### ISSUE TITLE
Parameter name of the phone number

### ISSUE THREAD

**Issue by GRANDX1** [VivaPayments/API#549]
We are trying to get PHONE parameter for the payment via API but get NULL. Can you please, advise the name of this parameter?

Thank you

**Comment by GRANDX1** [comment]
Please, help!!! We urgently need this info!

**Comment by kostGX** [comment]
Please provide more information. What integration method are you using?

How are you performing payments? Have you checked that your customers input their phone numbers during the checkout process you provide?

Thanks!

**Comment by GRANDX1** [comment]
Hi Kostas,
Thank you for your reply.
We have integrated Simple Checkout. The thing is that we need not only accept payments from customers but also to be able to send payments to customers. I have found in your documentation that OCT API enables sending money customers using the same credit cards which they used for sending the payments to us. However, your customer service department replied to us that this API will be open to us in at least 2 weeks after we go live. (By the way, please, confirm with OCP API we will be able to snd money to our clients both for credit cards and viva wallet payments). 

We checked and found out that it is possible to send payments from VIVA BO to VIVA wallets but for this phone number is necessary. That’s why we added PHONE parameter at the time when the client makes a payment to us using VIVA WALLET, however, we are not getting the phone number with the payment details once the payment has been finished.

Thanks you in advance

Svetlana

**Comment by GRANDX1** [comment]
Hi!
Any news for us?

Svetlana
GRANDX

**Comment by GRANDX1** [comment]
Hi!
Sorry for the reminder again but we need to fix the PHONE PARAMETER issue and go live with VIVA as our clients badly need this payment method.

Thank you in advance.

Svetlana
GRANDX

**Comment by GRANDX1** [comment]
Hi!
Sorry for the reminder but the issue is still very urgent or us

**Comment by GRANDX1** [comment]
@dpnevmatikos @kostGX

**Comment by menelaostrik** [comment]
i'm using NativeCheckout and i pass the phone information as: `$obj->Phone = "number";` inside the php script
hope it helps

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
