### ISSUE TITLE
CURLOPT_SSL_CIPHER_LIST on PHP must be commented for production calls

### ISSUE THREAD

**Issue by candreikos** [VivaPayments/API#55]
On the PHP sample of create_order.php, the curl command CURLOPT_SSL_CIPHER_LIST must be commented out in order for the API call to work. Any other value to the command such as RC4-SHA, will not work at all.
I have submitted the commented code line to my respective fork. (candreikos/API)

**Comment by defilerc** [comment]
Hi @candreikos ,

Thank you very much for your useful comments and contribution.

Best regards
