### ISSUE TITLE
Recent Issues

### ISSUE THREAD

**Issue by polyskasinides** [VivaPayments/API#550]
Please note that recently we are getting a lot of unsuccessful payment attempts with the below details. Can you please check these out and explain the issue?

Examples: 

- OrderStateCode: 0, OrderState: Pending, VivaOrderID: 6083146714972606,, CrmOrderId: 1ce51194-731e-11e8-a022-06d9ab67fa49

- ReasonCode: E, ReasonCodeDesc: The transaction was not completed because of an error, VivaTransactionID: c9107557-9281-4f67-8933-986f7603c45e, VivaOrderID: 7498222887672609,, CrmOrderId: 740fcb7c-731d-11e8-b795-06d9ab67fa49, PaddedCardNo: 7845

- OrderStateCode: 1, OrderState: Expired, VivaOrderID: 7486408437172605,, CrmOrderId: 5b715fe4-731e-11e8-9fe6-06d9ab67fa49

**Comment by kostGX** [comment]
Hello @polyskasinides, I ran your order code ids on our logs and found the following error message: "The Timeout to process the order has expired"

How exactly are you creating this Orders? If you're doing this via our API you need to make sure that you follow the instructions on https://github.com/VivaPayments/API/wiki/Optional-Parameters and specifically set according to your needs:

`PaymentTimeOut ( int32 ): By default, the life span of every Payment Order is 300 seconds (5 minutes). This is the time given to the cardholder to complete an online payment. If the cardholder does not complete the payment within the given time frame, the Payment Order is automatically cancelled. By using this parameter, you can define a different life span for your Payment Order.
Note 1: Value is in seconds and can be either smaller or greater than 300 secs.
Note 2: Use value 65535 if you want your Payment Order to never expire.`

Let me know if that helped - thanks!

**Comment by polyskasinides** [comment]
Thanks @kostGX. I've changed the PaymentTimeOut to 65535. We'll see how it goes and get back this thread if we have any issues.
