### ISSUE TITLE
Bad request, no ref, on woocommerce with official plugin

### ISSUE THREAD

**Issue by firstroad** [VivaPayments/API#551]
Hello,
I used this plugin only ([https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce](https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce)). After checkout there is a redirect to a page that shows "Bad Request" and the url is: "http://demo.vivapayments.com/web/newtransaction.aspx?Ref=". Probably for some reason the ref is mistakenly empty. The same goes for test mode and normal. Have I missed some settings? I just followed the guide in the link above.

**Comment by VivaWalletSupport** [comment]
Hello, please check if you are using the correct merchant id and api key from your demo account and you are not using the credentials from your live account in demo mode.

**Comment by firstroad** [comment]
Merchant id was incorrect, I am sorry. Thanks
