### ISSUE TITLE
simple checkout issue

### ISSUE THREAD

**Issue by datapack** [VivaPayments/API#555]
Καλημέρα σας ,
Εχω ενα προβλημα με το simple checkout .
https://github.com/VivaPayments/API/wiki/Simple-Checkout

Το link μας ειναι http://pay.cityu.gr/pay.html

Αφού βάλουμε κάρτα κλπ δεν λαμβανουμε τα χρήματα ...αλλα ουτε υπάρχει χρεωση στο πελάτη 

Μπορούμε να το δούμε ? ( η χρεωση 0,01 euro δεν εγινε ποτε στη καρτα που εβαλα )

**Comment by kostGX** [comment]
Η ελάχιστη χρέωση που μπορείτε να βάλετε είναι 0,30€. Παρακαλώ δοκιμάστε ξανά με μεγαλύτερο ποσό χρέωσης (μπορείτε μετά να ακυρώσετε την συναλλαγή από το διαχειριστικό σύστημα, επιστρέφοντας έτσι τα χρήματα στην κάρτα που χρεώσατε.)

Ευχαριστω

**Comment by datapack** [comment]
Καλησπέρα σας ,
Δοκίμασα με 1 euro και δεν άλλαξε κατι ... 

Ευχαριστω πολυ

**Comment by dimkasta** [comment]
Η απάντηση από το api της viva τι κωδικό επιστρέφει?

**Comment by kostGX** [comment]
@datapack τι error "χτυπάει" στο backend σας όταν κάνετε POST το token που παίρνετε από την Simple Checkout?
