### ISSUE TITLE
Πρόβλημα με nativecheckout

### ISSUE THREAD

**Issue by menelaostrik** [VivaPayments/API#556]
Καλησπέρα σας,
 προσπαθώ να κάνω integrate το NativeCheckout σαν gateway processor σ'ένα wp plugin για hotel reservations.
ενώ το Plugin μου δουλεύει κανονικά, οι πληρωμές δεν περνάνε.
Ακόμη και απευθείας σε 2 αρχεία όπως στο παράδειγμα(viva.php & NativeCheckout.php)
δείχνει στην αρχή ότι περνάει όμως η μεταβλητή $transactionId γυρνάει πίσω NULL. 

το ίδιο πρόβλημα έχω και στο demo και στο live περιβάλλον και έχω κάνει όλα τα απαραίτητα βήματα στο vivawallet.com(εγκεκριμένη πηγή, ενεργοποιημένη Native/Pay with Viva Wallet checkout).

μήπως μου διαφεύγει κάτι; 
αυτό λειτουργεί Out-of-the-box(δλδ με τις απαραίτητες αλλαγές σε publickey,mechant, κτλ);

ευχαριστώ εκ των προτέρων για οποιαδήποτε βοήθεια,
Μενέλαος

**Comment by menelaostrik** [comment]
Βρήκα τη λύση [εδώ ](https://github.com/VivaPayments/API/issues/144) ευχαριστώ πολύ

**Comment by menelaostrik** [comment]
γνωρίζεται πως μπορώ να βάλω σε αυτά τα πεδία: [screenshot](http://prntscr.com/k2khtw) εγγραφές;
Περιγραφή, πελάτης, παρατηρήσεις.
Δε θα έπρεπε στο Πελάτης να παίρνει αυτόματα από το: <input type="text" size="20" name=”txtCardHolder” autocomplete="off" data-vp="cardholder"/> της φόρμας; 
κάνω κάπου λάθος;
ευχαριστώ εκ των προτέρων,
Μενέλαος

**Comment by Sotiris-k** [comment]
Ενημερωτικά, η λύση που σύνδεσες δεν είναι η καλύτερη. Το να απενεργοποιήσεις το SSL Verification στα curl requests είναι λύση τύπου "πονάει κεφάλι, κόβει κεφάλι".

**Comment by menelaostrik** [comment]
Καλημέρα Σωτήρη και ευχαριστώ για την απάντηση σου.
δε μπορώ όμως να καταλάβω τι ακριβώς συμβαίνει γιατί το request στέλνεται κανονικά από SSL.
έχεις καμιά ιδέα;

**Comment by Sotiris-k** [comment]
Πήγαινε στο https://curl.haxx.se/ca/cacert.pem και κατέβασε αυτό το αρχείο.

Μετά πήγαινε στα PHP Settings του server και βάλε την παρακάτω παράμετρο (αντικατέστησε το path με το path που θα έχει αποθηκεύσει το PEM αρχείο στον server)
`
curl.cainfo=/path/to/cacert.pem`

Μετά θα δουλεύει το παράδειγμα όπως είναι στο repository εδώ.

**Comment by Sotiris-k** [comment]
Μου κάνει εντύπωση γιατι το Root Certificate που χρησιμοποιει η Viva συμπεριλαμβάνεται μέσα στο bundle που σου ανέφερα. Υποθέτω πως για κάποιο λόγο η ρύθμιση αγνοείται από το php-fpm και σε αυτή τη περίπτωση πρέπει να μπει σαν curl option πριν το call με τον παρακάτω τρόπο.

`curl_setopt($ch, CURLOPT_CAINFO, __DIR__ . '/cacert.pem');`

Όπως πάντα στήσε τα paths ως αρμόζουν. Για δοκιμή μπορείς να βάλεις το PEM file στον ίδιο φάκελο με το PHP αρχείο για να το διαβάσει όπως ακριβώς στο έδωσα.

**Comment by menelaostrik** [comment]
Καταλαβαίνω πως είναι άκρως απαραίτητο να χρησιμοποιηθεί,
έχω κάψει το κεφάλι και δε μπορώ να το κάνω να λειτουργήσει. Μπορείς σε παρακαλώ να με βοηθήσεις;
στο phpinfo() μου δίνει TLS-SRP | No 
μπορώ και συνδέομαι με curl --tlsv1 -v https://demo.vivapayments.com κανονικά.
Bγάζει warning sto error_report της Php
Warning: curl_setopt() expects parameter 1 to be resource, null given in /home/test/public_html/new/NativeCheckoutClass.php on line 65
δοκίμασα και έτσι όπως μου το έδωσες(με το pem στο ίδιο κατάλογο) και με absolute path το ίδιο κάνει.
αφού έβαλα και το $ch = curl_init(); από πάνω, το warning εξαφανίστηκε, όμως το πρόβλημα παραμένει. 
υπάρχει κάτι που μου διαφεύγει;

**Comment by menelaostrik** [comment]
η αλήθεια είναι πως υπάρχουν αρκετά notices http://prntscr.com/k395jf
τα οποία όμως εξαφανίζονται όταν απενεργοποιώ το verifyhost και verifypeer

**Comment by menelaostrik** [comment]
Κατάφερα και βρήκα τη λύση χρησιμοποίησα rsa_aes_256_sha αντί για TLSv1 με:
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'rsa_aes_256_sha');

φαίνεται να λειτουργεί κανονικά, υπάρχει λες κάποιο πρόβλημα με αυτό;

**Comment by Sotiris-k** [comment]
Τα errors εξαφανίζονται οταν το απενεργοποιείς γιατι όλα αυτά είναι γραμμένα με τη λογική ότι δεν θα έχεις null response. Οπότε όταν τα απενεργοποιείς παίρνεις κανονικό response.

Για τον τρόπο που το έλυσες το θέμα δεν έχω κάτι να πω. Από τη στιγμή που το Vivapayments.com έχει αυτό το cipher στη λίστα με αυτά που υποστηρίζει τότε είσαι κομπλέ.

**Comment by menelaostrik** [comment]
Σωτήρη, ξέρεις πως μπορώ να μαζί με τη χρέωση της κάρτας να γίνονται εγγραφές στα πεδία: πελάτης,περιγραφή και παρατηρήσεις στο backend της viva κάτω από το "οι πωλήσεις μου";

και πάλι σ'ευχαριστώ εκ των προτέρων για το χρόνο σου, 
Μενέλαος

**Comment by Sotiris-k** [comment]
Δυστυχώς δεν ξέρω να σε βοηθήσω για αυτό. Αν δεν υπάρχει αυτή η λεπτομέρεια στο Wiki τότε θα δοκίμαζα απλά με πειραματισμό αφού γεμίσω όλα τα πεδία που αφορούν τον customer.

**Comment by menelaostrik** [comment]
καλό κάψιμο πάλι δλδ. χεχε.
Σωτήρη μου να'σαι καλά για το χρόνο σου και τη βοήθεια σου.
ευχαριστώ και πάλι
