### ISSUE TITLE
Δεδομένα σε περιγραφή & παρατηρήσεις 

### ISSUE THREAD

**Issue by menelaostrik** [VivaPayments/API#558]
καλησπέρα και πάλι,
βάση του https://github.com/VivaPayments/API/wiki/Optional-Parameters μπορούν να περάσουν αρκετά δεδομένα, όχι όμως τα: περιγραφή και οι παρατηρήσεις.
γνωρίζει κανείς πως μπορούν να περάσουν και αυτά;
δοκίμασα τυχαία μερικά όπως description, desc, remarks και άλλα, όμως χωρίς τύχη.
Οποιαδήποτε βοήθεια εκτιμάται ιδιαίτερα.
ευχαριστώ εκ των προτέρων,
Μενέλαος

**Comment by Sotiris-k** [comment]
Έχεις δει τα **MerchantTrns** και **CustomerTrns** ; 

Είναι τα πιο κοντινά σε αυτό που θες.

**Comment by menelaostrik** [comment]
ναι, τα έχω δει. οι πληροφορίες που εγγράφονται αντιπροσωπεύουν πεδία μέσα στο κουμπί πληροφορίες. Αυτά που με ενδιαφέρουν είναι αυτά: http://prntscr.com/k48rkb 
φαντάζομαι πως εφόσον υπάρχουν τα πεδία διαθέσιμα στο backend με κάποιο τρόπο θα εγγράφονται.

**Comment by Sotiris-k** [comment]
Απ' όσο έχω ασχοληθεί με το API, αυτά τα πεδία δεν έχω καταφέρει να τα συμπληρώσω. Πολύ πιθανόν να μην συμπληρώνονται λοιπόν.

**Comment by dimkasta** [comment]
Δεν ξέρω αν βοηθάει, στο simple checkout, το πεδίο περιγραφή γεμίζει με το data-vp-description του κουμπιού.
Δοκίμασε να περάσεις κάτι σαν 
Description

**Comment by menelaostrik** [comment]
δοκίμασα ότι κοντινό μπόρεσα να σκεφτώ:
Desciprtion
description
remarks
desc
vp_description
data_vp_description κ.α χωρίς επιτυχία :(

το έχει καταφέρει αυτό κάποιος παιδιά;

**Comment by menelaostrik** [comment]
επιπλέον μετά από κάθε συναλλαγή έρχεται email στον πελάτη το οποίο γράφει:

Στοιχεία συναλλαγής
--
Επιχείρηση |  
Περιγραφή συναλλαγής |  

όπως βλέπετε είναι κενά.
άρα σίγουρα υπάρχει τρόπος να γίνουν οι εγγραφές.

μπορεί παρακαλώ κάποιος να βοηθήσει;

**Comment by kostGX** [comment]
@menelaostrik καλησπέρα, το πεδίο **Παρατηρήσεις** δεν μπορείτε να το παραμετροποιήσετε καθώς παράγεται από το σύστημα σε περίπτωση κάποιου σφάλματος π.χ. όπως φαίνεται εδώ:
![screen shot 2018-07-12 at 11 45 09](https://user-images.githubusercontent.com/3908736/42622491-2ac85394-85c9-11e8-9229-8f5f26f3c7c4.png)

Σχετικά με το πεδίο περιγραφή θα πρέπει να κάνετε post το optional parameter 
```
CustomerTrns ( string ): This optional parameter adds a friendly description to the payment order that you want to display to the cardholder on the payment form. It can either be your customer order code or a short description of items/services purchased.
Note: The maximum length of this parameter is limited to 255 characters
```

Μπορείτε να δείτε εδώ όλα τα optional parameters που μπορείτε να "περάσετε" σε μία συναλλαγή: https://github.com/VivaPayments/API/wiki/Optional-Parameters

**Comment by menelaostrik** [comment]
@kostGX καλησπέρα Κώστα,
με ενδιαφέρει περισσότερο το πεδίο περιγραφή/description για το οποίο δεν αναφέρεται πουθενά το Optional-parameters του wiki.

**Comment by kostGX** [comment]
@menelaostrik 2 περιγραφές υπάρχουν (μία που φαίνεται στον έμπορο μόνο και μία που φαίνεται και στον πελάτη) και αναγράφονται στο οptional parameters.

![screen shot 2018-07-12 at 11 51 24](https://user-images.githubusercontent.com/3908736/42622862-0ad2cdd4-85ca-11e8-9d94-23cf174eb676.png)

Δοκιμάστε να περάσετε αυτές τις 2 παραμέτρους για να δείτε πως φέρονται.

**Comment by menelaostrik** [comment]
@kostGX το έχω ήδη δοκιμάσει. για να φανούν αυτά στο backend πρέπει ο χρήστης να κάνει click στο κουμπί information, εκεί έχει πεδία γι αυτά τα strings.
εγώ θα ήθελα το πεδίο Περιγραφή/description όπως φαίνεται εδώ https://user-images.githubusercontent.com/3908736/42622491-2ac85394-85c9-11e8-9229-8f5f26f3c7c4.png
και έχει test short desc

**Comment by kostGX** [comment]
@menelaostrik κατάλαβα. Και πάλι, το CustomerTrns είναι αυτό το πεδίο που αναφέρετε.

Εγώ στέλνω αυτό:
`var settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://demo.vivapayments.com/api/Orders",
  "method": "POST",
  "headers": {
    "authorization": "Basic OGEzZTQ5OWYtYmYyZi00NGNiLWI4ZmQtNGIwN2Q0YjJhODE3OnZ1QD5pbg==",
    "content-type": "application/x-www-form-urlencoded",
    "cache-control": "no-cache",
    "postman-token": "314da156-5470-59e0-9b90-5facf340b8a8"
  },
  "data": {
    "Amount": "202",
    "ServiceId": "4",
    "FullName": "Kostas Xiradakis",
    "Email": "kost.xiradakis@gmail.com",
    "Phone": "00306945994211",
    "MerchantTrns": "Kostas Merchant Test",
    "CustomerTrns": "Kostas Customer Test",
    "PaymentTimeOut": "65535",
    "DisableIVR": "true",
    "DisableCash": "true",
    "DisablePayAtHome": "true",
    "DisableWallet": "true"
  }
}

$.ajax(settings).done(function (response) {
  console.log(response);
});`

Και στο διαχειριστικό βλέπω αυτό:
![screen shot 2018-07-12 at 12 07 42](https://user-images.githubusercontent.com/3908736/42623828-87e1ceb8-85cc-11e8-91c8-eddf66497773.png)

Ευχαριστώ

**Comment by menelaostrik** [comment]
@kostGX Κώστα μου ευχαριστώ για το χρόνο σου, είχες απόλυτο δίκιο, εγώ είχα λάθος έναν χαρακτήρα στη μεταβλητή και δε το έπαιρνε.
και πάλι ευχαριστώ.
