### ISSUE TITLE
To demo περιβάλλον επιστρέφει πάντα επιτυχία

### ISSUE THREAD

**Issue by dimkasta** [VivaPayments/API#559]
Σύμφωνα με τις οδηγίες, ο αριθμός κάρτας 
4111111111111111
επιστρέφει επιτυχία, και όλοι οι άλλοι αριθμοί θα πρέπει να επιστρέψουν σφάλμα

Οι δοκιμές μου είναι με simple checkout

Παρ' όλα αυτά το ΑΡΙ https://demo.vivapayments.com/api/transactions
επιστρέφει πάντα επιτυχία με success και κωδικό F

Έχω κάνει δοκιμές με τις δοκιμαστικές κάρτες
4111111111111111
4012888888881881
5555555555554444

Υπάρχει κάποιος συνδυασμός που επιστρέφει σφάλμα για να μπορέσω να το χρησιμοποιήσω στα test μου?
Ευχαριστώ

**Comment by Sotiris-k** [comment]
Εγώ χρησιμοποιώ τον [Credit Card Generator του PayPal](https://developer.paypal.com/developer/creditCardGenerator/) και παίρνω εγγυημένα fail.

**Comment by dimkasta** [comment]
Ωραίο εργαλειάκι.
Εγώ χρησιμοποιώ αυτό 
https://www.paypalobjects.com/en_GB/vhelp/paypalmanager_help/credit_card_numbers.htm

Δοκίμασα και από τον generator, και πήρα πάλι success

**Comment by Sotiris-k** [comment]
Να σε ρωτήσω, όταν λες επιτυχία τι εννοείς; HTTP Response 200; 

Δεν μπορείς να χρησιμοποιείς τον κωδικό F για να ξέρεις πότε κάνει fail;

**Comment by dimkasta** [comment]
Παίρνω στο response success=true, κωδικό F και λαμβάνω email επιβεβαίωσης για την επιτυχία της συναλλαγής

**Comment by Sotiris-k** [comment]
Δυστυχώς δεν μπορώ να αναπαραγάγω το πρόβλημά σου.

Εγώ χρησιμοποιώ την φόρμα που έχουν στο παράδειγμα για να πάρω το CreditCard[Token] και μετά το χρησιμοποιώ στο call δημιουργίας νέου Transaction (μαζί με Ordercode και Sourcecode). Έτσι παίρνω το fail.

**Comment by Sotiris-k** [comment]
Κάνω POST εδώ http://demo.vivapayments.com/api/transactions/?key=to_public_key_sou_edw

**Comment by Sotiris-k** [comment]
Έπρεπε να ρωτήσω από την αρχή ποιά υλοποίηση προσπαθείς να καταφέρεις. 

Εγώ χρησιμοποιώ Native Checkout ενώ εσύ Simple Checkout. Το είχα κάνει κάποτε, πριν αρκετά χρόνια, το Simple Checkout αλλά τώρα δεν θυμάμαι τίποτα...

**Comment by dimkasta** [comment]
Το ψηλιάστηκα :) Και νόμιζα ότι το είχα γράψει στο πρώτο πόστ :)

Σ' ευχαριστώ πάντως

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
