### ISSUE TITLE
Wordpress

### ISSUE THREAD

**Issue by vladimir075** [VivaPayments/API#56]
Hi! I have purchased a wordpress template that allow payments through paypal and stripe payment systems. But I need my payment system to be Greek one (the company is located in Greece) and to have Greek checkout language. So my question is if VivaPayments system can be implemented to wordpress theme.

**Comment by dpnevmatikos** [comment]
Hi there @vladimir075 
Please consult the [Website Checkout ](https://github.com/VivaPayments/API/wiki#website-checkout) section at Viva Payments wiki for more information.
There are also third party plugins available if you are using woocommerce (not supported or maintained by Viva Payments).

**Comment by vladimir075** [comment]
Hi, I would like to to test how native (on my website) checkout flow 
behavior. I made account but don't know how to check real time checkout 
flow. Please advise.

Best regards,

Vladimir Khanukaev
President

GREECE.RU Property Development S.A.
Real Estate Services & Legal Assistance

Tel:  (+30) 2310 567 433
Fax: (+30) 2310 557 151

www.greece.ru
www.privatevacation.com
www.newgreece.ru

“GREECE.RU” has been presenting select Greek properties onto the international market for over 10 years. The Head office of the company is situated in Thessaloniki, Greece and branch offices are located in Moscow and Halkidiki (in the district of Sani Resort). Also, the company has strong partnerships in Russia, the countries of CIS and, of course, Greece and the rest of Europe.

**Comment by dpnevmatikos** [comment]
Hi again,
In order to use Native checkout properly and understand the flow please check
the related documentation [here](https://github.com/VivaPayments/API/wiki/Native-Checkout) .

**Comment by vladimir075** [comment]
This is documentation for integrating it. Before I assign a developer to 
integrate it I would like to see how it works in a test mode. How I can 
do it?

Best regards,

Vladimir Khanukaev
President

GREECE.RU Property Development S.A.
Real Estate Services & Legal Assistance

Tel:  (+30) 2310 567 433
Fax: (+30) 2310 557 151

www.greece.ru
www.privatevacation.com
www.newgreece.ru

“GREECE.RU” has been presenting select Greek properties onto the international market for over 10 years. The Head office of the company is situated in Thessaloniki, Greece and branch offices are located in Moscow and Halkidiki (in the district of Sani Resort). Also, the company has strong partnerships in Russia, the countries of CIS and, of course, Greece and the rest of Europe.

**Comment by dpnevmatikos** [comment]
You could try running a sample project found [here](https://github.com/VivaPayments/API/tree/master/NativeCheckout).

**Comment by vladimir075** [comment]
Dear Dimitris, I am not a developer so it's difficult to understand for 
me how to set it. Can you help me to see it in live mode?

Best regards,

Vladimir Khanukaev
President

GREECE.RU Property Development S.A.
Real Estate Services & Legal Assistance

Tel:  (+30) 2310 567 433
Fax: (+30) 2310 557 151

www.greece.ru
www.privatevacation.com
www.newgreece.ru

“GREECE.RU” has been presenting select Greek properties onto the international market for over 10 years. The Head office of the company is situated in Thessaloniki, Greece and branch offices are located in Moscow and Halkidiki (in the district of Sani Resort). Also, the company has strong partnerships in Russia, the countries of CIS and, of course, Greece and the rest of Europe.

**Comment by dmihos** [comment]
Hi Vladimir

Thanks for your interest in our services.

There is, sadly, no way for you to test the native checkout flow without coding, but you can get an idea of our services by testing the ‘Pay with Viva Wallet’ checkout.
There is a relative link, at the bottom of this page http://www.vivawallet.com/en-us/business/pay-with-vivawallet

Native checkout allows you to render a payment form, in your site, with all the basic fields (card number, card owner, expiration date, CVC) and perform a server-side charge with the token you get.
It involves development from your part, but the steps are pretty straight forward.
Details are given in the page @dpnevmatikos gave you ahead.
We’re always here to assist you, of course.

For easier integration, you can also consider using Redirect Checkout (https://github.com/VivaPayments/API/wiki/Redirect-Checkout)

**Comment by vladimir075** [comment]
Thank you a lot!

Best regards,

Vladimir Khanukaev
President

GREECE.RU Property Development S.A.
Real Estate Services & Legal Assistance

Tel:  (+30) 2310 567 433
Fax: (+30) 2310 557 151

www.greece.ru
www.privatevacation.com
www.newgreece.ru

“GREECE.RU” has been presenting select Greek properties onto the international market for over 10 years. The Head office of the company is situated in Thessaloniki, Greece and branch offices are located in Moscow and Halkidiki (in the district of Sani Resort). Also, the company has strong partnerships in Russia, the countries of CIS and, of course, Greece and the rest of Europe.
