### ISSUE TITLE
 Πρόβλημα με Πολλαπλά κουμπιά σε simple mode

### ISSUE THREAD

**Issue by dimkasta** [VivaPayments/API#560]
Όταν βάζω πάνω από 1 κουμπί, στην ίδια ή σε διαφορετική φόρμα στην ίδια σελίδα, το script του simple checkout παύει να λειτουργεί.
Τα κουμπιά μένουν κενά, χωρίς περιγραφή, και δεν λειτουργούν

Δείγμα εδώ
https://jsbin.com/wuneveqifu/edit?html,output

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
