### ISSUE TITLE
native check out

### ISSUE THREAD

**Issue by johnpaizis** [VivaPayments/API#561]
Hi,
When trying to integrate Native Checkout I get 

Failed to load https://demo.vivapayments.com/api/cards/installments?key=y0M6%2B4lNUHLRd9z9zwVhKrJ2V6cfjevDsPUlICFSnNA%3D: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://prodelivery.gr' is therefore not allowed access. The response had HTTP status code 404.

Please advise!

**Comment by Sotiris-k** [comment]
This is a [CORS issue](https://www.w3.org/wiki/CORS_Enabled).

API Calls should be done from the backend.
