### ISSUE TITLE
Simple Checkout στον Chrome

### ISSUE THREAD

**Issue by donfn** [VivaPayments/API#568]
Στον (δικό μου τουλάχιστον) Chrome, το simple checkout κάνει ό,τι να ναι... Ποιο συγκεκριμένα:
Στην αγορά με κάρτα, μετά από την συμπλήρωση των στοιχείων, το πάτημα του κουμπιού "Πληρωμή €ΧΧ" και την ολοκλήρωση του 3-DS(το δοκίμασα στο production με κανονική κάρτα της Alpha),  το κουμπί γίνεται κόκκινο και εμφανίζει ένα X. 
![image](https://user-images.githubusercontent.com/12240818/42725150-ac31d9c2-8787-11e8-857b-0e0ff1d285ca.png)
![image](https://user-images.githubusercontent.com/12240818/42725162-bc10c7d6-8787-11e8-9187-ea6417e98978.png)

Στην κονσόλα παίρνω σφάλμα 500:
![image](https://user-images.githubusercontent.com/12240818/42725169-e570d22e-8787-11e8-9556-87c1d41ea80f.png)
οπότε κάτι παίζει με το backend (??). Δεν ξέρω...πάντως στον Opera δουλεύει ρολόι το Simple Checkout.

Επίσης...Κατά την πληρωμή με Viva Wallet, το iFrame πιάνει όλη την οθόνη, κάνει logout (χωρίς να σε αφήνει να ξαναμπείς) και δεν κάνει τίποτα.
![image](https://user-images.githubusercontent.com/12240818/42725205-95423ee0-8788-11e8-80e0-3aa90cc06ac5.png)
![image](https://user-images.githubusercontent.com/12240818/42725211-b0613ffa-8788-11e8-9f6e-0d58fbe82b82.png)
![image](https://user-images.githubusercontent.com/12240818/42725215-bc719740-8788-11e8-88d3-7ac825d90385.png)

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
