### ISSUE TITLE
API Integration Issue - Authentication Error (CC-981379)

### ISSUE THREAD

**Issue by g0d** [VivaPayments/API#572]
Χαίρεται,

Προσπαθώ να κάνω integrate το Native API σας και ασχέτως με ποιο τρόπο το κάνω, συνέχεια λαμβάνω το παρακάτω μύνημα:

HTTP/1.1 404 Invalid or inactive reseller with id 22c663c1-b4cd-48c0-abd3-5b360e888f27 Server: nginx/1.4.6 (Ubuntu) Date: Sat, 14 Jul 2018 17:21:42 GMT Content-Length: 0 Connection: keep-alive X-Viva-CorrelationId: 18-195-533C6F11

Έψαξα στο GitHub αλλά τίποτα δεν επιλύει το θέμα μου.
Ο λογαριασμός είναι όντως ανοικτός και ενεργός (αυτό μου είπαν στο support για το ερώτημα που άνοιξα με κωδικό: CC-981379) και δεν έχω προβλήματα με όλα τα άλλα θέματα που είχαν πρώην συνάδελφοι με τα TLS, encryption γενικά, headers κτλ. Άρα είμαι μπερδεμένος στο τί συμβαίνει αφού το μήνυμα λέει ξεκάθαρα πως ο λογαριασμός είναι INVALID or INACTIVE...?

Merchant ID: 22c663c1-b4cd-48c0-abd3-5b360e888f27
Platform: Customized WordPresss + code from scratch

**Comment by g0d** [comment]
Γεια σας,

ακόμα παίρνω το ίδιο...
HTTP/1.1 404 Invalid or inactive reseller with id 22c663c1-b4cd-48c0-abd3-5b360e888f27 Server: nginx/1.4.6 (Ubuntu) Date: Wed, 18 Jul 2018 10:44:10 GMT Content-Length: 0 Connection: keep-alive X-Viva-CorrelationId: 18-199-82A587D1

**Comment by g0d** [comment]
Γεια σας,

ΔΕΝ εχω καμία απαντηση και το σύστημά σας το χρειάζομαι γιατί ετοιμάζω ένα προϊόν που θα βγεί στην παραγωγή. Γνωρίζεται τί συμβαίνει? Έχετε κάποια στοιχεία για το ενδεχόμενο λάθους από πλευρά σας ή πλευράς μας?

Αναμένω απάντηση προς επίλυση.

Ευχαριστώ.

**Comment by g0d** [comment]
Χαίρεται,

Επειδή ειναι κουραστικό πραγματικά αυτό. Έχετε μηχανικούς που γνωρίζουν τη λύση, έχετε τρόπο να κάνετε assess το κώδικα σας και να μας παρέχετε λύση ή να το ξεχάσουμε?

**Comment by dpnevmatikos** [comment]
Καλησπέρα @g0d 
Έχετε δοκιμάσει τα βήματα όπως περιγράφονται [εδώ](https://github.com/VivaPayments/API/wiki/Native-Checkout)?

Στην περίπτωση που τα έχετε δοκιμάσει και πάλι έχετε θέμα, μπορείτε να μας δείξετε τον κώδικα που χρησιμοποιείτε για την Native?

**Comment by g0d** [comment]
Καλησπέρα. Εμείς κάνουμε χρήση της PHP, δε βοηθά ιδιαίτερα η υλοποίηση και η λύση σε C#. Θα πρέπει να μιλήσω με τους συνεργάτες μου για το κατά πόσον μπορώ να μοιράσω κώδικα. Πάντως τα δεδομένων τα παραλαμβάνει ο server σας άρα από εκεί και πέρα θεωρώ πως είναι κάποια αδυναμία στη δική σας υλοποίηση ή κάποιο side case. Θα επιστρέψω με πληροφορία αναλόγως. Ευχαριστούμε.

**Comment by hsintichakis** [comment]
Καλησπέρα, 
δοκιμάστε να αφαιρέσετε τον χαρακτήρα "%" από το API key ή και να τον αντικαταστήσετε με κάποιον άλλο χαρακτήρα.
