### ISSUE TITLE
SUPER URGENT Error in Viva wallet card operation Ticket No (CC-985455)

### ISSUE THREAD

**Issue by mvoreadi** [VivaPayments/API#575]
Καλησπέρα, όπως είπαμε και τηλεφωνικά ξαφνικά η πληρωμή με κάρτα δεν δουλεύει.  Το ηλεκτρονικό κατάστημα μου είναι το Anthoshop.com και είναι σε πλατφόρμα Shopify.  Η σύνδεση με το Viva wallet έχει γίνει μέσω της εφαρμογής που έχετε για το Shopify και δούλευε κανονικά μέχρι προχθές. 

Παρακαλώ για άμεση διευθέτηση του θέματος γιατί χάνουμε πωλήσεις!

Ευχαριστώ,
Μαριλένα Βορεάδη

![image](https://user-images.githubusercontent.com/32038103/42928225-62862240-8b3f-11e8-98b6-3d9398397d38.png)

**Comment by dmihos** [comment]
Καλημέρα, φροντίστε οι δοκιμές που κάνετε να είναι με ποσά μεγαλύτερα από το 0.01 ευρώ που δοκιμάσατε εδώ.

**Comment by mvoreadi** [comment]
Οντως τώρα δουλεύει με τεστ μεγαλύτερο των 2€. Ελπίζω να λύθηκε το πρόβλημα γιατί είχαν πρόβλημα και οι πελάτες που σίγουρα προσπαθούσαν να πληρώσουν ποσά μεγαλύτερα του 0,01.

**Comment by mvoreadi** [comment]
Το πρόβλημα λύθηκε.  Ευχαριστώ πολύ!
