### ISSUE TITLE
Αποτυχία συναλλαγής

### ISSUE THREAD

**Issue by avlachopanos** [VivaPayments/API#576]
Χαίρετε,

χρησιμοποιώ το plugin για WooCommerce σε εγκατάσταση WordPress 4.9.7–el με WooCommerce 3.4.3 . Σε test-mode η πληρωμή έδειξε ότι πέρασε αλλά όταν βάζω τα στοιχεία του πελάτη (μας και σας) και δοκιμάζω να κάνω μία κανονική πληρωμή μου βγάζει απλά

<img width="1303" alt="screen shot 2018-07-19 at 11 11 55" src="https://user-images.githubusercontent.com/6751014/42941147-7b5e86b6-8b64-11e8-9b1a-8e4472d7bcf7.png">

Μπορείτε να ελέγξετε τη συναλλαγή και να μου πείτε τι πάει στραβά ώστε να το επιλύσω;

Ευχαριστώ

**Comment by VivaWalletSupport** [comment]
Hello, what plugin is used?

**Comment by avlachopanos** [comment]
<img width="845" alt="screen shot 2018-07-20 at 09 29 49" src="https://user-images.githubusercontent.com/6751014/42986883-f1980500-8bff-11e8-9504-b1d67dd4146f.png">

**Comment by VivaWalletSupport** [comment]
Did you put the correct credentials for the live account in the plugin settings (Merchant ID / API key), did you setup a payment source in the live account and is the new source code used in the plugin settings, is the new payment source activated?

**Comment by avlachopanos** [comment]
Since the account belongs to the client I asked him to sent these data to me following the instructions on this page https://support.vivawallet.com/hc/en-us/articles/201514302-Where-can-I-find-MerchantID-API-key-and-Source-Code and then I put them in the corresponding fields of the plugin. 
Is there a way to verify that the account is active without having access to it? The client claims that it is active but perhaps he is mistaken 

![screen shot 2018-07-20 at 10 52 18](https://user-images.githubusercontent.com/6751014/42990442-511c4e4a-8c0b-11e8-8f2c-fad7b0e26d1f.png)

**Comment by VivaWalletSupport** [comment]
Let your client send a screenshot of the source listing in his Viva account.

**Comment by avlachopanos** [comment]
The client sent me the screenshot of the source listing and the source in question is active with type website and the operation switch is turned on. However in the description it does not say the domain of the e-shop but a generic description. Is this an error?

**Comment by VivaWalletSupport** [comment]
It should not matter, please post a screenshot of the source listing and the payment source settings.

**Comment by avlachopanos** [comment]
![viva1](https://user-images.githubusercontent.com/6751014/43017850-4eea1d8c-8c60-11e8-9c58-d9ebaa798476.jpg)
![viva2](https://user-images.githubusercontent.com/6751014/43017851-4f2e0a74-8c60-11e8-8d89-b1055000abdf.jpg)

**Comment by VivaWalletSupport** [comment]
The supported plugin does not work with the Native but with the Redirection Integration method. Ask your client to correct this in the payment source and to put also the correct return URLs.

**Comment by avlachopanos** [comment]
Success! Thank you very much for the help
