### ISSUE TITLE
API Call Failed

### ISSUE THREAD

**Issue by djdesigngr** [VivaPayments/API#58]
Καλησπέρα σας, έχω ενσωματώσει τον κώδικα για create order αλλάζοντας τα στοιχεία που πρέπει στα δικά μου και μετέπειτα σε demo αλλά και σε live περιβάλλον μου εμφανίζει Api call failed. Τι λάθος μπορεί να έχει γίνει. Σας ευχαριστώ εκ των πρωτέρων

**Comment by dpnevmatikos** [comment]
Καλησπέρα @djdesigngr 
Χρησιμοποιείτε το sample σε php? Αν ναι, τότε θα πρέπει να γυρνάει και ένα error code η κλήση στην ```CreateOrder```. Μπορείτε να δείτε ποιο error code είναι αυτό?
