### ISSUE TITLE
Payment doesn't get registered in prestashop backend

### ISSUE THREAD

**Issue by DimosthenisK** [VivaPayments/API#582]
Greetings,
after the (successful) installation of the module in prestashop, some orders get paid from vivawallet but they don't appear in my prestashop backend. They do, however, appear in my vivawallet.

I also enabled the webhook which sadly changed nothing.
Anyone knows what is going on?

**Comment by VivaWalletSupport** [comment]
Hello, what module are you using? Could you post screenshots from the module and payment source settings?

**Comment by voidblaze** [comment]
Im using [this](https://github.com/VivaPayments/API/tree/master/Plugins/prestashop/vivawallet) one. I believe that settings are irrelevant as most payments go through, but there you go: 
![image](https://user-images.githubusercontent.com/32791127/43187404-f6d1429a-8ff9-11e8-95aa-80ecaecdf620.png)
![image](https://user-images.githubusercontent.com/32791127/43187562-64bdf92e-8ffa-11e8-8c72-e226a7cb5332.png)


Let me know ASAP if I have revealed something that i shouldn't have.

**Comment by VivaWalletSupport** [comment]
When testing a (fail) transaction I get an HTTP 500 error when getting returned to the store. Please investigate was causes this to happen (check Presta/PHP error logs).

**Comment by voidblaze** [comment]
Both only have errors from 2016.

**Comment by VivaWalletSupport** [comment]
Make sure you see the last pages of your Prestashop log and enable logging in case it has been disabled.

**Comment by voidblaze** [comment]
My only errors are from PaymentModule, and they state "Secure key doesn't match" very sporadically (about once a month). Nothing around our testing period since the first of July.

**Comment by VivaWalletSupport** [comment]
It could be a PrestaShop bug, I would suggest to keep an eye on following topic: http://forge.prestashop.com/browse/BOOM-5074

**Comment by VivaWalletSupport** [comment]
Hello voidblaze, please close this issue in case the problem has been resolved, otherwise let me know how I can help.

**Comment by ludofrenchy** [comment]
Hello,
I have the same problem.
The customer has finalized his order, made the payment, which is registered on my vivawallet account but nothing displayed in my backend.
did you find a solution?
I am on prestashop 1.7.5.2

Thank you
