### ISSUE TITLE
Πρόβλημα χρήσης κώδικα για πληρομές

### ISSUE THREAD

**Issue by nplion** [VivaPayments/API#588]
Καλημέρα,

Έχω δοκιμάσει να χρησιμοποιήσω των κώδικα από το https://github.com/VivaPayments/API/tree/master/NativeCheckout/PHP
το $response από το function ExecuteCall είναι πάντα καινό οπότε εμφανίζει λάθος στον κώδικα

Δοκίμασα τον κώδικα και από το
https://github.com/VivaPayments/API/tree/master/CreateOrder/PHP
ξανά το $response είναι είναι καινό

Δοκίμασα τελικά την ποιο απλή λύση με το κουμπί, όλα καλά, παίρνω το Token, τι να το κάνω μετά? Δεν έχετε κανένα simple σε php?
STEP 2: Make the charge σε PHP υπάρχει?

**Comment by matthewrgourd** [comment]
Sorry that your issue wasn't responded to before this time. Please refer to our [Developer Portal](https://developer.vivawallet.com) if you have any further technical queries. Otherwise please raise another issue here and I'll be happy to help. Thanks!
