### ISSUE TITLE
Οι πληρωμές ξαφνικά σταματησαν να λειτουργουν, αλλαξε το URL χωρίς να το πειράξουμε

### ISSUE THREAD

**Issue by LarosPericles** [VivaPayments/API#59]
Καλησπέρα,

Ενω όλα δουλεύαν σωστά εδώ και 2 χρόνια...
Εδώ και κάποιες ημέρρες, οταν κάποιος παει να κανει μια πληρωμη Live τον σταματάει επιτόπου στο δευτερο βήμα με μηνυμα "Η συναλλαγή σας απέτυχε." μιλησα με κάποια κυριά και μου είπε οτι τα Settings στις πηγες δεν ηταν σώστα. Ειμαστε 100% σιγουροι οτι κανένας δε πείραξε τα Settings παρολα αυτά το URL www.vivapayments.com !!! Φαινετε οτι κάποιος άλλος εκτός του account μας τα πείραξε ή έγινε κάποιο Crash στην εφαρμογή σας? 

Αλλάζοντας πάλι τα Settings στο σωστό URL εξακολουθούμε να λαμβάνουμε το ίδιο μήνυμα οταν κάνουμε μια Live πληρωμή.

Υπάρχει κάποιος private τρόπος επικοινωνίας για να μην εκθέτουμε τα Links και τα Merchant ids στο Public Forum?

Ευχαριστώ

**Comment by dpnevmatikos** [comment]
Καλησπέρα,
Παρακαλούμε επικοινωνήστε μαζί μας στο merchants@vivawallet.com παραθέτοντας στοιχεία για τον εν λόγω έμπορο (αφμ ή merchant Id, κωδικός πηγής) και το github issue.

Ευχαριστούμε.
