### ISSUE TITLE
Δεν εμφανίζεται/αποθηκεύετε η επιλογή πληρωμής

### ISSUE THREAD

**Issue by legacyapparel** [VivaPayments/API#592]
Καλησπέρα σας εχω κατεβάσει το Plugin για το Virtuermart 2 εχω κανει κανονικά εγκατασταση αλλα όταν κανω αποθηκευση των παραμέτρων στο virtuemart δεν μου αποθηκέυει τα πεδία που εχω ορίσει ενώ μου βγαλει μηνυμα οτι τα εκανε save. Μπορεί να βοηθήσει καποιος σχετικά;

Έχω Joomla 2.5 και VM.2
PHP εχω δοκιμάσει όλες τις versions

**Comment by VivaWalletSupport** [comment]
Hello, please try the updated package.
[vm_plugin_vivawallet.zip](https://github.com/VivaPayments/API/files/2309723/vm_plugin_vivawallet.zip)

**Comment by VivaWalletSupport** [comment]
Hello legacyapparel, please close this issue in case the problem has been resolved, otherwise let me know how I can help.
