### ISSUE TITLE
CC-1010652

### ISSUE THREAD

**Issue by espressocoffice** [VivaPayments/API#594]
Έκδοση WooCommerce: 3.4.4
• ποια η version της πλατφόρμας αυτής
Έκδοση WordPress:                                                                                 4.9.8
Το πρόβλημα αν και σας το έχουμε περιγράψει τηλεφωνικά, ενώ φεύγει από το σύστημα του WooCommerce και ανοίγει η δική σας σελίδα εισαγωγής των στοιχείων της κάρτας ο πελάτης συμπληρώνει τα στοιχεία του, το σύστημα σας επικοινωνεί με την τράπεζα, η τράπεζα στέλνει επιβεβαιωτικό κωδικό ασφαλείας συναλλαγής ο πελάτης πατάει οκ αλλά δεν γίνεται ούτε η χρέωση στον πελάτη ούτε το σύστημα σας επιστρέφει στο δικό μας τον κωδικό πληρωμής, χωρίς κανένα μήνυμα προβλήματος, ούτε στον πελάτη ούτε σε μας και με μηνυμα επιτυχής  συναλλαγής.

Αναμένουμε τις ενέργειες σας και τις οδηγίες σας.

**Comment by espressocoffice** [comment]
https://el.wordpress.org/plugins/woo-payment-gateway-for-vivapayments/

**Comment by VivaWalletSupport** [comment]
In case you have a problem with that plugin, you might try their support first.
https://wordpress.org/support/plugin/woo-payment-gateway-for-vivapayments

**Comment by espressocoffice** [comment]
As we describe and explain in phone call with Viva, we don't.have problem with plugin and everything works and communicate perfect with viva system. Viva system has the problem and while customer is in your system, pul all bank card info, bank sent the 4 digit security vode via sms to accept the transaction, click ok and your system don't proceed with the payment, without any error , only that trnsaction was successful. Please check in your crm the Voice call with us and whole case please. We have describe too many times the same thing! Please, check. Tnk u.
