### ISSUE TITLE
ΚΑΤΑΣΚΕΥΗ E-SHOP

### ISSUE THREAD

**Issue by SWEETPAINMASSAGE** [VivaPayments/API#598]
ΠΩΣ ΜΠΟΡΟΥΜΕ ΝΑ ΜΑΘΟΥΜΕ : ΟΝΟΜΑ ΤΡΑΠΕΖΑΣ , ΚΩΔΙΚΟΣ SORT , BIC/SWIFT KAI VivaPayments CodeId. ΤΑ ΧΡΕΙΑΖΟΜΑΣΤΕ ΣΑΝ ΣΤΟΙΧΕΙΑ ΓΙΑ ΤΡΟΠΟ ONLINE ΠΛΗΡΩΜΩΝ.

**Comment by SWEETPAINMASSAGE** [comment]
ΜΠΟΡΕΙ ΚΑΠΟΙΟΣ ΝΑ ΜΕ ΒΟΗΘΗΣΕΙ?

**Comment by VivaWalletSupport** [comment]
Could you describe in a more detailed way what you need? Are you using a specific payment plugin or custom code, do you need to store these variables after a transaction etc.

**Comment by SWEETPAINMASSAGE** [comment]
I MADE AN E-SHOP SITE AND I NEED SOME DETAILS FOR ONLINE PAYMENT. I HAVE TO KNOW , SORT CODE AND VivaPayments CodeId . HOW CAN I FIND THIS?

**Comment by VivaWalletSupport** [comment]
In case you are using a ready made plugin for connecting your store with Viva, please post a URL where you got the plugin from.

**Comment by SWEETPAINMASSAGE** [comment]
https://www.papaki.com/cp2/?lang=el-GR

**Comment by VivaWalletSupport** [comment]
In case following is the plugin: https://el.wordpress.org/plugins/woo-payment-gateway-for-vivapayments/#installation you can download their installation pdf that has clear information on the subject.

**Comment by VivaWalletSupport** [comment]
Hello SWEETPAINMASS, please close this issue in case the problem has been resolved, otherwise let me know.
