### ISSUE TITLE
ecommerce plugin - need some help developing

### ISSUE THREAD

**Issue by emanoyhl** [VivaPayments/API#60]
hi i'm trying to create a plugin for an ecommerce site and based on all your code samples, it seems incomplete...

basically i want to submit the payment amount to vivawallet and i even tried using your button (which has an error on your public site, missing a " for action) and it's just not going through - also i'm not receiving a redirect... or response action...

do you have any complete code that we can actually work with or is it just these bits and pieces?

where are the complete variables list that are passed onto viva and returned (POST/GET)?

any help greatly appreciated

i'm using oscommerce 2.1.0.1 - so i just need php coding - just want to pass the info at checkout into the vivapayment button so it pops up to pay, then once complete, to close the button popup and finish the process on my site for successful checkout and confirmation...

**Comment by dpnevmatikos** [comment]
Hi there @emanoyhl 
From what I understand you are trying to use the "Pay with Viva Wallet" payment method.
Did you follow the steps listed [here](https://github.com/VivaPayments/API/wiki/Pay-with-Viva-Wallet) ?
If you did then are there any errors logged in the browser's console?

**Comment by emanoyhl** [comment]
yes i have

the only error i get is "VivaPayments: Required data-vp attribute "publickey" was not found or is empty"

it's as if is not submitting the publickey in POST...

**Comment by dpnevmatikos** [comment]
Hi @emanoyhl 
From what you're saying it seems that you are missing the ```data-vp-publickey``` attribute from the button's rendering code. The public key is required both for Native checkout and Pay with Viva Wallet checkout.
Please take a look at the [first step ](https://github.com/VivaPayments/API/wiki/Pay-with-Viva-Wallet#step-1-display-the-button) required for rendering a "Pay With Viva Wallet" correctly.

**Comment by emanoyhl** [comment]
yes i have done all the steps correctly ... i believe i found the problem of not passing the public key - now i am having this issue:
VivaPayments: Invalid data-vp-lang value - i have tried with el-GR and also leave it empty returns same error...

**Comment by dpnevmatikos** [comment]
You need to use either 'el' for Greek or 'en' for US-English. Please have a look [here](https://github.com/VivaPayments/API/wiki/Pay-with-Viva-Wallet#received-parameters).

**Comment by emanoyhl** [comment]
now i receive these errors:
[Error] Unable to post message to http://demo.vivapayments.com. Recipient has origin http://www.MYSITENAME.gr.

	postMessage
	nt (js:1:5942)
	(anonymous function) (js:1:6774)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (btn_el.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (simplecheckout, line 0)

**Comment by emanoyhl** [comment]
http://demo.vivapayments.com/api/orders/web/checkout/simplecheckout?publickey=MYKEYISHERE&amount=0.00&lang=el&baseurl=http%3A%2F%2Fdemo.vivapayments.com%2Fapi%2Forders&description=MYSITEDESCRIPTION

http://demo.vivapayments.com/api/orders/web/content/images/simplecheckout/btn_el.png


both those return 404 not found...

**Comment by dpnevmatikos** [comment]
Try using ```demo.vivapayments.com``` as the base URL instead of ```demo.vivapayments.com/api/orders```.

**Comment by emanoyhl** [comment]
i have - and i still get this:
[Error] Unable to post message to http://demo.vivapayments.com. Recipient has origin http://www.MYSITE.gr.

	postMessage
	nt (js:1:5942)
	(anonymous function) (js:1:6774)
[Error] Failed to load resource: the server responded with a status of 403 (Invalid merchant public key) (simplecheckout, line 0)

http://demo.vivapayments.com/web/checkout/simplecheckout?publickey=MYPUBLICKEY&amount=0.00&lang=el&baseurl=http%3A%2F%2Fdemo.vivapayments.com%2F&description=MYDESCRIPTION

**Comment by emanoyhl** [comment]
i double checked my public key and is correct - and the error shows the key as correct.... (of course i replaced with "MYPUBLICKEY" to not reveal on this forum)

what could be the problem?

**Comment by emanoyhl** [comment]
it's as if the public key is being html escaped - in my public key i have the `/` and `=` characters.... in the error where it shows the code it shows the escaped '%252F' and '%253D' respectively.... 

https://demo.vivapayments.com/web/checkout/simplecheckout?publickey=MYPUBLIC%252FKEY%253DSEETHEESCAPEDCHARACTERS&amount=0.00&lang=el&baseurl=https%3A%2F%2Fdemo.vivapayments.com%2F&description=MYDESCRIPTION&merchantref=Array
Failed to load resource: the server responded with a status of 403 (Invalid merchant public key)

**Comment by dpnevmatikos** [comment]
> Failed to load resource: the server responded with a status of 403 (Invalid merchant public key)

This clearly indicates that you are using a wrong public key. Please note that the key you use in the demo environment is not the same with the one used for production.
Did you get your demo key by logging into ```demo.vivapayments.com```?

**Comment by emanoyhl** [comment]
yes - i have

i'm using everything on the demo account setup with the public key, merchant id, api key, etc...

**Comment by emanoyhl** [comment]
any news?

still having problems here...

**Comment by emanoyhl** [comment]
seriously does viva wallet even want people to use their service to receive any type of payments since most of us cannot set it up properly because either 1. your example code are useless and incomplete, or 2. the support is very very lacking....

again, any help on this?? or should i look elsewhere for a payment system?

thanks

**Comment by dmihos** [comment]
Hi emanoyhl

The samples provided here at GH are working, verified, usable samples.
We're doing our best to provide support, thanks for understanding.

There's clearly something wrong with your implementation. 
I can only advise you send an email to merchants@vivawallet.com with your sample, containing public key, for further investigation.
Please don't forget to mention this Github issue for reference.

Thank you

**Comment by emanoyhl** [comment]
i understand is frustrating when there is no immediate response, not just from admins here but from other users who may be experiencing same issues - regardless i have resolved the invalid key and have gotten all the way to the viva wallet payment section - i add the fake card values of 4111 1111 1111 1111 etc, and i click to submit and it will not - with this new error:

Failed to load resource: the server responded with a status of 500 (Internal Server Error) https://demo.vivapayments.com/web/checkout/getpaymenttoken

"The required anti-forgery cookie &quot;__RequestVerificationToken_L1dlYg2&quot; is not present."

**Comment by emanoyhl** [comment]
Server Error in '/Web' Application.

The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /web/checkout/getpaymenttoken

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1069.1



is problem from your site??

**Comment by dmihos** [comment]
Yes Emanouhl, you're getting 404 for a non existing Viva Payments url.
Our sample code does not produce such a url, so there's something wrong with your implementation.
Have you sent us a sample of your code to the email address I mentioned earlier?

**Comment by emanoyhl** [comment]
that url is produced when i click the vivawallet button after inputting the 4111 1111 1111 1111 cc to submit payment.... so it must be coming from somewhere.... is definitely not in the code - no i haven't submitted it yet, but will do so soon.... thanks in advance
