### ISSUE TITLE
Transactions suddenly stopped working

### ISSUE THREAD

**Issue by vasgrigor** [VivaPayments/API#600]
Hello.
We have been experiencing a problem with payments lately. While everything worked well for many months and we were normally accepting payments through the API, a problem suddenly occurred. We use our own custom code on our website and your own code in php for payments. We did not make any changes to the code, nor did we make any changes to the VIVA account page, and the problem appeared all of a sudden. The merchantid and apikey codes are correct, we checked them.
The problem as we have spotted from our side is that the create_order.php page no longer creates a orderid (does not return an orderedid number). So when our site tries to make a new transaction after that, eventually that leads to a page with a Bad Request error (https://www.vivapayments.com/web/newtransaction.aspx?ref=). I will write again that everything worked well until recently and we did not make any changes.
We would please need some guidance about how the problem can be corrected so that purchases can be made again through our website. Please check your system records for the latest purchase requests from our  website (teacherland.gr) and let us know what could be the problem and how it could be fixed.

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
