### ISSUE TITLE
Iframe not working in Safari

### ISSUE THREAD

**Issue by neomobil** [VivaPayments/API#601]
Hi!
I get a 500 when I want to make Simple payment from Safari. The same is working in Chrome.

**The request:**

MIME-Typ: application/x-www-form-urlencoded; charset=UTF-8
CheckoutOptions.Amount: 1088400
CheckoutOptions.Lang: en
CheckoutOptions.Description: test.com
CheckoutOptions.MaxInstallments: 0
CheckoutOptions.MerchantRef
CheckoutOptions.PublicKey: LZmm8E8FLUJmRMPQFAssIV3mkzsrgQ3wbDIp7XcsZno=
CheckoutOptions.SourceCode
CheckoutOptions.ResellerId
CheckoutOptions.ResellerSourceCode
CheckoutOptions.Preauth: False
CountryCode: GR
__RequestVerificationToken: 9zKVGkgTpNsPv4J869fY8Qkdl-bACwGg-Ji80Pc-5hpsyt_x6rQ4jS7tmnARcTfEtU4DhT_m8Kxql-N2vJEZ3vGnGDwEwStRnvLzWAysA2U1
CardNumber: 4111111111111111
ExpDate: 10 / 20
CardCVV: 111
Installments
FirstName: test
LastName: test
CheckoutOptions.CustomerEmail: test@test.com
FullName: user name
Month: 10
Year: 20
CardHolderAuthenticationSessionId: 7ad9c880-f637-4a98-917d-cf35b4df0ec4

**The response from server:**

HTTP/1.1 500 Internal Server Error
Cache-Control: private
Content-Type: text/html; charset=utf-8
Date: Tue, 11 Sep 2018 17:28:46 GMT
Connection: keep-alive
Server: nginx/1.4.6 (Ubuntu)
Content-Length: 3423
X-Viva-CorrelationId: 18-254-E192188E
p3p: CP=Internet Explorer Requires This In Order to Set Third Party Cookies

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
