### ISSUE TITLE
Is it possible to use the API to pay end users directly?

### ISSUE THREAD

**Issue by AdrianHarrisinLondon** [VivaPayments/API#602]
Hi -  we have a marketplace type app (iOS & Android) where we want almost all of the customer payment  to go directly to the end recipient,  Who might be an individual rather than a business, and who might have a viva wallet, PayPal account, Stripe account, bank account etc,  and a small commission to be split to go to our merchant account directly- is this possible please?

**Comment by kostGX** [comment]
Hello @AdrianHarrisinLondon, please visit our website https://www.vivawallet.com/en-gb/contact-us/ and request a contact by our sales team about that. 

Thanks
