### ISSUE TITLE
prestashop, multicurrency issues

### ISSUE THREAD

**Issue by alkalline** [VivaPayments/API#603]
I have installed the prestashop plugin in a multicurrency eshop running PS 1.6.1.11 and noticed 2 issues:

-viva processes all payments in Euro, but it doesn't actually convert the price of the items. e.g. if something costs 1€ and you swith to USD (visiting from the US does so automatically), the shop will display the price as $1,16 (the actual value converted into USD), but when you select to pay the price transmitted to viva will be 1,16€.

-there is something wrong with GBP. If the currency is set to British Pound the server returns error 500 at order?step=5 (the payment selection screen).

**Comment by VivaWalletSupport** [comment]
Just made some corrections, please try the latest files.
[vivawallet.zip](https://github.com/VivaPayments/API/files/2378997/vivawallet.zip)

**Comment by VivaWalletSupport** [comment]
Make sure you are not using cached files, that you have set the currency convertion rates correctly and have a look at your error logs why you receive a 500 error when using GBP.

**Comment by alkalline** [comment]
![viva-multicurr](https://user-images.githubusercontent.com/15138466/45486417-b02a2f00-b763-11e8-803e-df0a3d60c3ed.gif)

I have cleared both the server cache as well as my session.
I can see the currency correction code you added. Still no go.
I will further investigate the GBP issue and give hints if I find a cause.

**Comment by alkalline** [comment]
PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to create order code (Person ***some-person*** does not support currency '826')' in ***some-path***/modules/vivawallet/vivawalletold.php:283

**Comment by VivaWalletSupport** [comment]
In case GBP is not supported in your Viva account you can disable it from the modules settings or request to enable it for your MID. Regarding the USD issue, I cannot replicate it. Is this currency supported in the module settings and if so, can you test by do a die statement on the $currency_symbol in the code?

**Comment by alkalline** [comment]
I have disabled the plugin for both USD and GBP for the time being. Did you just register to test it? I can enable it for a bit for you to try.

I will look into the GBP setting as I am not the merchant and I will need him to look into it.

**Comment by VivaWalletSupport** [comment]
Yes I did register, but in order to debug I would need FTP and store admin access. If needed send it to 
vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com

**Comment by alkalline** [comment]
Everything works as intended now. Thanks a ton!
