### ISSUE TITLE
Transaction 

### ISSUE THREAD

**Issue by pakagyla** [VivaPayments/API#605]

**Comment by pakagyla** [comment]
Καλησπέρα, 

Χρησιμοποιούμε το Opencart Cms στην έκδοση 3.0.2.0. 
Το module που έχουμε χρησιμοποιήσει είναι το https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=26471&page=8

Το μήνυμα που βγάζει είναι attach. 
<img width="1202" alt="2018-09-20 11 40 30" src="https://user-images.githubusercontent.com/30188766/45810296-fb4bc100-bcd2-11e8-9832-75b3ae3bda4e.png">

**Comment by pakagyla** [comment]
Καλυσπέρα , μποροώ να έχουμε μια απάντηση παρακαλώ?

**Comment by hsintichakis** [comment]
Καλησπέρα, θα πρέπει να επικοινωνήσετε με τον developer του συγκεκριμένου plugin.
