### ISSUE TITLE
Shopify Integration: Viva Wallet appearance

### ISSUE THREAD

**Issue by pvoulg** [VivaPayments/API#607]
We build shops on behalf of our clients on the Shopify platform, and we've activated the Viva External Payment Gateway method for most of them.

I'd like to know whether there's any chance the wording that appears during Checkout, can in any way be altered since we're facing a specific issue: some of our clients sell their products abroad and the current Viva payment option only displays the Viva Wallet logo, which isn't recognized by non-greek customers as a credit card payment method (see screenshot below). A simple **Viva Wallet - Pay via credit/debit card** or something along those lines would suffice. There is already an option to edit a longer description of the specific payment method, but that requires the user to click on the Viva option first (which isn't happening).

<img width="621" alt="screen shot 2018-09-24 at 09 27 59" src="https://user-images.githubusercontent.com/7416221/45995462-d4113d00-c0a0-11e8-99db-7d8c56921228.png">

Due to this issue, one of our clients has already reverted to a different payment method (2Checkout), after noticing a significant drop in order completion. 

Is there any way to make it clearer that this is a credit card payment method? The CC symbols on the right are apparently not enough of an indicator, as the same appear on the PayPal option just above, and customers—apparently—assume that you need an account in order to use this payment option.

Any ideas?

**Comment by kostGX** [comment]
Hello @pvoulg, thanks a lot for choosing Viva Wallet for processing your clients' payments.

Since we can only edit the logo (image) in the Shopify Gateway settings, we will try to incorporate a relevant wording to help with the drop rate.

The image dimensions required are 220x24 px so we'll see what we can fit in that.

I'll keep you posted in this thread.

**Comment by kostGX** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/3908736/46038846-dc0ac480-c114-11e8-83ac-39681d1160f3.png">

@pvoulg I just updated it to the above. Thanks for the constructive feedback. We're always interested in making the experience better for both merchants AND developers. 

Have a good one!

**Comment by pvoulg** [comment]
Thanks a lot @kostGX for your immediate response and quick fix! We'll test it right away.
