### ISSUE TITLE
Recurring payments

### ISSUE THREAD

**Issue by johndel** [VivaPayments/API#609]
Έκανα μια δοκιμή στο demo, έφτιαξα ένα Order με MaxInstallments=3 και AllowRecurring=true. Πήρα token μέσω μιας custom φόρμας μια φορά και παρατήρησα ότι με αυτό το token μπορώ να κάνω χρεώσεις παραπάνω από το order amount όπως επίσης δημιούργησα παραπάνω transactions από 3 για αυτό το order που ήταν το MaxInstallment. 

Αυτό συμβαίνει και σε production;
Το token της custom φόρμας τι διάρκεια έχει;

**Comment by kostGX** [comment]
@johndel To Installment είναι οι γνωστες άτοκες δόσεις. Διατίθεται σε καρτούχους πιστωτικών καρτών (όχι χρεωστικών ούτε προπληρωμένων). Αν για παράδειγμα κάνετε ένα Order των 100€ με 2 installments, τότε θα πληρωθείτε σε 2 μηνιαίες δόσεις των 50€. Επειδή βασίζεται στην χρήση πιστωτικών ορίων, τα χρήματα σας θα τα πάρετε σίγουρα, ακόμη κι αν ο καρτούχος δεν έχει υπόλοιπο.

Το Recurring από την άλλη, αφορά επαναλαμβανόμενες χρεώσεις, χρησιμοποιώντας το token της κάρτας στο οποίο αναφέρεστε. Ένα συχνό use case των Recurring payments είναι η λειτουργία "αποθήκευσης κάρτας για μελλοντικές αγορές". Στην περίπτωση που η κάρτα δεν έχει αρκετό διαθέσιμο υπόλοιπο, η χρέωση αποτυγχάνει και δεν πληρώνεστε.

Αν έχετε κάνει tokenize πιστωτική κάρτα, τότε μπορείτε να περνάτε σαν παράμετρο, σε call για recurring payment, το Installments και να ξεκινάτε νέο "κύκλο" άτοκων δοσεων.

Τι ακριβώς προσπαθήτε να υλοποιήσετε;

**Comment by johndel** [comment]
Μάλλον δε χρειάζομαι τότε το installment. 

Το use case είναι το εξής:
Θέλω να υλοποιήσω την χρέωση ενός "προϊόντος / υπηρεσίας" σε 3 δόσεις οι οποίες όμως θα έχουν και διαφορετική χρέωση. Αν π.χ. κοστίζει 3000 ευρώ, στην πρώτη φάση θα χρεώνεται η κάρτα 100 ευρώ, έπειτα από κάποιο διάστημα μερικών μηνών θα χρεώνεται 1400 (τα μισά μείον την αρχική χρέωση) και έπειτα από κάποιο διάστημα τα υπόλοιπα 1500. 

Ερωτήσεις:
Οπότε με το token που παίρνω από την φόρμα, θα μπορώ να το υλοποιήσω το παραπάνω; Έχω ακολουθήσει το παράδειγμα [εδώ.](https://github.com/VivaPayments/API/wiki/Native-Checkout) Όμως το token της custom form δεν είναι της credit card αλλά της credit card σε συνδυασμό με το order code και φαντάζομαι θα γίνεται expire, ή όχι;

Επίσης, κάθε φορά που επιθυμεί κάποιος να αγοράσει κάτι, θα πρέπει να βάζει τα στοιχεία της credit card; Δε βρίσκω κάπου τρόπο να αποθηκεύεται το token μιας credit card του χρήστη.

**Comment by johndel** [comment]
@kostGX Μπορείς να μου στείλεις link που να δείχνει πώς γίνεται tokenize μια πιστωτική κάρτα;

**Comment by kostGX** [comment]
@johndel hope this helps https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction

**Comment by johndel** [comment]
@kostGX Αυτό το έχω δει αλλά το ΤransactionId που ζητά δεν είναι το token της credit card. Υπάρχει τρόπος να φτιάξεις token της credit card όπως γίνεται στο stripe / braintree;

Νομίζω το documentation σας θέλει βελτίωση.

**Comment by kostGX** [comment]
@johndel Ευχαριστώ για την αναφορά. Θα φροντίσουμε να το βελτιώσουμε. Φυσικά είμαστε πάντα ανοιχτοί σε προτάσεις βελτίωσης του documentation. 

Στο θέμα μας: To functionality είναι όμοιο, με την διαφορά πως αντί να στέλνεις κάποιο token και amount για να χρεώσεις, στέλνεις το transaction id. 

**Flow**
1) Κάνεις create order περνώντας AllowRecurring=true 
`curl --request POST \
  --url http://demo.vivapayments.com/api/Orders \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data 'Amount=300&AllowRecurring=true&PaymentTimeOut=65535'`

2) Παίρνεις το Order Code και Μεταφέρεις τον χρήστη στη redirect checkout σελίδα `https://demo.vivapayments.com/web/checkout?ref=ORDER CODE`

Λόγω του AllowRecurring εμφανίζεται σχετικό checkbox στο checkout flow:
<img width="869" alt="allow recurring order" src="https://user-images.githubusercontent.com/3908736/46211181-8d8b3f00-c33b-11e8-9ae2-68787ad1db26.png">

3) Ο χρήστης πληρώνει το Order (το οποίο εμφανίζεται και στο διαχειριστικό)
![recurring sale ui](https://user-images.githubusercontent.com/3908736/46211246-be6b7400-c33b-11e8-9a40-e3d38cc4ff6b.png)

4) Για να ξαναχρεώσω την ίδια κάρτα, αρκεί είτε να κάνω το flow "Repeat" από το UI, είτε να κάνω POST το transaction ID όπως φαίνεται παρακάτω:
`curl --request POST \
  --url http://demo.vivapayments.com/api/transactions/f025e46f-7474-440b-8ad0-a403880feda2 \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data 'Amount=3000&MerchantTrns=%22merchant%20description%22&CustomerTrns=%22customer%22'`

Ελπίζω να βοήθησα.

**Comment by johndel** [comment]
@kostGX Σε ευχαριστώ πολύ. Και η τελευταία μου ερώτηση: Αν έχω custom native form αντί να κάνω redirect, πώς μπορώ να εμφανίσω στον user για να κάνει accept τις recurring payments; Τι πρέπει να σας στείλω;

**Comment by johndel** [comment]
@kostGX Μπορείς να έχεις custom payment form και recurring payments; ή δουλεύει μόνο με redirect; Αν γίνεται μόνο με redirect δεν πειράζει, θα το κάνω έτσι.
