### ISSUE TITLE
Πρόβλημα με την διασύνδεση 

### ISSUE THREAD

**Issue by konstantinos-x** [VivaPayments/API#61]
(Αφαίρεσα τα στοιχεία του site και του λογαριασμού καθώς είναι public , παρακαλώ πείτε μου  ένα τρόπο να σας τα αποστείλω για να δοκιμάσετε και εσείς αυτά που γράφω, στο τηλέφωνο μου είπαν ότι είναι private το μήνυμα από εδώ , αλλά δεν είναι οπότε δεν μπορώ να τα προσθέσω.) 

Αγαπητοί , ενώ είχα φτιάξει την διασύνδεση (και την είχα δοκιμάσει με demo λογαριασμό και όλα λειτουργούσαν σωστά) για το domain ***.gr ο ιδιοκτήτης του με ενημέρωσε ότι δεν δέχεται πιστωτικές κάρτες στο vivawallet. Το ξαναγύρισα στο demo για να σιγουρευτώ τι συμβαίνει. Μπορείτε να δοκιμάσετε και εσείς τα ακόλουθα στην διεύθυνση ***.gr .  Το τηλέφωνο του demo λογαριασμού που έχει συνδεθεί είναι ****** με όνομα ****
 
Η διασύνδεση πραγματοποιείται με επιτυχία στο πρώτο στάδιο , επιστρέφεται ordercode και γίνεται η ανακατεύθυνση κανονικά στο vivapayments. Στην σελίδα που γίνεται η ανακατεύθυνση όλα τα στοιχεία είναι σωστά όπως έχουν αποσταλεί από την εφαρμογή (Περιγραφή χρέωσης, Όνομα κατόχου, E-mail , τηλέφωνο και ποσό). Όμως όταν πηγαίνει κάποιος να πληρώσει με κάρτα ανακατευθύνετε σε μια σελίδα του vivapayments που λέει “Checkout Result Η συναλλαγή σας απέτυχε “, χωρίς να γίνεται ανακατεύθυνση στην σελίδα Failure που έχει δηλωθεί. Το πλέον παράδοξο είναι ότι στο admin του vivapayments στις πωλήσεις η συναλλαγή φαίνεται κανονικά. 

Αυτή την στιγμή στο ***.gr έχω αφήσει την διασύνδεση με το demo ώστε να μπορείτε να ελέγξετε και εσείς. Για αυτό τον λόγο παρακαλώ ενημερώστε με μόλις δείτε το τι συμβαίνει , ώστε να γυρίσει σε παραγωγή , καθώς είναι site που ήδη έχει πωλήσεις. 
Ευχαριστώ.

**Comment by dpnevmatikos** [comment]
Καλησπέρα,
Παρακαλώ επικοινωνήστε στο merchants@vivawallet.com παραθέτοντας στοιχεία του εμπόρου (αφμ ή merchant Id και source code) βάζοντας μέσα και το Link προς το παρον issue.

Ευχαριστούμε.
