### ISSUE TITLE
Original Credit Transaction (OCT) requests

### ISSUE THREAD

**Issue by GRANDX1** [VivaPayments/API#611]
We have gone through the document to understand the flow and requirement. We have some queries which we have listed below, kindly provide information on the below:

This is link which I have referred for the implementation: https://github.com/VivaPayments/API/wiki/Original-Credit-Transaction-(OCT)

Here I have Used MerchantId: ef49ab63-bd76-4474-b97d-a33e31e6d2c1
 	and Password: 4skuPJ		for the authentication

Note: these Merchant ID and Password (API key) are same, which is used on staging environment while implementing the VIVA Deposit.

Point 1:
could you please confirm that we should use the same Merchant Id and Password for the withdrawal request?

This is request example:
When we hit the  url : https://demo.vivapayments.com/api/transactions/11290?Amount=25.00&ServiceId=6

Method name: delete Authentication:
Username: merchantId - ef49ab63-bd76-4474-b97d-a33e31e6d2c1
Password: Api key - 4skuPJ Request parameter transactionId = 11290
Amount = 25.00

Response:
{
"Message": "The request is invalid."
}

Point 2:
We are getting the response as invalid request. Could you please let us know what we are messing in the request?

Attached below is the screenshot for your reference:

Point 3: Kindly provide us the IP address, if any which we can whitelist at our API level?
![image](https://user-images.githubusercontent.com/36725214/46188453-e0d89f80-c2f1-11e8-9c94-4a5db3565d47.png)

**Comment by GRANDX1** [comment]
@kostGX  please, help! Thank you in advance

**Comment by hsintichakis** [comment]
1. Yes, you use the same credentials as stated in the [relevant documentation](https://github.com/VivaPayments/API/wiki/Original-Credit-Transaction-(OCT))

2. The call needs the ID of the original transaction (type: GUID). In addition to that, the amount needs to be in cents. For example if you have 25€, you need to pass **2500**

3. You need to whitelist the following IPs [()](https://github.com/VivaPayments/API/wiki/Webhooks#webhook-url-verification) in case you need to use webhooks.

**Comment by GRANDX1** [comment]
Thank you! We will check

**Comment by GRANDX1** [comment]
Please, check further questions in the file
[VivaPayment-withdraw-query - 23-10-2018.pdf](https://github.com/VivaPayments/API/files/2528564/VivaPayment-withdraw-query.-.23-10-2018.pdf)

**Comment by kostGX** [comment]
@GRANDX1 hello, we see that on Production mode you have made successful OCTs.

Has this been solved?

**Comment by GRANDX1** [comment]
@kostGX no, we still have questions in the file attached
[VivaPayment-withdraw-query.-.23-10-2018.pdf](https://github.com/VivaPayments/API/files/2619768/VivaPayment-withdraw-query.-.23-10-2018.pdf)

**Comment by GRANDX1** [comment]
@kostGX We still have issues with OCT. Please, check the file attached
[VivaPaymentWithdrawQuery.docx](https://github.com/VivaPayments/API/files/2684902/VivaPaymentWithdrawQuery.docx)

**Comment by kostGX** [comment]
@GRANDX1 hello, I have enabled the OCT service for your demo merchant. Note: You need to specifically be granted access to this API call on Production as well, so please request permission by mailing support@vivapayments.com

**Comment by GRANDX1** [comment]
@kostGX  Could you please, double check OCT is enabled for our demo account?  Still does not work.

**Comment by GRANDX1** [comment]
@kostGX Could you please, double check OCT is enabled for our demo account? Still does not work.

**Comment by mikered7** [comment]
@kostGX  Did you requested permission at support@vivapayments.com aw @kostGX  advised?

**Comment by GRANDX1** [comment]
Yes, of course. For staging they recommended to apply to support on github while for live they will enable OCT. 

The problem is that for now is that OCT is not enabled for us on staging
