### ISSUE TITLE
Πρόβλημα με Native Checkout

### ISSUE THREAD

**Issue by mfonsos** [VivaPayments/API#612]
Καλησπέρα,

Αντιμετωπίζουμε ένα πρόβλημα στην υλοποίηση του Native Checkout.  Πρόκειται για custom υλοποίηση και όχι για κάποιο 3rd party plugin.

Στις περισσότερες συναλλαγές, έχουμε λάβει απάντηση ERROR CODE:403 ERROR TEXT:Source 1023 of merchant 14fdaea7-8c05-4d92-bca4-ad2a65e6057c supports only native checkout. Το εν λόγω source id είναι ρυθμισμένο για Native checkout. Έχουμε επικοινωνήσει και με το call center όπου μας επιβεβαίωσαν οτι έχει γίνει η απαραίτητη ρύθμιση για το Native Checkout και μας παρέπεμψαν στο GitHub.  Από την μεριά μας στέλνουμε, όσο μπορούμε να δούμε, όλα τα απαραίτητα πεδία και ρυθμίσεις.

Παρακαλώ για την βοήθεια σας  για την επίλυση.

Ευχαριστούμε

**Comment by mfonsos** [comment]
Καλησπέρα,

Αντιμετωπίζουμε σοβαρό πρόβλημα καθώς σχεδόν όλες οι προσπάθειες που γίνονται γυρίζουν ERROR CODE:403 και αποτρέπουν τους πελάτες να προβούν σε παραγγελία.

Παρακαλούμε για την άμεση ανταπόκριση σας.

Ευχαριστούμε.

**Comment by dpnevmatikos** [comment]
Καλησπέρα @mfonsos 
Μπορείτε να μας δείξετε τον κώδικα που χρησιμοποιείτε για να rendαρετε την Native Checkout ?

**Comment by mfonsos** [comment]
Καλησπέρα,

Στο Frontend για να κάνουμε generate token χρησιμοποιούμε αυτό το .js αρχείο
[viva.zip](https://github.com/VivaPayments/API/files/2438082/viva.zip)

Μόλις γίνει validate και επιστραφεί valid token κάνουμε post σε αυτο το url: https://www.vivapayments.com/api/orders/ με το εξής object:
body: {
                Amount: (amount * 100),
                AllowRecurring: 'false',
                RequestLang: 'en-US',
                SourceCode: 1023,
                Installments: '0'
            } 

Μόλις επιστρέψει valide orderCode κάνουμε post σε αυτό το url: 
https://www.vivapayments.com/api/transactions με το εξής object:

body: {
                            OrderCode: OrderCode,
                            SourceCode: 1023,
                            CreditCard: { Token: _card.token },
                            Installments: '0',
                            RequestLang: 'en-US'
                        } 
Στην συνέχεια επιστρέφει το ERROR TEXT:

ERROR TEXT:"Source 1023 of merchant 14fdaea7-8c05-4d92-bca4-ad2a65e6057c supports only native checkout"

Ευχαριστώ.

**Comment by dpnevmatikos** [comment]
@mfonsos Ο κώδικας που μου στείλατε πρέπει να χρησιμοποιηθεί και σε συνδιασμό με κάποια HTML για τα πεδία της Simple. Μπορείτε να μου στείλετε την HTML ?

**Comment by mfonsos** [comment]
> 
> 
> Ο κώδικας που χρησιμοποιούμε τον έχουμε πάρει απο το Native Checkout με τα ίδια data-vp οπού και χρησιμοποιούμε για να κάνουμε generate to token.
> `
> 
> ```
>                             <div class="form-group col-sm-12 col-xs-12"
>                                  ng-class="{'has-error':true}"
>                                  ng-if="formModelDisplay.showCreditCardFields">
> 
>                                 <input type="text" id="ccvv" class="form-control" placeholder="CVV" name="txtCVV" size="4" autocomplete="off" ng-model="formData.cvv" data-inputmask="'mask': '999'" data-vp="cvv" required="required"/>
>                                 <script type="text/javascript">
>                                     $("#ccvv").inputmask();
>                                 </script>
>                             </div>
> 
>                             <div ng-if="formModelDisplay.showCreditCardFields">
>                                 <div class="form-group col-sm-12 col-xs-12">
>                                     <span>ΗΜ. ΛΗΞΗΣ (MM/YYYY)</span>
>                                 </div>
>                                 <div class="form-group col-sm-7 col-xs-7" ng-class="{'has-error':true}">
>                                     <input type="text" id="creditMonth" class="form-control" placeholder="ΜΗΝΑΣ" data-inputmask="'mask': '99'" maxlength="2" minlength="2" name="txtMonth" autocomplete="off" ng-model="formData.month" data-vp="month" required="required"/>
>                                 </div>
>                                 <div class="form-group col-sm-2 col-xs-2"></div>
>                                 <div class="form-group col-sm-6 col-xs-6" ng-class="{'has-error':true}">
>                                     <input type="text" id="creditYear"  class="form-control" placeholder="ΕΤΟΣ" data-inputmask="'mask': '9999'" maxlength="4" minlength="4" name="txtYear" autocomplete="off" ng-model="formData.year" data-vp="year" required="required"/>
>                                 </div>
>                                 <script type="text/javascript">
>                                     $("#creditMonth").inputmask();
>                                     $("#creditYear").inputmask();
>                                 </script>
> 
>                             </div>
>                         
>                         </div>
>                     </div>`
> ```
> 
> Σας παραθέτουμε και την φόρμα που ζητήσατε.

[html_file.zip](https://github.com/VivaPayments/API/files/2438300/html_file.zip)

**Comment by mfonsos** [comment]
Το πρόβλημα συνεχίζεται καθημερινός με τουλάχιστον ένα Error Code 403 οπου ο πελάτης στην συνέχεια τηλεφωνεί στο Call Center για να ενημερώσει οτι δεν μπόρεσε να προβεί σε αγορά μέσω του Website.
