### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by PanosMoosend** [VivaPayments/API#613]
Καλησπέρα

Έχουμε business account viva wallet και τις τελευταίες μέρες όταν πάμε να κάνουμε απο το μενού "πωλήσεις" επανάληψη μιας παλαιότερης χρέωσης (ώστε να ξαναχρεώσουμε έναν πελάτη μας) σε κάποιες περιπτώσεις μας βγάζει ένα άγνωστο error 502. Δεν το κάνει σε όλους τους πελάτες. Κάποιες επαναληπτικές περνάνε κανονικά. Επισυνάπτουμε print screen του προβλήματος. Παρακαλούμε να μπρεί μια προτεραιότητα γιατί η συνδρομή μας είναι μηνιαία και δεν μπορούμε να χρεώσουμε τους πελάτες μας. 

![502 01](https://user-images.githubusercontent.com/43740861/46279513-f0feb200-c571-11e8-9bdc-101b5b9d8103.jpg)
![502 02](https://user-images.githubusercontent.com/43740861/46279514-f1974880-c571-11e8-8e2f-4c73d536e041.jpg)

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming this is no longer a problem, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
