### ISSUE TITLE
Token decryption failed for cross-domain REST API

### ISSUE THREAD

**Issue by asamaras11** [VivaPayments/API#615]
Καλησπέρα σας,

είμαι ο developer μιας online PHP εφαρμογής η οποία έχει ήδη integration με την Viva με Native Checkout και μπορώ να πω οτι δουλεύει άψογα.
Πρόσφατα, προχωρήσαμε σε redesign της εφαρμογής η οποία πλέον αποτελείται από PHP backend και Angular frontend. Ο server τρέχει στο π.χ. domain.gr και το angular είναι στο app.domain.gr. Προφανώς, το angular κάνει calls στον server για να πάρει data.
Οι χρήστες μπορούν να κάνουν πληρωμή από 2 σημεία: από μία plain PHP page που βρίσκεται στο domain.gr και από ένα angular page που βρίσκεται στο app.domain.gr

Έχω κάνει setup τον test account στο demo.vivapayments.gr και έχω βάλει στην πηγή πληρωμών το domain.gr.
Η πληρωμή από την PHP σελίδα περνάει κανονικά ενώ η πληρωμή από την angular page κόβεται με το error: 
The following error occured: Token decryption failed, token does not belong to merchant 1d8712a7-c9cf-4b5e-b930-1a630adae194

Φαντάζομαι οτι κόβεται επειδή στην δεύτερη περίπτωση έχουμε cross-domain request?

Θα ήθελα την βοήθειά σας παρακαλώ καθώς σε 1 βδομάδα θα βγούμε live και θα θέλαμε να λυθεί όσο πιο γρήγορα μπορούμε.

Ευχαριστώ!

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. I think you're right in your assumption. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
