### ISSUE TITLE
Mobile API - Production  Card tokenization

### ISSUE THREAD

**Issue by Alexookah** [VivaPayments/API#617]
Το Card tokenization δουλεύει κανονικά στο Demo.
στο Production όμως δεν δουλεύει!!! επιστρέφει error code 404.

λείπει το Authorization στο request:
- (NSMutableURLRequest *)createCardRequest

βάζοντας την παρακάτω γραμμή δουλεύει κανονικά μετά
[request setValue:[self authenticationHeaderForUsername:self.merchantID password:self.apiKey]
   forHTTPHeaderField:@"Authorization"];

να κάνω PULL request?

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
