### ISSUE TITLE
Database writes the order but order does not appear in opencart dashboard nor email

### ISSUE THREAD

**Issue by PuzzlePiece** [VivaPayments/API#618]
We use 1.5.6.4 opencart and vivawallet redirect method, dunno the exact module.
The client pays normally and we can see the money in vivawallet enviroment, also database shows the order but in the backoffice in opencart we can only see the order in missing orders and so we dont receive email for the order either. 

Any suggestions?

**Comment by VivaWalletSupport** [comment]
I would suggest to try the OpenCart 1.5 extension from https://github.com/VivaPayments/API/tree/master/Plugins/opencart

Follow the instructions from the readme text, report back in case the problem persists or close this ticket if the problem has been solved.
