### ISSUE TITLE
ERROR CODE 403 mercant supports only native checkout

### ISSUE THREAD

**Issue by mfonsos** [VivaPayments/API#619]
Καλησπέρα,

Ανοίγουμε καινούργιο αίτημα με το ίδιο πρόβλημα καθώς δεν έχουμε επίλυση του προβλήματος.

Πρόβλημα στην υλοποίηση του Native Checkout. Πρόκειται για custom υλοποίηση και όχι για κάποιο 3rd party plugin.

Στις περισσότερες συναλλαγές, έχουμε λάβει απάντηση ERROR CODE:403 ERROR TEXT:Source 1023 of merchant 14fdaea7-8c05-4d92-bca4-ad2a65e6057c supports only native checkout. Το εν λόγω source id είναι ρυθμισμένο για Native checkout. Έχουμε επικοινωνήσει και με το call center όπου μας επιβεβαίωσαν οτι έχει γίνει η απαραίτητη ρύθμιση για το Native Checkout και μας παρέπεμψαν στο GitHub. Από την μεριά μας στέλνουμε, όσο μπορούμε να δούμε, όλα τα απαραίτητα πεδία και ρυθμίσεις.

Παρακαλώ για την βοήθεια σας για την επίλυση.

Ευχαριστούμε

**Comment by dpnevmatikos** [comment]
Καλησπέρα,
Εχετε άκολουθήσει τα βήματα όπως αναφέρονται εδώ ? 
https://github.com/VivaPayments/API/wiki/Native-Checkout

**Comment by mfonsos** [comment]
Καλημέρα,

Η διαδικασία που γίνεται :

   - Ο χρήστης βάζει τα στοιχεία του οπου λαμβάνει το Token μέσω του Native
   Checkout Form.
   - Στην συνέχεια αποστέλουμε το Token οπου μας γυρίζετε το Order Code.
   - Τέλος postaroume με το Order Code όπου το Transaction γίνεται fail
   (όχι πάντα)

P.S. στην περίπτωση που ξανακάνουμε την ίδια διαδικασία εφόσον έχει
επιστρέψει Error supports only native checkou...Η διαδικασία ολοκληρώνεται
επιτυχώς.

Αν χρειάζεστε αντίστοιχα logs για να τα συγκρίνετε με τα δικά σας έχουμε
τουλάχιστον ένα με δύο την ημέρα απο τις 21/09/2018.

Σας παραθέτω και το Error απο τα logs μας.

ERROR CODE:403
ERROR TEXT:"Source 7986 of merchant 14fdaea7-8c05-4d92-bca4-ad2a65e6057c
supports only native checkout"
------

{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ErrorCode":403,"ErrorText":"Source
7986 of merchant 14fdaea7-8c05-4d92-bca4-ad2a65e6057c supports only native
checkout","TimeStamp":"2018-10-25T13:06:55.0920866+03:00","CorrelationId":null,"EventId":0,"Success":false}

Με εκτίμηση,
Φόνσος Ματθαίος.

**Comment by dpnevmatikos** [comment]
Καλημέρα @mfonsos 
Παρατηρώ οτι υπάρχει διαφορά στους κωδικούς των πηγών που έχεις χρησιμοποιήσει. Στη μια περίπτωση είναι ο 7986 στην άλλη η 1023. Μπορούμε να δοκιμάσουμε μόνο με μια συγκεκριμένη πηγή? 
Επίσης: το πρόβλημα λες οτι δεν συμβαίνει κάθε φορά. Αυτό σημαίνει οτι κάποιες φορές η συναλλαγή ολοκληρώνεται με επιτυχία και κάποιες άλλες όχι?

Αν ολοκληρώνεται έστω και μια συναλλαγή τότε δεν υπαρχει κάτι που να μπορουμε να κάνουμε από πλευράς δικής μας.

**Comment by mfonsos** [comment]
Φτιάξαμε και δεύτερη πηγή για να δοκιμάσουμε εναλλακτικά μήπως έφταιγε κάτι
στην πρώτη, και στις 2 πηγές το πρόβλημα παρουσιάζετε.

Οι δοκιμές που κάναμε στο demo account και συνεχίζουμε και κάνουμε, δεν
υπάρχει κανένα πρόβλημα στην ολοκλήρωση όσες φορές και να δοκιμάσουμε. Το
πρόβλημα
υπάρχει μόνο στο production οπου με τον ίδιο ακριβώς κώδικα επιστρέφει το
Native Checkout Error.

Επομένος μου λές ότι το Error Code που μου επιστρέφεται το οποίο είναι πολύ
συγκεκριμένο (ενώ έχουμε κάνει check το Native Checkout στο account μας)
φταίμε εμείς και η Viva δεν μπορεί να κάνει κάτι γι'αυτό και μου προτείνεις
να αλλάξω Πάροχο ώς λύση?
