### ISSUE TITLE
epipla24.gr με πεταει σε 404

### ISSUE THREAD

**Issue by pcinfogr** [VivaPayments/API#62]
καλησπέρα
ειμαι ο τεχνικος της εταιρειας epipla24.gr που έχει ενσωματωμένοaddon gia cs-cart για vivapayments
κ τελειως ξανφνικα τελευταια με το που γινονται οι πααγγλίες χρηστών τους πετάει σε 404 σελίδα (ενδεχομενως λαθος success url) ενώ παράλληλα η χρέωση γίνεται κανονικα κ οι πααγγελίες μπαίνουν σε ατελή μορφή που δεν φαινονται στο διαχειριστικό έυκολα.

παρακαλω να λυθει άμεσα ευχαριστω
κωστας ηλιάδης

**Comment by pcinfogr** [comment]
παρακαλώ να λυθέι άμεσα

ο πελάτης δέχεται παραγγελίες ακόμη κ τώρα.

η εξυπηρέτηση πελατών της viva με παρέπεμψε σε αυτό εδώ το post se github που δεν ξερω καν αν ειναι ζωντανη τεχνική υποστήριξη! 

παρακαλώ να λύσουμε το θέμα άμεσα

ευχαριστω
περιμένω απα΄ντηση

**Comment by pcinfogr** [comment]
συγνωμη! αυτο ειναι η τεχνική υποστήριξη της vivapayments????αυτο ειναι το μοναδικο μεσον επικοινωνίας για ενα προβλημα το οποίο είναι άμεσο κ αφορά πληρωμές που ήδη ισχύουν κ υπα΄ρχει άμεσο πρόβλημα με τις πληρωμες?! 
αυτο ειναι που δαιφημιζει ως ολοκληρωμενο συστημα πληρωμων?!!

**Comment by dmihos** [comment]
Καλησπέρα σας

Βλέπουμε 1 συναλλαγή σήμερα στο λογαριασμό σας.
Η πηγή που αντιστοιχεί σ'αυτή τη συναλλαγή, έχει ένα url που πράγματι δίνει 404.
Δε φαίνεται να υπάρχει κάποιο πρόβλημα στο λογαριασμό σας.
Θα πρέπει να ελέγξετε στο site σας αυτό το url, κι αν χρειάζεται να ενημερώσετε αντίστοιχα την πηγή.

**Comment by pcinfogr** [comment]
οκ
απ οτι ειδα εχει τελειως δαιφρετικα url
κ δειχνει στο τελος το hellaspay...!
ισχυει κατι τετοιο?

οπως κ να χει μπορειτε να τσεκαρετε κ ν εγκρινετε διοτ αλλαξα τα url στις πηγες αν εινια να δουμε αν δουλευει σωστα?
περιμενω απαντηση ευχαριστω

**Comment by pcinfogr** [comment]
επανεφερα τα λινκς
θελω μια αμεση εξυπηρετηση για να λειτουργηση η ιστοσελιδα το πρωι παρακαλω!

υπαρχει κανεις?!

**Comment by pcinfogr** [comment]
τωρα βγαζει access denied....

**Comment by pcinfogr** [comment]
ολο το τεχνικο τμημα για υπνο?

**Comment by deliverymanager** [comment]
Δεν ειμαι απο το τεχνικο τμημα απλως κι εγω οπως και πολλοι αλλοι που παρακολουθουμε τον πηγαιο κωδικα της Viva λαμβανουμε τις ειδοποιησεις σας.
Σιγουρα δεν απευθυνεται το issue tracking του πηγαιου κωδικα της Viva στο οποιο βρισκομαστε σε προβληματα εγκαταστασης ενος  plugin η addon το οποιο στηριζεται στο συστημα της Viva.

Ωστοσο, νοιωθωντας την αγωνια σας για να εξυπηρετησετε τον πελατη σας, πιστευω το πιο σωστο ειναι να απευθυνθειτε στην εταιρια η οποια σας πουλησε το addon το οποιο συνδεεται με τη Viva Payments.
Υπαρχει πληθωρα τετοιων plugins στη αγορα καποια καλα καποια οχι τοσο. Σιγουρα δεν μπορουμε να περιμενουμε να υποστηριζει τη σωστη λειτουργια τους η Viva γιατι πολυ απλα δεν τα εχει δηνιουργησει αυτη.

Σχετικα με το τεχνικο θεμα σας.
Απο οτι ειπατε το success url το οποιο εχετε δηλωσει στο Πανελ της viva πεταει 404. Το url αυτο ειναι δικο σας. Οποτε εσεις ελεγχετε τι ακριβως θα εμφανισει.
Ελπιζω να αντιλαμβανεστε τι λεω και τα λεω με διαθεση να σας βοηθησω καπως. 

Φιλικα,
Ανεστης

**Comment by pcinfogr** [comment]
oxi ασε τ 404

πλεον μου βγαζει access denied.

το αλλαξα το addon εβαλα άλλο

κ το οποιο το εχω ξαναδοκιμασει

αλλα μου εβγαζε κ παλιτοερα στο αλλο καταστημα access denied κ το διορθωσατε απο εκει.

ποτε πρεπει να περιμενω να μου δωθει access...

**Comment by dmihos** [comment]
Αγαπητέ Κώστα Ηλιάδη καλησπέρα

Όπως σωστά ειπώθηκε πιο πάνω, το παρόν GitHub Repo χρησιμοποιείται σαν issue tracking για τον προσφερόμενο από εμάς κώδικα που κάνει access το API μας. Επιπλέον, περιλαμβάνει κάποια wiki pages με οδηγούς που βοηθούν στη διασύνδεση με τα συστήματα των εμπόρων.
Για υποστήριξη σε παραγωγικά περιβάλλοντα θα πρέπει να απευθύνεστε στο merchants@vivawallet.com. Προφανώς υπήρξε κάποια παρεξήγηση με το support τμήμα μας, το οποίο προφανώς δεν κατάλαβε σωστά το request, ζητώ συγγνώμη γι'αυτό.

Για το θέμα που αντιμετωπίζετε, παρακαλώ σημειώστε τα παρακάτω:
Το μήνυμα 'Access denied' το δίνει το site epipla24.gr 
Δυστυχώς δε μπορούμε να γνωρίζουμε το λόγο, θα πρέπει να διερευνηθεί από τον τεχνικό του site ή την εταιρία που ανέπτυξε το 3rd party plugin που χρησιμοποιείτε.
Αν πρόκειται για display κάποιου error που παίρνετε από το API μας, δώστε μας κάποιες λεπτομέρειες της κλήσης στο merchants@vivawallet.com να το διερευνήσουμε.
Πάντως ο λογαριασμός σας είναι ενεργός, όπως και όλες οι πηγές σας.

**Comment by pcinfogr** [comment]
μα το ιδιο ακριβως plugin δουλευει σωστα κ σε άλλο παρόμοι site
δε γινεται το ενα να μη λειτουργει κ το αλλο να λειτουργει σωστα!
εκανα χτες αλλαγές στα url κ μηπως μπερδευτηκαν οι πηγες κ θελανε να ενημερωσουν οτι αλλάχθηκαν!

δειτε το λιγο!
δε μπορει να μου βγαζει access denied τη στιγμη που μπαινει σε περιβαλλον vivapayments κ να φταιει το site!

**Comment by pcinfogr** [comment]
άλλαξα addon με άλλο κώδικα
το οποιο το χρησιμοποίησα κ σε άλλη ιστοσελίδα που λειτουργει κανονικα.
πλεον δε υπαρχει το 404
δεν με βαζει ΚΑΝ στην συναλλαγή για viva

**Comment by pcinfogr** [comment]
?

**Comment by dmihos** [comment]
Λυπάμαι, δε φαίνεται κάποιο πρόβλημα με το λογαριασμό σας.
Εκτελέσαμε επιτυχώς CreateOrder με τις web πηγές που έχετε καταχωρήσει, και η checkout οθόνη εμφανίζεται σωστά.
Αν θέλετε, στείλτε στο merchants@vivawallet.com τα στοιχεία που χρησιμοποιείτε για τη διασύνδεση (MerchantId, ApiKey, SourceCode) για περαιτέρω έλεγχο.

Το παρόν issue, όπως και τα υπόλοιπα που έχετε ανοίξει, θα πρέπει να κλείσουν, καθώς δεν αφορούν γενικά προβλήματα integration για public reference.

Ευχαριστώ για την κατανόηση
