### ISSUE TITLE
Πρόβλημα ολοκλήρωσης πληρωμής με Opencart (3.0.2.0)

### ISSUE THREAD

**Issue by pakagyla** [VivaPayments/API#620]
Καλησπέρα, 

Είναι η δεύτερη φορά που προσπαθούμε. 
Εχουμε προσθέσει το module ,έχουμε μιλήσει με την εταιρία που αγοράσαμε το module και μας λέει να μιλήσουμε μαζί σας ή να δουμε τις ρυθμίσεις. 
Κατα το checkout , γινετε το redirect στο viva wallet και βαζουμε τα στοιχεία κάρτας του πελάτη. 
Κάνει το request και απαντάει με ένα Error. 
Μπορειτε να το δείτε μήπως δεν έχουμε βάλει σωστα τις ρυθμίσεις και τα στοιχεία μας στο module ή μήπως οφείλετε σε εσάς?
Ο λογαριασμος μας είναι εταιρικός και ταυτοποιημένος.

**Comment by pakagyla** [comment]
Τι θα γίνει , θα μας βοηθήσετε ποτέ? Δεν μου έχει ξανατύχει τέτοια αντιμετώπιση είδικά στο χώρο των επιχειρήσεων.

**Comment by VivaWalletSupport** [comment]
Hello, try the supported OpenCart 3 extension from https://github.com/VivaPayments/API/tree/master/Plugins/opencart and post back in case the problem continues.
