### ISSUE TITLE
viva wallet σε opencart 2.3.0.2

### ISSUE THREAD

**Issue by webprestige** [VivaPayments/API#621]
Ξερει κανεις γιατι στο admin του opencart εχω δυο viva  modules τα οποια οταν τα ενεργοποιω στην αρχη δεν εκανε redirection και τωρα βγαζει fatal error? στο checkout?

**Comment by VivaWalletSupport** [comment]
Hello, what extension did you install for Viva Payments?

**Comment by VivaWalletSupport** [comment]
Hello webprestige, did you manage to resolve the issue?
