### ISSUE TITLE
Error Store Not Found (Error Payment Redirection)

### ISSUE THREAD

**Issue by BalinisCaprets** [VivaPayments/API#622]
Γεια σας, έχω ακολουθήσει όλες τις ενέργειες που μου υποδείξατε καθώς και την διαδικασία ταυτοποίησης επαγγελματικού λογαριασμού και συνεχίζω να αντιμετωπίζω το ίδιο πρόβλημα, όταν επιλέγω να κάνω πληρωμή με Viva Wallet Payments στο redirecting μου εμφανίζει το σφάλμα "STORE NOT FOUND".

**Comment by VivaWalletSupport** [comment]
Hello, are you using an e-commerce platform and a specific plugin to connect?

**Comment by dmihos** [comment]
Hi BalinisCaprets
This looks like an error related to Shopify Integration.
Have you followed [this guide](https://github.com/VivaPayments/API/wiki/Shopify-Integration)?

**Comment by BalinisCaprets** [comment]
Hello thanks for your instresting, im using Shopify. ---- On Sun, 21 Oct 2018 08:00:08 +0300 Tom van der Veer <notifications@github.com> wrote ---- Hello, are you using an e-commerce platform and a specific plugin to connect? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by BalinisCaprets** [comment]
Hello thanks for your message i already followed all of those instructions. ---- On Mon, 22 Oct 2018 10:02:18 +0300 dmihos <notifications@github.com> wrote ---- Hi BalinisCaprets This looks like an error related to Shopify Integration. Have you followed this guide? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by dmihos** [comment]
It seems you probably missed some steps.
Did you, specifically, fill in [this](http://landing.vivawallet.com/shopify) form?
Were you given back, by email, the store token required?
If not, what store token did you specify in the shopify gateway activation screen?

**Comment by erimpapova** [comment]
I have the same issue. Nothing went wrong during installation or whatever...
What should I do?
