### ISSUE TITLE
Issue with VIVA and Shopify | Πρόβλημα με Shopify and Viva 

### ISSUE THREAD

**Issue by spiros89** [VivaPayments/API#623]
Προσπάθησα να εγκαταστήσω το VIVA στο Shopify. Ωστόσο μέχρι στιγμής πρώτον δεν έχω καταφέρει να δω πως θα το κάνω να λειτουργήσει ως Direct Payment Method δηλαδή να μην χρειάζεται να φύγει κάποιος από την σελίδα μου ώστε να ολοκληρώσει την πληρωμή. 

Δεύτερον ακολουθώντας τις μοναδικές οδηγίες που βρήκα https://github.com/VivaPayments/API/wiki/Shopify-Integration Τελικά μου έκανε μόνο redirect method η οποία κιόλας όταν έβαλα τα στοιχεία της κάρτας μου έβγαλε "Error - Generic Error". Έχω βάλει το MerchantID και Store Token που είχαν σταλεί αλλά και πάλι δεν τα κατάφερα να έχω κάτι λειτουργικό. 

Τι ενέργειες μπορώ να κάνω για να το λύσω;  

![image](https://user-images.githubusercontent.com/44294262/47219642-079d6980-d3b8-11e8-81fd-3b228d8f2082.png)

**Comment by spiros89** [comment]
I tried to integrate Viva Payment on my Shopify store. Even I tried a lot, I could not install it as a direct payment method. On the other words, someone completes the payment on my website and don't leave for viva payment websites. 

Secondly after the instructions for [Shopify Integration ](https://github.com/VivaPayments/API/wiki/Shopify-Integration)
it installed only the redirect method which is not working! I did the checkout process and after my choice to "Viva Wallet Payment," it redirected me to viva wallets pages to complete my credit card details. After the details, it showed me "generic error". I have already completed the integration with MerchantID and Store token that emailed me but again is still not functional. 

Could you help me?

**Comment by dmihos** [comment]
Hi Spiros89
As mentioned in the integration guide you have read, the only checkout option available for Shopify is Redirect Checkout. 
Regarding the 'Generic Error', you've most probably changed the 'Checkout' option of your 'Shopify' source to Native. Please switch it back to Redirect.
Please let us know if you are still having issues.
