### ISSUE TITLE
Πρόβλημα με την εισαγωγή του αριθμού κάρτας στο VivaPayments Gateway του woocommerce

### ISSUE THREAD

**Issue by npapant** [VivaPayments/API#624]
Χαίρετε!
το πρόβλημα είναι ότι όταν μεταβεί ο πελάτης στο περιβάλλον της Viva για να πληρώσει και εισάγει λανθασμένο αριθμό κάρτας δεν γίνεται έλεγχος επιτόπου και δεν εμφανίζει σχετικό μήνυμα, αντίθετα αφήνει τον πελάτη να συνεχίσει, να βάλει δηλ. τα υπόλοιπα στοιχεία της κάρτας (στα οποία κάνει τον σωστό έλεγχο σε αντίθεση με τον αριθμό κάρτας) και το ποσό και στη συνέχεια το woocommerce θεωρεί τη παραγγελία με εκκρεμή πληρωμή.

**Comment by VivaWalletSupport** [comment]
Hello, a pending order status is a good indication for the merchant that the transaction failed or should be further investigated.

**Comment by npapant** [comment]
Yes, but the client should be instantly informed that his payment has failured!

**Comment by VivaWalletSupport** [comment]
What plugin and method are you using for connecting with Viva Payments?

**Comment by npapant** [comment]
I am using the "VivaPayments Gateway" from papaki woocommerce. 
I am using the same url for both transactions (success and failure) "domain.gr/wc-api/WC_Papaki_Vivapayments_Gateway".

**Comment by VivaWalletSupport** [comment]
I would suggest to review their documentation and open a support ticket there in case of a problem. https://wordpress.org/plugins/woo-payment-gateway-for-vivapayments/

**Comment by VivaWalletSupport** [comment]
Hello npapant, please close this issue in case it has been resolved, otherwise let me know.
