### ISSUE TITLE
Prestashop rounding issue

### ISSUE THREAD

**Issue by alkalline** [VivaPayments/API#625]
Greetings,
we had an occurrence today when an order failed with error "Warning 279,99 € paid instead of 280,00 €".

There seems to be an issue with the way Prestashop rounds the prices before sending the order to be processed. We had this issue last year with PayPal but they figured it out (they tolerate small differences according to https://github.com/iqtecommerce/Prestashop-1.6-Paypal-3.11.1-rounding-decimal-places-problem-fix). Any chance to look into it? It's a shame to lose clients for 0,01 euro!

Thanks in advance.

**Comment by VivaWalletSupport** [comment]
Hello, what module is used to connect with Viva Payments?

**Comment by VivaWalletSupport** [comment]
Unlike Paypal where the problem there was caused by calculating the sum of product prices and rounding them, this module uses the cart order total in cents. Also unlike as with Paypal it does not use its own function to check the amount after the transaction but is uses the Prestashops default PaymentModule.php file (function validateOrder). You might find following link usefull https://www.prestashop.com/forums/topic/291300-disable-round-prices/

**Comment by alkalline** [comment]
Yes, but it seems that Presta asked for 280e and the client only tried to pay for 279,99e. This kind of error wouldn't happen if there was just one value passed from PS and that's that. So my guess is that there IS some calculation somewhere that makes errors like this happen.

If you take the cart value as is, then the error may be introduced at another point. In our case, this is a multicurrency shop. The customer was from UK, maybe he tried to buy using GBP and the value was converted in Euros. Maybe you use different exchange rates and they produce this difference. If you use the rates PS uses, are you also using the same function to convert currencies? Maybe this is where the rounding error happens.

Or maybe Prestashop uses a different rounding when displaying values and another one when actually processes orders. In this case this is all PS's fault, but I had to bring the issue into your attention.

Finally, I understand that the idea of "small difference toleration" is not a way to fix this error, but rather mask it. But in *most cases* a difference of 1 cent per item *should not* be a deal breaker. If you catch this error and retry with a fault tolerance of 0,01e / item it may still be worth it. 

Your thoughts?

**Comment by VivaWalletSupport** [comment]
For currency rate adjustment, the module uses the rates as set in Prestashop. You would have to edit the function validateOrder in Prestashop (classes PaymentModule.php) to allow a tolorance.
