### ISSUE TITLE
WooCommerce Viva Installments not appearing

### ISSUE THREAD

**Issue by Alina-chan** [VivaPayments/API#626]
Καλησπέρα,
Έχω ένα WooCommerce eshop στο οποίο έχω εγκαταστήσει το "Viva Payments – Viva Wallet WooCommerce Payment Gateway" plugin. Παράλληλα έχω δημιουργήσει ένα test account στο demo.vivapayments και ένα συγκεκριμένο wallet για την ιστοσελίδα μου. 

Στις ρυθμίσεις του plugin έχω βάλει σωστά το API, merchant ID, code ID etc και τον αριθμό των δόσεων στις 3. Αυτή τη στιγμή λειτουργώ με redirect και όχι με native checkout. 

Παρόλαυτά, κατά το redirect στο περιβάλλον της viva, δεν μου εμφανίζει καμία επιλογή για δόσεις, ανταυτού χρεώνει όλο το ποσό σαν να μην έχω ενεργοποιήσει τη λειτουργία των δόσεων. Έχω παραλείψει κάτι; Πώς μου προτείνετε να προχωρήσω;

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
