### ISSUE TITLE
Normal request works, demo doesn't

### ISSUE THREAD

**Issue by vaspervnp** [VivaPayments/API#627]
I have setup a woocommerce site with Viva plugin. When in Demo mode, the ?ref is empty and I get a bad request. When in production mode, it works ok and I get to your site. The installation is updated to the latest scripts.

I wan't to test the whole procedure, but I can't.

**Comment by VivaWalletSupport** [comment]
Hello, what plugin is used for the connection?

**Comment by imalliar** [comment]
Yes, I've seen the same error too. The plugin is from enartia. What is the error message? Wrong merchant id or API isn't working?

**Comment by kostGX** [comment]
@vaspervnp please make sure you're using a secure protocol for communicating with our servers (Not SSL or TLS v1). We're deprecating it soon so we've disabled support for it on the Demo environment. 

Production still tolerates it until migration is over.

**Comment by solisoft** [comment]
On my side demo always redirect to my error page with card 4111 1111 1111 1111 CVV 111 and a future expiration date ... 
Can we have a reason why it is rejected ?

**Comment by VivaWalletSupport** [comment]
Hello verify you are connected to the demo environment of Viva payments and that the transaction amount is more then the minimum amount.

**Comment by solisoft** [comment]
Yes it was connected to demo env ... I'm gonna test with prod env now

**Comment by VivaWalletSupport** [comment]
Hello solisoft, please close this issue in case it has been resolved, otherwise let me know.

**Comment by solisoft** [comment]
Well ... I can't ... I'm just able to add additional comments ...

**Comment by webitbz** [comment]
Thank you for the reply solisoft.
Hello vaspervnp, please close this issue in case it has been resolved, otherwise let me know.

**Comment by VivaWalletSupport** [comment]
Thank you for the reply solisoft.
Hello vaspervnp, please close this issue in case it has been resolved, otherwise let me know.
