### ISSUE TITLE
Προβλημα συνδεσης shopify με viva wallet  !!!!!

### ISSUE THREAD

**Issue by djgogos** [VivaPayments/API#629]
Καλησπερα

εχω κανει ολες τις απαραιτητες ενεργειες για την συνδεση του eshop μου με το shopify.

στο redirect αυτη την στιγμη λεει "store not found"

τι αλλο πρεπει να κανω για να συνδεθουνε ???

**Comment by dmihos** [comment]
Πρόκειται για demo (test mode);
Αν ναι, έχετε κάνει [εγγραφή στο demo περιβάλλον](
https://demo.vivapayments.com/en-us/signup) και [έχετε ζητήσει σχετικό demo token](https://landing.vivawallet.com/shopify);

**Comment by djgogos** [comment]
καλημερα

τωρα τοσα που εχοω κανει εχω μπερδευτει

πως ζηταω το κανονικο περιβαλλον και το τοκεν ??

**Comment by dmihos** [comment]
Αν έχετε επικοινωνία με την υποστήριξη, ζητείστε τους παραγωγικό token.
Διαφορετικά, αν θέλετε, συμπληρώστε τη φόρμα εκ νέου.

**Comment by djgogos** [comment]
ευχαριστω πολυ  :)
