### ISSUE TITLE
συγνωμη! αυτο ειναι η τεχνική υποστήριξη της vivapayments?????????

### ISSUE THREAD

**Issue by pcinfogr** [VivaPayments/API#63]
συγνωμη! αυτο ειναι η τεχνική υποστήριξη της vivapayments????αυτο ειναι το μοναδικο μεσον επικοινωνίας για ενα προβλημα το οποίο είναι άμεσο κ αφορά πληρωμές που ήδη ισχύουν κ υπα΄ρχει άμεσο πρόβλημα με τις πληρωμες?! 
αυτο ειναι που δαιφημιζει ως ολοκληρωμενο συστημα πληρωμων?!!

**Comment by nikolasd** [comment]
Όχι, αυτό είναι τεχνικά κείμενα και δείγμα κώδικα, ώστε κάποιος προγραμματιστής να δημιουργήσει μία διασύνδεση με το σύστημα πληρωμών της VIVA. Όλο αυτό, απευθύνεται σε εξειδικευμένους χρήστες και σε καμία περίπτωση δεν αποτελεί "τεχνική υποστήριξη" προς τελικό πελάτη. Για αυτό θα σας συμβούλευα να απευθυνθείτε είτε σε αυτόν που σας έφτιαξε τη διασύνδεση ή που σας πούλησε τη δική του υλοποίηση ή στην VIVA, αύριο το πρωί, στο τηλεφωνικό τους κέντρο. Αυτό που στελνετε τα μηνύματα σαν email, ονομάζετε issues tracking ενός versioning συστήματος που ονομάζετε git και παρεχετε από την εταιρεία github.
Και εγώ είμαι ένας από τους εξειδικευμένους χρήστες που ευγνωμονει τη VIVA που έφτιαξε επιτέλους ένα εύκολο σύστημα online εκκαθάρισης πιστωτικών καρτών, ανεξάρτητο από τις τράπεζες και Ελληνικό.
Μην περιμένετε απάντηση τέτοια ώρα. Και εγώ που απαντώ, είναι γιατί με ξυπνησαν τα notifications από τα απανωτά σας μηνύματα.

Καλό βράδυ και καλό μουράγιο.

Υ.Γ. Ποτέ δεν βγάζουμε ένα σύστημα live χωρίς τα απαραίτητα tests και backup plan.

**Comment by pcinfogr** [comment]
εγω ειμαι ο τεχνικος για την υποποίηση του συγκεκριμενου πελατη!

κ εμχρι τωρα λειτουργουσε κανονικα ή ετσι πιστεύαμε τουλαχιστον!!!
μεχρι που διαπιστωσε ο πελατης μου οτι στις αγορες του τον στελνει σε 404!!!

ΟΛΟΙ οσοι εχουν βαλει viva μεχρι τωρα το εχουν μετανιωσει...κ το αφηνουλ λογω κοστους που αγορασαν το addon!!

παραλληλα 2 πελατες μου μου ειπαν οτι φασιστικα η iva αλλαξε πολιτικη στις κρατησεις σε ενα πελατη που εκανε τζιρους στο eshop του πανω απο 5000 ευρω τη μερα...κ ο οποιος φυσικα εφυγε χωρις δευτερη σκεψη κ πηγε σε πειραιως...
καμια σχεση!
κ καμια επαφη γενικτοερα με το θεμα εξυπηρετησης...οταν απο το τηλεφωνο με στελνουν στο github!!! το οποιο προσωπικα το θεωρω πολυ δυνατη πλατφόρμα αλλα ΟΧΙ Κ ΓΙΑ τεχνικη υπστηριξη μιας ετιαρειας που διαφημιζεται ως ιδρυμα πληρωμων!!
γτ οι πληρωμες γινονται οπως ξερετε 24 ωρες!!!
κ καποιοι πελατες μπορει να θελουν να κανουν αγορες!
