### ISSUE TITLE
Viva gateway fails to complete transaction

### ISSUE THREAD

**Issue by Alina-chan** [VivaPayments/API#630]
Hello, I'm using the official Viva payment plugin for WordPress and currently working on a demo viva account. I have set up the merchant, code id, api key correctly at the woocommerce settings and set the URLs on my demo viva wallet as following:
Success: https://domain.com/wc-api/wc_vivawallet&vivawallet=success
Failure: https://domain.com/wc-api/wc_vivawallet&vivawallet=fail

I also enabled the legacy API for woocommerce, however I always get a failure response. 
On the error log, I see some PHP notices such as: 
- PHP Notice:  Constant CURL_SSLVERSION_TLSv1 already defined in /home/domain/public_html/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php on line 320
- PHP Notice:  Undefined variable: session in /home/domain/public_html/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php on line 321
- PHP Warning:  curl_setopt() expects parameter 1 to be resource, null given in /home/domain/public_html/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php on line 321

What am I doing wrong? Can't find a way to make it work.

**Comment by VivaWalletSupport** [comment]
Hello, are you using following plugin?
https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

If so, please post the wc-vivawallet.php you are using as notices/warnings you mention do not corrspond with the line number of the original file (example: line 320 contains only a closing bracket).

**Comment by VivaWalletSupport** [comment]
I see the code has been modified, please try the original code and inform me in case of a problem.

**Comment by Alina-chan** [comment]
I did a reinstall however I still get a failure as a return

**Comment by VivaWalletSupport** [comment]
Please describe the problem as detailed as possible. Presuming you are using the demo mode and the credentials from your demo account (mid,api key,source code,test mode checked in the plugin settings), what data are you using to make the test transaction (card, order amount). After making the transaction you are returned to your fail URL or is there another problem? Can you provide some screenshots of the payment source settings, plugin settings, fail page that is redirected to?

**Comment by Alina-chan** [comment]
Of course. I am using a demo viva account under http://demo.vivapayments.com. 
My wallet is set up as: 

![image](https://user-images.githubusercontent.com/22427823/47774537-f593c300-dcf5-11e8-975c-ba7e93a4b397.png)

My settings under **WooCommerce** > **Vivawalet** are:
![image](https://user-images.githubusercontent.com/22427823/47774613-32f85080-dcf6-11e8-991d-30a677579bd4.png)

I only allow logged in users (me in this case) to be able to proceed with the Viva payment gateway by using the following snippet on my functions.php file (*):

`add_filter('woocommerce_available_payment_gateways', 'custom_filter_gateways', 1);

function custom_filter_gateways($gateway_list) {
	if(!is_user_logged_in()) {
		unset($gateway_list['vivawallet']);
	}
    return $gateway_list;
}`

(*) Note: I've tried to momentarily disable this action in case that was the issue, but that makes no difference after all.

I chose a product on my eshop and I proceed to checkout where I chose the Viva payment option. 
![image](https://user-images.githubusercontent.com/22427823/47774892-f1b47080-dcf6-11e8-9794-ee4f91806e4f.png)

By clicking on checkout I get redirected to Viva's demo environment where I use the following details:
![image](https://user-images.githubusercontent.com/22427823/47774984-258f9600-dcf7-11e8-94a1-3cc8b174b6bf.png)

By submitting this form I get redirected to this screen:
![image](https://user-images.githubusercontent.com/22427823/47775080-6091c980-dcf7-11e8-9b2c-4e08635c8fa8.png)

2 rows get inserted in the **vivawallet_data** table on my database

![image](https://user-images.githubusercontent.com/22427823/47775495-7eabf980-dcf8-11e8-9ee7-ff4d4f8dea45.png)

The order shows up under the WooCommerce > Orders as (**): 
![image](https://user-images.githubusercontent.com/22427823/47775591-c03ca480-dcf8-11e8-9c24-afa1207b5233.png)

![image](https://user-images.githubusercontent.com/22427823/47775625-d6e2fb80-dcf8-11e8-8e9c-1cfcb7b8db03.png)

(**) Note: It doesn't insert the transaction ID in the order's description as well.

Back to my Viva's demo account, I see no transactions as for today:

![image](https://user-images.githubusercontent.com/22427823/47775717-232e3b80-dcf9-11e8-981b-9fadb241a0af.png)

These are the steps I follow every time, and same thing happens when I leave the Viva payment option as public and not unset it.

**Comment by VivaWalletSupport** [comment]
Correct in the payment source the return URLs to include the index.php? parts:
SUCCESS URL: index.php?wc-api=wc_vivawallet&vivawallet=success
FAIL URL: index.php?wc-api=wc_vivawallet&vivawallet=fail

For the failing transaction, please do a die statement on line 311 like die($postargs); to see what arguments are used and post them here. You can remove the plugin settings images as it is no longer needed.

**Comment by Alina-chan** [comment]
With the die statement the checkout process stops at http://domain.com/checkout/?key=wc_order_5bd9c9a7cd721&order-pay=7794 giving the message:

Amount=3950&RequestLang=el-GR&Email=balaur%40hta.gr&MaxInstallments=1&MerchantTrns=7794&SourceCode=6114&CurrencyCode=978&PaymentTimeOut=300

**Comment by Alina-chan** [comment]
I have set up the return URLs as below:
SUCCESS URL: index.php/wc-api/wc_vivawallet&vivawallet=success
FAIL URL: index.php/wc-api/wc_vivawallet&vivawallet=fail

**Comment by VivaWalletSupport** [comment]
See the differences:
Wrong:
SUCCESS URL: **index.php/wc-api/wc_vivawallet**&vivawallet=success
FAIL URL: **index.php/wc-api/wc_vivawallet**&vivawallet=fail

Right:
SUCCESS URL: **index.php?wc-api=wc_vivawallet**&vivawallet=success
FAIL URL: **index.php?wc-api=wc_vivawallet**&vivawallet=fail

**Comment by Alina-chan** [comment]
I see, can I use your version of return URLs with pretty permalinks though? Also, do I need the WC Legacy API to be enabled?

**Comment by Alina-chan** [comment]
With the changes you suggested, I now get the following screen:
![image](https://user-images.githubusercontent.com/22427823/47804350-3cf17200-dd3d-11e8-8e17-9b97aa5d7ae7.png)

**Comment by Alina-chan** [comment]
Just emailed you, thank you!
