### ISSUE TITLE
Vivapayments.com marked as "Not secure" by Chrome

### ISSUE THREAD

**Issue by PhotoPaul** [VivaPayments/API#631]
Το πρόβλημα το παρατήρησα σήμερα στον Chrome Version 71.0.3578.20 (Official Build) beta (64-bit) στα Windows, καθώς και στον Chrome 72.0.3591.2 στο Android, αλλά ενδέχεται να υπάρχει και σε προηγούμενες εκδόσεις του Chrome καθώς και σε άλλους Browsers και OSes.

Παρακαλώ λύστε το γιατί οι πελάτες μας βλέπουν το site σας ως "Not secure" με αποτέλεσμα να φοβούνται να συμπληρώσουν τα στοιχεία τους.

**Comment by PhotoPaul** [comment]
![image](https://user-images.githubusercontent.com/3471804/47707749-4394c200-dc35-11e8-9684-e4d897e69601.png)

**Comment by PhotoPaul** [comment]
This issue doesn't appear anymore.

Double checked with:
Chrome Version 71.0.3578.30 on Windows
Chrome 72.0.3596.0 on Android

You can consider it closed.

**Comment by kostGX** [comment]
Thanks for noticing.
