### ISSUE TITLE
Viva Wallet payment

### ISSUE THREAD

**Issue by Cristinawork** [VivaPayments/API#634]
I have connected the eshop epiplazampetoglou.gr with viva wallet.
Everything ok, after pressing pay with viva wallet the popup Pay with Viva Wallet is showing up, the right amount also, but when the customer inserts card details, nothing goes on, we have tried with a few cards.

code used is this

<script src="https://www.vivapayments.com/web/checkout/js"></script>
<form action="/checkout" method="post">
<button type="button" 
  data-vp-publickey="xxx-thepublickey"
  data-vp-merchantref="xxx-merchantid"
  data-vp-lang="en"
  data-vp-text="Pay &raquo; Viva Wallet"
  data-vp-description="Text"
  data-vp-amount="200">
</button>
</form>

**Comment by kostGX** [comment]
Hello @Cristinawork and thank you for your patience.

For the Simple Checkout (the integration method you're trying to achieve) what the form does is generate a transaction token. 

After this is done you need to POST the token to your backend in order to make to charge and complete the order.

Please consult this instructions: https://github.com/VivaPayments/API/wiki/Simple-Checkout

**Comment by Cristinawork** [comment]
Hello and thank you.
Where should I post vivaWalletToken, in the same simple checkout form? With which value??
You mean this script: public class TransactionResult... ??
What is this, java, where should I put it in the code, in the form, after the form...
Please give me a simple example

**Comment by kostGX** [comment]
I suggest you follow the instructions from the beginning.

1) Paste the following HTML code in your page:
`html <html>
    <head>
        <title>Simple Checkout</title>
    </head>
    <body>
      <form id="myform" action="/checkout" method="post">
        <button type="button"
          data-vp-publickey="YOUR PUBLIC KEY (found in Settings > API Access)"
          data-vp-baseurl="https://demo.vivapayments.com"
          data-vp-lang="en"
          data-vp-amount="1000"
          data-vp-description="My product">
        </button>
      </form>

      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://demo.vivapayments.com/web/checkout/js"></script>
    </body>
</html>`

As you can see, on submit, this form POSTs a request to /checkout
**<form id="myform" action="/checkout" method="post">**

This means you'll have to "listen" on this endpoint (i.e. mysite.com/checkout) following the logic of TransactionResult in order to make the actual transaction.

The TransactionResult code is in .NET (C#) language and is designed to run on the server-side, i.e. backend.

**Comment by Cristinawork** [comment]
Βλέπω από αλλα comments οτι γράφετε ελληνικά, οπότε θα συνεχίσω έτσι.
Ναι, βλέπω τώρα οτι η φόρμα έχει το action /checkout αλλά δεν το χρειαζομαι.
Εγώ δεν θέλω να το πάω σε άλλη σελίδα checkout, εφόσον ανοίγει το popup πληρωμής Viavawallet που εμφανιζει σωστά τις μεταβλητές που του στέλνω, ποσο, επιχειρηση κλπ. Εμφανίζει και την επιλογή για κάρτα, απλά δεν γίνεται η πληρωμή.
Το μόνο που θέλω είναι να γίνεται απευθείας πληρωμή με κάρτα, δεν χρειάζομαι να μου στείλει response πισω στο site.

**Comment by kostGX** [comment]
Ο πελάτης δεν αλλάζει σελίδα, απλά η χρέωση πραγματοποιείται σε δικό σας backend και στην συνέχεια ανάλογα το response, στην ίδια σελίδα ο πελάτης βλέπει αν πραγματοποιήθηκε η πληρωμή ή όχι.

Αυτό συμβαίνει για λόγους security. Για την χρέωση απαιτείται το Charge Token καθώς και το API Key σας, το οποίο αν δεν γινόταν server side, σημαίνει πως θα μπορούσε ο οποιοσδήποτε να αποκτήσει πρόσβαση σε στοιχεία του λογαριασμού σας μέσω του API Key.

**Comment by Cristinawork** [comment]
ΟΚ, θα δοκιμασω το βάλω στην ιδια σελίδα. Αλλά πως το γράφω, τι tags βάζω πριν και μετά τον κώδικα, πριν δηλαδή το public class TransactionResult και στο τέλος?

**Comment by Cristinawork** [comment]
Ακόμη τι value πρέπει να εχει το hidden token στην φορμα simple checkout?
<input type="hidden" name="vivaWalletToken" value="">

**Comment by kostGX** [comment]
@Cristinawork Καλημέρα σας, το TransactionResult είναι .NET κώδικας που δεν τρέχει σε HTML σελίδες αλλά σε backend server. Θα πρέπει να έχετε τεχνικές γνώσεις για να κάνετε την συγκεκριμένη υλοποίηση.

Το hidden token δεν έχει κάποια τιμή. Γεμίζει αυτόματα από την φόρμα της Simple Checkout και αυτό το token αποστέλλεται στο backend σας για να ολοκληρωθεί η χρέωση.

**Comment by Cristinawork** [comment]
Καλησπέρα,
php δουλευώ, όπως οι περισσότεροι. τι γίνεται σε αυτην την περίπτωση?
by the way, δεν θα έπρεπε να λέγεται simple checkout

**Comment by kostGX** [comment]
Καλημέρα,

This can be achieved with a single HTTP POST request to ‘/api/transactions’ as shown below.

Αν μελετήσετε τον κώδικα .NET θα δείτε πως γίνεται POST στο /api/transactions και περνάμε σαν parameter "PaymentToken" την τιμή του charge token (του hidden field δηλαδή). Συνεπώς χρειάζετια μία παρόμοια υλοποίηση σε PHP (παραδείγματα από google search 
https://www.google.com/search?client=safari&rls=en&q=how+tp+make+rest+post+request+php&ie=UTF-8&oe=UTF-8)

Έτσι ολοκληρώνεται η χρέωση.

**Comment by Cristinawork** [comment]
Εκανα τον κωδικα στην checkout page που στέλνει η φόρμα, αλλά δεν.
Οταν κάνω δοκιμη πληρωμης με καρτα, ενω δειχνει οκ, δεν ολοκληρώνεται η πληρωμη.

$serviceurl = 'https://www.vivapayments.com/api/transactions';
$curl = curl_init($serviceurl);

$MerchantId = 'client merchant id';
$APIKey = 'client api key'; 
$PaymentToken = $_POST["vivaWalletToken"];

curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_HEADER, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_POSTFIELDS, $PaymentToken);
curl_setopt($curl, CURLOPT_MERCHANTID, $MerchantId);
curl_setopt($curl, CURLOPT_APIKEY, $APIKey);

$curl_response = curl_exec($curl);
$decoded = json_decode($curl_response);
curl_close($curl);

**Comment by Cristinawork** [comment]
response 

{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ErrorCode":404,"ErrorText":"Order with code 0 was not found","TimeStamp":"2019-01-08T12:50:47.2093373+02:00","CorrelationId":null,"EventId":2,"Success":false}

**Comment by Tinakicious** [comment]
Τελικά ποια είναι η λύση που δώθηκε για αυτό το πρόβλημα? Αντιμετωπίζω ακριβώς το ίδιο θέμα, φτάνω στην checkout αλλά η πληρωμή δεν ολοκληρώνεται. Μπορείτε να παρέχετε έναν κώδικα σε php που να εναι λειτουργικός?
