### ISSUE TITLE
Παραμέτροι για PaymentRequest() και OrderRequest()

### ISSUE THREAD

**Issue by WebWars** [VivaPayments/API#635]
Καλησπέρα υπάρχει κάποιος τρόπος να μάθουμε το σύνολο των παρεμέτρων που μπορούμε να στείλουμε στα PaymentRequest() και OrderRequest(); Προσπαθώ να περάσω Description For Customer μέσω Native Chekout αλλά δεν μπορώ.

Ευχαριστώ!

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
