### ISSUE TITLE
Issue with Magento 1.9.3.8

### ISSUE THREAD

**Issue by ioannisgz** [VivaPayments/API#636]
Εγκαταστήσαμε το plugin σας σε magento 1.9.3.8
Στην παραγγελία στο link που στέλνει η πλατφόρμα μας μάλλον κάτι λείπει.

https://www.vivapayments.com/web/newtransaction.aspx?Ref=
Αυτό είναι που στέλνουμε και παίρνουμε απάντηση Bad Request.
Μπορείτε να με βοηθήσετε;

**Comment by VivaWalletSupport** [comment]
Hello, please check if you are using the correct credentials for your live Viva Payments account (MerchantID,API key,Source Code) and if the payment source has been activated.

**Comment by ioannisgz** [comment]
Hello. Thank you for your answer.

As I checked all fields are correct.



Merchant 38e2a94e-cfaf-47a4-b6ff-6ed5f17bdd3d.

Optional Secondary Source code should be empty?

Also in should I change something in viva wallet advanced section : Order code is s, Transaction ID is t , Language is lang

As far I understand is that we can’t connect with your api because of a problem. When our system creates the order number and goes for the redirect the link is wrong. Something is missing after the =
Here is the link we produce: https://www.vivapayments.com/web/newtransaction.aspx?Ref= <https://www.vivapayments.com/web/newtransaction.aspx?Ref=> 

Also I see in our logs these errors:

2018-11-05T08:27:57+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/wpaper/public_html/app/code/local/Mage/Vivawallet/Model/Hpay.php on line 255
2018-11-05T08:27:57+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/wpaper/public_html/app/code/local/Mage/Vivawallet/Model/Hpay.php on line 256
2018-11-05T08:27:57+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/wpaper/public_html/app/code/local/Mage/Vivawallet/Model/Hpay.php on line 257
2018-11-05T08:27:57+00:00 ERR (3): Notice: Trying to get property of non-object  in /home/wpaper/public_html/app/code/local/Mage/Vivawallet/Model/Hpay.php on line 258

Something  is wrong in Hpay.php




 <https://www.wallpapershop.gr/>
Goutzamanis Giannis 	
0030 697 7707 813/sales@wallpapershop.gr <mailto:sales@wallpapershop.gr>
WallpaperShop  Tel: 0030 210 5026891/ Fax: 0030 211 7407303  
25th Martiou 54 , 13231 , Petroupoli , Athens
https://www.wallpapershop.gr <https://wallpapershop.gr/>
 <https://www.facebook.com/WallpaperShop.gr> <https://twitter.com/WallpaperShops> <applewebdata://67CA0AAE-98FA-439A-8ACE-126FC36D976C/ioannis.goutzamanis> <http://pinterest.com/wallpapershops/>
This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. Wallpapershop is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.

P Please consider the environment before printing this email

**Comment by VivaWalletSupport** [comment]
Please post a screenshot of the payment extension settings, viva payment source settings and the viva payment sources list (mask the API key).
