### ISSUE TITLE
Viva wallet and woocommerce complete payment

### ISSUE THREAD

**Issue by panagiotisstathopoulos** [VivaPayments/API#637]
I am using Viva payments on a Woocommerce / Wordpress site
https://github.com/somewherewarm/woocommerce-gateway-viva

The transaction/order from the client's side is completed fine, with no errors. The payment is complete in Viva but in the admin panel i still see in the order "payment pending".

I see the following error on the log, any hep ?

2018-11-06T15:27:39+00:00 ERROR Error: Processed payment for an unknown order. Possible fraudulent attempt. Request details: Array
(
    [wc-api] => wc_gateway_viva
    [result] => success
    [t] => 510000000-00000-....
    [s] => 200000...
    [lang] => en-US
)

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
