### ISSUE TITLE
Πρόβλημα μετά από επιτυχής συναλλαγή σε magento

### ISSUE THREAD

**Issue by ioannisgz** [VivaPayments/API#641]
Καλησπέρα. Μετά από επιτυχής πληρωμή με κάρτα δεν ανακατευθύνεται ο πελάτης στην ιστοσελίδα μας. Παραμένει στο μήνυμα επιτυχίας της VIVA.  Αυτό έχει ως αποτέλεσμα να πηγαίνει στον πελάτη μόνο το mail της viva για την πληρωμή. Το δικό μας mail δεν φεύγει καθόλου. Η παραγγελία μπαίνει στο σύστημα μας κανονικά. Χρησιμοποιούμε το plugin που έχετε για Magento 1.9.3.8.
Μπορείτε να βοηθήσετε;

**Comment by VivaWalletSupport** [comment]
Hello, looks like you are not connected to a payment source that you should have created in your Viva account, the source code number should be used in the extensions settings.

**Comment by ioannisgz** [comment]
I am sorry I didn't understand. What should I do?

**Comment by ioannisgz** [comment]
In my extension's configuration I have these:
Source Code & Source Code fields are empty.
OrderCode URL: https://www.vivapayments.com/api/orders
Gateway URL: https://www.vivapayments.com/web/newtransaction.aspx.

Also MerchantID and API Key are filled.

**Comment by VivaWalletSupport** [comment]
See the setup section at https://github.com/VivaPayments/API/tree/master/Plugins/magento/magvivawallet

**Comment by VivaWalletSupport** [comment]
They should be as documented, for Magento 1.x:

Example with URL rewrite disabled:
Success page: https://www.mysite/index.php/vivawallet/hpay/hpok/
Failure page: https://www.mysite/index.php/vivawallet/hpay/hpnok/

Example with URL rewrite enabled:
Success page: https://www.mysite/vivawallet/hpay/hpok/
Failure page: https://www.mysite/vivawallet/hpay/hpnok/

**Comment by ioannisgz** [comment]
Nope. It isn't working. I get always page not found in my site.
Link is : www.mysite/vivawallet/hpay/hpok/?t=0a156a9b-23c6-416e-aecb-34121401b1e4&s=1986175134872600&lang=el-GR

**Comment by VivaWalletSupport** [comment]
Please post a screenshot of the source settings, mask partly the domain name if needed.

**Comment by ioannisgz** [comment]
<img width="715" alt="screenshot 2018-11-22 at 12 57 30" src="https://user-images.githubusercontent.com/44767880/48898745-3d6dbc00-ee56-11e8-95af-2f3a937531d8.png">
I tried both ways. Redirection or not.

**Comment by VivaWalletSupport** [comment]
Could you send admin, ftp and viva account access to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com to check the installation?

**Comment by ioannisgz** [comment]
Email sent to both accounts. Please check and inform me. Thank you

**Comment by VivaWalletSupport** [comment]
In your case I corrected the URLs to:
Success page: https://www.mysite/el/vivawallet/hpay/hpok/
Failure page: https://www.mysite/el/vivawallet/hpay/hpnok/

Please check if it is ok now and close the ticket if solved.

**Comment by ioannisgz** [comment]
Ok.This is working! Thank you very much.
Last question please to close this issue. What if the order is placed from the my en/ English store?
Will I have the redirection to the Greek store?

**Comment by VivaWalletSupport** [comment]
You can configure the payment extension settings in a particular storeview (Greek/English) and adjust the source code setting for each storeview. In your Viva account create 2 payment sources, one for Greek and one for English. For the English payment source use following URLs:
Success page: https://www.mysite/en/vivawallet/hpay/hpok/
Failure page: https://www.mysite/en/vivawallet/hpay/hpnok/

**Comment by ioannisgz** [comment]
Perfect! Understood! Thank you very much!
