### ISSUE TITLE
Recurring transaction failed Error 502

### ISSUE THREAD

**Issue by nlabiris** [VivaPayments/API#644]
Καλησπέρα σας,

Μετά από επικοινωνία με το support της Viva (μέσω ticket **CC-1054775**), με παρέπεμψαν στη σελίδα σας στο Github για περισσότερες πληροφορίες.

Κατά τις δοκιμές μας στο **demo** περιβάλλον παρατηρήσαμε ότι αρκετά συχνά τον τελευταίο μήνα μας επιστρέφεται το παρακάτω response κατά την δημιουργία recurring transaction. *(το πρόβλημα εμφανίστηκε ξαφνικά από αρχές Νοεμβρίου)*

```json
{
    "Emv": null,
    "Amount": 0.39,
    "StatusId": "E",
    "CurrencyCode": "978",
    "TransactionId": "1b6cdaf6-17cb-4976-b38b-8deb2f738c09",
    "ReferenceNumber": 51720,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ErrorCode": 502,
    "ErrorText": "Transaction failed",
    "TimeStamp": "2018-11-22T09:23:51.3532456+02:00",
    "CorrelationId": null,
    "EventId": 10199,
    "Success": false
}
```

Όπως φαίνεται από το **ErrorCode**, επιστρέφει **502** που σημαίνει ότι υπάρχει κάποιο server side issue.

Επίσης, παρατηρήσαμε *ότι οι failed συναλλαγές που είχαμε με ίδιο κωδικό λάθους δεν καταγράφονται στο portal που φαίνονται όλες οι συναλλαγές*.

Έχετε κάποια ιδέα γιατί μπορεί να συμβαίνει αυτό; Υπάρχει κάποιο server side issue από την μεριά σας;

Ευχαριστώ εκ των προτέρων.

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. This could have been an issue with our demo server which happens from time to time. If you have any other queries please do please let us know and we'd be happy to help. Thanks!
