### ISSUE TITLE
Urgent assistance required

### ISSUE THREAD

**Issue by DPATARAS** [VivaPayments/API#645]
Hello

Platfrom: Wordpress/Woocommerce
Plugin: Viva Payments - Viva Wallet WooCommerce Payment Gateway by Enartia
Method: Redirection

I own 2 websites using both wp/woocommerce.
I have two  active payment sources (one for each website)
I own a single wallet on which both payment sources are connected.

When i use the codelt of each payment source, then upon completion of payment it returns to a blank page with only a "-1" in the upper left corner. Payment is visible on viva account.
Payment is send to merchants email. However the order is not arriving in woocommerce dashboard and to the merchants email.

When i use the codelt "default", payment is made but there is no redirection back to merchant's website, although we have set to return to homepage. Orders not vissible on woocommerce dashboard. Τhey can be found only in "παραγγελίες">>"δικά μου" (orders>my orders). I made real time tests.Ιn test payments i did not use my card or my details so there couldnt be any connection with me.

Thanks in advance for your support.

Dimitris

**Comment by matthewrgourd** [comment]
Hi @DPATARAS, I'm sorry for the lack of response previously. In case this is still an issue, I need to point out that [Viva Wallet WooCommerce Payment Gateway by Enartia](https://wordpress.org/plugins/woo-payment-gateway-for-vivapayments/) is not our official plugin so as such we can't offer any support. The official plugin along with in-depth instructions is available here:

https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

We plan to move this download to the Wordpress plugin directory in the next few weeks. This should avoid any confusion in the future.

Thanks!
