### ISSUE TITLE
Πρόβλημα με αποτυχημένη πληρωμή

### ISSUE THREAD

**Issue by codeminelab** [VivaPayments/API#646]
Καλησπέρα σας,

Προσπαθεί κάποιος πελάτης να πληρώσει online μέσα από το API, αλλά αποτυγχάνει.

Χτυπώντας το API με το αντίστοιχο transaction ID

https://members.vivawallet.com/api/transactions/33e9f3b9-f544-4e7a-baf2-f582676701dc

επιστρέφει 

"StatusId": "E"

Υπάρχει κάποιος τρόπος να γνωρίζουμε για ποιο λόγο απέτυχε η πληρωμή του?

**Comment by nlabiris** [comment]
Καλησπέρα,

Από όσο γνωρίζω από παλιότερα issues (#196) που κοίταξα, απλά επιστρέφουν ένα generic message γιατί η κάθε τράπεζα έχει διαφορετικό τρόπο να δηλώνει τα errors που προκύπτουν κατά τη συναλλαγή.

Ελπίζω να βοήθησα

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
