### ISSUE TITLE
Ελληνικά στο στάδιο πληρωμής OpenCart

### ISSUE THREAD

**Issue by alextsampas** [VivaPayments/API#647]
Στο στάδιο επιβεβαίωσης της πληρωμής εμφανίζεται μόνο στα Αγγλικά το νέο παράθυρο. 
Η προσπάθεια γίνεται με redirect στο περιβάλλον σας. 
https://www.vivapayments.com/web/newtransaction.aspx
χωρίς δυνατότητα Ελληνικών (Η σημαία είναι μόνο Αγγλική) 
Η γλώσσα του eshop ειναι Ελληνικά.
Παρακαλώ ενημερώστε με πως ο Έλληνας θα βλέπει Ελληνικά !
Πλατφορμα OpenCart 3.0.2.0

**Comment by VivaWalletSupport** [comment]
Hello, what extension is used to connect OpenCart with Viva Payments?

**Comment by alextsampas** [comment]
Hello , I am using this
https://github.com/VivaPayments/API/tree/master/Plugins/opencart/Opencart%203

-

**Comment by VivaWalletSupport** [comment]
In your el-gr.php (catalog) file, what value has been specified at the $_['code'] variable?

**Comment by alextsampas** [comment]
$_['code'] = 'el';

Ελληνικά Greek

**Comment by VivaWalletSupport** [comment]
Could you send ftp access to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com to check the installation?

**Comment by alextsampas** [comment]
I sent above access and info
