### ISSUE TITLE
Source:1111 OrderID:11null

### ISSUE THREAD

**Issue by olekkas** [VivaPayments/API#648]
Καλησπέρα σας ,
Έχω βάλει το Merchant ID στο Viva Payment API ID, Το Api Key στο API Password, και παιρνω ένα μηνυμα: Source:1111 OrderID:11null (το source id είναι τυχαίο για επεξήγηση)
Η πλατφ΄ορμα είναι OpenCart 3 και το template Jurnal 3.
Μπορείτε σας παρακαλώ να μου πείτε που κάνω λάθος?

**Comment by VivaWalletSupport** [comment]
Hello, what extension is used to connect OpenCart with Viva Payments?

**Comment by olekkas** [comment]
https://cakeart.gr/orestis.php

**Comment by olekkas** [comment]
ocgr_viva_3.x

**Comment by olekkas** [comment]
οκ thank you
