### ISSUE TITLE
SHOULD WE BECOME UNPOLITE TO DRAW SOME ATTENTION?? TERRIBLE SUPPORT

### ISSUE THREAD

**Issue by DPATARAS** [VivaPayments/API#653]

**Comment by codeminelab** [comment]
I feel exactly the same. I opened a ticket 9 days ago, and although the support section of Viva told me to raise the ticket here, I got no response so far... Not a good tactic to keep your customers. I will certainly not suggest viva for my next customers.

**Comment by DPATARAS** [comment]
Have contact them by phone 4-5 times, they said they would notify the github team.. nothing happened..
Then theyy told me to send an email to support@vivawallet.com, did twice.. nothing happened..

**Comment by matthewrgourd** [comment]
Hi there, sorry for the lack of reply, please could you re-raise the issue if it's still a problem and I'll look into it as a matter of priority!
