### ISSUE TITLE
Mobile API PCI compliance

### ISSUE THREAD

**Issue by artetrad** [VivaPayments/API#656]
Καλησπέρα, θα ήθελα να ρωτήσω αν το integration με το Mobile API σας απαιτει απο πλευράς μας PCI compliance. 

Δηλάδή σε περίπτωση που σε ένα mobile app χρησιμοποιήσουμε custom πεδία για να προσθέσει ένας χρήστης την κάρτα του και δεν τα κρατήσουμε σε δικές μας βάσεις δεδομένων αλλά τα χρησιμοποιήσουμε για να κάνουμε tokenize την κάρτα αυτή μέσω του API σας, τότε απ'ότι καταλαβαίνω εμείς δε χρειάζεται να είμαστε PCI compliant. Αρκεί που είστε εσείς που κάνετε το storing της κάρτας. 

Θα ήθελα μια επιβεβαίωση για το παραπάνω. Ευχαριστώ.

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
