### ISSUE TITLE
Πρόβλημα με 3D Secure

### ISSUE THREAD

**Issue by PUBLEES** [VivaPayments/API#657]
Στην αρχή της συνεργασίας μας είχα ζητήσει να μην είναι ενεργό το redirect στο 3D Secure καθώς οι χρήστες δεν είναι εξοικειωμένοι με αυτήν την τεχνολογία και μου δημιουργεί πρόβλημα στις παραγγελίες που δέχομαι, χάνοντας πελάτες.

Ωστόσο, τις τελευταίες 2 εβδομάδες, με ενημερώνουν χρήστες του e-shop μου ότι τους κάνει redirect σε 3D Secure και είτε δεν έχουν ιδέα τι πρέπει να κάνουν, είτε ότι όταν ακολουθούν τις οδηγίες τους μπλοκάρει.

Παρακαλώ για την άμεση απαληφή του redirect στο 3D Secure καθώς χάνω πελάτες.

**Comment by liagkos** [comment]
Εννοείς τη φόρμα που ζητάει το extra authentication του πελάτη, ανάλογα την τράπεζα;

**Comment by liagkos** [comment]
Δεν ήξερα πως μπορεί να απενεργοποιηθεί αν το ζητήσεις. Παρ'όλα αυτά διαφωνώ με την προσέγγισή σου. Αυτού του είδους η επιπλέον προστασία δεν είναι καινούργια, υπάρχει πάρα πολλά χρόνια, οι on-line αγορές υφίστανται στην Ελλάδα ακόμα περισσότερα χρόνια, και σε καμία περίπτωση οι χρήστες που προτιμούν αυτόν τον τρόπο αγορών δεν είναι σε "βρεφικό" ή "νηπιακό" στάδιο. Ξέρει δηλαδή ο άλλος να μπαίνει στο ebay, να ψωνίζει και να πληρώνει με Paypal, και δεν ξέρει να χρησιμοποιήσει 3DSecure; Υπερβάλλεις νομίζω...

**Comment by PUBLEES** [comment]
Αυτά που αναφέρεις είναι η μια οπτική, όταν ακούς, σχεδόν καθημερινά ότι το iphone δεν έχει τόνους στο πληκτρολόγιο, (λόγο της φύσεως των υπηρεσιών που παρέχουμε δημοσιεύσεις πάσης φύσεως υποχρεωτικών και μη δημοσιεύσεων σε εφημερίδες) το τι ακούμε κάθε μέρα υποστηρίζει όλα όσα αναφέρω. Πιθανότατα φυσικά για το κοινό που απευθύνετε το e-shop μου. Σε αρκετές περιπτώσεις δε, η πρώτη αγορά που έκαναν μέσα από το internet ήταν η δημοσίευση της αναγγελίας του γάμου τους μέσα από το site μας. Επομένως, όλα αυτά που αναφέρω ποιο πάνω έχουν κάπου μια βάση.
Να ξεκαθαρίσω ότι είμαι υπέρ του 3D Secure, αλλά θα πρέπει να γίνουν ποιο ξεκάθαρα κάποια πράγματα σε όλους τους χρήστες των καρτών και σε καμία περίπτωση δεν θέλω να χάσω ούτε έναν πελάτη λόγω της άγνοιάς του για το 3D Secure.

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
