### ISSUE TITLE
Prestashop instegration issue with repeated url

### ISSUE THREAD

**Issue by Yogita2212** [VivaPayments/API#658]
I have been facing an issue on my site. The URL repeats it self while checkout. Please refre to the attachment. 

![image](https://user-images.githubusercontent.com/45760554/49733901-bff4d900-fca8-11e8-880f-67d5e9b01148.png)

**Comment by VivaWalletSupport** [comment]
Hello, could you post a link to the module that is used for connecting with Viva Payments?

**Comment by Yogita2212** [comment]
We used this

https://github.com/VivaPayments/API

**Comment by VivaWalletSupport** [comment]
Could you post a screenshot of your payment source setup?

**Comment by Yogita2212** [comment]
[image: image.png]

**Comment by VivaWalletSupport** [comment]
Please post the image at git to be visible.

**Comment by Yogita2212** [comment]
![image](https://user-images.githubusercontent.com/45760554/49865495-15f18a00-fe2b-11e8-9324-82029a764622.png)

**Comment by VivaWalletSupport** [comment]
The image you posted is not from the payment source you created in your Viva account, I would suggest to remove it and to change your API Key. Please try again posting an image from your source setup.

**Comment by belga1** [comment]
from where you get this module

**Comment by VivaWalletSupport** [comment]
Hello Yogita2212, did you manage to resolve this issue or is there any other problem I can help you with?
