### ISSUE TITLE
Hikashop

### ISSUE THREAD

**Issue by andreas444** [VivaPayments/API#659]
Καλησπέρα. Προσπαθώ να εγκαταστήσω το plugin για το  Hikashop σε joomla αλλά μου βγάζει το μήνυμα: Unable to find install package.

Μπορείτε να με βοηθήσετε;

**Comment by VivaWalletSupport** [comment]
Hello, what plugin is used and what version of Joomla / Hikashop?

**Comment by andreas444** [comment]
Hello, thank you for reply. I use HikaShop Starter: 4.0.1 & the plugin https://github.com/VivaPayments/API/tree/master/Plugins/hikashop/plg_viva_hikashop. Joomla 3.9.1

**Comment by VivaWalletSupport** [comment]
I cannot replicate the error using the same configuration, I suspect that the files where not saved and packed correctly.
[plg_viva_hikashop.zip](https://github.com/VivaPayments/API/files/2668317/plg_viva_hikashop.zip)

**Comment by andreas444** [comment]
Thank you very much. The problem is solved :+1:

**Comment by andreas444** [comment]
I proceed after installation and I receive the message from hikashop: _syntax error, unexpected ''BGN'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'_ 

Any idea? Thank you again.

**Comment by VivaWalletSupport** [comment]
At what file (line number) / location does the error occur?

**Comment by VivaWalletSupport** [comment]
See that one filed contained a bug, please use attached.

[plg_viva_hikashop.zip](https://github.com/VivaPayments/API/files/2671623/plg_viva_hikashop.zip)

**Comment by andreas444** [comment]
Perfect, I installed the plugin. Thank you a lot!
