### ISSUE TITLE
Mixed Content HTTPS calls HTTP file

### ISSUE THREAD

**Issue by johnchampa** [VivaPayments/API#660]
Καλημέρα

Έχω ένα θέμα με ένα site που φτιάχνω το οποίο είναι σε τοποθεσία https αλλά φαίνεται να καλεί αρχείο http από https://demo.vivapayments.com/web/checkout/js

Όταν το γύρισα σε live κατάσταση είχα πάλι το ίδιο πρόβλημα

Παρακάτω είναι το πρόβλημα από console log

Mixed Content: The page at 'https://mysite.com/checkout/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://demo.vivapayments.com/api/cards/installments?key=ziZzammkpLYHnNhr7%2B2gJxH5OZ%2Bzv88%2FcLD%2ByYspAW0%3D'. This request has been blocked; the content must be served over HTTPS.

Ευχαριστώ

**Comment by matthewrgourd** [comment]
Hi there, sorry for the delayed response. This issue should be fixed now as we're using HTTPs for both demo and live environments: https://developer.vivawallet.com/development-environments/

Thanks!
