### ISSUE TITLE
We have done the test as per above instruction but we cannot get the response after payment process and can't see the transaction log on our viva demo account.

### ISSUE THREAD

**Issue by Delivertoo** [VivaPayments/API#661]
Hi Support,

Now we have integrated viva native checkout using git hub code, i.e.: https://github.com/VivaPayments/API/tree/master/NativeCheckout/PHP

Our demo viva account is:
**wallet id174460646080**

Please check this URL:http://paymentgateway.livedemoproject.com/vivanative/web/
**As per the Viva document:**

"The demo work environment can be used for all your development/demonstration requirements. No actual payments are made from this environment.
A successful transaction can be simulated (in the demo environment only), with the demo card number 4111 1111 1111 1111 with any future expiration date and 111 for the CVV2. All other card numbers will result in a failed transaction. You can create demo accounts from here, all that is required is a mobile phone number.

The minimum transaction amount is 0.30 EUR"

We have done the test as per above instruction but we cannot get the response after payment process and can't see the transaction log on our viva demo account.

We have done everything as per your instruction. Please check and let us know what we to do now to get the success.
Please check our code also https://trello-attachments.s3.amazonaws.com/5ab1f8cf6e36c824edde2c02/5bbdae61506a674f31b1c820/eab7b389c975f88bb6db33c9041ff205/vivapay.zip

13/12/2018

We have checked  again all the instruction and we have done all the settings stepwise. Also we have checked it on a secure site but we're also get this error.

Please check the URL: https://api-development-customization.ordering.co/sys/data/payment/customization/vivanativetest/index
Hence, can you please let us know about what can be the possible reason for the error "Viva Payments: Not Found" What we have to do to solve this error.

Thank You!

**Comment by Delivertoo** [comment]
We have checked all the instruction and we have done all the settings stepwise. Also we have checked it on a secure site but we're also get this error.

Please check the URL: https://api-development-customization.ordering.co/sys/data/payment/customization/vivanativetest/index
Hence, can you please let us know about what can be the possible reason for the error "Viva Payments: Not Found" What we have to do to solve this error.

Thank You!

**Comment by kostGX** [comment]
@Delivertoo hello,

I have seen that you successfully managed to integrate with Simple Checkout -- great news!

Is this issue still relevant? If yes let me know so we can look into it, although it seems like you didn't follow all the steps of the guide: https://github.com/VivaPayments/API/wiki/Native-Checkout

If not, kindly close the issue.
