### ISSUE TITLE
Greek language page after making payment on my webstore, should be in English 

### ISSUE THREAD

**Issue by monkymonk** [VivaPayments/API#662]
Hi 
My webshop is in the UK, whole page is in English, but since I connected to Viva wallet, page after completed payment is in Greek language- screenshot attached:

![rgrfg](https://user-images.githubusercontent.com/45765050/49809399-af9b3780-fd56-11e8-9cd1-71ceaad128b8.JPG)

Can you sort this out for me please. I called Viva several times and they are helpless..... they sent me to you

Kind Regards
Amanda

**Comment by VivaWalletSupport** [comment]
Hello, could you provide us with some more details for what e-commerce platform is used, do you use a plugin to connect (post a link from the used plugin), did you setup a payment source to connect?

**Comment by monkymonk** [comment]
I use WooCommerce, payments went thorugh good, just the page after payment is in Greek... :)
 
see attachements for plugin version I use
 
 
 
W dniu 2018-12-11 16:56:42 użytkownik Tom van der Veer <notifications@github.com> napisał:
Hello, could you provide us with some more details for what e-commerce platform is used, do you use a plugin to connect (post a link from the used plugin), did you setup a payment source to connect?

**Comment by VivaWalletSupport** [comment]
The attachment did not arrive, just send the URL from where you got it.

**Comment by monkymonk** [comment]
that is URL where I got plug in from :
https://www.seven7senses.co.uk/wp-admin/plugins.php?s=viva&plugin_status=all
 
 
 
 
 
W dniu 2018-12-11 19:23:15 użytkownik Tom van der Veer <notifications@github.com> napisał:
The attachment did not arrive, just send the URL from where you got it.

**Comment by monkymonk** [comment]
I have made screenshot with description of this plugin, I also contacted plugin home page 'EMSPACE' and he replyed:
''Hello Amanda,
 
Our plugin is no longer supported. You are free to make any changes by your own.
 
Kind Regards,
John''
 
W dniu 2018-12-12 19:28:44 użytkownik Tom van der Veer <notifications@github.com> napisał:
That URL only works on your own store so it does not help to identify what is used. Could you try to post the plugin description?

**Comment by VivaWalletSupport** [comment]
Unfortunately I cannot provide assistance on a 3rd party plugin, maybe another Emspace plugin user can help you or use the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

**Comment by monkymonk** [comment]
Can you tell me step by step how to use the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce 
 
which plugin to use and how to put it to shop on WooCommerce
 
I am green in this subject :)
 
W dniu 2018-12-12 21:01:49 użytkownik Tom van der Veer <notifications@github.com> napisał:
Unfortunately I cannot provide assistance on a 3rd party plugin, maybe another Emspace plugin user can help you or use the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

**Comment by VivaWalletSupport** [comment]
The specific plugin pointed at has a readme file with installation instructions..

**Comment by monkymonk** [comment]
can you please upload plugin that I need in your next e-mail attachments as I can't handle it , can't download it somehow...
 
thank you
 
 
W dniu 2018-12-12 21:01:49 użytkownik Tom van der Veer <notifications@github.com> napisał:
Unfortunately I cannot provide assistance on a 3rd party plugin, maybe another Emspace plugin user can help you or use the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce

**Comment by VivaWalletSupport** [comment]
[vivawallet-for-woocommerce.zip](https://github.com/VivaPayments/API/files/2677061/vivawallet-for-woocommerce.zip)

**Comment by monkymonk** [comment]
sorry to be pain in a neck , I did added yr plugin to my plugins on WooCommerce but no change , page after making payment is still in Greek... and   it suppose to go back to shop after payment.
I am hopeless
 
 
 
W dniu 2018-12-13 18:31:25 użytkownik Tom van der Veer <notifications@github.com> napisał:
vivawallet-for-woocommerce.zip

**Comment by VivaWalletSupport** [comment]
Follow the instructions to setup a payment source in your Viva account to connect with your estore, use the code of the source (like 1234) in the plugin settings to connect to your Viva source.

**Comment by monkymonk** [comment]
see screenshot of payment page i see after putting code 1234 in (see attachement)
 
 
 
 
W dniu 2018-12-13 21:00:17 użytkownik Tom van der Veer <notifications@github.com> napisał:
Follow the instructions to setup a payment source in your Viva account to connect with your estore, use the code of the source (like 1234) in the plugin settings to connect to your Viva source.

**Comment by monkymonk** [comment]
Viva wallet gave me API key and Merchant ID, that is all. i can't see anymore payment codes that apply to my account. I have putted API key and Merchant ID into plugin settings week ago.
 
Where can I code you are talking about ?
 
Many thanks :)
 
W dniu 2018-12-13 21:00:17 użytkownik Tom van der Veer <notifications@github.com> napisał:
Follow the instructions to setup a payment source in your Viva account to connect with your estore, use the code of the source (like 1234) in the plugin settings to connect to your Viva source.

**Comment by monkymonk** [comment]
zipped plugin you gave me sipports payments in Euros only ... I need British Pounds :)
 
 
 
 
W dniu 2018-12-14 05:23:09 użytkownik Tom van der Veer <notifications@github.com> napisał:
The 1234 code was just an example, use the code generated for your payment source. Do not reply by email to post comments containing screenshots or attachements, post them in this thread to be visible.

**Comment by monkymonk** [comment]
have you got any tel number so I can call you please?
 
 
 
 
W dniu 2018-12-14 05:23:09 użytkownik Tom van der Veer <notifications@github.com> napisał:
The 1234 code was just an example, use the code generated for your payment source. Do not reply by email to post comments containing screenshots or attachements, post them in this thread to be visible.

**Comment by VivaWalletSupport** [comment]
+ 44 (20) 37347770

**Comment by monkymonk** [comment]
You helped me a lot, you resolved my issue, sorry for asking so many simple questions ( I never had a experience with this subject before)
 
Thank you again - great customer service and help.
 
All the best :)
 
W dniu 2019-01-08 09:28:48 użytkownik Tom van der Veer <notifications@github.com> napisał:
Hello monkymonk, did you manage to resolve issue or is there any other problem I can help you with?

**Comment by VivaWalletSupport** [comment]
No problem and thank you, could you please close this issue?
