### ISSUE TITLE
Problem with vivawalet installments

### ISSUE THREAD

**Issue by dkontod** [VivaPayments/API#664]
Hello.
I have a web store Magento 1.9.4.2
I have installed and setup the payment source and the API, but there is no option for installments in either magento order page or vivapayments redirect page.
How can I activate installments?
![image](https://user-images.githubusercontent.com/24634785/50044241-551d1680-0089-11e9-98d9-885c1cfd4c5d.png)
![image](https://user-images.githubusercontent.com/24634785/50044243-61a16f00-0089-11e9-9ed6-8a333c736fff.png)
![image](https://user-images.githubusercontent.com/24634785/50044255-9281a400-0089-11e9-9f44-9c65039c1d9c.png)

**Comment by VivaWalletSupport** [comment]
Hello, copy the design template (app\design\frontend\default\default\template\vivawallet) to your used theme, clear cache and recompile (if compiler is used).

**Comment by belga1** [comment]
Put 0 for not using the instalments. Add 2 to 36 max to enable the instalments
