### ISSUE TITLE
Πρόβλημα με το Viva plugin στο E shop μου

### ISSUE THREAD

**Issue by IoannisBark** [VivaPayments/API#665]
Γειά σας.

Έχω εγκαταστήσει επιτυχώς το VivaPay Payment Gateway Plugin στο Woocommerce e shop μου και έχω καταχωρήσει επιτυχώς τα στοιχεία μου
![00](https://user-images.githubusercontent.com/45901936/50045866-07ada300-00a3-11e9-9f3b-968c8a6795b3.png)

Το πρόβλημα μου είναι πως όταν πηγαίνω να κάνω μια πληρωμή ενώ με πηγαίνει κανονικά στο Native Checkout που έχω επιλέξει, συμπληρώνω τα στοιχεία μου με πηγαίνει σε ένα 3d secure περιβάλλον το οποίο κρατάει 2 δευτερόλεπτα και με πετάει σε αποτυχία πληρωμής.

Έχω δοκιμάσει με διάφορες κάρτες αλλά το πρόβλημα παραμένει.
![01](https://user-images.githubusercontent.com/45901936/50045907-56f3d380-00a3-11e9-837d-68f92da057c3.png)
![02](https://user-images.githubusercontent.com/45901936/50045908-56f3d380-00a3-11e9-89e4-f9f893aaeacb.png)
![03](https://user-images.githubusercontent.com/45901936/50045909-56f3d380-00a3-11e9-923c-a3d659bb20eb.png)

Μήπως κάνω κάτι λάθος;

**Comment by kostGX** [comment]
@IoannisBark καλημέρα,

Ο τρόπος που χρησιμοποιεί το plugin σας είναι Redirect Checkout και όχι Native. 

Παρακαλώ επιβεβαιώστε πως η πηγή πληρωμών 7161 δεν είναι Native. Μπορείτε να δείτε τις πηγές σας στο Sales > Online Payments > Websites Apps

![https___members_vivawallet_com_selfcare_el-gr_sources_paymentsources_sourcetypeid_ae0e2b35-df43-4729-bd6d-a89a86ce3640](https://user-images.githubusercontent.com/3908736/50209410-52b60780-037c-11e9-8b47-643f2e8b83a0.jpg)

**Comment by IoannisBark** [comment]
Εξ αρχής το έχω ορίσει σε Native/ΠΛηρωμή με Viva Wallet Checkout διότι επιθυμώ να μεταβαίνει στις σελίδες της Viva και αφετέρου δεν έχω Url επιτυχημένης συναλλαγής κλπ.

Δεν μπορεί το plugin να λειτουργήσει σε Native;

**Comment by kostGX** [comment]
Τα screenshots που μας δείχνετε είναι από Redirect checkout και οχι από Native checkout.

Επίσης το plugin που εμείς υποστηρίζουμε για WooCommerce είναι αυτό εδώ: https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce 

Βεβαιωθείτε πως έχετε ακολουθήσει τις οδηγίες ενσωμάτωσης και ενημερώστε μας αν συνεχίζεται να έχετε πρόβλημα.

Ευχαριστώ

**Comment by IoannisBark** [comment]
Επειδή προφανώς δεν έχω τις γνώσεις σας - και φαντάζομαι πως θα έχετε τους λόγους σας ώστε να μην έχετε το plugin σας σε έτοιμη zip μορφή όπως όλος ο εξελιγμένος κόσμος - πως "κατεβάζω" τον φάκελο "vivawallet-for-woocommerce"?

Αφού με καθοδηγήσετε στο να τον κατεβάσω φαντάζομαι πως μια απλή συμπίεση θα χρειαστεί και όχι κάτι εξειδικευμένο σωστά;

Αν μπορώ  επίσης να προτείνω, να ανεβάσετε ένα βίντεο στο You tube σχετικά με το πως εμείς οι "κοινοί θνητοί" εγκαθιστούμε όλο το σύστημα στη σελίδα μας χωρίς να χρειαστεί να πληρώσουμε developers κλπ.

**Comment by IoannisBark** [comment]
Με λίγο ζόρι τα κατάφερα και όλα δουλεύουν κανονικά.
Σας ευχαριστώ πολύ για την υποστήριξη.
Καλή σας μέρα.
