### ISSUE TITLE
Magento 1.9 Integration

### ISSUE THREAD

**Issue by ctzio** [VivaPayments/API#668]
Hello, 
we are trying to integrate vivapayments magento module with our client's site. We have a problem with the success and failure URL's. Using

vivawallet/hpay/hpok/
vivawallet/hpay/hpnok/

as described in the module's readme we are redirected into a 404 page. Since your instructions are not clear, do we need to add the Magento success and failure pages:

checkout/onepage/success/
checkout/onepage/failure/

Or is your module using custom URL's and which are those?

Thank you for your help
Regards

**Comment by VivaWalletSupport** [comment]
Example with URL rewrite disabled:
Success page: index.php/vivawallet/hpay/hpok/
Failure page: index.php/vivawallet/hpay/hpnok/

Example with URL rewrite enabled:
Success page: vivawallet/hpay/hpok/
Failure page: vivawallet/hpay/hpnok/

Please post a screenshot of the payment source settings and s a screenshot of the extension settings (mask Api Key) to see what might be wrong.

**Comment by ctzio** [comment]
Hello, 
I am attaching my settings
![mysettings](https://user-images.githubusercontent.com/10050863/50142734-7cefc280-02b3-11e9-8510-1a604346f6f6.png)
![magentosettings](https://user-images.githubusercontent.com/10050863/50142739-7feab300-02b3-11e9-9ebb-49c81b089323.png)

**Comment by VivaWalletSupport** [comment]
Unfortunately I cannot see much at these screenshots. Please send the images (mask only the api key) to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com and send a link to a demo product that can be purchased.

**Comment by VivaWalletSupport** [comment]
Noticed you use the language parameters in the URLs, so you would have to create 2 payment sources in you Viva account, use the source code for your Greek payment source in your Greek storeview settings, the return URLs should be gr/vivawallet/hpay/hpok/ and gr/vivawallet/hpay/hpnok/

Use the source code for your English payment source in your English storeview, the return URLs should be like envivawallet/hpay/hpok/ and en/vivawallet/hpay/hpnok/

**Comment by VivaWalletSupport** [comment]
You're welcome and please close this ticket when everything is working correctly.

**Comment by ctzio** [comment]
It seems to be working. So I am closing this ticket. Thank you very much for your help.
