### ISSUE TITLE
vivawallets bad request prestashop

### ISSUE THREAD

**Issue by belga1** [VivaPayments/API#669]

**Comment by belga1** [comment]
i am using vivpay module i have put all values after cicking for payment generate bad request how i solve issue please help and second i also install vivawallet it goese to the page where we put the card infor mation buat after its gives error transction failed and 
![002](https://user-images.githubusercontent.com/45693748/50156484-34de9900-02cf-11e9-9bd0-946041e8dbaa.png)
and second i also install vivawallet it goese to the page where we put the card infor mation buat after its gives error transction failed and 
![002](https://user-images.githubusercontent.com/45693748/50156707-bfbf9380-02cf-11e9-83fc-cee48f22b208.png)

**Comment by belga1** [comment]
these are the settings
![002](https://user-images.githubusercontent.com/45693748/50157507-e088e880-02d1-11e9-96fc-721178b2c561.png)

**Comment by belga1** [comment]
![002](https://user-images.githubusercontent.com/45693748/50157577-16c66800-02d2-11e9-931e-c18cfa4df41b.png)

**Comment by belga1** [comment]
![002](https://user-images.githubusercontent.com/45693748/50157993-27c3a900-02d3-11e9-9826-addeb5e85cb5.png)

**Comment by VivaWalletSupport** [comment]
For Vivapay please contact the modules developer for support. Regarding the vivawallet module please make sure you followed the instructions from the readme.txt file and post a screenshot from the vivawallet plugin settings (mask your api key) and from the connected payment source.

**Comment by belga1** [comment]
how to create webhook please help
Settings/API Access/Webhooks, this assures the order will be handled correctly in case the customer does not return to the estore after the transaction:
WEBHOOK URL: http(s)://(www.)your_domain.com/modules/vivawallet/webhook.php

**Comment by belga1** [comment]
![002](https://user-images.githubusercontent.com/45693748/50161386-f4394c80-02db-11e9-9910-f129476212fa.png)

**Comment by VivaWalletSupport** [comment]
In case you have solved the problem connecting your payment module I would suggest to close this issue and to open a new issue for the webhook problem.

**Comment by belga1** [comment]
thanks For help
