### ISSUE TITLE
how to verify webhook in vivawallets

### ISSUE THREAD

**Issue by belga1** [VivaPayments/API#670]

**Comment by belga1** [comment]
![002](https://user-images.githubusercontent.com/45693748/50165454-53e82580-02e5-11e9-9c96-8d6d582c9467.png)

**Comment by VivaWalletSupport** [comment]
Hello, for general information have a look at https://github.com/VivaPayments/API/wiki/Webhooks
In case you want to use the webhook in combination with a specific payment plugin, please refer to the documentation of the plugin if webhooks are supported and how to use them.

**Comment by belga1** [comment]
please i can not understand where i have to write theses codes

**Comment by belga1** [comment]
can any body help me i am stuck here please

**Comment by VivaWalletSupport** [comment]
In case custom code is used, what part from the Wiki do you not understand? In case it would have to work with a specific payment plugin, please specify for wich plugin and what is not understood about the webhook.

**Comment by belga1** [comment]
it comes to tjis page
![christian](https://user-images.githubusercontent.com/45693748/50224072-3a0a1980-039d-11e9-8416-a63913c42173.png)when we click to charge the other page for code with machine is not apper it shows payment is done but nothing is done

**Comment by belga1** [comment]
how i solve this problem

**Comment by VivaWalletSupport** [comment]
I do not see a relation with a webhook and your latest post, are you testing a payment plugin and what plugin is used?

**Comment by belga1** [comment]
vivapay

**Comment by belga1** [comment]
viva wallet both
viva pay show bad request the developer asked i have to discuss here the problem
vivawallet goes to the page to inter usenale and data but do nothing i am stuck here

**Comment by VivaWalletSupport** [comment]
I do not have any knowledge of the vivapay extension, in case you paid for it, ask the developer for support or demand a refund and use the free supported vivawallet plugin. 

Also opening issues for one problem (webhook) and then changing the subject for a problem with integrating a various payment plugins is not very effective. 

Take it step by step, fix one issue (payment plugin integration) and then proceed with posting a next issue (using webhooks).

In case you want to go further here with solving the issue to connect the vivawallet plugin, please provide a screenshot of the vivawallet plugin settings (mask api key) and a screenshot of the payment source you created in your viva payment account to connect with the vivawallet plugin. Use the readme.txt file that is included with the vivawallet plugin for your reference.

**Comment by belga1** [comment]
These are the settings
![0014](https://user-images.githubusercontent.com/45693748/50354818-03730100-054d-11e9-8910-5c20561b708d.jpg)
Module Setting
![0015](https://user-images.githubusercontent.com/45693748/50354831-0d94ff80-054d-11e9-848f-73beead636a8.jpg)

**Comment by belga1** [comment]
please tell me where i am wrong

**Comment by VivaWalletSupport** [comment]
Thank you, the info seems correct. Make a purchase with an order value over 30 cents and with a valid credit card that has sufficient funds. You can cancel the transaction afterwards from your Viva account.

**Comment by belga1** [comment]
thansk 
can you tell how i active mastereo bank transfer local for belgium thanks for help

**Comment by VivaWalletSupport** [comment]
I do not know what mastereo bank transfer is, in case it is another payment option from Prestashop I would suggest to have a look in their forum. If the vivawallet payment module works correct now, please close the issue.
