### ISSUE TITLE
πρόβλημα με 3D secure

### ISSUE THREAD

**Issue by tackou** [VivaPayments/API#671]
Καλησπέρα.
Χρησιμοποιούμε το drupal 6 - ubercart και πληρωμή με redirect.
Πελάτης, μας ενημέρωσε ότι δεν μπορεί να ολοκληρώσει την πληρωμή
με κάρτα αφού τον οδηγεί σε παράθυρο 3d secure.

Μπορείτε να μας βοηθήσετε?

![screen shot 2018-12-18 at 11 15 44 am](https://user-images.githubusercontent.com/45975999/50170875-987dbc00-02f9-11e9-844c-7e8e07c777b1.png)

**Comment by kostGX** [comment]
@tackou μέσα στο iframe που ανοίγει, φορτώνεται το 3D Secure page του card issuer, στο οποίο δεν μπορεί να έχει έλεγχο η Viva Wallet ή ο έμπορος. 

Θα πρέπει ο πελατης να δοκιμάσει με διαφορετικής τράπεζας κάρτας, ή να επικοινωνήσει με την τραπεζά του για το θέμα. Επίσης στις 3D Secure συναλλαγές μεσολαβεί και κάποιος mediator ο οποίος μπορεί να είχε πρόβλημα επικοινωνίας την στιγμή της συναλλαγής.

**Comment by tackou** [comment]
ok thanks.

Στις Δευ, 7 Ιαν 2019 στις 4:58 μ.μ., ο/η Kostas Xiradakis <
notifications@github.com> έγραψε:

**Comment by djgogos** [comment]
καλησπερα

εδω και 3 μερες εχω το ιδιο προβλημα. 

δοκιμασα και εγω με δικια μου καρτα της πειραιως και δεν μπορεσα να ολοκληρωσω την συναλλαγη.

Πως μπορει να φτιαχτει αυτο ?

ευχαριστω
