### ISSUE TITLE
ΕΡΩΤΗΣΗ ΓΙΑ MULTICURRENCY 

### ISSUE THREAD

**Issue by kwssiamp** [VivaPayments/API#672]
Καλσηπερα σας, εχω ηλεκτρονικο κατστημα και σκεφτομαι την συνεργασια με την εταιρεια σας, θα ηθελα να συνδεσω την πλατφορμα σας με το καταστημα μου! Πριν γινει αυτο εχω μια σημαντικη ερωτηση, εμεις πουλαμε κατα κυριο λογο στο εξωτερικο, πολλοι πελατες μας διαλεγουν το νομισμα τους μεσω του currency converter Που τους παρεχουμε και ολοκληρωνουν την αγορα στο δικο τους νομισμα, θα ηθελα να μαθω, εαν ενας πελατης διαλεξει δολαρια, μετα επιλεξει το προιον στην τιμη δολαριων που βλεπει, συνεχισει στο Chevkout βλεποντας παλι την ιδια τιμη, μετα ιταν παει στο δικο σας redirect page η Pop up θα βλεπει την ιδια τιμη δολαριων η το αλλαζετε εσεις αυτοματα σε ευρω! Ρωταω γιατι κατι τετοιο θα μπορουσε να δημιουργησει συγχηση στον πελατη και να χασω την αγορα! Το ιδιανικο θα ηταν να παραμενει η τιμη σε δολαρια! Με καλυπτει η υπηρεσια σας?

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
