### ISSUE TITLE
MULTICURENCY ISSUE IN CHECKOUT 

### ISSUE THREAD

**Issue by kwssiamp** [VivaPayments/API#675]
Καλσηπερα, εχω εδω και 5 μερες που εκανα  μια ερωτηση και δεν μου απαντησε κανεις! Ειμαι ηδη απογοητευμενος απο το κακο customer service σας, παρακαλω απαντηστε μου αμεσα! Το ερωτημα ειναι το εξης. Στο καταστημα μας πολλοι πελατες μας διαλεγουν το νομισμα τους μεσω του currency converter Που τους παρεχουμε και ολοκληρωνουν την αγορα στο δικο τους νομισμα, θα ηθελα να μαθω, εαν ενας πελατης διαλεξει δολαρια, μετα επιλεξει το προιον στην τιμη δολαριων που βλεπει, συνεχισει στο Chevkout βλεποντας παλι την ιδια τιμη, μετα ιταν παει στο δικο σας redirect page η Pop up θα βλεπει την ιδια τιμη δολαριων η το αλλαζετε εσεις αυτοματα σε ευρω! Ρωταω γιατι κατι τετοιο θα μπορουσε να δημιουργησει συγχηση στον πελατη και να χασω την αγορα! Το ιδιανικο θα ηταν να παραμενει η τιμη σε δολαρια! Με καλυπτει η υπηρεσια σας?

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
