### ISSUE TITLE
VivaWallet Demo Account not working with Test card details

### ISSUE THREAD

**Issue by big89** [VivaPayments/API#676]
Hello,

We are having some problem while using test card details on Viva Wallet Demo Environment.
It gives error as : The Transaction failed.
We tried many times but not working.

Recent Txn Id : 2966535932272607

Our Demo Merchant Id : 58132157-baf5-4554-8229-d95d238a64c0

Can anyone please look into this and let us know the issue on priority.

Thanks,
Logicmaker

_Originally posted by @big89 in https://github.com/VivaPayments/API/issues/278#issuecomment-448860904_

**Comment by big89** [comment]
Hello,

Yes, as per integration guide provided, we are using redirect approach to
integrate Viva Payments on Website using PHP.

We are able to create order and redirect customer to Viva secured payment
page.

When we are entering test card details, it gives mentioned error.

Can you please check logs for our demo merchant account and let me know
exact issue.

Thanks,
Logicmaker

**Comment by big89** [comment]
Hello @VivaWalletSupport and All Contributors,

We are still waiting long for your kind support on the issue we are facing.

Can any one help us.

Thanks & Regards,
Logicmaker

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!

**Comment by HumayunE** [comment]
Hello @VivaWalletSupport and All Contributors,

We are still waiting long for your kind support on the issue we are facing.
Can any one help us?

Thanks,
Heymi

**Comment by matthewrgourd** [comment]
Please share any request / response logs and we will look into for you. Also, what is the base URL you're using for your API calls?

**Comment by HumayunE** [comment]
Hi @matthewrgourd ,
Thanks for replying.

This is the base url: https://demo.vivapayments.com
 I use '/api/orders' to create order number.
Then it creates order code and redirect me to checkout.
Then I type in Test Card Details and on submit it shows this.
![Screen Shot 2019-08-06 at 1 07 10 PM](https://user-images.githubusercontent.com/10536341/62522613-76668900-b84b-11e9-99d6-713d6fc78ac1.png)
![Screen Shot 2019-08-06 at 1 07 31 PM](https://user-images.githubusercontent.com/10536341/62522628-80888780-b84b-11e9-9e21-8f2fce5ea21e.png)

**Comment by matthewrgourd** [comment]
Hi @big89 and @HumayunE this is expected behaviour with the demo card number. The transaction will work with a real card in production.

**Comment by HumayunE** [comment]
Hi @matthewrgourd Please check screenshot. There is also a link above. It is not a live situation.

**Comment by HumayunE** [comment]
second screenshot: https://user-images.githubusercontent.com/10536341/62522628-80888780-b84b-11e9-9e21-8f2fce5ea21e.png

**Comment by matthewrgourd** [comment]
@HumayunE I know, that's what I'm saying.

**Comment by big89** [comment]
This is really irrelevant answer!

@HumayunE Have you tried with any other test card details ?

Please try with below if it works :

Visa Card : 4860530113481433
Expiry : 12/19
CVV : 123

Thanks & Regards,
Logicmaker

**Comment by big89** [comment]
BTW, when we enter card details and proceed, it get stuck on below URL :

http://127.0.0.1:8090/PaymentServiceProviders//frontcontroller?t=68407035-6d90-400b-a4f8-91701e48117f&s=2598538946872607&lang=el-GR&eventId=10051&eci=2

@matthewrgourd  Check if any problem on payment gateway demo environment setup and its working fine at this moment.

Better if you share working details with us here.

Thanks & Regards,
Logicmaker

**Comment by HumayunE** [comment]
@big89 Now they have fixed it but now it redirects to a failure url only..

Check this, I have mentioned this issue here:
https://github.com/VivaPayments/API/issues/1135

Thanks!
