### ISSUE TITLE
Viva error: no order code received

### ISSUE THREAD

**Issue by mparcharidis** [VivaPayments/API#677]
Καλησπέρα σας,
στο ηλεκτρονικό κατάστημα domain.gr έχουμε εγκαταστήσει ένα premium plug in τις obs technologies για woocommerce sites. Το πρόβλημα είναι ότι ενώ είναι όλα ρυθμισμένα σωστά και από το διαχειριστικό της viva αλλά και στο Plug in οι πληρωμές δε λειτουργούν και κατά την παραγγελία εμφανίζεται το παρακάτω μήνυμα "Viva error: no order code received".

Αρχικά βάλαμε τα default στοιχεία για σύνδεση αλλά μετέπειτα ενώ δε λειτουργούσε δημιουργήσαμε μία νέα έγγραφή από το διαχειριστικό της viva αλλά και πάλι τα ίδια. Το θέμα είναι ότι δοκιμάσαμε με ένα demo λογαριασμό που είχαμε της viva και έπαιξε κανονικά, αλλά με τον πραγματικό λογαριασμό του πελάτη δε παίζει.
Θα μπορούσατε να μας κατευθύνεται λίγο, διότι ο κατασκευαστής του plug in μας ενημέρωσε ότι είναι θέμα με τον λογαριασμό της viva, σας ευχαριστούμε.

**Comment by VivaWalletSupport** [comment]
Hello mparcharidis, see now you are using the supported plugin, in case you do have any issues with it please close this ticket, otherwise let me know.
