### ISSUE TITLE
Problem with VivaWallet redirection 

### ISSUE THREAD

**Issue by ATENEAGR** [VivaPayments/API#678]
Hello! I have a Shopify account and a site www.atenea.gr I have all the token and ID and the logo of Viva payments appears good on my site ... BUT.. When a customer goes to use Viva Payments and the site redirects him to the site of Viva it doesn’t work and gives a message “ERROR INPUT IS INVALID” please let me know if you can help me !!

**Comment by matthewrgourd** [comment]
Hi there, apologies for the lack of reply previously. I'm assuming you managed to solve this issue somehow but please let me know if not. Thanks!

**Comment by ATENEAGR** [comment]
All good and clear 

thanks 

                             www.atenea.gr

                         Co-Founders since 2018

Dr. Charalampos T.A. Papadimitriou M.D.
Sommelier 
Wines • Spirits • Coffee 

Tatyana López Masih
