### ISSUE TITLE
Payment confirmation email sent in Greek - needs to be in English

### ISSUE THREAD

**Issue by john-antunes** [VivaPayments/API#679]
Hi,

Please can you help me. We have recently integrated Viva Wallet with our Shopify site (www.theleafco.com). Today we had our first customer process their payment using Visa Wallet but their confirmation of payment came through to them all in Greek. Please can you let us know what needs to be done (or if you can change it) so that all confirmations from our store go to the customer in English?

I look forward to your reply
John

**Comment by kostGX** [comment]
Solved by referenced issue.
