### ISSUE TITLE
NO REPLY IN 2 DAYS: Payment confirmation email sent in Greek - needs to be in English #679

### ISSUE THREAD

**Issue by john-antunes** [VivaPayments/API#680]
Hi,

2 days ago I logged the request below and have yet to receive a reply. This is already after having logged the issue 2 weeks ago with support@vivawallet. Can someone please help me with this??

--------------------------
Hi,
Please can you help me. We have recently integrated Viva Wallet with our Shopify site (www.theleafco.com). Today we had our first customer process their payment using Visa Wallet but their confirmation of payment came through to them all in Greek. Please can you let us know what needs to be done (or if you can change it) so that all confirmations from our store go to the customer in English?
I look forward to your reply
John

**Comment by kostGX** [comment]
Hello @john-antunes and happy 2019. Can you please check the Preferred Language in your settings and make sure it's set to English?

Thanks

![preferred language](https://user-images.githubusercontent.com/3908736/50766594-851f9a00-1282-11e9-82cc-5093b9adfcf2.jpg)

**Comment by john-antunes** [comment]
Hi

Thanks for the reply. I don’t know where to find ‘local language’ in settings – please can you tell me where I find that setting?

Thanks
John

**Comment by john-antunes** [comment]
This has now been done, many thanks

**Comment by platawellness** [comment]
@kostGX Hi, I have checked that the preferred language is set to English as per the image below however, the payment confirmation to the customer from Viva is still in Greek.

<img width="386" alt="screenshot 2019-01-23 at 10 38 22" src="https://user-images.githubusercontent.com/46958111/51600958-18033a00-1efb-11e9-98d1-563ea1f61068.png">

<img width="773" alt="screenshot 2019-01-23 at 09 44 23" src="https://user-images.githubusercontent.com/46958111/51600984-25202900-1efb-11e9-8bcc-9d92b3818c13.png">

Please advise.

Jon

**Comment by platawellness** [comment]
@john-antunes did you get this sorted?

**Comment by john-antunes** [comment]
I've made the change so will let you know if any customer says otherwise, thanks

**Comment by platawellness** [comment]
I’ve made the change and same thing happens.

Jon

On 23 Jan 2019, at 11:15, john-antunes <notifications@github.com<mailto:notifications@github.com>> wrote:


I've made the change so will let you know if any customer says otherwise, thanks
