### ISSUE TITLE
Hikashop

### ISSUE THREAD

**Issue by andreas444** [VivaPayments/API#681]
Καλησπέρα και καλή χρονιά. Έχω εγκαταστήσει επιτυχώς το plugin της Viva Payments για το Hikashop αλλά προσπαθώ να κάνω μια συναλλαγή και δεν προχωρά η διαδικασία. Κολλάει στο σύνδεσμο https://agronomist.gr/component/hikashop/checkout/task-step/step-1?Itemid=1101 και μου δείχνει άσπρη οθόνη.
Η παραγγελία δημιουργείται κανονικά και λαμβάνω email σχετικό.
Μήπως μπορείτε να με βοηθήσετε;
Ευχαριστώ εκ των προτέρων.

**Comment by VivaWalletSupport** [comment]
Hello and best wishes for 2018. A white page usually indicates a fatal error, please investigate you PHP error log to see what is hapening.

**Comment by VivaWalletSupport** [comment]
Hello andreas444, please close the ticket in case the problem has been resolved, otherwise let me know when you any other problem.
