### ISSUE TITLE
Joomshopping

### ISSUE THREAD

**Issue by andreas444** [VivaPayments/API#682]
I can't install joomshopping plugin. Could you send me this plugin?

Thank you in advance.

**Comment by VivaWalletSupport** [comment]
You can download all the code from https://github.com/VivaPayments/API/archive/master.zip and remove everything that is not needed from the zipped file.
[joomshopping_viva.zip](https://github.com/VivaPayments/API/files/2727195/joomshopping_viva.zip)

**Comment by andreas444** [comment]
Happy new year :-) Unfortunately I'm still not able to install the plugin . Message received: Unable to find install package

**Comment by VivaWalletSupport** [comment]
Did you install according the install.txt ?

**Comment by andreas444** [comment]
I'm sorry, I didn't see it. Its all perfect, thank you for your support.

**Comment by VivaWalletSupport** [comment]
Hello andreas444, please close the ticket in case the problem has been resolved, otherwise let me know when you any other problem.

**Comment by andreas444** [comment]
Hello. I installed succesfully the plugin but i can't finish the payment. I'm receiving a 1054 error. The link: https://agronomist.gr/component/jshopping/checkout/step6?Itemid=0

**Comment by VivaWalletSupport** [comment]
That error seem to be related to mysql, could you email FTP and administrator access to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com to have a look at it?

**Comment by andreas444** [comment]
Ok I've just sent the email.
Thank you for your support.

**Comment by VivaWalletSupport** [comment]
Thank you, will inform you when done.

**Comment by VivaWalletSupport** [comment]
Looks like the problem occurs because you installed multiple Joomla modules (JoomShopping / Hikashop) so that a problem with the database table occured. Remove the modules, remove the database table (#__vivadata) manually and install again the module that is going the be used (eirher Hikashop or JoomShopping). In case you need both modules working in one installation you would have to modify one module to use a different database table name.

**Comment by andreas444** [comment]
I removed the 2 modules but I can't find vivadata table 🙁

**Comment by VivaWalletSupport** [comment]
In case the table was dropped by uninstalling the modules, it is ok. Install the Joomshopping module or the Hikashop module and check afterwards if the table has been created.

**Comment by andreas444** [comment]
I did it :+1: 
Thank you so much for your assistance.
