### ISSUE TITLE
Wrong Redirection Link

### ISSUE THREAD

**Issue by Eternity022** [VivaPayments/API#684]
Hello ,

We are facing an issue with the redirection link from viva payments site. Our customers is completing the orders , paying the amount , but when the redirection comes we face the issue. We have state that the redirection link is xxxx.gr/index.php?route=checkout/success&token= and your system redirects our clients to https://xxx.gr/index.php?route=checkout/success&token=&t=xxxxx&s=xxxxxxx&lang=el-GR.

What is going on?

**Comment by matthewrgourd** [comment]
Apologies for the lack of reply. I assume this isn't a problem now so am closing the issue. Obviously do let us know if anything else comes up!
