### ISSUE TITLE
VivaWallet Payment WooCommerce Not Working

### ISSUE THREAD

**Issue by c0mpute** [VivaPayments/API#685]
Hi,

I have 2 WooCommerce websites that I am trying to use Viva Wallet for. I have the standard settings with redirection, and followed all the instructions. I know it used to work the last time I was trying to use it with one of my sites, but now I have a new account and newer Wordpress/WooCommerce version and it doesn't work anymore.

For both websites after I select Viva Wallet as a checkout option and click pay now, I get sent to a blank page that says "please click the button below to pay", and there is no button or anything else. Just a page with my site's header, the order details, this message and blank space.

Also, for the test mode it doesn't work at all, when I click pay now I just get thrown to a blank page with nothing other than an Error message displayed.

The websites have different Wordpress/WooCommerce versions. One is Wordpress v 5.0.2 and WooCommerce v 3.5.3 and the other is Wordpress v 4.9.9 and WooCommerce v 3.5.2.

From the looks of it the WooCommerce plugin hasn't been updated in 6 months, so it's probably some compatibility issues since it was working a few months ago for an earlier version of 
Wordpress/WooCommerce. Could you please look into it and update the plugin?

PS: By the way, I recently had the same exact problem when trying to pay on a different unrelated website that probably had a different payment gateway, but the problem was identical. I'm guessing the last couple of Wordpress/WooCommerce versions have changed the checkout functionality and not all gateway developers have caught on yet.

Thank you.

**Comment by c0mpute** [comment]
After looking through error logs, it seems I have found the error:

2019-01-07T20:39:58+00:00 CRITICAL Uncaught Exception: Unable to create order code (Person [redacted_uid] does not support currency '978') in /[redacted_path]/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php:357

Can Viva Wallet really not process payments in different currencies than your main country's currency? The company is in Romania and the only currency enabled on my account is RON, but I don't even take RON payments, I take GBP and EUR. Is there nothing to be done?

**Comment by matthewrgourd** [comment]
Hello Steve, for the transaction at Viva only the currency is supported from the country your company is registered in. In case this would be Romania, only the RON currency would be allowed. For WooCommerce there are various plugins available that are able to convert other currencies to EURO or GBP in the checkout stage. You would need to do a search here: https://woocommerce.com/product-category/woocommerce-extensions

**Comment by geokir** [comment]
Hello, I have the same problem. I have tried some currency converters but I want that to be done automatically in the background and not to have my clients choose to pay in another currency than they see.

Any help?
