### ISSUE TITLE
issues with woocommerce and viva wallet

### ISSUE THREAD

**Issue by alextovey** [VivaPayments/API#686]
Hi,

We are running woocommerce on wordpress 5.0.2 The plugin test mode does not work and viva wallet webhook keeps failing when we are trying to add this. We need to be able to setup the webhook and do testing before it goes live so customers can start to use this.
attached is the output from woocommerce status.
and a image from the webhook section.
![capture](https://user-images.githubusercontent.com/22075161/50825922-392c2e00-1332-11e9-85ab-ef190f041d52.PNG)
[status report.txt](https://github.com/VivaPayments/API/files/2736353/status.report.txt)

**Comment by VivaWalletSupport** [comment]
Hello, to start with the demo mode, what problem(s) are you having there?

**Comment by alextovey** [comment]
We just get a white page with"Bad Request" in the top left.

**Comment by VivaWalletSupport** [comment]
Could you post me for this environment (http://demo.vivapayments.com) following screenshots?
1. Plugin configuration settings (mask the api key)
2. Payment source settings
3. Payment sources listing (including browser URL)

**Comment by alextovey** [comment]
That works using demo.vivapayments.com however i still cant get webhooks towork either in demo or live version. :(

**Comment by VivaWalletSupport** [comment]
I do not see the URLs in the screenshots as asked for (to verify you are working in the demo environment), but looking at the merchantid you posted from the API access / general page and your plugin settings you seem to mix the demo with the live account. 

Please correct this and only use credentials from the demo account in your plugin settings and work from the demo environment to add the webhook.

**Comment by alextovey** [comment]
I started doing the live account after the demo worked. bar the webhook./

**Comment by VivaWalletSupport** [comment]
Can we finish the verification in the demo account before we move on?

**Comment by alextovey** [comment]
Okay. two mins

**Comment by alextovey** [comment]
![capture](https://user-images.githubusercontent.com/22075161/50836060-30e2eb80-1350-11e9-8fad-bd3911cf6616.PNG)
![capture1](https://user-images.githubusercontent.com/22075161/50836061-30e2eb80-1350-11e9-948e-c2ccc8725068.PNG)
![capture2](https://user-images.githubusercontent.com/22075161/50836062-30e2eb80-1350-11e9-9cfe-e1cd42613976.PNG)


All matching as asked.

**Comment by VivaWalletSupport** [comment]
Still having a problem when adding the webhook URL from the demo account?

**Comment by alextovey** [comment]
Yes still the same problem as above. I'll try again that is the right link for it?

**Comment by alextovey** [comment]
All working on the live environment now too. You should add about the demo bit on the git.
