### ISSUE TITLE
Render button multiple times with ng-if

### ISSUE THREAD

**Issue by AristotelisGarro** [VivaPayments/API#687]
Γεια σας αντιμετωπίζω πρόβλημα χρησιμοποιώντας το Simple Checkout σε AngularJS application. 
Το κουμπί περιέχει ng-if για να δημιουργείται υπό περιπτώσεις μετά από κάποια επιλογή του χρήστη. 

Την πρώτη φορά που αρχικοποιείται το κουμπί και γίνεται render μέσω της function window.VivaPayments.Simple.initSimple() εισάγεται το <iframe> στο DOM, το κουμπί εμφανίζεται και λειτουργεί κανονικά και παρατηρώ ότι στο αρχείο "https://demo.vivapayments.com/web/checkout/js" τα intervals φορτώνονται και δουλεύουν σωστά.

 Αν λόγο του ng-if το κουμπί σβηστεί και ξανά ανοίξει  γίνεται render πάλι με αποτέλεσμα να έχω αρκετά <iframe> στην σελίδα μου τα οποία ανοίγουν όλα μαζί το ένα πίσω από το άλλο. 

Δοκίμασα να αφαιρέσω τα <iframe> πριν γίνει render πάλι το κουμπί, αλλά μένουν τα προηγούμενα intervals χωρίς να γίνονται clear με αποτέλεσμα να παίρνω errors.
```
Uncaught TypeError: Cannot read property 'postMessage' of null
    at d (js:formatted:268)
    at js:formatted:303
```
Υπάρχει κάποιος τρόπος να αφαιρώ τα <iframe> όταν το κουμπί παύει να υπάρχει?
Σε άλλη περίπτωση υπάρχει κάποιος τρόπος να σταματήσω μόνο τα συγκεκριμένα intervals ώστε αυτά να μην μου δημιουργούν τα errors μόλις ξανά φτιαχτεί?

**Comment by matthewrgourd** [comment]
Hi there, apologies for the lack of response previously. There are known issues with Simple Checkout due to its use of an iframe. We recommend that those affected try [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) instead. Thanks!
