### ISSUE TITLE
Using Port in url settings VivaWallet

### ISSUE THREAD

**Issue by makistank** [VivaPayments/API#688]
Hello my implementation is under a different port than 80 so my success and fail urls must be in a format like : http://mydomain.com:8080/success.php and so on. I try to add my full url with port together but with no luck as the administration panel remove the : and collapse the port to my url. The same thing happen ig i try to add before success url the port (:8080/success.php) the result is to save it as /8080/success.php.

Is any way to support :portnumber after the url of implementation?

Thanks in advanced

**Comment by matthewrgourd** [comment]
Hi there, could you let me know if you're attempting to implement Redirect Checkout or one of the e-commerce plugins. If the latter, which one? Thanks!

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
