### ISSUE TITLE
Simple checkout form Order with code 0 was not found

### ISSUE THREAD

**Issue by Cristinawork** [VivaPayments/API#690]
Using the viva simple checkout, making the API call at https://www.vivapayments.com/api/transactions, I always get this response from viva, it is like viva doesn't receive anything from the form, no amount, nothing. (for using this method should I enable Native checkout in Viva Wallet customers settings? I tryied both anyway)

viva api response
{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ErrorCode":404,"ErrorText":"Order with code 0 was not found","TimeStamp":"2019-01-09T19:05:15.673329+02:00","CorrelationId":null,"EventId":2,"Success":false}

*if someone answers, can use greek lang

**Comment by Cristinawork** [comment]
ετσι ειναι η σελίδα, λείπει κάτι και to response είναι πάντα 0 ?

<?php 
if (isset($_POST['vivaWalletToken'])) {

$request =  'https://www.vivapayments.com/api/transactions';	
$MerchantId = '******************';
$APIKey = '*****';
$PaymentToken=$_POST['vivaWalletToken'];

$postargs = 'PaymentToken='.$PaymentToken;

$session = curl_init($request);

curl_setopt($session, CURLOPT_POST, true);
curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
curl_setopt($session, CURLOPT_HEADER, true);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

$response = curl_exec($session);
curl_close($session);

}
?>
<!DOCTYPE html> 
<html lang="en"> 
<head> <meta charset="UTF-8"> <title>Simple checkout</title> </head> 
<body> 

<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script> 
<script src="https://www.vivapayments.com/web/checkout/js"></script> 

<form id="myform" action="" method="post"> 
<button type="button" 
data-vp-publickey="********************" 
data-vp-merchantref="8796669583648"
data-vp-baseurl="https://www.vivapayments.com" 
data-vp-lang="en" 
data-vp-amount="100" 
data-vp-description="My product"> 
</button> 
<input type="hidden" name="vivaWalletToken" id="vivaWalletToken">
</form> 

</body> 
</html>

**Comment by Cristinawork** [comment]
κοπηκε ο κωδικας βλέπω
τμηματικα

php

if (isset($_POST['vivaWalletToken'])) {

$request =  'https://www.vivapayments.com/api/transactions';	
$MerchantId = '******************';
$APIKey = '*****';
$PaymentToken=$_POST['vivaWalletToken'];

$postargs = 'PaymentToken='.$PaymentToken;

$session = curl_init($request);

curl_setopt($session, CURLOPT_POST, true);
curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
curl_setopt($session, CURLOPT_HEADER, true);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

$response = curl_exec($session);
curl_close($session);

}

**Comment by Cristinawork** [comment]
meta forma

<script src="https://code.jquery.com/jquery-1.11.2.min.js"></script> 
<script src="https://www.vivapayments.com/web/checkout/js"></script> 

<form id="myform" action="" method="post"> 
<button type="button" 
data-vp-publickey="********************" 
data-vp-merchantref="8796669583648"
data-vp-baseurl="https://www.vivapayments.com" 
data-vp-lang="en" 
data-vp-amount="100" 
data-vp-description="My product"> 
</button> 
<input type="hidden" name="vivaWalletToken" id="vivaWalletToken">
</form>

**Comment by Cristinawork** [comment]
forma sketi

<form id="myform" action="" method="post"> 
<button type="button" 
data-vp-publickey="********************" 
data-vp-merchantref="8796669583648"
data-vp-baseurl="https://www.vivapayments.com" 
data-vp-lang="en" 
data-vp-amount="100" 
data-vp-description="My product"> 
</button> 
<input type="hidden" name="vivaWalletToken" id="vivaWalletToken">
</form>

**Comment by Cristinawork** [comment]
δεν τη πηρε, πως θα δουμε αν ειναι σωστη?

**Comment by Cristinawork** [comment]
Χρησιμοποιώ την φόρμα Simple checkout https://github.com/VivaPayments/API/wiki/Simple-Checkout
Η φόρμα φαίνεται να λειτουργεί, εμφανίζει το popup για πληρωμή αλλά η χρέωση δεν γίνεται.
Στέλνω το PaymentToken και τα στοιχεία που χρειάζονται στο https://www.vivapayments.com/api/transactions αλλά το response δείχνει ότι δεν λαμβάνει ούτε το ποσό, ούτε τίποτα άλλο.
Response που λαμβάνω από Viva wallet api
{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ErrorCode":404,"ErrorText":"Order with code 0 was not found","TimeStamp":"2019-01-07T17:54:18.8724023+02:00","CorrelationId":null,"EventId":2,"Success":false}
 
Πως δεν επιστρέφει το Amount, αφού το στέλνω πχ για 1 ευρω
data-vp-amount="100"

**Comment by Cristinawork** [comment]
Καλησπέρα, 
Ναι, προσπάθησα να εισάγω εδώ όλο τον κώδικα, αλλά τον κόβει.
Οπότε το έβαλα σε ένα test δικό μου:
https://www.ellasan.gr/sites/eshop.net/test 
Το δοκίμασα και σε Demo και σε Production. Δοκίμασα και με το Native checkout enabled & disabled.
Δοκιμές με production κωδικούς πελάτη και urls.

**Comment by kostGX** [comment]
@Cristinawork τον είδα τον κώδικα.

Επιβεβαιώστε πως ως Public Key βάζεται αυτό που βλέπουμε στο παρακάτω screenshot:
![https___members_vivawallet_com_selfcare_en-gb_security_apiaccess](https://user-images.githubusercontent.com/3908736/51746235-1168f400-20ae-11e9-8b1e-b5064ddfc125.jpg)

Έχετε κάνει δοκιμή με καρφωτές τιμές αντί να τις κάνετε echo δυναμικά μέσω PHP για να βεβαιωθείτε πως δουλεύει; Στο data-vp-amount βλέπω πως κάνετε echo και κάποια 00 μετα το ποσό.

Προτείνω να δοκιμάσετε με καρφωτές/στατικές τιμές -- όχι δυναμικές -- να δείτε πως συνεχίζει το flow και στην συνέχεια να πάτε να κάνετε δυναμικές μια μια τις data-vp τιμές της φόρμας ώστε να κάνετε debug.

**Comment by Cristinawork** [comment]
Ναι, τα βαζω όλα τα στοιχεία ακριβώς, public key, merchant id κλπ. οπως ειναι στην απεικόνηση πανω.
Και ναι, δοκίμασα και καρφωτα στατικά χωρις php echo όλα αυτά. Κατι πρέπει να μου ξεφεύγει, αλλα τι...?
Ετοιμαζω τωρα το τεστ στην σελιδα που σας εστeιλα το link, να δειτε και εσεις live τι γινεται.
Και φερνω και το viva response (προφανως συνδεεται στο api αφου υπάρχει καποιο response)
Θα επανελθω σε λιγο.
Ευχαριστώ πολύ πάντως.
Χριστίνα

**Comment by Cristinawork** [comment]
Και ναι, ξέρω, το ποσό και μετά 2 μηδενικά, πχ για 1 ευρω βαζω 100 και όντος στο popup φαινεται οτι το πηρε σωστά, και το ποσο και την επιχειρηση - merchant

**Comment by Cristinawork** [comment]
Αν μπορείτε, πηγαίνετε στην σελιδα μου τεστ, βαλτε στο καλαθι το πρωτο προιον Test product 1 euro και προσπαθήστε να κάνετε την αγορα με την δοκιμαστικη καρτα viva 4111 1111 1111 1111
* συνδεθειτε με τα δοκιμαστικα email & pass που ειναι πανω στη 1 σελιδα
https://www.ellasan.gr/sites/eshop.net/
Αφου κάνετε την εικονική αγορά θα δείτε το response

**Comment by kostGX** [comment]
@Cristinawork το είδα. Το κοιτάω κι εγώ να δω τι γίνεται. Βλεπω η Simple Checkout παίζει με Demo περιβάλλον.

To API Base URL που κάνετε POST στο /api/transactions ποιο είναι;

Πρέπει να ποστάρετε στο https://demo.vivapayments.com (demo) και όχι https://www.vivapayments.com

Επιβεβαιώστε παρακαλώ σύμφωνα και με το τελευταίο step πως είναι όλα γυρισμένα σε demo.

Ευχαριστώ

https://github.com/VivaPayments/API/wiki/Simple-Checkout#switching-from-demo-to-live-production-environment

**Comment by Cristinawork** [comment]
Ολα παιζουν σε production περιβάλλον, και η φορμα Simple checkout και το API call με πραγματικά στοιχεία του πελάτη.
Θέλετε να το γυρίσω όλο σε demo, μπορω, αλλά θα μας βοηθησει να δουμε κατι παραπανω?

**Comment by kostGX** [comment]
Αφού όλα κοιτάνε παραγωγή θα πρέπει να δοκιμάσετε με παραγωγική κάρτα (μια κανονική mastercard ή visa) και όχι με δοκιμαστική 4111 1111 1111 1111 (κάποιο υπόλοιπο του demo πρέπει να υπάρχει). Στην πορεία μπορείτε να κάνετε Cancel/Refund από το διαχειριστικό για να επιστραφούν τα χρήματα.

Βεβαιωθείτε πως το amount είναι μεγαλύτερο απο 30 cents.

Κάτι πρέπει να έχει ξεφύγει δεδομένου πως δέχεται την Demo κάρτα σε παραγωγή.

**Comment by Cristinawork** [comment]
Εκανα μολις τεστ με πιστωτική 1 ευρω αλλά δεν πέτυχε, το ίδιο response, ολα είναι null

HTTP/1.1 200 Order with code 0 was not found Date: Fri, 25 Jan 2019 15:33:31 GMT Server: Microsoft-IIS/10.0 Strict-Transport-Security: max-age=15768000 Content-Type: application/json; charset=utf-8 X-Viva-EventId: 2 X-Viva-CorrelationId: 19-025-D60DBB3 Content-Length: 319 {"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ErrorCode":404,"ErrorText":"Order with code 0 was not found","TimeStamp":"2019-01-25T17:33:31.7571483+02:00","CorrelationId":null,"EventId":2,"Success":false}

**Comment by Cristinawork** [comment]
μήπως χρειαζόμαστε κάποια άλλη ρύθμιση στο ιδιο το viva account, κάτι ίσως δεν είναι ενεργοποιημένο?
native checkout το ενεργοποίησα, ετσι πηρα και τα στοιχεια

**Comment by Cristinawork** [comment]
κοιτάω παντού να δω υπόλοιπα του demo
στην φορμα ειναι μονο αυτα
1.
data-vp-baseurl="https://demo.vivapayments.com" (δεν το εβαλα καθολου, λενε οι οδηγιες οτι
If no value is set, Production environment is assumed. )
2. 
<script src="https://demo.vivapayments.com/web/checkout/js"></script>
που το αλλαξα σε
<script src="https://www.vivapayments.com/web/checkout/js"></script>

κι στο api call μονο το url
αυτο ειναι σωστο production api url ?
https://www.vivapayments.com/api/transactions

**Comment by Cristinawork** [comment]
εβαλα στο τεστ στη 1 σελίδα φωτο με τις ρυθμισεις στο business account viva, να δουμε μηπως λειπει κατι απο εκει

**Comment by Cristinawork** [comment]
Καλημέρα, μήπως έχουμε κανένα νέο, το είδατε?

**Comment by donfn** [comment]
Έχω ασχοληθεί και γώ με το Simple Checkout και μου ψιλοέβγαλε την πίστη μέχρι να το καταφέρω..Ορίστε τι έχω γράψει:
```
$MerchantId = ΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧ;
$APIKey = ΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧ;		
		
$session = curl_init($this->requesturl.'/api/transactions');
curl_setopt( $session, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
curl_setopt($session, CURLOPT_POSTFIELDS, json_encode(array("PaymentToken" => $_POST['vivaWalletToken'])));
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, htmlspecialchars_decode($MerchantId) . ':' . htmlspecialchars_decode($APIKey));
$response = curl_exec($session);
curl_close($session); 
```

Δώσε μεγάλη βάση στοjson_encode(array("PaymentToken" => $_POST['vivaWalletToken'])) , καθώς μόνο υπό αυτή τη μορφή (για μένα τουλάχιστον) το δεχεται ο σέρβερ... Αν είσαι σε Wordpress, μπορείς να πάρεις κατευθείαν το plugin που έχω γράψει για να μην παιδεύεσαι https://wordpress.org/plugins/viva-payments-simple-checkout/

**Comment by donfn** [comment]
Δοκίμασε:

```
$MerchantId = ΧΧΧΧΧΧΧΧΧΧΧΧΧ;
$APIKey = ΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧΧ;
					
$session = curl_init('https://ΧΧΧΧ.vivapayments.com/api/transactions');
curl_setopt( $session, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
curl_setopt($session, CURLOPT_POSTFIELDS, json_encode(array("PaymentToken" => $_POST['vivaWalletToken'])));
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, htmlspecialchars_decode($MerchantId) . ':' . htmlspecialchars_decode($APIKey));
$response = curl_exec($session);
curl_close($session);
```

**Comment by Cristinawork** [comment]
Ευχαριστώ πολύ, τα δοκίμασα ακριβώς έτσι αλλά παίρνω πάντα το response ...Order with code 0 was not found...
Μήπως πρέπει να στείλω και το order code με κάποιο τρόπο? 
(δεν ειναι Wordpress)

**Comment by Cristinawork** [comment]
Τώρα εχω κάνει αλλαγές (δεν ήθελε hidden field στην φόρμα ) και κάτι μου γυρίσει στο response, τα περισσότερα δεδομένα, το ποσό κλπ., δεν δειχνουν πλέον ολα null, αλλα ακομη ειναι Transaction failed, Error code 502

{"Emv":null,"Amount":1.00,"StatusId":"E","CurrencyCode":"978","TransactionId":"33d8caa5-10a0-461f-8f6e-832d50fca750","ReferenceNumber":731854,"AuthorizationId":null,"RetrievalReferenceNumber":"908508731854","ErrorCode":502,"ErrorText":"Transaction failed","TimeStamp":"2019-03-26T10:51:10.7058478+02:00","CorrelationId":null,"EventId":10051,"Success":false}

**Comment by Cristinawork** [comment]
Είναι οκ τώρα, δεν ηθελε το hidden field token στην φόρμα όπως το περιγραφουν στις οδηγίες, αυτό δεν το στέλνουμε εμείς, το παράγει το σύστημα viva και εμείς το καλούμε. 
"After selecting the payment method and filling in the necessary fields, paymentForm is submitted to the URL defined in the action attribute along with vivaWalletToken, a hidden <input> field. "
Εσβησα τα τεστ που είχαμε κάνει.
I'm closing the issue
