### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by AbsoluteDigitalMedia** [VivaPayments/API#691]
We have installed and configured the module for Magento 2 onto the website and it appears that when we go and place a to test payment, we are receiving the following error:
 
[09-Jan-2019 20:52:06 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getBaseCurrencyCode() on null in /home/cafeafdd/public_html/app/code/Ced/VivaPayments/Model/PaymentMethod.php:281
Stack trace:
#0 /home/cafeafdd/public_html/vendor/magento/module-sales/Model/Order/Payment.php(353): Ced\VivaPayments\Model\PaymentMethod->validate()
#1 /home/cafeafdd/public_html/vendor/magento/module-sales/Model/Order.php(873): Magento\Sales\Model\Order\Payment->place()
#2 /home/cafeafdd/public_html/vendor/magento/module-sales/Model/Order.php(1080): Magento\Sales\Model\Order->_placePayment()
#3 /home/cafeafdd/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()
#4 /home/cafeafdd/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent('place', Array)
#5 /home/cafeafdd/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()
#6 /home/cafeafd in /home/cafeafdd/public_html/app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 281

Would you be able to provide me with feedback on how to resolve this error?

**Comment by VivaWalletSupport** [comment]
Hello, what version of Magento 2 is used?

**Comment by AbsoluteDigitalMedia** [comment]
Hi, thank you for your reply.

We are currently using Magento 2.2.7 and we was sent the following link to the module:

https://github.com/VivaPayments/API/tree/master/Plugins/magento/magento2_vivawallet/Ced/VivaPayments

**Comment by VivaWalletSupport** [comment]
Thank you, I will have a look at it.

**Comment by VivaWalletSupport** [comment]
Replace the Ced\VivaPayments\Model\PaymentMethod.php with the one from attached package.
[magento2_vivawallet.zip](https://github.com/VivaPayments/API/files/2746186/magento2_vivawallet.zip)

**Comment by VivaWalletSupport** [comment]
In case the problem has been solved, please close this issue, otherwise let me know how I can help any further.

**Comment by AbsoluteDigitalMedia** [comment]
Hi,

Thank you for sending us the code replacement, this resolve the PHP error, however, we are now receiving the below error:

{"0":"Notice: Trying to get property of non-object in \/home\/cafeafdd\/public_html\/app\/code\/Ced\/VivaPayments\/Model\/PaymentMethod.php on line 202","1":"#0 \/home\/cafeafdd\/public_html\/app\/code\/Ced\/VivaPayments\/Model\/PaymentMethod.php(202): Magento\\Framework\\App\\ErrorHandler->handler(8, 'Trying to get p...', '\/home\/cafeafdd\/...', 202, Array)\n#1 \/home\/cafeafdd\/public_html\/app\/code\/Ced\/VivaPayments\/Controller\/Checkout\/Start.php(40): Ced\\VivaPayments\\Model\\PaymentMethod->getPostHTML(Object(Magento\\Sales\\Model\\Order\\Interceptor))\n#2 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/App\/Action\/Action.php(107): Ced\\VivaPayments\\Controller\\Checkout\\Start->execute()\n#3 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->___callParent('dispatch', Array)\n#5 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/home\/cafeafdd\/public_html\/generated\/code\/Ced\/VivaPayments\/Controller\/Checkout\/Start\/Interceptor.php(26): Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->___callPlugins('dispatch', Array, Array)\n#7 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/App\/FrontController.php(55): Ced\\VivaPayments\\Controller\\Checkout\\Start\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#10 \/home\/cafeafdd\/public_html\/vendor\/magento\/module-store\/App\/FrontController\/Plugin\/RequestPreprocessor.php(94): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#11 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/home\/cafeafdd\/public_html\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(73): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#13 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#14 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#15 \/home\/cafeafdd\/public_html\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#16 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#17 \/home\/cafeafdd\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(257): Magento\\Framework\\App\\Http->launch()\n#18 \/home\/cafeafdd\/public_html\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#19 {main}","url":"\/vivapayments\/checkout\/start","script_name":"\/index.php"}

**Comment by VivaWalletSupport** [comment]
Seems you have a problem connecting to Viva, are you in the demo mode?

**Comment by AbsoluteDigitalMedia** [comment]
We aren't in the demo version, please attached screenshot.
![screen shot 2019-01-14 at 09 37 08](https://user-images.githubusercontent.com/46559082/51105197-3fae2000-17e0-11e9-808c-74c419ef7489.png)

**Comment by VivaWalletSupport** [comment]
I would advise to change you API key as it should not be known to others. Correct the used URLs (ordercode,gateway,transaction) in your settings to include the www part.
