### ISSUE TITLE
Credit Card installments

### ISSUE THREAD

**Issue by mvoreadi** [VivaPayments/API#693]
dmihos Γειά σας.  Έχω το API του Shopify στο eshop μου για πληρωμές με πιστωτική κάρτα μέσω Viva. Μπορώ να βάλω την επιλογή δόσεων;

To eshop μου είναι το Anthoshop.gr και το merchant id: CDDD3A5E-DE9E-4B14-9CDA-FD1E861907E3.
Ευχαριστώ,
Μαριλένα Βορεάδη

**Comment by mvoreadi** [comment]
dmihos Θα μπορούσατε να μου απαντήσετε παρακαλώ;

**Comment by dmihos** [comment]
Γεια σας, προς το παρόν, το shopify δε μας δίνει τη δυνατότητα να ορίζει ο έμπορος αν θέλει δόσεις για μια παραγγελία ή όχι.
