### ISSUE TITLE
PHP Native checkout

### ISSUE THREAD

**Issue by CodeScroll** [VivaPayments/API#695]
Hello, i try to run the NativeCheckout/PHP/web/ and i get that Error(photo in link). Why ? How to make a transaction ? 

[https://prnt.sc/m6eaz2](url)

**Comment by kostGX** [comment]
Hello,

Please make sure you've enabled Native Checkout in both your API Access and Websites/Apps settings as shown below

![api access native checked](https://user-images.githubusercontent.com/3908736/51115951-58372e00-1812-11e9-82e5-7b85fd0096b0.jpg)


![native checkout websites aps](https://user-images.githubusercontent.com/3908736/51115996-78ff8380-1812-11e9-8cf2-ca3b695b7150.jpg)

**Comment by CodeScroll** [comment]
Δεν βρισκω το Popup στην δευτερη εικονα σας!

**Comment by kostGX** [comment]
@CodeScroll πλοηγηθείτε από το μενού Sales > Online Payments > Websites/Apps

**Comment by CodeScroll** [comment]
Still the Undefined index: drpInstallments in C:\xampp\htdocs\viva\viva-2.php on line 7 exist! What should i make ?

**Comment by pRieStaKos** [comment]
> 
> 
> Still the Undefined index: drpInstallments in C:\xampp\htdocs\viva\viva-2.php on line 7 exist! What should i make ?

Στην φόρμα σου δεν εχεις βαλει `<options>` στις δόσεις ([εδώ](https://github.com/VivaPayments/API/blob/master/NativeCheckout/PHP/web/index.php#L90))

**Comment by CodeScroll** [comment]
> 
> 
> > Still the Undefined index: drpInstallments in C:\xampp\htdocs\viva\viva-2.php on line 7 exist! What should i make ?
> 
> Στην φόρμα σου δεν εχεις βαλει `<options>` στις δόσεις ([εδώ](https://github.com/VivaPayments/API/blob/master/NativeCheckout/PHP/web/index.php#L90))

https://prnt.sc/m7g609

**Comment by CodeScroll** [comment]
Ok, now i have 

The following error occured: The merchant with id 9*********4 does not have a source with code 'Native' assigned or the source is disabledThe following error occured: Order with code 0 was not foundTransaction Failure

**Comment by pRieStaKos** [comment]
Εχεις φτιαξει πηγη ? Πωλήσεις > Online Πληρωμές > Websites/Apps

**Comment by CodeScroll** [comment]
https://prnt.sc/m7gffi

Μαλλον ναι.

**Comment by CodeScroll** [comment]
Μηπως φταιει που εχω βαλει την Ip μου ετσι ? 

https://prnt.sc/m7gjvu

**Comment by pRieStaKos** [comment]
> 
> 
> Μηπως φταιει που εχω βαλει την Ip μου ετσι ?
> 
> https://prnt.sc/m7gjvu

Όνομα Domain: εξωτερική σου IP
Συνδεδεμένο Wallet: το wallet που θες.

To 4073 βάλτο, [εδώ](https://github.com/VivaPayments/API/blob/master/NativeCheckout/PHP/lib/NativeCheckoutClass.php#L16)

**Comment by CodeScroll** [comment]
Ε Π Ι Τ Ε Λ Ο Υ Σ

Ε Υ Χ Α Ρ Ι Σ Τ Ω
