### ISSUE TITLE
OpenCart Έκδοση 3.0.2.0 redirect fails

### ISSUE THREAD

**Issue by rotame** [VivaPayments/API#702]
Δεν γίνεται redirect Με το δικό σας module μας δίνει το παρακάτω error 
Notice: Trying to get property of non-object in /home/cakeartg/public_html/4/catalog/controller/extension/payment/vivawallet.php on line 133Notice: Trying to get property of non-object in /home/cakeartg/public_html/4/catalog/controller/extension/payment/vivawallet.php on line 134Notice: Trying to get property of non-object in /home/cakeartg/public_html/4/catalog/controller/extension/payment/vivawallet.php on line 135Notice: Trying to get property of non-object in /home/cakeartg/public_html/4/catalog/controller/extension/payment/vivawallet.php on line 136

**Comment by rotame** [comment]
Αγοράστηκε και απο την εταιρεία με το ίδιο λάθος

**Comment by rotame** [comment]
![screenshot from 2019-01-12 15-41-34](https://user-images.githubusercontent.com/46726715/51207513-ab44da00-1913-11e9-8051-c084f7b23056.png)
![screenshot from 2019-01-12 15-44-20](https://user-images.githubusercontent.com/46726715/51207515-ab44da00-1913-11e9-872b-99b92e30b7e8.png)

**Comment by rotame** [comment]
Δεν μπορούμε να καταλάβουμε γιατί αποτυγχάνει το redirect

**Comment by VivaWalletSupport** [comment]
Hello, to help identify the problem please post following screenshots:

1. Payment extension settings (mask API Key).
2. Viva payment source settings (including the browsers URL).
3. Viva payment source(s) listing page (including the browsers URL).

**Comment by olekkas** [comment]
![3](https://user-images.githubusercontent.com/45355329/51233453-977c9080-1972-11e9-996b-8dd63ff15c4c.JPG)
![extension](https://user-images.githubusercontent.com/45355329/51233454-977c9080-1972-11e9-8ea9-2776f47791f7.JPG)
![source](https://user-images.githubusercontent.com/45355329/51233455-98152700-1972-11e9-8bda-76ea0e7adc79.JPG)

**Comment by VivaWalletSupport** [comment]
Please change your API key as it should not be revealed, then send me again a screenshot of the payment source including the browser URL like http://prntscr.com/m7tq6q and also send a screenshot of your API settings like http://prntscr.com/m7tqmu (including browser URL, do not include your new API Key). Also please confirm the PHP cURL extension is active on your server.

**Comment by rotame** [comment]
Mod Security disabled
Server CPANEL
PHP Version 7.0.33



Regarding CURL
cURL support	enabled
cURL Information	7.62.0
Age	4
Features
AsynchDNS	Yes
CharConv	No
Debug	No
GSS-Negotiate	No
IDN	No
IPv6	Yes
krb4	No
Largefile	Yes
libz	Yes
NTLM	Yes
NTLMWB	Yes
SPNEGO	Yes
SSL	Yes
SSPI	No
TLS-SRP	Yes
HTTP2	Yes
GSSAPI	Yes
KERBEROS5	Yes
UNIX_SOCKETS	Yes
PSL	No
Protocols	dict, file, ftp, ftps, gopher, http, https, imap, imaps, pop3, 
pop3s, rtsp, scp, sftp, smb, smbs, smtp, smtps, telnet, tftp
Host	x86_64-redhat-linux-gnu
SSL Version	OpenSSL/1.0.2q
ZLib Version	1.2.7
libSSH Version	libssh2/1.4.3





Στις 2019-01-16 09:19, Tom van der Veer έγραψε:

**Comment by olekkas** [comment]
![3](https://user-images.githubusercontent.com/45355329/51236345-918aad80-197a-11e9-8e39-b25974677273.JPG)
![source](https://user-images.githubusercontent.com/45355329/51236346-92234400-197a-11e9-85ce-9cd5ad106d6f.JPG)

**Comment by olekkas** [comment]
you mean my viva account pass and username?

**Comment by VivaWalletSupport** [comment]
Correct, together with store admin and ftp access but send it to the email addresses as mentioned before, do not post them here at github.

**Comment by olekkas** [comment]
ok  i send it

**Comment by rotame** [comment]
The problem was from SSL
We changed from Letsencrypt free to RapidSSL and working fine
Thanks a lot You can close the ticket
