### ISSUE TITLE
SHOPIFY redirect language English

### ISSUE THREAD

**Issue by YorgosKer** [VivaPayments/API#704]
I use Viva payments on my greek eshop but i have a problem with languages

When someone click to pay with viva payments automatically redirect by the system to viva's site but in the engish version, not greek. And the only way to make the language greek is to click the greek flag. 

Is there a way to automatically redirected to the english version?

Thanks in advance

**Comment by matthewrgourd** [comment]
Hi there, apologies for the lack of reply previously. I'm assuming you managed to solve this issue somehow but please let me know if not. Thanks!

**Comment by YorgosKer** [comment]
Hi.
No, i don't know what can i do
Is there a way to solve this problem?

Στις Δευ, 22 Ιουλ 2019 στις 6:34 μ.μ., ο/η matthewrgourd <
notifications@github.com> έγραψε:

**Comment by matthewrgourd** [comment]
Hi there I've checked with our Shopify developer and apparently that's the correct behaviour in the current setup but we intend it to recognise the country you're in in the future.
