### ISSUE TITLE
Multi Currency

### ISSUE THREAD

**Issue by TheGoodBudz** [VivaPayments/API#705]
Hello,

We want to accept multi currency payments. Is it  possible to integrate with shopify BOLD cashier app and if not, is there an alternative to Bold Cashier to accept multi-currency which Viva integrates with.

**Comment by bigtili** [comment]
Hi, we would also like to accept multi currency payments. The WooCommerce plugin does not seem to support it. Please help.

**Comment by matthewrgourd** [comment]
Hi @bigtili, for the transaction at Viva only the currency is supported from the country your company is registered in. In case this would be the UK, only the GBP currency would be allowed. For WooCommerce there are various plugins available that are able to covert other currencies to GBP in the checkout stage. You can do a search at https://woocommerce.com/product-category/woocommerce-extensions
