### ISSUE TITLE
VIVA PAYMENTS - PAYMENT CONFIRMATION EMAIL SENT TO CLIENT IN GREEK NOT ENGLISH

### ISSUE THREAD

**Issue by platawellness** [VivaPayments/API#706]
Hi,

We have been testing the Viva payment system on our website and have one issue which we are unable to resolve.

After an order has been placed and paid for on our site, the client receives a payment confirmation email from Viva however, it is in greek as per the image below.

<img width="773" alt="screenshot 2019-01-23 at 09 44 23" src="https://user-images.githubusercontent.com/46958111/51602061-ee97dd80-1efd-11e9-9b85-45582095a1a7.png">

As per earlier posts, we have checked that our preferred language is set to English as per the picture below.

<img width="386" alt="screenshot 2019-01-23 at 10 38 22" src="https://user-images.githubusercontent.com/46958111/51601970-b09ab980-1efd-11e9-98e8-2e1757860321.png">

Just to be clear, we are not talking about the payment confirmation that the merchant receives which is coming through in English.

Please advise. Thanks in advance for your help.

Jon

**Comment by bigtili** [comment]
Hi, I have the same problem. Any news on the solution?

**Comment by platawellness** [comment]
Hi, unfortunately not. I have raised a query with VIVA, they keep directing me to GitHub but I don’t think the solution is there.

Jon

On 14 Mar 2019, at 08:28, bigtili <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I have the same problem. Any news on the solution?

**Comment by ravravrav** [comment]
What's the latest on this one guys? There surely must be a way to set this to English?

**Comment by kostGX** [comment]
@platawellness The checkout's lang parameter dictates the language of the email receipt. If that it's not set (via what triggers the Create Order call), then it falls back to the account setting of Preferred Language.

In any case, you can request from our support team to disable these notifications entirely for your account.

Please let me know if I can help any further :)
