### ISSUE TITLE
Vivawallet for OC2.3 ERROR

### ISSUE THREAD

**Issue by billykarag** [VivaPayments/API#707]
Hi
i just installed the vivawallet extension for **OC2.3**, i made all the necessary actions, followed the instructions [here](https://github.com/VivaPayments/API/blob/cc95dd31a000d3d61ceafdd91d6c46a7a1b2b1f1/Plugins/opencart/Opencart%202.3/readme.txt), in the _backoffice of vivawallet and backend of OC_ and i get this notice when im about to place a new order

**Notice: Trying to get property of non-object in /home/bequeenb/public_html/catalog/controller/extension/payment/vivawallet.php on line 132Notice: Trying to get property of non-object in /home/bequeenb/public_html/catalog/controller/extension/payment/vivawallet.php on line 133Notice: Trying to get property of non-object in /home/bequeenb/public_html/catalog/controller/extension/payment/vivawallet.php on line 134Notice: Trying to get property of non-object in /home/bequeenb/public_html/catalog/controller/extension/payment/vivawallet.php on line 135**

Does anyone know what i did wrong?
my site is [bequeenboutique](http://bequeenboutique.com
)

**Comment by VivaWalletSupport** [comment]
Hello, to help identify the problem please post following screenshots:

1. Payment extension settings (mask API Key).
2. Viva payment source settings (including the browsers URL).
3. Viva payment source(s) listing page (including the browsers URL).
4. Also send a screenshot of your API settings like http://prntscr.com/m7tqmu (including browser URL, mask your API Key).

**Comment by billykarag** [comment]
![1](https://user-images.githubusercontent.com/46971349/51660495-a5579480-1fb6-11e9-9178-f99cc9e6d872.jpg)
![2](https://user-images.githubusercontent.com/46971349/51660496-a5f02b00-1fb6-11e9-8809-ca0513612097.jpg)
![3](https://user-images.githubusercontent.com/46971349/51660497-a5f02b00-1fb6-11e9-8f74-7151df7a6285.jpg)

**Comment by VivaWalletSupport** [comment]
Vivawallet payment source problem:
Remove www. from the Domain Name setting as your site does not use www by default.

Payment extension settings problems:
OrderCode URL: https://www.vivapayments.com/api/orders
Redirect URL: https://www.vivapayments.com/web/newtransaction.aspx

**Comment by VivaWalletSupport** [comment]
In case this solved the problem please close this issue, otherwise let me know how I can assist.

**Comment by VivaWalletSupport** [comment]
In case the payment source is under review (inactive) after making the change to the domain name, it should be indicated in the payment sources listing page.

**Comment by billykarag** [comment]
Thank u very much for the help
