### ISSUE TITLE
Issue with the returing link

### ISSUE THREAD

**Issue by atsouf** [VivaPayments/API#708]
Καλησπέρα σας,

έχω χρησιμποποιήσει το plugin της enartia για woocommerce και με τα credentials που μου δίνει η viva συνδέομαι κανονικά και γίνεται η πληρωμή. Με κάνει σωστά redirect στην viva με τα σωστά ποσά και στοιχεία. Το πρόβλημα είναι ότι όταν ολοκληρωθεί η πληρωμή δεν με επιστρέφει στο site ούτε μαρκάρει την παραγγελία ως ολοκληρωμένη.  Έχω προσθέσει τα links αλλά δεν γίνεται καν διαδικασία redirect. Βγάζει επιτυχής πληρωμή και δεν επιστρέφει

**Comment by yiannis667** [comment]
Το ιδιο προβλημα και εδω ...

**Comment by pmantzar** [comment]
και γω το ίδιο θέμα έχω. βρήκατε λύση?

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Can you please let me know if this is still an issue for you? Thanks!
