### ISSUE TITLE
Viva wallet με Pegasus

### ISSUE THREAD

**Issue by oasis6** [VivaPayments/API#709]
Καλημέρα σας,
Υπάρχει ένα πρόβλημα με την σύνδεση του VivaWallet με το Tesae Pegasus.
Όταν γίνεται πληρωμή με πιστώτικη/χρεωστική κάρτα από το σίτε μας (entermusic.gr) δεν γίνεται Συνημμένα θα βρείτε φωτογραφία από τις ρυθμίσεις του pegasus.
Σας ευχαριστώ
![default](https://user-images.githubusercontent.com/47053522/51785346-2ea9cb00-215f-11e9-82d4-13a32dd96341.jpg)

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found a solution to this problem, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
