### ISSUE TITLE
redirect error and order cancelled

### ISSUE THREAD

**Issue by yiannis667** [VivaPayments/API#710]
hello i have created 2 pages for succesfull and unsuccesfull transactions on woocommerce but when customer pays viva wallet doesnt redirect them there..instead i get oops nothing found here on a new page opened.. so customers dont know if they paid or not..another issue is that after payment the order gets cancelled by itself within a few hours. how can i fix these 2 issues ? thank you

**Comment by VivaWalletSupport** [comment]
Hello, are you using a specific plugin to connect WooCommerce with Viva Payments?

**Comment by yiannis667** [comment]
I am using the enartia version 1.2 plugin. Thank you

**Comment by VivaWalletSupport** [comment]
In that case I would suggest to contact the developer of the plugin for support, or use the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce and follow the instructions from the readme.txt file.

**Comment by yiannis667** [comment]
I will use the supported plugin.. Thank you !

**Comment by yiannis667** [comment]
I clicked the link provided is there a file there to download ?

**Comment by yiannis667** [comment]
I cant find the viva wallet for woocommerce zip file to download. Can you point me where its at ?

**Comment by VivaWalletSupport** [comment]
This is the zip file that contains all code examples and plug ins:
https://github.com/VivaPayments/API/archive/master.zip

**Comment by VivaWalletSupport** [comment]
In case the problem has been solved please close this issue, if you have any other questions please let me know.

**Comment by yiannis667** [comment]
i tried installing the api-master plugin but i get wordpress error saying no valid extensions were found

**Comment by VivaWalletSupport** [comment]
You can install through FTP, please note that the master.zip contains all files and plugins from the repository, you only need the files for woocommerce.

**Comment by yiannis667** [comment]
I have installed and activated the plugin, how do i create viva wallet source code ? Thank you

**Comment by VivaWalletSupport** [comment]
Yes, but you have to specify the settings in that app as mentioned in the readme.txt file.

**Comment by yiannis667** [comment]
thank you for your help ! i have put setting in wordpress and viva wallet website. I wait for app to be verified from viva wallet and test it . if i have no issue i will close the subject. Thank you !
