### ISSUE TITLE
ΧΡΕΩΣΗ ΣΕ ΞΕΝΑ ΝΟΜΙΣΜΑΤΑ

### ISSUE THREAD

**Issue by kwssiamp** [VivaPayments/API#714]
Σε προηγουμενο μειλ μου ειπατε πως ειστε συμβατοι με DCC (Digital Currency Converter) για την μετατροπή των συναλλάγματος.  Δεν μπορω να βρω στο API σας την παραμετρο για να κανω χρεωση σε ξενα νομισματα! Μπορειτε να με καθοδηγησετε παρακαλω?

**Comment by kostGX** [comment]
Καλησπέρα σας @kwssiamp, το DCC είναι στα πλάνα μας, αλλά αυτή τη στιγμή δεν παρέχεται η υπηρεσία.
