### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Diamando** [VivaPayments/API#715]
Θα ήθελα να χρησιμοποιήσω την υπηρεσία Viva Wallet ώστε ο χρήστης να μπορεί να εισάγει το ποσό που θέλει να προσφέρει. Να κάνει δηλαδή εισφορά / δωρεά στον οργανισμό. 

Μπορείτε να με καθοδηγήσετε με πως μπορώ να το κάνω αυτό;

Χρησιμοποιώ την πλατφόρμα Wordpress (Version 5.0.3).

Ευχαριστώ

**Comment by matthewrgourd** [comment]
Hi there, sorry no-one got back to you previously. We don't currently offer an out-of-the-box option for customers to pay a manually determined amount. Hope this helps. Thanks!
