### ISSUE TITLE
Abandoned checkout not cancelling order

### ISSUE THREAD

**Issue by gazja** [VivaPayments/API#716]
Hello,

I can't find any documents online or on the Viva Wallet admin dashboard regarding our issue.  We are currently using Magento 1.9. 

Currently the new order creation and failed/successful payments work fine. The problem is when a user starts the checkout process and never completes the Viva Wallet payment form (redirect) the order just gets left in status "New" and is never cancelled.

Is there fuinctionality in this payment module to automatically cancel these abandoned orders, or do we need to add a cron job to process these orders?

Thank you,
Gareth Pitchford

**Comment by VivaWalletSupport** [comment]
Hello, in case you are referring to the supported Magento extension from the VivaPayments plugins, there is no option for that. However, there are other Magento extensions that can handle such (cron) jobs. In case this answered your question, please close this issue.

**Comment by gazja** [comment]
Thank you for your response, I will make a cron task for this. Do you know if the vivawallet checkout screen has a timeout length? We don't want to be accidently cancelling orders people can still pay for.

**Comment by VivaWalletSupport** [comment]
Timeout has been hard coded to 300 seconds https://github.com/VivaPayments/API/wiki/Optional-Parameters#paymenttimeout--int32-

**Comment by gazja** [comment]
Thank you, closing ticket as resolved the issue by creating our own cron task.
