### ISSUE TITLE
Order is cancelled after successful transaction

### ISSUE THREAD

**Issue by bitmyjob** [VivaPayments/API#717]
Hi, we are using the suggested github extension for Magento 2 and we experiencing the following problem: As soon as an order is complete and the payment is captured, the order status remains in "Pending Payment" and after a few hours the order status is changed automatically in Magento to "Cancelled" ! At the same time, that does not affect the payment and the transaction is complete in vivapayments platform.

Waiting your update as its really critical issue and we need to fix it asap.

**Comment by VivaWalletSupport** [comment]
Hello, could you post a screenshot of the payment source you created in your Viva account?

**Comment by bitmyjob** [comment]
what kind of screenshot you need? the transaction in magento platform or the success transaction in viva account?

**Comment by bitmyjob** [comment]
Is this what you need?

 

Από: Tom van der Veer [mailto:notifications@github.com] 
Αποστολή: Monday, February 4, 2019 13:30
Προς: VivaPayments/API
Κοιν.: bitmyjob; Author
Θέμα: Re: [VivaPayments/API] Order is cancelled after successful transaction (#717)

 

I need the screenshot from the payment source you created in you Viva account.

⁣Kind regards,
Tom van der Veer

+35796138974
+306977080153​

**Comment by VivaWalletSupport** [comment]
The return URLs are not correct, please have a look at the readme file on how to use these URLs.

**Comment by VivaWalletSupport** [comment]
In case you have solved the problem, please close this issue, otherwise let me know how I can help.
