### ISSUE TITLE
Shopify Plugin Error

### ISSUE THREAD

**Issue by scarlettjo123** [VivaPayments/API#718]
Hi there,

I was under the impression the account had been successfully integrated with Shopify, however, after attempting a test purchase it appears this is not the case.

Tried to select debit/credit card payment via Viva Wallet and was met with a plugin error, can you please assist as a matter of urgency?

**Comment by kostGX** [comment]
Hello @scarlettjo123, if you followed the steps of the integration guide found here: https://github.com/VivaPayments/API/wiki/Shopify-Integration

Then you are ready to process payments. Please make sure you are entering an amount larger than 30cents and that you have NOT checked the "test mode" box. Use a real card, you can later refund/cancel the transaction via the Viva Wallet interface.

**Comment by scarlettjo123** [comment]
I have followed the integration guide and we attempted a purchase of £1.00. 

Where is the test mode box? So I can check?

**Comment by kostGX** [comment]
@scarlettjo123 I couldn't find a customer care ticket that you requested Shopify StoreToken under these credentials. Please follow the integration guide carefully, to the letter. Don't forget to request Shopify credentials via this form: https://landing.vivawallet.com/shopify

After you receive your Shopify integration credentials, then run the guide carefully once again and you won't have any problems. We have hundreds of merchants using the Shopify integration today.

**Comment by kostGX** [comment]
@scarlettjo123 goodmorning, I just checked and it seems like you didn't submit the form.

After you submit it, then our Customer Care department will send you the credentials which you can use during the integration guide in order to successfully process payments with us.

**Comment by scarlettjo123** [comment]
Hi, I will submit the form AGAIN and let you know so you can verify whether this has been completed or not...

**Comment by scarlettjo123** [comment]
Form submitted 04-02-2019 12:13 pm. I can send a copy of the form if necessary

**Comment by scarlettjo123** [comment]
Hello, any word??

**Comment by scarlettjo123** [comment]
Hello. Urgent assistance needed.

**Comment by Alisoncoins** [comment]
@scarlettjo123 did they complete document verification for you? I'm trying to make sense of this my self but did read on here that document verification can take two weeks if you completed correctly,

I'm also waiting for support regarding this issue but hoping I'm just been silly and its because my merchantID isn't activated yet = [support request](https://github.com/VivaPayments/API/issues/726)

**Comment by kostGX** [comment]
@scarlettjo123 hello, did you manage to solve your issues?

**Comment by scarlettjo123** [comment]
Hello, no! Might we have to wait 2 weeks as alisoncoins suggested? I really need more communication and assistance. It's not good enough that your customer service over the phone is unable to help, and this appears to be no better!

**Comment by kostGX** [comment]
Hello,

No. Account verification doesn't block the Shopify integration. 

I still can't find in our back-office program Shopify Credentials Request for the merchant_id 12e73cc4-b3b6-4520-beaf-bd0ed32a4ada

It seems that the submission of this form fails https://landing.vivawallet.com/shopify

We're not experiencing any issues with other customers.

Can you try to send manually from your email client the following email to request credentials:

Subject: Shopify Token Request {{your shopify store url}}

Body: Hello Viva, I would like to process payments with Viva Payments on my Shopify store. 
Shopify store name: {{Shopify Store Name}}
Shopify store url: {{Shopify Store URL}}
Merchant ID: 12e73cc4-b3b6-4520-beaf-bd0ed32a4ada
Phone number: {{your viva wallet registration phone number}}
First Name: {{your first name}}
Last Name: {{your last name}}
Email: {{your email}}

Let me know if you did so I can search again to see if the request comes through.

Thanks and sorry your inconvenience.

**Comment by scarlettjo123** [comment]
what email address am I sending this to please?

**Comment by kostGX** [comment]
@scarlettjo123 merchants@vivawallet.com (sorry I forgot to mention it)

**Comment by scarlettjo123** [comment]
thank you

**Comment by scarlettjo123** [comment]
Form manually sent, please let me know once received...

**Comment by kostGX** [comment]
Hello,

I confirm that we received the form submission. You should get your StoreToken in the following 24 hours.

Thanks.

**Comment by Alisoncoins** [comment]
whats closed im still want to know were my £800 went ?

On 17/06/2019 16:27, matthewrgourd wrote:

> Closed #718 [1]. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/VivaPayments/API/issues/718
[2]
https://github.com/VivaPayments/API/issues/718?email_source=notifications&amp;email_token=ALKGXJUGIX5IKZQEJ6BBEMDP26UPRA5CNFSM4GTZEVD2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSAP5IRA#event-2418005060
[3]

**Comment by matthewrgourd** [comment]
Hi there, apologies, I assumed you'd received the store token and everything was ok. Please raise a [new issue](https://github.com/VivaPayments/API/issues/new) or call us on + 44 (20) 37347770 and we will look at on an urgent basis. Thanks!
