### ISSUE TITLE
Integration questions.

### ISSUE THREAD

**Issue by LL-Support** [VivaPayments/API#719]
Hello! We have some integration questions, please, help us:

Deposits
1) Can we customize the payment page when using Redirect Checkout?

2) Do you control the uniqueness of our transaction id? (request: / api / Orders, parameter MerchantTrns).

3) We have a question about your notification service called Webhooks. You send alerts only about creating or canceling a transaction (-Create Transaction,
-Cancel / Refund Transaction), we also need a notification about the successful completion of the payment. Can you add this notification?

4) We need documentation about all possible request: / response / api / Orders parameters. In the current documentation we didn't find them.

Withdraw
1) We need documentation about all possible Original Credit Transaction (OCT) request / response parameters. We did not find them in the current documentation - there is only one successful example.

Refund
1) There isn't description about all possible request / response parameters DELETE / api / transactions /. Please, describe it. 

Please, add to whitelist out IP's (or we can add it in Business account?):
81.198.186.18 
81.198.164.132 

Also, please, give us your IP for whitelist on our side.

The documentation did not find answers to our questions.

**Comment by LL-Support** [comment]
Colleagues, is there any information on the problem?

**Comment by LL-Support** [comment]
Colleages, waiting for an answer from you.

**Comment by matthewrgourd** [comment]
Hi there, sorry for the delayed response. All the documentation that exists currently can be found here:

https://developer.vivawallet.com/api-reference-guide/payment-api-details/

Thanks!
