### ISSUE TITLE
web hook (Error code 502)

### ISSUE THREAD

**Issue by Delivertoo** [VivaPayments/API#720]
When we try to add webhook URL  we get verification error. Please check the screen:
![image](https://user-images.githubusercontent.com/45786496/52228768-eb1c3300-28bb-11e9-923a-9548123cac3d.png)

we use the Redirection method
can you please help me

**Comment by kostGX** [comment]
Hello, please consult this section of the Webhook verification guide and you will solve your problem

https://github.com/VivaPayments/API/wiki/Webhooks#webhook-url-verification

**Comment by Delivertoo** [comment]
We have successfully verified our webhook link but now we're getting another error, i.e: "A Webhook for this Event Type already exists (Error code 409)" because  already added a webhook for "Transaction Payment Created". from a diferent web site  
Any advice?

**Comment by Delivertoo** [comment]
θα μας απαντήσει κανείς ?

**Comment by kostGX** [comment]
@Delivertoo hello, currently you cannot have 2 webhooks for the same event.

You could use a middleware to consume the webhook and based on the transaction source decide to further route it. 

Hope this helps.

**Comment by Delivertoo** [comment]
@kostGX  Thanks 
ποια γραμμή είναι αυτή που μου δίνει την πηγή ή το web site που έγινε η πληρωμή για να το αναγνωρίσω και να το δρομολογήσω ανάλογα ?
{
  "EventData":{
	"Amount": 100.50,
	"CardNumber": "411111XXXXXX1111",
	"CardTypeId": 0,
	"ClientId": "90a7114f-3a7a-466b-8a45-000111222555",
	"CompanyName": "Viva Ηλεκτρονικές Υπηρεσίες",
	"CurrencyCode": 978,
	"CurrentInstallment": 0,
	"CustomerTrns": "Customer description",
	"Email": "customer@viva.gr",
	"FullName": "Customer FullName",
	"InsDate": "2014-06-18T14:20:30.45+03:00",
	"MerchantId": "90a7114f-3a7a-466b-8a45-000111222666",
	"MerchantTrns": "Merchant Reference",
	"OrderCode": 776027772607,
	"ParentId": "90a7114f-3a7a-466b-8a45-000111222777",
	"ResellerCompanyName": "Παπασωτηρίου",
	"ResellerId": "90a7114f-3a7a-466b-8a45-000111222888",
	"ResellerSourceAddress": "Πανεπιστημίου 37 και Κοραή, Αθήνα",
 	"ResellerSourceCode": "2233",
	"ResellerSourceName": "Πανεπιστημίου",
	"SourceCode": "Default",
	"StatusId": "F",
	"TotalCommission": 2.71,
	"TotalFee": 0.50,
	"TotalInstallments": 0,
	"TransactionId": "90a7114f-3a7a-466b-8a45-000111222888",
	"TransactionTypeId": 5
  },
  "EventTypeId": 1796,
  "Created": "2014-06-18T14:20:30.45+03:00"
}

**Comment by Delivertoo** [comment]
@kostGX  
Λογικά  στο web hook που θα λάβουμε πρέπει  κάπως να βρούμε αυτό που δείχνω στην φώτο? 

![image](https://user-images.githubusercontent.com/45786496/52481615-a93f0580-2bb7-11e9-9faa-f19a158b2245.png)

**Comment by kostGX** [comment]
Correct and it's called **SourceCode**

Please check the Webhooks document to see sample payloads of all supported events.

**Comment by Delivertoo** [comment]
@kostGX 
ok Thanks i found it
