### ISSUE TITLE
Αποτυχίας Συναλλαγής

### ISSUE THREAD

**Issue by LinoZipper** [VivaPayments/API#721]
Καλησπέρα προσπαθώ να ενσωματώσω το κώδικα με Κουμπί πληρωμών με συγκεκριμένο ποσό και λαμβάνω το παρακάτω μήνυμα. 
Η συναλλαγή σας απέτυχε.
fail Αποτυχίας Συναλλαγής.
Το site είναι δηλωμένο και ενεργό
PHP version:  7.0
το site είναι joomla 3.91

(Σε άλλο site joomla 3.86 PHP version:  5.6 λειτουργεί κανονικά)

Μπορεί κάποιος να βοηθήσει;

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming you found an answer to your question by other means, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
