### ISSUE TITLE
Native Checkout is working on demo account but now working on live account. 

### ISSUE THREAD

**Issue by Usmanakram123** [VivaPayments/API#722]
i am using Yii2 framework and using PHP script for vivaapyments.  after integrating i tested it using demo account it was working with demo credit card like 4111 1111 1111 1111. it successfully return transaction ID to my local database.  But when i changed the API keys and payment source code it is not working with real credit card. it does not even return any transaction ID.  
same happening with when i used Redirection instead of Native Checkout.

**Comment by kostGX** [comment]
Hello @Usmanakram123, did you change your API base URL from demo.vivapayments.com to www.vivapayments.com?

Can you pls share your merchant id so I can take a look?

**Comment by Usmanakram123** [comment]
Yes. i have done these 3 steps after successfull testing the demo account.
1. changed the URL from demo.vivapayments.com to www.vivapayments.com on my controller
2. changed the **Merchant ID** and **API Key** in my controller.
3. changed the **Public Key** in my view (where the input fields are)
4. changes the URL from demo.vivapayments.com to www.vivapayments.com in same view file.

My **Merchant ID** on live account  is  74456fdd-f37c-4726-b040-1faf1b0ffe9c
--

**Comment by kostGX** [comment]
@Usmanakram123 thank you. And which Source Code are you using? (just checking via the back office to see if your Apps/Websites config is correct)

**Comment by Usmanakram123** [comment]
We are using https://github.com/VivaPayments/API/blob/master/NativeCheckout/PHP/lib/NativeCheckoutClass.php

and production URL is https://www.ukpharmacymeds.com/
its the ecommerce store for Medicines. 
i have also implemented the demo on same above URL and its working good with demo account and demo credit card. but when i changed the APIs and Urls it stop working. no error shows. 
currently we removed the checkout page. (currently we are only accepting the Bank transfer)

**Comment by Usmanakram123** [comment]
We are using https://github.com/VivaPayments/API/blob/master/NativeCheckout/PHP/lib/NativeCheckoutClass.php

and production URL is https://www.ukpharmacymeds.com/
its the ecommerce store for Medicines.
i have also implemented the demo on same above URL and its working good with demo account and demo credit card. but when i changed the APIs and Urls it stop working. no error shows.
currently we removed the checkout page. (currently we are only accepting the Bank transfer)

**Comment by Simonfbarrett** [comment]
Hello there, I have just opened a Viva Wallet account and would like to link to my website which is WordPress WooCommerce. Ideally I would like native so it all stays on my site. I am completely lost what to do and how to get set up, I do t know how to code so any help greatly appreciated or direction where I can get this done. I even don't mind paying someone to sort this out. Many thanks. My website is www.thegingerjuicer.com

**Comment by Usmanakram123** [comment]
tell me your all scnerio on email. may be i can help you. send me email on this address. er.usman.akram@gmail.com
