### ISSUE TITLE
Simple Checkout  in Romanian

### ISSUE THREAD

**Issue by donfn** [VivaPayments/API#723]
When Romanian is selected, the pop-up is correctly translated, though the button displays greek text...

**Comment by kostGX** [comment]
@donfn hello, you can customize the text to your liking using the data-vp-text attribute.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/3908736/52413851-5b5ccb80-2aeb-11e9-86b7-60559355abb9.png">

See here: https://github.com/VivaPayments/API/wiki/Simple-Checkout

Let me know if you have solved the issue.

**Comment by donfn** [comment]
Καλησπέρα και ευχαριστώ για την απάντηση!
Γνωρίζω για το συγκεκριμένο attribute, παρ'όλα αυτά , επειδή φτιάχνω ένα intergration για woocommerce, δεν μπορώ να αναγκάσω τον ρουμάνο μαγαζάτορα να αλλάξει το κείμενο..Θα έπρεπε να δουλεύει όπως πρέπει out-of-the-box ;) .
