### ISSUE TITLE
Error: Signature not verified

### ISSUE THREAD

**Issue by pvoulg** [VivaPayments/API#725]
Kαλησπέρα. Αντιμετωπίζουμε ένα ζήτημα με την σύνδεση Shopify store και το Viva Wallet integration. Έχουμε προσθέσει κανονικά MerchantID και StoreToken (το οποίο μας στάλθηκε αφού ο πελάτης μας συμπλήρωσε την αντίστοιχη φόρμα) και κατά το redirect στο περιβάλλον της Viva Wallet παρουσιάζεται σφάλμα **"Error: Signature not verified"**.

Το StoreToken μας είχε σταλεί αρχικά λάθος από το merchants@vivawallet.com (είχε ένα κενό ανάμεσα στους χαρακτήρες), αλλά παρότι διορθώθηκε το πρόβλημα εξακολουθεί. 

Ο πελάτης μας είχε ήδη λογαριασμό στην Viva και υπήρχε ενεργή πηγή online πληρωμών συνδεδεμένη με το παλιό του site (σε περιβάλλον WooCommerce), την οποία και απενεργοποίησα. Παρατήρησα ότι δεν υπήρχε πηγή από το Shopify, και έτσι δημιούργησα μία, αλλά από ότι αντιλαμβάνομαι είναι κάτι που πρέπει να γίνει από την δική σας πλευρά, καθώς υπάρχουν πεδία που δεν εφαρμόζονται στην συγκεκριμένη περίπτωση. Επιπλέον, όταν προσπαθώ να διαγράψω την πηγή που δημιούργησα παρουσιάζεται σφάλμα **"Οι πηγές πληρωμών με συναλλαγές δεν μπορούν να διαγραφούν"** (ενώ δεν υπάρχουν συναλλαγές από αυτή την πηγή).

Μπορείτε να με ενημερώσετε για το πως να προχωρήσουμε σχετικά, καθώς το κατάστημα είναι online και αυτή τη στιγμή δεν μπορεί να δεχτεί ηλεκτρονικές πληρωμές; Το Shopify URL είναι το εξής: differentstoregr.myshopify.com

**Comment by kostGX** [comment]
@pvoulg Καλημέρα σας,

Το συγκεκριμένο error σχετίζεται με το ό,τι δεν έχει περαστεί σωστά το Store Token.

Τα tokens εκδίδονται ανά merchant id, συνεπώς για δεύτερο ή περισσότερα stores, χρησιμοποιείτε τα ίδια credentials. 

Βρήκα στα logs του Shopify URL σας και φαίνεται να έχει εκδοθεί ορθώς το token.

Μπορείτε να επιβεβαιώσετε πως έχει περαστεί σωστά το token + merchant_id και πώς δεν έχετε κάποιο config Test Mode στο Control Panel του Shopify ενεργοποιημένο;

Ευχαριστώ

**Comment by pvoulg** [comment]
@kostGX Καλησπέρα, 

Ξαναπέρασα το integration από την αρχή. Είναι απενεργοποιημένο το test mode. 

Το Store Token που μας έστειλαν είχε από την πρώτη στιγμή ένα κενό ανάμεσα σε δύο χαρακτήρες. Το επισήμανα στο merchants@vivawallet.com και μου επιβεβαίωσαν ότι αυτό έχει γίνει εκ παραδρομής και δε θα έπρεπε να είναι εκεί. Το δοκίμασα χωρίς κενό, παρόλα αυτά εξακολουθεί να μην λειτουργεί όπως πρέπει. 

Δοκίμασα επίσης να το γράψω, αντί να το κάνω copy-paste και το πρόβλημα επιμένει. Υπάρχει τρόπος να εκδοθεί νέο Store Token σε περίπτωση που οφείλεται το σφάλμα σε αυτό (ώστε να αποκλείσουμε αυτή την εκδοχή);

**Comment by kostGX** [comment]
@pvoulg καλησπέρα και πάλι,

Υπήρχε ένα θέμα το email service και "έφαγε" κάποιους χαρακτήρες του token.

Σας έστειλα εκ νέου το token σωστά. Οπως θα παρατηρήσετε λείπουν 2 pipes |

**Comment by pvoulg** [comment]
@kostGX ok, ευχαριστώ, τώρα δουλεύει κανονικά.
