### ISSUE TITLE
WooCommerce for WordPress

### ISSUE THREAD

**Issue by richardjsteggles** [VivaPayments/API#727]
Using 5.0.3 version of WP and cant seem to get the integration between  the wallet and WooCommerce to communicate.

**Comment by VivaWalletSupport** [comment]
Hello, please confirm the supported plugin from https://github.com/VivaPayments/API/tree/master/Plugins/wordpress is used and provide a screenshot of the plugin settings (mask API key).

**Comment by richardjsteggles** [comment]
<img width="818" alt="screenshot wp_wc_vw" src="https://user-images.githubusercontent.com/47525061/52567039-31651b00-2e03-11e9-94c7-b904ca2ae1a7.PNG">
 please see attached

**Comment by VivaWalletSupport** [comment]
This is not a screenshot from the supported plugin, but from a 3rd party plugin..
Please close this issue in case this solved your problem.
