### ISSUE TITLE
Refunds

### ISSUE THREAD

**Issue by scarlettjo123** [VivaPayments/API#728]
Hi there,

With regards to Shopify orders, do the payments have to be refunded/cancelled in Viva Wallet as well as Shopify?  

I have just tried to refund in Shopify but to no avail, so then "cancelled" it in Viva Wallet... Is this the case?

**Comment by kostGX** [comment]
@scarlettjo123 hello, yes. We currently don't support capturing or refunding transactions via the Shopify Control Panel. 

You need to perform it in the Viva Wallet Dashboard.

It's definitely within our interest to implement deeper integration with Shopify but I can't provide you with a certain timeline at this time.

**Comment by scarlettjo123** [comment]
So, just to be clear. You do not know when we can send a customer refund notification or indeed see VivaWallet refunds in the Analytics section of Shopify for reporting, etc?

**Comment by rossboardman** [comment]
Hi, @kostGX or anyone at Vivawallet, can you please confirm if this is still the case and that a refund made within Vivawallet will not be reflected within Shopify?

**Comment by matthewrgourd** [comment]
@rossboardman That is correct, yes. Thanks and sorry if this isn't the answer you want.

**Comment by 0766458080** [comment]
Hi every one can any person tell me about refunding becuse vivawallet hold my transaction from.one week

**Comment by 0766458080** [comment]
I want refund my transaction
