### ISSUE TITLE
Έλεγχος υπάρχοντος merchant id

### ISSUE THREAD

**Issue by xaniotis27** [VivaPayments/API#729]
Καλησπέρα σας,
Φτιάχνω μια εφαρμογή όπου ο κάθε χρήστης θα μπορεί να "φτιάχνει" την δική του πηγή πληρωμών δημιουργώντας λογαριασμό στην vivapayments και στο σύστημα μου θα βάζει το merchant id και api key.. 
Η ερώτηση μου είναι η εξής:
Εγώ σαν σύστημα θέλω να τσεκάρω όταν βάζει κάποιος χρήστης το merchant id του και το api key, να τα ελέγχω με κάποιο τρόπο αν είναι valid ή όχι... 

Αυτό γίνεται ή όταν κάποιος θα πατήσει πληρωμή θα του βγάλει σφάλμα?

Υ.Γ. Έψαξα εδώ αλλά δεν βρήκα κάποια αντίστοιχη ερώτηση ή στους κώδικες κάτι αντίστοιχο πέρα από το create order...

Ευχαριστώ εκ των προτέρων!

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. I'm afraid we don't have an API for this so won't be able to facilitate your project. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
