### ISSUE TITLE
Detailed errors when a transaction fails

### ISSUE THREAD

**Issue by mauxtin** [VivaPayments/API#730]
Καλησπέρα,

Υπάρχει τρόπος να δω για ποιό λόγο μια (δοκιμαστική στο demo) συναλλαγή απέτυχε;

Ανακατευθύνομαι στη σελίδα της πληρωμής, βάζω στοιχεια 4111 1111 1111 1111 και 111 για CVV αλλά μετά κανει redirect στη σελίδα του fail και statusId: "E" χωρίς καμιά άλλη πληροφορία.

Η τελετυταία προσπάθεια έχει TransactionId: "be9d5349-83ac-4f45-b809-ba092ca714f3"

**Comment by kostGX** [comment]
@mauxtin Have you tried using GetTransactions and checking the ErrorText property?

https://github.com/VivaPayments/API/wiki/GetTransactions

Let me know if you need further help.

**Comment by mauxtin** [comment]
Καλησπέρα @kostGX

Ναι, πέρνω 
```
 "Transactions": (...),
 "ErrorCode": 0
 "ErrorText": null
 "TimeStamp": "2019-02-13T13:47:16.0545013+02:00"
 "CorrelationId": null
 "EventId": 0
 "Success": true
```

Αλλά γίνεται redirect στο url για αποτυχημένες συναλλαγές και δεν βλέπω την συναλλαγή στο dashboard (sandbox) της viva.

**Comment by mauxtin** [comment]
Υπάρχει κάποιος άλλος τρόπος να κάνω debug το πρόβλημα; @kostGX

**Comment by mauxtin** [comment]
Related: #690 #646 #644 #606

**Comment by kostGX** [comment]
@mauxtin μπορείτε να δείτε τα failed transactions στο dashboard Sales > Sales transactions επιλέγοντας από τα φίλτρα

Advanced search > Remarks > Failed

@mauxtin τα redirect URLs τα έχετε σεττάρει σωστά στο Sales > Online > Websites/Apps?

**Comment by mauxtin** [comment]
Καλησπέρα @kostGX,

Μπορώ να δω τα transactions με το τρόπο που περιγράψατε, ευχαριστώ. Ωστόσο δεν μπορώ ακόμα να δω τον λόγο που τα transactions αποτυγχάνουν. 

Τα redirects έχουν δηλωθεί ναι, γίνεται το redirect απο τη πληρωμή σε εμένα κανονικά αλλά πάντα σαν αποτυχημένο transaction.

**Comment by kostGX** [comment]
@mauxtin καλησπέρα,

Μολίς δοκίμασα να φτιάξω order code (στην default πηγή) με το δικό σας merchant_id (de735313-c85e-447d-ac0e-713cfde08341) το οποίο και πλήρωσα στην redirect checkout (https://demo.vivapayments.com/web/checkout?ref=ORDER_ID)

και στην συνέχεια με έκανε redirect success. Κοιτώντας τα logs, έχει περαστεί ως approved η συναλλαγή.

Μπορείτε να επιβεβαιώσετε?

Ευχαριστώ

**Comment by mauxtin** [comment]
@kostGX ευχαριστώ για την άμεση ανταπόκριση. 

Επιβεβαιώνω ότι η συναλλαγή σας πέρασε επιτυχώς. Απο ότι φαίνεται στέλνω κάποιες λάθος παραμέτρους. Υπάρχει κάποιος τρόπος να δω τι πήγε λάθος στις υπόλοιπες συναλλαγές;
