### ISSUE TITLE
vivaWallet prestashop - Redirect issues after successful payment 

### ISSUE THREAD

**Issue by ramanccube9** [VivaPayments/API#731]
Hi Team,
I am working with prestashop viva wallet, I have done payment successfully, after payment link should be redirect on website but it gives "Successfull Messages" on viva payment website page.

![image](https://user-images.githubusercontent.com/47551044/52614868-181ea600-2eb9-11e9-8630-996b5f6dc010.png)

**Comment by VivaWalletSupport** [comment]
Hello, are you using the supported plugin? Is so, did you follow the instructions from the readme file on how to connect your store with your Viva wallet payment source?

**Comment by VivaWalletSupport** [comment]
In case you have resolved the problem, please close this issue.
