### ISSUE TITLE
Order Paid - Status: Shipped not Processing

### ISSUE THREAD

**Issue by yiannis667** [VivaPayments/API#732]
Hello, when customer pays with viva wallet the order status becomes SENT and not PROCESSING so customer receives email that order has been sent but order is in processing. I am using your viva wallet app from github. Wordpress and Woocommerce. Apreciate any help. Thank you

**Comment by VivaWalletSupport** [comment]
Hello, please post a screenshot of your plugin settings (mask the API key) and from your Viva Wallet payment source setup.

**Comment by yiannis667** [comment]
i got it .. on settings it was prompt to complete order, i changed to processing. Thank you !
