### ISSUE TITLE
Custom url μετά απο πετυχημένη  πληρωμή

### ISSUE THREAD

**Issue by xaniotis27** [VivaPayments/API#733]
Καλησπέρα σας,
Θα ήθελα να ρωτήσω αν η διαδικασία των redirect μετά από πετυχημένη συναλλαγή γίνεται μόνο μέσα από τις πηγές πληρωμών ή αν υπάρχει η δυνατότητα να στέλνεται μέσα του create order.

Αυτό το ρωτάω γιατί φτιάχνω μια custom εφαρμογή και ο κάθε πελάτης θα δημιουργεί την δική του πηγή πληρωμών και πέρα από τα merchant id και api key που θα βάζει στο σύστημα μου να μην τον βάζω σε διαδικασία να βάζει τα url success και error στην viva...

Ευχαριστώ πολύ!

**Comment by kostGX** [comment]
Hello,

I'm not sure what you're trying to implement but this might come handy: https://github.com/VivaPayments/API/wiki/Payment-Sources:-AddSource
