### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by gazja** [VivaPayments/API#735]
Hello,

We have been using VivaWallet for a few weeks now without issue, since last night we are getting customers directed to the API URL and getting a "Service Unavailable" HTTP Error 503.

The following URL in question is : https://www.vivapayments.com/web/newtransaction.aspx

Are there currently issues on VivaWallet's API? To calrify, this has been working for weeks and we have taken many payments, without change to our side we now get this error. 

Thanks,
Gaz

**Comment by kostGX** [comment]
@gazja Hello what kind of integration have you implemented? What's your merchant id so I can open an investigation ticket.

Thanks!

**Comment by gazja** [comment]
Hello @kostGX . 

We currently have implemented magento 1.9. You can test this on www.seedsmancbd.com using an English (UK) address on checkout selecting any card type as the payment option. 

Our merchant ID is : 5a267158-acaa-43b3-a322-91cdaebd324b

Also my work email is gaz@tgrventures.com if it is easier to email me directly regarding this. Unfortunately we are unable to take any payments today, so it's rather urgent for us to resolve.

Thanks,
Gaz
