### ISSUE TITLE
Redirection URLs

### ISSUE THREAD

**Issue by pentesgeorge** [VivaPayments/API#736]
Hello,
I am using yours official plugin for woocommerce.

I use the links for redirection as described at the instructions but they are not working properly.
They redirect to page which shows -1.

I found a pdf with instructions and I used  wc-api/WC_Papaki_Vivapayments_Gateway.
With this setting success redirect works perfect but failed redirect goes to success page too.

Can you help me?

Thank you!

**Comment by VivaWalletSupport** [comment]
Hello, could you post a screenshot of the plugin settings? Please mask the api key.

**Comment by pentesgeorge** [comment]
Hello,
these are the settings
![screenshot from 2019-02-15 12 42 34](https://user-images.githubusercontent.com/30080885/52851887-e22f2b00-311f-11e9-80af-4e5b3a5135a6.png)

**Comment by donfn** [comment]
This is not the official integration. Viva, unfortunately, doesn't post their plugins on the WordPress marketplace. You can download the official plugin here: https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce .  
The plugin you currently have is developed by a greek hosting company called 'Papaki' and more specifically by its parent company 'Enartia'.

Also, I'm currently looking for merchants to test my integration, so if you are interested you can try it https://wordpress.org/plugins/viva-payments-simple-checkout/ .

**Comment by pentesgeorge** [comment]
Thank you for your quick reply.

I downloaded and installed your plugin.

![screenshot from 2019-02-15 14 17 46](https://user-images.githubusercontent.com/30080885/52856277-a9498300-312c-11e9-9569-75d8e9f49fb4.png)

But I come to same error.
Blank page -1

I use permalinks for my worpdress website.

Thank you,
George

**Comment by donfn** [comment]
What's your website's language? Greek or English? Can you provide a link?

P.S. I don't work at Viva :-P

**Comment by pentesgeorge** [comment]
I use both languages.
I use for the translation polylang plugin and I installed now Loco translate for the Viva Plugin translation.

My website is photosphere.gr you can find a product at /shop

**Comment by donfn** [comment]
Να σου μιλάω στα Ελληνικά τότε. Στο Dashboard, ΠΩΛΗΣΕΙΣ > ONLINE ΠΛΗΡΩΜΕΣ > WEBSITES / APPS και μετά στην πηγή πληρωμών που έχεις βάλει στο πεδίο "Source Code", τι link έχεις βάλει; Μπορείς να στείλεις ένα screenshot;

**Comment by pentesgeorge** [comment]
Ωραίος!
Στο woocommerce -> payments -> vivawallet  στο source  code
Βάζω το code που υπάρχει στο Websites/Apps στο Dashboard του viva account μου

**Comment by donfn** [comment]
😉

![viva](https://user-images.githubusercontent.com/12240818/52858476-efa1e080-3132-11e9-8d31-01d3e643402b.png)
Πες ότι στο κόκκινο κουτί είναι το Payment Source σου...Αν πατήσεις πάνω στο πεδίο "Περιγραφή", θα σου βγάλει κάτι επιπλέον ρυθμίσεις.. Μπορείς να τις στείλεις σκρινσοτ?

**Comment by pentesgeorge** [comment]
Έχεις απόλυτο δίκιο.
Χθες ψάχνοντας απελπισμένα για μια λύση πριν ποστάρω στο Φορουμ έκανα διάφορες δοκιμές και είχα αλλάξει μια από αυτές τις παραμέτρους.
Τώρα δουλεύουν όλα τέλεια!!!

Σε ευχαριστώ πολύ για τον χρόνο και την βοήθεια σου.

**Comment by donfn** [comment]
Τίποτα! 😄
