### ISSUE TITLE
Change in amount parameter?

### ISSUE THREAD

**Issue by Vrachno** [VivaPayments/API#737]
While testing viva payments in the demo server today, I was unable to complete transactions due to a "zero or negative amount" error. Debugging made me realize that I was accidentally passing a float number in euros instead of cents, contrary to what the documentation states (1.20 instead of 120). What bothers me is that this used to work until now, and the transactions were completed with the correct amount.

Was something changed recently in the back end that prevents users to pass floating point numbers?

Thanks.

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Nothing has changed as far as we're aware. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
