### ISSUE TITLE
Payment with card when in Facebook in-app browser fails

### ISSUE THREAD

**Issue by legolassoi** [VivaPayments/API#738]
When users try to make a payment using their credit/debit card on our website when viewed through the FB in-app browser, the payment appears to be declined. However, their is no record of these transactions in Viva Wallet which means that the payments aren’t reaching viva wallet at all.

No notification is given to the user. They only see the red rectangle with the white cross (as per below screenshot)

![fail](https://user-images.githubusercontent.com/18256979/52877353-673b3400-3162-11e9-894f-85e1a08cbfc6.jpg)

 
If the user makes the same payment from the same page opened in a web browser, then the payment is successful.

Viva Wallet representative has also tested this and encountered the same issues.

**Comment by matthewrgourd** [comment]
Hi there, sorry for the lack of response previously. There are known issues with Simple Checkout when used with the Facebook browser. You'll need to switch to our [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) in order to avoid any further issues. Thanks!
