### ISSUE TITLE
Prestashop - Installation not working

### ISSUE THREAD

**Issue by m-Nightly** [VivaPayments/API#739]
Hello there,

I followed the entire process described in the readme file. But this doesn't work, the error we're getting is caused here :

In the module import class.
$response = \call_user_func_array($controller, $arguments);

I've tried to install the module via my FTP and dropping it directly in the modules folder, but this doesn't work either. The module doesn't appear in the list of modules.

Has this problem already been encountered? How do I solve it?

Kr,
Nightly

**Comment by VivaWalletSupport** [comment]
Hello, maybe something went wrong with packing the module? Please try attached 
[vivawallet.zip](https://github.com/VivaPayments/API/files/2872698/vivawallet.zip)

**Comment by m-Nightly** [comment]
> Hello, maybe something went wrong with packing the module? Please try attached
> [vivawallet.zip](https://github.com/VivaPayments/API/files/2872698/vivawallet.zip)

Hello, 

This isn't working either.

Our version is 1.7.5.0 and we're using a custom theme, could this be it? 

The error we're receiving from Prestashop doesn't show us what went wrong during the installation, only that an exception was raised.

Do you have any kind of logging set up at your side? Do you see what went wrong ? :)


Kind regards,
Nightly

**Comment by VivaWalletSupport** [comment]
Did you try to install manually through FTP? In that case check that the folders and file have the correct file rights (folders 755, files 644 on LAMP).

**Comment by m-Nightly** [comment]
> Did you try to install manually through FTP? In that case check that the folders and file have the correct file rights (folders 755, files 644 on LAMP).

Hello,

Yes, I tried doing it manually already and the file rights are correct (folder & files). And is still doesn't work. Does the module work with templates ?

Kr,
Nightly

**Comment by VivaWalletSupport** [comment]
For the font-end some issues have been seen in the past with specific themes and 3rd party checkout extensions, for the admin area I have not experienced such a problem. In case you could send admin and ftp access to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com I can have a look at the problem.

**Comment by VivaWalletSupport** [comment]
Turning off the debug setting (*1), removing the module by FTP, installing the module again and correcting the folder/file permissions seems to have done the trick. http://prntscr.com/mn14k1

(*1) https://www.prestashop.com/forums/topic/525033-getting-error-you-do-not-have-permission-to-configure-this-module-when-trying-to-install-a-module/

Let me know in case there is any other problem, otherwise close this issue.

**Comment by m-Nightly** [comment]
> Turning off the debug setting (*1), removing the module by FTP, installing the module again and correcting the folder/file permissions seems to have done the trick. http://prntscr.com/mn14k1
> 
> (*1) https://www.prestashop.com/forums/topic/525033-getting-error-you-do-not-have-permission-to-configure-this-module-when-trying-to-install-a-module/
> 
> Let me know in case there is any other problem, otherwise close this issue.

Thanks for the fixes. 

We still have one question, we can't seem to see the payment method on the e-commerce and in the admin console. 

We only see the module and we're able to configure it, as explained in the readme file provided in the git.

**Comment by VivaWalletSupport** [comment]
You did not allow the payment method for the available shipping options.
http://prntscr.com/mni988

Let me know in case there is any other problem, otherwise close this issue.
