### ISSUE TITLE
Magento 2.1 link doesn't work

### ISSUE THREAD

**Issue by gpessios** [VivaPayments/API#740]
Hi,
We tried to navigate through the eCommerce page (https://github.com/VivaPayments/API/wiki#ecommerce-store) to the Magento 2.1 plugin but the link returns a 404 error. Is there a module that you could suggest?
We are interested more on one that we could possibly use for a native checkout solution.
Thank you in advance.
Regards,
George

**Comment by VivaWalletSupport** [comment]
Hello, the correct location is https://github.com/VivaPayments/API/tree/master/Plugins/magento/magento2_vivawallet/Ced/VivaPayments

Please note that this extension works with the redirection method.
