### ISSUE TITLE
Order remains in "Pending" after successful transaction

### ISSUE THREAD

**Issue by gpessios** [VivaPayments/API#741]
Hi,
After a successful transaction the order in Magento doesn't update to "Processing". It just remains in a "Pending" status.
Any help would be much appreciated.
Thank you.

**Comment by VivaWalletSupport** [comment]
Could you please post a screenshot of the extensions settings (mask api key) and a screenshot of the payment source?

**Comment by pmantzar** [comment]
I have the same issue on woocommerce sites where the card is charged successfully on viva but we don't get a valid response and we get many pending orders. The clients try again and again and we have many transactions and charges to the clients for the same order

**Comment by VivaWalletSupport** [comment]
@pmantzar I would suggest to open a new issue as this one is related to another e-commerce platform. Post also a screenshot of the plugin settings (mask api key) and a screenshot of the payment source.

**Comment by gpessios** [comment]
@VivaWalletSupport where "Source Code" is the 4 digit Code from payment source.

![screenshot 2019-02-18 at 11 01 13](https://user-images.githubusercontent.com/1614960/52940232-b786e180-336e-11e9-90a3-3ea805652e7a.png)
![screenshot 2019-02-18 at 11 05 52](https://user-images.githubusercontent.com/1614960/52940255-c4a3d080-336e-11e9-9708-361d719e9dea.png)

**Comment by VivaWalletSupport** [comment]
The "New Order Status" entry (Processing) does not look original, did you make any changes to the code? Also this is the status that the order gets when redirecting to Viva, not when receiving a valid transaction (in that case the order status would be Completed). I would suggest to connect to the sandbox environment until the correct working has been confirmed before moving to live mode.

**Comment by gpessios** [comment]
Even when using the default "New Order Status" which was "Pending Payment" we encounter the same issue. The order keeps being stated as "Pending" and doesn't update to "Processing". So we did also make a change to the code to try if that "Processing" on "New Order Status" will fix the issue. Do all the rest of the urls have the correct values?

**Comment by VivaWalletSupport** [comment]
The paid status is for the invoice, let me know when you have connected to the demo environment to see a test. Please use the original files.
