### ISSUE TITLE
Viva Wallet WooCommerce - Payment

### ISSUE THREAD

**Issue by Diamando** [VivaPayments/API#742]
Hi,

I'm using the following plugin and I'm facing issues with the orders. 

[https://wordpress.org/plugins/woo-payment-gateway-for-vivapayments/]

While the website gets paid and the client gets a notification of the payment, the viva page never redirects back to the website but the most important is that the order status remains as "pending payment". This is a critical issue, since the order must be marked as "Completed" and if this is the case then the program automatically will send the ticket to the customer. 

Since now the order status is not changing, the tickets never reach their destination...

I will be glad if you can help me ASAP since this specific website is related with a movie and we want to sell tickets a month before the premiere.

I'm using wordpress 5.0.3 and woocommerce 3.5.4. 
The version of the VIVA plugin is 1.2.

Thanks in advance,
Diamando

**Comment by flametonguez** [comment]
Did you find any solution to this? I'm facing the same issue

**Comment by matthewrgourd** [comment]
Hi there, the plugin you mention (https://wordpress.org/plugins/woo-payment-gateway-for-vivapayments) is not our official one therefore we are unable to support it. Please refer to the WooCommerce page on the Viva Wallet Developer Portal for both the official plugin and installation instructions: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
Thanks!
