### ISSUE TITLE
simple checkout error

### ISSUE THREAD

**Issue by Delivertoo** [VivaPayments/API#743]
@gliaskos @kostGX  hello,
we have done the testing using the test credentials & we have got the success in test mode but in  a real test we can't complete the payment .

can you help me please

**Comment by deb-ordering** [comment]
@gliaskos @Delivertoo @kostGX Hi,

We are presently facing problems with the simple checkout 2nd step i.e. STEP 2: Make the charge (https://github.com/VivaPayments/API/wiki/Simple-Checkout#step-2-make-the-charge) 
We are getting vivaWalletToken from the 1st step. We are using PHP code to make the charge, but we are not getting success to make the charge using our live card. Please check below our code and let us know where we will have to make the changes? Or else it would be very helpful for us if you can send us the PHP sample code for Simple-Checkout#step-2-make-the-charge. 

`$request =  'https://www.vivapayments.com/api/transactions';	// production environment URL

// Your merchant ID and API Key can be found in the 'Security' settings on your profile.
$MerchantId = 'b64cf27a-9cdc-415e-bb06-ee7e48d0a93d';
$APIKey = 'SO?wq+'; 
$postargs = 'PaymentToken='.$vivaWalletToken;

$session = curl_init($request);
// Set the POST options.
curl_setopt($session, CURLOPT_POST, true);
curl_setopt($session, CURLOPT_POSTFIELDS, $postargs);
curl_setopt($session, CURLOPT_HEADER, true);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
curl_setopt($session, CURLOPT_USERPWD, $MerchantId.':'.$APIKey);
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
// Do the POST and then close the session
$response = curl_exec($session);
//print_r($response);
// Separate Header from Body
$header_len = curl_getinfo($session, CURLINFO_HEADER_SIZE);
$resHeader = substr($response, 0, $header_len);
$resBody =  substr($response, $header_len);
curl_close($session);`

Thank You!

**Comment by donfn** [comment]
@deb-ordering Change your API key ASAP. You should mask such info before posting...

Try this code:

```
   $MerchantId = xxxxxxxxxxxxxxx;
   $APIKey = xxxxxxxxxxxxxxxxxx;
					
   $session = curl_init('https://www.vivapayments.com/api/transactions');
   curl_setopt( $session, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
   curl_setopt($session, CURLOPT_POSTFIELDS, json_encode(array("PaymentToken" => $_POST['vivaWalletToken']))); //Replace $_POST['vivaWalletToken'] in case you have already have it as a variable
   curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
   curl_setopt($session, CURLOPT_USERPWD, htmlspecialchars_decode($MerchantId) . ':' . htmlspecialchars_decode($APIKey));
   $response = curl_exec($session);
   curl_close($session);
```

**Comment by Delivertoo** [comment]
@VivaWalletSupport 
θα μας απαντήσει κανείς παρακαλώ

**Comment by deb-ordering** [comment]
@donfn 
Thank you for your help. I will let you know if any further assistance needed.

**Comment by donfn** [comment]
@Delivertoo Κάνεις κανονικά κλήση του /api/transactions, μετά από την υποβολή της φόρμας του simple checkout;

**Comment by Delivertoo** [comment]
@deb-ordering   the @donfn ask:  do you  normaly call the / api / transactions after submitting the simple checkout form

**Comment by donfn** [comment]
Εσένα ρώτησα xD @Delivertoo

**Comment by donfn** [comment]
Όταν συμπληρώνεις τα στοιχεία της κάρτας και πατάς πληρωμή, δεν γίνεται απευθείας
η χρέωση. Αντιθέτως, παίρνεις ένα "κωδικό έγκρισης" (vivaWalletToken) , τον οποίο μετά πρέπει να 
τον στείλεις στους server της Viva -μέσω μερικών γραμμών κώδικα-, έτσι ώστε να ολοκληρωθεί η συναλλαγή.

**Comment by Delivertoo** [comment]
@donfn Δεν είμαι ο προγραμματιστείς εγώ . Απο ότι φαίνεται μάλλον ο κώδικάς που έδωσες βοήθησε γιατί μόλις μου ε΄παν να κάνω δοκιμή και πέρασε .
Ευχαριστώ

**Comment by donfn** [comment]
😃👍 

Υ.Γ. Πάτα "Close issue" δίπλα από το πράσσινο κουμπί "Comment", για να δείξεις ότι 
έλυσες το πρόβλημα σου.
