### ISSUE TITLE
Can't Create a Demo Account

### ISSUE THREAD

**Issue by JamesAntropy** [VivaPayments/API#744]
Hi,

I'm trying to create a demo account here: https://demo.vivapayments.com/en-us/signup in order to test the OC extension, but I keep getting this error: http://james.antropy.co.uk/images/screenshots/029d4d278.jpg

Is there a problem with the form at the moment? 

Kind Regards,

James

**Comment by nestonian** [comment]
Same problem here, trying today

**Comment by kostas1986** [comment]
Same here. Unable to create an account or login with an existing one!

**Comment by sdagkas** [comment]
Same! Is anybody from viva monitoring these threads?

**Comment by matthewrgourd** [comment]
Sorry for the delayed response. This shouldn't be an issue now.
