### ISSUE TITLE
Δόσεις WooCommerce

### ISSUE THREAD

**Issue by sagoro** [VivaPayments/API#745]
Καλησπέρα σας,

έχω ένα e-Shop που δουλεύει με Redirection Checkout στο site της Viva, όμως δεν έχω την επιλογή για δόσεις.

Έχω βάλει το ποσό των δόσεων που θέλω στον κώδικα, όμως δεν μου εμφανίζεται η επιλογή δόσεων στην ιστοσελίδα της Viva.

=' . $srccode . '&DisableIVR=true&MaxInstallments=6' .

Ευχαριστώ εκ των προτέρων.

**Comment by matthewrgourd** [comment]
Please see answer to [issue 839](https://github.com/VivaPayments/API/issues/839). Thanks!
