### ISSUE TITLE
Magento 2.24 - exception thrown when placing a test order

### ISSUE THREAD

**Issue by CBDology** [VivaPayments/API#746]
Hi,

I'm installing the plugin for Magento 2.24.

I've set up the api key etc.

When I try to place a test order, at the checkout I choose the Viva payment method and then click the place order button and the following exception happens:

url: mydomain/vivapayments/checkout/start

1 exception(s):
Exception #0 (Exception): Notice: Trying to get property of non-object in mydomain/app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 202

Exception #0 (Exception): Notice: Trying to get property of non-object in mydomain/app/code/Ced/VivaPayments/Model/PaymentMethod.php on line 202
#0 mydomain/app/code/Ced/VivaPayments/Model/PaymentMethod.php(202): Magento\Framework\App\ErrorHandler->handler(8, 'Trying to get p...', '/home/cbdology/...', 202, Array)
#1 mydomain/app/code/Ced/VivaPayments/Controller/Checkout/Start.php(40): Ced\VivaPayments\Model\PaymentMethod->getPostHTML(Object(Magento\Sales\Model\Order\Interceptor))
#2 mydomain/vendor/magento/framework/App/Action/Action.php(107): Ced\VivaPayments\Controller\Checkout\Start->execute()
#3 mydomain/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#4 mydomain/vendor/magento/framework/Interception/Interceptor.php(138): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callParent('dispatch', Array)
#5 mydomain/vendor/magento/framework/Interception/Interceptor.php(153): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#6 mydomain/generated/code/Ced/VivaPayments/Controller/Checkout/Start/Interceptor.php(26): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->___callPlugins('dispatch', Array, Array)
#7 mydomain/vendor/magento/framework/App/FrontController.php(55): Ced\VivaPayments\Controller\Checkout\Start\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#8 mydomain/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#9 mydomain/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#10 mydomain/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 mydomain/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 mydomain/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 mydomain/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 mydomain/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 mydomain/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#16 mydomain/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 mydomain/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#18 mydomain/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#19 {main}

Any help much appricated.

Cheers

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

1. Extension settings (mask the API Key).
2. Viva Wallet payment source settings (include the browsers URL in the screenshot).
3. Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
4. API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by CBDology** [comment]
Hi, many thanks, please find attached.
![viva wallet payment source screenshot](https://user-images.githubusercontent.com/47788456/53031256-68bb7380-3464-11e9-9708-fc1663486e1a.jpg)
![viva wallet website-apps screenshot](https://user-images.githubusercontent.com/47788456/53031257-69540a00-3464-11e9-8820-e2feae5fe4f4.jpg)
![api access screenshot](https://user-images.githubusercontent.com/47788456/53031258-69540a00-3464-11e9-92e6-6dc5cb94a788.jpg)
![extension settings screenshot](https://user-images.githubusercontent.com/47788456/53031259-69540a00-3464-11e9-80d4-2e35acc53b0a.jpg)

**Comment by VivaWalletSupport** [comment]
In the extension settings correct the (demo) URLs from **https://demo**.vivapayments.com to **https://www**.vivapayments.com or use the credentials (Mid/Key/Source code) from your Viva demo account.

**Comment by CBDology** [comment]
Hi this worked, all fixed, thanks very much
