### ISSUE TITLE
viva payments/ i get an 404 error page after transaction

### ISSUE THREAD

**Issue by Samcronic** [VivaPayments/API#747]
after i put everything that the plug in asks i get an 404 error i use woocommerce

**Comment by VivaWalletSupport** [comment]
Hello, could you post a link to the plugin you are using?

**Comment by Samcronic** [comment]
how do i post it??

**Comment by Samcronic** [comment]
[wc-vivawallet.zip](https://github.com/VivaPayments/API/files/2881087/wc-vivawallet.zip)

**Comment by VivaWalletSupport** [comment]
You could post a link as https://github.com/VivaPayments/API/tree/master/Plugins/wordpress/vivawallet-for-woocommerce in that case.

Please please provide the following 4 screenshots:

1. Plugin settings (mask the API Key).
2. Viva Wallet payment source settings (include the browsers URL in the screenshot).
3. Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
4. API Access page (mask API Key, include the browsers URL in the screenshot).

See issue https://github.com/VivaPayments/API/issues/746 for what screenshots I need.

**Comment by Samcronic** [comment]
![viva3](https://user-images.githubusercontent.com/47787680/53034270-80eabd00-347b-11e9-803e-9f1efbae7d54.jpg)
![viva4](https://user-images.githubusercontent.com/47787680/53034273-81835380-347b-11e9-9521-3e1b28217d9b.jpg)
![viva1](https://user-images.githubusercontent.com/47787680/53034274-81835380-347b-11e9-8414-a333098cbdb7.jpg)
![viva2](https://user-images.githubusercontent.com/47787680/53034275-821bea00-347b-11e9-9113-fdbf393bb34a.jpg)

**Comment by VivaWalletSupport** [comment]
In your plugin settings uncheck the Test mode http://prntscr.com/mnaivh as the credentials you are using are for the live mode. In case you want to test the plugin you would configure the plugin (Mid/Key/Source code) with the credentials from your demo account at http://demo.vivapayments.com

In case this solved your problem please close this issue, otherwise let me know how I can help.

**Comment by Samcronic** [comment]
thank you a lot
