### ISSUE TITLE
Issue with entering mobile phone number at checkout - bug

### ISSUE THREAD

**Issue by HempHash** [VivaPayments/API#748]
Hi, there still seems to be an issue/bug with mobile phone devices using our viva wallet payment gateway on our shopify integration - customers are having issues entering their mobile number - does not work with or without prefix - customers can't complete payment - please help

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Assuming this is no longer a problem, I'm closing the issue. However, if you have any other queries please do please let us know and we'd be happy to help. Thanks!
