### ISSUE TITLE
PHP issues

### ISSUE THREAD

**Issue by stevebgs** [VivaPayments/API#749]
I am using php 7.2  in my virtuemart site there seems to be coding issues with the virtuemart plug in and this version I am not technical are you able to sort this out for me " operator not supported for strings" that is the what i see i n the cart page  when i use DEBUG  is see this - IS THERE SOME CODING TO CHANGE TO ARRAY ?  If 
 de activate the VIVAwallet plug in the site and shopping cart works fine

![screenshot 2](https://user-images.githubusercontent.com/47790994/53105943-f90fbc00-3529-11e9-9d80-b6ab724de295.png)

![shot4](https://user-images.githubusercontent.com/47790994/53112200-a4bf0900-3536-11e9-90cd-a9ef254a81ae.png)

Please email me I can give you access to my cpanel to correct code etc if you can do

**Comment by VivaWalletSupport** [comment]
Hello, please send me the URL for the used version of the VirtueMart plugin.
Example: https://github.com/VivaPayments/API/tree/master/Plugins/virtuemart/vm3_plugin_vivawallet

**Comment by VivaWalletSupport** [comment]
In case you are using the VM3 plugin, it has been updated today. Try the latest version and let me know in case there is still a problem, otherwise close this issue.
