### ISSUE TITLE
Checkout Result (Η συναλλαγή σας απέτυχε)

### ISSUE THREAD

**Issue by vasilis1984** [VivaPayments/API#75]
Καλησπέρα σας,

προσπαθώ να συνδέσω την πληρωμή του Viva στο site ενός πελάτη μου.
Ο κώδικας που χρησιμοποιώ είναι να σας ποστάρω στο https://www.vivapayments.com/api/orders

Χρησιμοποιώ το Merchant ID και το API Key του πελάτη μου και εσείς μου γυρνάτε το status ΟΚ και το url για να κάνω redirect.
Πραγματικά, μπαίνω εκεί (το κάνω copy paste σε έναν browser) και μου βγάζει σωστά το ποσό της χρέωσης και με ρωτάει πως να πληρώσω.

Συνδέομαι με το viva μου (έχω υπόλοιπο) και όταν πληρώνω μου βγάζει στο Checkout Result ένα error Που λέει "Η συναλλαγή σας απέτυχε."

Έχω ρυθμίσει στο εταιρικό προφίλ του πελάτη μου, τις πηγές πληρωμών με τα success και fail url's

Γιατί συμβαίνει αυτό; Κάποια βοήθεια;

Ευχαριστώ,
Βασίλης.

**Comment by dmihos** [comment]
Καλησπέρα
Πιθανά είναι κάποιο πρόβλημα με το δικό σας client wallet (ίσως κάποιο όριο).
Ξαναδοκιμάστε, αν θέλετε, κι αν το πρόβλημα συνεχίζει, αποστείλατε στο merchants@vivawallet.com τα στοιχεία και των 2 λογαριασμών για διερεύνηση.
Ευχαριστώ

**Comment by vasilis1984** [comment]
Καλησπέρα σας,

το πρόβλημα συνεχίζεται και δεν έχει λυθεί. Η χρέωση που προσπαθώ να κάνω είναι είτε 0.01 ευρώ είτε 0.1 ευρώ. Μεταφέρομαι κανονικά στο interface της viva, όπως περιγράφω και έχω κανονικά υπόλοιπο στον λογαριασμό μου.

Έχω ήδη επιοκοινωνήσει με το email που μου λέτε και μου είπανε να απευθυνθώ εδώ.

Ευχαριστώ,
Βασίλης.

**Comment by dmihos** [comment]
Το πρόβλημα είναι στο ποσό που χρησιμοποιείτε για δοκιμή, δε μπορεί να γίνει χρέωση τόσο μικρού ποσού. Δοκιμάστε ένα μεγαλύτερο ποσό, αν θέλετε (πάνω από 0.30€-0.40€)

**Comment by vasilis1984** [comment]
Έχετε απόλυτο δίκιο, έβαλα 0.30 λεπτά και έγινε κανονικά η πληρωμή ΟΜΩΣ δεν μεταφέρθηκα ποτέ πίσω στο site. Μου έβγαλε ότι "Η χρέωση της κάρτας πραγματοποιήθηκε επιτυχώς."

Έχω ρυθμίσει κανονικά τα URL's για success ή fail.

Ευχαριστώ,
Βασίλης.

**Comment by dmihos** [comment]
Θα πρέπει να βεβαιωθείτε ότι περνάτε το σωστό SourceCode κατά τη δημιουργία του Order, ώστε να γίνει χρήση των σωστών redirect urls μετά την πληρωμή.

**Comment by vasilis1984** [comment]
Εγώ σας ποστάρω στο URL https://www.vivapayments.com/api/orders τις παρακάτω μεταβλητές:
- Amount  (με τιμή 30)
- AllowRecurring (με τιμή false)
- RequestLang (με τιμή el-GR)
- SourceCode (με τιμή Default)

και μου γυρνάτε ένα URL της μορφής https://www.vivapayments.com/web/newtransaction.aspx?ref=9814858582772605 όπου και εκεί κάνω redirect.

Ευχαριστώ,
Βασίλης Τριβλής.

**Comment by dmihos** [comment]
Δεν αναφέρομαι στο redirect που κάνετε εσείς, αλλά σε αυτό που κάνει η Viva μετά την πληρωμή.
Έχετε βάλει τα urls του site σας στην πηγή **Default**;

**Comment by vasilis1984** [comment]
Μιλάτε για την μεταβλητή SourceCode; Και εάν ναι τι πρέπει να γράψω;
Όπως σας έχω πει από το 1ο post μου έχω ρυθμίσει στο εταιρικό προφίλ του πελάτη μου, τις πηγές πληρωμών με τα success και fail url's.

Ευχαριστώ,
Βασίλης Τριβλής.

**Comment by dmihos** [comment]
Είναι λίγο αινιγματικό αυτό που αναφέρετε με το 'έχω ρυθμίσει τις πηγές'.
Αν έχετε φτιάξει νέα πηγή με τα urls του site του πελάτη σας, τότε θα πρέπει να χρησιμοποιείτε το SourceCode αυτής της πηγής όταν δημιουργείτε το Order.

**Comment by vasilis1984** [comment]
Τώρα κατάλαβα ότι θα πρέπει να βάλω στο SourceCode της πηγής που έχω φτιάξει.

Έκανα μια παραγγελία και παίζει μια χαρά.

Ευχαριστώ,
Βασίλης Τριβλής.
