### ISSUE TITLE
Request bearer token issue

### ISSUE THREAD

**Issue by xtheonexuk** [VivaPayments/API#750]
Hi

I'm having an issue with the API Authentication.
I've created a demo account for the development so hopefully the API works on the demo accounts?

I'm following the documentation - https://github.com/VivaPayments/API/wiki/API-Authentication
I've ruled out it being an issue with my PHP code by using cURL on the command line and still getting the same issue.
My command line call is as follows...
`curl --request POST --url https://demo-accounts.vivapayments.com/connect/token --header 'authorization: Basic ODE3YmY4NGQtYzczYS00ZDYwLWJlZDgtY2Y2MGEzZmRjMmVkOnZpdmE=' --header 'content-type: application/x-www-form-urlencoded' --data grant_type=client_credentials`

And the response I'm getting back is...
`{"error":"invalid_client"}`

Any assistance would be appreciated :)

Thanks,
Dave

**Comment by pefremidis** [comment]
Hello,
I am having the same issue.
Trying to implement reccurring payments using card Tokenization and charging Tokenized Cards.
I cannot successfully obtain the access token to move forward.

Thanks

**Comment by xtheonexuk** [comment]
Apparently Viva don't care about helping their customers.
Time to find an alternative payment provider!

**Comment by sdagkas** [comment]
Same here, did anyone find a solution to this?

**Comment by xtheonexuk** [comment]
3 months later. Still no reply. Amazing work guys!

**Comment by matthewrgourd** [comment]
Hi all, sorry for delayed reply. Please see https://github.com/VivaPayments/API/issues/883 which addresses the same issue. We have had some teething issues with the APIs which are hopefully now resolved. Thanks!
