### ISSUE TITLE
Setting Up Plugin

### ISSUE THREAD

**Issue by Simonfbarrett** [VivaPayments/API#751]
Hello, I am hoping someone could please help. I have just signed up to Viva Wallet and I have a WordPress WooCommerce website. Ideally I would like to have a Native system how do I go about integrating Viva Wallet to WooCommerce? Is there a specific plug in I need or do I need to write code which I can't do. Any hell is greatly appreciated. Many thanks

**Comment by matthewrgourd** [comment]
Hi there, apologies for the delayed reply. Our plugins support only the redirect form of checkout. You can find more information about the Viva Wallet for WooCommerce extension here: https://developer.vivawallet.com/e-commerce-plugins/woocommerce Thanks!
