### ISSUE TITLE
After activating module on prestashop 1.7.3 the module  page becomes blank

### ISSUE THREAD

**Issue by astrid2002** [VivaPayments/API#752]
After activating module on prestashop 1.7.3 the module  page becomes blank

i see there are erros with the css and js files of the modules please see screenshot attached 

![download](https://user-images.githubusercontent.com/13542427/53299978-f29b8000-385a-11e9-979e-2374af137163.png)
![screen shot 2019-02-20 at 21 25 10](https://user-images.githubusercontent.com/13542427/53299979-f29b8000-385a-11e9-8f19-6223996f3bf5.png)

**Comment by donfn** [comment]
This is a CORS issue (probably). Are you using cpanel or plesk?

**Comment by astrid2002** [comment]
yes i am using CPanel    On Sunday, February 24, 2019, 5:47:50 PM GMT+4, DONFN <notifications@github.com> wrote:  
 
 This is a CORS issue (probably). Are you using cpanel or plesk?

**Comment by VivaWalletSupport** [comment]
Looks like you are trying to install the complete Viva Payments API repository including numerous docs and plugins. You would only need to pack the specific files for the Prestashop gateway, try attached and close this issue in case it solved the problem. 
[vivawallet.zip](https://github.com/VivaPayments/API/files/2897990/vivawallet.zip)
