### ISSUE TITLE
Redirection URL doesn't work

### ISSUE THREAD

**Issue by tutobo** [VivaPayments/API#753]
Hi ! I need help with the redirection.  We have put the URLs to the viva wallet dashboard on the webshop , but the redirection function is not working,  can you help us?

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

1. Plugin settings (mask the API Key).
2. Viva Wallet payment source settings (include the browsers URL in the screenshot).
3. Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
4. API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by tutobo** [comment]
Dear Viva Wallet,

 

I am sending you the screenshots

 

Ioannis Ypatidis   Robotics Engineer

         Founder - CEO

 





                

Main office:                                    

Asklipiou  str 23 P.C. 16673

Voula , Athens - Greece

url: www.tutobo.com

 

Land line:          +30 2110190907

Cell:                    +3069 55093797

e-Mail:                ioannis@tutobo.com

 

THINK GREEN, DO NOT PRINT UNLESS IT IS NECESSARY 

 

Messages sent by e-mail can be manipulated by third parties. For this reason my e-mail messages are generally not legally binding. This electronic message (including any attachments) contains confidential information and may be privileged or otherwise protected from disclosure. Particular information is intended to be used by the intended addressee only. Please be aware that any disclosure, copy, distribution or use of the contents of this message is prohibited. If you have received this e-mail improperly you are kindly asked to notify the undesigned immediately by e-mail reply and delete it afterwards. Thank you.

**Comment by VivaWalletSupport** [comment]
Please post them at github to be visible.

**Comment by tutobo** [comment]
![viva_api](https://user-images.githubusercontent.com/41436046/53339378-deb15600-390e-11e9-9ad1-5a85211a60b5.PNG)
![viva_plugin](https://user-images.githubusercontent.com/41436046/53339379-deb15600-390e-11e9-8822-0e41165ee85f.PNG)
![viva_plugin1](https://user-images.githubusercontent.com/41436046/53339380-deb15600-390e-11e9-93cb-817db76c8e4f.PNG)
![viva_source](https://user-images.githubusercontent.com/41436046/53339381-deb15600-390e-11e9-82b8-581f4b1b69d7.PNG)

**Comment by VivaWalletSupport** [comment]
In the plugin settings you did not specify the Source Code (5550) and in the payment source you are not using the return URLs as instructed in the readme.txt
Success: index.php?wc-api=wc_vivawallet&vivawallet=success
Fail: index.php?wc-api=wc_vivawallet&vivawallet=fail

In case this solved the problem, please close this issue.

**Comment by tutobo** [comment]
Hi! Yes this worked , thank you very much for the fast reply. 

The issue is solved and closed
