### ISSUE TITLE
When request for token fail with error: Authorization has been denied for this request

### ISSUE THREAD

**Issue by Sujiyama** [VivaPayments/API#754]
Hello i try to get token from live production and i take the below message:
Authorization has been denied for this request

When i try from demo work fine. 
Can you see please what happen?

What ever information you want please tell me 

Thanks

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. What is it you're trying to do? Please send a bit more information if this is still an issue. Thanks!

**Comment by Sujiyama** [comment]
Hi Matthewgourd thanks for your reply and interest at least one person after 4 months (Thanks again really).
I found solution by my self. 
To help other people the problem was to TLS. 
So to fix it i put that in your code : ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
before everything and check the viva url to have https inside and not only http.
