### ISSUE TITLE
PrestaShop Integration Module failing

### ISSUE THREAD

**Issue by richardjsteggles** [VivaPayments/API#755]
Hi I have followed the instructions on the prestashop readme.txt but in my clients website back office the module for VivaWallet uploads but doesnt show in the payments section?

Any reason why this could be?

Thanks

**Comment by VivaWalletSupport** [comment]
Hello ,please check if a previous solved issue helps you.
https://github.com/VivaPayments/API/issues/739

**Comment by VivaWalletSupport** [comment]
In case it has solved your problem, please share your solution and close this issue.

**Comment by richardjsteggles** [comment]
Hi Tom,

No this hasn’t helped at all. The ecommerce plug in installs but it doesn’t show as an option in the payments window.

Thanks

**Comment by richardjsteggles** [comment]
Please see attached

**Comment by VivaWalletSupport** [comment]
Please post any screenshots at github, they do not show in case you send them by email.

**Comment by richardjsteggles** [comment]
Ok thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by richardjsteggles** [comment]
<img width="670" alt="capture - no match integration prestashop" src="https://user-images.githubusercontent.com/47525061/53636293-8d0f1100-3c17-11e9-83fd-f39a62e5fcb6.PNG">

**Comment by VivaWalletSupport** [comment]
Please send me a screenshot of the carrier restrictions.

**Comment by richardjsteggles** [comment]
Can you elaborate please?

**Comment by VivaWalletSupport** [comment]
What version of Prestahop is used?

**Comment by richardjsteggles** [comment]
1.7.4.3

**Comment by VivaWalletSupport** [comment]
Check Payment / Preferences

**Comment by richardjsteggles** [comment]
Hi Tom

This issue is still not resolved

**Comment by richardjsteggles** [comment]
<img width="670" alt="capture - no match integration prestashop" src="https://user-images.githubusercontent.com/47525061/54035987-6d955c80-41b2-11e9-957d-1b11d4aa6b9a.PNG">
<img width="670" alt="capture - no match integration prestashop" src="https://user-images.githubusercontent.com/47525061/54035994-6f5f2000-41b2-11e9-9af2-7c6b5c84511a.PNG">
![inkedapi int - no match_li](https://user-images.githubusercontent.com/47525061/54036005-74bc6a80-41b2-11e9-900a-3bc0fa963435.jpg)

**Comment by richardjsteggles** [comment]
<img width="670" alt="capture - no match integration prestashop" src="https://user-images.githubusercontent.com/47525061/54036069-987fb080-41b2-11e9-8e51-1a6a9e08d5b5.PNG">


![inkedapi int - no match_li](https://user-images.githubusercontent.com/47525061/54036082-a03f5500-41b2-11e9-9b50-f27da847a374.jpg)


<img width="753" alt="screen shot carriers - no match" src="https://user-images.githubusercontent.com/47525061/54036120-afbe9e00-41b2-11e9-8ffa-f74df00206ae.PNG">

**Comment by VivaWalletSupport** [comment]
Could you email admin url/user/pass + ftp credentials to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com for having a look at the problem?
