### ISSUE TITLE
Native Checkout PHP custom / δεν λειτουργεί

### ISSUE THREAD

**Issue by fragogiannis** [VivaPayments/API#756]
Καλησπέρα, έχω PHP custom e-shop και προσπαθώ να εγκαταστήσω το Native checkout. Έχω σετάρει τα πάντα σωστά  χρησιμοποιώντας ακριβώς αυτόν τον κώδικα https://github.com/VivaPayments/API/tree/master/NativeCheckout/PHP

- εχω ανοίξει κανονικά το source code και είναι confirmed
- Το έχω γυρίσει από demo σε www
- Έχω σετάρει MerchantID, api key, sourcecode (Merchant ID: d67bb0f2-6b12-4de1-a28d-142ddb8c43a4)

κάνω submit μια κάρτα και επιστρέφει:

Transaction Succesful with Id :

Δεν επιστρέφει ID, δεν έχει χρεωθεί καμία κάρτα. Μπορεί να με βοηθήσει κάποιος; Τι πηγαίνει λάθος;

Ευχαριστώ!

**Comment by donfn** [comment]
Μπορείς να στείλεις όλο το response που παίρνεις από το curl;

**Comment by fragogiannis** [comment]
Σ' ευχαριστώ για την απάντηση, χρησιμοποιώ ακριβώς το PHP example στο link που εβαλα, δεν μου εμφανίζει κάποιο curl response ή κάποιο άλλο μήνυμα στον browser. Φορτώνει απλά ξανά η φόρμα με τα στοιχεία της κάρτας με μόνο μήνυμα το: Transaction Succesful with Id : και τίποτα άλλο.

(απολογούμαι για τις μέτριες γνώσεις development, φαντάζομαι θα αρκούσαν για να το κάνω να παίξει!)

**Comment by donfn** [comment]
Στο demo δούλεψε κανονικά;

**Comment by fragogiannis** [comment]
Έκανα το print_r, δεν εμφανίζει τίποτα πάλι, άρα είναι empty το response;

Δεν δοκίμασα ποτέ demo, πήγα κατευθείαν στο live!

**Comment by donfn** [comment]
Δοκίμασε το και με echo($response). Λίγο παράλογο να σου βγάζει Transaction Successful με empty response...

Επίσης δοκίμασε το και στο demo περιβάλλον, μπας και έχει κάποιο πρόβλημα το API.

**Comment by donfn** [comment]
P.s. Βάλε και ένα exit() μετά το print ;)

**Comment by fragogiannis** [comment]
Είναι πολύ περίεργο, το έκανα και echo, του έβαλα και το exit; και γυρνάει blank page τώρα (λογικό), εξακολουθεί να είναι empty το response...

**Comment by angsfl** [comment]
Το ίδιο πρόβλημα ακριβώς έχω και εγώ. Μπορεί κάποιος να το κοιτάξει?

**Comment by donfn** [comment]
Από το nativecheckoutclass.php σβήσε την γραμμή που λέει :

curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

**Comment by angsfl** [comment]
Δεν αρκεί η διαγραφή. Υπάρχει αλλαγή στον τρόπο που το curl ελέγχει τον peer.  Αν προστεθεί ό έλεγχος για τον τύπο του λάθους ως ακολούθως φαίνεται
		// Do the POST and then close the session
		$response = curl_exec($session);
		if ($response === FALSE) { die(curl_error($session));  }
κάνουμε die για να δούμε το πραγματικό λάθος. 

Η εύκολη λύση παντως είναι πριν από το SSL να μπει γίνει CURLOPT_SSL_VERIFYPEER -> FALSE

Ο κώδικας θα γίνει:

curl_setopt($session, CURLOPT_SSL_VERIFYPEER, FALSE); 
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');

**Comment by donfn** [comment]
Όχι όχι όχι όχι!!! Μην απενεργοποιήσεις για κανένα λόγο τον έλεγχο SSL... Η
viva σε ανάρτησή της στα FAQ έχει πει ότι δεν θα υποστηρίζει πλέον το
TLSv1, λόγω των κανονισμών PCI-DSS. Σίγουρα θα πρέπει να διαγράψεις την
γραμμή ή να αλλάξεις την βερσιόν σε 1.2 ή 1.3.
