### ISSUE TITLE
Viva: 2 issues /Redirection to original website/ Obligation to put his telephone number (CC-1070529)

### ISSUE THREAD

**Issue by Georges896** [VivaPayments/API#757]
Hello,
Good evening

The issue concerning payments has been well solved, but apparently, after the successful payment, the link is not redirected after a few seconds to the site Freewinshopping.com. It should normally be notified as on other sites "you are about to be redirected to your site merchant''

Can you please also delete during the process of the payment the obligation for the customer to put his telephone number, this could stop his purchase.

Thank you in advance for solving it's two new issues
Kind Regards

Freewinshopping

**Comment by VivaWalletSupport** [comment]
Hello, please please provide the following 4 screenshots:

1. Plugin settings (mask the API Key).
2. Viva Wallet payment source settings (include the browsers URL in the screenshot).
3. Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
4. API Access page (mask API Key, include the browsers URL in the screenshot).

The phone number is obligatory.

**Comment by Georges896** [comment]
Thank you for your feedback,

The team checks again with the updated version, the issue should normally be solved.
