### ISSUE TITLE
"The transaction failed" issue

### ISSUE THREAD

**Issue by dariusapanas** [VivaPayments/API#758]
Hi, have successfully integrated Viva Wallet into Prestashop and tried to do the test buy. On the very last step (after bank authorisation) the message pops up "The transaction failed". Tried with couple of different cards and all of them are working fine everywhere else. Please help. Thanks

**Comment by VivaWalletSupport** [comment]
Hello, has the transaction been registered successfully in your Viva account? If not, did you try an amount of 30 cents with a valid card?

**Comment by dariusapanas** [comment]
Hi. 
I have registered the website in my Viva account. Don’t know if anything else has to be registered. I tried with the £1 and the cards I been trying were valid. 

Kind Regards
Darius

**Comment by VivaWalletSupport** [comment]
Has the **transaction** been registered successfully in your Viva account?

**Comment by dariusapanas** [comment]
It says "No records to display" under sales if this is what you mean.

**Comment by VivaWalletSupport** [comment]
Unfortunately I cannot check why your card transaction fails, in case you have another card to try..

**Comment by dariusapanas** [comment]
Hi,
I tried all different cards but it fails every time after banks
authorisation. All the cards are working and have money on it. Please help
as I really need my site up and running asap. Thanks

Regards
Darius

**Comment by VivaWalletSupport** [comment]
What version of Prestashop is used?

**Comment by dariusapanas** [comment]
Prestashop 1.7.3.3

Kind Regards
Darius

**Comment by VivaWalletSupport** [comment]
Create a demo account at https://demo.vivapayments.com and use attached plugin to connect.
Use the demo card credentials to make a test.
[vivawallet.zip](https://github.com/VivaPayments/API/files/2930525/vivawallet.zip)

**Comment by dariusapanas** [comment]
Hi, I can't install the plugin supplied. It says server code 403. Will ask
my developer try to do it for me as I am not so technical. Will update you
shortly.

**Comment by dariusapanas** [comment]
Is is possible on the plugin configuration I potting the wrong API code?
The one I have is from my viva wallet account API access and containing 3
letters, 2 symbols and 1 number. I hyperactive in blue. I copied and pasted
that one. Or it has to be done somehow else?

**Comment by VivaWalletSupport** [comment]
For the demo plugin you have to use the merchant  id, api key and source code from your demo account.

**Comment by astrid2002** [comment]
Hello the problem we are having with the module is when i make a payment  i am redirected to this link https://www.vivapayments.com/web/newtransaction.aspx  and there i get a 404 error

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by astrid2002** [comment]
Hello i did not understand what you wanted to have i am sending you the screenshot of the plugin settings and the link of the website 

https://www.labnature.co.uk/

![module_setting](https://user-images.githubusercontent.com/13542427/54202834-53c58380-44ea-11e9-9fdd-0713ce0a85ea.png)

**Comment by VivaWalletSupport** [comment]
See for example the 4 screenshots from a previous post, include the browsers URL and only mask the API Key.
https://github.com/VivaPayments/API/issues/772

**Comment by dariusapanas** [comment]
Please find attached

**Comment by dariusapanas** [comment]
<img width="1245" alt="Screenshot 2019-03-12 at 21 43 51" src="https://user-images.githubusercontent.com/47757964/54239394-fa257f00-4512-11e9-89fa-a63470dcea75.png">
<img width="1250" alt="Screenshot 2019-03-12 at 21 45 30" src="https://user-images.githubusercontent.com/47757964/54239397-fc87d900-4512-11e9-9fac-7754818bf9cc.png">
<img width="1241" alt="Screenshot 2019-03-12 at 21 47 32" src="https://user-images.githubusercontent.com/47757964/54239403-ff82c980-4512-11e9-9626-5b1e7f8195e7.png">
<img width="1231" alt="Screenshot 2019-03-12 at 21 51 03" src="https://user-images.githubusercontent.com/47757964/54239411-027dba00-4513-11e9-89f6-f6be83b93619.png">
<img width="1238" alt="Screenshot 2019-03-12 at 21 56 48" src="https://user-images.githubusercontent.com/47757964/54239415-04477d80-4513-11e9-923e-a105d5d36fd0.png">

**Comment by VivaWalletSupport** [comment]
Are you using the demo plugin I sent you the last time? If so, the first screenshot from viva is from the live account and you should use the credentials from your demo account in the plugin. Unfortunately the first part of the URL from the viva payment sources you posted is missing, so I cannot see if they are from the live or demo account. The 4th screenshot (payment source settings) is wrong, please consult the readme.txt from the module how to setup the payment source (using redirection method).
