### ISSUE TITLE
Invalid merchant public key error message

### ISSUE THREAD

**Issue by ottotilla** [VivaPayments/API#759]
Hi, i have followed your instructions for to do the 'Simple' integration and when i try to make a payment i get an  'Invalid merchant public key' error message. i followed the instructions for obtaining this key from the following in the documentation on the 'Simple' integration:

![vp1](https://user-images.githubusercontent.com/11995626/53634210-7c5b9c80-3c11-11e9-8308-5ad4e9bc1138.jpg)

Following these instructions, i am getting the 'Public key' as illustrated in the image below:
![vp2](https://user-images.githubusercontent.com/11995626/53634240-939a8a00-3c11-11e9-8994-f7bf97557f57.jpg)

i am using https://demo.vivapayments.com/ as the data-vp-baseurl data property and have verified from the form that the public key that i have obtained from the API setting above is exactly as it appears in our configuration setting.

i would appreciate it if you could explain why i am getting this error message and where i can obtain a 'valid' key. i am presuming this is a 'demo' key since there is no obvious distinction visible in the API Settings for our account - there is just 'Public Key'

Thanks.

**Comment by kostGX** [comment]
Hello @ottotilla,

Have you tried using a Source or Website/App (Menu > Sales > Online Payments > Websites/Apps that is Simple and Native checkout enabled?

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/3908736/53698948-c5674880-3deb-11e9-9b4c-08b5389068ed.png">

**Comment by donfn** [comment]
You need to visit https://demo.vivapayments.com and create a demo account.

**Comment by ottotilla** [comment]
Hi, 

Thanks for getting back to me. i have done both of the things suggested above and there is no difference - i still get the same 'Invalid merchant public key' message. You might want to consider adding the point about the 'Editing Payment Source' to you docs - there was no mention of that particular step that i could see in the docs for 'Simple' integration. 

Although i have done the things suggested, i am still having the issue that i raised - any further suggestions? i have followed all of the steps, and have verified that all the relevant paramas are being passed as per the docs but still getting the error. Could it be something to do with strange characters in the Public Key that i have? It definitely doesn't look like the one in the docs, but since it was issued by yourselves, i obviously have no control over this. It contains '/' and '+' characters which i would think might cause encoding problems... Obviously, i have no wish to publish that key in this support forum, so perhaps you could take a look at that. 

Many thanks.

**Comment by donfn** [comment]
Can you confirm that you've taken the public key from the demo dashboard? (http://demo.vivapayments.com/en-gb/signin)

The demo platform has nothing to do with the production one. Try to change your base URL to 
www.vivapayments.com . If the popup works, then you are your production Public Key.

**Comment by ottotilla** [comment]
Hi, thanks for getting back to me with this. This allowed me to get past the 'Invalid public key' issue. The documentation could be made more clear on the Wiki that you **have** to create a demo account - it is obviously not an optional step.
