### ISSUE TITLE
API Call Failed

### ISSUE THREAD

**Issue by vasilis1984** [VivaPayments/API#76]
Καλησπέρα σας,

έχω ενσωματώσει τον κώδικα για create order και έχω αλλάξει τα στοιχεία (MerchantId, APIKey) με τα δικά μου.

Χρησιμοποιώντας το demo περιβάλλον, μου βγάζει το παρακάτω error

"API Call failed! The error was: Invalid or inactive reseller with id XXXXXXXXXXXXXXXXX"

Χρησιμοποιώντας το live περιβάλλον, μου βγάζει μια χαρά τα παρακάτω:

"Your Order Code is: ΧΧΧΧΧΧΧΧΧΧ

To simulate a successfull payment, use the credit card 4111 1111 1111 1111, with a valid expiration date and 111 as CVV2.
Make Payment"

Το Make Payment, που είναι link με οδηγεί στο http://demo.vivapayments.com/web/newtransaction.aspx?ref=ΧΧΧΧΧΧ , όπου το ΧΧΧΧΧ είναι το Order Code που μου έχει επιστρέψει το API σας. Όταν πατάω το link, τότε μου βγάζει η σελίδα σας "403 - Forbidden: Access is denied."  Βέβαια, έχω δοκιμάσει και στο http://vivapayments.com/web/newtransaction.aspx?ref=ΧΧΧΧΧΧ αλλά το αποτέλεσμα είναι το ίδιο.

Ευχαριστώ,
Βασίλης.

**Comment by vasilis1984** [comment]
Κάποια ενημέρωση;

**Comment by defilerc** [comment]
Καλησπέρα @vasilis1984 ,

Μπορείτε να δοκιμάσετε τη λύση που περιγράφεται στο thread https://github.com/VivaPayments/API/issues/144

και να μας πείτε αν αυτό έλυσε το πρόβλημά σας;

Ευχαριστούμε πολύ.

**Comment by defilerc** [comment]
Κλείνουμε το issue, λόγω απουσίας κάποιας δραστηριότητας για πάνω από ένα μήνα. 

Σε περίπτωση που ακόμα ενδιαφέρεστε για υποστήριξη και δεν έχετε επιλύσει το πρόβλημά σας, μπορείτε να ξανά ανοίξετε το συγκεκριμένο issue ή να δημιουργήσετε κάποιο νέο.

Με εκτίμηση
