### ISSUE TITLE
Error : Signature not verified

### ISSUE THREAD

**Issue by lobbbyboy** [VivaPayments/API#760]
Hello Kosta and team!

I'm having the regular issue :)
I added both my Merchant ID and Store Token, but it doesn't seem to work.

My store URL is: https://mastic-spa.myshopify.com/

Thanks,
Savvas

**Comment by kostGX** [comment]
Hi Savva,

Long time no see :) Hope all is well.

 This error usually has to do with incorrect config.

Please confirm the below:
1) You got your Store Token credentials sent via email by our support by submitting this form: https://landing.vivawallet.com/shopify
2) Input the correct details Merchant ID / Store Token in your Shopify admin area (as shown in screenshot below).
3) Make sure "test mode" is not enabled. You can "test on production", so to speak, with valid cards and then cancel/refund the transactions through your Viva Wallet Account UI.

Hope this helps and thanks for choosing us :) 

![screenshot 2019-03-01 at 14 58 45](https://user-images.githubusercontent.com/3908736/53698836-96040c00-3dea-11e9-8cd9-6b7afd3552b5.png)

**Comment by lobbbyboy** [comment]
Ela Kosta! I've already done everything you mention :)
But, still no luck. Could you please have a look?

Thanks,
Savvas

**Comment by kostGX** [comment]
Hello Savva,

I'm closing the issue since we sorted it.

**Comment by nutraleaf** [comment]
I am having the same issue adding viva to my second catalogue please can someone help ?
