### ISSUE TITLE
Refund Action Disabled

### ISSUE THREAD

**Issue by JamesAntropy** [VivaPayments/API#761]
I'm trying to add refund functionality to the VivaWallet OC extension, but I'm getting the following error: 

"The specified api action is disabled for the merchant 9d69ef26-56d3-48ba-9476-265414ab1465, please consult the documentation"

However refunds are enabled here: http://james.antropy.co.uk/images/screenshots/28df4d7f1.jpg is there somewhere else I need to enable refunds?

I'm making a DELETE request to https://demo.vivapayments.com/api/transactions/63a2c79c-f75e-41fc-80d5-88575797b15b with the arguments: Amount=100&ActionUser=development

The full response is:
```
{
  "Emv": null,
  "Amount": null,
  "StatusId": "E",
  "CurrencyCode": null,
  "TransactionId": null,
  "ReferenceNumber": null,
  "AuthorizationId": null,
  "RetrievalReferenceNumber": null,
  "ErrorCode": 403,
  "ErrorText": "The specified api action is disabled for the merchant 9d69ef26-56d3-48ba-9476-265414ab1465, please consult the documentation",
  "TimeStamp": "2019-03-01T16:27:07.8581921+02:00",
  "CorrelationId": null,
  "EventId": 0,
  "Success": false
}
```

**Comment by kostGX** [comment]
Hello @JamesAntropy you should be ok now. 

Please try again.

**Comment by JamesAntropy** [comment]
Hi @kostGX I'm still getting the same error I'm afraid:

```
{
  "Emv": null,
  "Amount": null,
  "StatusId": "E",
  "CurrencyCode": null,
  "TransactionId": null,
  "ReferenceNumber": null,
  "AuthorizationId": null,
  "RetrievalReferenceNumber": null,
  "ErrorCode": 403,
  "ErrorText": "The specified api action is disabled for the merchant 9d69ef26-56d3-48ba-9476-265414ab1465, please consult the documentation",
  "TimeStamp": "2019-03-06T12:27:55.707644+02:00",
  "CorrelationId": null,
  "EventId": 0,
  "Success": false
}
```

**Comment by kostGX** [comment]
@JamesAntropy sorry for the inconvenience. You should be ok now.

There was an issue with the refund permissions on the demo account.

**Comment by JamesAntropy** [comment]
@kostGX,
 Now I have a different issue, if I do a partial refund it works but then if I try and refund the remaining I get the following response:

```
{
  "Emv": null,
  "Amount": null,
  "StatusId": "E",
  "CurrencyCode": null,
  "TransactionId": null,
  "ReferenceNumber": null,
  "AuthorizationId": null,
  "RetrievalReferenceNumber": null,
  "ErrorCode": 403,
  "ErrorText": "Invalid transaction. The transaction 63a2c79c-f75e-41fc-80d5-88575797b15b does not allow recurring charge",
  "TimeStamp": "2019-03-14T14:43:49.6596366+02:00",
  "CorrelationId": null,
  "EventId": 0,
  "Success": false
}
```

**Comment by JamesAntropy** [comment]
Hi @kostGX, have you had a chance to look at this yet?

**Comment by kostGX** [comment]
Hello @JamesAntropy,

I just tried Refunding on a demo transaction 2 times and I didn't have a problem.

I recommend that you post here the requests exactly as you send them so we can look into them further.

Best regards,
Kostas

`{
  "Emv": "910A1FEE5D2612BF809E3030",
  "Amount": 10.00,
  "StatusId": "F",
  "CurrencyCode": "978",
  "TransactionId": "7b1c7efb-c31f-499f-b2ee-13596794d332",
  "ReferenceNumber": 75656,
  "AuthorizationId": "075656",
  "RetrievalReferenceNumber": "908610075656",
  "ErrorCode": 0,
  "ErrorText": null,
  "TimeStamp": "2019-03-27T12:24:01.3232965+02:00",
  "CorrelationId": null,
  "EventId": 0,
  "Success": true
}


refund :
{
  "Emv": null,
  "Amount": 5.0,
  "StatusId": "F",
  "CurrencyCode": "978",
  "TransactionId": "c755a25d-8aad-4f52-81fa-b88328ba2d1b",
  "ReferenceNumber": 75684,
  "AuthorizationId": "75684",
  "RetrievalReferenceNumber": "908610075684",
  "ErrorCode": 0,
  "ErrorText": null,
  "TimeStamp": "2019-03-27T12:56:19.4601866+02:00",
  "CorrelationId": null,
  "EventId": 0,
  "Success": true
}

second refund : {
  "Emv": null,
  "Amount": 2.0,
  "StatusId": "F",
  "CurrencyCode": "978",
  "TransactionId": "6b8adeed-7fea-4f87-bf31-d5768567f5aa",
  "ReferenceNumber": 75686,
  "AuthorizationId": "75686",
  "RetrievalReferenceNumber": "908610075686",
  "ErrorCode": 0,
  "ErrorText": null,
  "TimeStamp": "2019-03-27T12:57:35.7044623+02:00",
  "CorrelationId": null,
  "EventId": 0,
  "Success": true
}`

**Comment by JamesAntropy** [comment]
Hi @kostGX,

I'm making a DELETE request to https://demo.vivapayments.com/api/transactions/63a2c79c-f75e-41fc-80d5-88575797b15b

with the variables: Amount=100&ActionUser=development

This is my response:
```
{
  "Emv": null,
  "Amount": null,
  "StatusId": "E",
  "CurrencyCode": null,
  "TransactionId": null,
  "ReferenceNumber": null,
  "AuthorizationId": null,
  "RetrievalReferenceNumber": null,
  "ErrorCode": 400,
  "ErrorText": "Negative or zero amount in reversal, transaction 63a2c79c-f75e-41fc-80d5-88575797b15b",
  "TimeStamp": "2019-04-02T13:19:25.4875313+03:00",
  "CorrelationId": null,
  "EventId": 0,
  "Success": false
}
```

**Comment by JamesAntropy** [comment]
Hi @kostGX any thoughts on this?

**Comment by JamesAntropy** [comment]
@kostGX ?

**Comment by matthewrgourd** [comment]
Hi @JamesAntropy is this still causing you issues? Do you have any more information you can send through?

**Comment by matthewrgourd** [comment]
Hi @JamesAntropy is this still causing you issues? Do you have any more information you can send through?

**Comment by JamesAntropy** [comment]
Hi @matthewrgourd yes I'm still having an issue, while it seems to refund the total amount, I can't seem to do a partial refund.

Partial refund:
`{
   "Emv":null,
   "Amount":null,
   "StatusId":"E",
   "CurrencyCode":null,
   "TransactionId":null,
   "ReferenceNumber":null,
   "AuthorizationId":null,
   "RetrievalReferenceNumber":null,
   "ThreeDSecureStatusId":null,
   "ErrorCode":400,
   "ErrorText":"PaymentsInvalidAmountForVoid",
   "TimeStamp":"2019-07-24T11:50:43.2120691+03:00",
   "CorrelationId":null,
   "EventId":0,
   "Success":false
}`

Full refund:
`{
   "Emv":"910A1FEE5D2612BF809E3030",
   "Amount":11.38,
   "StatusId":"F",
   "CurrencyCode":"826",
   "TransactionId":"237898a8-9e69-479c-a88f-396ec759941b",
   "ReferenceNumber":96490,
   "AuthorizationId":null,
   "RetrievalReferenceNumber":"920508096489",
   "ThreeDSecureStatusId":2,
   "ErrorCode":0,
   "ErrorText":null,
   "TimeStamp":"2019-07-24T11:55:16.7958372+03:00",
   "CorrelationId":null,
   "EventId":0,
   "Success":true
}`

**Comment by matthewrgourd** [comment]
Hi @JamesAntropy , sorry, could you send a full request log for the partial refund?

**Comment by JamesAntropy** [comment]
Hi @matthewrgourd sure, I'm posting 
`Amount=500&ActionUser=development`
to
`https://demo.vivapayments.com/api/transactions/c7d3f558-0ac8-41fc-93b2-8b940b440ed3?amount=500`
this is the response:
```json
{
   "Emv":null,
   "Amount":null,
   "StatusId":"E",
   "CurrencyCode":null,
   "TransactionId":null,
   "ReferenceNumber":null,
   "AuthorizationId":null,
   "RetrievalReferenceNumber":null,
   "ThreeDSecureStatusId":null,
   "ErrorCode":400,
   "ErrorText":"PaymentsInvalidAmountForVoid",
   "TimeStamp":"2019-07-25T10:29:50.8839258+03:00",
   "CorrelationId":null,
   "EventId":0,
   "Success":false
}
```

**Comment by matthewrgourd** [comment]
Hi @JamesAntropy I've checked with our development team and partial refunds are definitely working ok from an API perspective. The issue here is that partial refunds are only supported for transactions that have been cleared. If a credit card transaction has not been cleared yet, then the only action that can be performed is a full reversal (void). This is what the error indicates. Thanks!

**Comment by JamesAntropy** [comment]
Hi @matthewrgourd thanks, for clearing that up, is there anyway to clear a transaction in the demo system so that I can test partial refunds?

**Comment by matthewrgourd** [comment]
Hi @JamesAntropy Our developer has come back to me with the information that clearance runs every night at 2am. You will therefore have to wait until tomorrow to test. Hope this helps!

**Comment by adrianblynch** [comment]
Hi @matthewrgourd - Can I take from this that refunds can't be issued until after 2am the next day?

What timezone is that?

Thanks.

**Comment by matthewrgourd** [comment]
Hi @adrianblynch it's Greek time as that's where our platform is based. So you we could say midnight GMT but it could be earlier or later depending on a number of factors. Hope that helps!
