### ISSUE TITLE
WooCommerce - Payment page not loading

### ISSUE THREAD

**Issue by richardjsteggles** [VivaPayments/API#762]
I have at least 4 clients who are reporting that their customers are not able to see the payments page or are not being redirected at the payment stage?

**Comment by VivaWalletSupport** [comment]
Hello, are you using a ready made plugin to connect and if so, who is the plugin author?

**Comment by richardjsteggles** [comment]
It is a VivaWallet plugin the author is VivaWallet

**Comment by VivaWalletSupport** [comment]
Please provide an URL to the location from where the plugin was downloaded.

**Comment by richardjsteggles** [comment]
I have the plugin on my desktop???

**Comment by VivaWalletSupport** [comment]
Lets try something else, could you post a screenshot of the plugin settings?

**Comment by richardjsteggles** [comment]
How it appears on WooCommerce?

**Comment by VivaWalletSupport** [comment]
That would be great, also post it at Github, do not send it by email and mask the API Key.
