### ISSUE TITLE
Woocommerce - Payments cancelling automatically, some going through, others not.

### ISSUE THREAD

**Issue by swapsy123** [VivaPayments/API#763]

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by swapsy123** [comment]
![shot1](https://user-images.githubusercontent.com/33666663/53764282-c3bd8380-3ec4-11e9-9a1e-6151072709fd.PNG)
![shot2](https://user-images.githubusercontent.com/33666663/53764290-c5874700-3ec4-11e9-88bb-8df5733b5a27.PNG)

**Comment by VivaWalletSupport** [comment]
Please provide me also with the following 3 screenshots (see plugins readme.txt how to setup a payment source in your Viva account)):

Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by matthewrgourd** [comment]
Hi @swapsy123 , I'm assuming this is no longer an issue or you have found a solution elsewhere. Thanks!
