### ISSUE TITLE
Empty response from Charge request

### ISSUE THREAD

**Issue by ottotilla** [VivaPayments/API#765]
Hi,
In our demo site 'Simple' checkout implementation, the user enters card data (using 4111 1111 1111 1111, Exp 12/20 and CVV 111 as the test data) we get a vivaWalletToken back successfully, but when i try to do a charge using exactly the code in your documentation in the wiki - ie:

public class TransactionResult
{
    public int ErrorCode { get; set; }
    public decimal Amount { get; set; }
    public string ErrorText { get; set; }
    public Guid TransactionId { get; set; }
}

public async Task<TransactionResult> ChargeAsync(string vivaWalletToken)
{
    var cl = new RestClient("https://demo.vivapayments.com/api/") {
        Authenticator = new HttpBasicAuthenticator("your_merchant_id", "your_api_key")
    };
    var request = new RestRequest("transactions", Method.POST) {
        RequestFormat = DataFormat.Json
    };
    request.AddParameter("PaymentToken", vivaWalletToken);
    var response = await cl.ExecuteTaskAsync<TransactionResult>(request);
    return response.ResponseStatus == ResponseStatus.Completed &&
        response.StatusCode == System.Net.HttpStatusCode.OK ? response.Data : null;
}

i get the following response back:
"StatusCode: 0, Content-Type: , Content-Length: 0"

i am using the merchant id and api key from our 'demo' account, and making the call to the same url as is in the code above (https://demo.vivapayments.com/api/)

Is there some way for you to track the requests to your server if i provide the vivaWalletToken? i am not getting any useful information back to assist in diagnosing the issue. There is no exception being thrown or anything like that - just an empty response with response.Data being null, so no useful info provided there either. Any ideas what the issue may be?

Many thanks.

**Comment by donfn** [comment]
From my personal experience with the API, you may get an empty response when you use an unsupported or deprecated TLS version on your client.

I don't know ASP.NET very well, but I found this snippet:

System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12

This will set your TLS version to 1.2 . Hope I helped.

**Comment by ottotilla** [comment]
Hi donfn,

Many thanks for your helpful response - i tried that and it worked! i was testing on my local machine - the server  definitely has the correct version of TLS on it as we have previously upgraded this to use TLS 1.2, but evidently not so locally. You have been a great help - much appreciate your kind assistance.
