### ISSUE TITLE
Simple integration popup always fails on first attempt, works on second attempt

### ISSUE THREAD

**Issue by ottotilla** [VivaPayments/API#766]
Hi,

With our 'Simple' integration, the popup displays and i complete it as per the image below. When you click 'Pay £xxx now', it always appears to fail with the red displayed in the button as per the image below.

![firsttry](https://user-images.githubusercontent.com/11995626/53803845-dd4ee180-3f3d-11e9-8ab9-f54f6b58bceb.jpg)

i close the popup with the 'x' at the top right corner and then immediately click our page button to display the popup again which i complete using exactly the same details as per the below, except that on the second attempt, it succeeds as per the image below, automatically closes and then we process the vivaWalletToken that is sent to us.

![secondtry](https://user-images.githubusercontent.com/11995626/53803978-2ef76c00-3f3e-11e9-8642-4734fafe2988.jpg)

Any idea why it consistently fails on the first attempt every time even though i use exactly the same card details and the same details are posted on the second attempt where is succeeds?

Many thanks.

**Comment by matthewrgourd** [comment]
Hi there, apologies for the lack of reply previously. We have issues with Simple Checkout in certain browsers. If this applies to you, please use [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) instead. Thanks!
