### ISSUE TITLE
 502 [ErrorText] => Transaction failed

### ISSUE THREAD

**Issue by tolgakocmh** [VivaPayments/API#769]
Are there any detailed documents regarding the integration or the error codes?
We need to learn more about this error so we can brief our customer. 

 [Emv] => 
    [Amount] => 430
    [StatusId] => E
    [CurrencyCode] => 978
    [TransactionId] => 233a1e7c-451e-4ba9-bff8-53823f708d9a
    [ReferenceNumber] => 239223
    [AuthorizationId] => 
    [RetrievalReferenceNumber] => 906020239223
    [ErrorCode] => 502
    [ErrorText] => Transaction failed
    [TimeStamp] => 2019-03-01T22:54:48.9272969+02:00
    [CorrelationId] => 
    [EventId] => 10013
    [Success] =>

**Comment by matthewrgourd** [comment]
Hi there, our error code information is included on the following page in the Viva Wallet Developer Portal:

https://developer.vivawallet.com/api-reference-guide/error-code-information/

Thanks!
