### ISSUE TITLE
Shopify integration

### ISSUE THREAD

**Issue by aloha23** [VivaPayments/API#77]
Hello!

We have an eshop - sunofabeach.com which is created with Shopify - and we want to know if we can integrate Viva Payments as a payment gateway.

Has somebody done that integration in the past?

Please let me know - thanks,
Kriton

**Comment by aloha23** [comment]
Could you please get back to me on that question plz

**Comment by dmihos** [comment]
Hi Kriton
We can only officially support you if you plan to make direct calls to our API.
There is no official Shopify plugin for Viva Payments.
You can leave this issue open though, in case someone has successfully done it and wants to drop by and help.

**Comment by aloha23** [comment]
If you check here there are quite a few users that are asking for it -
https://ecommerce.shopify.com/c/payments-shipping-fulfilment/t/post-your-gateway-requests-here-136389#comment-202952


On 5 May 2016 at 14:10, dmihos <notifications@github.com> wrote:

> Hi Kriton
> We can only officially support you if you plan to make direct calls to our
> API.
> There is no official Shopify plugin for Viva Payments.
> You can leave this issue open though, in case someone has successfully
> done it and wants to drop by and help.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/VivaPayments/API/issues/77#issuecomment-217126481>
>



-- 
*Kriton RountosCambo Industries*
*Office Tel: (+30) 213 005 3625*

*Mobile Tel: (+30) 693 6756 128kriton@camboindustries.com
<kriton@camboindustries.com>www.camboindustries.com
<http://www.camboindustries.com/>*

**Comment by ashukasama** [comment]
@aloha23 I feel we can help you to create viva payment gateway using shopify app + alternative payment gateway.

**Comment by aloha23** [comment]
@ashukasama sounds interesting - can you please tell me how you feel you can do that?

**Comment by ashukasama** [comment]
@aloha23 We will create alternative payment gateway for you which will communicate with shopify app to handle order etc. We can have further discussion on skype : niteshkasma (I will be available ) or email : shopify@lucentinnovation.com. 👍
