### ISSUE TITLE
Shopify integration and installment payments

### ISSUE THREAD

**Issue by georgekpc** [VivaPayments/API#770]
Hi,

I have a Shopify website and we successfully use your service for payments.
We would like to make installment payments available on our website. However, when we contacted your support they told us that we should make this change on our end (shopify admin panel). Of course there is no such option on payment settings section of Shopify. This answer does not make any sense as clients leave Shopify and get redirected to your platform to checkout. 
Could you please advice us how to enable installment payments?

Thanks

**Comment by matthewrgourd** [comment]
Hi @georgekpc for Shopify integrations we only support checkout with redirection and one-off payments. For recurring and API-based payments, you should see:
	
- https://developer.vivawallet.com/online-checkouts/simple-checkout
- https://developer.vivawallet.com/online-checkouts/native-checkout-v2
 - https://developer.vivawallet.com/api-reference-guide/payment-api-details/create-recurring-transaction
 - https://developer.vivawallet.com/api-reference-guide/payment-api/card-tokenization

Hope this helps and sorry for the delayed reply!
