### ISSUE TITLE
jQuery dependency in Native Checkout

### ISSUE THREAD

**Issue by joergac** [VivaPayments/API#771]
I just wanted to ask if there are any plans to remove jQuery as a dependency. If not any chance to implement another library for React or Vue.js that doesn't require jQuery?

Thanks in advance

**Comment by joergac** [comment]
I suppose that's a no @VivaWalletSupport?

**Comment by dkladis** [comment]
Hello guys!

I have the same issue. Is there some way that we could use Native Checkout in ReactJS without jQuery dependency?

Thanks!
