### ISSUE TITLE
Payment taken but not hooking back to WooCommerce.

### ISSUE THREAD

**Issue by Bcheets** [VivaPayments/API#772]
We are using the latest versions of Wordpress and Woocommerce.

Payments are being taken from viva but nothing is hooking back to the website to tell woocommerce that the payment has been taken, so eventually the order defaults to cancelled and no notification is sent to the site admins to inform of the new order.

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by Bcheets** [comment]
![api_access](https://user-images.githubusercontent.com/4192329/53954946-9690f100-40cf-11e9-8c87-9f2ee86be4d7.jpg)
![store_source](https://user-images.githubusercontent.com/4192329/53954947-97298780-40cf-11e9-82ad-1194f28be759.png)
![plugin_settings](https://user-images.githubusercontent.com/4192329/53954948-97298780-40cf-11e9-88b9-3c2bba64fb3d.jpg)
![website_apps](https://user-images.githubusercontent.com/4192329/53954949-97298780-40cf-11e9-81fc-d31a2b59811f.png)

**Comment by VivaWalletSupport** [comment]
You sent twice: Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
Both with different source codes (5088 and 7455 / Default), which one is used?

Also you missed to send a screenshot from the payment source settings.

**Comment by Bcheets** [comment]
Ive sent 4 different screenshots, I don't know if some of these duplicate what you are asking. The control panel is not very clearly set out and there is no knowledge base or 'Help' search function to assist people who are new to viva. 

On which link would we find the payment source settings you are asking for? 

The image I attached of the Plugin settings shows we are using Source Code 5088 as directed by the sales support department.

**Comment by VivaWalletSupport** [comment]
The payment source to connect your website is located at:
https://user-images.githubusercontent.com/4192329/53954949-97298780-40cf-11e9-81fc-d31a2b59811f.png

You would use in the plugin settings Source Code 7455 (5088 is for a physical pos/device to capture payments). Click on the 7455 source in your Viva account to view the settings and make a screenshot to check these settings.

**Comment by VivaWalletSupport** [comment]
In case the problem was solved, please close this issue. Otherwise post the requested screenshot.

**Comment by Bcheets** [comment]
The incorrect Source Code is what the sales department advised, they told us we had to make a physical store and put that in as the source, so there needs to be some communication to give the sales team the correct method, there is no knowledge base, so basically no-one (customer or sales team) is given guidance how to set this up.

Anyway . . . we have changed the Source code to the one you suggested and the Vivawallet system now fails to take payment and then redirects the user to this page, a 404 with a url that means nothing to our website, Ive attached an image for you to see the URL. In woocommerce the order is still showing as pending payment, so now there is no payment at all and no hook.

With other payment gateways, we tend to set up APIs on one page, (rather than 3 different ones) we are also usually asked to provide a Success or Failure URL, do we also have to generate our own webhook's on a fourth page with Vivawallet, Is so, where is this? 

Why is there no provided guidelines or knowledge base for this payment gateway system? It quite an important thing to have direction on and get right. 

I have also attached a screengrab of the info  provided when we click on the 7455 source code, we don't know if this is correct as there are no instructions as to what is correct. 


![unknown](https://user-images.githubusercontent.com/4192329/53985455-8a2e8780-4113-11e9-883c-62a18921e149.png)
![screen shot 2019-03-07 at 20 02 30](https://user-images.githubusercontent.com/4192329/53985658-23f63480-4114-11e9-8dd3-922e6e8f5f5d.png)

**Comment by VivaWalletSupport** [comment]
Please follow the installation/setup instructions as provided by the readme.txt file that came with the plugin:
https://github.com/VivaPayments/API/blob/master/Plugins/wordpress/vivawallet-for-woocommerce/readme.txt

Correct the integration method in the payment source to redirection.

**Comment by Bcheets** [comment]
This IS helpful, we simply uploaded the plugin zip that was emailed to us. Maybe this should be on the front end of the website somewhere for  people to follow?

I have one question regarding this please - 
Which  'Event Type' do we need to use for the webhook to  "assure the order will be handled
correctly in case the customer does not return to the estore after the transaction"  ?

**Comment by VivaWalletSupport** [comment]
You would use the Transaction Payment Created event type for that. In case the problems has been solved please close this issue, otherwise let me know how I can help.

**Comment by Bcheets** [comment]
Thanks for your help with this, The system now seems to be working!

Some suggestions to make your job easier in the future and allow you to focus on more important things . . .  .  it would be good to have that 'Read Me' text displaying on a page at VivaWallet.com with download links for the various plugins, also the sales team need to be trained properly about how to set up, again they would also benefit from a set up page on the site / knowledge base.

Thanks again for your patience.
