### ISSUE TITLE
There is no button!

### ISSUE THREAD

**Issue by sekeriz** [VivaPayments/API#775]
Hi,
I have installed the extension in opencart 2.3.0.2,  I have set up the viva account and everything but I see no button at the 4th step of the checkout, so the client cannot complete the purchase.

**Comment by VivaWalletSupport** [comment]
Hello, could you provide a link from where you got the extension?

**Comment by sekeriz** [comment]
I got it from you -> https://github.com/VivaPayments/API/tree/master/Plugins/opencart/OpenCart%202.0%20-%202.1%20-%202.2

**Comment by VivaWalletSupport** [comment]
That one is not for OpenCart 2.3, remove these files and use the one from https://github.com/VivaPayments/API/tree/master/Plugins/opencart/Opencart%202.3

**Comment by VivaWalletSupport** [comment]
In case using the correct package, please close this issue. Otherwise let me know how I can help.
