### ISSUE TITLE
Error Code 422 - PaymentsNoBinRouteFound 

### ISSUE THREAD

**Issue by ottotilla** [VivaPayments/API#776]
Hi, In our 'Simple' integration on live we are getting this error. We placed a test transaction previously which worked fine when we went live, but we have had two customers from the US try to pay and in both cases we have received this error returned with no TransactionId. Is this something to do with payments from US customers? We know it works fine for UK customers. Many thanks.

**Comment by ottotilla** [comment]
Hi, In our 'Simple' integration on live we are getting this error. We placed a test transaction previously which worked fine when we went live, but we have had two customers from the US try to pay and in both cases we have received this error returned with no TransactionId. Is this something to do with payments from US customers? We know it works fine for UK customers. Many thanks.

**Comment by bigtili** [comment]
Hi, I have a similar issue with WooCommerce (not accepting EUR payments on a GBP Viva account). Did you get any reply from @viva-payments ?

**Comment by matthewrgourd** [comment]
Hi there, apologies that no-one came back to you on this one. Can you let me know if this is still an issue? Thanks!
