### ISSUE TITLE
Native Checkout PHP custom - Moved permanently

### ISSUE THREAD

**Issue by Lucania001** [VivaPayments/API#778]
Hi,

I configured my PHP native checkout. It works with demo account details and demo API url fine

https://demo.vivapayments.com

When I go to the live URL with live credentials

https://vivapayments.com

I am getting a success message without a transaction ID and no card charge/no transaction. When I log out the response header and response I get the following

```
[13-Mar-2019 16:43:19 Europe/Berlin] <head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://www.vivawallet.com/en-eu/api/transactions">here</a></body>
[13-Mar-2019 16:43:19 Europe/Berlin] HTTP/1.1 301 Moved Permanently
```

So have you changed your production API url?

**Comment by donfn** [comment]
You forgot 'www'. The correct production base URL should be www.vivapayments.com.

**Comment by Lucania001** [comment]
Beautiful, thats fixed it!
