### ISSUE TITLE
Multicurrency Issue

### ISSUE THREAD

**Issue by bigtili** [VivaPayments/API#779]
I have an issue with accepting EUR payments on my WooCommerce site (I have a GMP Viva acc). 

After completing the order one gets redirected to a page which says: To complete the payment click the button below. There is no button. And why is there a redirect to this page as it should be redirected to Viva Credit Card form?

I have been trying to fix these issues with your Email Support for days. 

Please help. @kostGX @VivaWalletSupport

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by bigtili** [comment]
@VivaWalletSupport 
Here you go. Thank you.

![screen2](https://user-images.githubusercontent.com/8112863/54364150-944d0a80-466c-11e9-94aa-d10fcd6ceee6.JPG)
![screen3](https://user-images.githubusercontent.com/8112863/54364151-944d0a80-466c-11e9-83b9-381a9eb045e7.JPG)
![screen4](https://user-images.githubusercontent.com/8112863/54364152-94e5a100-466c-11e9-9214-920caa315d11.JPG)
![screen1](https://user-images.githubusercontent.com/8112863/54364154-94e5a100-466c-11e9-9bd3-fb883bea7080.JPG)

**Comment by VivaWalletSupport** [comment]
Could you clarify GMP Viva acc?

**Comment by bigtili** [comment]
Sorry, I meant GBP Viva account. We have a GBP account, but would like to accept EUR payments too.

**Comment by VivaWalletSupport** [comment]
As far as I know you can only accept payments in the currency from your Viva account (GBP) in your case.

**Comment by bigtili** [comment]
Hi,

I got this from Viva email support:

We would like to inform you that your Viva Payments’ account supports the
currency of the country of incorporation.

As a result, your Viva Payments’ account may accept payments of different
currencies, but your account is credited to GBP.
Also, when we signed up, they told us we can accept payments in GBP, EUR
and USD.

**Comment by VivaWalletSupport** [comment]
Do you have currently any problem when making a transaction in GBP currency?

**Comment by bigtili** [comment]
No.

**Comment by bigtili** [comment]
Hi, any news regarding multi-currency payments via Viva gateway?

**Comment by VivaWalletSupport** [comment]
Hello, concerning the plugin and the settings I do not see a technical issue as you also mention that payments in GBP currency do not give a problem. Regarding the problem of accepting foreign currencies with your GBP account I cannot help you, it is an administrative issue. I would recommend to contact your Viva account manager on this and on what has been assured to you regarding the foreign currency acceptance.

**Comment by nagleator** [comment]
Hi mate,

Did you get this resolved? Have the same issue.

**Comment by matthewrgourd** [comment]
Hello, for the transaction at Viva only the currency is supported from the country your company is registered in. In case this would be the UK, only the GBP currency would be allowed. For WooCommerce there are various plugins available that are able to covert other currencies to GBP in the checkout stage. You can do a search for these at https://woocommerce.com/product-category/woocommerce-extensions. Thanks!
