### ISSUE TITLE
Integration με Opencart

### ISSUE THREAD

**Issue by Conalgr** [VivaPayments/API#78]
Καλημέρα,

Θα ήθελα να ρωτήσω αν έχετε κάποιο extension έτοιμο ή αν υπάρχει κάποιος κώδικας για να βάλουμε το Viva wallet στο opencart.

Ευχαριστώ εκ των προτέρων για την άμεση απάντησή σας.

Με εκτίμηση,

Νικόλαος Τούμπας

**Comment by defilerc** [comment]
Καλησπέρα @Conalgr ,

Στο παρακάτω URL, μπορείτε να βρείτε παραδείγματα κώδικα, ανάλογα με τη γλώσσα που θέλετε να χρησιμοποιήσετε: https://github.com/VivaPayments/API

Δεν υπάρχει κάποιο επίσημο plugin για το opencart, για το οποίο να παρέχεται υποστήριξη από τη Viva Payments.

Αν παρολαυτά, επιθυμείτε να χρησιμοποιήσετε κάποιο εξωτερικό plugin (extension), θα πρέπει να επικοινωνήσετε με τους δημιουργούς του, για να δείτε τι δυνατότητες παρέχει και κατά πόσο καλύπτει τις ανάγκες σας.

Ευχαριστούμε πολύ για την επικοινωνία
