### ISSUE TITLE
Refund is disabled

### ISSUE THREAD

**Issue by mauxtin** [VivaPayments/API#780]
Hello,

Similarly with #761 I am getting the error 
```
Refund is disabled for the merchant de735313-c85e-447d-ac0e-713cfde08341
```

Is this something I can change on my dashboard? Or is it on your side?

**Comment by kostGX** [comment]
@mauxtin you should be ok now. It's a config on our side.

**Comment by mauxtin** [comment]
Thanks. Can we also enable it for `3c5ea6c7-7675-46eb-9d08-66ebedf1289a`?

**Comment by kostGX** [comment]
@mauxtin I guess this is a production merchant_id as I couldn't find it on Demo database.

Production works fine, what we do on Demo is to emulate that you passed Verification (which enables Payouts and therefore refunds).
