### ISSUE TITLE
VIVA ΚΑΙ ΠΗΓΑΣΟΣ ERP -ERP PEGASUS

### ISSUE THREAD

**Issue by mpikat** [VivaPayments/API#783]
Αν και η πληρωμή γίνετε κανονικά στο viva δεν επιστρέφει σε εμας στον ΠΉΓΑΣΟ ότι ολοκληρώθηκε η πληρωμή Τι μπορέι να είναι? 
FormRedirect
https://www.vivapayments.com/web/newtransaction.aspx?ref=
Request
https://www.vivapayments.com/api/orders
RequestTransactionData
https://www.vivapayments.com/api/transactions

**Comment by VivaWalletSupport** [comment]
Hello, are you using a specific plugin to connect?

**Comment by matthewrgourd** [comment]
Sorry for the delayed reply. Can you send through some screenshots if the issue is still occurring? You'll need to blur out any private information...Thanks
