### ISSUE TITLE
Demo env not working: PaymentsNoBinRouteFound

### ISSUE THREAD

**Issue by aleksanderd** [VivaPayments/API#784]
Hi!

#480 related

demo env still not working, same error: PaymentsNoBinRouteFound

is it still not fixed yet or I doing something not correctly?

thank you!

**Comment by Usmanakram123** [comment]
@aleksanderd can you tell me further details of your project. so i can help you

**Comment by donfn** [comment]
I don't encounter any issues at the demo environment. What implementation are you using?
Native, Redirect or Simple Checkout? 

Can you share your code with your credentials masked?

**Comment by aleksanderd** [comment]
We using Native Checkout.  
Frontend part seems to be work ok - the token is given ok.  
Backend part creating order is ok too, but the `transaction` method is failed with code 422 and message 'PaymentsNoBinRouteFound'.   

request:   
![image](https://user-images.githubusercontent.com/5766592/54596685-35114080-4a46-11e9-8251-03edd99e69a9.png)

response:   
![image](https://user-images.githubusercontent.com/5766592/54596720-4c502e00-4a46-11e9-8695-b5807f3976b0.png)

Also be noted, it(the same code) is work ok already for Live env, so the code is 100% ok 
and it is not too easy to share it since its complexity, etc...

**Comment by donfn** [comment]
Make sure you're using httpS://demo.vivapayments.com. In the documentation
it is used without https and that may result in errors (probably routing etc).

**Comment by aleksanderd** [comment]
sure:  

![image](https://user-images.githubusercontent.com/5766592/54598157-0183e580-4a49-11e9-9bf7-9101d16965b1.png)

**Comment by aleksanderd** [comment]
Also, could I use `https://demo.vivapayments.com/web/checkout/js` at the frontend form or need to use `https://www.vivapayments.com/web/checkout/js` ? I tried both and both gives the token ok... same error at the finish `transaction` method call.

**Comment by donfn** [comment]
You are using the credentials provided in the demo console? 
http://demo.vivapayments.com/en-gb/signin

**Comment by donfn** [comment]
The token is generated via Public Key cryptography-it doesn't matter if you load the demo or www version.

**Comment by aleksanderd** [comment]
> Are you using the credentials provided in the demo console?   

yes, copied its from here:   

![image](https://user-images.githubusercontent.com/5766592/54663454-5def0f80-4af2-11e9-8a1f-2834a40b8681.png)

![image](https://user-images.githubusercontent.com/5766592/54663653-0dc47d00-4af3-11e9-8c4c-55e82a898beb.png)

**Comment by aleksanderd** [comment]
May be it is cos the account seems to be not verified? I confirmed email but it not hepled....    


![image](https://user-images.githubusercontent.com/5766592/54664089-42850400-4af4-11e9-85aa-bfe7c4be7bf5.png)


Is it possible to use demo env without any doc scans/etc ?

**Comment by aleksanderd** [comment]
May be it is cos "unreal" local domain which is not accessible outside?

**Comment by aleksanderd** [comment]
we registered a new demo account and it works with it!

seems to be old demo account issue...

thank you!
