### ISSUE TITLE
Payment successful, no callback to website though.

### ISSUE THREAD

**Issue by dijitul** [VivaPayments/API#785]
Hiya,

Searched through existing issues but couldn't find anything that helped.

We have got Opencart 2.3.0.2 working with viva payments, but the website is putting all orders into missing as Viva isnt telling my website the order was paid for.

Viva order is successful
Viva send email saying thanks it has been successful
Website sends email saying Thanks for signing up
Website does not mark the order as PAID so it sits in "Missing Orders"

What is missing from the OC setup steps? There has to be something missing.

Any help would be appreciated.

**Comment by dijitul** [comment]
My VIVA settings are as per they suggest in the setup guide
My OC settings are as per they suggest in the setup guide

Argh this is annoying.

**Comment by VivaWalletSupport** [comment]
Hello, are you using a specific plugin to connect?

**Comment by dijitul** [comment]
Yes, the plugin from here

https://github.com/VivaPayments/API/tree/master/Plugins/opencart/Opencart%202.3

**Comment by dijitul** [comment]
I spotted the SUCCESS and FAILURE urls change from one version to the next

I am using 2.3.0.2

Should they be

Success path: index.php?route=payment/vivawallet/callback&success
Fail path: index.php?route=payment/vivawallet/callback&fail

OR

Success path: index.php?route=extension/payment/vivawallet/callback&success
Fail path: index.php?route=extension/payment/vivawallet/callback&fail

**Comment by VivaWalletSupport** [comment]
Like the readme.txt instructs:
Success path: index.php?route=extension/payment/vivawallet/callback&success
Fail path: index.php?route=extension/payment/vivawallet/callback&fail

**Comment by dijitul** [comment]
Fixed it.

Was file permission/ownership related. It wasnt saving the source code, which meant (I guess) it wasnt *correctly* pointing to viva. FIxed that, reentered the source code, BINGO it worked.

PRO TIP: Put a company logo in the settings page in viva, and when testing if you dont see your logo, your website isn't pointing to the correct Source :)

**Comment by elijahnyaroya** [comment]
Hello,

How do we specify redirect link to my e-commerce website success or fail page when the payment is successful or failed.

Kindly help.
Tanks in advance
