### ISSUE TITLE
Inconsistent Payments Error 

### ISSUE THREAD

**Issue by lgillatt** [VivaPayments/API#786]
Hello, we are having inconsistent success with payments on our wordpress / woocommerce website.

Some orders are processing perfectly fine, yet other are resulting in customers reporting that the payment aspect isn't working leaving us with a pending order (not cancelled) and no payment received to complete the order.

Our site is https://www.cbd-guru.co.uk/

**Comment by matthewrgourd** [comment]
Hi there, sorry for the lack of response previously. Are you using our official extension available only from here? https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ If not please uninstall the existing plugin and follow the installation instructions on the above page. Thanks!
