### ISSUE TITLE
How to use Native Checkout on wordpress without redirecting the viva page

### ISSUE THREAD

**Issue by Usmanakram123** [VivaPayments/API#787]
i have developed a plugin for native checkout using the PHP native checkout library. and its working fine.

**Comment by kostGX** [comment]
Hey @Usmanakram123,

You need to edit your Source settings.

Go to Sales > Online Payments > Website/Apps and edit your source settings to Native Checkout.

**Comment by Lucania001** [comment]
@Usmanakram123 would be interested if you want to collaborate on native native checkout? how did you get around the ajax/getting token issue? Happy to share my repo
