### ISSUE TITLE
Error code 502 - Transaction Failed

### ISSUE THREAD

**Issue by ottotilla** [VivaPayments/API#788]
Our integration is working under normal circumstances but we have on one of our transactions received an error code of 502 with the not very helpful error text 'Tranasaction Failed'. 

i see that this issue has been raised by a number of people, but i guess that if you don't actually respond with anything helpful, then people are going to keep raising it. 

Can you provide any more useful information than 'Transaction Failed'? Is it a technical or a merchant related failure?

**Comment by VivaWalletSupport** [comment]
Hello is the failed transaction logged in your Viva backoffice under Sales Transactions - advanced search, with the Remark "Failed"? Anything else known about the attempted failed transaction (like other currency)?

**Comment by ottotilla** [comment]
Thanks for responding to my issue. Yes, the failed transaction is logged in our Viva back office - i can see it after having followed your instructions. The transaction was in the same currency that we have previously processed all our transactions under. i have no additional info with respect to the transaction other than that it was processed in exactly the same way as other transactions. We have had successful transactions both prior to and following this one, which is why we were trying to determine the cause of the failure - 'Transaction Failed' doesn't tell us much about what the cause of the issue might be.

Appreciate your help.

Regards

**Comment by VivaWalletSupport** [comment]
In case a transaction fails (for whatever reason) the StatusId E is returned (The transaction was not completed because of an error). Exact details why the card was not accepted are not available to the customer / merchant through the API system. You might contact your Viva account manager to find out more.

**Comment by ottotilla** [comment]
Thank you for your help - i will get the someone to contact the Viva account manager. Appreciate your kind assistance.

Regards.
