### ISSUE TITLE
Redirection from Viva Wallet not working

### ISSUE THREAD

**Issue by Ballymultani** [VivaPayments/API#789]
Hi
 I have created a test site (domain with testing appended to it in the URL) and from this testing site, 
I am currently using a demo account from https://demo.vivapayments.com. So everything seems to work apart from the redirection URL which I have set up as 

- testing/index.php?wc-api=wc_vivawallet&vivawallet=success
- testing/index.php?wc-api=wc_vivawallet&vivawallet=failure

When the transaction completes using the test card details, firstly, it always fails. Secondly, it attempts a redirection but a response of -1 is returned.

Can someone please explain why the -1 is the response and why it's doing this?

Regards

Bally

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by Ballymultani** [comment]
Its ok I was using the wrong plug in. Thank you for your response, I have got it resolved.
