### ISSUE TITLE
MAGENTO 2

### ISSUE THREAD

**Issue by eliassdogos** [VivaPayments/API#79]
Καλησπέρα,

Υπάρχει νεο extension για magento 2? 

Αυτο,

https://www.magentocommerce.com/magento-connect/catalogsearch/result/?q=Viva+Payments&pl=0

αφορά την έκδοση 1,9

**Comment by defilerc** [comment]
Καλησπέρα @eliassdogos ,

Η ανάπτυξη εξωτερικών plugins γίνεται από ανεξάρτητους developers και γι' αυτό το λόγο δεν παρέχεται επίσημη υποστήριξη από τη Viva Payments.

Θα πρέπει να επικοινωνήσετε με τους δημιουργούς του plugin, για να πάρετε επιπλέον πληροφορίες.

Ευχαριστούμε πολύ
