### ISSUE TITLE
Custom form in wordpress or in html/php with amount from user

### ISSUE THREAD

**Issue by mzoannou** [VivaPayments/API#790]
Hello

I have a wordpress website that i need to build a form that the user will provide name, surname and an amount of money and pay through viva wallet with his card.

can you please provide me with the appropriate code and guides?

Thanks in advance

**Comment by kostGX** [comment]
Hello @mzoannou,

Please follow the link below and follow the appropriate guide -- thanks!

https://developer.vivapayments.com/e-commerce-plugins
