### ISSUE TITLE
The specified api action is disabled for the merchant

### ISSUE THREAD

**Issue by mauxtin** [VivaPayments/API#793]
```
Client error: 
`POST https://demo.vivapayments.com/api/wallets/307361069956/balancetransfer/290067240141` 
resulted in a `403 The specified api action is disabled for the merchant 
de735313-c85e-447d-ac0e-713cfde08341, please consult the documentation` response
```

Can you please allow my demo account to use that endpoint? 

(I suppose it is a similar case to https://github.com/VivaPayments/API/issues/780, please let me know if it's something else instead)

**Comment by mauxtin** [comment]
@VivaWalletSupport Any update on this?

**Comment by mauxtin** [comment]
Any updates on this?? @VivaWalletSupport

**Comment by kostGX** [comment]
@mauxtin I have enabled the API call for your Demo account.

Regarding production account, you will have to ask your account manager to follow through with this request.

**Comment by mauxtin** [comment]
Thanks @kostGX!

**Comment by mauxtin** [comment]
Hi @kostGX, I am still getting the same error message.

**Comment by mauxtin** [comment]
@kostGX @VivaWalletSupport

**Comment by mauxtin** [comment]
@kostGX @VivaWalletSupport

**Comment by kostGX** [comment]
@mauxtin please try again

**Comment by Mukhammad911** [comment]
Hello dear support. I am also getting this error for production

**Comment by veteranslayer** [comment]
Hello, i am getting the same error for the demo account "The specified api action is disabled for the merchant 77e73c25-4ebc-46f2-bd5f-d36ba63c26b7, please consult the documentation". 

Is there something i can do to open this function? @VivaWalletSupport

**Comment by lieremiadis** [comment]
Hello, I an getting the same error for production account: 

**Error Code 403
The specified api action is disabled for the merchant ed105491-5fda-4ca2-9938-debe1fb3c615, please consult the documentation**

Can you please help us?

**Comment by mrusciel** [comment]
You most open a new insue, and they(support) anwser very fast... 
This is how I resolved....
