### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by WebWars** [VivaPayments/API#794]
Good evening.

This is the log I am getting when I try to use the API. The demo enviroment works great but on production I get this.

HTTP/1.1 401 Unauthorized
Date: Mon, 25 Mar 2019 21:35:26 GMT
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=15768000
Content-Type: application/json; charset=utf-8
X-Viva-CorrelationId: 19-084-3F664E16
Content-Length: 61

{"Message":"Authorization has been denied for this request."}HTTP/1.1 401 Unauthorized
Date: Mon, 25 Mar 2019 21:35:26 GMT
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=15768000
Content-Type: application/json; charset=utf-8
X-Viva-CorrelationId: 19-084-3B70A6D1
Content-Length: 61

{"Message":"Authorization has been denied for this request."}stdClass Object
(
    [Message] => Authorization has been denied for this request.
)

I tried the solution on #144 it seemed to be working for a moment and couple of months later (today) I seem to get this error. Reverting to curl_setopt($session, CURLOPT_SSL_CIPHER_LIST, 'TLSv1'); didn't do anything unfortunately.

Regards,
Babis

**Comment by matthewrgourd** [comment]
Sorry for the delayed reply. Which API are you attempting to use? Have you tried with your production rather than demo credentials for authentication? Thanks!
