### ISSUE TITLE
redirection problem zpecommerce

### ISSUE THREAD

**Issue by Bapander** [VivaPayments/API#795]
Hi
We use zpecommerce platform and they have integrated viva wallet as redirect method, the payments are successful, however after the transaction is completed its not redirecting to our website, they have created failed and successful pages and have entered this in viva wallet dashboard under the website/apps section which has been approved by viva wallet.

Can someone please help.

**Comment by matthewrgourd** [comment]
Hi there, I'm afraid we can't help with third-party integrations. We support only our own extensions here:  https://developer.vivawallet.com/e-commerce-plugins/
Thanks.
