### ISSUE TITLE
Woocommerce - Belgium - Payment page in GR

### ISSUE THREAD

**Issue by hubuducu** [VivaPayments/API#798]
Hello!
Ecommerce merchant says that by default the payment page is in GR
where do they need to make the switch?

Alexandre, from Sales Support BE
( averreydt@vivawallet.com)

**Comment by VivaWalletSupport** [comment]
Hello, please try the supported plugin from https://developer.vivapayments.com/e-commerce-plugins/

**Comment by VivaWalletSupport** [comment]
In case that solved the problem, please close this issue.
