### ISSUE TITLE
Check out page 

### ISSUE THREAD

**Issue by jaysjfc** [VivaPayments/API#799]
Is there any way I can remove the section "phone with prefix" when customers are filling out the card details??

**Comment by kostGX** [comment]
Hello @jaysjfc, currently it's not supported but it's definitely within our plans to support parameters for disabling the input of phone and email. However, I can't provide a timeline at this point.

Please monitor this page https://developer.vivapayments.com/api-reference-guide/payments-api/create-order/optional-parameters/ for when the new parameters are added.

In the meantime, you could integrate using [Native Checkout](https://developer.vivapayments.com/checkouts/native-checkout/) which allows you to avoid capturing the personal details of your customers, but requires more integration effort.

Let me know if I can help any further,
Thanks!

**Comment by jaysjfc** [comment]
Is there anyone who could install native checkout for me as I am having a lot of people getting to the checkout and not making any payments.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
