### ISSUE TITLE
Viva Gateway Plugin Error with Redirection

### ISSUE THREAD

**Issue by xenofon360** [VivaPayments/API#800]
Hi,

I am running this plugin: https://wordpress.org/plugins/woo-payment-gateway-viva-wallet/ installed at WordPress 4.9.8 with WooCommerce 2.5.0 and PHP 7.0.33. The reason that i run this Plugin is that i of course installed the other 2 that are eligible and newest but both of them give an error in Plesk logs cause of my WooCommerce version. I tried on another testing server these 2 new plugins after i updated WordPRess and WooCommerce to the last versions but i had problem with my website (Viva Worked though). So we are going to work on this plugin, that's for sure. No updates, no other plugins. I need to adjust my system on this plugin.

This Plugin works perfectly with my system. No Plesk error logs, Viva appears in Checkout page as payment method and i am redirected normally to Viva Page. I Set card credentials and payment is done. My card is charged for the purchase and Viva Wallet appears the new transaction normally. Emails are sent and everything is perfect except one thing that i believe that you will know how to fix.

After successful payment, redirection sent me at a White Blank Page instead of Thank you Page with order details. That's all. Everything else works fine as i mentioned above.

I sent you some necessary screenshots at this point:

Plugin:
https://pasteboard.co/I7uQlIF.jpg

Viva Wallet:
https://pasteboard.co/I7uQPop.jpg

If you need, i have cloned my website on a Testing Server where it can be called with another URL than domain name. Inform me if you need access. Then we are going to fix the problem there and when ready i will transfer the changes to the main website.

Thank you in advance. Hope to find the solution.

**Comment by VivaWalletSupport** [comment]
Hello, please try the supported plugin from https://developer.vivapayments.com/e-commerce-plugins/

**Comment by xenofon360** [comment]
Hi,

Thank you for the fast response.

I installed your plugin. I have exactly the same error. More detailed ...

I redirected at Viva environment, i filled my card's credentials, press charge button and...
1) I redirected at this blank page: https://pasteboard.co/I7vdUSy.jpg
2) Order appeared at Back End as pending payment status.
3) Viva Wallet environment appeared the transaction.
4) At plugin's settings (back end) i left instalments blank and order status drop down as "completed", as it was by default.

No errors appear in Plesk logs, so redirection is the problem i think. This plugin is also compatible with my system. Maybe we need to make some changes in php files.

Best Regards,

**Comment by VivaWalletSupport** [comment]
Did you follow the installation and setup instructions (in particular the setup of the payment source)?

**Comment by xenofon360** [comment]
Hi,

Of course. Everything is like before in Viva environment like i mentioned above with the previous plugin: https://pasteboard.co/I7uQPop.jpg

I filled plugin fields with all the credentials and the result is that blank page but with completed order.

Best Regards,

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by xenofon360** [comment]
Hi,

As you asked.

1) https://pasteboard.co/I7vVTwJ.jpg
2) https://pasteboard.co/I7vWbTQ.jpg
3) https://pasteboard.co/I7vWjHD.jpg
4) https://pasteboard.co/I7vWv2a.jpg

Best Regards,

**Comment by VivaWalletSupport** [comment]
Please setup the plugin first in the demo environment to verify the working (uncheck native payments in your demo API access page). In case the problem persists post again the screenshots and then please only mask the API Key.

**Comment by xenofon360** [comment]
Hi,

I did it with Demo Account. With Demo everything is worst. Transaction does not appear as order in Back End of WooCommerce and in Demo Viva Wallet environment.

Also after your Viva card credentials page i redirected again at blank page with -1 appear on top left of the screen.

As you asked:

1. https://pasteboard.co/I7wWOkh.jpg
2. https://pasteboard.co/I7wX1pk.jpg
3. https://pasteboard.co/I7wX7WX.jpg
4. https://pasteboard.co/I7wXdTN.jpg

**Comment by xenofon360** [comment]
Hi,

Excuse me. My fault. We have something here. I didn't fill my testing server URL before, i had my main. So now i redirected back to checkout page after VIva's environment but i had an error. These are my fixes related to my previous message:

1. https://pasteboard.co/I7xbNpf.jpg
2. https://pasteboard.co/I7xbTGXr.jpg

We are close enough.

Thank you.

**Comment by VivaWalletSupport** [comment]
Minimum order amount is 30 cents.
http://prntscr.com/n4971b
http://prntscr.com/n4995c

**Comment by VivaWalletSupport** [comment]
In case the problem has been solved, please close this issue, otherwise let me know how I can help.

**Comment by xenofon360** [comment]
Hi,
 
Thank you.

Let me perform some tests and we will close it soon.

I will inform you with next message.

Best Regards,

**Comment by xenofon360** [comment]
Hi,

Let me make some questions here.

1) Why Viva's environment is set to English language while i use your official plugin and doesn't let me change the language with country flags? My previous plugin (it was not functional) let me change the language. With this plugin everything is in English only.

Example Testing Environment: https://pasteboard.co/I7EvD9J.jpg

2) Also with this plugin customer receives Viva's email (successful buy) in Junk folder, not in Inbox (with previous plugin email went to Inbox, not Junk). This must be fixed for sure.

3) Viva's email is in english language. I need it in Greek too.

4) You do not provide a field in you plugin to fill with Description. Description that appears in Viva's Wallet environment, in emails etc. I need this field. It was working before, with your plugin it's not.

Bes Regards,

**Comment by VivaWalletSupport** [comment]
1. Setup your store correctly, when using Greek your store locale should be el-GR (yours uses en-US). When corrected the customer should see a Greek payment page and receive Greek emails when visiting the site in Greek language.
2. Not a matter related to the plugin.
3. See point 1.
4. Any plugin might have its own functionality, feel free to add your desired logic.

**Comment by xenofon360** [comment]
HI,

I completely understand. Although, we must do something for that cause i use en-US over a year now and i have done direct translations using Loco translate plugin for english strings. You understand that i can not change my whole site language now for a single plugin. So please give me a solution here.

I didn't understand 4. Are we able to add description somehow?

Best Regards,

**Comment by VivaWalletSupport** [comment]
For the language and description have a look at:
https://developer.vivapayments.com/api-reference-guide/payments-api/create-order/optional-parameters/ (RequestLang / CustomerTrns parameters) and modify the plugin to your needs.

**Comment by xenofon360** [comment]
Hi,

I need to close this ticket. In my case with English, please let's finish it. I am troubled about something, how can i handle strings of this page:
https://pasteboard.co/I7FJqBv.jpg

This environment doesn't belong to me. The Payment description is ok and translated by me cause these files belong to plugin and i can edit. What i sent you belongs to Viva, and i need it of course or with choice of changing languages or with Greek only. English only is not an option for me absolutely.

How can we solve this? I am not making any proportions, i let this to you. Guide me or help me.

Thank you.

Best Regards,

**Comment by VivaWalletSupport** [comment]
I would suggest to open a new ticket for the language issue you have with your store, so someone who experienced the same problem might pick it up.

**Comment by xenofon360** [comment]
Hi,

Sure.

Thank you a lot.
