### ISSUE TITLE
Translate Viva Payment Environment

### ISSUE THREAD

**Issue by xenofon360** [VivaPayments/API#801]
Hi,

My Wordpress / WooCommerce store uses as core language English and all translations are made by me manually on english strings. I can not change my core language after this whole time of course so i need to adjust Viva environment page on my needs.

My problem is with this page:
https://pasteboard.co/I7FJqBv.jpg

I need to translate everything in here in Greek language, English is not an option for me.

I have used plugins related to Viva payments that appear country flags in the environment where customer makes the choice of language. These plugins were not operational and now i use the official plugin that is supported by the community here.

I do not believe that my problem hasn't a solution.

Please, i am all ears, how can we fix that?

Best Regards,

**Comment by VivaWalletSupport** [comment]
In wc-vivawallet.php change the string:
$poststring['RequestLang'] = $formlang;

To:
$poststring['RequestLang'] = '';

**Comment by xenofon360** [comment]
Hi,

Thank you very much. It worked!

Now Viva's environment by default is in greek but it has also the choice to change it to english with flag buttons. That's exactly what i wanted.

I need something last that is related with the best assistance of Viva Wallet environment for customers. A plugin that i used before had this function but this one which is the official is not, so this is related to plugin.

Check here please: https://pasteboard.co/I80draK.jpg

I need to add a standard description. This description appears at viva email that customer receives too, i have seen this, but for this plugin is blank and has no power to send this description among with email, back end of wordpress doesn't offer a necessary field to be filled by me.

So, what's the deal here? Set this description in another php file? Please enlight me.

Best Regards,

**Comment by kostGX** [comment]
@xenofon360 search your code for where "CustomerTrns" is set. That's what affects it. 
MerchantTrns are for internal use only (your customer cannot see it).

**Comment by xenofon360** [comment]
Hi,

Please be more specific.

1) Search my code in which php file of the plugin, maybe the main one?

2) Do what with "CustomerTrns"? Delete it or edit it? Replace it with something else?

Also i believe that you are referring to the description as i mentioned above that "it worked" if you are referred to the translation. But thank you very much.

Best Regards,

**Comment by VivaWalletSupport** [comment]
You would have to edit the wc-vavawallet.php file and alter following string:
$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300';

To something like:
$mytext = 'The text to include';
$postargs = 'Amount='.urlencode($poststring['Amount']).'&RequestLang='.urlencode($poststring['RequestLang']).'&Email='.urlencode($poststring['Email']).'&MaxInstallments='.urlencode($poststring['MaxInstallments']).'&MerchantTrns='.urlencode($poststring['MerchantTrns']).'&SourceCode='.urlencode($poststring['SourceCode']).'&CurrencyCode='.urlencode($poststring['CurrencyCode']).'&PaymentTimeOut=300&CustomerTrns='.$mytext;

**Comment by VivaWalletSupport** [comment]
In case this solved your problem, please close this issue. Otherwise let me know how I can help.

**Comment by xenofon360** [comment]
Hi,

I did what you mentioned above. I got error 500 for my whole website when refreshed.

Check here: https://pasteboard.co/I9amWVs.jpg

To be more specific ....

1) I found the line that holds the code that you told above.
2) In the above line i set: $mytext = 'Παραγγελία από AP Marine Store | apmarinestore.gr';
3) In the code line i went at the point ...'&PaymentTimeOut=300'; and set ... '&PaymentTimeOut=300'&CustomerTrns='.$mytext;

This procedure gave me error 500.

Something is missing ... 

Best REgards,

**Comment by VivaWalletSupport** [comment]
Remove the quote after 300

**Comment by xenofon360** [comment]
Hi,

Thank you very much. Everything works perfect now.

I am closing this ticket.

Keep on the great work!

Best Regards,
