### ISSUE TITLE
WooCommerce Vivawallet Gateway - pending payment

### ISSUE THREAD

**Issue by KatePitsi** [VivaPayments/API#802]
Hello,
my site is WordPress and there is a problem with the Viva wallet plugin.
While it normally charges the transaction card, it returns the order to the store as a pending payment and does not notify the administrator and the customer by email.
Only viva sends mail that the card was charged to the customer.
While PayPal pays orders via card it comes as processing normally.

**Comment by VivaWalletSupport** [comment]
Please try the supported plugin from https://developer.vivapayments.com/e-commerce-plugins/woocommerce/

See the provided instruction on how to setup and how to configure.

**Comment by VivaWalletSupport** [comment]
Please close this issue in case the problem has been solved, otherwise inform me how I can help.
