### ISSUE TITLE
WooCommerce Vivawallet Gateway - pending payment error

### ISSUE THREAD

**Issue by KatePitsi** [VivaPayments/API#803]
γεια,
το site μου είναι WordPress και υπάρχει πρόβλημα με το plugin της Viva wallet. 
Ενώ χρεώνει κανονικά την κάρτα συναλλαγής επιστρέφει την παραγγελία στο κατάστημα σαν pending payment και δεν ενημερώνει με email το διαχειριστή και τον πελάτη. 
Μόνο η viva στέλνει mail ότι χρεώθηκε η κάρτα στον πελάτη. 
Ενώ το PayPal παίζει κανονικά οι παραγγελίες μέσω κάρτας έρχεται σαν processing κανονικά.

**Comment by VivaWalletSupport** [comment]
Hello, it seems you have opened 2 issues for the same problem, could you please close one of them?
