### ISSUE TITLE
WooCommerce Vivawallet Gateway - Webhooks error 

### ISSUE THREAD

**Issue by KatePitsi** [VivaPayments/API#805]
καλημέρα σας,
Tα βήματα ( https://developer.vivapayments.com/ ) τα έκανα όλα μια χαρά το μόνο που δεν μπορώ να δημιουργήσω είναι το webhook μέσα στο API Access του VivaWallet Account.

Tο url αυτό 
http(s)://(www.)your_domain.com/index.php?js-api=JS_Gateway_Vivawallet&webhook
το θεωρεί λανθασμένο (αλλάζοντας την θέση με το domain) όταν πατήσω το verify.

Μπορείτε να μου πείτε χρειάζεται να έχουμε webhook;; και αν ναι τι πρέπει να γράψω ακριβώς;;

Θα περιμένω απάντησή σας.
Ευχαριστώ πολύ.

**Comment by VivaWalletSupport** [comment]
It is an error in the documentation, it should be:
http(s)://(www.)your_domain.com/index.php?wc-api=wc_vivawallet&vivawallet=webhook

**Comment by KatePitsi** [comment]
με αυτό το url παίζει κανονικά, αλλάξτε το και στο instruction που έχετε..
ευχαριστώ πολύ!!

**Comment by kostGX** [comment]
@KatePitsi will be updated in the next update of the developer portal.

Thanks for noticing 👍
