### ISSUE TITLE
Payment success, Redirect blank page with "-1"

### ISSUE THREAD

**Issue by Shorefire** [VivaPayments/API#806]
Hello there,

Can I get some assistance please?

I have managed to receive one payment via the vivawallet_for_woocommmerce plugin, but the success and failure redirections display a blank page with "-1" after the payment screen.

These are the URLs I have used on the Viva website
**Success:** index.php?wc-api=wc_vivawallet&vivawallet=success
**Failure:** index.php?wc-api=wc_vivawallet&vivawallet=fail

I have not set up the "optional" webhook. But I think I should not need to?

Any guidance will be much appreciated, please.

Kind regards,

**Comment by VivaWalletSupport** [comment]
Hello, check if you specified the domain correctly in the payment source (using www or not, https protocol or http). I would suggest to setup first the basics correctly before advancing to the webhook.

**Comment by Shorefire** [comment]
Hi, thanks for your quick reply.

![url](https://user-images.githubusercontent.com/49193646/55413729-d679b580-5561-11e9-8691-9cea09219ac0.png)
![domainname](https://user-images.githubusercontent.com/49193646/55413730-d679b580-5561-11e9-93bc-2941f8524a63.png)

I've triple checked them twice, and they seem to be right.

Is there something else I can try?

**Comment by VivaWalletSupport** [comment]
You seem to use another plugin to connect (using he setup instructions from the Viva Wallet supported plugin, instead of following the instructions from the plugin you use), please use the plugin and instructions from https://developer.vivapayments.com/e-commerce-plugins/woocommerce/

In case that solved your problem, please close this issue.

**Comment by Shorefire** [comment]
No, please that is incorrect. The screenshots I posted in my previous reply were from the Vivawallet website control panel. This screenshot is the plugin that I am using, and the link you have posted is where I got it from.

![Screen Shot 2019-04-02 at 16 37 25](https://user-images.githubusercontent.com/49193646/55416062-0d51ca80-5566-11e9-925f-1d512918a815.png)

**Comment by Shorefire** [comment]
Oh wait, my apologies. The link has changed. There is a different plugin now. I will test and see if it is working, then I will close the ticket.

**Comment by Shorefire** [comment]
All is working correctly. Thank you very much for your help.
