### ISSUE TITLE
Native checkout integration with pre-auth

### ISSUE THREAD

**Issue by alekseykuleshov** [VivaPayments/API#807]
Hello,

I want to implement the checkout so firstly the amount is being pre-auth, and then after the sale was reviewed, the payment should be captured ("settled", any other term?).

I see how to pre-auth the amount on user card: https://developer.vivapayments.com/api-reference-guide/payments-api/create-order/optional-parameters/

But I see no way to capture the transaction after. Should I call https://developer.vivapayments.com/api-reference-guide/payments-api/update-order/ with `IsPreAuth` set to false? Any other way to do this? 

Thanks for your help.

**Comment by alekseykuleshov** [comment]
@VivaWalletSupport Could you please help me with the issue? How can I capture payment which was pre-auth-ed?

**Comment by alekseykuleshov** [comment]
Also, I'm sending the create order request with `$obj->IsPreAuth = true;`, but the transaction are charged, bot pre-auth. The similar issue described here: https://github.com/VivaPayments/API/issues/454 (I had to translate from Greek). What I do wrong?

**Comment by alekseykuleshov** [comment]
@VivaWalletSupport Is there any way to capture the pre-auth payment via native checkout api? There is nothing about it at documentation. 

We are almost ready to use VivaPayments in production, but can not till this one is resolved.

**Comment by kostGX** [comment]
Hey @alekseykuleshov,

Check this call out:

https://developer.vivapayments.com/api-reference-guide/payments-api/create-recurring-transaction/
developer.vivapayments.com


Make the following call using as initial transaction id the one you got from the preauth.
POST /api/transactions/{preauthId}

The amount of the capture needs to be less or equal to that of the initial preauth transaction.

Best of luck :)

**Comment by alekseykuleshov** [comment]
@kostGX It worked, thank you a lot! The only thing which is required extra is to enable recurring payments for merchant. Now, it's fully functional for me.

**Comment by kostGX** [comment]
@alekseykuleshov This can be enabled from your API Access settings on production.

If you're on demo and it's not working feel free to share your merchant id so I can take a look.

**Comment by alekseykuleshov** [comment]
@kostGX Yes, it's working great! Thank you very much for your help! Should I close the issue?
