### ISSUE TITLE
Native checkout integration error

### ISSUE THREAD

**Issue by alekseykuleshov** [VivaPayments/API#808]
Hello,

I'm developing the solution on my localhost using the demo environment. I get the error of `Source XXXX of merchant XXXXXX-XXX-XXX-XXXX-XXXXXX supports only native checkout` all the time. What I am doing wrong? 

Is that because of the local environment? Will the issue disappear when I deploy to server with external ip and https? What's the proper way to development process then? I don't want to break live site while debug.

Thanks for your help.

**Comment by spotcodes** [comment]
I am also facing the same issue which trying for Native Checkout on WooCommerce website. Please reply if anyone knows the solution. 
![Native checkout issue](https://user-images.githubusercontent.com/25795476/55578347-4f7c3700-5733-11e9-9448-811c28dc3a65.png)

**Comment by alekseykuleshov** [comment]
@spotcodes It was my error, I was sending empty card token because of my mistake. 

But, error message is absolutely misleading. I think it should be corrected. @VivaWalletSupport
