### ISSUE TITLE
Πρόβλημα με MakePayment (/api/transactions)

### ISSUE THREAD

**Issue by kostas-brainbox** [VivaPayments/API#81]
Καλημερα,
έχω πρόβλημα στο demo περιβάλλον με τα request στο MakePayment δηλαδή στο url /api/transactions, το οποίο επιστρέφει 502 error.
Αντιθετα στο CreateOrder (/api/orders) δουλεύει κανονικά και επιστρέφει και transaction id.

Το δοκίμασα και σε μία εφαρμογή που δούλευε κανονικά και πάλι επιστρέφει το ίδιο error.
Υπάρχει κάποιο πρόβλημα με το API;

**Comment by dmihos** [comment]
Αναφέρεστε μάλλον στο demo περιβάλλον, το οποίο είχε ένα configuration θέμα, το οποίο διορθώθηκε.
Μπορείτε να ξαναδοκιμάσετε
