### ISSUE TITLE
Native Checkout issue on WooCommerce website

### ISSUE THREAD

**Issue by spotcodes** [VivaPayments/API#810]
Since the last two weeks, I am trying to integrate Viva Wallet plugin in WooCommerce website however after doing all the attempts, I am still stuck on Native Checkout. Attached herewith screenshot. If anyone has resolved that issue in the past, please feel free write to me.

![Native checkout issue](https://user-images.githubusercontent.com/25795476/55612875-e7673880-57a6-11e9-9f7b-91b1d75f1743.png)

**Comment by matthewrgourd** [comment]
Hi there, sorry for the lack of response previously. Viva Wallet for WooCommerce is redirect-only you can't use it natively. Please see [these instructions](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) for further information. Thanks!
