### ISSUE TITLE
Store not found.

### ISSUE THREAD

**Issue by brij121** [VivaPayments/API#811]
I have added the vivawallet to my shopify account but when I try a test payment it says - Store not found.

I checked and followed the document. Please can you let me know how to fix this.

**Comment by kostGX** [comment]
You should uncheck the test mode since we don't support it.

Please proceed with testing on Production mode (you can cancel the transaction from your Viva Wallet dashboard after it's done.)

**Comment by ap1988** [comment]
Hi there KostGX, 
I am experiencing exactly the same issue. 
Where does one check / uncheck test and production mode - I believe our store is live right now.
Thanks

**Comment by matthewrgourd** [comment]
https://help.shopify.com/en/manual/payments/shopify-payments/testing-shopify-payments

**Comment by 07944444123** [comment]
hi Im having the same issue and I have uncheck the test mode please help me out as I have customers who can't order

**Comment by matthewrgourd** [comment]
Hi @07944444123 have you followed our [detailed setup instructions](https://developer.vivawallet.com/e-commerce-plugins/shopify/)?

If the answer is yes, please [raise a new issue](https://github.com/VivaPayments/API/issues) with as much information as possible and we'll look into it.

**Comment by 07944444123** [comment]
Hi 
I’ve already done this and I’m not sure what to do now
