### ISSUE TITLE
webhook prestashop

### ISSUE THREAD

**Issue by tsilis** [VivaPayments/API#812]
The url could not be verified. Please make sure you have entered a valid, publicly available, url that conforms to these guidelines

**Comment by VivaWalletSupport** [comment]
Hello, what URL was provided?

**Comment by tsilis** [comment]
https://samarasenergy.gr/modules/vivawallet/webhook.php

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 2 screenshots:

Plugin settings (mask the API Key).
API Access page (mask API Key, include the browsers URL in the screenshot).

Also please inform me if there is any problem when making an order using the Viva Payments method.

**Comment by tsilis** [comment]
![module](https://user-images.githubusercontent.com/10558801/55870057-705be680-5b90-11e9-9820-907179b3e193.png)
![backend](https://user-images.githubusercontent.com/10558801/55870058-705be680-5b90-11e9-9d96-b9c1de115876.png)
![backend1](https://user-images.githubusercontent.com/10558801/55870060-70f47d00-5b90-11e9-842a-c13c36999191.png)
![backend2](https://user-images.githubusercontent.com/10558801/55870061-70f47d00-5b90-11e9-9b58-028bb815812f.png)

**Comment by tsilis** [comment]
![module](https://user-images.githubusercontent.com/10558801/55870258-d8aac800-5b90-11e9-9e73-a9195c0cae13.png)
![backend](https://user-images.githubusercontent.com/10558801/55870341-098afd00-5b91-11e9-9c33-fb6fab645719.png)

**Comment by tsilis** [comment]
never had any transaction

**Comment by VivaWalletSupport** [comment]
Unfortunately I do not see the requested browser URL in your screenshot, also the module does not work with the Native method, it should not be checked. Further more I would suggest to verify the correct working of the payment module first by making a transaction before exploring additional features like the webhook.

**Comment by tsilis** [comment]
native removed
![module](https://user-images.githubusercontent.com/10558801/55877441-a86c2500-5ba2-11e9-8260-defa40a140ec.png)
![backend](https://user-images.githubusercontent.com/10558801/55877442-a86c2500-5ba2-11e9-9f51-af4c328025ae.png)
![backend1](https://user-images.githubusercontent.com/10558801/55877443-a904bb80-5ba2-11e9-9b37-19c89b0a3317.png)
![backend2](https://user-images.githubusercontent.com/10558801/55877444-a904bb80-5ba2-11e9-9986-e71470d1752e.png)

**Comment by tsilis** [comment]
Στοιχεία συναλλαγής
Η συναλλαγή σας απέτυχε.

**Comment by tsilis** [comment]
Κωδικός Πληρωμής: 1672313239172605

**Comment by VivaWalletSupport** [comment]
Correct the domain name in your payment source, remove the www. part.
For the webhook could you email admin url/user/pass + ftp credentials to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com for having a look at the problem?

**Comment by tsilis** [comment]
thanks, removed the www.
credentials send , please check

**Comment by VivaWalletSupport** [comment]
So far nothing has been received at vivawalletgithubsupport@hellasboost.gr

**Comment by tsilis** [comment]
send it from another mail, it's weird because comes an automatic mail from cc mail (ecommerce)

**Comment by tsilis** [comment]
please check

**Comment by VivaWalletSupport** [comment]
Thanks, it was a coding error. Please try again to add the webhook.

**Comment by tsilis** [comment]
no, i have the same issue
http://prntscr.com/na5l9g

**Comment by VivaWalletSupport** [comment]
Could you email me access to your Viva account?

**Comment by tsilis** [comment]
yes sure, tell me if you received

**Comment by VivaWalletSupport** [comment]
Got it, a leftover from debugging caused the problem, added the webhook.
In case the problem is solved please close this issue, otherwise let me know how I can help.

**Comment by tsilis** [comment]
super
Kind Regards
