### ISSUE TITLE
Vivapayments "No order placed after payment"

### ISSUE THREAD

**Issue by ebuygr** [VivaPayments/API#814]
Dear colleagues,

I have an issue on my website with the vivapayments module. Attached you will find the .jpg file which is completed with the proper parameteres. When the client chooses to pay with credit/debit card and it redirects to the native checkout of Vivawallet the charge is done but the order is not placed. As a result we see the payments but we can't see the order. Is there something that we do wrong?
Waiting for your kind response.

Thank you
![viva](https://user-images.githubusercontent.com/27009982/55982541-d08e7d80-5ca1-11e9-8f29-9230ee5fcb1e.JPG)

**Comment by VivaWalletSupport** [comment]
Hello, it would be more logic to post your questions to the developer of the payment extension that you are using. Another option would be to use the supported plugin and documentation from https://developer.vivawallet.com/e-commerce-plugins/opencart2.3/

Please close this issue in case this solved your problem.
