### ISSUE TITLE
Issues Viva Wallet / Shopify

### ISSUE THREAD

**Issue by ap1988** [VivaPayments/API#815]
Hi there, 
I am having issues with payments being processed using Viva wallet which I have successfully integrated with Shopify. 
After I / a customer has completed an order on my store and then directed to viva wallet - i / the customer is automatically directed to the following site https://demo.vivapayments.com/shopify which states "Error Store not found". 
Please can somebody advise how to solve this issue so the website can properly process payments. 
Thanks
Alex

**Comment by kostGX** [comment]
@ap1988 please make sure you have Test mode *disabled* at your Shopify Control Panel.

Thanks

**Comment by Constantinoscreations** [comment]
Hello
I have the same problem and also when a customer goes to checkout he only has the Paypal option but no option to pay with credit cards. Test Mode is disabled.

**Comment by matthewrgourd** [comment]
@Constantinoscreations Please follow the guide here to install Viva Wallet as an option for payment within Shopify: https://developer.vivawallet.com/e-commerce-plugins/shopify/

**Comment by aromaenergy** [comment]
Hello,

I have this exact issue 
I have linked viva wallet to shopify. Used merchant ID and store token (which I assume is API Key)
![Error page when trying to pay](https://user-images.githubusercontent.com/53214641/61697387-15a95d80-ad2f-11e9-9ef9-0fde4b5f996e.jpg)
Test mode is off, but when I go to do a purchase it comes up with the error.
What am I missing?

**Comment by matthewrgourd** [comment]
@aromaenergy  Please follow the guide here to install Viva Wallet as an option for payment within Shopify: https://developer.vivawallet.com/e-commerce-plugins/shopify/ Thanks!
