### ISSUE TITLE
Prestashop Order Validation

### ISSUE THREAD

**Issue by DiyanDesigns** [VivaPayments/API#817]
Hello, I am having some issues with the vivawallet module on Prestashop 1.7.5
I've successfully connected it and even tho the payment seems to succeed on the viva payments side, when it redirects me back to the store (modules/vivawallet/success.php & modules/vivawallet/fail.php) I am getting an error:

``Fatal error: Uncaught PrestaShopException: Ανεπανόρθωτο σφάλμα in /home/storename/public_html/classes/Tools.php:1109 Stack trace: #0 /home/storename/public_html/classes/PaymentModule.php(254): ToolsCore::displayError() #1 /home/storename/public_html/modules/vivawallet/fail.php(37): PaymentModuleCore->validateOrder(23136, '8', 0, 'Vivawallet', 'Transaction fai...', Array, NULL, false, NULL) #2 {main} thrown in /home/storename/public_html/classes/Tools.php on line 1109``

Prestashop 1.7.5
PHP 7.1

**Comment by VivaWalletSupport** [comment]
Hello, anything logged in your Prestashop error log and/or in your PHP error log?

**Comment by DiyanDesigns** [comment]
It looks like prestashop logged the following error:
``PaymentModule::validateOrder - Secure key does not match``

I just noticed that we had www the Domain name setting on vivawallet.com ([http://prntscr.com/ndq0vm](http://prntscr.com/ndq0vm))
But our site is redirecting to the non www version, could that be the issue?

**Comment by VivaWalletSupport** [comment]
See also issue https://github.com/VivaPayments/API/issues/818 that seemed to have the same problem.

**Comment by DiyanDesigns** [comment]
Removing www fixed the problem. Thank you for your help.
