### ISSUE TITLE
VivaWallet prestashop redirection problems

### ISSUE THREAD

**Issue by jobywood** [VivaPayments/API#818]
Hi there,

we are having some problems with the VivaWallet prestashop module and setup. 

We have been able to take payments successfully from customers and believe that we have followed the instructions as given in the readme file to the letter, however when the time comes for the redirection to happen it gives a 'fatal error' sign and also no order is created for us in prestashop either. 

Please see the attached pictures for further details:-

![vivawallet](https://user-images.githubusercontent.com/44703631/56346096-440c1f80-61b9-11e9-81eb-925c5e749c61.jpg)

![prestashopvivamodule](https://user-images.githubusercontent.com/44703631/56346103-48383d00-61b9-11e9-952e-ade28897c3ef.jpg)

![fatal error](https://user-images.githubusercontent.com/44703631/56346112-4b332d80-61b9-11e9-9be9-e3e21a3aff0a.JPG)

Thank you.

**Comment by VivaWalletSupport** [comment]
Hello, please remove the www. part from the source setup as your site does not seem to use it. What error is logged in your Prestashop and PHP log files?

**Comment by jobywood** [comment]
thanks for your speedy response. 

The prestashop error that is logged shows as:-

PaymentModule::validateOrder - Secure key does not match

I have removed the www. part as you have suggested, i am just waiting for the site to be validated again now ;)

Thanks

**Comment by jobywood** [comment]
Hi again,

our domain has been approved now and the changes that you recommended does appear to have fixed our issue ;) so thanks very much for your help!!
