### ISSUE TITLE
Transaction failed 502 error

### ISSUE THREAD

**Issue by nlabiris** [VivaPayments/API#819]
We received the following response when trying to make a recurring transaction using the demo environment.

{
    "Emv": null,
    "Amount": 1.53,
    "StatusId": "E",
    "CurrencyCode": "978",
    "TransactionId": "4289f2ed-03e2-404e-8a65-146289ec2daa",
    "ReferenceNumber": 80951,
    "AuthorizationId": null,
    "RetrievalReferenceNumber": null,
    "ErrorCode": 502,
    "ErrorText": "Transaction failed",
    "TimeStamp": "2019-04-18T14:03:30.620709+03:00",
    "CorrelationId": null,
    "EventId": 10199,
    "Success": false
}

Is there any issue with Viva's backend?

**Comment by matthewrgourd** [comment]
This could be because the demo environment was down. It should be ok now. Have you since been able to succeed in the above?

**Comment by nlabiris** [comment]
Yes. Everything works properly now.
