### ISSUE TITLE
Πώς ενσωματώνω τα κουμπιά πληρωμών?

### ISSUE THREAD

**Issue by thecrypt13** [VivaPayments/API#82]
Καλημέρα σας

Δημιουργώ 2 κουμπιά πληρωμών, κάνω copy/paste τον κώδικα όπως λένε οι οδηγίες, αλλά λαμβάνω "Αποτυχία Συναλλαγής"

Μπορείτε να με καθοδηγήσετε βήμα - βήμα στο πώς θα ολοκληρώσω τη διαδικασία?

Το API και το source πού τα βάζω ακριβώς? Κατά τη δημιουργία των κουμπιών πληρωμής δεν μου δίνει τέτοια δυνατότητα.

Δεν είμαι τεχνικός, οπότε θα σας παρακαλούσα όπως μου υποδείξετε τον τρόπο.

Ευχαριστώ

**Comment by thecrypt13** [comment]
Θα πρέπει να δημιουργήσω 2 ξεχωριστές σελίδες στο σάιτ μου για να τις δηλώσω ως επιτυχημένη ή εσφαλμένη συναλλαγή? Εάν ναι, τι θα πρέπει να περιέχουν αυτές οι σελίδες? Κάποιον κώδικα? Ποιο κώδικα?

**Comment by dmihos** [comment]
Καλησπέρα σας

Το μήνυμα Αποτυχία Συναλλαγής βγαίνει μετά τη συμπλήρωση των στοιχείων της κάρτας; Αν ναι, τότε πιθανά απλά αποτυγχάνει η συναλλαγή με τη συγκεκριμένη κάρτα.

Πάντως, τα κουμπιά πληρωμών δε θέλουν κάποιο extra κώδικα από εσάς, ούτε success/fail urls.
Κάνετε απλά copy/paste τον κώδικα που δίνει το κουμπί.

Υποψιάζομαι ότι κατά το paste, το σύστημα που έχετε (κάποιο cms πιθανά), πειράζει ελαφρώς τον κώδικα και δημιουργεί το πρόβλημα. Ξαναδοκιμάστε, σε κάποια κενή -αρχικά- σελίδα και βεβαιωθείτε ότι δεν πειράχτηκε καθόλου το script που δίνει το κουμπί πληρωμής.

**Comment by thecrypt13** [comment]
Ο κώδικας που αντιγράφω είναι ακριβώς ο ίδιος με αυτόν που δημιουργεί το σύστημα. Ωστόσο, εξακολουθεί να βγάζει "Αποτυχία συναλλαγής".

Η πλατφόρμα που χρησιμοποιούμε είναι wordpress

Επίσης, υπάρχει περίπτωση να μπορεί να δημιουργηθεί κουμπί πληρωμής με ανοιχτό ποσό για να βάζει ο πελάτης ό,τι ποσό επιθυμεί? Εάν ναι με ποιο τρόπο?

Ευχαριστώ

**Comment by dmihos** [comment]
Δοκιμάστε, αν θέλετε, να βάλετε τον κώδικα σε μια κενή html σελίδα να δείτε αν λειτουργεί.
Η δοκιμή θα πρέπει να γίνει σε ένα physical html αρχείο, για να εξαλειφθεί η πιθανότητα κάποιο cms να "πειράζει" τον κώδικα (κάτι που φαντάζομαι ότι συμβαίνει στην περίπτωσή σας).
Αν υπάρχει πρόβλημα, μπορείτε να τη στείλετε στο support@vivawallet.com για περαιτέρω έλεγχο.

Σχετικά με το ανοιχτό ποσό, δυστυχώς δεν υπάρχει αυτή η δυνατότητα
