### ISSUE TITLE
Problem with Distinctive title

### ISSUE THREAD

**Issue by xenofon360** [VivaPayments/API#823]
Hi,

Our Company uses a Viva Wallet account to receive payments from a joomla / virtuemart eshop for 3 years now with no problem, everything works more than great.

Now, the same company, needs to create another eshop (WordPress / Woocommerce) this time and receive payments in the same Viva Wallet Account.

For this new eshop, we created a new payment source in the Websites / Apps Viva Wallet area, set correctly all the needed fields and right now, the state is "Active".

Also, we downloaded the official viva gateway plugin that this community suggests, set the options, everything is fine too.

My problem is this : https://pasteboard.co/Ibk5iGW.jpg (We contacted Viva before we come here - they send us here)

My problem is that for this VAT Number, the first site is auto filled for the Account (Taxis information), cause first site has the same name with Company. This name is not correct for the new site, cause this name is being viewed by customers into system emails of successful orders. I need the other site's name to be there.

Also these emails are related to the first site, i can not add more for the second site.

This VAT number is the problem. Viva support told me that i am not able to create another Viva wallet account with this VAT. So what am i going to do here? I do not want the first site that behold's company's name to be related for the second site for customers. I need them to work seperately.

So i am all ears community.

Best Regards,

**Comment by matthewrgourd** [comment]
Hi there, sorry for the lack of response previously. As far as I'm aware, if you wish to receive payments into two companies you would need separate Viva Wallet accounts. If the second business is VAT registered you would need to tell us a different VAT number (or leave blank if not VAT registered).
