### ISSUE TITLE
Customize email which Viva sends to buyers

### ISSUE THREAD

**Issue by Srdjann011** [VivaPayments/API#824]
Is there any way I can access to email confirmation which buyer receives after the process is finished?

**Comment by matthewrgourd** [comment]
Hi there, sorry for the lack of response previously. Which [online checkout](https://developer.vivawallet.com/online-checkouts) or [e-commerce plugin](https://developer.vivawallet.com/e-commerce-plugins/) are you using? Please reopen if still a problem.
