### ISSUE TITLE
Issue with Viva Wallet success redirect and changing order to processing on woocommerce 

### ISSUE THREAD

**Issue by wsupermarket** [VivaPayments/API#825]
On payment success uses going to a url and the page says

-1

Another issue is that woo commerce states pending payment even though we have had a notification from viva of a successful payment

finally some orders showing on woo commerce as penidng payment but no email received from viva even though that the payment option by the user.

Help!!!

Thanks

**Comment by wsupermarket** [comment]
Just to add, its wordpress, woocommerce and using the latest version of viva payments gateway

**Comment by VivaWalletSupport** [comment]
Hello, are you using the plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ and did you check the provided instructions?

**Comment by wsupermarket** [comment]
HI Yes that's it and followed it to the letter. Still getting the issues though. I can provide screen shots if required? Please advise how we go about rectifying these issues?

Many thanks

**Comment by VivaWalletSupport** [comment]
Please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by wsupermarket** [comment]
Plugin settings (mask the API Key):

![github1](https://user-images.githubusercontent.com/49955034/56723399-ca3bdf00-6740-11e9-9c90-2028823fdd85.jpg)

**Comment by wsupermarket** [comment]
Viva Wallet payment source settings (include the browsers URL in the screenshot):

![github2](https://user-images.githubusercontent.com/49955034/56723517-03744f00-6741-11e9-8b0e-3f7df6d162e8.jpg)

**Comment by wsupermarket** [comment]
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.

![github 3](https://user-images.githubusercontent.com/49955034/56723632-459d9080-6741-11e9-8013-1491f459514e.jpg)

**Comment by wsupermarket** [comment]
API Access page (mask API Key, include the browsers URL in the screenshot).

![github-4](https://user-images.githubusercontent.com/49955034/56723817-9ad9a200-6741-11e9-9089-ced851be7921.jpg)

**Comment by VivaWalletSupport** [comment]
You are **not** using the plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ Ask the plugin provider for assistance or use the supported plugin and follow the instructions.

**Comment by wsupermarket** [comment]
is everything else ok?

Is this below now the correct plugin?

![github5](https://user-images.githubusercontent.com/49955034/56726314-6c11fa80-6746-11e9-88b4-3049843fa2f9.jpg)

**Comment by VivaWalletSupport** [comment]
Are you experiencing any problem with the supported plugin?

**Comment by wsupermarket** [comment]
Testing it now - thanks for your help so far we shall report back ASAP

**Comment by VivaWalletSupport** [comment]
You're welcome, please close this issue ion case the problem is solved.

**Comment by wsupermarket** [comment]
No its not working, just tried a live purchase as a test

![image](https://user-images.githubusercontent.com/49955034/56752089-700e3e80-677f-11e9-8572-9b41e91ba053.png)

**Comment by wsupermarket** [comment]
This is now using the supported plugin as screenshot shows above with all setting in VIVA Wallet remaining the same as before - please help - thanks

**Comment by VivaWalletSupport** [comment]
What amount did you use for your test?

⁣Kind regards,
Tom van der Veer

+35796138974
+306977080153​

**Comment by wsupermarket** [comment]
All seems to be working thanks
