### ISSUE TITLE
Extended URL on Thank you page

### ISSUE THREAD

**Issue by spotcodes** [VivaPayments/API#826]
I have successfully integrated the Viva Payment gateway, however after making the payment when user redirects to the website it does not redirect on the linked Thank you page. The viva wallet automatically extend the Thank you page URL with some parameters , like that:

?t=056725aa-e26c-47c6-bf85-014e3dbf2c45&s=9826950016933929&lang=en-US

Please help to resolve this issue.

**Comment by VivaWalletSupport** [comment]
Please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

And a screenshot from the page that Viva redirects to.

**Comment by matthewrgourd** [comment]
Hi @spotcodes , as you've not got back to us, I assume this is no longer a problem so I'm closing the issue. Thanks!
