### ISSUE TITLE
Payment Buttons | Πρόβλημα με checkout page σε popup window

### ISSUE THREAD

**Issue by mgerolym** [VivaPayments/API#827]
Καλησπέρα σας, 

Αντιμετωπίζω ένα πρόβλημα στην υλοποίηση payment button. Η επιλογή show checkout page σε popup window δε λειτουργεί, o κώδικας που γίνεται export δημιουργεί την ίδια ακριβώς συμπεριφορά, ανοίγει τη σελίδα checkout σε νέα καρτέλα.

Δοκίμασα να παραμετροποιήσω τον κώδικα, στο σημείο που δηλώνεται **popup: 'False'** να προσθέσω **popup: 'True'**. Με αυτό τον τρόπο η λειτουργία αλλάζει, πράγματι εμφανίζεται το popup, αλλά υπάρχει πρόβλημα με τις διαστάσεις του σε mobile συσκευές. Φαίνεται να υπάρχει κάποιο πρόβλημα με τα styles (να μην παίρνει το σωστό ύψος τo iframe με τη φόρμα πληρωμής, με αποτέλεσμα να κρύβονται οι μισές πληροφορίες της φόρμας). 

Υπάρχει κάποιος άλλος τρόπος να ενεργοποιήσω το option για checkout page σε popup window;

Ευχαριστώ

**Comment by matthewrgourd** [comment]
Hi there, sorry for the lack of response previously. I'm afraid all I can suggest is you try our [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) in place of Simple Checkout. Thanks!
