### ISSUE TITLE
403 error and can't verify link

### ISSUE THREAD

**Issue by lewis4490** [VivaPayments/API#828]
Hi all,

I'm having a few issues getting the module to work properly and I can't seem to verify my link.

Verify my link: Error! The URL could not be verified. Please make sure you have entered a valid, publicly available, URL that conforms to these guidelines (Error code 502)

Also when trying to click pay now in the cart I am getting;
403
Forbidden
Access to this resource on the server is denied!

I am using Prestashop 1.7

Any help would be much-appreciated thanks in advance.

Kind regards,
Lewis

**Comment by VivaWalletSupport** [comment]
Please check that the modules and the vivawallet folders have the correct permissions (755), files should have 644 permissions.

**Comment by lewis4490** [comment]
Hello,

Thank you so much it is now working.

Can I give some advice please?

It doesn't mention to change the file permissions anywhere in the 
tutorial for setting it up.
Might be worth mentioning.

Thanks
Lewis

**Comment by VivaWalletSupport** [comment]
Thank you for the tip, in case your problem has been solved please close this issue.

**Comment by EmanonZero** [comment]
I am having the same issue, it will not verify my webaddress

http://kohaoracum.cluster027.hosting.ovh.net/index.php?wc-api=wc_vivawallet&vivawallet=webhook

Says above about folder permissions, how do I change them in Wordpress?

Thank you

![viva](https://user-images.githubusercontent.com/40642344/56862005-5c8cee80-699e-11e9-8751-d19728c82074.jpg)
