### ISSUE TITLE
The specified api action is disabled for the merchant

### ISSUE THREAD

**Issue by mauxtin** [VivaPayments/API#829]
Similarly to #793, can you please enable recurring transactions for my account?

It would be really helpful if you could enable everything for my account so that I don't have to wait 5 days each time I want to use a new feature. 

Thanks

Merchant: de735313-c85e-447d-ac0e-713cfde08341

**Comment by mauxtin** [comment]
Hey @VivaWalletSupport & @kostGX, any update on this?

**Comment by kostGX** [comment]
@mauxtin we have enabled recurring transactions for your account.

Best regards,
Kostas
