### ISSUE TITLE
Πληροφορίες σχετικά με τις επαναλαμβανόμενες πληρωμές

### ISSUE THREAD

**Issue by xaniotis27** [VivaPayments/API#83]
Θα ήθελα να πληρώνουν οι πελάτες μου μηνιαίως για τις υπηρεσίες που τους παρέχω.. Αυτό που θέλω είναι να εισάγω τις επαναλαμβανόμενες πληρωμές μέσω της viva και θα ήθελα να μου πείτε αν τα παρακάτω που σας γράφω για την τεχνική υλοποίηση είναι σωστά!!
 
Αρχικά μέσω της api/orders δημιουργώ ένα order και τον κάνει redirect στην σελίδα της viva ώστε να πληρώσει.. Στην φόρμα υπάρχει ένα checkbox που λέει για επαναλαμβανόμενες πληρωμές.
Όταν γίνει η πληρωμή και είναι τσεκαρισμένο το συγκεκριμένο πεδίο μέσω της api/transactions/transaction_number_pou_molis_egine κοιτάω εάν το RecurringSupport ισοδυναμεί με 1 και τότε αποθηκεύω στην βάση μου ότι ο πελάτης θέλει τις επαναλαμβανόμενες πληρωμές!
Οπότε εγώ κάθε μήνα θα τρέχω ένα δικό μου αρχείο(recurring_payment.php όπως δείχνετε και στο github) θα κοιτάω ποιος έχει ενεργοποιήσει το συγκεκριμένο πεδίο θα το τρέχω με το ποσό που έχει συμφωνηθεί και θα πληρώνει αυτόματα χωρίς να επεμβαίνει ούτε αυτός αλλά ούτε και εγώ... και μετά πάλι η ίδια διαδικασία!
 
Όλα αυτά που έχω γράψει είναι σωστά τεχνικά??
 
Σας ευχαριστώ πολύ

**Comment by dmihos** [comment]
Καλησπέρα σας

Είναι σωστά αυτά που περιγράφετε, σα λογική. 
Τις λεπτομέρειες, των API κλήσεων, τις βλέπετε στην πορεία (πχ στο CreateOrder πρέπει να ορίσετε AllowRecurring = true για να εμφανιστεί το checkbox στην checkout).

**Comment by xaniotis27** [comment]
Καλησπέρα σας,
Στην περίπτωση που κάποιος πελάτης στα payment options αντι να επιλέξει card επιλέξει να πληρώσει με viva wallet βλέπω ότι "εξαφανίζεται" η επιλογή του "recurring payments"! Δεν έχω και σε demo περιβάλλον λεφτά στο wallet ώστε να το τσεκάρω(Δεν ξέρω και πως μπορώ να βάλω σε demo περιβάλλον)! 
Συνοψίζοντας:
1) Τι γίνεται με το checkbox των επαναλαμβανόμενων πληρωμών όταν επιλέξει κάποιος viva wallet?
2) Σε demo περιβάλλον πως μπορώ να βάλω χρήματα ώστε να μπορέσω να το ελέγξω και με viva wallet?

Σας ευχαριστώ πολύ

**Comment by dmihos** [comment]
Καλημέρα
Οι απαντήσεις στα επιμέρους ερωτήματά σας:
1. Δυστυχώς δεν υποστηρίζουμε ακόμη recurring payment σε wallets
2. Στείλτε μας εδώ το walletId του προσωπικού σας λογαριασμού (φαίνεται στην ενότητα "To Viva Wallet μου - ΧΧΧΧΧΧΧΧ"), να το φορτίσουμε

**Comment by xaniotis27** [comment]
Καλημέρα σας,
Το walletid μου είναι 862755972605

Σας ευχαριστώ

**Comment by dmihos** [comment]
Προστέθηκαν funds στο wallet σας
