### ISSUE TITLE
Webhook using Woocommerce

### ISSUE THREAD

**Issue by EmanonZero** [VivaPayments/API#830]
![viva](https://user-images.githubusercontent.com/40642344/56862250-d6be7280-69a0-11e9-86f9-dd655cabcb37.jpg)

I cannot verify my domain when creating a webhook, any advice please, I have attached a screenshot of what happens.

Thank you

**Comment by VivaWalletSupport** [comment]
Please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by EmanonZero** [comment]
Thanks for the reply, here are the screenshots

![image](https://user-images.githubusercontent.com/40642344/56880100-5b69c900-6a53-11e9-8178-c1cdc60c61d1.png)
![image](https://user-images.githubusercontent.com/40642344/56880245-d8953e00-6a53-11e9-8f30-1ba1f835aaec.png)
![image](https://user-images.githubusercontent.com/40642344/56880276-f367b280-6a53-11e9-878e-df98e892274c.png)
![image](https://user-images.githubusercontent.com/40642344/56880316-1eea9d00-6a54-11e9-9861-3a8e93b8d030.png)

**Comment by VivaWalletSupport** [comment]
Use the instructions / plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ for the supported plugin or ask the plugin provider for assistance.

**Comment by EmanonZero** [comment]
I did all this and the verification button returns the error I sent on my first post here.

Thanks

**Comment by VivaWalletSupport** [comment]
The screenshots from the plugin settings / payment source setup you posted are not from the supported plugin that can be downloaded from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

**Comment by EmanonZero** [comment]
That worked with the correct plugin, thank you very much for your help and quick responses.

**Comment by VivaWalletSupport** [comment]
You're welcome, please close this issue in case the problem has been solved.
