### ISSUE TITLE
Gateway is charging euro sites in Puunds

### ISSUE THREAD

**Issue by jimORH** [VivaPayments/API#831]
If a customer buys something in a euro region for E 100 euro for example the will charged GBP 100. 

so via payment is not converting to euro. 

We are using shopify .

**Comment by paneksypnos** [comment]
The same it happens also using WooCommerce. We are based in UK, but our e-Shop prices are in Euros.
Any euro amount is "translated" into GBP ... 
Any solution?

**Comment by jimORH** [comment]
as you can see i left this message over a week ago with no support. 

It is just as well we are moving to a new provider.

**Comment by dmihos** [comment]
Please check https://github.com/VivaPayments/API/issues/822
