### ISSUE TITLE
WOOCOMMERCE WEBHOOK 

### ISSUE THREAD

**Issue by cedconsult** [VivaPayments/API#833]
Hello, 
Hello, I downloaded the module from Vivawallet, 
I followed all the steps for the installation

but I have problems installing the new payment module and for the WEBHOOK

and when I go on the link I have that

Warning: sizeof(): Parameter must be an array or an object that implements Countable in /home/clients/9a9f7c20096b786adaacf45f61f90838/web/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php on line 585

and  wen i want to test the module,  i have this 

404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

can you help me ?

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by cedconsult** [comment]
I tried with the redirection and with the native version, 
I have the same problem with 4 sites of different clients 
with the same template Impreza ...

![website-native](https://user-images.githubusercontent.com/50151834/57038398-19f73a80-6c5a-11e9-815c-abc128a67e15.jpg)
![website-redirrection](https://user-images.githubusercontent.com/50151834/57038399-1a8fd100-6c5a-11e9-83ee-03330af52be0.jpg)
![aps](https://user-images.githubusercontent.com/50151834/57038400-1a8fd100-6c5a-11e9-8784-8e8335257ba3.jpg)
![api](https://user-images.githubusercontent.com/50151834/57038401-1a8fd100-6c5a-11e9-8512-351f7a88d817.jpg)
![webhook](https://user-images.githubusercontent.com/50151834/57038402-1a8fd100-6c5a-11e9-9216-78405620cb23.jpg)
![page site](https://user-images.githubusercontent.com/50151834/57038403-1a8fd100-6c5a-11e9-8579-2a6bb5589af0.jpg)
![plugin](https://user-images.githubusercontent.com/50151834/57038404-1a8fd100-6c5a-11e9-9540-86126a70394d.jpg)

**Comment by VivaWalletSupport** [comment]
Un-check the Test mode from the plugin settings as you are using the credentials from your live account. The plugin does not support the native mode (only redirection), make the necessary corrections in your Viva account settings.

**Comment by cedconsult** [comment]
Thank you very much , it's working now !!!

**Comment by cedconsult** [comment]
Have a nice day !

**Comment by cedconsult** [comment]
Hello, same problem with 2 other website, 
I followed the same procedure but I do not know how to create my webhook

**Comment by cedconsult** [comment]
![redirrection-myrolls](https://user-images.githubusercontent.com/50151834/57066053-7b0b2680-6ccb-11e9-9c51-422bf5ee441e.jpg)
![website-marools](https://user-images.githubusercontent.com/50151834/57066055-7b0b2680-6ccb-11e9-8071-2b72e0537112.jpg)
![api-marols](https://user-images.githubusercontent.com/50151834/57066056-7b0b2680-6ccb-11e9-8db5-b9315fe937f5.jpg)
![webhook-marolls](https://user-images.githubusercontent.com/50151834/57066057-7b0b2680-6ccb-11e9-9f1c-48ee26cb2e48.jpg)
![application-marolls](https://user-images.githubusercontent.com/50151834/57066058-7ba3bd00-6ccb-11e9-90db-c8fd0fab3322.jpg)

**Comment by VivaWalletSupport** [comment]
Please post the screenshots as in your previous post (to see all settings) and disable native checkout.

**Comment by cedconsult** [comment]
hello what screenshot are you missing?

**Comment by cedconsult** [comment]
![application-2](https://user-images.githubusercontent.com/50151834/57080222-5d04ec80-6cf2-11e9-93f3-2e20734f9cf2.jpg)

**Comment by VivaWalletSupport** [comment]
Try disabling error reporting when checking the webhook.

**Comment by cedconsult** [comment]
ok like this ?
![webhook-marolls-2](https://user-images.githubusercontent.com/50151834/57082862-e0750c80-6cf7-11e9-8313-2cfc088d1bbf.jpg)

**Comment by VivaWalletSupport** [comment]
Disable error reporting so that the warning does not show (breaking the verification) in PHP 7.2+
https://marolls-cbd.be/index.php?wc-api=wc_vivawallet&vivawallet=webhook

**Comment by cedconsult** [comment]
I have to go where to disable that? On th FTP, in wp-config it is 

define('WP_DEBUG',          false);
define('WP_DEBUG_LOG',      false);
define('WP_DEBUG_DISPLAY',  false);

**Comment by cedconsult** [comment]
Ok i ad this

 display_errors= off
error_reporting=E_ALL & ~E_NOTICE & ~E_STRICT 

on user.ini
and now it's ok 

Thank you 
i do the same for my another website ;)

**Comment by cerbere83** [comment]
Hey I have the same problem.
I need help.
Thank
