### ISSUE TITLE
The transaction does not allow recurring charge

### ISSUE THREAD

**Issue by pefremidis** [VivaPayments/API#836]
Καλησπέρα,

προσπαθώ να φτιάξω επαναλαμβανόμενες πληρωμένες. Διάβασα τα σχετικά issues που υπάρχουν εδώ και μπορώ να το πετύχω.

Έχω ενεργοποιήσει στο account μου τις επαναλαμβανόμενες πληρωμές.
Όταν δημιουργώ ένα αρχικό order στέλνω την παράμετρο 'AllowRecurring' => true.
Όταν δημιουργώ για πρώτη φορά το transaction στέλνω την παράμετρο 'AllowsRecurring' => true

το error που παίρνω είναι 
Error 403': Invalid transaction. The transaction 204f846c-ec4b-4f93-ba1f-e7cc0c107c5c does not allow recurring charge

Επίσης ψάχνω στο documentation και δεν βρίσκω κάπου ξεκάθαρα πως να κάνεις create ένα transaction. 

Χρησιμοποιώ Native Checkout. Παίζει κάποιο ρόλο;

**Comment by mauxtin** [comment]
Αντιμετωπίζω το ίδιο πρόβλημα με ακριβώς τα ίδια βήματα. Μήπως βρήκες τη λύση @pefremidis?

**Comment by pefremidis** [comment]
@mauxtin καλησπέρα.
Να πω την αλήθεια δεν ασχολήθηκα σήμερα με το συγκεκριμένο.
Θεωρώ το documentation αρκετά ελλειπές στο κομμάτι του transaction.
Εσύ πως το χρησιμοποιείς το Native Checkout?
Έχεις κάποιο framework τύπου Laravel ή κάποιο Wordpress, Drupal?

**Comment by mauxtin** [comment]
Καλησπέρα @pefremidis 

Χρησιμοποιώ το [Laravel-Viva-Payments](https://github.com/sebdesign/laravel-viva-payments) και έχω ανοίξει issue [εδώ](https://github.com/sebdesign/laravel-viva-payments/issues/9) αλλα φαίνεται να είναι θέμα της viva.

Έχω δοκιμάσει και μέσω postman με το ίδιο error

**Comment by pefremidis** [comment]
Καλημέρα υπάρχει κάποιος που μπορεί να μας πει τι συμβαίνει τελικά;
Έχει περάσει μία βδομάδα και δεν έχω λάβει κάποια ενημέρωση.

Είμαι ενεργός πελάτης τα τελευταία 2 χρόνια με ΑΦΜ 133769261 και θέλω να προχωρήσω το σύστημα πληρωμών ένα βήμα παρακάτω. Αν δεν υπάρχει το ελάχιστο support τότε πως θα μπορέσω να το κάνω αυτό; 
Κάλεσα τηλεφωνικά με παραπέμπουν εδώ. Στέλνω εδώ και δεν εμφανίζεται κανένας. Τι κάνουμε τελικά; Υπάρχει λύση στο συγκεκριμένο; Κάνω κάτι λάθος εγώ; Βλέπω υπάρχει και άλλος κόσμος που έχει το ίδιο θέμα.

**Comment by sebdesign** [comment]
Το πρόβλημα έχει αναφερθεί κι από μένα πριν 3 χρόνια [σε αυτό το issue](https://github.com/VivaPayments/API/issues/54), αλλά δεν έχω λάβει σαφή απάντηση.

**Comment by mauxtin** [comment]
@kostGX @VivaWalletSupport ????

**Comment by matthewrgourd** [comment]
Hi all, I'm sorry no-one replied to this issue previously. Laravel Viva Payments is not an official Viva Wallet package so unfortuanately we can't provide specific support. Regarding getting help with Native Checkout or our Payments API, please see the below pages on our developer portal. I hope this helps. Thanks!

https://developer.vivawallet.com/online-checkouts/native-checkout-v2
https://developer.vivawallet.com/api-reference-guide/payment-api-details

**Comment by sebdesign** [comment]
@matthewrgourd as others have explained, it's not an issue specific to the Laravel package.
Even using Postman fails when trying to create a recurring transaction, according to the developer portal: https://developer.vivawallet.com/api-reference-guide/payment-api-details/#create-recurring-transaction

**Comment by matthewrgourd** [comment]
Hi @sebdesign please send through any request / response logs you may have available so I can look into this further.
