### ISSUE TITLE
Viva payments don't work on my Shopify Store even though i have the Store Token and Merchand id connected

### ISSUE THREAD

**Issue by Cosmowill** [VivaPayments/API#838]
Hello, even though i have completed all the steps to integrate Viva Wallet on my store, when a customer tries to pay, Viva Wallet then redirects him to Viva's website to complete his purchase. What happens next is that the webpage doesn't work correct and it writes “Could not create order. Generic error.”

I am attaching a screenshot of what the redirect webpage looks like.

![unnamed](https://user-images.githubusercontent.com/50326864/57225430-00b50c00-7015-11e9-9c53-283435ad2a4e.jpg)

Please help me as soon as possible because i am losing time and therefore money.

Kind Regards

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry no-one got back to you previously. Could you please let me know if this is still an issue and I'll follow up for you?

**Comment by Cosmowill** [comment]
Hello, i fixed the problem thank you!

I just want to ask if Viva Wallet works fine in all the countries, so can i
accept money from countries like Qatar, Serbia, Switzerland without a
problem?

Kind Regards

**Comment by matthewrgourd** [comment]
Hi there, that's good to know. About your other question, I'm just checking. Will get back to you tomorrow. Thanks!

**Comment by matthewrgourd** [comment]
Hi @Cosmowill, we can confirm this, yes. Thanks!

**Comment by Cosmowill** [comment]
I want to ask one more question.

Is it possible to connect Viva Wallet to a wix website?

Kind Regards

**Comment by matthewrgourd** [comment]
Hi @Cosmowill Unfortunately we currently don't have available a Viva Wallet plugin / extension for Wix Ecommerce. Thanks!

**Comment by subir1910** [comment]
Hi @Cosmowill 

I m facing the same issue. I tried multiple time to integrate it but every time it's show the error.

Please help
Thankyou

**Comment by subir1910** [comment]
Please help me as soon as possible because i am losing time and therefore money.

**Comment by Steevo0206** [comment]
Hi @Cosmowill can you please tell how you fixed your issue I have exactly the same one.
Thank you

**Comment by matthewrgourd** [comment]
Hi @subir1910, please raise a new issue on our GitHub homepage at https://github.com/VivaPayments/API/issues describing in detail the problem you're experiencing. Are you using a specific plugin or attempting to integrate with the Viva Wallet API? Are any errors occurring, if so, can you let me have screenshots? Is it a problem when attempting to pay by mobile or desktop or both? I will endeavour to answer your query as soon as possible once you have opened the ticket. Thanks!

**Comment by matthewrgourd** [comment]
Hi @Steevo0206, please raise a new issue on our GitHub homepage at https://github.com/VivaPayments/API/issues describing in detail the problem you're experiencing. Are you using a specific plugin or attempting to integrate with the Viva Wallet API? Are any errors occurring, if so, can you let me have screenshots? Is it a problem when attempting to pay by mobile or desktop or both? I will endeavour to answer your query as soon as possible once you have opened the ticket. Thanks!
