### ISSUE TITLE
Τι επίπεδο SSL certificate χρειάζεται να αγοράσω;

### ISSUE THREAD

**Issue by aigiorama** [VivaPayments/API#84]
Βλέπω ότι στα ssl certificate κυκλοφορούν διάφορα πακέτα. Επειδή είμαι καινούριος σε αυτό, μπορείτε να μου πείτε τι επίπεδο ssl certificate χρειάζεται να αγοράσω για το vivapayments; Σας ευχαριστώ.

**Comment by dmihos** [comment]
Δεν υπάρχει κάποια συγκεκριμένη πρόταση/requirement, από την πλευρά μας.
Προτείνω να συμβουλευτείτε την εταιρία που σας παρέχει το hosting στο site σας.
