### ISSUE TITLE
Payment problem vivawallet woocommerce

### ISSUE THREAD

**Issue by cedconsult** [VivaPayments/API#842]
Hello, payments are refused 
https://greenline-cbd.be

![IMG_2614](https://user-images.githubusercontent.com/50151834/57283203-edef1580-70ae-11e9-95ba-60f0a6ea9b88.JPG)

**Comment by cedconsult** [comment]
Can you help me ?

**Comment by matthewrgourd** [comment]
Sorry for the delayed reply. I believe this is a refusal on the part of the card issuer rather than Viva Wallet. Is this problem resolved now?
