### ISSUE TITLE
WooCommerce Vivawallet Gateway - pending payment error 

### ISSUE THREAD

**Issue by cmikrovas** [VivaPayments/API#843]
Hello,
my site is WordPress and there is a problem with the Viva wallet plugin.
While it normally charges the transaction card, it returns the order to the store as a pending payment and does not notify the administrator and the customer by email.

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by VivaWalletSupport** [comment]
In case you have solved the problem, please close this issue.

**Comment by cmikrovas** [comment]
Hello,i havent solved it. I am trying to gather the information (screenshots) that you need to proceed.

**Comment by VivaWalletSupport** [comment]
According to the provided screenshots you are using a 3rd party plugin, contact the developer for support or use the supported plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

In case that solved the problem, please close this issue.
