### ISSUE TITLE
ρυθμίσεις github

### ISSUE THREAD

**Issue by sw1gr** [VivaPayments/API#845]
Καλησπέρα σας
έχω ένα eshop σε prestashop , έχω εγκαταστήσει ένα module που κάνει τη σύνδεση me viva wallet έχω κάνει τις βασικές ρυθμίσεις στο viva wallet και τώρα θα πρέπει να προχωρήσω στις ρυθμίσεις του  Github . θα μπορούσατε σας παρακαλώ να με βοηθήσετε σχετικά  ;

**Comment by VivaWalletSupport** [comment]
For installation and setup see https://developer.vivawallet.com/e-commerce-plugins/prestashop/

**Comment by sweetecgr** [comment]
καλησπέρα σας
Μόλις εγκαταστήσω το module μου απενεργοποιεί όλες τις μεθόδους πληρωμής.
Στο τελευταίο βήμα της παραγγελίας μου γράφει δεν υπάρχει μέθοδος πληρωμής. 
Πρέπει να το κάνω απεγκατάσταση για να ενεργοποιηθούν πάλι οι μέθοδοι πληρωμής.
(έχω paypal , αντικαταβολή , κατάθεση σε τράπεζα.)
Prestashop 1.7.5.1

**Comment by VivaWalletSupport** [comment]
Enable the payment module after you have setup the payment source in Viva and when the source has been activated.

**Comment by sweetecgr** [comment]
καλημέρα σας
Μεταφράζω το "pay by viva"  στα ελληνικά στο admin  , αλλά δεν αλλάζει στο eshop   , συνεχίζει να φαίνεται το pay by viva στο check out στα Αγγλικά .

**Comment by VivaWalletSupport** [comment]
Hello, can you post the translation files?

**Comment by sweetecgr** [comment]
Hi 
i send you tranlsations folder (zip)
[Translations.zip](https://github.com/VivaPayments/API/files/3186061/Translations.zip)

**Comment by VivaWalletSupport** [comment]
Try attached.
[Translations.zip](https://github.com/VivaPayments/API/files/3186971/Translations.zip)

**Comment by sweetecgr** [comment]
ok
thanks a lot . its fine .
