### ISSUE TITLE
Integration with Duda

### ISSUE THREAD

**Issue by john-antunes** [VivaPayments/API#846]
Hi,

We are looking to develop a new website using the Duda platform (www.duda.co). VivaWallet is not listed on Duda's list of payment gateways. Please can you tell me if you can integrate with Duda's ecomm platform?

**Comment by kostGX** [comment]
Hello @john-antunes,

We just reached out to Duda to learn more about integrating with them.

We currently don't support a plug n play integration with Duda, but if they allow you to embed custom code and make API calls from their platform, then you could go about building a DIY solution by following the developer docs @ https://developer.vivawallet.com

If this answers to your question please close the issue.

Best regards,
Kostas
