### ISSUE TITLE
Payment create token error

### ISSUE THREAD

**Issue by pilixonis** [VivaPayments/API#848]
Hello i created an account to viva wallet and i got a merchantId, an API key and a public key. I used the Native Checkout v1.0 and i get an error: 404 Account token was not found for key {myPublicKey}, when i am using my public key. When i tried the same form with a demo public key from your examples, the form submits and creates a Token. Do i have to do something with my account in order to enable my public key?

**Comment by kostGX** [comment]
@pilixonis Hello can you please post the documentation link you're trying to implement and details of the step you're having errors with?

Thanks!

**Comment by pilixonis** [comment]
Hello, I tried with both: https://developer.vivawallet.com/online-checkouts/simple-checkout/
and https://developer.vivawallet.com/online-checkouts/native-checkout-v1/ 
and used my public Key from my account, that i have already set for native checkout use.

From both of them i have the same response: Invalid merchant public key

**Comment by kostGX** [comment]
@pilixonis Ok but on demo, with the exact same code you have no issues?

What steps do you take from moving from demo to production?

**Comment by pilixonis** [comment]
No i am just trying on demo, although i tried at production i had the same error. Never got it to work properly. I meant in my first message with "demo public key" that i used another public key that i found, which i supposed was a demo public key, and both simple and native checkout worked properly and i got a token and when i switched back to my public key the error message was shown again, so i am supposing that is a problem with my public key and not with the code.

**Comment by kostGX** [comment]
Ok let's try doing this on demo. Can you share your merchant id (found under: Settings > API Access)

**Comment by pilixonis** [comment]
You mean the public key or the merchant id? is it safe to share merchant id?

**Comment by kostGX** [comment]
Yes it is @pilixonis

**Comment by pilixonis** [comment]
merchantid: 5cd6cc16-d641-42eb-8c6f-a4a37ead7df3

public key: /oo6Mtg1BPtUhZowR6HUGtvoN6ZoP2VtfXnrnVhSTGo=

**Comment by kostGX** [comment]
@pilixonis these are production credentials. could you please go about posting your DEMO credentials. You can create demo credentials in this website:

http://demo.vivapayments.com/en-us/signup

Login to demo from this link: http://demo.vivapayments.com/en-us/signin

**Comment by pilixonis** [comment]
Did't realize i have to create different account for the demo. I tried with the new account and everything works fine, thank you.
