### ISSUE TITLE
Webhook για card transactions

### ISSUE THREAD

**Issue by thanos-ar** [VivaPayments/API#849]
Καλημέρα,

προσπαθώ να στίσω ένα automation όπου όταν θα γίνει ένα transaction σε κάποια κάρτα εργαζομένουν στο business account τα data του transaction θα περνιούνται στο CRM. Έστισα ένα webhook για Transaction Payment Created, αλλά δεν έτρεξε για Wallet2Wallet Transfer, επίσης δεν είμαι σίγουρος αν θα γίνεται trigger γενικότερα καθώς δεν είμαι σίγουρος αν τα transactions που ορίζεις στο webhook είναι SALES TRANSACTIONS ή αν πιάνει οποιοδήποτε transaction>

Please advice.

**Comment by thanos-ar** [comment]
Καλησπέρα,

κάποια απάντηση στο παραπάνω;;;

**Comment by matthewrgourd** [comment]
Hi there, please see https://developer.vivawallet.com/api-reference-guide/payment-api-details/webhooks/ I hope this helps. Thanks!
