### ISSUE TITLE
Native checkout και integration με Joomla 3.5

### ISSUE THREAD

**Issue by aigiorama** [VivaPayments/API#85]
Απ' όλη τη διαδικασία του native checkout που δίνετε ως παράδειγμα, απλώς κάνω copy/paste το φάκελο της php ή και ό,τι αφορά android κτλ; Έχω ένα site που στηρίζεται σε joomla και δουλεύω πάνω στο hikashop, αλλά ο πελάτης θέλει απλώς να βάζουν τον αριθμό της κάρτας τους και χωρίς να φεύγουν από το site να γίνεται η δουλειά. Πραγματικά έχω μπερδευτεί. Επίσης, θέλει να υπάρχει και μια μικρή φόρμα. Μου έχει δώσει για παράδειγμα αυτή τη σελίδα, αλλά να το στήσω στο Joomla: https://www.leadershipinstitute.org/Contribute/
Ευχαριστώ όπως και να έχει.

**Comment by dmihos** [comment]
Καλημέρα
Θα πρέπει να μελετήσετε τον οδηγό για τη [Native Checkout](https://github.com/VivaPayments/API/wiki/Native-Checkout) καθώς και τα αντίστοιχα [samples](https://github.com/VivaPayments/API/tree/master/NativeCheckout).

Ο κώδικας είναι ενδεικτικός για να παρουσιάσει τις δυνατότητες. 
Θα πρέπει να τον μελετήσετε για να τον εντάξετε στο site σας, ώστε να μπορείτε να τον υποστηρίξετε τεχνικά. Δεν πρόκειται για κάποιο plugin το οποίο θα δουλέψει με τη λογική του copy-paste.
Ότι απορία έχετε, μπορείτε να τη στέλνετε εδώ.
