### ISSUE TITLE
Viva Wallet issue with Shopify | Πρόβλημα με Viva Wallet και Shopify

### ISSUE THREAD

**Issue by farmhellas** [VivaPayments/API#850]
Even though my Shopify store is connected to my Viva Wallet (Merchant ID and Store Token) when proceeding to payment through my website, it throws my clients here. Please give some feedback ASAP!
<img width="1280" alt="Στιγμιότυπο 2019-05-15, 10 36 09" src="https://user-images.githubusercontent.com/50234024/57772075-334dbb80-771d-11e9-8513-7a8ca6f3abce.png">

**Comment by dmihos** [comment]
You've either been sent an incorrect token or you mistyped it on the Shopify page.
Please ask the support team to verify your store token and make sure you copy/paste it correctly (no missing characters, no trailing spaces etc)

**Comment by farmhellas** [comment]
They haven't provided me a Store Token yet!

**Comment by dmihos** [comment]
Please follow this guide carefully
https://developer.vivawallet.com/e-commerce-plugins/shopify/
