### ISSUE TITLE
API credentials incorrect or api unavailable error

### ISSUE THREAD

**Issue by andrewbird84** [VivaPayments/API#851]
Hi, I am trying to use viva payments plugin to take payments with Woocommerce. I have been backwards and forwards for days with other issues, but now it seems to be working, although cannot take a payment as "API credentials incorrect or api unavailable error". I have included screenshots of my settings. I was told by someone at viva wallets support to open a ticket here and give the following screenshots, including the url bar. I have read through many posts saying the same thing, and have checked all that I can myself. 
Any help would be appreciated.

![api settings page](https://user-images.githubusercontent.com/17703228/57799342-c64f1b80-7746-11e9-828a-1e3947230e5f.JPG)
![app settings](https://user-images.githubusercontent.com/17703228/57799343-c6e7b200-7746-11e9-99e0-9faf1643c4db.JPG)
![payment source page](https://user-images.githubusercontent.com/17703228/57799344-c6e7b200-7746-11e9-86c4-f58667c7a13e.JPG)
![settings page](https://user-images.githubusercontent.com/17703228/57799345-c6e7b200-7746-11e9-92ec-584169a04350.JPG)

**Comment by VivaWalletSupport** [comment]
You have checked "Enable Test Mode" in the plugin settings while you seem to use the credentials from your Viva live account. In case the problems has been solved, please close this issue.

**Comment by ngoun** [comment]
Ωραία
Στις Πέμ, 16 Μαΐ 2019, 05:59 ο χρήστης Tom van der Veer <
notifications@github.com> έγραψε:

**Comment by andrewbird84** [comment]
I have disabled test mode and now it redirects to the 'enter card details'
page as it should. However when I try and complete the sale it fails and
the order remains as pending payment on woocommerce and there is no money
in viva wallet account.

**Comment by andrewbird84** [comment]
OK, so money went through as it should for the last sale I just made, I can
see it on my viva wallets dashboard. However there is no sale at all in
woocommerce, not even a pending payment sale.

**Comment by andrewbird84** [comment]
After more attempts this is what happens.

I try to make the sale and I am redirected to viva payments for payment processing as it should, there I fill out my card details and complete the order.

The payment seems to be successful. But it goes back to my site to this url

https://ukseedstore.com/index.php?wc-api=wc_vivawallet&vivawallet=success&t=d3046786-6ab9-45fb-ab2e-6465c5804335&s=5061034171946840&lang=en-US

and displays this below on a blank page at the url mentioned above

-1

Once I check woocommerce orders there is no order at all

and as the customer, when I load the site front end back up the items are still in my basket

**Comment by VivaWalletSupport** [comment]
Download and use the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
