### ISSUE TITLE
woo commerce... no order placed/ received after payment

### ISSUE THREAD

**Issue by christosham** [VivaPayments/API#852]
We downloaded and installed the viva wallet payment plug in from the link below
https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

However, after succesful payment, we dont see any order in our system. 

We use the payment for downloadable products but our athletes dont receive their confirmation emails from woocommerce, only the confirmation email from vivawallet.
http://www.brevetphilippi.com/

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by christosham** [comment]
hello... attached the screenshots you requested
![plugin settings](https://user-images.githubusercontent.com/50735176/57971508-d3af1480-7997-11e9-9b33-68a05b8ecaf8.png)
![API Access page](https://user-images.githubusercontent.com/50735176/57971509-d3af1480-7997-11e9-91af-c7ffc595e925.png)
![Viva Wallet WebsitesApps page](https://user-images.githubusercontent.com/50735176/57971510-d3af1480-7997-11e9-8e6c-98284d155f45.png)
![Viva Wallet payment source settings](https://user-images.githubusercontent.com/50735176/57971511-d3af1480-7997-11e9-8876-08ac20f3ec1f.png)

**Comment by VivaWalletSupport** [comment]
Please follow the setup instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ to the letter and close this issue when the problem has been solved. Otherwise re-post the requested screenshots after correcting the settings.
