### ISSUE TITLE
Probleme connexion vivawallet 

### ISSUE THREAD

**Issue by skunkercbd** [VivaPayments/API#853]
Hi, I am trying to use viva payments plugin to take payments with Shopify. I have been backwards and forwards for days with other issues, but now it seems to be working, although cannot take a payment as "API credentials incorrect or api unavailable error". I have included screenshots of my settings. I was told by someone at viva wallets support to open a ticket here and give the following screenshots, including the url bar. I have read through many posts saying the same thing, and have checked all that I can myself.
Any help would be appreciated.
![IMG_0045](https://user-images.githubusercontent.com/50751937/57950361-52984480-78e7-11e9-97d2-ae511df91a14.PNG)
![IMG_0046](https://user-images.githubusercontent.com/50751937/57950362-52984480-78e7-11e9-90aa-564fcf7867cc.PNG)
![IMG_0047](https://user-images.githubusercontent.com/50751937/57950363-5330db00-78e7-11e9-9609-0dc9fc3b1e8c.PNG)
![IMG_0049](https://user-images.githubusercontent.com/50751937/57950364-5330db00-78e7-11e9-9903-721292e658a4.jpg)
![IMG_0029](https://user-images.githubusercontent.com/50751937/57950424-78254e00-78e7-11e9-95fa-7e30b0287770.PNG)

**Comment by dmihos** [comment]
This is the only guide you need to carefully follow
https://developer.vivawallet.com/e-commerce-plugins/shopify/
