### ISSUE TITLE
vivawallet for woocommerce technical help 

### ISSUE THREAD

**Issue by exciteforlife** [VivaPayments/API#854]
![Screenshot_20190516-164856_Chrome](https://user-images.githubusercontent.com/50826665/58012281-108c2000-7aec-11e9-8894-6558810ad9ce.jpg)

Hello, 
Im just wondering if anyone can help. 
Im unable to get any help from vivawallet and my web developer is away. 

Ive installed the vivawallet plug in and done succesful tests yet customers are still experiencing issues when trying to pay. see attached screenshot. it just isn't showing the sumbit button. 

Also at the cart page the vivawallet doesn't look that secure. 
Usually payment processors will put pictures of debit cards and say something like secure verified etc. please see attached screenshot like paytriot has. is there any way i can add this ?

![viva screen shot](https://user-images.githubusercontent.com/50826665/58012864-50073c00-7aed-11e9-8ae5-97e2fb5d8188.png)

Ive looked in the app on woocommerce and it has an api key in but I want to check its the right one. I cant locate the vivawallet api key in my back office account so not sure how to check this. 

Any help would be greatly appreciated

many thanks 
rachael

**Comment by VivaWalletSupport** [comment]
Hello, I did not experience any problem when making a test. Check your error logs to see what error happened on your server at the time your customer experienced this problem. You could also edit the used png icon that is located in your plugin folder to adjust it to your needs. For screenshot where you can ocate your API Key please have a look at https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

In case this solved your problem, please close this issue.

**Comment by exciteforlife** [comment]
Thanks Tony,

Can I just double check how you change the PNG icon. Ive looked in plugins
and it doesnt have an option to edit. The vivawallet in woocommerce
settings under payment also doesn't have an option to change the PNG just
the wording.

Thanks
Rachael
*Best Wishes *
*Rachael Wilson *
*Director *

*Excite for Life Ltd *
*7 Westgate *
*Cleckheaton *
*West Yorkshire *
*BD19 5ET*

*TEL:01274 872 468*

*Follow us on **Facebook <http://www.facebook.com/cbdwoman>  Instagram
<http://www.instagram.com/cbdwoman>  Youtube
<https://www.youtube.com/cbdwoman>*


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by VivaWalletSupport** [comment]
There is no option in the plugin settings, you would have to download the png file from your plugin folder with a file manager tool (like FTP), make your changes and upload it back.

**Comment by exciteforlife** [comment]
Great Thanks Tony
