### ISSUE TITLE
trying again seeing as my first support query was ignored

### ISSUE THREAD

**Issue by john-antunes** [VivaPayments/API#856]
Hi,

We are looking to develop a new website using the Duda platform (www.duda.co). VivaWallet is not listed on Duda's list of payment gateways. Please can you tell me if you can integrate with Duda's ecomm platform?

**Comment by matthewrgourd** [comment]
Hi there, apologies for the delayed response. I'm afraid we don't currently have a plugin for the Duda platform. However, thank you for your interest!
