### ISSUE TITLE
After transaction succesful, 404 error page not found?

### ISSUE THREAD

**Issue by robertpace** [VivaPayments/API#857]
HI, 
Viva integration into Woocommerce, all conected and working fine, payments taken and showing in wallet, all good.
However, when the payment is taken it does not go to the payment successful page, it just shows a page not found 404 error and the basket does not empty?
The site is currently offline working from a wordpress staging platform, will this issue correct when it becomes live? ie, it cant loop back to the payment successful page because its still in staging and not the .co.uk address? or is there another problem that needs looking at?
Thanks in advance.
Robert

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by matthewrgourd** [comment]
Hi @robertpace , as we've not heard from you again, I'm assuming this is no longer an issue or you have found a solution elsewhere. Obviously if this is not the case, please let us know. Thanks!
