### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by butt1989** [VivaPayments/API#858]
hi 
iam facing issue if i pay from my own card debit card from uk its works fine, if any customer try to pay from usa or japense its giving error code 404 usually error appears after check out page
 url: http://tpcsolution.com

**Comment by butt1989** [comment]
![thumbnail (1)](https://user-images.githubusercontent.com/50702598/58166538-f3895580-7c81-11e9-8fe2-d54f819061a2.jpg)
![Uploading thumbnail.jpg…]()

**Comment by VivaWalletSupport** [comment]
Hello, try the supported plugin and guidelines from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
Please note that you cannot use another currency then the one used in your Viva account (GBP in your case).
In case this solves you problem, please close this issue.
