### ISSUE TITLE
Magento 2 not trigger order emails with VIVA

### ISSUE THREAD

**Issue by ioannisgz** [VivaPayments/API#859]
Hi. I am having an issue with magento 2.3.1
Although the transaction is completed and we capture the amount in VIVA gateway, Magento returns to success page but order emails are not triggering. No error in logs.
This has something to do your module because all other orders without VIVA payment, emails are fine. We have set the order status after order with VIVA to processing status.
Any help please?

**Comment by VivaWalletSupport** [comment]
Hello, what email is missing, the one send to the customer, admin, both?
Is the order updated correctly to the set status?

**Comment by ioannisgz** [comment]
Hello. Both emails are missing. The order is updated correctly. And if you go inside order you can send the mail manually which is working

**Comment by VivaWalletSupport** [comment]
Please implement the latest version of the API/Plugins/magento/magento23_vivawallet/Ced/VivaPayments/Controller/Viva/Callback.php file and inform me if the problem persists. Otherwise pleas close this issue.
