### ISSUE TITLE
redirect πολυγλωσο

### ISSUE THREAD

**Issue by jasonpoul** [VivaPayments/API#86]
geia sas ginete sti redirect forma plirwmis stoixiwn kartas na einai diglwsi na iparxei i epilogi metaksi ellinikwn kai aglikwn i na fainodai kai ta dio tautoxrona? euxaristw

**Comment by dmihos** [comment]
Γεια σας
Μπορείτε μόνο, από πριν, να ορίσετε τη γλώσσα, περνώντας στο url της checkout 
lang=el-GR ή 
lang=en-US

**Comment by jasonpoul** [comment]
kai pws borw an to orisw gia kathe glwsa ksexwrista to url?

2016-04-14 9:25 GMT+03:00 dmihos <notifications@github.com>:

**Comment by dmihos** [comment]
Φαντάζομαι αναφέρεστε στα redirect urls, που ανακατευθύνεται ο πελάτης μετά την πληρωμή.
Δεν υποστηρίζονται urls ανά γλώσσα. 
Αν πρέπει οπωσδήποτε να υποστηρίξετε αυτή τη λογική, τότε θα πρέπει να φτιάξετε 2 πηγές και να τις χρησιμοποιείτε εναλλάξ, ανάλογα τη γλώσσα που θέλει ο πελάτης. 
Αντίστοιχα, θα ορίσετε κατάλληλα redirect στην καθεμία.

**Comment by jasonpoul** [comment]
exw to plugin to dwrean apo to emspace pou sto kwdika alazw to el-gr kai to
kanw en-us ala pws tha to ritmisw na alazei analoga ti glwsa. dio piges ti
enoeis pws na to kanw? euxaristw

Στις 14 Απριλίου 2016 - 12:40 μ.μ., ο χρήστης dmihos <
notifications@github.com> έγραψε:

**Comment by dmihos** [comment]
Δυστυχώς δε γνωρίζω πως λειτουργεί το plugin. 
Απ'ότι καταλαβαίνω, δεν υποστηρίζει αλλαγή στην παράμετρο lang ανάλογα τη γλώσσα του site σας.
Θα πρέπει, νομίζω, να απευθυνθείτε στην εταιρία που το υποστηρίζει.

**Comment by jasonpoul** [comment]
Xwris plugin pws ensomatwnw sto site to viva payment ta link pou exete pou
leei pws na kaneis redirect de leei pws dimiourgeis
. sto woocoomerce pws to ensomatwnw. Pou paw kai kanw auta pou leei o
odigos. Vazw kodika kapou kai an nai pou.Euxaristw

Στις Παρασκευή, 15 Απριλίου 2016, ο χρήστης dmihos <notifications@github.com>
έγραψε:

**Comment by defilerc** [comment]
Καλησπέρα @jasonpoul ,

Στο παρακάτω URL μπορείτε να βρείτε παραδείγματα κώδικα, σε διάφορες γλώσσες, ανάλογα με το τι θέλετε να χρησιμοποιήσετε:

https://github.com/VivaPayments/API

Σας ευχαριστούμε πολύ για την επικοινωνία
