### ISSUE TITLE
Κάποιες πληρωμές αποτυχαίνουν

### ISSUE THREAD

**Issue by johnchampa** [VivaPayments/API#860]
Καλησπέρα
Έχω κάποιες πληρωμές που αποτυχαίνουν.
Πληρωμή πραγματοποιήθηκε επιτυχώς στις 30/4 μετά από λίγες ημέρες κάποιες πληρωμές απέτυχαν, και μετά είχα επιτυχημένες πληρωμές μέσα στον Μάϊο.
Το κέντρο εξυπηρέτησης της Viva μου είπε ότι ίσως υπάρχει πρόβλημα στην σύνδεση της τράπεζας του πελάτη με το VivaPayments.

**Comment by kostGX** [comment]
@johnchampa καλησπέρα,

Μπορείτε να μου πειτε το merchant id σας https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/

καθως και ημερομηνίες με αποτυχημένες πληρωμές ώστε να κάνουμε investigate?

Γενικά αν έχουμε πρόβλημα σε επίπεδο service, το ανακοινώνουμε εδώ: https://status.vivawallet.com

Διαφορετικά τα rejections προκύπτουν λόγω κάρτας (το κάνει reject η τράπεζα του καρτούχου, για διάφορους λόγους -- μπορεί ο καρτούχος να μην έχει χρήματα, ή η τράπεζά του να έχει κλειδώσει π.χ. τις online πληρωμές μέχρι να ζητήσει ο πελάτης να του επιτραπούν, κ.α.)
