### ISSUE TITLE
cancelling payment within authorisation process - cannot take payment.

### ISSUE THREAD

**Issue by CRYSTALDURHAMUKCIC** [VivaPayments/API#861]
Source name: Crystaldurham UK CIC
Code: 5495
Merchant ID: 71df3791-b00a-42b7-9abd-565c623f07e0
Domain: seebeedeal.co.uk

Hello,
Viva Wallet online checkout via my ecommerce website (seebeedeal.co.uk) is unable to take a payment as it cancels it at the payment processing security check level.
No payment is being taken, nor confirmed.
Here is what and where goes wrong:

1, On seebeedeal.co.uk basket, customer go to checkout.
2, Customer fills out relevant customer details, (logged in user or not)then hits the "proceed to pay with Viva Wallet".
3, Page is redirected to Viva Wallet site, where customer fills out payment information (bank card details, email, phone number etc)
4, Customer hits "pay now"
5, Screen goes to process payment with 3d secure checks with the given bank secure checking screen comes on (confirmation window) -as normal, processing payment, 
6, whilst processing, the screen lands back on my website (seebeedeal.co.uk) showing the basket page, where the checkout process started (loophole) as if nothing has happened.
No payment is taken.

I spoke to Viva Wallet and all is set correctly on my account, enabled and correctly set to receive payments. I am able to take manual POS payments and over the phone as well. They have confirmed that the authorisation is failing at the secured payment processing stage.
They have advised me to contact your support to help and rectify this issue.

I have also spoken to my host site developer ZP Commerce, and they have confirmed all settings to be correct at their (my) end, plus the error occurs on the Viva Wallet authorisation page/process.
  
I have been using Viva Wallet with woocommerce for the last few months, not a single hiccup and nothing has been changed settings-wise. I have moved from wordpress/woocommerce to ZP Commerce, who took over hosting my site and I have not been able to take payments since.
 
Please kindly rectify this issue as a matter of urgency for me.
 
Many thanks

Kind regards,

Laszlo Hornyik
0044(0)775-1672-472

**Comment by matthewrgourd** [comment]
Hi there, sorry for the delayed reply. I've looked into this with our development team and unfortunately we don't currently support ZP Commerce. You can suggest a plugin be developed via ZP Commerce but beyond that I'm afraid Viva Wallet is unable to help further. Best regards, Matt
