### ISSUE TITLE
Virtual terminal

### ISSUE THREAD

**Issue by Happysteps-shop** [VivaPayments/API#863]
Hello!
I can't use virtual terminal in my account because I can not choose the Payment source in the drop-down list. In this case, my store is listed in my account
See print screens by links;
https://yadi.sk/d/YO3DeF8biHOiOg
https://yadi.sk/d/gfSU3-ItnQJoig
What do I need to do so I can use Virtual terminal in my account?

Merchant ID | 2ea037a1-5ff0-432f-a1b0-93cb9d73580e
-- | --

**Comment by kostGX** [comment]
@Happysteps-shop hello, does the source you're looking for have Native Checkout enabled? If yes then it won't show in the Virtual Terminal selection.

Try creating a new source 

Let me know if that solved your issue

**Comment by Happysteps-shop** [comment]
Thank you very much!
Now it's ok!
