### ISSUE TITLE
Some payments failure, problem with telephone filed, "canceled" status in woocommerce

### ISSUE THREAD

**Issue by datarhan** [VivaPayments/API#864]
Hello,

I use woocommerce with your plugin. Some of a payments failure with the unknown issue.  Also  a lot of problems with telephone number (incorrect format or something else) - can I make this field not required? The other issue with payment status in woocommerce admin part, after successful payment the status is "canceled".

As I see in tickets my problems have a lot of your customers, but all the tickets not solved.

Best regards!

**Comment by VivaWalletSupport** [comment]
Hello, phone is required, for your other problem please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by datarhan** [comment]
https://members.vivawallet.com/selfcare/en-gb/security/apiaccess
![Screenshot 2019-05-30 at 11 49 34](https://user-images.githubusercontent.com/17749578/58624806-64a7b900-82d1-11e9-9d13-5bd0d83a2ec1.png)

https://members.vivawallet.com/selfcare/en-gb/sources/paymentsources?sourceTypeId=ae0e2b35-df43-4729-bd6d-a89a86ce3640
<img width="603" alt="Screenshot 2019-05-30 at 11 43 32" src="https://user-images.githubusercontent.com/17749578/58624810-67a2a980-82d1-11e9-9065-545e1f5d91af.png">

https://www.leafboutique.eu/wp-admin/admin.php?page=wc-settings&tab=checkout&section=papaki_vivapayments_gateway
<img width="928" alt="Screenshot 2019-05-30 at 11 46 24" src="https://user-images.githubusercontent.com/17749578/58624820-6a050380-82d1-11e9-9920-fa81ae1d6e24.png">

https://members.vivawallet.com/selfcare/en-gb/sources/paymentsources?sourceTypeId=ae0e2b35-df43-4729-bd6d-a89a86ce3640
<img width="963" alt="Screenshot 2019-05-30 at 11 48 27" src="https://user-images.githubusercontent.com/17749578/58624826-6b363080-82d1-11e9-9c72-e06e276454cf.png">

**Comment by VivaWalletSupport** [comment]
You are using a 3rd party plugin, ask the developer for support or use the supported plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

In case that solved the issue, please close this ticket.
