### ISSUE TITLE
Problem when print Viva orders

### ISSUE THREAD

**Issue by ioannisgz** [VivaPayments/API#865]
Hi. Magento 2.3.1 version. All order payed with viva successful return to Magento as processing status. But we can't print pdf for any of these orders. Only viva orders have this issue. All other orders are printed fine.
Error in exception:

`[2019-05-30 07:48:10] report.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND store_id=3' at line 1, query was: Select value FROM eav_attribute_option_value WHERE option_id= AND store_id=3 [] []`

Please help us....It is critical for printing these orders to our department

**Comment by VivaWalletSupport** [comment]
Hello, could you provide a screesnhot from where you try to print?

**Comment by ioannisgz** [comment]
Sure:
![Untitled](https://user-images.githubusercontent.com/44767880/58624044-fa464700-82d7-11e9-9378-21c60349c06c.jpg)

**Comment by VivaWalletSupport** [comment]
Unfortunately I cannot replicate the issue, after creating the invoice, view invoice and clicking on the Print button the pdf is presented for printing. You might check the MySQL problem you get informed about.

**Comment by ioannisgz** [comment]
Ok....Let me check this please. I am thinking that it has something to do with your module but I will come back

**Comment by ioannisgz** [comment]
Please tell me? you said that you printed after creating the invoice. Can you check if you can print just after order is placed? before invoice.

**Comment by VivaWalletSupport** [comment]
From which location?

**Comment by ioannisgz** [comment]
From admin....inside the order please

**Comment by VivaWalletSupport** [comment]
In case you referer to the location ORDER VIEW / Information, there is no Print button.
http://prntscr.com/nvd2hb

**Comment by ioannisgz** [comment]
Ok.Let me check please!
