### ISSUE TITLE
Redirect after a seccessful payment

### ISSUE THREAD

**Issue by nmalca** [VivaPayments/API#866]
Im using viva payment on 2 websites
1. buycbd.co.il
2. 3cbd.co.uk
I have issues with both, the payment is going through fine as I can see the money in the Viva account but then redirect to nothing (I'll attach screenshot of what I see from both sites)
Also I'll attach the settings as requested.
Im not sure where to get "take screen shot of new payment source for API settings" as requested if you can direct me to where to find it I'll appreciate it.

![](https://dw3i9sxi97owk.cloudfront.net/uploads/stream/2019/05/1849129/24144057/E7C570B1-BA38-4E11-AFF4-AFC427F0CD17.jpeg)
![3cbd settings](https://user-images.githubusercontent.com/51195108/58625877-48088280-82cb-11e9-98e7-56ca72db0714.png)
![buycbd settings](https://user-images.githubusercontent.com/51195108/58626044-b4838180-82cb-11e9-9149-7dc10ffca51d.png)

Also when I moved my site from shopify to WP i created another link not realising its the same account still and when im trying to delet it it says you cant delet source with transaction on it any advise on that? (screenshot attached)
![Screenshot147](https://user-images.githubusercontent.com/51195108/58627406-142f5c00-82cf-11e9-8bbf-5329a696b64e.png)

Also I'll need help with creating a demo account for testing as I dont know how and using real payment and then cancelling it all the time.

**Comment by VivaWalletSupport** [comment]
You are using a 3rd party plugin, ask the developer for support or use the supported plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

In case that solved the issue, please close this ticket.

**Comment by nmalca** [comment]
Yoy havent reply to me in regards to the other issue on the ticket.

**Comment by VivaWalletSupport** [comment]
https://developer.vivawallet.com/getting-started/

**Comment by nmalca** [comment]
Also when I moved my site from shopify to WP i created another link not realising its the same account still and when im trying to delet it it says you cant delet source with transaction on it any advise on that? (screenshot attached)
![](https://user-images.githubusercontent.com/51195108/58627406-142f5c00-82cf-11e9-8bbf-5329a696b64e.png)

**Comment by nmalca** [comment]
Hi.
That doesn't really help as we tried everything.
What is the other option to using the plugin?
Im stuck now for few days and need to go forward.

Also you didnt reply to me in regards to the other issue i put in the same
ticket

Regards
Nissim

**Comment by VivaWalletSupport** [comment]
Regarding the plugin, as mentioned before:
Ask the developer for support or use the supported plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

Regarding account questions I would suggest to open a new issue as I cannot provide assistance on that. Besides that, as the error mentions, you cannot remove the old payment  source because it has transactions, just leave it and create a new payment source to connect your new system...
