### ISSUE TITLE
Viva wallet WooCommerce no giving customers payment option. 

### ISSUE THREAD

**Issue by Wonderleafuk** [VivaPayments/API#867]
The viva wallet is set up and linked to my Woocommerce site and the option to select pay with Viva wallet comes up but when you click the button to pay no card details option comes up for the customer to put their details and and complete the order

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by Wonderleafuk** [comment]
Where is the payment source page? I don't understand what this is?

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 11 59 29](https://user-images.githubusercontent.com/51167802/58629036-32975680-82d3-11e9-9327-bdb3ad80ace5.png)

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 12 03 21](https://user-images.githubusercontent.com/51167802/58629071-48a51700-82d3-11e9-9543-4e7968a2a43b.png)

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 12 01 51](https://user-images.githubusercontent.com/51167802/58629088-55c20600-82d3-11e9-8dc3-c8885d6df8e6.png)

**Comment by VivaWalletSupport** [comment]
You are using a 3rd party plugin, ask the developer for support or use the supported plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

In case that solved the issue, please close this ticket.

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 12 02 18](https://user-images.githubusercontent.com/51167802/58629109-65414f00-82d3-11e9-94f7-39631056efa4.png)

**Comment by Wonderleafuk** [comment]
Ive used the supported plugin and its still not working?

**Comment by VivaWalletSupport** [comment]
Provided screenshots are from a 3rd party plugin, see my previous reply.

**Comment by Wonderleafuk** [comment]
I deleted the 3rd party plugin to install your supported plugin

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 12 24 40](https://user-images.githubusercontent.com/51167802/58630082-3aa4c580-82d6-11e9-8005-dd4aa5d040d9.png)

**Comment by Wonderleafuk** [comment]
This is my only viva plugin now

**Comment by VivaWalletSupport** [comment]
Cofigure as described at https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ and provide the following 4 screenshots in case the problem persists:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 12 43 46](https://user-images.githubusercontent.com/51167802/58630874-a5570080-82d8-11e9-8901-e88efa18482f.png)

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 12 45 34](https://user-images.githubusercontent.com/51167802/58630952-e222f780-82d8-11e9-8da8-51583bc4c0bc.png)

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 12 46 46](https://user-images.githubusercontent.com/51167802/58631004-0f6fa580-82d9-11e9-8176-7a29181dae53.png)

**Comment by Wonderleafuk** [comment]
https://members.vivawallet.com/selfcare/en-gb/sources/paymentsources?sourceTypeId=ae0e2b35-df43-4729-bd6d-a89a86ce3640

**Comment by Wonderleafuk** [comment]
I don't know where to find the payment source settings to take a screen shot

**Comment by VivaWalletSupport** [comment]
Correct the domain name in your payment source (see your last screenshot) to wonderleaf.co.uk as your site does not use www and verify that payment source 9784 has been enabled and is active. Also make sure the Test mode is unchecked in the plugin settings (you did not include that part in your screenshot).

**Comment by Wonderleafuk** [comment]
domain name changed. 9784 is all active and test mode is unchecked but still the same issue.

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 13 43 36](https://user-images.githubusercontent.com/51167802/58633658-fff45a80-82e0-11e9-9e1d-518b99e1fbdd.png)

**Comment by Wonderleafuk** [comment]
All that happens every time is it returns to this screen with no payment option to input card details

**Comment by VivaWalletSupport** [comment]
Please provide a screenshot of the sources listing page.

**Comment by Wonderleafuk** [comment]
Where will find this?

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 14 04 23](https://user-images.githubusercontent.com/51167802/58634696-dee13900-82e3-11e9-8f9f-a98b5fac9b42.png)

**Comment by Wonderleafuk** [comment]
is this it?

**Comment by VivaWalletSupport** [comment]
One page before where all payment sources are listed.

**Comment by Wonderleafuk** [comment]
![Screen Shot 2019-05-30 at 14 12 32](https://user-images.githubusercontent.com/51167802/58635140-0389e080-82e5-11e9-89ca-c9de7c85658b.png)

**Comment by VivaWalletSupport** [comment]
Looks like something is not correct in your WooCommerce setup, could you email admin login to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com for having a look at the problem?

**Comment by Wonderleafuk** [comment]
just admin login to WooCommerce or to Wordpress site also?

**Comment by matthewrgourd** [comment]
This would be your [login](https://www.vivapayments.com/en-gb/signin) to the Viva Wallet banking app, I believe.
