### ISSUE TITLE
The requested URL returned error: 404 Invalid or inactive reseller with id

### ISSUE THREAD

**Issue by devdeepak21** [VivaPayments/API#868]
Hi Team,

We are integrating viva wallet in our website and while doing the same we are getting the error :--

"The requested URL returned error: 404 Invalid or inactive reseller with id".

Kindly help us out on the same.

Thank
Deepak

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by devdeepak21** [comment]
Please find the snapshot

**Comment by devdeepak21** [comment]
- 
![https   members vivawallet com selfcare en gb sources paymentsources sourceTypeId ae0e2b35 df43 4729 bd6d a89a86ce3640](https://user-images.githubusercontent.com/27845205/58785834-f9792200-8603-11e9-9347-e8565eb96bfa.png)

**Comment by devdeepak21** [comment]
![IMG_20190603_132523](https://user-images.githubusercontent.com/27845205/58785900-1ada0e00-8604-11e9-9b4d-5c776dd8249d.jpg)

**Comment by VivaWalletSupport** [comment]
Please use the plugin and the instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/, configure as described. In case the problem persists provide the **4** screenshots **exactly** as described. In case the problem has been solved please close this issue.
