### ISSUE TITLE
Διπλές πληρωμές μέσω του API σε android/ ios εφαρμογή

### ISSUE THREAD

**Issue by kostas-brainbox** [VivaPayments/API#869]
Καλημέρα,
έχουμε παρατηρήσει σε πελάτη μας να πραγματοποιούνται διπλές πληρωμές. 
Το πρόβλημα είναι ότι έχουμε ελέγξει τον κώδικα μας και δεν φαίνεται να υπάρχει κάποιο πρόβλημα και επίσης στα email των διπλών πληρωμών φαίνεται ότι οι πληρωμές έχουν γίνει με ένα δευτερόλεπτο διαφορά(ή και το ίδιο δευτερόλεπτο) και έχουν και το ίδιο order code.
Λογικά αν γινόταν κάποια δεύτερη πληρωμή με το ίδιο order code θα έπρεπε το σύστημα να μην την δέχεται, οπότε υποθέτουμε ότι υπάρχει κάποιο πρόβλημα από την πλευρά της viva.
Για παράδειγμα το order code 7329593250572609 στις 1 Jun 2019, 14:48

Ευχαριστούμε

**Comment by matthewrgourd** [comment]
Hi there, sorry for the lack of reply previously. Please can you let me know if this is still an issue and describe the problem in english if possible? Thanks!

**Comment by kostas-brainbox** [comment]
Hi Matthew,
the problem is that some payments were shown two or three times. The weird part was that they all had the same date and time and also the same order code.
The system should block payments with the same order code after the initial payment.
Example order code 7329593250572609 at 1 Jun 2019, 14:48.

The problem is not frequent now because we have made some changes in our app.
The changes are mainly to prevent calling the viva api multiple times in the same second.

But I think the problem still remains because if you call the viva api multiple times in the same second you will get multiple (real) payments with the same order code.

Thanks

**Comment by matthewrgourd** [comment]
Hi @kostas-brainbox I've raised this with our development team but that's about all I can do I'm afraid. Thanks – Matt
