### ISSUE TITLE
Reccuring payments 

### ISSUE THREAD

**Issue by vasilisf** [VivaPayments/API#87]
Καλημέρα σας, 

Έχουμε υλοποιήσει την διασύνδεση μέσω του viva payments για την υποστήριξη reccurring payments.  
Όταν δημιουργούμε μια παραγγελία από περνάμε την παράμετρο AllowReccuring = true.  
Αυτό πράγματι εμφανίζει ένα checkbox στη σελίδα σας για να αποδεχτεί ο τελικός πελάτης επαναλαμβανόμενες πληρωμές από τον έμπορο. Το πρόβλημα είναι ότι το checkbox αυτό δεν είναι υποχρεωτικό προς τη συμπλήρωση του.  
Θα θέλαμε να ρωτήσουμε τα ακόλουθα:
 
- Μπορεί να γίνει υποχρεωτική η συμλήρωση του εν'λογω checkbox? Ο πελάτης μας πουλάει αποκλειστικά συνδρομές οι οποίες χρεώνονται με τον μήνα οπότε πιστεύουμε ότι είναι απαραίτητο.
- Υπάρχει κάποιος τρόπος η χρέωση μετά τον πρώτο μήνα να γίνεται αυτόματα?
- Υπάρχει τρόπος η χρέωση μετά τον πρώτο μήνα να γίνεται μέσα από την web εφαρμογή που αναπτύσσουμαι και όχι μέσα από το panel της viva payments?
 
Ευχαριστώ πολύ

**Comment by dmihos** [comment]
Καλησπέρα σας

Δυστυχώς δεν παρέχεται η δυνατότητα υποχρεωτικής συμπλήρωσης του checkbox. 
Η μόνη εναλλακτική που μπορώ να σκεφτώ, είναι να ακυρώνετε τη συναλλαγή αυτόματα(https://github.com/VivaPayments/API/wiki/CancelTransaction), αν μετά την πληρωμή δείτε ότι δεν έχει γίνει επιλογή του Checkbox. 

Τις recurring συναλλαγές θα πρέπει εσείς να τις εκτελείτε εσείς όποτε θέλετε, είτε μέσω του panel, είτε μέσα από τη web εφαρμογή σας, με κλήση στο API (https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction)

**Comment by vasilisf** [comment]
Καλησπέρα σας, και χρόνια πολλά. 

Υπάρχει κάποιος τρόπος όπου με βάση το response της viva να αναγνωρίζουμε από τον  κώδικα αν έχει το checkbox επιλεχθεί ?

Επίσης, βλέπω ότι παρέχετε και την CreateRecurringTransaction method. (https://github.com/VivaPayments/API/wiki/CreateRecurringTransaction) 

Αυτή θα την χρησιμοποιήσω για να χρεώνω τον πελάτη μόνο σε περίπτωση που έχει επιλέξει το checkbox ?

Ευχαριστώ πολύ

**Comment by dmihos** [comment]
Η GetTransactions επιστρέφει το Payment.RecurringSupport, που δηλώνει αυτό ακριβώς (αν ο χρήστης επέλεξε το checkbox).
Η κλήση για την εκτέλεση του recurring payment είναι αυτή που αναφέρετε (CreateRecurringTransaction)
