### ISSUE TITLE
Payments canceled

### ISSUE THREAD

**Issue by JOYFASHIONHOUSE** [VivaPayments/API#870]
Good morning,

I am having many canceled payments in woocommerce, and I want to make sure that 100% of them, are because of insuffienct funds of the customer or there is another cancelation reason.
I am attaching screenshot requested in related issues.
![viva1](https://user-images.githubusercontent.com/51203145/58787157-e3626600-85f1-11e9-9a48-5ee641e5d0ca.jpg)
![viva2](https://user-images.githubusercontent.com/51203145/58787158-e3626600-85f1-11e9-9c73-e9b42f876130.jpg)
![viva3](https://user-images.githubusercontent.com/51203145/58787160-e3626600-85f1-11e9-816d-58c26d95af86.jpg)
![viva4](https://user-images.githubusercontent.com/51203145/58787162-e3626600-85f1-11e9-8147-2141711b5956.jpg)

**Comment by matthewrgourd** [comment]
Hi there, are you based in Greece? Please call us on (+30) 211 7604 000 to discuss the issue. Thanks!
