### ISSUE TITLE
OAuth2 token request returns "invalid_client"

### ISSUE THREAD

**Issue by sdagkas** [VivaPayments/API#871]
While calling "https://accounts.vivapayments.com/connect/" for token generation using Basic Authentication with MerchantId:ApiKey, the response contains the error "invalid_client". I've double checked and the MerchantId, ApiKey are correct. Am I missing something here?

**Comment by matthewrgourd** [comment]
Hi there, could you let me know what it is you're trying to do, e.g. which APIs you're attempting to access?

**Comment by sdagkas** [comment]
Hi, I'm trying to implement redirection with ASP.NET. Following the guide on "https://developer.vivawallet.com/online-checkouts/redirect-checkout/", as step 1 I see "Create Order" which uses Identity Server authentication so following the steps on "https://developer.vivawallet.com/authentication-methods/#identity-server-oauth2" I try to get an authentication token.

**Comment by matthewrgourd** [comment]
Hi there, after looking into this in fact the section of the documentation that refers to Identity Server authentication is wrong. It should state that basic authentication is needed and link to https://developer.vivawallet.com/authentication-methods/#basic-authentication

We will update the relevant pages as soon as possible, in the meantime please accept our apologies for this error! Note that the same thing applies to retrieving transactions referred to here https://developer.vivawallet.com/api-reference-guide/payment-api/retrieve-transactions/

**Comment by sdagkas** [comment]
Ok, thanks!
