### ISSUE TITLE
Payment page Vivawallet in French

### ISSUE THREAD

**Issue by Romano67** [VivaPayments/API#872]
Hello,

I would like to know if it is possible to translate the payment page into French.
I can provide you with the French translation so that you can integrate it.
This is very important for my clients.

Thank you for your reply.

![payment-vivawallet](https://user-images.githubusercontent.com/51318032/58789993-ba40d600-85ef-11e9-9756-ee1941f0db82.png)

**Comment by matthewrgourd** [comment]
Hi there, I'm afraid a French version of the payment screen isn't something we support at present, but perhaps it will be in the future. I'll make a note of your request. FYI, we have our own translation agency for this purpose.
