### ISSUE TITLE
Can't access demo.vivapayments.com

### ISSUE THREAD

**Issue by sdagkas** [VivaPayments/API#873]
After successful login I am presented with the "Sign up" form where the "Sign Up" button does not work.

![Screenshot_2019-06-03 Sign up - Viva Wallet](https://user-images.githubusercontent.com/754098/58790044-3dfec080-85f8-11e9-9544-0ec0398f1c4c.png)

**Comment by ngoun** [comment]
For Sign-in [https://demo.vivapayments.com/en-gb/signin](https://demo.vivapayments.com/en-gb/signin) 
For me works fine.
