### ISSUE TITLE
Issue with incoming website payments

### ISSUE THREAD

**Issue by rdtrade** [VivaPayments/API#875]
My customers are all receiving the same error when ever they try to make the payment:
------------------
"This card does not support electronic transactions. In order to complete this payment please use a different card, or add funds to your Viva Wallet."
-----------------

I also had an email from the risk department which told me that I should stop taking Virtual POS payments but I was allowed to accept payments through the website which I am now doing but this error is happening and I have  many customers trying to make payment as we speak.

Merchant ID: 34808276-11fb-46b6-a624-c5cc78c7bf25

**Comment by rdtrade** [comment]
That issue has been resolved but now the webhook is not working when I try create it in viva wallet.

I found some documentation which shows what the payment redirection should be, but it is just not being accepted in vivawallet therefore my transactions are not changing their order status

It is a woocommerce website - https://prosportshop.co.uk/?wc-api=wc_gateway_viva

**Comment by rdtrade** [comment]
I have tried to create this webhook in viva wallet but it is not being accepted: https://prosportshop.co.uk/?wc-api=wc_gateway_viva

Currently my orders statuses are not updating after purchase. I found documentation online which told me that should be the url for a webhook with viva wallet if you use woocommerce

**Comment by matthewrgourd** [comment]
Hi @rdtrade I believe that webhook is for the [unofficial WooCommerce Viva Wallet plugin](https://github.com/somewherewarm/woocommerce-gateway-viva#3-set-up-viva-wallet-webhooks). If you [install our own plugin](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) the correct webhook is `http(s)://(www.)your_domain.com/index.php?wc-api=wc_vivawallet&vivawallet=webhook`
