### ISSUE TITLE
I dont receive the payment in my site so the order change status as cancel 

### ISSUE THREAD

**Issue by Aikaterini8** [VivaPayments/API#876]

**Comment by Aikaterini8** [comment]
Hello the few last week i face the following error.
My customers pay the orders through Viva , i receive normally the payment from Viva alert , but this information doesnt return to my site so the order stay for few minutes in status " waitting for payment" and finally the order cancelled .

Could you please help me ?

Thank you 

Br

**Comment by VivaWalletSupport** [comment]
Hello, please provide some more details with what is used (platform/plugin).

**Comment by Aikaterini8** [comment]
Hello ,
I am using woocommerce , with WordPress 5.0.4.The pluging is the  Viva Payments - Viva Wallet WooCommerce Payment Gateway version 1.3.2

Thank you 
    Στις Τετάρτη, 5 Ιουνίου 2019, 12:59:17 μ.μ. EEST, ο χρήστης Tom van der Veer <notifications@github.com> έγραψε:  
 
 
Hello, please provide some more details with what is used (platform/plugin).

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by Aikaterini8** [comment]
Hello ,
Please  find attach the settings :
Thank you 
    Στις Παρασκευή, 7 Ιουνίου 2019, 9:25:31 π.μ. EEST, ο χρήστης Tom van der Veer <notifications@github.com> έγραψε:  
 
 
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by VivaWalletSupport** [comment]
Please post the screenshots at github as they do not show.

**Comment by Aikaterini8** [comment]
![ScreenHunter_10820 Jun  10 23 39](https://user-images.githubusercontent.com/49983345/59285972-8f9def80-8c77-11e9-89da-3196b08dd6fc.jpg)
![ScreenHunter_10821 Jun  10 23 39](https://user-images.githubusercontent.com/49983345/59285974-8f9def80-8c77-11e9-9099-a5dc8ac15bb9.jpg)
![ScreenHunter_10822 Jun  10 23 41](https://user-images.githubusercontent.com/49983345/59285975-8f9def80-8c77-11e9-8f24-3ceb019acb0d.jpg)
![ScreenHunter_10823 Jun  10 23 41](https://user-images.githubusercontent.com/49983345/59285976-90368600-8c77-11e9-92a3-6b33bd65aaad.jpg)

**Comment by VivaWalletSupport** [comment]
Use the supported plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ and close this issue when solved.

**Comment by Aikaterini8** [comment]
Hello Matthewrgroud ,

I Follow the instruction of the above link , but i still face issues with the payments . Could you please helo me ?

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by Aikaterini8** [comment]
Hello i download the plugin from your instruction and i enable the viva with  version 3.5.7 is that the correct one ?
![ScreenHunter_10985 Jun  25 09 10](https://user-images.githubusercontent.com/49983345/60073498-5494c500-9729-11e9-8991-c7519b938556.jpg)

**Comment by VivaWalletSupport** [comment]
Yes it is.

**Comment by Aikaterini8** [comment]
Good , so i send you the nessesary photos
![ScreenHunter_10984 Jun  25 09 09](https://user-images.githubusercontent.com/49983345/60074987-f538b400-972c-11e9-88ad-52f343f6fa3b.jpg)
![image](https://user-images.githubusercontent.com/49983345/60075078-2a450680-972d-11e9-97be-c7abbdea7ece.png)

**Comment by Aikaterini8** [comment]
![image](https://user-images.githubusercontent.com/49983345/60075261-9293e800-972d-11e9-8511-7cf884d58db7.png)
![image](https://user-images.githubusercontent.com/49983345/60075336-b9521e80-972d-11e9-918e-19fb80e64e5e.png)

**Comment by Aikaterini8** [comment]
Please tell me if something missing 

Thank you

**Comment by VivaWalletSupport** [comment]
Missing is the details of the payment source (2526), also you would have to specify this source code in the plugin settings and please change your API Key as it should remain secret.

**Comment by Aikaterini8** [comment]
Hello sorry that i am asking again .

is the below the correct configuration.?

![image](https://user-images.githubusercontent.com/49983345/60091975-7d7b8100-974e-11e9-8b43-487d9c7ff20c.png)

**Comment by VivaWalletSupport** [comment]
Regarding the plugin configuration ,yes.

**Comment by Aikaterini8** [comment]
So you write 2 thinks :
1) Missing is the details of the payment source (2526) -> could you please give me more info ?what ihave to do and where ?

2)also you would have to specify this source code in the plugin settings . This is ok 

Thank you

**Comment by VivaWalletSupport** [comment]
For a screenshot of the payment source settings, edit the payment source and make a screenshot:
https://user-images.githubusercontent.com/49983345/60075336-b9521e80-972d-11e9-918e-19fb80e64e5e.png

**Comment by Aikaterini8** [comment]
![image](https://user-images.githubusercontent.com/49983345/60214282-da218d80-986d-11e9-9133-fb30e1e7fde7.png)

![image](https://user-images.githubusercontent.com/49983345/60214300-e1489b80-986d-11e9-9e9f-9d0d37f1380d.png)

![image](https://user-images.githubusercontent.com/49983345/60214319-e9a0d680-986d-11e9-978d-5fa06b9b137f.png)

**Comment by VivaWalletSupport** [comment]
Change the protocal to https in the payment source settings.

**Comment by Aikaterini8** [comment]
![image](https://user-images.githubusercontent.com/49983345/60240787-7ffae980-98ba-11e9-8e4e-7186a38ec8fa.png)

**Comment by VivaWalletSupport** [comment]
Correct, does the order status now gets updated correctly after a transaction?
