### ISSUE TITLE
Is Preauthorisation in Simple Check-Out and or Payment Notifications Possible ?

### ISSUE THREAD

**Issue by CatalinVivaWalletRomania** [VivaPayments/API#877]
My client - a high end dental clinic in Romania-   is developing / personalizing a new booking platform 
I read online somewhere the preauthorisation can be integrated with Native Checkout Integration ?
Anyway
He is asking if we can integrate Preauthorised Transactions online ( very important for him):
-	In Payment Notifications
-	With Simple  Checkout / Payment Buttons
Any other suggestions / recommendations you may have will be more then welcome

**Comment by kostGX** [comment]
Hello @CatalinVivaWalletRomania,

Preauth with payment notification is supported please see screenshot on how to trigger them via API:
![image](https://user-images.githubusercontent.com/3908736/58958052-e9934680-8799-11e9-886f-7069f038576a.png)

Native and Redirect checkout also support this (the same way we create an order in the above example, relevant parameters need to be passed).

Simple checkout:
Yes it's supported by passing the data-vp-preauth flag. See here
https://developer.vivawallet.com/online-checkouts/simple-checkout/ 

We don't support payment buttons for outside of Greece.

Let me know if you need further help.

**Comment by CatalinVivaWalletRomania** [comment]
Thank you x 1000!
Will get in touch if other questions are bought up by customer
Sincerely,

Catalin Trandafir
Sales Executive - E-commerce, POS & MPOS Payment Acceptance Solutions
M: (+40) 799 000 367     *  ctrandafir@vivawallet.com<mailto:ctrandafir@vivawallet.com>  *  vivawallet.com

**Comment by CatalinVivaWalletRomania** [comment]
Thank you x 1000!
Will get in touch if other questions are bought up by client
