### ISSUE TITLE
Error 422: PaymentsNoBinRouteFound

### ISSUE THREAD

**Issue by odysseas12** [VivaPayments/API#878]
One year ago I had this issue. No reply was given.
Today I have this issue again this time on the demo env.
(
            [Emv] => 
            [Amount] => 
            [StatusId] => E
            [CurrencyCode] => 
            [TransactionId] => 
            [ReferenceNumber] => 
            [AuthorizationId] => 
            [RetrievalReferenceNumber] => 
            [ErrorCode] => 422
            [ErrorText] => PaymentsNoBinRouteFound
            [TimeStamp] => 2019-06-03T18:54:03.8753642+03:00
            [CorrelationId] => 
            [EventId] => 2054
            [Success] => 
        )

Please reply and advice on this issue.

**Comment by dpnevmatikos** [comment]
Hello @odysseas12 ,
There was a configuration issue with your account. Could you please try again, and let me know
if it now works as it should ?

thanks

**Comment by odysseas12** [comment]
Hi Dimitris,
Now Im getting transaction failled using 4111 1111 1111 1111 as a credit card

(
    [error] => 1
    [data] => stdClass Object
        (
            [Emv] => 
            [Amount] => 87
            [StatusId] => E
            [CurrencyCode] => 978
            [TransactionId] => 11146038-d66c-4b16-9b75-2563b4ccf5d8
            [ReferenceNumber] => 89222
            [AuthorizationId] => 
            [RetrievalReferenceNumber] => 
            [ErrorCode] => 502
            [ErrorText] => Transaction failed
            [TimeStamp] => 2019-06-04T13:48:31.8735278+03:00
            [CorrelationId] => 
            [EventId] => 307
            [Success] => 
        )

)

**Comment by dpnevmatikos** [comment]
Hi again @odysseas12 
could you please try again ?
I've created a new source under your account named `test-web`.
Can you please use it when posting to `/transactions` to complete the transaction ?

**Comment by odysseas12** [comment]
The payment source I always use "2232" works now.
Dont know what changed but thanks.
