### ISSUE TITLE
Χρήση της υπηρεσίας για donate

### ISSUE THREAD

**Issue by pasakk** [VivaPayments/API#88]
Στο site μας  (www.safem-hellas.org )  θέλουμε να έχουμε την δυνατότητα του donate.

Να μπορεί ο χρήστης να κάνει clik στο κουμπί του viva και να γίνετε προώθηση  στην  σελίδα σας ώστε να μπορεί να συμπληρώνει το ποσό που θέλει να κάνει donate και στην συνέχει τον τρόπο πληρωμής (με κάρτα στην προκειμένη περίπτωση ).  Και στην συνέχεια να γυρίζει στην δικιά μας σελίδα.

Αυτό το μοντέλο μπορεί να πραγματοποιηθεί μέσω του viva;
εάν ναι θα παρακαλούσα μία βοήθεια θα ήταν σωτήρια.

To site μας είναι το www.safem-hellas.org .

Να σας επισημάνω ότι είμαστε τεχνικοί.

Ευχαριστούμε  πολύ.

**Comment by dmihos** [comment]
Καλησπέρα σας
Αυτό που περιγράφετε είναι ένα τυπικό σενάριο [Redirect Checkout](https://github.com/VivaPayments/API/wiki/Redirect-Checkout) με κωδικούς ανοιχτού ποσού ([Optional Parameters](https://github.com/VivaPayments/API/wiki/Optional-Parameters) > DisableExactAmount). 
Μπορείτε να μελετήσετε τον οδηγό που περιγράφει τα 3 απλά βήματα του integration.
Για όποια απορία, είμαστε στη διάθεσή σας

**Comment by pasakk** [comment]
Ευχαριστώ για την άμεση απάντηση το πρόβλημα είναι ότι σαν πλατφόρμα κάνουμε χρήση την www.yola.com που δυστυχώς δεν μας επιτρέπει να κάνουμε χρήση php αλλά μόνο html. Η δημιουργία ενός κουμπιού για redirection θα ήταν τέλεια γιατί είναι μόνο html  αλλά δεν μας επιτρέπει το ανοικτό ποσό. Υπάρχει η δυνατότητά να περάσω παράμετρο στον κώδικα της δημιουργίας του κουμπιού ώστε να έχω φόρμα με ανοικτό ποσό;

**Comment by dmihos** [comment]
Δυστυχώς δεν υπάρχει αυτή η δυνατότητα
