### ISSUE TITLE
Viva Wallet Error

### ISSUE THREAD

**Issue by BradGrantBaker** [VivaPayments/API#880]
I have just added Viva Wallet as a payment option to my website. I have tried a few test transactions and when redirected to the Viva Wallet website I am confronted with "Error - Store not found"

Any clue as to why this would be?

Thanks

Brad

**Comment by BradGrantBaker** [comment]
I have followed the plugin guide step by step. All steps have been completed.
It is set to redirect, test mode is turned off.

I have checked and double checked that the  merchant ID and store token are correct.

At this point I'm stuck waiting to launch my site.

Any help would be much appreciated. 

Thanks

**Comment by VivaWalletSupport** [comment]
Please provide some more info on what is used (platform/plugin).

**Comment by BradGrantBaker** [comment]
Hi sorry, I'm using Shopify.

Thanks

Brad

**Comment by dmihos** [comment]
Hi @BradGrantBaker 
Is it this guide you have followed?
https://developer.vivawallet.com/e-commerce-plugins/shopify/

**Comment by BradGrantBaker** [comment]
Hi, the issue has been resolved now.

Thanks for you Help,.

Brad
