### ISSUE TITLE
Viva Payments/Wallet payment gateway refused to accept payment

### ISSUE THREAD

**Issue by IBL2019** [VivaPayments/API#881]
Customer has advised they tried to purchase a product from my shopify website & payemnt was refused by Viva Payments/Wallets payment gateway.  Please advise ASAP.

**Comment by matthewrgourd** [comment]
Hi there, sorry for the delayed response. Has anyone else reported issues? Could this be a problem with their card? Please provide further details or call support on + 44 (20) 37347770. Thanks!

**Comment by IBL2019** [comment]
Hi Matthew,

Yes the issue was reported by numerous parties, the whole vivapayments wallet was down with no way to receive payments for some time. The issue was so bad i tried to make a purchase myself to no avail.

Is there a limit/restriction on payment limits as some transactions will be high value for wholesale customers.

Can we please have support with this??

Many thanks

O Lawrence

Sent from my iPhone

On 19 Jun 2019, at 12:03, matthewrgourd <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there, sorry for the delayed response. Has anyone else reported issues? Could this be a problem with their card? Please provide further details or call support on + 44 (20) 37347770. Thanks!

**Comment by matthewrgourd** [comment]
Hi there,

Sorry for the delayed response. We have since looked into the issue and fixed the problem. I'm advised this shouldn't happen at all again in the future.

Thanks,

Matt
