### ISSUE TITLE
Payment Pending magento 2.2.0

### ISSUE THREAD

**Issue by alexbk31** [VivaPayments/API#882]
Hello. I have set up your module and working with my viva wallet account fine. I can receive the payments and return to my store after successful transaction. The issue is that all orders coming from viva are having status pending payment which is wrong. You can work with these orders after. For example you can't put the order on hold. The correct status should be processing. I saw in module settings that you have an option for choosing the status of the order after payment. But in there the only option is pending payment. Can you explain please what is going on? 

magento 2.2.0

**Comment by alexbk31** [comment]
also when a transaction fails in viva wallet customer is redirect back to magento and errors saying payment failed/order cancelled is there any way to have it so they can try payment again on viva or have them redirected back to payment failed with out cancelling the basket so they can try alternative payment method

**Comment by VivaWalletSupport** [comment]
Hello, for the pending payment problem, did you use the latest release?

**Comment by alexbk31** [comment]
Hi yeah ive installed the new module and its working now but i have ran in to a new issue 
if a customer card declines it diverts them back to the website and says Error: Your transaction failed or has been cancelled!

is it possible to set so it dont return them to website and they can try again on viva wallet with a different card 
or
 have them directed back without it canceling order so they can try alternative payment method

**Comment by VivaWalletSupport** [comment]
Hello, the functionality might be added in a future release.
