### ISSUE TITLE
Tokenize card

### ISSUE THREAD

**Issue by andreasagap** [VivaPayments/API#883]
I try to get the chargeToken and go to step 5 (Execute the payment). However, I have a 401 error. My credentials are Basic Authentication, because the `https://demo-accounts.vivapayments.com/connect/token` doesn't work.
![Screenshot 2019-06-05 at 09 06 11](https://user-images.githubusercontent.com/23177011/58933839-357dc580-8771-11e9-8879-301daf5c9e1c.png)

**Comment by dellitsa** [comment]
I am having the same issue. I want to use the methods described in the [Card tokenization](https://developer.vivawallet.com/api-reference-guide/payment-api/tokenize-card/) and I get stuck at Step 1. I am using the Basic Authentication request and I get **401 Unauthorized** response. How can I get the Identity Server credentials? I have already sent an email at support@vivawallet.com seven days ago and I didn't get any response.

**Comment by andreasagap** [comment]
@matthewrgourd @dpnevmatikos Please let us know if you have an update.

**Comment by Stratubas** [comment]
@matthewrgourd @dpnevmatikos Any progress? I'm getting 401 too, we've asked for Identity Server credentials weeks ago, still waiting.

**Comment by dpnevmatikos** [comment]
Hello everyone, 
@Stratubas @dellitsa apologies for the late reply.
Please try again to retrieve an access token using the following set of credentials:
```
ClientId: generic_acquiring_client.apps.vivapayments.com
Secret: generic_acquiring_client
```

**Comment by andreasagap** [comment]
@dpnevmatikos what exactly is this cliendID (generic_acquiring_client.apps.vivapayments.com) ?

> Hello everyone,
> @Stratubas @dellitsa apologies for the late reply.
> Please try again to retrieve an access token using the following set of credentials:
> 
> ```
> ClientId: generic_acquiring_client.apps.vivapayments.com
> Secret: generic_acquiring_client
> ```

**Comment by dpnevmatikos** [comment]
@andreasagap it's just a username and password to use with the [token endpoint](http://docs.identityserver.io/en/latest/endpoints/token.html#token-endpoint)

**Comment by andreasagap** [comment]
@Stratubas @dellitsa  Check this picture, maybe it helps you.
![Screenshot 2019-06-10 at 11 19 05](https://user-images.githubusercontent.com/23177011/59182114-95a9a880-8b71-11e9-92f4-ab67a9c20ed0.png)

**Comment by andreasagap** [comment]
@dpnevmatikos Thank you for the help. Everything is working now.

**Comment by Stratubas** [comment]
@dpnevmatikos Nice! Should we use these credentials in production though?
