### ISSUE TITLE
API is not working/ πρόβλημα με πληρωμή στο eshop viva wallet woocommerce

### ISSUE THREAD

**Issue by petross9** [VivaPayments/API#884]
Ευχαριστούμε - η παραγγελία αναμένει πληρωμή. Θα μεταφερθείτε αυτόματα στη Vivapayments για να πραγματοποιήσετε πληρωμή.

Λάθος στοιχεία εμπόρου ή το API δεν λειτουργεί.

Και κάπως ετσι η πληρωμή δεν πραγματοποιείτε.

εχει κανείς το ίδιο πρόβλημα?

**Comment by VivaWalletSupport** [comment]
Hello, try the plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/
