### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by SteveMersereau** [VivaPayments/API#885]
I'm using vivawallet with WooCommerce for WordPress. 

Your documentation says that I need to copy a code from the New payment source dialog box in Vivawallet's control panel into  the VivaWallet source code box in WooCommerce's payments section.

My issue is that there is no code in the New payment source dialog box in Vivawallet's control panel.

Help appreciated!

![image](https://user-images.githubusercontent.com/10234034/58954995-a2558780-8792-11e9-8e83-03555ea7b0ee.png)

![image](https://user-images.githubusercontent.com/10234034/58955013-abdeef80-8792-11e9-8024-8e040beb93ce.png)

**Comment by matthewrgourd** [comment]
Hi @SteveMersereau, sorry to hear you've been having problems! I tried to recreate the isssue in both demo and live but a code is generated in both cases after I click on the **Add Website/App** button on the [Payment Sources](https://members.vivawallet.com/selfcare/en-gb/sources/paymentsources) page. If possible, could you clarify further what is happening / not happening for you? Thanks, Matt

**Comment by SteveMersereau** [comment]
Hi Matthew! Thanks for getting back. I'm not sure I can clarify any further. The code box is currently showing "Defatult" instead of a four digit number. 

![grab](https://user-images.githubusercontent.com/10234034/58958791-93270780-879b-11e9-9d2c-13fcb2af5e63.jpg)

**Comment by matthewrgourd** [comment]
You simply need to create a new payment source rather than editing the existing default one. Let me know if this helps!

**Comment by SteveMersereau** [comment]
That's perfect, thanks!
