### ISSUE TITLE
Page redirect on successful transaction

### ISSUE THREAD

**Issue by SteveMersereau** [VivaPayments/API#886]
I'm using vivawallet with WooCommerce for WordPress and setting up for first time; using redirection integration.

When a payment is made, the user is returned to mydomain.com/?wc-api=wc_gateway_viva&result=success and the payment has gone through successfully.  

The page displayed is a white screen of death with -1 appearing in top left of the screen.

I need to redirect user from mydomain.com/?wc-api=wc_gateway_viva&result=success  to the mydomain.com//transaction-success/

Please advise.

**Comment by matthewrgourd** [comment]
Hi @SteveMersereau I believe you're referring to the unofficial Viva Wallet WooCommerce plugin here: https://github.com/somewherewarm/woocommerce-gateway-viva The official download together with instructions is on this page: https://developer.vivawallet.com/e-commerce-plugins/woocommerce Hope this helps!

**Comment by SteveMersereau** [comment]
I'm taking over from a previous developer; I didn't originally install. But the plugin we're using is 

WooCommerce Vivawallet Gateway | Extends WooCommerce with the Vivawallet gateway.Version 3.5.4 the author is vivawallet.com. Is that the unofficial one?

**Comment by matthewrgourd** [comment]
Thanks for the clarification. That's definitely ours but I think you need to install 3.5.7 the latest version the source code of which is  located here: https://github.com/VivaPayments/API/blob/master/Plugins/wordpress/vivawallet-for-woocommerce/wc-vivawallet.php

However, it might be easier to start a fresh installation downloading the ZIP file directly from our [instruction page](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/) on the Viva Wallet Developer Portal as the guide on GitHub has been deprecated.
