### ISSUE TITLE
MAGENTO PROBLEM 

### ISSUE THREAD

**Issue by giannaki1981** [VivaPayments/API#887]
Καλησπέρα σας ,

μπορείτε να με βοηθήσετε με το παρακάτω  πρόβλημα ? καναμε το update
στο magento στην έκδοση Magento ver. 1.9.4.1 και όταν ένας πελάτης
πληρώνει και πηγαίνει η δικη σας επιβεβαίωση άλλα δεν πηγαινει
αντιγραφο παραγγελιας απο το σαιτ o develop μου ειπε να σας στειλω το
παρακατω αν μπορείτε να το δείτε και να μας βοηθησετε τι πρεπει να
αλλαξω

we have one issue, can you ask vivawallet support ,I have tried but
not found support area to ask them.
please ask them if you can:As below:
Payment with vivawallet after successfull payment : it should be go to this url:
https://titiluluboutique.com/el/vivawallet/hpay/hpok/
as we have given here: http://prntscr.com/nyv64x
but order is not going to this url ,as per guide of payment :
https://developer.vivawallet.com/e-commerce-plugins/magento1.x/
So,
if order will be go here https://titiluluboutique.com/el/vivawallet/hpay/hpok/
after successfull payment then , magento will also able to sent all
other data like
transaction all that.that will show in magento admin area.

Please check
Thanks

**Comment by VivaWalletSupport** [comment]
Hello, to what (wrong) URL are you taken after a success transaction? Setup the plugin to work with the demo mode first in order to test and to see what is wrong.
