### ISSUE TITLE
Opencart 3 module  Fatal error: Unable to create order code (Negative or zero amount, merchant xxxxxx

### ISSUE THREAD

**Issue by chrismfz** [VivaPayments/API#888]
Hello people. 

Opencart 3.0.2.0 setup, working smooth, just one day I've seen multiple errors like this:

[08-Jun-2019 09:33:18 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to create order code (Negative or zero amount, merchant XXXXXXX-XXXX-XXXX-XXXX-XXXXX                                                      XXXXXX))' in /home/user/public_html/catalog/controller/extension/payment/vivawallet.php:139

Stack trace:
#0 [internal function]: ControllerExtensionPaymentVivawallet->index(Array)
#1 /home/user/storage/modification/system/engine/action.php(79): call_user_func_array(Array, Array)
#2 /home/user/storage/modification/system/engine/loader.php(48): Action->execute(Object(Registry), Array)
#3 /home/user/public_html/catalog/controller/extension/d_quickcheckout/payment.php(57): Loader->controller('extension/payme...')
#4 /home/user/public_html/catalog/controller/extension/d_quickcheckout/payment.php(20): ControllerExtensionDQuickcheckoutPayment->prepare(Array)
#5 [internal function]: ControllerExtensionDQuickcheckoutPayment->index(Array)
#6 /home/user/storage/modification/system/engine/action.php(79): call_user_func_array(Array, Array)
#7 /home/user/stora in /home/user/public_html/catalog/controller/extension/payment/vivawallet.php on line 139

Disabling plugin and Enabling again it works. 
Any thoughts ?

PHP Version 5.6.40
--

disable_functions 

show_source, system, shell_exec, passthru, exec, proc_open, mail
--

--

**Comment by VivaWalletSupport** [comment]
Hello, you might try using OpenCart's default checkout to exclude the problem is caused by the used checkout.

**Comment by matthewrgourd** [comment]
As you've not got back to us, we assume this issue is fixed. Please let us know if any further queries and we'd be happy to help. Thanks!

**Comment by dippetas** [comment]
I have the exact same issue Fatal error: Uncaught exception 'Exception' with message 'Unable to create order code (Negative or zero amount, merchant ea2667f4-96cf-4455-949e-37232a37cbdf)

**Comment by kanenas** [comment]
@dippetas you may use the solution suggested here #2484
