### ISSUE TITLE
Opencart 3 module: Vivapayments not redirecting back to merchant site after successful or failed payment.

### ISSUE THREAD

**Issue by georgekaf** [VivaPayments/API#889]
Vivapayments not redirecting back to merchant site after successful or failed payment in both demo and live environments.

After completing a transaction (failed or successful) we are redirected to a URL similar to 

http://demo.vivapayments.com/web/checkout/result?t=46f7c40c-f6ec-488b-9707-f36774e806c9&s=8924620896672606&lang=el-GR&eventId=0&eci=2

Please advise.

Online payment app/website has been created and module has been activated.

**Comment by VivaWalletSupport** [comment]
In case you are using the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/opencart3/ verify that article 3/4/5 have been implemented correctly.

**Comment by georgekaf** [comment]
The source code wasn't filled. That resolved the redirection issue.
