### ISSUE TITLE
Woocommerce plugin 

### ISSUE THREAD

**Issue by pcnetlab** [VivaPayments/API#89]
Καλησπέρα σας,

Ποιο woocommerce plugin προτείνετε για την καλύτερη λειτουργια του vivapayment σε ενα eshop ως τρόπο πληρωμής?

Ευχαριστώ.

**Comment by defilerc** [comment]
Καλησπέρα @pcnetlab ,

Τα plugins τα οποία έχουν αναπτυχθεί για το woocommerce plugin, είναι από ανεξάρτητους developers και δεν παρέχεται κάποια επίσημη υποστήριξη από τη Viva.

Για τυχόν πληροφορίες/απορίες, θα πρέπει να επικοινωνήσετε με τον εκάστοτε developer του plugin.

Ευχαριστούμε πολύ για την επικοινωνία
