### ISSUE TITLE
WP / Woocommerce return issue

### ISSUE THREAD

**Issue by SteveMersereau** [VivaPayments/API#890]
Using WP / Woocommerce and all working great except for one thing.

The orders are being marked in Woo as Complete. The client is saying that the order is meant to go to "processing" instead of "complete" so that it can be picked up by the fulfilment company. Can you advise please? 
 
Thanks!

**Comment by SteveMersereau** [comment]
By the way, I'm using Redirection Integration...

**Comment by VivaWalletSupport** [comment]
In case the supported plugin is used from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ you could set the needed order status in the plugin settings (see step 3).
