### ISSUE TITLE
VivaWallet Integration OnlineShop

### ISSUE THREAD

**Issue by Julesdr** [VivaPayments/API#891]
Hello,

I try to integrate vivawallet through my wordpress shop woocommerce.

I followed the whole tutorial, but now when I try to test if it works, when I click on pay with vivawallet, I have this message that I join you in screen.
![vivawallet prob1](https://user-images.githubusercontent.com/51660601/59205521-63b13a00-8ba3-11e9-8fcb-1b088790add1.png)

Do you know where it comes from?

**Comment by VivaWalletSupport** [comment]
Hello, as mentioned in the shown error the used Euro currency is not valid for your Viva account.

**Comment by Julesdr** [comment]
Hello,

thanks for your quick return!

The thing is that I have already seen a site using viva wallet, let me pay in euros.

From there I would like to be able to do the same.

Do you know how can I unlock payment acceptance in euros?

Excellent day. :)

**Comment by VivaWalletSupport** [comment]
You would have to setup a Viva account in a Euro currency country.

**Comment by Julesdr** [comment]
The thing is my company is registered in UK, country that uses "Pound currency"

Do you think I can setup an account in Euro even if my company is registered in UK?

Best regards and thanks again for your quick return.

**Comment by VivaWalletSupport** [comment]
That would not be possible, you would need a company that is registered in a Euro country.
In case that solved the problem, please close this issue.
