### ISSUE TITLE
Error code= 502, Status Id = E

### ISSUE THREAD

**Issue by DJ124** [VivaPayments/API#893]
We have integrated Viva Wallet with our app. After integration it is working fine till yet. But from few days it is not working correctly. 
It is not making transaction. Yes, API for card token generation is working fine. But while making payment through that card it is failed without any proper reason.

It gives Error Code : 502 and text as "Transaction failed".

It is really very very confusing that what is the exact issue. Before few days while this happens, it was working fine. But sometimes it was failed on every cards. 

Please help ASAP, so that we can fix that if this from our side.

**Comment by matthewrgourd** [comment]
Hi there, I'm checking with our development team. I'll get back to you when they've had a chance to look into this further. Could I just ask, what type of checkout have you implemented? Could you check our [developer portal](https://developer.vivawallet.com/) and let us know what sections are most relevant? Thanks!

**Comment by matthewrgourd** [comment]
Hi @DJ124 , could you tell me whether this error is still occurring? I've checked with a colleague and apparently this can happen from time to time when using the demo environment but shouldn't happen in production.

**Comment by TwinkleMali** [comment]
@matthewrgourd ,

Sorry for late reply, But we are still facing that issue in production. Our customers are trying to pay using their different credit cards. but non of them are working for them.
Would you please provide your email address so we can share some of the details regarding our app and logs we have for this issue?
Looking forward to your reply soon.
Thank You.

**Comment by matthewrgourd** [comment]
Hi there I'm not sure I'll be able to help directly but maybe if I share with one of our developers. I've sent a blank email to tma@narola.email.

**Comment by TwinkleMali** [comment]
Hi matthewrgourd,

We still do not get any solution from your end for transaction failure. Status: E and Error Code: 502. 
And Our customer are keep on facing issue in payment. We must have to found solution for this issue soon.
We have reviewed Viva document, we found some iso error code there. 
Would you please update me how we can get iSO error code if transaction will get failed due to iSO reason ?

Looking forward to your reply soon.

Thanks,
Twinkle

**Comment by matthewrgourd** [comment]
Please share any request / response logs and we will look into for you. What is the base URL you're using?

**Comment by TwinkleMali** [comment]
Hi @matthewrgourd ,

Please find steps and url we are following are below.

Steps:

Card tokenization: (Called form mobile application to get token passed it to server.)
URL: https://www.vivapayments.com/api/cards?key={Our Public key}
Params: Number
CVC
ExpirationDate
CardHolderName

Creating order using,
URL: https://www.vivapayments.com/api/orders
Params: Amount = {Something}
SourceCode = {Something}
MaxInstallments = 0 (By default always)

Payment execution:
URL: https://www.vivapayments.com/api/transactions
Params: Amount = {Something}
OrderCode -> Received from above URL response
SourceCode = {Something}
CreditCard["Token"] = {card_token}

And in response it returns Status id: E and error code: 502.

Please do let us know if anything is managed wrong or missed to be managed.
Also if you need any other information from us that please let us know.

Looking forward to your reply.

Thanks,
Twinkle

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali I don't recognise https://www.vivapayments.com/api/cards?key={Our Public key} When did you find that in developer.vivawallet.com . You mention about card tokenization. Have you checked the relevant section? https://developer.vivawallet.com/api-reference-guide/payment-api-details/#card-tokenization

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali we discussed this by email and I think everything was covered. Is it ok to close this issue now?

**Comment by sergiutritean** [comment]
Hello, I'm facing the same issue, I'm trying to apply what's written in developer section of your website and it tells me that the URL I'm trying to add as a webhook can't be verified.  This is the url: "https://smartsenses.ro/index.php?wc-api=wc_vivawallet&vivawallet=webhook"
