### ISSUE TITLE
Can't accept installments Opencart

### ISSUE THREAD

**Issue by fatnikos** [VivaPayments/API#894]
Hello. I have opencart 1.5.6.4 and I use Viva payments for over 3 years. Since 2 weeks ago, installments have stopped appearing as an option, during checkout. Has something changed recently?

**Comment by VivaWalletSupport** [comment]
Hello, are you using a specific plugin / method to connect?

**Comment by fatnikos** [comment]
Yes, I am using this extension
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=13983

**Comment by VivaWalletSupport** [comment]
I see it uses the redirection method and since the problem appears in your stores checkout, you would have to consult your plugin provider. In case that solved your problem, please close this issue.
