### ISSUE TITLE
Currencies supported

### ISSUE THREAD

**Issue by SteveMersereau** [VivaPayments/API#895]
Can you let me know which currencies are supported by VivaWallet?  I'm using WordPress / WooCommerce if that's relevant.

**Comment by VivaWalletSupport** [comment]
Hello Steve, for the transaction at Viva only the currency is supported from the country your company is registered in. In case this would be the UK, only the GBP currency would be allowed. For WooCommerce there are various plugins available that are able to covert other currencies to GBP in the checkout stage. Please close this issue in case that answered your question.
