### ISSUE TITLE
Problem redirect to complete payment method on shopify

### ISSUE THREAD

**Issue by AlhagEsmaeel** [VivaPayments/API#896]
From my shopify payment method after redirecting to complete payment:
https://checkout.vivawallet.com/shopifyplugin

''Invalid currency used. You can currently only use EUR, GBP & RON''
dropenshop.com

**Comment by matthewrgourd** [comment]
Hi there, from which country are you operating?

**Comment by matthewrgourd** [comment]
The Viva Wallet Shopify plugin is compatible only with Euro, GBP and Romanian Leu currencies...
