### ISSUE TITLE
VivaWallet Shopify PlugIn Error

### ISSUE THREAD

**Issue by Padge72** [VivaPayments/API#897]
Hi,

Setup my VivaWallet account to Shopify site last night but when trying to test if it takes payments I get the attached error message. How do I fix this?
![Error Message](https://user-images.githubusercontent.com/51827022/59514591-17247200-8eb5-11e9-9cc3-ef911c293e10.jpeg)

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear you've been experiencing problems. Can you let me know if you've followed [this guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/) for setting up Viva Wallet with Shopify? Thanks!

**Comment by Padge72** [comment]
Hi Matthew,

Yes that was the process followed so it shows on Shopify as an available
payment method.

When a customer trys to buy an item, once all details are completed and the
button is pressed to complete the transaction the error message comes up.

Customers paying via PayPal can transact, which I'm surprised about.  But
we want to make sure they have a card option as well as PayPal.

Rwgards,
Simon

**Comment by matthewrgourd** [comment]
Hi there, thanks for clarifying the issue. I'm checking with our plugin developer. We'll get back to you soon!

**Comment by Padge72** [comment]
Thank you for your reply

**Comment by matthewrgourd** [comment]
Hi there, I'm told that the 'Input is invalid' error is a common one and usually means the MerchantID / Store Token fields have been completed incorrectly during setup. Would you be able to check this?

https://developer.vivawallet.com/images/VivaWalletPaymentProvider.png

**Comment by nutraleaf** [comment]
I am having the same issues. Please can someone help me . I have customers complaining that my website is a scam because they get taken to the error page

**Comment by nutraleaf** [comment]
I have checked Merchant ID and store token at least 20 times

**Comment by matthewrgourd** [comment]
@nutraleaf Very sorry to hear that. Are your customers receiving the same error message? We will look into further...

**Comment by nutraleaf** [comment]
Yes they are receiving the same message

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Padge72** [comment]
Hi Matthew,

I have an email from Richard Steggles that set the account up with a Login
and Password which is what I used for the store and token fields.

Regards,
Simon

**Comment by nutraleaf** [comment]
Maybe that is what I need a login and password

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dmihos** [comment]
Hi @Padge72 

No, your username and password are not your MerchantId and StoreToken.

As Matthew already suggested, you need to carefully follow [the guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/)

Please take a careful look at the 'Before you begin' section.
Did you fill up that form? Have you been sent the MerchantId and the StoreToken?

**Comment by nutraleaf** [comment]
[Image]
I have it all set up and the merchant Id is on my dashboard on viva along with my store token were it says API is that my store token

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dmihos** [comment]
> [Image] I have it all set up and the merchant Id is on my dashboard on viva along with my store token were it says API is that my store token Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

No, that is not your store token.
You will also need to follow [the guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/)

**Comment by nutraleaf** [comment]
[Image]
Ok have have followed the guide and I am at this stage so I think I am on the right track to getting set up

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Padge72** [comment]
Hi I thought I had been sent it in an email by Richard Steggles???

Who or where does the merchant id and store token come from?

Regards,
Simon

**Comment by nutraleaf** [comment]
Hi do you have a email address or someone I can email for technical support ?
I am still waiting for my account to be verified and still waiting for a token key to be emailed to me ?
This is not a simple straight forward system when it come to contact with viva
Debbie

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by matthewrgourd** [comment]
@Padge72 your merchant ID is found in the banking app. [Log in](https://www.vivapayments.com/en-gb/signin), then follow [these instructions](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/). To order a Shopify token which will then be emailed to you, complete [this form](https://viva.microsoftcrmportals.com/shopify). If you have already done the latter, but are still waiting to receive a Shopify token, let me know and I will chase.

**Comment by matthewrgourd** [comment]
@nutraleaf Please may I have your merchant ID (but not API key). Your merchant ID is found in the banking app. [Log in](https://www.vivapayments.com/en-gb/signin), then follow [these instructions](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/).  I will then chase for you.

**Comment by Padge72** [comment]
Hi Matthew,

I tracked down merchant id and requested the token, which was received.

As I had already installed the plug in to Shopify I just updated the
merchant id and token. We've had a transaction this morning go through.

Thanks for your help. I'll keep your email address handy for any future
issues as I want to set up some discounts on bulk purchases, monthly
subscriptions and pre-orders for stock.

Regards,
Simon

**Comment by nutraleaf** [comment]
This is my merchant id
89134563-85a7-4d79-93b5-65e97dd6ed3b

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by matthewrgourd** [comment]
@nutraleaf Thanks. I'm checking with our Shopify developer and will get back to you soon!

**Comment by matthewrgourd** [comment]
Hi @nutraleaf I have answers for you. If you have already completed a [token request form](https://viva.microsoftcrmportals.com/shopify), customer service will reply to you, usually within 24 hours. About your verification status, you need to email customer service directly: [support@vivawallet.com](mailto:support@vivawallet.com). Hope that helps! Matt

**Comment by nutraleaf** [comment]
Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
