### ISSUE TITLE
Vivawallet Woocommerce PlugIn Language Settings for Payment Page

### ISSUE THREAD

**Issue by CatalinVivaWalletRomania** [VivaPayments/API#898]
Hi
https://www.bormasina.ro/ just integrated the VivaWallet WooCommerce Plugin
The developer is asking if their are any settings in which he could change the language of the redirect payment page from English to Romanian

**Comment by VivaWalletSupport** [comment]
Hello, only English and Greek language are currently available:
https://developer.vivawallet.com/api-reference-guide/payment-api/create-order/#optional-parameters

In case that answered your question, please close this issue.
