### ISSUE TITLE
IMPORTANT: 3DSecure via API

### ISSUE THREAD

**Issue by hakJav** [VivaPayments/API#899]
I need to integrate payments 100% via your API into our IndeJuice.com online store, without any redirection away from the website. However, on the following API documentation page there is no information on how to deal with 3DSecure:

https://developer.vivawallet.com/api-reference-guide/payment-api/tokenize-card/ 

3DSecure will be mandatory come September due to PSD2.

Please advise on where I can find documentation on how to implement 3DSecure via the tokenization route above.

**Comment by matthewrgourd** [comment]
Hi there, we have a solution called [Native Checkout v2 (3DS)](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) which you may want to look at. However, you would need to request client credentials from us. Alternatively, [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/) which requires only basic authentication (credentials available in the Viva Wallet banking app). Thanks!

**Comment by hakJav** [comment]
Hi Matthew, I understand that link explains how to use 3DSecure via a transaction, but my question more specifically is how do I tokenize a card via 3DSecure? For example:
 1) Customer is in Checkout
 2) Customer adds card and chooses to 'save card'
 3) Customers hits 'Buy Now' and is redirected to 3DSecure
 4) Customer validates 3DSecure
 5) IMPORTANT: Server receives tokenized card value for future purchases (which will not need future 3DSecure)
 6) When customer returns, they just select card and hit 'buy now', server uses the tokenized card, no need for 3DSecure again.

This is how PayPal currently works, but we wish to do the same thing with VivaWallet. We just need the documentation for it. PSD2 regulations state 3DSecure is only required on first purchase to verify identity.

**Comment by matthewrgourd** [comment]
Hi there, thanks for clarifying the issue. I'm checking with our development team. I'll get back to you when I've been given an answer.

**Comment by matthewrgourd** [comment]
Hi @hakJav , I've spoken to a colleague of mine and I'm advised you need to do the following:

1. Complete the [Native Checkout v2](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) flow, which at the end will provide you with a payment token.

2. Once you receive the payment token and create a transaction, you exchange the payment token for a [card token](https://developer.vivawallet.com/api-reference-guide/payment-api/tokenize-card/) and store it on your server.

3. When one of your clients wants to complete a payment again, you'll need to exchange the card token with a new payment token and create a new transaction.

I hope this helps! Please get back to me if you have any further questions. Thanks, Matt

**Comment by hakJav** [comment]
Hi Matthew,

Many many thanks for finding that answer, that makes sense from what I've read from the API docs. THis is absolutely great customer service.

**Just one more question:** Is there a test card number that I can use in the Sandbox/Demo Account? Specifically a test card that initiates a 3DSecure authorisation? (one that I can use to test the 3DSecure route I mentioned above)

Much appreciated!

**Comment by matthewrgourd** [comment]
Hi @hakJav , try 4016000000040000012 as the card number. You can use any future date as the card expiration date and any CVV.

**Comment by VizuaaLOG** [comment]
Hey @matthewrgourd,

I'm trying to use that test card number but it's not triggering a 3D secure popup. Is this something that will only show on the live environment?

I'm using the Viva JS integration to generate a charge token but want to make sure the 3D Secure HTML is rendered correctly while it's being tested.

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG, I've raised this with our Development Team who will get back to you soon.

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG Response from dev team is that this is beyond our control. This happens due to instabilities that our 3DS provider at times faces in their demo environment. You could try card number 6007930123456780 which seems to work...hope this helps. Thanks!

**Comment by VizuaaLOG** [comment]
Hey @matthewrgourd ,

Thanks for the alternative card, doesn't seem to like it though. When creating a transaction using a charge token with the card number 6007930123456780 the API returns PaymentsNoBinRouteFound

Assuming that means more to you than it does me haha.

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG I've raised this with one of our developers who mentioned that it's a configuration issue at our end. I'll let you know when it's fixed. Apologies for any inconvenience caused. Thanks!

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG please could I have the merchant ID so we can look into this further. Thanks!

**Comment by VizuaaLOG** [comment]
Hey @matthewrgourd,

Sure it's 0dc910ed-7e96-404e-9171-ee918766cf46

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG I've had a reply back from our developer: 

> Card 6007930123456780 is a demo card and that's why id does not work as expected. Unfortunately card numbers used to trigger the 3DS authentication are not able to complete a transaction.

If this helps, please close the issue. Thanks!

**Comment by VizuaaLOG** [comment]
Thanks for looking into it. It didn't trigger a 3DS authentication though,  it gave a charge token straight away. I'm using the Viva JS library if that helps and the request token method.

I just want to trigger a 3DS check to verify the auth box will show and display correctly. Seems to be a bit tricky to get it to trigger a check though.

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG Can you let me know where you got the JS library from so I can check it? I mean the URL if you don't mind. Thanks.

**Comment by VizuaaLOG** [comment]
Hey @matthewrgourd The JS library is the one from the documentation https://www.vivapayments.com/web/checkout/v2/js

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG Can you try some alternative card numbers? 4016000000040000012 or 4016000000002 . Let me know the outcome. Thanks!

**Comment by VizuaaLOG** [comment]
Hi @matthewrgourd,

Thanks for sending these. Just tried both of these cards and they both complete the transaction but do not trigger a 3DS check.

**Comment by matthewrgourd** [comment]
@VizuaaLOG One of our developers has changed some of your configuration details. Can you try again? Thanks!

**Comment by VizuaaLOG** [comment]
Hey @matthewrgourd,

YES! Seems to be working now with 4016000000040000012 and everything on my checkout form broke :(. But at least I can sort that out.

Thanks for your help with this!

**Comment by digu087** [comment]
Hello @matthewrgourd 
We are trying to implement viva wallet into WHMCS . Everything has been integrated so far but we are not been able to test the 3DS flow . Have tried above credit card as well , but still no luck .
You can check our test cart here https://dev.brontobytes.com/cart.php .
This is the last issue we need to resolve before going live .

**Comment by matthewrgourd** [comment]
Hi @digu087 apologies for the delayed reply. One of our developers has responded about test cards for 3DS. Please see item one of the following: https://github.com/VivaPayments/API/issues/1073#issuecomment-532243393
