### ISSUE TITLE
Πρόβλημα με διασύνδεση 

### ISSUE THREAD

**Issue by MKaniouri** [VivaPayments/API#90]
Καλημέρα
προσπαθώ να διασυνδέσω το www.caralarms.gr με την viva για online πληρωμές με κάρτα. Ενώ έχει γίνει έγκριση πηγής και είναι όλα οκ την στιγμή που πάει να κάνει redirect μου βγάζει ένδειξη Bad Request. Θα μπορούσατε να το ελέγξετε παρακαλώ??

![image](https://cloud.githubusercontent.com/assets/18465339/14559299/5456f24e-0310-11e6-9941-37c50da638c8.png)

**Comment by dpnevmatikos** [comment]
Καλησπέρα @MKaniouri 
O κωδικός που περνάτε στην παράμετρο ```ref``` δεν είναι σωστός. Αν το παρατηρήσετε θα δείτε οτι δεν είναι αριθμός.

**Comment by MKaniouri** [comment]
Τι θα έπρεπε να περαστεί σε αυτή την παράμετρο???

**Comment by dpnevmatikos** [comment]
Πρέπει να περαστεί ο κωδικός πληρωμής που δημιουργείτε στο σύστημα μας (OrderCode) και είναι αριθμητικό.
