### ISSUE TITLE
Vivawallet won’t redirect to create order in prestashop

### ISSUE THREAD

**Issue by braisnatural** [VivaPayments/API#900]
Hi there!

We are experiencing the same issue of #818 , after payment there’s no redirection to our website so the order is not created on prestashop. 

Customers do receive the option to print the receipt on screen but no link or redirection to our website.

Tried to remove www of our domain on vivawallet configuration but still is not working. Payment is accepted but order in prestashop is not created.
![F45040C8-5F19-4508-9FC9-5AD8850EEDBD](https://user-images.githubusercontent.com/51922913/59619908-e69a3d80-912b-11e9-8180-ed2975f9f36b.png)

Would you help us? Thanks!

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by braisnatural** [comment]
Hi, thanks for your fast reply, here are the pictures.

<img width="1045" alt="source" src="https://user-images.githubusercontent.com/51922913/59665179-b77adf00-91b2-11e9-8206-804a6abfa692.png">
<img width="2041" alt="web-apps" src="https://user-images.githubusercontent.com/51922913/59665180-b77adf00-91b2-11e9-995c-1fac22ebc384.png">
<img width="783" alt="api-settings" src="https://user-images.githubusercontent.com/51922913/59665183-b77adf00-91b2-11e9-9b4f-ecd8ed6c569e.png">
<img width="661" alt="Plugin settings" src="https://user-images.githubusercontent.com/51922913/59665184-b77adf00-91b2-11e9-99dc-e0e3e4b46ce2.png">

Awaiting for your reply, kind regards.

**Comment by VivaWalletSupport** [comment]
In your API settings uncheck the box Enable Native..
In your module settings specify the Source Code 6408

If that solved your problem, please close this issue.

**Comment by braisnatural** [comment]
Thank yo for your reply, unfortunately after the changes we are getting a fatal error, the error URL is:

http://www.semillas-de-marihuana.com/modules/vivawallet/success.php?t=616d907c-a285-41d5-934e-4cf57e5e9227&s=1346475978956293&lang=en-US&eventId=0&eci=1?t=616d907c-a285-41d5-934e-4cf57e5e9227&s=1346475978956293&lang=en-US&eventId=0&eci=1

I'm attaching new images of how it looks after your directions.

Awaiting for your help again, kind regards.

<img width="811" alt="Captura de pantalla 2019-06-18 a las 13 28 46" src="https://user-images.githubusercontent.com/51922913/59678723-6a583680-91cd-11e9-9922-cea78b4bbbea.png">
<img width="645" alt="Captura de pantalla 2019-06-18 a las 13 27 56" src="https://user-images.githubusercontent.com/51922913/59678724-6af0cd00-91cd-11e9-9df1-08d5c3b93449.png">
<img width="526" alt="Captura de pantalla 2019-06-18 a las 13 28 24" src="https://user-images.githubusercontent.com/51922913/59678725-6af0cd00-91cd-11e9-98d1-64207524b178.png">

**Comment by VivaWalletSupport** [comment]
Correct the doman name in your payment source to include www (as your site uses the www part), it should be www.semillas-de-marihuana.com

**Comment by braisnatural** [comment]
Now is working, thank you for your support, very appreciated.

Kind regards
