### ISSUE TITLE
email notification to seller

### ISSUE THREAD

**Issue by Socialway** [VivaPayments/API#901]
I would like for the seller (our customer) to receive an email notification every time a payment via viva wallet is made online. Right now only the person who pays receives notification.

Please instruct on how to get this done.

WordPress 5.2.1, Viva Payments - Viva Wallet WooCommerce Payment Gateway 1.3.2, WooCommerce 3.6.4

**Comment by VivaWalletSupport** [comment]
Usually the merchant would receive a payment notification from the Viva platform after a success transaction, if not received, please check if it is not blocked by a spam filter and that the provided email address is correct. In case that solved the problem, please close this issue.

**Comment by Socialway** [comment]
Thank you for your reply.
It seems the email for notifications had never been verified.
