### ISSUE TITLE
Magento 2.3 module doesn't work in Multi store mode

### ISSUE THREAD

**Issue by Ddcdom** [VivaPayments/API#903]
**Preconditions**

1. Magento 2.3.1 installed
2. Two stores configured in Magento
3. Viva Wallet extension for Magento 2.3 installed and configured as per [guide](https://developer.vivawallet.com/e-commerce-plugins/magento2.3/)
4. Viva Wallet extension configured for real payments (not test mode)

**Steps to reproduce**

1. Add to basket and checkout
2. Select Viva Wallet as payment method
2. Make card payment on Viva Wallet page

**Expected results**
Redirected back to Magento store thank you page and order shown in back office in 'processing' state.

**Actual result**
Redirected back to Magento store (https://mystore.comvivapayments/viva/callback), which displays blank white page. No errors are logged anywhere in the system.

**Additional information**

This bug is caused by the code in the Viva Wallet extension Callback controller (`app/code/Ced/VivaPayments/Controller/Viva/Callback.php`). On lines 100,102,104 and 157, the call to the `ScopeConfig`'s `getValue `method passes a single argument, so the method uses the systems default scope. The config for the default scope is defined in `app/code/Ced/VivaPayments/etc/config.xml` and contains demo values, causing the callback to fail.

I've created this [pull request #902 ](https://github.com/VivaPayments/API/pull/902) which fixes the problem. In addition to fixing the problem this pull request also moves the instantiation of the ScopeConfig object from directly using the object manager to using dependency injection as [recommended by Magento](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/depend-inj.html).

**Comment by matthewrgourd** [comment]
Many thanks for submitting your code changes for review. These are now approved and merged to master. Many thanks for your input, it is much appreciated by the Viva Wallet team!
