### ISSUE TITLE
https://checkout.vivawallet.com/shopifyplugin

### ISSUE THREAD

**Issue by LOUISE132** [VivaPayments/API#906]
Hi

I've set Viva Wallet as payment processor.

When running test purchase the page before completing order redirects to the below link:
https://checkout.vivawallet.com/shopifyplugin

Everything is set to live.

Please advise why this is happening and how to correct it.

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear you're experiencing problems. Before we go any further, can I just check if you followed the installation instructions in our developer guide [here](https://developer.vivawallet.com/e-commerce-plugins/shopify/)?

**Comment by LOUISE132** [comment]
Hi Mathew
I believe I did - now Im checking the merchant id and store token is correct yet Im unable to find the store token.
Where would I have initially found this ?

**Comment by matthewrgourd** [comment]
Hi @LOUISE132 you need to complete a [Shopify token request form](https://viva.microsoftcrmportals.com/shopify). Customer service will then email you back with the token, usually within 24 hours. Thanks, Matt

**Comment by LOUISE132** [comment]
So to confirm the token you just emailed  is not correct?

**Comment by matthewrgourd** [comment]
If you have already received an email containing the token then that is correct.

**Comment by LOUISE132** [comment]
OK I did recieve the email and enterd the token AND it's still not working

The payment link directs to the below page:
https://checkout.vivawallet.com/shopifyplugin

Are you able to assist in correcting this issue?

**Comment by dmihos** [comment]
The link you are posting is not very informative.
What does this page display? Do you have a screenshot?

**Comment by LOUISE132** [comment]
Please find screen shot attached.

**Comment by dmihos** [comment]
You probably attached it in an email, but we can't see it.
You need to post it in the Github issue.
https://github.com/VivaPayments/API/issues/906

**Comment by LOUISE132** [comment]
![SCREENSHOT](https://user-images.githubusercontent.com/52067765/59919131-f1541b80-9426-11e9-8285-591ef15e7136.jpg)

**Comment by dmihos** [comment]
What have you used as MerchantId? 
Can you post its first 20 characters here?

**Comment by LOUISE132** [comment]
806439ac-de73-4a1c-bfb5

**Comment by dmihos** [comment]
Please double check the merchantId, it seems you've mistyped it, it is 36 characters long, including the dashes (-).

**Comment by LOUISE132** [comment]
Thank you that has fixed it!
Can you please assist with another issue?
I received email confirmation that our account had been successfully verified and our dashboard message:
‘The verification of your account has been completed. You are ready to use all our services.’
However when I then click onto our Profile page the messages reads:
‘Pending Documents! Click on UPLOAD DOCUMENTS button, to upload the remaining documents that were requested during your identification.’
Can you please advise, as I have already supplied all the required information?

**Comment by matthewrgourd** [comment]
Hi there, please email support@vivawallet.com or call + 44 (20) 37347770 as this is a customer service issue. Thanks!

**Comment by LOUISE132** [comment]
Will do Thanks
