### ISSUE TITLE
CS-Cart 3 Fails Redirection Page

### ISSUE THREAD

**Issue by iNarek** [VivaPayments/API#907]
Hi, we have a CS-Cart 3 installation.

After following the instructions to implement the Viva Wallet API on this link:
https://developer.vivawallet.com/e-commerce-plugins/cscart/

Until the Optional Webhooks part. I couldn't get that to work, even after following the instructions on this page for Webhooks:
https://developer.vivawallet.com/e-commerce-plugins/find-your-credentials-and-add-a-webhook/

And completing the order on our website. It redirects to a blank page and gets stuck on a message

"Πραγματοποίηση της Παραγγελίας. Σας παρακαλούμε περιμένετε..." ("Completing your order. Please wait...")

Can anyone please help asap, because we're losing orders.
Thanks

**Comment by VivaWalletSupport** [comment]
Hello, please provide the following 4 screenshots:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by iNarek** [comment]
Here you go:
https://drive.google.com/drive/folders/14SST5WOMHvFs053zEoyuYTT_IWnK-ipd?usp=sharing

**Comment by VivaWalletSupport** [comment]
Thank you, please follow the instructions for setting up the connection to the letter, your screenshots do not resemble what has been instructed at https://developer.vivawallet.com/e-commerce-plugins/cscart/

Also make sure you are using the plugin from https://github.com/VivaPayments/API/tree/master/Plugins/cscart/cscart-vivawallet as the instructions do not apply for a used 3rd party module.

Also execute following mysql query, as I noticed it is missing from the instructions:
```
INSERT INTO `cscart_language_values` (`lang_code` ,`name` ,`value`) VALUES 
('EN', 'text_vivawallet_notice', '<b>Note:</b> Please set the following information to payment source:<br />Success URL: <u>[success_url]</u><br /> Fail URL: <u>[failure_url]</u><br /><b>Optional:</b> Set the following information to the webhook URL:<br />Success URL: <u>[webhook_url]</u><br /><br />'), 
('EL', 'text_vivawallet_notice', '<b>Note:</b> Please set the following information to payment source:<br />Success URL: <u>[success_url]</u><br /> Fail URL: <u>[failure_url]</u><br /><b>Optional:</b> Set the following information to the webhook URL:<br />Success URL: <u>[webhook_url]</u><br /><br /><br />');
```

**Comment by iNarek** [comment]
You're right. I noticed I haven't put the "Source Code" number in the plugin from the "Code" box in the "New Payment Source dialog box". Thanks.

I downloaded the "API-master.zip" from the top of the instructions page. "**Download API-master.zip to your desktop.**" https://developer.vivawallet.com/e-commerce-plugins/cscart/
Isn't that the latest version?

I also executed the SQL code you gave me and the cs-cart plugin now displays further information.

Here are some updated screenshots:
https://drive.google.com/drive/folders/1VFUK6ZiiV7ZNbN9rZ3-OQhkL2stkNA4b?usp=sharing

Note: The webhook url that now shows up in the plugin page, I copy-pasted it in the "Create Webhook" dialog box but it doesn't work. (and the **Error!** not that appears "these guidelines (Error code 502)" link is not pointing at the correct url. It redirects here https://github.com/VivaPayments/API/wiki/Webhooks)

**Comment by VivaWalletSupport** [comment]
Are you able to make an order now using the Viva Payment option?

**Comment by iNarek** [comment]
Unfortunately no. You can go to https://www.cptpapadakisphoto.gr/ now and try to pay with Viva Wallet. You'll see that it gets stuck on the redirection page.
Order this item https://www.cptpapadakisphoto.gr/index.php?dispatch=products.view&product_id=10920 so I know it's you, and we can delete the order later.

**Comment by VivaWalletSupport** [comment]
What errors are logged?

**Comment by iNarek** [comment]
`Warning	mod_fcgid: stderr: PHP Parse error: syntax error, unexpected T_VARIABLE in /var/www/vhosts/cptpapadakisphoto.gr/httpdocs/payments/vivawallet.php on line 51, referer: https://www.cptpapadakisphoto.gr/index.php?dispatch=checkout.checkout	`			Apache error

**Comment by VivaWalletSupport** [comment]
Please edit the file an correct following string:
$MerchantID =  $processor_data['params']['merchant_id']

To:
$MerchantID =  $processor_data['params']['merchant_id'];

**Comment by iNarek** [comment]
OMG it Worked! Finally! Thank you so very much! :D

![success!](https://user-images.githubusercontent.com/3193558/60100917-7317b200-9763-11e9-811e-0129594dbe08.jpg)

**Comment by VivaWalletSupport** [comment]
Please close this issue in case the problem has been resolved.

**Comment by kotheor** [comment]
Unfortunately no. You can go to https://www.dpaper.gr/proionta/product/1-xartotainia5740.html now and try to pay with Viva Wallet. You'll see that it gets stuck on the redirection page.
