### ISSUE TITLE
At the checkout it's showing euro sign instead of £ sign

### ISSUE THREAD

**Issue by Shoplexabc** [VivaPayments/API#908]
at the checkout viva wallet showing euro sign instead of £ sign in my shopify store 
Could you please look into it
shoplex.co.uk

**Comment by matthewrgourd** [comment]
Please have a look at our [Shopify guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/). Step 10 describes how to change currency. Hope that helps! Let me know if not. Matt

**Comment by Shoplexabc** [comment]
Hi there

The store currency is set to GBP i've double checked that's working fine it's showing GBP for the customers at the checkout however in the same panel when you pay by card the viva wallet shoes the same amount with the euro symbol front of it and it might confuse buyers

**Comment by Shoplexabc** [comment]
it's on the page when you completed the check out and the summary page thank you for your order etc.. and there is 2 values like £7.50 and another one €7.50 with the euro symbol front of it

**Comment by matthewrgourd** [comment]
Hi @Shoplexabc this seems like a Shopify issue rather than a problem at our end. We suggest you contact their [support team](https://support.shopify.com/). Thanks!
