### ISSUE TITLE
currency Problem

### ISSUE THREAD

**Issue by BlueGreenWhite** [VivaPayments/API#909]
Hi
I get the following message when trying to pay using Euros in my website  (Paying in GBP works fine).

Can you help me fix this problem so that I can accept euros as well as GBP please.

Fatal error: Uncaught Exception: Unable to create order code (Person [Edited out] does not support currency '978') in /homepages/27/d731440582/htdocs/[website]/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php:343 Stack trace: #0 /homepages/27/d731440582/htdocs/[website]/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.php(453): WC_VIVAWALLET->generate_form(1069) #1 /homepages/27/d731440582/htdocs/[website]/wp-includes/class-wp-hook.php(286): WC_VIVAWALLET->receipt_page(1069) #2 /homepages/27/d731440582/htdocs/[website]/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /homepages/27/d731440582/htdocs/[website]/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /homepages/27/d731440582/htdocs/[website]/wp-content/plugins/woocommerce/templates/checkout/order-receipt.php(44): do_action('woocommerce_rec...', 1069) #5 /homepages/27/d731440582/htdocs/[website]/wp-content/plugins/woocommerce/includes/wc-core-functions.php(249): include('/homepa in/homepages/27/d731440582/htdocs/[website]/wp-content/plugins/vivawallet-for-woocommerce/wc-vivawallet.phpon line343

**Comment by VivaWalletSupport** [comment]
Hello, for the transaction at Viva only the currency is supported from the country your company is registered in. In case this would be the UK, only the GBP currency would be allowed. For WooCommerce there are various plugins available that are able to covert other currencies to GBP in the checkout stage. Please close this issue in case that answered your question.

**Comment by BlueGreenWhite** [comment]
Thanks for the response.  I was under the impression that vivaWallet could take different currency payments.  

I’ve looked for the plugins but not been able to find one.  Could you give me two or three examples please of these plugins that I can try.  

Thanks

**Comment by matthewrgourd** [comment]
You would need to do a search for a suitable plugin on the following page: https://woocommerce.com/product-category/woocommerce-extensions/
