### ISSUE TITLE
Προβλημα με redirect

### ISSUE THREAD

**Issue by mikelos4** [VivaPayments/API#91]
Καλημέρα
προσπαθώ να συνδέσω το www.find4you.gr με την viva για online πληρωμές με κάρτα. Ενώ έχει γίνει έγκριση πηγής και είναι όλα οκ την στιγμή που πάει να κάνει redirect μου βγάζει ένδειξη Bad Request. 
Ευχαριστω
![v3](https://cloud.githubusercontent.com/assets/18575675/14676880/08057044-0718-11e6-8137-59b310d168bf.JPG)
![v2s](https://cloud.githubusercontent.com/assets/18575675/14677001/68460ec8-0718-11e6-99da-97efeb9c6058.jpg)

**Comment by dmihos** [comment]
Καλημέρα

Όπως φαίνεται στο 1ο screenshot σας, το url της checkout σελίδας δεν έχει συμπληρωμένη την παράμετρο ref, στην οποία θα πρέπει να μπει το OrderCode από το 1ο βήμα (CreateOrder).
Το 2ο screenshot μοιάζει να δείχνει το configuration panel κάποιου plugin.
Θα πρέπει να επικοινωνήσετε με την εταιρία που υποστηρίζει το συγκεκριμένο plugin, να σας βοηθήσει να το κάνετε configure σωστά.
