### ISSUE TITLE
Example Code Not Working!

### ISSUE THREAD

**Issue by hakJav** [VivaPayments/API#911]
When I run the example code here: https://github.com/VivaPayments/API/blob/master/CreateOrder/PHP/create_order.php

It returns the error message: "API Call failed! The error was: Moved Permanently"

I can't get the API to work at all.... has the API endpoint changed?? Also, my demo-account dashboard just shows the error message "Ιt's taking a bit longer than expected..."

**Comment by matthewrgourd** [comment]
Hi there, we are looking into this. I will get back to you shortly. Thanks!

**Comment by TwinkleMali** [comment]
@matthewrgourd , We are also facing same issue. And our application is live. 
Any luck at your end for this issue? 

Looking forward to your reply.

Thank You.

**Comment by hakJav** [comment]
@matthewrgourd can you please post an update soon? This issue is critical for us. We need to go live before September, the European PSD2 deadline (the new payment security law).

**Comment by matthewrgourd** [comment]
@hakJav @TwinkleMali  I'm sorry for the delay. I believe the code sample needed to be updated to show 'https' for the demo URL, as in 'https://demo.vivapayments.com/api/orders'. I've changed this now. If you're referring to production, I'm afraid I can't see any obvious issue. Please update this issue by attaching screenshots of the error messages with any personal data or security information blanked out.

**Comment by hakJav** [comment]
Hey @matthewrgourd - very weird, I thought I tried https before, but it works now with https. Many thanks for addressing this issue.
