### ISSUE TITLE
'Unknown cipher in list: TLSv1'

### ISSUE THREAD

**Issue by elefter** [VivaPayments/API#912]
Hello i am using Simple Checkout to crate a charge,
i get the vivaWalletToken and proceed to make the charge with using curl.
I am hosting the site in topHost.

the post url i use is https://demo.vivapayments.com/api/transactions.
the curl i use has this version: 'ssl_version' => 'NSS/3.36',

after the call i get the following error:
'Unknown cipher in list: TLSv1'

**1.** after digging around i found this solution: #32 
----------------------------------
η γραμμή:
curl_setopt($session, CURLOPT_SSL_CIPHER_LIST,'TLSv1');

πρέπει να αντικατασταθεί με το:
define('CURL_SSLVERSION_TLSv1', 1);
curl_setopt( $session, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);
------------------------------------------------

When i do that i get the following error:
------------------------------------------------
'HTTP/1.1 200 The specified api action is disabled for the merchant 000c727f-6b91-469d-833b-9a772f3d09b9, please consult the documentation
Server: nginx
Date: Mon, 01 Jul 2019 15:38:07 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 440
Connection: keep-alive
X-Viva-CorrelationId: 19-182-C85C952C
X-Powered-By: ASP.NET

{"Emv":null,"Amount":null,"StatusId":"E","CurrencyCode":null,"TransactionId":null,"ReferenceNumber":null,"AuthorizationId":null,"RetrievalReferenceNumber":null,"ThreeDSecureStatusId":null,"ErrorCode":403,"ErrorText":"The specified api action is disabled for the merchant 000c727f-6b91-469d-833b-9a772f3d09b9, please consult the documentation","TimeStamp":"2019-07-01T18:38:07.4980216+03:00","CorrelationId":null,"EventId":0,"Success":false}'
------------------------------------------------

2. Another solution i found was #144 If i do that i also get the same error.

**Comment by matthewrgourd** [comment]
Are you definitely logging into your [Viva Wallet demo merchant account](https://demo.vivapayments.com/en/signin) and getting your merchant ID and API key from there? Thanks.

**Comment by matthewrgourd** [comment]
Hi there, have you checked the [Simple Checkout](https://developer.vivawallet.com/online-checkouts/simple-checkout/) page on our Developer Portal? I'm not immediately sure how to help with this issue but can raise with a developer if required. As an alternative, you could try our [Redirect Checkou](https://developer.vivawallet.com/online-checkouts/redirect-checkout/)t.
