### ISSUE TITLE
Error in api/orders using https://demo.vivapayments.com/api/orders

### ISSUE THREAD

**Issue by fylstathis3** [VivaPayments/API#915]
Hi,
We are getting the following error when we call api/orders:
-System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

This call was working fine for a long time, but now it returns this error.
Could you please help us?
Regards

**Comment by matthewrgourd** [comment]
Sorry to hear you've been experiencing issues. I've just checked the API and can access with no problems. Could you let me know your merchant ID and the name of the business, please, and I'll check further?

**Comment by fylstathis3** [comment]
Hi,
Thank you for your reply.
The merchantId is "da73c68d-83f6-4b58-8678-ddb6fe537fb2" and the name of the business is Levante Ferries.

Thank you in advance

**Comment by matthewrgourd** [comment]
Hi there, we've checked and can find no problems on our side. It is most likely a server issue as the API call isn't even being initiated. Beyond that, you'll need to speak to your IT engineer...
