### ISSUE TITLE
Payment error in prestashop

### ISSUE THREAD

**Issue by mhardenne** [VivaPayments/API#916]
Hello,

A merchant faces issues with his prestashop e-commerce. 
This is the error his clients get when trying to pay on his e-commerce : 
![erreur de paiement](https://user-images.githubusercontent.com/52457297/60584342-4a0fa680-9d8d-11e9-8a34-10609ccff259.png)

See the error on his backend office is the same : 

![2](https://user-images.githubusercontent.com/52457297/60584426-7f1bf900-9d8d-11e9-9b28-b8450f3e9f9f.png)

Any idea where does it come from ?
Does the Viva plugin accept all cards ?
Let me know if you need something more.

Thanks

**Comment by VivaWalletSupport** [comment]
Hello, this error always happens, or with some transactions? Are you using a specific plugin to connect?
https://support.vivawallet.com/hc/en-us/articles/360001360725-What-types-of-card-can-I-accept-

**Comment by mhardenne** [comment]
Hello,

No this error happens sometimes (more "often") but they receive payments.
What do you mean by "specific plugin to connect" ?

Thanks for the answer

**Comment by mhardenne** [comment]
Almost 1 command out of 2 has this error to be more precise

**Comment by VivaWalletSupport** [comment]
From where did you get the payment module, or did you develop it yourself?
