### ISSUE TITLE
Crippling Payment Failures

### ISSUE THREAD

**Issue by Mpanayi** [VivaPayments/API#917]
Hello Technical Vivapayments team.  I have a concerning issue where customers payments are processing but eventually cancel. The customer is redirected to a white screen with -1 displayed in the corner.  We have configured the plugin correctly (WooCommerce Vivawallet Gateway version3.5.7 by vivawallet) entering   merchant id , API and 4 digit code taken from Vivawallet created. After several efforts we decided to try Viva Payment – viva wallet WooCommerce payment Gateway version 1.3.2 by Enartia  this also failed payment but redirects the customer saying incorrect merchant id or failed API.  We have checked all settings and as of yet have no sales because we cannot receive payment. We have invested in SEO campaigns so we need to be able to sell. Please get back to us with a solution.

**Comment by VivaWalletSupport** [comment]
Hello, please use the supported plugin (v357) and provide the following 4 screenshots:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by Mpanayi** [comment]
![Capture1](https://user-images.githubusercontent.com/52491227/60619565-a3092a00-9de1-11e9-88c2-6f9b0b9c0c56.JPG)
![Capture2](https://user-images.githubusercontent.com/52491227/60619566-a3a1c080-9de1-11e9-9f73-1705a96b1ca6.JPG)
![Capture3](https://user-images.githubusercontent.com/52491227/60619567-a3a1c080-9de1-11e9-98a1-f1231f7657ba.JPG)
![Capture4](https://user-images.githubusercontent.com/52491227/60619569-a3a1c080-9de1-11e9-9054-f13d0ddeefe4.JPG)

**Comment by VivaWalletSupport** [comment]
Please provide following screenshot (source 2194):
Viva Wallet payment source settings (include the browsers URL in the screenshot).

**Comment by Mpanayi** [comment]
![source](https://user-images.githubusercontent.com/52491227/60640172-8810d700-9e2e-11e9-9399-a48b065ca4f9.JPG)
![source cont](https://user-images.githubusercontent.com/52491227/60640184-9fe85b00-9e2e-11e9-97c2-55f10790b114.JPG)

**Comment by VivaWalletSupport** [comment]
Remove the www. part from the Domain Name, as your site does not seem to use it. In case that solved the problem, please close this issue.

**Comment by Mpanayi** [comment]
i tried still getting this
![error codes](https://user-images.githubusercontent.com/52491227/60646599-64588b80-9e44-11e9-885c-efe78f9e85a1.JPG)

**Comment by Mpanayi** [comment]
this could be because its pending the change of url still

**Comment by VivaWalletSupport** [comment]
You would have to wait until the change in your payment source is approved and the source is activated.
