### ISSUE TITLE
webhook (error 502)

### ISSUE THREAD

**Issue by nature1st** [VivaPayments/API#918]
I'm trying to creat a webhook and keep getting Error 502 message

https://www.nature1st.co.uk/index.php?wc-api=wc_vivawallet&vivawallet=webhook

is what i have entered, can anyone help. I have no ideal what i'm doing??

**Comment by VivaWalletSupport** [comment]
Hello, please use the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ and provide the following 4 screenshots:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by texnikoss** [comment]
Εχω αυτο το προβλημα και εγω. 
Σφάλμα! Το url που εισάγατε δε μπορεί να επιβεβαιωθεί. Παρακαλώ βεβαιωθείτε ότι είναι ένα έγκυρο, προσβάσιμο url φτιαγμένο με αυτές τις προδιαγραφές. (Κωδ. Σφάλματος 502)
Δεν φτιαχνεται με τιποτα. τι LINK  βαζω εκει?
