### ISSUE TITLE
Test account 404 error on subscribe now

### ISSUE THREAD

**Issue by ChrisLennonLondon** [VivaPayments/API#920]
Hi there,

I set up a live account earlier and managed to get a couple of transactions through. However the email confirmation to the customer, did not come through (Prob woocommerce)

So I have now setup a test account so I can do some exstensive testing.

As soon as I click subscribe now, I get an error 404 when it tries to open the viva application

Happy to provide my account details if there is a private option?

**Comment by ChrisLennonLondon** [comment]
PS, I have woocommerce config as test mode, api, and 4 digit id and the other code all correct.

**Comment by matthewrgourd** [comment]
Hi there, apologies for the lack of reply previously. Please let me know where you got the WooCommerce plugin from, i.e. send me the link to the download page as I need to check this first. Thanks!

**Comment by matthewrgourd** [comment]
No reply so closing issue.
