### ISSUE TITLE
Magento 2.3.1 multilanguage problem

### ISSUE THREAD

**Issue by ioannisgz** [VivaPayments/API#921]
Hi. Our magento is using two languages English and Greek. Although in vivapayments we have created two different Websites, one for English and one for Greek store with the correct urls from magento, when a customer is completing the order and moving to viva payments url this page is always at English language and you don't have the ability to change to Greek. We have set to magento one code for English store and one for Greek. But it we use in viva links:
```
OrderCode URL: https://www.vivapayments.com/api/orders
Gateway URL: https://www.vivapayments.com/web/newtransaction.aspx
Transaction URL: https://www.vivapayments.com/api/transactions/
```

What we do wrong please?

**Comment by VivaWalletSupport** [comment]
Hello, make sure that in both payment sources you created in your Viva account the return URLs contain the correct store language parameters.

**Comment by ioannisgz** [comment]
These URLs are Ok. The have the magento's language parameters. But my problem is not at return to my shop. The issue is when you go from my shop to VIVA. VIVA page is always to english.

**Comment by VivaWalletSupport** [comment]
In Ced\VivaPayments\Model\PaymentMethod.php at line 95 following code is executed to get the used locale: $trlang = $this->_localeResolver->getLocale();
In case el-GR is detected the payment form from Viva should be in Greek, in all other cases in English.

**Comment by ioannisgz** [comment]
I see that code but are you sure it is working? In our side when you place an order in Greek store when you leave our shop from magento Greek store it goes to VIVA English site.

**Comment by VivaWalletSupport** [comment]
Check if your store uses the el-GR locale when visiting in Greek, otherwise you might adjust the code or the used locale.

**Comment by ioannisgz** [comment]
<img width="1095" alt="Screenshot 2019-07-04 at 17 54 01" src="https://user-images.githubusercontent.com/44767880/60675376-ed8fb280-9e84-11e9-9630-897c3a819a8d.png">
Magento locale is set right. But it isn't as you mentioned el-GR. Magento for Greek store uses el_GR
and for English en_US.
Maybe the underscore is the problem??

**Comment by ioannisgz** [comment]
Just know checked again....Both stores English and Greek from our shop goes to this screen:

![Screenshot](https://user-images.githubusercontent.com/44767880/60675844-064c9800-9e86-11e9-837b-8c878a1da114.png)

**Comment by ioannisgz** [comment]
> In Ced\VivaPayments\Model\PaymentMethod.php at line 95 following code is executed to get the used locale: $trlang = $this->_localeResolver->getLocale();
> In case el-GR is detected the payment form from Viva should be in Greek, in all other cases in English.

In same file line 125 is:

```
 if ($trlang=='el-GR') {
            $formlang = 'el-GR';
        } else {
            $formlang = 'en-US';
        }
```

Should I change them with 

> el_GR and en_US

**Comment by VivaWalletSupport** [comment]
Try with only changing `if ($trlang=='el-GR') {` to `if ($trlang=='el-GR' || $trlang=='el_GR') {`

**Comment by ioannisgz** [comment]
Ok....I am closing the issue for now. Thank you!
