### ISSUE TITLE
viva walet A920 403 PAYMENT POLICY CREDIT RESTRICTION

### ISSUE THREAD

**Issue by P15CEM** [VivaPayments/API#922]
IM  GETTING THIS MESSAGE WHEN IM TRYING TO TAKE A PAYMENT OF CLIENT AND GET THIS MESSAGE: PAYMENTS POLICY CREDIT RESTRICTION - 403. CAN SOMEONE HELP PLEASE. ON TERMINAL A920

**Comment by matthewrgourd** [comment]
Please contact customer service on + 44 (20) 37347770. Thanks!
