### ISSUE TITLE
Payment error 

### ISSUE THREAD

**Issue by Davidburden99** [VivaPayments/API#923]
Hi,

When customers are trying to buy something on my site and redirected to viva wallet they are experiencing an error problem. see attached 

please advise
![Screenshot 2019-07-04 at 12 59 30](https://user-images.githubusercontent.com/52534895/60665533-9aa20500-9e5c-11e9-8705-b0620ca79fe1.png)

**Comment by dmihos** [comment]
It seems like you're trying to add Viva Wallet payments in a Shopify store.
Did you carefully follow [this guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/)?

**Comment by Davidburden99** [comment]
Hi, 

no as per my message above I already have been using viva wallet in conjunction with shopify for a while now. It suddenly stopped working the day I messaged you. It seems to be working now. Can you give me an answer as to what happened and is it all working correctly now?

Today another issue has come to light. On the 29th June Chloe Bell tried to make an order on my site, she got as far as making payment to viva wallet and then it didn't re direct back to shopify. We were totally unaware of the order and it returned to our abandoned checkout list rather than as an order. What happened here?

transaction details:


Order Code | 4944971045718770
-- | --
Timestamp | 29/06/2019 22:04:48
Merchant Reference | 6292949467195
Description for customer | The London Botanists - #6292949467195
Amount | 70.00 GBP
Tip Amount | 0.00 GBP
Paid to your wallet | 68.00 GBP
Channel / Source | Web Redirect / Shopify
Wallet | Primary [65223032]
Tags | The London Botanists
Transaction Id | d5b3ee8b-7d83-4559-858f-54c9a40e0fd7

**Comment by Davidburden99** [comment]
we only found out about this order when she contacted us

**Comment by Davidburden99** [comment]
Another customer has tried to make a payment and faced an error at viva wallet. I would like to escalate this as a complaint as I still haven't received a response as to why this keeps happening

**Comment by Davidburden99** [comment]
![Screenshot 2019-07-09 at 11 27 41](https://user-images.githubusercontent.com/52534895/60881131-f1cd1e80-a23c-11e9-92a5-30bf32280207.png)
![Screenshot 2019-07-09 at 11 28 23](https://user-images.githubusercontent.com/52534895/60881140-f4c80f00-a23c-11e9-95bc-c7e849f81c7f.png)

**Comment by Davidburden99** [comment]
Its costing me money and reputation for this to keep happening

**Comment by dmihos** [comment]
H Davidburden99.
There is no recorded global problem, thousands of orders keep completing every day without issues.

Please note, due to the way checkout flow works on Shopify (a set of redirects from store>gateway>checkout>gateway>store) it does happen that the client is not redirected back to store. It's not common or usual, but it happens, usually it's the client's connection or browser to blame.

We'll be closely monitoring the flow for improvements that we can do.

The error you posted on the first message is something different.
It's reported again today by one other user, we'll handle this with highest priority.

**Comment by matthewrgourd** [comment]
Hi @Davidburden99 , I'm sorry for the lack of contact after you raised this issue. We did in fact investigate and found there to be a problem which was later fixed. Please do let me know if you experience any further issues and I will escalate immediately. Have a good day!
