### ISSUE TITLE
ΠΛΑΤΦΟΡΜΑ ΠΛΗΡΩΜΩΝ ΛΟΓΑΡΙΑΣΜΩΝ

### ISSUE THREAD

**Issue by paradisegdevelop** [VivaPayments/API#924]
ΚΑΛΗΜΕΡΑ ΕΙΜΑΙ ΕΝΑ ΙΔΙΩΤΙΚΟ ΚΕΠ ΚΑΙ ΘΑ ΗΘΕΛΑ ΝΑ ΒΑΛΩ ΜΕΣΑ ΣΤΗΝ ΙΣΤΟΣΕΛΙΔΑ ΜΟΥ ΕΦΑΡΜΟΓΗ ΓΙΑ ΝΑ ΜΠΟΡΟΥΝ ΟΙ ΠΟΛΙΤΕΣ ΝΑ ΠΛΗΡΩΝΟΥΝ ΛΟΓΑΡΙΑΣΜΟΥΣ ΜΕΣΩ ΤΗΣ VIVA PAYMENTS

**Comment by matthewrgourd** [comment]
Please send them to https://members.vivawallet.com/el-gr/ClientSignUp. Thanks!
