### ISSUE TITLE
Simple Checkout in Safari - iFrame opens in a new tab

### ISSUE THREAD

**Issue by donfn** [VivaPayments/API#925]
Hello,
For quite a while now, Simple Checkout on Safari, instead of rendering an iFrame,
the page opens in a new tab. As a result, the Simple Checkout form cannot communicate with the originator page. After the submission of the card details, the payment button becomes green, a token is generated, but there is no way to harvest it and process it further.

Note that I've received the same complaint from customers using browsers other than Safari (so far on mobile). 

(The issue can also be replicated at your JSBin example)

Thanks.

**Comment by matthewrgourd** [comment]
Hi there, we are aware there are browser compatibility issues with Simple Checkout. Our recommendation is to switch to using [Redirect Checkout](https://developer.vivawallet.com/online-checkouts/redirect-checkout/) if low success rate with SC. Thanks!
