### ISSUE TITLE
Cannot Access: 3DSecure via the Native Checkout v2.0 API

### ISSUE THREAD

**Issue by hakJav** [VivaPayments/API#926]
This issue is regarding:
> https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#3dsecure-via-the-native-checkout-v2-0-api

Specifically accessing the endpoint:
> /nativecheckout/v2/chargetokens

I can't seem to create a charge token. I assume you have to access the endpoint via OAuth2, so my API call includes the access token in an Authorization header (Bearer scheme), and I've passed the following parameters as the documentation states:

```
{
    "Cvc": "111",
    "Amount": 1000,
    "Number": "4016000000040000012",
    "Holdername": "John Doe",
    "ExpirationYear": 2030,
    "ExpirationMonth": 10,
    "SessionRedirectUrl": (my own url endpoint)
}
```

However, I always get a 404 Not Found error.

Am I missing any parameters? Is the demo endpoint incorrect? I've tried the following endpoints, but they only return 404:
 - https://demo.vivapayments.com/api/nativecheckout/v2/chargetokens
 - https://demo.vivapayments.com/nativecheckout/v2/chargetokens

It probably would be easiest if you send across (or add to the API documentation) a Postman example?

**Comment by matthewrgourd** [comment]
Hi @hakJav sorry to hear this. Have you tried https://demo-api.vivapayments.com//nativecheckout/v2/chargetokens? Please check and get back to me if any issues. Thanks!

**Comment by hakJav** [comment]
Still isn't working. Does it work on your end? Could you send across screenshots of a working Postman example of (1) the Authorization data and (1) and parameters data?

**Comment by matthewrgourd** [comment]
Hi there, below are the steps I took in the demo environment. Hope this helps!

![1](https://user-images.githubusercontent.com/44943019/60875916-ca715400-a232-11e9-8f5b-cd44599c8ec6.png)

![2](https://user-images.githubusercontent.com/44943019/60875924-cfce9e80-a232-11e9-8397-04d7c0a8d82d.png)

![3](https://user-images.githubusercontent.com/44943019/60875944-d4935280-a232-11e9-94e7-25983dee56d5.png)

![4](https://user-images.githubusercontent.com/44943019/60875974-e2e16e80-a232-11e9-8f46-7d91eabf4052.png)

![5](https://user-images.githubusercontent.com/44943019/60876193-4e2b4080-a233-11e9-8d6f-9444bcf593fe.png)

**Comment by VizuaaLOG** [comment]
Following your screenshots all I keep receiving is a 403 Forbidden. Even after generating a new token. The JS API is also returning a 403. Triple checked and my postman config is the same as your screenshots.

**Comment by matthewrgourd** [comment]
@VizuaaLOG When you send the POST request, have you selected  'Bearer token' as the type of authorization before including the token? See screenshot below:

![6](https://user-images.githubusercontent.com/44943019/60886291-7d4cac80-a249-11e9-8369-1c830d2f3915.png)

**Comment by hakJav** [comment]
@matthewrgourd I'm also getting a 403 Forbidden error following the initial steps. I also tried switching the Authorization type option to 'Bearer' after acquiring a new token and it returns a 403 Forbidden (and on one occasion returned a 401 Unauthorised error).

Are we missing any extra credentials? Or maybe our IP is being blocked?

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG and @hakJav, I'm sorry to hear you're still experiencing issues. I can't work out why this is happening and will need to troubleshoot with one of our senior developers. He's not in the office today but have a chat to him first thing tomorrow. Thanks.

**Comment by hakJav** [comment]
Cool thanks @matthewrgourd - and thanks for taking the time to send the screenshots above. Please let your senior dev know this is an urgent issue.

**Comment by VizuaaLOG** [comment]
@matthewrgourd Bearer is selected. I'm also seeing the same issue using the Javascript API.

Agree with @hakJav about this being an urgent issue. Look forward to hearing from the senior dev.

**Comment by matthewrgourd** [comment]
I have raised with the dev, please await his response which I'm sure will be coming shortly.

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG and @hakJav, I've spoken to the senior dev and we discussed a potential solution whereby I send you individual client credentials by email. You should use these in place of any shared credentials as we think this is what's causing the 403 error. Please can you email mgourd@vivawallet.com with the following info and I'll generate individual client ids / secrets for you in the next 30 minutes:

- Viva Wallet account name
- **demo** merchant id
- return email address.

Thanks, and sorry for any inconvenience caused!

**Comment by hakJav** [comment]
Thanks, just sent across an email.

**Comment by VizuaaLOG** [comment]
@matthewrgourd Sorry for the late response was tied up with another project yesterday. I've just sent across an email from my work email (tom@dimen********.com).

Thanks for your help so far with this 👍

**Comment by VizuaaLOG** [comment]
@matthewrgourd Thank you for your email, the credentials specific to my demo account to seem to be working now.

A question on a related topic though, what is the reason for having to go through support to get these credentials? All other payment vendors I've used provide these details on the dashboard in some way. Am I able to requests credentials on behalf of our client that is using your platform (this is why I have the demo account) or do they need to put a support request in? As seems like potentially a long wait for a response.

Thanks for your help with this though! I can now continue testing lol

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG I understand completely what you're saying. Rest assured that the dashboard facility you mention is on the product roadmap. In the meantime, please use this GitHub issues board to get in contact with our development team or myself. Thanks!

**Comment by hakJav** [comment]
@matthewrgourd - received the new client credentials, but now I'm constantly getting a 401 Unauthorised error instead of a 403. Have the credentials expired? Do I need to do anything in my account to enable it?

**Comment by matthewrgourd** [comment]
Hi @hakJav you use the client credentials to [request an access](https://developer.vivawallet.com/api-reference-guide/authentication-methods/#step-1-request-access-token) token. This has a time limit of one hour so you have to keep on renewing. Hope this helps!

**Comment by hakJav** [comment]
Yes I'm aware of that and that's what I did - I generated a fresh access token using the new credentials, yet now I'm getting a 401 (whereas last time with the old credentials it was a 403).

My question was if the new credentials I was given have expired? Or if there's anything else I need to do to enable it?

**Comment by hakJav** [comment]
**Update**: The _WWW-Authenticate_ response header keeps stating:
> Bearer error="invalid_token", error_description="The token is expired"

I deleted ALL saved access tokens and generated a new one, so it's definitely not expired, yet your server is stating it is. Not sure if it makes a difference as the server should only be using UTC, but I'm situated in the UK, completely different timezone to Greece.

**Comment by matthewrgourd** [comment]
Hi @hakJav , I'm sorry to hear that. Please can you send the client credentials for me to check. The same email address as before: mgourd@vivawallet.com Thanks!

**Comment by hakJav** [comment]
Sent!

**Comment by matthewrgourd** [comment]
Works fine for me with https://demo-api.vivapayments.com/nativecheckout/v2/chargetokens The credentials have not expired. If you've got to the stage of [creating a payment order](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-5-create-a-payment-order) remember you'll need to switch to basic authentication with your demo merchant ID and API key as the credentials. Hope this helps!

**Comment by hakJav** [comment]
Still doesn't work, kept saying Bearer tokens were expired seconds after I generated them.

However, now I can't even simply generate an access token. OAuth2 now times out with a 504 Gateway Time-out error, even though I could get a Bearer access token before.

That's two problems now that prevent me from integrating VivaWallet.

Matt, this is getting ridiculous. Why are there so many problems? Is this still in Beta? Has it not been properly tested??

**Comment by matthewrgourd** [comment]
Hi @hakJav Sorry to hear that, it appears we were having problems with the demo environment which should be back up and running now.
