### ISSUE TITLE
Εμφάνιση φόρμας πληρωμής σε ληγμένη συναλλαγή 

### ISSUE THREAD

**Issue by nplion** [VivaPayments/API#927]
Ενώ η συναλλαγή έχει λήξει, πατώντας το link, ανοίγει σελίδα της Viva με την φόρμα πληρωμής, πάνω στην οποία γράφει την ημερομηνία λήξης  Νομίζω πως πρέπει απλά να εμφανίζει το μήνυμα ότι η εναλλαγή έχει λήξει χωρίς την φόρμα, γιατί ο πελάτης μπορεί να μην δει το μήνυμα με ημερομηνία λήξης και να προχωρήσει στην πληρωμή.

**Comment by matthewrgourd** [comment]
Hi there, is this a request for support or a new feature request? Please can you elaborate on the issue (in English if possible) as I'm not sure I fully understand it!
