### ISSUE TITLE
Pending Payments

### ISSUE THREAD

**Issue by rsanota** [VivaPayments/API#928]
Hi,

I have just started using VivaWallet with my new website www.hemptree.co.uk and alot of my orders shown on my website are just pending. With no record of the order showing on my Vivawallet account when I login.

Why am I getting so many pending payments?

**Comment by VivaWalletSupport** [comment]
Hello, assuming you are using the plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce could you provide some more details like, do you receive any orders that are paid with Viva and have a correct order status, is there a certain pattern in the failed orders (example using another currency) and did you try a payment yourself?

**Comment by rsanota** [comment]
Yes I am using the plugin you advise.

Customers are advising they are getting error messages when trying to place an order - but then receiving order confirmation  by email, however our website indicates that the order is pending and no payment is received.

Please investigate.

Kind regards,

Ranjeet

**Comment by VivaWalletSupport** [comment]
Hello Ranjeet, please try to answer my previous questions:
Do you receive any orders that are paid with Viva and have a correct order status, is there a certain pattern in the failed orders (example using another currency) and did you try a payment yourself?
Besides that, what exact error messages do the customers get and at what location (at Viva or in the store after returning).

**Comment by rsanota** [comment]
Yes I have received orders since, the orders with errors are UK based and from Finland - I attempted a payment myself and it did go through.

Customers have emailed the following : 

*****************************************************

Hello Ron,

The message on the website said there was an error after I entered payment details and clicked place the order.
I completed the page again and it came back with page "Error" on it. I closed the browser and when opened again,
I got an email confirming the order.

I did not cancel it. Will the gummies (2) be sent soon or are you out of stock?


Thanks
Katherine

PS no emails about cancelling anything

***********************************************************************

Hi,

I was trying to place an order, but for some reason my payment doesn't seem to go through. After I have identified myself in my online bank and try to verify the purchase, I'm redirected to this website vivapayments.com. This is just a blank page and doesn't go anywhere from there.

Best regards,

Jenni Sironen


********************************************************

Hi yes ,,,
First it said payment failed then a box came up saying payment successful , order complete?

Regards Matt

*************************************************************

**Comment by VivaWalletSupport** [comment]
Unfortunately the error reports from your clients are not very helpful as they are not detailed enough (what exact error was shown on what location). Also you still did not inform me if you receive any **orders that are paid with Viva and have a correct order status** (in the stores backoffice). Please test a payment yourself and inform me in detail what problem occurs (tip: use screenshots to clarify).

**Comment by rsanota** [comment]
Yes I have had orders going through correctly with the right order status.

I have tested the viva payment myself and it was fine

**Comment by VivaWalletSupport** [comment]
Does the store use multiple currencies or only GBP?
