### ISSUE TITLE
Error κατά το checkout σε Shopify

### ISSUE THREAD

**Issue by pvoulg** [VivaPayments/API#929]
Καλημέρα, 

Παρατηρείται από το πρωί ζήτημα σε Shopify eshop πελάτη μας όταν ορισμένοι πελάτες προσπαθούν να καταχωρήσουν παραγγελία και επιλέξουν ως τρόπο πληρωμής την Viva (βλ. attached). 

Βγαίνει μήνυμα error, σε κάποιες περιπτώσεις, ενδεικτικά στα screenshots από Firefox/Windows και Safari/iOS. Αντίστοιχα δεν παρατηρείται το ίδιο σε Firefox/MacOS και Chrome/Windows.

Παρακαλώ δείτε το άμεσα, καθώς βρισκόμαστε σε περίοδο εκπτώσεων και υπάρχει αυξημένος όγκος παραγγελιών. Ευχαριστώ.

![1](https://user-images.githubusercontent.com/7416221/60874645-04495700-a241-11e9-8c81-d3d6e433146a.png)
![Image from iOS](https://user-images.githubusercontent.com/7416221/60874671-0c08fb80-a241-11e9-9755-bd58fd626735.png)

**Comment by matthewrgourd** [comment]
Hi there, in case you've not done so already, please follow the guide at https://developer.vivawallet.com/e-commerce-plugins/shopify/
Let us know if you're still experiencing after that. Thanks!
