### ISSUE TITLE
Απόδειξη στα Αγγλικά και εμφάνιση ποσού σε λίρες Αγγλίας

### ISSUE THREAD

**Issue by stefansxxl** [VivaPayments/API#93]
Καλημέρα, έχω ένα site e-shop, που πουλάει μόνο σε Αγγλία και έχω 2 προβλήματα: 
1ον η απόδειξη πληρωμής που φτάνει στον πελάτη με mail, μόλις γίνει η πληρωμή είναι στα Ελληνικά, και 
2ον, ο πελάτης χρεώνεται λίρα, άρα πρέπει να δει λίρα μέσα στην απόδειξη και όχι ευρώ.

**Comment by defilerc** [comment]
Καλημέρα @crisxz,

Η απόδειξη εκδίδεται στη γλώσσα δημιουργίας του order. Κατά τη δημιουργία του order, μπορείτε να περάσετε την extra παράμετρο RequestLang=en-US, έτσι ώστε όταν πληρωθεί, η απόδειξη πληρωμής να γίνει στα Αγγλικά. Περισσότερες πληροφορίες για τη δημιουργία του order, μπορείτε να βρείτε εδώ: https://github.com/VivaPayments/API/wiki/CreateOrder

Τέλος, η χρέωση στον πελάτη γίνεται σε Ευρώ, επομένως η απόδειξη πληρωμής εκδίδεται σε Ευρώ.

Ευχαριστούμε για την επικοινωνία
