### ISSUE TITLE
Viva Wallet Shopify Plugin Issue (Token Not saving)

### ISSUE THREAD

**Issue by THCLDN** [VivaPayments/API#930]
Please can anyone help...

I have been given this link to follow:
https://developer.vivawallet.com/e-commerce-plugins/shopify/

I have also filled in the form and received my merchant ID and Token, when i click installed it didnt show any section for credit card providers, i had to go through 3rd party. It says my account is active but the token will not save, can anyone advise me please. 

Many Thanks

**Comment by matthewrgourd** [comment]
Hi there, during installation, have you opened http://www.shopify.com/admin/authorize_gateway/1041324 in the same browser window that you used to log in to Shopify? After you have done so, follow step 6 onwards in the [guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/). Let me know how you get on. Thanks.

**Comment by THCLDN** [comment]
Hi there, 

I have followed all steps, i have viva wallet installed but the token is not saving?

**Comment by matthewrgourd** [comment]
I'm not sure I understand what you mean by "token is not saving". Please can you send a screenshot or two taking care to obscure the token / any other private details. Thanks.

**Comment by THCLDN** [comment]
Hi, 

So i have followed the link provided and installed viva wallet, i have also put my merchant and token i had received via email from Viva Wallet. 

I had contacted shopify to ask if it was correctly integrated, the customer service said "They could not see any token saved, but i had received an email from them saying new payment method saved and set up. So i wanted to know how would i knot its correctly installed, and if the token has saved?

Please find pictures attached.

![Screen Shot 2019-07-10 at 16 49 34](https://user-images.githubusercontent.com/52712701/60984398-8c0f8e00-a333-11e9-80d9-13f0729a677e.png)
![Screen Shot 2019-07-10 at 16 49 53](https://user-images.githubusercontent.com/52712701/60984399-8c0f8e00-a333-11e9-8163-a980416fd7c4.png)

**Comment by THCLDN** [comment]
HI, 

Seems like i done everything, just ran a test order and so far so good, i will now close this matter and if i have any more questions or need any help i will be sure to open a request. 

Kind Regards
