### ISSUE TITLE
Eshop JoomDonation -Viva Plugin. Problem. The Order doesnot complete after payment

### ISSUE THREAD

**Issue by kostasmultimedia** [VivaPayments/API#931]
Good evening
I have this site: www.corc.gr
I have the eshop Platform from JoomDonation.
Everything works fine using Paypal. 
I decided to use Viva Payments. Because of my customeres need to use Credit Cards in my site 
. There i created a account. I made a merchant account. It was easy.
The Vivawallet after hours confirmed that and i was OK .
I follow the instructions and i installed viva Plugin and i filled the data as Viva site adviced.
After the order the redirecion to Viva Payments Platform and the payment works and i see the transaction results. 
After  there are serious problems. It seems the cart does nt reset after the payment.
The Eshop Platform does not send notification to Admin and to Customer...
It seems as the order doesnot completed.
If you can help me.

If you want i could attach and screenshots 

Thank you

**Comment by VivaWalletSupport** [comment]
Hello, please use the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/joomdonation-eshop/ and provide the following 4 screenshots:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by kostasmultimedia** [comment]
Goodmorning
I installed and i use thethe supported plugin JOOMDONATION ESHOP.
The eshop website works perfectly using paypal... But not using Viva Payments plugin..
I include the screenshots with titles.
I hope you understand the problem
Yours Sincerelly
![00-MY-ESHOP-SITE](https://user-images.githubusercontent.com/44064185/60957097-bdc12e80-a30c-11e9-99f6-58d060334c8f.jpg)
![01-MYVIVA-SETTING-MERCHANT](https://user-images.githubusercontent.com/44064185/60957098-be59c500-a30c-11e9-8bac-4162f74aff51.jpg)
![02-VIVA-INSTRUCTIONS](https://user-images.githubusercontent.com/44064185/60957099-be59c500-a30c-11e9-92be-31772ad2898b.jpg)
![03-VIVA-INSTRUCTIONS](https://user-images.githubusercontent.com/44064185/60957100-be59c500-a30c-11e9-9ee8-8fc782f377b2.jpg)
![04-SETTING-VIVA-PAYMENT-SOURCE-APP](https://user-images.githubusercontent.com/44064185/60957102-be59c500-a30c-11e9-9600-a4c93d04c643.jpg)
![05-VIVA PAYMENT PLUGIN JOOMLA-ESHOP-JOOMDONATION](https://user-images.githubusercontent.com/44064185/60957104-bef25b80-a30c-11e9-979e-7279aaab4d22.jpg)
![06-ERROR-AFTER-PAYMENT-SITE](https://user-images.githubusercontent.com/44064185/60957105-bef25b80-a30c-11e9-849f-25dec36d7d42.jpg)
![07-OK-VIVA-AFTER-PAYMENT](https://user-images.githubusercontent.com/44064185/60957106-bf8af200-a30c-11e9-8505-ac619765067e.jpg)
![08-ERROR-ORDERS-ESHOP-JOOMDONATION](https://user-images.githubusercontent.com/44064185/60957107-bf8af200-a30c-11e9-854a-4d590b64a752.jpg)
![09-BLANK-EMAIL-NOTIFICATION TO ADMIN-CUSTOMER](https://user-images.githubusercontent.com/44064185/60957108-bf8af200-a30c-11e9-908d-2f99f4c59909.jpg)

**Comment by VivaWalletSupport** [comment]
I updated the code at https://github.com/VivaPayments/API/blob/master/Plugins/joomla/joomdonation_eshop/os_viva/os_viva.php

Please uninstall / remove current plugin and use the latest version. Close this issue in case that solves the problem, otherwise let me know.

**Comment by kostasmultimedia** [comment]
EVERYTHING IS OK NOW
THANK YOU VERY MUCH

**Comment by VivaWalletSupport** [comment]
Great to hear so, please close this issue in case it is no longer needed.
