### ISSUE TITLE
European directive PSD2 (3D Secure and SCA)

### ISSUE THREAD

**Issue by nlabiris** [VivaPayments/API#932]
Hello,

At the moment, we have integrated Viva's Payment API that we are using for quite a long time now and we have experienced no issues.

From a technical standpoint, we are using the following endpoints to complete payments.

1. POST /api/orders

We create an order code and then we are using the redirect checkout (https://developer.vivawallet.com/online-checkouts/redirect-checkout/) to allow the user enter their card details at Viva's payment form.

After creating the payment order, we redirect the customer to the Viva Wallet checkout page: /web/checkout?ref={OrderCode}

They also need to check the option to allow recurring payments, that exists on the form, in order to allow us to create recurring payments for seamless user experience when a payment is needed.

2. POST /api/transactions/{TransactionId}

We use this endpoint to make recurring transactions (if the user has allowed that) at a later stage and if the following conditions are met.

- The cardholder has already been charged succesfully in the past
- The cardholder has agreed on allowing recurring payments on their card

Will there be any changes in the integration process and the operations that we have already implemented due to the activation of the European directive PSD2 regarding 3D secure and Strong Customer Authentication (SCA)?

Than you in advance.

**Comment by matthewrgourd** [comment]
Hi there, I believe that SCA will be in place at Viva Wallet from September 2019. Yes, we expect some minor changes in the integration process, but we'll ensure these are communicated to you in advance of the switchover. Thanks for raising this as an issue. Your feedback is noted.

**Comment by drakakisgeo** [comment]
Any news? Its September and the deadline in 3 days.

**Comment by nlabiris** [comment]
From what I know, there is a deadline in place until 03/2021. But in order to be ready for that we told that we need to implement the [Native Checkout v2.0 3DS](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) method

**Comment by matthewrgourd** [comment]
Hi @drakakisgeo, sorry for the delayed reply. We are ready for the SCA requirement and you can find further details here: https://developer.vivawallet.com/online-checkouts/migrating-from-native-checkout-v1/ Basically it is being covered by 3DS. Hope that helps! Thanks.
