### ISSUE TITLE
Payments do not go through; not being processed

### ISSUE THREAD

**Issue by GreenGreen31** [VivaPayments/API#934]
Hello,

I have had an issue with taking payments with vivawallet since last week. After you enter your card detail, and the payment begins to load, it takes me back to my website checkout page with this error messgae 

"error occurred, please try again".

This has been the issue for more than 10 customers. 
![APIPAGE](https://user-images.githubusercontent.com/52738454/60962597-851e5680-a306-11e9-8550-a7dcebf32152.png)
![pluggin](https://user-images.githubusercontent.com/52738454/60962599-851e5680-a306-11e9-9ce5-30cd13b17b99.png)
![Profilesettingpage](https://user-images.githubusercontent.com/52738454/60962601-85b6ed00-a306-11e9-9428-6cd0ddfcbb6d.png)
![vivawebpage](https://user-images.githubusercontent.com/52738454/60962602-85b6ed00-a306-11e9-8e64-75846b20665e.png)

**Comment by VivaWalletSupport** [comment]
Hello, could it be that your changed your sites protocol from http to https since last week? You would need to adjust the protocol in the payment source to https in that case.

**Comment by GreenGreen31** [comment]
Hello,

What payment source do you refer to because I’ve changed it to https on
viva wallet and I’m still receiving the same error.

Looking forward to hearing from you.

Thank you

**Comment by VivaWalletSupport** [comment]
https://user-images.githubusercontent.com/52738454/60962602-85b6ed00-a306-11e9-8e64-75846b20665e.png

Regarding the failed orders showing the message "error occurred, please try again", the transactions also failed (no money received in your Viva account)?

Could you try yourself to make an order / transaction and report the outcome?

**Comment by GreenGreen31** [comment]
Hello,

No money was received in my account.

This is really stressing me out. The same error keeps happening.

**Comment by VivaWalletSupport** [comment]
Could you try yourself to make an order / transaction and report the outcome?

**Comment by GreenGreen31** [comment]
Hello,

I just tried, the viva wallet page appears then it takes me back to my
page. Same error.

**Comment by VivaWalletSupport** [comment]
What amount did you try with?

**Comment by GreenGreen31** [comment]
I tried making a payment on £16

**Comment by VivaWalletSupport** [comment]
Setup the plugin with the viva demo environment and try a transaction with the provided test card to verify the correct working of the plugin.

**Comment by GreenGreen31** [comment]
Can you please help me with the process of getting this setup done.

**Comment by VivaWalletSupport** [comment]
Just repeat the instructions and setup an account at https://demo.vivapayments.com/en/signup
Update your plugin settngs and configure it to use the test mode.

**Comment by GreenGreen31** [comment]
Hello,

The same error happened again

**Comment by VivaWalletSupport** [comment]
Can you provide a link to a test product that I can purchase using your demo connected setup?

**Comment by GreenGreen31** [comment]
https://www.mynetdoctor.co.uk/checkout/

djgreengh@gmail.com
green

**Comment by GreenGreen31** [comment]
that's the link, you can log in with the details provided

**Comment by VivaWalletSupport** [comment]
Please update the code in wc-vivawallet.php with the new from https://github.com/VivaPayments/API/blob/master/Plugins/wordpress/vivawallet-for-woocommerce/wc-vivawallet.php before I make the test and inform me when done.

**Comment by GreenGreen31** [comment]
where is that code located

**Comment by VivaWalletSupport** [comment]
[vivawallet-for-woocommerce.zip](https://github.com/VivaPayments/API/files/3382545/vivawallet-for-woocommerce.zip)

**Comment by GreenGreen31** [comment]
should I just download this new zip instead as im not able to open the php file

**Comment by VivaWalletSupport** [comment]
Download the zip and use the new wc-vivawallet.php file to replace your existing one, it has a mod for the demo environment. You might also use the zipped package to install the plugin again from scratch (after uninstalling current plugin).
