### ISSUE TITLE
Prestashop 1.7 module not working

### ISSUE THREAD

**Issue by tagadmin** [VivaPayments/API#935]
Hi,

Installed the prestashop module for 1.7.

All payment attemps end up with the browser displaying a 404 Page not found error from the vivapayments website.

This is the URL the module is attempting to access :
https://www.vivapayments.com/web/newtransaction.aspx?Ref=

Needles to say, we cannot process any payments.

Best regards

**Comment by VivaWalletSupport** [comment]
Hello, please use the supported plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/prestashop/ and provide the following 4 screenshots in case the problem persists:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by tagadmin** [comment]
Hello,

Thank you for your reply.

I already had the supported module. Anyways, I deleted it, downloaded it again and configured it with the instructions.


Here are the screenshots:









This is the error while trying to create the webhook. The error is caused by the module on the server, below is the server error log :



Module is crashing when trying to access the webhook

Then for any transaction attempt we get always the same result :




Do ont hesitate to ask for more precisions if needed.

Thank you.

Best regards

**Comment by VivaWalletSupport** [comment]
Please post your screenshots at Github to be visible.

**Comment by tagadmin** [comment]
![Screenshot 2019-07-11 at 07 56 28](https://user-images.githubusercontent.com/52746824/61063939-238ee280-a401-11e9-93ba-c7bf9eafab6d.jpg)
![Screenshot 2019-07-11 at 07 59 01](https://user-images.githubusercontent.com/52746824/61063961-2b4e8700-a401-11e9-9231-da0e1973ff7f.jpg)
![Screenshot 2019-07-11 at 07 59 01](https://user-images.githubusercontent.com/52746824/61063971-2f7aa480-a401-11e9-9044-9f782e83b954.jpg)
![Screenshot 2019-07-11 at 07 59 41](https://user-images.githubusercontent.com/52746824/61063983-36a1b280-a401-11e9-9b4b-076f0416a072.jpg)
![Screenshot 2019-07-11 at 08 01 36](https://user-images.githubusercontent.com/52746824/61063991-3b666680-a401-11e9-8832-1be80943a35b.jpg)
![Screenshot 2019-07-11 at 08 01 49](https://user-images.githubusercontent.com/52746824/61063998-40c3b100-a401-11e9-821b-0fcd3f72bcc9.jpg)
![Screenshot 2019-07-11 at 08 01 00](https://user-images.githubusercontent.com/52746824/61064012-45886500-a401-11e9-99ce-98982c3f0ac8.jpg)
![Screenshot 2019-07-11 at 07 56 45](https://user-images.githubusercontent.com/52746824/61064023-4b7e4600-a401-11e9-8699-fdb984b8d33f.jpg)
Screenshots related to my previous post.

**Comment by VivaWalletSupport** [comment]
Please change your API key and try again, notice items in bold.

Payment module settings (**mask the API Key**).
Viva Wallet payment source settings **(include the browsers URL in the screenshot**).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (**mask API Key, include the browsers URL in the screenshot**).

**Comment by tagadmin** [comment]
Changing the API key made it work.

I jsut tried with my own card and it works.

Thank you.

**Comment by tagadmin** [comment]
Everything is working now, except :

When a payment is successful the status of the order on Prestashop is always set to "Cancelled", which is not good.
Redirections URL seems to be correct (see attached screen captures)

Best regards
![Screenshot 2019-07-20 at 09 10 56](https://user-images.githubusercontent.com/52746824/61575627-52c2e500-aace-11e9-815e-87d95dc050a6.jpg)
![Screenshot 2019-07-20 at 09 11 52](https://user-images.githubusercontent.com/52746824/61575635-70904a00-aace-11e9-9ce4-8f68aa016d60.jpg)

**Comment by VivaWalletSupport** [comment]
I would suggest to use the latest code from https://github.com/VivaPayments/API/tree/master/Plugins/prestashop/vivawallet and to test in demo mode to see what goes wrong, use the test card from Viva and an amount higher then 30 cents.

**Comment by matthewrgourd** [comment]
Hi @tagadmin, please let us know how you get on otherwise close the issue if you've got it working. Thanks!

**Comment by tagadmin** [comment]
Hi,

I cannot work on the production server. I am setting up a test machine that will be ready by tomorrow.

Thanks :-)

**Comment by tkardaridis** [comment]
I am facing the same issue. As soon as the customer press the Complete button i am getting the same 404 error as @tagadmin  tagadmin mention in his comment. Also the webhook cannot be verified. I download the latest code from github and install it but still i am getting the save error.

**Comment by matthewrgourd** [comment]
Hi @tkardaridis, this is a very old issue so your problem is unlikely to be the same as the one identified here. Can you let me know which version of PrestaShop you're using?

**Comment by tkardaridis** [comment]
Prestashop version is 1.7.6.8
Module version is the latest 1.7.8
I also change the API Key, just in case and because the @tagadmin mention that by changing the API Key the problem has been resolved, but no, unfortunately.

**Comment by matthewrgourd** [comment]
Hi @tkardaridis is this the first time you've attempted to install our plugin for PrestaShop 1.7? Di you obtain the latest version from the below page and follow all the instructions?

https://developer.vivawallet.com/e-commerce-plugins/prestashop1.7/

If the answer is yes to both those questions, please can I also have the website address of your store and a screenshot of your prestashop payment module settings with API key blurred out?

**Comment by tkardaridis** [comment]
As you asked for please check the issue #1981. I have all the screenshots there.
