### ISSUE TITLE
White Screen after enetering Card details

### ISSUE THREAD

**Issue by megabookkeeping** [VivaPayments/API#937]
Hello I am using WP website and installed plugin woocomerce
We have mentioned all details correct in plugins. But since 2 days clients are not able to pay. As soon as they enter credit /debit card numbers they redirect to a white screen. 
Kindly help asap.

**Comment by VivaWalletSupport** [comment]
Please confirm that the plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ is used and post a screenshot of this white page including the browsers URL.

**Comment by megabookkeeping** [comment]
Yes i am using the correct plugin from your given link. As of now i dont have any screenshot as my clients were trying to pay. Just wanted to know do we have to enable the native checkout option also. Because it was not enabled.

**Comment by VivaWalletSupport** [comment]
Could you try yourself to make an order / transaction and report the outcome, the specific plugin does not support Native mode.

**Comment by megabookkeeping** [comment]
As requested i tried and sending you the screenshot of the error
![Screen Shot 2019-07-11](https://user-images.githubusercontent.com/52752389/61024174-66819380-a3ca-11e9-81a4-5f5b654ab46f.png)

**Comment by VivaWalletSupport** [comment]
Correct the protocol in the Viva payment source you created from https to http as your site does not seem to support https. It is prefereable though to make your site work under the https protocol. Please close this issue in case that solved the problem.
