### ISSUE TITLE
Payment error

### ISSUE THREAD

**Issue by gham7** [VivaPayments/API#938]
I have tried on numerous occasions to test payments. Each time I process payment form WooCommerce cart the payment appears to go through but forwards to a blank page after taking payment.

**Comment by gham7** [comment]
![Screenshot 2019-07-10 at 20 32 11](https://user-images.githubusercontent.com/51792738/60998919-d6a00300-a351-11e9-8fd6-b1c61ba77050.png)

**Comment by VivaWalletSupport** [comment]
Hello, please use the supported plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ and provide the following 4 screenshots in case the problem persists:

Payment module settings (mask the API Key).
Viva Wallet payment source settings (include the browsers URL in the screenshot).
Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
API Access page (mask API Key, include the browsers URL in the screenshot).

**Comment by Pelapatate** [comment]
I have the same issue here. I would like to send you the requested screenshots, but it's not clear for me where to get all of them. Can you be a little bit more specific and provide a private mail where I can send them?

Thank you,

Giulio

![WhatsApp Image 2019-07-17 at 13 42 06](https://user-images.githubusercontent.com/53004157/61373912-591d4b00-a89b-11e9-8fa6-0080ad3e02d3.jpeg)

**Comment by Pelapatate** [comment]
Another piece of information you might need is: 
the first time my clients try to pay trough Vivawallet/woocommerce they always get the "-1" error. Afterwords, if they try again, they succeed on the second or third try.

**Comment by VivaWalletSupport** [comment]
Please see other issues for an example of the screenshots like https://github.com/VivaPayments/API/issues/943

In case you have a privacy concern for posting the images here, mask (partly) other info you do not want to share.

**Comment by Pelapatate** [comment]
Thanks for the info, 

> Hello, please use the supported plugin and instructions from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ and provide the following 4 screenshots in case the problem persists:
> 
> Payment module settings (mask the API Key).
![Screenshot 2019-07-17 15 19 52](https://user-images.githubusercontent.com/53004157/61379674-44937f80-a8a8-11e9-8bda-f8833e2615a0.png)
> Viva Wallet payment source settings (include the browsers URL in the screenshot).
![Screenshot 2019-07-17 15 26 02](https://user-images.githubusercontent.com/53004157/61379677-452c1600-a8a8-11e9-9867-cdfa5b1bc6bb.png)
> Viva Wallet Websites/Apps page, include the browsers URL in the screenshot.
![Screenshot 2019-07-17 15 25 55](https://user-images.githubusercontent.com/53004157/61379675-452c1600-a8a8-11e9-9f89-1923b6c9c536.png)
> API Access page (mask API Key, include the browsers URL in the screenshot).
![Screenshot 2019-07-17 15 28 35](https://user-images.githubusercontent.com/53004157/61379679-45c4ac80-a8a8-11e9-82eb-c897c4d378f5.png)

One of our client wrote me:
"I got the -1 about 3 times. But it worked once I clicked the email link again and loaded a fresh tab."

**Comment by VivaWalletSupport** [comment]
According to your screenshots you are not using the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ 

I would advise to contact the plugin developer for support in this case.
