### ISSUE TITLE
Test card details doesn't work

### ISSUE THREAD

**Issue by HackAfro** [VivaPayments/API#939]
When I attempt creating a transaction with the test card details on the demo account, I get an error saying `No card owner`. How can I resolve this issue as it is very urgent.

The test card information used are:

```
{
  "cvc": 111,
  "expirationMonth": 1,
  "expirationYear": 2020,
  "holderName": "John Doe",
  "number": "4111111111111111"
}
```

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear that. Please can you let me know whether you've referred to our [Developer Portal ](https://developer.vivawallet.com/)and if so, what page? Which base URL are you using for demo purposes? Thanks!

**Comment by HackAfro** [comment]
Thank you for the prompt response. Yes, I've been using the developer portal as a guide. The base URL I used for the request was `https://demo.vivapayments.com/api/` for payments. And `https://demo-api.vivapayments.com/acquiring/v1` for generating charge tokens.

**Comment by matthewrgourd** [comment]
Hi @HackAfro I have just recreated this myself and am getting the same result. Will report to our Development Team and get back to you when I have an answer.

**Comment by matthewrgourd** [comment]
Hi @HackAfro I've checked with our senior developer and it appears that the documentation is slightly misleading. I will be updating it shortly. In the meantime, can you try following [steps 1](https://developer.vivawallet.com/api-reference-guide/payment-api-details/card-tokenization/#step-1-get-charge-token-using-card-details), [4](https://developer.vivawallet.com/api-reference-guide/payment-api-details/card-tokenization/#step-4-create-an-order) and [5](https://developer.vivawallet.com/api-reference-guide/payment-api-details/card-tokenization/#step-5-execute-the-payment) on their own as 2 and 3 are optional if you need to store the card details. Thanks!

**Comment by HackAfro** [comment]
Those were the steps I followed. The steps 2 and 3 are required for us are we are storing the card token for future transactions. I ran into the issue following these steps.

**Comment by matthewrgourd** [comment]
Hi @HackAfro ok, understood. Is it possible for you to post the full request-response log?

**Comment by HackAfro** [comment]
Okay. Here's the response when I attempt creating a transaction:

```
{ Emv: null,
  Amount: null,
  StatusId: 'E',
  CurrencyCode: null,
  TransactionId: null,
  ReferenceNumber: null,
  AuthorizationId: null,
  RetrievalReferenceNumber: null,
  ThreeDSecureStatusId: null,
  ErrorCode: 400,
  ErrorText: 'No card owner',
  TimeStamp: '2019-07-12T15:58:34.0415555+03:00',
  CorrelationId: null,
  EventId: 0,
  Success: false }
```

Here's the transaction body:

```
 {
        OrderCode: 5554413799008351 ,
        SourceCode: 'default',
        CreditCard: {
          Token: '05FB1A1EBF41440FDF88A359C46645B6D1EE3EF5',
        },
      };
```

**Comment by matthewrgourd** [comment]
Hi there, the token you're using in the transaction body is a card token rather than a charge token. To convert into a charge token follow step 3 of the [Card Tokenization guide](https://developer.vivawallet.com/api-reference-guide/payment-api-details/card-tokenization/#step-3-get-charge-token-using-card-token). My response contained ctok_Ee9tR0I7Y5BzfGcjKN-P4OftZmE Please try this instead. Let me know what the outcome is.
