### ISSUE TITLE
CodeID

### ISSUE THREAD

**Issue by stelioscloudtech** [VivaPayments/API#94]
Hello , I am working on adding the vivawallet API on my site to receive payments and it asks for Merchant ID, API key and CodeID.. I have the first 2 but i dont know how to locate the CodeID..I asked on the vivawallet by phone but they redirected me to your forum.
I hope to a prompt reply. Thanks.

**Comment by stelioscloudtech** [comment]
( creating the vivawallet payment in the eCommerce System )

**Comment by dmihos** [comment]
Hi Stelioscloudtech
It seems you're using a third party plugin for the integration with Viva.
I'm afraid you'll have to ask the company that supports it about what the CodeId is.
It's not a terminology Viva uses.

I would guess it's the Source Code, but that's exactly that, a guess.
Please let us know if we can help more

**Comment by stelioscloudtech** [comment]
Καλησπέρα, 
Όπως είδα, παρέχετε support και στα ελληνικά, οπότε το προτιμώ..
Έχω ήδη αποστείλει ερώτημα σχετικά με αυτό στους ανθρώπους που φτιάχνουν το Plugin..
Έκαναν μία δοκιμή και πήραν το παρακάτω error :
![vivaerror](https://cloud.githubusercontent.com/assets/18618266/14780779/31225dca-0ae7-11e6-88a7-8a3485dae8e7.png)

Μπορείτε να με βοηθήσετε σχετικά ώστε να ενημερώσω και τους ανθρώπους που το φτιάχνουν?

Ευχαριστώ.

**Comment by stelioscloudtech** [comment]
Επειδή προσπαθώ να συμπληρώσω φόρμα της VIVA και ο ένας με στέλνει στον άλλον... Τώρα μου λένε να ανεβάσω εδώ το screenshot me to CodeID που μου ζητάει ι φόρμα, μπας και βρεθεί κάποιος να ξέρει τι είναι.. H Viva μου λέει ότι δεν ξέρει , πρέπει να απυθυνθώ σε εσάς, εσείς μου λέτε μία γνώμη χωρίς να είστε σίγουροι, ο προγραμματιστής μου λέει ότι είναι κωδικοί που δίνονται από την εταιρεία που θα δέχεται πληρωμές... Κι εγώ κάνω το μαλάκα τώρα και το πάιρνω από την αρχή...
Επικοινώνησα πάλι τηλεφωνικά λοιπόν με το viva support και με παρέπεμψαν πάλι σε εσάς ώστ να σας δώσω το screenshot από τη φόρμα ώστε να μου πείτε ΠΟΥ θα βρω το CodeID ....
Συγχωρείστε μου τα νεύρα, αλλά δεν ευθύνομαι για το μπαλάκι που μου πετάει μία ο ένας και μία ο άλλος.. 
![vivasettings](https://cloud.githubusercontent.com/assets/18618266/14782115/d7f686e6-0aef-11e6-9061-a591740faffa.png)

**Comment by dmihos** [comment]
Αφαίρεσα την εικόνα με τα στοιχεία διασύνδεσης. 
Παρακαλώ αλλάξτε **άμεσα** το ApiKey σας

Κατανοώ τον εκνευρισμό σας, αλλά, όπως είπα ήδη, πρόκειται για ορολογία των ανθρώπων που συντηρούν το plugin, γι'αυτό και δε μπορούμε να βοηθήσουμε.

Από το νέο screenshot που στείλατε, φαίνεται ότι πράγματι αναφέρονται στο SourceCode, οπότε δοκιμάστε να βάλετε τον κωδικό από τις πηγές που έχετε στο site σας (Οι πωλήσεις μου > Πηγές Πληρωμών > Κωδικός)

**Comment by flametonguez** [comment]
Για όποιον ακόμα ψάχνει το VivaPayments CodeId, είναι ένας κωδικός με 4 ψηφία που βρίσκεται μέσα στο Πωλήσεις->Online Πληρωμές->Websites/Apps. Εκεί θα βρείτε το website που έχετε καταχωρήσει, μέσα στα στοιχεία του θα βρείτε και το CodeId. Στο περιβάλλον της Viva ονομάζεται σκέτο "κωδικός".
![4](https://user-images.githubusercontent.com/48553568/54427417-1e57aa80-4723-11e9-8cbf-d18590fcd7e4.JPG)
