### ISSUE TITLE
viva payments - prestashop 1.7.5.1

### ISSUE THREAD

**Issue by VickyFrag** [VivaPayments/API#940]
εγινε η εγκατασταση του Module 
και απενενργοποιηθηκαν ολοι οι  τροποι πληρωμης
μολις απενεργοποιω το Module της viva
εμφανιζονται οι υπολοιποι τρόποι πληρωμης.

**Comment by VivaWalletSupport** [comment]
Hello, please check your error logs for the problem that is occuring. In case a 3rd party checkout, try with using Prestashops default checkout options.
