### ISSUE TITLE
Viva Wallet Redirecting/Returning EURO Currency to Shopify Order Confirmation Page

### ISSUE THREAD

**Issue by Stevstar** [VivaPayments/API#941]
Hi Guys,

We are having a huge issue with VIVA WALLET returning EURO currency to Shopify s Order confirmaiton page.

1. Settings in Shopify are all set to GBP
2. Orders in shopify show GBP
3. VIVA Wallet is set to Language English
4. Viva Wallet shows transactions in Sales dashboard as GBP

5.  URGENT ISUSSUE - Viva is passing order confirmation back to shopify as EURO!!!!!!!!!

Someone please help us fix this as we have over 500 orders in the system now and it is affecting our brightpearl integration adn showing orders to fulfill as 0.00 GBP revenue due to VIVA passing back to shopify EURO. So Fulfillent system does not recognize it as a GBP value and is posing 0.00 value amounts per order.

**Comment by matthewrgourd** [comment]
Hi there, sorry for the delay. Can you let me have your company name and website address, please, and I will investigate.

**Comment by matthewrgourd** [comment]
Hello again, details of your issue have been passed on to our Shopify plugin developer. He will have an update soon. Thanks and apologies for any inconvenience caused.

**Comment by Stevstar** [comment]
Name: Ignite International UK ltd

 

Website: Uk.ignitecbd.co

 

 

Thanks,

 

SF

**Comment by Stevstar** [comment]
Thank you Matthew!

 

 

Steven V. Friend

 

Director of Ecommerce | Ignite International, Ltd.

M: 217.841.0883 | E: steve@ignite.co

www.Ignite.co <http://www.ignite.co/>    <http://www.ignitecbd.co/> www.IgniteCBD.co

 


________________________________

 

CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure.

**Comment by matthewrgourd** [comment]
Hi there, I'm told by our Shopify plugin developer that your issue should be fixed now. No currency info. was being exchanged between the systems and he has made a change that will force the passing of currency in case this might help you. Please let us know if any further problems otherwise close this issue if you're happy. Thanks. Matt

**Comment by Stevstar** [comment]
Thank you. We will look at our current incoming orders and see if GBP is now passing.

 

Thanks,

 

 

 

 

Steven V. Friend

 

Director of Ecommerce | Ignite International, Ltd.

M: 217.841.0883 | E: steve@ignite.co

www.Ignite.co <http://www.ignite.co/>    <http://www.ignitecbd.co/> www.IgniteCBD.co

 


________________________________

 

CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure.

**Comment by ap1988** [comment]
Hi Matthew, 
We are having exactly the same problem. 
We have all our setting set to Pounds - but we are getting complains that at checkout symbols are being changes to dollars or euros. 

Company name: 60 Acres

Website - https://www.60acres.co.uk/

please help!

**Comment by Stevstar** [comment]
Hi @matthewrgourd , We also are seeing that we cannot refund customers in Shopify either: 

Displays "non refundable item" in shopify even when VW is set to allow refunds.

Will also be helpful fo ryou to share teh corrections you made to the prior issue for the community to see since it is a wide issue many users are seeing.

Thanks!

SF

**Comment by ap1988** [comment]
Hi Matthew, 
Quickly checking on the issue / request i made on 26 July in case it has slipped through the net. 
Many thanks
A

**Comment by matthewrgourd** [comment]
@Stevstar Please can you let me know if the original issue was solved. You said "We will look at our current incoming orders and see if GBP is now passing." What is your conclusion? Regarding the refund problem, please raise separately as a [new issue](https://github.com/VivaPayments/API/issues) with as much detail as possible and we'll take a look. Thanks!

**Comment by matthewrgourd** [comment]
Hi @ap1988 Is this issue still occurring? We applied a fix two weeks ago.
