### ISSUE TITLE
pending payment weekends

### ISSUE THREAD

**Issue by magicbus4** [VivaPayments/API#942]
Hello,

I use vivapayment at my eshop and my problem is that at weekends cant proceed the payment.
At order status i have pending and it never charge the buyer.
From Monday until Friday the payments proceed successfully.
The platform is virtuemart 3

**Comment by matthewrgourd** [comment]
I've checked with out plugin developer who says there are no known issues with the Viva Wallet / Virtuemart plugin. Please can you contact support on 020 3665 8171 and ask them to check your account. Thanks!

**Comment by matthewrgourd** [comment]
Sorry, that number should have been + 44 (20) 37347770.
