### ISSUE TITLE
Woocommerce - Transaction Failed Message 

### ISSUE THREAD

**Issue by divieshm** [VivaPayments/API#943]
Scenario:

i have installed plugin - API/Plugins/wordpress/vivawallet-for-woocommerce/ onto my wordpress website

I created website/Apps under sales 

Steps to reproduce error
in the woocommerce app i have imputed the details from VIVA WALLET

Assumptions
on the woocommerce site, i have added an item to my shopping cart and have clicked on shopping cart 

WHEN: I click pay now 
AND: I enter my payment info into the payment page 
THEN: I am redirected to vivawallet to enter Credit Card information
AND: my card gets approved
THEN: I am redirected to a Transaction Failed page
AND: Nothing appears on my vivawallet transaction OR in my woocommerce sales page

**Comment by VivaWalletSupport** [comment]
Hello, in case the card transaction was accepted, at least it would have to show in your Viva account under Sales. Try setting up and testing the plugin first with the demo account and use the demo card to verify the correct working.

**Comment by divieshm** [comment]
We used a demo account throughout the testing and developing process and it worked perfectly well.

It's only when switched to the live account it fails to work.

Thanks
Diviesh

**Comment by divieshm** [comment]
Any chance we can arrange that someone remote into my machine and confirm that it is setup as expected

**Comment by VivaWalletSupport** [comment]
Please provide the following 4 screenshots:

Payment module settings (**mask the API Key**).
Viva Wallet payment source settings (**include the browsers URL in the screenshot**).
Viva Wallet Websites/Apps page, **include the browsers URL in the screenshot**.
API Access page (**mask API Key, include the browsers URL in the screenshot**).

**Comment by divieshm** [comment]
How do i attach my images not appearing on here

**Comment by divieshm** [comment]
> Please provide the following 4 screenshots:
> 
> Payment module settings (**mask the API Key**).
![Payment module Setings](https://user-images.githubusercontent.com/48175171/61315523-dc389580-a7f6-11e9-8177-49feafbd6d1b.jpg)

> Viva Wallet payment source settings (**include the browsers URL in the screenshot**).
![payment source](https://user-images.githubusercontent.com/48175171/61315546-e5c1fd80-a7f6-11e9-9698-e0a1a55677b8.jpg)

> Viva Wallet Websites/Apps page, **include the browsers URL in the screenshot**.
![website-apps](https://user-images.githubusercontent.com/48175171/61315555-ebb7de80-a7f6-11e9-869c-1a689f790372.jpg)

> API Access page (**mask API Key, include the browsers URL in the screenshot**).
![API Access page](https://user-images.githubusercontent.com/48175171/61315568-f1adbf80-a7f6-11e9-922c-84e169818961.jpg)

**Comment by VivaWalletSupport** [comment]
Please see step 1 - point 4 on how to configure your payment source:
https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

Please close this issue in case that solved the problem.

**Comment by divieshm** [comment]
All working thank you

**Comment by craigb88** [comment]
I'm having the same issue. 
I've tried uninstalling the plugin and resetting it up following all the steps but no payments are going through.

I get the verified card page on Viva then I get redirected back to my website with the error message "An error occured, please try again."
