### ISSUE TITLE
Shopify Re-direct at payment and € showing in confirmation

### ISSUE THREAD

**Issue by MichaelSourceCBD** [VivaPayments/API#945]
Hi There,

The following message appears when in developer mode "It looks like this page is redirecting to a page that isn't compatible with this editor. To ensure that your redirect doesn't interfere with the editing experience, replace window.location.href = with window.top.location.href = in your theme's JavaScript over here."

Also the page does not re-direct / when using the site as a customer takes to viva wallet and displays the message "store not found"

Also on payment confirmation € are shown when all other settings are in £

**Comment by matthewrgourd** [comment]
Hi there, we have recently fixed an issue relating to currencies. Please ensure you follow the installation instructions on our [Shopify page](https://developer.vivawallet.com/e-commerce-plugins/shopify/) and get back to us if any further problems. Thanks!
