### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by johsamo** [VivaPayments/API#949]
Working on local server docker ubuntu 18.04 firefox latest demo
Even before submiting, while I input card's info I get message "VivaPayments: error", ando on the console:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://demo.vivapayments.com/api/cards/installments?key=gH7jQPDJIwEBzD1X52HixHamY9SVFKBZxu0d4farMlg%3D. (Reason: CORS request did not succeed).
Pls Help
Thanks in advance

**Comment by matthewrgourd** [comment]
This [Medium post](https://medium.com/@xinganwang/a-practical-guide-to-cors-51e8fd329a1f) on CORS may help. Let me know if not!
