### ISSUE TITLE
Custom variables

### ISSUE THREAD

**Issue by chgiak** [VivaPayments/API#95]
Is it possible to pass custom variables on order create and have them back on success redirect from viva wallet?

**Comment by dmihos** [comment]
Hi chgiak
You can use [Order Tags](https://github.com/VivaPayments/API/wiki/Optional-Parameters) during CreateOrder and then [GetTransactions](https://github.com/VivaPayments/API/wiki/GetTransactions) on your success/failure urls to get them back
