### ISSUE TITLE
URGENT REDIRECTION NOT WORKING

### ISSUE THREAD

**Issue by wraithinator** [VivaPayments/API#950]
Getting a bit annoyed now. I'm a little techy but no coder. We finally get most of it working but after the customer makes a payment it doesn't go to the thank you page it goes to a page which is blank and has a -1. We followed all the steps listed here: https://developer.vivawallet.com/e-commerce-plugins/woocommerce/?fbclid=IwAR0KHZb8saaeGClAmAOtoOaxYXGdkdQJ0Y07MKBPcwpSvyRDNuw2BPtiPec

We followed this to the letter. And it still doesn't work. We are using it with wordpress and woocommerce. Our woocommerce version is 3.6.5. PHP version 7.2.19. vivawallet plugin version 1.3.2. Please get back to me as soon as possible.

![1](https://user-images.githubusercontent.com/53062621/61538581-9f0c1780-aa31-11e9-8629-095f2bb875a7.png)

![IMG-20190623-WA0001](https://user-images.githubusercontent.com/53062621/61538674-cebb1f80-aa31-11e9-9766-d864e25154fe.jpg)

**Comment by VivaWalletSupport** [comment]
Hello, you seem to be using a 3rd party plugin, you would have to follow their setup instructions in that case.

**Comment by matthewrgourd** [comment]
Hi @wraithinator Apologies, our official plugin isn't available yet via the Wordpress plugin directory. I think you have downloaded this extension which we don't officially support https://wordpress.org/plugins/woo-payment-gateway-for-vivapayments . We will soon be adding ours to the directory which should avoid any confusion. In the meantime you can download it from here if you wish: https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip. Thanks!
