### ISSUE TITLE
Quick one - Webhook url verification?

### ISSUE THREAD

**Issue by shahzaibmuneeb** [VivaPayments/API#951]
I see there are other issues on it but I can't seem to figure it out - the documentation links all lead to the github page which says:

> Announcement!
The Viva Payments wiki has been deprecated and content moved to the new Viva Wallet Developer Portal. There you'll find updated help content on how to integrate your website, application, blog, or e-commerce store with Viva Wallet.

And I can't seem to find it in the new docs? I basically see that the thank you redirect does not pass any query parameters (btw is this how it's meant to be?) with the order/transaction detail so  I cannot confirm payment and am looking to set it up with the webhook feature.

**Edit:**
Forgot to mention my main question - I'm trying to add a webhook url my Lambda function (behind API Gateway) and when I try to add the url it says:

> The url could not be verified. Please make sure you have entered a valid, publicly available, url that conforms to `[these guidelines](https://github.com/VivaPayments/API/wiki/Webhooks)` (Error code 502)

What is the whole process of adding a webhook end to end and is there documentation on it that I am just missing?

Thanks

**Comment by matthewrgourd** [comment]
Hi there, I'm sorry to hear you're experiencing issues. The section on webhooks is here in our developer portal: 

https://developer.vivawallet.com/api-reference-guide/payment-api-details/#webhooks

Hope this helps!

**Comment by shahzaibmuneeb** [comment]
Thank you that's very helpful. Seperately, is there no way to receive any data on the thank you page regarding the transaction the user just made?

**Comment by matthewrgourd** [comment]
Hi @shahzaibmuneeb, no problem. Regarding your other question, yes, if you're using Redirect Checkout: https://developer.vivawallet.com/online-checkouts/redirect-checkout/#step-3-confirm-the-transaction Thanks!
