### ISSUE TITLE
need client credentials for OAuth2

### ISSUE THREAD

**Issue by bcashmatix** [VivaPayments/API#952]
hi there

based on what you have on that link:
https://developer.vivawallet.com/authentication-methods/#identityserver-oauth2-authentication

_"_OAuth 2 token generation
Follow the steps below to generate a bearer token for use with our APIs. The token has a time limit of one hour after which it expires.

Step 1: Apply for client credentials
Before you can request an access token, you need to obtain client credentials from Viva Wallet. Please raise an issue via our public GitHub account and let us know whether you need demo or production access. We will email you back within 24 hours. If you’re requesting production access, it may take a little longer."__

i need credentials for demo and production in order to use OAuth2

as in order to get: Step 2: Request access token"

i need enter:
[Client ID]:[Client Secret]

which i dont have now in my vivawallet account

Please help me ( you can contact me via my email

**Comment by matthewrgourd** [comment]
Hi there, the process is we provide you with test credentials for use with the sandbox first. Once you're happy, I can apply for production credentials. Please email me at mgourd@vivawallet.com and I can deal with the first step. Thanks!

**Comment by matthewrgourd** [comment]
Hi @bcashmatix, I have sent through an update by email. Please send through your merchant ID and other business info by this method. Thanks!

**Comment by matthewrgourd** [comment]
You should have your demo credentials now. The request for production credentials has been put in. I'll let you know as soon as I've an update.

**Comment by bcashmatix** [comment]
thank you.
i am waiting.

‫בתאריך יום ג׳, 23 ביולי 2019 ב-12:21 מאת ‪matthewrgourd‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by matthewrgourd** [comment]
I'm sorry for the delay; I'll chase tomorrow if nothing by the end of the day.

**Comment by matthewrgourd** [comment]
Your client credentials are now available. Please see your email. Thanks!
