### ISSUE TITLE
Incorporate Image Cropper into Profile/Edit Profile/Backgrounds/Upload Backgrounds 

### ISSUE THREAD

**Issue by pitnik** [VivaPayments/API#953]
The Width:Height Ratio Needed here is 4.5!
![112233](https://user-images.githubusercontent.com/48185354/61661981-1cf04d00-acd6-11e9-812b-3081a87715a4.png)

**Comment by matthewrgourd** [comment]
Hi there, I think you've got the wrong issues board. This is for [Viva Wallet](https://www.vivawallet.com/en-eu/) technical problems. Thanks.

**Comment by pitnik** [comment]
Thank you so much and excuse me for the inconvenience.
