### ISSUE TITLE
Notification Bell when Receiving Messages! 

### ISSUE THREAD

**Issue by pitnik** [VivaPayments/API#954]
A "blink-blink" notification sound would be helpful as an alert for new Messages (maybe in conjunction with a red colored (## of messages) nest to TAB title, see attachment...
![112233](https://user-images.githubusercontent.com/48185354/61662514-3fcf3100-acd7-11e9-823f-be18dd5646cf.png)
)

**Comment by matthewrgourd** [comment]
Hi there, I think you've got the wrong issues board. This is for [Viva Wallet](https://www.vivawallet.com/en-eu/) technical problems. Thanks.

**Comment by pitnik** [comment]
Thank you for informing me and excuse me for the inconvenience.
