### ISSUE TITLE
Wordpress Vivawallet Demo - An error occured, please try again.

### ISSUE THREAD

**Issue by DanMaxwell101** [VivaPayments/API#955]
I have installed Vivawallet and followed the instructions to set it up with a demo account. When I submit an order after entering card details I am redirected back to the website but there is an error saying "An error occured, please try again. " There is no error code and I cant see any further errors anywhere. I have looked on here but nothing has helped.

**Comment by matthewrgourd** [comment]
Hi there, which of our solutions are you using? Is it an [online checkout](https://developer.vivawallet.com/online-checkouts/) or [e-commerce plugin](https://developer.vivawallet.com/e-commerce-plugins), or perhaps you're attempting to integrate directly with our [Payment API](https://developer.vivawallet.com/api-reference-guide/payment-api-details/)? Please provide further information including screenshots if appropriate.

**Comment by DanMaxwell101** [comment]
It's the E-commerce plugin. I can show screen shots of the settings pages.

![Screen Shot 2019-07-23 at 11 35 55](https://user-images.githubusercontent.com/53214760/61705667-2f05d600-ad3e-11e9-9d1e-cc925a9d77fc.png)

**Comment by matthewrgourd** [comment]
In the WooCommerce Payment settings can I just confirm you are definitely entering the Merchant ID, API Key and Source Code from your demo account at https://demo.vivapayments.com/en/signin ?

**Comment by DanMaxwell101** [comment]
Yes I am

**Comment by matthewrgourd** [comment]
Hello, please provide the following screenshots from your demo setup:

* [plugin settings](https://developer.vivawallet.com/e-commerce-plugins/woocommerce/#step-2-integrate-with-the-e-commerce-store) (mask the API Key)
* Viva Wallet [payment source ](https://developer.vivawallet.com/online-checkouts/create-a-payment-source/)settings (include the browser's URL in the screenshot).
* Viva Wallet [Websites/Apps page](https://developer.vivawallet.com/e-commerce-plugins/view-the-payment-source-list/) (include the browser's URL in the screenshot).
* [API Access page](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/) (mask API Key, include the browser's URL in the screenshot).

Thanks!

**Comment by DanMaxwell101** [comment]
Hi Matt, thanks for your help with this. Screen shots attached...

![plugin_settings](https://user-images.githubusercontent.com/53214760/61773513-c6c1fd80-adec-11e9-852c-ea1373df30be.jpg)
![payment_source](https://user-images.githubusercontent.com/53214760/61773514-c6c1fd80-adec-11e9-9733-7bb1ea85a099.jpg)
![Websites_Apps_page](https://user-images.githubusercontent.com/53214760/61773517-c6c1fd80-adec-11e9-868f-148eb7d09c55.jpg)
![API_Access_page](https://user-images.githubusercontent.com/53214760/61773520-c75a9400-adec-11e9-8a66-035540f30397.jpg)

**Comment by VivaWalletSupport** [comment]
Hi, what card data is used for testing and what amount? Also there is no need to enable native pay in your last screenshot.

**Comment by DanMaxwell101** [comment]
Various between £0.11 and £1.11. My personal card

**Comment by VivaWalletSupport** [comment]
You cannot use a live card in the demo environment and you have to use an amount of at least 0.30.
https://developer.vivawallet.com/development-environments/

**Comment by DanMaxwell101** [comment]
That's working now. Thank you very much for your help.
