### ISSUE TITLE
Linked Viva Wallet to shopify via guide - at checkout it gives error

### ISSUE THREAD

**Issue by aromaenergy** [VivaPayments/API#956]
Set up Viva Wallet as our payment provider on shopify.
Put in Merchant ID from our account
Used API key for store token (assumed this was right)
Test payments turned off.
Shopify accepted all this.
Went to do an order on the site, comes up with this error,
What am I missing?

![Error page when trying to pay](https://user-images.githubusercontent.com/53214641/61699264-7f773680-ad32-11e9-9c98-0181dfc50cbc.jpg)

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear about your issue. 

You need to request a store token by completing [this form](https://viva.microsoftcrmportals.com/shopify). Full instructions are given on this page on our developer portal:

https://developer.vivawallet.com/e-commerce-plugins/shopify

Hope this helps. Thanks!
