### ISSUE TITLE
Simple checkout with installments

### ISSUE THREAD

**Issue by Cristinawork** [VivaPayments/API#957]
Is it possible to use installments in the Viva Wallet simple checkout form?
is there something like  data-vp-installments ?

**Comment by matthewrgourd** [comment]
Hi there, I'm afraid not, for this use case you'd need to use our [Native Checkout 3DS](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/). Thanks!

**Comment by Cristinawork** [comment]
OK, thanks. But is it possible to set installments in the viva customer account, for example for more than 300 euro 2 installments, for 600 euro 3 installments and so on..

**Comment by matthewrgourd** [comment]
Hi there, are you talking about a Viva Wallet personal or business account. Personal accounts are only supported in Greece and I'm afraid I don't have an in-depth knowledge of them.
