### ISSUE TITLE
"The site is experiencing technical difficulties." message at checkout

### ISSUE THREAD

**Issue by Oanicica** [VivaPayments/API#958]
hello, merchant ROEM NOSIS SRL, https://amoshop.ro/, they always get this error. We tried as well on their website and got the same message. Can you help?

![4af6becc-757b-4068-bdab-585495f5a6ea](https://user-images.githubusercontent.com/53224411/61716137-270e5c00-ad67-11e9-9ab3-72656a37618a.jpg)

**Comment by matthewrgourd** [comment]
Sorry to hear that. Can the merchant provide details of the integration with Viva Wallet? Are they using one of our [e-commerce plugins](https://developer.vivawallet.com/e-commerce-plugins/) or [online checkouts](https://developer.vivawallet.com/online-checkouts/)? Unfortunately we can't help without more information. Thanks!

**Comment by Oanicica** [comment]
WORDPRESS
www.amoshop.ro/wp-admin
UserName: amoshop
PassWord: %8GLALR4Ly
:) this is what the merchant gave me

**Comment by matthewrgourd** [comment]
@Oanicica Thanks but I need to delete your reply from GitHub as it is a public forum. Please do not post this kind of sensitive information in the future. I have retained it in my email but we need to remove it from GitHub immediately. My question was simply what kind of integration with Viva Wallet has the merchant made, but I can see it is probably WooCommerce. Is that correct?

**Comment by matthewrgourd** [comment]
I gather this is a WooCommerce integration. Please provide the following screenshots from the merchant's setup:

* plugin settings (mask the API Key)
* Viva Wallet payment source settings*
* Viva Wallet Websites/Apps page*
* API Access page* (mask API Key)

*Include the browser's URL in the screenshot

Thanks!

**Comment by matthewrgourd** [comment]
Screenshots sent separately:

![Amoshop_3](https://user-images.githubusercontent.com/44943019/61778156-2244b900-adf6-11e9-8b96-1aa5b544be2c.png)
![Amoshop_2](https://user-images.githubusercontent.com/44943019/61778158-2244b900-adf6-11e9-920a-69857ead0ec1.png)
![Amoshop_1](https://user-images.githubusercontent.com/44943019/61778159-2244b900-adf6-11e9-87fe-b3a9a580f13e.png)

**Comment by matthewrgourd** [comment]
Apologies, closed in error. Reopened for @VivaWalletSupport to respond. Thanks!

**Comment by VivaWalletSupport** [comment]
Please provide the following screenshots from the merchant's setup, (re-)post items marked bold:
plugin settings (mask the API Key)
**Viva Wallet payment source settings***
**Viva Wallet Websites/Apps page***
**API Access page* (mask API Key)**
***Include the browser's URL in the screenshot**

**Comment by matthewrgourd** [comment]
@VivaWalletSupport I'm requesting this info now offline...

**Comment by matthewrgourd** [comment]
Hi @VivaWalletSupport the first URL is https://members.vivawallet.com/selfcare/en/sources/paymentsources?sourceTypeld=ae0e2b35-df43-4729-bd6d-a89a86ce3640  

and the second one is 

https://amoshop.ro/wp-admin/admin.php?page=wc-settings&tab=checkout&section=vivawallet

Hope this helps!

**Comment by VivaWalletSupport** [comment]
Please post the screenshots exactly as with previous issue https://github.com/VivaPayments/API/issues/955

**Comment by matthewrgourd** [comment]
You have the screenshots and below is 1 of 2 of the required URLs:

https://members.vivawallet.com/selfcare/en/sources/paymentsources?sourceTypeld=ae0e2b35-df43-4729-bd6d-a89a86ce3640

I believe the only outstanding item now is the URL for [viewing the payment source list](https://developer.vivawallet.com/e-commerce-plugins/view-the-payment-source-list/). Is that correct?

We're not able to send through any further screenshots I'm afraid.

Thanks.

**Comment by VivaWalletSupport** [comment]
Correct, in the payment source settings remove the www. part from the domain name as the site does not seem to use it. In the plugin settings check the Enable Test mode and uncheck it when using the credentials from the live account.

**Comment by Oanicica** [comment]
Hello, merchant says he already did these things and in Test mode it didn't work either.

**Comment by VivaWalletSupport** [comment]
In that case post the correct 4 screenshots as requested before (with browsers URL) for the demo   environment.

**Comment by Oanicica** [comment]
![2](https://user-images.githubusercontent.com/53224411/61854380-9d75a000-aec6-11e9-84dd-2002edeb7299.jpg)
![3](https://user-images.githubusercontent.com/53224411/61854381-9d75a000-aec6-11e9-97b5-2e31cfc1179b.jpg)
![4](https://user-images.githubusercontent.com/53224411/61854382-9e0e3680-aec6-11e9-87ef-10c6a690a1c2.jpg)
![1](https://user-images.githubusercontent.com/53224411/61854383-9e0e3680-aec6-11e9-91f1-a35cef5b943b.jpg)

Here they are.

**Comment by VivaWalletSupport** [comment]
Please re-post the first screenshot with only the API Key hidden, same for the last screesnhot and to include all settings.

**Comment by Oanicica** [comment]
Here they are: 
![Inkedfdf_LI](https://user-images.githubusercontent.com/53224411/61879394-9ddc5e00-aefb-11e9-8787-9acd906c6d59.jpg)
![InkedSettings_LI](https://user-images.githubusercontent.com/53224411/61879396-9e74f480-aefb-11e9-9315-5f1b35490d2b.jpg)

**Comment by VivaWalletSupport** [comment]
Thank you, could you please change the API Key in the Viva acount and in the module settings (take care no empty spaces occur) and let me know if the problem persists?

**Comment by Oanicica** [comment]
Hmmm, we change the API Key to what?

**Comment by VivaWalletSupport** [comment]
Somthing like Ab125S! but of cource not the same as this example.

**Comment by Oanicica** [comment]
I just put a random key and for two seconds i see the screen with "order approved", but then It give this error:
![image](https://user-images.githubusercontent.com/53224411/61883377-02e78200-af03-11e9-9d1d-dd8eb7e95127.png)

**Comment by VivaWalletSupport** [comment]
Just to verify, you did not change anything else, only the API Key in Viva and in the plugin settings?

**Comment by Oanicica** [comment]
I changed it only in the plugin settings, not in Viva....you mean the Viva Wallet account of the merchnat? Or in CRM? where exactly?

**Comment by VivaWalletSupport** [comment]
Just click on the current API Key https://user-images.githubusercontent.com/53224411/61879394-9ddc5e00-aefb-11e9-8787-9acd906c6d59.jpg

**Comment by Oanicica** [comment]
It's changed there already. Tell me where do we need to change it also and we will do it.

**Comment by VivaWalletSupport** [comment]
Besides in the Viva account you would also need to change it in the plugin settings https://user-images.githubusercontent.com/53224411/61879396-9e74f480-aefb-11e9-9315-5f1b35490d2b.jpg

**Comment by Oanicica** [comment]
it's changed in the plugin settings :) So I will tell the guy to change it in the account. thanks!

**Comment by Oanicica** [comment]
I changed the key in the account and tried again and it doesn't work. The same error. Please tell us what to do.

**Comment by VivaWalletSupport** [comment]
To have a look at it could you email wp-admin access + ftp credentials to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com ?

**Comment by Oanicica** [comment]
Is it ok if I send the email?

**Comment by matthewrgourd** [comment]
@Oanicica Yes, please go ahead. Thanks!

**Comment by Oanicica** [comment]
E-mail sent. Thanks!

**Comment by VivaWalletSupport** [comment]
Seems to be working now, you did not use the correct Source Code in the plugin settings.

**Comment by matthewrgourd** [comment]
@VivaWalletSupport The merchant wishes the payment page to be in Romanian. Do you have any advice to give?

**Comment by VivaWalletSupport** [comment]
https://github.com/VivaPayments/API/issues/898

https://developer.vivawallet.com/api-reference-guide/payment-api-details/#OP - Optional Parameters - Table - RequestLang

**Comment by matthewrgourd** [comment]
@VivaWalletSupport Please confirm that Romanian is not currently available in the plugin. My colleague needs to get back to the merchant with a clear answer! I gather from the provided link that the only two options are English and Greek. Is that correct?

**Comment by VivaWalletSupport** [comment]
Romanian and any other language are available in the plugin by making translations through the ecommerce software. According Viva's documentation it's API only supports Greek and English language on their payment page (that can be set by using the optional RequestLang parameter).
