### ISSUE TITLE
PCI Compliance

### ISSUE THREAD

**Issue by johnny1b1g** [VivaPayments/API#96]
Θα πρέπει να είμαστε **PCI Compliance** για να χρησιμοποιήσουμε το **Native Checkout** μέσα από τη **desktop εμπορική εφαρμογή** που έχουμε υλοποιήσει? Θέλουμε να πληρώνουν οι πελάτες μας μέσα από την εφαρμογή χωρίς να χρειάζεται να ανοίγουν browser και να χρησιμοποιούμε το Redirect Checkout?

**Comment by dmihos** [comment]
Όχι δεν απαιτείται να είστε PCI Compliant.
Ή Native Checkout, με τον τρόπο ακριβώς που περιγράφουμε στον οδηγό integration, εξασφαλίζει ότι δεν παίρνετε τα στοιχεία της κάρτας στον server σας, συνεπώς δεν απαιτείται να συμμορφώνεστε με τα PCI rules.
Ωστόσο, απαιτείται να σερβίρετε τη σελίδας σας με https.
