### ISSUE TITLE
WooCommerce: VivaWallet orders status skipping 'processing' stage

### ISSUE THREAD

**Issue by atomwise** [VivaPayments/API#962]
We have WooCommerce Vivawallet Gateway as a merchant service plugin for our WordPress site.

Our web orders feed through to Royal Mail's 'Click & Drop' shipping / postage system that allows us to generate pre-paid franking slips.

Our 'Click & Drop' system only receives order data (delivery address, product ID etc) when a WooCommerce order arrives in a 'Processing' status.

Since activating Vivawallet Gateway, all orders are apparently listed as 'Completed' in WooCommerce, meaning that no data is received by Click & Drop.  I can't find any reason for each order having skipped the 'Processing' status stage.

Previously, when we were using PayPal's WooCommerce plugin, we had no problem with this status shift.

Can anyone please help?

Cheers, 

Martin - Atomwise Ltd.

**Comment by VivaWalletSupport** [comment]
Hello, in case you are using the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/ please post a screenshot from the plugin settings (mask API key).
