### ISSUE TITLE
Card Tokenization

### ISSUE THREAD

**Issue by pavlidismi** [VivaPayments/API#963]
From the documentation, in Authentication methods (https://developer.vivawallet.com/authentication-methods/), when trying to complete step 2, the server returns an error 400: Bad Request.

As far as the credentials go, this error is reproducible in a demo account using the account's active client_id and client_secret. If instead of that, the generic credentials are given

> generic id: generic_acquiring_client.apps.vivapayments.com
> generic secret: generic_acquiring_client

then the request is able to continue and the payment happens.

However, the use of the generic credentials is only available for demo environments. So after moving to a non-demo account, using the account's proper credentials, I get the same response (400).

I have checked the base64 conversion and it looks to be correct (to test it I converted the generic credentials to base64 and got the correct string that is provided in the documentation).

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear you've been experiencing issues. When you say 'using the account's proper credentials' have you requested these as outlined in [step 1](https://developer.vivawallet.com/authentication-methods/#step-1-apply-for-client-credentials)? Please note that these are not the same as the client's merchant ID and API key which are used to access our other APIs.

**Comment by pavlidismi** [comment]
Hello, thank you for the fast reply!
If I understand this correctly, the "Merchant ID" and "API Key" under Settings -> API Access are not the proper client credentials to use for receiving the token? If so, I would need to request credentials for production access.

**Comment by matthewrgourd** [comment]
Hi there, no problem. 

That's correct, for card tokenization on production you initially need to request client credentials. Please send an email to mgourd@vivawallet.com with the following details:

* business name
* merchant ID (live)
* email address 

Thanks!

Matt

**Comment by pavlidismi** [comment]
Thank you, I will proceed with this, and once the credentials are ready, I will try again!

**Comment by matthewrgourd** [comment]
I have put in the client credentials request. I'll update you when I can. Thanks.

**Comment by matthewrgourd** [comment]
Client credentials supplied by email.
