### ISSUE TITLE
Prestashop 1.7.3 error payment

### ISSUE THREAD

**Issue by oldmanxxxv** [VivaPayments/API#964]
Hi there.
We try to implement this module for payment but we still encounter a strange problem.
We have installed the module and configured. We have created an account on vivapayments.com but somehow it doesn't work.
We have tested with an ING cards.
Everything it is ok till the moment when the service has to pull money from the account.
**Here are the steps:**
Put something in the cart and arrive on the payment checkout, choose Vivawallet for pay method.
The interface opens (https://www.vivapayments.com/web/newtransaction.aspx?Ref=!!!!!!!)
Input the card informations and click pay.
The module connects to ING and ask for the money.
The ING give me a sms with the authorization code.
I fill the autorization code into the window and it closes.
After that I'm redirected to the shop on a page where it says something wrong happened with the transaction. (There is no info about what happened)
In the admin area the order have status payment error.
When I check the ING account, no money are pulled.

So, where is the problem?

Thank you.

**Comment by oldmanxxxv** [comment]
OK. We have tried to use a different card from another bank.
Transaction was successful, flawless.
So the problem remains. 
How many banks will refuse a transaction coming from VivaWallet?

**Comment by matthewrgourd** [comment]
Hi there, apparently our third-party plugin developer already replied by email so I'm closing this issue. Please see a copy of his message below:

"As understood I do not see a problem with the payment module here (redirects to Viva to make the payment, redirects back to the store with the message that something went wrong with the transaction, bank confirms no transaction was made).
So I would suggest to have a Viva account manager / representative from ING to investigate why these transaction attempts failed. "

**Comment by oldmanxxxv** [comment]
Hi there.
As far as I know a new test with ING bank has been made and it was successful. 
Thanks!
