### ISSUE TITLE
oAuth 2 access request

### ISSUE THREAD

**Issue by christianago** [VivaPayments/API#966]
Hello,

I need client id and client secret for redirection API for use with sandbox and live

Regards

**Comment by matthewrgourd** [comment]
Hi there, sorry, I'm not quite sure what you're requesting. Is it Redirect Checkout you wish to use or something else. If the former, this uses [basic auth](https://developer.vivawallet.com/authentication-methods/#basic-authentication) so you don't need to request client credentials. You instead need to log in to your merchant account and check the API access page where you will [find your merchant ID and API key](https://developer.vivawallet.com/e-commerce-plugins/find-your-merchant-id-and-api-key/). These are used during authentication as your username and password respectively.

**Comment by matthewrgourd** [comment]
Hi @christianago Please email mgourd@vivawallet.com with both your demo and live merchant IDs and let me know which calls you need to access. Thanks!
