### ISSUE TITLE
Woocommerce - Wrong Merchant crendentials or API unavailableArray

### ISSUE THREAD

**Issue by pixelpudding** [VivaPayments/API#967]
I'm using the VivaWallet Woocommerce payment gateway plugin. When an order goes through it says it's successful, but the order notes say:

```
Wrong Merchant crendentials or API unavailableArray
(
[0] =>
[1] =>
301 Moved Permanently
nginx
)
```
Obviously this isn't ideal. Any ideas on what's happening here?

**Comment by matthewrgourd** [comment]
Hi there, is it our [official plugin](https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip) you're referring to or one downloaded from elsewhere? Can you let me know the version number in order to cross-reference? Thanks!

**Comment by pixelpudding** [comment]
Yes it's the official plugin. Version 3.5.7

**Comment by matthewrgourd** [comment]
Please provided the following screenshots and we will look into the issue:

* Payment module settings from [WooCommerce / Payments tab](https://developer.vivawallet.com/images/WooCommercePaymentsTab.png?classes=border&width=900) (mask the API Key).
* Viva Wallet [payment source settings](https://developer.vivawallet.com/images/NewPaymentSource.png) (include the browser's URL in the screenshot).
* Viva Wallet [Websites/Apps page](https://developer.vivawallet.com/images/WebsitesSubmenu.png?classes=border&width=900) (include the browser's URL in the screenshot).
* [API Access page](https://developer.vivawallet.com/images/API%20Access.png?classes=border&width=900) (mask API Key (include the browser's URL in the screenshot).

Thanks!

**Comment by pixelpudding** [comment]
As requested:

[
![Screenshot 2019-07-29 16 51 45](https://user-images.githubusercontent.com/34652948/62063181-52d78900-b222-11e9-8827-bee3ca7fe3c1.png)
![Screenshot 2019-07-29 16 55 54](https://user-images.githubusercontent.com/34652948/62063183-52d78900-b222-11e9-9b5c-a3d6a2d99bc2.png)
![Screenshot 2019-07-29 16 56 30](https://user-images.githubusercontent.com/34652948/62063184-52d78900-b222-11e9-8ebb-b10afa60e968.png)
![Screenshot 2019-07-29 16 56 53](https://user-images.githubusercontent.com/34652948/62063186-53701f80-b222-11e9-83a8-91697f75306f.png)



](url)

**Comment by VivaWalletSupport** [comment]
Hello, the only order note that the plugin inserts after a success payment is a string that contains the transaction ID, so I wonder where you get the mentioned order note from and at what location it is shown. Could you send a screenshot from that? Also I would recommend to setup the plugin first with the demo mode, so you can test with the test card before moving to production.

**Comment by matthewrgourd** [comment]
Hi @pixelpudding, if you wish you can install our official plugin by following the instructions given here: https://developer.vivawallet.com/downloads/vivawallet-for-woocommerce.zip Otherwise, I'm afraid we cannot help any further.
