### ISSUE TITLE
Store not Found 

### ISSUE THREAD

**Issue by 07944444123** [VivaPayments/API#968]
I have added the vivawallet to my shopify account but when I try a test payment it says - Store not found.

I checked and followed the document. Please can you let me know how to fix this.

**Comment by matthewrgourd** [comment]
Sorry you've been experiencing issues. Could I have your Merchant ID, please, so I can check your Viva Wallet account?

**Comment by 07944444123** [comment]
Sure il email that over

**Comment by 07944444123** [comment]
a6bd7537-8cd9-4f79-a602-26d16db8a426

**Comment by 07944444123** [comment]
Hi 

Please we are getting really frustrated as this today was the 4th working day our website can’t take payments and we have had no reply from your company.

**Comment by matthewrgourd** [comment]
Hi there, apologies for the delay, we're looking into it. Your account is fine so I need to ask a few more questions if you don't mind? Please can you let me know approximately how long you've been using Viva Wallet for payments in Shopify or is this a new setup?

**Comment by 07944444123** [comment]
We setup last week

**Comment by matthewrgourd** [comment]
We currently have no reported problems with our Shopify plugin. Could you triple-check that you followed our [detailed installation instructions](https://developer.vivawallet.com/e-commerce-plugins/shopify/) verbatim?

**Comment by 07944444123** [comment]
Yes we have done everything as instructed

**Comment by matthewrgourd** [comment]
Please send me a screenshot of the following settings with partially obscured values. Thanks!

![VivaWalletPaymentProvider](https://user-images.githubusercontent.com/44943019/62212385-84726080-b398-11e9-9d6f-69516da5c6df.png)

**Comment by 07944444123** [comment]
Hi 

I’m confused 

Please call me 07944444123

**Comment by matthewrgourd** [comment]
I'm afraid we don't do phone support. I just want to make sure you've put the correct values in the fields during setup. Merchant ID is 'a6bd7537-8cd9-4f79-a602-26d16db8a426', and store token should have been sent to you by email. Is that how you set it up?

**Comment by matthewrgourd** [comment]
There is sometimes a problem with the store token. Would you like me to request a new one in case that helps?

**Comment by 07944444123** [comment]
Yes please

**Comment by matthewrgourd** [comment]
Hi @07944444123 I've spoken with our Shopify developer and unfortunately the error message 'store not found' means you've either not been issued with a store token, ever, or you're entering an incorrect value for [merchant ID](https://developer.vivawallet.com/e-commerce-plugins/merchant-id).

To order your store token you need to complete and send one of these forms:

https://viva.microsoftcrmportals.com/shopify/

Please try again and get back to me if any further issues.

**Comment by 07944444123** [comment]
Hi

We are using the Merchant number form the setting menu and token that was emailed to us 

Not sure what to do know

**Comment by 07944444123** [comment]
Hi 

Please can you confirm if the below is my store token

**Comment by 07944444123** [comment]
Hi 

We have now got a new token and we are now facing a new challenge 

It says generic error

**Comment by 07944444123** [comment]
Hi 

What’s this email about ???
