### ISSUE TITLE
members.vivawallet.com source setup problem

### ISSUE THREAD

**Issue by PanosRk** [VivaPayments/API#969]
Greetings! 
I am writing this problem here, as your customer support directed me.

We are trying to set up our 'source', in your administrative panel, for our e-shop payment gateway. We enter the correct information (domain name, success and failure URLs), etc, but after the approval procedure, the source seems to have lost the data; only the e-shop's logo remains. 

When trying out the payment gateway form the e-shop, the system redirects us to the payment page, as it should. But as you understand, we are unsure that it is working properly, and we are hesitant to open it to the public.

Is that normal behavior?

Thank you in advance

Panos

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear you've been experiencing problems. Are you attempting to implement one of our [online checkouts](https://developer.vivawallet.com/online-checkouts/) or is it one of the [e-commerce plugins](https://developer.vivawallet.com/e-commerce-plugins/)? Please provide the name if possible.

**Comment by PanosRk** [comment]
Hi there Matthew,

we are trying to set up our 'source' in the vivawallet panel, (Sales -> Online payments -> websites/apps) for our e-shop payment gateway (cs-cart).

We enter the correct information (domain name, success and failure URLs), etc in the vivawallet panel but after the approval, the source seems to have lost the data; only the e-shop's logo remains.

Is that normal behavior?

Panos

**Comment by matthewrgourd** [comment]
Hi there, no, that is not normal behaviour as far as I'm aware. Can you confirm you've followed the detailed setup instructions for either [CS Cart 2/3](https://developer.vivawallet.com/e-commerce-plugins/cscart/) or [CS Cart 4](https://developer.vivawallet.com/e-commerce-plugins/cscart4/) before we look into this further?

**Comment by PanosRk** [comment]
Hello Matthew,

yes, we did follow the instructions for CSCart4.

**Comment by matthewrgourd** [comment]
Please provided the following screenshots and we will look into the issue:

* Payment module settings from CS Cart (mask the API Key).
* Viva Wallet [payment source settings](https://developer.vivawallet.com/images/NewPaymentSource.png) (include the browser's URL in the screenshot).
* Viva Wallet [Websites/Apps page](https://developer.vivawallet.com/images/WebsitesSubmenu.png?classes=border&width=900) (include the browser's URL in the screenshot).
* [API Access page](https://developer.vivawallet.com/images/API%20Access.png?classes=border&width=900) (mask API Key (include the browser's URL in the screenshot).

Thanks!

**Comment by PanosRk** [comment]
Hello Matthew,

we do not wish to share such information on a public forum.

Can we have some personal support communication?

Thank you,

Panos

**Comment by matthewrgourd** [comment]
Ok, please send the requested screenshots to mgourd@vivawallet.com copying in info@webit.bz.

**Comment by matthewrgourd** [comment]
We can confirm there is no issue at our end. Please request support from your plugin provider, or install our [official plugin](https://developer.vivawallet.com/e-commerce-plugins/cscart4/).

**Comment by PanosRk** [comment]
Dear matthew,

there was never a problem with the plugin. 

Your vivawallet panel has the problem.

Can someone please support me, and my customer?

Thank you

Panos

**Comment by PanosRk** [comment]
I am going to use a screenshot, to explain the problem.

We enter the requested information in the form seen in the screenshot below, 
but after a few hours, the information reset to default values!
(only the logo remains)

![Screenshot_2019-08-01 https members vivawallet com](https://user-images.githubusercontent.com/53474278/62297033-0e91f600-b479-11e9-987d-cccf0d399e04.png)

Please help us set the information correctly, because we have been struggling with the issue for 2 weeks now, and our customer (and yours, consequently) is furious.

Thank you,

Panos

**Comment by matthewrgourd** [comment]
Hi there, you have sent through some screenshots that clearly show settings from a third-party plugin, [Hellaspay](https://www.magentocommerce.com/products/hellaspay-1035.html), which we do not support. I'm sorry we can't help any further.

**Comment by PanosRk** [comment]
Dear Matthew,

even though the 2 entities are irrelevant, we just installed your addon from your documentation page.

The behavior of the vivawallet admin interface has the same issue. We enter the information, and after a few hours, the information reset to default values! the screenshot in my previous message depicts that.

Can you help us please?

If not you, can you direct me to the correct support?

Panos

**Comment by PanosRk** [comment]
I am posting the solution:

As it turns out, the vivawallet.com administration panel only works correctly under the chrome web browser (and in incognito mode), instead of the mozilla firefox we were using.

Now, you can consider this thread closed.

Panos

**Comment by matthewrgourd** [comment]
Hi @PanosRk, thanks for this. We'll pass on your feedback which is very useful.
