### ISSUE TITLE
Redirect back to eshop/info on payment page

### ISSUE THREAD

**Issue by sptm92** [VivaPayments/API#97]
Χαιρετε,

Βλεπω οτι μολις πραγματοποιει ο πελατης την πληρωμη το success Page της Viva δεν εχει καποιον συνδεσμο Η δν υπαρχει δυνατοτητα να επιστρεψει ο πελατης πισω στο success page του eshop..

Επισης υπαρχει δυνατοτητα, στην φορμα που συμπληρωνει ο πελατης τα στοιχεια του, να υπαρχει καπου ενα μερος το οποιο θα εμφανιζονται τιτλος/τιτλοι των προιοντων που προκειται να αγορασει ο πελατης?

**Comment by dmihos** [comment]
Θα πρέπει να ορίσετε τα urls του site σας στην ενότητα Οι πωλήσεις μου > Πηγές Πληρωμών.
Για την περιγραφή που θέλετε να φαίνεται, μπορείτε να χρησιμοποιείτε το πεδίο "CustomerTrns" κατά τη δημιουργία του Order
