### ISSUE TITLE
Getting started POS Terminal integration

### ISSUE THREAD

**Issue by online123be** [VivaPayments/API#971]
Hello,
I am new to Viva Wallet and the integration. I have a PHP based inapp browser POS platform and a A920 device. Because I am running my software from a different device I need the TCP/IP option, but I dont find my way arround this integration. I understand the explanation on the developer pages, but I dont know how to get started.
Could someone please get me in the right direction on how to connect, send / request some data, ... ? I just dont know how to start.. Once started I will have something to toy with and I'll be fine :).

**Comment by donfn** [comment]
I, personally, wouldn't use PHP for that 😅...
If you're just toying around, then check out this python script:
```
import socket
import sys
import random

pos_ip = '192.168.2.12'
pos_port = 8080

pos = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
pos.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
pos.setsockopt(socket.SOL_TCP, socket.TCP_KEEPIDLE, 60)
pos.setsockopt(socket.SOL_TCP, socket.TCP_KEEPCNT, 4)
pos.setsockopt(socket.SOL_TCP, socket.TCP_KEEPINTVL, 15)

pos.connect((pos_ip, pos_port))
amount = str(input('Input the amound (ex. 20.50 for 20,50€): ')).replace(',','.')
packet = '|'+str(random.randint(1000,9999))+'|200|00|PAYMENT|'+amount+'|0000||||'
packet = '0'*(4-len(str(len(packet)))) + str(len(packet)) + packet
pos.send(packet.encode())
print('Sending the transaction details to the POS')
pos.recv(4096)
print('Present the card at the terminal. Close this program to cancel the transaction.')
response = pos.recv(4096).decode().split('|')
if response[4] == '00':
	print('SUCCESS! AUTHORIZED  '+ response[11] + '€' + ' from ' + response[6] + ' ' + response[7] )
else:
	print('DECLINED. View the POS screen for more info.')
input("Press ENTER to close...")
```

Otherwise, if you need this for a project that requires PHP, there should be a similar function to Python's socket that handles TCP conversations.
