### ISSUE TITLE
Error code 405

### ISSUE THREAD

**Issue by Lucania001** [VivaPayments/API#972]
Hi,

Getting error code 405.

ErrorCode":405,"ErrorText":"Action blocked due to security policy",

Can you tell me what this means?

**Comment by matthewrgourd** [comment]
Please provide further details of what Viva Wallet product or service you're attempting to use that results in this error. Is it one of our [e-commerce plugins](https://developer.vivawallet.com/e-commerce-plugins/) or [online checkouts](https://developer.vivawallet.com/online-checkouts/)?

**Comment by Lucania001** [comment]
Hi Matthew,

This is an API call to the transactions API to charge a customers card. Happy to provide full response if that helps?

**Comment by matthewrgourd** [comment]
Hi there, thank you. Yes, please provide the full request / response obscuring any confidential information.

**Comment by matthewrgourd** [comment]
@Lucania001 This sounds like a localized issue. You should probably speak to your IT department or web host. Feel free to reopen if it's still a problem.
