### ISSUE TITLE
Attention This card does not support electronic transactions.

### ISSUE THREAD

**Issue by menelaosdim** [VivaPayments/API#973]
The last few days I'm getting this message, (me and a lot of my client's, clients)....

Attention
This card does not support electronic transactions. In order to complete this payment please use a different card, or add funds to your Viva Wallet.

It's not a configuration error, it does happen in Viva Payments enviroment (after redirect).

In both Opencart Versions (1.5 and 3.x).

With a storebought VivaPayments extension.

I've actually tried a lot of different debit / credit carts (Viva, Mastercard etc) and I'm still getting the same response!

Let me note that the e-shop is running for 5 years now and it's the first time we've encountered something like this.

Thanks in Advance :)

Menelaos

**Comment by matthewrgourd** [comment]
Please provided the following screenshots and we'll look into the issue:

* Payment module settings from OpenCart (mask the API Key).
* Viva Wallet [payment source settings](https://developer.vivawallet.com/images/NewPaymentSource.png) (include the browser's URL in the screenshot).
* Viva Wallet [Websites/Apps page](https://developer.vivawallet.com/images/WebsitesSubmenu.png?classes=border&width=900) (include the browser's URL in the screenshot).
* [API Access page](https://developer.vivawallet.com/images/API%20Access.png?classes=border&width=900) (mask API Key (include the browser's URL in the screenshot).

Thanks!

**Comment by matthewrgourd** [comment]
Hi @menelaosdim , sorry to hear this, I will raise with one of our developers and get back to you.

**Comment by matthewrgourd** [comment]
Hi @menelaosdim , sorry for the delayed reply. We are looking into this for you. Could you send your merchant ID to mgourd@vivawallet.com in order to progress things?

**Comment by matthewrgourd** [comment]
@menelaosdim please can you send your merchant ID and business name to mgourd@vivawallet.com?

**Comment by menelaosdim** [comment]
Hello @matthewgoud well i sent it via e-mail! Many thanks :)

**Comment by matthewrgourd** [comment]
Hi @menelaosdim I've checked your account and no issues at this end. I will ask our plugin developer to reply. Thanks!

**Comment by matthewrgourd** [comment]
I've checked with our plugin developer and the extension you mention is not one provided by us so I'm afraid we can't offer you any support. Feel free to download our own extension and follow the instructions given at https://developer.vivawallet.com/e-commerce-plugins/opencart3/

**Comment by menelaosdim** [comment]
Im using your extension now and it STILL does the same thing... With YOUR extension.

Shal  I Reopen the issue on GitHub;

Just help the man for god's shake, he is YOUR client too.

It's not even remotely acceptable that he cannot accept payments since August... I mean... This is just bad servive...

[cid:61318b25-6bdc-4687-b395-c23b1e230fc9]

________________________________

**Comment by matthewrgourd** [comment]
Sorry about this, I will need to check the account. Please send business name and merchant ID to mgourd@vivawallet.com

**Comment by menelaosdim** [comment]
Of Cource.

TERZIEVA ANA LUBEN
Dekor Candles

Merchant id = 941ea9e5-9409-40dc-b345-651aae165e57
________________________________

**Comment by matthewrgourd** [comment]
Hi @menelaosdim I've checked the account and there is a note attached to it meaning e-commerce transactions are not enabled at present. Please get the merchant to contact [customer service](https://www.vivawallet.com/en-eu/contact-us/) for an explanation. Unfortunately there's nothing further I can do from here.
