### ISSUE TITLE
Woo commerce viva wallet language issue

### ISSUE THREAD

**Issue by nutritionking** [VivaPayments/API#974]
Hey guys I'm hoping you can help when my customer's are going to the checkout page and clicking the viva wallet portal to make payment its appearing in Greek how can i make the default language English please

**Comment by VivaWalletSupport** [comment]
Hello, could you send a screenshot of the plugin settings, masking API and other sensitive infromation?

**Comment by nutritionking** [comment]
Hey I've managed to sort it out

Kind regards

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
