### ISSUE TITLE
Havana House - Payments pending issue 

### ISSUE THREAD

**Issue by richardjsteggles** [VivaPayments/API#975]
My client Havana House are experiencing an issue where the payments are timing out or are left in a pending status and are not transacting. They are using a woocommerce plugin.

www.havanahouse.co.uk
www.regalcigars.com
www.thevaping-lounge.com
www.tobacconistonline.com

**Comment by richardjsteggles** [comment]
![havana house](https://user-images.githubusercontent.com/47525061/62364878-91b75880-b51a-11e9-9487-baea795f5bf4.jpg)

**Comment by VivaWalletSupport** [comment]
Hello, please confirm that the plugin and its instructions are used from https://developer.vivawallet.com/e-commerce-plugins/woocommerce/

If so, please provided the following screenshots (for one of the mentioned domains) and we will look into the issue:

Payment module settings from CS Cart (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by richardjsteggles** [comment]
Yes they followed these steps

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by richardjsteggles** [comment]
Please specify the payment module settings as the client is using woocommerce I believe

API access page?

**Comment by VivaWalletSupport** [comment]
See an example of the 4 screenshot previous issue https://github.com/VivaPayments/API/issues/967
