### ISSUE TITLE
Merchant i.D

### ISSUE THREAD

**Issue by Robert-A-Taily** [VivaPayments/API#976]
I have sent off three times for my merchant I.D & store token but have yet to receive anything and need to it add to my shopify store a.s.a.p to start accepting payments. 

Merchant I.D889eb1c9-525e-459a-a964-c495983fa865

Please do let me know when this is completed.

**Comment by matthewrgourd** [comment]
Sorry to hear that, what is the business name, please?

**Comment by matthewrgourd** [comment]
Hi there, apparently we've sent a token twice, once to woof@taily.com and once to woof@taily.co.uk. Have you checked your spam?

**Comment by Robert-A-Taily** [comment]
Hi,

Business name is Advanced Supplements LTD. 

I haven't received any token for merchant I.D or store I.D. The only email that it should be sent to is 

woof@taily.co.uk

Can you please issue it again.

Many Thanks,
R

**Comment by Robert-A-Taily** [comment]
Can you please action this a.s.a.p

**Comment by matthewrgourd** [comment]
Hi there,

The team that deals with the Shopify extension came back with this reply on Friday:
   
> We have sent the token to both woof@taily.com and woof@taily.co.uk
> This is the email the merchant fills in when submitting the form

Thanks, should I suggest they check their spam?

> Yeah, otherwise its an email provider issue

> They just sent another request with e-mail woof@taily.com, I'm forwarding it again just in case.

**Comment by Robert-A-Taily** [comment]
The email as previously stated is woof@taily.co.uk so please make sure that all correspondence is sent to the correct email address. 

I have checked the spam

**Comment by matthewrgourd** [comment]
We have definitely sent to woof@taily.co.uk so please check with your email provider if they've unintentionally blocked the email.

**Comment by Robert-A-Taily** [comment]
outlook don't block any emails unless specified.

Is there any chance that you can send copy in my personal email address robert.r.acres@gmail.com as there seems to get around this issue.
