### ISSUE TITLE
Client Credentials request

### ISSUE THREAD

**Issue by LoggiaNG** [VivaPayments/API#977]
Hello, 
we need DEMO client credentials to test our implementation for bearer tokens and the rest of the VivaWallet API.

We used to have client_id = "generic_acquiring_client.apps.vivapayments.com" and client_secret = "generic_acquiring_client", but this is not working anymore, correct?

Thank you!

**Comment by matthewrgourd** [comment]
Hi there, please email myself mgourd@vivawallet.com with your Merchant ID and an email address to send the credentials. I can generate for you. The ones you mention are for card tokenization only.
