### ISSUE TITLE
Transaction Failed : Fetch ISO error code from viva payment api response.

### ISSUE THREAD

**Issue by TwinkleMali** [VivaPayments/API#978]
Hi ,

We still do not get any solution from your end for transaction failure. Status: E and Error Code: 502. 
And Our customer are keep on facing issue in payment. We must have to found solution for this issue soon.
We have reviewed Viva document, we found some iso error code there. 
Would you please update how we can get iSO error code if transaction will get failed due to iSO reason ?

Looking forward to your reply soon.

Thanks,
Twinkle

**Comment by matthewrgourd** [comment]
Please attach any request / response logs so we can look into further. You should obscure any customer or confidential information. Thanks!

**Comment by TwinkleMali** [comment]
Hi @matthewrgourd ,

Please find steps and url we are following are below.

Steps:

1) Card tokenization: (Called form mobile application to get token passed it to server.)
        URL: https://www.vivapayments.com/api/cards?key={Our Public key}
        Params:  Number
                        CVC
                        ExpirationDate
                        CardHolderName

2) Creating order using,
        URL: https://www.vivapayments.com/api/orders
        Params:      Amount = {Something}
                            SourceCode = {Something}
                            MaxInstallments = 0 (By default always)

3) Payment execution:
        URL: https://www.vivapayments.com/api/transactions
        Params:      Amount = {Something}
                            OrderCode -> Received from above URL response
                            SourceCode = {Something}
                            CreditCard["Token"] = {card_token} 

And in response it returns Status id: E and error code: 502.

Please do let us know if anything is managed wrong or missed to be managed.
Also if you need any other information from us that please let us know. 

Looking forward to your reply.

Thanks,
Twinkle

**Comment by matthewrgourd** [comment]
Hi @TwinkleMali , we've looked at your issue and believe step 1 relates to [Native Checkout v1](https://developer.vivawallet.com/online-checkouts/native-checkout-v1) which has been deprecated. Please used [Native Checkout v2](http://localhost:1313/online-checkouts/native-checkout-v2/) instead. Thanks!

**Comment by TwinkleMali** [comment]
Hi @matthewrgourd ,

We have not used NativeCheckout1. We have used payment api.
and to get card token we found api from viva github project.
Here it is an link.
https://github.com/VivaPayments/API/tree/master/MobileAPI

Would you please update us what changes i have to do ?

**Comment by matthewrgourd** [comment]
Hi there, I've checked with one of our developers and he has responded that in order to integrate your mobile app with our API you need to use Native Checkout v2 which is documented here: 

https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#3dsecure-via-the-native-checkout-v2-0-api 

The code samples at https://github.com/VivaPayments/API/tree/master/MobileAPI are no longer relevant and I have asked for them to be removed. 

Hope this helps!

**Comment by TwinkleMali** [comment]
Hi @matthewrgourd ,
So payment api we have used for create order and make payment is also need to be changed?

**Comment by TwinkleMali** [comment]
i am referring below two apis.

Creating order using,
URL: https://www.vivapayments.com/api/orders
Params: Amount = {Something}
SourceCode = {Something}
MaxInstallments = 0 (By default always)

Payment execution:
URL: https://www.vivapayments.com/api/transactions
Params: Amount = {Something}
OrderCode -> Received from above URL response
SourceCode = {Something}
CreditCard["Token"] = {card_token}

**Comment by matthewrgourd** [comment]
Sorry @TwinkleMali , the correct link is https://developer.vivawallet.com/online-checkouts/native-checkout-v2 . `Create order` and `Execute payment` are referenced under [Step 5](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-5-create-a-payment-order) and [Step 6](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/#step-6-complete-the-charge) respectively in the instructions.
