### ISSUE TITLE
API v2 Credentials

### ISSUE THREAD

**Issue by donfn** [VivaPayments/API#979]
Hello,
I would like to request the production credentials for the account with Merchant ID: 1137e218-6f45-44de-a1f5-cb295e0afd0a. 

Hope this process becomes automated soon... 😬

**Comment by matthewrgourd** [comment]
Hi there,

Please could you send the request to mgourd@vivawallet.com with the following information (fill in the blanks):

* business name: [         ]
* merchant ID: 1137e218-6f45-44de-a1f5-cb295e0afd0a
* environment requested: PRODUCTION
* contact email address: [         ]

In answer to your question, we're working on automating the process. Thanks!
