### ISSUE TITLE
Customize Payment Page

### ISSUE THREAD

**Issue by integrators** [VivaPayments/API#98]
Hello, can we further customize the payment page (apart from adding our logo at the top?)

**Comment by dmihos** [comment]
Hi integrators
No, excluding logo, the Redirect checkout page is not customizable.
You can evaluate the other two checkout options if you want maximum customization:
[Pay with Viva Wallet](https://github.com/VivaPayments/API/wiki/Pay-with-Viva-Wallet)
[Native Checkout](https://github.com/VivaPayments/API/wiki/Native-Checkout)
