### ISSUE TITLE
url redirect loop

### ISSUE THREAD

**Issue by YigoAbi** [VivaPayments/API#980]
i had installed on magento store but it redirecting to no where it not open any url
https://www.ace-wellness.uk
please help

**Comment by VivaWalletSupport** [comment]
Hello, please provide following 4 screenshots to check the problem.

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by YigoAbi** [comment]
![Screenshot from 2019-08-05 09-25-48](https://user-images.githubusercontent.com/45944167/62438089-860aa280-b763-11e9-8bd3-e0ea319d7494.png)
![Screenshot from 2019-08-05 09-29-50](https://user-images.githubusercontent.com/45944167/62438113-9de22680-b763-11e9-9776-8ab8eb313e1f.png)

**Comment by donfn** [comment]
Change your API key **ASAP** (API Access -> click on API Key -> Type some long, random chars -> save). Some people (like me) have new threads emailed to their inbox along with any photos attached.

You have not followed the instructions given on creating a web source (you're using default).

Follow the instructions given here:
https://developer.vivawallet.com/e-commerce-plugins/magento2.3/

You probably missed **"Click on the Add Website/App button on the right."**

**Comment by VivaWalletSupport** [comment]
Please change your API Key asap, this should not be posted or at least masked as mentioned before. Follow the installation / configuration instructions to the letter (as you did not create a valid payment source). https://developer.vivawallet.com/e-commerce-plugins/magento1.x/

In the plugin settings specify the Source Code and full Ordercode / Gateway URLs, as shown below for the live environment:
https://www.vivapayments.com/api/orders
https://www.vivapayments.com/web/newtransaction.aspx

**Comment by YigoAbi** [comment]
i have updated API key but same issue

may i give you login details os site and gateway please make it

**Comment by VivaWalletSupport** [comment]
Hello, please provide following the **4** updated screenshots to check the problem.

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by YigoAbi** [comment]
![error1](https://user-images.githubusercontent.com/45944167/62632823-bebb9f00-b950-11e9-854e-9caa00ec39ce.png)
![error](https://user-images.githubusercontent.com/45944167/62632833-c11df900-b950-11e9-8cd2-43ccac4ad72d.png)
![Screenshot from 2019-08-07 20-15-39](https://user-images.githubusercontent.com/45944167/62632899-e3177b80-b950-11e9-9090-5bcd686dd4b7.png)

**Comment by VivaWalletSupport** [comment]
Please try to follow given instructions:
In the plugin settings specify the Source Code and full Ordercode / Gateway URLs, as shown below for the live environment:
https://www.vivapayments.com/api/orders
https://www.vivapayments.com/web/newtransaction.aspx

Also in the payment source you forgot the index.php part at the failure URL.

Please correct these items and in case the problem persists post again the 4 screenshots.

**Comment by YigoAbi** [comment]
![error3](https://user-images.githubusercontent.com/45944167/62635338-21169e80-b955-11e9-8f07-df18d0207a72.png)

**Comment by YigoAbi** [comment]
https://www.ace-wellness.uk/index.php/vivawallet/hpay/redirect/?Ref=

this is my issue not getting some ref from plugin

**Comment by VivaWalletSupport** [comment]
Please try to follow given instructions:
In the plugin settings specify the full Ordercode / Gateway URLs, as shown below for the live environment:
https://www.vivapayments.com/api/orders
https://www.vivapayments.com/web/newtransaction.aspx

Also in the payment source you forgot the index.php part at the failure URL.

Please correct these items and in case the problem persists post again the 4 screenshots.

**Comment by YigoAbi** [comment]
I don't have live environment screen/link

**Comment by YigoAbi** [comment]
done thanks

**Comment by YigoAbi** [comment]
help me to make a test order

**Comment by YigoAbi** [comment]
installed and everything is ok but unbale to order using magento store

**Comment by VivaWalletSupport** [comment]
Hello, please provide following the 4 updated screenshots to check the problem.

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).

**Comment by YigoAbi** [comment]
![Screenshot from 2019-08-15 21-55-19](https://user-images.githubusercontent.com/45944167/63110083-47b58480-bfa8-11e9-90a2-07c7bc60cd83.png)
![error](https://user-images.githubusercontent.com/45944167/63110099-4edc9280-bfa8-11e9-8cfd-9a857d07f6ff.png)

everything is ok i want to make a test with my credit card

**Comment by VivaWalletSupport** [comment]
You can test in live mode using a payment over 0.30 p/cnt with your credit card cancelling the payment afterwards through your Viva account, ot by setting up the demo environment using the provided test card.

**Comment by cocorikush** [comment]
I have a problem with payment. do you speak french?
