### ISSUE TITLE
Merchant I.D (Same as #976) 

### ISSUE THREAD

**Issue by Robert-A-Taily** [VivaPayments/API#981]
I have requested the token and merchant i.d. The team have stated that this has been sent to woof@taily.co.uk but that is not the case. 

I have requested that my personal email of robert.r.acres@gmail.com be copied in on the email as well so that I can get the Shopify account correctly setup.

**Comment by matthewrgourd** [comment]
Hi @Robert-A-Taily , I've put in the request but it may be quicker filling in another [Shopify token request form](https://viva.microsoftcrmportals.com/shopify) with the alternative address. Also, bear in mind a lot of our staff are on holiday in August. Thanks!

**Comment by Robert-A-Taily** [comment]
Hi @matthewrgourd I have already dont this and there has been no email to my personal email either. So I presume that the problem lies your end as I'm not getting any emails via our own server or via gmail.

Can you provide it on this note then we can close the ticket.

**Comment by Robert-A-Taily** [comment]
just screenshot it and then we can be done with it!

**Comment by Robert-A-Taily** [comment]
A new ticket has been raised with my personal email robert.r.acres@gmail.com

Can you please mark this as urgent as I really need to get this verified and be able to accept payments a.s.a.p

**Comment by Robert-A-Taily** [comment]
To confirm the merchant I.D in my case would be ADVANCED SUPPLEMENTS LTD? 

As I have received the store token, and can now process the migration on Shopify
