### ISSUE TITLE
Error - ShopifyPlug

### ISSUE THREAD

**Issue by Tom13763** [VivaPayments/API#983]
Hi, I added vivawallet to my shopify account, with the merchant ID and the store token then while I try a test payment it redirects to a "Store not found" page.

![Viva-1](https://user-images.githubusercontent.com/53798881/62501105-7d5caf80-b7e9-11e9-8fce-c4b20cf905b5.jpg)
![Viva-2](https://user-images.githubusercontent.com/53798881/62501109-8188cd00-b7e9-11e9-8e0e-0c4f1edd3186.jpg)

Please could you help me?
Thanks in advance

**Comment by livsterf** [comment]
Having the same issue, any luck resolving? HAvent been able to get through on the phone to Vivawallet yet.

**Comment by matthewrgourd** [comment]
Hi @Tom13763, sorry to hear you've been experiencing issues. Could you quickly confirm the web address of your store? Thanks!

**Comment by matthewrgourd** [comment]
Hi @livsterf , sorry to hear you've been experiencing issues. Could you quickly confirm the web address of your store? Also if you wouldn't mind letting me know if you followed the instructions below verbatim? Thanks!

https://developer.vivawallet.com/e-commerce-plugins/shopify/

**Comment by Tom13763** [comment]
Hi Mattew, thanks to you for the help, my website is  https://www.green-doctor.be
I already read and folowed the instructions.
Before I receive my store token from Viva wallet, I entered my API key instead of my store token, (below the merchant ID field).
Could it be the cause of the problem?

**Comment by matthewrgourd** [comment]
Hi there, can you maybe try to completely remove anything relating to Viva Wallet and start again? Using your API key instead of store token may well have caused a problem!

**Comment by Tom13763** [comment]
It seems that I can only desactivate or reactivate Vivawallet in shopify and not remove anything..

**Comment by asrock49** [comment]
Has this been resolved? i'm having the same issue!

**Comment by Tom13763** [comment]
Still not resolved, please Matt, could you tell me how to do?

**Comment by matthewrgourd** [comment]
@Tom13763 @asrock49 Sorry but generally these types of issue relate to incorrect setup of Shopify. You need to make sure you follow the instructions in the [Shopify guide](https://developer.vivawallet.com/e-commerce-plugins/shopify/) exactly as they are written. A common problem is that the merchant ID is not correct. For help with finding your merchant ID, check this page: https://developer.vivawallet.com/e-commerce-plugins/merchant-id However, saying that, I will alert our Shopify developer in case there's any additional help he can provide.

**Comment by Tom13763** [comment]
Thank you for the answer Matt, I would be happy to get in touch with your shopify developer because I really don't found a solution.

**Comment by matthewrgourd** [comment]
Hi @Tom13763, ok, I've spoken with him and he's suggesting you may have 'Use test mode' checked in the Shopify settings. If you could try again with this de-selected?

**Comment by Tom13763** [comment]
Yes, I'm very happy to say that all is working very well without the testing mode, Thank you very much guys!
