### ISSUE TITLE
Credentials for Native Checkout v2.0

### ISSUE THREAD

**Issue by KateRoseMorley** [VivaPayments/API#985]
We require demo credentials for the accounts with the following Merchant IDs:

ba55608f-0c28-4dbd-9c2b-4e472fe57bec
0a913198-76dc-445e-9195-0da5f96b9052

**Comment by matthewrgourd** [comment]
Hi @KateRoseMorley, please email myself (mgourd@vivawallet.com) and I will reply back with the credentials you need. Thanks!
