### ISSUE TITLE
Problem with payement plug in on prestashop

### ISSUE THREAD

**Issue by Streetshop33** [VivaPayments/API#986]
Hi, 

Since Saturday wwe have a problem with the vivawallet gateway payement. When we want to go on the payement page nothing happend but when i disable vivawallet on my back office i can go on my payement choice page. I think there are a problem with vivawallet plug in.

**Comment by VivaWalletSupport** [comment]
Hello, before Saturday you did not have a problem with the Viva Wallet module? If so, what changes have been made to PrestaShop since Saturday? Also please confirm that this issue is related to the supported plugin from https://developer.vivawallet.com/e-commerce-plugins/prestashop/

**Comment by Streetshop33** [comment]
Hi, 

We did not change something on prestashop and we didn't have problem with the plug in and monday i have request from customer telling they can't have access of payement page and when i desable vivawallet we can acess of payement page but the they can't paid with their credit card because vivawallet is disable... Yes i confirm that the issue is related to this plugin.

**Comment by VivaWalletSupport** [comment]
As the plugin code does not change by itself, something must have changed in the store configuration or on your server that caused the suddenly appearing problem. Please check your configuration again, see if any errors are logged, check if no other (checkout) modules have been added since.

**Comment by Streetshop33** [comment]
I tried to uninstall the plugin and instal it no work. I contact ovh and the tell to me that other people have this problem. I'm sure we don't change nothing on prestashop

**Comment by VivaWalletSupport** [comment]
The problem as you mention happened with a few other clients that use a 3rd party one page checkout module. But as you mention that you did not make any changes, it would not be likely to be the same problem in your case (as you would have the problem from start).

**Comment by Streetshop33** [comment]
We have the plugin since 1 month all perfectly working i don't know what could be the problem ? I tried all i can do. When the plugin is activate when we want to go to the page to choose the means of payements the web page searching all time ...

**Comment by VivaWalletSupport** [comment]
Please follow what has been suggested before:
Check your configuration again, see if any errors are logged, check if no other (checkout) modules have been added since (use PrestaShops default checkout).

**Comment by Streetshop33** [comment]
I check all you say there nothing wrong. We have a second website with vivawallet we don't use it since 2 weeks ( No new module, no touche back office since 2 week ) and we have the same problem.

**Comment by VivaWalletSupport** [comment]
Culd you provide a screenshot of the payment option page with the Viva Wallet option disabled?

**Comment by Streetshop33** [comment]
![Capture](https://user-images.githubusercontent.com/53818523/62605373-44f8c680-b8fa-11e9-9c0d-89a1b9c8dc08.JPG)

This is the payement page who should appear vivawallet but when vivawallet is "on" i can't have access of this page.

**Comment by VivaWalletSupport** [comment]
Please send admin URL + login credentials, FTP credentials from one of the sites to vivawalletgithubsupport@hellasboost.gr with a cc to ecommerce-support@vivawallet.com to investigate the problem.

**Comment by Streetshop33** [comment]
Okay, i send you all the information.

**Comment by VivaWalletSupport** [comment]
Thank you, please contact your hosting provider to solve the problem you have on your server to connect with Viva (through cURL), following error occurs: Failed to connect to www.vivapayments.com port 443: Connection timed out (7)
