### ISSUE TITLE
Problems with shopify integration (can't find viva wallet install page)

### ISSUE THREAD

**Issue by ecigwholesale** [VivaPayments/API#987]
Hi 
We followed the steps to install viva wallet on shopify, but we stuck on step 5. After we click the link and login to our store, nothing come up, all we can see is the shopify dashboard which is not what's step 6 showing. 
Anyone have same issue? 
https://developer.vivawallet.com/e-commerce-plugins/shopify/

**Comment by matthewrgourd** [comment]
Hi there, sorry to hear you're experiencing issues. Could you quickly confirm the web address of your store? Thanks!

**Comment by ecigwholesale** [comment]
Ecigwholesale.co 

Regards
Owen
No1 Ejuice
Unit 27 
Alder Close
Erith
DA18 4AJ
020 3638 7209

**Comment by matthewrgourd** [comment]
Hi @ecigwholesale are you still having problems or have you managed to resolve this now? I would advise reading the entirety of the Shopify guide as all the information should be there, including what to do if you're see a slightly different screen...

**Comment by ecigwholesale** [comment]
All solved thank you 

Regards
Owen
No1 Ejuice
Unit 27 
Alder Close
Erith
DA18 4AJ
020 8311 8050
