### ISSUE TITLE
V2 Javascript library assumed jQuery is on $

### ISSUE THREAD

**Issue by VizuaaLOG** [VivaPayments/API#988]
The Viva Payments V2 Javascript API is assuming jQuery is assigned to window.$, this is not always the case, especially when jQuery is running in no conflict mode (which is default for Wordpress).

An easy fix for this would be to wrap the Viva JS code in a self-invoking function that has `jQuery` injected into it. Something like:

```javascript
(function($) {
  // all of the current Viva code
}(jQuery));
```

This would help get around when $ is not being used within a certain webpage. Alternatively, all $ references can be changed to jQuery.

**Comment by matthewrgourd** [comment]
@VizuaaLOG Thanks for this! I'll be sure to pass on to our development team when they're back from their summer vacation.

**Comment by matthewrgourd** [comment]
Hi @VizuaaLOG I've passed on and apparently we'll be implementing your suggestion – thanks again!

**Comment by dpnevmatikos** [comment]
Hi @VizuaaLOG and thanks for your comment,
We've finished implementing it and you can expect it to reach production within the next few days.

Again, many thanks for your suggestion and for taking the time to provide and implementation approach!

**Comment by VizuaaLOG** [comment]
Hey @dpnevmatikos that's awesome thank you! Will make integrating it into existing systems such as Wordpress (:weary:) a bit easier :+1:
