### ISSUE TITLE
API for iOS and Android application

### ISSUE THREAD

**Issue by Yokkeshsr** [VivaPayments/API#989]
API exampled given on your platform is not working for native payment process in Android and iOS platform.

Can you please check with them any alternate API for payment checkouts in Vivawallet.

**Comment by matthewrgourd** [comment]
Hi there, would you mind letting me know where you saw the API example you mention. Is it under https://github.com/VivaPayments/API/tree/master/MobileAPI by any chance?

**Comment by matthewrgourd** [comment]
Hi there, if you were attempting to use any of the code under https://github.com/VivaPayments/API/tree/master/MobileAPI this is no longer in use and we are about to remove it. Sorry for any confusion caused. Please use Native Checkout v2 instead:

https://developer.vivawallet.com/online-checkouts/native-checkout-v2/

Hope this helps. Thanks!
