### ISSUE TITLE
Αλλαγή εταιρείας στο vivawallet και στο site

### ISSUE THREAD

**Issue by Costas81** [VivaPayments/API#99]
Καλησπερα σας,

Αλλάζουμε ΑΦΜ και επωνυμία εταιρείας και ήδη έχουμε φτιάξει το vivawallet της νεας εταιρείας και έχει ταυτοποιηθεί εταιρικά και τραπεζικά. Σύντομα, θα αλλάξουμε και στο site μας το merchant_id και το API_key ούτως ώστε οι πληρωμές από δω και στο εξής να γίνονται στη νέα εταιρεία με το νέο ΑΦΜ.

Η ερώτηση μου ειναι η εξής: Οι επαναλαμβανόμενες πληρωμές στο site μας, που γίνονται σε μηνιαία βάση και μια φορά το μήνα, απο παλιούς πελάτες , οι οποίοι είχαν δηλώσει την χρεωστική/πιστωτική τους κάρτα τους με το παλιό API, τώρα που θα γυρίσουμε από το παλιό ΑΦΜ και την παλιά εταιρεία στο καινούριο ΑΦΜ και στην καινούρια εταιρεία, πού θα οδηγηθούν οι πληρωμές αυτές? Στην παλιά εταιρεία και εταιρικό λογαριασμό ή στην καινούρια εταιρεία και στον καινούριο λογαριασμό?

Ευχαριστώ εκ των προτέρων.

**Comment by dmihos** [comment]
Καλησπέρα σας
Οι επαναλαμβανόμενες πληρωμές θα εκκαθαρίζονται στο παλιό εμπρορικό account σας, αφού μέσω αυτού μπορούν μόνο να εκτελεστούν.

**Comment by Costas81** [comment]
Υπαρχει καποιος τροπος να μεταβιβαστουν οι πληρωμες στο καινουριο account?

Ευχαριστω

**Comment by dmihos** [comment]
Όχι, δυστυχώς δεν υπάρχει αυτή η δυνατότητα.

**Comment by Costas81** [comment]
Τι workaround υπαρχει σ αυτη την περίπτωση?

Αν θέλετε, παρακαλώ καλέστε με καθώς πρέπει να βρούμε μια λύση.
6949266381

Ευχαριστώ

**Comment by Costas81** [comment]
Υπάρχει μήπως κάποιο νεώτερο?

Ευχαριστώ εκ των προτέρων.

**Comment by defilerc** [comment]
Καλησπέρα @Costas81 ,

Δεν υπάρχει δυνατότητα μεταφοράς recurring payments σε άλλη εταιρεία, καθώς αυτό θα απαιτούσε εκ νέου αποδοχή και από τη μεριά των πελατών. Σε μια τέτοια περίπτωση ο χρήστης θα πρέπει εκ νέου να αποδεχθεί χρέωση με την καινούρια εταιρεία.

Με εκτίμηση,
