### ISSUE TITLE
Error Store not found

### ISSUE THREAD

**Issue by asrock49** [VivaPayments/API#991]
Hi guys,

I have integrated the viva wallet gateway as per your instructions: 
https://developer.vivawallet.com/e-commerce-plugins/shopify/

But when i try to do a test purchase, the gateway redirects to https://feed.viva.gr/shopify stating : ERROR
Store not found.

Merchant ID | ef204a32-443b-4455-8b2b-bc30e8e58a95

Can you please help me resolve this. 

Thanks

**Comment by dmihos** [comment]
You need to uncheck the 'Use test mode' on the form of MerchantId/StoreToken inputs.
