### ISSUE TITLE
Viva Wallet prestashop Fatal Error 500

### ISSUE THREAD

**Issue by Artchemist** [VivaPayments/API#992]
Hi, 

I have install viva wallet plugin on prestashop 1.7.6.0  and currently working on demo mode with demo account and credentials. 
I have added the "source code" so it will redirect when success or fail. 

It does redirect to modules/vivawallet/success.php with variables (t, s, lang, eventid, eci)
The problem is that I get a fatal error (below) instead of a success page. 

Fatal error: Uncaught Error: Call to a member function get() on null in /home/brandcosmetics/public_html/classes/Tools.php:801 Stack trace: #0 /home/brandcosmetics/public_html/classes/Tools.php(773): ToolsCore::getContextLocale(Object(Context)) #1 /home/brandcosmetics/public_html/classes/PaymentModule.php(421): ToolsCore::displayPrice(10, Object(Currency), false) #2 /home/brandcosmetics/public_html/modules/vivawallet/success.php(42): PaymentModuleCore->validateOrder(17, '2', 10, 'Vivawallet', 'OrderCode: 9579...', Array, 1, false, 'd9dbd7d2e15eea3...') #3 {main} thrown in /home/brandcosmetics/public_html/classes/Tools.php on line 801

I cannot figure out what the issue might be. 

Do you need extra information ?

**Comment by VivaWalletSupport** [comment]
Thank you for your post, we will investigate the problem and develop a new version for PrestaShop 1.7.6 if needed.

**Comment by VivaWalletSupport** [comment]
Please use following for PrestaShop 1.7.x:
[vivawallet.zip](https://github.com/VivaPayments/API/files/3512057/vivawallet.zip)

Use following URLs on PrestaShop 1.7.x
Success URL: module/vivawallet/success
Failure URL: module/vivawallet/fail

Webhook (optional): module/vivawallet/webhook
