### ISSUE TITLE
Cannot get Bearer Token (randomly 504 Gateway Time-out)

### ISSUE THREAD

**Issue by LoggiaNG** [VivaPayments/API#994]
Hello, 
we need to use tokenization for payments with redirection.

We have tested the process through the week and it was working.
However, today that we opened it to production and tried to test it, we cannot get the bearer token to start our payment process (the same happens in the demo environment).
We saw the same thing also last Saturday, is there some kind of maintenance going on on Saturdays or is it some other error?

If we can't rely on this service to be stable we won't be able to use it... :/

![Screenshot 2019-08-10 at 10 41 48](https://user-images.githubusercontent.com/53644001/62819360-debfae00-bb5c-11e9-9f95-86d382d1ee57.png)

**Comment by matthewrgourd** [comment]
Hi there, 

I've tested on demo and there seems to be no issue now. Apologies for any previous down-time. In answer to your question, I'm afraid that at times our demo environment isn't 100% reliable. However, rest assured that the same cannot be said of production. For the latter you need to request credentials via my email address (mgourd@vivawallet.com) including the following information:

* Business name
* Merchant ID
* Contact email address

Thanks,

Matt
