### ISSUE TITLE
Error message 'The site is experiencing technical difficulties' on checkout screen

### ISSUE THREAD

**Issue by cnscurt** [VivaPayments/API#995]
I'm trying to install Vivawallet for a client of mine but have run into difficulty.
Once on the checkout page, I've getting the below error message...
![image](https://user-images.githubusercontent.com/54024131/62857997-0ba4ca00-bcf1-11e9-816a-6f6600e39eba.png)

I've changed the API key as mentioned in another thread, but that has not worked either.
Other settings are as follows...
![image](https://user-images.githubusercontent.com/54024131/62858097-49a1ee00-bcf1-11e9-833a-777023a5a58e.png)
![image](https://user-images.githubusercontent.com/54024131/62858129-61797200-bcf1-11e9-968a-0f591cdb71f9.png)
![image](https://user-images.githubusercontent.com/54024131/62858162-7ce47d00-bcf1-11e9-8519-2b596507e8a1.png)

I noticed in that other thread, that apparently their source code was incorrect, how would I check this is correct? I've un-installed and re-installed the plugin to make sure that wasn't the case, which still brings up the same issues.

If you need to reach via private message, please feel free to do so.
I hope to hear back from you soon.

Thanks
Curt

**Comment by VivaWalletSupport** [comment]
Hello, try specifying the source code (6858) instead of the source name in the plugin settings.

**Comment by cnscurt** [comment]
> Hello, try specifying the source code (6858) instead of the source name in the plugin settings.

That's worked.
Appreciate the help and speedy response.

Thanks,
Curt
