### ISSUE TITLE
Magento 1.9 Place order not redirecting

### ISSUE THREAD

**Issue by katragadda-sivaram** [VivaPayments/API#996]
When clicking on place order on one page checkout, customer not redirected to viva wallet page. It is stuck on the same page.
Stock levels are reducing which causes inventory discrepancies and no order is recorded in the back office.

**Comment by VivaWalletSupport** [comment]
Hello, please provide following 4 screenshots to check the problem.

Payment plugin settings (mask the API Key).
Viva Wallet payment source settings (include the browser's URL in the screenshot).
Viva Wallet Websites/Apps page (include the browser's URL in the screenshot).
API Access page (mask API Key, include the browser's URL in the screenshot).
