### ISSUE TITLE
Accepting Recurring Orders & Subcription Payments through Shopify

### ISSUE THREAD

**Issue by DrinkThreeDots** [VivaPayments/API#997]
Hi there,

We would like to begin taking recurring payments/set up subscription offers for customers who wish to receive our products on a regular basis. Is there a shopify app which can process this for us and through integration with your payment gateway?

Any help or guidance here would be greatly appreciated. 

Thanks!
Sean
DrinkThreeDots

**Comment by matthewrgourd** [comment]
Hi @DrinkThreeDots, apologies for the delayed response. I'm afraid we don't currently support recurring payments or subscriptions via our Shopify plugin.
