### ISSUE TITLE
No redirect after successful payment

### ISSUE THREAD

**Issue by pdx169** [VivaPayments/API#999]
I am trying to integrate Viva Wallet into CS-Cart 4.9.3. I am using the VivaWallet cs-cart 4 plugin.

I have set everything up for the integration however after vivawallet successfully takes a payment it doesn't redirect back to my website. I just remain on the Transaction details page. I have entered the Success URL & Failure URL. Do you know what might be going wrong?

On a side note i also notice that the logo i uploaded into vivawallet does not display.

Thank you
Bart

**Comment by VivaWalletSupport** [comment]
Hello, looks like you are not connecting to the payment source you would have created in your Viva account, please check the instructions given at https://developer.vivawallet.com/e-commerce-plugins/cscart4/

**Comment by pdx169** [comment]
I'd missed adding in the Source Code into CS-Cart. Added now and all working.

Thanks for the help
